### ISSUE TITLE
[Bug]: The reset widget option has wrong value for dropdown

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#10001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click the "on click" of an button and select the reset widget option, it shows wrong value under the "Reset Children" dropdown. Initially it shows true and onlclick it becomes Yes/No. 
<img width="1061" alt="Screenshot 2021-12-26 at 11 29 24 AM" src="https://user-images.githubusercontent.com/83352306/147399983-d0f30beb-86e4-43d1-b742-7d448dd0266b.png">
<img width="1061" alt="Screenshot 2021-12-26 at 11 29 51 AM" src="https://user-images.githubusercontent.com/83352306/147399984-ba6f4938-a0ec-4e02-af87-8001a9410269.png">

### Steps To Reproduce

1. Add a button widget
2. Go to "OnClick" event from property panel
3. Choose the reset form widget
4. Choose a widget from the Widget dropdown
5. Observe the behaviour of Reset Children dropdown

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Happens for every widget whenever an action is changed to reset widget.

In the behavior described above, by default the reset widget function parameter for reset children is empty. When empty, we are defaulting it to true and it is shown in the select field for reset children. 
<img width="269" alt="Screenshot 2021-12-29 at 10 54 38 AM" src="https://user-images.githubusercontent.com/19730984/147630054-c6e11f0c-562c-442f-96b3-2e1f34dc57a4.png">

If we change it, the parameter is explicitly set to true in the function. 
<img width="269" alt="Screenshot 2021-12-29 at 10 54 50 AM" src="https://user-images.githubusercontent.com/19730984/147630064-c8256ff9-5fd6-46ba-82bf-b8d9f4aa5523.png">

Proposed solutions from my side
1. We can show Yes as the default selected value in this case and also add "true" to the function parameters going forward for all new instances.
2. For existing apps/instances, we should just show Yes in the selected value for reset children when the parameter is empty and not add "true" in the function preventing migrations.

@somangshu can you suggest if this is a good way? Also is this something app viewers pod does or UI builders pod?

**Comment by somangshu** [comment]
This changed was made so that by default all children are reset because users were finding it difficult to perceive otherwise. @hetunandu I recall you had made this change, Can you tell us what POD can deal with this?

**Comment by dilippitchika** [comment]
Discussed with @Nikhil-Nandagopal , we should change the options to say true/false than Yes/no as it's inline with the function parameters. It would also be better, if we can add true by default in the function parameters rather than keeping it empty.
