### ISSUE TITLE
[Bug]: should allow empty string as value in array type properties in multiple widgets

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#10007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Due to our recent property [validation related fixes](https://github.com/appsmithorg/appsmith/pull/9476), Multiple widgets are not allowing empty string as values. This was working before and now it's breaking some of the user's applications.

- [x] Checkbox group widget 
- [x] MultiSelecttree widget
- [x] Multiselect widget
- [x] dropdown widget
- [x] radio group widget
- [x] single select tree
- [ ] switch group widget

### Steps To Reproduce

1. Add a single select widget to canvas (or anyone from the list above)
2. Add following array as options `[{"label": "option1", "value": ""}, {"label": "option2", "value": "2"}]`
3. Error is shown saying that invalid value.

Expected:
Should accept empty string `""` as the value in **one** of the option.
### Environment

Production

### Version

Cloud

**Comment by israrwz** [comment]
Besides the empty value, the issue also exists when an option's value is 0 (zero).

**Comment by sbalaji1192** [comment]
@israrwz Actually I'm able to use 0 as the value in select widget options. Could you give me an example options array where it's throwing an error?
![Screenshot 2021-12-28 at 10 31 36 AM](https://user-images.githubusercontent.com/5328605/147529978-120af8e4-dc71-40dd-857b-4dd59d52528d.png)
