### ISSUE TITLE
[Bug]: Unable to find Appsmith droplet on digital ocean marketplace

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#10000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As per the doc we have an Appsmith droplet on the Digital ocean marketplace, but currently, it's throwing an error as no droplet was found.

Ref link : https://marketplace.digitalocean.com/apps/appsmith ,

### Steps To Reproduce

1. Open the ref link
2. Check the error

### Environment

Production

### Version

Self-Hosted

**Comment by sharat87** [comment]
We are now back in action at <https://marketplace.digitalocean.com/apps/appsmith>.
