### ISSUE TITLE
[Bug]: Token is getting generated when we use v3 recatchaKey and keep captcha version as v2

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#10027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/15d9839a05184eb081ce847c0f8e638e-00001.gif)](https://www.loom.com/share/15d9839a05184eb081ce847c0f8e638e)

### Steps To Reproduce

1. Drag and drop a Button widget
2. Enter recatcha v3 key and keep version as v2
3. Click on Button widget
4. Observe that token is getting generated

### Environment

Production

### Version

Cloud

**Comment by vibhandikyash** [comment]
@vivekverma2312 Seems like the Google's Recaptcha has backward compatibility and the same key works for both versions. Also, upon investigation it seems like there is no such identifier which can state that this is of v2 or v3.
