### ISSUE TITLE
[Bug]: Input updates with default values are not captured

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#10026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This happens intermittently. At times the input widget value with default value does not update correctly

### Steps To Reproduce

This happens intermittently

- Have a table row value bound to an input widget default value
- Call a query/Api to save these inputs
- Switch rows and update the input with the same values
- Sometimes the input does not get saved with the right value

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu @rohan-arthur shouldn't we solve this with the stability issues epic? Seems like a stability issue to me

**Comment by dncpax** [comment]
I'm the original reporter. At the moment I cannot publish my app because updating a simple record sometimes fails silently to update some columns. So to be fair, appsmith fails to update a database table in a consistent way. I cannot stress this enough - it is impossible to deploy an app that sometimes does not save the data to the database and the user is unaware.

**Comment by rohan-arthur** [comment]
@dncpax we are looking into this on priority, will post updates here.

**Comment by dncpax** [comment]
@rohan-arthur thank you very much for the update.

**Comment by Rishabh-Rathod** [comment]
@hetunandu I was able to reproduce this issue again in the input field inside a modal but the same wasn't possible with the input widget either on canvas or inside CONTAINER  or FORM WIDGET, were you able to replicate it in other cases too?

**Comment by rohan-arthur** [comment]
@dncpax the fix is in process, we had earlier implemented a hacky way to fix this, but thought a more enduring solution would be better suited. This should be available soon, will update the ETA when I know more.

**Comment by dncpax** [comment]
@rohan-arthur Thanks for the update. I've been tracking progress. I'm taking the time to improve my app.

**Comment by dncpax** [comment]
not stale...

**Comment by Nikhil-Nandagopal** [comment]
@dncpax that's just our bot coming in to wake everyone up when an issue hasn't seen activity for awhile 😆 
We're working on how to solve this
