### ISSUE TITLE
[Bug]: Columns in the property pane changes on repeated clicking. Focused state color is black

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#10033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on any of the columns in the columns property of the table widget repeatedly, then the columns change their position automatically i.e. columns swap automatically. 
Also, it is observed that the focused state color has changed to black, as previously it was orange.

Please find below for your reference the video for this issue:
https://loom.com/share/c06009491e534d499abfe9fff912c4c2

### Steps To Reproduce

1. Drag and drop the table widget.
2. Go to the columns property in the property pane.
3. Click repeatedly on any of the rows.
4. Observe that they gets swapped automatically.
5. Also observe the focused state color of the row which is selected in this property. 

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Having trouble reproducing, checking with @keyurparalkar

**Comment by dilippitchika** [comment]
Ok, not reproducible in production but in release and dp. I guess we broke something in this component itself as this issue is also reproducible in tabs. Can we please prioritise this? else I guess this will impact production next @somangshu @sbalaji1192

<img width="287" alt="Screenshot 2021-12-29 at 11 07 41 AM" src="https://user-images.githubusercontent.com/19730984/147630634-46e04385-a3d1-4d25-b285-9d3b750c46a3.png">

**Comment by sbalaji1192** [comment]
@dilippitchika +1

**Comment by somangshu** [comment]
@aswathkk is this related to any property pane changes, Kindly check!

@keyurparalkar its the position of the cursor which updates and not the tile itself. Also I think the black border is intended as before this it seemed like there is some error in the tile. @vasanth-appsmith can confirm this. 

@vicky-primathon has your change related to tile repositioning gone in? Please check if that is true and this is related.

**Comment by somangshu** [comment]
related to #10030

**Comment by somangshu** [comment]
This change has been repeated, We will take this up with the actual implementation for the next release
