### ISSUE TITLE
[Bug]: Unable to edit the sub menu options in most of the widgets after repositioning the sub menus

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that unable to edit the sub menu options by clicking on the settings icon in most of the widgets like Button group widget, Table column edit, Tab widget

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c95928912e11456bab53751c8175fd54-00001.gif)](https://www.loom.com/share/c95928912e11456bab53751c8175fd54)

### Steps To Reproduce

1.Launch Appmsith app in release environment
2.Drag and drop button group widget 
3.Choose any of the sub button menu and click on setting options and observe

Similarly try for table widget and tab widget

### Environment

Release

### Version

Cloud

**Comment by YogeshJayaseelan** [comment]
@vicky-primathon @somangshu The same behaviour exists on Page properties as well and please look into the below video

https://www.loom.com/share/4edcc7b57c434ca994eddd7199fff773

**Comment by somangshu** [comment]
This change has been reverted, We will take this up with the actual implementation for the next release
