### ISSUE TITLE
[Bug]-[1300]:No error is shown on navigation if page name is invalid

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1004]
Using `navigateTo('NonExistentPageName')` should throw and error instead of navigating to a bad state

**Comment by vvkpd** [comment]
Could you please add more context on card?
Thanks

**Comment by navdeepsingh** [comment]
@Nikhil-Nandagopal Right now seems there is no limitation to enter Alphanumerics, special-characters into Page Name at top Navigation.
![Screen Shot 2021-03-22 at 4 24 27 PM](https://user-images.githubusercontent.com/2968787/111979466-1c532e00-8b2b-11eb-8fb9-9f45a51ffaac.png)
So we need to validate with some pattern?
The error message must be shown in the Toast box notification right?

cc @mohanarpit

**Comment by Nikhil-Nandagopal** [comment]
@navdeepsingh this seems like an unrelated issue. The name at the top is the app name not the page name
The problem here is that using the navigate function a user may configure
{{ navigateTo('RandomPageName') }}
and this does not throw an error to the user but instead navigates to a bad state.

**Comment by riodeuno** [comment]
Related to #2343

**Comment by Nikhil-Nandagopal** [comment]
@navdeepsingh just to clarify it is related to #2343 but this is also required because the user can navigate to an invalid page using JS mode

**Comment by vnodecg** [comment]
In `NavigationActionSaga.ts` check if the page is available in the `pageList` before pushing it to `history`. If the page is not present throw an show an error message saying the `Page is not available` instead of navigating

**Comment by hetunandu** [comment]
We need to create two new functions: `navigateToPage` and `navigateToUrl` with this strict validation. Existing `navigateTo` will call one of the above functions without validation

**Comment by rohan-arthur** [comment]
WIDGET_PROPERTY_UPDATE, updatedValue contains "{{navigateTo"
usage: 1300

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1300 |
| Effort (months)  | 0.5 |

**Comment by rimildeyjsr** [comment]
This issue is closed by https://github.com/appsmithorg/appsmith/pull/14856
