### ISSUE TITLE
[Bug]: The icon disappears in the input widget when the widget is resized 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the input widget with icon is resized the icon form the input widget disappears

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6f36a155aa2b4dbcb46895180b6b224c-00001.gif)](https://www.loom.com/share/6f36a155aa2b4dbcb46895180b6b224c)

### Steps To Reproduce

1.Launch appsmith app in release/Production Environment
2.Drag and drop Input widget
3.Add any icon to the input widget
4.Resize the widget and observe

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@momcilo-appsmith can you help with the design for this? How should the icon be aligned and how should the text be written in the input?

**Comment by momcilo-appsmith** [comment]
@dilippitchika The icon should be centered to the first line of text.

**Comment by dilippitchika** [comment]
This is not possible today, because input on resize becomes a text-area internally. Need to think on how to communicate this to users.

**Comment by momcilo-appsmith** [comment]
@somangshu @areyabhishek @riodeuno @dilippitchika what do you guys think about making a separate widget for the text area? We could also add an improvement to it - allowing the app viewers to resize it since this will be possible soon?

**Comment by dilippitchika** [comment]
My suggestion was to just make this explicit in the current input widget, if the input type is text then the dev can select if it's a multi-line text or a single line text. If multi-line then it's basically a text-area.

**Comment by somangshu** [comment]
@momcilo-appsmith I like the thought, But from how we separate widgets, I will argue that this should be separate. An idea for design would be if for the text area we bring the icon outside the field / textarea, aligned on the top.

**Comment by somangshu** [comment]
@dilippitchika @momcilo-appsmith we discussed this, and found that we are not able to find and example where the text area uses an icon. The current behaviour seems appropriate. Closing this for now
