### ISSUE TITLE
[Bug]: The icon in the input widget is slightly top aligned 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user adds any icon to the input widget and icon is slightly top aligned 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/a82e7394d2cf4d4aadb4b952404086fd-00001.gif)](https://www.loom.com/share/a82e7394d2cf4d4aadb4b952404086fd)

### Steps To Reproduce

1.Launch appmsith app in release/Production environment
2.Drag and drop Input widget 
3.Add any icon to the input widget and observe the icon alignment - To compare add any input text to the widget and compare the text alignment with the icon 

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Fixed in app-theming by @jsartisan #3369. Pawan please link this to your PR.
