### ISSUE TITLE
[Bug] Cloud hosted version should not show algolia

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1005]
## Summary
1. Create an account on https://app.appsmith.com
2. Open the help icon on the bottom left
3. See search by algolia symbol

**Comment by Jain-Sanchit** [comment]
@Nikhil-Nandagopal May I know the file path for this section ? I would like to work on this.

**Comment by mohanarpit** [comment]
@Jain-Sanchit I'm sorry. This got mislabeled as Hacktoberfest. Unfortunately, you don't have access to the cloud hosted version configuration keys as that is a private repository. I'm correcting the labels. Please pick another issue from our list.
