### ISSUE TITLE
[Bug]: API : Query Params does not get auto-added when parameter contains dynamic substitution

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#10055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Params added to API URL of static type gets auto-added to Query Params section. Of Dynamic nature doesnt.

### Steps To Reproduce

1. Create Api Datasource
2. Input the URL with static params:
3. Eg: https://cat-fact.herokuapp.com/facts/random?animal_type=cat
4. Observe Params tab - animal_type = cat is autoadded
5. Create another Api datasource
6. Input URL with dynamic param:
7. Eg:https://api.genderize.io?name={{Suggestions.data.type}}
8. Observe Params tab is not auto-filled with name as {{Suggestions.data.type}}

### Environment

Release

### Version

Self-Hosted

**Comment by rvkayy** [comment]
Did this get resolved? Facing the same issue . I want to dynamically make API request based on the user selection

**Comment by Nikhil-Nandagopal** [comment]
@rvkayy ys this should be working
