### ISSUE TITLE
[Bug]: Tooltip appears in an empty space

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tooltip appears when I mouse over an area of the property pane. After inspecting, I found that there's a question mark icon button that is white in color that making it hard to distinguish from the background white.

https://user-images.githubusercontent.com/10436935/147659693-e637539e-a14c-4896-862d-5e6580a566c3.mov

### Steps To Reproduce

1. Add a Table widget or tab widget where there is a panel
2. Goto property pane and open the property for a column
3. Point your mouse to the right side of column name and see the tooltip appears

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@aswathkk great find :'). 

Visible for any component which has configurable children. Table, Tabs etc. The message currently indicates how users can connect data to the child. 

Change the color of the icon - Make it similar to the delete/copy icon color in the parent
