### ISSUE TITLE
[Feature]: Scroll To Widget Function

### ISSUE THREAD

**Issue by tiger360** [appsmithorg/appsmith#10057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello,
I'd like to have a Scroll To Top button or specific section.
Thanks

### Why should this be worked on?

Especially on mobile when the list is very long  instead of scrolling .

**Comment by Nikhil-Nandagopal** [comment]
@tiger360 thank you for the feature request. A good way to solve this would be to allow users to call a function that scrolls to any widget on a page.

**Comment by oskarannas** [comment]
This one is similar to #8314, maybe the could be combined :)

**Comment by Nikhil-Nandagopal** [comment]
@oskarannas great catch! It is a duplicate of #8314
