### ISSUE TITLE
[Feature]: Requesting AWS Lambda in Data Sources similar to S3

### ISSUE THREAD

**Issue by awanishraj** [appsmithorg/appsmith#10073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Using S3 integration with Appsmith is very seamless. It just needs AccessKey and SecretKey. A similar interface to directly invoke Lambda functions would be very helpful. 

A direct API call to lambda is a bit involved due to request signing. 
[https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html
)

Currently, n8n has such an integration - [https://n8n.io/integrations/n8n-nodes-base.awsLambda](https://n8n.io/integrations/n8n-nodes-base.awsLambda)

### Why should this be worked on?

We use many lambdas for our internal use. Most of them are currently behind another server. Having this feature would make the API calls direct.

**Comment by rohan-arthur** [comment]
hi @awanishraj ,

Thank you for submitting this issue! I am a product manager here at Appsmith, and while this looks like an interesting problem, we would like to understand more about your needs. Would you please share more details about your use-case? 

Here are some clues to get started:
1. What language(s) are you using?
2. What is the type and size of the data that you'll be operating on?
3. How frequently do you expect to be making these calls?
4. Finally, why would you like this functionality in Appsmith? Why not let Appsmith only converse with AWS via API, and not handle the logic across the fence within AWS itself?

Happy to [get on a call](https://calendly.com/rohan-arthur/60min) with you as well to discuss this. 

Thanks,
Rohan

**Comment by Themercee** [comment]
This would indeed be a nice feature to have. Retools has this and we nearly go with them because of this 😅

**Comment by tristandibbens** [comment]
This works really nicely in Retool, please can we have this added
Thanks

**Comment by Maduranga** [comment]
Any update on this?
Have you guys figured out a way to call a Lambda function URL with cURL?
Is `--aws-sigv4` working for you?
Cheers.

**Comment by rmadabhushanam** [comment]
Any update on providing this ability? I think direct Lambda integration makes it easy to build a truly serverless experience for appsmith and opens up almost all AWS services to appsmith in a simple way.
