### ISSUE TITLE
[Bug] In case of wrong URL leading to connection refusal, HTTP 500 is not the correct error. Expose this to the client

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1007]
For example,

Incorrect URL : [numbersapi.com/159.65.220.83:443](http://numbersapi.com/159.65.220.83:443) (https://numbersapi.com)
Correct URL : http://numbersapi.com

We should return a proper error message instead of a generic HTTP 500 error from the server.

**Comment by CH-ND-N** [comment]
sir, please assign this to me.

**Comment by mohanarpit** [comment]
@CH-ND-N Welcome to Appsmith! :tada: 

In order to solve this issue, please check the file `RestApiPlugin.java` to see where the problem is.

**Comment by CH-ND-N** [comment]
ok sir I am on it.

**Comment by mohanarpit** [comment]
@CH-ND-N Since we haven't seen any updates from you on this issue, I'm unassigning it. I understand that something else would have come up. Whenever you have time, feel free to come back and check out our issues to pick another one.

**Comment by mohanarpit** [comment]
Closing as this is not an issue any more.
