### ISSUE TITLE
[Bug]: Multi Select Serverside Filtering Broken

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#10078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The multi select resets everytime the data changes making server side selection impossible
The same might be true of the select / tree select etc.

### Steps To Reproduce

1. Drag a multi select
2. Configure serverside pagination
3. Search for a term
4. The select closes making it impossible to select the searched term
5. App
https://app.appsmith.com/applications/61cd5be2a4437918c01f87af/pages/61cd8575a4437918c01f89b2/edit
Video
https://user-images.githubusercontent.com/3897254/147754697-23ce688e-e5c8-4f52-9d73-599f09abcc6b.mov

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
https://user-images.githubusercontent.com/11089579/147755742-a760e6b8-c680-4fc4-a813-b67eb146e7dc.mov

**Comment by Nikhil-Nandagopal** [comment]
onFilter Update is also getting called every time I select an option here. Very broken experience

**Comment by sbalaji1192** [comment]
Closing this in favour of https://github.com/appsmithorg/appsmith/issues/10297
