### ISSUE TITLE
[Bug]: Logging out when app is partially loaded causes incorrect error handling

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user logs out during app load, then user is redirected to `server unavailable` error instead of login page and going back on the browser page does a myriad of things that looks glitchy.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3a27cb3949364d4192efc585fd3ebecc-00001.gif)](https://www.loom.com/share/3a27cb3949364d4192efc585fd3ebecc)

### Steps To Reproduce

1, log out when an app is being freshly loaded
2. try to navigate back on the browser

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore
