### ISSUE TITLE
[Bug]: Bindings are expanded from preview view for query's on entity explorer

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 `Show bindings` options are automatically expanded if one queries bindings are expanded
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c6b07ca69abe4587bae1208fa22c8155-00001.gif)](https://www.loom.com/share/c6b07ca69abe4587bae1208fa22c8155)

### Steps To Reproduce

1. Go to entity explorer and click on any query
2. Select `show bindings`, see that all options are collapsed
3. Expand a few and now switch to see bindings of other queries

### Environment

Deploy Preview

### Version

Cloud

**Comment by arunvjn** [comment]
Fixed in the latest explorer DP.

**Comment by arunvjn** [comment]
@ramsaptami Can you please retest ?

**Comment by ramsaptami** [comment]
It's been fixed hence closing the issue.
