### ISSUE TITLE
[Bug]: We could not connect to our servers please check your internet connection - Getting this error when accessing appsmith from browser

### ISSUE THREAD

**Issue by kpchandr** [appsmithorg/appsmith#10093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running appsmith on kubernetes and when i access the appsmith using Loadbalancer Ip from browser , getting below error message

We could not connect to our servers please check your internet connection 

### Steps To Reproduce

install on kubernetes using below link 
https://docs.appsmith.com/setup/kubernetes
expose it to internet using ingress and access from browser using ingress IP

### Environment

Production

### Version

Cloud

**Comment by kpchandr** [comment]
When i describe appsmith internal server pod i can see liveness probe is failing

Warning  Unhealthy  7m18s (x9 over 8m13s)  kubelet            Liveness probe failed: Get "http://10.0.0.194:8080/api/v1/users/me": dial tcp 10.0.0.194:8080: connect: connection refused

**Comment by un-fuf-a-doo** [comment]
I just want to add that on-premise Docker starts up successfully, but we also are getting connection refused. We have tried with iptables and without iptables, neither are successful.

Server is headless Ubuntu 21.10, so I cannot test via localhost. Telnet connection to all ports 80, 443, 9001 answer. Only in the browser do we see connection refused.

**Comment by sharat87** [comment]
Hey @kpchandr, it sounds like your backend service isn't running. Is it possible to get the logs from the backend pod to see why it's failing to start?

**Comment by sharat87** [comment]
Hey @un-fuf-a-doo, may I ask if you are also running on Kubernetes? If not, then I think you are facing a different issue. Let's move to another issue to investigate the problem. If you are indeed also running Kubernetes, can you share the logs from your backend pod to see why it might be having trouble working right?

**Comment by un-fuf-a-doo** [comment]
No mine is a Docker issue, but it is the exact same.  We fixed our issue by running AppSmith on a higher port number, above 1024 and it works.  We don't know why it won't run on port 80, we have no other services using it.

**Comment by Nikhil-Nandagopal** [comment]
Closing this and adding allowed ports to our docs
