### ISSUE TITLE
[Bug]: The label text truncates on resizing the input widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user resizes the input widget the label text truncates when the text size is chosen as Heading 1

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/a1a0ce96a6754d8b9f50b2db34b9cfc5-00001.gif)](https://www.loom.com/share/a1a0ce96a6754d8b9f50b2db34b9cfc5)

### Steps To Reproduce

1.Launch appmsith app in release/Production environment 
2.Drag and drop Input widget
3.Add label text
4.Resize the widget position - Top to bottom 
5.Choose the text size as heading 1 and observe

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Needs to be solved, when label text size changes the input area needs to decrease accordingly. 

@somangshu adding this to product backlog. Can we assign this to Paul to be picked up after the label enhancements ?

**Comment by wmdev0808** [comment]
This issue has been fixed on the PR at https://github.com/appsmithorg/appsmith/pull/10600
