### ISSUE TITLE
[Bug]: Search field is not working for all columns when app is generated using CRUD

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4a0db676072a451fb41a32726c1e9ecb-00001.gif)](https://www.loom.com/share/4a0db676072a451fb41a32726c1e9ecb)

Expectation: Search should work for all the columns if none of the field is selected at the time of creating new page as a searchable column

### Steps To Reproduce

1. Create a CRUD app using any DB like Postgre
2. Select a table
3. keep blank for "Select a searchable column from the selected table" dropdown
4. Generate Page
5. Try to search keywords of different columns
6. Observe there is a blank table for all columns except any one

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@chandannkumar this is not a bug, only a single field can be made searchable at a time. If nothing is selected, nothing will be searched
