### ISSUE TITLE
[Bug]: Autocomplete needs to show async await keywords instead of showing 'no suggestions'

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, `async`, `await` keywords etc... are displayed as no suggestions by autocomplete and these needs to be added into autocomplete suggestions

### Steps To Reproduce

1. Try using promises keywords in JS editor or on action fields of the property pane and observe autocomplete show `no suggestions` instead

### Environment

Release

### Version

Cloud

**Comment by hetunandu** [comment]
Happens for action.run functions and async JS functions

**Comment by eco-monk** [comment]
Removed High label because, it's only async await keywords that are missing.
.then, .catch are available on actions. need to look into async functions.

**Comment by bharath31** [comment]
@satbir121 can we add `async` and `await` to autocomplete results?
