### ISSUE TITLE
[Bug]: On adding regex the error message is not displayed persistently in the input widget

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by passing the invalid value regex error message is not displayed 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/072523bab3454bcc84227a98a3d75f38-00001.gif)](https://www.loom.com/share/072523bab3454bcc84227a98a3d75f38)

### Steps To Reproduce

1.Launch appmsith app in release/Prod environment
2.Drag and drop input widget 
3.Add regex as [a-z]
4. Pass the following value in the input ADSFDF#%$^ observe error message will be displayed 
5. Pass the following value DDSFFr or VGHT#e any invalid values with any small letters and observe - No error message is displayed

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@YogeshJayaseelan can you check the same issue in here. https://www.regextester.com/ 

According to this the second text "DDSFFr" is valid for [a-z]

**Comment by vibhandikyash** [comment]
@YogeshJayaseelan Here it seems like there is an issue with the regex. The one that you've mentioned in the above video is fuzzy regex and will only check if 1 char of it is in lowercase and will validate.
Pl. recheck with this regex: `^[a-z]+$`
https://images.zenhubusercontent.com/275993885/3e3f7679-73d5-48b1-b253-f0add4b0429d/screen_recording_2022_01_27_at_3_09_04_pm.mov
