### ISSUE TITLE
[Bug]: The run button loads in infinte loop

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The run button loads in an infinite loop in data sources
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2ffb50c00d4c43c9a6156ca52cfef960-00001.gif)](https://www.loom.com/share/2ffb50c00d4c43c9a6156ca52cfef960)

### Steps To Reproduce

1. I am facing the issue in the below app
2. https://release.app.appsmith.com/applications/61d2a525a201f119979dd6c9/pages/61d2a525a201f119979dd6cc

### Environment

Release

### Version

Cloud

**Comment by sumitsum** [comment]
Looks like a FE issue. The client is not making executeAction API call.
![Screenshot 2022-01-03 at 8 18 51 PM](https://user-images.githubusercontent.com/1757421/147944571-4c212fb8-2ffd-4a9e-8b4f-bfafc0cfec6c.png)

**Comment by AmanAgarwal041** [comment]
Re-opened this issue because an edge case was missed.
### Reproduction steps

When we update the query `very fast` but the previous value and ending value remains same eg. `ABCD` we remove `D` and then add `D` so the ending data remains `ABCD`  and we hit `CMD+ENTER` for running the query. Then the loading state remains in the infinite loading state.

**Comment by RakshaKShetty** [comment]
reopening the issue need to fix one corner case https://www.loom.com/share/45f67edbb70e46faa0169192c7152abd

**Comment by sribalajig** [comment]
Effort - 3 Days

**Comment by saiprabhu-dandanayak** [comment]
**@AmanAgarwal041 , @Nikhil-Nandagopal , @RakshaKShetty** , is the bug still persisting? When I try to replicate the issue, it works fine for me. Could you please confirm?

**Comment by Nikhil-Nandagopal** [comment]
@saiprabhu-dandanayak it looks like it was fixed
