### ISSUE TITLE
[Bug]: Video overlapping after video stops while stretching widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/868f1d4e0d844a6abb76363e7bdf7e90-00001.gif)](https://www.loom.com/share/868f1d4e0d844a6abb76363e7bdf7e90)

### Steps To Reproduce

1. Drag and drop new camera widget onto canvas
2. Change the camera Mode to Video
3. Make a video
4. After you stop recording the video stretch the Camera widget horizontally and observe
5. You will observe a video overlapping in Preview mode

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@wmdev0808 please verify and close this is already resolved

**Comment by wmdev0808** [comment]
@somangshu ,
This issue has already been fixed by the [PR](https://github.com/appsmithorg/appsmith/pull/10943).
I've verified that.
