### ISSUE TITLE
[Bug]-[9944]:Clicking on the settings badge of a modal doesn't open the properties

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#10128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a modal with some widgets inside it. When I am looking at the properties of a widget inside the modal, and then I click on the "settings badge" of the modal itself, I expect to see the properties of the modal but nothing happens. 

But settings badge I mean this: 
![Screenshot 2022-01-03 at 20 34 22](https://user-images.githubusercontent.com/94514895/147946318-d0f733a0-6294-489a-ab7b-b3cbf5b1fd09.png)

Video:

https://user-images.githubusercontent.com/94514895/147946872-ddec3902-0676-4cfe-889f-67fea00f824a.mov

Uploading Screen Recording 2022-01-03 at 20.35.28.mov…

### Steps To Reproduce

1. Create a modal with some widgets inside it, say, a text widgets "Text1" and "Text2"
2. Go to the Text1, you will see the property pane for Text1
3. Click on the settings badge for Text2, you will see the property pane for Text2
4. Establish that you can see the properties of a widget either by clicking on the widget or by clicking the settings badge
5. Now click the settings badge on the modal --> you should now see the properties of the modal, but nothing happens
6. Click in any empty space in the modal, and this mode of opening the property pane of a modal seems to work ok

### Environment

Production

### Version

Cloud

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1243 |
| Effort (months)  | 0.25 |
