### ISSUE TITLE
[Bug]: Always keep the camera dimensions intact on resize.

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6b3b69d0b6424e70a9ad4e0c3e7d9082-00001.gif)](https://www.loom.com/share/6b3b69d0b6424e70a9ad4e0c3e7d9082)

### Steps To Reproduce

1. Drag and drop new camera widget onto canvas
2. Change the camera Mode to Video and Deploy the application
3. Start recording the video
4. Stop the video and observe the video preview gets change in appearance and feels like video is running in full screen mode even if widget is in other resolution

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
The fix to this is to keep the camera dimensions contained within the width and the height of the bounding box like css object-fit contain property. 

This will help retain the size and not confuse our users about the jerk in the images or videos.

**Comment by somangshu** [comment]
@wmdev0808 is this fixed? This was not linked to any PR and hence the auto labelling did not happen, If we have fixed this we need to make sure we link all such issue to a PR, if its missed after closing we make sure to add the `QA` label to the issue

**Comment by wmdev0808** [comment]
@somangshu ,
It has already been fixed by PR [#10943 ](https://github.com/appsmithorg/appsmith/pull/10943).
I've linked to the PR
