### ISSUE TITLE
[Bug]: Deleting administrator user throws error in 'Members' page. 

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user is in 'Members' page and an admin user is deleted, page throws error. (refer video for detail walkthrough)
![image](https://user-images.githubusercontent.com/92293815/147927550-e9e5868c-78ed-4af7-845c-e99acf2f00a7.png)

https://loom.com/share/91d301a63fe2439eb346e189ce87ed35

Expected behavior: On page refresh the user must be redirected to home page.

### Steps To Reproduce

1. Login with UserA and create an org
2. In Org > Share > Manage Users > Invite users > Enter UserB email id and provide Administrator role
3. In another browser login with UserB details and verify UserA organization is present. Now in the organization present > Share > Manage users > Delete UserA from the list.
4. Go back to UserA browser and click on refresh and observe the error.

### Environment

Release

### Version

Cloud

**Comment by deepika-appsmith** [comment]
We no longer have the error toast messages, instead we get a blank screen on clicking back we end up on homepage. Attached the video for reference

https://github.com/appsmithorg/appsmith/assets/161307325/968a4cd5-5fe4-40e6-910e-a4dd64f80745
