### ISSUE TITLE
[Feature]: Allow export / import of action

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#10127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, we have an export / import feature that works at the application scope. However, it does not address the use case where a user might want to import one or many actions from one application to another. They may not want to import / export the whole application - but they might be interested in certain action configurations since these action configurations could serve as a starting point for them - e.g. if a user has configured an action with 10 input fields (form based input) - and if they want to copy the same action config across applications - then copying each field one by one is too tedious. 

### Why should this be worked on?

- Improve user experience and application usability. 
- Cut down on development time.

**Comment by riteshkew** [comment]
Closing this as Modules/Packages should be able to provide a resolution for this.
