### ISSUE TITLE
[Bug]-[20]:Bindings pop-up window design is different from other pop-ups

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bindings pop-up has a glow effect to its border that's not present on other pop-ups in the app

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c6b07ca69abe4587bae1208fa22c8155-00001.gif)](https://www.loom.com/share/c6b07ca69abe4587bae1208fa22c8155)

### Environment

Deploy Preview

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 20 |
| Effort (months)  | 0.5|
