### ISSUE TITLE
[Enhancement]: Support admins to reset passwords for users in self hosted instances without SMTP

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User doesn't have any local SMTP to use for sending Emails and would like to set or reset passwords for users. This can be done by adding support in the Admin settings UI. 

### Steps To Reproduce

1. Don't configure SMTP in self-hosted instances
2. Reset password

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika I think this is a duplicate of #3906
