### ISSUE TITLE
[Enhancement]: Support for default labels in select/multi-select for server-side filtering cases

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a new default label property in select and multi-select which will help surfacing defaults when the data is not present on the client side. 

### Why should this be worked on?

Currently, the default value property in select/multi-select cannot be used for data which resides on the server.

**Comment by somangshu** [comment]
@dilippitchika a little more information on how this property will function is required, Can you leave a note here regarding the same?

**Comment by dilippitchika** [comment]
@somangshu closing this as it's already covered in the PRD of #10297
