### ISSUE TITLE
[Bug]: Success or error call for promises in a JS object does not work unless return keyword is used for the function

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Success or error alert from a JS object inside a `promise` does not work until `return` keyword is used on the function.
For e.g., following code works only when the return keyword is present:
```
return myFunc1()
.then(() => showAlert("onSuccess call"))
.catch(() => showAlert("onError call"))
```

Similarly, when chaining JS, return needs to be included to execute onSuccess and onError code. For example:
```
Api1.run()
.then(() => { 
    Api2.run()
    return myFunc1()
```

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3250b3db55e642648d62e7ca21faf880-00001.gif)](https://www.loom.com/share/3250b3db55e642648d62e7ca21faf880)

### Steps To Reproduce

1. Use `promise` and display a showAlert on success and error
2. Observe all functions within `promise` call have been executed but success/error code is not executed.
3. Use return keyword before executing the promise and you'll see onSuccess and onError calls executed as expected

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment]
**When promises is called from a widget**
https://www.loom.com/share/5eb705672cb04d5fbba9fe3cbeb01c15

**When promises is called from another promise**
https://www.loom.com/share/7de08cbe96864bde9e7c148e8353120c

**Comment by ApekshaBhosale** [comment]
@ramsaptami return is needed because if you don't return the promise, the platform will close the request and not process any events from the worker

cc @hetunandu 

5:39
You need to return the promise to be able to process is properly

**Comment by ajinkyakulkarni** [comment]
@Nikhil-Nandagopal Need your input on this issue.

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni @ApekshaBhosale @hetunandu is it possible to detect a promise literal when we parse the JS and then auto flag it as async?
