### ISSUE TITLE
[Bug]: Grouped widgets in a container can't be moved back on to the canvas

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Widgets that have been grouped can't be moved back onto canvas since it appears as a red block where ever the widget is moved (even when the widget size fits in the area)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/140db5381ced4b8d8fab3b880ca39880-00001.gif)](https://www.loom.com/share/140db5381ced4b8d8fab3b880ca39880)

### Steps To Reproduce

1. Group fairly largely sized widgets and then try to move them back onto the canvas

### Environment

Release

### Version

Cloud

**Comment by kamakshibhat-appsmith** [comment]
Not occuring anymore, Closing this
