### ISSUE TITLE
[Bug]: Sample Heroku Endpoint for Custom Authentication is failing

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I hit the url mentioned in the guide to create a sample custom authentication app- https://docs.appsmith.com/how-to-guides/how-to-implement-custom-authentication-on-appsmith

It returns a not found error. https://appsmith-tutorial-apis.herokuapp.com/auth/loca
<img width="1013" alt="Screenshot 2022-01-05 at 10 13 17 AM" src="https://user-images.githubusercontent.com/19730984/148161706-febcec46-408b-4876-a3b6-4620d946d111.png">
l

### Steps To Reproduce

1. Open Postman/ Curl
2. Send a Post request to https://appsmith-tutorial-apis.herokuapp.com/auth/local
3. For more details follow the steps in the doc - https://docs.appsmith.com/how-to-guides/how-to-implement-custom-authentication-on-appsmith

### Environment

Production

### Version

Cloud

**Comment by vihar** [comment]
@dilippitchika, can you test this out? The issue is now fixed.

**Comment by dilippitchika** [comment]
Hey @vihar yes this is working now, closing the issue.
