### ISSUE TITLE
[Bug]: Intermittent : Data do not populate on table after binding the query until refresh the screen

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#10167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d7dd05f7fb0743f28c3765d8da298632-00001.gif)](https://www.loom.com/share/d7dd05f7fb0743f28c3765d8da298632)

### Steps To Reproduce

Tried binding the query on Table widget and data is not populated on table but evaluated below shows the data

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Will wait for more evidence on this, tried reproducing but couldn't observe.

**Comment by somangshu** [comment]
Cannot reproduce this. 

@vivekverma2312 one suggestion, Please keep the chrome dev tools open, if could be helpful to look at the console in these cases, We might be missing something very critical
