### ISSUE TITLE
[Bug]-[424]:showAlert does not read multi line content and shows error when it encounters a new line

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`showAlert()` displays a syntax error on prod and uncaught promise rejection on current release when trying to display multi-line content.

This gets especially bad for the user when using non-JS mode on trigger field and multiple lines are entered in the `message` box
![image](https://user-images.githubusercontent.com/79509062/148165317-18346370-2ecf-4a27-8429-5ea6e00459d3.png)

![image](https://user-images.githubusercontent.com/79509062/148164957-926ddb0a-4af0-4ab5-8153-980d5a0ad378.png)

### Steps To Reproduce

1. Use multi-line content inside of a `showAlert()` and observe error handling as seen in the screenshots above

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
reach: 81

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 53 |
| Effort (months)  | 0.25 |

**Comment by rimildeyjsr** [comment]
Update on bug - we dont see an error but only one line is read and the other lines ignored

**Comment by arunvjn** [comment]
Fixed in https://appsmith-c5su55jan-get-appsmith.vercel.app/

**Comment by AnandiKulkarni** [comment]
Invalid unexpected token is given - {{showAlert('Msg line 1\nMsg Line 2\nMsg line 3', '');}}

add space to the next line. -  {{showAlert('Msg line 1\n
						Msg Line 2\nMsg line 3', '');}}
Trigger it - error is displayed

**Comment by AnandiKulkarni** [comment]
On discussion - verified and closing the issue
