### ISSUE TITLE
[Feature] Integrate with Redis

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1016]
## Summary

We would like to integrate with Redis DB.

## Motivation

Redis DB is a commonly used caching database for quick access of data. We would like to integrate with it to provide users a better experience with Appsmith

## Additional Context

For this issue, we will operate almost exclusively in the maven module `appsmith-plugins` . Each of these integrations is a plugin to the Appsmith platform. 

1. In the module `appsmith-plugins` , create a new module for the specific integration that you are developing. Copy the `pom.xml` from other modules to ensure that you have the basic structure in place.
2. Add the name of your new module to the parent `pom.xml` in `appsmith-plugins`. If you don't add this, your plugin will not be compiled.
3. When you write a plugin, you will also add test cases for this plugin. Please check the other plugins as a sample for how to do this. For databases, we will use [https://www.testcontainers.org/](https://www.testcontainers.org/) for bringing up containers to test against.
4. For all plugins, the interface that the plugin implementation needs to satisfy is: `PluginExecutor.java`
5. Each integration must support basic CRUD capabilities. Any additional features may be mentioned later through a separate issue/PR.

**Comment by pc9795** [comment]
I am looking 👀 into this
