### ISSUE TITLE
[Bug]: The hide and unhide functionality are swapped by hiding a column and pressing cmd+z for redo

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by hiding  any columns in the table property pane and by pressing cmd+z the hided column will be re-displayed but the unhide icon will be displayed in the property pane and which is turn pressing the unhide icon will agaon hie the column 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7131e43d790a41959cb6e5a103f38202-00001.gif)](https://www.loom.com/share/7131e43d790a41959cb6e5a103f38202)

### Steps To Reproduce

1.Launch appsmith app in release/Production environment 
2.Drag and drop table widget
3.Open property pane 
4.Hide any of the column by clicking on hide icon 
5.Press cmd+z for redo and check the column will be displayed in the table widget but still in the property pane hide icon will be displayed

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
This is more of a re-rendering issue when it comes to undo/redo, Opening the same property pane again shows the correct changes

cc @jsartisan @marks0351

**Comment by riodeuno** [comment]
@prsidhu @sbalaji1192 This seems to be a standard data integrity issue, where there are multiple sources for the truth about the hidden columns. We should update the code, so that this property is taken from on source which should ideally be the primaryColumns configuration for the column in question.
