### ISSUE TITLE
[Bug]: There is no space between Text size and pixel for Text size property on property pane

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#10171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="280" alt="Screenshot 2022-01-05 at 1 23 15 PM" src="https://user-images.githubusercontent.com/83569920/148180929-41b2e007-3f32-4674-99db-107d2feb1f16.png">

### Steps To Reproduce

1. Drag and drop a Table widget
2. On property pane go to Text size property
3. Select Heading3 Option from drop-dopwn which is 16px
4. After selection it looks `Heading316px`

### Environment

Release

### Version

Cloud

**Comment by aswathkk** [comment]
Closing this since I'm unable to reproduce this.
