### ISSUE TITLE
[Bug]: Redo is not happening after deleting a button from button group 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user deletes any button from the button group property and clicking on cmd+z shows the deleted button in the property pane but not in the widget 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9c76f0baf13e4cb5a5df3eb27ae0b96b-00001.gif)](https://www.loom.com/share/9c76f0baf13e4cb5a5df3eb27ae0b96b)

### Steps To Reproduce

1.Launch appmsith app in release/Production environment 
2.Drag and drop button group widget 
3.Open property pane 
4.Delete any of the button 
5.Press cmd+Z
7.Check for the deleted button in the widget 

### Environment

Production

### Version

Cloud

**Comment by YogeshJayaseelan** [comment]
This is the same behaviour for Menu Button widget as well

**Comment by somangshu** [comment]
@jsartisan @techbhavin need you guys to triage this and propose a probable solution, Let me know what is required here

**Comment by jsartisan** [comment]
This should work out of the box. Will take a look

**Comment by btsgh** [comment]
Tested the following on Release: 
1. Menu button widget - Reordering menu items in property pane is reflected in the Menu button widget 
2. Menu button widget - Deleting one menu item in property pane is reflected in the widget, also, on Cmd + Z (redo), bringing back the menu item in property pane is reflected in the widget.
3. Menu button widget - Clicking the settings icon on each of the menu items, opens up the property pane of the correct menu item's settings.
4. Tab widget - Reordering tab items in property pane is reflected in the tab widget 
5. Tab widget - Deleting one menu item in property pane is reflected in the widget, also, on Cmd + Z (redo), bringing back the menu item in property pane is reflected in the widget.
6. Tab widget - Clicking the settings icon on each of the tabs in the property pane, opens up the corresponding property pane of the correct tab's settings.
7. Button group widget - Reordering buttons in property pane is reflected in the button group widget.
8. Button group widget - Deleting one button in property pane is reflected in the button group widget, also, on Cmd + Z (redo), bringing back the button item in property pane is reflected in the widget.
9. Button group widget - Clicking the settings icon on each of the buttons in the property pane, opens up the corresponding property pane of the correct button's settings.

**Comment by somangshu** [comment]
@Aishwarya-U-R can you kindly check if these 👆  use cases are covered by out test suit. Seems trivial but prone to regression
