### ISSUE TITLE
[Template]: Bulk upload data

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#10176]
### Title

Insert CSV into database

### Objective

A user uploads a CSV/spreadsheet, which will be of a particular format, which the user can see and download.

A user is able to add a single entry using a Modal, OR upload a CSV/spreadsheet file which must match the existing format. The tool will validate the file, and append the table data to the database.

functionality to be highlighted:
File picker
Data validation using JS editor

### Wireframes

https://www.figma.com/file/0k6nAag845scrCkqd3YqlR/Bulk-Upload?node-id=0%3A1

### Validation criteria

The user should be able to upload CSV files only
The file should match the format of the existing table defined
The app should populate the data into the correct columns
The user should be able to add image and document links to the system as well, and they will be displayable on the database

### Use case

Martketing

### Industry

Real Estate

### Data sources

Any

**Comment by ducviet98** [comment]
Hi, is Feature released?

**Comment by kocharrahul7** [comment]
https://app.appsmith.com/bulk-insert-update/bulk-insert-update-623cd37b4d9aea1b062b347b
