### ISSUE TITLE
[Feature] Allow inviting other GitHub users to Appsmith

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1018]
## Summary

Today we can invite users by using their email id, but we can't invite developers with GitHub accounts. So my Appsmith account with GitHub id can't be invited to any other organization.

Feature requests:
1. Invite GitHub user ids
2. Notify them if possible(maybe ask for email ids to notify?)
3. Allow user to sign up using GitHub(or email that was added during the invite process)
4. 

Reference
Slack, Airtable

**Comment by pranavkanade** [comment]
A user raised this issue on Intercom last week, with some pointers - 
```
The user:email scope allows an app to access a user's email addresses. See https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps. For further discussions, also see https://github.com/nextauthjs/next-auth/issues/374 and https://github.com/thephpleague/oauth2-github/issues/3.
```

**Comment by lptr** [comment]
Same problem here. In my organization GitHub is the go-to authentication method, and that's how I'd like to control access to Appsmith as well. It would be nice if Appsmith fetched the user email automatically, but being able to update it manually would be a good workaround for now, too.

**Comment by nsteblay** [comment]
I have similar issues.  I understand the constraint helps promote purchasing the enterprise edition.  But many who are contemplating purchasing will be using Github authentication and will need a way to invite users to specific workspaces.  This all but makes using Github authentication untenable.  I would highly recommend prioritizing this feature.
