### ISSUE TITLE
[Bug]: gzip is not turned on release and some self hosted instances.

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#10180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On release and some self hosted instances, gzip is not enabled. Please check the screenshot below.

<img width="1421" alt="Screenshot 2022-01-05 at 12 06 40 PM" src="https://user-images.githubusercontent.com/441914/148196688-11c057f8-8810-4847-bdd4-a77f0103d785.png">
<img width="1417" alt="Screenshot 2022-01-05 at 12 06 23 PM" src="https://user-images.githubusercontent.com/441914/148196702-14ab81ac-63a0-4e1a-88fb-f7a2b7ec7600.png">

### Steps To Reproduce

1. Open Appsmith app on chrome.
2. Goto network tab and see the content-encoding header.

On release content is not gzipped, and the transfer size is more than twice of the gzipped file on prod.

### Environment

Release

### Version

Self-Hosted

**Comment by SatishGandham** [comment]
@pratapaprasanna , See if we can enable gzip for `/execute` calls as well.

**Comment by SatishGandham** [comment]
While you are here, see if you can address this as well
#10503

**Comment by tolgaulas** [comment]
This is still valid on the latest release and has impact as in #17829

**Comment by tolgaulas** [comment]
This issue is solved by adding the following custom header into the API definiton in appsmith  : `accept-encoding: identity` as defined in https://www.rfc-editor.org/rfc/rfc2616#section-14.3

**Comment by somangshu** [comment]
@tolgaulas we shall check that internally and revert back to you

cc @sharat87 @pratapaprasanna

**Comment by pratapaprasanna** [comment]
![Screenshot 2022-10-26 at 3 52 54 PM](https://user-images.githubusercontent.com/15846947/198003569-f834276f-a2ca-4d3c-9aad-09bd0a96b2a8.png)

We see this in our release environment. therefore closing this issue
