### ISSUE TITLE
[Bug]-[1000]:Forking large apps throws a timeout error but app card is created and trying to launch this fails

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Forking large apps throws a timeout error but app card is created and trying to launch this fails.

![image](https://user-images.githubusercontent.com/79509062/148215562-94a9df04-5303-456f-a01b-4c4c3d413a2e.png)
![image](https://user-images.githubusercontent.com/79509062/148215987-2695ada5-e0cb-45d5-8afa-c76ad364acc8.png)

### Steps To Reproduce

1. Try to fork GitHub Manager on app.appsmith.com
2. Observe forking fails with a timeout error as seen in the screenshot, but app card is created which fails to launch

### Environment

Production

### Version

Cloud

**Comment by ramsaptami** [comment]
Once forking fails with "Appsmith timed out" message, the pop-up does not close until manually dismissed.

Attempting to fork the app again, causes an odd behaviour as seen in the video below.
https://www.loom.com/share/1a7755acb9204a83a3be73e2ce4598a7

**Comment by abhvsn** [comment]
@ramsaptami are we still facing this issue?

**Comment by ramsaptami** [comment]
Still seeing the timeout error @abhvsn

**Comment by abhvsn** [comment]
Reopening this as this is still happening with some apps

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | 1 |

**Comment by abhvsn** [comment]
This was happening for github manager app which had around 90k JSObjects attached to this app, but we have done some clean up and this is working as expected after that. We have another issue though in case of timeout app card will be created and the application will be in a sane state, so we are improving the UX in such cases which is being tracked in another issue https://github.com/appsmithorg/appsmith/issues/13503.   

Discussion around the issue with `Github Manager` application https://theappsmith.slack.com/archives/CGBPVEJ5C/p1651822294533249

Closing this as this is now being tracked as timeout exception
