### ISSUE TITLE
[Task]: Design System Improvements

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#10186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Align the radio button in the DS. Today the radio button is centre aligned with the text. We should top align it with the text.
- When deleting a datasource the delete option is on top. The delete option should always be at the bottom.
- Inside pages setting when there is only one page we should disable the drag cursor which appears. The spacing and the sizes of the icons are slightly off.
- Migrating the share application modal to the new version in the DS.

**Comment by albinAppsmith** [comment]
- Colour of settings, copy and delete icons are different on page properties
- Organization image on Org settings page trims off the boundary when image is loaded
- The arrow size is very small - debug
