### ISSUE TITLE
[Bug]: While adding document viewer inside the container widget, it shows 'iframe' as a popup for only 1st time

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2945ae11c55f492995e323f93cbdb576-00001.gif)](https://www.loom.com/share/2945ae11c55f492995e323f93cbdb576)

### Steps To Reproduce

1. Add a container widget
2. Add a document viewer widget inside container widget
3. After adding document viewer widget inside container, do not move the cursor and observe there will a popup of iframe at document viewer widget

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
I don't think we should consider this a bug and move on from it
