### ISSUE TITLE
Widget enhancements Q1 22

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#10200]
## Objective: 
enhancing the existing widgets, such that we add more value for the community, making our existing widgets function better

## Success metrics:
- Community requests are resolved
- More use case coverage without adding new widgets

## RACI Matrix:

| Responsible | Accountable | Consulted | Informed | 
| ----- | ----- | ----- | ----- |
| @vibhandikyash @wmdev0808 @techbhavin @Tooluloope @vicky-primathon | @Tooluloope | | @somangshu @dilippitchika |

**Comment by somangshu** [comment]
Notes WE Q1 22:

- 22 issues total
- None is estimated 
- 9 issues in needs design / PRD, @momcilo-appsmith / @dilippitchika to revert
- 4 issues in needs info & icebox, should be divided between the team
- the team further decides if the issues should be picked up, if all relevant information is available, if picking up add the estimate and move the issue to product backlog, else drop a relevant comment, remove it from the epic and move it back to icebox, you could also choose to assign me / @dilippitchika here
- 2 issues in product backlog needs to be assigned and estimated

**Comment by somangshu** [comment]
Ongoing work roster:

| Author | PR | 
| ------ | ------ |
| @vicky-primathon  | 3 |
| @wmdev0808  | 4 |
| @Tooluloope  | 2 |
| @vibhandikyash  | **7** |
| @techbhavin  | **5** |

**Comment by vibhandikyash** [comment]
Actionable items:
- Estimation for all the tasks from product backlog to done.
- If have multiple issues in backlog reassign to another developer internally with fewer tasks.

**Comment by dilippitchika** [comment]
Action items 3 Feb
 1. #3613 - Bhavin to check and Dilip to check Json form dependency

**Comment by dilippitchika** [comment]
Widget enhancements

1. 11383 pull - stuck since 3 days
2. 8911 - Needs to be moved forward ASAP, really small issue
3. 10758 - Random test failing, @techbhavin to check again if it fails then need to raise it in qa-automation channel
