### ISSUE TITLE
[Bug]-[100]:Placement options on button widget is incorrect

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Placement options on button widgets does not convey the right information and is ambiguous in action and labeling
`Start` and `between` move the label to the left most corner of the button and `center` keeps the button label in the middle

![image](https://user-images.githubusercontent.com/79509062/148419018-27b574e5-2872-4128-9dd0-53d1479b0bce.png)

### Steps To Reproduce

1. Go to button widget's property pane and observe the behaviour when different placement options are picked

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment]
@momcilo-appsmith @vasanth-appsmith Is there a better way to represent this instead of a dropdown?

**Comment by momcilo-appsmith** [comment]
@vasanth-appsmith Let's have a radio group for this in the property pane with icons.

**Comment by dilippitchika** [comment]
Reach: 98
Impact: Medium

**Comment by sbalaji1192** [comment]
@dilippitchika We need a design for this.

**Comment by tauantcamargo** [comment]
@dilippitchika can i ge tit?

**Comment by trishitapingolia** [comment]
Can I work on this issue?

**Comment by CursedRock17** [comment]
@ramsaptami was the pull request that I sent what you had in mind for the change.

**Comment by ramsaptami** [comment]
Hey @CursedRock17 , looks like it's still being reviewed. Let me chase up with the team to get this expedited for you.

**Comment by CursedRock17** [comment]
@ramsaptami thanks!

**Comment by nikhil-babar** [comment]
@ramsaptami I would like to work on this issue

**Comment by ramsaptami** [comment]
hey @nikhil-babar, the team needs to RCA this to get to all the issues that need resolving, once that's done this would be ready to be picked up. We'll post an update once it's been triaged.

**Comment by dilippitchika** [comment]
I don't think we should have this feature, it's unnecessary. I would rather remove it when we use WDS button

**Comment by narayand16** [comment]
@ramsaptami Did the team get time to triage this issue/bug? If yes, can you share the final requirements and the approach to fix the issue?

**Comment by ramsaptami** [comment]
@narayand16 could you please take a look at other issues marked for hacktoberfest? This one has design decisions that we still need to iron out.

**Comment by KelvinOm** [comment]
@ramsaptami In the new version of widgets(WDS components), we do not plan to support text alignment inside the button. The width of the button will be calculated based on the content.
