### ISSUE TITLE
[Task]: Add analytics events for UQI 

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#10210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Form vs raw data usage

**Comment by nidhi-nair** [comment]
Closing since this is the same as action execution and CRUD.

**Comment by rohan-arthur** [comment]
https://mixpanel.com/project/2032485/view/178891/app/dashboards#id=3088423&editor-card-id=%22report-32293272%22
