### ISSUE TITLE
[Bug]: App in preview mode shows hidden widgets

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hidden widgets should not be visible in **preview mode**

### Steps To Reproduce

1. Turn off `Visible` property of a widget and switch to **preview mode**. Observe hidden widget is still visible

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami why is this low? This seems like a critical issue to me that is affecting all production apps

**Comment by ramsaptami** [comment]
Marking this back to low since this is to do with preview mode and not view mode. My bad for missing the right word there
