### ISSUE TITLE
[Bug]: Progress bar widget 'fill color' field shows green when no color is set

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Progress bar widget ```Fill color``` shows Green #03B365 when the user sets the field to no color.

https://loom.com/share/529e84cbc9b14810b9eb2db666e9d4d0

**Expected behavior:**
Must display like below
![image](https://user-images.githubusercontent.com/92293815/148506418-6191d0c0-4057-4ee2-a5f7-514ed6e94c49.png)

### Steps To Reproduce

1. Drag and drop Progress bar widget
2. In ```Fill color``` field select no color > Click on canvas > Click on property pane again. Observe the field

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
It takes the theme color
