### ISSUE TITLE
[Feature]: [validations] Extracting requirements from JSON

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#10230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we get the form config, we have to extract the validation config and create validation paths.

As an FE Coder, I should be able to extract the validation keys from the config JSON and set them as validation paths, so that the validation service can run the validations on the components.

Corner cases: None

Test cases: additional test cases will be required
To be planned separately

Documentation required: Yes
To be planned separately

Note: this is part of the larger validation story, details [here](https://docs.google.com/document/d/1E-3fc3xSk0aQ4r6iOlz9nFtuqUeozsyFuDOaD5dcSDQ/edit#).

### Why should this be worked on?

As a Plugin developer, I should be able to enable real time validations on the query and ds forms, so that the developer can know when they have entered something wrong

**Comment by prapullac** [comment]
Waiting for backend

**Comment by prapullac** [comment]
Verified as a part of regression
