### ISSUE TITLE
[Bug]: Invited user to group cannot register via OAuth

### ISSUE THREAD

**Issue by japrogramer** [appsmithorg/appsmith#10253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when an email is invited into a group and the User model for that email doesn't already exists a new User model with that email is created.

When the user goes to register via OAuth spring security OAuth complains that the user already exists.

This does not happen when the User registers via email and password and then tries to login via OAuth.

### Steps To Reproduce

1. invite email of user that isn't already registered into a group.
2. register via OAuth.
3. spring oauth complains that user already exists.

### Environment

Release

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer I just tried the steps mentioned on our cloud instance and it worked fine. Was this using the google login?

**Comment by japrogramer** [comment]
@Nikhil-Nandagopal  thank you for checking, I went back and tried to replicate the error I experienced.

The cause was actually different. When the OAuth provider returns an email with a capital letter,
registration works the first time but any subsequent attempts to login result in an error like this.

```
backend stdout |  - [6e7ee110-1]  500 Server Error for HTTP GET "/login/oauth2/code/XXXXX"
backend stdout | com.appsmith.server.exceptions.AppsmithException: There is already an account registered with this email japrogramer@github.com. Please sign in instead.
backend stdout |        at com.appsmith.server.services.ce.UserServiceCEImpl.lambda$createUserAndSendEmail$15(UserServiceCEImpl.java:519)
backend stdout |        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout |        |_ checkpoint ⇢ org.springframework.security.oauth2.client.web.server.authentication.OAuth2LoginAuthenticationWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.security.oauth2.client.web.server.OAuth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
backend stdout |        |_ checkpoint ⇢ HTTP GET "/login/oauth2/code/XXXXX" [ExceptionHandlingWebHandler]

```

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer can you mention which OAuth provider returned the email with a capital letter?

**Comment by japrogramer** [comment]
@Nikhil-Nandagopal my own custom provider, I know y'all don't support any provider other than github or google.

I didn't close the issue when I learned that it was an OAuth problem because maybe they might return an email with a capital
letter.

But also because its a strange pattern for spring-security to check for an existing user with an email with capital letters but to create a user with lowercase letters, that results in a user successfully registering but not being able to login after login out.

I am working on a fix on my side, so feel free to close the issue if y'all think it is not a problem with the existing providers.

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer no this is indeed an issue on our end, in the beginning we did not sanitise emails while creating users and later we decided to merge authenticated users that signed in via SSO. This has caused this issue. Thank you for informing us

**Comment by RakshaKShetty** [comment]
Cant test this issue
