### ISSUE TITLE
[Bug]: Photos Taken on Iphone Fail to Upload using FilePicker

### ISSUE THREAD

**Issue by myevo8u** [appsmithorg/appsmith#10258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to upload a picture to my API through the filepicker via my iPhone I get a SyntaxError: Unexpected Identifier. When uploading pictures through desktop no errors. If I transfer the picture taken on my iPhone and try to upload from the Desktop, I receive the same error. I have tried across multiple mobile browsers as well. 

Is there a formatting problem with mobile pictures that AppSmith cannot interpret? I have attached the photo taken from my Iphone for testing purposes.  (Kd-28WaterPump.jpg)

![FilePicker-Syntax-Error](https://user-images.githubusercontent.com/49907883/148715702-8cbb8aff-69aa-4dd0-880d-880dbd275f5e.png)
![Imageupload](https://user-images.githubusercontent.com/49907883/148715762-b7568b8c-b55d-4a6c-a98b-6b18da2e1be3.png)
![Kd-28WaterPump (2)](https://user-images.githubusercontent.com/49907883/148716300-a8520fe0-0121-4935-9e50-24de6e2c1043.jpg)
![FilePickerJS](https://user-images.githubusercontent.com/49907883/148716359-9a399a64-8eab-45af-a4d8-b5420faea148.png)

 

### Steps To Reproduce

Create FilePicker to upload Image. Use API to upload Image on remote server, store return URL value to be updated in table on form submit. 

Submit photo from desktop, should succeed. Switch to iPhone, open AppSmith form, hit file upload, take picture on phone, and hit upload. Error should appear. 

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
This should be working
