### ISSUE TITLE
[Feature]: Mongo plugin: add template for `aggregate`, `count` and `distinct` cmd

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#10256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- add templates for `aggregate`, `count` and `distinct` cmd

### Why should this be worked on?

- provide template for all supported cmds.

**Comment by felixsuarez0727** [comment]
Hi! @sumitsum. Can you please assign this to me?

**Comment by anngedeus** [comment]
Hello can I also help with finding a solution for this issue?

**Comment by sumitsum** [comment]
Hi @anngedeus , thanks a lot for showing interest in this issue. Unfortunately, this issue has already been assigned to Felix. However, there are plenty of other `good first issues` that are still un-assigned. I would encourage you to take a look through those issues and find a nice and interesting issue to work on.  We would be very glad to help you with any of those issues that you pick. Eagerly looking forward to your contribution. Happy hunting :)

**Comment by nidhi-nair** [comment]
Closed via #11153
