### ISSUE TITLE
[Bug]: When one organization is deleted there is a loading icon for all other organizations

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When one organization is deleted there is a loading icon for all other organizations

![image](https://user-images.githubusercontent.com/92293815/148747460-8a0197aa-d872-4864-87cc-4dde5b764cb4.png)

https://loom.com/share/40b76a46306b4fcb88a7999067435212

### Steps To Reproduce

1. In Home page create a new organization
2. Delete the newly created organization 
3. Click on ```...```  for other organization and observe the loading icon

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
no longer valid
