### ISSUE TITLE
[Bug]: The radio options overlaps with the progress bar widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that on adding additional radio options to the radio group the options goes out of the widget and due to which when the progress bar is placed on the newly added radio option the radio options overlaps with the progress bar - Refer video below

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/feb8191fdb1b4f37b868aabdf7082d6d-00001.gif)](https://www.loom.com/share/feb8191fdb1b4f37b868aabdf7082d6d)

**Note: This radio option overlaps will happen for other widgets as well and not only with the progress bar**

### Steps To Reproduce

1.Launch appmsith app in release/Production 
2.Drag and drop radio group widget 
3.Add one more radio options and observe the option goes out of the widget 
4.Place progress bar or button or divider on the newly added radio options and observe

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Happens with any widget addition and not just progress bar widget. This means we either add a scroll and add the options within scroll or support dynamic height. Don't think we should solve this now.

**Comment by somangshu** [comment]
closing this in favour of dynamic height
