### ISSUE TITLE
[Bug]: Resizing widgets from corners should maintain aspect ratio on the resizing animation

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Widget dimensions goes awry when resized from its corners instead one line from each axis is reduced/increased. Expected behaviour is to maintain aspect ratio when using corner arrows to resize

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9c222c9aa1134dbf9701b09fcd22a48b-00001.gif)](https://www.loom.com/share/9c222c9aa1134dbf9701b09fcd22a48b)

### Steps To Reproduce

1. Add an icon button and resize the widget. Observe the animation when resizing the widget and the movement of borders on the x and y axis

### Environment

Production

### Version

Cloud

**Comment by PrabhjotSembhi** [comment]
Hi, @ramsaptami I can fix it.  Please assign it to me

**Comment by PrabhjotSembhi** [comment]
@ramsaptami We are reconstructing our house in the process. A brick or stone fallen on my PC. 

I forgot I was assigned this task. I thought it would be good if I share this update with you. 

I will contribute to appsmith in few days once my PC is up and running 

Thanks

**Comment by ramsaptami** [comment]
this has been fixed on prod
