### ISSUE TITLE
[Bug]: Drop down menu visible throughout the home page scroll

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Drop down menu is visible and does not collapse throughout the home page scroll when no action is performed on it.
https://loom.com/share/9eb57a8808b645269816896dcce8081a

### Steps To Reproduce

1. Go to home page, create sufficient organizations for scroll to appear
2. Go to the last organization and click on ```...``` and scroll up in the home page.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
No longer valid
