### ISSUE TITLE
[Bug] Seeing a lot of items in autocomplete even though they are not on the screen

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1027]
https://www.notion.so/Seeing-a-lot-of-items-in-autocomplete-even-though-they-are-not-on-the-screen-3bafa6d2ad334aea9f9fe4f4bfc1fc83

**Comment by hetunandu** [comment]
Hey @prapullac can you test this in our current release? I think it should be solved with the immutable widgets change

**Comment by Nikhil-Nandagopal** [comment]
duplicate of #951

**Comment by prapullac** [comment]
We can close the issue as it is working as expected
