### ISSUE TITLE
[Bug]: Button color in table widget when changed to no color moves back to green color

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Button color in table widget when changed to 'no color' moves back to green color. Whereas the default behavior of Button widget on a canvas when the color is changed to _no color_, it becomes transparent and on hover it appears green. Consistency can be maintained when a button is placed irrespective on a canvas, form, container or a table.

Currently button on canvas, container and on form behaves same it is indifferent on table widget.

https://loom.com/share/32decd910a744a5aa95934e1597e5888

### Steps To Reproduce

1. Drag and drop a table widget
2. Click on settings icon for _action_ column
3. Change the Button Color to no color.

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@shwetha-ramesh good catch, I would rather say that the default should be fallback even in the button, that is green for now if no color is given, this is more consistent in terms of UI, what do you think?

**Comment by somangshu** [comment]
Infact if required we can also check this across the button type widget and make the behaviour consistent, @shwetha-ramesh can you help us create the list
