### ISSUE TITLE
[Bug]: JSObject - Timing issue resulting in 'Run' failure 

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#10284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e3701499185944cc864edd4e402fafb1-00001.gif)](https://www.loom.com/share/e3701499185944cc864edd4e402fafb1)

### Steps To Reproduce

1. Create a JS object
2. In the default template - add a simple return statement
3. Click run
4. The function does not run properly & is reverted back to non-run state
5. Give ample wait & then try to run - the JS function returns fine
6. Also observe the page is never auto-saved - save icon loads throughout the time

### Environment

Release

### Version

Cloud

**Comment by bharath31** [comment]
This is no longer reproducible
