### ISSUE TITLE
[Enhancement]: Select and Multi-select V2 to handle server side filtering

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10297]
Currently, select and multi-select widgets are not able to support server side filtering because we are not storing the labels of values selected from the server side. 

This causes the multi-select and select not usable. We need to store the label and the value of the selected options.

PRD

# Select widgets v2

## Objective

To support server side filtering in select and multi-select widgets, we need to launch v2 of the widgets where we save the label selected along with value. Today we only save the value and rely on the data to fetch the label, but this is not possible when server sider filtering is turned on and option is not present in the filtered list

## Success Metrics *

| Goal | Metric |
| --- | --- |
| Support server-side filtering in select widgets | % of dropdowns with server-side filtering switch on. (Need analytics event) |

Requirements

| Requirement | User story | Comments |
| --- | --- | --- |
| App viewer should view the label of the selected option in the input for select and multi-select | As a user of the app, I want to see the option I have selected get reflected in the input for select widgets. |  |
| If they search for the same option again in the dropdown they should see the option selected to be highlighted | As a user of the app, I want to see the option I have selected get highlighted if I search for it. |  |
| Multi-select widget should have a search bar inside the dropdown like select. Provide the filterable option here for the developer to enable. | As a developer, I want to allow users to search for options in a multi-select widget. | We need a filterable toggle similar to select widget in multi-select for the search inside the dropdown |
| Developer will now configure the default option(s) instead of value both for client and server side. Default option needs both “value” and “label”. Will be applicable for any new select/multi-select widget. Multi-select will have default options, where user is supposed to add array of objects. | As a developer, I want to specify the value and label for the default option(s) to show if the data is not available on client side. | While we can keep the client side to be similar to current behavior, this will be inconsistent for the user as if they enable server side they have to add a default label. 

This will impact a lot of areas though - 1. Cypress tests 2. Documentation 3. Videos |

## Documentation

- [Add] Multi-select filtering toggle 
- [Update] Default option for select and Default options for multi-select

## Out of Scope

- Changes to tree and multi-tree select widget

## Developer Handoff Document in Figma
Will need design discussion. Most things are re-usable.

## RACI Matrix

| Responsible |  |
| --- | --- |
| Accountable |  |
| Consulted |  |
| Informed |  |

**Comment by sbalaji1192** [comment]
@Tooluloope I have closed the other bug in favor of this enhancement. please refer https://github.com/appsmithorg/appsmith/pull/10155 for the changes I did as part of the other bug.

**Comment by dilippitchika** [comment]
Added PRD @somangshu @Tooluloope please review and suggest changes if any. 

CC @vivekverma2312 @Nikhil-Nandagopal
