### ISSUE TITLE
[Bug]: Incorrect reference error is displayed for function that is present in a promise call

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Incorrect reference error is displayed on console for functions that are called within a promise 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8de3725addb649fcb7f0250b46d42bac-00001.gif)](https://www.loom.com/share/8de3725addb649fcb7f0250b46d42bac)
![image](https://user-images.githubusercontent.com/79509062/148793143-dff2cde2-2e1f-4838-9e26-0e7cdf05246d.png)
![image](https://user-images.githubusercontent.com/79509062/148793526-ba041332-92fc-4287-a40f-3f0db2f7e7e8.png)

### Steps To Reproduce

1. Go to app at [link](https://release.app.appsmith.com/applications/612332edfe755a38b6e6a9c2/pages/61a0f83a15961655bd407657/edit) and observe errors on console.

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment]
Execution is not affected by the errors displayed on the console. These errors are displayed as a result of how JS and API's are handled when app is loaded hence deprioritising this to `low`

**Comment by ramsaptami** [comment]
Reopening this issue since we still see ReferenceError on console.

**Comment by rohan-arthur** [comment]
@ramsaptami would you please share the app link again? The one shared above does not work anymore

**Comment by Rishabh-Rathod** [comment]
Is it same as https://github.com/appsmithorg/appsmith/pull/12683 ? @ramsaptami

**Comment by ramsaptami** [comment]
@Rishabh-Rathod this isn't the same error we see as the one in #12683. I can't seem to find the app that has this issue so I'm trying to repro this. I'll post the link here when I do
