### ISSUE TITLE
[Bug]-[1750]:New error handling on trigger field does not convey the right information

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a query that's called from JS call fails then the error message displayed does not convey the right information. Shows `Uncaught promise rejection` error. Before promises was merged, the error was `Syntax error` and `unexpected error` displayed to the user

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6129691e5d1d4ea4be3fe74c9ecc4d40-00001.gif)](https://www.loom.com/share/6129691e5d1d4ea4be3fe74c9ecc4d40)

### Steps To Reproduce

1. Create an empty query and trigger it on an action field and observe the error displayed to user

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
incidence of uncaughtpromiserejection over 6m: 3500

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3500 |
| Effort (months)  | <<number>> |

**Comment by Rishabh-Rathod** [comment]
Faced here by a discord user where it was mentioned. They see a lot of Uncaught Promise Rejection errors. https://theappsmith.slack.com/archives/C024GUDM0LT/p1662560495472359

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 when can we fix this?

**Comment by bharath31** [comment]
@satbir121 @ApekshaBhosale  We should intercept and format these error messages before showing them to the user. Ideally, error types like`UncaughtPromiseRejection`, `ReferenceError`, etc.. shouldn't be a part of system-generated error messages. Let me know what you think.

**Comment by ApekshaBhosale** [comment]
@bharath31 yes we need to. we have added UncaughtPromiseRejection string before showing. we need to change these errors

**Comment by Nikhil-Nandagopal** [comment]
Great! Can we please fix this soon? I think this random error has been one of the sore spots in the product. It just makes people feel irritated because it's so random. Unless the error has some genuine information, it should not show and we should always try to show useful information.

**Comment by bharath31** [comment]
this is no longer an issue
