### ISSUE TITLE
[Bug]: On ListWidget reset, children widgets value becomes undefined hence 2nd file upload is saved as undefined for the old s3 application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The 2nd file upload is saved as undefined for the old s3 application

![image](https://user-images.githubusercontent.com/45958978/148903803-5513cc79-b239-4190-ba11-c7b0a27cf854.png)

More details about this issue was discussed - #9922

### Steps To Reproduce

Go to old S3 crud page
Upload a file, Wait until 'File Uploaded' message is displayed
Search with File prefix & verify result is showing fine
Upload 2nd file, Wait until 'File Uploaded' message is displayed
Search with File prefix
No Search results are returned
Try uploading 3rd file & no search results returned as well
The 2nd added file is added with the name as "undefined" instead of original name

### Environment

Production

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
This issue is specifically for ListWidget bug which was core issue for #9922

**Comment by RakshaKShetty** [comment]
You can use this app https://release.app.appsmith.com/applications/61c2bde37f07823aaeee8025/pages/61c2e4777f07823aaeee8334/edit

**Comment by somangshu** [comment]
Deprioritising this to high, Not in the OKR this quater

**Comment by Tooluloope** [comment]
Closing As this currently works
https://user-images.githubusercontent.com/31691737/177056632-5f5ed1ff-a6bd-4831-9296-cd093582ca77.mov
