### ISSUE TITLE
[Bug]: nginx HTTP template missing in appsmith-editor container

### ISSUE THREAD

**Issue by noe-charmet** [appsmithorg/appsmith#10304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I'm currently trying to make a setup of the app without using the install script.
I have encountered an issue when running the `appsmith-editor:v1.6.6` container.
When using http instead of https, the `start-nginx.sh` script attempts to `cat` a file called `/nginx-app-http.conf.template` which does not exist in the image.
However there is a file called `/nginx-app-https.conf.template`.

### Steps To Reproduce

Launch `appsmith-editor:v1.6.6`  without SSL cert config

### Environment

Production

### Version

Self-Hosted

**Comment by mohanarpit** [comment]
Not sure which install script you are referring to. Currently, in order to run Appsmith, you just need to bring up a Docker container. The steps are listed at: [https://docs.appsmith.com/setup/docker](https://docs.appsmith.com/setup/docker). 

Let us know if this container setup works for you.

Alternatively, if you are building & running Appsmith from source, can you please follow our setup guide at: [https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md)?

**Comment by noe-charmet** [comment]
[This is the script I refer to](https://github.com/appsmithorg/appsmith/blob/release/deploy/install.sh).

We're actually trying to deploy the front-end and  backend containers (+ other tools), in a k8s like environment. We have an ingress gateway in front the appsmith front-end, it handles L7 termination. So we would like to use http only between out gateway and the front-end container.

On startup the front-end container calls the [start-nginx.sh](https://github.com/appsmithorg/appsmith/blob/release/app/client/docker/start-nginx.sh) script. Which generates the nginx config.

This config generator, bases itself on multiple possible config templates.`/nginx.conf.template`, `/nginx-app-http.conf.template`, `/nginx-app-https.conf.template`.

In our case it seems like it should load (/nginx-app-http.conf.template)[https://github.com/appsmithorg/appsmith/blob/release/app/client/docker/templates/nginx-app-http.conf.template]. Which seems to be injected directly by the [Dockerfile](https://github.com/appsmithorg/appsmith/blob/release/app/client/Dockerfile).

However as seen in this screenshot, the file is not included in the `appsmith-editor` container with tag `v1.6.6`.
![image](https://user-images.githubusercontent.com/59678972/148950576-040bf6c6-1484-4a06-aedc-f9edc59a7a43.png).


Thank you for taking time to answer my question. I understand that we're not going the recommended easy way, but it's important for me to have strict process separation in containers, and not just deploy a single all-in-one container.

**Comment by sharat87** [comment]
Hey @noe-charmet, thank you for reporting this. We just pushed a fix that fixes the location of the http config file in the Docker image.

**Comment by noe-charmet** [comment]
@sharat87 thank you for being so quick at fixing it !
