### ISSUE TITLE
[Bug]: SSH keys generation issue

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#10302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use Jsch library to generate SSH keys which used by git sync feature to connect to a git client. The Jsch library generates the RSA SHA-1 types keys. But the github made some changes to improve protocol security when you push or pull Git data. This change includes removing support for RSA SHA-1 type signature keys. 
More can be found here - https://github.blog/2021-09-01-improving-git-protocol-security-github/

### Steps To Reproduce

All the git related operations will fail because of the security change done by github as the support for RSA SHa-1 type keys is stopped from today. 

### Environment

Production

### Version

Cloud

**Comment by abhvsn** [comment]
Just checked with the compatibility with `ECDSA`, this does support SHA-2 which can be quick fix with no library upgrade etc. But this does mean we will have to go through the migration and will have to ask users to update on Github as well

cc: @AnaghHegde @nayan-rafiq

**Comment by AnaghHegde** [comment]
Yes this looks like a better fix. Also migration is needed no matter what type of solution we take @abhvsn

**Comment by abhvsn** [comment]
@AnaghHegde are you picking this up or should I go ahead?
