### ISSUE TITLE
[Bug]: Error when determining async function ReferenceError: get_reports_detailed__admin is not defined

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#10314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User application has console error 

<img width="425" alt="Screenshot 2022-01-11 at 4 54 39 PM" src="https://user-images.githubusercontent.com/23132741/148934533-2f23f9b8-7d4f-4696-9955-d0871da957ea.png">

### Steps To Reproduce

Not Sure Yet.

### Environment

Production

### Version

Cloud

**Comment by ramsaptami** [comment]
Not sure of repro steps here but observed this after promises was merged

![image](https://user-images.githubusercontent.com/79509062/149122488-661c3f0d-2d57-4364-b451-468fbcee2b42.png)

**Comment by Rishabh-Rathod** [comment]
duplicate of https://github.com/appsmithorg/appsmith/issues/10293
