### ISSUE TITLE
[Bug]: Form validation breaks when the Min Date or Max Date empty in a DatePicker widget

### ISSUE THREAD

**Issue by israrwz** [appsmithorg/appsmith#10317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you add a DatePicker widget to a form, and toggle the Submit button's **Disabled Invalid Forms** property to true, the form validation will break when the DatePicker's **Min Date** or **Max Date** properties are empty.

This happens even if the DatePicker is not marked as a required field.

### Steps To Reproduce

1. Add a form wiget
2. Add a DatePicker widget to the form.
3. Make either the **Min Date** or the **Max Date** property of the DatePicker empty.
4. Toggle the **Disabled Invalid Forms** of the form's submit button to true.
5. The submit button will remain disabled.

### Environment

Production

### Version

Self-Hosted

**Comment by mcsptit** [comment]
MAX date validation is invalid when the default date value is the same as max date value
