### ISSUE TITLE
[Bug]:  Airtable breaks when tried to access it 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#10327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user clicks on the Airtable icon the application breaks clicks

### Steps To Reproduce

1) Navigate to Datasources
2) Click on Airtable 
and observe

Link to DP :
https://appsmith-3dhv9gs0f-get-appsmith.vercel.app/applications

### Environment

Deploy Preview

### Version

Cloud

**Comment by ohansFavour** [comment]
[New DP](https://appsmith-mp8f6dloj-get-appsmith.vercel.app/). 

PS: This issue is linked to #9657
