### ISSUE TITLE
[Bug]-[2000]:Dropdown UI issue on gen CRUD page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When dropdown does not have any values on Gen CRUD page then a tiny bar appears in the wrong place.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8a8b5633015d4e2cbb4db2dcc79c062a-00001.gif)](https://www.loom.com/share/8a8b5633015d4e2cbb4db2dcc79c062a)

### Steps To Reproduce

1. Use any DB that's got incorrect config to repro this and select it as the source for CRUD generation.  Observe the error displayed.
2. Now observe a tiny bar appear when dropdown is clicked as seen in the video.

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4000 |
| Effort (months)  | 1 |
