### ISSUE TITLE
[Feature]-[1300]:Display Page suggestions when user is focused on the navigate action selector

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1033]
## Description
When a user selects the navigate action in an action selector, they have to enter an empty input which provides no feedback as to what values can go there. The values accepted are a URL or the name of the page but there is no intimation of this to a user

**Comment by Nikhil-Nandagopal** [comment]
Lets separate navigateToPage and navigateToURL so that arguments are not being overridden leading to confusing UX

**Comment by rohan-arthur** [comment]
WIDGET_PROPERTY_UPDATE, updatedValue contains "{{navigateTo"
usage: 1300

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1300 |
| Effort (months)  | 0.5 |

**Comment by rimildeyjsr** [comment]
This issue is closed by https://github.com/appsmithorg/appsmith/pull/14856
