### ISSUE TITLE
[Bug]: Menu items are not accepting spaces as Menu name on Button group widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e15f0d36046446ce9888e214f4ee0ad6-00001.gif)](https://www.loom.com/share/e15f0d36046446ce9888e214f4ee0ad6)

### Steps To Reproduce

1. Add a Button group widget to canvas
2. Select any buttons and click on gear icon from property pane
3. Change the button type to "Menu"
4. Add a new Menu items
5. Observe that default  name has proper space between characters but when we try to edit the name, space vanishes and we are unable to add spaces between the characters

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Duplicate of #9443
