### ISSUE TITLE
[Bug]-[270]:async functions in sync fields (path based error)

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#10347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an async function is used in `if else` statement.

The error `Async function called in a sync field` only shows up, when the block it is used in (if/else) is active.

### Steps To Reproduce

1. Create a `table`.
2. In `table data`, write `true ? [] : showAlert("")`
3. Notice no error shows up. (despite using showAlert in a sync field)
4. Change `true` to `false`. And notice the error shows up. 
![Screen Recording 2022-01-12 at 15 32 02](https://user-images.githubusercontent.com/66776129/149120630-08258851-2691-410a-ae7d-068da406cca9.gif)

This can be misleading to users when they're developing app's.
Sometimes the error will show up sometimes it won't.

### Environment

Production

### Version

Cloud

**Comment by juandl** [comment]
![image](https://user-images.githubusercontent.com/25650720/176321234-7dae21cf-4257-4773-bc46-765dced70142.png)

**Comment by bharath31** [comment]
Assuming 3% of users use if/else statements within mustache brackets on the property pane 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 270 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
should be fixed with #20008
