### ISSUE TITLE
[Feature]: Add docker support for arm/v7 for devices like raspberry pi

### ISSUE THREAD

**Issue by niradler** [appsmithorg/appsmith#10348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add docker support for arm/v7 for devices like raspberry pi
```
Creating network "appsmith_default" with the default driver
Pulling appsmith (index.docker.io/appsmith/appsmith-ce:)...
latest: Pulling from appsmith/appsmith-ce
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

### Why should this be worked on?

the effort is not high and the gain is a full market of people using this devices

**Comment by niradler** [comment]
i will do it my self and just build it on my machine

**Comment by niradler** [comment]
running something like this
`docker buildx build --platform linux/arm/v7 -t appsmith/appsmith-pi .`
@Nikhil-Nandagopal any command to bootstrap the project for docker build ?
```
 => ERROR [11/22] COPY ./app/client/build editor/                                                                                                                 0.0s
 => CACHED [12/22] COPY ./app/rts/package.json ./app/rts/dist/* rts/                                                                                              0.0s
 => ERROR [13/22] COPY ./app/rts/node_modules rts/node_modules                                                                                                    0.0s
------
 > [11/22] COPY ./app/client/build editor/:
------
------
 > [13/22] COPY ./app/rts/node_modules rts/node_modules:
------
error: failed to solve: failed to compute cache key: "/app/rts/node_modules" not found: not found
```

**Comment by niradler** [comment]
if you need help i can help with multi stage build, it is more user friendly and safe (dependencies that build/install on the host, can cause issues when target architecture is different then the os)

**Comment by niradler** [comment]
[workflow example ](https://github.com/n8n-io/n8n/blob/b4b65bb90624ad00e6e3336c276a363548fb60cc/.github/workflows/docker-images-rpi.yml)

**Comment by sharat87** [comment]
Hey @niradler, thank you for reporting this. We just pushed a fix that fixes the location of the http config file in the Docker image. Thank for offering to help, much appreciated 😃.

**Comment by arminus** [comment]
FYI - I manged to build the docker image on my Pi4 (aarch64) last week, runs fine. 

The issue I had previously was MongoDB, which in current versions doesn't work on 32bit OSes anymore, after I upgraded my Pi to 64 bit bullseye things began to work. (with some tinkering with the build environment).

**Comment by Nikhil-Nandagopal** [comment]
@niradler could you check and see if this issue still persists for you?

**Comment by arminus** [comment]
@Nikhil-Nandagopal it would be nice though if you guys could provide an arm/multiarch image on docker hub, though?

**Comment by sharat87** [comment]
Hey @arminus, the image is indeed published for arm architecture, but for 64bit only, at https://hub.docker.com/repository/docker/appsmith/appsmith-ce/tags?page=1&ordering=last_updated. Is that what you're looking for?
