### ISSUE TITLE
[Bug]: RichTextEditor no value when copy patse

### ISSUE THREAD

**Issue by NguyenMinhDung** [appsmithorg/appsmith#10357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I copy any content to RichTextEditor then I read content of RichTextEditor by RichTextEditor.text but no value

### Steps To Reproduce

1. Copy content
2. Paste content to RichTextEditor
3. Read content of RichTextEditor but no value

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@NguyenMinhDung this seems to be working for me. Can you please share a video?

**Comment by NguyenMinhDung** [comment]
### Here video to reproduce the bug
https://user-images.githubusercontent.com/2491855/149336661-2a6cff5e-cb94-4add-afbc-eee957cfe16a.mp4

### Below video is another bug, when I clear content of RichTextEditor but the content is still there
https://user-images.githubusercontent.com/2491855/149336731-4e3d2c72-0f0e-4381-8563-2fb1ea1c49b1.mp4

**Comment by Nikhil-Nandagopal** [comment]
@NguyenMinhDung thank you for reporting this. It seems to happen inside a modal and in some other cases
