### ISSUE TITLE
[Bug] When the role of the member is changed by Admin the member but must be intimated by a mail

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1037]
#Steps
1. Add a user to an org as app viewer
2. Update the user's role in the settings page
3. The user does not receive an email informing of the update

**Comment by Sufiyan1997** [comment]
@Nikhil-Nandagopal I would to work on this. Can you assign it to me?

**Comment by Nikhil-Nandagopal** [comment]
@Sufiyan1997 go for it!

**Comment by mohanarpit** [comment]
@Sufiyan1997 Just to ensure you are on the right track, this bug requires changes in `UserOrganizationServiceImpl` class in `updateRoleForMember`. This is on the server code base.

**Comment by trishaanand** [comment]
@Sufiyan1997 : I have added a new html template for this email. You will find it by the name `updateRoleExistingUserTemplate.html `. You would need to provide three variable values. These are as follows : 
1. Inviter_First_Name : This is the session user's first name ( Or the user who is updating the role for another member of the organization)
2. inviter_org_name : This is the name of the organization for which this change was made
3. user_role_name : This is the name of the role which has now been assigned to the member of the organization.

Please use the function `UserServiceImpl`.inviteUser as a guide on how to replace variables in the template and then send out the email.

**Comment by Sufiyan1997** [comment]
@trishaanand Thanks. This will be very helpful

**Comment by prapullac** [comment]
verified the issue and works as expected
