### ISSUE TITLE
Implement the Run button design changes

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#10387]
Implement the Run button changes as shown in the following design document https://www.figma.com/file/sT3HR1VSWOTtPfh5vlpU8x/JS-Editor-Improvements?node-id=2%3A2

**Comment by rohan-arthur** [comment]
agreed to leave the response tab open by default, and leave the minimize button active. I will create a separate issue to improve this behaviour.

**Comment by rohan-arthur** [comment]
stuck with #6539
