### ISSUE TITLE
[Bug]: API response is stringified when it's a HTML response

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

API response is stringified when it's a HTML response, for example when using `yahoo.com`

![image](https://user-images.githubusercontent.com/79509062/149298244-dc3b99ac-f7fe-49ff-a0d1-5f181aec2673.png)

### Steps To Reproduce

1. Run an API query for yahoo.com and observe the response to be as seen in the image above. Expectation is that it needs to be be in readable format

### Environment

Release

### Version

Cloud

**Comment by nidhi-nair** [comment]
Unassigning myself since this is a client side change. The solution here would be to pretty print the response after taking the content type and data into account.
