### ISSUE TITLE
[Task]: performance issue in self-hosted instance

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#10382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Note: The issue is still not clear, this is a task to keep track of things being tried and progress being made.

1. load times are slow in user's machine (seems to not be the case in anand's machine)
2. chrome was reported (by user) to be faster than firefox (might be that the browser has been kept open for a long period)
3. noticed switching to mobile hotspot makes load time faster (even though wifi had better connection speed) (tested on nidhi's machine)

actions:
1. Look into TTFB to see if there's anything to be done in client side
2. Look at nginx, try restarting user's server
3. Check if the user had been using VPN

user machine spec: (imac/12.1/8GB(5.5GB used)/i5)
network speed (37(download), 7(upload) Mbps)

**Comment by ApekshaBhosale** [comment]
As @SatishGandham pointed out we have found the issue and we are actively working on it. 
One of the libraries we use in our code was taking most of the time but we have found an alternative library that improves performance by 40%. But again we are looking to improve more if we can immediately.  
Will have an update soon.

**Comment by billyrudi** [comment]
Thanks. I'm waiting for un appsmith update.
