### ISSUE TITLE
[Bug]Enhancement : An Auto triggered Acknowledgement mail can be sent to user on Feedback

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1039]
https://www.notion.so/Enhancement-An-Auto-triggered-Acknowledgement-mail-can-be-sent-to-user-on-Feedback-e664427002d943b9a36cc14442780f71

**Comment by Nikhil-Nandagopal** [comment]
@prapullac let's not Move the p2s for now

**Comment by Nikhil-Nandagopal** [comment]
We're doing this manually today
