### ISSUE TITLE
[Bug]: Cloning a page containing JS object with duplicate names cause an internal server error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cloning a page that has JS objects with the same name causes app to return an internal server error.

### Steps To Reproduce

1. Create an app with `Page1`
2. Add JSObject names `JSObject1`
3. Create new page `Page2`
4. Move JSObject to new page so `Page1` and `Page2` will have `JSObject1` 
5. Deploy so both unpub and pub versions will be in sink 
6. Move `JSObject1` from `Page2` to `Page1` so in `Page1` we will have 2 JSObject named `JSObject1` (I’m not sure if this should be allowed)
7. Deploy
8. Try to clone `Page1` couple of times you will see the internal server error for the second page

### Environment

Release

### Version

Cloud

**Comment by abhvsn** [comment]
@Irongade as per our earlier discussion move JS object across pages (point number 4 listed in the description) still open but this ticket talks about the cloning the page altogether. Can we track the issue about the move JS Object in seperate ticket?

**Comment by Irongade** [comment]
@abhvsn Okay, New Issue created for this edge case.

**Comment by ramsaptami** [comment]
Works as expected - cloning the page and application does not give any error as previously seen
