### ISSUE TITLE
[Bug]: App crashes on renaming input widget and adding another input widget to the canvas

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that each and every time when an input widget is added to canvas and renamed as Number and the data type is set to number and on adding another input or any other widgets to the canvas the widgets doesn't load and on refreshing the page the app crashes 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2c025c81dcf646c58b23ed0d3039710a-00001.gif)](https://www.loom.com/share/2c025c81dcf646c58b23ed0d3039710a)

### Steps To Reproduce

1.Launch appmsith app in release
2.Drag and drop input widget 
3.Rename the input widget as Number
4.Change the datatype to number 
5.Drag and drop another input widgets and other widgets 
6.Refresh the page and observe

### Environment

Release

### Version

Cloud

**Comment by vicky-primathon** [comment]
Issue exists as cyclic dependency get created when Input widget is renamed to Number.

**Comment by vicky-primathon** [comment]
Since "Number" is a restricted keyword in JS we cannot use it for naming the input widget. 
To fix this I think we should evaluate the value and throw an error before setting the name.

**Comment by somangshu** [comment]
@sbalaji1192 need you to chime in here

**Comment by sbalaji1192** [comment]
@vicky-primathon @somangshu Javascript keywords should not be used as entity names. We already have a long list of keywords that are restricted from being used as widget names over here - `JAVASCRIPT_KEYWORDS` - `/app/client/src/constants/WidgetValidation.ts`. some of the keywords are missing,  like Object, String. As part of this issue, let's expand the list to have all the js keywords.
