### ISSUE TITLE
[Bug] Widgets symbol must be same on both Side bar as well as on entity explorer

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1040]
https://www.notion.so/Widgets-symbol-must-be-same-on-both-Side-bar-as-well-as-on-entity-explorer-782a7e3c33dd493f8c25164a2103b1a0

**Comment by Nikhil-Nandagopal** [comment]
@prapullac can you mention which widget symbols are not the same

**Comment by prapullac** [comment]
@Nikhil-Nandagopal 
We can close this issue as this does not exits now.
