### ISSUE TITLE
[Bug]: Select Widget changes size

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#10410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The select widget changes it's size based on the width of the options

### Steps To Reproduce

1. Create a select widget with long options and short width

https://user-images.githubusercontent.com/3897254/149488809-b87f8257-eebc-4591-b303-81c4c6f6bbee.mov

2. Select an option

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Needs a fixed min-width defined and any characters exceeding it should just truncate.
https://www.loom.com/share/1c6fa3f8c5f948a4b150f43cc1dd4f29

**Comment by dilippitchika** [comment]
4 cols
