### ISSUE TITLE
[Bug]: Table styling bugs

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Listing all the bugs here
1. Whenever we have background color for a cell, it applies to the whole table on search.
2. Even if the table data is fits the width, we observe a scroll horizontally. The last column doesn't resize to fit the width. Occurs even if there's less data than the width of column.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6527f28f1cce4c33a08bf56f62ec7955-00001.gif)](https://www.loom.com/share/6527f28f1cce4c33a08bf56f62ec7955)

### Steps To Reproduce

Background color issue
1. Add a background color to the first column.
2. Search for any of the values in the row.
3. Observe that the color of the remaining rows changes to the color of the first cell.
4. Happens only for 1 search result.

Scroll issue
1. Add a table with data less than width of the table widget.
2. Scroll horizontally in the view mode. 
3. Observe the scroll happening even though size of data is less than the width of the widget

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@Tooluloope I suggest we take this up internally. Maybe @keyurparalkar can help if you have too many issues assigned
