### ISSUE TITLE
[Bug]: Deleting the default text from the Property pane doesn't reset the text from the RTE Widget

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deleting the default text from the Property pane doesn't reset the text from the RTE Widget
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/62e8a6f2983b45f88f9a240c2f4d220c-00001.gif)](https://www.loom.com/share/62e8a6f2983b45f88f9a240c2f4d220c)

### Steps To Reproduce

1. Go to Canvas
2. Drag and drop the rich text editor
3. Remove the default text 
4. Now observe the text displayed on the RTE widget 
5. It retains the text instead of clearing it 

### Environment

Release

### Version

Cloud

**Comment by vicky-primathon** [comment]
Change in defaultText property needs to be handled in RichTextEditorComponent

**Comment by Tooluloope** [comment]
@keyurparalkar is this not covered in your PR?

**Comment by keyurparalkar** [comment]
Yes @Tooluloope it is covered.
