### ISSUE TITLE
[Bug]: The data doesn't covert to Markdown type in RTE 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The data doesn't covert to Markdown type in  RTE 

### Steps To Reproduce

1. Drag and drop the RTE
2. Bind it with HTML code
3. Now Bind it with the Other RTE
4. Now change the Input type to  Markdown
5. The data doesn't covert to markdown

### Environment

Release

### Version

Cloud

**Comment by Tooluloope** [comment]
fixed in https://github.com/appsmithorg/appsmith/pull/10422
