### ISSUE TITLE
[Bug]: Text styling is not applied in the pop up 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when there is a larger text and truncate text toggle is enabled the styling applied are not populated in the pop up

<img width="336" alt="Screenshot 2022-01-18 at 2 35 43 PM" src="https://user-images.githubusercontent.com/11089579/149905367-a2e33436-a740-4b1c-9d54-63c82f6d7dba.png">
<img width="603" alt="Screenshot 2022-01-18 at 2 35 48 PM" src="https://user-images.githubusercontent.com/11089579/149905376-f192a7a2-0eab-44ac-a0cb-788126acbc8f.png">

### Steps To Reproduce

1.Launch appmsith app in release/Prod environment 
2.Drag and drop text widget
3.Add more text and enable truncate text toggle
4.Apply text styling - colour, size 
5.click on the three dots to open pop up and observe

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@YogeshJayaseelan small request, please dont leave the issue description at observe, Its easier to the end user to grok by reading what actually was observed
