### ISSUE TITLE
[Feature]: Responsive preview of the application

### ISSUE THREAD

**Issue by jyash97** [appsmithorg/appsmith#1043]
## Summary

A way to preview the application to test how it will perform on various screen sizes or devices.

## Motivation

Currently, there is only one way to test this is deploy the application, and using the dev tools test the responsiveness in the deployed URL.

## Additional Context

One idea on how I think responsiveness can be handled is by having a button for previewing the application at the top in the navigation bar. 

And the content can be similar to the dev tools experience but with fewer details. Something like this: 

![image](https://user-images.githubusercontent.com/22376783/95237617-15a75780-0826-11eb-914a-2959ccdf172d.png)

In the dropdown, there can be an option to add a new device which can then accept width and height for the specific device.
___

Another idea would be simply to show desktop, mobile and tablet icons at top and render the canvas in that size.

**Comment by Nikhil-Nandagopal** [comment]
@jyash97 this is a great feature once we support responsive UI. Right now our UI is fixed for desktop screens and we don't scale for smaller devices. We'll look at incorporating this when we build our mobile responsive feature

**Comment by Nikhil-Nandagopal** [comment]
This is now solved in our edit mode. More responsive properties will be available when we enable responsive applications
