### ISSUE TITLE
[Bug]: UI overflow in app homepage, which appears after every new Signup

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot (16)](https://user-images.githubusercontent.com/95341241/149763452-1b73d1ae-7fda-40a2-bd71-4b866f667608.png)

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0b4189459cf14c19aa24679052c03a97-00001.gif)](https://www.loom.com/share/0b4189459cf14c19aa24679052c03a97)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we're solving it in the new onboarding
