### ISSUE TITLE
[Bug]: Blank Organization name 

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ffdcdb4290f445d086d1d62b9289aab0-00001.gif)](https://www.loom.com/share/ffdcdb4290f445d086d1d62b9289aab0)

### Steps To Reproduce

1. Go to Organization settings
2. Keep Organization Name as Blank
3. Observe homepage with no organization name visible

### Environment

Production

### Version

Cloud

**Comment by vuiets** [comment]
@albinAppsmith could you take a look at this as well.

**Comment by hiteshjoshi** [comment]
Hey, can't prioritise this atm. We will have it picked up near quarter end. This is bug but not critical.

**Comment by hiteshjoshi** [comment]
Closing this as #10532 fixes this. Reopen if required.
