### ISSUE TITLE
[Bug]: Hover state hides the text for lighter button colors in secondary and tertiary variants

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the Color of the button is white or any light color, the hover color being light makes it hard to see the text.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/705da99a394949478f30106168646e2c-00001.gif)](https://www.loom.com/share/705da99a394949478f30106168646e2c)

### Steps To Reproduce

1. Add a new button to canvas
2. Change the button color to #FFF and the variant to either secondary or tertiary
3. Hover on the button and see that the text is hidden.

### Environment

Production

### Version

Cloud

**Comment by momcilo-appsmith** [comment]
@somangshu Can we use different hover color for the light version?
One other solution that is probably way easier to do is to have a transparent background instead of a solid color.

**Comment by somangshu** [comment]
@momcilo-appsmith what would be the condition to do that? I was thinking of the following

We can darken the font color and the hover remain the same as background. In case of secondary we can also do the same as font color to border color. WDYUT?

Ex: we select #FFFFFF, on hover we darken this color by for say 60%, the background remains transparent, In case the variant is secondary, the border colour also inherits the value from font color.

**Comment by dilippitchika** [comment]
Fixed in #4354
