### ISSUE TITLE
[Bug]:  After importing if the user tries to Fork or duplicate the application error is displayed to user 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#10441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user tries to fork or duplicate an application within or to another application after importing the application an error message stating "Please enter a valid parameter name." irrespective of using any name format. 
However, on refresh it is observed that the application forked or duplicate application would be created 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/50c5900795924350a19ce835c0e9feef-00001.gif)](https://www.loom.com/share/50c5900795924350a19ce835c0e9feef)

### Steps To Reproduce

1) Navigate to homepage 
2) Click on the action icon of the organization
3) Import and export the application click on Fork 
4) Fork the application 
and observe the error message 

### Environment

Release

### Version

Cloud

**Comment by abhvsn** [comment]
@prapullac are you facing this issue, asking this because I'm unable to reproduce this on my end. Also, is this happening to a specific applications?

**Comment by prapullac** [comment]
@abhvsn : Unable to reproduce the issue on the release environment. We can close the issue
