### ISSUE TITLE
[Bug]:  Reactivity problem on deployed version

### ISSUE THREAD

**Issue by dadebulba** [appsmithorg/appsmith#10448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a multiselect input with options fetched from a SQL query. The user select the options and a list should render based on selected options. On development mode it works fine but on deployed version the list display "missing data" also when options are present and selected

**Development mode**
![ok](https://user-images.githubusercontent.com/29399933/149824558-80d57129-3d60-4778-8e27-da0a3498d4f4.png)

**Deployed version**
![ko](https://user-images.githubusercontent.com/29399933/149824574-f17756a5-7fd2-4a1d-9ca6-4b4cdc5d81e1.png)
.

### Steps To Reproduce

1. Link a Postgres DB as Datasource
2. Add a SELECT query
3. Add the multiselect input widget that fetch data from the previous query
4. Add the list that render the selected items within a paragraph per item

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@dadebulba can you invite support@appsmith.com to your application to debug this issue?

**Comment by dadebulba** [comment]
Hi @Nikhil-Nandagopal, sorry, my bad. I discovered that the data delivered to the list was an Array of number. Apparently, Appsmith expects an array of object. So, instead of passing `[1,2,3]`, I casted it to `[{id: 1}, {id:2}, {id:3}]` and now the deployed app is working as expected. Maybe some debug/warning logs should be inserted in the browser console. Thank you for the support.
