### ISSUE TITLE
[Bug] Hover highlight in entity explorer should be edge-to-edge

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1045]
## Steps
1. Hover over an item in the entity explorer in an application
2. The hover is not edge to edge

**Comment by Jain-Sanchit** [comment]
Sorry if my doubt is too stupid , Can i know what is 'Entity Explorer'? @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@Jain-Sanchit the entity explorer is the sidebar on the left which has all the names of the widgets and APIs

**Comment by Jain-Sanchit** [comment]
@Nikhil-Nandagopal  Got it and got the error , One more thing , do we need edge to edge hovering or no edge to edge and just on the main area i.e. only the written part . I think I can try and solve this.

**Comment by Nikhil-Nandagopal** [comment]
@Jain-Sanchit i'm not sure I understand your question. The hover of the entity explorer should be edge to edge

**Comment by Nikhil-Nandagopal** [comment]
@Jain-Sanchit I don't see a PR linked to this issue so I'm unassigning this from you. Feel free to come back when you find the time

**Comment by sumanthyedoti** [comment]
I like to fix it

**Comment by Nikhil-Nandagopal** [comment]
@sumanthyedoti  go for it!
