### ISSUE TITLE
[Type]-[100]:Missing hover states across the application

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#10471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

![image](https://user-images.githubusercontent.com/34486435/150075099-cdaa405c-cf6c-4363-adae-a01133334018.png)

Hover state for the comments takes a while to kick in. The tooltip should be shown immediately on hover.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 1 |

**Comment by rohitagarwal88** [comment]
fixed in ADS 2.0
