### ISSUE TITLE
[Docs]: Mention about the usage of Smart JSON substitution 

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I can't find any section in the docs about "Smart JSON Substitution" option available in API settings.

### Describe the improvement

The docs should mention some examples that inform the user about the scenarios in which one should enable or disable Smart JSON Substitution. A video about the usage will be great.

**Comment by ajinkyakulkarni** [comment]
Related issues https://github.com/appsmithorg/appsmith/issues/11817, https://github.com/appsmithorg/appsmith/issues/8784

**Comment by jnikhila** [comment]
Documentation is available for [Smart JSON Substitution](https://docs.appsmith.com/core-concepts/connecting-to-data-sources/authentication#smart-json-substitution)
