### ISSUE TITLE
[Bug] Enhancement: Deleting the application user must be displayed with confirmation message

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1048]
https://www.notion.so/Enhancement-Deleting-the-application-user-must-be-displayed-with-confirmation-message-4b8ba7a1b1b14e7cb00065dcaa883c05

**Comment by mohanarpit** [comment]
Duplicate of #961

**Comment by prapullac** [comment]
Verified the issue and confirmation message is added into the action icon
