### ISSUE TITLE
[Bug]-[224]:App card is created even when app import fails and no action can be performed on this app card

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App card is created with no timestamp details when app import fails. This app card is a placeholder and performing any action like edit or launch throws a resource not found error.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/71cebf292b384a6293f0767805417ae3-00001.gif)](https://www.loom.com/share/71cebf292b384a6293f0767805417ae3)

### Steps To Reproduce

1. Try to import a corrupt app and observe an `internal server error` displayed when import fails
2. Refresh the page and observe an app card created for this app and have no timestamp details.
3. Clicking on `Edit` or `Launch` does not yield expected behaviour instead shows resource not found

### Environment

Production

### Version

Cloud

**Comment by ramsaptami** [comment]
This happens even when app duplication fails - except in this scenario the dummy app card created has timestamp details

**Comment by abhvsn** [comment]
@ramsaptami re-iteration here to keep the expectations consistent, in failure scenarios server should throw a friendly error message and the app card should not show up. Is there anything other we are looking for?

**Comment by ramsaptami** [comment]
Yep, think that should be good

**Comment by Nikhil-Nandagopal** [comment]
reducing priority since it doesn't break an existing app

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 28 |
| Effort (months)  | 0.25 |
