### ISSUE TITLE
[Enhancement]: Progress bar widget enhancements

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's no difference between indeterminate and determinate progress bar. We want to support the indeterminate or infinite loading progress bar in the widget.

### Steps To Reproduce

Select the indeterminate type of progress bar

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@dilippitchika we should probably do a v2 to merge both the widgets `circular` / `bar`

**Comment by fsureau-kpler** [comment]
Hi, the indeterminate status is a bug, right? We can set it to indeterminate but it does not change the behaviour

**Comment by dilippitchika** [comment]
Hey @fsureau-kpler yes it's a bug. One of the items we want to fix primarily is this.

**Comment by dilippitchika** [comment]
# Progress Bars

## Objective

*Here you fill in the objective of the product/feature that you are writing about.*

The progress bar widget needs to be enhanced to fix the indeterminate behavior and simplify the experience.

## Success Metrics *

*List of all metrics you are tracking and the desired goal.*

| Goal | Metric |
| --- | --- |
| Simplify user experience | Customer satisfaction score increases |

Requirements

*List of requirements for the feature or epic along with a user story informing why we need to support the requirement*

| Requirement | User story |
| --- | --- |
| Update the indeterminate type of progress bar for both linear and circular progress bars | As a user, I want to show progress for queries which don’t have % associated with them |
| Merge circular and linear progress bar. | As a user, I want don’t want to configure a different widget if I am trying to accomplish the same thing which is different visually. |
| Support steps in circular progress bar | As a user, I want to configure steps in a circular progress bar |

**Infinite loading**

Today the indeterminate progress bar doesn’t work, first objective is to support indeterminate bars both for linear and circular progress bars and then update the property pane.

Instead of using **type dropdown** for determinate and indeterminate, **we use a switch with the label “Infinite loading”**, when Infinite loading is switched on the following fields should be hidden in property pane - 

- Progress
- Number of steps
- Show result

**Merge circular and linear progress bar**

We should not have 2 widgets one for linear and other for circular, we can merge them into a single widget as the functionality is the same and the only difference is visual.

Here we use the type dropdown to separate the linear and circular progress bars.

**Circular progress bar to support steps**

Steps can configured in a circular progress bar similar to the linear progress bar.

**Migrations** 

No migration, we should introduce a new progress bar widget which can handle both linear and circular progress together.

- Also remove the circular progress bar in the list of widgets devs can add
- Anyone using an existing circular progress bar or regular progress bar can still edit them.

## Documentation

*List the documentation tasks that you are already aware of, and maintain this list as you go along*

- Remove circular progress bar widget documentation
- Update the properties of the progress bar widget documentation
    - Type - To linear/circular
    - Infinite loading

Out of Scope

<aside>
📢 *List the things that are out of scope or might be revisited after the first release.*

</aside>

- Improved property pane as per new designs
- Steps in a progress bar to be rounded off
- Progress % broken down into total and progress

Developer Handoff Document in Figma

<aside>
📢 *Link to the developer Handoff Document.*

</aside>

[https://www.figma.com/file/LJkCgOPC1ritQkEPlqLBaR/Progress-bar-prop-pane?node-id=1%3A2](https://www.figma.com/file/LJkCgOPC1ritQkEPlqLBaR/Progress-bar-prop-pane?node-id=1%3A2)

RACI Matrix

<aside>
📢 *Details of people involved in the project*

</aside>

| Responsible |  |
| --- | --- |
| Accountable |  |
| Consulted |  |
| Informed |  |

**Comment by dilippitchika** [comment]
@somangshu @Nikhil-Nandagopal please review this

**Comment by somangshu** [comment]
@dilippitchika following are my comment

> we use a switch with the label “Infinite loading”
- [ ] This will remain at the top of the property pane
- [ ] what happens if the user add config in the given field and then updates the switch, will the old config reset to default or should we try and persist it (might be difficult)

> No migration, we should introduce a new progress bar widget which can handle both linear and circular progress together.
- [ ] I suggest the name to be `progress widget`

> Type - To linear/circular
- [ ] this is not clear, I suggest we add it to the requirement list

**Comment by dilippitchika** [comment]
> what happens if the user add config in the given field and then updates the switch, will the old config reset to default or should we try and persist it (might be difficult)

We already persist for select and table widgets when server side filtering and pagination is enabled/disabled. This should work here as well, is what i think.

Updated the PRD for the rest of the items

**Comment by wmdev0808** [comment]
@somangshu 
Ok, I will
