### ISSUE TITLE
[Feature]: Make a change in the column headers such that the overflowing content is visible in the tooltip upon hover on column header.

### ISSUE THREAD

**Issue by vicky-primathon** [appsmithorg/appsmith#10495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would need tooltip for a column header since sometimes i have many columns and column name is big but i want to show as many columns as possible on view port. But this truncates table column name and i can't see the column header name without a tooltip. 

### Why should this be worked on?

This will allow users to have more columns visible on view port with context on column header name/title.

**Comment by somangshu** [comment]
@Tooluloope can you take the action here, please merge this is everything is done, or reassign this internally if required
