### ISSUE TITLE
[Feature]:  Support a load event for Select widget

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#10499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When the options are loaded in the Select widget, a [user](https://discord.com/channels/725602949748752515/760761686549463060/933649843598032926) wants to fire another query.  `onOptionChange` is only triggered when the selection is changed by manual user input.  Can we support a new event like `onOptionsLoaded` to support firing actions when options in Select widget are changed programatically or may be find another potential solution for this use case.programmatically

### Why should this be worked on?

Helps to automatically fire queries when data in the Select widget is changed programmatically.

**Comment by somangshu** [comment]
I get the context better now, But the name `onOptionsLoaded` might be misleading. It feels like when the options are finished loading fire my event. Also should be take a call to fire the onOptionChange when programatically the default value is changed and this probably does not happen when the value is first set on page load

cc @riodeuno @SatishGandham @sbalaji1192 @Tooluloope @dilippitchika
