### ISSUE TITLE
[Feature]: Support developers to use names given to custom columns while referencing the data

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith developers can reference any column name from table data, even if it's custom.

### Why should this be worked on?

Currently users have to remember what is customCol1, customCol2 etc. while binding data to other widgets. We want to ease the reference process.

**Comment by shadabbuchh** [comment]
@sbalaji1192 as discussed with you I'll move this issue to `Done` as we are able to reference custom columns with given names. However, I'll raise a separate bug for the above mentioned issue.
