### ISSUE TITLE
[Bug]: Google sheets operations don't work on sheets with space in name

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#10502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Google sheets operations should work without issues on workbooks with sheets that have spaces in the name. 

### Steps To Reproduce

1. Create a Google Sheets query
2. Link to a sheet with space in the sheet name. Eg. `Sheet with space`
2. Choose "Insert row" option from the dropdown 
3. Try to insert the row
4. See error. 

This is happening because Appsmith URL encodes the sheet name while the Google Sheets API doesn't accept the URL encoded form. 

### Environment

Production

### Version

Cloud

**Comment by prapullac** [comment]
Hi Leo
Tested this issue and observe the following 
Working Scenarios :
1) Space between sheet name works (ie: Forward me ) 
2) Space at the beginning or end of the sheet name works 

Not working scenario:
1) however if the name of the sheet is ( Forward me ) does show an parsing error even when the sheet name is added properly into the query
