### ISSUE TITLE
Set expiry headers on static resources

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#10503]

**Comment by sharat87** [comment]
@SatishGandham, can you add some more details to this please? Are we talking about cache expiry headers? Like `Etag`? I'm wondering what would be a reasonable expiry time for the static assets? Like, 5mins, 1day, 10days, etc.? Sorry if I misunderstood the whole point of this issue here.

**Comment by SatishGandham** [comment]
@sharat87 , I'm talking about the cache expiry headers. Since our js and css file names are hashed, we can set it to a year.
We cache these resources using service worker, but setting expiry headers will help if service worker is disabled or has an error.

**Comment by sharat87** [comment]
Ah yes, I forgot that they are hashed. Yes makes sense. Thanks for clarifying.
