### ISSUE TITLE
Optimise chunking and serve essential code on priority

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#10507]
Find and separate code essential for first load
- [ ] Find out why the entry chunk is 5MB
- [ ] Separate code for each screen
- [ ] Identify common code
- [ ] Rate code on priority

**Comment by somangshu** [comment]
@SatishGandham can you add your findings from before over here?

**Comment by somangshu** [comment]
This should be validated and closed

**Comment by SatishGandham** [comment]
This was handled as a part of first load / bundle optimization.
