### ISSUE TITLE
[Bug]: User is unable to set smtp server on Caprover  and digitalocean one click install

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#10500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://discord.com/channels/725602949748752515/760761686549463060/933633682047115325

I have been trying to install Appsmith on Caprover but every time I change the environment settings to update the email smtp and click save, Appsmith crashes and has an error report that a line can't be found in the docker.env file - I have also tried the digitalocean one click install - when I update the settings and click save I get a message that it has saved but then after about 30 seconds I get an error messag
![Screenshot_2022-01-20_at_08 01 37](https://user-images.githubusercontent.com/84702014/150310127-ea329293-ae61-4da9-9814-7f73ee7706fd.png)
e

### Steps To Reproduce

Try changing STMP server on self hosted instance on  Caprover  and digitalocean 

### Environment

Production

### Version

Self-Hosted

**Comment by sharat87** [comment]
@yatinappsmith, from the linked Discord conversation, it looks like the logs were sent to you on DM? Can you share them with me so I can take a look at this please? Thanks.

**Comment by sharat87** [comment]
Closing. If we can get the information asked above, we can reopen and investigate.
