### ISSUE TITLE
[Feature]: Accordion Widget

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#10516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user on discord requested for Accordion widget.

What is the Accordion component? 
an example can be seen here - https://jqueryui.com/accordion/

### Why should this be worked on?

This needs to be triaged

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #2888
