### ISSUE TITLE
[Bug]: Some of the columns in the grid are not as wide as the other ones

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#10524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to resize a widget the grid shows up and some of the columns are not as wide as the other ones.
I also tried to resize the widget to some of those grids, but the grid acts as if they don't exist.
I tried some of my old apps as well as creating new apps, but this doesn't happen there. It only happens for this app (an old app that I opened randomly today): https://app.appsmith.com/applications/616aa9b3770d321d435c3a23/pages/616aa9b3770d321d435c3a25

I also can not drag widgets around on the canvas.

### Steps To Reproduce

1. Drop a widget on the canvas
2. Try to resize it (doesn't work when I try to drag it around)
3. Observe

![Screenshot 2022-01-20 at 15 02 58](https://user-images.githubusercontent.com/81744497/150353355-1c1ece19-f37d-4717-8eff-33c93ab7779f.png)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@momcilo-appsmith can you give us access to the app? Does it happen if you clone the app as well? Can you share a video?

**Comment by zmajevic** [comment]
@Nikhil-Nandagopal I tried to reproduce this in other apps, it doesn't happen at all.

**Comment by momcilo-appsmith** [comment]
@Nikhil-Nandagopal I tried to reproduce this in other apps, it doesn't happen at all.

**Comment by Nikhil-Nandagopal** [comment]
ok then this must be an issue in older apps
