### ISSUE TITLE
[Bug]: Copy-pasting Stat Box widget causes the copy to appear inside of the original widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Copy-pasting Stat Box widget causes the copy to appear inside of the original widget instead of the usual behaviour where the copy appears below the original widget.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9e4119c333894a76b53715713e431132-00001.gif)](https://www.loom.com/share/9e4119c333894a76b53715713e431132)

### Steps To Reproduce

1. Select Stat Box widget and click copy
2. Paste the widget without exiting selection and observe the behaviour as seen in the video attached.
3. Repeat the same with other widgets and observe the behaviour is different. Even List widget which is similar to the Stat Box widget appears below the original and not inside.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Expected since it's a container. Will be different once we have a stat box widget and not a HOC
