### ISSUE TITLE
[Bug]: CRUD generation is not allowed when GSheet has only headers present

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a Google Sheet document has only headers and no data under those headers then the sheet cannot be used for CRUD.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/721afb5780264c91b62dc8452e130365-00001.gif)](https://www.loom.com/share/721afb5780264c91b62dc8452e130365)

### Steps To Reproduce

1. Create a Google sheet with only headers and try to use this on the CRUD feature.
2. Generate Page button is not activated until data is present under those headers.

### Environment

Production

### Version

Cloud

**Comment by abhvsn** [comment]
@sumitsum @nidhi-nair is there a way to get the column header when there is no row data except for the column headers, as this is needed while creating the CRUD page from the google sheet.  
Currently, we are fetching the first row in the google sheet and use their keys to populate the available columns using `FetchSheetRows` method and `RowLimit=1`

**Comment by nidhi-nair** [comment]
We'd have to write a separate command for this. Makes sense to do that anyway since a get structure would be expected to work for multiple sheets inside a spreadsheet. We could return with a schema that has a structure similar to the SQL kind.

**Comment by leotom2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BE-Coders-Pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/10527?planning-poker) with ZenHub @nidhi-nair @sumitsum
