### ISSUE TITLE
[Bug] Size of the Share must be increased 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1053]
The `Share` option displayed on the Home page is too small. Increasing the size of the Share option makes it visible and user friendly.

## Screenshot

![image](https://user-images.githubusercontent.com/458946/95243426-455a5d80-082e-11eb-8355-e16b5f0d5dac.png)

**Comment by Jain-Sanchit** [comment]
Is the share button on top navbar while editing the app? What size is expected ?

**Comment by mohanarpit** [comment]
@Debsourabh Can you please help with the correct dimensions of the button?

**Comment by Nikhil-Nandagopal** [comment]
@Jain-Sanchit this is for an on-going project so not currently up for grabs :)
