### ISSUE TITLE
[Enhancement]: Change the default page background to be closer to white

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Change default page background into a shade of white instead of the current color so that it looks a little more modern. 

Also assess the impact on current widgets.

### Why should this be worked on?

The current default page background looks like older admin panels. Changing it white would help bring a refreshed look to the UI.

**Comment by zmajevic** [comment]
Can we try these two colors? 
#f8fafc
#f1f5f9

**Comment by momcilo-appsmith** [comment]
Can we try these two colors?
#f8fafc
#f1f5f9

**Comment by dilippitchika** [comment]
@dhruvikn can you use #f8fafc in the modern theme's page background?
