### ISSUE TITLE
[Feature] Twilio Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#10539]
Integrate Twilio

**Comment by prapullac** [comment]
Issues identified in DP testing 
1. Appropriate Error messages are not displayed 
Ex: When on List message and Account SID is missing identifiable message is not displayed 
2. Mandatory fields are not displayed to users on List Command

**Comment by felixsuarez0727** [comment]
Thanks for the feedback @prapulla, here is my take on the issues you identified:

> 1. Appropriate Error messages are not displayed
>    Ex: When on List message and Account SID is missing identifiable message is not displayed

What I understand is that it would be appropiate to have error messages that are easier to understand to people who might have a hard time understanding the error messages that come from Twilio.

The image below shows the output (current behavior) of the suggested example:

![no-account-id-query-error-message.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/2f62b1da-e454-47e4-9bd3-abefc3ec6213)

The current behavior is to forward the response from Twilio (or any other plugin) as we receive it. Capturing the error message and injecting our own version of the message would require changes to the SaaS Integration App and possibly creating mappings for error message ranges.

Also, it seems this is the expected behavior:

![query-response.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/5b85ea82-d3f6-41c7-a88f-ab7aed2ca6de)

**Comments:**

- It should be safe to assume that someone working on an integration should be able to use the error response to figure out what is missing (particularly with Twilio that has pretty good error code documentation).
- It might be a good idea to have better form validation when creating queries (more on this next)

> 2. Mandatory fields are not displayed to users on List Command

The "required" asterisk is not that visible, but it's there:

![required-field.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/4444a181-1f88-4ebd-90e7-268dd138bece)

The Account SID is the only required field of this action (this is the current setup)

![required-acc-id-list.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/a8e83ff2-3d42-4956-a76d-bbd428de6d97)

**Comments:**

- Having a more visible "required" element, or even better, form validation for the "Query" form might be a good feature for FE.

> 3. Adding field names according to the Twilio application would help the user connect to appsmith faster

I would like to expand on this. I tried to stick to the terminology on the [Twilio API Documentation](https://www.twilio.com/docs/sms/api/message-resource).

We might want to come up with some guidelines on names of actions and labels for the integrations going forward.

Sticking as closely as possible to the official docs of the API seems a good starting point, so it is easier for any user to find the relevant documentation, but we might want to do "standardize" how the integrations are defined.

**Additional Comments:**

- Your comments bring up important aspects of the whole "Create a query from a plugin" experience, but nothing specific about the Twilio integration.
- We might want to handle those comments as separate issues for FE, but I would like to get someone else's take on it, I might be ignoring something about the scope of the integration.

**Comment by felixsuarez0727** [comment]
On a related note...

@AmanAgarwal041, are there any plans to pull the contents of the tooltip to the "Create Query" UI?

![tooltip.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/3f14c93e-98b1-4d1b-8c70-3b7c3414f2d1)

This might help to address @prapullac 's comment.

Or, by looking at the Airtable Integration, we might opt to put "helper texts" (ex: required, string, integer) on the labels.

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/f44be4db-0580-40fe-963c-c3b1d7cab4e2)

**Comment by felixsuarez0727** [comment]
Addressed comments regarding labels:

Opted for a simple human-readable format:

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/ce5d5418-d83f-4c7b-8f10-d3a583a11545)

Other info for ease of use (tooltip) will be added via the new UI designs.

**Comment by prapullac** [comment]
Issues on Twilio: @felixsuarez0727 
Twilio 
1. Since there is a single auth type we can make it as the default selection 
2. Twilio icon is not displayed to the user appropriately in the Query pane and entity explorer 
3. When the user clears the entered data the evaluated value must be displayed as “undefined” but we are currently showing empty.

**Comment by felixsuarez0727** [comment]
Adressed #2, Logo doesn't look as "crisp" as desired but it can be clearly identified as Twilio's logo.

Also added the Engineering Guidelines below so that we can have consistent looks:

- Prefer square logos as they look best.
- Usually `.png` and `.svg` formats work fine.
- Resizing to 24x24, 48x48 or 64x64 is often necessary (change according to the logo).

(Looking into 1 and 3 since they seem more related to behaviors of AppSmith components, and not so related to the Twilio Integration)

**Comment by felixsuarez0727** [comment]
Regarding 2:

When the user clears the entered data the evaluated value must be displayed as “undefined” but showing empty. But at the beginning if the value is empty it shows undefined.

https://images.zenhubusercontent.com/275993885/c3d4399f-715c-414e-a1b8-aee1872fec1b/video2896672334.mp4

Can someone confirm this is expected? It seems like a bug on those inputs.

**Comment by felixsuarez0727** [comment]
Regarding 1, integration has several types of authentication, by default the first option of the authentications must be started. But this is an example of the current behavior 

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/52ac6201-96ee-4f03-9d2b-4a840c5f1a6c)

For more details see #12565

**Comment by nidhi-nair** [comment]
This is now in production, and GA! :)
