### ISSUE TITLE
UQI Documentation 

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#10541]
Add Documentation for 
- End user experience while using UQI
- JSON / form mode
- Schema for where clause and sorting components

**Comment by nidhi-nair** [comment]
@jnikhila I'm going to be spending some time this week on creating a draft for these documentation changes. Mentioning this as an FYI so you're able to plan for this in your pipeline.

**Comment by jnikhila** [comment]
Sure @nidhi-nair - Do you have an expected date of completion and release? I can then accordingly add it to the pipeline.

**Comment by jnikhila** [comment]
@rohan-arthur / @nidhi-nair - I've shared the doc for review.

**Comment by jnikhila** [comment]
[Docs](https://docs.appsmith.com/datasource-reference/querying-google-sheets) are published.
