### ISSUE TITLE
[Bug]: Filter panel in table keep visible with no way to hide.

### ISSUE THREAD

**Issue by Isaac23164** [appsmithorg/appsmith#10556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I press on filter the filter panel appear and stay visible without a way to close it

### Steps To Reproduce

when I press on filter the filter panel appear and stay visible without a way to close it

### Environment

Deploy Preview

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@Isaac23164 there should be an x to close the filter. Can you share a video / screenshot of what you're seeing?
