### ISSUE TITLE
[Bug]: Select table dropdown from Quick Wizard page gets misaligned 

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#10559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I go to generate a page from datasource, the entity explorer closes after a while. If I have the dropdown opened, everything shifts to the left except for that dropdown.

### Steps To Reproduce

1. Click on Generate new page from a datasource
2. Open the second dropdown (select table one)
3. Wait a little bit for entity explorer to go away

<img width="852" alt="Screenshot 2022-01-22 at 09 43 57" src="https://user-images.githubusercontent.com/81744497/150631668-c87a3cc5-e680-4d9c-bf16-f5c0fd67acc2.png">

<img width="773" alt="Screenshot 2022-01-22 at 09 44 06" src="https://user-images.githubusercontent.com/81744497/150631671-f5ab0e30-d56f-4ff7-9342-b2e858e7b70d.png">

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
@momcilo-appsmith Hey, I'm not able to replicate this. I tried leaving it open for a few minutes, but the entity explorer didn't collapse. I also tried to manually collapse it, but it didn't lead to this misalignment. Any chance you can see if the issue still exists?

**Comment by Nikhil-Nandagopal** [comment]
This is fixed with the entity explorer docking
