### ISSUE TITLE
[Feature]: Create the GraphQL Query Editor Page with Query and Variable Inputs

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#10550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- [ ] Create a GraphQL Query Editor Page
- [ ] Add Query and Variable Inputs for the GraphQL requests

### Why should this be worked on?

This is the important part of creating a GraphQL queries for the user.

**Comment by prapullac** [comment]
WAiting for DP

**Comment by prapullac** [comment]
Verified on instance provided
