### ISSUE TITLE
[Bug]: How Appsmith works modal is broken

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#10564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When someone signs up they get this modal of how Appsmith works. One of the pictures in that modal is pushed out of it because another icon's size has somehow changed.

![image](https://user-images.githubusercontent.com/81744497/150635823-abe9f2df-f2ad-4a95-8b58-ef8e4cc29585.png)

### Steps To Reproduce

1. Create a new account
2. Get to the step where you get the How Appsmith works modal

### Environment

Production

### Version

Cloud

**Comment by Rishabhkaul** [comment]
Fixed with new onboarding. Closing this
