### ISSUE TITLE
[Bug]: Dragging table column cards doesn't scroll up/down the property pane

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#10561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I have a lot of columns, I can't scroll up/down the property pane while dragging the table column cards.

### Steps To Reproduce

1. Drag a table on your canvas
2. Create 10 columns
3. Try to scroll up while dragging one of the cards.

Loom recording:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/56e8895420214b01a7620614420a7ed0-00001.gif)](https://www.loom.com/share/56e8895420214b01a7620614420a7ed0)

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment]
Related to #8623

**Comment by somangshu** [comment]
This is duplicate of #4266
