### ISSUE TITLE
[Bug]: Long table search value gets covered by the clear icon button

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#10562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user tries to search for a value that is long, the search text gets covered by clear icon.

### Steps To Reproduce

1. Type in a long value in the search box in the table

<img width="568" alt="Screenshot 2022-01-22 at 11 05 04" src="https://user-images.githubusercontent.com/81744497/150634193-45b9d125-b379-47da-96e7-cb3c7475935f.png">

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment]
Is there a design showing how this should work?

**Comment by momcilo-appsmith** [comment]
The designs that were provided for the search component were pretty clear on what the width of the text is. You can find one of them here: https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=468%3A5421

**Comment by somangshu** [comment]
@momcilo-appsmith should we truncate the text?

**Comment by zmajevic** [comment]
@somangshu Yes, we should do that?

**Comment by momcilo-appsmith** [comment]
@somangshu Yes, we should do that.

**Comment by dilippitchika** [comment]
I was hoping we follow the behaviour similar to input widget, the text is revealed on moving the cursor forward with keyboard. 
![Screenshot 2022-01-27 at 10 42 06 AM](https://user-images.githubusercontent.com/19730984/151295965-b6b7bd24-9fd2-46c0-89b2-762eff5f54af.png)

Maybe i didn't get what truncate means here. If this is showing "..." is it because there is no boundary visible once the search bar is de-selected? Then truncation should only be shown for the deselected version.

There's one more discussion happening around the search bar size as well. I'll link so I can track.

**Comment by momcilo-appsmith** [comment]
@dilippitchika I suggest 2 different states here:
1. When the text is not in focus we show ...
2. When you click on the search box, it highlights the text and lets you use the arrow to go to the right. 
I attached screenshots as examples. What do you think?
![Screenshot 2022-02-03 at 00 31 58](https://user-images.githubusercontent.com/81744497/152255474-86a9cd3a-1511-4daf-9371-d7f78b042782.png)
![Screenshot 2022-02-03 at 00 32 01](https://user-images.githubusercontent.com/81744497/152255477-ff2a4327-cb16-4a78-ab12-e91219866d94.png)

**Comment by dilippitchika** [comment]
Hey @momcilo-appsmith yes this is inline with what I thought, can i know the reason why the search bar size is not longer?

**Comment by shwetha-ramesh** [comment]
@dilippitchika are we following the same design for input widget too ?

**Comment by somangshu** [comment]
@shwetha-ramesh I hope your query was answered, Apologies for getting late here. Can you attach a screenshot so we can discuss what scenario you are talking about

**Comment by shwetha-ramesh** [comment]
> @shwetha-ramesh I hope your query was answered, Apologies for getting late here. Can you attach a screenshot so we can discuss what scenario you are talking about

I was talking about this scenario here. There was ui overflow here too, but it seems to be fixed now. 
![image](https://user-images.githubusercontent.com/92293815/154212582-2bd8c1f2-1b73-4f77-9140-1ed2aea00924.png)
