### ISSUE TITLE
[Feature]: Download table/form to local file with format (JSON, CSV, etc.)

### ISSUE THREAD

**Issue by svanschalkwyk** [appsmithorg/appsmith#10566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Export a table or JSON object to a local file, specifying the format (JSON, CSV, etc.)

### Why should this be worked on?

Using Appsmith to edit and annotate data sources.

**Comment by Nikhil-Nandagopal** [comment]
@svanschalkwyk have you tried out download function? This should be able to achieve what you are looking for
