### ISSUE TITLE
[Feature]: As an app viewer, I should be able to easily click into the table search field, so that I can avoid mis-clicks on the table header.

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#10567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The default table search field is a nice feature with which I can search/filter the table, but there is a small usability problem with it. When I look at the table header, I cannot say where the search field starts and where it ends. In the following video, I first attempt to click into it in an area that is beyond the field boundary, and obviously nothing happens.

Uploading Screen Recording 2022-01-22 at 22.59.50.mov…

https://user-images.githubusercontent.com/94514895/150780671-37c7a16b-eee0-40a2-8f77-817396e038ef.mov

### Why should this be worked on?

the current behaviour can cause the user to get confused or frustrated because they don't see a response to their clicks. Solving this problem will make a more pleasant app viewer experience.

**Comment by dilippitchika** [comment]
@rohan-arthur the video is missing, can you add it again?

**Comment by rohan-arthur** [comment]
@dilippitchika done - have edited the OP

**Comment by somangshu** [comment]
We need a small design change to denote the clickable area for the search, Or programatically make it such that the search bar always covers the rest of the space!

**Comment by jsartisan** [comment]
Fixed in #17228
