### ISSUE TITLE
[Bug]: On hover the highlight is not proper

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#10577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Uploading Screenshot 2022-01-24 at 2.24.49 PM.png…]()

### Steps To Reproduce

1. Drag and drop a button widget
2. Click on property pane
3. Navigate to On click property
4. Hover on "Execute a query" property
5. Observe that the hover is not proper

### Environment

Release

### Version

Cloud

**Comment by ankurrsinghal** [comment]
Screenshot is not uploaded. What should exactly happen on Hover. The `Execute a query ` and `Execute a JS function` hover interaction is the same. @vivekverma2312 @somangshu

**Comment by vivekverma2312** [comment]
@ankurrsinghal Please check the screenshot and loom video
<img width="1920" alt="Screenshot 2022-01-24 at 11 00 33 AM (2)" src="https://user-images.githubusercontent.com/83569920/150793862-41af0a0c-158c-46ab-838e-d792993dcf61.png">

https://www.loom.com/share/aaa79f2c1696475b961798e89280eb79

**Comment by somangshu** [comment]
Are we able to verify this? How is this only happening on release? Can others check on local? cc @aswathkk @rahulramesha

**Comment by aswathkk** [comment]
@somangshu Observed this 5 days back on release. Check [this](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1642611214360100) thread
