### ISSUE TITLE
[Task]: Multiple export KT and tasks breakdown

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#10579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Rishabh-Rathod** [comment]
## Problems need to discuss before supporting multiple exports in JSObjects.

Currently, JS objects only support export default object and that is accessed using its name.
#### **Export method**
```
export default { data: [] }
```
#### **Structure**
The way `JsObject1` is stored currently is 
```
JsObject1 = { 
  data: []
 }
```
#### **Access method**
we write `{{JsObject1.data}}` to refer data.

Now, If Jsobject1 needs to become a js file exporting multiple values, we might need to consider below scenarios
### 1. Supporting multiple export
#### Export method
```
// JsObject1.js
const data = {};
const b = () => null;

export { data, b };
```
#### Structure
If we check the structure of JsObject1 here, normally how it is stored in JS is something like this.
```
JsObject1 = { 
  default: null,
  data: {},
  b: () => null
 }
```
#### Access method
`{{JsObject1.data}}`

Notice, the difference between the current scenario where 
- JsObject1 = default exported value and 
- here where JsObject = all exported members ignoring the default exported.

### 2. Supporting current default export with multiple export shown in 1st point
#### Export method
```
// JsObject1.js
const data = {};
const b = () => null;

export { data, b };
export default { data: 1 }
```
#### Structure
If we check the structure of JsObject1 here, normally how it is stored in JS is something like this.
```
JsObject1 = { 
  default: { data : 1 },
  data: {},
  b: () => null
 }
```
#### Access method
`{{JsObject1.data}}`
 // what would be the value here? 1 or []

This questions the current way user can access the JsObject.data and the structure.

**Comment by rohan-arthur** [comment]
currently not a priority
