### ISSUE TITLE
[Bug]: Preview and resizing not available when uploading Display Picture 

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Preview not available when uploading Display Picture from Filepicker widget. The user has to click on cancel and then upload the file. Only then the picture gets uploaded. User also not able to resize the picture currently. 

Also the picture gets compressed after uploading

_Similarly Organization logo is not visible too after upload._

![image](https://user-images.githubusercontent.com/92293815/150758662-a9a56df0-80a6-40db-b094-969639e2e95e.png)

![image](https://user-images.githubusercontent.com/92293815/151787368-ee3c0b11-3fd0-4052-b7e3-b6302c42f4d7.png)

https://loom.com/share/39c88514d4964999bc1f97c8ad318d4c
https://loom.com/share/dade1d84cfd946ed8a0c95be6d6fde41

### Steps To Reproduce

1. Click on _Edit profile_ > _Upload display picture_
2. Click on _browse files_ in pop up.
3. Upload a picture and observe

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
This does not break the app or stops user from actually using the widget, setting the priority to low

**Comment by akash-codemonk** [comment]
Profile image while uploading seems to be resizable.

https://user-images.githubusercontent.com/67054171/159282751-b01469fb-1261-4a4b-9b12-794164858173.mov

Organisation image after selecting an image is visible as well. Closing this issue.
