### ISSUE TITLE
[Bug] The login url should be /login instead of /user/login. Same for signup

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1058]
If someone types only `/login`, we should redirect them to `/user/login`? The same behaviour should exist for `signup`. It should redirect the user to `/user/signup`.

We still want to keep the `/user` prefix because that URL loads other assets and handles the navigation to other user login/signup related activities.

**Comment by Jain-Sanchit** [comment]
@Nikhil-Nandagopal Can you elaborate the issue a bit , I think I can work on this one .

**Comment by mohanarpit** [comment]
@Jain-Sanchit I've added details to the ticket. Please let me know if this makes sense to you. Would you like me to assign the issue to you as well?

**Comment by Jain-Sanchit** [comment]
@mohanarpit  I got the issue , and i think I have decoded what i have to do in the time .
I think I have to add 2 redirect routes in the client side in AppRouter.tsx file here [https://github.com/appsmithorg/appsmith/blob/bf2b4efbfd6cec003827dae35c645fd807cad0d9/app/client/src/AppRouter.tsx#L70](url) .
I will raise a PR , if you think its correct . Please assign me and let me know.

**Comment by mohanarpit** [comment]
@Jain-Sanchit Yes. Along with that you will have to remove the `/login` sections in the `docker/templates/nginx-mac.conf.template`, `docker/templates/nginx-linux.conf.template` and `deploy/template/nginx_app.conf.sh`. These Nginx files are responsible for the routing on the server side.
