### ISSUE TITLE
[Bug]: JS Snippet "aggregate query data" is incorrect

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The aggregate query data snippet in the JS snippets is wrong. It's not working. A user reached out to me thinking it was a bug in our chart widget. I don't know why there's an error, but the error is in this line

aggregateMap[user.status] = aggregateMap[user.status] ? 1 : aggregateMap[user.status] + 1

### Steps To Reproduce

1. Add a chart
2. Bind the chart to users db
3. Add the snippet
4. Bind to gender of a user
5. Notice the error. 

While we are also facing some validation related issue, this is happening because the JS snippet is incorrect. I updated the snippet and shared to the user.

{{
    function(){
      const aggregateMap = {
      };
      fetchUsers.data.map((user) => {
          if (aggregateMap[user.status]){
            aggregateMap[user.status] = aggregateMap[user.status]+1;
          }
          else{
            aggregateMap[user.status] = 1;
          }
      });
      return Object.keys(aggregateMap).map((key) => {
        return {
          x: key,
          y: aggregateMap[key]
        }
      })
    }()
    }}

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Fixed
