### ISSUE TITLE
[Bug]: Aspect ratio of video changes when Camera widget is longer in width than the aspect ratio

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2cb3685dd2ec4bd78bc19b2f41e146f0-00001.gif)](https://www.loom.com/share/2cb3685dd2ec4bd78bc19b2f41e146f0)

Aspect ratio of the image should be same in any (full screen mode or custom size) resolution of camera widget

### Steps To Reproduce

1. Add camera widget
2. Observe aspect ratio of the image you see in edit mode and Deploy the same
3. Observe the aspect ratio of the image you see in Deployed version

Note: Test run on Windows os laptop

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
@wmdev0808 can you comment if this is fixed in https://github.com/appsmithorg/appsmith/pull/10943?

**Comment by wmdev0808** [comment]
@dilippitchika ,
It's never been dealt

**Comment by dilippitchika** [comment]
Editing the issue then - The problem (which still exists) is the aspect ratio should be maintained no matter how the widget resizes. 

- If the camera widget is of higher height that aspect ratio can fit - the black bars should appear on the top (DONE Already #10943)

- If the camera widget is of higher width that aspect ratio can fit - the black bars should appear on the side as shown in the image below 
![Group 2 (1)](https://user-images.githubusercontent.com/19730984/155669811-a6fb4891-fbbf-440d-915f-e32da0413e23.png)

@wmdev0808 moving this to product backlog, please estimate this

CC - @Tooluloope
