### ISSUE TITLE
[Bug]: When table widget is binded with google sheet & forked to a different organization the data is lost.

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When table widget is binded with google sheet & forked to a different organization the data is lost.

https://loom.com/share/458ef6023bf7490eab05be2d2764a016

### Steps To Reproduce

1. Open a new application in Org A
2. Drag drop table widget and bind with google sheet
3. Fork this application to Org B and observe

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@shwetha-ramesh kindly alway add the required labels, We have automations in place which will add the relevant labels and assign the required entity.

**Comment by nidhi-nair** [comment]
This is expected since we do not copy authorization response to new organizations. We would expect users to re-authenticate the datasource for the data to show up.
