### ISSUE TITLE
[Bug]: ADS Dropdown component crashes App

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#10590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Double click on any dropdown selected option in the propertypane of any widget.property pane

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9931213360de4ea785d9e57c9f3b22d6-00001.gif)](https://www.loom.com/share/9931213360de4ea785d9e57c9f3b22d6)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@aswathkk could you check to see if this could be critical?

**Comment by aswathkk** [comment]
@somangshu I checked this in production and the error is getting logged in the console and this doesn't result in app crashing.
So, I think this is not a critical issue.

**Comment by aswathkk** [comment]
Closing this since it is already resolved in #11077
