### ISSUE TITLE
[Bug]: Highlighted text area remains highlighted even after text has moved on property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Expand property pane after highlighting text on a text field and observe the behaviour as seen in the video. Empty space is highlighted instead of the text. This empty space abruptly collapses when clicked on.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2b788af6ecad4e3f8203f1a4b434d39b-00001.gif)](https://www.loom.com/share/2b788af6ecad4e3f8203f1a4b434d39b)

### Steps To Reproduce

1. Type code into a text field of the property pane
2. Now highlight a block of text and expand the property pane

### Environment

Release

### Version

Cloud

**Comment by areyabhishek** [comment]
I don't see the bug here. Isn't this good behaviour?

**Comment by ramsaptami** [comment]
The highlighted text is holding position on screen location and not on the text as seen in the attached video below. Another thing that happens on Appsmith is the empty gap that's created while expanding the property pane causes the text box to abruptly collapse when you click the area where the highlight existed. It should ideally be a smooth transition.

 https://www.loom.com/share/5a66df7657444cea814b843586c69f6e

**Comment by somangshu** [comment]
@ramsaptami good find. 

Still treating this as low, It doesn't stop the user from building the app. 

Another thing is, Kindly do not add more issue to the EPIC - property pane improvements, We are fixed on the scope there, Labelling this `property pane` and leaving them will also allow we to later gather them in the next property pane epic

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working
