### ISSUE TITLE
[Feature]: Provide code formatter/prettifier near the JS object code

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#10602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

While adding "JS object", if we start coding and mess up the formatting, there is no way (except manual) to reformat the code.

![Screenshot-2022 01 24-21 37 50](https://user-images.githubusercontent.com/1573771/150823877-b102f0fa-89e0-4508-a624-6e0336e5bfcf.png)

### Why should this be worked on?

- This is a low hanging fruit (but also a low impact one)
- Properly formatted code can be edited faster again, if there is a need to change.
- It is a nice to have feature.

**Comment by rohan-arthur** [comment]
@IAmAnubhavSaini please see the comment here and add anything else that we might have missed: https://github.com/appsmithorg/appsmith/issues/9269#issuecomment-1000147580

**Comment by IAmAnubhavSaini** [comment]
@rohan-arthur I didn't know that it is called JS editor. Yeah that pretty much covers the use case.
