### ISSUE TITLE
[Bug]: List Widget Broke

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#10607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The list widget broken in our a force app
https://app.appsmith.com/applications/61cd5be2a4437918c01f87af/pages/61cd8575a4437918c01f89b2?branch=master

### Steps To Reproduce

1. Go to the app
2. Click on an issue
3. Click on upvotes
4. Notice multiple items without any data
5. This used to have data in it

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
there is definitely some problem, the standup app also is showing symptoms inside the list widgets in todays update, we need to investigate quickly and take an action

**Comment by somangshu** [comment]
Deprioritising to high, this is not directly related to the list widget, the JS expression sometimes fails to evaluate, clearing the field out and entering the value fixes the issue for now

**Comment by somangshu** [comment]
cc @riodeuno @SatishGandham

**Comment by Nikhil-Nandagopal** [comment]
@somangshu but this broke a users app so how is this not critical?

**Comment by somangshu** [comment]
Since this is not persistent and indirectly related to the list widget, I thought it should be high. But yes from the user pov this should be looked into at priority.

**Comment by Nikhil-Nandagopal** [comment]
Yeah if anything breaks an app that was working, it means it has caused negative business impact to a user so it must be critical

**Comment by Nikhil-Nandagopal** [comment]
Another user has reported this on discord https://discord.com/channels/725602949748752515/760761686549463060/937013227764711474
@somangshu @sbalaji1192 can we fix this on priority?

**Comment by somangshu** [comment]
@ohansFavour does #10737 fix this? Kindly link and close if that is the case

**Comment by ohansFavour** [comment]
Yes, #10737 fixes this
