### ISSUE TITLE
[Task]: Make Color picker keyboard accessible

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

![Screenshot 2022-01-25 at 3 25 42 PM](https://user-images.githubusercontent.com/10436935/150954299-ba20a017-4e89-42dc-a25f-8d9a44cccfb3.png)
Check Theming DP for updated property control

**Comment by aswathkk** [comment]
Closing this issue since it the PR is merged to theming branch

**Comment by btsgh** [comment]
Tested all the widgets, and their sub buttons (e.g. button group), to test the colour picker where ever it is present. All widgets- colour picker we are able to navigate through keyboard using the keys mentioned in the feat - 11797.
