### ISSUE TITLE
[Task]: Make Box Shadow control keyboard accessible

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

![Screenshot 2022-01-25 at 3 27 55 PM](https://user-images.githubusercontent.com/10436935/150954682-fdf27aa1-bc73-4030-b908-8e5c7d365cb1.png)
Check Theming DP for new controls

**Comment by aswathkk** [comment]
The PR got merged to Theming (#9714)

**Comment by btsgh** [comment]
Discussed with @aswathkk - since this is done in Theming EPIC and It’s not merged in to release yet, will wait for the merge into release to proceed with testing.

**Comment by shwetha-ramesh** [comment]
Tab to focus
ArrowRight and ArrowLeft to cycle through items
Space|Enter to select the item

Verifying this issue.
