### ISSUE TITLE
[Task]: Make Border radius control keyboard accessible

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

![Screenshot 2022-01-25 at 3 30 57 PM](https://user-images.githubusercontent.com/10436935/150955170-8fd47537-d089-43b9-9f76-b821fe2614ba.png)
Check Theming DP for new controls

**Comment by aswathkk** [comment]
The PR got merged to Theming (#9714)

**Comment by shwetha-ramesh** [comment]
Tab to focus
ArrowRight and ArrowLeft to cycle through items
Space|Enter to select the item

Verifying this issue.
