### ISSUE TITLE
[Task]: Make option input keyboard accessible

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

![Screenshot 2022-01-25 at 3 34 44 PM](https://user-images.githubusercontent.com/10436935/150955974-4b175e83-f3d7-48d7-b296-6752ec98e31f.png)

**Comment by Sripriya93** [comment]
Verified

https://user-images.githubusercontent.com/104895602/167385727-b74f1fdc-6b9a-41fb-9bd0-10390b9d1140.mp4
