### ISSUE TITLE
[Feature]: Ability to wrap widgets on smaller screens

### ISSUE THREAD

**Issue by thecodrr** [appsmithorg/appsmith#10627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, Appsmith has only a single static layouting option. This works but if you want to, say, layout 2 charts side by side, they appear really pinched on smaller screens. The workaround, obviously, is to layout everything vertically but this is a huge waste of space on bigger screens.

### Why should this be worked on?

Having the ability to either specify different widgets layout for mobile screens or a layout widget like `flex` would allow for apps that work beautifully across all screen sizes.

**Comment by Nikhil-Nandagopal** [comment]
Hey @thecodrr thank you for the feature request. We have this feature tracked here #4630 please do upvote it :)

**Comment by cverdes** [comment]
I think that it could be great to be able to have different widgets location and sizes for each different canvas sizes.

**Comment by Nikhil-Nandagopal** [comment]
@cverdes we're thinking of a viewport responsive solution where you can define breakpoints for views depending on the viewport.
