### ISSUE TITLE
[Bug]: RichText default text doesn't refresh on {{ Table.selectedRow.<field> }} and row selection changes

### ISSUE THREAD

**Issue by arminus** [appsmithorg/appsmith#10621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Table1 has 2 columns, id and description, in the Postgres DB, one row has a non-empty description, others have empty or NULL descriptions
- a RichText widget in the same page uses `{{ Table1.selectedRow.description }}` as DefaultText
- when selecting different table rows, the content of the RichText never refreshes while a Label widget with `{{ Table1.selectedRow.description }}`  does indeed refresh

### Steps To Reproduce

https://user-images.githubusercontent.com/683680/150964811-4325ad6d-374b-4623-a495-b44d80f32fdf.mp4

### Environment

Release

### Version

Self-Hosted

**Comment by somangshu** [comment]
should be fixed with #10629 cc @Tooluloope

**Comment by Tooluloope** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/10422

**Comment by somangshu** [comment]
@arminus thanks for reporting this issue, we checked it on our end and this has been fixed on our release and cloud environment. Once we tag the release, this should be available in your self hosted instance as well. Give us till the end of day, we shall keep you posted here

**Comment by arminus** [comment]
I can't reproduce the behavior described above in 1.6.8, however, the content of the RichText widget is now "sticky", i.e. if I open a modal with it a 2nd time, it still shows the old value, although its Default Text is set to empty, I didn't see that in my tests with 1.6.7...

**Comment by Tooluloope** [comment]
@arminus Could you explain further?

Do you mean you want the RTE to reset every time you open the modal?

Do drop a video so we can assist to help resolve the issue

**Comment by arminus** [comment]
Here you go. To me this looks like a regression in 1.6.8 - or a new feature which I don't quite like ;-) (seriously, if this is a feature, it would be nice to make it configurable)

https://user-images.githubusercontent.com/683680/151431776-be520a43-603d-42d2-8d5d-810f22876520.mp4

**Comment by dilippitchika** [comment]
Hi @arminus for now, can you reset the widget after Save is clicked and the action is executed successfully. We will investigate this issue further.

![Screenshot 2022-01-28 at 11 02 58 AM](https://user-images.githubusercontent.com/19730984/151492772-c16b8c04-5725-4c90-9268-dec24b18d1d0.png)

**Comment by arminus** [comment]
@dilippitchika  - fair enough, thanks.
