### ISSUE TITLE
[Bug]: Decimal dropdown is not getting fixed to "0" when decimal is already set to other than 0

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Decimal value is not getting back to "0" if set as 1 or 2 once

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/22ce9d2f76d54127a5db48ee7496aff4-00001.gif)](https://www.loom.com/share/22ce9d2f76d54127a5db48ee7496aff4)

### Steps To Reproduce

1. Add currency input to canvas
2. set decimal to 2
3. Add some 2 decimal value in the Default Text field
4. Try to change the decimal dropdown to 0
5. Observe that decimal is set to 2 itself

### Environment

Release

### Version

Cloud

**Comment by sbalaji1192** [comment]
duplicate of https://github.com/appsmithorg/appsmith/issues/10576

**Comment by chandannkumar** [comment]
Closing this, as it is a duplicate issue of #10576
