### ISSUE TITLE
[Bug]-[400]:"Disable icon" should be visible in Table widget's icon column is set to Disabled

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/787a5533764443d6a57697747b73f062-00001.gif)](https://www.loom.com/share/787a5533764443d6a57697747b73f062)

### Steps To Reproduce

1. Drag and drop a Table widget
2. Change the action column type to Icon widget
3. Select a icon widget
4. Enable disable property
5. Observe that when we hover the cursor on disabled icons, cursor icon should be changed to disable icon same as other widgets

### Environment

Production

### Version

Cloud

**Comment by adarshlilha** [comment]
@somangshu hey can I take this up?

**Comment by somangshu** [comment]
@adarshlilha go for it!

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 0.1 |

**Comment by somangshu** [comment]
#12767 should be fixed with this issue
