### ISSUE TITLE
[Bug]: Super Admin Page

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#10628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The super admin page on self hosted has a lot of issues

### Steps To Reproduce

- The default state of whether users can signup shows false even though it's true
- The vertical spacing between the fields is too high. There's the same spacing between sections and between fields.
- The restart modal contents are not centered and the text is cut
- Restarting the server ALWAYS fails
- The option to add admin emails does not grant other users access to this page
- We were not able to work out why configuring our email was not working. It just says send test email failed. There is no error message.
- The reset password emails aren't sent even when test email works

### Environment

Production

### Version

Self-Hosted

**Comment by ankitakinger** [comment]
Below is the status for each of the points mentioned in this issue:

- The default state of whether users can signup shows false even though it’s true -> **_Signup toggle has two values viz. Allow signup for all users and Allow only invited users. I guess the default should be allow all users and hence it is false by default._**

- The vertical spacing between the fields is too high. There’s the same spacing between sections and between fields. -> **_Has been fixed_**

- The restart modal contents are not centered and the text is cut -> **_Has been fixed_**

- Restarting the server ALWAYS fails -> **_We will be increasing its timeout from 30s to 60s… Currently working on it & creating a new PR for this_**

- The option to add admin emails does not grant other users access to this page -> **_Has been assigned to @trishaanand  Issue https://github.com/appsmithorg/appsmith/issues/11118_**

- We were not able to work out why configuring our email was not working. It just says send test email failed. There is no error message. -> **_It worked for me and @RakshaKShetty _**

- The reset password emails aren’t sent even when test email works -> **_Is this happening in case of Google/Github login? In the above new PR which I’ll be creating, we are going to show reset password only if form login is enabled._**

**Comment by ankitakinger** [comment]
Below is the status for each of the points mentioned in this issue:

**Has been fixed:**
- The default state of whether users can signup shows false even though it’s true
- The vertical spacing between the fields is too high. There’s the same spacing between sections and between fields.
- The restart modal contents are not centered and the text is cut

**Backend changes needed:**
- Restarting the server ALWAYS fails -> **We will be increasing its timeout from 30s to 60s… Currently working on it & creating a new PR for this (temp fix)**
Edit: https://github.com/appsmithorg/appsmith/pull/11591
- The option to add admin emails does not grant other users access to this page -> Has been assigned to @trishaanand Issue https://github.com/appsmithorg/appsmith/issues/11118

**@akash-codemonk is working on it:**
- We were not able to work out why configuring our email was not working. It just says send test email failed. There is no error message.
- The reset password emails aren’t sent even when the test email works.

**Comment by Nikhil-Nandagopal** [comment]
@ankitakinger let me know when I can test out the fixes!

**Comment by ankitakinger** [comment]
@Nikhil-Nandagopal the fixed issues can be tested after our next release since the Toggle button changes are not on prod yet.

**Comment by hiteshjoshi** [comment]
@sharat87 a way to know if its a slim container or not is required for this.

**Comment by akash-codemonk** [comment]
> * We were not able to work out why configuring our email was not working. It just says send test email failed. There is no error message.

Previously we had a hardcoded message. This has been fixed with showing the actual error message which is much more helpful.

> * The reset password emails aren’t sent even when the test email works.

This seems to work. Since the button now shows up only for form logins this will probably fix it.

**Comment by sharat87** [comment]
@ankitakinger @Nikhil-Nandagopal is this fixed then? Can we close?

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 I haven't tested this yet. Let me get to that and I'll close it
