### ISSUE TITLE
[Bug]: incorrect quotes around database table name in postgres integration scneraio

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#10631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add a postgres datasource and add any query, if the table name has hyphens in it, then quotes get assigned to first word after the schema and the dot. For example, `public."counter"-with-db`

The quotes should be applied to the whole table name. For example: `public."counter-with-db"`

![Screenshot-2022 01 25-23 54 40](https://user-images.githubusercontent.com/1573771/151036932-a72eaf0f-a21e-41c3-8b76-c5640fd38f7c.png)

### Steps To Reproduce

1. Create a postgres table with hyphens in its name.
2. Add postgres data source
3. Add a query
4. See that quotes wrap only first word after the dot.

I have not tried it with other databases. Yet.

### Environment

Production

### Version

Cloud

**Comment by Naveen-Goud** [comment]
Hii @rohan-arthur @IAmAnubhavSaini  ,I am picking up this issue. I will add solution approach after debugging the code.

**Comment by Naveen-Goud** [comment]
Hii @rohan-arthur @IAmAnubhavSaini  @Nikhil-Nandagopal , 
I think you can close this ticket.
I have tried to reproduce in local, but observed that its working fine .
below is the screen shot of implementation.
![image](https://github.com/user-attachments/assets/13065114-ddcf-4fb4-858b-ea319a539ce6)

thank you.

**Comment by Nikhil-Nandagopal** [comment]
@Naveen-Goud thanks for verifying this issue!

**Comment by rohan-arthur** [comment]
this is still reproducible, see screenshot
![Screenshot 2024-07-30 at 16 14 38](https://github.com/user-attachments/assets/5325eb2f-5e92-4a3f-b8c1-e0514792ec3f)

**Comment by Nikhil-Nandagopal** [comment]
@Naveen-Goud maybe it's only happening with table's with 2 hyphens

**Comment by Naveen-Goud** [comment]
@Nikhil-Nandagopal , Now I am able to reproduce it proper , Will  post an update with solution approrach after debuging the code.
