### ISSUE TITLE
[Feature]: Rich Text Editor (RTE) should expose toolbar icons for the TinyMCE loaded plugins

### ISSUE THREAD

**Issue by ruswerner** [appsmithorg/appsmith#10633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Looking at the Rich Text Editor widget source code here:

https://github.com/appsmithorg/appsmith/blob/6accb9e364dc30a055cb7b9e68af826425b52eb3/app/client/src/widgets/RichTextEditorWidget/component/index.tsx#L76

It appears that a multitude of great TinyMCE editor plugins are loaded, however the configured toolbar buttons here:

https://github.com/appsmithorg/appsmith/blob/6accb9e364dc30a055cb7b9e68af826425b52eb3/app/client/src/widgets/RichTextEditorWidget/component/index.tsx#L39

... do not include (expose) the features from the plugins. I am specifically interested in the image/media plugin and some others. Is it possible to expose the configuration of the toolbar buttons and/or plugins for a given RTE widget via the properties panel. I think it would be fine to pass through a JS snippet if that makes the feature happen sooner.

### Why should this be worked on?

TinyMCE is configured to load plugins, however the plugin features are not exposed via the hard-coded toolbar config. Our team needs these buttons in the toolbar.

**Comment by ruswerner** [comment]
One additional note: It seems inefficient (network/cpu-wise) to load these plugins that cannot effectively be used by the editor because the buttons aren't included in the toolbar. I recognise that one wouldn't want *ALL* the buttons in the toolbar b/c it would be overwhelming to most, however there should be a way to specify which buttons are in the toolbar.

**Comment by somangshu** [comment]
@ruswerner thanks for the feature request and the additional context you have provided 🎉 . we will start looking into this now and prfioritize the fix.

**Comment by dilippitchika** [comment]
@Tooluloope is there a reason these are not exposed today?
