### ISSUE TITLE
[Bug]-[900]:Welcome screen is not keyboard friendly

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#10634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The dropdowns on the form do not seem to retain their values when they are tabbed through and selected via keyboard. The form can only be submitted when the dropdown selection is done by mouse click.

Tabbing through does not pass through the CTA (Next button)

### Steps To Reproduce

https://user-images.githubusercontent.com/5298848/151114922-77b5a02a-a0a3-4e95-9ce2-d9bc7bcee52c.mov

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ad99526 you can go for it! Hope you've read our contribution guidelines :)

**Comment by Himanxu1** [comment]
HEY , I can work on it but i want  to clearly know that what to do like make this dropdown keyboard friendly?

**Comment by ankitakinger** [comment]
@Himanxu1 yes the dropdown currently only works with a mouse click. Should work with a tab key on the keyboard as well.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 900 |
| Effort (months)  | 0.5 |

**Comment by akash-codemonk** [comment]
This seems to be working now.

https://user-images.githubusercontent.com/67054171/171787310-13ce8c9e-3cf1-455f-a870-578548af04f3.mov

**Comment by akash-codemonk** [comment]
Reopening as mentioned again https://github.com/appsmithorg/appsmith/issues/14441. @sharat87 Could you add the browser and os used? Seems to work on chrome on mac.

**Comment by IM-TECHNO** [comment]
I'll Work on this Issue

**Comment by Nikhil-Nandagopal** [comment]
@IM-TECHNO sure go for it

**Comment by utkarsh-shrivastav77** [comment]
Hi is this issue still open

**Comment by alexhstone** [comment]
If this issue is still open, I'd be happy to do a fix.  Let me know!  Thank you!

**Comment by pranay-0512** [comment]
Is this issue still open? I can fix this

**Comment by sprajwal11** [comment]
Hi there!

I'm interested in working on this issue. Could you please confirm if it's still open and if I can get started on it?

Thanks!
Prajwal

**Comment by ankitakinger** [comment]
Closing this, as the welcome screen is keyboard-friendly now.
