### ISSUE TITLE
[Bug] Delete option on Property Pane looks like its on the edge.

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1063]
Steps to reproduce:
Step 1 : Add a widgets(Radio button ,Dropdown)
Step 2 :  Click on Property Pane 
Step 3 : Observe the Delete option 

![Screen Shot 2020-10-07 at 1 21 54 PM](https://user-images.githubusercontent.com/71753653/95303856-614b1700-08a1-11eb-8457-1da6863d2e48.png)

**Comment by NetPenguins** [comment]
I would like to take this one.

**Comment by Nikhil-Nandagopal** [comment]
@NetPenguins go for it!

**Comment by jyash97** [comment]
Hey @Nikhil-Nandagopal 👋 

It would be great to have a label to identify that the issue is already taken or someone is working on it. This will help new developers to filter issues.

Thanks

**Comment by Nikhil-Nandagopal** [comment]
@jyash97 we'll eventually transition to an unassigned status for issues that no one has claimed. Right now we're just moving all our issues from our internal notion to GitHub so I'm still the assignee on them :)

**Comment by NetPenguins** [comment]
Cant seem to get the dev env up and running. It continues to fail to compile. I keep getting random variants of the following  `'name' is specified more than once, so this usage will be overwritten.  TS2783`

**Comment by mohanarpit** [comment]
@NetPenguins Can you please join our [Discord](https://discord.gg/rBTTVJp) channel? Will be easier to debug there.

**Comment by NetPenguins** [comment]
I will be on tomorrow and will provide screenshots of what I'm seeing.

**Comment by Nikhil-Nandagopal** [comment]
> Hey @Nikhil-Nandagopal 👋
> 
> It would be great to have a label to identify that the issue is already taken or someone is working on it. This will help new developers to filter issues.
> 
> Thanks

All open issues are not unassigned :)

**Comment by jyash97** [comment]
> All open issues are not unassigned :)

Awesome thanks 💯

**Comment by Nikhil-Nandagopal** [comment]
@NetPenguins  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance! 😃

**Comment by akshay11298** [comment]
Hi @Nikhil-Nandagopal, if this issue is up for grabs, I'd like to work on it

**Comment by Nikhil-Nandagopal** [comment]
@akshay11298 go for it!

**Comment by akshay11298** [comment]
HI @Nikhil-Nandagopal, I have opened PR #1304 for this. Below is the screenshot of that screen. 
![image](https://user-images.githubusercontent.com/26507126/96553846-61044000-12d3-11eb-8c7a-5bfb299ac57d.png)

I am not sure why but one of the test cases got cancelled. Can anyone help me with that? Thanks in advance!

**Comment by akshay11298** [comment]
> HI @Nikhil-Nandagopal, I have opened PR #1304 for this. Below is the screenshot of that screen.
> ![image](https://user-images.githubusercontent.com/26507126/96553846-61044000-12d3-11eb-8c7a-5bfb299ac57d.png)
> 
> I am not sure why but one of the test cases got cancelled. Can anyone help me with that? Thanks in advance!

That issue has been resolved and all test cases have passed now.

**Comment by Nikhil-Nandagopal** [comment]
@akshay11298 awesome! One more successful PR! 🎉

**Comment by prapullac** [comment]
Verified the issue and works as expected
