### ISSUE TITLE
[Bug]-[2500]:Intrusive notifications while editing text values

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#10635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I drop a component and start editing its text value (in right-hand-side options pane), if there is an error in the code, a notification or more come up and block me from editing.

Ideally, notifications should pop up from a top edge (any corner), and there should be a way to dismiss these quickly. Instead of waiting.

![Screenshot-2022 01 26-12 02 01](https://user-images.githubusercontent.com/1573771/151115001-d0fefc4f-3110-43dd-9d19-c1ef3686d31e.png)

### Steps To Reproduce

1. Drag a component.
2. Start editing.
3. Make a wrong change which should trigger a notification/error toast.
4. Wait for it to go away. (this is the bug)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@IAmAnubhavSaini these can be dismissed by clicking on them, is it not clear for the user, we might need to check we need a cross icon, cc @momcilo-appsmith

**Comment by IAmAnubhavSaini** [comment]
@somangshu I realized that this notifications can be dismissed only while reading code. I have added `cursor: pointer` to indicate that these can be clicked. 

I also want to know if we can move these to center of the screen, because now the property pane is fixed on right.

**Comment by Nikhil-Nandagopal** [comment]
@IAmAnubhavSaini Where do you mean by center? Do you mean absolute center or top center or right center?

**Comment by Nikhil-Nandagopal** [comment]
This needs to be thought through carefully because this is only a problem for editors, app viewers will still be happy to see the notifications on the top right corner since they don't have any permanent real estate there

**Comment by IAmAnubhavSaini** [comment]
@Nikhil-Nandagopal it is a valid concern, I guess apps also spend more time deployed and have lot more users; than devs in edit mode. 

Do you think we should put a condition for edit vs deployed mode? (I don't know as of right now, how difficult/easy it is to figure that out).

**Comment by Nikhil-Nandagopal** [comment]
@IAmAnubhavSaini I guess the main question is what is the alternate location you are proposing to show this at?

**Comment by IAmAnubhavSaini** [comment]
@Nikhil-Nandagopal 

There are few things that I am considering.

1. Moving the toast closer to the top bar. Right now it is at `8em` offset. I am thinking `2rem`.
2. Moving the toast to center. (You can test the toast component here: https://fkhadra.github.io/react-toastify/introduction/)
3. Allowing app developers to set the value of position themselves. There are 6 of these, `{top, bottom} x {left, right, center}` This actually could be a separate feature.

Initially I wanted to fix 1, and move on. But now I think 3 would be worthwhile, as it gives developers more control over their apps.

**Comment by Nikhil-Nandagopal** [comment]
@IAmAnubhavSaini I think we offset it from the topbar because it covers the run button on the Query Editor otherwise. Please test this on all screens if you're making a change.
As for #3, I think that's a different problem to solve. showAlert is a developer configured notification vs this which is a system-generated notification. Changing this shouldn't affect that because it might hurt some developer apps that show critical information in the middle of the screen

**Comment by momcilo-appsmith** [comment]
We could change the position of it to be:
* Centered at the top, right below the toolbar
* Centered at the bottom

**Comment by Nikhil-Nandagopal** [comment]
Centered top makes the most sense to me for system-generated messages

**Comment by IAmAnubhavSaini** [comment]
![Screenshot-2022 01 31-11 55 57](https://user-images.githubusercontent.com/1573771/151748504-07a14d6e-0f81-4503-b9b8-e30cee8f79d9.png)

The image above makes me wonder if we need a minimum width for the notification.

**Comment by Nikhil-Nandagopal** [comment]
@IAmAnubhavSaini the width can be varying but it should be center aligned. Here it's centered but right aligned. Also just want to be doubly sure this does not affect the notifications from showAlert and only the system generated ones right?

**Comment by IAmAnubhavSaini** [comment]
Unfortunately these (shown in image above) are `showAlert`s. I am under the impression (still) that both are generated by the same code, except `showAlert` is programmable.

I tried getting system generated error, same thing, visually. Check below.

![Screenshot-2022 01 31-17 53 14](https://user-images.githubusercontent.com/1573771/151793451-566eae7a-622a-4e8d-9abe-bb4306ba38d9.png)

My guess is that the redux actions are different for `showAlert` and system generated notifications, but in the end, toasts are getting generated from the same code.

Let me see if there is a way to differentiate between the two.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5000 |
| Effort (months)  | 1|
