### ISSUE TITLE
[Feature]: Make Google Sheets scope editable

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#10639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

From [this](https://github.com/appsmithorg/appsmith/issues/10434#issuecomment-1019069451) comment, a user would like to restrict access to Google Sheets so we only have edit permissions on specific sheets. We need to let users create their own scopes for this, that overrides the provided scopes. Since some commands will fail after restricting the scope, we should also think of a way to convey the reason that those commands failed.

### Why should this be worked on?

Users are uncomfortable with sharing full access to their Google accounts.

**Comment by rohan-arthur** [comment]
will be fixed with #20191
