### ISSUE TITLE
[Bug]: Firestore queries show mandatory asterisk even when they are not

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#10640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="540" alt="Screenshot 2022-01-26 at 1 01 46 PM" src="https://user-images.githubusercontent.com/5298848/151121368-ecc230df-906d-43b3-a6ff-d2952aa11b91.png">

### Steps To Reproduce

Go the Get documents in collection command in Firestore queries

### Environment

Production

### Version

Cloud

**Comment by devnamrits** [comment]
Hi @nidhi-nair 
Can you please assign me this bug? I would like to resolve this issue.

**Comment by nidhi-nair** [comment]
Hey @devnamrits! The issue is all yours! :) Please make sure to read our [Code Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md) before getting started. Do let us know if you get stuck somewhere, or would like more information on the issue!

**Comment by devnamrits** [comment]
Thank you very much @nidhi-nair. Will surely connect whenever I get stuck.

**Comment by devnamrits** [comment]
Hi, I was installing the client-side application. First I got an issue name @types-shodown not found. For resolving this I installed the showdown module separately. After that, I'm getting this error after the development server gets compiled successfully.
Someone please help me in resolving this.
<img width="1388" alt="Screenshot 2022-03-01 at 9 56 06 AM" src="https://user-images.githubusercontent.com/54183698/156107546-7d2426f1-f9cf-4bd0-9e80-08cfbe80e29e.png">

I have installed and built an app/server on my end. It's running fine. 

cc: @nidhi-nair @ajinkyakulkarni @danieldare @rohan-arthur

**Comment by nidhi-nair** [comment]
@devnamrits Can you try pulling from our release branch again? This was an issue from the dev side that has since been fixed.

**Comment by devnamrits** [comment]
Okay great! Doing that

**Comment by devnamrits** [comment]
That error got resolved by taking the pull from the latest release.
But got this error. Have raised in discord as well?
Can I get the minimum required valued .env file for the client-side app?
<img width="839" alt="Screenshot 2022-03-01 at 10 47 35 AM" src="https://user-images.githubusercontent.com/54183698/156110847-cc09b7bf-8316-4073-84d2-26fe937457a7.png">

cc: @nidhi-nair

**Comment by devnamrits** [comment]
Hi @nidhi-nair before raising PR just wanted to ensure 

1. Collection/Document Path
2. Order By (JSON array of field names to order by)
3. Start After
4. End Before
5. Limit Documents

All the above should not be marked as mandatory which I referred to from https://docs.appsmith.com/datasource-reference/querying-firestore and have made changes as shown below. 

<img width="1433" alt="Screenshot 2022-03-02 at 9 36 14 PM" src="https://user-images.githubusercontent.com/54183698/156400255-4f8b2ce9-b51a-45d4-8c85-01ca5fab1b07.png">


But I think Collection/Document Path should be the mandatory field as it's being required to query over the firestore DB.
So please confirm which fields should be mandatory and which should be not. After confirmation, I will raise PR.
