### ISSUE TITLE
[Task] Create a default query and binding for all widgets

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1064]
## Description
getUsers will be the name of the query that returns 10 users
Table
DropDown
Radio 
Chart
Image

**Comment by areyabhishek** [comment]
This API needs to be really snappy else users will think the widgets are slow. We'll also have users from around the world use this in a self-hosted scenario. The API might be slow for someone far away from our data centers. Can we host this API on a CDN so that they don't experience any latency?
