### ISSUE TITLE
[Feature]: When migrations take place this updates application resources, which results inaccurate tracking changes for git-sync

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#10644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we run the migration during the release cycle more often than not we update resources attached to applications like pages, widget DSL, actions, JSObjects, etc. and users don't have any clue what migrations took place in a particular release. With the git-sync, we are providing a number of entities updated since the last commit to give more overview over updates to their apps, but with the migration we end up conveying incorrect updates.

### Why should this be worked on?

This is defeating the purpose of displaying the number of resources updates since the last commit 

![image](https://user-images.githubusercontent.com/41686026/155501149-8481c725-1efd-4527-b49d-2c162afef65a.png)

**Comment by abhvsn** [comment]
For now, we will be providing a friendly message that we are seeing x changes because of the DB migration

**Comment by abhvsn** [comment]
Reopening this as client-side changes are still pending
cc: @haojin111

**Comment by abhvsn** [comment]
As per the latest discussion we have updated the implementation to have `isManualUpdate` and `isAutoUpdate` flag to convey the changes if done by user or the by the migration.

**Comment by IAmAnubhavSaini** [comment]
@abhvsn The PR #11414 doesn't have `isAutoUpdate`.

**Comment by IAmAnubhavSaini** [comment]
`isAutoUpdate` Related: https://github.com/appsmithorg/appsmith/issues/12065, PR: https://github.com/appsmithorg/appsmith/pull/12099

**Comment by abhvsn** [comment]
@IAmAnubhavSaini can we close this?
