### ISSUE TITLE
[Bug]: Button drag issue in firefox

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#10655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Button is not draggable if drag starts from empty area in button. If I start dragging from the text, button is draggable. Happens in Firefox 91.5.

This doesn't happen in chromium, button can be dragged from any area.

https://user-images.githubusercontent.com/1573771/151161388-e69fe29c-8f59-4c0f-9c6a-f0ffb59772d1.mp4

### Steps To Reproduce

1. open firefox
2. drag drop a button
3. increase size of the button
4. drag from empty space, it is not draggable. (bug)
5. drag from text, it is draggable.

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
We can verify is this happening because of the pointer-event:all as pointed out by @aswathkk https://github.com/appsmithorg/appsmith/pull/8206
