### ISSUE TITLE
[Bug]: RichText modified state doesn't get set by copy&paste and stores empty or previous value

### ISSUE THREAD

**Issue by arminus** [appsmithorg/appsmith#10654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Copy&pasting something into a RichText control doesn't appear to set its modified state, resulting in an empty or previous content being returned by RichText.text

### Steps To Reproduce

https://user-images.githubusercontent.com/683680/151152956-71656884-1cb7-4908-9d86-b9834df3de85.mp4

### Environment

Release

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@arminus could you share the version of your application? This should be fixed in 1.6.7

**Comment by arminus** [comment]
See attached, I've xxxxxxxx'ed out the DB host and password (and I am on 1.6.7):

[richTextSave.zip](https://github.com/appsmithorg/appsmith/files/7943758/richTextSave.zip)

**Comment by arminus** [comment]
Cannot repro in 1.6.8 anymore - but now there's #10621

**Comment by dilippitchika** [comment]
Ok, closing this issue as it's fixed.
