### ISSUE TITLE
[Bug]: Esc key doesn't work while editing text in firefox

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#10665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In firefox, when I start editing text value and want to jump to next property via tab, pressing `esc` doesn't stop the editing text behavior.

This is not an issue in chromium. In chromium, pressing `esc` and then `tab` moves focus to next property.

https://user-images.githubusercontent.com/1573771/151292219-5cade799-80ae-451f-a5c5-164854729d25.mp4

This video contains two parts, first firefox then chromium. Notice that in firefox, `esc`, then `tab` keeps the focus at the current input.

### Steps To Reproduce

1. Open Firefox.
2. Add a Text
3. Edit text property
4. Press esc (bug)
5. Press tab
6. Notice that focus is still in the input and a tab has been registered as input.

Repeat with chromium to see that pressing tab will move to next element in property pane.

### Environment

Production

### Version

Cloud

**Comment by vuiets** [comment]
@aswathkk can you check this and cover it with [#8845 | Property Pane Improvements](https://github.com/appsmithorg/appsmith/issues/8845)?

**Comment by aswathkk** [comment]
@vuiets Checked and it is found to be resolved in #10641
