### ISSUE TITLE
[Bug]: Crash after Creating JS Object

### ISSUE THREAD

**Issue by sullo** [appsmithorg/appsmith#10661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating a new JS Object via the + button, if I select the new object from the sidebar the UI crashes and goes to a page titled "Oops! Something went wrong". This has happened more than once today. 

### Steps To Reproduce

1. On the left menu, next to "JS Objects," press the + to add a new jsobject
2. Select the new JS Object named simiarl to JSObject1

At this point the UI errors and "crashes"

A refresh of the page has the new object correctly created and selected.

### Environment

Production

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
This is duplicate of #10601
