### ISSUE TITLE
[Bug]: App breaks when you increase the height of the list item

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#10668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Here's the loom video showing the issue
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e52dd6a49b034b25b633f904f25eb236-00001.gif)](https://www.loom.com/share/e52dd6a49b034b25b633f904f25eb236)

### Steps To Reproduce

1. Drag and drop a list widget.
2. Try to increase the height of the first list item (stretch it quite a bit down)
3. The app breaks and if you try to open it again from the dashboard, it still shows as broken

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@somangshu we are not able to recover the application if this error comes. Can you take a look?

**Comment by dilippitchika** [comment]
@ohansFavour suggested that this issue will be fixed with the PR mentioned above.
