### ISSUE TITLE
[Bug]: Select all/deselect all do not work for the default row in table widget if it is changed 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#10669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/618c4e6e7b5c49a4bce8e5040daaa29e-00001.gif)](https://www.loom.com/share/618c4e6e7b5c49a4bce8e5040daaa29e)

### Steps To Reproduce

1. Drag and drop a table widget
2. bind the widget with with query
3. Enable multi-row select 
4. Change the default row value
5. Now if we select/deselect all on table widget the default row do not get selected/deselected

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@vivekverma2312 was this discovered from a user? If yes, can you add the community tag?

**Comment by dncpax** [comment]
Hello. I'm the original reporter. In my case, the multiselector has this bug in every situation.
To reproduce:
1) build an app from scratch
2) create a sql server query
3) create a table
4) bind the query.data
5) set multirow support
6) deploy app
7) select multiple rows
8) unselect the multirow checkbox -> rows are cleared BUT first row is selected

https://user-images.githubusercontent.com/2836636/151346877-535118f2-7489-4b7f-9e9e-623fdd283b1c.mp4

**Comment by dilippitchika** [comment]
Hey @dncpax thanks for the detailed video. I wanted to ask you if you need the default selected row to be the first row on page load? If that's not necessary for you, can you set the default selected value property to be empty? 

Let me know if it is necessary. Thanks for helping us out!

**Comment by dncpax** [comment]
I did not set a default selected row...

**Comment by dncpax** [comment]
ok, I understand... it's set by default to 0. Yes, when I cleared it, the  issue is solved.
Thank you. That is an easy solution that works for me.

**Comment by somangshu** [comment]
Hey @dncpax we too the call the set default selected row to 0 such that first time users who are trying to user use selectedRow in for say a query, they would not see errors and succeed easily, if the values are not present, we saw that the user faced difficulties in completing the transaction. 

What you have reported is indeed a bug, and AFAIK this seems to have resurfaced. We shall look into this. 

Dev note: 
- [ ] Add tests for selection of all / none if default selected row is set or not
