### ISSUE TITLE
[Feature]: Add JS option for Menu options in Menu Button widget

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#10682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, there is no way users could add menu options via JS and this has been requested by users.

### Why should this be worked on?

This is something we provide mostly for every widget except TAB and MENU, and it seems like a common use-case inside the Table widget as TableWidget cannot have a select widget inside it.

**Comment by somangshu** [comment]
More context: 
- [Slack thread](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1643252210061200)
- [Community post](https://community.appsmith.com/t/how-do-i-dynamically-create-menu-items-in-the-menu-button-column-type/517)

**Comment by somangshu** [comment]
@dilippitchika need you help here, Trying to understand how much of a real world use case this could be, Initially we assumed that the user will not need dynamic menu items, and show / hide / enable / disable for each menu item was provisioned. We did not see a value in giving an option for binding. 

Another reason was more technical, we did not want to expose the ID of each menu item to the app dev, we faced problems earlier in the tab widget because of this. If the use case makes sense, we will solve for this while implementing

**Comment by dilippitchika** [comment]
Will think about it in a bit more depth. However, dynamic widget creation is not just limited to menu buttons but can also be useful in other places. 

One place where we are internally using it is in JSON form for the array type input.

**Comment by somangshu** [comment]
@dilippitchika I think you are getting it wrong. I meant that the user want to make the menu items dynamic, get the values from a DB or something. Let me know if this needs a discussions

**Comment by dilippitchika** [comment]
Ok, if we know the max number of buttons then it can be done i guess, else we will again have to think about pagination and stuff.

**Comment by lublak** [comment]
@dilippitchika 
Technically, you can also simply say: Here is the maximum. You can only display 10 or the rest will not be displayed at all.
pagination would hardly make sense there i think. Possibly rather a scrolling.
I also had a similar request only in addition with submenus:
https://github.com/appsmithorg/appsmith/issues/10816

**Comment by dilippitchika** [comment]
Asked by another user today - https://discord.com/channels/725602949748752515/725609493974614076/945375041460244560

**Comment by somangshu** [comment]
@ashit-rath @sbalaji1192 we need your help here, What all we need to think of, We are thinking if we create this dynamically
- Configs will be lost
    - Should that always persist
- Will the users want to control this from the data object  
-

**Comment by sbalaji1192** [comment]
@somangshu Is there a use case for this? users won't be able to write onClick action handlers for dynamically generated menus.

**Comment by somangshu** [comment]
Removing this feature request from the menu widget in that case!

**Comment by Nikhil-Nandagopal** [comment]
Lets close this in favor of #6766
