### ISSUE TITLE
[Bug]: Creating JS Object creates an object Object key  inside the evaluations tree object of redux store

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#10689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Whenever JS Object is created, extra key with name `object Object` is created.
2. After creating more JS Objects no more new keys are created so the key was not necessary as it gets deleted on the deletion of any JS Object
![JS Object](https://user-images.githubusercontent.com/7565635/151351922-a646c6e5-cc2a-4562-a6d0-7cfaf1bbe574.png)

### Steps To Reproduce

1. Create a JS Object 
2. Observe in the redux console panel

### Environment

Production

### Version

Cloud

**Comment by satbir121** [comment]
Stale issue. Not reproducible now.
