### ISSUE TITLE
[Bug]: Ratings widget flashes previous rating when rating is reduced 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Reducing stars on rating widget causes previous value to flash before setting the selected rating

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/04343c7017b047a183551bf21662cb99-00001.gif)](https://www.loom.com/share/04343c7017b047a183551bf21662cb99)

### Steps To Reproduce

1. Click on a rating on a rating widget and reduce the rating - observe the widget flash previous value before settling on the lower rating

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
Might be related to the change in private widget.

@ramsaptami can you confirm if this happens outside the list widget?

**Comment by ramsaptami** [comment]
It happens when it's outside the list widget, i.e., on the canvas

**Comment by somangshu** [comment]
@wmdev0808 kindly triage this issue
