### ISSUE TITLE
[Bug]: Resolution issue with initial app suggestion

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#10698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="899" alt="Screenshot 2022-01-27 at 11 24 19 PM" src="https://user-images.githubusercontent.com/5298848/151416277-6bd1598e-d95b-4475-a729-511507d9d1c0.png">

### Steps To Reproduce

Login with a new user, wait for redirection to new app

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment]
Akash is fixing this. Will be live soon! Ill close this because it's been reported before. #10564
