### ISSUE TITLE
[Bug]: List widget does not support rating widget properly.

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#10691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The list widget is supporting the rating widget for some reason any more. Out internal standup app has the widget used inside the list in today's update and you can see that the values are evaluated properly but not rendered on the widget.

I tried check this on a new list widget with a new rating widget, At first it works, but as soon as I try a binding the widget does not show default rating anymore, neither does is rectify the widget if the value is hardcoded

### Steps To Reproduce

1. add a list widget
2. add a rating widget to the list
3. observe that the rating widget shows the default rating right now
4. replace the default rating with a dynamic binding now
5. observe that the rating widget does not respond to any inputs anymore
6. observe that changing the default rating back to hardcoded value also does not work

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@ohansFavour could you check if this is related to your change

**Comment by ohansFavour** [comment]
Yes @somangshu , I am reverting the private widgets feature [here ](https://github.com/appsmithorg/appsmith/pull/10693).

**Comment by somangshu** [comment]
@ohansFavour please take note if there was a migration written earlier, This might cause problems

**Comment by ohansFavour** [comment]
Noted @somangshu. I will fix the edge cases.
