### ISSUE TITLE
[Enhancement]: Use navigateTo() function to navigate to widgets

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. Current `navigateTo()` function can be enhanced to navigate to a different widget on the canvas or sub-menus of widgets like tabs or menu.

### Why should this be worked on?

When user wants to navigate to a different part of the canvas, we currently can't use the `navigateTo` function for this operation. A use case to that I can think of if for documentation kind of site, navigating to a specific location can help when creating links.

Another use case that came from a Discord user is navigating to different tables based on button widget action.

**Comment by oskarannas** [comment]
Similar to #8314
