### ISSUE TITLE
[Enhancement]: Enable scroll and Truncate text don't need separate switches in a text widget

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When truncate text option enabled in text widget, Scroll switch is not valid anymore as we truncate. We can indeed club the option together instead.

Bad suggestion but nevertheless a suggestion : Create a dropdown called overflow text and add Scroll and Truncate as options there.

![Screenshot 2022-01-28 at 11 30 18 AM](https://user-images.githubusercontent.com/19730984/151495356-0df005c3-5e2a-414e-a570-8192e29df547.png)
 

### Why should this be worked on?

Showing both options together doesn't make sense as one is dependent on other. @momcilo-appsmith can you please take a look at this?

**Comment by somangshu** [comment]
I agree to overflow being more accurate in terminology. I upvote for the solution. Technically, we might have a hard time with the migrations

**Comment by momcilo-appsmith** [comment]
I agree with the solution too.

**Comment by dilippitchika** [comment]
# Overflow in text widget

## Objective

*Here you fill in the objective of the product/feature that you are writing about.*

Today in the text widget, we have the power to enable scroll and enable truncate together, however both of these cannot work together the user has to select one or the other. 

The idea is to communicate this to the developer by updating the property pane. 

## Success Metrics *

*List of all metrics you are tracking and the desired goal.*

| Goal | Metric |
| --- | --- |
| Simplify user experience | Customer satisfaction score increases |

## Requirements

*List of requirements for the feature or epic along with a user story informing why we need to support the requirement*

| Requirement | User story |
| --- | --- |
| The user should be able to select either scroll, truncation or no overflow | As a developer, I want to be able to control the way overflow works in the text widget based on different use-cases |

Instead of having 2 switches, one for enable scroll and the other for truncate text. 

We should use only one field for the user to select how should the text overflow.

This field for now should be a dropdown field with label as “Overflow” with the following options

1. Scroll contents - Enables scroll in the text widget
2. Truncate text - Enables truncation in the text widget
3. No overflow - No scroll or truncation

Tooltip for label - “Controls the text behavior when length of text exceeds”
![Screenshot 2022-03-03 at 4 30 39 PM](https://user-images.githubusercontent.com/19730984/156552646-4bc46637-da5f-4a42-9973-d90bb7f83a90.png)

**For all new drag drop for text widgets, overflow should be set to No overflow by default.**

### **Very Important - Migration**

This needs to be done for all the text widgets, which means that we will need to migrate existing texts widgets to use the behavior. Cases to consider based on the switches today

| Current behavior | Future behavior |
| --- | --- |
| Enable scroll - OFF Truncate text - OFF | The option selected in the dropdown should be None |
| Enable scroll - ON Truncate text - OFF | The option selected in the dropdown should be Scroll contents |
| Enable scroll - OFF Truncate text - ON | The option selected in the dropdown should be Truncate text |
| Enable scroll - ON Truncate text - ON | The option selected in the dropdown should be Truncate text |

## Documentation

*List the documentation tasks that you are already aware of, and maintain this list as you go along*

- Update the text widget property table
    - Remove the “Enable scroll” and “Truncate text” properties
    - Add a new “Overflow” property
        - Content for the property - 
        It controls the text’s overflow behaviour when the length of text exceeds the defined area
            - Scroll contents - It enables scrolling within a widget's set boundary. It helps you not truncate long text and lets you display it inside a small area on the app.
            - Truncate text - It truncates the text that goes beyond the text box size.
            - None - It doesn’t overflow the text and shows the maximum possible text in the defined area.
- Remove the truncate text video
- Add a new video for Overflow

## Out of Scope

*List the things that are out of scope or might be revisited after the first release.*

- Using button groups in place of dropdown


## RACI Matrix

*Details of people involved in the project*

| Responsible |  |
| --- | --- |
| Accountable |  |
| Consulted |  |
| Informed |  |

**Comment by momcilo-appsmith** [comment]
Hey @dilippitchika is there anything you need from design team here?

**Comment by dilippitchika** [comment]
@momcilo-appsmith just need your sign-off, we will update the property pane when we are doing the property pane project.

**Comment by momcilo-appsmith** [comment]
@dilippitchika Reviewed it - seems good to me.

**Comment by somangshu** [comment]
@dilippitchika I am guessing we have the conclusion here, in case it otherwise, Please let us know

cc @wmdev0808

**Comment by dilippitchika** [comment]
Yes, we can proceed with the implementation
