### ISSUE TITLE
[Task]: Update widget default image 

### ISSUE THREAD

**Issue by UXFalcon** [appsmithorg/appsmith#10707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

@sbalaji1192 

Please update the default image 

https://assets.appsmith.com/widgets/default.png

to the attached one 

![image placeholder 2](https://user-images.githubusercontent.com/90375262/151512089-25942282-f486-434a-9de2-6fe4772b5e28.png)

**Comment by somangshu** [comment]
@UXFalcon is this related to the image widget

**Comment by somangshu** [comment]
I found out that this is to replace the default image of the image widget. The asset is attached above

**Comment by mohanarpit** [comment]
The image has been updated in the CDN. Closing this issue.
