### ISSUE TITLE
[Bug]: Elements on editor watch window overlap

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Elements on the watch window overlap on smaller resolution. We can instead move all operations to the second line and have only function name appear on the first line
![image](https://user-images.githubusercontent.com/79509062/151521603-e31c984a-a132-450f-8001-62a2134fc90c.png)

### Steps To Reproduce

1. Keep entity explorer and console open when on JS editor and vary their sizes to observe how the watch window elements behave

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment]
Another example of an overlap
![image](https://user-images.githubusercontent.com/79509062/153427762-74766c93-f8d5-4539-9b34-ad54cea2ec18.png)

**Comment by parth-appsmith** [comment]
@ramsaptami this is the older designs for the JS editor which is being completely revamped. This issues will be resolved with the new JS editor designs.

New Designs
https://www.figma.com/file/sT3HR1VSWOTtPfh5vlpU8x/?node-id=0%3A1

**Comment by rohan-arthur** [comment]
should become irrelevant after #10387
