### ISSUE TITLE
[Bug]: Text elements on query settings page are not alinged properly even though we have an option to scroll

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Need better placement of text elements on query settings page. They are compressed even though we have a scroll bar on that window but is not utilized well at the moment.

![image](https://user-images.githubusercontent.com/79509062/151522756-6bec2c56-8a6d-48b2-81b6-f5fc99df3954.png)

### Steps To Reproduce

1. Open up settings page of a query and observe the text elements and a scroll bar present on screen

### Environment

Production

### Version

Cloud

**Comment by Irongade** [comment]
Same as issue #10873.
