### ISSUE TITLE
[Bug]: Default error is displayed when a new JS object/function is created

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a new JS object or function displays default error for async function check

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c09b650194a240849ce8e6e9d7727151-00001.gif)](https://www.loom.com/share/c09b650194a240849ce8e6e9d7727151)

### Steps To Reproduce

1. Add a new JS object and observe the error as seen in the video above
2. Add a new function to this JS object and observe the same error show up again

### Environment

Deploy Preview

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
@ramsaptami is this still happening? if not, can we please close this?

**Comment by ramsaptami** [comment]
Closing this since the error is not appearing anymore
