### ISSUE TITLE
[Bug]: Recaptcha is not working on release

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time we click on submit button, recaptchaToken gets generated which we can see on Text widget(after binding). Currently recaptchaToken is not generated on click. 
Adding video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d7fb2d9b8d41465585d0c380f403fee4-00001.gif)](https://www.loom.com/share/d7fb2d9b8d41465585d0c380f403fee4)

### Steps To Reproduce

1. Add Button widget on canvas
2. Add recaptcha key for either v2 or v3
3. Add Text widget and bind with Button widget to see recaptcha token {{Button1.recaptchaToken}}
4. Click on the Submit button to display recaptcha on Text widget
5. Observe that token is not visible on Text widget

Note: Same activity has been done on Production and seems everything works fine there but not working on release

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@vicky-primathon please check this on priority. If you have a fix, make sure of adding the test case so that we dont have problems with this feature

**Comment by vicky-primathon** [comment]
Failing as getting below error when loading google recaptcha script. 
![Screenshot 2022-01-31 at 3.58.23 PM.png](https://images.zenhubusercontent.com/6041ffa5a2bd1760a7e766e9/33e7319e-c5ea-4e98-a263-590bf7f86eaa)

**Comment by chandannkumar** [comment]
@vicky-primathon Issue still exists on release

**Comment by vicky-primathon** [comment]
Can we use this solution here @somangshu 
https://stackoverflow.com/questions/61862932/chrome-extension-refused-to-load-the-script-because-it-violates-the-following-c

**Comment by vicky-primathon** [comment]
@chandannkumar  this issue is fixed on release

**Comment by chandannkumar** [comment]
@vicky-primathon still same issue. Since we are getting the error as "Violation of content security policy" in console only for release environment. Meanwhile we can confirm this fix after release 
cc @somangshu

**Comment by chandannkumar** [comment]
Reopening this. Since this issue is not working on release because of above reason mentioned.
Adding console error screenshots
![image](https://user-images.githubusercontent.com/95341241/153140652-0a094bd3-e2e0-4fcb-a38d-0310bc5552c4.png)
![Screenshot (23)](https://user-images.githubusercontent.com/95341241/153140754-22dde064-fb23-434e-80dc-b505da808dff.png)

**Comment by somangshu** [comment]
@sharat87 can you help us here? Not sure if this is something to do with the release env itself

**Comment by sharat87** [comment]
Added `www.gstatic.com` for `script-src`. Can we check once again please? @chandannkumar

**Comment by chandannkumar** [comment]
This seems working fine now
