### ISSUE TITLE
[Task]: Check and throw error if there is a discrepancy in dynamicBindingPathList before saving

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#10712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks
Related to https://github.com/appsmithorg/appsmith/issues/10037

We are seeing a lot of sentry errors lately related to invalid bindingPathList across multiple widgets(refer below). This error is being thrown from the server, hence we don't have much context on how we ended up with an invalid list. As part of this task, we need to add a check, before we make a save call, to identify this error on the client and then throw a sentry error. That way will have more context on the issue.
<pre>
 "widgetType" : "LIST_WIDGET",  "bindingPath" : "template.ButtonGroup1.groupButtons.groupButtonir5dikkud2.label",  "message" : "Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this.",  "widgetName" : "List1",  "widgetId" : "spuvlxlf5d",  "pageId" : "61ededd4be698f35db550072",  "layoutId" : "61ededd4be698f35db550070",  "dynamicBinding" : "SWOT"
<pre>

**Comment by sbalaji1192** [comment]
https://sentry.io/organizations/appsmith/issues/2880419545/?environment=Production&project=1546547&referrer=alert_email

**Comment by somangshu** [comment]
@keyurparalkar by when will be able to fix this up?

**Comment by keyurparalkar** [comment]
@somangshu this will get completed by today or max by tomorrow first half.
