### ISSUE TITLE
Update container widget doc

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#10721]

**Comment by jnikhila** [comment]
First draft available on [google doc.](https://docs.google.com/document/d/1Ed1p6EPhIgxe9keTjesUk4AsJ_H1UAt0qAtFqQ0rkuY/edit?usp=sharing)

**Comment by jnikhila** [comment]
@cokoghenun - As discussed, we'll need a video for container widget. Just a thought, as the container widget is more like a placeholder, if you create an app around it, it'll be beneficial for users.

**Comment by Rishabhkaul** [comment]
I am assuming this can be closed @jnikhila

**Comment by jnikhila** [comment]
@Rishabhkaul - We are awaiting an updated video. @cokoghenun

**Comment by cokoghenun** [comment]
Hey @jnikhila I can work on a newer video async as I have higher-priority videos to work on right now. But I've added this update request to my list

**Comment by jnikhila** [comment]
Sure, @cokoghenun - Please raise a PR once you have updated the video.

**Comment by cokoghenun** [comment]
Yes you can
