### ISSUE TITLE
[Feature]: Button Group widget: centered icon, no label

### ISSUE THREAD

**Issue by some-rando** [appsmithorg/appsmith#10725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, Button Group widgets have icon alignment options of left and right per button. But there is no centered option, which makes sense when there is a text label, but not when there is no text label.

As far as I can tell, the left and right icon alignment is really just "put the icon on the left or right of the label text, then center everything within the button boundaries." Meaning there's padding on one side of the icon to separate it from the text label, and that padding stays there currently even when there is no text. And that nudges it off center when there is no text label.

I can think of three options:

1. Add a toggle button, like the Visible and Disabled buttons to hide the text label and remove the padding on the icon. This seems most ideal so that each button can still have a label for developer use. A big bonus would be to have it JS enabled, especially if we ever get to a point where we have responsive design, or can read the window width to determine if we don't have enough space to show the text or not. This might be useful for other widgets too.
2. Detect when there is no text in the Label field and automatically remove the single side padding next to the icon which should automatically center it.
3. Add a centered Icon Alignment option that shows when there is no text in the label. This seems least useful of the three options.

### Why should this be worked on?

On small screens, like phones, sometimes a navigation menu that spans the width of the screen can have the text cut off if there is too much of it. But often the icons alone are enough of an interface help that the text is unnecessary. Icons alone would work. There may be other use cases too.
I don't know if it would be useful for icons only for sub-menu buttons or not.

**Comment by areyabhishek** [comment]
Thanks for the request. Adding a center alignment option makes sense. 
We'll be working on better responsive design in a few months so the widgets will work better.

**Comment by dilippitchika** [comment]
Ok, my suggestion is for the button group to also support icon button as a type of button which can be added. 

We don't have to worry about adding center positioning of the icon for a text button. 

@somangshu @momcilo-appsmith

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika I think this is a problem with the button itself and that has trickled down here. Even button alignment between icon & text cannot be controlled properly and solving that will solve this

**Comment by somangshu** [comment]
@dilippitchika One point
- Should we center the icon in case there is no label and icon alignment, this way we solve the problem without adding any overhead

**Comment by dilippitchika** [comment]
@somangshu i was checking what you said and based on it i found that in a button widget it automatically center's when there's no text. However in a button group it doesn't, the user also faced this - 

> Meaning there's padding on one side of the icon to separate it from the text label, and that padding stays there currently even when there is no text. And that nudges it off center when there is no text label.

**I think we only need to fix it in the button group.**  If we fix this, the user can start using the button group widget with icons for now. This is solution # 2 in what the user has proposed. 

Regarding the advanced settings which Nikhil mentioned, that can be a separate issue.

**Comment by dilippitchika** [comment]
Dev action item - 
- Please remove the extra padding in the button inside a button group when there's no label

**Comment by btsgh** [comment]
Tested this in Release. Without a label, the icon on Button Group widget is centred. Works as per feature expectation.
<img width="545" alt="Bug10725" src="https://user-images.githubusercontent.com/101863839/159905856-9233afdc-16ba-4e35-a417-7bcd1004d7c6.png">
