### ISSUE TITLE
[Feature]: BigQuery datasource

### ISSUE THREAD

**Issue by maximelebastard** [appsmithorg/appsmith#10728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I'd like to be able to use a Google BigQuery datasource to fetch data from this tool.
It would require to copy/paste Service Account file obtained from Google.

### Why should this be worked on?

BigQuery is a major Data Warehouse technology used for a lot of Data workshops.
It would be a great way to analyze big amounts of Data.

**Comment by Nikhil-Nandagopal** [comment]
Hello, we have this issue here #3129 so I'm closing this in favor of that
