### ISSUE TITLE
[Docs] How to use appsmith with your own authentication system

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1073]
## Describe the problem
Users need a step by step guide to using appsmith with their own authentication APIs
The guide should include steps on storing the access token, hiding views for unauthenticated users, navigating the users on success, and displaying errors

**Comment by sakshi006** [comment]
Hey @Nikhil-Nandagopal  can i work on this?

**Comment by mohanarpit** [comment]
@sakshi006 Welcome to Appsmith & for volunteering to contribute to the project. 

I'm sorry but this is a little more involved. It'll be better if a maintainer picks up this issue. I would suggest that you go through our [issue list](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) and pick one more suited for first contributors.

**Comment by sakshi006** [comment]
Sure, thanks!

**Comment by Nikhil-Nandagopal** [comment]
We're now welcoming contribution to this issue

**Comment by idivyanshbansal** [comment]
I would like to do this issue

**Comment by Nikhil-Nandagopal** [comment]
@idivyanshbansal apologies, we already have a guide for this and as such I'm closing this issue
