### ISSUE TITLE
[Bug]-[200]:Cannot jump to modal from js_object

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#10740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am at a js object, and click a modal, modal does not open. When I click a child element (say, text in modal) then modal opens.

I should be able to click a modal from js_object and get it to open.

https://user-images.githubusercontent.com/1573771/151761208-91c34cc9-1753-4fc5-8e56-cb17996b62bb.mp4

### Steps To Reproduce

1. Add a modal
2. Add a js_object
3. Click at modal, it won't open.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
So Glad someone finally reported this! I face this all the time and it's so annoying when it breaks my flow :)

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 0.5 |

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 updating the reach here because this is the same issue that happens when navigating via the omnibar as well and that has much higher usage.
