### ISSUE TITLE
[Bug]-[1500]:Focus pointer moves when page is scrolled in Welcome tutorial

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Focus pointer moves when page is scrolled in Welcome tutorial

![image](https://user-images.githubusercontent.com/92293815/151771987-1ded76cb-9e23-4852-b472-e3201b08fb57.png)

https://loom.com/share/bb2a76fdfbad416e9a0dbeafaa847f4e1

https://loom.com/share/08bd2365f8244fd7be4710cc44be286d

### Steps To Reproduce

1. Click on Welcome Tour on the bottom left corner of home page
2. Proceed with the tutorial. Scroll the page when the pointer appears and observe

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 1 |

**Comment by akash-codemonk** [comment]
@shwetha-ramesh The pointer moves based on the position of the element. Is the expectation to hide it when the associated element is not visible?
