### ISSUE TITLE
[Bug]: Select widget treating value `0` as false and hence causing validation issues in the form

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#10757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am passing the following array as options to the widget. This widget's REQUIRED is set to true w.r.t the form widget it is inside in.

```
[{
  label: 'Active',
  value: 1
}, {
  label: 'Inactive',
  value: 0
}]

```

I also have a form button which has "Disabled on Invalid Forms" set to true.
Now when I select the `Inactive` option from the select widget, the "Submit" button is seen as disabled. This issue wasn't there earlier.

### Steps To Reproduce

1. add a select widget in the form widget with the above data for options. 
2. set the select field to required
3. set the form to `Disabled on Invalid Forms`
4. select the `invalid` option with value 0
5. observe that the form button is still disabled

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
Bumping to critical since this broke a users app
