### ISSUE TITLE
[Bug]: Recordings that are saved are not playing

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#10759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Audio Recorder - It is observed that the saved recordings are not playing 

https://loom.com/share/97c6cec0f8074d8580ad393573902237

### Steps To Reproduce

1.Launch appmsith app in release environment
2.Drag and drop audio recorder widget
3.Click on play icon to record audio 
4.Click on tick icon to save the recording 
5.Click on the play icon on the saved recording and observe the recording is not playing 

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Assigning high, because it's a clearly written that a user can play the recording they saved and users would like to play the recording before uploading it to apps.  But @YogeshJayaseelan can you verify if it's happening on Production also?

**Comment by YogeshJayaseelan** [comment]
@dilippitchika No this is not happening in production

**Comment by dilippitchika** [comment]
@wmdev0808 can you check this issue on priority? It's only happening in release.

**Comment by somangshu** [comment]
@dilippitchika @YogeshJayaseelan this seems very similar to the #10756, Something has changed and causing this error on console for release specifically

`Refused to load media from 'blob:<URL>' because it violates the following Content Security Policy directive: "media-src * data:".`

Need some help here @sharat87 @mohanarpit

**Comment by Sripriya93** [comment]
Verified

https://user-images.githubusercontent.com/104895602/167565187-95ecb5da-7dbd-4ccc-b61e-959354759355.mp4
