### ISSUE TITLE
[Bug]-[4000]:Wrong widget name in Welcome tutorial

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The widget name shown in Step 4 & Step 5 of the description of the tutorial doesn't match with the widget 

![image](https://user-images.githubusercontent.com/92293815/151774964-8cf42e66-89c6-4968-910f-54d8c69d6188.png)

![image](https://user-images.githubusercontent.com/92293815/151776984-9990bb05-ee9a-4f4c-8dca-a03cef966b29.png)

### Steps To Reproduce

1. In home screen click on Welcome tutorial
2. Process to step 4 & step 5 and read the description of the tutorial and verify with the widget name

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4000 |
| Effort (months)  | 0.5 |

**Comment by shwetha-ramesh** [comment]
@akash-codemonk the below image issue still exists. Hence re-opening this issue.
![image](https://user-images.githubusercontent.com/92293815/167344604-b60ba491-141f-4f6a-85bd-4a000ca35604.png)
