### ISSUE TITLE
[Bug]-[300]:The focused cursor is displayed at the end of the input field

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The focused cursor is displayed at the end of the input field

### Steps To Reproduce

1. Generate a crud page In a firefox browser
2. Now click on the input box the cursor blinks at the end of the input widget instead of the place where curser clicked

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 150 |
| Effort (months)  | 0.5|
