### ISSUE TITLE
[Bug]: Enable/disable and dynamic value fetch is not working in UQI forms

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#10761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The functionality of the enable/disable to 

### Steps To Reproduce

Not on prod so can't be tested normally. 

### Environment

Release

### Version

Cloud

**Comment by prapullac** [comment]
Waiting for backend changes

**Comment by prapullac** [comment]
Verified as a part of regression
