### ISSUE TITLE
[Bug]: TextWidget crashes when bound to large data, like JSON from api response

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#10771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever you bind large data to text widget, it crashes the application.
Usually users bind api response to a text widget for debugging purposes, and this puts the application in unrecoverable state.

### Why this happens
Unlike table or list widget, we don't restrict the amount of data we show in a text widget. 
When we have lot of nested data, that results in a high amount of dom nodes.
Response from this innocent looking API of about 700KB creates a million dom nodes
https://restcountries.com/v3.1/all

Half a million among those are BR tags

<img width="423" alt="Screenshot 2022-01-31 at 8 16 20 PM" src="https://user-images.githubusercontent.com/441914/151814662-ec54f929-5e26-4344-b53d-c8d9cf9eb1b1.png">

### Suggested fix?
Truncate the text when its large. Show a small button/ellipsis to load more text.
We can estimate the number of characters we have to show based on area of the text widget.

```
// Sample code
  getText() {
    const { text } = this.props;
    if (text && text?.length > 10000) {
      return text?.slice(0, 5000);
    }
    return text;
  }
```

#### Things to consider

- Since we allow HTML tags in the text widget, this may remove the closing tags and mess with rest of the application. 

### Steps To Reproduce

- Make an api pointing to https://restcountries.com/v3.1/all
- Bind it to a text widget

This will put the application in unrecoverable state.

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@SatishGandham we have "truncate text" as a property in the text widget, should we just enable it by default?

**Comment by SatishGandham** [comment]
@dilippitchika This is close to the implementation I had in mind, but I can not make that product decision.

**Comment by dilippitchika** [comment]
Understood, @somangshu moving this to needs info. Can you assign someone to help understand the truncate text behavior changes suggested by @SatishGandham?

**Comment by Nikhil-Nandagopal** [comment]
Will truncating help because the large data is still going to be in the evaluations so AFAIK that will still cause this to crash?

**Comment by dilippitchika** [comment]
@SatishGandham there's another issue #10569 and it looks same, I am closing the other one. Please re-open if that's a different one.

**Comment by SatishGandham** [comment]
@Nikhil-Nandagopal , Yes, I verified it. The page crashes because we create a lot of DOM nodes. Same data works with table or list widget because we don't render all of it.

@dilippitchika , its the same issue. Thanks.

**Comment by somangshu** [comment]
Seems like this is also what in happening in #[10379](https://github.com/appsmithorg/appsmith/issues/10379)

**Comment by somangshu** [comment]
we found out that the content inside the text with a broken HTML tag does not flow outside the text widget and effect the rest of the DOM. The above strategy could probably work.

**Comment by prsidhu** [comment]
@somangshu @SatishGandham  an update on this one:

1. In case of large json data (json or html), truncation doesn't break the screen or cause overflow.
2. If text contains any of these tags - doctype, html, head or body; then the widget breaks with the following error:
```HTML documents as Interweave content are not supported```.

https://github.com/milesj/interweave/issues/124

If it's not an overkill, then could either handle the error better or try again by stripping away undesirable content. What do you suggest?

Large json data as returned by (https://restcountries.com/v3.1/all) makes for an Extremely slow render. Still trying to debug that.

**Comment by prsidhu** [comment]
Rendering is slow because it's still trying to render the complete text. 

Will push a fix next: Based on the area of the widget, we can use a slice() of the text as a state variable (displayText), while pass this.props.text to the modal component as is.

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal yes, it will render as it does today

**Comment by somangshu** [comment]
@prsidhu what is the update here?

**Comment by prsidhu** [comment]
@somangshu dev is done. Will create a pr by eod
