### ISSUE TITLE
[Bug]-[300]:The binding is not displayed for the button group widget in the entity pane

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The binding is not displayed for the button group widget in the entity pane 
![image](https://user-images.githubusercontent.com/45958978/151925374-19104a45-3b8f-4c15-b48b-4acaca9d8d6c.png)

### Steps To Reproduce

1. Go to canvas
2. Drag and drop the Button group widget In the entity pane
3. Click on the meat ball icon( 3 dots icon)
4. Click on Show Binding 
5. There is no data displayed the pop up closed 

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 1 |

**Comment by kocharrahul7** [comment]
This has been solved now

<img width="1459" alt="image" src="https://github.com/appsmithorg/appsmith/assets/20532920/9998f8c9-0501-493c-b198-5065cc7e408e">
