### ISSUE TITLE
[Bug]: Submission disabled if widgets not marked as required have validation

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#10785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a widget is marked as not required but has some validation, the **Submit** button gets disabled. For eg: on a Datepicker widget if there is a **max date** property set up which is an earlier date (default date is TODAY),  the user is prevented from submitting and is forced to enter something in the Datepicker.
<img width="1149" alt="Screenshot 2022-02-01 at 2 53 56 PM" src="https://user-images.githubusercontent.com/32227135/151942898-c1ba02aa-ec8e-43b9-858e-b87f938bf5c2.png">

Also pasting the link to Discord conversation for this issue - https://discord.com/channels/725602949748752515/760761686549463060/937988720198549574

The validation property seems to override the Required property.

### Steps To Reproduce

1. Drag and drop a Datepicker widget on a Form. Mark as **not required**
2. Set the max date property to a date earlier than today's date
3. The submit button gets disabled on the form even though the user has not selected any date yet. 

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@danciaclara this is actually valid because in this case the default date is after the max date which means the date selected is invalid so the form should be disabled
