### ISSUE TITLE
[Feature]: Ability to change the background color of the page

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#10815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

New option for setting the background color of the page should be added.

### Why should this be worked on?

To change the background ui of the application for every page.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika @jsartisan seems like a fairly simple feature we can add for users

**Comment by jsartisan** [comment]
We are already doing this in app theming PR.

**Comment by dilippitchika** [comment]
Talked to @jsartisan we don't have a way to do it at a page level only at an app level. Will co-ordinate with Liz and add this.

**Comment by jjohnson5253** [comment]
We would also like to be able change the background color of apps to something besides white! We need to make a dark themed app. Please implement this if possible!
