### ISSUE TITLE
[Feature]: Custom navigation

### ISSUE THREAD

**Issue by lublak** [appsmithorg/appsmith#10816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A way to organize the pages into subgroups.
This could also simply help a menu button that can be configured on the one hand with a json configuration and on the other hand also allows under menu buttons.

### Why should this be worked on?

Currently there is only the normal menu button.
This one does not allow you to configure it via json nor to build submenus.

**Comment by Nikhil-Nandagopal** [comment]
Hi @lublak we have this issue tracked here, could you please upvote that one? #2282

**Comment by lublak** [comment]
@Nikhil-Nandagopal oh thanks :)
I had not found that because I had searched for nested menu. Thank you.

**Comment by lublak** [comment]
@Nikhil-Nandagopal can we reopen this?
Since I'm talking about custom navigation here.
Besides appsmith application I would also like to include links with navigateTo.
Based on this: https://www.youtube.com/watch?v=Fu2PaPnIyus

**Comment by Nikhil-Nandagopal** [comment]
@lublak sure re-opening it for custom navigation

**Comment by pranavkanade** [comment]
Closing this issue in favor of a more specific requirement of allowing multiple levels of nesting in the menu button widget. https://github.com/appsmithorg/appsmith/issues/11733
@lublak
