### ISSUE TITLE
[Feature]-[308]:Show correct lint error when async/await is used in a function

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#10825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user faced the following problem.

![image](https://user-images.githubusercontent.com/800578/152131345-108893da-d945-4ae8-84d5-fb04c42cccb9.png)

This is because, we are currently showing the following error message

![image](https://user-images.githubusercontent.com/800578/152135641-b57a1027-3500-4d14-9abd-9384a0ca4a15.png)

Instead, we should tell the user to mark the parent function async.

### Why should this be worked on?

The current error message is not very helpful for the user to resolve the problem by himself/herself. We should provide an accurate error message.

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 154 |
| Effort (months)  | <<number>> |
