### ISSUE TITLE
[Bug]: JSObject function execution is disabled without any error message

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#10824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have written the following code.  No error message is thrown, but at the same time, I am not able to run any function.

![image](https://user-images.githubusercontent.com/800578/152132986-eb3e0ed1-df5f-4f8d-9422-397161090067.png)

### Steps To Reproduce

1. Create a JSObject
2. Add the following code
```javascript
export default {
	myVar1: [],
	myVar2: {},
	myFun1:  () => {
		let a = this.myFunc2();
		let n = [1,2,3]
		n.forEach(function(val){
			console.log(val)
		});
	},
	myFun2: async () => {
		return 1;
	}
}
```
3. See that no error message is thrown still you can't run any functions

### Environment

Production

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
@ajinkyakulkarni this is not high but fixed it anyways. 
there is a warning and i was checking the wrong list to disable the response panel.
warning in above code is - a variable is defined but never used.
