### ISSUE TITLE
[Feature]: Show remaining number of pages in the table widget

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#10830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- Add a text to show remaining number of pages in the table widget when there exist total records count.

### Why should this be worked on?

This was a feature requested by the user.
[https://discord.com/channels/725602949748752515/760761686549463060/938400013086781450](https://discord.com/channels/725602949748752515/760761686549463060/938400013086781450)

**Comment by dilippitchika** [comment]
Looks like we missed this while adding Total Record Count. @Tooluloope can you confirm who worked on Total record count on server side filtering on the table?

**Comment by somangshu** [comment]
This should be an easy fix. good catch @AmanAgarwal041.

@Tooluloope I am assigning this to you for now

**Comment by dilippitchika** [comment]
High reach, low impact

**Comment by dilippitchika** [comment]
Reach: 215 at-least in last 6 months
Impact: Low
