### ISSUE TITLE
[Bug]: Datasource `+` button takes user to Create New tab even if there are active datasources.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#10839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c46ea675545a4b34804b0197ad0db1b7-00001.gif)](https://www.loom.com/share/c46ea675545a4b34804b0197ad0db1b7)

### Steps To Reproduce

1. Create new app in an org where you already have datasources
2. Click on Datasources `+` button, you'll be redirected to `Create New Tab` instead of `Active`

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is expected because + query can be used to create a query on a datasource
