### ISSUE TITLE
[Bug]: Execute Query menu not scrollable when overflowing

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#10835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user tries to assign and execute query on click action, If user have more number of queries present in the app, user is not able to scroll to the overflowing content.

Also, suspecting this can happen for "Execute JS Function"

![Screenshot 2022-02-02 at 7 45 32 PM](https://user-images.githubusercontent.com/87797149/152170752-70ae35f7-dcbd-460e-b88e-974e637ae974.png)
.

### Steps To Reproduce

1. Drag and drop a button
2. Goto onClick action
3. Select "Execute a query"

### Environment

Production

### Version

Cloud

**Comment by RakshaKShetty** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/152727354-fb0fea78-d589-4d1b-8c1a-45c41bb96789.png">
