### ISSUE TITLE
[Bug]: Ensure correct capitalization of product names across docs and Appsmith platform

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#10848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently, MySQL is written as Mysql, MSSQL as MsSQL, Elasticsearch as ElasticSearch. We need to ensure that correct capitalization is used for each product/technology name mentioned on our docs or the Appsmith platform. 

![image](https://user-images.githubusercontent.com/800578/152294703-807120f1-b618-4753-a95d-78509110675f.png)

### Describe the improvement

Identify all incorrect capitalization and update docs and Appsmith platform.  Also, update the internal stylesheet document https://www.notion.so/appsmith/Stylesheet-e322bda33eef400983dbd131e1c8c0ee

**Comment by sharat87** [comment]
I think this still needs to be fixed in the docs, so reopening.

**Comment by jnikhila** [comment]
@danciaclara - This ticket will span across many sprints. We can keep making changes based on the doc we'll pick for Rehaul. Once the Rehaul Phase 2 is completed, we can revisit the ticket to test if anything is missed. Your thoughts??
