### ISSUE TITLE
[Bug]: Evaluation failed for rating widget's Tooltips property

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#10841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2022-02-02 at 9 48 20 PM](https://user-images.githubusercontent.com/13262095/152195893-5b2b8446-4f5b-4ac7-bbdb-2fdadfced5a7.png)

### Steps To Reproduce

Please fork this application (`populate list from query` page)
https://app.appsmith.com/applications/61fa19d411f4c46e3dfd2250/pages/61fa19d411f4c46e3dfd2253
### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@pranavkanade did not understand which app to fork, can you help? I cannot reproduce this issue

**Comment by pranavkanade** [comment]
@dilippitchika sorry my bad. Added the link.

**Comment by dilippitchika** [comment]
Thanks for identifying this @pranavkanade.  

This is also an issue related to list widget. It's only failing when the rating widget is inside a list.

**Comment by Tooluloope** [comment]
Closing in favour of https://github.com/appsmithorg/appsmith/issues/13211

**Comment by ashit-rath** [comment]
Already fixed in #15839
