### ISSUE TITLE
[Feature]-[600]:Rename S3 datasource name/icon to something more generic

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#10849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

S3 and corresponding icon in the Datasources section should be renamed to something more generic name/icon 
![image](https://user-images.githubusercontent.com/800578/152295961-74f4657b-77a0-4f33-995a-ed29176c2f03.png)

![image](https://user-images.githubusercontent.com/800578/152295975-40a12d9d-af45-4fe0-992e-85e36577db04.png)

### Describe the improvement

We should rename S3 and corresponding icon to something more generic name/icon as we support more than Amazon S3 under this datasource.

**Comment by areyabhishek** [comment]
@parth-appsmith Check this out. Could you find a generic S3 logo that we could use here? This is a quick fix

**Comment by parth-appsmith** [comment]
@areyabhishek upon research, the most common logo used for S3 is I have found is this(attached). As per what I have understood S3 is a file storage protocol developed by amazon, even though other cloud service providers are providing S3 storage but the most recoginisable icon for S3 still remains the amazon one.
We can try a custom variation of it but the whole purpose of an icon is to provide quick recollection of what it stands for in a glance which I still believe the current logo does.

If anyone has any other information on this that can help, please do share.

![image.png](https://images.zenhubusercontent.com/616e6ca5bc03b81db0d9e2a0/65945a12-79d1-49fb-8b22-27202d7621e3)

**Comment by rohan-arthur** [comment]
s3 6m usage: 148, but doubling this since I cannot reduce the effort further
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 0.25 |

**Comment by Irongade** [comment]
We are closing this issue since we are going for the same icon for now.
