### ISSUE TITLE
[Bug]: The 2 scrolls are displayed inside the git connection modal

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The 2 scrolls are displayed inside the git connection modal
![image](https://user-images.githubusercontent.com/45958978/152286543-d10eb833-9623-4146-af0b-d295e5eb5e7b.png)

### Steps To Reproduce

1. Open firefox browser
2. Try to connect any of the application to git 
3. Dont copy key to repo 
4. Now click on connect button 
5. the error is displayed try to scroll 
6. The 2 scrolls are displayed

### Environment

Release

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
@RakshaKShetty DP: https://appsmith-5t8qvpv7n-get-appsmith.vercel.app/ Please test
