### ISSUE TITLE
[Task]: Stop unnecessary uncaught promise errors to sentry

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#10865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We don't need all of these errors to be logged into sentry, they are mostly user errors.

https://sentry.io/organizations/appsmith/issues/2877416816/events/?environment=Production&project=1546547&statsPeriod=14d

**Comment by bharath31** [comment]
@Rishabh-Rathod @satbir121 could we prioritize this and fix it in the current sprint? I'm guessing the fix should be simple. Our Sentry quotas are being breached and we're missing out on the actual platform errors.

**Comment by bharath31** [comment]
Related: #16618

**Comment by bharath31** [comment]
@arunvjn would #19515 fix this?

**Comment by arunvjn** [comment]
Yes @bharath31. Closing this ticket
