### ISSUE TITLE
[Feature]: Allow dynamic string arrays in multipart

### ISSUE THREAD

**Issue by noe-charmet** [appsmithorg/appsmith#10876]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

APIs using multipart would commonly expect list of values to be sent as unique values using the same key;

```
// My source data could be an output of a Select for example with value ['a', 'b', 'c']

// In JSON we would have something like this
{
  myList: ['a', 'b', 'c']
}

// In multipart the request might look like this
--12345
Content-Disposition: form-data; name="myList"

a
--12345
Content-Disposition: form-data; name="myList"

b
--12345
Content-Disposition: form-data; name="myList"

c
--12345
```

Currently it is not possible to map an array value in such a way in appsmith

### Why should this be worked on?

APIs expecting requests using this format can not be achieved, unless there is a fixed and contact length array to send.

**Comment by danieldare** [comment]
Hi @noe-charmet, Just to Mention, we are currently working on the issue.
