### ISSUE TITLE
[Bug]: this.params shows undefined in evaluated value

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#10878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When referencing params in a query, it shows undefined in the evaluated value
This should show similar to the way we do prepared statements

### Steps To Reproduce

1. Create a query that reads this.params.key
2. View the evaluated value

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
autocomplete doesn't work as well. investigating this.

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 I suggest we solve this with the application level actions project

**Comment by mohammedahmed18** [comment]
Has there been any progress on this ?

**Comment by bharath31** [comment]
@mohammedahmed18 we don't have any updates here. Did you face an issue with this recently?
