### ISSUE TITLE
Performance analysis of git feature.

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#10880]

**Comment by abhvsn** [comment]
- Implement stopwatch to log execution time for APIs
- Update indexes in MongoDB as per the suggestions from execution time

**Comment by hiteshjoshi** [comment]
@abhvsn can we close this?

**Comment by abhvsn** [comment]
I'll close this once we have definitive numbers for existing API and function execution time, keeping this open until then
