### ISSUE TITLE
[Feature] Allow users to upload images to appsmith servers so they can be used in image widgets

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#1089]
## Description

The image widget does not support image uploading from computer and only accepts a URL.

## Ideal solution

There should be an option to upload single/multiple images. Along with ability to drag and drop to upload an image from file explore.

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign I believe the file picker does this. Image widgets are only to display uploaded images and hence only take a url or base64

**Comment by aakashDesign** [comment]
@Nikhil-Nandagopal My problem here is not with the file picker. I just want to display a couple of icons on my app canvas. The image widget is what I'd like to use.

My ideal flow -
1. Drop Image Widget to canvas.
2. Select an image from Desktop.
3. Image widget now displays my chosen PNG/JPG.

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign I think I understand now. This looks like it's more of a 
File upload into our own appsmith servers and using that file in the image widget
Taking this up as a feature request not a bug

**Comment by mohanarpit** [comment]
@all-contributors Please add @aakashDesign for their contributions to design

**Comment by mohanarpit** [comment]
@all-contributors Please add @Debsourabh for their contributions to design

**Comment by ginjojohny** [comment]
I really need this feature to be used in my application .  Is this available now ?

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny this is not available inside the platform. You can integrate Appsmith with S3 or Cloudinary to achieve this.

**Comment by DeanMann** [comment]
Please add this feature to access local image assets for information and in-house branding

**Comment by Nikhil-Nandagopal** [comment]
@DeanMann you can upload local assets using the file picker to S3 to achieve this.We won't support this because managing file storage is outside of the scope of our project
