### ISSUE TITLE
[EPIC]-[6800]:Improving CRUD Generation

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#10894]
Updating the current CRUD flow to incorporate the existing datasources, Incorporating JSON forms, and no longer relying on just the first 4 fields, and improving the design to make CRUD generation a complete experience

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 1|

**Comment by hiteshjoshi** [comment]
Closing this. As this is no more valid.
