### ISSUE TITLE
[Feature]: Support custom SSL certificates for deployments

### ISSUE THREAD

**Issue by arbfay** [appsmithorg/appsmith#10906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Support easily renewable, custom SSL certificates for an Appsmith deployment, instead of creating new ones from Let's Encrypt.

### Why should this be worked on?

Custom SSL certificates are necessary for deployments in Enterprise and high-security startups, where internal CAs are deployed and certificates renewed at various paces (10-years, daily, etc). Same for sandboxed/offline deployments.

**Comment by arbfay** [comment]
A workaround is to use a sidecar proxy (envoy, linkerd2-proxy, etc) and disable SSL for Appsmith. This is what we're doing.

**Comment by arbfay** [comment]
[There is this section in the repo that says it is possible to load custom certificates.](https://github.com/appsmithorg/appsmith/tree/release/deploy/docker#custom-ssl-certificate)
This is not in the [docs](https://docs.appsmith.com/security). Any reason?

**Comment by Nikhil-Nandagopal** [comment]
@arbfay you are right this seems to be a miss on our documentation. We'll add this there
