### ISSUE TITLE
[Docs]: Application Level actions example documentation

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#10902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- How to access app-level actions?
- How to pass arguments?
- What is the difference between page-level actions vs app-level actions?
- When to use app-level actions?
- How to convert a page-level action to app-level action?

**Comment by Rishabhkaul** [comment]
@jnikhila is this still required?

**Comment by jnikhila** [comment]
@Rishabh-Rathod - Could you please confirm what's needed as part of this ticket and add the first draft?

**Comment by Rishabh-Rathod** [comment]
@jnikhila We can close this task. It was created by me when the team picked `Application level actions` that were later moved again to the backlog.
