### ISSUE TITLE
Fix Slowness/Failure to load Integration API Actions on Saas Integration Manager.

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#10909]
## Current Behavior

The *API Manager* page takes more than 2 minutes to load its contents and most of the time the API Actions Table won't load it's contents.

This happens on the following environments:

- Chromium: Version 97.0.4692.71 (Official Build) built on Debian 11.2, running on Debian 11.2 (64-bit)
- Firefox: 91.5.0esr (64 bit) on Debian 11.2
- Chrome: 98.04758.81 (Official Build) (64-bit) on Windows 10

## Steps to Reproduce

1. Go to: https://app.appsmith.com/applications.
2. Click *Edit* on the *SaaS Integration Manager*.
3. Click on *View API* for the Twilio Integration
4. Wait up to 2 minutes for the whole page to load (this is the problematic behavior)
5. The page contents will load, but the *REST APIs* table won't load its contents unless you click on the **refresh** button and wait a little more.

![Video](https://images.zenhubusercontent.com/275993885/4312ede5-a2d0-44ab-a9ce-9c79eb8d07e6/api_actions_slowness.mp4)

## Environment

Production

## Version

Cloud

**Comment by felixsuarez0727** [comment]
Backend(Guess): Noticed on meetings that  when you guys use the SaaS Manager, it loads significantly faster. Even though using Chrome instead of FF helped, this feels like it's taking a while to get the resources from the server to the client.

**Comment by felixsuarez0727** [comment]
Noticed that on other computers the load time is faster. For this reason, the following test is proposed, in which the different times it takes to perform a process are compared to analyze how it behaves in different environments.

### Steps to reproduce the test 

1. Go to https://app.appsmith.com/applications
2. Start the chronometer and select edit in Saas Integration Manager
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/03e88511-2261-492e-b34f-bf7c1767b6cd)
3. Select the Twilio Integration (View API)
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/278a6c07-613d-4127-afac-2d46960a503b)
4.Update the table, select LIST_MESSAGE, and select Dynamic Variables.
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/bc3bfe0f-278d-4699-91de-2a0e77f65abb)
5. When Dynamic Variables finish, stop the chronometer.

### Results 
| ID Test | Browser | CPU         | RAM | Computer Model        | Time | Operating system | Internet Speed |
|---------|---------|-------------|-----|-----------------------|------|------------------|----------------|
| 1       | Chrome (Version 98.0.4758.80)  | Core™ i7-5500U  |8 GB | DELL Inspiron 15-5558 |38.39 s| Ubuntu 20.04.3          |      99.43 Mbps          |
|         |         |             |     |                       |      |                  |                |
|         |         |             |     |                       |      |                  |                |

**Comment by felixsuarez0727** [comment]
Overall, if the time it takes to complete these steps is around 30 - 40 seconds, then the experience is acceptable. But, if completing these steps takes more than 01:00 s, the feeling of slowness is affects the user experience.

Setting aside the fact that using a Chrome-based browser always provides better responsiveness than Firefox (by a significant margin), we could conclude that the performance of the SaaS Integrations app is within range if a computer with good specs (modern CPU) is used.

Since this is related to the SaaS Integration App, and it's clear that this is mostly related to client-side factors, I would advise to close this issue in favor of #8639 and all the other efforts to improve the [performance of Appsmith in general.](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+performance+label%3APerformance)

**Comment by prapullac** [comment]
Closing the issue as it is working as expected
