### ISSUE TITLE
Fix "Run" button randomly disables itself after changes on form are saved.

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#10910]
## Current Behavior

The "Run" button on the REST APIs form (the one used for testing), gets disable after saving changes with the "Save" button. In some cases, it won't come back unless the page is reloaded. 

**Note:** A workaround is to remove `{{Utils.isDirty()}}` from the *Disabled* input box of the button. This could be the solution, but the effects of this change need to be determined.

This happens on the following environments:

- Chromium: Version 97.0.4692.71 (Official Build) built on Debian 11.2, running on Debian 11.2 (64-bit)
- Firefox: 91.5.0esr (64 bit) on Debian 11.2
- Chrome: 98.04758.81 (Official Build) (64-bit) on Windows 10

## Steps to Reproduce

1. Go to a "REST APIs" form. 
2. Select any API "action". 
3. Edit the URL on the "URL & Params" tab. Inmediatly revert the change so that nothing changes. 
4. Click "Save". 
5. Observe how the "Run" button gets disabled.

![Video Run Button](https://images.zenhubusercontent.com/275993885/eb31382e-1f85-406d-9539-4d68ae7f3d0d/run_button.mp4)

## Environment

Production

## Version

Cloud

**Comment by felixsuarez0727** [comment]
I considered this is a front-end related issue.

**Comment by felixsuarez0727** [comment]
### Background

`Utils.isDirty()` is the way to tell if the object obtained from `ActionDao.getSaveRequest()` and the object generated from the current data on the table are different.

`Utils.isDirtty()` is used to disable the "Run" button so that it is not executed on an "inconsistent" state.

### The issue

The reason the "Run" button is getting disabled constantly is that `Utils.isDirty` is constantly evaluated as `true`.

A closer look to `Utils` shows that there are two functions to check if "is dirty":
- `Utils.isDirtyCheck()`
- `Utils.isDirty()`

They are the same on how the objects are created, but the method for comparing if the two objects are the same is different. `Utils.isDirtyCheck()` converts them to strings and compares the strings with `.localeCompare()`. `Utils.isDirty` compares the objects with `_.isEqual()` from [Underscore.js](https://underscorejs.org/#isEqual)

Even though `_.isEqual()` is usually the [best option](https://www.samanthaming.com/tidbits/33-how-to-compare-2-objects/), under manual inspection it seems that it is evaluating the 2 objects as not equals when they actually are.

(Here is diff of both objects when the form is loaded and nothing has been changed/saved. Ignore the first and last lines. They are the same, but being evaluated as different)

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/3738bf50-fbf3-40a5-a74c-841ee295de7b)

### Actions

(I made slight modifications to `Utils.isDirty` return values, so I could verify the _original_ and _newReq_ objects.)

For the moment, changing `Utils.isDirty` to `Utils.isDirtyCheck().isDirty` on the _Disabled_ control input for the _Run_ buttons seems to solve the issue. This is done to use string comparison method instead of `_.isEqual`).

Since `run_action` (the Run Button) doesn't actually change anything on the Integration definition, it should be safe to leave it as is, but comments from someone with more in-depth understanding of the SaaS Manager App are welcome.

**Comment by felixsuarez0727** [comment]
It has been suggested to reach out someone on the UI building pod... Possibly, someone with better understanding of the inner workings of the app to approve this action plan.

**Comment by felixsuarez0727** [comment]
The root cause of the issue seems to be related to the fact that at the time of constructing the `original` object, the changes on made on the UI and saved with the "Save" button are not picked up:

https://images.zenhubusercontent.com/275993885/19993189-58e0-435a-ab0a-961d87d5c568/is_dirty_no_ui_update.mp4

I will be working on identifying the reason why that happens, and to update the code to fix this.

**Comment by felixsuarez0727** [comment]
The root cause is that table selection does not update at a time and shows an old version of the path. When refreshing the page, it works. 

Solution: Update the table at the moment that saves the object, the button save does two actions, save the information and then refresh the table.

![imagen](https://user-images.githubusercontent.com/25110207/156205921-08d4f21b-4601-4058-acc2-949a41dfd17c.png)

![imagen](https://user-images.githubusercontent.com/25110207/156205707-8b58a851-fab4-42c2-bcd9-ba0201ae79ce.png)

**Comment by nidhi-nair** [comment]
Need to figure out a process for QA here.

**Comment by prapullac** [comment]
Closing the issue as it is working as expected
