### ISSUE TITLE
[Bug]-[5000]:Spelling error in step 7 of the tutorial

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spelling error in step 7 of the tutorial

![image](https://user-images.githubusercontent.com/92293815/152746908-1dcca45d-6d1d-4289-89e6-cfcc3c4642f2.png)

### Steps To Reproduce

1. Start the welcome tutorial
2. Proceed to Step 7 and read the description on the header .

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2500 |
| Effort (months)  | 0.25 |

**Comment by ramsaptami** [comment]
Can we also remove the word `this` on Step 1? It's a confusing wording there.

**Comment by shwetha-ramesh** [comment]
@akash-codemonk - @ramsaptami callout has not been fixed, hence re-opening this issue
