### ISSUE TITLE
[Bug]-[700]:Welcome tutorial ends on page refresh

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user is in the middle of the tutorial and the page gets refreshed the tutorial ends abruptly.

https://loom.com/share/1dd574b0442e4630a94b8747aafe1cfd

### Steps To Reproduce

1. Start the Welcome tutorial > Click on refresh on any step of the tutorial and observe 

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 350 |
| Effort (months)  | 1|

**Comment by akash-codemonk** [comment]
DP: https://appsmith-bgz4p9900-get-appsmith.vercel.app/. 
Note that we don't restore at the initial screen where we show the start building cta. Also we don't restore all states like if the widget sidebar was open we don't reopen it on refresh, but the onboarding continues to be usable. We also go back a few steps in cases where we cannot resume with the latest step.

@Richarex @ramsaptami Could you please help with verifying the deploy preview

**Comment by Richarex** [comment]
@akash-codemonk Not able to verify the issue getting "Google recaptcha verification failed. Please try again" error.

**Comment by Richarex** [comment]
This is fixed, verified it on the DP url provided.

**Comment by Richarex** [comment]
This is fixed, verified it on release env.
