### ISSUE TITLE
[Feature] Dynamically control page visibility

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1092]
## User stories:
1. Users implementing login via their own APIs need to hide pages that aren't accessible till the login is complete
2. Users want to conditionally hide pages that are not relevant to certain user ids or user groups

## Designs required:
1. Way to access page properties: Order of pages, mark certain pages as 'Homepage', control visibility of pages
2. Property window to modify the page properties
3. Way to reorder/ set home page/ clone/ delete and conditional visibility controlled via JS.

**Comment by areyabhishek** [comment]
@hetunandu @Nikhil-Nandagopal @Debsourabh could you look at the feature spec? What else do we need here?

**Comment by Nikhil-Nandagopal** [comment]
Another property that just came up is the slug name of the page in the URL when we have clean URLs.
So properties I can see are

- Page Name
- URL slugname
- Visibility
- Page Order

**Comment by areyabhishek** [comment]
Should we just show the current slug name but disable editing it till we can create clean URLs? For now, we'll show the current URL, and later we'll show the ability to edit it.

**Comment by Nikhil-Nandagopal** [comment]
Yes, we can even not show it. I just wanted to add an exhaustive list so we can think about the future design

**Comment by Debsourabh** [comment]
To have page properties clubbed under one place, I think this is the best approach for 2 reasons:

1. This is consistent with other property windows that we have.
2. Lean learning curve and everything under one roof. 

The property window will appear when they click on the 3 dots and we show the menu. The menu can take care of all the above-mentioned properties. For reorder, the best experience is to drag and drop within the Entity Explorer. I do not see the need to have an option for the reordering page. 
![CaptureA](https://user-images.githubusercontent.com/34486435/101600385-399f3900-3a21-11eb-88ee-90f3f8d4c07f.PNG)

The property pane for the pages will behave in the exact same fashion as it does today for any widget. 
![CaptureB](https://user-images.githubusercontent.com/34486435/101600396-3c9a2980-3a21-11eb-9629-d2cf6dddba1e.PNG)

A couple of pointers:

1. If you have set something as a homepage we cannot drag and drop that. It will always appear on the top. If there are 4 pages and the first one is the homepage, the user can only reorder 3 pages. 
2. In this flow we do not need to open any additional menu to accommodate the above-mentioned properties.
3. As compared to the previous page menu UX, this does not look like a long list. 
4. Page rename will work the same way as widget rename.

**Comment by mohanarpit** [comment]
@Debsourabh What happens to the overflow menus for other entities like Action, Query, Datasource etc. Will they also transform into this UI? I'm asking because ideally, we'd like to be consistent in our approach across the board.

**Comment by Debsourabh** [comment]
> @Debsourabh What happens to the overflow menus for other entities like Action, Query, Datasource etc. Will they also transform into this UI? I'm asking because ideally, we'd like to be consistent in our approach across the board.

Yes. Ideally, we should move to this format as these are properties of respective elements.

**Comment by Nikhil-Nandagopal** [comment]
@Debsourabh If the approach is this type of property pane, then why not treat the page as a top-level widget which shows the property pane? i.e if you click the page, it selects the entire canvas and shows the property pane. That seems more consistent with the mental model than this.

**Comment by Debsourabh** [comment]
Does this approach work? In this case, we have independent 3 dots for the actions and then the property for the page. This way we do not break the mental modal and at the same time get some more real estate to work with in the future. 

![CaptureA](https://user-images.githubusercontent.com/34486435/101781312-a4359f00-3b1d-11eb-91b1-f0afc2ebd0b7.PNG)
![CaptureB](https://user-images.githubusercontent.com/34486435/101781318-a566cc00-3b1d-11eb-9cd3-79e93c9e14e0.PNG)

**Comment by areyabhishek** [comment]
Some comments:
1. How will you control properties of all the pages together?
2. How will reordering of pages happen?
3. Please give a way to access all page controls from the entity explorer itself. Either in the overflow menu.

I like the idea of a consistent flow, but how the property pane opens today for widgets won't work well. It'll need to be modified to open for a page.

This is how you open a property pane for a widget today:
1. Click on the entity to select the widget
2. Click on the tiny button at the top to open the property pane

Both of these applied to pages:
1. Clicking a page to select and open its properties mean that property pane of a page cannot be opened without navigating to the page (a user could be trying to change properties of all pages from a single page)
2. I have to now click the chevron/unfurl icon on the left to open the page's widgets because the main action opens the property pane
3. If I'm already in the page, then I have scroll to the top to open the property pane

Some solutions:
1. Have an additional ⚙️ icon in the page names in entity explorer that can be clicked to open the properties of a page
2. Every page can have properties, but there should be a global set of properties for the entire set of pages. This could be similar to global table properties-->column properties

**Comment by Debsourabh** [comment]
> Some comments:
> 
> 1. How will you control properties of all the pages together?
> 2. How will reordering of pages happen?
> 3. Please give a way to access all page controls from the entity explorer itself. Either in the overflow menu or an icon beside the entity name.
> 
> I like the idea of a consistent flow, but how the property pane opens today for widgets won't work well. It'll need to be modified to open for a page.
> 
> This is how you open a property pane for a widget today:
> 
> 1. Click on the entity to select the widget
> 2. Click on the tiny button at the top to open the property pane
> 
> Both of these applied to pages:
> 
> 1. Clicking a page to select and open its properties mean that property pane of a page cannot be opened without navigating to the page (a user could be trying to change properties of all pages from a single page)
> 2. I have to now click the chevron/unfurl icon on the left to open the page's widgets because the main action opens the property pane
> 3. If I'm already in the page, then I have scroll to the top to open the property pane
> 
> Some solutions:
> 
> 1. Have an additional ⚙️ icon in the page names in entity explorer that can be clicked to open the properties of a page
> 2. Every page can have properties, but there should be a global set of properties for the entire set of pages. This could be similar to global table properties-->column properties

**Comment by Debsourabh** [comment]
There are 3 options under the link. Each with its owns pros and cons.

https://www.figma.com/file/NJB6wtUsWfYKIKICXKwWzY/?node-id=44%3A2

**Comment by Debsourabh** [comment]
Post our conversation around this I have updated the designs here.

https://www.figma.com/file/NJB6wtUsWfYKIKICXKwWzY/?node-id=77%3A1587

**Comment by riodeuno** [comment]
Related issue #2244

**Comment by riodeuno** [comment]
Notes in #2786

**Comment by dncpax** [comment]
Just trying to get attention to this issue. After watching the video on custom authetication where tabs are hidden/shown according to authentication success, I was under the impression we could the same with pages... but not so.
Page visibility does not support binding, AND we cannot set Page visibility from other pages... so I think this is a dead end...
Is there a workaround? How to not show pages until after authentication happens?

**Comment by Nikhil-Nandagopal** [comment]
@dncpax we're working on this as part of #3317 because we realize that simply hiding the page is not enough for security, we need to restrict access to this page. 
To work around this today, you can mark the login page as hidden and set it to home. This will hide all other pages when the user is on the login page

**Comment by dncpax** [comment]
Hi @Nikhil-Nandagopal thanks for the workaround - I will look into it.
I don't think most users will need the full granular access control. But some measure of control would be nice. I agree that hiding is not really that secure, but it's something we can live with if we couple that with hiding controls and binding queries to a store value (authenticated=true/false).
I have been playing around with redirecting to an external page when authentication is not appropriate for the app.

**Comment by slysiou** [comment]
Hi, sorry to push on this old request. I am using external authentication and tabs on each page like the example on Youtube. 
But, managing visibility of a page based on JS would be great, to avoid the tab asking to go back to login.

**Comment by nvcnvn** [comment]
I think this should be separated from the RBAC issue but more about components visibility level.

For example, many components visibility can be controlled by JavaScript, this "menu component" should have it also.

**Comment by spikecodes** [comment]
Any update on this?
