### ISSUE TITLE
[Bug]: Unable to download file from image widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding a url to image widget is displaying the image but downloading the same file is not working on release

![image](https://user-images.githubusercontent.com/95341241/152761134-7f9fc95f-06fe-48f6-b970-43c050cb9558.png)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0b425dd8c9bf43458e0d5cfa3b0fe443-00001.gif)](https://www.loom.com/share/0b425dd8c9bf43458e0d5cfa3b0fe443)

### Steps To Reproduce

1. Add image widget
2. Add image url to the widget to dispaly the same image
3. Enable download option
4. Try downloading the image

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
@Tooluloope can you get this triaged? Has the image download ever worked for base64 addresses?

**Comment by Tooluloope** [comment]
@chandannkumar This is related to this other issue https://github.com/appsmithorg/appsmith/issues/10753
@techbhavin would this https://github.com/appsmithorg/appsmith/pull/11391 solve both.
Also @chandannkumar Could you try reproducing the issue using the deploy link on the PR.


Adding @sharat87 due to the CSP issue I'm seeing in the screenshot

**Comment by sharat87** [comment]
Same problem with CSP as I've detailed here: https://github.com/appsmithorg/appsmith/issues/10753#issuecomment-1042922605. Briefly, I don't think this should be solved in CSP, but in the implementation of the download button.

**Comment by techbhavin** [comment]
yes , this issue is covered  by  PR #11391

**Comment by shwetha-ramesh** [comment]
@somangshu @techbhavin : tested this on release and there are two observations that are made. So when user gives a image URL on the image widget and click on "enable download" and downloads the file, few set of files gets downloaded in the same tab and few images gets redirected to a different tab (there is no download). What would be the ideal behavior ? (pls refer loom video)

cc: @chandannkumar @vivekverma2312 
https://loom.com/share/718828a016d747baad2459db0fd23d61

**Comment by somangshu** [comment]
@shwetha-ramesh this is by choice, we are aware of the situation, the images sometime through header choose to deny the access control, and hence we can only open it in a new tab for the user to force save through browser controls.
