### ISSUE TITLE
[Bug]: Header tags are not styled correctly in the Text widget

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#10936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use header tags like `h1`, `h2`, etc. inside the Text widget, these used to get the standard header styling applied to them in the past. But now, text inside these tags look like normal text. The problem seems to be that Tailwind resets the styles for these tags with the following CSS:

```css
h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
}
```

But then that kinda hints that perhaps, Tailwind styles could be used for styling my text, so if I try `<h1 class="text-6xl">Header</h1>`, that still doesn't show large text, it's still body sized.

### Steps To Reproduce

Drop a new text widget and use the following as the text:

```html
<h1>Header here</h1>
<p>Paragraph text here.</p>
```

Notice that the header and the paragraph have the same font size and look the same.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika @somangshu how did this break?

**Comment by somangshu** [comment]
Apparently with the use of tailwind @Nikhil-Nandagopal. All tags have font-size inherit

Cc @jsartisan
