### ISSUE TITLE
[Bug]: Creating an action after binding to a widget still show action as not available

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#10939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I bind a button to an action that doesn’t exist, I get an error saying the action doesn’t exist. But when I go create that action and come back, the error is still there.

https://user-images.githubusercontent.com/120119/152792143-d77cfd9c-ca05-4fcd-a48b-8aaf936afc33.mov

### Steps To Reproduce

Drop a button widget and set the onClick to `{{missingAction.run()}}`.

Then go create an action and name it `missingAction`.

Now go back to the button widget's properties and see that the error `missingAction is not available` is still there.

### Environment

Production

### Version

Cloud

**Comment by eco-monk** [comment]
Will be handled here #11943
