### ISSUE TITLE
[Bug]: The deploy functionality is not working in slim container for large dataset

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The deploy functionality is not working in a slim container for large dataset
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7d34cf3185ec43beb164da29cc1e8dc8-00001.gif)](https://www.loom.com/share/7d34cf3185ec43beb164da29cc1e8dc8)

### Steps To Reproduce

1. In the local instance 
2. Add the Google sheet with the huge data 
3.  Now generate the page  for the google sheet 
4. Try to deploy
5. the deploy button loads for  quite a lot of time after that the loading stops but the application is not displayed in the view mode

### Environment

Release

### Version

Self-Hosted

**Comment by yatinappsmith** [comment]
slow response from query causes chrome to block popups. Hence apps was not accessible in view mode

**Comment by yatinappsmith** [comment]
added app as attachment

**Comment by leotom2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BE-Coders-Pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/10934?planning-poker) with ZenHub @nidhi-nair @sumitsum

**Comment by nidhi-nair** [comment]
Seems related to #4387

**Comment by leotom2000** [comment]
When large data are fetched first and then tried to deployed.
Seems both Front-end and back-end issue, the deploy button is not sending request immediately on clicking,
Also the backend is taking considerable time to give response, will check with front end first and go ahead for backend, 
assigning to Frontend Team
