### ISSUE TITLE
[Task] evaluate only sub trees in the datatree

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1094]
# Logic to optimize evaluation of the data tree
The premise of this is that our data tree evaluation takes a long time because we re-evaluate every dynamic binding and property on every update. Here we will discuss how to optimize this to evaluate only the properties that have changed and their dependencies.
There are 2 large functions that are called on every update
- createDependencyTree
- evaluateDataTree

## Triggering the functions
To find which of these function should be called, we have 2 choices
- Flag certain actions to only trigger createDependencyTree  and some to trigger evaluateDataTree
- Interpret the diffs of the old dataTree with the new dataTree and triggering the functions based on what has changed

### Interpret the diff
This is the preferred approach because it is more generic and does not hinge on new actions registering the trigger
We can make use of this library https://github.com/flitbit/diff#readme for diffing which outputs a list of propertyPaths that have changed in this evaluation cycle. Ex. ["Table1.selected.row", "getUsers.data"]
A helper function will prune the property paths that do not affect evaluation Ex. size, pos, isFocused, etc.
The remaining property paths need to be checked for whether any of their bindings have changed. 
If their bindings changed, 
    - call updateDependencyTree with the propertyPaths whose bindings changed and wait for the update
    - call evaluatePropertyPaths with all propertyPaths that have bindings changed and values changed
else 
    - call evaluatePropertyPaths

**A dependency changed if a binding {{ }} was Added / Deleted / Edited in an entity in edit mode.**
*Actions binding updates are also considered in the dependency graph because the evaluated values of the actions need to be displayed*

### updateDependencyTree
Taking each property path that changed, we find the 
- list of paths that this property was dependent on before and delete the dependency graph connection to them
- list of paths that this property is dependent on now and add them to the dependency graph
**We need to make updating the DAG Fast with map lookups instead of array lookups**

### evaluatePropertyPaths
Evaluate each property path and the paths dependent on it
*Assumption: It doesn't matter what order you evaluate the property paths that changed because they will always be disjoint*

**Comment by Nikhil-Nandagopal** [comment]
## Improvement
Save dependency tree on the server to avoid first time eval

**Comment by trishaanand** [comment]
Considering that DSL is converted into dependency tree, we should get rid of DSL completely and store dependency trees instead. Other than evaluated values, are other details stored in the dependency tree? Or do you have another data structure that is responsible of storing the static properties of the widgets?

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand the DSL is different from a dependency tree. A DSL is a HTML like structure which contains information around the layout and the properties of every widget. The dependency tree is a graph implemented as an array of edges which tells us that the table's selected row property depends on the getUsers data property [Table1.selectedRow, getUsers.data] 
evaluated values are not stored in the dependency tree. it's only a slim relationship map.

**Comment by hetunandu** [comment]
- [ ] Refactor change listener to be diff based instead of event based
- [ ] Refactor Dependency calculation with sub tree optimisations
- [ ] Refactor Evaluation calculation with sub tree optimisations
