### ISSUE TITLE
[Bug]-[200]:On selecting a widget in explorer pane, the canvas doesn't auto-scroll to the widget selected.

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i have a lot of widgets in my canvas and the canvas is scrollable, I am unable to reach the widget i selected using the explorer pane automatically. This worked in the older version of the explorer pane.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0e987d5dc0fb48a1a50f1456341c6215-00001.gif)](https://www.loom.com/share/0e987d5dc0fb48a1a50f1456341c6215)

### Steps To Reproduce

1. Add multiple widgets
2. Make sure that at least one widget is not in the window area but can be reached via scroll
3. Click on the widget which is not in the window from the explorer pane
4. Observe that the canvas doesn't auto-scroll to that point

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4000 |
| Effort (months)  | 1|

**Comment by arunvjn** [comment]
@dilippitchika Unable to replicate this in v1.7. Is there an app I could look at where this is breaking ?

**Comment by dilippitchika** [comment]
Looks fixed now, closing this
