### ISSUE TITLE
[Bug]: Input widget `onSubmit` ends up triggering `onTextChange`

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#10944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an input widget has onSubmit and onTextChange configured, on pressing enter, both events gets triggered.get

### Steps To Reproduce

1. Add an input widget.
2. Add {{showAlert("onSubmit")}} to onSubmit event.
3. Add {{showAlert("onTextChange")}} to onTextChange event.
4. Type something on the input and press enter. 
5. Observe that onSubmit gets triggered followed by onTextChange.

### Environment

Production

### Version

Cloud

**Comment by sbalaji1192** [comment]
CC @dilippitchika @somangshu

**Comment by dilippitchika** [comment]
Starting the discussion here, after on Submit is clicked we should not allow on Text change to be triggered. This need not be a migration, to prevent users whose apps are built using this to break.
