### ISSUE TITLE
[Bug]: Links in comment's notification email don't work

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#10968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Example of the link received by a user: link received : https://app.appsmith.com/applications/app_id/pages/null/edit?commentThreadId=thread_id&isCommentMode=true 
there is a "null" value in the url that's probably causing the issue

### Steps To Reproduce

Tag someone in a comment to create a notification.

### Environment

Production

### Version

Cloud

**Comment by Rishabhkaul** [comment]
@Nikhil-Nandagopal wondering incase this can be closed since real time commenting is deprecated.
