### ISSUE TITLE
[Enhancement] : Checkbox widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10975]
https://www.notion.so/appsmith/Checkbox-b8a235faf3b74fa2aff59f68cafc0c05

**Comment by vivekverma2312** [comment]
@jsartisan  Label are not aligned in checkbox when we change the text size.

<img width="382" alt="Screenshot 2022-07-29 at 11 39 30 AM" src="https://user-images.githubusercontent.com/83569920/181694403-688a7ddc-fe4b-4311-9569-b11bf04e573e.png">

**Comment by dilippitchika** [comment]
@vivekverma2312 unfortunately this is a known issue which we are unable to fix as part of reskinning as this needs a change in properties. However, the checkbox moving out of bounds looks like an issue

**Comment by vivekverma2312** [comment]
Thanks for the update @dilippitchika . So the checkbox going out of bound need to be fixed in this PR or shall I raise a separate issue for that?

**Comment by dilippitchika** [comment]
You can create a separate issue for it @vivekverma2312
