### ISSUE TITLE
[Enhancement] : Chart widget reskinned

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10974]
https://www.notion.so/appsmith/Chart-aac49a84bc5a41248dacaed65d7cf6b9

**Comment by dilippitchika** [comment]
Hey @jsartisan @keyurparalkar I need one of you to assess if the changes suggested for reskinning chart widget are possible or not. 

Mainly 2 things which I want to be checked
1. There's a divider in the between chart and the heading.
2. Chart dimensions - I always see an extra space towards the bottom in our current chart widget. The proposed value is different. 

Please assess and let me know.

**Comment by keyurparalkar** [comment]
@dilippitchika The extra space towards the bottom of the is adjustable: It will look something like this:
