### ISSUE TITLE
[Enhancement]: Switch reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10987]
https://www.notion.so/appsmith/Switch-51f47213ed53455eb4fe035b64b5dc0b

**Comment by somangshu** [comment]
Could the left-padding of the switch itself in the switch widget be increased to match the switch group? They do not align when stacked, even though the widgets have the same width and horizontal position.

![Screen Shot 2022-03-24 at 2 49 30 PM](https://user-images.githubusercontent.com/11089579/160374846-f7d3fe6f-5e52-48a7-93a5-51bb9c1f83db.png)
