### ISSUE TITLE
[Type]-[497]:Select reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10988]
https://www.notion.so/appsmith/Select-2e17fe3eface46c49111170f623deb90

**Comment by jsartisan** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 497 |
| Effort (months)  | 0.5 |

**Comment by jsartisan** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 497 |
| Effort (months)  | 0.5 |

**Comment by laveena-en** [comment]
Tested and verified.
