### ISSUE TITLE
[Enhancement]: Radio group reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10985]
https://www.notion.so/appsmith/Radio-group-a82e799a8e254bf9a2ed16704c484d1b

**Comment by chandannkumar** [comment]
Alignment of options is not proper on Radio group widget when Inline property is enabled

![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/0a04fb83-3ff8-462e-95f6-3ad1c16264f7)
