### ISSUE TITLE
[Enhancement]: Rating widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10983]
https://www.notion.so/appsmith/Rating-6b06cb1357a6417296d90295abf9d584

**Comment by aswathkk** [comment]
<img width="321" alt="Screenshot 2022-03-03 at 7 35 22 PM" src="https://user-images.githubusercontent.com/10436935/156580380-0ce3d945-ddf2-4b62-99f6-4acef351be83.png">
A scrollbar at the end of the rating widget creates a thick white line. If we increase the height this goes away. Need to fix this either by increasing the default height of the widget or by removing the scrollbar itself.

**Comment by dilippitchika** [comment]
Thanks for adding this Aswath
