### ISSUE TITLE
[Enhancement]: Table widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10995]
Fix all CSS related issues in the current table widget

**Comment by chandannkumar** [comment]
Observation: @jsartisan 
- On clicking the pagination arrow of Table data's last page, the data seems redirected to the 1st page of the record even though the arrow icon is disabled.
video: https://www.loom.com/share/c0141141d13c4b6ba24d26d038452e48

**Comment by chandannkumar** [comment]
Tested and verified
