### ISSUE TITLE
[Enhancement]: List widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10999]
https://www.notion.so/appsmith/List-4ef5910007254260b3fdb7c92b79594f

**Comment by vasanth-appsmith** [comment]
I am working on this widget for re-skinning. The estimated completion date is the 17th.
[FIGMA](https://www.figma.com/file/1aTQ6vksqqAMtgB243PtHm/UI-%7C-Widget-Style-Updates-0.1?node-id=4474%3A71230)

**Comment by chandannkumar** [comment]
Tested this and LGTM

**Comment by laveena-en** [comment]
@jsartisan Raised an issue wrt list widget reskinning here: #17253
