### ISSUE TITLE
[Bug]-[20488]:Maintain context in the UI editor when I switch between pages

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#11009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when I switch between pages: UI, API pane, DB query & back to UI, the state of the UI is lost. It loads the default state of the page. I have to select the particular widget & the specific property I was editing in order to make changes. Not sure how big a change this will be in the code, but it's a small UX change that would improve my dev UX by a lot.

### Steps To Reproduce

1. Open the UI editor
2. Drag a widget & start editing any property
2. Navigate to the API pane
3. Navigate back to the UI editor

See that the cursor doesn't focus on the widget & property any more. 

### Environment

Production

### Version

Cloud

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5122 |
| Effort (months)  | 0.5 |

Estimating the effort for this as 2 person-weeks. We can update this when we calibrate with the devs.
