### ISSUE TITLE
[Bug]: The from email id is displayed wrong in the commenting emails

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The wrong email id is displayed when user 1 tag user 2 and add a comment in the comment section
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/153132435-f51d5194-b62a-436b-a95d-b6f7f72eabea.png">

### Steps To Reproduce

1. Go to commenting feature
2. Tag Raksha@appsmith.com and add a new comment
3. Now when the user Raksha receives a email the receiver email is displayed as "hello@appsmith.com" instead of user email id

### Environment

Production

### Version

Cloud

**Comment by RakshaKShetty** [comment]
reopening the issue still facing same issue 
![image](https://user-images.githubusercontent.com/45958978/162890220-8d641edf-0e8e-4c48-8b9f-e1a7076cb173.png)

**Comment by vuiets** [comment]
@RakshaKShetty what @nayan-rafiq mentioned here is the right. It's okay for an email to go from hello@appsmith.com. As a product, we are notifying the one who receives the message. The latter part should be checked though, that is when you reply to a message notification email it should add the owner of the message in the 'To' field.

Going forward when we provide whitlabeling of Appsmith as a feature, we'll allow users to enter a custom email address for the 'From' address field.

Closing this for now as the current flow is correct.
