### ISSUE TITLE
[Enhancement] : Phone input widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11023]
https://www.notion.so/appsmith/Phone-input-96ac4aa08ee04198a4a610524d0860ea

**Comment by dilippitchika** [comment]
Phone widget missing items: Same as currency missing items - copy pasting for now

- No phone country found state missing
- Is the width of the country search popup fixed?
- What happens when the length of a country extends the width. How does the wrapping work?
- Designs do not show scroll bar in the dropdown, please add scroll

**Comment by chandannkumar** [comment]
Found issues are reported on Currency Input widget Enhancement
#11026

**Comment by chandannkumar** [comment]
LGTM
