### ISSUE TITLE
[Enhancement] : Switch group widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11022]
https://www.notion.so/appsmith/Switch-group-39b21f09ed2042e5955194d42b46866a

**Comment by chandannkumar** [comment]
The gap between Label and Options keeps increasing on increasing the size of switch group widget vertically when Inline property is enabled.

![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/b0f72baa-5c02-4b8c-be30-95e76066802a)
