### ISSUE TITLE
[Enhancement] : Video widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11021]
https://www.notion.so/appsmith/Video-d617e6f7ba3548dcbb386f0d51527da4

**Comment by dhruvikn** [comment]
@dilippitchika, YouTube maintains the aspect ratio of the video no matter the size of the container by adding a black background. Our video widget on the other hand has a background property, but it is set to transparent/none by default. Adding a black background color by default solves the border-radius issue, just like YouTube. Shall we move ahead in this direction?

<img width="764" alt="CleanShot 2022-10-06 at 16 34 27@2x" src="https://user-images.githubusercontent.com/22471214/194297880-46f47366-dee3-424d-ba5c-9502d9a0f0ce.png">

**Comment by dilippitchika** [comment]
Hey @dhruvikn yes we can proceed in this direction
