### ISSUE TITLE
[Enhancement] : Currency input widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11026]
Scope - https://www.notion.so/appsmith/Currency-widget-03bf484b3e474058aad34d6da4a0dac3

**Comment by dilippitchika** [comment]
Currency widget missing items:
1. No currency found state missing
2. Is the width of the currency search popup fixed?
3. What happens when the length of a currency with country extends the width. How does the wrapping work?
4. Designs do not show scroll bar in the dropdown, please add scroll

**Comment by chandannkumar** [comment]
Observations:
1. Search icon is overlapped with 'x' icon on the search bar of dropdown. Also the 'x' is unclickable
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/4a0cfe75-649c-440e-98ec-416dadfbbd27)

2. When we add Currency widget somewhere at the bottom of the canvas, Clicking to open dropdown it jumps to the top area of the canvas on edit and preview mode
https://www.loom.com/share/c8c3f4bdc7eb4472b6913de177bcf3f9

3. There is a slight cut of the Label when 'Label Font Style' is selected as **Italic** (Issue is present on prod as well)
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/b9da468a-cb20-4437-97af-ec564336748c)

Note: The issue reported above are also similar in Phone Input widget as well
@jsartisan

**Comment by jsartisan** [comment]
@laveena-en @vivekverma2312 since chandon is OOO, can someone else pick this up?

**Comment by chandannkumar** [comment]
@jsartisan I am available and I will continue testing this

**Comment by chandannkumar** [comment]
On the above [callouts ](https://github.com/appsmithorg/appsmith/issues/11026#issuecomment-1205030906) point 2 will get fixed later

**Comment by chandannkumar** [comment]
LGTM
Moving this to Done
