### ISSUE TITLE
[Bug]-[1191]:Scroll is not working on swapping columns position when some of the column focus are out of the viewport

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#11035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that on the table property pane when some of the columns are outside of viewport and upon try to swap the columns below/top the scroll does not work 

https://loom.com/share/80abebc67fa744c4825e47cc2332ebf0

### Steps To Reproduce

1. Launch appsmith app in release environment 
2. Drag and drop table widget 
3.  Open property pane 
4. Add a few more columns 
5. Keep the table property focus where few columns can be visible and few outside the viewport 
6. Try to swap/ repositioning the column from top to bottom and observe the scroll is not functional 

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
I think there's already an issue for this. Let me see if I can find it.

**Comment by sbalaji1192** [comment]
## Stats
Calculated the reach by looking at users who have updated the columnOrder in the Table widget.
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1191 |
| Effort (months)  | 0.5 |

**Comment by carinanfonseca** [comment]
I am closing this issue because it is not reproducible in production right now.
