### ISSUE TITLE
[Docs]: add documentation for REST APIs

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#11045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

We don't have documentation for REST APIs. 

### Describe the improvement

Please provide documentation for REST APIs on a Notion/Google doc and mention in which section it needs to be added. @Pranay105 or docs team can take it from there.

**Comment by nidhi-nair** [comment]
Added a draft here: https://www.notion.so/appsmith/REST-API-b078f8f884e64567aec19353831556af

cc: @ajinkyakulkarni
