### ISSUE TITLE
[Type]-[18352]:All the Property pane controls re-renders when we press js toggle

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#11040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Rishabh-Rathod** [comment]
<img width="862" alt="Screenshot 2022-04-15 at 1 43 37 AM" src="https://user-images.githubusercontent.com/23132741/163468354-f283e65b-c034-4835-99b4-111724da483a.png">

Event - Just click on an Input widget on canvas. I see that here we have a huge performance gain opportunity.   

@aswathkk @SatishGandham  

Are we working on this?

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2485 |
| Effort (months)  | 0.5 |

**Comment by aswathkk** [comment]
I'm thinking of taking up this issue this quarter.

**Comment by somangshu** [comment]
@aswathkk can idea right now when this can be picked up?

**Comment by aswathkk** [comment]
@somangshu I will pick it up after 2 weeks
