### ISSUE TITLE
[Bug]: `rootActionConfig.editor.options` not being populated by API Manager

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#11055]
Even though the API Actions are successfully recorded, the `rootActionConfig.editor.options` array was not populated with the label/value pairs.

This causes that the plugins (like Twilio) can't be tested by QA.

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/e8712900-45d9-440a-9a58-a607625f7766)

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/440e967e-71d7-4ad6-b5c4-d382d61d8cb2)

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/7f386f18-510c-44b4-ad39-ce356f68be28)

**Comment by felixsuarez0727** [comment]
The root cause is when an action is created but not updated in `rootActionConfig.editor[0].options`and shows empty.

Issue found: When a new action is made, the `Add_Integretation_Command ` is not automatically executed after the action is created. In ActionDao, in the create function, it does not enter in `then()`, which causes the integration in options to not be carried out.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/642089a5-fb25-4d64-a0f5-1a2730d82d50)

Solution: In ActionDao `Add_Integration_Command.run() `is placed outside of `Insert_Action.run`. When creating a new action, it is saved in options, pending verification because it does not enter to `then()` of `Insert_Action.run`

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/0ef83c02-7fe2-42c7-8f41-53c48cecd0a1)
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/6a340476-e34d-4232-a282-fe8729a6c2c1)

**Comment by felixsuarez0727** [comment]
So far, it has worked well with HubSpot's Files API (Options are added without issue). Moving to QA

**Comment by felixsuarez0727** [comment]
Experiencing a similar behavior (actions dropdown not loading) for the HubSpot Files Integration.

Currently investigating this , since `rootActionConfig.editor.options` is being populated just fine (this issue's fix). So, it seems to be related to something entirely different.

**Comment by prapullac** [comment]
Closing the issue as it is working as expected
