### ISSUE TITLE
[Bug]:  Date picker should not update till a user selects a date

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#11057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

**Feature Requirement Proposal**
For the Datepicker Widget, we have one action "onDateSelected".
We may need "onMonthSelected" and "onYearSelected" as there are issues in certain scenarios

This requirement is based on a issue faced by a Discord user
https://discordapp.com/channels/725602949748752515/940981446338809886

**Feature Requirement Summary :**
---Not Finalised --

 

### Why should this be worked on?

The need happens when we want to display the selected date in another place.

**Part A**
(1) User Displays the selected date in a label/textfield using the 'onDateSelected" action script.
(2) User navigates to the next month and selects somewhere outside, the month gets changed in the datePicker.
(2.1) The date in the label/textfield remains unchanged, so a mismatch is occurring
(3) Similarly when Year is changed the mismatch between the datepicker date and the display date in a label/textfield occurs.

Considering the above scenario we need the implementation.

Alternatively
**Part B**
(1) To make mandatory to select the modal calendar, else the calendar may not disappear.
(2) Do not change the Month or Year in the datepicker unless a date is selected.

TODO :
To decide which option are feasible and we could go ahead (Part A or Part B or a combination). 
To write down the conclusion in the "Feature Requirement Summary" above.

**Comment by fsureau-kpler** [comment]
Hi, as discussed on the Support channel, as long as the date displayed is different than the date if the DatePicker.SelectedDate variable, this is a bug, that can lead to a new feature by primarily a bug.

**Comment by Nikhil-Nandagopal** [comment]
Hey @leotom2000 thanks for creating this issue. I think the solution should be to only update the date when a date is selected and not when a user is browsing the calendar.
@somangshu @dilippitchika can we get this small issue solved quickly?

**Comment by somangshu** [comment]
@Tooluloope can you help us triage this?
