### ISSUE TITLE
[Enhancement] : Input widget Reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11061]
Scope - https://www.notion.so/appsmith/Input-Widget-4ac315b06a114083bda740731278f038

**Comment by dilippitchika** [comment]
Items to be improved
1. Position of error messages - Discussed yesterday
2. Icons can be added by the user - this design is missing
3. Hover state for input widget
4. Tool tip design is missing - there's a possibility of only having tooltips and no labels.

Please check the current implementation

**Comment by chandannkumar** [comment]
Observation:
1. There is some gap between Label and Tooltip when Label position is set to left. 
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/c69c542f-e2c7-4f55-b7b8-eeddb6cb9851)

2. Hover color change in eye icon in password is still exists. On notion doc it says to remove this hover color change.
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/ecdf4cd5-3541-4b45-9b03-f73c23058bc9)

**Comment by chandannkumar** [comment]
LGTM
