### ISSUE TITLE
[Bug]: REST API datasource : default value is not showing up for `Authentication Type` dropdown

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#11062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Default value is not showing up for `Authentication Type` dropdown.

### Steps To Reproduce

1. Create a new REST API datasource.
2. Notice that no default value is shown for `Authentication Type` dropdown.

### Environment

Production

### Version

Cloud

**Comment by devnamrits** [comment]
@sumitsum Can I take this up??
cc: @danieldare
