### ISSUE TITLE
[Bug]: MongoDB datasource test shows ok when authentication is invalid

### ISSUE THREAD

**Issue by mojtab23** [appsmithorg/appsmith#11067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we have a MongoDB datasource that needs authentication, the test datasource button show ok even if we enter invalid credentials. This comes from the way that mongoPlugin `testDatasource()` is implemented and it ignores `Unauthorized` error when testing a datasource.

It's related to number 8 of this issue: https://github.com/appsmithorg/appsmith/issues/5005#issuecomment-1002032009

### Steps To Reproduce

1. Create a MongoDB datasource that needs authentication( user & password ).
2. In the **Authentication** section enter invalid credentials or leave them empty.
3. Hit the **Test** datasource button and it shows **OK** even that queries will not work.

### Environment

Release

### Version

Self-Hosted

**Comment by btsgh** [comment]
Scenarios tried:
-   Valid user name and password - Gives a success message.
-  Invalid user name and valid password - errors out (Exception authenticating mongo credential) 
- Invalid user name invalid password - errors out (Exception authenticating mongo credential)
-  Valid user name, invalid password - errors out (Exception authenticating mongo credential) 
Test gives error message when authentication is invalid.
<img width="921" alt="Bug11067_Error1_Invalidusername_Validpassword" src="https://user-images.githubusercontent.com/101863839/160093296-fa4ce98e-43a0-4cc0-9a28-44d6224fcdcc.png">
