### ISSUE TITLE
[Task]: Add tooltip for all the property names

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#11065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The property name is getting keyboard focus if we use `Tab` key to navigate through the property controls.
But, the focus state is not visible to the users unless the property name has a tooltip associated with it.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/dcbac37cb766457697c8f744957418c1-00001.gif)](https://www.loom.com/share/dcbac37cb766457697c8f744957418c1)

**Comment by vuiets** [comment]
@vasanth-appsmith will we be considering this with the property pane reorganization or themeing projects?

**Comment by aswathkk** [comment]
![image (2)](https://user-images.githubusercontent.com/10436935/158166703-7260e77b-ccf0-49c6-a7f3-e03e2ce9394e.png)
@vuiets @vasanth-appsmith 
Are we looking at a highlighted state like this?

**Comment by aswathkk** [comment]
We decided to have a tooltip available for all the property names for consistency. In that case, a separate focus state is not required.

**Comment by aswathkk** [comment]
Closing this in favour of #4645
