### ISSUE TITLE
[Docs]: Add documentation for Helm

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#11066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

We are releasing Helm charts for Appsmith deployments on Kubernetes. We should add these steps to our official documentation as well.

### Describe the improvement

The README file at: https://github.com/appsmithorg/appsmith/tree/release/deploy/helm has already been written. This needs to be moved to docs.appsmith.com

**Comment by Nold360** [comment]
The Helm chart deployment is very confusing to me. After deploying it i end up with a single appsmith container, which doesn't work:
```
Initialize .env file
Load environment configuration
Checking environment configuration
Check mongodb uri host
Check initialized database
Check mongodb cloud replica set
********************************************************************
*          Mongodb cloud replica set is not enabled                *
```

There is no mention in the docs, that i need to deploy mongo or redis myself. Furthermore those should be included as subcharts in the appsmith chart.

Why is it so different from the "install.sh" k8s deployment? Why even maintain multiple deployments for k8s? Why not have it all salved in the chart?

Anyways, I tried to add a mongodb using bitnami's chart but couldn't make it work. even with configured env in appsmith chart.

**Comment by sharat87** [comment]
Hey @Nold360, sorry just seeing this now. That issue you mention was recently resolved. Can you try again now? If you are still facing the issue, please let us know here or in a new issue.

I'm closing this issue since this is about docs and we've already documented helm charts at https://docs.appsmith.com/setup/kubernetes.
