### ISSUE TITLE
[Bug]: Tree select widget behavior for long label names

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7e03fa19a4dc4099899905ad9d0c744e-00001.gif)](https://www.loom.com/share/7e03fa19a4dc4099899905ad9d0c744e)

### Steps To Reproduce

1. Add Tree select widget on canvas
2. Add large text options in dropdown list
3. Observe that text been overlapped with dropdown icon

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Adding another issue

Select widget doesn't truncate the text selected on resize. This can lead to overlaps. Will need to create a new bug.
