### ISSUE TITLE
[Bug]: REST API UI issues

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#11071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Collating a bunch of issues here:

- [ ] When saving a new API as datasource, the datasource creates two empty headers by default. This should not be the case because it breaks the UI at multiple places.
        - Datasource view mode shows empty headers
        - REST API shows inherited headers that never render
- [ ] When you try to store an API as a datasource, the rules to display the "Save as datasource" option next to the URL bar is different from the one on the Authentication tab. I am always allowed to store an API as datasource from the Authentication tab. We could do with some messaging here.
- [ ] The authentication type shown for REST APIs that do not use authentication is shown as DBAUTH in some cases
- [ ] The headings "Key" and "Value" for the Headers tab looks different from the headings in the Params tab

### Steps To Reproduce

https://user-images.githubusercontent.com/5298848/153391243-03b030b5-0d22-4792-a101-8068d8199cc4.mov

<img width="246" alt="Screenshot 2022-02-10 at 4 08 37 PM" src="https://user-images.githubusercontent.com/5298848/153391107-2287d437-4b6e-449e-88f6-e375576ea3a2.png">
<img width="957" alt="Screenshot 2022-02-10 at 4 08 42 PM" src="https://user-images.githubusercontent.com/5298848/153391116-46564587-1d19-4f7c-9488-ecbda2b549b2.png">
<img width="949" alt="Screenshot 2022-02-10 at 4 08 47 PM" src="https://user-images.githubusercontent.com/5298848/153391129-d4d28627-f8a6-434d-adfd-738e9e0a3405.png">

### Environment

Production

### Version

Cloud

**Comment by AmanAgarwal041** [comment]
1. Can disabling the `Save as Datasource` button in the Authentication tab be a solution for the second issue ?
2. Was unable to reproduce the third issue : (`The authentication type shown for REST APIs that do not use authentication is shown as DBAUTH in some cases`). @nidhi-nair Can you please add the steps to reproduce the issue ?

**Comment by AmanAgarwal041** [comment]
1. `The authentication type shown for REST APIs that do not use authentication is shown as DBAUTH in some cases` : Seemed to be a old issue which was not reproducible, so leaving it all other will be solved in the created PR.
