### ISSUE TITLE
[Feature]: Validation for malformed JSON objects coming from the SaaS Integration Manager App.

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#11087]
Improved Error Handling and Logging is needed for the SaaS Integration Manager App.

**Comment by nidhi-nair** [comment]
We should add a schema validation step before saving any data in the DB. This will help pinpoint the source of errors in the app.

**Comment by felixsuarez0727** [comment]
@nidhi-nair, to move ahead with this, I think we need to:

-  Resume or discussion regarding how do we want to handle this. The early comments are recorded on: [Discussion: How to Test SaaS Integrations](https://www.notion.so/appsmith/Discussion-How-to-Test-SaaS-Integrations-de14586343e449969ed8fc0176e36f7b).
- Create a copy of the `mock-api` repo and provide me with access, so I can review it.
-  Documentation on the Schema the backend expects for the SaaS Integration configuration objects.

This will also require some backend work outside the SaaS Manager App.

Please let me know your thoughts.
