### ISSUE TITLE
[Bug] SaaS Integration Manager creates a malformed JSON for Integrations

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#11086]
For the Twilio integration, it was noticed that the SaaS Integration Manager could create a malformed JSON.

Lines 346 to 348 ([https://app.zenhub.com/files/275993885/4b6b7f55-b34b-4453-8104-6031fa192760/download](https://app.zenhub.com/files/275993885/4b6b7f55-b34b-4453-8104-6031fa192760/download)) contain an example of parameters for the action that were added but did not create properly.

It seems that because those objects were not created properly, the integration, once installed, is unable to load the actions.

**Comment by nidhi-nair** [comment]
It is likely that this JSON got malformed in a CRUD operation on action templates. A reproduction has not been created so far, but we could start trying by creating and deleting actions in a test integration.

**Comment by felixsuarez0727** [comment]
Created an integration called "Test Integration" as suggested. 

I have been adding pairs of Dynamic variables to each section where they can be added (Query String, Query Params, Json Body, etc).

Removing the first member of the pair seems to be working fine when checking via "Fecth_Actions". Any way to check on the Mongo side?

When this was detected, the specific issue was that some identifiers were missing, right?

**Comment by felixsuarez0727** [comment]
Been trying to reproduce the malformed json. The closest I've gotten is  this "mismatch" between what is presented on the form and what template.children registers.

1. Add two variable strings to the URL input. (00:09)
2. Save and check that the Dynamic variables appear. (00:23)
3. They don't appear on Fetch_Actions: template.children. (00:30)
4. Click "Save" multiple times. (00:45).
5. Re-run Fetch_Actions, template.children is now populated (00:53)
6. Update the name of the variables and save. (01:11)
7. Update to name of the variables again (different (1:25)
8. Check that Dynamic Variables is updated. It is (character missing due to other issue).
9. Save and check the values on template.children were updated. They were.
10. Add the missing character to the variable. Check it is updated on Dynamic Variables (2:23)
11. Save and then refresh.
12. The variable name on template.children is not changed and stays that way.
13. The only way to force the change is to add a new  variable altogether. (04:07)

**Comment by felixsuarez0727** [comment]
Reopening... (Closed by mistake)

**Comment by felixsuarez0727** [comment]
The root cause is that template children do not update at a time and show an old version of dynamic variables. When selecting the first tab Dynamic Variables and then save, it works.

Issue found: When a new change is made in the Url/Params tab it doesn't update in Dynamic Template Children, it only happens when the Dynamic Variables tab is selected before.

Solution: Change the condition in tab configuration and add
DynamicVariables.updateDynamicTemplateChildren() in the button save, to update the dynamic variables every time that going to save and prevent an old version of variables.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/c6d7f21c-d9f5-4273-ad80-b7b82d5a1203)
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/52cc571f-e2a7-45a2-bdcf-032e4662f91d)
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/0ab3df8b-7a60-4773-b38e-66891aba0f87)
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/19687a5b-2f28-4198-94e8-06754bbad939)

**Comment by prapullac** [comment]
Working as expected hence closing the issue
