### ISSUE TITLE
[Bug]: Select Widget does not clear after submit or reset but is actually empty

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [appsmithorg/appsmith#11081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Apologies if this is a dup. I did a search for "is:Bug select widget" and got 9+ pages of results. The select widget does not visually clear after submit or reset but the state does clear.

### Steps To Reproduce

Following the "Building a Store Catalog Manager" tutorial.
1. Using forms
2. Using a "Select" widget in place of the dropdown widget.
3. Complete the form and select something.
4. After submitting the form the dropdown widget does not visually clear/reset.
5. Fill out the form again but do not select anything just leave the select widget on what it was.
6. Submit the form.
7. Check the DB. You will see the first submit recorded data for the select but not the second.

### Environment

Deploy Preview

### Version

Cloud

**Comment by areyabhishek** [comment]
Thanks for reporting this! We'll fix this
