### ISSUE TITLE
[Task]: Handle MongoDB 5 upgrade

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#11098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

MongoDB is upgrading to version 5. As part of this upgrade, they have removed certain commands which can be [seen here](https://docs.mongodb.com/manual/release-notes/5.0-compatibility/#removed-commands). In this list, we definitely use `ensureIndexes()` command. Hence, Appsmith needs to upgrade MongoDB library & handle this upgrade for MongoDB Atlas as well.

This is not a very high priority issue yet. But we'll have to keep an eye out on the MongoDB 5 rollout so that we can respond quickly.

**Comment by rgdev** [comment]
What is the state of Appsmith on MongoDB 5.0.x right now ? Are we gonna break it if we upgrade an existing DB to Mongo 5 ?

**Comment by mohanarpit** [comment]
Closing as this was fixed as part of `v1.9.2`
