### ISSUE TITLE
Documentation - List Widget - Beta

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#11094]
The ticket will cater to changes available for the existing list widget available on the platform:
- Modifying the existing documentation for clarity and readability
- Update the documentation structure

**Comment by jnikhila** [comment]
The updated documentation for Beta List widget is available for review.
https://docs.google.com/document/d/1M3Qbwv02iBj3nqchcMvmEl23G0dD_yEU83z2m6ODeeE/edit?usp=sharing

**Comment by jnikhila** [comment]
Updates as per first round of discussion:
* Add a properties table - giving a snapshot of all the properties
* Add a events table - giving a snapshot of all the events

**Comment by jnikhila** [comment]
Apart from videos, the document is updated and ready for review.

**Comment by jnikhila** [comment]
@cokoghenun - as discussed earlier, we have to update the list widget video to incorporate the new headings, and add connect data button feature.

**Comment by cokoghenun** [comment]
Sure @jnikhila

**Comment by jnikhila** [comment]
@megaconfidence - closing this issue as I assume this is already added to your pipeline.
