### ISSUE TITLE
[Bug]: onPageLoad behaviour is different for forked, duplicated and original apps when function call fails

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When confirmation is set for onPageLoad function run then the app behaves differently for
1. Original app - Confirmation modal is displayed
2. Duplicated app - Confirmation modal is displayed
2. Forked app - Toast message indicating failure is displayed
3. Imported app - onPageLoad setting for function is disabled when function run fails

The function used for all of the above scenarios is a function that is in error state hence fails by default and runs the onError chunk of Promise code.

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7b53e47aff9744ab82d1dde8b3052207-00001.gif)](https://www.loom.com/share/7b53e47aff9744ab82d1dde8b3052207)

### Environment

Deploy Preview

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
Backend change needed for this https://github.com/appsmithorg/appsmith/issues/11327
