### ISSUE TITLE
[Feature]: Date Picker for Month and Year.

### ISSUE THREAD

**Issue by kamilkabir9** [appsmithorg/appsmith#11105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Date Picker for Month and Year should allow user to select just month(ex: 1st FEB) of a year.

### Why should this be worked on?

This will allow users to select just a month rather than selecting a particular date. Switching between months will be also be easier.

REF:
![image](https://user-images.githubusercontent.com/10809445/153683270-4aeca562-dc28-41b1-a65b-340e5cfcdb37.png)

**Comment by dilippitchika** [comment]
@Tooluloope can this be checked if this is a straightforward change in the underlying component? If not, we have to think of new widgets and then work on design.

cc @somangshu

**Comment by Tooluloope** [comment]
I've gone through Blueprint Documentation, they don't support this. We'll have to make this a separate Widget

**Comment by dilippitchika** [comment]
We will be adding a JS snippet for month and year so that they can be used with select widgets. Rather than creating separate widgets.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika then can we close this?

**Comment by dilippitchika** [comment]
@Pranay105 can you add the following snippets?

Year picker - This snippet converts your select widget into a year picker.
`{{
    function(){
      let start_year = 1920; //change start year for year picker
      let end_year = 2120; //change end year for year picker
      let years = [];
      for (let i = start_year;i<= end_year;i++){
        let current_year_object = {
          "label":i.toString(),
          "value":i.toString()
        }
        years.push(current_year_object)
      }
      return years;
    }()
}}` 

Month picker - This snippet converts your select widget into a month picker.
`[
    {
      "label": "January",
      "value": "january"
    },
    {
      "label": "February",
      "value": "february"
    },
    {
      "label": "March",
      "value": "march"
    },
    {
      "label": "April",
      "value": "april"
    },
    {
      "label": "May",
      "value": "may"
    },
    {
      "label": "June",
      "value": "june"
    },
    {
      "label": "July",
      "value": "july"
    },
    {
      "label": "August",
      "value": "august"
    },
    {
      "label": "September",
      "value": "september"
    },
    {
      "label": "October",
      "value": "october"
    },
    {
      "label": "November",
      "value": "november"
    },
    {
      "label": "December",
      "value": "december"
    }
  ]
`

**Comment by somangshu** [comment]
FYI, for the months snippet we could use moment as follows

`{{moment.months().map((v) => { return {label: v, value: v.toLowerCase()}})}}`

**Comment by kamilkabir9** [comment]
Hi any idea why the below coding is not working 
`function year_month_dropdown(){ 

        let start_year = 2021; //change start year for year picker 
        let end_year = 2022; //change end year for year picker 
        let years = []; 
        function getMnth(year){
        	return moment.months().map((v) => { return {label: `${v} - ${year}`, value: moment(`${v}-1-${year}`, "MMMM-D-YYYY").format("D-MMM-YYYY")
        }
        }
        )
        }
        for (let i = start_year;i<= end_year;i++)
            { 
            let months=[getMnth(i)];
            let current_year_object = { "label":i.toString(), "value":moment(`January-1-${i}`, "MMMM-D-YYYY").format("D-MMM-YYYY"), "children":months}
            years.push(current_year_object) 
            } 
         return years; 
     }`

**Comment by somangshu** [comment]
@kamilkabir9 Is this is a JS Object? How are you utilising the above code?

Idea the code is alright and should be able to execute if implemented properly

**Comment by kamilkabir9** [comment]
@somangshu I'm using code to create tree select component.

2022
  Jan
  Feb
  .
  .
  .
2021
  Jan
  Feb
  .
  .
  .

**Comment by somangshu** [comment]
@kamilkabir9 I was able to find the problem, some error in the code and one bug in the tree-select widget
- Since Appsmith is reactive, we need to use IFEE to execute multiline JS code, Another problem in the code is that you are encapsulating the children array in another array and hence the code is failing to execute, 
![Screenshot 2022-04-19 at 1 26 18 PM](https://user-images.githubusercontent.com/11089579/163954428-a47196e6-323d-42d1-81a4-f000e4e0720b.png)

- Bug on the platform is that the parent and children values need to be unique. The unique validation should alway apply on the same level and not all the values in the whole object. cc @dilippitchika @Tooluloope does this makes sense to you guys, We will need to take a call here.

**Comment by Tooluloope** [comment]
@somangshu Not applying the Unique validation on all values would be Inconsistent.
Since the Output of the Treeselect widget doesn't specify nesting, It just outputs a value/values irrespective of if the value is nested. So if we have duplicate values in two separate Parents, the outputted value would be the same.

**Comment by dilippitchika** [comment]
Yeah agreed with Tolu, 

If we start supporting duplicates then this is how it MAY work - 
- Allow duplicates across children and pass both levels of information in selectedOptionValue. Like it becomes an object which has the details of parent and child. The object should be unique.

Let's see if we want to create a separate issue and tackle this, i believe this is useful for treeselect but needs more validation.
