### ISSUE TITLE
[Bug]: Update config label in Rest API datasource config page

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#11106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Update  label`Send client credentials with` to `Send client credentials with (on refresh token):` under the `Advanced settings` tab that appears for `Oauth` + `Authorization Code` setting.

### Steps To Reproduce

1. Create new Rest API datsaource. 
2. Set authentication typo to OAuth. 
3. Select Authorization code from dropdown. 
4. Unfurl Advanced settings dropdown. See the config names. 

### Environment

Production

### Version

Cloud

**Comment by RishiKumarRay** [comment]
@sumitsum can i raise a PR updating the changes?

**Comment by sumitsum** [comment]
@RishiKumarRay yes, that would be great. I am assigning this issue to you. I see that you have already raised a PR for this issue. Please do let us via comment here if the PR is ready for review. Please reach out to us on [Discord](https://discord.com/invite/rBTTVJp) if you face any difficulties.

**Comment by RishiKumarRay** [comment]
@sumitsum please review the PR, thanks for assigning
