### ISSUE TITLE
[Bug]: The option to add admin emails does not grant other users access to admin setting

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The option to add admin emails does not grant other users access to admin setting
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/153799262-3d3e5718-9540-4d49-ac91-87165fa41516.png">

### Steps To Reproduce

1. In the admin setting page 
2. under general tab
3. In Admin Email when user adds any email address along with the admin email 
4. The newly added users list doesn't get the admin access

### Environment

Production

### Version

Self-Hosted

**Comment by hiteshjoshi** [comment]
Removing this from SSO/SAML epic. I think someone wanted to connect ACL but its not being covered as ACL but rather adhoc permission at instance level atm.

**Comment by RakshaKShetty** [comment]
admin access is granted in some scenarios and fails in some scenario so added a separate issues so closing this
