### ISSUE TITLE
[Feature]: Entity explorer pane: allow bulk operations on queries

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#11117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

On entity explorer pane allow bulk operations on queries like bulk move, bulk copy, bulk delete.

### Why should this be worked on?

It will help address use cases like this - say I need to move 10 queries from page1 to page2 then instead of moving them one by one I should be able to multi select all such queries and move them using the bulk move feature.

**Comment by sumitsum** [comment]
One way to implement it would be to simply iterate over all the queries one by one and call the necessary APIs e.g. call the `copy` API for each action in case of `bulk copy`.

**Comment by riteshkew** [comment]
this should now be possible through modules/packages
