### ISSUE TITLE
[Bug]: Dropped files is not displayed in File picker pop up when widget is moved outside the container

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c58a009bfad24ec683f822b639b76d04-00001.gif)](https://www.loom.com/share/c58a009bfad24ec683f822b639b76d04)

### Steps To Reproduce

1. Drag and drop a File picker widget
2. Add any file
3. Upload the file
4. Now drag and drop the file picker from container to canvas
5. Click on file picker
6. Observe that uploaded file is not displayed

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
This problem is not actually faced by the app viewers, This is not of priority, 

@techbhavin can you explain what change are you making in the PR?

**Comment by somangshu** [comment]
Closing this off now now, this DX is not relevant and the changes made is costing us time, closing the PR as well right now
