### ISSUE TITLE
[Bug]: Table widget refreshes each time a button type column is clicked

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When table widget has a button type column and this button is clicked, table refreshes and any widgets deriving data from the table widget also refresh. This has been observed on current release and works as expected on master without any lag or refresh.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/54d03a3768394ba5ad5ef45c158c91ba-00001.gif)](https://www.loom.com/share/54d03a3768394ba5ad5ef45c158c91ba)

### Steps To Reproduce

1. Go to app at link - https://release.app.appsmith.com/applications/620a06c4a68a2619dc8d0caa/pages/620a06c4a68a2619dc8d0cac/edit
https://app.appsmith.com/applications/6209d7096b4b1e154a3c01ea/pages/6209d7096b4b1e154a3c01ed/edit

2. Observe the difference in behaviour of the app when button type column of the table widget is clicked.

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@SatishGandham Do you know any probable cause for this issue?

cc @ApekshaBhosale

**Comment by ApekshaBhosale** [comment]
@somangshu yes we do. we added dependency from actions to the widget which causes one more eval. we are are reverting the change and will work on another solution.
