### ISSUE TITLE
[Bug]: Update from CRUD Generated page with timezone field resulting with Error in Updating Resource

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#11141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1456" alt="Screenshot 2022-02-14 at 5 32 04 PM" src="https://user-images.githubusercontent.com/91450662/153863009-64467a84-5891-45d3-8c20-1c10466f2b85.png">

### Steps To Reproduce

1. Generate CRUD page with Postgres DS
2. Create/Select a table having timestamp type columns
3. CREATE TABLE public.timezoneTest (
    id integer NOT NULL,
    name character varying,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone)
4. insert into public.timezoneTest (id, name, "createdAt", "updatedAt") values
(7, 'Test user 7', '2019-08-07 21:36:27+00', '2019-10-21 03:23:42+00')
5. Now try updating one of the timestamp field in right format & hit 'Update' - observe 'Error in Updating Resource' toast msg
6. Or Try updating only name [non-timestamp type] field to different value & hit 'Update' - observe 'Error in Updating Resource' toast msg
7. Try updating a table with no timestamp columns & update works fine
8. Updating should be success in all scenarios

### Environment

Release

### Version

Cloud

**Comment by sumitsum** [comment]
The workaround here would be to turn off the prepared stmt toggle.

**Comment by leotom2000** [comment]
Findings :
Part 1:
The application can work without this fix in the following way
Example of working syntax for updating TimeStampTS without this fix is : 2022-04-11 05:30:00
This is saved as UTC format in the DB, which fetching necessary conversion are required based on the fetching location and displayed in the right field in the same syntax.
So Updating again with the same syntax will work without this fix.

Part 2:
At present we are fetching and displaying in this format 2022-04-11T00:00:00Z
This format although valid is not understood by postgress, so this fix is required.
In this case the TimeStampTS will be save as such (like a varchar) and can be fetched back and displayed without any conversion complexities.

However this fix work for both the above cases
