### ISSUE TITLE
[Bug]: LIMIT private repos does not restrict 3 apps at instance level

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For git-sync feature we are limiting number of private repo connected at 3 per instance(self-hosted) and 3 per org at Cloud version. 

### Steps To Reproduce

For git-sync feature we are limiting number of private repo connected at 3 per instance(self-hosted) and 3 per org at Cloud version. But this is not being applied at org level but not at instance level even for the self hosted. 

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
I think we should continue to only enforce this at an organization level and not an instance level
