### ISSUE TITLE
[Bug]-[2670]:geolocation callback is not called

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#11147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://docs.appsmith.com/framework-reference/appsmith#geolocation

Calling an API `onSuccess` of `getCurrentPosition` doesn't work.

```
{{
  appsmith.geolocation.getCurrentPosition(() => {
	  showAlert("ABC")
  })
}}
```

### Steps To Reproduce

1. On button click.
2. Call `appsmith.geolocation.getCurrentPosition`.
3. And call an API inside it's success callback.
4. Click the button.
5. Notice the API never gets called.

### workaround
Call the API after `getCurrentPosition` instead of the callback.
![image](https://user-images.githubusercontent.com/66776129/153881934-4c81b2df-5cbf-46ca-bef7-b13d2375cef2.png)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk is this even expected? Now with the new promises, I think only .then should work for these newer functions. @hetunandu can confirm

**Comment by bharath31** [comment]
Assuming 100% of users who use `getCurrentLocation()` on WIDGET_PROPERTY_UPDATE or AUTO_COMPLETE_SELECT

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 267 |
| Effort (months)  | 0.2 |

**Comment by satbir121** [comment]
Tested this with on [PR](https://github.com/appsmithorg/appsmith/pull/18235)

cc @ramsaptami 
```
{{appsmith.geolocation.getCurrentPosition(() => {
	Api1.run({id: 15});
	showAlert("abc " + Math.random())
	setTimeout(() => {
		showModal('Modal1')
	})
}, (error) => {
	Api1.run({id: 15});
        console.log("ERROR",error)
	showModal("Modal1")
	showAlert("Error " + Math.random());
})}}
```
