### ISSUE TITLE
[Bug]: Add JS for icon property in buttons

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#11142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

EX: Starting with the button widget, We see that the button color cannot be dynamically changed and the one in the table widget can. This is an Inconsistency and similar situations can be see across  these properties.

We propose we look at this from the other way around and make all properties JS convertible, and then check what are the failing scenarios.

- [ ] What changes do we need to this from the platform POV.

### Steps To Reproduce

1. D&D button widget
2. try setting the button color dynamically
3. see that you do not really have access to JS

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@riodeuno @vuiets your thought here please

**Comment by dilippitchika** [comment]
@somangshu this is becoming a headache now. 

I have assigned a similar issue to @vibhandikyash #11387 where the idea is to convert all fields to JS first in a dp and see which fields don't need JS and remove JS option for those. 

Can we discuss about this issue in slack/sync once and move ahead?

**Comment by somangshu** [comment]
@dilippitchika surely we can do that, Our idea is to find a change to enable it everywhere rather than making the changes individually. Hence I needed an input from @riodeuno. Feel free to start a thread around this.

**Comment by somangshu** [comment]
Thanks @riodeuno 

@dilippitchika we will need to a way to list and track all scenarios. We can work on this together if you have a template in mind, We will keep @vivekverma2312 informed about all the discussion. 

The only thing is that this looks like high effort from the PRD / Dev / QA POV. We might have to push this back to later. Let me know if you agree / disagree

**Comment by dilippitchika** [comment]
Missed this for some reason, I will create a template and track this forward.

**Comment by dilippitchika** [comment]
We have fixed a lot of these in the property pane project. Adding ones that got missed out 

We need the icon property to have JS in button, button group and menu buttons.

**Comment by dilippitchika** [comment]
Greetings @sanjus-robotic-studio  thanks for showing interest 🎉 , This is all yours. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by sanjus-robotic-studio** [comment]
Hey @dilippitchika I have raised a pr for this error

**Comment by dilippitchika** [comment]
Thanks for this @sanjus-robotic-studio, @Tooluloope can you please review this pr and run it through our workflows?

CC @somangshu

**Comment by Sripriya93** [comment]
Checked in Button, Button group and Menu button, JS option for Icon property is present only for Button widget.
It is not present in Button group and Menu button.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/104895602/198519868-f4970904-f2c2-404a-84db-586cdd03b1a1.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/104895602/198519951-195c6da3-ec55-424c-9361-061676b70683.png">

**Comment by dilippitchika** [comment]
@sanjus-robotic-studio can you also add it in menu button and button groups?

**Comment by sanjus-robotic-studio** [comment]
Ok sure

**Comment by sanjus-robotic-studio** [comment]
But in the previous Pr itself I have added it. Can you check and let me know

**Comment by dilippitchika** [comment]
You are right, i can see it there, but not in our environment. Let me ask someone to check, @Tooluloope @yaldram can one of you check?

**Comment by Tooluloope** [comment]
@sanjus-robotic-studio  Could you help fix this?
https://user-images.githubusercontent.com/31691737/199193670-ee7ff157-f456-48ce-b566-674196b67a0a.mov

CC @dilippitchika

**Comment by sanjus-robotic-studio** [comment]
@Tooluloope, will try to fix it

**Comment by Tooluloope** [comment]
> @Tooluloope, will try to fix it

Thank you @sanjus-robotic-studio

**Comment by sanjus-robotic-studio** [comment]
@Tooluloope can you check this ?
https://github.com/appsmithorg/appsmith/pull/18031

**Comment by chandannkumar** [comment]
JS toggle is not added for Button Group widget
![image](https://user-images.githubusercontent.com/95341241/201280089-9bc8549f-9a66-40b8-a1e5-9da29dda4f56.png)

Verified JS toggle on Button, Menu Button & Icon Button

**Comment by Sripriya93** [comment]
Added JS toggle on Button, Menu Button, Icon Button & Button Group- Tested and verified
