### ISSUE TITLE
[Bug]: Property pane boundary collides with canvas scroll bar making it a hard to use experience

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Canvas scroll bar is placed under the property pane boundary which gets highlighted when hovered over. This causes canvas scroll bar to get hidden and almost impossible to use.

### Steps To Reproduce

1. Drop multiple widgets on the canvas such that there's a scroll on the canvas
2. Try to use this scroll bar to move on the canvas and observe that the hover state of the property pane boundary overlaps and collides with the scroll bar functionality

### Environment

Production

### Version

Cloud

**Comment by momcilo-appsmith** [comment]
@somangshu we have it as low priority for this week.

**Comment by momcilo-appsmith** [comment]
@somangshu Is it possible to:
1. Put the drag line inside the property pane and make it 2px?

**Comment by somangshu** [comment]
Thanks for pointing out @momcilo-appsmith Found this to be a simple fix

We can resolve this
