### ISSUE TITLE
[Bug]: airtable test throws error "unsupported operation"

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#11146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Airtable datasource creation.
Test button always throws `unsupported operation` error.

However, If we save and create a query. It works like a charm.

### Steps To Reproduce

- Create a new Airtable datasource
- Select API key authentication type
- Paste your API key
- Click `test`
- Unsupported operation alert pops-up

Needs to be checked with bearer key.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/17f9eb2cbd924e689ecca044ba76b429-00001.gif)](https://www.loom.com/share/17f9eb2cbd924e689ecca044ba76b429)

### Environment

Production

### Version

Cloud

**Comment by nidhi-nair** [comment]
Closing as fixed in #10450
