### ISSUE TITLE
JSON Form - Handle configuration retention for missing properties (Modes)

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#11159]
The JSON form takes the JSON in `sourceData` and converts it into a form with fields.
When this `sourceData` changes i.e the underlying property name changes or the value type changes, the form re-generates the modified properties (resetting it to the detected field type with default configuration)
A problem arises when we connect with a Table widget's selected row property to the sourceData of the JSONForm.
In certain cases, while cyclic through the table rows, there may be cases where a certain row won't have a particular property.
```js
// row with all the properties
{
  name:  "John",
  age: 20,
}

```
```js
// row with missing property
{
  name:  "John",
}

```

This change in source data would cause the field `age` to be removed from the JSON form and thus leading to the loss of any configuration changes made to that particular field.

There is another scenario where were this loss takes place. When refreshing the page, the `selectedRow` of the table widget would have all the property values as an empty string.

```js
// row with all the properties
{
  name:  "",
  age: "",
}

```
As age is now a `string` from a `number` the configuration again changes.

Proposed solution
When a field is generated for the first time, we freeze the field for any auto-detection from the source data. So even if the property goes away from the source data, the JSON Form parser won't touch it at all unless the user un-freezes it which would tell the widget that the particular field is open for auto-modification.

Example:
https://appsmith-20p6kw2e0-get-appsmith.vercel.app/applications/620b3c7ecc03f3620acfc6a7/pages/620b3c7ecc03f3620acfc6aa

**Comment by ashit-rath** [comment]
cc: @riodeuno @somangshu @Nikhil-Nandagopal @dilippitchika @vivekverma2312 @sbalaji1192

**Comment by Nikhil-Nandagopal** [comment]
@ashit-rath 
What if we always kept the configuration of the field in the JSON Form irrespective of whether the sourceData changes? I know this will lead to additional configuration being stored in some cases but there, the user can simply delete those fields and we can give them a button to reset the configuration in the property pane

**Comment by ashit-rath** [comment]
@Nikhil-Nandagopal 
We would lose the auto changing of fields.
If we are typing out the `source data` instead of binding, the first letters we type out would be the deciding factor for the field type that comes out.
Eg. my intention -> { "date": "10/12/2010 } and while typing I pause at { "date", "1" } <- now we are stuck with Text input and I manually have to go and change to a date picker and set the date format.
This might lead to a more painful experience when dealing with an array or object type.

**Comment by ashit-rath** [comment]
The above example I gave is not quite appropriate. Right now "1" -> "10/12/2010" does not convert to the date field automatically. But changing from 
"1" -> 1
 "false" -> false
 "test" -> ["test"] 
etc.
would lead to a field type change.

**Comment by Nikhil-Nandagopal** [comment]
So here is my suggestion:
- We must always maintain a users configuration unless the query changes just like we do in the table widget
- If in some case, a user has some older bloated configs, we can simply give them a way to remove those in the UI
- If a config is present and no source data is present, the field should render with empty data since this is a common use case of missing column data in tables
- If a user really doesn't want the field to render for some usecase, they can control the visible property of the configuration and hide it based on some condition
- If a use is manually typing out the source data and a configuration gets set before they decide to change the data, the user can manually go and manually update the config or we can provie them with a convenience re-generate config CTA that just re-generates the config but I don't think this is so important, it's fine if this is manual for today

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal To resolve the scenario in question, here is how I am interpreting your suggestions, please verify if I understand this correctly.

Old sourceData:
``` { "name" : "Ashit", "address": "Bangalore", "email": "ashit@appsmith.com", "status": "Approved" } ```

New sourceData:
``` { "name" : "Ashit", "email": "ashit@appsmith.com", "created_date": "01/01/1970", "updated_date": "02/02/2022" } ```

The JSONForm shows the following fields for the new sourceData:
- name
- email
- created_date
- updated_date
- address
- email
- status

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno yes and let the user regenerate from the current data if he doesn't like this config

**Comment by ashit-rath** [comment]
Discussed solution:
- We would have a property at the form level called "Mode" which would be either set to `static` or `dynamic`.
   a. <b>Static mode</b> - In this mode, a button appears in the field configuration section "Generate config", which takes the 
     source data and generates config out of it and any change in the source data would not trigger a re-generation of the 
     config unless the "Generate config" is pressed.

  b. <b>Dynamic mode</b> - In this mode, the "Generate config" button is not present and the field configuration changes according to the changes in the source data.

- Static mode would be by default for the new JSON Form widget.

- If a new field gets added to the source data in either mode if the key matches with a custom field's key then no new field configuration would be generated.

@Nikhil-Nandagopal @riodeuno @vivekverma2312 Let me know if I missed anything.
cc @somangshu @dilippitchika @vasanth-appsmith

**Comment by dilippitchika** [comment]
Design is done - https://www.figma.com/file/pZuLD9mWXtk45TOjAeh32b/Form-Widget-Thu-26-Aug?node-id=0%3A1

**Comment by unknown1337** [comment]
@[ashit-rath](https://github.com/ashit-rath), I'd love to use this feature. Do you have any idea when it will be released (appsmith hosted)? :) thanks!

**Comment by ashit-rath** [comment]
Hi @unknown1337, thank you for showing interest in the JSON Form widget. There are a couple of more features that we are planning to bake into this widget before we release it. You can most likely expect this to be available before the end of March.

Meanwhile, if you have not yet; you can try out the widget [here](https://appsmith-git-feature-form-builder-widget-get-appsmith.vercel.app/) and it would be really awesome if you could give us any feedback.

**Comment by unknown1337** [comment]
> Hi @unknown1337, thank you for showing interest in the JSON Form widget. There are a couple of more features that we are planning to bake into this widget before we release it. You can most likely expect this to be available before the end of March.
> 
> Meanwhile, if you have not yet; you can try out the widget [here](https://appsmith-git-feature-form-builder-widget-get-appsmith.vercel.app/) and it would be really awesome if you could give us any feedback.

Thanks, Could it be correct that I cannot sign in with my appsmith account details with the link that you've provided?

**Comment by ashit-rath** [comment]
@unknown1337 Yes, you cannot sign in with your Appsmith credentials as the link uses our release server(a sandbox server for testing features). You can create new credentials using that link and then explore the feature.
Let me know if you are facing any issues.
