### ISSUE TITLE
[Feature]: Different widgets location and sizes for different canvas sizes

### ISSUE THREAD

**Issue by cverdes** [appsmithorg/appsmith#11154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I think that it could be great to be able to have different widgets location and sizes for different canvas sizes.

### Why should this be worked on?

I feel the current responsive system of appsmith quite limited.

**Comment by Nikhil-Nandagopal** [comment]
Hello, we'll be working on this feature as part of $4630. Please do upvote that issue :)
