### ISSUE TITLE
[Bug]: Select Query on generated page is not prepared statement

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#11155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I generate a CRUD page, the SELECT query is not a prepared statement

### Steps To Reproduce

1. Create new app
2. Select "generate from a data table"
3. Select: 
    a. datasource: users
    b. table: public.users
    c. searchable column: name
    d. click "generate page"
4. Look at the "delete", "insert" and "update" queries - they all have "use prepared statement" as "true"
5. Look at the "select" query - this has "use prepared statement" as "false"

Expected:
the toggle is on for all queries

Actual:
the toggle is off for select query

For reference, the select query is: 
`SELECT * FROM public."users"
WHERE "name" ilike '%{{Table1.searchText || ""}}%'
ORDER BY "{{col_select.selectedOptionValue}}" {{order_select.selectedOptionValue}}
LIMIT {{Table1.pageSize}}
OFFSET {{(Table1.pageNo - 1) * Table1.pageSize}};`

We recommend that our users use prepared statements for security reasons. 
[link to slack conversation.](https://theappsmith.slack.com/archives/C02KTH6EHUG/p1644732414634219)
Per @mohanarpit :
_"With prepared statements, PostgreSQL doesn’t allow dynamic values for ORDER BY, LIMIT and OFFSET. Hence, the toggle is turned off."_
Per @sharat87 : 
_"If those keywords don’t allow dynamic values, then either we don’t use bindings for them, or our intelligent substitution system should handle bindings for those keywords separately and the other bindings via prepared statements."_

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is not possible since the generate page takes the column as the key
