### ISSUE TITLE
[Bug]: Currency Input widget is accepting alphabet "e" along with numbers

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In currency input widget, no alphabets and special characters are allowed since it only accepts number as a valid input.
Here "e" is allowed to type which throws error as invalid input.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/43658ef69dc74bdd907328f668b78d00-00001.gif)](https://www.loom.com/share/43658ef69dc74bdd907328f668b78d00)

### Steps To Reproduce

1. Add currency input widget to canvas
2. Try adding input with alphabets and observe it accepts "e" as a input and numbers only

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Not an issue, expected behavior to handle large numbers
