### ISSUE TITLE
[Bug]: Firefox : Clicking on white space near any property on property pane do not focus it

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f846ddbc09b74502908922cadf3567d1-00001.gif)](https://www.loom.com/share/f846ddbc09b74502908922cadf3567d1)

### Steps To Reproduce

On chrome and safari if we click on white space beside any property it focus on that property but the same do not happen on firefox. In firefox browser user has to click on the property for focus.

Use Case: If any user click on any property and try to use keyboard accessibility then user will face difference in UX on firefox. 

### Environment

Production

### Version

Cloud

**Comment by aswathkk** [comment]
@vuiets Should we resolve this on Property pane improvement epic?

**Comment by vuiets** [comment]
@aswathkk wondering if this is a design issue? Do we need a focus state for the Property Pane controls before we may pick this up?

**Comment by aswathkk** [comment]
@vuiets We need a design for the focus state for some components like the property title, copy button etc. I've created a separate issue for that.
This issue is more about inconsistencies in the firefox browser's behaviour.
In chrome, if we click on a white area near to property title and pressing `Tab` moves the focus to the property title. But, that's not the case in Firefox.

**Comment by vuiets** [comment]
Sounds good. Let's pick this up as a part of [#8845 | Property Pane Improvements](https://github.com/appsmithorg/appsmith/issues/8845) 👍

**Comment by somangshu** [comment]
@ankurrsinghal are you working on this right now?

**Comment by vivekverma2312** [comment]
@vuiets Checked on the latest version of Firefox (Version 98.0.2 (64-bit)) and not able to repro it currently.
