### ISSUE TITLE
[Bug]: UQI form control components not setting evaluation order

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#11160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

evaluation order is not getting set for form inputs in the new components. Likely cause is that some of these paths are created on the fly within these component definitions.

### Steps To Reproduce

https://theappsmith.slack.com/archives/C02KTH6EHUG/p1644904919405449?thread_ts=1644833232.546069&cid=C02KTH6EHUG

### Environment

Release

### Version

Cloud

**Comment by prapullac** [comment]
Related to UQI

**Comment by prapullac** [comment]
Verified as part of regression
