### ISSUE TITLE
[Bug]: Menu options scroll beyond table/container/tabs/form widget area when scroll horizontally/Vertically 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0d228678db9646e4b1090d5cdaf84c1f-00001.gif)](https://www.loom.com/share/0d228678db9646e4b1090d5cdaf84c1f)

### Steps To Reproduce

1. Drag and drop a Table widget
2. Bind with query
3. Add a column with menu widget type
4. Add few options in menu widget 
5. Now click on menu widget and open the option drop-down
6. Scroll the table data horizontally 

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Amazing find 😆

**Comment by dilippitchika** [comment]
@Tooluloope the suggested fix can be the following, but I think there can be a better suggestion. 
1. Close the menu options when scrolling starts.
2. Contain the pop-up in the parent widget. 

Please assign someone to investigate.

**Comment by somangshu** [comment]
@techbhavin will find out if `2.` is possible

**Comment by btsgh** [comment]
Tested in Release. As per the fix (https://github.com/appsmithorg/appsmith/pull/12199), the behaviour is fine. 
https://www.loom.com/share/33c5c15a2c5142dfab396cc8b81ac330
Only after the menu option is closed, scrolling is allowed.
