### ISSUE TITLE
[Bug]:  Reset Widget on click resets all the input in a  Form Widget

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#11172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Add Different inputs in form widget

reset a widget on submit

All widgets get resetted

### Steps To Reproduce

https://user-images.githubusercontent.com/31691737/154027357-c3d1acf8-cc06-4f14-a9b8-40c8bc17d4ab.mp4

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope this is because you have marked resetWidgetOnSubmit as true in the button
