### ISSUE TITLE
[Bug]: Example snippet of Radio widget errors out

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Example snippet of Radio widget errors out when copy paste into the field

![image](https://user-images.githubusercontent.com/79509062/154115151-b0c572d0-f3c6-4d43-8347-c78d2b143415.png)

### Steps To Reproduce

1. Use the example expected structure of a Radio widget in the Options field and observe the error

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@ramsaptami the expected structure example if trying to show that it expects both integer and string. Its not a valid object. 

Do you agree? If so please close the issue

**Comment by Tooluloope** [comment]
There is an issue in the code inputted.
Changing the example structure would be fine

**Comment by ramsaptami** [comment]
Can we replace the example with a working snippet as is the case with most other widgets?

**Comment by somangshu** [comment]
Since we are giving the copy button, we should do that, The message that both are accepted is anyways conveyed from the structure. 

@Tooluloope we can take this forward
