### ISSUE TITLE
[Feature]: Allow users to upload and view excel sheet without a DB integration

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#11182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Users often want to just upload and view an excel sheet in the browser. They'd then like to modify the excel sheet to upload it to a database.

### Why should this be worked on?

https://community.appsmith.com/t/upload-an-excel-file-and-show-in-a-table/602

**Comment by somangshu** [comment]
@areyabhishek isn't this a common [datagrid scenario ](https://github.com/appsmithorg/appsmith/issues/1392)

**Comment by dilippitchika** [comment]
Closing this for now, it does look like a common data grid scenario.
