### ISSUE TITLE
[Bug]: Form widget should include the following widgets in data property when added in form

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#11188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The form widget does not include the multi-select, switch group widget selected values in form.data property. It only includes children widgets that expose the selected value in the `value`  key into the data property.
Input, Currency, Phone, select expose the entered/chosen value in `value`  property. But multi-select, switch group, etc are not exposing the `value`  property.

### Steps To Reproduce

1. Add a form widget in canvas
2. Add a multiselect widget in the form
3. choose a value on multiselect
4. form.data property doesn't have this value

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
**Items which are not supported in form.data but need to be supported are -** 
1. Treeselect
2. Switch group
3. Multi tree select
4. Multi select
5. Phone input and currency input are not shown when empty
6. Check box group
7. Audio recorder
8. Filepicker
9. Camera

**Comment by dilippitchika** [comment]
@Tooluloope @wmdev0808 this should be linked to #4182 and done immediately after that.

**Comment by jjagielka** [comment]
On top of it, containers prevent the widgets to be visible for the form data. If you group widget (which adds container in the background) widgets are removed from from data visibility. Similarly if you use tab widget in the form it won't be 'transparent'.

**Comment by dilippitchika** [comment]
@jjagielka sorry I didn't quite catch the request. Could you add a screen-recording for this?

**Comment by jjagielka** [comment]
https://user-images.githubusercontent.com/6282254/159896264-ee7f7ba9-d261-4160-b12a-9613cdc31a39.mp4

**Comment by dilippitchika** [comment]
Thanks for sharing this, this may be a bigger change in the form. I have created a new issue #12255 to track this.

**Comment by jjagielka** [comment]
I think both are connected. I suspect your implementations of muliti-select, checkbox group, etc.. are based on grouping widgets with a container, and that's why the values are not populated to the form data.

**Comment by dilippitchika** [comment]
@wmdev0808 please pick up this issue, estimate and add the suggested changes.

**Comment by wmdev0808** [comment]
@dilippitchika ,
- As we've already confirmed, Here are the widgets involved in the current scope:
1.Tree select
2. Switch group
3. Multi tree select
4. Multi select
5. Phone input and currency input are not shown when empty
6. Check box group
=========================================
> What should be done:
- Form data and associated widgets logic and  should be fixed so that the widgets above should be detected in the form.
- Fix on 5. by debugging.
- Add a Cypress test for the above fix
==========================================
> My estimate is 1
