### ISSUE TITLE
[Enhancement]: When app name is long on hover it displays 'Rename application' in View mode

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When application name is too long on hover it displays 'Rename application' in View mode. Ideally on hover it is right to display the full application name.

![image](https://user-images.githubusercontent.com/92293815/154211856-8a5bc09e-f340-4dd6-b836-ae0c238334f6.png)

### Steps To Reproduce

1. Go to any application and rename application to a very long name
2. Observe an ellipsis is added and on hover it shows 'Rename application'

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
This was more of a conscious decision @shwetha-ramesh. We want the action to be more visible in the edit mode, And looking at the view mode the behaviour looks appropriate. Let me know if you think otherwise, Closing this for now
