### ISSUE TITLE
[Bug]: server isn't verifying page unique names

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#11192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2022-02-14 at 19 39 04](https://user-images.githubusercontent.com/31691737/154201816-aa47541f-da0e-4479-ba6f-8816d6e86073.png)

### Steps To Reproduce

Open the same application in two tabs, click add page in both the tabs, refresh

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #14286
