### ISSUE TITLE
[Task]: Opening property pane should focus the widget name

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#11199]
From @somangshu 
> When you select a widget you need to use the mouse to start with keyboard navigation, I believe we have to reduce this click simply by focusing on the widget name as soon as the widget is selected.

Final decision:
- Focus on the first property whenever we click on the widget.
- When we add a new widget or when we paste a widget, focus on the widget name. (it should be editable only if we press space or enter otherwise it will be hard to other operations like delete, copy, paste etc,)

**Comment by vuiets** [comment]
Sounds good as long as we don't make it active and just focus on it.

**Comment by aswathkk** [comment]
@vuiets @somangshu @riodeuno 
If we make the widget name to be focused on opening the property pane, the following user flows are getting affected:
- Ability to delete the widget using the `delete` key.
- Ability to copy the widget using the `Cmd` + `C`.

When the user performs these actions, the focus will be on the widget name and these actions will be applied on the widget name rather than on the widget itself!

**Comment by yaldram** [comment]
I think in order to avoid the above scenarios we had the `click on F2 to focus on widget name`, rather than just `focus directly on the widgetname`.

**Comment by riodeuno** [comment]
@aswathkk @yaldram I was wondering if the widget name has two states:
- Highlighted state where we're not yet editing the name, just the field is selected.
- Focused state where we have the cursor, and can modify the entity name.
If we have these two states, we can make the default behaviour only highlight the name. This should free up the delete, cut and copy keyboard shortcut handlers.

**Comment by aswathkk** [comment]
What we decided on the last call is
- When a new widget is inserted into the canvas, focus on the widget name. This also encourages users to give a proper name for the widgets initially.
- When an existing widget is selected, focus on the first property in the property pane.
@vuiets Correct me if I'm wrong.

**Comment by vuiets** [comment]
Yes, that's right @aswathkk 

Came across another scenario on a user research call with @Nikhil-Nandagopal and @rahulramesha. User wanted to rename a widget on pasting it so adding that here
> When a widget is pasted, focus on the widget name. This makes it easy for the user to name it and reference it properly in bindings on other widgets.

**Comment by aswathkk** [comment]
I understand that we are making it easier for a set of users to rename the widget.
But there is another set of users who are getting affected by this:
- users who paste widgets accidentally
- users who DnD wrong widget to the canvas
we will be making it hard for them to delete the widget

**Comment by vuiets** [comment]
So @aswathkk we'll focus on the name but not make it active. 

Then one has to hit `Enter`/`Space` to make it active and rename the widget.

This way the other operations like deleting a widget, copying a widget, and cutting a widget using keyboard shortcuts can still be done.

**Comment by Sripriya93** [comment]
Working fine. Moving to done !

**Comment by Sripriya93** [comment]
Issue# https://github.com/appsmithorg/appsmith/issues/14265
https://www.loom.com/share/e82c783cf6b940608bbfd95a3cd9104b
When adding a new widget, its name is not getting focused if we are doing a reflow.
