### ISSUE TITLE
[Feature]:Hide shadows of hiddens  objects during page loading in deploy view

### ISSUE THREAD

**Issue by billyrudi** [appsmithorg/appsmith#11203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi, 
when i set visible = false in every objects it is not beautiful to see in deployed version during page loading
 the shadow of this object... 

### Why should this be worked on?

The end user , if the page spend some time to load ,  might get disoriented to see shadows of objects that not exixst. 
It is rigth only in designe time.

**Comment by Nikhil-Nandagopal** [comment]
@billyrudi this doesn't seem to be happening in the deployed version. Can you please share a video of this issue?

**Comment by billyrudi** [comment]
Please see this videa at the center bottom

https://user-images.githubusercontent.com/11408614/155348630-74e4c287-7b27-418d-a37f-413f04c77b7b.mov

**Comment by billyrudi** [comment]
tanks...

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal isn't this what "animate loading" switch is supposed to do? Are you aware if that's what this is about?

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika that property is to always disable the loading state. But here the problem is that the hidden elements are in a loading state

**Comment by dilippitchika** [comment]
Hey @billyrudi for the hidden widget, can you also disable "Animate loading" property? It will not show the shadow in this case. Please let me know if this doesn't help.

**Comment by billyrudi** [comment]
Hi, yes i have disabled also animate loading but the shadow apperas. Try with a long time page loading and you can see the problem.

**Comment by dilippitchika** [comment]
Let me get this investigated with the team

**Comment by dilippitchika** [comment]
@Tooluloope can you assign someone who has worked on "Animate loading" to investigate the above issue? 

CC - @somangshu @vivekverma2312

**Comment by Tooluloope** [comment]
@wmdev0808 Would you be able to triage this issue?

**Comment by dilippitchika** [comment]
@wmdev0808 can you leave a note on what is the proposed change you need to do to support this as well?

**Comment by somangshu** [comment]
- [ ] When the widget is not visible and animate loading is false - dont show widget or the skeleton
- [ ] When the widget is visible and animate loading is false - show the widget but not the skeleton
- [ ] When widget is visible and animate loading is true - show the widget and the skeleton
- [ ] when widget is not visible and animate loading is true - should not show the widget and skeleton

| Visible | Loading | ShowWidget | ShowSkeleton | 
| ---- | ---- | ----- | ----- |
| false | false | false | false |
| true | false | true | false |
| true | true | true | true |
| false | true | false | false |

cc @dilippitchika @wmdev0808 @Tooluloope

**Comment by billyrudi** [comment]
rigth!
