### ISSUE TITLE
[Bug]: Create a lock on datasource context cache to avoid multiple parallel connections from being created

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#11202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A single datasource on the server is expected to have a long-running connection that is reused till it expires. This connection context is retained in a map that acts as a cache between different execution calls. However, this cache is not synchronized and can hence create multiple connections that remain unused, and occupy the connection pool.

### Steps To Reproduce

Unsure of how this can be done so far, will need to mock parallel calls to server.

### Environment

Production

### Version

Cloud

**Comment by sumitsum** [comment]
@nidhi-nair can you please explain this line ? : `However, this cache is not synchronized and can hence create multiple connections that remain unused, and occupy the connection pool.`

**Comment by nidhi-nair** [comment]
@sumitsum Since `Hashmap` does not handle concurrent connections inherently, we'd need to create a `synchronized` lock around the cache. Multiple APIs access this map at the same time, and even though in terms of consumption we'll always get a valid connection, the cration of connections happens multiple times, and are possibly only closed the one time. Does this address your question?

**Comment by sumitsum** [comment]
Closed via https://github.com/appsmithorg/appsmith/pull/14348
