### ISSUE TITLE
[Feature]: Provide a way to modify the default branch for git

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#11223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today if user wants to update the default branch and delete the older branch there is no way to do that from Appsmith. Even though user can modify the same on remote the same will not be reflected in Appsmith UI. Also, deleting the default branch is not allowed today in Appsmith because we have default branch ids referenced nested in each resource.   

### Why should this be worked on?

This will be useful in scenarios when the default branch ended up in bad state due and user is unable to revert these changes somehow.

**Comment by hiteshjoshi** [comment]
We will need to communicate with the user about git default branch and changing that will also change your default branch inside the App. Syncing branch after git default branch change is necessary.

**Comment by hiteshjoshi** [comment]
- [ ] Better communication for updates on the default branch after sync etc.

**Comment by AnaghHegde** [comment]
Issues covered part of this 
- #11651 
- #11541

**Comment by AnaghHegde** [comment]
Closed via https://github.com/appsmithorg/appsmith/pull/11549
