### ISSUE TITLE
[Epic]: Responsive Viewport

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#11231]
## Objective:

Enable Appsmith devs to create responsive applications on Appsmith.

## Requirements:

| Title | User story | Comments |
| ---- | ----- | ------|
| | | |

## Queries

**Comment by somangshu** [comment]
- Here we want to be able to define the probably ways we could address this, Start gathering all the information required, Point out any platform changes we might need later.
- We should also think about the success metrics:

**Comment by gauravpay3ds** [comment]
is this available on local or cloud version ?

**Comment by Nikhil-Nandagopal** [comment]
@gauravpay3ds this is not yet available. We're working on this feature here #4630
