### ISSUE TITLE
[Docs]: SSO with OIDC

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#11232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Add documentation for configuring SSO using OIDC.

### Describe the improvement

We should add step by step guide to integrate with the following identity providers :
- Auth0
- Okta
- PingID

**Comment by vuiets** [comment]
@Pranay105 @jnikhila could we add this to our pipeline for next week. This requires us to configure settings on the identity provider(IdP) and on Appsmith. So each of the IdPs that are listed here, namely Auth0, Okta and PingID, need a separate page of their own.

@trishaanand and @ankitakinger can help with this.

**Comment by Pranay105** [comment]
I can take this up. Who is working on the first draft?

**Comment by hiteshjoshi** [comment]
Documentation for JWT tokens as well

**Comment by hiteshjoshi** [comment]
@Pranay105 were you able to get a grasp on the thoughts from Trisha and Ankita for this documentation to proceed?

**Comment by Pranay105** [comment]
@hiteshjoshi Yes, I'm working on the documentation.

**Comment by hiteshjoshi** [comment]
@Pranay105 can you help @vuiets to get on same page the first draft of the documentation.

**Comment by Pranay105** [comment]
@hiteshjoshi I have already written the documentation for SSO. It's the final review stage. You can have a look here -
[Auth0](https://docs.google.com/document/d/1Lk98J9wy2RzSUvK8OOydH09RgUVzJnIfchHBGwkkBNs/edit#)
[Okta](https://docs.google.com/document/d/1hKt26G2ydmxu5XsIv4jzk10bH23Zf2tWnF6sxHnsIt8/edit)
[PingID](https://docs.google.com/document/d/19cd7Iqtr-Zns4wnfI98KSx4xjRlQPSQrxDQPARLuYJk/edit#)
