### ISSUE TITLE
[Feature]: Increase drop-down box display speed

### ISSUE THREAD

**Issue by dschain** [appsmithorg/appsmith#11252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

**Release v1.6.10** 
When there are more than 1000 records in the drop-down box, the display delay time is very long, more than 5 seconds. It is hoped that this function module can be improved and the use efficiency can be improved.

![image](https://user-images.githubusercontent.com/44538731/154627523-6ddf2d03-d4b3-45a9-90fa-21ae5fe7ed90.png)

### Why should this be worked on?

Increase display speed

**Comment by Nikhil-Nandagopal** [comment]
@dschain the dropdown isn't meant to handle this many records at once. You can enable server-side pagination to deal with large amounts of data in the dropdown and bind the search of the dropdown to show the rows that you need

**Comment by Nikhil-Nandagopal** [comment]
@dschain you can fork this app to see how to achieve this
https://app.appsmith.com/applications/61fbdf232cd3d95ca414b805/pages/6215d4742882606a1df5c695

**Comment by dschain** [comment]
Invalid method. This function is more like conditional selection. After selecting options, it needs to query 1000 records of secondary options in the database, and then select from 1000 records of filtering.

**Comment by dschain** [comment]
I urgently need this function, which has a great impact on work efficiency.
