### ISSUE TITLE
[Bug]: Unable to launch local instance of Appsmith on Windows using docker

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to setup Appsmith on local by following steps present on documentation found at link: https://docs.appsmith.com/setup/docker

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/154628877-3effb582-75db-499e-aa48-22662d04b1d8.png)
![image](https://user-images.githubusercontent.com/79509062/154628957-178693d6-6dad-4ada-bb92-d90c87093c35.png)

### Environment

Production

### Version

Cloud

**Comment by sum35h** [comment]
It is working fine now. No issues.

**Comment by ramsaptami** [comment]
Closing this for now since it's working fine.
