### ISSUE TITLE
[Bug]: The remote URL details will be lost when user edit the git user config details before connecting to Git  

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The remote URL details will be lost when the user edit the git user config details before connecting to Git  
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/71bef533c96a49eab1489661d3d13635-00001.gif)](https://www.loom.com/share/71bef533c96a49eab1489661d3d13635)

### Steps To Reproduce

1. Add the remote url  
2. Under user setting section 
3. click on edit icon 
4. now under Git user config 
5. Edit the user name and email 
6. Now navigate back to Git connection pop up 
7. All the detailes are will be lost and user have to reenter all the details from Remote URL

### Environment

Production

### Version

Cloud

**Comment by abhvsn** [comment]
Reassigning this to the concerned person as this is a client-side state management

**Comment by RakshaKShetty** [comment]
The edit button is removed so cant test this flow
