### ISSUE TITLE
[Bug]: Broken app due to calling .filter() on element instead of array

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#11254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On dev.appsmith.com

![Screenshot-2022 02 18-11 50 27](https://user-images.githubusercontent.com/1573771/154629422-66a8f68f-f61b-43ed-aac1-6a927d1d90e8.png)
![Screenshot-2022 02 18-11 50 50](https://user-images.githubusercontent.com/1573771/154629419-168b1c18-055f-4b5c-9795-b52188903bce.png)

On app.appsmith.com
![image](https://user-images.githubusercontent.com/1573771/154630313-e84770cd-37a1-4d98-9523-881a2b9012d9.png)

### Steps To Reproduce

1. Click a dropdown with options.
2. Select an option.
3. Select same option again.

https://user-images.githubusercontent.com/1573771/154630032-779859aa-140d-4ed9-8163-7436342156bc.mp4

### Environment

Release

### Version

Self-Hosted

**Comment by rashmi-rai** [comment]
Not reproducible anymore.
