### ISSUE TITLE
[Bug]: Uncommitted changes shows up in the app even though user did not make any changes

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Connect an app to git and then open the app again after few days and notice un committed changes. 
Even for the git import feature this is happening. 

### Steps To Reproduce

Connect an app to git and then open the app again after few days and notice un committed changes. 
Even for the git import feature this is happening. 

### Environment

Production

### Version

Cloud

**Comment by hiteshjoshi** [comment]
@AnaghHegde to close discussion with @rahulramesha

**Comment by AnaghHegde** [comment]
Per discussion @rahulramesha  need to make the change so that the value does not get updated in widget. Issue #12290

**Comment by abhvsn** [comment]
We are seeing some other changes as well when user tries to connect the application when uses drag and drop way to build app
![Screenshot 2022-04-13 at 2 58 33 PM](https://user-images.githubusercontent.com/41686026/163145706-699f74f6-83f5-47ec-847b-5c308135ad1c.png)
