### ISSUE TITLE
[Bug]: Eval is throwing type error for empty array

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#11260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we receive the empty array as a response from the API and if the same is bounded to table or list widget we are getting `Value does not evaluate to array` eval error.

### Steps To Reproduce
- Create DB query with no data
- Bind the data to table or list widget
- Check the error in eval window

![image](https://user-images.githubusercontent.com/41686026/154646074-dab55e1f-1160-49de-8a6f-ccdd4fc21ed5.png)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@abhvsn this seems to be working. Can we get the actual response of the query here?

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we have no update
