### ISSUE TITLE
[Task] Generate report of all the evaluation processes

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#11263]
### Sub Eval process
 - createFirstTree
 - updateTree
 - overAll evaluation log
### Post Eval process
 - updateAutoComplete - (tern log)

**Comment by Rishabh-Rathod** [comment]
https://github.com/puppeteer/puppeteer/issues/1512#issuecomment-349784408 This might help.

**Comment by somangshu** [comment]
@Rishabh-Rathod can we close this; I guess we are tracking this in a different way now
