### ISSUE TITLE
[Task]: BE coders pod charter

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#11261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Simplify and extend the JTBD responses
- Classify into larger focus areas
- Clarify actionable items for long term goals
- Associate/disassociate to goals we have picked up in the short term

**Comment by rohan-arthur** [comment]
team charter: https://www.notion.so/appsmith/Team-Charter-Backend-Coders-Pod-20635fdce0774a7785b7beba90829d96
