### ISSUE TITLE
[Feature] authorization using current session data

### ISSUE THREAD

**Issue by sijad** [appsmithorg/appsmith#1127]
## Summary

ability to use current session data in queries or API calls.

## Motivation

this would make it possible to use current logged-in user's session data for authorization.

## Additional Context

having access to `Request` data (e.g. cookies, custom headers, etc) also can be useful too.

### example

```sql
select * from applications where owner_id = '{{CurrentSessionData.user_id}}'
```

**Comment by Nikhil-Nandagopal** [comment]
@sijad thank you for the idea. This is already possible today using {{ appsmith.user.email }}

**Comment by Nikhil-Nandagopal** [comment]
@sijad I'm closing this issue for the time being. Do reach out if you feel it doesn't solve the use case you had in mind
