### ISSUE TITLE
[Feature]: Provide option to delete branch with in the Application

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Just like any git hosting provider we should allow the users to delete branch. 

### Why should this be worked on?

Very basic and must needed feature for git
User will create multiple branches for testing developing branches and they would end up with stale branches

**Comment by AnaghHegde** [comment]
@vuiets @Debsourabh We need design for this feature.

**Comment by AnaghHegde** [comment]
@hiteshjoshi Design for this is pending.

**Comment by hiteshjoshi** [comment]
@vuiets @Debsourabh to post update with updated designs.

**Comment by RakshaKShetty** [comment]
UI Is not yet ready to test
