### ISSUE TITLE
[Docs] : Documentation for JWT tokens

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#11271]

**Comment by jnikhila** [comment]
@trishaanand / @Pranay105 - The first draft for [JWT documentation](https://docs.google.com/document/d/1W7m4Lq3ehKTcW40WCB8OPwY7q9ohUso-z9lfLAcNoQI/edit?usp=sharing) is available. Please go through the same and let me know if you think any changes are needed.

**Comment by trishaanand** [comment]
Closing this since JWT documentation is now available here : https://docs.appsmith.com/core-concepts/json-web-tokens-jwt
