### ISSUE TITLE
[Feature]-[300]: Include data format (Base64/Binary) information in Filepicker widget's files

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#11279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need a way to identify the data format of the `data` property in the entries of the `files` property in the filepicker widget.

### Why should this be worked on?

On many occasions, we find ourselves having access to only the `files` property, which doesn't have the information necessary to correctly parse or convert the data. So, having the explicit mention of the data format in the file object will help.

**Comment by dilippitchika** [comment]
@riodeuno we have a way to find out this using {{FilePicker1.files[0].type}} can you check if this is what you were referring to?

If yes, then was this detail not clear? Maybe we should consider renaming this to data_format.

**Comment by riodeuno** [comment]
@dilippitchika This issue talks about the format in which the uploaded file is encoded. For example, in the screenshot, the encoding is a base64 string, however, there is no way to reliably identify this today
<img width="290" alt="Screenshot 2022-03-15 at 1 33 59 PM" src="https://user-images.githubusercontent.com/103687/158332933-b1a09fad-0273-4c47-a883-a6b52da9ea15.png">
.

**Comment by dilippitchika** [comment]
@riodeuno thanks for adding more context.

Actionable - 
- Expose a dataFormat field for every file in the filepicker widget which contains the information if the data is "base64" or "binary" or "text".
- This field uses the value set from the data format field in the filepicker
![Screenshot 2022-03-29 at 10 48 25 PM](https://user-images.githubusercontent.com/19730984/160668903-f1fab669-69a8-4ec2-9f60-57a7fb0ce837.png)

**Comment by dilippitchika** [comment]
We need to check if this breaks any s3 queries or other cases with the backend team.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 150 |
| Effort (months)  | 0.5 |
