### ISSUE TITLE
[Task] Missing analytics events for Git Sync

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#11286]
There are a few missing FE events

For Connect funnel
* ‘Connect Git’ event for bottom bar click
* ‘Commit and Push’ button click event on Deploy modal
* ‘Last Deployed Preview’ click on Deploy modal

For Deploy funnel
* ‘Commit and Push’ button click event on Deploy modal
* ‘Last Deployed Preview’ click on Deploy modal

For Create Branch funnel
* Open branch popup event from bottom bar click on active branch name
* Create branch event in the branch popup
* Sync branches event in the branch popup

For Merge funnel
* ‘Merge Changes’ button click event on Merge modal

**Comment by hiteshjoshi** [comment]
@vuiets can you confirm if all events are added? If yes, lets close this.

**Comment by vuiets** [comment]
Did a quick check and notice some new events. I'll check this tomorrow and get back to you guys.

**Comment by IAmAnubhavSaini** [comment]
# Git Analytics

For Connect funnel

- ‘Connect Git’ event for bottom bar click (already done)
- ‘Commit and Push’ button click event on Deploy modal (already done)
- ‘Last Deployed Preview’ click on Deploy modal (already done)

For Deploy funnel

- ‘Commit and Push’ button click event on Deploy modal (repeated)
- ‘Last Deployed Preview’ click on Deploy modal (repeated)

For Create Branch funnel

- Open branch popup event from bottom bar click on active branch name (already done)
- Create branch event in the branch popup (already done)
- Sync branches event in the branch popup (already done)

For Merge funnel

- ‘Merge Changes’ button click event on Merge modal (already done)

## ‘Connect Git’ event for bottom bar click

```javascript
AnalyticsUtil.logEvent("GS_CONNECT_GIT_CLICK", {
  source: "BOTTOM_BAR_GIT_CONNECT_BUTTON",
});
```

## ‘Commit and Push’ button click event on Deploy modal

```javascript
AnalyticsUtil.logEvent("GS_COMMIT_AND_PUSH_BUTTON_CLICK",{
  source: "GIT_DEPLOY_MODAL",
	isAutoUpdate,
	isManualUpdate,
});
```

## ‘Last Deployed Preview’ click on Deploy modal

```javascript
AnalyticsUtil.logEvent("GS_LAST_DEPLOYED_PREVIEW_LINK_CLICK", {
  source: "GIT_DEPLOY_MODAL",
});
```

## Open branch popup event from bottom bar click on active branch name

```javascript
AnalyticsUtil.logEvent("GS_OPEN_BRANCH_LIST_POPUP", {
  source: "BOTTOM_BAR_ACTIVE_BRANCH_NAME",
});
```

## Create branch event in the branch popup

```javascript
AnalyticsUtil.logEvent("GS_CREATE_NEW_BRANCH", {
	source: "BRANCH_LIST_POPUP_FROM_BOTTOM_BAR",
});
```

## Sync branches event in the branch popup

```javascript
AnalyticsUtil.logEvent("GS_SYNC_BRANCHES", {
  source: "BRANCH_LIST_POPUP_FROM_BOTTOM_BAR",
});
```

## ‘Merge Changes’ button click event on Merge modal

```javascript
AnalyticsUtil.logEvent("GS_MERGE_CHANGES_BUTTON_CLICK", {
  source: "GIT_MERGE_MODAL",
});
```
