### ISSUE TITLE
[Task] Resizable pages container | Entity explorer. 

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#11284]
Typography changes.

**Comment by albinAppsmith** [comment]
@ramsaptami / @Parthvi12  Can we test this in DP?
DP - https://appsmith-git-feat-page-container-resize-get-appsmith.vercel.app/

**Comment by Parthvi12** [comment]
@albinAppsmith Can we preserve state when:
- User resizes the page section ,deploy and then come to edit mode.
- User resizes the page section ,close app and revisit app later.

**Comment by albinAppsmith** [comment]
@Parthvi12  Added this functionality

**Comment by Parthvi12** [comment]
@albinAppsmith Thanks, this is working as expected.
