### ISSUE TITLE
[Task] Communication about URL changes to existing users. 

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#11283]
Valid for both cloud and self hosted. 

This could just be a temporary popup box with message about new url formats and how they affect apps.

**Comment by RoopKrrish9696** [comment]
**Design Handoff File link :** 
https://www.figma.com/file/b3tHFXEoghB4xCbo6FIRnH/Manual-Updates---Clean-URLs?node-id=2%3A1

cc @arunvjn
