### ISSUE TITLE
[Feature]: conditional layouts/containers

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#11296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Defining layouts/widgets to be shown based on a specific condition.
(I'm using the tab container as it is convenient to demonstrate.)
![Screen Recording 2022-02-20 at 19 31 15](https://user-images.githubusercontent.com/66776129/154846405-d9fdbf3e-9dec-45ce-8b06-8c98140f36dd.gif)

But the idea is, for the end user. The same space in canvas can be occupied by a different container depending on the app state.

---

Yes, we do have `visible` property. But it only allows the developer to show/hide containers.
Not to switch between containers.

---

### Why should this be worked on?

The developers can develop apps that are more dynamic in nature.
This can also serve as a way to handle errors.

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk I believe this is possible using the tab widget. You can set the default selected tab and hide the tabs to achieve this
https://docs.appsmith.com/core-concepts/dynamic-ui/widget-visibility#dynamic-forms

**Comment by eco-monk** [comment]
Ahhhh, thanks.! I didn't know that was possible.
