### ISSUE TITLE
[Bug]: Pressing enter submits the form without password confirmation on the welcome screen for self hosted instances

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [appsmithorg/appsmith#11294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When logging in for the first time enter a password with out a confirm password and hit enter. This bypasses the confirm password.

### Steps To Reproduce

When logging in for the first time enter a password with out a confirm password and hit enter. This bypasses the confirm password.

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
Hi @MichaelLeeHobbs we don't have a confirm password field while signing up so I don't understand this issue. Could you please add more details

**Comment by MichaelLeeHobbs** [comment]
@Nikhil-Nandagopal First login of a new appsmith deploy

**Comment by Nikhil-Nandagopal** [comment]
@MichaelLeeHobbs great catch! Thanks for the information
