### ISSUE TITLE
[Feature]: grid list

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#11293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![image](https://user-images.githubusercontent.com/66776129/154844606-97e4c361-2304-490d-b7cf-fb7ebd87024f.png)

### Why should this be worked on?

To use in cases where grid list makes for a better UI. Instead of a vertical list/table.

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk this seems similar to #7256  so closing this in favor of that
