### ISSUE TITLE
[Bug]: List widget page size incorrect in certain situations 

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The issue is shown in the attached video.

The list widget has incorrect page size for certain height settings.  This leads to weird behaviour when using server-side pagination. For eg. If there is a simple query pulling records from DB. In total there are 4 records. It only shows 3 records in the list. You expect the 4th record to show on the 2nd page, but it doesn't show. 

If you increase the list widget height, this appears to solve the issue.  

https://user-images.githubusercontent.com/32227135/154901474-992314ce-e01b-44dc-95bc-43e7073935e8.mp4

 

### Steps To Reproduce

See the attached video below

https://user-images.githubusercontent.com/32227135/154900467-329e4295-8b56-4fd2-ae14-82af91c09ef6.mov

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@ashit-rath can you take a look at this. The container height is what I felt what was causing the problem here. The way we calculate the page size is not appropriate and hence the query is pull different number of rows for the user.

**Comment by ashit-rath** [comment]
@danciaclara The loom video that you shared, seems to have the server-side pagination disabled. I was able to reproduce just like your loom video but with server-side enabled it seems to work fine.
Can you provide some more context or steps to reproduce with the server-side enabled?

**Comment by Nikhil-Nandagopal** [comment]
@ashit-rath page size should work for both cases right?

**Comment by ashit-rath** [comment]
@Nikhil-Nandagopal Yes, for both cases the pageSize would change with the change of the height of the widget and item spacing.
