### ISSUE TITLE
[Docs]: Enhancing UI For Docs

### ISSUE THREAD

**Issue by AjRadwan** [appsmithorg/appsmith#11291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/datasource-reference/querying-google-sheets

### Describe the problem

Can we work on enhancing the UI for this 
I know it looks ok and it's fine but It can be improved 

![image](https://user-images.githubusercontent.com/43091820/154805339-ab81df45-04fd-4ee1-899c-4edb79ffaafd.png)
it looks

### Describe the improvement

**something like this without showing the scroller** 

![image](https://user-images.githubusercontent.com/43091820/154805376-5b772fdd-45a9-4cbb-830e-ea1d2d077500.png)

**Comment by Nikhil-Nandagopal** [comment]
@AjRadwan we use gitbook and so aren't in control of the documentation UI directly but thank you for your feedback!
