### ISSUE TITLE
[Docs] Add reference to node version and enhance CONTRIBUTING.md

### ISSUE THREAD

**Issue by avats-dev** [appsmithorg/appsmith#1130]
## Documentation Link 

- https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md
- https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md 

## Describe the problem

Instances where problems occur (based on what I faced):
- a contributor want to set up dev environment, but there are no such references in [contributing guide](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md).
- and when he reaches [here](https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md), he sets up everything and runs `yarn` and then see that it requires `node 10.16.3` which is nowhere mentioned in prerequisites. 

## Describe the improvement

A clear and concise description of the improvement.
- Link [`server` setup](https://github.com/appsmithorg/appsmith/blob/master/contributions/ServerSetup.md) and [`client` setup](https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md) guides to [contributing guide](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md).
- Add `node version` to prerequisites and add appropriate references to manage this, such as through `nvm`.

> I would like to work on this.

**Comment by jyash97** [comment]
Hey @avats-dev  

This will be a really good addition in the guide as this will help developers who are looking to contribute. For the node version & nvm, I have set up a PR already, check it over here: https://github.com/appsmithorg/appsmith/pull/1119
