### ISSUE TITLE
[Bug]: Discrepancy in record count of List widget on Browser refresh

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

List widget is bind with SQL query and should populate the exact record coming from query.
But here every time we refresh the browser it is observed that there is a loss of 1 record untill page changes in List widget
Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4ca748f9e3e0434696ea16c381b2a2b9-00001.gif)](https://www.loom.com/share/4ca748f9e3e0434696ea16c381b2a2b9)

### Steps To Reproduce

1. Add List widget on canvas
2. Bind SQL query with List widget like "**Select * from tableName limit {{List1.pageSize}} offset {{(List1.pageNo - 1) * List1.pageSize}};**"
3. After running the query, go back to canvas to make sure you see all the records in List widget
4. Refresh the browser and observe that there is a missing record

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
This exists in prod too. This is not a regression / release blocker. We have already created this issue based after a user reported in on discord. We know the problem here and are not working towards a resolution. #11299
