### ISSUE TITLE
[Bug]: Different shades of same color in List widget appears for different items

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Items background color for 1st item has correct color shade but all other items have light color which doesn't match with the color selected by user

![image](https://user-images.githubusercontent.com/95341241/154923291-fde6a07e-673a-4599-b48e-c5194060c5ec.png)

### Steps To Reproduce

1. Add List widget to the canvas
2. Change the Item Background color to Black for better visibility of issue ( Choose any color and observe)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
This is intended for the edit mode, Please check the view mode
