### ISSUE TITLE
[Bug]-[6500]:Inconsistency in naming actions

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#11303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an action from the new queries/js navigation, the actions are called `Query1`. When creating them from the datasources, they're called `Api1` in some cases (when the integration is not a DB). We should follow the same rules of nomenclature.

### Steps To Reproduce

https://user-images.githubusercontent.com/5298848/154915588-60a5b997-20c8-431c-bcf0-17c53f7b6b74.mov

### Environment

Production

### Version

Cloud

**Comment by akash-codemonk** [comment]
This seems to be an issue with the omnibar where the logic for creating an api is slightly different.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 6500 |
| Effort (months)  | 1 |

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 1 month seems quite high for this!

**Comment by Parthvi12** [comment]
https://user-images.githubusercontent.com/80334441/171801853-f8af37d7-086b-403a-a52d-212af1d20021.mov



Reopened as names are not consistent when we create actions from omnibar and that from datasource.

**Comment by akash-codemonk** [comment]
Fixed in https://github.com/appsmithorg/appsmith/tree/feat/graphql 
cc @AmanAgarwal041
