### ISSUE TITLE
[Bug]: Button group widget and Menu widget accepts duplicate options

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#11317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the button group widget accepts duplicates button and the menu button widgets also accept duplicate menu button 

<img width="1680" alt="Screenshot 2022-02-21 at 5 22 21 PM" src="https://user-images.githubusercontent.com/35128442/155266382-e1dbdbb7-0d52-4be8-9356-f6c482a06017.png">

### Steps To Reproduce

1. Launch appsmith app in release/Production environment 
2. Drag and drop Button group widget and menu button widget 
3. Open property pane and new buttons or sub-menu button 
4. Rename the newly added button or submenu button to any existing button names and see duplicate button name are accepted and no error message is displayed.

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@YogeshJayaseelan the screenshot wasn't uploaded can you upload it again?

**Comment by YogeshJayaseelan** [comment]
@dilippitchika Added screenshot

**Comment by dilippitchika** [comment]
@vasanth-appsmith how to indicate errors like this in this component?
Please take a look at the current behavior in the table widget for duplicates. I believe we could improve the error feedback here.
![Screenshot 2022-02-25 at 10 34 51 AM](https://user-images.githubusercontent.com/19730984/155657064-d0845dfb-f9e1-43e7-b3c3-4e6813eea3b1.png)


This is how it looks for the table widget

**Comment by momcilo-appsmith** [comment]
@dilippitchika Why is this a problem?

**Comment by SunnyTitus** [comment]
Extracted the below technical solution through ChatGPT. Hope this gives some direction

Technical Solutions: (ChatGPT)

Front-End Code (React):

ButtonGroup Component Update:

Update the ButtonGroup component to handle the validation logic for unique button names:import React, { useState } from 'react';

const ButtonGroup = () => {  const [buttons, setButtons] = useState([{ name: 'Favorite' }, { name: 'Add' }]);  const [error, setError] = useState('');

  const addButton = (name) => {    if (buttons.some(button => button.name === name)) {      setError('Button name must be unique');    } else {      setButtons([...buttons, { name }]);      setError('');    }  };

  return (    <div className="button-group">      {buttons.map((button, index) => (        <button key={index}>{button.name}</button>      ))}      <input        type="text"        onBlur={(e) => addButton(e.target.value)}        placeholder="Add button"      />      {error && <p className="error">{error}</p>}    </div>  );};

export default ButtonGroup;

Menu Component Update:

Update the Menu component to handle the validation logic for unique menu item names:import React, { useState } from 'react';

const Menu = () => {  const [menuItems, setMenuItems] = useState([{ name: 'Item1' }, { name: 'Item2' }]);  const [error, setError] = useState('');

  const addMenuItem = (name) => {    if (menuItems.some(item => item.name === name)) {      setError('Menu item name must be unique');    } else {      setMenuItems([...menuItems, { name }]);      setError('');    }  };

  return (    <div className="menu">      {menuItems.map((item, index) => (        <div key={index}>{item.name}</div>      ))}      <input        type="text"        onBlur={(e) => addMenuItem(e.target.value)}        placeholder="Add menu item"      />      {error && <p className="error">{error}</p>}    </div>  );};

export default Menu;

CSS for Error Message:

Ensure you have appropriate styling for the error message:
.error {
  color: red;
  font-size: 12px;
}



Back-End Code (Spring Boot):

Controller Update:

Update the controller to handle the validation logic if any backend validation is necessary:@RestController@RequestMapping("/api/widgets")public class WidgetController {

private Set<String> buttonNames = new HashSet<>();
private Set<String> menuItemNames = new HashSet<>();

@PostMapping("/addButton")
public ResponseEntity<String> addButton(@RequestParam String name) {
    if (buttonNames.contains(name)) {
        return ResponseEntity.badRequest().body("Button name must be unique");
    }
    buttonNames.add(name);
    return ResponseEntity.ok("Button added successfully");
}

@PostMapping("/addMenuItem")
public ResponseEntity<String> addMenuItem(@RequestParam String name) {
    if (menuItemNames.contains(name)) {
        return ResponseEntity.badRequest().body("Menu item name must be unique");
    }
    menuItemNames.add(name);
    return ResponseEntity.ok("Menu item added successfully");
}

}

**Comment by saicharan-zemoso** [comment]
Hello @Nikhil-Nandagopal @dilippitchika @YogeshJayaseelan , is this issue still open. can I try to solve this issue?

**Comment by Nikhil-Nandagopal** [comment]
@saicharan-zemoso I don't think this is a valid issue so I'm going to close it

**Comment by akshayvijayjain** [comment]
@Nikhil-Nandagopal , Even I had the same thought that this might not be a valid issue, but the UI and logic is already in place, therefore, we internally worked on this issue and will present pull request in few days, 

Request you to consider it once.
So it show Red border along the duplicate menu item, or duplicate button label, only logic piece was missing which will be there in the pull request. 

@saicharan-zemoso  you can create the draft pr, and explain the solution

**Comment by Nikhil-Nandagopal** [comment]
@akshayvijayjain would you be open to a quick chat next week? Here's my calendly
https://calendly.com/appsmith-nikhil/30min

**Comment by akshayvijayjain** [comment]
> @akshayvijayjain would you be open to a quick chat next week? Here's my calendly https://calendly.com/appsmith-nikhil/30min

sure, booked a slot!
