### ISSUE TITLE
[Bug]: Unable to import application with json file size > 1MB

### ISSUE THREAD

**Issue by abhijit-motorq** [appsmithorg/appsmith#11314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I export an application and the json file is greater than 1MB, I get `undefined is not an object (evaluating 'n.status')` when I try to import the json file as an application. From the developer tools, I found out the requests failed with HTTP error 413. The import is working fine for json file 934Kb, but fails for files greater than 1MB files.
 

### Steps To Reproduce

Import an application with json file size greater than 1MB.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@abhijit-motorq is it possible to share a sample JSON that we can try?

**Comment by abhijit-motorq** [comment]
[Archive.zip](https://github.com/appsmithorg/appsmith/files/8110864/Archive.zip)
This contains both working and failing json files.

**Comment by abhijit-motorq** [comment]
[Archive.zip](https://github.com/appsmithorg/appsmith/files/8113024/Archive.zip)

I have attached both import working and failing json files.

**Comment by abhvsn** [comment]
@abhijit-motorq I tried to import this on my end and working for both the files, can you try again by clearing your browser cache. Are you trying this on Appsmith cloud (app.appsmith.com) or self hosted instance? If on self-hosted instance what's the hardware specs?

**Comment by abhijit-motorq** [comment]
Sorry @abhvsn, it was an issue with my Nginx config on self hosted instance.
