### ISSUE TITLE
[Bug]: App viewer rights user able to see Admin's General & Members page

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User with app viewers right can see General & Members page of a different user when url is copy pasted to a different browser (refer video for walkthrough of steps)

https://loom.com/share/6734e316f5c446d1855dda5b7ec3a6d5

https://loom.com/share/e86f19a7113d4a7084fb1730f530636f

### Steps To Reproduce

1. Login with user A > Create Org ABC 
2.  Click on Share > Manager users > Invite users > Enter user B details and select App viewer role
3. Now copy this page URL and paste it in a different browser > Now in that browser login with user B credentials
4. Observe you are able to see General and Members page of User A.

### Environment

Release

### Version

Cloud

**Comment by trishaanand** [comment]
Not an issue today.
