### ISSUE TITLE
[Bug]-[5000]:Email address field should be in edit mode when share modal is opened up

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, a user needs to manually click on the input box to enter email address when the share modal pops-up. Would be better UX if the input box is already on edit mode so user can start typing if needed. 

### Steps To Reproduce

1. Click on share pop-up and observe the input box needs to be clicked on to be able to enter an email address.

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5000 |
| Effort (months)  | 0.5 |
