### ISSUE TITLE
[Bug]: Map correct collection ids for onPageLoad actions during import

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#11327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to export-import the application with onPageLoad action from actionCollection, imported applications onPageLoadActions `collectionsId` is not getting mapped correctly  

### Steps To Reproduce

1. Create JSObject with body 
```
export default {
	getData: async () => {
		const data = await Query1.run();
		return data;
	}
}
```
2. Attach a binding to table widget `{{JSObject1.getData.data}}`
3. Export the application
4. Import application and check the response field `layouts.layoutOnLoadActions` for getPageById API 

### Environment

Production

### Version

Cloud

**Comment by ramsaptami** [comment]
Causes issues when importing an app with JS objects and API's set to run on page load as seen in #11104 hence reopening the issue
