### ISSUE TITLE
[Bug]: Exporting App creates a Copy of one of the pages

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#11337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/92d8fb96c5e341dcb0ca2ace04a2c8b4-00001.gif)](https://www.loom.com/share/92d8fb96c5e341dcb0ca2ace04a2c8b4)

### Steps To Reproduce

1. Select an application with more than one pages in app.appsmith
2. Export the application
3. Import the same json 
4. Observer one of the pages has a copy created
5. Parent app pages should replicate & no duplicate copy of application should be created

### Environment

Production

### Version

Cloud

**Comment by yatinappsmith** [comment]
This issue would happen clone page takes a lot of time

**Comment by Aishwarya-U-R** [comment]
To be fixed as part of fix for - https://github.com/appsmithorg/appsmith/issues/11139
