### ISSUE TITLE
Update chart widget doc

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#11335]

**Comment by jnikhila** [comment]
@cokoghenun - could you please review and update the video as per new settings.

**Comment by cokoghenun** [comment]
Will do @jnikhila

**Comment by cokoghenun** [comment]
Needs video @cokoghenun

**Comment by Rishabhkaul** [comment]
Closing since this looks like its updated.

**Comment by jnikhila** [comment]
@cokoghenun - Is this completed?
