### ISSUE TITLE
[Bug]: List widget - When using pagination, no way to go back to previous page after reaching last page

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using server-side pagination on the list widget, if you click on the Next button after the last page with data, it shows "No data to display" and then there is no way to go back to the previous page and the list widget stays stuck on the no data page.

Uploading Screenrecording_20220222_084207.mp4…

.

### Steps To Reproduce

1. Connect data to a list widget and use server-side pagination
2. Go to the last page with data and click Next
3. It shows a page with the text "No data to display" 
4. Now there is no way to go back to the previous page

### Environment

Production

### Version

Cloud

**Comment by dsakaria16** [comment]
Hi guys any update on this?

**Comment by Nikhil-Nandagopal** [comment]
@dsakaria16 we haven't prioritised this issue yet. We're planning on tackling all List related issues next month
