### ISSUE TITLE
[Bug]: Pasting an async function does not mark it as async till an edit is done

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#11347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/12022471/155114822-47bec491-5a42-4e7e-a89c-a8a5c8a48bd8.mov

https://user-images.githubusercontent.com/12022471/155114858-54cd6e62-707f-44f1-be13-c35c687c46a5.mov

### Steps To Reproduce

Copy/cut an async function and paste it in the JS Editor

### Environment

Production

### Version

Cloud

**Comment by ramsaptami** [comment]
This is happening again hence reopening

**Comment by rohan-arthur** [comment]
not reproducible anymore
