### ISSUE TITLE
[Bug]: Navigating to home page before an app on view mode loads causes any errors triggered during page load to appear on home page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an app page takes long to load and user navigates to the home page before the page loads, then any errors that should show up inside the app starts showing up on the home page.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8091b25d5aec45d988832a8b4f82b5db-00001.gif)](https://www.loom.com/share/8091b25d5aec45d988832a8b4f82b5db)

### Steps To Reproduce

1. Go to `Old A-Force` app on Appsmith internal apps or https://app.appsmith.com/applications/61cd5be2a4437918c01f87af/pages/61cd8575a4437918c01f89b2
2. Load Community Issues page and before the page loads, navigate to home page and observe the errors pop-up on home page even though user is not on the app

### Environment

Production

### Version

Cloud

**Comment by riteshkew** [comment]
not reproducible in latest version v1.43
