### ISSUE TITLE
[Bug]: resetWidget does not work for FilePicker widget

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`resetWidget` fails to clear selected files in the file picker.

### Steps To Reproduce

Select a file and try to clear the widget.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Oh wow this re-opened again. @somangshu @dilippitchika @vivekverma2312 can we please fix this once and for all. This has happened multiple times

@pranavkanade can you please share an app that can reproduce this?

**Comment by dilippitchika** [comment]
@techbhavin can you take a look at this, is this same as https://github.com/appsmithorg/appsmith/issues/6124 which is closed? Please triage this and let us know.
