### ISSUE TITLE
[Bug] Clicking on appsmith logo causes undesirable page load.

### ISSUE THREAD

**Issue by pushkar1393** [appsmithorg/appsmith#1136]
## Description

There seems to be an issue with the routing whenever an `onClick` event is triggered by clicking on the appsmith logo. The routing seems to work normally when landing on the sign-in page at first. However, there seems to be an issue with the following scenario that I came across. 

### Steps to reproduce the behaviour:

- I signed in and then out of the organization. It came back to the login page. 
- I click on the app logo for the **first time** and it shows up a blank page, probably because the router is trying to route to` /applications ` but since the auth has been revoked it shows an empty page. 
- I click on the app logo for the **second time** and it actually shows me my dashboard  `/applications` for a good one second before it redirects me to the `/user/login` page with a notification that I am redirected because of unauthorized access.

<img width="1183" alt="Screen Shot 2020-10-12 at 1 34 01 AM" src="https://user-images.githubusercontent.com/31943620/95708909-7e7a3f80-0c2b-11eb-8ace-0bf5e5509089.png">

### Important Details
 - OS: [MacOSX]
 - Browser [Chrome]

**Comment by Nikhil-Nandagopal** [comment]
@pushkar1393 thank you for reporting this!

**Comment by loiscodes** [comment]
I'll take this

**Comment by Nikhil-Nandagopal** [comment]
👋 Hi @loiscodes,  I've assigned the issue to you :)
Hope you've had a chance to look at our [Contribution Guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md)

**Comment by loiscodes** [comment]
neat! I'll work on this now. Thanks

**Comment by loiscodes** [comment]
@Nikhil-Nandagopal The PR I created for this issue is passing all tests. If there is anything else that is needed, please let me know. Thanks!

**Comment by Nikhil-Nandagopal** [comment]
@loiscodes thank you! @hetunandu will review your PR
