### ISSUE TITLE
[Bug]: Default Container widget within the list widget should be hidden on the Entity Explorer

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Users are able to access the default Container widget within the list widget and manipulate its properties. And here, all properties work except the background colour.

<img width="1440" alt="Screenshot 2022-02-22 at 5 50 50 PM" src="https://user-images.githubusercontent.com/32227135/155255404-fc5c2d35-cce9-4111-9adb-1352b12482fb.png">
s

### Steps To Reproduce

1. Drag and drop a list widget on the canvas
2. On the entity explorer, under the list widget, select the container widget
3. Check the property pane to view its properties

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Good catch @danciaclara!

**Comment by somangshu** [comment]
@dilippitchika why is this in the icebox, we can address it I belive

**Comment by Nikhil-Nandagopal** [comment]
@somangshu why not allow this? #6858 needs it!

**Comment by dilippitchika** [comment]
My default logic is moving all list related items to icebox for now. We can take a look at it next week for triaging @somangshu.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal This way there are two places that allow the configuration for the container in the list widget, it might be confusing the dev.

**Comment by somangshu** [comment]
Regarding #6858 we could add a JS expression in List widget item style to achieve such a use case?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu it doesn't work becasue the list widget doesn't have access to currentItem, only its children do. So that is why this feature makes sense

**Comment by somangshu** [comment]
Understood @Nikhil-Nandagopal, in that case should the list widget property related to container be removed

**Comment by Tooluloope** [comment]
Closing in support of https://github.com/appsmithorg/appsmith/issues/6858

**Comment by dilippitchika** [comment]
Closing since it's opposite to #6858
