### ISSUE TITLE
[Bug]: Mobile responsiveness not supported in fluid width when app is embedded in iframe

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An app built on fluid width canvas is mobile responsive but when embedded in an iframe it loses this and stretches the widgets on the canvas.

![WhatsApp Image 2022-02-19 at 12 28 12](https://user-images.githubusercontent.com/32227135/155254549-922945b7-159d-4eac-a730-df8ccefb29b5.jpeg)
![WhatsApp Image 2022-02-19 at 12 26 45](https://user-images.githubusercontent.com/32227135/155254557-19c7d966-fc72-4308-979d-5ef3a199bb84.jpeg)
 

### Steps To Reproduce

1. Create an app on fluid width canvas
2. Check the app on different devices and it is responsive
3. Embed the app in an iframe. The app is no longer responsive

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@prsidhu we need to find out why the iframe dosent consider the or apply the layout styles

**Comment by prsidhu** [comment]
@somangshu Adding the following line to <head> solves the problem:

```<meta name="viewport" content="width=device-width, initial-scale=1">```

However, this is an external solution, as in beyond our control. How do you want to go about it?

**Comment by somangshu** [comment]
Great find 💯 , I suppose we will need to tell the user about this through our documentation. This is also a best practice I believe, correct if I am wrong there @prsidhu.

@Nikhil-Nandagopal @riodeuno what do you guys suggest.

**Comment by prsidhu** [comment]
@Nikhil-Nandagopal Inside the parent app where it is being embedded.

**Comment by Nikhil-Nandagopal** [comment]
Ok then this sounds good. Lets close it and inform the user and document it

**Comment by btsgh** [comment]
Tested and found the documentation updated added in the how-to-guides as per above fix.
