### ISSUE TITLE
[Bug]-[288]:MySQL datasource failing on application import

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#11385]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 75 |
| Effort (months)  | 0.25 |

**Comment by sumitsum** [comment]
I have not been able to reproduce the import related issue on either my local setup or release or prod. I have asked Satish to check and revert back if the issue still persists. 
Regarding the class cast exception - it occurs only when compiled / built using IntelliJ - it is not related to the actual issue reported by Satish, hence I will look into it separately.

**Comment by sumitsum** [comment]
Update:
Of the two issues reported intially:
* Issue with datasource not linking with action on git import has been resolved and not reproducible. 
* Issue with class cast exception is still seen when (a) compiled with IntelliJ (b) run with docker on local setup. 
Since the second issue is only seen with MySQL db, the team has decided to shift away to Postgres db for now to remove the blocker.

**Comment by rohan-arthur** [comment]
mysql users in 3 months: 500
(guess, because no event available) of these, users who also used import application, 15%: 75

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 75 |
| Effort (months)  | 0.25 |
