### ISSUE TITLE
[Bug]: The action selector from the property pane show the list of datasources.

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#11380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you select "Execute Query" on the actions selector from the property pane, with the list of all the queries/apis it also lists down all the data sources which you have created. When you select the data source it redirects to a new query flow taking the user away from the canvas.

Showing the list of data sources doesnt make sense in a list which is primarily used to bind queries/apis.  

![action selector - showing datasources not query](https://user-images.githubusercontent.com/92779003/155277677-7f49d6b0-077c-4a25-b546-99bff3b544b8.png)

### Steps To Reproduce

1. Add a button to canvas
2. Click on onCLick to select an action.
3. Click on "Execute a Query" 

### Environment

Production

### Version

Cloud

**Comment by mohanarpit** [comment]
@parth-appsmith @yaldram Quick question: Initially, we were showing the list of datasources in the list so that a user can create a query easily by clicking on the datasource. Hence, if the user hadn't created a query earlier, they have the option to quickly create it from this list. 

Are we now letting go of that functionality?

**Comment by yaldram** [comment]
@mohanarpit yes if in this Pull Request I have removed the Datasources list, so that functionality won't work anymore, you only have the option to create a `new Query`.

**Comment by parth-appsmith** [comment]
@mohanarpit the problem is with the arrangement and grouping of options. 
When the user selects "Execute a Query" option from the actions selector the primary goal has to be to show the list of of queries that the user can bind and not the data sources. The primary goal would be to bind a query to an action, where as even if the user clicks on a data source they get redirected to create a query flow which also doesn't seem to be a good interaction. 

Also we have a CTA called "Create a new query" which essentially does the same thing. 

Rather we should move the list of data sources inside the Create a new query option as another level of drop down and only the  list of queries when the user selects "Execute a Query".

**Comment by parth-appsmith** [comment]
@yaldram why did we close this issue, the problem has not been solved yet.
![image](https://user-images.githubusercontent.com/92779003/158319965-864304f0-1647-43a7-85ce-231f2d96566f.png)

**Comment by yaldram** [comment]
Hey @parth-appsmith, it is been merged in release branch after Q/A. It is not yet there in production yet. Will be there soon. I tested it on the latest release, it is working.
