### ISSUE TITLE
[Bug]-[8836]:Order of columns changes and hidden property is assigned to different column than previously selected

### ISSUE THREAD

**Issue by japrogramer** [appsmithorg/appsmith#11384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So I have a table who's columns might change and when they do,
it messes up the order and the visibility of the columns in my published app.

**To remedy this I filter each row and filter out the columns I'm not interested in
before passing it to the table.**

The problem is that because javascript doesn't have ordered dictionaries,
the logic that appsmith uses seems to depend on the order always being the same
instead of using the property name it seems to rally on the order almost as if it was
processing the data as if it was in an array. This seems to result on the order and
visibility of the columns changing each time the app is edited and thus affects each new deployment.

I'm aware of this issue but it is distinctly different because the error only happens when editing the app
https://github.com/appsmithorg/appsmith/issues/9635

### Steps To Reproduce

1. filter out columns from {{query.data }} helps if data has many columns

something like 
```
{{ query.data.map( ({wanted_columns, ...unwanted_columns})=> {
      return Object.assign({},  { wanted_columns,})
}) }}
```

2. publish app
3. edit app, changing order and column visibility
4. publish again
5. order and visible columns will change

### Environment

Release

### Version

Self-Hosted

**Comment by isaacrj** [comment]
I'm having this problem as well. 
In my case, I have the table connected to a MongoDB collection via a Query. 
As the documents in this collection have different properies, applying a filter to the query results in an array of objects with potentially different properties.
Each time the properties in the result array change, the columns in the table fall out of order and the visibility gets scrambled as well.

**Comment by areyabhishek** [comment]
@japrogramer @isaacrj Thank you for reporting this issue. We've reproduced this bug. It used to work before but a recent change seems to have introduced a regression.

**Comment by dilippitchika** [comment]
@Tooluloope can you triage this issue? Looks like it used to happen before.

CC @sbalaji1192 for tracking this in table v2.

**Comment by Tooluloope** [comment]
@vivekverma2312 @YogeshJayaseelan Could you help reproducing this issue?

**Comment by vivekverma2312** [comment]
@Tooluloope I observed some issue around visibility on changing the order of column on table widget.
https://watch.screencastify.com/v/73XxoRR6OqXu4KStwaPT

**Comment by dilippitchika** [comment]
@japrogramer @isaacrj can you both review the above comment and let us know if you are facing the same issue. If not, please provide us with a screen-recording of the issue

**Comment by isaacrj** [comment]
@dilippitchika I can confirm that this is definitely a part of the issue: the visibility of a column is tied to its position. It is not limited to visibility: it happens with any other column properties, at least when the change occurs due to a change in the property order of the documents retrieved from a data source.

**Comment by pranavkanade** [comment]
@dilippitchika this happens in both edit & deploy mode.
https://www.loom.com/share/44d7972449174a41a7df901645434327

**Comment by Tooluloope** [comment]
Thanks, @isaacrj @vivekverma2312

**Comment by dilippitchika** [comment]
@pranavkanade thanks for the video, really clear now

**Comment by somangshu** [comment]
## Stats
| Stats | Value |
| ---- | ----- | 
| Reach | 2209 | 
| Effort | 0.5 |
