### ISSUE TITLE
[Bug]:  MongoDB Query Command not Found.

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#11394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For MonogDB when we add a new Query, it throws an error - **No valid mongo command found. Please select a command from the "Command" dropdown and try again**. Even if the DropDown has `Find Document(s)` selected. We had to de-select and re-select the option, sometimes it fails on local.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/13429535/155314096-4fb7dce1-5151-4d8f-b58c-cf71adc7efeb.png">

You can also see this error on production, the query throws an error and in the browser console to can see the `.filter` error.

### Steps To Reproduce

1. Go to create a New Query for MongoDB.
2. Enter the Collection Name and run the Query.
3. Try to changing the `Command` dropdown.

### Environment

Production

### Version

Cloud

**Comment by yaldram** [comment]
On line 840 - `src/Components/ads/Dropdown.tsx` - selected of type `DropDownOption | DropDownOptions[]` is asserted - 
```js  
const selectedOptions = (selected as DropdownOption[]).filter(
   (option: DropdownOption) => option.value !== optionToBeRemoved.value,
);
```
Used on line No - 718 is causing the issue
```js
  isSelected
      ? () => props.selectedOptionClickHandler(option)
      : () => props.optionClickHandler(option)
```

**Comment by dilippitchika** [comment]
@yaldram can you add a heading to the bug?

**Comment by rashmi-rai** [comment]
Not reproducible anymore.

**Comment by rashmi-rai** [comment]
Fixed via https://github.com/appsmithorg/appsmith/pull/11632
