### ISSUE TITLE
[Bug]: Incomplete canvas loads when datasources URL is redirected on edit mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An incomplete canvas loads instead of actual navigate page when datasource, query or page properties URLs are redirected on new Clean URL's

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d913840cd4cc463bae9d0ef39ed888de-00001.gif)](https://www.loom.com/share/d913840cd4cc463bae9d0ef39ed888de)

This also happens when using the `navigateTo()` function
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/20b30d284fb34c939dde2d64b04abf3c-00001.gif)](https://www.loom.com/share/20b30d284fb34c939dde2d64b04abf3c)

### Steps To Reproduce

1. On release/prod, go to any of the above mentioned pages and copy slug from `/application...` onwards and paste after `https://appsmith-git-feat-betterurls-get-appsmith.vercel.app/`. Observe app open up with nothing on the canvas as seen in the video.

### Environment

Deploy Preview

### Version

Cloud

**Comment by arunvjn** [comment]
Fixed in the latest DP
