### ISSUE TITLE
[Task]: Add support for analytics events in theming backend

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Review the events in the doc: https://www.notion.so/appsmith/Theming-analytics-be0df0ef55ed4e6dae1a10c8e5353a1d
- Add support for analytics events needed

**Comment by dilippitchika** [comment]
@nayan-rafiq any update on this?

**Comment by nayan-rafiq** [comment]
@dilippitchika I didn't get a chance to work on it yet. I'll try to pick it up this week.
