### ISSUE TITLE
[feature]: [Table widget] clicking on a Interact-able cell (button, icon button) should not select the corresponding row.

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#11403]
Currently, we're propagating the click event on a button in a table cell to the parent row, which results in the row getting selected. As part of this issue, we need to stop propagating the click event. 
https://community.appsmith.com/t/multi-row-table-with-button-column/668

**Comment by jrvidotti** [comment]
+1 for this

**Comment by pranavkanade** [comment]
@sbalaji1192 will table v2 have the same issue?

**Comment by sbalaji1192** [comment]
@pranavkanade This has been fixed in Table v2. Clicking on button, icon button, and menu button will not select/unselect the corresponding row anymore.

**Comment by benthielker** [comment]
Is it possible to intentionally select the parent row of the button clicked?

**Comment by sbalaji1192** [comment]
@benthielker You can use the `Table.triggeredRow` property to access the parent row when a button is clicked. you need to bind some action to the button in order for the triggeredRow to get populated.
