### ISSUE TITLE
[Feature]: I should be able to get the structure behind a data source at any time

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#11408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The first time when I add a new query, I also get to see the structure under the datasource, so that I can see the entities (tables, buckets etc) under that data source, and can quickly select simple crud queries. This is nice.

However, I ran into this problem today when I wanted to add a query for my MySQL data source:
![Screenshot 2022-02-24 at 08 47 12](https://user-images.githubusercontent.com/94514895/155451531-0291a25c-0c60-4dfa-b68d-dd80e7e90713.png)

The timeout is fine, it is par for the course when dealing with communication between multiple systems over a complex network. However, I would like to have a way to initiate the "get structure" action if the default action fails for any reason. 

### Why should this be worked on?

Being able to see the structure helps me remain in Appsmith and visualise the model so that I can build my app more easily, rather than having to back and forth between applications for this.

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur I believe clicking the 3 dots and refresh does this
