### ISSUE TITLE
[Feature] HubSpot Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#11404]
HubSpot is an American developer and marketer of software products for inbound marketing, sales, and customer service.

Its products and services aim to provide tools for customer relationship management, social media marketing, content management, lead generation, web analytics, search engine optimization, live chat, and customer support.

## HubSpot API Current Status

HubSpot's whole API is composed of 10 different APIs. Each API has a set of Endpoints to manage Objects within that API.

Currently, HubSpot is developing **v3** of their APIs. Some Endpoints are only available under **v2**. Most docs of **v3** state that the APIs are subject to change.

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/1414f809-e067-4bea-830c-c4a15401f9a7)

## HubSpot API Hierarchy

The API Structure is roughly divided like this:

- [Analytics API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13030)
- [Automation API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13031) 
- [CMS HubDB API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/11984)
- [CMS Domains API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13026)
- [CMS URL Redirect API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13028)
- [CMS Source Code API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13029)
- [CMS Performance API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13039)
- [Conversations](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13032)
- [CRM API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/11982)
- [Events API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13033)
- [Marketing API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13034)
- [Files API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/11983)
- [Settings API](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/12151)
- [Webhooks](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13035)

Below is the status (as of 2022-02-23) of the endpoints of each section (at the moment the documentation uses v3 as point of reference).

**Analytics API**

| Endpoint                 | Status            | Notes |
| ---                      | ---               | ---   |
| Reporting                | Under Development |       |
| Custom behavioral events | Beta              |       |

**Automation API**

| Endpoint                  | Status            | Notes |
| ---                       | ---               | ---   |
| Create & Manage Workflows | Under Development |       |
| Custom Workflow Actions   | Stable            |       |
| Custom code actions       | Not an API        |       |

**CMS API**

| Endpoint      | Status         | Version   | Notes |
| ---           | ---               | ---   | ---   |
| Templates     | Under Development |  v2     |        | 
| Layouts       | Under Development |  v2     |       | 
| Blogs         | Beta              |  v3     |       | 
| Media Bridge  | Beta              | v1      |       | 
| Pages         | Beta              |  v3     |       | 
| HubDB         | Stable            |   v3    |       | 
| Site search   | Beta              |  v3     |       | 
| Domains       | Stable            |  v3   |       | 
| URL redirects | Stable            |  v3     |       | 
| Performance   | Stable              |  v3     |       | 
| Content audit | Beta              | v3      |       | 
| Source Code   | Stable            |  v3     |       | 

**Conversations**

| Endpoint               | Status     | Notes    |
| ---                    | ---        | ---      |
 |Inbox and messages  | Beta|  |
| Chat Widget SDK        | Not an API | SDK Only |
| Visitor Identification | Stable     |          |

**CRM API**

| Endpoint             | Status | Notes |
| ---                  | ---    | ---   |
| Contacts             | Stable |       |
| Companies            | Stable |       |
| Deals                | Stable |       |
| Tickets              | Stable |       |
| Feedback Submissions | Beta   |       |
| Products             | Stable |       |
| Line items           | Stable |       |
| Quotes               | Stable |       |
| Custom Objects       | Stable |       |
| Calls                | Beta   |       |
| Email                | Beta   |       |
| Meetings             | Beta   |       |
| Notes                | Beta   |       |
| Tasks                | Beta   |       |
| Search               | Stable |       |
| Imports              | Stable |       |
| Owners               | Stable |       |
| Associations         | Beta   |       |
| Pipelines            | Beta   |       |
| Properties           | Stable |       |

**Events API**

| Endpoint        | Status            | Notes |
| ---             | ---               | ---   |
| Web analytics   | Beta              |       |
| Email analytics | Under Development |       |
| Tracking code   | Not an API        |       |
| Cookie Banner   | Not an API        |       |

**Marketing API**

| Endpoint                 | Status            | Notes |
| ---                      | ---               | ---   |
| Marketing Events         | Stable            |       |
| Marketing Emails         | Under Development |       |
| Transactional Email      | Stable            |       |
| Ecommerce Bridge         | Under Development |       |
| Subscription Preferences | Stable            |       |
| Marketing calendar       | Deprecated        |       |
| Social Posts             | Deprecated        |       |
| Forms                    | Beta              |       |
| Lists                    | Under Development |       |

**Files API**

| Endpoint | Status | Notes |
| ---      | ---    | ---   |
| Files    | Stable |       |

**Settings**

| Endpoint | Status | Notes |
| ---      | ---    | ---   |
| Users    | Stable |       |

**Webhooks**

| Endpoint | Status | Notes |
| ---      | ---    | ---   |
| Webhooks | Stable |       |

## Integration Scope

Considering preliminary review of the Docs and what seems to be most useful for HubSpot and Appsmith users, we could start with the **CRM API** (only Stable APIs). These seem to cover the most common use cases of HubSpot Integrations.

The following points are up to discussion:

- Should we only implement v3 Stable actions?
- What actions will be most used by users?

Feedback from HubSpot users is welcomed so that we can make the right decision on how to go forward with this.

## Developer Setup

1. [Create a HubSpot Developer Account](https://app.hubspot.com/signup-v2/developers/step/join-hubspot?hubs_signup-url=developers.hubspot.com/get-started&hubs_signup-cta=developers-getstarted-app).
2. [Create a Test Account](https://developers.hubspot.com/docs/api/creating-test-accounts).
3. [Set up your API Credentials](https://knowledge.hubspot.com/integrations/how-do-i-get-my-hubspot-api-key?_ga=2.80465495.1545340635.1575915958-500942594.1573763828).
4. [Run a test request to the Contacts Endpoint](https://developers.hubspot.com/docs/api/crm/contacts).

## References (Useful Links)

- [Understanding the CRM](https://developers.hubspot.com/docs/api/crm/understanding-the-crm?_ga=2.21847609.341006870.1586180142-500942594.1573763828)

- [HubSpot API reference documentation](https://developers.hubspot.com/docs/api/overview)

**Comment by felixsuarez0727** [comment]
Need to continue to next sprint.

**Comment by felixsuarez0727** [comment]
HubSpot CMS Source and HubSpot CMS Performance are removed from the scope of this task. The first one require changes in SaaS Ap that will addressed in next sprint.  The second one will be deprecrated.

**Comment by yatinappsmith** [comment]
added testscases to individual hubspot tasks

**Comment by nidhi-nair** [comment]
Closing in favour of #15969 , created that issue as an epic without being aware of this existing issue.
