### ISSUE TITLE
[Bug]: GraphQL Query Post Behavior Error, Inconsistent

### ISSUE THREAD

**Issue by ClarksonCote** [appsmithorg/appsmith#11407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a GraphQL instance accessible through a POST endpoint.  I have made the endpoint accept `application/graphql` content-types to bypass another issue I've been encountering with Appsmith using `application/json`

There is an odd behavior where placing the raw query text within the body works, but storing that within a string variable and referencing that variable does not work.

Looking at the logs, what is sent in both cases, according to Appsmith, is identical. There are no differences shown there, which is the perplexing part of this issue that leads me to believe it's not user error.

### Steps To Reproduce

With my GraphQL endpoint and the `content-type` headers set to `application/graphql`

Case 1: Place the raw text into the body of the POST and submit.
Body: `{ metadatarecord ( limit: 10 ) { assignedId uploadTime } }`
Log Output Snippet of Request Sent: 
```
"request":{
"body":"{ metadatarecord ( limit: 10 ) { assignedId uploadTime } }"
"headers":[...]
```
Status: Works

Case 2: Place the raw text into a string variable `queryString`, reference that string variable in the body of the POST and submit.
Variable assignment code:
```
var queryString = "{ metadatarecord ( limit: 10 ) { assignedId uploadTime } }";
storeValue('queryString', queryString);
```
Body: `{{appsmith.store.queryString}}`
Log Output Snippet of Request Sent:
```
"request":{
"body":"{ metadatarecord ( limit: 10 ) { assignedId uploadTime }"
"headers":[...]
```
Status: Fails with Syntax error returned from endpoint

In each case, Appsmith is showing an identical body submission in the request area of the logs, yet Case 1 works, and Case 2 doesn't. If I had to guess, there's actually two sets of double quotes wrapping the query text, but AppSmith doesn't show that.

If I try to use `{{JSON.stringify(appsmith.store.queryString)}}` then I do see two sets of quotes in the body from the logs, i.e.
`"body":""{ metadatarecord ( limit: 10 ) { assignedId uploadTime }""`

### Environment

Release

### Version

Self-Hosted

**Comment by rashmi-rai** [comment]
@ClarksonCote Try running your query with smart substitution on. You will find a checkbox for the same in the settings tab. If issue still persists share screenshot of the error.

**Comment by ClarksonCote** [comment]
@rashmi-rai I tried that just now. It appears to have the same behavior, I receive an invalid syntax message even though the Body looks identical to when I submit the raw text in the body without a reference to the appsmith.store variable...

`"body":"{ metadatarecord ( limit: 10 ) { assignedId uploadTime } }"`

**Comment by ClarksonCote** [comment]
@rashmi-rai @Nikhil-Nandagopal are there any other updates here? This is a blocker for us on a very high priority effort. I understand you have your own priorities too, of course, but if this is potentially an easy thing to fix at AppSmith, it would be great to have the fix sooner rather than later.

**Comment by ClarksonCote** [comment]
@nidhi-nair the original issue referenced above did have smart substitution turned OFF. I only turned it on after @rashmi-rai suggested that above, on this post: https://github.com/appsmithorg/appsmith/issues/11407#issuecomment-1057759745

**Comment by nidhi-nair** [comment]
I see, do you think you could share screenshots of your configuration? Or connect with us in Discord for a more synchronous resolution?

**Comment by ClarksonCote** [comment]
@nidhi-nair is it possible to just setup a video call to show you? I could even do so right now.

**Comment by nidhi-nair** [comment]
Yes that works, please give me 10 minutes, I'll be back with a meeting link. :)

**Comment by ClarksonCote** [comment]
Thank you

**Comment by nidhi-nair** [comment]
Closed via resolution on call. Turns out the smart substitution config wasn't updated on the API. This is a platform level bug that we will need to investigate. Unfortunately haven't been able to reproduce it so far at my end.
