### ISSUE TITLE
[Bug]-[2960]:MongoDB update query is not accepting valid value (an array) in update field

### ISSUE THREAD

**Issue by mojtab23** [appsmithorg/appsmith#11419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This query is valid for MongoDB 4.2+ 
```
db.getCollection('user').updateOne(
    {"_id":"1"    },
    [{"$set":{"newField":"$name"}}]
)
```
And in order to work correctly the `$set` part needs to be in an array.
But when we try to do something similar via Appsmith, It throws an error:
![Screenshot 2022-02-24 145332](https://user-images.githubusercontent.com/5852362/155516594-7c9beeec-ecd0-4088-a2ae-6bdeb7495b5e.png)

### Hint
https://github.com/appsmithorg/appsmith/pull/12241#discussion_r844997566

### Steps To Reproduce

Like the Image above:
1. Create an update query in a MongoDB datasource
2. Enter an update statement in array form like this one `[{"$set":{"testField":"$status"}}]`
3. It fails when you run the query with this error: ```Execution failed with status 5005
No valid mongo command found. Please select a command from the "Command" dropdown and try again ```

### Environment

Production

### Version

Cloud

**Comment by devnamrits** [comment]
Hi @Nikhil-Nandagopal @mojtab23, can you please assign it to me?? I want to resolve this issue.

**Comment by Nikhil-Nandagopal** [comment]
@devnamrits thank you for your enthusiasm. I'd like to direct you to have a look at our contribution guidelines and start with a few good first issues before tackling issues like these :)

**Comment by devnamrits** [comment]
Thank you @Nikhil-Nandagopal for your kind advice. I'll be picking a few more good first issues and then level up the challenges.

**Comment by devnamrits** [comment]
Thank you @mojtab23  for assigning me this issue. Will go ahead and accomplish this.

**Comment by devnamrits** [comment]
@mojtab23 I've created PR for this issue. Can you please review it?
cc: @Nikhil-Nandagopal

**Comment by rohan-arthur** [comment]
Mongo 6m usage: 1477
Consider 25% affected users: 370

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 370 |
| Effort (months)  | <<number>> |

**Comment by rohan-arthur** [comment]
@sumitsum what's going on with [this](https://app.zenhub.com/workspaces/data-integration-pod-6322a759b3296d249ce5c4ed/issues/appsmithorg/appsmith/12241) PR? Do we only need to add a test case? If yes, maybe this will be a quick change?

**Comment by sumitsum** [comment]
@rohan-arthur the PR also has a comment for making certain changes to the code, which has not been done yet. So basically two things pending - (1) code change requested via comments (2) JUnit TC.

**Comment by amogh2019** [comment]
Could someone please assign this issue to me?
Have raised PR #17732 for the same.

**Comment by sumitsum** [comment]
@amogh2019 assigned the issue to you.

**Comment by sumitsum** [comment]
Re-opening the issue since manual QA has not been performed since this was an exeternal PR and QA had reported some issue with the `local_testing.sh` script before. This issue should be closed once manual testing has been done.

**Comment by amogh2019** [comment]
Should it be assigned to someone else?

**Comment by sumitsum** [comment]
@amogh2019 we will take care of this internally. I am hoping this issue remaining open should not be a problem wrt to the Hacktoberfest contributions.

**Comment by theparthacus** [comment]
@rlnorthcutt, for Hacktoberfest considerations.
