### ISSUE TITLE
[Bug]: Modal Widget scroll not working

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The scroll is not working in the modal widget

### Steps To Reproduce

Fork following app - 
https://app.appsmith.com/applications/62174f288a51871ac43aa737/pages/62174f288a51871ac43aa73a

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Adding this to HPI - @Tooluloope please get this triaged and estimated.
