### ISSUE TITLE
[Feature]: Icon Button Widget - the Icon and Button Color property should have JS option.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![Screenshot 2022-02-24 at 6 42 07 PM](https://user-images.githubusercontent.com/13262095/155530833-4c6f82ce-6d97-447b-a129-e72e045e995c.png)
Users should be able to change the values of the Icon and Button Color property based on stat values.

### Why should this be worked on?

User request on the intercom - 
How can I change the icon in your stats box based on a certain value? For example, I will attach an image. I count the amount of bags yesterday and today, if the difference is a positive % I'd like a green icon with an upwards arrow. If it is a negative % I'd like a red icon like the one in the attachment
<img width="472" alt="Screenshot 2022-02-24 at 6 46 55 PM" src="https://user-images.githubusercontent.com/13262095/155531201-bdd51e2b-b7c4-4300-95c6-e956bfb95ac7.png">
.

**Comment by dilippitchika** [comment]
Very small change but linked to #11142
