### ISSUE TITLE
[Bug]: On Login only the first parameter passed in url persists

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

When passing parameters in URL, only the first one persists. So, if you have ?embed=true&abc=xyz only the embed parameter will persist. On the other hand, if you have ?abc=xyz&embed=true, then the abc parameter will persist.

### Steps To Reproduce

The issue was flagged by a user on discord. https://discord.com/channels/725602949748752515/760761686549463060/946323545796009985

### Environment

Production

### Version

Cloud - Appsmith v1.7.9-SNAPSHOT

**Comment by pranavkanade** [comment]
@Nikhil-Nandagopal @vuiets

**Comment by vuiets** [comment]
@hiteshjoshi this likes like a low effort solve. Can we get this fixed?

**Comment by Nikhil-Nandagopal** [comment]
Yeah lets please solve this. It's such a small issue and has been blocking the user

**Comment by lublak** [comment]
I have the same issue with the new url system (named urls).
Not the first, for me its the "embed".

```
http://appsmith.intranet.local/applications/625427bf877c4319d858c63f/pages/625427c0877c4319d858c642?tab=tab1&embed=true
```
to
```
http://appsmith.intranet.local/app/test/page1-625427c0877c4319d858c642?embed=true
```

**Comment by codedmind** [comment]
This still happen... in version 1.7

**Comment by hiteshjoshi** [comment]
@RakshaKShetty can someone confirm this on version 1.7 and debug why its happening?

**Comment by codedmind** [comment]
Still happens in v1.7.5

**Comment by pranavkanade** [comment]
@hiteshjoshi can we please prioritize this?

**Comment by hiteshjoshi** [comment]
@pranavkanade , @Parthvi12 tested it and could not replicate it. Can you redirect us to the application you are testing? That will be better point to start.

**Comment by codedmind** [comment]
@hiteshjoshi i share a loom with @pranavkanade in discord.

**Comment by codedmind** [comment]
Any news?

**Comment by hiteshjoshi** [comment]
Hey, @codedmind we are still looking into it. And will keep you posted sometime the next week.

**Comment by eco-monk** [comment]
Created an app that summarizes the issue
https://app.appsmith.com/app/pass-params/home-62da454aa7d0d33f843d9272

**Comment by eco-monk** [comment]
We intentionally persist only `branch` and `embed` parameters upon navigation.
([code](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/entities/URLRedirect/URLAssembly.ts#:~:text=//%20not%20persisting%20the,%3D%20existingParams%3B))

**Comment by eco-monk** [comment]
@codedmind, the login issue is solved.
https://www.loom.com/share/559f06e868e04d72a46807e806548439

What we're looking at right now, is a completely different issue. (persisting params on calling `navigateTo`)
Created another issue for this #15390.

This helps avoid confusion when looking at comments/PR's etc...
