### ISSUE TITLE
[Bug]: Git connect fails when the repo contains yml files

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user tries to connect a repo(gitLab or any) contains .yml file connect is failed. `.yml` files are used for CI purpose and we should allow such scenarios.

### Steps To Reproduce

Create a repo in gitlab and choose empty/blank repo
Notice `.yml` CI file added to repo
Now try to connect to the repo and connect fails

### Environment

Production

### Version

Cloud

**Comment by pranavkanade** [comment]
We also need to support, `yaml` files

**Comment by pranavkanade** [comment]
@nayan-rafiq @riteshkew  This bug has resurfaced. 
<img width="301" alt="Screenshot 2023-11-29 at 1 08 15 PM" src="https://github.com/appsmithorg/appsmith/assets/13262095/7df6e00d-a1ea-4487-be24-ccf372e98b73">
<img width="665" alt="Screenshot 2023-11-29 at 1 08 11 PM" src="https://github.com/appsmithorg/appsmith/assets/13262095/d054dbc6-381f-4a9f-9054-e99862010441">
