### ISSUE TITLE
[Bug]: File Upload flow causes failures for base64 type

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Uploading files using binary as a stream of data instead of base64 because it causes performance problems and leads to multiple failures. - Reported from client(KB)

### Steps To Reproduce

1. Add a filepicker widget
2. Upload small and large base64 and binary files
3. Understand if the data entry and data retrieval process are easy or hard.

### Environment

Production

### Version

Cloud

**Comment by j2bd** [comment]
Hello, 
Indeed, I can't get the base64 content of the files that are picked with the FilePicker...
Hope this bug will be quickly patched ;) 
Thanks & Regards,

**Comment by Nikhil-Nandagopal** [comment]
@j2bd can you tell us a bit about your issue? To which datasource are you trying to upload the file? What is the error you're seeing?

**Comment by j2bd** [comment]
Hi @Nikhil-Nandagopal 

With one of my app, filepicker was used to upload files on another webapp by API using base64 content. 
Till now, it worked well.
But, I can't get anymore the content of my file as a base64 string via the properties of the widget ( FilePicker1.files[0].data ...)

Thanks for your help,

**Comment by Nikhil-Nandagopal** [comment]
@j2bd this is a different issue that we were able to resolve so I'm closing it. Can you share the error you're seeing?
