### ISSUE TITLE
[Bug]: JsEditor unexpected parse error for comment

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#11458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/1337557c5b9648ac9f370da6d4defd4a-00001.gif)](https://www.loom.com/share/1337557c5b9648ac9f370da6d4defd4a)

The above recording shows the error

### Steps To Reproduce

As it was not easily reproducible, we could re-use @Rishabh-Rathod application - https://app.appsmith.com/applications/61e7ef0ceb0501052b9fef37/pages/61e7ef0ceb0501052b9fef3b/edit/jsObjects/61e7ef13eb0501052b9fef52

1. Open the above link. ( make sure you have application access )
2. Edit the comment line, like shown in the video to reproduce the issue.

### Environment

Production

### Version

Cloud

**Comment by ohansFavour** [comment]
This bug is introduced when we unescape a script containing a comment that has "\\n" or "\\r". This doesn't happen on new Apps (`evaluationVersion > 1`).

**Comment by ohansFavour** [comment]
Yes, it should.
