### ISSUE TITLE
[Bug]: [List widget] clicking on child widget (button etc) should not trigger `onListItemClick`.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When there is a button widget inside a list, clicking on the button triggers `onClick` of the button and it also triggers `onListItemClick` of the List Widget

### Steps To Reproduce

here is the sample app (please fork it)- https://app.appsmith.com/applications/62189b47445a8d746a05f768/pages/62189b47445a8d746a05f76b

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Will triage this with list issues, @somangshu can you check if this can be picked up independent of list issues though?

**Comment by st-trade** [comment]
Had this issue

**Comment by Nikhil-Nandagopal** [comment]
@st-trade sorry, you faced this issue. We'll be solving this soon

**Comment by Tooluloope** [comment]
Closing, duplicate of https://github.com/appsmithorg/appsmith/issues/9568

**Comment by Tooluloope** [comment]
Closing, duplicate of https://github.com/appsmithorg/appsmith/issues/9568
