### ISSUE TITLE
[Bug]: Numeric input widget and Appsmith store interaction bug

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#11466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This video shows a peculiar bug occurring in certain circumstances when using two numeric input widgets to show the interaction between an addition to a base value and the sum of the addition and the base.

https://user-images.githubusercontent.com/142613/155872452-3717c720-94fa-4781-bbdb-06863dbf29dd.mp4

The first input, Adjust, holds the value of an addition to a base value. The second input, Final, holds the sum of the base and the adjustment. When the user changes Adjust, Final is updated using the Appsmith store, and vice versa when the user changes Final, Adjust is updated.

This works as expected most of the time, but I have found that when the value of one of the widgets is changed and then the other widget is changed in the "opposite direction", the first change of the second widget is not handled correctly. It seems to be essentially ignored, or there is a timing issue between the widget value changing and the call to storeValue().

As I am using "linked" inputs like this in several places in my apps, I'd really like to see a fix for this. :pray:

### Steps To Reproduce

I'm uploading the demo app. Change the extension, Github doesn't like JSON uplaods... :scream: Install and fiddle with the inputs :wink: 

[Numeric input interaction bug.txt](https://github.com/appsmithorg/appsmith/files/8148238/Numeric.input.interaction.bug.txt)

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
@zzgvh Appsmith's `storeValue()` is an async function and should not be used to update widget properties. You can try binding a widget property eg: `Input1.value` or a JS object function that returns a result eg: 
```
export default {
	calculate: () => {
		return Number(CategorySlider1.value) + Number(CategorySlider2.value)
	}
}
```

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 while that is true, this should still have worked and seems like a bug in the platform

**Comment by zzgvh** [comment]
Also I'd like to point out that, as far as I know, I have to use the Appsmith store to allow me to "link" the data in the two widgets. Changing one value adjusts both widgets, and the user can choose to change either one of the widgets. This cannot be accomplished by referring to just the widget's values as it results in a circular dependency.

**Comment by bharath31** [comment]
@zzgvh Nikhil and I had an internal discussion. It appears that you are expecting `onTextChange()` event to be triggered based on a system event `storeValue()` due to binding. I'd like to clarify that all event handlers are triggered only on user events and not on system events. This is why store changes from one input widget are not propagated to another on your app. 

### Here's an implementation that works: 

Link to sample app- https://app.appsmith.com/app/complex-store-updates/incorrect-634528f589020c7ac296b7dc

#### Default Values: 

1. AdjustInput: 
```
{{appsmith.store.adjust_value}}
```
2. FinalInput: 
```
{{appsmith.store.final_value}}
```

####  onTextChanged Values: 

1. AdjustInput: Execute JS function 
```
export default {
	store: async() => {
		await storeValue("final_value", Number(Input1.text) + Number(basetext.text))
		await storeValue("adjust_value", Number(Input2.text) - Number(basetext.text))
	}
}
```

2. FinalInput: Execute JS function
```
export default {
	store:  async () => {
		await storeValue("adjust_value", Number(Input2.text) - Number(basetext.text))
		await storeValue("final_value", Number(Input1.text) + Number(basetext.text))
	}
}

**Comment by zzgvh** [comment]
Ah, yes I see what you mean. Although my solution works for all cases except the _one case_ described above, so to an implementer who's not 100% read up on how the underlying machinery works I think you can understand that it looks like a bug. :wink: :lady_beetle: Anyway, thanks for taking the time to straighten things out for me!
