### ISSUE TITLE
[Bug]: The time delay of the content displayed in the drop-down box is too long

### ISSUE THREAD

**Issue by georgewangchn** [appsmithorg/appsmith#11468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Release v1.6.0~v1.6.12
When there are more than 1000 records in the drop-down box, the display delay time is very long, more than 5 seconds. It is hoped that this function module can be improved and the use efficiency can be improved.

Same with #11252

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/44538731/155917320-2c6c080a-d5d3-48e5-b9ae-e43d5438013e.png)

### Environment

Release

### Version

Self-Hosted

**Comment by dilippitchika** [comment]
@prsidhu any updates on this?

**Comment by prsidhu** [comment]
@dilippitchika https://github.com/appsmithorg/appsmith/pull/11673
