### ISSUE TITLE
[Bug]: On changing visible and homepage the order of page changes on page properties

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2a88ffdbaccc43e79185dd8f4d89bb69-00001.gif)](https://www.loom.com/share/2a88ffdbaccc43e79185dd8f4d89bb69)

### Steps To Reproduce

1. On page properties create few pages
2. Now click on setting icon and toggle visible or homepage property
3. Observe that the page order changes and the pop up new page is displayed automatically 

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
Tried reproducing the above steps on Production environment. Issue seems to be fixed. Toggle does not any changes in the page order changes.
