### ISSUE TITLE
[Bug]: On the truncation modal, the text is not aligned properly when there are urls

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i add a text with urls and make the text widget right aligned, with truncation. When the show more modal opens it's not aligned properly.

### Steps To Reproduce

1. Add text with a url in the text widget
2. Enable truncation and make sure text cuts off to see the ...
3. Make sure text is right aligned.
4. Open the truncation/show more modal and observe that it's not aligned correctly.

![Screenshot 2022-02-28 at 12 43 09 PM](https://user-images.githubusercontent.com/19730984/155941534-c1b0c9aa-181d-4c13-bc3b-9fc0f769f488.png)

### Environment

Production

### Version

Cloud

**Comment by techbhavin** [comment]
@somangshu  @dilippitchika needs PRD of this issue so we can understand what is expected output we want?


**Current Observation** 
- when we add text with URL, the text widget is left or Right align then the link is not truncated instead of it will show in a horizontal scroll.

**Comment by somangshu** [comment]
I also want to try and understand what is this important to solve?

**Comment by dilippitchika** [comment]
@techbhavin @somangshu the problem is that it should either be completely left aligned or completely right aligned. 

In the image shared above the widget has property text align set to right but the right alignment is not working here as the other text doesn't align with the URL on the right end. Why do we need a PRD here?

**Comment by somangshu** [comment]
I believe its about word wrap, so we need to identify the expected Behavior 
- Are we expecting the url to break word? is there any other suggestion

@jsartisan can you suggest what style otherwise could work best here?

**Comment by dilippitchika** [comment]
Hey this doesn't need word-wrap because we already have horizontal scroll. Can we connect once?

**Comment by somangshu** [comment]
@techbhavin we decided to `word-break: break-all` for the text only when inside the modal. _**Not for the default text component or text in the modal**_

**Comment by btsgh** [comment]
Tested on Release. Seems to have been fixed as per comments and discussions in the thread above. The text is now aligned properly when there is a URL.
<img width="1358" alt="Bug11474_2" src="https://user-images.githubusercontent.com/101863839/160997838-3981b2be-0137-4895-a807-dd3fa3f0e515.png">

<img width="1366" alt="Bug11474" src="https://user-images.githubusercontent.com/101863839/160997824-22ac945d-bb8f-4fe0-aa69-3fec1e7c8743.png">

**Comment by dilippitchika** [comment]
@somangshu can you take a look at the above screenshot pasted by @btsgh, In the first line word "the" is broken but we thought it won't. I think this is bad experience if this happens to break words which are small, can you let me know if this is something we can fix?

**Comment by somangshu** [comment]
@dilippitchika that is break-work works, This is expected according to me, if now, we will have to revert
