### ISSUE TITLE
[Bug]: The fetch selected theme api is giving 401 error for logged out users

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#11486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am trying to open a public app in the logged-out state, the app is redirecting me to the login page. Seems like a issue with fetch selected theme API - 
![image](https://user-images.githubusercontent.com/6636360/155968325-06a5a62f-6905-46ed-b8ce-d1e6b5d55624.png)

### Steps To Reproduce

1. On theming DP, create an app and deploy it. 
2. Make the app public
3.  Open the app in incognito mode.
4. Notice the app will take you to the login page.

### Environment

Production

### Version

Cloud

**Comment by btsgh** [comment]
Recreated the steps with guidance from @nayan-rafiq .. Issue has been fixed. 
https://www.loom.com/share/3e533d27f920444d8ad57e8cbc44da11
