### ISSUE TITLE
[Bug]: The empty page is  pre-populated with widgets name from the previously selected page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The empty page is  pre-populated with widgets name from the previously selected page
![image](https://user-images.githubusercontent.com/45958978/155973016-9ee6c18e-3e92-4e38-8781-5e01ea121c2f.png)

### Steps To Reproduce

1. Create a new crud page 
2. Now add a new page 2
3. now go back to the crud page and navigate back to page 2 
4. The widgets present in the page 1 is displayed in the Widget section of the entity explorer

Note: Issue is reproducible when user navigate between the pages multiple times

### Environment

Release

### Version

Cloud

**Comment by akash-codemonk** [comment]
Closing as unable to repro anymore.
