### ISSUE TITLE
[Bug]: Able to place widget outside the item container on list widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/adec646b5b7b4a329d9d3b527625a27d-00001.gif)](https://www.loom.com/share/adec646b5b7b4a329d9d3b527625a27d)

### Steps To Reproduce

1. Drag and drop a list widget
2. Increase the item spacing
3. Now I able to drop widget outside the item container

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@rahulramesha can you check to see if this related to the reflow experience?

**Comment by rahulramesha** [comment]
@somangshu, yes this seems to be related to reflow, This seems to be a corner case we missed out.

**Comment by somangshu** [comment]
In that case we should take this forward.
