### ISSUE TITLE
[Docs] Add information about domain specific user signup for Google OAuth2

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1148]
## Documentation Link 
Relevant link that needs to be improved: https://docs.appsmith.com/third-party-services/google-login

## Describe the problem

Currently our documentation doesn't have any indicators that Google sign in can be restricted to certain domains for self-hosted instances.

## Describe the improvement

Information about the environment variable that controls specific domain signups can be configured needs to be added in Step 5. The environment variable to be added to `docker.env` file is : `APPSMITH_OAUTH2_ALLOWED_DOMAINS`. The value will be the domain. For eg, `APPSMITH_OAUTH2_ALLOWED_DOMAINS=abc.com` will restrict Google signups to email IDs belonging to abc.com.

**Comment by fredb1106** [comment]
Hi mohanarpit. Can I be assigned that change? This would be my first contribution to hacktoberfest; hoping this is right first step to first ask being assigned to that issue. Let me know.

Thanks!

**Comment by mohanarpit** [comment]
@fredb1106 It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, check out the [Appsmith Challenge](https://github.com/appsmithorg/appsmith/discussions/863) where you can win some cool swag by inviting your friends to contribute to this project as well.

**Comment by fredb1106** [comment]
Sure, will work on this today! By looking at your code I noticed `APPSMITH_OAUTH2_ALLOWED_DOMAINS` was also missing from some sample docker.env files or Shell scripts to generate them e.g.:

- appsmith/app/server/envs/docker.env.example
- appsmith/deploy/template/docker.env.sh

... and potentially those also:

- appsmith/.env.example
- appsmith/app/server/envs/dev.env.example

I can add that parameter to those files as well while we're at it.

Also I can see that from the below 2 files that the domains list can be a comma-separated list so I can mention that as well.

- appsmith/app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java (line 54)
- appsmith/app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomServerOAuth2AuthorizationRequestResolver.java (line 165)
