### ISSUE TITLE
[Bug]: Commenting on canvas is broken

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On canvas, comment pins are not being put in the right place.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/a84f757551b84753ae5158e2c348dfa0-00001.gif)](https://www.loom.com/share/a84f757551b84753ae5158e2c348dfa0)

### Steps To Reproduce

Open an app in comment mode and try to put a comment on canvas.

### Environment

Production

### Version

Cloud

**Comment by vuiets** [comment]
@hiteshjoshi bumping this up again. Been a few weeks since users haven't been able to use the commenting functionality because pins don't get placed where they ought to. 

Looks like a low effort solve. Can we route this to someone and get it fixed?

**Comment by hiteshjoshi** [comment]
Yeah this is low effort. It's just the x axis while adding comment is a bit messed up.

**Comment by hiteshjoshi** [comment]
Closing this.
