### ISSUE TITLE
[Bug]: Image URL stops working after I remove default image URL from image widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e031a1bb34ed4674a8958372b88e1595-00001.gif)](https://www.loom.com/share/e031a1bb34ed4674a8958372b88e1595)

### Steps To Reproduce

1. Drag and drop image widget
2. Paste an image URL
3. remove the default Image url
4. Now if I copy paste the existing image URL it stops working

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@techbhavin can you please check and tell me what changed here before we start working on it, seems like this is a regression.

**Comment by techbhavin** [comment]
![image](https://user-images.githubusercontent.com/58818598/157609471-9ffee4ea-cebc-4a9c-a9de-843848d27725.png)
@somangshu  I think it's not working because of this condition.

**Comment by somangshu** [comment]
@techbhavin please help me understand, does the variable `imageError` result in true if the default image is not present?
Also can you check the git blame to see how it worked before?

**Comment by techbhavin** [comment]
this change is related to PR  [#11247](https://github.com/appsmithorg/appsmith/pull/11247/files#diff-f5a90f0e2c0fd42e087007ea8111774502f2575208f839360a80f1be7ae81613R131)

root cause: `imageError` is not set again to false when we add again default image. 

I will look into this issue

**Comment by sbalaji1192** [comment]
@techbhavin @somangshu As mentioned ImageError is getting reset properly. we need to set it to true on when image URL changes on `componentDidUpdate`

**Comment by wmdev0808** [comment]
@somangshu @sbalaji1192 @techbhavin ,
We can also just simply fix this issue using the conditional expression on underlying `img` tag like this:
L218: 
```
{(this.props.imageUrl || this.props.defaultImageUrl) && (
  <img
    alt={this.props.widgetName}
    onError={this.onImageError}
    onLoad={this.onImageLoad}
    src={this.props.imageUrl || this.props.defaultImageUrl}
    style={{
      display: "none",
    }}
  />
)}
```

**Comment by sbalaji1192** [comment]
@wmdev0808 That will not solve the issue. if there is an error, the img element wouldn't get rendered. because of the condition in L131. The ideal way to fix this is to reset imageError, when props change.

**Comment by wmdev0808** [comment]
> @wmdev0808 That will not solve the issue. if there is an error, the img element wouldn't get rendered. because of the condition in L131. The ideal way to fix this is to reset imageError, when props change.

@sbalaji1192 , you're right. I agree with your way, thank you
