### ISSUE TITLE
[Bug]: Shuffling of menu items are not reflected until page refresh

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/73a849fe78704aeca616ae87b0e54804-00001.gif)](https://www.loom.com/share/73a849fe78704aeca616ae87b0e54804)

### Steps To Reproduce

1. Add Menu Widget to canvas
2. Shuffle menu items in different order 
3. Click on menu widget and observe that Items are not re-arranged as expected

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@yaldram whats the update here?

**Comment by yaldram** [comment]
@somangshu it is in Q/A @vivekverma2312 has started testing this feature today. Also my Pull Request fixes other bugs associated with the drag and drop lists we have in the property pane for other  widgets like Tabs. Please check here - https://github.com/appsmithorg/appsmith/pull/11938
