### ISSUE TITLE
Run query on page load feature is not working for the queries copied from one page to the other .

### ISSUE THREAD

**Issue by ginjojohny** [appsmithorg/appsmith#11528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Run query on page load  feature is not working for  the queries   copied from one page to the other  .

### Steps To Reproduce

1. Created home page and  write some  PostgreSql  queries  say a listing page.
2.  Created  another page with form widget and copied some queries from the first page .
3. The copied queries did not running on page load  even the configuration is set  .

### Environment

Production

### Version

Self-Hosted

**Comment by ginjojohny** [comment]
Actually this is not the problem of copied queries   new queries also not running on page load  in the second page onwards . I have three pages in my application . I listed out master data from my database in a dropdown list on page load itself . The query is running fine on page load of first page and the remaining pages showing error on dropdown option value as it is not loading .

**Comment by rashmi-rai** [comment]
@ginjojohny is this issue present in edit mode or view? Also please share the error message.

**Comment by ginjojohny** [comment]
Issue is in both edit and view mode.  I  am sharing the screen shots  .

![Screenshot (13)](https://user-images.githubusercontent.com/94359116/156368992-848d09db-7de5-4530-941d-2e60bbaafb65.png)

This is my query

![Screenshot (12)](https://user-images.githubusercontent.com/94359116/156368931-f0dbe84c-8460-4171-a28d-f7272d8ae687.png)

Settings of query

![Screenshot (15)](https://user-images.githubusercontent.com/94359116/156369002-93fe26b9-7c76-4a79-9246-3023b246c67c.png)

form page

**Comment by ginjojohny** [comment]
I have tried so many times by refreshing and deployed the application . Every time I took this page and will show this  error on that dropdown . I  am already a member of  discord .

**Comment by rashmi-rai** [comment]
@ginjojohny Sorry for late reply, please post this github issue on discord. We will get in touch with you.

**Comment by rashmi-rai** [comment]
@ginjojohny please rename `client_id` to something else. Name of the input box `client_id` is the same as the index `client_id`, this creates cyclic dependency that breaks page onload logic. ![Screenshot 2022-03-08 at 1.16.31 PM.png](https://images.zenhubusercontent.com/61287a32887234048832d53a/d1041488-9639-474e-9c4e-edd5ae09ac64)

**Comment by ginjojohny** [comment]
@rashmi-rai  Thank you for your help . It is fixed now .
