### ISSUE TITLE
[Bug]: App does not exit from saving state when edits are made on the editor or query

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Edits on JS editor does not exit from saving state unless an action like adding a widget to canvas is done. Any page refresh ends the saving process but refactors that needs to be done on multiple front fails.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3b63b857c17944f7965a60043d0c7bb2-00001.gif)](https://www.loom.com/share/3b63b857c17944f7965a60043d0c7bb2)

### Steps To Reproduce

1. Make an edit on JS editor and observe the saving icon on the top bar not terminate.
2. Bind a JS object to multiple widgets and change the function name. Observe that refactor fails on occasions and causes code flow to break.

### Environment

Release

### Version

Cloud

**Comment by pranavkanade** [comment]
@ajinkyakulkarni @rohan-arthur A user is unable to save their query.
![image (2)](https://user-images.githubusercontent.com/13262095/156361351-38100194-ccc0-4243-bebb-f704f121e0a3.png)

Can we please get this prioritized?

**Comment by Aishwarya-U-R** [comment]
Related to : #10284
