### ISSUE TITLE
[Docs]: Large files are evaluated as blob

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Filepicker (data format - binary/base64) converts MP3 file to blob.
![Screenshot 2022-03-01 at 8 03 56 PM](https://user-images.githubusercontent.com/13262095/156189531-450b650c-80d7-4d6d-9dbf-09d2af05e004.png)
![Screenshot 2022-03-01 at 7 55 03 PM](https://user-images.githubusercontent.com/13262095/156189545-3038be40-1da9-45b1-bb56-1019f05ea160.png)

### Steps To Reproduce

Try to upload mp3 file of 5MB using file picker widget

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@pranavkanade this was done because we cannot maintain such long strings of data in the code. What is the problem here? You can still upload data from blobs. Is this a community issue?

**Comment by pranavkanade** [comment]
@dilippitchika Thanks for confirming.
@Pranay105 this is a documentation change for all the widgets that can upload. When the user tries to log the data it’ll show blob, but if the user uses it in an API/query it’ll actually upload base64/binary.
