### ISSUE TITLE
Call user profile, and features request in parallel  to optimise first load

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#11539]
### This might not be required after we fix the router. 

Right now, we call the features request after the user/me request is done. Doing this adds to delay in loading the application.

We should make them in parallel. Before that, investigate if combining these two api's into a single one is more appropriate.

**Comment by arunvjn** [comment]
API to fetch feature flag returns 401 for an anonymous user. We need to change the response to 200 ok with empty object as response. 
@nayan-rafiq Can you help us here ?
