### ISSUE TITLE
[Docs] Links for appsmith alternatives are broken

### ISSUE THREAD

**Issue by draco-malfoy** [appsmithorg/appsmith#1153]
## Documentation Link 

https://docs.appsmith.com/faq#what-if-i-get-stuck-while-building-an-app-on-appsmith

## Describe the problem

The links for  Wix, Squarespace, or Webflow are broken

## Describe the improvement

Working links should be provided.

**Comment by draco-malfoy** [comment]
I would like to take this. Should I link these directly the specific websites? @Nikhil-Nandagopal @mohanarpit

**Comment by mohanarpit** [comment]
@draco-malfoy Welcome to Appsmith!

Yes. Please link to those websites directly.

**Comment by draco-malfoy** [comment]
Just realized that we have a separate repo for docs, should I log in another issue there?

**Comment by mohanarpit** [comment]
You can link to this issue from the other repository. Also, please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). It has all the details on how to contribute to Appsmith.

**Comment by draco-malfoy** [comment]
https://github.com/appsmithorg/appsmith-docs/pull/46
