### ISSUE TITLE
plugins/forms api calls should not block the editor

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#11538]
After we get the list of plugins, we make calls to `plugin/_id_/form` to get the plugin form details in sequence. That adds 2-2.5 seconds to the first load time.

1. These form details are not needed on the widgets editor.
2. They should be loaded in parallel.
3. They don't need to wait for the dsl.
4. They aren't even required on the editor.
5. Editor need not wait for these apis, but it does.

If we are prefetching this, so that we already have the info when going to the respective plugins screen,
please find why the editor is made to wait for these, and see if fixing this no longer blocks the editor.

If not, remove these call from the widgets editor screen.

In the screenshot below

- Move 4 to the start
- Eliminate 5, or make them parallel and move to start/non blocking

<img width="2168" alt="Screenshot 2022-03-02 at 2 45 59 PM" src="https://user-images.githubusercontent.com/441914/156336358-d0794be5-e56b-41ef-a3e9-0b200acbe97d.png">

**Comment by somangshu** [comment]
## actionable 

Decide what can be done further, Below are some strategies 
- [ ] we need to delay the form calls
- [ ] Make it non blocking
- [ ] since they are static, it makes sense to cache them

**Comment by somangshu** [comment]
@SatishGandham what is the verdict here? Can you please drop a note? AFAIR, we said that this is not the way forward.

**Comment by ayushpahwa** [comment]
Closing this issue since the APIs are now already non blocking.
