### ISSUE TITLE
[Docs] Grammatical and spelling mistakes in Terms and conditions page

### ISSUE THREAD

**Issue by draco-malfoy** [appsmithorg/appsmith#1154]
## Documentation Link 

https://app.appsmith.com/terms-and-conditions.html

## Describe the problem

 Grammatical and spelling mistakes

## Describe the improvement

Grammar can be improved

**Comment by draco-malfoy** [comment]
I have worked on this. @mohanarpit @Nikhil-Nandagopal

**Comment by draco-malfoy** [comment]
https://github.com/appsmithorg/appsmith/pull/1149

**Comment by mohanarpit** [comment]
Not relevant at this juncture.
