### ISSUE TITLE
[Bug]: Type error does not show any error instead throws uncaught promise error when code is run

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any error should display appropriate text to indicate to the user on the exact issue. Currently, type error only shows an **uncaught promise error** with a misleading text stating the **function does not exist**.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/236570dfc4d84a50810cb882be37e096-00001.gif)](https://www.loom.com/share/236570dfc4d84a50810cb882be37e096)

### Steps To Reproduce

1. Copy paste following code on JS editor
`export default {
	myVar1: Input1.text.length > 0 ? Select1.selectedOptionLabel : MultiSelect1.selectedOptionLabels,
	newFunc: () => {
		showAlert("new " + this.myVar1)
	}
}`
2. Run the query and observe incorrect error displayed stating **function does not exist**
3. Replace `Input1.text.length` with `Input1?.text?.length` and observe the query works

App behaviour is different at different locations for this exact piece of code. `Input1.text.length > 0 ? Select1.selectedOptionLabel : MultiSelect1.selectedOptionLabels` works without any errors on JS of property pane but throws an error when it's used on the editor

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
will become irrelevant with #9979 - if we decide that we are ok with variables not being reactive.

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/11542?planning-poker) with ZenHub @ApekshaBhosale

**Comment by eco-monk** [comment]
Will be closed with #9979
