### ISSUE TITLE
Ensure that the DSL,actions, js objects  calls are made as soon as possible

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#11553]
We wait till the features api call is back to load the editor. Then, we wait for the DSL to load to make the calls to Actions and **JSObjects**.

```
// In AppRouter.tsx
// Render the app once the feature flags have been fetched
    if (!featureFlagsFetched) return null;
```
We should be making the DSL and the two calls that happen along with it, plus JS Object and Actions as soon as possible. 
Screenshot below marks where the DSL calls and **actions**+**JSObjects** should start

<img width="2168" alt="Screenshot 2022-03-02 at 2 45 59 PM" src="https://user-images.githubusercontent.com/441914/156332367-7a8bbd43-dd83-490c-8959-29bc001743d8.png">

**Comment by arunvjn** [comment]
API calls to fetch plugins, datasources and mockDatasource are called along with actions in #10957
