### ISSUE TITLE
[Bug]: The Command page does not load when user tries to load it

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#11557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please refer to the video for below :
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/1cc16a114bd342fc8beb000b72f9a509-00001.gif)](https://www.loom.com/share/1cc16a114bd342fc8beb000b72f9a509)

### Steps To Reproduce

1) Click on any of the old data sources 
and observe  that the data is displayed but the entire page does not display 

### Environment

Release

### Version

Cloud

**Comment by Irongade** [comment]
@sumitsum @yatinappsmith @prapullac This bug is not reproducible on release or on production. How did you arrive at this bug?

**Comment by sumitsum** [comment]
@Irongade please reach out to @prapullac to discuss how to reproduce this issue.

**Comment by rashmi-rai** [comment]
This issue is not reproducible. @prapullac can you please confirm?

**Comment by prapullac** [comment]
The issue was intermittent and currently not reproducible, hence we can close the issue

**Comment by rashmi-rai** [comment]
Closing this issue as it is not reproducible
