### ISSUE TITLE
[Bug]-[660]:Avoid un-necessary status API call for git connected application for better performance

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we open the git connected application in edit mode, on the first load we make the status API call(which is heavy in nature, avg is 4 sec RTT) to get information like uncommitted changes, remote status etc. But suppose say even before this API call is not completed and if you click on the commit button you can observe that another call is triggered to the same API. 

The same happens when we switch between commit and merge tab in git sync modal.

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/12005551/156328285-e99009ec-b6d2-4045-8578-b8b6ba7e8d69.png">

### Steps To Reproduce

When we open the git connected application in edit mode, on the first load we make the status API call(which is heavy in nature, avg is 4 sec RTT) to get information like uncommitted changes, remote status etc. But suppose say even before this API call is not completed and if you click on the commit button you can observe that another call is triggered to the same API. 

### Environment

Production

### Version

Cloud

**Comment by hiteshjoshi** [comment]
@IamAnubhavSaini can you debug this and see if we can improve the heavy calls.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 330 |
| Effort (months)  | 0.25 |

**Comment by abhvsn** [comment]
Just wanted to highlight what Anagh has already reported to get the attention:
> The same happens when we switch between commit and merge tab in git sync modal.
