### ISSUE TITLE
[Bug]: Button when deleted does not appear back with CTRL + Z cmd for button group widget

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Delete a button from property pane in button group widget, it disappears from the widget now when user gives keyboard command ctrl+Z the button appears in property pane but not on the canvas.

https://loom.com/share/228baed6a5f0456dac9c95c2d9feb673

### Steps To Reproduce

1. D&D button group widget
2. In property pane delete "Favorite" button
3.  Give keyboard command CTRL+Z

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
duplicate of #10175
