### ISSUE TITLE
[Feature] Add MSFT SQL Server DB Integration

### ISSUE THREAD

**Issue by DeliriousWildebeest** [appsmithorg/appsmith#1155]
**Summary**

Ability to use Microsoft SQL Server DB as a data source. 

**Motivation**

SQL Server is an extremely common DB system which is used in numerous small, medium and large businesses. Adding native support will expand the reach of AppSmith to a new set of organizations.

**Comment by Nikhil-Nandagopal** [comment]
@DeliriousWildebeest thank you for the feature request! 🎉  
Is this feature urgent? If you could tell us a bit about your timeline, it would help us prioritize it better. 😬

**Comment by DeliriousWildebeest** [comment]
My project timeline is about 30 days but I'm not expecting the team to prioritize a feature to cater to a random stranger's needs!

For me personally, it's a priority since I use SQL Server so I'm not able to use AppSmith without setting up a REST API in front of the DB. Lack of SQL Server isn't a deal-breaker, but it creates extra roadblocks to try and integrate into a usable solution for less technical users (as well as more possibilities for things to break). 

I know that SQL Server is used in a lot of SMBs (as well as in Microsoft Azure Cloud) so there is a sizable market out there for it, especially given the on-premise hosting capability. Since SQL Server licenses cost money, a lot of businesses are locked into the ecosystem, whereas start-ups and smaller developers are more likely to use POSTGRESQL or MYSQL instead because they are free and open-source with higher compatibility. What I would say is that because of those reasons most low-code/no-code solutions don't target SQL Server so it would be a good differentiating feature to have.

 Microsoft makes SQL Server Express available via [https://hub.docker.com/_/microsoft-mssql-server](Docker) 

To install in an ubuntu container is the following command:

`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -e 'MSSQL_PID=Express' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu `

For the Java SQL Server driver that can be found here:
[https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15](MSFT)

**Comment by Nikhil-Nandagopal** [comment]
@DeliriousWildebeest thank you for the detailed reply! This makes a lot of sense. I think it's not a lot of effort on our end since there's a jdbc driver. I'll get this prioritised and update you soon.

**Comment by sharat87** [comment]
This has been merged and should soon be available at <https://app.appsmith.com>.

@DeliriousWildebeest Thank you for the detailed suggestion which helped us prioritize this! 😁

**Comment by mohanarpit** [comment]
@DeliriousWildebeest This integration is now available on https://app.appsmith.com. Feel free to give it a spin. 

Look forward to your feedback on this integration.
