### ISSUE TITLE
[Bug]: Menu buttons are of different width

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#11574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Buttons with text of the same length have a different widget and do not look aligned. We should fixed-width, or min-width setting on the Menu Button

![menu button](https://cdn.discordapp.com/attachments/760761686549463060/948664962996391956/Screen_Shot_2022-03-02_at_2.32.02_PM.png)

https://discord.com/channels/725602949748752515/760761686549463060/948664963633934378

### Steps To Reproduce

Add same size text width different letters in menu button widget

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@sbalaji1192 can this be done in table v2, where the button width is in some % of col width irrespective of the length of text?

**Comment by sbalaji1192** [comment]
@dilippitchika We have a similar issue on the V2 epic  - https://github.com/appsmithorg/appsmith/issues/10278

**Comment by dilippitchika** [comment]
Thanks closing this and tracking it in #10278
