### ISSUE TITLE
[Bug]: Multiple queries on the same postgres datasource create new connection pools

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#11572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Suppose that there are 10 on page load actions of postgres type built on top of the same datasource. Also suppose the datasource has not created a connection pool so far (which would happen when no queries have run so far). When the said page is loaded, 10 queries are triggered in parallel. This would lead to all 10 queries creating a new connection pool for the datasource. This breaks the expectation that only one connection pool would be established per datasource. 

### Steps To Reproduce

1. Run appsmith on local and bring it up fresh. This ensures that we can reproduce this issue in the later steps.
2. On a new application, create 10 postgres queries on top of a single datasource. 
3. Go to settings page and set all these 10 queries to run on page load.
4. Now restart the appsmith container to ensure that the server comes up again and no connection pool exists to reproduce.
5. Now open the application created on step 2. 
6. Now observe that on the postgres database, 10 connections would exist instead <5.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand nice find! Hope this fixes our pesky connection pool issue

**Comment by nidhi-nair** [comment]
FYI: This is the likely cause of #11202, we should be able to fix these in one go.
