### ISSUE TITLE
[Feature]: Git: expose branch name as an appsmith property

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#11573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Expose the current branch name as a property on the global scope something like `appsmith.git.branch`

### Why should this be worked on?

by exposing this, users can write business logic using this and can help them solve for environments

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu I don't believe this is the right way to implement this. We should implement environments properly
