### ISSUE TITLE
[Feature]: Provision to tune java parameters of appsmith

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#11580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Provision to tune java server arguments using environment variables. 

### Why should this be worked on?

Allows JVM tuning.

**Comment by Nikhil-Nandagopal** [comment]
Hello @sum35h! Could you tell us a bit about what parameters are you looking to tune and why?

**Comment by sharat87** [comment]
Closed in #11581.
