### ISSUE TITLE
[Bug]: JsEditor run is not triggering API call

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#11589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Production app - https://app.appsmith.com/applications/6220703745ea27345b493741/pages/6220703745ea27345b493745/edit/jsObjects/6220703745ea27345b49374f used in video.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7bd89794d3d645a9ba16281797cffdb5-00001.gif)](https://www.loom.com/share/7bd89794d3d645a9ba16281797cffdb5)

### Steps To Reproduce

This video has clear steps to reproduce -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7bd89794d3d645a9ba16281797cffdb5-00001.gif)](https://www.loom.com/share/7bd89794d3d645a9ba16281797cffdb5)

### Environment

Production

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
there is error in your code @Rishabh-Rathod there is a mismatching bracket. i don't know why linting is not showing error here but this is not problem with API execution

**Comment by Rishabh-Rathod** [comment]
The above function is not tagged as `async` and hence APIs are not getting triggered. 
Need to check `isFunctionAsync ` logic and make sure such functions are tagged as async.

**Comment by Rishabh-Rathod** [comment]
![Screenshot 2022-03-09 at 6.29.37 PM.png](https://images.zenhubusercontent.com/60c2f984f9be7454ac4d7382/b3ae76d0-aa00-4c6e-b0a1-558785273145)

`isFunctionAsync` fails to determine `isAsync` because `data_table.selectedRows` is not having its evaluated value.

This is related to #9645.

**Comment by Rishabh-Rathod** [comment]
As this issue will be closed with #9645 which is the core problem here, unassigning this issue.

**Comment by bharath31** [comment]
@Rishabh-Rathod should we close this issue?

**Comment by Rishabh-Rathod** [comment]
@bharath31 this issue still exists in the product.

**Comment by Rishabh-Rathod** [comment]
This Issue was fixed in production with JSObject mutation.
