### ISSUE TITLE
[Bug]: Add padding at bottom of logs section

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#11592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="935" alt="Screenshot 2022-03-03 at 12 45 51 PM" src="https://user-images.githubusercontent.com/89374972/156521164-6d4e384e-02ff-4369-a112-521981365df6.png">

### Steps To Reproduce

- Create a query on any datasource.
- Run the query 
- Check the logs section. The text at the bottom will be cropped

### Environment

Production

### Version

Cloud

**Comment by ChandanBalajiBP** [comment]
this is how it looks today. Hence closing this issue.
<img width="949" alt="Screenshot 2022-05-02 at 4 25 18 PM" src="https://user-images.githubusercontent.com/104058110/166223468-a3a337eb-e868-4731-8dce-553635d63196.png">
