### ISSUE TITLE
[Bug]: Private app when embedded in iframe does not authenticate user on login

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Private apps when embedded in an iframe shows a login screen. But when a user tries to log in, it does not redirect the user to the application and stays on the login screen showing 'Resource not found'

@Nikhil-Nandagopal 

### Steps To Reproduce

Embed a private app in an iframe. When a user with access to the app tried to login, it does not work. Also flagged by a discord user here  -
https://discord.com/channels/725602949748752515/760761686549463060/948828700718276608

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@rohan-arthur I think this is a known limitation on the platform, we have disabled it for a reason.

@Nikhil-Nandagopal can you add context?

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal which pod needs to look at this?

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika this ideally App viewers can pick up but we can get help from @hiteshjoshi @nayan-rafiq since it has an implication on authentication

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal how to estimate reach for this? My current thought is all urls where embed=true should ideally be private by default and only be public when essential. 

Is this being looked at by ndx now?

Also kicking off a discussion, i think metabase have done a good job at documenting embed workflow for devs. https://www.metabase.com/learn/embedding/embedding-charts-and-dashboards

This may not be related but an interesting read.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika you can look at the number of page loads that have embed in the URL and redirect in the URL.

**Comment by DaftBrit** [comment]
Any plans to progress this further? Foolishly waited until my app was ready to go before grabing a custom domain and embedding in an iframe. Is the current work around simply to make public and "roll your own" login form?
