### ISSUE TITLE
[Bug]: On page change in the view mode we can see a vertical scroll bar appear and then disappear

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i try to switch pages, i can observe that a scroll bar appears and then goes away immediately. 

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d7b8ee1b7ef54edbaadf4f3ff4bbe3e6-00001.gif)](https://www.loom.com/share/d7b8ee1b7ef54edbaadf4f3ff4bbe3e6)

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@techbhavin can you check if this is happening because of the embed change you did?

CC - @somangshu @Tooluloope

**Comment by techbhavin** [comment]
@dilippitchika  this is not relevant to the embed changed

**Comment by dilippitchika** [comment]
Thanks @techbhavin, @Tooluloope can you assign someone to investigate?

**Comment by somangshu** [comment]
Annoying little behaviour we should look into soon @Tooluloope @techbhavin
