### ISSUE TITLE
[Bug]: The user should not be allowed to connect 2 different apps to a single git repo

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The user should not be allowed to connect 2 different apps to a single git repo

### Steps To Reproduce

1. In the release instance
2. Create a new org 
3. Now add 2 apps app1 and app2 
4. Now Connect APP1 to git repo 1 just connect dont do a first commit
5. Now Connect App2 to same git repo 
6. The connection will be successful
7. Now do a first commit from app1 after that Try the commit from App2 the commit Fails

### Environment

Release

### Version

Cloud

**Comment by AnaghHegde** [comment]
@abhvsn Can we auto commit and push the app on the connect CTA? This would be a better approach to avoid edge cases like this?

**Comment by abhvsn** [comment]
We have moved away from this as it was taking somewhere around 12-15sec, but let us explore other ways to tackle if not we can come back to the solution you have mentioned

**Comment by abhvsn** [comment]
Closing this as this is already fixed
