### ISSUE TITLE
Quick Search & Navigation links give Page not found

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#11611]
When rendered through the Quick Search & Navigation available on app.appsmith.com the documentation links for datasources are broken.

The issue is that the quick search points to the url:https://docs.appsmith.com/connecting-to-databases/ whereas the expected url is- https://docs.appsmith.com/core-concepts/connecting-to-data-sources.

The same applies to the other links on the connecting to the data sources page. 

However, the rendering works perfectly if used from docs.appsmith.com.

**Comment by pranavkanade** [comment]
@arunvjn @jnikhila A slight correction to the description ( I only found one broken link for `Hit a REST API`) 
https://www.loom.com/share/8eed7328ae4e419aa5878fa57fe22bf8
