### ISSUE TITLE
[Perf]: List widget re-rendering memoization

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#11620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The `getCanvasChildren` memoization is not working correctly anymore i.e the equality function always returns false. Right now the only way this works is if we do deep equality on all params.

Works
```js
memoizeOne(fn, deepEqual)
```

Doesn't work with individual deep equals
```js
memoizeOne(fn, (prev: any, next: any) => {
      // not comparing canvasChildren becuase template acts as a proxy

      return (
        deepEqual(prev[0], next[0]) &&
        deepEqual(prev[1], next[1]) &&
        deepEqual(prev[2], next[2]) &&
        deepEqual(prev[3] === next[3]) &&
        deepEqual(prev[4] === next[4]) &&
        deepEqual(prev[5] === next[6]) &&
        deepEqual(prev[6] === next[6])
      );
    })
```

**Comment by dilippitchika** [comment]
@ashit-rath what should be the next steps here? I don't see this assigned to anyone

**Comment by Tooluloope** [comment]
Picked up after solving the major Derived Property issues with the list widget
