### ISSUE TITLE
[Bug]: Table Cell Data Values are Misplaced - Visually incorrect

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#11638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1019" alt="Screenshot 2022-03-04 at 5 55 34 PM" src="https://user-images.githubusercontent.com/91450662/156773529-294c8306-8292-4b2a-a0d4-7c60a409e2cc.png">

### Steps To Reproduce

1. Drag Drop a table & map data
2. Observe if column data fits - it moves to top of the cell, else center of the cell

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
Tested this - in production environment with

**Comment by btsgh** [comment]
Tested this in
1. Production environment
2. Connecting to googlesheets datasource
Issue is fixed.
<img width="1183" alt="Bug11638_Fixed" src="https://user-images.githubusercontent.com/101863839/159736586-2dab262b-58fb-4976-a5e5-ca630191b8c9.png">
