### ISSUE TITLE
[Bug]: Appsmith login page is  showing while  embed  the  application  to an external html page using iframe

### ISSUE THREAD

**Issue by ginjojohny** [appsmithorg/appsmith#11637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Created an application and embed it to an html page using iframe tag  with '?embed=true'   parameter in the app url . But it showing the appsmith login page instead of the home page of application .

### Steps To Reproduce

1. Create an application.
2. Embed it into an html page using  within iframe and run the page 

![Screenshot (22)](https://user-images.githubusercontent.com/94359116/156773266-4102ab7c-e65d-46f8-8b14-26b28c1d17ea.png)

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
Hello, we have this tracked in #11603 you can follow that issue to see it's progress

**Comment by ginjojohny** [comment]
@Nikhil-Nandagopal   https://github.com/appsmithorg/appsmith/issues/11603  this issue refers to the private app. 
 My application is configured as public and before it was working fine with my html page .

**Comment by dilippitchika** [comment]
Hey @ginjojohny I am able to access public apps in the embed mode and it doesn't show any login page. Could you share the app url or the give access to us?

**Comment by ginjojohny** [comment]
@dilippitchika  My another application  created with the latest version is working fine with embed feature .  The app which is created with older version has the problem .  I will share the forked app for this on discord.

**Comment by dilippitchika** [comment]
Ok, please share this with someone in our team or email me dilip@appsmith.com so that I can investigate.

**Comment by ginjojohny** [comment]
Sorry for the late replay , I didn't get any notification about this issue  .  Ok I will email the application soon.

**Comment by ginjojohny** [comment]
closing this issue as got solution from community for the similar case
https://community.appsmith.com/t/how-do-i-skip-the-appsmith-login-form-in-my-application-by-new-feature-of-enable-disable-form-login-in-admin-authentication-settings/705/8
