### ISSUE TITLE
[Bug]: Hyperlink on iFrame widget does not perform any action

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dropping a new iFrame widget on canvas displays a text with CTA that does not perform any action on click

![image](https://user-images.githubusercontent.com/79509062/156797779-0b6f96a5-e876-4af9-a162-9d90e3a45086.png)

### Steps To Reproduce

1. Drop an iFrame widget and try to click on the hyperlink present - observe nothing happens when clicking on it

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Clicking the link in an iframe should open the link in the same tab, this is not happening.

**Comment by somangshu** [comment]
Error`Mixed Content: The page at 'https://release.app.appsmith.com/applications/614d881668f3e86b095d24d9/pages/614d881668f3e86b095d24db/edit' was loaded over HTTPS, but requested an insecure resource 'http://www.iana.org/domains/reserved'. This request has been blocked; the content must be served over HTTPS.`
