### ISSUE TITLE
[Bug]: Datasources don't get cleared from entity explorer when dependent queries are deleted

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a query of a datasource is deleted, it's dependent datasource is not cleared from the entity explorer. Since the current design of the entity explorer is intended to display actively used datasources with a query, this behaviour does not comply with current design.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f6f8a9bd71ea4b709472034085e16230-00001.gif)](https://www.loom.com/share/f6f8a9bd71ea4b709472034085e16230)

### Steps To Reproduce

1. Add datasource to an app and create a query for this datasource
2. Delete this query and observe the datasource still present on the entity explorer

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
We now show 3 datasources by default on the entity explorer. The datasource will now remain here.

You can track the change here: https://github.com/appsmithorg/appsmith/issues/11031
