### ISSUE TITLE
[Feature]: Group by Properties in a Table like Notion

### ISSUE THREAD

**Issue by tiger360** [appsmithorg/appsmith#11655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://user-images.githubusercontent.com/5794444/156900014-7cb907bf-3235-432b-be6d-632bea2e2db4.mp4

Grouping by a property of a table like in Notion 

### Why should this be worked on?

 it allows you to visually separate rows in your database views, by pretty much any property.

**Comment by GreenFlux** [comment]
Here's a tutorial on building a table widget with row grouping by using variable mutations. 

https://community.appsmith.com/content/guide/building-table-row-grouping-using-variable-mutations

**Comment by Nikhil-Nandagopal** [comment]
This isn't the right usecase for this widget
