### ISSUE TITLE
[Bug]: Audio blob url shows undefined for audio recorder widget when trying to access

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I record a new audio using the audio recorder widget, the blobURL shows empty when trying to bind in a query or other widgets.

### Steps To Reproduce

1. Drag a new audio widget
2. Record and save the audio
3. Use {{<audiorecorder>.blobURL}} in a query or text widget to see that the value is shown as empty
4. Use {{<audiorecorder>}} to see the full parameters supported and see the blobURL parameter has value
![Screenshot 2022-03-07 at 10 33 20 AM](https://user-images.githubusercontent.com/19730984/156971150-6b540b3d-9736-4516-99c0-6bababb1f816.png)
![Screenshot 2022-03-07 at 10 33 13 AM](https://user-images.githubusercontent.com/19730984/156971177-2d1f8cd2-05f4-40e2-83f3-cce778814ba9.png)

### Environment

Production

### Version

Cloud

**Comment by ohansFavour** [comment]
Autocompletion shows wrong hint. It should be `blobURL` instead of `blobUrl` .  Fixed [here](https://github.com/appsmithorg/appsmith/pull/11667)
