### ISSUE TITLE
[Task] Improve readme

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1166]

**Comment by Wittty-Panda** [comment]
@Nikhil-Nandagopal Can you provide a description on what to do ?

**Comment by Nikhil-Nandagopal** [comment]
@Wittty-Panda this issue has already been assigned. please have a look at our hacktoberfest issues to begin contributing :)

**Comment by Wittty-Panda** [comment]
@Nikhil-Nandagopal okay sir.
