### ISSUE TITLE
[Bug]-[800]:Filepicker doesn't show files in it's pop-up when the user goes to a query page and comes back

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i upload a file in filepicker and go to the query/api page and come back, I can see the number of files uploaded in the button but don't see the files in the pop-up. 

Either reset the filepicker or show the files uploaded, the current state is weird.

### Steps To Reproduce

1. Upload a file to filepicker
2. Navigate to query page
3. Come back to the widget
4. Open the pop-up
5. See that the file is not shown 

Loom -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/48f6107d76f7445c938bef1ecf0509e2-00001.gif)](https://www.loom.com/share/48f6107d76f7445c938bef1ecf0509e2)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
similar to #11129

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | 1 |
