### ISSUE TITLE
[Bug]: Background colour is not working properly on Table widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#11671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1077" alt="Screenshot 2022-03-07 at 1 37 10 PM" src="https://user-images.githubusercontent.com/83569920/156992231-2bca0048-3d9b-4543-8537-13565f1bc8e2.png">

### Steps To Reproduce

1. Drag and drop a table widget
2. Change the background colour 
3. Observe that the colour is not displayed properly

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
Tested in Production environment. Background colour on table widget seems to be working fine now.
<img width="1195" alt="Bug11671_Fixed" src="https://user-images.githubusercontent.com/101863839/159721671-7e7a9dde-cf4c-4eb2-8d84-8fbb07072465.png">

**Comment by Tooluloope** [comment]
Fixed in this https://github.com/appsmithorg/appsmith/pull/12356
