### ISSUE TITLE
[Bug]: Unable to start fat container

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#11679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Server desnot start
Please check attached file
[serverstart.txt](https://github.com/appsmithorg/appsmith/files/8196940/serverstart.txt)
s

### Steps To Reproduce

```sh
docker pull appsmith/appsmith-ce:release
mkdir docker-release
cd docker-release
docker run -d --name appsmith-cerelease-test -p 80:80 -p 9001:9001 -p 443:443  -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ce:release
```

### Environment

Release

### Version

Self-Hosted

**Comment by sharat87** [comment]
@yatinappsmith, hey, I just tried this and couldn't reproduce the problem with the command in the description, but I did manage to produce the same error with this:

```sh
docker run --name ace -p 8001:80 -v "$PWD/stacks:/appsmith-stacks" -d -e APPSMITH_SIGNUP_DISABLED= appsmith/appsmith-ce:release
```

The error message:

```
Unsatisfied dependency expressed through constructor parameter 0;
 nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDataServiceImpl' defined in URL [jar:file:/opt/appsmith/backend/server.jar!/BOOT-INF/classes!/com/appsmith/server/services/UserDataServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0;
 nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'commonConfig': Unsatisfied dependency expressed through field 'isSignupDisabled';
 nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean';
 nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
```

It appears if `APPSMITH_SIGNUP_DISABLED` is not `true` or `false`, it breaks. Even an empty string.

One way to resolve this is to define an autowired `setSignupDesabled` method, similar to the `setAdminEmails` method in the same CommonConfig class,

https://github.com/appsmithorg/appsmith/blob/28c181b59c680b932b5f44fda9edc7c7c416f514/app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java#L109-L112

In this method, we implement a more resilient way of turning this into boolean. This problem exists in the other boolean fields in this class as well.

**Comment by yatinappsmith** [comment]
Verified
