### ISSUE TITLE
[Feature]: Multiple Email addresses in Email address input

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [appsmithorg/appsmith#11689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow multiple email addresses in email address input. Have an option to allow the input to accept multiple email addresses separated by comma or semicolon. 

### Why should this be worked on?

It's very common to need to input multiple emails address when accepting data for TO, CC, and BCC fields. There is no easy way to currently do this. This should also be easy to implement. Currently, using an input field and doing validation via JS.

**Comment by Nikhil-Nandagopal** [comment]
@MichaelLeeHobbs I think this should be a new widget. Sort of like a tag widget that allows users to add items to it with validation for email

**Comment by dilippitchika** [comment]
Hey @MichaelLeeHobbs apologies for the delayed response, have you checked if you can use JSON form widget to solve this problem?

Here's a sample app - https://app.appsmith.com/app/json-form/email-collector-62c7ba0b01213a676a34945f
