### ISSUE TITLE
[Bug]: App visibility is set to private after git merge operation

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After merging the branches with in Appsmith if the app is public it is reset to private. 

### Steps To Reproduce

1. Connect an app to git repo
2. Create branch from the main branch 
3. Make the app public
4. Add a widget or page or make any changes and then do commit + push
5. Now merge the branch back to main branch
6. Try to access the app in view mode and notice that it is not public and user is redirected to login screen
### Environment

Production

### Version

Cloud

**Comment by vmulholl** [comment]
We were not using branches and the same issue happened to us. The toggle indicates public but the app appears as private. 

Workaround: toggle it into private and retoggle into public and it now works.

**Comment by Nikhil-Nandagopal** [comment]
@vmulholl thank you for reporting this! We''' have a fix for this soon

**Comment by AnaghHegde** [comment]
There are two parts 
1. Visibility is reset after merging 
2. When we change the visibility to Public/Private from the UI, it should be applied to all the branch applications.
