### ISSUE TITLE
[Bug]: AppSmith consumes {{}} when it should not

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [appsmithorg/appsmith#11688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AppSmith is consuming {{value}} when it should not. I expect AppSmith to not consume {{value}} when it is an input value for an input field.

### Steps To Reproduce

1. Create an input
2. Input example: `SubjectInput` Text: `HL7 Result: CODE 5 - CRITICAL VALUE - {{institution}} {{accessionNumber}}`
3. Create backend API that accepts JSON
4. Create an API query that sends JSON data to the backend API.
  Example  - The subject and body are Handlebars templates and should have {{values}}
    ```
    {
      name: "{{NameInput.text}}",
      description: "{{DescriptionInput.text}}",
      from: "{{FromInput.text}}",
      to: "{{ToInput.text}}",
      cc: "{{CCInput.text}}",
      bcc: "{{BCCInput.text}}",
      subject: "{{SubjectInput.text}}",
      body: "{{BodyInput.text}}",
      templateMessageExample: {{JSON.parse(SampleMessageInput.text)}},
      rule: {{JSON.parse(RuleInput.text)}},
    }
      
      ```
5. The AppSmith API Query Evaluated Value will correctly show the {{value}} but when the server receives the post request the {{values}} are replaced with null

As a work around I am doing the following `body: "{{BodyInput.text.replace(/{/g, '@').replace(/}/g, '#')}}",`

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
Also related to #7346. I'm closing those in favor of this
