### ISSUE TITLE
[Bug]: www.appsmith.com user signup page does not open up on Kali Linux (debian flavor)

### ISSUE THREAD

**Issue by sachinvyas2012** [appsmithorg/appsmith#11683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Platform details:
=============
uname -r
4.19.0-kali1-amd64

uname -v
#1 SMP Debian 4.19.13-1kali1 (2019-01-03)

Browser:
======
Firefox 60.4.0esr (64-bit) Firebox Quantum

When I open the https://www.appsmith.com/ open on Firefox 60.4.0esr (64-bit), the user signup page does not open up. It works fine with newer version of Firefox so issue appears to be on older  Firefox browser release. Please see the steps below on how to reproduce it.

Steps 1. O

### Steps To Reproduce

1. Use Firefox browser (60.4.0esr ) on Linux (debian flavor) to open the page https://www.appsmith.com/

2. It does not how user sign up option by default

3. Click on sign up open or login, it shows blank page

4. Ideally it show open up user sign up page when someone clicks on sign up. On newer release of Firefox browser it does open up user sign up page

5. Firefox browser (60.4.0esr) -> Tools -> Web Developer -> Web console has following error

the resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.[Learn More]
signup
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.
signup:1
The resource at “https://static.hotjar.com/c/hotjar-2240640.js?sv=7” was blocked because tracking protection is enabled.[Learn More]
signup
Loading failed for the <script> with source “https://static.hotjar.com/c/hotjar-2240640.js?sv=7”.
signup:1
TypeError: window.customElements is undefined[Learn More]
12.9b9bee13.chunk.js:2:3696501
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.appsmith.com/static/js/12.9b9bee13.chunk.js
Source Map URL: 12.9b9bee13.chunk.js.map[Learn More]

### Environment

Deploy Preview

### Version

Cloud

**Comment by sachinvyas2012** [comment]
Seems redirection for sign up is not working

Additional error details:
====================

Firefox -> Tools -> Web Developer -> Web Console -> 


TypeError: window.customElements is undefined[Learn More]
12.9b9bee13.chunk.js:2:3696501
<anonymous>
https://app.appsmith.com/static/js/12.9b9bee13.chunk.js:2:3696501
u
https://app.appsmith.com/user/signup:1:1262
[1028]
https://app.appsmith.com/static/js/main.cb9fe072.chunk.js:1:27038
u
https://app.appsmith.com/user/signup:1:1262
[1785]
https://app.appsmith.com/static/js/main.cb9fe072.chunk.js:1:1175942
u
https://app.appsmith.com/user/signup:1:1262
[1326]
https://app.appsmith.com/static/js/main.cb9fe072.chunk.js:1:867708
u
https://app.appsmith.com/user/signup:1:1262
r
https://app.appsmith.com/user/signup:1:459
t
https://app.appsmith.com/user/signup:1:322
<anonymous>
https://app.appsmith.com/static/js/main.cb9fe072.chunk.js:1:2


<anonymous>
https://app.appsmith.com/static/js/12.9b9bee13.chunk.js:2:3696501
u
https://app.appsmith.com/user/signup:1:1262
[1028]
https://app.appsmith.com/static/js/main.cb9fe072.chunk.js:1:27038
u
https://app.appsmith.com/user/signup:1:1262
[1785]
https://app.appsmith.com/static/js/main.cb9fe072.chunk.js:1:1175942
u
https://app.appsmith.com/user/signup:1:1262
[1326]
https://app.appsmith.com/static/js/main.cb9fe072.chunk.js:1:867708
u
https://app.appsmith.com/user/signup:1:1262
r
https://app.appsmith.com/user/signup:1:459
t
https://app.appsmith.com/user/signup:1:322
<anonymous>

**Comment by sachinvyas2012** [comment]
Let me check and find if I can share any additional detail that can help in fixing it.

**Comment by sachinvyas2012** [comment]
@hiteshjoshi if and when you get to see this message and need any additional triaging details please let me know.

**Comment by hiteshjoshi** [comment]
@sachinvyas2012 Thanks for writing. We will verify this also Firefox 64 was release in late 2018 so might take us time to work on fix.

**Comment by sachinvyas2012** [comment]
@hiteshjoshi thank you for your response. How about a 10 minutes session on Discord ( time that is convenient to you ) so that we both can join the channel at that time and fix it.

**Comment by Nikhil-Nandagopal** [comment]
@sachinvyas2012 we try not to support older browsers so is there any reason you cannot upgrade? I'm closing this as we try to be as compatible with newer versions as possible
