### ISSUE TITLE
[Bug]: Long comment on Comment mode cuts off POST & CANCEL button from canvas

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Long comment on Comment mode cuts off POST & CANCEL button from canvas

https://loom.com/share/6b9620d93c444cdcbe0a6808fd7ff606

### Steps To Reproduce

1. Create an application
2. Go to Comment mode
3. Enter a very long comment and observe.

### Environment

Production

### Version

Cloud

**Comment by Rishabhkaul** [comment]
@somangshu maybe this can be closed?

**Comment by somangshu** [comment]
You are right @Rishabhkaul, commenting is deprecated

Cc @hiteshjoshi @kocharrahul7
