### ISSUE TITLE
[Feature]: Set the mock API by default when adding a new API

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#11697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When user adds a new data source and tries to add a API, we show the mock api path as placeholder. But when user starts editing the path, it's gone. It would be better if mock API path is there by default so that user can see it in action.

### Why should this be worked on?

It'll make user more interested if they can try an API without thinking much. From my experience, it's not likely that someone has an API ready at hand when they've arrived here. After coming to this page when they find that an API URL is required, they need to find an JSON API first before testing this feature. 

If the mock-api URL was by default there, user's will be able to try that out and get familiar with this feature quickly.

**Comment by Nikhil-Nandagopal** [comment]
@nayan-rafiq this can maybe happen for the very first API created but shouldn't happen every time the API is created otherwise it just adds double work to configure an API

**Comment by nayan-rafiq** [comment]
@Nikhil-Nandagopal Yeah, this can be done when there is no API configured for that application or organization.

**Comment by devnamrits** [comment]
@nayan-rafiq @Nikhil-Nandagopal  @sharat87 Should I pick this up?? If yes, can you please elaborate on the exact requirement and little insight from the code's perspective?
Thank you!

**Comment by nayan-rafiq** [comment]
@devnamrits Yes, you can pick this up. Let me try to explain the context. 
Click on the plus sign beside the DATASOURCES and then go to Create new API. You'll see the API editing form appear. In the URL input box, `https://mock-api.appsmith.com/users` is set as placeholder. This value should be there as value also. In other words, the input field will have `https://mock-api.appsmith.com/users` typed by default.

This should happen if there is no other API present for this application. So if user goes to Create new API for the second time, it'll not be there.

Please feel free to ask if you need more help.

**Comment by devnamrits** [comment]
@nayan-rafiq Have done few changes in my local but there some more things that I need to work. Can you connect in discord??

**Comment by devnamrits** [comment]
Raised PR for this. Please review.
cc: @sharat87 @kocharrahul7 @hiteshjoshi @Nikhil-Nandagopal

**Comment by Rishabhkaul** [comment]
Is this related to #10609 @kocharrahul7 ?

**Comment by Nikhil-Nandagopal** [comment]
Yeah that seems like a better solution. Let's close this in favor of that
