### ISSUE TITLE
[Feature]: Mass switch queries to another datasource

### ISSUE THREAD

**Issue by Bimbobao** [appsmithorg/appsmith#11696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow for the switching of existing queries (in bulk) to another datasource.

### Why should this be worked on?

The current way of switching datasource for an existing query are to (1) select the query and (2) switch the query to the appropriate datasource. The steps are then manually repeated for all required queries and pages, which could be tedious if there are many pages/queries (especially when repeated testing of different datasources are needed).

**Comment by Nikhil-Nandagopal** [comment]
Hi @Bimbobao ! Thank you for the feature request. We have this feature tracked here as part of #2836 Please do upvote that issue
