### ISSUE TITLE
[Bug]: File picker does not show content (`data`) of files with size of 5MB or above

### ISSUE THREAD

**Issue by mojtab23** [appsmithorg/appsmith#11711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When working with the file-picker widget if you select a file bigger than 5MB it doesn't show its content instead it shows something like `blob:sfsafdas....?type=Binaray`. If the size of one file is bigger than the frontend limits, we need to show an error to the user instead of providing a file with some false content.

Also with file-picker, we have a property for _Max File Size_ that can be up to 100MB , if there is a file limit like 5MB in the frontend, we need to change the _Max File Size_ maximum value for better UX.
 

### Steps To Reproduce

![Recording 2022-03-08 at 16 14 04](https://user-images.githubusercontent.com/5852362/157240600-6a1f2b70-f538-4dc5-a141-5ceadb0def37.gif)

- Use the File Picker button to select a file bigger than 5 or 20 MB
- You can access the file data, but the content is incorrect and it is something like this `blob:361ee7b1-93e9-43e4-b120-7c264019a0f3?type=Binary`

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@mojtab23 actually the content isn't false. That is the blob location of the file since we store it in memory. Is there another solution to this?

**Comment by mojtab23** [comment]
Oh right @Nikhil-Nandagopal, how I can use this location to access the file content? Is there any documentation for that?

**Comment by Nikhil-Nandagopal** [comment]
@mojtab23 I believe appsmith does that for you automatically when the API call is triggered. @hetunandu am I right here?

**Comment by hetunandu** [comment]
@mojtab23 @Nikhil-Nandagopal that is correct. The blob is resolved automatically when uploading/downloading it

**Comment by mojtab23** [comment]
> @mojtab23 @Nikhil-Nandagopal that is correct. The blob is resolved automatically when uploading/downloading it

Can you help me in case we selected a large file (50MB) with a file picker button how we can send it (upload it) with for example S3 plugin? When I try to send file data it just sends the blob location to the server, not the actual file content.

**Comment by dilippitchika** [comment]
@mojtab23 can you reach out to me on slack? I can guide you, If this is happening then you have to change the s3 query to text/binary and back to base64 again and try running the query.

**Comment by shubhransh-locale** [comment]
Hello,
We are using content of data to hit a python API and hence cant access the data, is there a way in current state I can get the data of the file for my use case

**Comment by Nikhil-Nandagopal** [comment]
@shubhransh-locale you can achieve this by binding the filepicker1.files[0].data property

**Comment by shubhransh-locale** [comment]
@Nikhil-Nandagopal Thank you for the update.
