### ISSUE TITLE
[Feature]: Vertical table display mode

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#11717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the option to display a table with the headers as a column on the far left, and display what would be rows as columns after it. Actions like row highlighting on cell select would happen to the columns instead of the rows. The field should allow JS input in the same way as the text style field.

### Why should this be worked on?

This would allow for tables to be used for things like comparison charts, and add another element of customizability to the widget.

**Comment by Nikhil-Nandagopal** [comment]
@AS-Laguna can you add an example of a react component that does this or an example of this in any product?

**Comment by AS-Laguna** [comment]
@Nikhil-Nandagopal I can't seem to find an example. The best way I can describe it is display the data with a header column instead of a header row. [This codeply](https://www.codeply.com/go/bp/4N6s1QjOEb) shows a rough example of what this should look like.

I most often see this kind of display used in comparison charts, or calculation spreadsheets where you want to see many row values at once. Orienting the table like this allows to see more information on the screen which can help in some situations.

**Comment by Nikhil-Nandagopal** [comment]
I don't think this is a common enough use case for us to tackle right now so I'm going to close this issue

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith that was because the data only returned a single row. That isn't a good use case for a table widget
