### ISSUE TITLE
[Bug]: Multi select dropdown does not pre populate single values .

### ISSUE THREAD

**Issue by ginjojohny** [appsmithorg/appsmith#11714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I  have  a multi  dropdown  list with some integer values . I am able to select and save single as well as multi values . But while am trying to pre populate these values from my  db query , the single value is not prepopulating to the list.

![Screenshot (26)](https://user-images.githubusercontent.com/94359116/157257284-bf026ea4-030c-4324-add8-dbad04fe0545.png)

### Steps To Reproduce

1. Create a page  with multiselect dropdown widget  and set values into it.
2. Select single value from the dropdown and save to  database.
3. Create  a modal for  edit  these values  and set default values from the database query.

### Environment

Production

### Version

Self-Hosted

**Comment by somangshu** [comment]
Thanks for reporting this @ginjojohny. While I am seeing that we are not parsing the default value correctly specially if its an integer, There is a solution for you right now until we are able to fix this from our end. 

You need to have the integers in an array like below
`{{[Table1.triggeredRow.selectedMonth]}}`


We will resolve this at the soonest and get back here, Let us know if it still is not working for you

**Comment by somangshu** [comment]
@Tooluloope [Internal discussion reference](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1646807392688839)

**Comment by ginjojohny** [comment]
@somangshu  Thank you for the support .  I am tried with the option you given but it is not working for multi values.   Anyway I end up with a solution like  this : 

 {{ Table1.triggeredRow.selectedMonth.length >1 ?Table1.triggeredRow.selectedMonth: [Table1.triggeredRow.selectedMonth]}}

and it is working for now.
Please tag  me if there is a fix on this .

**Comment by ginjojohny** [comment]
Thank you @somangshu  for the support .  I tried with the solution you given . But that is not working for multiple values  because  multiple values already comes s an array . 
Anyway I tried with other method    :

{{ _.size(Table1.triggeredRow.selectedMonth) >1 ?Table1.triggeredRow.selectedMonth : [Table1.triggeredRow.selectedMonth] }}

Even if it is some twisted way  it is working for now.   Please let me updated while the issue is fixed.

**Comment by ginjojohny** [comment]
@somangshu  The solution I have mentioned above is not working properly after I deployed the application.  Is there any other option you can suggest  for this ?

**Comment by somangshu** [comment]
@ashit-rath @Tooluloope kindly look into this and provide a working solution for now, Let also talk about the proposed solution we are planning to implement.

@ginjojohny we will get back to you soon

**Comment by ginjojohny** [comment]
OK thank you

**Comment by Tooluloope** [comment]
@ginjojohny to quickly unblock you, could you try using this format `{{[Table1.triggeredRow.step]}}`

**Comment by ginjojohny** [comment]
@Tooluloope  Thank You

**Comment by btsgh** [comment]
Tested this in Release. Discussed scenarios with @Tooluloope and found these behaviours which is expected.

<img width="1249" alt="Bug11714_2" src="https://user-images.githubusercontent.com/101863839/161912103-4f772774-87de-4cdb-8f1a-9038c7c74eb1.png">

<img width="960" alt="Bug11714_1" src="https://user-images.githubusercontent.com/101863839/161912073-ce242c73-2f3a-4287-842b-840876eb2647.png">

<img width="593" alt="bug_11714_more" src="https://user-images.githubusercontent.com/101863839/161912199-33e82bd2-b208-452d-9d57-bdc1831fbeae.png">
