### ISSUE TITLE
[Bug]: Select Widget data disappearing in Modal 

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#11713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Select Widget value is disappearing in a Modal dialog when a grid row is selected in a specif way.
The same is happening for text also.

### Steps To Reproduce

Create a Grid and Modal to display the row data

Scenario 1 :
- Single click a row the Modal Comes up with right rowdata  - Works fine
- Double click another row, the data in the Modal disappears - **Issue Exists**

Scenario 2 : 
- Single click a row the Modal Comes up with right rowdata  - Works fine
- In the same highlighted row, 
    - do a double click.  Modal comes with right data - Works fine
- In the same highlighted row 
    - Do a Single click first and  (No modal appears)
    - then do a Double Click  - data in the modal disappears - **Issue exists**   
    
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e775b66ad99a41f6b65fac5aa100d366-00001.gif)](https://www.loom.com/share/e775b66ad99a41f6b65fac5aa100d366)

### Environment

Release

### Version

Self-Hosted

**Comment by leotom2000** [comment]
Originally reported by a Discord user

https://user-images.githubusercontent.com/8027694/157245748-89d983fc-a6bc-46f5-b4b9-8f17c405ecae.mp4

**Comment by Nikhil-Nandagopal** [comment]
@leotom2000 I think the issue you described first and what the user has described are different. In your case the problem is that the row is getting unselected. This will be solved with #11403 
But in the users case only the select data doesn't seem to be populating. Can you investigate this and find a reproduction?

**Comment by leotom2000** [comment]
> @leotom2000 I think the issue you described first and what the user has described are different. In your case the problem is that the row is getting unselected. This will be solved with #11403 But in the users case only the select data doesn't seem to be populating. Can you investigate this and find a reproduction?

That make sense, a row un-selected by a single click, and then clicked may not pass the value to child window (modal), which could be handled by #11403; 
The user issue is something to be explored,
