### ISSUE TITLE
[Bug]: Evaluated Pane overflows when the data/URLs are long. 

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#11722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Evaluated pane overflow when the text is too long. Added screenshot for reference:

![CleanShot 2022-03-09 at 11 20 15@2x](https://user-images.githubusercontent.com/16307796/157380674-a74612bc-05b5-4e04-9e44-012eaa9e6248.png)

### Steps To Reproduce

1. Bind any API on the property pane
2. When the data is shown on the evaluated pane and if it's long, the pane overflows.

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@vihar this seems to be working for me. Which browser are you using?

**Comment by vihar** [comment]
I'm using Chrome.

This is happening while I'm updating the `Computed Value` property inside the `Column Control` tab.

https://www.loom.com/share/c5630b797c6e483592d9112ba52bbdd6

**Comment by Nikhil-Nandagopal** [comment]
@vihar thanks!

**Comment by bharath31** [comment]
this is no longer reproducible with the new evaluated value pane improvements
