### ISSUE TITLE
[Bug]-[298]:Cell background color not applied for new columns in table widget

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cell background color not applied for new columns in table widget
![image](https://user-images.githubusercontent.com/92293815/157416644-8a93a029-3883-412f-b380-bfa926fbc2cc.png)
https://loom.com/share/3130ad9143284ed1944d6f7d9ddd861d

### Steps To Reproduce

1. Drag and drop table widget
2. In property pane add Cell background color
3. Create new column > Make column type as Button

### Version

Cloud

**Comment by thisischandresh** [comment]
I found this issue too

**Comment by sbalaji1192** [comment]
Calculated the reach by looking at the number of users who have added a cellBackground at table level.
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 298 |
| Effort (months)  | 0.5 |
