### ISSUE TITLE
[Bug]: List Widget's PageNo does not reflect correctly

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#11739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

.png :-
<img width="1244" alt="Screenshot 2022-03-09 at 5 17 30 PM" src="https://user-images.githubusercontent.com/91450662/157437004-f9132301-77b4-4985-9812-45107cdd235c.png">

### Steps To Reproduce

1. Create a ListWidget with data spanning multiple pages
2. Map the ListWidget's PageNo to Input text to see the value changing as user moves pages
3. Observe that the values are not computed correctly & remains the same as page 1
4. **Expected**: Values should be computed rightly

### Version

Cloud Release v1.6.14

**Comment by Aishwarya-U-R** [comment]
Update: PageSize is defined today show the total number of items ListWidget can fit it & not the current number of items visible on a ListWidget.

**Comment by somangshu** [comment]
This works fine when server side is enabled, Deprioritising this

**Comment by Tooluloope** [comment]
Can be fixed without DerivedProperties Evaluations

**Comment by ashit-rath** [comment]
Note: 
Client side page number is stored in a state in the List widget
Server side page number is stored as a meta property.
Merge both into one.
