### ISSUE TITLE
[Bug] On invalid Email Id no error message is displayed to user 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1173]
Steps to reproduce :
1) Navigate to home page 
2) Click on Share option 
3) Add an invalid email Id
and observe

Observation :
It is observed that on adding invalid email Id the user will able to add role and Invite becomes active 

Expectation 
An error message must be displayed to user on entering incorrect email Id

**Comment by ng29** [comment]
Hey @Nikhil-Nandagopal / @prapullac 

Is it available for grabs, so that i can pick it up ?

**Comment by Nikhil-Nandagopal** [comment]
@ng29 this issue is already assigned. I request you to have a look at our issues below.
[Open Issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22)
