### ISSUE TITLE
Rich text editor - video link not functional

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#11731]
The rich text editor video link shows a youtube icon. The link is broken.

**Comment by jnikhila** [comment]
@cokoghenun - Could you please verify if the video is available and if something has changed.

**Comment by cokoghenun** [comment]
Hey @jnikhila, I've made a PR with the fix https://github.com/appsmithorg/appsmith-docs/pull/352

**Comment by jnikhila** [comment]
PR merged and changes available on docs.
