### ISSUE TITLE
[Bug]: Query on mock DB fails for column names with camelCase

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#11738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever we are making a query on the mock Postgres DB which involves a column name with camelCase characters, the query fails with an error saying the column name is provided in all lower case.

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/8526215/157436095-9cb78493-fd9e-44f8-bbd8-8c27109c4533.png">

### Steps To Reproduce

1. Create an app and make a query from the mock Postgres DB
2. Make a simple select query involving a column name with camelCase chars.
3. The query will fail, saying column name is being used with lower case.Postgres

### Version

Cloud

**Comment by mohanarpit** [comment]
This is not a bug, but an idiosyncrasy of Postgresql. All camel-cased column names in Postgresql needs to be double quoted.
