### ISSUE TITLE
[Feature]: Add support for Appsmith to connect through a http or https proxy server 

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When the user self hosts Appsmith in their network, there is a very high chance that all network calls to the outside world will be blocked. Usually the outside/internet calls are done via proxy server which is used only for the purpose of interacting with the outside world. 

This feature lets the users to use features which are dependent on Cloud Service such as OAuth, GitSync, Licencing etc without them having to whitelist ip/domain of Cloud Service. 

### Why should this be worked on?

We use cloud service for a lot of activities now a day. When the user self hosts appsmith in their network, there is a very high chance that all network calls to the outside world will be blocked. Usually the outside/internet calls are done via proxy server which is used only for the purpose of interacting with the outside world. With this support we can support such requirements from users.

**Comment by Nikhil-Nandagopal** [comment]
@AnaghHegde I think this is related to #3311

**Comment by sharat87** [comment]
No, these are different issues. This one is to set a proxy on Appsmith server, for _all_ outgoing communications, including that with cloud-services, and any and all REST APIs.

The other one linked above, is a way to set the proxy on a specific REST datasource, and potentially even use different proxies for different datasources.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 is this becasue it's needed for air-gapping?

**Comment by AnaghHegde** [comment]
Yes that is correct. A user on discord has requested this.

**Comment by sharat87** [comment]
Also for airgapping, yes, but doesn't have to be. Some companies don't restrict the whole of Internet, but just require that all outgoing traffic go through a proxy, for whatever security or audit purposes.

**Comment by dncpax** [comment]
without this (or an equivalent api configuration), no external api can be reached when a forward proxy exists in the network.

**Comment by dncpax** [comment]
I'm sorry but I think this issue is not solved by #14207 .
For example, appsmith backend cannot reach cs.appsmith.com.
Also, templates are not fetched, so an error is shown in the gui.
So it's not just about api requests. It's about appsmith backend not accessing internet resources bc it does not respect the proxy env vars.
I'm using 1.7.1.

**Comment by sharat87** [comment]
@dncpax, thanks for reporting this. I'm reopening this and will prepare a fix soon.

**Comment by rbcb-bedag** [comment]
Hi
Just curious about the state of this fix.
We have upgraded to v1.7.10 and have still the error:

either we can have an instance, which can call REST API's from the internet (by setting our corporate proxy via ENV Variable)
OR
we can make internal calls to our own services.

But we can't have an instance, which can call to internal and external services.

And thank you so far for the great work 👍
