### ISSUE TITLE
[Bug]: Forking public app via new user sign-up results in a 400 response on prod

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
Moving original description below since the behavior on release and prod is a little different when trying to fork public app via a new user sign-up.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/747b7a8750d34bf594af7603b6e4b0b0-00001.gif)](https://www.loom.com/share/747b7a8750d34bf594af7603b6e4b0b0)

### Steps To Reproduce
1. Use a public app [URL](https://app.appsmith.com/applications/62384cb64d9aea1b062ae5ee/pages/62384cb64d9aea1b062ae5f1) and open it up on incognito to be able to repro this scenarrio
2. Click on fork app and create a new user to access this app and observe the 400 error displayed on successfully creating the user (seen in the video)

Public app to fork: https://app.appsmith.com/applications/62384cb64d9aea1b062ae5ee/pages/62384cb64d9aea1b062ae5f1

=================================================================================
**Original issue description**

When a public app is forked using a new user, there's no edit button available and the only option available to the user is to navigate to the home page and the forked app does not exist in the organization

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/63f89d54c2924cb496e6fcc77bcc1a30-00001.gif)](https://www.loom.com/share/63f89d54c2924cb496e6fcc77bcc1a30)

### Steps To Reproduce

1. Use templates and create an app on release URL. Copy from `application/...` and paste it after `https://appsmith-git-feat-betterurls-get-appsmith.vercel.app/`
4. Allow forking this app and make this app public
5. Open up the URL using a new user and observe there's no other option apart from navigating to the home page and once on the home page there is no card for the app that was just forked.

### Version

Cloud

**Comment by arunvjn** [comment]
This issue is not specific to clean URLs and is on release as well. Can you please reassign this ticket ? @hiteshjoshi

**Comment by ramsaptami** [comment]
Bumping up the severity on this issue since this exists on prod and new users cannot fork an app successfully
https://www.loom.com/share/747b7a8750d34bf594af7603b6e4b0b0

**Comment by abhvsn** [comment]
@hiteshjoshi this seems to be an issue on client side because I'm getting redirected to 
`https://release.app.appsmith.com/applications/{appId}/pages/{pageId}/fork` after the sign up for new user but client is not making a call to actually fork the application
`https://release.app.appsmith.com/api/v1/applications/{sourceAppId}/fork/{destinationOrgId}`

**Comment by ramsaptami** [comment]
Reopening this since we're still seeing a 400
![image](https://user-images.githubusercontent.com/79509062/163146590-c8256c08-3f43-4039-b672-19bce45a0046.png)

**Comment by akash-codemonk** [comment]
Blocked by https://github.com/appsmithorg/appsmith/issues/12926

**Comment by akash-codemonk** [comment]
> Reopening this since we're still seeing a 400 ![image](https://user-images.githubusercontent.com/79509062/163146590-c8256c08-3f43-4039-b672-19bce45a0046.png)

This is working on release now.

**Comment by Richarex** [comment]
New user is able to signin the public app which is Forked. Verified it on prod, working fine closing it.
![image](https://user-images.githubusercontent.com/93259714/179184607-8c1cb962-3011-4afd-960b-a9348cd83bc7.png)
