### ISSUE TITLE
[Bug]: FilePicker gets reset on refreshing the page and doesn’t show the file uploaded

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#11741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On uploading a file in filepicker widget and then refreshing the page, resets the filepicker to its intial stage and doesn't contain the file uploaded.

### Steps To Reproduce

1. Go to canvas and drag FilePicker widget
2. Upload a file in this widget
3. Refresh the page and observe.

### Version

Production

**Comment by dilippitchika** [comment]
Hey @Parthvi12 this is expected behaviour, is there a reason why we need to solve this?

**Comment by Parthvi12** [comment]
@dilippitchika Oh is it, I was automating tests in cypress and on reloading page, the filepicker was resetting thought its a bug, I'll close it then.
