### ISSUE TITLE
Add example for Mongo aggregate command in docs

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Over the last few days i have seen quite a few users asking about the Mongo aggregate command. After checking in documentation i found that we don't have enough examples on the usage of aggregate command in RAW mode.

### Why should this be worked on?

1. Reduces time on A force team. 
2. RAW mode expects the mongo command in a particular way and if there are any syntax issues in the command it is hard to debug unless we know the expected format. 
3. We have examples for Insert, Update etc but not for aggregate command. Considering the usage `aggregate` command is used quite heavily in Mongo DB.

**Comment by jnikhila** [comment]
@AnaghHegde - Could you please [review the existing doc](https://docs.appsmith.com/datasource-reference/querying-mongodb#7.-aggregate) and let us know if anything else is needed to be worked upon as part of this ticket?

**Comment by AnaghHegde** [comment]
@jnikhila This does not specifies on how to execute the mongo aggregate command in RAW mode. That is still missing.

**Comment by AnaghHegde** [comment]
When we try to query via RAW mode it is hard to find what is wrong especially the syntax. Like the example shown in below screenshot.
![image (4)](https://user-images.githubusercontent.com/12005551/170250440-3da9ae8f-787e-4f21-9234-e1622e2df539.png)

**Comment by jnikhila** [comment]
Need to contact with @sumitsum for review.

**Comment by jnikhila** [comment]
@AnaghHegde - Please review the changes.

**Comment by jnikhila** [comment]
Published the doc.
