### ISSUE TITLE
[Docs] Add an FAQ for How to run the application on a different port

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#1174]
## Documentation Link 

Link to [FAQ page](https://docs.appsmith.com/faq)
Link to [the file](https://github.com/appsmithorg/appsmith-docs/blob/v1.2/faq.md) that needs to updated

## Describe the problem

If the developer already has a process running on a specific port, they need to change the port at which AppSmith runs.

## Describe the improvement

Add a step by step guide to running application on a different port. Add shell scripts wherever necessary.

Follow [docs contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md).

**Comment by SantoshSrinivas79** [comment]
@satbir121 I'll work on this

**Comment by satbir121** [comment]
@SantoshSrinivas79 Any updates?

**Comment by Rithvik-Reddy** [comment]
Hi @satbir121  is this issue availaible? If so can I take this up?

**Comment by SantoshSrinivas79** [comment]
@Rithvik-Reddy I haven't got to it yet. Pls feel free to take it up

**Comment by Rithvik-Reddy** [comment]
@SantoshSrinivas79  Alright then will work on this.

**Comment by mohanarpit** [comment]
@Rithvik-Reddy Welcome to Appsmith! 🎉 

I've assigned this issue to you. Please try to raise a PR in the next 2 days to resolve this issue.

**Comment by Rithvik-Reddy** [comment]
@mohanarpit Thanks for warm welcome. Will raise the PR soon

**Comment by timetravel107** [comment]
Hi, can someone please advise where to change ports that cause this error--> "Appsmith requires ports 80 & 443 to be open. Please shut down any other service(s) that may be running on these ports."

**Comment by SantoshSrinivas79** [comment]
@timetravel107 the way I did this on my Ubuntu server is as follows (I'm still playing in `development`):

**Server configuration**

Change in `./appsmith/app/server/scripts/start-dev-server.sh`

My config example (the last line): 

```sh
(cd dist && exec java -Dserver.port=8080 -jar server-*.jar)
```

**Client configuration**

Change the config in `./app/client/package.json`

`"start": "EXTEND_ESLINT=true REACT_APP_ENVIRONMENT=DEVELOPMENT PORT=9050 craco start"`

this is used by `yarn start` and runs the client on port `8000`. You need to reverse proxy the domain to this port.


My NGINX config looks like this. Hope it helps in configuring your system:

```sh
server {
    listen 80;
    server_name appsmith.mypad.in;
    client_max_body_size 10m;

    gzip on;
    gzip_proxied any;

    proxy_ssl_server_name on;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header Accept-Encoding "";

    sub_filter_once off;
    location / {
        proxy_pass http://localhost:9050;
    }

    location /f {
       proxy_pass https://cdn.optimizely.com/;
    }

    location /api {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://localhost:8080;
    }

    location /oauth2 {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://localhost:8080;
    }

    location /login {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://localhost:8080;
    }

}
```

**Comment by Nikhil-Nandagopal** [comment]
@Rithvik-Reddy  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by Rithvik-Reddy** [comment]
> @Rithvik-Reddy I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

Hey @Nikhil-Nandagopal Im so sorry for not being able to finish it in time. Thank you for being understanding of this.

**Comment by Nikhil-Nandagopal** [comment]
@Rithvik-Reddy don't be sorry! Contributing to open source should be a passion not a chore. It's perfectly fine if you don't find the time, the important thing is to come back when you do 🙂

**Comment by trdillon** [comment]
Hello, I'm new to the project and am interested in working on this. I just wanted to clarify, should the FAQ just address the port change in a dev environment such as @SantoshSrinivas79 described [in their comment](https://github.com/appsmithorg/appsmith/issues/1174#issuecomment-716615877)? 

I saw elsewhere in the docs the steps to change the port in a [Docker container](https://docs.appsmith.com/getting-started/setting-up/docker#running-appsmith-on-a-different-port), should that be included in the FAQ as well?

**Comment by Nikhil-Nandagopal** [comment]
Hello @trdillon  👋 
As you mentioned, this issue was covered in our docs but looks like it wasn't closed. The issue Santhosh described is a separate workaround for contributors. I'm closing this issue for now but I do urge you to have a look at our other [great first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22)
