### ISSUE TITLE
[Bug]: SSO Issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [ ] The disconnect OIDC flow Breaks ( on restart it doesn’t come up) 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7cf94792b7c84f348bf494f8f0660514-00001.gif)](https://www.loom.com/share/7cf94792b7c84f348bf494f8f0660514)
- [x] License key invalid 
- [x] Duplicate userId key
- [x] The mandatory field addition ( add asterisk on mandatory fields) 

### Steps To Reproduce

SSO issues

### Version

selfhosted

**Comment by ankitakinger** [comment]
@Debsourabh @trishaanand should we add a RED * at the end of the label of the fields to show it's a mandatory field to be added while configuring OIDC?
