### ISSUE TITLE
[Bug]: feature flag for git-import is missing in org's more menu

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#11754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you try to import a git repo, /git/profile api fails and user is not able to import git repo.

### Steps To Reproduce

1. Go to release/app
2. Open dev console
3. Click import git repo, see the error
4. Paste remote url and see that SSH key is not generated.

![Screenshot 2022-03-10 at 1 12 58 PM](https://user-images.githubusercontent.com/1573771/157613822-8d3a8eb7-7946-4e50-bf3a-bc7dd39dc2ea.png)
![Screenshot 2022-03-10 at 1 15 41 PM](https://user-images.githubusercontent.com/1573771/157613824-34454e23-2243-4f02-95f3-14bef6d671f7.png)
![Screenshot 2022-03-10 at 1 16 41 PM](https://user-images.githubusercontent.com/1573771/157613829-b33adb48-7ed9-4059-bdaf-9fe17f218193.png)

### Version

Cloud, Release

## updates

Issue is with FE code, a feature-flag check for git-import feature is missing.

![Screenshot 2022-03-10 at 1 57 50 PM](https://user-images.githubusercontent.com/1573771/157619976-5b611319-683e-475c-8ff0-664f4dae485b.png)

**Comment by haojin111** [comment]
```
getFeatureFlags().GIT_IMPORT && (
                              <MenuItem
                                cypressSelector="t--org-import-app-git"
                                icon="upload"
                                onSelect={() => {
                                  AnalyticsUtil.logEvent(
                                    "GS_IMPORT_VIA_GIT_CLICK",
                                  );
                                  dispatch(
                                    setIsImportAppViaGitModalOpen({
                                      isOpen: true,
                                      organizationId: organization.id,
                                    }),
                                  );
                                }}
                                text="Import Via GIT"
                              />
                            )}
```
line 800 in applications/index.ts
Git_import feature flag should be set as false on release app

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini Feature flag is already present for the git import.
