### ISSUE TITLE
Sequence of confirmation modals and promise run is not consistent and incorrect in places 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an API is called from a JS function which has been marked to run on page load without user confirmation and the API itself is marked to run on page load with user confirmation, then what we observe is that both API calls run in tandem rather than sequential, i.e. ideally run JS first and then the APIs. 

But when the API is not set to run on page load but run with confirmation, then only the API call made from JS function is executed and there's no confirmation modal for the API call

**Please note:** All API calls are set to fail (observing negative tests)

(PS: please reduce the volumn on your device before playing the video below. Didn't realize my mic would pick up my voice this loud)
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/371edafb3e7444488b9f3693a2fac410-00001.gif)](https://www.loom.com/share/371edafb3e7444488b9f3693a2fac410)

### Steps To Reproduce

1. Create a `JSObject1.myFun1` that's set to run on page load without user confirmation
2. Call the API with a catch statement like: `return Api1.run().catch(() => showAlert("failed to run Api1()"))`
3. Now set Api1 to run on page load with user confirmation
4. Refresh the page and observe the sequence of execution
5. Now turn off on page load setting for Api1 and only retain confirmation modal setting
6. Refresh the page again and observe the behaviour as seen in the video

Sample app with multiple functions and API's running various combinations of these settings:
https://appsmith-cltq8r028-get-appsmith.vercel.app/applications/6228ab322e44f550a3b886b4/pages/6228ab322e44f550a3b886b6/edit/jsObjects/6229af92a284dc7417fb4eb8

### Version

Cloud

**Comment by ramsaptami** [comment]
Ideal sequence of execution: JS objects (without confirmation) --> JS objects with confirmation --> API call

**Comment by nidhi-nair** [comment]
Closing the issue because from the video and discussion with Apeksha, this sequence is as expected.
