### ISSUE TITLE
[Bug]: Revamp delete confirmation for all destructive actions

### ISSUE THREAD

**Issue by Irongade** [appsmithorg/appsmith#11761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For all deletion operations, we make use of clicking the delete button twice instead of a modal

### Steps To Reproduce

try to delete a datasource, see the modal pop up

### Version

1.66

**Comment by rohan-arthur** [comment]
tested, looks good to go. Great work Ade!
