### ISSUE TITLE
[Bug]: Iframe onMessageReceived not getting triggered in case of srcDoc

### ISSUE THREAD

**Issue by pallavagarwal07** [appsmithorg/appsmith#11779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi team, we recently started using Appsmith, and we are running into an issue with embedded iframe widgets within appsmith.

Specifically, the onMessageReceived hook never seems to be called.

### Steps To Reproduce

1. Add an iframe widget.
2. Set srcDoc to
```
<html>
  <script>
    setTimeout(() => window.parent.postMessage("hello",'*'), 1000);
  </script>
</html>
```

set onMessageReceived to `{{showAlert(Iframe1.message)}}`

Expectation: I see an alert with "hello".
Actual: Nothing happens.

Setup: Self hosted, version: v1.6.13

### Version

Self hosted, version: v1.6.13

**Comment by somangshu** [comment]
Thanks for reporting this @pallavagarwal07 

Two things here:
- `window` object is not allowed on appsmith. I am not sure if the above statement is executing.
- I will still check if the origin is hindering in receiving the post message.

**Comment by somangshu** [comment]
@wmdev0808 can you help me out here? Can you check the issue is because of the origin being the same? Should the postMessage work through the srcDoc?

**Comment by pallavagarwal07** [comment]
The same page hosted elsewhere works fine - i.e. the problem is specific to srcDoc.

The window object is not allowed within appsmith inside javascript contexts. This is plain HTML and is not being interpreted by appsmith till it gets set as the srcDoc of the iframe, at which point it *does* run.

If I open console in my browser, and put 

```
window.listener('message', () => {console.log("received message")})
```

in the chrome console, I can actually see the message posted by the iframe. This would not be happen if the script inside the iframe wasn't executing.

**Comment by somangshu** [comment]
Thanks for the additional context @pallavagarwal07, Can you please help me understand your use case as well?

**Comment by pallavagarwal07** [comment]
Hi @somangshu thanks for the quick replies!

Basically iframe+srcDoc allows me to quickly write custom components and they can't communicate with the parent page without a postmessage - which is limiting this approach. However I can still host the same code externally as a workaround for now, but it would be great to not have to do that.

Let's say I have a timer component (plain html, javascript), I can just dump that code (if its small enough) in the srcDoc. The postMessage allows me to communicate with appsmith widgets (lets say the timer sends the current time back to the page at 100ms intervals).

**Comment by somangshu** [comment]
Understood, I get that could be helpful @pallavagarwal07, Let me have a discussion around this internally. If I find more interesting takes on this, Ill get back here.

**Comment by pallavagarwal07** [comment]
Thanks @somangshu. I took a quick look at the code and came up with a proposed fix here: https://github.com/appsmithorg/appsmith/pull/11809

Let me know if this is something that we can consider merging. The PR fix description also mentions a bug with the current implementation which is probably quite important to fix (multiple iframe with same origin case).

Kudos on keeping the code so clean and easy to contribute to!

**Comment by somangshu** [comment]
I must say, You are just awesome @pallavagarwal07 ❤️ 🎉 💯. 
Thanks for the contribution, Ill look into it and get the maintainers to review. 👏 👏 
Looking forward to merging this soon. Please keep an eye on any review comments 🙂
