### ISSUE TITLE
[Task]: bring scrollbar to the top of other elements 

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#11782]
UPDATE : Change in direction of the scroll bar, we don’t want it to be visible. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

scrollbar is partially hidden by git connection subtitle

https://user-images.githubusercontent.com/1573771/157743063-0b8b0025-da98-4d57-8784-1964a6102640.mov

<img width="548" alt="Screenshot 2022-03-11 at 1 16 52 AM" src="https://user-images.githubusercontent.com/1573771/157743095-8ebf8a5e-7304-4fc1-9533-68ebf050e53c.png">

**Comment by hiteshjoshi** [comment]
@debsourabh to come back with iterations/decision.
