### ISSUE TITLE
[Feature]-[120]:Map Widget Enhancement - Bind searched location to input fields without clicking on map

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#11781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the functionality of binding the address of the searched location from the map widget to an input field, without clicking on the map.

![image](https://user-images.githubusercontent.com/101268423/157736461-6514c2e7-fd42-421f-9ff6-ff80784be06c.png)

### Why should this be worked on?

As an enhancement, this will improve the user experience as it will allow users to search on the Map widget, and display searched fields on other widgets without clicking on the Map widget.

**Comment by dilippitchika** [comment]
After investigation, i see that we don't show a marker for the item the user has searched in the map widget. Is it not possible to show a marker in the map widget for something which is searched for? 

Try searching "SBI Bank" and click on first result you wouldn't know where exactly is the location

**Comment by somangshu** [comment]
Do we have any consensus on this being the generic behaviour across such components elsewhere?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @dilippitchika I think here the solution is pretty simple. We just need to add the address to the Map1.center object which only contains the lat/long right now

**Comment by dilippitchika** [comment]
> 15 users bound map.center in their bindings

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 15 |
| Effort (months)  | 0.25 |
