### ISSUE TITLE
[Bug]: Forking apps add the deleted page from the Original app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Forking apps add the deleted page from the Original app
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/af8a968361034774b6228b3d11ec1040-00001.gif)](https://www.loom.com/share/af8a968361034774b6228b3d11ec1040)

### Steps To Reproduce

1. Generate a new app
2. Add 2 pages Page 1 and page 2 
3. Now delete the Page 1
4. Now fork the application to the new org
5. Open the application and check the user can see the deleted page in the application

### Version

Release

**Comment by abhvsn** [comment]
@RakshaKShetty is this happening to the specific app? If yes can you please share the app link here?
