### ISSUE TITLE
[Bug]-[100]:Binding values directly in the API url does not get evaluated

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you bind widget values in the api URL, it evaluates to no value.
<img width="1193" alt="Screenshot 2022-03-11 at 12 22 59 PM" src="https://user-images.githubusercontent.com/32227135/157822724-f3e6a131-edeb-4158-8285-d718c1471fee.png">
<img width="444" alt="Screenshot 2022-03-11 at 12 24 22 PM" src="https://user-images.githubusercontent.com/32227135/157822736-c4ddc9f9-b40d-41af-84f6-a764468786d1.png">

### Steps To Reproduce

1. Add an input widget with a random value (eg: baz)
2. Create an API and in the URL bind the value of the input widget like this http://foo/bar?{{Input1.text}}
3. We would expect the value to evaluate as http://foo/bar?baz, but it shows http://foo/bar

### Version

Cloud, Self-hosted -  v1.6.14

**Comment by ramsaptami** [comment]
Re-opening since the evaluated value from binding is still not recognized
![image](https://user-images.githubusercontent.com/79509062/162149796-a2759577-2f35-451a-994f-57793dd7f691.png)

**Comment by rashmi-rai** [comment]
For URLs like this: `https://api.github.com?{{appsmith.user.name}}` api is not returning correct `dynamicBindingPathList` . `{ key: "queryParameters[0].key" }` would be missing. 
However, URL `https://api.github.com?{{appsmith.user.name}}=` gives correct response.

**Comment by rohan-arthur** [comment]
Event: BINDING_SUCCESS,
Properties:
propertyPath = config.path
entityType = API
unevalValue contains `?{{`
...6m usage: 25

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 25 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
This isn't reproducible anymore. An error is thrown since the URL pattern is incorrect.
