### ISSUE TITLE
Add a code-formatter to the project

### ISSUE THREAD

**Issue by pc9795** [appsmithorg/appsmith#1179]
## Summary

As multiple contributors will write code in their unique style it is no harm in having a code-formatter integrated using Maven/CI which will ensure consistency.

## Motivation

It will improve code readability and consistency.

## Additional Context

https://github.com/jhipster/prettier-java

**Comment by inesane** [comment]
Can I be assigned this?

**Comment by shinnlok** [comment]
Can I take this?

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you let us know how to proceed here. What should be the formatting syntax?

**Comment by hetunandu** [comment]
Looks like we need something like this [Super Linter](https://github.com/github/super-linter)

**Comment by JoelLau** [comment]
how about something like ESLint, Prettier, and pre-commit hook to enforce the coding style (Husky)

**Comment by hetunandu** [comment]
@JoelLau We do have a pre-commit hook but looks like it does get run when committing directly via Github.

**Comment by vvkpd** [comment]
I would like to contribute on this card if required, please let me know
