### ISSUE TITLE
[Bug]-[700]:How to find generate from a date table option after navigating between newly created pages?

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#11791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I faced an issue while creating a new page, there are two options

1. Build with drag & drop
2. Generate from a data table

I created two pages: Page 4 and Page 5. 
I can see both options, but if I navigate to Page 4 after creating Page 5. I am taken directly to the canvas, and same happens with Page 5.

How do I go to Generate from a data table?

### Steps To Reproduce

Check the video for the steps.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/43d92417dedf442aa29b1a3386c78b54-00001.gif)](https://www.loom.com/share/43d92417dedf442aa29b1a3386c78b54)

### Version

Cloud

**Comment by RoopKrrish9696** [comment]
Hey guys, I think this can be solved with our new add new page / application design which is in progress ( template phase 2 basically ) , we have some thoughts around this - we can sync around this in templates catchup. cc @hiteshjoshi @kocharrahul7

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1400 |
| Effort (months)  | 1|

**Comment by kocharrahul7** [comment]
https://github.com/appsmithorg/appsmith/issues/14446

Will be addressed with this issue
