### ISSUE TITLE
[Task]: Error message without an error 

### ISSUE THREAD

**Issue by soul-cell** [appsmithorg/appsmith#11803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![error](https://user-images.githubusercontent.com/82372780/157850164-91753894-975a-4639-8d45-cfd44da2cb06.PNG)

This message appears every time I launch the app  but there is no  error in the global variables JS and everything works fine .

### Steps To Reproduce

NA

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@soul-cell this seems like there may be another function or button with the same name. Can you share the app where this is happening?

**Comment by soul-cell** [comment]
Sorry cant share the application because of some policies , but I can assure you that there is no other function or buttons with this name

**Comment by Nikhil-Nandagopal** [comment]
@soul-cell can you reproduce this in an app where it can be shared? Otherwise, you can write to support@appsmith.com and we can get on a call to debug the issue

**Comment by soul-cell** [comment]
@Nikhil-Nandagopal Reproducing is the problem , I worked on some other applications but never noticed this problem before . I will post again if I am able to reproduce it

**Comment by Nikhil-Nandagopal** [comment]
Ok thank you please re-open this if you can reproduce it
