### ISSUE TITLE
[Feature] Restrict users edit a form simultaneously

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#11810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be an option to prevent multiple users from editing a form simultaneously.

### Why should this be worked on?

This is an enhancement that is very useful for situations where multiple users collaborate and should not be allowed to edit a form at the same time.

**Comment by anvaravind** [comment]
https://app.appsmith.com/applications/622ce1770bf98b2d5df754b5/pages/622ce25a0bf98b2d5df754c6, we have a table where we display the content of database ( we are using rest API to fetch data from DB  in backend)
We have a separate form to insert/update records, imagine a case where multiple users try to update  the data based on what they see on table, if 2 users try to update the same record then last successful record will succeed
with the current RTS service could it be possible to implement a mechanism where , when a user tries to edit the form, the same form for other users should be grayed out.

**Comment by Nikhil-Nandagopal** [comment]
@anvaravind thanks for chipping in with a solution. I think we need to approach this in a more generic way where we can expose the field a user is editing in JS and then a developer can write logic to disable the fields that they think are important for this
