### ISSUE TITLE
Evaluated value needs to have a styled scrollbar 

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1182]
Comes down to asthetics I guess. The default scrollbars don't look nice with our designs so we are hiding them as of now. Another solution is to style the scroll like we do for the property pane today

_Originally posted by @hetunandu in https://github.com/appsmithorg/appsmith/pull/1171#discussion_r503910957_

**Comment by jyash97** [comment]
Hey @hetunandu 👋 

We can put the scrollbar style at a global level so that every pages and component have a consistent scroll-bar style. What do you think?

I can look at these issue as this should be a small fix IMO.

**Comment by hetunandu** [comment]
Hey @jyash97 !
We don't really want to do this for every scrollbar in the platform. But definitely for the Evaluated Value popup mentioned in this issue

Can you take [this](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/constants/DefaultTheme.tsx#L44) and make sure that component gets this scroll bar. 

Assigning it to you
