### ISSUE TITLE
[Feature]: Make password widgets eye icon/toggle non default

### ISSUE THREAD

**Issue by shashi-donon** [appsmithorg/appsmith#11828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Can we have a way to avoid the eye icon, it would be really helpful if we had a secret field, or a way to  disable that eye icon so that user is not able to see the field  JUST BE ABLE TO EDIT IT 
<br>
<img width="302" alt="Screenshot 2022-03-14 at 1 42 25 PM" src="https://user-images.githubusercontent.com/42883689/158131151-7a1df47b-28d5-4ee0-a665-821076ce24a7.png">
<br>
<img width="302" alt="Screenshot 2022-03-14 at 1 43 06 PM" src="https://user-images.githubusercontent.com/42883689/158131365-b1801591-5717-47e5-9cdb-85ac323efe43.png">

### Why should this be worked on?

It would be very helpful if we had some secret fields that can just be edited without being able to view it

**Comment by Nikhil-Nandagopal** [comment]
@shashi-donon thank you for the feature request!

**Comment by shashi-donon** [comment]
Thanks for looking to it,

**Comment by dilippitchika** [comment]
> we had some secret fields that can just be edited without being able to view it

Hey @shashi-donon why is it this way? I need more information to triage this better. Is this being done for a specific reason?

**Comment by shashi-donon** [comment]
So We have situation where we are just storing the password for api calls. and we have a support team who can do simple diagnostic check, and we don't to show case those password anyone.

But instead they could be able to just create a new password for the user directly.

**Comment by Nikhil-Nandagopal** [comment]
@shashi-donon that would still not be secure as the user can find that information from the network. I suggest either
- Not returning any data from the network
- If for some reason you have to return it, don't show that in the Input widget, instead store it using storeValue and retrieve it directly from there
Let us know if this still doesn't work for you. We try to avoid adding too many configurations to the widgets to prevent over complicating them
