### ISSUE TITLE
[Bug]: Unable to display the image error appears when default image url is empty

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When default image url is empty and while adding image url in Image field, the widget displays "Unable to display the image".
Same error occurs for adding image url as an input or binding it with File picker widget

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/793d6fa35d7c45bfb3a27e99377a91c7-00001.gif)](https://www.loom.com/share/793d6fa35d7c45bfb3a27e99377a91c7)

### Steps To Reproduce

1. Add Image widget to canvas
2. Remove pre-filled default image url
3. Add image url in Image field and observe the error displayed in widget
4. Bind Filepicker widget with Image widget and remove default image url from property and observe the error

### Version

Cloud - Production

**Comment by dilippitchika** [comment]
Fixed in #11494
