### ISSUE TITLE
[Bug]: null as defaultValue evaluates to 0 in Input widget number type

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#11839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When {{null}} is bound to defaultValue of Input widget Number type, it evaluates to 0.

### Steps To Reproduce

1. Add an input widget to the canvas
2. choose Number type
3. Set {{null}} as defaultValue in property pane
4. Input has 0 as value.

### Version

clound

**Comment by btsgh** [comment]
Tried this bug on Production environment and I was able to reproduce it still.  Release environment, and this is what happens

**Comment by btsgh** [comment]
1. Tried this bug on Production environment - Was able to reproduce the issue. 
2. Tried it on release environment - An error comes up to the effect - "This value must be a number" (View attached screenshot)

<img width="858" alt="Bug11839_StagingEnv" src="https://user-images.githubusercontent.com/101863839/159649778-6c281587-b11f-4ff3-af4f-fac583a7f922.png">

@sbalaji1192 @dilippitchika

**Comment by sbalaji1192** [comment]
@btsgh 
WRT,
-1, it is expected. This change has not been promoted to master.
-2, @dilippitchika do we need to allow null value and treat it as empty?

**Comment by dilippitchika** [comment]
Me and @ashit-rath were discussing this that we should support null overall in all the widgets. We will need to do on a bigger level. If this is not a migration, we are good to go with this fix.

**Comment by sbalaji1192** [comment]
@dilippitchika Could you explain what do you mean by migration?

**Comment by dilippitchika** [comment]
If the user is already using {{null}} in their number input widget and it was going to 0, what will happen to those number inputs now?

**Comment by sbalaji1192** [comment]
@dilippitchika We won't convert the value to 0 and show an error border around the defaultValue.

**Comment by dilippitchika** [comment]
@sbalaji1192 won't this break flows which are using {{null}}?

**Comment by sbalaji1192** [comment]
@dilippitchika It won't break the application. Just that input value will be empty. Is it not a edge case?

**Comment by dilippitchika** [comment]
Not sure, because the data has changed for those cases. Is this in production now?

**Comment by sbalaji1192** [comment]
@dilippitchika yeah. This is in production now.

**Comment by dilippitchika** [comment]
Discussed with @sbalaji1192, the conlusion is - No changes to this PR, it will stay the same. We haven't heard from users yet, so we think this change is fine for now.

In future, we are planning to support null values across all fields

**Comment by btsgh** [comment]
As per comments above and my observation on Release, marking this issue as fixed.
