### ISSUE TITLE
[Bug]: Welcome tutorial does not start for new user

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Welcome tutorial does not start for new user after clicking on 'Start tutorial' 

https://loom.com/share/b6af623e1366446992726632685743fc

### Steps To Reproduce

1. Login with a new user
2. Click on 'Start tutorial' in the pop-up 

### Version

Cloud

**Comment by hiteshjoshi** [comment]
The modal is closing without any errors on the console or any drop from the BE APIs. Possible that modal close is being triggered.
