### ISSUE TITLE
[Bug]: Datepicker resets to today's date when typing in the date/time for certain date format

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you try to change the date/time by typing in the datepicker widget (for eg: DD/MM/YYYY HH:mm format), it defaults to today's date. Only selecting the date and time in the widget works

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/12bd542c76de448fabed025ed8903e4a-00001.gif)](https://www.loom.com/share/12bd542c76de448fabed025ed8903e4a)

### Steps To Reproduce

1. Add a Datepicker widget 
2. Change the format to DD/MM/YYYY HH:mm
3. Try to change the date by typing in the widget and you will notice that it will keep resetting to today's date.

### Public Sample App

https://app.appsmith.com/applications/622f0be20bf98b2d5df769c6/pages/622f0be20bf98b2d5df769c9

### Version

Cloud/Self-hosted - v1.6.14

**Comment by dilippitchika** [comment]
**Formats for which this issue exists**
![Screenshot 2022-03-14 at 5 43 58 PM](https://user-images.githubusercontent.com/19730984/158171090-6f3a85e8-12d1-447c-8db6-acb1ee16a5c5.png)
![Screenshot 2022-03-14 at 5 47 36 PM](https://user-images.githubusercontent.com/19730984/158171100-69f08162-227a-49be-841e-d11feac96b4c.png)
![Screenshot 2022-03-14 at 5 48 26 PM](https://user-images.githubusercontent.com/19730984/158171106-22662d56-5f91-46ac-9495-17399527a878.png)
![Screenshot 2022-03-14 at 5 49 28 PM](https://user-images.githubusercontent.com/19730984/158171112-fee6658f-8e04-4e4b-a876-b432ee257920.png)
![Screenshot 2022-03-14 at 5 49 54 PM](https://user-images.githubusercontent.com/19730984/158171114-16f858ec-c97c-450c-aabc-2deee0131e40.png)

**Comment by dilippitchika** [comment]
Just to add some more context, the app-viewers noticed this when they started copy pasting values. The user's team is not able to move fast because of this functionality which now broke. 

@ankurrsinghal please help me identify how this broke as well, to understand if there are some other unknown issues.

**Comment by ankurrsinghal** [comment]
I think somehow formating for DD/MM/YYYY is getting invalid during editing and parseDate is resetting it. Check here https://github.com/appsmithorg/appsmith/blob/2bf259519d84f48fb99efc6cd5c3d4a16740a789/app/client/src/widgets/DatePickerWidget/component/index.tsx#L207.

I am checking the whole flow to see why its getting invalid. There is lot of formatting going on. I am estimating it I will be able to find the fix by today.

**Comment by ankurrsinghal** [comment]
@dilippitchika Found the problem. I think now we are using DatePickerWidget2 and earlier we were using DatePickerWidget (1). What I understood from both the widgets is that we save date values as strings but the DatePicker change handler gives us Date object, therefore, we reformat it and save it. 

So in DatePickerWidget, we use whatever the currently selected format is but in DatePickerWidget2 we are using date.ISOString() no matter whatever the date format is, there lies the problem, in the DD/MM/YYYY format, the ISO parses it as MM/DD/YYYY therefore whenever you type a date more significant than 12 it reads it as the month which is invalid and defaults to the current date. In the current issue if you try a date less than 12 it works actually.

@danciaclara @Nikhil-Nandagopal

**Comment by ankurrsinghal** [comment]
Here are the code references,

DatePickerWidget (1)
https://github.com/appsmithorg/appsmith/blob/78e562cbb38ed24fe34e447319edfd1b6ed388bc/app/client/src/widgets/DatePickerWidget/component/index.tsx#L222

DatePickerWidget2
https://github.com/appsmithorg/appsmith/blob/78e562cbb38ed24fe34e447319edfd1b6ed388bc/app/client/src/widgets/DatePickerWidget2/component/index.tsx#L245

**Comment by dilippitchika** [comment]
Hey @sbalaji1192 was this change done to support the moment() issue we had? Can you help @ankurrsinghal with what the fix should be?

**Comment by ankurrsinghal** [comment]
@dilippitchika I think the fix is to revert it to what is in the DatePickerWidget (1) if we get to know why we changed it in the first place to ISOString().

**Comment by sbalaji1192** [comment]
@dilippitchika No. This is a completely different issue, not related to the https://github.com/appsmithorg/appsmith/pull/11399

**Comment by ankurrsinghal** [comment]
DP:- https://appsmith-git-fix-datepicker-resets-to-today-11837-get-appsmith.vercel.app/
