### ISSUE TITLE
[Bug]: The old file is replaced with new file in s3 crud page upload

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#11833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user tries to upload the 2nd file in the same folder of the s3 crud page the Images are overlapped instead of Creating the new file
Note: This issue is occurring because all the file names are displayed as undefined
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f6e37cf91f504d9aa63ed6e2949f30c4-00001.gif)](https://www.loom.com/share/f6e37cf91f504d9aa63ed6e2949f30c4)

### Steps To Reproduce

1. generate a S3 crud page
2. now add a folder name as folder 1 and add a file no 1
3. upload a file 
4. Now search for the folder name folder one there will a file 1 displayed
5. Now Try to add a file 2 to the same folder that is folder 1
6. Now the uploaded file 2 replaces file 1 instead of being added as a new file

### Version

release

**Comment by Aishwarya-U-R** [comment]
This is happening when uploading a file directly also. [without using a folder]

**Comment by eco-monk** [comment]
`List.items[0].Input` -> doesn't have `text` property. Hence the file name is `undefined`.

[Sample app export](https://drive.google.com/file/d/1eCefB9fJklRacRTPt4fB6dGCuS0YfoXm/view?usp=sharing)

**Comment by btsgh** [comment]
Discussed with Raksha, found the issue to be fixed in Production environment. Browser Tested on - Chrome

**Comment by btsgh** [comment]
Discussed with @RakshaKShetty, found the issue to be fixed in Production environment. Browser Tested on - Chrome .
