### ISSUE TITLE
[Bug]: Focus lossing while click on multi dropdown  list

### ISSUE THREAD

**Issue by ginjojohny** [appsmithorg/appsmith#11849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I am click on multi dropdown list the focus jumped to the top of the UI and when am click again the dropdown values  are visible.

Before  click on dropdown list

![Screenshot (32)](https://user-images.githubusercontent.com/94359116/158190474-c9c0547d-acbb-49b4-8911-690f26b0f0f9.png)

After click on dropdown list

![Screenshot (34)](https://user-images.githubusercontent.com/94359116/158190505-88bc7e52-f645-4629-99c7-f12308f9759c.png)

After click again on dropdown

![Screenshot (33)](https://user-images.githubusercontent.com/94359116/158190527-31b5ea89-31db-4031-ac30-6784ba8e7e99.png)

### Steps To Reproduce

1. Create a page with multi dropdown list with  more values and add some more widgets before and after dropdown widget .
2. Click on dropdown and check the UI

### Version

Self hosted   v1.6.14

**Comment by dilippitchika** [comment]
Impacts the app viewer directly and it's unclear why this happened. @Tooluloope please triage and prioritise.

**Comment by Tooluloope** [comment]
@dilippitchika @YogeshJayaseelan Could you confirm if this happens only on windows PC or it's browser related.
Couldn't reproduce this on my System.

Also #11485
https://www.loom.com/share/97ec42ea01fc497590e8fb0eb9cdee13

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Both the issues #11849 and #11485 are not reproducible in Mac and Windows 

CC : @shwetha-ramesh
