### ISSUE TITLE
[Bug]: Sequential ID for Table Using JS (Reactive variables)

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#11852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is not able to create a sequence number field for a table widget using JS code.
Data Source: MongoDB

### Steps To Reproduce

1. Connect **MongoDB** as data source for a table widget.
2. Create a **JS Object** called `JSObject1` and include the following code:

```
export default {
id: 0,
getId: () => {
this.id += 1;
return this.id;
}
}
```

**Note**: The code used when Server-Side Pagination is enabled is the following:
```
export default {
id: sales_log_tbl.pageNo -1,
getId: (row) => {
this.id += 1;
return this.id
}
}
```

3. Create a **custom column** in the table widget, and add the following as **Computed Value**:

`{{JSObject1.getId()}}`.

![image](https://user-images.githubusercontent.com/101268423/158206968-4d13ace6-b8db-46e8-9cb9-6a1a985b352e.png)

**Result**: The sequential number is generated incorrectly.

As a workaround, this solution works:
```
﻿ getDataWithIds: () => {
let offset = (Table1.pageNo - 1) * Table1.pageSize;
return Fetch_users_data.data?.map((item, idx) => {
return {
...item,
srno: offset + idx + 1,
}
});
}
```
Binding data to the table with `<js_obj>.getDataWithIds()` and using `currentRow.srno` binding to show the sequence number in a custom column.

### Version

Cloud

**Comment by bharath31** [comment]
@Nikhil-Nandagopal the expectation is for the variable `id` to be mutable since it is used as a temporary state. The function that is used in the binding `getId()` is already reactive.

**Comment by bharath31** [comment]
this is now solved with variable mutation
