### ISSUE TITLE
[Epic]: Application Configuration In Database (ACID)

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#11855]
### Objective

Move application configuration from environment variables into the database. The goal is to reduce our reliance on environment variables, and use the database to store such configuration information.

### Rationale

- Environment variables are powerful. Too powerful to control. They can be set via a very many places depending on the method of deployment.
- Changing them (very usually) needs a restart. So we end up handling these changes two-fold. Update the env file, as well as make the change at runtime, if possible.
- Repeating the environment variables in server/client, causes duplication and quite a few headaches, where something is configured in the client, but not on the server, causing confusions.

### Success Metrics

| Goal          | Metric         |
| ------------- | -------------- |
| Make static assets CDN friendly  | Remove all runtime environment variables in static assets  |
| Make Admin Settings more friendly  | Handle (most, if not all) changes to configuration without needing a restart        |

### Requirements

| Requirement   | User Story    |
| ------------- | ------------- |
| An API for the client to get application configuration from the server | As a user, I should be able to host Appsmith's static assets on a CDN.  |
| Affect application configuration changes without restart | As a user, I should be able to change application configuration without needing a server restart and potential downtime.  |

### Implementation Notes

- The backend server will take the values of whatever settings it needs from the DB and use them.
- The client will request what it needs and gets their values. The backend should maintain a list of what variables can be shared to the client and to what extent.
  - By “what extent”, I mean does the client need the value of a setting, or just to see whether a setting has a non-empty value. This is useful for things like OAuth configuration, where the client doesn’t really need the key, just that it exists and is non-empty.
  - Eventually, the client shouldn’t have any runtime environment variables. All such information should be fetched from the server.
- The Admin settings will need to be wired up to apply changes in the DB, for those settings that are powered by the DB.

### Documentation

For all environment variables that this change was implemented, the documentation needs to be updated to reflect the change. Let's list them in this section as such variables come up during implementation.

### Developer Handoff Document in Figma

No UI change.

### RACI matrix

| ------------- | ------------- |
| Responsible   | @sharat87               |
| Accountable   | @sharat87               |
| Consulted     | @Nikhil-Nandagopal, @mohanarpit, @areyabhishek|
| Informed      |               |

**Comment by sharat87** [comment]
Related Slack thread: <https://theappsmith.slack.com/archives/CPQNLFHTN/p1646815186755609>.

**Comment by sharat87** [comment]
Related Slack thread: <https://theappsmith.slack.com/archives/CPQNLFHTN/p1646815186755609>.

**Comment by sharat87** [comment]
We could probably leverage the `Config` domain that's already defined.

More implementation notes:

1. Each configuration should have a `name`, a `currentValue` and a `defaultValue`. If the `currentValue` is `null` or missing, only then the `defaultValue` is effective. Even if it is `0` or `""`, then we take it as is, and ignore the `defaultValue`.
2. For a given configuration, if it is configured both in the database and as an environment variable, the server gives precedence to the environment variable. But the client completely ignores the environment variable value, and uses whatever the server gives.
3. The client, as part of providing the Admin Settings UI, should be able to see the current effective value of a given configuration `name`, and should also know whether this is the `defaultValue`. This is so that the client can show this in the UI, with a button like `Reset to default`, which is only possible if the client has this information.
4. The client, on startup, gets information on the capabilities and configuration values needed, as part of the `/me` call. This list of which configuration the client can access should be maintained as a whitelist on the server.

The following is a (non-exhaustive, growing) list of configuration that should be moved from environment variables to the database:

```
APPSMITH_CLOUD_HOSTING
APPSMITH_CLOUD_SERVICES_BASE_URL
APPSMITH_DISABLE_INTERCOM
APPSMITH_DISABLE_TELEMETRY
APPSMITH_FORM_LOGIN_DISABLED
APPSMITH_FUSIONCHARTS_LICENSE_KEY
APPSMITH_GOOGLE_MAPS_API_KEY
APPSMITH_INTERCOM_APP_ID
APPSMITH_MAIL_ENABLED
APPSMITH_OAUTH2_GITHUB_CLIENT_ID
APPSMITH_OAUTH2_GOOGLE_CLIENT_ID
APPSMITH_RECAPTCHA_SITE_KEY
APPSMITH_SIGNUP_DISABLED
APPSMITH_VERSION_ID
APPSMITH_VERSION_RELEASE_DATE
```

Note that not all of these are configurable from Admin Settings, and that is as it should be. But nevertheless, the client should get their values from the server.

If possible, let's not move all of these configuration to the DB as part of a single PR. Let's do this incrementally, with smaller PRs, as always.

**Comment by rhuanbarreto** [comment]
Just linking this comment to the same feature
https://github.com/appsmithorg/appsmith/issues/22359#issuecomment-1514753166
