### ISSUE TITLE
[Bug]: UQI : JSON Format Issues

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#11871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When users are in JSON format  fields the following issues are observed 
1) Evaluated values are always UNDEFINED in JSON format
2) Needs error defined appropriated when the user is in JSON format
3) Fields do not get highlighted in red when there are mistakes in syntax

### Steps To Reproduce

1) Navigate to Query pane 
2) Select command in S3_List 
3) Navigate to JSON format and observe

### Version

Release

**Comment by nidhi-nair** [comment]
Closed as part of #12313
