### ISSUE TITLE
[Bug]-[200]:SMTP datasource duplication on application fork

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#11873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From community:
```
can you please explain what you mean by duplicate...does it mean that if there is one SMTP datasource it becomes two in the forked app - or did you mean something else ?

Yes, that's right.  On each fork of the application to another organisation, it appears the SMTP datasource duplicates (e.g SMTP, SMTP (1), SMTP (2)) and on each duplication the authentication details are reset. I would of brushed this off as expected behaviour, but it not the same behaviour with a PostgreSQL datasource for example.
```

Also seen to be happening with JSONObject as mentioned here: https://theappsmith.slack.com/archives/C0341RERY4R/p1647341711977009?thread_ts=1647341621.398129&cid=C0341RERY4R 

### Steps To Reproduce

Writing from user's description:
1. Create an application with SMTP datasource.
2. Fork application.

### Version

self hosted.

**Comment by abhvsn** [comment]
@hiteshjoshi please assign the concerned person

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     |50 |
| Effort (months)  | 0.5|

**Comment by riteshkew** [comment]
Closing this as this is not reproducible.
