### ISSUE TITLE
[Bug]-[1408]:Mongo plugin- smart substitution fails with $regex keyword when input is number

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#11880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From community:
```
{$match: {
  $or:[
  {OrderNumber:{$regex:"{{orders_table.searchText}}"}}
  ]
}} 

Error: error $regex has to be a string. 

can you please share what evaluated value is being substituted for {{orders_table.searchText}}
If there is something in the search box will be “69” other wise “”
```

This issue was resolved upon turning off smart BSON substitution.

### Steps To Reproduce

.

### Version

cloud

**Comment by rohan-arthur** [comment]
reach 683

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 683 |
| Effort (months)  | 0.25 |

**Comment by subrata71** [comment]
After investigating I would say this is not directly related to the data type issue rather integer values are losing the quotes around them when the following regex is applied.

`MustacheHelper`
`private static String regexQuotesTrimming = "([\"']\\?[\"'])";`

```
    public static String replaceMustacheWithPlaceholder(String query, List<String> mustacheBindings) {
        return replaceMustacheUsingPatterns(query, APPSMITH_SUBSTITUTION_PLACEHOLDER, mustacheBindings,
                placeholderTrimmingPattern, APPSMITH_SUBSTITUTION_PLACEHOLDER);
    }
```

But I cannot say either that removing this part i.e. applying`regexQuotesTrimming` to the values and later doing smart substitution to retain the quotes for some data types e.g. String, Date, Time. 

@sondermanish

**Comment by sondermanish** [comment]
Thanks @subrata71 !
For the query Input: `{"release_date": {$regex: "{{"24"}}", $options: "si"}}`  

`private static String replaceMustacheUsingPatterns(String query, String placeholder, List<String> mustacheBindings,
                                                       Pattern sanitizePattern, String replacement) {
        ActionConfiguration actionConfiguration = new ActionConfiguration();
        actionConfiguration.setBody(query);

        Set<String> mustacheSet = new HashSet<>();
        mustacheSet.addAll(mustacheBindings);

        Map<String, String> replaceParamsMap = mustacheSet
                .stream()
                .collect(Collectors.toMap(Function.identity(), v -> placeholder));

        // Replace the mustaches with the values mapped to each mustache in replaceParamsMap
         //{"release_date": {$regex: "{{"24"}}", $options: "si"}}
        ActionConfiguration updatedActionConfiguration = renderFieldValues(actionConfiguration, replaceParamsMap);

        String body = updatedActionConfiguration.getBody();
        
        //{"release_date": {$regex: "#_appsmith_placeholder#", $options: "si"}}
        body = sanitizePattern.matcher(body).replaceAll(replacement); 
        // {"release_date": {$regex: #_appsmith_placeholder#, $options: "si"}} --> this will be further changed to {"release_date": {$regex: 24, $options: "si"}}


        return body;
    }`
    
    The above line removes the quotes from the placeholder if there are no other strings present hence leaving the final data type of the parameter to be decided by the smart substitution only.

**Comment by prapullac** [comment]
@sondermanish : Completed testing on DP and works well

**Comment by subrata71** [comment]
> @sondermanish : Completed testing on DP and works well

Hi @prapullac 
Would you mind adding a `Test Plan Approved` label then?

**Comment by prapullac** [comment]
@subrata71 : I have added it in the PR
