### ISSUE TITLE
[Docs]: Update JS Editor documentation

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#11881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

JS Editor will be coming out of beta by the end of March 2022 and we need to update the documentation with the latest changes.

### Describe the improvement

@ApekshaBhosale to provide new updates
@rohan-arthur to edit/review and give product approval
@Pranay105 to do final editing and publishing

**Comment by jnikhila** [comment]
@ApekshaBhosale / @rohan-arthur / @Pranay105 - Please review the doc - [updated version Async function settings](https://docs.google.com/document/d/1kgu33a_vwyjTMivbtfO9yh3eLtoHbAk4NxWTg7lmEpI/edit#heading=h.90i81dhulqd)

**Comment by jnikhila** [comment]
Review comments closed. cc- @rohan-arthur

**Comment by jnikhila** [comment]
Once the UI changes are updated to cloud the documentation can be released.

**Comment by jnikhila** [comment]
@rohan-arthur - Please review and close the ticket. Doc changes are published and available [here](https://docs.appsmith.com/framework-reference/javascript-editor-beta/asynchronous-javascript-function-settings).

**Comment by rohan-arthur** [comment]
doc is live! :)
