### ISSUE TITLE
[Feature]-[450]:Add an option to create a new organization from fork app pop-up

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

If user wishes to fork an application to a new organization, then they'd need to first create a new organization, go to the app they want to fork and then fork the app. By introducing a "+ create a new organization" option in the dropdown similar to `creating a new datasource on CRUD form`, we'd be reducing user clicks and duration to fork an app to a new application

### Why should this be worked on?

Improving user experience by reducing the number of steps taken to clone an app in a different organization

**Comment by rahulbarwal** [comment]
To make this change we have to update `ForkModal`. This modal is used in 2 places: 
1. Fork application in `/aplications`
2. Fork template in `/templates`

Problems with this:
1. Allowing users to create new workspaces might result in creating a lot of unnecessary workspaces
2. Not all users are going to have access to create workspace
3. If we are looking for the user in `/applications` page, they already have a list of workspaces on left side nav. 

After going through it extensively, we have decided not to pursue this, until we have user requests on this.
