### ISSUE TITLE
[Bug]: function arguments tooltip multi-line

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#11899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

this is a follow-up to #4789 - with that issue, the user will be able to see the tooltip if they are writing and completing the function call in a single line. However, the tooltip does not appear for multiple lines, example:
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631353331666532396433353437356531333438323537342f37626532623965632d353437662d343934662d613261652d663930666139613538393739](https://user-images.githubusercontent.com/94514895/158571363-3423dffe-426e-4967-b880-bf33ec473297.png)

With this issue, the user should be able to see the function argument tooltip just the same, whether they are using single or several lines.

### Why should this be worked on?

this is an incremental change to #4789 , and improves the user experience

**Comment by bharath31** [comment]
tracking this under the main feature https://github.com/appsmithorg/appsmith/issues/11899
