### ISSUE TITLE
[Bug]: Modal widget takes a lot of time to open

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#11901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The modal widget is taking more than 2 sec to open.
User Recording -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/62ffe2d2dfa742978eb76fc1d4420290-00001.gif)](https://www.loom.com/share/62ffe2d2dfa742978eb76fc1d4420290)

### Steps To Reproduce

User has shared their app with us - https://theappsmith.slack.com/archives/C024GUDM0LT/p1647341275401519

### Version

Self-Hosted

**Comment by SatishGandham** [comment]
This is because
- The tables selected row changes, and it re-renders.
- The modal content itself takes time to render.

Try to open the modal before the table renders, optimise the modal content, which means optimizing the individual widgets.

**Comment by ramsaptami** [comment]
Can we also show a loading state/icon when modal widget is taking time to load? UX goes into a grey area while waiting for something to happen between triggering the modal to open and the modal actually appearing on screen.

**Comment by dilippitchika** [comment]
Agreed with Saptami's suggestion. Is there something we can do to communicate data is still loading?

**Comment by Nikhil-Nandagopal** [comment]
Let's not take the focus away from the real problem. The modal has to open as soon as a user selects it. The time between a user interaction and the UI responding has to be < 100ms

**Comment by somangshu** [comment]
This is still faced by another user, Conversation thread [here](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1664446560000649)

**Comment by dilippitchika** [comment]
@somangshu what are the next steps we can take here to analyse this issue?

**Comment by somangshu** [comment]
No actionability on this as of now, we will have to link this to #15699 and take it up as a perf EPIC. 
Right now only table performance is identified as a bottle neck and is being worked on. 

Also the problem was kinda related table optimization as you can see that the table operation delay the modal from opening. 

cc @vsvamsi1 something to consider while working on table widget optimization. Can you link you task here or vice versa

**Comment by vsvamsi1** [comment]
sure @somangshu  here is the task https://app.zenhub.com/workspaces/app-viewers-pod-616922264a5ea000108d319d/issues/gh/appsmithorg/appsmith/20910

**Comment by somangshu** [comment]
The optimization is still not a part of the issue you are point to? We need to pick this up while stress testing other widget for perf optimization!

**Comment by vsvamsi1** [comment]
Hi @somangshu, I tried analysing opening a very simple Modal and i don't think it is related to the table. I have observed that the eval computations seems to be contributing to the latency. The latency is correlated to the size of the data set as mentioned in this document as well [https://www.notion.so/appsmith/postMessage-transmission-overhead-af6231604efa4daea27edb28d2e7653a](post message overhead). This also affects us opening the modal from a lighter table in an app having a heavier table. The open modal operation from both the tables took about the same amount of time. I think the issue us alway carrying the heavy widget data for eval computations. 
There are two significant eval executions initiated from these sagas to open the modal
- initiateActionTriggerExecution
- showModalSaga
After the execution does the state get updated to open the modal. For a dataset of 9000 records the two evaluations took about 9 seconds to complete. [Screenshot 2023-03-25 at 4.32.13 PM.png](https://images.zenhubusercontent.com/63aacee5532b0364c531f322/096d6b95-78eb-4b8c-97c2-a6b09aec8bce)

**Comment by Harshithazemoso** [comment]
@pranavkanade I have picked up this issue and observed the following:

Normal Modal: Loads with a 5ms delay, without any noticeable latency.
Table Edit Modals: These modals are taking approximately 60ms to load.
Could you please confirm if the issue has been resolved, or if further investigation is needed?

**Comment by Harshithazemoso** [comment]
hello @pranavkanade I have recorded the video for the issue ,where the modal widget is not taking more than 2 seconds to load in both normal widget and in a table where there are 25 entries .
[Video:Showing data modal takes less time for loading](https://www.loom.com/share/737a749c149c4d84b1ed2a21ac1db5b0?sid=524e5580-7ac5-4db6-8a0b-c1c620a05d47)

**Comment by vsvamsi1** [comment]
Hi @pranavkanade I just want to verify if your experience has gotten better, We have taken multiple steps to optimise our code based on your feedback. Please let us if it is still a persistent issue, if isn't can you please close the ticket.

**Comment by vsvamsi1** [comment]
Hi @pranavkanade I will close the ticket for now, let me know if its still an issue and we can reopen it.
