### ISSUE TITLE
[Epic]: Select widget family - stability

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#11902]
### Objective

Improve the select widgets by addressing code, default and consistency behaviours which will stabilise the widget

Select and multi select widgets
- Code #10575
- Default behaviour
   - [x] #12225
   - [x] #12554
   - [ ] #12531
   - [ ] #13664 
   - [x] #13665
- consistency in UX and UI 
    - [ ] #7259 
    - [ ] #9550 
    - [ ] #6780
    - [ ] #9424
    - [ ] #12660
 
The select widget today has too many breaking use case, specially after the v2. Even the codebase has a lot of unused styles which is difficult to maintain, more things can be observed if an in-depth analysis of code is conducted. We also need to think about the DX consistently across select family, Like handling the validations on default value in different widgets.

### Success Metrics

| Goal          | Metric         |
| ------------- | -------------- |
| Consistent UI and UX  | We need to look at the interactions the widget has and make it consistent, This needs to happen for the UI too   |
| Simplify DX  | User should not have a hard time setting up properties like default value. |

### Requirements

| Requirement   | User Story    |
| ------------- | ------------- |
| code refactor  | use the minimum code that is required, abstract the styles common to all widgets in the family, performance profile and find out any other changes  |
| `default value` & `validations` refactor |  The select widget family has been reported to produce inconsistent DX and Bugs while setting up the default value, Wrong or unclear validation was also shown  |
| UI and UX consistency | UI and interactions need to be made consistent across the select widgets, ex the popup opening, or the selected and hover state of options etc. |

### Documentation

- some changes will be required around the fixes made on DX / default value / validation

### Out of Scope

- Other enhancements that are listed by users or otherwise

### RACI matrix

| | |
| ------------- | ------------- |
| Responsible   |       @souma-ghosh         |
| Accountable   |        @souma-ghosh       |
| Consulted     | @ashit-rath @Nikhil-Nandagopal @Tooluloope  |
| Informed      |      @somangshu @dilippitchika          |

**Comment by Nikhil-Nandagopal** [comment]
@somangshu can we add #11844 also to this

**Comment by Tooluloope** [comment]
@Nikhil-Nandagopal I think this is being fixed here https://github.com/appsmithorg/appsmith/pull/10600

**Comment by Tooluloope** [comment]
@momcilo-appsmith @jsartisan, Currently, is there any design fix in the Select family?

**Comment by momcilo-appsmith** [comment]
There are no updates to functionality that I know of. The only updates are the ones for the inconsistencies between the widgets that we found earlier @Tooluloope.

**Comment by dilippitchika** [comment]
Priority issues for me, which should be picked up right now (outside of this epic)
1.  https://github.com/appsmithorg/appsmith/issues/11849 - Raised by community and very annoying experience
2. https://github.com/appsmithorg/appsmith/issues/11485 - Same issue as #11849 happening in tabs
3. https://github.com/appsmithorg/appsmith/issues/12020 - Default value should first search in the options. 

Looks like multi-select widget needs some more effort than select widget.

**Comment by somangshu** [comment]
@dilippitchika iin case we want to take this up separately lets create a new issue / epic and address it, Is our goal clear?

**Comment by Tooluloope** [comment]
#12020 is waiting to be merged.
Gone through QA

**Comment by dilippitchika** [comment]
## Suggested Milestone 1

- [ ] #10575
- [ ] #12531
- [ ] #13664 
- [ ] #13665
- [ ] #12225 
- [ ] #12554

@somangshu @Tooluloope please review this, i have updated the issues in the list and think that these issues should be shipped first. They need not be shipped together, but the idea is we can divide this epic into milestones and keep tracking.

**Comment by somangshu** [comment]
Cc @souma-ghosh

**Comment by dilippitchika** [comment]
@somangshu a valid suggestion from Nikhil was to use epic currently for select and multi select widgets and not the tree select widget because of the lower reach of the widgets, barring one issue https://github.com/appsmithorg/appsmith/issues/11485

We could re-evaluate if we want to work on tree and multi-tree-select once we are done with the milestone 1 and we should be okay to to pick them up later. This would also shorten the scope a lot. Any concerns with this approach?

**Comment by dilippitchika** [comment]
NOT IN SCOPE, just documenting for reference

Tree select and multi-tree-select
- [ ] #11485
- [ ] #13674  
    - [ ] #12235 
    - [ ] #10847
    - [ ] #12609

**Comment by dilippitchika** [comment]
Updated the scope of the epic to only contain select and multiselect for now

**Comment by dilippitchika** [comment]
18 May

Action items

- [ ] @dilippitchika to update the issues in the epic so that they are linked - Deadline 18 May
- [ ]  @souma-ghosh to go over all the issues in the epic and understand the context better with Tolu and Ashit's help - Deadline 23 May
- [ ] @souma-ghosh to work on a tech spec and get back to us.
