### ISSUE TITLE
[Feature]-[1666.6666666666667]:response tab behaviour on JS Editor

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#11904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This issue is not meant for direct implementation, rather we will use this for discussion, design and decision.

We have a new design for JS Editor with #10387 

According to the [design](https://www.figma.com/file/sT3HR1VSWOTtPfh5vlpU8x/JS-Editor-Improvements?node-id=2%3A2), the response tab should have been collapsed by default, in order to show a large editor area to the user. However, in doing so, we had not thought about the specific triggers that should cause the expansion of the response tab:
1. When user runs a function --> already done with 10387
2. When there are errors 
3. ....

Also to bear in mind while planning and designing a solution for this: whether it is desirable for the response tab's expand/collapse behaviour to be normalised across the application, or are we fine with having a specialised behaviour only for JS Editor.

### Why should this be worked on?

Collapsing the response tab by default allows the user to have more "real estate" when they first open the code editor. 
However, this comes with the caveat that the behaviour of the response tab/debugger is pretty much "set" in the rest of the application, and should we:
- have a different behaviour only for JS Editor, or
- change the behaviour of the tab across the application

**Comment by rohan-arthur** [comment]
May be related #6114

**Comment by rohan-arthur** [comment]
JS editor unique usage, 6m: 2500

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2500 |
| Effort (months)  | <<number>> |

**Comment by ayushpahwa** [comment]
JS editor unique usage, 6m: 2500

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2500 |
| Effort (months)  | 0.75 |
