### ISSUE TITLE
[Enhancement] Import template through cloud services

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#11900]
We need to import the template application through cloud services. Currently, the application JSON file is stored in a external server and that file is downloaded by the appsmith server. This may lead to problem as we've only dependency on cloud services.

Instead of adding a new dependency on a third party, we should use cloud services as a proxy to that server for this API.

**Comment by hiteshjoshi** [comment]
- Discuss with Team DevOps
- Container need download access for downloaded files

**Comment by ramsaptami** [comment]
Closing this as verified since templates are forkable

>  Actually the API calls are made from backend. One way to test this is to monitor the network calls from backend. Another way to test is - disable network access to aws s3 from backend server and test whether fork is working or not. BTW both of them are quite complicated.
Also it's a very low priority issue, you can close it as long as the templates are forkable
