### ISSUE TITLE
[Bug]-[115]:Unable to use "this." literally on JSObjects

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#11912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A string that has `this.` is converted to JS Object's name!

<img width="890" alt="Screenshot 2022-03-16 at 6 04 37 PM" src="https://user-images.githubusercontent.com/10436935/158591770-785493ee-1da6-4e2c-aa8d-54450ba8ea4a.png">

The temporary solution is to escape the dot (`"this\\.").

### Steps To Reproduce

1. Create a JSObject
2. Write some code that has a string containing `this.`
3. Run the function and see the output

### Public Sample App

https://app.appsmith.com/applications/6231d849f1c0af1ceded57e3/pages/6231d849f1c0af1ceded57e6

### Version

Cloud v1.6.15

**Comment by eco-monk** [comment]
Also related to #12315
