### ISSUE TITLE
[Bug]: Animation is not consistent in Progress Bar widget

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#11915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Animation of progress bar doesn't work if the value is going from zero or going to zero

https://user-images.githubusercontent.com/10436935/158615274-43a28bfd-ec0b-49fb-a4f0-05d55e45562d.mov

### Steps To Reproduce

1. Add a progress bar widget
2. set the value to 0
3. set the value to 50 and there won't be any smooth transition
4. set the value to 100 and the transition will be smoother
5. set the value to 25 and see the transition will be smoother here as well
6. set the value to 0 and see no transition!

### Version

Cloud v1.6.15

**Comment by ARibeiro3110** [comment]
Hello! I'm interested in contributing to Appsmith by fixing this bug. Could you please assign this issue to me?
