### ISSUE TITLE
JSON Form documentation

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11921]
Please add documentation for JSON form

https://www.notion.so/appsmith/JSON-form-documentation-a5ca3fef7c9c4c27be175e216d6d6fde

**Comment by Pranay105** [comment]
@cokoghenun needs video.

**Comment by cokoghenun** [comment]
@Pranay105  Video has been recorded. Should be ready next week

**Comment by cokoghenun** [comment]
@Pranay105 this is done and the video has been scheduled. You'll get a PR soon

**Comment by jnikhila** [comment]
@cokoghenun, @Pranay105 - Is this completed?
