### ISSUE TITLE
Deploy Same App to Multiple Orgs Programmatically

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#11922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Use case:
The user needs to deploy the same app to multiple organizations. The user has an on-premises setup, and the app is in git. They need to programmatically publish it to each organizations (any API endpoint?) without having to manually import the app to each Organization.
Ideally, they would like to use the GitLab pipeline and deploy the same app to multiple Orgs.

### Why should this be worked on?

This feature improves user experience, as it saves users a lot of time and effort when they have to deploy the same app to multiple organizations.

**Comment by Nikhil-Nandagopal** [comment]
Hi @ame-appsmith , I think this will be solved with #5971 and git import so I'm closing this in favor of those
