### ISSUE TITLE
[Bug]: Square brackets property accessor throws undefined in JSObjects

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#11926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you use square brackets to access an object's property, it returns undefined.

<img width="1204" alt="Screenshot 2022-03-17 at 11 49 07 AM" src="https://user-images.githubusercontent.com/32227135/158748807-1ed76340-49c4-4575-b0df-f02736f3a383.png">

### Steps To Reproduce

Use this code

```
export default {
  lala: "dddddd",
    querySelector: () => {
			console.log(this.lala);
			console.log(this['lala']);
    },
}
```

### Version

Cloud/Self-Hosted - v1.6.15

**Comment by rfenaux** [comment]
Hi there, any update on this ?

**Comment by Nikhil-Nandagopal** [comment]
@rfenaux is there any reason you cannot simply use the dot notation to access this?
`this.varName`

**Comment by rfenaux** [comment]
Hello, any update on this ?

**Comment by ApekshaBhosale** [comment]
Hello @rfenaux , we found the issue. Will try to get this fixed soon. I will update you accordingly

**Comment by bharath31** [comment]
@ApekshaBhosale did we manage to find a potential fix for this issue?
