### ISSUE TITLE
[Bug]-[1500]:Upon adding a new JSObj/Query/Blank API's - EntityExplorer should show the new item in the expanded tree

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#11937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

.png: 
<img width="630" alt="Screenshot 2022-03-17 at 1 53 36 PM" src="https://user-images.githubusercontent.com/91450662/158785172-38abfd6d-e869-497e-ac5a-d2e45686b881.png">

### Steps To Reproduce

1. Create a new application
2. Add a new JSObject/Query/Blank API
3. User should be able to see the item added in the left side tree - as a confirmation that new item being created is added [as visible before]
4. Once user expands/collapses the Queries/JS or DataSources sections - then that state should be preserved upon different navigations/page refreshes etc.,
5. For older apps - the state can be preserved as decided by user
6. This bug addresses only the experience during a new application creation

### Version

Cloud Release v1.6.15

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3000 |
| Effort (months)  | 1|

**Comment by Aishwarya-U-R** [comment]
@arunvjn On an existing application -> Adding a new Page or New Application -> First page - Does not still have the Queries/JS open & so no indication of a newly added Api/Query/JSObject to the user.
Point 6 from this bug is not addressed. Hence reopening the bug.

**Comment by Richarex** [comment]
- [ ] when we add Queries/Datasource and hit on the back button then it is not navigating back to the canvas instead it opens the  datasource page. Please refer the video attached:- https://jIju8JbmWA.vmaker.com/record/CAuXSLz5ZiZPEqDy

**Comment by hetunandu** [comment]
> @hetunandu
> 
> * [ ]  when we add Queries/Datasource and hit on the back button then it is not navigating back to the canvas instead it opens the  datasource page. Please refer the video attached:- https://jIju8JbmWA.vmaker.com/record/CAuXSLz5ZiZPEqDy
> * [ ]  Getting "Internal server error while processing request" when clicked on the Save and Authorize button from the datasource page. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/Fy3Hsamk4MyOoEwD

These issues are unrelated to the change and already existing in prod

**Comment by Richarex** [comment]
This issue is fixed verified it on the DP url.
