### ISSUE TITLE
[Bug]: Border and container have gaps when both are coloured

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When border and background of a widget is coloured then there's an inconsistent gap observed between the 2 colors. This is more pronounced when the border radius is set for the widget.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e4590278338a4ca486b9f9dbfc466c17-00001.gif)](https://www.loom.com/share/e4590278338a4ca486b9f9dbfc466c17)

### Steps To Reproduce

1. Add background and border colours on a container widget and observe the gap between the two colours being inconsistent as seen in the video
2. Add a border radius and observe the gap becomes more awkward.

### Version

Cloud

**Comment by ashit-rath** [comment]
@dilippitchika Need to triage for hacktoberfest
cc: @Tooluloope

**Comment by Tooluloope** [comment]
Fixed already
