### ISSUE TITLE
[Bug]-[100]:Need a divider between org list and quick help on home page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Need a divider between org list and quick help (?) on the home page. The current design makes it hard to distinguish where organization list ends and where the help section begins with a quick glance. 

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/158826622-63e10014-334d-4456-a080-583a7fc811d4.png)

### Version

Cloud

**Comment by noobyogi0010** [comment]
Hey @ramsaptami @Nikhil-Nandagopal 
I would love to work on this issue. Is it still open for work?
Thanks!

**Comment by hiteshjoshi** [comment]
@noobyogi0010 I will try to get an update on UI and then maybe you can work on this issue.

**Comment by noobyogi0010** [comment]
@hiteshjoshi Alright. I'll be waiting for your reply!
Thanks!

**Comment by hiteshjoshi** [comment]
Hi! @noobyogi0010 
The UI for this needs some work. I will follow up once we have something.

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
