### ISSUE TITLE
[Bug] update layout and update action API fail when multiple successive calls are made

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1194]
## Description

The updateLayout API has a longer response time for some users and stacking multiple calls successively eventually causes multiple timeouts. This also leads to some calls responding 400 from the server but the same doesn't reach the client.

Core things to fix
- Erratic response times
- Queuing on the frontend (updateLayout & updateAction)
- 400 requests

**Comment by prapullac** [comment]
Verified the issue and working as expected
