### ISSUE TITLE
[Bug]: Unable to use Oauth2 REST api

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#11952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to use Oauth2 REST api. I am trying to use monday.com. My guess is it is unable able to populate Bearer token or Documentation is insufficeint 

### Steps To Reproduce

1. In monday.com create an app for appsmtih.
2. Featch credentials
3. Add Ouath2 datasource and authenticate the app. (Please make sure you have update callback url)

### Version

Self Hosted latest release

**Comment by yatinappsmith** [comment]
I was able to use Oauth2 working with dropbox. I am still keeping the priority as critical as we lack documentation and debugging for Oauth. I am still unable to use monday.com

**Comment by leotom2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BE-Coders-Pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/11952?planning-poker) with ZenHub @nidhi-nair @sumitsum

**Comment by yatinappsmith** [comment]
Adding a lable critical, as while verifying this issue my existing Oauth 2 apss have stopped working.

**Comment by yatinappsmith** [comment]
Dropbox issue is resolved

**Comment by yatinappsmith** [comment]
Going too and fro dropbox issue still present on cloud but not on selfhosted

**Comment by yatinappsmith** [comment]
Reopening this as facing dropbox issue on release

**Comment by yatinappsmith** [comment]
![image](https://user-images.githubusercontent.com/84702014/167829539-b466ebe6-6d9b-4664-bb1f-f62fbdc60467.png)
