### ISSUE TITLE
[Bug]: Remove login form on signup page if it is disabled & update UI based on Design QA

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#11956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- When form login is disabled, the signup screen still shows form login.
- Update the UI based on suggestions given during Design QA.
- Update some cypress tests.

Design QA changes to be done:
- download button margin bottom - 24px
- toggle up and down 8px, top -20 left 58
- send test email button spacing reduce
- redirect URL ? should work on hover
- copy icon should be outside the main block for redirect url
- tooltip for green tick - form login is enabled 

### Steps To Reproduce

- Go to Admin Settings and disable form login.
- Sign out and check the signup screen.
- Login form still exists on the signup screen but is hidden on the login screen.

### Version

Self Hosted - latest

**Comment by Sabbirhosenali** [comment]
I want remove login page
