### ISSUE TITLE
[Bug]: appsmith server/container won't start if Admin Setting: Instance Name contains spaces

### ISSUE THREAD

**Issue by kavhad** [appsmithorg/appsmith#11966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the Admin Setting "Instance Name" )is changed and contains space characters between words the server won't startup after restart.

The following error is shown in the docker logs:
`appsmith       | /appsmith-stacks/configuration/docker.env: line 94: **<First word of Instance Name>**: command not found`

I manually changed the setting in docker.env filed and removed the space character and the server started correctly after that.

### Steps To Reproduce

1. Go to 'Admin Settings > General'
2. Change field 'Instance Name' to a name that contain multiple words separated by space.
3. Restart server/container.
 

### Version

v1.6.16

**Comment by akash-codemonk** [comment]
Unable to repro. Changed the instance name in admin settings page to have space between words. The app seems to run fine after save and restart.

**Comment by sharat87** [comment]
Hey @kavhad, thanks for reporting. This issue should've been fixed by https://github.com/appsmithorg/appsmith/pull/11799, which is part of the latest release published yesterday. Can you pull the latest image again and check with that please?
