### ISSUE TITLE
[Feature]: Make custom fusion chart not to refresh on change of data

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#11962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

If I create a custom fusion chart and bind it to a widget or appsmithStore, the chart refreshes every time when the widget's value or appsmithStore value changes.
There should be some way to make this change smoother without refreshing the entire chart.

### Why should this be worked on?

![chart](https://user-images.githubusercontent.com/10436935/158950949-da8ec80b-f06f-40e5-a4be-a6e4450b1639.gif)
Custom chart config:
```
{
  "type": "cylinder",
  "dataSource": {
    "chart": {
        "subcaptionFontBold": "0",
                "cylFillColor":{{appsmith.store.power>20?"03B365":"DD4B34"}},
        "lowerLimit": "0",
        "upperLimit": "100",
        "lowerLimitDisplay": "Empty",
        "upperLimitDisplay": "Full",
        "numberSuffix": " %",
        "showhovereffect": "1",
        "theme": "fusion"
    },
    "value": {{appsmith.store.power}}
  }
}
```
This was requested by a [user in Discord](https://discord.com/channels/725602949748752515/954176816719994890).

This will be really useful in plotting some real-time data.

**Comment by dilippitchika** [comment]
@techbhavin can you investigate if this is possible?

**Comment by dilippitchika** [comment]
Please let us know the estimate and the fix before trying to pick this up

**Comment by techbhavin** [comment]
@dilippitchika  

Here the issue is on the `componentDidUpdate` chart is rendered every time to prevent refresh every time we need to update only data instead of updating all custom-chart every time.
