### ISSUE TITLE
[Bug]: Fork template button looks weird in safari

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to fork a template, I don't see the button clearly in safari
![Screenshot 2022-03-18 at 11 56 54 AM](https://user-images.githubusercontent.com/19730984/158949084-64a09587-2325-4d71-a078-5b5c032a87b0.png)

### Steps To Reproduce

1. Go to safari
2. Open release app
3. Select the template you want to fork
4. Fork it

### Version

Release

**Comment by hiteshjoshi** [comment]
@albinAppsmith can we check if this is coming from the design system?
