### ISSUE TITLE
[Bug]-[1392]:Curl import corrupts data

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#11977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Curl import corrupted

### Steps To Reproduce

Try importing curl for 
```
curl -X POST https://api.eu.sparkpost.com/api/v1/transmissions -H 'Authorization: <APIKEY>' -H 'Content-Type: application/json' -d '{
   "options":{
      "open_tracking":false,
      "click_tracking":false,
      "inline_css":false
   },
   "recipients":[
      {
         "address":{
            "email":"user@domain.tld",
            "name":"user"
         }
      }
   ],
   "content":{
      "from":{
         "name":"sender",
         "email":"sender@domain.tld"
      },
      "reply_to":"replyto@domain.tld",
      "subject":"subject",
      "text":"textbody",
      "attachments":[
         {
            "name":"attachmentname.pdf",
            "type":"application/pdf",
            "data":"'$(cat test.pdf | base64 --wrap=0)'"
         }
      ]
   }
}'
```

### Version

self hosted

**Comment by rohan-arthur** [comment]
reach 1183

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1183 |
| Effort (months)  | 0.5 |

**Comment by nidhi-nair** [comment]
@yatinappsmith The curl import gets corrupted because of this line: 
```
"data":"'$(cat test.pdf | base64 --wrap=0)'"
```
The command is expecting a sub-shell to run, and parse the inner command, but Appsmith would not be initializing a sub-shell in any sense. The command is therefore not going to perform the expected manipulation. What do you think is a good way to handle this?

**Comment by yatinappsmith** [comment]
@nidhi-nair can we fail this curl cmd with a proper error?

**Comment by nidhi-nair** [comment]
Sounds good. I'll be sending an error for a toast message as this: 

<img width="310" alt="Screenshot 2022-05-04 at 3 14 28 PM" src="https://user-images.githubusercontent.com/5298848/166659080-ba86899d-1fcd-4d82-b90b-30cd714726f5.png">

Scenarios covered:
1. Sub-shell called within double quotes with `$()` or with ``` `` ```
2. Sub-shell called outside of quotes with `$()` or with ``` `` ```

**Comment by yatinappsmith** [comment]
Verified https://www.loom.com/share/f9751a616bfe4569976bda22ff0cf2d2
