### ISSUE TITLE
[Bug]-[3600]:When Gsheet is created using CRUD the update does not work

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#11978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

precondition: Consider we have a Gsheet with only header and we create a CRUD page using the same Gsheet and it is observed that the data does not get updated with insert query until it is Gsheet is added with a value on the sheet.  

### Steps To Reproduce

1) Create a Gsheet using the Appsmith Query 
2) Click on "Generate page" and select the name 
and observe header is not added and is always displayed as col_1 etc 

### Version

release

**Comment by rohan-arthur** [comment]
CRUD usage: 3000
gsheets usage: 15%

reach: 450

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 450 |
| Effort (months)  | 0.25 |

**Comment by Nikhil-Nandagopal** [comment]
Should be working now
