### ISSUE TITLE
[Bug] Loader is not displayed to user on changing the roles

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#1198]
## Steps to reproduce

1. Navigate to Organisational setting 
2. Click on Members 
3. Now change the role 

Ensure your an admin

## Observation

It is observed that on changing the role of a  user the loader is not displayed to user.

## Expected behaviour

Loader must be displayed to user when the role is updated. This would help the user to know that there is action that is taking place in the backend

**Comment by prapullac** [comment]
Verified the issue and is working as expected
