### ISSUE TITLE
[Feature] HubSpot CMS HubDB API Saas Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#11984]
### Description: 

HubDB is a relational datastore that presents data as rows, columns, and cells in a table, much like a spreadsheet. HubDB tables can be added or modified in the HubSpot CMS.

------------------------
### Documentation:

https://developers.hubspot.com/docs/api/cms/hubdb

------------------------
### TO-DO

------------------------
### API Actions Progress
| Action                             | EngSpec Doc | SaaS Manager App | SaaS App Run | Test App Run |QA  |
| ---                                | ---         | ---              | ---    | --- | --- |
| Get Published Tables               | Yes         | Yes              | Yes     | Yes  |No  |
| Create Table                       | Yes         | Yes              | Yes     | Yes  |No  |
| Return Draft Tables                | Yes         | No               | No    | No  |No  |
| Get Details Published Table   | Yes         | Yes               | Yes    | Yes  |No  |
| Archive Table                      | Yes         | Yes               | Yes     | Yes |No  |
| Get Details Draft Table            | Yes         | No               | No     | No  |No  |
| Update Existing Table              | Yes         | Yes               | Yes   | Yes  |No  |
| Clone Table                        | Yes         | Yes               | Yes     | Yes  |No  |
| Export Draft Table                 | Yes          | No               | No     | No  |No  |
| Import Data Into Draft Table       | No          | No               | No     | No  |No  |
| Publish Table From Draft           | Yes         | No               | No     | No  |No  |
| Reset Draft Table                  | Yes          | No               | No     | No  |No  |
| Export Published Version Table     | Yes          | Yes               | Yes     | Yes  |No  |
| Unpublish Table                    | Yes          | Yes               | Yes     | Yes  |No  |
| Get Rows Table                     | Yes         | Yes               | Yes     | Yes  |No  |
| Add New Row Table                  | Yes          | Yes               | Yes     | Yes  |No  |
| Get Rows From Draft Table          | No          | No               | No     | No  |No  |
| Get Table Row                      | Yes          | Yes               | Yes     | Yes  |No  |
| Get Row From Draft Table           | No          | No               | No     | No  |No  |
| Update Existing Row                | Yes          | Yes               | Yes     | Yes  |No  |
| Replace Existing Row               | Yes          | Yes               | Yes    | Yes  |No  |
| Permanently Delete Row             | Yes          | Yes               | Yes     | Yes  |No  |
| Clone Row                          | Yes          | Yes              | Yes     | Yes  |No  |
| Get Set Rows                       | Yes          | Yes               | Yes     | Yes  |No  |
| Clone Rows In Batch                | No          | No               | No     | No  |No  |
| Create Rows In Batch               | No          | No               | No     | No  |No  |
| Permanently Delete Rows            | Yes          | Yes               | Yes     | Yes  |No  |
| Get Set Rows From Draft Table      | No          | No               | No     | No  |No  |
| Replace Rows In Batch Draft Table  | No          | No               | No     | No  |No  |
| Update Rows In Batch Draft Table   | No          | No               | No     | No  |No  |

------------------------
### Notes 

The CMS API provides a set of endpoints focused on batch operations. Such operations implement the same functionality of the “Basic” endpoints but with a different request object to pass batches of data (create, update, delete, etc). At the moment we won’t be adding the Batch actions since the functionality will be duplicated with the basic variants.

**Comment by felixsuarez0727** [comment]
This is current status. Unchecked boxes will be completed for next sprint:
![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/f21e9a8e-ab77-4643-8285-25c3eb8c38e7)

**Comment by btsgh** [comment]
Test cases are available here - 
1. [Basic Test](https://github.com/appsmithorg/TestSmith/issues/1808)
2. [Get Published Tables](https://github.com/appsmithorg/TestSmith/issues/1809)
3. [Create Tables](https://github.com/appsmithorg/TestSmith/issues/1813)
4. [Update Existing Table](https://github.com/appsmithorg/TestSmith/issues/1821)
5. [Archive Table](https://github.com/appsmithorg/TestSmith/issues/1825)
6. [Get Details Published Table](https://github.com/appsmithorg/TestSmith/issues/1826)
7. [Clone Table](https://github.com/appsmithorg/TestSmith/issues/1831)
8.

**Comment by btsgh** [comment]
Issues observed so far : 
1. First creation of API, when we click on each of the fields, whether the fields are blank.  or are having data, the evaluated value shows up as undefined. ![HubSpotCMSHubDB_undefined.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/978bb9ab-9a42-4364-a925-d3a212724add)
2. No Response codes, or API return codes.
3.  When the field is empty, the expected result is it should show records all records, including true and false records.
However at present it shows only records having archive as false.
4. [Get Published Tables -> Archive](https://github.com/appsmithorg/TestSmith/issues/1812) - When the field is empty, the expected result is it should show records all records, including true and false records. However at present it shows only records having archive as false.
5. Create table fails in this scenario - https://www.loom.com/share/178f48c7ee5141b29c1b3630b5b53964
6. Create table [Scenario7](https://github.com/appsmithorg/TestSmith/issues/1820) - fails -an error message comes up. 
Either the table should get created successfully or the Dynamic tag field should be marked as mandatory
7. Update Existing Table - What is the difference between Table ID / Name field and just the Name field? Why are there two fields?
8. Update Existing Table [Scenario 2](https://github.com/appsmithorg/TestSmith/issues/1823) - If Dynamic meta tag field (which is not a required field) is empty , the query fails. This behaviour is incorrect. The query should pass, or the above field should be marked required.. ![HubSpotCMSHubDB_DynamicMetaTagBlankError.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/5b460c4c-1651-4cce-956d-d56abe88e78f)
9. Archive Table - fails. ![HubSpotCMSHubDB_ArchiveFail.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/7def3100-bb65-4cbf-a571-bcbeb8ec8f69)
10. [Get Details Published Table](https://github.com/appsmithorg/TestSmith/issues/1826) - the run passes though the mandatory field of Table Id or name is blank! All table details are listed
11. [Clone Table](https://github.com/appsmithorg/TestSmith/issues/1831) - mandatory fields have missing *![HubspotCMSHubDB_CloneTable_Missing*.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/151efca4-f8be-425b-8361-4b3d5d00a4b1)
https://www.loom.com/share/8fa5beda8d104781a778245a64da2567
12. Clone table [scenario4](https://github.com/appsmithorg/TestSmith/issues/1835) - Error message comes but no valid information to user
13. Unpublish table [scenario1](https://github.com/appsmithorg/TestSmith/issues/1838) , [scenario2](https://github.com/appsmithorg/TestSmith/issues/1839) and [scenario3](https://github.com/appsmithorg/TestSmith/issues/1841)- The query passes, but the table is still listed in the get published tables query ... They should not get listed in the published tables on unpublishing. 
14. Get Rows Table [Scenario2](https://github.com/appsmithorg/TestSmith/issues/1844) - Total still shows 4, though only one is displayed.. Total should come up as 1. 
15. [Get Table Row](https://github.com/appsmithorg/TestSmith/issues/1846) - What is the difference between Get rows table and Get table row? Test 2 fails as the scenario runs
16. [Export Published Version Table](https://github.com/appsmithorg/TestSmith/issues/1847) - Test 3 gives garbled characters. What formats does it take?
17. [Add New Row Table](https://github.com/appsmithorg/TestSmith/issues/1848) - Test1 and Test2 does not give the correct error message
18. [Update Existing Row](https://github.com/appsmithorg/TestSmith/issues/1849) - Test1 - The error displayed is incorrect
19. [Replace Existing Row](https://github.com/appsmithorg/TestSmith/issues/1850) - Test1 error is not appropriate
20. [GetSetRows](https://github.com/appsmithorg/TestSmith/issues/1851) -  Test1/ Test2- error message does not make sense
21. [Permanently Delete Rows](https://github.com/appsmithorg/TestSmith/issues/1852) - Test1/ Test2- error message does not make sense
22. Issue with Permanently Delete a Row - https://www.loom.com/share/96247ff71d4b437380c7eea1193b8331
23. Replace existing row - issue - https://www.loom.com/share/8e0fb4212ab143cd9ae866a51bbbb872

**Comment by prapullac** [comment]
@felixsuarez0727 
1) Naming convention of domains in comparison to other Hubspot  is a different example: it is written as HubDB -Get Published Tables other DB simply have Commands
