### ISSUE TITLE
[Feature]: Global key event listener

### ISSUE THREAD

**Issue by binodgupta010** [appsmithorg/appsmith#11998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I want to trigger an event on enter button  click. 

### Why should this be worked on?

User want to submit request on enter button click.

**Comment by Nikhil-Nandagopal** [comment]
@binodgupta010 if I understand correctly you want to add a global listener for the enter key on the page?

**Comment by wigbertojr** [comment]
+1

**Comment by Nikhil-Nandagopal** [comment]
I believe this is related to #28472 so I'm closing this in favor of that
