### ISSUE TITLE
[Bug]: It is not live for you yet Comming Soon when I connect to git，what is the reason

### ISSUE THREAD

**Issue by 243324195** [appsmithorg/appsmith#11993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is not live for you yet Comming Soon when I connect to git，what is the reason

### Steps To Reproduce

Click git

### Version

1.6.5

**Comment by Nikhil-Nandagopal** [comment]
@243324195 please update your Appsmith instance to 1.6.6
