### ISSUE TITLE
[Bug]-[250]:cURL command - On empty box the user is displayed with inappropriate error message

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#12008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Import is clicked on an empty box of cURL inappropriate error message is displayed to the user stating  "Enter a valid  parameter cURLcode "

Expectation : 
Since the user has not added any cURL code we can let the user know by stating error as "Please add the cURL code"

### Steps To Reproduce

1) Navigate to cURL  
2) click on import option 
and observe the error message 

Note : Ensure the cURL code is empty 

### Version

Release

**Comment by rohan-arthur** [comment]
CREATE_DATASOURCE_CLICK, plugin = REST API: 1700
Assume 25% use curl: 425
Assume 5% attempt empty save: 21

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 21 |
| Effort (months)  | 0.15 |
