### ISSUE TITLE
[Bug]: JS objects are being duplicated during git sync

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#12000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user has reported that when they branch off of their app, the JS objects are duplicated in the resulting app. This causes the app to be in erroneous state, since the collection can also not be deleted because of multiple branched collections referring to the same master collection.

### Steps To Reproduce

https://discord.com/channels/725602949748752515/953747596625707089/953750765258833970

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi @abhvsn are we working on this? This can potentially break apps for users

**Comment by abhvsn** [comment]
Other thread where this issue was getting discussed: https://discord.com/channels/725602949748752515/948548193296195605 
Issue might be bigger and not specifically related to the git, I'll try to triage the root cause as with git branching I'm not able to reproduce this.

**Comment by ereio** [comment]
+1 can confirm this is happening to us on self-hosted
