### ISSUE TITLE
[Task]: GraphQL:  Refactor REST API code to create re-usable components

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#12019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Refactor REST API plugin code on the API server to create re-usable components.

### Why should this be worked on?

To speed up the development of future REST API like code flows.

**Comment by prapullac** [comment]
Waiting for the DP

**Comment by prapullac** [comment]
Verified on the DP
