### ISSUE TITLE
[Bug]: Multi Select options are being picked from the default value instead of the label field

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#12020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using a multi select widget, the options are being displayed based on the default values instead of the labels configured in the option

### Steps To Reproduce

1. Drag a multi-select widget
2. Notice the options selected in the widget are GREEN (value) instead of Green (label)

### Version

Cloud

**Comment by somangshu** [comment]
This was observed while triaging https://github.com/appsmithorg/appsmith/issues/11714

cc @Tooluloope @ashit-rath @dilippitchika I think you guys were able to report this as well?

**Comment by dilippitchika** [comment]
@somangshu we did not discuss this i think, @Tooluloope correct me if am wrong. 
We discussed all these cases, but did not prioritise the order of the cases. 

This is a prioritisation issue, basically we should check the options first and if it's not there in the options then we should show the value.

Can we please discuss this and move ahead @Tooluloope?

**Comment by btsgh** [comment]
Tested on Release - The options selected in the widget are now correct. ( Green (label) , Red (label)
<img width="856" alt="Bug12020" src="https://user-images.githubusercontent.com/101863839/160632381-795e0014-c13d-4a07-9222-6565923e0386.png">
)
