### ISSUE TITLE
[Bug]-[2200]:Import application modal is not center aligned for non appsmith users

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Import application modal is not center aligned for non appsmith users
![image](https://user-images.githubusercontent.com/92293815/159260720-52c005f4-3d11-4a35-9073-9abf00c9a769.png)

### Steps To Reproduce

1. Go to release login with non appsmith users
2. Click on three dots next to organization and click on Import.

### Version

Cloud

**Comment by AnaghHegde** [comment]
@shwetha-ramesh Is this a release blocker?

**Comment by shwetha-ramesh** [comment]
Had tagged it HIGH @AnaghHegde

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 275 |
| Effort (months)  | 0.25 |

**Comment by IAmAnubhavSaini** [comment]
This has been fixed.
