### ISSUE TITLE
[Bug]: Comment box opens up at odd locations in view mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Comment box opens up a odd location and sometimes goes out of view for user

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/294716e1e11347ea81f76ec753e17050-00001.gif)](https://www.loom.com/share/294716e1e11347ea81f76ec753e17050)

### Steps To Reproduce

1. Deploy an app and switch to comment mode
2. Click on the canvas to drop a comment and observe the comment box open up at random locations and even be hidden from viewport sometimes

### Version

Cloud

**Comment by vuiets** [comment]
@ramsaptami this looks like a duplicate of [#11499 | Commenting on canvas is broken](https://github.com/appsmithorg/appsmith/issues/11499).

**Comment by ramsaptami** [comment]
CLosing this in that case, thanks @vuiets
