### ISSUE TITLE
[Bug]: Dropdown option gets misaligned after selection

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Selected dropdown option gets misaligned on the CRUD page

![image](https://user-images.githubusercontent.com/79509062/159251181-97955d69-9102-4be8-8958-9160e249510a.png)

### Steps To Reproduce

1. Go to CRUD page and select a datasource
2. After selecting, observe the alignment of the datasource entry - it's misaligned as seen in the screenshot.

### Version

Cloud

**Comment by ginilpg** [comment]
@ramsaptami Is this done? Can we close this ticket?

**Comment by ramsaptami** [comment]
Seems to be fixed, hence closing it.
