### ISSUE TITLE
[Bug]: Deleting Query from ContextMenu deletes previous query 

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6f9f46ca4f8f4457bb502e55b3240b6a-00001.gif)](https://www.loom.com/share/6f9f46ca4f8f4457bb502e55b3240b6a)

### Steps To Reproduce

1. Create a query on any data source, eg: Postgres used in above example
2. Create query2 on same data source
3. Delete query2 from inside query page - via context menu
4. Observe it deletes the query1 & query2 stays
5. **Expected: Deleting respective query should delete only that & user's other data should remain untouched**

### Version

Prod/Release v1.6.16

**Comment by sumitsum** [comment]
Client seems to be making `DELETE` call with the wrong action id. Needs to be investigated further on the client side. cc: @ajinkyakulkarni

**Comment by ramsaptami** [comment]
Found another issue on the same line for copying of queries #12140
