### ISSUE TITLE
[Bug]: Pagination previous/next is not proper

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#12030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="713" alt="Screenshot 2022-03-21 at 6 00 57 PM" src="https://user-images.githubusercontent.com/83569920/159261491-d00d4d11-82e4-474c-b968-89417a92f0d9.png">

### Steps To Reproduce

Drag and drop a table widget on canvas and observe

### Version

Cloud

**Comment by somangshu** [comment]
Not seeing any specific code changes around this right now, But I see that the change is in SVG fill which is causing this 
![Screenshot 2022-03-21 at 6 25 02 PM](https://user-images.githubusercontent.com/11089579/159265176-442b712a-c2a0-44c2-b143-2f3ad73281d0.png)

Ill find out the relevant change that made this happen

**Comment by yaldram** [comment]
The fix is here in this PR - https://github.com/appsmithorg/appsmith/pull/11973
