### ISSUE TITLE
[Bug]: Generate page doesn't work for S3 and mongo datasource

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Generate page doesn't work for S3 and mongo datasource
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/159266018-4ae1c832-86c3-41d2-8341-5399a201c3a4.png">

### Steps To Reproduce

1. Add the s3 datasource 
2. now click on generate page
3. Select  the Datasource as s3
4. now select the bucket as assert.test.appsmith.com
5. Now click on generate button 
6. The internal server error is displayed instead of generating the page

### Version

release

**Comment by btsgh** [comment]
Tested in Release. Generate page now works for both Amazon S3 data source as well as Mongo DB data source. No errors observed.
