### ISSUE TITLE
[Bug]: On opening Tutorial through open documention in Omnibar, shows page not found.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#12047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In omnibar, Open documentation button for tutorial points to documentation with link: "https://docs.appsmith.com/tutorial-1", which shows page not found.

### Steps To Reproduce

1. Go to Omnibar
2. Go to Documentation
3. Click on Tutorial
4. Click on open documentation 

### Version

Production

**Comment by arunvjn** [comment]
Closing this since it is a duplicate of #11953
