### ISSUE TITLE
[Bug] Table should show the number of records instead of the pages

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1205]
## Description
The table shows the page information twice instead of showing the number of records

<img width="1650" alt="Screenshot 2020-10-14 at 11 46 45 PM" src="https://user-images.githubusercontent.com/3897254/96028891-89c1ab00-0e77-11eb-8a59-a0f2afcc3970.png">

**Comment by shreyamodi1999** [comment]
Hey can you assign this to me?

**Comment by satbir121** [comment]
Sure @shreyamodi1999 Please reach out if you need any help. Also go through our [contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md).

**Comment by satbir121** [comment]
@shreyamodi1999 Any updates?

**Comment by Nikhil-Nandagopal** [comment]
@shreyamodi1999 I don't see a PR for this. I understand something must have come up so I'm unassigning this from you. Feel free to come back to our issues when you have a chance!

**Comment by ng29** [comment]
Hey @Nikhil-Nandagopal  / @satbir121 

Can i pick this up and more info around this will be much appreciated such as file directory and so .. 

Cheers

**Comment by Nikhil-Nandagopal** [comment]
@ng29 go for it!

**Comment by ng29** [comment]
> @ng29 go for it!

PLease assign and share buggy files path 👍

**Comment by Nikhil-Nandagopal** [comment]
@ng29 the TableWidget file should be the one to checkout

**Comment by ng29** [comment]
> @ng29 the TableWidget file should be the one to checkout

hey @Nikhil-Nandagopal , currently i am doing the testing part of issue 949 , setup is in progress under the guidance of @hetunandu  , so will start this tomorrow

**Comment by Nikhil-Nandagopal** [comment]
@ng29  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by vvkpd** [comment]
I would like to work on this card if required

**Comment by Nikhil-Nandagopal** [comment]
@vvkpd go for it!

**Comment by mohanarpit** [comment]
@vvkpd I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by vvkpd** [comment]
Sorry for the delay but i am working on it!!!!!!!

**Comment by mohanarpit** [comment]
@vvkpd Thanks for replying. 

I'm assigned this issue back to you. Would appreciate it if you could open a PR within the next couple of days so that we can close this. Else, we'll be forced to re-assign the issue so that someone else can pick up & resolve this issue.

**Comment by mohanarpit** [comment]
@vvkpd I'm sorry but I'm unassigning you from this issue because I haven't seen a PR open for this. Feel free to contribute to Appsmith whenever you have the time by picking up some other issue from our list.

**Comment by vvkpd** [comment]
I think this can be close. right @mohanarpit ?

**Comment by prapullac** [comment]
Reopening the issue as it is not working as expected

**Comment by vvkpd** [comment]
@prapullac Could please share your insights? What is expected and how is behaving differently? 
Thanks

**Comment by Nikhil-Nandagopal** [comment]
@vvkpd the issue here is that the text showing 1 - 25 items seems confusing to a user
Can we update this to simply show 25 records

**Comment by vvkpd** [comment]
@Nikhil-Nandagopal So, you are saying that changing the message `showing 1 - 25 items` to `show 25 items`
Right?

**Comment by Nikhil-Nandagopal** [comment]
@vvkpd yes but let's say records instead of items

**Comment by vvkpd** [comment]
hey @Nikhil-Nandagopal I have raised a pr please take a look

**Comment by Nikhil-Nandagopal** [comment]
@vvkpd can you remove the show as well. It makes it feel like it's showing that many items. Just a simple
25 records should be fine. Rest looks good and we can merge

**Comment by vvkpd** [comment]
pushed the changes, have a look

**Comment by Nikhil-Nandagopal** [comment]
@vvkpd LGTM! Thank you for your contribution
