### ISSUE TITLE
[Task]: Update react-scripts to 5.0.0

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#12066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by yaldram** [comment]
At this point in time craco does not support react-scripts version 5 (cra-5)
- https://github.com/gsoft-inc/craco/issues/399
- https://github.com/gsoft-inc/craco/issues/378

**Comment by riodeuno** [comment]
@yaldram I was wondering if we can consider what we're using craco for, and see if there are ways around it. Either by removing CRACO or by using a different CRA webpack modification library.

**Comment by yaldram** [comment]
@riodeuno we are using craco for overriding the CRA webpack configuration.

**Comment by riodeuno** [comment]
@yaldram Yes. I was wondering if we can look into which configurations we are overriding, and whether they can now natively be done in CRA5, or we can use an alternative to CRACO for this which supports CRA5.

**Comment by yaldram** [comment]
@riodeuno sure will look for other alternatives.
