### ISSUE TITLE
[Feature]: Add Submenu to entity explorer to create new query/js

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#12060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

# Introduction

- We redesigned the Explorer to enable one-click creation of files. Now users can click on (+) icon next to Query/JS to create any type of file.
- Upon clicking the plus (+) icon, the omnibar asks users to choose a file type. The file type could be an API or JS, or a query on a particular db.
- The experience of creating a new query/js from the omnibar is heavily optimized for keyboard-based usage, but compromises on mouse first interaction.
- We should redesign this experience for mouse first usage as users primarily interact with the explorer with a cursor.
- The omnibar way of adding a query/js should still be available for advanced users, and we should preserve the keyboard shortcuts.

# Problems with current design

- The omnibar is small and centered on the screen. This feels disconnected from the explorer and breaks the user's flow.

# Solution

- Upon clicking on the plus (+) icon next to query/js, we should open a submenu right next to it, that allows users to create an API/JSObject/Query.
- The submenu should list datasource to query similar to the omnibar.
- Users should be simultaneously able to create query/js with the omnibar/shortcuts.

# Design

**Figma Prototype** - https://www.figma.com/proto/UjVDuTFphqSuLDeUhMYJBO/Dev-handoff-Create-new-Query-JS-submenu?node-id=2%3A25&viewport=338%2C48%2C0.26&scaling=min-zoom&starting-point-node-id=2%3A4681
**Figma handoff** - https://www.figma.com/file/UjVDuTFphqSuLDeUhMYJBO/Dev-handoff---Create-new-Query%2FJS-submenu?node-id=2%3A25
<img width="1456" alt="Screenshot 2022-03-22 at 10 54 55 AM" src="https://user-images.githubusercontent.com/65771350/159413685-3d2d7c9f-2c72-4ba8-8c7c-b8a9bc2e70f8.png">

# Interaction Detail -

- User hovers over the plus icon next to Query/JS.
- A submenu pops up. The title is 'Create New'.
- User can select one of the options to create a new API/JSObject/Query a datasource.
- The height of the submenu is limited to show only API & JSObject, plus three recent datasources.

### Why should this be worked on?

- Adding a new Query/JS is a core editor flow that affects every user, and every new appsmith user equally.

**Comment by aakashDesign** [comment]
**Design Update**

After discussions with the design team, we have decided the Submenu should open OnClick, instead of OnHover. This is to ensure consistency with other modules on the explorer.

I've updated the **figma prototype** - https://www.figma.com/proto/UjVDuTFphqSuLDeUhMYJBO/Dev-handoff-Create-new-Query-JS-submenu?node-id=2%3A25&viewport=338%2C48%2C0.38&scaling=min-zoom&starting-point-node-id=2%3A4681

**Updated Interaction Detail -**
- User _clicks_ over the plus icon next to Query/JS.
- A submenu pops up. The title is 'Create New'.
- User can select one of the options to create a new API/JSObject/Query a datasource.
- The height of the submenu is limited to show only API & JSObject, plus three recent datasources.

**Comment by kocharrahul7** [comment]
This hsa been closed, and can be tracked here: 
https://github.com/appsmithorg/appsmith/issues/11015

**Comment by kocharrahul7** [comment]
Accidentally closed
