### ISSUE TITLE
[Bug]: Document viewer widget looks different in Edge browser

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Document viewer widget looks different in Edge browser

![image](https://user-images.githubusercontent.com/92293815/159425517-13cf0e10-5dc3-4ed4-a520-12330744b674.png)

### Steps To Reproduce

1. Open release in Edge
2. Drag and drop document viewer widget

### Version

cloud

**Comment by techbhavin** [comment]
@shwetha-ramesh 
For PDF rendering Document viewer used iframe and Browser-Wise has rendering iframe is different. 

so I don’t think it is an issue.

**Comment by techbhavin** [comment]
@somangshu  can you plz help here .

Here I don’t think it is an issue. we can close this issue.
