### ISSUE TITLE
[Bug]: Inappropriate confirmation message is displayed when user wants to delete the Datasource

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#12075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user tries to delete the data source it is observed that the user is displayed with an inappropriate confirmation message stating to confirm if the user wants to run the datasource

Expectation :
User must be displayed with a confirmation message stating "Are you sure you want to delete the data source 1" 

### Steps To Reproduce

1) Create a new datasource
2) Click on delete option 
and observe the confirmation message

![Screenshot 2022-03-22 at 12 34 40 PM](https://user-images.githubusercontent.com/71753653/159427857-dfe241e3-ff33-42ba-92e6-5cd45a7e75ea.png)

### Version

release

**Comment by rohan-arthur** [comment]
@Irongade current behaviour is different, the error says "Are you sure you want to perform this action"
Was this intended, and is this related to #11761 ?
