### ISSUE TITLE
[Bug]: Switch group widget is crashed when selectedValues is undefined

### ISSUE THREAD

**Issue by wmdev0808** [appsmithorg/appsmith#12078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When `selectedValues` is `undefined`, the app is crashed

### Steps To Reproduce

1. Drop both of switch group widget and checkbox group widget on the canvas.
2. Let the checkbox group widget throw cyclic dependency error by passing a evaluation expression for an option value and clicking on JS toggle in `Options` property.
For example,  BLUE to {{BLUE}}
3. The app is crashed

Reference:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/874971cc3ced4f69925b20606e43c6a3-00001.gif)](https://www.loom.com/share/874971cc3ced4f69925b20606e43c6a3)

### Version

Cloud

**Comment by btsgh** [comment]
Though the app crash does not happen, once the steps as shown in the earlier loom video are followed, however the cyclic dependency error comes up after which the Switch Group fails to function properly. 
The Switch Group widget should not be impacted if changes are made to Checkbox Group widget. Check the behaviour in the video below to understand -

https://www.loom.com/share/b817cc8f5a2f46d790845c50016ad259

**Comment by Rishabh-Rathod** [comment]
Ideally, we should make sure that if users' application goes into a cyclic dependency issue. We still send correct values to `dataTree` and widgets do not crash but instead, stay in the older valid state.

@wmdev0808 Does the widget receives unexpected values in props?

**Comment by somangshu** [comment]
@Rishabh-Rathod not sure about that, this is to do with some characters in the JS mode of switch group, it crashes the App, and post that the widgets do not function.

**Comment by Rishabh-Rathod** [comment]
@ajinkyakulkarni FE-coders will need to do an RCA for this issue. Can we add a RACI metric here?

**Comment by bharath31** [comment]
This is no longer reproducible
