### ISSUE TITLE
[Bug] Property fields are not being saved correctly in datasource/action forms

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#1209]
## Description

Form fields in datasource or action configuration that are built on properties are not being sent to the server correctly.

### Steps to reproduce the behaviour:

The following steps can illustrate the symptom:

1. Create a new MySQL datasource.
1. Set a value for the "Timezone override" field under the section "MySQL Specific Parameters".
1. Hit save, and wait for the save to finish with success.
1. Refresh the page and navigate to edit this datasource to check if the value is still there.
1. The field is blank.

## Analysis

This is concerning fields that are specified like the following:

```
datasourceConfiguration.properties[0].serverTimezone
```

The values for such fields are being sent to the server in the following manner:

```json
"datasourceConfiguration": {
  ...
  "properties": {
    "serverTimezone": "value in the input"
  }
}
```

However, the server is expecting something like the following:

```json
"datasourceConfiguration": {
  ...
  "properties": [
    {
      "key": "serverTimezone",
      "value": "value in the input"
    }
  ]
}
```

## Changes Needed

1. The client should send the data of such fields as separate `key` and `value` fields in an object. This was the case in the past, I couldn't confirm when this changed.
1. The server should not respond with success when such data is sent. The server is getting an object with `key` and `value` as null, in which case it should throw an error and not save.

## Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by prapullac** [comment]
Verified the issue and working as expected
