### ISSUE TITLE
[Bug]: Content gets trimmed on Table widget

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#12130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The hyper link content inside a table cell is truncated.
<img width="749" alt="Screenshot 2022-03-22 at 1 05 27 PM" src="https://user-images.githubusercontent.com/10436935/159430778-8c817744-bdce-4ec9-bfe0-3e1085e0a8c1.png">

### Steps To Reproduce

1. Add a table widget
2. Change one column to be of type URL and look at cell's padding

### Version

Cloud v1.6.15

**Comment by somangshu** [comment]
Dev note: Triage to understand the root cause here. Leave a comment about the same
