### ISSUE TITLE
[Bug]: Evaluation error on a child widget does not clear from debugger when undoing action and only clears after a hard reload

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there's an evaluation error on a child widget of a list widget, then an undo action (Ctrl+Z) does not clear the evaluation error from either the debugger or the widget and only clears when the page is refreshed.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3681bd9b715141fbb0a5c8a253e760ef-00001.gif)](https://www.loom.com/share/3681bd9b715141fbb0a5c8a253e760ef)

### Steps To Reproduce

1. Drop a list widget on canvas and add a button widget to it
2. Bind the button widget to any random string so we see an evaluation error as seen in the video above
3. Now undo using Ctrl+Z or Cmd+Z and observe the user actions revert but evaluation error stays put in both the button widget and the debugger
4. Observe that only a hard reload of page clears this evaluation error
5. Delete this widget and replace with another button widget and observe the new button default this evaluation error as seen in the video

### Version

Cloud

**Comment by ohansFavour** [comment]
The problem here is that the `List Widget`'s template object doesn't get updated when a child widget is removed from it. Hence, errors still get persisted.

cc: @somangshu

**Comment by Tooluloope** [comment]
This seems fixed.

https://user-images.githubusercontent.com/31691737/170879392-21d66f75-f410-4a59-9229-cabc44d093a3.mov

**Comment by Tooluloope** [comment]
@ramsaptami Could you confirm?

**Comment by ramsaptami** [comment]
This has been fixed hence closing it

**Comment by ohansFavour** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/11883
