### ISSUE TITLE
[Bug]: MultiSelect Widget binded with text widget using SelectedOptionLable it shows the selectedOptionValues

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#12143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is observed that when an multiselect widget is binded with text widget using selectedOptionLabels the text widget shows the selected option value instead of label

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/18502f043d7843cf85cd627e8da102d1-00001.gif)](https://www.loom.com/share/18502f043d7843cf85cd627e8da102d1)

### Steps To Reproduce

1. Drag and drop a multi select widget 
2. drag and drop a text widget 
3. Bind multi-select widget with text widget as {{MultiSelect1.SelectedOptionLabel}} and observe that the text widget shows the value instead of label

### Version

Cloud

**Comment by dilippitchika** [comment]
@Tooluloope i believe #12554 and this are related, please confirm so that we can track in one place only

**Comment by Tooluloope** [comment]
close in favour of https://github.com/appsmithorg/appsmith/issues/12554
