### ISSUE TITLE
[Task]: Remove or redesign dual errors on merge conflict case

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#12154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Continuing from #11750 

![](https://user-images.githubusercontent.com/217911/156349385-d71dcc89-8201-4472-b401-da9dcbded24f.jpeg)

**Comment by vuiets** [comment]
Hey just double checking to confirm that we are removing the info icon and ensuring that the font weight is from the Design System for the error message under the select dropdown over here.

**Comment by IAmAnubhavSaini** [comment]
This has been fixed. Checked in prod.

<img width="553" alt="Screenshot 2022-05-18 at 1 23 47 PM" src="https://user-images.githubusercontent.com/1573771/168987264-4a8bbe28-85e6-49c8-bf6f-3b124e8ef12c.png">
