### ISSUE TITLE
[Feature] HubSpot Settings API Saas Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#12151]
HubSpot Settings API Saas Integration

### Description: 

This API can be used to manage the users on an account and manage the roles of those users.

------------------------
### Documentation:

https://developers.hubspot.com/docs/api/settings/user-provisioning

------------------------
### TO-DO

------------------------
### API Actions Progress

| Action                           | EngSpec Doc | SaaS Manager App | SaaS App Run | Test App Run |QA  |
| ---                              | ---         | ---              | ---    | --- ||--- |
| Retrieve List Users | Yes          | Yes               | Yes     | Yes  |   No  |
| Add User                         | Yes          | Yes               | Yes     | Yes  |   No  |
| Retrieve User                   | Yes          | Yes               | Yes     | Yes  |No  |
| Modify User                    | Yes          | Yes               | Yes     | Yes  |No  |
| Removes User                     | Yes          | Yes               | Yes     | Yes  |No  |
| Retrieve Roles Account          | Yes          | Yes               | Yes     | Yes  |No  |
| See Details Account's Teams      | Yes          | Yes               | Yes     | Yes  |No  |

------------------------

**Comment by felixsuarez0727** [comment]
This is almost done, but we will continue next sprint.

**Comment by btsgh** [comment]
Testcases are available here:

1. [Basic Test](https://github.com/appsmithorg/TestSmith/issues/1783)
2. [Add User](https://github.com/appsmithorg/TestSmith/issues/1784)
3. [Retrieve User](https://github.com/appsmithorg/TestSmith/issues/1807)
4. [Modify User](https://github.com/appsmithorg/TestSmith/issues/1799)
5. [Remove User](https://github.com/appsmithorg/TestSmith/issues/1804)
6. [Retrieve Role Account](https://github.com/appsmithorg/TestSmith/issues/1805)
7. [See Details Accounts Teams](https://github.com/appsmithorg/TestSmith/issues/1806)

**Comment by felixsuarez0727** [comment]
HubSpot Settings Observations

 | #|Question/Observation | Related Issue | Resolved |
|---| ---                                | ---         | ---              |
|1| Open Square bracket present in the Secondary Team Id by default.  | [##13038](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13038) | No |
|2| Add User Scenario7 fails  |  -   |No|
|3|Retrieve User Issues / queries | - | No |
|4|Even if the User ID field is mandatory, if we leave it blank, the query runs without an error and gives the output |-| No|
|5| Retrieve List of Users. What is the use of After here | - | Yes |
|6| What is the order in which the 3 users are picked? |- | Yes|
|7| Incorrect Error. Also, one cannot specify size. |- | No|
|8| The square bracket is present in secondary Team Id's by default. Not required|- | No|
|9| An error comes up [B@650f4eb - What does this mean? |- | No|
|10| Error is incorrect, needs to be more specific.  |- | No|
|11| What will ID Property take? |- | No|
|12| An error pops up on trying to remove user.  |- | Yes|
|13| What is this supposed to retrieve? Roles of all users? Or Particular user?|- | Yes|
|14| Response comes for one userid. How is this valid? |- | Yes|
|15| What is this supposed to retrieve? Details Accounts Teams of what? Response comes..how to verify if this is valid? |- | Yes|
|16| Incorrect Names of Commands |- | No|




Updates about observations

1. There is a related issue, we are going to work on this
2. We have to investigate the cause of the problem
3. We have to change name Retrieves User to Retrieve user, 
ID property is the name of a property with unique user values.For example USER_ID or Email
4. We need to do more research on the problem
5. Is the paging cursor token to get the next set of results. We will clarify this when we add the subtext
6. According to the test that was done, the users shown are the first 3 that were created
7. We need to do more research on the problem
8. We need to understand the problem
9. We need to do more research on the problem
10. The same as problem 9
11. Is the name of a property with unique user values.
12. Resolved
13. Retrieve the roles on an account, not of a particular user
14. Retrieve the roles on an account, not of a particular user
15. You can see all the teams of the account in general. To test it, you should create several teams in HubSpot and then run the action, you will see a list with the teams that the account has.
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/20394915-ce10-4872-b151-feca64b616e9)
16. The change is pending
