### ISSUE TITLE
[Feature]-[1000]:Improvements to column visibility panel in table widget

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#12157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a data source has a lots of properties and we need to show only a few of them - a lot of work needs to be done in configuring table widget. For example, this API https://api.github.com/search/repositories?q=language:java returns a response where each item has lots of attributes. If I need to show a few attributes e.g. name, star count, fork count - I've to click on the hide button of every other property which will take a lot of time. Another issue is - if my required properties are scattered, I've to scroll through the long list of column attributes to access them. I can drag them on top but that's also complex and time consuming as the list is very long. 

A few small options can help here:

- Add hide all and show all option so that I can quickly hide all and show the few required ones manually
- Show the visible properties first and hidden ones after them. If I've 5 attributes visible and 40 are hidden, the visible 5 attributes should automatically come up first and rest 40 should be shown after them. Alternatively, we can divide the properties into two groups - visible and hidden
- Hidden items are displayed on the table in edit mode in grey color which makes the table unnecessarily large. As the hidden items will be displayed when I make them visible again, there is no reason to keep them displayed in the table.
- There is no way to delete an attribute. A lot of attributes can be unnecessary and there is no chance I'll show them but still I've to maintain the binding because there is no way to delete. If deleting an attribute creates a filter method automatically, user will be able to know that they can write functions to do the trick.
- A search option can be added to quickly find a column.

<img width="1155" alt="Screenshot 2022-03-23 at 12 42 20 PM" src="https://user-images.githubusercontent.com/83352306/159641372-a79189db-d217-46b4-b11b-659148cfdbd2.png">

### Why should this be worked on?

It'll make the Table Widget more user friendly and easy to use. Table widgets are the most common thing developers.

**Comment by dilippitchika** [comment]
Assuming 80% of our table devs face this
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1500 |
| Effort (months)  | 2 |

**Comment by spark-c** [comment]
Hello! I just came across this additional little UI bug related to Table Column visibility.

When a column is hidden, swapping its position in the list with a visible column __does not correctly update the hidden/visible icons__, and causes the icons to be out of sync with the columns' actual visibility state. Refreshing the browser page gets everything back in sync.

Here is a visual demo:

https://user-images.githubusercontent.com/51402465/163227486-fb8c900b-eca1-4a6d-9246-189c66de96d0.mp4

### Steps to reproduce:
1. Create a table, connected to some datasource with several columns.
2. In the table's properties, toggle the visibility of one column using the Eye icon.
3. Drag that column to swap its place with one of the visible columns.
4. The icons are now the opposite of what they should be; the visible column will show a "hidden" icon, and vice-versa. Clicking either of the icons will toggle the visibility of the correct column and its icon, so they stay out of sync with each other.

The icons can be reset to their correct state by either refreshing the page, or by dragging the columns again in the reverse of the way that broke them... if that makes sense. Using the bug to fix the bug. :)

**Comment by Nikhil-Nandagopal** [comment]
@spark-c thank you for the detailed steps to reproduce it!

**Comment by dilippitchika** [comment]
@spark-c thanks, we are tracking this in #11384 and will push this fix soon

**Comment by momcilo-appsmith** [comment]
@dilippitchika should this issue be closed?
