### ISSUE TITLE
[Bug]: The google sheet authentication is failing in the import flow

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The google auth is failing in the import flow

### Steps To Reproduce

1. Import the application which has the google auth
2. now in the reconnect Datasource modal
3. Authorize the google auth
4. It says authorize is successful
5. Now once the user navigates to the application 
6. the google auth authorization is failed and the user need to reauthenticate it 

### Version

release

**Comment by RakshaKShetty** [comment]
The application is breaking when the user tries to authenticate the google sheet
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/160342333-2572b342-e756-4b9f-8276-24a931e96b09.png">

**Comment by RakshaKShetty** [comment]
Added the comment in the PR

**Comment by AnaghHegde** [comment]
@RakshaKShetty Can we close this issue? I believe this is fixed in the latest push @haojin111 has made.
