### ISSUE TITLE
[Bug]: Inconsistent label in connections tab

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#12168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The "Connect Widget" and "Add new widget" should have the word "widget" in same format - either both of them should be in lowercase or uppercase.
![Uploading Screenshot 2022-03-23 at 4.37.57 PM.png…]()

### Steps To Reproduce

1. Add a new API
2. Click on the right panel
3. Click on the connections tab

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@nayan-rafiq the image did not get uploaded please update it. Also for super tiny text fixes can we just fix them instead of creating an issue around fixing them?
