### ISSUE TITLE
[Bug]-[1000]:navigateTo params 0 doesn't work.

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#12177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`navigateTo("Page2", {id: 0})` doesn't add id to the URL. (Any variable with value 0 doesn't get passed)

Workaround: call toString() in the variable
`navigateTo("Page2", {id: "0"})`

### Steps To Reproduce

1. Call `navigateTo("Page2", {id: 0})` on click.
2. Click the button and notice URL is not appended with id=0.

This is the same when using any variables, `navigateTo("Page2", {id: myVariable})`.

### Version

Cloud - 1.6.16

**Comment by dslotcavage** [comment]
Would like to add that I have this issue as well.  This makes the navigateTo function much less useful, as I can't pass Table.selectedRowIndex (or really anything with an index).  I'm going to use storeValue as a less-optimal workaround unless there's a better option available.

**Comment by bharath31** [comment]
Assuming 10% of users who update widget properties with navigateTo() face this issue

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 250 |
| Effort (months)  | 0.5 |
