### ISSUE TITLE
[Feature]-[762]:bring back error message `async functions in sync fields`

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#12179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we use and async function (e.g. Query.run()) in a non-async field (e.g. `table.tableData`)

We used to throw an explicit error stating `Cannot use async functions in sync field`.
This was removed as having this check was hindering performance.

Right now, `TypeError: Api1.run is not a function` is shown which is misleading for the users.

### Why should this be worked on?

We need to address this, so the users are not mislead.

**Comment by rohan-arthur** [comment]
number of instances in jan '21: 170
extrapolating 6 months, reach: 1020

**Comment by bharath31** [comment]
@satbir121 we need to prioritize this. came up on a [recent hacktoberfest app feedback ](https://www.notion.so/App-feedback-08cc56807ed34c7fabfa1a11aa091cca?d=f639867726dc4635a3744457807760cf#1159f3129ff3450dac038d8359493433)

**Comment by satbir121** [comment]
Discussing this with the team. We can try to show a better message.
