### ISSUE TITLE
[Bug]-[1750]:No information available is shown under API datasource

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#12171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on datasource from the left panel, a message appears saying "No information available". It's no clear what information is missing or whether it's a problem or not. It should either be removed or we should show something e.g. base url of the API here.
<img width="354" alt="Screenshot 2022-03-23 at 5 09 09 PM" src="https://user-images.githubusercontent.com/83352306/159686859-078f0759-aaee-4edd-8f80-3762d1339812.png">

### Steps To Reproduce

1. Add a new API
2. Create a new datasource for the API
3. Click on the name of the datasource from the left panel

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3500 |
| Effort (months)  | 1 |

**Comment by Nikhil-Nandagopal** [comment]
We should just change this to say `Schema not available`
