### ISSUE TITLE
[Enhancement]: Search/Filter ability in Active DataSources with DataSources name

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. As the number of data sources increase, finding it difficult to track it down in Active Data sources list

### Steps To Reproduce

1. Create multiple data sources
2. Navigate to Active data sources section
3. The newly created datasource appears at last - user needs to scroll a bit before finding it
4. **Expected: Should have ability at top of page to search/filter for the data source with name**
5. **Expected: New data source should also appear at top instead of bottom for easy navigation**

### Version

Prod/Release v1.6.17

**Comment by Nikhil-Nandagopal** [comment]
@Aishwarya-U-R I know this is a problem for our org because we do a lot of testing but this is generally not a problem for users since they don't have more than 3 - 4 datasources so I'm going to close this :)
