### ISSUE TITLE
[Task] How to upload Images to S3

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1218]
## Description
We need a how-to guide on uploading images from an appsmith app to Amazon S3. The guide should cover
- Using the file picker
- Generating a signed URL
- Uploading the file
The guide should also contain gifs / images wherever relevant

**Comment by dowenrei** [comment]
Hi Nick, I would gladly work on this!

**Comment by Nikhil-Nandagopal** [comment]
@dowenrei go for it!
