### ISSUE TITLE
[Feature]: Track active branch at user level for git connected applications

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#12198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, each user who has access to edit the git-connected application lands on the default branch, and then they have to checkout to their working branch. 

### Why should this be worked on?

It becomes cumbersome every time you have to checkout to the actual branch, considering the git APIs are slow.

**Comment by infinitetrooper** [comment]
Closed with https://github.com/appsmithorg/appsmith/issues/30321
