### ISSUE TITLE
[Epic]: Support Air-Gapped Appsmith Instances

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#12200]
When a customer requires absolute data security due to the nature of the industry or to comply with legal requirements, they would like to run Appsmith on an air-gapped server, i.e. a server that is physically isolated from unsecured networks such as public internet.

To solve this, We will provide Appsmith Air-Gapped Edition, a subset of appsmith-ee that works gracefully without public internet access.

Product Note - [Notion](https://www.notion.so/appsmith/Air-Gapping-Appsmith-98805d25188f4a1281b53104c5b6a72c)
<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5r3rg)

**Comment by Moemad-711** [comment]
Some Enterprises are in need of an version that doesn't connect to the internet or the ability deploy the app developed by AppSmith to environments not connected to the internet.

**Comment by vuiets** [comment]
Hey @Moemad-711 thanks for dropping your use case here :)

Could you please help me understand this better?
> ... ability deploy the app developed by AppSmith to environments not connected to the internet

**Comment by Moemad-711** [comment]
This is for enterprise that host internal tools on On-premise servers that can't be connected to the internet due to security limitations

**Comment by vuiets** [comment]
Sorry, I missed that! Thanks for clarifying :)

**Comment by infinitetrooper** [comment]
This is now available in v1.9.18, please reach out to us through this [page](https://www.appsmith.com/enterprise).
