### ISSUE TITLE
[Bug] Deleting an application shows errors although the deletion happens

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#1220]
## Description

When deleting an application, we see a toast saying "Deleting application...", but then there's two more toasts saying application by that ID doesn't exist. It looks like we are doing a `PUT` request on that application after the deletion is successful, which fails.

### Steps to reproduce the behaviour:

1. Create a new application in an organization.
2. Delete it and observe.

![Screenshot 2020-10-15 at 15 55 41](https://user-images.githubusercontent.com/120119/96111859-693d3380-0eff-11eb-80fc-5ff891138c46.png)

![Screenshot 2020-10-15 at 15 56 44](https://user-images.githubusercontent.com/120119/96111868-6c382400-0eff-11eb-9aa8-4ca16ae16aa3.png)

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser Firefox

**Comment by jyash97** [comment]
Looks like this is a duplicate for https://github.com/appsmithorg/appsmith/issues/961

**Comment by sharat87** [comment]
Whoop, you're right. Closing as duplicate then. Thanks @jyash97!
