### ISSUE TITLE
[Bug] Creating an application with the name of a just deleted application fails

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#1221]
## Description

When creating an application with the name of an application that was *just* deleted, it fails with an error `An application with this name already exists`. If we refresh the page, the error doesn't happen and we can create the application with that name again.

### Steps to reproduce the behaviour:

1. Create a new application called `one`.
1. Delete the application `one`.
1. Immediately, without refreshing the page, create an application in the same organization called `one`.
1. It will fail.
1. Refresh the page and try doing the same thing.
1. It will succeed.

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser Firefox

**Comment by hetunandu** [comment]
Earlier issue was closed recently #796

**Comment by sharat87** [comment]
I think that issue is different. It's about errors showing up when deleting an application. This one's about not being able to create an application with the name of a deleted one.

**Comment by mohanarpit** [comment]
@sharat87 Is this a duplicate of #827 ?

**Comment by sharat87** [comment]
Yeah looks like. Sorry folks, I should definitely be looking before raising issues. Will keep in mind going forward. Closing as duplicate. Thanks Arpit.

**Comment by mohanarpit** [comment]
Also unable to reproduce this issue. It seems to have been fixed. Please re-open it if you feel differently.

**Comment by sharat87** [comment]
I noticed it on prod, but looks like it's already fixed on staging.
