### ISSUE TITLE
[Bug]-[3500]:Pressing Esc key when autocomplete is open causes control to exit the editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When writing code on the JS editor and autocomplete opens up then pressing the Esc key causes control to exit the editor box and user has to click inside the box again to continue coding.

This behaviour is observed on JS fields of the property pane as well but using the Esc key there comprises a behaviour expected from a form field style of layout - the kind we have on our property pane.

### Steps To Reproduce

1. Go to the editor, type in anything like `app`
2. When the autocomplete opens up, pressing esc key to close the autocomplete causes control to exit the editor entirely.

### Version

Cloud

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1750 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
not reproducible anymore
