### ISSUE TITLE
[Bug]: Icon color not present for Button group widget

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Icon color not present for Button group widget. Where as Menu item inside button group has icon color selection available. 

![image](https://user-images.githubusercontent.com/92293815/159905088-5cb06a12-3134-434d-b7d8-48cab88af8c2.png)

### Steps To Reproduce

1. Drag and drop Button Group Widget
2. Look for Icon color in button group
3. Look for icon color in menu items.

### Version

Cloud

**Comment by somangshu** [comment]
Not an issue anymore, This is rectified after theming
