### ISSUE TITLE
[Bug]: Able to search Table based on a hidden column value in View/Deploy mode

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/159915667-49d9e0ba-9b3f-4482-ab79-ddcca17ebe00.mov

### Steps To Reproduce

1. Use table widget, map some data
2. Make a column hidden
3. Try to search for the hidden column value in Edit mode - results are returned
4. Deploy the app & search for the same hidden column value in Deploy mode - results are returned
5. **Expected: When column is hidden from user, allowing to view results based on hidden column value can confuse user & should not be allowed**

### Version

Cloud/Release v1.6.16

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5bd3g)

**Comment by Nikhil-Nandagopal** [comment]
It's expected
