### ISSUE TITLE
Update missing fields for Airtable integration on SaaS Manager App

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#12220]
The Airtable integration seems to be missing the data for `displayName`, `description` and some other values on some Actions.

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/0eca924b-d01b-4311-bf7d-10ef0fa3efbb)

(Make sure that we are using `displayName` as the display name for actions. Currently, some string manipulation make the display name look weird `Delete A Record` instead of `Delete a record`)

Tasks:

- Update those values.
- Add an EngSpec for Airtable to use as reference.

**Comment by felixsuarez0727** [comment]
**Save Button is Disabled in Airtable Integration**

When I try to edit an action, I can't save it (button is disabled) because integration status is approved, I'll ask how to proceed to update the displayName.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/8afa1894-fda1-4f8c-ad5a-ce6a5e860871)

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/b4a524bb-4118-435c-a447-5edc6d0c6f2f)

**Comment by felixsuarez0727** [comment]
Already updated and tested on SaaS App under (Airtable 1.2). Need to figure out how to proceed with this one (how to update from one to another on prod).

**Comment by felixsuarez0727** [comment]
Add API name and description to all actions
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/7cc474f8-79a5-4799-9821-24b09d43fdbd)

Updated labels and tooltips in different dynamic variables

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/1232d174-3f53-424c-aabe-615f4ebfbec4)

Note: 
We are investigating why the action name is not updated based on the displayName.

**Comment by felixsuarez0727** [comment]
It seems that when the action is saved in the getSaveRequest function all data is updated but the displayName only querie the existing table name. 

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/339e52d6-5aef-4eb1-9019-8ad65624a962)

Possible Solution

Instead of Table1.selectedRow.name use `api_name.text.toUpperCase().replaceAll(" ", "_")`

**Comment by felixsuarez0727** [comment]
Need to test possible solution described above.

**Comment by felixsuarez0727** [comment]
Update about this issue

- The placeholders are not in the oficial documentation, so for now no variable has a placeholder.
- When changing the displayName of an action the name is not updated, we are working on this issue. 
- The integration is already installed in the organization **SaaS Integrations | Testing**, and the different tests have been performed, all actions are working.

**Comment by felixsuarez0727** [comment]
**Updates:** 

- The observations stated on this issue have been resolved.

- Another issue will be created to further improve the helper texts of the Airtable integration (subtitle, tooltip, placeholder) [#14611](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/14611)

**Comment by AmanAgarwal041** [comment]
This issue is fixed temporarily on branch `fix/12220-missing-fields`

**Comment by yatinappsmith** [comment]
![image](https://user-images.githubusercontent.com/84702014/176357414-ffdff095-6052-4bf5-932a-956f4f3bbd86.png)
Bug verification failed

**Comment by AmanAgarwal041** [comment]
Code has been merged to master branch.
