### ISSUE TITLE
[Bug]: Discrepancy in org URLs and the org names

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2022-03-24 at 8 30 42 PM](https://user-images.githubusercontent.com/13262095/159946382-be25da23-b2d0-49e6-97fe-bae8238897b4.png)

### Steps To Reproduce

1. Click on any one of the orgs listed on the left bar & observe the URL

### Version

Cloud

**Comment by Parthvi12** [comment]
This has been verified on release.
