### ISSUE TITLE
[Bug]: The Datasource credentials retains in appsmith sample apps when the user imports the app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Datasource credentials retains in the appsmith sample apps when the user imports the app
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/160079776-ec9308af-2338-44f6-abe6-6b37be02acfe.png">

### Steps To Reproduce

1. Got to doc.appsmith.com
2. export the sample app
3. Now in release instance Try to import the Sample app 
4. The Reconnect datasource modal is not displayed

### Version

release

**Comment by AnaghHegde** [comment]
@RakshaKShetty Its not an issue. To support backward compatibility we support the old files where the credentials are already present. In such cases we do not show the reconnect datasource modal.

**Comment by abhvsn** [comment]
@RakshaKShetty are we seeing this on release? Asking this because `git-import` is still not present in the prod so sample apps are getting exported with the datasource configuration.

**Comment by abhvsn** [comment]
Closing this as the exported file was from prod instance where this feature isn't live yet
