### ISSUE TITLE
[Bug]: Async tag of a particular function keeps turning off when app is loaded and only recognizes it as async after an edit

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A JS function keeps loosing it's async tag when app is loaded and on editing the object, the async tag reappears. 

### Steps To Reproduce

1. Go to JS object at [this](https://release.app.appsmith.com/applications/623d6239e0a3cd4540af5979/pages/623d6239e0a3cd4540af597f/edit/jsObjects/623d6239e0a3cd4540af59ca) location
2. Observe the state of the function - if in async - clear cache and reload the app
3. Observe the async tag no longer present on the function
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e7fc47ecce8449d59dd9c8f1fcfec972-00001.gif)](https://www.loom.com/share/e7fc47ecce8449d59dd9c8f1fcfec972)

4. If the function does not have an async tag, edit to reparse the function and observe the async tag reappear
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/587722d8bfad4b2ab6f6cd3a99956ce0-00001.gif)](https://www.loom.com/share/587722d8bfad4b2ab6f6cd3a99956ce0)

### Version

Cloud

**Comment by eco-monk** [comment]
[Sample app](
https://drive.google.com/file/d/18m5N_B3heLxGXlZlBj6HDSQydB_M38rZ/view?usp=sharing) to reproduce
Happens only when a JsObject refers another JSObject
![image](https://user-images.githubusercontent.com/66776129/161952748-978f8919-903e-4b3d-a035-e316dab74c23.png)
