### ISSUE TITLE
[Docs]: Git Import

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#12244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

We have introduced git import feature and is currently in release under feature flag. We need to have a documentation for the same

**Comment by jnikhila** [comment]
@AnaghHegde - Docs are published and available on [live](https://docs.appsmith.com/core-concepts/git-sync). Please verify.

**Comment by AnaghHegde** [comment]
Looks good to me
