### ISSUE TITLE
[Bug]: Promises is not working on prod and works partially on release

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Promises onSuccess and onError calls produces different behaviour each time code is run

### Steps To Reproduce

1. Go to app at [link ](https://release.app.appsmith.com/earworm-issue-12247/music-app-624183a614d46d3d101807ee/edit)
2.  Authorize the application by clicking on the Spotify logo on `Auth page`
3. Confirm all confirmation modals that come up during page load after navigating to the `Music app` page
4. Go to JS object `pageLoadActions.authorizeSpotifyUsage` and `SpotifyAuthorization.authTPP` and observe the flow and behaviour of the code each time the application is run.
 

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami why is this not critical if it breaks existing apps?

**Comment by ramsaptami** [comment]
It's an edge case while using `navigateTo()` and then `storeValue()` to save returned query params from URL. Code flow also seems to be breaking also because of another regressed issue #12243 
CC: @hetunandu @ApekshaBhosale

**Comment by ramsaptami** [comment]
Bumping up priority since behaviour of the code and hence the application is inconsistent on each run

**Comment by ramsaptami** [comment]
QA verification blocked due to #12643

**Comment by ramsaptami** [comment]
Reopening this since API response using promise is returned as undefined on [this](https://release.app.appsmith.com/app/earworm/av-page-61ea4a44361846772cfb1180/edit/jsObjects/621dfa612b75295c1c165ed6) app
