### ISSUE TITLE
[Bug]: The save button is missing for authenticated API in import modal

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The save button is missing for authenticated API in import modal
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/160083088-ce9e93fe-f294-4882-a1a2-69c8b34b3c38.png">

### Steps To Reproduce

1. Import an application that is connected to authenticated API
2. Now Add all the details required for the data source authentication
3. The save button is not displayed in the modal

### Version

release

**Comment by yatinappsmith** [comment]
Raising severity as this bug prevents user from importing authenticated apis

**Comment by haojin111** [comment]
now merging resolution for this bug

**Comment by RakshaKShetty** [comment]
Fixed <img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/161488322-114a92be-ab41-41f2-823e-0270e45db905.png">
