### ISSUE TITLE
[Feature] - Create functionality to create UI canvas and templates to emulate mobile devices

### ISSUE THREAD

**Issue by SantoshSrinivas79** [appsmithorg/appsmith#1225]
## Summary

Allow users to create quick mobile friendly apps to leverage the power of AppSmith to create interaces and custom apps to already existing and complex business applications (including legacy ones).

## Motivation

As a user, I find AppSmith to lie between low-code and no-code which is great in itself. The various quick mobile app development products in the market are very restrictive in many ways but have extremely utility from a functional use-case point of view.

AppSmith is very well positioned to excel where a little more control is required and users are ok to read up blogs etc for few hours. I'll write a few blog posts too :-)

My favorite use-case is to put together quick apps that sit on a database that is already being served by a more complicated application. Getting something neat and secure suffices my need. E.g. Think about getting a contact list, appointment calendar, communication history etc. at the fingertips of field staff. Very useful application is a mobile interface to work of a legacy  backend ERP database.

So, even if AppSmith targets the most used sizes (2 android and 2 ios, one each for tablet n phone) and **doesn't allow** any responsiveness beyond them (due to resource limitations), it may well be enough for most users! Freedom to allow basic styling (basic colors, images etc) in the hands of makers would be enough to be extremely useful.

## Additional Context

Create UI interface canvases similar to [Glideapps](https://www.glideapps.com/) and [Adalo](https://www.adalo.com/).

**Comment by Nikhil-Nandagopal** [comment]
@SantoshSrinivas79 this is now possible on appsmith!
https://docs.appsmith.com/core-concepts/dynamic-ui/application-layout
Do let us know if you'd like any further enhancements

**Comment by SantoshSrinivas79** [comment]
This is wonderful @Nikhil-Nandagopal and very useful. Thank you!

Just wondering is there any possibility to add some CSS styling. Basically, assign an `id` or a `class` and the components get the styles from a global `CSS`?

Here is a way that Bubble does it https://l.mypad.in/bbl_css_round

**Comment by Nikhil-Nandagopal** [comment]
@SantoshSrinivas79 We're working on this here #3183
