### ISSUE TITLE
[Bug]: Extracting a text input value does not return the value in entirety always. 

### ISSUE THREAD

**Issue by nishantag9** [appsmithorg/appsmith#12258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After a text input has received some user input, and we try to extract the value from the text input, sometimes the entire value is not returned. Example user input -> 90 | returned value on read -> 9. 0 is missing when extracting the value from the text input. This mostly was happening when the application was having heavy data & load.

### Steps To Reproduce

1. Might have to create some load on application

2. Add text input

3. Add input text

4. Try to extract the text, at some cases user load entire value is not returned 

### Version

Self Hosted - v1.6.16

**Comment by Nikhil-Nandagopal** [comment]
@nishantag9 can you please share a sample app that does this or a video?
