### ISSUE TITLE
[Bug]-[280]:Any random database name tests OK for MongoDB database

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#12260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try create a MongoDB datasource with Use Mongo Connection String URI set to No by providing host address name and authentication details, even if I provide a random database name in the Authentication section and click on Test icon, the test passes with a success message.
It should give an error to the effect of Invalid Database Name. 

### Steps To Reproduce

1. Click on Add a New Datasource under Datasources
2. Select MongoDB Database
3. Set the parameters as below:
- Use Mongo Connection String URI - No
- Connection Mode - Read/Write
- Connection Type - Replica Set
- Host Address - <appropriate host address>
- Port - leave blank
- Default Database Name - leave blank
- Database Name - xyz (give any random db name)
- Authentication Type - SCRAM-SHA1
- Username.- give the appropriate user name for a valid db
- Password - give the appropriate password a valid db

Attached the link to the loom video showing the issue -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b3d532ab8ab84e22b24bf304965b95ef-00001.gif)](https://www.loom.com/share/b3d532ab8ab84e22b24bf304965b95ef)

### Version

Release

**Comment by rohan-arthur** [comment]
number of users of mongo - 500

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 700 |
| Effort (months)  | 0.25 |

**Comment by PiyushPushkar02** [comment]
DP link: https://ce-21599.dp.appsmith.com

**Comment by dixerus** [comment]
This might have been one of those cases when it is not a bug, but a feature. Appsmith was automatically creating a database, so one doesn't need to connect to the cluster/instance to create a db through other means. This has a convenience for not going out of Appsmith and decreases usage complexity. This can lead to many random unused databases on the cluster, but for small internal apps this is acceptable and the benefits outweigh the drawbacks.
