### ISSUE TITLE
[Feature]: Conditionally show/hide elements depending on layout size

### ISSUE THREAD

**Issue by krusli** [appsmithorg/appsmith#12272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In AppSmith there is currently no way to hide elements on specific layout/viewport sizes.

### Why should this be worked on?

- Enables different layouts on mobile & desktop (related: #4630)  
Some of the use cases this would be used for would already be handled by #4630 but there may be specific scenarios where we might need to differentiate features/actions based on the client (e.g. disable Camera widget only on Desktop)
- How this is done in Bootstrap, for example: https://getbootstrap.com/docs/4.0/utilities/display/

One (simplistic) way to do this, is to expose viewport type and sizes within the `appsmith` global JS object. It then can be used within the **Visible** property of the widget  

e.g. `{{appsmith.layout == 'desktop' ? true : false}}` in **Visible** would work.

![image](https://user-images.githubusercontent.com/14309096/160332439-6296aa33-142f-40b1-aa09-29bffe9fcb1a.png)  
**Visible** property of a widget

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5j5e4)

**Comment by Nikhil-Nandagopal** [comment]
@krusli thank you for the information!

**Comment by abhvsn** [comment]
I recently came across a tool called flutterflow which gives this option to set widget visibility based on screen layout and surprisingly it was really helpful 😀

**Comment by gilad009** [comment]
Please prioritize it since it's currently (almost) impossible to make a decent mobile app

**Comment by Nikhil-Nandagopal** [comment]
@gilad009 we're currently working on this. If you are open to having a conversation that could help us build this better, we have a beta program that you can register for here https://app.appsmith.com/app/betasmith/registration-652933ef23a9db3488a04d25?id=8

**Comment by rxunique** [comment]
+1

**Comment by KelvinOm** [comment]
We will solve this by creating building blocks with pre-configured behavior
