### ISSUE TITLE
[Bug]: The error CTA should be added when new SSH key is generated and not added in git

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The error CTA should be added when new SSH key is generated and not added in git

### Steps To Reproduce

1. Go to App which is connected to git 
2. Now Under git connect tab click on Meat ball icon 
3. Generate a new SSH Key 
4. Now do a change in the app before coping the new ssh key in the git repo 
5. try to commit and push 
6. The commit and push button is disabled but the error cta is not displayed

### Version

release

**Comment by IAmAnubhavSaini** [comment]
@RakshaKShetty I think you mean to say error notification message instead of `error CTA`. `CTA` means Call To Action, which is a fancy way of saying most important button the page.

**Comment by IAmAnubhavSaini** [comment]
Need to handle this response from backend.

```
{
    "responseMeta": {
        "status": 400,
        "success": false,
        "error": {
            "code": 4044,
            "message": "git status failed. \nDetails: git@site.org:repo/user.git: Auth fail",
            "errorType": "GIT_ACTION_EXECUTION_ERROR"
        }
    }
}
```

**Comment by IAmAnubhavSaini** [comment]
I came up with "Please make sure that regenerated SSH key is added and has write access to repo."  

This error comes up when the ssh key is regenerated, and not added to the remote.

**Comment by IAmAnubhavSaini** [comment]
There is another, related issue, which is when user deletes remote repo after connection and first commit.

```
{
    "responseMeta": {
        "status": 400,
        "success": false,
        "error": {
            "code": 4044,
            "message": "git status failed. \nDetails: Invalid remote: origin",
            "errorType": "GIT_ACTION_EXECUTION_ERROR"
        }
    }
}
```

For this I am proposing "Remote repo doesn't exist or is unreachable".

**Comment by abhvsn** [comment]
> I came up with "Please make sure that regenerated SSH key is added and has write access to repo."
> 
> This error comes up when the ssh key is regenerated, and not added to the remote.

I think can reuse the existing error message for this:
`SSH Key is not configured properly. Did you forget to add SSH key to remote? Can you please try again by reconfiguring the SSH key with write access`

> Remote repo doesn't exist or is unreachable"
Looks good 

Thanks @IAmAnubhavSaini I'll improve the error messages on server side, but we should make a provision to display these errors on UI. Because even today server is sending the errors which are not getting displayed by the client for status and list branch APIs which run on page load and in other places as well like on deploy tab etc.

**Comment by vuiets** [comment]
@abhvsn over here what @IAmAnubhavSaini is suggesting is concise, clean and communicates the error message. So let's go with that in all the relevant places?

So here are my suggestions for the two scenarios being discussed here
> Please make sure that regenerated SSH key has write access to the repo and is added on your git hosting provider.

Good with 👇 as well
> Remote repo doesn't exist or is unreachable

Thanks for drafting these!

**Comment by IAmAnubhavSaini** [comment]
On how to show the error to user: I am leaning towards showing an alert. The alternative is putting it on Deploy modal, error notification banner.

Let me know your thoughts.

**Comment by RakshaKShetty** [comment]
the toast is displayed  as in image<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/161526254-74a6d39c-0425-4acc-8d5b-a94b6e0e3b8a.png">
