### ISSUE TITLE
[Bug]: Error When Adding a User to an Organizaion Using Firefox Browser

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#12280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to add a user to the organization, an error is received on Firefox. The "Oops! Something went wrong" page is displayed.

![image](https://user-images.githubusercontent.com/101268423/160348482-9605f5d0-5430-4664-b3d1-4d4210a28b49.png)

Environment:
Firefox 98.0.2, on Ubuntu Linux 20.04

### Steps To Reproduce

1. In the 'dashboard'/home page, click the **Share** button.
2. Enter an email address.
3. Try to 'choose a role'.

Result: able to choose a role, but getting an "Oops! Something went wrong" page.

### Version

Self Hosted

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith this seems to be working for me. Please share a video on how to reproduce this

**Comment by Irongade** [comment]
> @ame-appsmith this seems to be working for me. Please share a video on how to reproduce this

@ame-appsmith Same here.

**Comment by ccrockett** [comment]
@ame-appsmith This is still happening for me with `Appsmith Community v1.9.10` and `Firefox v111` on `Pop!_OS 22.04 LTS`. Screen shots and video provided below:
![Screenshot from 2023-03-27 10-01-28](https://user-images.githubusercontent.com/169208/227980510-a0df06a9-a0b7-42fb-a9cb-a0b5ff4587de.png)
[Screencast from 03-27-2023 09:59:17 AM.webm](https://user-images.githubusercontent.com/169208/227980637-eaaf4fa4-7063-4e1d-a2f1-4ef02e7018eb.webm)

**Comment by ccrockett** [comment]
After a little debugging, I found the issue was caused by a Firefox extension (specifically firefox relay) adding extra elements in the email box. Once I disabled the extension if works in Firefox now.
