### ISSUE TITLE
[Bug]: Tooltip for Json form widget's Datepicker type is not working

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#12293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Uploading image.png…]()

### Steps To Reproduce

1. Add Json form widget
2. Create a datepicker type field
3. Add Tooltip for datepicker
4. Observe tooltip is not being displayed for Datepicker fields and displayed for other type fields

### Version

Cloud/Release

**Comment by btsgh** [comment]
Tested in Release. Tooltip is now being displayed for Date picker in JSON Form
<img width="372" alt="Bug12293" src="https://user-images.githubusercontent.com/101863839/160983993-7a6a9469-df3d-489d-8f46-604e9a95d755.png">
