### ISSUE TITLE
[Bug]: Currency Input rounds off text  if there is a trailing zero

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#12297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user enters `11.90` on the Currency widget and clicks outside, the text gets rounded to `12`.

### Steps To Reproduce

1. Drop a currency widget on the Canvas
2. type `11.90`
3. Click outside the widget.
4. Observe that text gets rounded to `12`.

### Version

cloud

**Comment by pranavkanade** [comment]
@Nikhil-Nandagopal @sbalaji1192 If this is a quick fix can we please prioritize it? A user is blocked by this -
> We are in the process to deliver this project to a customer.

**Comment by sbalaji1192** [comment]
@pranavkanade I already working on this. will push this for next release.

**Comment by btsgh** [comment]
Tested in Release - Fixed
<img width="441" alt="Bug12297" src="https://user-images.githubusercontent.com/101863839/160990646-9b17328d-55a8-4d4d-9740-f9d06ee27ed2.png">
.
