### ISSUE TITLE
[Feature]: deprecation warning on widgets

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#12291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need to integrate a “deprecation” of widgets notification. The goal is:

- [ ] How to signify that a widget — currently on the canvas — has been deprecated to an Appsmith developer? and that they should drag and drop a new widget of the same type from the widgets panel.

We need to add a new flag `deprecated: true` to the widget configurations of the widget which has been deprecated. This will be a platform level change, followed by the widgets that need this property.

### Why should this be worked on?

Today in Appsmith it's not possible to notify the developer of any widget depreciation so that they can take an action and avoid any breaking changes in their apps.

**Comment by somangshu** [comment]
#3613 is related to this, We have two ways to move forward
- [ ] Migrate all references, Create a checklist to test, Create all relevant tests, Use all the form references in internal apps to test all the use cases: `Confidence 80%`
- [ ] Do not touch the older references, Do not add any migration, Create v2 to use button, show error on all old formButtons through validations or the above suggestion. `Confidence 100%`

We will move ahead based on the final call on the above.

**Comment by somangshu** [comment]
I found clean URL implement something new which felt relevant 👇 


<img width="456" alt="Screenshot 2022-03-29 at 1 14 22 PM" src="https://user-images.githubusercontent.com/11089579/160620996-d4cc2e0e-0ee6-46fe-b93c-9f263d502328.png">

<img width="1093" alt="Screenshot 2022-03-29 at 1 14 35 PM" src="https://user-images.githubusercontent.com/11089579/160621010-d52a7572-7421-4742-8434-7f1dc6a0c85e.png">

**Comment by somangshu** [comment]
@rohitagarwal88 please look into this, Need you to take this forward

**Comment by rohitagarwal88** [comment]
@momcilo-appsmith : Can you look into the design for the deprecation?

**Comment by momcilo-appsmith** [comment]
@rohitagarwal88 is this all we need:

1. norification when it happens
2. Indicator that a widget on the canvas is deprecated?

Do we also need to show this for variants of a widhet (e.g. number input in the input widget)?

**Comment by rohitagarwal88** [comment]
> @rohitagarwal88 is this all we need:
> 
> 1. notification when it happens: **Yes**
> 2. indicator that a widget on the canvas is deprecated? **Yes**
> 
> Do we also need to show this for variants of a widget (e.g. number input in the input widget)? **No**

**Comment by aswathkk** [comment]
Related: #9014

**Comment by somangshu** [comment]
cc @vasanth-appsmith @rohitagarwal88 Additional context from a user.
![Screenshot 2022-04-19 at 12 45 31 PM](https://user-images.githubusercontent.com/11089579/163947107-527ad363-bbeb-4010-94d4-5b531650626f.png)

**Comment by vasanth-appsmith** [comment]
> cc @vasanth-appsmith @rohitagarwal88 Additional context from a user. ![Screenshot 2022-04-19 at 12 45 31 PM](https://user-images.githubusercontent.com/11089579/163947107-527ad363-bbeb-4010-94d4-5b531650626f.png)

Good one @somangshu Thanks. But we are not doing the upgrade widget right now correct?

**Comment by vasanth-appsmith** [comment]
@rahulramesha Please check the design for this. Let me know if you have any questions. [Figma](https://www.figma.com/file/EIJQ6jccl6uvNQul3nD6f0/Deprecated-Widget?node-id=12%3A6083)

**Comment by rahulramesha** [comment]
@Pranay105 @jnikhila Need your help in deciding a warning message. For the deprecated widgets, we are currently planning to add the message, “**There’s a newer version available. The current version will not be maintained.**” This message might sound a bit stiff to the user. Can you guys suggest some alternatives or does this message sound good?

![image](https://user-images.githubusercontent.com/71900764/167306265-e07328ff-4dbc-4d7a-ae00-bb874b050a64.png)

cc: @dilippitchika @vasanth-appsmith @rohitagarwal88

**Comment by jnikhila** [comment]
@dilippitchika , @rohitagarwal88 , @vasanth-appsmith 

A couple of questions -
-  Is the current version maintained for some time frame and can that be accessible to be added to the message so that users can have time to update and move to a newer version?
- Can the WIDGET_NAME be dynamically populated?
- Instead of the current version can the actual version used by user is available so that we can add to the message?

**The base message can be as follows:**

`We urge you to update to a [NEW_VERSION] of [WIDGET_NAME]. The [CURRENT_VERSION] is [deprecated/discontinued] and will not be supported.`

**Based on whether the support is available for a stipulated time frame we can choose either deprecated or if no support is available then discontinued.**

We can amend the message based on the above confirmations.

**Comment by rohitagarwal88** [comment]
To answer your question @jnikhila 

- Is the current version maintained for some time frame and can that be accessible to be added to the message so that users can have time to update and move to a newer version? **The current version would work, and the user would see the message whenever he opens the property pane. For example, the User has a button V1 widget in his app, and we release V2. His App would work as expected but if he drags the button from the widget panel then he would get V2. Also, the user can upgrade as per convenience & we will support him on discord**
- Can the WIDGET_NAME be dynamically populated? **Yes**
- Instead of the current version can the actual version used by user is available so that we can add to the message? **We do not maintain the version as of now. We just release new widgets and hide the older widgets. Name is changed like Input_widget_v2, datepicker_v2**

Hope that helps, do let me know if you have any other questions.

**Comment by btsgh** [comment]
Unable to test this as the message is not coming as per Discussion with @rohitagarwal88

**Comment by rahulramesha** [comment]
@btsgh This message only appears in the propertyPane of deprecated widgets. Unfortunately any new widgets that are added are not deprecated hence, it can't be seen. you can try testing in this application https://appsmith-git-deprecationwarning-get-appsmith.vercel.app/app/deprecated-warning-message-test/deprecated-widgets-6274de107c6b4e16b81a24a3/edit, This application has all the deprecated widgets,

**Comment by btsgh** [comment]
Thanks @rahulramesha .. Looked up the above application. I see these widgets in your app - Input widget, Select widget, Date picker widget, File Picker widget, MultiSelect widget, Form Button, Progress Bar, Circular Progress .. and when I click on each one, I see this message - 
![Screenshot 2022-05-13 at 10.03.48 PM.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/fb8e06f3-40eb-417b-b4f5-a49d2cf131d1)

Also, on adding any of the above widget newly, I do not see the message, which is the right behaviour as per your update above. 

However, for the FormButton widget, if I add a new Form widget, and select the Submit or Reset button on it, I see the above message. As per your explanation above, the Submit and Reset buttons in the newly added Form widget should not show the deprecated message as they are newly added, is that right?  Please let us know. 

Also, do let us know if there is any other scenario that you would like us to test around this.

**Comment by jnikhila** [comment]
Thanks @rohitagarwal88. Based on the confirmation we can use the message as follows:

`
 **Heading** - Stay Up-to-date
 **Message** - A new version of [WIDGET_NAME] widget is available. Upgrade to enjoy enhanced experience.
`
CC: @rahulramesha @dilippitchika

**Comment by rahulramesha** [comment]
@somangshu, we are currently adding deprecated warning to `Form Button Widget` as well.  I was under the impression that it is already migrated. Need your confirmation if we should do that as `Form Button Widget`  is not migrated yet.

**Comment by rahulramesha** [comment]
Thanks @jnikhila. 

@rohitagarwal88 @dilippitchika does this sound good, should I move ahead with making changes to show @jnikhila's message instead?

**Comment by somangshu** [comment]
@rahulramesha the form button widget is not yet deprecated, We have the open issue here > https://github.com/appsmithorg/appsmith/issues/3613

Once this change is in, We would like to create a V2 based on [this](https://github.com/appsmithorg/appsmith/pull/11152#issuecomment-1067659518) discussion. Please let me know if you need more info here.

**Comment by btsgh** [comment]
Tested the new message as per discussion above and all the widgets in the deprecated app shared above. Seems fine.

**Comment by jnikhila** [comment]
@rohitagarwal88 - Could you please confirm, what user action is needed when the widget is deprecated? We can then amend the message accordingly.
