### ISSUE TITLE
[Task]: Optimize blob conversion during execution for file picker inputs

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#12294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently we read blob urls into string text while executing, and then convert the text into a plain text blob to ensure correct encoding while passing the data over the network. There is a possibility of skipping these conversions in some conditions that we should investigate.

**Comment by AmanAgarwal041** [comment]
#### Analysis :
There is a function inside `app/client/src/sagas/ActionExecution/PluginActionSaga.ts` file which has a function `evaluateActionParams`. The above task is referenced to this particular functionality.
