### ISSUE TITLE
[Bug]: The Get started button doesn't work in welcome page 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Get started button doesn't work when user try to signup with the google auth this is for non super admin 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/160399979-f0b21ca0-cf23-466c-8fb7-a77e7877ee58.png">

### Steps To Reproduce

1. Run the ce fat conatiner
2. inside the local host set up the google auth
3. Now try to signup with the new user in the google auth
4. Inside the welcome page when user clicks on get started button the user is not navigated to the hope page
 

### Version

local

**Comment by arunvjn** [comment]
Looks like a backend issue since redirect URL doesn't contain the URL origin info.

**Comment by arunvjn** [comment]
> Looks like a backend issue since redirect URL doesn't contain the URL origin info.

Found the issue. Looking into it now.
