### ISSUE TITLE
[Bug]: Import application redirects to url with no application id

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bfcbcceeab7843b7a0130f10168edc30-00001.gif)](https://www.loom.com/share/bfcbcceeab7843b7a0130f10168edc30)

### Steps To Reproduce

Though this is difficult to reproduce when tried importing the golden app on release I faced this issue.

### Version

1.6.17

**Comment by ramsaptami** [comment]
Verified only by uploading the same `Golden app` and works fine now
