### ISSUE TITLE
[Bug]: Evaluation fails to throw an error when 'null' is used, however using 'NULL' is accepted

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using `''` and `NULL` does not lead to an evaluation error but using null throws an error

Also, any upper case value does not lead to an error state

### Steps To Reproduce

1. Go to a select widget and set default value as `''`, `null` and `NULL` and observe that only null is unacceptable

![image](https://user-images.githubusercontent.com/79509062/160398196-b024b893-1413-4377-a0db-b3ea9ea22aa2.png)
![image](https://user-images.githubusercontent.com/79509062/160398320-99a107f5-bc76-443b-8dc7-bc2064e187cb.png)

### Version

Cloud

**Comment by btsgh** [comment]
Tested on Release, seems to be fixed. (Behaviour video below -)
https://www.loom.com/share/ecec38b089a243d1ba2d6cd14f281098
