### ISSUE TITLE
[Bug]: Organization name can be empty

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Organization name can be left empty from General page 

https://loom.com/share/45f0b5c1570c4337b248fc3989306c57 

### Steps To Reproduce

1. Go to Release
2. Click on three dots next to the organization > Settings
3. In General page remove the Org name.

### Version

Cloud

**Comment by vishnu-gp** [comment]
Fixed with https://github.com/appsmithorg/appsmith/pull/12805
