### ISSUE TITLE
Add BE analytics event for templates

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#12319]

**Comment by nayan-rafiq** [comment]
@kocharrahul7 I've logged and attached application name property when template is forked. What other things we need to do for this? We're logging event for fork template only.

**Comment by kocharrahul7** [comment]
This is enough for now.

I assume we have a user ID as well, so we can see the total number of users who are forking templates?

**Comment by nayan-rafiq** [comment]
Yes, that's correct.
