### ISSUE TITLE
[Feature] Utility script to update the nginx proxy for client when running locally

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1231]
## Summary
Need a small script(node.js or bash) that will update the api backend when the client is running locally. This script would make sure the nginx config in the docker container is correct and running without changing any source code.

## Motivation
This helps in switching between backends easy.
Currently changing the api backend for the client is cumbersome with the following steps:
1. Shut down the wildcard-nginx Docker container by running: sudo docker stop wildcard-nginx && sudo docker rm wildcard-nginx 
2. In the file docker/templates/nginx-linux.conf.template, change all occurrences of http://localhost:8080 to https://release-api.appsmith.com. 
3. Run start-https.sh to bring up the wildcard-nginx container again.
If we can automate this by running a script, it would be very easy to switch for development purposes.

## Additional Context
We already have start-https.sh script that does part of the work. We should probably just enhance that to handle switching as well

**Comment by mohanarpit** [comment]
I think a much better solution is to bring up the API server on the local machine as well. Ensures that the entire Appsmith system is running independently on the developer's machine. This can be done by modifying the file `app/server/docker-compose.yml` in conjunction with the `.env` file that will be created at the root of the project.

**Comment by hetunandu** [comment]
Having a local server running is helpful but does not solve the issue with switching app backends. I would argue that when we do start having a local server, the switching would become more often and this script gets more handy.

**Comment by ofpiyush** [comment]
If you have a specific preference order, you can use `proxy_next_upstream` to achieve this.

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream

The typical setup could be to have local server as the first upstream and 

PS: Only do it for 502 errors else you might miss errors on local.

**Comment by hetunandu** [comment]
Fixed with #1756
