### ISSUE TITLE
[Bug]: Errors and Logs get clipped on debugger

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#12314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1530" alt="Screenshot 2022-03-28 at 19 59 30" src="https://user-images.githubusercontent.com/46670083/160530015-7e2a6d65-e112-4c3e-b654-8bdd45a3d541.png">
<img width="1536" alt="Screenshot 2022-03-28 at 19 59 58" src="https://user-images.githubusercontent.com/46670083/160530026-04d565f3-38b4-4b33-b975-c18427109234.png">

### Steps To Reproduce

* Ensure that there are at least 3 errors in the App
* Navigate to Api pane and check the Error tab

### Version

Cloud

**Comment by btsgh** [comment]
Tested on Release. Found to be fixed.
<img width="864" alt="Bug_12314_1" src="https://user-images.githubusercontent.com/101863839/161811701-b0b280a3-2105-48e2-91a2-1e46d6ebb04a.png">
<img width="1109" alt="Bug_12314_2" src="https://user-images.githubusercontent.com/101863839/161811724-416bdfde-5a60-4077-bc9c-46cb70a90464.png">
