### ISSUE TITLE
[Bug]: Serialise fields with map datatype in a predicatable order 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#12327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As the map datatype does not have the predictable order, this is giving pending uncommitted changes even if user haven't updated anything for the git connected application. 

### Steps To Reproduce

1. Connect app to git
2. Add actions to the app
3. Commit and push so that there are no pending changes
4. Check status, you will see pending changes randomly even if nothing has been changed

### Version

Cloud

**Comment by Parthvi12** [comment]
I am facing this issue with my app where I followed these steps

**Comment by abhvsn** [comment]
This is not the right place to report this issue, as we are discussing the `Map datatype` here. @Parthvi12 but this seems like a change in JSObject, is this reproducible everytime?

**Comment by Parthvi12** [comment]
@abhvsn Oh ok, closing this issue, I'll create another one as I am able to reproduce this every time.
