### ISSUE TITLE
[Bug]: Grouped widgets get placed outside the original canvas

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#12320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When grouping widgets into a container. The widgets get dumped outside of the intended canvas and get rendered on the main canvas

### Steps To Reproduce

1. Add a Modal widget
2. Select the two default buttons 
3. use the "cmd + G" shortcut or the UI mechanism in the video

https://user-images.githubusercontent.com/103687/160551996-7602c81d-5c23-42dd-85f4-762918799df2.mov

### Version

Cloud / All

**Comment by btsgh** [comment]
Tested on release, the grouped widgets remain original canvas.
