### ISSUE TITLE
[Bug]-[2600]:Generating New Page with new Mongo DB data source, error pops up the first time.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#12329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On generating a new MongoDB data source, and Generating New Page with a valid collection user gets an error though the page seems to have been generated

### Steps To Reproduce

1. Create a new data source, choose MongoDB data source
2. Choose the following 
- Connection type: Replica set 
- Host address: mockdb.kce5o.mongodb.net
- Database name: <appropriate db name>
- User name: <appropriate user name>
- Password: <appropriate password>
- Click on Test, and on success, Save the data source.
3. From the data sources page, Active tab, Click on Generate New Page from the new data source you created. 
4. Select the appropriate collection. Click on Generate page. 
On the generate page UI, an error and a success message comes up. 
<img width="350" alt="Bug_MongodbGeneratePage" src="https://user-images.githubusercontent.com/101863839/160571637-b435c6d6-3a96-499f-99a9-65f1f5b7e426.png">

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3702339d0621461fa7059245da9a5924-00001.gif)](https://www.loom.com/share/3702339d0621461fa7059245da9a5924)

Success message - Successfully generated a page
Error message - The action FindQuery has failed

### Version

Release

**Comment by btsgh** [comment]
<img width="641" alt="FindQuery2" src="https://user-images.githubusercontent.com/101863839/160594814-45a3924d-df98-4280-8185-4164becff0c8.png">
<img width="654" alt="FindQuery1" src="https://user-images.githubusercontent.com/101863839/160594824-73484517-a9b5-4444-b0e9-18792de5f791.png">
Error and log observations.

**Comment by Nikhil-Nandagopal** [comment]
@btsgh can you please share the app? Is this because the datasource is configured incorrectly?

**Comment by btsgh** [comment]
@Nikhil-Nandagopal .. I wouldn't think the data source is configured incorrectly, as, when I do a generate page a second time from the same DB, the page gets generated just fine. This is observed only the first time, when I create a new MongoDB data source, and generate page for the first time.

**Comment by Nikhil-Nandagopal** [comment]
## Stats
| Stat | Values | 
| ------------- | ------------- |
| Reach     | 200 |
| Upvotes   |  |
| Commentors   |     |

**Comment by arunvjn** [comment]
@btsgh Unable to replicate this locally. Is there an existing app where I could replicate this ?

**Comment by btsgh** [comment]
@arunvjn - unable to reproduce it on the current environment. Looks like it has been indirectly fixed.
