### ISSUE TITLE
[Type]-[2500]:Mouse hover issues

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#12322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- The hover on the widget icons switches to pointer from drag.

https://user-images.githubusercontent.com/103687/160553979-662afdba-bef4-4907-aa83-312c3ed7944f.mov

- The text on the user profile page is clickable however, the pointer doesn't signify the same

https://user-images.githubusercontent.com/103687/160554142-0dbed90f-ba08-41ae-9588-6aebe6b7d711.mov

- Two upload modals have different UI.

<img width="784" alt="Screenshot 2022-03-29 at 12 23 17 PM" src="https://user-images.githubusercontent.com/103687/160554263-372022c2-68d5-43da-a3e2-e0311210450b.png">

<img width="792" alt="Screenshot 2022-03-29 at 12 21 36 PM" src="https://user-images.githubusercontent.com/103687/160554249-b040d19e-eb36-4198-b873-6de8d76d4460.png">

**Comment by riodeuno** [comment]
The entity explorer has a strange experience when clicking on the + Add Widget. The screen recording is attached.

https://user-images.githubusercontent.com/103687/160562983-b80b5b02-96a6-4cff-b1de-8f7659ff44ca.mov

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5000 |
| Effort (months)  | 1 |

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
