### ISSUE TITLE
[Bug]: Projection Component Issues

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#12348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Options do not show up in Projection Component
- `data` in request payload is adding quotes

#### Issue 1: Columns dropdown do not show options
1. Create Google Sheet datasource
2. Create Query for the same and choose the command Fetch Many
3. Scroll down to `Columns` dropdown and click on it
It will not show any options.

#### Issue 2: `data` in request payload is adding quotes

1. Create Google Sheet datasource
2. Create Query for the same and choose the command Fetch Many
3. Scroll down to `Sort By` and add column name in component mode
4. Click on `SWITCH TO JSON EDITOR`. Observe the payload, `data` is an object here. This is expected behaviour
5. Now make a change in `json` mode and observe the payload again. `data` is now being sent with quotes. This is a bug. 

### Public Sample App

https://uqi.appsmith.com/projectioncomponentissue/page1-623abe446424322bbfd16bea

### Version

Cloud

**Comment by nidhi-nair** [comment]
Fixed with configurations and fetch dynamic values feature.
