### ISSUE TITLE
[Bug]: Renaming from entity explorer does not work as expected on Mozilla Firefox

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Renaming from entity explorer does not work on Firefox and any JSObject/API query that is renamed from here goes through refactor but linter picks it up as undefined and widget goes into an error state

### Steps To Reproduce

1. Rename a JS object from the entity explorer and observe the corresponding binding refactor based on new name - but the renaming fails and reverts back to the old name
2. Refresh the page and observe the bound widget in error state as seen in the video

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/54ceae8f3dd245a1bd5f7f2417f7fffe-00001.gif)](https://www.loom.com/share/54ceae8f3dd245a1bd5f7f2417f7fffe)

### Version

Cloud

**Comment by kocharrahul7** [comment]
@ramsaptami I am not able to replicate this issue, can you please confirm that this is an existing issue, or if it has been resolved?

**Comment by ramsaptami** [comment]
Closing this since this seems to be fixed
