### ISSUE TITLE
[Bug]-[2400]:Clicking on forget password doesn't work if focus is on the password field

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#12345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking forget password doesn't work if the focus was on password input, as we show user an error that password field cannot be empty.

There is one more place where this issue occurs, while editing the name of the app when the app is open, and we try to clear out the name, it throws a toast about name cannot be empty. App should wait to see if focus is lost and if so, then show the alert.

I think we need to track dirty state via `isDirty` flag in these components. If the form is not dirty, then don't show the error and don't block the event from firing. 

### Steps To Reproduce

1. Go to login, 
2. click on the password field, 
3. click on forget password, 
4. see that click doesn't work.

### Screenshots and screen captures

https://user-images.githubusercontent.com/1573771/160623658-c127be4a-7f2f-44bb-b1dd-b3d43f61a4bb.mov

https://user-images.githubusercontent.com/1573771/160623682-07114bb5-9138-473f-860a-215d0ff3cdb0.mov

Even while editing organisation name

![Screenshot 2022-03-29 at 7 04 41 PM](https://user-images.githubusercontent.com/1573771/160623711-d06013db-93cd-42b7-aa5f-a2da378a9287.png)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi @vuiets can we please fix this?

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.25 |

**Comment by vuiets** [comment]
People who've signed up in the last 6 months: 24000
Guestimating that the number 25% of these use form login (Couldn't find the event to estimate this right): 6000

**Comment by Nikhil-Nandagopal** [comment]
Updated the estimate assuming 10% of users ever forget their password

**Comment by IAmAnubhavSaini** [comment]
The forget password event should keep track of dirty state of the input form and on blur/lost focus, it should see if the form is dirty and if it was, the throw the error/warning. If user just clicked in the input fields and didn’t enter and remove any value, then the form state is not dirty, and error should not be thrown, also the click should work.

The other scenarios are due to eager evaluation of empty input field and showing error as soon as possible.

---


I think I mixed two slightly different types of bugs here. One is eager evaluation of the input field value when we are naming things: orgs, apps etc. The other is not keeping track of dirty state of input form to show error properly, e.g. forget password scenario.

**Comment by berzerkeer** [comment]
> The forget password event should keep track of dirty state of the input form and on blur/lost focus, it should see if the form is dirty and if it was, the throw the error/warning. If user just clicked in the input fields and didn’t enter and remove any value, then the form state is not dirty, and error should not be thrown, also the click should work.
> 
> The other scenarios are due to eager evaluation of empty input field and showing error as soon as possible.
> 
> I think I mixed two slightly different types of bugs here. One is eager evaluation of the input field value when we are naming things: orgs, apps etc. The other is not keeping track of dirty state of input form to show error properly, e.g. forget password scenario.

Right now, I am only able to fix the issue with form login password field. With the application name and organisation name we are using <EditableTextSubComponent/> in which we are forcibly calling the InputValidation callback on input change. So we should actually move that out of that component, and give the developer who uses the EditableText component have control on how and when to validate the field.

**Comment by berzerkeer** [comment]
Reopened so that we can track the EditableText issue.

**Comment by Nikhil-Nandagopal** [comment]
@berzerkeer can we open a separate issue that is not as critical as this one for that case since it does not seem like it blocks the user in those cases?

**Comment by berzerkeer** [comment]
@Nikhil-Nandagopal Sure i will do that.

**Comment by berzerkeer** [comment]
Created an issue to for other cases - https://github.com/appsmithorg/appsmith/issues/13779
