### ISSUE TITLE
[Bug]-[5600]:Evaluate Value not included in Body of GET Request.

### ISSUE THREAD

**Issue by Irongade** [appsmithorg/appsmith#12343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user uses dynamic bindings in raw body of a GET request it does not get sent in the body of the request when it is ran despite it showing up in the evaluated pop up.

![Screen Shot 2022-03-28 at 9 40 26 AM](https://user-images.githubusercontent.com/37867493/160619626-67cf0320-0ebf-43cb-9f3b-5fe74a925030.png)

### Steps To Reproduce

1. Create a GET request
2. Add a key-value in the raw body of the request, with the value being a dynamic binding.
3. Run the query and observe that the object is not included in the request.

### Version

1.6.16

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3500 |
| Effort (months)  | 0.25 |

**Comment by nidhi-nair** [comment]
This seems to be a client side issue, reassigning to @ayushpahwa who is looking into this right now.
