### ISSUE TITLE
[Bug]: Discard API bug not resulting in proper change discard

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#12344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Discard API is not able to cleanly discard changes.

---

When I try to delete a datasource which has associated actions, after that discarding action doesn't result in clean state.

https://user-images.githubusercontent.com/1573771/160620328-7aa650b2-2608-4597-a80c-d482746a7186.mov

---

Another case

https://user-images.githubusercontent.com/1573771/160620624-371d6b04-cc66-431d-8b4b-d5b274946c14.mov

On commit:

![Screenshot 2022-03-29 at 5 35 36 PM](https://user-images.githubusercontent.com/1573771/160620678-15059d1c-566a-471e-9e13-5a6c01c9c3ce.png)

### Steps To Reproduce

1. Add a bunch of datasources, objects and pages to a git connected repo.
2. Try making changes after first commit.
3. Click Discard changes button.

For exact steps please take a look at the attached videos.

### Version

Release

**Comment by IAmAnubhavSaini** [comment]
PR for discard changes: https://github.com/appsmithorg/appsmith/pull/11835, DP link can be picked from there.

**Comment by abhvsn** [comment]
For client-side migration, we have decided to depend upon letting users know about the migration. This is because the server doesn't have any way to run the client-side migration, which is resulting in uncommitted changes showing up even after the discarded change is executed successfully.

**Comment by abhvsn** [comment]
@IAmAnubhavSaini I'm not able to reproduce the bug when we have updates for queries, JSObject and pages etc and user tries to delete the datasource which already has the queries attached. If you are still facing the issue can you please list down the steps to reproduce? 
For ref: https://www.loom.com/share/ddb8af641cb8410c9634aa25d37d33eb

**Comment by abhvsn** [comment]
For updates to the `rightColumn` property we have fixed this in the recent PR and the version we are dependent on the migration messaging as stated earlier https://user-images.githubusercontent.com/1573771/160620678-15059d1c-566a-471e-9e13-5a6c01c9c3ce.png

If we are satisfied and unable to reproduce the issue related to the datasource deletion we can close this issue 
cc: @IAmAnubhavSaini

**Comment by IAmAnubhavSaini** [comment]
Looks like #12351 fixed it.
