### ISSUE TITLE
[Feature]: Add Support for Azure Container Instance Deployment

### ISSUE THREAD

**Issue by hockeyrjc** [appsmithorg/appsmith#12353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add Deploment support for Azure Container Instances.

### Why should this be worked on?

Self-hosted does not support this configuration. An Azure VM is overkill when this can be implemented as a PAAS service

**Comment by jrotello** [comment]
I am currently hung up getting things running on Azure Container Instance. The main issue appears to be with the Azure Storage Driver for Docker. File permissions don't play nicely with mongo key. See the following thread from Discord for logs and error messages (https://discordapp.com/channels/725602949748752515/1013810425546149889).

**Comment by sharat87** [comment]
Hey @jrotello, thank you for your interest in Appsmith, and the offer to help. I'm not very familiar with Azure myself so I'll call upon your offer to help on this. Would it be possible to put up some steps to do to deploy Appsmith on Azure Container Service (AZS)? I'd like to try with those exact steps and, if I reproduce the problem, see what we can do to resolve this.

I think the problem with working on this issue right now is less of a lack of interest, and more of a lack of the right know-how. Steps to reproduce this would be gold. Thank you!

**Comment by jrotello** [comment]
Hi @sharat87,

Thanks for the quick response! Here are some basic instructions that should get you up to the point where it is failing. Let me know if you have any questions.

1. Ensure you have an active Azure subscription
2. `docker login azure` and follow the prompts
3. `docker context create aci <context name>` (ex: `docker context create aci appsmithctx`)
4. `docker context use appsmithctx`
5. Download the attached compose file and update `<storage_account_name>` with the name of the storage account to be created in your Azure subscription.
    * **NOTE:** You can probably safely update the resource reservations to 1 CPU and 1G of memory for this testing.
    * [docker-compose.zip](https://github.com/appsmithorg/appsmith/files/9461864/docker-compose.zip)
6. `docker compose --file docker-compose.aci.appsmith.yml up`
    * All the necessary Azure resources should be created for you automatically. They will be created in the resource group you assigned when creating your Docker context in step 3.
    * To tear down the resources use `docker compose --file docker-compose.aci.appsmith.yml down` This we remove the Azure Container Instance resources, bur leave the storage account around. If you want to remove the storage account as well, then you will also need to run `docker volume rm <storage_account_name>/stacks`

I think the underlying problem as it stands right now is that the `azure_file` Docker Storage Driver uses SMB under the hood and setting linux file permissions on it doesn't seem to do anything. I haven't tested it, but I'm wondering if there might be a similar issue when running on Windows Subsystem for Linux. See `/appsmith-stacks/logs/mongodb/db.log` for the permission error.

Please let me know if I can be of further help!

**Comment by gguille077** [comment]
this would be just great

**Comment by sum35h** [comment]
@hockeyrjc  @gguille077 @jrotello  The documentation for installing Appsmith on Azure Container Instance had been published [here](https://docs.appsmith.com/getting-started/setup/installation-guides/azure-aci).
