### ISSUE TITLE
[Bug]: Label does not show on top of Password text inputs when resized

### ISSUE THREAD

**Issue by Irongade** [appsmithorg/appsmith#12355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Normally When a Text input is resized the Label moves to its top. But for Password Text inputs this behaviour does not happen.

https://user-images.githubusercontent.com/37867493/160695912-bfcbd25b-258b-4f6b-9cdd-92cc3a17d612.mov

### Steps To Reproduce

1. Add an Input widget on canvas
2. Add a Label to it
3. Drag the input down and notice that the Label aligns to the top
4. Switch Data type to Password
5. Watch this alignment fail.

### Version

1.6.16

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @Irongade since we're now giving users the explicit control in the input to do this, we don't need to solve this issue right?

**Comment by dilippitchika** [comment]
Linking to #7064, @wmdev0808 please update the description of the pr to also add this issue

**Comment by btsgh** [comment]
This issue is now resolved. Based on the Feature 10600 that has been implemented, the controls have been given to user to set the size, position, width etc for the Label parameter. Works fine.
