### ISSUE TITLE
[Bug]-[8]:Unable to use `currentRow` inside Menu Color property of menu button in the table column

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2022-03-30 at 11 00 02 AM](https://user-images.githubusercontent.com/13262095/160757845-e7847044-be08-43ec-9a1b-b329e3cbae40.png)

### Steps To Reproduce

1. Create a table with the menu button column
2. Try to change the `Menu Color` property using `currentRow` 

### Version

Cloud

**Comment by somangshu** [comment]
There is a special control that we use in table widget property pane that allows us to use currentRow . Instead of the special control, a regular input control is used here for the JS mode of Menu Color.
We need to add this to the property config of the table widget

`customJSControl: "COMPUTE_VALUE",`

cc @ashit-rath

**Comment by ashit-rath** [comment]
@somangshu I'm not 100% sure but I think this change might involve a migration.

**Comment by somangshu** [comment]
Dev note: 
- [ ] point out implementation plan
- [ ] Create a QA checklist if a migration is involved (discuss internally)

**Comment by dilippitchika** [comment]
@somangshu making it lower priority, let's not pick this for now because the no. of users who have encountered this currently is too low.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2 |
| Effort (months)  | 0.5 |

**Comment by chandannkumar** [comment]
Tested this Bug on PR #15457 and seems fine

**Comment by felipejoribeiro** [comment]
I can't access row information using the `currentRow` definition inside the buttons of the menu button:

![Image](https://github.com/user-attachments/assets/047263a1-b466-4fcf-a0e1-c79ae1f1d805)

I miss this feature as this would allow for deletion without row selection. Options to go around this issue are very hacky.
