### ISSUE TITLE
[Bug]: Widgets selected from Query editor Suggestions does not show in Deploy/View mode

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/160795840-ba989cb4-55cb-4f2c-b504-c6314c2e29e1.mov

### Steps To Reproduce

1. Connect to a data source, eg: Postgress DB
2. Write a query to fetch data
3. Use the widget suggestions from right side of query editor & add the widget to the page
4. Verify page is saved & widgets are visible enabled & deploy the app
5. **Observer : In the Deploy/View mode - the widget does not show up & the page is empty**
6. **Expected: Widget suggestion is provided for quicker results & app should work fine as similar to creating app from scratch**

### Version

Prod/Release v1.6.17

**Comment by mohanarpit** [comment]
@Aishwarya-U-R Either this is not a bug or I'm unable to reproduce it. From the video, I can see that you haven't deployed the application before going to the "View mode". Can you try clicking on "Deploy" before checking the deployed version of the application?
