### ISSUE TITLE
[Feature]: Option to automatically import a frontend file on loading appsmith container

### ISSUE THREAD

**Issue by AleenaThomas-gh** [appsmithorg/appsmith#12363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently importing a json file has to be done separately after loading the appsmith container. But if there an option to specify in the startup file (for eg. in 'load_onstartup' variable in docker-compose file) the file to be imported, then this would be helpful because then all we need to do is start up appsmith and the json file is already imported.  

### Why should this be worked on?

This will be a useful feature to have a frontend user perspective, where the user do not use appsmith to develop/modify frontend applications, but only use an existing application to access a UI that has been already developed.

**Comment by Nikhil-Nandagopal** [comment]
Hi @AleenaThomas-gh ! Thank you for the feature request. Is there a reason why you need to start appsmith frequently? Generally we expect a single deployment to be accessible to multiple users
