### ISSUE TITLE
[Bug]: clicking on button in the table should not trigger `onRowSelected` event of the table

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `onRowSelected` of the table gets triggered if the user clicks on the button may have in one of the columns
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d30b507060cf4422afba26e59a22b4d3-00001.gif)](https://www.loom.com/share/d30b507060cf4422afba26e59a22b4d3)

### Steps To Reproduce

1. Create a table with button & add an `onClick` action
2. Add `onRowSelected` action for the table
3. Click on the button, you'll see that the `onRowSelected` also gets triggered.

### Version

Cloud

**Comment by dilippitchika** [comment]
@pranavkanade already tracking this here - https://github.com/appsmithorg/appsmith/issues/11403 🥲
