### ISSUE TITLE
[Bug]: Enable commit and push CTA in case we have local commits

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#12368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, as we have commit and push as a single operation we expect both the operation will succeed but in some cases, like auth fail etc this is not true, where we end up committing to local filesystem but push fails. This will result in a locked state to push to remote as commit and push is disabled:
![image](https://user-images.githubusercontent.com/41686026/160796514-fb2a3d3d-9ab5-4f27-87d7-8ec36ea3bb7e.png)

### Steps To Reproduce

1. Connect app with write access for ssh key
2. make initial commit and push
3. Remove write access for the ssh key
4. Try commit and push

### Version

Cloud

**Comment by infinitetrooper** [comment]
Stale
