### ISSUE TITLE
[Feature]-[250]:Support for Running selection in Query editors like any other editor in market

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/160760073-b6f99e1a-99e8-416b-951b-a40472f00198.mov

### Steps To Reproduce

1. Connect to any relational data source like postgres, mysql etc
2. Fire a simple query as shown
3. Now try to run a selection [User may want to use the same editor for multiple reasons]
4. Observe that running only selected part of query is not allowed
5. **Expected: Run selection should be allowed like any other available query editors for more flexibility**

### Version

Prod/Release v1.6.17

**Comment by Nikhil-Nandagopal** [comment]
@Aishwarya-U-R the video doesn't seem to be playing for me. Can you please add more information?

**Comment by Nikhil-Nandagopal** [comment]
Never mind, I was able to find it. Do you have an example of a query editor that does this?

**Comment by Aishwarya-U-R** [comment]
Anything like beekeeper studio (open source), Toad for Oracle databases, SQL server management studio etc...

**Comment by rohan-arthur** [comment]
SQL plugins, 6m usage: 5000
assume 1/4 of users want to test their queries like this: 1250

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1250 |
| Effort (months)  | <<number>> |

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur I think 1/4 is an excessive guess for this. I wonder how many people even knew of a power user feature like this

**Comment by Nikhil-Nandagopal** [comment]
Closing this. I don't believe this is actually useful for app development. It makes sense for analysis of data because you're trying to understand different parts of a query but for app building the final query that you write is what is most important
