### ISSUE TITLE
[Docs]: SSO | OIDC - Add Generic OIDC Configuration

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12376]
As part of this documentation, we can ask the user to create an application on their identity provider for Appsmith and ask the user to copy paste all the required fields onto Appsmith. Here we can add explicit call outs for scopes and username attribute fields.

Also, add below disclaimer to individual OIDC Pages:

> OpenID Connect is available only in the enterprise edition for self-hosted instances, and only the Superuser of your Appsmith organization can set up OIDC.

* Generic OIDC
* Auth0
* Okta
* PingIDentity

**Comment by jnikhila** [comment]
@trishaanand - Could you please add details to the ticket?

**Comment by trishaanand** [comment]
As part of this documentation, we can ask the user to create an application on their identity provider for Appsmith and ask the user to copy paste all the required fields onto Appsmith. Here we can add explicit call outs for scopes and username attribute fields.
