### ISSUE TITLE
[Bug]-[350]:Unexpected updates of widgets using the Appsmith store when calls to the store are made from a JSObject

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#12370]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Internal team discussion [link](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1656939805945449)

**I'm using the Appsmith store to set Default text on Inputs and Default value on Selects. What I'm seeing is that a widget that has a default driven by a store object created and accessed with my JSObject functions is _updated when another store object is set_ by my JSObject.**

I've discovered what I think is a bug in the interaction between JSObjects and the Appsmith store. It's a quite subtle bug but really annoying when you're building heavily data driven forms.

A small explanation of my reasons for writing this JSObject might be helpful. I'm using the Appsmith store quite a bit and I needed to organize all my `appsmith.store.foo_bar` values. So I wrote a JSObject, named `Store`, the core of which is made up of one property and two functions:

```javascript
export default {
  page: "test",

  get: (field) => appsmith.store[`${Store.page}_${field}`],

  set: (field, value = undefined) => {
    storeValue(`${Store.page}_${field}`, value)
  },
};
```

Using this I can now set and get Appsmith store objects using `Store.set("foo", 42)` and `Store.get("foo")`

As you can see in the code above there's also a property, `page`, that is used as a prefix to the store object names. This makes it easy to read and manipulate groups of values such as all that are associated with a certain page, and to separate "app globals" from "page globals". This is the main reason for setting this up, you need logical naming when juggling 50+ Appsmith store values! Another reason is that I experimented with storing objects rather than single values, again to group data into logical chunks, but this has the unwanted effect that when some part of such an object is updated all widgets using that object get updated. So I had to have a one-to-one relationship between a stored value and an Appsmith store name. Names with prefixes was the solution.

### Steps To Reproduce

I have created a small app and a video demonstrating this behavior and how it differs between using `appsmith.store.foo` and `Store.get("foo")`

The first pair of inputs, with buttons setting store objects to drive the default value, uses the regular `storeValue()` function and `{{appsmith.store.input1}}`. When both inputs have been set using the buttons, I change the value of Input1 manually, then I set the value of Input2 using a button that calls `storeValue()`. Input1 remains the same. This is expected, Input1 should not be affected by what happens to Input2.

The second pair of inputs are set using `Store.set()` and their defaults are driven by `Store.get()`. After both inputs have been given values using the buttons, the value of Input3 is changed manually. And when Input4 is now changed using the `Set input4 to 17` button, _the value of Input3 is changed to 42, the Appsmith store value of `test_input3`_! This is clearly different from how the first pair of inputs behave so... :beetle: 

https://user-images.githubusercontent.com/142613/160779006-c0ea3a37-8f1d-4347-b581-a443d7ed661c.mp4

The app only demonstrates the bug for Inputs, but similar behavior is seen with Selects. I haven't used it in other widgets, but it seems likely the bug is "universal".

### Public Sample App

https://app.appsmith.com/applications/62440bc6c99df2369931cbe6/pages/62440bc6c99df2369931cbe9

### Version

Cloud

**Comment by rohan-arthur** [comment]
at least 1400 users are aware of/are using storeValue in WIDGET_PROPERTY_UPDATE.
Let's say, of these, 50% use the function in a JS object, and of those, 50% face this error

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 350 |
| Effort (months)  | <<number>> |

**Comment by zzgvh** [comment]
As I'm using the JSObjects more and more and really seeing the benefits in terms of better organization and code re-use I would humbly like to post a **Bump!** for fixing this issue! IIFEs are getting kinda old :stuck_out_tongue_winking_eye:

**Comment by ravikp7** [comment]
@bharath31 Should we be picking this up?

**Comment by bharath31** [comment]
@ravikp7 yes. please investigate why store updates are dropped when run consecutively

**Comment by satbir121** [comment]
Tried replicating on [Sample app](https://app.appsmith.com/app/complex-store-updates/incorrect-634528f589020c7ac296b7dc). It is not reproducible anymore
