### ISSUE TITLE
[Feature]: Graphql Smart substitution - research

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

_As an engineer, I want to find the best option to implement smart substitution, so that I can enable more sophisticated GraphQL queries_

### Why should this be worked on?

this is part of graphql v1

**Comment by sumitsum** [comment]
To start with, the following use cases would be covered. More use cases would be added as and when they are discovered as we have done for other plugins as well. 
* binding value is a string - value would be substituted after wrapping inside quotes
* binding value is a number - value would be substituted without quotes
* binding value is a boolean - value would be substituted without quotes 
* binding value is a full query - value would be substituted without quotes 
* binding value is anything else - value would be substituted without quotes
