### ISSUE TITLE
[Task] Improve contrast for + new on Home page

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1238]
https://www.figma.com/file/RdWmO9Ny6SfkMZAFIhLKSU/Appsmtih-NUX-Workspace_Aakash?node-id=509%3A783

**Comment by K-Kumar-01** [comment]
Hello @Nikhil-Nandagopal  Can i work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@K-Kumar-01 unfortunately this issue is not up for grabs. Please have a look at our issues with the tag Good First Issue or Hacktoberfest 😄
