### ISSUE TITLE
[Task]: GraphQL Action refactor tests

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

_As an engineer, I should ensure the quality and sanity of the code flows by providing automated test cases on the server side_

@Sumit Kumar placeholder to list the test cases

1. All current REST API plugin tests must pass. 
2. All new GraphQL plugin tests must pass. 
3. Other new test cases might be added based on which components have been refactored.

**Comment by sumitsum** [comment]
Closing it since all REST API plugin tests are passing.
