### ISSUE TITLE
[Docs]: graphql documentation

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

_As an app developer, I should be able to understand how to use the GraphQL plugin by reading it up on the documentation website_

### Describe the improvement

this is part of graphql v1 https://www.notion.so/appsmith/PRD-Native-GraphQL-Support-8b67d6c768a04be0a65597ecf79c5cfd

**Comment by nidhi-nair** [comment]
We have this available on docs.appsmith.com now.
