### ISSUE TITLE
[Feature]: Graphql smart substitution for query body

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

_As an app developer, I should be able to use moustache binding in the graphql body without compromising the validity of the query, so that I can use more sophisticated queries_

1. queries can be transformed from business logic
2. dynamic data can be passed to the query at runtime

### Why should this be worked on?

this is part of graphql v1 https://www.notion.so/appsmith/PRD-Native-GraphQL-Support-8b67d6c768a04be0a65597ecf79c5cfd

**Comment by prapullac** [comment]
Not on the release yet

**Comment by prapullac** [comment]
Verified on the DP
