### ISSUE TITLE
[Bug] Signup Button is not showing for Customer Support Dashboard

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1241]
### Steps to reproduce the behaviour:
1. Open the customer support dashboard in incognito mode
2. The signup button is not showing for not logged in users

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : This looks like a frontend issue. The '/me' API is correctly returning back 'anonymousUser'. 
Also, I am not seeing the "Fork" option for the customer support application. This is because the  "appIsExample" field has been set to false. Was that done intentionally?
