### ISSUE TITLE
[Docs]: REST API multipart and binary data usage

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#12415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/connecting-to-data-sources/authentication

### Describe the problem

We don't have good guidance on how to use multipart form data as a content type on Appsmith. Since this experience is different from other products, we should create a page for this. Also, we've started to support binary data for REST. We should explain how this works, since the support for this will grow one plugin at a time.

### Describe the improvement

Same as above. I'll add a link to a Notion draft as a comment later.

**Comment by nidhi-nair** [comment]
Draft: https://www.notion.so/appsmith/Multipart-and-Binary-data-be27baa167c546d5a92abbff8e6f15b5

**Comment by Pranay105** [comment]
@ajinkyakulkarni can review the first draft and move it to Sprint Backlog?

**Comment by jnikhila** [comment]
@nidhi-nair - Could you please confirm the release date for this ticket?

**Comment by nidhi-nair** [comment]
@jnikhila This change is already on prod, better docs requirement was an afterthought in this case :)

**Comment by jnikhila** [comment]
Thanks @nidhi-nair

**Comment by spark-c** [comment]
[PR available here](https://github.com/appsmithorg/appsmith-docs/pull/735) for review
