### ISSUE TITLE
[Bug]-[3500]:Binary Form Data

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#12414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to add body in Binary form data and user forgets to add type. It is observed that we are not showing any error on RUN action it is important for us to display and understand the type of data that is being sent.

### Steps To Reproduce

1) Navigate to API pane 
2) add a POST request data
3) Navigate to Body
4) Select : Binary Form data 
5) Ensure type is not select 
6) Click on RUN 
and observe 
no error message is displayed to a user 

### Version

release & prod

**Comment by rohan-arthur** [comment]
assume 50% of 3500: 1750

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1750 |
| Effort (months)  | 0.25 |

**Comment by sneha122** [comment]
The issue requires backend validation on type field

**Comment by Tallon66** [comment]
@prapullac Could I please be assigned this issue.

**Comment by prapullac** [comment]
@Tallon66 : Can you please pick one from the list mentioned below 
https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest
Thank you and wish you the best
