### ISSUE TITLE
[Bug]: Button group widget onClick doesn't work for buttons

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#12410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Button group widgets on click functionality doesn't work when a button is bound to onClick both in edit and view mode.

### Steps To Reproduce

1. Add a new button group widget
2. Bind onClick property for the buttons in the button group
3. Click the button to see that the action doesn't get executed

### Version

Production

**Comment by dilippitchika** [comment]
Loom - https://www.loom.com/share/12fb7fe7f2ef4d8496f9a6897354f64c

**Comment by yaldram** [comment]
@dilippitchika @techbhavin @sbalaji1192  I think the issue is in `ButtonGroupWidget/components/index.tsx` on line 543 remove the curry function - 
```js
// change this
onButtonClick = (onClick: string | undefined) => () => {
    this.props.buttonClickHandler(onClick);
  };
```

```js
// to this remove the currying here
onButtonClick = (onClick: string | undefined) => {
    this.props.buttonClickHandler(onClick);
  };
```
Please also check the onClick for menu items after you remove the currying
