### ISSUE TITLE
[Feature]: Option to disable pageLoad action functionality in Edit mode to exit from navigation loop

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a user tries to write a page load query that contains logic to navigate some other page. 
If the logic is not conditional then there is no way for user to again change the logic, as going to that page will just navigate to another page.

This will lead to being stuck in a loop and there is no way other than to export the app, modify the logic and import it, which is not a great experience. 

DEMO given by discord user - https://app.appsmith.com/page-load-loop/page-6244b587ae85b361029c117c 

### Why should this be worked on?

When the user is playing around with page load in editor mode, it is easy to create such an issue and as there is no documented way out user might be stuck here and lose access to those pages if the user is unaware of a workaround to export and resolve the issue.

Discord user request - https://discord.com/channels/725602949748752515/958457101418627172/958770468775682158

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6ezt8)

**Comment by GreenFlux** [comment]
Another user from Discord is facing this issue and is locked out of their app.

**Comment by bharath31** [comment]
Assuming 10% of users firing two ROUTE_CHANGE events with `undefined` navigationMethod within 5 seconds face this issue

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3400 |
| Effort (months)  | 0.5 |

**Comment by bharath31** [comment]
@satbir121 can we think of potential solutions and prioritize this feature?

**Comment by bharath31** [comment]
closing this in favor of #15308
