### ISSUE TITLE
[Bug]-[96]:Error state should be displayed in the Ui when the license key is missing in ee image

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error state should be displayed in the Ui when the license key is missing in ee image

### Steps To Reproduce

1. Run the Appsmith-EE image 
2. The container fails when the license key is not added
3. As of now we have not added the error scenario in the UI
4. The error state is only displayed in the docker logs

### Version

localhost

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12 |
| Effort (months)  | 0.25 |

**Comment by Nikhil-Nandagopal** [comment]
Solving this as part of the new business edition
