### ISSUE TITLE
[Docs]:Update what user sees when Appsmith runs for the first time

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12433]
A user tried to set up Appsmith on Docker, but doesn’t see it running. How many containers should be up and running when executing:
docker-compose up -d ?

https://app.intercom.io/a/apps/y10e7138/inbox/conversation/164629100077560

**Comment by jnikhila** [comment]
@sharat87 - could you please add details to the ticket.

**Comment by sharat87** [comment]
Let's add a note that we expect two container to be running, along with expected output from `docker-compose ps` after starting. Also a screenshot of the welcome page should help people know what to expect when opening Appsmith for the first time.

**Comment by jnikhila** [comment]
@sharat87 - Could you please review the changes on GitBook?

**Comment by sharat87** [comment]
@jnikhila, I think this is merged. If not, can you share a link to the changes that need to be reviewed. Please include a link to the GitBook PR so I know what to review and if it's still waiting for a review. Thanks!

**Comment by Pranay105** [comment]
@sharat87 @jnikhila it is merged.
