### ISSUE TITLE
[Bug]: The save and authorize functionality  is broken in Authenticated API

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The save and authorize functionality  is broken in Authenticated API
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/161037042-9ed7ce83-623d-4fa7-af29-7f3c765b85e4.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/161035885-9931142b-71b2-43b0-b48b-0104bccd95db.png">

### Steps To Reproduce

1. Go to the application 
2. Now navigate to create new datasource tab
3. Click on Authenticated API 
4. Add all the require details
5. Now click on SAve and Authorize button
6. The response error will be displayed

### Version

release

**Comment by prapullac** [comment]
This issue still displays the error in the same format. 
![Screenshot 2022-04-08 at 1 14 32 PM](https://user-images.githubusercontent.com/71753653/162389591-71635d1f-1f74-425b-8db6-092f1898fd96.png)

**Comment by Irongade** [comment]
@prapullac Google sheets authorization does not work in release. This should't be a bug. @nidhi-nair Any thoughts on this?

**Comment by nidhi-nair** [comment]
Google sheets authorization is working for me on release. Could someone please help with a reproduction for this?

**Comment by Irongade** [comment]
@nidhi-nair its working for me as well, I suspect she tested this on her local. @prapullac

**Comment by prapullac** [comment]
Closing the issue as it is working as expected
