### ISSUE TITLE
[Task]: Add `isConfigStoredAtDataSource` field to remote SaaS plugins

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#12432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Edit SaaS manager app to start storing this field
- Ensure this field is editable via cloud services
- Create a doc to figure out which plugin needs to have this property turned on

**Comment by nidhi-nair** [comment]
Related to https://github.com/appsmithorg/appsmith/pull/12251

**Comment by felixsuarez0727** [comment]
Feature added on branch: `feature/add-configStored-at-dataSource` (SaaS App)

For now, it is a checkbox that can be enabled/disabled from the integration form. The default value at the moment is `false`.

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/626405a3-a501-404c-aa43-c6ff4fd6f1ad)

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/ffd048c9-fa88-4c74-9ddc-bca124f182f4)

**Comment by felixsuarez0727** [comment]
As mentioned [here](https://github.com/appsmithorg/appsmith/pull/12251#issuecomment-1084091291) we can meet to clarify, what should the default value be.

**Comment by felixsuarez0727** [comment]
It was decided not to go further with this solution. Changes won't be merged into `master`. No integration on PROD had this property added to it.
