### ISSUE TITLE
[Bug]: derivedColumns property shouldn't appear in the debugger

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#12436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user reported an error when running a query on a custom column in the table widget. The error however does not affect successful execution.
![unknown (5)](https://user-images.githubusercontent.com/32227135/161030354-b5ffcb71-3f8a-4a57-b6f8-55c5ebd51f4a.png)
 

### Steps To Reproduce

Reported by user here - https://discord.com/channels/725602949748752515/760761686549463060/958989208331108362

### Version

Cloud/Self-Hosted -  v1.6.17

**Comment by Nikhil-Nandagopal** [comment]
@danciaclara this seems like a problem related to #11943
