### ISSUE TITLE
[Docs] Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [appsmithorg/appsmith#1245]
## Documentation Link 
Readme.md

## Describe the problem
Missing table of contents in readme.

## Describe the improvement
The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.
A clear and concise description of the improvement.

I would like to work on this

**Comment by bharrod321** [comment]
I'd like to create this.  Anything specific you are looking for with it?

**Comment by ng29** [comment]
> I'd like to create this. Anything specific you are looking for with it?

hey @bharrod321 i have requested @Nikhil-Nandagopal to work on this 👍

**Comment by mohanarpit** [comment]
@ng29 Thank you for opening this issue and giving us a feature idea on how we can improve the README. I've assigned this to the relevant people within the team to improve the structure of the README.

**Comment by ng29** [comment]
> @ng29 Thank you for opening this issue and giving us a feature idea on how we can improve the README. I've assigned this to the relevant people within the team to improve the structure of the README.

Hey @mohanarpit , no worries. i can also pick this up with backtracking to main toc too 👍

**Comment by Nikhil-Nandagopal** [comment]
Closing this as our readme is not very long today
