### ISSUE TITLE
[Bug]: Multiselect Dropdown doesn't close when the label is on the side

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#12458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Multiselect widget displays weirdly in compact mode, i.e when the label is on its side

### Steps To Reproduce

Just drag a Multiselect Widget 

Make it quite Long.
Then add a Label to be on the side of the widget

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/dc5c31b3ac2b4c8c9526a5828e5a63f9-00001.gif)](https://www.loom.com/share/dc5c31b3ac2b4c8c9526a5828e5a63f9)

### Public Sample App

https://release.app.appsmith.com/performance-dashboard-beta/tracking-by-metric-6245d30320d39e42471bf99d

### Version

Cloud

**Comment by btsgh** [comment]
Tested on Release. Works fine. A long Multi-select Dropdown closes fine when there is a label also attached. 
https://www.loom.com/share/755ef58bee324286b28567bbac26ad98
