### ISSUE TITLE
[Bug]: Gsheet authentication fails in the reconnect datasource modal

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The google auth fails when the user tries to authentication the google sheet as a last datasource

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/1bc6143a7e4e47aeaeb3f0c801fa94b3-00001.gif)](https://www.loom.com/share/1bc6143a7e4e47aeaeb3f0c801fa94b3)
### Steps To Reproduce

1. Import the application which as multiple data source along with google sheet
2. authenticate all the datasource now at the last authenticate the google sheet 
3. The user is navigated to the application instead of authenticate  page

### Version

release

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty not critical since it doesn't break a user's app

**Comment by RakshaKShetty** [comment]
reopening the issue can repro in current regression

**Comment by AnaghHegde** [comment]
@haojin111 Can you check this on priority ?

**Comment by haojin111** [comment]
sure, I will
