### ISSUE TITLE
[Bug]: Dependency map causes erratic behaviour of app on page load

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dependency map that's formed during action creations starts causing unexpected behaviour when onPage settings are altered/changed on relevant actions (like queries and JS functions). When any of these queries fail and/or deleted/modified then on page actions start behaving erratic and unpredictable. Having queries/functions that were previously set to run on page load and then refactoring code to run these queries using promises causes issue observed in #12247 

This issue is also related to #12446 

### Steps To Reproduce

1. Go to app at [link](https://release.app.appsmith.com/earworm/home-6219207a0276eb01d22fec5e/edit)
2. Go through authorization flow by clicking on the Spotify logo
3. Observe console log
4. Refresh page and repeat auth flow and observe auth flow

Execution of onPage actions is not consistent and keeps changing on each run. 
[Discussion thread](https://theappsmith.slack.com/archives/C02GAUE9P5H/p1648557161948299?thread_ts=1648553272.780369&cid=C02GAUE9P5H)

### Public Sample App

https://release.app.appsmith.com/earworm/home-6219207a0276eb01d22fec5e/edit

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
this is same as https://github.com/appsmithorg/appsmith/issues/12454
