### ISSUE TITLE
[Bug]: Grouping widgets in a list widget makes text disappear

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#12478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I group 2 or more widgets which are in a list, the text in all widgets in the list go blank

https://user-images.githubusercontent.com/20532920/161190860-504c25bf-fa9b-412e-8aa4-c4283fa26815.mov

### Steps To Reproduce

- Create a list widget
- Add multiple widgets inside the list
- Group them
- The text in the grouped widget disappears, as well as on occasion other text

### Public Sample App

https://app.appsmith.com/untitled-application-15/page1-6246737b4f1a665b23048a35

### Version

Cloud  v1.6.17

**Comment by somangshu** [comment]
@rahulramesha can you tell me if this is related to the widget grouping?

**Comment by somangshu** [comment]
For me something else happened on grouping the widget, they jump out of the list widget. On looking into it further, I found out the the list widget does not work for child container widgets.

@jsartisan @SatishGandham are you aware of why this happens?
