### ISSUE TITLE
[Bug]:  Duplicate name being allowed for JSObject

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#12487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We can have two different JSObjects with same name in the same page. 

### Steps To Reproduce

Create 2 JS Objects and edit the name via the edit option as shown below in the video. 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2974dce9c78d43d2b1e833d42bb7664a-00001.gif)](https://www.loom.com/share/2974dce9c78d43d2b1e833d42bb7664a)

### Public Sample App

https://app.appsmith.com/jsobject-replicate/page1-62468fc597dde1526a12fbcb?branch=master

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Why is this a frontend check? Backend should be rejecting this
