### ISSUE TITLE
[Bug]-[20]:Unable to add comments/leave a blank line at start of JSObjects/JSEditor

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1326" alt="Screenshot 2022-04-01 at 8 06 39 AM" src="https://user-images.githubusercontent.com/91450662/161202875-c80ba7fb-ea50-4c7d-95e6-87804a545a0d.png">

### Steps To Reproduce

1. Create a new JS object
2. Since this JS Object can have multiple functions - add a comment at start with a small description note
3. **Observe : Error is displayed & user is not allowed to add comment as 1st line**
4. Remove the added comment & leave the line blank
5. **Observe: The blank line also causes the issue & code is not read from next line which actually is the start of JS obj**
6. **Expected: Adding a comment or a blank line at start of JS Obj should not cause the actual code to be unread & result in error**

### Version

Prod/Release v1.6.17

**Comment by ramsaptami** [comment]
This was discussed before and IIRC, we stuck to the current format because `export default { }` needs to appear first for the object to be read. We could revisit this if this causes confusion to the larger audience.

**Comment by Nikhil-Nandagopal** [comment]
The format is fine but we should not treat anything outside the export default as a break in the JSEditor. It should still work with spaces, new lines, comments, etc

**Comment by rohan-arthur** [comment]
usage of js object in 6m: 3000
since it is a widespread practice to include explanation comment at the top of the code block, consider 10% of users need this to work, so reach: 300

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 1 |

**Comment by Nikhil-Nandagopal** [comment]
There's a clear error message for it so it's expected
