### ISSUE TITLE
[Bug] Extra padding in URL bar in API creation pane

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1248]
## Description

The URL bar in the API creation pane moves up a pixel when in focus and moves back down when out of focus. See loom video: https://www.loom.com/share/5bf3a435aa70420895411a2ec0677d62

The URL bar shouldn't move.

**Comment by KarenEfereyan** [comment]
@Nikhil-Nandagopal can i please take this instead? You seem to be working on multiple issues? Can i take this up instead? If you don't mind

**Comment by areyabhishek** [comment]
@KarenEfereyan Please do take this up! Thank you. I'll assign this to you. If you need help, please ping us on Discord or email us :)

**Comment by prithviraj-maurya** [comment]
Can I have a look on this

**Comment by Nikhil-Nandagopal** [comment]
Go for it!

**Comment by areyabhishek** [comment]
> Can I have a look on this

@prithviraj-maurya someone else is already working on this. I'd suggest finding a different one.

**Comment by KarenEfereyan** [comment]
> 
> 
> > Can I have a look on this
> 
> @prithviraj-maurya someone else is already working on this. I'd suggest finding a different one.
No @areyabhishek kindly let @prithviraj-maurya take it up

**Comment by Nikhil-Nandagopal** [comment]
@KarenEfereyan I've unassigned this from you. @prithviraj-maurya let me know if you'd still like to work on this

**Comment by jrcamelo** [comment]
I would like to try this. 
I believe the problem lays somewhere around [here](https://github.com/ThakurKarthik/appsmith/blob/release/app/client/src/components/editorComponents/CodeEditor/index.tsx#L109-L215), perhaps happening when the lineWrapping is toggled. 
I will set up my environment so I can test something out, but would you happen to have a clearer idea on how to fix this?

**Comment by hetunandu** [comment]
Good catch @jrcamelo. Definitely something to do with style toggles when an input is focused or blurred. Can you see if it is a border or a margin issue?

**Comment by sumanthyedoti** [comment]
Hi. I like to take it up.

**Comment by areyabhishek** [comment]
@sumanthyedoti welcome to your first issue. I've assigned it to you.
