### ISSUE TITLE
[Bug] Cursor appearing inside dropdown in API creation pane

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1249]
## Description

A text cursor appears in the dropdown to choose the API method. See loom video: https://www.loom.com/share/c445db8fc93e4d1e92e5301c2e2095fb

Screenshot
<img width="123" alt="Screen Shot 2020-10-16 at 9 53 31 PM" src="https://user-images.githubusercontent.com/30255708/96283585-1005fa80-0ffa-11eb-8c58-71c31fde9b1a.png">

**Comment by KarenEfereyan** [comment]
@Nikhil-Nandagopal can I help you? You seem to be working on multiple issues. Which can i help with?

**Comment by areyabhishek** [comment]
@KarenEfereyan Nikhil is one of the lead maintainers of the project, that's why he is assigned to most issues. :) You can work on this too. I'll assign this to you.

**Comment by KarenEfereyan** [comment]
@areyabhishek i'll take this up instead. Unassign me from the other one. Let the other person take it up. @Nikhil-Nandagopal im sorry about yesterday. I had no idea. I'll let you know if i have any blockers

**Comment by mohanarpit** [comment]
@KarenEfereyan We haven't seen any activity on this issue in the last few days. I just wanted to follow up and find out if you're still working on this issue. 

Please don't hesitate to reach out if you are stuck and need any help from the maintainers.

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan We haven't seen any activity on this issue in the last few days. I just wanted to follow up and find out if you're still working on this issue. 
> 
> Please don't hesitate to reach out if you are stuck and need any help from the maintainers.

Yes. Good morning. So sorry i haven't given updates. The truth is im not sure how to tackle the issue. What exactly do i need to do?

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan We haven't seen any activity on this issue in the last few days. I just wanted to follow up and find out if you're still working on this issue. 
> 
> Please don't hesitate to reach out if you are stuck and need any help from the maintainers.

Yes. Good morning. So sorry i haven't given updates. The truth is im not sure how to tackle the issue. What exactly do i need to do?

**Comment by hetunandu** [comment]
Hey @KarenEfereyan 

The file you need to update is the [ApiEditor/Form](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/APIEditor/Form.tsx#L199)

This is using the [BaseDropdown](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/designSystems/appsmith/Dropdown.tsx) component.
We use [react-select](https://react-select.com/home) for this implementation so you will need to check it's documentation. 

As a solution, if it does not exist, expose this setting as a prop in the BaseDropdown that can be toggled via any consumer of this component. If the prop already exists, just passing the right values from the Form must suffice

Let me know if there are any more doubts about this

**Comment by Nikhil-Nandagopal** [comment]
@KarenEfereyan  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by sumanthyedoti** [comment]
I like to work on it

**Comment by riodeuno** [comment]
@sumanthyedoti Thank you for your interest. Assigning this to you. There are details regarding the fix in the discussion above, which can help you with this.

**Comment by sumanthyedoti** [comment]
@hetunandu hi,
I only gave the expected prop `isSearchable={false}` to `DropdownField` in APIEditor/Form. 
One test has failed. Can you please help me in finding what I missed?

**Comment by hetunandu** [comment]
Hey @sumanthyedoti, sorry for this, but we are noticing that that test is a bit flaky and failing for many PRs today. For now, you can ignore that `Widget_loading_spec`
