### ISSUE TITLE
[Bug]: JS object+function pair is not identified when being called by another function

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When one JS function calls another JS function, then the nested function comes up as an error stating 'nestedJSObj.myFun is not a function at parentJSObj'  causing app flow to break

Not sure of exact repro steps to reach this state but sample app with this behaviour is attached below

### Steps To Reproduce

1. Go to app at [this link](https://release.app.appsmith.com/earworm-performance-lag-issue-11284/music-app-issue-11284-6241687ee5732918f59b7d7d/edit/jsObjects/6241687fe5732918f59b7def)
2. Edit `pageLoadActions.authorizeSpotifyUsage` by adding a comment if you can't see the async tag (another issue being tracked under #12243 )
3. Observe console displaying an error ``` SpotifyAuthOperation.authTPP is not a function at authorizeSpotifyUsage ```
4. Navigate on JS objects and observe this function exsits

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/67949cfb39b5464fbf97f599f2253f3d-00001.gif)](https://www.loom.com/share/67949cfb39b5464fbf97f599f2253f3d)

### Public Sample App

https://release.app.appsmith.com/earworm-performance-lag-issue-11284/music-app-issue-11284-6241687ee5732918f59b7d7d/edit/jsObjects/6241687fe5732918f59b7def

### Version

Cloud

**Comment by nidhi-nair** [comment]
@ApekshaBhosale I see that the JSObject does return with the action, do you think the parsing fails at some point and hence fails to add the function to the data tree?

**Comment by ApekshaBhosale** [comment]
@nidhi-nair yes parsing is failing because nestedFunction is not parsed yet, that's why an undefined error has been thrown

**Comment by nidhi-nair** [comment]
Ah I see, so this one would be the issue we solve by introducing the entity reference map or equivalent solution? @ApekshaBhosale
