### ISSUE TITLE
[Bug]: Multiselect options do not show options

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#12517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Multi-select dropdown not rendering options

### Steps To Reproduce

1 . Create google sheets datasource
2. Create a query on it.
3. Choose command fetch many
4. Scroll down to columns and click on it
5. It will not show any options.

### Public Sample App

http://uqi.appsmith.com/projectioncomponentissue/page1-623abe446424322bbfd16bea

### Version

Cloud

**Comment by prapullac** [comment]
UQI related issue
