### ISSUE TITLE
[Feature]: Expose network logs in Cloud

### ISSUE THREAD

**Issue by sullo** [appsmithorg/appsmith#12523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When working on an app in the cloud, not all errors can be seen via the UI. For example, an error reported by an API _will_ appear, however any of the following happen (and probably some more) there is no ability for an Appsmith developer to see what is wrong:

* Networking errors
* Connection failures
* DNS errors
* Any error generated by Appsmith's servers which perform the API request to third parties

### Why should this be worked on?

When using a 3rd party or public API, Appsmith app developers can't access logs on the API side in most cases. Because we have the lack of visibility from the Appsmith side as well, it can be very difficult or impossible to determine why API calls return as failed. 

If the API calls originated from the browser (client side JS), it could be run through a proxy or observed via Dev Tools. However, they are run from Appsmith's cloud.

This makes for a tough situation when debugging.

**Comment by Nikhil-Nandagopal** [comment]
@sullo thanks for the feature request! Do you have a specific API where is this not happening? I think ideally we should propagate error codes that appsmith receives from a 3rd party API back to the browser as well

**Comment by sullo** [comment]
This is specifically with the GitHub API(s). I also use a private API and it doesn't fail very often, but GitHub does a lot.

**Comment by Nikhil-Nandagopal** [comment]
@sullo but the github APIs response is returned to the client. So can you tell me where you're facing this issue?
