### ISSUE TITLE
[Bug]: Docker import fails with file from cloud

### ISSUE THREAD

**Issue by sullo** [appsmithorg/appsmith#12522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After exporting an application from Appsmith cloud, I am unable to load it into a docker installation.

### Steps To Reproduce

1. Download application from an Appsmith Cloud instance. (v1.6.17-SNAPSHOT)
2. Import instance into local Docker installation (v1.6.16)

### Version

1.6.16 Self Hosted

**Comment by Nikhil-Nandagopal** [comment]
@sullo due to migrations in format, we don't support importing into older instances. You must update your self hosted instance to the latest version for this to work

**Comment by sullo** [comment]
At that moment, my local instance was fully updated to the latest version. So I assume cloud was ahead?

**Comment by Nikhil-Nandagopal** [comment]
@sullo yes that is quite possible. We're trying to reduce the lag between self hosted and cloud
