### ISSUE TITLE
[Bug]: Cyclic dependency error with JS on slave table button

### ISSUE THREAD

**Issue by arminus** [appsmithorg/appsmith#12528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the current release branch from github (this effect cannot be reproduced with 1.6.16 and is IMHO clearly a regression)

Barebones extract from my actual app:

- a master (Table1) and a slave table (Table2), content of the slave table is updated based on Table1.selectedRow.id
- second table has a column with a button which reads Table2.selectedRow.<column> on click via a JS function (set to not run on page load)
```
export default {
	cyclic: () => {
		storeValue("commentText", Table2.selectedRow.text)
	}
}
```
-> this invariable leads to a cyclic dependency error 
```
Cyclic dependency found while evaluating. Node was: Table2.primaryColumns.customColumn1
```

https://user-images.githubusercontent.com/683680/161384875-3d1d374c-cc9f-433c-ab95-3f84bf5a38a1.mp4

Note that this has nothing to do with JS editing, the error first appeared when I imported the application JSON from 1.6.16.

**This is a blocker for upgrading to > 1.6.16 for my actual application**

### Steps To Reproduce

See attached clip

If the JS function only accesses Table2.selectedRowIndex the error cannot be reproduced

I've seen other bug reports for cyclic dependency errors, maybe this repro help to iron out the problems...

### Version

SelfHosted / Release branch

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur  I bumped the priority since the user mentioned that it is breaking their existing app

**Comment by ohansFavour** [comment]
@arminus, while we work on this, a workaround is this.

1. Change `cyclic function` to 

 cyclic: (text) =>{
 storeValue("commentText", text)
 }
 
 
2.  Change `Table2.onclick` to

{{ JSObject1.cyclic(Table2.selectedRow.text)}}

**Comment by Rishabh-Rathod** [comment]
@ohansFavour with RCA can you please also add rough estimate here.

**Comment by arminus** [comment]
Thank you, I confirm that my main app works again without the workaround (git release branch)
