### ISSUE TITLE
[Bug]: Unable to delete DataSource when mapped Query is run via JS

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/161474369-741404cc-7400-40c9-9ce2-4479ad0ee7e5.mov

### Steps To Reproduce

1. Create a data source, Postgres used in example
2. Create a query to select data from table
3. Run this query via a JSObj
4. DragDrop widgets & map the JSObj & query to them
5. Now, Delete query - Query deleted successfully
6. Now try to delete Data source - toast 'cannot delete since 1 action using it' appears
7. Next delete the JSoBj - JSObj deleted successfully
8. Again try to delete Data source - again toast 'cannot delete since 1 action using it' appears
9. Try deleting the mapped widgets also [ideally should not be required] - just for confirmation
10. **Observer - toast 'cannot delete since 1 action using it' keeps appearing - when tried to delete this Data source**
11. Navigate to a different new application & delete the old application & then try to delete the data source from new application & then deletion of data source is successful
12. **Expected: Once query is deleted, Data source should allowed to be deleted**

### Version

Cloud/Release v1.6.17

**Comment by Nikhil-Nandagopal** [comment]
@Aishwarya-U-R this issue is already reported in #10358 and not critical since it does not break a users existing app
