### ISSUE TITLE
[Bug]-[1200]:Unable to select previously selected option from dropdown if value outside the options is set - unless other option is selected at-least once

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/161390275-d6d4bed2-a643-4fdd-820f-d124a9668642.mov

### Steps To Reproduce

1. Drag drop a select widget - set some options for the dropdown
2. Map the Default value of the select to take values outside of existing options, example used - Table.selectedRow.step 
3. Now select step#1 from table - observe Select also reflects the value
4. **Now select step#3 from table -  observe Select also reflects the value (not one of the available select option)**
5. Now from select, try to change dropdown & select # 1 - one of the option value present
6. Observe User is unable to select # 1 unless # 2 selected
7. **Expected - All of Select option values should be available for selection anytime**

### Public Sample App

https://release.app.appsmith.com/applications/62486d45ab307a026918639e/pages/62486d45ab307a02691863a7

### Version

Prod/Release v1.6.17

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 0.5 |

**Comment by Tooluloope** [comment]
@dilippitchika to fix this we would need to fix this strict check of defaultValue and loose check when serverside filtering is Enabled

**Comment by dilippitchika** [comment]
@Tooluloope i don't understand what exactly is happening here. I get the part around strict and loose check, but the part i need help grasping is - Why is the change not working? Default value should always be discarded once a user interacts with this widget and selects a value right? What is preventing that here?

**Comment by chandannkumar** [comment]
@Tooluloope This issue still exists. Reopening this issue

https://www.loom.com/share/22aa0c311a2644bfaed092929301ac56

**Comment by dilippitchika** [comment]
@somangshu why is this moved to needs prd, it's a bug right? Is there something which we need a prd for here?

**Comment by somangshu** [comment]
The issue got reopened, I believe its going against some initial requirement hence wanted you to confirm once. 
We removed it from the sprint for the same reason, @Tooluloope was not sure how to proceed here

**Comment by dilippitchika** [comment]
Ok, i will work on it

**Comment by dilippitchika** [comment]
Ok i am not sure, what this goes against in our scenario since if server side filtering is disabled we won't be showing default values which are not part of table. Will wait for @Tooluloope to come back.

**Comment by rahulbarwal** [comment]
This issue is resolved and we are unable to reproduce. please reopen if you see this again.
