### ISSUE TITLE
[Bug]: Unexpected removal of recently created DataSource from EntityExplorer DATASOURCES section when Query [run via JS] is deleted

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/161404668-d9a09198-1776-4c84-8165-0b43e5e22f2e.mov

### Steps To Reproduce

1. Create a Data Source, example used - Postgres DB
2. Run a query via JS against this DataSource
3. Map query results, JS method call to widgets, as shown
4. Deploy the app, verify & navigate back to edit page
5. Expand Queries & Expand Datasources sections
6. Observe: New Data source is displayed at top root of DATASOURCES section as expected
7. Now delete the query
8. **Observe : Datasource is also removed from DATASOURCES section**
9. **Expected: User deleting query might also want to the Delete the DataSource from EntityExplorer, hence it should not be removed**

### Version

Cloud/Release v1.6.17

**Comment by kocharrahul7** [comment]
should be closed with https://github.com/appsmithorg/appsmith/issues/13485

**Comment by Aishwarya-U-R** [comment]
Still able to repro this issue, reopening.
