### ISSUE TITLE
[Bug]-[4]:JSON Form (Select field) `onFilterUpdate` property shows two different variations of same code block

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2022-04-04 at 12 53 44 PM](https://user-images.githubusercontent.com/13262095/161499199-0f9c6edc-97d1-4975-a052-39026887aac8.png)
![Screenshot 2022-04-04 at 12 53 36 PM](https://user-images.githubusercontent.com/13262095/161499215-afa02849-56b9-49fa-8fa4-736c8a163759.png)

### Steps To Reproduce

1. Create JSON form add select field
2. Populate `onFilterUpdate` check and uncheck `JS` toggle.

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1 |
| Effort (months)  | 0.5 |
