### ISSUE TITLE
[Template]: 6 month employee feedback

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#12552]
### Title

6 month employee feedback

### Objective

The bi-yearly feedback that every employee in an organization looks out for from other employees is the use case for this app.

The app consists of the following 3 pages:

1. Custom form builder: This page allows the user to enter the fields that they desire for in their form.
    
    The form builder would be a list, wherein the user enters the question and the form gets constructed on the next page accordingly. The form would also contain a few fields already which could be removed by the user, if not needed. The existing fields in the form builder would be:
    
    - First and Last name (text input)
    - Pod name (dropdown)
    - How long have you known me for (approximately)? X Months (number input)
    - Overall rating (rating)
    - Things I have been doing well? (text input)
    - Things that I can improve on?(text input)
    - Things that I should be doing, but not doing?(text input)
    - Any other suggestions/feedback?(text input)
    - LinkedIn recommendation(text input)
    
    The form builder should allow the user to enter the field that they would like to have in the form and the answer fields could be either a rating input, a text field or a number input.
    
2. Answering the form: This page allows the user to share the form with other employees where they can answer the form that the user built from the last page.
    
    The recommendation section would call the LinkedIn API which would allow the employee to write a recommendation for the user (optional field).
    
3. Feedbacks at a glance: On this page, every employee can see the aggregate rating for every other employee.
    
    On clicking their own name, they can see all the feedback that they have received along with the button to post the recommendation on their LinkedIn profile or not. A few charts (and a feedback word cloud) could also be displayed to help understand the feedbacks more efficiently.

### Wireframes

https://www.figma.com/file/jt3nkpptBTCwKamcyXLeR7/6-month-feedback-wireframes?node-id=0%3A1

### Validation criteria

- User should be able to make a custom form
- User should be able to check the form responses
- User should be able to submit recommendation

### Use case

Human Resources (HR)

### Industry

Other

### Data sources

PostgreSQL

**Comment by kocharrahul7** [comment]
https://app.appsmith.com/templates/629f5363e8e73110ce2518af
