### ISSUE TITLE
[Docs]: Update Tutorial Review Moderator Dashboard

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12550]
Update Doc:

https://docs.appsmith.com/tutorials/review-moderator-dashboard

![Java Instructions](https://images.zenhubusercontent.com/6203759d49a2167250e9a805/1d14feee-b196-4b9e-bcf1-046f31735a0a)

**Comment by Pranay105** [comment]
Some observations while fixing the tutorial - 
1. There are grammatical errors that have been fixed.
2. The visuals are outdated and need to be replaced.
3. After reading through the tutorial, our product has changed a lot compared to when this tutorial was written. We need to take that into account and make changes. Some examples - 
 - When you create a new app, the landing page comes with 2 options - Build with Drag and Drop or Connect to a Data source. We have to mention this in the tutorial.
 - When you want to test your query, you have to click on the run button. Currently, we are showing it as "test" button in the tutorial.
 - We have to mention the option to connect a widget to a query from the query window itself.

**Comment by Rishabhkaul** [comment]
@Pranay105 Can this be closed?

**Comment by jnikhila** [comment]
@Rishabhkaul - This is in the 'Needs Video' pipeline. A new video is needed as the existing one is outdated. @cokoghenun - Could you please confirm?

**Comment by cokoghenun** [comment]
@jnikhila it seems the original video was created by the docs team. Can we get someone from the team to re-record it?

**Comment by jnikhila** [comment]
@harshilp24 - please take a look.

**Comment by harshilp24** [comment]
I think the videos are up to date. cc: @jnikhila
