### ISSUE TITLE
[Enhancement]: Automatically select an authentication option for SaaS Integrations datasource creation.

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#12565]
Each SaaS Integration could have several types of authentication, by default the first option of the authentications should be selected. 

Nidhi suggests that we use the `initialValue` property to automatically show the first value out of the array of entries in the datasource configuration. This can be applicable even to cases where we have multiple auth types.

This is an example of the current behavior

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/52ac6201-96ee-4f03-9d2b-4a840c5f1a6c)

This is an example of the desired behavior

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/36ce2455-9c68-43d3-9691-faf271dcb766)

**Comment by felixsuarez0727** [comment]
Assesment shows that this is Front End related.

**Comment by felixsuarez0727** [comment]
Aman said that property `inicitalValue` should be present in parallel to the properties `label`, `description`, `controlType`, `configProperty`. But the issue [#13833](https://github.com/appsmithorg/appsmith/issues/13833) not allow to continue with this issue.

What we can do it create an initialValue for the plugin and confirm that it is coming when we open datasource form for twilio on any application, until they close the other issue we will be working on this.

**Comment by felixsuarez0727** [comment]
No updates on [#13833 ](https://github.com/appsmithorg/appsmith/issues/13833)

**Comment by rohan-arthur** [comment]
not our focus for the foreseeable future, will get around to this at a later time.
