### ISSUE TITLE
[Bug]: Linting error in List widget when using storeValue

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#12561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using storeValue with `currentIndex` in Listwidget is giving linting error.

### Steps To Reproduce

1. Drop List widget
2. On the image in list widget, bind onClick to `{{ storeValue('a',currentIndex)}}`. Make sure there is no space between comma and `currentIndex`.
3. Refresh the page and check the property pane for the same image widget. 
4. Notice the linting error

### Version

1.6.17

**Comment by somangshu** [comment]
not seeing any errors with the above steps right now

cc @jsartisan can you share what the error is?
