### ISSUE TITLE
[Bug]: Dropdown popover in the property pane needs a max height after which content scrolls

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#12572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Today all the dropdowns used in the property pane don't have a max height property. This hides data when the screen is a bit small and the user doesn't know that more data exists.

### Steps To Reproduce

1. Add a JSON form widget or a datepicker widget
2. Click on the JSON form -> Field type or datepicker -> date format
3. Observe the number of items visible without scroll in the popover
![image](https://user-images.githubusercontent.com/19730984/161679594-c6be01b4-5a54-4538-a790-db6c1a344492.png)

### Version

Production

**Comment by vasanth-appsmith** [comment]
@aswathkk I have updated the designs for this. Please check and let me know if you have any doubts. [Figma](https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=4660%3A106036)

**Comment by btsgh** [comment]
Tested this on Release - on all widgets with properties that have scroll option to scroll through the items. Works fine,.
