### ISSUE TITLE
[Bug]: Inconsistent Behavior When Launching Empty Duplicated App

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#12570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating an empty app, then duplicating it, the two (2) apps have different behavior when launched.
When launching the original app, it displays this screen:
![image](https://user-images.githubusercontent.com/101268423/161636868-a96511ad-cc5b-4ae9-bf5e-66abbd7dcdbe.png)

When launching the duplicated app, it displays this screen with Resource not found error:
![image](https://user-images.githubusercontent.com/101268423/161636932-0f5f2b26-797b-4637-8557-1f5d383b9196.png)
 

### Steps To Reproduce

1. Create a new app and rename it as desired.
2. Duplicate the app.
3. Launch the original app.
4. Launch the duplicated app.
5. Notice the difference in behavior.

### Version

Cloud  v1.6.17-SNAPSHOT

**Comment by riteshkew** [comment]
not reproducible in v1.18
