### ISSUE TITLE
[Bug]: Changing MongoDB URI makes the container fail to start

### ISSUE THREAD

**Issue by praveenkumarKajla** [appsmithorg/appsmith#12587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i update mongodb uri to custom one rather than localhost this happens (AWS AMI)

```
Checking environment configuration
Checking APPSMITH_MONGODB_URI
Checking initialized database
Checking Replica Set of external MongoDB
Mongodb cloud Replica Set is enabled
MongoDB shell version v4.4.13
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:374:17
```

### Steps To Reproduce

1. Update mongodb uri in docker.env or from admin settings
2. restart using docker restart appsmith

### Version

Self Hosted AWS AMI v1.3

**Comment by sharat87** [comment]
@praveenkumarKajla, can you try wrapping the value of your `APPSMITH_MONGODB_URI` in single quotes? Like this:

```sh
APPSMITH_MONGODB_URI='mongodb://host/db...'
```

This should fix your problem. Let us know how it turns out. Thanks!
