### ISSUE TITLE
[Task]: RCA unnecessary re-rendering of AppViewerPageContainer

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Issue reported by @SatishGandham 

### SubTasks

<img width="1920" alt="Screenshot 2022-04-05 at 12 57 38 PM" src="https://user-images.githubusercontent.com/23132741/161704539-f39fabf0-b657-486c-825e-3f29079411e0.png">

**Comment by Rishabh-Rathod** [comment]
## RCA

As we subscribe to evaluated values and DSL in `AppViewerPageConatiner`, it is tend to re-render. 

Solution -
Inside `getCanvasWidgetDsl`, we should remove evaluated values for now and also aim to even separate out styles of widgets and subscribe each widgets to only relevant values.

**Comment by Rishabh-Rathod** [comment]
Scope of this issue is changed from focusing on `AppViewerPageContainer`  to widgets rendering improvement. 

Hence, estimate needs to be updated accordingly.

Shall i create a separate issue for `widgets rendering` and close this issue as RCA task done ?
@somangshu

**Comment by somangshu** [comment]
yes, that works, Please do post the RCA as well here

**Comment by Rishabh-Rathod** [comment]
## RCA [DRAFT]

### Cause:
In the `AppViewerPageConatiner` component, we subscribe to all the widgets. 
Even if a single property in one of the widgets changes, `AppViewerPageConatiner` subscribing to all the widgets rerenders. Individual components themselves don't re-render because of the should component update implemented in the base widget.

### Solution:
Make each widget subscribe to its own data instead of `AppViewerPageConatiner` passing it down.

#### Estimated Improvement: 

#### How it was estimated: Performance profile on A-force application
