### ISSUE TITLE
[Docs] MYSQL Documentation is missing in appsmith

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1259]
## Describe the problem
We have documentation on how to query postgres and mongodb but no documentation on MYSQL.

## Describe the improvement
We should create a document for Querying MYSQL that is very similar to postgres

**Comment by KarenEfereyan** [comment]
@Nikhil-Nandagopal please assign this one to me. I'm particularly good at writing. Are there any resources to gather information from though?

**Comment by yash2189** [comment]
I could work on this @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@KarenEfereyan you can have a look at our existing docs for postgres
https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-postgres
And our contribution guide
https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/CONTRIBUTING.md

**Comment by Nikhil-Nandagopal** [comment]
@yash2189 since Someone has already claimed this I suggest you go through our many open good first issues

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan you can have a look at our existing docs for postgres
> https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-postgres
> And our contribution guide
> https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/CONTRIBUTING.md

I'll be sure to

**Comment by KarenEfereyan** [comment]
@Nikhil-Nandagopal the asset upload file is empty as can be seen here, https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/asset-upload.md. In the project tree structure in Vscode, I queried for the asset-upload.md file and it doesn't seem to be there. Can you please look into it?

**Comment by Nikhil-Nandagopal** [comment]
@KarenEfereyan this seems to be the right file
https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/UploadingAssets.md
Where did you find the previous link?

**Comment by KarenEfereyan** [comment]
> @KarenEfereyan this seems to be the right file
> https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/UploadingAssets.md
> Where did you find the previous link?

On the main contributing.MD file

**Comment by Nikhil-Nandagopal** [comment]
@KarenEfereyan  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by yash2189** [comment]
Hi @Nikhil-Nandagopal I would like to work on this as you mentioned that issues anytime if they're available to work on :)

**Comment by mohanarpit** [comment]
@yash2189 Go for it! 🚀

**Comment by mohanarpit** [comment]
@yash2189 Since I haven't seen a PR opened for this issue, I'm unassigning you right now. I understand that something else might have come up. Feel free to contribute to Appsmith again by picking up any other issue.

**Comment by yash2189** [comment]
@mohanarpit Sorry I had started working on this but wasn't able to complete. Would it be fine if I raise the PR till today evening?

**Comment by mohanarpit** [comment]
Sure. Once you open a PR for this issue, it'll get assigned back to you. Thanks!

**Comment by yash2189** [comment]
Thanks @mohanarpit I'll start working on the same
