### ISSUE TITLE
[Bug]To implement Mongo Unit Test for issue 10114 - Docker image issue

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#12591]
Running Maven test end up in a issue of Can't get Docker image.
No code issue was identified, the missing images were pulled still the same issue exists in  development environment.
Need to write unit Test for below issue 
https://github.com/appsmithorg/appsmith/issues/10114

**Comment by sumitsum** [comment]
Closing since we are now using the same PR to push the fix and the TC.
