### ISSUE TITLE
[Docs]: How to deploy Appsmith on Google Cloud run 

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12598]
A writeup to be added under setup Appsmith for Google Cloud Run.

Link to [Community](https://community.appsmith.com/t/serverless-stateless-deploy-google-cloud-run/788/3)

**Comment by jnikhila** [comment]
@sharat87 - Could you please spare time to take this ahead and add some pointers so that we can progress on documentation?

**Comment by Rishabhkaul** [comment]
@jnikhila Are we still doing this?

**Comment by jnikhila** [comment]
@Rishabhkaul - This doc request was raised as part of a user request. We are still awaiting information from the devops team. @pranavkanade, @sharat87 - Could you please confirm if this is needed and please provide a first draft so that the doc team can work on this?

**Comment by yan-hic** [comment]
Seems stalled. So appsmith on cloud run is not supported ?

**Comment by danciaclara** [comment]
@pratapaprasanna you can share the first draft here

**Comment by danciaclara** [comment]
Draft - https://www.notion.so/appsmith/Deploy-appsmith-on-Cloudrun-412e3caaae054dee80de991941f487e7?pvs=4
