### ISSUE TITLE
[Bug]: When an action was delete, it doesn't delete the options actions automatically

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#12602]
In AppSmith Test, an "Update Object" option is displayed, but this actions does not exist, so they have to remove manually

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/632cd736-d8bc-4e03-926d-3219038a36a5)

Need find a way to remove it automatically

**Comment by felixsuarez0727** [comment]
A query was create to solve this problem automatically

**Comment by felixsuarez0727** [comment]
A query was create to solve this problem. The options remove automatically

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/94a81cdd-0590-40ef-853e-b71f0400f701)

**Comment by felixsuarez0727** [comment]
Changes have been made to `master`. Ready for QA.

The steps to test this are:

1. On the SaaS Integration, use a Test App.
2. On the test App create a 2 Test Commands.
3. Install the Integration into a Test Organization.
4. Confirm that you can create a DataSource.
5. Confirm that your Test Command is on the Dropdown.
6. Go back to the SaaS App and Delete one of the Test Actions.
7. Proceed to Install the Integration again on the same Organization.
8. Go to the organization, create another DataSource.
9. You will see that the Command that you deleted no longer appears on the dropdown, this is the expected behavior. (The bug is that the option on the select widget doesn't get removed).

**Comment by felixsuarez0727** [comment]
Here is a test/demo of the desired behavior:

https://images.zenhubusercontent.com/275993885/9e3e7759-3d59-47af-a816-81c4cc9b7f31/options_not_deleted_test.mp4

**Comment by yatinappsmith** [comment]
- [ ] [[Test case] : [Bug]: When an action was delete, it doesn't delete the options actions automatically](https://github.com/appsmithorg/TestSmith/issues/1942#)

**Comment by yatinappsmith** [comment]
verified on saas manager
