### ISSUE TITLE
[Bug]: Git import modal shows the wrong text

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#12603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="535" alt="Screenshot 2022-04-05 at 9 29 40 PM" src="https://user-images.githubusercontent.com/80334441/161796690-0d9f7246-14e1-443d-ab44-0b7446b150b0.png">

It says "Create an empty git repository and paste the remote URL here."  Although for git import we are using repository which already has commits for the app.

### Steps To Reproduce

1. Click on NEW.
2. Click on import
3. Click on Import from github repo
4. Git import modal will open

### Version

Release

**Comment by bolshoytoster** [comment]
@Parthvi12 if it just need to be changed to something like 'Paste the remote url here:' I could open a PR now.

**Comment by Parthvi12** [comment]
@bolshoytoster Hey, thanks. Please go ahead :)

**Comment by IAmAnubhavSaini** [comment]
This has been fixed.

![Screenshot 2022-07-07 at 6 53 00 PM](https://user-images.githubusercontent.com/1573771/177784222-e48e9d3c-93b5-4398-958c-66351ed0ac5d.png)
