### ISSUE TITLE
[Feature]: Datalist as in html

### ISSUE THREAD

**Issue by Somashekar-B** [appsmithorg/appsmith#12616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Please add a feature like Datalist tag in html..
that is it provides auto suggestions for the normal input field

Reference
[https://www.w3schools.com/tags/tag_datalist.asp](url)

### Why should this be worked on?

This is most required feature to make a better user experience application by making the form filling or entering details in a easy way

**Comment by Nikhil-Nandagopal** [comment]
@Somashekar-B thanks for the feature request. We have this widget tracked here #6928
