### ISSUE TITLE
[Bug]: JSONForm select field does not open when used in an nested field (Array/Object)

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#12625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The select field menu does not open when it is added to an Array Item/Array of Object/Object or any nested structure.

### Steps To Reproduce

1. Add a JSON Form
2. Add a new custom field
3. Change the type to Object
4. Add a new field under that object
5. Change the newly added field type to select
6. Try clicking the select field on the form, the menu won't open.

### Version

Cloud

**Comment by somangshu** [comment]
Godspeed @ashit-rath 🤗 💟
