### ISSUE TITLE
[Bug]: UI overflow when organization name is long

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When organization name is too long and when user shares the app the modal that appears has overlapping of ellipsis and x icon

![image](https://user-images.githubusercontent.com/92293815/161974269-cbd79e3d-2f5a-4373-bc0f-cf6a0387c3f0.png)

### Steps To Reproduce

1. In release create a new organization with very long name
2.  Click on share and observe the modal

### Version

Cloud

**Comment by ankitakinger** [comment]
This is fixed. Closing the issue.
