### ISSUE TITLE
[Bug]: On trying to copy a grouped smaller widgets the size of the widget increases each time when the widgets are grouped and pasted 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#12624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is observed for all the smaller widgets - when the widget is copied and pasted on the canvas and upon grouping the original and copied widget and pasting again on the canvas the widget size increases each time when the same process is repeated. Refer video below

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0b7027bdc288483c8b0bdd43331435eb-00001.gif)](https://www.loom.com/share/0b7027bdc288483c8b0bdd43331435eb)

### Steps To Reproduce

1.Launch the Appsmith app in release/Production 
2.Drag and drop any smaller widget - Ex button widget 
3.Copy the button widget and paste it on the canvas
4.Group the original and copied widget 
5. Paste the copied widget again on the canvas
6. Now again group the already grouped widget with the newly copied widget 
7. Paste the copied widget again on the canvas and observe the widget size is increased compared to the original widget size 

### Version

cloud

**Comment by dilippitchika** [comment]
@YogeshJayaseelan this is intended because today we use a container to group items. What is happening everytime you group this way is that you are adding new containers, so container 2 contains container 1 + new button. Hence the size difference.
