### ISSUE TITLE
[Bug]-[50]:Table Filter - Removing where clause does not rightly update the input text value but filtered result is fine

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/162014415-d2238737-a184-4563-9c91-d46dd5ad2904.mov

### Steps To Reproduce

1. Drag drop table with some table data
2. Filter table with some input text
3. Add one more filter with different input text
4. Remove 1st filter added
5. **Observe : Where clause input text is now not updated rightly**
6. **Expected:  Where clause input text should show respective filter value**

### Version

Cloud/Release v1.6.17

**Comment by dilippitchika** [comment]
Great catch @Aishwarya-U-R 🏅 , we wouldn't have caught it. Probably there are some other items here which are undetected.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.5 |

**Comment by souma-ghosh** [comment]
Fixed in PR
https://github.com/appsmithorg/appsmith/pull/16904
