### ISSUE TITLE
[Bug]: Insert query fails in mysql crud pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Insert query fails in mysql crud pages
![image](https://user-images.githubusercontent.com/45958978/161977680-45b542f9-ef34-4167-81e9-4679aae3fc25.png)

### Steps To Reproduce

1. Generate a My sql crud page
2. Now click on insert button
3. Add  data in the input fields
4. click on submit button
5. There is not action performed and the queries fails 

### Version

release

**Comment by Rishabh-Rathod** [comment]
This doesn’t seem to be related to frontend hence unassigning myself.

**Comment by abhvsn** [comment]
@Nikhil-Nandagopal have we made updates in the CRUD page template? I'm seeing the JSON form widget is used in the update and insert form. This is causing the issues as queries are updating the fields partially or failing completely. Can we please revert that change for now as backend will also need some change in how the replacement logic is handled in the queries.

**Comment by Nikhil-Nandagopal** [comment]
Reverted the changes so this should be working when it's deployed in 30 mins

**Comment by RakshaKShetty** [comment]
the issue is resolved now
