### ISSUE TITLE
[Bug]: POSTGRES CRUD : Table does not get populated 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#12636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user tries to create a CRUD page it is observed that data does not get populated 

### Steps To Reproduce

1) Click on Postgres data source 
2) Click on generate page 
3) Ensure to add table content 
![Screenshot 2022-04-06 at 7 56 05 PM](https://user-images.githubusercontent.com/71753653/161999828-bc4baaeb-0af9-4b68-a04e-2616481f0d3e.png)

### Version

Release

**Comment by akash-codemonk** [comment]
Seems like an issue with the Table Widget or an evaluation issue. Going to the query page and returning back to the canvas, the data is visible in the table widget.

**Comment by dilippitchika** [comment]
@akash-codemonk @prapullac  unable to reproduce with the users postgres DB. Can you please share the app json with the data source for us to test?

**Comment by akash-codemonk** [comment]
It works fine when you open an app with the generated page. It also works once you switch to some other view. 

Steps to repro on release.
- Create an app
- Generate a page from the users mock postgres datasource.

https://user-images.githubusercontent.com/67054171/162130636-a6864db4-2560-48c5-8d2a-482fb5a6b2a5.mov

**Comment by Nikhil-Nandagopal** [comment]
Reverted the changes so this should be working when it's deployed in 30 mins

**Comment by prapullac** [comment]
After the changes have been reverted the issues seem to be resolved

**Comment by prapullac** [comment]
After the changes have been reverted the issues seem to be resolved
