### ISSUE TITLE
[Bug]: The update query seems to be broken in mysql crud

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The update query seems to be broken in mysql crud
 query for reference:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/161982794-f6b672b0-4f73-49bd-90af-ff5dee31cbbd.png">

### Steps To Reproduce

1. Generate a My sql crud page
2. Now click on insert button
3. Add data in the update input fields
4. click on submit button
5. Few of the Columns are not updated as in the above screenshot

### Version

release

**Comment by RakshaKShetty** [comment]
@Nikhil-Nandagopal  reopening the issue facing the same issue 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/162131972-5bad801e-9607-41ba-8cb0-7f310a662a28.png">

**Comment by Nikhil-Nandagopal** [comment]
Reverted the changes so this should be working when it's deployed in 30 mins

**Comment by RakshaKShetty** [comment]
The issue is resolved now
