### ISSUE TITLE
[Feature]: Hugging Face Inference API Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#12631]
Docs: https://huggingface.co/inference-api

**Comment by felixsuarez0727** [comment]
As of now, tree actions have been added.

**Comment by felixsuarez0727** [comment]
As of now, I have added eight actions.

**Comment by felixsuarez0727** [comment]
![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/3823ae15-4dd5-4bff-bd67-47f449dc8ab7)

**Comment by felixsuarez0727** [comment]
A minor sample app is also ready:

https://app.appsmith.com/app/test-hugging-face/page1-6258fbf50d3d384069c11017

**Comment by felixsuarez0727** [comment]
Moving to QA since the integration and the sample app is ready.

**Comment by btsgh** [comment]
Testcases are available here - 
1.[ Basic Testcase](https://github.com/appsmithorg/TestSmith/issues/1881)
2. [Bert-base-uncased-hateexplain](https://github.com/appsmithorg/TestSmith/issues/1882)
3. [Classificacion-texto-suicida-finetuned-amazon-review](https://github.com/appsmithorg/TestSmith/issues/1883)

**Comment by btsgh** [comment]
Issues found so far - 
1.  In Bert-base-uncased-hateexplain - testcase point 2 fails as text is spelt incorrectly ![Bertbaseuncasedhateexplain.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/5234589d-cfca-4de0-96f8-a7bbb46b44ba)
This issue occurs across all the commands
2. Testcase point 3 - FAILS CURRENTLY - it runs even though the field is blank. It should give an appropriate message that required field is missing. This issue occurs across all the commands
3. Testcase point 6 - FAILS sometimes - an error pops up![bertbase error.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/b7a838b9-bf1a-4763-88c4-d7f86d93abdc). 
4. In the "Classificacion-texto-suicida-finetuned-amazon-review" command, testcase point 4 - FAILS CURRENTLY - it gives an output exactly the reverse of the expected output.
5. Testcase5  enter an english text equivalent  - (FAILS CURRENTLY - it gives an output exactly the reverse of the above)
6.

**Comment by felixsuarez0727** [comment]
Hugging Face Observations

 | #|Question/Observation | Related Issue | Resolved |
|---| ---                                | ---         | ---              |
|1| In Bert-base-uncased-hateexplain - testcase point 2 fails as text is spelt incorrectly  | - | No |
|2| It runs even though the field is blank. It should give an appropriate message that required field is missing.  |  -   |No|
|3| FAILS sometimes - an error pops up | - | No |
|4| It gives an output exactly the reverse of the expected output. |-| No|
|5| FAILS CURRENTLY - is English supported? | - | No |
|6| Gives an exact opposite response | - | No |
|7| Currently gives a slightly different response number  | - | No |
|8| Gives an exact opposite response  | - | No |
|9| Output is different  | - | No |
|10|Response is not the same as seen in the comparison URL.  | - | No |
|11| Gives an exact opposite response | - | No |
|12| Fails as the response we get | - | No |
|13| The response received on our interface is different  | - | No |
|14| Currently fails. Neutral shows the largest value. | - | No |
|15| Currently fails. Joy shows the largest value. | - | No |
|16| Currently fails. Neutral shows the largest value. | - | No |
|17| Does not give the same response as seen in the above url | - | No |





Updates about observations

1. We are going to change this in all the commands


**Note**: For the other test we need to do more research on the problem

**Comment by rohan-arthur** [comment]
@felixsuarez0727 can we move this to icebox since we are not actively working on it?
