### ISSUE TITLE
[Bug]-[300]:Table Filter - Reverts to previous Operator upon removing a Filter condition

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/162090664-fdf49ef2-7a4f-4ca7-a616-db6838ec560c.mov

### Steps To Reproduce

1. Drag drop table with some table data
2. Filter table with multiple conditions with one operator, verify results
3. Now change the operator to another, verify results
4. Remove one of the filter condition applied
5. **Observer - Operator is reverted to previous operator**
6. **Expected - Operator & other conditions should remain intact until user changes it & not revert on a different action, here - deletion of a where clause**

### Version

Cloud/Release v1.6.17

**Comment by dilippitchika** [comment]
Can we debug why this is happening, this will impact server side filtering feature #10486

**Comment by dilippitchika** [comment]
@Tooluloope please triage this and let us know the next steps when you are picking up #10486

**Comment by Tooluloope** [comment]
@Aishwarya-U-R @dilippitchika  what's the expected behavior, 
Should the filter not update till when the user clicks Apply?

**Comment by Aishwarya-U-R** [comment]
@Tooluloope  - **Expected - Operator & other conditions should remain intact until user changes it & not revert on a different action, here - deletion of a where clause** - as given in description above!
