### ISSUE TITLE
[Bug]: Auto-suggestion is not working for progress widget while binding

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#12647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observation 1: Auto-suggestion is not coming while binding
Observation 2: Now `Progress1.progress` is not functional. It has been changed to `Progress1.value`

https://watch.screencastify.com/v/MrAi0zeMMqfoMyj42Coo

### Steps To Reproduce

1. Drag and drop a Progress widget
2. Drag and drop a text widget
3. Try to bind the Progress widget with text widget
4. Observe that auto suggestion is not displayed

Observation 2:

### Version

release

**Comment by yatinappsmith** [comment]
Removing QA label as verified label was added
