### ISSUE TITLE
[Bug]: Progress widget with circular type is showing wrong value 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#12649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Uploading Screenshot 2022-04-07 at 11.09.37 AM.png…]()

### Steps To Reproduce

1. Drag and drop a Progress widget
2. Change the type to Circular
3. Change the progress to 55
4. Observe that value displayed in 5.000000000001
5. It is observed only for some values [55-58]

### Version

release/cloud

**Comment by somangshu** [comment]
@vivekverma2312 please re-upload the attachment here

**Comment by yaldram** [comment]
Please round the value - ` {`${Math.round((progress / MAX_VALUE) * 100)}%`}` check -appsmith/app/client/src/widgets/CircularProgressWidget/component/index.tsx Line 112

**Comment by vivekverma2312** [comment]
@somangshu 
<img width="953" alt="Screenshot 2022-04-07 at 11 09 37 AM" src="https://user-images.githubusercontent.com/83569920/162163174-27faf6a6-ea5b-41b5-8f53-59f3fab98447.png">
