### ISSUE TITLE
[Docs] Images are not optimized

### ISSUE THREAD

**Issue by JeffResc** [appsmithorg/appsmith#1264]
## Documentation Link 

N/A

## Describe the problem

Images in this repository are not optimized.

## Describe the improvement

I have losslessly compressed them and was able to reduce the overall file size by around 22% without losing any image quality. My branch can be found [here](https://github.com/JeffResc/appsmith/tree/img). I would like to create a pull request with these changes, but I am opening an issue first to seek input.

**Comment by Nikhil-Nandagopal** [comment]
👋 Hey Jeff, Thank you for your contribution. I don't see much value in reducing the image size of our documentation at this point but I'd be happy to have a look before taking a call. Unfortunately the link you point to redirects me to the fork not the PR against our repo so I can't see a diff. Can you raise a PR and link to that?

**Comment by JeffResc** [comment]
I attempted to first open this as a pull request, but the template suggested I should open an issue first. You can find the PR here:  #1294.

**Comment by Nikhil-Nandagopal** [comment]
@JeffResc  I see the net gain is about 20kb. The change is from
439kb to 420kb. The gain is not worth the risk of merging this large a change in terms of images so I'm not accepting this PR. Please have a look at our open issues
