### ISSUE TITLE
[Bug]: Select widget shows blank spaces

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Select widget shows blank spaces when more options are added.
https://loom.com/share/f7b8333ca2da4fae84fed6574dfea635
![image](https://user-images.githubusercontent.com/92293815/162132717-635ea4cb-d5ae-4bda-96f8-71e587e42f53.png)

### Steps To Reproduce

1. Drag and drop select widget
2. Add more values at the end of the default values given 
```[
  {
    "label": "Blue",
    "value": "BLUE"
  },
  {
    "label": "Green",
    "value": "GREEN"
  },
  {
    "label": "Red",
    "value": "RED"
  },
  {
    "label": "Orange",
    "value": "ORAN"
  },
 {
    "label": "Oe",
    "value": "ON"
  }
]```

3. Click on the drop down and select the last option 

### Public Sample App

_No response_

### Version

cloud

**Comment by dilippitchika** [comment]
@shwetha-ramesh this issue is being tracked here - https://github.com/appsmithorg/appsmith/issues/12755

FYI this is a critical issue
