### ISSUE TITLE
[Bug]: On importing template app through git import, template's name changes to that of git repository's name.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#12661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On importing a template app through git, its name is updated to that of git repository's name

### Steps To Reproduce

1. Fork a template into org
2. Connect it to git.
3. Import the connected app through git import.
4. Observe the name of application to be updated to repository's name.

### Public Sample App

https://release.app.appsmith.com/app/templaterelease/home-624e91b076bd5e3c25b801b6/edit?branch=master

### Version

Production

**Comment by nayan-rafiq** [comment]
Seems this issue is related with Git feature

**Comment by abhvsn** [comment]
@Parthvi12  this is a expected behaviour from git-import implementation. 
We are not committing the application name as changing the name or even importing the same application in same org will change this field for every alternate commit and push from both imported and parent application.

**Comment by AnaghHegde** [comment]
@Parthvi12 Closing this as it is the expected behaviour of git import feature. We can reopen the issue if anyone thinks we are doing it wrong.
