### ISSUE TITLE
[Bug]-[2400]: Action creator onSuccess and onError reset to "No Action" led to error: Unexpected token ')' when triggering action

### ISSUE THREAD

**Issue by lovemyliwu** [appsmithorg/appsmith#12663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

after reset onSuccess handler to "No Action", page generate wrong callback function for onPageChange handler  Query `Users`

```
errorMessage: "SyntaxError: Unexpected token ')'"
errorType: "PARSE"
message: "SyntaxError: Unexpected token ')'"
originalBinding: "Users.run(() => (), () => {})"
raw: "\n  function closedFunction () {\n    const result = Users.run(() => (), () => {})\n    return result\n  }\n  closedFunction.call(THIS_CONTEXT);\n  "
severity: "error"
type: "EVAL_TRIGGER_ERROR"
```

should generate `Users.run(() => {}, () => {})`

### Steps To Reproduce

1. create a query `Users` to fetch user list data
3. create a query `UserCount` to fetch record count and set alias to `count`
4. Add table widget binding to query `Users`
5. enable server side pagination
6. setup total record count property binding to `UserCount.data[0]['count']`
7. setup onPageChange event handler to `Users.run()`
8. setup outgoing event onSuccess handler to any action, for example query `UserCount`
9. deploy
10. reset outgoing event onSuccess handler to "No Action"
11. deploy
12. change page should see the error

### Version

Self Hosted - v1.6.5

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika did something change in the property pane recently?

**Comment by Nikhil-Nandagopal** [comment]
Simplified steps: 
1. Drag a button
2. configure the action selector to call 1 query and 1 query on success
3. Remove the on success query
4. Click the button

**Comment by Nikhil-Nandagopal** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 0.25 |

**Comment by yaldram** [comment]
Under `src/components/editorComponents/ActionCreator/index.tsx` line number 191 change this - 
```js
 const successArg = changeValue.endsWith(")")
  ? `() => ${changeValue}`
  : `() => ${changeValue}()`;
```

to - 

```js
  const successArg = changeValue.endsWith(")")
    ? `() => ${changeValue}`
    : `() => ${changeValue}{}`;
```
It worked for me, but need to test all scenarios. @dilippitchika @ApekshaBhosale

**Comment by dilippitchika** [comment]
@yaldram can you check if this code was changed recently?

@somangshu who works on this part?

**Comment by yaldram** [comment]
@dilippitchika I can see 5 months and 7 months ago changes atleast on the lines 192 - 194. The above solution is my guess, because these changes worked for me. Please contact frontend pod.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @dilippitchika this should be handled in the UI Builders. It's related to the action selector component.

**Comment by Rishabh-Rathod** [comment]
## Workaround

Toggle to JS mode and add code that was visible earlier for example.

When created trigger using action creator, we see `{{Api1.run()}}` 
1. Toggle to JS mode.
2. Replace generated code to `{{Api1.run()}}` 
3. Try triggering action now by a button click or other event. It should work as expected.
