### ISSUE TITLE
[Bug] Empty space in bottom of the page in view mode

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#12672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Current Experience
- The canvas does not clip to hug contents in the view mode, resulting in a lot of empty space at the bottom of the page and an unnecessary scrollbar.

Expected
- The canvas should clip to hug contents in the view mode.

### Steps To Reproduce

1. Add a widget to the top of the canvas.
2. Publish the application
3. Reduce the viewport size of the browser to notice a scrollbar appearing even though there is no content in the canvas.

### Version

Cloud

**Comment by Sripriya93** [comment]
Compared the behavior with release and could see the difference and no extra space in the canvas or the Deploy mode is seen. Moving to done.
