### ISSUE TITLE
[Docs] Add documentation on how to use re-captcha in Button Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1268]
## Describe the problem
Add a documentation page on how to use re-captcha inside a button widget

**Comment by JoshHeng** [comment]
@Nikhil-Nandagopal Please could I work on this issue

**Comment by JoshHeng** [comment]
@satbir121 I can't see the server side Recaptcha integration in your [commit](https://github.com/appsmithorg/appsmith/commit/8bf80fe50745f4cb64a2497a3de615c00af8ac13).
Is the Recaptcha integration complete (and are we not validating the captcha responses), or are you still working on it?

**Comment by Nikhil-Nandagopal** [comment]
@JoshHeng re-captcha requires only a client-side integration on appsmith. The server is expected to receive the token that the client sends and perform the verification on their own.
What our documentation should display is 
- Correctly configuring the recaptcha button
- Sending the re-captcha token to the backend using an API
- A link for a users backend to verify the token
