### ISSUE TITLE
[Bug]: Calling an async framework function inside a sync function tags the function async but doesn't add the `async` keyword

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#12687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="456" alt="Function marked async in Response tab" src="https://user-images.githubusercontent.com/91450662/162220547-662fd15e-ae70-4387-9220-1b8ddf72feb3.png">
<img width="586" alt="Unable t use await" src="https://user-images.githubusercontent.com/91450662/162220589-350222e7-7a3c-47cc-a14f-9db4c1e8767d.png">

### Steps To Reproduce

1. Create a new JSObj
2. Use one of the internal helpers available eg, storeValue(), showAlert() etc
3. Observe: Function in response tab gets tagged 'ASYNC'
4. Now try using await within the same function
5. **Observe : It is not allowed & throws error** & user is expected to add async to function name explicitly even though he sees ASYNC tagged to function in response tab!
6. **Expected: Trigger a toast informing the user with CTA which will auto adds the async keyword to function name in editor also**

### Version

Prod/Release v1.6.17

**Comment by bharath31** [comment]
@satbir121 this is super confusing and I've run into this issue a couple of times

**Comment by ohansFavour** [comment]
A function being asynchronous doesn't necessarily translate to it using the "async/await" syntax. Callbacks, Promises, etc also make functions asynchronous. The lint error message in "await" already provides the user with information on how to fix the issue.
