### ISSUE TITLE
[Bug]: Extra "" needed around password input value for API body JSON

### ISSUE THREAD

**Issue by aaahariri** [appsmithorg/appsmith#12696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have an API that accepts the body in this format:
```
{
    "email":"{{Input_email.text}}",
    "password":"{{Input_password.text}}"
}
```
However, when I try to call it with variables, it throws errors (saying the password needs to be a string). I checked the body sent with the AppSmith request, it showed that it was actually sent like this:
```
{
    "email":"f1@myemail.com",
    "password":123
}
```
As you can see, the **password "" was stripped**. I was only able to resolve this after modifying the API JSON body within AppSmith to include an extra "" around the password input value like this:
```
{
    "email":"{{Input_email.text}}",
    "password":""{{Input_password.text}}""
}
```

I thought that such behavior is odd and could be a bug!

### Steps To Reproduce

1. Add a Rest API that requires Raw JSON in the body
2. Replace variable values with input fields with the password field being masked

### Version

Self-Hosted Appsmith v1.6.18

**Comment by Nikhil-Nandagopal** [comment]
@aaahariri you can disable smart substitution for the API in the settings to solve this

**Comment by aaahariri** [comment]
@Nikhil-Nandagopal 
Thanks for your response. I actually want to use smart substitution but the behavior is not consistent at the moment. It removed the "" i only one of the smart tags.

**Comment by aaahariri** [comment]
Further to the above, it seems that if the input was just numbers, the "" would be stripped but not if the input includes letters and is treated as a string.

The same API/Query would throw an error if the input didn't include any letters (and therefore was treated as a number). However, if the input to the same field was a string (numbers and letters) it would not throw any errors and would work fine.

I don't think such inconsistent behavior is normal.

**Comment by Nikhil-Nandagopal** [comment]
@aaahariri smart substitution is used to automatically add the quotes around strings and automatically escape special characters such as apostrophe's inside them. This means that the code looks at the key in the JSON and detects if it is a number and removes the quotes and treats it as a number while if it is not a number, it adds the quotes and escapes any special characters
