### ISSUE TITLE
[Docs]: Update JavaScript Editor (Base Doc)

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12697]
Update the existing [JavaScript Editor (Beta)](https://docs.appsmith.com/framework-reference/javascript-editor-beta) doc.

**Comment by jnikhila** [comment]
Comment by @rohan-arthur 
I think we should avoid referring to the "newness" of a feature set, because it will not be true in a few months. Think of this document serving a user that is reading this several years from now

**Comment by ajinkyakulkarni** [comment]
#12195 is complete.

**Comment by jnikhila** [comment]
@rohan-arthur - Could you please review the published doc and close the ticket?

**Comment by jnikhila** [comment]
@cokoghenun - The existing video will need to be updated for the JS Editor. Could you please add this to your ticket pipeline - needs video.

**Comment by cokoghenun** [comment]
I've added this. Thanks @jnikhila

**Comment by Rishabhkaul** [comment]
@jnikhila assuming this can be closed right?

**Comment by jnikhila** [comment]
@Rishabhkaul - The ticket is in the 'Needs Video' pipeline. @cokoghenun - Is this ticket completed?

**Comment by cokoghenun** [comment]
Not yet. Bumping it up!

**Comment by cokoghenun** [comment]
Hey, @jnikhila I can work on a newer video async as I have higher-priority videos to work on right now. But I've added this update request to my list. Please feel free to close this issue
