### ISSUE TITLE
[Feature]: Container Jump Optimization and Add Logs to track Container jump metrics

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#12690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This feature is to Optimise container jumps by 
- changing threshold to absolute values
- make sure the mouse Pointer is on the canvas before jump in or else Reflow
- Add Log Trackers to monitor speed, acceleration of container jump and also log if it was a successful container jump or an accidental one.

### Why should this be worked on?

- Push this out as this container jump feels better than what is in Prod.
- With trackers, analyse and arrive at optimal values for Container jump thresholds.

**Comment by btsgh** [comment]
Discussed with @rahulramesha . Tested for ease of placement of widgets into container. Able to place widgets easily into container widget.
