### ISSUE TITLE
[Bug]: App crashes when using GSheets where condition operator using keyboard shortcuts

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App crashes when using GSheets where condition operator using keyboard shortcuts

### Steps To Reproduce

1. Go to any Goole Sheet query
2. Go to the where clause bit and type in a column name and then use `TAB` to move to the next feild and observe the app crash

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/69cfb7c69ca846448b819c398eb6f627-00001.gif)](https://www.loom.com/share/69cfb7c69ca846448b819c398eb6f627)
![image](https://user-images.githubusercontent.com/79509062/162395681-d92b1ac9-5438-4b4a-97a8-fb5176717afb.png)

### Version

Cloud

**Comment by rohan-arthur** [comment]
not able to reproduce with the original steps anymore, but thanks to @prapullac here's another way to see this error:
1. Add a GSheets query
2. enter spreadhsheet, and sheet name
3. run the query once
4. go to where clause section
5. enter "column name"
6. hit TAB (app doesn't crash)
7. when the focus is on OPERATOR field, hit the "down" arrow to expand the dropdown
8. app crashes
