### ISSUE TITLE
[Bug]: Unable to use arrays in postgres prepared statement

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#12702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Followed the docs to use arrays in SQL prepared statement: https://docs.appsmith.com/datasource-reference/querying-postgres#using-arrays-in-prepared-statement

It throws the following error:
```
ERROR: syntax error at or near "[" Position: 42
```

<img width="1257" alt="Screenshot 2022-04-08 at 11 20 50 AM" src="https://user-images.githubusercontent.com/10436935/162374231-1fa83d2d-328a-4e83-8045-75d335c33610.png">

### Steps To Reproduce

Follow [the docs](https://docs.appsmith.com/datasource-reference/querying-postgres#using-arrays-in-prepared-statement) and write a query using arrays and prepared statements

### Public Sample App

https://app.appsmith.com/app/array-in-sql-prepared-statement/page1-624ee59f457aa64da9e002d4

### Version

v1.6.17

**Comment by Nikhil-Nandagopal** [comment]
@aswathkk in the image prepared statements are off
