### ISSUE TITLE
[Docs]: Add a page describing the constraints for import/export of applications using JSON file

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#12704]
Context - https://discord.com/channels/725602949748752515/760761686549463060/961867160584597534

**Comment by jnikhila** [comment]
@abhvsn - Could you please add the first draft for the same.

**Comment by abhvsn** [comment]
@jnikhila noted! I'll provide the draft latest by Monday

**Comment by abhvsn** [comment]
@Pranay105 created a rough draft for the request https://www.notion.so/appsmith/Limitations-of-import-export-by-file-a9bb66a29b6c4b22baf65548b7e1e807

**Comment by Pranay105** [comment]
Already updated [here](https://docs.appsmith.com/advanced-concepts/more/backup-restore)
