### ISSUE TITLE
[Bug]-[210]:Mongo plugin URI parsing issue

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#12713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1649405309648129
Cannot share the URI string publicly here for security reasons. 

### Steps To Reproduce

https://theappsmith.slack.com/archives/C0341RERY4R/p1649405309648129 
Cannot share the URI string publicly here for security reasons. 

Workaround: Use the form based datasource config page.

### Version

cloud

**Comment by sumitsum** [comment]
@rohan-arthur Sorry, I just realised - not saving the URI string in some way was a mistake. Now I am not able to access the app that had the URI - we may not be able to figure out what the exact issue was - but I think we can figure out certain things from trial and error. From what I remember, our regex was parsing the URI string in a wierd way because the URI string had certain characters that the regex was using to identify the pattern. I think a little bit of trial and error should reveal some of such bad URI string types.

**Comment by rohan-arthur** [comment]
mongo 6m usage: 1050
Assume 5% users face this issue:  52.5

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 52.5 |
| Effort (months)  | <<number>> |

**Comment by pranavkanade** [comment]
@nidhi-nair this issue has resurfaced. [Internal discussion](https://theappsmith.slack.com/archives/C0341RERY4R/p1656488339424539)

**Comment by pranavkanade** [comment]
Another user flagged this issue - [link](https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100137352)

**Comment by nidhi-nair** [comment]
@jnikhila added draft for the documentation change related to this issue [here](https://www.notion.so/appsmith/Mongo-URI-format-a9a8d77080274c5cb1c551d189a822de).
