### ISSUE TITLE
[Docs]: Update Documentation - Prepared Statement

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12715]
We need to add documentation around when to use prepared statement and when not to along with scenarios.

Take inspiration from the How Do I Do X sessions recently.

Appsmith has just released a new video explaining Prepared Statements in depth. The docs should be checked against this video's content/explanation to ensure the instructions match and are clear.

Video can be found here.

(created from TODO in the Aforce ticket "Use LIKE Keyword in PostgreSQL Query with Prepared Statement Turned On")

**Comment by jnikhila** [comment]
@ajinkyakulkarni - we'll need help from Nidhi/Sumit to take this ticket ahead.

**Comment by Pranay105** [comment]
Nidhi's explanation - The prepared statements feature, when turned off, is supposed to evaluate to exactly what the query sent for execution is.
Prepared statements today works in a 1 binding - 1 parameter relationship. This means that every binding in the query needs to correspond to a prepared parameter for the query. If the user needs more logic in the query, that does not necessarily need to be a parameter, they would have to opt out of prepared statements.
Another bit of context: The concept of prepared parameters only works for certain placeholders. For example, you can prepare the values to replace in the where clause conditions, but you can't prepare the name of the table to query.
What that means is that if the user needs to dynamically choose the table to query, that use case is automatically impossible to achieve through prepared statements.
But from a product perspective there are still a bunch of things we can do to improve the experience, and also improve the use cases we're catering to with prepared statements:

1. Currently turning on prepared statements takes care of handling quotes for the replacement, but with prepared statements turned off, users are left stranded with regards to smart substitution as well. We should be able to cater to both these use cases separately.
2. Prepared statements should explicitly offer users with the option of selecting which of their bindings is applicable for PS. That way the can combine Appsmith logic with PS and make their apps more secure.
3. All of this becomes moot, till we solve for a way to show default values for queries easily. Our current solution to this is to allow for "safe" handling of the this.params path, but honestly the solution to this particular issue shouldn't be clean code, it should be something we provide from the product itself.

**Comment by jnikhila** [comment]
Please add examples when to use prepared statements and when to choose to opt out.

**Comment by jnikhila** [comment]
[how-to guide](https://docs.appsmith.com/how-to-guides/how-to-use-prepared-statements) published on live.
