### ISSUE TITLE
[Bug]: Deleted parent Array type fields reappears on browser refresh in JSON Form widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#12711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding multiple array field inside array items, we can see multiple delete options as well. 
On deleting parent field, it seems like field got deleted but it reappears on browser refresh

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7c97262687ff46a9885359ae55ce494b-00001.gif)](https://www.loom.com/share/7c97262687ff46a9885359ae55ce494b)

### Steps To Reproduce

1. Add Json form onto canvas
2. Add new fields and change it to Array
3. Add Array field inside Array items
4. Keep on doing it for 4-5 times
5. Delete 2nd array field and observe that it got deleted
6. Refresh the browser and observe that all array fields reappears

### Version

cloud/Production

**Comment by dilippitchika** [comment]
Not an issue
