### ISSUE TITLE
[Bug]-[480]:Tree select widget - dropdown flickers when we click on the default selection area and filter has text entered.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#12714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In tree select widget, in the dropdown on attempt to filter, with the text entered, if we click on the tree select default field, dropdown flickers and does not get expanded. 

### Steps To Reproduce

1. Drag and drop a tree select widget
2. Click on the dropdown arrow
3. Enter a letter to filter. The options having that letter will get highlighted
4. Now click on the default selection area. Dropdown gets closed
5. Again click on the default selection area. 
 The dropdown flickers. It does not get displayed completely. Only when user clicks on the arrow to the right of the select area, the dropdown appears properly.

Expected behaviour - dropdown should get displayed even on clicking on default selection area, with filter applied.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9041091f41e44e509a247a989092d781-00001.gif)](https://www.loom.com/share/9041091f41e44e509a247a989092d781)

### Version

Release

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 120 |
| Effort (months)  | 0.5 |

**Comment by YogeshJayaseelan** [comment]
@techbhavin This is happening in release 

https://loom.com/share/245d775f2be74ebdbec01e531a974beb

**Comment by techbhavin** [comment]
@YogeshJayaseelan  @vivekverma2312  

I am not able to reproduce this issue in release.

https://user-images.githubusercontent.com/58818598/166624176-ea94cf1e-414d-423d-ac6c-81ab8db84fcf.mov

**Comment by btsgh** [comment]
Unable to reproduce on release now (9th May 2022). Probably some other change has resolved this issue.

**Comment by btsgh** [comment]
Tested and found to be fine
