### ISSUE TITLE
[Task]: In Dev mode, appsmith becomes unresponsive due to an iframe 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

<img width="1916" alt="Screenshot 2022-04-08 at 5 32 20 PM" src="https://user-images.githubusercontent.com/23132741/162431899-b70bcc4d-fe43-410d-86ae-46d2379f164a.png">

Cause of iframe maybe is related to - https://stackoverflow.com/questions/69051008/react-injecting-iframe-with-max-z-index-on-reload-after-changes-development

**Comment by noobyogi0010** [comment]
Hey @Rishabh-Rathod 
I would like to work on this issue if it's not already worked upon.
Thanks!

**Comment by Rishabh-Rathod** [comment]
Hey @noobyogi0010,

You could surely go for it. Are you able to reproduce this issue in development mode? 
As this issue is related to project configuration and hard to reproduce in development mode, it was not made as Good First Issue. 

If you would like to pick some other issue feel to to pick from [Good first issues. ](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+no%3Aassignee)
