### ISSUE TITLE
[Feature]: Sidebar Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#12734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be a sidebar widget that users can use to navigate the page or content through the sidebar.
Currently, we have a sample app where a sidebar is implemented, but we do not have a separate widget for this.

### Why should this be worked on?

A sidebar widget would be useful for users so that they can only drag and drop it to the canvas and configure it according to their needs. It is more time-consuming to implement the sidebar using the existing widgets.

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith thanks for the feature request. We already have this issue tracked here #2282
