### ISSUE TITLE
[Bug]-[44]:Appsmith loses connectivity to ArangoDB

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#12732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Shared by user on Discourse

> I’ve recently started testing AppSmith with ArangoDB(v3.9.0).
>I have both AppSmith and Arango hosted in separate Docker containers on my local machine.
> 
> Initially everything works well, but after a period of time AppSmith appears to lose connectivity to Arango. Looking at the AppsSmith console i can see the following: (logs here - https://community.appsmith.com/t/arangodb-connectivity-issues/834)
>
> I’ve tried binding to host.docker.internal and my local IP address, both behave the same - works initially and then stops. I can also confirm that this behaviour has not changed since updating to AppSmith v1.6.18

### Steps To Reproduce

https://community.appsmith.com/t/arangodb-connectivity-issues/834

### Version

Self-Hosted - v1.6.18

**Comment by rohan-arthur** [comment]
Arango 6m: 11

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 11 |
| Effort (months)  | 0.25 |

**Comment by rohan-arthur** [comment]
I'm closing this issue because we haven't seen this in the past year or so
