### ISSUE TITLE
[Bug]-[30]:Ms SQL plugin prepared stmt

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#12731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From community:
```
how to fix the issue when we are query DB and have mix of values type and appsmith try to frce it as int and the retunr error because the collum have nvarchar and varchars values?

can you please tell the column data type ?

nvarchar48
is from a view

Are you using a select query or update query ?.

the error happen because the specific code
select query
if ignore this > EN0001
i have results if not ignore that error appears

```
![image](https://user-images.githubusercontent.com/1757421/162480651-4e168416-8888-48f1-a622-684d2d7c35c7.png)

```
it appears the issue is the same as the "insert"
appsmith is transforming 00002 into 2
so something like '00002' don't return nothing
i must put it to something = '00002' but then appsmith conert it to something = 2

Can you try after toggling off the prepared stmt toggle ?

yeah if i do that it works

Does the select work or only insert ?

the select work
will check the insert
yep it works
```

### Steps To Reproduce

I haven't tried it out myself. I am currently relying on the info provided by the user as mentioned above

### Version

cloud

**Comment by sribalajig** [comment]
@subrata71 @btsgh can you please check if this issue is still valid?

**Comment by subrata71** [comment]
This issue is about losing leading zeros. This has already been handled by https://github.com/appsmithorg/appsmith/issues/17072. I think we can close this issue. 
@sribalajig
