### ISSUE TITLE
[Feature]-[25]:Hide Add and Delete controls if a JSON Form is disabled

### ISSUE THREAD

**Issue by vernonstinebaker** [appsmithorg/appsmith#12744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When displaying a JSON form, even when a section within the form is set to disabled (and the elements within the section also set to disabled), the Add and Edit buttons still appear. This is inconsistent with the section being disabled. 

See attached screenshot.

<img width="870" alt="Screen Shot 2022-04-10 at 20 13 39" src="https://user-images.githubusercontent.com/8304954/162618062-d4b8ec26-debf-4dd3-8c57-0760fd30ed7a.png">

### Why should this be worked on?

If an element is disabled, it shouldn't be editable. The Add and Delete options are inconsistent with the disabled option.

**Comment by Nikhil-Nandagopal** [comment]
@vernonstinebaker thank you for the feature request!

**Comment by dilippitchika** [comment]
Let's discuss this once @ashit-rath i believe there's a bit more nuance here.

**Comment by dilippitchika** [comment]
Suggested solution

- Disabled for now will disable the add new and delete options as well.
- We will later add controls to hide delete and add new specifically.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 25 |
| Effort (months)  | 0.5 |
