### ISSUE TITLE
[Template]: WordPress & WooCommerce Sales Dashboard

### ISSUE THREAD

**Issue by rochesterj** [appsmithorg/appsmith#12748]
### Title

WordPress & WooCommerce Sales Dashboard

### Objective

A dashboard that reads data from a WordPress & WooCommerce site directly.

It showcases how to generate many useful components from the WP database connection:

- Get the aggregate revenue
- Get the orders count
- Calculate the average ticket size
- Get revenue by date within a specific period (day, week, month, year)
- Get orders count by status
- Get orders by location
- Generate products ranking (products and sales list)
- Get customers ranking (customers and order amount)
- Using custom charts to display information

All these elements are filtered by timeframes set by the user (today, current week, current month, current year, yesterday, last week, last month, last year).

Optional page: Login form connected to WordPress (use WP login / username).

The article teaches users how to get this data, how to create their own KPIs, best practices for performance, how to add granularity (for example, if there are managers for different countries or product categories), how to add WP login

### Wireframes

https://app.appsmith.com/applications/625314aa6a70ad452dee5116/pages/625314aa6a70ad452dee511c

### Validation criteria

User should be able to select timeframes
Optional: User should be able to login with WordPress credentials

### Use case

Sales

### Industry

Other

### Data sources

Mysql

**Comment by Rishabhkaul** [comment]
@GreenFlux @danciaclara This is a blog post, not sure if this is useful enough as a template

**Comment by jacquesikot** [comment]
Template request has been moved to Request Templates App here - https://app.appsmith.com/app/request-templates/request-list-6241c12fc99df2369931a714
