### ISSUE TITLE
[Bug]-[2640]:Renaming page after reorder is not proper on page setting page

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#12758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ccbb6c4bc3f241ceb3c9f51fa28b8dae-00001.gif)](https://www.loom.com/share/ccbb6c4bc3f241ceb3c9f51fa28b8dae)

### Steps To Reproduce

1. Navigate to Page setting page
2. Add few new pages
3. Rename one of the page
4. Reorder that page
5. Now try to reorder another page
6. Observe that previous page is getting renamed.

### Version

Cloud

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 330 |
| Effort (months)  | 0.25 |

**Comment by Sripriya93** [comment]
Working fine, Verified!
