### ISSUE TITLE
[Bug]: Omnibar: List Widget - Update broken link

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12759]
The last link isn't hyperlinked correctly in the quick navigation. 
![Quick Navigation.png](https://images.zenhubusercontent.com/6203759d49a2167250e9a805/1cfdc1e6-1335-46e9-b8f6-2247bc037a44)

The link works fine on docs.appsmith.com but is broken when searched through omnibar.

**Comment by jnikhila** [comment]
@hiteshjoshi - The issue is occuring when searched through omnibar. Could you please verify and pass it on to the concerned team. CC - @ajinkyakulkarni

**Comment by jnikhila** [comment]
As suggested by @arunvjn - I've edited the doc and merged to trigger the AWS Lambda again. I checked the list doc again after a considerable amount of time but the broken link issue still exists. @ajinkyakulkarni - I guess someone from the engineering team will have to take it ahead.

**Comment by hiteshjoshi** [comment]
@akash-codemonk can you take a look into this

**Comment by akash-codemonk** [comment]
This issues exists currently for all the below docs
```
setup/kubernetes
setup/aws-ecs
tutorials/review-moderator-dashboard/creating-interactive-views-using-lists-and-charts
tutorials/building-a-store-catalog-manager/part-2-using-forms
tutorials/building-a-store-catalog-manager/part-3-creating-interactive-views
sample-apps
how-to-guides/how-to-work-with-google-sheets-on-appsmith
how-to-guides/use-mssql-as-data-source how-to-guides/use-redshift-as-data-source-on-appsmith
how-to-guides/how-to-use-elasticsearch-as-a-data-source-on-appsmith
how-to-guides/how-to-work-with-graphql-on-appsmith 
how-to-guides/how-to-use-js-object-within-appsmith 
core-concepts/git-sync
datasource-reference/querying-google-sheets
datasource-reference/querying-mongodb
framework-reference/javascript-editor-beta
widget-reference/chart
widget-reference/container
widget-reference/currency-input
widget-reference/form
widget-reference/input
widget-reference/json-form
widget-reference/list
widget-reference/phone-input
widget-reference/table
```
