### ISSUE TITLE
[Bug]: Select Widget - Options are vanishing as user selects options from bottom of the popup.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2022-04-11 at 11 39 19 AM](https://user-images.githubusercontent.com/13262095/162681621-728b729b-8256-4e97-a12f-bf9e15ddc60c.png)
![Screenshot 2022-04-11 at 11 39 10 AM](https://user-images.githubusercontent.com/13262095/162681628-12f6d870-0f6b-44ab-a891-42e9d8ccd6f5.png)
![Screenshot 2022-04-11 at 11 38 58 AM](https://user-images.githubusercontent.com/13262095/162681630-ed00090d-dbe2-49e9-a89b-8434b63a0c19.png)
![Screenshot 2022-04-11 at 11 38 50 AM](https://user-images.githubusercontent.com/13262095/162681631-27116d58-a16b-47a7-8cf3-308a351be2f5.png)
![Screenshot 2022-04-11 at 11 40 12 AM](https://user-images.githubusercontent.com/13262095/162681636-c3d68513-9134-43f0-af7a-2ef2a4b8b1f2.png)

### Steps To Reproduce

1. Drag Select Widget
2. Add static options to JS Object
3. Populate the select widget
4. Click on it and select option from bottom & click on widget again.

### Public Sample App

https://app.appsmith.com/applications/621e1b9e445a8d746a062f01/pages/6253d146e52b06350af34319

### Version

Cloud

**Comment by dilippitchika** [comment]
@Tooluloope can you please investigate why this is happening and then let us know the fix

**Comment by Tooluloope** [comment]
Okay @dilippitchika
