### ISSUE TITLE
[Bug]: Datepicker dropdown menu is cut off in the deployed mode

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#12757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open a datepicker dropdown menu it will be cut off if it is at the top of the page.
![Screenshot 2022-04-11 at 09 16 31](https://user-images.githubusercontent.com/81744497/162684651-054e6e17-7776-419d-9081-df1472dd8b2b.png)

This only happens in Appviewer mode, not while building the app.

### Steps To Reproduce

1. Add a date picker to your app
2. Deploy the app
3. Scroll down so that the date picker is at the top page
4. Open date picker

### Version

Cloud

**Comment by dilippitchika** [comment]
@momcilo-appsmith please share the app unable to reproduce this

**Comment by momcilo-appsmith** [comment]
@dilippitchika For some reason, I can't find it and I can't reproduce it as well. I saw it in an app from one of our users and reproduced it that day. But it seems like it is solved now.
