### ISSUE TITLE
[Bug]: GSheet : Datasource name is not displayed to user in the Query pane 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#12762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user Authorise the Gsheet and navigates to create a Query it is observed that the Datasources is not displayed to user 

### Steps To Reproduce

1) Navigate to Datasource page 
2) Click on Gsheet 
3) Authorise the account
4) Click on New API
and Observe that the Datasource name is not displayed to the 

Note: The datasource is not displayed in the dropdown as well. However, execution of the query does work.

![Screenshot 2022-04-11 at 1 19 01 PM](https://user-images.githubusercontent.com/71753653/162691031-7f8c0790-c474-4588-8850-27ea5d452c0b.png)
user in the dropdown 

### Version

Release

**Comment by btsgh** [comment]
Though the database dropdown is not blank, The issue commented above by @prapullac  is still existing. When we create a Query with an excel data source, only GSheets data sources are listed. This behaviour is incorrect. As per the requirement and also as per the behaviour of all the other queries associated with other data sources, All the DataSources that we have created should be listed in that drop down and user should be able to select any data source (even other than gsheets datasource).

**Comment by Irongade** [comment]
@btsgh This behaviour is not incorrect. The reason why other datasources are not displayed is because they are not of the same type as google sheets. Google sheets as of today are still classified as Saas datasources, which other types like MongoDB, MySql are not. 

The behaviour is also consistent with what's in Production as of today.

**Comment by prapullac** [comment]
Hi @Irongade 
Thanks for helping us understand the implementation.I will go ahead and close the issue
