### ISSUE TITLE
[Bug]: JSObject gives error when referencing a widget in showAlert()

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#12766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

showAlert(MultiSelect1.selectedOptionValues.length;, 'info') gives error in JSObject function

### Steps To Reproduce

1. Create  a MultiSelect Widget, lets call it MultiSelect1 
2. Create a JSObject, JSObject1, add function myFun1
3. In myFun1 add ```showAlert(MultiSelect1.selectedOptionValues.length;, 'info')```
4. Try running JSObject1.myFun1, it shows an error _response is undefined

### Version

Cloud

**Comment by ohansFavour** [comment]
`showAlert` expects a string as its first argument. changing the code `showAlert(MultiSelect1.selectedOptionValues.length.toString(), 'info')` solves this.
