### ISSUE TITLE
[Bug]: When extra long name for organization is given text is overlapped in Fork modal

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When extra long name for organization is given text is overlapped in Fork modal

![image](https://user-images.githubusercontent.com/92293815/162719756-dee269f6-9e9f-4ea0-b024-c0c017d45019.png)

### Steps To Reproduce

1. Login to release
2. Create 2 org > Name 1 organization with extra long name
3. Fork an application from first org to second org and verify the fork modal

### Version

Cloud

**Comment by hetunandu** [comment]
[Uploading... Screen Recording 2022-07-13 at 10.03.22 AM.mov]

I don't see this happening anymore @shwetha-ramesh 
Can you confirm if this is still happening on your end?

**Comment by kocharrahul7** [comment]
Cannot be reproduced any more, if it returns, please reopen
