### ISSUE TITLE
[Bug]-[500]:Table column border is sensitive and triggers both move and resize actions on mouse click leading to bad UX

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Resizing table columns causes columns to get rearranged since the border is sensitive to both resize and rearrange action. This causes UX issues where user has to be slow while resizing as seen in the video and control is still on the selected column so either the column is resized or rearranged when user lets go of control by release click action.

### Steps To Reproduce

1. Go to a table widget and add a few columns
2. Try to re-size columns by hovering over the column boundary to see the resize icon.
3. Click to select the resize option and observe cursor change to move icon
4. Let go of cursor click at various points on the column header and observe that the column size readjusts to the point where the resize action is registered (see video attached at the 4 second mark to see this behaviour)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/70dd8d17372b4fd392b6b67d7948147f-00001.gif)](https://www.loom.com/share/70dd8d17372b4fd392b6b67d7948147f)

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | 0.5 |
