### ISSUE TITLE
[Bug]: Tooltip cuts off for Organization with extra long name on hover 

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When extra long organization name is added for the first organization on the list  and when the user hovers over the name on the left hand side of the home page, the tooltip gets cuts off from the top of the screen

![image](https://user-images.githubusercontent.com/92293815/162714692-d732f5a6-3add-4cc4-91bc-a381c03f1949.png)

### Steps To Reproduce

1. In home page > Click on new organization and enter a extra long name for the first organization
2. Hover on the org name on the left hand side of the home page

### Version

Cloud

**Comment by riteshkew** [comment]
Not applicable post homepage revamp.
