### ISSUE TITLE
[Feature]: Access organisation details, members on Appsmith Context Object

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#12772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today, we can only access user details on the Appsmith Context Object using `{{appsmith.user}}`. Would it be possible to create a new feature that lets us access all the **organisation** details and members? 

Something like: `{{appsmith.org.members}}`

More context: https://community.appsmith.com/t/how-do-i-get-organization-members-inside-my-application/841/2 

### Why should this be worked on?

This lets us control organisation details and members within Appsmith apps itself. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7h630)

**Comment by nzidol** [comment]
+1 appsmith.user.role is information entered by the user when they sign up, User and Administrator should be able to edit that....

**Comment by ohansFavour** [comment]
As part of this feature, we should also include the **`workspace name`**. More info [here](https://app.frontapp.com/open/msg_1mwxnr4c?key=XoXvMzYD1X2p1QZiD2uakPsoi9HodQuA)

**Comment by geekyme-fsmk** [comment]
+1.

My use case: 
1. I created an internal tool, and have assigned different appsmith roles for viewing / developing the app. 
2. My viewers have different permissions (supervisor vs employee)
3. Supervisor has elevated rights, and can access certain screens that the employee cannot.

**Comment by Nikhil-Nandagopal** [comment]
@geekyme-fsmk that is available in our business addition as part of our Role based Access Control feature. That will be a much better way to solve your use case. You can sign up here and give it a try https://www.appsmith.com/pricing

**Comment by riteshkew** [comment]
Solved by programmatic access control
