### ISSUE TITLE
[Bug]-[25000]:[UI] hover state missing for items in the 3 dots menu

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Untitled (1)](https://user-images.githubusercontent.com/94514895/162721720-e54c9528-e5cc-4464-b057-027dd86c5a71.png)

### Steps To Reproduce

1. go to datasources page
2. expand the 3 dots menu
3. the menu items don't have a hover state

### Version

Cloud

**Comment by rohan-arthur** [comment]
reach: 12000

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.10 |

**Comment by rohan-arthur** [comment]
this is how it looks today, maybe it was fixed in another PR:

https://user-images.githubusercontent.com/94514895/165514757-7a1513bd-eeb8-480a-a284-bd42a2a40f85.mov
