### ISSUE TITLE
[Feature] Report specific errors to Rollbar

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1278]
## Summary

Instead of all errors on the server side being reported to Rollbar, only specific errors should be reported. 

## Motivation

Since the Appsmith Cloud Platform uses Rollbar for error tracing and paging engineers internally, we should only report those errors that are critical in nature and require an engineer's attention. 

## Additional Context

In order to solve for this, we need to add a parameter to the `AppsmithError` enum that determines if a particular error must be reported or simply logged to the file. Then in the `GlobalExceptionHandler`, we make a decision to report the error to Rollbar based on this parameter.

**Comment by sumitsum** [comment]
Pull req merged. Opening new issue for sentry part.
