### ISSUE TITLE
[Bug]: EditorJSONtoForm Component being re-rendered unnecessarily

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#12787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

EditorJSONtoForm was being re-rendered 30 times due to the wrong props being passed from the parent component -> QueryEditor.

### Steps To Reproduce

In development mode : 
- Added a `console.count` to display the number of re-rendering of a component.
- Added a `whyDidYouRender` property to component to identify the props creating re-rendering issues.

### Version

Both

**Comment by yatinappsmith** [comment]
Performance fix , verified for regression
