### ISSUE TITLE
[Docs]: Review OAuth documentation for Authorization Code workflow

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#12813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/connecting-to-data-sources/authentication/oauth2-authentication

### Describe the problem

A user reported that our documentation for OAuth is not clear https://discord.com/channels/725602949748752515/760761686549463060/962283221662449714

https://theappsmith.slack.com/archives/C02KTH6EHUG/p1649469058031879

### Describe the improvement

Please review the current OAuth documentation and update any section that you feel is unclear for our users.

**Comment by jnikhila** [comment]
@rohan-arthur - I've ported the changes to Gitbook. Could you please review the same?

**Comment by nidhi-nair** [comment]
Hey @jnikhila! There's also some advanced settings under Authorization Code and the resource and audience fields under Client Credentials. Should we be adding details for those in the same page?

**Comment by jnikhila** [comment]
@nidhi-nair -  As discussed, I'll add a section Additional settings that will cover the advance settings as well as some optional settings. For client credentials workflow, it will be worked upon as part of #12984

**Comment by jnikhila** [comment]
Document available on[ live site](https://docs.appsmith.com/core-concepts/connecting-to-data-sources/authentication/oauth2-authentication).

**Comment by rohan-arthur** [comment]
lgtm thanks Nikhila
