### ISSUE TITLE
[Bug]-[16]:Unable to select option in Radio Group field type when value is Number on JSON Form widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#12815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/25292713d76842da8e03b4a50b1f7d66-00001.gif)](https://www.loom.com/share/25292713d76842da8e03b4a50b1f7d66)

### Steps To Reproduce

1. Add Json Form widget onto canvas
2. Add a Radio Group Field type
3. Under Options set value as Number to see the issue
4. Observe that option is not getting selecting on click

### Version

Cloud/Production

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4 |
| Effort (months)  | 0.5 |
