### ISSUE TITLE
[Bug]:  The option to add admin emails does not grant admin access for form login users 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 The option to add admin emails does not grant admin access for form login users 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/162886643-e4c922a6-e4e5-4887-afa4-10f307b2ca28.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/162886689-204aafd7-b4f6-4af2-ab36-cf98b75cdf53.png">

### Steps To Reproduce

1. In the admin setting page
2. under general tab
3. In Admin Email when user adds any email address of the existing user
4. Now login with the existing user email
5. check for admin setting  acess
6. The user doesn't have a admin access

### Version

release

**Comment by nayan-rafiq** [comment]
@RakshaKShetty I was not able to reproduce this locally. Can you reproduce the issue on release or other instances?

**Comment by RakshaKShetty** [comment]
@nayan-rafiq still facing the issue attaching the screenshot for Reference i have tested in the release ce image
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/175859021-ec1fc8a2-d2c4-4b1a-bab4-2a550f76e92d.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/175859049-600ddabb-d655-4d17-b162-c183255e732c.png">

**Comment by sharat87** [comment]
Looks like this has been fixed since. I can't reproduce it on the current `release` image.

**Comment by renatocron** [comment]
I think there's a regression, I'm having this issue on Appsmith Community v1.9.27
