### ISSUE TITLE
[Bug]-[7000]:Placement issue with debugger

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#12829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is gap at the bottom of the debugger through which we can see the content of the canvas
![Screenshot 2022-04-12 at 11 29 48 AM](https://user-images.githubusercontent.com/5328605/162891089-58af46d7-92b5-4ed6-ae82-38b7a969cff7.png)
a 

### Steps To Reproduce

1. Open debugger
2. observer that the bottom of debugger has a gap 
3. scroll the canvas contents and observer that you can see the content through the gap

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3500 |
| Effort (months)  | 0.25 |
