### ISSUE TITLE
[Bug]-[500]:Entity explorer does not navigate to widget on other tab

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1282]
Steps to reproduce:
1) Add a tab widget 
2) Add Multiple tabs 
3) Add a dropdown widget on Tab1 
4) Copy the Dropdown widget 
5) Navigate to Tab2 and paste it without selection of the area 
and observe 

Observation:
Observation 1:
The dropdown widgets gets placed on Tab1 even when the user is on Tab2 but this is visible on the entity explorer

Observation 2:
Now clicking on the entity explorer for dropdown's it is observed that the user is not navigate to respective tabs for display 

Expectation:
Expectation 1:
User must be navigated to Tab where the widget is placed when the user is on another tab on click from the entity explorer 

Expectation 2:
On Copy the widget must be placed on the current tab where the user is 

Video link:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4f073d08002f4c96a4fbbefba5252785-00001.gif)](https://www.loom.com/share/4f073d08002f4c96a4fbbefba5252785)

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 0.5 |

**Comment by Richarex** [comment]
@hetunandu please take a look on these issues.
- [ ] when the user tries to navigate to widget under tab3 of tabs widget from different page it doesn't navigate. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/5r0msq0sXbDsiDiT
- [ ] Modal widget disappears when the user tries to drag and drop another widget inside tab widget. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/wPw8AvNzT6arRGXa
- [ ] when the widget is placed below view port and navigating to it from omnibar it doesn't get highlighted though the property pane opens. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/w2CrUVJ3y3xv1qAk

**Comment by Richarex** [comment]
- [X] when the user tries to navigate to widget under tab3 of tabs widget from different page it doesn't navigate. This issue is fixed verified it on the DP url.
- [X] Modal widget disappears when the user tries to drag and drop another widget inside tab widget. This issue is fixed verified it on the DP url

**Comment by Richarex** [comment]
2round off of testing has been completed, verified all the bug fixes and no new issues found.
