### ISSUE TITLE
[Bug]: CRUD pages display table column error on browser console

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CRUD generated pages are displaying a parse error for table widget

### Steps To Reproduce

1. Generate a page via CRUD, refresh page and observe the console
![image](https://user-images.githubusercontent.com/79509062/162890834-b7448dd0-f793-4e12-acd0-f7e2420b6a89.png)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Unless it's an error a user faces, we can ignore it
