### ISSUE TITLE
[Example] Create a customer OnBoarding Example app on appsmith

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1283]
## Describe the problem

We want to build a customer onBoarding example application to demonstrate the power of tools that can be built on appsmith. We can use this template as a guiding star on how the customer onboarding app should look
https://www.jetadmin.io/templates/customer-onboarding-tool
The app should be built on app.appsmith.com and be made public
The documentation and readme should be updated with the application

**Comment by CH-ND-N** [comment]
sir please assign this to me.

**Comment by Nikhil-Nandagopal** [comment]
@CH-ND-N unfortunately this has already been assigned to someone. Please have a look at our other good first issues 😃

**Comment by krishguptadev** [comment]
How can I fix this issue?

**Comment by Nikhil-Nandagopal** [comment]
@krishguptadev sure, go for it and raise a pr with the exported application!

**Comment by krishguptadev** [comment]
@Nikhil-Nandagopal I would like to know where am I supposed to add this, since I am new to this project

**Comment by Nikhil-Nandagopal** [comment]
@krishguptadev you can start by building the app and Sharing it with us. In the meantime, I'll create a folder to check this in

**Comment by krishguptadev** [comment]
Also, what do I have to recreate? Like I just see this page when I open the link: 
![image](https://user-images.githubusercontent.com/91655303/135754837-4dd1506f-a14f-4cc9-9de8-5b72790eae8d.png)

**Comment by krishguptadev** [comment]
> Also, what do I have to recreate? Like I just see this page when I open the link: ![image](https://user-images.githubusercontent.com/91655303/135754837-4dd1506f-a14f-4cc9-9de8-5b72790eae8d.png)

Could you tell @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@krishguptadev it looks like the demo is not loading for you. I think you need to hit accept and refresh the page.

**Comment by krishguptadev** [comment]
It loaded, but I think we should not clone this, since it is a template [up for sale by someone](https://www.jetadmin.io/pricing/internal-tool)

**Comment by Nikhil-Nandagopal** [comment]
@krishguptadev the template is only a guiding star for the type of requirements a customer onboarding tool should have. Please don't replicate it but use it to understand the type of tool to be built :)

**Comment by krishguptadev** [comment]
@Nikhil-Nandagopal I have made this till now: https://app.appsmith.com/applications/6159a9ed3a5bfe535012a43c/pages/6159a9ed3a5bfe535012a43e Could you tell me what more could I add?

**Comment by vihar** [comment]
Hey @krishguptadev, this is a simple CRUD app that can be auto-generated from Appsmith. Can you try to add any other functionalities to this, as I mentioned above?

**Comment by Nikhil-Nandagopal** [comment]
Hi @krishguptadev, maybe this isn't the best issue to work on then? Have you had a look at our other good first issues?

**Comment by Nikhil-Nandagopal** [comment]
Hi @krishguptadev , this may be a better issue for you
https://github.com/appsmithorg/appsmith/issues/4468
Do leave a comment if you're interested in it

**Comment by kocharrahul7** [comment]
This issue can be tracked here

https://github.com/appsmithorg/appsmith/issues/9661
