### ISSUE TITLE
[Bug]: `navigateTo` is throwing unexpected errors with list widget

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2022-04-12 at 12 11 03 PM](https://user-images.githubusercontent.com/13262095/162902315-32e4b170-0e84-4350-9770-62de2f7f3660.png)
![Screenshot 2022-04-12 at 12 43 53 PM](https://user-images.githubusercontent.com/13262095/162902353-29d5ec2c-57e4-42db-a29a-f710f0f0ebd8.png)

Here are the two instances of this issue. The `navigateTo` throws an error for valid bindings.

### Possible solution 
https://github.com/appsmithorg/appsmith/pull/14470

### Steps To Reproduce

https://theappsmith.slack.com/archives/C0341RERY4R/p1649716348012539

### Version

Cloud

**Comment by ajinkyakulkarni** [comment]
Internal discussion around this issue https://theappsmith.slack.com/archives/C0341RERY4R/p1649716348012539

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/12833?planning-poker) with ZenHub @rimildeyjsr

**Comment by pranavkanade** [comment]
@rimildeyjsr are we actively working on fix for this issue?

**Comment by Rishabh-Rathod** [comment]
## Workaround for above issue in ListWidget

1. Create a JSObject like below
```
export default {
	escapeString: (str) => {
		return str.replace(/\n/g, "\\n").replace(/\t/g, "\\t").replace(/\r/g, "\\r").replace(/'/g, "'")    
	},
}
```
2. Add `JSObject.escapeString(data)` before passing data to your action
In above case, 

instead of 
```js
navigateTo(data)
```
we need to convert it to.
```js
navigateTo(JSObject.escapeString(data))
```

**Comment by bharath31** [comment]
Assuming 80% of users writing `navigateTo()` face this issue  

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1680 |
| Effort (months)  |  |
