### ISSUE TITLE
[Bug]: Draw size is not proper when we resize the browser

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#12835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/cc52ac82cef849ff830915dde59702f6-00001.gif)](https://www.loom.com/share/cc52ac82cef849ff830915dde59702f6)

### Steps To Reproduce

1. Open an app with few widgets
2. Drag and draw few widgets on canvas
3. Copy the widgets
4. Now resize the browser
5. Paste the copied widgets
6. Bring back the size of the browser
7. Observe that the draw area reduces from the right side.

### Version

Cloud

**Comment by btsgh** [comment]
This issue has been fixed and is working fine on release.
