### ISSUE TITLE
[Feature]-[2400]:Autoassign the column datatype in table widget instead of default Plain Text depending upon the column data

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#12831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently for any type of data in table widget `Plain Text` is auto-assigned. User will have to change it manually if one wants to. 

### Why should this be worked on?

One of the use-case where we find this useful is in generate CRUD page feature, where we have implemented the server side pagination along with the order by operator which depends upon the `table.sortOrder.column` and we don't have any control over user's data so default assignment don't work here.

Sample query:  
```
SELECT * FROM public."users"
WHERE "field1" ilike '%{{data_table.searchText || ""}}%'
ORDER BY {{data_table.sortOrder.column || 'id'}} {{data_table.sortOrder.order || 'ASC'}}
LIMIT {{data_table.pageSize}}
OFFSET {{(data_table.pageNo - 1) * data_table.pageSize}};
```

**Comment by dilippitchika** [comment]
Applicable for
1. Dates
2. Numbers
3. Booleans (i think this will work already because of only 2 possible values)

Assuming all new table users will benefit from this (all users who dragged and bound a table widget)

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2400 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Kicking off a discussion on this to understand the solution

@sbalaji1192 @Tooluloope is this straightforward now that we have similar logic in the json form?

**Comment by sbalaji1192** [comment]
@dilippitchika There is a slight deviation from the JSON form.
In the table,
1.  You need to look at all the row values for a column to figure out the column type. If the user has enabled serverside pagination. it would be not possible to determine the column type without looking at all the rows.
2. Need to consider the performance aspect when it comes to tables with huge table data.

**Comment by Nikhil-Nandagopal** [comment]
@sbalaji1192 we don't need to be perfect here when guessing the data type for the user. We can infer the type based on the rows in the viewport.

**Comment by dilippitchika** [comment]
@sbalaji1192 you are right about us not being able to figure out for all rows. Which means there's a chance of missing accuracy on this. But today we are don't have a way to dynamically change the type for the column (if it has 2 data types) and enabling that will be very hard to configure in the property pane.

So what we are essentially doing is suggesting better defaults for the user, and allowing them to change it on their own if they wish to. I guess we only need to look at the first row for this. 

Or If we want to look at a few rows, and if there's a mismatch in data types, i don't think we will be able to know which datatype we should default to and then default it to plain text.

**Comment by sbalaji1192** [comment]
@dilippitchika Usually while guessing types, we should go for a type that is inclusive. For example, if you find a number and string. you can assume that as a string type.
Agreed with only looking at the first few rows to determine the type. In that case, it will be fairly straightforward to implement this.
