### ISSUE TITLE
[Bug]-[60000]:Rest API Under The Authentication tab "Save as datasource" does not look as an Active button

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#12842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user adds an API to the API pane it is observed that the "Save as datasource" appears next to the field. When the user navigates to Authentication Tab and observes the Save as datasource it is observed that the "Save as datasource" is not displayed as active button 

### Steps To Reproduce

1) Navigate to API Pane 
2) Add a API 
3) Navigate to Authentication Tab
and observe the button it is grey colored and does not seem to be active 
![Screenshot 2022-04-12 at 2 55 28 PM](https://user-images.githubusercontent.com/71753653/163791895-4a8331a4-5fcd-4df6-9100-7e12e5b8e963.png)

### Version

Release

**Comment by rohan-arthur** [comment]
Hi @prapullac the screenshot didn't get uploaded, would you please upload it again? Are you referring to these two CTAs:
![Screenshot 2022-04-18 at 11.04.10.png](https://images.zenhubusercontent.com/6196337f2def7ccca841bb55/c48b73a2-3b5f-4b06-9170-f38d6d405490)

**Comment by prapullac** [comment]
@rohan-arthur Yes the button looks inactive we need to make the user feel it is active after adding the API. We can add color and make it feel like a button that is clickable

**Comment by bhairavee23** [comment]
Hello, is anyone working on this? Else I would like to take a stab at it

**Comment by AmanAgarwal041** [comment]
@ChandanBalajiBP is working on this

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.1 |

**Comment by parth-appsmith** [comment]
@rohan-arthur @ChandanBalajiBP the designs for this issue are done. 
Notion doc: https://www.notion.so/appsmith/Inconsistent-CTA-design-on-the-API-pane-fe0913f2e05b415e9d1e0dccbc291f2b

Figma Designs: https://www.figma.com/file/GuqV8Or2PStpE3rTknsDzk/API-Pane-Improvements?node-id=503%3A23251

Zeplin Handoff File: https://zpl.io/9q6Z8lp

**Comment by AmanAgarwal041** [comment]
Re-opening the issue for the design mis-match
