### ISSUE TITLE
[Feature]: Ability to pass cookies to API

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#12858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There's no way to pass cookies to an API via the API pane

### Why should this be worked on?

A discord user wanted to pass cookies to an API to get an access-token in return.
[Here](https://discord.com/channels/725602949748752515/760761686549463060/963395716686946354)'s the link to the message.

**Comment by Nikhil-Nandagopal** [comment]
This is a different problem solved via our SSO feature.
