### ISSUE TITLE
[Docs]: Migrating App from Cloud - Self Host

### ISSUE THREAD

**Issue by vasanthappsmith** [appsmithorg/appsmith#12863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Migrating App from Cloud - Self Host

`[Intercom](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/5269111/conversations/164629100084347)`

### Why should this be worked on?

Needs Documentation.

**Comment by jnikhila** [comment]
The [hashnode](https://appsmith.hashnode.dev/announcing-the-import-export-feature-for-appsmith-applications) link to update docs.

**Comment by sum35h** [comment]
@jnikhila  The doc at the above link needs to be updated. I'll raise a CR on gitbook shortly.

**Comment by sum35h** [comment]
The doc for migration [here](https://docs.appsmith.com/advanced-concepts/more/backup-restore#steps-to-migrate-entire-appsmith-data-onto-instances) seems very old.
@sharat87  Should we update this with the appsmithctl migrate command that geekup had written? or should we use backup and restore to handle instance migration?

**Comment by sharat87** [comment]
No. That document is solving a different problem. It works, only if you have admin control over _both_ the source and destination environments of your migration. Like, I have Appsmith on a server on AWS, and I want to move it to a server on GCP. This is the doc I need. It'll move _all_ users, workspaces, applications, API Keys, configs etc.

But, we obviously can't have that for moving from our prod. This should be solved with a doc that directs users to export just their apps, or connect to Git, and import them on their self-hosted instances.

**Comment by sum35h** [comment]
@sharat87  Sorry for the confusion, although this issue is with respect to cloud to self-hosted migration. 
I saw that the docs [here](https://docs.appsmith.com/how-to-guides/backup-restore) here is actually for server to server migration, where users are directed to use mongodump and copy to new instance with mongorestore.
So, I thought it would be better to update this with the migrate command.

**Comment by danciaclara** [comment]
https://theappsmith.slack.com/archives/C01CFTXD0N8/p1679380329924149

**Comment by danciaclara** [comment]
related - https://github.com/appsmithorg/appsmith-docs/issues/440

**Comment by aunyks** [comment]
Hey y'all, thanks for the awesome product. Can the community help unblock this, or is it pending internal work?
