### ISSUE TITLE
[Template]: Cashflow forecast & reports app

### ISSUE THREAD

**Issue by rochesterj** [appsmithorg/appsmith#12868]
### Title

Cashflow forecast & reports

### Objective

This app can be used for simple cashflow control and projections. It can be used by small companies and entrepreneurs, as a quick alternative to online services.

The app has 2 pages:

Overview:
- Current cash (KPI)
- Cashflow projection for 30 days (KPI)
- Cashflow projection for 90 days (KPI)
- Charts with cashflow projections with many options
- - Select which accounts included in the current chart
- - Select when the chart starts and ends relative to today (including days/weeks/months switcher for easier control)
- - Select to display all transactions, only incoming or only outgoing
- - Select chart period (daily, weekly, monthly)
- Revenues and expenses summary by month

Reports
- Reports page using form filters to view all transactions in a period
- Quick edit option to mark if money was received/paid

The data entry in the example is done using AirTables, but any database can be used.

### Wireframes

https://app.appsmith.com/applications/625331106a70ad452dee556a/pages/625331106a70ad452dee5570

### Validation criteria

* User should be able to control the chart options and see the correct projections
* User should be able to select the month and see the right chart summary
* User should be able to generate reports using the filters
* User should be able to edit the entry using the "edit" button from the table

### Use case

Finance

### Industry

Other

### Data sources

Any

**Comment by Rishabhkaul** [comment]
@GreenFlux @danciaclara Wondering incase this is useful at all for templates
