### ISSUE TITLE
[Feature]: add history.pushState as "Change url params" 

### ISSUE THREAD

**Issue by lublak** [appsmithorg/appsmith#12860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

it would be useful to have a simple function to update the current parameters of the url through a js object {key:value}.
![grafik](https://user-images.githubusercontent.com/44057030/162962497-7fed4b8f-cf9a-4871-a128-1a926e0fb3fc.png)
![grafik](https://user-images.githubusercontent.com/44057030/162963532-753648f5-5dcc-4137-bd80-4aa24c42ff09.png)

Example:
https://app.appsmith.com/app/untitled-application-1/page1-6255724b0d3d384069c022f0
[Tabs.zip](https://github.com/appsmithorg/appsmith/files/8472949/Tabs.zip)

### Why should this be worked on?

To update ruls according to the currently set parameters. Such as tabs.

**Comment by Nikhil-Nandagopal** [comment]
@lublak have you tried simply navigating to the current page with the new params? That should automatically update the query params. This is a sample app that updates the param on the current page
https://app.appsmith.com/app/framework/navigateto-62566b650d3d384069c05830?email=wear
