### ISSUE TITLE
[Docs]: Update setup - Docker Java args

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12873]
Update the [Docker](https://docs.appsmith.com/setup/docker) Docs - 

* Update the docker.env section:
     * Add Appsmith Java Arguments

**Comment by jnikhila** [comment]
@sharat87 - Could you please help us in understanding what details to be added to the docker.env file?

**Comment by sharat87** [comment]
@sum35h, can you help document the env variable you developed for setting custom Java args here please?

**Comment by jnikhila** [comment]
@sum35h - Could you please help on this?

**Comment by jnikhila** [comment]
@danciaclara - As discussed with @sum35h - @sharat87 suggested that this config shouldn't be added to the documentation and can be part of the DevOps team's internal docs. Could you please take this ahead? I'm moving the ticket to blocked status until finalized.

**Comment by danciaclara** [comment]
@sharat87 Shall we go ahead and close this permanently or will we change our stance on whether this should be added to the docs?

**Comment by sharat87** [comment]
@danciaclara, yes, let's close please. Thanks.
