### ISSUE TITLE
[Bug] Intermittent : page gets broken on multiple copy and paste option is used 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1287]
Steps to reproduce:
1) Add a widget
2) Copy the widget 
3) Paste the widget multiple times 
and observe

Observation :
The page is broken 
Please refer the screenshot 
![Screen Shot 2020-10-19 at 6 26 45 PM](https://user-images.githubusercontent.com/71753653/96454627-c146a380-1239-11eb-9143-02b1a9af7ad2.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac is this still valid?

**Comment by prapullac** [comment]
@Nikhil-Nandagopal 
This is not valid as I am unable to reproduce the issue. We can close the issue for now
