### ISSUE TITLE
[Bug]: UI crashes while creating organization when backend server is unavailable

### ISSUE THREAD

**Issue by vishnu-gp** [appsmithorg/appsmith#12882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create an organization from the home page while the server is not available for some reason, UI crashes like this,
<img width="1752" alt="Screenshot 2022-04-12 at 6 34 47 PM" src="https://user-images.githubusercontent.com/9128194/163120166-c2e38c1a-1b37-4b25-a8c9-8235a638cda8.png">

The process can be seen here
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/dd2e01e7c7af47148ebf3f7d33df174a-00001.gif)](https://www.loom.com/share/dd2e01e7c7af47148ebf3f7d33df174a)

Ideally what I expect is the UI to handle these errors properly and show error messages accordingly instead of crashing.

### Steps To Reproduce

1. Goto home page where applications and organisations are listed.
2. Stop the backend server.
3. Click on '+ New Organization' from the left organizations menu.
4. Wait for the API call to fail.

NOTE: Please refer
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/dd2e01e7c7af47148ebf3f7d33df174a-00001.gif)](https://www.loom.com/share/dd2e01e7c7af47148ebf3f7d33df174a)

### Version

Self Hosted - v1.6.19

**Comment by Nikhil-Nandagopal** [comment]
@vishnu-gp I don't think we should handle this. Our server is expected to always be running. There are too many cases to handle if we want to support the server not running so I'm closing this issue

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal This is not true. During deployment or network unavailability, the server can become unreachable or unresponsive. At no point should the client browser crash. This is part of software hygiene that the unavailability of a dependent service should not crash the code. Hence, this should be handled at a global level for consistency across the code base.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit from the screenshot it will not crash in production, it's only showing that because it's in development mode.

**Comment by vishnu-gp** [comment]
@Nikhil-Nandagopal I thought the same and even asked fe-coders before creating the issue.
