### ISSUE TITLE
[Docs]: App theming

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#12883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

App theming feature documentation #3369 

### Describe the improvement

Documentation for new feature

**Comment by dilippitchika** [comment]
@jsartisan @keyurparalkar please review the first draft for theming here 
https://www.notion.so/appsmith/App-Theming-caedc2f85bb34817858b2366b5cb9823

@keyurparalkar i need a list of all the properties in the widgets which we have added newly. Could you please prioritise some time for it?

**Comment by dilippitchika** [comment]
Collating all info - 

1. With theming we have made changes to certain style properties across multiple widgets, here's a list of properties - https://www.notion.so/appsmith/64c8a2fabba54f1e800a3c266f92b326?v=de8b77c3f2944c2dbd6c18a5a4dadca8
2. We also have added a new theme panel in the app where user can control themes and customise them - https://www.notion.so/appsmith/App-Theming-caedc2f85bb34817858b2366b5cb9823


@jnikhila @Pranay105 this is ready to be picked up and the current estimated release date is 11 May 22 🚀 

Please let me know the next steps

**Comment by Pranay105** [comment]
Adding documentation videos now. cc @dilippitchika
