### ISSUE TITLE
[Bug]: UI issue on Add Query for Authenticated API 

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12895]
Please refer to the below screenshot for the UI issue.
![UI-misalignment.png](https://images.zenhubusercontent.com/6203759d49a2167250e9a805/e2ae025c-8f7b-4b94-b3fc-bc8844ac6237)

**Comment by Irongade** [comment]
This PR already fixes this issue, https://github.com/appsmithorg/appsmith/pull/12886
