### ISSUE TITLE
[Bug]: User is unable to add Azure DevOps git repo URL

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2022-04-13 at 1 15 02 PM](https://user-images.githubusercontent.com/13262095/163126492-5ee5dcfd-d2ea-4757-bde6-a10f372b6c6d.png)

### Steps To Reproduce

1. click on `connect git` 
2. paste this URL - `git@ssh.dev.azure.com:v3/hubglobalnz/HubGlobal/AppSmith`

### Version

Cloud

**Comment by AnaghHegde** [comment]
This requires changes from BE as well for url validation. @vishnu-gp Will work on this.
