### ISSUE TITLE
[Bug]-[2760]:JSON form shows error in debugger on first bind

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#12894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JSON form shows that the date of birth field's default value is invalid, even after updating the data

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ac7417a1751046aba81b7eb285cef370-00001.gif)](https://www.loom.com/share/ac7417a1751046aba81b7eb285cef370)

### Steps To Reproduce

1. Add a new json form
2. Bind a query
3. Open debugger and see error
4. Refresh page and notice error goes away

### Version

Production

**Comment by ashit-rath** [comment]
When a path has an error and in certain evaluation cycle the path is removed from the data tree, the path is not removed from the `__evaluation__.errors` object.
This is for all the widgets not just the JSONForm
Steps to reproduce in Table widget

**Comment by bharath31** [comment]
Assuming 10% of users who perform BINDING_SUCCESS with JSON form widget face this issue. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach   | 388 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@bharath31 a better way to check how many users face this - https://mixpanel.com/s/XSxqS

**Comment by bharath31** [comment]
@dilippitchika that looks more accurate. thanks!
