### ISSUE TITLE
[Bug]: Table widget only shows limited rows (first page) even with Pagination disabled

### ISSUE THREAD

**Issue by pallavagarwal07** [appsmithorg/appsmith#12908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I don't know if this is an intended behavior or not (doesn't seem like it, but I'm surprised there's no other issues for it).

If the table component is connected to a datasource, it shows only a limited number of rows - the ones that fit without scrolling - even if pagination is disabled. I'd expect that the first page will be shown if pagination is enabled and all data (scrollable) would be shown if pagination is disabled.

### Steps To Reproduce

Step 1: Create a datasource and connect it to a table. Make sure there is enough data for atleast two pages.
Step 2: Disable client side pagination for the table.

Expectation: The whole list of data is shown (scrollable)
Reality: Only the first page of the data is shown with no way to see the rest.

### Public Sample App

https://app.appsmith.com/applications/62066f5d6b4b1e154a3be83e/pages/6256fbaf0d3d384069c082ab

### Version

Able to replicate on Cloud

**Comment by Nikhil-Nandagopal** [comment]
@pallavagarwal07 you can set the table to enable server side pagination and it will scroll. I agree this is confusing and we should improve it. @dilippitchika instead of server side execution being a switch and having a separate pagination option, can we have a single pagination control that is a dropdown with options for Server Side pagination, Client Side pagination and No Pagination?

**Comment by pallavagarwal07** [comment]
@Nikhil-Nandagopal The sample has server side pagination enabled, but I still can't scroll. Could you post a link to a sample app where scrolling works? Maybe along with the json export of the config? :sweat_smile:

**Comment by dilippitchika** [comment]
@pallavagarwal07 when server side pagination is enabled and the pagination controls are visible, All the records from a query or an API are visible if pageSize is less than the number of records in the query.

Can you please check the app here - https://app.appsmith.com/applications/61e11a42eb0501052b9fab3e/pages/61e11a42eb0501052b9fab41

You should be able to fork it and see the behavior

**Comment by dilippitchika** [comment]
Closing this and creating a new issue based on Nikhil's comment
