### ISSUE TITLE
[Bug]: Custom charts fail to load when you move to another page

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#12905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In both edit and deployed mode, the custom chart stops loading when you move between pages. 

Error in Console attached below
<img width="536" alt="Screenshot 2022-04-13 at 1 16 21 PM" src="https://user-images.githubusercontent.com/32227135/163198504-9fb21f59-841b-404b-b434-5313a73d5dbd.png">

### Steps To Reproduce

https://app.appsmith.com/app/mapping-test/page2-625675ce0d3d384069c05c38

- Hard reload on Page 2 
- Goto page 1,
- Come back to page 2
- Observe that the chart fails to load any data now on both the pages

### Public Sample App

https://app.appsmith.com/app/mapping-test/page2-625675ce0d3d384069c05c38

### Version

Cloud/Self-Hosted - v1.6.20

**Comment by dilippitchika** [comment]
@Bhavin789 can you please add your findings here, this is a high priority issue.

**Comment by techbhavin** [comment]
In My Observation, Look Like there is a specific issue with the given applications. 

Below I tried to create the same application which is using the chart widget and here I am not able to reproduce the same issue

Public App 
https://release.app.appsmith.com/app/mapping-test/page2-625d3a1577c4e778bb8107ea

**Comment by Nikhil-Nandagopal** [comment]
@techbhavin @danciaclara is this issue reproducible?

**Comment by techbhavin** [comment]
@Nikhil-Nandagopal,

Yes, this issue is reproducible, a chart is failing when an action connector is failed . after that all application chart is not able to load. 

@somangshu  @dilippitchika  can we bring someone who has a better idea on connector and data binding.

**Comment by dilippitchika** [comment]
@somangshu please help move this forward. Do we need someone from BE coders here?

**Comment by somangshu** [comment]
@Rishabh-Rathod can you check for the related issue here, Its the API which fails and then cause the chart to not load. 
Alternatively can you point me to the person who can best solve this?

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod can you check for the related issue here, Its the API which fails and then cause the chart to not load. Alternatively can you point me to the person who can best solve this?

Ideally in all cases, if API returns valid data or not, the Chart widget shouldn’t be crashing correct? @somangshu 

About the API failure, let me check the application. @techbhavin Can you please invite `support@appsmith.com` to the app?

**Comment by somangshu** [comment]
This is not a critical issue, the api is the actual cause and the user was able to resolve it, We are looking into this priority to resolve. Changing the label now

**Comment by jsartisan** [comment]
Another way to repro it without using any query/action:

1. Drop chart widget
2. Select custom chart type
3. In the `Custion Fusion chart` input, use this value
```
{
  "type": "dragnode",
  "dataSource": {
    "chart": {
      "caption": "",
      "arrowatstart": "0",
      "arrowatend": "1",
      "viewMode": "1",
      "showRestoreBtn": "1",
      "connectorToolText": "$label",
      "theme": "fusion"
    },
    "dataset": [
      {
        "id": "1",
        "seriesname": "S1",
        "data": []
      }
    ],
    "connectors": [
      {
        "stdthickness": "2",
        "connector": []
      }
    ],
    "annotations": {}
  }
}
```

Now fusioncharts won't just load. even for new chart widgets.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal can you elaborate on why this was closed?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu i thought it was fixed. Is it not yet?

**Comment by somangshu** [comment]
nope @Nikhil-Nandagopal, core challange is with the fusion chart library, they do not validate and the properties that are sent in there object, hence they crash, we can only cover a few cases (which we did)

Also, Fusion chart SDK does not have separate instances of the widget in an app, this leads me to believe that one crash crashes other instances of the chart widget as well. 

Our fix is to move away from Fusion chart as part of #4437

**Comment by rajatagrawal** [comment]
> 

@danciaclara can you please share json version of the app where this issue is repro'ed ?

**Comment by rajatagrawal** [comment]
> Another way to repro it without using any query/action:
> 
> 1. Drop chart widget
> 2. Select custom chart type
> 3. In the `Custion Fusion chart` input, use this value
> 
> ```
> {
>   "type": "dragnode",
>   "dataSource": {
>     "chart": {
>       "caption": "",
>       "arrowatstart": "0",
>       "arrowatend": "1",
>       "viewMode": "1",
>       "showRestoreBtn": "1",
>       "connectorToolText": "$label",
>       "theme": "fusion"
>     },
>     "dataset": [
>       {
>         "id": "1",
>         "seriesname": "S1",
>         "data": []
>       }
>     ],
>     "connectors": [
>       {
>         "stdthickness": "2",
>         "connector": []
>       }
>     ],
>     "annotations": {}
>   }
> }
> ```
> 
> Now fusioncharts won't just load. even for new chart widgets.

@jsartisan Would you happen to remember the missing key/values in this json structure that would make the chart widget work in this case ?
