### ISSUE TITLE
[Bug] Intermittent : User is displayed with an error message on application load 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1290]
Steps to reproduce
1) Navigate to homepage
2) Click on application edit button 
and observe

Observation
It is observed that an error message is displayed to user on application edit 
![Screen Shot 2020-10-19 at 7 11 27 PM](https://user-images.githubusercontent.com/71753653/96464507-85b1d680-1245-11eb-95a7-01f343a89eaf.png)
![Screen Shot 2020-10-19 at 8 14 29 PM](https://user-images.githubusercontent.com/71753653/96466698-bd218280-1247-11eb-8920-e5ba720a855d.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac is this always happening? Is the query configured correctly?

**Comment by prapullac** [comment]
@Nikhil-Nandagopal : This is nothing to do with the query table as I have not added on load action setting for the query. When I open the application I see this error and its intermittent as mentioned in the summary

**Comment by Nikhil-Nandagopal** [comment]
@prapullac is verified this is because there is a query select * from users in your app without a limit which is leading to a timeout

**Comment by prapullac** [comment]
Reopening the issue and Please do refer the video 
https://www.loom.com/share/55f2c407124e4f03b365ae7452cf86a1

**Comment by prapullac** [comment]
Verified the issue and working as expected
