### ISSUE TITLE
[Bug]: Auto Scroll is not happening for dropping widget inside container type widgets

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#12902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7e86e831df42465685bfa57ccef9ecc3-00001.gif)](https://www.loom.com/share/7e86e831df42465685bfa57ccef9ecc3)

### Steps To Reproduce

1. Add container widget onto canvas
2. Place it towards bottom of the canvas to observe the issue
3. Add any other widget onto canvas. eg- Document viewer widget
4. Try to drag and drop Document viewer widget inside container widget as shown in video and observe that Auto-Scroll doesn't happen in canvas

### Version

Cloud/Production

**Comment by rohitagarwal88** [comment]
@rahulramesha/ @riodeuno : When the container/or any widget is moved to the bottom that pushes the canvas to scroll. The jittery experience is observed.

https://www.loom.com/share/330f1392cd6e49339a1449744be524dc

**Comment by rohitagarwal88** [comment]
@Sripriya93 : can I close this issue?

**Comment by Sripriya93** [comment]
@rohitagarwal88 Yes. We can close this issue.
