### ISSUE TITLE
[Bug]: input values getting truncated 

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

User reported issue, and prima facie this seems to be unrelated to #12318 

1. application has a form with some input fields and a submit button
2. when user enters some values in these widgets and clicks submit, an insert query is called
3. sporadically, the values from these inputs are truncated. For example, "Hotel" is stored as "Ho", and "200" is stored as "2"

please note: The user is directly using the format `input1.text` to access these values in the insert query, and they don't use any store values.

Some things we investigated along with the user:
1. the problems occurs randomly, on random fields
2. this is not related to delay time, because even if the user waits 1 minute before submitting the form, sometimes the truncated values are being persisted to the db

PS: I have a copy of the app json if needed.

### Steps To Reproduce

explained above

### Version

Cloud

**Comment by SidHiremath** [comment]
It is dangerous bug when we we are building the critical application(related to financial apps),  Could you please fix this as soon as possible within some time or so.

**Comment by rohan-arthur** [comment]
@SidHiremath thank you for your comment. We are currently trying to find a way to reproduce this, do you see this issue in your apps as well? If yes, do you mind doing the following: 
1. invite support@appsmith.com to your org
2. share the app link and steps to reproduce the error here

**Comment by Rishabh-Rathod** [comment]
@sbalaji1192  Can you add steps to reproduce for this issue.

**Comment by sbalaji1192** [comment]
@Rishabh-Rathod I was able to repro this issue consistently by swiping the keys from 1 to 9 rapidly.

**Comment by Rishabh-Rathod** [comment]
Steps to reproduce 
- Open Sample complex application ( Ask @Rishabh-Rathod for access )
- Go to the “Configuration Details” page -> “Segmentation Config” tab.
- Click on the “Add sample data” button to add data to the table.
- Once data is populated, click on the “Edit” button inside the table to open the modal.
- If you edit any Input in the modal, the binding is not getting reflected in the Text widget at the bottom.
Also noticed a lot of delay in loading the widgets and opening the modal

When tried swiping the keys from 1 to 9 rapidly, we saw the truncation issue was reproducible.

**Comment by SidHiremath** [comment]
When this will be fixed?   

Kindly request that this is something that should be fixed as early as possible or right away as it might cause data issue!

**Comment by Rishabh-Rathod** [comment]
This is already worked on https://github.com/appsmithorg/appsmith/pull/13084 and the solution is in the testing phase. 
This will soon be fixed in production. 
@SidHiremath
