### ISSUE TITLE
[Bug]-[424]:The open repo navigation is broken in git pull request

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Pull conflict when the user clicks on the Open repo link the user is navigated to the application instead of the git repo
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/163320604-b622d2d1-120a-40c7-bfbb-bed74d98c7b0.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/163320626-93372b89-1f3f-41d6-9fd3-3e233906e0f5.png">

### Steps To Reproduce

1. connect the application to the git 
2. Now create a pull conflict in the master branch 
3. When the conflict pop up comes up with open repo link 
4. click on open repo link
5. The user is navigated to new app page instead of the git repo

### Version

release

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 53 |
| Effort (months)  | 0.25 |
