### ISSUE TITLE
[Bug]: Can't call the camera in iframe

### ISSUE THREAD

**Issue by hillsonzhang** [appsmithorg/appsmith#12924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using the iframe widget, can't call the camera in iframe

### Steps To Reproduce

1.iframe URL : https://blog.minhazav.dev/research/html5-qrcode.html

### Version

Self Host 1.6.6

**Comment by btsgh** [comment]
Accessed the url mentioned in the bug description through iframe widget, and camera is now working both on canvas and on deploy.
