### ISSUE TITLE
[Bug]: Signing up with a redirect url navigates to a 400 page.

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#12926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to signup from a public app redirects the user to a 400 page.

### Steps To Reproduce

1. Visit a public app without being signed in.
2. Click on sign in at the top right.
3. Move to sign up page from login screen.
4. Enter email and password and click on signup.
5. Redirected to a 400 page.

https://user-images.githubusercontent.com/67054171/163342109-ff516726-44b8-417c-aa69-ca8a5dfd2338.mov

This happens on prod when recaptcha is enabled. It works as expected when recaptcha is disabled. When recaptcha is enabled the recaptchaToken is added as a query param to the redirect url so it could be related to query param parsing. 

Also happens while forking https://github.com/appsmithorg/appsmith/issues/11745#issuecomment-1097805745 where there is a redirect url.

### Version

Cloud - 1.6.20

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk can this be closed?

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi @akash-codemonk can we close this ASAP? It's been open for too long

**Comment by akash-codemonk** [comment]
Closed with https://github.com/appsmithorg/appsmith/pull/15074.
