### ISSUE TITLE
[Bug]: Opening https://app.appsmith.com/templates or any subdomain of this doesn't redirect to a login page

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#12920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user tries to open https://app.appsmith.com/templates or any subdomain (any template directly) while not logged in, The user isn't redirected to the appsmith login page, but is instead shown a "Page not found error"

https://user-images.githubusercontent.com/20532920/163328123-b46fed25-18e7-4fcf-8818-16ae807a3494.mov

### Steps To Reproduce

1. Open a private window
2. Enter the link https://app.appsmith.com/templates
3. observe the error message

### Version

Cloud - 1.6.20

**Comment by ramsaptami** [comment]
Still seeing the `page not found` page instead of being rerouted to login page
