### ISSUE TITLE
[Type]-[604]:Property Pane mount takes around 600-700ms

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Event - Click on Input Widget on Canvas.

Each codemirror component itself takes around 50-100 ms.

<img width="1492" alt="Screenshot 2022-04-15 at 1 42 00 AM" src="https://user-images.githubusercontent.com/23132741/163517596-8b78c4c3-9467-4618-9bb5-e16fbfbc42e8.png">
<img width="558" alt="Screenshot 2022-04-15 at 9 23 09 AM" src="https://user-images.githubusercontent.com/23132741/163517662-ae16b4b1-2e68-41b6-862f-71e136f29cc9.png">

**Comment by Rishabh-Rathod** [comment]
Quoting @SatishGandham message from slack
```
1. Code editor is the expensive one here. It will get slower if the widget has a lot of JS options enabled.

2. mounting is heavy, so we wont mount.
We can have a wrapper component which does this
{{isFocused && <CodeMirror />}}
{{!isFocused && <TextArea />}}
```

**Comment by somangshu** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 302 |
| Effort (months)  | 1.0 |

**Comment by somangshu** [comment]
@Rishabh-Rathod @arunvjn is this related to #11040

**Comment by Rishabh-Rathod** [comment]
@somangshu both are performance issue with property pane but different.

This issue is related to how heavy/slow mounting property pane is.

Other issue is how slow updating values in property pane is.

**Comment by Rishabh-Rathod** [comment]
Ideally, it shouldn't take more than 50ms to mount property pane.

**Comment by somangshu** [comment]
We are talking this improvement in #13112, it will be tracked there, closing this for now
