### ISSUE TITLE
[Bug]: The application breaks when the user deletes the main branch after changing the default branch

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The application breaks when the user deletes the main branch after changing the default branch

### Steps To Reproduce

1. Connect the application to the git
2. now create a new branch 
3. From the remote chnage the default branch from master to newly created branch
4. Now delete the main branch 
5. The application breaks

### Version

release

**Comment by AnaghHegde** [comment]
@RakshaKShetty I looked at release env and found a different issue. After updating the default branch the delete branch, we are unable to delete the master branch. I will be closing this. 
https://www.loom.com/share/a258959e14434c8fa1936fd815b3b194

**Comment by AnaghHegde** [comment]
Closed via https://github.com/appsmithorg/appsmith/pull/11549
