### ISSUE TITLE
[Bug]-[11200]:Show filepicker to upload self signed certificates

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#12948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Current Behavior**
Filepicker to upload `Self signed certificate` show up for a specific selection, AuthType `OAuth2.0` and Grant Type `Authorization Code` and Use Self-signed certificate:`yes`.

**Required behavior**
Show to upload `Self-signed certificate` irrespective of the user  inputs.

### Steps To Reproduce

1. Go to APIEditor
2. Select AuthType `OAuth2.0`
3. Select Grant Type `Authorization Code`
4. In Advanced Settings `Use Self-signed certificate` select yes
5. The filepicker show to upload `Self-signed certificate` shows up now.

### Version

Cloud

**Comment by rohan-arthur** [comment]
REST 6m usage: 3500
assume 40% requirement: 1400

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1400 |
| Effort (months)  | 0.25 |
