### ISSUE TITLE
Doc : Add documentation for integrating with SAML on Appsmith

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#12941]
As part of this exercise, we should aim to add a generic document + some helpful guides in integrating for SAML SSO using famous identity providers like Okta, Auth0, PingID, Active Directory, etc.

**Comment by jnikhila** [comment]
SAML and Auth0 configurations published.

**Comment by jnikhila** [comment]
[SAML Docs](https://docs.appsmith.com/setup/instance-configuration/single-sign-on-sso/security-assertion-markup-language-saml) published on live.
