### ISSUE TITLE
[Task]: Prevent the layers on top of widgets from rendering in edit mode

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#12949]
In edit mode each widget has these 9 layers on top of it.

- PositionedContainer
-  SnipeableComponent
- DraggableComponent
- WidgetNameComponent
- ResizableComponent
- OverlayCommentsWrapper
- PreventInteractionsOverlay
- PreviewModeComponent
- ErrorBoundary

Whenever you change a property in the property pane, or edit a meta property  all these layers render for all widgets on the canvas and none of these have to re render.

Though this PR handles most of the issues with wasted widget renders #12727, we will still have a problem when there are lot connected widgets. For example a large form widget depending on the table selected row or list widget active item.

**Proposed solution**

Refactor the getWidgetView in BaseWidget class and 

- Fix the selectors used by all the layers to prevent wasted renders.
- Memoize the positioned containers style calculation.
- Inline the components instead of call them as functions [Not sure this step is required]

**Comment by SatishGandham** [comment]
Some changes to baseWidget to getStarted
https://gist.github.com/SatishGandham/421f696f36cab97263471348ea780dfb

**Comment by prsidhu** [comment]
Expected gains from this effort:
~ 50% reduction in scripting time.

Current scripting time for A force app on my system : ~400ms.
Scripting time after removing all HOCs in basewidget: ~200ms. (Max possible improvement)
