### ISSUE TITLE
[Docs]: How - to Guide - SQL Procedures

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12942]
A guide explaining how to trigger procedures from Appsmith.
We can update the existing [doc](https://docs.appsmith.com/learning-and-resources/how-to-guides/returning-data-from-a-stored-procedure)

**Comment by jnikhila** [comment]
@ajinkyakulkarni / @hiteshjoshi / @rohan-arthur / @somangshu - Need help from engineering team to document this. Could you please assign it to an engineer for first draft or add pointers to the ticket?

**Comment by jnikhila** [comment]
@nidhi-nair - Could you please share a first draft and a loom video for this?

**Comment by danciaclara** [comment]
We will picking this up as part of Top guides project
