### ISSUE TITLE
[Bug]-[5760]:Created API does not save body if raw type is selected with no headers

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#12956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Body Values are not being saved if the headers are empty and raw type is selected for body tab.
https://user-images.githubusercontent.com/7565635/163555189-557f3734-3a60-4ee4-92ed-fa0548d31cd2.mov

### Steps To Reproduce

1. Create an API
2. Go to body tab
3. By default the selected type is `raw`
4. Write something, wait for 2-3 secs and reload
5. Check the data is not saved

### Version

Release

**Comment by rohan-arthur** [comment]
REST 6m usage: 3600
assume 20% requirement (body type raw): 720

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 720 |
| Effort (months)  | 0.25 |
