### ISSUE TITLE
[Bug] : OAuth2- Authenticated API | Client Credentials

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#12957]
The datasource creation when selected grant type as Client Credentials fails.

Scenario 1 - The datasource creation happens but it suddenly starts failing with  and then you are no longer able to add the datasource.

`{"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}`

Scenario 2 - When the datasource is created and you would try to update it, the save and re-authorize will not work and throw below exception.
![image.png](https://images.zenhubusercontent.com/6203759d49a2167250e9a805/7b65a6f1-18d5-4ce7-a6cb-88ca11173d0c)

At the moment, due to these bugs a user will not be able to proceed and is blocked for client credentials flow.

**Comment by sh-TU** [comment]
I encountered this issue as well. From the logs, it seems appsmith is expecting a refresh token but according to the oauth2 specs, client credentials shouldn't have a refresh token.

**Comment by kavhad** [comment]
Also encountered this issue. I'm using AWS Cognito service for authentication and authorization and OAuth2 as protocol. I concurr with @sh-TU appsmith should only expect and use the accessToken in client credentials flow.

**Comment by rohan-arthur** [comment]
what is the event that we raise for this error? I tried this filter and it gave me only one result in the past year, so it looks wrong: 
![Screenshot 2022-04-18 at 11.19.22.png](https://images.zenhubusercontent.com/6196337f2def7ccca841bb55/66691a87-aa3f-4446-956d-f722fdb488ec)

**Comment by rashmi-rai** [comment]
There are two issues in the here:
- API is returning this error `Bad Request: Malformed parameter 'resource' for DatasourceController.update`
- Remove `Save and Authorise` button for `Client Credentials` Grant Type

**Comment by nidhi-nair** [comment]
More information on the issue on [this](https://discord.com/channels/725602949748752515/760761686549463060/965894785669939230) Discord thread.
