### ISSUE TITLE
[Bug]: DataTreeFactory.create takes >300ms for complex application

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Terminology
`DataTree` in appsmith is the object which has all widgets, actions, and JS objects evaluated data + configuration data.

To get this `dataTree` we create an unEvalDataTree using `DataTreeFactory.create` and pass it to the worker.
The worker then gives us an evaluated `dataTree`.

#### `DataTreeFactory.create` 
Currently on change of the any of the below values, we re-run `DataTreeFactory.create` again
- actions
- jsActions
- widgets
- widgetsMeta
- pageListPayload
- appData
- editorConfigs
- pluginDependencyConfig

This is a heavy process, below is example of complex application where we noticed this took 370 ms on main thread
<img width="1434" alt="Screenshot 2022-04-16 at 2 48 52 PM" src="https://user-images.githubusercontent.com/23132741/163669798-bd45f00a-95a7-4ae0-b8a9-2b297b8bb565.png">

### Steps To Reproduce

1. Open Sample complex application ( Ask @Rishabh-Rathod  for access  )
2. Go to the “Configuration Details” page -> “Segmentation Config” tab.
3. Click on the “Add sample data” button to add data to the table. 
4.  Once data is populated, click on “Edit” button inside the table to open the modal.
If you edit any Input in the modal, the binding is not getting reflected in the Text widget at the bottom.
Also noticed a lot of delay in loading the widgets and opening the modal

### Version

1.6.20

**Comment by Rishabh-Rathod** [comment]
The above issue contributes a huge role in causing this https://github.com/appsmithorg/appsmith/issues/12318.

Assuming that for this complex application. We want the evaluated data tree back from the worker in 200ms, after the user types in a widget to reflect that in bindings.

- Current worker time to evaluate changes is ~178.32 ms. 
<img width="502" alt="Screenshot 2022-04-16 at 3 16 49 PM" src="https://user-images.githubusercontent.com/23132741/163670365-844a137d-bfb4-4611-9ef4-4ef65e915cf2.png">

- 200ms - 178ms = 22ms to finish `DataTreeFactory.create` with the assumption that nothing else is happening on the main thread.
- Currently, `DataTreeFactory.create` takes ~370ms which is more than double the time worker takes for evaluation of changes.

Ideally, This function should not take more than 20 ms, if we need to reach a 200 ms response experience in binding widgets. 

Obviously, we will also need to optimize our evaluation but as this takes double the time, we need to prioritize it.

**Comment by SatishGandham** [comment]
Major part in the creation of uneval tree is `generateDataTreeWidget` since the widgets don't change very often, memoizing it will give us the results we are looking for.

Improvement will be very prominent on complex large apps making lot of API calls and slower systems.

**Things to consider**

- Since we can not have an infinite cache, we should find a way to set the cache size dynamically based on the number of widgets on a page. We can set it to a reasonably large number, but then we will be wasting memory unnecessarily.
