### ISSUE TITLE
[Bug]: Users are not able to delete the branch which has been changed from the default branch 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Users are not able to delete the branch which has been changed from the default branch 

### Steps To Reproduce

1. Connect the application to the git
2. now create a new branch
3. From git hub change the default branch to the newly created branch b1
4. Now come back to the application sync the branch
5. now master branch will be removed as a default branch
6. Now try to delete the master branch 
7. The error is displayed as 
8. the error is displayed as cant delete the branch
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/163774158-7ed6bcaa-7766-4ad9-b126-2f4f4063aabd.png">

### Version

release

**Comment by vuiets** [comment]
This doesn't break the person's app so bumping down the priority on this.
