### ISSUE TITLE
[Bug]: [Regression] Internal server error when saving a OAuth2 datasource

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#12983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to connect to zoho crm with OAuth 2.0. When I enter all the fields and click "Save and authorize", I see an internal server error. Video:

https://user-images.githubusercontent.com/94514895/163767994-24c9be9b-03b8-4c17-a9c5-a65144f19fc9.mov

error message: `{"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}`

### Steps To Reproduce

described above, I can share credentials if needed.

### Version

Cloud

**Comment by prapullac** [comment]
Error message is not displayed  appropriately 
![Screenshot 2022-05-09 at 4 10 33 PM](https://user-images.githubusercontent.com/71753653/167394077-c860ea31-af9b-4340-b27d-06028125054a.png)

**Comment by prapullac** [comment]
Closing the current issue as the above-mentioned issue is not related.
