### ISSUE TITLE
[Bug]: "Unexpected error" is shown for empty organization name

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

"Unexpected error" is shown for empty organization name
![image](https://user-images.githubusercontent.com/92293815/163791878-bd6e1f18-03db-491c-9bfc-16ec4570af8c.png)

### Steps To Reproduce

1. Go to Release
2. Click on three dots next to the organization > Settings
3. In General page remove the Org name.

### Version

Cloud

**Comment by vishnu-gp** [comment]
@shwetha-ramesh This fix is to handle the issue from the backend. I believe there should be a frontend validation also needed here.

**Comment by vishnu-gp** [comment]
@shwetha-ramesh With the backend fix https://github.com/appsmithorg/appsmith/pull/12805, empty org names won't get saved. To handle this error we would need a frontend validation or error handling when an empty name is passed.

**Comment by trishaanand** [comment]
Not a regression. This today happens for all backend thrown errors when displayed on client. Removing "Regressed" label.
