### ISSUE TITLE
[Bug]: First step of the welcome tutorial throws error

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#12993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

First step of the welcome tutorial throws error

![image](https://user-images.githubusercontent.com/92293815/163785230-1b89f2d4-4620-453c-96af-db543134ed88.png)
![image](https://user-images.githubusercontent.com/92293815/163785270-996617da-b83c-4a0b-b264-4f1fd6107529.png)

https://loom.com/share/438562da130840e198efe9e937fa298b

### Steps To Reproduce

1. Create a new user
2. Start the welcome tutorial 

### Version

Cloud

**Comment by akash-codemonk** [comment]
This should be fixed now. Context https://theappsmith.slack.com/archives/CGBPVEJ5C/p1650264061622499.
