### ISSUE TITLE
[EPIC]-[6000]:Templates Phase 2

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13005]
### Objective

The objective of phase 2 is to enhance the existing template reach from just making these apps forkabe and accessible  within Appsmith to truly integrating them. To achieve this, we have identified the following key areas where we can implement new user flows to make templates and more effective:

- Allowing the user to access templates from within the canvas, allowing them to add/merge a template into an existing application To achieve this, users can access the list of templates within the new app or the new page flow. Users will be able to quickly browse a template and import it into their apps
- Rather than forcing a user to import a whole application into their organisation, and then starting to build from there, or copy elements from there, a user should be able to import just the specific parts of the template that they need into their app.
- Adding in support for the Sample apps available in our documentation. We have to build a process around the documentation of this, to make the results accessible to all users, as well as fitting the current template requirements and standards

### Success Metrics

| Goal          | Metric         |
| ------------- | -------------- |
| Simplify user experience  | Increased count of templates  |
| Simplify user experience  | Increased template forking|
| Simplify user experience  | reduce time taken to build apps|

### Requirements

| Requirement   | User Story    |
| ------------- | ------------- |
| Must reduce time taken to build apps  | a user must be able to build apps faster |
| Must improve access of templates to users | the user must have access to templates within their canvas  |
| Must improve access of templates to users | the user must be able to add templates to existing apps  |

### Developer Handoff Document in Figma

https://app.zeplin.io/workspace/6253e6ecf6f33f6c80df2df4/projects?seid=629ed3d2967eeb127728e1fb

### Deploy preview

https://appsmith-dv0377c0i-get-appsmith.vercel.app/

### RACI matrix

| | |
| ------------- | ------------- |
| Responsible | @akash-codemonk , @nayan-rafiq |
| Accountable | @kocharrahul7, @RoopKrrish9696 |
| Consulted | @Nikhil-Nandagopal, @mohanarpit, @areyabhishek|
| Informed |  |

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3000 |
| Effort (months)  | 1 |

**Comment by vinay-appsmith** [comment]
@kocharrahul7 Reduction in time spent in creating their app UI should also be tracked. That is also an indicator of success in using templates.

**Comment by kocharrahul7** [comment]
@vinay-appsmith updated as requested

**Comment by RoopKrrish9696** [comment]
Design review for the latest [DP](https://appsmith-p31woqcdj-get-appsmith.vercel.app/) above: cc @kocharrahul7 @akash-codemonk 

1. Gap between canvas and the two cards should be corrected.
2. Canvas width should be matched with the cards.
3. The new page drop-down should be updated according to the zeplin.
4. The helper text for the "add button" should be corrected acc to zeplin.
5. Search should be sticky in the modal, please refer zeplin once.
6. Height of the sticky navbar in the template description page should be fixed ( decreased ).
7. Remove bg-color for the similar templates section.
8. The gap between "select all" and "checkbox" should be decreased.
9. The scroll bar should be fixed here acc to DS. https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=4998%3A24582a

**Comment by RoopKrrish9696** [comment]
Design review for latest [DP](https://appsmith-doldixj5g-get-appsmith.vercel.app/): cc @kocharrahul7 @akash-codemonk 

1. The inactive filter state  - the stroke colour for the checkbox is black but should be grey, please refer to zeplin once.
2. Also, the padding between the last similar templates section and the above section is less, please check once.
