### ISSUE TITLE
[Bug]: Select query failed toast is displayed even when the crud page is generated successfully

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Select query failed toast is displayed even when the crud page is generated successfully
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/163805036-7ae0c2b1-0cae-418c-8c19-7d5e13786e89.png">

### Steps To Reproduce

1. use a sample mongo data source
2. under active tab click on generate page
3. Select the table name generate a crud page
4. the select query failed toast is displayed even when the crud page is successfully created

### Version

release

**Comment by abhvsn** [comment]
@Rishabh-Rathod can you please check on this seems like a client-side issue for `onPageLoad`

**Comment by Rishabh-Rathod** [comment]
@abhvsn @RakshaKShetty 
This seems to be an issue with the debugger showing incorrect errors as the query is executing and the table is getting data back. Doesn't seem like the query actually failed. I tried it on release, and in my case also in-network call query executed as expected.

**Comment by nidhi-nair** [comment]
@Rishabh-Rathod is there some backend fix required here? AFAICT the execution was successful? Could you please provide some more context to what the issue is here?

**Comment by ohansFavour** [comment]
@nidhi-nair No, this is a client-side issue.
