### ISSUE TITLE
[Feature] HubSpot CMS Domains API Saas Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13026]
### Description: 

These endpoints allow you to return information about the domains connected to a particular HubSpot CMS site. You can return data for a list of domains or specify a domain by ID.

------------------------
### Documentation:

https://developers.hubspot.com/docs/api/cms/domains

------------------------
### TO-DO

------------------------
### API Actions Progress
| Action                             | EngSpec Doc | SaaS Manager App | SaaS App Run | Test App Run | QA  |
| ---                                | ---         | ---              | ---          | ---          | --- |
| Get Current Domains                | Yes          | Yes               | Yes           | Yes          | No  |
| Get Single Domains                 | Yes          | Yes               | Yes           | Yes           | No  |
 
------------------------

**Comment by prapullac** [comment]
HUBSPOT issues :
CMS Domin:
1. Domain ID field in Single Domains option is confusing as the results contain domain and Id Separately : we need to use ID instead.
2. When user adds Syntax wrong we have show error.  https://www.loom.com/share/e4cda3f4447c4918a3856db9e6ccd51f
3. Some fields need to be defined well ex: Current domain method and as we scroll below we simple see “After” and “Before” option. Does not give a definition nor a syntax of its behaviour 
4. Tooltip must be added 
5. In “Single Domain” method even without adding data into the mandatory field  the user is displayed with Results 
6. Limit has an issue (need more clarity for ensure it is an issue)

**Comment by felixsuarez0727** [comment]
HubSpot CMS Files Observations

 | #|Question/Observation | Related Issue | Resolved |
|---| ---                                | ---         | ---              |
|1| Domain ID field in Single Domains option is confusing as the results contain domain and Id Separately : we need to use ID instead.  | [#13906](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13906) | Yes |
|2|When user adds Syntax wrong we have show error.  |   [#13909 ](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13909)    |No|
|3|Some fields need to be defined well ex: Current domain method and as we scroll below we simple see “After” and “Before” option. Does not give a definition nor a syntax of its behaviour | [#13910](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13910) |Yes |
|4|Tooltip must be added |[#14296](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13911)| No|
|5| In “Single Domain” method even without adding data into the mandatory field the user is displayed with Results | [#13911](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/13911)| Yes |
|6| Limit has an issue (need more clarity for ensure it is an issue) |- | No|

Updates about observations

1. I have changed the Domain ID to ID only
2. We need to do more research on the problem
3. Tooltip and subtext added for better understanding
4. We are working on it
5. I found that the problem is because GET
/cms/v3/domains/ is the Api of Current Domain so when you do not put the ID is not a problem for the system because recognize like a Current Domain. I make the decision of change the ID to not required this means in both cases they have to work.
6. I don't understand this comment, could you explain it to me

**Comment by prapullac** [comment]
@felixsuarez0727 : Verified the issue on the Hubspot DP
