### ISSUE TITLE
[Bug]-[30000]:[UI] Spacing in RUN button in the Query response pane

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bad spacing between “🙌 Click on RUN after adding your query”. Add space on both sides of the RUN button. 
<img width="297" alt="Screenshot 2022-03-29 at 11 46 07 AM" src="https://user-images.githubusercontent.com/94514895/163827687-f2a41405-553f-480a-9675-e18ec0fde300.png">

### Steps To Reproduce

1. create a query
2. look in the bottom half to see the message described above

### Version

Cloud

**Comment by rohan-arthur** [comment]
reach 12000

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.10 |
