### ISSUE TITLE
[Feature]-[30000]:Query pane - context menu is outdated

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The context menu that opens up by clicking on the three-dot menu is outdated. It should be the same as the menu that opens from the explorer. 
<img width="270" alt="Screenshot 2022-03-29 at 11 44 54 AM" src="https://user-images.githubusercontent.com/94514895/163826055-2426a45e-f26d-46a7-9eb3-896c650244e4.png">

![Screenshot 2022-04-18 at 20 21 22](https://user-images.githubusercontent.com/94514895/163826193-d5540749-3bdd-4690-b036-34a5d9e3c20d.png)

### Steps To Reproduce

1. check context menu in query pane --> this is outdated
2. compare with context menu in entity explorer --> this is the updated one

### Version

Cloud

**Comment by rohan-arthur** [comment]
reach: 12000

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.10 |

**Comment by ChandanBalajiBP** [comment]
@parth-appsmith need more clarity to address this issue.

**Comment by rohan-arthur** [comment]
won't fix in isolation, this should be part of [phase 1 strategy](https://www.notion.so/appsmith/Data-strategy-f5cf65284b9b44edb9d737e793523b02?d=4750ce446ed246e6919123875f5d73cc#c24a27ab4c3540b6a91012a99792ee83)
