### ISSUE TITLE
[Bug] Same user can be invited on share and no error message is displayed to user 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1302]
Steps to reproduce:
1) Navigate to home page 
2) Click on Share option
3) Add and email Id (Ensure the user is already invited)
4) Select a role 
6) Click on invite 
and observe

Observation:
It is observed that the user has been successfully invited 

Expectation:
An error message stating the user is already invited must be displayed to user.

**Comment by mohanarpit** [comment]
@prapullac I'm closing this issue because it's expected behaviour. Even if the user exists in a particular organization, we don't want to throw any errors and want to seamlessly let the request go through. Throwing an error in this scenario is not the desired UX.
