### ISSUE TITLE
[Feature]: Combobox - Allow user to type their own options in Select widgets.

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#13037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a developer, I would like to allow my users to enter their own custom entries into a Select widget. In the even that a user searches the Select widget and their typed option doesn't exist, pressing Enter should add the typed option to the widgets options.  It may need a corresponding `onNewOptionAdded` or similar event to control the value/label that gets assigned to the new option.

### Why should this be worked on?

Say we have a list of tags. If the user cannot find the Tag they are searching for then they should be able to type a new one. The same could be said for any variable list of items.

**Comment by dilippitchika** [comment]
Closing in favour of https://github.com/appsmithorg/appsmith/issues/6928

**Comment by Naik1994** [comment]
Hi Team,
 
This thread marked as closed but the requested feature is still not achievable using other solutions provided in different tagged issues. Is this planned in any future release or can we please work on this ?

**Comment by somangshu** [comment]
We are going to be releasing custom widgets soon. That way, you can easily implement any widget on appsmith quite easily. 
This is planned to be generally available end of this quarter or early next one.

**Comment by Nikhil-Nandagopal** [comment]
@Naik1994 this was closed in favour of #6928 which is the same feature request. You can track that.
