### ISSUE TITLE
[Bug] No "back to home" CTA on 500 page

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#1303]
## Description

https://app.appsmith.com/500 does not have any call to action for users to navigate back/reset their state.

## Solution

Add "back to home" button on 500 page. Design should be same as https://app.appsmith.com/404

**Comment by JeffResc** [comment]
Hello, could I go ahead and claim/reserve this to work on?

**Comment by Nikhil-Nandagopal** [comment]
@JeffResc go for it!
