### ISSUE TITLE
[Bug]: Not able to disable form login & signup at build time

### ISSUE THREAD

**Issue by u128393** [appsmithorg/appsmith#13041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Most options in [app/client/src/ce/configs/index.ts](https://github.com/appsmithorg/appsmith/blob/v1.6.20/app/client/src/ce/configs/index.ts) (as of v1.6.20) are configurable via environment variables at build time, because they start with `REACT_APP_`, which are good. But a few, including `disableLoginForm`, `disableSignup` and `disableTelemetry`, are not. Is there a reason for this? Can these be changed?

### Steps To Reproduce

1. Run `APPSMITH_FORM_LOGIN_DISABLED=1 yarn build`
2. Serve the app
3. Check form login is still enabled

### Version

Self Hosted - v1.6.20

**Comment by Nikhil-Nandagopal** [comment]
@u128393 yes it can be via the variable mentioned here
https://docs.appsmith.com/setup/instance-configuration/disable-user-signup
