### ISSUE TITLE
[Bug]: The merge functionality breaks  in git when the page name has a special character 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The merge functionality breaks  in git when the page name has a special character 

### Steps To Reproduce

1. Add a app
2. connect to git create a new branch 
3. generate a crud page
4. change the page name 
5. commit the changes to git
6. Now try to merge the changes to Master 
7. the queries are not added to the Git

### Version

release

**Comment by sbalaji1192** [comment]
closed as part of https://github.com/appsmithorg/appsmith/pull/13040

**Comment by yatinappsmith** [comment]
Verified.
