### ISSUE TITLE
[Bug]-[1476]:In Table widget, on changing Default Row Height to Tall / Small, the header font also changes.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Table widget, when we change the Default Row Height property to Tall / Small, the header height remains constant, but the header font also changes.

### Steps To Reproduce

1. Drag and Drop a table widget to the canvas
2. In the Property Pane, change the Default Row Height to Tall and observe the header font.
3. In the Property Pane, change the Default Row Height to Small and observe the header font.
The Height of the header row is constant, which seems fine, however, the font size of the header row changes.

<img width="1077" alt="TW_HeaderFontSize1" src="https://user-images.githubusercontent.com/101863839/163974684-bd53787f-f327-4f83-a6f3-a5a1cfda35fa.png">
<img width="1090" alt="TW_HeaderFontSize2" src="https://user-images.githubusercontent.com/101863839/163974715-41bfc88d-2396-4c04-9116-9b7e05acdd70.png">
<img width="1092" alt="TW_HeaderFontSize3" src="https://user-images.githubusercontent.com/101863839/163974723-4c031a8b-1bc0-4bdb-bf21-984d5a79bd79.png">

Expected Behaviour - The font size of the header row should remain constant.

### Version

Release

**Comment by dilippitchika** [comment]
@momcilo-appsmith what do you think here, should the font size change or not? I am of the opinion that it should not change. The user is simply changing the default row height.

**Comment by somangshu** [comment]
should be taken up with #12239

**Comment by dilippitchika** [comment]
Keep the font size to 14px irrespective of the change in the row height, we are anyways not changing the header height

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 738 |
| Effort (months)  | 0.25 |

**Comment by dilippitchika** [comment]
Completed in widget reskinning
