### ISSUE TITLE
[Epic]: JSON form next steps

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13078]
Now that we are starting to gain some traction on JSON form we have some issues with the JSON forms and users are also asking for improvements on it. 

We had already thought about some of these improvements for the JSON form but need to design these.

Items to ship would be in product backlog for this epic

Larger items to discuss would be in the needs PRD/design flow

Items not getting picked up would remain in icebox

**Comment by dilippitchika** [comment]
**User feedback notes from slack channel**

Had a call with Appsmith Enterprise user of 3 months. Very Happy with JSONForm. Not so happy with the performance.
Application was slow, he was calling multiple queries, a query was not fetching more than 300 rows. Not sure if he was fetching lot of data.
Asked for table widget inline editing.
JSON Forms look like iframe to him, specially with scrollbar on. We added a bit of styling, it seemed reasonably good for him.
He placed a few widget placed vertically, all with not much heights. At least two were JSONForms. He wanted them to auto expand/collapse as scrollHeight was not much. This was his major problem
He wanted more control over JSONForm’s individual fields like border colour, validation, control to collapse and expand whenever applicable. Validation was very important for him, also the ability to control collapse/expand property.
In the JSONForm if key is null, it shows text field, he wanted number.
He wanted a quick way to add window prompt like feature which prompts him when he navigates away or refreshes the page. He was asking for browser’s window.prompt.
He was getting a few error toasts but application seemed to be working fine, asked him for the steps to reproduce.

**Comment by Aishwarya-U-R** [comment]
@dilippitchika @ashit-rath If JSONForm detects a multi select input - which is an array from SourceData - it rightly creates the widget - but the options seems wrong.. I want the values from this array only to be Default values also!! 
Can we consider addressing this also as part of the next steps?

<img width="1148" alt="Screenshot 2022-05-12 at 12 39 24 PM" src="https://user-images.githubusercontent.com/91450662/168023281-d43c3ef0-d992-456d-ad6f-a97bfae77fc5.png">

**Comment by dilippitchika** [comment]
@Aishwarya-U-R we are tracking this, but long story short it's not possible for us/appsmith to autocreate a multi-select or a select because we don't know how many options you have. All we have is info of the current row. 

Is this field changing or absent in your data? If not, then you can create a custom field and make that multi-select and that will work.

**Comment by Aishwarya-U-R** [comment]
Hi @dilippitchika - Why is it not possible? While we pre-populate the Default Value already `{{sourceData.MultiSelectColumnName}}`, why cant we also populate the Options filed with the same sourceData as shown below & show the right values from it rather than showing the default 'Blue, Green, Red' like shown in above image?

The issue I'm want to address is showing right values in options as the field gets identified as multiselect already by JSONForm.

<img width="958" alt="Screenshot 2022-05-16 at 2 32 41 PM" src="https://user-images.githubusercontent.com/91450662/168557526-05468236-2ff1-4f75-9ff0-a7f522837ac6.png">

**Comment by dilippitchika** [comment]
Options depend on the use-case, assuming the data is the record of a user in a simple request tracking scenario where there is a table with user names and their statuses

[ { "name":"Dilip", "tags":["new","high value"]},   { "name":"Aishwarya", "tags":["old","mid value"]}]

When you click on a row in a button let's say a JSON form shows data of a row
{ "name":"Dilip", "tags":["new","high value"]}
 
 This is the only data which comes to json form, we have no information of what are the tags of other records in JSONform.sourceData, because we only get 1 record at one time here. So we can't automatically add the other tags from the 2nd record. 
 
 The options case works for you because i assume all your labels/values are being passed in sourceData, but this is highly unlikely.

**Comment by Aishwarya-U-R** [comment]
No, No! I get your point!
The ask is to show 'new' & 'high value' in Dropdown for user 'Dilip' (other values respectively for other user), while his details are shown in JSON Form instead of 'Blue', 'Green', 'Red' that we show today - which is of-course not right!

**Comment by dilippitchika** [comment]
That's wrong right? The data will always be incomplete. 

Plus here you are assuming that label and value are the same which may not always be the case.

**Comment by dilippitchika** [comment]
Maybe you are right, let me think a bit more. 

For me the reason i don't like this approach as well is because it's still the same amount of work a user needs to do. 

If they have no options selected or one option selected in the specific row then the values become empty or one. This will only work well if there are a few options selected. If we do it we only have to do it for the optics.

**Comment by some-rando** [comment]
As Laguna requested, I'm adding my use case of JSON Forms that is currently looking for added functionality. Issue #16343 has been created for it. But in short, adding the ability to know what the index of the current Array Item is from within the JSON Form would be very beneficial for doing things with the Array Items. I'm loving JSON forms so far, but this is holding it back for me.

**Comment by MohitDeshwal** [comment]
This shouldn't be closed. Not providing access to currentitem for nested array in JSON forms make them useless. Can't even show data in a select based on "filterText".

**Comment by Nikhil-Nandagopal** [comment]
@MohitDeshwal it's tracked here #16343
