### ISSUE TITLE
[Bug]: Working authenticated API suddenly stopped working; `Connection Refused, status 5000`

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#13072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user on the Intercom is complaining that an authenticated API suddenly stopped working. They are getting Connection Refused, status 5000 error. They’ve tested the same API on the postman, and it works fine.
https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100089491

### Steps To Reproduce

Don't have exact steps to reproduce, although @sumitsum might have some idea.

### Version

self hosted

**Comment by nidhi-nair** [comment]
User has mentioned this was a configuration issue, closing the bug.
