### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by deependersingla** [appsmithorg/appsmith#1308]
## Summary
Conditional new fields appears based on user input

If appsmith can do some ajax magic where i can show dynamic form to the user based on the input they selected. For example: if they select country: India, they should see a new field GST Number.

This will make it super easy to use appsmith for more dynamic and complex input forms.

[Example.](https://miro.medium.com/max/1400/0*oXI0Y0n6b37fzH6V.gif)

**Comment by Nikhil-Nandagopal** [comment]
@deependersingla this should already be possible today. You can control the visibility of a widget using dynamic values
use {{ Dropdown.selectedOptionValue === "" }} inside the visibility field

**Comment by areyabhishek** [comment]
@deependersingla Here's a loom video showing how to access the conditional visibility feature: https://www.loom.com/share/09bfa0c841754cb198e6b1aee443d847 I've taken this video from an example app called "Applicant tracker" that should also be in your org.

In the gif you posted, the dropdown widget is replaced by a text field. This is currently not possible in Appsmith but you'll be able to achieve most of the conditional formatting requirements by using a separate container.

@Nikhil-Nandagopal This particular feature doesn't work for dynamic forms where one widget needs to be replaced with another widget depending on the selected option. So this is definitely an enhancement of the existing feature.

**Comment by areyabhishek** [comment]
New issue created: https://github.com/appsmithorg/appsmith/issues/1317

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek this is supported today using a tab widget
https://www.notion.so/appsmith/Dynamic-Forms-UI-d47551f9267144429be9a3bf8685b138
