### ISSUE TITLE
[Feature]: Provide a way to increase the body size param which is required for importing the application through JSON file

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/setup/kubernetes#appsmith-configuration

### Describe the problem

The default size for the request body might be limited on kubernetes clusters installed using the helm-charts which causes the problem in the import flow. This can be fixed by updating the supported max size. 
For more details please refer: https://community.appsmith.com/t/issue-on-import-json-application-413-request-entity-too-large/855

### Describe the improvement

Create a section for Kubernetes installations on how to update the request body size as discribed in the community forum

**Comment by jnikhila** [comment]
@sharat87 / @sum35h   - could you please help us out understand the documentation needs?

**Comment by harshilp24** [comment]
This seems to be a config on the helm chart ingress.  Assigned to @sum35h, as discussed. CC: @jnikhila

**Comment by sharat87** [comment]
@pratapaprasanna, we seem to have a limit of 150M in NGINX configuration:

https://github.com/appsmithorg/appsmith/blob/76d4a7aa3f0cfb4aacd92cce1b70f12f428c1c51/deploy/docker/templates/nginx/nginx-app-http.conf.template.sh#L29

Can you confirm if we have this same figure in the NGINX controller configuration as well please?

@abhvsn, this is the limit we want, I'm guessing, right?

**Comment by abhvsn** [comment]
Yes, this issue was discussed long back but AFAIR this was a config issue and updating the setting in values.yml fixed the issue for customer.

**Comment by sharat87** [comment]
Okay. I'll wait for @pratapaprasanna to confirm that as well, and if that's also fine, we can close this.
