### ISSUE TITLE
[Bug]: Inline JS function misbehaves when query is ran and data is stored in appsmith store

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#13094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we use `appsmith store` to bind the data object to different widgets then some widgets do not show the updated value s when the data stored in the `appsmith store` is updated after running the update call to the datasource and fetching the value again.

Here's a link to the app which shows the behaviour described above.
[Store Issue Application](https://app.appsmith.com/app/store-issue/page1-625db1de0d3d384069c221c8)

Adding in the image to describe the proper functionality of the application and the bug

<img width="885" alt="Screenshot 2022-04-19 at 6 54 30 PM" src="https://user-images.githubusercontent.com/7565635/164014082-94ede4cb-1128-4f98-a417-31a68c784703.png">

There are 3 buttons: 
- Button 1 : `Submit using JS function` -> Which uses JS function and the functionality works fine 
- Button 2 : `Submit using inline JS` -> Which uses inline JS and the functionality works fine as the inline JS has async await
- Button 3 : `Submit using inline JS (doesn't work)` -> Which uses inline JS but the functionality breaks as the inline JS uses callback method which eventually calls an async method (JSFunction.fetchValue) but if the last function (JSFunction.fetchValue) is called using callbacks it works fine

The functionality : 
- As and when the store is updated the widgets should reflect the same but which doesn't happen in case of button 3.

### Steps To Reproduce

Above mentioned description has the Application link which describes reproduction of the issue.

Here's an Application link : [Store Issue Application](https://app.appsmith.com/app/store-issue/page1-625db1de0d3d384069c221c8)

### Public Sample App

https://app.appsmith.com/app/store-issue/page1-625db1de0d3d384069c221c8

### Version

Both

**Comment by rohan-arthur** [comment]
![Screenshot 2022-05-03 at 15.27.35.png](https://images.zenhubusercontent.com/6196337f2def7ccca841bb55/4d431a6e-f614-44e5-a57d-f7b739a52bad)

**Comment by rohan-arthur** [comment]
@AmanAgarwal041 would you please invite me to this app so I can see it in edit more?

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur you can now fork the app

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 check this out

**Comment by bharath31** [comment]
@AmanAgarwal041 this seems to work now. could you check if you're still facing this issue?
