### ISSUE TITLE
[Docs]: Internal properties to be updated for all widgets

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/widget-reference/camera

### Describe the problem

Binding properties of a widget are different to other properties on the property pane and needs to be listed down to explain the usage and expected behaviour of using these widget binding properties. Camera widget has these properties listed.

### Describe the improvement

For example, when using `Button1.` then there are currently 4 properties that show up for a user to access. The meaning and usage are apparent in some cases but are not so clear in others like on the audio widget's `playState`. The possible values are not apparent unless user tries different combinations. Documenting this would help provide clear information.

**Comment by dilippitchika** [comment]
@jnikhila can you take a look once on how we can work on this and what are the current gaps?

**Comment by jnikhila** [comment]
Sure @dilippitchika. cc - @ajinkyakulkarni

**Comment by jnikhila** [comment]
@ajinkyakulkarni - Moved the ticket to consider for upcoming sprint as this needs analysis in terms of sizing the work.
