### ISSUE TITLE
[Bug]-[40]:Disabled button can be clicked on the welcome page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Disabled button registers a click on the welcome page and hence user is navigated to the next page without needing to enter details

### Steps To Reproduce

1. Sign up to Appsmith
2. On the welcome page, click enter without entering any details and observe user navigated to next page even though button is disabled.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/86ed770d47a74f5599ff485365a49a7b-00001.gif)](https://www.loom.com/share/86ed770d47a74f5599ff485365a49a7b)

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 10 |
| Effort (months)  | 0.5 |

**Comment by eco-monk** [comment]
We have some trouble verifying this in deploy preview.
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1678694313317649

**Comment by Richarex** [comment]
This is fixed verified it on the DP url.
