### ISSUE TITLE
[Bug] Enhancement : Appropriate Error message must be displayed to user when Onpageload and confirm before load setting are used together

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1309]
Steps to reproduce:
1) Navigate to application
2) Create a query
3) Navigate to query setting 
4) Toggle OnPageload and confirm before load
and observe

Expectation:
User can only use one among the option at once and when user tries to execute both together the user must be displayed with an error message

**Comment by Nikhil-Nandagopal** [comment]
@prapullac verified that this is not a problem. This is only because of the other issue #1290
