### ISSUE TITLE
[Task]: Reduce property pane mount time by mounting code editor on demand

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#13112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Most expensive part of the property pane is the code editor. This is used when JS is enabled for any field.

For example, if a widget has 4 JS fields, it mounts 4 code editors. CodeEditor is very expensive and accounts for more than half of property pane render time.

**Solution**:
Mount code editor when focused. We can have a wrapper component, say `CodeInput`
Whose render function would be something like

`{isFocused?<CodeEditor />:<Input />}`

**Things to watch out for**

- Measure the improvement when there are 4+ code editors on property pane
- Ensure that mounting code editor on demand doesn't affect UX
- Ensure keyboard navigation works like before

**Comment by Sripriya93** [comment]
One round of regression is done after the deployment in the regular regression cycle, no issues found, marking as verified
