### ISSUE TITLE
[Docs] Add a page on how to control visibility of UI widgets

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1312]
## Describe the problem

Users don't fully understand that apppsmith can be used to dynamically control the visibility of a widget. We should display how to control a widget from another widget and from an API data

**Comment by Rithvik-Reddy** [comment]
Hi can I be assigned this issue?

**Comment by hetunandu** [comment]
Hey @Rithvik-Reddy, assigned this to you. Welcome to the Appsmith community 😄
Make sure you read the [Documentation Contribution Guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before you proceed and raise the PR within 3 days.

**Comment by Rithvik-Reddy** [comment]
Hi @hetunandu, thanks for the warm welcome. Will be sure to go through the guidelines before raising the PR.
