### ISSUE TITLE
[Docs]: Update | Security

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#13131]
[Security ](https://docs.appsmith.com/security#securely-executing-javascript) doc needs update.

As per issue raised on aforce channel:

we need to update our security document. Take a look at the following link to a section; not sure what #1 actually means - https://docs.appsmith.com/security#securely-executing-javascript

**Comment by jnikhila** [comment]
The first draft is available at https://www.notion.so/30ab6e99f80e4c0482dc96d3b651370d
@Rishabh-Rathod and @trishaanand  - Could you please review the doc and update if it's ready for the doc team.

**Comment by jnikhila** [comment]
@Rishabh-Rathod and @trishaanand - Could you please confirm if the review is completed, and can we start work on the ticket?

**Comment by jnikhila** [comment]
@Rishabh-Rathod / @trishaanand - Please review the doc.

**Comment by Rishabh-Rathod** [comment]
@jnikhila Document looks good to me.

**Comment by jnikhila** [comment]
Documentation published.
