### ISSUE TITLE
[Bug]-[2880]:Unable to commit new changes.

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#13130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to commit new changes with app https://app.appsmith.com/app/habitasaurus/task-6256bfa40d3d384069c0719b?branch=Tasks.

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/cf97a51588e74fea836c61497524716e-00001.gif)](https://www.loom.com/share/cf97a51588e74fea836c61497524716e)

### Public Sample App

https://app.appsmith.com/app/habitasaurus/task-6256bfa40d3d384069c0719b?branch=Tasks

### Version

Cloud

**Comment by abhvsn** [comment]
@yatinappsmith seems like a DB query performance issue as I can see some timeouts. Can you please check if this is happening with other org as well if you fork the same app to a different org?

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 360 |
| Effort (months)  | 0.25 |

**Comment by abhvsn** [comment]
Closing this as fixed in https://github.com/appsmithorg/appsmith/pull/13133
