### ISSUE TITLE
[Bug]: Checkbox Label is not visible when Array only consists of checkboxes

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#13140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we add Checkbox field in json form inside Array items, the label name doesn't appear but when we add same under Object's first field, the checkbox field appears as normal

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3900e3a6538d4175a422277a8609e292-00001.gif)](https://www.loom.com/share/3900e3a6538d4175a422277a8609e292)

### Steps To Reproduce

1. Add Json form onto canvas
2. Add a Array type field
3. Inside Array items, change the field to Checkbox and observe the array field on Json form

### Version

Cloud/Production

**Comment by ashit-rath** [comment]
@chandannkumar Can you check if this issue is resolved in the theming epic?
DP of theming: https://appsmith-git-theming-phase-1-get-appsmith.vercel.app/

**Comment by chandannkumar** [comment]
@ashit-rath Tested this issue on theming DP where it seems Fixed and working as expected
