### ISSUE TITLE
[Bug]: GraphQL: fix build failure on IntelliJ

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#13145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fix the build failure on IntelliJ introduced via issue #12019. 
The build works fine from CLI.

### Steps To Reproduce

.

### Version

Self Hosted

**Comment by sumitsum** [comment]
Currently, the build goes through on IntelliJ but query execution fails with the following error: `java.lang.NoClassDefFoundError: graphql/parser/InvalidSyntaxException`

**Comment by sumitsum** [comment]
@prapullac since this a POM file change I am assuming no QA should be required for this. Please re-open and move it to the QA pipleline if QA is required. I am closing it for now.

**Comment by prapullac** [comment]
Not on the release yet

**Comment by prapullac** [comment]
Closing this issue as per comment by Sumit
