### ISSUE TITLE
[Bug]-[5142.857142857143]:Cannot access outer variable inside a callback

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#13156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I use a `setInterval` method and assign that to a variable and inside the setInterval's callback if I use `clearInterval` to stop the recurring function. Its shows me an error of variable not defined.

Here's a link to the application : [Set Interval Issue](https://app.appsmith.com/app/setinterval-issue/page1-62600d9a00cba01cd02eb38d) 
Here are some screenshots of the application : 

<img width="873" alt="Screenshot 2022-04-20 at 7 18 52 PM" src="https://user-images.githubusercontent.com/7565635/164245883-53214423-e2fc-42f0-96b0-0b5698a740f6.png">

<img width="543" alt="Screenshot 2022-04-20 at 7 22 07 PM" src="https://user-images.githubusercontent.com/7565635/164246064-b539f4a8-3e94-4416-8f53-a7df479e6d23.png">

Same thing happens with other callback functions like ```Query.run(function(){ //use outside variable here })```.

### Steps To Reproduce

1. Create a JS function
2. Create a timer using `setInterval` function
3. store `setInterval` function returned value in some variable -> v1
4. use `clearInterval` function and pass  v1 variable to it inside setInterval callback function to clear it using some condition.
5. It throws an error saying `UncaughtPromiseRejection: interval is not defined` and the setInterval cannot be cleared

### Public Sample App

https://app.appsmith.com/app/setinterval-issue/page1-62600d9a00cba01cd02eb38d

### Version

Both

### Developer notes

https://github.com/appsmithorg/appsmith/pull/17832#discussion_r1006677902

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu @ApekshaBhosale I remember there was a similar issue for this somewhere. Do you remember which issue that was?

**Comment by hetunandu** [comment]
setInterval is not going to return an id on Appsmith. You will need to pass a custom id as the 3rd argument in setInterval and use that id to clear that interval

**Comment by AmanAgarwal041** [comment]
This error also comes when there is a variable initialised outside of the API call inside JS Object and is being used inside the callback functions of the API calls. I have updated the above attached application for the issue [Sample Application](https://app.appsmith.com/app/setinterval-issue/page1-62600d9a00cba01cd02eb38d). @hetunandu please have a look at it.

**Comment by Nikhil-Nandagopal** [comment]
Yup can confirm something like this will fail
```
myFun2: async () => {
		var testVal = "hello";
		Test_API.run(() => {
			showAlert(testVal);
		})
		//use async-await or promises
	}
```
@ApekshaBhosale It's mentioned that this was handled in this issue here https://github.com/appsmithorg/appsmith/issues/6872#issuecomment-921529953
But it doesn't work

**Comment by Nikhil-Nandagopal** [comment]
@AmanAgarwal041 @rohan-arthur when are we fixing this issue? This was reported here as well
https://www.notion.so/appsmith/Tanvi-Bhakta-Thoughts-while-building-and-using-my-first-app-s-ab87b921c44d413f9a7b306241887845#40a555f9ee6c4592bf0f40ab98a481c7

**Comment by ApekshaBhosale** [comment]
this is not fixed.  check with the team to put it on priority @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
One more user reported this issue
https://community.appsmith.com/t/unable-to-access-variable-outside-of-function-when-invoked-as-setinterval-callback/1194/2
@satbir121 @rohan-arthur

**Comment by Rishabh-Rathod** [comment]
### Temporary Workaround 

Instead of using local js variables, Appsmith store values could be used.

## Inside JSObject
```js
export default {
    myfunc: async () => {
         storeValue("varName", "anyValue");
         setInterval(() => {
               const varName = appsmith.store.varName;
               if (varName === "done"){
                   clearInterval("interval") // to stop the interval
               }
         }, 1000, "interval");
    }
}
``` 

## Inside widget event field
```js
{{(() => {
         storeValue("varName", "anyValue");
         setInterval(() => {
               const varName = appsmith.store.varName;
               if (varName === "done"){
                   clearInterval("interval") // to stop the interval
               }
         }, 1000, "interval");
    })()}}
```

**Comment by ZackKnopp** [comment]
Same issue for me:
```
callApiInSequence: async (api1, api2=null, api3=null) => {
		
		// Adding callback functions explicitly here fixed a bug where select grabs old data before update is finished for some reason, I think it's a problem with their handling of Patch
		api1.run(
		(up_res) => {
			console.log("up_res", up_res)
			debugger
			api2.run(
			(sel_res)=>{console.log("sel_res",sel_res)},
			// Needed the error handle below otherwise appsmith threw unhandled exceptions, even though no errors showed up
			error => showAlert("Failed because: "+ JSON.stringify(error)))
		},
			error => showAlert("Failed because: "+ 			JSON.stringify(error))
		)


	}
```

`api2` shows as undefined.

The await/async works, but callbacks don't. And I'm using callbacks because there is still a bug that wont let the api error message be passed through when I use async await.
