### ISSUE TITLE
[Bug]-[2500]:Console log errors visible to user for JSObject is async determination

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#13153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The issue is with the console log being visible to the user for function run which Appsmith does internally.
JSObject runs function internally as part of its implementation and is not a bug.
Users should not be shows logs for such cases. As they don't expect the function to run without any trigger.

the function should not actually be getting executed at this time. It's just our code going through the functions to parse them and that's why we're logging them.

Link to the issue: https://discord.com/channels/725602949748752515/965650283474612224

### Steps To Reproduce

1. Create a JS Object.
2. Define an async function inside this object(with a console statement in it).
3. Disable the page load execution option for this Object.
4. Refresh the page
5. Observe that even if the page load execution is disabled. Still the function is getting executed.

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
@keyurparalkar there might be miscommunication.
The issue is with the console log being visible to the user for function run which Appsmith does internally.
JSObject runs function internally as part of its implementation and is not a bug. 
Users should not be shows logs for such cases. As they don't expect the function to run without any trigger.

**Comment by rohan-arthur** [comment]
@Rishabh-Rathod are these "pre-runs" consequential to the user in any way? If no, is the requirement that we should suppress these pre-runs from being logged?

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod are these "pre-runs" consequential to the user in any way? If no, is the requirement that we should suppress these pre-runs from being logged?

Yes, we need to just remove logging for pre-runs as they cause confusion to the users when they check the browser dev tool's console.

**Comment by 2snEM6** [comment]
How are they non consequential? The user expects the function to be run *once* when the page loads, not twice.

**Comment by Nikhil-Nandagopal** [comment]
@2snEM6 the function should not actually be getting executed at this time. It's just our code going through the functions to parse them and that's why we're logging them. If you call an API and check the network, you will not see 2 API calls.

**Comment by rohan-arthur** [comment]
6m usage of js editor: 2500
considering 50% of users look at the console: 1250

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1250 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
this should no longer be an issue since dry runs are disabled as a part of #18175
