### ISSUE TITLE
[Type]-[400]:Deprecate duplicate application as we can fork the application within the same organization as well

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using the fork application user can create a copy of the application within the same organization along with the other organizations of which the user is part. From the user's perspective, this creates some confusion as we are doing the same thing in 2 different places. 
For more details please check slack thread: https://theappsmith.slack.com/archives/C0341RERY4R/p1650518456216239

**Comment by abhvsn** [comment]
@hiteshjoshi can we please prioritise this to decrease our tech debt

**Comment by hiteshjoshi** [comment]
@abhvsn can you write more details about it. The title alone isn’t making absolute sense.

**Comment by abhvsn** [comment]
Sorry for not being clear earlier but we are referring to deprecate the duplicate application feature as we can create a copy of the application using fork application as well. User will have to fork the application in the same organization. For more details please check the slack thread where user got confused because we are doing the same operation by 2 different ways.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 1 |
