### ISSUE TITLE
[Bug]-[160]:CheckBoxGroup not displaying options in a modal

### ISSUE THREAD

**Issue by soul-cell** [appsmithorg/appsmith#13171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CheckBoxGroup inside a modal not displaying the values even though the options property of that same checkBoxGroup shows the correct evaluated values . 
![Capture](https://user-images.githubusercontent.com/82372780/164387821-7e50916f-8f79-4dba-8c55-47686b92819e.PNG)

### Steps To Reproduce

1.Create a modal with a CheckBoxGroup
2.Tick the options and close the modal 
3.Reopen the modal 

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@soul-cell I'm not able to reproduce this issue. Can you please create a public app that reproduces this issue on app.appsmith.com so we can fix it?

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal found a way to reproduce, happens when you reset the modal

https://www.loom.com/share/45c2d263fe7f4a04a58ceb268d9f2f4c

**Comment by dilippitchika** [comment]
Reach - Assuming 20% of checkbox group users who have updated checkbox group options have faced this

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 40 |
| Effort (months)  | 0.5 |
