### ISSUE TITLE
[Feature]: Integration with firebase storage

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user on intercom wanted to integrate with firebase storage similar to how we use S3 to upload and manage files.

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100079780

### Why should this be worked on?

Improved integrations

**Comment by areyabhishek** [comment]
We have one open for this at #1647 https://github.com/appsmithorg/appsmith/issues/1647 Closing this in favor of that.
