### ISSUE TITLE
[Feature]-[3000]:Provide support for older MSSQL version that require TLS1.0

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#13187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith's backend server doesn't allow connecting to endpoints that require TLS1.0 and not TLS1.1 or TLS1.2

### Why should this be worked on?

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100091357

**Comment by rohan-arthur** [comment]
MsSQL 6 month usage: 220
apply 25% requirement: 55

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 55 |
| Effort (months)  | <<number>> |

**Comment by dilippitchika** [comment]
@rohan-arthur the RICE score is infinity on this 🤯

**Comment by rohan-arthur** [comment]
@dilippitchika yes, still needs the effort to be added - have applied the label `needs estimate` to this issue so that the team knows to add the effort to get the final score

**Comment by sharat87** [comment]
This isn't specific to MSSQL, but has been seen with MySQL and I think MongoDB as well. This needs to be fixed/changed at the JRE settings level.

Here's the past conversation on this with gory details: <https://theappsmith.slack.com/archives/CPQNLFHTN/p1633705690184200>.

The solution should be that TLSv1 will be disabled by default, and users can set an env variable, like `APPSMITH_ENABLE_TLSV1`, which, if set to `true`, should do the necessary changes from the entrypoint script before starting the backend server.

**Comment by rohan-arthur** [comment]
@sharat87 thank you for sharing more insight into this! I have updated the reach score.

**Comment by danciaclara** [comment]
Another user faced an issue due to this - https://discord.com/channels/725602949748752515/760761686549463060/1013390850811756545

**Comment by sharat87** [comment]
Before we attempt to solve this, I'd encourage everyone to advise upgrading their systems to move away from TLS v1.0. It's been deprecated for over two years now, and is very-not-recommended. See <https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.0>.

I'm going to close this issue, in that interest. If there's someone who absolutely cannot upgrade from this vulnerable TLS version, we can reopen and reconsider.
