### ISSUE TITLE
[Bug]: the master branch is selected as default even when its removed from the default branch

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the master branch is selected as default even when its removed from the default branch

### Steps To Reproduce

1. Connect the application to the git
2. now create a new branch
3. From git hub change the default branch to the newly created branch b1
4. Now come back to the application sync the branch
5. now master branch will be removed as a default branch
6. Now go to home page
7. reopen the application in edit mode
8. the master branch will be selected by default instead of new default branch

### Version

release

**Comment by AnaghHegde** [comment]
Fixed via #13207
