### ISSUE TITLE
[Bug]: The master branch text is displayed even after deleting the master branch from app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The master branch text is displayed even after deleting the master branch from app, along with this the internal server error is displayed
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/164442528-05cc21eb-c631-4ac3-bbd3-661846eb7a98.png">

### Steps To Reproduce

1. Connect the application to the git
2. now create a new branch
3. From git hub change the default branch to the newly created branch b1
4. Now come back to the application sync the branch
5. now master branch will be removed as a default branch
6. Now go to home page
7. reopen the application in edit mode
8. the internal server error is displayed with the selected branch name as master

### Version

release

**Comment by AnaghHegde** [comment]
@haojin111 @IAmAnubhavSaini We should pass the branchname parameter for git connected application when the user clicks on edit. But somehow we are not using the branch from the git application metadata
<img width="1440" alt="Screenshot 2022-04-22 at 10 37 17 AM" src="https://user-images.githubusercontent.com/12005551/164607114-1f78b855-7143-49a9-8f6b-b4f88104a6d2.png">

**Comment by RakshaKShetty** [comment]
Fixed 
![Uploading image.png…]()
