### ISSUE TITLE
[Bug]: in sending the body of API when body has key with value as String of comma separated numbers

### ISSUE THREAD

**Issue by Somashekar-B** [appsmithorg/appsmith#13181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we pass the body of any API as like 
{
 "key":**"1,2,3,4"**,
"key2":"temp"
} 

it will pass the body to the API as
{
 "key":**1**,
"key2":"temp"
}

so it will consider that string of numbers with comma separated it will convert it into number actually it should be the string of numbers 
**Please Fix it soon**

### Steps To Reproduce

1. Create an API that accepts body as **JSON object which contains a string of comma separated Integers as a value for a key**
2. Try to print the request on the Server side to check the body recieved

### Version

Self Hosted Version no idea

**Comment by Nikhil-Nandagopal** [comment]
@Somashekar-B Thank you for reporting this issue! You can solve this by turning off smart substitution.

**Comment by Somashekar-B** [comment]
No it didn't solved the problem actually it made it even worse.
Actually the evaluated value will not be the same as the value passed to
the api as body if it is same then everything will be fine
Please check that

**Comment by Nikhil-Nandagopal** [comment]
@Somashekar-B I just tried reproducing this and while hitting request inspector from my app, you can see the body is being sent correctly
https://requestinspector.com/p/01g1jzfzypmd6w0yzet0dwhd2h
Can you share an app that is pointing to requestinspector where you are able to reproduce this?

**Comment by Somashekar-B** [comment]
can you send me what was your request body

and please try to send body as
{
    "text": "1,2,3,4",
    "time": "2022-05-04T12:09:10.054Z"
}

and observe the body recieved in the backend

**Comment by Nikhil-Nandagopal** [comment]
@Somashekar-B is it possible some middleware in your backend is automatically trying to split the request key?
The request inspector logs show the correct data has come to it
![Uploading Screenshot 2022-05-06 at 4.00.47 PM.png…]()

**Comment by Nikhil-Nandagopal** [comment]
@Somashekar-B you can turn off smart substitution. It's a setting in the settings tab of the API
and add quotes around the Input binding
```{
  "text": "{{Input1.text}}",
  "time": "2022-05-04T12:09:10.054Z"
}```
<img width="745" alt="Screenshot 2022-05-06 at 5 45 01 PM" src="https://user-images.githubusercontent.com/3897254/167129593-c52e6c4e-e557-49be-835b-5cef09629f20.png">

**Comment by Somashekar-B** [comment]
@Nikhil-Nandagopal Thanks that solved the problem..
