### ISSUE TITLE
[Bug]: Async functions turned into sync code is still executed on page load even though the option to do so is unavailable

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a function containing async code is made into sync function - then any on page action that was previously set is retained and the sync is run on page load

### Steps To Reproduce

1. Add a JS object and mark an async function to run on page load
2. Remove async code in the function and refresh the page - observe that the previously marked async function is run again

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/a74a18aa5c5940b3a51cc9f5eb4eb05b-00001.gif)](https://www.loom.com/share/a74a18aa5c5940b3a51cc9f5eb4eb05b)

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/13197?planning-poker) with ZenHub @ohansFavour

**Comment by ohansFavour** [comment]
As per the discussion with @ApekshaBhosale, this should ideally be handled on the backend. As long as the isAsync property is correctly configured, sync functions should not have the "onPageload" and "confirmBeforeExecute" as true.

cc: @nidhi-nair

**Comment by nidhi-nair** [comment]
Hey @ramsaptami ! Why is this a requirement at all? Would we not be diverging from behaviour from APIs and queries if we handle this specially? The idea with APIs as well is that once a user marks something to be run on page load manually, we honour that setting regardless of anything else. May be what we do need is to expose a reset button across all entities to the user?

**Comment by prapullac** [comment]
Moving it to Inprogress as the issue still exists
