### ISSUE TITLE
[Bug]-[180]:The pull changes button should be displayed inside the deploy modal when there are only remote changes

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The pull changes button should be displayed inside the deploy modal when there are only remote changes
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/164466808-45ae56ed-4d5c-4d97-a245-c91105d62db7.png">

### Steps To Reproduce

1. Connect the application to the git
2. do some changes in the remote 
3. now there will be 1 pull change on the pull icon
4. now click on+ icon under deploy tab the commit and push will be disabled 
5. now instead of commit and push disabled we need to give the pull changes button

### Version

release

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 45 |
| Effort (months)  | 0.25 |

Adding the reach for this as everyone who uses branches on their Git app, as they are most likely to encounter this. @abhvsn correct me if I am wrong on this.

**Comment by abhvsn** [comment]
Actually, this will be an issue when the user has the same branch in multiple Appsmith instances. In this setup user's can commit and push from 1 instance for which the user on other instance if working on the same branch will have to pull the changes first.

**Comment by infinitetrooper** [comment]
Currently, it's discard and pull so, this doesn't apply.
