### ISSUE TITLE
[Feature]: User wants an option to reduce login session time

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#13191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

User needs the session time to be less than a month

### Why should this be worked on?

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100065704

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #24455
