### ISSUE TITLE
[Docs] Cases for references to Appsmith are inconsistent and typo found

### ISSUE THREAD

**Issue by michizhou** [appsmithorg/appsmith#1321]
## Documentation Link 

Inconsistent Cases for "Appsmith":
https://docs.appsmith.com/core-concepts/apis/running-apis-on-page-load
https://docs.appsmith.com/core-concepts/connecting-to-databases
https://docs.appsmith.com/function-reference/navigateto
https://docs.appsmith.com/third-party-services/email
https://docs.appsmith.com/third-party-services/email/sendgrid
https://docs.appsmith.com/third-party-services/email/amazon-ses
https://docs.appsmith.com/third-party-services/google-login
https://docs.appsmith.com/third-party-services/github-login
https://docs.appsmith.com/third-party-services/google-maps

Documentation Typo:
https://docs.appsmith.com/core-concepts/connecting-ui-and-logic/working-with-js-libraries

## Describe the problem

References to "Appsmith" are inconsistent, with the name for the platform being lowercase while other pages of the website documentation have references which are uppercase (treating "Appsmith" as a proper noun). 

A typo was also found in the documentation page for working with JS libraries.

## Describe the improvement

Documentation typo should be fixed and inconsistent references to "Appsmith" should be changed to uppercase to reflect the use of "Appsmith" as a proper noun across all documentation pages.

**Comment by areyabhishek** [comment]
@michizhou thanks for opening this issue!

**Comment by michizhou** [comment]
@areyabhishek @Nikhil-Nandagopal I have opened a PR that will resolve this issue. Please let me know if any additional changes or modifications need to be made for the documentation.
