### ISSUE TITLE
[Task]: Highlight JS Object's name when newly created

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#13213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/13213?planning-poker) with ZenHub @ohansFavour
