### ISSUE TITLE
[Bug]: PropertyPane evaluation of Child widget in a list widget  throws an error when some chars are used

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#13211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Text widget in a list widget has 's and that throws an error for some reason

### Steps To Reproduce

Drag a Text widget into a List Widget, Then change the text in the Text widget to `Yesterday's`.
Observe an `SyntaxError: Unexpected identifier` error 

### Version

cloud

**Comment by Tooluloope** [comment]
Related to PropertyPane evaluations for List widget

**Comment by ashit-rath** [comment]
Already fixed in #15839
