### ISSUE TITLE
[Feature]: List widget - default selected item

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#13214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a user, I should be able to set a default selected item while using the list widget

### Why should this be worked on?

Use Case:
Depending on the item selected a Query / API functions, It would be helpful if programatically I can set a default selected item in the list that onPageLoad is set.

**Comment by somangshu** [comment]
@dilippitchika [user on discord](https://discord.com/channels/725602949748752515/760761686549463060/1001135761992712284) requesting for this feature, I have asked for the use case, If they respond Ill drop it here, Otherwise can you check the detail and see if this needs to be prioritized?

cc @Tooluloope @ashit-rath

**Comment by dilippitchika** [comment]
Updated PRD - https://appsmith.notion.site/Default-selected-item-161e87fa9f754fc485285d5b32817d7d

**Comment by shastryblr** [comment]
Designs are shared [figma](https://www.figma.com/file/9EZtkgE6VmiEv8LIQzwr5K/Default-selected-item---List?node-id=48%3A1717&t=NWAUkJBnO67jTXpl-1),  Engineer has shared feedback. 

Handoff to happen by today (friday,02-Nov-2022)

**Comment by dilippitchika** [comment]
@Tooluloope can you check this out for the sprint, after you are done with total record count?

**Comment by Tooluloope** [comment]
- The feature is to work for both Serverside and Clientside data.
- For ServerSide, we'd need a default page property
- We'd add this feature for Clientside alone till we have the best UX for serverside data.

cc @vsvamsi1
