### ISSUE TITLE
[Bug]: When an incomplete SaaS Integration is installed via the SaaS Manager App, actions are not loaded.

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13234]
If an action is incomplete when it is installed in an organization, the query remains loading and does not display the actions. 

Some tests that were performed:

|Test|Status|
|---|---|
|Install for first time an integration without label and tooltip|loading|
|Install an integration with a complete action |work|
|Install an integration with only the label| work|
|Install an integration with only tooltip | work|
|Install again an integration that work, without label and tooltip| work|

Note: I have a suspicion that these fields are related and when one is created, the other field is created in null so that it does not present the problem. But when it is installed for the first time, those fields do not exist, so it this happens. 

Possible solutions: 
- Make Label and Tooltip required.
- Improvements to validation as mentioned on #11087

**Comment by felixsuarez0727** [comment]
I need to test more scenarios where this could fail. I am uncertain if we want to handle this as changes to the SaaS App (validation?) or included on [#11087](https://github.com/appsmithorg/appsmith/issues/11087).

Thoughts?

CC: @nidhi-nair @AmanAgarwal041

**Comment by felixsuarez0727** [comment]
I was not able to reproduce this error. I suspect previous updates to SaaS App and Backend are fixing this error.

**Comment by prapullac** [comment]
@felixsuarez0727 : Please let me know how I can verify the issue on SAAS manager App

**Comment by felixsuarez0727** [comment]
For this one, you will have to create a small test integration on the SaaS App. I usually use a test endpoing on this platform: https://webhook.site/.

Then you recreate the conditions mentioned in the table on this issue's description.

Example: Create an Integration that has one dynamic variable, save it, then remove that dynamic variable, then, try to install the integration and check if it breaks the organization.
