### ISSUE TITLE
[Task]: Improve the UX for commit and push flow when there are upstream changes alongwith the local changes

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Desctiption

As we don't have a separate CTA for commit and push we need to think through the scenario when user have local as well as upstream changes. This is because in the current flow commit succeeds but push fails to maintain the git history.

**Comment by abhvsn** [comment]
More discussion on this issue: https://theappsmith.slack.com/archives/C02K2MZERSL/p1650876597888719

**Comment by abhvsn** [comment]
Present the flowchart diagram to cover all the edgecases to discuss this further

**Comment by abhvsn** [comment]
https://miro.com/app/board/uXjVO3qLt7Q=/

**Comment by Debsourabh** [comment]
Adding Prototype with 3 options to choose from :
https://www.figma.com/proto/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-Git-Sync?page-id=3015%3A18242&node-id=3022%3A18733&viewport=-4343%2C-1422%2C0.74&scaling=min-zoom&starting-point-node-id=3022%3A29483

We did a peer review and there was some feedback around it. So here is the updated version
https://www.figma.com/proto/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-Git-Sync?page-id=3015%3A18242&node-id=3122%3A21281&viewport=875%2C132%2C0.09&scaling=min-zoom&starting-point-node-id=3122%3A21281&show-proto-sidebar=1

**Comment by RoopKrrish9696** [comment]
Handled with new IA
