### ISSUE TITLE
[Bug]: API call inside a JS is displayed as an error when bound to a widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Calling an API/datasource query in a JS object and binding this to a widget throws an error stating `Api1.run` is not a function. Error message needs to be improved since async function is not allowed in data fields.

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/git-connected-app-with-js-objects/page1-62668caa01f360366e25e4d2/edit) location
2. Observe the binding on the table widget display an error stating `mockAPI.run` is not a function

![image](https://user-images.githubusercontent.com/79509062/165088937-ee5e4b66-1725-4003-9c4b-c73cbc248363.png)

### Public Sample App

https://release.app.appsmith.com/app/git-connected-app-with-js-objects/page1-62668caa01f360366e25e4d2/edit

### Version

Cloud

**Comment by ramsaptami** [comment]
Related to #12179
Duplicate of #13288

**Comment by ramsaptami** [comment]
Error message needs to be improved and documentation enhanced on usage of async functions
@Rishabh-Rathod will raise a seperate task for this

**Comment by Rishabh-Rathod** [comment]
https://github.com/appsmithorg/appsmith/issues/13320 created an issue for improvement in docs here. 
@ramsaptami Can you create an issue for improvement of the error message?

**Comment by ramsaptami** [comment]
Hey Rishabh, I've added the `error` tag on the issue and updated the description to state the same. Hope the works
