### ISSUE TITLE
[Bug]-[2514.285714285714]:MongoDB requires string parsing when working with datetimes

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#13285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user has a collection in MonogDB which contains many datetime fields with invalid value `0001-01-01T00:00:00.000+00:00`. When they are trying to project the datetime fields in the Project clause in the query it is returning `org.json.JSONException: JSONObject["$date"] not a string` error. They can use `toString()` to convert them while projecting them but there are many fields and they are looking for another solution or a way for Appsmith to ignore invalid date and return them even if they are invalid.
Invalid datetime example:
![](https://cdn.discordapp.com/attachments/966421700206034984/966787249985445988/unknown.png)
Error from Appsmith:
![](https://cdn.discordapp.com/attachments/966421700206034984/966788546256056400/unknown.png)

### Steps To Reproduce

1. Create a table in mongo containing datetime column with the format `0001-01-01T00:00:00.000+00:00`.
2. Query the table in Appsmith and try to project the datetime fields.
3. Observe `org.json.JSONException: JSONObject["$date"] not a string` error.

### Version

Self Hosted - 1.6.20

**Comment by MarabiFouad** [comment]
Hello everyone Actually I raised this issue and still I am awaiting your response. Is it in progress?

**Comment by leotom2000** [comment]
> Hello everyone Actually I raised this issue and still I am awaiting your response. Is it in progress?

Hi @MarabiFouad, the current status is "Work in Progress"
Sorry there has been some delay when we started working on this issue.
Appreciate your query as a reminder and we would put this on priority and update you the status.

**Comment by rohan-arthur** [comment]
mongodb 6m usage: 1100
considering date is a common requirement (say80%): 880

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 880 |
| Effort (months)  | <<number>> |

**Comment by MarabiFouad** [comment]
Hi there, any news about this issue?

**Comment by cokoghenun** [comment]
@Nikhil-Nandagopal I came across this issue two days ago when doing a fetch query on a collection that uses MongoDB date fields. I ran into the same issue:


![Screen Shot 2022-06-01 at 12 17 07 PM](https://user-images.githubusercontent.com/17744578/171926977-230a693e-2270-4cc3-9b28-9f57575fad55.png)
![Screenshot 2022-06-01 at 12 14 49 PM](https://user-images.githubusercontent.com/17744578/171927003-d0ffbc05-1489-4a0b-886c-31ba9688a680.png)

**Comment by punit-squadcast** [comment]
Hi @cokoghenun 
I am also facing same issue, have you found any fix for this. Please help me with the same.
Thanks

**Comment by subrata71** [comment]
I am going to look into this issue in this sprint.
cc: @rohan-arthur @nidhi-nair

**Comment by subrata71** [comment]
### Findings
Internally, [Date](https://www.mongodb.com/docs/manual/reference/bson-types/#std-label-document-bson-type-date) objects are stored as a signed 64-bit integer representing the number of milliseconds since the Unix epoch (Jan 1, 1970). In case of invalid date or date which doesn't belong to the above valid range this is found in different format. Hence our current implementation is not able to parse and the user ended up seeing JSON parsing error.

**Comment by subrata71** [comment]
@Nikhil-Nandagopal I have started working on this. I will share as soon as I find any solution to this.
