### ISSUE TITLE
[Docs]: Connect to MsSQL (Workbench) running from a local machine

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#13286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Appsmith need to connect and get data from MsSQL Server through Workbench running from local machine.
The expected procedure involves
(1) Whitelisting Appsmith Server
(2) Exposing the IP address of the local machine to the internet whether the IP address is static or dynamic.
(2.1) Use of Ngrock or any other process to be detailed.

This requirement is based on a user query through intercom
https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100093436

### Describe the improvement

There are documentation to whitelist MsSQL running in AWS.
There are documentation to connect application running in local machine using ngrock.

This requirement is a combination of both.
Connecting MsSQL (Workbench tool) running from a local machine.

**Comment by jnikhila** [comment]
@leotom2000 - Could you please confirm if [this doc ](https://docs.appsmith.com/how-to-guides/how-to-work-with-local-apis-on-appsmith)explains the needed info?

**Comment by sumitsum** [comment]
@jnikhila The steps in the doc would have to be modified a little to connect with a local DB instead of a API server: 
- `ngrok` would have to be run like `ngrok tcp ...` instead of `ngrok http ...`
- there is no need to configure `authtoken`

**Comment by jnikhila** [comment]
Thanks, @sumitsum. This is helpful :)
