### ISSUE TITLE
[Docs]: Whitelist IP on MySQL Workbench

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#13282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/datasource-reference/querying-mysql

### Describe the problem

The process of whitelisting the Appsmith IPs in a MySQL database using Workbench is not documented.

### Describe the improvement

The documentation should contain a section where it is explained how to whitelist the IP using MySQL workbench to help and unblock users that are trying to use MySQL as a data source in Appsmith. 
Currently, we only have these docs:
- https://docs.appsmith.com/how-to-guides/aws-whitelist
- https://docs.appsmith.com/how-to-guides/how-to-work-with-local-apis-on-appsmith
There is also a topic on Stackoverflow that might help: https://stackoverflow.com/questions/44224258/how-to-whitelist-ip-addresses-in-mysql-workbench

**Comment by jnikhila** [comment]
@ajinkyakulkarni - Could you please confirm who can help us on this?

**Comment by Pranay105** [comment]
@sumitsum can you please confirm if solution on Stackoverflow works so that we can add it to docs?

**Comment by sumitsum** [comment]
@Pranay105 the StackOverflow answer points to a MySQL workbench documentation page. By reading the page, I felt like it very likely is the correct way of whitelisting users / IP, however since I have never used MySQL workbench myself, I would recommend that someone try it as well to confirm it.

**Comment by danciaclara** [comment]
https://dev.mysql.com/doc/refman/8.0/en/group-replication-ip-address-permissions.html
