### ISSUE TITLE
[Bug]: Find root cause for missing plugin id and plugin type in JS action objects

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#13280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Find root cause for #11927 - ie why plugin id and plugin Type go missing in some JS actions. 

### Steps To Reproduce

Not available.

### Version

cloud

**Comment by subrata71** [comment]
It could be related to this [Slack Thread](https://theappsmith.slack.com/archives/CPQNLFHTN/p1669142481685559). As we don't do multiple inserts/updates in one single transaction, such data inconsistencies can happen.

**Comment by riteshkew** [comment]
Closing it as RCA can be found [here](https://www.notion.so/appsmith/Data-inconsistencies-w-r-t-JS-Objects-c58f124fe20e4415b5c0e180b423b0be) in detail as mentioned by Subrata above.
