### ISSUE TITLE
[Bug]-[92]:Cyclic dependency error thrown when renaming JS functions

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cyclic dependency error is displayed when JS function is being renamed and clears when page is refreshed

### Steps To Reproduce

1. Take any existing app with JS objects or go to app at [this link ](https://release.app.appsmith.com/app/git-connected-app-with-js-objects/page1-62668caa01f360366e25e4d2/edit/jsObjects/62668cc801f360366e25e4d9)
2. Try to rename any function - observe the cyclic dependency error as seen in the video

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/19137f50abf6485aaa7e0919b7ad0fc7-00001.gif)](https://www.loom.com/share/19137f50abf6485aaa7e0919b7ad0fc7)

### Public Sample App

https://release.app.appsmith.com/app/git-connected-app-with-js-objects/page1-62668caa01f360366e25e4d2/edit/jsObjects/62668cc801f360366e25e4d9

### Version

Cloud

**Comment by rohan-arthur** [comment]
6m usage: 2300
apply 1% requirement: 23
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 23 |
| Effort (months)  | <<number>> |

**Comment by sumitsum** [comment]
@ajinkyakulkarni I am seeing this error even if I append just a single character at the end of the function name - which seems to me that it may not be related to the pause taken when renaming.

**Comment by ajinkyakulkarni** [comment]
@sumitsum we will prioritize this issue.
