### ISSUE TITLE
[Task]: RCA for promisification of JSObject function confirmation

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#13289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

https://github.com/appsmithorg/appsmith/pull/12553 Here, we removed the promisification of JSObject function confirmation due to issues faced in https://github.com/appsmithorg/appsmith/issues/12446.

- We need to investigate the root cause of the issue here and re-implement the promise method for it.

**Comment by Rishabh-Rathod** [comment]
@Druthi i believe we already re-implemented the confirmation logic that using promises. Could you please confirm?

**Comment by Druthi** [comment]
@Rishabh-Rathod Not sure what you mean here. We were trying to fix the nested functions confirmation logic but faced the blocker of not being able to stop execution to handle this case.

So no fix went out regarding this.
