### ISSUE TITLE
[Bug]: Airtable List Records integration is missing the offset field

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#13291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you list records from a table with more than 100 rows, the response will contain a field called `offset`. You use this value to call the next page, but we don't currently provide a field for the users to put this offset.

### Steps To Reproduce

1. Connect an Airtable to Appsmith and create new query.
2. Set the query type to List Records.
3. Observe that there is no field for `offset`.

### Version

Cloud 1.6.20

**Comment by felixsuarez0727** [comment]
The new offset field is added. Tests are performed to verify its operation as follows

**Comment by felixsuarez0727** [comment]
The new offset field is added. Now when you list records from a table with more than 100 rows you can put the offset value and show the next data. Tests are performed to verify its operation as follows 

If the offset is not added, the first 100 data are displayed. 
![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/785c0d34-42ef-4503-b79c-d58c3949fb43)

When the offset is entered, the following 100 data are displayed 

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/c49edff4-a6e4-4c72-b2a4-5ac74d281e0e)

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/a742717a-0a2d-4ca0-a949-05eb5c015d3a)

**Comment by felixsuarez0727** [comment]
This change is already in master.
