### ISSUE TITLE
[Bug]: In the git connect application the datasource name is displayed inside the queries 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The data source name is displayed inside the queries 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/165218572-52c7bd51-2e85-4077-a4a4-af3784361a24.png">

### Steps To Reproduce

1. connect the application to the git
2. add a page add few OAuth APIs 
3. commit and push 
4. Now in the remote 
5. Open the api 
6. Inside the code the data source type is displayed but the data source type should not be displayed 

### Version

release

**Comment by AnaghHegde** [comment]
@RakshaKShetty This is valid. We do exclude the datasource name and type in such cases. I am guessing you created a Rest API right? where the datasource information is stored inside the actions.
