### ISSUE TITLE
[Bug] Malformed JSON in API

### ISSUE THREAD

**Issue by deependersingla** [appsmithorg/appsmith#1329]
## Description
API post request is not working with JSON body of a dynamic form. Please see attached screenshot for the details.

![image](https://user-images.githubusercontent.com/3043621/96701996-e1e43a00-13ae-11eb-9a32-ad504e8f797d.png)

Error:
![image](https://user-images.githubusercontent.com/3043621/96702156-1b1caa00-13af-11eb-841d-c87d587768ae.png)

System Details:
https://whatismybrowser.com/w/8HGZTFE

**Comment by Nikhil-Nandagopal** [comment]
Hi @deependersingla , this is due to a malformed JSON exception. You can wrap your bindings in quotes to avoid this
{
"type": "{{Dropdown1.selectedOptionValue}}"
}

Hope this help 😃

**Comment by deependersingla** [comment]
thanks, worked.
