### ISSUE TITLE
[Bug]: Enter valid applicationId toast is displayed when user opens the application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Enter valid applicationId toast is displayed when user opens the application

### Steps To Reproduce

1. login to the release instance
2. click on any one app 
3. the appplication id error is displayed 

### Version

release

**Comment by AnaghHegde** [comment]
Closing this via - https://github.com/appsmithorg/appsmith/issues/13489
