### ISSUE TITLE
[Bug]: Tabs Widget - active tab is not highlighted

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#13313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="205" alt="Screenshot 2022-04-26 at 11 55 00 AM" src="https://user-images.githubusercontent.com/13262095/165259891-bfa7575a-fec5-4898-b124-83096b94bf25.png">
The active tab is not highlighted (green line at the top)

### Steps To Reproduce

Drag & Drop a new tabs widget onto the canvas.

### Version

Cloud

**Comment by somangshu** [comment]
@souma-ghosh can you check what changed here?

**Comment by souma-ghosh** [comment]
Looking into it

**Comment by dilippitchika** [comment]
@souma-ghosh don't know if you are still looking at it
There's a difference in the CSS for what we see in Pranav's laptop vs what we see in laptops' where it's working

Pranav's laptop
![image](https://user-images.githubusercontent.com/19730984/165691331-afe7146d-c842-4314-9976-48ecabfa437a.png)

My laptop (working as expected)
![image](https://user-images.githubusercontent.com/19730984/165691508-50cd6ca4-9e43-41b3-abcb-7e3f6dfa2d76.png)

**Comment by souma-ghosh** [comment]
@dilippitchika @somangshu  Tried reproducing this in my system, didn't work out. Found just now that this is not reproducible anymore even in Pranav's system
