### ISSUE TITLE
[Bug]: Cannot see result of postgres query

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

response tab indicates that 10 rows were returned, but is blank:
![Screenshot 2022-04-26 at 13 31 19](https://user-images.githubusercontent.com/94514895/165252173-f8dc1364-6c44-4253-8237-0d1ded9289c4.png)

### Steps To Reproduce

1. Create a datasource for the internal DB. Get credentials from [here](https://www.notion.so/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e)
2. 
![Screenshot 2022-04-26 at 13 32 24](https://user-images.githubusercontent.com/94514895/165252008-d37e0729-f865-4c0f-ae33-a649d3e1b1bf.png)
3. Create a simple query: `select * FROM github_issues limit 10;`
4. Run it, and you'll see that the response is empty

### Version

Cloud

**Comment by sh-TU** [comment]
In a query edit page, appsmith doesn't know how to render data types that are array. For example this kind of column in postgres
```
redirect_uris character varying(255)[] NOT NULL DEFAULT ARRAY[]::character varying[],
```
This just shows a blank response. The rest works

**Comment by Nikhil-Nandagopal** [comment]
@sh-TU thanks for the information! You are right and we are working towards fixing this ASAP

**Comment by Irongade** [comment]
A fix has been created for this on the client side. @rohan-arthur @Nikhil-Nandagopal @sh-TU
