### ISSUE TITLE
[Bug]-[12000]:Fix hover state of renaming titles

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#13329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fix hover state of
- query name
- datasource name
- api name

### Steps To Reproduce

- Open query editor
- Hover over query name. 
- **Current hover state:**
<img width="357" alt="Screenshot 2022-04-26 at 7 51 46 PM" src="https://user-images.githubusercontent.com/89374972/165322154-ac418891-5212-4eb7-9065-d7f635c4f0fb.png">

**- Expected hover state:**
<img width="351" alt="Screenshot 2022-04-26 at 7 46 27 PM" src="https://user-images.githubusercontent.com/89374972/165322132-bdd21e69-ff77-46f3-8460-8eb0f523c327.png">

### Version

Cloud

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 6000 |
| Effort (months)  | <> |
