### ISSUE TITLE
[Docs]: Add documentation to explain why `async functions in sync fields` error comes up and how to get out of it ?

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#13320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/how-to-guides/how-to-use-js-object-within-appsmith

### Describe the problem

https://github.com/appsmithorg/appsmith/issues/12179

We have noticed the error message `async functions in sync fields` which currently is removed led to error messages like
`Uncaught (in promise) TypeError: getUIConfigs.run is not a function` mentioned https://github.com/appsmithorg/appsmith/issues/13288. This is more confusing for users as they don't expect `getUIConfigs.run` to be not defined. 

Also, `async functions in sync fields` error was not easily understandable to our users as we have not defined what `async functions` are in Appsmith and what does `sync fields` mean? 

### Describe the improvement

Tasks
- Create better terminology to explain `async functions` and `sync fields` 
( example - https://github.com/appsmithorg/appsmith/issues/13288#issuecomment-1108901512 ) 
- Use those terminologies in our docs at all places relevant.

**Comment by jnikhila** [comment]
@pranavkanade - FYI.

**Comment by jnikhila** [comment]
@Rishabh-Rathod - Could you please add your inputs to the ticket so that we can pick it up?

**Comment by jnikhila** [comment]
[A video by @cokoghenun](https://www.youtube.com/watch?v=yn_8gs5w04g&feature=youtu.be) can be used to elaborate.

**Comment by Rishabh-Rathod** [comment]
Done with review. Doc shared looks good to me.

**Comment by Rishabh-Rathod** [comment]
Docs for it is added https://docs.appsmith.com/core-concepts/writing-code/workflows, hence closing the issue.
