### ISSUE TITLE
[Bug]-[230]:Newly added text gets cleared from the editor when browser window is switched soon after typing in something

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Any text typed into a newly loaded JS object is undone when current window is switched using tab key, i.e., the newly added text is cleared.

This can be repro'd only on a JS object that is being edited for the first time. Cannot repro this on a function that is currently being worked on. See video for more info

### Steps To Reproduce

1. Open an app with JS objects
2. Click enter to create a new line and quickly type in any keyword like `store` or `app` and select the first option that comes up on autocomplete by clicking on `down arrow` and `enter`
3. Immediately tab the window and come back to the window that has Appsmith - observe the newly added text cleared from the editor

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0fd114d2bfc04d3b81e3e5c7cd4ae9db-00001.gif)](https://www.loom.com/share/0fd114d2bfc04d3b81e3e5c7cd4ae9db)

### Version

Cloud

**Comment by rohan-arthur** [comment]
total users: 2300
number of affected users (guess 5%): 115

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 115 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
no longer reproducible
