### ISSUE TITLE
[Bug]: If there's a space in a value in `docker.env`, the server fails to start

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#13335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If any of the values in the `docker.env` file contain a space, like this:

```sh
APPSMITH_ADMIN_EMAILS=one@example.com, two@example.com
```

Then the server will fail to start with an error like the following:

```
line 10: two@example.com: command not found
```

There's no way to recover without going and editing the `docker.env` file to fix this.

### Steps To Reproduce

Start a new self-hosted instance, go to admin settings, in admin emails, enter `one@ex.com, two@ex.com`, and click on save and restart. The server won't start.

### Version

Self Hosted

**Comment by tomharvey** [comment]
I'd argue that this is not a `deployment` or `devops` issue as indicated in the labels of the ticket. Seems like core app business logic to be able to escape the settings it stores; regardless of how this is deployed you will run into the issue. Production deployment just makes it harder to repair.

**Comment by sharat87** [comment]
Hey @tomharvey, thanks for sharing your experience here. I agree, this issue makes for a very unpleasant experience. I'm currently working on coming up with a solution to this.

You're also right on the classification part. The reason I put it that way was, ideally, I'd want this solved in two places. First, when saving a value with spaces, ensure that the value is quoted appropriately. Second, even if some unquoted values have spaces in them, Appsmith should be resilient to it. This second part is what's a little tricky, but I'll go ahead and do the first part of the solution at least for now.
