### ISSUE TITLE
[Bug]: Hide Column - Toggle Button works in reverse

### ISSUE THREAD

**Issue by Mkallday** [appsmithorg/appsmith#13337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Appsmith Toggle Bug](https://user-images.githubusercontent.com/36720153/165363955-799175ec-2533-4e62-83ea-a9feaa3cb1ce.gif)

Toggle to hide working in reverse

### Steps To Reproduce

1. In a table
2. Press "eye" icon to hide columns

### Version

Appsmith v1.6.22-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
@Mkallday we need more information on how to reproduce this issue. Can you please provide that?
