### ISSUE TITLE
[Type]-[12000]:Outdated Design for Rest API Editor

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#13330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

It will fix following issues:
- [Inconsistent datasource dropdown](https://www.notion.so/appsmith/Usability-UI-issues-3ed292f1e7924526b2a3bd56f0a50b5c?p=fb227188f2fc49c0a74dbd899a9a0948)
- [bgColor mismatch for method dropdown](https://www.notion.so/appsmith/Usability-UI-issues-3ed292f1e7924526b2a3bd56f0a50b5c?p=f9cec4b3fe424839b14b94636bb73861)
- [Method dropdown is styled differently](https://www.notion.so/appsmith/Usability-UI-issues-3ed292f1e7924526b2a3bd56f0a50b5c?p=e841eae7c96643679500ac6896cb8832)
- [Slash icon alignment in Key Value component](https://www.notion.so/appsmith/Usability-UI-issues-3ed292f1e7924526b2a3bd56f0a50b5c?p=d7b32f8f3a3447a98741560988e32080)

### SubTasks

- Design and implement new REST API Editor as per new design system

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | <<number>> |

**Comment by rohan-arthur** [comment]
@parth-appsmith , would you please link the right resources from the design system before we can pass this on to engineering?

**Comment by parth-appsmith** [comment]
@ChandanBalajiBP 
Here is the component for reference: 
API Input Dropdown: https://www.figma.com/file/GuqV8Or2PStpE3rTknsDzk/API-Pane-Improvements?node-id=540%3A26457
API Method Dropdown: https://www.figma.com/file/GuqV8Or2PStpE3rTknsDzk/API-Pane-Improvements?node-id=541%3A26612

I am confirming a few things regarding point 2, please hold off on it for now.

Aside from this the rest of them seems to be alignment issue.

**Comment by parth-appsmith** [comment]
@ChandanBalajiBP regarding the bgColor mismatch for method dropdown, please refer to the designs below.

https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=4771%3A23705
