### ISSUE TITLE
[Bug]: evaluation delay between multiple moment() or new Date() calls creates unexpected behaviours

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#13338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The value of the binding `{{ moment() }}` at different places is different due to the millisecond delay in the evaluation of these expressions.

### Context
A user was using a date picker widget inside a form widget. They set the default value as `{{ moment() }}` and min date also as `{{ moment() }}`. The Submit button inside the form is found to be in the disabled state since the default value is a few milliseconds less than that of the min date.
https://discord.com/channels/725602949748752515/760761686549463060/963433503414960188

### Steps To Reproduce

Try binding `{{ moment() }}` in multiple text widgets and reload the page. You will find that each of the value will be different.

<img width="952" alt="Screenshot 2022-04-27 at 7 40 04 AM" src="https://user-images.githubusercontent.com/10436935/165424882-ac53d94d-abb8-4830-aef7-0a4e55fac58a.png">

### Public Sample App

https://app.appsmith.com/app/moment-evaluation-issue/page1-6268a654d8480440cf7829a1

### Version

Cloud 1.6.20

**Comment by Nikhil-Nandagopal** [comment]
@aswathkk This is expected and not a bug, the exact same would happen in a react app right?
