### ISSUE TITLE
[Feature]: Overlapping Widgets

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#13332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, it is not possible to have overlapping widgets in Appsmith. Several users have requested this feature as they would like to use a widget on top of another one and show/hide them conditionally, but today it is only possible to place the widgets next to each other.

Use cases:
1. Overlap an image widget and a video widget so that if the URL of the asset is an image, the image widget will be displayed and the video widget will be hidden, and vice-versa.
2. Overlap 2 buttons and based on a condition, show only one of them and hide the other. For this scenario, the workaround is to use a single button and set the label/color/onChange event conditionally using JS.

### Why should this be worked on?

This feature will improve the user experience by allowing users to overlap 2 or more widgets and show or hide them conditionally.

**Comment by Nikhil-Nandagopal** [comment]
Rather than overlap, we'll be enabling this via #11038 where the widget that is hidden will take up no space and thus the widget below it will show there
