### ISSUE TITLE
[Bug]-[Infinity]:Fix inconsistency with test and save buttons in datasource forms

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#13347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Datasources like postgres and airtable auto saves data. Save button in not required here.

### Steps To Reproduce

Open postgres datasource form
Make a change in any field 
Navigate away from page
Open the saved postgres datasource form again
Observe that the changes are autosaved

### Version

Cloud

**Comment by rohan-arthur** [comment]
@parth-appsmith datasource configuration is the only place where we show a save button. Should we confirm this decision and suppress autosave in this case?

**Comment by rohan-arthur** [comment]
datasources created, 6m: 12000
assume 1/3 of users go away from the configuration page with unsaved changes: 4000

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4000 |
| Effort (months)  | <<number>> |

**Comment by rohan-arthur** [comment]
will be addressed in #4381
