### ISSUE TITLE
[Docs]: Add git-connect deploy key document for AWS code commit and azure platforms

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/git-sync#connecting-to-git-repository

### Describe the problem

Currently, we have provided the documents for Gitlab, Github, Bitbucket but we are also getting requests for Azure and AWS platforms.  

### Describe the improvement

We should give clear steps on how Appsmith talks using SSH auth works with Azure and AWS platforms and what steps are required to establish the connection.

Azure: https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#step-2--add-the-public-key-to-azure-devops-servicestfs

AWS: https://docs.appsmith.com/core-concepts/git-sync#connecting-to-git-repository

**Comment by jnikhila** [comment]
@nidhi-nair - Could you please help us unblock this issue in @abhvsn absence?

**Comment by Pranay105** [comment]
This is unblocked. I'm trying out the feature currently. Will work on it soon. cc @jnikhila

**Comment by danciaclara** [comment]
AWS code commit is not supported. We are only adding steps for Azure
