### ISSUE TITLE
[Bug]-[656]:Unable to connect apps to azure devops

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to connect apps to azure devops 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/165459372-a1aaabd4-6a1f-4364-adae-cc10b22351b8.png">

### Steps To Reproduce

1. add new app
2. Click on connect git 
3. add a remote url 
4. now try to add ssh in the azure devops 
5. the error is displayed as in the attached screenshot

### Version

production

**Comment by pranavkanade** [comment]
@AnaghHegde is there a workaround for this?

**Comment by pranavkanade** [comment]
@hiteshjoshi @vuiets, can we pick this up if there is a quick fix?

**Comment by AnaghHegde** [comment]
@pranavkanade I am looking at this on priority but there is no work around at the movement. The problem here is that, we generate EDCSA ssh keys and it is not supported by Github. Prev, we used SHA type keys but the problem was Github stopped supporting this due to security reasons. This needs a discussion before raising a fix. 
Issue #1030

**Comment by AnaghHegde** [comment]
Reopening as FE work is not yet completed. @IAmAnubhavSaini is working on the FE tasks.

**Comment by RakshaKShetty** [comment]
The front end activity is still pending for this, so will be tested once FE is ready

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 82 |
| Effort (months)  | 0.25 |


Estimating that 10% of the Git users will use Azure DevOps so reach: 82

**Comment by IAmAnubhavSaini** [comment]
@BigHoss It is in release branch, should be released next week.
