### ISSUE TITLE
[Bug]-[12500]:Key value input component is inconsistent with design

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#13350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Key value input component is inconsistent with design

Ref: https://www.notion.so/appsmith/Usability-UI-issues-3ed292f1e7924526b2a3bd56f0a50b5c?p=93f9f83982cc4589834ffa9704a0beb1

### Steps To Reproduce

- Open postgres datasource 
- Observe the Host and Port key value component. **Current implementation**
<img width="726" alt="Screenshot 2022-04-27 at 12 04 19 PM" src="https://user-images.githubusercontent.com/89374972/165455984-ca32396d-f9ef-4c12-b5cd-a92cd708e83a.png">

**Expected**: https://www.figma.com/file/IfutQTUq3g97j59i3mx6Y4/Appsmith-Screens-Library?node-id=27%3A3438

 

### Version

Cloud

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2500 |
| Effort (months)  | 0.1 |

**Comment by ChandanBalajiBP** [comment]
Following is the updated screen for host address and port
<img width="1183" alt="Screenshot 2022-05-04 at 3 42 49 PM" src="https://user-images.githubusercontent.com/104058110/166662947-c403d75e-165e-4539-acd8-33bfaf0de818.png">
But when actual screen is compared with the design, there are differences in almost all components and buttons
Below is the design screenshot
<img width="763" alt="Screenshot 2022-05-04 at 3 43 03 PM" src="https://user-images.githubusercontent.com/104058110/166662917-e13c1956-e4e8-4eb3-9976-8bf20598a798.png">
tagging @parth-appsmith.
