### ISSUE TITLE
[Bug]: "Learn More" link on gitImport modal opens git sync documentation.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#13352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking "Learn More" link on git import modal, should open git import documentation i.e. https://docs.appsmith.com/core-concepts/git-sync#importing-from-a-repository instead it opens git sync documentation i.e. https://docs.appsmith.com/core-concepts/git-sync

### Steps To Reproduce

1. Click on import from a git repo
2. Click on Learn More

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
@haojin111 there was a related change to text; could you take a look at it?

**Comment by haojin111** [comment]
no, there isn't. I think!
On starting stage of import git function, the documentation isn't prepared!
Please update it yourself!

**Comment by AnaghHegde** [comment]
@Parthvi12 The Learn more link in the git import modal is correct IMO. Because this is not specific to git connect or import. 
The learn more is about the key gen protocol.

**Comment by Parthvi12** [comment]
@AnaghHegde Yes that makes more sense, closing it
