### ISSUE TITLE
[Docs] Add docs for ElasticSearch plugin

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#1336]
## Documentation Link 

ElasticSearch plugin's docs link pointing at <https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-elasticsearch> needs to be populated.

**Comment by KarthiK2601** [comment]
can you assign me this 
also the above said link is not working

**Comment by yash2189** [comment]
Hello can this be taken?

**Comment by mohanarpit** [comment]
@KarthiK2601 Go for it! 

The link is not working because once you resolve this PR, that's where your content will start to show up. You can check our documentation for other integrations (like Postgresql) at: https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-postgres

We would want a similar page for Elasticsearch as well.

**Comment by mohanarpit** [comment]
@yash2189 I'm sorry but @KarthiK2601 claimed this first, hence I've assigned it to him. 

Please claim some other issues from our list of "Good First Issue".

**Comment by KarthiK2601** [comment]
ok i am going to start working on the issue right away

**Comment by KarthiK2601** [comment]
where can i find the docs for the elastisearch ?
can you please guide me through

**Comment by mohanarpit** [comment]
@KarthiK2601 https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html may be a good place to start. Else, you can find a lot of other tutorials on Getting Started with Elasticsearch by Googling.

**Comment by mohanarpit** [comment]
@KarthiK2601 https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html may be a good place to start. Else, you can find a lot of other tutorials on Getting Started with Elasticsearch by Googling.

**Comment by Nikhil-Nandagopal** [comment]
@KarthiK2601  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by sagar-rout** [comment]
Hi, @Nikhil-Nandagopal @mohanarpit , I know elasticsearch a bit. I can start working on this.  I am not able to understand where I have to make change. If you guide me little bit, I will love to contribute. 

@mohanarpit I show your comment few months ago, I can not access postgreSQL link too. Could you please point me the example where this thing is working and where its not working. Thanks

> @KarthiK2601 Go for it!
> 
> The link is not working because once you resolve this PR, that's where your content will start to show up. You can check our documentation for other integrations (like Postgresql) at: https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-postgres

**Comment by Nikhil-Nandagopal** [comment]
@sagar-rout go for it. This is the updated link to our documentation
https://docs.appsmith.com/v/v1.2.1/datasource-reference/querying-postgres
You can ready about how to contribute to our documentation here
https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md

**Comment by Nikhil-Nandagopal** [comment]
@sagar-rout unfortunately a member of the team already had a PR raised for this but hadn't linked it here so this issue has been closed. Please do have a look at our many other good first issues :)

**Comment by sagar-rout** [comment]
hi @Nikhil-Nandagopal, Do you have any open issue related to Elasticsearch ? Otherwise I will have a look. I am using Arch based Manjaro linux, that docker setup script didn't work. It maybe not the right place to ask the question. I will raise an improvement ticket or issue.

**Comment by Nikhil-Nandagopal** [comment]
@sagar-rout I don't think we have any open elastic search issues right now. Please do raise a ticket if you'd like support for a new OS
