### ISSUE TITLE
[Feature]: Add Test Cases for GraphQL

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#13367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Need to add graphql test cases for the automation testing

### Why should this be worked on?

Automation Testing

**Comment by prapullac** [comment]
As per discussion with @Aishwarya-U-R there needs test cases to be added hence moving to In Progress

**Comment by prapullac** [comment]
Not on the release yet
