### ISSUE TITLE
[Docs] Add docs for DynamoDB plugin

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#1337]
## Documentation Link 

DynamoDB plugin's docs link pointing at <https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-dynamodb> needs to be populated.

**Comment by KarthiK2601** [comment]
can you assign me this

**Comment by KarthiK2601** [comment]
also the link shared above says the web page is not found

**Comment by mohanarpit** [comment]
@KarthiK2601 Yes, the link is throwing a 404 because the documentation doesn't exist yet 😄. The link is placed there so that we can verify if the documentation has been written in the appropriate section with the expected URL.

Also, I see that you already have 2 other issues assigned to you. Can you raise PRs and close them before picking this one up?

**Comment by yash2189** [comment]
Hi @mohanarpit , can this issue be assigned or would it be assigned on FCFS basis? 
Please tell me , thanks.

**Comment by mohanarpit** [comment]
@yash2189 It's generally FCFS. But since @KarthiK2601 already has 2 other issues assigned to them, you are free to take this one up. We just want to ensure that folks aren't overloaded with issues in a single go.

Happy contributing! 😄

**Comment by yash2189** [comment]
Hi @mohanarpit can you please tell me where can I find some information/docs about DynamoDB

**Comment by mohanarpit** [comment]
@yash2189 AWS documentation is a good starting point: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.html. Else there are a lot of tutorials online on how to work with DynamoDB.

**Comment by Nikhil-Nandagopal** [comment]
@yash2189  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by yash2189** [comment]
@Nikhil-Nandagopal Sorry I had been assigned some other issue, hence I wasn't able to complete. Is it fine if I contribute to this post Hacktoberfest?

**Comment by Nikhil-Nandagopal** [comment]
@yash2189 yes absolutely! We welcome contributions all year round 😄

**Comment by leduytung** [comment]
Can anyone show a simple example? 
I don't know how to use DynamoDB query in the Appsmith query editor.
