### ISSUE TITLE
[Docs] #13375 Improve discoverability of `storeValue` for new users

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#13375]
Currently, it is a bit difficult for newer users to notice that the Appsmith store / `storeValue` functionality exists.

Related comment from @AS-Laguna 
> I would like to mention that to new users, using the appsmith store and storeValue to set widget properties is not intuitive to most people it seems. Is there any way we can gently introduce them to this concept when they create their first app? I remember spending a few weeks wishing I could programatically change some properties before I saw the Appsmith video on the topic.

**Comment by jnikhila** [comment]
As part or Rehaul 2 we can look for search terms.

**Comment by Pranay105** [comment]
Already documented.
