### ISSUE TITLE
[Task]: Create an analytics event whenever the platform enters an "Oops! something went wrong" states

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Users very often end up in an "Oops! something went wrong" state, but we are not aware how often, and we aren't always aware when it happens. To quantify this issue, we would need to Create a backend analytics event to track how often this happens.

Note: By analytic event we mean mixpanel logs here.

### Steps To Reproduce

The issues are often difficult to reproduce, however this page doesn't do anything to offer us support. 

### Public Sample App

https://app.appsmith.com/applications/62417234c99df23699319d70/pages/62417234c99df23699319d73/edit

### Version

Cloud  v1.6.22

**Comment by nayan-rafiq** [comment]
This error is generated from FE whenever an expected data is not found. For example, one way to reproduce this is to - delete the theme of application. It would be better if we can send the analytics event from FE because FE has better context on the underlying API, response related to this error.

**Comment by sharat87** [comment]
@nayan-rafiq, I _think_ the idea here is that the FE sends the crash data to the BE, and the BE then makes the analytics call _on behalf_ of the FE. This is so that ad-blockers don't block the crash report.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 I don't think we should do that. There's a generic way to solve that using segment and we don't need to manually piple this event

**Comment by hiteshjoshi** [comment]
We will be implementing this on FE.
