### ISSUE TITLE
[Bug]-[140]: Date picker shows random month when a custom min date is set

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#13389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we choose a date other than the current date as minDate in datepicker widget, it shows a random month in the date picker popup.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/48be010e55284b23b7d59764104247f1-00001.gif)](https://www.loom.com/share/48be010e55284b23b7d59764104247f1)

### Steps To Reproduce

1. Add a Date picker widget to canvas
2. Set tomorrow's date as minDate
3. Remove defaultDate
4. Open the date picker popup on the canvas
5. Observer that it shows a random month 

### Version

cloud

**Comment by sbalaji1192** [comment]
We need to set the `initialMonth` prop on the `DateInput` blueprint component based on the min, defaultDates.

**Comment by dilippitchika** [comment]
Reach - Devs configuring the minDate field. Assuming 50% are future dates.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 140 |
| Effort (months)  | 0.5 |

**Comment by shadabbuchh** [comment]
On setting tomorrow's date or any other date as `Min Date`, the `Datepicker` widget allows the developer to only select from that date and not before it.
https://www.loom.com/share/90c861481fb547a78dcb3ec0df09f3a1
