### ISSUE TITLE
[Bug]: Unable to see application in home page after the git connect flow is aborted in middle 

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#13385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

User is Unable to see application in home page after the git connect flow is aborted in middle 

### Steps To Reproduce

1. Create an app and click on connect to git
2. Enter the url and generate keys
3. Save the edit mode url of the app in a different place
4. Now go back to home page and refresh 
5. Observe the app is missing from the home page

### Version

Cloud v1.6.22

**Comment by rubabuddin** [comment]
also running into the same issue

**Comment by AnaghHegde** [comment]
@rubabuddin Thanks for reporting this issue. The fix is on the way and will be pushed very soon. We are sorry that you are facing this issue.

**Comment by rubabuddin** [comment]
thanks @mohanarpit @AnaghHegde! are we just waiting for the hotfix to merge to see the issue resolved?

**Comment by AnaghHegde** [comment]
@rubabuddin We are going to test this in our release env first and if things look good then we will push this change for all the user. It is delayed due to some other internal issue, apologies for that. Ideally it would be out by now. Please wait for sometime. I will update this thread once the fix is live.
