### ISSUE TITLE
[Docs] : Add - Multiple envs and git version control documentation.

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#13380]

**Comment by jnikhila** [comment]
@pranavkanade - Could you please add the required details to the ticket?

**Comment by pranavkanade** [comment]
@AnaghHegde @abhvsn can we get a draft for this? We'll need a couple of images and steps to do this.

**Comment by pranavkanade** [comment]
I've listed the steps here - https://discord.com/channels/725602949748752515/968852830062534676/968858007163248671

@danciaclara, do you think we should create a youtube tutorial about this?

**Comment by AnaghHegde** [comment]
@pranavkanade I will take this up tomorrow

**Comment by AnaghHegde** [comment]
@pranavkanade There is a video from lightning demo, is that not enough? On git import we have docs containing step by step by guide.

**Comment by jnikhila** [comment]
@cokoghenun - Could you please share the video link from lighting demos as referred by @AnaghHegde?

**Comment by jnikhila** [comment]
As per your comment @pranavkanade - Are we creating a youtube tutorial? 
@pranavkanade / @danciaclara - Could you please confirm if we need to pick this up for documentation?
