### ISSUE TITLE
[Epic]: Airtable and Twilio Stability

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#13399]
### Objective

This epic is meant to capture the services in scope for the next phase of SaaS integrations. It also includes efforts to fix issues with older integrations.

### Success Metrics

| Goal          | Metric         |
| ------------- | -------------- |
| Productionize 1 integrations  |  |
| Reduce friction with older integrations |  |

### Requirements

| Requirement   | User Story    |
| ------------- | ------------- |
| Must implement Twilio APIs  | as a user, I want to be able to access Twilio APIs easily on Appsmith  |
| Must fix Airtable issues | as a user, I want to be able to use all aspects of Airtable APIs |
| Must fix Twilio issues | as a user, I want to be able to use all aspects of Twilio APIs |

### Out of Scope

- All other SaaS Integrations (Hubspot, Hugging Face, Zenhub, etc).

### RACI matrix

| Role | Assignees |
| ------------- | ------------- |
| Responsible   | @felixsuarez0727  |
| Accountable   | @felixsuarez0727  |
| Consulted     | @rohan-arthur , @kocharrahul7 |
| Informed      | @ajinkyakulkarni , @Nikhil-Nandagopal |

**Comment by rohan-arthur** [comment]
not our focus for the foreseeable future, will get around to this at a later time.
