### ISSUE TITLE
[Bug]: Unable to rename JSObject on new branch when connected to git 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#13407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/165706194-18489d42-e24e-42a4-8e5a-fdc2b161d6b5.mov

### Steps To Reproduce

1. Switch to a new branch "feat/abcd" on app connected to git 
2. Create new JsObject 
3. Rename it from jsEditor
4. Observe the name is not changed
5. Rename it from context menu
6. Observe the name doesn't change.

### Version

Cloud

**Comment by abhvsn** [comment]
@Parthvi12 not able to reproduce this on Mozilla v99.0. Can you please provide the browser along with the version? Also, provide the network logs wanted to check if API is getting executed.

**Comment by Parthvi12** [comment]
As discussed with @abhvsn the issue seems to be with JSEditor and not git, API is getting executed successfully and renaming works on hard refresh.

**Comment by abhvsn** [comment]
To provide more info, this is happening on chrome Version 100.0.4896.127 (Official Build) (arm64)

**Comment by bharath31** [comment]
Was able to reproduce this issue
![Screenshot 2022-11-15 at 8.58.01 PM.png](https://images.zenhubusercontent.com/62eb9bbb5f4e41370eb42266/9cecb00a-3c91-43c0-b321-a9e24425adb7)


@ApekshaBhosale @subrata71 @nidhi-nair is this related to https://github.com/appsmithorg/appsmith/issues/14755?

**Comment by subrata71** [comment]
> @ApekshaBhosale @subrata71 @nidhi-nair is this related to #14755?

Yes, the JS object name conflict issue is same as [this](https://github.com/appsmithorg/appsmith/issues/14755)
