### ISSUE TITLE
[Bug]-[48]:Save button remains disabled in S3 datasource

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#13405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue was found in Appsmith's Internal Apps i.e. `Deprecated A Force Admin Panel`

### Steps To Reproduce

1. Open pre existing S3 datasource 
2. Select `Amazon S3` as S3 provider
3. Fill all the required fields
4. Save button remains disabled

### Version

Cloud

**Comment by sumitsum** [comment]
Another user has reported that the button becomes disabled after saving the datasource. https://www.loom.com/share/bd7a569d54694fbeb79111711ec91a1f

**Comment by rohan-arthur** [comment]
S3 6m usage: 236
Assume this affects 10% of the users: 23.6

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 24 |
| Effort (months)  | <<number>> |

**Comment by pranavkanade** [comment]
@sumitsum, is there a workaround for this issue?

**Comment by sumitsum** [comment]
@pranavkanade creating a new datasource should have the button enabled.

**Comment by rohan-arthur** [comment]
another workaround is hitting the `Back` button - if the form has some unsaved changes then you should see a save dialog.

**Comment by rohan-arthur** [comment]
this could be a regression introduced https://github.com/appsmithorg/appsmith/issues/26126

**Comment by rohan-arthur** [comment]
Explanation: When I open the s3 datasource for editing, and if I make _any_ changes in the form fields, the `Save` button should get enabled. Also explained in the attached video.
https://github.com/user-attachments/assets/19382946-a0f5-4c93-a665-7b189458b9ac

**Comment by SaiCharanChetpelly31** [comment]
HI @rohan-arthur @rashmi-rai @pranavkanade @sumitsum Is this issue still exists? Iam unable to reproduce it.

**Comment by saiprabhu-dandanayak** [comment]
Hi **@rohan-arthur** , When I open the `s3 datasource` for editing, and selecting `Amazon s3` for amazon service provider dropdown the `secret key`  field is being cleared and `save` button is in disabled state and upon entering the `secret key` the save button is being enabled. i am uable to reproduce this issue,
can you pls confirm this once.

**Comment by PrasadMadine** [comment]
Hi @rohan-arthur , I am unable to reproduce this issue. Is this still exists?
