### ISSUE TITLE
[Feature] Message event details

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#13419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Implement a newer version of the IframeWidget, so that users can use the newer version and have access to all the metadata provided by the [`message`](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event) event.

### Why should this be worked on?

The browser's [`MessageEvent` ](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event)provides a few metadata which can be useful when building web application checks and workflows.
In the IframeWidget, we only have access to the event's data, but not the other properties like `source`, `origin`, etc.

**Comment by somangshu** [comment]
Quoting the user:
> Mozilla advises an origin and optionally a source check (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns). Appsmith now only performs a source check (https://github.com/appsmithorg/appsmith/blob/21a9f5725f9281be8ea7668ecede09c9ad3a3102/app/client/src/widgets/IframeWidget/component/index.tsx#L90). is it safe to use this postmessage mechanism now or is there a risk that someone else (not the host in the iframe itself) can send a message to appsmith which then is exposed to the appsmith application ?

**Comment by somangshu** [comment]
[Intercom thread](https://app.intercom.com/a/apps/y10e7138/conversations/164629100093256?redirectTo=feed )

**Comment by somangshu** [comment]
@souma-ghosh any update here?

**Comment by souma-ghosh** [comment]
@somangshu Not much progress yet. Will be prioritising this next week

**Comment by unknown1337** [comment]
@riodeuno (thanks for creating the issue, forgot to say that). Could you update us? thanks!

**Comment by dilippitchika** [comment]
Hey @unknown1337 we are testing this, if everything is good this will be out in a couple of weeks

**Comment by unknown1337** [comment]
Thanks!

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
