### ISSUE TITLE
[Feature]-[300]:Improve import application UX flow

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As per the current implementation, there is no loading state-provided when a user tries to import the application. This results in a bad UX when we have a large application that takes more than 10sec to import the app successfully.   

Checkout the current experience:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f317f4bc453f4963859fea41ad96325a-00001.gif)](https://www.loom.com/share/f317f4bc453f4963859fea41ad96325a)

Design handoff: https://www.figma.com/file/IOx0WPeZsChCaXwgVxU3LX/Import%2FExport-Design?node-id=1594%3A8197
<img width="792" alt="Screenshot 2022-04-28 at 3 48 13 PM" src="https://user-images.githubusercontent.com/41686026/165731495-124f97e6-e425-4c47-80be-fa1284f38471.png">

### Why should this be worked on?

This will improve the import application UX especially for larger apps.

**Comment by abhvsn** [comment]
@Debsourabh I think instead of a linear loader circular one will make more sense, as for small apps we get the response within a sec but for others, this can go beyond 20secs as well.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 150 |
| Effort (months)  | 0.25 |
