### ISSUE TITLE
[Feature]: Ability to suppress the Toast messages in specific known failure scenarios

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#13421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. User wants ability to suppress the Application toast messages in certain scenarios where he knows there is going to be no data & do not expect toast error & data in those cases
2. User feels - this alert could be unnecessary in such places & hence wants to suppress it

### Why should this be worked on?

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100095478#part_id=comment-164629100095478-14470174776

**Comment by Nikhil-Nandagopal** [comment]
@Aishwarya-U-R the user should be able to do this by assigning an onError callback to the query
