### ISSUE TITLE
[Bug]: PreparedStatement issue when there is a JSON column value

### ISSUE THREAD

**Issue by leotom2000** [appsmithorg/appsmith#13422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MySQL with one of the columns has a JSON value works fine when prepared Statement is off.
Fails when prepared statement is off.
Similar issue happens when we use IN () in the query.

 

### Steps To Reproduce

This query (not exact) fails with prepared statement on (may be syntax too, need to be tested )
{
"value": "INSERT into Table SET name = $1, mac_id = $2,\nerp_id = $3,stat = 'REGISTERED',
checks =\"{'Step-1': $4,\n'Step-2': $5,\n'Step-3': $6 ,\n'Step-4': $7 ,\n'Step-5': $8 ,\n'Step-6':$9 }\",
_date = $10,end_date = $11, created_by = $12",
"parameters": {
"$1": "","$2": "","$3": "",
"$4": false,"$5": true,"$6": true,"$7": true,"$8": true,"$9": true,
"$10": "","$11": "","$12": ""
}
}

Original issue by discord user :
https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100095496

### Version

Self hosted

**Comment by subrata71** [comment]
It's hard to understand the problem statement with this piece of information. I think the information is inadequate and hence closing the issue.
