### ISSUE TITLE
[Feature]: Adding Variables in src When App Is Embedded in iFrame

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#13424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

If the user embeds the app in an iFrame, they should be able to add more variables to the src and access those variables inside Appsmith like a GET variable.

https://discord.com/channels/725602949748752515/760761686549463060/968954294814535710

### Why should this be worked on?

This would improve the user experience as the user would be able to access the variables added in the src of an iFrame when embedding the app.

**Comment by ame-appsmith** [comment]
@nayan-rafiq

**Comment by somangshu** [comment]
@ame-appsmith thanks for the feature request, Are you talking about iframe widget inside appsmith or embedding appsmith itself in external iframe?

**Comment by bobhilbig** [comment]
> @ame-appsmith thanks for the feature request, Are you talking about iframe widget inside appsmith or embedding appsmith itself in external iframe?

Embedding appsmith itself in an external iframe.

**Comment by Nikhil-Nandagopal** [comment]
@bobhilbig thanks for the information! So something like a message listener that listens to a postMessage from the parent iFrame inside appsmith is what you're looking for?

**Comment by bobhilbig** [comment]
The iframe embedding appsmith contains a link to appsmith. I would love to use php to append some GET information to that link. Thats the easiest method.

But if it needs to be part of a POST variable that could work too.

**Comment by Nikhil-Nandagopal** [comment]
@bobhilbig you can do that today as well. You can append a query param to the link as 
https://<link>?email=abc@gmail.com
and access this from within the iFrame appsmith app as {{appsmith.URL.queryParams.email}}

**Comment by bobhilbig** [comment]
Is there a way for POST variables to be retrieved in an iframe too?

**Comment by bobhilbig** [comment]
Actually, possibly moot, if i can just embed a POST variable into the iframe link. so this is good.
