### ISSUE TITLE
[Bug]: User notices onPageLoad query failing when navigating to the page

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#13435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It was noticed that the user's `onPageLoad` queries were failing intermittently when navigating to the page.

<img width="501" alt="Screenshot 2022-04-22 at 3 17 50 PM" src="https://user-images.githubusercontent.com/23132741/165896888-bb45d897-baa2-4e7f-bfc4-c58ce1473578.png">
<img width="964" alt="Screenshot 2022-04-22 at 3 18 30 PM" src="https://user-images.githubusercontent.com/23132741/165896902-8c1b227e-4a60-4564-9f69-edd4da759c7b.png">
<img width="980" alt="Screenshot 2022-04-22 at 3 21 36 PM" src="https://user-images.githubusercontent.com/23132741/165896915-1bdee4e8-f007-4366-b45b-977bdbcab7da.png">

### Steps To Reproduce

Unfortunately, we don't have clear steps to reproduce this.

### Version

1.6.x

**Comment by rohan-arthur** [comment]
@ohansFavour confirmed with user that this is not reproducible anymore.
