### ISSUE TITLE
[Bug]: Longer column names in table widget causes overflow on the Filter UI

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On connecting to a Snowflakes DS, where the tables have longer column names, it causes the text to overflow in the Filter UI. 
Expected behaviour - Text should not overflow. It could be shown truncated (...) with a tooltip appearing on hover to show the entire name.

### Steps To Reproduce

1. Drag and drop a table widget.
2. Add a snowflake data source - Credentials can be found [here](https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e)
3. Create a query - Select * from call_center limit 10; 
4. Save this query and bind the table to this query. (in the table data field - {{Query1.data}} )
5. Now click on Filters in the table UI , choose WHERE and select a column name. Here we see that the column name text is cutoff. For every clause that is added, the same behaviour is seen.

<img width="1058" alt="Table_Datafrom_SnowflakeDB_LongColumnName" src="https://user-images.githubusercontent.com/101863839/165905670-1a2676dd-a5a0-4bfd-9001-e5b458de472d.png">

### Version

Release

**Comment by dilippitchika** [comment]
Fixed in table v2, closing this and adding the label
<img width="731" alt="Screenshot 2022-08-18 at 12 53 32 PM" src="https://user-images.githubusercontent.com/19730984/185334796-b2e3d642-4c0a-4657-bfa8-280466acf0f5.png">
.
