### ISSUE TITLE
[Bug] Layout DSL goes into a bad state after certain Widget Operations

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1344]
## Description

Not exactly sure why, but after a certain operations, the keys of our critical widget structure change and put the layout and the app in the bad state.

Two instances noticed so far:
- User updated a widget name and the name replaced by the `type` key.
- type had a `date` string attached to it `type`

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you provide the pageIds here

**Comment by Nikhil-Nandagopal** [comment]
lowering priority since we can't repro it

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu closing this since we have no repro
