### ISSUE TITLE
[Task]: Remove the callout for Clean URLs

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Remove this callout, leaving the icon on the bottom right with the red dot notification
<img width="376" alt="Screenshot 2022-04-15 at 10 37 14 AM" src="https://user-images.githubusercontent.com/20532920/165941162-8a8cf30c-dd52-4198-b51c-dcbee1e05362.png">

**Comment by arunvjn** [comment]
@kocharrahul7 Not sure if there is anything that needs to be changed here. We have already removed the callout from showing up automatically for users. It's now more like a tool-tip and doesn't get triggered on it own.

**Comment by kocharrahul7** [comment]
Okay, fantastic
