### ISSUE TITLE
[Task] Auto flag queries on page load

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1345]
## Description
Users forget to flag queries as on Page load. We can pre-empt this for queries bound to widgets and not triggered by any widget. We should also let users know that the query / API was flagged

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you help with the exact field that the front end sends which can tell the backend that these are the trigger properties so don't flag these queries onPageLoad

**Comment by hetunandu** [comment]
`dynamicTriggers` map in a widget has these properties

**Comment by mohanarpit** [comment]
@hetunandu To the best of my understanding, `dynamicTriggers` are the actions that DON'T need to be invokved onPageLoad, while the `dynamicBindings` are the ones that should be invoked onPageLoad. Am I right over there?

**Comment by hetunandu** [comment]
These names are about to change in #1625 but i will use the old names here

`dynamicBindings` is maintained by the client to flag widget properties that have `{{ bindings }}` but cannot "trigger" an action

`dynamicTriggers` is maintained by the client to flag widget triggers that are used (all need to have bindings) that can only trigger actions and not return a value

I think for onPageLoad, on action edit we set query param `flag=true|false` on the0 api that indicates that the user has set onPageLoad manually and hence should not be `automagically` flagged by the server

cc @trishaanand correct me if I am wrong here

**Comment by trishaanand** [comment]
@nidhi-nair : 
Today, we walk the entire DSL to extract all the widget names. In this step, we should also first read `dynamicBindings` key. If present, this would be of the following type :
"dynamicBindings": {
                "value": true,
                "text": true
              }
`value` and `text` represent fields that must exist at widget level which would contain mustache bindings. We should use helper function `MustacheHelper.extractMustacheKeysFromFields` at this point by passing the values stored in keys `value` and `text` and store these mustache keys. 
These mustache keys then become our first list of possible actions which can now be marked on load. The thing to note here is that the words that have now been added to mustache keys would also contain words other than action names (like other widgets, js functions, etc.) We would be fetching all actions whose names match any in the above list and mark them as on load (except the actions which have the field userSetOnLoad set to true. For such actions, we make no changes).

**Comment by nidhi-nair** [comment]
@trishaanand From what I understand, the `dynamicBindings` key should have a list of all possible widget attributes that would be referring to APIs or DB queries. Would we then not resort to simply using that list instead of the scan?
