### ISSUE TITLE
[Bug]: Increase Field width in all possible DataSource Query Editor pages

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#13460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ex: S3:
<img width="1206" alt="Screenshot 2022-04-29 at 6 09 27 PM" src="https://user-images.githubusercontent.com/91450662/165946128-e9e3c4c4-1e8f-4aa5-9150-110f80aab0dc.png">

Ex: ElasticSearch - Path field:
<img width="878" alt="Screenshot 2022-04-29 at 2 07 11 PM" src="https://user-images.githubusercontent.com/91450662/165945760-55b274d9-a455-40bb-9785-debc90ef6375.png">

### Steps To Reproduce

1. Open any relevant Query Editor page for a Data source
2. Observe few fields width can be increased to fit in some more character length so user gets a fuller view of value in such fields without having to click it
3. DataSources with scope: Gsheet, Mongo, S3, ElasticSearch etc

### Version

Prod/Release v1.6.23

**Comment by parth-appsmith** [comment]
@Irongade please use this designs as reference for setting the width for input fields. We have used the same structure for google sheets uqi.

https://www.figma.com/file/Qs7p5frNx7uEfVYpADGk0d/Query-Pane-Improvements?node-id=503%3A35248
