### ISSUE TITLE
[Bug]: default text is not working as expected when it is changed onTextChange of Input widget.

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#13469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the store value which is bound to the default text of an input widget gets changed on `onTextChange` of the same widget. the UI is not reflecting the updated text. it is still showing the entered value. for more context please refer here - https://discord.com/channels/725602949748752515/760761686549463060/969666760406089748

https://user-images.githubusercontent.com/5328605/166094634-c888ec1d-8c67-4f42-8f35-bfaefa8d45cd.mov

### Steps To Reproduce

use this sample to the app to repro - https://app.appsmith.com/app/dynamically-change-input-text/page1-626ca841f18dd4514ab56580/edit

### Public Sample App

https://app.appsmith.com/app/dynamically-change-input-text/page1-626ca841f18dd4514ab56580/edit

### Version

cloud

**Comment by sbalaji1192** [comment]
@Rishabh-Rathod This could be related to #12318

**Comment by Rishabh-Rathod** [comment]
This is not related to #12318 and will be separately fixed.

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/user-attachments/assets/9fb67b88-6ffd-46d5-b85c-17de98e3bdd3
