### ISSUE TITLE
[Bug]: Run button can be clicked even when in disabled state

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Extension of #12144 where run button can still be clicked when in disabled state during certain edge case when execution is taking a while since UI is slightly slower to revert back.

[Slack conversation link detailing the scenario](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1651214499370879)

### Steps To Reproduce

1. Throttle network connection or use an API that's fetching a large dataset
2. Continue to click on the Run button while observing execute calls go through on the browser console
3. There are certain times when more than one call is registered  while clicking on the disabled run button

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/daf4fcf19f2247ae950e04753e50cdbf-00001.gif)](https://www.loom.com/share/daf4fcf19f2247ae950e04753e50cdbf)

### Version

Cloud

**Comment by Irongade** [comment]
After debugging, this issue is not reproducible and the misconceptions about its operation has been cleared.
