### ISSUE TITLE
[Fature] Integration Grouping/Scoping for SaaS Integrations with many commands

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13471]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

- Add a way to group or scope integrations for cases when there can be many supported commands.

### Why should this be worked on

- Improve the UX when dealing with integrations for platforms that offer many APIs.

### Details

(Using HubSpot as an example)

- The whole HubSpot API is big.
- We could potentially implement more than 300 commands for HubSpot.
- If everything is kept under the same integration, having a select with 300+ options will be bad UX.
- If we separate each API section (CRM, CMS, Files, Settings, etc) the DataSource view will get "polluted" by many HubSpot Datasources.
- This issue addresses that problem. Work on multiple fronts (UX, FE and BE) will be needed to make sure we approach this the right way.
- This will provide a solution for future Integrations that support **many** commands.

### Tasks

1. Agree on the desired UX for this case.
2. Changes to the BE to allow grouping (if needed).
3. Changes to the SaaS App to group Integrations.
4. Changes to the FE to give users the ability to choose the "scope" on a group of integrations from the same platform.

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/cc7a07e4-637d-4c9f-95cc-30ad44153e7f)
![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/6bd04177-0768-4d2a-911c-e019caff0622)

**Comment by rohan-arthur** [comment]
not our focus for the foreseeable future, will get around to this at a later time.
