### ISSUE TITLE
[Docs] Add documentation for Redis Plugin

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1347]
## Documentation Link 

Need to add a section in our documentation that informs the user about Redis server integration.

## Describe the problem

We've added Redis server as an integration to Appsmith. We need to have a page (similar to the [Postgres documentation](https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-postgres))

## Describe the improvement

Please refer to the [contribution doc](https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/CONTRIBUTING.md) to check out how to create documentation pages.

**Comment by KarthiK2601** [comment]
please assign me this task

**Comment by Nikhil-Nandagopal** [comment]
@KarthiK2601 go for it! 🎉 
Be sure to have a look at our contribution guidelines and our existing documentation format for db integrations :)

**Comment by KarthiK2601** [comment]
yeah sure i will have a look at that !

**Comment by KarthiK2601** [comment]
can you please guide me through

**Comment by KarthiK2601** [comment]
i have forked the appsmith-docs repo

**Comment by KarthiK2601** [comment]
which category does the Redis server integration documentation come under ?
Documenting widgets, functions, DB integrations or uploading assets ?

**Comment by KarthiK2601** [comment]
it comes under the plugin category, and there is no Guidelines for how to document New plugins

**Comment by mohanarpit** [comment]
@KarthiK2601 It comes under the section of "Connecting to Databases". The documentation for Redis should be similar to the Postgres one linked in the issue.

Let me know if you have any other questions regarding this.

**Comment by KarthiK2601** [comment]
can you please guide me through

**Comment by mohanarpit** [comment]
@KarthiK2601 What are you stuck with? Please refer to the [contribution doc](https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/CONTRIBUTING.md) to check out how to create documentation pages.

A new page needs to be added in the "Connecting to Databases" section of the document. This new page needs to tell the user how to connect to a Redis instance and query it using Appsmith.

**Comment by Nikhil-Nandagopal** [comment]
@KarthiK2601  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!
