### ISSUE TITLE
[Bug]: Server side Filtering is not working for Select and Multi Select widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#13495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9e00f453bac344caaaf8486d60269e94-00001.gif)](https://www.loom.com/share/9e00f453bac344caaaf8486d60269e94)

### Steps To Reproduce

1. Add Select/Multi Select Widget onto the canvas
2. Add a query from datasource. eg (MYSQL): SELECT * FROM users where role = 'Admin' ORDER BY id LIMIT 10 
3. Bind the query with select/multi select widget to make it as dropdown options. eg: {{Query1.data.map( (obj) => { return  {'label': obj.name, 'value': obj.name } })}}
4. Enable server side filtering and now search the text in filter and observe that no filter is happening

### Version

Cloud/Production

**Comment by dilippitchika** [comment]
@chandannkumar have you also bound the onFilterUpdate event to work? It shows up in actions/events when server side filtering is enabled?
![Screenshot 2022-05-04 at 2 29 12 PM](https://user-images.githubusercontent.com/19730984/166651494-07a8441b-8058-47d6-b624-686a1157b663.png)

**Comment by chandannkumar** [comment]
@dilippitchika Yes, i tried onFilterUpdate  event too
https://www.loom.com/share/1c6bb3ecad0a4410a1f1f942a35636b5
Please let me know if i am missing anything here

**Comment by dilippitchika** [comment]
@chandannkumar the onFilterUpdate event has to actually search using a query. Similar to how onSearchTextChanged works in table.

**Comment by chandannkumar** [comment]
It seems working fine on Server side filtering and able to get the filtered results on Select & Multi Select widget
Closing this, as this issue doesn't exists
