### ISSUE TITLE
[Bug]: Incorrect message displayed to user when no data is returned to the debugger

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a JS function has the return keyword but does not return any value back to debugger then we show an incorrect message asking if the return keyword has been used

### Steps To Reproduce

1. Copy paste below code into an object and hit run
```
export default {
	yellow: () => {
		return Api1.run()
		.then(() => showAlert("Success"))
		.catch(() => showAlert("Error))
	}
```
2. Observe the debugger message as seen in the screenshot

![image](https://user-images.githubusercontent.com/79509062/166208968-5120d547-54aa-4260-84d9-0789edeef9d6.png)

### Version

Cloud

**Comment by ohansFavour** [comment]
Hey @noobyogi0010 , thanks for showing interest in this issue. Yes, you can pick it up.

**Comment by noobyogi0010** [comment]
@ohansFavour what should be expected behaviour for this scenario?

**Comment by ApekshaBhosale** [comment]
@parth-appsmith can you please pitch in here?
