### ISSUE TITLE
[Bug]-[100]:Video icon is not center aligned for table widget with column type Video

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#13497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Video icon is not center aligned for table widget with column type Video

![image](https://user-images.githubusercontent.com/92293815/166217421-512380ae-d8b9-4ff9-886e-3c905434b299.png)

### Steps To Reproduce

1. Drag and drop table widget
2. Create new column
3. Change column type to Video > Add a computed value and observe 

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.5 |

**Comment by souma-ghosh** [comment]
@shwetha-ramesh Unable to reproduce this. Could you check of this issue still persists?
