### ISSUE TITLE
[Bug] docker failed to start

### ISSUE THREAD

**Issue by jroxendal** [appsmithorg/appsmith#1349]
The `appsmith-internal-server` of the docker components failed after running the install.sh script. 

`java.lang.IllegalArgumentException: the salt parameter must not be empty`
<details>
<code>appsmith-internal-server_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
appsmith-internal-server_1  |  - Application run failed
appsmith-internal-server_1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authenticationSuccessHandler' defined in URL [jar:file:/server.jar!/BOOT-INF/classes!/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'examplesOrganizationCloner' defined in URL [jar:file:/server.jar!/BOOT-INF/classes!/com/appsmith/server/solutions/ExamplesOrganizationCloner.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'datasourceServiceImpl' defined in URL [jar:file:/server.jar!/BOOT-INF/classes!/com/appsmith/server/services/DatasourceServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 13; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'encryptionServiceImpl' defined in URL [jar:file:/server.jar!/BOOT-INF/classes!/com/appsmith/server/services/EncryptionServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.appsmith.server.services.EncryptionServiceImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: the salt parameter must not be empty</code>
</details>

The install.sh script failed, all the other services started correctly but this one.

### Steps to reproduce the behaviour:

1. run install.sh according to docker install documentation.
2. one service fails to start.

Image details:
`appsmith:$ docker image inspect appsmith/appsmith-server`
output:
<details>
<code>
[
    {
        "Id": "sha256:7cddbe549e920225ba1e34a7f41039b0741b520cf13ed6a697d0d0b3beba8bb2",
        "RepoTags": [
            "appsmith/appsmith-server:latest"
        ],
        "RepoDigests": [
            "appsmith/appsmith-server@sha256:7d457cf9c9c8349c4c4df47ca30215b8a52352786057a9684e2cb7ca470cb2e8"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-10-21T05:28:38.314688895Z",
        "Container": "7b6f0d191c878afef2c962bc7528a357b30628197867161278e00e9f3f919e1d",
        "ContainerConfig": {
            "Hostname": "7b6f0d191c87",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "JAVA_VERSION=jdk-11.0.8+10",
                "JAVA_HOME=/opt/java/openjdk"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/bin/sh\" \"-c\" \"/entrypoint.sh\"]"
            ],
            "Image": "sha256:87647735cbe2ccd77c7c3c20d49c1657d97e9275c3e5a286343e336881bdd75e",
            "Volumes": {
                "/tmp": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "tech@appsmith.com"
            }
        },
        "DockerVersion": "19.03.13+azure",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "JAVA_VERSION=jdk-11.0.8+10",
                "JAVA_HOME=/opt/java/openjdk"
            ],
            "Cmd": null,
            "Image": "sha256:87647735cbe2ccd77c7c3c20d49c1657d97e9275c3e5a286343e336881bdd75e",
            "Volumes": {
                "/tmp": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "tech@appsmith.com"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 215655132,
        "VirtualSize": 215655132,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/15c50451780db3795955bdc6b39dd937f7d25e188222c00d0d67d1dd61338091/diff:/var/lib/docker/overlay2/c0aa0effe9019a45a37cd7df2250db98e7f12b3571e6430b18f02f8469095ba5/diff:/var/lib/docker/overlay2/7304c4110f544389891a73709b16bd06972368f6d1341600623b16930d456caf/diff:/var/lib/docker/overlay2/991817dd700189d961decdd554b6f176630fb0fa76ea62a18cf2fda3bd1e397f/diff:/var/lib/docker/overlay2/4e7a3765c59e5ff726c0b73f286962cca187ab79a34bc24ee013d74f5fea76e3/diff:/var/lib/docker/overlay2/fd0dd020172ff2ba372bb88f56a02ac19821b3c2515fd21da04ffa5c5f750b87/diff",
                "MergedDir": "/var/lib/docker/overlay2/e0a54234c15929e546eaf5c76db16db099262e9fe7359983e6f1cc17390780b2/merged",
                "UpperDir": "/var/lib/docker/overlay2/e0a54234c15929e546eaf5c76db16db099262e9fe7359983e6f1cc17390780b2/diff",
                "WorkDir": "/var/lib/docker/overlay2/e0a54234c15929e546eaf5c76db16db099262e9fe7359983e6f1cc17390780b2/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:50644c29ef5a27c9a40c393a73ece2479de78325cae7d762ef3cdc19bf42dd0a",
                "sha256:23619cbdaa4c218f44d550204f9577405098031a955dd4c4d7b5076445ece745",
                "sha256:c2ac4178ebdc4e60dadf823e420d066661fc9a2a0eece21b82d51092a7794c28",
                "sha256:b2584eeae51c1f431eab682ba99bf8e451de39a88f79779f26cb9bdb7dc12239",
                "sha256:1e23296d1bf1698eac4059bf21f48596e6b7a648b6051842dcb9aed407754c1f",
                "sha256:91bf8854adf0056d5aca39989229af303ad7c7e42242dc641f82bdebf8422d23",
                "sha256:7c880f9141403e63681f2c29dbd5dd328e4f9d9a7f427fe87e0dfba15c89110f"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
</code>
</details>

### Important Details
 - Version: latest install.sh
 - OS: MacOSX 
 - Docker desktop 2.4.0.0

**Comment by Nikhil-Nandagopal** [comment]
Hi @jroxendal 👋  
Sorry you faced this issue. 
@mohanarpit could you have a look and help here? The script seems to be working on my mac!

**Comment by mohanarpit** [comment]
@jroxendal This error is occurring because the `encryption.env` file that got generated doesn't have the keys: `APPSMITH_ENCRYPTION_PASSWORD` or `APPSMITH_ENCRYPTION_SALT` . These are mandatory for the server to start up correctly. Can you please confirm this?

**Comment by jroxendal** [comment]
I can confirm this: if I edit the generated file and input values, it start working! Thanks for the quick reply.

**Comment by jroxendal** [comment]
You should probably document this :)

**Comment by Nikhil-Nandagopal** [comment]
@jroxendal this shouldn't have required you to add a salt value. fresh installations don't require salts but the script was confusing so we understand how you landed here. 
Steps we're taking to improve this
- Update the script with better text so users performing new installs are not confused by the flow which connects them to their existing installations
- Add a check so that an empty salt value cannot be entered during installation.

**Comment by Gi972** [comment]
Hello,

I have the same issue, and same I could to fix it with text. it's may because during install I have this error 
```
Set the mongo root user: gi    
Set the mongo password: 
Input error
Input error
```
But I think it's not fixed

**Comment by Nikhil-Nandagopal** [comment]
@Gi972 I am seeing an error when an empty password is being set

+++++++++++ ERROR ++++++++++++++++++++++
The mongo password cannot be empty. Please input a valid password string.
++++++++++++++++++++++++++++++++++++++++

Are you installing using the install.sh script?

**Comment by Gi972** [comment]
yes I made a screenshoot for you

![image](https://user-images.githubusercontent.com/1606247/105968154-007d5f80-6087-11eb-98f1-a5bdcd5eb3ea.png)

**Comment by mohanarpit** [comment]
@Gi972 In an endeavor to gather more information, can you let me know what Shell (Zsh, Fish etc) are you using & which version of bash you are on?

Also, is it possible for you to give an example of the password that you are trying to input in the installation script? From the looks of it, it seems like the bash `read` command is throwing an error. 

Alternatively, can you let me know what happens if you put in a simple password like `abcd1234`? Does the script still fail on your system?

**Comment by Gi972** [comment]
Sure, 

My version is zsh 5.8 (x86_64-apple-darwin20.0)
My root and password is the same I just tape 
gi
gi

I try also with abcd1234 but I have the same error

And I look the permission fo my folder
![image](https://user-images.githubusercontent.com/1606247/105971652-0c6b2080-608b-11eb-96bf-e17ffb3e8c0f.png)
