### ISSUE TITLE
[Bug]: Input Widget - Required property set to True, no indication that it is required on first instance of deploy.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If an Input widget has “Required” property set to true, on first instance of deploy (or even on canvas), there is no way user knows if the input field is required. 
Expected behaviour - There should be some indication for the field if the Required property is true. (Usually websites have an asterisk * mark next to required fields, could something similar to that be displayed?

### Steps To Reproduce

1. Drag and drop an input widget to the canvas
2. Set the Required property to true in the Property pane, for this field
3. Either on the Canvas, or on deploy, at the first instance, if nothing is typed in the text field, there is no way to know that this is a required field.
4. Only when we type something and delete it, then a pop up message comes up to the effect that the field is required.

Expected behaviour - There should be some indication immediately on deploy, and on the canvas, for the field, if the Required property is true. (Usually websites have an asterisk * mark next to required fields, could something similar to that be displayed?)

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
@btsgh the reason we did not provide this was because we decided that if a user wants to indicate this to their user, they can add the asterisk in the label. If you feel you have a good experience you want to add, please raise a feature request. But as of now this is the expected behaviour
