### ISSUE TITLE
[Bug]: Inability To Display text/plain Responses In API Response Viewer

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#13501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was checking out the new response view switchers and noticed text/plain responses are not displayed in the API response view. We now have a ‘RAW’ view which could be easily used to display this

### Steps To Reproduce

You can test using this hello world API and you notice that no response gets shown on the API response viewer 
https://hello-world.cokoghenun15.workers.dev/

### Version

Cloud/v1.6.23-SNAPSHOT

**Comment by prapullac** [comment]
We are displaying RAW view and the response is displayed to user
