### ISSUE TITLE
[Bug]: Binding text widget to input widget of data type email, text is having a hyperlink, which takes user to a blank page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I bind a text widget to an input widget of data type email, the text displayed has a link created, on clicking which, it goes to an "about:blank" page. 

Expected behaviour - Expecting a new mail page to open up from the mail server (unsure though if this is a possibility at present)

### Steps To Reproduce

1. Drop an input widget (Input1) onto the canvas. 
2. Set data type to email.  
3. Enter a test email address into this field. 
4. Now drop a text widget on to the canvas. 
5. Bind this text widget to the input widget (In the Text field of the property pane of text widget - enter something like this - Email: {{Input1.text}}. 
6. The text in the widget that is displayed is the email id entered in the input widget. However, it also automatically has a link created ( as it is an email id. ) On clicking the link, user is taken to a blank page.
7. This behaviour is seen on canvas and deploy mode too. 

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
@btsgh this is not a bug. Clicking on it opens the default mail client on the system
