### ISSUE TITLE
[Bug]: Widget icons in entity explorer have different colors representing them.

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#13502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/34486435/166244308-de62120c-0bab-49f4-af71-ce40feb073c6.png)

### Steps To Reproduce

1. Open the application
2. Drop widgets to entity explorer.
3. Some widgets have a different color compared to others.

### Version

Cloud

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
