### ISSUE TITLE
[Bug]: `onPageLoad` actions sporadically failing

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a couple of queries on the page: 
https://release.app.appsmith.com/app/vtx-onboarding-tool/currencies-626fb4c4afffd379fcf0c844/edit

1. querySelectActiveCurrencies
2. selectCurrentSelectedCurrency (Expected to fail as not configured correctly)

We can see the queries are getting executed on edit mode but seeing some random behavior on view mode. 
Page where we are seeing the failures : https://release.app.appsmith.com/app/vtx-onboarding-tool/currencies-626fb4c4afffd379fcf0c844
Query name which populates the tree widget `querySelectActiveCurrencies`
In edit mode we can see widget getting populated correctly but it’s intermittent on view mode.
Widget name: `vayMultipleCurrencySelection`

Slack conversation: https://theappsmith.slack.com/archives/C0341RERY4R/p1651501371020359?thread_ts=1651067937.099729&cid=C0341RERY4R

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9146992e1e8444cfbdfe9e89f453652e-00001.gif)](https://www.loom.com/share/9146992e1e8444cfbdfe9e89f453652e)

Note: This is an imported application but we have seen some instances where users complained this is happening for normal applications as well.

### Steps To Reproduce

1. Check the importd application on edit mode 
2. Both the actions gets executed every time in edit mode
3. Intermittently execute call is missing in view mode

 
![image](https://user-images.githubusercontent.com/41686026/166269089-863c2c74-7746-4706-9439-81cdb8e06598.png)

### Version

Cloud v1.6.23

**Comment by ohansFavour** [comment]
Theming changes have brought back the parallelization of init calls in view mode.
