### ISSUE TITLE
[Bug]: Function that is still being parsed can be run causing old code to run but incorrectly show current code and toast message

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A parsing issue consistently reproducible by keyboard shortcut usage (**Ctrl+Enter/Cmd+Enter**) making it quicker to run functions. In that intermediate time when a function is parsing we see old code being run when UI shows new code and success message.

### Steps To Reproduce

1. Create a new JS object and type in `return "hi"` in myFun1() of a new function and execute using keyboard shortcut
2. Observe the saving icon, success message and UI displaying new code on the function is run successfully but there's response is seen in the watch window because function hadn't parsed completely when function was run
3. Change the above snippet to `return false` and run the function
4. Observe that function returns `hi` in the watch window and not the current code
5. Re-run the function and observe that correct response is now seen on the console because it's now the updated code

### Version

Cloud

**Comment by ohansFavour** [comment]
@rohan-arthur how do you think this should be handled?

**Comment by ramsaptami** [comment]
Attached video shows how 2 complete different functions on a JS object is run when selected function on the dropdown is current function the user is working on and user hits run using keyboard shortcut mid-way when the app is still being saved (parsed)
https://www.loom.com/share/46bdc6a157cb48bb93cbde6f78a6b9c9
