### ISSUE TITLE
[Bug]: Editing JSObject throws a bunch of errors within the Network Tab

### ISSUE THREAD

**Issue by iamrkcheers** [appsmithorg/appsmith#13539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create a JSObject in the code editor, I get a huge bunch of XHR calls, some of them responding with the following error,
"Cannot have more than 120 active event names".

### Steps To Reproduce

1. Go to QUERIES/JS
2. Click on JSObjects
3. Open the Network tab
4. Try writing a Javascript object
<img width="1440" alt="Screenshot 2022-05-04 at 2 20 55 AM" src="https://user-images.githubusercontent.com/16760643/166565143-b83af072-8cd2-436f-b314-54048d1930bc.png">
<img width="787" alt="Screenshot 2022-05-04 at 2 21 30 AM" src="https://user-images.githubusercontent.com/16760643/166565167-4c8a02d2-a6d3-4bbc-9d0c-7f7727013c8e.png">

### Public Sample App

https://app.appsmith.com/app/untitled-application-1/page1-626fd8458a368d6f1ef57a2e

### Version

Self Hosted - v1.6.23

**Comment by Nikhil-Nandagopal** [comment]
@iamrkcheers this is a problem with how intercom cannot handle the events we send to segment. This should have no impact ideally so I'm going to close this but we'll speak to the intercom team on how to avoid this
