### ISSUE TITLE
[Bug]-[416]:Reset widget doesn't set value to current default value instead sets it to initial default value

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#13540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we reset a widget, currently evaluated values and meta values are not in sync.

For example:-
For the Input widget, If default text = "ABC" and then it was changed to default text = "ABCDEF". 
On reset
- Input.text = "ABC" 
- text visible in widget = "ABC"

We expect the widget to reset to its current default values but it resets to initial default values.

### Steps To Reproduce

1. Add an Input widget, Text widget, and Button widget to the canvas.
2. Bind Text widget = `{{Input1.text}}`
3. Button widget onClick = `{{resetWidget("Input1")}}`
4. Change default value of input widget and click on button to reset.
Notice, that the input widget doesn’t reset to its default value.

### Public Sample App

https://app.appsmith.com/app/resetwidget/page1-62614f3b00cba01cd02f03f5

### Steps To Reproduce in Sample App
1. Type `1` in Input1 
2. Click on the `Reset Input2` button
3. Again Type `1` in Input1 
4. Click on the `Reset Input2` button

Repeating this multiple times will showcase cases where 
1. Input2 resets to the current default value visible in `Input1` or 
2. Input2 resets to the initial default value which is "ABC"

Ideally, we should always reset the widget to its current default value IMO.

Recording -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/354b8c1a885e4889be691b5a2318d362-00001.gif)](https://www.loom.com/share/354b8c1a885e4889be691b5a2318d362)

### Version

1.6.22

**Comment by Nikhil-Nandagopal** [comment]
@Rishabh-Rathod this seems to be working for me. Can you provide a public example?

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod this seems to be working for me. Can you provide a public example?

@Nikhil-Nandagopal I have added a public sample add, steps to reproduce, and a recording showing the issue.

**Comment by Nikhil-Nandagopal** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 104 |
| Effort (months)  | 0.5 |

**Comment by Nikhil-Nandagopal** [comment]
@Rishabh-Rathod able to reproduce it now. We really need to fix framework breaks like this

**Comment by Rishabh-Rathod** [comment]
https://github.com/appsmithorg/appsmith/pull/13084 PR fixed this issue also. 

This issue is not reproducible on release. I have done verification for it. Closing it.

@ramsaptami could you also verify it.

**Comment by Nikhil-Nandagopal** [comment]
@Rishabh-Rathod awesome!
