### ISSUE TITLE
Multiple Environments

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#13545]
That is the one thing Retool has that I really like over Appsmith. Otherwise I am liking Appsmith a bit more so far. They have a really easy way to flip between production / staging environment with all the same widgets on a page

**Comment by hexadecy** [comment]
We use al least 3 environments (dev, staging, and production)

**Comment by Nikhil-Nandagopal** [comment]
@hexadecy you can achieve this today using our Git Feature. You can connect your app to a git repository and then import it into a staging organization & a dev organization. You will be prompted to enter separate credentials for all your datasources in these organizations

**Comment by Nikhil-Nandagopal** [comment]
Closing this feature as we're tracking it here #2836
