### ISSUE TITLE
[Bug]: Optimize click interaction on table widget

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#13546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you click on a table row, the whole table renders twice, which is absolutely not necessary.
I believe this is happening due the meta property selected row changing.

This is the profile of a click interaction a page with single table widget having default data.
<img width="2168" alt="Screenshot 2022-05-04 at 11 16 10 AM" src="https://user-images.githubusercontent.com/441914/166628893-ca971b3d-dea2-4509-9658-f04be19d1342.png">

### Steps To Reproduce

- Add a table widget to a page
- Start the chrome profile
- Click on a table row.

### Version

All

**Comment by somangshu** [comment]
@SatishGandham is this a problem is the table v1 or v2?

**Comment by SatishGandham** [comment]
@somangshu , This was in v1. We should check if the same is happening in v2.

**Comment by somangshu** [comment]
@sbalaji1192 @keyurparalkar can you guys help us check this in V2?

**Comment by Tooluloope** [comment]
After extensive debugging, 
The Table Widget V2 renders twice in edit mode due to evaluations of Meta properties and the
 derived properties that depend on it. 

https://user-images.githubusercontent.com/31691737/189281781-ff14c3b8-fd23-4c66-af71-672ebb723bd1.mov
