### ISSUE TITLE
[Docs]: Update documentation for import application

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/how-to-guides/backup-restore

### Describe the problem

Recently we have modified the way we import application after we introduced the git-import. Earlier we used to share all the configuration required within the exported file which led to a security leak. 

### Describe the improvement

As per modified implementation, we are asking for datasource configuration once we import the app in the destination org for which the doc needs updation
<img width="1434" alt="Screenshot 2022-05-04 at 10 13 44 AM" src="https://user-images.githubusercontent.com/41686026/166624123-9145c3bb-9ac5-427b-b423-f53c67edee13.png">
.

**Comment by vuiets** [comment]
Hey @abhvsn am I getting something wrong here?

We've already covered importing via Git under [Git Sync](https://docs.appsmith.com/core-concepts/git-sync#importing-from-a-repository) aren't we?

**Comment by vuiets** [comment]
Ah my bad, this is the change in flow to our existing normal `Import` app flows.

**Comment by AnaghHegde** [comment]
We have the draft available here already - https://docs.google.com/document/d/1uMtJZnbFax4uAvzHxp6P0MmyMuEIcJaWXV2NBkajXeI/edit

**Comment by Pranay105** [comment]
I have used this draft to create Import from Git repository under Git documentation @AnaghHegde

**Comment by vuiets** [comment]
@Pranay105 can we prioritise this if we haven't already? We get a handful of requests in support around this. It'll help those users understand the new flow.

**Comment by Pranay105** [comment]
I'll pick this up in the next sprint @vuiets
