### ISSUE TITLE
[Bug]: API is working fine in Postman but same API will work fine but gives error response in Appsmith

### ISSUE THREAD

**Issue by Somashekar-B** [appsmithorg/appsmith#13565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a post API which when executed through postman providing expected response

but i tried to execute same API using appsmith it is throwing error response 
even though the API worked totally fine and it successfully made changes in DB

### Steps To Reproduce

1. Create a post request API
2. Run that API in Postman with some valid JSON body if got successful response then
3. Run same API with same JSON body in appsmith 
4. You will get error response
5. Check whether DB has new data. ( it will have new Data ). 

### Version

Don't know but the problem is from past 7-8 days

**Comment by Nikhil-Nandagopal** [comment]
@Somashekar-B can you share the API? Also is the API response a string or a JSON?
