### ISSUE TITLE
[Feature]: Python support for api integration 

### ISSUE THREAD

**Issue by Nllii** [appsmithorg/appsmith#13577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Awesome project.

postman is cool but can python programmers get basic REPL environment for integration. 
Maybe something like https://replit.com

.Thanks

### Why should this be worked on?

Postman is cool, but python programmers are use to the terminal. Postman has too much fancy stuff.  Adding REPL  will make api integration bearable for python programers like myself.

**Comment by Nikhil-Nandagopal** [comment]
@Nllii thank you for the feature request! I have a question about this. As of today, our REST API integration is only used to talk to an already created API. Are you looking to create an API inside Appsmith with Python or call a Python script that is already created somewhere on your server

**Comment by Nllii** [comment]
Yes. To call a python script.

I have tried bokeh, plotty, pyscript and Mongodb charts to create a dashboard, it takes up too much resources and too much fancy stuff. 

This project has what I need. 
Now adding python for basic  CRUD and HTTP request. With a drag and drop UI attached to ones code. 

You know. Like [scratch or REPL apps](https://scratch.mit.edu/projects/editor/?tutorial=getStarted)

**Comment by Nllii** [comment]
The current  flow for attaching QUERIES/JS(postman)  is in Javascript and  API  calls are in postman; then binding to canvas widget. 

JSObject is in javascript, this  is where python is needed for creating functions for python users. 

#### To conclude  I'm using cUrl imports for now to get my API urls in, then creating my functions in javascript. but;  I am I want  to write python scripts inside Appsmith to bind to the widgets and make api calls using 
```requests.get(url = URL, params = PARAMS) ``` instead of postman and JSObject.

**Comment by Nikhil-Nandagopal** [comment]
Closing in favor of #23506 13577
