### ISSUE TITLE
[Bug]: Grouping widget pushes widget below it further down

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#13572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there are multiple widgets at the below a group of widget. Grouping the selected widgets will push the widgets below the group to further below.

### Steps To Reproduce

1. Add few widgets in a single column
2. select some of the top widgets and press cmd + g
3. observe the widgets below the group to be pushed further down

### Version

Release

**Comment by Sripriya93** [comment]
Working fine, Verified

https://user-images.githubusercontent.com/104895602/167382971-b57c2f49-b158-4508-a762-290b8febfbd8.mp4

d
