### ISSUE TITLE
[Bug]-[292]:Compact property is not functional for Menu widget and Menu type on Table widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#13583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/1ac45b64776343e082fa89a8126b1954-00001.gif)](https://www.loom.com/share/1ac45b64776343e082fa89a8126b1954)

### Steps To Reproduce

1. Drag and drop Menu widget
2. Add few Menu items
3. Click on menu widget
4. Now enable compact property
5. Click on Menu widget
6. Observe there is no change

### Version

Cloud/ Release

**Comment by dilippitchika** [comment]
The only change i see is the font size is smaller, other than that there is no difference. I also don't see the design mentioning what this does. 

If so, can we safely remove this field?

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 146 |
| Effort (months)  | 0.25 |

**Comment by somangshu** [comment]
@chandannkumar please open another issue, assign @souma-ghosh & @sbalaji1192, send the issue to sprint backlog.

Do add the correct steps to reproduce. Closing this issue again
