### ISSUE TITLE
[Bug]: shows schema not available until its loaded 

### ISSUE THREAD

**Issue by ganganimaulik** [appsmithorg/appsmith#13584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**No information available/shows schema not available** displayed until real error message/data appears. 

should display **Loading..** message

https://user-images.githubusercontent.com/10296400/166870595-dbb60443-6a67-48da-8d9c-bcc222450fa5.mp4

### Steps To Reproduce

1. add sample users datasource (its same for any/most datasources)
2. try to expand it as shown in video

### Version

cloud

**Comment by ginilpg** [comment]
@somangshu Can we close this ticket? Is this done?

**Comment by somangshu** [comment]
@ginilpg I am not sure about this. Looks like the issue is related to datasource in entityexplorer.

**Comment by AmanAgarwal041** [comment]
Closing as the featured branch is merged
