### ISSUE TITLE
[Bug]: Canvas scroll to top when I drop Tab widget on the canvas

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#13582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observed this issue on Tab change as well.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0b4fff84ba0144dd8d51d2da1e57f459-00001.gif)](https://www.loom.com/share/0b4fff84ba0144dd8d51d2da1e57f459)

### Steps To Reproduce

1. Drop few widgets on top of the canvas so that visible screen have widgets now
2. Scroll the canvas and the drop Tab widget
3. Observe that the canvas scroll back to top

### Version

Cloud/Release

**Comment by dilippitchika** [comment]
@jsartisan @keyurparalkar are you checking this?

**Comment by jsartisan** [comment]
Let me check this

**Comment by vivekverma2312** [comment]
@jsartisan Similar behaviour is observed for drop-down widgets.
https://www.loom.com/share/d9105908a6e24f5c99604ded1bb3f953

**Comment by dilippitchika** [comment]
@vivekverma2312 for tree and multitree we had this issue - https://github.com/appsmithorg/appsmith/issues/11485
@Tooluloope could you confirm if it is fixed? I see the PR https://github.com/appsmithorg/appsmith/pull/13129 mentions this issue

**Comment by Tooluloope** [comment]
@dilippitchika That PR should fix the issue for the Select widget

@vivekverma2312 could you help test Select widget in this PR #13129

**Comment by vivekverma2312** [comment]
@Tooluloope @dilippitchika Tree and multitree issue is observed on canvas and above PR solves the issue only inside container widgets and not on canvas. This issue exist on prod as well so if you want I can raise a separate issue for this.

**Comment by Parthvi12** [comment]
@vivekverma2312  Just observed on switching tabs the canvas is scrolling to top as well.
