### ISSUE TITLE
[Enhancement]: Remove Success toast messages for JS on page load in view mode

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#13581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There is no need to show Success toast messages for JS functions after they run on page load in the **deployed mode** as the end-users won't be able to make sense of that message.

### Why should this be worked on?

A user was asking about how to turn off toast messages - https://community.appsmith.com/t/toast-messages-ran-successfully/938

**Comment by rohan-arthur** [comment]
How can we know the incidence of usage of this setting? In the console, I see `Async EXECUTE_PAGE_LOAD_ACTIONS Track Transaction` but this is not available for tracking on mixpanel.

**Comment by Nikhil-Nandagopal** [comment]
I think by default end-users should just not see these messages at all!

**Comment by codedmind** [comment]
> I think by default end-users should just not see these messages at all!

agree, i just purpose the option, assuming that someone decided to put that notification their should have be a reason :D

**Comment by perekrestov** [comment]
> > I think by default end-users should just not see these messages at all!
> 
> agree, i just purpose the option, assuming that someone decided to put that notification their should have be a reason :D

If someone wants a notification he always can put `showAlert('...')` inside the function

**Comment by yatinappsmith** [comment]
Still getting this message https://www.loom.com/share/7f43f810bf8345cc815ce54049117f05

**Comment by ohansFavour** [comment]
@yatinappsmith,  we want to show this in edit mode, it's only in view mode that we do not show this. I guess the title is confusing, I will modify that now.

**Comment by GabrielMarques89** [comment]
Is this completed ? 

I'm developing in appsmith and i have this issue... i have some pages that runs a few js / calls and i have like 3~4 alerts popping up on the page load... and this messes with the user experience

**Comment by Nikhil-Nandagopal** [comment]
@GabrielMarques89 you may be on an older version. It should be fixed once you update
