### ISSUE TITLE
[Feature]-[516]:Add label settings and styles to switch, checkbox

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13586]
## Objective

With the change to support label widths for different widgets, checkbox and switch widget need some different settings to ensure their labels are aligned

### Requirements
We need to support labels for switch and checkbox

**Positions**

1. Left - Devs can select this to show the label to left of the check or radio button
2. Right - Devs can select this to show the label to right of the check or radio button 

**Alignment**

1. Left - Once position is set, alignment left makes the label text aligned either to the boundary(left position) or to the checkbox/radio button (right position)
2. Right - Once position is set, alignment left makes the label text aligned either to the boundary(right position) or to the checkbox/radio button (left position)

**Label styles to support**

- Text color - Allow devs to update the color of the label
- Text size - Allow devs to update the text size
- Font style - Allow devs to update the font style

**Migration**

Currently we have the alignment field in checkbox and radio, based on the values for alignment we need to migrate them to the following configuration

Old Values | New values
-- | --
Alignment : Left | Position : Right , Alignment : Left |  
Alignment : Right | Position : Left , Alignment : Right |  

## Documentation

- Updates to documentation to add these new fields for all the following widgets

### Figma Link here

Property pane design - [https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-|-Content-Property-Pane?node-id=2777%3A64824](https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=2777%3A64824)

For label styles use the same design as input widget label styles group

Widget design -https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library

**Comment by dilippitchika** [comment]
I will be completing the PRD and adding it here

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 516 |
| Effort (months)  | 0.5 |

**Comment by techbhavin** [comment]
@dilippitchika, Figma link not redirect to correct design, can you plz help me on the same
