### ISSUE TITLE
[Bug]: MultiSelect widget v1 unable to reflect value changes

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#13588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/23132741/166878074-81418f97-e22c-4f80-b5ac-00a7ac03b30a.mov

### Steps To Reproduce

1. Go to A force application, Community issues page
2. Change row selection with another row that has value in states ( multiple times )
3. Notice that in the Details tab, the Multi-select widget showing `states` doesn't reflect the value according to the selected row. 

### Tasks 
Currently, we have commented  [Application/CommunityIssues_Spec.ts](https://github.com/appsmithorg/appsmith/pull/13084/files/6590b0820ca104067b1dcaae6b8cb2c7ecde841b#diff-3d799910c16fbb70ccbae0491e77b7452dca9c8686fd50397a5a6af3102352a7) test case for unblocking current PR due to this issue.
- [ ] Uncomment test case changes once this issue is resolved.

### Version

1.6.24

**Comment by Rishabh-Rathod** [comment]
Marked it as a high priority as this happens for the multi-select widget for an edge case. 

Internal slack communication link - 
https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1651836391943489?thread_ts=1651762228.810179&cid=C02K0SZQ7V3

**Comment by ohansFavour** [comment]
@Rishabh-Rathod can you kindly confirm that this still happens?

**Comment by bharath31** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/13588?planning-poker) with Zenhub @Druthi

**Comment by Druthi** [comment]
- There is no issue with the multiselect widget reflecting values here. Only issue is with test cases in the Community Issues spec that has some errors in how it was written. 

Been trying to fix it however the last two tests have been failing. Right now I don't think it is priority so moving it back to icebox.

**Comment by bharath31** [comment]
@Druthi what are the next steps here?

**Comment by Druthi** [comment]
I think we can close this for now and reopen in case it re surfaces.
