### ISSUE TITLE
[Bug]: TypeError for debuggersaga where reading name from undefined plugin

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#13594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Reading values from undefined
<img width="651" alt="Screenshot 2022-05-05 at 2 13 59 PM" src="https://user-images.githubusercontent.com/7565635/166890091-ae6f9693-558d-43f2-89b3-e7f38eaa291c.png">

### Steps To Reproduce

1. View Mode of an application
2. See console

### Public Sample App

https://app.appsmith.com/applications/60d72903ee9aa1792c5bf168/pages/614d9b9e18a27e5288afa99d?branch=master

### Version

Both

**Comment by prapullac** [comment]
Verified as a part of regression
