### ISSUE TITLE
[Bug]-[4788]:Next/Previous icon on Tab widget is not functional with single click but only working when we click and hold

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#13591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b717c6db52eb47b7bbb3ceee88ca15b3-00001.gif)](https://www.loom.com/share/b717c6db52eb47b7bbb3ceee88ca15b3)

### Steps To Reproduce

The issue is if we click it once it does not work. You have to click and hold it to be functional. Currently on prod we have click behaviour and not click + hold.

### Version

Cloud/ Release

**Comment by dilippitchika** [comment]
@jsartisan this experience feels very laggy, can you check this once?

**Comment by vivekverma2312** [comment]
@dilippitchika @jsartisan Observed next/previous icon is not functional at all with touch on trackpad  and only work with click. Marking it to Release Blocker.

**Comment by somangshu** [comment]
@vivekverma2312 @dilippitchika I want to contest if this is really a release blocker, Considering the click still works

**Comment by somangshu** [comment]
Considering people who use the tabs widget with `show tabs` as `true`

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4788 |
| Effort (months)  | 0.5 |

**Comment by somangshu** [comment]
I also noticed, no one really turned this property to false, Does this mean we should have this behaviour by default, it will help reduce the number of properties in widget pane. cc @dilippitchika @vivekverma2312

**Comment by vivekverma2312** [comment]
@somangshu Marked it as release blocker because the user who uses `Tap to click` on Trackpad will not be able to click. I also struggled to understand as it was working for others (who uses click) and not for me.
