### ISSUE TITLE
[Feature]: Support a way to theme older apps 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

With theming now going to be live, we need a way to support theming of older apps.

### Why should this be worked on?

This will help with faster adoption of theming for our existing users, rather than them having to sit and reconfigure all the widgets they worked on.

**Comment by dilippitchika** [comment]
Conversation reference - https://theappsmith.slack.com/archives/C02JV8G1MP0/p1651735399004239

**Comment by shadabbuchh** [comment]
Moving this issue to `In Progress`. Mentioned the observations in https://github.com/appsmithorg/appsmith/pull/13741.

**Comment by shadabbuchh** [comment]
Moving this issue to In Progress. Mentioned the observations in #13741.

**Comment by shadabbuchh** [comment]
Moving it to `Done`. Comments are tracked in https://github.com/appsmithorg/appsmith/pull/13741
