### ISSUE TITLE
[Bug]: App crash on List widget when try copy/paste

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#13609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/eda77e0771234aa992198df3c73406ed-00001.gif)](https://www.loom.com/share/eda77e0771234aa992198df3c73406ed)

### Steps To Reproduce

1. Drag and drop a List widget
2. Copy list widget (CMD +C)
3. Move the cursor on the container
4. Pate it (CMZ+V)
5. Observe the app crash

### Version

Cloud

**Comment by Sripriya93** [comment]
Verified. QA done.
https://images.zenhubusercontent.com/275993885/27912328-a5c9-4668-a227-d7a43fde9f76/my_first_application___editor___appsmith___11_may_2022.mp4

**Comment by Sripriya93** [comment]
Working fine, Verified.
