### ISSUE TITLE
[Bug]: Issue seen in an app if there is a query with a column name as BorderRadius

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

User cannot have query with column name as "BorderRadius"

### Steps To Reproduce

This bug seems to be related to theming.  Removing a column named "BorderRadius" solves the problem.
Here are the videos showing the issue:
1. Shows issue:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6b9073e1b35247cfaeaf43daf1a51e7d-00001.gif)](https://www.loom.com/share/6b9073e1b35247cfaeaf43daf1a51e7d)
2. Shows how the issue can be avoided by removing BorderRadius column
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/01c114578b2d47b1b298acd06c6de4af-00001.gif)](https://www.loom.com/share/01c114578b2d47b1b298acd06c6de4af)

### Public Sample App

https://release.app.appsmith.com/app/habitasaurus/profile-6268e911bd7afb15ac39ba0b/edit#50cdgqv7rr

### Version

Release

**Comment by dilippitchika** [comment]
Need access to this app, it says not found for me. Please share it with demo@appsmith.com

**Comment by dilippitchika** [comment]
@btsgh removing critical tag and using release blocker. 

Please use critical if something breaks in production, I am assuming this issue doesn't happen in production yet.

**Comment by jsartisan** [comment]
@btsgh I am not able to reproduce this issue on my end :/

**Comment by btsgh** [comment]
@jsartisan - In the Habitasaurus app, Profile page, Apply Theme gives the uncaught promise rejection if the GetThemes query has this Select statement - SELECT * FROM "Themes" ORDER BY id LIMIT 10;

**Comment by jsartisan** [comment]
@dilippitchika The issue is not related to theming because it is still happening there is no BorderRadius column. This is related to actions and queries. Pulling the issue of theming stability epic.

**Comment by dilippitchika** [comment]
@btsgh can you please check this or a similar scenario once and let me know if it's still occuring? We need to know more info and reproduce it in other apps

**Comment by btsgh** [comment]
@dilippitchika  - The above habitasaurus application that is attached in this bug itself now does not function correctly as a lot of things in the UI have changed since then.
