### ISSUE TITLE
[Bug]: Default values placeholder on phone widget is incorrect

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Placeholders for `default text` property for phone input widgets are incorrect. It has `John Doe` as placeholder even though it don't accept string type input

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/166957471-a9219d51-4537-485d-814a-f65f1ab6e316.png)

### Version

Cloud

**Comment by Lovakush** [comment]
@ramsaptami I want to contribute in this issue can you assign to me ?

**Comment by dilippitchika** [comment]
@Lovakush please check issue #14061
