### ISSUE TITLE
[Bug]-[168]:Document viewer widget does not appear on autocomplete suggestion

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Document viewer widget does not appear on autocomplete suggestion

### Steps To Reproduce

1. Drag and drop a document viewer widget on canvas
2. Drop a text widget and attempt to bind properties of document viewer widget - observe autocomplete does not suggest this widget even if the widget has been renamed

https://www.loom.com/share/07a868bd87134f3a8418a74713839ff5

### Version

Cloud

**Comment by rohan-arthur** [comment]
WIDGET_CARD_DRAG - Unique
type DOCUMENT_VIEWER_WIDGET
836

Assume 10% of users want to refer to this in some JS, so reach = 84

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 84 |
| Effort (months)  | 0.25 |
