### ISSUE TITLE
[Task]: Add cypress testcases for delete branch 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13616]
### Functional
Failure:
- User is trying to delete the current checkout branch
- When trying to delete the default branch 

Success:
- User tries to delete non-default and non checked out branch

### UI
- Remote branches should not have vertical ellipsis 
- After successful deletion of branch if we trigger sync branch flow deleted branch should only appear in remote branch list

**Comment by hiteshjoshi** [comment]
This is taken care of. Closing this. Reopen if required. @RakshaKShetty @ramsaptami
