### ISSUE TITLE
[Bug]-[215]:Rating widget appears broken on dropping into canvas

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On dropping a Rating widget onto canvas on a 13" laptop, with Fluid width selected - the Rating widget seems cutoff on Release url. 

### Steps To Reproduce

1. On the release url, create a new page. Make sure the Canvas size is fluid width.
2. Drag and drop the rating widget.
3. The widget stars are cutoff. 

This is not the issue on Prod. If Canvas size is made - Desktop, Tablet Large or Mobile device - this issue is not seen. Problem is seen in Fluid width and Tablet. 
Display - 13" screen.
<img width="548" alt="Rating_Cutoff" src="https://user-images.githubusercontent.com/101863839/166919348-5eb4a3d7-f3ab-4492-99eb-7a107c6a477e.png">

### Version

Release

**Comment by dilippitchika** [comment]
Reproducible, we can increase the default width to be more but this looks like a bigger problem across widget drops. 

Whenever a widget drops, we need to make sure it looks best in every possible resolution. A few ways to do this 
1. Responsive default data - Today only the width is responsive, but if we also had different default widget behavior for different widths this would be better
2. For smaller grid sizes or no. of grids the widget width when dropped should be increased to make sure there is a fixed range of px value for it

**Comment by dilippitchika** [comment]
For now we will increase the width of the rating widget to make sure it doesn't break across any screen size.

**Comment by dilippitchika** [comment]
Assuming the impacted apps are being built on mobile and tablet for easier calcuation. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 215 |
| Effort (months)  | 0.5 |
