### ISSUE TITLE
[Feature]: Change theme button on theme UI

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Change theme will be shown on hovering the card rather than an explicit button

### Why should this be worked on?

This will help bring the properties to be consumed directly below the themes

**Comment by dilippitchika** [comment]
Updated design to discuss on, needs some design help

https://www.figma.com/file/wVHeU6hnJtC29sLAiGo5yl/UI-%7C-Application-Theming-2.1?node-id=3421%3A262520

**Comment by chandannkumar** [comment]
@jsartisan @dilippitchika 
Observation:
- As per figma design, we can see a option to 'customize' whenever theme is selected. But in DP there is no customize option and everytime we need to go back to configure more
https://www.loom.com/share/a03b5d7ee6604996ae7292c317b252fe

**Comment by dilippitchika** [comment]
@chandannkumar thanks for this, there is a difference and it is known. We are waiting for some user feedback to improve this currently and are tracking it in a separate issue https://github.com/appsmithorg/appsmith/issues/13627

**Comment by chandannkumar** [comment]
Change theme will be shown on hovering the card rather than an explicit button - Tested & verified

Tested this feature on PR and working as expected
