### ISSUE TITLE
[Bug] On Clicking of lightning bolt to add data we should change the interaction from click to hover.

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#1363]
## Description

The widgets can call for data from API or Datasources. This happens when the user will click on the lightning bolt to choose a data source. The interaction as of now is that they have to click on each of them to add. This can be changed to hover.

### Steps to reproduce the behaviour:
1. Add any widget
2. Select Data > from API
3. You need to click on API again to create a new API
![Capture](https://user-images.githubusercontent.com/34486435/96974323-b12f0c80-1536-11eb-8015-f71a80759bae.PNG)

### Important Details
 - Version: [Cloud]
 - OS: [Windows]
 - Browser [Chrome]

**Comment by nuwan94** [comment]
I like to work on this issue.

**Comment by Nikhil-Nandagopal** [comment]
> I like to work on this issue.
> 
> Do we need to add hover function to the other menus as well? ("Use data from a Query" and "Use data from a Widget")?

@nuwan94 yes we should enable hover for all menus
