### ISSUE TITLE
[Bug]: Function execution does not wait for user confirmation before running and does not display response when run on page laod

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Function execution does not wait for user confirmation before running and does not display response in watch window when run on page load

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/untitled-application-3/page1-6274f3497c6b4e16b81a28a8/edit/jsObjects/6274f5fd7c6b4e16b81a28cb?editName=true) location and observe the JS object behaviour as mentioned in the video
2. JS function marked to ask for user confirmation does not ask for user confirmation
3. Also observe that JS object running myFun1() on page load executes successfully but myFun2() fails to displays any information

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/1973d0cf245f45e9be19bb9b4cf24a96-00001.gif)](https://www.loom.com/share/1973d0cf245f45e9be19bb9b4cf24a96)

### Public Sample App

https://release.app.appsmith.com/app/untitled-application-3/page1-6274f3497c6b4e16b81a28a8/edit/jsObjects/6274f5fd7c6b4e16b81a28cb?editName=true

### Version

Cloud

**Comment by Aishwarya-U-R** [comment]
getId - confirm does not come.. since its being called inside - callBooks:
 
https://user-images.githubusercontent.com/91450662/181263864-182db403-7b58-4985-a736-f44e83e7e22c.mov

**Comment by satbir121** [comment]
This issue still persists. [Reproduced in this app](https://app.appsmith.com/app/public-testing-issues/issue13646-637f231f854b686e2f8d8c8d/edit/jsObjects/637f272c4a42f47b0d2c564a)

**Comment by satbir121** [comment]
@ramsaptami If a function is set to run on page load, you mentioned in the video that the response should be shown on page refresh. But the response shouldn't be shown.

**Comment by ohansFavour** [comment]
I agree with Satbir here. We should not show a response in the debugger on page load. One of the issues we might face doing this is that the current JS Object response UI doesn't show which function the response corresponds to.
If multiple functions are run on page load, and a response is shown in the debugger, users can not tell which function's data is shown.

**Comment by ramsaptami** [comment]
Fair enough reason for not showing function response on page load. But the main issue with not showing confirmation modal is still open.

**Comment by Druthi** [comment]
This bug seems to be the same issue as [this issue](https://app.zenhub.com/workspaces/fe-coders-pod-6167d1b64ee5f20014242ab7/issues/gh/appsmithorg/appsmith/17500)

**Comment by shwetha-ramesh** [comment]
@Druthi working as expected. Moving to Done

**Comment by Druthi** [comment]
Moving this card to Product backlog as we've encountered some blockers. We need some product discussion on this. 

Explained the issues here https://www.loom.com/share/ee6786b057824e0890214b0a8bc37800

**Comment by bharath31** [comment]
@Druthi now that we've shipped #18175, should this be an easy solve?

**Comment by Druthi** [comment]
@bharath31 As discussed the blocker is not related to sync and async but regarding the current platform limitation of not being able to stop execution in evaluations. Therefore we cannot take care of the case of showing confirmation for  nested functions

**Comment by ramsaptami** [comment]
fixed in #17500
