### ISSUE TITLE
[Bug]-[70]:Required selection for RadioGroup widget does not show the red rectangle required indicator

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Radio Group Widget, in the Property Pane, on removing the Default value and setting the Required property to Enabled, the red rectangle to show the required indicator does not appear.

### Steps To Reproduce

1. In the production environment (app.appsmith.com), drag and drop a Radio Group widget
2. Remove the Y from Default property and make it empty.
3. Make the Required switch enabled. 

Note that there is no required indicator that appears. This indicator appears correctly on other widgets, for e.g. checkbox group or checkbox.

Also, the functionality of the Required property is working. This is checked by dropping the above Radio Group widget onto a Form widget. We see that the Submit button gets disabled if there is no option is selected in the Radio group widget. Only the indicator is missing. 

<img width="1101" alt="RadioGrp_RequiredIndicator" src="https://user-images.githubusercontent.com/101863839/167112246-025e09ba-8b6e-44c1-8c72-576753086398.png">

### Version

Production

**Comment by dilippitchika** [comment]
The current behavior on required is not upto the mark and needs some more design investigation. Assigning this to design team to triage and get back.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 70 |
| Effort (months)  | 0.5 |

**Comment by andrewdietekoki** [comment]
@dilippitchika Worked on solutions here: https://www.figma.com/file/zHCSC8aA9crvqXrxCjcTwD/Issues-and-Fixes?node-id=12%3A8489

**Comment by somangshu** [comment]
fixed in Reskinning

**Comment by dilippitchika** [comment]
https://github.com/appsmithorg/appsmith/pull/15329
