### ISSUE TITLE
[Bug] Incorrect autocomplete of toString() to convert to string

### ISSUE THREAD

**Issue by pric-appsmith** [appsmithorg/appsmith#1365]
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. To convert a value  (let's say `userId`) to string using JS, When I select `toString` option from autocomplete suggestions, it completes it as `userId.toString`, which is incorrect, and I have to manually change it to `toString()`.

![chrome-capture](https://user-images.githubusercontent.com/72548460/96977920-5ea41f00-153b-11eb-8d65-1e0b59a6a99d.gif)

### Expected behavior
Autocomplete to complete it with the correct syntax of the function call i.e. `toString()`

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Chrome

**Comment by Nikhil-Nandagopal** [comment]
@pric-appsmith thanks for catching this!
