### ISSUE TITLE
[Feature]-[213]:Multiselect widget default value consistency for server side filtering

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Creating this issue to track the multiselect widget default value updates. 

### Why should this be worked on?

Consistent behavior for default values in multiselect widget

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 213 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Adding my notes here for the part i am confident of for Multi select widget

## Default value with server side filtering OFF- MultiSelect widget
1. Supported formats - `[values]`, `[{label,value}]`
2. When any value from default is not present in the list of options
   - The value will not be shown by default in the multiselect widget, if all values are missing no default should be multiselect widget
   - The default value field in property pane should show an error
      - Error message - "Some or all default values are missing from options. Please update the values."
3. When the label is different from the one configured in the default and the options
    - The default label(s) will be shown from the options and not from the data in the default values field.
       -  The selectedOptionLabels and selectedOptionValues should populate data of value from default and label from options

## Default value with server side filtering ON- MultiSelect widget
1. Supported formats -`[values]`, `[{label,value}]`
2. When value is not present in list of options
    - Format is `[values]`, then we throw an error message 
       - Default value is missing in options. Please use `[{label : <string | num>, value : < string | num>}]` format to show default for server side data
    - Format is `[{label,value}]` then we show the these as the default labels and values in the multi-select widget
3. When value is present in list of options
    - Similar to server side filtering OFF; We show the default from the list of options
    - If the label is different between default and the option then, the default label(s) will be shown from the options and not from the data in the default values field 
       -  The `selectedOptionLabels` and `selectedOptionValues` should populate data of value from default and label from options

Not considering CSV here, need discussion on that.

**Comment by dilippitchika** [comment]
@Tooluloope i have updated the comment, can you check point 2 in both server side ON and OFF again?

**Comment by laveena-en** [comment]
Tested and verified.
