### ISSUE TITLE
[Bug]Add widget from from Query is not populating query data in table widget

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#1366]
Steps:

1.Create a query using postgres datasource.
2.Then execute a query , make sure you can see the query response.
3.Click on Add widget.

Expected:
Table widget to be populated with query response.

Actual:
Table widget is populated with default table data.

**Comment by akash-codemonk** [comment]
@NandanAnantharamu  Just tried on release seems to work.

**Comment by akash-codemonk** [comment]
I can replicate the issue.

**Comment by NandanAnantharamu** [comment]
@akash-codemonk yeah its kind of intermittent. If you need any help do let me know

**Comment by NandanAnantharamu** [comment]
Its working

**Comment by hetunandu** [comment]
@NandanAnantharamu Can you push the test case now

**Comment by NandanAnantharamu** [comment]
@hetunandu data is loading but there is issue with binding , https://github.com/appsmithorg/appsmith/issues/1378

**Comment by NandanAnantharamu** [comment]
@akash-codemonk This issue still seen intermittently , can you check again ?

**Comment by prapullac** [comment]
Verified the issue and working as expected
