### ISSUE TITLE
[Feature]-[516]:Select value default changes for consistency and server side filtering

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Select widget default values are not yet standardised across server side filtering and regular behavior. Using this to track the updates to default. Will add notes here.

### Why should this be worked on?

Currently the behavior for select widget's default values are very confusing. We want to standardise this as early as possible due to the importance of this widget.

**Comment by dilippitchika** [comment]
Assuming all users who have configured default are impacted

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 516 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
## Default value with server side filtering OFF- Select widget
1. Supported formats - `value`, `{label,value}`
2. When value is not present in the list of options 
     - No default should be shown in the select widget
     - The default value field in property pane should show an error
       - Error message - "Default value is missing in options. Please update the value."
3. When label is different between default `{label,value}` and in options
    - The label is shown from the list of options and NOT from the label added in the default field
       - The selectedOptionLabel and selectedOptionValue should populate data of value from default and label from options  

## Default value with server side filtering ON - Select widget
1. Supported formats - `value`, `{label, value}`
2. When value is present in list of options
    - Similar to server side filtering OFF; We show the default from the list of options
    - If label is not same between options and default {label, value}; We show the default from the list of options
       - The selectedOptionLabel and selectedOptionValue should populate data of value from default and label from options 
4. When value is not present in list of options
    - If the format is `value` and not `{label,value}` 
        - No default should be shown in the select widget
        - The default value field in property pane should show an error 
           - Error message - "Default value is missing in options. Please use {label : <string | num>, value : < string | num>} format to show default for server side data"
    - If the format is `{label, value}` 
       - The default will be shown in the list of options using the label field from {label, value}
       - There should be no error in the default field
       - The selectedOptionLabel and selectedOptionValue should populate data from {label, value}

**Comment by Tooluloope** [comment]
Hi @dilippitchika 
I don't think we need to bother ourselves with if the value is in the Option or not when server-side filtering is ON.

Speaking specifically for 3a above, we should display the default value irrespective of the format.

**Comment by dilippitchika** [comment]
@Tooluloope why do you think so? In this case, aren't we sending incorrect data to the backend if the user doesn't select anything, which then throws an error on the query. Is there some reason behind this which I am not able to grok?
