### ISSUE TITLE
[Feature]: Click to add a new row in the table

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow users to add a new row in the table with the data.
Link to PRD - https://www.notion.so/appsmith/Adding-a-new-row-in-the-table-0ec90544d26c4c25ab1f9b2504e919a1
Link to design - https://www.figma.com/file/aJ2Hwz9gH5AK6zaRYtZV8a/Table-widget-update?node-id=2119%3A132071

### Why should this be worked on?

This will make tables support building full fledged apps

**Comment by kamakshibhat-appsmith** [comment]
Checked DP, Issued added in [PR](https://github.com/appsmithorg/appsmith/pull/17515#issuecomment-1295252550) @sbalaji1192

**Comment by kamakshibhat-appsmith** [comment]
tested and looks good . This was fixed by [17515](https://github.com/appsmithorg/appsmith/pull/17515)
