### ISSUE TITLE
[Feature]: Support HTML as a column type in the table widget

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow using html as a column type in the table widget

### Why should this be worked on?

Enhances our table widget to render custom html making the tables look better

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b0vnw)

**Comment by JoshMayberry** [comment]
I am also interested in this

**Comment by lublak** [comment]
Theoretically, you can also offer text that works exactly like the text widget in addition to pain text.

**Comment by lublak** [comment]
@dilippitchika Theoretically, you can also offer text that works exactly like the text widget in addition to pain text.

**Comment by lublak** [comment]
It would be also nice to allow html directly in the header rows:

![grafik](https://user-images.githubusercontent.com/44057030/184330688-b25db9c5-684b-4795-b479-b3b8271ff460.png)

**Comment by rafaelferreirapt** [comment]
Hi, I am experimenting retool and appsmith. In retool we made a table with rows with HTML, but I can't do this in appsmith. It will be awesome to have that in appsmith. 
![Captura_de_ecra_2022-08-22_as_06 34 01](https://user-images.githubusercontent.com/4203171/185846805-efac50cb-9b1b-4d4a-ba81-c2e7fe7e7088.png)

**Comment by dilippitchika** [comment]
Hey @rafaelferreirapt can you also provide context on how you show the html inside table? Any screenshots will help

**Comment by rafaelferreirapt** [comment]
Hi, we are building a CS dashboard for our team. We are an electric mobility application. We need to show to the CS team in the table plenty of information before going into the session details page
![Captura_de_ecra_2022-08-22_as_06 38 36](https://user-images.githubusercontent.com/4203171/185871523-0790c0bc-4a53-42ac-81c3-34ab12f60296.png)
.

**Comment by dilippitchika** [comment]
Thanks a lot for this @rafaelferreirapt we are planning to pick this up soon, please keep following this github issue

**Comment by somangshu** [comment]
@andrewdietekoki is this picked up, If yes, can you add an estimate?

**Comment by andrewdietekoki** [comment]
Sure. I will do that.

**Comment by andrewdietekoki** [comment]
@JoshMayberry @lublak @rafaelferreirapt Do you mind sparing some time to briefly talk about this issue and the context of use? Do let me know when it's convenient.

**Comment by rafaelferreirapt** [comment]
Hi @andrewdietekoki, yes, we can talk through Appsmith Discord, my user is rafaelferreirapt#4209.

**Comment by andrewdietekoki** [comment]
Ok @rafaelferreirapt Thanks.

**Comment by kazazor** [comment]
Any progress made here?
We would like to do something simple and include an `<a>` link in the table column instead of the plain URL

**Comment by mgperry1** [comment]
More support to add this feature HTML in column

**Comment by pv-pro** [comment]
I am also interested in this !

**Comment by ngolosov** [comment]
I am also interested in this !

**Comment by zuroma999** [comment]
Would be great if this feature were added. Other similar tools I'm evaluating have this.

**Comment by spamoom** [comment]
Just to add to this, I share the same need for a HTML column as https://github.com/appsmithorg/appsmith/issues/13681#issuecomment-1221999542

We need to display complex data with rendered HTML links that send users out to relevant pages and/or external links

**Comment by Qizheng-AI** [comment]
Please add this sooner, I meet this question either.

**Comment by 8jinal8** [comment]
Awaiting for this to get implemented.. Any expected timeline for the release? Supposed to be done '[soon](https://github.com/appsmithorg/appsmith/issues/13681#issuecomment-1222183044)' 2 years back!

**Comment by jack-goslin** [comment]
Same here. Would be really nice to make the tables less sterile.
