### ISSUE TITLE
[Docs]: Problem while deploying on Azure w/ Terraform; define volume mount

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#13685]

**Comment by spark-c** [comment]
Update docs to tell users to define a volume mount in order to persist internal Appsmith data while restarting their container.

See [Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1652086201807969) for more information.

**Comment by jnikhila** [comment]
@sharat87 - Could you please help us out in understanding what needs to be documented?

**Comment by danciaclara** [comment]
Closing this as we don't have documentation on deploying on Azure with Terraform. So we probably don't need to document the troubleshooting fo this one.
