### ISSUE TITLE
[Feature]: Support editing date column type in table widget

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow developers to mark date columns as editable

### Why should this be worked on?

Helps with editing dates inline

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_64ljg)

**Comment by rohan-arthur** [comment]
user requested this feature today: https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100112270

**Comment by dilippitchika** [comment]
https://www.notion.so/appsmith/Date-and-date-time-in-table-c9e292188eff4604a9f2b3c91aca1efb

**Comment by charles-bloomfield** [comment]
Yes, we need this!

**Comment by LauridsJMikkelsen** [comment]
So whats the status on this? I still cant make date columns editable in Appsmith Community v1.8.15. Love the app but really need this feature

**Comment by dilippitchika** [comment]
Hey @LauridsJMikkelsen this will be released in v1.9.1, we are in closing stages for this

**Comment by pambrose** [comment]
Hi @dilippitchika, is your statement about 1.9.1 still true? If so, I do not see it in the release notes, and it is not working on the AppSmith-hosted app..

**Comment by dilippitchika** [comment]
My apologies @pambrose this feature is yet to be closed. We ran into a challenge for adding a new row. We are planning to close this in v1.9.4 or v1.9.5

**Comment by dilippitchika** [comment]
@souma-ghosh @somangshu can we treat this as high priority since we have regressed a lot on the timelines?
