### ISSUE TITLE
[Task]: Prominent display for git changes to catch user's attention on deploy modal 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

As a part of displaying the migration changes currently we are communicating this with message string on the deploy modal. This is not very prominent as user's are missing the message and end up in a panic state. 
Slack thread: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1651518390613139

**Comment by infinitetrooper** [comment]
Stale - Closing this.
