### ISSUE TITLE
[Enhancement]: Ability to read clipboard content copied via copyToClipboard()

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#13693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Right now we have a method to copy the contents to clipboard via Appsmith. Manually cmd+v does paste the copied content, but would also need a way to paste it programmatically - which can be a direct method something like readClipboardData() or allowing usage of Keyboard events via JSObj functions to achieve the same.

### Steps To Reproduce

1. Copy some content into clipboard using copyToClipboard('some text')
2. Try to output this data via a showAlert() --> right now there is no way to access the clipboard data
3. **Expected: Should be able to access clipboard contents via Appsmith**

### Version

Prod/Release v1.6.23

**Comment by Nikhil-Nandagopal** [comment]
@Aishwarya-U-R if you wrote the code to copy the data to the clipboard, then you can use the same data in the showAlert right? Doesn't seem like a valid use case

**Comment by Aishwarya-U-R** [comment]
@Nikhil-Nandagopal Ok, so if I also showAlert on same string copied - How does a user know copyToClipboard method is actually working? Simply copy & trust that its copied to clipboard without being able to access it?
And, I want to use it instead of storeValue at times! 
storeValue tends to have a variable name also attached to it & alive even after value in it is removed, while copyToClipboard - I can use & dispose the value & not care about the dummy variable still existing during the whole lifetime of the application.

**Comment by Aishwarya-U-R** [comment]
Yes, so how to paste from within Appsmith without manually doing cmd/ctrl+v?

**Comment by Nikhil-Nandagopal** [comment]
@Aishwarya-U-R you cannot paste programmatically. To verify if it's in the clipboard, you can manually try it because that is what the clipboard is for.
