### ISSUE TITLE
[Bug]-[400]:error js function already exists after deleting

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

to quote the user:
"It seems that the JS objects cache the functions you create, and there's no way to clear that cache.  I got an error that one of my controller functions already exists, even though I deleted it a while ago.  When I tried to delete and recreate the controller, it started saying that all the functions already existed, and the entire page started glitching.  I was able to get around this by cloning the page and deleting the old one, but this bug seems like something we'd want to fix."

### Steps To Reproduce

I was not able to reproduce this issue. Just posting here as reported by the user.

### Version

Cloud

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 100 |
| Effort (months)  | <<number>> |

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur are we able to reproduce this issue? It seems like it needs more information because I'm unable to reproduce this

**Comment by zzgvh** [comment]
I'm seeing similar issues. From time to time, have not been able to make it reproducible :-( but it still happens sometimes. Whe JSObjects were new it was much more common. The only lead I can give you is that I can fix it by renaming the JSObject twice: JSObjOrigName -> JSObjNewName1 -> JSObjNewName2 -> JSObjOrigName.

**Comment by ogbofjnr** [comment]
Having this issue on latest version. Especially when server overloaded and requests hit timeout.

**Comment by bharath31** [comment]
I'm able to reproduce this error by performing the following actions in quick succession: 
1. Create an app with at least two pages
2. Create a JSObject in Page1 and add a function with a unique name eg: 'helloWorld: () => {}`
3. Create another JSObject on Page1 and add a function with the same name `helloWorld: () => {}`
4. Delete one of the JSObjects, quickly open Page2 and switch back to Page1. Notice the error.

**Comment by satbir121** [comment]
@bharath31 Can you please test by throttling the network as well? It's pretty easy using chrome Dev tools.

[How to simulate slow network in Chrome](https://www.browserstack.com/guide/how-to-perform-network-throttling-in-chrome)

**Comment by bharath31** [comment]
@satbir121 this is reproducible on a throttled network as well 

![slow 3g](https://user-images.githubusercontent.com/17562726/195038301-04b63f45-e319-4af7-8683-896974260e27.png)

![no throttling](https://user-images.githubusercontent.com/17562726/195038277-f931abe0-2764-4451-a169-9030d3f63cff.png)
