### ISSUE TITLE
[Bug]: Even after discarding the changes on the old apps still 1 change retains

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even after discarding the changes on the old apps still 1 change retains
![image](https://user-images.githubusercontent.com/45958978/167578329-b1aa4409-8916-4146-a8de-4d1fdd8124e2.png)

```json
{
    "responseMeta": {
        "status": 200,
        "success": true
    },
    "data": {
        "modified": [
            "pages/API/canvas.json"
        ],
        "added": [],
        "removed": [],
        "conflicting": [],
        "isClean": false,
        "modifiedPages": 1,
        "modifiedQueries": 0,
        "modifiedJSObjects": 0,
        "modifiedDatasources": 0,
        "aheadCount": 0,
        "behindCount": 0,
        "remoteBranch": "refs/remotes/origin/master",
        "discardDocUrl": "https://docs.appsmith.com/core-concepts/git-sync#discard-and-pull-changes"
    }
}
```

### Steps To Reproduce

1. Get Old git connected application
2. with  lot of old changes
3. Discard removed all of them but one.
4. the last one cannot be removed via discard.
5. Commit changes
6. Reload app, see that canvas.json change is still here.

### Version

release

**Comment by abhvsn** [comment]
@RakshaKShetty can you please make a commit and post the diff we are seeing in the remote?

**Comment by IAmAnubhavSaini** [comment]
@abhvsn  https://github.com/RakshaKShetty/api_import/commit/b83ef4b924c33009e06a967710313b3081fc5cf1

**Comment by abhvsn** [comment]
Closing this as we are tracking this under https://github.com/appsmithorg/appsmith/issues/14411
