### ISSUE TITLE
[Bug]: Icon added to Input widget disappears on making it a multiline text

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I resize an input widget border, the icon added to the widget disappears.

Expected behaviour - The icon should accordingly get placed in the widget.

### Steps To Reproduce

1. Drag and drop an input widget to the canvas
2. Add an icon from the property pane Icon Options. 
3. Set Label position to Top
4. Resize the border of the Input widget.
5. On resizing to a little more than one line of text spacing, the icon disappears.

### Version

Release AND Production

**Comment by dilippitchika** [comment]
So when you resize an input widget it becomes a text-area, i think that is the reason why icon is not retained. 

Let's check from a tech standpoint if this is possible or not first and the effort, then we will plan this

**Comment by techbhavin** [comment]
@dilippitchika  , I agree with your comment 

when we resize the input widget then it will convert into text-area and  text-area doesn’t have the property to set an icon in the blueprint UI library 

so that’s not possible

**Comment by Nikhil-Nandagopal** [comment]
That's a great point. Let's close this then
