### ISSUE TITLE
[Bug] Confirm on reload is not functional for pageLoadActions

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1370]
Steps to reproduce
1) Navigate to editor 
2) Add a Query 
3) Navigate to settings 
4) Toggle on Confirm on reload
5) navigate to editor
6)Add a table widget with binding a query
7) Refresh the page and observe

Observation:
It is observed that the Confirm on reload is not functional  as the pop up asking for confirmation is not dispalyed in editor mode as well as Deploy mode

Expectation:
On refresh or in deployment the user must be displayed with an confirmation pop up to run the query

This is on both FF and Chrome

**Comment by Nikhil-Nandagopal** [comment]
@prapullac this is only meant to run on trigger
