### ISSUE TITLE
[Bug]: mysql remote host username not following mysql host, but appsmith server host

### ISSUE THREAD

**Issue by iwyrobi** [appsmithorg/appsmith#13701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i try to connect to remote mysql server 10.2.2.7, the username not set to user@10.2.2.7 but user@10.2.2.17

10.2.2.17 is the host of appsmith app deployed.

### Steps To Reproduce

1. Goto datasource mysql
2. add remote host
3. add username and password
4. test

![2022-05-10_12-22](https://user-images.githubusercontent.com/32827701/167542185-014076f8-fc37-4823-9490-662e361e3543.png)

### Version

Appsmith v.1.6.25 (self hosted)

**Comment by sumitsum** [comment]
@iwyrobi the issue that is reported here in the screenshot is coming from the MySQL sever i.e. Appsmith is not generating this error message. The error message format matches the error message which is received when remote connection is not enabled on MySQL. Please check out the solution mentioned here: 
https://tableplus.com/blog/2019/09/access-denied-for-user-root-localhost-mysql.html 
https://stackoverflow.com/questions/41645309/mysql-error-access-denied-for-user-rootlocalhost
