### ISSUE TITLE
[Bug] Response body is not displayed to user when HTTPS is not added to API

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1371]
When the API is added without HTTPS and run for Success it is observed that the response body is not added however the status 200 is displayed to user 

![Screen Shot 2020-10-23 at 6 44 57 PM](https://user-images.githubusercontent.com/71753653/97007989-ddab4e80-155f-11eb-91eb-026acdd6af2b.png)

**Comment by hetunandu** [comment]
Seems to be working with other apis. Maybe just a pipedream specific thing?

**Comment by hetunandu** [comment]
@prapullac please confirm this again

**Comment by prapullac** [comment]
@hetunandu : This is working as expected we can close the issue
