### ISSUE TITLE
[Docs]: Update DynamoDB docs; primary key/partition key

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#13727]
## Primary / Partition Key
There was some confusion regarding how to use the primary key for DynamoDB. In our docs, we refer to it only as "Primary Key" -- in the DynamoDB docs, they also use terms Partition Key, Sort Key, Composite Primary Key; it can all be a bit confusing.

It may helpful in our docs to either include a brief description of what these keys are, or at least add a hint block that links to the appropriate AWS docs where it describes these terms.

[From AWS](https://aws.amazon.com/blogs/database/choosing-the-right-dynamodb-partition-key/):
> What is a partition key?
>
> DynamoDB supports two types of primary keys:
>
> * Partition key: A simple primary key, composed of one attribute known as the partition key. Attributes in DynamoDB are similar in many ways to fields or columns in other database systems.
>*  Partition key and sort key: Referred to as a composite primary key, this type of key is composed of two attributes. The first attribute is the partition key, and the second attribute is the sort key. All data under a partition key is sorted by the sort key value. The following is an example.

## Operations
Lastly, a user had asked about retrieving multiple items from the DB; there are operations to do this (like a SCAN), which we have not documented on our end. It doesn't seem worthwhile to document all of the possible DynamoDB operations in our docs, since there are so many of them and they don't require any special configuration from the Appsmith platform.

I'm not sure if any action should be taken about the last part, but I included it for consideration.

**Comment by jnikhila** [comment]
Technical review completed by @sumitsum. [Doc published](https://docs.appsmith.com/reference/datasources/querying-dynamodb).
