### ISSUE TITLE
[Enhancement]: Update the default themes in app theming 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The default themes could be improved in app theming as the colors are not either appealing or typically used in apps.

### Why should this be worked on?

By default apps built in appsmith should look amazing

**Comment by UXFalcon** [comment]
Update:
We have defined new color palette along with color palette name 
The information can be found[ here ](https://www.notion.so/appsmith/App-theming-s-Default-color-s-4dee614f47d6481bb4225fc835368119)

**Comment by dilippitchika** [comment]
New themes are documented above, @jsartisan please check

**Comment by dilippitchika** [comment]
Scope:
1. Remove sharp, rounded and modern themes
2. Add the new themes listed in the document above
3. Whenever a new app is created automatically apply the earth theme
