### ISSUE TITLE
[Bug]: The discard change action is not performed correctly on older apps

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The discard change action is not performed correctly on older apps
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/167768235-a9330b2a-e893-4a53-9f45-856baea756a8.png">

### Steps To Reproduce

1. Open any older app which is connected to git
2. The app should have both uncommitted changes and the changes to pull
3. Now discard the change
4. The progress bar will be struck for long long time

### Version

release

**Comment by abhvsn** [comment]
@RakshaKShetty how did we end up in 1 commit ahead scenario here? This is causing the issue as there is merge conflict now after you pull the changes. On the other hand @IAmAnubhavSaini should we make a provision to display the error message here?

**Comment by IAmAnubhavSaini** [comment]
@abhvsn I think we make a commit to local repo even when it is `n` commit behind remote repo. Next time you load this page you see `1 commit ahead`.

**Comment by abhvsn** [comment]
This is a valid scenario in that case. @IAmAnubhavSaini can we display a proper error message as we can't resolve the merge conflicts without the user intervention?

**Comment by abhvsn** [comment]
Closing this as we are tracking this under #14411
