### ISSUE TITLE
[Bug]: Discard the change staying in the newly created page throws a page not found error

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Discard the change staying in the newly created page throws a page not found an error

### Steps To Reproduce

1. Connect the application to git 
2. now add a new page 
3. discard the change
4. The user will be navigated to page not found error

### Version

release

**Comment by abhvsn** [comment]
This is the expected behavior @RakshaKShetty as the new page is not present in the repo. Do we have different expectations?

**Comment by abhvsn** [comment]
@vuiets @Debsourabh should we look into this issue? I think we should give a CTA to redirect users to the default page for that particular branch.

**Comment by vuiets** [comment]
At this point are we able to tell if we are on that page that was discarded @IAmAnubhavSaini?

**Comment by IAmAnubhavSaini** [comment]
@vuiets We can figure out if we are on one of the pages that are going to be discarded. After discard, no.

**Comment by vuiets** [comment]
Alright in this scenario, where we are on a page that's going to be discarded, can we redirect to the home page after the discard?
