### ISSUE TITLE
[Bug]-[60]:Incorrect behaviour for Icon Alignment property set to right, for Start and Center Placement in Menu Button Widget

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#13745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Icon Alignment property is set to right ->, for Start and Center Placement, the behaviour is incorrect (Compared with Prod)

Expected behaviour - Should be as per current behaviour on Prod

### Steps To Reproduce

1. Drag and drop a menu button widget. 
2. Attach an icon to it
3. Icon Placement - let it remain at Center
4. Change the Icon Alignment to right. The icon moves to the extreme right, pushing the text to extreme left. This is incorrect behaviour. 
5. Now change the Icon Alignment to left. Make Icon Placement to Start
6. This behaviour is ok. However, on changing the Icon Alignment to right again, same issue as point 4 is seen.

Expected behaviour - Should be as per current behaviour on Prod
<img width="709" alt="Release_IconPlacement_Start" src="https://user-images.githubusercontent.com/101863839/167805284-e1b86e81-ae17-4b86-9403-addd902d6a43.png">
<img width="726" alt="Release_IconPlacement_Center" src="https://user-images.githubusercontent.com/101863839/167805294-11b5ec8e-0636-4881-9a9d-19f29ed865d4.png">
<img width="752" alt="Prod_IconPlacement_Center" src="https://user-images.githubusercontent.com/101863839/167805305-0421968b-f5d2-4a6b-ac8e-0427c0cd7d36.png">
<img width="762" alt="Prod_IconPlacement_Start" src="https://user-images.githubusercontent.com/101863839/167805311-56a9e3ff-2958-41a6-8b4c-a55d2e8f2ccd.png">

### Version

Release

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 60 |
| Effort (months)  | 0.5 |
