### ISSUE TITLE
[Bug]: Documentation - Version select - App crashes when we select any version in the third click (random order)

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#13752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we go to Documentation, and select any version 
for eg., V1.2.1 and then select 1.0.0 and then V1.2, app crashes.

### Steps To Reproduce

1. Go to "Documentation"
2. Select any version in the left top corner (Eg: V1.2.1)
3. Select another version (Eg: V1.2)
4. Select another version (Eg: 1.0.0)
5. Observe App crash (Happens both in release and prod)

https://user-images.githubusercontent.com/104895602/167835497-a5728a2f-d7c7-4a7e-a6d2-bca9d1dc18b0.mp4

### Version

production & release

**Comment by Nikhil-Nandagopal** [comment]
@Sripriya93 this actually seems to be an issue with Gitbook. Could you raise an issue with them?
