### ISSUE TITLE
[Bug]: Select Widget - On entering a filter value unrelated values are also displayed

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#13754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user enters a value in the filter option, other options which are not related to the filter are also displayed.
![Select Widget 01](https://user-images.githubusercontent.com/39921438/167858453-182e4685-ac2f-4412-aaa6-f17e0e2d3bcc.PNG)

### Steps To Reproduce

1. Drag the `Select` widget onto the canvas.
2. Click on the drop down option.
3. Enter a value in the `Filter` field.

**Expected:** Only entries related to the value entered should show up.
**Actual:** Unrelated entries also show up

### Version

Release

**Comment by dilippitchika** [comment]
Hey @shadabbuchh is server side filtering turned on?

**Comment by shadabbuchh** [comment]
@dilippitchika no.

**Comment by dilippitchika** [comment]
Ok, let me check. If this is not working then it should be high or critical.

**Comment by dilippitchika** [comment]
![Screenshot 2022-05-12 at 10 30 35 AM](https://user-images.githubusercontent.com/19730984/167995463-3d9c815e-b470-43e1-8c29-7b632f481c96.png)

@Tooluloope do you know why the search shows results from items which don't have the same characters? It's first doing an exact match then it shows weird results.

**Comment by Tooluloope** [comment]
THis is weird, Wasn't like this before now.
looking into this

**Comment by shadabbuchh** [comment]
@Tooluloope please clarify the following:
When the user types something in the `filter` section, options that contain those typed in characters somewhere in them also show up in the suggestions e.g. below I typed in "re" and the suggestions that came up were "Red"(as expected) & "Green"(maybe because it also contains "re" in it). Is this something that is built deliberately or should this also be fixed?
![Select Widget_after fix.PNG](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/0bfe4ed7-20f7-42af-9235-683e21ff4127)

**Comment by Tooluloope** [comment]
@shadabbuchh the filtering should only shows items that have the filter text, 
I.e if "re" is inputed, only options with "re" in either label or value should show up.

**Comment by shadabbuchh** [comment]
Thank you @Tooluloope. Will close this bug as now it is working as expected.
