### ISSUE TITLE
[Bug]: Git sync modal shows uncommitted changes, even when there are no changes made.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#13778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On creating new app , adding actions and connecting it to git, initially in git sync modal ; it shows commit input box as disabled with text "No changes to commit". However on reopening the modal it shows "1 query modified" .
<img width="1235" alt="Screenshot 2022-05-11 at 11 12 54 AM" src="https://user-images.githubusercontent.com/80334441/168011291-47826bc6-614e-4464-9404-2424908353d3.png">

### Steps To Reproduce

1. Create new app
2. Create JSObject and add function (do not add semicolon in return statement)
myFun1: () => {
		return "Success"
	}
3. Connect it to git, and close modal
4. Open modal again and observe

### Version

release

**Comment by vuiets** [comment]
Hey @Parthvi12 thanks for catching this! Is this consistent?

**Comment by Parthvi12** [comment]
@vuiets Yes, this is consistent using function I mentioned i.e. when I don't give semicolon in the return statement.

**Comment by AnaghHegde** [comment]
@Parthvi12 Are you still facing the issue? I tried reproducing the issue but had no luck.

**Comment by vuiets** [comment]
@Parthvi12 @AnaghHegde can we check this again?

**Comment by Parthvi12** [comment]
@vuiets Not able to reproduce this now, should we close it?

**Comment by vuiets** [comment]
Yes closing this then. Thanks for checking @Parthvi12.
