### ISSUE TITLE
[Bug] Refreshing table data should not clear the selection

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1377]
### Steps to reproduce the behaviour:
1. Drag a table
2. Connect it to a Query
3. Select a row
4. Refresh the table data
5. The selection is cleared

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal Did you mean the scenario where the table data is changed? Or should it not be cleared only when the table data is the same?

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno let's add a default selected row index field and simply honor that value?

**Comment by Nikhil-Nandagopal** [comment]
closing in favor of #1653
