### ISSUE TITLE
[Bug]: Select family widget overlap when label are Extra Large in size

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#13772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e85ef242dec0445fbe067f34fc4eccd7-00001.gif)](https://www.loom.com/share/e85ef242dec0445fbe067f34fc4eccd7)

### Steps To Reproduce

1. Add a select widget onto canvas and any widget just below the select to observe the overlap
2. Change the Label Text Size to XXL from property pane
3. Change the Position of the label to Top from property pane
4. Observe there is a overlap of dropdown

### Version

Cloud/ Release

**Comment by dilippitchika** [comment]
Known issue being tracked in dynamic height project - https://github.com/appsmithorg/appsmith/issues/11038
