### ISSUE TITLE
[Bug]: On binding table widget from query editor, gives error on canvas.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#13773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/168001429-5fd7e279-5e18-4208-b891-dead8713c179.mov

### Steps To Reproduce

1. Go to query editor.
2. Bind Table widget from suggested widget sidebar.
3. Observe error is shown on debugger.
4. However on refreshing page, the error goes away.

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
Seems to work now
