### ISSUE TITLE
[Bug]: Confusion while accessing persistent and session stores with same names

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#13789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Users have to keep in mind which store they are using for a particular property every time they update the value.
e.g. -
```
storeValue('a', 1) // persistent
storeValue('a', 2, false) // session
```
This creates two copies in two different stores. And the user has to make sure to address the proper store when they want to change the value.

### Why should this be worked on?

We had a user whose app went haywire because they didn't consider this difference.

The app I built to show the difference - https://app.appsmith.com/app/appsmith-store/page1-627b8afe0b47255c28137dca
Video explainer -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c16c99ea8ab54f40a1ddcedffd42a18b-00001.gif)](https://www.loom.com/share/c16c99ea8ab54f40a1ddcedffd42a18b)

**Comment by Rishabh-Rathod** [comment]
@pranavkanade This seems like a bug to me. When we set a value in persistent store it should automatically also set it to temporary store ( not calling it session store as browser sessionStorage persists on page reload. https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage )  

Can you help me understand what is expected in the feature?

**Comment by rohan-arthur** [comment]
not a bug, works as expected

https://github.com/user-attachments/assets/5c77c6cc-55f3-4ad5-b488-ef811114d1d8
