### ISSUE TITLE
[Bug]: Templates page - List of template requests - Page 2 is enabled - No data to display - No "Back" button

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#13788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we go to Templates page by clicking on "Request for a template" from main page and click on "See what other are requesting", we could see "List of template requests" page, if we scroll down there is page number 1 with "Next page" button enabled, but there is no data to display, Also there is no back button, only by clicking on browser's back button we could be able to go back

### Steps To Reproduce

1. Click on "Templates" tab in main page
2. Click on "Request for a template" at the end of the page
3. Observe new tab opens with requests templates page
4. Click on "See what others are requesting"
5. Observe "List of template requests", scroll down to the bottom of the page
6. Observe Page number is displayed with "Next page" Navigation enabled
7. Click on "Next page" button and observe "No data to display"
8. Observe no back buttons available 

https://user-images.githubusercontent.com/104895602/168049810-ad83a820-ede5-4786-b1eb-a64e86da5a1b.mp4

Expected: 
1. If "No data to display", "Next page" should be disabled
2. Back button should be available or page number arrows should be available to move to "Previous page"

Actual:
1. "Next page" button is enabled, when "No date to display"
2. Back button is not available or Previous page button

### Version

Release and production

**Comment by kocharrahul7** [comment]
Issue has been solved
