### ISSUE TITLE
[Feature]-[1046.5]:Widget's label should be clickable to focuses on the associated input

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#13792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a user clicks or touches/taps a label, its associated input should be focused. 

### Why should this be worked on?

Having label associated is good practice for screen readers and it increases the hit area for focusing the input and provides an advantage to anyone trying to activate it — including those using a touch-screen device.

This change has to be made for all the widgets that have a label and also the JSON Form's label-input association logic should change from an implicit approach i.e

```
<label>Do you like peas?
  <input type="checkbox" name="peas">
</label>
```

to 

```
<label for="username">Enter your username:</label>
<input id="username">
```

which is the ideal way

**Comment by ashit-rath** [comment]
Associated issue #12910

**Comment by dilippitchika** [comment]
All html labels autofocus the input when clicked on - https://codepen.io/dilippitchika/pen/JjpZOvE

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2093 |
| Effort (months)  | 1 |
