### ISSUE TITLE
Categorising Git Sync documentation and changing the heading to "Version Control with Git"

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#13790]
Segregate Git Sync documentation into different pages. Currently, there is an information overload as all the Git Sync features are on one page only. Had a conversation with @vuiets and @AnaghHegde where we finally came to the conclusion that it needs to be divided into subpages.
Also, We are changing the name From Git Sync to **Version Control with Git**

**Comment by Pranay105** [comment]
@vuiets , @AnaghHegde Let me know if we need any further changes in the doc structure.

**Comment by AnaghHegde** [comment]
Is this prioritised?

**Comment by AnaghHegde** [comment]
Is there any time line for the above task ?

**Comment by AnaghHegde** [comment]
Can we reorder the connect to git and import from git page? Import from git is at bottom and not very visible. Lets organise the content something like this -
Pre Req - setting the env varaiable
1. Connect to Git
2. Import from Git
3. Generating SSH key
