### ISSUE TITLE
[Docs]: JS Promises -- Check for accuracy and clarity

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#13805]
A user has reported that the JS Promises docs found [here](https://docs.appsmith.com/core-concepts/writing-code/javascript-promises) aren't quite correct and should be revised.

A discussion of the issue can be found [here on slack](https://theappsmith.slack.com/archives/C0341RERY4R/p1652278233844619)

**Comment by jnikhila** [comment]
@ApekshaBhosale - Could you please verify this?
