### ISSUE TITLE
[Bug]: I can't load my Appsmith App using POST request

### ISSUE THREAD

**Issue by zetagalactic** [appsmithorg/appsmith#13809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My request: is it possible to allow Appsmith apps to be loaded by POST request? I hope this won't open any security holes in future updates.

My case:
I'm using software (Bitrix24) that allows me to integrate an external page (Appsmith app in my case) inside an iframe so that it can interact with the internal software. The challenge here is that this software doesn't just load the app as a classic Iframe, it actually uses JS to load the page by a POST request where it sends specific queries to that page to be used. 
What is creating a conflict with the Appsmith is that this software loads the Appsmith app by POST request and not GET request. Actually, if you try to send a POST request to any Appsmith app it will request a  "405 Not Allowed" response.

1. My App URL is: https://app.appsmith.com/applications/623c64644d9aea1b062b2c14/pages/623c64644d9aea1b062b2c17

2. Below is the actual request that Bitrix24 does when loading the Appsmith app page:
  Request URL: https://app.appsmith.com/applications/623c64644d9aea1b062b2c14/pages/623c64644d9aea1b062b2c17?DOMAIN=ibht-engine.bitrix24.com&PROTOCOL=1&LANG=en&APP_SID=1ca972164c2f0479c77b34a76d1a9ed9
  Request Method: POST
  Status Code: 405 
  Referrer Policy: strict-origin-when-cross-origin

### Steps To Reproduce

Easy, just send a POST request (instead of the GET) to any of your Appsmith app URLs and you will get a "405 Not Allowed" response.

### Public Sample App

https://app.appsmith.com/applications/623c64644d9aea1b062b2c14/pages/623c64644d9aea1b062b2c17

### Version

Cloud Latest

**Comment by zetagalactic** [comment]
I found the solution for this!

**Comment by karimsiam** [comment]
can you elaborate more on how you handled post request?
