### ISSUE TITLE
[Bug]-[932]:Unable to access `currentRow` in Menu items of Menu Buttons in Table columns

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#13808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![](https://cdn.discordapp.com/attachments/760761686549463060/974364805303504906/Screen_Shot_2022-05-12_at_1.36.33_PM.png)

### Steps To Reproduce

1. Create a table and set one of the columns to be Menu Button
2. Create or edit one of the menu items in the button
3. Try to access `currentRow` in any of the properties

### Version

Cloud 1.6.23

**Comment by AS-Laguna** [comment]
This issue is very similar to #12359

**Comment by dilippitchika** [comment]
@ashit-rath can you take a look at this? I thought based on #12359 the only place it should impact is the color. But looks like disabled also doesn't work.

**Comment by ashit-rath** [comment]
@dilippitchika I'll check this out.

**Comment by somangshu** [comment]
@dilippitchika can we have RICE prioritization here?

**Comment by dilippitchika** [comment]
Assuming this affects users who have added a menu button and then trying to reference current row in the menu item is 50% of the users 
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 233 |
| Effort (months)  | 0.5 |
