### ISSUE TITLE
[Feature]-[2000]:Tooltip for Icon Button Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#13807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user should be allowed to add a hover for an icon button, just like it is possible for the regular button widget. Therefore, the Tooltip property should be available in the property pane of the icon button widget.

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100104622#part_id=comment-164629100104622-14672317103

### Why should this be worked on?

This would improve the user experience, as users could add tooltips for icon buttons just as they already can for regular buttons.

**Comment by dilippitchika** [comment]
Assuming 50% of icon button widget users need a tooltip

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Requirements:
Developer experience
1. Add a new property called "Tooltip" below the Icon field in the Icon button
2. Tooltip is an input field
User experience
1. Hovering on an icon-button shows the tooltip
2. Tooltip should be visible on hover even if the button is disabled.

Check how the tooltip works in button, it should exactly be the same experience.
