### ISSUE TITLE
[Task]: Include feature branch PRs in sprint review filters

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In the current [sprint review](https://www.notion.so/appsmith/May-2-13-8adbdf30cdcf49d5838e3a4082169d46) filters, we are tracking the total open PRs under _5(b)_

Example filter is: https://github.com/appsmithorg/appsmith/pulls?q=is%3Apr+is%3Aopen++label%3A%22BE+Coders+Pod%22+-is%3Adraft

This filter does not include PRs that are on feature branches, e.g., those for graphql.

**Comment by sumitsum** [comment]
As per my analysis, even non release branch PRs are included as long as the label `BE Coder's Pod` is added to the PR.
