### ISSUE TITLE
[EPIC] Clean URL phase 2

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#13815]
## Requirements for Clean URLs Phase 2:

Allow users to customise app URLs so that they can make their apps as searchable as their requirement. This is the first step to having public apps as well.

## Reasons for change:

1. Allow users to make their apps far more searchable and accessable
2. Optimise their URLs for SEO

## In scope for this Project:

1. Allowing the user to customise the URL with the app and page name to make apps far more searchable
2. Allow the user to set a completely custom single string name for their apps

## Out of scope for this project:

1. Removing Page ID

## Design inputs:

We would like to have the URL customisation at a page level, where a user can customise the URLs for each page. There are a few options for this which are as follow:

1. Adding in a component in this submenu, which adds an “Edit URL” component
    
![Image1](https://user-images.githubusercontent.com/20532920/176602654-ecc38d51-725a-4875-b9d9-c96e5a0513af.png)

    
2. Adding in an edit button which allows users 
    
![Image2](https://user-images.githubusercontent.com/20532920/176602672-221074de-a3eb-4989-a74e-051afff3a5a6.png)

    
    
3. Page properties page (this page can go through a refactor/redesign, but for now, we should add a button into the page properties page, which will allow this to be done easily)
    
    
<img width="1140" alt="Image3" src="https://user-images.githubusercontent.com/20532920/176602686-d3a63828-96bf-49ec-b8bd-0cd7e8a1d472.png">

    

## What we want to allow the user to do:

the user should be able to edit the URL from the “page properties” page.

The current format of the URLs are:

```markup
https://app.appsmith.com/app/<App-Name>/[<](https://app.appsmith.com/app/<App)Page-Name>-PageID/
```

The new format should allow the user to either continue with the current URL structure, or refactor into the following:

```markup
https://app.appsmith.com/app/<Custom-App-Slug>-PageID/
```

When the time comes to deal with Page grouping, our intention is to allow users to create the page groups, and have them reflect in the URL as well. When this happens, we can address this using a ‘-’ to seperate out groups, thereby allowing users to create infinately deep groups, and the layout would look like this

### Possible wireframes (only to highlight functionality).

![Image4](https://user-images.githubusercontent.com/20532920/176602703-46e7b11a-5b96-40ae-a6d3-723e29b57edb.png)

![Image5](https://user-images.githubusercontent.com/20532920/176602719-dc7ae849-74e9-48d4-86f4-30a73b7ca88e.png)

These wireframes are of the page properties page. This page will continue to grow in functionality. For now, the new functionality we want to add is the page URL, and allowing us to edit the page URL.

The 2nd page is to show the editor, where a user can create a new editor. In this editor, all special characters will be replaced with a ‘-’, but this will allow users to edit the slug. The PageID, and the domain

Job stories:

# 

## Job Stories

1. When I use an application regularly I want it to be highly searchable so when I use an app regularly I want the URL to be easily recallable so that I can get to it faster?
2. When I see a URL for an application I want it to reflect what the application does so I can see if it is relevant to me

## Developer Stories

1. When I create an application I want to be able to create a custom URL so I can have it be relevant to the application title
2. When I share my app with my team I want to share a customised but rememberable link so that they can easily get back to it?
3. When I create a single page application I want the URL to be as simple as possible so I can have it as short and memorable as possible
4. When I create a custom URL I want to be able to have a different one for every page so users can access each page seperately
5. When I create an application I want the default URL to be relevant so I can have a relevant URL without having to edit it every time
6. When I create a public application I want the URL to be SEO friendly so I can have my app be discoverable on search engines

**Comment by RoopKrrish9696** [comment]
**Zeplin handoff link for the above issue** 
https://zpl.io/09WMW6x

**Figma designs handoff link for the above issue** 
https://www.figma.com/file/Q6s9qidrQX6b15yUUGR0ES/Clean-URLs---Phase-2-%26-App-settings-design-handoff?node-id=2%3A1
