### ISSUE TITLE
[Bug]-[82]:Delete branch button should be disabled after first click

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click the delete branch CTA, we should disable the CTA so as to avoid the subsequent API calls. 

### Steps To Reproduce

1. Connect app to git, let us take main as default branch
2. Create new branch f1
3. Checkout to main
4. Try deleting the f1 branch and click CTA multiple times and check the network tab
<img width="1688" alt="Screenshot 2022-05-13 at 11 05 59 AM" src="https://user-images.githubusercontent.com/41686026/168217970-b6223e92-9f1e-4593-81c7-60b46db173e1.png">

### Version

Cloud: v1.6.26

**Comment by IAmAnubhavSaini** [comment]
@abhvsn  I am not able to reproduce it, could you share a video of it happening.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 41 |
| Effort (months)  | 0.25 |

**Comment by abhvsn** [comment]
@IAmAnubhavSaini I'm not able to reproduce this on release now, seems like we have fixed this. Closing this now!
