### ISSUE TITLE
[EPIC] Git performance & UX

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#13823]

**Comment by vuiets** [comment]
Can you guys share some context here? Missed this on our planning call because of network issues.

**Comment by vuiets** [comment]
@abhvsn @AnaghHegde @IAmAnubhavSaini @hiteshjoshi can we close this epic if we reached the goals that we set out for it? We could move the remaining items to the next epic to bring git version control out of beta.

**Comment by IAmAnubhavSaini** [comment]
Yes, let's close it. We are not going to get any more time on it. Next git efforts will be on gitV2

**Comment by AnaghHegde** [comment]
I agree with @vuiets. We can close this and move the remaining issue to v2.

**Comment by hiteshjoshi** [comment]
Yeah I will just need to move the issues to Git V2.
