### ISSUE TITLE
[Task]-[3448]:Update the documentation links for 'Version Control with Git'

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#13821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We are discussing a restructure to the `Git Sync` documentation in https://github.com/appsmithorg/appsmith/issues/13790. 

As we've decided to call it `Version Control with Git` going forward and the documentation URL will change to reflect the change, we have to update the documentation links in the Git flows.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 431 |
| Effort (months)  | 0.25 |

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini Can you confirm if the above change requires any FE changes as well? We are planning on pushing this in the next release.

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini I am not saying anything should change on FE. I just wanted to make sure none of the urls are hardcoded on FE.

**Comment by IAmAnubhavSaini** [comment]
To best of my knowledge, no. URLs are not hardcoded.
