### ISSUE TITLE
[Feature] Support deploying on SUSE operating systems

### ISSUE THREAD

**Issue by paususe** [appsmithorg/appsmith#1382]
## Summary

The https://github.com/appsmithorg/appsmith/blob/release/deploy/install.sh script does not support deploying on SUSE operating systems. Please do.

## Motivation

Makes it possible to install on openSUSE/SLES for users of those Linux distributions.

**Comment by Nikhil-Nandagopal** [comment]
@paususe thank you for opening this issue and the PR! We'll have this tested and merged in soon 🎉
