### ISSUE TITLE
[Bug]: "Change theme" property pane persists between the apps

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#13836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Change theme property pane persists between the apps. 

Environment  = RELEASE

https://user-images.githubusercontent.com/14138515/168325295-63345dec-6b84-494f-960f-387abd1650ba.mov

### Steps To Reproduce

1. Create a new app.
2. Click on the change theme in the property pane.
3. Now click on the appsmith icon in the top left corner to open all the applications.
4. Now open a new app, and observe that the "Change theme property pane" still persists.

### Version

Cloud

**Comment by vivekverma2312** [comment]
@keyurparalkar Issues has been tested and working fine.
