### ISSUE TITLE
[Feature]: Merge two applications into one

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#13835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have page "A" inside one application and page "B" inside another application. I would like to have page A and B on the same application. This feature would allow to merge two applications together by adding all pages from app 2 to app 1.

### Why should this be worked on?

Say you're building two internal apps alongside each other. As time goes on, the two projects start to align and share more data. At some point, it's obvious that they should be in the same application, but to do that you have to manually copy over every page, query, and JSObjects. It would be much better to have a built in workflow for this.

**Comment by sharat87** [comment]
There are two distinct problems here. One, move/copy/clone a page in one application to another application. Second, merge two applications, potentially producing a new one (or not), that contains pages from both applications.

The first at least, seems like a very useful feature.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 agreed, I believe it's the first too

**Comment by hiteshjoshi** [comment]
Actually its the mix of both. The user is asking to merge pages of two applications. Its similar to what we doing with templates.

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi but the use case is not to create a 3rd app from 2 apps. It's always to copy or move some part of an existing app to an existing app like in templates right?

**Comment by hiteshjoshi** [comment]
Yes @Nikhil-Nandagopal, the use case is such. The only problem I feel is, if the apps are connected to Git. It will create a lot of changes and might require steps to ask which branch to merge on etc. Hence creating a third app based on default branch seems like a safest option to start with and later we can iterate.

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi ah from that perspective I understand but the problem in creating new apps is that now all the teams need to be notified that the usual URL they use, must be changed to the new URL. That's a big overhead in companies and they prefer that URLs don't change

**Comment by Nikhil-Nandagopal** [comment]
I think this will be solved by reusability so I'm closing it in favor of #5229
