### ISSUE TITLE
[Bug]: a helm chart was deleted for appsmith (1.5.2

### ISSUE THREAD

**Issue by cep21** [appsmithorg/appsmith#13838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is no version 1.5.2 for appsmith on https://helm.appsmith.com/index.yaml

Maybe the CICD needs to be updated to not delete old charts?

This is a problem because we use gitops to keep our cluster consistent and it cannot find 1.5.2 anymore (it's currently 1.5.3 now).

Most helm repositories keep older versions around to reproduce builds that haven't yet upgraded.

### Steps To Reproduce

curl https://helm.appsmith.com/index.yaml

### Version

1.5.2

**Comment by sharat87** [comment]
Hey, thank you for reporting. This indeed looks like a bug. We'll get back to you soon. Thanks.

**Comment by pratapaprasanna** [comment]
Hi @cep21,

Thanks for reporting the issue.

The issue is solved now. You can try downloading 1.5.2 now.
