### ISSUE TITLE
[Feature] Zendesk Voice API Saas Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13844]
### Description: 

This is the reference documentation for the Zendesk Talk API. The Talk API is part of the Zendesk v2 API. Use the Talk API in conjunction with the Support API to work with Talk agents, groups, and tickets.

------------------------
### Documentation:

https://developer.zendesk.com/api-reference/voice/talk-api/introduction/

------------------------
### TO-DO

------------------------
### API Actions Progress
| Action                             | EngSpec Doc | SaaS Manager App | SaaS App Run | Test App Run | QA  |
| ---                                | ---         | ---              | ---          | ---          | --- |
| List Phone Numbers                 | No          | No               | No           | No           | No  |
| Show Phone Number                  | No          | No               | No           | No           | No  |
| Create Phone Number                | No          | No               | No           | No           | No  |
| Update Phone Number                | No          | No               | No           | No           | No  |
| Update Phone Number                | No          | No               | No           | No           | No  |
| Show Digital Line                  | No          | No               | No           | No           | No  |
| Create Digital Line                | No          | No               | No           | No           | No  |
| Update Digital Line                | No          | No               | No           | No           | No  |
| Delete Digital Line                | No          | No               | No           | No           | No  |
| Show Availability                  | No          | No               | No           | No           | No  |
| Update Availability                | No          | No               | No           | No           | No  |
| List Greeting Categories           | No          | No               | No           | No           | No  |
| List Greetings                     | No          | No               | No           | No           | No  |
| Create Greeting                    | No          | No               | No           | No           | No  |
| Update Greeting                    | No          | No               | No           | No           | No  |
| Delete Greeting                    | No          | No               | No           | No           | No  |
| List Agents Activity               | No          | No               | No           | No           | No  |
| Open Ticket in Agent’s Browser     | No          | No               | No           | No           | No  |
| Open a User’s Profile in an Agent’s Browser      | No          | No               | No           | No           | No  |
| Creating Tickets                   | No          | No               | No           | No           | No  |

------------------------

**Comment by rohan-arthur** [comment]
not a priority at present, closing this issue
