### ISSUE TITLE
[Feature] Zendesk Custom Data API Saas Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13845]
### Description: 

The Zendesk custom data APIs lets you connect and understand all your customer data wherever it lives. It consists of the Custom Objects API, Profiles API, and Events API.

------------------------
### Documentation:

https://developer.zendesk.com/api-reference/custom-data/introduction/

------------------------
### TO-DO

------------------------
### API Actions Progress
| Action                             | EngSpec Doc | SaaS Manager App | SaaS App Run | Test App Run | QA  |
| ---                                | ---         | ---              | ---          | ---          | --- |
| List Object Types                  | No          | No               | No           | No           | No  |
| Create Object Type                 | No          | No               | No           | No           | No  |
| Update Object Type                 | No          | No               | No           | No           | No  |
| Delete Object Type                 | No          | No               | No           | No           | No  |
| List Object Records                | No          | No               | No           | No           | No  |
| Create Object Record               | No          | No               | No           | No           | No  |
| Update Object Record               | No          | No               | No           | No           | No  |
| Delete Object Record               | No          | No               | No           | No           | No  |
| List Relationship Types            | No          | No               | No           | No           | No  |
| Create Relationship Type           | No          | No               | No           | No           | No  |
| Delete Relationship Type           | No          | No               | No           | No           | No  |
| List Relationship Records by Type  | No          | No               | No           | No           | No  |
| List Relationship Records by Object| No          | No               | No           | No           | No  |
| Create Relationship Record         | No          | No               | No           | No           | No  |
| Delete Relationship Record         | No          | No               | No           | No           | No  |
| List Custom Object Events          | No          | No               | No           | No           | No  |
| List Jobs                          | No          | No               | No           | No           | No  |
| Create Job                         | No          | No               | No           | No           | No  |
| Search Object Records              | No          | No               | No           | No           | No  |
| Get profiles by user ID            | No          | No               | No           | No           | No  |
| Get profile by profile ID          | No          | No               | No           | No           | No  |
| Get profile by identifier          | No          | No               | No           | No           | No  |
| Create or update profile by user ID| No          | No               | No           | No           | No  |
| Update profile by profile ID       | No          | No               | No           | No           | No  |
| Delete profile by profile ID       | No          | No               | No           | No           | No  |
| Get Zendesk User Events            | No          | No               | No           | No           | No  |

------------------------

**Comment by rohan-arthur** [comment]
not a priority at present, closing this issue
