### ISSUE TITLE
[Feature] Zendesk Help Center API Saas Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13842]
### Description: 

The Help Center API is part of the Zendesk v2 API. Responses are always filtered according to the permissions of the user on whose behalf the API request is made. For example, when the user requests a list of articles in a section, the API returns only the articles the user can view in Help Center.

The API deals only with Help Center items. For example, comments can be made on both articles and requests, but the Help Center API only provides access to article comments. This means that an endpoint that returns "all comments made by a user" actually returns "all comments made on Help Center articles by a user."

------------------------
### Documentation:

https://developer.zendesk.com/api-reference/help_center/help-center-api/introduction/

------------------------
### TO-DO

------------------------
### API Actions Progress
| Action                             | EngSpec Doc | SaaS Manager App | SaaS App Run | Test App Run | QA  |
| ---                                | ---         | ---              | ---          | ---          |---  |
| List Articles                      | No          | No               | No           | No           |No   |
| Create Article                     | No          | No               | No           | No           |No   |
| Update Article                     | No          | No               | No           | No           |No   |
| Archive Article                    | No          | No               | No           | No           |No   |
| List Comments                      | No          | No               | No           | No           |No   |
| Create Comments                    | No          | No               | No           | No           |No   |
| Update Comment                     | No          | No               | No           | No           |No   |
| Delete Comment                     | No          | No               | No           | No           |No   |
| List All Labels                    | No          | No               | No           | No           |No   |
| Create Label                       | No          | No               | No           | No           |No   |
| Delete Label                       | No          | No               | No           | No           |No   |
| List Categories                    | No          | No               | No           | No           |No   |
| Create Category                    | No          | No               | No           | No           |No   |
| Update Category                    | No          | No               | No           | No           |No   |
| Delete Category                    | No          | No               | No           | No           |No   |
| Search Articles                    | No          | No               | No           | No           |No   |
| Search Posts                       | No          | No               | No           | No           |No   |
| List Sections                      | No          | No               | No           | No           |No   |
| Create Section                     | No          | No               | No           | No           |No   |
| Update Section                     | No          | No               | No           | No           |No   |
| Delete Section                     | No          | No               | No           | No           |No   |
| List External Content Records      | No          | No               | No           | No           |No   |
| Create External Content Record     | No          | No               | No           | No           |No   |
| Update External Content Record     | No          | No               | No           | No           |No   |
| Delete External Content Record     | No          | No               | No           | No           |No   |
| List External Content Sources      | No          | No               | No           | No           |No   |
| Create External Content Source     | No          | No               | No           | No           |No   |
| Update External Content Source     | No          | No               | No           | No           |No   |
| Delete External Content Source     | No          | No               | No           | No           |No   |
| List External Content Types        | No          | No               | No           | No           |No   |
| Create External Content Type       | No          | No               | No           | No           |No   |
| Update External Content Type       | No          | No               | No           | No           |No   |
| Delete External Content Type       | No          | No               | No           | No           |No   |  

------------------------

**Comment by rohan-arthur** [comment]
not a priority at present, closing this issue
