### ISSUE TITLE
[Bug]: in MultiSelect widget, sometimes the selectedOptionLabels returns selectedOptionValues instead

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you try to use a MultiSelect, and set a default value, sometimes the selectedOptionLabels property returns the selectedOptionValues property.

This can be seen with the base values set when you import the widget onto the canvas.

### Steps To Reproduce

1. Drag a MultiSelect widget onto the canvas
2. Drag 2 text widgets onto the canvas
3. Set the text value for each of the text fields as MultiSelect1.selectedOptionLabels and MultiSelect1.selectedOptionValues
4. With the base configuration set for the multiselect, the selectedOptionLabels should return an array containing Red and Green, however it returns RED and GREEN

Upon changing the value, it works as expected.

### Public Sample App

https://app.appsmith.com/app/untitled-application-24/page1-6281d5c52c1e3f03d32a1b1d

### Version

Cloud v1.6.24

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal why is this critical? Who is using "selectedOptionLabels" in their app and in default?

**Comment by dilippitchika** [comment]
This is already being tracked here - https://github.com/appsmithorg/appsmith/issues/12554

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika not many but critical is marked based on whether it broke apps or not, not depending on the reach

**Comment by Nikhil-Nandagopal** [comment]
We can close if its a duplicate
