### ISSUE TITLE
[Feature]: change widget's properties from other widget's action 

### ISSUE THREAD

**Issue by kzerozero0** [appsmithorg/appsmith#13846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For example, I use a checkbox to control datepicker's ablility. If the checkbox is ```isChecked == true``` then i want to disable the datepicker.

![image](https://user-images.githubusercontent.com/103813128/168464652-a01474f0-ef65-4fde-8bdc-3c2f028c882b.png)

I tried, but it seems dosen't work.

### Why should this be worked on?

I think, it's a normal use case.

**Comment by Nikhil-Nandagopal** [comment]
@kzerozero0 Appsmith is based on a reactive paradigm so instead of assigning this property onCheckChange, you just need to assign the disabled property of the datepicker to {{ Checkbox1.isChecked }} and this will disable it if it is checked.
