### ISSUE TITLE
Add custom slugs along with auto generated slugs for pages

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#13850]
Currently the slugs for the pages and applications are auto generated. As there will be option to set them manually from the client side, we should stop auto generating them. It should be conditional.

For example, if an user never changes a slug, it'll be auto generated. If user changes it or chooses an option to disable this (e.g. a checkbox input for auto generate slug), it'll not be auto generated anymore.

**Comment by nayan-rafiq** [comment]
Currently the slugs for the pages and applications are auto generated. As there will be option to set them manually from the client side, we should stop auto generating them. It should be conditional.

For example, if an user never changes a slug, it'll be auto generated. If user changes it or chooses an option to disable this (e.g. a checkbox input for auto generate slug), it'll not be auto generated anymore.

**Comment by arunvjn** [comment]
@nayan-rafiq There will not be a checkbox or a disable autogenerate option on the front-end. 
We should continue to autogenerate slugs but also add an additional field (customSlug)at the page level. 
If this property is present, we will use it to build URLs and not the auto-generated slug.
