### ISSUE TITLE
[Bug]: No way to go back to appsmith applications from the app viewer mode navigation

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. As part of theming change to the navigation, we now don't have a way to navigate to appsmith apps
2. A user who clicks on comment mode cannot come out of it unless they press escape

### Steps To Reproduce

Appsmith apps
1. Deploy the app
2. Observe the appsmith logo is not available in the navigation
3. A user doesn't have a way to go to their apps

Comment mode
1. Click on comment in the view mode
2. Click the button again but it doesn't come out of comment mode

### Version

Release

**Comment by UXFalcon** [comment]
The design has been started on 16th
and Now available for peer review 
https://www.figma.com/file/4Qs7lxAEjpwU0BNG1e9Bis/?node-id=106%3A1912

**Comment by UXFalcon** [comment]
FIY,
The estimated handoff date is set to 15th Jun 2022

**Comment by dilippitchika** [comment]
@jsartisan assigning to you, please check the design and estimate. Reach out in case of confusion

**Comment by UXFalcon** [comment]
@jsartisan 
Please change the app icon. 
[Updated design ](https://www.figma.com/file/4Qs7lxAEjpwU0BNG1e9Bis/?node-id=106%3A1912)
CC @dilippitchika
