### ISSUE TITLE
[Bug] Loading app in view mode always opens default page

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1385]
## Description

In the view mode for a multi-page app, the default page is always opened instead of the specific page that the user wishes to traverse to.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create a multi-page application
2. Deploy the application & go to the view mode
3. Navigate to any non-deafult page
4. Refresh the page

You will see the default page get populated even though the URL belonged to the non-default page. This can be the source of a lot of confusion.

### Important Details
 - Version: Cloud / Self-Hosted v.1.2.10

**Comment by prapullac** [comment]
Verified the issue as it is working as expected
