### ISSUE TITLE
[Bug]: Page name is coming blank on page properties

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#13856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/717a394b16c440a8850ba3ac8b387075-00001.gif)](https://www.loom.com/share/717a394b16c440a8850ba3ac8b387075)

### Steps To Reproduce

Changing page order and deleting the page from page setting page makes the page area blank

### Version

Cloud

**Comment by yaldram** [comment]
Unable to reproduce.
