### ISSUE TITLE
[Bug] Opening applications/ breaks the theme

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1386]
## Description

Opening the home page with the trailing slash `/applications/` breaks the theme and displays the page weirdly

### Steps to reproduce the behaviour:

1. Go to https://app.appsmith.com/applications/

<img width="1678" alt="Screenshot 2020-10-24 at 11 48 59 AM" src="https://user-images.githubusercontent.com/458946/97069586-eb5be500-15ee-11eb-916d-ab7ade8b3828.png">

### Important Details
 - Version: Cloud / Self-Hosted v1.2.10
 - OS: MacOSX
 - Browser: Firefox

**Comment by yash2189** [comment]
Hi! Can you please tell me what needs to be done for this specific issue?

**Comment by ThakurKarthik** [comment]
Hey @mohanarpit @hetunandu can i take this issue? I have a fix ready

**Comment by trishaanand** [comment]
@ThakurKarthik : Go for it! Looking forward to your PR!

**Comment by trishaanand** [comment]
@yash2189 : I am sorry that I completely missed your message and assigned this issue to the second responder. I would be very mindful of this in the future. I hope you can pick up another good first issue and are not discouraged because of my mistake.

**Comment by ThakurKarthik** [comment]
Hey @trishaanand since the issue was not assigned to @yash2189, I started working on it.I assumed that since he did not ask to be assigned, the issue was available. I hope it did not offend anyone.
Thanks

**Comment by yash2189** [comment]
That's alright @trishaanand , since @ThakurKarthik already had a fix for that issue it was better that he got assigned :)

**Comment by prapullac** [comment]
Verified the issue and works as expected
