### ISSUE TITLE
[Bug]: Open and close side bar (Hamburger menu)- not working in first page of Welcome tour

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#13869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we click on Welcome tour in Main page and click on the ☰ (Hamburger menu) in top left corner, we are not seeing opening or closing of side bar. But we are able to see the hover or click message but no action noted.

### Steps To Reproduce

1. Click on "Welcome tour"
2. Observe page loads to first page of "Welcome tour"
3. Click on ☰ (Hamburger menu) in top left corner
4. Observe "Lock side bar open ctrl+/" is displayed
5. Click again observe "Close side bar ctrl+/" is displayed
6. But Side bar is not Locked open or closed 

https://user-images.githubusercontent.com/104895602/168588646-062094ba-cadf-47f9-8aca-5ddb12390eb8.mp4

### Version

release and production

**Comment by hiteshjoshi** [comment]
@akash-codemonk can you debug this?

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk I think ideally we should just hide that option in the onboarding

**Comment by akash-codemonk** [comment]
This isn't related to onboarding. This is an issue in preview mode where entities are not editable so the explorer is disabled(or not visible). As mentioned hiding the icon in preview mode can help fixing this.  
cc @RoopKrrish9696

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk ok lets do that
