### ISSUE TITLE
[Bug]: UI breaks on changing the "Label" placement of closely placed widgets

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#13862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When 2 widgets are placed closely and the user changes the placement of the label of one of the widgets, the widgets overlap with each other.

https://user-images.githubusercontent.com/39921438/168567215-220f0f2b-c832-4249-8aa9-2122f474a5fa.mov

### Steps To Reproduce

1. Drag and drop a `Select` widget.
2. Now drag and drop another widget just below the `Select` widget.
3. Change the position of the label for the select widget from `Left` to `Top`.

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
@shadabbuchh this seems kind of expected. What is the alternative?

**Comment by Nikhil-Nandagopal** [comment]
@shadabbuchh but then if the user changes the label position back, you would expect the widgets to shift back up. I think as an experience it becomes a little confusing because in which cases should it shift back up vs not.

**Comment by dilippitchika** [comment]
We are solving this as part of dynamic height, already discussed with ankur and abhinav. 

The idea is when label moves to top or left app viewers pod will consume the dynamic height api to adjust the widget boundary and move the other widgets.
