### ISSUE TITLE
[Bug]: Unable to login to appsmith using admin credentials

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#13861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Missing auth0 button,  Still appsmith prevents me from logging in.

![image](https://user-images.githubusercontent.com/84702014/168556828-4f6205ca-ada1-42f7-ac3d-a0fe41d12fdf.png)

### Steps To Reproduce

Steps:
Use an external mongodb
Setup auth0
use same email as admin email to login with auth0
destroy container and directory.
Resetup appsmith.

I dont have a way to recoiver this instance.

### Public Sample App

http://3.110.37.87/

### Version

selfhosted

**Comment by sharat87** [comment]
Not sure I understood this.

> destroy container and directory.

After this step, unless I'm misunderstanding this step, how can we ever recover the instance at all?
