### ISSUE TITLE
[Bug]: Allow Half Stars toggle not working in real time

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#13867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The changes made to the `Allow half stars` toggle do not reflect in real time.

https://user-images.githubusercontent.com/39921438/168586346-2acfba9f-471d-44d3-b5bf-3fc0b24637dc.mov

### Steps To Reproduce

1. Create the `Rating` widget. By default the `Allow half stars` toggle is turned off. 
2. Turn the toggle on and enter a decimal value for `Default Rating`.
3. Now, turn off the toggle.

Expected: An error should be thrown.
Actual: No error is thrown to let the user know that the toggle is turned off. Same is true for the other way around.

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@shadabbuchh this is expected. Properties are to control the inputs users give to the widget, but they do not prevent the developer from setting the default of the widget. An example of this would be in a react component, if we were to set halfStars=false and defaultRating=2.5, it would show 2.5 stars
