### ISSUE TITLE
Video link not working 

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith#13877]
I think video link or YouTube video has some issues in the Heroku doc.

https://docs.appsmith.com/setup/heroku

@cokoghenun can you look into this?

![image.png](https://images.zenhubusercontent.com/6256ad80dd2729be5445ad0b/68de64f1-fedb-49a3-a76f-df4ddb4e14e8)

![image.png](https://images.zenhubusercontent.com/6256ad80dd2729be5445ad0b/3eb9ac37-3569-405c-af67-dbd0dd23a925)

**Comment by cokoghenun** [comment]
@harshilp24 I'm not sure if it's a Gitbook issue but it works now
