### ISSUE TITLE
[Bug]: Overlapping of widget name in canvas

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#13873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In some instances the labels that display the names of different components in a widget overlap with each other.

https://user-images.githubusercontent.com/39921438/168597992-be6b3b52-96be-40a2-a638-1289e1462e27.mov

### Steps To Reproduce

1. Create a `Statbox` widget.
2. Hover over the different text boxes.

Expected: The labels for different text boxes should not overlap with each other.
Actual: If there is an error on some text box and the user hovers over another text box, the labels overlap.

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
I don't think we can control whether the labels overlap, but I think the main problem here is that the error should not show permanently and only on hover. @rohitagarwal88 can we fix this small issue? It's quite painful to see the entire screen with errors

**Comment by rahulramesha** [comment]
@Nikhil-Nandagopal @rohitagarwal88 @momcilo-appsmith removing permanent labels when errored is an easy task, but should we provide any other indicators for the user to identify the widgets that have errors, without having to hover over them individually. If not i can go ahead with the changes.

**Comment by Nikhil-Nandagopal** [comment]
@rahulramesha the debugger shows the errors and they will show on hovering the widget so i think that is good enough

**Comment by btsgh** [comment]
Verified in Release. The error only appears on hover now. Works fine.
