### ISSUE TITLE
[Feature]: Add custom widget like Grafana plugin？

### ISSUE THREAD

**Issue by Ye-Ting** [appsmithorg/appsmith#13883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi Team, first of all thank you for this great tool!

I want to add custom widget in [appsmith](https://github.com/appsmithorg/appsmith) .
But I have no idea of how to do that like [Grafana plugins](https://grafana.com/grafana/plugins

![image](https://user-images.githubusercontent.com/8576059/168722616-7211a67c-7dde-4d60-9d68-806fd711a08f.png)

### Why should this be worked on?

I need to add a visual component to the page (like https://g6.antv.vision/zh/examples/net/forceDirected/#basicForceDirected) whose data is dependent on AppSmith fetching data from the database.

**Comment by Nikhil-Nandagopal** [comment]
@Ye-Ting hello 👋 we have this feature tracked here #2033 so I'm closing this issue.
