### ISSUE TITLE
[Feature]-[726]:Enable spellcheck in rich text editor

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#13885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Within the rich text editor currently there is no spellcheck enabled, this prevents users from correcting their spellings

### Why should this be worked on?

Helps users write better in the Rich text editor when they are writing long paragraphs

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 363 |
| Effort (months)  | 0.25 |

**Comment by dilippitchika** [comment]
Expected behavior
1. As a user I want to know what are the mistakes in my words when i write so that I can correct them than send a mis-spelt word
2. As a user I want to correct my mistakes in the words without leaving the page

**Comment by dilippitchika** [comment]
Based on the above behavior, with the current fix the user is only able to see their mistakes but not able to correct them because we have context menu enabled in the RTE. 

We can disable the context menu for now as the user still can use the toolbar to add links.

Place where this can create a problem is when the toolbar is disabled.

**Comment by dilippitchika** [comment]
Check this document, browser based spellchecking section - https://www.tiny.cloud/blog/tinymce-spellchecker/ 

We can add a note on the context menu for user to do ctrl+right click to see the browser right click menu. They also have given the code for us to use.

**Comment by dilippitchika** [comment]
@techbhavin assigning this to you to pick up after the completing the current issue.

**Comment by techbhavin** [comment]
@dilippitchika  @Tooluloope 

to enable spellcheck pro is available only for [paid TinyMCE subscriptions](https://www.tiny.cloud/pricing/).

refer link below
https://www.tiny.cloud/docs/tinymce/6/introduction-to-tiny-spellchecker/

**Comment by ashit-rath** [comment]
@techbhavin We are not enabling the spellcheck pro here. We are just enabling the browser spell check and modifying the context menu (when we right click) to show a small instruction on how to open the browser's right click menu.

Check this out -> https://fiddle.tiny.cloud/gohaab/10

<img width="679" alt="Screenshot 2022-05-24 at 5 17 23 PM" src="https://user-images.githubusercontent.com/88306433/170027564-28cff304-dd8d-418a-92c5-7c692c14015d.png">
