### ISSUE TITLE
[Bug]-[2500]:async tag not updated for cross Js objects

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#13888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Async tag for cross JS objects reference only get updated on edit.

### Steps To Reproduce

Create JsObject2
```
export default { 
	callApi: () => {
		return Api1.run();
	},
}
```

Create JsObject1
```
export default { 
	myFun1: () => { 
		return JSObject2.callApi();  
	},
}
```

Notice `JsObject1.myFun1` and `JsObject2.callApi` are both async (in settings tab)

Change `JsObject2.callApi` -> `return Ap1.data`

Notice `JsObject2.callApi` is not async anymore, but `JsObject1.myFun1` is not updated accordingly.

Making a blank change on `JsObject1` updates the list accordingly.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8c8418d66a9e451ea90a6e5b88f72e6f-00001.gif)](https://www.loom.com/share/8c8418d66a9e451ea90a6e5b88f72e6f)

---

Expected: `JsObject1` should be updated automatically.

### Public Sample App

https://drive.google.com/file/d/1szW_A_YcN-KiIszOzmm9nOYKkR8ZDt_6/view?usp=sharing

### Version

Cloud - Appsmith v1.6.24-SNAPSHOT

**Comment by rohan-arthur** [comment]
6m usage of js object: 2500
consider 25% of users run into this, 625

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 625 |
| Effort (months)  | <<number>> |

**Comment by ayushpahwa** [comment]
6m usage of js object: 2500
consider 25% of users run into this, 625

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 625 |
| Effort (months)  | 0.5 |
