### ISSUE TITLE
[Feature]-[34]:Add TinyMCE CODE plugin in toolbar

### ISSUE THREAD

**Issue by ry-TU** [appsmithorg/appsmith#13882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi Team, first of all thank you for this great tool!

I noticed that the `code` plugin is loaded, however, this is not exposed in the toolbar. 

### Why should this be worked on?

Enabling the `code` will give more flexibility to the user to modify the HTML doing advanced stuff, for example, I'm trying to add a `details` HTML tag since its not supported by TinyMCE by default. I managed to do a workaround (see screenshot below) but the cons is I have to repeat it in all HTML editors if needed

https://user-images.githubusercontent.com/87054659/168705008-dcce3be3-533c-430a-be16-44ff15ec83e4.mov

Enabling the TinyMCE CODE plugin will be something like this in HTML Editor

https://user-images.githubusercontent.com/87054659/168705261-28d9bbcf-8554-4598-9a7f-36c5577b21b0.mov

Let me know your thoughts

**Comment by Nikhil-Nandagopal** [comment]
@ry-TU thanks for the feature request!

**Comment by dilippitchika** [comment]
Hi @ry-TU Thanks for this. This seems fairly advanced for text editing, could you help us understand what you are trying to build better? This will help us prioritise this request faster.

**Comment by ry-TU** [comment]
@dilippitchika we've been using the rich text editor to create instructions or guidelines for our users, the default config mostly gives us what we want however as we update our guidelines to be more effective, we want to have some toggles to show/hide content on it and [summary](https://www.w3schools.com/tags/tag_summary.asp) HTML tag is one way to do it without needing of any custom JS or plugins

**Comment by dilippitchika** [comment]
Hey @ry-TU thanks for the additional context, this helps me understand a bit of why you are doing this. A few questions - 
1. Are these instructions/guidelines editable by your user? Or are they just for reading, because if they are instructions i believe they should never fully disappear and keeping it in a text editor is confusing, please correct me if I am wrong.
2. If the instructions are non-editable, would you be interested in exploring the iframe widget for the time being. You can do all the HTML formatting you need in this widget as well, just that it won't be editable. Apologies if you have already checked this out.

![Screenshot 2022-05-23 at 10 13 58 AM](https://user-images.githubusercontent.com/19730984/169745021-9984e0f7-a763-4231-b755-852c69303bde.png)

**Comment by ry-TU** [comment]
@dilippitchika 

> 1. Are these instructions/guidelines editable by your user? Or are they just for reading, because if they are instructions i believe they should never fully disappear and keeping it in a text editor is confusing, please correct me if I am wrong.

To answer your question, No it will not be editable by our users but our content editor will but also our content editor dont have edit app access they're just the using it.

Sorry for confusion but I should told this earlier, we built an appsmith app as an admin application that has rich text editor to edit guidelines/instructions and that guidelines/instructions is saved in our database via API, and that column fetched and rendered as RAW HTML in different application.

**Comment by dilippitchika** [comment]
Oh, i understood it now. Thanks for the additional context!

**Comment by dilippitchika** [comment]
Assuming only 5% of RTE users need this feature

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 17 |
| Effort (months)  | 0.25 |

**Comment by sheksushant** [comment]
Are there any plans to add this feature?

**Comment by dilippitchika** [comment]
@sheksushant not yet from our side, let me see if any of our external contributors can add it

**Comment by priyanka-mahour** [comment]
@somangshu I have raise PR please check https://github.com/appsmithorg/appsmith/issues/13882
