### ISSUE TITLE
[Bug]: Very long values in APPSMITH_ENCRYPTION_PASSWORD and APPSMITH_ENCRYPTION_SALT makes it skip these variables

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#13889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user flagged this issue. 

> It seems like that very long values for APPSMITH_ENCRYPTION_PASSWORD and APPSMITH_ENCRYPTION_SALT break it somehow to skip email and signup variables.
Now I use shorter ones and everything is working again. 

### Steps To Reproduce

Needs to be investigated and reproduced

https://discord.com/channels/725602949748752515/975730370689499136/975740299005558784

### Version

v1.6.24

**Comment by Nikhil-Nandagopal** [comment]
@sub1983 @sum35h could one of you please have a look?
