### ISSUE TITLE
[Feature]: Perform file ops only when the resource is updated

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#13893]
Currently, we are deleting all the files in the repo and again recreating them from DB resources. This results in unwanted file operations even if the resource is not altered since the last commit. One way to solve this is by checking the updated at field for both corresponding file and the DB object and doing the selective file operations.

New Scope(02/06/22): Add test cases for helper class FileUtils inside appsmith-git.

**Comment by vishnu-gp** [comment]
Increasing the estimate by 2 points to incorporate the new FileUtilsTest scope added to the issue.
