### ISSUE TITLE
[Bug]: Select widget pick from Suggested Widgets is still V1

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#13899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Select Widget V1 doesn't support theming and currently in the suggest Widget Pane, the suggested Select widget given to the user is v1

https://user-images.githubusercontent.com/91450662/168786217-ea043be9-e23b-45c5-b8fa-5936fa4b3d46.mov

### Steps To Reproduce

1. Create any new API & run to fetch results
2. Use the Select from the Suggested widgets section & add to page
3. **Observe the existing theme is not applied**
4. Drag drop another widget & see some changes the previous widget (dropdown highlight color changes)
5. **Observe : Options dropdown is overflowing outside the dropdown field**
6. Change theme, **Observe : Border Radius is still not applied & over flow also persists**
7. **Expected : Select Widget from Suggested widgets also conform to theme & its properties**

### Version

Prod/Release v1.6.26

**Comment by hiteshjoshi** [comment]
I think @akash-codemonk will be the best person to pick this up. Please do let me know Akash if you have the context or would need thoughts here.

**Comment by Aishwarya-U-R** [comment]
Dependent FE [https://github.com/appsmithorg/appsmith/pull/14059](url)

**Comment by chandannkumar** [comment]
The suggested select widget have different Value and Label under map function which results in error. Since select widget requires unique Label and value.
refer video: https://www.loom.com/share/4c8a1aa5a5fb4f9988f02240964f419d 

P.S: Please add the same column name in 'Label' & 'Value' in map function to avoid errors
@AnaghHegde @akash-codemonk Re-opening this issue.

**Comment by akash-codemonk** [comment]
@chandannkumar  This issue is related to widget not considering the current theme selected by the user. The unique value is a different issue altogether. Can we create a seperate issue for the same?

**Comment by chandannkumar** [comment]
@akash-codemonk Thanks for clarification. Creating a new issue to track the same.
Closing and verifying #13899, since the issue with theming has been resolved here
