### ISSUE TITLE
[Bug] JS Switch not converting back to ui

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1389]
## Description
JS switch button converts to js field on first click but fails to convert back into ui field on switch back

### Steps to reproduce the behaviour:
1. For a text widget, convert to js for visibility
2. Click JS again

##### Observation:
Clicking `JS` again is not switching to UI

### Important Details
 - Version: [Cloud / Self-Hosted v1.2.10]

**Comment by prapullac** [comment]
Verified the issue as it is working as expected
