### ISSUE TITLE
[Bug]: UncaughtPromiseRejection: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by pratikbgit** [appsmithorg/appsmith#13901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/9802900/168794679-7a2bbb54-9526-456c-9dc8-a00825e5929e.png)

### Steps To Reproduce

https://appsmith.sim.tradersync.com/app/devtradersyncadminpanel/apply-tag-627cf626c9bd187fc499fa55

![image](https://user-images.githubusercontent.com/9802900/168794679-7a2bbb54-9526-456c-9dc8-a00825e5929e.png)

![image](https://user-images.githubusercontent.com/9802900/168800865-51b3693b-9ad1-466d-b67e-e6127c4946e4.png)

![image](https://user-images.githubusercontent.com/9802900/168796012-c3c09cfb-f932-4020-9006-c479eaeca9ad.png)

### Error
![image](https://user-images.githubusercontent.com/9802900/168806422-6fb476f8-f7fe-443a-a5f7-113d6b78851c.png)

### Public Sample App

https://appsmith.sim.tradersync.com/app/devtradersyncadminpanel/apply-tag-627cf626c9bd187fc499fa55

### Version

v1.6.21 - Selfhosted

**Comment by Nikhil-Nandagopal** [comment]
@pratikbgit in this case, it seems likely that the query SelectGetUSEquityMarket_Ohld_id probably did not return any data and due to that, there is an error when trying to access the id field. Could you check the response of this query and reopen this if you are still facing this issue?

**Comment by pratikbgit** [comment]
@Nikhil-Nandagopal 

Yes i know did not receive any data but why its return an error

**Comment by Nikhil-Nandagopal** [comment]
@pratikbgit because data[0] will be undefined and accessing undefined['id'] is an illegal operation. So here you should either ensure there is always data or add a check for the data being present before you store the value. You can do this by converting it to JS and writing the code as
```{{
  SelectGetUSMarket_Equity.run((res) => {
       if(res.length > 0) {
           // storeValue(...)
       }
   })
}}```
