### ISSUE TITLE
[Bug]: anomalous diffs created during data tree update

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#13905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When making changes to a JsObject, we see `JsObject.methodName[index]` being listed as changes.
(Also noticed in some other entities)

<img width="875" alt="image" src="https://user-images.githubusercontent.com/66776129/168826615-b8d6c3b6-fdaa-43f4-acc0-4329747ba5d9.png">

This shouldn't happen, because in `evalTree` `JsObject.methodName` is a string.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/66776129/168828298-ba33d912-1f31-42f2-a924-ffc0946a37d8.png">

### Steps To Reproduce

1. Create a JsObject
2. Make some changes to it
3. Notice the difference array in console

### Version

Appsmith v1.6.24-SNAPSHOT

**Comment by eco-monk** [comment]
As of now, No case identified where users are impacted.

**Comment by bharath31** [comment]
@Rishabh-Rathod @ApekshaBhosale is this still an issue?

**Comment by Rishabh-Rathod** [comment]
@ohansFavour Could you please confirm once if this issue was closed with your changes to covert JSObject function string object to string literal ?

**Comment by ohansFavour** [comment]
Yes, my changes have fixed this.
