### ISSUE TITLE
[Bug]: Email template when role is changed in a workspace is broken

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#13918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The email received when a user role in a workspace is changed seems incorrect. There is no beginning in the sentence :

"
has updated your role in the organization "vivek's apps" to App Viewer in Appsmith.
"

<img width="1642" alt="Screenshot 2022-05-18 at 10 56 19 AM" src="https://user-images.githubusercontent.com/8403079/168963735-a523d9af-69f5-487d-baf1-5546c7eb1d93.png">

### Steps To Reproduce

On an instance with email setup, update the role of a user with valid email. Confirm this by checking the email received.

### Version

Production

**Comment by vishnu-gp** [comment]
@trishaanand I just tried this from the release branch and was not able to reproduce this. Are there any particular steps to reproduce this other than those mentioned in the description?
![Screenshot 2022-06-15 at 13 07 39](https://user-images.githubusercontent.com/9128194/173770755-24d58093-afdf-46fa-b14e-6252216dc5e8.png)

@vuiets @hiteshjoshi

**Comment by riteshkew** [comment]
No longer validl.
