### ISSUE TITLE
[Bug]: Animation on switching tab in Entity Explorer

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#13929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The animation which is made for the tab switching in the entity explorer seems slow, We should remove it
![Kapture 2022-04-08 at 18 25 57](https://user-images.githubusercontent.com/11089579/168990769-2656b5f8-b549-4061-9b7d-a43f7d1c7a6d.gif)

### Steps To Reproduce

1. Open any app
2. Switch to widgets tab on the entity explorer
3. observe the animation

### Version

Cloud - v1.7.0

**Comment by somangshu** [comment]
This should ideally be like

https://user-images.githubusercontent.com/11089579/168990983-33ea56d9-d587-40bb-98c9-1a7149d092b9.mp4

cc @areyabhishek @momcilo-appsmith @vinay-appsmith we will take this ahead, let us know in case you feel otherwise

**Comment by Parthvi12** [comment]
@arunvjn On switching to widgets tab, Search Widgets is not focused. Could you please add this.
