### ISSUE TITLE
[Bug]: Remove animation on property pane helper tooltip

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#13923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is an animation that comes upon every tooltip in the property pane. This also appears across the app. There should not be any animation here.

![Kapture 2022-04-08 at 18 32 24](https://user-images.githubusercontent.com/11089579/168983706-805419b3-b796-49e5-b8d1-4cf1846f3bca.gif)

### Steps To Reproduce

1. open property pane
2. hover on helper
3. observe that the tooltip has an animation 

### Version

Cloud - v1.7.0

**Comment by btsgh** [comment]
Animation still exists on Release. Discussed with @arunvjn . He is looking into it.

**Comment by arunvjn** [comment]
@btsgh Looked into it. The github action "Sync community workflow" on release-ee keeps failing because of a merge conflict. Any recent changes might not be there on release.app.appsmith.com
