### ISSUE TITLE
[Bug]: Property pane sections - collapse animation

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#13928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The animation in the property pane sections to collapse it is slow and needs to be removed

![Kapture 2022-04-08 at 18 19 48](https://user-images.githubusercontent.com/11089579/168986666-bdc7b842-514c-44f4-ba22-cfcb3cbea2e3.gif)

### Steps To Reproduce

1. open property pane
2. collapse a section
3. observe the animation

### Version

Cloud - v1.7.0

**Comment by Sripriya93** [comment]
Have verified Property pane sections - collapse animation for all widgets and sub widgets 

Waiting for response - Arrow in the right side of each section heading in the property pane might also need to rotate faster along with the collapse. 

Advise needed if we can move this Fix to done

**Comment by yaldram** [comment]
@Sripriya93 thanks for bringing this up, yes they should rotate faster. I have pushed a fix please verify.

**Comment by Sripriya93** [comment]
Have verified both deployments, for collapsing the property pane sections and the arrow. Working fine, Moving to done, Have checked all the widgets and sub widgets property pane and arrows.

**Comment by btsgh** [comment]
Tested on Release. Working fine.
