### ISSUE TITLE
[Bug]: In Table widget for button/icon/menu type when Button Color is selected as Theme color and we toggle JS {{or}}}} is displayed

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#13931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/cc3fad73b9604647aa810a78f4bd42b2-00001.gif)](https://www.loom.com/share/cc3fad73b9604647aa810a78f4bd42b2)

### Steps To Reproduce

1. Drag and drop a table widget
2. Change the column type to icon
3. Scroll to Button color property
4. Select the Theme color
5. Now click on JS
6. Observe {{or}}}} is displayed

### Version

Cloud

**Comment by dilippitchika** [comment]
@keyurparalkar could you please check this once? This is an inconsistency.

**Comment by keyurparalkar** [comment]
@dilippitchika I checked with @jsartisan about this, This issue occurs because the binding value of the button color is not in the following format: `{{Table1.sanitizedTableData.map((currentRow) => (...))}}`. The theming binding should be wrapped up with this special wrapper.

**Comment by dilippitchika** [comment]
@sbalaji1192 is this already something you fixed to support theming in table widget?

**Comment by sbalaji1192** [comment]
@dilippitchika Same behavior is happening in Table v2 as well. I will fix this separately.
@keyurparalkar Could you please make the changes in Table v1?
