### ISSUE TITLE
[Docs] : Update Elastic Search Doc

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith#13934]
This user is not able to connect to elastic search. They shared a screenshot with the error:

![Screen Shot 2022-05-18 at 11.41.07 am.png](https://images.zenhubusercontent.com/6256ad80dd2729be5445ad0b/d3e030e5-bb50-4e57-9f2b-d1a37762cea9)

[Intercom](https://app.intercom.io/a/apps/y10e7138/inbox/conversation/164629100108419)
[Slack Discussion ](https://theappsmith.slack.com/archives/C0341RERY4R/p1652847302097849)
[Docs](https://docs.appsmith.com/how-to-guides/how-to-use-elasticsearch-as-a-data-source-on-appsmith#initial-setup)

Also, add how to use the Auth token.

**Comment by danciaclara** [comment]
@spark-c Can you check if this was taken care of in the recent rehaul?

**Comment by spark-c** [comment]
@danciaclara This field is defined in the doc, although I don't have an example and haven't personally tested it to verify the required format of the API Key due to trouble setting up my own Elasticsearch instance:

> Authorization Header: Instead of the username/password fields, you can provide an Authorization Header to authenticate your queries. This field is only used when the Username/Password for Basic Auth fields are empty.

**Comment by danciaclara** [comment]
@spark-c can you get help from the BE team and get this issue resolved. We need to be able to test what we write in the documentation
