### ISSUE TITLE
Multi Tree Select that works with {{appsmith.URL.queryParams.Param}}[Feature]: 

### ISSUE THREAD

**Issue by PaulMcF1987** [appsmithorg/appsmith#13930]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

I have noticed that all of the widgets that I have tried so far work with `{{appsmith.URL.queryParams.Param}}` with the exception of the Multitree Select.

I have a form structure where I select the table row and that allows me to view the form input. If anything needs changed, I then click edit in the view form which takes me to a different window

I am populating the edit fields using 

`{{navigateTo("EditJob", {"Param": Param.text })}}`

and then pulling the info on the new form using the above - `{{appsmith.URL.queryParams.Param}}`

Should the Multitree Select be populated via this method or is this something which has not yet been added?

### Why should this be worked on?

I feel this would make a more complete app builder and allow more flexibility to users

Without this function, developers will need to look for other options to achieve the same result and there may not be any options available to them

**Comment by Nikhil-Nandagopal** [comment]
@PaulMcF1987 this should be working. Could you please share the steps or a video that shows this not working? If this is added to the default values and the options of the multi select has a matching value, it should work

**Comment by PaulMcF1987** [comment]
@Nikhil-Nandagopal  https://share.vidyard.com/watch/uYYdK9W3uzGgitjYFu3GwJ? That is a video showing the issue

**Comment by Nikhil-Nandagopal** [comment]
@PaulMcF1987 the value "Dedicated multidrop" is not there in the options of the multi tree select

**Comment by PaulMcF1987** [comment]
@Nikhil-Nandagopal 
At 1:40 you will see me pointing this option out in the multi tree select.

**Comment by Nikhil-Nandagopal** [comment]
@PaulMcF1987 looking even closer at 1:04. In the evaluated value, I can see that Dedicated Multidrop has an additional " in front of it. My guess is you are sending the quotes in the query params which is causing this. Are you trying to send the array in the query params? That might be the problem. You can try to store it using storeValue instead and then read it using appsmith.store.Param or serialise the data in the query params to comma separated values

**Comment by PaulMcF1987** [comment]
@Nikhil-Nandagopal The reason it has the Quotes infront of it is beacuse it is usually stored as`["Dedicated Multidrop"]`

I used a function which removed the `[]` but kept the  `""`

I have removed the function which now presents it as `["Dedicated Multidrop"]` and also picks it up in the next page...

Is there a way to remove both the [] and "" and still have it work as it should?

**Comment by Nikhil-Nandagopal** [comment]
@PaulMcF1987 so if it's an array type, what you can do is pass it as
{{ navigateTo('Page', Table1.selectedRow.column.join(",")) }}

This way it will be sent as a string instead of an array
