### ISSUE TITLE
[Feature]: Center align the home page

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, our top-level page on [app.appsmith.com](http://app.appsmith.com/) has the following layout. The content of the page spans the full width of the area next to the side-bar.

![image](https://user-images.githubusercontent.com/20532920/169030767-2641afcc-d23f-4e67-9a17-882abf57d679.png)

With a new page being introduced in the form of templates, our requirement was to have templates and have the ability for the user to filter these templates.

### Why should this be worked on?

**Centering the page content will help us with:**

- Readability of the content, on larger screens.
- Having controls close to the content (eg: filters)
- Treat 'apps' and 'templates' as pages instead of tabs.
- Helps in scaling the design if we want to introduce more pages at this level. Every page can have it's own design layout without having the constrain that every page needs to have a sidebar.

**What does this change involve visually?**

- The sidebar will not be on the extreme left of the page. It will be next to the content.
- The line-separator demarcating the sidebar from the content will be removed.

**Comment by kocharrahul7** [comment]
Would like to bundle in the solution for this issue as well: #8736 [8736](https://github.com/appsmithorg/appsmith/issues/8736).

**Comment by hiteshjoshi** [comment]
Should this be a part of the design system pod?

**Comment by kocharrahul7** [comment]
Abhishek asked Roop to merge this with the Templates phase 2, but I think it makes sense to put it in the design system pod honestly

**Comment by hiteshjoshi** [comment]
Oh yes, while working on templates we can fix this. Good idea. I will switch back labels.

**Comment by kocharrahul7** [comment]
No longer relevant
