### ISSUE TITLE
[Bug]: Inconsistency in Back button and edit Icon in API Editor

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#13932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Back button is not as per design 
2. Edit Icon is different from the design

Ref - https://www.figma.com/file/IfutQTUq3g97j59i3mx6Y4/Appsmith-Screens-Library?node-id=257%3A39431

<img width="381" alt="Screenshot 2022-05-18 at 3 31 40 PM" src="https://user-images.githubusercontent.com/104058110/169013777-1846426d-5fe9-4d46-bede-ea6162126bf3.png">

### Steps To Reproduce

1. Go to API/JS/Query editor
2. Can find back button on the top left of the editor and Edit icon next to title

### Version

Cloud

**Comment by rohan-arthur** [comment]
dependent on this: https://theappsmith.slack.com/archives/CRVRBGU1K/p1655099347851899
