### ISSUE TITLE
[Bug]: Firestore: Same Records Are Displayed on All Pages When Using Pagination in List Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#13946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using **Firestore** and implementing **Server-Side Pagination** for a **List**, it displays the _same records_ on all pages. 
The same implementation works correctly in a Table widget.
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1652372710725879

### Steps To Reproduce

1. Add a **List** widget.
2. Create a **query** that fetches the data.
3. Implement **server-side pagination** and note that the same records are displayed on all pages.

### Public Sample App

https://app.appsmith.com/app/firestore/firestore-pagination-6283d136309fd93a9bf0fe7b

### Version

Cloud  v1.6.26-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
I think this is because the List Widget is not passing Next and Prev for cursorbased pagination

**Comment by dilippitchika** [comment]
@ame-appsmith can you add the sample app for table? I was not able to figure out how to get it to work there as well.

**Comment by pranavkanade** [comment]
@dilippitchika here is the app - https://app.appsmith.com/app/firestore-1/firestore-pagination-62849faf309fd93a9bf12c3f
You already have access to it.

**Comment by dilippitchika** [comment]
@pranavkanade why is the table not wired fully? Clicking on previous from page 3 to go to page 2. It shows data from page 1, this sample app is not fully built out. 

@Tooluloope will you be able to investigate the list part here? I think there's a problem with server side pagination here.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika this is because we don't have a way to disable pagination buttons so when an empty page is detected. It's the same as starting from scratch. This is necessary for cursor based pagination
