### ISSUE TITLE
[Bug]: Incorrect dependencyMap when js binding of widget property is untoggled

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#13940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

we noticed that when we untoggled js binding `dynamicBindingPathList` was updated correctly but transaltedDiffs didn’t receive the update and hence `dependencyMap` was not updated. 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/68918ba13b1f4167b1fc9bd42b583a09-00001.gif)](https://www.loom.com/share/68918ba13b1f4167b1fc9bd42b583a09)

NOTE: As the dynamicBindingPathList got saved correctly and on refresh, we recreated the dependency map. This issue gets resolved on page refresh.

### Steps To Reproduce

1. Add a button widget
2. Toggle JS for `isVisible` 
3. Add JS binding `{{true}}` 
4. check `dependencyMap`, Button will have `isVisible` in dependency.
5. Untoggle `isVisible`
6. check `dependencyMap`, Button still has `isVisible` in dependency.

### Version

1.6.26

**Comment by rohan-arthur** [comment]
not valid anymore
