### ISSUE TITLE
[Bug]-[110]:wrong function is run in js object sometimes

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

this is not always reproducible, but the function selector in the js editor sometimes jumps and changes values unpredictably. So, when I try to run the function that I am currently editing, and the function selector jump occurs, then the wrong function ends up getting executed. 

In my experience, this has happened about 50% of the time when I am working with brand new JS objects.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/98bdeb95a2de4ea49eaec58e5ea9ae7d-00001.gif)](https://www.loom.com/share/98bdeb95a2de4ea49eaec58e5ea9ae7d)

### Steps To Reproduce

explained above

### Version

Cloud

**Comment by rohan-arthur** [comment]
loom video https://www.loom.com/share/98bdeb95a2de4ea49eaec58e5ea9ae7d

**Comment by rashmi-rai** [comment]
[Steps to reproduce ](https://www.loom.com/share/98bdeb95a2de4ea49eaec58e5ea9ae7d)

**Comment by bharath31** [comment]
assuming 5% of users who run a function face this issue 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     |  110 |
| Effort (months)  | 0.5 |

**Comment by bharath31** [comment]
unable to reproduce this
