### ISSUE TITLE
[Bug] Entity names that coincide with internal function names put entities in a bad state

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1396]
## Description

A button named download puts the button in a bad state because it coincides with our internal function name

### Steps to reproduce the behaviour:
1. drag a button
2. name it download
3. the button breaks
4. this could be true of apis / queries as well

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal @appsmithorg/design How should we prompt the error to the user?

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan we can use the same style that we use when an entity is renamed with a name of an existing entity

**Comment by jsartisan** [comment]
Fixed in #1781
