### ISSUE TITLE
[Bug]: Using moment() within js function fails

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i have a simple function which should return current timestamp:

`myFun1: () => {
		let a = moment();
		return a;
	}`
When I run this, the debugger indicates that there is an error. When I try to debug, there are no errors. 
If I replace the return statement as `return a + 1;`, then the function runs successfully.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c2213884e3bc4611b0dff3a94a469ade-00001.gif)](https://www.loom.com/share/c2213884e3bc4611b0dff3a94a469ade)

conversation here: https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1652951480887279

### Steps To Reproduce

explained above

### Version

cloud

**Comment by ApekshaBhosale** [comment]
@rohan-arthur as you did a + 1 it stringified the value and hence it works else you are trying to return whole library.
