### ISSUE TITLE
[Tutorial]: Update : How to Build a Meeting Scheduler (Calendly Clone) in 30 Minutes

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith#13973]
There are certain parts that are confusing for users.

[Tutorial 
](https://www.appsmith.com/blog/how-to-build-a-calendly-clone-in-30-minutes)

[Slack Discussion](https://theappsmith.slack.com/archives/C0341RERY4R/p1652992114164169)

- This highlighted step is not very clear (the user didn't enter the params). Also a screenshot might help.
![image (4).png](https://images.zenhubusercontent.com/6256ad80dd2729be5445ad0b/b4791a66-6efb-45d7-b8f0-4ff231601124)
![image (3).png](https://images.zenhubusercontent.com/6256ad80dd2729be5445ad0b/8f13abc2-60b6-484a-bd9a-cfd56d3a04ae)

-Also this section could be improved by adding more details and screenshots. The user didn't know how to create the API and where to use the CURL command.
![image (5).png](https://images.zenhubusercontent.com/6256ad80dd2729be5445ad0b/c5eba2bc-65f5-435d-8896-c38cc1264c0e)

**Comment by jnikhila** [comment]
@vihar - Could you please take a look at this?

**Comment by vihar** [comment]
@jnikhila I've updated the tutorial with screenshots. I've also added a disclaimer that the article is old and needs editing, meanwhile, users can use the new template we've created here:

https://www.appsmith.com/template/Meeting-Scheduler
 

https://www.appsmith.com/blog/how-to-build-a-calendly-clone-in-30-minutes
