### ISSUE TITLE
[Bug]-[4869]:Table (v1) reverts column positions on sorting if columns returned differ

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#13979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/169489128-6413dfea-6fdf-4b70-bcf0-00901f8656f7.mov

### Steps To Reproduce

1. Connect Table to a datasource which does not return values for some columns (eg used: Mongo TED)
2. Drag drop columns from within table properties to reorder the columns
3. Deploy & Observe: Dragged column remains in its position
4. Now try to sort it
5. **Observe : The repositioned columns reverts to its old position**
6. **Expected: New positions of the table columns should remain after any action taken by user**

### Version

Prod/Release v1.6.26

**Comment by dilippitchika** [comment]
Assuming 60% of table users, (updated order - 90%, sorted an updated column - 70%)

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4869 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@pranavkanade we are waiting for table v2 to get merged to pick up other table issues. Else we will have a merge conflict like we had in theming.
