### ISSUE TITLE
[Bug]-[800]:MySQL - cleaner 'Missing Password' error toast

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#13977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**My SQL: Right now gives the direct message from MYSQL server when no password is provided during connection:**
<img width="987" alt="Screenshot 2022-05-20 at 11 33 51 AM" src="https://user-images.githubusercontent.com/91450662/169483685-cd26aa84-0256-48c7-9c73-349a5ac0a4e9.png">

The error should say something along the lines of `Incorrect username / password. Please provide correct username / password and try again.`

### Steps To Reproduce

1. Create a new MySQL Ds
2. Try to connect without providing password
3. **Observe: Error message is a bit clumsy & unclear**
4. **Expected: A clean error message indicating the cause & helping the user correct it himself!**

### Version

Prod/Release v1.6.26

**Comment by rohan-arthur** [comment]
mysql 6m usage: 2000
assume 20% affected users, because this is basic datasource configuration: 400

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | <<number>> |

**Comment by ahlavorato** [comment]
Could I work on it?

**Comment by sumitsum** [comment]
@ahlavorato thanks a lot for showing interest in solving this issue. However, on re-assessing this problem it feels like it might not be a good candidate for a good first problem. I apologize since this issue was incorrectly marked as a good first problem. I would request you to find another issue to work on. Happy coding :)

**Comment by Bisht13** [comment]
Can I work on this?

**Comment by btsgh** [comment]
Seeing this problem even if we are entering an incorrect password. 
<img width="276" alt="mysqlincorrectpassword" src="https://user-images.githubusercontent.com/101863839/206982038-8b4cd0f5-236f-4649-8359-98afd16b3a09.png">

**Comment by prapullac** [comment]
Hi @vaibh1297 
We need to make a clear statement of error message
Scenario 1: when the password is wrong the user is displayed with error message stating  <Access denied for user admin @157.45.212.33 Password : Yes>
Scenario 2 : when the password is empty the user is displayed with error message stating  <Access denied for user Password : No>
 ![Screenshot 2023-01-05 at 9.46.52 PM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/56c75372-9651-42a9-bd5f-6c4aad43de43)

![Screenshot 2023-01-05 at 9.48.23 PM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/b143d9d0-5b2e-4193-9d89-018a8ce5828d)
