### ISSUE TITLE
[Bug]-[266.5]:Autocomplete doesn't show up in square brackets when the identifier has invalid characters

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#13983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The best match for the auto complete doesn't show up in square brackets when the identifier has invalid characters.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/492f939257544bb2a641118c2ba0dc7f-00001.gif)](https://www.loom.com/share/492f939257544bb2a641118c2ba0dc7f)

### Steps To Reproduce

1. Drag a table
2. Drag a text widget
3. Enter `{{Table1.selectedRow[' ']}}`.

**Expected:** Auto complete options should display in order to make it convenient for the user.
**Actual:** Auto complete `selectedRow` columns do not show up.

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
Tern support autocompletion for square brackets without double quotes but not with qoutes.

https://ternjs.net/doc/demo/index.html#simple

<img width="447" alt="Screenshot 2022-09-02 at 12 49 38 PM" src="https://user-images.githubusercontent.com/23132741/188081104-37a88dbc-1a7f-4d1a-92b5-11a239adfb3d.png">

If the requirement is to support autocomplete specifically with double quotes like VSCode then we might need to check the tern library code and add a fix for it. 

I would consider that an high-effort task.

**Comment by bharath31** [comment]
Assuming users who perform `WIDGET_PROPERTY_UPDATE` with `updatedValue` containing `['` face this issue

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 533 |
| Effort (months)  | 1 |

**Comment by bharath31** [comment]
@Rishabh-Rathod IMO, we should support autocomplete for both `.` and `[]` property accessors. I would suggest creating an issue on [ternjs/tern](https://github.com/ternjs/tern). Could we also list down alternate approaches to get this working?

**Comment by Rishabh-Rathod** [comment]
> Could we also list down alternate approaches to get this working?

We will need to try once with codemirror v6 other than that fixing in ternjs by ourselves or with the maintainer's help is the only option I could think of.

cc: @bharath31

**Comment by bharath31** [comment]
@Rishabh-Rathod gotcha! I see that CodeMirror 6 migration could potentially solve a bunch of issues + allow us to make new enhancements. Could you please share a doc containing a list of issues that could be squashed? This will help us estimate the impact and prioritize the migration.
