### ISSUE TITLE
[Enhancement]: Show an icon indicating Homepage in deployment mode 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1398]
Steps to reproduce:
1) Add multiple page 
2) Define the homepage 
Deploy the application 

observation:
It is observed that the user is unable to identify the homepage of the application 

Expectation:
As defined in the editor mode if user at the deploy mode can identify the homepage it will be user friendly.

**Comment by areyabhishek** [comment]
If the first page is always the homepage, then do we need a different way to depict it? Closing it unless there's a burning need for this.
