### ISSUE TITLE
[Bug]: Org members popover behaviour needs correction

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an organization lists down excess members under `+`, clicking on this icon pops up members list that stays on screen. Hovering over other member bubbles causes them to appear behind this list as seen in the video and the popover does not collapse when the page is scrolled.

### Steps To Reproduce

1. Go to any org that has a lot of members (like our [Appsmith Internal Apps](https://app.appsmith.com/applications#appsmith-internal-apps))
2. Click on the `+` icon where we can see a list of other members on the org
3. Now hover on the left of this icon to see member popover appear hidden behind this list
4. Scroll the page and observe this list stay put on the page even when the icon is out of page view

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bf21920c29cd4757b9d4b0eb62ffd7be-00001.gif)](https://www.loom.com/share/bf21920c29cd4757b9d4b0eb62ffd7be)

### Public Sample App

https://app.appsmith.com/applications#appsmith-internal-apps

### Version

Cloud

**Comment by ankitakinger** [comment]
This is fixed in the updated UI under ADS 2.0. Closing the issue.
