### ISSUE TITLE
[Bug]: Tooltip of camera widget record button flashes on hover when placed on a modal widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a camera widget is placed on modal and user hovers over the record button, a tooltip appears on the top of the camera widget as seen in the video and blinks on hover. The cursor hovering over the record button flashes as well.

### Steps To Reproduce

1. Drop a camera widget over a modal widget
2. Hover over the record button and observe the tooltip flash as seen in the video

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/853548636073458988c3c3e755b30e74-00001.gif)](https://www.loom.com/share/853548636073458988c3c3e755b30e74)

### Version

Cloud

**Comment by dilippitchika** [comment]
Removed the tooltips, so closing this issue
