### ISSUE TITLE
[Bug]: Error message is incomplete on the debugger when user denies running a query

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When query run is declined by user, then debugger displays partial information which does not convey the right information. This needs to be enhanced.

### Steps To Reproduce

1. Set any query to run on page load with user confirmation
2. Refresh page and decline query run on user confirmation modal
3. Go to the query page and observe the debugger display `{}` as error message on `Response` tab and on Error tab, there's an incomplete message as seen in the image below

![image](https://user-images.githubusercontent.com/79509062/169544355-2d1f5a95-4503-432f-8b1d-0193401a5b30.png)

![image](https://user-images.githubusercontent.com/79509062/169544281-b3783daa-ce7d-4e76-82ff-32c2651a5e7c.png)

### Version

Cloud

**Comment by ramsaptami** [comment]
Error message is still incomplete on the Errors tab of the debugger. Toast message displays text as "action was cancelled by the user" but the debugger shows a different text.
![image](https://user-images.githubusercontent.com/79509062/202432167-bbb4b047-ec47-4c9b-b8c5-ef9619d9250b.png)

**Comment by bharath31** [comment]
this is no longer an issue
