### ISSUE TITLE
[Bug]-[2400]:Text overflows on evaluated value pop-up on a query page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#13995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On a query page when the evaluated value displays a long continuous string like a URL, the text overflows on the pop-over as seen in the image below.

### Steps To Reproduce

1. On any query page use a URL param like `appsmith.URL.fullPath` or `Audio1.url` and observe the evaluated value pop-up

![image](https://user-images.githubusercontent.com/79509062/169548457-dfcf8132-4890-4b50-af14-94c95122bbb2.png)

### Version

Cloud

**Comment by rohan-arthur** [comment]
say 1 in 5 users have experienced this

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2400 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
this is no longer reproducible after the new evaluated value pane improvements
