### ISSUE TITLE
[Bug]: Wrong tooltip text in theme property pane

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#13992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Wrong tooltip message is shown on hovering the border-radius and box-shadow

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b55bbe7aa3804e9689f7f4c4c46b9d1f-00001.gif)](https://www.loom.com/share/b55bbe7aa3804e9689f7f4c4c46b9d1f)

### Version

Cloud

**Comment by dilippitchika** [comment]
Show S, M, L respectively for sake of consistency across the platform
