### ISSUE TITLE
[Bug]: mysqlPlugin tests failing on WSL and Ubuntu

### ISSUE THREAD

**Issue by sidhantgoel** [appsmithorg/appsmith#13998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

mysqlPlugin tests fail

### Steps To Reproduce

Run mysqlPlugin tests on WSL on windows
or
Run mysqlPlugin tests on Ubuntu
Tests fail with the following error
`
[ERROR] Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 139.706 s <<< FAILURE! - in com.external.plugins.MySqlPluginTest
[ERROR] testExecuteDataTypesExtensive(com.external.plugins.MySqlPluginTest)  Time elapsed: 0.144 s  <<< FAILURE!
java.lang.AssertionError
        at com.external.plugins.MySqlPluginTest.lambda$45(MySqlPluginTest.java:863)
`

### Version

Appsmith v1.6.26-SNAPSHOT

**Comment by yatinappsmith** [comment]
![image](https://user-images.githubusercontent.com/84702014/172861548-9f006cbd-ffae-4f30-b35a-c8946f3053ca.png)
