### ISSUE TITLE
[Feature]-[10750]:provide a way to kill / stop query execution

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#14006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently if I click on the `run` button on query config page and if the query gets takes a long time to return, then there is no way for me to stop the current execution and re-run the query - except to either wait for the query to time out or refresh the page. 

### Why should this be worked on?

Better user experience.

**Comment by rohan-arthur** [comment]
these following events were triggered about 215,000 times in the past 6 months
RUN_API_CLICK
RUN_API_SHORTCUT
RUN_QUERY_CLICK
RUN_QUERY_SHORTCUT

Even if the user wanted to abort 1/20 such events, the reach is 10750

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 10750 |
| Effort (months)  | <<number>> |

**Comment by ayushpahwa** [comment]
these following events were triggered about 215,000 times in the past 6 months
RUN_API_CLICK
RUN_API_SHORTCUT
RUN_QUERY_CLICK
RUN_QUERY_SHORTCUT

Even if the user wanted to abort 1/20 such events, the reach is 10750

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 10750 |
| Effort (months)  | 0.5 |

**Comment by rohan-arthur** [comment]
design planning link: https://www.notion.so/appsmith/Abort-query-execution-e8a13ded5e464ee68c41c8334bf452ae

**Comment by parth-appsmith** [comment]
Project Product/Design Doc: https://www.notion.so/appsmith/Abort-query-execution-e8a13ded5e464ee68c41c8334bf452ae
Figma Designs: https://www.figma.com/file/GuqV8Or2PStpE3rTknsDzk/API-Pane-Improvements?node-id=919%3A32049
Zeplin Handoff files: https://zpl.io/Amdjn5e
