### ISSUE TITLE
[Bug]-[350]:Log Tab (Debugger)

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#14005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently the `Log` tab on the query execution page shows the record of all action executions or events along with a timestamp but the time shown does not have AM / PM qualifier - hence it can become confusing for the user to figure out if a query was run at x hrs in the morning of the evening. Two ways to overcome this - either append AM / PM qualifier or show time as 0 - 24 hrs clock. 

### Steps To Reproduce

.

### Version

cloud, self hosted

**Comment by bharath31** [comment]
Assuming 5% of users who perform `DEBUGGER_TAB_SWITCH` view logs that are old enough to create timestamp confusion. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 350  |
| Effort (months)  | 0.5 |
