### ISSUE TITLE
[Bug]: App crashes when content of JS Editor is very large

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#14002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App crashes when a large JSON is pasted into JS Editor

### Steps To Reproduce

Paste a very large JSON into a js object function, App crashes.

NB: This is not reproducible on all machines

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
Added estimate of one as this issue was not estimated and according to what we discussed. We should at least have 1 estimate if it wasn’t estimated.
