### ISSUE TITLE
[Bug]-[350]:Debugger logs not getting updated in time

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#14007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sometimes when a query is executed and a response is received, then even though the query execution has completed the `Log` tab does not show the log for the latest query run. It takes 5-10 sec to update, sometimes longer. 

### Steps To Reproduce

.

### Version

cloud, self hosted

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 700 |
| Effort (months)  | 1 |

**Comment by bharath31** [comment]
@sumitsum could you add steps to reproduce? we can close this if this is a stale issue.

**Comment by ohansFavour** [comment]
This issue should be resolved by https://github.com/appsmithorg/appsmith/pull/18285
