### ISSUE TITLE
[Bug] Move all build time variables to runtime variables in the client

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1400]
## Description

Instead of using `REACT_APP_*` variables (that are set at build time), we should move them to `APPSMITH_*` variables that can be set at runtime. This will ensure that users are able to configure their instances on the fly and not need to rebuild the client application.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit is this done?

**Comment by mohanarpit** [comment]
We've migrated the variables that could be migrated. There are a select few that still remain but we don't have a good solution for them yet. Closing this issue.
