### ISSUE TITLE
[Bug]: Scroll for select widget is not proper in view mode

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/48a6450abbfb47b9a4f65e0c37086fdb

### Steps To Reproduce

1. Create new API
2. Run the API
3. Click on select widget from the suggestions
4. Now deploy the app
5. Observe that scroll is not smooth

### Version

Cloud

**Comment by vivekverma2312** [comment]
@dilippitchika I tried with 50 options and able to repro it. Make sure you select the widget from Query page
<img width="1535" alt="Screenshot 2022-05-30 at 1 06 31 PM" src="https://user-images.githubusercontent.com/83569920/170942048-8ec013b7-0f7a-4c09-a620-d92d3b9bed28.png">

**Comment by somangshu** [comment]
Closing this, its related to #13899
