### ISSUE TITLE
[Bug] Refactor : Queries dont get copied from the Parent  page to child page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1401]
Steps to reproduce:
1) Add a query to Page1 bind to table 
2) Now copy a page 
and observe

Observe:
It is observed that the widgets on the parent page gets copied however the binding also remains on the table butit is observed that the query does not get copied for the binding to work 

Expectation:
It is expected that the query and API must get copied.

**Comment by trishaanand** [comment]
This issue was fixed before bringing refactor branch to release. Please verify that this issue does not exist on release. Thanks!
