### ISSUE TITLE
[Bug]: Cyclic dependency when copy paste list widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/2f12ca97faca44e983daa3f8700f0787

### Steps To Reproduce

1. Drag and drop a List widget
2. Bind with query
3. Copy/paste the List widget
4. Observe the cyclic dependency error is displayed

### Version

cloud

**Comment by eco-monk** [comment]
Steps to repro:
1. Drag and drop a list widget
2. Bind image onClick to a function `showAlert("bla bla")`
3. Copy the List

**Comment by eco-monk** [comment]
> this might be related: https://github.com/appsmithorg/appsmith/issues/9181#issuecomment-1041366572

@rohan-arthur. 
Yes, [this](https://github.com/appsmithorg/appsmith/issues/9181#issuecomment-990655310) must have been same (without the flickering)

**Comment by eco-monk** [comment]
When OnClick function is configured for the image.

`dynamicTriggerPathList` is sent as `template.Image1.onClick` for the copied list widget.
Even though the Image widget is named as `Image1Copy`.

---

When this makes it to the `dependencyMap`.  
`template.Image1.onClick` is rolled back to `List1Copy.template`.
And hence results in a cyclic dependency.
