### ISSUE TITLE
[Bug]-[372]:Header node checkbox of a MultiTreeSelect widget does not display properly on hovering

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upon hovering over the header node of a `MultiTreeSelect` widget when not all child nodes are selected, a small line appears inside it. 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/12ba5d3567ee46fc88a68942ead4c236-00001.gif)](https://www.loom.com/share/12ba5d3567ee46fc88a68942ead4c236)

### Steps To Reproduce

1. D&D a `MultiTreeSelect` widget.
2. For a parent node that has multiple child nodes, select only one/a few nodes.
3. Hover over the parent node.

**Actual Behaviour:** A small line gets displayed inside the checkbox of the parent node.

### Version

Cloud

**Comment by dilippitchika** [comment]
Good catch @shadabbuchh 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 186 |
| Effort (months)  | 0.25 |

**Comment by dilippitchika** [comment]
@techbhavin please check this issue

**Comment by shadabbuchh** [comment]
Issue is verified in Release. Working as expected.

https://www.loom.com/share/82285b0b6adc4d9db2e6a02510fadbc0.

**Comment by shadabbuchh** [comment]
This issue is verified in `Release`.

https://www.loom.com/share/2e603811bc9a498a8985b01b90a585c0
