### ISSUE TITLE
[Bug]: GraphQL issues 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#14022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Server Side Issues

- [x] On wrong API being run shows an empty error message 
- [x] On empty body or wrong request the  error message is empty 
- [x] Without the Query variable the API is non-functional ([![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0cee4c43650542eba3f46d8adaeaed41-00001.gif)](https://www.loom.com/share/0cee4c43650542eba3f46d8adaeaed41)
- [x] Incorrect server code is displayed to the user when inappropriate data is added to the Query (5005)
- [x] The error message must be displayed in a more simple format than technically defining the error 

- [x] API does not support Integration with Table from the connections

#### Client Side Issues
- [x] Unable to support bracket pair highlighting in GraphQL
- [x] Number of records can be displayed on the response.
- [x] We are not supporting Prettify Query
- [x] UI is broken in Advanced Settings (general)
- [x] Number of params added is not displayed like that of the Header

Queries:

1. User can add API directly without Datasource by editing the API

### Version

Deploy Preview

**Comment by AmanAgarwal041** [comment]
@prapullac  Can you add a screenshot of the UI related issues. It would be helpful.

Answer to the query `User can add API directly without Datasource by editing the API` :    No, user will have to create a datasource before adding any Graphql API.

**Comment by prapullac** [comment]
![Screenshot 2022-05-23 at 10 23 04 AM](https://user-images.githubusercontent.com/71753653/169813706-1cb68400-7f72-4ad1-b1bf-cffb7f5b76b6.png)

**Comment by AmanAgarwal041** [comment]
**Number of records can be displayed on the response.**
It is difficult tot display number of records on the response because it does not have a structure that it is fixed instead it depends on the graphql query that user created. So it is not possible to display number of records in a generic way.
`Hence, marking this issue as complete task`

**Comment by AmanAgarwal041** [comment]
**We are not supporting Prettify Query**
This can be picked up in V2.
`Hence, marking this issue as complete task`

**Comment by AmanAgarwal041** [comment]
Above mentioned Issues that are fixed in [PR](https://github.com/appsmithorg/appsmith/pull/14053) :
- Unable to support bracket pair highlighting in GraphQL
- UI is broken in Advanced Settings (general)
- Number of params added is not displayed like that of the Header

**Comment by sumitsum** [comment]
Closing since all the issues seem to be have been addressed as per my tests today.
