### ISSUE TITLE
[Bug]: App import fails

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#14021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App import fails
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e5234c593bdf49ee9815e39768bd83c6-00001.gif)](https://www.loom.com/share/e5234c593bdf49ee9815e39768bd83c6)

### Steps To Reproduce

1. import attached app fil
[Habitasaurus (3).zip](https://github.com/appsmithorg/appsmith/files/8753499/Habitasaurus.3.zip)
e

### Version

selh hosted

**Comment by IAmAnubhavSaini** [comment]
I am able to import the application.


https://user-images.githubusercontent.com/1573771/169970026-fe1fbddc-8e86-40bd-a8c3-da59c462e760.mov


https://user-images.githubusercontent.com/1573771/169970103-caf4e236-ed09-42ab-8c8a-33f566901a35.mov

**Comment by abhvsn** [comment]
Closing this as this is being worked on in https://github.com/appsmithorg/appsmith/issues/13503
