### ISSUE TITLE
[Bug]-[876]:User gets an error even when table widget is added from the API page successfully

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the table widget is added successfully from the API page we get to see the below error `The value at primaryColumns.action.buttonColor is invalid`. The API page is still adding the Table widget v1 hence this is a table widget v1 issue.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9f3e514ffe3346ceab5098d61655fe96-00001.gif)](https://www.loom.com/share/9f3e514ffe3346ceab5098d61655fe96)

### Steps To Reproduce

1. Add a datasource and create a new API for the same.
2. After successfully running the the API and getting the proper response in the API page, in the `Add new widget` section of the same page click on the `Table` widget.

**Expected:** The table widget should be added to the canvas and no error should be thrown to the user.
**Actual:** The user sees `The value at primaryColumns.action.buttonColor is invalid` error.

### Version

Cloud

**Comment by dilippitchika** [comment]
Similar to issue found in JS form's first binding which is also a debugger error #12894 

Adding this to actions pod plate

**Comment by rohan-arthur** [comment]
WIDGET_CARD_DRAG, widgetType = JSON_FORM_WIDGET, 6 months unique: 876

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 876 |
| Effort (months)  | <<number>> |

**Comment by dilippitchika** [comment]
Hello @MrChrisRodriguez is this issue somehow blocking you from using appsmith?

**Comment by MrChrisRodriguez** [comment]
@dilippitchika -- when following a getting started tutorial immediately led to a bug, I lost faith in the maturity of AppSmith and ended up leaving and signing up for Retool.

I think it's incredibly important that people using AppSmith for the first time do not run into an unexpected bug like this or they, like me, will feel that it's not worth investing time to continue down the path of learning the tool.

**Comment by dilippitchika** [comment]
@bharath31 @satbir121 please check this out once

**Comment by bharath31** [comment]
@MrChrisRodriguez We're really sorry you had a bad experience. Looks like this issue slipped through the cracks. We'll get this investigated right away.
