### ISSUE TITLE
[Feature]: typeahead feature in gsheets uqi

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I am configuring my GSheets query, I would like to use the type-ahead feature on some dropdowns like `Spreadsheet`, because I might have 100s of spreadsheets, and I would like to find the one I want more easily.

1. go to http://15.206.147.106/
2. add a gsheet query
3. Operation: "Fetch Many"
4. Entity: "Sheet Row(s)"
5. Spreadsheet --> expanding this dropdown shows all of my spreadsheets. Would be nice to have the type-ahead for this field.

**Entity - Sheet Row(s)**

- [ ] Spreadsheet
- [ ] Sheet Name

### Why should this be worked on?

1. this will make it easier for the user to quickly find the entities they want to work with. 
2. the current implementation is vexing to use if I have 100s of spreadsheets in my google account

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2100 |
| Effort (months)  | <<number>> |

**Comment by nidhi-nair** [comment]
The component has been ported to the design system and has its properties available [here](http://design-system.appsmith.com/?path=/story/design-system-dropdown-v2--dropdown-with-search).

**Comment by nidhi-nair** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2100 |
| Effort (months)  | 0.1 |

**Comment by nidhi-nair** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2100 |
| Effort (months)  | 0.1 |

**Comment by nidhi-nair** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2100 |
| Effort (months)  | 0.1 |

**Comment by nidhi-nair** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2100 |
| Effort (months)  | 0.1 |

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2100 |
| Effort (months)  | 0.1 |

**Comment by sneha122** [comment]
Since there are some inconsistencies in dropdown v2 provided by the design systems pod, I have raised [this](https://github.com/appsmithorg/appsmith/issues/16396) after discussing it with Albin.

**Comment by rohan-arthur** [comment]
type-ahead already added, closing this issue
