### ISSUE TITLE
[Bug]: git-status changeset is not shown on deploy tab if user switches from merge tab to deploy tab before the API call finishes

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The deploy tab will be in a disabled state when user moves from merge to deploy tab before the API call finish
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b6d4243fa74a444a8853c40103766bf0-00001.gif)](https://www.loom.com/share/b6d4243fa74a444a8853c40103766bf0)

### Steps To Reproduce

1. In a git connected app, make changes to a page.
2. Open merge tab, quickly click on deploy tab (before status call finishes)
3. Notice that the changeset is not available on deploy tab.
4. Close the modal, open deploy tab from bottom bar.
5. Notice that the changeset is available.

### Version

release

**Comment by infinitetrooper** [comment]
It's working as of v1.9.47, reopen if reproducable.
