### ISSUE TITLE
[Docs] :  Update - Image Widget

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#14040]
[Refer to the thread on Slack](https://theappsmith.slack.com/archives/C01CFTXD0N8/p1653340422893379)

Add details on using SVG Support to the [Image widget](https://docs.appsmith.com/widget-reference/image).

**Comment by SatishGandham** [comment]
@jnikhila , How is using SVG going to be any different from other image formats?

**Comment by jnikhila** [comment]
@SatishGandham - The issue is raised as part of [the Slack thread added to the description ](https://theappsmith.slack.com/archives/C01CFTXD0N8/p1653340422893379)of the ticket. It seems that the issue faced using SVG image format is that there are some more configurations needed (`data:image/svg+xml;charset=UTF-8`)  as per the [Slack communication](https://theappsmith.slack.com/archives/C01CFTXD0N8/p1653340422893379).

The document is not having this information and hence we need to understand what is needed so that users can use SVG images.
