### ISSUE TITLE
[Bug]: When a new user is shared a private app, they see hard to understand errors

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#14048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app   end user is given a non-public link to the application by the developer,And 
1. the end user has an appsmith account 
2. the end user is logged out
3. the end user is not part of the organisation of the developer

After clicking the link the user is sent to Appsmith. A quick message saying “resource not found” appears before redirecting the user to the login screen, which should not be required. The user should be sent directly to the login screen

After logging in, the user is shown an error message saying: "page not found" Which is not ideal, since this does not have a lot of information

### Steps To Reproduce

When an app   end user is given a non-public link to the application by the developer,And 
1. the end user has an appsmith account 
2. the end user is logged out
3. the end user is not part of the organisation of the developer

### Version

1.7.0

**Comment by ginilpg** [comment]
@ankitakinger Is this issue resolved?

**Comment by ankitakinger** [comment]
@ginilpg the error message seen before redirection to login page is handled now. The redirection happens without any error message seen prior to that.

**Comment by ginilpg** [comment]
If user is not logged in we will show 404 page and CTA for login. This way we can convey the message and user can go to login page to access the app.

**Comment by ankitakinger** [comment]
@ginilpg If we are planning to remove the redirection to the login page and show a login CTA on the 404 page instead, then I want to highlight this here:
While making this change, we will have to keep in mind the SSO with private embedded apps scenario. Private embedded apps work with redirection to the login page only. CTA inside the embedded app doesn't work.

For any further queries/info on this, please contact me or @infinitetrooper

**Comment by Nikhil-Nandagopal** [comment]
The correct experience seems to be working. The user is taken to the login page and after they login, they see the app
