### ISSUE TITLE
[Bug]: RTE Widget's values are not getting reflected in the google sheet

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#14045]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I am facing an issue with the feedback form that I created. The feedback form is simple, there are `3 RTEs inside a FORM widget`. The form is connect to a google sheet query. Please find attached the `json` export for the application.
 
**Expected behaviour is:** On click of the submit button, the data should get inserted into the google sheet.
**Observed behaviour is:** Sporadically, the data is not getting reflected into some columns of the google sheet on click of the submit button. Below is the screenshot of the google sheet for this behaviour.

![Screenshot 2022-05-24 at 11 07 37 AM](https://user-images.githubusercontent.com/14138515/169959873-7567cf0c-9db0-4b8e-88a9-7aba28c51335.png)

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0409115e8a43488682242b1b9341c875-00001.gif)](https://www.loom.com/share/0409115e8a43488682242b1b9341c875)

Application JSON:
[application-json.txt](https://github.com/appsmithorg/appsmith/files/8973663/application-json.txt)

### Steps To Reproduce

1. Import the app via json given in the description.
2. Make sure to update the google sheet query with your own google sheet link.
3. Now try to enter the data into the RTE quickly and click on the `send feedback` button.
4. Observe that for some columns the value is not getting reflected.

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
https://github.com/appsmithorg/appsmith/pull/9889/files#r880333079
[@Tolulope Adetula](https://theappsmith.slack.com/team/U0212ERTFH7) seems like we added debounce ( custom implementation ) of 1000 ms for Rich text Editor?
Can you please share why was that added, seems to me the above issue which [@Keyur Paralkar](https://theappsmith.slack.com/team/U02MNT4GKMF) is facing is due it that.
To verify I reduced the setTimeout time to 10ms and things worked fine.
Ideally, we should not maintain value in the state of the component, any reason why we maintain a local state here?

**Comment by keyurparalkar** [comment]
The proposed solution mentioned in this [PR](https://github.com/appsmithorg/appsmith/pull/14126) here was to remove the debounce and the internal state that is present at the component level.

**Motivation for the above change**

> Ideally a widget shouldn’t maintain its own debounce for updating state.
This will lead to worker not getting updated values and then any triggers like API run, storeValue etc will not see the reflected changes visible in UI.

Slack [comment](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1653453921355319?thread_ts=1653394644.532629&cid=C02JV8G1MP0) from @Rishabh-Rathod 

Here is the slack current slack thread for the same. [Thread](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1653565977104299)

Post refactor of the code and applying the above fix mentioned in the PR we found that there are 3 issues that occurred:
1. Removal of default text gets updated in the widget that has Rich text editor's binding but the RTE widget does not get updated value. = FIXED.
2. Text reappears whenever the text is cut or deleted(BackSpace) from the RTE widget.
3. When Input type is MARKDOWN, the cursor shifts while typing.

Here are my findings towards these issues:

**ISSUE-1:** _**Removal of default text gets updated in the widget that has Rich text editor's binding but the RTE widget does not get updated value.**_
 - This is fixed by calling the `onValueChange` function on initial render.

**ISSUE-2:** **_Text reappears whenever the text is cut or deleted(BackSpace) from the RTE widget._**

- _This issue is sporadic and it is difficult to reproduce._ From my observation the issue is sometimes re-producible by enabling CPU throttling from the google chrome's Performance tab.
- After debugging it is found that this issue might be caused due to value prop of tinyMCE's editor component is not receiving the latest value within 200ms. 
- This is a default behaviour for tinyMCE's RTE component. As doc states - 

> Changes to the editor must be applied to the value prop within 200 milliseconds to prevent the changes being rolled back.

Doc [link](https://www.tiny.cloud/docs/tinymce/6/react-ref/#value)

**ISSUE-3:** **_When Input type is MARKDOWN, the cursor shifts while typing._**

- After debugging, the most probable cause for this is - We are converting the MARKDOWN text to HTML with the help of `showdown` library due to which this issue occurs. But Need to do further investigation on the root cause.

Below is the video that explains ISSUE-1 and ISSUE-2.
https://user-images.githubusercontent.com/31691737/171059905-0f64b804-7ec5-4447-a8e2-f54c83c0e990.mov

CC: @somangshu @sbalaji1192 @dilippitchika @Rishabh-Rathod @Tooluloope
