### ISSUE TITLE
app data inside kubernetes

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith#14055]
https://docs.appsmith.com/setup/kubernetes

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100110897

We need to add info on :

Where will the data be saved when we deploy the container to Kubernetes?"

﻿When we deploy appsmith on a aws/eks cluster these are the sequence of steps.
﻿
﻿- we use EFS(like docker volume) to store the 'stacks' directory.
﻿- We create a PV(persistent volume ).
﻿- appsmith-pods/deployment makes a PVC(persistent volume claim)
﻿and there by access the stacks directory to perform all reading/writing operation.
﻿
﻿In the regular deployment(non-aws), the same follows.

**Comment by jnikhila** [comment]
@pranavkanade - Could you please elaborate on this?

**Comment by jnikhila** [comment]
@sumitsum / @sharat87 - Could you please add pointers to the ticket?

**Comment by sum35h** [comment]
@pratapaprasanna  Could you help me with this one.
