### ISSUE TITLE
[Enhancement]: CRUD >> JSON From | Ability to identify Table column datatype & Autoselect JSON form field types accordingly

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#14056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JSON form to Auto Select 'MultiLine input' type for a column with datatype varchar(50) or more to accommodate more text:
<img width="1078" alt="Screenshot 2022-05-20 at 11 59 07 AM (1)" src="https://user-images.githubusercontent.com/91450662/169998348-6ab1fc96-18be-402e-a27b-ddbb70823e1b.png">
<img width="327" alt="Screenshot 2022-05-24 at 2 42 40 PM" src="https://user-images.githubusercontent.com/91450662/169998380-1fb7ddf8-a78f-4144-ad45-f2f8d78a2a4e.png">

### Steps To Reproduce

1. Create CRUD page - for any data source , eg: MySQL used here
2. Identify a table which has text more than 500 chars
3. Observe the JSON form type for this column is Text input
4. **Expected: Check table column type & if its varchar(50) or more, make the default type of JSON form field - 'Multiline input'**
5. Identify a table which has columns that are NOT NULL
6. Observe JSON field for this column
7. **Expected: To make this field required true in JSON Form to comply with the table structure from UI**

### Version

Prod/Release v1.7.1

**Comment by dilippitchika** [comment]
@Aishwarya-U-R  did not understand this line - Expected: To make this column required true to comply with the table structure from UI

**Comment by Aishwarya-U-R** [comment]
@dilippitchika - I mean - if this column is created as NOT NULL in the table, then the corresponding field in JSON form also should be automatically set to Required true - so that user does not run into the Query error on UI while trying to Update the record without the field but is rather already notified of this field being mandatory with red *!
