### ISSUE TITLE
[Bug]-[110]:Table widget - for Default Row Height set as Short - Vertical Alignment working is incorrect

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When in Table widget, I set Default Row Height as Short, and try aligning (using Vertical Alignment property) up, the text aligns down, and vice versa.

### Steps To Reproduce

1. Add Table widget to the canvas.
2. Set Default Row height as Short
3. Now try the Vertical Alignment property. 

When Alignment Up is chosen, the text is aligned down, and when Alignment Down is chosen, the text is aligned up.

<img width="1098" alt="Screenshot 2022-05-24 at 3 14 17 PM" src="https://user-images.githubusercontent.com/101863839/170005598-db35c1d4-7f27-4e5e-8521-300cd541b128.png">

### Version

Production

**Comment by sbalaji1192** [comment]
@btsgh This is not reproducible in Table v2. Could you please verify once and close this issue?

**Comment by btsgh** [comment]
@sbalaji1192  - The original issue is not reproducible. However, the vertical alignment property now does not really move the text in the row up or down.
The movement when any of the vertical alignment is selected is very minimal. Here is the video - https://www.loom.com/share/69ddc4559ab14ed7b9c86cfccae58964

**Comment by sbalaji1192** [comment]
@btsgh Vertical alignment kicks in when there is column wrapping to the next line. In short mode, there is not much room for the text to move up and down. Could you try with a wrapped column ?

**Comment by btsgh** [comment]
@sbalaji1192  - Tried the above and yes it works as expected. Closing this issue.
