### ISSUE TITLE
[Bug]: Ability to desc/describe table in MySQL

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#14054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Simply desc command does not work:**
<img width="540" alt="Screenshot 2022-05-24 at 2 08 41 PM" src="https://user-images.githubusercontent.com/91450662/169991628-ebb2d6d1-a0a3-474f-9de9-546e65f7e476.png">

**It works only if select is appended:**
<img width="1025" alt="Screenshot 2022-05-24 at 2 13 19 PM" src="https://user-images.githubusercontent.com/91450662/169991744-debe11d6-ca71-4528-b495-8edfc2f410e5.png">

### Steps To Reproduce

1. Create a MySQL Datasource
2. **Try to run desc statement on any tables present**
3. Observe the response
4. **Expected: User should be able to see the table structure with** `desc table_name` **or** `describe table_name` **statements**

### Version

Prod/Release v1.7.1

**Comment by rohan-arthur** [comment]
MySQL 6m usage: 215
Apply 25% requirement: 53.5

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 53.5 |
| Effort (months)  | 1 |

**Comment by subrata71** [comment]
### Test Plan

- [TestCase]: Stand-alone `select` query e.g. `SELECT * FROM TABLE` should provide the expected output
- [TestCase]: Stand-alone `show` query e.g. `SHOW DATABASES` or `SHOW TABLES` should provide the expected output
- [TestCase]: Stand-alone `desc` e.g. `DESC TABLE` query should provide the expected output
- [TestCase]: Stand-alone `describe` e.g. `DESCRIBE TABLE` query should provide the expected output
- [TestCase]: Any combination of the above queries separated by semicolons `(;) `should result in expected output too

**Comment by subrata71** [comment]
@ajinkyakulkarni  
I have added the test plan like the [above](https://github.com/appsmithorg/appsmith/issues/14054#issuecomment-1143765667). Am I on the right track? Please advise if it needs any revision.

**Comment by Aishwarya-U-R** [comment]
@subrata71 - Cypress tests for 'select' already exists. Please go ahead with scripts for others. And we dont support more than one statement in query editors today. Is the last case going to be handled as part of this bug fix?

**Comment by subrata71** [comment]
@Aishwarya-U-R 
In fact, we support more than one statement in the query editor. Although it doesn't appear with all the columns in the tabular view as different queries have different sets of columns. If can check the JSON view under the Response tab you will see outputs from every query.

**Comment by yatinappsmith** [comment]
cypress tests are missing

**Comment by yatinappsmith** [comment]
- [ ] [[Testcase] [Bug]: Ability to desc/describe table in MySQL ](https://github.com/appsmithorg/TestSmith/issues/1853)
