### ISSUE TITLE
[Enhancement]: CRUD >> JSON From | AutoGenerated queries to be corrected incase of a TextType Primary column

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#14063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Update query - also trying to set the Primary Column:**
<img width="1071" alt="Screenshot 2022-05-24 at 12 28 50 PM" src="https://user-images.githubusercontent.com/91450662/170029645-91f05392-67fb-4e56-99d7-0c420109862b.png">
**Insert query - inserting Primary column twice:**
<img width="589" alt="Screenshot 2022-05-24 at 3 17 40 PM" src="https://user-images.githubusercontent.com/91450662/170029737-d56c5167-43b7-485b-8e69-fe16197dfe0b.png">

### Steps To Reproduce

1. Create a table with Primary column as text type - example used - Product Line of type varchar(50) & set it Primary Key in DS - MySQL
2. Generate CRUD page from this table
3. **Observe : Insert & Update queries are wrong as mentioned above**
4. Deploying the app without correcting above results in error from View mode
5. User for now can go to the queries & update them accordingly & Deploy mode works fine
6. **Expected: The CRUD generated queries should be rightly created so user need not edit it unless other changes**

### Version

Prod/Release v1.7.1

**Comment by rohan-arthur** [comment]
CRUGgen is deprecated, so closing this issue
