### ISSUE TITLE
[Epic]: Cyclic Dependency Fixes

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#14060]
### Objective

Solve the cyclic dependencies issues at an architectural level so that they don't happen again and provide users a way to resolve them themselves without needing to reach out to the support team.

### Success Metrics

| Metric         |
| -------------- |
| <50 unique errors in a month([report](https://mixpanel.com/project/2032485/view/178891/app/insights#~(columnWidths~(bar~())~displayOptions~(chartType~'line~plotStyle~'standard~analysis~'linear~value~'absolute)~sorting~(bar~(sortBy~'column~colSortAttrs~(~(sortBy~'value~sortOrder~'desc)))~line~(sortBy~'value~sortOrder~'desc~valueField~'averageValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'averageValue)))~table~(sortBy~'column~colSortAttrs~(~(sortBy~'label~sortOrder~'asc)))~insights-metric~(sortBy~'value~sortOrder~'desc~valueField~'totalValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'totalValue)))~pie~(sortBy~'value~sortOrder~'desc~valueField~'totalValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'totalValue))))~timeComparison~null~querySamplingEnabled~false~title~'~sections~(show~(~(dataset~'!mixpanel~value~(name~'CYCLICAL_DEPENDENCY_ERROR~resourceType~'events)~resourceType~'events~profileType~null~search~'~dataGroupId~null~math~'unique~perUserAggregation~null~property~null))~filter~(clauses~(~(dataset~'!mixpanel~value~'!cohorts~resourceType~'events~profileType~null~search~'~dataGroupId~null~filterType~'list~filterOperator~'contains~filterValue~(~(cohort~(id~972685~name~'Non*20Appsmith*20CE~negated~false))~(cohort~(id~839025~name~'Non*20Appsmith*20Cloud~negated~false)))~propertyObjectKey~null))~determiner~'all)~time~(~(dateRangeType~'in*20the*20last~unit~'month~window~(unit~'month~value~12))))~legend~())))        |

### Prioritised User Stories

| User Story    |
| ------------- |
| e.g. as a user, I want to be able to access the platform via mobile phone  |
| e.g as a user, I want to be able to communicate with the other members on the canvas  |

### RACI matrix

| ------------- | ------------- |
| Responsible   |        @ApekshaBhosale @rashmi-rai @ohansFavour @eco-monk @rimildeyjsr @Rishabh-Rathod        |
| Accountable   |        @ApekshaBhosale        |
| Consulted     | @rohan-arthur @ramsaptami |
| Informed      |     @ajinkyakulkarni           |

**Comment by rohan-arthur** [comment]
see conversation here: https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1651575644166099
notion doc here: https://www.notion.so/appsmith/Cyclic-Dependency-Errors-830aad407e194d27804a764caa92e05c
