### ISSUE TITLE
[Bug]-[54]:The edge of the last column gets chipped in table widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the last column (extreme right) of the table widget, if the column is of type URL, then the "visit link"/"new tab" icon is not displayed completely as it gets chipped by the border.
Also noticed if user moves further towards the border, they are not able to click on the link instead the cursor now changes to an "Open hand" which is used to move the widgets in the canvas.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/02f5adc0a4f84240b049234b7297bfca-00001.gif)](https://www.loom.com/share/02f5adc0a4f84240b049234b7297bfca)

### Steps To Reproduce

1. D&D a table widget.
2. Add a custom column and change the `Column Type` to URL in the property pane of the column.
3. In the `Computed Value` add some URL.
4. Now hover over the cells containing the URL.

**Expected:** The "visit link"/"new tab" icon should be displayed in its entirety.
**Actual:** The icon gets chipped and is not completely visible. 

### Version

Cloud

**Comment by dilippitchika** [comment]
Only an issue when url is the last column.

**Comment by dilippitchika** [comment]
Total use of url col - 415
Users not updated the display text - 270
Users who have the url in last col - 20% 


## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 54 |
| Effort (months)  | 0.5 |

**Comment by rahulbarwal** [comment]
@shadabbuchh I am unable to replicate this. Probably got fixed without tagging a PR. 
I am closing this, Please re-open if you still see this.
