### ISSUE TITLE
[Feature] Ability to set style for "Row button" in table 

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#1407]
## Summary

Ability to set different styles (colors) for "Row buttons" in the table widget.

## Motivation

This would be useful to show the buttons intent. For instance an "edit"-button could be green or blue and a "delete"-button could be red.

Blueprints different intents could be used: "primary", "success", "danger" and "warning."

The button widget has this type of function already but only with "primary", "secondary" and "danger" intents.

### Example
![buttons](https://user-images.githubusercontent.com/5412178/97184857-a925d580-179f-11eb-963e-652a6b988fb6.png)

**Comment by Nikhil-Nandagopal** [comment]
@oskarannas thank you for the feature request! We're actively working on this and should be able to ship this early next week! 😃
