### ISSUE TITLE
[Bug]: seeing build error due to old lombok package version

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#14080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Seeing [this](https://stackoverflow.com/questions/66801256/java-lang-illegalaccesserror-class-lombok-javac-apt-lombokprocessor-cannot-acce) error due to old lombok package version. We have updated the version in most of the pom files but few pom files still use the old version. 
Ref: https://theappsmith.slack.com/archives/CPQNLFHTN/p1653413674448529 

### Steps To Reproduce

Follow steps here to build the server app: https://github.com/appsmithorg/appsmith/blob/release/contributions/ServerSetup.md#steps-for-setup 

### Version

self hosted

**Comment by SaumyaBhushan** [comment]
I would like to work on this issue .

**Comment by sumitsum** [comment]
Hi @SaumyaBhushan , thanks for showing interest in the issue. Unfortunately, this issue has already been assigned to someone else. However, we still have some good first issues that have not been assigned to anyone yet. I would highly encourage you to check out [this list](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+no%3Aassignee) once and see if there is any issue that you want to pick up. Happy coding :)

**Comment by SaumyaBhushan** [comment]
Sure, thanks @sumitsum

**Comment by YatinChaubal** [comment]
Closing this issue. Relying on regression and CI
