### ISSUE TITLE
[Feature]: sub-navigation in the navbar Top Side & Left Side Bar. 

### ISSUE THREAD

**Issue by pratikbgit** [appsmithorg/appsmith#14081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I need this feature because if multiple Menu comes and I have to merge few sub-menu into one main menu then its beneficial for us.

Also I would like to change Orange color to Userdefined color.

### Why should this be worked on?

I Grouping of menu manage in a single menu.

**Comment by Nikhil-Nandagopal** [comment]
Hi @pratikbgit , we have this feature tracked here #2282 
could you leave a comment there?
You should now be able to configure the color using our theming option
