### ISSUE TITLE
[Feature]: Being able to insert filepicker uploaded images to Gsheets.

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#14098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need a way to be able to insert images uploaded by filePicker into google sheet. 

### Why should this be worked on?

We currently donot support this.

**Comment by Nikhil-Nandagopal** [comment]
@parth-appsmith did this come as a user request? GSheets is not a good place for file / image information. You should store it in S3 and upload the link of the file to GSheets

**Comment by parth-appsmith** [comment]
@Nikhil-Nandagopal yes this was a user requested feature on [intercom](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/5269111/conversations/164629100113322).

**Comment by Nikhil-Nandagopal** [comment]
@parth-appsmith please let them know that they should use S3 and store the link in. GSheets
