### ISSUE TITLE
[Docs] : [How to guide] | Using Git Flow for different environments

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#14093]
Add documentation for reading environment variables for the datsources - Refer to #7454
 Refer to the[ slack conversation](https://theappsmith.slack.com/archives/C01CFTXD0N8/p1653464991937249).

**Comment by jnikhila** [comment]
@nidhi-nair - Could you please help us unblock this ticket?

**Comment by Pranay105** [comment]
As per my discussion with @AnaghHegde , the work around for this feature only works in some cases. So, it's better to wait for the feature to come out. The estimated time is ~ 2 months.

**Comment by danciaclara** [comment]
@Pranay105 Can we think of documenting this for cases where it works? As the feature is two months away, we can give our users some workaround in the meantime. Also the multiple environments feature will be business edition, so the workaround would continue to be helpful for our community users. @AnaghHegde what's your suggestion. cc: @jnikhila

**Comment by danciaclara** [comment]
https://community.appsmith.com/t/is-there-the-ability-to-switch-between-production-and-develop-datasources/702/2?u=dancia
