### ISSUE TITLE
[Bug] The "storeValue"-function stores widget references as plain text

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#1409]
## Description

When you use the "storeValue"-function and set the value to the data of another widget, plain text gets stored, not the other widgets data.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add a new input widget
1.2 Add the text "my text" to the input field
2. Add a new button widget
3. In the buttons "onClick"-action, select "Store Value"
4. As the "Key", set "testing123"
5. As the "Value"
5.1 Click the lightning icon
5.2 Select "Use data from a Widget"
5.3 Select the input widget created in step 1
6. Click the button
7. Check the browsers dev tools local storage
8. The data set for the "APPSMITH_LOCAL_STORE-*" is `{ "testing123": "{{Input1.text}}" }`, not the expected `{ "testing123": "my text" }`

### Workaround
It is possible to work around this issue by using the JS-option and removing the quotes and curly braces from around the value. Like this `{{ storeValue('testing123', Input1.text) }}`.

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Firefox, Chrome

**Comment by prapullac** [comment]
Verified the issue as the displayed data is {"testing123": "my text" }
