### ISSUE TITLE
[Bug]-[400]:Names given to custom columns do not reflect while referencing unless the page is refreshed.

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user changes the `property name` of a custom column e.g. from `customColumn1` to `Distance`. The new name i.e. `Distance` does not reflect in the app (autocomplete) while binding table.selectedRow.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/80ef0d193dcc47f9a62043ee6dd60c6f-00001.gif)](https://www.loom.com/share/80ef0d193dcc47f9a62043ee6dd60c6f)

### Steps To Reproduce

1. D&D a table & a text widget
2. In the property pane of the table click on `Add a new column`.
3. Change the `Property name` of the custom column from `customColumn1` to `Distance`.
4. Try to bind the Text widget with the table widget using: `{{Table1.selectedRow.Distance}}`.

**Expected:** The binding should take place successfully.
**Actual:** In the autocomplete options user still sees the original name i.e. `customColumn1` instead of `Distance`.

### Version

Cloud

**Comment by dilippitchika** [comment]
@sbalaji1192 have you already looked at this issue?

**Comment by sbalaji1192** [comment]
@dilippitchika Yes. I was not able to repro this on my end. And also it doesn't look like a Table widget issue. More of a autocomplete related issue.

**Comment by Rishabh-Rathod** [comment]
This is table widget issue, please check the data received from widget in unEvalTree 
 
![SCR-20220727-lax](https://user-images.githubusercontent.com/23132741/181218564-325aa922-223c-44c1-8153-8ebb81f40efb.png)
![SCR-20220727-lbd](https://user-images.githubusercontent.com/23132741/181218570-44f53b5d-b58c-43b5-974d-aa92a51cf2fb.png)

Steps to reproduce
1. Add a table widget to canvas
2. Open devtools to check unEvalTree logs and clear all the logs
3. Edit the widget column name and check latest unEvalTree and we can also check canvasWidgetsReducer for widget values.
