### ISSUE TITLE
[Bug]: Multiple 'Error parsing column value' in Console

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#14104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1702" alt="Screenshot 2022-05-25 at 12 13 13 PM" src="https://user-images.githubusercontent.com/91450662/170255106-63eac578-9dcd-4b65-a675-acf01e84e768.png">

### Steps To Reproduce

1. Create new CRUD page using any data source & its associated table
2. Observe : Multiple errors in console as below - in both Edit & Deploy mode as shown above: 
```
SyntaxError: Unexpected token { in JSON at position 1
    at evaluation.worker.5475de0e.worker.js:2 'Error parsing column value: ' '{{data_table.sanitizedTableData.map((currentRow) => ( currentRow.customColumn1))}}'
```
4. Page renders fine though.
5. **Expected: No console errors**

### Version

Prod/Release v1.7.1

**Comment by Rishabh-Rathod** [comment]
A discord user faced this issue https://discord.com/channels/725602949748752515/1024863192935051394

**Comment by Rishabh-Rathod** [comment]
Another discord user faced this issue https://discord.com/channels/725602949748752515/1024628545911279637

**Comment by Rishabh-Rathod** [comment]
@sbalaji1192 Can we please remove the below code to avoid such a console error that confuses our users?

```
console.error(
                e,
                "Error parsing column computedValue: ",
                column.computedValue,
              );
```

**Comment by sbalaji1192** [comment]
@Rishabh-Rathod Could you create an issue for this?

**Comment by Rishabh-Rathod** [comment]
@sbalaji1192 This issue was created for the same, we can close this with the fix.

**Comment by sbalaji1192** [comment]
@Rishabh-Rathod Sounds good!
