### ISSUE TITLE
[Bug] Prettier is not running on commit hook

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1411]
## Description
Seen in #1319 that prettier was not running with the pre commit hook configured

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Make a .ts/tsx file change in the client folder with a formatting mistake
2. Commit this change

#### Observation
Prettier does not fix the formatting

**Comment by logicalahara** [comment]
hey @hetunandu, I'd like to contribute to this bug.

Any pre-requisites ?

### will you please assign this to me?
