### ISSUE TITLE
[Feature]: Datasource image should be bundled

### ISSUE THREAD

**Issue by pkrolkgp** [appsmithorg/appsmith#14118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When running appsmith in docker on premise the svg's for datasource are hardcoded to lad from assets.appsmith.com and thus not displayed

### Steps To Reproduce

Run docker on premise and check datasources

### Version

selfhosted - 1.7

**Comment by riteshkew** [comment]
@pkrolkgp First of all, please accept our sincere apologies for getting to this late. Can you please add more details on the problem statement you are looking to solve for, we might have a workaround for you in store.
