### ISSUE TITLE
[Task]: Data type parsing logic for evaluated values

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#14135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Identify valid data types(primitive)
- Implement logic to map these data types
- Add map of evaluated value data types to action execution request

**Comment by ChandanBalajiBP** [comment]
Few cases considered for typeof
//True cases
// Numbers
typeof 37                === 'number';
typeof 3.14              === 'number';
typeof Math.LN2          === 'number';
typeof Infinity          === 'number';
typeof NaN               === 'number'; // Despite being "Not-A-Number"
typeof Number(1)         === 'number'; // This case is not handled by typeof. so loking for better approach.

// Strings
typeof ""                === 'string';
typeof "bla"             === 'string';
typeof (typeof 1)        === 'string'; // typeof always return a string
typeof String("abc")     === 'string'; // but never use this form!

// Booleans
typeof true              === 'boolean';
typeof false             === 'boolean';
typeof Boolean(true)     === 'boolean'; // but never use this form!

// Undefined
typeof undefined         === 'undefined';
typeof blabla            === 'undefined'; // an undefined variable

// Objects
typeof {a:1}             === 'object';
typeof [1, 2, 4]         === 'object'; // use Array.isArray or Object.prototype.toString.call to differentiate regular objects from arrays
typeof new Date()        === 'object';
typeof new Boolean(true) === 'object'; // this is confusing. Don't use!
typeof new Number(1)     === 'object'; // this is confusing. Don't use!
typeof new String("abc") === 'object';  // this is confusing. Don't use!

// Functions
typeof function(){}      === 'function';
typeof Math.sin          === 'function';

//False cases - typeof returns wrong value for wrapper objects
Example:
const message = new String('This will not work');
typeof message //Return 'object' - but expected output is 'string'
typeof value === 'string' || value instanceof String; //can be resolved using

**Comment by ChandanBalajiBP** [comment]
Have chosen below function to find the datatype
const trueTypeOf = (obj) => Object.prototype.toString.call(obj).slice(8, -1).toLowerCase()

Test cases considered - includes all above and 
trueTypeOf([]); // array
trueTypeOf({}); // object
trueTypeOf(''); // string
trueTypeOf(new Date()); // date
trueTypeOf(1); // number
trueTypeOf(function () {}); // function.
trueTypeOf(/test/i); // regexp
trueTypeOf(true); // boolean
trueTypeOf(null); // null
trueTypeOf(); // undefined

Still looking on how to identify file datatype. As uploaded file can be an object or a string. Will further look into server-side logic for the same in current implementation and handle this case.

**Comment by ChandanBalajiBP** [comment]
Completed this task and committed code to this PR https://github.com/appsmithorg/appsmith/pull/15729

**Comment by nidhi-nair** [comment]
Closed via #16106
