### ISSUE TITLE
[Epic]: Predictable data types during action execution

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#14134]
### Objective

After evaluating a dynamic binding on the client side, today we lose the data type information during the action execution request. This leads to inaccurate assumptions being made during the substitution logic because the best match logic may not necessarily be what the user intended the binding type to be. To overcome this, we should leverage the evaluated type as extra information while finding the best matching data type for any integration.

In this phase of the project, that will span multiple epics, we will be focussing on solving two problems:
1. Any binding that evaluates to `null` or `undefined` must be registered as a null value during execution. Each integration is free to interpret how it understands null values from that point.
2. Any value that can be interpretted as different types must honour the type that the evaluation process identifies.
    - For a binding that evaluates to `"1"`, the substitution type must be string
    - For a binding that evaluates to `1`, the substitution type must be numeric
    - For a binding that evaluates to `"true"`, the substitution type must be string
    - For a binding that evaluates to `true`, the substitution type must be boolean

### Success Metrics

| Metric         |
| -------------- |
| We do not get issues related data type being incorrectly identified |
| We should be able to work on not having to rely on explicit type casting in SQL statements |

### Prioritised User Stories

| User Story    |
| ------------- |
| As a user, I want to be able to send numericals as strings in dynamic bindings |

### Developer Handoff Document in Figma

N/A

### Test Plan

[ ] Create a list of all known data types on Appsmith. Test for different kinds of inputs on REST API for these
[ ] Create a SQL datasource with all data types used in a table. Try to use prepared statements for all combinations of data

### RACI matrix

| ------------- | ------------- |
| Responsible   |    @subrata71  , @ChandanBalajiBP  |
| Accountable   |    @nidhi-nair            |
| Consulted     |  |
| Informed      |      @mohanarpit          |

**Comment by subrata71** [comment]
The goal of this epic is to build the infrastructure for data-type handling on the server side with the help of client-side data type and apply it to one SQL plugin (MySQL) and refactor the common data type handling for the rest of the plugins. Applying the data type handling to MySQL will essentially solve all the known issues related to data type and refactoring the common data type handling will help the rest of the plugins distinguish between 
-"null" string and `null` object
- `{{"098765"}}` and `{{098765}}` // the former will be identified as a string and the latter will be identified as a number

I would like to express my sincere gratitude to the folks for their valuable feedback and guidance throughout this entire journey.
@nidhi-nair 
@ChandanBalajiBP 
@ajinkyakulkarni 
@btsgh 
@rohan-arthur 
@prapullac 
@sumitsum 
@riteshkew 
@sbalaji1192
