### ISSUE TITLE
[Bug]: Apps show error - `The action ... has failed` on page load

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#14141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Multiple appsmith users have complained that they are seeing the error: `The action ... has failed` on page load.

We started seeing the error after the release of v1.7

### Steps To Reproduce

Internal conversation - https://theappsmith.slack.com/archives/CGBPVEJ5C/p1653633651705329

This case is intermittently observed on apps before v1.7

### Version

v1.7

### Test Plan

Cypress

- [ ] [[Test Case] : Execute actions should get called once for every page change](https://github.com/appsmithorg/TestSmith/issues/1740)

Jest

- [ ] [[Test Case] : Testing Init Saga for execution of multiple action calls in a specified sequence](https://github.com/appsmithorg/TestSmith/issues/1739)

**Comment by pranavkanade** [comment]
<img width="506" alt="Screenshot 2022-05-27 at 1 10 12 PM" src="https://user-images.githubusercontent.com/13262095/170653180-d580e677-8c11-4510-b201-12ffa12a7ddb.png">

**Comment by lublak** [comment]
I have the same issue after the update.

**Comment by stevestava** [comment]
Here is the console info for the errors I am getting...

<img width="477" alt="image" src="https://user-images.githubusercontent.com/19496297/171078281-ab7c507b-1e6e-43bf-92b7-9cbc3c139424.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/19496297/171078337-642a56cd-d3cc-4503-839b-9f04cdf636ea.png">
