### ISSUE TITLE
[Research] Appsmith Promise without return statement 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14140]
- Understand why we need `return` statement for promise 
- Is it possible to remove `return` statement need without making any platform change?
- if not what possible, what changes will we need to make to allow promise with a need of `return`

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/14140?planning-poker) with ZenHub @ApekshaBhosale

**Comment by bharath31** [comment]
Notes- https://www.notion.so/appsmith/Thoughts-Why-do-we-need-to-return-Promise-90022dc00e634d96be608f5346864134
