### ISSUE TITLE
[Bug]: After a widget is pasted on a new page, it does not get displayed on the canvas

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user copies a widget and pastes it in a new page using `Ctrl+V`, although the widget name gets displayed in the explorer section, but the widget does not get displayed in the canvas unless the user clicks on the widget name.

https://user-images.githubusercontent.com/39921438/170925412-147212f1-1348-4a14-a865-3ea4504993be.mov

### Steps To Reproduce

1. On Page 1 (default page), d&d some widgets on the canvas.
2. Copy any of the widget from that page.
3. Create a new page and paste the widget.

**Expected:** The widget should get displayed on the canvas of the new page by default.
**Actual:** Although the widget name gets displayed in the explorer section, but the widget does not get displayed in the canvas unless the user clicks on the widget name.

### Version

Cloud

**Comment by rohitagarwal88** [comment]
@rahulramesha : Please triage this issue

**Comment by Sripriya93** [comment]
Having issue with Modal widget copy pasting in the same page, which affects the copy pasting in page 2, creating a separate issue and moving this Bug (#14157) to done as discussed. Other widgets are working fine.
