### ISSUE TITLE
[Epic]: App theming stability 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#14159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Creating this to track issues in app theming stability. 
These are small changes which -
1. Cannot wait until widget reskinning
2. Are problems with theming experience
3. Bugs which need to be fixed

**Comment by dilippitchika** [comment]
Issues - 
- https://github.com/appsmithorg/appsmith/issues/13992
- https://github.com/appsmithorg/appsmith/issues/14106
- https://github.com/appsmithorg/appsmith/issues/14143
- https://github.com/appsmithorg/appsmith/issues/13931
- https://github.com/appsmithorg/appsmith/issues/13617
- https://github.com/appsmithorg/appsmith/issues/13854
- https://github.com/appsmithorg/appsmith/issues/13720
- https://github.com/appsmithorg/appsmith/issues/13629
- https://github.com/appsmithorg/appsmith/issues/13626
- https://github.com/appsmithorg/appsmith/issues/13596

**Comment by dilippitchika** [comment]
Let's plan these issues out once and start understanding the priority and effort. 

cc - @somangshu

**Comment by dilippitchika** [comment]
Action items for this week 6/6/22- 
1. https://github.com/appsmithorg/appsmith/issues/14106 - @jsartisan 
2. https://github.com/appsmithorg/appsmith/issues/14143 - @jsartisan 
3. https://github.com/appsmithorg/appsmith/issues/14220 - @keyurparalkar 
4. Exporting app saved themes are not showing up - @jsartisan to discuss with @nayan-rafiq 
5. Change the theme font and deploy the app, then open the app again using edit button in deploy mode, observe the appsmith font changes to the theme font - @keyurparalkar to check


https://github.com/appsmithorg/appsmith/issues/13617 -- Someone has to check again

**Comment by jsartisan** [comment]
Closing the epic :D
