### ISSUE TITLE
[Feature]: Ability to set the working branch for Git connected apps

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#14175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For Git-connected apps, people want to set a working branch at the application level so their dev team land on this branch when they open the editor.

### Why should this be worked on?

When people have the same app synced to multiple environments using our git sync, they want to encourage their teams to work on the environment branch by default at the app-level and not mess with app on the `main` or production branch. The _default_ branch doesn't solve this problem for them today.

Github defines a _default_ branch as 
> The base branch for pull requests and code commits

Refer [changing the default branch](https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch) on Github's docs. Also, changing the _default_ branch is a hosting provider concept and not a `git` concept.

We can make this easier by letting people set a working branch for the apps on our UI.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_avyrw)

**Comment by AnaghHegde** [comment]
@vuiets This requires a native integration with git hosting providers. So it won't be possible to achieve it in Appsmith UI with current implementation.

**Comment by abhvsn** [comment]
We have received 2 requests for this in the current week, just wanted to log here. The main reason was default branch got messed up and some other child branch had the latest changes.

**Comment by vuiets** [comment]
Updated this to to reflect the right idea. Please take a look.

+2 for this. Heard two more _Business_ edition users request for this.

**Comment by AnaghHegde** [comment]
One more request from the discord user - https://discord.com/channels/725602949748752515/760761686549463060/999239999084040273
<img width="883" alt="image" src="https://user-images.githubusercontent.com/12005551/179987970-4e2689f6-062a-4e09-ae32-3f66f0c36cfc.png">

**Comment by IAmAnubhavSaini** [comment]
Please move it to git V2

**Comment by vuiets** [comment]
There have been multiple requests around this so we might pick this up before that @IAmAnubhavSaini. Almost every single _Business_ edition user has requested for this. But we have to design for it. So will a sprint or two before it comes up.

**Comment by vuiets** [comment]
@Nikhil-Nandagopal had a great idea to look at this as the deployment branch and consider it in tandem with [#11522 | Automated Deployments](https://github.com/appsmithorg/appsmith/issues/11522)

**Comment by developer-honoru** [comment]
i need this function

**Comment by vuiets** [comment]
Hey @developer-honoru this is on our radar and I was wondering if I could talk to you and get your use case down in detail so we factor it in when we build it out. If you are keen on talking to us, could you pick a time that works best for you on my calendar? Here's the link to it :) - 📆 https://calendly.com/appsmith-vishak/conversations

**Comment by vuiets** [comment]
We had another request for this from a prospect yesterday, they had a single app synced across staging, demo and production instances using git. The apps on the instances default to main branch always, instead they wanted it default to the environment branch here. They have a small dev team of about 9 doing a hundred different things and they automate things to stay agile. This hindrance was slowing down their internal tool building pace.

**Comment by IAmAnubhavSaini** [comment]
Not only that we might need to provide a functionality to hide specific branches in different environments/instances.

In the example above, it wouldn't make sense to let prod-branch be accessible in demo instance.

**Comment by developer-honoru** [comment]
@vuiets I'm not familiar with English, so meeting can be difficult. If you can speak Korean or Japanese, you can.

**Comment by developer-honoru** [comment]
@vuiets  It would be good to refer to this
https://docs.retool.com/docs/git-syncing

**Comment by developer-honoru** [comment]
You can talk by email. For your information, we are curren
![image](https://user-images.githubusercontent.com/33475816/192922277-29f77d29-7a98-4686-8955-8e545fcf5138.png)
tly exchanging emails with the Appsmith team.

**Comment by developer-honoru** [comment]
https://discord.com/channels/725602949748752515/1016955840437174273/1016955843889074236

**Comment by vuiets** [comment]
Ah thanks @developer-honoru, will get in touch with you vai email :)

**Comment by infinitetrooper** [comment]
Released as part of Default Branch config in Appsmith Enterprise v1.9.47
