### ISSUE TITLE
[Bug]: UI issues once select family widgets are resized

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`MultiTreeSelect` widget:

1. When the user resizes the widget to the minimum limit, the dropdown arrow overlaps with the text present. 
2. Also if there are multiple options selected, e.g. 4 options are selected and the user resizes the widget, when they reach the minimum limit, the text changes to `+ 3 more`.

https://user-images.githubusercontent.com/39921438/170967666-0c18f8d7-b6b2-4b68-b529-fd7a6c741667.mov

All select widgets in general:

- Once the widgets are resized to the min limit, the border intersects the widget, which does not look good from a UI perspective. Can/should this be fixed?

https://user-images.githubusercontent.com/39921438/170968665-67cb35cf-07ba-4c17-be65-5a50b64580e4.mov

### Steps To Reproduce

1. D&D any select family widget.
2. Resize the widget to the minimum possible limit.

### Version

Cloud

**Comment by dilippitchika** [comment]
Widgets should have defined min widths ideally below which they cannot be resized.
