### ISSUE TITLE
[Docs] Youtube Video needs improvement

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1417]
## Documentation Link 

https://www.youtube.com/watch?v=mzqK0QIZRLs

## Describe the problem

The video is a little too fast paced and does not communicate the flow of why we're querying data and how that query is being connected to the table very well. It also needs to emphasize on the fact that you can write ANY JS inside the {{ }}

**Comment by Nikhil-Nandagopal** [comment]
@valerianpereira thank you for your interest in contributing to appsmith. This issue is currently not up for grabs and is being worked on by the team! Here are a list of good first issues if you'd like to contribute
https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22

**Comment by Rishabhkaul** [comment]
@cokoghenun Do you think its time to re-do this video? Given that it gets so many hits and might be outdated. cc @Nikhil-Nandagopal

**Comment by cokoghenun** [comment]
Sure, taken note of this and will start working on it

**Comment by jnikhila** [comment]
@megaconfidence - I assume this is already added to your pipeline. Closing this issue.
