### ISSUE TITLE
[Docs]: Note that multi-user editing is possible with Git-Sync

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#14183]
Our docs (FAQ) currently state that multi-user editing is not possible, however with Git Sync, users can work on multiple branches of an app simultaneously.

https://docs.appsmith.com/faq#does-appsmith-support-multi-user-editing

**Comment by jnikhila** [comment]
@vihar - Could you please add a coomunity post for this? CC: @pranavkanade

**Comment by jnikhila** [comment]
@pranavkanade - could you please review and close the ticket?

**Comment by jnikhila** [comment]
@AnaghHegde - Could you please review and close the ticket?

**Comment by AnaghHegde** [comment]
Looks good to me
