### ISSUE TITLE
[Bug]-[12000]:appsmith.URL is not updating when using navigateTo in Edit mode

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Loom recording to demo issue - https://www.loom.com/embed/f16a5ed2f60646ff996716e6d5062972

### Steps To Reproduce

1. Create 2 pages.
2. Go to `Page2` and add a button to navigate to `Page1` in edit mode
3. Click on the button and check the URL and `appsmith.URL` value

### Public Sample App

https://app.appsmith.com/app/resetwidget/navigate-to-issue-6294e2abb4c51656bfeb3df5/edit

### Version

1.7.0

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 1 |

**Comment by Rishabh-Rathod** [comment]
@kocharrahul7 
how did we measure reach for this issue? 
If we considered `appsmith.URL` usage then just to clarify even to URL visible in the browser is incorrect after navigateTo in view mode as shown in the loom recording. 
I believe it will have less effort ( maybe 1-2 week ) and more reach ( users using `navigateTo` )

**Comment by kocharrahul7** [comment]
@Rishabh-Rathod  Oh, that's true, I didn't consider the URL not getting updated. And thanks for the heads-up on the effort. Updated the comment

**Comment by Nikhil-Nandagopal** [comment]
@Rishabh-Rathod would this have broken existing apps?

**Comment by Richarex** [comment]
This issue is resolved now URL is updating when navigateTo is used in edit mode.

https://user-images.githubusercontent.com/93259714/181751925-dba62fae-db3d-46cf-9a4f-b8d62a53143e.mp4
