### ISSUE TITLE
[Bug]-[2752]:Public apps asking for login after moved to self hosted

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#14182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user moves a public app from cloud to self hosted instance, the app permission is getting changed. It is asking for login.

It starts working if you
1. Turn off public sharing
2. Reload the page
3. Turn it on again

### Steps To Reproduce

1. Create an app and make it public.
2. Move the app to self hosted instance.
3. Check the public app

### Version

Self Hosted - 1.6.26

**Comment by vuiets** [comment]
@albinAppsmith @Nikhil-Nandagopal from a security standpoint isn't making an imported app private by default good thing to do?

I think this behaviour sits well especially when people move apps across environments. We can keep it private by default to keep it secure and people can share it again in public when they see it fit?

So what I suggest is we keep apps private by default on import. What are your thoughts?

**Comment by Nikhil-Nandagopal** [comment]
@vuiets that is a good point. A user might not realize that their app is public if they forked it from a template. But I think the problem here is that it shows it is public in the settings when it is not.

**Comment by harishkotra** [comment]
> @vuiets that is a good point. A user might not realize that their app is public if they forked it from a template. But I think the problem here is that it shows it is public in the settings when it is not.

That's right. Public is enabled post import in a different environment. I agree with keeping imported apps private but currently as a user there is no message or a notification about this behaviour. Enabling and Disabling the toggle is a hack but a note during export or import educating the users will help.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 344 |
| Effort (months)  | 0.25 |

**Comment by hiteshjoshi** [comment]
@RakshaKShetty this needs to be tested during RBAC testing.

**Comment by RakshaKShetty** [comment]
@hiteshjoshi i could still repro the issue so reopening the issue ![image.png](https://ima![image.png](https://images.zenhubusercontent.com/60a213f9a1e4f1bd65b83f42/708b0096-02e5-4eeb-8c78-9b266d5f24d7)ges.zenhubusercontent.com/60a213f9a1e4f1bd65b83f42/aac7319d-2822-4719-b844-57daf31da38a)

**Comment by hiteshjoshi** [comment]
@RakshaKShetty  to re-test with RBAC
