### ISSUE TITLE
[Docs] Image does not expand in docs

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1418]
## Documentation Link 

https://docs.appsmith.com/widget-reference/table

The image does not expand on clicking

**Comment by dowenrei** [comment]
I'll take that!

**Comment by Nikhil-Nandagopal** [comment]
@dowenrei go for it!

**Comment by dowenrei** [comment]
Upon checking, I realised that the Table.gif file size is small (504kb) as compared to other gifs which have file size of Mb. Is it okay to upload a completely new gif showing the same functionality?

**Comment by Nikhil-Nandagopal** [comment]
Yes please go ahead
