### ISSUE TITLE
[Bug]: Switch group widget - Inline property not working

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I drop a switch group widget on the canvas, it is seen that the inline property of the widget does not work, though the Inline property is enabled by default. The switch group options remain one below the other with the inline enabled, even though they are supposed to be next to each other.

### Steps To Reproduce

1. Drop the switch group widget on to the canvas
2. Note that the Inline property is enabled by default, but still the options are one below the other. 

This is broken in release. Works fine in Production.

Also tested an older application which had a Switch Group Widget, and found that the older application also was impacted by this bug. 
<img width="1300" alt="swgrpinline2" src="https://user-images.githubusercontent.com/101863839/171022312-9f0b5780-237b-481d-9c75-8d32a921860d.png">
<img width="1310" alt="swgrpinline1" src="https://user-images.githubusercontent.com/101863839/171022325-ee71d236-9bb9-45aa-9dd7-3ed4b377766d.png">

### Version

Release

**Comment by shadabbuchh** [comment]
This issue has been tested in Release and is working as expected.

https://images.zenhubusercontent.com/275993885/88e0604f-1993-48f5-8606-c0f4a088393b/screen_recording_2022_06_01_at_11_07_54_am.mov
