### ISSUE TITLE
[Bug]: Multiselect widget on reset doesn't fallback to default values.

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#14198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a multiselect widget is reset either individually or inside a form (enabling reset on submit success), the `selectedOptionValues` is resetting to `[]` (empty array) rather than to the default value.

### Steps To Reproduce

1. Drag a multiselect widget
2. Drag a Text widget and set the `Text` property to `Multiselect1.selectedOptionValues`
3. Drag a button and set the `onClick` property to reset the multiselect widget.
4. Select the value `Blue` in the multiselect.
5. Press the button to reset the widget
6. Notice the Text widget displays the  `Multiselect1.selectedOptionValues` as `[]` instead of `["GREEN", "RED"]`.

### Version

Cloud

**Comment by ashit-rath** [comment]
@Aishwarya-U-R Ideally the output should contain "Dark Blue" and "Light Blue" as well. Can you create a separate issue for this?

@dilippitchika @souma-ghosh Something we should take care in the Select family epic?

**Comment by dilippitchika** [comment]
@Aishwarya-U-R what is the mode selected? I can't see it from your screenshot. If you have selected display all items then it works as expected. 
<img width="1035" alt="Screenshot 2022-06-16 at 10 46 46 AM" src="https://user-images.githubusercontent.com/19730984/173996613-a94fd85a-7dcd-4555-9ba9-720046d4388d.png">

**Comment by Aishwarya-U-R** [comment]
@dilippitchika - Yes, I also have the mode set to "Display all items".
And the question here is : If 'BLUE' which has some child items is set as fallback "Default Value" then resetting the widget - should contain child items also when `{{MultiTreeSelect1.selectedOptionValues}}` is used somewhere or not?

In above image you can see that when `{{MultiTreeSelect1.selectedOptionValues}}` displayed in Text widget - only BLUE is displayed & not DARK BLUE & LIGHT BLUE (while they are still selected in MultiTreeSelect)
