### ISSUE TITLE
[Bug]: Cyclic dependency error

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#14202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below is link to the app where the cyclic dependency is observed. 

### Steps To Reproduce

Open the app from the below link in edit mode and observe the cyclic dependency error shown. 
https://www.loom.com/share/b03f9f060cfb4715948b9cb109f59434

### Public Sample App

http://ec2-13-235-78-161.ap-south-1.compute.amazonaws.com/app/arteviva/login-6295afd8bf665a0a95913098/edit?branch=master

### Version

Latest from release branch

**Comment by Rishabh-Rathod** [comment]
I noticed that the `actions` field for all the JS objects was an empty array, though the JSObject `body` had functions.

Slack thread - https://theappsmith.slack.com/archives/C02KTH6EHUG/p1653999029583849

**Comment by nidhi-nair** [comment]
Unassigning myself till we have more information around reproducing this issue.

**Comment by Nikhil-Nandagopal** [comment]
Closing this if we don't have information
