### ISSUE TITLE
[Enhancement] Widget Name does not feel editable

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1420]
Make widget name and app name feel editable.

**Comment by Debsourabh** [comment]
https://www.figma.com/file/fKGoWuZKBYmN94KHn74OE8/Widget-Renaming?node-id=0%3A1

Here is the design file for the same.

Flow:

1. Hover over the name
2. Underline appears under the name deeming it editable
3. Click to select the text
4. Rename text
5. Name is updated successfully.

**Comment by marks0351** [comment]
The enhancement looks to have been implemented already. @Debsourabh can u pls confirm?

**Comment by Nikhil-Nandagopal** [comment]
This can be closed
