### ISSUE TITLE
[Bug]-[4400]:Sending credentials as body or header option is not provided in Authenticated API

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#14218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In OAuth2.0 authentication there is no option to send the authentication parameters as header or body
<img width="2551" alt="Screenshot 2022-06-01 at 12 36 18 PM" src="https://user-images.githubusercontent.com/104058110/171347541-374f82dc-22de-44ab-b6ff-f457ee744556.png">

![image](https://user-images.githubusercontent.com/104058110/171345901-3ef6fe95-c244-4953-98cf-36c4a3ddb54d.png)
Adding postman screenshot for reference
<img width="2560" alt="Screenshot 2022-06-01 at 12 28 40 PM" src="https://user-images.githubusercontent.com/104058110/171355232-2de024bb-899f-4aa1-ad88-633e68e48ad0.png">

### Steps To Reproduce

1. Create a new Authenticated API in Datasource page.

### Version

Cloud

**Comment by rohan-arthur** [comment]
REST 6m usage: 4400
assume 5% requirement: 220

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 220 |
| Effort (months)  | <<number>> |

**Comment by prapullac** [comment]
Please find the test cases [here ](https://github.com/appsmithorg/TestSmith/issues/1894)

**Comment by deanmas** [comment]
hi @ChandanBalajiBP , this is still not working. I can select "Send as Basic Auth headers" and save but authentication is still failing. Works fine in Postman
