### ISSUE TITLE
[Bug]-[10000]:async tag not assigned in absence of null checks

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#14229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Missing null checks in Js objects result in async tag not getting assigned to a function.

This is because, we do a dry run of the method and it throws `Cannot read properties of undefined`.
Before the execution reaches the async part of the code.

### Steps To Reproduce

```
export default {
	myVar: [],
	myVar2: {},
	myFun1: () => {  
		//this.myVar[0].id;
		//this.myVar2.data.id;
		return Api1.run()
	},
}
```

- Uncomment the lines in myFun1 and notice the async tag is not assigned anymore. (Even if Api1.run() is async)

- When null checks are added the tag will be assigned properly.
```
this.myVar[0]?.id;
this.myVar2.data?.id;
```

https://www.loom.com/share/459c8b3ad1f14f73a712fcaf1bedf77a

### Possible Solution
Check - https://github.com/appsmithorg/appsmith/issues/14618#issue-1274629024

### Version

Cloud - Appsmith v1.6.26-SNAPSHOT

**Comment by rohan-arthur** [comment]
6m usage of js object: 2500
consider 50% of users run into this, 1250

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1250 |
| Effort (months)  | <<number>> |

**Comment by ayushpahwa** [comment]
6m usage of js object: 2500
consider 50% of users run into this, 1250

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1250 |
| Effort (months)  | 0.25 |

**Comment by ApekshaBhosale** [comment]
same as https://github.com/appsmithorg/appsmith/issues/14229
