### ISSUE TITLE
[Docs]: How to increase Filepicker upload size on self-hosted?

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#14232]
In their self-hosted instances of Appsmith, users would like to upload files 50MB - 100MB+. To allow this, they should set `APPSMITH_CODEC_SIZE` to 50, 100, etc. in their docker.env file.

We should also include the related error message to increase discoverability in the docs.

A user is experiencing an error at the moment even after setting the `APPSMITH_CODEC_SIZE` var, unsure whether this is a bug.

* See Slack thread [here](https://theappsmith.slack.com/archives/C0341RERY4R/p1654060634582969)

* See Discord thread [https://discord.com/channels/725602949748752515/760761686549463060/966724066117566524](here)

**Comment by spark-c** [comment]
Platform currently can't handle files larger than 100MB, moved to Icebox while internal issues are resolved

**Comment by danciaclara** [comment]
@harshilp24 can you check with the App viewers pod if this has been fixed and ready to be documented

**Comment by danciaclara** [comment]
@harshilp24 can you check about whether this is ready to be documented
