### ISSUE TITLE
[Feature]: When field is hidden in a json form allow user to set if they want to use source data as fallback

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#14231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a new switch for dev to configure when visible is set to off, to use the source data in form data rather than user having to write JS code for this.

### Why should this be worked on?

When i hide a field in json form, i want to access it's value from the source data so that my update query doesn't remove the fields altogether

**Comment by kittiu** [comment]
+1, also get the same problem.
