### ISSUE TITLE
[Docs]: How to configure up Gmail email provider for Appsmith instance

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#14235]
Users would like to know about having the Appsmith server use the Gmail SMTP server to send emails

See post [here](https://community.appsmith.com/t/how-do-i-configure-gmail-smtp-with-appsmith/52) for reference and starting point

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/getting-started/setup/instance-configuration/email/gmail).
