### ISSUE TITLE
[Bug]: Appsmith crash when create an API pointing to Github hosted json

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We saw an issue where Appsmith crashed for users when they created an API with URL as  https://raw.githubusercontent.com/dmfilipenko/timezones.json/master/timezones.json and hit run to it.

### Steps To Reproduce

1. Create a new API
2. URL = https://raw.githubusercontent.com/dmfilipenko/timezones.json/master/timezones.json and hit run to it

### Public Sample App

https://release.app.appsmith.com/app/dynamically-change-input-text/page1-62729b10bf58a33d4ce4cedb/edit

### Version

1.7.1

**Comment by yatinappsmith** [comment]
- [ ]  [1755 [Testcase]: [Bug]: Appsmith crash when create an API pointing to Github hosted json](https://github.com/appsmithorg/TestSmith/issues/1755)

**Comment by SamGallagherForte** [comment]
I believe I am seeing this same issue for a custom API I am integrating with. When executing, or now even when just browsing to the query page, I see the error "Oops! Something went wrong". My API is returning JSON data.

**Comment by yatinappsmith** [comment]
The issue still exists https://www.loom.com/share/6041f202ba5848a7a4715da0f0bb8a6c

**Comment by ChandanBalajiBP** [comment]
@yatinappsmith Its working fine for me. Can you try once again. If repeated can you share your app with me so that i can debug.
<img width="2171" alt="Screenshot 2022-06-09 at 2 17 04 PM" src="https://user-images.githubusercontent.com/104058110/172805616-bf5dfe17-a815-45c5-b626-f8d1061214bb.png">

**Comment by ChandanBalajiBP** [comment]
Image was not built at that point of time. Now it's working in release also. Closing this issue.
