### ISSUE TITLE
[Bug]: Badly tagged image

### ISSUE THREAD

**Issue by merqurio** [appsmithorg/appsmith#14243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When upgrading the application I saw that the [v.1.6.25](https://github.com/appsmithorg/appsmith/releases/tag/v.1.6.25) is badly tagged. It should be v1.6.25. There is an extra dot between the `v` and the `1`.

### Steps To Reproduce

1. Go to Releases
2. Check the release format and compare to other release patterns
3. Go to Docker Hub
4. Check the release format and compare to other release patterns

### Version

Self Hosted v1.6.25

**Comment by Nikhil-Nandagopal** [comment]
@merqurio thanks for reporting this! You can update to a newer version of our release directly while we fix this
