### ISSUE TITLE
[Enhancement]: Increase Max file size on the Filepicker widget 

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#14248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today there is a 100MB limit on max file size on the Filepicker widget. We need to consider increasing this limit.

### Why should this be worked on?

Video files could usually exceed this limit. 
Was also asked by a user - https://community.appsmith.com/t/filepicker-file-size-limit/1023/3

**Comment by ajinkyakulkarni** [comment]
FYI - It appears that the max file upload size is hardcoded to 100 in `app/client/src/widgets/FilepickerWidget/widget/index.tsx`
<img width="959" alt="image" src="https://user-images.githubusercontent.com/800578/172103690-68577d7a-df24-42fd-ab80-f991216e13bb.png">

If we increase this, we have to also update the corresponding `client_max_body_size` for nginx.

**Comment by ajinkyakulkarni** [comment]
More discussions 
https://theappsmith.slack.com/archives/C0341RERY4R/p1654060634582969

https://theappsmith.slack.com/archives/C02KTH6EHUG/p1654426767271499

**Comment by colin-precisionos** [comment]
I also need to increase this limit - any news on this?

**Comment by Nikhil-Nandagopal** [comment]
@colin-precisionos we recently increased this limit and it should work on our self hosted instances. Could you tell us a bit about the application you are building and the challenge you are facing with it?

**Comment by colin-precisionos** [comment]
I need a front end to allow users to load media like videos, dicom series, pptx with videos (some times up to 500MB), into our strapi headless CMS.  Are there instructions to increase this number on my self hosted instance?

Thanks,
Colin

**Comment by Nikhil-Nandagopal** [comment]
@colin-precisionos Unfortunately we don't support uploading files larger than 200mb at this time. We'll look into how we can improve this.

**Comment by colin-precisionos** [comment]
My instance, Appsmith v1.9.43, is still has the 100MB - how do I move it to 200MB?
[cid:dc628531-eeb1-43ae-b797-ffd96577cb02]

________________________________

**Comment by colin-precisionos** [comment]
Can I get some feedback on this please?

________________________________

**Comment by Nikhil-Nandagopal** [comment]
@colin-precisionos can you try file upload using the fetch API directly? 
https://docs.appsmith.com/write-code/reference/Fetch-API

This should bypass the limit

**Comment by colin-precisionos** [comment]
The FilePicker provides the GUI to select the file - this has the 100MB limit.  The suggestion below doesn't help with this limit.
I've been told it's now a 200MB limit, but I still see the FilePicker with 100MB limit in the latest version.  Are there settings I need to configure?
Thanks,
Colin


[cid:d43ba1af-28b5-431f-9135-07ee0ccc49a5]
________________________________

**Comment by Nikhil-Nandagopal** [comment]
@colin-precisionos we're pushing out a fix to increase the filepicker to 200mb. It will be available in the next weeks release

**Comment by colin-precisionos** [comment]
Ok - thank you.
________________________________

**Comment by colin-precisionos** [comment]
Hello,

I still can't set a file select size greater than 100Mb, despite your team saying it should have been in the build weeks ago.

We are on version 1.9.58

Please advise.
Thanks,
Colin

***@***.***

***@***.***
