### ISSUE TITLE
[Bug ]: Issues related to Google UQI

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#14244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below are the list of issues is
Enhancement:
1. Highlight in red when the mapping with the field is wrong 
2. Highlight in red when JS Syntax is wrong 
3. Indicate the mandatory field
4. Highlight in red when the mapping with field is wrong 
5. Highlight in red when JS Syntax is wrong 
6. Filter to be left-aligned:  If possible we can remove "Where" as well as we are displaying the condition as a separate field
7. Sort by field can have a drop-down 
8. If possible display load time and size of Data
9. the search bar is not consistent
10. When the sheet is deleted the user must be displayed with an error message on the queries using the sheet 
11. On "Read Only" permission the user must not display with CRUD option or on Trying to click on Generate page option an toast message must be displayed to user 
12. 

### Steps To Reproduce

- [x] 1. When the user changes the name of the spreadsheet and the sheet name remains as previous it is observed that the results are still fetched from the sheet name and not from the spreadsheet. 

expectation: when the spreadsheet is changed we can clear other fields 
- [x] 2. On converting the spreadsheet field into JS it is observed that the URL does not get updated based on the name change pulled from the dropdown 
- [x] 3. Selecting Entity as Sheetrows in Fetch details is not functional
- [x] 4. Indicate the mandatory field 
- [x] 5. Scroller is displayed to the user when the relationship pane is displayed to the user 
- [x] 6. Scroller is displayed in the dropdown of the filter by field commands 
- [x] 7. Uncaught promise exception https://www.loom.com/share/b64819cd914e4157a62707783fe64a7a
- [x] 8.  Does not work on a page that has decimal and multiple data types
- [x] 9. Crud/Table  does not get populated with different data types https://www.loom.com/share/36a4e4c973304ad49ae1a1483d44c224
- [x] 10. Negative number should not be supported in table heading row 
- [x] 11. Unable to import Apps.
- [x] 12. CRUD : Insert and Update functionality is broken  
- [x] 13. Filter by and Sort By : On converting from the JS to regular field the field does not get updated based on the values written in the JS and vice versa (https://www.loom.com/share/c26b4f938b924b71b876b014bc58403e)
- [ ] #14600 
- [x] When user try to navigate to query params from entity section in property pane the query pane is displayed plan 
 https://www.loom.com/share/5a0046bd40d84daaba6238ddcbc8e749

### Version

Cloud

**Comment by nidhi-nair** [comment]
> Highlight in red when the mapping with the field is wrong

We'll need validations to be able to achieve this. Deferring this feedback to when we pick that project up.

**Comment by nidhi-nair** [comment]
> Uncaught promise exception
This one's happening because the table widget converts the `/` (forward slash) character in the heading in the Google Sheet into the `_` (underscore) character. Using an unknown field in the where clause is throwing an ugly error though. Tracking that part of the issue [here](https://github.com/appsmithorg/appsmith/issues/14312).

**Comment by nidhi-nair** [comment]
> On converting the spreadsheet field into JS it is observed that the URL does not get updated based on the name change pulled from the dropdown

It is expected that the JS mode retains its previous value. The conversion should only happen on the first switch, and that seems to work as expected.

**Comment by nidhi-nair** [comment]
> Scroller is displayed in the dropdown of the filter by field commands 

I've added a few more operators on this since, so we don't need to worry about this issue any more.
