### ISSUE TITLE
[Bug]: Incorrect home page is displayed when user changes home page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Incorrect home page is displayed when user changes home page on page properties and then navigates back to the app from organization page after change, i.e. previous home page is retained as loading page even after home page has been changed. Refreshing sets the correct home page.

### Steps To Reproduce

1. Change `home page` on an app from page properties that contains multiple pages
2. Navigate to the home page and re-launch the app
3. Observe that app loads with the previous home page instead of recently changed home page

https://www.loom.com/share/82556779edb84ba2bbeede203b180da0contain

### Version

Cloud

**Comment by kocharrahul7** [comment]
Can no longer reproduce
