### ISSUE TITLE
[Bug]: Binding parameters is not supported for simple statement error in MySQL

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#14250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Intro
The LIKE operator is used in a WHERE clause to search for a specified pattern in a column.

The wildcard percent sign (%) represents zero, one, or multiple characters

### Doesn't work with mustache binding with Prepared Statement on
This works as expected in Appsmith when using Prepared Statement without % enclosed. While using Prepared Statement enclosing the parameter with %, the "`Binding parameters is not supported for simple statement`" error is returned from the server. 

<img width="1122" alt="Binding Parameters exception with PS on" src="https://user-images.githubusercontent.com/3524599/171640620-b32d3a4a-bc51-436d-a247-2e3798763dce.png">

### Works with mustache binding with Prepared Statement off

<img width="1136" alt="PS off" src="https://user-images.githubusercontent.com/3524599/171641393-f1c14070-c0de-4940-94a9-a8c02266985c.png">

### But works with mustache binding with Prepared Statement on if and only if
If the value provided from the input widget has percent (%) sign enclosed then it works as expected.

<img width="1502" alt="Current workaround" src="https://user-images.githubusercontent.com/3524599/171644856-c21a4fdb-4a4d-4e73-bb45-dd3bf6ec1761.png">

### Demonstration
[Loom Video](https://www.loom.com/share/a6133c11ee754115b9f691e1407b0b31)

### Steps To Reproduce

1. Configure a MySQL datasource
2. Go to the Query editor
3. Create an input widget and type some value in there which you are going to match by the following query 
4. Write a query like `SELECT * FROM YOUR_TABLE WHERE SOME_COLUMN LIKE '%{{InputWidget.text}}%'`
5. You should see an error message like "`Binding parameters is not supported for simple statement`"

### Version

Cloud - v1.7.0

**Comment by Nikhil-Nandagopal** [comment]
@subrata71 I believe for prepared statements, the entire value must be passed and only a part of the value should not be so 
%{{}}% won't work but {{ "%" + "%" }} will work. Thus this is expected
