### ISSUE TITLE
[Feature]: In view mode clicking on comment again should deselect it and move back to view mode

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#14264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When in commenting is enabled, clicking on the comment button again should take us back to view mode.

### Why should this be worked on?

User requests 
- When i am in the comment mode, I am unable to exit it anymore

People think this is a bug because they are trying the obvious part where clicking on the same thing that got them into it will get them out as well, however it works on escape only today.

**Comment by vuiets** [comment]
Hey, we're sunsetting commenting as a feature soon since the usage hasn't lived up. You can follow https://github.com/appsmithorg/appsmith/issues/14173 for updates around this.

**Comment by dilippitchika** [comment]
Ok @vuiets i will close this then, thanks for the update
