### ISSUE TITLE
[Feature]: Snowflake plugin: use connection pool

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#14269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currenlty the Snowflake plugin does not use connection pool, but relies on single JDBC based connections. We can use a connection pool like in Postgres plugin so that our plugin connection can become thread safe and we can also re-use connections instead of creating a new one each time.

### Why should this be worked on?

* To make sure that our plugin is thread safe. 
* To make sure that we don't end up creating too many connections to the DB.

**Comment by PiyushPushkar02** [comment]
Re-tested the same in my local.
Moving this to Needs QA
