### ISSUE TITLE
[Bug]: widget's name is not getting focused on adding new widget

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#14265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When adding a new widget, its name is not getting focused if we are doing a reflow.

https://www.loom.com/share/e82c783cf6b940608bbfd95a3cd9104b

### Steps To Reproduce

Add a new widget and while dropping it, make other widgets move. It will make the first property in focus rather than the widget name.

### Version

Cloud

**Comment by btsgh** [comment]
Waiting for the fix for bug - https://github.com/appsmithorg/appsmith/issues/14512 -  to test this issue.
