### ISSUE TITLE
[Bug]: First evaluations for generate CRUD failing

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#14278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After generating a CRUD page for Google Sheets, the fetch rows query does not seem to populate the Sheet URL and Sheet name on the UI correctly. All the queries execute properly though, and they seem to have the same action configuration. 

### Steps To Reproduce

https://user-images.githubusercontent.com/5298848/171847547-2b5ffd13-6cea-4808-abec-dcb4dc9b6408.mov

### Version

Deploy Preview

**Comment by Nikhil-Nandagopal** [comment]
@Irongade @nidhi-nair this doesn't seem to be using the latest generate CRUD app
