### ISSUE TITLE
[Docs]: I'd like to add a CDK Construct to make it easier to setup on AWS ECS

### ISSUE THREAD

**Issue by tomharvey** [appsmithorg/appsmith#14289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I don't like to click my way through the AWS console, and AWS CDK allows us to write IaaC and make everything repeatable.

### Describe the improvement

I've written up a CDK construct which allows anyone to deploy Appsmith as a ECS Fargate service.

I'd like to host this file in the docs, and include information on how to use it to create an appsmith deployment.

Is the GitBook editable? Where do I edit the docs?

[appsmith_fargate.txt](https://github.com/appsmithorg/appsmith/files/8835424/appsmith_fargate.txt)

**Comment by Nikhil-Nandagopal** [comment]
Hello, you can simply raise a PR to the docs page. I suggest adding this under https://github.com/appsmithorg/appsmith-docs/blob/v1.3/setting-up/aws-ami.md

**Comment by jnikhila** [comment]
@sum35h - Could you please confirm and share the details that we can add?

**Comment by danciaclara** [comment]
@sharat87 Could you please confirm if this needs to be included in our official docs or as a knowledge base article?
