### ISSUE TITLE
[Bug]: The data from the query does not show up on the widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#14299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Its observed that the response on the query that is visible in the query pane evaluates to undefined on the widget after the query finishes loading.

### Steps To Reproduce

Checkout the release manager app

- Get response from a query
- bind data on for ex a table widget
- observe that the data shows up as undefined on the widget but not the query pane

### Public Sample App

https://app.appsmith.com/app/appsmith-standup/release-manager-61e7f0d8eb0501052b9fef5f/

### Version

Cloud - v1.7.1

**Comment by YatinChaubal** [comment]
Verified as part of release
