### ISSUE TITLE
[Bug]: Logs Tab

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#14297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Logs tab does not show the warning or errors generated by the code in JS Objects. Ideally, the logs tab should also show errors or warning generated by the code written by developers. 

### Steps To Reproduce

NA

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@jnikhila the logs tab only shows runtime errors and logs and since warnings are a static construct, they are shown under the errors tab

**Comment by jnikhila** [comment]
@Nikhil-Nandagopal - The logs tab just shows logs that are generated by Appsmith codebase like execution timestamp etc. But the logs that the developer wants to generate are not a part of it. Probably, I'll rephrase the sentence so that it's clear. The main idea is that developer written code related logs, warnings are not generated in the errors/log tab available for a JS Object.

**Comment by Nikhil-Nandagopal** [comment]
@jnikhila if you mean console.log then we have a feature for that here #14228
