### ISSUE TITLE
[Docs]: Include information on how to manually update to new release on each hosting platform

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#14298]

**Comment by jnikhila** [comment]
@sum35h - could you please update the ticket status once the desired changes are done?

**Comment by jnikhila** [comment]
@sumitsum - Could you please confirm if the changes are done?

**Comment by sum35h** [comment]
@jnikhila The documentation for maual update are already published.
-   Docker
-   K8s
-   AWS MAI
-   AWS ECS
-   Digital Ocean
-   Heroku
