### ISSUE TITLE
[Enhancement] Add tooltips in the query screen - Hubspot Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#14296]
Recently, was implemented the functionality of being able to add a tooltip and subtext to dynamic variables, so HubSpot's variables will be updated as well.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/ee26c66e-c826-47af-bb30-6b3ccb8f9e12)

**Comment by felixsuarez0727** [comment]
I did not have bandwidth to catch this issue. It will be moved to next sprint: Jun 13 - Jun 26, 2022.

**Comment by felixsuarez0727** [comment]
## Updates 
I have added all the tooltips and subtexts for Hubspot actions in [EngSpec](https://www.notion.so/appsmith/HubSpot-1-2-EngSpec-7aeec604d39c4d3697698a7b1931f6cf#247bc6ebd3ad4f07831a2071b7abb332), @nidhi-nair you can help us to review this section before moving to Saas Manager?.

The format we use for the tooltips is `"The number of users to retrieve. Type: Integer"`. Is a description and the type of the input, and for the subtext `"The maximum number of results per page. Example: 20".` Is a  short description with an example. 

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/4248b678-eace-4b3e-9516-823b898f9abb)

**Note:** In some cases, the subtexts were longer, so we put the example in the tooltip.

**Comment by felixsuarez0727** [comment]
Comments from Nidhi and Nikhil suggest that tooltips and subtexts are too verbose without adding value:

> One feedback I have is that we can get rid of the example, since the example is visible in the placeholder text any way. - Nidhi

> my general feedback is that it's too verbose and it's giving information about the field without actually helping the user configure it. - Nikhil

I'm working on a few proposals here: [Proposal: Simplification of Tooltip and Subtext for Hubspot](https://www.notion.so/appsmith/Proposal-Simplification-of-Tooltip-and-Subtext-for-Hubspot-712d24ef9ab84ff79ca83615059cee35)

**Comment by felixsuarez0727** [comment]
Need bless from Rohan (Product) to go ahead with this proposal.
https://www.notion.so/appsmith/Proposal-Simplification-of-Tooltip-and-Subtext-for-Hubspot-712d24ef9ab84ff79ca83615059cee35

**Comment by rohan-arthur** [comment]
@felixsuarez0727 looks good! :)

**Comment by felixsuarez0727** [comment]
All tooltips were completed.

**Comment by prapullac** [comment]
@felixsuarez0727 :
Unable to see the tooltip please view the screenshot for the same 
![Screenshot 2022-09-02 at 4.18.04 PM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/78a71e9e-a164-4c9f-b22b-aa52b3dad5b1)

**Comment by felixsuarez0727** [comment]
The `SaaS Integrations | Testing` org has been updated with the latest version of HubSpot. If you are using a private Org, please install the latest version of HubSpot to that Org via the SaaS Manager App.

Also make sure you are using the right Datasource (there are still old versions that we have not been able to uninstall). Refer to the images below:

![20220902072033.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/c7da5f9c-69cc-4ef7-984c-6976567b68c5)
![20220902072129.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/1e6fbb2e-6e5f-4a7e-bc45-c82423a4f199)
![20220902072332.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/4b9c3752-3bba-49c3-b74c-93e4776f10d5)

**Comment by prapullac** [comment]
@felixsuarez0727 : I observe the tooltip only in the datasource that you have created on trying to identify the same on other hubspot datasource i am unable to find the tooltip can I get clarity here

**Comment by felixsuarez0727** [comment]
@prapullac , on the "SaaS Integrations | Testing" organization there are multiple datasources and queries that were created from old versions of the HubSpot integrations, those should no longer be used since they don't have the latest updates.

The best way for you to verify the tooltips is to install the Integration manually on your own organization. Please follow the steps on the "Verification" section of [this document](https://www.notion.so/appsmith/How-to-Edit-Tooltips-2bf9e4fdafb14946b46ce838e44f9343#8f077798f43d4f3ba3aa069b6e985dab).

Sorry for the confusion. The datasource that I showed you has the latest updates on this. In the future, we will work on the feature to uninstall Integrations from Orgs so that there will only be one HubSpot on that org.

**Comment by prapullac** [comment]
@felixsuarez0727 : Thanks Felix this is great source of information. we observe only on the new installed Hubspot and not on the older datsources if I have understood it right. hence we can close the issue
