### ISSUE TITLE
[Bug]-[44]:Not able to commit my branch getting 404 error

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1916" alt="Screenshot 2022-06-06 at 2 55 30 PM" src="https://user-images.githubusercontent.com/83569920/172134332-32aeccad-1954-4a06-a226-0966a9dc8991.png">

### Steps To Reproduce

1. Created an app
2. Create a new branch and made some change
3. click on deploy
4. Click on commit
5. I am not able to commit

### Version

Cloud

**Comment by AnaghHegde** [comment]
@vivekverma2312 I am not able to reproduce this error. Can you please share the app where you have faced this issue?
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12005551/172150496-52c0ed7c-1de3-48ab-a1b1-5c8746c7a2cd.png">

**Comment by vivekverma2312** [comment]
@AnaghHegde The latest changes where discarded by mistake so I am trying if I can repro the issue.

**Comment by abhvsn** [comment]
@RakshaKShetty can you keep an eye on this, not sure what was the rootcause as we are unable to repro this now.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 11 |
| Effort (months)  | 0.5 |

Putting down reach for this as people who've made a manual commit after creating a branch in the last 6 months: 11
