### ISSUE TITLE
[Bug]: Theme font is applied to appsmith when navigating from deploy mode back to edit mode

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#14305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i apply a new theme font and deploy it, then come back to the edit mode of the app using the edit button in deployed mode. 

I can see the same font is applied to appsmith as well.

### Steps To Reproduce

1. Select a new font in app's theme
2. Deploy the app
3. In the deployed app click on edit app again and come back to the edit mode
4. Now the theme font will also be visible in appsmith for property pane, IDE and other places
![Screenshot 2022-06-06 at 2 38 09 PM](https://user-images.githubusercontent.com/19730984/172131399-8bb06cdb-52ea-41e1-bcd3-bf1231cb2901.png)

### Version

Production/Cloud

**Comment by chandannkumar** [comment]
Tested this in PR #14492 and working as expected
