### ISSUE TITLE
[Bug] Maps : Initial location does not get stored in the Property pane 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1430]
Steps to reproduce:
1) Add an MAP widget 
2) Add a Initial Location 
and  observe 

Observation:
1) the map does not navigate to desired location on edit mode however on deploy mode the map is navigated to initial location

**Comment by ofpiyush** [comment]
@prapullac I wasn't able to reproduce this. This might have been fixed already.

Can you check again?

If you see the same behaviour, please include more information like browser and/or console errors.

There is a related issue that I see, the name of the location doesn't persist. I'll check that.

**Comment by prapullac** [comment]
@ofpiyush I am able to reproduce the issue Please refer the screenshot for the same 
![Screenshot 2020-11-18 at 1 46 20 PM](https://user-images.githubusercontent.com/71753653/99503996-ecd9bc80-29a4-11eb-81b2-0730e9fe9019.png)

**Comment by ofpiyush** [comment]
Yes that's the one I can see.

> the map does not navigate to desired location on edit mode however on deploy mode the map is navigated to initial location

This is the one that I can't seem to reproduce, the map does navigate to the location.

**Comment by prapullac** [comment]
@ofpiyush : Correct this is resolved on both edit and deploy mode the map is moved to desired location. We can close the issue
