### ISSUE TITLE
[Bug]: The scrollbar is shown for commit message input even when it is disabled in git sync modal

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#14308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/172133100-e16fe304-17d9-4d07-8edf-bd7d251f5f3c.mov

Ideally scrollbar should be removed when the initial commit is disabled.

### Steps To Reproduce

1. Connect an app to git
2. Observe git sync modal when initial commit is disabled

### Version

Release

**Comment by IAmAnubhavSaini** [comment]
This has been fixed.


https://user-images.githubusercontent.com/1573771/177025792-58672a68-fe38-4f15-9fdf-048a47518705.mov
