### ISSUE TITLE
[Bug] Maps : On Copy paste of the widget the map is navigated to initial location 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1431]
Steps to reproduce:
1) Add a Map widget
2) Add initial location 
and observe that the map is not navigated to initial location
3) Copy the widget 
4) Paste the widget 
and observe

Observation:
It is observed that Copied map widget is at initial location. 

Expectation:
both the parent and child widget should have similar behaviour

**Comment by ofpiyush** [comment]
I tested it on https://release.app.appsmith.com and both seem to work and behave the same. 

I'll keep this open till I make changes on other map bugs as a reminder to test copy behaviour as well.
