### ISSUE TITLE
[Bug]: Prettify the error message for WHERE condition failures

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#14312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The action execution failure seen when the where clause column value is not a valid column in the Google Sheet is the generic uncaught promise. The error details also just displays the SQL query instead of a pointed UQI field.

### Steps To Reproduce

1. Create a fetch many rows query
2. Add a where clause with a random (invalid) column
3. Run the query in the editor
4. Also try running it as a trigger (button click on the canvas)

### Version

Deploy Preview

**Comment by prapullac** [comment]
Not in the release yet
