### ISSUE TITLE
[Feature]: Show horizontal scroll bar in table widget only on hover

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#14319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great to show the scrollbar in the table widget only hover just like we have for the vertical scrollbar. The behavior should be the same.

### Why should this be worked on?

The scrollbar in the tables widget shows up all the time and it kind of looks ugly.

**Comment by dilippitchika** [comment]
Duplicate of #3744
