### ISSUE TITLE
[Bug]: The deleted variable is displayed inside the JS object autosuggestion

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The deleted variable is displayed inside the JS object autosuggestion
https://www.loom.com/share/e6514d24bc964bce830215d3fa057790

### Steps To Reproduce

1. Add new js object
2. Add few variables along with myvar 1 and 3
3. Now delete all the variable just keep var1
4. now add atext widget 
5. try to bind the js type jsobject1. all the deleted variable names are displayed

### Version

release

**Comment by rohan-arthur** [comment]
additionally, the type of `myVar1` is still shown as `array` in the autocomplete, but Raksha has changed it to a string. Check 00:40.

**Comment by Rishabh-Rathod** [comment]
This seems to be resolved by the JSObject AST parsing fix #14842 which went into release.

We could verify and close this. I have already verified once. 

cc: @ramsaptami  @RakshaKShetty
