### ISSUE TITLE
[Bug]-[84]:Checkbox Group widget - inline disabled, Label position Top or Auto, Style Alignment - End/Center/Around - label and options overlap

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a check box group widget to canvas, add around 3 / 4 more options, set inline to off, label position to top or auto, and style alignment to either end/center/around, the label and options get overlapped and UI is not clear.

### Steps To Reproduce

1. Drag and drop a checkbox group widget
2. Add around 3 or 4 more options.
3. Set the inline property to off, and label position to top or auto
4. Set Style Alignment to either - End/Center/Around.

Observe that the label and options get overlapped and UI is not clear.
<img width="737" alt="Screenshot 2022-06-06 at 9 02 56 PM" src="https://user-images.githubusercontent.com/101863839/172194578-dfce8690-7d2d-441d-b9c0-9164ef00605a.png">

### Version

Production

**Comment by btsgh** [comment]
Also seeing this behavior on deploy if the checkbox group widget is placed at the top of the page - 
<img width="763" alt="Screenshot 2022-06-17 at 12 53 05 PM" src="https://user-images.githubusercontent.com/101863839/174247345-ceea21b6-f05d-42b9-b3b2-8eb4ea9aef07.png">

**Comment by dilippitchika** [comment]
1. Ok the alignment option is only useful when inline is switched on, once off we can choose to hide the alignment option. 
2. If the inline field is js controlled then alignment will only work when inline is true.
3. Another bug with checkbox group is that when inline is on and there are options which exceed a line, resizing the widget other options which are outside don't come within the widget boundaries. 
![Screenshot 2022-06-21 at 12 23 16 PM](https://user-images.githubusercontent.com/19730984/174735398-dad42d7e-d3fb-469d-83c6-95b1e84fd53e.png)

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 84 |
| Effort (months)  | 0.5 |
