### ISSUE TITLE
[Bug]: Home page behaviour on deployed app when page is hidden

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Deploying an app where the home page is marked as `hidden,` hides all the other pages on the app in deployed mode. Launching the app from here on only shows the hidden home page and not the other pages

### Steps To Reproduce

1. Have multiple pages on an app
2. Mark home page as hidden and deploy the app
3. Notice other pages on the app not appear in view mode

https://www.loom.com/share/f3428a10459044b987b76567f181f490

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is actually an expected behavior. Hidden means to hide it from the navigation hierarchy and make it an internal page. Users use this for login pages on Appsmith so that their team lands directly on a login page that does not have any other pages till they login
