### ISSUE TITLE
[Bug]: API response from server has string datatype in body

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#14329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We saw an issue where Appsmith crashed(handled in client side) for users when they created an API with URL as https://raw.githubusercontent.com/dmfilipenko/timezones.json/master/timezones.json and hit run to it.

This is a server side fix for the issue - #14242

### Steps To Reproduce

1. Create a new API
2. Enter URL = https://raw.githubusercontent.com/dmfilipenko/timezones.json/master/timezones.json
3. Hit run.

### Public Sample App

https://release.app.appsmith.com/app/dynamically-change-input-text/page1-62729b10bf58a33d4ce4cedb/edit

### Version

1.7.1

**Comment by rohan-arthur** [comment]
duplicate: https://github.com/appsmithorg/appsmith/issues/14666
