### ISSUE TITLE
[Docs]: Need docs for reset widget styles feature

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#14336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

https://github.com/appsmithorg/appsmith/issues/13596

For older apps (apps which were created before theming was live) a ui builder has to manually go and update each widget to reset their styles to use app theming. This feature helps them reset all such styles across widgets with a single click. 

Can be cheked in release, just make sure you change multiple widgets colors to be different than theme colors and click on reset widget styles from the theme properties.

### Describe the improvement

**EXISTING CONTENT**
--

All apps support theming, but for older apps, changing the theme or customizing the theme may not update the app entirely. This is to prevent overriding any changes you have already done by styling your widgets. If you still want to use themes in your existing application, please reset your widget's styles.****

**NEW CONTENT**
--
All apps support theming, but for older apps we do not want to override any style changes you have done. To apply theming in older apps you have to specifically reset all current widgets styles from the menu in the theme properties. 

All the previous widgets which were not able to support styling using themes will now be available to style. 

NOTE: Widgets which are deprecated will not support theming, you will need to upgrade them to support theming.

**Comment by jnikhila** [comment]
Documentation published. CC: @spark-c
