### ISSUE TITLE
[Bug]: CI does not catch Junit test failures

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#14333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the PR is created in github multiple tests are run and if all of these tests run without failures then we can merge the changes to release branch. 

But the Junit test failures are not accounted for this. Even though there are failures in JUnit this is not considered and one can merge the PR to release branch. 
https://theappsmith.slack.com/archives/CPQNLFHTN/p1654535891273319

**Comment by AnaghHegde** [comment]
Findings : 
The CI was skipped due to the incompatibility issue between surefire plugin and junit 4. So only the tests using junit 5 were run and junit 4 dependent tests did not run. Hence they were not caught in CI.

**Comment by sidhantgoel** [comment]
1 PR still pending, opening again.

**Comment by yatinappsmith** [comment]
Cannot be verified
