### ISSUE TITLE
[Bug]-[1185]:Table (v1) row selection is not retained when PrimaryKey is set & sorting applied

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#14347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/172361472-48acd577-41cf-4210-b86c-d1e57a2d5e61.mov

### Steps To Reproduce

1. Create a CRUD page , eg: from Postgres DS
2. Set the Primary Key of the data table (that is supposed to retain the selection of row)
3. Deploy the app & update some row fields from JSON Form
4. Observe : Row selection is retained & user doesnt loose track of the row where the change is made
5. Now - Apply some sort to the table
6. Update some row fields again
7. **Observe: Row selection is not retained & some random rows are selected even when Primary column of the data_table remains set**
8. **Expected: Row selection should retain when Primary Key is set - after any action by user**

### Version

Prod/Release v1.7.1

**Comment by dilippitchika** [comment]
Assuming all of users who set primary column id are impacted

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1185 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Just leaving my notes for triaging here
1. When sorting is applied and you update something and run the get query the table is re-rendered losing the applied sorting in the first place.
2. If the sort is server side, then updating and expecting the primary key to be retained means that data can be on a different page altogether now. 

I don't know if we can solve this even without any server actions 
1. unless you store the applied sorting when table re-loads.
2. or remove the sorting and highlight the right row, but the position may be different.

**Comment by dilippitchika** [comment]
@sbalaji1192 please triage in the next meeting

**Comment by sbalaji1192** [comment]
@dilippitchika Currently we reset the sorting orders, and filters when the tableData changes. We compare the tableData as a whole including schema and row values. I guess we need to only reset the sorting order and filter if the schema changes. Need to think further about the edge cases
Removing this from the stability epic

**Comment by GreenFlux** [comment]
Similar issue reported here:
https://community.appsmith.com/t/how-to-stay-on-selected-row-after-updating-data-of-row-in-a-table/1688

In this case, the user was not using sorting, or the PrimaryKey property. Once they added the PrimaryKey, the selectedRow retention started working again.

**Comment by rahulbarwal** [comment]
Not reproducible in Table V2. Assuming that this is fixed, I am closing this. Please re-open if you face this again.
