### ISSUE TITLE
[Feature]: Nested Lists: Add a List Widget Inside Another List Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#14341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add support for using nested lists. This feature was requested by several users. 

[Use case example](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100118258#part_id=comment-164629100118258-15078222023):
The user wants to display courses. A course can have multiple modules and each module has different types of content: video, pdf, quiz. The number of modules and the number of videos/pdfs/quizzes each module contains are unknown, so the structure is not always the same.
Example: Let's suppose that we have a course with 2 modules:
Module A has 1 video a 1 PDF
Module B has 3 videos and 1 quiz
![image](https://user-images.githubusercontent.com/101268423/172331171-ee534c4b-e975-4cac-ba07-4bfdcddd8ef8.png)
![image](https://user-images.githubusercontent.com/101268423/172329309-1f51d0d5-479f-409d-814c-6952e88daae4.png)

Here's [another use case](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100071117#part_id=comment-164629100071117-13734026916).

### Why should this be worked on?

The ability to use nested lists would help users to display data with flexible structure and number of items.

**Comment by Nikhil-Nandagopal** [comment]
Related to #2888

**Comment by dilippitchika** [comment]
Fixed in list v2

**Comment by JetUni** [comment]
How can I use list v2? I don't see any option in the UI and I'm having trouble setting up something similar to this

**Comment by Nikhil-Nandagopal** [comment]
@JetUni update to the latest version and simply drag a list widget and it will be available
