### ISSUE TITLE
[Enhancement] Show empty message in entity explorer when there are no datasources

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1435]
## Summary

When the list of datasources is empty for an organization, when I expand the dropdown for datasources in the entity explorer, I should see an empty message. 

## Motivation

All other sections of the entity explorer show an empty message. For eg, when there are no widgets, the widget drop down expands to show the message: "No widgets yet .... ". We should show a similar message in the datasources dropdown.

**Comment by Sushmitha004** [comment]
Hi, I would like to work on this issue. Can you please assign this issue to me?

**Comment by trishaanand** [comment]
@Sushmitha004 : Go for it! Good luck!

**Comment by Sushmitha004** [comment]
> @Sushmitha004 : Go for it! Good luck!

@trishaanand Thank you :)

**Comment by Nikhil-Nandagopal** [comment]
@Sushmitha004 if you haven't already, please skip this issue. We're changing the location of datasources and this issue will no longer be valid in a few days. Sorry for the confusion 😅 
If you already have a PR open already, we'll leave it open so you qualify for hacktober 😃

**Comment by Sushmitha004** [comment]
> @Sushmitha004 if you haven't already, please skip this issue. We're changing the location of datasources and this issue will no longer be valid in a few days. Sorry for the confusion 😅
> If you already have a PR open already, we'll leave it open so you qualify for hacktober 😃

No issues :)
