### ISSUE TITLE
[Docs]: How to add an application load balancer on top of ECS setup

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#14361]
In reference to query [here on Intercom](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100119794)

**Comment by jnikhila** [comment]
@sharat87 - Could you please let us know if we need to document this?

**Comment by jnikhila** [comment]
@sharat87 - I believe this is more of an AWS specific task. I don't think we need to document this. Could you please confirm?

**Comment by sharat87** [comment]
@jnikhila, yes. At best, it may make sense as a knowledge base article in the community site, but not part of our docs.
