### ISSUE TITLE
[Task]: Analytics event for actions CRUD

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

raise an event from the backend when a JS Object / Query / API is:
- create_Query / create_JSObject / create_JSFunction
- delete_Query / delete_JSObject / delete_JSFunction
- rename_Query / rename_JSObject / rename_JSFunction
- update_Query / update_JSObject / update_JSFunction

With metadata of
- queryName
- appName
- pageName
- appId
- orgId
- pageId
- datasource (see execute event)
- pluginName

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair @rohan-arthur I updated some of the property names. Also these should be separate events and not a single event with different operation properties
