### ISSUE TITLE
[Docs] Add Linux specific constraints and build debug info

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#1437]
## Documentation Link 

https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md
https://github.com/appsmithorg/appsmith/blob/master/contributions/ServerSetup.md 

## Describe the problem

1. The setup guide is written with macOS as the reference. There are minor differences when working with Linux 
    environment. 
2. The setup guide does not provide debug info in some build failure cases - like docker failing silently. 
3. Some steps look obsolete. 
4. Some statements could be misleading. 
5. Please check the attached document for details : [setup_experience.pdf](https://github.com/appsmithorg/appsmith/files/5449739/setup_experience.pdf)

## Describe the improvement

A clear and concise description of the improvement.

1. Add Linux specific requirements. 
2. Add debug info for common build errors.
3. Correct build step or any statement wherever required.

**Comment by sumitsum** [comment]
Hi @Nikhil-Nandagopal please assign the issue to me.

**Comment by mohanarpit** [comment]
@sumitsum This is all yours now 😄

**Comment by sumitsum** [comment]
Fixed.
