### ISSUE TITLE
[Bug] When I create large joins, the fields of the 3rd table and on do not show up (and other quirks)

### ISSUE THREAD

**Issue by tluyben** [appsmithorg/appsmith#1438]
## Description

select * from x,y where x.id=y.xid;

shows only content from x in the resulting table. 

select x.id, x.name, x...., y.id,y.name,y.... etc

works fine, however; 

select x.id, x.name, x...., y.id,y.name,y....,z.id,z.name,z.... from x,y,z where ..join them

shows no values from z, also if you rearrange them; 

select x.name,z.street,y.cheese from x,y,z 

it shows name and cheese but not street. 

### Steps to reproduce the behaviour:

Just create larger joins and click Run + Add Widget. 

This might be partially related to the width / css bugs in the table, but not completely/in all cases ; the fields are simply not there. 

### Important Details
- Self hosted, installed 1 day ago (where do I find the version)? 
- Linux/Ubuntu

There are no relevant errors in logs as far as I saw (only some synching errors which pop up but not during testing of any of these features) (either chrome or server).

**Comment by Nikhil-Nandagopal** [comment]
@tluyben this could be because the column names generated are the same, you can add an alias to the column names to take care of this

**Comment by Nikhil-Nandagopal** [comment]
@tluyben , we verified that this is indeed the issue. Steps we're taking are to notify users that there are 2 columns being returned with the same name and hence re-directing them to alias their columns. Since this does not block a user, lowering the priority here.

**Comment by tluyben** [comment]
Another *doh*; yep that's it. Thanks... I used something I hacked together before which just automagically fixed that so I really didn't think about it! Thanks for the help ! 

I can fix/add stuff myself, especially on the backend (I'm an api/backend dev with almost 15 years of java), but I couldn't get the frontend to compile/work; i'll come online in Discord one of these days.

**Comment by Nikhil-Nandagopal** [comment]
Awesome! Looking forward to seeing you there 😄  Feel free to reach out for any help whatsoever!

**Comment by sumitsum** [comment]
reopening to track client side changes. Server side changes had been merged with the linked PR.
