### ISSUE TITLE
[Bug]: App canvas is stuck in loading state ( Desktop Layout )

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[This](https://release.app.appsmith.com/app/earworm/home-6219207a0276eb01d22fec5e/edit) app is stuck in a loading state and I'm unable to edit the app. The app can be viewed in view mode though

### Steps To Reproduce

1. Go to app at [this location](https://release.app.appsmith.com/app/earworm/home-6219207a0276eb01d22fec5e/edit) and throttle internet and CPU speeds and then remove the throttles
2. Observe the canvas remains in loading state as seen in the video

https://www.loom.com/share/f5815278b0274f8a91b9485e35c7eab1

### Version

Cloud

**Comment by SatishGandham** [comment]
This happens only in the desktop layout. Use fluid layout until the issue is resolved.

**Comment by vivekverma2312** [comment]
@jsartisan I am still able to repro this issue on release. [App](https://release.app.appsmith.com/app/maintenance-order-management/home-page-62a1b68a61c2701a373be911)
