### ISSUE TITLE
[Bug]: DynamoDB is broken

### ISSUE THREAD

**Issue by maximelebastard** [appsmithorg/appsmith#14391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since latest update 1.7.1 - when I go to my existing DynamoDB datasource and press "Test", I'm getting the error `for input string ""`

This breaks all my apps and has been auto-updated

### Steps To Reproduce

1. Create a new DynamoDB datasource
2. Enter credentials and press "Test"
3. See the error `for input string ""`

Other case:
1. Use an existing DynamoDB datasource by doing a request
2. See the error `for input string ""`

### Version

Self Hosted - 1.7.1

**Comment by Nikhil-Nandagopal** [comment]
@maximelebastard sorry you're facing this issue. Are your existing queries still running?

@ajinkyakulkarni @rohan-arthur could someone have a look here?

**Comment by maximelebastard** [comment]
@Nikhil-Nandagopal thank you for the quick reply.
Actually all my existing queries to dynamodb are broken - and it still not works even if I create a new datasource and recreate the queries.

**Comment by Nikhil-Nandagopal** [comment]
@maximelebastard sorry you're facing this. We're actively working on a fix

**Comment by subrata71** [comment]
@maximelebastard 
Thanks for sharing the stack trace. I wonder if that is **all** that you shared? Can you please check again if there's more stack trace for this error?

Also, can you please tell us your availability for having a session with you?

**Comment by sumitsum** [comment]
Work around is to add the following to the `docker.env` file: 
```
HTTP_PROXY=http://:0
HTTPS_PROXY=https://:0
```

**Comment by maximelebastard** [comment]
@subrata71 I took a slot on your Calendly, thanks

@sumitsum Your workaround worked ! Thank you !
How can this be related to the proxy ? 🤔

**Comment by subrata71** [comment]
AWS DyanmoDB SDK is trying to resolve the proxy port for unknown reasons. It appears to be unknown to us. However, the team is working on finding the right fix for this problem. Till then please go with this workaround solution. Please bear with us.

Do we still need the meeting? @maximelebastard

**Comment by maximelebastard** [comment]
@subrata71 If the issue is identified and reproduced on your side - I don't think so :)

**Comment by sharat87** [comment]
Adding a little more detail, the AWS API is fundamentally an HTTP API. So, when there's a HTTP proxy configured, it automatically tries to pick it up, and use it to make calls to AWS.

So far, Appsmith didn't support HTTP proxies, in any form or fashion. The last version added support for this in the REST API plugin. However, in the way this was done, the proxy port was set to empty string `""`, when a proxy is not configured. This takes the form `-Dhttp.proxyPort=""` in the Appsmith's server's `java` command. Previously, the proxyPort wasn't set at all, and this argument wasn't present at all.

Now, the AWS Java SDK, when noticing that there is a proxy port set, it immediately tries to parse it as a number. But, of course, an empty string `""` can't be converted to a string, and so we see the error.

With the workaround, we are basically setting the proxy host to empty string `""`, and proxy port to `0`. So when the AWS SDK tries to parse the port, it gets `0` and figures that the proxy was probably misconfigured and proceeds without using a proxy for the HTTP calls. This is why the workaround is able to do what it does.

I'm now working on a fix where if a proxy is not available, the `-DproxyPort` is not passed at all, and so this error shouldn't occur even if the workaround is not applied. I'll notify on this issue when you may remove those env variables from your `docker.env`.

Thank you for your patience with this issue. Let me know if I should elaborate on anything further on this topic. Cheers!

**Comment by btsgh** [comment]
Tested based on scripts in the associated [PR](https://github.com/appsmithorg/appsmith/pull/14508), and after discussion with @sharat87 .. Dynamo DB "Test" and "Save" works fine in the above mentioned scenario.
