### ISSUE TITLE
[Bug]: INSERT into PSQL text ending in "D" or "F" fails

### ISSUE THREAD

**Issue by disl-pdavid** [appsmithorg/appsmith#14394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using 1.7.1 in docker.
I have a psql table that has been working fine:
```
  Column   |            Type             | Collation | Nullable |           Default            | Storage  | Stats target | Description 
------------+-----------------------------+-----------+----------+------------------------------+----------+--------------+-------------
 id         | integer                     |           | not null | generated always as identity | plain    |              | 
 serial     | text                        |           |          |                              | extended |              | 
 created_on | timestamp without time zone |           |          |                              | plain    |              | 
Indexes:
    "sondes_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "deployment" CONSTRAINT "deployment_sonde_fkey" FOREIGN KEY (sonde) REFERENCES sondes(id)
```

I bind a simple form to add data to the table that works just fine for almost anything.
**EXCEPT** if my input text string ends in the character `D` or `F` (or `d` or `f`).

Trying to input any sequence of characters and numbers works fine.
It only fails when it's any number of digits, followed by the characters `D` or `F`

| input | result |
| --- | --- |
| 123 | :heavy_check_mark: |
| 123D | :x: |
| 123F | :x: |
|12343234D | :x: |
| 123aa1D | :heavy_check_mark: |

This is the error I see for the query when attempting this:
```
01:29:06
[AddSondeQuery]Execution failed with status 5005
Query preparation failed while inserting value: 123456D for binding: {{SerialNumberInput.text}}. Please check the query again. Error: Character D is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
{
"requestParams":{...
}
}
```

### Steps To Reproduce

1. Create new app.
2. Add postgresql data source
3. Create a table with a `text` column.
4. Bind input form to a query to `INSERT` to that table/column.
5. Try to insert above string that fails `123D`.

The cloud version of appsmith has this same bug (see sample app).

### Public Sample App

https://app.appsmith.com/app/my-first-application/page1-629777d8b4c51656bfec095a

### Version

Cloud + Self-Hosted 1.7.1

**Comment by Nikhil-Nandagopal** [comment]
@disl-pdavid Thanks for reporting this. Did this work before? Can you try wrapping it in quotes? That should help

**Comment by rohan-arthur** [comment]
Thanks @disl-pdavid for that clue about prepared statements. We will look into this.

**Comment by disl-pdavid** [comment]
> @disl-pdavid is there an issue with quotes? You should be able to manage this with '{{Input1.text}}' and prepared statements being on

The query is a simple one:

```sql
INSERT INTO sensors (type, serial, created_on) 
VALUES 
('{{TypeSelect.selectedOptionValue}}',
 '{{SerialNumberInput.text}}',
 NOW()
)
```

With prepared statements on, this fails with the above messages.  
Did you perhaps mean quotes somewhere else that I might be misunderstanding?

**Comment by subrata71** [comment]
This is supposed to be fixed by this [PR](https://github.com/appsmithorg/appsmith/pull/17429). Hence, I am closing this issue.
