### ISSUE TITLE
API responses with 204 HTTP Status code and empty bodies display as error yet they are succesful.

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#14390]
Context: https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/14108

![image2.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/bdc8254f-89b8-4603-add0-9aca9bde2f63)

**Comment by ChandanBalajiBP** [comment]
@felixsuarez0727 I am not able to reproduce the error with the given curl import. Can you help me with this.

**Comment by ChandanBalajiBP** [comment]
Closing this issue as its not reproducible in version 1.7.2 as well as in release.
