### ISSUE TITLE
Add more data points to the backend error flows for git

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#14398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Below mentioned parameters need to be present in the error message for git
- applicationId 
- ApplicationName
- userId/userName(to connect the nginx and server logs)
- Improve sentry logs as well by including the user context
- branchName

**Comment by AnaghHegde** [comment]
@abhvsn Do you have any suggestions on what extra fields or any other info we need to include in the error message for the git sync ?

**Comment by abhvsn** [comment]
Let's include the `branchName` to the param list.

**Comment by infinitetrooper** [comment]
Stale
