### ISSUE TITLE
[Bug]: Black border on Application card menu

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#14392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="311" alt="image (3)" src="https://user-images.githubusercontent.com/10436935/172687753-33582b5d-0b36-4c14-ac7c-d0787d0f15e9.png">

Related to this, we could see a black border around the widget name in the property pane:
https://www.loom.com/share/36fd6e2a47fd47f391495e08a7927dc9

### Steps To Reproduce

Open the home page and click on the three-dotted menu button below the application.

### Version

Cloud 1.7.1

**Comment by Sripriya93** [comment]
Fix# 14393 affects - 
[Task]: Opening property pane should focus the widget name #11199
[Bug]: widget's name is not getting focused on adding new widget #14265

Also Organization name is focused with black border
![image (2)](https://user-images.githubusercontent.com/104895602/173026349-d991d35e-4015-41b1-aa10-6d6a6c1b5a92.png)

**Comment by aswathkk** [comment]
@Sripriya93 I've moved one bug to a separate issue (#14512) since it requires some more effort to solve.

**Comment by btsgh** [comment]
Issue is fixed - Clicking on the three-dotted menu button below the application and Clicking on the similar menu next to New for creating a new app, the black border does is not present
