### ISSUE TITLE
[Feature]: Introduce optional typeahead in dropdowns

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#14405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need the option for dropdowns to be able to have the type ahead feature so that users can filter through the drop down easily. 

### Why should this be worked on?

Currently, the use case for this is limited to Google Sheets UQI. [Link](https://github.com/appsmithorg/appsmith/issues/14031) to related issue for this in UQI

**Comment by tanvibhakta** [comment]
Link to the design docs for this: https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=10508%3A30677

**Comment by nidhi-nair** [comment]
Closing since the component is now [available](https://github.com/appsmithorg/appsmith/issues/14405).
