### ISSUE TITLE
[Bug]: The Learn more link leads to page not found error in the git revoke modal 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Learn more link leads to page not found error in the git revoke modal 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/172789118-e2d0d6e1-b73b-4ece-acd9-abc69c96553a.png">

### Steps To Reproduce

1. open any git connected app
2. click on seeting icon on the bottom bar 
3. click on delete icon next to ssh key placeholder 
4. now in revoke access modal 
5. click on learn more link 
6. verify the error displayed in the page

### Version

release

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini I am not able to find references for these. Can you check if they are hardcoded in FE?

1.
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/12005551/172821096-90fad020-ea4c-42a9-8b95-3dbc126a1138.png">

2. 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/12005551/172821326-fe384ae1-5328-4a5b-a7b7-6edd75fcf45a.png">

**Comment by AnaghHegde** [comment]
Closing this via https://github.com/appsmithorg/appsmith/pull/14430
