### ISSUE TITLE
[Bug] Table content not  without horizontal scroll or limited horizontal scroll 

### ISSUE THREAD

**Issue by tluyben** [appsmithorg/appsmith#1440]
## Description

When creating queries and clicking Run, the resulting table underneath has no horizontal scroll. 
When add widgets from queries with large amounts of fields, not all fields show up. 

Both of the issues are because the .table element-style min-width is not calculated correctly (in the former case it is 0px and in the latter it is something but too small); is there a way to change the calculation easily?  

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

Create a query with a lot of fields (over 20) and click Run, you only see a few. Then + Add Widget and test there, you see more (as you can scroll now) but still not all (and the last one is usually cut-off). 

### Important Details
 - Version: Self-hosted
 - OS: Linux/server
- browser: Chrome/Safari (it's worse under Safari but we hardly use that anyway)

**Comment by tluyben** [comment]
It seems columncount * 150px works well for me, so as a bandaid: 

`setInterval(function(){ if (document.location.href.indexOf("edit/queries")>0) { var table = document.getElementsByClassName("table")[0];  if (table) table.style["min-width"] = (table.firstChild.children.length*150)+"px"; } else {var tables=document.getElementsByClassName("table"); if (tables)for(var i=0;i<tables.length;i++) tables[i].style["min-width"] = (tables[i].firstChild.firstChild.children.length*150)+"px";}}, 1500);`

**Comment by Nikhil-Nandagopal** [comment]
@tluyben thank you for reporting these! We'll ship a fix quickly

**Comment by Nikhil-Nandagopal** [comment]
@tluyben tested this on a few devices and needed a little clarification here
Is your trouble with the horizontal or vertical scroll in the query pane? We're only seeing an issue in the horizontal scroll.

In the table widget, I can see the data is getting paginated so there is no vertical scroll, you can instead go to the next page as indicated in the image.  Was this the confusion?
<img width="905" alt="Screenshot 2020-10-28 at 2 26 34 PM" src="https://user-images.githubusercontent.com/3897254/97414195-b40c7180-1929-11eb-98fe-012da7af9c78.png">

Please share screenshots if this does not solve it

**Comment by tluyben** [comment]
Oh! It was early for me; I meant horizontal ; fixing this issue. Apologies. The issue is not vertical, it's horizontal.

**Comment by Nikhil-Nandagopal** [comment]
@tluyben thank you! We'll fix this asap and hope the issue in the widget is clear that you can access the next page from the top right section. Thank you for the contribution 😄
