### ISSUE TITLE
[Bug]-[1644]:Handle client side migration for git discard functionality to avoid seeing uncommitted changes

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#14411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user's application has client-side migration since last commit, and if user triggers the discard and pull flow user ends up seeing uncommitted changes as client-side migrations run after the successful response from server. This gives the false impression that discard failed for some unknown error though UI does not show any error state. To resolve this issue we will be doing a autocommit when we detect the client-side migrations in get status flow:

- [x] #19209
- [ ] Chain get status API with migrations so as to avoid the race condition i.e. run all the migrations and then trigger get status API @IAmAnubhavSaini 
- [x] #14412

### Steps To Reproduce

1. Connect application to git
2. Reduce the page DSL version from DB by 1 (manual update)
3. Commit changes without refreshing the page
4. Hard refresh from browser to trigger client side migrations along with get status call
5. Try pull and discard flow
6. Even if discard is successful we will see migrations changes to be committed

### Version

Cloud: v1.7.1

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 822 |
| Effort (months)  | 1 |

@IAmAnubhavSaini roughly estimating time for this to be 2 person-weeks for prioritisation. Feel free to call out for a change if you think different.

**Comment by AnaghHegde** [comment]
Closing this as its covered via the Auto Commit flows
