### ISSUE TITLE
[Bug]-[2784]:App import/export not maintaining the main canvas state

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#14410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you export and app and import it, the canvas state is not maintained. It defaults to fluid.

### Steps To Reproduce

1. Take any app, and set the main canvas to desktop layout.
2. export the app and import it.

You will notice that the imported app has fluid layout instead of deskotop

### Version

cloud

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 348 |
| Effort (months)  | 0.25 |

**Comment by AnaghHegde** [comment]
This will be solved via this PR https://github.com/appsmithorg/appsmith/pull/14120

**Comment by AnaghHegde** [comment]
Closing this via https://github.com/appsmithorg/appsmith/pull/14120
