### ISSUE TITLE
[Epic]: Console Log 

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#14431]
### Objective

To introduce the capability to debug any appsmith application using console logs. Appsmith users should be able to write console statements in their JS objects, click handlers or API responses to create and debug complex workflows.

[Discussion history and open questions](https://www.notion.so/appsmith/Console-log-ac7c5c69a5c94670a691706a3a9061bd)

### Success Metrics

| Metric         |
| -------------- |
| Reduce support queries on A force to debug applications  |

### Prioritised User Stories

| User Story    |
| ------------- |
| As a user, I want to be able to view how data is flowing through my complex application by using console statements  |
| As a user, I want to be able to debug my JS functions to identify faulty logic  |

### RACI matrix

| ------------- | ------------- |
| Responsible   |     @ayushpahwa          |
| Accountable   |        @ayushpahwa        |
| Consulted     | @Nikhil-Nandagopal, @mohanarpit, @areyabhishek|
| Informed      |  @ajinkyakulkarni @rohan-arthur        |

**Comment by parth-appsmith** [comment]
Hi team, we've got a signoff for the console.log designs. Here is a [loom video](https://www.loom.com/share/b553a0e92f9a41b487d7fa028d790ea5) explaining the designs.
Design Spec Doc: https://www.notion.so/appsmith/Console-log-output-afacec4313414f28b91007c302597a2f
Figma Designs: https://www.figma.com/file/X03G0OsEtvH9JHDhU8XREy/JS-Editor-Improvements?node-id=2186%3A112955
Zeplin Handoff: https://zpl.io/g8X1pq0 (edited)
