### ISSUE TITLE
[Task] Fix UI for Query Form

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1443]
https://www.figma.com/file/RdWmO9Ny6SfkMZAFIhLKSU/Appsmtih-NUX-Workspace_Aakash?node-id=685%3A587

**Comment by RotonEvan** [comment]
What is the exact problem?

**Comment by Nikhil-Nandagopal** [comment]
@RotonEvan thank you for being a part of the community, this task is currently not up for grabs as it's part of an ongoing project. Feel free to have a look at our many [good first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22)
