### ISSUE TITLE
[Task]: Apps used to make this template section

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#14448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The aim of this project is to allow users who are looking at templates to also check out similar sample apps.

The sample apps will be linked based on functionalities, and the most similar sample apps will be linked with templates

**Comment by rahulbarwal** [comment]
@akash-codemonk , @kocharrahul7
Problems with this: 
* Sample apps are just guides, these are not finalized product.
* These are hosted on a separate platform. 
* In current UI we already have similar templates, we don't want to clutter the UI by giving user too much options.

Solutions that might work for this:
* Introduce these via help page in templates.
* When community library is ready, we can have tab there or a link to other resources.

Owing to these points we decided not to work on this. We might revisit this when our community library is ready. Please let us know if you have any concerns.
CC: @rlnorthcutt
