### ISSUE TITLE
[Feature]: Select widget from suggested widgets list should allow users to choose the label and value fields before adding to widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The select widget fails when a user tries to bind it from the suggested widget section. This happens when data has all nonunique values

https://www.loom.com/share/4c8a1aa5a5fb4f9988f02240964f419d

### Steps To Reproduce

1. Run the mock API
2. select the select dropdown from the widget suggestion section
3. verify the error displayed in the debugger

### Version

Cloud/Release

**Comment by chandannkumar** [comment]
https://github.com/appsmithorg/appsmith/issues/6394

**Comment by chandannkumar** [comment]
Issue related to same https://github.com/appsmithorg/appsmith/issues/6394

**Comment by dilippitchika** [comment]
I don't understand this is issue, when value is duplicate it will never work in the select widget. The dev will have to change the binding there. 

@somangshu @chandannkumar

**Comment by somangshu** [comment]
I dont remember adding the above detail here. 

I agree to @dilippitchika, this is a valid failure

**Comment by Nikhil-Nandagopal** [comment]
I think that defeats the purpose of the feature and the user can always change this later so closing it
