### ISSUE TITLE
[Bug]: storeValue not working properly

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#14461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Discord users have complained that the `storeValue` function is not working properly & breaking their apps
https://discord.com/channels/725602949748752515/984376486016458752

PS: It could be side effect of the flaky ness in async-await syntax
### Steps To Reproduce

Not able to reproduce it on cloud/release
Link to the app - https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1654854805972249?thread_ts=1654780541.136509&cid=C02K0SZQ7V3

### Version

v1.7.1

**Comment by Rishabh-Rathod** [comment]
Internal discussion - https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1656039009475309

Closing this as we weren’t able to reproduce this issue and there were 2 storeValue fixes that went in which ideally should resolve above issue too. 

Fixes - https://github.com/appsmithorg/appsmith/pull/14847, https://github.com/appsmithorg/appsmith/pull/14658

If this is reproducible then feel free to re-open it.
