### ISSUE TITLE
[Bug]: Audio widget's derived URL property is incorrect when placed inside a list widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Audio widget's source URL does not update UI information when inside a list widget even though evaluated property of that widget has updated URL's

### Steps To Reproduce

1. Go to the app at [this](https://release.app.appsmith.com/app/earworm/debugging-page-62a32578f4e3980741ff56e2/edit) location
2. `fetchTopTracks` query data is linked to both table and list widget
3. On changing query param of `fetchTopTracks` using select widget dropdown option, both widget's data is refreshed - except the audio widget on list which only changes to show previous query result, i.e., when artist2 is selected, audio widget shows derived URL from artist1. When artist3 is selected, audio widget shows derived URL from artist2

https://www.loom.com/share/d3727e5669424b09a4082715f3342ee7
![image](https://user-images.githubusercontent.com/79509062/173064075-b884d5ed-7c97-44fd-966a-23e42b80a26f.png)

### Public Sample App

https://release.app.appsmith.com/app/earworm/debugging-page-62a32578f4e3980741ff56e2/edit

### Version

Cloud

**Comment by dilippitchika** [comment]
@Tooluloope can you triage this? We need to know if it's a list issue or JS issue.

**Comment by Tooluloope** [comment]
@ramsaptami Could you help make the App work, so I can debug further

**Comment by ramsaptami** [comment]
It's in working order now @Tooluloope, you can take a look now

**Comment by kamakshibhat-appsmith** [comment]
LGTM !
