### ISSUE TITLE
[Feature]: highlight query in entity explorer upon creation from template

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I create a query from one of the available CRUD templates, I can see that a new query is created called `Query1`, with some query body etc. However, as a new user, I might not know what this Query1 is, and it would be beneficial to highlight `Query1` in the entity explorer.

https://www.loom.com/share/9ed18d2fd4534716823ddbabe6d2ca5e

### Why should this be worked on?

this will help to onboard the new user more easily to the hierarchy presented in the entity explorer.

**Comment by rohan-arthur** [comment]
This happens also when:
1. Go to view all datasources, and click the "new api" cta 
2. View single datasource, click "new api" cta

**Comment by kocharrahul7** [comment]
This issue is the same as [this](https://github.com/appsmithorg/appsmith/issues/11937) one. Can be tracked there
