### ISSUE TITLE
[Bug]: Reset the search in select widget after a value is selected

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#14469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i search for a value and select it within a select widget, then if i click once again the search text should be empty

### Steps To Reproduce

1. Add a new select widget
2. Search for a value and select it
3. Reopen the widget popover to see that the searched value is still there

### Version

Production

**Comment by vihar** [comment]
+1, came across the same issue when resetting my Select Widget and Multi-Select Widget.
