### ISSUE TITLE
[Bug]: Incorrect redirection from Omnibar

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#14477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On selecting a sample app from the omnibar on app.appsmith.com, it redirects to "Page not Found"
[Loom video link](https://www.loom.com/share/4008871d575844faa551ec2af62a131b)

### Steps To Reproduce

1. Open an app in app.appsmith.com
2. Type "run multiple queries" > It pops us a list of sample apps
3. Click on any sample app and it opens to a page saying "Page not Found"

### Version

Cloud - 1.7.2

**Comment by Nikhil-Nandagopal** [comment]
@arunvjn I can see the links in algolia are correct so I suspect it's a faulty change in the code

**Comment by Parthvi12** [comment]
Working fine on release.
