### ISSUE TITLE
[Bug]: Make sure all UQI component widths are consistent

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#14478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The widths on the dropdowns, entity selector, where clause, sort component and pagination component need to be aligned.

### Steps To Reproduce

https://user-images.githubusercontent.com/5298848/173289086-9a4b4071-9e6c-4fe0-b6f7-1db5e26734c8.mov

### Version

Deploy preview

**Comment by ayushpahwa** [comment]
Fixed via #15035
