### ISSUE TITLE
[Bug]: Git connection fails if missing certificate

### ISSUE THREAD

**Issue by vmatt** [appsmithorg/appsmith#14473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**I'd like to ask a switch on the UI to either enable to make insecure connections, or a possibility to add easily add Enterprise certificates.**

When I tried to connect to our GitHub Enterprise platform, the Web UI shows 500 Internal server error. In the logs, i found this
```
editor stdout | 17.168.57.172 - - [12/Jun/2022:14:59:39 +0000] "POST /api/v1/git/connect/62a08cd9e480796e0cdbeac6 HTTP/1.1" 500 128 "http://appsmith-ip/app/migration-app/medium-demo-62a4f2395ebcd86af11aa961/edit/jsObjects/62a5cd0f5ebcd86af11aa989" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"
editor stdout | 
editor stdout | 127.0.0.1 - - [12/Jun/2022:14:59:44 +0000] "GET / HTTP/1.1" 200 9362 "-" "curl/7.68.0"
editor stdout | 
editor stdout | 127.0.0.1 - - [12/Jun/2022:14:59:59 +0000] "GET / HTTP/1.1" 200 9362 "-" "curl/7.68.0"
editor stdout | 
backend stdout | userEmail=anonymousUser, sessionId=, thread=reactor-http-epoll-4, requestId=9785dcbe-882d-4ae9-aa84-d8ef347207f0 - [b69d06e8, L:/172.22.0.3:45186 - R:github.enterprise.com/enterprise-ip:443] The connection observed an error
backend stdout | javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

<img width="422" alt="image" src="https://user-images.githubusercontent.com/3168272/173239597-a77f181f-acf4-4988-b5c4-d9de986bc3a8.png">

### Workaround i tried (and failed):
1. Get your Root CA from you local machine.
2. Convert it to .pem format
`openssl x509 -inform der -in RootCA.cer -text -noout`
3. On the machine where you ran Appsmith container , copy vi to be able to edit files in the docker container
`sudo docker cp /bin/vi appsmith:/bin/vi`
4. Enter into the container:
```
sudo docker exec -it appsmith bash
cd /usr/lib/jvm/java-11-openjdk-amd64/lib/security
vi temp.pem
```
Paste your pem key here
`keytool -import -noprompt -trustcacerts -alias aliasname -file   temp.pem  -cacerts`
hint: Password for cacert keystore is "changeit"

But after importing cert, is still failing.

### Steps To Reproduce

1. Go to "Connect with Git (Beta)"
2. Add your Github Enterprise URL
3. Generate SSH key
4. Add SSH key on Github Enterprise
5. Click on Connect

### Version

Self Hosted - v1.7.1

**Comment by Nikhil-Nandagopal** [comment]
@vuiets @abhvsn could you have a look at what could be causing this?

**Comment by sharat87** [comment]
Hey @vmatt, Appsmith supports installing custom root CA certificates. The docs for how to do this weren't merged until now, which I just did. Please follow steps at https://docs.appsmith.com/setup/instance-configuration/custom-ca-root-certificate to make your root cert available to Appsmith server. Thanks.
