### ISSUE TITLE
[Bug]: Text is getting clipped when Italic Font style is used

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="196" alt="Screenshot 2022-06-13 at 3 07 10 PM" src="https://user-images.githubusercontent.com/83569920/173329286-b7aee79d-ac1c-44f7-a8f9-902761302bbd.png">

### Steps To Reproduce

1. Drag and drop a Table widget
2. Change the Text size
3. Select Italic Font style

### Version

Cloud

**Comment by somangshu** [comment]
@souma-ghosh lets identify and consult the solution with @sbalaji1192 before implementation

**Comment by souma-ghosh** [comment]
@sbalaji1192 I noticed this issue no longer exists in table v2. Should we implement the same solution for table v1?

**Comment by sbalaji1192** [comment]
@dilippitchika Yeah. we should. This issue is too simple to ask the user to upgrade to table v2.

**Comment by dilippitchika** [comment]
Yeah, please implement for v1 now
