### ISSUE TITLE
[Bug]: App Crashes when running a Select query that results in Empty table/No records [MySQL, Postgres]

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#14493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run a `MySQL` query with `IS NULL` syntax keeping the prepared statement turned off then the following unexpected behaviors are noticed in the local environment (release branch) and in the release.app.appsmith.com as well.

## Shows Oops both in local and release.app.appsmith.com

![Screenshot 2022-06-13 at 6 21 37 PM](https://user-images.githubusercontent.com/3524599/173352415-a655bf7e-d9c1-4d4e-a99b-f84af2b5bcb1.png)

## Broken Front-end only in local (release branch)

<img width="1365" alt="Screenshot 2022-06-12 at 12 56 18 AM" src="https://user-images.githubusercontent.com/3524599/173352498-f9d8ef05-d420-405b-9113-2dcf36c83bbd.png">

## Expected Behaviour found in app.appsmith.com

![Screenshot 2022-06-13 at 6 23 22 PM](https://user-images.githubusercontent.com/3524599/173352892-aa91efbe-9460-4fe3-8b07-6f4e743fd5f7.png)

### Steps To Reproduce

1. Create a `MySQL` datasource
2. Write a query containing IS `NULL` syntax where the query is not supposed to return any row because of no matching rows found in the table
3. You should see a page saying **Oops! Something went wrong** and later you will see some front-end source code that basically breaks the entire front-end (Happens to exist in the local environment on the release branch but **Oops** page appears in `release.app.appsmith.com` too)'

## Demonstration
[Loom Video](https://www.loom.com/share/d4fac848b5194d2b906d8d921bdd05cc)

### Version

Cloud / Self Hosted - v1.7.1

**Comment by Aishwarya-U-R** [comment]
Happens on Postgres DS too.

**Comment by Aishwarya-U-R** [comment]
https://user-images.githubusercontent.com/91450662/173360718-9b7e090a-e834-4c14-9c77-dc17da52e864.mov

**Comment by ayushpahwa** [comment]
Originated from PR [14274](https://github.com/appsmithorg/appsmith/pull/14274). Adding extra check.
