### ISSUE TITLE
[Bug]: Green highlight is displayed when new column is added in the table widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/df98d55906224004ab2aa3b8e2c685cc

### Steps To Reproduce

1. Drag and drop a table widget
2. Open property pane
3. Click on add new column
4. Observe that added column name is highlighted with green line

### Version

cloud

**Comment by yaldram** [comment]
Unable to reproduce this.
