### ISSUE TITLE
[Bug]: Discrepancy on files and their count in Filepicker widget when Tabs is being switched on Tabs widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we use filepicker widget on Tabs widget, the count of the files and actual visible files are not matching

https://www.loom.com/share/d9befde5009a463b88326882febcdbe3

### Steps To Reproduce

1. Add Tabs widget onto canvas
2. Add Filepicker widget onto Tabs widget
3. Add image & document viewer widget and bind the widgets with Filepicker
4. Add two supported files into filepicker to dispaly on image & document viewer
5. Now switch the Tabs to Tab1 and switch back to Tab2
6. Observe that Filepicker shows '1 files selected' but click on file picker and observe there is no file present

### Version

Cloud/Production

**Comment by dilippitchika** [comment]
@chandannkumar in the same app can you check one more thing for me -
Instead of step 5 in the above list of steps, go to a query or a JS object page and come back to the filepicker. 

Can you check if step 6 is still the same here?

**Comment by chandannkumar** [comment]
@dilippitchika Just checked the scenario as u suggested, the discrepancy on files count can be seen in this too

**Comment by dilippitchika** [comment]
Ok closing in favor of #11660
