### ISSUE TITLE
[Feature]: Make it easier to resolve the merge conflicts when user updates the any resource

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#14498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As per current DB structure actions are embedded inside the JSObjects. Every new method in JSObjects results in new action getting created in DB. Consider user updates the JSObject.myFun1 then user will have changes at 2 locations
- Queries directory under myFun1 file
- Body of JSObject1
We should not commit these duplicates and JSObject body should be committed as is. These steps surely makes it easier to resolve the conflicts even if occurs at same line.

Steps to resolve this issue:
- Don’t commit action body to queries/JSObject1-myFun1.json as this is not adding any value
- Keep the text as is and avoid stringifying the body of JSObject

Discussion thread: https://theappsmith.slack.com/archives/C02K2MZERSL/p1655105041401639

### Why should this be worked on?

This will enhance the merge conflict resolution which occurs for every JSObject update by quite a bit, and also it will reduce the number of occurrences to end up in these conflicts.

- [x] #18514
- [x] #18515
- [x] #18516
- [x] https://github.com/appsmithorg/appsmith/issues/19791

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6bu18)

**Comment by abhvsn** [comment]
@Nikhil-Nandagopal I was digging through this and wanted to comeup with alternate approach as newline is not supported by JSON:
https://stackoverflow.com/a/52557585/13092339

Considering the current limitations we can split the string into array and then serialize. The major issue here is we end up attaching `""` for each line. 
Output for ref:
```
 "body": [
      "export default {",
      "	myVar1: [],",
      "	myVar2: {},",
      "	myFun1: () => {",
      "		return \"appsmith\";",
      "	},",
      "	myFun2: async () => {",
      "		//use async-await or promises",
      "	}",
      "}"
    ],
```

Will this be good enough? I'm looking for more ideas here.

**Comment by abhvsn** [comment]
As per the discussion we have decided to use js files to store the code present in the JSObject.

**Comment by Gabriel-Azevedo** [comment]
Storing JSObjects as JS files would significantly improve the code review experience. 

My biggest problem as a tech lead is that pull request reviews for Appsmith basically became auto-approves to the point that we turned off the approval requirement to merge.
Readability is terrible and the process to un-stringify and diffing is such a hassle that it's almost impossible to convince the devs to do it.

Here's how it looks right now:

![Screenshot 2022-12-16 at 15 37 30](https://user-images.githubusercontent.com/9356226/208166375-71645101-8947-46d1-be99-bf344e1e55db.png)

So any solution to improve it would be highly beneficial and add a lot of value to one of the biggest draws to Appsmith for my company with is git sync
