### ISSUE TITLE
[Bug]: Camera widget in full screen not showing video or audio options available

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#14496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using Camera widget with full screen mode video and audio options are not getting displayed.

https://www.loom.com/share/1d3f2423826148da8ef0814a792ab0a6

### Steps To Reproduce

1. Drag and drop Camera widget
2. Click on arrow 🔽 near the camera icon
3. Observe options displayed to use as camera, try same with audio icon choosing "Video" property
4. Click on Full screen in the camera widget
5. Repeat step 2 and observe no options displayed

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working
