### ISSUE TITLE
[Bug]: Adding an existing user under "Manage users" shows success message instead of error message

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#14495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user try to add an existing user in "Manage users", user get message "The user has been invited successfully" but the user is not getting added (which is expected), but an error message is expected.

https://www.loom.com/share/bfdc600c2d404280b2ba9e47d4ab55da

### Steps To Reproduce

1. Click on meatballs menu (...) of the organisation
2. Click on Members
3. Click on Invite users
4. Enter email address which is existing and select any role and click on "Invite"
5. Observe user is no added but a success message is displayed "The user has been invited successfully"

Expected: "The user already exist"
Actual: "The user has been invited successfully"

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
@Sripriya93 this is because there is no value in telling the user that the user is already added. It's simply better to move forward
