### ISSUE TITLE
[Bug]: JS object is in an error state but no error is displayed on debugger or browser console

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JS object goes into error during execution but no error is displayed either on errors tab on the debugger or on browser console.

### Steps To Reproduce

1.  Go to JS object at [this](https://release.app.appsmith.com/app/scratch-pad/js-error-issue-62a7690dd901b06688ea14fb/edit/jsObjects/62a7690dd901b06688ea1513) location and run function `myFun1`
2. Observe the execution error 

### Public Sample App

https://release.app.appsmith.com/app/scratch-pad/js-error-issue-62a7690dd901b06688ea14fb/edit/jsObjects/62a7690dd901b06688ea1513

### Version

Cloud

**Comment by ohansFavour** [comment]
Two issues here

1. Errors found while executing a js function don't get logged in the debugger.
2. `myVar2: Input1.text.toString()` causes parsing of the js object to be wrong.
