### ISSUE TITLE
[Bug]-[91]:Drag and Drop Action in Firefox Returns Server Not Found Error

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#14506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user reported that when they open the **deployed view** of the application on **Firefox** if they select a text and drag and drop it with the mouse cursor somewhere on the page, the page shows loading, and the `Server not found` error page is shown. Here are some screen recordings that demonstrate the issue:

- https://user-images.githubusercontent.com/101268423/173676997-f40c4007-cde9-467f-90ea-722876ec97b0.mp4
- https://user-images.githubusercontent.com/101268423/173674656-c917094c-8b52-48a4-9c7c-5e2f90f2f7ad.mp4 

The issue is not reproducible on the Chrome and Edge browsers. It only happens on Firefox.

### Steps To Reproduce

1. Create a simple app and deploy it.
2. Select the text of a widget with the mouse cursor, drag, and drop it somewhere on the page.
3. Note that the page starts loading and a `Server not found` error gets displayed.

### Version

Cloud/Self Hosted

**Comment by dilippitchika** [comment]
@ame-appsmith the recording says not found, it's unclear from this description on what is happening. Can you please check?

**Comment by ame-appsmith** [comment]
> @ame-appsmith the recording says not found, it's unclear from this description on what is happening. Can you please check?

I have updated the recording link and also recorded an additional one: https://user-images.githubusercontent.com/101268423/173676997-f40c4007-cde9-467f-90ea-722876ec97b0.mp4

**Comment by dilippitchika** [comment]
Ok the only reason this happens in firefox is because we are able to drag the selected text in firefox, but this is not possible in chrome/edge browsers because the selected text is not automatically dragged.

The server not found error is shown because the dragged text is applied as a url in the page which then leads to an incorrect url thus showing server not found.

**Comment by somangshu** [comment]
their are quiet a few requests here. Do we have this prioritized? @dilippitchika @rohitagarwal88

**Comment by mohanarpit** [comment]
For good or bad, this is a feature of Firefox and not specific to Appsmith. Try opening https://www.google.com/ on Firefox. Then drag & drop a text from another window onto that tab. Firefox thinks it's a URL that should be opened and tries to redirect to that page. This doesn't happen on Chrome.

**Comment by AthiraVijayan21** [comment]
I think it need more clarification-" In Firefox if they select a text and drag and drop it with the mouse cursor **_somewhere on the page_,** the page shows loading, and the Server not found error page is shown." This is the issue..

Drag & drop a text from another window onto that tab,Firefox thinks it's a URL that should be opened and tries to redirect to that page. _ This is not ..!

**Comment by dilippitchika** [comment]
Dragging text, we cannot block but dropping text we can. @mohanarpit this is not causing an issue in appsmith dashboard but only in the apps as dropping a text in apps are causing them to be interpreted as urls. 

Reopening this issue. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 91 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@rohitagarwal88 i believe this is a canvas issue, can you please ask someone to triage this?

**Comment by rohitagarwal88** [comment]
@rahulramesha : Please triage this issue.
