### ISSUE TITLE
[Bug]: git import modal shows up unexpectedly

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#14507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you opened an application and open git-connect modal, and click back button, git-import modal shows up. It should not. 

---

Logic seems like:

```
if git-connect modal is open:
    if git-connect flow:
        something
    else
        open git-import
```

### Steps To Reproduce

1. Create a new application
2. Click git-connect
3. Click back button on browser 
4. See that git-import shows up.

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
Existing app scenario:

https://user-images.githubusercontent.com/1573771/173492114-abf4c04d-a5bf-45eb-9ad8-92f3643e4d7a.mov


New app scenario:

https://user-images.githubusercontent.com/1573771/173492173-f563931a-b109-44be-ae82-34958e941953.mov

**Comment by infinitetrooper** [comment]
Stale
