### ISSUE TITLE
[Bug]: Vertical Scroll Cannot Be Removed When Layout Should Fit to Page

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#14519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A vertical scroll bar is shown and cannot be removed when the layout/content should actually fit the page. 

Check this loom screen-recording:
https://www.loom.com/share/03866f8346c44167a20233baf5a149a8

### Steps To Reproduce

1. Create a new app and add some widgets. The layout should fit the page.
2. Note that the scroll is shown in both edit and deployed mode.

### Public Sample App

https://app.appsmith.com/applications/62a841c284b91337251a1411/pages/62a841c284b91337251a1414

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5ws98)

**Comment by dilippitchika** [comment]
Why doesn't the canvas auto-resize to occupy minimum width? What is the logic that we use today

@riodeuno can you help? How do we change the size of the canvas in the apps?
