### ISSUE TITLE
[Bug]: Menu button widget - when many menu options are added, no scroll, & the dropdown UI inconvenient to use

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add many menu options for a menu button widget, the UI of the dropdown is not convenient for the user, it extends and flows below the visual area. 
Also, on Deploy, when we click the Menu button, after the menu items are displayed, when we click the menu button again, the UI moves down, and focus goes to the menu items, instead of the menu getting closed.

### Steps To Reproduce

1. Drag and drop a menu button widget. 
2. Add say 15 - 20 menu options and check the dropdown 
3. It extends and flows below the visual area. 
4. Also, on deploy, the menu dropdown functionality is improper on click to close-  focus goes to the menu items, instead of the menu getting closed.
https://www.loom.com/share/40d22812c22b4532af0c60730308f84d

### Version

Production

**Comment by dilippitchika** [comment]
@btsgh closing this in favor of #12286, also adding the comments from you on the deploy mode there for tracking.

**Comment by btsgh** [comment]
@dilippitchika  - noted. Thanks
