### ISSUE TITLE
[Bug]: After app save action, the function selected in action dropdown changes leading to incorrect execution when using keyboard shortcuts

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there are multiple functions present in an object, the function selected in action dropdown changes whenever there's a saving action performed on the app and so when user is executing the function using keyboard shortcuts leads to incorrect functions being executed since the selected options change.

### Steps To Reproduce

1. Have multiple functions in an object as seen in the video attached and observe the current function selected on action dropdown.
2. Now modify any function and execute using keyboard shortcut `Ctrl + Enter` and observe the behaviour
3. Repeat the above steps for different functions and observe how the dropdown selection changes each time there's an app save action

https://www.loom.com/share/069392d0ad834210be5c6ad2c10adf52

### Version

Cloud

**Comment by bharath31** [comment]
not reproducible anymore
