### ISSUE TITLE
[Bug]: Select widget dropdown options look unfocused/hazy

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Select widget dropdown looks hazy/unfocused (text colour does not look the same as on other widgets of the select family) and this becomes more obvious when there are multi-worded options present in the dropdown

### Steps To Reproduce
Select widget:
![image](https://user-images.githubusercontent.com/79509062/173525705-4ac2ee72-59ed-4ebd-864c-0e4347b83962.png)

Multiselect widget: 
![image](https://user-images.githubusercontent.com/79509062/173814700-3f4c9f1d-078c-45c1-a5b4-fedea8b8a75e.png)

MultiTree Select widget:
![image](https://user-images.githubusercontent.com/79509062/173814839-7f04e40b-6a52-4db3-97ed-98986f36b895.png)

### Version

Cloud

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal updated the issue description with screenshots of the other select widgets for clarity

**Comment by dilippitchika** [comment]
Fixed this in select family reskinning
