### ISSUE TITLE
[Bug]: Disable drop down after the user selects a branch in git merge tab

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#14523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are not disabling the drop-down after the user selects a branch. We should block the user from making a different selection until the response for merge status is received from the server. This is inconsistent with other flows in git and it will result in unnecessary API calls for the same behaviour. 

### Steps To Reproduce

1. Open any git connected application and open git merge tab
2. Select one of the branch from the drop down 
3. Notice that drop down is not disabled and user can choose a different branch. 

### Public Sample App

any app

### Version

latest

**Comment by IAmAnubhavSaini** [comment]
This was fixed by https://github.com/appsmithorg/appsmith/pull/14540
