### ISSUE TITLE
[Docs]: Only Docs until version 1.3.0 is available on https://docs.appsmith.com/

### ISSUE THREAD

**Issue by tzahari** [appsmithorg/appsmith#14539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

On https://docs.appsmith.com/v/v1.3.0 documentation is only available up to version 1.3.0
Why are the versions > 1.3.0 are missing?

### Describe the improvement

Publish all versions up to 1.7.2

**Comment by Nikhil-Nandagopal** [comment]
@tzahari our documentation version does not reflect the product version so all the information in 1.3.0 should be relevant to the latest product version. We do know that some images are out of date and we're working on updating those :)
