### ISSUE TITLE
[Docs]: Process to upgrade to new Select Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#14533]
<p>Need to add corrosponding doc related to the warning `stay up to date` for switch widget</p>

**Comment by tzahari** [comment]
This would be helpful! Thank you

**Comment by jnikhila** [comment]
A generic how-to guide will be created as part of the ticket [Add doc/explainer video link to stay up-to-date alert for select widget] (#14462). Thus, closing this ticket.
CC: @dilippitchika / @pranavkanade
