### ISSUE TITLE
[Feature]: Increasing timeout on internal nginx

### ISSUE THREAD

**Issue by DanPhonovation** [appsmithorg/appsmith#14535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary
I have appsmith deployed via helm.

I see that there is an internal nginx proxying api calls to localhost:8080. I need to increase the timeout on this call past the nginx default of 60 seconds, but can't find an existing entrypoint to modify this.

Any way this can be part of a ConfigMap or recommendations on injecting something like: 

```
proxy-connect-timeout: "360"
proxy-send-timeout: "360"
proxy-read-timeout: "360"
```

into sites-available/default in the /api block (which proxies to localhost:8080)?

### Why should this be worked on?

Custom edge cases. For long running API tasks >60 secs this will generate a 504 Gateway timeout otherwise.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5wrpo)

**Comment by DanPhonovation** [comment]
For more clarity, I have a basic button-press UI that is calling a custom API performing a long running task. We have verified that indeed, it is appsmith's nginx issuing Gateway Timeout, and not our custom API. We did this by dropping into the appsmith pod and viewing nginx logs.

**Comment by ajwillia** [comment]
I'm also experiencing the same issue; have a REST API that is long running (90-200+ seconds).  I ended up implementing a temporary work-around by adding the following lines to nginx.conf and restarting nginx
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;

**Comment by DanPhonovation** [comment]
This sed will do the job if anyone wants to include it in their own Dockerfile:
```
sed '/location \/api {/a \    proxy_read_timeout 300;\n    proxy_connect_timeout 300;\n    proxy_send_timeout 300;\n    fastcgi_send_timeout 300;\n    fastcgi_read_timeout 300;' appsmith.nginx.conf
```

**Comment by heedfull** [comment]
Here is a screen shot of the issue, when running appsmith using the provided docker image
![image](https://user-images.githubusercontent.com/2331676/174295727-1a8dfb68-50ba-4fea-ad13-b40c6e313a0f.png)

**Comment by jackdmoloney** [comment]
Commenting to say I'm currently running into the same issue. Use case is a specific function likely only to run once every few weeks or so, but is expected to do a very large amount of operations. It currently takes 5-ish minutes to resolve from our API, but the page will always timeout after 1. The error shows the exact same as the screenshot above.

**Comment by shalomy-cyera** [comment]
I also have this issue and need this feature.
In my case, I'm waiting for a model to respond, this can take a couple of minutes. so chunking the data will not help.
