### ISSUE TITLE
[Bug] Update nginx config file for Linux platform to point to cloud api server instance by default.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#1453]
## Description

Change the Nginx config file for the client app to point to the cloud hosted release server by default on a Linux platform. 
https://github.com/appsmithorg/appsmith/blob/release/app/client/docker/templates/nginx-linux.conf.template 

1. Currently, the Nginx config file points to http://localhost:8080 by default. Hence, when only the client app is run on a local setup, it will not be able to find any backend server app. Need to change it to https://release-api.appsmith.com 

### Steps to reproduce the behavior:
1. Build and run the client app on a Linux setup.

### Important Details
 - OS: Linux

**Comment by mohanarpit** [comment]
Closing as duplicate of #1231 . Instead of hitting `release-api.appsmith.com` , we should enhance our setup process to bring up the backend server up as well via Docker.
