### ISSUE TITLE
[Docs]: JSON form limit (50)

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#14538]
<p>Data inside JSON Forms are not visible when they are more than 50 items long; it may help to document this fact to avoid users being confused if they run into this.<br /><br />Discord thread [here](https://discord.com/channels/725602949748752515/760761686549463060/962686856296816660)</p>

**Comment by jnikhila** [comment]
@dilippitchika - do we need to document this? CC: @Nikhil-Nandagopal

**Comment by dilippitchika** [comment]
Hey @jnikhila yes, we should add a section for this and what they can do if they encounter this limit. Let me write a draft and share it with you.

**Comment by jnikhila** [comment]
@dilippitchika - Did you get a chance to add pointers, so that we can pick this up?

**Comment by Pranay105** [comment]
@dilippitchika any update on this?

**Comment by dilippitchika** [comment]
Please find the first draft @jnikhila @Pranay105 https://www.notion.so/appsmith/JSON-form-limit-5d4ef6114f81454dabbc5fe0d60d55c5

**Comment by jnikhila** [comment]
Thanks, @dilippitchika. Could you please add it to the[ First Drafts page](https://www.notion.so/appsmith/First-Drafts-f8d0a91dfaa54524887b81e0392ea93d) on the notion for the Doc team?

**Comment by dilippitchika** [comment]
Done

**Comment by jnikhila** [comment]
Thanks @dilippitchika

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/help-and-support/troubleshooting-guide/widget-errors).
