### ISSUE TITLE
[Docs]: Document Forge external library

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#14542]
<p>We have external library [Forge](https://github.com/digitalbazaar/forge) available within appsmith, but it is not documented in our [External Libraries](https://docs.appsmith.com/core-concepts/writing-code/ext-libraries) docs page.<br /><br />somewhat related Discord thread [here](<a href="https://discord.com/channels/725602949748752515/760761686549463060/984839751938998323">here</a> where a user's question was solved by showing them that this was available.</p>

**Comment by pranavkanade** [comment]
We can delay this
