### ISSUE TITLE
[Docs]: Environment variable for disable Intercom is not correct

### ISSUE THREAD

**Issue by tzahari** [appsmithorg/appsmith#14541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/setup/instance-configuration/disable-intercom

### Describe the problem

On the page is documented that you need to set the environment to 
`APPSMITH_INTERCOM_APP_ID=`

I used this with the version 1.7.1 and the Intercom was still popping up.

After some research I found the correct setting seems to be:
`APPSMITH_DISABLE_INTERCOM=true`

I found this variable in the git repo: https://github.com/appsmithorg/appsmith/search?q=APPSMITH_DISABLE_INTERCOM

### Describe the improvement

Update the page with my provided information.

Thanks a lot

**Comment by Nikhil-Nandagopal** [comment]
@tzahari thanks! This has been updated

**Comment by tzahari** [comment]
Thanks for the fast update.
Maybe update also the first paragraph to:

`To disable Intercom on your instance, set the environment variable APPSMITH_DISABLE_INTERCOM to true.`

**Comment by Nikhil-Nandagopal** [comment]
Whoops! Fixed it 😀
