### ISSUE TITLE
[Bug]: MySQL query fails for having the "IS" word inside a comment in Prepared Statement

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#14544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there's an "is" word inside a comment in a `MySQL` query having the prepared statement turned on, the query fails with the following message 

> **"Appsmith currently does not support the IS keyword with the prepared statement setting turned ON. Please re-write your SQL query without the IS keyword or turn OFF (unsafe) the 'Use prepared statement' knob from the settings tab."**

<img width="1240" alt="Screenshot 2022-06-14 at 9 48 59 PM" src="https://user-images.githubusercontent.com/3524599/173621948-3e0d69b4-ce4c-41bd-a98f-b50233d05b63.png">

### Expected result
Comment is supported even in a prepared statement and here's an example of the expected result when the "is" word doesn't exist inside the comment

<img width="1244" alt="Screenshot 2022-06-14 at 9 48 33 PM" src="https://user-images.githubusercontent.com/3524599/173622265-468cd487-8f96-43b7-b167-a2a742cfb949.png">

### Steps To Reproduce

1. Create a MySQL datasource
2. Write a simple query having the "is" word inside a comment. For example,
```
SELECT 
* --Appsmith is awesome
FROM TABLE
```
3. The query should fail with the error message
> **"Appsmith currently does not support the IS keyword with the prepared statement setting turned ON. Please re-write your SQL query without the IS keyword or turn OFF (unsafe) the 'Use prepared statement' knob from the settings tab."**

### Version

Cloud / Self hosted- v.17.2

**Comment by appsmithguru** [comment]
RCA: the validation step is done before removing comments on the query statement.

Fix: Rearranging the steps: remove comments first then validate

**Comment by osama-fahd** [comment]
Hey guys, is the issue resolved yet? 
Because I'm getting the same error:

"error":"appsmith currently does not support the is keyword with the prepared statement setting turned on. please re-write your sql query without the is keyword"
