### ISSUE TITLE
[Feature]: Need Total Record Count field for Server-side pagination in List widget

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#14551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a user decides to use server side pagination in the List widget, it is unaware of how many records will be present.

### Why should this be worked on?

This causes issue where a user can keep clicking next page, and see List items which have undefined values.
We need a field like "Total Record Count" to be shown, whenever server side pagination is enabled, done similarly in Table Widget.

**Comment by jdglacier** [comment]
@Nikhil-Nandagopal Whether you add a "Total Record Count" or allow us to disable the next button some other way, something must be done here. As it stands, I simply cannot use this widget if I have a variable number of list items and server-side pagination is enabled.

**Comment by dilippitchika** [comment]
Updated PRD - https://appsmith.notion.site/Total-record-count-acd4b22cb4604dc0bb60d382c0796372

**Comment by shastryblr** [comment]
Design has been shared [https://www.figma.com/file/h1fOWB98oe2o4tHpTsh7X0/List---Total-record-count?node-id=29%3A1253&t=7xUh5Cx6ALoETsQv-1](url)

**Comment by dilippitchika** [comment]
Assuming 50% list users need this at some point
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 750 |
| Effort (months)  | 0.5 |
