### ISSUE TITLE
[Bug]: Incorrect code is executed in an if-else block regardless of conditions

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Consider the below code, only the first chunk of code in the if-else block is executed regardless of there not being a logical match, i.e. page always redirects to a different page regardless of what the selected value is.

```
if (Select2.selectedOptionValue = "Page navigation") {
	navigateTo('Navigated Page')
}
else if (Select2.selectedOptionValue = "Widget navigation") {
	navigateTo('#ywc7thfwfa')
}
else if (Select2.selectedOptionValue = "Tab navigation") {
	navigateTo('#fc3l3b6pjd')
}
```

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/scratch-pad/automation-test-cases-62987963c43c3d0bd6572185/edit/jsObjects/629b73794a296f2606c790a0) location
2. Go to the select widget present in `Automation TC2` container and change the options and observe the behvaiour. No matter what the selection is, the app is always redirected.
3. Now comment out the first block of code to disallow page navigation, now change option selected on observe that user is still navigated to a different page inspite of commenting out that code

[App link on release](https://release.app.appsmith.com/app/scratch-pad/automation-test-cases-62987963c43c3d0bd6572185/edit/jsObjects/629b73794a296f2606c790a0)

[App link on prod](https://app.appsmith.com/applications/62428ae4c99df2369931af4b/pages/62a97afa84b91337251a6a80/edit)

https://www.loom.com/share/0bebfb28ed614c158313f762551eb6ac

### Public Sample App

https://release.app.appsmith.com/app/scratch-pad/automation-test-cases-62987963c43c3d0bd6572185/edit/jsObjects/629b73794a296f2606c790a0

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami it should be == not =
