### ISSUE TITLE
[Bug]: The RSA key generation was not available. for the new application is tried to connect

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The RSA key generation was not available. for the new application is tried to connect
![image](https://user-images.githubusercontent.com/45958978/173799768-7ecc268e-5628-4f29-9c37-4e8011f92c9e.png)

### Steps To Reproduce

1. Add a new app
2. Click on connect git button
3. add the azure remote url
4. Now in ssh key section click on 3 dot icon to generate new key 
5. The RSA key is not displayed

### Version

Deploy preview

**Comment by IAmAnubhavSaini** [comment]
@AnaghHegde is working on this. We need a new API that will return only the key types.

Ref: https://github.com/appsmithorg/appsmith/issues/14563

**Comment by IAmAnubhavSaini** [comment]
This will be taken care by https://github.com/appsmithorg/appsmith/pull/14383

**Comment by IAmAnubhavSaini** [comment]
Done.
