### ISSUE TITLE
[Bug]-[632]:Incorrect example structure shows showMessage on trigger field, copying this text leads to incorrect handling by the platform

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Example structure on trigger field incorrectly shows showAlert as showMessage and using this snippet causes unexpected behaviour where the snippet gets truncated on triggering the widget and throws an error message.

### Steps To Reproduce

1. Drop any widget on the canvas and select any trigger field from the action selector dropdown
2. Go to the example structure of the trigger field and copy-paste it into the field as seen in the video
3. Trigger the widget action field and observe the error as seen in the video and also observe the text being truncated.

![image](https://user-images.githubusercontent.com/79509062/173770159-d1be7325-cd2d-4388-9888-016ad13483e3.png)

https://www.loom.com/share/7b5fa72373e447079722a8396c90f127

### Version

Cloud

**Comment by rohan-arthur** [comment]
WIDGET_PROPERTY_UPDATE, updatedValue contains `showMessage(`, over 6 months: 316

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 316 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
@satbir121 this seems like a quick fix

**Comment by rimildeyjsr** [comment]
This is being fixed as part of AST refactors
