### ISSUE TITLE
[Bug]: Variables that have just been defined on an object does not return expected values, only refreshing the page returns expected value

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a widget property is assigned to a variable on a JS object, then the value is not correctly returned as seen in the video attached

### Steps To Reproduce

1. Drop various widgets onto the canvas and assign their internal properties to variables in a JS object
2. Display these as soon as they are defined in a showAlert and observe that these variables don't appear on the showAlert until the page is refreshed.

https://www.loom.com/share/0500c9ffe2e24e01bf3506daca686b9a

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6a9jg)

**Comment by ApekshaBhosale** [comment]
this is expected behavior as we are treating them as constant values and will be applied once application is loaded.  @ramsaptami

**Comment by ramsaptami** [comment]
But it doesn't make sense when we assign a global variable (localized to the object) a widget value like: `value: Select1.selectedOptionLabel` and it's only on page refresh that this `value` is read/updated. But select widget's modified value can never be assigned to this variable.

The scenario above is simple when it's a direct widget value assignment, but when we have conditional statements then the variable will never hold dynamic value. Example: `value: Input1.text ?? Select1.selectedOptionValue` will always hold one value no matter the changes made on the canvas since it will always revert to the default evaluated value of this expression on page refresh and stay that way.

CC: @Nikhil-Nandagopal @satbir121

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale this seems to be the case of reactive variables right?

**Comment by bharath31** [comment]
@Rishabh-Rathod @rimildeyjsr FYI. This is the refresh issue we were discussing yesterday.
