### ISSUE TITLE
[Bug]: Saving an api as datasource throws 'Duplicate key error' intermittently

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#14566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is observed in cypress test `OAuthServiceValidation_spec.js` on saving an api as datasource throws error intermittently making the test flaky.

<img width="1434" alt="Screenshot 2022-06-15 at 2 14 41 PM" src="https://user-images.githubusercontent.com/80334441/173794456-dc9ec272-b973-4b5c-9f47-d74b038c9b9a.png">

### Steps To Reproduce

These are the steps followed in cypress test:

1. Create an api "https://oauth.mocklab.io/userinfo"
2. Click on Save as datasource
3. Error pops up sometimes.

### Version

Release

**Comment by rohan-arthur** [comment]
haven't seen this specific flaky behaviour, please reopen if the issue still exists.
