### ISSUE TITLE
[Bug]: If the Azure contains brackets in Remote URL then the URL is considered as invalid in spite of being valid

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the Azure contains brackets in Remote URL then the URL is considered as invalid in spite of being valid
<img width="630" alt="image" src="https://user-images.githubusercontent.com/45958978/173801277-4b8acf11-7759-41a4-954b-d4f0f56fef53.png">

### Steps To Reproduce

1. From home page
2. click on 3 application setting
3. click on import menu
4. click on git import
5. add azure remote url which has brackets
6. verify the display oferror message

### Version

deploy preview

**Comment by IAmAnubhavSaini** [comment]
@vuiets Do we want to support `()` in repo URL?

**Comment by vuiets** [comment]
Sure, from the looks of it Azure supports it in URLs. Any downsides to doing this?

**Comment by IAmAnubhavSaini** [comment]
Done.
