### ISSUE TITLE
[Bug]: Clicking on the dropdown icon on tree select widgets causes app navigation to the top of the canvas

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking on the dropdown icon on tree select widgets causes app control app navigation to the top of the canvas. This happens on view and edit mode of an application

### Steps To Reproduce

1. Drop a tree-select & multi-tree select widget at the bottom of a long page
2. Click on the icon dropdown to view options
3. Observe that app control navigates users to the top of the canvas and that the user has to scroll back down to the widget to see its expanded options tray. This happens once each time the application is loaded and the options tray is accessed.

https://www.loom.com/share/8b02a78a8f994242b9e23bdba97ad85a

### Version

Cloud

**Comment by dilippitchika** [comment]
@vivekverma2312 can you check this once? i thought Tolu's recent PR fixed this.

**Comment by chandannkumar** [comment]
@dilippitchika It is observed that the issue still exists, as i can see the same issue was fixed at #11485

**Comment by dilippitchika** [comment]
Thanks Chandan, closing this in favor of #11485
