### ISSUE TITLE
Check available space before taking a backup

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#14573]
If we can estimate the final size of the backup archive, we can use that to check if there's available space before attempting to take the backup. If not, let's do a check like at least min(10%, 5GB) of free space is available before proceeding.

**Comment by sum35h** [comment]
As a part of the issue, I will also be setting up backup error logs at `/appsmith-stacks/logs/backup/error.log` , and  also sending out an error mail to the admin in case backup operation fails.
