### ISSUE TITLE
[Enhancement]: Style options missing for Button, Icon Button and Menu button column types

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#14588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The Table widget has style properties for all column types except the Button, Icon Button and Menu Button column types. 

The missing ones are

- Text Align
- Text Size
- Font Style
- Vertical Alignment
- Text Color
- Cell Background

Alignment options should be also present in Audio and Video type

### Why should this be worked on?

For consistency across all column types on the table widget

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_57n2k)

**Comment by dilippitchika** [comment]
Closing as this will be fixed in #10278
