### ISSUE TITLE
[Bug]: App crashes when query returns 0 rows

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was not able to reproduce this, but a couple of users have reported issues with their apps crashing when they run a query that returns 0 rows. 

[forum link](https://community.appsmith.com/t/mysql-query-that-returns-empty-table-results-in-error-screen/1084/9)

things to note:
1. user is on self hosted version 1.7.2

### Steps To Reproduce

1. Create a query on MySQL table, such that there are 0 rows expected to be returned. For example, `select * from class where id = 100`, and ensure that the table `class` does not have a row that has `id` as `100`
2. Run the query
3. --> app crashes
4. Now whenever I try to navigate to the query on the app, I encounter the crash
5. Go to the database and create a row with `id` as `100`
6. Now the crash is gone

### Public Sample App

waiting for the user to share access to their app

### Version

self hosted

**Comment by AmanAgarwal041** [comment]
Closing this issue as the fix for this is already merged into release.
Similar Issue: [14493](https://github.com/appsmithorg/appsmith/issues/14493)
Linked PR: [14502](https://github.com/appsmithorg/appsmith/pull/14502)
