### ISSUE TITLE
[Bug]: Able to nest Modal widget inside containers while pasting in a group

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#14608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Modal widget should always exist on the main Canvas and should never be inside containers.

When pasting a modal widget while a Container widget is selected will paste the modal widget in the main canvas instead of a container. But, when the modal widget is copied in a group with other widgets, and a container widget is selected it pastes all the widgets including the modal widget inside the Container Widget

### Steps To Reproduce

1. Drag a modal widget, container widget and some other widgets on canvas.
2. press cmd + A to select all the widgets including modal widget.
3. press cmd + C to copy all the widget along with modal widget.
4. select only the container widget.
5. press cmd + V to paste all the widgets.
6. Observe that the modal widget is also pasted inside the container widget

expected behaviour,
Modal widget should always paste on the main canvas

### Version

Cloud/ Self-Hosted

**Comment by btsgh** [comment]
Tested on release and found to be working correctly.
