### ISSUE TITLE
[Bug]: Sometimes, the user isn't able to see the run button in the onboarding

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#14614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When certain users do the user onboarding, they do not see the red run button. It does not load in for all users

### Steps To Reproduce

Not easily replicable, will add recordings if we can identify them

### Version

1.7.1 cloud

**Comment by hiteshjoshi** [comment]
This is not reproducible.
