### ISSUE TITLE
[Bug]: Cyclic dependency issue observed for an API query 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A cyclic dependency issue has cropped up postfix for #14599 for API query that has not been configured as a datasource. All widgets on the canvas are glitching up because of this cyclic dependency issue

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/scratch-pad-1/iframe-62ab69165f88750016a6cee8/edit) location and observe the cyclic dependency error show up on page load

https://www.loom.com/share/b2c533ea1a034fa480c62a7a110ee896

### Public Sample App

https://release.app.appsmith.com/app/scratch-pad-1/iframe-62ab69165f88750016a6cee8/edit

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami is this still reproducible? wondering if this was fixed as a part of the larger cyclic dependency epic

**Comment by ramsaptami** [comment]
Closing this since original app does not exist. Tried to import the app and this app does not throw any error on page load
