### ISSUE TITLE
Add tooltips,subtext and placeholders in the query screen - Airtable Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#14611]
Recently, was implemented the functionality of being able to add a tooltip and subtext to dynamic variables, so Airtable's variables will be updated as well.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/a6b8f045-4850-4db5-a797-de5247eedc61)

**Comment by felixsuarez0727** [comment]
The proposed changes to the Airtable tooltips, subtitle and placeholder can be reviewed in [EngSpec ](https://www.notion.so/appsmith/Airtable-Integration-EngSpec-b771ed93f6eb447ab8a824673754b719) , please make any necessary observations.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/2bd66595-807e-4b3a-9129-24c9a89bffee)

Note: Changes have to be reviewed from the EngSpec since currently any change on the SaaS App will go directly to production. Any suggestions on how to improve this process are welcomed.

**Comment by nidhi-nair** [comment]
Engineering spec looks good to me. We can go ahead with this.

**Comment by felixsuarez0727** [comment]
Added tooltips and subtext to Airtable instance

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/ab66436c-007b-453a-b60c-1e7e3c11f601)
