### ISSUE TITLE
[Bug]: Dummy data is displayed in the Access control section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dummy data is displayed in the Access control section
<img width="994" alt="image" src="https://user-images.githubusercontent.com/45958978/174245750-56fd35e8-0df0-4be9-9634-5d7098a2b266.png">

### Steps To Reproduce

1. Pull the ee release
2. login with appsmith id
3. The access control section will be displayed
4. The Tabs contains the dummy data here

### Version

release

**Comment by ankitakinger** [comment]
This is expected. These screens have been implemented with dummy data. We will be updating this once APIs are ready so we can integrate the FE with the same.
