### ISSUE TITLE
[Bug]-[166]:User gets "Actions" & "Events" (duplicate) sections in the Property Pane which save the same purpose

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are two issues:

1. A user is able to see both `Actions` & `Events` sections in the `Property Pane` for `TreeSelect` & `MultiTreeSelect` widgets which save the same purpose of providing the user with `onOptionChange` property. This can be confusing for the user as both have the same usage.
2. There is a naming inconsistency in the above section. For some widgets like `Button` widget we see the section named as `Events` and for `Button Group` widget it is named as `Actions`. 

Please have a look at the below video for clarity:
https://www.loom.com/share/feb9262bb7f343bb88a4bed2bf0c24b8

### Steps To Reproduce

1. D&D a `TreeSelect` or a `MultiTreeSelect` widget.
2. Go to the Property Pane and observe.

The user sees both `Actions` & `Events` sections in the `Property Pane`. 

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 83 |
| Effort (months)  | 0.25 |

**Comment by shadabbuchh** [comment]
> @shadabbuchh what happens when you trigger events? Which one works is it actions or events or both? Can you verify that for me once, I can get it fixed urgently.

@dilippitchika both `Events` & `Actions` work in the same way.

**Comment by dilippitchika** [comment]
Thanks, @techbhavin please remove the `Actions` group here and keep the `Events` group

**Comment by Tooluloope** [comment]
@dilippitchika We could just remove them in all widgets.
Button Group.
Camera
Currency Input
Input
JSONForm and All Field Types
MapChart
All Selects
Phone Input
Switch Group
These are all the Widgets that uses Actions instead of Events

**Comment by dilippitchika** [comment]
@Tooluloope  we are fixing this in property pane project aswath is working on. Here the problem is that this is a duplicate which got added.

**Comment by dilippitchika** [comment]
Idk why this is moved back to in progress. The scope of this issue is - 
For the widgets which have both actions and events (which is a bug) like mentioned above, we will only keep events and remove actions. 

NOT IN SCOPE - Other widgets where it's called actions, we will rename it to events as part of property pane project.

**Comment by techbhavin** [comment]
@dilippitchika @somangshu  
Here Deployment Preview is Broken so QA is not able to test this PR, that is why it is in In Progress

**Comment by btsgh** [comment]
Tested the areas as mentioned in the video by @shadabbuchh. User can see only Events now, and also, the naming inconsistency between button and button group is resolved. At both places its Events.
