### ISSUE TITLE
[Bug]-[547]:Table row selection to be visibly shown/highlighted when Cell background applied too

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#14635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/174277283-86f6b6cd-72b3-43eb-bbbc-f11ef0d94dbc.mov

### Steps To Reproduce

1. Drag drop a table widget onto canvas
2. Map some data for display
3. Apply cell background colour for all columns
4. Deploy & Select some random rows
5. **Observe : Row selection is not shown/highlighted**
6. **Expected: Selected Row should be highlighted on top of the colours to confirm user of his click action**

### Version

Prod/Release v1.7.4

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 547 |
| Effort (months)  | 0.5 |

**Comment by sbalaji1192** [comment]
Selected row background and hover background are applied at the row level, while cell background is applied at the cell level. Hence the cell background overrides the row background.
@dilippitchika We need to address hover color as well, right?

**Comment by jsartisan** [comment]
Fixed in #17228
