### ISSUE TITLE
[Bug]: Issues related to tooltips in the app

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Following are issues related to the tooltip component throughout the app:

1. The content of the tooltip when user tries to add more than 4 nested where condition groups is not proper.
<img width="1003" alt="Screenshot 2022-06-17 at 4 07 16 PM" src="https://user-images.githubusercontent.com/39921438/174282623-3ba2fa25-eaae-429c-8960-fac7d11f74ef.png">

Since we are allowing only 3 where condition groups, shouldn't the tooltip be "For S3 only 3 nested where condition groups are allowed" instead of the above?

2. The tooltip gets truncated while hovering over a long page name in a deployed app.
<img width="246" alt="Screenshot 2022-06-17 at 4 16 32 PM" src="https://user-images.githubusercontent.com/39921438/174284045-3e1b6bd1-1e42-4d39-8cd1-7244ab06c1e6.png">

3. Upon pressing `Tab` on the keyboard, some of the tooltips do not appear like they do when the user hovers over the icons manually using a mouse.
4. The user does not get a tooltip while hovering over a long API name.
https://www.loom.com/share/0f610df2bd7c443cb5e2dffdb0e255b2

5.Tooltip for JSObject without any function is truncated.
<img width="538" alt="Screenshot 2022-06-17 at 4 23 07 PM" src="https://user-images.githubusercontent.com/39921438/174284845-130db8ac-39b1-4f1a-a9c0-8485eb8bc70c.png">

6. If a `Rating` widget has a `Max Rating` of more than 5, the tooltip does not appear for the rest of the ratings. (Should this be treated as a bug?)
https://www.loom.com/share/9d83bc5c0618494cafd9e4a1f4e900e4

7. Design Inconsistency: The tooltip for `Troubleshoot issue` and while multi selecting widgets does not have the arrow/speedbump.
<img width="601" alt="Screenshot 2022-06-17 at 4 27 18 PM" src="https://user-images.githubusercontent.com/39921438/174286364-4ad849dc-0d57-4b8a-9eb8-ebde5f78ac0e.png">
<img width="345" alt="Screenshot 2022-06-17 at 4 27 27 PM" src="https://user-images.githubusercontent.com/39921438/174286373-00f9c685-dfde-4128-a2e1-e3dcaef56ea9.png">

Also for multi select widget tooltip why are we showing the paste option in the tooltip for copy & cut ?

8. No tooltip displayed for the `!` icon.
<img width="357" alt="Screenshot 2022-06-27 at 11 45 48 AM" src="https://user-images.githubusercontent.com/39921438/175872695-b399a372-2726-4327-8e55-b543c5c5614b.png">

9. At several places throughout the app e.g. `Relationships entity hover`, `notification bell icon`, `Account avatar` etc. there is a delay in displaying the tooltip.
10. The git branch name icon does not have a tooltip.
<img width="181" alt="Screenshot 2022-08-24 at 11 03 01 AM" src="https://user-images.githubusercontent.com/39921438/186337036-a61c0b5a-6dee-4eb3-9c58-4afe4edb5413.png">

### Steps To Reproduce

Check the tooltips all over the app.

### Version

Cloud

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
