### ISSUE TITLE
[Bug]: Browser console shows canvas widget is undefined

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Browser console throws an error for missing default and meta properties of list widget when bound data has not been run yet. This has the potential of creating confusion with users and needs to be removed.

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/earworm/list-widget-issue-62acb61f78c5ed4cdfd8d9a0/edit) location
2. Open up the browser while the app loads and observe the errors as seen in the screenshot below

![image](https://user-images.githubusercontent.com/79509062/174347846-e1d80730-2427-4dcd-bf2d-5b3b22a578dd.png)
![image](https://user-images.githubusercontent.com/79509062/174347981-93cef024-f6b8-4c1e-ab23-41679919e748.png)

### Public Sample App

https://release.app.appsmith.com/app/earworm/list-widget-issue-62acb61f78c5ed4cdfd8d9a0/edit

### Version

Cloud

**Comment by dilippitchika** [comment]
@ramsaptami can you check this once? It seems this issue has closed

**Comment by ramsaptami** [comment]
Issue with the list widget seems to have been fixed but there's something showing up for the canvas widget @dilippitchika 
![image](https://user-images.githubusercontent.com/79509062/195857613-996bffba-b8f0-4694-bcf5-297fcf09af4d.png)

**Comment by dilippitchika** [comment]
@aswathkk can you check this once? Updating the issue.

**Comment by yaldram** [comment]
This error is thrown on line `224`, `WidgetFactory.tsx`. I think - all Containers have a `Canvas` widget inside of them. And we don't have a `propertyPaneConfig` for the canvas widget, maybe we don't log this error if the Widget type is `CANVAS_WIDGET`.

**Comment by dilippitchika** [comment]
Yes @yaldram looks like we have to add it in log blacklist
