### ISSUE TITLE
Fix the problem of deselecting rows in the action table in Saas Integration Manager

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#14656]
When a row of the table is selected it is changed to the first row always

The following video shows the error

https://images.zenhubusercontent.com/275993885/b7be6c57-e580-43dd-a946-2e40dc6cce8d/video2994857732.mp4

Possible error:

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/d7cb603c-a415-42db-a0e4-7038df2f819b)

I should investigate how to keep the row that is selected until I click on another.

**Comment by AmanAgarwal041** [comment]
The action table seems to be working fine. Hence, moving this issue to needs qa.

**Comment by prapullac** [comment]
@felixsuarez0727 : Unable to test this as the Saas Manager App - API Manager Page - displays an error (Page does not get loaded )

**Comment by felixsuarez0727** [comment]
Moving to Blocked PR.
