### ISSUE TITLE
[Bug]: Consecutive storeValue calls don't work and only the first call is executed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Consecutive `storeValue()` does not work anymore - regressed issue. Only the first call goes through

### Steps To Reproduce

1. Use consecutive `storeValue()` bound either in a widget JS or in a `promise.all()` and observe that the code fails and saves only the first `storeValue()` call

https://release.app.appsmith.com/app/scratch-pad/iframe-629d9ca4b1677a11502ab3e2/edit

### Public Sample App

https://release.app.appsmith.com/app/scratch-pad/iframe-629d9ca4b1677a11502ab3e2/edit

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
This doesn't seem to me an issue, until it was working earlier.

#### Code used in the application
```js
{{storeValue('imageApi','https://dog.ceo/api/breeds/image/random')
storeValue('factsApi', 'https://dog-api.kinduff.com/api/facts')
.then(() => {
	petStuff.run()
	petFacts.clear()
})
}}
```

#### Ideal implementation 

- Promise chain

```js
{{
storeValue('imageApi','https://dog.ceo/api/breeds/image/random').then(() => {
   return storeValue('factsApi', 'https://dog-api.kinduff.com/api/facts')
     .then(() => {
	petStuff.run()
	petFacts.run()
      })
      })
}}
```

- With Promise.all()

```
{{Promise.all([storeValue('imageApi','https://api.thecatapi.com/v1/images/search'),
storeValue('factsApi', 'https://catfact.ninja/fact')]).then(() => {
	petStuff.run()
	petFacts.run()
})
}}
```

**Comment by ramsaptami** [comment]
Including another [app's object](https://release.app.appsmith.com/app/earworm/debugging-page-62a32578f4e3980741ff56e2/edit/jsObjects/62a32578f4e3980741ff5760) where the promise code was working previously, but now only saves the first store value

Code:
```
let tokens = [
	storeValue('authToken', response.access_token),
	storeValue('refreshToken', response.refresh_token)
]
return Promise.all(tokens)
	.then(() => {	
		console.log("Auth code in store is " + appsmith.store.authToken)
		console.log("Refresh token in store is " + appsmith.store.refreshToken)
	})
	.catch((err) => {return showAlert('Could not store tokens in store ' + err.toString())})
```

Response:
![image](https://user-images.githubusercontent.com/79509062/174345233-fac2feed-0b5f-4e15-8cd6-03ffb16fed4a.png)

**Comment by Rishabh-Rathod** [comment]
Yes, this seems like an issue where `Promise.all(tokens)` didn't wait for all promise to resolve.

Steps to reproduce 
1. Click on `appIcon` to authorize
<img width="393" alt="Screenshot 2022-06-18 at 3 02 12 AM" src="https://user-images.githubusercontent.com/23132741/174403851-0fc82829-16e6-45ea-9a17-99fe368a8c1b.png">

2. Check logs.
3. To again reproduce, clear store and repeat step 1
<img width="282" alt="Screenshot 2022-06-18 at 3 21 04 AM" src="https://user-images.githubusercontent.com/23132741/174405608-3671d0b6-1532-4bf7-89ab-738726572f1c.png">

- Request token does get stored but Promise.all() didn't work as expected.

![SCR-20220618-4eh](https://user-images.githubusercontent.com/23132741/174405372-5d79f12a-47d6-4172-8528-2999b7e2ab6a.png)

#### Other observations

- When i added a API call inside promise.all

```js
let tokens = [
  storeValue('authToken', response.access_token),
  storeValue('refreshToken', response.refresh_token),
  singlesFetchQuery.run()
  ]
```

Code started working as expected. 
![image](https://user-images.githubusercontent.com/23132741/174407541-1ac344fe-8cc6-4b33-8f24-e1600487675b.png)

This makes me believe that 
- when we ran 1st storeValue, we resolved all promise related to storeValue. Hence, we didn't actually waited for `storeValue('refreshToken', response.refresh_token)`
