### ISSUE TITLE
[Bug]: onPageLoad Action not running on load ( onLoad )

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Discord user loom recording - https://www.loom.com/share/036a7d6106a1460eb0e4730f25d68cb6

Discord user message - https://discord.com/channels/725602949748752515/986691843343384596/986878259629269002

![SCR-20220619-un6](https://user-images.githubusercontent.com/23132741/174491418-c6f908a5-088b-482f-a190-fbbd29a46390.png)
![SCR-20220619-uoj](https://user-images.githubusercontent.com/23132741/174491421-7824ac7c-b04f-4043-b919-6d2d98f6d6fe.png)

- User is using git sync feature

### Steps To Reproduce

Unclear

### Version

1.7.4

**Comment by rohan-arthur** [comment]
internal conversation [here](https://theappsmith.slack.com/archives/C02KTH6EHUG/p1655699933845749?thread_ts=1655695490.700909&cid=C02KTH6EHUG)

**Comment by nidhi-nair** [comment]
Closing this issue till we have more clarity around the requirement here.
