### ISSUE TITLE
[Bug]: Same app opens up in a new tab instead of the git repo on Open Repo button click

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#14674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/174563639-49bef866-d8be-4934-9024-5e56de296cb9.mov

### Steps To Reproduce

1. Go to an app connected to git which has merge conflicts
2. Error modal opens with Open Repo button
3.  Click on the button and observe

### Version

Release

**Comment by IAmAnubhavSaini** [comment]
@Parthvi12 I am not able to reproduce this. Let's have a call tomorrow.

**Comment by IAmAnubhavSaini** [comment]
@Parthvi12 I am not able to reproduce it. Please provide more details.

**Comment by Parthvi12** [comment]
@IAmAnubhavSaini  to reproduce this error :
1. Go to github repo and change something ex: query name from Query1 to Query2
2. Change the query name from app as well Query1 to Query3
3. Commit the changes and it will show  message to pull the remote changes.
4. Close the modal and click on pull changes icon, it should open the modal mentioned in the issue

Let me know if you are still having trouble reproducing this.

**Comment by IAmAnubhavSaini** [comment]
@Parthvi12 Where did it used to come?
