### ISSUE TITLE
[Bug]: Phone & currency Input widget Popup breaks on wrong search text in popup filter

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we do quick search on popup that appears to change country code/currency, the popup breaks when we do wrong search instead of showing 'No results'

https://www.loom.com/share/e876c382aedf47eb9b349d9ef7b19245

### Steps To Reproduce

1. Add Phone Input/Currency Input Widget onto canvas
2. Enable Change Country Code/Currency option from property pane
3. Now search with wrong input in the popup of change country code/currency
4. Observe that popup disappears as soon as we add wrong text in the search input

### Version

Cloud/Production

**Comment by Sripriya93** [comment]
Have verified phone and currency input widget with invalid values, moving to done.
