### ISSUE TITLE
[Bug]: deployed info is not displayed on the deploy tab in the git import flow.

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 the deploy link doesn't display on git import when user has just imported and there is nothing to commit

### Steps To Reproduce

1. Import a git connected app
2. click on deploy tab 
3. the deployed link is not displayed

### Version

Deploy preview https://appsmith-git-fix-13642-get-appsmith.vercel.app/app/potential-guide/page1-62b00fee78c5ed4cdfd8e1a2/edit?branch=master

**Comment by IAmAnubhavSaini** [comment]
@abhvsn When we git import an application is it deployed automatically like an app is deployed on commit?

**Comment by abhvsn** [comment]
@IAmAnubhavSaini yes that's the expectation.

**Comment by IAmAnubhavSaini** [comment]
This has been fixed in https://github.com/appsmithorg/appsmith/pull/14597

See:

https://user-images.githubusercontent.com/1573771/174010973-e9e3e2ed-8cfc-4092-b1bf-2d0a20414d11.mov
