### ISSUE TITLE
[Bug]: Content type prioritisation and auto inclusion in header for API body types

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#14675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Addition of content type header on 
> 1. Change of body tabs 
> 2. Prioritisation between user added and auto added content type

is not working as required(ref: Postman)

Addition of related body types to the request also works differently compared to Postman.

Postman
1. Addition of content type header and sending its respective body. https://www.loom.com/share/342d4fd187484f47b6c6a0e36be5fcf7
2. Prioritisation of user content type vs auto added content type along with body. https://www.loom.com/share/bcd54a49759b45c0bdb1c63c087cf0c8

### Version

1.7.4

**Comment by alienfacepalm** [comment]
^^^ This breaks workflow with Launch Darkly API.

**Comment by sribalajig** [comment]
Deprioritising for now as we are already addressing this as part of #18473
