### ISSUE TITLE
[Bug] Github social login on app.appsmith.com misses https

### ISSUE THREAD

**Issue by k0rn1** [appsmithorg/appsmith#1468]
## Description
If I try your demo on https://app.appsmith.com/ and try to login with github, the redirect url misses `https`.
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to https://app.appsmith.com/user/login
2. Click on _Sign in with Github_
3. Redirect url starts with _http://app.appsmith.com:443/login/oauth2/code/github..._
4. Prefix browser url with `https://`

### Important Details
 - Version: Cloud
 - OS: Linux Arch rolling
 - Browser chrome

**Comment by Nikhil-Nandagopal** [comment]
@k0rn1 thank you for reporting this!
@mohanarpit can you have a look here and see how this negatively affects the login flow?

**Comment by mohanarpit** [comment]
@k0rn1 This should be resolved now. Can you please confirm? 

The issue was that in our cloud environment, we migrated to use the AWS ALB and our servers weren't respecting the `X-Forwarded-Proto` header. This is now resolved.

**Comment by mohanarpit** [comment]
I'm closing this issue for now. Incase the issue still exists for you, please feel free to re-open this issue.

**Comment by k0rn1** [comment]
it works now
