### ISSUE TITLE
[Bug]-[21]:Audio recorder does not reset UI when a recording is taking place

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When audio recorder/camera widget on video mode are reset while they are recording then the widget continues to record without any changes occurring on the UI, i.e. the UI continues to record.

### Steps To Reproduce

1. Using a binding as follows on a button widget's trigger field
`{{resetWidget("AudioRecorder1",true).then(() => showAlert('success'))}}`
2. Add a an audio recorder and text widget to the canvas
3. Bind internal widget properties of the audio recorder to the text widget as seen in the video
4. Click on the record on the audio recorder and then click on the button widget - observe the success toast displayed but audio recorder continues to record
5. When recorder is paused or stopped then the widget resets as expected
6. Similar behaviour is observed with the camera widget on video mode - but UI retains ok and discard icons even after a reset as seen in issue #14692 

https://www.loom.com/share/0122d91c7ed345fa8493f8a149e79e29

### Version

Cloud

**Comment by dilippitchika** [comment]
Assuming 30% of audio rec widgets get reset either via form or directly

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 21 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Workaround exists to stop the recording and then click on reset

**Comment by wisewizardofthestars** [comment]
Can I try to work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@wisewizardofthestars yeah sure please go for it

**Comment by akshat8605** [comment]
Is this issue still open? Can it be assigned to me?

**Comment by ramsaptami** [comment]
please go for it @akshat8605

**Comment by akshat8605** [comment]
@ramsaptami please review the changes. I have changed the blogURL value to null when the recording starts.
