### ISSUE TITLE
[Bug]: Update on Input widget inside List shows that value on all pages of the corresponding row until browser refresh

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#14697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the List widget, if there is an Input widget, note the following the bugs

1. When you first bind the data to the list widget, the value in the first input widget will be blank until the browser is refreshed.
<img width="399" alt="Screenshot 2022-06-21 at 9 55 27 AM" src="https://user-images.githubusercontent.com/32227135/174716473-1dfe227e-2e80-45c9-9243-8b8ac53b0fbf.png">

2. If you update the first input widget on the list, the display shows that updated value in all pages of the corresponding row until the page is refreshed. In the screenshot below, I change the name Jimmy on page 1 and the display reflects on all the other pages until the browser is refreshed. When serverside pagination is not used, this behaviour only occurs with the first item on the list 
<img width="371" alt="Screenshot 2022-06-21 at 10 04 08 AM" src="https://user-images.githubusercontent.com/32227135/174716942-cb6c52c7-1816-428d-bce5-dc668ae390b0.png">

3. When using serverside pagination on list, the bug in step 2 occurs for every list item on the page, not just the first one
<img width="424" alt="Screenshot 2022-06-21 at 10 08 54 AM" src="https://user-images.githubusercontent.com/32227135/174717364-83578678-f850-422f-9230-5fffbf30294f.png">

I only checked this with update query, this probably also happens on an insert query

### Steps To Reproduce

1. Add a list widget to the canvas
2. Add an input widget
3. Bind data to the list and display a field on the input widget. You will notice the input on the first list item is blank until the page is refreshed
4. Change the value on the input widget on the first list item and run an update query
5. Navigate to the other pages in the list and note that it shows the same updated value on all the pages until the browser refresh
6. Check the same with serverside pagination on, you will note this behaviour on all the list items and not just on first list item on the current page

### Public Sample App

https://app.appsmith.com/app/input-widget-bugs-inside-list/page1-62b14dc740b36d162478b0da

### Version

v1.7.4

**Comment by somangshu** [comment]
@Tooluloope @ashit-rath we should add this to out test cases, Maybe we are already covering this.

**Comment by Tooluloope** [comment]
Not all has been covered.
I'll add the rest

**Comment by dtunikov** [comment]
Hey
I also have problem with list items overwriting.
It affects all lists with input widgets which have more than one page.
Looks like very common bundle (list + input).

https://user-images.githubusercontent.com/106737620/183688830-b5b4ba3e-af7e-462d-89eb-5bfc919f7406.mp4

**Comment by Nikhil-Nandagopal** [comment]
@dtunikov sorry you're facing this issue. We're working on a solution for this here #15839

**Comment by ame-appsmith** [comment]
[Another user](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100163025#part_id=comment-164629100163025-16776293983) reported this bug.

**Comment by filipesmedeiros** [comment]
I have had problems with this also! 😄

**Comment by dilippitchika** [comment]
Hey @filipesmedeiros thanks for reaching out, we have fixed this issue in a newer version of the list which we plan to launch in the next few weeks.

**Comment by dilippitchika** [comment]
Can you please tell me your use-case @filipesmedeiros of using the input widget in the list? It will help us test our newer version better

**Comment by filipesmedeiros** [comment]
Of course @dilippitchika. I am using it to build a dynamic multiple-filter form.

So basically the person uses a multi-select to select all filters they want to apply. Then, I use a list to create a list of inputs, with one item/input for each filter selected in the multi-select. I will then use the values of each input to filter an endpoint (sending it in the query params).

I actually wish there was a more native way of doing multi server-side filtering, but this will do for now! 😄
