### ISSUE TITLE
[Bug]: Tab widget always defaults to the first tab when reset on both internal property and UI

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Resetting tab widget 

### Steps To Reproduce

1. Drop a tabs widget on canvas and add a few extra tabs on the widget
2. Set default tab to `Tab 2`
3. Drop a button and a text widget on the canvas and bind tab widget's selectedTab property on to the text widget and set a reset trigger for the tab widget on the button
4. Change selected tab to **Tab 1** and observe the change on the text widget to **Tab 1**
5. Click on the button widget to trigger reset and observe the text widget change from **Tab 1** to **Tab 2** and back to **Tab 1**
6. Change the selected tab to **Tab 3** and observe the change on the text widget to **Tab 3**
7. Click on the button widget to trigger reset and observe the text widget change from **Tab 3** to **Tab 2** and then to **Tab 1**
8. UI in all cases of widget reset always goes back to Tab 1

https://www.loom.com/share/770c8a43686a4b96b814d405a0ac41a0

### Version

Cloud

**Comment by dilippitchika** [comment]
Reset widget fuction in tab widget doesn't work as expected. If the default tab is tab2 resetting it should go to tab 2 and not tab 1. This is broken.

**Comment by dilippitchika** [comment]
@techbhavin please triage this issue, no need to fix right now. Just need to know why this is happening.

**Comment by techbhavin** [comment]
After resetting the Tab widget, widget getting `selectedTabWidgetId`(meta property) is undefined. so It takes the first tab as the default tab in the Tabs widget.

![image](https://user-images.githubusercontent.com/58818598/178743460-22db4159-13fa-4cb2-8cbe-008fca3fa783.png)

@dilippitchika

**Comment by techbhavin** [comment]
Hello @dilippitchika, Yes we can fix this issue from our side.
