### ISSUE TITLE
[Bug]-[48000]:Wasted renders of JSCollectionEntityContextMenu

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#14700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JSCollectionEntityContextMenu is rendering 10k to 15k times for every action on Aforce app. I don't see why that needs to run so many times. I believe it to be a problem with the hook `useNewJSCollectionName();`

### Steps To Reproduce

Take a react profile while editing the table data property[Just add a space] on community issues page. You will see it render 15k times.

Or

Just put console.count in `JSCollectionEntityContextMenu` component function

### Version

Both / Latest

**Comment by rohan-arthur** [comment]
Hi @SatishGandham , would you please explain the impact on the user? I'm assuming this degrades performance?

**Comment by SatishGandham** [comment]
@rohan-arthur , Yes. Performance degradation. Though this is a small component, the number of times it gets rendered is concerning.
Should be a small fix.

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.5 |
