### ISSUE TITLE
[Docs] Add multi-series how-to

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1470]
## Documentation Link 
https://docs.appsmith.com/widget-reference/chart

## Describe the problem
Multi-series documentation is missing.

## Describe the improvement
Describing the "Add Series" button in the reference gif and the documentation will help in understanding the way to add multiple series into a chart.

**Comment by ukitta555** [comment]
Working on it!

**Comment by ukitta555** [comment]
@riodeuno  done!
https://github.com/appsmithorg/appsmith-docs/pull/60

**Comment by ukitta555** [comment]
Maybe close the issue? The PR got merged.
