### ISSUE TITLE
[Bug]-[Infinity]:Prettifying the code & then clicking inside code editor is reverting the preetified version

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#14704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

prettifying the code & then clicking inside code editor is reverting the prettified version & also 1st click on prettify - removing only lint errors & only 2nd click actually prettifying also exists

### Steps To Reproduce

https://user-images.githubusercontent.com/10229595/174753086-631b1af7-7653-49ad-8b31-0ff161f0e759.mov

### Version

1.6.6

**Comment by rohan-arthur** [comment]
this is an edge case, so consider 10% requirement

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 250 |
| Effort (months)  | <<number>> |
