### ISSUE TITLE
[Bug]: The URL field for APIs is deleting all text after a ?  whenever optional chaining or ternary operators are used.

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#14706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The URL field for APIs is not saving the entered URL properly when optional chaining or ternary operators are used. At first, the editor evaluates the JS as valid and shows the correct evaluated value. But when you view another API/Query/JS Object and come back, the `?` and all text after it has been deleted. 

**Example:**
https://someAPI.com/products?page={{appsmith.store?.pageNo||1}}

**After viewing another API and returning to first API:**
https://someAPI.com/products?page={{appsmith.store

The URL is truncated at the `?`, and even the closing mustache binding is lost. 

### Steps To Reproduce

1. add mustache bindings and JS expression to API’s URL field, using optional chaining or ternary operator (anything with a `?`)
2. click to a different API/Query, then come back to first API
3. observe that the `?` and all text after are lost, including the closing `}}`.

### Version

Appsmith v1.7.4-SNAPSHOT

**Comment by GreenFlux** [comment]
@Nikhil-Nandagopal , @rohan-arthur , a little more background on this issue:

When an API's URL references another API which has not ran yet, the evaluated value at the URL is invalid and returns an error in the editor. 

**Example:**
`https://storename.myshopify.com/admin/api/2021-10/products/{{findProducts.data[0].id}}/variants.json`

This causes an error in the editor until findProducts has run, which needs an input from the user for a custom search. So I don't want the findProducts query to run on page load. I expect there to be no data in findProducts on page load. 

But now there is always an error in the editor for this API until the findProducts API returns data. And I have this same scenario with multiple endpoints in the same app, resulting in numerous errors on page load.

All of these errors could be avoided with optional chaining. However, this bug causes the API's URL value to be deleted/truncated after the `?`, so optional chaining can not be used. It would be a great improvement to the editor if these nuisance errors could be avoided. Currently it is hard to notice new errors in the editor when the count always shows as 9+.

**Comment by bharath31** [comment]
@GreenFlux are you still facing this issue? I could get ternary operators to work on an API URL
```
https://opentdb.com/api.php?amount={{Api5.data ? Api5.data.results.length : 2}}
```

**Comment by GreenFlux** [comment]
@bharath31 , I just retested. It looks like this has been fixed! Previously, ternary operators, and optional chaining, both caused all text to be lost after the `?`, but I am not able to reproduce either issue now.

**Comment by bharath31** [comment]
Awesome! Closing this issue now :)
