### ISSUE TITLE
[Bug]: Query Returns {} when Select Files Picked via Widget

### ISSUE THREAD

**Issue by lukearran** [appsmithorg/appsmith#14717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We've noticed a strange behavior when working with the "file picker" widget to upload documents to an external source.

Users have reported being unable to upload files. Upon looking into the issue, we've found that the issue is limited to a range of PDF documents when referred to in a S3 or PostgreSQL query. The query (for both connectors) returns the below error, with no additional information to describe the cause of the problem.

![Screenshot showing 'An error occurred' followed with {}](https://tick9public.blob.core.windows.net/public-internet/app_images/Screenshot%202022-06-21%20162550.png)

We have re-produced this issue with uploading Base64, Text and Binary data via a PostgreSQL connection, and a S3 connection (via MinIO).

### Steps To Reproduce

1. Create a new application on Appsmith
2. Place a `File Picker` widget.
3. Set the `Data Format` to `Base64`
4. Create a new S3 connection (tested with MinIO)
5. Set `Create a new file` as the command
6. Set the bucket name.
7. Set `{{FilePicker1.files[0].name}}` in the `File Path` field
8. Set `Base64` in `File Data Type`
9. Set `Content` field to `{{FilePicker1.files[0]}}`
10. Click `Run`
11. Observe an error response containing `{}` with no additional information.

Please note, a sample file named `sample_bad_file_upload.pdf` was given to **[AS] Laguna** on Discord which can be used to reproduce the issue.

### Version

Self Hosted

**Comment by Nikhil-Nandagopal** [comment]
@AS-Laguna could you please share more information on this?

**Comment by AS-Laguna** [comment]
I believe the team is currently looking into this. @ohansFavour is there any update on this?

**Comment by AS-Laguna** [comment]
@lukearran does this happen when testing the query in the query pane? There is a known issue of the filepicker being cleared when navigating away from the canvas in #11660. Could you check if this is the case?

**Comment by lukearran** [comment]
@AS-Laguna - I can reproduce that issue with navigating to a query pane when in the editor mode. But we can see the file data being passed into the S3 or PostgreSQL query before execution - when in published, or editor mode.

**Comment by AS-Laguna** [comment]
@lukearran To clarify: you can see the file being sent, and it still seems to return `{}`? Could you please provide a loom video of this behavior?

**Comment by ohansFavour** [comment]
@lukearran we are currently not able to reproduce this behavior, even with the sample file which you sent. A loom video could better help us reproduce this.

**Comment by lukearran** [comment]
@ohansFavour - No problem, I've included a Loom video below.

https://www.loom.com/share/69be9f6a38364a7893534514af812f7e

Please let me know if you require any further information.

**Comment by ohansFavour** [comment]
Further discussion

https://discord.com/channels/725602949748752515/760761686549463060/988818435809112064

**Comment by lukearran** [comment]
Thanks @ohansFavour for your call earlier!

After our remote session, I can now confirm that this issue was caused by a bad Nginx configuration input which prevented uploads greater than 1.5MB+. Increasing the `client_max_body_size` to a higher file size resolved the issue (in this case, 10MB).

More information on the issue can be found here - https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

Thanks again,

Luke
