### ISSUE TITLE
[DOCS] - Create doc for window.postMessage task

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#14723]
Create a document for #7241 task on window.postMessage added to global functions

**Comment by rimildeyjsr** [comment]
Link to documentation - https://www.notion.so/appsmith/88de24af66ef41ec8e36c663942a4657?v=a2169b3184194138ab1fa88905e9ce82&p=e1ba3bc55b8b41c7a0198152007306a3

**Comment by rimildeyjsr** [comment]
This is for post message task - https://app.zenhub.com/workspaces/fe-coders-pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/12551

Will go in with the next release cycle

**Comment by jnikhila** [comment]
@spark-c - Could you please confirm the status of this and add it to the ticket?

**Comment by spark-c** [comment]
Last I heard, this task was going to be worked on again beginning in late August; I just took a look to see if there was an update on the ticket, and it looks like a new implementation of `postMessage()` was being tested last week, so maybe it might be ready soon.

@rimildeyjsr do you know if this is the case? Thank you!

**Comment by jnikhila** [comment]
@spark-c - Could you please take up this ticket?

**Comment by spark-c** [comment]
Note to self: Update /reference/appsmith-framework/widget-actions/ with links to all of the current framework events along with `postWindowMessage()`

**Comment by spark-c** [comment]
Apologies for the delay, docs PR is coming soon.

**Comment by spark-c** [comment]
PR [available here](https://github.com/appsmithorg/appsmith-docs/pull/646) for review

**Comment by spark-c** [comment]
Should be ready to merge very soon pending final review
