### ISSUE TITLE
[Bug]: Resetting list widget causes unexpected page size behaviour

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Resetting a list widget causes odd behaviour with page size where page size goes to infinity or decreases and child containers get pushed into only a few pages. The 2 videos attached show this behaviour.

Also, if the last or pages close to the end are selected during reset then the UI does not revert to Page 1.

### Steps To Reproduce

1. Drop and list and button widget on the canvas
2. Set button onClick to reset list widget
3. Reduce the size of the list widget to only display one result and trigger reset by clicking on the button
4. Observe the list widget page number goes from 1,2,3... to infinity
5. Refresh the page and bind a large dataset to the list widget
6. Expand the list widget to show a few more than 1 result per page 
7. Reset the widget
8. Observe the page number decreases and results getting cramped on pages making child containers inaccessible
9. Refresh the page and move to the last page on the list widget
10. Reset the widget and observe the UI does not revert to the first page

https://www.loom.com/share/8b9d090e2f024ca39e8eff1084a6df87
https://www.loom.com/share/be009a515929480d95ab1876e42f7572

### Version

Cloud

**Comment by somangshu** [comment]
@Tooluloope can you check if this issue is with the list widget, or the reset widget functionality. 

In case this is related to the list widget, Lets add this to the test plan, and also the EPIC.

**Comment by kamakshibhat-appsmith** [comment]
LGTM!
