### ISSUE TITLE
[Bug]-[1654]:Default value of an Input’s text is undefined

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#14734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When defaultText isn’t set and user hasn’t focused on the input’s textarea, an input's text value is undefined, even upon reload.

### Steps To Reproduce

[loom video](https://www.loom.com/share/bc00428b76614cd5b5d2b77f9583c14b?t=0).

Steps to reproduce (in dev mode)

1. Drag and drop an Input widget 
2. Inspect the unevaltree

### Version

Cloud

**Comment by dilippitchika** [comment]
@somangshu @sbalaji1192 if we do this change, is this a new version? Also @sbalaji1192 i need some help understanding how many users will be impacted by this. Can you triage this once?

**Comment by sbalaji1192** [comment]
@dilippitchika It's a very simple fix but it will impact people who are expecting the default value of the input widget to be `undefined`. So we should add a new version.
There is no way for us to know "how many" users will get impacted.

**Comment by sbalaji1192** [comment]
@dilippitchika Ignore my previous comment about introducing a new version. Making this change would not affect any app. so we should be fine with making the change on the same version of the input widget.

**Comment by somangshu** [comment]
@iamrkcheers please have a discussion with @sbalaji1192 before picking this up

**Comment by somangshu** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 827 |
| Effort (months)  | 0.25 |
