### ISSUE TITLE
[Bug]: Customer on-boarding DB query fails intermittently

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

During the customer onboarding journey, the pre-set DB query fails to run at times and leads to confusion and user's abandoning the on-boarding journey.

### Steps To Reproduce

1. Create a new user to start customer on-boarding journey
2. Walkthrough to reach the step where we run a DB query - observe that the DB query fails intermittently and returns an error response making it a bad UX 

https://www.loom.com/share/357045e50c454e8096cc8800cc3c134d

### Version

Cloud

**Comment by akash-codemonk** [comment]
Closing as duplicate of #14744
