### ISSUE TITLE
[Feature]-[250]:redesign the page properties page

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#14745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The current page properties page is awkward and doesn't quite do much. with clean URLs and other future projects, we would like to refactor the page to include app properties, page properties, as well as allow room to grow for future app level settings

### Why should this be worked on?

the current page properties page isn't very useful, but if we were to gather all the page and app level settings to a single page, it would make it easier to understand and work with

### Sub tasks
- [x] #16155
- [x] #16156
- [x] #16157
- [x] #17209
- [ ] #18411

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | 1|

**Comment by RoopKrrish9696** [comment]
**Zeplin handoff link for the above issue** 

https://zpl.io/09WMW6x

**Figma designs handoff link for the above issue** 
https://www.figma.com/file/Q6s9qidrQX6b15yUUGR0ES/Clean-URLs---Phase-2-%26-App-settings-design-handoff?node-id=2%3A1

**Comment by Nikhil-Nandagopal** [comment]
@RoopKrrish9696 why don't we have a settings CTA in the right side bar?

**Comment by RoopKrrish9696** [comment]
@Nikhil-Nandagopal According to the discussion we had on that day along with @kocharrahul7 @areyabhishek , there were a couple of reasons we discussed why we can build the settings icon later in the navbar, not right now. 

1. Already there is a new navbar in place and we don't have enough settings yet where people can use them often, so let's track how people are using the settings and then take a call, till then we can have it in the dropdown. 
2. Crowding the navbar is again a thing we need to deal with is what people who questioned against, so this is also a reason here. But I don't think this is such a significant issue, we can have an icon which is not so troublesome.

**Comment by Nikhil-Nandagopal** [comment]
@RoopKrrish9696 I don't mean the navbar, I meant the right side bar where canvas items etc are present. The reason being that the CTA on the left and then the pane opens on the right is really weird. This also kills the discovery of theming. So just a general settings callout where themes is today can help this.
@kocharrahul7

**Comment by kocharrahul7** [comment]
Hey, at the moment we aren't moving theming settings.

We can add the CTA now, and then when theming is moved add a quick note mentioning that theming settings can be found within that settings page

**Comment by kocharrahul7** [comment]
After disuccing with the App Viewers pod, we will move theming in here as well, and will come up with a solution for discoverability of themes simultaneously.

**Comment by eco-monk** [comment]
- [ ] Page context menu changes
- [ ] Move general and app theme settings into app settings panel
- [ ] Move page settings into app setting panel

**Comment by eco-monk** [comment]
Linking design system issues created for reference: (nothing major)
#17431
#17393

**Comment by RoopKrrish9696** [comment]
**Design review for the[ latest DP](https://appsmith-jlhby3j2n-get-appsmith.vercel.app/app/klnlkkl-6344feff6ecce258ec09293f/edit) :** cc @kocharrahul7 @ginilpg @eco-monk 

1. App settings CTA hover state missing
2. Autosave loader state to be implemented
3. All paddings are mismatching the latest [zeplin](https://zpl.io/JEwOwJr) link, please cross-check with zeplin. ( In theme settings, the left padding for the title and the rest of the body is different, please check that as well )
4. Hide page navigation should be "Show page navigation" and active by default ( refer [zeplin](https://zpl.io/JEwOwJr) link for this )
5. Set as homepage disable state to be implemented ( in the latest [zeplin](https://zpl.io/JEwOwJr) link )
6. Set as homepage disable state in the page settings drop down to be implemented ( in the latest [zeplin](https://zpl.io/JEwOwJr) link )
7. The tooltip for the collapse button in the settings pane is missing
