### ISSUE TITLE
[Bug]: Async functions with TypeErrors are not marked as Async in JS Editor

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#14742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a JS Function has a TypeError, even if it's marked as async, it is not treated as one (doesn't show up in the settings tab). 

### Steps To Reproduce

1. Go to the JS Editor page
2. Create an async function with a typeError (`cannot read x of undefined`).
```
   myFun1: async () => {
		//write code here
		const user = {
		}
		console.log(user.name.test)
	}
```
or run an Api

```
   myFun1: () => {
		//write code here
		const user = {
		}
		console.log(user.name.test)
                Api1.run()
	}
```
3. Observe the settings tab, and see that these functions are not treated as async.

### Version

Cloud

**Comment by rishabhrathod01** [comment]
As we have removed the concept of async function tagging for JSObject. This issue is no more valid.
