### ISSUE TITLE
[Feature]: Add timestamp to `backend.log` file

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#14769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The user wants logs with timestamps, as it'll help them with debugging the issue.

### Why should this be worked on?

https://theappsmith.slack.com/archives/C02MUD8DNUR/p1655981399229579

**Comment by sharat87** [comment]
Solved in #15440.
