### ISSUE TITLE
[Bug]: Comment mode not turning off in view mode

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#14771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/12022471/175288589-3c0a0378-5fe3-4db5-8db1-970a9a9a46d8.mov

Once we are in comment mode, it is not possible to come out of it in view mode by clicking on the button again
Pressing "C" also does not work

### Steps To Reproduce

In the view mode of the app click on the comment button on the top right. There is no way to exit this mode now

### Version

Cloud

**Comment by vuiets** [comment]
This issue has been around for a while but we are looking at sunsetting commenting as part of https://github.com/appsmithorg/appsmith/issues/14173 since we haven't had much usage and we don't have the bandwidth to continue supporting it.

So this will be closed with that.
