### ISSUE TITLE
[Bug]-[7568]:Edit auth API datasource, I don't know if client secret is saved or not

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I edit an authenticated API datasource, I see the datasource form with all the fields filled, except the client secret. But now I don't know if the secret is actually saved or not, because the placeholder text is the same both in create and edit mode: `Client Secret`.

![Screenshot 2022-06-24 at 08 01 31](https://user-images.githubusercontent.com/94514895/175455340-45c3ae27-d28a-432d-b766-a19b2a3e6139.png)

When I edit a datasource, I should be able to distinguish the saved password/secret/etc fields from the ones where I have not entered anything

### Why should this be worked on?

This simple fix should allay the user's anxiety and make the datasource editing experience better.

**Comment by rohan-arthur** [comment]
same issue with:
1. Airtable, both for token and key
2. MySQL password (but not, e.g., for mongo password)
3. DynamoDB, AWS Secret Access Key
4. MS SQL server, password
5. Firestore Service Account Credentials
6. Redshift, password
7. S3, key
8. Snowflake, password
9. ArangoDB, password

**Comment by rohan-arthur** [comment]
event ROUTE_CHANGE, path containing 'edit/datasource', 6 months data:
Total: 170,000
Unique: 10,300
i.e., about 86% of cloud users end up editing datarources

total 6m unique usage of all above datasources is 8,800. 
of these, 86% = 7568

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 7568 |
| Effort (months)  | <<number>> |

**Comment by prapullac** [comment]
Issues :
1) Password is displayed to user before Saving the datasource on Dev tool

**Comment by prapullac** [comment]
The above mentioned issue still exists. However the issue

**Comment by PiyushPushkar02** [comment]
Re-tested it in my local once. 

Moving this to Needs QA.

**Comment by PiyushPushkar02** [comment]
Even after merging the release, there is still a build failure which is not reproducible locally. Will need more time to check this. Moving this ticket back to product backlog as we cannot close this without spending some extra time on the same. @rohan-arthur @sumitsum

**Comment by rohan-arthur** [comment]
### Solution direction
_**Phase1: single plugin**_
1. Let us pick any one plugin, say Postgres. 
2. In the datasource config page for postgres, there is the password field
3. Here, create a datasource with username and password, and save it
4. Open it for editing, you see that the password field is empty

**Step 1: show a constant number of placeholder characters**
First as a simple implementation, show 6 password mask characters when a password exists

**(low priority)Step 2: show correct number of placeholder characters**
Once step 1 is working and looks good, the number of mask characters should be equal to the length of the password


_**Phase2: general solution for all plugins**_
the implementation should work for all plugins, [listed here](https://github.com/appsmithorg/appsmith/issues/14783#issuecomment-1165157508)

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur the solution here seems unclear because if we simply show 6 characters and the user saves the datasource, the datasource will now be invalidated. So I'm questioning whether this issue is actually valid and we should just close it because I think we expect a user to re-enter any password credentials if they try to save a datasource

**Comment by rohan-arthur** [comment]
Thanks @Nikhil-Nandagopal I've added a clause to clarify above, "_only when the datasource is opened for editing_"
I try to explain in this video

https://github.com/user-attachments/assets/2a517093-a376-40b8-b406-cf9a82a869b8

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur I understand that but in this case we also need to handle the scenario where a user does not edit the password field but we still maintain the older password on the server.

**Comment by rohan-arthur** [comment]
@Nikhil-Nandagopal The user needs to know whether they have saved something in the secret fields. Masked characters is a widely understood convention, but even an indicator or an icon will do. It is not acceptable to leave the user in the dark about the configuration that they entered.

![Screenshot 2024-07-15 at 18 22 50](https://github.com/user-attachments/assets/783eaecc-1266-4a2c-b6b9-bc03edd11617)
![Screenshot 2024-07-15 at 18 22 33](https://github.com/user-attachments/assets/cce58528-00ec-400e-aa25-06058a358785)
![Screenshot 2024-07-15 at 18 22 12](https://github.com/user-attachments/assets/17bf8016-6502-4040-ae76-a59e5b51b5aa)


ref screenshots from retool, budibase and superblocks.

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur as I said it's fine to have the masked characters, my point is that in that event we also need to have a way to detect whether the password was edited or not and not update / update only that field
