### ISSUE TITLE
[Docs]: typo fixes in dropbox example in OAuth doc

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/connecting-to-data-sources/authentication/oauth2-authentication/authorization-code

### Describe the problem

Section `Integrate with Dropbox`
1.**Fix the scope** the scope is mentioned as `file.content.write`
![Screenshot 2022-06-24 at 07 57 09](https://user-images.githubusercontent.com/94514895/175450090-1edc4ce1-a383-4a58-b2f2-5fa00de84ae4.png)

whereas dropbox supports `files.content.write`
![Screenshot 2022-06-24 at 07 55 24](https://user-images.githubusercontent.com/94514895/175450137-34d58333-9b97-44c3-b750-ffd97ffc7948.png)

2. **Remove extra character** the value of header key `Dropbox-API-Arg` contains an extra `
![Screenshot 2022-06-24 at 09 48 15](https://user-images.githubusercontent.com/94514895/175461363-dd5b2f8b-df1a-4079-b9bc-5e7349d3caa3.png)

### Describe the improvement

If I follow the instructions in the doc, I get an error page on clicking `Save and Authorize`
This is a simple fix, we probably overlooked it in review.

**Comment by jnikhila** [comment]
@rohan-arthur - Updated and published the doc.

**Comment by jnikhila** [comment]
Published [doc](https://docs.appsmith.com/core-concepts/connecting-to-data-sources/authentication/oauth2-authentication/authorization-code#integrate-with-dropbox).
