### ISSUE TITLE
[Bug]: Graphql ui and functionality issues second iteration

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#14789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [x] Remove the tooltips from the body and body variable headers
![Tooltips](https://user-images.githubusercontent.com/7565635/175324278-69fc62df-9f01-432f-a757-03d491b2c28a.png)

- [x] The tooltip underline for the pagination tab has to be dotted underlines so that is consistent with the component of the property pane and UQI. 
<img width="747" alt="Screenshot 2022-06-24 at 12 05 21 PM" src="https://user-images.githubusercontent.com/7565635/175477048-6cf206d6-18d0-4352-8d90-67ff9ac4aa84.png">

- [x] The slash command shoudn’t be active for disabled inputs.
<img width="458" alt="Screenshot 2022-06-24 at 12 06 23 PM" src="https://user-images.githubusercontent.com/7565635/175477189-ff3d67fa-d6ff-4210-b778-b8ebed171628.png">

- [x] The width of the dropdowns and inputs are much larger than the ones in the designs. 

- [x] Page crashes when you enable the separate value checkbox.

- [x] Configure Previous page and Configure next page titles are inconsistent with the designs. 
        a) Font size should be 14px.
        b. Spacing is different from designs they are supposed to be closer the the inputs than the top section.

- [x] Need an empty state for the dropdowns in case there isn’t a query written or there are no variables mentioned in the code.
<img width="381" alt="Screenshot 2022-06-24 at 12 07 03 PM" src="https://user-images.githubusercontent.com/7565635/175477287-e98ec00f-a50c-4947-ae7a-e4c5fba44f67.png">

- [x] Create a flow for creating direct GraphQL API just like Rest API flow right now and keep the GraphQL datasource flow as well.

### Steps To Reproduce

1. Go to create GraphQL Datasource.
2. Create GraphQL API
3. Observe the above issues.

### Version

Self Hosted

**Comment by prapullac** [comment]
Not in the release Yet
