### ISSUE TITLE
[Bug]: Dropdown size is too small

### ISSUE THREAD

**Issue by rizistt** [appsmithorg/appsmith#14787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have created a multi-select dropdown in the form and the data is dynamic (loaded dynamically through a SQL script). But on the mobile screen, the dropdown width is too small to view the list of items.

![image](https://user-images.githubusercontent.com/37738960/175474621-45f9644d-d731-4a29-9639-73279063a12d.png)

### Steps To Reproduce

1. Add a multi-select widget to the form.
2. Change the label position to "Top"
3. Bind the options to the SQL query.
4. Enable "Server-Side Filtering"
5. Bind the same query to the "onFilterUpdate" event
![image](https://user-images.githubusercontent.com/37738960/175475076-e6d845cd-ff2f-4343-b13a-71f7cc902456.png)

### Version

Self-Hosted - 1.7.4

**Comment by dilippitchika** [comment]
@rizistt is it happening in the JSON form or a regular select widget?

**Comment by rizistt** [comment]
> @rizistt is it happening in the JSON form or a regular select widget?

Not sure what you meant there, but here is a bit more detail, when you select a "Select" widget, it sets random data as options, I removed it and made it dynamic by binding it to a SQL query.

One thing that I noticed was when the label is empty (while the position is set to Top) the dropdown appears with 100% width. The moment you enter something as a label, it shrinks.

WITHOUT LABEL:
![image](https://user-images.githubusercontent.com/37738960/175921508-55dd7ed0-2b4a-494f-abc9-723e58db6761.png)

WITH LABEL AND POSITION TOP:
![image](https://user-images.githubusercontent.com/37738960/175921840-a045b023-a1b0-473f-a5ba-a4a6e76f6130.png)

WITH LABEL AND POSITION LEFT:
![image](https://user-images.githubusercontent.com/37738960/175921931-a8aae616-355e-4326-9812-6c7581d7362b.png)

**Comment by dilippitchika** [comment]
Thanks for the additional info, this only happens when the widget is out of bounds. If you resize the widget, after changing the position to top, it doesn't happen. 

We are going to solve this internally to make sure the widget is not going out of bounds.

**Comment by rizistt** [comment]
Sure, I will reduce the width and try again.

**Comment by dilippitchika** [comment]
@rizistt you need to increase the height of the widget when the label position is set to Top

**Comment by rizistt** [comment]
Thank you, increasing the height did the trick.
