### ISSUE TITLE
[Docs] : Update iFrame

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#14794]
Refer to the [Slack conversation](https://theappsmith.slack.com/archives/C01CFTXD0N8/p1656061114922759)

Key pointers to update:

* Work on the postMessage implementation
* Explain the property properly
* List the internal property message that is used to expose the object that is received

A [sample app](https://release.app.appsmith.com/applications/60c1ddf39eaedc5f554a2346/pages/60c1ddf39eaedc5f554a2348/edit) that could help understand the working.

**Comment by jnikhila** [comment]
@somangshu - Could you please confirm whom to connect to discuss the changes?

**Comment by somangshu** [comment]
@jnikhila please let me know. I might be able to help. Otherwise will get the relevant people based on the question

**Comment by spark-c** [comment]
As a small update to this issue, the iframe docs now have the internal `message` property included and briefly explained in its properties table.

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/reference/widgets/iframe).
