### ISSUE TITLE
[Enhancement] Mongo Data structure not returning for mongo clusters

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1479]
## Description

Some mongo dbs do not respond to fetching their structure in our current implementation. We should add a fallback to use this API to list collections
https://docs.mongodb.com/manual/reference/command/listCollections/

**Comment by sharat87** [comment]
Getting structure will fail if the credentials that are configured in the datasource do not have permissions to access the structure metadata in the database. For example, in the case of MongoDB, if the user configured in the datasource doesn't have the authority to run the `listCollections` command on the database, the structure functionality won't work. The way around this is to use credentials that have permission to run the `listCollections` command so Appsmith can fetch the structure.

**Comment by Nikhil-Nandagopal** [comment]
Additionally, we should communicate to users that we are unable to access the structure due to permissions
