### ISSUE TITLE
[Bug]-[500]:Google Sheets | Scope | Read Only allows write access

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#14803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Read Only` datasource allows inserts, updates, and delete.

### Steps To Reproduce

- Create a `Read and Write` scoped datasource
- Perform CRUD -> All works well
- Edit the Datasource and change the scope from `Read and Write` to `Read Only`
- Create Query/ use existing query to perform Insert/update/delete
- The operations went through without any error

Note - This only happens when the datasource is previously set with a `Read and Write` scope. The error messages are shown for a `Read Only` scope datasource. The issue seems to be with the Google Permissions. Once a `read and write `permission is granted for a google account, the insert/update/delete is going through irrespective of the scope set.

### Version

Cloud

**Comment by rohan-arthur** [comment]
GSheets 6m usage: 2500
Assume 5% of users run into this issue: 125

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 125 |
| Effort (months)  | <<number>> |

**Comment by nidhi-nair** [comment]
I am unable to reproduce this error. @jnikhila had you re-authorized the datasource after modifying the scope to read only? Without re-authorizing, the datasource would continue to use the last valid token it has, which is from the larger scope.

**Comment by jnikhila** [comment]
@nidhi-nair - I retested the scenario and it seems to work. I think the issue was that on scope changes the DS was not taking you to the Google screen to reauthroize the permissions, and thus was working on the previous permissions. This seems to have fixed now as the permissions are reset based on the scope selected by users.

On another note - the UI for scope has changes. When the doc was created it showed as "Read Only", and "Read and Write". These changes [are not part of documentation at the moment](https://docs.appsmith.com/reference/datasources/querying-google-sheets#connection-settings). Could you please raise a doc modification ticket to capture the change?

**Comment by nidhi-nair** [comment]
I see that the [issue](https://github.com/appsmithorg/appsmith/issues/15614) has been created, thanks for that Nikhila! <3
