### ISSUE TITLE
[Bug]: JSObject function execution failure when it is parsing

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/23132741/175784483-9ce32ad4-45fe-4160-973b-0a62b126f8d6.mov

### Steps To Reproduce

```js
export default {
      myFun1: () => {
        let values =
          [
            storeValue('val1', 'number 1'),
            storeValue('val2', 'number 2'),
            storeValue('val3', 'number 3'),
            storeValue('val4', 'number 4')
          ]
        return Promise.all(values)
          .then(() => {
            showAlert(JSON.stringify(appsmith.store))
        })
          .catch((err) => {
            return showAlert('Could not store values in store ' + err.toString());
          })
      }
    }
```
1. Copy the content of JSObject in the above test
2. Create new JSobject
3. Paste the copied JSObject code
4. Let the save get completed and ASAP press the run button.

### Version

1.7.5

**Comment by ramsaptami** [comment]
Attached video shows how 2 complete different functions on a JS object is run when selected function on the dropdown is current function the user is working on and user hits run using keyboard shortcut mid-way when the app is still being saved (parsed)
https://www.loom.com/share/46bdc6a157cb48bb93cbde6f78a6b9c9

**Comment by bharath31** [comment]
@satbir121 could we run an RCA here and find a potential fix?

**Comment by Rishabh-Rathod** [comment]
Closing the issue as this is no more reproducible after performance improvement in evaluations.
