### ISSUE TITLE
[Bug]-[6489]:Cannot delete the first header in API datasource form

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In API datasource page, headers section, the delete icon is shown only from the second row onwards. This means that I cannot delete the first row, and have to remove the contents manually.

https://user-images.githubusercontent.com/94514895/175768142-5281a866-a864-477c-b7d2-88366cb1ce56.mov

### Steps To Reproduce

1. click `+` next to `Datasources` to see the datasource pane
2. select `Authenticated API`
3. See that the first header cannot be deleted

### Version

Cloud

**Comment by rohan-arthur** [comment]
Edit or create datasource, 6m: 18,540
REST plugin usage is 35%
Therefore reach = 6489

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 6489 |
| Effort (months)  | <<number>> |

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur reach is off here because all these users are app viewers and not necessarily developers and out of the developers the number that will reach this page is lower and the number that will experience this issue is a fraction of that

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur reach for edit data source is closer to 13k, we also shouldn't assume that all those users will face this issue it will likely only be a small percentage

**Comment by AmanAgarwal041** [comment]
We need design for this use case i.e. where should the delete icon be present to delete the first header and add icon to add the headers

**Comment by prapullac** [comment]
Completed testing and observe that the issue is working as expected
