### ISSUE TITLE
[Bug]: Cannot deploy latest release (1.7.5) to Heroku

### ISSUE THREAD

**Issue by ribtoks** [appsmithorg/appsmith#14808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I cannot deploy Appsmith to Heroku (using Mongo Atlas connection URL) per instructions in the documentation. I tried both master and 1.7.5 git tree. After the installation you get `Appsmith server is unavailable` screen and in the logs - Java exceptions (attached). Btw, I did verify MongoDB connection and it works.
[intmaker-appsmith-logs-1656265317090.txt](https://github.com/appsmithorg/appsmith/files/8987319/intmaker-appsmith-logs-1656265317090.txt)

### Steps To Reproduce

1. Press "Deploy to Heroku" button from docs page and follow instructions
2. Deployed app does not start, logs contain lots of java exceptions

### Version

Self Hosted - 1.7.5

**Comment by sharat87** [comment]
Hey, thanks for sharing the full logs. I see the following error message in the logs:

```
Database name must not be empty
```

Can you confirm if you have a database name set in your value for `APPSMITH_MONGODB_URI` please?

For example, the has a database name called `dbname`:

```
mongodb+srv://username:password@cluster-name.abcdef.mongodb.net/dbname
```

**Comment by sharat87** [comment]
Hey @ribtoks, the database doesn't need creating. MongoDB will auto-create databases when someone attempts to use it. So, in your cluster URI, just set the database name to `appsmith` or something and restart, it should pick it up.

**Comment by ribtoks** [comment]
I can confirm that after appending `appsmith` to the MongoDB connection string, everything worked out. Thanks @sharat87 !
