### ISSUE TITLE
[Bug]: When entering a value in the currency input, it always appears as invalid

### ISSUE THREAD

**Issue by rodrigo-mahamud** [appsmithorg/appsmith#14809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have added a currency input to my form and when entering an amount the currency input always returns "invalid value

https://user-images.githubusercontent.com/76396937/175831127-3ce54b92-9bb7-427a-bf22-95613bbbb7a0.mp4

"

### Steps To Reproduce

1. Add a currency input field
2.  Depoy

### Public Sample App

https://app.appsmith.com/app/fund-raising-crm/inicio-62b87f9420ae3225cef24686

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@rodrigo-mahamud this is because it is marked as a required field in the currency input property pane
