### ISSUE TITLE
[Bug]: File Picker - JS Toggle on Allowed File Types - JS toggle un-clickable till field is cleared

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With File Picker widget, if we do a JS toggle on Allowed File Types property, with any of the properties selected, the JS button remains non clickable until  the field is cleared. This behavior is seen even if the Allowed file types are of valid file types.

Expected Behavior - If the allowed file types are of valid file types, the JS button should not be disabled. 

### Steps To Reproduce

1. Drop a file picker widget onto the canvas.
2. From the Allowed File Types property, select Images. 
3. Now click on the JS toggle button
4. The button gets disabled immediately and unless we clear the field, it does not get enabled again
5. This behavior is seen even if the Allowed file types are of valid file types, which is incorrect.

If the allowed file types entered are of valid file types, the toggle should not get disabled. Only if we enter some unaccepted value, it should get disabled.
<img width="579" alt="Screenshot 2022-06-24 at 10 14 46 PM" src="https://user-images.githubusercontent.com/101863839/175856917-ec42eabf-7887-42ca-98af-488879211fad.png">

### Version

Release

**Comment by dilippitchika** [comment]
@aswathkk can you check once what is happening here? Ideally this should have a way to go back but something is changing which is preventing it from doing so

**Comment by aswathkk** [comment]
@dilippitchika This case (multi-select in dropdown) is not handled properly. I will raise a PR with a fix.

**Comment by btsgh** [comment]
Tested and found to be fixed.
