### ISSUE TITLE
[Bug] When bindings are being substituted inside a string, the quotes are not being escaped

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1481]
## Description

Mongo Queries that have a regex where the regex reads an array from a widget don't work because the backend does not escape the evaluated value after substitution

### Steps to reproduce the behaviour:
1. create a mongo query against our mock db
`{
  "find": "users",
  "filter": {
    "name": { "$regex": "[\"nikhil@appsmith.com\"]" }
  },
  "sort": {
    "_id": 1
  },
  "limit": 10
}
`
2. Run this query, it runs fine
3. Bind the regex to a text with the text set as ["nikhil@appsmith.com"]
4. Run the query and it fails because the quotes are not escaped during substitution. The evaluated value shows the text as escaped

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal @hetunandu The problem here is that in the evaluated value pane, we are displaying a JSON stringified value of the binding. This exact same string is sent to the server in the request for action execution. When the server decodes the JSON, by default the Spring framework performs a `JSON.parse` on the request body. This is the source of inconsistency in the evaluated value & actual request being sent to the database. 

In order to solve this, I would suggest that the evaluated value shows the raw data that it's getting from the binding and NOT `JSON.stringify` the value.

**Comment by Nikhil-Nandagopal** [comment]
Can we not do a smart substitution and auto escape if we're substituting inside quotes?

**Comment by mohanarpit** [comment]
But isn't it simpler to not JSON stringify it in the evaluated value pane? Wouldn't that be a global solve?

**Comment by hetunandu** [comment]
The reason we stringify the results of a binding with the rest of the input is IMO correct. We are substituting an object between two strings so the resulting output should be a string. That is how it works every other widget or action binding.

**Comment by mohanarpit** [comment]
@hetunandu So, I can see that if I bind just `{{Text4.text}}`, the evaluated pane shows `"ABC"`. But if I bind `{{Text4.text}} {{Text4.text}}`, the evaluated value is `\"ABC\" \"ABC\"`.

What is the logic that the client is applying in order to determine if the binding is a String or an Object?

**Comment by Nikhil-Nandagopal** [comment]
lowering the priority here since we are picking up all dynamic binding issues as part of the dynamic refactor project

**Comment by ofpiyush** [comment]
I am getting confused here.

Can we come up with a different example to demonstrate what we're looking for?

As I try to think through this, the behaviour of `{ "$regex": "[\"nikhil@appsmith.com\"]" }` keeps tripping me.

The correct usage for a regex query with array of values would be something like:

```
{ "$regex": "nikhil@appsmith.com|user2@example.com" }
```

That begs the question, if you tried to bind an array to `$regex`, should we auto join it with pipes?

That would need us to be aware of the query and the key you're trying to bind a value to. Is that what we're going for as part of the fix here?

Behaviour of `$in` for example is correct right now because it expects and gets an array.

```
{ "$in": {{Dropdown1.selectedOptionValues}} }
```

^ i.e. we can't just convert everything to string directly.


Escaping even in case of strings, mostly depends on the surrounding code.
For values `hello 'world'|hello "world"`, it matters which quote was used outside and what was escaped.


```
{ "$regex": "{{Dropdown1.selectedOptionValues.join('|')}}" }
```

**Comment by Nikhil-Nandagopal** [comment]
@ofpiyush [\"nikhil@appsmith.com\"] is not to denote an array of values but simply a regex as [a-z]. The point of this being that referencing a string from an input does not escape the quotes while a user would expect it to. Simply put, the output of a javascript evaluation will always be a data type i.e number, string, array, object etc. When this value is put in an SQL / JSON / Mongo Plugin, the data type should assume it's corresponding representation. i.e string in SQL is 'hello' and number is simply 2. So the output of a text "John's apples" for SQL would be 'John\'s apples' because apostrophes need to be escaped due to the string representation of SQL while in mongo it need not be because the string representation requires double quotes (here double quotes need to be escaped).

We should however never attempt to do some sort of logical transformation as from an array to a regex piped list of values, that was not the intention here. The example is not referencing from a dropdown but from an input where the data type is a text, not an array. i.e text ["nikhil@appsmith.com"]

**Comment by ofpiyush** [comment]
Thank you for this, now we have an upper bound of "things we'll definitely not do" at `transforming data type in non-trivial ways`.

The lower bound seems to be set at `escaping behaviour works at the plugin level`.

While I agree with the sentiment, that's the bit I am not completely sure of.

For example:

> in mongo it need not be because the string representation requires double quotes (here double quotes need to be escaped

That's not entirely true. You can use single quotes in mongo and have double quotes in the value and it would work just fine. That makes it complicated at least with this plugin.

```
{ "$regex": '{{Input1.text}}' }
```
^ Need to escape at least single quotes. Values like `["nikhil@appsmith.com"]` would work without problems.

vs 
```
{ "$regex": "{{Input1.text}}" }
```
^ Need to escape at least double quotes. Values like `['nikhil@appsmith.com']` would work without problems.

vs 
```
{ "$regex": {{Input1.text}} }
```
^ Should we add any escaping quotes here? Doing so might break the behaviour of `$in`.

-------------------

In it's current form, I'm still not completely clear if we'll need to be aware of:

- The text surrounding the binding. (outside quotes or lack thereof seem to matter)
- The value in the binding itself (quotes, no quotes in case of string, values inside an array in case of `$in`)

A couple of things to validate:
- Is mongo an outlier here? How many other plugins accept different type of the quotes?
    - MySQL allows both single and double quotes for strings. Aside: [Some people like to watch the world burn](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes)
- Can we just escape every type of quote?

IMO, it should be one of:
- Use the quotes that the plugin allows for, we'll use the correct escaping.
- Every plugin works with just one kind of quotes and escaping works in tandem, everything else errors and tells you why.
- We don't escape at all, it's all on you.

Anything in between feels like magic that sometimes works, extra behaviour that I need to remember about appsmith.

**Comment by Nikhil-Nandagopal** [comment]
@ofpiyush the proposal is to give the user the final version of the value in the context of the plugin. i.e
is is expected that
```
{ "$regex": {{Input1.text}} }
```
evaluates to 
```
{ "$regex": "[\"nikhil@appsmith.com\"]" }
or
{ "$regex": '["nikhil@appsmith.com"]' }
```
whichever the plugin decides is correct for it.

But
```
{ "$regex": "{{Input1.text}}" }
```
is not expected to be handled and will simply return the correct version of the evaluation wrapped plus additional quotes around it.

**Comment by ofpiyush** [comment]
That would break the current working behaviour of
```
{ "$in": {{Input1.text}} }
```

**Comment by ofpiyush** [comment]
Sorry I wasn't clear, that would make it impossible to use `$in` in mongo. It expects an array, it will never get an array because we're adding quotes

**Comment by trishaanand** [comment]
Closing this because this gets handled as part of Prepared Statement.

**Comment by thebadking** [comment]
this should be re-opened as the prepared statement fixes this specific issue but breaks others, I would prefer having control over the query, also debugging with prepared statement is a pain as it flags the wrong position almost every time

**Comment by Nikhil-Nandagopal** [comment]
@thebadking you can manually disable prepared statements / smart substitution from the query settings to gain control over it.
