### ISSUE TITLE
[Bug]: Appsmith store modifying object's sub path temporarily inside evaluation

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/23132741/175900134-2ab8fe4e-5748-4ed4-bac6-9b3256d539a8.mov

Current storeValue implementation has below code to temporarily store the value to dataTree while running evaluation.
```
// momentarily store this value in local state to support loops
    _.set(self, `appsmith.store[${key}]`, value);
```
Here, as we are using `lodash's set`, keys like `test` and `test.two` are not treated as two different keys and hence the bug.

### Steps To Reproduce

1. Create a JSObject with below code
```
export default {
	myFun2: async () => {
		await storeValue("test", { "a": 1}, false);
		console.log("$$$",appsmith.store.test);
	  await storeValue("test.two", { "b": 1}, false);
		console.log("$$$",appsmith.store.test);
	},
	showStore: () =>  { console.log("$$$-appsmith.store", appsmith.store); return appsmith.store }
}
```
2. Open browser dev tools and add filter `$$$` ( just for ease of debugging )
3. run `myFun2` check the logs
4. run `showStore` and check to `appsmith.store` value

### Version

1.7.5

**Comment by ohansFavour** [comment]
I think the expectation here is that when the key to `storeValue` is a path, the corresponding value at that path should be updated.

**Comment by ohansFavour** [comment]
@tiger360 I see you had agreed with my earlier comment about updating the stored value if a path is supplied as key to `storeValue`. Having discussed with the team, our resolution is to keep the storeValue API's behavior as it is, for consistency with that of the browser's `localstorage` setItem.
We'd however fix the initial issue where a sub-path is temporarily modified during evaluation.

**Comment by tiger360** [comment]
I still don't get the behavior here : 
It's not respecting the order of execution 
plus I have the key stored and the path too in the "store"
![image](https://user-images.githubusercontent.com/5794444/176613457-efec9520-157b-4268-aa1d-8ad8666666c2.png)

**Comment by ohansFavour** [comment]
Hey @tiger360 ,

1. The issue with it not respecting the order of execution is fixed in this [PR](https://github.com/appsmithorg/appsmith/pull/14847) and will be merged as soon as possible.

2. When a path is used as a key in `storeValue`, it won't cause an update in store at that path. A new field with the path as key will be created in store.

Eg. storeValue("example.name", "felix", false) will create a field in store below

 {
  example.name: "felix"
 }

This is the same behaviour as the setItem of localStorage.
