### ISSUE TITLE
[Bug]: The internal server error is displayed in one of the git-connected application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#14829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The internal server error is displayed in one of the git-connected application

### Steps To Reproduce

1. connect the app to git
2. now refresh the page 
3. open the app in edit mode
4. the internal derver error is displayed

### Public Sample App

https://release.app.appsmith.com/app/regressionjun27/page1-62b935dab2680c2ce2064929/edit?branch=master

### Version

release

**Comment by vuiets** [comment]
@AnaghHegde could you take a look at this on priority if you haven't already?

**Comment by AnaghHegde** [comment]
@vuiets I have spent some time on this. Not able to reproduce this on other apps. I am having some issues in accessing BE logs from server @pratapaprasanna is working on a PR that will fix that issue.

**Comment by AnaghHegde** [comment]
@RakshaKShetty I am Not able to reproduce the error even in the app you have shared. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12005551/180744407-81a3a983-093a-4c3a-a616-170afe2504e9.png">

**Comment by ramsaptami** [comment]
This issue is intermittently reproducible on [this](https://release.app.appsmith.com/app/earworm/page1-632037c506ac9b7940792df8) app. Clear cache and reload the app if the error is not seen to consistently repro the issue

![image](https://user-images.githubusercontent.com/79509062/189870570-c8cbaaf5-4bad-4067-94fe-384f09ef39d8.png)

**Comment by AnaghHegde** [comment]
Changing the priority from Critical to High as the issue is intermittent

**Comment by ramsaptami** [comment]
[App](https://release.app.appsmith.com/app/earworm/home-6219207a0276eb01d22fec5e/edit?branch=master)

Consistently shows up for one of the apps on release right now. Attaching logs from devTools, hope that helps

![image](https://user-images.githubusercontent.com/79509062/211538474-b7c303e2-bc27-4e0e-b5de-3b077de30c87.png)

[earworm app_git status_500.zip](https://github.com/appsmithorg/appsmith/files/10382030/earworm.app_git.status_500.zip)

CC: @Parthvi12

**Comment by AnaghHegde** [comment]
Closing this issue as the issue is not reproducible anymore. 
cc - @ginilpg @infinitetrooper

**Comment by AnaghHegde** [comment]
@ramsaptami Can you share the app with me? Also why is this a HIGH priority issue? It is not reporducible.

**Comment by ramsaptami** [comment]
[This](https://github.com/appsmithorg/appsmith/issues/14829#issuecomment-1377112306) comment has all the info. IMO it's not a hard-to-reproduce issue. The steps are unclear but this error has been seen by multiple QA members on their apps hence high

**Comment by AnaghHegde** [comment]
@ramsaptami Can you share the screenshot or loom recording of this? I don't see this error on the app you have shared. I did verify this on the app you had shared.

**Comment by ramsaptami** [comment]
@AnaghHegde Looks like someone edited the app that caused it to lose its error state (had 107 commits pending when I opened the app this morning)
Please refer to my previous comments above for screenshots and browser logs of when the issue did occur. I'll take a look at getting the error back around

**Comment by Parthvi12** [comment]
Reopening the issue since I am seeing this in one of my app everytime I open the app.
![Uploading Screenshot 2023-03-01 at 10.40.25 AM.png…]()

**Comment by AnaghHegde** [comment]
@Parthvi12 Can you check the response of this API? What does it say exactly?

**Comment by Parthvi12** [comment]
@AnaghHegde 
<img width="1440" alt="Screenshot 2023-03-01 at 11 03 14 AM" src="https://user-images.githubusercontent.com/80334441/222053893-7202ac70-494f-43fd-b64c-a1b1258d7023.png">

**Comment by AnaghHegde** [comment]
Okay this is different from what @ramsaptami faced. Could you share this app with me?

**Comment by Parthvi12** [comment]
@AnaghHegde Shared this app with you https://release.app.appsmith.com/applications/623eecd66c86dd5be6fdd191/pages/623eecd66c86dd5be6fdd194/edit?branch=master , also I just noticed on opening git sync modal app is crashing, but its not reproducible in other apps.

**Comment by ginilpg** [comment]
@aakashDesign Please check this

**Comment by ginilpg** [comment]
@akash-codemonk Please check this

**Comment by akash-codemonk** [comment]
> @AnaghHegde Shared this app with you https://release.app.appsmith.com/applications/623eecd66c86dd5be6fdd191/pages/623eecd66c86dd5be6fdd194/edit?branch=master , also I just noticed on opening git sync modal app is crashing, but its not reproducible in other apps.

<img width="809" alt="git sync" src="https://user-images.githubusercontent.com/67054171/223357461-4f320830-d9cd-4e7c-8c6c-8ac29502b729.png">

Have fixed the issue locally where the app was crashing, had to handle `status` being undefined. In the change list it shows `Some changes are platform upgrades from Appsmith.`. Ideally I think we should have some kind of error state in the UI but I will go ahead with this for now as it will have the correct change list once the api starts working.  
cc @AnaghHegde

**Comment by akash-codemonk** [comment]
Oh okay cool will create a PR for the crash fix then.

**Comment by akash-codemonk** [comment]
Closing the issue as app crash has been fixed in https://github.com/appsmithorg/appsmith/issues/21237. Please reopen if there are any other concerns here. @AnaghHegde @Parthvi12 @ramsaptami
