### ISSUE TITLE
[Docs] Add info to make client app point to release api server. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#1482]
## Documentation Link 

https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md

## Describe the problem

1. Till there is way to setup up both the api server app and the client app together, users must be allowed access to release api server.

## Describe the improvement
1. Add info to connect client app to release api server.

**Comment by mathagician** [comment]
I want to work on this. Can you please assign this to me?

**Comment by sumitsum** [comment]
Hi @mathagician , very sorry, a pull request has been raised for this issue. Please select another one.

**Comment by sumitsum** [comment]
Fixed.
