### ISSUE TITLE
[Bug]: Background of certain tooltips does not match with the tooltips in rest of the app

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The background of tooltip for the `Icon Button` & `Input`, `PhoneInput` & `CurrencytInput` widgets is different from the other tooltips throughout the app.
https://www.loom.com/share/ecc14a9e4b1b4c509657f93b88194998
<img width="705" alt="Screenshot 2022-06-27 at 2 22 14 PM" src="https://user-images.githubusercontent.com/39921438/175900254-18bdde5c-5420-4b9f-93fa-bc1e811f7661.png">

### Steps To Reproduce

1. D&D an Icon Button widget.
2. Add a tooltip in the property pane.

### Version

Cloud

**Comment by dilippitchika** [comment]
@shadabbuchh this is intentional as these are error tooltips or tooltips which need to draw attention. 

Which part does it not match to?

**Comment by shadabbuchh** [comment]
@dilippitchika 
> this is intentional as these are error tooltips or tooltips which need to draw attention.

Understood. Does this hold good for tooltips displayed for `Icon Button` widgets as well?

> Which part does it not match to?

If you see for an `Icon Button` the background for the tooltips is white where as the tooltips in the rest of the app have a black background.
<img width="327" alt="Screenshot 2022-07-01 at 10 13 52 AM" src="https://user-images.githubusercontent.com/39921438/176824983-2afe3c6b-8a4a-4545-ab54-f3081c7523c3.png">
<img width="240" alt="Screenshot 2022-07-01 at 10 14 07 AM" src="https://user-images.githubusercontent.com/39921438/176824998-61aa2eb3-733e-4be4-9654-0a4921d4dfcf.png">

**Comment by dilippitchika** [comment]
So the case here is widgets follow a different design than the property pane. It's ok for them to be different.

**Comment by somangshu** [comment]
@ichik do you think this is a valid use case? If not please drop in a comment and close this issue

**Comment by ichik** [comment]
@somangshu editor's UI should not match widgets' UI.
