### ISSUE TITLE
[Bug]: Selected Border Radius & Box shadow are not visible for the widgets added inside List widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/95341241/175897793-fa7c1d0c-407c-403c-99f6-ab3871899215.png)

### Steps To Reproduce

1. Add List widget into canvas
2. Add Button widget onto List widget
3. Observe Button widget's property pane that Box Radius & Shadow are not visibly selected.

Note: This bug also happens for primary columns in table widget

### Version

Cloud / Production

**Comment by aswathkk** [comment]
The table widget's issue is different from this. Created a separate issue for that #14999

**Comment by dilippitchika** [comment]
@aswathkk what is the issue here?

**Comment by aswathkk** [comment]
@dilippitchika The value sent to these property controls is `undefined` somehow. I couldn't dig deeper. Someone with more context about ListWidget will be able to figure out the reason.

**Comment by dilippitchika** [comment]
Ok, assigning this to @jsartisan to check

**Comment by jsartisan** [comment]
Removing the issue from reskinning epic. We will fixing this in list v2

cc: @dilippitchika
