### ISSUE TITLE
[Bug]: No visible auto-suggestion for the widgets added inside List Widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/9050f53567e34532b866ef8dd5c8940d

### Steps To Reproduce

1. Add List widget onto canvas
2. Add any other widget inside list widget. for eg: Button widget
3. Try to bind Button widget with any other widget
4. Observe that widgets added inside list widgets are not showing auto-suggestions

### Version

Cloud / Production

**Comment by satbir121** [comment]
Stale issue. Can not reproduce.
