### ISSUE TITLE
[Bug]: Page Unresponsive while enabling 'server side pagination' on List widget using large datasets

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/77af40664bde49aea231d8b1131d31e0

### Steps To Reproduce

1. Add a query of data more than 1000 records
2. Add List widget onto the canvas
3. Bind query data with List widget
4. Try to enable 'server side pagination' from property pane
5. Observe the page get unresponsive after a moment

### Version

Cloud/Production

**Comment by somangshu** [comment]
Happens on the table widget too as pointed out by @Tooluloope

**Comment by SatishGandham** [comment]
@somangshu There is an issue for table widget i think. It is because users enable server side pagination without using it in the query, there by retrieving all the records. This has to be handled at server side and limit the number of records we return.



@chandannkumar, Did you use the pagination parameters in the query to limit the data?

**Comment by chandannkumar** [comment]
@SatishGandham I used simple query i.e SELECT * FROM users where role = 'Admin' ORDER BY id; and tried to enable server side pagination.

**Comment by somangshu** [comment]
@SatishGandham I understand, that Might be the case, Still wondering, Since the query retuned the same number of object, How is it that while we enabled SSR it failed for the same number of records (Since the params are not used at all)

**Comment by somangshu** [comment]
@dilippitchika found this to be a mix of user configuration and the way we handle the data in such scenarios. If the user does not set the prams required in the query to limit the response, things will load fine on client side pagination as the records that are rendered are based on the page size of the widget, but in case its server side pagination, this logic goes away and all items are now rendered which leads to excessive memory consumption that result in a unresponsive page.

This is happening from before and hence now a regression. We need to identify from the product / tech point of view how can this be made better. For now if the user sets his query correctly with the right pagination properties, it will work fine. For the same reason changing the priority to high

cc @SatishGandham @Tooluloope please add anything I might not be relaying well here!

**Comment by kamakshibhat-appsmith** [comment]
LGTM!
