### ISSUE TITLE
[Bug]: Input widget issues

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Error message when `Default Text` has more characters than the `Max Chars` is incorrect. It should be: `Default Text length must be less than or equal to Max Chars allowed.`
<img width="531" alt="Screenshot 2022-06-27 at 3 03 02 PM" src="https://user-images.githubusercontent.com/39921438/175911116-c5ff9607-cebe-4b4a-9c3d-81837f818cb9.png">

2. ~If a user enters some text in the widget and then sets a `Max Chars` such that it is less than the initial text entered, no error is thrown. (This is reproducible in release. Works fine in prod)
https://www.loom.com/share/1b94a690ce674008ac909f9dc6eb1ba1~

### Steps To Reproduce

1. D&D an `Input` widget.

### Version

Cloud

**Comment by somangshu** [comment]
@jnikhila can you provide copy for the given content
> Default Text length must be less than or equal to Max Chars allowed

@shadabbuchh for the 2nd point
- The error is not visible to the app viewers since they will not have access to the property pane
- The field is not dirty, Does it trigger the error once you make a small change focus & blur the input? How is the behaviour different in Prod and Release?


cc @souma-ghosh

**Comment by jnikhila** [comment]
@somangshu - I think it will be helpful to users if we tell them what the current max chars limit is and how many characters they have exceeded. In which case, the users will be able to reword the data.

Below are a few messages that we can use:

`Message 1 - The entered text exceeds the MaxChars limit of <AllowedNumberOfChars> characters by <TheExceededChars> characters.`

For example, message 1: "The entered text exceeds the MaxChars limit of 150 characters by 20 characters."

`Message 2 - You have exceeded the <MaxChars> characters limit for the <Field_Name> field by <TheExceededChars> characters.`

For example, message 2: "You have exceeded the 150 characters limit for the input1 field by 20 characters."

`Message 3 - The <Field_Name> field has a max length of <MaxChars> characters, and you have exceeded it by <TheExceededChars> characters.`

For example, message 3: The input1 field has a max length of 150 characters, and you have exceeded it by 20 characters.

Note - I've assumed the data in the angular brackets can be populated at runtime. Please let me know if that's not the case.

**Comment by shadabbuchh** [comment]
> * The field is not dirty, Does it trigger the error once you make a small change focus & blur the input? How is the behaviour different in Prod and Release?

@somangshu in Prod when some text is entered in the Input widget and then the `Max Chars` is set, we instantly see an error if the entered text has more characters that the max limit. However I am not able to see this behaviour in release.

**Comment by somangshu** [comment]
@shadabbuchh @jnikhila On further looking into the issue I have a different POV now. 

This issue only occurs when the default text is bigger than the max char allowed, that mean the app viewer has no control over this, I think ideally the error should be shown on the property pane itself.

Hence the error show to the end user today is invalid. Do you guys agree?

cc @dilippitchika need you inputs here

**Comment by somangshu** [comment]
> Prod when some text is entered in the Input widget and then the `Max Chars` is set, we instantly see an error if the entered text has more characters that the max limit. However I am not able to see this behaviour in release.

@shadabbuchh I think the end user cannot enter text more than the allowed char size even if they copy paste some text directly

**Comment by jnikhila** [comment]
@shadabbuchh and @somangshu 
Ideally, it should not allow the user to enter more chars than the max chars. However, the user can enter more characters than the max chars set in the default text as shown below:
<img width="1038" alt="User-Can-Enter-More-Characters-than-MaxChars" src="https://user-images.githubusercontent.com/99252011/176120957-d7da54f8-9d5a-4bdd-8d80-7c4be68b26f0.png">

I do agree that a message gives more clarity to user and I guess it'll be more convenient for user to see the field highlighted with error and error message shown on the editor. We can also display the error on the property pane.

**Comment by somangshu** [comment]
Yes that is the only way, The default text can be bound to an API that results in longer text and hence leave the input field in an invalid state. In case the field is in a form, the submit action would be disabled because of this invalid field, So it's obvious that the error need to be shown to the end user as well. 

Additionally, I agree that the error should also be should on the default text property.

cc @dilippitchika

**Comment by dilippitchika** [comment]
A few things
1. @jnikhila we can't use 2 or 3 as the error messages, app viewer doesn't know what Input 1 is. 
2. Agreed with the fact that we should show the error message on default text as well

So we need an error message in 2 places
1. The input widget itself
2. The default text field

Agreeing with @somangshu on this

**Comment by jnikhila** [comment]
@dilippitchika - Do you mean that the field names can't be evaluated at runtime?

But then, can the values for` <AllowedNumberOfChars> `and `<TheExceededChars> `be derived at runtime.

`
Message 1 - The entered text exceeds the MaxChars limit of <AllowedNumberOfChars> characters by <TheExceededChars> characters.
`

For example, message 1: **"The entered text exceeds the MaxChars limit of 150 characters by 20 characters."**

**Comment by dilippitchika** [comment]
The above message we can use, also message 1 will be really long. Are you sure you want to use this?

**Comment by jnikhila** [comment]
@dilippitchika - We can reword message 1 to be a bit shorter -

`Message 1 - The entered text exceeds the <AllowedNumberOfChars> characters limit by <TheExceededChars> characters.`

For example, message 1: **"The entered text exceeds the 150 characters limit by 20 characters."**

**Comment by shadabbuchh** [comment]
**Correction:** Issue 2 exists on prod as well.

**Comment by shadabbuchh** [comment]
@somangshu as discussed I have created a separate bug https://github.com/appsmithorg/appsmith/issues/14886 for the following issue:
> If a user enters some text in the widget and then sets a Max Chars such that it is less than the initial text entered, no error is thrown.

**Comment by dilippitchika** [comment]
@jnikhila this works, thanks
