### ISSUE TITLE
[Bug]: Fuzzy search and search tags in widget panel - On doing fuzzy search, extra / unrelated options are visible

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On doing a fuzzy search with various options as per this [Notion](https://www.notion.so/appsmith/Widget-Explorer-Fuzzy-search-b234cb24ef3244fe90e36b05eca664ef) doc, the user, along with the appropriate options, gets more unrelated widgets also listed.

### Steps To Reproduce

1. Create a new page in an application.
2. In the widgets panel, using [this](https://www.notion.so/appsmith/Widget-Explorer-Fuzzy-search-b234cb24ef3244fe90e36b05eca664ef) document, try searching for various widgets with the search options specified in the document.

The following issues are observed - 

1. If we type Visual, along with Map chart and Chart, Modal is also show. Modal should not be shown
<img width="271" alt="FuzzySearch_Visual" src="https://user-images.githubusercontent.com/101863839/176094059-de3ea6f7-ab55-41da-abcc-796595febeee.png">

2. If we type "upload", along with Filepicker, Audio is also shown. Audio should not be shown
<img width="255" alt="FuzzySearch_Upload" src="https://user-images.githubusercontent.com/101863839/176094177-bbeb72c4-72c9-44b7-9aa7-f9aae267468e.png">

3. If we type "total" in search, along with Currency Input, Modal also is shown. Modal should not be shown.
<img width="261" alt="FuzzySearch_Total" src="https://user-images.githubusercontent.com/101863839/176094302-c1de91c8-5520-45f6-aca0-9c7bcce73705.png">

4. If we type "tags" in search, it should bring up Multi-select. However, along with Multi-select, other widgets are also shown. 
<img width="271" alt="FuzzySearch_Tags" src="https://user-images.githubusercontent.com/101863839/176094677-ac14c756-0528-46e8-a016-8b2ffbde25e0.png">

5.  If we type "submit" in search, it should bring up Button, Button Group and icon button. However, along with them, other widgets are also shown.
<img width="261" alt="FuzzySearch_Submit" src="https://user-images.githubusercontent.com/101863839/176094876-f2b13478-c987-4ae4-86f4-f615650915bd.png">

6.  If we type "stars" in search, it should bring up Rating. However, along with it, other widgets are also shown.
<img width="260" alt="FuzzySearch_Stars" src="https://user-images.githubusercontent.com/101863839/176094993-d60f7ba5-2116-49c7-98b8-e534d69092f6.png">

7. If we type "rte" in search, it should bring up Rich Text Editor. However, along with it, other widgets are also shown. 
<img width="270" alt="FuzzySearch_RTE" src="https://user-images.githubusercontent.com/101863839/176095331-8977d4e8-a8d8-4ceb-90d4-c9ecc233dcf2.png">

8. If we type "Popup" in search, it should bring up Modal. However, along with it, other widgets are also shown.
<img width="260" alt="FuzzySearch_Popup" src="https://user-images.githubusercontent.com/101863839/176095411-38fdec77-f97c-4d43-862e-22a7eea66627.png">

9. If we type "Player" in search, it should bring up Audio. However, along with it, other widgets are also shown.
<img width="247" alt="FuzzySearch_Player" src="https://user-images.githubusercontent.com/101863839/176095483-d5c0c179-fc62-419c-9489-12f4a9c3eb32.png">

10. If we type "photo" in search, it should bring up Camera. However, along with it, other widgets are also shown.
<img width="256" alt="FuzzySearch_Photo" src="https://user-images.githubusercontent.com/101863839/176095551-462b4b57-0861-46ae-b8a1-a3800ac0e5a9.png">

11. If we type "percent" in search, it should bring up Progress. However, along with it, other widgets are also shown.
<img width="287" alt="FuzzySearch_Percent" src="https://user-images.githubusercontent.com/101863839/176095609-a984ae6d-7b2c-4bcd-8073-dd7879231945.png">

12. If we type "pdf" in search, it should bring up Document Viewer. However, along with it, other widgets select are also shown.
<img width="252" alt="FuzzySearch_Pdf" src="https://user-images.githubusercontent.com/101863839/176095662-43a4d84e-fd23-437b-b66f-271b9df257e0.png">

13. If we type "parent" in search, it should bring up Container. However, along with it, other widgets are also shown.
<img width="260" alt="FuzzySearch_Parent" src="https://user-images.githubusercontent.com/101863839/176095721-2a3ed660-11b0-47ad-aca8-83eb1610580e.png">

14. If we type "number" in search, it should bring up Input. However, along with it, other widgets are also shown.
<img width="258" alt="FuzzySearch_Number" src="https://user-images.githubusercontent.com/101863839/176095821-8db03301-ba3f-40bd-bcb0-3508f23350c4.png">

15. If we type "line" in search, it should bring up Divider. However, along with it, other widgets are also shown.
<img width="257" alt="FuzzySearch_Line" src="https://user-images.githubusercontent.com/101863839/176095871-8f0eac2f-5694-4ab8-b67c-4fb53aa30c68.png">

16. If we type "group" in search, it should bring up Container/Form/Button Group/Radio Group/ Checkbox Group/ Switch group.. However, along with them, other widgets are also shown.
<img width="269" alt="FuzzySearch_Group" src="https://user-images.githubusercontent.com/101863839/176096002-5cf73ee8-4f1d-4498-9a95-d25561740e88.png">

17. If we type "graph" in search, it should bring up map/map chart. However, along with them, text widget is also shown.
<img width="249" alt="FuzzySearch_Graph" src="https://user-images.githubusercontent.com/101863839/176096068-85be1ec6-f48a-4d9b-ab49-098500954c46.png">

18. If we type "embed" in search, it should bring up iframe. However, along with it, input widget is also shown.
<img width="279" alt="FuzzySearch_Embed" src="https://user-images.githubusercontent.com/101863839/176096135-89e8d5bb-c7b0-4d3a-82ae-c11dd8204cb2.png">

19. If we type "div" in search, it should bring up Container and Divider. However, along with them, other widgets are also shown.
<img width="263" alt="FuzzySearch_Div" src="https://user-images.githubusercontent.com/101863839/176096202-15874e99-a1da-4133-90fd-adac16dbffaf.png">

20. If we type "dialog" in search, it should bring up Modal. However, along with it, table widget is also shown.
<img width="275" alt="FuzzySearch_Dialog" src="https://user-images.githubusercontent.com/101863839/176096267-2eb52b93-f2b2-4777-b93a-6cd344ea72c4.png">

21. If we type "datagrid" in search, it should bring up Table. However, along with it, other widgets are also shown. 
<img width="255" alt="FuzzySearch_Datagrid" src="https://user-images.githubusercontent.com/101863839/176096370-60331db6-9cc4-42d7-97fc-1cd7760eadc6.png">

22. If we type "choice" in search, as per Notion doc, it should bring up Radio Group. However, along with them, other widgets are also shown. As per my understanding, since checkbox and checkbox group also enable the user to choose, they can be present in the search. But all the other widgets should not be shown. 
<img width="263" alt="FuzzySearch_Choice" src="https://user-images.githubusercontent.com/101863839/176096601-f1b9af69-03f7-48b4-b7ac-73a2166b570d.png">

23. If we type "call" in search, it should bring up Phone Input. However, along with it, other widgets are also shown.  
<img width="263" alt="FuzzySearch_Call" src="https://user-images.githubusercontent.com/101863839/176096694-18f2905a-119d-4626-8898-6a4cdfc2616f.png">

24.  If we type "calendar" in search, it should bring up Date Picker. However, along with it, camera widget is also shown. 
<img width="251" alt="FuzzySearch_Calendar" src="https://user-images.githubusercontent.com/101863839/176096749-bffde0c3-5e64-44c2-8fa4-8cd4f5e527e4.png">

25.  If we type "amount" in search, it should bring up Currency Input. However, along with it, other widgets are also shown.
<img width="237" alt="FuzzySearch_Amount" src="https://user-images.githubusercontent.com/101863839/176096807-52c15889-df91-4095-9c7c-61cb115bbaa1.png">

26.  If we type "sound" in search, it should bring up Audio and Audio Recorder. However, along with it, other widgets are also shown. 
<img width="274" alt="FuzzySearch_Sound" src="https://user-images.githubusercontent.com/101863839/176096899-6b847358-6322-4016-81cd-c7793b8ea5c0.png">
 

### Version

Release

**Comment by rohitagarwal88** [comment]
@prsidhu take this issue first

**Comment by btsgh** [comment]
Some observations - 
1. If we type stars in the search box, both Rating and StatsBox widget are shown. This is in correct. As per notion doc, only Rating widget should be shown.

**Comment by prsidhu** [comment]
@btsgh I've updated the threshold for fizzy search, so #1 should be resolved now. As for #2 and #3, I think it's reasonable to fix them. However, string match in displayName of the widget isn't working too well. We can include the desired strings in the searchTags to support these use cases. What do you suggest?

**Comment by btsgh** [comment]
@prsidhu - not sure I get your proposed resolution for #2 and #3.. " including in the searchTags ".. where will these get included and what will be the impacted areas, if any? @rohitagarwal88 - any thoughts?
