### ISSUE TITLE
[Bug]-[98]:Save Theme does not support 'space' to save as a theme name

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Saving Theme does not support 'space'. The name with the space is not getting saved as a theme name

![image](https://user-images.githubusercontent.com/95341241/175950250-e654366e-8502-4559-915a-fa0f484bbc65.png)

### Steps To Reproduce

1. Click on canvas to see theming properties
2. Click on 3 dots and click on 'save theme'
3. Try to save theme name with names which have spaces. for eg: My new theme
5. Observe that it does not support spaces as a name and throws error

### Version

Cloud/Production

**Comment by dilippitchika** [comment]
@iamrkcheers can you pick this up? This uses a validation fuction which doesn't support spaces yet. We can add that.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 49 |
| Effort (months)  | 0.25 |

**Comment by dilippitchika** [comment]
@dhruvikn please pick this up once you are done with the current issue
