### ISSUE TITLE
[Bug]: Modal overlaps with nav bar in smaller screens

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#14849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i open a large modal in the view mode for small screens it overlaps with the nav bar.
![image](https://user-images.githubusercontent.com/19730984/176098752-12b0d106-b5d7-452d-b11c-4f4aafde80dc.png)

When a modal is open it should take the highest priority

### Steps To Reproduce

1. Add a large modal
2. Deploy the app
3. Open the modal
4. Observe it is blocked by nav bar

### Version

Cloud 1.7.5

**Comment by somangshu** [comment]
@rohitagarwal88 @rahulramesha please get this prioritized

**Comment by Sripriya93** [comment]
Have verified with button on click action to open modal widget, made the Modal larger till the limit

![image](https://user-images.githubusercontent.com/104895602/179222175-1605f613-9938-49d2-9a10-00f52f699e0d.png)
