### ISSUE TITLE
[Bug]: Cannot fork templates with multiple pages from platform

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#14852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Forking a template with multiple pages throws an internal server error on the Platform.

### Steps To Reproduce

1. Go to app.appsmith.com/templates/<App ID>
2. Click on "Fork this Template"
3. This throws an "Internal server error"

### Version

Cloud - 1.7.5

**Comment by Parthvi12** [comment]
QA verification is blocked for this issue on release, once the PR gets merged to master, will test this issue on Prod again.

**Comment by Richarex** [comment]
This issue is resolved now, user is able to Fork any template without any internal server error.
