### ISSUE TITLE
[Feature]: watch variables in JSobjs

### ISSUE THREAD

**Issue by unknown1337** [appsmithorg/appsmith#14859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Goal: execute a function X when a (store) variable Y changes
How: 
1. at each function & UI element that can change the store variable Y call the function X [current appsmith WoW]
2. create a watcher/ register a watcher when a store variable changes. see e.g. [vuejs watchers](https://vuejs.org/guide/essentials/watchers.html#basic-example)

### Why should this be worked on?

 simplicity & maintainability, 'Appsmith' will register all functions X that need to be executed once a variable changes iso that the appsmith 'user' needs to register the function X at all places where the variable to be watched Y can be changed.

**Comment by Nikhil-Nandagopal** [comment]
@unknown1337 I believe we have this issue tracked here #2639
