### ISSUE TITLE
[Bug]: Show linting error for names which are not supported as property by JSObject

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, user shouldn't use following `variable` or `js action / function` name in JSEditor else internal fields will get overwritten and errors will be expected due to dataTree going into bad state

- `name`
- `body`
- `ENTITY_TYPE`
- `actionId`
- `bindingPaths`
- `dependencyMap`
- `dynamicBindingPathList`
- `meta`
- `pluginType`
- `reactivePaths`
- `variables`

### Steps To Reproduce

https://user-images.githubusercontent.com/23132741/176170197-459cabb3-c4e0-40c9-a55a-fc5a65ba3b81.mov

1. Create a JSObject
2. Add `variables` as property 
3. Try to add new random variable and notice `error` 

It could be either `parsing error` , `cyclic dependency error` depending upon variable name and JS code in JSObject

> Note: errors for different reserved name could be different. 

### Version

1.7.6

**Comment by bharath31** [comment]
@ohansFavour @Rishabh-Rathod what are the next steps here?

**Comment by Rishabh-Rathod** [comment]
After the dataTree split, this issue is resolved.
