### ISSUE TITLE
[Bug]: JSObject variable value changes should reflect in dataTree

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When variable value is changed in a JS object, changes must be reflected as soon as save action is completed and not after a page refresh as is the functionality right now. Refreshing page to update dataTree is not the expected behaviour a user expects 

### Steps To Reproduce

1. Define a variable in a JS object and display this value on the console or as an alert message
2. Change this value and run the function again to show this updated value - observe that the old value is still being executed
3. Refresh the page and run the function - observe that the new value is now executed
4. Repeat the steps and observe that a page refresh is needed to update dataTree

### Version

Cloud

**Comment by rishabhrathod01** [comment]
This does work in production. Please reopen if didn't work for any specific case.
