### ISSUE TITLE
[Bug]: JSObject property not getting deleted from the dataTree

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#14870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we remove variable from JSObject, the old removed variables still are present in JSObject dataTree.
<img width="1414" alt="Screenshot 2022-06-28 at 3 46 51 PM" src="https://user-images.githubusercontent.com/23132741/176200409-b438a35d-774e-4018-960a-d4f79895f0bc.png">

### Steps To Reproduce

1. Create a JSObject
2. Remove variable
3. Check browser logs => `dataTree` to verify is variables are present yet or not.

### Version

1.7.6

**Comment by Rishabh-Rathod** [comment]
Seems like this issue also got closed with #14842, I am unable to reproduce it anymore. 

cc: @ramsaptami
