### ISSUE TITLE
[Bug]: Contributors page should check for vaild email

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#14884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Bug]: Contributors page should check for vaild email

### Steps To Reproduce

Steps
1) Goto "Admin Page"
2) click the integration
3) click + 
4) Add invalid email
5) error should be displayed
https://www.loom.com/share/877471d998a74a5d8ea1571b6928d381

### Public Sample App

https://app.appsmith.com/app/saas-integration-manager/admin-page-61c45b5aa99ba037d2f3def0?branch=master

### Version

cloud

**Comment by sumitsum** [comment]
Closing this issue because we are phasing out the SaaS integrations manager app.
