### ISSUE TITLE
[Bug]: No error is thrown if the input widget contains characters greater than the max limit

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No error is thrown if one enters some text in the Input widget and then sets a `Max Chars` property such that it is less than the number of characters entered.
https://www.loom.com/share/1b94a690ce674008ac909f9dc6eb1ba1

Please note the following:

1. No error is triggered once you make a small change focus & blur the input.
2. On hitting `Backspace` the characters get erased. (No error is triggered)
3. A developer is not allowed to further enter any characters.
4. There is no error visible for the appsmith dev on the property pane

Please refer to the below comment to get clarity on the solution for this issue:
https://github.com/appsmithorg/appsmith/issues/14830#issuecomment-1168572017

### Steps To Reproduce

1. D&D a Input widget.
2. Enter 20 characters.
3. Not set a limit on the `Max Chars` property.

### Version

Cloud

**Comment by somangshu** [comment]
@techbhavin build an understand of what can be achieved from the above. Get in touch with @dilippitchika if you need clarity on the Requirement

cc @sbalaji1192 please review any changes w.r.t the same
