### ISSUE TITLE
[Task]: Miro plot for mapping of required data types in Datatype handling

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#14882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

List all datatypes on Client, Server side and JSON supported types and map on miro board
This helps us to get clear picture on all datatypes to be handled and plan better for the implementation

**Comment by ChandanBalajiBP** [comment]
Ref: https://miro.com/app/board/uXjVO2Pq1hs=/

**Comment by subrata71** [comment]
According to the last meeting we are not supposed to spend time doing this. That might add delay to the progress. That's why we have closed this issue.
