### ISSUE TITLE
[Feature] Integration with Postman Tool

### ISSUE THREAD

**Issue by harshloco** [appsmithorg/appsmith#1488]
## Summary

Adding functionality to import existing Postman collection into **appsmith** as a REST API.
The existing Api builder form can be used to populate all the data from POSTMAN.
Helps to speed up things when the tool is used for organisations' which host their API's collection on postman and wants to integrate with **appsmith** 

## Motivation

I was looking into **appsmith** as a way to provide live data insights to non-technical staff for my organisation, in turn reducing some of the debugging/support requests.

I was going through tutorials on how to connect with MySql and Rest API.
MySql is a good option, but an API gives me more power to get data from backend.

At my organisation we have a collection on POSTMAN.

When I tried setting it up, I was stumped just by the thought of adding each API into **appsmith** from POSTMAN.
And therefore, got an IDEA of automatically integrating collection from POSTMAN.

## Additional Context

![image](https://user-images.githubusercontent.com/5271603/97771688-a1957080-1b93-11eb-8fc1-d9a710adb62b.png)

![image](https://user-images.githubusercontent.com/5271603/97771705-bd991200-1b93-11eb-8a27-f16eb6db8f8f.png)

**Comment by Nikhil-Nandagopal** [comment]
@harshloco thank you for the feature request! This is a great request and definitely makes sense. We'll add this to our roadmap. In the meanwhile, if you'd like to import your APIs quickly, you can use our CURL importer.  😃

**Comment by kaprinsoftware** [comment]
Hey @harshloco  We have built a utility that can import a swagger / openapi spec or a postman collection export into Appsmith by defining Datasources and add all the endpoints defined.
If you are interested in using it we can continue the conversation.
