### ISSUE TITLE
[Bug]: JS toggle is not working for vertical alignment property

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/fd17c1002a7148eeae4d78cd70b2dee9

### Steps To Reproduce

1. Drag and drop a table widget
2. Click on any column from property pane
3. Click on JS toggle for vertical alignment property
4. Observe that by default LEFT populates and clearing the data does noting

### Version

Cloud

**Comment by vivekverma2312** [comment]
@aswathkk We have a work around for this. If user enter `TOP | CENTER | BOTTOM` and click on JS toggle then user can go back to select existing options.
https://www.loom.com/share/ba0c31cd18784f1ea4e75b910585e779
Removing blocker label and adding critical label to it.

**Comment by btsgh** [comment]
When we empty the field and click anywhere outside, the CENTER text automatically gets added to the field
