### ISSUE TITLE
[Docs]: [AWS AMI] - Update to latest Appsmith release

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#14891]
Refer to the [slack](https://theappsmith.slack.com/archives/C0341RERY4R/p1656444464610149) discussion:

Update the broken links:

* Configure a custom domain for your App
* Find Application Credentials
* Updating your Appsmith installation

Also, add Update your Appsmith installation.

* Configure a custom domain for your App - link/step has to be removed.
Instead we can add link to the Custom domain setup for docker in Further Readings section.

**Comment by jnikhila** [comment]
@sum35h - Could you please provide first draft or pointers for the doc?

**Comment by sum35h** [comment]
Points to add for updating Appsmith running on the aws ami:
## Updating manually
To update Appsmith  manually, ssh into the ec2 instance with the username `appsmith` and run the following command:
`cd appsmith && sudo docker-compose pull && sudo docker-compose rm -fsv appsmith && sudo docker-compose up -d`

## Enabling Appsmith Auto-updates 
If your Appsmith setup does not have auto-update enabled (i.e. it will not have Watchtower container running along with Appsmith in the host machine) You can enable auto-update by followin the following steps:
SSH into the ec2 instance with username `appsmith`
Change directory to `/appsmith`
docker-compose down
Open the `docker-compose.yml` file with any text editor and uncomment all the lines that are commented out (line 13-23).
Run the command:
`docker-compose up -d
`

**Comment by jnikhila** [comment]
Published.
