### ISSUE TITLE
[Bug]-[560]:Curl import does not work with figma api's

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run a Curl import with Figma API, an error is thrown. 
<img width="1219" alt="curlimport_figmaapi" src="https://user-images.githubusercontent.com/101863839/176382424-46f6efb4-4288-47d3-b3a6-c3d0b8fdc704.png">

### Steps To Reproduce

1. Open an application on Release
2. Go to Queries and click the plus sign next to it, choose New cURL Import
3. Paste this code in the text field - 

curl -H 'X-FIGMA-TOKEN: figd_PqDJxGgXcL37oy6OCCBgnT_-C0hkAAFkO1f4pUd4' 'https://api.figma.com/v1/files/RbXQA33UJQZvqrwDCnGX9j/nodes?ids=0%3A1'

4. Click on Import. This succeeds. 
5. Now click on RUN - An error is thrown

https://www.loom.com/share/a47305bbb1814f929bc0ce5741dde16f

### Version

Release

**Comment by AmanAgarwal041** [comment]
We are adding a figma api from the front end and the server handles the execution of that api. But when the server executes the action, the api throws an error from the cloudfront with statusCode `400 BAD_REQUEST`. Here's the response from the cloudfront:

```
[2049,ActionExecutionResult(statusCode=400 BAD_REQUEST, title=null, errorType=null, headers={"Content-Type":["text/html"],"Connection":["keep-alive"],"Server":["awselb/2.0"],"Date":["Thu, 14 Jul 2022 11:04:29 GMT"],"Strict-Transport-Security":["max-age=31536000; includeSubDomains; preload"],"X-Cache":["Error from cloudfront"],"Via":["1.1 a1077ac119cdde99fff02ef7322b33b8.cloudfront.net (CloudFront)"],"X-Amz-Cf-Pop":["DEL51-P2"],"X-Amz-Cf-Id":["c5WMlDwqx8IzxCRkAJ0hfn4zfL_Lz2X8Hqdvv6X38fbnxuESNnEdCQ=="],"content-length":["122"],"X-APPSMITH-DATATYPE":["TEXT"]}, body=<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
</body>
</html>, readableError=null, isExecutionSuccess=false, messages=[], request=ActionExecutionRequest(actionId=62cfcfa6ea41e76c83edf6b3, requestedAt=2022-07-14T11:04:27.907578Z, query=null, body=[B@254f35a, headers={"X-FIGMA-TOKEN":["figd_E-xdPtoKwkfnn6_By-nbNh-5lnp7b1JA2v2b3rjo"]}, httpMethod=GET, url=https://api.figma.com/v1/files/ywx3aWsV1NU8s9OvoUudSz/nodes?ids=0%3A1, properties=null, executionParameters=null, requestParams=null), dataTypes=null, suggestedWidgets=null)]
```

>

**Comment by sondermanish** [comment]
The curl imports the statement to API datasource, here API datasource is throwing the error, Postman responds with same status code 400 when `Host` header is omitted. Investigating further.

**Comment by rohan-arthur** [comment]
added tag `core query execution` as a dummy to get this issue into data platform pod

**Comment by sribalajig** [comment]
@sondermanish pls add you findings here

**Comment by btsgh** [comment]
@sondermanish  @sribalajig - when I try the same in Postman -
1. Import -> Raw Text -> Paste the [command](curl -H 'X-FIGMA-TOKEN: figd_PqDJxGgXcL37oy6OCCBgnT_-C0hkAAFkO1f4pUd4' 'https://api.figma.com/v1/files/RbXQA33UJQZvqrwDCnGX9j/nodes?ids=0%3A1') and click on Continue -> Import 
2. The GET url that gets generated on Postman is - https://api.figma.com/v1/files/RbXQA33UJQZvqrwDCnGX9j/nodes?ids=0%3A1
3. On clicking Send, this works fine. 


Same steps when tried through Appsmith Curl Import, the Get url generated through CURL import for above figma link is - https://api.figma.com/v1/files/RbXQA33UJQZvqrwDCnGX9j/nodes?ids=0:1

**Comment by sumitsum** [comment]
Rest API 6m usage: 5600
% of users impacted: 5
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 280 |
| Effort (months)  | 0.25 |

**Comment by prapullc** [comment]
@sumitsum :
The created a new token again and added the required field ie. File Key and Id from our existing Figma Files . Tried Query to Get Images and Get File node, both worked fine displayed results as on Fimga API Document.

**Comment by btsgh** [comment]
Tested and found to be fixed on release.

**Comment by SINHOLEE** [comment]
for me, It has same problem when i added `content-length` in headers
but It is ok when remove `content-length`
