### ISSUE TITLE
[Task]: Fork and upgrade the chrome profile parsing library

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#14898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We use this library to parse our chrome profiles.
https://github.com/saucelabs/tracelib
It uses code from chrome devtools as is. Since the repository hasn't been update in 3 years, it might break any time with a new release of chrome.

Update the code used from chrome devtools with the latest ones.

**Comment by marks0351** [comment]
This issue has been worked on and is merged.
