### ISSUE TITLE
[Bug]: Unable to Connect to ElasticSearch Database

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#14909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user tried to connect to their ElasticSearch database after doing some changes in their db and got the following error:
`class [Ljava.lang.Object; cannot be cast to class [Lorg.apache.http.Header; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lorg.apache.http.Header; is in unnamed module of loader org.pf4j.PluginClassLoader`
They can connect via Postman and it was working via Appsmith previously too, but they recently upgraded to version 1.7.4.
After downgrading to Elasticsearch 7.10.3 it still did not work.

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100127475#part_id=comment-164629100127475-15430502088

### Steps To Reproduce

The user did some changes to their ElasticSearch DB. The connection has stopped working and they got an error.

### Version

Self-Hosted - v1.7.4

**Comment by nik13** [comment]
effecting 7.16.2 as well. previous it was working.
