### ISSUE TITLE
[Bug]: api call with a failed response code causes the JSfunction to hang

### ISSUE THREAD

**Issue by unknown1337** [appsmithorg/appsmith#14901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. when I create JSObj calling an API that replies with a 401 status causes the rest of the JSOBJ function to hang = NOK. This also implies that a catch block will never be reached [NOK2]

### Steps To Reproduce

1. Create JS obj
2. code: 
`export default {
	logoutNow433423: async ()=>{
		await storeValue("auth",undefined)
		try
		{
			//await apiSupabaseLogout.run() ;// api that will respons with a error as I missed a parameter
		}
		catch(err){
			// this code will never be reached.... [NOK!!]
			console.log("something went wrong")
			console.log(err);
		}
		console.log("finished execution")		
	}
}`

4. execute function
(1) observe that the function keeps hanging
(2) neither the console log finished execution NOR " something went wrong" was reached
(3) a 'random error with a is undefined' is created 
(note, commenting out the line with await will cause the function to run sucessfully
![image](https://user-images.githubusercontent.com/5968968/176410417-e0c6a646-d9ce-4b7f-979f-cbba44a58a1c.png)

### Version

cloud @ 29/06/2022

**Comment by Nikhil-Nandagopal** [comment]
@unknown1337 this seemed to work for me. Could you please share a sample app where we can reproduce this?
