### ISSUE TITLE
[Feature] Return the list of users for all organizations during homepage load

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1490]
## Summary

Currently we have an API which can fetch the users per organisation. We need an API which can fetch the users for all orgs related to the user. This will reduce the amount of network traffic required to load the home page.

## Motivation

We need to show the user profile icons for all the organizations that a user is a part of. Refer to screenshot below.

## Additional Context

<img width="775" alt="Screenshot 2020-10-15 at 11 57 30 AM" src="https://user-images.githubusercontent.com/458946/97772957-b6610c80-1b71-11eb-91cf-02bb87d01f40.png">

**Comment by nidhi-nair** [comment]
@mohanarpit As an aside to this feature, there seems to be a mismatch in the usage of Workspace and Organization between this screen and production, inside of production itself.
<img width="571" alt="Screenshot 2020-11-03 at 2 47 07 PM" src="https://user-images.githubusercontent.com/5298848/97967947-f9c2b180-1de3-11eb-8374-bdf8c72a449b.png">
<img width="546" alt="Screenshot 2020-11-03 at 2 48 42 PM" src="https://user-images.githubusercontent.com/5298848/97967955-fcbda200-1de3-11eb-9e7c-1a91467fce60.png">

**Comment by mohanarpit** [comment]
@nidhi-nair Good catch. The terminology should be "Organization" everywhere. Incase you see any text in the UI that refers to "workspace", please create a bug for this. 

When the designs were being made, we were referring to it as a "Workspace" but then decided to call it "Organization" at the end.
