### ISSUE TITLE
[Bug]: issue with current item in List widget

### ISSUE THREAD

**Issue by unknown1337** [appsmithorg/appsmith#14900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to bind currentitem.id in an *Icon* button click handler within a list:
1. auto complete does not work, current item is not recognized in the action button [NOK]
2. the currentItem.id is actually passed to the function [OK]
3. this ID is then used in an API request which hangs (await will never finish, even not after the 10s timeout [NOK]
4. replacing currentItem.id with List1.selectedItem.id will cause everything to work fine [OK]

Maybe related to https://github.com/appsmithorg/appsmith/issues/8677 

Example:
A. function:
![image](https://user-images.githubusercontent.com/5968968/176404318-66deb9e9-c7a0-4fb3-80ec-cee538a97caf.png)
B. Not working icon button [no console.log done reached]
![image](https://user-images.githubusercontent.com/5968968/176404370-2b67d248-21c7-44a7-9067-54538dd49cd2.png)
C. working icon button 
![image](https://user-images.githubusercontent.com/5968968/176404606-cb59877a-95f3-4f93-a8fa-4111a4c99d3f.png)

### Steps To Reproduce

0. 
1. create a JSObjfunction with testfunc:(id)=>{console.log(`start id:${id}`); apixxx.run({id:id}); console.log("done")}
2. create an API apixxx
3. create a list with items
4. add an *icon* button to the list
5. in the action/ onlick property select the JSObj function and as argument id type {{cur....  -> not autocompleted). then type {{currentItem.id}} yourselve
6. clicking on the button will result in a console.log with only "start id: 1", but will not show "done"

### Version

Cloud @ 29-06-2022

**Comment by satbir121** [comment]
Out of the 4 issues mentioned:

1. auto complete does not work, current item is not recognized in the action button [NOK]
2. the currentItem.id is actually passed to the function [OK]
3. this ID is then used in an API request which hangs (await will never finish, even not after the 10s timeout [NOK]
4. replacing currentItem.id with List1.selectedItem.id will cause everything to work fine [OK]

1. Autocomplete is working as expected.
3. Performance issue is also not reproducible.

[Checked in this app](https://app.appsmith.com/app/public-testing-issues/issue14900-637f30924a42f47b0d2c5780/edit)
