### ISSUE TITLE
[Docs]: Disable overriding the ssh key config through identityFile to avoid git auth failure 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#14905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/version-control-with-git/connecting-to-git-repository

### Describe the problem

When user is working with local development ssh config file can have default ref for IdentityFile mapped to 
`~/.ssh/id_ed25519` as per latest security guidelines followed by platforms like github, gitlab etc. This creates a problem to connect the appsmithb application with git remote provider, as we generate the SSH public and private key using Jgit library and use these keys to authenticate the communication with the remote repo. To avoid overriding the keys generated by Jgit we need to comment or remove the identity file reference from the Host setting.  

### Sample file content of `/.ssh/config`:
**Before:**
```
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
```

**After:**
```
Host *
  AddKeysToAgent yes
  UseKeychain yes
  #IdentityFile ~/.ssh/id_ed25519
```

**Comment by jnikhila** [comment]
@vuiets - Is this ready for doc team?

**Comment by vuiets** [comment]
@jnikhila do you have enough to go on or do you need a draft for this?

**Comment by jnikhila** [comment]
@vuiets - A draft will be helpful.

**Comment by danciaclara** [comment]
@abhvsn hey this slipped from our radar. If this is not related to adding anything in the instance configuration files, then ideally this shouldn't reside in the product docs. Could you confirm where this setting is to be added.

**Comment by infinitetrooper** [comment]
Closing this as it's stale, will reopen if required.
