### ISSUE TITLE
[Docs]: Java heap specs which Appsmith is hosted 

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#14906]
<p>Users would like to know about necessary resources for hosting Appsmith, and information about improving Appsmith instance performance by increasing available resources (via the `APPSMITH_JAVA_HEAP_ARG` variable in the .env file).</p>
<p>Discord thread here: https://discord.com/channels/725602949748752515/760761686549463060/991580506988748893</p>

**Comment by jnikhila** [comment]
@sum35h - Could you please help with the statistics that we can add to docs?
