### ISSUE TITLE
[Bug]-[9600]:new JS function does not show in the run dropdown until refresh

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#14916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/94514895/176615689-e91f1318-8765-4e64-b77d-6e6b99ec6026.mov

when I add a new js function, it is not available to be run

### Steps To Reproduce

1. create a new js object
2. ignore the default added functions, add one more below them
3. enter some valid statement. I enetered `return "hi`
4. expand the dropdown next to the `Run` button

--> you don't see the newly added function

5. Refresh the page

--> now you see the newly added function

### Version

Cloud

**Comment by bharath31** [comment]
not able to reproduce this anymore
