### ISSUE TITLE
[Bug]: Un-necessary evaluations

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#14917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We can see two evals happening for one change in property from the property pane. This seems un-necessary

https://user-images.githubusercontent.com/103687/176639630-be6ec498-a25f-4d09-b41f-5e998a581a04.mov

Note 1: This was seen during development.
Note 2: During triage, we might find more scenarios.

### Steps To Reproduce

The following are the steps I had taken, but I suspect other scenarios might also reflect this issue.

1. Add a modal widget.
2. Add a checkbox group to the widget.
3. While observing the console, add an option to the checkbox group widget from the property pane.

### Version

Dev mode (release branch)

**Comment by Rishabh-Rathod** [comment]
### Initial RCA

This seems to be an issue with the CheckBox Group widget. 

In `componentDidUpdate` when options change we re-calculate the `selectedValues` and call `updateWidgetMetaProperty` to update the `selectedValues` 

In case, when previous and newly calculated `selectedValues` are equal we should not call `updateWidgetMetaProperty` 

Below code fixes this issue.

```
if (!isEqual(selectedValues, this.props.selectedValues)) {
        this.props.updateWidgetMetaProperty("selectedValues", selectedValues, {
          triggerPropertyName: "onSelectionChange",
          dynamicString: this.props.onSelectionChange,
          event: {
            type: EventType.ON_CHECK_CHANGE,
          },
        });
      }
```
