### ISSUE TITLE
[Feature]: search, group and categorize errors in debugger

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#14926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Instead of showing a list of errors in debugger.
We could have the option to group and categorize them.

---

### Why should this be worked on?

If the user has a long list of pending errors. (9+)
- It's discouraging to skim through the list of errors. (if they decide to clean up their app)
- It's not very easy to find errors related to a specific entity.

---

### Entity types (as dropdown):
1. All (selected by default)
2. API/Queries
3. Canvas/Widgets
4. JsObjects

---

### Group by entity
Say a check box that enables/disables grouping.
Errors from same widget/Api/JsObject are grouped into one accordion.

---

### Search (to filter errors) - perhaps just a search would suffice?

**Comment by rohan-arthur** [comment]
not planned - we will relook at the debugger in the near future as part of the IDE pod roadmap
