### ISSUE TITLE
[Bug]: Duplicate names for sections in property pane of RTE widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#14922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a RTE widget there are two sections in the Property pane named `Styles`. Ideally one of them (which deals with label styling) should be named as `Label Styles.`
<img width="305" alt="Screenshot 2022-06-30 at 3 44 58 PM" src="https://user-images.githubusercontent.com/39921438/176654839-2e6f5fb7-5896-495f-abca-9d903550d972.png">

### Steps To Reproduce

1. D&D a RTE widget.
2. Go to the property pane.

### Version

Cloud

**Comment by dilippitchika** [comment]
@keyurparalkar please add your RTE pr to this once you fix this issue

**Comment by shadabbuchh** [comment]
This issue has been fixed. Now we see `Label Styles` & `Styles` as two different sections in the property pane.
![Screenshot 2022-07-01 at 3.43.06 PM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/bbe5ed77-f5d0-4a55-a171-8d473497afba)
Moving it to `Done`.
