### ISSUE TITLE
[Bug]: Keycloak credentials are missing from docker.env after upgrading to EE

### ISSUE THREAD

**Issue by vishnu-gp** [appsmithorg/appsmith#14931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the Appsmith docker version is upgraded from Community Edition to Enterprise Edition the Keycloak user credentials are missing from docker.env post upgrade.

### Steps To Reproduce

1. Start CE container using docker-compose.yml
2. Update docker-compose.yml to use EE image with License Key
3. Restart the container. Keycloak credentials will be missing in the docker.env after this.

### Version

1.7.5

**Comment by OladapoAjala** [comment]
@Nikhil-Nandagopal @pratapaprasanna I guess to fix this one must have a an EE license key?

**Comment by Nikhil-Nandagopal** [comment]
@OladapoAjala not necessarily but we're already working on this. You can expect a fix soon!

**Comment by OladapoAjala** [comment]
@Nikhil-Nandagopal great, I was just looking for a docker related issue to contribute to. I'd be glad if you can point me to one.
