### ISSUE TITLE
[Docs]: Add async / await snippet to storeValue docs

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#14935]
`storeValue` is an asynchronous action, and it is sometimes necessary to `await` the function call when attempting to store data and then access it again. However, our docs page [here](https://docs.appsmith.com/reference/readme-1/actions/store-value) does not make clear mention of this. The function signature does indicate that `storeValue` returns a Promise, but otherwise we don't mention that it's async and there are no code snippets where the function is `await`ed or involved in a promise chain.

Users are frequently confused by this when they attempt to access stored values before the action has completed. We should add a snippet/scenario in the docs that explains when it is necessary to `await` the function call.

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/reference/appsmith-framework/widget-actions/store-value). @ohansFavour - Please review and close the ticket.
