### ISSUE TITLE
[Bug] Glitches related to isVisible property

### ISSUE THREAD

**Issue by AndreaPravato** [appsmithorg/appsmith#1493]
## Description
Despite declaring the intention to hide an item, the time shows up for a moment upon page change; only then it disappears.
Expected behavior would be to not see the item at all.

### Steps to reproduce the behaviour:
1. set {{Table1.isVisible}} to false, either with toggle or through js (ex.: {{appsmith.mode === "EDIT"}}). Ex. tested on Appsmith Tutorial app.
2. publish the application
3. change from page 1 to 2, back and forth; switching to page 1 you will see Table1 for a moment, then it will disappear.

**Comment by Nikhil-Nandagopal** [comment]
@AndreaPravato thank you for reporting this! This is happening because we recently moved to a more asynchronous method of evaluating javascript to improve our performance. We'll get this fixed soon 😃

**Comment by hetunandu** [comment]
Hey @AndreaPravato when you switch, do you see the Table1 in a loading state or a properly rendered table with/without data in it?

**Comment by hetunandu** [comment]
Closing this now since it seems to be working as expected. @AndreaPravato Please feel free to reopen this again if you find see this again

**Comment by AndreaPravato** [comment]
Hi, thanks for working on this. From my point of view the issue is still open. 
I have the impression behavior improved for tables in containers only, but other things are still showing up.
![elementsShowingUp](https://user-images.githubusercontent.com/4329975/99871959-863fe300-2bde-11eb-8ff5-959cfea7ca1f.gif)
Previously existing project; switching to page 2 some containers still show up and then disappear; there is a table in a container there also, and that is not displayed apparently now (or it is too fast to see). 
Anyway, the table data is loaded and accessible to the user. I can anticipate the need to check for this behavior as a developer, as I can imagine the feature could be implemented with css visibility property, but to be safe and for usability it would be a good improvement to warn the user (that is setting an element not to be visible) about the fact that related data is going to be loaded anyway. 
![1](https://user-images.githubusercontent.com/4329975/99872066-5e04b400-2bdf-11eb-943b-849762653d94.png)
Table not displayed, but data loaded

![tableAppears](https://user-images.githubusercontent.com/4329975/99871963-893ad380-2bde-11eb-967f-bddeb075ec4a.gif)
New project, table appears and disappears when I switch to page1

**Comment by Nikhil-Nandagopal** [comment]
@AndreaPravato thank you for adding such detailed screenshots. I think we have more clarity on what to solve now
@hetunandu I believe this is happening due to the async nature of our evaluation. Can we not render the canvas till the first evaluation is complete?

**Comment by Nikhil-Nandagopal** [comment]
This has now been fixed as evaluations happen before the first render

**Comment by AndreaPravato** [comment]
> This has now been fixed as evaluations happen before the first render

@Nikhil-Nandagopal Great! Is #1834 related and can it be closed as well? Thanks!

**Comment by Nikhil-Nandagopal** [comment]
@AndreaPravato thanks I missed that one! This is fixed as well :)
