### ISSUE TITLE
[Bug]-[385]:Actions on RTE is repeated

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#14949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="761" alt="Screenshot 2022-07-01 at 2 28 58 PM" src="https://user-images.githubusercontent.com/83569920/176862557-2e3623c7-4978-4bb4-97ba-ea2f6419ac96.png">

### Steps To Reproduce

1. Drag and drop a RTE widget
2. Click on 3 dots in toolbar
3. Check the actions are repeated

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 385 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Remove the other color and highlight color

**Comment by victor-echo-delta** [comment]
This issue seems to be resolved, is there anything more that needs to be done here?
<img width="483" alt="image" src="https://user-images.githubusercontent.com/34849403/229368866-8b015669-4ac7-42fe-8eb8-1fed156cc29b.png">

**Comment by nikhil-babar** [comment]
@dilippitchika I would like to work on this issue, plz can you assign me this issue

**Comment by dilippitchika** [comment]
Closing this, as the issue is now resolved
