### ISSUE TITLE
[Bug] Button onClick-Js executed multiple times on page load, with no click

### ISSUE THREAD

**Issue by AndreaPravato** [appsmithorg/appsmith#1494]
## Description

Loading a page triggers multiple times the execution of javscript set in onClick button action

### Steps to reproduce the behaviour:
1. Edit "AppSmith tutorial" app (or any); add a Button
2. In the onClick action of that new button, add some javascript instructions
3. Publish the application, visit the page, you will see that the javascript instructions have been executed multiple times (ex.: 7 times in my test case), despite the button not having been clicked yet.

![button1](https://user-images.githubusercontent.com/4329975/97777807-eb219380-1b72-11eb-88a0-5bf0a83879f9.png)
![button2](https://user-images.githubusercontent.com/4329975/97777809-ebba2a00-1b72-11eb-98db-fc63d75cb007.png)

**Comment by Nikhil-Nandagopal** [comment]
@AndreaPravato this was a great catch! Fortunately, this does not affect actions such as APIs / navigation but I agree the evaluation should not take place in these cases as well.

**Comment by mohanarpit** [comment]
This issue is no longer reproducible in production. It has been fixed as part of our performance upgrades.
