### ISSUE TITLE
[Bug]-[36]:In a table widget, JS toggle retains the CENTER text on vertical alignment property of column

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On clearing JS toggle of vertical alignment property of a column in a table widget, and clicking anywhere outside the text area, the CENTER text comes back up again.

### Steps To Reproduce

Drag and drop a table widget
Click on any column from property pane (say Task column)
Click on JS toggle for vertical alignment property
Observe that by default CENTER populates. 
Delete the CENTER text and click outside of the text area. 

The text CENTER gets auto-populated again.

### Version

Release

**Comment by dilippitchika** [comment]
This is now showing left to me automatically, we need to understand why we are adding a default value here, when the value doesn't evaluate we should simply show an error and default to center, rather than adding a value automatically.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 18 |
| Effort (months)  | 0.25 |

**Comment by sbalaji1192** [comment]
@dilippitchika Each property has a defaultValue associated with it in the property configuration, in the event of no value it gets evaluated to the defaultValue. 
But here `verticalAlignment` has wrong `defaultValue`. it should have been `CENTER`.
