### ISSUE TITLE
[Bug]: JS Toggle on Date picker's First Day of Week is not consistent with other fields JS toggle

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#14954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I enable JS using JS toggle on First day of Week field (which has default 0 in it) of Date Picker widget, immediately it gets disabled and user has to clear field to enable it again. 

### Steps To Reproduce

Drag and drop a Date picker widget
In the Property Pane, browse down to the First Day Of Week field. 
Click on the JS toggle to enable it

See that it immediately gets disabled and asks user to clear field to enable it again

Expected behavior - it should be consistent with the other fields. Should not get disabled as soon as it is clicked on.

### Version

Release

**Comment by btsgh** [comment]
cc: @aswathkk

**Comment by aswathkk** [comment]
@dilippitchika Do we need JS toggle option for *First Day of Week* property?
Since it is an input field already and it supports JS code by default, why do we need to convert it into a JS field?

**Comment by dilippitchika** [comment]
No we don't need it. Looks like it was added by accident. We can remove it safely.

**Comment by Sripriya93** [comment]
JS toggle option is removed in the Date picker, First day of the week property, Marking as verified

![image](https://user-images.githubusercontent.com/104895602/191903642-416ba9d1-7a5e-4f45-bf0e-6d93b4828605.png)
