### ISSUE TITLE
[Enhancement]: Toast Message system errors on canvas leads to bad UX

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#14952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Problem

Toast message for system errors like onPageLoad API failures being shown on canvas, blocks the canvas for few seconds and makes it non-intractable.   
 
![image (1)](https://user-images.githubusercontent.com/23132741/176868575-dbcdbb69-4cba-4477-ad53-a4dd1c74f8de.png)

Internal discussion [link](https://theappsmith.slack.com/archives/CRVRBGU1K/p1653634506004899)

#### Sub Task
- We need to find a good solution for the position of the error messages in edit and view mode.
- We also need to theme the error messages so that it doesn't look out of place in view mode.

**Comment by kocharrahul7** [comment]
Toast messages no longer look like this
