### ISSUE TITLE
[Bug]: Remove 300 ms delay from fetchDynamicValues flow

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#14965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are waiting for 300ms when fetching dynamic values after we get the notification that evaluations are complete to allow for the data tree to be updated. We can work to remove this delay by
1. Hooking up the trigger to a different action that notifies when the new tree is ready
2. Create a non-blocking wait/delay.

### Steps To Reproduce

This is part of a code optimisation, the new effects can be seen in dynamic value fetching.

### Version

Cloud

**Comment by prapullac** [comment]
Verified it based on regression
