### ISSUE TITLE
[Bug]: onPageLoad fails after fork

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#14978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After forking the app onpageload stops working

https://www.loom.com/share/d9b963a52a0d479086aa13aab23c9ffd

### Steps To Reproduce

1. Fork habitasaurus.
2. Get tasks onPageload stops working.

### Public Sample App

https://release-ee-https.appsmith.com/app/habitasaurus-1-1/task-62c2b9da2565875a778e43e8

### Version

selfhosted

**Comment by bharath31** [comment]
no longer reproducible
