### ISSUE TITLE
[Bug]: JS toggle's disabled state is not represented properly in UI

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#14973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The disabled state of the JS toggle button doesn't look like it is disabled.

https://user-images.githubusercontent.com/10436935/177104422-2f8eba25-2fc8-4929-b0d0-0aad195c7071.mov

### Steps To Reproduce

Add any widget. Add any binding to any property and look at the JS toggle. It is disabled actually but the UI doesn't look like it is disabled.

### Version

release

**Comment by btsgh** [comment]
Tested JS toggle across widgets/properties. Functions fine now.
