### ISSUE TITLE
[Bug]: Run button on queries does not exit hover/selected state once the query has been run and cursor is moved away from the button

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Run button on queries does not exit hover/selected state once the query has been run and cursor is moved away from the button

### Steps To Reproduce

1. On any query, hit the run button and observe the hover/selected state does not change back to normal state after running the query
2. Toggling between bowser windows causes the button to revert to normal state but once back on the application window then the button goes back to being in selected state

https://www.loom.com/share/0072bbb8f92041979ff4de6bae12cd3d

### Version

Cloud

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
