### ISSUE TITLE
[Bug]: Older datasource not used for long time (6 months or so) needs Authorisation while we run the query 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#14985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to an older application that is stale for 6 months or so it is observed that the data source needs to be re-authorized
The user has not displayed an error in red with Asterics asking with Authorisation 

### Steps To Reproduce

1) open an old application
2) open an Datasource Query 
3) run the Query 
and observe it error is displayed 
4) navigate to respective Datasource 
and observe it does not ask for Auth 

Example : Gsheet 

### Public Sample App

release

### Version

cloud

**Comment by nidhi-nair** [comment]
This is expected in case refresh tokens expire as well. An app that has long been unused should not continue to work without authorization, that sounds like good security practice.
