### ISSUE TITLE
[Bug]: Not able to upload an image to Google Cloud using Binary Data 

### ISSUE THREAD

**Issue by utkarshDunzo** [appsmithorg/appsmith#14986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to upload a file to Google Cloud using FilePicker widget, but I am not able to send the file in binary data format. I have recorded a video of the issue, please go through it:
 [Video Link](https://www.loom.com/share/affa4c024a294415bd89ee7513874e41)

### Steps To Reproduce

Refer the video.

### Version

Self Hosted 1.7.5

**Comment by Nikhil-Nandagopal** [comment]
@utkarshDunzo thanks for reporting this. We'll have a look and get back to you on this

**Comment by utkarshDunzo** [comment]
@Nikhil-Nandagopal by when can we expect a response, actually this is a major blockage for our appsmith usage.

**Comment by dilippitchika** [comment]
@utkarshDunzo what is the binding appsmith.store.file_data pointing to?

**Comment by nidhi-nair** [comment]
Hey @utkarshDunzo ! Thanks for reporting this issue. Could you please share whether your setting for `Smart JSON Substitution` is turned on in the Settings pane of the REST API? If it is, could you please try running the API with the setting turned off?

**Comment by utkarshDunzo** [comment]
Hey @nidhi-nair, turning off the smart substitution resolved the issue. Thanks for your help.
