### ISSUE TITLE
[Bug]: Gsheet Field can not be converted into JS before selecting data from the dropdown

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#14998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The field can not be converted into JS without selecting data from the dropdown 

### Steps To Reproduce

1) Add an API from the Datasource
2) now navigate to Spreedsheet
3) Click on JS 
and observe that user is unable to convert to JS until the data is selected from dropdown

Video:
https://www.loom.com/share/2d705381e0c94cbbb1b608d5c5b1badc

### Public Sample App

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
@prapullac this is not reproducible anymore: 

https://user-images.githubusercontent.com/94514895/194902766-d43ab6ad-64a9-4d17-a8da-26bccc3382a6.mov
