### ISSUE TITLE
[Bug]: Canvas empty Space does not go away even after modifying the bottom most row

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#14991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In few applications, The canvas has extra empty space at the bottom of the canvas, even though there are now widgets present in that area.
Resizing, Dragging or even deleting a widget should recalculate the canvas length and adjust it accordingly. But even these operations does not change the bottom most row of the canvas, resulting in extra space at the bottom of canvas

### Steps To Reproduce

1. This is only reproducible in few applications, on only few pages
2. Export appsmith stand-up app
3. Import the app
4. Navigate to Standup Form, and Scroll down
5. Observe that the empty space at the bottom of the canvas
6. try a widget operation like resizing a widget, dragging a widget or deleting a widget.
7. Observe that these operations does not trigger any change in Main canvas height and the empty canvas space still exists
8. Expected behaviour, When a widget is resized, dragged or deleted on the Main canvas, The main canvas should recalculate its height and get rid of empty space.

### Public Sample App

https://app.appsmith.com/app/appsmith-standup/standup-form-5fb67116322ddc249377f5eb?branch=master

### Version

Cloud

**Comment by Sripriya93** [comment]
Verified with Standup app, older applications, dragged, deleted and resized widgets and are able to see the space go away.
