### ISSUE TITLE
[Bug]: Default selected value of border radius or box shadow is not visible in Table column property

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#14999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The default selected value of border-radius or box-shadow for Table widget's column property is not visible.
It should be shown which item is selected out of the available options.

<img width="826" alt="Screenshot 2022-07-05 at 10 40 42 AM" src="https://user-images.githubusercontent.com/10436935/177254177-20606fb4-8f1a-4299-9db5-533384f61aa4.png">
 

### Steps To Reproduce

1. Add Table widget
2. Goto action column's property and take a look at border-radius & box-shadow

### Version

1.7.6

**Comment by Sripriya93** [comment]
Verified in older applications. For Table Widget V2, creating a separate issue.
![image](https://user-images.githubusercontent.com/104895602/179220973-fcc95966-8a4b-40cb-995d-a1e7f504074f.png)
