### ISSUE TITLE
[Bug]: Design System PR label check failing

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#14995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Design System PRs label check workflow is failing since the name of the label is incorrect.
Current label in the workflow: Design System POD
Actual label:  Design System Pod

### Steps To Reproduce

1. Create any PR and add label Design System Pod.
2. Label checker workflow will fail on that PR.

### Version

Cloud

**Comment by yatinappsmith** [comment]
verification not required
