### ISSUE TITLE
[Bug] Page name is not displayed to user as it overlaps with application name 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1499]
Open the application and observe the name of the application is overlapped with the page name and page name is not displayed to user 
![Screen Shot 2020-11-02 at 10 03 15 AM](https://user-images.githubusercontent.com/71753653/97830452-05827b00-1cf3-11eb-96cf-dc68831a36ce.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac we're removing page name from the top
