### ISSUE TITLE
[Bug]: log file overwritten in shared deployments

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#15004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We deploy appsmith on kubernetes and share the same efs across multiple pods.

Problem:
When the logs are written to` /appsmith-stacks` and we have multiple pods writing to the same directory.
logs of appsmith process are getting over-written. In a nut-shell it is more like a race-condition where the last process to generate logs get over-written on the efs drive. 

This causes in-consistency when we debug issues in any setup.

### Steps To Reproduce

go to release cluster verify any service logs, They only contain partial confirmation
eg: 
logs in log-dna are in-consistent with logs in efs volume.

### Public Sample App

release.app.appsmith.com

### Version

eks-instance/cloud

**Comment by yatinappsmith** [comment]
Cannot be verified
