### ISSUE TITLE
[Bug]: Filepicker not retaining the data when i move to a query page

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i upload a file to filepicker and bind a data to query, i am unable to see the uploaded file values

### Steps To Reproduce

1. Add a new filepicker widget
2. Upload a file
3. Change page to a query page
4. Reference filepicker.files[0]
5. Observe that the reference shows undefined

### Version

Production

**Comment by pranavkanade** [comment]
https://www.loom.com/share/747fa873e3b44969aaf2e5e5af804f4f

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika @keyurparalkar can we please get this issue prioritised?

**Comment by dilippitchika** [comment]
Triaging this, also related to https://github.com/appsmithorg/appsmith/issues/11660
