### ISSUE TITLE
[Bug]: Dropdown used for property pane connections causes expensive style recalculations

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#15018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there is a evaluation cycle, dropdown used in property pane connections triggers an expensive style recalculation, costing about 40-80ms per cycle. 

Since it's dimensions don't change, there is no need for calling this property which triggers these calculations.
<img width="1667" alt="Screenshot 2022-07-05 at 12 26 56 PM" src="https://user-images.githubusercontent.com/441914/177303043-b34b228d-8a6c-430d-b1c7-7f1e71c61e7b.png">

Note: The above profile is with 4x throttling.

### Steps To Reproduce

Create a simple app with couple of widgets with one of them having some incoming and outgoing connections.

### Version

Both

**Comment by yatinappsmith** [comment]
Will be covered as part of regression
