### ISSUE TITLE
[Bug]: Array of files not working with multipart/form-data in execute action

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#15025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you try to upload `multiple` files in a single key using `multipart/form-data`, then the upload doesn't work.
Here are the screenshots that represent the application
![Screenshot 2022-07-05 at 5 24 42 PM](https://user-images.githubusercontent.com/7565635/177321679-b51e3bc2-a8ea-41bf-87df-557d08896a54.png)

![Screenshot 2022-07-05 at 5 21 19 PM](https://user-images.githubusercontent.com/7565635/177321534-92f67403-5eee-4104-9d35-678e7be11a0e.png)
.

### Steps To Reproduce

1. Create an application that has file picker with support of multiple files and increase the size limit
2. Add an API that sends the files `{{Filepicker1.files}}` as array.
3. Observe that the files uploaded result in 53 bytes size only

### Version

Both

**Comment by shantanu1singh** [comment]
Hi @AmanAgarwal041 @nidhi-nair , I'm unable to upload 2 or more excel files using the same key `files` in an API request accepting multipart form data. I get the following error:

<img width="702" alt="image" src="https://github.com/appsmithorg/appsmith/assets/2570312/2767beb5-0304-49bf-bf14-38c89d1d06e2">

The files were added to the appsmith filepicker widget and I'm using it as follows:
<img width="892" alt="image" src="https://github.com/appsmithorg/appsmith/assets/2570312/719fa80e-7d7a-465b-97f0-69206295bf1d">


Was this bug related to the same? If so, what's the recommended way of handling such scenarios of uploading multiple files through a REST API using multipart form data payloads.
