### ISSUE TITLE
[Enhancement]: UQI query screen JS Toggle behavior should be consistent with the canvas area property pane

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Query pane of the Google Sheets UQI datasource, wherever the JS Toggle is present, the behavior should be consistent with the current JS toggle behavior on canvas property pane.

### Steps To Reproduce

The JS Toggle functionality has been modified on canvas recently as per this feature request - 
[Feature]-[9884]:Disable JS button if the field is not empty or if the default text is modified#10833

This feature should be consistent across the application. Google Sheets screens where-ever JS toggle appears, the same behavior should be seen.

Reference screen - 
<img width="1150" alt="GSheets_JSToggle" src="https://user-images.githubusercontent.com/101863839/177365325-c300dc0c-266c-452c-b903-3604b194a3a9.png">

### Version

Release

**Comment by rohan-arthur** [comment]
link to conversation: https://theappsmith.slack.com/archives/CNQ9Q91C0/p1664795369902699
