### ISSUE TITLE
[Enhancement]: Google Sheets - Fetch Many, on choosing Sheet Rows, Columns section could have a Clear All option

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On choosing Fetch Many -> Sheet Rows, from a particular sheet, the user can choose specific columns that he wants to fetch. Here, for clearing the column selection all at once, a Clear All option will be a good to have. 

### Steps To Reproduce

1. Create a google sheets data source, and create a Query to that data source.
2. Choose Operation as Fetch Many , Entity as Sheet Rows, choose a spreadsheet and the sheet within it. 
3. Choose a few columns from that sheet, from Columns dropdown, and click RUN. Data from those specific columns will appear. 
Now, if we want data from all columns, we need to remove the columns one by one from the columns dropdown. If there was a Clear All option, would be easier for the user to remove the columns in one shot.

<img width="595" alt="GSheets_ClearAll" src="https://user-images.githubusercontent.com/101863839/177367662-bc24f1fb-181b-4dc1-828e-d5321aa1d40e.png">
 

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
@btsgh this seems like an enhancement rather than a bug

**Comment by AnnaHariprasad5123** [comment]
Hi @btsgh I am willing to work on this issue. But I am facing 500 server when I tried to connect google sheets in local.
![image](https://github.com/appsmithorg/appsmith/assets/124746204/4df44185-e286-418f-979e-7f4d627f47d7)

**Comment by AnnaHariprasad5123** [comment]
@btsgh I started working on this enhancement.

**Comment by daaliachhak17** [comment]
as per comment closing ticket-https://zemoso.atlassian.net/browse/TNOSB-172
