### ISSUE TITLE
[Bug]: getIdToken returns null

### ISSUE THREAD

**Issue by fungiboletus** [appsmithorg/appsmith#15040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`getIdToken` returns null.

See https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/java/com/appsmith/server/domains/User.java#L136-L139

### Steps To Reproduce

1. Install AppSmith and configure it with Google Authentication
2. Try to load `{{appsmith.user.idToken}}`
3: It's empty

### Version

latest on github

**Comment by Nikhil-Nandagopal** [comment]
@fungiboletus it seems to be working for me. Could you share a video with this issue?

**Comment by fungiboletus** [comment]
I could if necessary, but are you sure you tested on the version from this repository?

**Comment by Nikhil-Nandagopal** [comment]
I tested it on our cloud and release environments which are the latest code deployments from the main appsmith repo. Are you able to reproduce this on https://app.appsmith.com?

**Comment by trishaanand** [comment]
Not reproducible. Closing this.
