### ISSUE TITLE
[Feature]: Prevent secrets and keys to be pushed into github

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#15042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Recently, we pushed a secret token and key from AWS to our GitHub repository which in turn raised an alarm with AWS and caused a quarantine of the key. We should add a pre-commit hook to check if someone is trying to push a secret or key accidentally and stop them.

### Why should this be worked on?

To prevent accidental push of org-wide secrets and keys to public domain via our github repo.

**Comment by yatinappsmith** [comment]
No testing required
