### ISSUE TITLE
[Bug]-[5196]:JSObject Async function response data is not set when the function is executed using widget event like button onClick

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#15056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you bind the data from a JSObject to a widget using `{{JSObjectName.FuncName.data}}` and then execute the function on click of button, it doesn't update or display the data on the widget. The evaluated value in widget  and console logs show that the function was executed but the widget does not display any data.

Discord users query - https://discord.com/channels/725602949748752515/760761686549463060/994148281355612240

> For a JSObject function where `run on page load is turned off`

### Steps To Reproduce

1. bind the data from a JSObject to a widget using {{JSObjectName.FuncName.data}}
2. execute the function on click of button
3. check the data not being reflected in the widget 

### Version

1.7.6

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5g4p8)

## Possible solution
`myFunc : (function(){ const result = (functionCode)();$$setResponseData("JSObject.myFunc", result) })`

here, `$$setResponseData` is an internal method to set value in dataTree and is used above to set the response of JSObject function run to the response data path.

**Comment by rohan-arthur** [comment]
WIDGET_PROPERTY_UPDATE, updatedValue contains `.data` 6 months: 6000

Consider that 80% of this is for direct query binding, that leaves: 1200

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1200 |
| Effort (months)  | 1 |

**Comment by pranavkanade** [comment]
Another user reported this today.

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale @bharath31 this issue seems to be happening quite frequently

**Comment by Rishabh-Rathod** [comment]
One more user faced this issue on A-force. 
Internal slack link - https://theappsmith.slack.com/archives/C0341RERY4R/p1661808786706499

**Comment by bharat-patodi** [comment]
Wrong Bharat @Rishabh-Rathod 😀

**Comment by Rishabh-Rathod** [comment]
> Wrong Bharat @Rishabh-Rathod 😀

Sorry, my bad. 🙈

**Comment by amexcompliance** [comment]
This bug IMO needs to be a high priority. It cripples the ability to update the widget when the underlying parameters of the API/Query is modified through user interaction. As a workaround, I have utilized (per appsmith's recommendation too) localStorage , that is storeValue(key, result) then bind the widget appsmith.store.key. It works, until it does not as this solution does not scale. Today I blew out my local storage size limit and need to re-think how I am going to keep adding dynamic widgets. By dynamic I mean a widget that needs to be updated as user interacts with the UI. Otherwise widgets populated only once works with  JSObjectName.FuncName.data

**Comment by bharath31** [comment]
@amexcompliance thanks for flagging this! we're discussing potential solutions to address this issue. I'll have more updates for you by Thursday.

**Comment by ame-appsmith** [comment]
Another user reported this issue on our [forum](https://community.appsmith.com/t/data-propery-of-a-js-object-function-is-not-updated-after-execution/1449).

**Comment by bharath31** [comment]
Update: We've picked this issue up in the current sprint. We should have a fix out soon.

**Comment by beckerrobin** [comment]
@bharath31 Can you confirm that this is still being worked on?

**Comment by bharath31** [comment]
Update: It turns out this is a slightly complicated bug to fix. We have a couple of ideas on the table but we need more time to come up with the right solution. We'll have more updates on this next week.

**Comment by beckerrobin** [comment]
> Update: It turns out this is a slightly complicated bug to fix. We have a couple of ideas on the table but we need more time to come up with the right solution. We'll have more updates on this next week.

I fully understand. It's nice to hear that it's still being worked on. Keep up the good work!

**Comment by samg666** [comment]
met the same issue, hope to have a fix soon.

**Comment by felix-appsmith** [comment]
Hello, a user asks how the solution for this ticket is going. Could you tell me something to communicate it, please?

**Comment by ohansFavour** [comment]
@felix-appsmith this will be available in release in 2 weeks.
