### ISSUE TITLE
[Bug]MAPS:  unable navigate to  marked location after deployment when my initial location and default marker are two different location

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1506]
Steps to reproduce:
1) Add a Map widget
2) Click on Property pane of the widget
3) Set the Initial location 
4) Set the Default marker 
5) Now deploy
6)Try to move the map  
and observe 

Observation:
It is observed that the user is unable to navigate to location other then the Initial location. Trying to reduce/ increase the size of the map user is only navigated in and around  initial location

**Comment by ofpiyush** [comment]
Steps to repro the bug on current release
1. Create map widget
1. Set default location from property pane
1. click JS to see js object, click back to see empty field (covered in another issue)
1. refresh editor page OR deploy application
