### ISSUE TITLE
[Bug]-[663]:Button group does not have an active state that's similar to button widget's clicked state

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a button widget is clicked, we see a loading sign, but for a button group, we don't show this. This inconsistent UX can cause users to trigger field action multiple times since action trigger state is unclear. This becomes more problematic when the code executed takes a while and causes unnecessary termination of code.

![image](https://user-images.githubusercontent.com/79509062/177707995-6b85f63d-861a-429f-965c-81943716cc0b.png)

### Steps To Reproduce

1. Create an action trigger for buttons on a `button group widget` and trigger it - observe the IU does not change
2. Create an action trigger for a `button widget`and trigger it - observe the UI changes to a loading icon

### Version

Cloud

**Comment by andrewdietekoki** [comment]
@dilippitchika Iterated a solution here:
https://www.figma.com/file/zHCSC8aA9crvqXrxCjcTwD/Issues-and-Fixes?node-id=1%3A11515

**Comment by dilippitchika** [comment]
Design is perfect, ready for implementation.
