### ISSUE TITLE
[Bug]: JS Toggle on Progress widget's "Progress" and "Number of Steps" fields is not consistent with JS toggle on other fields

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I enable JS using JS toggle on Progress or Number of Steps field of Progress widget, immediately it gets disabled and user has to clear field to enable it again.

### Steps To Reproduce

Drag and drop a Progress widget
In the Property Pane, in the Progress and the Number of Steps fields, click on the JS toggle to enable it

See that it immediately gets disabled and asks user to clear field to enable it again

Expected behavior - it should be consistent with the other fields. Should not get disabled as soon as it is clicked on.

### Version

Release

**Comment by aswathkk** [comment]
These fields already accept JS. So, no need to have a JS toggle option for them. Removing the JS toggle button for these properties is the solution.

**Comment by Sripriya93** [comment]
JS toggle is removed in Progress and No of steps, Marking as verified
![image](https://user-images.githubusercontent.com/104895602/191899813-4d562dcf-2b99-4d27-b203-56ef00ae0ecd.png)
