### ISSUE TITLE
Add page to copy SaaS related collections from Prod to Release for individual collections

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#15079]
Recently, we created a new page with the functionality to copy SaaS related collections from Prod to Release for Cypress Testing. ([#14587](https://app.zenhub.com/workspaces/be-coders-pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/14587)). Another feature we want to implement is the same functionality but for individual collections, for example plugin and actionTemplate.

We can base on the existing Admin Toolbox page and improve it with this new functionality.

**Comment by felixsuarez0727** [comment]
How to test:

Introduction: The objective with this feature is to copy all the data of an Integration from Prod to Release. This includes data on the following collections: `plugin`, `actionTemplate` and `datasourceTemplate`.

To test this, we can use an existing testing integration.

The process goes like this:

1. Open the SaaS App (Edit Mode)
2. Go to the API Manager page. Select a testing Integration.
3. Create a test Command.
4. Go to the Admin Page.
5. Use the `Get_Plugin` (Prod CS) to confirm that the `options` property has the new entry.
6. Use the `Get_Plugin_Release` (Release CS) to confirm that entry doesn't exist in `options`.
7. Navigate to Admin Page -> Utils. Click on "Copy to Release" and accept all the prompts.
8 Use the queries described on steps 5 and 6 to confirm that now both are in sync.

Example video: 
https://images.zenhubusercontent.com/275993885/70ff8b67-92d6-4a81-8e2c-8198ed3e8053/migrate_plugin.mp4

**Comment by yatinappsmith** [comment]
![image](https://user-images.githubusercontent.com/84702014/178913920-d30bd35e-5cc9-45a4-aaaa-72a51bc55bbb.png)

**Comment by yatinappsmith** [comment]
- [ ] [[Test case] : copy SaaS related collections from Prod to Release for individual collections ](https://github.com/appsmithorg/TestSmith/issues/1943)

**Comment by yatinappsmith** [comment]
verified on saas manager
