### ISSUE TITLE
[Bug]-[1160]:multiselect widget is not  showing appropriate options

### ISSUE THREAD

**Issue by nived-7** [appsmithorg/appsmith#15073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

multiselect widget is not  showing appropriate options after I manually open a query ,  options are reappearing only after I reload the page .

### Steps To Reproduce

1. create a multiselect widget with options
2. create a query 
3. try to expand the options of the multiselect widget after manually opening the query .

### Version

Appsmith v1.7.6

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika looks like we broke something here

**Comment by dilippitchika** [comment]
Hey @nived-7 can you please add a screenshot or a video recording, i am not able to understand what opening a query means?

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika this is to create a query using the slash commands

**Comment by nived-7** [comment]
Just selecting a query from Query/js options (under the widget select options)

Sent from Mail for Windows

**Comment by dilippitchika** [comment]
https://www.loom.com/share/cd6b4cd8bf6a46ad973d1f6016c7f2e3 

@Tooluloope can you triage this?

**Comment by dilippitchika** [comment]
Assuming 10% of slash command users are trying to bind options in multi select widget
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 290 |
| Effort (months)  | 0.5 |

**Comment by Tooluloope** [comment]
Fixed in #15058
