### ISSUE TITLE
[Bug]: Appsmith crashes when trying to create a new app

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Appsmith crashes on trying to create a new app from workspace - this happens on release and not prod.

### Steps To Reproduce

1. Go to any old organization and click on the new button and observe either `page not found` error or see the app crash

![image](https://user-images.githubusercontent.com/79509062/177787732-a5571971-6261-468b-b683-5bf151f88f66.png)
![image](https://user-images.githubusercontent.com/79509062/177787695-4e280f38-de1a-4e9f-b08e-12f732857abc.png)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami this seems to be working for me
