### ISSUE TITLE
[Bug]: Editing few applications just shows error screen

### ISSUE THREAD

**Issue by awanishraj** [appsmithorg/appsmith#15087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are unable to edit 2-3 of our apps on AppSmith. "Launch" is working fine. "Edit" results in the following error screen.

<img width="1512" alt="Screenshot 2022-07-08 at 1 59 11 PM" src="https://user-images.githubusercontent.com/6928709/177951895-1330936e-f012-4be7-90f1-7befc7e6944f.png">

I have tried logging in and out. Clearing browser history/incognito mode. But the edit page never opened for these 2-3 apps.

### Steps To Reproduce

We were unable to reproduce this error with a fresh app. The issues is affecting only 2-3 previous apps.

There are no error stack traces in the docker logs as well. In the front end logs, I could see these error messages:

<img width="603" alt="Screenshot 2022-07-08 at 1 59 34 PM" src="https://user-images.githubusercontent.com/6928709/177952169-bdfe61cd-a924-4d15-bcc1-9041af1f82f1.png">

### Version

Self Hosted - 1.7.6

**Comment by awanishraj** [comment]
Exporting/importing into a new organization worked. All the applications in the source organization have this problem. I believe the issue at the organization level and not at the application level

**Comment by awanishraj** [comment]
Creating a new application in this organization also has the same issue. The application gets created, but it directly goes to the error screen.

**Comment by danciaclara** [comment]
@awanishraj Sorry about the issue you are facing? Can you give some more information about when this started happening? Were you performing an action on the app for example -  Writing queries, creating JSObects, etc..

**Comment by awanishraj** [comment]
It started happening 2 days back. Don't remember any specific action that resulted in this. I came back to edit the application to add new features and that's when I noticed. Then on checking all other applications in organization, I encountered the same issue.

**Comment by danciaclara** [comment]
Ok. Thanks for clarifying. Our team is investigating this and we'll come back with an update as soon as possible.

**Comment by danciaclara** [comment]
cc: @AnaghHegde

**Comment by danciaclara** [comment]
@awanishraj Can you invite support@appsmith.com to your app so that we can investigate this? Thanks

**Comment by awanishraj** [comment]
Unfortunately, this org has confidential data and dashboards. Can we do this over a zoom call?

**Comment by awanishraj** [comment]
@danciaclara The issue got resolved in v 1.7.7
