### ISSUE TITLE
[Bug]: The datatype for the table is blob but also the table cant able to receive the image data 

### ISSUE THREAD

**Issue by HarishkumarNithiyananthem** [appsmithorg/appsmith#15082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the table there is a Column with datatype blob even though the column cant access the data respect to the blob. I used file picker for this which fetch the image data and I used to store the image data in the column with the datatype blob which is also used to store the image but I cant able to store the image in the column this was the issue I faced. 

### Steps To Reproduce

1. select table widget and provide some data to it with one column lets name as attachment set that attachment data type as medium blob
2. pick the file picker widget 
3. provide the file picker widget data to the Attachment column with {{filepicker.files[0]}}
4. search for the image that was uploaded in the attachment column with file picker it will show an invalid image

### Public Sample App

https://app.appsmith.com/user/login

### Version

cloud/self hosted - 6.6

**Comment by Nikhil-Nandagopal** [comment]
@HarishkumarNithiyananthem the table only accepts URLs to render as an image
