### ISSUE TITLE
[Bug]-[206]:Discarding git changes is stuck on UI and does not show any error on the application

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there's an error during git discard, the UI is stuck and does not respond to any mouse clicks. Checking browser console reveals the error being an error accessing repo file.

### Steps To Reproduce

1. Create a git-connected app whose git configuration has been changed so it reflects an error on the frontend
2. Make changes on the app and try to discard these changes and observe that the progress bar gets stuck after a point with no error notification.
3. Go to browser console and observe the error

https://www.loom.com/share/1e9f45fce5794f2aa7e8364c6b608906
![image](https://user-images.githubusercontent.com/79509062/178188090-1060e5cb-ec2c-4476-8f3b-393775bcf68c.png)

### Version

Cloud

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 103 |
| Effort (months)  | 1 |

**Comment by hiteshjoshi** [comment]
This is a result of not responding properly to the error reports from the server. @ankitsrivas14 to check this.

**Comment by infinitetrooper** [comment]
Stale
