### ISSUE TITLE
[Bug]: The Data is not displayed in Omni bar after clicking on learn more link from property pane

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Data is not displayed in the Omni bar after clicking on learn more link from the property pane
https://www.loom.com/share/49104398a9ed4a678791c2fef225fb6a
below screenshot is something i am seeing in prod 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/178198138-d988d830-5c7e-43bb-9d79-118b1b3aeec6.png">

### Steps To Reproduce

1. Goto the application 
2. add a new page
3. go to widget tab
4. drag and drop a tree select widget 
5. From property pane 
6. click on learn more link under connect data button
7. the omni bar pops up but the data is not displayed

### Public Sample App

https://release.app.appsmith.com/app/11th-july-regression/audio-widget-62cbab4a4eb23b5ac7c64844/edit?branch=raksha_widgets%2F1

### Version

release

**Comment by arunvjn** [comment]
Recent version bump on 'marked' package to fix dependabot alerts seem to have broken the documentation tab in omni-bar.
Can you guys take a look ? @arslanhaiderbuttar @akash-codemonk

**Comment by RakshaKShetty** [comment]
The Links are broken in Following Places :
1.Documentation link from Omni Bar
2.Documentation Link from Queries

**Comment by eco-monk** [comment]
`marked` has become `undefined`.
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/66776129/178652759-5c891842-1ec9-4e7c-a0b2-4826c35b004c.png">

Imports updated here recently.
https://github.com/appsmithorg/appsmith/pull/14970

**Comment by Richarex** [comment]
This is fixed now closing it.
