### ISSUE TITLE
[Feature]: Dynamic table menu button column items

### ISSUE THREAD

**Issue by kimploo** [appsmithorg/appsmith#15100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Table menu button column items (Table => Column => Menu button => Menu Items) should change dynamically by dynamic table data change.

### Why should this be worked on?

Let's say following data is received by api. If this feature applied, I can dynamically check homwork arrays elements in Appsmith table. This feature have many potential if user have to manage complicated JSON as below.

```typescript
// use UnitEntity[] as table data
interface UnitEntity {
  id: number;
  title: string;
  description: string;
  homework?: HomeworkInformation[] | null;
}
```

i.e.
1. click the menu button to see nested array elements
2. click the menu button to see nested array elements, and click menu button items to delete or do some actions related to menu button items

I attach loom video for better explanation. 
https://www.loom.com/share/031f47979fd749e5b26632ce170bae8f

**Comment by Nikhil-Nandagopal** [comment]
@kimploo thank you for the feature request! That is a great point

cc: @dilippitchika

**Comment by dilippitchika** [comment]
Hey @kimploo a few more questions to understand your request better. 
1. What is the data shown in a homework? Any sample data here will help. The reason i think this is useful is, it looks like homework is a child and should be seen in a different drill down like UI rather than directly in the table.
2. What will clicking on any homework inside a menu button do? Will it open something else where you see the homework?

**Comment by dilippitchika** [comment]
@kimploo also this is a duplicate issue of #12362, closing this issue in favor of that

**Comment by kimploo** [comment]
@dilippitchika 

> What is the data shown in a homework? Any sample data here will help. The reason i think this is useful is, it looks like homework is a child and should be seen in a different drill down like UI rather than directly in the table.

Please check my type definition - homework property has an array of homeworkInformations, which is an object with few string property.

```typescript
// use UnitEntity[] as table data
interface UnitEntity {
  id: number;
  title: string;
  description: string;
  homework?: HomeworkInformation[] | null;
}

interface HomeworkInformation {
  name: string;
  studentRepo: string;
  referenceRepo: string;
  devRepo?: string;
}
```

I originally does not have need this feature(dynamic table menu button column items). If Appsmith can show nested JSON format well in table, I'm find with that. However I failed to find the best way to show my nested array on table. That's why I tried to use menu button feature to show my nested array elements(`homeworkInformation[]`). when I try to do so, menu button cannot be added dynamically. These are overall reason that I request this feature.

I ended up making sth like this below, click menu button -> show modal -> see nested Item via JSON form UI.
![스크린샷 2022-07-13 오후 5 17 25](https://user-images.githubusercontent.com/12145019/178685473-96e7a210-be06-476e-8344-3c8be8660675.png)

> What will clicking on any homework inside a menu button do? Will it open something else where you see the homework?

I wanted to have CRUD homework feature. Read all homeworks in one table, and if I click one homework, there should be some options to create / update / delete homework

> this is a duplicate issue of https://github.com/appsmithorg/appsmith/issues/12362, closing this issue in favor of that

Good that other people also needed this feature!
