### ISSUE TITLE
[Bug]: In git sync modal Open repo and Discard changes buttons are misaligned 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#15113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1429" alt="Screenshot 2022-07-11 at 10 16 25 AM" src="https://user-images.githubusercontent.com/80334441/178207748-e7a133e7-878a-4876-bc28-13720a540cf5.png">

When an app has merge conflicts , in git sync modal the Discard changes and Open repo button are not aligned properly 

### Steps To Reproduce

1. Go to github repo and change something ex: query name from Query1 to Query2
2. Change the query name from app as well Query1 to Query3
3. Commit the changes and it will show message to pull the remote changes.
4. Pull the remote changes and observe

### Version

Release

**Comment by RakshaKShetty** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/180692560-3961edf1-d972-44ee-a864-8ba9d2977736.png">
