### ISSUE TITLE
[Bug]-[440]:Dropdown search behaviour is incorrect when search field does not match listed options

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a search text does not match dropdown options on a tree-select/multi-tree select widget then the options tray should not open up and display only matched options when there is a match. Behvaiour is expected to be in line with select/multi-select widget. 

### Steps To Reproduce

1. Drop a tree & mutli-tree select widgets onto the canvas.
 2. Use the filter property to search for values present in the options tray - all options are displayed with the matched option appearing in bold.
 3. Search for values not present in the options tray - all options are displayed even though there aren't any matches

https://www.loom.com/share/da799fb76265438db4f9651e080d6d88

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 440 |
| Effort (months)  | 0.5 |
