### ISSUE TITLE
[Bug]: typo on blog page

### ISSUE THREAD

**Issue by jibe-b** [appsmithorg/appsmith#15116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi there, love your work! Keep on clean coding!

There is a typo on blog page https://www.appsmith.com/blog/may-round-up-app-theming-new-copy-paste-experience-and-product-updates:

`APITemplte.io` occurs while there should be an `a` as in: [APITemplate.io](https://apitemplate.io/)

### Steps To Reproduce

.

### Version

Webpage

**Comment by Nikhil-Nandagopal** [comment]
@jibe-b Thank you for pointing this out!

@vihar could you please update this?

**Comment by jnikhila** [comment]
@vihar - Could you please look into this?

**Comment by vihar** [comment]
I've updated this issue, please view the changes at https://www.appsmith.com/blog/may-round-up-app-theming-new-copy-paste-experience-and-product-updates.

cc: @jnikhila

**Comment by spark-c** [comment]
By the way, there is now an instance of the misspelling: "APITempalte.io". The link correctly points to the site "apitemplate.io", but the text itself is off.

**Comment by jnikhila** [comment]
@vihar - Could you please look into this?
