### ISSUE TITLE
[Bug]: Advance setting change MongoDB does not work

### ISSUE THREAD

**Issue by caw-ishikajain** [appsmithorg/appsmith#15123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I create a MongoDB and added it to settings but it always says retying nothing happens.

I am using self deployed version on AWS ECS and when Task is restarted it wipes out all the data, which is very frustating with no backup we just lose data, I guess using EFS volume is also not good choice read it somewhere not sure.

I tried doing it using CLI as well, didn't worked.

Please suggest some better way.

![image](https://user-images.githubusercontent.com/55681862/178258652-426651c5-693f-4636-907e-c240ab203169.png)

Thanks

### Steps To Reproduce

1. Create MongoDB with all allow access IP
2. Add DB URL to Advance settings
3. Restart

### Version

Self/Hosted - 1.7.6

**Comment by pratapaprasanna** [comment]
@caw-ishikajain can you access the mongo-cluster from any off your mongo-clients? as-in not specifically on appsmith can you access the mongo-db from other sources ?

**Comment by caw-ishikajain** [comment]
Yes, I am able to access it in MongoDBCompass.

**Comment by sum35h** [comment]
@caw-ishikajain Have you configured the volume mapping mentioned in the [docs](https://docs.appsmith.com/setup/aws-ecs#step-2-create-task-and-container-definitions ) ?

**Comment by caw-ishikajain** [comment]
Yes, Appsmith is working with local DB.
I had to upgrade the image, I was facing one bug(#14210). So I created a new version for Task definition and updated the docker image version to 1.7.6 and updated the service then a new task is created and I lost previous data.

What I know is -
EC2 creates a container on each task run, and once a task is stopped we cannot start the same task or the same container.

Let me know if the above things are not correct.

Thanks

**Comment by sum35h** [comment]
@caw-ishikajain  You're correct, every task creates a new container and is stateless. So we use the volume binding (EBS/EFS)  for the appsmith/stacks directory ( where the data is persisted) to maintain persistence on the Appsmith container.

**Comment by caw-ishikajain** [comment]
ok, thanks
