### ISSUE TITLE
[Bug]: Search is not working properly on Appsmith Documentation page

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#15125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While searching on appsmith documentation page, the text gets reset and search is only taking 1 input and not more than that. 
Weird behavior on search can be seen in video

https://www.loom.com/share/a2e0392615ae494892d2f0ae2a44d7f7

### Steps To Reproduce

1. Open an app and click on '**?**' icon to open documentation
2. or visit https://docs.appsmith.com/
3. Click on search to search for queries
4. Observe that search behavior is weird on providing input

### Version

Cloud/Production

**Comment by akash-codemonk** [comment]
Looks like a documentation issue.

**Comment by jnikhila** [comment]
It is resolved by the GitBook Support team and should be working now.
