### ISSUE TITLE
[Bug]-[25]:Clear all selection property doesn't work in Tree select widget

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clear all selection property doesn't work in Tree select widget
https://www.loom.com/share/cef34c23cc0943f5b81f0f4a3e6a529d

### Steps To Reproduce

1. Go to canvas
2. drag and drop the Tree select widget
3. In the property pane
4. enable the clear all section property
5. now in tree select widget click on Close icon the selection is not reset the 

### Public Sample App

https://release.app.appsmith.com/app/11th-july-regression/treeselect-62cbab4a4eb23b5ac7c64844/edit?branch=raksha_widgets%2F1

### Version

release

**Comment by dilippitchika** [comment]
- Replace "Clear all selections" with "Allow Clearing Value"
- When switched on we show the clear option on the widget
- When switched off we don't show the clear option on the widget

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 25 |
| Effort (months)  | 0.5 |
