### ISSUE TITLE
[Bug]: Inconsistency b/w JSON form and simple form with regards invisible fields in formdata

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#15131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

values of the Invisible fields in a simple form are present in the (form)data. but in JSON form, invisible field values are not present in the formData.

### Steps To Reproduce

1. Drop a JSON form
2. create a field and its value is present in the Jsonform1.formdata
3. make this field invisible and its value is not present in the formdata anymore.
4. do the same thing with a simple form, the field is present regardless of the field visiibility.

### Version

cloud

**Comment by dilippitchika** [comment]
@sbalaji1192 closing in favor of #14231 do let me know if it needs to be reopened.

**Comment by muezz** [comment]
@dilippitchika Any idea when this will be fixed/implemented? I really need it and I am waiting for a solution. From the other issue, I can see that its been more than a month. If there is a temporary work around that you know about, do let me know.

**Comment by dilippitchika** [comment]
Hey there's a temporary workaround, you can just update the form data to append the hidden fields using a js object. So in that js object you can write code which takes the form data from the JSON form and the hidden fields in source data and combines both of them together.

**Comment by muezz** [comment]
@dilippitchika Thats actually quite clever. I'll work with that for now. Hopefully this gets resolved soon.
