### ISSUE TITLE
[Bug]: The save and restart button has a performance issue in Admin setting page 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The save and Restart button loads for some time when the user tries to restart the server
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/178452973-0c11eafb-5447-4c2a-b057-9e9739640143.png">

### Steps To Reproduce

1. Take a ee release pull
2. Run. the release docker image 
3. Now open the local 
4. Add a OIDC Auth details and click on save and restart
5. The loader is displayed in the button and then the Restart server message is displayed

### Version

local

**Comment by ankitakinger** [comment]
@RakshaKShetty this is not a bug. There are 2 APIs being called when we click on save & restart:
1. To save changes in docker.env which is why we see the loader on the save & restart button
2. To restart the server which is why we see the restarting banner
