### ISSUE TITLE
[Bug]: Tooltip to add query does not follow standard seen across the app

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Tooltip that pops up on hover of `+` next to `Queries/JS` is in all caps which does not follow the standard of other tooltips

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/178512971-66391dfe-1404-4b51-a390-9d73bbd3ff1f.png)
![image](https://user-images.githubusercontent.com/79509062/178513082-d8d1c682-86a1-46be-8aea-10cc00a6fc54.png)
![image](https://user-images.githubusercontent.com/79509062/178513192-9cf6c309-6fff-46f4-b591-e8c79ca1f612.png)

### Version

Cloud

**Comment by kocharrahul7** [comment]
No longer present
