### ISSUE TITLE
[Bug]-[6]:SSO SAML setup is giving server error issues.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On trying to setup SAML with the following metadata details:
 https://login.microsoftonline.com/3e889401-476e-489a-9d84-07f623ee08a4/federationmetadata/2007-06/federationmetadata.xml?appid=fe5c6870-f962-48a1-90b7-e4bb5f52ac97

It gives an error.

### Steps To Reproduce

1. Login to appsmith on localsetup, and go to the Admin settings page from the user icon
2. Click on Authentication link and select Edit from the SAML section
3. Enter the above details in the metadata url section

On Save and Restart, an internal server error pops up. here is the docker log-
[saml_docker_log.docx](https://github.com/appsmithorg/appsmith/files/9091376/saml_docker_log.docx)

Note: This same setup works on two other machines, but observed only on mine, even after multiple attempts

### Version

localhost

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3 |
| Effort (months)  | 1 |
