### ISSUE TITLE
[Bug]: Remove "copy" from copied JS object name

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#15143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user pointed out that on copying the JS object from the JS editor page, we are appending "copy" to the name, but on copying it from the explorer page, we don't do this.

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100140873#part_id=comment-164629100140873-15716667940

### Steps To Reproduce

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100140873#part_id=comment-164629100140873-15716667940

### Version

1.6.6

**Comment by Nikhil-Nandagopal** [comment]
@rimildeyjsr I believe this happens for all entities including APIs

**Comment by AnandiKulkarni** [comment]
@rimildeyjsr this PR is quite old and work was on hold, PR needs to be updated by latest
