### ISSUE TITLE
[Bug]: Optimize codeeditor data subscriptions

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#15157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CodeEditor subscribes to dynamic data but it is not used for display purposes. Dynamic data changes on every eval cycle causing all code editors on the screen to rerender.

DynamicData is used for the hinters and its updated on component mount and update, since this is only required on focus.

Remove the subscription to dynamic data at component level and get the data directly from store on focus or hover.

While you are here see if we can remove any further subscriptions to the redux store. `recentEntities` in particualr.

### Steps To Reproduce

- Create an app with single button
- Make all possible properties into JS
- Store `new Date()` on button click to trigger an eval cycle

1. Take a react profile of the button click, you will see all the codeditors render.
2. Take a chrome profile of button click, you will see purple color in the profile marking render of codeeditor.

**GOAL**: CodeEditor should not re-render

- Ensure that the UX is not changed in anyway due to doing this work on demand.
- Run the cypress tests ASAP after initial work to estimate the time required to fix failing cypress tests if any.

### Version

Both

**Comment by arunvjn** [comment]
Checked the hinters we use across our codebase, and none of them seem to have an update call associated with them. Will need to check on why it was written in the first place.

**Comment by ramsaptami** [comment]
Has been verified by dev
