### ISSUE TITLE
[Bug]: JS code with additional text does not evaluate

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#15162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I write `Returned: {{currentItem.date_returned === "" ? "No" : currentItem.date_returned}}` I expect the output to be `Returned: No`

But instead I get the output to be  ` `

![image](https://user-images.githubusercontent.com/55969597/178674850-869fb328-3663-47f2-84a6-8bab9deb92dd.png)
![image](https://user-images.githubusercontent.com/55969597/178674868-824268ec-593f-4f60-a3b2-55a2b3be1fb7.png)
![image](https://user-images.githubusercontent.com/55969597/178674880-38d7d19d-61b2-4fab-813b-95c2ac93742a.png)

### Steps To Reproduce

1. Create an appsmith app
2. In a text widget, in the text property mention `{{currentItem.date_returned === "" ? "No" : currentItem.date_returned}}` which checks if the there is no return date, it outputs `No `or if there is a return date, it outputs the date.
3. Now, in another text widget mention `Returned: {{currentItem.date_returned === "" ? "No" : currentItem.date_returned}}` which should work the same way as in step 2 with a `Returned:` appended at the start. But, it does not evaluate the query correctly and just outputs ` `  when there is no return date.

### Update to the issue

Having a newline Character, a backslash just before the JS code raises an error, e.g 
1. `Returned: \{{currentItem.date_returned === "" ? "No" : currentItem.date_returned}}`
2. ```
      Returned: 
      {{currentItem.date_returned === "" ? "No" : currentItem.date_returned}}
 ```

### Public Sample App

_No response_

### Version

Cloud 1.7.7

**Comment by Tooluloope** [comment]
This is a general issue and not isolated to only List Widget.

https://www.notion.so/appsmith/Handle-JS-Code-with-Text-on-a-Platform-Level-babd323a2bcd427c8167984a78f72c21
