### ISSUE TITLE
[Bug]-[20]:Wrong lint error (result is defined but never used)

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#15165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="610" alt="Screenshot 2022-07-13 at 09 11 23" src="https://user-images.githubusercontent.com/46670083/178684794-7acf9ce6-b287-4681-8e1b-cc1bd74e78c2.png">

### Steps To Reproduce

Create JSObject with the following content

```
export default {
	myFun1 :() => {  
	}
	myFun2: ()=>{}
}
```

### Version

Cloud

**Comment by bharath31** [comment]
Assuming 1% of JSObject users face this issue 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 30 |
| Effort (months)  | <<number>> |
