### ISSUE TITLE
JSON form reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15171]
https://www.notion.so/appsmith/JSON-form-57ec14b1826c49498dc9203a8b5fdf46

**Comment by chandannkumar** [comment]
Tested this and LGTM
- Tested the distance of Submit/reset button from bottom and right is same
- Tested the position of Button end and inputs end is same
- Tested the migration with older apps and observe no breakage
- Tested with CRUD apps
- Regression on JSON Form
