### ISSUE TITLE
[Bug]: Select inside a modal within a list widget doesn't show default value

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i have a list with a modal and data bound to a select widget inside the modal, changing the list modal and coming back doesn't show the default value 

### Steps To Reproduce

1. Add a list widget
2. Add a modal widget in a list item
3. Add a select widget in the modal and reference some default data from store or query
4. Change the list item selected to something which doesn't have the default value
5. Come back to the list item which has the default value

https://sharing.clickup.com/clip/p/t14293777/47c41405-f443-4a90-855b-f4f152a0a08e/screen-recording-2022-07-08-09:41.webm

### Version

Production

**Comment by Tooluloope** [comment]
Fixed in #15133

**Comment by Tooluloope** [comment]
https://user-images.githubusercontent.com/31691737/182542372-9dd0c88a-a508-40b5-818f-9ab11c604fbd.mov
