### ISSUE TITLE
[Bug]: Creating new cURL import query from entity explorer crashes the app

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#15175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we create new cURL import from entity explorer, it gives the error "Resource not found" and on refresh app crashes

https://user-images.githubusercontent.com/80334441/178717222-c4d20cd8-a9fc-4c5a-9689-75495c6d7661.mov

### Steps To Reproduce

1. Go to entity explorer 
2. Create new cURL import and observe

### Version

Release

**Comment by Richarex** [comment]
This issue is still happening reopening it.
![image](https://user-images.githubusercontent.com/93259714/178909593-01258629-4eab-4dfa-bca5-d89b436d5992.png)
