### ISSUE TITLE
[Feature]: Add onSuccess action selector for all actions using promise.then

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#15185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Previously we had controlled this because only queries had callbacks but with promises, all actions can be configured with callbacks

### Why should this be worked on?

This will allow users to configure onSuccess callbacks without converting to JS

**Comment by Nikhil-Nandagopal** [comment]
User request
https://app.intercom.com/a/apps/y10e7138/inbox/inbox/4281719/conversations/164629100142430

**Comment by ravikp7** [comment]
@satbir121 @bharath31 We now support `then` onSuccess for all platform functions except the ones for which this doesn't make sense like `getGeolocation` (This [doesn't support promise even in the actual browser API](https://w3c.github.io/geolocation-api/#getcurrentposition-method)), `stopGeolocation`, `setInterval`, `clearInterval`, and `postMessage`.

I think we can close this issue now.
