### ISSUE TITLE
[Bug]: Camera and Filepicker issues

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#15200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are many issues with the camera widget and file picker that prevent them from being used properly.

## Filepicker
1. Select a file
2. Navigate to the API
3. Come back to the canvas
4. Open the filepicker, the file is not showing but is present in the data
5. Changing the file format to binary doesn't update the actually data

## Camera Widget
The camera widget has internal properties of dataURL which is not expected. It needs to have a file object exactly as a filepicker which is generated based on the data format so that uploads can happen.

### Public Sample App

http://3.111.33.176/app/customer-support-dashboard/page1-62b2f40f3eee0a0040fcf699/edit

### Version

Self Hosted

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal I am closing this in favor of #11660 and #10680
