### ISSUE TITLE
[Docs]: Docs for table v2

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

We added inline edit support for table. Need to add documentation for it and a couple of other features

### Describe the improvement

Add docs for new feature - https://www.notion.so/appsmith/Table-v2-documentation-cb35640ac6294e9482a0044746810d41

**Comment by jnikhila** [comment]
Published.
