### ISSUE TITLE
[Bug]: trigger field errors don't show up in debugger

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#15212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unless executed, Trigger field errors don't show up in debugger.

### Steps To Reproduce

- Write erroneous code in button OnClick field.
- Notice debugger doesn't list the error.
- But it shows up when clicking on the button.

https://www.loom.com/share/768e087f907f4a9c90ad47baf285da84

### Public Sample App

https://drive.google.com/file/d/16H7YLK3ZtbZrzGgX97NYKYnMBKQbZN-z/view?usp=sharing

### Version

Cloud - v1.7.8-SNAPSHOT

**Comment by rohan-arthur** [comment]
closed with #35839
