### ISSUE TITLE
[Bug]: Error message persist when parent widget is deleted

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#15213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error messages of child widgets are not cleared when parent widget is deleted.

### Steps To Reproduce

https://www.loom.com/share/4842dc8cecf14d19b6c0d3c3bbc2153e

### Version

Cloud - 1.7.8

**Comment by ohansFavour** [comment]
This is already resolved
