### ISSUE TITLE
[Bug]: UI alignment for keyvalue array component in mongo datasource form

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#15234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The alignment of the label is off in the `keyvalue_array` component. 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/8526215/179209226-b92a5415-4798-4a92-a43a-d2cfe2b67170.png">

### Steps To Reproduce

1. Create a new mongo DB data source.
2. The datasource form will open, observe the UI of host address and port.

### Version

cloud

**Comment by btsgh** [comment]
Tested on Release and has been fixed. Port is now aligned correctly.
