### ISSUE TITLE
What is the appsmith equivalent to nuBuilder lookup?

### ISSUE THREAD

**Issue by m2acgi** [appsmithorg/appsmith#15243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Please check the gif screenshot. Click the paly button in the upper right corner of the gif to play.

### Why should this be worked on?

![2022-07-16_11-29-02](https://user-images.githubusercontent.com/34497122/179337529-13a01007-512c-4aae-b617-ff51c58d30d1.gif)

**Comment by Nikhil-Nandagopal** [comment]
@m2acgi you should be able to drag a modal widget and populate that with the values that you need
