### ISSUE TITLE
[Bug]-[4932]:Cannot read properties of undefined (reading 'properties')

### ISSUE THREAD

**Issue by juandl** [appsmithorg/appsmith#15247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the last update of appsmith, every time there's an issue happening using "GIT", I'm not actually sure how is happening, because after a day or 2 starts happening

![Screen Shot 2022-07-17 at 11 22 50 AM](https://user-images.githubusercontent.com/25650720/179390187-78713efb-912e-47d1-b324-9a088d7442d4.png)

It works again, after re-importing the project from git

### Steps To Reproduce

1. Import project from git
2. Change any page 
3. Commit changes
4 In this step is when we wait after a day or 2, start happening the issue

### Version

v1.7.8

**Comment by juandl** [comment]
I noticed that there is a pending change to commit, and when I try to "discard changes" it doesn't work and it keeps loading infinitely

**Comment by Nikhil-Nandagopal** [comment]
@juandl just so I understand, is this only an error in the console or does this impact your experience in any way?

**Comment by juandl** [comment]
> @juandl just so I understand, is this only an error in the console or does this impact your experience in any way?

It full impact the experience, because after this error happens I can't access to any of my pages. So edition mode and preview (after deployed) is not working at all and the appsmith crash with an error (same as the picture)

**Comment by AnaghHegde** [comment]
@juandl Are you on Appsmith cloud? If not would it be possible to share the backend logs from the Appsmith instance? You can share it with - anagh at appsmith.com
If you are on Appsmith cloud please invite me to the same app. Email id - support at appsmith.com

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 822 |
| Effort (months)  | 0.5 |

**Comment by simonwanghub** [comment]
![image](https://user-images.githubusercontent.com/30173054/224544212-bfd55051-bb5b-4205-b2ea-5748cbbff0f9.png)

I export from cloud, import docker fail

**Comment by simonwanghub** [comment]
has error as below:


d-e9ee23a23b12 - Checking if feature GIT_IMPORT is active for user 78479896@qq.com
backend stdout |
rts stdout | Error response received while authentication:  {
rts stdout |   status: 404,
rts stdout |   statusText: 'Not Found',
rts stdout |   headers: {
rts stdout |     vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
rts stdout |     'content-type': 'application/json',
rts stdout |     'content-length': '90',
rts stdout |     'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
rts stdout |     pragma: 'no-cache',
rts stdout |     expires: '0',
rts stdout |     'x-content-type-options': 'nosniff',
rts stdout |     'x-frame-options': 'DENY',
rts stdout |     'x-xss-protection': '1 ; mode=block',
rts stdout |     'referrer-policy': 'no-referrer',
rts stdout |     connection: 'close'
rts stdout |   },
rts stdout |   config: {
rts stdout |     url: 'http://localhost:8080/users/me',
rts stdout |     method: 'get',
rts stdout |     headers: {
rts stdout |       Accept: 'application/json, text/plain, */*',
rts stdout |       Cookie: 'SESSION=5df20d02-b319-43b8-bdeb-e24ac2937fc1',
rts stdout |       'User-Agent': 'axios/0.21.2'
rts stdout |     },
rts stdout |     transformRequest: [ [Function: transformRequest] ],
rts stdout |     transformResponse: [ [Function: transformResponse] ],
rts stdout |     timeout: 0,
rts stdout |     adapter: [Function: httpAdapter],
rts stdout |     xsrfCookieName: 'XSRF-TOKEN',
rts stdout |     xsrfHeaderName: 'X-XSRF-TOKEN',
rts stdout |     maxContentLength: -1,
rts stdout |     maxBodyLength: -1,
rts stdout |     validateStatus: [Function: validateStatus],
rts stdout |     transitional: {
rts stdout |       silentJSONParsing: true,
rts stdout |       forcedJSONParsing: true,
rts stdout |       clarifyTimeoutError: false
rts stdout |     },
rts stdout |     data: undefined
rts stdout |   },
rts stdout |   request: <ref *1> ClientRequest {
rts stdout |     _events: [Object: null prototype] {
rts stdout |       abort: [Function (anonymous)],
rts stdout |       aborted: [Function (anonymous)],
rts stdout |       connect: [Function (anonymous)],
rts stdout |       error: [Function (anonymous)],
rts stdout |       socket: [Function (anonymous)],
rts stdout |       timeout: [Function (anonymous)],
rts stdout |       prefinish: [Function: requestOnPrefinish]
rts stdout |     },
rts stdout |     _eventsCount: 7,
rts stdout |     _maxListeners: undefined,
rts stdout |     outputData: [],
rts stdout |     outputSize: 0,
rts stdout |     writable: true,
rts stdout |     destroyed: false,
rts stdout |     _last: true,
rts stdout |     chunkedEncoding: false,
rts stdout |     shouldKeepAlive: false,
rts stdout |     _defaultKeepAlive: true,
rts stdout |     useChunkedEncodingByDefault: false,
rts stdout |     sendDate: false,
rts stdout |     _removedConnection: false,
rts stdout |     _removedContLen: false,
rts stdout |     _removedTE: false,
rts stdout |     _contentLength: 0,
rts stdout |     _hasBody: true,
rts stdout |     _trailer: '',
rts stdout |     finished: true,
rts stdout |     _headerSent: true,
rts stdout |     socket: Socket {
rts stdout |       connecting: false,
rts stdout |       _hadError: false,
rts stdout |       _parent: null,
rts stdout |       _host: 'localhost',
rts stdout |       _readableState: [ReadableState],
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 7,
rts stdout |       _maxListeners: undefined,
rts stdout |       _writableState: [WritableState],
rts stdout |       allowHalfOpen: false,
rts stdout |       _sockname: null,
rts stdout |       _pendingData: null,
rts stdout |       _pendingEncoding: '',
rts stdout |       server: null,
rts stdout |       _server: null,
rts stdout |       parser: null,
rts stdout |       _httpMessage: [Circular *1],
rts stdout |       [Symbol(async_id_symbol)]: 5765,
rts stdout |       [Symbol(kHandle)]: [TCP],
rts stdout |       [Symbol(kSetNoDelay)]: false,
rts stdout |       [Symbol(lastWriteQueueSize)]: 0,
rts stdout |       [Symbol(timeout)]: null,
rts stdout |       [Symbol(kBuffer)]: null,
rts stdout |       [Symbol(kBufferCb)]: null,
rts stdout |       [Symbol(kBufferGen)]: null,
rts stdout |       [Symbol(kCapture)]: false,
rts stdout |       [Symbol(kBytesRead)]: 0,
rts stdout |       [Symbol(kBytesWritten)]: 0,
rts stdout |       [Symbol(RequestTimeout)]: undefined
rts stdout |     },
rts stdout |     _header: 'GET /users/me HTTP/1.1\r\n' +
rts stdout |       'Accept: application/json, text/plain, */*\r\n' +
rts stdout |       'Cookie: SESSION=5df20d02-b319-43b8-bdeb-e24ac2937fc1\r\n' +
rts stdout |       'User-Agent: axios/0.21.2\r\n' +
rts stdout |       'Host: localhost:8080\r\n' +
rts stdout |       'Connection: close\r\n' +
rts stdout |       '\r\n',
rts stdout |     _keepAliveTimeout: 0,
rts stdout |     _onPendingData: [Function: noopPendingOutput],
rts stdout |     agent: Agent {
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 2,
rts stdout |       _maxListeners: undefined,
rts stdout |       defaultPort: 80,
rts stdout |       protocol: 'http:',
rts stdout |       options: [Object],
rts stdout |       requests: {},
rts stdout |       sockets: [Object],
rts stdout |       freeSockets: {},
rts stdout |       keepAliveMsecs: 1000,
rts stdout |       keepAlive: false,
rts stdout |       maxSockets: Infinity,
rts stdout |       maxFreeSockets: 256,
rts stdout |       scheduling: 'lifo',
rts stdout |       maxTotalSockets: Infinity,
rts stdout |       totalSocketCount: 2,
rts stdout |       [Symbol(kCapture)]: false
rts stdout |     },
rts stdout |     socketPath: undefined,
rts stdout |     method: 'GET',
rts stdout |     maxHeaderSize: undefined,
rts stdout |     insecureHTTPParser: undefined,
rts stdout |     path: '/users/me',
rts stdout |     _ended: true,
rts stdout |     res: IncomingMessage {
rts stdout |       _readableState: [ReadableState],
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 3,
rts stdout |       _maxListeners: undefined,
rts stdout |       socket: [Socket],
rts stdout |       httpVersionMajor: 1,
rts stdout |       httpVersionMinor: 1,
rts stdout |       httpVersion: '1.1',
rts stdout |       complete: true,
rts stdout |       headers: [Object],
rts stdout |       rawHeaders: [Array],
rts stdout |       trailers: {},
rts stdout |       rawTrailers: [],
rts stdout |       aborted: false,
rts stdout |       upgrade: false,
rts stdout |       url: '',
rts stdout |       method: null,
rts stdout |       statusCode: 404,
rts stdout |       statusMessage: 'Not Found',
rts stdout |       client: [Socket],
rts stdout |       _consuming: false,
rts stdout |       _dumped: false,
rts stdout |       req: [Circular *1],
rts stdout |       responseUrl: 'http://localhost:8080/users/me',
rts stdout |       redirects: [],
rts stdout |       [Symbol(kCapture)]: false,
rts stdout |       [Symbol(RequestTimeout)]: undefined
rts stdout |     },
rts stdout |     aborted: false,
rts stdout |     timeoutCb: null,
rts stdout |     upgradeOrConnect: false,
rts stdout |     parser: null,
rts stdout |     maxHeadersCount: null,
rts stdout |     reusedSocket: false,
rts stdout |     host: 'localhost',
rts stdout |     protocol: 'http:',
rts stdout |     _redirectable: Writable {
rts stdout |       _writableState: [WritableState],
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 2,
rts stdout |       _maxListeners: undefined,
rts stdout |       _options: [Object],
rts stdout |       _ended: true,
rts stdout |       _ending: true,
rts stdout |       _redirectCount: 0,
rts stdout |       _redirects: [],
rts stdout |       _requestBodyLength: 0,
rts stdout |       _requestBodyBuffers: [],
rts stdout |       _onNativeResponse: [Function (anonymous)],
rts stdout |       _currentRequest: [Circular *1],
rts stdout |       _currentUrl: 'http://localhost:8080/users/me',
rts stdout |       [Symbol(kCapture)]: false
rts stdout |     },
rts stdout |     [Symbol(kCapture)]: false,
rts stdout |     [Symbol(kNeedDrain)]: false,
rts stdout |     [Symbol(corked)]: 0,
rts stdout |     [Symbol(kOutHeaders)]: [Object: null prototype] {
rts stdout |       accept: [Array],
rts stdout |       cookie: [Array],
rts stdout |       'user-agent': [Array],
rts stdout |       host: [Array]
rts stdout |     }
rts stdout |   },
rts stdout |   data: { responseMeta: { status: 404, success: false, error: [Object] } }
rts stdout | }
rts stdout |
rts stdout | Error response received while authentication:  {
rts stdout |   status: 404,
rts stdout |   statusText: 'Not Found',
rts stdout |   headers: {
rts stdout |     vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
rts stdout |     'content-type': 'application/json',
rts stdout |     'content-length': '90',
rts stdout |     'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
rts stdout |     pragma: 'no-cache',
rts stdout |     expires: '0',
rts stdout |     'x-content-type-options': 'nosniff',
rts stdout |     'x-frame-options': 'DENY',
rts stdout |     'x-xss-protection': '1 ; mode=block',
rts stdout |     'referrer-policy': 'no-referrer',
rts stdout |     connection: 'close'
rts stdout |   },
rts stdout |   config: {
rts stdout |     url: 'http://localhost:8080/users/me',
rts stdout |     method: 'get',
rts stdout |     headers: {
rts stdout |       Accept: 'application/json, text/plain, */*',
rts stdout |       Cookie: 'SESSION=5df20d02-b319-43b8-bdeb-e24ac2937fc1',
rts stdout |       'User-Agent': 'axios/0.21.2'
rts stdout |     },
rts stdout |     transformRequest: [ [Function: transformRequest] ],
rts stdout |     transformResponse: [ [Function: transformResponse] ],
rts stdout |     timeout: 0,
rts stdout |     adapter: [Function: httpAdapter],
rts stdout |     xsrfCookieName: 'XSRF-TOKEN',
rts stdout |     xsrfHeaderName: 'X-XSRF-TOKEN',
rts stdout |     maxContentLength: -1,
rts stdout |     maxBodyLength: -1,
rts stdout |     validateStatus: [Function: validateStatus],
rts stdout |     transitional: {
rts stdout |       silentJSONParsing: true,
rts stdout |       forcedJSONParsing: true,
rts stdout |       clarifyTimeoutError: false
rts stdout |     },
rts stdout |     data: undefined
rts stdout |   },
rts stdout |   request: <ref *1> ClientRequest {
rts stdout |     _events: [Object: null prototype] {
rts stdout |       abort: [Function (anonymous)],
rts stdout |       aborted: [Function (anonymous)],
rts stdout |       connect: [Function (anonymous)],
rts stdout |       error: [Function (anonymous)],
rts stdout |       socket: [Function (anonymous)],
rts stdout |       timeout: [Function (anonymous)],
rts stdout |       prefinish: [Function: requestOnPrefinish]
rts stdout |     },
rts stdout |     _eventsCount: 7,
rts stdout |     _maxListeners: undefined,
rts stdout |     outputData: [],
rts stdout |     outputSize: 0,
rts stdout |     writable: true,
rts stdout |     destroyed: false,
rts stdout |     _last: true,
rts stdout |     chunkedEncoding: false,
rts stdout |     shouldKeepAlive: false,
rts stdout |     _defaultKeepAlive: true,
rts stdout |     useChunkedEncodingByDefault: false,
rts stdout |     sendDate: false,
rts stdout |     _removedConnection: false,
rts stdout |     _removedContLen: false,
rts stdout |     _removedTE: false,
rts stdout |     _contentLength: 0,
rts stdout |     _hasBody: true,
rts stdout |     _trailer: '',
rts stdout |     finished: true,
rts stdout |     _headerSent: true,
rts stdout |     socket: Socket {
rts stdout |       connecting: false,
rts stdout |       _hadError: false,
rts stdout |       _parent: null,
rts stdout |       _host: 'localhost',
rts stdout |       _readableState: [ReadableState],
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 7,
rts stdout |       _maxListeners: undefined,
rts stdout |       _writableState: [WritableState],
rts stdout |       allowHalfOpen: false,
rts stdout |       _sockname: null,
rts stdout |       _pendingData: null,
rts stdout |       _pendingEncoding: '',
rts stdout |       server: null,
rts stdout |       _server: null,
rts stdout |       parser: null,
rts stdout |       _httpMessage: [Circular *1],
rts stdout |       [Symbol(async_id_symbol)]: 5805,
rts stdout |       [Symbol(kHandle)]: [TCP],
rts stdout |       [Symbol(kSetNoDelay)]: false,
rts stdout |       [Symbol(lastWriteQueueSize)]: 0,
rts stdout |       [Symbol(timeout)]: null,
rts stdout |       [Symbol(kBuffer)]: null,
rts stdout |       [Symbol(kBufferCb)]: null,
rts stdout |       [Symbol(kBufferGen)]: null,
rts stdout |       [Symbol(kCapture)]: false,
rts stdout |       [Symbol(kBytesRead)]: 0,
rts stdout |       [Symbol(kBytesWritten)]: 0,
rts stdout |       [Symbol(RequestTimeout)]: undefined
rts stdout |     },
rts stdout |     _header: 'GET /users/me HTTP/1.1\r\n' +
rts stdout |       'Accept: application/json, text/plain, */*\r\n' +
rts stdout |       'Cookie: SESSION=5df20d02-b319-43b8-bdeb-e24ac2937fc1\r\n' +
rts stdout |       'User-Agent: axios/0.21.2\r\n' +
rts stdout |       'Host: localhost:8080\r\n' +
rts stdout |       'Connection: close\r\n' +
rts stdout |       '\r\n',
rts stdout |     _keepAliveTimeout: 0,
rts stdout |     _onPendingData: [Function: noopPendingOutput],
rts stdout |     agent: Agent {
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 2,
rts stdout |       _maxListeners: undefined,
rts stdout |       defaultPort: 80,
rts stdout |       protocol: 'http:',
rts stdout |       options: [Object],
rts stdout |       requests: {},
rts stdout |       sockets: [Object],
rts stdout |       freeSockets: {},
rts stdout |       keepAliveMsecs: 1000,
rts stdout |       keepAlive: false,
rts stdout |       maxSockets: Infinity,
rts stdout |       maxFreeSockets: 256,
rts stdout |       scheduling: 'lifo',
rts stdout |       maxTotalSockets: Infinity,
rts stdout |       totalSocketCount: 2,
rts stdout |       [Symbol(kCapture)]: false
rts stdout |     },
rts stdout |     socketPath: undefined,
rts stdout |     method: 'GET',
rts stdout |     maxHeaderSize: undefined,
rts stdout |     insecureHTTPParser: undefined,
rts stdout |     path: '/users/me',
rts stdout |     _ended: true,
rts stdout |     res: IncomingMessage {
rts stdout |       _readableState: [ReadableState],
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 3,
rts stdout |       _maxListeners: undefined,
rts stdout |       socket: [Socket],
rts stdout |       httpVersionMajor: 1,
rts stdout |       httpVersionMinor: 1,
rts stdout |       httpVersion: '1.1',
rts stdout |       complete: true,
rts stdout |       headers: [Object],
rts stdout |       rawHeaders: [Array],
rts stdout |       trailers: {},
rts stdout |       rawTrailers: [],
rts stdout |       aborted: false,
rts stdout |       upgrade: false,
rts stdout |       url: '',
rts stdout |       method: null,
rts stdout |       statusCode: 404,
rts stdout |       statusMessage: 'Not Found',
rts stdout |       client: [Socket],
rts stdout |       _consuming: false,
rts stdout |       _dumped: false,
rts stdout |       req: [Circular *1],
rts stdout |       responseUrl: 'http://localhost:8080/users/me',
rts stdout |       redirects: [],
rts stdout |       [Symbol(kCapture)]: false,
rts stdout |       [Symbol(RequestTimeout)]: undefined
rts stdout |     },
rts stdout |     aborted: false,
rts stdout |     timeoutCb: null,
rts stdout |     upgradeOrConnect: false,
rts stdout |     parser: null,
rts stdout |     maxHeadersCount: null,
rts stdout |     reusedSocket: false,
rts stdout |     host: 'localhost',
rts stdout |     protocol: 'http:',
rts stdout |     _redirectable: Writable {
rts stdout |       _writableState: [WritableState],
rts stdout |       _events: [Object: null prototype],
rts stdout |       _eventsCount: 2,
rts stdout |       _maxListeners: undefined,
rts stdout |       _options: [Object],
rts stdout |       _ended: true,
rts stdout |       _ending: true,
rts stdout |       _redirectCount: 0,
rts stdout |       _redirects: [],
rts stdout |       _requestBodyLength: 0,
rts stdout |       _requestBodyBuffers: [],
rts stdout |       _onNativeResponse: [Function (anonymous)],
rts stdout |       _currentRequest: [Circular *1],
rts stdout |       _currentUrl: 'http://localhost:8080/users/me',
rts stdout |       [Symbol(kCapture)]: false
rts stdout |     },
rts stdout |     [Symbol(kCapture)]: false,
rts stdout |     [Symbol(kNeedDrain)]: false,
rts stdout |     [Symbol(corked)]: 0,
rts stdout |     [Symbol(kOutHeaders)]: [Object: null prototype] {
rts stdout |       accept: [Array],
rts stdout |       cookie: [Array],
rts stdout |       'user-agent': [Array],
rts stdout |       host: [Array]
rts stdout |     }
rts stdout |   },
rts stdout |   data: { responseMeta: { status: 404, success: false, error: [Object] } }
rts stdout | }
rts stdout |
backend stdout | userEmail=78479896@qq.com, sessionId=5df20d02-b319-43b8-bdeb-e24ac2937fc1, thread=lettuce-epollEventLoop-7-1, requestId=43873069-7d73-4398-ad66-10714b7f6579 - Going to get all published action collections with application Id: 640dcd209a90505aead562da, branch: null
backend stdout |
backend stdout |  -
backend stdout | java.lang.NullPointerException: The mapper returned a null value.
backend stdout | 	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout | 	|_ checkpoint ⇢ Handler com.appsmith.server.controllers.PageController#getPageNamesByApplicationIdInViewMode(String, String) [DispatcherHandler]
backend stdout | Stack trace:
backend stdout | 		at java.base/java.util.Objects.requireNonNull(Objects.java:246)
backend stdout | 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:151)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4346)
backend stdout | 		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
backend stdout | 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
backend stdout | 		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredComplete(FluxUsingWhen.java:405)
backend stdout | 		at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:540)
backend stdout | 		at reactor.core.publisher.Operators.complete(Operators.java:137)
backend stdout | 		at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4361)
backend stdout | 		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:397)
backend stdout | 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
backend stdout | 		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
backend stdout | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058)
backend stdout | 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
backend stdout | 		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:367)
backend stdout | 		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:276)
backend stdout | 		at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:439)
backend stdout | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:784)
backend stdout | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:732)
backend stdout | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:240)
backend stdout | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:206)
backend stdout | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:197)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$recurseCursor$4(BatchCursorFlux.java:98)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:171)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout | 		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
backend stdout | 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout | 		at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:207)
backend stdout | 		at com.mongodb.internal.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:146)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursor.lambda$next$0(BatchCursor.java:35)
backend stdout | 		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4361)
backend stdout | 		at reactor.core.publisher.Mono.subscribeWith(Mono.java:4476)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4193)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.recurseCursor(BatchCursorFlux.java:104)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$0(BatchCursorFlux.java:56)
backend stdout | 		at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
backend stdout | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout | 		at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$sinkToCallback$30(MongoOperationPublisher.java:550)
backend stdout | 		at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$2(OperationExecutorImpl.java:73)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.operation.FindOperation$3.onResult(FindOperation.java:755)
backend stdout | 		at com.mongodb.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:532)
backend stdout | 		at com.mongodb.internal.operation.CommandOperationHelper$10.onResult(CommandOperationHelper.java:483)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:286)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:84)
backend stdout | 		at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection$2.onResult(DefaultConnectionPool.java:530)
backend stdout | 		at com.mongodb.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:142)
backend stdout | 		at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:462)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:439)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:744)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:711)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:581)
backend stdout | 		at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:578)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.readAsync(NettyStream.java:322)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.handleReadResponse(NettyStream.java:350)
backend stdout | 		at com.mongodb.connection.netty.NettyStream.access$1200(NettyStream.java:104)
backend stdout | 		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:409)
backend stdout | 		at com.mongodb.connection.netty.NettyStream$InboundBufferHandler.channelRead0(NettyStream.java:406)
backend stdout | 		at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
backend stdout | 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout | 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout | 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
backend stdout | 		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
backend stdout | 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
backend stdout | 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
backend stdout | 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout | 		at java.base/java.lang.Thread.run(Thread.java:829)
