### ISSUE TITLE
[Bug] Widget scroller is not displayed to user on windows chrome browser

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1525]
When the user navigates to widget page the user is not displayed with scroller to navigate to the layout section of the widget page 

Environment:
Chrome > Windows 7 > Release and Master

However n firefox the scroller is visible to user 
 
![widgetscroller](https://user-images.githubusercontent.com/71753653/97958721-cbd57100-1dd3-11eb-8b5d-518501cad98f.png)

**Comment by vivekverma2312** [comment]
Not able to repro the issue. We ca close the issue.

**Comment by YogeshJayaseelan** [comment]
Verified this issue in Windows 10 chrome browser - Widget scroller is available and accessible
