### ISSUE TITLE
[Bug]-[440]:Airtable API key/ Bearer token field does not appear on the datasource

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#15253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user tries to add the token or key after the selection it is observed that the field does not appear 

### Steps To Reproduce

1) Navigate to datasource
2) select the Airtable
3) Select  API key/ Bearer token
and observe that field to add the key is not displayed to the user
![Screenshot 2022-07-18 at 10 54 48 AM](https://user-images.githubusercontent.com/71753653/179449813-bfab0042-4128-4c10-a5ff-a8c1d5bb260c.png)

### Public Sample App

release

### Version

cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5zhsc)

**Comment by felixsuarez0727** [comment]
Inputs are working fine for me. I'm unable to reproduce.

This bug seems to be intermittent, I'm still trying to figure out the source cause.

**Comment by subrata71** [comment]
@felixsuarez0727 
This is the server response I am getting when clicking on creating new Airtable datasource

```
{
    "responseMeta": {
        "status": 201,
        "success": true
    },
    "data": {
        "id": "62d5a0c13df1fa12f087f0d3",
        "userPermissions": [
            "execute:datasources",
            "manage:datasources",
            "read:datasources"
        ],
        "gitSyncId": "629498fe0b092f4f690a5d4e_62d5a0c03df1fa12f087f0d2",
        "name": "Untitled Datasource 8",
        "pluginId": "61531b1b9370f312a0394f16",
        "pluginName": "Airtable",
        "workspaceId": "629498fe0b092f4f690a5d4e",
        "invalids": [
            "No datasource configuration found. Please configure it and try again."
        ],
        "messages": [],
        "isConfigured": false,
        "isValid": false,
        "new": false
    }
}
```

**Comment by felixsuarez0727** [comment]
This was taken from  Prod, the response does seem to be the right one.

```json
{
	"responseMeta": {
		"status": 201,
		"success": true
	},
	"data": {
		"id": "62d976efe1c2ed505a05897f",
		"userPermissions": ["execute:datasources", "manage:datasources", "read:datasources"],
		"gitSyncId": "62d76be5b06ce90d91dbe9de_62d976efe1c2ed505a05897e",
		"name": "Untitled Datasource 4",
		"pluginId": "61dbfd4b6bd5757f166ccc76",
		"pluginName": "Airtable",
		"workspaceId": "62d76be5b06ce90d91dbe9de",
		"invalids": ["No datasource configuration found. Please configure it and try again."],
		"messages": [],
		"isConfigured": false,
		"isValid": false,
		"new": false
	}
}
```

**Comment by felixsuarez0727** [comment]
Since we are using the Release Importer (tool that copies integration config from Prod to Release), I would expect the `pluginId` to be the same, yet it is not. (I will be looking into this)

Another behavior that I have noticed is that this seems to be intermittent. I couldn't reproduce it for the last couple of days, yet @AmanAgarwal041 and @prapullac were able to provide picture. Nonetheless, yesterday @AmanAgarwal041 was unable to reproduce it on the same organization he was able to reproduce it a day ago.

**Comment by felixsuarez0727** [comment]
# The following tests were performed

## Steps to Reproduce
1. Login to release.app.appsmith.com
2. Create a new Twilio datasource
3. Verify if the authentication inputs appear.
4. Verify the inputs of the actions 

This happens on the following environments:

- Firefox: (64 bit) on Ubuntu 20.04.3
- Chrome: (64-bit) on Windows 10

| Operating System  | Browser |Number of Tests | Inputs Work |
|---|---|---|---|
|  Ubuntu | Chrome  | 10                          | Yes |
|  Ubuntu | Firefox  | 10                          | Yes |
|  Windows | Chrome | 10                          | Yes |
|  Windows | Firefox  | 10                          | Yes |
|  Windows | Microsoft Edge  | 10                          | Yes |
|  Windows | Opera  | 10                          | Yes |


https://images.zenhubusercontent.com/275993885/e136f136-ec79-4461-a09b-97529d69b121/video1.mp4

https://images.zenhubusercontent.com/275993885/12dd34fc-c195-4a1b-a460-215ad30a5fdb/video2.mp4

## Note: 

- When the page was accessed, the inputs did not load, but when the tests were about to be carried out, they worked.

- We also installed the browser from scratch on a computer that did not have it, and it worked, we were unable to reproduce the error with this tests

**Comment by felixsuarez0727** [comment]
I created this table to have a register of the moments that Release works, maybe this way we can see a pattern 

|Date	|Worked  |URL|
|--- | --- | --- |
|2022-27-07 16:15:00|  No | release.app.appsmith.com / our instance|
|2022-27-07 18:44:00|  Yes |release.app.appsmith.com / our instance|
|2022-28-07 16:20:00| Yes |release.app.appsmith.com / our instance|

**Comment by felixsuarez0727** [comment]
I also tested on Release_aug1 of the prapulla branch. And at the time of 2022-01-08 20:00:00 (UTC) the inputs worked fine.

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/683524c7-9615-49f3-8ed7-b62a23be40ce)

**Comment by felixsuarez0727** [comment]
To check with Sumit.

**Comment by felixsuarez0727** [comment]
Sumit is currently looking at this issue.

**Comment by sumitsum** [comment]
Airtable usage in 6m: 331
% of users impacted: 50 %
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 165 |
| Effort (months)  | 0.75 |

**Comment by praneetloke** [comment]
I am experiencing this issue right now. I've tried to restart AppSmith to no luck. It also seems that the Queries against such a datasource also lose the ability to display any of the inputs. Strangely, I can see the input field for the "Bearer Token" authentication mechanism. Is there anything else I can do to help diagnose this issue?

**Comment by GreenFlux** [comment]
another user is facing this issue on Discord:
https://discord.com/channels/725602949748752515/1064204306951176302

**Comment by btsgh** [comment]
Reproduced this again on Release Regression on 1.9.5 [24th jan 2023]

**Comment by Irongade** [comment]
After discussing with Nidhi, we confirmed that a backend engineer would be better poised to fix this issue as they'll need to work on the Java code that returns these configs. This is because Airtable is a saas plugin and there is no explicit form that is kept on the server side for the Airtable plugin that I can manually fix.

**Comment by sumitsum** [comment]
Removed the release blocker tag since the issue still looks flaky - i.e same behaviour as before.

**Comment by btsgh** [comment]
Have pinged @sumitsum to understand the steps to setup the cloud services locally. Waiting for a response on this. Unable to proceed after step 2 in the PR

**Comment by btsgh** [comment]
This has been tested as per the steps mentioned in the fix and it is working fine. Hence moving the issue to Ready to Merge.
