### ISSUE TITLE
[Bug]:  On setting "Enable multi row selection" to true - the property pane moves as Default Selected Row field is modified

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 When I toggle "Enable multi row selection" - the property pane moves up/down

### Steps To Reproduce

1. Drag and drop a table widget
2. Turn on the "Enable multi row selection" toggle.

Observe that there is movement in the property pane. This did not happen in Prod. 

Expected behaviour - this movement should not happen in the pane when the user toggles.

Note: This is because of the Default Selected Row property value and name getting changed on toggling.

### Version

Release

**Comment by trishitapingolia** [comment]
Can i work on this?

**Comment by dilippitchika** [comment]
Greetings @trishitapingolia  thanks for showing interest 🎉 , This is all your. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by trishitapingolia** [comment]
> Greetings @trishitapingolia  thanks for showing interest 🎉 , This is all your. Assigning this to you now.
> 
> Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

Thankyou for the assignment. Can you please elaborate the issue. I tried understanding the issue but couldn't get the exact problem.

**Comment by nasserabd** [comment]
Hello, can I be assigned this issue and contribute? Would love to give it a shot

**Comment by sundaram2021** [comment]
hey @btsgh are you talking about the movement of default selected rows in the pane

**Comment by btsgh** [comment]
> hey @btsgh are you talking about the movement of default selected rows in the pane

Yes that's correct.

**Comment by sundaram2021** [comment]
> > hey @btsgh are you talking about the movement of default selected rows in the pane
> 
> Yes that's correct.

then  whats wrong in this 
when you toggle for multiple rows then "default selected row" should be converted to "default selected rows".
thats doesn't seems to be a problem

@btsgh  please correct me if i am wrong or if i am going wrong on this particular issue

**Comment by btsgh** [comment]
> > > hey @btsgh are you talking about the movement of default selected rows in the pane
> > 
> > 
> > Yes that's correct.
> 
> then whats wrong in this when you toggle for multiple rows then "default selected row" should be converted to "default selected rows". thats doesn't seems to be a problem
> 
> @btsgh please correct me if i am wrong or if i am going wrong on this particular issue

Yes - I guess this issue no longer valid. I had raised this issue more than a year ago - since at that time, it had regressed from the previous behaviour.  @dilippitchika  - just checking back once with you as well, guess this can be closed out?

**Comment by chulbulji67** [comment]
is this isssue resolved?

**Comment by dvj1988** [comment]
@btsgh This bug is not valid anymore. We can close this bug.


https://github.com/appsmithorg/appsmith/assets/18716465/b17fc9ae-378f-45e0-a715-0b5d116fba83
