### ISSUE TITLE
[Bug]: Tooltip on Update Mode option needs to start with capital

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I hover over the Update Mode option to know what it does, the tool tip that appears for it starts with a lower case. It should start with an uppercase.

### Steps To Reproduce

1. Drag and drop a table widget
2. Hover over the Update Mode property in the property pane 

The tooltip on this starts with a lower case letter. Change it to upper case.
<img width="403" alt="Screenshot 2022-07-18 at 2 33 28 PM" src="https://user-images.githubusercontent.com/101863839/179480843-3ade62c3-75d2-4e13-969b-b1e86eee6ece.png">

### Version

Release

**Comment by dilippitchika** [comment]
@sbalaji1192 can you fix this asap?

**Comment by sbalaji1192** [comment]
@dilippitchika Sure. I will fix this along with https://github.com/appsmithorg/appsmith/issues/15256
