### ISSUE TITLE
[Bug] API URL field allows multiline input causing big twitch in UI

### ISSUE THREAD

**Issue by sumanthyedoti** [appsmithorg/appsmith#1526]
![97785414-dbce3480-1bca-11eb-891f-b0628d7cea16](https://user-images.githubusercontent.com/30371888/97957786-e575b900-1dd1-11eb-9b0d-cf1c61eb8528.gif)

### Steps to reproduce the behaviour:
1. Go to API pane
2. Enter **multiline** input in URL field
3. Toggle between *focus* and *blur* on the field

**Comment by hetunandu** [comment]
We should disable multiline characters in single line fields to avoid getting into this situation

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu but this UX was working fine before. Why did it break?

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal we never disallowed the new line characters in the URL field AFAIK. Earlier it still used to go into the single line state for long strings on blur of the input but i am not sure how it was working when we added line breaks in the input.

@sumanthyedoti The issue with the twitch should have been resolved in your earlier commit.
