### ISSUE TITLE
[Bug]: Selecting datasources using keyboard shortcut selects previous entry and not selected entry, query template does not load

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Issue # 1:** Selecting datasources from keyboard shortcut from the entity explorer ends up picking the previous entry and not the selected datasource.

**Issue # 2:** Creating queries this way leads to some query templates not loading at all (i.e. wait time is infinite). User has to refresh page to see the query template else the app shows a `Loading.....` placeholder that does not change (See at at 41s  mark of the attached video)

### Steps To Reproduce

1. Use the entity explorer shortcut to select a datasource
2. Use your keyboard keys to scroll down and select a datasource, preferably to the next page on the dropdown to consistently repro this issue - observe the selected datasource's template does not open up, instead it's the option listed just before the selected option. (Issue # 1)
3. Some queries take a long time to load templates (wait time is infinite), only refreshing the page loads the template as expected (Issue # 2)

https://www.loom.com/share/2c5064caabf148338fd79b8f54a83a71

### Version

Cloud

**Comment by akash-codemonk** [comment]
Issue 3 is the same as reported in https://github.com/appsmithorg/appsmith/issues/15127.
