### ISSUE TITLE
[Bug]: On selecting "Auth as Header" does not display view mode as header and refers to as BODY

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#15270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when an Auth is added to a header in the edit mode it is observed that on view mode we are still displaying it as  BODY 

### Steps To Reproduce

1) Navigate to Auth API
2) Add an API with Auth in the header
3) Save the Datasource
and observe that it is displayed as body 
![Screenshot 2022-07-18 at 2 58 33 PM](https://user-images.githubusercontent.com/71753653/179492057-5d8e269d-5fd2-4964-b7d1-22e67155e44d.png)

### Public Sample App

release

### Version

cloud

**Comment by AmanAgarwal041** [comment]
This is working fine :
- create an API datasource
- Add datasource url
- select `oAuth2.0` as authentication
- select `Grant Type` as `Authorization Code`
- Go to advanced settings and  click to open the collapsible group
- Select `Header` in `Send client credentials with (on refresh token):` option
- Hit save. See the `Send client credentials with (on refresh token):` value changes to header.

**Comment by prapullac** [comment]
tested with the above steps and observed that it is working as expected
