### ISSUE TITLE
[Bug]: App saving state frequently ends up in an error state

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App saving state frequently ends up in an error state (yellow icon) instead of saving successfully

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/megamind/save-state-error-62d541b53df1fa12f087ef68/edit) location
2. Drag and drop widgets/ create queries/ objects and observe the save state turn yellow at some point

![image](https://user-images.githubusercontent.com/79509062/179500686-fdadf814-7039-4857-92b4-da0e3f7ab5d7.png)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno @rohitagarwal88 can we triage this? I've seen this occur frequently as well

**Comment by rohitagarwal88** [comment]
@yaldram Please triage this issue.
