### ISSUE TITLE
[Bug]: Documentation links thru ctrl+k, query pane, debugger are broken

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#15279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we click on documentation thru ctrl+K in editor, Query pane and debugger pane.

If we click on any widgets and click on "pop out" icon, and once the page is loaded we see "Page not loaded"

### Steps To Reproduce

1. Click "Ctrl+k" in editor or click on Query, new Datasource, click on any error and click on "Browse code snippets", close the snippets filter
2. Click on "Search Documentation"
3. Click on any widget and click on "Pop up" icon or "Open Documentation"
4. Observe "Page not found" error opened in next tab
![image (5)](https://user-images.githubusercontent.com/104895602/179524753-89008688-59aa-44af-86fe-b9409836a958.png)

### Version

Release

**Comment by kocharrahul7** [comment]
I believe this is now closed cause of this fix

https://github.com/appsmithorg/appsmith/pull/14605 

Please confirm
