### ISSUE TITLE
[Bug]: Function is not identified as async

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#15273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```sendSMS.run()``` is a valid function, however the query throws this error
 
![image](https://user-images.githubusercontent.com/55969597/179495956-ddd49ab9-2c21-4cae-a666-d1194f1f9798.png)

### Steps To Reproduce

1. Create a JSObject
2. 	```sendSMSFuncold: () => {
		const selectedNums = Table1?.selectedRows?.map((row) => row?.sms_number);
		selectedNums.forEach((num) => {
			sendSMS.run({num});
		});
	}``` 
where ```Table1``` is populated with some data and has column ```sms_number``` and ```sendSMS``` is the Twilio ```Create Message``` API. 

### Version

Cloud - 1.7.7

**Comment by ApekshaBhosale** [comment]
Findings: while checking isFunctionAsync we are sending unEvalDataTree hence it fails to recognize this function is async resulting in API not available
