### ISSUE TITLE
[Bug]-[600]:Documentation from Query Data source loading to the middle of document

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#15280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we click on new Query Datasource, and click on "Documentation" in right side, an omni bar opens, when we click on any topic it jumps to the middle of the topic and not focused on the heading of the topic

![image](https://user-images.githubusercontent.com/104895602/179526702-cbb68e40-1c67-4694-86e9-a029dfd7e894.png)

### Steps To Reproduce

1. Click on New data source query 
2. Click on "Documentation"
3. Click on any topic other than first topic
4. Observe the topic clicked is not focused in the heading but in the middle

### Version

Release

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1200 |
| Effort (months)  | 1 |
