### ISSUE TITLE
[Bug]: Function  of certain types not runnable in JS Editor

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#15283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Functions, where null coalescing and logical expressions are used together, are not treated as functions in the JS Editor.

### Steps To Reproduce

1. Go to JSObject page
2. Write the following JS Object

```
export default {
testFun: (searchText) => {
		const filterText = searchText ?? (Issue_Form.fieldState?.labels?.filterText || '');
		return Api1.run({ filterText });
	},
}
```
3. See that function is not runnable

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ohansFavour isn't this because it's not marked as async
