### ISSUE TITLE
[Bug]: Entities having the same name when merged into a page take on an inconsistent naming conventions

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When queries and objects have the same name, for example `JSObject1` on Page 1 and Page 2 and this object is moved from one page to another then the entity name is modified to `JSObject11`. Adding entities after this causes naming to being from 11,12,13.... instead.

### Steps To Reproduce

1. Create a query/object (`Query1/JSObject1`) on `Page1` and `Page2` of an app
2. Move the entity from `Page1` to `Page2` - observe the entity name change from `Query1/JSObject1` to `Query11/JSObject11`
3. Add more queries/objects and observe the naming convention does not follow current order.

https://www.loom.com/share/8d609ced4d914ee38a45e08fde8a98f2

### Version

Cloud

**Comment by bharath31** [comment]
Will be handled by #15934
