### ISSUE TITLE
[Bug] Organization is referred to as Workspace in Organization settings

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#1531]
## Description

There is a mismatch in terminology for Organization in the settings page.

### Steps to reproduce the behaviour:
1. Go to the drop down for any organization
2. Click on Organization Settings
3. The label for an organization's name is seen as "Workspace"

<img width="546" alt="Screenshot 2020-11-03 at 2 48 42 PM" src="https://user-images.githubusercontent.com/5298848/97969978-d51c0900-1de6-11eb-95e2-7e24ae22ad4d.png">

**Comment by areyabhishek** [comment]
@mohanarpit As a part of this change, can we stop appending 'personal organization' to new orgs created in Appsmith? Just call it 'XYZ's apps'. Why should we do this? 
1. If you think about it personal organization makes no sense as a noun.
2. The length of the default org name is too long.
