### ISSUE TITLE
[Feature]: Support Websockets

### ISSUE THREAD

**Issue by fresh-ji** [appsmithorg/appsmith#15326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i m a fresh man to appsmith. when i use WebSocket in JSObject, i want to fetch out data from the ws connection, so i tried "storeValue", but it doesn not work. The console said "storeValue is not defined"

so could you provide a way to get the data out from ws message.

thanks!!!

code below:

<img width="331" alt="屏幕截图 2022-07-20 180115" src="https://user-images.githubusercontent.com/25540984/179955417-8c899c40-b77b-4f1c-8685-30c5672fbde9.png">

### Steps To Reproduce

1.exec code blow in JSObject
onToolPageLoad: () => {
		var ws = new WebSocket("ws://10.11.24.117:8081/test")
		ws.onopen = function () {}
		ws.onmessage = (evt) => {
			var j = JSON.parse(evt.data)
			storeValue(("msg1", j.num)    ----->   this is where went wrong
			console.log(j)
		}
	}

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5w3rg)

**Comment by Nikhil-Nandagopal** [comment]
@fresh-ji thanks for reporting this. Currently the platform does not support this but we'll take this up as a feature request

**Comment by tomjose92** [comment]
@fresh-ji , we had recently introduced an article that shows how to connect the Websockets using JSObjects (javascripts and native Websocket initialisation).
And via Mutations we have a way to retrieve the response coming from the sockets. You can check it out here below
https://community.appsmith.com/tutorial/integrating-websockets-appsmith
