### ISSUE TITLE
[Feature]: As a user I want to know what changes have been made when we say "Some changes are platform upgrades from Appsmith"

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a user I want to know what changes have been made when we say "Some changes are platform upgrades from Appsmith"

```
{
    "responseMeta": {
        "status": 200,
        "success": true
    },
    "data": {
        "modified": [
            "metadata.json"
        ],
        "added": [],
        "removed": [],
        "conflicting": [],
        "isClean": false,
        "modifiedPages": 0,
        "modifiedQueries": 0,
        "modifiedJSObjects": 0,
        "modifiedDatasources": 0,
        "aheadCount": 0,
        "behindCount": 0,
        "remoteBranch": "refs/remotes/origin/master",
        "discardDocUrl": "https://docs.appsmith.com/core-concepts/version-control-with-git/pull-and-sync#discard-and-pull-changes"
    }
}
```
<img width="525" alt="Screenshot 2022-07-20 at 11 45 39 AM" src="https://user-images.githubusercontent.com/45958978/179910777-36cf9c70-7ece-41df-9d55-3b9a768b32c5.png">
<img width="540" alt="Screenshot 2022-07-20 at 11 45 58 AM" src="https://user-images.githubusercontent.com/45958978/179910800-edfbe478-b004-470a-b02a-8fd3abac2076.png">

### Why should this be worked on?

It gives user correct info

**Comment by infinitetrooper** [comment]
Solving with #24668
