### ISSUE TITLE
[Bug]: No visual demarcation on 'add' menu of the entity explorer

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currenrtly, we don't demarcate between new query creation, datasources used and all datasources on the quick add option of the entity explorer. This makes it visually confusing to find 

### Steps To Reproduce

1. Click on + icon on the Queries/JS section of the entity explorer of an app that's got queries - observe there are 3 different sections in there but no demarcation of where the sections end and where the next begins

![image](https://user-images.githubusercontent.com/79509062/179998241-cb061890-febf-4155-9b60-4c07d7801fbd.png)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami actually there are no sections here. All the items are meant to create a query against a datasource or a new blank one. This should not generally be a problem for our users since their number of data sources wouldn't exceed 2 - 3
