### ISSUE TITLE
[Task]: Misfiring WIDGET_DRAG analytics event

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#15345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The `WIDGET_DRAG` frontend analytics event has no data collected for the past 30 days and has hardly any for the last 6 months. Needs to be looked at.

**Comment by aswathkk** [comment]
@yaldram In #5389, I think we replaced `WIDGET_DRAG` with `WIDGET_CARD_DRAG`. Please do confirm it though.

**Comment by vuiets** [comment]
`WIDGET_CARD_DRAG` is for widget drags from entitiy explorer to the canvas? Can we have `WIDGET_DRAG`for canvas drag and drop with the same properties of `WIDGET_DRAG`, performance hits considered?
