### ISSUE TITLE
[Feat]:There is no option to push committed changes after git push fails

### ISSUE THREAD

**Issue by vishnu-gp** [appsmithorg/appsmith#15349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When for some reason git push fails, Appsmith commits the changes but there is no option to push those commits and deploy the app in the next try unless the user makes another change in the app then commit and push.

![Screenshot 2022-07-15 at 12 44 32](https://user-images.githubusercontent.com/9128194/180147804-c53f0b25-6902-498b-96b0-ddbf49e5e4c4.png)

The expected behaviour should be either adding a push feature for already committed changes or discarding the commits that happened while a push fails after the failure.

https://www.loom.com/share/9b3f7d3f4cc3421da0fb8985ea825832

### Steps To Reproduce

1. Create an application and connect it to git
2. Mark the branch as protected on GitHub
3. Make some changes in the app and try to push
4. After the push fails close and reopen the modal
https://www.loom.com/share/9b3f7d3f4cc3421da0fb8985ea825832

### Version

1.7.8

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 90 |
| Effort (months)  | 0.25 |


Estimating that 10% of the Git users making a commit will run into a push failure here: 90

**Comment by ginilpg** [comment]
Can we effectively handle this error in UI? To some extent, this problem can be resolved by providing a proper error message to the user. @brayn003 @infinitetrooper

**Comment by RoopKrrish9696** [comment]
Handled with native git connection
