### ISSUE TITLE
[Task]: Separate fetchAllApplications and  release notes API

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#15346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two observations here
1. Api to `fetchAllApplications` which has URL https://app.appsmith.com/api/v1/applications/new is called twice
Reason i am guessing is most probably
- once to fetch all application and
- once to fetch release notes
2. Can we please have a separate API for release notes with pagination which should only trigger when user click on release notes UI 

Each release’s version description has around 13kb data and total data fetched is around ~560kb.

<img width="1214" alt="Screenshot 2022-07-19 at 3 40 27 PM" src="https://user-images.githubusercontent.com/23132741/180145477-04d31fe6-d294-401f-b183-dc35e3324cd1.png">
<img width="933" alt="Screenshot 2022-07-19 at 3 40 50 PM" src="https://user-images.githubusercontent.com/23132741/180145488-b777e0c3-e786-4ac1-9aff-cc030670b9d7.png">

### Steps To Reproduce

1. Open browser devtool
2. Go to https://app.appsmith.com/api/v1/applications/new and notice network calls

### Version

1.7.9

**Comment by somangshu** [comment]
@hiteshjoshi can this be prioritised, if not this quarter, let me know, ill push it out.
Since is approx 1MB of data transfer that can be reduced by half, if its a low hanging fruit we should try and cover this

**Comment by vivonk** [comment]
Sure @hiteshjoshi , I will do take a look at this. Thanks!

**Comment by somangshu** [comment]
@vivonk is this something you are picking up? If so, I would like to add it to the perf sprint in order to be able to to track its progress easily. LMK

**Comment by vivonk** [comment]
Yes @somangshu , I will pick this up in next week along with some other tasks.

**Comment by vivonk** [comment]
@somangshu @hiteshjoshi I have gone through this task. I will be helping on creating a separate API for version release information but similar changes on frontend will be required. 
Can I get help on frontend side for making similar changes?

On frontend, it would be to handle `/new` API's response without `releaseItems` and releaseItems data will be available on a separate API.

**Comment by somangshu** [comment]
@Rhitottam will you be able to help us here?

**Comment by Rhitottam** [comment]
Hi @somangshu Sure i will work on this.
