### ISSUE TITLE
[Feature]: An `appsmithctl version` command to print details of currently running Appsmith instannce

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#15375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, to know the version of Appsmith running, we have to open the UI and check it out. It'd be nice to know the version from the CLI, with a command like `appsmithctl version` or something. Some example outputs:

```
Appsmith Community Edition version 1.7.9
Release Notes at https://github.com/appsmithorg/appsmith/releases/tag/v1.7.9
```

```
Appsmith Business Edition version 1.7.9
Release Notes only available inside Appsmith UI
Licensed to Agent Smith, expires on 2022-12-31
```

### Why should this be worked on?

This can be a simple way to ask users to share the output of, when troubleshooting. Instead of _what have you configured_, we can start asking, _what's actually running_, which is what we're interested in, more often than not.

**Comment by nidhi-nair** [comment]
Such a nice quality of life feature! :)
