### ISSUE TITLE
[Bug] The table crashes when inside a form and it resets

### ISSUE THREAD

**Issue by tluyben** [appsmithorg/appsmith#1537]
## Description

- Drag a form
- Drag a table inside it
- Create a query to fetch users from the mock db
- Connect the query to the table
- Click the form submit button
- The table crashes and shows an error

**Comment by Nikhil-Nandagopal** [comment]
@tluyben could you share an image of the property pane of the widget that is showing this?

**Comment by tluyben** [comment]
Already discussed in Discord, but the issue goes away when the submit button has 'reset form on success' set to off/false. 

And to fix my description a bit more ; the table is *on* the form which I forgot to mention (or rather thought was not relevant).
