### ISSUE TITLE
[Feature]: support appsmith.URL.pageHash

### ISSUE THREAD

**Issue by unknown1337** [appsmithorg/appsmith#15394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For some functionality it's usefull to be able to acquire not only the page URL&path but the hash. E.g. if in a script you want to do something independent of a pageName.

Proposal:
ex. current page is login-62bb0af020ae3225cefdddfa
then appsmith.URL.pageHash returns  62bb0af020ae3225cefdddfa

### Why should this be worked on?

see above, ease of scripting (no custom regex)

**Comment by IAmAnubhavSaini** [comment]
`62bb0af020ae3225cefdddfa` is the id (in the database) of the page named `login`. The current page slug in url is built from `${pageName}-${pageId}`. The page id belongs to each page and is different. 

There is nothing that you can do independently with the page id. If you are looking for the pageids in an application, please look at the response of the api: `/api/v1/pages?pageId={defaultPageId}&mode=EDIT`

**Comment by Nikhil-Nandagopal** [comment]
@IAmAnubhavSaini why was this re-opened?

**Comment by IAmAnubhavSaini** [comment]
I don't know if there is any potential here for a new feature.

I closed it as a bug, but then realised may be users want some scriptability with page/IDs.

**Comment by josiah-roberts** [comment]
I'm having an issue where `{{ appsmith.URL.hash }}` does not update when the hash changes; only when the page is reloaded.

**Comment by thanhloc1993** [comment]
> I'm having an issue where `{{ appsmith.URL.hash }}` does not update when the hash changes; only when the page is reloaded.

I have a similar issue
