### ISSUE TITLE
[Bug]: navigateTo("pageName") doesn't persist query params (except embed)

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#15390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A follow up on #11422.

When calling `navigateTo("pageName")`.
All existing query params (expect `embed`) are removed upon navigation.

So, if you have `?embed=true&abc=xyz` only the `embed` parameter will persist.

### Steps To Reproduce

https://app.appsmith.com/app/pass-params-issue/home-62da698da7d0d33f843da27f

Video shared by user: https://www.loom.com/share/a9880a50be244b9d87f8739cae7c3286

### Version

Cloud - Appsmith v1.7.9-SNAPSHOT

**Comment by eco-monk** [comment]
We intentionally persist only `branch` and `embed` parameters upon navigation.
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/entities/URLRedirect/URLAssembly.ts#:~:text=//%20not%20persisting%20the,%3D%20existingParams%3B

Looking at why we do this.

**Comment by eco-monk** [comment]
This seems to be the case even a few months before at `1.6.10`.
https://github.com/appsmithorg/appsmith/blob/v1.6.10/app/client/src/constants/routes.ts#:~:text=//%20not%20persisting%20the,as%20any%3B

I suppose, This should be a feature request/enhancement and needs some thought before proceeding.
We should not break existing behaviours of apps, that rely on navigateTo.

cc: @kocharrahul7

**Comment by Nikhil-Nandagopal** [comment]
This isn't a bug. If the user wants to persist the param, they should send it in the navigate to function again
