### ISSUE TITLE
[Feature]: Add dataChange event in table widget V2

### ISSUE THREAD

**Issue by mdmozibur** [appsmithorg/appsmith#15397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When an editable cell's data is edited, there should an event after the edit is finished (could be enter button press or unfocus).
 

### Why should this be worked on?

This is a required customization feature in editable tables. Otherwise the appeal of editable table will not be that good.

**Comment by dilippitchika** [comment]
Hey @mdmozibur you can do it using 3 ways - 
1. You can trigger a query when a row is updated and the save button in a row is clicked
2. You can configure onSubmit event in a column which is like onDataChange at a column
3. You can configure a button outside the table which can be used to save changes to the table
You can check this document - https://docs.appsmith.com/widget-reference/table/inline-editing
Or this app to learn more on how to use and configure it - https://app.appsmith.com/app/editable-table/row-save-62d8f8d0e1c2ed505a0557cc

If you have already checked our docs, Can you explain why you need onDataChange? Which database are you working with?

**Comment by dilippitchika** [comment]
Closing this issue, will reopen if there's more info from @mdmozibur on this.
