### ISSUE TITLE
[Bug]: Linting is not reactive when path is incorrect

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#15407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

See loom recording [here](https://www.loom.com/share/610c4432407548d29ba19107eb0192fc)

### Steps To Reproduce

1 Drag a button widget
2. Create an entity (Api, Query or JSObject)
3. In any field, add an incorrect path eg. `entityname.tetete`
4. Delete entity, and see that linting doesn't get updated

### Version

Cloud

**Comment by ohansFavour** [comment]
Cause of issue

When we `extractReferencesFromBinding`, we do not add subpath top-level entities, except they are explicitly referenced (to prevent unnecessary evaluations and performance dip).

so, for binding `{{Api1.data.unknownProperty}}`, extracted reference is `Api.data`. However, for `{{Api1.unknownProperty}}` no reference is extracted because Api1.unknownProperty isn't present in the data tree and top-level subpath entities are not added as references except explicitly referenced (eg. for binding `{{Table1}}`, extracted reference is `Table1` ).

Different explored solutions

1. Add subpath top-level entities if present in the dataTree. For `{{Api1.unknownProperty}}`, add Api1 as a reference.

Cons

a. Leads to unnecessary evaluations.
b. Might increase the chances of a cyclic dependency in the application.

2. Create a data structure that stores a list of all extracted identifiers from bindings throughout the application.

Cons
a. As an application grows, the number of extracted identifiers grows much faster than the number of entities present in the App, manipulating the data structure might get very expensive.

**Comment by Rishabh-Rathod** [comment]
> a. As an application grows, the number of extracted identifiers grows much faster than the number of entities present in the App, manipulating the data structure might get very expensive.

@ohansFavour Do we need to store list of all extracted identifiers? or only those which are not active?

Currently, our `dependencyMap` already stores all active extracted identifiers, we could just create a store for non-active references. correct?

Also, can you help me understand how we maintained this value ( data structure of variable to store extracted references )?

**Comment by ohansFavour** [comment]
@Rishabh-Rathod Apparently, the way we currently extract identifiers from code has some abnormalities hence invalid identifiers are getting added, resulting in a large number of extracted identifiers. I have already started working on that [here ](https://github.com/appsmithorg/appsmith/pull/16171). This should reduce the number of untracked identifiers which is then stored in a "dependencyMap" type object.
