### ISSUE TITLE
[Bug]-[4000]:Onboarding visual distraction from the entity explorer being hidden

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#15409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Entity explorer is visible when the user starts the onboarding, and remains visible till the cursor is moved

The immediate movement causes a great distraction, and the user immediately scans to the entity explorer, rather than looking at the instructions, or the run button

https://user-images.githubusercontent.com/20532920/180756972-c3d06619-2e9f-435d-9edc-05d8a8a5662a.mov

### Steps To Reproduce

1. Start the onbaording
2. click on Start building
3. observe

### Version

v1.7.9 Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4000 |
| Effort (months)  | 0.5|

**Comment by Richarex** [comment]
This issue is fixed now, closing it.

https://user-images.githubusercontent.com/93259714/181729547-4e57aa66-6f93-4412-baea-a9583c6bd35f.mp4
