### ISSUE TITLE
[Bug]: Inaccurate error messages for Airtable integration errors

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#15404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there is an error in the syntax of a query/any other error; the error message is a gibberish and does not help the user with any information on how to solve the error. 
![image](https://user-images.githubusercontent.com/55969597/180659747-96fba1ad-d9dc-4338-b4b7-ae7481f3931f.png)
![image](https://user-images.githubusercontent.com/55969597/180659751-d54d7fad-da9d-4996-9698-8a2dcbbde942.png)
![image](https://user-images.githubusercontent.com/55969597/180659762-5a27aa1f-9d81-47cc-a41b-2781a85ab2b2.png)

### Steps To Reproduce

1. Create a new app with Airtable connected as a datasource
2. Write a "create record" query with a syntax error, for eg: missing a pair of { } in the query
3. Run the query, the gibberish shows up as an error message

### Version

Cloud - 1.7.9

**Comment by rohan-arthur** [comment]
not our focus for the foreseeable future, will get around to this at a later time.

**Comment by sumitsum** [comment]
@rohan-arthur instead of closing these issues shouldn't we put them into icebox ?
