### ISSUE TITLE
[Feature]: Allow users to add custom fonts for their theme

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#15416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The user wants to enhance their theme with custom fonts. This can be done in two ways - 1. web fonts from google or similar service 2. Uploading TTF files

### Why should this be worked on?

A user on the intercom reached out to ask for this feature.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7540c)

**Comment by pranavkanade** [comment]
Intercom OP - [link](https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100150007)

**Comment by ramsaptami** [comment]
Will be worked on here: https://github.com/appsmithorg/appsmith/issues/20365
