### ISSUE TITLE
[Bug]: Search returns unrelated options in the Entity Explorer

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If we search for widgets in the entity explorer, the search returns unrelated options as well.

<img width="197" alt="Screenshot 2022-07-25 at 12 04 07 PM" src="https://user-images.githubusercontent.com/39921438/180725162-ce433b49-0876-4840-92f8-916ee0876f96.png">
<img width="198" alt="Screenshot 2022-07-25 at 12 04 22 PM" src="https://user-images.githubusercontent.com/39921438/180725188-cf55f12c-13a4-4513-816a-03fa8e216606.png">

### Steps To Reproduce

1. Go to the Entity explorer.
2. Search for any widget.

**Expected:** Only widgets related to the search keyword should be displayed.

### Version

Cloud

**Comment by dilippitchika** [comment]
@rohitagarwal88 @prsidhu we can't keep doing this, as it's not helping to solve for spelling mistakes. It's creating more issues. Should we skip any fuzzy matching for now and only do perfect match?

**Comment by rohan-arthur** [comment]
not reproducible anymore, maybe got fixed with another issue
