### ISSUE TITLE
[Bug]-[1000]:Renaming a query/object from the entity explorer causes context switch from current tab to the renamed query/object

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Renaming a widget or datasource from the entity explorer, simply changes the name whereas, changing the name of a query or a JS object from the entity explorer causes the active tab to change from current page to the renamed entity.

Context should only switch when users select the query/object and not when they are simply choosing to rename the entity from the explorer. This is because when a user is on the canvas or the editor and is in the middle of writing code, and wants to rename a few queries/objects, the intention is to simply rename the entities and continue wherever the user is on the current tab. Not switch to the query and navigate back to where the user was.

### Steps To Reproduce

1. Add widgets, queries and objects to an app
2. Rename a query/object from the entity explorer when present on the canvas - observe that on successfully renaming the query/object, context is switched from canvas to the query
3. Rename a widget/datasource from the entity explorer when present on the canvas - observe that on successfully renaming the widget/datasource, context does not move away from the current content

https://www.loom.com/share/d717a0c1a6c84e5983b6a4493fcd39ed

### Version

cl

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 0.5 |

**Comment by kocharrahul7** [comment]
With the new segmented control, this no longer happens
