### ISSUE TITLE
[Bug]-[350]:Random keystrokes trigger autocomplete to show up

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When code on the editor has already been indented, using keyboard board shortcut causes the autocomplete pop-up to open up wherever the cursor is present
2. Pasting a code snippet triggers autocomplete to show up
3. Pressing CTRL + any character shows autocomplete 

### Steps To Reproduce

1. Use the following code in the editor and prettify the code from the settings
```
export default {
	transformAPI: () => {
		const users =  fetchUsers.data.forEach((user) => {
			user.dob = moment(user.dob).format('Do MMM YYYY');
			return user;
		})
		return users
	}
}
```
2. Prettify from the drop-down options present on the top right
3. Now use keyboard shortcut again and observe that the autocomplete pop-up opens up as seen in the video

https://www.loom.com/share/9c22f3e3dd944a8cad11748e2cd1fe31

### Version

Cloud

**Comment by bharath31** [comment]
assuming 5% of autocomplete users face this 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 350 |
| Effort (months)  | 0.5 |
