### ISSUE TITLE
[Bug] Cursor changes to text on hovering on 'App name'

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1543]
## Description

See loom video:
https://www.loom.com/share/6c3f960ed88a45beb6737c14eb6ca450

@Debsourabh: 
1. The app name doesn't look editable just like in the property pane. 
2. The app name looks totally different in the deploy mode vs the edit mode.
<img width="185" alt="Screen Shot 2020-11-03 at 11 47 15 PM" src="https://user-images.githubusercontent.com/30255708/98024884-f9033d00-1e2e-11eb-858f-56d30245e6e3.png">
<img width="130" alt="Screen Shot 2020-11-03 at 11 47 23 PM" src="https://user-images.githubusercontent.com/30255708/98024888-facd0080-1e2e-11eb-9187-951437e4ab45.png">

Can you design the navbar so that when the developer switches between the edit mode and deployed mode, the app name, Appsmith logo look consistent? Today the position of the app name and Appsmith logo changes slightly and it doesn't look good. See loom video here: https://www.loom.com/share/7b0fe02528644ddda709bbde748da1bb

**Comment by Nikhil-Nandagopal** [comment]
https://www.figma.com/file/51WpTmpdZAz3WI6UNwCOC2/New-App-Creation-Flow?node-id=5%3A422
