### ISSUE TITLE
[Bug]: Connect to git modal does not allow valid ssh urls

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#15432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Open the app and click on connect to git. Add the ssh url - `git@gitlab-abcd.test.org:org__org/repoName.git`.

### Steps To Reproduce

Open the app and click on connect to git. 
Add the ssh url - `git@gitlab-abcd.test.org:org__org/repoName.git`
Notice the FE throws an error saying invalid ssh url.
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/12005551/180784510-e3e2976a-4001-44ec-ace7-19d251a73933.png">

### Public Sample App

Any app

### Version

Latest

**Comment by AnaghHegde** [comment]
@vuiets Can we also update the placeholder for the input box? It says url begins with ssh:// but that will result in error state as jgit does not support that.

**Comment by mohanarpit** [comment]
@AnaghHegde Does the server consider the given input ( `git@gitlab-abcd.test.org:org__org/repoName.git` ) to be a valid or does the server also reject it as invalid?

**Comment by AnaghHegde** [comment]
@mohanarpit Server has validation as well. This needs change in both BE and CE validation.

**Comment by vuiets** [comment]
@AnaghHegde we could go with this
> Enter the SSH URL of your git repo

**Comment by AnaghHegde** [comment]
@vuiets This looks good to me. And can you please set the priority, i am not sure if i have added the right one.
