### ISSUE TITLE
[Feature]: Decouple the pages list from the topbar so users can hide just one

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#15443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

At the moment, users can either show the entire topbar (app title, edit, share, pages list etc.) or none of it

We should decouple the page list ( red box in screenshot) with the titlebar (black box in screenshot), allowing users to navigate across pages if they should chose to do so while the app is embeded.

We should add a URL parameter to enable the user to do this

<img width="1440" alt="Screenshot 2022-07-22 at 7 27 31 PM" src="https://user-images.githubusercontent.com/20532920/180928269-50c15957-5b2c-4c2a-8c59-673bb93d9032.png">

### Why should this be worked on?

This seems like a logical next step, and an improvement in the user experience for the developers who would like to develop apps, as well as the app viewers.

Rather than forcing users to add CTAs or navbars in their apps, it would be much easier to have the existing navbar/page list visible

**Comment by Nikhil-Nandagopal** [comment]
Not useful so closing
