### ISSUE TITLE
[Bug]: Google Sheets - Issue with a column that has different data types

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#15444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If a column in Google sheets has different data types, for eg; Numbers and Text, only one of them is fetched in the data and the other returns empty values.

<img width="911" alt="Screenshot 2022-07-26 at 10 45 20" src="https://user-images.githubusercontent.com/32227135/180928860-2cde846c-7b79-46c6-8873-d3fa0b203a57.png">
<img width="1246" alt="Screenshot 2022-07-26 at 10 46 36" src="https://user-images.githubusercontent.com/32227135/180928867-3e757d01-fa96-42ad-9174-6e92448d3bb8.png">
<img width="860" alt="Screenshot 2022-07-26 at 10 47 28" src="https://user-images.githubusercontent.com/32227135/180928944-df535e6a-4c2e-48bf-b6f8-525058570d2e.png">

### Steps To Reproduce

1. In a column on Google Sheets, add both numbers and text
2. Fetch the data on Appsmith and view the response
3. You will see values in certain objects missing

### Version

v1.7.9

**Comment by o2lkd** [comment]
I'm facing the same issue as well, hoping for a fix soon.
