### ISSUE TITLE
[Bug]-[1016]:When all the header options are turned off scrollbars in a table dissapear

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i turn off all the options in header in a table, the scrollbars within the table dissapear

### Steps To Reproduce

1. Add a table
2. Make it scrollable by resizing horizontally and vertically
3. Hide the search, pagination, filter and download from the property pane
4. Observe that the scrollbars dissapear

### Version

Production

**Comment by dilippitchika** [comment]
@souma-ghosh will the fixed in the recent change we did for scrollbars in table?

**Comment by souma-ghosh** [comment]
> @souma-ghosh will the fixed in the recent change we did for scrollbars in table?

No, we need to work on this separately @dilippitchika

**Comment by dilippitchika** [comment]
@Ravina-Deogadkar  this can be picked up. Please let me know if you are interested

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by thedreader** [comment]
Hi, I would love to work on this issue. Could you assign it to me?

**Comment by dilippitchika** [comment]
Greetings @thedreader  thanks for showing interest 🎉 , Please go ahead and create a PR. I will assign this to you and @Ravina-Deogadkar. If any of you can contribute to this, it would be great.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by Ravina-Deogadkar** [comment]
Thanks for assigning

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1016 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@keyurparalkar can you check this issue once, since you changed the scrollbar recently

**Comment by keyurparalkar** [comment]
This behaviour should also be present in the column freeze feature. https://github.com/appsmithorg/appsmith/issues/15448

**Comment by dilippitchika** [comment]
Fixed in column freeze pr
