### ISSUE TITLE
[Bug]-[2000]:Reconnect database modal does not show up when forking a template, but it does show up when importing the same app as a JSON

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#15463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app (with sharing disabled) is JSON imported to a new organization (which does not use the same data source as in the app that you're importing), the SaaS connector shows up like in the picture attached below
![image](https://user-images.githubusercontent.com/55969597/181019303-fb1cabbe-1f07-4f12-ad7b-ad4420949669.png)

But, when we publish a template on the platform (also with disabled sharing), on forking - the SaaS connector does not show up and the template gets forked without asking for the user's data source credentials.

### Steps To Reproduce

1. Create a new app
2. Add in a data source in the app
3. Deploy and Disable share for the app
4. Export the app into a JSON
5. Import the JSON in a brand new organization
6. The SaaS connector shows up asking for the missing data source's credentials
7. Fork this template (sharing has been disabled for this) in a new organization
8. The template forks without the SaaS connector asking for the creds of the missing datasources

[Link to screen recording](https://www.loom.com/share/8485ca94bdb548d4aeaab2a3f2886952)
First part shows JSON import into a new org and then forking a template into a new org

### Version

Cloud - 1.7.9

**Comment by akash-codemonk** [comment]
If I am not wrong the expectation here is to ask for credentials while forking a template. I think for forking templates the datasource credentials are exported with it which removes the need for adding credentials. I am guessing we want to add templates where we do not want to add credentials for which there is no implementation for this currently. Found a slack thread for the same https://theappsmith.slack.com/archives/CGBPVEJ5C/p1648186861969569

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | 0.5 |

**Comment by akash-codemonk** [comment]
https://user-images.githubusercontent.com/67054171/182368698-53de623d-4f9d-4035-a47b-52e205619d89.mov

No deploy preview as both backend and frontend changes need to get merged together to release.

**Comment by Richarex** [comment]
This issue is fixed now, closing it.
