### ISSUE TITLE
[Bug]: Linting Error when using crypto

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#15469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The debugger shows a parsing error when using `crypto`. The function works fine and returns everything as expected apart from that error received in the debugger.

![image](https://user-images.githubusercontent.com/101268423/181062693-56befe8e-79dd-486a-9bb0-d4f1835d1fde.png)

![image](https://user-images.githubusercontent.com/101268423/181062786-c0a9b6d4-ef8a-4630-b9b5-3962b1e74ada.png)

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100150477#part_id=initial-part-164629100150477-1383308119

### Steps To Reproduce

Create a function inside a JS Object and use the crypto method.

### Version

Cloud

**Comment by unknown1337** [comment]
Thanks for filing!
