### ISSUE TITLE
[Bug]: TreeSelect | Unable to capture right Label data OnPageLoad (first load)

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#15466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="689" alt="Screenshot 2022-07-26 at 8 46 28 PM" src="https://user-images.githubusercontent.com/91450662/181044677-88a207e9-bd3d-4536-bd86-fb2af9ebf416.png">
<img width="1221" alt="Screenshot 2022-08-29 at 5 07 07 PM" src="https://user-images.githubusercontent.com/91450662/187192653-8383edca-5e9e-4ac3-b934-ec60ea118fc7.png">

### Steps To Reproduce

1. Dragdrop Tree select widget/MultiTree & map for the selected options display
2. Observe the selected option value & label data
3. **While the label data is Blue - the data captured is only "B" - can be seen in screenshot - TreeSelect**
4. **While the label data is Green - the data captured is "GREEN" - which is option value - MultiTreeSelect**
5. Now change the selected valued in Tree Select & observe right data is captured
6. **Expected - The right Label (and Value) data should be available (at all times and) during first load also**

### Version

Prod/Release v1.7.10

**Comment by shadabbuchh** [comment]
This issue is still prevalent on `Release` hence reopening it.
https://www.loom.com/share/b82061c625904198a7292c7dd890a42a

**Comment by Tooluloope** [comment]
Fixed already, in #16401
