### ISSUE TITLE
[Bug]-[5000]:Entity explorer pop-up behaviour is incorrect when scrolling through on the explorer

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the hamburger icon is clicked next to a query/widget and a datasource is expanded to display all it's tables as seen in the video then scrolling on the entity explorer causes the pop-up to scroll with the explorer and sometimes add an unnecessary scroll on the canvas

### Steps To Reproduce

1. Click on the hamburger icon next to a mongo query
2. Expand it's datasource so you can see all it's tables
3. Now scroll in both directions on the entity explorer and observe that the pop-over persists on screen and it's behaviour is incorrect in both directions as seen in the video (moving upward causes pop-over to colliade with pages and other irrelevant entities on the explorer and moving downward causes an extra scroll to appear)

https://www.loom.com/share/81ae4909ad304ec4a5928ad837e298af

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5000 |
| Effort (months)  | 0.5|

**Comment by akash-codemonk** [comment]
Hiding the menu on scroll should fix this.

https://user-images.githubusercontent.com/67054171/182079137-472a16ab-f14d-419b-a251-550bb237976d.mov


https://appsmith-56xsan47i-get-appsmith.vercel.app/
