### ISSUE TITLE
[Bug]: Only the first list item resets with the resetWidget function

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#15487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user is performing bulk uploads using the list widget; after he submits the form, he wants to reset his input widgets on the list items. He used the `resetWidget` function and passed the `List1` widget with `children: true`, but it does not work.

Link: https://community.appsmith.com/t/resetting-a-list-in-a-modal/1230/2

### Steps To Reproduce

1. Drag and drop a list widget
2. Add a couple of input widgets to the first list item
3. Add a button and set the `onClick` to `resetWiget` - `{{resetWidget("List1",true)}}`
4. Write some dummy text on the input widgets
5. Click the button to reset the list
6. Only the data on the first list items resets

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5zax8)

**Comment by danciaclara** [comment]
Do we have a workaround for this issue? A user asked for it - https://discord.com/channels/725602949748752515/760761686549463060/1006541611615920158

**Comment by dilippitchika** [comment]
Short answer no. I don't know if this is something we can fix in the time being. @Tooluloope can you check?

**Comment by karthikeyann** [comment]
Input widget in the first item does not get updated on next page in the list. It stays the same as previous page.
