### ISSUE TITLE
[Bug]: Table Widget V2 UpdatedRow Is Always An Empty Object

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#15486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Table1.updatedRow` object never gets updated with the edited information when a row is submitted, saved or discarded. The video below for more details

https://user-images.githubusercontent.com/17744578/181265143-90950c30-bccd-467d-8582-82ae2b271dd6.mp4

### Steps To Reproduce

See the video below

https://user-images.githubusercontent.com/17744578/181265143-90950c30-bccd-467d-8582-82ae2b271dd6.mp4

### Version

Cloud/Appsmith v1.7.9-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika @sbalaji1192 this seems like a very basic bug. How is inline editing working?

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal so we simply reused triggeredRow as updatedRow, it works once you bind something to onclick. We kept this bug open to fix the issue of it not showing up by default

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika ok but that seems like a bug, because if we suddenly realise that the triggered row should have the original values and not the edited values, we won't be able to migrate users who used this method. Can we fix this?

**Comment by dilippitchika** [comment]
Yeah we are fixing this, that's exactly why we kept this issue open

**Comment by dilippitchika** [comment]
Fix - 
1. updatedRow should be available as soon as a user updates a table cell. Not edits, but updates.
2. updatedRow when the mode is set to custom should show data of the most recent row which is updated.

**Comment by cokoghenun** [comment]
Thanks for working on this @keyurparalkar 🙏
