### ISSUE TITLE
[Bug]: Drag and Drop Action in Firefox (not in another window onto that tab) returns a "Server not Found "  Error 

### ISSUE THREAD

**Issue by AthiraVijayan21** [appsmithorg/appsmith#15483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I Drag and Drop a text in my application opens in  Firefox (not in another window onto that tab) returns a "Server not Found "  Error .

### Steps To Reproduce

1.Open appsmith application in Firefox
2.Drag any text  in the deployed version of your app. It will opens a new tab and server not found error is showing.

### Version

Self Hosted

**Comment by dilippitchika** [comment]
Duplicate of #14506 @AthiraVijayan21 please add more details in the same issue, i don't think these are 2 different issues. Just a consequence of firefox supporting drag and drop
