### ISSUE TITLE
[Bug]-[800]:Property bindings show undefined on the Entity Explorer

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#15482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bindings for derived and meta properties in the entity explorer show undefined even though they appear correctly in JS bindings. See the screenshot below which shows the updatedRows property of the Table widget.

<img width="1403" alt="Screenshot 2022-07-27 at 10 19 12" src="https://user-images.githubusercontent.com/32227135/181235930-a50becb3-ba6a-45a0-8465-fdc75903f340.png">

This is also the case for other such properties like isValid / formData / text / selectedOptionValue, etc..

Additional note:
The entity explorer uses the pageReducer and it only subscribes to FETCH_PAGE_DSL_SUCCESS action, whose payload is always the DSL saved in the backend. So meta and derived properties are not considered. Prior to the redesign of the Entity explorer these properties used to show up.

### Steps To Reproduce

1. Drag and drop an input widget and type some data into it.
2. Check the text property binding in the entity explorer
3. It will show undefined
<img width="671" alt="Screenshot 2022-07-27 at 17 04 08" src="https://user-images.githubusercontent.com/32227135/181237090-ecfcd6d0-6bba-4b06-84f2-1740269db71d.png">

### Version

1.7.9

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 800 |
| Effort (months)  | 1|

**Comment by kocharrahul7** [comment]
This has been solved now
