### ISSUE TITLE
[Bug]: Platform changes hint string stays after committing.

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#15495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you have client migration changes, we show a string "Some changes are platform upgrades from Appsmith." as of now, but this stays after committing.

The string should not be visible after successful commit or discard.

### Steps To Reproduce

1. Go to an old app
2. See that you have `Some changes are platform upgrades from Appsmith.` visible.
3. Commit
4. Note that the string stays up.

![Screenshot 2022-07-28 at 10 36 46 AM](https://user-images.githubusercontent.com/1573771/181427194-0829b92a-9229-488b-9017-58085ba2713c.png)

https://user-images.githubusercontent.com/1573771/181427350-f82d1644-c86b-468c-8559-81923a310c65.mov

### Version

Cloud

**Comment by infinitetrooper** [comment]
Stale
