### ISSUE TITLE
[Bug]: JS Editor reloads the entire page when running a function

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#15502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open an app for the first time and execute a sync JS function, the entire page reloads itself. This doesn't happen on subsequent runs. 

### Steps To Reproduce

1. Create a sync JS function with limited logic like `console.log("executed function"); `
2. Execute the function 
3. Reload the app
4. Execute the function again
5. The page will reload again (which it shouldn't)

Please check the attached video https://www.loom.com/share/f8bf34f90f7241ad8ec82cbcb09d37d3

### Version

Cloud v1.7.9-SNAPSHOT

**Comment by ohansFavour** [comment]
This issue is easily reproducible in the Firefox browser.
