### ISSUE TITLE
[Bug]: Debugger does not log errors

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Js object in parse error state does not log errors on the debugger.

### Steps To Reproduce

1. Go to the app at [this](https://release.app.appsmith.com/app/automation-test-cases/page1-62e25a5905ac9048e7e548d3/edit/jsObjects/62e25a64dda365410919a239?editName=true) location since it's hard to reproduce this on other apps/pages
2. Run the function and observe the parse error on debugger
3. Click on Debug button or navigate to the Errors tab and observe there are no errors logged

### Public Sample App

https://release.app.appsmith.com/app/automation-test-cases/page-3-62d6486f600c9c6f0b73b67e/edit/jsObjects/62e0f79bdf8b96353259e008

### Version

Cloud

**Comment by ohansFavour** [comment]
@ramsaptami the link you shared doesn't link to a valid JSObject.

**Comment by ramsaptami** [comment]
Hey @ohansFavour, could you please try [this](https://release.app.appsmith.com/app/automation-test-cases/page-3-62d6486f600c9c6f0b73b67e/edit/jsObjects/62e0f79bdf8b96353259e008) link?

**Comment by ohansFavour** [comment]
@ramsaptami, there is an error in the debugger for the link you shared.

<img width="1280" alt="Screenshot 2022-08-16 at 19 54 28" src="https://user-images.githubusercontent.com/46670083/184958862-9395fe02-0789-4cdb-aab7-f7f247ff9272.png">

**Comment by ramsaptami** [comment]
Seems to be working now, so closing the issue.
