### ISSUE TITLE
[Bug]: Dynamic height issues observed in checkbox widget on DP

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#15509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Scenario -1

1) Drag and drop a check box widget
2) Select Height as "Auto Height"
3) Enter some text in the Label of the checkbox widget with few lines to view the Auto height function
4) Select "On check change" event, and choose "Open Modal" or "Navigate to" and select a "Modal" or "url" to any existing page.
5) Now try to delete some lines in the Label of the checkbox widget
6) Observe Auto height function doesn't work

![image](https://user-images.githubusercontent.com/104895602/181494816-1fb93071-037d-4e8d-8377-559aaa0746c0.png)

- [x] Scenario - 2

1) Drag and drop a Checkbox widget
2) Select Height as Auto height with limits
3) Slide the Min and Max rows to 4
4) Observe the widget height is not moved to 4 rows

![image (8)](https://user-images.githubusercontent.com/104895602/181495726-c03cc677-f2a4-43ed-89d4-79c4e98f79ed.png)

**Comment by ankurrsinghal** [comment]
It's blowing up in the `dynamicHeightSagas` giving `TypeError: Cannot read properties of undefined (reading 'bottomRow') line 457`. It's because `dynamicHeightLayoutTree` does not have that widget id (see screenshot
<img width="531" alt="Screenshot 2022-08-16 at 8 01 11 PM" src="https://user-images.githubusercontent.com/17961105/184906021-310176d5-af8c-416a-8c61-335c8f75df64.png">
).

**Comment by ankurrsinghal** [comment]
And I realized that this, that tree is looking bad, breaking everytime for every new widget added with `Auto Height`.

**Comment by ankurrsinghal** [comment]
@Sripriya93 Please find the fix for this issue, here, #16268

**Comment by Sripriya93** [comment]
Scenario - 1 : Working fine

![image](https://user-images.githubusercontent.com/104895602/186611442-238efc76-c4cd-4f27-b287-88edd89c66af.png)
![image](https://user-images.githubusercontent.com/104895602/186611464-8c24d70c-42f1-4826-ae86-582cb2dc9334.png)

Scenario - 2 : Working fine

![image](https://user-images.githubusercontent.com/104895602/186611511-69aa1fd8-4fb7-4984-8092-8347e7b497de.png)
