### ISSUE TITLE
[Bug] On deleting a widget the message is displayed twice

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1551]
Steps to reproduce
1) Add a widget to a canvas
2) Click on Delete from the keyboard 
and observe

Observation
 the delete message is displayed twice to user

![delete](https://user-images.githubusercontent.com/71753653/98086460-cb58db00-1ea4-11eb-8317-6b22f667eb95.png)

**Comment by niyoj** [comment]
Can you assign this issue to me? I would like to contribute in this issue.

**Comment by Rishabh-Rathod** [comment]
Hey👋🏼 @niyoj, thanks for showing interest in this issue.

Unfortunately, this issue is no more valid. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22)

Looking forward to seeing your contributions :)

**Comment by Rishabh-Rathod** [comment]
In the current version, there is no message visible on the deletion of a widget. Hence, closing this issue.
