### ISSUE TITLE
[Bug]: Postgres | Binary | Delay observed in retrieval of data on screen if table column is of bytea type

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#15523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/181697154-e2683b97-33a2-433d-945b-39263b036a95.mov

### Steps To Reproduce

1. Connect to a Postgres ds
2. Create table `CREATE table binarytype (serialid SERIAL primary key, imagename TEXT, existingImage bytea, newImage bytea);`
3. Create a Modal to insert data - `INSERT INTO public."binarytype" ("imagename", "existingimage", "newimage") VALUES ('{{Insertimagename.text}}', '{{Insertimage.files[0].data}}', '{{Insertimage.files[0].data}}');`
4. Insert from UI as shown in video & display the records from Postgress table onto Table Widget
5. **Observe the delay in fetching records**
6. **Same delay is observed during record deletion also**
7. **Expected : Records fetching with any datatype as column should be equally performant!**

### Version

Prod/Release v1.7.10

**Comment by nidhi-nair** [comment]
This might be an issue with data streaming since byte arrays for images would typically be much larger than other data. We'll tackle this when we take up the streaming project.

**Comment by rohan-arthur** [comment]
Fixing this requires a substantial enhancement which we are unlikely to do in the short-to-medium term, hence I am closing this issue.
