### ISSUE TITLE
[Feature]-[780]:Add a series color property in default charts

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a new property for series color in default charts

### Why should this be worked on?

1. We want to reuse theme colors by default on the charts
2. People need to configure custom charts simply because they cannot change the color

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 390 |
| Effort (months)  | 0.25 |

**Comment by dilippitchika** [comment]
1. Add a new property called to chart series below series title, called series color 
2. Bind the first value to color of the theme
3. Bind the second value to a random color or keep it empty for fusion charts to default it to something

**Comment by souma-ghosh** [comment]
@dilippitchika This design for `Series Color` will not apply to pie chart. Since a pie chart will always have a single series and multiple colours. Should we hide this for Pie Chart?

**Comment by alienfacepalm** [comment]
It would be nice to be able to add custom colors. Why not add a color field next to the x/y keys in the series? 

e.g. 
```
[
 {
   "x": "Good",
   "y": 45,
   "color": "#0099ff"
 }, 
   "x": "Bad", 
   "y": "55, 
   "color": "#FFFFFF
]
```

**Comment by dilippitchika** [comment]
Thanks for the request @alienfacepalm, what are you trying to do here? We wanted our users to have access to the color picker to the pick the color.

**Comment by alienfacepalm** [comment]
I'd just like the pie graph to have customized colors for each slice. It would be killer to fit our branding with the colors. Say you want a pie chart with the dominate color of each brand's logo. Right now the way it is it's defaulting to purple and teal and I can't figure out how to change it. It doesn't match anything in our theme.  Thanks man

**Comment by dilippitchika** [comment]
I agree, thanks a lot for the input, i will create a new issue and get it prioritised

**Comment by dalekirkwood** [comment]
Was this ever done?
