### ISSUE TITLE
[Bug]: GraphQL: fix self referencing data path 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#15529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fix self referencing data path for GraphQL plugin.

### Steps To Reproduce

1. Add GraphQL api to table widget. 
2. check that it does not execute on page load. 
3. Check server logs to see that cyclic dependency error is reported.

### Version

self hosted

**Comment by prapullac** [comment]
Not on the release yet

**Comment by prapullac** [comment]
Verified on the DP
