### ISSUE TITLE
[Bug]: Phone widget's value does not retain formatting when value is set from store

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 When phone widget's value is derived from a stored value and this is already formatted, the widget tends to ignore that during display and override formatting to plain text even when formatting is turned off.

### Steps To Reproduce

1. Use [this](https://randomuser.me/api/) API to dynamically display phone numbers on the widget
2. Store the returned `phone` and `cell` values using storeValue function
3. Bind {{appsmith.store.phone}} to display the text and turn off formatting on the property pane of the phone widget
4. Observe the evaluated value of the field on the property pane and the value displayed on the widget

https://www.loom.com/share/219e007895b949b593fe08a9c7ff6fb8

### Version

Cloud

**Comment by somangshu** [comment]
Not reproducible.
