### ISSUE TITLE
[Bug]: The API Auth is broken and display the error as "Access token is malformed"

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The API Auth is broken and display the error as "Access token is malformed"
![image](https://user-images.githubusercontent.com/45958978/181717803-bf03ecc8-65f6-4afd-91b4-b87319e39df0.png)

displays

### Steps To Reproduce

1. Create an authenticated API
2. Now create a new  Post api 
3. Click on run
4. the access token is malformed error is displayed

### Version

production

**Comment by btsgh** [comment]
OAuth2.0 Appsmith setup with Dropbox, Post using https://api.dropboxapi.com/2/files/list_folder this command worked at first,  However, after an hour or two I started getting the malformed error - Error in call to API function "files/list_folder": The given OAuth 2 access token is malformed. There was no OIDC involved in my system in this case

**Comment by sumitsum** [comment]
The following two params were not added to the API datasource config: 
```
response_type=code
token_access_type=offline
```
The API is working as expected post addition of these config. Hence closing the issue. 
Ref: https://theappsmith.slack.com/archives/C02KTH6EHUG/p1659677460093089
