### ISSUE TITLE
[Bug]: Prettifying code on the editor makes it aligned with an arbitrary margin 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Prettifying a piece of code causes a line to get aligned with an arbitrary margin

### Steps To Reproduce

1. Copy paste below code into the editor and prettify it - observe line 11 not aligning itself properly

```
export default {
	dog: async () => {
		setInterval(() => {
			storeValue('imageApi','https://dog.ceo/api/breeds/image/random')
			return storeValue('factsApi', 'https://dog-api.kinduff.com/api/facts') 
				.then(async () => {
				await petImages.run()
				await petFacts.run()
			}).then( () => {
				(petImages.responseMeta.statusCode === '200 OK' ? storeValue('dogImage', petImages.data.message) : appsmith.store.dogImage),
				(petFacts.responseMeta.statusCode === '200 OK' ? storeValue('dogFact', petFacts.data.facts[0]) : appsmith.store.dogFact)
			})
		}, 12000, 'dog')	
	}
}
```

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami the`,` at the end of line 10 is the cause of this behavior and this is expected. Here's [same code](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9gAdKWmAiAcyT1IGcBPKMPABQBKPAF4AfHjoMYjTnBgBJWHGwA3UpQHCxk6YwMxOMHHABqm8nAEByAJYBbUizgBBDHZsAaGwAsYMBicSAD0IcwsAHRgcBAhpB4hAEbYcHAEnCGOznAh2KRQzA42QvSGjKkw5NhQeMamFpRWtmRgRu6eXnh+AUGh4awAtAl2kQDWdoXkxMTREA7xia1GJXhlshuMkTC+CAJcvPw6ElLr5TCkAO6kdvgYCopOLpyR2ORQwmebF9e3ePcwABipDaLzeH1KMkMAF8hNtdh9BCITvpvowBADHjkwXBOFgoPIALIKUiRYykKqcADCECIYlEom6ACYAAwsvAAeQA0jY8AB+OomVKNZo2CJYlzef4PJ64yIECmkhy4zg5ETsBJBBy3XxkoVweWsCVwIReL6GDEKYGg164-FEkl6inkam0uD0xk2Vns7m8gX1YWWaxi1jWmBSgFhl4Ki6RZacADaLIAuuqOBgtTq9aZDSww5DzrCvtCugBGb0srohlglAwyaH0aEgLwgCAYGB2aCcZCgUjYbAQS4ABT7CG7KE01243ZbKRBYwUAGVSMqADKTODIMiUeSz-JgBcwRcYEGTFjIGBvOAtuAOJLpIgEVcFFjkHKAnBOAJn5AgCgmZsQH8BxKAAdV8W47RBOBFzHW47DUW5uF-MBOBnEBJnkXAh3yFgnC3TRdxAAArTg0EXM9KDgABFcgIHgAid2vEAT2wLDfySUh70oQCMGwSYYFAuwCB2ZBS1LABmFs+IgeRQPyDBfz43FVDUTcWwARzo+AcLbcc-04QYoDSR9ANSLS7FSHDnHwpBtyI+RtQvK8W04Si3ACfiknIHTVHXYzGIc9zaPozc7MI5iLiSISRN8ZAmRbS8bkoM8aQcWzUE4ABWQCXTgAAVLjx3s5i1CsZQiFgRcwH49tXEKRcYG4KjArgaFoSAA) on a prettier playground for instance. Notice lines 12 and 15.
