### ISSUE TITLE
[Feature]: Appsmith app should be able to listen to messages sent from the parent webpage

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#15538]
When appsmith is embedded as an iframe, listen to messages from parent window.

JS equivalent -> `window.addEventListener('message', (ev) => {})`.

## Method signature

- Subscriptions to be unsubscribed:
  - On page change, because the callback can have references to entities from that page
  - On app switch/exit, because we want to restrict listening to app's only.

- `subscribeParentMessages`
```
subscribeParentMessages(
	"https://eco-monk.github.io", 
	(message) => { showAlert(message) }
)
```

- `unsubscribeParentMessages`
```
unsubscribeParentMessages("https://eco-monk.github.io")
```

---

Todo:
 - [x] decide on UI (Discussed: this will be handled purely in code for now) @kocharrahul7 @RoopKrrish9696 
 - [x] investigate and handle security concerns (we're good with adding domain checks)
 - [x] handle page switch unsubscribe
 - [x] unsubscribe and subscribe -> params remain the same
 - [x] No action creator -> since it's not a widely used method

**Comment by michaelerobertsjr** [comment]
This seems to be related to Issue#12953 @rimildeyjsr Can you confirm the status of this feature?

**Comment by ericmigi** [comment]
I'd be happy to set up a $200 bounty for this feature, if anyone wants to build it!

**Comment by eco-monk** [comment]
Adding `isParentMessageSuscriptionActive` method had to be handled differently.
This possibly has to be a global method, because the existing ActionTriggers logic doesn't support returning values.
This means subscriptionsMap is to be maintained between main thread and worker thread.
And needs to be kept in sync.

**Comment by wemod123** [comment]
> I'd be happy to set up a $200 bounty for this feature, if anyone wants to build it!
Seems progress of this feature is slow, will you pay that to accelerate? 😂

Actually just want to understand when is feature will be released in estimation

**Comment by yatiac** [comment]
why was this closed as completed? Any indications on how it was implemented? I can see all PR's ended up close because of inactivity (nobody approved them)
