### ISSUE TITLE
[Bug]: Appsmith add an additional success:true field to API response when it is triggered through an event

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#15540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the API is run through a button click, for example, there is a `"success" : true` field that is added to the API response. This is a problem when the user uses the JSON form widget as this field gets added as a switch widget on the form. 
![unknown](https://user-images.githubusercontent.com/32227135/181727559-fe464745-17bd-42a0-a26b-ea8322dafc22.png)

Slack thread [link](https://theappsmith.slack.com/archives/C0341RERY4R/p1659078321039199)

### Steps To Reproduce

1. Create an API
2. Try running it through a button click
3. Check the response for "success" : true field.

### Version

1.7.10

**Comment by ramsaptami** [comment]
We also see this incorrect `success=true` response added to a JS object when onError block of promises is executed
https://www.loom.com/share/6c63b63916fd4226a18ef4486c6d9d95
