### ISSUE TITLE
[Bug]: Mongo plugin: queries are erroring out with message "state should be: server session pool is open"

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#15548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Mongo plugin: queries are erroring out with message "state should be: server session pool is open"
- Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1659076053299979

### Steps To Reproduce

https://theappsmith.slack.com/archives/C0341RERY4R/p1659076053299979

### Version

self hosted, cloud

# Temporary fix
- It may be temporarily fixed by either re-saving the datasource or creating a new datasource and linking the queries against it.

**Comment by RajappaXenon** [comment]
Hi

Any updates on this issue

**Comment by sumitsum** [comment]
@RajappaXenon aplogies, the fix is still not available. We are actively working on it. In the mean time, you may be able to temporarily fix it by either re-saving the datasource or creating a new datasource and linking the queries against it.

**Comment by RajappaXenon** [comment]
Thanks for the quick turnround @sumitsum
