### ISSUE TITLE
[Bug]: Tablet V2 Doesn't Select Row When Clicking on Menu Button

### ISSUE THREAD

**Issue by lukearran** [appsmithorg/appsmith#15551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a Table V2 widget with a Menu Button column, the row is no longer automatically selected after the user clicks on a menu button option. I expect the row to be selected in order to complete an action against the row (e.g update field in row, delete row).

### Steps To Reproduce

1. Create a new application
2. Drag and drop a "Table" widget
3. Add a new column
4. Set the column type to "Menu Button"
5. Add a "Menu Item"
6. Publish the app, and observe the row not being selected after clicking on a menu item.

### Public Sample App

https://app.appsmith.com/app/table-issue-example/page1-62e3f7944003a7259a2f8081

### Version

Self Hosted - 1.7.9

**Comment by Nikhil-Nandagopal** [comment]
@lukearran you can use {{Table1.triggeredRow}} as a property in the meanwhile

**Comment by lukearran** [comment]
> @lukearran you can use {{Table1.triggeredRow}} as a property in the meanwhile

Thanks @Nikhil-Nandagopal

**Comment by zzgvh** [comment]
I don't see this as a bug. If the onRowSelected event handler would trigger when the button was clicked, then there's no way to distinguish between a click on the button and on the table row itself. Selecting the row and clicking the button are two entirely separate events. If you want the row to be selected you should be able to set Default Selected Row in the button event handler.

**Comment by dilippitchika** [comment]
@lukearran in tables, clicking on a button will not select a row. Hence we suggest using the triggered row binding instead.
