### ISSUE TITLE
[Bug]: toString() doesn't convert to string

### ISSUE THREAD

**Issue by jfajardo** [appsmithorg/appsmith#15556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, I have an input text as a password field, but when I put a number this is not converted to a string
`SignUpForm.data.InputPassword.toString()`

![image](https://user-images.githubusercontent.com/4583818/182005187-145ea9db-9927-4175-8bac-513b817879b5.png)

### Steps To Reproduce

1. Add an input field
2. Add an API and inside the body add the value field` {{SignUpForm.data.InputPassword.toString()}}`

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@jfajardo you can solve this by turning smart substitution off in the settings of the API

**Comment by subrata71** [comment]
@jfajardo 
As a current workaround can you please try the following steps?

- Turn off smart JSON substitution
![Screenshot 2022-08-01 at 3 55 46 PM](https://user-images.githubusercontent.com/3524599/182123959-cfe2110f-1f65-4b0c-8305-6ad7e8758972.png)

- Enclose the values with double quotes
```
  {
      "email": "{{SignUpForm.data.InputEmail.toString().toLowerCase()}}",
      "password": "{{SignupForm.data.InputPassword.toString()}}"
  }
```

**Comment by jfajardo** [comment]
@subrata71 thanks, works fine
