### ISSUE TITLE
[Bug]: Async function does not appear on settings tab

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[clearStorage](https://release.app.appsmith.com/app/earworm/debugging-page-62a32578f4e3980741ff56e2/edit/jsObjects/62a32578f4e3980741ff5760?branch=master) function does not appear on the settings tab of the object unless modified. To repro the function not appearing on the settings tab, clear cache and reload the JS object and observe again

### Steps To Reproduce

1. Go to the app at [this](https://release.app.appsmith.com/app/earworm/debugging-page-62a32578f4e3980741ff56e2/edit/jsObjects/62a32578f4e3980741ff5760?branch=master) location
2. Navigate to the settings tab and observe that the function clearStorage does not appear on there
3. If you can see it, clear cache and reload page
4. Modify the function and you'll start to see the function on the settings tab

Function:
![image](https://user-images.githubusercontent.com/79509062/182088186-2b655e11-19f0-4878-8d7b-e25fd79dceee.png)

Async function does not appear on the settings tab:
![image](https://user-images.githubusercontent.com/79509062/182088027-6aa44fee-1011-4d21-a513-e3a4414901f7.png)

### Public Sample App

https://release.app.appsmith.com/app/earworm/spotify-and-youtube-61ea4a44361846772cfb1180/edit/jsObjects/6266b803cb603a05f907ff76?branch=master

### Version

Cloud

**Comment by ramsaptami** [comment]
Related issue https://github.com/appsmithorg/appsmith/issues/11589

**Comment by bharath31** [comment]
@ramsaptami I'm not able to reproduce this

**Comment by ramsaptami** [comment]
I've updated the [app link](https://release.app.appsmith.com/app/earworm/debugging-page-62a32578f4e3980741ff56e2/edit/jsObjects/62a32578f4e3980741ff5760?branch=master) to access the function that fails in this scenario
