### ISSUE TITLE
[Bug]: Autocomplete suggestion for table widget (triggeredRowIndex) does not return any value

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Autocomplete suggestion `triggeredRowIndex` shows up on autocomplete but does not return any value under any known condition.

### Steps To Reproduce

1. Drop a table and text widget on to the canvas
2. Observe there's a suggestion for `triggeredRowIndex`, use that in the text binding as {{Table1.triggeredRowIndex}} - it's always an empty value. Also, this suggestion has an `Unknown` type.

![image](https://user-images.githubusercontent.com/79509062/182130165-43afe344-743f-49d8-959f-2c8970da67a0.png)

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
![Screenshot 2022-08-06 at 12.48.20 AM.png](https://images.zenhubusercontent.com/60c2f984f9be7454ac4d7382/c0503f29-5619-4ac8-ab8c-41dd186e54b6)

When we click on a button added in table row then we could see triggeredRowIndex value getting changed. Until there is nothing triggered this values stays not defined and hence unknown. 
cc: @ramsaptami
