### ISSUE TITLE
[Bug]: On unchecking the 'Editable' checkbox 'Update Mode' is still displayed in the property pane of the Table widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we uncheck the `Editable` checkbox for all the columns or even for a single column, the `Update Mode` property is still displayed in the property pane. It doesn't make sense for it to be there as it is useful only when a columns is marked as editable.

https://www.loom.com/share/daf6b56af55f4911a022bca3507a9a50?focus_title=1&muted=1&from_recorder=1

### Steps To Reproduce

1. D&D a table widget.
2. Mark a column or all the columns as `Editable`.
3. Now uncheck the `Editable` checkbox.

**Expected:** The `Update Mode` property should disappear from the property pane.

### Version

Cloud

**Comment by dilippitchika** [comment]
@shadabbuchh this was done intentionally, as we are using the checkbox only to reveal the field. Rest all the time it will be visible, since the user has shown intent to make columns editable.
