### ISSUE TITLE
[Feature]: Support a button group in a table column

### ISSUE THREAD

**Issue by fomeiherz** [appsmithorg/appsmith#15565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![image](https://user-images.githubusercontent.com/8408589/182109836-87e881f7-e6b6-41d9-b182-cd70620f90cf.png)

As shown above, Is there a table's column support multiple button?

### Why should this be worked on?

Use case: I can put 'edit' or 'detail' button to a column, this will shorten the table length. Rather than add a new column for a button.

**Comment by dilippitchika** [comment]
@fomeiherz thanks for raising the request, we will prioritise this on our end and get back with a timeline. Until then please use the menu button for now.

**Comment by dilippitchika** [comment]
Closing as duplicate of #14579
