### ISSUE TITLE
[Bug]: Download | CORS errors to be shown to the user on UI as an alert

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#15577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="295" alt="Screenshot 2022-08-01 at 5 27 21 PM" src="https://user-images.githubusercontent.com/91450662/182142820-4723b058-44db-4956-9c22-8ac67aebc146.png">
<img width="540" alt="Screenshot 2022-08-01 at 5 27 54 PM" src="https://user-images.githubusercontent.com/91450662/182142893-6c2a5c48-950e-4804-ad83-01ba973d9d54.png">

### Steps To Reproduce

1. Drag drop a button widget to download an excel file on its 'onClick' event
2. Give url - sample: https://stg-trinity-uipub.netmeds.com/api/appsmith/generateTemplate
3. Click on the button & observe the UI
4. **Observe : User sees no notification on the UI indicating the CORS issue even though the same is mentioned in docs & user is not aware unless he notices the Console of browser window**
5. **Expected: User should be notified of the CORS issue to course correct himself & not waste time in waiting for AForce reply**

### Version

Prod/Release v1.7.11

**Comment by Nikhil-Nandagopal** [comment]
This seems to be working so closing this
