### ISSUE TITLE
[Bug]-[64]:iFrame - On setting onSrcDocChanged event to navigate to a different page, user is unable to return to the original page where the iFrame is present.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#15585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/c99ecf443f2944e1aae6082ce067a355

### Steps To Reproduce

1. Drop an iFrame widget and add in the srcDoc details
2. Set the onClick event to navigate to a different page (same window) onSrcDocChanged
3. Change the content of the SrcDoc
4.  User gets navigated to the set page (page 1 in this case) but is unable to come back to page 4 (original page)

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 16 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@somangshu this is a critical issue in some sort, because the user can't go back to the older page anymore and there's no workaround other than exporting and updating the DSL manually. If you also the think the same, we can bump the priority.

**Comment by somangshu** [comment]
This is the default behaviour on the iFrame widget, As soon as the widget load, and the src is set, the onSrcDocChanged is triggered, we need to restrict this particular event, on page load, when the iframe widget is loaded, so not trigger the event. cc @techbhavin we have to first identify is this is possible. Adding it to the current sprint for tracking

**Comment by techbhavin** [comment]
@somangshu Yes, we can do as you mentioned things.
