### ISSUE TITLE
[Bug]: Button Group widget UI on Vertical Orientation, bottom text gets cutoff when Disable toggle on

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I set the Disable toggle to on, the button group bottom part of button text gets cutoff

Expected behavior - The border should not get cutoff.

### Steps To Reproduce

Drag and drop a button group widget,  Set orientation to Vertical. 
Add a few more buttons to the group. 
Set the Disable toggle to on and see the bottom part of text getting cut off. 

https://www.loom.com/share/00806e75e6604ec892dab6d2d1538e7f

### Version

Release

**Comment by dilippitchika** [comment]
Looks like this is fixed now @btsgh can you reverify?

**Comment by btsgh** [comment]
> Looks like this is fixed now @btsgh can you reverify?

Yes this is fixed @dilippitchika
