### ISSUE TITLE
Grouping and Reorganisation for Input Widgets

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#15583]
Based on the following Figma File and Notion doc, Group the properties of the Input widgets into Content & Style Tabs and re-organise the property sections.

Figma:
- [Input Widget](https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=2670%3A60360)
- [Currency Input Widget](https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=3751%3A69510)
- [Phone Input Widget](https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=3755%3A69854)
- [Date Picker Widget](https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=2650%3A57868)
- [Rich Text Editor](https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane?node-id=4516%3A129586)

Property Library:
https://www.notion.so/appsmith/853275adc3524c0390f7599b66f74859?v=8004de7cc9b74523a496388ad812ebc2

**Comment by Sripriya93** [comment]
Have tested all the mentioned widgets and its property pane and bindings with other widgets, all working fine. Moving to done
