### ISSUE TITLE
[Bug]: API endpoint returning readAddress(..) failed: Connection reset by peer; 

### ISSUE THREAD

**Issue by Irongade** [appsmithorg/appsmith#15597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user sets up an Authenticated Rest API Endpoint and runs the query, they get the following error: `readAddress(..) failed: Connection reset by peer; nested exception is io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer`
<img width="1273" alt="unknown 2" src="https://user-images.githubusercontent.com/37867493/182213553-a6a756c7-eb6a-496d-86f2-fe817c158852.png">
<img width="1258" alt="unknown 3" src="https://user-images.githubusercontent.com/37867493/182213596-048af9bc-7225-46d2-a0c5-14d468b3ffc8.png">

### Steps To Reproduce

1. Create an Authenticated Rest API endpoint with the below configuration:

<img width="819" alt="unknown 4" src="https://user-images.githubusercontent.com/37867493/182213737-b8108ba5-2d13-47ab-8418-9861fa2ad6fd.png">
<img width="799" alt="unknown 5" src="https://user-images.githubusercontent.com/37867493/182213742-15091133-f9b0-49d6-9521-79ec270d26fb.png">

2. Set the content type to `application/json` and body data to
<img width="1273" alt="unknown 2" src="https://user-images.githubusercontent.com/37867493/182214001-cb1890c9-1cde-4a2c-b51a-e250c4910b36.png">

3. Run the API.

### Version

1.7.10

**Comment by prapullac** [comment]
Since the issue is related to oAuth 2 cypress for now can not be handled.

**Comment by ame-appsmith** [comment]
Same issue, different symptoms: 
![image](https://user-images.githubusercontent.com/101268423/182399331-fcbc6e97-0057-4002-8b7e-3c7c5efab8e6.png)

[internal discussion](https://theappsmith.slack.com/archives/C02805TDC8K/p1659354838917759)
