### ISSUE TITLE
[Bug]: Clicking on "Row Level" in the update mode dropdown adds a new save/discard column

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i click on the update mode dropdown multiple times, a new save/discard column is added each time

https://www.loom.com/share/c29cca9d3cbb45fab7aeee2da5310ab4

### Steps To Reproduce

1. Mark the table as editable
2. Open the update mode dropdown
3. Click on row level again
4. Observe a duplicate column is added for save/discard

### Version

Production - 1.7.10

**Comment by sbalaji1192** [comment]
related to #15625

**Comment by dilippitchika** [comment]
Fixed in latest release
