### ISSUE TITLE
[Bug]-[1132]:Unable to access jwt token in EE instance via OIDC login

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to access jwt token in EE instance via OIDC login

### Steps To Reproduce

1. Take a pull of ee instance
2. Open local host 
3. Set up the OIDC login from the admin setting page
4. Now sign out
5. Login from OIDC 
6. Add a api
7. add post api as https://enz8r94ukkcmh.x.pipedream.net/
8. in header add bearer token <<APPSMITH_USER_OAUTH2_ACCESS_TOKEN >>
9. run the query 
10. now to go the request bin and check the post request the token i snot visible

### Version

production

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 283 |
| Effort (months)  | 0.5 |
