### ISSUE TITLE
[Bug]: When a column is made hidden in the edit mode the opacity of header is the same

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a column is hidden in the table and marked editable
1. Decrease the opacity of the header/label to be same as table v1
2. Remove the editability

### Steps To Reproduce

1. Add a table v2
2. Mark a column as editable
3. Now hide the column
4. Observe there are minimal UI changes to distinguish if it's visible

### Version

Production

**Comment by dilippitchika** [comment]
Create a new issue for hiding the hidden column in the preview mode @sbalaji1192

**Comment by jsartisan** [comment]
Fixed in #17228
