### ISSUE TITLE
[Bug]-[2780]:Success block of code is executed when user denies to share location when using Geolocation API

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user denies location access when using `getCurrentLocation()` function then success case is incorrectly executed.

Also, `appsmith.geolocation.canBeRequested` is true for case where user denies website to ask for location permission.

### Steps To Reproduce

1. Use following code in a JS object
```
locationDetails: () => {
		return appsmith.geolocation.getCurrentPosition()
			.then(() => {
			showModal('Modal1')
			showAlert('Your location is now updated')
			return appsmith.geolocation.currentPosition
		})
			.catch(() => {
			return showAlert("There's an error fetching your location", 'error') })
	}
```
2. On the Modal widget, drop a map widget and bind lat and long with `{{appsmith.geolocation.currentPosition.coords.latitude}}` & `{{appsmith.geolocation.currentPosition.coords.longitude}}` - step can be avoided but can be included to verify map widget functionality
3. Run the function `locationDetails` and deny browser permission to share location
4. Observe that success blocked is executed when user denies permission (watch video below)

https://www.loom.com/share/96c78abadac94817ba2917554a3209c0

### Version

Cloud

**Comment by satbir121** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | <<>> |
| Effort (months)  | 0.3 |

**Comment by bharath31** [comment]
Assuming 100% of users who use `getCurrentLocation()` or `canBeRequested` on WIDGET_PROPERTY_UPDATE or AUTO_COMPLETE_SELECT

**Comment by satbir121** [comment]
Not reproducible any more.
