### ISSUE TITLE
[Bug]: S3 plugin: handle IllegalStateException like stale connection

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#15620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1659432202891439 

### Steps To Reproduce

Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1659432202891439

### Version

self hosted

**Comment by shivamklr** [comment]
Hey @sumitsum, I am new to the project. Let me know if this is a great first issue for me.

**Comment by sumitsum** [comment]
Hi @shivamklr, thanks showing interest in contributing to Appsmith. Sorry, this issue has already been assigned to someone else, hence I would have to suggest you to look for another good first issue. Happy coding :)
