### ISSUE TITLE
[Task]: Mongo plugin: refactor Mongo plugin JUnit TCs

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#15623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Currenlty MongoPlugin test file has become too large. It would be good to refactor it into multiple smaller files. Filename: `MongoPluginTest.java`

**Comment by rohanshankar** [comment]
Is this still an issue? If so, I can work on it!

**Comment by rakhazachrie** [comment]
Hi, I'd love to contribute to this issue

**Comment by Taz03** [comment]
Can i get assigned for this?

**Comment by amogh2019** [comment]
Could someone please assign this issue to me?
Have raised PR #17633  for the same.

**Comment by sumitsum** [comment]
@amogh2019 assigned the issue to you.

**Comment by amogh2019** [comment]
Thank you @sumitsum for all the time that you have given over my changes this week! :)

**Comment by sumitsum** [comment]
Thanks @amogh2019 for your valuable contributions to Appsmith. Looking forward to more such contributions from you :)
