### ISSUE TITLE
[Bug]: GIT Remote URL Pattern does not accept URLs with hyphen

### ISSUE THREAD

**Issue by andreoav** [appsmithorg/appsmith#15637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The current regex does not works if you provide an URL starting with `git@` if the host contains a hyphen.

```js
const GIT_REMOTE_URL_PATTERN = /^((git|ssh)|(git@[\w\.]+))(:(\/\/)?)([\w\.@\:\/\-~\(\)]+)[^\/]$/im;
```

Matches: `git@example.com:user/name.git`
Does not match: `git@example-something.com:user/name.git`

### Steps To Reproduce

1. Go to `Edit` app.
2. Click `Connect GIT (Beta)`.
3. Type a remote URL like `git@example-something.com:user/name.git`.
4. Validation fails.
5. Remove the `-something` from the URL.
6. Validation passes.

### Version

Self Hosted - v1.7.10

**Comment by areyabhishek** [comment]
Thanks @andreoav for reporting this and sharing the piece of code with the problem. We'll check this out and share a fix. Did you run into this bug while trying to use git sync?

**Comment by AnaghHegde** [comment]
@andreoav Thanks for reporting this. It was a known issue and we have already raised a fix for this. Here is the link to the PR - https://github.com/appsmithorg/appsmith/pull/15499

It will be available in the next release. Closing this issue via https://github.com/appsmithorg/appsmith/issues/15432
