### ISSUE TITLE
[Bug]: Initialized datatype of variables does not change until the app is refreshed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Initialized datatype of a variable present in a JS object does not change until the app is refreshed. Hence when a user is using this changed variable type in a binding then they see an error for incorrect datatype.

### Steps To Reproduce

1. Add a new JS object - observe `myvar2` is an object datatype
2. Change this value to a string, something like, "sunday"
3. Try to bind `myvar2` to a Button widget's label and observe there's an error for datatype
4. Refresh the page and observe this error is cleared

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami JSObject variables work like constants and cannot be reassigned. Related to #14568
