### ISSUE TITLE
[Bug]: Hidden columns in table widget should not be visible in preview mode

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#15639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hidden columns in the table widget are shown after the visible columns in edit mode and hidden in view mode. We need to hide the hidden columns in preview mode as well.

### Steps To Reproduce

1. D&D Table widget.
2. Hide a column. Observe that it shown after the visible columns.
3. Go to preview mode. Observe that it is still shown.
4. We need to hide the hidden columns in preview mode as well.

### Version

cloud

**Comment by ame-appsmith** [comment]
Another [user](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100163607#part_id=initial-part-164629100163607-1422886147) reported this issue.

**Comment by tophat1986** [comment]
Any update on this one?  

I share the same view that even in edit/preview mode, if the columns are set to hidden, then let's hide it.  I can see it's greyed out at least.  

But it's hard to understand the positioning of columns and behaviour for UI if there's horizontal scrolling all the while for needlessly long reference paths and ID's.

**Comment by Nikhil-Nandagopal** [comment]
@tophat1986 we're now picking this up

**Comment by sbalaji1192** [comment]
@tophat1986 
>I share the same view that even in edit/preview mode, if the columns are set to hidden, then let's hide it. I can see it's greyed out at least.

In edit mode , we re greying out the hidden columns instead of hiding them, cause that gives users option to configure those columns without having to make them visible first.
I agree that in preview mode we should remove the hidden columns from the table. My above PR fixes this.
