### ISSUE TITLE
[Bug]: Action selector syntax gets messed up and does not revert to a sane state when errors in child fields are corrected

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Action selector fields go into a weird state with incorrect syntax and unnecessary characters when extra mustache binding is added to the child parameters. There's no way to revert to a sane state on the binding without toggling to JS mode or re-doing the action. It's also quite easy to miss the incorrect characters being added since it's not an editable field on non-JS mode and has a tendency to get overlooked by users.

### Steps To Reproduce

1. Select setInerval on the actions selector dropdown and input values into all fields
2. Intentionally include extra mustache bindings on the Id field and correct it
3. Do the same with other child fields
4. Observe the syntax on the main action selector field

https://www.loom.com/share/10dd74631fc34a659be4ec576e4b08dc

### Version

Cloud

**Comment by Druthi** [comment]
@ramsaptami There seems to be some changes with action selector since this loom video. Could you check if this is still happening. I wasn't able to reproduce it exactly.

**Comment by ramsaptami** [comment]
This issue seems to be resolved as part of action selector but raised #25428 and #25430 as an extension/side-effect of the changes
cc: @Druthi
