### ISSUE TITLE
[Bug]: Table widget interactable columnTypes (button, icon button, menu button, and edit actions) should not be present in `selectedRow`, `triggeredRow`, and `updatedRow` properties 

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#15640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table widget interactable columnTypes (button, icon button, menu button, and edit actions) should not be present in `selectedRow`, `triggeredRow` properties.

### Steps To Reproduce

1. D&D a table widget.
2. add a custom column and change the type to button
3. Observe that the button column appears in `selectedRow` and `triggeredRow` properties.

### Version

cloud

**Comment by ramsaptami** [comment]
`EditActions1` comes up on auto-complete which needs to be removed from suggestions along with the other changes mentioned above.

[Slack conversation](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1659948015443439)
