### ISSUE TITLE
[Bug]: Search bar in the workspace disappears on scrolling

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The “Search for apps…” search bar should be pinned on the top and should not disappear once we scroll through the apps. This will prevent the user from scrolling all the way up to the top just to search for an app.

https://www.loom.com/share/ddc06e6fbcb0433f92e6d320a3664d85

**Suggestions:**

1. The search bar should have a light border around it so that it is distinct from the background.
2. There should be a search bar for the workspaces section as well. If the user is invited to a lot of workspaces, it'll be easier for them to navigate to a particular one.

### Steps To Reproduce

1. Login to your account.
2. On the homepage you'll see the `Search for apps...` search bar.
3. Scroll through the workspaces.

You'll notice that the search bar disappears as we scroll down. This is not a good UX as the user has to scroll all the way up to search for an app.

### Version

Cloud

**Comment by pranavkanade** [comment]
@shadabbuchh I don't recall ever having a sticky search bar on /applications

**Comment by shadabbuchh** [comment]
> @shadabbuchh I don't recall ever having a sticky search bar on /applications

@pranavkanade can we add this as an enhancement?

**Comment by Nikhil-Nandagopal** [comment]
Solved
