### ISSUE TITLE
[Bug]: "Leave Workspace" option is not disabled if only one member is present

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Leave Workspace` option should be disabled/removed when you are the only member in the workspace.

<img width="356" alt="Screenshot 2022-08-03 at 2 58 33 PM" src="https://user-images.githubusercontent.com/39921438/182575550-947f1a49-7146-48fd-a094-d7708fd1de26.png">

### Steps To Reproduce

1. Go to the homepage.
2. Create a workspace such that only the current user is the admin and the sole member.
3. Clicl on the 3 dots next to the `Share` button.

**Expected:** The `Leave Workspace` option should either be completely removed or disabled.

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Not necessary the error is fine
