### ISSUE TITLE
[Feature]: Create a settings page to limit the domains which can access embedded apps

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#15661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Create a page where users can visually control where embedding is and isn’t allowed and discover how and where to control whitelisted domains

### Why should this be worked on?

[This PR](https://github.com/appsmithorg/appsmith/pull/15348) was used to address a possible vulnerability. However when we pushed this update, users were not able to access their existing apps, and this was reversed, by leaving the option to limit embedding, but enabling it across all platforms by default.

We should make it as accessible as possible for users to limit embedding to known domains

Deploy preview: https://theappsmith.slack.com/archives/C02JT9CSE6L/p1664371030083979

**Comment by RoopKrrish9696** [comment]
**Here is the first draft version of the admin settings :**  cc @kocharrahul7 @hiteshjoshi 

https://www.figma.com/file/NTbOAyb1Popy6bgiwjOuBy/Enable-embedding-of-Appsmith-apps?node-id=7159%3A1324

**Comment by RoopKrrish9696** [comment]
**Design review for the[ latest DP](https://theappsmith.slack.com/archives/C02JT9CSE6L/p1664371030083979):** cc @kocharrahul7 @akash-codemonk @ginilpg 

1. Stroke colour is missing from the radio button select state
2. The tooltip icon colour is different, refer to zeplin, please 
3. Font weight of the URL inputs is not matching zeplin
4. The active state of the URL input bar is missing
5. The "See why this is risky" button has a missing underline to it

**Comment by ginilpg** [comment]
@akash-codemonk  Please check below points 

- [ ] There is no duplicate domain validation. As of now, we can enter the same domain multiple times.
- [ ] Allowing embedding everywhere clears the domains entered in the restricted domain input box. Can we add a warning confirmation message if we change the option to "allow embedding everywhere"?

**Comment by akash-codemonk** [comment]
> @akash-codemonk Please check below points
> 
> * [ ]  There is no duplicate domain validation. As of now, we can enter the same domain multiple times.

As of now there is no validation really I don't feel like there is an issue with this. 

> * [ ]  Allowing embedding everywhere clears the domains entered in the restricted domain input box. Can we add a warning confirmation message if we change the option to "allow embedding everywhere"?

I think for a warning message we should take it up as an enhancement later on as currently the way it is implemented it is hard to add a custom UI.  Also I am not sure but I believe we won't have too many domain to enter here right? If required we can probably store it in local storage to persist those values.

**Comment by Richarex** [comment]
- [ ] In **Generated Docker Compose File** heading in docker spelling c is attached with k not spelled right. 
![image](https://user-images.githubusercontent.com/93259714/195525025-f30380ed-0822-4488-9c4c-282d73df1c57.png)

- [ ] Validation missing for **Limit embedding to certain URLs** section as it is allowing random text, only digits or only special characters in the url field without throwing any error message. Please refer to the attached video: https://www.loom.com/share/3d4468183a94478d84e7ae25f58441e4
- [ ]

**Comment by akash-codemonk** [comment]
> * [ ]  In **Generated Docker Compose File** heading in docker spelling c is attached with k not spelled right.
>   ![image](https://user-images.githubusercontent.com/93259714/195525025-f30380ed-0822-4488-9c4c-282d73df1c57.png)

Is out of scope of this issue. It is a different section altogether. So will not be modifying those. 

> * [ ]  Validation missing for **Limit embedding to certain URLs** section as it is allowing random text, only digits or only special characters in the url field without throwing any error message. Please refer to the attached video: https://www.loom.com/share/3d4468183a94478d84e7ae25f58441e4

As mentioned have not added validation to allow the full range of values as it can be more than full urls only. It is harder to validate for valid values here considering the range of values but it isn't a problem as it allows more flexibility for the user to edit.

**Comment by sharat87** [comment]
@Richarex, that's actually your browser rendering that way. The text is actually correct. You can try zooming in and out to see the rendering correct itself at some zoom levels.

Reg. the validation, I don't think that's a good idea. Hostname contain not just alphanumeric characters, but almost anything, especially when you consider non-English domain names. They also don't even have to have a `.` in them.

@akash-codemonk, I'm not sure if I understand, but this value should only be made up of _domains_, with optional protocol, but not full URLs.

**Comment by akash-codemonk** [comment]
Yeah by full url I meant including the protocol  e.g `https://release.app.appsmith.com`. I think you meant absolute urls e.g `
https://developer.mozilla.org/en-US/docs/Learn` probably has no effect. 
The point I wanted to make was adding some form of validation is not useful and leaving the user to enter the stuff they want  would be fine and preferred to make sure we don't end up restricting some value because our regex validation didn't consider that. What do you think about that?  @sharat87

**Comment by akash-codemonk** [comment]
> @akash-codemonk Please check the below issues mentioned:

> * [x]  4) When the user doesn't saves the embed urls and reloads the page and switches between different embed settings filters, it is observed that those urls reappears on the box. Please refer to the attached video: https://www.loom.com/share/d70cdb1e106d423ab918df003dbb560c

@Richarex This is expected behaviour since after editing you didn't save so on refresh it will show the previously saved values.
Have fixed point 5 as when the field is blank. The rest of the issues are existing behaviour/not related to embed settings/has been clarified in the comments above.
