### ISSUE TITLE
[Bug]: Hover state inconsistencies in Homepage

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The 3 dots next to `+ New` button & the pencil icon (for editing the workspace name) do not have a hover state.

https://www.loom.com/share/ad9b5267204345549f122af0d96e74c8

### Steps To Reproduce

1. Go to Homepage
2. For any workspace hover over the 3 dots next to the `+ New` button.
3. Now click on the 3 dots and hover over the pencil icon.

### Version

Cloud

**Comment by deepika-appsmith** [comment]
The hover state is present only for the header icons, we don't have a hover state for any menu item and it is consistent throughout home page. Attached reference.

Uploading Screen Recording 2024-04-01 at 1.36.59 PM.mov…
