### ISSUE TITLE
[Bug]: multiple canvas scrollbars on view mode

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#15678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/71900764/182599291-2efb9624-15f8-4865-a772-c0f69d853c3c.png">

### Steps To Reproduce

1. Create a long app in desktop mode
2. Deploy the application
3. reduce the size of the browser, until you see double scrollbars

### Version

Cloud

**Comment by btsgh** [comment]
Tested and found to be fixed
