### ISSUE TITLE
[Epic]: Stress test, profile and optimize widgets

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#15699]
### Objective

As we exhaust options to optimize for performance at the platform level, it's time to optimise individual widgets. We will in order of what widgets make majority of user apps.
You can use this order to start with

- Table
- List widget v2
- Tabs
- Modal
- Form
- JSON Form
- Input 

**What is expected**

- Stress test widgets with lot of data, actions, code and see where they break. See if we can remove those limitations, or put checks so that user doesn't fall into these.
- See if the underlying component can be optimized. ex: https://github.com/appsmithorg/appsmith/pull/11673
- Check what happens to these widgets in an eval cycle
     - When the widget property changes
     - When a linked widget changes its property. [Input1 changing Text1 default value]
     - When nothing in widget changes.

Look for wasted renders, unnecessary style recalculations [These appear in purple/violet color in chrome performance profiles].

### Success Metrics

| Metric         |
| -------------- |
| Our widgets are 10-40% faster  |

### Prioritised User Stories

| User Story    |
| ------------- |
| e.g. as a user, I want the widgets to be more responsive and fast |
| e.g as a user, I don't want my apps to crash or go into unrecoverable state  |

### RACI matrix

| ------------- | ------------- |
| Responsible   |               |
| Accountable   |               |
| Consulted     | @SatishGandham |
| Informed      |        @somangshu        |

**Comment by somangshu** [comment]
We do not have the bandwidth to take this up right now, We are looking at the list widget perf separately though
