### ISSUE TITLE
[Bug]-[Infinity]:appsmith.store value not read on load (when branch query param is removed)

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#15692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app integrated to git is opened without the branch param.
Stored value using `storeValue("key", "value")` is not fetched on page load.

### Steps To Reproduce

1. Create an app integrated with git.
2. Create a button to store some value on click. -> `storeValue("value", "abc")`
3. Create a text box to show the stored value. -> `appsmith.store`
4. Deploy the app and re-open link **without branch query param**.
5. Click store value and refresh the page.
6. Notice `appsmith.store` is empty on load.

https://www.loom.com/share/88fc5c03acc6452893b5b846bb4bf209

### Version

Cloud - 1.7.11

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7gfbg)

**Comment by pranavkanade** [comment]
@AnaghHegde could this be an issue from `git-sync` end?

**Comment by AnaghHegde** [comment]
@pranavkanade I am not sure. I am not aware of how the storeValue function works internally. Need to investigate this.

**Comment by bharath31** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | <<number>> |

**Comment by GreenFlux** [comment]
another user on Discord is facing this issue:
https://discord.com/channels/725602949748752515/1073980930970108016

**Comment by bharath31** [comment]
bumping the priority up. @satbir121 could we have someone from the team investigate this issue?

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 this is high priority inline with our [labeling guide](https://www.notion.so/appsmith/Issue-Labeling-and-Prioritization-0072175fd0f54983bf5b499895c7315e)

**Comment by GreenFlux** [comment]
another user on Discord is facing this issue. Do we have an ETA for a fix? 
https://discord.com/channels/725602949748752515/1073980930970108016/1075049112782770229

**Comment by ohansFavour** [comment]
@GreenFlux [the fix](https://github.com/appsmithorg/appsmith/pull/20601) for this will be merged into release today
