### ISSUE TITLE
[Bug]: Failed to fetch datasource structure error is displayed when we try to create crud pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While generating a crud page failed to fetch Datasource structure  is displayed even when there are tables
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/45958978/182828951-994f7e5d-28f2-4597-a7c1-80efbd2dc2d1.png">

### Steps To Reproduce

1. Go to home page
2. Create new workspace
3. cretae new app
4. add a mongo datasource
5. now try to generate a crud page 
6. The fetch Datasource structure error is displayed

### Version

https://rbac-release.appsmith.com/app/rbac-ce/page2-62eba4baff270560daab27e2/edit/datasource/62eba4beff270560daab27e4?branch=branch/test_01&from=datasources

**Comment by trishaanand** [comment]
@RakshaKShetty : Unable to reproduce on my local. Could you retry ?

**Comment by RakshaKShetty** [comment]
Not able to repro the issue so closing it for now
