### ISSUE TITLE
[Bug]: Evaluated Values of Graphql Query, Pagination is always undefined 

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#15714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The query body, pagination params should evaluate to proper values without dynamic bindings or undefined.

<img width="922" alt="Screenshot 2022-08-04 at 6 29 31 PM" src="https://user-images.githubusercontent.com/7565635/182852969-4dcecb02-745a-4a41-bbf4-860089e5607b.png">

### Steps To Reproduce

- Try creating a graphql api
- Change the query body
- The evaluated popup has undefined as value always

### Version

Self Hosted

**Comment by prapullac** [comment]
Verified on the DP and works well

**Comment by prapullac** [comment]
verified on the DP
