### ISSUE TITLE
[Bug]: Alignment issue in edit page of s3 Datasource 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Alignment issue in edit page of s3 Datasource 
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/45958978/182838456-7fba87f7-cc70-4f10-86d1-ea158600b5c4.png">

### Steps To Reproduce

1. Go to the home page
2. Create new workspace
3. create new app
4. Go to datasource page
5. click on s3 datasource
6. in edit page see the alignment of encrypted text

### Version

release

**Comment by prapullac** [comment]
Verified on the DP and looks good
