### ISSUE TITLE
[Feature]: Introduce permission for the Audit Logs with the new RBAC Infrastructure

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#15715]
## Sub Tasks

- [ ] Introduce a new permission group that grants access to read AuditLogs from the DB @trishaanand 
- [ ] Assign this permission to the Instance Admin only in v1. @AnaghHegde

**Comment by vuiets** [comment]
Is this to cover the `View Audit Logs` permission as part of RBAC?

**Comment by AnaghHegde** [comment]
@vuiets Yes that is correct.

**Comment by AnaghHegde** [comment]
This will be part of v2.

**Comment by AnaghHegde** [comment]
We will be picking up a few tasks in this -
1. Introduce a new permission group which grants access to read AuditLogs from the DB
2. Assign this permission to the Instance Admin only in v1.

**Comment by AnaghHegde** [comment]
This is completed. Latest changes are in the test env.
