### ISSUE TITLE
[Enhancement] :  "reset form on success" field when switched on also resets if there's an error in the API.

### ISSUE THREAD

**Issue by techbhavin** [appsmithorg/appsmith#15713]
There's one issue which we may need to fix when we are taking this up. 

Link to video - https://www.loom.com/share/56cc7ae651e34f8b88db0d730805e0b3

Today our "reset form on success" field when switched on also resets if there's an error in the API which is incorrect, i believe this could be fixed here

_Originally posted by @dilippitchika in https://github.com/appsmithorg/appsmith/issues/3613#issuecomment-1138453150_

**Comment by somangshu** [comment]
@dilippitchika is this being worked on?

@techbhavin can you give an update?

**Comment by dilippitchika** [comment]
Not that i am aware of @somangshu

**Comment by dilippitchika** [comment]
It was supposed to be done after form button migration, hence it was in sprint backlog

**Comment by somangshu** [comment]
@dilippitchika thanks, Can you link the issue to it?

**Comment by dilippitchika** [comment]
Linked to #3613

**Comment by dilippitchika** [comment]
Cannot reproduce, when api fails. Bumping this down and moving to icebox.
