### ISSUE TITLE
Create instructions for starting a DB with templates Schema

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#15737]
Today, when a user forks a template app, they are tied to using our database, which has all the tables prepared for this app to work well. However, if the user wishes to switch to their own database in this forked app, they have no easy way to replicate the necessary table schema on their database.

To solve this, we approach with three solutions that the user can choose from, depending on their situation.

1. A Docker image that starts a database, pre-filled with the necessary table schema and data even, along with an ngrok connection that the user can immediately start using in their app's datasource.
2. A Heroku one-click button to bring up a PostgreSQL database, which is then filled with the schema, and can immediately be used as their app's datasource.
3. An SQL file, that, when run on any database that they already have at hand, will produce the necessary schema and initial data, **without** corrupting any existing data on the database.

**Comment by jacquesikot** [comment]
@sharat87 Yes we do, I had created another task to track this here - https://github.com/appsmithorg/appsmith/issues/23500. We are going to be creating a getting started modal/screen on all templates to guide users on how to setup the app on their own datasource. I am going to close this task now and we can track from the other one above.
