### ISSUE TITLE
[Bug]: For git synced apps, local branches are missing in the branch list

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#15752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In git synced apps, local branches are missing under local branch section in branch list
<img width="1440" alt="Screenshot 2022-08-05 at 12 01 48 PM" src="https://user-images.githubusercontent.com/80334441/183016392-b6d78332-b532-489e-a71b-658f76d319bb.png">

### Steps To Reproduce

1. Go to git synced app which has multiple branches
2. Click on bottom bar branch button
3. Observe all the local branches are not visible

### Public Sample App

RBAC instance: https://rbac-release.appsmith.com/app/jsapp3/page1-625029b97881850f6e837180/edit?branch=master

### Version

RBAC instance

**Comment by trishaanand** [comment]
@AnaghHegde : Can you help debug this?

**Comment by AnaghHegde** [comment]
@Parthvi12 Can you please invite me to this app? I would like to take a look at this.
