### ISSUE TITLE
[Bug]:  The appsmith server  is taking too long error is displayed When we try to duplicate the app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to duplicate the app the appsmith server  is taking too long error is displayed
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/183016629-176b28f8-f089-4b2e-b982-cb27f8dfa285.png">

### Steps To Reproduce

1. Go to home page 
2. Click on meatball icon
3. Click on duplicate link
4. The appsmith server is taking too long message will be displayed
5. But after the page refresh the app will be duplicated in the workspace

### Version

https://rbac-release.appsmith.com/applications

**Comment by RakshaKShetty** [comment]
@trishaanand i have invited to a the workspace june6th regression here you can user app "release_jun6th" to repro the duplicate issue this is the app link  https://rbac-release.appsmith.com/app/release-jun6/postgre-629d7f12d13a5a28e0cbf3d5?branch=master

**Comment by RakshaKShetty** [comment]
Currently facing this issue in all the instances. This happens when the application is large with many pages. Keeping the issue open with low priority

**Comment by NickImmoflow** [comment]
Hey, 
on our self-hosted appsmith instance, I'm facing the same problem when I try to clone a page in my application. 

In the browser console, I get the Request_Timeout and Clone_Page_error. As I know, the timeout is on default at 20 seconds at the moment. 

Cloning the page helped to fix an unknown appsmith error, see it on screenshot.
![image](https://github.com/appsmithorg/appsmith/assets/152174059/aa6b36ce-ddb7-4850-8506-eb894fcccc61)

Please set up higher prio to this issue.

**Comment by NickImmoflow** [comment]
The problem is that it prevents me to create JS Objects. 
That is kind of critical.

Appsmith response: 
![image](https://github.com/appsmithorg/appsmith/assets/152174059/a609d558-0cc6-4c75-9bf5-d2372785ff3e)

Browser console response: "CREATE_JS_ACTION_ERROR"

**Comment by rahulbarwal** [comment]
Hey @NickImmoflow 
The original issue here is of `Duplicate app` feature, which has been deprecated. @RakshaKShetty should not face this anymore.

For the new errors you've shared, can you please confirm, if your issue same as the one shared in https://github.com/appsmithorg/appsmith/issues/24322 ?
This will facilitate centralized communication.

**Comment by Nikhil-Nandagopal** [comment]
Yeah lets close in favor of that or re-open a new one
