### ISSUE TITLE
Create a new temporary/restricted database for users that fork template applications

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#15756]
When a user forks a template application, we want to also create a separate database just for this user, that they can use to play around with the app to learn and perhaps, even share.

The following must be true for this database:

1. The user should be able to export all data on this database, when they want to.
2. The user only has permissions to run `SELECT`, `INSERT`, `UPDATE` and `DELETE` queries, and nothing else.
3. The database tables will be limited in terms of row count, like 100 or 1000.
4. The database comes with an expiry date, on which the database will be deleted.
    - As a prudent step before this, perhaps we can take a dump of all data in this database and email it to that user.

Additionally, there should be clear communication to the user regarding the above limitations.

**Comment by rahulbarwal** [comment]
@sharat87 Currently the way this is implemented is that all users share mock DB, which resets after every n hours. For now I think it is good enough. 
Other than this we are rethinking datasources in templates [here](https://www.notion.so/appsmith/Datasources-in-templates-a056de90c18a442fa6a46da130a13ae1?pvs=4)
I think we can close this. Let me know if you disagree.

**Comment by sharat87** [comment]
@rahulbarwal, feel free to close. This is now a very old issue, created when we had much less focus on templates. 🙂
