### ISSUE TITLE
[Feature] Enable num rows for server side pagination

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1578]
## Summary

Tables with serverside pagination can be navigated infinitely. Having an option to specify the number of rows will allow us to determine the number of pages

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal If I understand the issue correctly, a potential solution to this would be to have a `pageSize` or `pageRowCount` configurable from the property pane, which will override the current computed `pageSize` property?

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno no this is the total number of records that this data set contains. 
Total number/page size tells us the number of pages
