### ISSUE TITLE
[Bug] Some dynamic variables do not appear in the table - Saas Manager

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#15785]
The master branch does not show all the dynamic variables even if they exist in the database.

**As it should be**

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/be41b78e-f0d5-484e-b05a-69ed6be39b8a)

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/cf5ad026-57ef-48ce-aebc-48f61e01c69d)

**As shown**

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/531b18fb-b7e9-4c8e-99b1-426b85da1acc)

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/0dbfa2b7-3a89-4bf3-a613-97a86f455453)

**Comment by felixsuarez0727** [comment]
The problem was solved by cutting the {{currentItem.value}} command, and pasting it into the inputs area.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/47cd7f94-f147-4920-b20c-ef229fd7e32d)

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/03b791fa-8991-4de2-939a-2bd2c7857379)

**Comment by btsgh** [comment]
Unable to test this as the Saas Manager App - API Manager Page errors out -
<img width="1211" alt="SAASMgrError" src="https://user-images.githubusercontent.com/101863839/185365138-f31a0303-cb62-4d9d-b2de-5b290b6143b0.png">

**Comment by felixsuarez0727** [comment]
This issue is blocked by those two errors.
