### ISSUE TITLE
[Bug]: For shared workspace all the user icon are not displayed in the home page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For shared workspace all the user icon are not displayed in the home page
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/45958978/183344183-177e044d-13d0-44aa-b6fb-d3dc84c368ee.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/183344217-73a17b93-84ae-4e77-a2c3-1196012f844f.png">

### Steps To Reproduce

1. Go to home page
2. Now share a workspace to a user1 @appsmith.com
3. Give permission as app viewer
4. Now login as User 1 @appsmith.com
5. in the shared user icon only the user1 email will be displayed instead of displaying all user icon

### Version

https://rbac-release.appsmith.com/applications#62690e1cfbae7b086458424d

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty in the design, I can see it says +3 and that is expected. Hovering that should show all the users
