### ISSUE TITLE
[Feature] Allow disabling time in date picker

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1579]
## Summary

Provide an option to disable the time field in the date picker

**Comment by riodeuno** [comment]
This needs a new datepicker widget which allows only dates to be used and formatted.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno why does it require a new widget and not a property? Do we have a rule for widget vs property?

**Comment by mohanarpit** [comment]
Manipulating dates is complicated. I'd suggest that we have different widgets like DateTimePicker, TimePicker & DatePicker to denote different such combinations.

Also, we've seen this same scenario with other widgets. Complicating them with too many properties leads to bugs & lots of corner cases that wouldn't have arisen if they were separate widgets themselves. 

Lastly, I think it makes it clear to users building their apps regarding the usage.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit that sounds like a subjective rule. An objective rule would be like the underlying component is different so it should be different 2 different widgets or the underlying component is the same with different properties so it should be the same widget. Can we have a clear rule like this for deciding? On the internet is date time picker and date picker 2 different components in the majority of design systems or not? or in this one design system that we follow? If we can narrow that then it will become a no brainer in the future and we can move very quickly

**Comment by somangshu** [comment]
Closing this, as we are talking this up with #3516.
