### ISSUE TITLE
[Feature]: "replicaValues" field needed in helm chart's values.yaml

### ISSUE THREAD

**Issue by LronDC** [appsmithorg/appsmith#15813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Helm chart's values.yaml now does not have any field for statefulset replicas number. I think I need a field that can describe it.

### Why should this be worked on?

With this field I can set different replicas value when I install an app(now it defaults by 1), or when Appsmith is not used for now, I can set the replicas to 0 to free the resource for my environment by like: `helm upgrade ...  --set replicas=0`.

**Comment by LronDC** [comment]
Well If you like to accept this feature, I can work on this if you don't mind

**Comment by sharat87** [comment]
Hey @LronDC, thank you for raising this. We are actually already working on this to support clustering of the Appsmith stateful set by just changing the replicas.

I'm happy to see you're interested in working a solution for this, and I hate to reject. But, it's unfortunately a little more involved, and is tied to another fix we are working on. Predominantly around being able scale Appsmith, MongoDB and Redis replicas separately and reliably. So, we'll get back with a solution to this soon.

Thanks again! 🍻

**Comment by LronDC** [comment]
Very good to know that

> Hey @LronDC, thank you for raising this. We are actually already working on this to support clustering of the Appsmith stateful set by just changing the replicas.
> 
> I'm happy to see you're interested in working a solution for this, and I hate to reject. But, it's unfortunately a little more involved, and is tied to another fix we are working on. Predominantly around being able scale Appsmith, MongoDB and Redis replicas separately and reliably. So, we'll get back with a solution to this soon.
> 
> Thanks again! 🍻

Very good to know that. Thank all your fabulous works.

**Comment by pruthvi-itribe** [comment]
Hey @LronDC any update when would this feature go live ? Thanks in advance

**Comment by sharat87** [comment]
Hey @pruthvi-itribe, the solution is currently in review, and we are working on a migration path and the new Chart with this support may need some manual effort to upgrade. We're testing this out a little more before pushing it out. Unfortunately, I can't give a timeline right now. Thank you for your patience.
