### ISSUE TITLE
[Bug]: Random old apps fail to open in edit mode

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Random old apps fail to open in edit mode
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/183368477-ca574cd9-abb6-4f76-89a3-6a3439c1f55f.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/183368513-724f0187-7429-4d33-bfce-c19257f98e23.png">

### Steps To Reproduce

1. Go to home page 
2. Click on Edit mode
3. The appsmith server is unavailable error is displayed
4. refresh the page the user can see the edit page
to repo again
6. Now go back to home page 
7. Launch the application
8. come back to home page
9. again click on edit mode 
10. the app crashes

### Version

https://release.app.appsmith.com/app/release-aug1/mysql-62e7790daeb9323a17ed951e/edit?branch=master

**Comment by rohan-arthur** [comment]
@RakshaKShetty looks like I don't have access to the app link you mentioned. Would you please add me if possible?

**Comment by rohan-arthur** [comment]
added label `datasources` as a dummy in order to show this in the BE board

**Comment by rohan-arthur** [comment]
@RakshaKShetty looks like this is not reproducible anymore, would you please check?
