### ISSUE TITLE
[Docs]: Add documentation for OIDC integration with AWS Cognito

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#15827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Add documentation for OIDC integration with AWS Cognito

### Describe the improvement

NA

**Comment by pranavkanade** [comment]
@RakshaKShetty have we tested this?

**Comment by pranavkanade** [comment]
Gentle reminder @RakshaKShetty

**Comment by jnikhila** [comment]
@RakshaKShetty - Could you please share the first draft?

**Comment by rmwebmethod** [comment]
We are currently attempting to follow the Cognito documentation, resulting in an error - has this documentation been validated and the integration being validated? (or are we misunderstanding the documentation?)

**Comment by danciaclara** [comment]
@rmwebmethod Could you share the link to the documentation you are looking at because the one mentioned on this issue is not ready yet?

**Comment by jnikhila** [comment]
[Duplicate](https://app.zenhub.com/workspaces/user-education-pod-61c01739f309a80011b48267/issues/gh/appsmithorg/appsmith-docs/972)
