### ISSUE TITLE
[Bug]: Sync function is loaded on page load when accessing function as myFunc.data

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using `JSObject1.myFunc1.data` in a widget binding automatically shows the message `[JSObject1.myFunc1] will be executed automatically on page load` even when the function `myFunc1` is not an async function so this function will not have any settings on the JS objects and is executed on page load, i.e. a sync function runs on page load which is not allowed on the platform right now

### Steps To Reproduce

1. Use following code on the editor - observe that this function is not asycn hence does not appear on the settings tab of the object
```
myFunc1: () => {
		console.log('Heloo')
	}
```
2. Use {{JSObject1.myFunc1.data}} on widget binding and observe the message appear stating the function will be executed on page load
3. Refresh the page and observe browser console print `Hello` since this function was executed on page load

### Version

Cloud

**Comment by nidhi-nair** [comment]
Hey @ramsaptami ~ This seems to be by design. Why do we want to remove this functionality? I can in fact see a test case written on the server for this exact same scenario to work as it is working. :D

**Comment by ramsaptami** [comment]
Ohhhkkkkk, that's very confusing now. Cause @ApekshaBhosale and I spoke about this and she mentioned sync functions should not be set to run on page load 🙊 @ApekshaBhosale what do we do here?
