### ISSUE TITLE
[Bug]: Checkbox group widget - Required on with no box selected, behavior is different from prod

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I enable required property, and uncheck all the checkboxes, the required indicator behaves differently. This does not seem to be a part of reskinning changes either (Refer [Notion](https://www.notion.so/appsmith/Checkbox-group-659541492f7d47bb9e2a0e6e46361580 ))

### Steps To Reproduce

Drag and drop a Checkbox group widget. 
Uncheck all the boxes
Enable the Required property
The individual checkboxes get color borders, as against the red border that should indicate Required.

<img width="687" alt="Release" src="https://user-images.githubusercontent.com/101863839/183399812-4b8d1446-9f0b-4327-9753-32dcc278e8b7.png">

<img width="659" alt="Prod" src="https://user-images.githubusercontent.com/101863839/183399899-dc1daef2-c3db-4bab-95d7-4e03f44a29c4.png">

### Version

Release

**Comment by dilippitchika** [comment]
@btsgh this is a deliberate change we made, it was a part of figma - https://www.figma.com/file/1aTQ6vksqqAMtgB243PtHm/UI-%7C-Widget-Style-Updates-0.1?node-id=5042%3A79852

We missed adding it in notion. Closing this.
