### ISSUE TITLE
[Bug]: Class cast exception in S3 file upload although works with the evaluated value when pasted

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#15832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to upload a file in the S3 bucket with the following content, it keeps throwing an exception `class java.util.LinkedHashMap cannot be cast to class java.lang.String`

```
{
   "type": "text/json",
   "data": "{{JSON.stringify(appsmith.store.s3_action)}}"
}
```

### Relevant Discussion

- [Slack Thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1659023286858039)

- [Intercom](https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100152652#part_id=initial-part-164629100152652-1386664490)

### Recorded Videos
https://user-images.githubusercontent.com/3524599/183392101-65df2d84-82c5-48ce-a715-d07701d94343.mov

Uploading Screen Recording 2022-07-29 at 11.29.20 AM.mov…

### Version

Cloud / Self Hosted

**Comment by subrata71** [comment]
The above exception occurs at the following line of the `AmazonS3Plugin.java `file. 

`String encodedPayload = (String) multipartFormDataDTO.getData();`

Is there a specific reason to do this explicit typecasting to String?
@nidhi-nair

**Comment by subrata71** [comment]
Working on refactoring the codebase so that it helps us write successful test cases as well. Currently, there are no successful test cases are written in the S3 plugin.

**Comment by btsgh** [comment]
Following Scenarios Tested using content similar to the description in bug - 
1. Single image (png) upload, Smart Substitution ON - Passes. 
2. Single image (png) upload, Smart Substitution OFF - Passes.  (Note: content should be without quotes for value - eg. "data": value)
3. Single text file upload, Smart Substitution ON - Passes. 
4. Single text file upload, Smart Substitution OFF - Passes.  (Note: content should be without quotes for value - eg. "data": value)
5. Multiple image upload [referencing one image], Smart Substitution ON - Passes. 
6. Multiple image upload [referencing one image], Smart Substitution OFF - Passes. (Note: content should be without quotes for value - eg. "data": value)
7. Multiple text upload [referencing one text file], Smart Substitution ON - Passes. 
8. Multiple text upload [referencing one text file], Smart Substitution OFF - Passes.  (Note: content should be without quotes for value - eg. "data": value)

**Comment by prapullac** [comment]
Verified the issues and looks good to be moved
