### ISSUE TITLE
[Bug]: The uncaught promise error is displayed in S3 crud page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#15833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The uncaught promise error is displayed in S3 crud page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/183395637-884d752d-dfd4-40f4-b05b-17e9027fef91.png">

### Steps To Reproduce

1. Create an application
2. Add s3 datasource
3. generate a crud page
4. Now in search bar search for the folder name which is not present
5. The uncaught promise error is displayed

### Version

https://release.app.appsmith.com/app/aug-8th-release/mysql-62f09cc053a70d4cee704fa1?branch=master

**Comment by sumitsum** [comment]
Analysis is mentioned here: https://theappsmith.slack.com/archives/C02KTH6EHUG/p1660033166283729?thread_ts=1659965856.599039&cid=C02KTH6EHUG . I have requested for this bug to be re-assigned to a FE engineer.

**Comment by RakshaKShetty** [comment]
Not able to repro the issue, Closing for now
