### ISSUE TITLE
[Bug]: JS functions do not execute when set to run on page load

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Setting a JS functions to run on page load should execute and display on the respective widget but this does not happen

### Steps To Reproduce

1. Execute an API like `Api1.run` on JS object and return data like `Api1.data` from the function `myFunc`
2. Bind JSObj.myFunc.data to a table widget and observe the message that the JS function will be run on page load
3. Refresh the page and observe table data being empty but the Api has been run successfully

### Version

Cloud

**Comment by nidhi-nair** [comment]
@ramsaptami Could you please provide code snippets for these?

**Comment by ramsaptami** [comment]
[JS object](https://release.app.appsmith.com/app/infinite/page1-62d6b8433184b16ccf074cab/edit/jsObjects/62ebaedbfa138d2492c63e55) that's been set to run on page load and also is bound to the table widgets on the canvas where no data is displayed when page is refreshed

**Comment by nidhi-nair** [comment]
Are we supposed to be allowed to connect async functions to table data? @ramsaptami

**Comment by satbir121** [comment]
@ramsaptami Is this issue still happening?

**Comment by ramsaptami** [comment]
Closing this since it's working as expected
