### ISSUE TITLE
[Feature] Support multipart form data in the API pane

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1586]
## Summary

The API pane support multiple `content-type` headers but not multipart-form-data. We should support this content type as well.

## Motivation

File uploads and any large request bodies require multipart form data for initiating requests. 

## Additional Context

**Comment by spsneo** [comment]
Multi part form upload is widely used for file uploads.  Having this feature will help a lot.

**Comment by khushbu014** [comment]
Is this in progress? Form data is largely required for the use-cases we want to implement.

**Comment by Rashwan** [comment]
Commenting here as per @Nikhil-Nandagopal request, This is a high priority feature for us also.

**Comment by ajinkyakulkarni** [comment]
We have started working on this action. We expect to have this feature out within 2 working sprints (or approximately in 2-3 weeks from now).
