### ISSUE TITLE
Update Button Recaptcha 

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#15863]
In the Validation example, the screenshot shows to add the Recaptcha token in the headers, which results in an error. It should be added in BODY -> MULTIPART_FORM_DATA as key-value pair.

Refer to this issue - https://github.com/appsmithorg/appsmith/issues/15580

**Comment by jnikhila** [comment]
Available for review.

**Comment by jnikhila** [comment]
Updated and published the doc.

**Comment by jnikhila** [comment]
Updated and published the doc.
