### ISSUE TITLE
[Task]: Investigate why useCanvasDragging is being called in view mode

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#15875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

useCanvasDragging.ts:143:50 is getting called in view mode and taking a lot of time.
Not really sure whats happening.

Put a break point in this function, and see it triggered in view mode.
<img width="278" alt="Screenshot 2022-08-09 at 7 24 44 PM" src="https://user-images.githubusercontent.com/441914/183668750-ece49db4-e72c-4eed-a2b4-d17a807b5ce8.png">

**Comment by SatishGandham** [comment]
This seems to be from the container widget. It uses CanvasDraggingArena unconditionally.

**Comment by somangshu** [comment]
@marks0351 I added this to the sprint and assigned this to, Just FYI
