### ISSUE TITLE
[Feature] Create a page for app crashes

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1587]
## Summary

Users sometimes see a crash and are presented with a blank screen. We need to give better screen with some information and a way to retry.

## Motivation

The existing 404 or timeout page designs don't suffice.

**Comment by aakashDesign** [comment]
Have designed a generic error state for such errors.
<img width="1123" alt="Screenshot 2020-11-23 at 2 30 31 PM" src="https://user-images.githubusercontent.com/65771350/99944189-73710e00-2d98-11eb-8b2e-89ca86c586a3.png">


Figma Link - https://www.figma.com/file/k8rfuKyOROXz4j9qjFOytj/Generic-Error-State?node-id=0%3A1

**Comment by rishabhsaxena** [comment]
We have this error page currently:
![Screenshot 2021-09-01 at 4 26 33 PM](https://user-images.githubusercontent.com/1944800/131659858-e6d552ea-3619-45ca-b98f-ed0c54deb37f.png)
