### ISSUE TITLE
[Docs]: Modify documentation for Mongo datasource with URI connection string

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#15886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/datasources/querying-mongodb

### Describe the problem

The changes need to accompany [this](https://github.com/appsmithorg/appsmith/issues/12713) bug

### Describe the improvement

The draft for the documentation change has been added [here](https://www.notion.so/appsmith/Mongo-URI-format-a9a8d77080274c5cb1c551d189a822de).

**Comment by jnikhila** [comment]
@jnikhila added a draft for the documentation change related to this issue [here](https://www.notion.so/appsmith/Mongo-URI-format-a9a8d77080274c5cb1c551d189a822de).
