### ISSUE TITLE
[Feature]: Clear button for errors tab

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#15884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We have a clear button present in the logs tab to clear out all the logs there, it would be good to have the same for the errors tab as well. It could have the same look and functionality as the clear button in the logs tab

![Screenshot 2022-08-10 at 11 37 07 AM](https://user-images.githubusercontent.com/10229595/183827523-5551c220-8410-4921-9139-247ad76bff31.png)

### Why should this be worked on?

1. Add a clear button to the errors tab

**Comment by Nikhil-Nandagopal** [comment]
@rimildeyjsr the reason we can't have a clear button for the errors tab is because the errors reflect the current state of the application so unlike logs, you can't clear errors
