### ISSUE TITLE
[Bug]: Add missing tooltips in the property pane

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add missing tooltips in the property pane

Check this doc to find all the properties which need tooltips - https://www.notion.so/appsmith/853275adc3524c0390f7599b66f74859?v=77bd7d93e7cc43499f4fcd0e8275c5df

### Version

Production

**Comment by Sripriya93** [comment]
1) Expected : JSON Form - onSubmit - Triggers an action when the user presses enter or clicks outside the input box

Actual: 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/104895602/197110401-51bd2524-8038-406f-b8b1-72a7bbe2db98.png">

2) Expected: JSON Form - Switch - OnChange - Triggers an action when user interacts with the switch

Actual:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/104895602/197123798-29e089ca-a99f-417a-ae31-b35bde936ce7.png">

3) Expected - onChange - for Table switch, Switch, Rating and JSON Form Switch - Triggers an action when user interacts with the switch

### Actual: Different Tooltips in different widgets property

4) Expected - Border Width - # Border Width (px)

Actual:
 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/104895602/197131799-dfbafdda-c04d-4525-b7a9-d4381725317e.png">

5) Expected - Background color - Not sure of the tooltip - In notion we are having only for List and text
Other widget mentioned - Stat box, Modal, Container, Video , Form, JSON Form
Actual#1: Sets the Background color of the widget (Video)
Actual#2: Use a html color name, HEX, RGB or RGBA value (Modal, Container, JSON Form, Stat box, Form)

6) Unclear of the tooltip for IFrame widget - 
Actual : The URL of the page to embed

**Comment by Sripriya93** [comment]
Few more Tooltips are yet to be verified, @kamakshibhat-appsmith will be updating if any. Removing the` QA` label now.

**Comment by kamakshibhat-appsmith** [comment]
Rest working fine
