### ISSUE TITLE
[Task]: Arango plugin: change default db name to `_system`

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#15899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Currently when a new Arango DB plugin datasource is created the default db name is `default`. We should change it to `_system` since this is what the Arango documentation mentions as their default db name: https://www.arangodb.com/docs/stable/http/database-notes-on-databases.html#database-name

**Comment by reachtokish** [comment]
@sumitsum I'm interested to take up the issue. Could you pls assign this to me?

**Comment by sumitsum** [comment]
@reachtokish thanks for showing interest in this issue. I have assigned this issue to you. You need to make the change in [this](https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-plugins/arangoDBPlugin/src/main/resources/form.json) file. Happy coding :)

**Comment by reachtokish** [comment]
Sorry mistakenly clicked on unassign me link

**Comment by reachtokish** [comment]
Also raised https://github.com/appsmithorg/appsmith/pull/16198 - this PR. Kindly have a look.
