### ISSUE TITLE
[Docs]: Query/API Response Larger Than 5 MB

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#15890]
<p>https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100140461#part_id=comment-164629100140461-16197088722</p>

**Comment by jnikhila** [comment]
- Create a new page (Query Errors) >> [Troubleshooting](https://docs.appsmith.com/help-and-support/troubleshooting-guide) and add details.
