### ISSUE TITLE
Capture console logs from IIFE evaluations

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#15893]
When we put in IIFE in Text field of a Text widget, the console logs inside the IIFE are not showing up in the debugger tab.

To reproduce:

1. Insert the following snippet in the text field of the Text widget
```
{{ function(){
	const temp = "hello";
	console.log("Ayush1",temp);
	return temp;
}()}}
```

2. Check the console, you won't be able to see the log item.

**Comment by ayushpahwa** [comment]
Closed with #15676

**Comment by AnandiKulkarni** [comment]
Verified above function with widget - text select switch input

**Comment by nidhi-nair** [comment]
Closing since feature branch has been merged into release.
