### ISSUE TITLE
[Bug]-[1500]:Running a function for the first time from the dropdown selector on the editor causes the function to return an incorrect response

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Running a function the first time and selecting the function from the dropdown causes the watch window to return an incorrect response even though we see a "function ran successfully" message

### Steps To Reproduce

1. Add the following code onto the editor
```
myFunc1: () => {
   Api1.run()
   return Api1.data
}
```
2. Refresh the page and make sure myFunc1 has been selected in the dropdown
3. Click on the Run button and observe the watch window return a response checking if the return keyword has been used in the code

https://www.loom.com/share/253f616d6d6b4807b7d60a648711a46d

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami Please note that `Api1.run()` is an async operation and you have to wait for the promise before returning data. The following code should work: 

```
myFunc1: async() => {
    await Api1.run()
    return Api1.data
}
```

**Comment by ramsaptami** [comment]
Using the code in the description only works from the second try onwards. The first try does not return a response which is a discrepency @bharath31

**Comment by bharath31** [comment]
Assuming 100% of users interacting with JSObjects face this issue

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3000 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
This is a code-level issue related to the usage of async/await. Adding `await` and waiting for the promise should fix this issue. Reason why this is happening only on first run: Api1.data result is cached on subsequent runs. 

Fix: Add a linting warning to prompt usage of async/await

**Comment by bharath31** [comment]
@satbir121 this might need further triaging

**Comment by satbir121** [comment]
This is the expected behaviour. The function does an async call and exits before the async call returns. Solution to this is to use an `async/await` statement:

```
myFunc1: async () => {
   await Api1.run()
   return Api1.data
}
```
