### ISSUE TITLE
[Bug]-[40000]:.data does not appear as an autocomplete suggestion when using JS functions in a binding

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

.data does not appear as an autocomplete suggestion when using JS functions in a binding

### Steps To Reproduce

1. Use a JS function in a binding like `JSObject1.myFunc1.` and observe that data does not appear as a suggestion on autocomplete

![image](https://user-images.githubusercontent.com/79509062/183961988-86a4bccc-d83f-4419-b115-1d714a621ca6.png)

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami are you trying to access a variable that is within the scope of a function?

**Comment by ramsaptami** [comment]
This is related to accessing the data itself after function run @bharath31

**Comment by bharath31** [comment]
Assuming 5% of users in the `Widget property update > Binding success` funnel face this issue

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 120 |
| Effort (months)  | <<number>> |
