### ISSUE TITLE
[Bug]-[1550]:When button group button or table column is deleted, linter does not pick up incorrect binding

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a button group's button is used in a binding and this button is deleted, the linter does not recognize this incorrect binding

### Steps To Reproduce

1. Use a button group's button (eg, button1) in a binding on a text widget like `{{ButtonGroup1.groupButtons.Button1}}`
2. Now delete this button on the button group widget - observe no error is picked up from this incorrect binding path and no lint error is displayed

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami have you seen similar linting errors for other widgets?  

Assuming 10% of users who update a button group widget face this issue

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 75 |
| Effort (months)  | <<number>> |

**Comment by ramsaptami** [comment]
This is probably the case even with a table widget's column @bharath31

**Comment by satbir121** [comment]
Should users be using `{{ButtonGroup1.groupButtons.Button1}}` and `{{Table1.primaryColumns.Column1}}` ?

They are not exposed inside autocomplete because we do not want users to use them. They are just internal variables and they might change in future.

**Comment by bharath31** [comment]
Agree with Satbir. Optional chaining would be the best way to handle failures here.
