### ISSUE TITLE
[Bug]: Loading of API Manager Page fails with UncaughtPromiseRejection and Fetch_Integration_Datasources action failed.

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#15911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to go to the API Manager Page from the Integration Manager Page 2 errors/alerts show up.

`UncaughtPromiseRejection`: This appears everytime, it didn't cause issues with loadind the page in the past.
`The action "Fetch_Integration_Datasources" has failed`: This error is recent. It doesn't appear all the time, but when it appears the API Manager Page fails to load.

https://user-images.githubusercontent.com/25110207/183977544-5f483c80-99de-499f-a531-76e9aac7ba81.mp4

https://user-images.githubusercontent.com/25110207/183977551-cf860d5a-a601-4577-b45a-f58a622a36c1.mp4

### Steps To Reproduce

1. Launch the SaaS Manager App
2. Click on "View APIs" for the Twilio Integration.
3. Every now and then you will see the errors mentioned above.

### Version

Cloud v1.7.12-SNAPSHOT

**Comment by felixsuarez0727** [comment]
I did some research on both problems and this is what I found:

`UncaughtPromiseRejection`: This error occurs when you click on View Api without first selecting the row. When using currentRow._id it is undefined and therefore shows the error. To fix it temporarily, just click on the row before doing any action.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/02881a57-adc4-4ca7-99fc-ff112886efd1)

`The action "Fetch_Integration_Datasources" has failed`: I did not find the source of this problem I checked where fetch_integration_datasource is used and it still throws the error. In the query the error message is **$in needs an array**.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/d2df2b80-457c-4f2a-8bdd-0ddc30f7f501)

**Comment by felixsuarez0727** [comment]
|Class|Color|
|--|--|
|Button|(0,255,0)|
|||
|||
|||
|||
|||
|||

**Comment by prapullac** [comment]
We observe the page seems be e,pty and the API is failing
 ![Screenshot 2022-08-23 at 10.21.07 AM.png](https://ima![Screenshot 2022-08-23 at 10.21.15 AM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/04441a76-9054-4265-a0e7-81a08720668d)ges.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/44bf04a7-e33a-4415-b68e-fa15ea483308)

**Comment by felixsuarez0727** [comment]
@prapullac, is the error shown above something that you can consistently reproduce? How often does it happen to you?

I've been testing the SaaS App and haven't been able to make that specific query fail.

**Comment by prapullac** [comment]
@felixsuarez0727 : I am consistently able to repro this issue. I have also tried to relog in and verified

**Comment by felixsuarez0727** [comment]
I tried several times and the problem does not occur.

https://images.zenhubusercontent.com/275993885/c30c0406-2db4-49ee-9cf2-dacf9e13913c/video1634188688.mp4

**Comment by felixsuarez0727** [comment]
The issues in regards to access of the SaaS App were solved; so, moving this issue back to QA.

**Comment by prapullac** [comment]
Verified on DP
