### ISSUE TITLE
[Docs]: Update URLs in 'embedding apps' docs to new format

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#15915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/advanced-concepts/embed-appsmith-into-existing-application

### Describe the problem

The URLs in this docs page are of the old Appsmith URL format which may lead to confusion to users attempting to troubleshoot issues.
 
See the [original Slack thread](https://theappsmith.slack.com/archives/C01CFTXD0N8/p1660163084313189?thread_ts=1660163084.313189&cid=C01CFTXD0N8) for reference

### Describe the improvement

Since this page is documenting the use of HTML iframes and embedding Appsmith into other apps, we should update these Appsmith URLs to match the new style so users aren't confused if their app's URL doesn't match the docs examples.

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/advanced-concepts/embed-appsmith-into-existing-application).
