### ISSUE TITLE
[Bug]: Buttons inside forms added in containers and modals don't show form settings

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#15939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i have a container or a modal and add a form in it, the button for submit and reset don't show the form settings. 

### Steps To Reproduce

1. Add a container/modal
2. Add a form in it
3. Select the reset and submit button
4. Observe it doesn't show the options for form settings

### Version

Production

**Comment by dilippitchika** [comment]
@techbhavin can you please pick this up asap

**Comment by dilippitchika** [comment]
@techbhavin are you checking this?

**Comment by techbhavin** [comment]
@dilippitchika  issue fixed. Now some unrelated test case failing so working on it
