### ISSUE TITLE
[Bug] When widget name is updated the widget does not get searched on entity explorer

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1594]
Steps to reproduce:
1) Add a widget on the page eg: Button1 
2) Search via entity explorer
Observe the widget get identified
3) Rename the widget as "Fly"
4) Search the widget via entity explorer
and observe

Observation:
It is observed that on typing the widget in the entity explorer only the page is highlighted but the widget is not highlighted

Expectation:
It is expected that the widget must be highlighted as that of the other widgets

Video:
https://www.loom.com/share/d90426a837bc4d19b64ed24b67206a54

**Comment by Nikhil-Nandagopal** [comment]
@prapullac is this still happening? Can you verify please?

**Comment by prapullac** [comment]
Hi Nikhil 
This issue still persist. Hence reopening the issue.

**Comment by Nikhil-Nandagopal** [comment]
@prapullac can you help with the steps / video?

**Comment by akash-codemonk** [comment]
@prapullac Is the widget name not searchable or is the widget group not expanding to show the searched widget name?

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk after renaming it, the widget doesn't show up when you search by the new name
