### ISSUE TITLE
[Bug]: Browser tab title is generic when the embed query param is true

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#15949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I view my app in the browser I expect to see the app name as the tab title.

When I view my app in the browser with the embed query param set to true the tab title is just Appsmith. On mouseover, it simply shows an IP under the title.

![image](https://user-images.githubusercontent.com/101155659/184183826-deab8a5e-801f-4243-a7a2-2fd21717102f.png)

![image](https://user-images.githubusercontent.com/101155659/184183892-fd3dd9b2-d661-4ff3-87c8-e622398cbc80.png)

### Steps To Reproduce

1. Open any appsmith app
2. Observe that the tab title is the name of the app
3. Add `embed=true` as a query param to the URL
4. Refresh the page
5. Observe that the tab title is now `Appsmith`

### Version

Cloud

**Comment by gzarruk** [comment]
We have the same issue and is a problem as we white label our applications and looks unprofessional when we can't  expose the title. This happens when using side navigation. Top navigation displays the application title, so we are forced to use it. The attached image shows side navigation (left) vs top navigation (right). 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/24595022/236401716-9f5f4e8f-292c-43de-ac23-41b988751ee9.png">

**Version**
Self hosted

**Comment by dilippitchika** [comment]
@gzarruk i don't understand the 1st image, you are in the edit mode  so it will show the Editor and Appsmith, can you add a screenshot of the tab title after setting side nav and deploying the application?

**Comment by gzarruk** [comment]
> @gzarruk i don't understand the 1st image, you are in the edit mode so it will show the Editor and Appsmith, can you add a screenshot of the tab title after setting side nav and deploying the application?

Nope, I'm in preview mode in both cases. 
If I enable Side Navigation and deploy it, this is how it looks 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/24595022/236409471-a07ed338-e7e4-4afa-ba33-a80ae0f0dfd5.png">

**Comment by dilippitchika** [comment]
@dhruvikn can you triage this on priority? This happens when
- You turn off show navigation
- You set side navigation

**Comment by dhruvikn** [comment]
Hey folks, a PR to fix this has been [raised here](https://github.com/appsmithorg/appsmith/pull/23066).
