### ISSUE TITLE
[Bug]: GraphQL plugin: checkbox for different page size in cursor pagination section is not working

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#15956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- checkbox for different page size in cursor pagination section is not working as expected.

### Steps To Reproduce

1. click on the checkbox.

### Version

self hosted

**Comment by prapullac** [comment]
@AmanAgarwal041 : Verified the issue on DP

**Comment by prapullac** [comment]
Not on the release yet

**Comment by prapullac** [comment]
Verified on the DP
