### ISSUE TITLE
[Bug] Multiple homepage can be created 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1595]
Steps to reproduce:
1) Add pages 
2) Clone a page 
3) Click on action icon 
4) Click on "Set as Home page " 

![Screenshot 2020-11-05 at 3 46 44 PM](https://user-images.githubusercontent.com/71753653/98232152-514b5380-1f83-11eb-9a0b-4a6df043b718.png)
![Screenshot 2020-11-05 at 4 22 49 PM](https://user-images.githubusercontent.com/71753653/98232160-55777100-1f83-11eb-9076-ab59698b71bb.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac please verify

**Comment by prapullac** [comment]
Unable to reproduce hence closing the issue
