### ISSUE TITLE
[Bug]: For Select widget or a Checkbox group widget, Auto-complete does not show up in the Options section on Refresh

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On binding the Options of Checkbox group to a text widget, on refreshing the page, the autocomplete options do not show up. 
Similar behavior is seen even on Select widget. 

### Steps To Reproduce

Drop a checkbox group widget and a text widget onto canvas.
Try binding one of the options to the text widget. We can see the auto complete options come on. 
Refresh this page.
Retry the binding. No auto complete suggestions come up this time. 
<img width="639" alt="Screenshot 2022-08-11 at 10 31 37 PM" src="https://user-images.githubusercontent.com/101863839/184191786-89ab9cbb-f1be-4709-8e41-c56ff9966f00.png">

### Version

Production

**Comment by btsgh** [comment]
Note: Also seeing this behavior in Switch Group widget.

**Comment by Rishabh-Rathod** [comment]
@btsgh Can we also check in mongo query where we send object and are able to add binding? Maybe that also is impacted due to this. 

WIP PR to fix it - https://github.com/appsmithorg/appsmith/pull/15999

cc: @ramsaptami
