### ISSUE TITLE
[Docs]: Table widget v2 inline editing validations

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#15955]

**Comment by dilippitchika** [comment]
@Pranay105 @jnikhila we will go live with this in 2 weeks, we are going to work on first draft next week. Should be a really small change, we are just adding a few more properties in the inline editable table. Please add this in next sprint.

**Comment by jnikhila** [comment]
Sure @dilippitchika - As soon as the first draft is ready, please add the Ready for Doc Team label and move the ticket to Backlog (Draft Ready) Pipeline.

**Comment by Pranay105** [comment]
@dilippitchika any update on this?
