### ISSUE TITLE
[Bug]: GraphQL plugin: installation issue with existing orgs

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#15975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Currently when GraphQL plugin gets added to older orgs it exhibits some issues like - (1) The authenticated API icon is missing (2) The GraphQL API icon is non responsive. Need to fix it. 

### Steps To Reproduce

1. Run `feat/grapql` branch code on your local which has some previous data / orgs. 
2. check the datasources page.

### Version

self hosted branch `feat/graphql`

**Comment by prapullac** [comment]
@sumitsum Verified the issue on DP

**Comment by prapullac** [comment]
Not on the release yet

**Comment by prapullac** [comment]
Verified on the DP
