### ISSUE TITLE
[Bug] Improper alignment of API pane

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1598]
When the user is navigated to API pane user can be observed an disturbance in API pane 

![Screenshot 2020-11-05 at 6 17 26 PM](https://user-images.githubusercontent.com/71753653/98243090-747dff00-1f93-11eb-8d54-a43815bf3b37.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac can you add steps / video?
