### ISSUE TITLE
[Bug]-[348]:"Default Selected Row(s)" property in Table widget does not work in deploy mode

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If we set up a value for the `Default Selected Row(s)` property in Table widget, The row gets selected in edit & preview mode but once we deploy the app, the said row is not selected by default.

https://www.loom.com/share/1c6be403e86b436a87ea62bd7b951b91

### Steps To Reproduce

1. D&D a Table widget.
2. When `Enable multi row selection` property is disabled enter any valid number in the `Default Selected Row` property.
3. Clicl on the `Preview` mode and then click on `Deploy`.
4. Carry out the same flow with `Enable multi row selection` enabled.

**Expected:** The `Default Selected Row(s`) property should work in the deploy mode as well.

### Version

Cloud

**Comment by dilippitchika** [comment]
Needs triaging, assuming it doesn't work for 20% users who have set the property.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 87 |
| Effort (months)  | 0.5 |

**Comment by souma-ghosh** [comment]
Unable to reproduce this issue @shadabbuchh

**Comment by shadabbuchh** [comment]
> Unable to reproduce this issue @shadabbuchh

@souma-ghosh as discussed I checked now & the bug does not exist on production any more. Please close this issue.
