### ISSUE TITLE
[Bug]: Scroll Indicator inconsistencies across browsers

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#15986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below are some inconsistencies observed w.r.t the `Scroll Indicator` Component in different browsers:

1. Scroll Indicator does not appear for the JS Objects (Editor) in Chrome whereas we are able to see it in Firefox.
<img width="1440" alt="Screenshot 2022-08-12 at 3 59 48 PM" src="https://user-images.githubusercontent.com/39921438/184337399-95874d3d-f007-4d6e-a8da-e7cf9cb93a62.png">

2. The shape of the Scroll Indicator itself is different in Chrome & Firefox.
<img width="1440" alt="Screenshot 2022-08-12 at 4 01 51 PM" src="https://user-images.githubusercontent.com/39921438/184337675-6557d0ae-f5d3-4698-840a-1b3cb35aafe2.png">

### Steps To Reproduce

This can be seen in the JS Object Editor page & places all over the app where scroll is enabled.

### Version

Cloud

**Comment by rohitagarwal88** [comment]
Fixed in ADS 2.0
