### ISSUE TITLE
[Bug]: Admin pages UI issues for self-hosted instances

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Following issues need design fixes on the admin pages for self-hosted instances

### Steps To Reproduce

- [ ] Include a "Learn more" button under the option to opt into telemetry tracking
- [x] reset, upgrade and download buttons are not vastly different in colour and need some more distinction from other text on screen
- [x] Upgrade button placement feels off since it aligns with the text box above but feels overly spaced
- [x] `Read more` option on email and Google maps redirects to incorrect page
- [ ] Need a r`ead more` option on Advanced tab
- [x] Astrix text under Redis text should be `Redis` not `redis`. Similar change is needed for Appsmith as well
- [ ] Versioning should more clear - `current version` shows currently available production version but not the installed version on the fat container. This needs to be split into a `current version` and `installed version` to easily distingush and let the user know how far behind (if any) they are to current version
- [ ] Add `current version`, `installed version`, `update button` and `info` on how to update current instance on the Version tab
- [ ] `read more` section is at the bottom for Version tab (discrepancy compared to other tabs)
- [x] The documentation link on the Users tab does not have CTA enabled
![image](https://user-images.githubusercontent.com/79509062/184386562-bca110df-46fe-49bf-8e8a-981c513a5b8d.png)

- [x] Default users are present on a newly setup instance
![image](https://user-images.githubusercontent.com/79509062/184386475-b42e73d3-8122-4b22-9752-1c268fcf3e43.png)

### Version

Self-hosted

**Comment by riteshkew** [comment]
resolved as part of login flow redesign.
