### ISSUE TITLE
[Bug]: Self-hosted onboarding design issues

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Following cases need design changes for the on-boarding journey users take on self-hosted instances

### Steps To Reproduce

- [ ] Next button on the page does not have an active/disabled state
![image](https://user-images.githubusercontent.com/79509062/184386702-8c2b8e0c-298a-4c61-b2dd-b7c5509db861.png)

- [ ] There's no hover state for the link 'see what is shared'
![image](https://user-images.githubusercontent.com/79509062/184386824-d60babdf-7b29-4ae0-93e0-c8991e08048c.png)

- [ ] Toggle button when changed, remains in `clicked` state (dark colours) and does not exit until clicked outside (revert to normal Appsmith colour)
![image](https://user-images.githubusercontent.com/79509062/184386889-74b0f76e-8c15-4252-8c88-5f4afd3f75a0.png)

### Version

Self-hosted

**Comment by sharat87** [comment]
@ramsaptami, can we close this as the current UI is very different from what's illustrated here?
