### ISSUE TITLE
[Bug]:  API endpoint returning readAddress(..) failed: Connection reset by peer;

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#15994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Users when using the Oauth to connect to  AuthenticatedAPI are getting the following error: `readAddress(..) failed: Connection reset by peer; nested exception is io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer.`

![image](https://user-images.githubusercontent.com/107841575/184372848-b9bace2c-c8d2-472d-823e-96390d89bac7.png)

### Steps To Reproduce

- Go to Datasources, choose Authenticated API
<img width="964" alt="image" src="https://user-images.githubusercontent.com/107841575/184374035-9ff18488-c0dd-44a0-a837-e47df30faa37.png">
- verify the API with Oauth client credentials.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/107841575/184374379-d3d94cfc-c842-4683-afc1-48ec97729619.png">
- Fill in the parameters and URL
<img width="915" alt="image" src="https://user-images.githubusercontent.com/107841575/184374928-68208f81-be06-4491-be9c-1ee7d5d316bb.png">

- Run the query

![image](https://user-images.githubusercontent.com/107841575/184375298-d5b09ddd-723c-46aa-879a-37e5c31275a2.png)

### Version

Self Hosted: v1.7.12

**Comment by mlarash** [comment]
Hi, I'm just curious since this is affecting some of our apps -- is there any guess when this bug will be fixed?

**Comment by pranavkanade** [comment]
We've seen something like this before as well

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum this is the corresponding sentry error
https://sentry.io/organizations/appsmith/issues/3388844796/?alert_rule_id=821323&alert_timestamp=1656523423900&alert_type=email&environment=Production&project=1546547&referrer=alert_email

**Comment by mlarash** [comment]
hi, sorry I just wanted to check again since hitting an authenticated endpoint is a crucial component of multiple of our apps. Is there any plan to fix this?

**Comment by sumitsum** [comment]
@mlarash can you please check if this is still occurring in the latest version since a duplicate issue was addressed recently : https://github.com/appsmithorg/appsmith/pull/15593

**Comment by prapullac** [comment]
@sumitsum : This error is currently not visible on release. hence moving it to Done state

**Comment by masterashu-motorq** [comment]
I can experience this error in v1.8.13 on Kubernetes
