### ISSUE TITLE
[Bug]: Input widget comes with a default plus icon

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#16006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

InputWidget comes with a default plus icon and we are unable to clear it even if we select "(none)" as the icon.

### Steps To Reproduce

1. Add a new input widget
2. Try to change the icon

### Version

release

**Comment by btsgh** [comment]
Seems to have been fixed. Do not see any plus icon now with input widget.
