### ISSUE TITLE
[Bug]: Updating Appsmith on Heroku fails because `ENV_HOSTNAME` can't be expanded.

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#16002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I attempt to update my Heroku Appsmith instance I expect it to go smoothly.

Instead, I get this error:

```
Error: Format string '/appsmith-stacks/logs/%(program_name)s/%(program_name)s-%(ENV_HOSTNAME)s.log' for 'program:backend.stdout_logfile' contains names ('ENV_HOSTNAME') which cannot be expanded.
```

A user on discord, `Javier Leyton#5316`, reported that they were able to update to 1.7.5 fine, but after that they are unable to update pending this error.

### Steps To Reproduce

1.  Try to update an Appsmith instance on Heroku
2. Observe that, instead of completing, the app crashes with the above error

This may also be happening when trying to create new instances.

### Version

1.7.5+

**Comment by AS-Laguna** [comment]
@sum35h Another user has reached out with this issue. Do we have any update on this?

**Comment by sum35h** [comment]
Yes, as @vneecious  setting the env variable `HOSTNAME` in the Config Vars will prevent this issue for now. We will address this bug in our upcoming releases.
