### ISSUE TITLE
[Feature]: Dynamic Gridlayout from array of json object

### ISSUE THREAD

**Issue by xoraingroup** [appsmithorg/appsmith#16004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Dynamic grid layout should be rendered from array of json objects.

- Assuming we have an API that returns array of json objects.
- Now I would like to render them in a dynamic grid layout.
- A main dynamic Grid Layout component can be dragged to the form and the options can be set for 1, 3, 6 columns grid layout.
- Then It should be possible to configure the boxes in layout with specific set of component, like image or video or some text with multiple headers etc.

### Why should this be worked on?

The infinite scrolling with dynamic grid layout can make it possible to have beautiful SPA. Right now I don't see any components that can do this. You can take an example from ghost main page where there is dynamic grid and infinite scrolling.

**Comment by Nikhil-Nandagopal** [comment]
@xoraingroup thank you for the feature request. We're tracking this feature here #7256
