### ISSUE TITLE
[Feature] Modal should be listed as a widget so that the user can create modals from the widget pane

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1600]
Adding modal into the widget list would help user to create new modal

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal How will the modal widget be dragged on to the screen? Today the modal can't be moved around or placed anywhere but the center.

Three ways of dealing with the modal here.
1. Should we let the user drag and drop a modal widget where they please?
2. Should they drag and drop the modal but it always gets positioned in the center?
3. Should they have to click the modal to create a modal?

**Comment by mohanarpit** [comment]
Ass a UX, I vote for #2. Makes it intuitive for people and the modal automatically centers itself onto the screen.

**Comment by Debsourabh** [comment]
Considering we do not have the feature to move widgets we cannot always place it in the centre. We should let them design a modal and reuse it within a widget, but that modal will not be visible when they click on deploy.

**Comment by Nikhil-Nandagopal** [comment]
I think we should do #1 because it gives users the option to create drawers if they want. Allow users to drop and resize the modal however they please

**Comment by Debsourabh** [comment]
Can you explain drawers a little more?

**Comment by Nikhil-Nandagopal** [comment]
@Debsourabh a drawer is what we have for the API pane right now. it's a modal that sticks to one side of the screen.

**Comment by Debsourabh** [comment]
https://www.figma.com/file/wj5oTtuQkT3FEpdGb8o57y/?node-id=0%3A1

The link for the Modal Widget.

**Comment by riodeuno** [comment]
Note:
- When dragging a modal widget from the widget cards pane, the modal background overlay appears
- When the user drops modal on the overlay, the modal snaps to the center of the overlay
