### ISSUE TITLE
[Bug]: Old column names continue to exist even after renaming the column in Google Sheet

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#16011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
![GS-Bug-Image1](https://user-images.githubusercontent.com/3524599/184616043-ec5d5963-40bf-4498-882e-72981d80806e.jpeg)

I renamed a column in an existing data source (google sheets) and the API correctly picks up the name of the column, but when I try to run it, it shows it can not locate the old Column and ends up in an error.

Old Name : Machine List
New Name : MachineList

Edit: Things got a lot weirder, When I try to create a completely different API to get data from a different sheet, I’m getting the same “Machine List” not found error - it was never there, to begin with. I don't know what's going on anymore.

![GS-Bug-Image2](https://user-images.githubusercontent.com/3524599/184616119-6dd73b1a-c73b-4dab-908c-68f28990417f.jpeg)

### Source
This issue has been reported first in the community.appsmith.com forum.
https://community.appsmith.com/t/api-referring-to-old-column-names-after-changing-them-and-giving-error-when-loading-data/1295

### Steps To Reproduce

1. Create a Google Sheet (GS) datasource
2. Save and authorize GS datasource
3. Create an API on this GS datasource with operation `Fetch Many`
4. Select one or more columns from the `Columns` drop-down list
5. Now go to your Google Sheet and rename one column
6. Go back to the API that you created in step 3
7. You will see the new column names appearing under the `Columns` drop-down list
8. Now select one or more columns from the `Columns` drop-down list
9. You will see an error like
    Filtering failure seen:  Column "< Old column name >" not found

### Version

Cloud / Self Hosted

**Comment by subrata71** [comment]
## Workaround
Although the workaround to this problem may feel weird. I am afraid there is no better way to get rid of this. However, I have tried to demonstrate the workaround to this problem through this [Loom video.](https://www.loom.com/share/d7207f58758840219142a694e0e3e768)

1. Create the old column name again in your Google Sheet (You don't need to put any data under that column. Just keep it dummy)
2. Go back to your Google Sheet API and reload that API 
3. Run the API
4. Now remove the column name i.e. the dummy column from the `Columns` drop-down list
5. Run the API again
6. Now remove the dummy column name from your Google Sheet
7. Again reload your API
8. Now select your preferred columns from the `Columns` drop-down list

**Comment by subrata71** [comment]
## More info
Let's say I have a Google Sheet datasource `GS1` and created an API named `API1`
Datasource : `GS1`
API1 refers to `GS1` datasource. API1 has some projection columns say "`FirstColumn`" and "`Oops`". Now if you create another API i.e. `API2` this property is also copied from the previous API.

<img width="608" alt="Screenshot 2022-08-15 at 5 23 11 PM" src="https://user-images.githubusercontent.com/3524599/184627527-32f72bfa-abed-4af5-b4c8-57ae7bd30b2b.png">

**Comment by AmanAgarwal041** [comment]
> ## More info
> Let's say I have a Google Sheet datasource `GS1` and created an API named `API1` Datasource : `GS1` API1 refers to `GS1` datasource. API1 has some projection columns say "`FirstColumn`" and "`Oops`". Now if you create another API i.e. `API3` this property is also copied from the previous API.
> 
> <img alt="Screenshot 2022-08-15 at 5 23 11 PM" width="608" src="https://user-images.githubusercontent.com/3524599/184627527-32f72bfa-abed-4af5-b4c8-57ae7bd30b2b.png">

Created a new issue : #16077

**Comment by prapullac** [comment]
@AmanAgarwal041 
I observe that on changing the table column name in Gsheet gets updated only in the Response table however the Column name fields dropdown or Sheet name fields dropdown does not get updated in the Fetch many commands
![Screenshot 2022-08-18 at 4.49.29 PM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/ab9888fd-6710-41b0-b522-c83c3e425fd4)

**Comment by AmanAgarwal041** [comment]
> @AmanAgarwal041 I observe that on changing the table column name in Gsheet gets updated only in the Response table however the Column name fields dropdown or Sheet name fields dropdown does not get updated in the Fetch many commands ![Screenshot 2022-08-18 at 4.49.29 PM.png](https://camo.githubusercontent.com/ebf5a8ae8f925b7f3679e0ae952786b5fd44ea597a63a5e0e254475b6e2dbc59/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630613463666237646331303662663439646331343661642f61623938383866642d363731302d343162302d623532322d633833633365343235666434)

We are fetching column names once as they are fetched as dynamic values, so if we change the column names in google sheets then we don't get updated column names unless we refresh the page or the column fetching call goes again due to page changes or any other user actions. That is why the executing the query shows updated column but not the columns dropdown.

**Comment by prapullac** [comment]
@AmanAgarwal041 : Based on the above comment I have verified the issue and hence putting it to Done state
