### ISSUE TITLE
[Bug]: MongoDB query using {{Input.text}} value not working

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#16017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to run a MongoDB query using `{{Input.text}}`, I get an empty result even though the evaluated value is correct. This issue happens on both raw and regular find queries.  

Raw Find Query with plain string: 
<img width="1440" alt="Screenshot 2022-08-15 at 6 34 49 PM" src="https://user-images.githubusercontent.com/17562726/184640404-b73ce7ee-25a3-431a-91b2-37be1b8e483e.png">

Raw Find Query with {{Input.text}}:
<img width="1440" alt="Screenshot 2022-08-15 at 6 33 54 PM" src="https://user-images.githubusercontent.com/17562726/184640453-8f1e710a-74b9-4c98-8dcb-830a15d83c85.png">

Find Query with plain string: 
<img width="1440" alt="Screenshot 2022-08-15 at 6 39 20 PM" src="https://user-images.githubusercontent.com/17562726/184641186-5ca7710e-c392-40d6-a1f1-49e9f3e4b5fc.png">

Find Query with {{Input.text}}:
<img width="1440" alt="Screenshot 2022-08-15 at 6 40 24 PM" src="https://user-images.githubusercontent.com/17562726/184641223-e286ef4a-11e4-415e-8694-b9974d2f2af3.png">

 

### Steps To Reproduce

1. Go to MongoDB Atlas and create a new cluster/db/collection
2. Connect the DB on Appsmith 
3. Add some sample data (eg:) `{"id": "1234", "avatar": "hello"}`
4. Add an input widget and prefill the text as "1234"
5. Add a new regular/raw Find query with {"id": "{{Input1.text}}`
6. Notice no results appearing 
7. Replace {{Input1.text}} with plain text value `1234` and notice results appearing 

### Public Sample App

https://app.appsmith.com/app/mongo-find/page1-62fa30dc84757e0c05541b6f

### Version

Cloud

**Comment by pranavkanade** [comment]
Turning off `smart substitution` works, but the query without quotes doesn't work

**Comment by bharath31** [comment]
Looks like expected behavior. Closing this issue.
