### ISSUE TITLE
[Feature]: MsSQL: Implement Get Structure for Microsoft SQL plugin

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#16014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Users would like to generate CRUD pages for Microsoft SQL datasources. A pre-requisite for this is for us to be able to retrieve the DB structure for such datasources.

### Why should this be worked on?

Please refer to [this](https://github.com/appsmithorg/appsmith/issues/8590#issuecomment-1194072709) comment by a user that hints at how we can be achieving this.

**Comment by redone9211** [comment]
I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by sumitsum** [comment]
Hi @redone9211 you may refer to the get structure implementation for MySQL plugin here: https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java#L826 . 

The goal here is to display all the tables in a databse with related information like what columns they have and what keys are defined: 
![Screenshot 2022-09-09 at 12 00 07 PM](https://user-images.githubusercontent.com/1757421/189286057-627e83b6-890e-45c9-bbda-8577a58692c3.png)
