### ISSUE TITLE
[Bug]: Glitchy dropdown on editing permission of members in an organization

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#16018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to change the permissions of multiple users of an organization, the dropdown in most cases just goes away very soon and I'm unable to select the last option in the dropdown.
Sometimes it works well, sometimes it's just very glitchy

### Steps To Reproduce

1. Go to the 'Members' section of an organization
2. Try changing the permission using the dropdown.
[Screen recording reference](https://theappsmith.slack.com/files/U0351QH1Y6N/F03SRQJGCCW/untitled_video_-_screen_recording_-_8_9_2022__8_14_40_pm.webm)
 

### Version

Cloud v1.7.13

**Comment by hiteshjoshi** [comment]
More context : https://app.slack.com/client/TGA9SH07N/C02K2MZERSL

**Comment by hiteshjoshi** [comment]
TDB after new dropdown component.

**Comment by infinitetrooper** [comment]
This was long fixed, closing.
