### ISSUE TITLE
[Bug]Enhancement : Add an Edit icon in the header next to the application name indicating its editable

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1602]
Steps to reproduce:
1) Navigate to home page 
2) Click on the edit option of the application on hover 
3) Observe the header for application name 

Observation :
It is observed that application name does not seem to be editable only a known user can understand that the application name can be edited at the header. 

Expectation
Adding an edit icon close to the application name makes user understand that the application name can be edited inside the application

**Comment by Nikhil-Nandagopal** [comment]
@prapullac thank you for the enhancement request. We've intentionally taken a call not to add this edit icon today. If users still find it difficult, we'll consider bringing it back
