### ISSUE TITLE
[Docs]:  Error R14  - Heroku deployment errors

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16039]
<p>"It was looking that everything works but I am not able to get into the ""settings"" part as an admin. I have a lot of errors in the log some related to the amount of memory and some related to missing files. Any ideas ? <strong>Error R14 </strong>(Memory quota exceeded) - this is one of the errors."</p>

**Comment by jnikhila** [comment]
@sharat87 / @sum35h - Could you please add pointers to help document this?

**Comment by jnikhila** [comment]
Awaiting for a response from @sharat87 / @sum35h

**Comment by sharat87** [comment]
Admin Settings is not supported on Heroku. This is also mentioned in our docs page for Heroku.

Reg. the errors and memory problems, can we get the logs to see what those errors were please? What I think is likely is that they ran out of the free dyno capacity of Heroku and need more already. So they need to upgrade their plan probably. Can't say for certain without more information, including logs, typical user counts, and what their current plan on Heroku is.

Closing for lack of information. Please reopen when we have the information so we can investigate. Thanks.

**Comment by jnikhila** [comment]
@pranavkanade - Please take note of this. CC: @danciaclara
