### ISSUE TITLE
[Docs]: Mongo DB Error: name cannot be null

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16038]
<p><a href="https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100076361">https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100076361</a></p>
<p><p>The MongoDB queries are failing with an exception name that cannot be null.</p></p>

The link below could be helpful:
https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100153137

**Comment by spark-c** [comment]
@danciaclara I've tagged as "Needs more info"

**Comment by spark-c** [comment]
Up for review [here](https://github.com/appsmithorg/appsmith-docs/pull/633.)

**Comment by spark-c** [comment]
Waiting to hear about new changes to **Error Message** property that may require changes in this doc

**Comment by spark-c** [comment]
Info: Holding this merge until [this other PR](https://github.com/appsmithorg/appsmith-docs/pull/561) is merged, which will add a new styling component that will be used in this doc.
