### ISSUE TITLE
[Bug]: Dynamic bindings in chart widget replaces nulls with default values

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#16031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When evaluated values fail validation, we should not replace the value shown in the evaluated value window with the widget defaults. This would throw a user off and leave them unable to debug the source of their issue.

Ref: [Slack thread](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1659624832637009)

### Steps To Reproduce

In the two image below, we see that the evaluated value shows the incorrect default value when the same value is dynamically bound. 
<img width="608" alt="Screenshot 2022-08-16 at 1 36 02 PM" src="https://user-images.githubusercontent.com/5298848/184829741-5dd9adf8-58e5-4982-b24e-dd4c0933c1fe.png">
<img width="590" alt="Screenshot 2022-08-16 at 1 36 15 PM" src="https://user-images.githubusercontent.com/5298848/184829770-28786e85-7825-4296-8646-b8ca49141285.png">

### Version

Cloud

**Comment by bharath31** [comment]
this is no longer reproducible
