### ISSUE TITLE
[Docs]:  Update Query Doc - Add how to read query errors when query fails.

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16043]
<p>User query - <a href="https://discord.com/channels/725602949748752515/760761686549463060/938273022060683327">https://discord.com/channels/725602949748752515/760761686549463060/938273022060683327</a></p>
<p>Display actual error from the datasource/api.</p>

**Comment by spark-c** [comment]
ready for merge pending one more final review
