### ISSUE TITLE
[Enhancement] : Double click  on the widgets to open the property pane 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1604]
Steps to reproduce:
1) Navigate to editor mode of the application 
2) Add a widget 
3) Focus on the name of the widget and click 
and observe the property pane opens 

Observation:
it is observed that the user need to focus to open the property pane and it makes it difficult for a user 

Expectation
Double click on the widget would allow the user to easy the functionality of opening the property pane

**Comment by riodeuno** [comment]
We're working on the single-click approach, which makes this a non-issue.

**Comment by prapullac** [comment]
Closing the issue as per above comment
