### ISSUE TITLE
[Bug]: Last bit of a label is truncated on alignment change

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**This bug exists for all widgets that have a `Label` property.**

When we change the `Alignment` of the label to the right and apply `Italics` to the `Label Font Style`, the last bit of the label gets truncated. 
Even after increasing the width, the label does not get displayed properly.

https://www.loom.com/share/d714fa3cd85949e18aa6bb480e785228

### Steps To Reproduce

1. D&D any widget that has a `Label` property e.g. Input widget.
2. In the property pane right align the label and add italics to it.

**Expected:** The label should be displayed completely and no part of it should be truncated.

### Version

Cloud

**Comment by jsartisan** [comment]
@shadabbuchh @somangshu Let's close this bug as we have removed side label + alignment from the input widget?
