### ISSUE TITLE
[Docs]: Select widget - Server side Filtering

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16048]
<p>Add the sample app and elaborate on the same use case.</p>

**Comment by danciaclara** [comment]
Looks like we have added this section already - https://docs.appsmith.com/reference/widgets/dropdown-1#server-side-filtering

We can also link the Sample App @jnikhila @Pranay105

**Comment by spark-c** [comment]
Asked pranav about status of the sample app since it was a bit confusing without instructions for users

**Comment by danciaclara** [comment]
@spark-c You can add the steps from the video that is on this page. We can add the sample app later on as well

**Comment by spark-c** [comment]
In review [here](https://github.com/appsmithorg/appsmith-docs/pull/592)
