### ISSUE TITLE
[Docs]: Update Troubleshooting - Google Sheets Error

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16055]
<p>Google Sheets Error: Unable to parse range - The user uses Google Sheets as datasource and is not able to run an API, getting the error Unable to parse range. The issue is they used the file name instead of the Sheet name in the API configuration.</p>
<p>User Query - https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100109248#part_id=initial-part-164629100109248-1304241115</p>

**Comment by jnikhila** [comment]
The new feature update has a dro down to select the filename, and so this is no longer needed.
