### ISSUE TITLE
[Docs]: Update - FAQ (Performance and Scalability)

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16052]
<p>User Query - <a href="https://community.appsmith.com/t/performance-scalability/732?u=amongus009">https://community.appsmith.com/t/performance-scalability/732?u=amongus009</a></p>
<p>Add information about Performance and Scalability</p>
<p>Check with Arpit.</p>

**Comment by jnikhila** [comment]
@mohanarpit - Could you please share details for this?

**Comment by danciaclara** [comment]
@mohanarpit  There is some information we added in the Self hosting landing page  for scalability and performance- https://docs.appsmith.com/getting-started/setup#self-hosting-benefits 

If that looks good we can go ahead and close this ticket?
