### ISSUE TITLE
[Docs]: Update MongoDB - custom MongoDB

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#16057]
<p>Connect to external MongoDB with tlsCAFile parameter in connection URL</p>
<p><a href="https://discord.com/channels/725602949748752515/760761686549463060/968873285586681886">https://discord.com/channels/725602949748752515/760761686549463060/968873285586681886</a></p>
<p>One for Docker and one for Kubernetes.</p>

**Comment by jnikhila** [comment]
@sum35h / @sharat87 - Could you please share some pointer so that we can document the same?

**Comment by danciaclara** [comment]
https://community.appsmith.com/t/how-do-i-connect-to-external-mongodb-with-tlscafile-parameter-in-connection-url/1058

**Comment by harshilp24** [comment]
@danciaclara do I have to add this in the Troubleshooting section or in MongoDB docs? cc: @jnikhila
