### ISSUE TITLE
[Bug]: Unbale to use currentRow in Text Color and CellBackgroun Color in Table Widget

### ISSUE THREAD

**Issue by tommar42** [appsmithorg/appsmith#16068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to make so the background colour of cells, will change in a table if they meet certain conditions, but I cannot seem to be able to call currentRow to get the value of cells due to the error "currentRow is not defined" in the Text color and Cell Background color properties of the Table widget.  

I still fairly new to appsmith so there is a chance I may be doing something wrong.

### Steps To Reproduce

1. Create a table Widget
2. Add a Table data to the Widget (I was using google sheets) 
3. Try and use currentRow, in either Text Color or Cell Background Color

### Version

Cloud

**Comment by somangshu** [comment]
@tommar42 I think you are trying to use row level property on a global level property. The `currentRow` prop can only be accessed inside the column settings. 

Am I getting you correctly here?

cc @dilippitchika

**Comment by tommar42** [comment]
@somangshu 

Are yes that's where I went wrong, have it working correctly now.

Thank for your help and sorry about the bug report that turned out not be a bug
