### ISSUE TITLE
[Task]: Update more menu with actual menu-options for audit-logs-v1

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#16065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Need design and product input here. 
- Show more menu options on click.

@vuiets @Debsourabh What are we going to show in the more menu.

Refer: https://github.com/appsmithorg/appsmith/issues/15373

**Comment by IAmAnubhavSaini** [comment]
@vuiets Are we going to hide the more menu for now.

**Comment by vuiets** [comment]
@Debsourabh shall we hide the ellipsis menu since we have just the link to the documentation there, and _Audit Logs_ is self-explanatory and doesn't need documentation.

**Comment by vuiets** [comment]
@IAmAnubhavSaini let's go ahead and remove this since the UI is self-explanatory and easy to understand.

cc @vasanth-appsmith
