### ISSUE TITLE
[Bug]: Selected column values of G Sheets is copied of one API to new created API

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#16077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Selected column values are copied if one G Sheet API is opened and then we create a new API by clicking on entity explorer create new G Sheet API. Then the selected column values for newly API is same as the previously opened which result in error if we select any different SheetName which does not have such column name.

Network request of new action has payload with previous API's projection values : 
<img width="1440" alt="Screenshot 2022-08-17 at 1 40 09 AM" src="https://user-images.githubusercontent.com/7565635/184976011-c65c1820-c0e4-4dd5-bbf7-20120b8327e1.png">

### Steps To Reproduce

https://www.loom.com/share/09132a1606f042069c15fe73957e2c4d

### Public Sample App

https://app.appsmith.com/app/gsheet-rename-error-2/page1-62fbcb0c84757e0c05549b3b

### Version

Both

**Comment by Nikhil-Nandagopal** [comment]
@AmanAgarwal041 is this still an issue?

**Comment by rohan-arthur** [comment]
not reproducible anymore
