### ISSUE TITLE
[Bug]: GraphQL plugin: warning message for duplicate variable names is showing up in two places

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Currently the warning message is showing up both when the GraphQL action is updated and when it is executed. Hence, it shows up twice on the user screen. Need to remove one of them so that the message shows at only one place. 

### Steps To Reproduce

1. In a GraphQL action provide a variable name in the variables editor box and then use the same name in the pagination tab as well. 

### Version

self hosted

**Comment by prapullac** [comment]
verified this on DP
