### ISSUE TITLE
[Bug]: Pagination settings dropdown has some wrong caching

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In [this](http://3.111.33.176/app/graphql-basic/page1-62f9dc05241ba712c63b43e4/edit/api/62fa03fa241ba712c63b43ee) example app, I had (once upon a time) declared a variable with name `lim`. I have since deleted this variable.

Now when I go to the `Pagination` tab of my query, I see that `lim` is pre-selected, and I am also unable to expand the dropdowns. 

Screenshots:
1. This query does not have any variables: 
![Screenshot 2022-08-17 at 13 45 31](https://user-images.githubusercontent.com/94514895/185069477-96eb940c-12cf-4d75-82fc-e2c1a91d57e4.png)

2. But when I go to Pagination tab, I see some old redundant variable from another query being shown here. Also, I am unable to expand the dropdown:
![Screenshot 2022-08-17 at 13 46 23](https://user-images.githubusercontent.com/94514895/185069670-2b5c8134-8041-465d-b90a-07b287858dba.png)

### Steps To Reproduce

explained above

### Version

Cloud

**Comment by rohan-arthur** [comment]
conversation here: https://theappsmith.slack.com/archives/C03HF7YJ6RF/p1660724286119689

**Comment by prapullac** [comment]
Verified on the DP and works well

**Comment by prapullac** [comment]
Verified on the DP
