### ISSUE TITLE
[Bug]: Mustache bracket highlight need to be centered

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Binding suggestion pop-up has mustache bracket highlighted but is not centered

### Steps To Reproduce

Binding suggestion pop-up has mustache bracket highlighted but is not centered

![image](https://user-images.githubusercontent.com/79509062/185079829-e6860c33-a5e8-42af-aeed-9d9c38c5f05f.png)

### Version

Cloud

**Comment by rohitagarwal88** [comment]
Fixed by ADS 2.0 changes.
