### ISSUE TITLE
[Bug]: Date picker's shortcut's accent color is not same as selected Theming color

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#16100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The date picker calendar shortcuts accent color is not changing according to Theming color. It remains same as the older versions default theme i.e blue

![image](https://user-images.githubusercontent.com/95341241/185076949-33ac3c55-9679-40cf-b802-5697477349ed.png)

*Also check same issue for JSONForm date picker field type

### Steps To Reproduce

1. Drag & Drop Date Picker widget
2. Enable 'Show Shortcuts' from property pane
3. Click on date picker widget to open calendar
4. Observe that on shortcuts there is no theming color applied

### Version

Cloud / Production

**Comment by yaldram** [comment]
This issue is not re-producible anymore @chandannkumar can you please verify and close this issue. Thanks

**Comment by chandannkumar** [comment]
Thanks @yaldram, Closing this issue as it seems like already fixed
![image](https://user-images.githubusercontent.com/95341241/199398173-eac549a2-5725-4efd-b605-e2e9cd036bb6.png)
