### ISSUE TITLE
[Bug]: Issue occurring in the URL column of Table widget

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#16108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I define a column type as URL in a table widget, and pass both display and computed URL, the relative path is taken into consideration and not absolute URL.

### Steps To Reproduce

When I set only "Computed Value", on clicking the URL from the table takes me to the correct link (absolute URL).
But when I add the "Display Name" as well, then clicking on the URL takes only the relative path and I land on an incorrect link (relative path).

I have attached a video below about the issue.
https://user-images.githubusercontent.com/5265702/185100492-8a4392d3-3425-48d8-b2f5-31ec943a5620.mov

### Version

1.7.13

**Comment by dilippitchika** [comment]
This doesn't work in table v2 and ends up blocking developers. Bumping the priority to high, @souma-ghosh please pick this as soon as other in progress items are resolved.

@sbalaji1192 not adding in the epic.

**Comment by shadabbuchh** [comment]
The above issue is working fine on release.
https://www.loom.com/share/9f0fe7db66c64608a55d792551b64219
