### ISSUE TITLE
[Bug] Text gets cropped in the text widget even when there is good amount of space

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1610]
Steps to reproduce:
1) Add a text widget
2) Click on the property pane 
3) Enter long text with multiple 
 and observe

Observation:
It is observed that the text gets cropped even when the is enough space 

![Screenshot 2020-11-06 at 4 07 21 PM](https://user-images.githubusercontent.com/71753653/98356933-6dfe8e80-204a-11eb-8445-f8d8d4e3812c.png)

<img width="364" alt="Screen Shot 2020-11-09 at 5 36 48 PM" src="https://user-images.githubusercontent.com/30255708/98539353-3003a380-22b2-11eb-9aea-5b82a026fef8.png">

**Comment by Nikhil-Nandagopal** [comment]
@prapullac can you update the screeenshot, the boundaries are not there so it's not clear where it is getting truncated

**Comment by areyabhishek** [comment]
I updated the issue with another screenshot. See the tails of y and g, they are cut.

**Comment by riodeuno** [comment]
Another scenario reported.

![cropped](https://user-images.githubusercontent.com/103687/113394147-5c30d580-93b5-11eb-951c-5c8bb2cb8476.png)

**Comment by adnanmorsy97** [comment]
Hi @prapullac is this issue still open. I would like to take it :)

**Comment by areyabhishek** [comment]
@adnanmorsy97 Yes this is open. I'll assign it to you :)

**Comment by areyabhishek** [comment]
@adnanmorsy97 Let me know if you are working on this. If so, is there an update for this issue? Thanks!
