### ISSUE TITLE
[Bug]-[800]:Video & TreeSelect widgets not visible in the entity Explorer once sidebar is closed

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Once we click on `Close Sidebar` icon, Video & TreeSelect widgets disappear from the entity explorer.
Note: The widgets appear when we search for them in the search bar but not visible in the list of widgets.

https://www.loom.com/share/9a273f9c5b1544bc9fbbd3ca54bac2c7

### Steps To Reproduce

1. Go to any application.
2. In the Entity explorer click on the Widgets tab.
3. At the bottom you'll see TreeSelect & Video widgets.
4. Now click on the `Close Sidebar` (three lines) icon next to the appsmith icon on the top left corner.
5. Notice that TreeSelect & Video widgets disappear from the widget list

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | 1 |

**Comment by Richarex** [comment]
@akash-codemonk This issue is fixed verified it on DP url:- 
https://appsmith-lcbcd3v4t-get-appsmith.vercel.app/ 
Video & TreeSelect widgets are visible in the entity explorer even when the sidebar is closed.

**Comment by Richarex** [comment]
This is working fine, verified it on release.
