### ISSUE TITLE
[Bug]: my datasource suddenly deletes itself for no reason

### ISSUE THREAD

**Issue by nassim-2000** [appsmithorg/appsmith#16115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello

I was developing, creating MYSQL queries and suddenly my corresponding data source disappeared, and it is not in the list of data sources either. The queries become orphaned, and I have to manually add my database and select the right data source in each query or they won't run.

Thanks.

### Steps To Reproduce

1. go to the query editor
2. Run query sql
3. I have error (..... is not correctly configured. Please fix the following and then re-run: {Unable to find datasource 62fd72d044421e04c7b7d500} 
4. the database disappears

### Version

Docker container / Appsmith v1.7.13

**Comment by Nikhil-Nandagopal** [comment]
@nassim-2000 unfortunately these steps don't help us reproduce the issue on our end. Could you share a video of yourself reproducing this?

**Comment by nassim-2000** [comment]
> @nassim-2000 unfortunately these steps don't help us reproduce the issue on our end. Could you share a video of yourself reproducing this?

I can't predict when the problem will occur, otherwise I could have attached a video to better understand. The problem comes suddenly after 20 attempts as well as after 5 attempts.
