### ISSUE TITLE
[Bug]: While deleting a Datasource "Delete" option is prompted again after we click on "Are you sure"

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For any Datasource that has some actions using it once we click on `Delete` -> `Are you sure?`, we see the `Delete` option again while the datasource is getting deleted.

Ideally we should show the `Delete` option again after we get the `Cannot delete datasource since it has 2 action(s) using it.` message.

https://www.loom.com/share/64cfe152a1bd4e5a9c92d1e0542056e6

### Steps To Reproduce

1. In the `Show all Datasources` page of any application try to delete a datasource that has some actions on it.
2. Notice that the `Delete` option appears again once you  click on `Are you sure?` even before an error message has appeared.

### Version

Cloud

**Comment by Irongade** [comment]
I cannot seem to replicate this bug. @shadabbuchh

**Comment by Irongade** [comment]
I'm not really sure if we should say this is a bug.

**Comment by shadabbuchh** [comment]
> I'm not really sure if we should say this is a bug.

@Irongade as per my understanding this will confuse the customer, as when the `Delete` option appears again before the error message is displayed the customer will try to click on it again. Hence making it a frustrating UX.
What are your thoughts on this?

**Comment by Nikhil-Nandagopal** [comment]
The video shows both happening at the same time, I can't see a lag between the message and the delete changing so I'm closing this
