### ISSUE TITLE
[Bug]-[1568]:Checkbox widget - Label -> Position - On selecting Right, it still remains where it is.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I select the Right option from the Label -> Position property of Checkbox widget, it remains on the left. 
No difference is seen if we select Left or Right. 

Expected behavior - Previously, on selecting Right, the Label text used to be aligned to the right of the widget.

### Steps To Reproduce

1. Drag and drop a checkbox group widget and increase the width of the box.
2. Select the Right option from the Label -> Position property
3. Note that there is no change in the position of the Label text.
<img width="789" alt="Checkbox_labelposition_right" src="https://user-images.githubusercontent.com/101863839/185346412-38117b8b-9ade-4e7b-9625-66ddcbf1d3b3.png">

Earlier behavior -
<img width="702" alt="Screenshot 2022-07-14 at 10 59 25 AM" src="https://user-images.githubusercontent.com/101863839/185346514-1b2487e5-ca2e-429a-979b-d22ba7a3292e.png">

### Version

Release

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 392 |
| Effort (months)  | 0.5 |

**Comment by Sripriya93** [comment]
Working fine now, moving to done

![image](https://user-images.githubusercontent.com/104895602/195525474-e6bf3243-f458-4764-9b85-9c58d6ae8fea.png)
