### ISSUE TITLE
[Docs]: [Rehaul] - Update SSL & Custom Domain

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#16136]
Update the [doc](https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-domain#custom-ssl-certificate). Refer to [slack thread:](https://theappsmith.slack.com/archives/C01CFTXD0N8/p1660743662324069)

**Comment by jnikhila** [comment]
@cokoghenun - Could you please add your points to this ticket? It'll be helpful for us when we rewrite the doc.

**Comment by cokoghenun** [comment]
Sure @jnikhila

**Comment by jnikhila** [comment]
Thanks @cokoghenun.
