### ISSUE TITLE
[Bug]: Form data submission of date field not working with database in YYYY-MM-DD format 

### ISSUE THREAD

**Issue by Constantine9527** [appsmithorg/appsmith#16144]
I have a problem with the widget of DatePicker.

Current Behavior:
Form data submission of date field not working with postgresql in YYYY-MM-DD format . 
App sample in appsmith cloud: https://app.appsmith.com/app/testtablepage/page2-62fdddfe84757e0c05552c65
(It it insert the value ({{DatePicker.formatedDate})) of DatePicker  into users.image field )

I have a DatePicker widget and format is YYYY-MM-DD, but when I insert into database, the value of {{DatePicker.formatedDate}} becomes "YYYY-MM-DD +00",  Does "+00" mean time zone? How can I remove it ?

DatePicker properties: 
![image](https://user-images.githubusercontent.com/20188341/185333624-08fd31cd-57ca-4fbe-83f5-bd098315381a.png)

Insert Sql:
![image](https://user-images.githubusercontent.com/20188341/185333752-5c18796e-4500-4354-a542-3ea5a716d7b3.png)

Data show:
![image](https://user-images.githubusercontent.com/20188341/185521055-7f2764a5-89ff-4a2e-b4f4-fe2f7002de3e.png)

_Originally posted by @Constantine9527 in https://github.com/appsmithorg/appsmith/issues/9462#issuecomment-1219119037_

**Comment by Nikhil-Nandagopal** [comment]
@Constantine9527 this seems to be a bug while using prepared statements where we're trying to infer the data type of the widget. You can turn it off or insert it into a date type field to make it work

**Comment by subrata71** [comment]
Hi @Constantine9527 
What's the data type of that `image` column?

**Comment by Nikhil-Nandagopal** [comment]
@subrata71 it's text. It's our sample users DB

**Comment by subrata71** [comment]
The server identifies the data type as a date. And `preparedStatement.setDate` function adds a timezone offset to it. There's no way we can eliminate adding a timezone offset because the library always does that. In this case, it's recommended to use any `date/timestamp` type instead of string type in the database to store date values.

**Comment by Nikhil-Nandagopal** [comment]
@subrata71 thanks for the information. I think the only solution here is to remove the smart substitution or use it in the correct column type
