### ISSUE TITLE
[Bug]-[116]:On trying to configure snowflake db - no error is thrown if incorrect details are entered.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Snowflake DB -
If I enter any random values in the DB details screen (for account name, warehouse, etc) , and click test - no error is thrown.
The circular progress on Test button just goes on and on, and after 30.1s it just stops on the same screen. It is not clear to the user if the DB connection has been made/ has been tested successfully or if there is an issue.

### Steps To Reproduce

1. Click on new data source and select snowflake.
2. Enter random values in the db details screen. Click Test.

The circular progress on Test button just goes on and on, and after 30.1s it just stops on the same screen. It is not clear to the user if the DB connection has been made/ has been tested successfully or if there is an issue.

Expected behavior - Some information should be given to user on the status of the connection.

### Version

Release

**Comment by rohan-arthur** [comment]
based on 6m usage:

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 58 |
| Effort (months)  | <<number>> |

**Comment by btsgh** [comment]
This is true even for MSSQL DS.
