### ISSUE TITLE
[Bug]:  Autocomplete does not work as expected

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#16141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we use the mustache syntax inside the form fields for MongoDB query `{{}}` the autocomplete does not work as expected. When we hit enter the word is coming outside the mustache braces `{{}}`. 

Please check the recording - https://www.loom.com/share/b7721ca088bd4f2ab5743725349f5a2f

### Steps To Reproduce

1. Navigate to a mongo query.
2. Say for the query field type the mustache syntax and hit enter for the autocomplete

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
@yaldram the same issue will happen in any field if the content is the same
