### ISSUE TITLE
[Docs]: Tutorial for using REST API

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#16148]
The [mix panel](https://mixpanel.com/project/2032485/view/178891/app/dashboards#id=1160693&editor-card-id=%22report-13034407%22) shows that the most popular datasources used by our users is REST API and so it would be helpful for new users to have API as part of [Build Your First App](https://docs.appsmith.com/getting-started/start-building) doc.

**Comment by jnikhila** [comment]
@rohan-arthur - Please add if I've missed anything.

**Comment by danciaclara** [comment]
Maybe we should have two options for users to try out - one for database and one for REST. @jnikhila what do you think?

**Comment by jnikhila** [comment]
Yes that's correct @danciaclara. We have to update the doc to add the REST API steps.
