### ISSUE TITLE
Analytical events for RBAC

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#16152]

**Comment by hiteshjoshi** [comment]
@vuiets do you have any updates on the events for RBAC?

**Comment by vuiets** [comment]
Hey @hiteshjoshi was being proactive about this so added it. Is this blocking the team from moving things to release at the moment?

**Comment by hiteshjoshi** [comment]
@vuiets, the RBAC CE is ready. Analytical tasks will never block the tech team but the product. Please put an ETA for CE.

**Comment by vuiets** [comment]
Sure let me see if I can close it this week.
