### ISSUE TITLE
[Feature]: Custom domains for apps

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#16150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user wants custom domains for their apps

### Why should this be worked on?

OP - https://discord.com/channels/725602949748752515/760761686549463060/1010062136237641758

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5ac24)

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/msg_1eoyc93g) requested this feature.

**Comment by Riyagupta19** [comment]
Hi, requesting this feature as soon as possible so that I can host the application on my custom domain without appsmith opening on my own domain

**Comment by dikshitabm** [comment]
Yes. 
In deployed version I need custom domain and customized Url for my appsmith app.

**Comment by Adarshaparati** [comment]
I need a custom domain add features for each app in appsmith

**Comment by Nikhil-Nandagopal** [comment]
You can have each app in an instance and host every instance on a separate domain. We won't support a single app per instance since we're focused on internal tools
