### ISSUE TITLE
[Feature]: RedHighlight or Asterisk a Required Input field for better UI readability

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#16161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="644" alt="Screenshot 2022-08-19 at 3 07 53 PM" src="https://user-images.githubusercontent.com/91450662/185591022-fa1aa61b-e7a2-4cbd-93a2-853fc9c5b054.png">

### Steps To Reproduce

1. D&D few input fields inside a form widget & make their Required fields `True`
2. Also notice 'Disabled Invalid Forms' of Form widget is enabled
3. Deploy the app
4. **Observe: The form's Submit is disabled due to the fact that inputs are required but there is no visual indication for the user to know the cause of Form disable state at the start**
5. **Expectation: Red highlight around the input or Asterisk should be added once a input is made required as a visual indication**
6. **Also Observe: Write something into the required fields & then remove - now there is red highlight**

### Version

Prod/Release v1.7.13

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_axkcs)

**Comment by jsartisan** [comment]
Closing as this is done in new WDS Input widget ( available under feature flag )
