### ISSUE TITLE
[Bug]: Forking template dropdown UI not consistent

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There seems to be an unusual padding at the end of the `Choose where to fork the template` dropdown.

<img width="809" alt="Screenshot 2022-08-19 at 3 51 56 PM" src="https://user-images.githubusercontent.com/39921438/185619071-11497958-008a-4925-970f-88e1bdf55a43.png">

### Steps To Reproduce

1. Login to the application.
2. Go to the Templates page from the homepage.
3. For any template click on the Fork icon.

### Version

Cloud

**Comment by rahulbarwal** [comment]
![Screenshot 2023-06-12 at 2 44 44 PM](https://github.com/appsmithorg/appsmith/assets/6761673/5d825121-0b71-4650-aef8-62b263b951fb)
Hey @shadabbuchh, with new design system it already looks cleaner. In the newer UI, do you think we still need to change anything?

**Comment by shadabbuchh** [comment]
@rahulbarwal this was raised a year ago. Now with the new changes as you mentioned this issue can be closed.
