### ISSUE TITLE
[Bug]: Select Widget Display Issue on Tablet/Mobile When Opening On-Screen Keyboard

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#16169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When opening the keyboard on a tablet, the Select widget goes off the screen and no selection can be made.

![image](https://user-images.githubusercontent.com/101268423/185696452-039b106e-e803-41c6-ae91-173a4b236060.png)

![image](https://user-images.githubusercontent.com/101268423/185696284-c64b5378-d811-4f0f-8773-63fbe3783935.png)

### Steps To Reproduce

1. Access an app that contains a Select widget on a tablet.
2. Open the keyboard.
3. Note that the Select widget goes off the screen and you are unable to select any option.

### Version

Self-Hosted

**Comment by dilippitchika** [comment]
@dhruvikn triage this one this week. Ideally what we expect from triaging is, giving us a direction on how to fix this problem so that it can be estimated and picked up.

**Comment by dhruvikn** [comment]
Sure, will take a look.

**Comment by AndrzejGrainConnect** [comment]
Any update on this issue, its causing quite a few problems for our sales team.

**Comment by dhruvikn** [comment]
Hi @AndrzejGrainConnect, I'll be picking this up today. I'll keep you posted here. Thanks for your patience.

**Comment by dhruvikn** [comment]
Which browser and OS (plus version) are you using? @ame-appsmith @AndrzejGrainConnect?

**Comment by AndrzejGrainConnect** [comment]
We tested it on Chrome and Edge browsers and the OS was Android 11.

**Comment by dhruvikn** [comment]
One more question, as soon as you close the keyboard, does the select dropdown position itself automatically? @AndrzejGrainConnect

**Comment by AndrzejGrainConnect** [comment]
Yes that's right, when the keyboard is used to search through the dropdown box, the drop down disappears from the screen (As seen in photo 1) when the keyboard is hidden the drop down box returns to its normal state (As seen in picture 2).

**Comment by dhruvikn** [comment]
Hi @AndrzejGrainConnect, I was able to recreate the issue. Looking at the code and how the select widget works, we'll need a bit more time to investigate this. I have scheduled calls with the team for the same. Will keep you posted.

As for now, one workaround for this would be to reposition the select widget to somewhere else, where it is not overflowing to the top. Thanks!

**Comment by AndrzejGrainConnect** [comment]
Unfortunately that is not possible due to the limited space on the tablets, do you have an time-frame when this will be fixed as its heavily impacting our sales operations.

**Comment by dilippitchika** [comment]
Hey @AndrzejGrainConnect not yet, we realised this issue is due to a library we are using and it's a problem with the library. We are still investigating this and unfortunately cannot offer a time frame, hence we asked you to think of an alternative like moving the widget itself for now.

**Comment by dilippitchika** [comment]
Hey @AndrzejGrainConnect are you using server side filtering in your select widget? If not you can replace it with a tree-select widget and this problem should not happen there.

This is a big change for us in the select widget, hence this suggestion.

**Comment by dhruvikn** [comment]
Select
![select](https://user-images.githubusercontent.com/22471214/187872024-22d19bb2-f6ce-449c-bbb8-40ac10a9c3fe.png)

Tree Select
<img width="1312" alt="treeselect" src="https://user-images.githubusercontent.com/22471214/187872050-3c81876f-9eea-436e-89b4-d00190d875f3.png">

cc: @AndrzejGrainConnect @dilippitchika

**Comment by AndrzejGrainConnect** [comment]
Using tree select solves the issue however the filter functionality is quite crucial due to the number of elements in the list. There is a filter for the tree select object however that only highlights the needed field and does not scroll to it. 

Is there a way to make it behave similarly to the standard drop down search ?

**Comment by dhruvikn** [comment]
Hey @AndrzejGrainConnect, filter on both select and tree select works the same. Please take a look. Let me know if I'm missing anything. Thanks

https://user-images.githubusercontent.com/22471214/187896691-3609d320-878a-4d91-9eca-a6bf4fd00990.mp4

**Comment by AndrzejGrainConnect** [comment]
https://user-images.githubusercontent.com/109517299/187898753-f48b8af5-fc72-4ea2-b4ac-3bf22efb9f8b.mp4

Is this another bug , as my tree select menu does not behave like yours

**Comment by dilippitchika** [comment]
@AndrzejGrainConnect we fixed this bug recently, which version of appsmith are you on?

**Comment by AndrzejGrainConnect** [comment]
v1.7.14

**Comment by dilippitchika** [comment]
Ok, we fixed in v1.7.15 which will go live in next few days. Please upgrade once a new version is live.

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal keeping this open as this is still a valid issue in select widget and we suggested to use tree select.
