### ISSUE TITLE
[Bug]: The data looks misaligned inside share modal when the workspace name is too long 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The data looks misaligned inside the share modal when the workspace name is too long 
![image](https://user-images.githubusercontent.com/45958978/185623455-8c4bd7c1-4f20-4dcb-9ba9-d71209e6c32a.png)

### Steps To Reproduce

1. go to the home page
2. add a new workspace
3. Edit the work name space with a long name
4. Now click on share modal
5. now add a new user
6. Now the workspace name looks broken

### Version

https://rbac-release.appsmith.com/applications#62690e1cfbae7b086458424d

**Comment by ankitakinger** [comment]
Fixed in [#14823](https://github.com/appsmithorg/appsmith/pull/14823)
