### ISSUE TITLE
[Bug]: Tab title checks don't run when changing 

### ISSUE THREAD

**Issue by nzidol** [appsmithorg/appsmith#16170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I type a long title into a tab, the tab shows a truncated name without dots:
![image](https://user-images.githubusercontent.com/13618973/185722866-aba7a7f0-2aaa-474c-af1b-841faf1d8d5c.png)
![image](https://user-images.githubusercontent.com/13618973/185722873-46e31a16-fc39-415e-8608-5fc08e87dd07.png)

After a screen refresh the tab shows dots (...) for missing characters
![image](https://user-images.githubusercontent.com/13618973/185722916-c63f7f32-8bac-4b9b-9870-717dc46fb80c.png)
(Nice to have: tab adjustable to text size auto or manual....)

When shortening the title, the tab shows the shortened name with dots, also note there is no error on the "Default Tab"
![image](https://user-images.githubusercontent.com/13618973/185723028-bc97508c-85eb-48a2-b93b-0e25e8529154.png)
![image](https://user-images.githubusercontent.com/13618973/185723210-581df3c1-2558-4a57-be77-916c3c08210f.png)

On page refresh the "Default Tab" shows an error and tab is as expected:
![image](https://user-images.githubusercontent.com/13618973/185723275-83172ce4-7d52-4027-8fcc-bbe4c73fb191.png)
![image](https://user-images.githubusercontent.com/13618973/185723284-f779b11c-c7ab-4652-9823-fa57d4312df0.png)

When correcting the tab name the error on "Default Tab" is not cleared.
![image](https://user-images.githubusercontent.com/13618973/185723627-259f3cd0-4548-44f0-a54d-2dc638122799.png)

### Steps To Reproduce

1. Create new page
2. Add Tab widget
3. Follow steps in description

### Version

Self Hosted 1.7.13

**Comment by dilippitchika** [comment]
Thanks for bringing this to our attention @nzidol.

Both are valid issues and we will pick it up soon. We will soon fix the 1st one. I have linked them to the right issues to be fixed. Thanks.
