### ISSUE TITLE
[Bug]: "app.appsmith.com refused to connect" error is displayed on all the 5 templates

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#16178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when the user clicks on any of the 5 displayed templates this error "app.appsmith.com refused to connect" is shown on the first section of the template.

### Steps To Reproduce

1. Go to url:- https://release.app.appsmith.com/
2. Click on the 'Templates' button
3. Now select any template of your choice from the 5 templates shown below
4. Observe the error message displayed on the template page  
![chrome_ktOiAR8YbZ](https://user-images.githubusercontent.com/93259714/185851578-89c0f802-b151-4f4d-b90f-b4ae569e85ec.png)

### Version

Cloud - 1.7.14

**Comment by kocharrahul7** [comment]
Seems to be a similar issue as [this](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1660921307331549) @sharat87 is that an accurate assessment?

**Comment by kocharrahul7** [comment]
@Richarex This seems to have been closed
