### ISSUE TITLE
[Feature] Select first row as default row in table widget

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#1617]
## Summary

Select the first row as default row in table widget whenever a table widget has been created

## Motivation
Usually there are other widgets that rely on data from the selected row in a table. e.g. I have a canvas where I display user pic and name based on the selected row in table. Now, if I open the app and no row is selected in the table (which was the case till some time back not sure if it has been fixed), no user name or pic can be displayed when the application is opened for the first time. Whereas, if a row is selected by default then I can see some username and pic.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum thank you for opening this! This is a great feature request

**Comment by Nikhil-Nandagopal** [comment]
closing in favor of #1653
