### ISSUE TITLE
[Bug]: Gsheet page displays overlapping UI

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The UI components in the Gsheet page overlap which makes the whole page ugly.
<img width="793" alt="Screenshot 2022-08-22 at 2 41 58 PM" src="https://user-images.githubusercontent.com/39921438/185890890-993e39c9-1e2f-42e6-ac21-2fda7410b889.png">

### Steps To Reproduce

1. Go to any application in this DP: https://appsmith-593huxy6y-get-appsmith.vercel.app/applications.
2. Visit the Gsheet query page.

### Version

Cloud

**Comment by rohan-arthur** [comment]
@shadabbuchh would you please point out the PR that created this DP?

**Comment by shadabbuchh** [comment]
> @shadabbuchh would you please point out the PR that created this DP?

@rohan-arthur here you go:
https://github.com/appsmithorg/appsmith/pull/15892

**Comment by Irongade** [comment]
@shadabbuchh This PR isn't the cause for this behaviour.

**Comment by shadabbuchh** [comment]
> @shadabbuchh This PR isn't the cause for this behaviour. Please remove the AST label

@Irongade not sure about that. Just mentioned this PR as we got the DP link from the same.

**Comment by Irongade** [comment]
@yaldram This is due to the changes you made, kindly fix this. https://github.com/appsmithorg/appsmith/pull/15866

**Comment by yaldram** [comment]
The changes have been reverted @shadabbuchh please verify on release

**Comment by shadabbuchh** [comment]
> The changes have been reverted @shadabbuchh please verify on release

@yaldram this issue was not on Release to begin with. It was on the DP mentioned above. But  now I see it on Release as well.
<img width="1920" alt="Screenshot 2022-08-22 at 6 12 55 PM" src="https://user-images.githubusercontent.com/39921438/185923863-75724036-7a83-4cfb-863e-6a5c65a59fa6.png">

**Comment by yaldram** [comment]
@shadabbuchh give some time it will be resolved.

**Comment by nidhi-nair** [comment]
@shadabbuchh can we close this issue if the changes have been successfully reverted?

**Comment by shadabbuchh** [comment]
Yes, this is working fine on release.
