### ISSUE TITLE
[Bug]: GraphQL: Incorrect bracket pairing during linting

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
In the query window in body tab, the linting of {{ }} is wrong, and I’m not sure why it’s different vs. other editors. If I add double curly braces, the linter assumes that bracket 1 and 3 are a pair and bracket 2 and 4 are a pair.
```
Ref: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1655885054803919?thread_ts=1655821041.009059&cid=CGBPVEJ5C

### Steps To Reproduce

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1655885054803919?thread_ts=1655821041.009059&cid=CGBPVEJ5C

### Version

feature branch DP

**Comment by prapullac** [comment]
Verified on the DP. and it is observed that the Incorrect bracket pairing on selecting the brackets from slash command
