### ISSUE TITLE
[Bug]: GraphQL: fix background color

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
The visual design of the query editor  in body seems inconsistent. Specifically the grey BG behind ‘Query’ and ‘Query Variables’. Screenshot attached.
```
Ref: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1655885054803919?thread_ts=1655821041.009059&cid=CGBPVEJ5C

### Steps To Reproduce

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1655885054803919?thread_ts=1655821041.009059&cid=CGBPVEJ5C

### Version

self hosted

**Comment by prapullac** [comment]
Verified on the DP and works well
