### ISSUE TITLE
[Bug]: GraphQL: slash commands are active in disabled input boxes

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
Slash commands are active even in the disabled input field e.g. pagination tab input fields.
```
Ref: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1655886459059589?thread_ts=1655821041.009059&cid=CGBPVEJ5C

### Steps To Reproduce

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1655886459059589?thread_ts=1655821041.009059&cid=CGBPVEJ5C

### Version

feature branch DP

**Comment by AmanAgarwal041** [comment]
This issue was fixed in the previous PR https://github.com/appsmithorg/appsmith/pull/15028/files#diff-75c609e24bffea3bf79eacaa37b52fdd670d4fcb2302966c64172d43329226f8R234
