### ISSUE TITLE
[Docs] : MongoDB - Support for Serverless MongoDB

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#16181]
Refer [slack](https://theappsmith.slack.com/archives/C02KTH6EHUG/p1661149854009909)

Update MongoDB docs to [add support for serverless MongoDB](https://github.com/appsmithorg/appsmith/issues/9012).

**Comment by jnikhila** [comment]
@sumitsum and @rohan-arthur - Could you please add pointers to the ticket?

**Comment by Pranay105** [comment]
Hey we are closing this ticket, hoping this is just a driver update and it does not need documentation. If otherwise, please reopen this ticket and let us know the information we need to add to the docs. @rohan-arthur

**Comment by meshuamam** [comment]
Unfortunately, MongoDB serverless is still not supported
