### ISSUE TITLE
[Docs]: Table Widget v2.1: Checkbox Column Type Documentation

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#16205]
### Is there an existing issue for this?
Documentation for https://github.com/appsmithorg/appsmith/issues/7338

### Description

We wish to support checkbox as a column type in table

## Link to documentation

https://www.notion.so/appsmith/Table-Widget-Checkbox-column-type-5a8c09ffdc024d39bb8f511c07b403b5

**Comment by dilippitchika** [comment]
@jnikhila @Pranay105 this feature will go live in this week or next week. Please add this to your next sprint. I have already reviewed the document, but it's not structured yet. Would like you to review and let us know how we can structure it better.

**Comment by jnikhila** [comment]
@harshilp24 - Could you please add estimates to the ticket?
