### ISSUE TITLE
[Bug]-[4000]:Response url not encoded in Previous URL & Next URL

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#16202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

API call run fine but when I enter the same url in Next url, throws

java.net.URISyntaxException: Illegal character in query at index 78: https://api.github.com/orgs/appsmithorg/issues?filter=all&state=open&labels=UI Builders Pod&pulls=true&per_page=100&page=2

### Steps To Reproduce

Loom recording
https://www.loom.com/share/9956f599b4764e738790424ff72d8038

### Version

Cloud 1.7.13

**Comment by rohan-arthur** [comment]
REST 6m usage: ~5000
Considering 50% users use pagination: 2500
Of these, assuming 20% users use pagination with response url: 500

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | <<number>> |
