### ISSUE TITLE
[Bug]: JSEditor | Removing the default editor content does not empty the functions dropdown

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#16234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/186122132-6325c762-b5d5-4038-bf2f-f45d724e171e.mov

### Steps To Reproduce

1. Create a new JS object
2. Remove the default content from Editor
3. **Observe : The functions dropdown is still populated & is also able to run successfully**
4. **Expected: If the methods are removed from Editor, JS functions dropdown should show - No functions available & run button be disabled like below**
<img width="338" alt="Screenshot 2022-08-23 at 2 54 12 PM" src="https://user-images.githubusercontent.com/91450662/186122670-099ab6c7-cba5-4ceb-8d81-625c11cb6d1a.png">

### Version

Prod/Release v1.7.14

**Comment by bharath31** [comment]
related to #9585
