### ISSUE TITLE
[Feature]: Lists scrollable without pagination

### ISSUE THREAD

**Issue by lublak** [appsmithorg/appsmith#16231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This is about the List widget. If there are more data than are displayed we can automatically display pagination. There is no possibility here to make a list scrollable which I would prefer.
![image](https://user-images.githubusercontent.com/44057030/186092437-1c6a9290-62f1-4168-b3df-2307c23d32b3.png)

The same may be true for a table. You can deactivate the pagination but this does not allow the complete scrolling of the data.

### Why should this be worked on?

This allows for easy scrolling of a list without the user having to press a button.

**Comment by Nikhil-Nandagopal** [comment]
@lublak thanks for this feature request. We're working on this here #6293
Please drop a comment there

**Comment by lublak** [comment]
@Nikhil-Nandagopal This is more about asynchronous reloading of data with scrolling. For me, the data is already there and nothing is reloaded. It is only about visualization. If it still fits in there I can gladly leave a comment there :)
