### ISSUE TITLE
[Bug]: Table column type date can't change original/display format JS toggle

### ISSUE THREAD

**Issue by disl-pdavid** [appsmithorg/appsmith#16250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Create a table.
Attach to a query that contains a date column.
Change `Column Type` for date column to `Date`.

Change the `Original Date Format` to something, toggle JS (may need to toggle twice).  At that point you cannot turn OFF the JS toggle for either field.

Instead you get a message "Clear the field to toggle back" - **but** I cannot seem to clear the field.

### Steps To Reproduce

See above.

### Public Sample App

https://app.appsmith.com/app/untitled-application-2/page1-6304e8dc22c74318083907e0/edit#xvc42ix5qt

### Version

Cloud

**Comment by dilippitchika** [comment]
Thanks for bringing this to our attention @disl-pdavid, linking this to a similar bug in table widget. Linking it to #14953

**Comment by souma-ghosh** [comment]
> Thanks for bringing this to our attention @disl-pdavid, linking this to a similar bug in table widget. Linking it to #14953

This issue should get resolved when this PR (https://github.com/appsmithorg/appsmith/pull/16733) gets merged. This PR has been raised for the issue(https://github.com/appsmithorg/appsmith/issues/14953) linked above itself.
