### ISSUE TITLE
[Bug]: UI/UX issues in page properties

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below is the list of issues in the "Page Properties" page:
- Icons in Page Properties page do not have a hover state. Refer to the video below.
- The “Not Visible” icon is not a CTA like the other icons.
https://www.loom.com/share/2dde2ef1f7464d2181e56c7a6d5b0c27
- The “General” in the `Page Properties → Settings` pop-up does not look like a section heading. There should be something to differentiate it from rest of the options.
<img width="337" alt="Screenshot 2022-08-24 at 10 54 18 AM" src="https://user-images.githubusercontent.com/39921438/186335907-f7744bcc-3a81-4724-b830-0a8d3e2332a8.png">

- The “Go to page” link add no value in the Page properties page as the page name itself is clickable. Can we remove it?
<img width="175" alt="Screenshot 2022-08-24 at 10 55 18 AM" src="https://user-images.githubusercontent.com/39921438/186336027-f7eba13c-e43d-4cff-9404-8e5fd8dbf6b8.png">

### Steps To Reproduce

1. Go to any application.
2. In the pages section click on the "Page Properties" icon

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
No longer valid in the new IDE
