### ISSUE TITLE
[Bug]: Inaccurate Error Message When Using an Async Function in a Widget Field

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#16258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user used an async function (e.g., `Query1.run()`) in the **Computed value** of the Table widget column. The error message they received is that it is `not a function`, which is not accurate.
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/101268423/186342829-771c5c3d-d68d-4981-ad01-97886d85b1c9.png">

### Steps To Reproduce

1. Add a **Table widget** to the canvas and populate it with data.
2. Use an async function (e.g., `Query1.run()`) in the **Computed value** field of a column.
3. Note the **error message** displayed.

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith this is a Duplicate of #12179 so closing it in favor of that
