### ISSUE TITLE
[Bug]: UI/UX issues in the Entity Explorer

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below is the list of issues in the Entity Explorer:
- The “Page Properties” icon appears to be bigger in size when compare with the “Add a new page” icon.
<img width="253" alt="Screenshot 2022-08-24 at 10 43 32 AM" src="https://user-images.githubusercontent.com/39921438/186334456-4348aef3-4b79-401b-bd25-73d4a0358354.png">

- The page icon next to the page names does not look like a page rather looks like an application.
<img width="82" alt="Screenshot 2022-08-24 at 10 44 09 AM" src="https://user-images.githubusercontent.com/39921438/186334536-b9e41360-39a8-4b63-a138-e22f5f01d7b5.png">

- No tooltip is displayed when the “Page Properties” is highlighted. The tooltip only appears when the cursor is on top of the actual icon.
<img width="335" alt="Screenshot 2022-08-24 at 10 46 27 AM" src="https://user-images.githubusercontent.com/39921438/186334842-4d8133e7-daba-4e9b-89ec-2c72286a3823.png">

- The “No widget/query/JS to display” font size is inconsistent. It is smaller than the “Schema not available” font.
<img width="261" alt="Screenshot 2022-08-24 at 10 44 48 AM" src="https://user-images.githubusercontent.com/39921438/186334749-579dc22a-48ca-48ce-b104-1d169c2a099c.png">

### Steps To Reproduce

- Go to any application.
- Visit the Entity Explorer.

### Version

Cloud

**Comment by kocharrahul7** [comment]
The layout of the Entity explorer has changed significantly, and most of these are no longer valid. We will conduct a new design audit to validate layouts again
