### ISSUE TITLE
[Feature]: Reformatting the response of the JS editor to make it slightly more readable

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#16260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In JSObjects, when I run a function, and then navigate to a different function, there is no clear indicator for which functions response I am looking at.

https://user-images.githubusercontent.com/20532920/186356605-e686948a-6774-4db8-b38d-66220436d9d1.mov

This could cause confusion for users who are testing multiple functions, or have one function calling another.

It would be great to have the response formatted like: `myFun1: <return of myFun1>` or something similar to indicate which functions return statement you are looking at

### Why should this be worked on?

In JSObjects, when I run a function, and then navigate to a different function, there is no clear indicator for which functions response I am looking at.

**Comment by rohan-arthur** [comment]
not planned - we will relook at the debugger in the near future as part of the IDE pod roadmap
