### ISSUE TITLE
[Bug]-[3000]:Mongo | Query Editor | Enable one way switching from Form based & Raw command

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#16269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/186385886-9b4c3ae5-9f16-46b8-8bd8-46395ef654c2.mov

### Steps To Reproduce

1. Create a query on Mongo DS
2. Select & fill any of the following Mongo commands
<img width="314" alt="Screenshot 2022-08-24 at 3 14 05 PM" src="https://user-images.githubusercontent.com/91450662/186386855-643fa128-d142-4bcf-b5c5-28b40463d2fa.png">

3. Now convert the same to Raw format 
4. **Observe: The default template is seen & not the latest collection/command user tried to convert on**
5. **Expected: Templates to stay for new user & the one way conversion from any of above Form commands to Raw also should work as expected**
 

### Version

Prod/Release v1.7.13

**Comment by rohan-arthur** [comment]
mongo 6m usage: 1500
This is a core experience to writing mongo queries, so applying 50% reach: 750

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 750 |
| Effort (months)  | <<number>> |

**Comment by prapullac** [comment]
Tested on the local and seems to be working well
