### ISSUE TITLE
[Docs]: Snowflake db - Some additional details / screenshots to help ease out snowflake db datasource creation in appsmith

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/datasources/querying-snowflake-db

### Describe the problem

Though the above documentation link points to the Snowflake documentation to add details specific to account name, warehouse etc., some quick screenshots and pointers to quickly help the user setup the datasource would be appreciated.

### Describe the improvement

After creating a Sample database on the Snowflake page, using either azure or aws, or any that suits you, sign in to the snowflake account using your login details to find out various details of the existing sample database you can connect to. Here are some example pointers as to where you can find the required details that you would need to enter into the Appsmith Snowflake datasource page.

**Account Name*: gv14678.central-india.azure**

<img width="870" alt="Snowflake_Accountname" src="https://user-images.githubusercontent.com/101863839/186373091-c0a2a029-1186-4ef9-9dbd-6a41069dedf7.png">

**Warehouse - COMPUTE_WH**
[Go to the Admin link on the left panel in Snowflake, and on the top right you will see the ware house name.]

<img width="1421" alt="Snowflake_Warehouse" src="https://user-images.githubusercontent.com/101863839/186373017-472907a3-9a93-478b-a2e6-23f77e10ccd8.png">

**Database - SNOWFLAKE_SAMPLE_DATA**
[Go to the Data link on the left panel, and you will see the databases details appear on the right panel. ]

<img width="858" alt="Snowflake_Database" src="https://user-images.githubusercontent.com/101863839/186373677-9817a40c-a9d2-41a9-a8d9-f18cae87ab01.png">

**Default Schema - TPCDS_SF100TCL**
[Click on the database name]

**Role - ACCOUNTADMIN** 

<img width="947" alt="Snowflake_Schema_Role" src="https://user-images.githubusercontent.com/101863839/186373995-61b9f8d7-4649-480a-9f82-165140d2e149.png">

Finally, the authentication details can be entered as per the user's login details into snowflake, to Test and Save establish the connection.

**Comment by pranavkanade** [comment]
This could be useful - https://www.notion.so/appsmith/Snowflake-af8c74f885834e3a900adb5cfb9c3cf9
