### ISSUE TITLE
[Bug]: "Events" dropdown(s) positioning does not fit the screen when collapsing sections in the Property pane

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we collapse the section above the Events section for a widget and then click on any dropdown in the Events section, it does not fit the screen. 

https://www.loom.com/share/8270800c3a3b4882a51b84267f8b7b87

### Steps To Reproduce

1. Go to any application.
2. D&D a widget and collapse all the section(s) above the "Events" section.
3. Now click on any dropdown in the Events section.

### Version

Cloud

**Comment by Sripriya93** [comment]
Have verified all the widgets collapsing other properties. Marking as verified.
