### ISSUE TITLE
[Docs]: Protected branches in GIT Sync flow

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#16270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/advanced-concepts/version-control-with-git

### Describe the problem

Need documentation on how to control or restrict merges to master.

### Describe the improvement

I understand that making a branch as protected is the way to go about it. But need clarity on what all providers allow this other than Github.

Also more information around this scenario when a branch is protected, how is it expected for Appsmith user to be connected to their Github account to allow merges.

And details with respective to other providers as well.

**Comment by Pranay105** [comment]
@vuiets Need your help in adding this to docs.

**Comment by jnikhila** [comment]
@ginilpg - Could someone please help here?
