### ISSUE TITLE
[Bug] Shareable links appears to be broken

### ISSUE THREAD

**Issue by AdityaAnand1** [appsmithorg/appsmith#1627]
## Description
![image](https://user-images.githubusercontent.com/13274079/98439446-eed78c00-2117-11eb-9dc0-980faa0e1194.png)
I think this should probably be replaced by the actual page id?

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Went to the default template application tracker
2. Click on 'Share'
3. Click on copy and I got a link that appears to include `:pageId`
4. (See screenshot)

(I signed up pretty early on, perhaps an update may have broken sharing for templates that were initialized a while ago?)

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser chrome latest

**Comment by Nikhil-Nandagopal** [comment]
@AdityaAnand1 thank you for reporting this!
