### ISSUE TITLE
[Bug]: existing mysql queries fail with MySqlConnectionException

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two users reported this issue today:
[here](https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100161495) and [here](https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100145140)

![image (1)](https://user-images.githubusercontent.com/94514895/186403967-79acc0b7-91da-406d-8733-a2b846a1bdd2.png)

[This](https://docs.appsmith.com/help-and-support/troubleshooting-guide/action-errors/mysql-plugin-errors) could be a clue to fix the issue, but the error should ideally not occur for existing running queries.

### Steps To Reproduce

not sure, I was not able to reproduce this

### Version

Cloud

**Comment by rohan-arthur** [comment]
@sumitsum wasn't this fixed recently in another issue?

**Comment by sumitsum** [comment]
@rohan-arthur it is possible that we may have regressed somewhere.

**Comment by sribalajig** [comment]
Since we have changed our driver for MySQL, this error no longer occurs. Verified on Mixpanel.

**Comment by sribalajig** [comment]
Since we have changed our driver for MySQL, this error no longer occurs. Verified on Mixpanel.
