### ISSUE TITLE
[Bug]: Auto-complete does not work when multiple bindings exists on the same line

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to use a binding in an INSERT statement of Snowflake DB, though the widgets already exist on the page, the Autocomplete does not work to complete the widget names and action. 

### Steps To Reproduce

Create a snowflake datasource and create an INSERT query to the same. 

Refer following video to reproduce:
https://www.loom.com/share/91a7957ccc0b45c295685eb8faf388f2

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
@btsgh I don't think this will be snowflake specific. Can you verify whether this is happening in other plugins too?

**Comment by Rishabh-Rathod** [comment]
@Nikhil-Nandagopal Yes, this is not specific to the snowflake. It is for all the cases where multiple bindings are present in the same line. for eg: `{{Text.text}} ABC {{Input1.text}}`

This PR https://github.com/appsmithorg/appsmith/pull/16314 has fixed the new logic which missed this case.
