### ISSUE TITLE
[Bug]-[936]:SAML login fails with invalid request

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#16285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While trying to login, the user sees Invalid Request post successful authentication on the IdP.
Keycloak logs contain the error : 
"missing_required_destination"

### Steps To Reproduce

Trying to reproduce the issue. Will add the steps post reproduction.

### Version

EE Self Hosted

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 78 |
| Effort (months)  | 0.25 |

Estimating the time to fix and test this as one person-week. Please feel free to suggest a change.

**Comment by hiteshjoshi** [comment]
Fixed by changing user configurations. Doesn't require a code change.
