### ISSUE TITLE
[Docs]: [Rehaul]- Docker

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#16298]

**Comment by jnikhila** [comment]
@harshilp24 - Could you please add estimates to the ticket?

**Comment by spark-c** [comment]
PR is waiting on review, available [here](https://github.com/appsmithorg/appsmith-docs/pull/547)

**Comment by spark-c** [comment]
Will make test/video showing steps ASAP

**Comment by spark-c** [comment]
(In final reviews)

**Comment by spark-c** [comment]
Ready to merge once Nikhila is back and able to mark her changes as resolved.

**Comment by jnikhila** [comment]
@spark-c - Good to go. Approved the PR.
