### ISSUE TITLE
[Epic]: Git - Stable Release

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#16290]
The goal of this epic is to bring Git Version Control **out of Beta**. It will focus on closing stability issues, improving readability, and merge conflict resolution. 

More details on this [Notion page](https://www.notion.so/appsmith/Git-Stable-Release-42213ec073694c1490bb2ef9b6e12de7).

**Comment by hiteshjoshi** [comment]
Does this require any code change apart from removing the "beta" tag/placeholder etc., from the front end?

Also, we will need to work on some of these bugs for Git sync before calling it stable. 

https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Git+Version+Control%22++label%3A%22Bug%22

**Comment by IAmAnubhavSaini** [comment]
This requires some code changes. We should do it when there are no head-scratching bugs/issues in git.

A few are: 
- discard api throwing 5xx or 4xx error and UI not handling it.
- git BE implementation around locks.
- handling migration changes
- having force-pull, reset to earlier commit, reset to remote branch etc features.
- other open minor issues like Hitesh mentioned above.

I'd say we are stuck with it for a while.
