### ISSUE TITLE
[Docs]: [Rehaul]- Self Hosting

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#16296]

**Comment by jnikhila** [comment]
The outline for the ticket is finalized.

**Comment by jnikhila** [comment]
For peer and tech review raised a[ pull request](https://github.com/appsmithorg/appsmith-docs/pull/443).

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/getting-started/setup).
