### ISSUE TITLE
[Docs]: console logs feature documentation

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#16291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://www.notion.so/appsmith/Console-API-d118f5a0fccb401eb30165c90c9990b3

### Describe the problem

We are adding the new console log feature to our platform. This issue is to track the documentation for the same.

### Describe the improvement

This is a new feature so we will need to add the documentation for the same.

**Comment by jnikhila** [comment]
@ayushpahwa / @rohan-arthur - The initial draft is pushed for review.

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/reference/appsmith-framework/console-object).
