### ISSUE TITLE
[Bug]: When the widget is dropped on the canvas, max-height is less than minimum height (it’s 0) - it should be something else

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the widget is dropped on the canvas, max-height is less than minimum height (it’s 0) - it should be something else (Reported by @momcilo-appsmith )

### Steps To Reproduce

N/A

### Version

Cloud

**Comment by Sripriya93** [comment]
Have checked all the widgets with Dynamic height, all widgets are having a default Max height greater than the default Min height, Moving to done.
