### ISSUE TITLE
[Bug]: When minimum height is expanded to be larger than actual height, the actual height should change but it doesn’t

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When minimum height is expanded to be larger than actual height, the actual height should change but it doesn’t. (Reported by @momcilo-appsmith )

### Steps To Reproduce

N/A

### Version

Cloud

**Comment by Sripriya93** [comment]
When minimum height is expanded to be larger than the actual height for below widgets, the actual height is not changing

1) Container 
2) Form 
3) JSON form
4) Tabs

Which one is the right way to get expanded, Currency widget or the Date picker widget
Currency Input (Input, Phone input) 
Date picker (Multi tree select, Multi select, Select, Tree select)
![image](https://user-images.githubusercontent.com/104895602/188124443-7a8656bb-f228-4bf1-8bb0-25222a581712.png)

Moving issue to In progress.
