### ISSUE TITLE
[Bug]: Minimum height is 2 rows when the widget is dropped on the canvas, even though it can’t be less than 4

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Minimum height is 2 rows when the widget is dropped on the canvas, even though it can’t be less than 4 (reported by @mom)

### Steps To Reproduce

N/A

### Version

Cloud

**Comment by ankurrsinghal** [comment]
@momcilo-appsmith Why it can't be less than 4?

**Comment by momcilo-appsmith** [comment]
4 rows is today's minimum height for widgets. @riodeuno can confirm.

**Comment by riodeuno** [comment]
@ankurrsinghal Please share the original issue which lead us to make the minimum 2 rows.
