### ISSUE TITLE
[Feature]: Import and Export Application to Database directly 

### ISSUE THREAD

**Issue by Irongade** [appsmithorg/appsmith#16313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Instead of only Importing and Exporting apps by downloading them locally, Users want to be able to export apps to any database of their choice.

### Why should this be worked on?

This is an interesting request to think about, We need to triage if this is something we want to work on or not.

Reference to the conversation can be found here: https://discord.com/channels/725602949748752515/1012227463457288242

**Comment by Nikhil-Nandagopal** [comment]
We'll solve this as CI/CD  git integration
