### ISSUE TITLE
[Bug]: When the two are overlapping, the border of one of them is moved to the right for about 10px

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the two are overlapping, the border of one of them is moved to the right for about 10px (reported by @momcilo-appsmith )

### Steps To Reproduce

N/A

### Version

Cloud

**Comment by Sripriya93** [comment]
Working fine moving to done.
