### ISSUE TITLE
Update name when change the displayName action - Saas Manager App

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#16316]
When updating the displayName of an action, the name is not changed and remains the same as when it was created. 

### Steps to reproduce:
1. Open Saas Integration Manager
2. Choose a datasource test
3. Change the displayName of an action and then click  save
4. You can see that name is not updated. 

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/b67d0643-981e-4a68-9ecd-530e36103ce4)

**Comment by rohan-arthur** [comment]
not our focus for the foreseeable future, will get around to this at a later time.
