### ISSUE TITLE
[Bug]: Currency Input widget - Label - Left, Auto Height - Long label. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Step 1: Drag and drop a Currency input widget
Step 2: Change the Height from Fixed to Auto height
Step 3: Enter a long text in the Label and observe

The text gets truncated, and the height remains unchanged. 

As a user, I would want to see the text getting expanded and height increasing.

**Comment by ankurrsinghal** [comment]
@momcilo-appsmith @riodeuno @rohitagarwal88 We never talked about this edge case where the label is long but aligned left.

**Comment by ankurrsinghal** [comment]
Please see the fix here, https://appsmith-git-feat-label-auto-height-get-appsmith.vercel.app/

**Comment by Sripriya93** [comment]
Please check the loom video. We are still facing issues with the given steps.

https://images.zenhubusercontent.com/275993885/8dd18fb6-fccf-460b-af94-04acb3d59da6/untitled_application_4___editor___appsmith___21_september_2022.mp4
