### ISSUE TITLE
[Bug]: Unable to Configure Super User Directly in the docker.env File

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#16324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The implementation of making **super users** works only when changed via the **Admin Settings** page but not if it was directly changed in the `docker.env` file.

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100161174#part_id=initial-part-164629100161174-1413541376

### Steps To Reproduce

1. Configure the super user directly in the docker.env file.
2. Restart the instance.
3. The changes do not take effect.

### Version

Self-Hosted

**Comment by trishaanand** [comment]
Picking this up because it would become a blocker for RBAC to be tagged post promotion.

**Comment by yatinappsmith** [comment]
@RakshaKShetty can you verify this one?
