### ISSUE TITLE
[Bug]: Java properties for proxy not working as expected.

### ISSUE THREAD

**Issue by manikumarnune123** [appsmithorg/appsmith#16330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. The system proxy is not working when the trailing slash is configured in the http_proxy or https_proxy.

2. There were no fields for proxy username and proxy password.

3. NO_PROXY is not working for the CIDR range for example (`10.*.*.*`) or (`10.171.49.0/24`), even not working if the domain name is specified like `.example.com`.

### Steps To Reproduce

1. Configure the docker http_proxy and https_proxy with a trailing slash.
2. Configure the NO_PROXY with an IP.
3. Now run the appsmith container with proxy environment variables. 
4. Log in to appsmith and create a data source API that is behind the proxy.

The below image is for the NO_PROXY reference 

![image](https://user-images.githubusercontent.com/65438060/186879315-08790c71-bbb4-43c1-a0f9-4cbaab0cb68f.png)

The below image is for http_proxy and https_proxy with trailing slash.
![Proxy slash](https://user-images.githubusercontent.com/65438060/186879395-e2a88f1a-49da-48d8-95ec-8c52e4434918.png)

The reference implementation for NO_PROXY and proxyUser and proxyPassword.

### Version

1.7.11

**Comment by Nikhil-Nandagopal** [comment]
@manikumarnune123 are you running appsmith using docker or from source?

**Comment by manikumarnune123** [comment]
@Nikhil-Nandagopal Docker

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 any idea what is happening here?
