### ISSUE TITLE
[Bug]: Twilio not appearing in the filter list in the templates tab.

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#16334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="841" alt="bug" src="https://user-images.githubusercontent.com/67054171/186893057-65097099-164e-46fd-a8c3-98b351efa86d.png">

Although twillio is added to the datasource list of the template, it isn't appearing in the list of filters.

### Steps To Reproduce

1. Add a new template with twilio as a datasource.
2. Go to the templates tab and see that the template is present, but the twilio datasource isn't in the filter list.

More context:  https://theappsmith.slack.com/archives/C02RCR2PURZ/p1660912771736459

### Version

Cloud

**Comment by Richarex** [comment]
As informed by @akash-codemonk it is hard to test until a template which has this datasource is there. So closing this as per discussion.
