### ISSUE TITLE
[Bug]: Renaming a button group bound to appsmith store, the key is also renamed

### ISSUE THREAD

**Issue by phangs** [appsmithorg/appsmith#16354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created a button group to use as a page navigation control, I bound the visibility of the buttons based on an appsmith store key, based on the youtube video tutorials by adding this JS to the Visibility settings of the buttons:

Widget Name: Menu
Appsmith Store Key: Menu
JS Added to Button Visibility Settings: `{{appsmith.store.Menu.includes("Profile")}}`

After doing this, everything is working fine, specific buttons are hidden as expected. Then I decided to rename the button group widget, bugs where detected and I found out that the JS I have added to each button were modified as well when I changed the name of the widget to :

New Widget Name: MainMenu
Appsmith Store Key: Menu
Appsmith Modified JS: `{{appsmith.store.MainMenu.includes("Profile")}}`

I think appsmith mistakenly changed the JS code as well after I have changed the widget's name even though I did not changed the Key in the appsmith store.

### Steps To Reproduce

1. Create button group, name it Menu
2. Create an appsmith store entry as: 
 ```
const menu = ["Home", "Profile", "Reports", "Live" , "Operate Arena" , "Clients", "Settings", "Logout"];
	await storeValue("Menu", menu);
```
3. Bind the visibility setting to the appsmith store key "Menu"
`{{appsmith.store.Menu.includes("Home")}}`
4. Rename the button group widget to MainMenu
5. The binding of the visibility setting for each button group item is changed to :
`{{appsmith.store.MainMenu.includes("Home")}}`

### Version

Self-hosted v1.7.14

**Comment by Nikhil-Nandagopal** [comment]
@phangs thanks for reporting this. You are indeed correct about this issue. We have this issue tracked here #2098
