### ISSUE TITLE
[Bug]: rgba colours do not get applied correctly in Table widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When colours in the form of `rgba(0,0,0,0)` are applied to the cell background of the table widget, we can see it does not get applied uniformly.
https://www.loom.com/share/f0e91b9cfa4b4fcebc785117732fe9ba

<img width="1565" alt="Screenshot 2022-08-29 at 10 22 28 AM" src="https://user-images.githubusercontent.com/39921438/187125620-6310984d-aecb-4402-a9c3-ec62ba8f5459.png">

### Steps To Reproduce

1. D&D a table widget.
2. For `Cell Background Color` property add any colour in the `rgba(0,0,0,0)` format.

### Version

Cloud

**Comment by dilippitchika** [comment]
The problem is not visible when the data is already added to the table. @shadabbuchh can you show an example with real user data on table v2?

**Comment by shadabbuchh** [comment]
> The problem is not visible when the data is already added to the table. @shadabbuchh can you show an example with real user data on table v2?

@dilippitchika the issue seems to be resolved now. I am not able to reproduce it as on today.
