### ISSUE TITLE
[Bug] UI : Improve the design for datatype of 'Time' in Table

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1635]
Steps to reproduce:
1) Add a table 
2) Click on the action of the table header 
3) Now select the Date as datatype
and observe the dropdown 

Observation:
It is observed that the user is unable to distinguish between the format of the date input and output 

Expectation:
the expectation of making it more applying and user can identify the formats better 
![Screenshot 2020-11-09 at 9 13 21 AM](https://user-images.githubusercontent.com/71753653/98500730-3aeb1380-2273-11eb-9ce7-31a62b0f7b28.png)

**Comment by Debsourabh** [comment]
Adjusting Visual Contrast will help differentiate between the two.

Change the background for the header to #D3DEE3 and change text font-weight to 600.

![Capture3a](https://user-images.githubusercontent.com/34486435/100732295-8ae07480-33f2-11eb-84aa-bde379ab6e62.PNG)

**Comment by rishabhsaxena** [comment]
@Debsourabh 
Just to confirm if I got the expected change to be implemented:

Update color to `#D3DEE3` for non-selectable options in general
Update font-weight specifically for `Date Input Format` option
