### ISSUE TITLE
[Bug]: Issues in MultiTreeSelct widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two issues are happening with the MultiTreeSelect widget in release:

1. The `selectedOptionLabels` displays the values of the selected options instead of the labels.
2. On binding it with a Text widget using: `{{MultiTreeSelect1.selectedOptionLabels}}` when we clear all the selected options, the Text widget still displays the labels.

**Note:**

This happens when there is a Default Value mentioned for the TreeSelect widget.
This is happening only in release and not in Prod.

https://www.loom.com/share/8e6e11471fe2409fb786d556db0292e9

### Steps To Reproduce

1. D&D MultiTreeSelect & Text widgets.
2. Bind the Text widget to the MultiTreeSelect widget such that the Text property of the Text widget is {{MultiTreeSelect1.selectedOptionLabels}}.
4. Now clear the selected option in the TreeSelect widget.

**Expected:** The text in the Text widget should also disappear.

### Version

Cloud

**Comment by Aishwarya-U-R** [comment]
Similar to - [[Bug]: TreeSelect | Unable to capture right Label data OnPageLoad (first load) #15466](https://github.com/appsmithorg/appsmith/issues/15466)

**Comment by shadabbuchh** [comment]
This issue is still prevalent on `Release` hence reopening it.
https://www.loom.com/share/fe3c81a6add84e88b849fd489816fe28

**Comment by dilippitchika** [comment]
@Tooluloope can you check if the code was merged properly?

**Comment by Tooluloope** [comment]
Yeah, I'm currently checking.
Cos the deploy Preview, works well

**Comment by Tooluloope** [comment]
Fixed already, in https://github.com/appsmithorg/appsmith/pull/16401
