### ISSUE TITLE
[Bug]: "selectedOptionValue" in TreeSelect widget does not work as expected

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even when we clear the selected option in a TreeSelect widget, the value of the same is still stored.

**Note:** 

1. This happens when there is a `Default Value` mentioned for the TreeSelect widget.
2. This is happening only in release and not in Prod.

https://www.loom.com/share/efbfe26332a948f5b9d63917229b8e25

### Steps To Reproduce

1. D&D TreeSelect & Text widgets.
3. Bind the Text widget to the TreeSelect widget such that the `Text` property of the Text widget is `{{TreeSelect1.selectedOptionValue}}`.
4. Now clear the selected option in the TreeSelect widget.

**Expected:** The text in the Text widget should also disappear. 

### Version

Cloud

**Comment by shadabbuchh** [comment]
This issue is still prevalent on `Release` hence reopening it.
https://www.loom.com/share/b82061c625904198a7292c7dd890a42a

**Comment by Tooluloope** [comment]
Fixed already, in https://github.com/appsmithorg/appsmith/pull/16401
