### ISSUE TITLE
[Bug]: Improve performance of function run on the editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently running a function on the editor on release takes slightly more time than it does on prod. This needs to be improved. Console implementation also causes a slow execution on it's DP and has the potential to further slow down the editor

https://www.loom.com/share/31f39247e2cb495ba39dffad08b3a689

### Steps To Reproduce

1. Execute function3 on [app on release](https://release.app.appsmith.com/app/automation-test-cases/page-1-62c6b8c60721a64d32ce5e09/edit/jsObjects/630cb8c7d982454fd2dafcbb?editName=false) and [app on prod](https://app.appsmith.com/app/whatsapp-messenger/page1-6304ddb4b189ad45f609d796/edit/jsObjects/630c9b1b8faf1771c76bc102)

### Version

Cloud

**Comment by somangshu** [comment]
cc @SatishGandham point this out there, are we able to see in this in our perf infra

**Comment by ohansFavour** [comment]
Hi @ramsaptami , from the video you shared, you're executing a query in production and an Api in release. Since these two are different, the difference in time could result from the difference in execution time for the Query and Api.
We've observed a performance dip in release, which is fixed [here](https://github.com/appsmithorg/appsmith/pull/16406), however, this fix will not affect the execution time of the JS function in any way.

**Comment by ramsaptami** [comment]
Even with the same API, there's only a marginal difference in performance, though a step in the right direction for speed. But as I mentioned it on call the other day, think this is more to do with a combination of features that's lead to a cumulative slowdown

**Comment by Rishabh-Rathod** [comment]
@ramsaptami 
> there's only a marginal difference in performance?

Do you mean after merging this PR current release is still slow when compared to production?

Can we please try to test without hitting external API which could have its own deviation? 

To test the function execution between release vs production, i did a test where we ran a function
```js
export default {
	function3: async () => {
		return storeValue('response', 1).then(() => 
			      storeValue('response', 2).then(
                                   () => storeValue('response', 3)
                                )
)
	},
}
```

Evaluations logs 

| Production  | PR |
|--|--|
| ![SCR-20220831-l5i](https://user-images.githubusercontent.com/23132741/187809728-d150beb7-a797-4265-a518-d763220359d3.png)  | ![SCR-20220831-lbc](https://user-images.githubusercontent.com/23132741/187809732-9290f935-55bf-4adf-b13c-9fe976202185.png) |

**Comment by ramsaptami** [comment]
@Rishabh-Rathod apologies for not being clear, I meant to say that release is faster now that the PR is merged but compared to prod, it's marginally faster, not significant. Favour mentioned performance difference is more obvious on larger apps and I've QA'd on template apps and a medium-sized app only
