### ISSUE TITLE
[Bug]: PhoneInput | Properties pane | CountryCode search text is white

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#16374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/187193674-b88ff0a5-8501-4fd0-9d9c-824fd9cabb55.mov

### Steps To Reproduce

1. DragDrop a PhoneInput widget
2. Open properties pane & filter for different country code
3. **Observe : Search text is white**
4. **Expected: Search text should be visible to the user**
5. Search for "United" & observe multiple search results
6. **Observe: Type "space" to refine the filter further & see that search pop-up closes**
7. **Expected: User should be able to search for multiple words also**

### Version

Release v1.7.15

**Comment by shadabbuchh** [comment]
Same behaviour is prevalent in Currency Input widget as well.

**Comment by yaldram** [comment]
The color issue is due to some changes done in the `design-systems` repo

**Comment by Aishwarya-U-R** [comment]
Phone & Currency inputs are verified for working fine in Release.
<img width="740" alt="Screenshot 2022-08-30 at 2 07 48 PM" src="https://user-images.githubusercontent.com/91450662/187390573-991062a0-b628-4bac-a408-ba8fb32907f4.png">
<img width="718" alt="Screenshot 2022-08-30 at 2 08 19 PM" src="https://user-images.githubusercontent.com/91450662/187390689-89cf4e52-466b-4251-894c-206f7c8578b0.png">
