### ISSUE TITLE
[Bug] Renaming datasources is renaming multiple sources

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1637]
## Description

When I try to rename a datasource for a given plugin, all other datasources for that plugin get renamed.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to the Appsmith editor
2. Choose a plugin & create multiple datasources for that plugin
3. Rename one of the datasources. Notice that other datasources for that given plugin are also renamed.

### Important Details
 - Version: [Self-Hosted]
 - OS: [MacOSX]
 - Browser: Firefox

### Reference Video
https://www.loom.com/share/a7b29f396e104faaab63071d8197ab2e

**Comment by jsartisan** [comment]
@mohanarpit Can you check if this is still happening? We recently pushed a fix related to widget names that fixed this one. You should see an error like this - 

<img width="877" alt="Screenshot 2020-12-03 at 12 54 13 PM" src="https://user-images.githubusercontent.com/6636360/100977319-d320a380-3566-11eb-8ec4-b318098a5bcc.png">

**Comment by jsartisan** [comment]
![1](https://user-images.githubusercontent.com/6636360/100978875-ff3d2400-3568-11eb-8524-95cd2992acf6.gif)

@mohanarpit I just checked this. Not happening on my side. Can you check if this is still happening?

**Comment by mohanarpit** [comment]
This is no longer happening for me. I can see the bug you mentioned where the name doesn't reflect in the entity explorer. Can you open a separate issue for that? We'll resolve that separately.
