### ISSUE TITLE
[Bug]: Using expressions on the query editor causes the evaluated to behave incorrectly when the query is run

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using a logical expression or a null coalease in the URL of an API causes the evaluation to incorrect pass values and return an error

### Steps To Reproduce

1. In an API query, pass query params as part of a conditional expression.
`https://mock-api.appsmith.com/{{Text1.text ? 'users' : 'user'}}` or https://mock-api.appsmith.com/{{Text1.text ?? 'users'}}
2. Run this query and observe that on running this query, the evaluated changes from the correct evaluation instead sending `{{Text1.text ` as the evaluated value as seen in the video

https://www.loom.com/share/59e7b899f5694fa8abcf9036ae8864f8

### Version

Cloud

**Comment by prapullac** [comment]
Verified on the DP

**Comment by ramsaptami** [comment]
PR fixes truncation issue and had been verified
