### ISSUE TITLE
[Enhancement]: Reimagine 'Admin Settings' as an 'Admin Panel'

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#16389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This is a UI enhancement of the _Admin Settings_ page. Since it will house access control, audit logs, branding and more going forward we have to reimagine this as an _Admin Panel_.

### Why should this be worked on?

Our admin settings is evolving from a page that holds instance setting configurations - instance name change, admin email change, SMTP configuration, Google Maps API key configuration, and other such settings - to a panel that holds features with rich functionality like access control, audit logs, whitelabeling and more. We have to reimagine this page.

A few things to cover in the revamp, @Debsourabh please add to this list as you essay out the problem statements
- Rethink the information architecture for the admin panel
- Placement of the ‘Save’ button
    - 'Settings' save require you to restart the self-hosted instance
    - RBAC and Audit Logs can save it then and there
- Relook at terms and copy, also any changes to URL
- Keep in mind 'Upgrade' flows and affordances for _Business_ edition features
- Roles other than super admin will have access to the admin panel based on their access

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_543t8)

**Comment by sharat87** [comment]
@Nikhil-Nandagopal @Debsourabh, is this still relevant? If it is, can we move this to the appropriate pod. I don't think DevOps has much to contribute here.
