### ISSUE TITLE
[Bug]-[Infinity]:Setting a function to run on page load causes other sync functions to be set to run on page load

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a function in an object is bound to a widget like, `JSobj.myFunc.data` then other sync functions present on that object also get triggered to run on page load after a few minutes. This is seen by the message that pops up to tell the user a function is set to run on page load.

This toast message is very persistent and will keep triggering frequently and when user action causes toast messages to pop up

### Steps To Reproduce

1. Have a few functions on an object making sure there's at least 1 async (with a query run) and sync function in the object
2. Drop a few widgets onto the canvas
3. Bind the async function to a table widget and observe the notification that the function will be run on page load and also observe that the sync functions are also now being set to run on page load
4. Continue binding other widgets ti the same `JSobj.myFunc.data` and observe the toast message telling user that these functions are set to run on page load

### Public Sample App

https://release.app.appsmith.com/app/automation-test-cases/page-3-62e25a5905ac9048e7e548d3/edit#mz6fhqu7a9

### Version

Cloud

**Comment by bharath31** [comment]
Assuming 30% of JS Object users face this issue 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 900 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
@Rishabh-Rathod wouid #16823 fix this issue?

**Comment by Rishabh-Rathod** [comment]
> wouid https://github.com/appsmithorg/appsmith/pull/16823 fix this issue?

No, https://github.com/appsmithorg/appsmith/pull/16823 will only remove the async function definition and not change logic of automatic enabling of JSObject `onPageLoad` functionality. We can look into this together.

**Comment by ramsaptami** [comment]
Issue was fixed as part of AST changes, hence closing it
