### ISSUE TITLE
[Bug]: Google Sheets | Drop-downs close abruptly when a space or wrong/random text is entered

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Google sheet API page when we enter a random/wrong text in the dropdown search bar or enter a space, the dropdown closes abruptly.

https://www.loom.com/share/1ced86a1b63c4b049bcbfebf1a13027f 

### Steps To Reproduce

1. Go to any application.
2. Add a GSheet query.
3. In the drop-downs enter any random text or enter a valid text followed by a space.

### Version

Cloud

**Comment by rohan-arthur** [comment]
horrible bug, but since user is easily able to proceed, reducing the impact to `medium`

**Comment by Irongade** [comment]
The dropdown used here is coming from the design system, Do we still want this bug to be in this Pod? Since someone else is responsible for that part of the code.

**Comment by nidhi-nair** [comment]
This is a design system related change that @albinAppsmith will be taking over.

**Comment by shadabbuchh** [comment]
Verified in Release. Working as expected.
