### ISSUE TITLE
[Bug]-[180]:"Show more" Modal of a truncated Text widget is flickering

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#16387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a text widget with long text, kept inside a Modal, and set the overflow property to "Truncate.
When viewing the Show more of the Text widget, it starts flickering

### Steps To Reproduce

1. Create a Modal
2. Add a text widget inside it
3. Fill the text widget with long text.
4. Set the overflow property of the Text widget to "Truncate"
5. Now click on the triple dot icon on the Text widget.
6. When viewing the Show more box on top of the Modal, it starts flickering

 

https://user-images.githubusercontent.com/5265702/187351317-b7a8b273-4db6-4e17-bab0-a2f90a1065f2.mov

### Version

Cloud

**Comment by dilippitchika** [comment]
Assuming 10% users use truncate in modal

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 45 |
| Effort (months)  | 0.5 |
