### ISSUE TITLE
[Bug] No other tab is selected when the active tab is deleted

### ISSUE THREAD

**Issue by sumanthyedoti** [appsmithorg/appsmith#1638]
No tab is selected when the active tab is deleted

### Steps to reproduce the behaviour:
1. Go to the Editor
2. Add Tabs widget
3. Delete the _active_ tab

**Comment by Nikhil-Nandagopal** [comment]
@sumanthyedoti this is expected because the default Tab is set to a value which is not present. selecting the next tab would be wrong here

**Comment by sumanthyedoti** [comment]
@Nikhil-Nandagopal sorry if I didn't understand the context or this is expected too. 

This happens also when an active and non-default tab is deleted, the widget would be empty.

#### Steps to reproduce the behaviour:
- Select a non-default tab
- Delete it
----
Also how about disabling the deletion of a default tab. 
This resolves another issue where a default tab is deleted; the tab widget will be empty when the page refreshed/visited later

#### Steps to reproduce the behaviour:
- Delete a default tab
- Refresh the page

Tabs widget would be empty

**Comment by Nikhil-Nandagopal** [comment]
@sumanthyedoti got it, we can improve the UX by selecting the default tab in this case
