### ISSUE TITLE
[Enhancement]: Redirect to default page if the page id entered in the URL doesn't exist on the app or git branch

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#16395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the current page on a git branch is not present on another branch you want to switch to, AppSmith tries to open that page and shows an error. Instead, open the default page if a page is not available.

### Steps To Reproduce

1. Type the URL containing a page id that exists on one branch (say master) but not on the other(say dev) with the query params `?branch=dev`
2. Notice that instead of redirecting the page to the default page of the app, we see an error message.

### Version

Cloud / Self Hosted - latest

**Comment by vuiets** [comment]
Related to #11889.

**Comment by RoopKrrish9696** [comment]
Stale
