### ISSUE TITLE
[Feature] JS Editor

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1640]

**Comment by aakashDesign** [comment]
Here is the latest Figma file and prototype for JS editor

File- https://www.figma.com/file/Gmw2aRgbMuZTL9ocvgPSrp/JS-Editor?node-id=41%3A2
Prototype- https://www.figma.com/proto/Gmw2aRgbMuZTL9ocvgPSrp/JS-Editor?node-id=62%3A0&viewport=5864%2C1017%2C1.0264137983322144&scaling=min-zoom

**Comment by Nikhil-Nandagopal** [comment]
duplicate of #1751
