### ISSUE TITLE
[Bug]: Icon component - missing icons

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#16400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [ ] `settings-5-line`
- [ ] `edit-2-line`
- [ ] `file-add-line`
- [ ] `database-2-line`

### Steps To Reproduce

https://design-system.appsmith.com/?path=/story/design-system-icon--icon

### Version

Cloud

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
