### ISSUE TITLE
[Bug]: minDynamicHeight shows error even if it is less than maxDynamicHeight

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

minDynamicHeight shows error even if it is less than maxDynamicHeight.

### Steps To Reproduce

1. Drag a Checkbox group widget
2. Enable Auto Height with limits
3. Set Max height to 20
4. Set Min Height to 25
5. You will see a valid error that min height should be less than equal to max height.
6. Now set Max height to 30.
7. It still shows that error in point 5.

### Version

Cloud

**Comment by ankurrsinghal** [comment]
@riodeuno

**Comment by rohitagarwal88** [comment]
@ankurrsinghal : when minHeight throws error, signifier minHeight stay as it is. Check screenshot
![Screenshot 2022-08-31 at 1 48 05 PM](https://user-images.githubusercontent.com/890915/187629729-899d9e64-35bd-489c-adb7-02ab59ce9bd3.png)

**Comment by rohitagarwal88** [comment]
@ankurrsinghal : let's keep it open till #17159  is fixed

**Comment by kamakshibhat-appsmith** [comment]
@rohitagarwal88 shall we close this ? As we have right now removed he limits from property pane , This can be dealt later
