### ISSUE TITLE
[Enhancement]: Navigation from debugger error to particular field having error

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#16408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://user-images.githubusercontent.com/23132741/187438796-8533212d-49b6-47b5-8eb7-193c99c8c903.mov

Currently, not all debugger errors navigate to the exact point where the error occurred. In the above video, there is an example of a table widget's custom column field error where it was not easy to find the error from the debugger UI.

Suggestion to also add navigation icon in the debugger to help the user understand what action could happen on click.

### Why should this be worked on?

Improving navigation for debugger errors will help the user find and resolve errors faster.

**Comment by akash-codemonk** [comment]
Pending tasks as part of the issue
- [x] Property pane navigation for widget errors (except JSONForm widget)
- [ ] JSONForm widget error navigation
- [ ] Query pane errors
- [ ] JSObject errors
- [ ] Api pane errors

**Comment by kavitasmoolya** [comment]
verified on release
