### ISSUE TITLE
[Bug]: minDynamicHeight limit is not respected.

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

An edge case where widget does not respect the minDynamicHeight limit.

### Steps To Reproduce

1. Grab a checkbox group widget
2. Inline off.
3. Enable Auto Height with limits.
4. Set some maxDynamicHeight limit to 30.
5. Set some minDynamicHeight limit to 15.
6. Now keep on adding options until the widget height goes beyond minDynamicHeight limit to maxDynamicHeigt limit.
7. Now remove options until the height is less than the minDynamichHeight limit.
8. You will notice that the widget does not have height equal to minDynamicHeight limit which it should have.

### Version

Cloud

**Comment by ankurrsinghal** [comment]
Fixed

**Comment by Sripriya93** [comment]
Working fine now, Moving to done.
