### ISSUE TITLE
[Bug]: When we select "Auto height with limits" in Container widget - App crashes

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Drag and drop a Container widget, and change Height property from "Fixed" tp "Auto height with limits", observe the app crashes

https://user-images.githubusercontent.com/104895602/187440268-4d4b78f9-b1f3-4f13-9365-0792fdedd74d.mp4

**Comment by ankurrsinghal** [comment]
Fixed here, #16268

**Comment by Sripriya93** [comment]
Working fine, moving to done.

![image.png](https://images.zenhubusercontent.com/627b57d87180949256bd1e01/9edd5f8b-6281-4c63-b943-9c865da19bad)
