### ISSUE TITLE
[Bug]: Text widget - Truncate text not working - Auto height - Cuts text

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Drag and drop a text widget, bind the text widget to input widget, choose "Truncate text" in Overflow property, "Auto height" in Height property, Enter some long text and observe the text is cut and truncate is not working

![image](https://user-images.githubusercontent.com/104895602/187447969-2da27145-ea14-4ef1-a4dc-ab473d5cf9c8.png)

**Comment by ankurrsinghal** [comment]
Can you please check it here again, https://appsmith-evqqqnt7e-get-appsmith.vercel.app/.

**Comment by Sripriya93** [comment]
When Auto height or Auto height with limits is enabled, Overflow text option is hidden. Moving to done.
