### ISSUE TITLE
[Bug]: The three digit text in the member avatar overlaps with the other avatars

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a workspace when there are > 100 members, the text in the avatar depicting the +100 count overlaps with other avatars.

<img width="335" alt="Screenshot 2022-09-01 at 9 04 18 AM" src="https://user-images.githubusercontent.com/39921438/187826956-09ab8971-64a7-4cfa-aee1-b143b6ce3d8d.png">

### Steps To Reproduce

1. In the homepage visit any workspace that has > 100 members.

### Version

Cloud

**Comment by ankitakinger** [comment]
I think this is fixed now. Closing the issue.
