### ISSUE TITLE
[Bug]: CI failure : Appsmith server goes down (throws 503) intermittently

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#16435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Steps:
There isn't any exact steps, we see this issue randomly.

### Steps To Reproduce

1.Post login at the time of application creation the server is going down.

And Dashboard link.
https://dashboard.cypress.io/projects/eyxvp8/runs/23075/test-results/6b0b2b09-2f16-43fd-b6f9-0c3a7dcc01e3

### Version

v1.7.15

**Comment by Aishwarya-U-R** [comment]
Appsmith UI breaks while trying to rename the application
Example run: [https://dashboard.cypress.io/projects/eyxvp8/runs/23297/test-results/7377ef22-3aeb-4b7e-b1b5-56af2e981f9b](url)

**Comment by hetunandu** [comment]
Seems like this is happening in many scenarios and not just forking an app. Can we try to find more information about this?

**Comment by NandanAnantharamu** [comment]
@hetunandu this is not related to ForkApp test , its actually going down most of the times at the time of renaming application.

**Comment by NandanAnantharamu** [comment]
Dashboard link: 
https://dashboard.cypress.io/projects/n14p1y/runs/3348/test-results/ccb729c6-aef7-47d2-8052-403ecbcbaadd

Video link:
https://user-images.githubusercontent.com/67676905/189670837-30cf8489-71e4-4cf4-a07f-8280cd9abf1f.mp4

cc: @ginilpg

**Comment by NandanAnantharamu** [comment]
Adding some more new dashboard links:

https://cloud.cypress.io/projects/eyxvp8/runs/26672/test-results/72278745-18b3-4bb9-b90b-0299b9544a34?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

https://cloud.cypress.io/projects/eyxvp8/runs/26675/test-results/1f264f22-0307-44ef-a433-87fd8977a4b1?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

https://cloud.cypress.io/projects/eyxvp8/runs/26688/test-results/2334abd1-7c85-4e15-b96a-5d7e277bfd43?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

**Comment by Aishwarya-U-R** [comment]
Latest - https://cloud.cypress.io/projects/eyxvp8/runs/31053/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D

For logs - https://github.com/appsmithorg/appsmith/actions/runs/4423181990

**Comment by Vijetha-Kaja** [comment]
No longer reproducible. Working fine now.
