### ISSUE TITLE
[Feature]: Connecting to a git hosting provider on a custom SSH port

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#16442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Some companies that host their git source control providers on a custom ssh port are not able to connect their apps to git, integrate their app building with their dev workflows, back them up, and collaborate on them. 

Their remote URLs look like
`git@hostingprovider.com:1234/repo/appname.git`

We should look at supporting them.

---
👥 [Forum Post](https://community.appsmith.com/t/connecting-to-bitbucket-using-custom-ssh-port/1363)

### Why should this be worked on?

Looks like a potential hindrance for people looking to collaborate on apps using Git.

**Comment by hiteshjoshi** [comment]
This should work right away. As URL can have a PORT defined. To test it, we will need to have a custom git server. I will try with https://gogs.io/

**Comment by AnaghHegde** [comment]
@hiteshjoshi This would work out of the box when we work with git CLI. But since we use `jgit` library in the code base, we have to specify this explicitly while cloning or doing any git operations. And another thing is I am unsure if the `jgit` supports this or not at the movement.

**Comment by mikeywuu** [comment]
Is there any update on this issue? We're also affected by the limitation.
