### ISSUE TITLE
[Task]: Remove RapidAPI plugin code from the API server

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- At the moment we do not have plans to support RapidAPI integration and hence it is necessary to remove the related plugin code from the API server so that it doesn't lead to tech debt or force developers to consider its presence.

**Comment by prapullac** [comment]
@sumitsum : completed a round of sanity on the DP and everything looks good
