### ISSUE TITLE
[Task]: Maintain Context and Focus Phase 1

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#16456]
### Summary
Maintain last focus across Editor

## Entity explorer: ( @rahulramesha )

- [x] Leaving and then returning to a page should maintain what widget was selected
- [x] Which widget was selected when you were on a canvas

## Canvas / Widgets: ( @rahulramesha )

- [x] Single widget selection
- [x] Multiple widget selection
- [x] Property
- [x] Modal
- [x] Property Pane accordions and tabs

## APIs:

- [x] Which config tabs you have open
- [x] Code editors we set focus and cursor
- [x] response tab and height

## Query/SAAS

- [x] Config tabs
- [x] Code editor position
- [x] Response tabs and height

## JS Editor:

- [x] Code editor
- [x] Response tabs and height

DP link: https://appsmith-kqxwikj8l-get-appsmith.vercel.app/

**Comment by Richarex** [comment]
@hetunandu JS object editor page when the user selects "Logs" tab & applies the filter "Console Logs" switches to other API and navigating back to JS object editor page the applied filter is reset. Please refer the video attached: https://www.loom.com/share/69dca84f51354a82b0eb9f7da9d1a38a

**Comment by rahulramesha** [comment]
@Richarex please do tag me as well in the comments going forward, completely missed this comment,

For issues number,
2. This is a complex property Pane for a widget like editing the column of table widget etc, this will be worked on in Phase 2
3. Will also be worked in Phase 2
 Will work on fixing 4 and 5.
 
 Not sure i understand issue number 6, could you please provide a loom video
 
 @akash-codemonk could help with fixing the rest.

**Comment by Richarex** [comment]
@rahulramesha for issue no 6 have added the video, please go through the other issues as well.
