### ISSUE TITLE
[Task] API Pane Redesign

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1646]
Edit: Figma designs for the new API pane design: https://www.figma.com/file/HteDR4ixMWpQyelyYXPuZh/Appsmith-new-designs?node-id=97%3A2

This is the top-level issue that tracks the entire project. There are sub-tasks created for each feature of the new API pane designs to track each task more granuarly.

**Comment by mohanarpit** [comment]
@aakashDesign Can you please update this issue with the link to the Figma designs? Would like to pick this project up next.

**Comment by aakashDesign** [comment]
https://www.figma.com/file/HteDR4ixMWpQyelyYXPuZh/Appsmith-new-designs?node-id=97%3A2

**Comment by aakashDesign** [comment]
Hey! Have updated designs for Save as Datasource, and Lightning menu open on figma. Please take a look and let me know what you think.
https://www.figma.com/file/HteDR4ixMWpQyelyYXPuZh/Appsmith-new-designs?node-id=97%3A2

<img width="1503" alt="Screenshot 2020-12-01 at 10 46 45 AM" src="https://user-images.githubusercontent.com/65771350/100700107-b186b700-33c2-11eb-8c3b-6cfeca31c622.png">
<img width="1509" alt="Screenshot 2020-12-01 at 10 46 55 AM" src="https://user-images.githubusercontent.com/65771350/100700112-b51a3e00-33c2-11eb-9cfe-695f6babf105.png">

**Comment by areyabhishek** [comment]
@mohanarpit @Nikhil-Nandagopal: There's a small issue with the 'response + debug request' pane. This pane will also be used as the debugger both inside the API pane and canvas, so the way this needs to be built is different. The bottom pane will need to be floating but fixed to the bottom.
Could we talk about this? Thinking through this will help the debugger be built out easily in the future.

**Comment by aakashDesign** [comment]
@mohanarpit @devrk96 Hey! I have added updated API designs with new states and components.
New Figma file -
https://www.figma.com/file/ko05rfZRuc8HzqBZRpg1fY/API-Pane-Updates?node-id=0%3A1
