### ISSUE TITLE
[Bug]: Themes have become inaccessible for few apps because the same custom theme was being used across different applications

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#16481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Bug]: Themes have become inaccessible for few apps because the same custom theme was being used across different applications
On opening the affected apps, you get an error, crashing the editor 
<img width="910" alt="Screen Shot 2022-09-01 at 5 32 04 AM" src="https://user-images.githubusercontent.com/8403079/188101998-d051ec8b-312b-46e1-8c2d-f76d7f1c8607.png">

### Steps To Reproduce

This issue can't be reproduced afresh. This state was reached a couple of months ago when on cloning a new custom theme was not getting created. Same for git branches. The underlying bug was fixed but not the bad data.

### Version

Cloud

**Comment by Parthvi12** [comment]
Not able to verify this issue, because steps to reproduce are not clear.
