### ISSUE TITLE
[Docs]: Update documentation for navigateTo to aling with latest changes

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/appsmith-framework/widget-actions/navigate-to

### Describe the problem

Following PR changes UI and functionality of navigateTo and this needs to be updated on documentation
https://github.com/appsmithorg/appsmith/pull/14856

### Describe the improvement

UI an functional changes improvements for `navigateTo()`

**Comment by Pranay105** [comment]
@ramsaptami could you please summarize the changes needed in the navigateTo docs? cc @rimildeyjsr

**Comment by ramsaptami** [comment]
@Pranay105 Attaching a screenshot of how the navigateTo looks right now
![image](https://user-images.githubusercontent.com/79509062/191483452-60af0b4e-23a1-40ee-8e57-ef2ad5e93f09.png)

But having said that, we have a project where the action selector (the entire bit under Events on widgets) is changing so we can overhaul all of them together
