### ISSUE TITLE
[Bug]: /new API is very slow post RBAC on production

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#16498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the RBAC deployment on production, the homepage loading has become multiple times slower.

### Steps To Reproduce

Go to homepage on app.appsmith.com

### Version

Cloud

**Comment by RakshaKShetty** [comment]
This is a performance improvement issue that cant be tested. so removing the QA label
