### ISSUE TITLE
[Feature]: Allow tooltip icon color to be changed by itself or to match Label Style text color

### ISSUE THREAD

**Issue by some-rando** [appsmithorg/appsmith#16499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When used on an Input Widget, tooltips show the **question mark within a circle** icon, the icon fill is always a mostly-opaque black color. It doesn't changed based on the selected Text Color of Label Styles.

### Why should this be worked on?

Changing this would allow for consistency of the user interface, and the ability to see the tooltip icon when on a dark background (assuming it matches the text label that is also a light contrasting color).

It looks like this is because it's an SVG and not text, but the svg attribute of `<path fill="currentColor"...` looks like it could be dynamically changed to match the text label.

I have not checked to see if this same styling issue exists on other widget types besides Input Widgets.

**Comment by ame-appsmith** [comment]
[Another user](https://theappsmith.slack.com/archives/C04VADPRCCF/p1692878315821059) requested this feature.

**Comment by jsartisan** [comment]
@somangshu @ichik @KelvinOm Should we close this issue as we will be removing the ability to customize the label color?

**Comment by ichik** [comment]
@jsartisan yes, the icons would be matched to the rest of the theme automatically with WDS.

**Comment by somangshu** [comment]
@jsartisan please close it if the code is already in place under WDS

**Comment by jsartisan** [comment]
Closing as this will be handled automatically by wds theme engine.
