### ISSUE TITLE
[Bug]: Dynamic height issues observed in checkbox group widget on DP - separate issue - Auto height with limits

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

As we set Auto Height with limits - set appropriate min and max height, continue to add options, the options overflow out of the max height - is Scroll functionality with Auto Height with limits, working yet? 
<img width="430" alt="ChkboxGrp_AutoHeightWithLimits_NoScroll" src="https://user-images.githubusercontent.com/101863839/180167475-7cf763e2-d6f4-4358-8cc8-510f5e0814ab.png">

**Comment by ankurrsinghal** [comment]
fixed #16268

**Comment by Sripriya93** [comment]
Working fine, moving to done

![image](https://user-images.githubusercontent.com/104895602/188841698-ad83a42b-794c-4756-9fd7-ae19488499d6.png)
