### ISSUE TITLE
[Bug]: Dynamic height issues observed in checkbox group widget on DP - Separate issue

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Drag and drop a checkbox group widget, Turn off the Inline property, and set Required Flag to on. Now ensure that if no check boxes are selected, the red box indicating required, covers the entire section of checkboxes. This does not happen if inline is ON. The behavior is as below (only the first row is marked in red-

WITH INLINE ON -
<img width="593" alt="ChkboxGroup_WithInlineOn" src="https://user-images.githubusercontent.com/101863839/180166980-a7c8e4c6-1693-48ea-912b-3f4522e18c2d.png">

WITH INLINE OFF - 
<img width="539" alt="ChkboxGrp_AutoHeight_Inlineoff" src="https://user-images.githubusercontent.com/101863839/180166752-38964bff-c30a-4989-801c-1f2262024518.png">

**Comment by ankurrsinghal** [comment]
@Sripriya93 I think this problem is resolved in the design as there is no red box. Check here, https://appsmith-qhryi4omr-get-appsmith.vercel.app/user/login.

**Comment by Sripriya93** [comment]
Sure @ankurrsinghal Moving to done

![image.png](https://images.zenhubusercontent.com/627b57d87180949256bd1e01/2b5eb71a-7b06-40de-9d7e-c9d7831e9c63)
