### ISSUE TITLE
[Bug]: Modal widget - Auto height with limits - Not working as expected 

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Drag and drop a Modal widget, change the height property from "Fixed" to "Auto height", observe the min and max height signifiers or the dotted lines are not seen.

![image](https://user-images.githubusercontent.com/104895602/188146881-fb45a5ae-b32d-4ae7-a19c-49dba1ca9203.png)

**Comment by ankurrsinghal** [comment]
Please check it here, https://github.com/appsmithorg/appsmith/pull/16880

**Comment by Sripriya93** [comment]
We are able to see the signifiers when we choose Auto height with limits. But we are facing other issues, raising bugs separately for them. Moving this to done.
