### ISSUE TITLE
[Feature]: Allow users navigate to previous step in Welcome tour

### ISSUE THREAD

**Issue by victory-a** [appsmithorg/appsmith#16509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, users can only go forward to the next step in the interactive welcome tour.
It would be nice to allow users to go back and view instructions from previous steps.
<img width="1662" alt="Screenshot 2022-09-04 at 11 11 59 PM" src="https://user-images.githubusercontent.com/28878343/188335363-5e583e3a-abcc-4cdd-a031-0518fcdaa761.png">

### Why should this be worked on?

Users may need to reference instructions of solutions from previous steps to better understand what is going on in further steps.

**Comment by kocharrahul7** [comment]
Given the reduced importance, and eventual sunsetting of the welcome tour, we will be closing this issue
