### ISSUE TITLE
[Docs]:  Slider Widget

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#16506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://www.notion.so/Slider-Widgets-c8e9fcce6cdf4bcb98923669139b7087

### Describe the problem

We are working on a new slider widget. We need documentation for the widget.
We have 3 slider widgets **Number Slider**, **Category Slider** and **Range Slider**

### Describe the improvement

- This is a new widget which will be used by the user as inputs.
- We need to document all the 3 variants of the widget namely `Number Slider`, `Category Slider` and `Range Slider`.
- Not only document their use but also highlight some use cases where a slider is used in real world scenarios.
- Also need to document the various validations that we have for the properties of these widgets.
- And much more

**Comment by jnikhila** [comment]
@yaldram - Is the first draft ready for doc team to pick up?

**Comment by yaldram** [comment]
@jnikhila yes - https://www.notion.so/appsmith/Slider-Widgets-c8e9fcce6cdf4bcb98923669139b7087

**Comment by jnikhila** [comment]
Thanks @yaldram - What's the release date for this?

**Comment by yaldram** [comment]
The Q/A team is now working on testing the widget. So probably we will merge it this week. I would request you to get in touch with @dilippitchika on the release date.

**Comment by dilippitchika** [comment]
@yaldram i don't control the release date here, once the feature is QA complete we should be shipping it.

**Comment by jnikhila** [comment]
@spark-c - Could you please add estimates to the ticket?
