### ISSUE TITLE
[Docs]: [Rehaul] - Google Sheets Datasource

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#16518]
As quoted by [Pranay Agrawal(notion)](https://www.notion.so/appsmith/Pranay-Agarwal-InstaMeet-2cb8e305ac9a4ce7b53b283d8e0eadd7?d=d5346569ef1c491ead9e3d9eb0415f70#32685094d9754fd7adf7dd11bef12245)

In some cases there are multiple docs/ guides on integrating with a database, and docs are not fully consistent. For example, there are two docs on the website which show how to connect with Google Sheets (as listed below). However, while the first doc is top result that pops up on Google while searching ‘Google Sheets on Appsmith’, the guide is basis an older version of Appsmith, and hence is not most intuitive to follow (maybe we could add a line in the guides to indicate which version of Appsmith has been used in that specific guide)

1. [https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-work-with-google-sheets-on-appsmith](https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-work-with-google-sheets-on-appsmith)
2. [https://docs.appsmith.com/reference/datasources/querying-google-sheets](https://docs.appsmith.com/reference/datasources/querying-google-sheets)

**Comment by spark-c** [comment]
Notion [job story doc](https://www.notion.so/appsmith/Google-Sheets-5f850691a9dd45138fc0b748f48dfec6)

**Comment by spark-c** [comment]
current [draft pr](https://github.com/appsmithorg/appsmith-docs/pull/981)

**Comment by spark-c** [comment]
resolved by [rehaul PR](https://github.com/appsmithorg/appsmith-docs/pull/981)
