### ISSUE TITLE
[Bug]: The resource ID is missing for Login and logout events

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The resource ID is missing for Login and logout events
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/45958978/188356919-178221d8-595c-48ce-8f90-15c8c30d5576.png">

### Steps To Reproduce

1. Login to ec-2 instance
2. Go to home page
3. click on the members and setting tab
4. under others tab click on Audit log
5. Now the logged in user event will be displayed on the top
6. Click on the event name 
7. Inside ethe JSON the id is missing 

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
It is instance level event, `resource` will not be populated. The empty `id` json-filter is hidden now.
