### ISSUE TITLE
[Bug] Converting back from JS to regular script the initial data is lost 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1651]
Steps to reproduce:
1) Add a map widget
2) Add a Initial location
3) now convert it to JS 
and observe that the Lat and log is displayed to user
4) Convert back to regular script 
and observe

Observation:
It is observed that the initial location of the map is not store on converting back 

Expectation:
the initial location of the of the map must be displayed on converting back to regular script

**Comment by Tooluloope** [comment]
@vivekverma2312 Could you confirm if this is fixed

**Comment by aswathkk** [comment]
This will be resolved in #10833
