### ISSUE TITLE
[Feature]: Provide the user an option to add tabindex and couple of attributes to the Text field or any components

### ISSUE THREAD

**Issue by santhoshses** [appsmithorg/appsmith#16519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Is there a way where I can update the source code for adding these required attributes?

### Why should this be worked on?

I need to set the tabindex values for the focusing functionality.

**Comment by hetunandu** [comment]
@santhoshses Could you list all the properties/attributes you need?

**Comment by dilippitchika** [comment]
Closing in favor of - https://github.com/appsmithorg/appsmith/issues/7757
