### ISSUE TITLE
[Task]: Resolve Flaky Jest test failures

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#16525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We were experiencing frequent failures for the following Jest tests:
- ColorPickerComponentV2.test.tsx
- IconSelectControl.test.tsx

Example failures:
- https://github.com/appsmithorg/appsmith/runs/8145823657?check_suite_focus=true
- https://github.com/appsmithorg/appsmith/runs/8170350211?check_suite_focus=true

**Comment by smrutiparida** [comment]
<img width="996" alt="Screenshot 2022-09-05 at 5 55 44 PM" src="https://user-images.githubusercontent.com/5945400/188448919-b627b718-3c97-4fa1-baaf-82f6d6d90610.png">

With regard to failure of colorpicker test case, 

The test case do not have "escape" event called to remove the colorpicker from the DOM. Escape keyboard action related testcase verifies in an earlier test case -  "Pressing escape closes the color picker".  Hence this change is proposed.

However by that logic, the testcase should have failed 100% of the time, which it does not locally. 

@aswathkk @areyabhishek @SatishGandham

**Comment by aswathkk** [comment]
@smrutiparida Thanks for taking the time to explore this issue.
When we select a color, the color picker should be closed automatically. That is what is being tested at the end of this test case.
So, explicitly pressing `Escape` shouldn't be done.
