### ISSUE TITLE
[Bug] Launching the App viewer application lands user to "Page not found" page when admin has not deployed 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1652]
Steps to reproduce
1) Add an application in "XYZ" account 
2) Share application to "ABC" account as App viewer
3) Login to  "ABC" account 
4) launch the application shared 
and observe

observation :
User is navigated to Page not found page 

Expectation:
User must be able to view the empty application 

Video:
 https://www.loom.com/share/de30e9717b4048d7889ef72a217fcd32

**Comment by Nikhil-Nandagopal** [comment]
We should inform users that their app has not been deployed when they are inviting app viewers

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : Sure. But you still have existing app viewers who have access to this application who would still run into the same issue.

**Comment by rishabhsaxena** [comment]
seems to be working now
