### ISSUE TITLE
[Docs]: Add docs for Code scanner widget 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Add new docs for Code scanner widget

### Describe the improvement

We are adding a new widget to scan qr codes - https://github.com/appsmithorg/appsmith/issues/4577

**Comment by dhruvikn** [comment]
Hi @jnikhila, here's the first draft for the docs of the Code Scanner Widget - https://www.notion.so/appsmith/Code-Scanner-Widget-891f9d04eab4441e865c91e17170faad

We plan to merge [this](https://github.com/appsmithorg/appsmith/pull/15990) into release this week. Please let me know if we are missing anything. Thanks.

cc: @dilippitchika

**Comment by jnikhila** [comment]
Thanks @dhruvikn. Could you please record a loom video explaining the widget and use case, and add its link to the ticket?

**Comment by dhruvikn** [comment]
Sure @jnikhila, here you go.
 
PR - #15990 
Issue - #4577
PRD - https://www.notion.so/appsmith/QR-scanner-PRD-29f5a1f703b648acaeee463ab5ff6483

Demo video -
<video src="https://user-images.githubusercontent.com/22471214/190112874-7239a047-e771-4560-8d75-fad2ca229a9f.mp4"></video>

**Comment by jnikhila** [comment]
Thanks @dhruvikn
