### ISSUE TITLE
[Bug]: The "x" icon in TreeSelect widget is visible even when no options are selected

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On enabling the `Allow Clearing Value` property we get the `x` icon in the widget which ideally should be visible only when there is any option selected in the widget. But right now we see it even when there is no option selected. Also when we set an `onOptionChange` event and click on the `x` button, the event gets triggered.

**Note:** This bug is present only in `Release` and not in `Production`, hence marking it as `Regression`.

https://www.loom.com/share/7662751f8550499cbe65b86a7fa624ca

### Steps To Reproduce

1. D&D a TreeSelect widget.
2. Enable the `Allow Clearing Value` property.
3. Now click on the `x` icon to clear the selected option.

**Expected:** The `x` icon should disappear once the selected option is cleared.

### Version

Cloud

**Comment by Tooluloope** [comment]
RCA -> This issue was caused when we fixed #16367. A simple cypress test would have prevented this from happening.

I've added a cypress test in the fix
