### ISSUE TITLE
[Bug]: GSheet | Query page options take a lot of time to load

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/1d051742c9d94960a634955a1cd260b6

When we try to create a new API for a Gsheet, the drop-downs take a lot of time to load and sometime we get the below error:

<img width="1440" alt="Screenshot 2022-09-05 at 11 29 24 AM" src="https://user-images.githubusercontent.com/39921438/188408304-e45b3330-bc26-462c-a45b-8a75e438f19e.png">

**Note:**

1. This is prevalent only on `Release` and not on `Prod`.
2. Tried the same in an incognito window but no success there as well.
3. Using a Mac machine.
4. Prevalent on Chrome & Firefox

### Steps To Reproduce

1. Go to any application in `Release`.
2. Add a GSheet as a datasource.
3. Click on `New API`.

### Version

Cloud

**Comment by yatinappsmith** [comment]
Unable to use exsisting app using gsheet https://www.loom.com/share/aa5b9bdd71894287a208504c2922354d   https://release-ee-https.appsmith.com/applications/62ac1622d03dbf1d461f6ca1/pages/62ac1622d03dbf1d461f6cad/edit/saas/google-sheets-plugin/api/62ac1622d03dbf1d461f6cb6

**Comment by sumitsum** [comment]
It is supposed to be closed via https://github.com/appsmithorg/appsmith/pull/16565
