### ISSUE TITLE
[Bug]: Unexpected `pageList` variable value `{{pageList}}` 

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#16532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1127" alt="Screenshot 2022-09-03 at 4 14 28 AM" src="https://user-images.githubusercontent.com/23132741/188421952-805e51a4-3835-4764-ae6f-d8cfc9b43399.png">

### Steps To Reproduce

1. Go to the new Application
2. Add Text Widget
3. Type `{{pageList}}` in the Label field and check the evaluated value.

### Version

1.7.15

**Comment by rohan-arthur** [comment]
![Screenshot 2024-08-21 at 14 27 54](https://github.com/user-attachments/assets/fc939358-218f-4471-88fb-9646319c3a14)
not reproducible anymore
