### ISSUE TITLE
[Bug]: Overflow dropdown should be hidden if Auto Height is enabled in Text Widget

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Overflow dropdown in the Property Pane which contains options like, Truncate, Scroll, No overflow should be hidden if Auto Height is enabled in Text Widget, this is because user cannot edit the height of the widget because the Auto Height takers care of that.

### Steps To Reproduce

1. Drag a text widget.
2. Enable the Auto Height/Auto Height with Limits.
3. See that the Overflow options are still there.

### Version

Cloud

**Comment by Sripriya93** [comment]
Working fine
![image](https://user-images.githubusercontent.com/104895602/188617116-cb1e7a93-8a50-4ecf-9a21-fc2c1218d842.png)
Moving to done

**Comment by riodeuno** [comment]
Let's make sure that the value becomes no overflow so that the dynamic height takes care of changes in height.

**Comment by ankurrsinghal** [comment]
The issue is resolved here, https://github.com/appsmithorg/appsmith/pull/16949

**Comment by Sripriya93** [comment]
@riodeuno @ankurrsinghal Earlier when validated we saw the same as when we click on Auto height or Auto height with limits, we are seeing the Overflow text property fully disappears as before. (Please check below)
![image.png](https://images.zenhubusercontent.com/627b57d87180949256bd1e01/9b0946a2-9603-401e-9bbc-4c02a9816317)
I assume what @riodeuno is mentioning is, the option, the value becomes no overflow, but what we see is that it disappears.

Could we get this clarified please?

**Comment by Sripriya93** [comment]
Moving to done with reference to the comment given in PR https://github.com/appsmithorg/appsmith/pull/16949
