### ISSUE TITLE
[Bug]: Long label of the widgets does not wrap when entered without spaces

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Long label of the widgets does not wrap when entered without spaces found in Datepicker but present in some including Input, Select, Group widgets.

### Steps To Reproduce

1. Drag and drop any widget with labels.
2. Enter a long text without spaces.
3. Set it to top align.
4. Enable Auto Height.
5. See that the label cuts at the right boundary.

### Version

Cloud

**Comment by Sripriya93** [comment]
Working fine with the given steps to reproduce, moving to done.
