### ISSUE TITLE
[Task]: Updates modal new design

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#16552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

**Design File:-** https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=4675%3A23087

**Comment by shadabbuchh** [comment]
Testing for this PR in `ce` is complete. No issues found there.
However `ee` could not be tested as scripts are failing at docker build. Will test this in `ee` once this PR is merger.
