### ISSUE TITLE
[Bug]: Number Input rounding number instead of showing decimal

### ISSUE THREAD

**Issue by PaulMcF1987** [appsmithorg/appsmith#16551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When editing an entry, the number input box rounds the number up and does not display the decimal, the video below shows me first on my `View Screen` and you can see that the number in question should be 14.5%.
I then navigate to the edit screen, When I select the input box, instead of 14.5, the number has been rounded to 15.
I then select the `Default Text` box which confirms that the number should be 14.5.

If I then save the job, the number changes from 14.5 to 15.

However, if I click in the input box, the number changes to the expected 14.5.

The danger is, if I or another user doesnt know to click in this input box to set the value, once saved, the values will be incorrect.

Uploading numberinput.mp4…

### Steps To Reproduce

Create a tabbed page which pulls information from the selected row of a table.

Tab 1 is a view tab, created using Text Widgets.

Press an Edit button, which takes to tab 2 which uses input widgets. Make sure that on the table, there is a number with a decimal which is populated into the number input widget.
This should then show the number being rounded rather than showing the exact number.

### Version

Docker / 1.7.14

**Comment by Nikhil-Nandagopal** [comment]
@PaulMcF1987 I don't see a video attached. Could you please re-upload it?

**Comment by PaulMcF1987** [comment]
@Nikhil-Nandagopal The issue seems to have disappeared since the last update
