### ISSUE TITLE
[Feature]: Allow label width change directly from the UI in input type widgets

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow users to change the label width using drag handles in a widget. Widgets which should support this - 

- Input widgets: Regular input, currency, phone, datepicker
- Select widgets : Select, treeselect, multitreeselect, multiselect
- Group widgets : Radio, checkbox, switch groups
- Boolean widgets : Switch, checkbox

### Why should this be worked on?

This helps users drag to resize the label rather than having to work on a setting in the property pane.

**Comment by dilippitchika** [comment]
<img width="461" alt="Screenshot 2022-09-06 at 11 22 36 AM" src="https://user-images.githubusercontent.com/19730984/188557017-20ea3808-66c4-4c8c-abd0-26129df48751.png">


UI idea of what i was referring to

**Comment by rohitagarwal88** [comment]
@momcilo-appsmith / @rahulramesha / @marks0351 : Lets plan this today.
