### ISSUE TITLE
[Bug]: Debugger generates over 5700 logs on editing TableData of Table Widget

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#16570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While Modifying Table Data Property, it generates over 5700 logs for just modifying a single character of tableData Property of Table Widget. This was causing performance issues that is being fixed, but we still. need to investigate why a single action generates 5700+ debugger logs.

### Steps To Reproduce

1. Import the below app
2. Navigate to Regulations page
3. Of the Regulations table widget, modify tableData code
4. Check verify that the debugger logs add 5700+ logs to the redux state

https://theappsmith.slack.com/archives/C024GUDM0LT/p1661870471009029

### Version

Cloud/self hosted/Release

**Comment by somangshu** [comment]
@ohansFavour @ApekshaBhosale to give more context on the issue, In the above mentioned App on Regulations Page, while editing tableData, it generates over 5700 logs. Need one of your help in determining why so many logs are needed here.
