### ISSUE TITLE
[Bug]: Tab widget - Auto Height with limits - Container widget inside Tab widget

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Drag and drop a tab widget and set its height to auto height with limits. 
2. Add a few widgets inside it. 
3. Set its min height to 4 and max height to 400
4. Add a container widget into this tab widget and set the container widgets auto height to min 4 and say max 50
The container widget's bottom area border is lost, and also the dotted lines which indicate the max height are not visible

<img width="1127" alt="Tab_Container_AutoheightWithLimits_Border_DottedlineNotvisible" src="https://user-images.githubusercontent.com/101863839/188599232-3c2e2a72-2687-4b6d-828f-d4043fb7b9d5.png">

**Comment by riodeuno** [comment]
@btsgh Please share a loom recording for this issue. I'm unable to replicate this on this deploy preview https://appsmith-d9gs8gk0p-get-appsmith.vercel.app/
