### ISSUE TITLE
Task: List v2 - Child widget property pane, {{currentItem}} binding evaluated value is always undefined

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#16576]
- [ ] It should show the evaluated value instead of `undefined`
- [ ] It should throw validation errors.

**Comment by ashit-rath** [comment]
![Screenshot 2022-09-06 at 3.22.50 PM.png](https://images.zenhubusercontent.com/6108d334019397698aa61b3d/92a3e25f-8fe4-47b4-9e33-595bd5ac341d)

**Comment by aswathkk** [comment]
@ashit-rath Is this for ListWidgetV2?

**Comment by ashit-rath** [comment]
@aswathkk Yes it is
