### ISSUE TITLE
[Bug]: Tab widget - Autoheight with limits - Increasing the max height to beyond the canvas size does not enlarge the canvas height.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Drag and drop a tab widget. Increase its width. Change its height to Auto height with limits. 
2. The default numbers there are 2 and 40
3. Now add a few widgets inside the tab widget
4. Increase the max height to say 90

Observe that as the dotted line height is increased, the canvas height does not change. Canvas height should also increase.

<img width="1303" alt="Tab_MaxHeightIncrease_Canvas" src="https://user-images.githubusercontent.com/101863839/188584505-d8c2d4b2-ba95-40be-803e-762c52f76a0c.png">

**Comment by riodeuno** [comment]
@btsgh 

> the canvas height does not change. Canvas height should also increase
As the signifier is for the max height and not the current height of the widget, the canvas wouldn't respond to it. However, if the widget happens to increase height, the canvas should increase height accordingly.

**Comment by btsgh** [comment]
@riodeuno - Agreed.

**Comment by kamakshibhat-appsmith** [comment]
As mentioned, this cannot be fixed
