### ISSUE TITLE
Task: List v2 - Page size derived property fix

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#16586]
The list v2 on mount shows erratic number for the page size property. The expectation here is that if all the relevant information is not present while generating `pageSize`, its best to make it undefined rather than to give an estimated number as it will be used to generate meta widgets and also used in server side rendering

**Comment by kamakshibhat-appsmith** [comment]
@ashit-rath do we have page size issue in Listv1 as well?
I could see the page size is not evaluating correctly for List v1 as well on page reload.Can you confirm ?
https://www.loom.com/share/e2ab3381e66347f5bb01e0926b4d30b0

**Comment by kamakshibhat-appsmith** [comment]
--> Issues with List v2 page size evaluation on page reload .
https://www.loom.com/share/bf95456e9b064835895eaede04daa4cf

**Comment by kamakshibhat-appsmith** [comment]
I could see 3 on the canvas @ashit-rath

**Comment by kamakshibhat-appsmith** [comment]
Shall I create a separate issue to debug this?
