### ISSUE TITLE
[Bug]: Container widget inside Tab widget having auto height with limits - behavior incorrect

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Drag and drop a tab widget, increase the width and the height of the widget.
2. Add a container widget, an input widget and a stat box in the tab 1 and some random widgets in tab 2.
3. Set the tab widget to Auto height with limits - notice that the height of the tab widget reduces to hug its contents at the same time the dotted lines appear below for the max height.
4. Now add a stat box widget inside the container widget which is inside the tab widget.
5. Observe that the entire tab widget height decreases. 
6. This should not happen as the container widget is still taller and the max height of the tab widget is higher to include the entire height of the container widget.
<img width="1311" alt="Tab_Container_AutoHeightwithLimits_IncorrectBehavior" src="https://user-images.githubusercontent.com/101863839/188687711-714a9967-e43f-461e-9c8a-a5dbad595332.png">

**Comment by riodeuno** [comment]
@btsgh Please share a loom video for the decreasing tabs widget height. As for the max height marker appearing below the tabs widget bottom row, it is an expected scenario.

**Comment by btsgh** [comment]
@riodeuno  - [This](https://www.loom.com/share/d32c7bdb4ed94a06af2092e671d8011d) is the loom recording.
