### ISSUE TITLE
[Bug]: Input Widgets with Auto height enabled when entering longer text, contents are not fully hugged

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Drag and drop any of the Input widgets (Input, Phone Input, Currency Input)
Select Auto height in "Height" property 
In the "Label" property enter a longer text with more than four or five lines
Observe all the contents are not inside the border of the widget

Also when we move the widget downwards, we also observe that the contents are moved inside or the auto height is being increased for the widget. But then when we drag and drop another widget we are facing the same issue.

https://user-images.githubusercontent.com/104895602/188643207-f1323186-72a7-4344-a130-3c88b5fd9d75.mp4

**Comment by ankurrsinghal** [comment]
This issue has been resolved in this PR, https://github.com/appsmithorg/appsmith/pull/16943

**Comment by Sripriya93** [comment]
Working fine. Moving to done.
![image](https://user-images.githubusercontent.com/104895602/191473642-525e4728-e3b1-4822-a5bf-4843df2ac8b4.png)
