### ISSUE TITLE
[Feature] Hidden (dynamic and static) fields in query forms

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1659]
## Summary
Feature which has allowance for config driven hiding of form controls in query forms

## Motivation
Query forms are driven by configurations, this allows for client agnostic development of plugins.
To keep the config driven architecture, while allowing for further flexibility in visibility of columns this feature is needed.

## Additional Context

We will have a new property called `hidden` in the control configurations.
Example:
```
hidden: true
```
This signifies that the control will be of input type "hidden" with a static value provided in the `initialValue` property of the configuration.

Example:
```
hidden: { path: "actionConfiguration.body[0].x", comparison: "EQUALS", value: "y" }
```

Here we have a structure for the `hidden` property which the client understands. 
`path` this is a json path to the property we're trying to compare.
`comparison` this is the type of comparison operation we need to perform the potential values will be put in an enum.
`enum ComparisonOperations { "EQUALS", "NOT_EQUALS", "GREATER", "LESSER" }` (the actual strings are subject to change and only for reference.
`value` the RHS of this comparison

In the above example, the comparison performed by the client will be `_.get(actionConfiguration, "body[0].x") === "y"`.

_*Note on further abstraction*_
Today this approach allows for one comparison. This doesn't include cases which need more complex comparisons and calculations to come to a conclusion of whether to hide a certain control.

_*Note on logical parity with Property Pane controls*_
PropertyControls don't have to rely on JSON and can be passed in the format `hidden: (props: Value) => boolean` as the configurations come from the respective widgets.

One approach we can take to come to an eventual parity with the PropertyControls, is to have a ControlGenerator, which generates query form controls based on the configuration. This will lead us to eventually use a single `Control` component which generates the controls for both the property pane and query forms.

The underlying similarity between PropertyControls and Query form controls is only the fact that the controls are rendered based on a configuration. If we decide to merge the two controls, we will have to achieve parity w.r.t the config structures as well.

**Comment by sharat87** [comment]
Looks like this is not supported on section elements. Is that part of the idea here or if not, can we add that as well. For example, I have the following in a form:

```JSON
{
  "sectionName": "Query",
  "id": 2,
  "hidden": {
    "path": "actionConfiguration.pluginSpecifiedTemplates[0].value",
    "comparison": "NOT_EQUALS",
    "value": "GET_COLLECTION"
  },
  "children": [
    {
      "label": "Where Condition: Field Path (leave emtpy to not apply any conditions)",
      "configProperty": "actionConfiguration.pluginSpecifiedTemplates[3].value",
      "controlType": "INPUT_TEXT",
      "initialValue": ""
    },
    {
      "label": "Where Condition: Value",
      "configProperty": "actionConfiguration.pluginSpecifiedTemplates[5].value",
      "controlType": "INPUT_TEXT",
      "initialValue": ""
    }
  ]
}
```

Here, I want the `hidden` condition to apply to *all* the controls in this section. Should this be a separate new issue?

**Comment by akash-codemonk** [comment]
@sharat87  This was for individual fields. Hiding a section of fields could be a separate issue.

**Comment by sharat87** [comment]
Opened new issue for adding support for sections of controls at #1804.
