### ISSUE TITLE
[Bug]: Reset action is failing intermittently with an exception

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#16592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Test automation involving reset action of all widgets is seen failing for specific tests.

### Steps To Reproduce

1.Make sure you have Text Widget / CheckboxGroup widget / Submit widget
2.Bind Text box to display the selected valur in checkbox i.e {{CheckboxGroup1.selectedValues}}
3.Similarly bind Submit button on click to reset the checkboxgroup widget to reset. i.e. {{resetWidget("CheckboxGroup1",true).then(() => showAlert("success"))}}

Expected:
Widget should reset on click of submit button

Actual:
Intermittently the reset is not happening and below issue is seen in attachment
<img width="665" alt="Screenshot 2022-09-06 at 6 34 08 PM" src="https://user-images.githubusercontent.com/67676905/188645773-dadc08c9-8f1d-40de-b559-fd3b3aa80dc1.png">

Note : this is not related to CheckboxGroup alone its seen with other widgets as well

### Version

v1.7.15

**Comment by Aishwarya-U-R** [comment]
Seems a script issue, fixed that. Hence closing the bug.
