### ISSUE TITLE
[Bug] In MySQL prepared statements, it is impossible to use numeric values with leading zero as strings

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#16600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Consider a MySQL query with the following SQL, where column `col` is of type `text`:

Prepared Statement: `ON`

```sql
update x set col = {{"0123"}}
```

This sets the value of the column to `0123` when **not** using stored procedures and `123` when using stored procedure. The reason seems to be that we are identifying this value as an _integer_, because `Integer.parseInt` succeeds, however, in doing so, we lose the leading zero. The leading zero here is important which is why the column was defined as `text` type instead of a numerical type.

### Steps To Reproduce

1. Go to the MySQL query pane and turn on the prepared statement
2. Write a MySQL update query like `update x set col = {{"0123"}}`
3. Now execute a select query on table x e.g. `select * from x`
4. You will notice that the col is having value of `123` instead of `0123`

### Version

Cloud / Self Hosted

**Comment by subrata71** [comment]
Similar [issue](https://github.com/appsmithorg/appsmith/issues/4056) for Postgres which was closed a long ago.

**Comment by subrata71** [comment]
## Current Workaround

**Prepared Statement:** `OFF`
Wrapping with quotes and turning off prepared statements should work. 
Sample query to test this behaviour : `select '{{"009883"}}' --leading zeros are kept intact`

**Prepared Statement:** `ON`
# Problem Statement
With the prepared statement turned on the problem with leading zero becomes apparent. 

```
SELECT 
*
FROM your_table 
WHERE col = {{Input.text}} — e.g. Input.text = "098373"
```

In the above query although Input.text is having value with leading zero but the server will identify this as an integer. The server will execute a query like this 
```
SELECT 
*
FROM your_table 
WHERE col = '98373' --leading zero has gone
```

## Workaround (MySQL)
### 1) Using CONCAT method
```
SELECT 
*
FROM your_table 
WHERE col = CONCAT('0', {{Input.text}})
```

### 2) Using LPAD method (Can be used to prepend any number of zeros)

`SELECT LPAD({{"09988"}}, 5, '0') as output;`

**Comment by btsgh** [comment]
Tested scenarios around this issue. The testcases run against this bug can be found [here](https://docs.google.com/spreadsheets/d/1Dj4loojZza3djtGztabO28wEJcH5zrch8vjcSKWmB8o/edit?pli=1#gid=803809111)
Some issues have been raised, but none of them are blockers as on detailed analysis by Subrata, they seem to be behaviors of the SQL db, and would mostly needed to be handled through documentation or error handling. 
Moving this to Done.
