### ISSUE TITLE
[Docs]: [Rehaul] - SuperAdmin | Admin Settings 

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#16603]
Please also:

* add more details of what you can do in the admin settings page. Right now this doesn’t link to nor explain how email settings or other settings can be accessed through UI

Refer to the[ discussion thread.](https://theappsmith.slack.com/archives/C03C1PPUHDW/p1662535881333239)

Merged #13804

There's not much detail in what the admin settings are, and a user was blocked by lack of information.

Docs page for reference:

https://docs.appsmith.com/setup/instance-configuration/admin-settings

**Comment by jnikhila** [comment]
@spark-c - Do you think we can merge the #13804 issue?

**Comment by spark-c** [comment]
Sounds good, I think this will resolve that older issue also.
