### ISSUE TITLE
[Bug]: The no result found screen appears for a blink second when the user clicks on Audit log menu

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The no result found  screen appears for a blink second when the user clicks on Audit log menu
https://www.loom.com/share/50350788b77547edb94a5a4ee3760e56

### Steps To Reproduce

1. Lodin as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. For a blink sec the "no result found error is displayed"

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is fixed. Wait for latest DP to test.
