### ISSUE TITLE
[Bug]: The dropdown popup should not open by default when user deselects any events from the dropdown

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The dropdown popup should not open by default when user deselects any events from the dropdown
https://www.loom.com/share/af3d9394ba704d8ba5400376c4398bee

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. click on events dropdown select multiple events
5. Now from those events just deselect one event from clicking on close icon
6. The dropdown opens up by default

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
Not an issue anymore. We are not providing close button.
