### ISSUE TITLE
[Bug]: CI failure - Reconnect modal seen randomly when Navigating to HomePage

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#16627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Reconnect Missing Data Credentials popup is seen on clicking Welcome tour button. As a result CreateNewApp_spec.js is failing

### Steps To Reproduce

1.Login to App.
2.Click on Welcome Tour button

Expected:
Welcome tour should begin

Actual:
Incorrect popup "Reconnect Missing Data Credentials" is seen intermittently
<img width="1038" alt="Screenshot 2022-09-08 at 9 46 21 AM" src="https://user-images.githubusercontent.com/67676905/189033068-0ec08129-b27b-46a9-a46d-0a3957f091b3.png">

https://user-images.githubusercontent.com/119562824/233326867-308c410a-42e4-4169-8cd1-e891674ecfa9.mp4

### Version

v1.7.15

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/32711/test-results/a592ea0e-a783-4a38-94a1-7cb3652de782/video) with this failure

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/35834/test-result) with this failure - [Logs](https://github.com/appsmithorg/appsmith/files/11685088/59_ci-test-limited.ci-test-limited.58.txt)

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/7598/test-results/15ac1dd5-a301-423b-8164-ac131cec5b4c) with this failure - [Logs](https://github.com/appsmithorg/appsmith/files/11718845/1_ci-test.ci-test.0.txt)

**Comment by akash-codemonk** [comment]
Able to replicate manually. This is a bug have created an issue https://github.com/appsmithorg/appsmith/issues/24665.
Will close this once we have a solution for the bug.

**Comment by akash-codemonk** [comment]
I have added a workaround for the test. It shouldn't be failing any more. The test has a workaround. Closing this issue. 
cc @Vijetha-Kaja @Aishwarya-U-R

**Comment by Aishwarya-U-R** [comment]
@akash-codemonk - Whats ETA for actual fix?

**Comment by akash-codemonk** [comment]
Probably by end of this month.
