### ISSUE TITLE
[Feature]: Oauth 1.0 Support?

### ISSUE THREAD

**Issue by disl-pdavid** [appsmithorg/appsmith#16623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi!  I've got some legacy systems API that are using OAuth 1.0 with a consumer key and consumer secret but I cannot seem to find an option to use an OAuth 1.0 implementation for API accesss.  Is this something that is considered (or already attained through some other means)?

### Why should this be worked on?

Some APIs still require an OAuth 1.0 workflow for accessing protected endpoints.

**Comment by Nikhil-Nandagopal** [comment]
@disl-pdavid Thank you for the feature request. I don't believe we support this yet but we'll look into how we can support this

**Comment by disl-pdavid** [comment]
Honestly, this is probably a super-low importance for most people (myself included).  In some cases just manually obtaining an access token is likely good enough. :)  Thank you!
