### ISSUE TITLE
[Bug]-[7152]:Download image using action selector doesn't work

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i add a binding in download for image either using camera or using the image widget. I am unable to download the image. 

https://www.loom.com/share/60f6f0abe2b94cbeb5b4fb14a2754e45

### Steps To Reproduce

1. Add a new camera widget
2. Add a new button
3. Set button's onClick to download
4. Add an binding to download the image
5. Click on download
6. Observe it doesn't get downloaded

### Version

Production

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 @ohansFavour can we get this fixed? The download function has been broken forever

**Comment by bharath31** [comment]
This is a bug and 100% of users using the download action on the button widget would face this issue. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 295 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
@arunvjn should this get fixed as a part of blob changes for custom js libs?

**Comment by arunvjn** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/17895
