### ISSUE TITLE
[Bug]: SQL server unable to connect if password has special characters ';/>

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#16633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Error occurred when the password begins with `';/>`
- Error thrown was `Driver com.microsoft.sqlserver.jdbc.SQLServerDriver claims to not accept jdbcUrl,`
- Escaping characters also did not work

### Steps To Reproduce

1. Try to connect to a SQL server with password having some special characters like `';/>`
2. Unable to connect

### Version

cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6l3bg)

**Comment by AmanAgarwal041** [comment]
> Conversation from the user

I'm currently using Appsmith v1.7.1.

I think the issue is with the semi-colon (;) in the password. 
After inputting the password I get this error message (I'm changing the server and credentials):
`Driver com.microsoft.sqlserver.jdbc.SQLServerDriver` claims to not accept `jdbcUrl`,
`jdbc:sqlserver://IP:PORT;user=user;password=<masked>;/>;`

So it only recognizes the first character before the semi-colon as the password, because that's the only part that's "masked"

**Comment by sumitsum** [comment]
Closing because fixed [here](https://github.com/appsmithorg/appsmith/pull/25094).
