### ISSUE TITLE
[Bug]: Camera widget is unable to capture high quality images

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using camera widget, the image resolution is low which leads to blurred images

### Steps To Reproduce

1. Add a new camera widget
2. Take a photo from phone
3. Observe the resolution of images is lower than expected.

### Version

Production

**Comment by developer-honoru** [comment]
I linked the native app with a separate web view.

https://blog.naver.com/spring1a/222863510106

https://washswat.slack.com/files/U03K2BQBA64/F04285V5XDE/screen_recording_20220901_000251__1___1_.mp4
