### ISSUE TITLE
[Feature]: Ability to copy text from a Text Widget

### ISSUE THREAD

**Issue by PaulMcF1987** [appsmithorg/appsmith#16644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have created an app to store all information on certain projects. I then have other areas when I copy the information to.

I was absolutely amazed, when I found that I was not able to highlight the text from the appsmith app to then copy (Ctrl+v) the then paste into the other program.

### Why should this be worked on?

Copying and pasting is something people who work with computers do daily. It helps them to do things quicker and helps to take the Monotony out of the tasks.

I feel that copying and pasting of text is a very basic requirement that everyone who uses appsmith should be able to benefit from.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika this seems like a bug

**Comment by yaldram** [comment]
@PaulMcF1987 I cannot re-produce this anymore, you cannot select and copy text in preview and edit modes but in deployed apps we are able to select and copy text from the Text Widget. Please verify. Thanks.
