### ISSUE TITLE
[Bug]: In the application deployed event there is a missing data field

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the application deployed event there is a missing data field i.e "Visibility": Private
![Uploading image.png…]()

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. now check for application deployed event
5. in JSON check for the Data "Visibility": Private which is currently missing

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by vishnu-gp** [comment]
@RakshaKShetty This is available on EC2 now.

**Comment by vishnu-gp** [comment]
@RakshaKShetty All application object will have visibility now.
