### ISSUE TITLE
[Bug]: The Same events are displayed multiple times

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Same events are displayed multiple times beacuse same API is called 2 times in network
- [ ] when user edit the workspace name from general tab the 2 update events are added 
- [ ] when user change website name in general tab the unnecessary events are displayed 
- [ ] when user navigate to member tab from setting menu the 2 events are added 
- [ ] When user clones an app, and renames it, we get two events of the same description

### Steps To Reproduce

1. Login to application 
2. click on setting tab
3. now in general tab edit website placeholder
4. click on members&setting menu in home page
5. click on audit log
6. The same event is displayed 2 times

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
These are Appsmith events and audit logs just surfaces these problems up. These would have to be fixed at the source or at BE while recording the events.

**Comment by vishnu-gp** [comment]
> These are Appsmith events and audit logs just surfaces these problems up. These would have to be fixed at the source or at BE while recording the events.

@IAmAnubhavSaini We noticed multiple API calls happening for these requests from FE. Any idea why that is happening?

**Comment by IAmAnubhavSaini** [comment]
I have no idea. And this has to be assigned to the pod that is the source of the duplicate events.

**Comment by hiteshjoshi** [comment]
This doesn't require a solve. This happens only in the development servers where react renders twice. Based on discussion with @berzerkeer @IAmAnubhavSaini

**Comment by berzerkeer** [comment]
Hey no @hiteshjoshi , that was not the case. I checked we are not enabling strict mode nor using React 18. So the problem lies somewhere else. We just had that discussion as a possibility but didn't conclude 😅 . So this should be reopened AFAIK.Sorry that this was not communicated to you prior.

**Comment by infinitetrooper** [comment]
@trishaanand - Is this still an issue we need to solve?

**Comment by gurel** [comment]
We see the same problem, launching an app in view mode sents a `viewed` event for every page of the app even though they are not rendered. And then it sends another one for the active page.

So if i have an app with 3 pages (page1, page2, page3), when i enter the app the audit logs will say (page1,page2,page3,page1). 

Consecutive page switches work correctly.
