### ISSUE TITLE
[Bug]: The event  Id needs to be removed from the JSON

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The event  Id needs to be removed from the JSON
![image](https://user-images.githubusercontent.com/45958978/189127501-d15e20d1-29cf-413f-b8a7-afeaec90ee6a.png)

 

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. Open the event data
5. verify the display of  event id 

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is log/record id in database. This is harmless and also an extra data point for admin/super-user as this would make it easier to search in database.
