### ISSUE TITLE
[Bug]: The signup event should contain "role field" in the json

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The signup event should contain "role filed" in the json
<img width="510" alt="image" src="https://user-images.githubusercontent.com/45958978/189128336-3b4b2bdc-70ed-409d-913a-10e154e64252.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/189128402-b106faf2-aab0-45bd-99e0-ae3171d75c57.png">

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. click on events dropdown select user signup event
5. open event data the role field is missing 

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by AnaghHegde** [comment]
@vuiets Is this the expected behaviour? I don't remember deciding on this for the signup event.

**Comment by AnaghHegde** [comment]
@vuiets Continuing from the notion doc, we agreed that we will not need this. hence closing the issue.

**Comment by vuiets** [comment]
Reason for closing this
> Did add this for the `user.signed_up` event but we need this in the `user` object in general? We could cover this after _role-based access control_ is out.
