### ISSUE TITLE
[Bug]: The Date filter functionality is broken in audit log

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Date filter functionality is broken
https://www.loom.com/share/8e2e7b3cae5147d1a9f0650dba61197b

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. Select day as today
5. now select the date filter as last 30 days
6. the functionality doesn't work as expected

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This looks like FE issue. When user is far down the scrolled page, load on scroll stops working.

**Comment by IAmAnubhavSaini** [comment]
@AnaghHegde Could you check it from BE that this is not BE issue, just to be sure.

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini I can see that the date filter is working properly when I tested with postman locally. As you mentioned it could be because of the load on scroll issue.

**Comment by IAmAnubhavSaini** [comment]
This has been fixed. @RakshaKShetty please retest and reopen if not fixed.
