### ISSUE TITLE
[Bug]: The event dropdown looks to be misaligned

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The event dropdown looks to be misaligned
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/189127014-e224b493-65eb-409e-9394-6d10520e8ab3.png">

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. click on events dropdown 
5. The events dropdown seems to be overlapped

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is because the height of the browser viewport is low, due to which the opened options container wants to go up. 

@Debsourabh @vuiets Any idea about how tall we want the dropdown options container we want to be. It is 500px in the case above.
