### ISSUE TITLE
[Bug]: Both Email and username is displayed with email id's in JSON

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The username is displayed as email id in JSON
![image](https://user-images.githubusercontent.com/45958978/189275930-d5882e8a-70b4-4a65-874e-162b4236e562.png)

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. Open any one event 
5. inside the json check for users section
6. Check the email and name part both are displayed with emails

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by AnaghHegde** [comment]
This is fixed
