### ISSUE TITLE
[Bug]: The fork event name is not displayed as expected

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The fork event name is not displayed as expected
<img width="643" alt="image" src="https://user-images.githubusercontent.com/45958978/189128958-bc061e29-e1ec-4dda-921b-8a4a7eafaa04.png">
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/45958978/189129030-91289fdf-f7eb-4204-8323-f155bb28ea24.png">

### Steps To Reproduce

1. Login as admin
2. Now click on member and setting tab
3. now from general tab click on Audit log menu
4. click on events dropdown select Application forked event
5. the fork event name is not displayed as expected in prd

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This needs changes from BE first. @vishnu-gp  let me know when this is done from your side.

**Comment by vishnu-gp** [comment]
@IAmAnubhavSaini BE changes for this have been pushed to the feature branch.

**Comment by vishnu-gp** [comment]
@RakshaKShetty This is completed from FE & BE
