### ISSUE TITLE
[Bug]: The events are logged but the event name are missing from the event list dropdown

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The events are logged but the event name is missing from the event list dropdown
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/45958978/189291914-63cf97f7-6b71-43d9-b076-d2e8c3123b85.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/45958978/189291944-ceeefbe5-5dcb-460f-bf23-53e4fe0fe250.png">
The missing event names are :
1.Page viewed
2.Application deployed

### Steps To Reproduce

1. Login as admin
2. Now deploy the app
3. Now click on member and setting tab
4. now from general tab click on Audit log menu
5. check for the event page view and application deployed
6. Both the events are missing from the event list dropdown 

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by vishnu-gp** [comment]
Fixed
