### ISSUE TITLE
[Bug]: Unable to connect to supabase db from prod

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to connect to a Supabase db, the test connection fails

### Steps To Reproduce

1. Add a Postgres datasource
2. Enter the following details -
host: db.broabfvoglgyhmaftvdc.supabase.co
port 5432 
database : postgres 
user:postgres
password :WuSXznzyOQXrAlcd  (http://db.broabfvoglgyhmaftvdc.supabase.co/)
3. Click on Test. An error comes up as below -
<img width="1286" alt="Screenshot 2022-09-09 at 11 23 29 AM" src="https://user-images.githubusercontent.com/101863839/189281981-03426ee6-21df-42b4-83f6-5529a1de645e.png">

https://www.loom.com/share/ebbb232340be41838563b5eb0193409c

### Version

Production

**Comment by rohan-arthur** [comment]
@btsgh I was not able to reproduce this, the test was successful and was also able to create a query. Kindly retest and reopen if required.

**Comment by btsgh** [comment]
@rohan-arthur  - ok.. this did seem like an intermittent issue. Will keep a watch out for it.
