### ISSUE TITLE
[Bug]-[3000]:Mongo plugin - Query creation via templates is broken

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When clicking on `new query` from the active datasources page, templates for queries is not shown. 
2. When creating a query via the `Add` button on the datasource structure shown on the left hand entity explorer, the template query is not getting generated properly. 

### Steps To Reproduce

1. Go to active datasources page, click on new query for Mongo plugin. See that it does not ask to choose template query as it does for say MySQL plugin. 
2. Go to left hand entity explorer and unfurl collections for a Mongo datasource. Click on the `Add` button and choose a query type. Check that the generated form is incomplete. 

### Version

cloud

**Comment by rohan-arthur** [comment]
mongo 6m usage: 1500
we also lost about 40% of July's 1200 users by August, so this should be prioritised to make the experience better for new mongo users. 

Until the last quarter, Mongo has been growing at about 50% per quarter, so expecting this issue to affect the next 750 users.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 750 |
| Effort (months)  | <<number>> |

**Comment by sneha122** [comment]
- I am not able to replicate 2nd case, all fields are getting populated correctly it seems
- For the first case, the template is shown when we select `Raw` option from the commands dropdown, do we need to modify that and show templates initially itself? If that is the case, how should we show the templates? @rohan-arthur @sumitsum

**Comment by sumitsum** [comment]
As mentioned by @sneha122 we need to take a re-look at how we want to design the templates experience for our users. cc: @rohan-arthur @parth-appsmith

**Comment by rohan-arthur** [comment]
we removed the old static queries, so closing this issue
