### ISSUE TITLE
[Bug]: list selection not getting updated immediately

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the list widget has an attribute called `selectedItem`, but I don't know how to use it. 

1. there are no selection - based properties for the list (like for table, we have `default selected row`, `on row selected`, etc.
2. but when I type js, I see suggestion for `List1.selectedItem`
--> this is already confusing

However, a bigger problem is that the selection (blue border) is not happening with mouse click somehow. It happens when:
1. I click on a list item
2. go away from the canvas
3. come back to canvas
--> now, I can see that the list item I last clicked has the blue border

### Steps To Reproduce

https://www.loom.com/share/89d5fd0d2d9d4482a481f8be1fc630d7

### Version

Cloud

**Comment by dilippitchika** [comment]
Fixed in list v2
