### ISSUE TITLE
[Task]: Rename TriggerUtils.java

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16670]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

Rename `TriggerUtils.java` to `RestApiTriggerUtils.java`
Ref: https://github.com/appsmithorg/appsmith/pull/16554#discussion_r967011552

**Comment by bhuvanaindukuri** [comment]
You may assign it to me. Here is the PR created for the fix: https://github.com/appsmithorg/appsmith/pull/16687

**Comment by sumitsum** [comment]
@bhuvanaindukuri thanks a lot for showing interest in this issue. I have assigned this issue to you. I will be reviewing your PR as well. Happy coding :)

**Comment by sumitsum** [comment]
@appsmithguru can you please check out the comment here before raising the PR : https://github.com/appsmithorg/appsmith/pull/16687#issuecomment-1246637097 cc: @sondermanish
