### ISSUE TITLE
[Bug]: Unable to add GET parameters conditionally on an API request.

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#16683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have the following paginated API request: 
```
https://api.vercel.com/v6/deployments?limit=4
```

The pagination is done with `from` and `to` parameters

- If I wanted to get the next page, I should pass the next cursor from the response to `from` parameter of the request as follows:
  ```
  https://api.vercel.com/v6/deployments?limit=4&from=1662731501677
  ```

- If I wanted to get the previous page, I should pass prev cursor from response to `to` parameter of the request:
  ```
  https://api.vercel.com/v6/deployments?limit=4&to=1662735248196
  ```

This is how I constructed the URL on Appsmith's API pane:
```
https://api.vercel.com/v6/deployments?limit=4{{appsmith.store.getDeploymentsPaginationQuery}}
```

where I conditionally set the appsmith store `getDeploymentsPaginationQuery` as either `&from=1662731501677` or `&to=1662735248196` or `''` (for the first request)

But, what I end up having is args like this: 
```
{
  "limit": "4&from=1662731501677"
}
```

_Note: [Vercel's Documentation](https://vercel.com/docs/rest-api#endpoints/deployments/list-deployments) for reference_

### Steps To Reproduce

Make the following API request in Appsmith and observe the args section of the response:
```
https://echo.hoppscotch.io/v6/deployments?limit=4{{Math.random() > 0.5 ? '&param1=5' : '&param2=6'}}
```

### Version

Cloud

**Comment by rohan-arthur** [comment]
Hi @aswathkk , thanks for reporting this issue! would you please explain what the expected result should be instead of:
`
{
"limit" : "4&from= 1662731501677"
`
also, are you able to make this work by using the params?

**Comment by aswathkk** [comment]
@rohan-arthur 
Here the value of `limit` parameter becomes `4&from=1662731501677`.
I wanted that value to be only `4` and it should treat the string after 4 to be the next set of parameters.
So, the entire argument should be
```
{
  "limit": "4",
  "from": "1662731501677"
}
```

I was able to make this work using params since Vercel also accepts empty values like `limit=4&from=&to=`. Not sure whether all API endpoints work like this or not.


The step to Reproduce I wrote 4 days back is not working anymore!

### Here's the steps to reproduce this issue:
1. Create a JSObject (JSObject1)
  ```js
  export default {
	myFun1: () => {
      return Math.random() > 0.5 ? '&param1=5' : '&param2=6';
	}
  }
  ```
2. Make the following API request in Appsmith and observe the args section of the response:
```
https://echo.hoppscotch.io/abcd?limit=4{{ JSObject1.myFun1() }}
```

Response:
```json
{
  "method": "GET",
  "args": {
    "limit": "4&param1=5"
  },
  "data": "",
  "headers": {...},
  "path": "/abcd",
  "isBase64Encoded": true
}
```

The `args` should've been:
```json
 "args": {
    "limit": "4",
    "param1": "5"
  },
```

**Comment by Nikhil-Nandagopal** [comment]
This seems related to #14706
