### ISSUE TITLE
[Bug]: GSheet | Dropdowns in the GSheet query page are non-resposive

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The drop-downs in the GSheet query page do not work at all.
**Note:** This is happening for both old & new apps.
https://www.loom.com/share/38eeecfcafa0426cb69b722a96510d21

### Steps To Reproduce

1. Create/Go to an old app.
2. Create a new GSheet query.

### Version

Cloud

**Comment by prapullac** [comment]
Verified on the Release
