### ISSUE TITLE
[Bug] Rest Api content type url encode doesn't url encode on the plugin before making the WebClient call (Also make documentation changes)

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#1669]

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @trishaanand can we please pick this up and close it?

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : I seem to remember that we were doing this on the server but we removed this. I can't remember anymore what caused this change. 

To ensure that we solve this correctly, I propose that we first decode the data that we are getting and compare it to the original. If it changes, then what the developer user is sending is already encoded. No need to change anything. If it doesn't change, then the server encodes this data and then sends it out. This ensures that we are handling both the scenarios (where the developer user encodes the data, and the developer user sends out data in plain text)

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : From my preliminary google search, there is no 100% solve for this. Could we add a messaging on the API Pane in case the user chooses form url encoded as the content type that we expect decoded data? This way, in most scenarios the user would send decoded/raw data and the server would do the encoding. In the rare scenarios where the user has encoded data and wishes to send this directly, the messaging would ensure that the user first decodes the data and then sends it. 
Let me know your thoughts on this.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum @trishaanand I see an open PR for this, can we merge this?

**Comment by sumitsum** [comment]
Hi @Nikhil-Nandagopal, there is one review comment that I am addressing now, post which we should be able to merge it by tonight / latest by tomorrow.
