### ISSUE TITLE
[Bug]: Fix label for all the widgets post release merge

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#16692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Changes for LabelWithTooltip are discarded after the release merge.

### Steps To Reproduce

1. Pick any widget with a label.
2. Enter a long label.
3. Set alignment to top.
4. Enable Auto Height.
5. Observe there are no changes.

### Public Sample App

https://appsmith-qhryi4omr-get-appsmith.vercel.app/

### Version

Cloud

**Comment by ankurrsinghal** [comment]
Please verify it here, https://appsmith-git-feat-label-auto-height-get-appsmith.vercel.app/

**Comment by Sripriya93** [comment]
Working fine, Moving to done
![image.png](https://images.zenhubusercontent.com/627b57d87180949256bd1e01/403a089d-6cb8-4804-8957-cf73c1563d6d)
