### ISSUE TITLE
[Bug]: onClick actions are partially hidden for the menu widget.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#16697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The first few options in the onClick event section are hidden in the dropdown and the they are not accessible on scrolling either.
However, they are seen once the screen size is changed when dev tools are opened

https://www.loom.com/share/39cfd3cb57f24d04a4150d607e487975

### Steps To Reproduce

1. D&D a menu widget.
2. Click on the settings (gear icon) for any one of the menu items.
3. Select the dropdown under onClick.
4. Notice that the first few options are hidden

### Version

Production

**Comment by Sripriya93** [comment]
Happens with Button Group widget as well

Navigate from More ->Menu items -> First option "Settings" -> Events "Onclick"
![image](https://user-images.githubusercontent.com/104895602/189822519-2a29c38e-4452-456d-94dc-df716e48d4c3.png)

**Comment by Sripriya93** [comment]
Happens with Modal widget as well.

![image](https://user-images.githubusercontent.com/104895602/189837953-5efbcf14-640d-4994-81a4-aa9a334011b5.png)

**Comment by Sripriya93** [comment]
Working fine. Marking as verified, checked for Menu, Button group and Modal widget
![image](https://user-images.githubusercontent.com/104895602/191908586-7092ff6e-bcc8-4109-9633-1920183dea7a.png)
