### ISSUE TITLE
[Bug]: moustache+quotes formatting goes wrong in graphql body | autocomplete fail 

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/ccf9fccc89064ee7b4230aaf5bf3cc52 

1. pairing of moustache brackets and quotes "" causes a parse error (red highlight, no error)
2. after this error, autocomplete does not work anymore

### Steps To Reproduce

see video

### Version

Release

**Comment by AmanAgarwal041** [comment]
Created another issue for highlighting error #17193
