### ISSUE TITLE
[Bug]: In Audit log the alignment looks off when the email id is too big .

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The alignment looks off when the email id is too big. this happens both in the Users column and also in the Users Dropdown
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/189814655-bfdcd3d5-6986-4990-885b-cbe190dde7c1.png">

### Steps To Reproduce

1. Signup with a new email id in ec-2 instance
2. Now login with demo user 
3. Go to audit logs
4. Validate the display of email under users column nd also in users Dropdown

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
The list of emails is going up due to low vertical height of the viewport; that pushes the container upwards. 

The email will be truncated due to width of the container.

@vuiets @Debsourabh Need you input.

**Comment by vuiets** [comment]
@Debsourabh what do we have in the Design System for such scenarios?
