### ISSUE TITLE
[Bug]: API response JSON rendering is too slow

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. run api call on `https://restcountries.com/v3.1/all`
2. expand the bottom drawer
3. see that the response is truncated, and takes a long time to render in full
PS: this problem also exists for graphql

### Steps To Reproduce

https://user-images.githubusercontent.com/94514895/189814756-6b4c9fc3-62d9-467d-9d08-af66012fe629.mov

### Version

Cloud

**Comment by rohan-arthur** [comment]
so found out that the wait is actually not that long - the rendering completes when I interact with the pane in some way - either a click or a scroll. At this point, the response gets rendered properly.

https://user-images.githubusercontent.com/94514895/189823030-47dc9d2d-f3a0-44af-b1ed-1a253984341f.mov

**Comment by ChandanBalajiBP** [comment]
This also applies to RAW format also

**Comment by ChandanBalajiBP** [comment]
Altering the `viewportMargin` param of `codemirror` component will `render` the required number of rows.
Current `viewportMargin = 10`. Implies `10 extra rows` below and above apart from the rows visible on the screen are rendered.
By setting `viewportMargin= Infinity` => this delay won't be observed but `component render will slow down` as all rows are rendered at one go=> hence not the best option.

But setting `viewportMargin= 50`, we can have a workaround for this, as it's highly unlikely that a user can view more than 50 lines of code on a single page. Tested on `2560x1440` screen

But before altering this we have to consider the `impact on performance.`

**Comment by ChandanBalajiBP** [comment]
Performance with different `viewportMargin`
| viewportMargin | Attempt1 | Attempt2 | Attempt3 | Attempt4 | Attempt5 | Average |
|----------------|----------|----------|----------|----------|----------|---------|
| 10             | 160      | 164      | 137      | 130      | 162      | 151     |
| 50             | 184      | 167      | 146      | 175      | 182      | 171     |
| 100            | 180      | 177      | 178      | 190      | 177      | 180     |
| 1000           | 293      | 327      | 256      | 291      | 250      | 283     |
| 2000           | 434      | 428      | 390      | 423      | 386      | 412     |
| Infinity       | 7491     | 7161     | 6067     | 6257     | 6942     | 6784    |

**Comment by prapullac** [comment]
@ChandanBalajiBP : Completed testing the PR and looks good to me
