### ISSUE TITLE
[Bug]: Misplaced top bar in 'Workspace Settings' page

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#16712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Just noticed that the top bar on the _Workspace Settings_ page, with the 'Members in Example Apps' title, search bar and _Add Users_ button is misplaced in the hierarchy. Ideally, this should come inside the 'Members' tab instead.

<img width="1440" alt="Misplaced top bar with members " src="https://user-images.githubusercontent.com/1571370/189828438-79c2f54d-dc45-4888-b4fa-dec3248f7699.png">

Also, since we've got both _Members_ and _General Settings_ here, could we rename the _Settings_ in the Workspace menu to _Members and Settings_ to keep it consistent with our direction for _Admin Panel_.
<img width="241" alt="Workspace menu" src="https://user-images.githubusercontent.com/1571370/189828730-3083b4ad-dc73-4247-85b0-c6e364336643.png">

### Steps To Reproduce

1. As a workspace admin, click on _Settings_ in the Workspace menu
2. Take a look at the top bar in the _Settings_ page

### Version

v1.8.0

**Comment by ankitakinger** [comment]
Fixed in [#19113](https://github.com/appsmithorg/appsmith/pull/19113)
