### ISSUE TITLE
[Bug]: The event description name is not clear for the Instance setting event

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The event description name is not clear for the Instance setting event
<img width="586" alt="image" src="https://user-images.githubusercontent.com/45958978/189830899-ccc9bd90-fda8-4a78-b8f2-eb67551e22a1.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/45958978/189830938-31a2d56d-e9bb-4210-bf57-4c2ac8de2c38.png">

### Steps To Reproduce

1. Login as demo user in ec-2 instnace
2. now click on member &setting tab
3. Remove the google auth from auth tab
4. Now got to audit log page
5. Check the event name displayed

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is fixed.
