### ISSUE TITLE
[Bug]: Table widget crashes when editableCell is undefined on page load

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#16725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In deploy mode, if the Table widget editable cell value is undefined, the whole application crashes.
https://discord.com/channels/725602949748752515/760761686549463060/1018991583057682484

### Steps To Reproduce

Unable to repro on my end. Only happens on the user's application.
refer https://discord.com/channels/725602949748752515/760761686549463060/1018991583057682484

### Version

self hosted

**Comment by chandannkumar** [comment]
Tested Table widget v2 with all functionalities and it is working as expected
