### ISSUE TITLE
[Bug]: Console statements are printed twice the number on debugger as that seen on the browser console tab

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When executing a function on page load and this function contains console statements, then these statements get printed twice on the debugger whereas, on the browser console tab, we only see it appear once,

### Steps To Reproduce

1. Set a function to run on page load and ensure this function contains console statements
2. Refresh the page and observe the console statements on the browser console and on the debugger - console statements appear double the number of times on the debugger (i.e. if the statements are printed twice on the browser - once during parsing and once when the function is executed, then it's printed 4 times on the debugger)

https://www.loom.com/share/487afc4baea7413cae8351edf8a32350

### Version

Cloud

**Comment by bharath31** [comment]
not able to reproduce this anymore
