### ISSUE TITLE
[Bug]: Selected API/Query is not indicated when the 'move/copy API' popup menu is open

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#16736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an API is selected in the Explorer, its background is grey to show that it’s the current API being edited. But we do not have any indication of the ‘selected’ API when using the inline menu to copy/move APIs. It’s not clear which API is being copied/moved.

The background changes while hovering, before opening the menu. But then it shows as unselected once you’re in the menu. Can we keep showing the selected state while the menu is open?

### Steps To Reproduce

![Screen Shot 2022-09-13 at 10 15 43 AM](https://user-images.githubusercontent.com/24459976/189975767-295e8b18-119c-4805-971b-49ff31dabbf2.png)
![2022-09-13 10 24 32](https://user-images.githubusercontent.com/24459976/189975556-8324f09e-9809-41b4-911d-ca4dc578382c.gif)

### Version

1.7.15-SNAPSHOT

**Comment by kocharrahul7** [comment]
The current hover and selected state are identical. This will likely leed to more confusion. For now we will leave it, and update this when the new design system is ready with different hover and selected states

**Comment by rohan-arthur** [comment]
More discussion here: https://theappsmith.slack.com/archives/C05FUJNDL0P/p1707393418528229?thread_ts=1707393418.528229&cid=C05FUJNDL0P

**Comment by albinAppsmith** [comment]
Closing this since it is a duplicate issue.
ref: https://github.com/appsmithorg/appsmith/issues/24246
