### ISSUE TITLE
[Bug]: Missing JS toggles in widgets and JSON Form columns

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#16743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Default Country Code property in the Phone Input field has a JS toggle. However, this is missing inside the JSON Form.
<img width="605" alt="Screenshot 2022-09-14 at 11 04 19" src="https://user-images.githubusercontent.com/32227135/190068175-5655466f-2eec-41f0-9d31-f952fa879551.png">
![Uploading Screenshot 2022-09-14 at 11.05.01.png…]()

### Steps To Reproduce

Create a custom column for Phone Input inside a JSON Form. Notice that the Country Code property does not have a JS toggle.

### Version

v1.8.1

**Comment by dilippitchika** [comment]
Phone input regular
1. Allow country code change
Phone input json form
1. Allow country code change
2. Default country code
Currency input regular
1. Allow currency change
2. Decimals allowed
Currency input json form
1. Default currency
2. Allow currency code change
3. Decimals allowed

**Comment by flying-solo** [comment]
@somangshu i would like to work on this issue

**Comment by somangshu** [comment]
Greetings @flying-solo, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by flying-solo** [comment]
Hey @somangshu, can I get some more information about the bug.

**Comment by somangshu** [comment]
Sure, met me know what are the questions you have @flying-solo. This is happening in the phone input field of the json form. 

cc @ashit-rath

**Comment by dilippitchika** [comment]
@flying-solo some context
1. In our property panes inside a widget, we have a js toggle for fields so that users can write js rather than selecting from a list. This helps developers make properties dynamic based on data or users.
2. We need to enable this toggle in the fields i mentioned here - https://github.com/appsmithorg/appsmith/issues/16743#issuecomment-1246264850
3. Please take a look at other fields in the widgets to know how this is being done. Like in the code go to the currencyInput widget and take a look at the properties inside it and see how to add JS toggle by looking at a property which already has a toggle

**Comment by flying-solo** [comment]
✌️cool, will work on it .

**Comment by somangshu** [comment]
@flying-solo please let us know here if you have an open PR which is not yet tagged. We can take it forward

**Comment by flying-solo** [comment]
sorry for the delay i got a medical condition,  you can un assign me i would contribute later

**Comment by somangshu** [comment]
Sorry to hear that @flying-solo, Hope it better for you really soon.
Would love to see you back here for contributions 😃

**Comment by dubey-Ji** [comment]
Heyy i would like to work on this. can u assign me?

**Comment by dilippitchika** [comment]
Greetings @dubey-Ji, thanks for showing interest 🎉 , This is all yours. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by Vishrut19** [comment]
Hey @dubey-Ji  do you need help in it ?

**Comment by trishitapingolia** [comment]
Can i work on this issue ?

**Comment by somangshu** [comment]
Greetings @trishitapingolia, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

**Comment by trishitapingolia** [comment]
> Greetings @trishitapingolia, thanks for showing interest 🎉 , This is all your. Assigning this to you now.
> 
> Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Thankyou for assigning me this issue, I'll be back with a pr soon.

**Comment by chandannkumar** [comment]
Changes made only in widgets and not on JSON form in the PR mentioned in this issue
https://github.com/appsmithorg/appsmith/pull/17725#issue-1415026071
