### ISSUE TITLE
[Bug]: GraphQL is only usable with new workspaces

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. go to app.appsmith.com
2. create new app or open existing app
3. click + to add a new datasource
Two problems here:
1. there is only one options to `create new graphql api`. The second option for `authenticated graphql api` is missing
2. clicking on `create new graphql api` does nothing

Now create a new workspace and follow the steps above, everything works as expected. 

### Steps To Reproduce

![Screenshot 2022-09-14 at 10 41 36](https://user-images.githubusercontent.com/94514895/190068155-93965265-9e34-47c5-b667-4000031900a0.png)

### Version

Cloud

**Comment by sumitsum** [comment]
Closed via https://github.com/appsmithorg/appsmith/issues/16752
