### ISSUE TITLE
[Bug]: GraphQL: installation to few workspace has failed 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It seems that the GraphQL plugin installation to few workspaces has failed due to few interruptions in the migration run when prod clusters were coming up. Re-attempting to install the plugin should fix the issue. 

### Steps To Reproduce

https://theappsmith.slack.com/archives/C03HF7YJ6RF/p1663132345464659

### Version

cloud

**Comment by prapullac** [comment]
Verified the issue and looks good to be merged
