### ISSUE TITLE
[Task]: De-couple PhoneInput & CurrencyInput widgets with Appsmith Design System

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The `Dropdown Original` component from the Appsmith Design System is being used in the PhoneInput & CurrencyInput widgets as of now. We need to decouple them.

**Comment by somangshu** [comment]
cc @KelvinOm @jsartisan

**Comment by ichik** [comment]
Should be solved when we roll out new WDS widgets.
