### ISSUE TITLE
[Bug]-[3200]:Reconnect Datasource Modal is not being triggered when forking apps using Google Sheets datasource

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#16767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The _Reconnect Datasource_ modal does not appear when forking apps using Google Sheets, the way it does for other datasources. 

The app forks successfully, and a new Google Sheets datasource is created in the destination workspace, but the datasource still needs re-authorized. So all the queries are failing in the new app after forking, but we don't prompt the user to fix the datasource connection. 

### Steps To Reproduce

1. Fork the sample app: 
https://app.appsmith.com/app/gsheets-forking-test/page1-6320bef62d40fb444620a8cf
2. Note the new Google Sheets datasource is created, but the _Reconnect Datasource_ modal does not appear. 

### Public Sample App

https://app.appsmith.com/app/gsheets-forking-test/page1-6320bef62d40fb444620a8cf

### Version

Appsmith v1.8.1-SNAPSHOT

**Comment by rohan-arthur** [comment]
Since there is no event raised on forking an app, I am guessing 20% users make use of this feature: 4000
Gsheets represents 20% usage among plugins, so reach: 800

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 800 |
| Effort (months)  | <<number>> |

**Comment by rohan-arthur** [comment]
This needs to be done for hubspot and graphql as well

**Comment by sumitsum** [comment]
> This needs to be done for hubspot and graphql as well

Tracking the GraphQL issue here: https://github.com/appsmithorg/appsmith/issues/17020

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur we definitely have events for forking an app

**Comment by sneha122** [comment]
Conversation related to this issue: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1670935532822039

**Comment by NilanshBansal** [comment]
This issue got completed as part of this PR: #22390
