### ISSUE TITLE
[Bug]: Renaming a page does not rename references to it

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#16779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**When I renamed a page**, I expected that all references to that page would be renamed as well. 

However, what I observed is that **the references were not renamed** and parts of my app were broken.

In my specific case, I renamed a page and places where I had a `navigateTo('myPage', {})` broke

### Steps To Reproduce

1. Create a page called `X`
2. Write a `navigateTo('X', {})` anywhere in another page in your app
3. Check if the navigation works as expected
4. Rename `X` to `Y`
5. Check if the navigation works as expected - you will see the following page (on Chrome) -

![broken_navigation](https://user-images.githubusercontent.com/15727421/190328885-01d0b2a3-aec7-4916-8226-02b39b04ed6a.png)

This happens because the app tried to navigate to `https://Y`

### Version

Cloud

**Comment by pranavkanade** [comment]
@sribalajig In the case of `navigateTo`, the first argument is actually a raw String and not a reference. You'll have to change it manually. So, this is not a bug. Although, you raise a good point here about making it a reference. I'll keep the issue open for more inputs from other team mates.
