### ISSUE TITLE
[Bug]: The Clear-all link will disappear when user does a browser refresh

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The clear-all link disappears when user refresh the page  from the browser window
https://www.loom.com/share/e7739a07e3e84eff9880c93731a0a4b0

### Steps To Reproduce

1. Login as demo user
2. click on member&setting tab
3. click on Audit log menu
4. Now filter by Resourceid
5. do the browser refresh
6. The clear all link will be removed from UI

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is fixed.
