### ISSUE TITLE
[Bug] When an account is deleted the user must be deleted from all the shared application and manage users must be updated

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1678]
Steps to reproduce:
1) Add an account X
2) Share application from different accounts  consider Account B
3) Now delete the account
4) Login into Account B 
5) Navigate to  Manage Users 
and observe

If the account is recreated in the same name and user wants to share the application to the account then the user must delete the account and reshare it 

Observation:
It is observed that under manage Users of Account B the deleted account is still listed and user needs to delete the account name and re share the application.

Expectation:
When the account X is deleted the shared list under manage users must also be updated.

**Comment by Nikhil-Nandagopal** [comment]
@prapullac spoke to arpit and this is via an app exposed to delete from our staging only. It's not part of our product flow so I'm closing this
