### ISSUE TITLE
Task: List v2 - Profile Pagination component

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#16786]
The Pagination component takes more time than expected for on load and re-render. 
It needs to be profiled and verified.

**Comment by somangshu** [comment]
@ashit-rath should this be closed

**Comment by ashit-rath** [comment]
Profiling [compilation](https://www.notion.so/appsmith/Performance-profile-a05bfc3b1bca4ee1bdaf016bc74bce5b)

**Comment by somangshu** [comment]
cc @SatishGandham ☝️
