### ISSUE TITLE
[Bug]: Performance hit with storing multiple logs together

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#16792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, the console log feature stores each log one by one. So for 1000s of logs, there are a lot of redundant updates that go to the subscribed selectors which can be reduced to batched updates.

### Steps To Reproduce

Perf issue seen with console logs in a for loop.

### Version

Cloud

**Comment by Sripriya93** [comment]
As per discussion with @ayushpahwa, Marking as QA verified.
