### ISSUE TITLE
[Feature]: show only one error toast instead of two

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#16804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, if a query fails then two error toasts are displayed. One to show that the query has failed and the other one shows the detailed reason. This confuses the user and also makes the UI looks ugly. Ideally, we would want only one error toast to appear. 
Ref: https://theappsmith.slack.com/archives/C02KTH6EHUG/p1663241700304739?thread_ts=1663241403.228319&cid=C02KTH6EHUG
https://files.slack.com/files-pri/TGA9SH07N-F042HUPPN2F/is_not_supported_in_ps-mysql.png 

### Why should this be worked on?

Improved user experience. 
Better debugging experience.

**Comment by ChandanBalajiBP** [comment]
We will be removing toast messages for action execution. Hence closing this issue for now.

**Comment by ChandanBalajiBP** [comment]
For ref: https://github.com/appsmithorg/appsmith/issues/21490
