### ISSUE TITLE
[Bug]-[3240]:5432 is considered the default port if port is not provided in MSSQL

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#16808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The default port for `MSSQL` database is `1433` but in the source code I’ve found that it’s `5432` which is the default for `Postgres`.

### Steps To Reproduce

1. Go to Datasources -> Create New
2. Choose Microsoft SQL Server as the datasource
3. Provide all the information in the datasource-create page
4. Leave the port blank

### Version

Cloud / Self Hosted

**Comment by rohan-arthur** [comment]
6m usage: 405
although this is a low incidence issue, we should definitely fix this as tech debt, so leaving the reach as 100%

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 405 |
| Effort (months)  | <<number>> |

**Comment by rohan-arthur** [comment]
@vaibh1297 please also document the hard-coded port values for various plugins in notion or ghseets etc. This will help us understand the extent of the problem.

**Comment by Aishwarya-U-R** [comment]
@subrata71 @rohan-arthur - as part of this change - can we also show the default port like a placeholder (something like below)? So user knows what port will be considered incase of leaving it empty - for all applicable datasources?
<img width="307" alt="Screenshot 2022-09-27 at 7 25 51 PM" src="https://user-images.githubusercontent.com/91450662/192546240-663fec3a-e7c0-420b-aa85-71c72d43bed7.png">

**Comment by sumitsum** [comment]
@Aishwarya-U-R @vaibh1297 is also checking if showing a intial value / placeholder is possible.
