### ISSUE TITLE
[Bug]: UI/UX issues in connecting to Git.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#16810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The scrollbar extends over the contents of the modal.

https://user-images.githubusercontent.com/109572422/190558655-11799dea-b8f1-4fe7-930a-aeeb1d508e1f.mov

A "No" prompt option is required 

https://user-images.githubusercontent.com/109572422/190558831-6b7da61f-afe9-4717-9233-5cc4453fe6bf.mov

A hover state is required over the branch.

https://user-images.githubusercontent.com/109572422/190559003-c2369c5d-2b9d-44f1-9c44-31b6bc609a2e.mov

Space between "Deploy your application" and "Commit..." can be reduced

![image](https://user-images.githubusercontent.com/109572422/190559116-da2fdcfc-59e5-41c5-9b8b-2a88f7b85ffd.png)

Hover state/underline is required under the arrow as well to depict that it is clickable
![image](https://user-images.githubusercontent.com/109572422/190559260-fbd17086-d25e-4947-8566-c15fb425b5cd.png)

The icon next to "x pages modified" could be more relevant. Right now, the "app" icon is seen next to it. 
Also, the text "x pages modified" has a hand cursor over it which depicts that it’s a clickable element when in actuality it isn’t 

Instead of an arrow next to "Latest Deployed Preview", a go-to-page icon would be more apt.
![image](https://user-images.githubusercontent.com/109572422/190559385-7c31db26-866d-4013-94b8-2e5a7365c49f.png)
![image](https://user-images.githubusercontent.com/109572422/190559405-eec1daa0-c31e-4451-8461-d0d7406f52e3.png)

### Steps To Reproduce

1. Go to any application
2. Connect it to a Git repository 

### Version

Cloud

**Comment by infinitetrooper** [comment]
We moved to Git V2 in Q3 2023
