### ISSUE TITLE
[Bug]: The Data display inside the JSON is not in Correct format

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The display of Data inside the JSON is messed up 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/190570486-19eee6e0-d554-4eed-93ae-ba0178889ba7.png">

### Steps To Reproduce

1. Login as demo user
2. Click on members& setting tab
3. Click on Audit logs
4. Open any one of the event 
5. Verify the display of JSON format display

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
What is the preferable format for JSON? Above is in alphabetical order.

@vuiets

**Comment by vuiets** [comment]
Hey, it's on the Events List doc on the PRD. We could follow the same order.

**Comment by IAmAnubhavSaini** [comment]
This is done.
