### ISSUE TITLE
[Bug]: Updates Modal | Partial lines are displayed for some release notes

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For some of the release notes where the `Read More` is not clicked, we see partial lines being displayed.

<img width="1440" alt="Screenshot 2022-09-16 at 3 40 08 PM" src="https://user-images.githubusercontent.com/39921438/190616151-bda50981-2b64-4e26-9c81-a7128e0f68d4.png">

### Steps To Reproduce

1. Go to the homepage.
2. Click on the `What's New` button.

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This looks fixed
