### ISSUE TITLE
RBAC documentation

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#16820]

**Comment by jnikhila** [comment]
Based on the video recording for the feature walkthrough - @jnikhila and @Pranay105 are working on the initial outline.

**Comment by vuiets** [comment]
Recording a few key focus areas for the docs
* Listing instance users
* Creating custom groups and inviting users
* Creating custom roles and associating it with users or groups
* Permissions listing with description of what each permission lets you do

**Comment by Pranay105** [comment]
Any update on the first drafts? @trishaanand @ankitakinger

**Comment by jnikhila** [comment]
[Docs](https://docs.appsmith.com/advanced-concepts/access-control/granular-access-control) published.
