### ISSUE TITLE
[Bug]: Select widgets with bindings added before v1.8 have addtional {{ }} in default values

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i open a select or multi select widget and it had bindings for default values `{{ }}` then we are observing additional `{{ }}` for them.

### Steps To Reproduce

1. Open any older app which has a select or multi select widget with a binding
2. Observe how it shows the default value now
![image](https://user-images.githubusercontent.com/19730984/190627583-0803a34d-6f0a-41c8-aca2-a657b4a0a67c.png)

### Version

Production

**Comment by sbalaji1192** [comment]
@yatinappsmith FYI. Could you assign someone from QA ?

**Comment by yatinappsmith** [comment]
@laveena-en can you verify this?

**Comment by laveena-en** [comment]
yes, picking this up
