### ISSUE TITLE
[Bug]: Min range in Range slider not throwing error for entering characters

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

D&D a Range slider
Enter any Alphabets in Min range property
Observe No error is displayed

![image](https://user-images.githubusercontent.com/104895602/190662684-26d92375-13bb-442f-8acf-2e85cf45a328.png)

**Comment by yaldram** [comment]
@Sripriya93 Please check the latest deployment here - https://appsmith-ed15kznnt-get-appsmith.vercel.app/
