### ISSUE TITLE
[Bug]: Number slider - click precision not accurate

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

D&D a Number slider 
Click on 25% or 75%, observe user is able to choose 24 and 76. But in case of 50 its precise

A bigger pointer might help! or a hover tooltip would help

https://user-images.githubusercontent.com/104895602/190665740-a4f2f30d-a5d6-4598-91b2-1e8e460b842f.mp4

**Comment by yaldram** [comment]
This is not an issue, when I click on 25 and 50 I am able to select the exact values most of the time. It also depends on the width of the slider the greater the width, the greater the precision but again it is a slider we can slide easily. Also we cannot predict what value a user wants to choose, say if he wants to choose 24 and not 25. I think we can close this issue.
