### ISSUE TITLE
[Bug]: Selecting a table widget from snipping mode causes a theme related error for a button widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Selecting a table widget from snipping mode causes a theme related error for a button widget and this error clears out on page refresh

https://www.loom.com/share/2b591e5445f248f4aaec507d9a055264

### Steps To Reproduce

1. Run a query such that you see a table widget show up on snipping mode
2. Select the widget so it appears on the canvas
3. Observe that the widget defaults with an issue for theming but on page refresh this error clears out

![image](https://user-images.githubusercontent.com/79509062/190961631-f074aeed-507f-42c4-9f94-6e7e288d6ad8.png)

### Version

Cloud

**Comment by dilippitchika** [comment]
@ramsaptami closing this in favor of #14527
