### ISSUE TITLE
[Bug]: Evaluated value on Google sheets query page reverts to undefined after page refresh

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Evaluated value on Google sheets query page reverts to undefined after page refresh

### Steps To Reproduce

1. Create a Google sheets query and enter values on JS mode fields and observe the evaluated value have been populated as expected
2. Refresh the page and revisit these field and observe that evaluated value is now undefined

https://www.loom.com/share/94d7d803053a4c0e8efb4922cdbe33cf

### Version

Cloud

**Comment by rohan-arthur** [comment]
@sneha122 to confirm, this happens only when there is no dynamic binding in the field? If correct, we should close this issue as it will become moot after the [proposed evaluated value window changes](https://www.notion.so/appsmith/Improve-the-evaluated-value-window-experience-fbbdead747a5468b8015c2fbbb5843bc)

**Comment by sneha122** [comment]
> @sneha122 to confirm, this happens only when there is no dynamic binding in the field? If correct, we should close this issue as it will become moot after the [proposed evaluated value window changes](https://www.notion.so/appsmith/Improve-the-evaluated-value-window-experience-fbbdead747a5468b8015c2fbbb5843bc)

Yes @rohan-arthur This happens only when there is no dynamic binding in the field. If dynamic binding is there, issue does not replicate. @ramsaptami Please confirm once

**Comment by ramsaptami** [comment]
Closing this since it looks like the changes being planned on your pod will render this invalid.
CC: @sneha122 @rohan-arthur
