### ISSUE TITLE
[Bug]: Column filtering does not work when there are multiple row headings on a GSheet query

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Column filters can only be applied to the first row on a Google Sheet query and even though columns show up on column filter dropdown, we cannot use them since running such a query returns an error as seen in the video attached

### Steps To Reproduce

1. Use a Google Sheet containing multiple header rows as seen in the video attached
2. Use dropdown option to filter data and observe that only when header index is `Row 1` would the query be successfully executed but the query does not execute when row is anything other than `Row 1` (see video)

https://www.loom.com/share/fa33edf500ad49ab858a8d3cbf1a1c29

### Version

Cloud

**Comment by prapullac** [comment]
@nidhi-nair : Completed testing on the local and looks good to me
