### ISSUE TITLE
[Bug]: Selected GSheets columns are cleared when toggled from non-JS to JS mode on query editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When switching field state from non-JS to JS mode on GSheets query, the selected columns are cleared. This needs to be retained as is the behaviour across the rest of the application

### Steps To Reproduce

1. Select a few columns on the column field of a Google Sheet query from the dropdown present in non-JS mode
2. Click on JS toggle and observe that selected columns are cleared - this behavior deviates from behaviour seen across the application

https://www.loom.com/share/f440989a63044f6bb46ed348c8809c7d

### Version

Cloud

**Comment by sneha122** [comment]
As discussed here https://theappsmith.slack.com/archives/C040LHZN03V/p1663660862697159 This is an intended functionality to keep the first json object and not update it in subsequent toggles. As a result, closing this ticket.

**Comment by ramsaptami** [comment]
This is not the intended behaviour and needs a fix
