### ISSUE TITLE
[Bug]: Cursor position shifts to the end of the line when trying to use special characters naming any entity on the platform

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using special characters to name a query/object/widgets, there's a charecter replacement that takes place where, for example, `)` or `&` or `-` is replaced with an underscore `_` but it also causes the cursor to shift to the end of the line which is not the expected behaviour.

### Steps To Reproduce

1. Try to name any widget/query/object with a special character and observe that these characters are replaced by an `underscore` instead since there's a naming restriction - but also, the cursor shifts to the end of the line which is not an expected behaviour

https://www.loom.com/share/31ffa0816d54482a9428d8b45be0222a

### Version

Cloud

**Comment by kocharrahul7** [comment]
Can no longer reproduce, so closing this issue
