### ISSUE TITLE
[Bug]: Option(s) highlighted in dropdown even when selection is cleared 

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#16867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upon selecting any option in the TreeSelect, MultiSelect or MultiTreeSelect widgets using keyboard navigation and then clearing them from the widget, the last selected option remains highlighted in the widget dropdown.

https://www.loom.com/share/6e674967817c4ec68bbca9e675181d10

### Steps To Reproduce

1. D&D TreeSelect, MultiSelect or MultiTreeSelect widgets.
2. Select any option using keyboard arrows.
3. Now clear the value.
4. Again click on the dropdown.

**Expected:** No option should be highlighted as all the selected options are cleared.

### Version

Cloud

**Comment by dilippitchika** [comment]
@shadabbuchh it's the keyboard focus state which you are seeing here. The highlighted/selected state in these widgets looks like this now
<img width="291" alt="Screenshot 2022-09-19 at 6 38 36 PM" src="https://user-images.githubusercontent.com/19730984/191024606-191f5c43-1121-452b-8bc8-e46e8b04196b.png">


We can persist keyboard focus state, it should be fine. Please reopen the issue if you think otherwise and let me know

**Comment by shadabbuchh** [comment]
@dilippitchika the issue I am talking about occurs when we clear all the selections made. I see in your screenshot that you haven't cleared out the selection. Please refer to the video attached in the Description.

**Comment by dilippitchika** [comment]
@shadabbuchh even after you clear, i can see that nothing is shown selected based on your video because it doesn't have accent color as the highlight, it uses a gray color instead. I don't think anything is getting selected.

**Comment by shadabbuchh** [comment]
@dilippitchika yes that's correct. My point is... after all the selections are cleared why do we shoe the Grey colour highlight?

**Comment by dilippitchika** [comment]
That's just the keyboard focus indicator that if you click up arrow or down arrow the starting point will be from there. It's not an indication that something is selected, it's closer to hover state.
