### ISSUE TITLE
[Bug]: Issues with renaming a "JS Object"

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#16869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are a couple of issues that I observed -

1. When I rename a JS Object from the explorer pane, the object does not get renamed.

3. When I rename a JS object by directly editing its name in the title, the object gets renamed, but the name in the explorer pane is still the old name until I refresh the page.

### Steps To Reproduce

**Scenario 1**

https://user-images.githubusercontent.com/15727421/190990861-5f304428-172f-434a-8f02-63443f6c104c.mov

**Scenario 2**

https://user-images.githubusercontent.com/15727421/190991230-862d162b-70ec-4920-9f26-60c8cf835b6d.mov

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@sribalajig This seems to be working. I think your JSObject is currently not being saved and that is why this failed in scenario 1. You can see the orange dot in the topbar.
