### ISSUE TITLE
[Bug]-[516]:GSheets query does not honor selected column filter when there's a comma present after last row on JS code

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

GSheets query does not honor the selected column filter when there's a comma present after last row and executes all columns instead. If the comma should not be there then there should be a better way to handle the error rather than the current behaiour of not honoring the selected

### Steps To Reproduce

1. Select basic details of a GSheet query and select a few columns
2. Run the query and confirm the column filter works
3. Turn on JS mode on the columns field and add a comma after the last coumn entry
4. Run the query and observe the column filter does not get honoured as expected
5. Toggle back to the non-JS mode of the field and observe, selected columns remain as expected without the extra comma

https://www.loom.com/share/65f5c52f8c8b4007be722c1d0ba9efc0

### Version

Cloud

**Comment by sumitsum** [comment]
GSheet 6m usage: 2585
% of users impacted: 10
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 258 |
| Effort (months)  | 0.25 |

**Comment by rohan-arthur** [comment]
not possible anymore to toggle back from js mode without clearing the field, so this issue is not valid anymore.
