### ISSUE TITLE
[Bug]: Selected values on a GSheet query is stuck and unable to unselect from the UI and need to go to JS mode of the field to make any changes

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Selected values on a GSheet query is stuck and unable to unselect from the UI and need to go to JS mode of the field to make any changes

### Steps To Reproduce

1. Go to the query at [this](https://release.app.appsmith.com/app/megamind/theaming-and-js-objects-628bbf17460c5744a0940553/edit/saas/google-sheets-plugin/api/62bc0015a2e5674d8ce52979) location and toggle between the JS and non-JS mode and notice the inability to select columns from the dropdown UI

https://www.loom.com/share/1d325777afad40fba890f5df26893b58

### Version

Cloud

**Comment by nidhi-nair** [comment]
@ramsaptami This is likely because of #16868 itself. Coulf you please test this again once that change starts to appear on release? I don't think we'll see this anymore. Closing this issue and assigning QA label for that reason.

**Comment by ramsaptami** [comment]
Yep, this has been fixed it seems. Thanks @nidhi-nair!  :)
