### ISSUE TITLE
[Bug]: Checkbox group widget - Red color for required remains even on disabling widget, and changes to grey on hover

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Required is enabled and if all boxes are de-selected, and user disables the checkbox group widget, the red borders on the checkboxes remain and on hovering over the checkboxes, the colors change to grey from red. 

Expected behavior - The colors of the borders should also get greyed out as the widget is disabled. 

### Steps To Reproduce

1. Drag and drop a checkbox group widget
2. Set Required field to ON
3. Bind the Disabled toggle to - {{Checkbox2.isChecked}} and set Checkbox2 default state to off. 
4. Now uncheck all the checkboxes. We see the red borders on all the checkboxes.
5. Disable the widget. The red borders remain and change to grey on hover, even though the widget is disabled.
<img width="585" alt="Chkbox_RequiredBug_Tobelogged" src="https://user-images.githubusercontent.com/101863839/191049556-9af28022-5371-4a7a-9c60-76d478c02c0f.png">

### Version

Release

**Comment by dilippitchika** [comment]
@jsartisan looks like we missed it from reskinning, can you pick this up in the current sprint?

**Comment by laveena-en** [comment]
Tested and verified.
