### ISSUE TITLE
[Task] Canvas not being edge to edge makes the working area unclear

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1687]
## Description

A user found it disconcerting that the canvas did not stretch to the edge of the screen and could only see the edge of the canvas on dragging

**Comment by areyabhishek** [comment]
I guess the solution here is to have a very clear boundary for the canvas. The canvas is edge to edge on my 13inch screen but it still doesn't look so good. Boundaries will also help tell the user when the app isn't centered.

**Comment by riodeuno** [comment]
We have re-designed the canvas to have a border.
