### ISSUE TITLE
[Bug]: Clearing filter on the query editor causes suggested widget panel to collapse

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clearing filter on the query editor causes suggested widget panel to collapse

### Steps To Reproduce

1. Run any query on the query editor
2. Switch between tabs on the **debugger** and observe the suggested widget panel (snipping mode feature) stays in place
3. Clear filter on the logs tab and observe suggested widget panel collapses as seen in the video
4. Switch between **debugger** tabs again and the panel comes back

https://www.loom.com/share/4056e41d785f47a68009a837df4713de

### Version

Cloud

**Comment by bharath31** [comment]
not able to reproduce this anymore
