### ISSUE TITLE
[Feature]: Segregate UI Application repository (Admin Builder and UI Render) from Server (Database connectors & APIs) and their relevant docker images

### ISSUE THREAD

**Issue by ganeshkbhat** [appsmithorg/appsmith#16897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Segregate 
[**A] UI Application repository (Admin Builder and UI Render) from 
[**B] Server (Database connectors & APIs) from 
[**C] CLI .sh bash scripts; and 
[**D] their relevant docker images + compose files.

I could see different .sh bash scripts and compose files for the same but did not find [**E] relevant docs or cues to pull the builder and the UI Renders.

I did not find relevant documentation for the same. If there is a relevant doc, please let me know what steps to get Admin Builder and UI Render repo+configs+docker and a seperate deploy for [**F] API docs for the Backend Database connectors & APIs. Little messed up with the repo structure.  Which portions have tight coupling?

A [**G] swagger API for backend would have been cleaner. 

Let [**H] deploy in [local server](https://github.com/appsmithorg/appsmith/tree/release/deploy) without docker support. I wish to know what .sh bash scripts to run and supported OS distros.

--

I have seen this: 
     - Connect to your data with our connectors: databases (PostgresQL, MongoDB, Amazon S3, and many more), SaaS providers (like Google Sheets, Airtable, Twilio) or any GraphQL/REST API. [Docs](https://docs.appsmith.com/core-concepts/connecting-to-data-sources?utm_source=github&utm_medium=organic&utm_campaign=readme)
      - API client and query builder lets you run RESTful API, GraphQL, or database queries within connected datasources.
      - App theming to style your app pages and widgets and to customize the visual layout of your app in one click.

--

`Local Deploy` :
```
[ (Pluggable & Local Deploy) Admin Builder UI + Better Docs ]
>>> 
[ (Pluggable & Local Deploy) Server API - Admin Builder API +Plugins/Component API +UI API +Connectors +Better Docs ] 
>>> 
[ (Pluggable & Local Deploy) UI Render ]
```

### Why should this be worked on?

* Admin Builder +Plugin/Component section +UI segregated from Backend (API & DB connectors) - [**A], [**B], [**C], [**D]
* Pluggable Custom Backend Server based on specific needs
* Local deploy without docker support - [**H]
* Segregated docker support - [**B]
* Swagger support for APIs - [**G]
* Better documentation for Repos and API -  [**E], [**F], [**G]

**Comment by Nikhil-Nandagopal** [comment]
@ganeshkbhat this is our code contribution guide
https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md
Is there a particular issue you need help with? We believe in having a single mono repo as the best way to maintain this project so I'm closing this issue
