### ISSUE TITLE
[Bug]: JSeditor : Prettify for given code is not working properly 

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#16903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For below code snippet prettify code does not work properly

Recording - https://www.loom.com/share/19017c4971a649c988c4e5fb951958f4

simplify :()=> {
		return Api2.run()
			.then(async ()=>{
			await showAlert('test1'),
				await console.log('test2'),
				await console.log('test3')})
	},
}

[Environment - https://app.appsmith.com/app
Browser - Chrome ]

### Steps To Reproduce

1. Navigate to JSeditor
2. Write below code snippet 
3. Use Prettify code option for the code

simplify :()=> {
		return Api2.run()
			.then(async ()=>{
			        await showAlert('test1'),
				await console.log('test2'),
				await console.log('test3')})
	},
}

**Expected**:

simplify: () => {
    return Api2.run()
        .then(async () => {
            await showAlert('test1'),
                await console.log('test2'),
                await console.log('test3')
        })
},
} 

### Public Sample App

https://app.appsmith.com/app

### Version

cloud

**Comment by rohan-arthur** [comment]
works ok now
![Screenshot 2024-08-21 at 14 31 16](https://github.com/user-attachments/assets/2bcb7911-5660-441e-8e59-736dc2c339d9)
