### ISSUE TITLE
[Bug]: Code scanner widget does not reset its internal property

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On resetting the code scanner widget, its internal property value is not reset

### Steps To Reproduce

1. Drop a code scanner widget on the canvas
2. Use a text widget to bind its internal property `CodeScanner1.value`
3. Scan a QA code and observe text widget display the stored value of the code scanner
4. Use a button widget to reset the code scanner and observe that the action is executed but the internal properties are not reset

https://www.loom.com/share/ecd83ef1189b4f05b7c0f6707c4a92ec

### Version

Cloud

**Comment by dilippitchika** [comment]
@dhruvikn @chandannkumar how did this case get missed?

**Comment by chandannkumar** [comment]
@dilippitchika This is a clear miss from my end. 
Since code scanner auto close and updates values on every new scan and i didn't thought of resetting value a use case.

**Comment by dilippitchika** [comment]
@dhruvikn please pick this up in the next sprint
