### ISSUE TITLE
[Bug]: App crashes when the user navigates to the Audit logs page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App crashes when the user navigates to the Audit logs page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191256117-78d9814b-b076-4be7-bf3b-58bba9cedd5c.png">

### Steps To Reproduce

1. Login as demo user 
2. Click on Member&setting tab
3. click on audit logs tab
4. The app crashes

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
@RakshaKShetty Please open if this is still reproducible.

---

Please provide relevant API data.
