### ISSUE TITLE
[Bug]: Query call does not happen on widget action field trigger 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a query is set to run on widget trigger, the query does not run as expected and subsequent widgets updates fail.

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/automation-test-cases/page-3-debug-632976fb9b58ed74ea6422d4/edit) location
2. Select different options from the dropdown `selectAstronaut` - observe widgets on the page don't update with appropriate information.
3. Navigate to the query and observe, the query has been not been run

https://www.loom.com/share/243565da63834ef7a82e7f59e334cf77

### Public Sample App

https://release.app.appsmith.com/app/automation-test-cases/page-3-debug-632976fb9b58ed74ea6422d4/edit

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
After debugging, API is getting triggered after the dropdown option change and the JS function on the success of the API is also getting triggered. but the API 'filteredAstronout' which is used to showcase the data is not returning proper values hence it appears to be the wrong data. @ramsaptami please let's check this behavior with API which will give the right data.
I am removing the 'critical' tag.

**Comment by bharath31** [comment]
@ApekshaBhosale @ramsaptami could we close this issue if incorrect API response is preventing widget updates?
