### ISSUE TITLE
[Bug]-[1150]: navigateTo() cannot pass & in url queryparams between two pages

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to pass the value `A&B Ltd` from Page1 to Page2, so that I can display the value on Page2. 
Please see [this](https://app.appsmith.com/app/between-pages/page1-6329ee267f7b8d288db3707d/edit) app (shared with support email)

### Steps To Reproduce

video demo of the issue

https://user-images.githubusercontent.com/94514895/191317011-85ec2eba-3ae5-4017-8773-43eed7a0202a.mov

### Version

Cloud

**Comment by bharath31** [comment]
This also becomes a problem while passing objects with certain string values on the `navigateTo()` params. Example of an object that gets malformed: 

```
export default {
	myFun1: () => {
		const utm1= {string: "L&T", url:"https://www.domain.com/?utm_source=newsletter&utm_medium=email", number: 1234, object:{utm_source: "newsletter", utm_medium: "email$%#@"}};
		// Gets malformed when passed as param on navigateTo()

		navigateTo("Page2", utm1, "SAME_WINDOW")
		// Query Params: {"string": "L","T": "","url": "https://www.domain.com/?utm_source=newsletter","utm_medium": "email","number": "1234","object": "[object Object]"} ❌ 

		const utm2= {string: encodeURIComponent("L&T"), url:encodeURIComponent("https://www.domain.com/?utm_source=newsletter&utm_medium=email"), number: 1234, object:{utm_source: "newsletter", utm_medium: "email$%#@"}};
		// Works as expected when passed as param on navigateTo()

		navigateTo("Page2", utm2, "SAME_WINDOW")
		// Query Params: {"string": "L&T","url": "https://www.domain.com/?utm_source=newsletter&utm_medium=email","number": "1234","object": "[object Object]"} ✅
	}
}
```

Ideally, we should be URI Encoding all string values passed on the `navigateTo()` params object. 

@satbir121 thoughts?

**Comment by satbir121** [comment]
@rohan-arthur Query Param expects an object like `{ "foo": "Bar"}` instead of a string. Looks like its not evident enough from the UI. We need to work on discoverability. 

Given that, `{"name": "B&C Ltd" }` will also not work because there is a reserve character `&` inside. 

As a solution, system can loop through all the keys in query params object and encode/decode the values automatically.

**Comment by satbir121** [comment]
@bharath31 @rohan-arthur Any ideas on discoverability of query params as object?

**Comment by rohan-arthur** [comment]
@satbir121 discussing this here: https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1663735917910319?thread_ts=1663735917.910319&cid=C02K0SZQ7V3

**Comment by bharath31** [comment]
Assuming 5% of users who update widget property with `navigateTo()` use special characters on the method params.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     |  115 |
| Effort (months)  |  |

**Comment by bharath31** [comment]
Non-string values on params don't work as well. Related issue: #12177
