### ISSUE TITLE
[Bug]: Special characters on page names are converted to space

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#16929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to name a page with a special character like `Page1&2`, the character `&` gets converted to a space and the page name gets saved as `Page1 2`

### Steps To Reproduce

1. Go to Entity Explorer
2. Create a new page and try to name it `Page1&2`
3. View the page named as `Page1 2`

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is by design because special characters are invalid in variable names
