### ISSUE TITLE
[Feature]: Show the number of tabs on the header for list of tabs in property pane 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#16937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When working with tabs widget and there are a lot of tabs, i want to see the number of tabs so that i know there are more tabs which can be scrolled to access

### Why should this be worked on?

Helps users not get confused with regards to the data in tabs

**Comment by dilippitchika** [comment]
## Solution
Add the number of tabs present besides the tabs label

![image](https://user-images.githubusercontent.com/19730984/191434783-57e0b459-af15-4ce8-a0bc-ad9a0a68ff33.png)

**Comment by rksingh2001** [comment]
@dilippitchika I would like to work on this issue, please assign it to me?

**Comment by dilippitchika** [comment]
Greetings @rksingh2001 , thanks for showing interest 🎉 , This is all your. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by Subhamjain02** [comment]
I would also like to work on this, Please assign it to me.

**Comment by dilippitchika** [comment]
Hey @Subhamjain02 @AbhishekTiwari23 thanks for showing your interest. Since @rksingh2001 hasn't gotten back to us yet, i would like to wait for one more day and assign it to one of you.

**Comment by AbhishekTiwari23** [comment]
> Hey @Subhamjain02 @AbhishekTiwari23 thanks for showing your interest. Since @rksingh2001 hasn't gotten back to us yet, i would like to wait for one more day and assign it to one of you.

Ok, I am waiting

**Comment by tauantcamargo** [comment]
if  no one take it.. can i grab this issue? @dilippitchika

**Comment by AbhishekTiwari23** [comment]
> if no one takes it.. can I grab this issue? @dilippitchika

Actually, someone is already working on this issue

**Comment by tauantcamargo** [comment]
ooo sorry dude, i didn't see u was assigned

**Comment by dilippitchika** [comment]
Hi @AbhishekTiwari23 @tauantcamargo @Subhamjain02, Assigning this to you all 3 of you now. Since we haven't heard back from @rksingh2001. If one of you can submit a PR we should be able to close this quickly. Please check out other good first issues if you are unable to contribute to this.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by AnuragThePathak** [comment]
Is there anyone still working on it?

**Comment by dilippitchika** [comment]
Hello @AnuragThePathak i have assigned a few folks who were willing to work on it. Do you also want to work on this issue?

**Comment by AnuragThePathak** [comment]
If they are already working then it's fine.

**Comment by dilippitchika** [comment]
Ok, please let me know if you find any other issues you want to work on

**Comment by AnuragThePathak** [comment]
Sure I'll

**Comment by AkkiBond** [comment]
Hey, Can I work on it?
