### ISSUE TITLE
[Bug]: Snowflake DB - data in Date / Time Format on querying, is displayed in a different number format

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run a select query on Snowflake DB to pull in data the Date and Time columns show data in incorrect format.

### Steps To Reproduce

1. Connect to the following Snowflake DB. 
Account name - gv14678.central-india.azure 
Warehouse - COMPUTE_WH 
Database - NEWDBAPARNA 
Default Schema - PUBLIC
 Role - ACCOUNT ADMIN 
User name - Aparna 
Password - Snowflake123
2. Run a query - SELECT * FROM CALL_CENTER_APARNA;
3. Note the columns - CC_START_DATE, CC_END_DATE, CC_CREATIONTIME

The data in these columns should be in the form of Date and Time formats, but they are not.

<img width="1342" alt="QueryruninSnowflake" src="https://user-images.githubusercontent.com/101863839/191474578-b7c4f5c5-ea54-4f16-911b-581f151ec6cf.png">
<img width="843" alt="SnowflakeDBData" src="https://user-images.githubusercontent.com/101863839/191474603-bd270d7b-6db5-4c3e-93ba-4c46bb3dfa9a.png">
<img width="1161" alt="AppsmithQueryPullinginSnowflakeData" src="https://user-images.githubusercontent.com/101863839/191474611-03ecaeba-0ca8-46b2-b337-52ccdbdce17a.png">

### Version

Release

**Comment by rohan-arthur** [comment]
hi @btsgh the date here is represented as a javascript timestamp, and can be converted easily to other formats:
![Screenshot 2022-09-22 at 13.52.35.png](https://images.zenhubusercontent.com/6196337f2def7ccca841bb55/0ad8c61e-93b0-45fc-8349-859bf01a87c3)
