### ISSUE TITLE
[Feature]: Micro-frontends integration with Webpack 5 Module Federation

### ISSUE THREAD

**Issue by yescine** [appsmithorg/appsmith#16953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As some apps migrated to Micro-front ends architecture is there a way to export at runtime the whole smith-app as **Remote** component with webpack-module-federation-plugin so that we can integrate it in our existing **Host** react/vue/angular application.

For the sake of simplicity: No shared state or props between the host/remote.

### Why should this be worked on?

we can add feature and module (CRM table, reports, tasks manager) to our exiting app in short amount of time, tested out with our clients and if we need to scale or complicated business logic we can refactor to pure Js framework React/Vue/Angular.

**Comment by Nikhil-Nandagopal** [comment]
@yescine have you tried embedding appsmith via an iFrame? You should be able to even handle communication with the parent app.

**Comment by yescine** [comment]
@Nikhil-Nandagopal I never tried that I use only Iframe for video! 
I found it on the doc https://docs.appsmith.com/advanced-concepts/embed-appsmith-into-existing-application
But what if we want to share the auth state for app that need authenticated user ?

**Comment by Nikhil-Nandagopal** [comment]
@yescine you can share it with the iFrame query parameters or wait for the new postMessage implementation that will make this possible
