### ISSUE TITLE
[Bug]: Gsheets where clause: take form configuration into JS mode

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://user-images.githubusercontent.com/94514895/191651771-de046182-8c23-44e5-8651-253e783cd971.mov

in ghseets query, when I add some where clause in the form mode. I switch to the JS mode, and it would be good to see the form mode configurations in the JS mode. 

### Why should this be worked on?

1. makes it easier for the user to make their entries
2. serves as an instructional guide to the user to make edits more confidently

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur @ayushpahwa this is a bug. It should obviously not reset the value here

**Comment by sneha122** [comment]
As discussed here https://theappsmith.slack.com/archives/C040LHZN03V/p1663660862697159 This is an intended functionality to keep the first json object and not update it in subsequent toggles. Please refer #16895 for more details.

**Comment by Nikhil-Nandagopal** [comment]
@sneha122 just to chime in and be a bit more specific while it was intentional, it was a mistake that we deviated from the original design pattern in the property pane and we should fix this.

**Comment by sneha122** [comment]
Yes that's correct, we have a feature ticket created for this #16895
