### ISSUE TITLE
[Bug]: query view port gets truncated and not scrollable

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. when there is a large dynamodb query that exceeds the viewport, the view is truncated.
2. it is not possible to scroll while making a text selection

### Steps To Reproduce

https://user-images.githubusercontent.com/94514895/191662238-95095736-9e58-4698-bc17-889d4f3fbfaf.mov

### Version

Cloud

**Comment by sriharigr** [comment]
Is this issue fixed? If not can I take it up?

**Comment by Nikhil-Nandagopal** [comment]
@sriharigr this seems to now be fixed. You can have a look at some of our other low/medium issues to fix!
