### ISSUE TITLE
[Feature]: I need a function that can focus on the input

### ISSUE THREAD

**Issue by developer-honoru** [appsmithorg/appsmith#16965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to be able to focus on the input whether it is javascript or an action.

### Why should this be worked on?

I want to go directly to the input window when I press the button, but I can't.

**Comment by bharath31** [comment]
duplicate of #4874

**Comment by developer-honoru** [comment]
@bharath31 I wonder why they decided not to plan this
https://github.com/appsmithorg/appsmith/pull/17339#event-7706124739
I was waiting for @rimildeyjsr to come up with a new method.
If there is no developer to do this, can I make one?
i need this function
