### ISSUE TITLE
[Bug]: Inserting date and time values into snowflake db by binding to date widgets, the date and times entered in the db differ

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#16963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I bind the insert query values of Date and Time to Datepicker widget, and run the query, the date and time entered into the database varies from what is picked in the widget.

### Steps To Reproduce

1. Connect to the following Snowflake DB.
Account name - gv14678.central-india.azure 
Warehouse - COMPUTE_WH 
Database - NEWDBAPARNA 
Default Schema - PUBLIC
 Role - ACCOUNT ADMIN 
User name - Aparna 
Password - Snowflake123
2. Write an insert query like this for e.g- 
INSERT INTO CALL_CENTER_APARNA
  (CC_START_DATE, CC_SKNO, CC_MANAGER, CC_ID, CC_END_DATE, CC_CREATIONTIME, CC_COMPNAME, CC_COMPANYID, CC_CLOSE_DATE_SKNO,CC_CLASS,CC_CITY)
VALUES
  ('{{DatePicker1.selectedDate}}', 5, 'Darshan', '0000005', '{{DatePicker2.selectedDate}}', '{{DatePicker3.selectedDate}}', 'Milkshakes For You!',2,5,'First','Bengaluru');
3. DatePicker1 /2/3 have specific time and date selected. (Check the attached images). Run the above query and note that in the snowflake database, the values entered differ
<img width="668" alt="DateandTimein_AppsmithWidgets" src="https://user-images.githubusercontent.com/101863839/191552039-a7ff04ee-208c-429e-8e52-a798952463e1.png">

<img width="1151" alt="DateandTime_SnowflakeDB" src="https://user-images.githubusercontent.com/101863839/191552018-3e1e85be-6f5c-4417-80d4-075788a6a797.png">

If we directly enter the values in the query(without binding), the values match.

### Version

Release

**Comment by rohan-arthur** [comment]
@btsgh would you please attach the property configurations of the three date-pickers?

**Comment by btsgh** [comment]
@rohan-arthur - Does this help? 
<img width="281" alt="DatePicker3" src="https://user-images.githubusercontent.com/101863839/191908637-e80d036c-f101-4203-961b-f822153d9d1e.png">
<img width="289" alt="DatePicker2" src="https://user-images.githubusercontent.com/101863839/191908640-02b58240-3e18-4f1f-99e8-4fc7cc4e1b8a.png">
<img width="280" alt="DatePicker1" src="https://user-images.githubusercontent.com/101863839/191908643-1f1a184e-4d74-4dbf-a5e1-cea48d771f4d.png">

**Comment by btsgh** [comment]
Similar issue seen even on MySQL DB

**Comment by Nikhil-Nandagopal** [comment]
This is because the type of CC_END_DATE doesn't match the type inserted and CC_CREATIONTIME is storing the value in UTC so it's 5:30 hrs behind
