### ISSUE TITLE
[Bug] Consolidate request body sizes

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1696]
## Description
The filepicker widget allows the user to add an arbitrary number of MBs to the file size limit
The nginx `client_body_max_size` is a fixed value
The server has limits on this as well.

We need to consolidate this experience so that the user does not run into unexpected limitations.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit why must we limit this? Can we have a high arbitrary number like 100mb?

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno @mohanarpit is this still an issue? Can we close this?

**Comment by Nikhil-Nandagopal** [comment]
We're setting a large arbitrary size of 100mb for now

**Comment by srijanshetty** [comment]
@Nikhil-Nandagopal setting the file size to 100mb doesn't help. The connection gets terminated/reset by nginx on doing so.
