### ISSUE TITLE
[Bug]: user name should be displayed instead of text "user " in logged out/login in event descriptor

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

user name should be displayed instead of text "user " in logged out/login in event descriptor
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191729029-4f49c8bb-b1ed-4804-a19b-51efb073541d.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191729075-5c102642-4a83-4f9c-963f-13c98b0c46d2.png">

### Steps To Reproduce

1. Login as demo user
2. Click on member & setting menu
3. Click on audit log menu
4. In event filter select user Logged in and logged out event
5. Now very the display of event name displayed

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is fixed.
