### ISSUE TITLE
[Task]: Git Repo Page UI Inconsistencies

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#16975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

If a user reaches 3 repo limit on Git, then we show them a the modal to either upgrade or delete an existing repo. The UI for this is not the same as the design.
<img width="1680" alt="Screen Shot 2022-09-21 at 8 36 36 AM" src="https://user-images.githubusercontent.com/34486435/191664677-54f7aeb2-f9ca-4d67-9b81-7d3577958a83.png">

This is the expected UI

![image (16)](https://user-images.githubusercontent.com/34486435/191690932-5d9e9571-4dbf-436b-b336-ad6b4a329e7e.png)

**Comment by IAmAnubhavSaini** [comment]
Is there an API that returns for a given app the number of users that the app has been shared with?

Also, if we can figure out the number of users that an app is shared with in backend, BE can just return that number in response for limited git repo api.

**Comment by IAmAnubhavSaini** [comment]
@AnaghHegde ^
