### ISSUE TITLE
[Bug]: In Page view event the data for "Mode" is missing in JSON

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Mode data is missing in Page Viewed event
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191730105-730ee3d1-5d14-4deb-bacb-c63cf7ec8550.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191730187-5e88804f-96b5-4ebe-aa4c-5d5974acf04d.png">

### Steps To Reproduce

1. Login as demo user
2. Click on member & setting menu
3. Click on audit log menu
4. In event filter select page view event
5. Now very the display of "mode" event in the JSON

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is conveyed by the event. `page.viewed` for example.
