### ISSUE TITLE
[Task]: Track additional actions on JSObjects

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#16970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Tracking additional actions on the JSObject page will help us measure overall engagement, take better product decisions and help in debugging issues. 

Link to Specs: https://www.notion.so/appsmith/Tracking-JSObject-usage-746ad8fa321340918ae701f1dd4daa8e#bcdbd40704204cf9ab61cce344dd3f17

**Comment by ravikp7** [comment]
This issue is blocked on https://github.com/appsmithorg/appsmith/issues/18026
