### ISSUE TITLE
[Bug]-[178]:datepicker widget superfluous error when using js timestamp

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#16976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

for a datepicker widget, I assigned the default value from a store key that computes to `1609459200000`. 

--> this is correctly rendered in the canvas 
--> but there is an error that the date is not in the correct format

is this error valid and necessary, if we are anyway handling the logic of converting the timestamp to human readable date? 

### Steps To Reproduce

![Screenshot 2022-09-22 at 13 57 38](https://user-images.githubusercontent.com/94514895/191698049-71ed3a86-1901-441f-8876-c9cd36cc4276.png)

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 178 |
| Effort (months)  | 0.5 |

**Comment by somangshu** [comment]
Default date should be in the ISO format
We do not use epoch for default

cc @riodeuno do you think there in any implication or we can just remove the validation?

**Comment by Nikhil-Nandagopal** [comment]
Doesn't seem to be working for me and the value that is rendered might not actually be correct.
