### ISSUE TITLE
[Bug]: In datasource event the application section is missing in JSON

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The application section is missing in the data source event
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191741639-895de76d-c965-422b-8b75-18e9d819bee8.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191741709-00b313da-79d3-4af6-8cc6-dc391e3e06d6.png">

### Steps To Reproduce

1. Login as demo user
2. Click on member & setting menu
3. Click on audit log menu
4. In event filter select Datasource Creation event
5. Now very the display of data in jason the application section is missing

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by vishnu-gp** [comment]
@RakshaKShetty Datasources are created at workspace level and we don't have the data of from which application the datasource was created/updated/deleted in current analytics and thus moving this to the product backlog to take up in the next iteration.

**Comment by vishnu-gp** [comment]
@vuiets Datasource is not directly connected to any applications today. This means we are referring to the application from which the datasource was created/updated/deleted. Is this data really important? If yes FE will have to send the applicationId to BE every time a datasource is created/updated/deleted.
cc: @IAmAnubhavSaini

**Comment by vuiets** [comment]
Sorry I missed this earlier. Here I was thinking the context in which the action was performed is important. That being said, haven't been consistent with showing the context in which the action was performed everywhere. Let's not add the application information for the datasource events.

@vishnu-gp could you please make the change on the JSON format in the PRD as well?

**Comment by vishnu-gp** [comment]
Removed application data from the JSON Structure in PRD for datasource events.
cc: @RakshaKShetty @vuiets
