### ISSUE TITLE
[Bug]: The event dropdown is displayed with event name that are not being tracked currently

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The event dropdown is displayed with event name that are not being tracked currently
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191743804-801a509e-bc7f-4b45-9326-1177a44dc985.png">

### Steps To Reproduce

1. Login as demo user
2. Click on member & setting menu
3. Click on audit log menu
4. Click on event dropdown
5. verify the display of event names
6. The event that are not tracked currently all those names are displayed

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by vishnu-gp** [comment]
@RakshaKShetty This is done. Please test in EC2
