### ISSUE TITLE
[Bug]: The Instance setting update event is not  displayed when user filter the event from event filter

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The instance setting event filter doesnt work
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191731787-a922cc8a-bd24-4697-bd19-c50293811667.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191731823-cd9035b3-60a4-422b-8def-523f78c54627.png">

### Steps To Reproduce

1. Login as demo user
2. Click on member & setting menu
3. Click on audit log menu
4. In event filter select instance setting update event
5. The data is not displayed even when we have a data

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by IAmAnubhavSaini** [comment]
This is fixed. @RakshaKShetty please check on DP.
