### ISSUE TITLE
[Bug]: In Datasource Create event the data for "Datasource type" is missing in JSON 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Datasource type is missing in create datasource event
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191730920-2a75176e-1ad9-4bc6-a89a-6be9adf597a8.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191730983-98304cc8-bf8e-407b-87b0-74e808aa0063.png">

### Steps To Reproduce

1. Login as demo user
2. Click on member & setting menu
3. Click on audit log menu
4. In event filter select Datasource created event
5. Now very the display of data source type data in json

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by vishnu-gp** [comment]
@RakshaKShetty Done and deployed to EC2. Please retest with fresh events
