### ISSUE TITLE
[Bug]: The workspace name is missing in user Invite event

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#16986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The workspace name is missing in user Invite event
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/191744958-582dce19-5512-4760-a0f7-4ca970d0bb50.png">

### Steps To Reproduce

1. Login as demo user
2. Click on member & setting menu
3. Click on audit log menu
4. In event filter select user invite event
5. in user invite event the workspace name is missing

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by vishnu-gp** [comment]
@RakshaKShetty We don't have workspace details in analytics and the whole logic might change post-RBAC. Decided to do the changes after that. cc @vuiets 
Meanwhile, @IAmAnubhavSaini can you remove the workspace mention from the description text until this is ready?

**Comment by IAmAnubhavSaini** [comment]
How is RBAC connected to this? At the time of invite, you'd have workspace details. How else are you going to invite users otherwise?

------

I can remove workspace bit for now, but without that this log/record is not that useful.

**Comment by vishnu-gp** [comment]
> How is RBAC connected to this? At the time of invite, you'd have workspace details. How else are you going to invite users otherwise?
> 
> I can remove workspace bit for now, but without that this log/record is not that useful.

CE BE analytics doesn't include workspace details for this event. At some point, we decided not to put more effort into collecting more data at least for v1. Also, @vuiets mentioned with RBAC invite logic might change so we parked this removed workspace details from the JSON in Notion.

**Comment by vuiets** [comment]
So with RBAC we'll have 2 more flows come in, making it 3 in total
* Invite to workspace
* Invite to instance with roles
* Invite to group in an instance

So the context JSON has to change to reflect the right info so told @vishnu-gp we'll pick this up then. But @vishnu-gp we could do this as a fast follow and add workspace details for this if we have more important things to focus on and don't have the bandwidth right now.

**Comment by vishnu-gp** [comment]
> So with RBAC we'll have 2 more flows come in, making it 3 in total
> 
> * Invite to workspace
> * Invite to instance with roles
> * Invite to group in an instance
> 
> So the context JSON has to change to reflect the right info so told @vishnu-gp we'll pick this up then. But @vishnu-gp we could do this as a fast follow and add workspace details for this if we have more important things to focus on and don't have the bandwidth right now.

@vuiets We don't have that data coming in from analytics. I'd prefer to do it post-release merge at least.

**Comment by vuiets** [comment]
Sounds good @vishnu-gp, we could do it post the release merge.

**Comment by IAmAnubhavSaini** [comment]
This is fixed for now; with no workspace information.

**Comment by RakshaKShetty** [comment]
@vishnu-gp the workspace name is missing when user create a crud page

**Comment by vuiets** [comment]
@vishnu-gp if we are closing this, could you please raise a separate task to track this?

**Comment by RakshaKShetty** [comment]
@vishnu-gp adding the new issue link https://github.com/appsmithorg/appsmith/issues/17271
