### ISSUE TITLE
[Task]: Refactor common data type handling logic w.r.t. the newer structure

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#16994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by subrata71** [comment]
|Plugin Name  | Remarks |
| ------------- | ------------- |
| GoogleSheets| Fetch operations|
| AmazonS3| List files query |
|xxx|xxx|
|xxx|xxx|
|xxx|xxx|
|xxx|xxx|

**Comment by subrata71** [comment]
For the following cases we cannot get rid of this function DataTypeStringUtils.java -> stringToKnownDataTypeConverter entirely.

- After fetching data from Google Sheets the data type of each column is identified using this function. We don't have the respective client-side data type for such case which helps identify the data type in the newer implementation.
- In Postgres the data type of first element of array is required for the later processing but in execute API payload the client-side doesn't send the individual type of the array elements
- For parsing commands of MongoPlugin e.g. Aggregate, Insert
- TBD

**Comment by subrata71** [comment]
### Need for passing the data types of each array elements
In case of Postgres when the binding parameter is of type array we need to know the type of array elements as well. To be precise we need to know the type of the first array element. Till now the individual types of array elements are not passed from the client side. If we decide that we won't incorporate this change now then we have to consume the stringToKnownDataTypeConverter method in order to assume the type of the array elements as a fallback plan.

**Comment by nidhi-nair** [comment]
@subrata71 Do we have cases where we expect the array elements to be a heterogenous set of data types?

Agreed on the following usage. We can remove this after we implement user set data types for data sources:
> After fetching data from Google Sheets the data type of each column is identified using this function. We don't have the respective client-side data type for such cases which helps identify the data type in the newer implementation.

Could you please expound on the usage for the following scenario?
> For parsing commands of MongoPlugin e.g. Aggregate, Insert

**Comment by subrata71** [comment]
@nidhi-nair 
> Do we have cases where we expect the array elements to be a heterogeneous set of data types?

With respect to SQL, this is not possible to mix heterogeneous types of data under a single array. In case of REST API, there could be such a use case. 

`/an-imaginary-api?args=[xyz,string,number]`

> Could you please expound on the usage for the following scenario?

As far as I understand this is used to identify whether queries are written using array notation or without array notation. Please refer to the following screenshot which has the usage to that common method.

<img width="1139" alt="Screenshot 2022-10-07 at 12 09 26 PM" src="https://user-images.githubusercontent.com/3524599/194479579-1c922a04-880e-44d0-9c82-63ab64f90d10.png">
