### ISSUE TITLE
[Bug]: Git Merge modal dropdown issue

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#17005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Git > Merge tab when the dropdown is disabled, we are still able to see the hand icon which indicates that the dropdown is clickable (when actually it is disabled).

https://www.loom.com/share/ba4aa74d9e9749d9b728e52076bdf74b

### Steps To Reproduce

1. Go to any application that is connected to git.
2. Click on the Git Settings icon in the toolbar below.
3. Go to the `Merge` tab.

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
This is a `design-system` issue.


https://user-images.githubusercontent.com/1573771/194709737-905e0a2b-83e9-48ac-b4f9-e465df386d05.mov


The fix involves disabling the icon too. 

But I am not sure if we really want that. There is a case when option+icon is disabled for the current value, but not for the other values, in that case there will be no way to change the value if icon and option-popup is disabled too.

@shadabbuchh Please provide the use case for disabling the options popup and icon and re-open .

**Comment by brayn003** [comment]
Hi @ginilpg this issue is resolved with the new ADS. 
![CPT2305231643-1000x577](https://github.com/appsmithorg/appsmith/assets/8724051/ee2e38a7-12b6-4d5f-8178-fdd60c9d2d76)

**Comment by rohitagarwal88** [comment]
Closing the issue as it has been resolved in ADS 2.0
