### ISSUE TITLE
[Bug]: Evaluated value and slash command dropdown get trimmed off on the property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On any events field of the property pane, switch to JS mode and observe the evaluated value and slash command dropdown get trimmed as seen in the screenshot

### Steps To Reproduce

1. Drop any widget with an event field on to the canvas
2. Switch to JS mode and observe the evaluated value and the slash command dropdown getting trimmed off as seen in the screenshot

![image](https://user-images.githubusercontent.com/79509062/191908742-326ace31-30a0-4dd9-8284-92bb03997ef7.png)

### Version

Cloud

**Comment by aswathkk** [comment]
Sorry. I didn't see this issue.
Closing this since I'm already working on it on a separate issue #17079
