### ISSUE TITLE
[Bug]: GraphQL not working proplery with export / import / fork / git sync 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1663852465423809

### Steps To Reproduce

https://theappsmith.slack.com/archives/C040LHZN03V/p1663852465423809

### Version

cloud

**Comment by rohan-arthur** [comment]
will be done with #16767
