### ISSUE TITLE
[Bug]-[Infinity]:Incorrect usage of storeValue does not throw a linting error

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#17040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to use `storeValue()` without setting the required parameter `value`, I see no linting error. Allowing `storeValue('key')` for example leads to storing keys with undefined values.

Here's the error thrown when you try to use vanilla JS `setItem('key')` 

```
Uncaught TypeError: Failed to execute 'setItem' on 'Storage': 2 arguments required, but only 1 present.
```

### Steps To Reproduce

1. Open a new/existing JS Object
2. Try adding `storeValue('hello')` to a function
3. Notice that no linting error is thrown even though `storeValue()` is missing a required parameter `value`

### Version

Cloud

**Comment by bharath31** [comment]
Assuming 50% of JS Editor users face this issue 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1500 |
| Effort (months)  | <<number>> |

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 in this case, this is valid because not passing the last argument would default to undefined and storing undefined is valid. Rather than a linting error, it should succeed

**Comment by bharath31** [comment]
@Nikhil-Nandagopal yes- this is a programmatically correct usage but users could end up introducing accidental bugs by not passing required parameters for methods. 

eg: `storeValue('key')` and `navigateTo('pageName')` would work without the required parameters `value` and `target` respectively but the code would not result into any useful action here. 

Linting errors or [Autocomplete hints](https://github.com/appsmithorg/appsmith/issues/17087) could help here.

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 but that isn't exactly true. The user may just be trying to set the value to undefined. Linting for function signatures as a problem I think needs to be thought through entirely and should be a new feature we introduce than treated as a bug of this specific case
