### ISSUE TITLE
[Bug]: Styling issues in List widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#17043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Couple of issues wrt to widget styling in the List widget:

1. Box Shadow changes do not reflect on the widget.
2. On changing the `App Border Radius` the radii of the widget, list items inside the widget & the image in the list items change however the same behaviour does not happen when we change the widget Border Radius. Should the same behaviour reflect in this case as well?
3. Changing the widget border radius does not change the radius of the items inside in edit & view mode. (Works fine in the deploy mode)

https://www.loom.com/share/0f4ff68012874937a0adfb865022ed6f

### Steps To Reproduce

1. D&D List widget.
2. Change the Box Shadow/Border Radius of the widget.
4. Change the App Border Radius.

### Version

Cloud

**Comment by dilippitchika** [comment]
Fixed in list v2
