### ISSUE TITLE
[Bug]: Deleting all the data in Property Pane does not remove all the list items in List widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#17044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are able to see one List item even when we delete all the data in the Property Pane.

https://www.loom.com/share/6691d9eaba9f439a9bd2353168d6944e

### Steps To Reproduce

1. D&D a List widget.
2. Clear all the dummy data from the Property Pane.

### Version

Cloud

**Comment by Tooluloope** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/15839
