### ISSUE TITLE
[Bug]: The action selector for setInterval is broken

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#17055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The action selector for set interval asks the user to write the callback instead of letting them select it from a dropdown like we do everywhere else
if you enter showAlert in the callback, the action selector gets broken

### Steps To Reproduce

1. Drag a button
2. Configure setInterval on Click
3. Add showAlert('test') in the callback

### Version

Cloud

**Comment by bharath31** [comment]
@rimildeyjsr could you confirm if your refactor solves this issue?

**Comment by rimildeyjsr** [comment]
i will take a look at it

**Comment by bharath31** [comment]
@rimildeyjsr could you add an estimate to this task?

**Comment by arunvjn** [comment]
Fixed in [e94e1b6](https://github.com/appsmithorg/appsmith/pull/19689/commits/e94e1b6d6b4235051c1fd47701e8385d47b52747)
Please test https://ce-19689.dp.appsmith.com/

**Comment by AnandiKulkarni** [comment]
This is fixed
