### ISSUE TITLE
[Bug]: Create a new control to group the min and max auto height with limits

### ISSUE THREAD

**Issue by ankurrsinghal** [appsmithorg/appsmith#17056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, there is no option to create 2 different controls which are dependent on each other. For example, when we have min greater than max it throws an error, but if we update the max to be more than min, the error is still there because there is no way to update the min control form the max control.

### Steps To Reproduce

1. DnD any widget with Auto Height enabled.
2. Enable the Auto Height with limits.
3. Set min to be greater than max.
4. Observe there is an error.
5. Now update the max to be greater than min.
6. Observe that the max control error is gone but min control still shows an error.

### Version

Cloud

**Comment by ankurrsinghal** [comment]
Created a separate issue for wider perspective, https://github.com/appsmithorg/appsmith/issues/17159

**Comment by somangshu** [comment]
@riodeuno can we close this issue?
