### ISSUE TITLE
[Bug]-[0]:Autocomplete does not suggest same function name that belongs to a different object

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If there's a function of the same name in different objects then autocomplete does not show the function name as it incorrectly identifies it as a self-reference

### Steps To Reproduce

1. Drop 3 JS objects `JSObject1`, `JSObject2`, `JSObject3` and don't modify the structure of any of the objects
2. Start to type out `JSObject2.myFunc1` under `myFunc1` of `JSObject1` - observe `myFunc1` is not an autocomplete suggestion on `JSObject2`

https://www.loom.com/share/b32e0dc446ab4eeb92eeb0bdd8600297

### Version

Cloud

**Comment by bharath31** [comment]
@satbir121 this would need an RCA

**Comment by satbir121** [comment]
@bharath31 Adding effort here. Moving it to Product backlog.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | |
| Effort (months)  | 0.25 |
