### ISSUE TITLE
[Bug]: Getting "Resource not found" error on release app 

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#17061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user tries to edit the 'Release App' which is regression_sept_26 app "Resource not found" error is displayed on the screen.

### Steps To Reproduce

1. Go to this url:- https://release.app.appsmith.com/applications
2. Click on Edit button on 'regression_sep_26' app
3. Observe the error on the screen

**Actual Result**
"Resource not found" error is getting displayed when the user tries to edit the app.

**Expected Result**
User should be able to edit the app without any error.

**Note**
Please find the attached video: https://www.loom.com/share/f453c2482c074b8c8155ba80c13d28f6

### Public Sample App

 https://release.app.appsmith.com/app/release-sep-26/page1-6331329043b74e3b2d191598/edit/generate-page?branch=master

### Version

cloud v1.8.3

**Comment by IAmAnubhavSaini** [comment]
@Richarex could you give me access for the app

**Comment by Richarex** [comment]
@IAmAnubhavSaini can see you as the administrator while sharing the app with you.

**Comment by AnaghHegde** [comment]
@Richarex Do you remember the actions you performed on the app before the app ended up in this state?

**Comment by RakshaKShetty** [comment]
@Richarex marking the issue as critical as this was happening only in this app and couldn't repro it. so lowering the priority

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we can't reproduce
