### ISSUE TITLE
[Bug]: While adding new JSobject error is displayed - 'JSobject1 already exist'

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#17065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Created new app and try to add new JSobject >> Error is displayed that 'JSobject1 already exist'

Expected: Error should displayed when there is already a JSboject1 available while editing the JSboject name.
While creating, there should not be any error and it should create the JSobj appending numbers.

https://user-images.githubusercontent.com/80756091/192277407-2bbfd098-628f-47e3-a894-8455249a9330.mov

Env : Release/ Cloud

### Steps To Reproduce

1. Create a app
2. Create new JSobject 

Observation : Error is displayed that the JSobject1 already exist
Expected : If JSobject1 is not available on app it should not display the error and it should add JSobject

### Public Sample App

https://release.app.appsmith.com/app

### Version

could

**Comment by Nikhil-Nandagopal** [comment]
@AnandiKulkarni it seems to be working for me

**Comment by AnandiKulkarni** [comment]
@Nikhil-Nandagopal its still reproducible at my end.

**Comment by AnandiKulkarni** [comment]
Imported the app on production and able to reproduce it

**Comment by bharath31** [comment]
@AnandiKulkarni are you able to reproduce it on new/existing apps without an import?

**Comment by AnandiKulkarni** [comment]
@bharath31 this is reproducible on few apps and tried later on creating new app and issue no more existed but it is constantly existed on shared app. App is in primary stage and created on release date. Not sure why this error started coming

**Comment by bharath31** [comment]
related to related to https://github.com/appsmithorg/appsmith/issues/14755
