### ISSUE TITLE
[Bug]: Number and Range slider - Min Value field - Default value not set.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I drag and drop the Range Slider, the default value is not set for Min Value field

### Steps To Reproduce

1. Drag and drop the Range and Number Slider widgets
2. In the Property pane, not that the Min Value field is blank (though evaluated value shows as 0)

Expected behavior - it should be populated with 1 (as per [this](https://www.notion.so/appsmith/Slider-Widgets-c8e9fcce6cdf4bcb98923669139b7087) Notion doc)

### Version

Release

**Comment by yaldram** [comment]
We have updated the `Slider widget defaults`, the min value should start from 0. So in the code I have passed `0` & not `1`, I have updated the Notion Document. 

In the property pane though we don't actually see the `0` value we only see the `placeholder` as 0, I think this is a bug in the property pane input.  I will check this with the team and raise a bug.

**Comment by btsgh** [comment]
@yaldram - ok. 
Yes in the property pane, only placeholder is seen. This needs to be fixed, because, if I enter some value in the min value text box, and then delete it, it gives an error that the value cannot be empty. This gives a wrong impression to the user.

**Comment by yaldram** [comment]
I have created an issue for the property pane input not showing `0` here - https://github.com/appsmithorg/appsmith/issues/17080

**Comment by btsgh** [comment]
Fixed in Release.
