### ISSUE TITLE
[Bug]-[Infinity]:Appsmith treats a string as a number when the string is a numeric value with leading zero(s)

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#17072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This one comes from this [post](https://community.appsmith.com/t/adding-a-string-that-is-a-number-with-a-leading-zero/180)

User's complain:

https://community.appsmith.com/t/adding-a-string-that-is-a-number-with-a-leading-zero/180/12

### Steps To Reproduce

1. Let's have a table named x where col has some data "098765" of varchar type
2. Create a query like select * from x where col = {{"098765"}} 
3. Appsmith identifies "098765" as an integer and thus loses the leading zero

### Version

Cloud / Self Hosted

**Comment by sribalajig** [comment]
Affects users using ANY datasource (~12700). Assuming a 5% impact (users who have numeric strings), reach = 635
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 635 |
| Effort (months)  | <<number>> |
