### ISSUE TITLE
[Bug]: Content in property pane gets trimmed for certain widgets.

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#17079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some content in the bottom of the property pane gets trimmed

![Screenshot 2022-09-27 at 11 13 10 AM](https://user-images.githubusercontent.com/10436935/192443159-45d2dc7b-8585-44e3-b487-e8e5f7f8f159.png)

### Steps To Reproduce

1. Add a tab widget
2. Enable JS mode for onTabSelected
3. Click on the onTabSelected input and notice the popup below it gets trimmed

### Version

Cloud 1.8.2

**Comment by aswathkk** [comment]
![Screenshot 2022-09-27 at 11 23 10 AM](https://user-images.githubusercontent.com/10436935/192443982-4b40f0be-1f36-4287-84ce-6bf7dcdae6f4.png)
Also, the evaluated value popup is getting hidden.

**Comment by Sripriya93** [comment]
we are seeing a scroll in the Tabs widget in Tab settings, so moving to In progress

![image](https://user-images.githubusercontent.com/104895602/192779966-3dc83c6d-610b-40b1-b022-621735d7ceaf.png)
