### ISSUE TITLE
[Bug] Cloned an app and the original one isn't available.

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1707]
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand this is related to the issue uolo faced

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : Yes. But unfortunately haven't been able to reproduce this.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand closing for now. Can we add some logs for self-hosted instances? Maybe we can just write our console logs to a file?
@mohanarpit

**Comment by trishaanand** [comment]
Reopening this issue because it was reproduced on the cloud deployment of Appsmith.
