### ISSUE TITLE
[Bug]: Select Widget - Dropdown - cuts when placed at a particular position in the canvas

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#17070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we place the Select widget in a particular position, the dropdown options cut off at the top and not able to scroll as well

![image](https://user-images.githubusercontent.com/104895602/192288203-20d9777d-032c-44c4-8789-6d5387aadec6.png)

### Steps To Reproduce

1. D&D a Select widget
2. Add few more options to the dropdown
3. Place the widget parallel to the Explore/ Widgets 
![image](https://user-images.githubusercontent.com/104895602/192289430-9dc94e3e-d25f-469c-a4c6-290ca9f700b1.png)
4. Click on the dropdown
5. Observe that first two options (Filter, First option) are cut off and there is no dropdown to select or have a filter.

### Version

Release

**Comment by dilippitchika** [comment]
@Sripriya93 this issue is similar to #16169, closing this and will solve it there
