### ISSUE TITLE
[Bug]: "Internal server error while processing request" error is displayed while forking any template

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#17071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user tries to fork any template then '''Internal server error while processing request" error is displayed on the screen.

### Steps To Reproduce

1. Go to this url:- https://release.app.appsmith.com/applications
2. Click on the "Templates" button at the top
3. Now on templates page select any template 
4. Click on "Fork this template" button and observe the error

**Actual Result**
Internal server error is displayed while forking the template.

**Expected Result**
User should be able to fork the template without any issues.

**Note**
Please refer to the attached video:- https://www.loom.com/share/08540f95963c4c0abf5aa810471e2b9b

POST https://release.app.appsmith.com/api/v1/app-templates/621c6c6589659f362e07f7b3/import/63318266a263271357401314 returns 500 with following response

```
{
  "responseMeta": {
    "status": 500,
    "success": false,
    "error": {
      "code": 5000,
      "message": "Internal server error while processing request"
    }
  }
}
```

### Version

cloud v1.8.3

**Comment by akash-codemonk** [comment]
Closing. This seems to have been a temp issue. It is working now.
