### ISSUE TITLE
[Bug]:  Property Pane INPUT_TEXT if passed 0 as the default value for a widget property does not show the value

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#17080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- For the `Number & Range` slider widgets, the `Min. Value` property uses the `INPUT_TEXT` control.
- When we pass the value `0` as the default value it does not show up in the `INPUT_TEXT` control instead we only see a placeholder.

### Steps To Reproduce

1. Drag and Drop the `Number / Range Slider` widget.
2. Check the `Min. Value` property in the property pane

### Version

Release

**Comment by Sripriya93** [comment]
We are able to see the Evaluated value as 0 when we check the default Min value after we D&D Number and Range slider
![image](https://user-images.githubusercontent.com/104895602/193194406-f7efc98a-6db0-4bf8-bfa5-336f788dcbc9.png)
![image](https://user-images.githubusercontent.com/104895602/193194474-8e7b4ef4-0fd9-4bd9-b646-77b092e0fbeb.png)
