### ISSUE TITLE
[Docs]: Add FAQ related to HIPAA Compliance

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#17089]
<p>User wanted to know if Appsmith is HIPAA compliant. </p>
<p>https://app.intercom.com/a/apps/y10e7138/inbox/inbox/all/conversations/164629100080096</p>

**Comment by jnikhila** [comment]
Add it to FAQ.

**Comment by danciaclara** [comment]
Fixed by https://github.com/appsmithorg/appsmith-docs/pull/889
