### ISSUE TITLE
[Bug]: Git Sync Error - Unexpected State: Duplicate Key error

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#17094]
User is getting the following error when they try to commit their changes.

[Front conversations](https://app.frontapp.com/open/top_51wuk)

**Comment by nihaofana** [comment]
It's fixed now

**Comment by nihaofana** [comment]
It's fixed now

**Comment by vuiets** [comment]
@pranavkanade could you post a gist of the issue here? Not all of us have access to Front.

**Comment by pranavkanade** [comment]
Sorry, my bad. Updated the description

**Comment by vuiets** [comment]
Thanks @pranavkanade. @AnaghHegde could you investigate this issue and find it's cause? It'll help add a RICE score to this and prioritise it.

**Comment by AnaghHegde** [comment]
The error message says the issue is with Writing data because of the Index rules on the Unique key. Do we know how to user is reached this state? This does not look like a git problem.

**Comment by pranavkanade** [comment]
Removed the screenshot on user's request. Closing this as we are not able to reproduce this.

**Comment by pranavkanade** [comment]
@AnaghHegde @vuiets The user solved the issue by first deploying the app and then git-sync

**Comment by vuiets** [comment]
Thanks for the follow up and update @pranavkanade 🙏
