### ISSUE TITLE
[Docs]: Update Security to mention where we process data for cloud users

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#17092]
<p>https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100119943#part_id=comment-164629100119943-15138983487</p>

**Comment by jnikhila** [comment]
Add to FAQ.

**Comment by danciaclara** [comment]
Fixed by https://github.com/appsmithorg/appsmith-docs/pull/889
