### ISSUE TITLE
[Bug]-[1340]:Same widget names in different pages causes widget to show stale value

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#17097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there is a Table widget with the same name on two pages in an application, Navigating from one page to another shows the widget with tableData from the previous page.

https://user-images.githubusercontent.com/5328605/192513123-8ad30580-76d3-47ae-8cf9-cce74a440f4f.mov

### Steps To Reproduce

1 . Drag a table widget and bind it to a sample user data source query
2. Create a new page
3. Drag a table widget on page 3 as well.
4. Observe that while navigating from one page to another shows the table widget with data from the previous page.
5. Renaming the table widget in any one of the pages fixes this issue.

### Public Sample App

https://app.appsmith.com/app/untitled-application-26/page1-6332dfa22384d5623d9a03d1

### Version

cloud

**Comment by bharath31** [comment]
Assuming 1% of users who navigate between pages have the same widget name. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1340 |
| Effort (months)  | 0.5 |
