### ISSUE TITLE
[Bug]: Autocomplete does not suggest local variables on widget property pane as it does on the editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Autocomplete suggestion does not show up for local variables the way it shows up on the JS editor

### Steps To Reproduce

On the editor:
![image](https://user-images.githubusercontent.com/79509062/192538329-9f04829d-a9b1-46e2-a4d5-4185340bc21a.png)

On the property pane:
![image](https://user-images.githubusercontent.com/79509062/192547760-edbdd8f7-6a48-4975-8994-243d58f7f11f.png)

### Version

Cloud

**Comment by satbir121** [comment]
@ramsaptami This issue is not reproducible. Can you please check it?

**Comment by ramsaptami** [comment]
Closing this since it seems to have been fixed
