### ISSUE TITLE
[Bug]: Proxy not used for access token request during OAuth

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#17114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When logging in to a self-hosted Appsmith with Google OAuth2, and the server has a proxy configured, then then access token request that is made by the server doesn't use the proxy. Instead, this request is made directly.

### Steps To Reproduce

1. Install `brew install mitmproxy`, and start the proxy with `mitmweb --listen-port 9020 --web-port 9021`. This will open a veiw into all the requests going through the proxy.
1. Start an Appsmith with `docker run --name ace -p 8001:80 -v ~/appsmith-stacks:/appsmith-stacks -d --pull always -e HTTP_PROXY=http://host.docker.internal:9020 -e HTTPS_PROXY=http://host.docker.internal:9020 appsmith/appsmith-ce:release`.
1. Find the CA root cert at `~/.mitmproxy/mitmproxy-ca-cert.pem`. Use instructions at <https://docs.appsmith.com/setup/instance-configuration/custom-ca-root-certificate> to add this cert to your Appsmith installation, restart and preform the test again.
1. Configure OAuth, Google or GitHub on your instance.
1. Attempt to login via Google or GitHub, observe that the access token request, usually a request to `googleapis.com` if via Google, does _not_ show up in the Proxy's view.

### Version

Self Hosted

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_52b7w)

**Comment by pranavkanade** [comment]
@sharat87, the user says they upgraded to v1.8.5 and still seeing this issue.
https://app.frontapp.com/open/msg_1f4vp26k

**Comment by jainsrbh** [comment]
Any further updates on it? Any special configuration required?
