### ISSUE TITLE
[Bug]: In MySQL db, on binding db name to a widget, select command errors out

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In MySQL, when I bind the database name to a widget (say text1.text or input1.text), the select command errors out. 

### Steps To Reproduce

1. Connect to MySQL db. Details in [here](https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e)
2.  Create a Query to select all from alldatatypes8 table limit to 1 record
3. SELECT * FROM alldatatypes8 LIMIT 1; This runs and gives the output.
4. Add two widgets Input1 and Input2, where Input1 = 1 and Input2 = alldatatypes8
5. Now modify the query to SELECT * FROM {{Input2.text}} LIMIT {{Input1.text}};
6. This errors out with the following message - 

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''alldatatypes8' LIMIT 1' at line 1
<img width="805" alt="Screenshot 2022-09-28 at 12 51 50 PM" src="https://user-images.githubusercontent.com/101863839/192714575-a2f47678-74c0-4245-992d-926334924caf.png">

### Version

Production

**Comment by btsgh** [comment]
@subrata71  - Ok. If I unselect Prepared Statement, the query passes. Is it also possible to add this information to the following text below the Use Prepared Statement switch (for ignorants such as - me :D )-
" Turning on Prepared Statement makes your queries resilient against bad things like SQL injections. However, it cannot be used if your dynamic binding contains any SQL keywords like 'SELECT', 'WHERE', 'AND', etc. "

**Comment by subrata71** [comment]
When you turn off the prepared statement variable substitution takes place meaning the binding names are replaced by the respective values. And finally, the query looks like a simple string without any substitution in it. That's why it works under simple statements. 

When the underlying r2dbc library throws any error we propagate the same to the user. Customizing this error message to what you mentioned in this particular scenario cannot be achieved easily. 
@btsgh

**Comment by btsgh** [comment]
@subrata71 I was not talking about an error message being customised. The message that is below the query pane, could that be updated to include a shortened version of - 
"Prepared statements only allow parameters to be bound for "values". You cannot expect binding table names or column names through the prepared statement."

<img width="908" alt="Screenshot 2022-09-30 at 12 38 21 PM" src="https://user-images.githubusercontent.com/101863839/193211807-d5a06e81-02aa-4005-acf2-fce3fd30c4e5.png">

**Comment by Nikhil-Nandagopal** [comment]
Closing since this is expected. @btsgh please raise another issue if you have a suggestion for the text
