### ISSUE TITLE
[Feature]: Change default label position to top for all widgets which have labels 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Change default label position to top for all widgets which have labels and increase their height so that each widget with label fits in the bounding box. 

Widgets to be updated
1. All inputs
2. All selects
3. Datepicker
4. Group widgets

No need to do it in checkbox, switch and rich text editor

### Why should this be worked on?

When user drops the widget in the form/container the label cuts off today which then means user has to open the property pane and adjust the label there

**Comment by adarshlilha** [comment]
@dilippitchika I would like to work on this
To confirm - by default, labels are currently positioned "left" -> this needs to be positioned "top"
is this correct understanding?
<img width="307" alt="Screenshot 2022-09-29 at 21 59 44" src="https://user-images.githubusercontent.com/13575704/193087396-f8667e37-145f-470e-b754-0825e226e47a.png">

<img width="287" alt="Screenshot 2022-09-29 at 21 58 29" src="https://user-images.githubusercontent.com/13575704/193087133-ba572409-16c5-42f3-b397-22faf95135c1.png">

**Comment by dilippitchika** [comment]
Hello @adarshlilha yes, but this would also need a change in the default height as well. Since in the 2nd image you see the widget exceeds the boundary

**Comment by dilippitchika** [comment]
Would you be interested in picking this up?

**Comment by adarshlilha** [comment]
sure @dilippitchika I'll work on this, thanks

**Comment by Ayush-Kori** [comment]
Hey Can I work on this issue??

**Comment by dilippitchika** [comment]
Thanks for showing interest @Ayush-Kori

@adarshlilha will you be able to complete it, if not please let me know and we can assign to @Ayush-Kori

**Comment by tauantcamargo** [comment]
could i get it ? @dilippitchika

**Comment by dilippitchika** [comment]
Greetings @Ayush-Kori @tauantcamargo  thanks for showing interest 🎉 , This is all yours. Assigning this to you both of you for now. If one of you raises a PR first then we will assign only that person. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by sanjus-robotic-studio** [comment]
Hey Can I work on this As there is no update for about 4 days

**Comment by adarshlilha** [comment]
@dilippitchika I have changed the position of label to top for the input widgets
would need help on updating the default height of the label container, any pointers would be helpful, thanks

**Comment by dilippitchika** [comment]
Thanks @adarshlilha you don't have to update the label container height but the height of the widget which gets dropped by default. 

@yaldram @iamrkcheers can you folks help?

**Comment by yaldram** [comment]
Hey @adarshlilha when we change the label position to top you can see the widget is overflowing the gray box - 
<img width="186" alt="image" src="https://user-images.githubusercontent.com/13429535/196106002-a8ab9a5b-3153-46d7-ab0f-fa38b2c2110f.png">
I think we might need to update the `rows` property inside the `index.ts` files.
<img width="406" alt="image" src="https://user-images.githubusercontent.com/13429535/196106313-28398d2f-562d-4b02-9553-ab0bd83dd190.png">
Try assigning different values to the `rows` property, also check the `columns` property. Hope that helps.
