### ISSUE TITLE
[Bug]: Audit log: the JS object execute event is missing

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the JS object execute event is missing

### Steps To Reproduce

1.login as demo user
2. inside the app add a new js object
3. run the js object
4. now go to home page
5. click on admin setting 
6. now check the event is missing

### Version

http://ec2-65-2-149-212.ap-south-1.compute.amazonaws.com/applications

**Comment by vishnu-gp** [comment]
BE event is not there moving to Product Backlog
