### ISSUE TITLE
[Bug]: Selecting tab 2 from entity explorer doesn't open tab 2 but opens the default tab instead 

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i select the tab i want to see from the entity explorer, i only see the default tab

### Steps To Reproduce

1. Add a tab widget with 2 tabs
2. Navigate to the 2nd tab using entity explorer
3. Observe that the default tab is open

### Version

Production

**Comment by hetunandu** [comment]
Fixed with #21317

**Comment by Richarex** [comment]
This issue is fixed, verified it on release.
