### ISSUE TITLE
[Bug]: In MySQL, when I pass a string into a integer datatype column, the cell gets update with a 0.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In MySQL, when I pass a string into a integer datatype column, the cell gets update with a 0.

### Steps To Reproduce

1. Create a mysql datasource (Details [here](https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e))
2. Create a query like -
Update alldatatypes8 set PersonID = {{Input2.text}} where attendence = {{Input3.text}}
3. {{Input2.text}} - input2 widget datatype is text. PersonID column is of datatype int. 
4. I am passing random alphabets into this Input2 field and binding this widget to the above query.
5. Query passes and the PersonID cell in the database is updated to 0.
6. Also noted that even if this query is run without binding, by directly setting a string to PersonID (PersonID = 'estes'), even then the field is updated to 0.

Query should fail as the PersonID column is of INT type cannot allow text/string.

### Version

Production

**Comment by btsgh** [comment]
Another similar issue observed - 
Update alldatatypes8 set LastName = {{Input6.text}} where PersonID = {{Input2.text}}
Input6 = 00003arararara .. of original datatype text. Run above query, is successful
Now change widget from text to number datatype
Run above query, LastName is updated to blank.

**Comment by btsgh** [comment]
Another similar issue observed -

Update alldatatypes8 set LastName = {{Input6.text}} where PersonID = {{Input2.text}}
Input6 = 00003arararara .. of original datatype text. Run above query, is successful
Now change widget from text to number datatype
Run above query, LastName is updated to blank.
This seems to be incorrect behavior as only on change to Number datatype, the cell is updated to blank (null). If the widget is changed to say email with an invalid email entered in the widget (00003arararara), the cell still gets updated with this invalid email.

**Comment by btsgh** [comment]
Update alldatatypes8 set joiningdate = {{"2022-00-01"}} where PersonID = {{Input2.text}}
Update alldatatypes8 set joiningdate = {{"2022-09-00"}} where PersonID = {{Input2.text}}

The above cases cause the joiningdate cell to become blank.

Update alldatatypes8 set joiningdate = {{"0022-09-01"}} where PersonID = {{Input2.text}}
Update alldatatypes8 set joiningdate = {{"0000-09-01"}} where PersonID = {{Input2.text}}

These queries pass with the joiningdate cell updated to the above values.

Which is the right behavior?

**Comment by subrata71** [comment]
This happens due to a non-strict mode in MySQL. If you change the sqlmode to strict mode then this kind of query will result in an error. 

### Strict Mode
`set sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';`

### Non-strict Mode
`set sql_mode = '';`

**Comment by btsgh** [comment]
Thank you for detailing this finding @subrata71 ..
If it would be informative if the user is aware of this through appropriate messages. If the warning (along with the error) that is shown in MySQL client can also be shown here, it would help the user to know that this is the by default the behavior of MySQL server.

**Comment by Nikhil-Nandagopal** [comment]
Closing this for the same reasons as #17171
