### ISSUE TITLE
[Bug]: On updating tinyint datatype cell with a value outside the range, the cell gets updated with the max value of the range, instead of throwing an error.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I update a db  tinyint datatype cell with a value outside the range, the cell gets updated with the max value of the range, instead of throwing an error.

### Steps To Reproduce

1. Create a mysql datasource (Details [here](https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e))
2. Create a query like - 
Update alldatatypes8 set attendence = {{Input3.text}} where PersonID = {{Input2.text}}
3. "attendence" is of type tinyint. Input3 here is a number say 128 (or anything above it)
4. The query passes and shows updated rows as 1
5. However, when we see in the db cell, the value that has been added into the row is 127

For signed tinyint, it should bring up error if we add a value say -129 and below or 128 upwards
For unsigned tinyint, it should bring up error if we add a value say --1 or 256 onwards

### Version

Production

**Comment by subrata71** [comment]
This happens due to a non-strict mode in MySQL. If you change the sqlmode to strict mode then this kind of query will result in an error. 

### Strict Mode
`set sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';`

### Non-strict Mode
`set sql_mode = '';`

**Comment by Nikhil-Nandagopal** [comment]
This seems to be a behavior of the database and not related to appsmith so closing this. We should not be responsible for the behavior of the database
