### ISSUE TITLE
[Feature] Improve the UX for not logged in users accessing a page

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1717]
## Summary

End users who are not logged in and receive a deployed app are confused by the error message and think the app is broken. We should inform them of their not logged in status and direct them to log in

**Comment by areyabhishek** [comment]
A better fix for this problem is an automatic redirect instead of changing the 404 page. For now, I've made a small change to the 404 page.

**Comment by mohanarpit** [comment]
@areyabhishek I disagree. If we redirect the anonymous user to the logged in page, then the user knows that there is an application with that name & id. For private apps, that's a security breach. We shouldn't expose details of any private apps to anonymous users. I've attached a sample of the page shown by Github for a legitimate private repo when viewed by an anonymous user. 

<img width="1676" alt="Screenshot 2020-11-16 at 7 22 25 AM" src="https://user-images.githubusercontent.com/458946/99204709-7db16c00-27dc-11eb-8f89-85d8aff7656d.png">

Hence, I believe, we should solve this by messaging itself; telling the user that either the app doesn't exist or they don't have access to it.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit in this case it's neither of these 2 cases, it's that the app exists and the user has access but he's not logged in. For any non-public URL, can we just take users to the logged-in page or explicitly prompt a login? After login, if they try to access a protected resource we can say it doesn't exist or you don't have access.

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal But the act of taking them to a login page means that the app exists. Putting it another way, what would the flow be for an anonymous user who typed an incorrect URL? 

I believe that if the user is anonymous, then we should explicitly give a CTA on the error page to either: 
1. Login
2. Ask them to check the URL

This ensures that the experience is consistent for incorrectly typed URLs and apps that a user doesn't have access to.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit if the user is anonymous and typed an incorrect URL, we also prompt them to login.
I understand why GitHub does this experience because the # of private repos << # of public repos. If we look at sentry, the opposite is true and users are redirected to the login page.
The same is true of Gitlab where users are redirected to the login page.
[GitLab Invalid URL](https://gitlab.com/quicla/platform/external/zofli)
[Sentry Invalid URL](https://sentry.io/organizations/apsmith/issues/?environment=Production&project=1546547&statsPeriod=7d)
