### ISSUE TITLE
[Bug]-[1072]:Page numbers are incorrect when records in a page are different than page size

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When records in a page are different than page size, for example page size is 10 but records in a page are 50 then the no. of pages is still calculated using the page size but not the records on the page. This causes confusion to users.

### Steps To Reproduce

1. Add a table
2. Enable server side pagination
3. Add more records than the page size by setting the limit higher
4. Add total row count
5. Observe the number of pages are not accurate

### Version

Production

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_52v4c)

**Comment by dilippitchika** [comment]
Assuming 50% set the limit higher

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 268 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@souma-ghosh can you pick this up next sprint when you are back?

**Comment by souma-ghosh** [comment]
Sure @dilippitchika

**Comment by dilippitchika** [comment]
@souma-ghosh please add to next sprint and estimate

**Comment by souma-ghosh** [comment]
Ya that's done

**Comment by keyurparalkar** [comment]
@pranavkanade just a quick update. We are currently reverting the code change made in this issue #17187 since this revert fixes #18574.
What this implies is that users will face the issue mentioned in #17187 and we advice you to use table1.pageSize to limit the query while doing server side pagination

CC: @dilippitchika

**Comment by parothia** [comment]
When this will be fixed..

**Comment by dilippitchika** [comment]
@parothia we are still triaging this, can you let us know the following
1. Are you using table's pagesize property as the limit in your queries?
2. If you are not using it then can i know why?

**Comment by parothia** [comment]
@dilippitchika 
I am using APIs, and api will give response with count of total number of records..
For calling the API im using Table pageSize property..also I tried with constant..

it determines the number of pages correctly..if the pages are of full capacity..
as in most cases the last page will not be full .. so what it is doing dividing the total records by taking the number of entries in table..which can be 1 in last page 

so when i land on last page...the number of pages increases.. depends on the records on last page

**Comment by dilippitchika** [comment]
@parothia we fixed it here - https://github.com/appsmithorg/appsmith/issues/18574, it should be available next monday for everyone. 

This only works when you use the Table pageSize property as the limit in your apis

**Comment by parothia** [comment]
Thanks @dilippitchika

**Comment by somangshu** [comment]
Closing in favour of #18574. @dilippitchika please correct me If I am wrong here

**Comment by dilippitchika** [comment]
@somangshu this issue still exists

**Comment by dilippitchika** [comment]
We will solve it with auto height feature, fixed height will always work with table's pagesize

**Comment by NickImmoflow** [comment]
Hey, 
in the v1.13 we are facing the same issue with a list widget where we try to use server-side pagination. 

In the editor it works fine and when I run the list widget in the latest deployed preview, the list widget allows me to open the next page without any data.  

Is there any explanation why it works fine in the editor and preview area but not in the latest deployed preview?

**Comment by Nikhil-Nandagopal** [comment]
@NickImmoflow I'm not sure of the exact issue you are facing but it's expected that if you are using server side pagination then you should return the same number of rows that can be displayed in a page.

**Comment by NickImmoflow** [comment]
@Nikhil-Nandagopal In my case it was due to the select query for total records. I guess it did not load on time. And now is working well as expected.
