### ISSUE TITLE
[Bug]: Can not reference list of widgets in JSObject

### ISSUE THREAD

**Issue by charles-bloomfield** [appsmithorg/appsmith#17199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```ts
export default {
        datePickers: [
            DatePicker1,
            DatePicker2,
        ],

	datePickers: () => [
            DatePicker1,
            DatePicker2,
	],
	
	getChangedDatePickers: () => {
            //this blows up
            this.datePickers.filter((picker) => picker.formattedDate !== '');

            //this works
            this.datePickers().filter((picker) => picker.formattedDate !== '');
        }
}
````

### Steps To Reproduce

define two date pickers, replicate code above

### Version

Appsmith Community v1.8.0

**Comment by Nikhil-Nandagopal** [comment]
This is likely related to #14568

**Comment by Rishabh-Rathod** [comment]
@charles-bloomfield Could you please confirm if the same issue is reproducible for you after refreshing the page and running the function again?
