### ISSUE TITLE
[Bug]: GraphQL | URL Unconfigured toast message correction

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#17191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="829" alt="Screenshot 2022-09-29 at 7 24 42 PM" src="https://user-images.githubusercontent.com/91450662/193053634-f8062f6b-96d6-4c28-904c-83d4708e075f.png">

### Steps To Reproduce

1. Create new GraphQL API
2. Do not configure the url, click on run from the opened query pane
3. Observe the toast- as shown in above snap [it seems as if CE is not configured is a separate line of text - while its actually overflowing from previous word 'DEFAULT_GRAPHQL_DATASOUR**CE**']
4. **Expected: Clear error message to be shown to user**

### Version

Prod/Release v1.8.4

**Comment by sumitsum** [comment]
Closing as this issue is not valid anymore.
