### ISSUE TITLE
[Feature]: Support console statements that are executed on page load

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Console statements in async/sync functions that run on page load, don't appear on the debugger. This needs to be logged and preserved so user can refer to it once the app has loaded

### Why should this be worked on?

This is the functionality of the browser console and since we're supporting native console log, this needs to be supported as well

**Comment by bharath31** [comment]
this is now supported
