### ISSUE TITLE
[Bug]: Function content is not reactive hence we see a cyclic dependency error when certain conditions are met

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Function content is not reactive and hence when certain conditions are met, we see a cyclic dependency error as seen in the video attached. Refreshing the page reads the correct function content but causes bad UX to not update code as and when user makes amends

### Steps To Reproduce

1. Create a function with `Text1.text` as seen in the video
3. Change the content `showAlert("monday")`
4. Bind this function to a text widget named Text1 and observe the cyclic dependency error as seen in the video attached

https://www.loom.com/share/21574546376641eaa9ffc11047084ae9

### Version

Cloud

**Comment by bharath31** [comment]
no longer reproducible
