### ISSUE TITLE
[Task]: Arrows are too faint, almost unnoticable. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

It took me almost 1 minute to notice that there were two arrows here. 
![Screenshot 2022-09-30 at 2 13 28 PM](https://user-images.githubusercontent.com/1757421/193231014-811080a3-0142-4e7f-8846-253de3ae9134.png)

**Comment by Shyam-NR** [comment]
hey, can I work on it if this is still available?

**Comment by tanishk-23** [comment]
@sumitsum can I work on this issue?
