### ISSUE TITLE
[Bug]: JSAsync() | NonTagged Async function when bound gives irrelevant evaluation error

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#17227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Non Tagged async function in JS Obj:**

<img width="348" alt="Screenshot 2022-09-30 at 1 12 40 PM" src="https://user-images.githubusercontent.com/91450662/193234009-cac33d98-eb40-4162-b6bc-1844309bbc63.png">

**When bound the sync way to widgets:**

<img width="605" alt="Screenshot 2022-09-30 at 1 14 27 PM" src="https://user-images.githubusercontent.com/91450662/193234056-9f5dc4db-dd41-4af2-885a-edcbe267b4c1.png">

### Steps To Reproduce

1. Create a new JS object - run a query/api within JS function but do not tag the function async
2. Map the results of this JS method to a widget for display - here: table
3. FYI: Async methods should be called as 'jsobj.func.data'
4. Call this async method similar to a sync method call : here: `JSObject1.syncc2()` when bounding
5. **Observe the evaluation error displayed is confusing** (above image)
6. **Expected: Better debug error to the user to help him correct the issue himself**
7. Deploy & verify - the table simply does not load with no indication to user about the issue [Table might also not load incases of no records hence need a way to differentiate it here]

### Version

Prod/Release v1.8.4

**Comment by bharath31** [comment]
this should no longer be an issue. the current error message is more descriptive
