### ISSUE TITLE
[Bug]: Explorer pane shows a datasource connection error even when error is rectified

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#17238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**When** I have a datasource connectivity error, and I fix the error, **I don't expect to see the error** on the explorer pane after it has been rectified.
![datasource-error](https://user-images.githubusercontent.com/15727421/193269173-e61a63e8-31e2-4f96-b755-a0f68e19d7fd.png)

### Steps To Reproduce

1. Go to the datasources page and enter an invalid datasource configuration.
2. Hit "Test".
3. The connection test should fail and the connection error should be shown on the explorer pane on the left. You should see something like :
![datasource-error](https://user-images.githubusercontent.com/15727421/193269173-e61a63e8-31e2-4f96-b755-a0f68e19d7fd.png)
5. Now fix the connection error.
6. Although the connection error is fixed, you will still see the error on the explorer pane.
![datasource-error](https://user-images.githubusercontent.com/15727421/193269173-e61a63e8-31e2-4f96-b755-a0f68e19d7fd.png)

### Version

Cloud

**Comment by prapullac** [comment]
The issue looks good on the Dp and hence we can merge it to release
