### ISSUE TITLE
[Feature] JSON Form Widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1724]
## Summary
Form needs a few new features

- Generate form from a config
- Create and access nested structures in the form widget
- An Array form field on which you can keep adding multiple text fields

## Motivation
Form widget out of the box has limited functionality and making anything complex requires a lot of configuration from an App Developer

## Additional Context
Config can be something lime what jsonform uses

https://jsonform.github.io/jsonform/playground/index.html?example=fields-tabarray

**Comment by ioloc** [comment]
@hetunandu so the current situation I find myself in is building custom interfaces for bulk inserts mutations similar to (example from Hasura https://hasura.io/blog/bulk-insert-mutations-with-graphql-e22727ce5b12/ ), where you are inserting a parent object and multiple child objects at the same time (I am using Hasura and think they handle it as a transaction). 


mutation {
  insert_author(
    objects: [
      {id: 5, name: "Jacob"}
    ]
  ) {
    affected_rows
  }
  
  insert_article(
    objects:[
      {id: 1, title: "Sample article 1", content: "Some content", author_id: 5},
      {id: 2, title: "Sample article 2", content: "Some content", author_id: 5}
    ]
  ) {
    affected_rows
  }
}



The example shown (https://jsonform.github.io/jsonform/playground/index.html?example=fields-tabarray) here requires that you supply a schema, so what might be nice is a widget that visuall allows you to build this schema and form, where the output would be something like ... {
  "schema": {
  	"friends": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "Friend",
        "properties": {
          "nick": {
            "type": "string",
            "title": "Nickname"
          },
          "animals": {
            "type": "array",
            "items": {
              "type": "string",
              "title": "Animal name"
            }
          }
        }
      }
    }
  },
  "form": [
    {
      "type": "tabarray",
      "items": {
        "type": "section",
        "items": [
          "friends[].nick",
          {
            "type": "array",
            "items": [
              "friends[].animals[]"
            ]
          }
        ]
      }
    }
  ]
} 

another thought I had .. but I'm not too sure how this would work is to import the schema directly from  GraphQL introspection. Maybe something that could be investigated if you play on more deeply integrating with graphQL APIs. (I am by no means an expert in GraphQL, just use it a lot) , but do you guys think something like this is achievable?

**Comment by somangshu** [comment]
Closing this in favour of #2504, Add any missed requirement over there!
