### ISSUE TITLE
[Feature]: Add Stripe Integration

### ISSUE THREAD

**Issue by CookieHax** [appsmithorg/appsmith#17244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Adding stripe integration would be cool, lot's of companies use Stripe for checkout and it would be very cool if we could share data from stripe and visualize it.

### Why should this be worked on?

Would benefit many people and it would be cool if there were things such as a refund panel, checkout link generator and customer viewer, meaning you can view data all from one location.

**Comment by Nikhil-Nandagopal** [comment]
Hi @CookieHax thanks for the feature request. We're already tracking this issue here #3599 so I'm closing this
