### ISSUE TITLE
[Feature]: Mongo increase width of query box

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#17265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The input box to enter the MongoDB query is single column width, and this hampers readability for longer queries. Compare this to GraphQL where the query body is given a much wider box.
Ref: https://theappsmith.slack.com/archives/CRVRBGU1K/p1664776246729369
Reference image:
![Uploading CleanShot 2022-10-03 at 08.49.48@2x.png…]()

### Why should this be worked on?

increase readability of query body

**Comment by Irongade** [comment]
Tagging @parth-appsmith to this issue, kindly provide us with your thoughts on this.

**Comment by Nikhil-Nandagopal** [comment]
@Irongade we can use the same field we use for the insert body right? This is a bug and it used to work that way.

**Comment by Irongade** [comment]
Do you mean this component? @Nikhil-Nandagopal 

<img width="1125" alt="Screenshot 2022-10-10 at 08 55 31" src="https://user-images.githubusercontent.com/37867493/194820778-71852ebc-5875-4cd4-9647-1a8140efd0d9.png">

**Comment by Nikhil-Nandagopal** [comment]
@Irongade Yes

**Comment by Irongade** [comment]
@Nikhil-Nandagopal Okay 👍

**Comment by prapullac** [comment]
Tested on the local and it looks good to me
