### ISSUE TITLE
[Bug]-[500]:Navigation drawer for pages on mobile view should close when a page is selected

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#17260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When in mobile view, the navigation drawer for pages that open on clicking the hamburger menu should automatically close when a page is selected. Today, the user has to perform two clicks -  select the page and click on the close icon or outside to close the drawer.

### Why should this be worked on?

Was asked by a user on Discord - https://discord.com/channels/725602949748752515/1026357863284736091/1026357863284736091

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | 0.5 |

**Comment by ShaneMaglangit** [comment]
Hi, is this already being worked on? Otherwise, I would love to work on it.

**Comment by dhruvikn** [comment]
We fixed this along with App Navigation. This is not reproducible anymore. Closing it.
