### ISSUE TITLE
[Feature] iframe Widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1726]
## Summary
An iframe widget will allow app developers to embed other pages or components directly. 

## Developer Handoff File
https://www.figma.com/file/8aAbH6N9lYh4RnV37Rz4E8/Iframe-widget-design-Tue-4-May-2021?node-id=2%3A3024

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you suggest some of the properties of the iframe apart from URL?

**Comment by ioloc** [comment]
Could I ask, would something like this be possible ? 

https://stackoverflow.com/questions/11878947/auto-login-remote-site-inner-in-iframe

**Comment by rishabhsaxena** [comment]
> Could I ask, would something like this be possible ? (noting that this approach is insecure) ... but something like this.
> 
> https://stackoverflow.com/questions/11878947/auto-login-remote-site-inner-in-iframe

@ioloc you mean in the approach mentioned [here](https://stackoverflow.com/questions/11878947/auto-login-remote-site-inner-in-iframe#answer-16833828) ?

Here we are using form `target` attr to show the result in the iframe. [Example](https://stackoverflow.com/questions/168455/how-do-you-post-to-an-iframe#:~:text=An%20iframe%20is%20used%20to,name%20of%20the%20iframe%20tag.)

We could also provide an interface to communicate with the iframe using `postMessage`, could be useful if the dev has access to the page within the iframe

**Comment by Nikhil-Nandagopal** [comment]
@ioloc @rishabhsaxena thanks for contributing here with these great points.
To summarise, we should have access to an 
1. onURLChange action
2. onMessageReceived action
3. message property (object)
internal properties for the iframe
URL, hash, query params, message

**Comment by areyabhishek** [comment]
Do we need to do something to allow downloads from inside an iframe?
Feature to scroll inside the page and lock a view of the page in the iframe.

**Comment by somangshu** [comment]
The use of JS expression after an iFrame has loaded is limited with many restrictions. I think the intended behaviour to have additional functionality on the iFrame content will be difficult. 

Otherwise feature like downloading a file is still going to be handled by the browser and work normally.

**Comment by kamal0808** [comment]
Iframes under lists are not scrolling under edit mode. Is that deliberate or by design?

**Comment by somangshu** [comment]
@kamal0808 can you provide some visual / screen recording on this, Not able to understand what the problem is
