### ISSUE TITLE
[Bug]: On forking template to a child branch of git connected app is throwing Page not found error

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#17262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a template is forked to a child branch of git connected app and changes are not committed , on opening that app again it throws a Page not found error, ideally on opening app it should take user to the home page of master branch, which is how current git connected apps work.
<img width="1439" alt="Screenshot 2022-10-03 at 11 43 40 AM" src="https://user-images.githubusercontent.com/80334441/193512465-132012be-0a93-4cde-9890-ff7fb53a1686.png">

 

### Steps To Reproduce

1. Connect an app to git
2. Switch to child branch 
3. Fork a template from "Start a template card" on canvas and do not commit the changes
4. Go back to home page and open app again
5. Observe it throws Page not found error

It is observed is that although POST `/app-templates/${templateId}/merge/${applicationId}/${organizationId}` which is called for forking the app returns a 200 with the response showing the 3 pages(assuming this template has 3 pages).

`/api/v1/pages?mode=EDIT&applicationId=<application-id>` GET which is used to get the list of pages in the app does not return the newly added pages. 

Also note that when we are initially on master forking the template works fine.
  

### Version

Release

**Comment by akash-codemonk** [comment]
@Parthvi12 This is not a release blocker. This is the same as https://github.com/appsmithorg/appsmith/issues/17234.

**Comment by Parthvi12** [comment]
@akash-codemonk No this is not the same, so once we open the app again it takes us to the master branch even when we were on child branch and changes were not committed but here it is throwing page not found error on opening the app again

**Comment by ginilpg** [comment]
@hiteshjoshi @mohanarpit Could you please check this?

**Comment by Parthvi12** [comment]
@AnaghHegde Still seeing this issue
<img width="1440" alt="Screenshot 2022-10-10 at 10 11 00 AM" src="https://user-images.githubusercontent.com/80334441/194800235-0770a808-8eaf-49ba-a93c-febb862bb89f.png">

**Comment by akash-codemonk** [comment]
@Parthvi12 Does it happen always or did you try https://github.com/appsmithorg/appsmith/issues/17383 which happens without git?

**Comment by Parthvi12** [comment]
@akash-codemonk It's not happening always, this happened when I tried forking only selected pages from templates like in #17383

**Comment by AnaghHegde** [comment]
@Parthvi12 #17383 is still not fixed.

**Comment by Parthvi12** [comment]
Closing this then assuming forking selected pages in child branch is handled in this issue #17383
