### ISSUE TITLE
[Bug]: Forking template from start from template card, gives internal server error and opens template description modal intermittently 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#17275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in cypress tests, on trying to fork template, it shows below screen, causing tests to fail and making it flaky.
https://dashboard.cypress.io/projects/n14p1y/runs/3571/test-results/ffa5cd03-d6cc-45b6-9921-7c3f9091ba73/screenshots
<img width="1440" alt="Screenshot 2022-10-03 at 5 40 31 PM" src="https://user-images.githubusercontent.com/80334441/193573682-bca63156-e6aa-4818-adbb-ea31f96bc024.png">

### Steps To Reproduce
1. Fork a template from Add page popover, for the first time it works, Try forking again it sometimes gives internal server error

Attaching video here: https://dashboard.cypress.io/projects/eyxvp8/analytics/top-failures/c2a34a54-f078-fc17-dc4a-cd90a7b6d361-cc61eaf5-208c-c08a-e5ca-58d943091626

### Version

Release

**Comment by akash-codemonk** [comment]
Seems like the same was reported in https://github.com/appsmithorg/appsmith/issues/17071. It looks like the api randomly fails. We should probably just rerun those tests for now.

**Comment by akash-codemonk** [comment]
Possible scenario where we can repro.
Fork a template from Add page popover, for the first time it works, Try forking again the api sometimes returns internal server error

**Comment by ginilpg** [comment]
> Possible scenario where we can repro. Fork a template from Add page popover, for the first time it works, Try forking again the api sometimes returns internal server error

Tried to reproduce but no luck

**Comment by Parthvi12** [comment]
@ginilpg This is happening quite often on CI, where fork api fails randomly

**Comment by nayan-rafiq** [comment]
@akash-codemonk I've noticed one problem that may possibly lead to this error. When I click on the + icon, the underlying API is called twice. Here is a loom video of this: https://www.loom.com/share/62f4eff338f345c4a081929d896a9591

Also there seems to be another problem, the plus sign is not visible after importing a template once in an application. Here is the problem in action: https://www.loom.com/share/e6221dcec8ac4342afcb1f6b71065800

**Comment by akash-codemonk** [comment]
Have fixed the multiple api calls and the other issue mentioned. It still seems to return 500 on CI. I will have to debug this further on cypress on CI.
