### ISSUE TITLE
[Bug]: On forking selected pages from a template, resource not found error is shown

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#17270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On forking "Response" page of Employee time tracker and "Search" Page of Customer Support Dashboard, resource not found is shown, and user is not directed to forked page, however on hard refresh the redirection happens
<img width="1439" alt="Screenshot 2022-10-03 at 3 39 11 PM" src="https://user-images.githubusercontent.com/80334441/193552815-7ffa29ac-9b85-424c-88aa-25be879b55c6.png">

 

### Steps To Reproduce

1. Click on start from template card
2. Add Search page from Customer Support Dashboard
3. Observe the resource not found error is thrown

### Version

Release

**Comment by Richarex** [comment]
This is also fixed now resource not found error is not coming now. https://www.loom.com/share/25ef55c41809485f93c4faacbd5abbda
