### ISSUE TITLE
[Bug]: Filters for templates are not resetting on re-opening app or opening new app

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#17276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On selecting filters for templates from left pane they remain selected, even when we open some different app. Ideally we should reset it.

### Steps To Reproduce

1. Click on Start from templates card
2. Select any filter from left pane
3. Close the modal
4. Go back to Applications page
5. Open any other app, and click on start from template
6. Observe filters selected from the previous app are showing
This is also observed when we switch to Templates Tab

### Version

Release

**Comment by akash-codemonk** [comment]
It is intended behaviour as of now. We are persisting the same filters set in the templates tab or elsewhere.

**Comment by akash-codemonk** [comment]
cc @kocharrahul7 @RoopKrrish9696
