### ISSUE TITLE
[Bug]: Authenticated API response headers are not displayed

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#17279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user [reported](https://community.appsmith.com/t/do-not-display-headers-in-api-query-return/1482) in the community forum that with the Authenticated API when executed, it does not show the heders. However, the headers are shown in a text widget if we use this code  
` {{apiname.responseMeta.headers}}`we were able to reproduce it in the Appsmith Cloud version.

![imagen](https://user-images.githubusercontent.com/114161539/193613277-ca806886-ca68-4ec6-b401-d7b990e46a72.png)

![imagen](https://user-images.githubusercontent.com/114161539/193613447-37781229-c383-41bf-948d-63fc4489c668.png)

### Steps To Reproduce

1. Generate test responses you can use [webhook.](https://webhook.site/)
2. Generate a test in postman to see if we have heders.
3. In appsmith add a new Authenticated API data source
4. Generate a query and execute it, you will see that you have a response code of ` 200`, but the heders are not displayed.
5. Generate a text widget and type the following command to watch the heders ` {{apiname.responseMeta.headers}}`

### Version

Cloud Appsmith v1.8.4-SNAPSHOT

**Comment by ame-appsmith** [comment]
Here's an additional screenshot from another example where I reproduced this:
![image](https://user-images.githubusercontent.com/101268423/193661075-e14fd1ce-719b-448d-93f2-fc5c92d8ca82.png)

**Comment by prapullac** [comment]
Working as expected in the Local hence moving it to done state
