### ISSUE TITLE
[Epic] SSO for Private Embedded Applications

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#17286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith applications currently need to be signed onto when embedded on other websites. If I want don't want to see sign in page on the embed, I need to share the App publicly or already be logged in.
Instead it would be great if there is a way to let the parent window pass a message with the respective token, etc to the Appsmith embed, and hence automatically being signed onto the App and not requiring to login again.

### Why should this be worked on?

We support Appsmith application as embeds (passing a query param "embed=true" with the url), which many users use on their own web applications.
This additional login spoils the experience of the main website, as users have to do it for Appsmith embeds alone.
At the same time, expecting these applications to be shared publicly could raise other concerns.
If the Appsmith instances are configured with SSO, and if the main website can communicate with the right set of credentials or token, we can get rid of the additional login that is required on the Appsmith embeds.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand I had a call with this user and they are ok with posting the access token to the iFrame but I also read that the token should be shared so long as they are within the same subdomain.

**Comment by tusharmesh** [comment]
do we have a timeline for this ? 
let me know if any inputs are required we have the same use case.

**Comment by infinitetrooper** [comment]
@tusharmesh - We're planning to pick this feature up for development soon. Can you share more details of your use case so we can cover all scenarios? Thank You

**Comment by tusharmesh** [comment]
There are 2 scenarios/ case i would like to have in appsmith:
1) Able to send token in the URL in case of iframe and store that token in appsmith itself so that i can use that token to call my internal APIs
2) In my case we have a login page for our clients and internally we use AUTH0. if posible i wwould like to redirect appsmith to that login page and once successfully logged in it returns auth token and get redirects to appsmith again.

**Comment by infinitetrooper** [comment]
@tusharmesh - Thanks for your feedback.

1. We'll take this into consideration while building the embedded authentication feature.
2. The `Custom Login Support` feature is on our roadmap, we don't have clear timelines yet but, I've added your request to that requirement. I'll be sure to reach out to you when we pick it up and release.

**Comment by infinitetrooper** [comment]
**Project Details - [Notion](https://www.notion.so/appsmith/SSO-for-Embedded-Applications-bc72137ff9754f359bf0c24edfeb087e)**

**Comment by Hyperei** [comment]
I am glad to see this feature is headed into development soon. This is an important part of my use case, as I hope to assign subdomains to each individual app to streamline the end-user experience. Users will go to a subdomain app.example.com and will be presented with a login screen for that specific app. Another user may navigate to app2.example.com to access another app. Using public apps is a non starter as some of these apps must remain authenticated. Thanks for all your great work!

**Comment by infinitetrooper** [comment]
@Hyperei  - Thanks for your feedback. I'd like to understand a little more about your use case, correct me if I've understood this wrongly

1. You will embed each Appsmith app in a specific subdomain of your web app.
2. You will have specific authentication methods for each of those subdomains.

**Queries**

1. In the above flow, are you embedding the app to work as part of your legacy application (or) using them as complete apps?
2. What SSO methods would you want to support for authentication? (SAML, OIDC, Google OAuth, GitHub OAuth)

**Comment by infinitetrooper** [comment]
This feature has been released in Appsmith Business v1.9.8
