### ISSUE TITLE
[Bug]: Save/Discard option is present in the filters option which is causing the table widget to crash.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#17307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Save/Discard option is present in the filters option which is causing the table widget to crash.

https://user-images.githubusercontent.com/109572422/195045841-07da414b-251d-4d3e-b703-7b847ec4a7c0.mov

### Steps To Reproduce

1. D&D a Table widget
2. Enable column(s) to be editable
3. In the filters option, notice that the save/discard option is present. And on clicking on it, the table crashes.

### Version

Cloud

**Comment by dilippitchika** [comment]
@laveena-en the video is missing can you please add?

**Comment by laveena-en** [comment]
@dilippitchika Sorry, my bad. Added it
