### ISSUE TITLE
[Feature]: Support Postgres in addition to MongoDB (or support FerretDB)

### ISSUE THREAD

**Issue by joaocc** [appsmithorg/appsmith#17304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Has anyone considered supporting Postgres in addition to MongoDB for AppSmith DB?
As an alternative, has anyone tried using FerretDB (https://github.com/FerretDB/FerretDB) instead of native MongoDB?

### Why should this be worked on?

In environments where support for Postgres already exists and MongoDB is not being used, offering an alternative would increase the reach and penetration of the project.

**Comment by Nikhil-Nandagopal** [comment]
@joaocc the mongoDB is for appsmith to run effectively and doesn't depend on any existing database you have. The data in your postgres can still be used to build your applications. So I'm unable to reason the value behind this feature as we automatically ship with a mongoDB inside the docker container and maintaining multiple different databases for a project is quite an overhead

**Comment by Nikhil-Nandagopal** [comment]
Do let us know if there's something we missed and why this would be infeasible

**Comment by joaocc** [comment]
Thanks for your quick answer. We are aware that MongoDB is required for AppSmith internal working, and I do understand that from the project point of view, supporting multiple DBs is an extra burden.
From our view, on scenarios where you are a small company and you don't have any workload on MongoDB, adding AppSmith means you will need to acquire skills to manage, maintain and troubleshoot MongoDB. The question on FerretDB (which came about after a quick search on MongoDB-on-Postgres) would allow companies that already have Postgres to use AppSmith without having to introduce yet another database into their supported tools portfolio.
Thx

**Comment by sharat87** [comment]
@joaocc, thanks for sharing more details. You can actually run Appsmith without having delve into details on MongoDB etc. This is the exact reason Appsmith ships as a self-contained Docker image. It runs its own MongoDB and functions off of it, so you don't have to worry about it. Using an external MongoDB is an option, but is not required.

**Comment by joaocc** [comment]
Thanks. We will look into that (we weren't aware it was really self-contained).
