### ISSUE TITLE
[Feature]: Tooltip for date pickers

### ISSUE THREAD

**Issue by charles-bloomfield** [appsmithorg/appsmith#17305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There are tooltips for input text widgets but not for date widgets

### Why should this be worked on?

We have many date fields and we would like to clarify what they mean to our users.

**Comment by ame-appsmith** [comment]
Another user requested a Tooltip for the Select widget: https://community.appsmith.com/t/is-it-possible-to-add-a-tooltip-for-the-select-widget/1507

**Comment by dilippitchika** [comment]
Changes needed
1. Add a new tooltip field in the property pane for datepicker in the general section.
2. Make sure this is the first field here
3. Use the same logic from input widget for showing the tooltip when it's set

**Comment by dilippitchika** [comment]
Fixed in #18097
