### ISSUE TITLE
[Bug]: not able to see the "paginationField":"NEXT" property being sent by the client on release when using table widget pagination. 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#17303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

not able to see the "paginationField":"NEXT" property being sent by the client on release when using table widget pagination. 

### Steps To Reproduce
1. D&D a table widget
2. Add data source - Authenticated API and  Add sample query https://mock-api.appsmith.com/users?pageSize={{Table1.pageSize}}
3. enable server side pagination in the table and bind onPageChange event with the previous API query
4. Click on the next page in the table in the canvas and you can see that next page data is not being called 

Steps via Loom :
https://www.loom.com/share/f9b5d63c16234b85ab1735b12fb6cbfc

Sample App: 
https://release.app.appsmith.com/app/table-pagination-issue/page1-633c15bcc30de528e4cc575b

### Version

Release

**Comment by bharath31** [comment]
@Rishabh-Rathod @satbir121 is this related to https://github.com/appsmithorg/appsmith/issues/17134?

**Comment by Rishabh-Rathod** [comment]
@bharath31 https://theappsmith.slack.com/archives/CTHN8GX5Y/p1665045853036529?thread_ts=1664892198.498239&cid=CTHN8GX5Y 

cc: @arunvjn @satbir121
