### ISSUE TITLE
Leaving and then returning to a page should maintain what api/query was open

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#17348]

**Comment by Richarex** [comment]
- [ ] This is still not maintaining the previous api/query which was open while leaving and returning to page. It is coming back to the canvas. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/thnDzcfT3jRaFPDj

**Comment by ramsaptami** [comment]
LGTM, context position is retained on query and JS editor
