### ISSUE TITLE
[Bug]: In git connected app when user clicks on deploy button the the export event gets added in logs

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the git connected app when the user clicks on the deploy button the export event gets added in the logs

### Steps To Reproduce

1. open a git-connected app 
2. click on deploy button
3. now go to the audit log page
4. validate the latest event displayed

### Version

https://release-audit-logs-test.appsmith.com/app/git-app/page3-633ea2eeedadae4525c9bd66

**Comment by AnaghHegde** [comment]
@RakshaKShetty This will be addressed in the issue - https://github.com/appsmithorg/appsmith/issues/15698
