### ISSUE TITLE
[Bug]: In git connected app when user create a new branch the random events are displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Random events are displayed when the user created new branch in git connect apps
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/194290056-2c38237d-3202-4a69-8305-20ed51050f1c.png">

### Steps To Reproduce

1. go to a git-connected app
2. Create a new branch
3. Now go to the audit logs page
4. check the events displayed
5. The random events are displayed when the user creates a new branch

### Version

https://release-audit-logs-test.appsmith.com/app/git-app/page3-633ea2eeedadae4525c9bd66/edit?branch=newbracnh02

**Comment by AnaghHegde** [comment]
Closing this as we are tracking this in via - https://github.com/appsmithorg/appsmith/issues/15698
