### ISSUE TITLE
[Bug]: Destroy datasource context and connection on deleting datasource

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#17352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, we're not going through the cache and removing the connection entry, or closing any ongoing connection(s) when a datasource is deleted. This can bloat the number of connections that Appsmith creates to an given datasource.

### Steps To Reproduce

1. Create a new datasource
2. Run a query against it
3. Check the database for existing connection
4. Delete the query and datasource on Appsmith
5. Check the database for existing connection. It will still exist

### Version

Cloud

**Comment by btsgh** [comment]
MySQL test - 
Ran show processlist
 This IP started showing up - 103.195.203.87:7053
On deletion of query and DS, the above IP row did not show up.  

PostGreSQL 
select * from pg_stat_activity where usename='postgres' and datname='fakeapi';
 This IP started showing up - 103.195.203.87:7018/7016
On deletion of query and DS, this row did not show up.

**Comment by btsgh** [comment]
Tested this fix and the tests have been updated above .. Closing this issue as fixed.
