### ISSUE TITLE
[Enhancement]: Add placeholder text support for default port in plugins

### ISSUE THREAD

**Issue by vaibh1297** [appsmithorg/appsmith#17357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently when placeholder_text is added for default value of port in plugins then it is also replicated to hosts. Have to fix it so that only port contains the default port value and not host.

### Steps To Reproduce

1. Update placeholder_text for port using its default port number for any plugin.
2. Restart server
3. Go to dev.appsmith.com and check for placeholder text for host and port.

### Version

Cloud / Self Hosted

**Comment by Alcadeus0** [comment]
hi can i work on this issue :

**Comment by pranavkanade** [comment]
@Alcadeus0 Give it a shot

**Comment by sumitsum** [comment]
Closing because this has been fixed.
