### ISSUE TITLE
[Feature]: Save camera app photos with FilePicker

### ISSUE THREAD

**Issue by developer-honoru** [appsmithorg/appsmith#17366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The 3.x version of uppy used in FilePicker can be linked to the camera app when used on mobile.
![Screenshot_20221006_171355_Chrome](https://user-images.githubusercontent.com/33475816/194458166-97146666-05d8-41bd-be8d-ab3c33f7b753.jpg)

https://user-images.githubusercontent.com/33475816/194458227-4a1068d2-442d-4ba9-a2c2-84fe46d00843.mp4

### Why should this be worked on?

The camera photos you are using are not of good quality.

**Comment by dilippitchika** [comment]
@developer-honoru we have fixed the issue with the camera widget. can you check now?

**Comment by developer-honoru** [comment]
thank you @dilippitchika
