### ISSUE TITLE
[Feature]: Code scanner enhancements

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- When working to scan multiple codes 
   - users have to close and open the code scanner frequently to scan items. Instead it could be opened just like the camera widget.
   - users always have to select the camera which they want to use to scan the item, this introduces an extra click.
- Code-scanner should also reverse the camera just like the camera widget.

### Why should this be worked on?

Makes it more convenient to adopt the code scanner for power use-cases

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_571xo)

**Comment by dhruvikn** [comment]
These enhancements should be added in a different version of the widget, i.e. CodeScannerWidgetV2, right? @dilippitchika 

cc: @somangshu, @jsartisan, @sbalaji1192

**Comment by dilippitchika** [comment]
Yes, please do them in a new version

**Comment by somangshu** [comment]
QQ: why do we need to new version for this @dhruvikn @dilippitchika? Seems like no requirement here needs a migration

**Comment by dhruvikn** [comment]
Previously, the CodeScanner widget dropped a button on the canvas. Once the user clicked on that button, a modal opened and scanning started. Now, we want to show the camera feed with the scanner right from the beginning (no button, no modal). This will mean us changing the dimensions of the widget when dropped on the canvas. Also, the properties like button label, tooltip, icon (color, placement etc.) will be removed in the new version. 

These changes are drastically different from what we built in the initial code scanner. What do you suggest would be the best option here? @somangshu 

cc: @jsartisan @sbalaji1192

**Comment by sbalaji1192** [comment]
@dhruvikn @somangshu  We should introduce a new property in the code scanner widget to select the UI the developer prefers. 
Options would be `Always camera on` and `button click to open the scanner`. 
Otherwise, we would need to create a new version so as to not break users' applications.

**Comment by dilippitchika** [comment]
So i had a discussion with @dhruvikn, @sbalaji1192 we will go the direction you suggested. Even we had initially thought of this, it's just an extra property to deal with and manage for a mistake we did hence we choose not to, but until safer migrations are in place it's probably better to avoid users having to go through migrations.

**Comment by sbalaji1192** [comment]
Here actually the migration is not the problem, we are completely changing the UI of the widget which includes the dimensional change as well. Even if we do a safer migration, users will end up with a broken layout as this widget might overlap with other widgets.

**Comment by dilippitchika** [comment]
By safer migration, i mean a v2 where users can click a button and upgrade the widget. It has to be consented from the user as this will lead to a broken layout

**Comment by sbalaji1192** [comment]
Sounds good. We can add this property and make the `click to scan` the default value.
