### ISSUE TITLE
[Feature]: Multi-Line Label for Button Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#17365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Users should be able to display the label of a Button widget on multiple lines.
The Button Group widget allows the label to be wrapped on multiple lines, but it does the wrapping automatically based on the width of the button, and the user is not able to force the line break as desired.

### Why should this be worked on?

This feature would improve the user experience by allowing them to style the buttons to build more attractive apps.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_56mvg)

**Comment by tauantcamargo** [comment]
@dilippitchika can i get it?

**Comment by Nikhil-Nandagopal** [comment]
@tauantcamargo this isn't a good first issue, unfortunately. Please do search for the Good first issue label

**Comment by dilippitchika** [comment]
Not doing this, will be fixed in #8330
