### ISSUE TITLE
[Task]: Add array first element datatype to execute request

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#17384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The action execute request payload should contain the datatype of the first element of an array.
Example
```
{
  "actionId": "62eab32a1f856a6528b3c89b",
  "viewMode": false,
  "paramProperties": {
      "k1": "string",
      "k2": "object",
      "k3": "number",
      "k4": {
        "array": [
          "datatype",
        ]
      },
      "k5": "Boolean"
    }
}
```

**Comment by tauantcamargo** [comment]
can i get it?

**Comment by ChandanBalajiBP** [comment]
Hey @tauantcamargo,
Sorry, this is already fixed(yet to be released).
