### ISSUE TITLE
[Task]: Property Pane rendering re-architecture

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#17387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The hidden property of a property control is being calculated inside [PropertyControl](https://github.com/appsmithorg/appsmith/blob/2aaa413d6dc9468af33e1af468cf77a92fecadb7/app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx#L412) component.

If we ever wanted to see if a property is hidden, it is not directly possible unless we rely on the PropertyControl component.

While implementing the search feature in the property pane, I had to hack around these limitations so that we won't be showing hidden properties. I had to query the DOM to see if the property is hidden and accordingly I had to hide the parent using a state variable. This causes an unwanted re-render which will slow down the property pane in the longer run.

We need to re-architect the way in which we calculate the hidden or any other dynamic configuration values. We should do that before passing the configuration to ProertyControlGenerator.

**Comment by tauantcamargo** [comment]
@riodeuno do u already investigated it request?

**Comment by aswathkk** [comment]
Closing this since we lifted up the hidden property computation into PropertyPaneGenerator on #18164
