### ISSUE TITLE
[Bug]: Post forking an application without the first page the application ends up having pages with page name as the page id

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/67054171/194750905-94bd0186-39e0-4775-ae95-8af86b67e3c4.mov

<img width="613" alt="page-id" src="https://user-images.githubusercontent.com/67054171/194751021-432089db-2e04-46e7-99ae-47b2b32d4818.png">

If you fork a template by selecting pages to fork and if you don't select the first page. The application still ends having all the pages. Also the pages which were not selected seem to have the page name as the page id. We see the page not found error on the frontend when the invalid page(page which has the page name as the page id) ends up being the default page. Also it looks it is being set as the default page automatically post forking on the backend.

The response of GET `api/v1/applications/new` returns the unselected page(Dashboard) in the page list of the application. Also it is set as the default page and you can also see that the page id is the name of the page. Since it is set as the default page it tries to go to that page id on edit, but the page id is clearly invalid. The core issue seems to be the unselected page being added to the forked app.

### Steps To Reproduce

1. Create a new app and open the fork template modal. 
2. Fork the customer support dashboard by unselecting the first page.
3. You see the forked page. 
4. Go to home screen and edit the same app. It goes to a 404 page.

### Version

Cloud

**Comment by AnaghHegde** [comment]
This is not reproducible locally as the metadata about the page is not available in release CS. I will pick this up once this is reproducible locally. 
cc - @ginilpg @akash-codemonk @kocharrahul7

**Comment by akash-codemonk** [comment]
@AnaghHegde Do we know how do we get this metadata or make it available in release CS?

**Comment by AnaghHegde** [comment]
@akash-codemonk I am not aware of the internals here. @nayan-rafiq Could you help us here?

**Comment by AnaghHegde** [comment]
This is fixed via the PR - https://github.com/appsmithorg/appsmith/pull/17292

**Comment by AnaghHegde** [comment]
@Parthvi12 Could you please verify this? I tried selecting the pages

**Comment by Richarex** [comment]
This issue is fixed now verified it on release. Video link:- https://www.loom.com/share/4e10b05c956242daad9e227a35802274
