### ISSUE TITLE
[Feature]: Make the suggested widgets more noticable

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, when users run a query a list of suggested widgets is shown on the right hand pane. The users can select one of the suggested widgets to create that widget on the canvas and connect their query to the selected widget. However, it has been noticed that the users are not selecting the widget from the right hand pane. Instead they go to the canvas and drag and drop the widget. Hence, it would seem that we need to somehow draw the user's attention to the list of suggested widgets, which they seem to be ignoring at the moment. 
Ref: https://theappsmith.slack.com/archives/CGALMH6MT/p1665233735271839?thread_ts=1665152643.364829&cid=CGALMH6MT

### Why should this be worked on?

Better user experience.

**Comment by AnuragThePathak** [comment]
Hello, I was interested in working with this issue but I can't see the slack content you have shared because of not having an appsmith.com email. It could've been great if I get more info on what right hand pane and what search query is being referred to in this context. I can see that widgets can be searched in the left pane and it also shows the search results there only.

**Comment by sumitsum** [comment]
@AnuragThePathak thanks for showing interest in contributing to this issue. However, this issue might not be a good fit since it would need internal discussion and design iterations. I would suggest that you pick up another issue to work on. Please read through this code contribution guidelines before you start: https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md

**Comment by AnuragThePathak** [comment]
@sumitsum I was thinking that modifying styles here https://github.com/appsmithorg/appsmith/blob/12f9a005ae4f90a4678d04232fb5a34c8359cf90/app/client/src/components/editorComponents/GlobalSearch/SearchResults.tsx#L519 will solve the issue. Anyways, thanks for making me aware that it would need internal discussion and design iterations.

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we're making suggested widgets automatic now
