### ISSUE TITLE
[Bug]: Currency selector shows duplicate items

### ISSUE THREAD

**Issue by zhirzh** [appsmithorg/appsmith#17398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dropdown shows duplicate currency options when selecting a country which shares currency symbol with another country

Example: select UK, Jersey, Guernsey, Isle of Man have same currency `GBP`

Also, multiple countries are shown selected when any of "duplicate" currencies is selected

<img width="400" alt="Screenshot 2022-10-09 at 12 13 41 AM" src="https://user-images.githubusercontent.com/8132723/194722822-5c45f17c-9e3c-436b-a70e-234ea36868c1.png">

---

List of duplicates in [`CurrencyTypeOptions` list][1]

```
AUD : Australia, Cocos (Keeling) Islands, Christmas Island, Heard Island and McDonald Islands, Kiribati, Norfolk Island, Nauru, Tuvalu
CHF : Switzerland, Liechtenstein
DKK : Denmark, Faroe Islands, Greenland
EUR : Andorra, Austria, Alland Islands, Belgium, Saint Barthelemy, Cyprus, Germany, Estonia, Spain, Finland, France, French Guiana, Guadeloupe, Greece, Ireland, Italy, Luxembourg, Latvia, Monaco, Montenegro, Saint Martin (French part), Martinique, Malta, Netherlands, Saint Pierre and Miquelon, Portugal, Reunion, Slovenia, Slovakia, San Marino, French Southern Territories, Holy See (Vatican City State), Kosovo, Mayotte
GBP : United Kingdom, Guernsey, South Georgia and the South Sandwich Islands, Isle of Man, Jersey
ILS : Israel, Palestine, State of
MAD : Western Sahara, Morocco
NOK : Bouvet Island, Norway, Svalbard and Jan Mayen
NZD : Cook Islands, Niue, New Zealand, Pitcairn, Tokelau
USD : American Samoa, Ecuador, Micronesia, Federated States of, Guam, British Indian Ocean Territory, Marshall Islands, Northern Mariana Islands, Puerto Rico, Palau, El Salvador, Turks and Caicos Islands, Timor-Leste, United States, British Virgin Islands, US Virgin Islands
XAF : Central African Republic, Congo, Republic of the, Cameroon, Gabon, Equatorial Guinea, Chad
XOF : Burkina Faso, Benin, "Cote dIvoire", Guinea-Bissau, Mali, Niger, Senegal, Togo
```

[1]: https://github.com/appsmithorg/appsmith/blob/ab106455f2906f1a4e7a512c7e3d31f3d0d4695d/app/client/src/constants/Currency.tsx#L12

### Steps To Reproduce

- search currency for any country from duplicates list
- check country names in options 

### Version

cloud

**Comment by somangshu** [comment]
Similar to #22167
