### ISSUE TITLE
[Bug]: Rich Text Editor is buggy

### ISSUE THREAD

**Issue by zhirzh** [appsmithorg/appsmith#17402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

bugs found:
1. text modifiers (bold, italic, underline) remove text color (but background color is fine)
2. no icon for `underline` modifier but keyboard shortcut `Cmd+U` works
3. headings can be inserted in list items
4. text alignment (left, center, right) on list items don't move list marker (bullet, number)
5. text color & background color widgets rendered twice

<img width="1219" alt="Screenshot 2022-10-09 at 12 39 00 AM" src="https://user-images.githubusercontent.com/8132723/194723702-48265838-872f-4bdc-b753-d6d7db5c89f3.png">

### Steps To Reproduce

bug 1
- select text
- apply modifier
- change color

bug 2
- select text
- press `Cmd+U` or `Ctrl+U`

bug 3
- select "paragraph" text
- convert to list
- change block style to any heading

bug 4
- change alignment on list item

bug 5
- check last 2 widgets in toolbar

### Version

cloud

**Comment by dilippitchika** [comment]
These items are from the library, we might not be able to fix these
> headings can be inserted in list items
> text alignment (left, center, right) on list items don't move list marker (bullet, number)


1,2 and 5 we can fix

**Comment by zhirzh** [comment]
got it. can i pick this for ✨ hacktober ✨ ?
