### ISSUE TITLE
[Docs]: Missing documentation for import application from git repository

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#17408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/advanced-concepts/more/backup-restore#import-from-a-git-repository

### Describe the problem

Today, the link mentioned for git repository import is the same as the source page's link. 

### Describe the improvement

Please update the link to the correct page.

**Comment by vuiets** [comment]
Good catch, Trisha. Here's the right link
https://docs.appsmith.com/advanced-concepts/version-control-with-git/import-from-repository

**Comment by danciaclara** [comment]
Fixed it. Closing issue.
