### ISSUE TITLE
[Bug]: Email input allows invalid default value

### ISSUE THREAD

**Issue by zhirzh** [appsmithorg/appsmith#17403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

email input config panel doesn't validate default text

### Steps To Reproduce

- add input widget
- set data type to "email"
- add invalid default text "hello world"
  - no error messages
- deploy
- type something in email input
  - validation triggered
  - error shown

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment]
@zhirzh the default text can be invalid and we expect developers to handle that. The validation only runs for the values input by the end user
