### ISSUE TITLE
[Bug]: numeric input config doesn't report out-of-bound default values as error

### ISSUE THREAD

**Issue by zhirzh** [appsmithorg/appsmith#17404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when default value for numeric input is lower/higher than min/max value, the widget is highlighted (red border) but no errors are reported. in deployed websites, the input is always invalid

<img width="600" alt="Screenshot 2022-10-09 at 1 13 59 AM" src="https://user-images.githubusercontent.com/8132723/194724821-9dc3b72e-8fae-4b5b-8d7d-41b1b9c169eb.png">

### Steps To Reproduce

- add numeric input
- set min, max values
- set default value lower/higher than min/max value
- check bottom error panel & widget error tooltip

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this because the error will be shown on focus as is the UX for all inputs
