### ISSUE TITLE
[Bug]: When a template is imported. The app is reset to old url format. Because, the applicationVersion is reset to 1.

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a template is imported. The app is reset to old url format.
Because, the applicationVersion is reset to 1.

This currently breaks deployed apps.
https://www.loom.com/share/ddfe91bc3a0f402cb6eac0d56b31407d
Workaround: manually update url version (footer has a CTA for this) and re-deploy app.

### Steps To Reproduce

Steps are as shown in the video

### Version

Cloud

**Comment by Richarex** [comment]
@AnaghHegde This issue is partially fixed the deployed part is still failing. Please refer the attached video: https://www.loom.com/share/20af829a03c34672a62f15bb6835a932

**Comment by akash-codemonk** [comment]
When the deployed app is refreshed GET https://release.app.appsmith.com/api/v1/pages?pageId=<page-id>&mode=PUBLISHED returns 
```
{
  "status": 404,
  "success": false,
  "error": {
    "code": 4028,
    "message": "Unable to find page 634ce120d64fb10e109ff0f3. Either the asset doesnt exist or you dont have required permissions",
    "errorType": "INTERNAL_ERROR"
  }
}
```

Redeploying the app works fine, but it is expected that the current deployed version continue to work the same after forking a template and not redeploying. @AnaghHegde

**Comment by akash-codemonk** [comment]
Nope this is without git.

**Comment by AnaghHegde** [comment]
My bad, i misunderstood the issue.

**Comment by Richarex** [comment]
This is fixed now, verified it on release deployed app is loading perfectly fine now. https://www.loom.com/share/77c4da1f456b4a3e9a29a66092bcec11
