### ISSUE TITLE
[Task]: Context switching - Right side panel tabs

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17436]
Panel tabs on the api pane

DP: https://appsmith-a1ra9w73t-get-appsmith.vercel.app/

**Comment by Richarex** [comment]
- [ ] Switching between **Datasources** & **Connections** from api1 to api2 and navigating back to api1 it is not retaining it's previous position. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/qNCfLX6eqmlRl55B

- [ ] Under **Connections** section when we **Add new widget** dropdown in api1 and switching to api2 the same is getting reflected. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/Huv5RLejVsChfuYs

**Comment by akash-codemonk** [comment]
> @akash-codemonk please have a look on these issues
> 
> * [x]  Switching between **Datasources** & **Connections** from api1 to api2 and navigating back to api1 it is not retaining it's previous position. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/qNCfLX6eqmlRl55B

Fixed

> * [ ]  Under **Connections** section when we **Add new widget** dropdown in api1 and switching to api2 the same is getting reflected. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/Huv5RLejVsChfuYs

We are not storing dropdown states, so it is not a bug. We are only storing the tab selections.
