### ISSUE TITLE
[Bug]: Text input disabled style

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#17431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Disabled input component has interactions similar to when it's enabled.
This leads to confusion whether the field is disabled or not.

https://www.loom.com/share/9189d6f2f6a04b56acc7a584a6a0e83a

### Steps To Reproduce

Noticed when developing a feature.
```
<TextInput
          fill
          placeholder="Page URL"
          readOnly
          type="input"
        />
```

### Version

Cloud - 1.8.5

**Comment by tanvibhakta** [comment]
It looks like this is related: https://github.com/appsmithorg/appsmith/issues/17005
