### ISSUE TITLE
[Task]: Context switching - non code editors, we set focus but not cursor

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17435]
Maintain cursor position for inputs.

- Pagination Fields

https://user-images.githubusercontent.com/12022471/199162083-04726785-d3b7-4e81-98c1-764ee47930cc.mov

- Settings inputs

https://user-images.githubusercontent.com/12022471/199162092-dc2197c4-f05c-435c-96e6-4470ed75cf9a.mov

- Switches

https://user-images.githubusercontent.com/12022471/199163886-162c51f6-0c72-484d-bf3d-8ea62d2e1889.mov

- Changing the query type in a dropdown leads to another property being selected when a user changes it, which can be confusing

https://user-images.githubusercontent.com/12022471/199164729-98622607-a48b-4148-833a-76d9c0fdeca1.mov

**Comment by Richarex** [comment]
- [ ] In the datasource edit state when the user tries to edit in the document section then the **EVALUTATED VALUE** & **Documents** section are overlapping with each other. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/7FGIXZ8R0ipqQSui

- [ ] In the datasource edit state on **Settings** page the cursor position is getting maintained, is this expected? Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/MLEowTDLoR4hz7Aq

- [ ] Switching between different types of datasources query in edit state the previous selection from the drop down is not getting maintained. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/mGETm42HzrhWL4lq

- [ ] Even after selecting the commands from the drop down and switching between the datasources edit state the value selected is not maintained. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/ZoiqjsTfBDrFSs87

**Comment by akash-codemonk** [comment]
> * [ ]  In the datasource edit state when the user tries to edit in the document section then the **EVALUTATED VALUE** & **Documents** section are overlapping with each other. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/7FGIXZ8R0ipqQSui

It is a bug but out of scope for context switching. Will not be fixed as part of this issue. 

> * [ ]  In the datasource edit state on **Settings** page the cursor position is getting maintained, is this expected? Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/MLEowTDLoR4hz7Aq

For normal inputs which are not codeeditors it will get focused i.e cursor is visible. The cursor position is actually not maintained try placing it in the middle of the text.  Not a bug.

> * [ ]  Switching between different types of datasources query in edit state the previous selection from the drop down is not getting maintained. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/mGETm42HzrhWL4lq

This looks like a bug on release. It works fine on production. Please create an issue for this.

> * [ ]  Even after selecting the commands from the drop down and switching between the datasources edit state the value selected is not maintained. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/ZoiqjsTfBDrFSs87

This looks like a bug on release. It works fine on production. Please create an issue for this. Same as above.
