### ISSUE TITLE
[Task]: Context switching - Accordions

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17439]
Accordions close and open state need to persisted

DP: https://appsmith-mfua88p5u-get-appsmith.vercel.app/

**Comment by akash-codemonk** [comment]
@Ravina-Deogadkar   Unfortunately, this issue doesn't meet the criteria of what qualifies as a good first issue. 
https://github.com/appsmithorg/appsmith#how-to-contribute has information about how you can contribute. 
https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22 has a good list of issues where you can help contribute.

**Comment by Ravina-Deogadkar** [comment]
Ohh is there anything else I can look at

**Comment by Richarex** [comment]
- [ ] The cursor position is not getting maintained on the edit state of datasource page. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/oYrZVN7737qEQHuD
