### ISSUE TITLE
[Bug]: On clicking a multi-select widget, the app's settings pane does not close.

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#17440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you click on a multi select widget, the app settings pane should close and the widget's property pane should open. But it isn't working.

https://www.loom.com/share/06f896234a0f405bae3d8b1926a9ef99

### Steps To Reproduce

https://www.loom.com/share/06f896234a0f405bae3d8b1926a9ef99

### Version

Cloud

**Comment by dilippitchika** [comment]
@jsartisan it looks like the same issue you are triaging, can you check this out once?

**Comment by dilippitchika** [comment]
Fixed in #17530
