### ISSUE TITLE
[Bug]: Dropdown changes in design system affected performance of modal

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#17452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Recent changes in design system dropdown component affected the re-rendering time of modal widget. This is due to the use of createGlobalStyle functionality of styled component

### Steps To Reproduce

1. Goto performance dashboard
2. Check the PR details tab with [16718](https://github.com/appsmithorg/appsmith/pull/16718)
3. Notice the re-rendering time diff in MODAL_OPEN

### Version

@appsmithorg/design-system-1.0.25

**Comment by shadabbuchh** [comment]
This issue has been verified in release.
