### ISSUE TITLE
[Bug]: Concurrent console logs are not getting logged.

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#17462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Console log is trying to avoid duplication in concurrent logs. Because of this, if we try to log the same object with two different values, only one is displayed in the debugger.

https://user-images.githubusercontent.com/8299030/195007030-019a1e1a-06c6-46ad-9e0d-62ac5f782b65.mov

### Steps To Reproduce

Please refer to the video attached

### Version

cloud

**Comment by bharath31** [comment]
@satbir121 this would need an RCA

**Comment by Druthi** [comment]
@satbir121 I wasn't able to reproduce this. It seems to already be fixed

**Comment by rohan-arthur** [comment]
not reproducible anymore
![Screenshot 2024-08-26 at 14 10 14](https://github.com/user-attachments/assets/487731f3-d84a-4266-8e75-447d5589f243)
