### ISSUE TITLE
[Bug]: Text widget - Font Family on being bound to a radio group, in deploy mode we cannot see the font change

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I bind the Font Family of a text widget to a RadioGroup widget, to select say ubuntu on Y, and rubik on N [ like here -{{RadioGroup5.selectedOptionValue === 'Y'?'ubuntu':'rubik'}}], in edit and preview mode, the font change is seen, but in the deploy mode, the font does not change to either of the above, and remains in a different font. 

### Steps To Reproduce

Drag and drop a text widget
Bind the font family of the text widget to a RadioGroup widget - {{RadioGroup5.selectedOptionValue === 'Y'?'ubuntu':'rubik'}}
In Edit mode, when we choose Y / N .. based on the above binding, the text font changes
In Preview mode also it changes

However, in Deploy mode it does not change.
https://www.loom.com/share/3a827e6b73de49978bdabfa62fc29ea7

Issue is seen only on binding. If I directly choose a font, and deploy, I can see the changed font.

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
It's working
