### ISSUE TITLE
[Docs]: Update the documentation for OIDC Authentication for fetching Refresh Tokens

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#17478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc

### Describe the problem

Access tokens are not refreshed once they expire and there is a need to re-login every time in order to fetch new ones.
This leads to many requests which are valid to be errored out.

### Describe the improvement

As an improvement, superusers need to be educated about using `offline_access` scope, when setting up the OIDC Authentication, when configuring  a Self Hosted Appsmith Instance.

There are different configurations required by different OIDCs (Auth0, Okta, Active Directory, Ping Identity) and need to me mentioned in the Documentation. Also, respective changes needs to be updated in our Documentation, as mentioned below.

OIDC Refresh Token related changes

1. Active Directory
    1. Add additional scope `offline_access` under [Configure Scopes
](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory#configure-scopes)
    2. Add additional scope `offline_access` under [Configure Scopes in Active Directory](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/active-directory#configure-scopes-in-active-directory)
    3. Changes similar to above point in the Video Attached.
2. Okta
    1. Add additional scope `offline_access` under [Configure Scopes for Okta](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta#configure-scopes-for-okta)
    2. Check Refresh Token in [Create Application](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta#create-application)
        `General Settings -> Grant Type -> Client acting on behalf of User -> Check Refresh Token.`
3. Auth0
    1. Add additional scope `offline_access` under [Configuring Scopes for Auth0](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/auth0#configuring-scopes-for-auth0)
4. Ping Identity
    1. Educate Users about Checking the Refresh Token Grant Type in Application configuration as shown in the Image.

Configuration Screen on Ping Identity![Screenshot 2022-10-11 at 2 30 26 PM](https://user-images.githubusercontent.com/20905988/195047484-e3942f2c-2499-4257-a1a3-48e8d60e3037.png)

**Comment by jnikhila** [comment]
@trishaanand - Could you please confirm the priority of this change?

**Comment by nsarupr** [comment]
Hi @spark-c, has there been any updates on this.
If you need further clarification on the OIDCs or anything related to the SSO, please reach out to me on the same.

**Comment by spark-c** [comment]
Update: changes to the text are pretty much complete, now am just gathering media to replace outdated screenshots and video from the various OIDC platforms

**Comment by nsarupr** [comment]
The docs PR: https://github.com/appsmithorg/appsmith-docs/pull/482 fixes this issue.
