### ISSUE TITLE
[Bug]: Getting 'Resource not found' error on deploying template

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#17477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding pages from template and trying to deploy the app, it throws Resource not found error
<img width="1440" alt="Screenshot 2022-10-11 at 2 27 16 PM" src="https://user-images.githubusercontent.com/80334441/195046931-5f8ebbdb-7974-4d5a-bff2-aa655664ddb3.png">

### Steps To Reproduce

1. Click on Start from template card
2. Import 'Customer Support Dashboard' template into app
3. Deploy and observe 'Resource not found' error is thrown

### Version

Release

**Comment by akash-codemonk** [comment]
This most likely will get fixed once https://github.com/appsmithorg/appsmith/issues/17383 gets fixed.

**Comment by AnaghHegde** [comment]
Merged the fix for #17383 via the PR https://github.com/appsmithorg/appsmith/pull/17474. Let's reopen this after verifying the changes on release.
