### ISSUE TITLE
[Task]: MySQL plugin: Add connection pool 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Introduce connection pool mechanism to MySQL plugin.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum when is this going live?

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal apologies, my system had some issues with cypress, hence could not resolve the CI failures earlier. I will be taking help on this and try to push this change into release by early next week.
