### ISSUE TITLE
[Feature]: Improvements to the Table widget for server-side sorting and filtering

### ISSUE THREAD

**Issue by muezz** [appsmithorg/appsmith#17488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The table widget should allow sorting of multiple columns at the same time.

Table widget's UI based filter options should be available in a method like this: `myTable.tableFilters`

### Why should this be worked on?

Almost every database allows sorting over several columns and this is not possible to achieve if I want my user to have this ability. How this could be implemented:

- Add option within the table widget's UI to click over several columns and sort accordingly. A new button would also be required where the user can `reset` the columns back to their initial condition.
- At the moment, if no column is sorted, you get a method `sortOrder` which returns 
```
{
  "column":"desc"
  "order":"release_date"
}
```
- This should be changed to an array where the order of the key-value pairs determines the sort order.
```
[
  {
    "column":"desc"
    "order":"release_date"
  },
  {
    "column":"title"
    "order":"asc"
  }
]
```
- A user can then map this array to the syntax of the database of their choice, use it inside the query and run the it whenever a column is clicked or the reset button is pressed.

In a very similar way, server-side filtering should also be added.

- Currently, there is no way to access the options selected by the user in this "pop up":
![image](https://user-images.githubusercontent.com/100420605/195092775-4de15ce6-e6ad-491e-a552-0ffe3a531773.png)

- A method like `myTable.tableFilters` should be added that looks like this
```
{
  "filter": {
    "and": [
      {
        "field": "title",
        "type": "contains",
        "value": "hello",
      },

      {
        "field": "tagline",
        "type": "contains",
        "value": "world",
      }
    ]
  }
}
```
- A user can the map this object to the syntax of their database's query language and run the query whenever the filter options are changed.

### These two feature would be a great addition to the table widget in my point of view as it would allow a greater deal of functionality for the end user.

Note: I know that this could be implemented, currently, with separate widgets but it would be better if this becomes a built-in feature of the widget.

**Comment by dilippitchika** [comment]
Thanks for raising this @muezz we are going to work on server side filtering soon here - https://github.com/appsmithorg/appsmith/issues/10486

Regarding multi column sorting - here's the issue https://github.com/appsmithorg/appsmith/issues/9949

Please track both of these for updates on the issue. We will work on these soon and server side filtering is something even we have been trying to build.

I will be closing this issue, please let me know if there is some other issue which we need to work on from here.
