### ISSUE TITLE
[Bug]: Google Sheet - Switching between datasources does not fetch the updated list of spread sheets and sheet names

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#17498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Both the data sources show the same list of spreadsheets. Although, the list corresponds to `Design_Data` and not to the `Product_data` datasource.

<img width="1085" alt="Screenshot 2022-10-12 at 10 25 52 AM" src="https://user-images.githubusercontent.com/13262095/195253596-7dedec36-705f-4435-b289-92ac7711e9b9.png">
<img width="1084" alt="Screenshot 2022-10-12 at 10 19 03 AM" src="https://user-images.githubusercontent.com/13262095/195253861-3e6d1355-27e7-4a20-8238-4c74f60e0fcf.png">

### Steps To Reproduce

1. Create two google sheet data sources
2. Create an API
3. When you go on to select the spreadsheet you'll see the list
4. Change the datasource
5. You'll see the same list and not the updated list corresponding to the new datasource

### Version

cloud - v1.8.4

**Comment by prapullac** [comment]
Observed the Internal server error on Authorisation hence moving it into Blocked state

**Comment by prapullac** [comment]
Working as expected on the DP
