### ISSUE TITLE
[Bug]: Unnecessary scroll seen in  2nd step of Welcome tour, when we bind customer data

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#17492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we start welcome tour from home page, and in the 2nd step we are binding {{getCustomers.data}} in Table Data, the helper text is cut and there is an unnecessary scroll to the right.

![image](https://user-images.githubusercontent.com/104895602/195104803-218d700c-1406-46de-9e94-30e7649bd994.png)

### Steps To Reproduce

1. Click on "Welcome tour" in home page
2. Click on "Start building" 
3. Click on "Run" in the first step
4. Click on "Proceed to next step"
5. Click on "Customer Table" under the Widgets column
6. In the property pane of the Customer Table, click on the text box of Table data 
7. Observe the helper text under the text box is but and there is a scroll

### Version

Release

**Comment by akash-codemonk** [comment]
No longer valid.
