### ISSUE TITLE
Oracle DB

### ISSUE THREAD

**Issue by leomangueira** [appsmithorg/appsmith#17497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be amazing if it had the option to connect to oracle database

### Why should this be worked on?

I've been working with oracle for over 4 years, it's a database widely used by large companies and with great resources

**Comment by rohan-arthur** [comment]
@technervs Oracle integration is now available on [cloud](https://app.appsmith.com), and will be included in v1.9.19 if you're self hosting
