### ISSUE TITLE
[Bug]: Older applications on release throw internal server error as soon as it is clicked

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#17494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click any older application on [release.app.appsmith.com](https://release.app.appsmith.com) it throws Internal Server Error provided that the application has some widgets in its `dsl`.

### Steps To Reproduce

1. Go to release.app.appsmith.com
2. Click on any application which has some widgets in its canvas
3. You will notice an Internal Server Error

### Version

Release V1.8.4

**Comment by subrata71** [comment]
Getting this NPE in local after pulling the latest changes from the release branch. 

```
java.lang.NullPointerException: null
	at com.appsmith.server.domains.ActionDependencyEdge.hashCode(ActionDependencyEdge.java:23)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler com.appsmith.server.controllers.PageController#getAllPages(String, String, ApplicationMode, String) [DispatcherHandler]
Original Stack Trace:
		at com.appsmith.server.domains.ActionDependencyEdge.hashCode(ActionDependencyEdge.java:23)
		at java.base/java.util.HashMap.hash(HashMap.java:340)
		at java.base/java.util.HashMap.put(HashMap.java:608)
		at java.base/java.util.HashSet.add(HashSet.java:220)

```

**Comment by btsgh** [comment]
Tested and verified on Release. Applications are working fine now.
