### ISSUE TITLE
[Bug]-[2640]:GSheet - run button gets stuck

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[https://app.appsmith.com/app/robby-s-thesys-workspace/blank-manage-633dc509dca6ec1f8c[…]heets-plugin/api/631b88ec238888080c597081?branch=Development](https://app.appsmith.com/app/robby-s-thesys-workspace/blank-manage-633dc509dca6ec1f8c6e4825/edit/saas/google-sheets-plugin/api/631b88ec238888080c597081?branch=Development)

### Steps To Reproduce

1. Open the app provided above. 
2. A couple of actions would fail on page load. 
3. Click run button on the failed actions. 

### Version

cloud

**Comment by tanishk-23** [comment]
@sumitsum can I work on this issue?

**Comment by sumitsum** [comment]
@tanishk-23 thanks for showing interest in contributing to Appsmith. However, this issue does not seem like a good candidate since this issue is not easily reproducible. I request you to pick up another issue preferably with `Good First Issue` label. Also, please go through our [code contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md) before you start. Happy coding :)

**Comment by sumitsum** [comment]
GSheet 6m usage: 17600
% of users impacted: 15
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2640 |
| Effort (months)  | 0.5 |

**Comment by rohan-arthur** [comment]
closing this as we haven't seen this issue in a while
