### ISSUE TITLE
[Bug]: `Confirm before calling` setting does not work when a JS function is trigged on a button click

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#17500]
A discord user reached out regarding this.
https://cdn.discordapp.com/attachments/1029564855709073440/1029564855943970866/2022_10_12_10_20_35_252.mp4

Steps -
1. create JS object and a function
2. Set it to confirm before calling
3. Run the function from JS Object pane, it shows the confirmation box
4. Trigger it on button click it runs without any prompt

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_597bg)

**Comment by developer-honoru** [comment]
This is the issue I posted
The environment is version v1.8.4 for self-hosting.

**Comment by developer-honoru** [comment]
How is this going?

**Comment by bharath31** [comment]
@developer-honoru apologies for the radio silence here. we'll prioritize a fix for this issue soon.

**Comment by shwetha-ramesh** [comment]
@Druthi Working as expected . Moving to Done.

**Comment by Druthi** [comment]
Moving this card to Product backlog as we've encountered some blockers. We need some product discussion on this. 

Explained the issues here https://www.loom.com/share/ee6786b057824e0890214b0a8bc37800

**Comment by LagunaElectric** [comment]
@Druthi One of our users needs this feature working to prompt their users before taking destructive actions.

https://discord.com/channels/725602949748752515/1151650737118527488

**Comment by satbir121** [comment]
We are going to sunset this feature. It is tracked here: [Sunset Confirm Before calling a function](https://github.com/appsmithorg/appsmith/issues/29248)

**Comment by rishabhrathod01** [comment]
Confirm before calling is deprecated with this change https://github.com/appsmithorg/appsmith/pull/32527. Hence, closing this.
