### ISSUE TITLE
[Task]: Update Omnibar

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#17501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Omnibar uses Gitbook API to trigger the search. Once the documentation is moved to Docusaurus, the API integration should point to the new hosting platform. Please refer to the [slack discussion]([url](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1665071140515489)) for more details.

**Comment by jnikhila** [comment]
@mohanarpit - I've assigned it to you for now.

**Comment by Richarex** [comment]
- [ ] Navigate to this location Displaying Data (Read) > Transforming Data > click on any link under the transforming section
page not found error is displaying is this expected? 
![image](https://user-images.githubusercontent.com/93259714/200542775-3f16f18c-8ac8-4c8d-835e-693f62ab3d88.png)

**Comment by jnikhila** [comment]
@Richarex - The[ links are working](https://www.loom.com/share/1ab51ceccb1b48c7aea54ba73dd44407). Could you please record a loom video and share it?

**Comment by Richarex** [comment]
> @Richarex - The[ links are working](https://www.loom.com/share/1ab51ceccb1b48c7aea54ba73dd44407). Could you please record a loom video and share it?

@jnikhila it started working yesterday they were not working.

**Comment by jnikhila** [comment]
@Richarex - If you face the same issue again, please record a loom video and share.

**Comment by akash-codemonk** [comment]
> @akash-codemonk what are your insights on this
> 
> * [x]  Navigate to this location Displaying Data (Read) > Transforming Data > click on any link under the transforming section
>   page not found error is displaying is this expected?
>   ![image](https://user-images.githubusercontent.com/93259714/200556627-320467ac-f22b-4ca9-b37d-4e5c48c61ebe.png)

Have fixed the link 

> * [ ]  Under **Troubleshooting** section the 5th link **Hint Messages** when we click on the link it takes the user to the github link is it appropriate to show the end user the github link?
>   ![image](https://user-images.githubusercontent.com/93259714/200561877-5a03400a-2551-4dac-9724-41d4a9660ba1.png)

Not a bug in the omnibar as the link works the same on docs site https://docs.appsmith.com/help-and-support/troubleshooting-guide/
@Richarex

**Comment by Richarex** [comment]
This is working fine on release.
