### ISSUE TITLE
[Feature]: Rework actions pane for smaller space

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#17509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Why should this be worked on?

To move the action pane pages to a smaller space when multi-tabs is being introduced.

### Summary

1. Huge design research and compatibility/standards creation
2. Implementation may not take a long time, and it should be 1 layout as much as possible, that would be ideal. The same layout should look good and usable in 1/3, 1/2 and full screen.
3. figure out where to put the evaluated value pane, and how to place it. 
4. API pane/page
5. Query pane/page
    1. Need to go through each and every type of query and plugin
    2. Need to think through different dynamic forms where things can be added/removed like google sheets (filters)
6. JS Object pane/page
    1. Should not be much of a rework

We are tackling this in parts. Can be tracked here: https://github.com/appsmithorg/appsmith/issues/19744

<img width="1102" alt="Screenshot 2022-10-12 at 11 44 50 AM" src="https://user-images.githubusercontent.com/66776129/195301960-954280ac-8fcd-47aa-9c4f-164fefce4f32.png">

**Comment by ginilpg** [comment]
This been tracked here: #19744 hence closing this
