### ISSUE TITLE
[Feature]: New multi pane layout

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#17505]
This task is about the new multi pane layout where each entity can be opened/viewed in tab like view. 

Sub task/things to consider under this task would include the following

- Back button design
  - Remove existing back buttons from action pane(api/datasource/query)
  - How will browser back button behave here
- Sidebar
  - Settings
  - Explorer
  - Datasources
  - Library (discuss with FE coders sooner rather than later)
  - Search (keep it a button, and then make it a panel later)
- Tabs 
- Dynamic property pane
- create action pane
- Performance testing 
- What to show when a user opens an app for the first time
- Onboarding and signposting needs to be considered for the new layout.
- Help is the same as the `?` icon in the editor
- documentation screenshots need to updated, and if required rewording (and probably figure a way of automating for this)

**Comment by rohan-arthur** [comment]
won't fix - project cancelled
