### ISSUE TITLE
[Feature]: Response pane and debugger (reduce context switching)

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#17506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

1. User should not have to move to debugger to decode what is happening
    1. Show the error tab’s error on the response pane itself
    2. Show a collapsed error user can see without navigating
    3. Sniping mode + suggested widget

### Summary
Job stories:

- [ ] When I open the `full page API`, `full page canvas`, or the `split pane layout`, I want my experience to be consistent across all 3, so I don’t have any friction while switching from one layout to the other
- [ ] When I get an error, I want the error to be formatted in the best way possible, so I can easily understand, and debug my application
- [ ] When I navigate across appsmith, I want the debugger tabs to remain consistent, so I can easily understand errors, responses, and results (number and positioning of tabs)
- [ ] When I run a query, api, or JS function (action), I want to have access to the response and errors in an easily accessible way, so I can easily resolve the error without having to navigate on the platform
- [ ] When I open the list of errors, I want to see the list of all errors in a compact way, so I can easily find the relevant errors
- [ ] When I am focussed on an action/pane, I want to see the relevant errors focussed, so I can identify the errors and address them without the noise of all other errors in the app
- [ ] When I am binding data from a query to a widget (or one action to another), I want to see the response of the query as I bind it, so I can easily match the output, and write JS functions like map functions.

Desired outcomes of the project:
- [ ] create a new layout for the debugger which works with the side by side layout
- [ ] Include errors in the response
- [ ] Bring consistency across the debugger across appsmith

### Why should this be worked on?

Reduce the need to switch around when debugging errors.

**Comment by rohan-arthur** [comment]
won't fix - project cancelled
