### ISSUE TITLE
[Feature]: Moving the widget creation CTA off the Entity explorer

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#17511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently the creation of widgets is on the same pane as the entity explorer. We would like to move this off the entity explorer so that the user doesn't have to switch back and fourth between the widgets and the explorer tabs on the entity explorer

### Why should this be worked on?

As a part of context switching, we would like to reduce the number of clicks required for daily activities, this is one such activity which we can get reduced clicks for immediately. We don’t want the user to have to lose the context of the entity explorer while they are dragging and dropping a widget.

Use case in which this is a problem: A user drags and drops a bunch of widgets, and now needs to update a query, they click on the explorer tab and scan through the list of all the queries to find the right one. They have lost context.
In the current entity explorer layout, users will not lose context at all, and in the new layout, the user will retain the tabs. Either way, one of the core job stories was to decouple the entity explorer and the widget list

### Job stories:
1. When I *open the full page API, full page canvas, or the split pane layout*, I want *my experience to be consistent across all 3*, so I *don’t have any friction while switching from one layout to the other*
2. When I *am building an app (form to update data in an application)*, I want to *quickly switch between adding a widget and editing a query, without losing the context of either*, so I can create and edit my query and my canvas without having to reconfigure or change views, and re-adjust/re-learn to what is on my screen
3. When I *create a new app*, I want to *see my widgets in an easily accessible place*, so I can *quickly add my widgets to the canvas without having to look for them behind a click*
4. When I add a widget to my canvas, I want to be able to edit the properties of that widget as soon as I add it, so I can connect my widget to data as soon as I add it rather than having it hidden behind a click 
5. When I build an app on appsmith, I want to have the most commonly used widgets accessible to me asap, so I can quickly build out my basic structure without having to search for the widget
6. When I add a widget to my canvas, I want to be able to add another widget as soon as I add the first, so I can build out my UI in a single flow, rather than having this ability hidden behind a click

### Handoff files:
https://zpl.io/5EM65yr

### Questions and clarifications:

Questions | Answers
-- | --
Will the panel disappear when the user starts to drag? | Yes, the panel will become invisible when the user starts to drag
Will the panel become visible after the widget is dropped? | Yes, The panel will reappear when the user drops a widget.
What will happen if the user drops the widget where the panel is drawn? | The overlay will panel if the widget is dropped where the panel is placed
What are the top 5 widgets?| BUTTON_WIDGET, TABLE_WIDGET_V2, TEXT_WIDGET, INPUT_WIDGET_V2, CONTAINER_WIDGET
What are the escape conditions? | If the user hits escape, or if the user clicks outside the panel, it will disappear
RE: context switching, should we store the open state of the widgets tab? | No, this won't be necessary. The user no longer has to choose between the entity explorer and the canvas.

### Deploy preview
https://appsmith-brueyk12q-get-appsmith.vercel.app/

**Comment by akash-codemonk** [comment]
Tasks
- [ ] Remove explorer/widgets tab view from the explorer.
- [ ] Add widget panel cta on top of the canvas.
- [ ] Hide widget panel if the previously dropped widget/cursor position overlaps with the area of the widget panel
- [ ] Add a way to use commonly used widgets
- [ ] Update both the onboarding to use the new widget pane
- [ ] Cypress tests

**Comment by kocharrahul7** [comment]
We are not going forward with this for now. A new issue will be opened for this in the future
