### ISSUE TITLE
[Bug]: On importing template, JSObjects are not getting imported in git connected apps

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#17526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app is connected to git, and we try to import template JSObjects are not getting imported , this is being observed in this app https://release.app.appsmith.com/app/git-template-3-foodtruck/page-6329b3049d80cd6ff89749d9?branch=master
<img width="1440" alt="Screenshot 2022-10-12 at 11 01 40 PM" src="https://user-images.githubusercontent.com/80334441/195410002-6b6d5047-02e2-4062-8054-11cc783d4371.png">

### Steps To Reproduce

1. Connect an app to git
2. Try importing 'Customer support dashboard'
3. Observe JSObject 'Utils' is not imported 

Note: This is not reproducible always.

### Public Sample App

https://release.app.appsmith.com/app/git-template-3-foodtruck/page-6329b3049d80cd6ff89749d9?branch=master

### Version

Release

**Comment by akash-codemonk** [comment]
Tried with an app which was 7 months old was unable to repro.

**Comment by infinitetrooper** [comment]
Stale - closing this.
