### ISSUE TITLE
[Bug]: The UI & UX issue in Audit logs

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [x] .Replace the placeholder text "Select" in date filter with "All"
- [ ] The enter doesn't work inside Resource ID placeholder
- [x] "Select" Should not be an option to select in the Date filter
- [x] The hand icon should not be displayed event and user column names as it is not a clickable event
- [x] The clear all button should not be displayed when the user rearranges the date from the date column
- [x] In the Page edit event, we need to capture both old page name and the new page name
- [x] when authentication method is added The event name should be displayed as "{{authenticationMode}} authentication configured"

### Steps To Reproduce

1. Login as admin user
2. CLick on Admin setting menu
3. Clik on Audit log menu 
4. Check for above Ui and UX issues

### Version

https://release-ee.appsmith.com/settings/audit-logs

**Comment by vishnu-gp** [comment]
@RakshaKShetty Do we really need the old page name as well for page.updated? It's a little tricky to get that from BE and I don't see it in the PRD too.

**Comment by IAmAnubhavSaini** [comment]
- [ ] .Replace the placeholder text "Select" in date filter with "All"
- [ ] "Select" Should not be an option to select in the Date filter
These have been fixed as date range filter component has replaced dropdown.

- [ ] The clear all button should not be displayed when the user rearranges the date from the date column
This is not an issue.

- [ ] In the Page edit event, we need to capture both old page name and the new page name
Not sure if this is possible.

- [ ] when authentication method is added The event name should be displayed as "{{authenticationMode}} authentication configured"
This is incorrect.

- [ ] The enter doesn't work inside Resource ID placeholder
- [ ] The hand icon should not be displayed event and user column names as it is not a clickable event
PR: https://github.com/appsmithorg/appsmith-ee/pull/695
