### ISSUE TITLE
[Bug] Table Image doesn't scale on expanding row size

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1753]
## Description

When we increase the row size of the table, the image size doesn't scale. Ideally, the image should also get bigger based on the row size.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create a table and populate it with data that has an image URL
2. Increase the row size of the table
3. The size of the image remains the same

### Important Details
 - Version: Cloud / Self-Hosted
 - OS: e.g.MacOSX
 - Browser: Firefox

![unknown](https://user-images.githubusercontent.com/458946/99374447-97d87080-28e8-11eb-805b-57c7f50eb958.png)

**Comment by Nikhil-Nandagopal** [comment]
To clarify, this should be a property of the image widget whether to center, fit or repeat it's image

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal But this is not an image widget inside the table. It's just a property of the column. Ideally, the size of the image inside the cell should increase & decrease according to the row height.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit sorry my bad the image confused me with an image widget. Missed that it's inside the table

**Comment by prapullac** [comment]
Reopening the issue as the image does not get expanded on expanding the row size
