### ISSUE TITLE
[Bug]: The User name is displayed instead of user email when the user logs in with GitHub auth

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The User name is displayed instead of user email when the user logs in with GitHub auth
![image](https://user-images.githubusercontent.com/45958978/195609867-1b60c6f2-ad06-4596-afb5-78a79e334a95.png)

### Steps To Reproduce

1. Login to the app with the github auth
2. Now login as a Admin user
3. Go to admin setting page
4. click on Audit log
5. Filter by user login event
6. Check the user email displayed when user logged in with github auth
7. The user name is displayed istead of email

### Version

Localhost

**Comment by riteshkew** [comment]
Limitation of the implementation. Github doesn't send email as part of the response, so this is as expected.
