### ISSUE TITLE
[Task]: Remove oldest grays in the design system 

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#17545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Remove the following css variables from the design system:

    old-gray-10
    old-blue-gray
    old-outer-space
    old-dove-gray
    old-mid-gray
    old-alto
    old-mercury
    old-dove-gray-2
    old-silver
    old-dove-gray-3
    old-black-pearl
    old-alto-opacity-50
    old-white-opacity-50

**Comment by abhijain2003** [comment]
hey can you assign this to me

**Comment by tanvibhakta** [comment]
Hey @abhijain2003, this is an issue for something I'm working on right now. If you'd like to work on some issues for Hacktoberfest, please look at the issues we've marked as [good first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) to start with. Have a good day!
