### ISSUE TITLE
[Bug]:UI Inconsistencies in  Repo Limit modal 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user reaches the repo limit the repo name along with the  No of users sharing the repo should be displayed instead of repo url
 ![image](https://user-images.githubusercontent.com/45958978/195770555-493085c3-92a7-4d31-92c3-4cfc15aa3660.png)

### Steps To Reproduce

1. Pick the workspace where already 3 git-connected apps are present
2. Make sure all the git connected apps are connected to private repo
3. Now try to connect new app to git
4. When user to try to connect the new app to a new private repo 
5. The Repo limit pop up will be displayed
6. now check the details of repo limit
7. The repo name and Repo url is displayed instead of repo name and user count

### Version

release

**Comment by AnaghHegde** [comment]
@ankitsrivas14 IIRC, this is fixed. I remember you were working on this.
