### ISSUE TITLE
[Bug]: Welcome tour table widget V1 show old property pane.

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#17560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Welcome tour, table widget v1 is used that show the old property pane. Drag & Drop table widget, new property is shown
CustomerTable Property Pane
![Screenshot 2022-10-14 at 1 19 20 PM](https://user-images.githubusercontent.com/890915/195792112-ea8a84e0-4885-4b5c-8499-336e13de28bb.png)

Drag & Dropped Table Widget Pane
![Screenshot 2022-10-14 at 1 20 09 PM](https://user-images.githubusercontent.com/890915/195792262-b4d83d6e-f9bc-48c8-9d97-5666399955a2.png)

### Steps To Reproduce

https://www.loom.com/share/a4ccfd5fed794075bab8fd34b216ce51

### Version

Cloud

**Comment by Richarex** [comment]
Working fine verified it on the DP url:- https://appsmith-hdaizbe7o-get-appsmith.vercel.app/
![image](https://user-images.githubusercontent.com/93259714/206956494-33ef12eb-85a0-4a10-9552-d2fe941105cf.png)

**Comment by rohitagarwal88** [comment]
@ginilpg / @kocharrahul7 : Any ETA on it. We are using old table widget here.

**Comment by kocharrahul7** [comment]
@rohitagarwal88 Should be in prod with the next promotion

**Comment by rohitagarwal88** [comment]
Awesome thanks @kocharrahul7
