### ISSUE TITLE
[Task]: Instrumentation for Entity Refactor based on AST

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#17564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

For every refactor that happens, capture the following data :

- Application ID
- User ID
- What is the type of entity that is being refactored - plugin, query, JS Object etc.
- How many matching references were found with that name
- How many references did we end up renaming from 4
- Was the renaming successful or not

**Comment by nidhi-nair** [comment]
Ref Slack: https://theappsmith.slack.com/archives/C0423TJFUJK/p1665742898881359
