### ISSUE TITLE
[Feature] Nested Tree Selector Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1759]
# RACI matrix
| Label | Value | 
| ------------- | ------------- |
| Responsible |  @momcilo-appsmith |
| Accountable | @somangshu  |
| Consulted |  |
| Informed |  @Nikhil-Nandagopal |

# Objective

We need a tree selector widget that allows users to select single and multiple values from a list of options.

> TreeSelect is similar to Select, but the values are provided in a tree like structure. Any data whose entries are defined in a hierarchical manner is fit to use this control. Examples of such case may include a corporate hierarchy, a directory structure, and so on.

# Success Metrics

| Goal  | Metric |
| ------------- | ------------- |
| New widget  | Increase use case coverage |
| Nested objects  | ability to handle nested objects inside Appsmith |

# Requirements

| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Type | Weather to allow single or multiple selection | High | - |
| During single select show radio as a selection | When the dev chooses single select mode the user will be able to see radio buttons with the options since only one option can be selected | Medium  | - |
| During multiple select show checkbox as a selection | When the dev chooses multi select mode the user will be able to see checkbox buttons with the options since many option can be selected | Medium  | - |
| Options / Tree Data  | contain nested collection of Tree select children `{"label": "", "value": "", "children": [{}]}` | High  | - |
| isVisible |  Dev can set this attributes to show/hide with toggle or even a JS expression (JS convertible)  | High  | - |
| isDisabled | Dev can set this attributes to disable the widget with toggle or even a JS expression (JS convertible) | High | - |
| Action - `onChange` | API to trigger an action on change or se[de]lection of a option | High  | - |
| allowClear | Whether allow clear : boolean | High  | - |
| maxTagCount | Internally fixed to responsive, Tags will cover the space give and then show `+2 more` | High  | - |
| Placeholder | Placeholder of the tree input | Medium | - |
| Internal property: value | Get all selected values (Array is multiple); string : string[] | High | - |
| treeDefaultExpandAll | Whether to expand all treeNodes by default | Low | - | 
| Default Options | The dev can use this prop to set the default values which will be selected when the widget is loaded. The type for this field is `<array>` and we will do a deep search in the main object | High | - | 

# Questions:

| Question   | Answer |
| ------------- | ------------- |
| Imagine there is a parent item in a multiselect mode that has 2 child items. What if the user selects the parent item and one child item? Do we show both of them in the input or just the parent one |  |

# Developer Handoff Document in Figma:
[V1](https://www.figma.com/file/hsHKmSVcoQVKOoTXOIs7rQ/?node-id=136%3A1527) (changes required here)

[Final Design](https://www.figma.com/file/1HLLnIw4Fudx8EpgouaEDU/TreeSelect-Widget-Tue-20-July?node-id=2%3A1)

**Comment by Debsourabh** [comment]
PFA the Draft Designs for Nested Tree Widget

https://www.figma.com/file/hsHKmSVcoQVKOoTXOIs7rQ/New-Widgets?node-id=73%3A2

Points to note : 
1. These are draft designs and are not final.
2. `options: OptionTree` from the requirement wasn't clear. Still pending in the designs
3. W.r.t to the property pane there is some more fine tuning left to be addressed. 

Will update the same link with final when done.

**Comment by Debsourabh** [comment]
Here the Final Designs for Nested Widget

https://www.figma.com/file/hsHKmSVcoQVKOoTXOIs7rQ/?node-id=136%3A1527

Changes made :

1.Added a boolean value for making the fields checkable. 
2. Has some widget UI optimization w.r.t to handeling edge cases for dropdowns.

**Comment by momcilo-appsmith** [comment]
@nikhil @somangshu I added a question to the table, please check it out and let me know what do you think.

**Comment by Nikhil-Nandagopal** [comment]
@momcilo-appsmith as per how ant design work, there are 2 modes for multi-select. One where the parent is selectable as a node and one where selecting the parent is only a shortcut to selecting all children under it.
In the former the parent should show, in the later only the children should

**Comment by somangshu** [comment]
Also logically speaking, Is the parent node is selected, all children are counted and hence only the parent node should show up. Otherwise show only the selected children.

**Comment by Tooluloope** [comment]
@Debsourabh Which of the icons should be used?
<img width="273" alt="Screenshot 2021-07-19 at 13 37 17" src="https://user-images.githubusercontent.com/31691737/126160854-ad22f1e5-c711-4d3a-895b-a009df002706.png">

**Comment by somangshu** [comment]
@Tooluloope please wait a while, @momcilo-appsmith is going to attach the new designs according to the requirement changes. The widget icon will also be provided there.

**Comment by momcilo-appsmith** [comment]
@somangshu I just added the developer handoff file

**Comment by Tooluloope** [comment]
@momcilo-appsmith Was default value intentionally Omitted from the property pane?

Also, I noticed the Tooltip in the property pane is that applicable and if yes, I didn't see designs for that.

Lastly, is the orange color the hover state for the tree select as well as the checkboxes/ radio buttons?

@somangshu how many levels deep can we get a nested option?

**Comment by momcilo-appsmith** [comment]
@somangshu @Nikhil-Nandagopal the default option was not in the requirements, should we add it?

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope @momcilo-appsmith there should be a default value

**Comment by somangshu** [comment]
My Bad, I missed the requirement, Have added it here as well. @Tooluloope we need to implement this.

**Comment by Tooluloope** [comment]
@momcilo-appsmith @somangshu 
As agreed,  Tree select would have two separate widgets for Single and Multiselect. 

@momcilo-appsmith would you add the icon for both of these to the figma design

**Comment by momcilo-appsmith** [comment]
@Tooluloope Here they are: https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=2368%3A11993
