### ISSUE TITLE
[Feature]: In table widget have separate (customizable..) color for selected row and highlighted row.

### ISSUE THREAD

**Issue by nzidol** [appsmithorg/appsmith#17597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When moving the mouse across the table the row under the cursor is highlighted. When selecting a row the same color is used to indicate the selected row. Users can get confused when clicking twice on a row, the row still shows in highlighted color but dependent widgets are empty. Only when moving the cursor does it become clear no row is selected.

Test:
1 create page with table and Js-form 
2. set js-form source data to {{Table1.selectedrow}}.
3. Click a row in the table and click again.
4. Click a row and move cursor to different row

### Why should this be worked on?

Make it clear to users which is the selected row and which is the highlighted row.

**Comment by dilippitchika** [comment]
@nzidol we have fixed in https://github.com/appsmithorg/appsmith/issues/10995 - This should be available next week. Closing the issue for now, please let me know if you wish to reopen
