### ISSUE TITLE
[Feature] Switch Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1760]
## Summary

Users want a switch widget as an alternative to the checkbox widget due to the aesthetic appeal

## Additional Context

The switch widget will contain the following properties

label: string
isSelected: boolean
isVisible: boolean
isDisabled: boolean
isRequired: boolean
onSelectionChange:ActionSelector

https://www.figma.com/file/moGQyQffFfyUhHUMO9xqn3/Appsmith-v1.0-Final?node-id=1768%3A5093

**Comment by marks0351** [comment]
@Nikhil-Nandagopal  Can we have 'isToggledOn' or 'isSwitchedOn' instead of 'isSelected', 'onChange' instead of 'onSelectionChange'?

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 Yes makes sense 👍
