### ISSUE TITLE
[Bug]: The POST API of nocodb is not working properly in appsmith .

### ISSUE THREAD

**Issue by etherral17** [appsmithorg/appsmith#17602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I tried to run the nocodb's POST API in appsmith , I get a row of null values instead of the option to fill those values of the row .
![image](https://user-images.githubusercontent.com/17555725/196097984-8105357f-f1b1-4f9d-966c-60aac44ca893.png)

I need to change these values and update in the nocodb's database server running within the container.

### Steps To Reproduce

1.Go to nocodb and copy the POST URL into the POST API section of appsmith. 
2. We expect that it should run and give us values to be changed instead it provides us with null values and adds into the dataset in nocodb .

### Version

Docker container

**Comment by Nikhil-Nandagopal** [comment]
@etherral17 their post API expects the row to be inserted in the body field of the API. You can configure this under the tab named 'Body' in the screenshot you sent
