### ISSUE TITLE
[Bug]: can't remove user - internal server error

### ISSUE THREAD

**Issue by alinaepanaite** [appsmithorg/appsmith#17606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i want to remove a user from my app, i get an internal server error. 

### Steps To Reproduce

1. go to apps
2. go to member
3. select "delete' icon on member's line
4. get error
![Screenshot 2022-10-17 at 10 05 33](https://user-images.githubusercontent.com/115975936/196111067-1fc38f3c-1394-4750-a1bc-574d97517338.png)
 

### Version

Appsmith v1.8.5-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5w958)

**Comment by Nikhil-Nandagopal** [comment]
@alinaepanaite after you refresh the page is the member still not deleted? How many users do you have in the workspace?

**Comment by pranavkanade** [comment]
@alinaepanaite, are you using Appsmith on a self-hosted instance or Appsmith Cloud? If it's a self-hosted instance, can you please provide us the backend logs? You can find them in `/stacks/logs/backend/backend.log`

**Comment by alinaepanaite** [comment]
> 

no...i have been trying for a week now to delete the user. and i get the same error since.

**Comment by alinaepanaite** [comment]
> here you go. thank you. 

https://user-images.githubusercontent.com/115975936/196279433-9d97ade3-2286-40e0-be0c-0e71c51f5af9.mov

**Comment by danciaclara** [comment]
Another user who is facing this issue https://discord.com/channels/725602949748752515/1042141778297503785/1042141778297503785

**Comment by vuiets** [comment]
Cause and workaround for this added by @trishaanand in https://github.com/appsmithorg/appsmith/issues/17235#issuecomment-1284957402. Quoting it verbatim
> This issue is being seen only on Enterprise Edition. Only the Developers and the App Viewers are currently not able to leave a workspace which has been created over the last two weeks. The out right for such workspaces would be to request an administrator of such workspaces to remove the member from the workspace from `Manage members` page.

**Comment by pranayagarwal96** [comment]
@trishaanand @vuiets, on the above issue which Dancia shared, the user actually is on the cloud edition and is facing an error removing members even as an admin
