### ISSUE TITLE
[Bug]: The tooltip for the orange deviation dot in property pane is moving out of the screen

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#17604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the property name is a little long and the user has selected a value that is different from the theme, the deviated form theme orange dot appears. When hovering over it, the tooltip overflows from the screen.

![image](https://user-images.githubusercontent.com/22471214/196105166-4185d716-02f7-4e82-b681-3fcc4b2750a7.png)

### Steps To Reproduce

1. Open release.app.appsmith.com / create a fresh FE build from release.
2. DnD a text widget.
3. Change the text of the text widget to something lengthy like - 
> Lorem ipsum, in graphical and textual context, refers to filler text that is placed in a document or visual presentation. Lorem ipsum is derived from the Latin "dolorem ipsum" roughly translated as "pain itself".
4. Select **Overflow Text** in the property pane to **Truncate text**
5. Go to the style property pane and select any color in the "Truncate button color".
6. Hover over the orange dot and observe the tooltip overflowing.

https://user-images.githubusercontent.com/22471214/196107193-0fab95c9-9349-4d15-a131-0d44426adca4.mp4

### Version

Appsmith Release - Appsmith v1.8.5-SNAPSHOT

**Comment by iSatVeerSingh** [comment]
Is this issue still need to be resolved? Please let me know.

**Comment by iSatVeerSingh** [comment]
@dhruvikn @Nikhil-Nandagopal Please assign me.

**Comment by iSatVeerSingh** [comment]
@dhruvikn here is the PR https://github.com/appsmithorg/appsmith/pull/21992

**Comment by iSatVeerSingh** [comment]
@dhruvikn Please also check this another PR https://github.com/appsmithorg/appsmith/pull/21989 for issue https://github.com/appsmithorg/appsmith/issues/21368
