### ISSUE TITLE
[Bug]: Autosave failing for large JSObjects

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#17619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

To quote the user
"I have a massive issue here, I was editing JSObject in my app and while I was editing I constantly meet performance issues on the editor. The autosave feature keeps having issues and it takes so long to save. Sometimes it outright crashes or resets my codes to the previous save state. I kept using it anyway but a few moments later this happens: The entire server went down with it.
Please let me know what I can do to avoid it, I think we had the exact same issue before and we couldn't locate the issue, Our server went down multiple times before."

Server being used : AWS EC2 t3a.medium

More context can be found here, along with the logs : https://theappsmith.slack.com/archives/C0385FH70E8/p1665567331103289 

### Steps To Reproduce

1. Go to JSObject editor and try to edit a large JSObject
2. Make quick updates to query references and the autosave slows down.

### Public Sample App
App JSON : https://theappsmith.slack.com/archives/C0385FH70E8/p1665637419736139?thread_ts=1665567331.103289&cid=C0385FH70E8

_No response_

### Version

1.8.3

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5bg98)

**Comment by AnaghHegde** [comment]
Another user faced this issue and they are unable to use the Appsmith because of that. Slack thread - https://theappsmith.slack.com/archives/C0341RERY4R/p1666028336159649

**Comment by subrata71** [comment]
[RCA on Notion](https://www.notion.so/appsmith/RCA-Internal-Server-Error-while-Editing-Large-JS-object-88017c9245dd4a6a9f9237eddec6f82c)

**Comment by btsgh** [comment]
Auto save for large JS objects is no longer causing internal server errors. In some scenarios, it was observed, though it was not as frequent as it was before. This is as per dev's intended fix. Fixing it entirely would require larger changes and more time - Refer - "https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1668683912793319"

cc: @ramsaptami @subrata71
