### ISSUE TITLE
[Bug]: While running a create Query in the appsmith using postgres database , it shows "Execution failed with status 5005 ". Can someone pour some light about the issue here .

### ISSUE THREAD

**Issue by etherral17** [appsmithorg/appsmith#17610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Normally when I have connected other databases like mongodb atlas and even nocodb , I have observed that it has ran successfully . Now with the postgres database only it is showing error 5005 
![image](https://user-images.githubusercontent.com/17555725/196118515-fa813dfc-d9d1-48b0-89e6-bf01ba704d71.png)

Please look into this .

### Steps To Reproduce

1. Create a postgres database using docker and input some values and table into the database named of your choice .
2. Run queries in the psql prompt just  to check if its working and the tables are created or not .
3. Now connect the database to appsmith using the plus icon in database section on the left sidebar 
4. Once the database is connected , test it .If its successful then got the next step .
5. Go to Add queries section and then write your create query .
6. You will find that it shows an Execution error with status 5005 .

### Version

Ran inside docker .

**Comment by Nikhil-Nandagopal** [comment]
@etherral17 it's likely that the amount of data in your database is too large to load in a single query. Could you try by adding a limit to your query and paginating your data?
https://docs.appsmith.com/core-concepts/data-access-and-binding/displaying-data-read/display-data-tables#pagination

**Comment by etherral17** [comment]
@Nikhil-Nandagopal  Hey nikhil , I have freshly prepared that postgres database and has only 3 tables with few data points. I would need some points where you require more info . Can it be that I am using free docker version of appsmith , thats why the problem exists ? 
![image](https://user-images.githubusercontent.com/17555725/196131225-d4964511-d11b-4feb-8bbb-dda95eefcfe0.png)
You can see in this image that there is only two data points in this table "author" . Please help me as I am a fresher and this is my second issue post . So please feel free to guide me .

**Comment by Nikhil-Nandagopal** [comment]
@etherral17 it's then likely that you connection is not configured correctly/. Can you go to the datasource and try to hit the test button? Maybe a value in the connection is incorrect

**Comment by etherral17** [comment]
it got solved by recreating the database , a fairly simple solution delete the database and its metadata and recreate it .
