### ISSUE TITLE
[Bug]: Input widget is not reset even after closing and reopening the modal

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#17611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/87be9dac1a3b463a9d06cc2637ade1e0

The input widget doesn't reset automatically even after closing and reopening the modal

### Steps To Reproduce

1. Create a modal with input widget
2. Add value to input widget
3. Close and reopen, you'll see the persisted value.

### Version

v1.8.4

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5bdl8)

**Comment by somangshu** [comment]
If we set the onClose event of the modal to reset the child widget, the above requirement is fulfilled. 
Closing this issue
