### ISSUE TITLE
[Docs]: Global Functions Doc Missing Heading

### ISSUE THREAD

**Issue by SarojWasti** [appsmithorg/appsmith#17629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/GlobalFunctions.md

### Describe the problem

Unlike other, GlobalFunctions.md doesn't have a heading at all which could be improved.

### Describe the improvement

Adding `# Global Functions Doc` as heading for GlobalFunctions.md should improve the documentation.

**Comment by danciaclara** [comment]
@somangshu  Can you help us direct this to who would be the best person to add relevant info regarding this

**Comment by somangshu** [comment]
I think @rimildeyjsr can help us here
