### ISSUE TITLE
[Bug]: HTML tags are being shown in description field

### ISSUE THREAD

**Issue by shockdav** [appsmithorg/appsmith#17620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

HTML tags are being shown in the description field after I upgraded my appsmith version from v1.7.0 to v1.8.4.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/16309142/196166401-b0fa09cc-d580-4421-acc8-ee162d3d76a2.png)
![image](https://user-images.githubusercontent.com/16309142/196166429-642973c7-7e4f-46da-84da-67b5228bec01.png)

and our frontend is also showing the HTML tags which come from the Appsmith.

![image](https://user-images.githubusercontent.com/16309142/196166581-ede97544-1c14-4838-8fad-48b0217d1660.png)

### Version

Self Hosted - 1.8.4

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika was something changed in the table or the RICH text editor? I believe the Rich Text Editor always generated HTML content

**Comment by dilippitchika** [comment]
@Nikhil-Nandagopal previously there was a bug in RTE which is described here - https://github.com/appsmithorg/appsmith/issues/7231

We fixed this by upgrading the library and it introduced a default tag in the RTE. But RTE always outputs a html type field, so this problem should not have occured. CC @keyurparalkar 

@shockdav if you only want to allow a text input without any html then i suggest you use the text input and increase it's height.

**Comment by dilippitchika** [comment]
In the older version as well, if the end user presses shift+enter we add `<p>` tags everywhere. The change in #7231 fixed it to make the RTE consistent and always provide a html. We never expected it to work without html tags.
