### ISSUE TITLE
[Bug]: Bad UI in Toast message on dismissing tutorial

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#17641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The UI for the toast message seems to be broken when we dismiss the tutorial for a freshly signed up user on `https://release-ee.appsmith.com`.

<img width="1920" alt="Screenshot 2022-10-18 at 12 10 54 PM" src="https://user-images.githubusercontent.com/39921438/196356736-16b44139-ba16-4b45-adef-1a180f2e64b5.png">

### Steps To Reproduce

1. Sign up on `https://release-ee.appsmith.com`.
2. Open app > dismiss tutorial modal > in left panel, on the top.

### Version

Cloud

**Comment by tanishk-23** [comment]
@shadabbuchh can I work on this issue?

**Comment by rohitagarwal88** [comment]
Sry, @tanishk-23 this issue is a release blocker & picked up internally. 
You can explore other issues.

**Comment by tanvibhakta** [comment]
This issue was not able to be reproduced anywhere outside of this environment. It has not showed up in production.
