### ISSUE TITLE
[Bug] Appsmith install script on EC2 errors out

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1764]
## Description

When install appsmith using the `install.sh` script, the script errors out with the following message:
```
+++++++++++ ERROR ++++++++++++++++++++++
Appsmith requires ports 80 & 443 to be open. Please shut down any other service(s) that may be running on these ports.
++++++++++++++++++++++++++++++++++++++++
```

- No other services can be found to be running on these ports.

**Comment by Nikhil-Nandagopal** [comment]
Closing since it looks like it was resolved on discord

**Comment by harshit98** [comment]
**Solution**: Ports 80 and 443 must be added to security group of EC2 instance. This way I fixed my issue.
