### ISSUE TITLE
[Bug]-[128000]:The vertical scroll bar  is missing in the response tab for database queries

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The vertical scroll bar  is missing in the response tab for database queries
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/196385974-9af5249b-cf43-4941-92aa-4ea7cb264025.png">

### Steps To Reproduce

1. Add a Mock database users
2. Now run the select query
3. Now in response tab
4. Check the data try to do a vertical scroll the scroll doesn't work so its hard to see the data

### Public Sample App
https://release-ee.appsmith.com/app/release-oct-18/pagename-mysql-634e48963bb2695959262747/edit/queries/634e5e083bb2695959262a60?branch=raksha
### Version

release

**Comment by RakshaKShetty** [comment]
Facing this issue in specific query

**Comment by rohan-arthur** [comment]
this affects all users, therefore reach = 32,000

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 32000 |
| Effort (months)  | 0.25 |

**Comment by btsgh** [comment]
Tested and found to be fixed
