### ISSUE TITLE
[Feature] Possibility to have embeddable link without the navigation bar of Appsmith?

### ISSUE THREAD

**Issue by Simone-cogno** [appsmithorg/appsmith#1765]
## Summary

It would be nice to have the possibility to embed the app link in another application as iframe, and without the navigation bar.

## Motivation

In this way, it can be included in existing complex apps without having to jump to another website.

**Comment by hetunandu** [comment]
Duplicate of #1726

**Comment by Nikhil-Nandagopal** [comment]
Reopening because the iframe widget allows us to embed a page in appsmith while this is a feature to embed appsmith in another page

**Comment by Nikhil-Nandagopal** [comment]
@Simone-cogno thank you for the feature request! As a workaround, have you tried styling the iframe so that the navbar content is hidden?

**Comment by Simone-cogno** [comment]
I've tried several things like:
https://stackoverflow.com/questions/27129487/is-there-a-way-hide-elements-in-iframe-src-page

But nothing works, I suspect because of security issues on iframes.

Another possibility would be to add custom JS on the Appsmith page when is loading, is this possible at the moment?

**Comment by Nikhil-Nandagopal** [comment]
@Simone-cogno I think this should be fairly straightforward for us to handle. I'm thinking we add a query param that hides the navbar and you can load that page with the queryParam in the URL appended. Does that work?
It will look something like
https://app.appsmith.com/application/appId/pages/pageId?embed=true

**Comment by Simone-cogno** [comment]
@Nikhil-Nandagopal yes sure this will be nice. In the same subject, it would be also useful to add a password parameter too when the link is public so that only some people can see the embedded content without having to login into Appsmith (Other platforms similar to Appsmith do this too). But maybe that is another feature request.

**Comment by Nikhil-Nandagopal** [comment]
@Simone-cogno you are free to pass any query parameter and read that in appsmith. So even today you can pass
https://app.appsmith.com/application/appId/pages/pageId?accessToken=asdasda
and inside appsmith read it as {{ appsmith.URL.queryParameters.accessToken }}

**Comment by Nikhil-Nandagopal** [comment]
Also, the super fast @riodeuno has spun up a PR for this issue. You'll be able to access the embed feature as soon as it deploys 😁

**Comment by Simone-cogno** [comment]
@Nikhil-Nandagopal thanks you for the information I wasn't aware of that. It will try it. And nice to see the good support for this repo. I think it will be the future especially for admin/internal tool apps in small/medium organizations.

**Comment by Nikhil-Nandagopal** [comment]
@Simone-cogno thank you for your support! I'm sorry some of this information is not very easy to find today. We're working on improving our documentation :)
