### ISSUE TITLE
[Bug]-[25]:Copying a Chart widget shows an error for missing JS function.

### ISSUE THREAD

**Issue by muezz** [appsmithorg/appsmith#17662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am copying and pasting a chart from one app to another (which came from a sample app in my case). When I do that, I am getting the following error:

![image](https://user-images.githubusercontent.com/100420605/196406267-5a17b18d-6275-499f-8877-48e2fcac1351.png)

This error stays persistent and does not affect the app in anyway. This seems to be a bug that is not breaking in anyway. It is just a nuisance.

### Steps To Reproduce

1. Go to the sample app for Fusion charts.
2. Copy a chart from it
3. Paste it into your own app.

### Version

Appsmith v1.8.5-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5i8r0)

**Comment by Nikhil-Nandagopal** [comment]
@muezz it's likely that your chart has a binding to utils.transformPieChartData which is not valid inside the new app and thus you are seeing this

**Comment by muezz** [comment]
@Nikhil-Nandagopal I know that that is the likely reason but there is no binding for `utils.transformPieChartData` in my chart widget's properties.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 25 |
| Effort (months)  | 0.5 |

**Comment by Nikhil-Nandagopal** [comment]
This should be fixed in our new E-Chart
