### ISSUE TITLE
[Bug]: table widget does not show search results with elasticsearch query string when it has multiple words

### ISSUE THREAD

**Issue by josh9383** [appsmithorg/appsmith#17677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I search with multiple words separated by spaces in table widget with search query on elasticsearch as datasource; I can see results are fetched and totalRowCount updated on table but results are not rendered in table.

Expected : Table widget should show results as received from query response.

### Steps To Reproduce

1. Add Elasticsearch as datasource
2. Define query similar to : [https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-query-ex-request](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-query-ex-request) with pagination and searchText in query string
3. Connect table with JS snippet to use query results as data source
4. Test with single word search - works
5. Test with two words separated by space - does not work, results are retrieved but not displayed
6. Test same queries with elastic search directly or view results on debug console of appsmith - results are retrieved so no issues observed with data source or query.

 
![Screenshot 2022-10-19 101945](https://user-images.githubusercontent.com/20616650/196600370-eb837a1d-d440-4627-b703-10a029d464fb.png)
![Screenshot 2022-10-19 101713](https://user-images.githubusercontent.com/20616650/196600382-3cdadc8e-d43d-4bc1-acdd-7ff7636ef435.png)

`
{
	"from":{{ (searchTable.pageNo - 1) * searchTable.pageSize }},
	"size":{{ searchTable.pageSize }},
	  "_source": [
    "fname",
		"lname"
		],
  "query": {
    "query_string": {
      "query": "{{ searchTable.searchText? searchTable.searchText : "*"}}"
    }
  }
}
`

### Version

Self Hosted - CE

**Comment by dilippitchika** [comment]
Thanks for creating the bug @josh9383 can you also add a screenshot or a video for us to know the query response.

**Comment by josh9383** [comment]
> Thanks for creating the bug @josh9383 can you also add a screenshot or a video for us to know the query response.

Added to details - one screenshot with two words in search with empty table display but with retrieved result. Another with single word in search with results and its display.

**Comment by josh9383** [comment]
Hello team, I discovered that this issue shows up when both server side as well as client side search are enabled. Perhaps this is not a bug; but just needs a mention in documentation that enabling both client side search and server side search can result in conflicting issues so this should be discouraged.

**Comment by dilippitchika** [comment]
Thanks for the information @josh9383 i will update our docs
