### ISSUE TITLE
[Feature]: Rename table update mode options

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Rename table update mode options 
1. Row level - Single Row
2. Custom - Multi Row

### Why should this be worked on?

Makes it easy to explain what the update mode does

**Comment by dilippitchika** [comment]
![Screenshot 2022-10-18 at 10 12 04 PM](https://user-images.githubusercontent.com/19730984/196491734-e80dced8-3bcf-4225-ae3e-8ee8d84e3339.png)
![Screenshot 2022-10-18 at 10 13 05 PM](https://user-images.githubusercontent.com/19730984/196491884-5d87b450-e80c-4561-8cbf-f561e94595e2.png)

**Comment by RishikaKant** [comment]
Hello, please assign this issue to me

**Comment by sanjus-robotic-studio** [comment]
Hey @dilippitchika Can I work on this

**Comment by dilippitchika** [comment]
Hello @RishikaKant @sanjus-robotic-studio , this is already done by one of our team mates. Please feel free to check other issues
