### ISSUE TITLE
[Bug]: The upgrade message for the Audit log needs to be changed in the intercom

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The upgrade message for the Audit log needs to be changed in the intercom
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/196495129-f213e004-111b-4a15-84f0-e3b6e490ec00.png">

### Steps To Reproduce

1. Go to the admin setting
2. click on aduit logs
3. Click on the Upgrade button
4. Check the message  that sent through intercom
5. It just says upgrade which wont be clear 

### Version

release

**Comment by IAmAnubhavSaini** [comment]
@vuiets What message do we want to show here?
