### ISSUE TITLE
[Bug]: Context switching is hampering the copy paste experience of the widget

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#17670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two issues here:
1. Due to context switching the cursor is not retaining its initital position
2. This is breaking the copy paste experience of the widget

### Steps To Reproduce

1. Edit any property (say label ) of any widget (say text widget)
2. Click on the canvas to remove the focus from the property pane
3. Click on the edit widget again . You'll see the Cursor position is retained (position is wrong though)
4. Try copy and paste of the widget(Since the focus is on the input text box, Widget copy is not happening)
5. 
 https://www.loom.com/share/ed2108a3869d49f19c6245f28e5399f6

### Version

Release

**Comment by kamakshibhat-appsmith** [comment]
Checked the DP, working fine

**Comment by Nikhil-Nandagopal** [comment]
@kamakshibhat-appsmith please close if its working

**Comment by kamakshibhat-appsmith** [comment]
@hetunandu Can we move it to Needs QA pipeline so that I can close it accordingly?

**Comment by Richarex** [comment]
This is fixed, verified it on release
