### ISSUE TITLE
 [Bug]: The date range filter doesn't accept text input | audit-logs

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The date range filter functionality doesn't work when user manually types the date
https://www.loom.com/share/6c7fed8d51f643e3914e8ed28cb5cfaa

### Steps To Reproduce

1. go to admin setting page
2. click on audit logs menu
3. select the date range for start and end date
4. Now manually type in the date range filter
5. Give in the start and end dates 
6. The dates doesn't filter in the date range filter

### Version

release

**Comment by vuiets** [comment]
Lets disable text input if it doesn't work.
