### ISSUE TITLE
[Feature]: Deprioritise ranking of JS constructors on autocomplete results

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#17684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![function autocomplete](https://user-images.githubusercontent.com/46670083/196529849-baebbc7a-70a7-4f16-b048-65532f57bcf1.png)

Currently

1. The best match result autocompletes the Function() constructor.
2. The second result autocompletes the function keyword
3. The last result autocompletes the function name(params){    } statement

Expected order
1. The best match result autocompletes the function name(params){    } statement.
2. The second result autocompletes the function keyword
3. The last result autocompletes the Function() constructor (as this is the least frequently used)

### Steps To Reproduce

1. Go to any code editor field
2. type `{{fun}}`
3. See Autocompletion order

### Version

Cloud

**Comment by bharath31** [comment]
Related to #9480
