### ISSUE TITLE
[Bug]-[32000]:Evaluated Value popup overlaps the starting text of the query area and hampers query writing

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On creating and trying to write a query for any new datasource, the evaluated value popup comes immediately and covers the query area partially, making it inconvenient to write the query

### Steps To Reproduce

1. Create a datasource (mysql/postgres) Details here - [https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e]
2. Create a new query on this datasource
3. Click on the Query text area.
4. Note that the evaluated value box pops up and it partially covers the start of the query text area.
5. This makes it inconvenient to write the query
Note: The evaluated value box was coming up on the right of the text area in Prod, but has been moved to the left address another issue. 
However, it should be placed in such a way that it does not block the text view. 

### Version

Release

**Comment by bharath31** [comment]
@btsgh could you please attach a loom video to help us understand this issue better? Also, is this similar to https://github.com/appsmithorg/appsmith/issues/6259?

**Comment by btsgh** [comment]
<img width="1161" alt="evalinrelease" src="https://user-images.githubusercontent.com/101863839/196605395-e49eb957-e420-4bf9-8b0f-eb3cac9c0540.png">
<img width="1206" alt="evalinprod" src="https://user-images.githubusercontent.com/101863839/196605437-879d061b-87c0-4fa2-bf85-1e496a61fedb.png">

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 16000 |
| Effort (months)  | 0.25 |

**Comment by bharath31** [comment]
@rohan-arthur heads up-- this is similar to https://github.com/appsmithorg/appsmith/issues/6259 which is already a part of the [Evaluated Pane Improvements epic](https://github.com/appsmithorg/appsmith/issues/17463) on the FECoders Pod roadmap.

**Comment by rohan-arthur** [comment]
this got fixed with #4458
