### ISSUE TITLE
[Bug] Unable to add ternary to show null in API Body

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1769]
## Description

A user wants to add a ternary operator to send either a string or a null value to the server. This is currently not possible today

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Drag a dropdown
2. Add an API
3. Select the POST method
4. Add a binding
{
	"biosex": {{ Dropdown1.selectedOptionValue === "U" ? null : Dropdown1.selectedOptionValue }}
}

It's not possible to formulate this binding in a way that either returns a string with quotes or a null value

**Comment by mohanarpit** [comment]
Closing as duplicate of #1957

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit re-opening because this issue is not related to splitting but more to the quotes around the binding. So this is more later to our substitution change

**Comment by hetunandu** [comment]
This will be solved with #3759
