### ISSUE TITLE
[Feature]: Enable logical grouping of widgets and actions

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- Currently, there is no way to logically group a set of widgets and/or actions. I am imagining the end effect to be something like what `CSS` does for `HTML` elements. For e.g. consider the following use cases that may be addressed by this feature: 
  - a user has 20 different `input` widgets on a page and they want to update the `alignment` property for each of them. The current way is to go through each widget one by one and set the property individually. However, this is very painful and time consuming. A better approach could be to assign all the widgets to a logical group and update the `alignment` property for this logical group which should automatically apply the same to all the member widgets.
  - a user has 20 action and he wants to set each of them to run on page load. One way is to go through each action one by one and set their property individually, however, it is very painful and time consuming. Hence a better approach would be to group them together and assign the `on page load` property for the group which should automatically apply the same to the actions as well. 

### Why should this be worked on?

- Speeds up development.
- Improves user experience.

**Comment by Nikhil-Nandagopal** [comment]
Closing this as we're picking up Group styling separately and setting 20 queries on page load is not a very common use case
