### ISSUE TITLE
[Bug]: Internal server error when the evaluated value is of type ARRAY in MySQL

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#17702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Screenshot of Error
![bindingparameters_error_mysql_1](https://user-images.githubusercontent.com/3524599/196618603-e45f8d8d-d9ab-4b58-bb5a-d0a1224e5d7f.png)

[Relevant thread on Slack](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1666041302966259)

[Relevant thread on Discord](https://discord.com/channels/725602949748752515/1031589632728645693)

### Steps To Reproduce

- Create a multi-select widget
- Create a MySQL table with a varchar column, say x
- Try to insert the selected values from the multi-select into that varchar column x through the following query
`   INSERT INTO my_table(x) VALUES({{MultiSelect.selectedOptionValues}});` 
- You will notice an internal server error

### RCA
Let's say the selected options in the multi-select widget are `["x","y"]`. So the evaluated value of this binding `{{MultiSelect.selectedOptionValues}}` becomes `["x", "y"]`. For such a value the client side identifies the data type as an array. 

As MySQL doesn't have any support for array data type, we didn't add any support for the array data type in the MySQL plugin when we implemented the change required for **Datatype Handling V1** w.r.t. MySQL. We expected that the fallback data type i.e. the `StringType` would take over in such scenarios. But our assumption went wrong. The following code snippet is used to get the `AppsmithType` from the provided client-side data type and the evaluated value.

```
    public static AppsmithType getAppsmithType(ClientDataType clientDataType, String value, Map<ClientDataType, List<AppsmithType>> pluginSpecificTypes) {
        for (AppsmithType currentType : pluginSpecificTypes.get(clientDataType)) {
            if (currentType.test(value)) {
                return currentType;
            }
        }
        //Ideally we shouldn't reach here but if we do then we will return the FallbackType
        return new FallbackType();
    }
```

When `clientDataType` is of `ARRAY` the map called `pluginSpecificTypes` , provided by the respective plugin in our case which is MySQLPlugin, doesn't have any key for ARRAY. Thus `pluginSpecificTypes.get(clientDataType)` returns `null` and it throws a `NullPointerException` from the beginning of the for-loop.

### Current Workaround
If the client side identifies the data type as an array then we cannot prevent it to happen. The gimmick is to take out the array notation from the evaluated value of that binding. And get the values of the multi-select widget without having any array notation through a JS object. It's a two steps method

We are going to rewrite the following query
`INSERT INTO my_table(x) VALUES({{MultiSelect.selectedOptionValues}});` 

Two-step process

- Make the array notation part of your query i.e. take it out from the evaluated value
   ` INSERT INTO my_table(x) VALUES(CONCAT('[',  {{JSObject.getValuesOfMultiSelect()}}, ']');`
- Write the JSObject.getValuesOfMultiSelect() method
   ```
    export default {
	   getValuesOfMultiSelect: () => {
	        var a = MultiSelect2.selectedOptionValues.join(); 
	        return a ? a : null;
	   }
    }
   ```

Now the evaluated value of `{{JSObject.getValuesOfMultiSelect()}} `would be `x,y` for which the client-side data type is String.

### Permanent Solution
The right solution would be either to add a `null` check on `pluginSpecificTypes.get(clientDataType)` or add `ARRAY` type in the `pluginSpecificTypes` map.

#### More

This is the current pluginSpecificTypes map of MySQLPlugin

```
pluginSpecificTypes.put(ClientDataType.NULL, List.of(new NullType()));

pluginSpecificTypes.put(ClientDataType.BOOLEAN, List.of(new MySQLBooleanType()));

pluginSpecificTypes.put(ClientDataType.NUMBER, List.of(
        new IntegerType(),
        new LongType(),
        new DoubleType(),
        new BigDecimalType()
));

pluginSpecificTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType()));

pluginSpecificTypes.put(ClientDataType.STRING, List.of(
        new TimeType(),
        new MySQLDateType(),
        new MySQLDateTimeType(),
        new StringType()
));
```
After adding the ARRAY type in the map it would look like

```
pluginSpecificTypes.put(ClientDataType.NULL, List.of(new NullType()));

pluginSpecificTypes.put(ClientDataType.BOOLEAN, List.of(new MySQLBooleanType()));

pluginSpecificTypes.put(ClientDataType.NUMBER, List.of(
        new IntegerType(),
        new LongType(),
        new DoubleType(),
        new BigDecimalType()
));

pluginSpecificTypes.put(ClientDataType.OBJECT, List.of(new JsonObjectType()));

pluginSpecificTypes.put(ClientDataType.STRING, List.of(
        new TimeType(),
        new MySQLDateType(),
        new MySQLDateTimeType(),
        new StringType()
));

pluginSpecificTypes.put(ClientDataType.ARRAY, List.of(new StringType());
```

### Version

Self Hosted

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5d6rw)

**Comment by btsgh** [comment]
This bug has been tested in the DP and found to be fixed. Closing it as verified.
