### ISSUE TITLE
[Feature]: Enable deleting of whitespace in Form widget and / or canvas to resize the Form widget

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, the only way to reduce whitespace in the `Form` widget is to pull a widget in that space. Consider the following use case: 
- a user has three `Table` widgets lined top to bottom and then other widgets below them. Now the user deletes the topmost `Table` widget and has empty space on the top. They want to pull up all the widgets so as to fill that empty space. The only way currently is to group all the widgets and pull them together - which is a time-consuming and frustrating experience (doing it without grouping the widgets would be worse). A faster and more convenient approach could be to allow deletion of the whitespace which should automatically pull up any widget below the whitespace. 
- could the above argument apply to canvas as well ?

### Why should this be worked on?

- Speed up widget placement.
- Improve user experience when designing the page.

**Comment by dilippitchika** [comment]
@sumitsum is it a container/canvas problem or a form widget specific problem?
