### ISSUE TITLE
[Feature]: Enable active datasource search by type

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#17708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, the only way to search for an active datasource is via typing its name in the search bar at the top of the page. However, this is not feasible if the user has created a datasource some time ago and has forgotten its name. Hence, it would be useful a user can filter active datasources by type - e.g. Mongo DB or Postgres DB. 

### Why should this be worked on?

- Makes it easy to find active datasource.

**Comment by CursedRock17** [comment]
I can see what you're saying, but is it kind of inconvenient to add filters at the search bar. Would a better implementation be a filters menu underneath the Datasources subtopic in the sidebar? Also does it have to a filter menu or would it better to just sort the databases by Provider then sort them by name so they're much easier to access?

**Comment by sumitsum** [comment]
Closing in favour of https://github.com/appsmithorg/appsmith/issues/24488
