### ISSUE TITLE
[Bug]: Connect to private gitlab failed due to SSLException

### ISSUE THREAD

**Issue by zachary-guo** [appsmithorg/appsmith#17712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I followed the documentation how to use version control with git, and the git repository is my private gitlab repository with **http** and **ssh** protocal.

I deployed the key and grant write permissions to that key. But when connect to my private gitlab, I got the error:
        Internal server error while processing request

From the log, I found SSLException happened: [appsmith-gitlab-error.txt](https://github.com/appsmithorg/appsmith/files/9818332/appsmith-gitlab-error.txt)
And I'am sure the private gitlab is reachable from the appsmith.

How to solve this problem? Does appsmith only support https protocal's gitlab?

### Steps To Reproduce

1. Version Control with Git（private gitlab）
2. Deploy the key and grant write permissions
3. The private gitlab is reachable from appsmith
4. Connect to the private gitlab, I got `Internal server error while processing request`，the log shows SSLException

How to solve this problem?

### Version

appsmith 1.8.4

**Comment by manikumarnune123** [comment]
Is appsmith you were trying is cloud hosted(app.appsmith.com) or self-hosted?

**Comment by zachary-guo** [comment]
> Is appsmith you were trying is cloud hosted(app.appsmith.com) or self-hosted?

self-hosted

**Comment by manikumarnune123** [comment]
Copy your private gitlab SSL to `/appsmith-stacks/ca-certs` in crt format and restart/spin the docker container and check.

**Comment by AnaghHegde** [comment]
@zachary-guo Could you please whitelist cs.appsmith.com in your network? From the error it looks like the Appsmith server was unable to fetch the data from this server - cs.appsmith.com

**Comment by zachary-guo** [comment]
> 

@manikumarnune123 I can't find /appsmith-stacks direcotry. is it directly under / ? or should it under a relative direcotry? should I create that directory manually?

**Comment by zachary-guo** [comment]
> @zachary-guo Could you please whitelist cs.appsmith.com in your network? From the error it looks like the Appsmith server was unable to fetch the data from this server - cs.appsmith.com

I deploy appsmith locally with docker, there is no need to visit outside world. I followed manikumarnune123's step, create gitlab ssl cert, but I don't know where copy the cert to.

**Comment by AnaghHegde** [comment]
@zachary-guo In order for you to use the git sync feature we need to connect to cs.appsmith.com else this feature will not work.

**Comment by zachary-guo** [comment]
> @zachary-guo In order for you to use the git sync feature we need to connect to cs.appsmith.com else this feature will not work.

@AnaghHegde But I use private gitlab, in this case, does it necessary to connect to cs.appsmith.com ?

**Comment by AnaghHegde** [comment]
@zachary-guo Yes, it does. In the Community Edition for a workspace, a user can connect up to 3 private repositories to an app.

**Comment by zachary-guo** [comment]
> @zachary-guo Yes, it does. In the Community Edition for a workspace, a user can connect up to 3 private repositories to an app.

@AnaghHegde After whitelist to cs.appsmith.com, this time I got a different tip：

GIT CONFIGURATION ERROR
SSH Key is not configured properly. Did you forget to add SSH key to remote? Can you please try again by reconfiguring the SSH key with write access

Actually, I have done the 【deploy key】action with grant write permissions, what's the problem ?
![deploy key](https://user-images.githubusercontent.com/1758397/197161257-cb37013e-7878-47e3-8bcc-7508bb30a4a5.png)

**Comment by AnaghHegde** [comment]
@zachary-guo Please follow the steps from this doc - https://docs.appsmith.com/advanced-concepts/version-control-with-git/connecting-to-git-repository#for-gitlab and refer to this youtube video for adding the GitLab repository.
