### ISSUE TITLE
The h1, h2, h3, p1, p2 font sizes in table don’t work.

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1771]

**Comment by areyabhishek** [comment]
@riodeuno @Nikhil-Nandagopal could we introduce these font sizes+alignment options in the text widget too? They feel like related issues which should be tackled all together. It'll also mean that the text widget doesn't appear inconsistent compared to the table widget options. 
Current list of properties:
<img width="263" alt="Screen Shot 2020-11-18 at 1 16 54 PM" src="https://user-images.githubusercontent.com/30255708/99500406-586d5b00-29a0-11eb-806e-3852c860f4e0.png">

**Comment by Nikhil-Nandagopal** [comment]
We can but let's do it outside of this project. The controls are reusable but we need to write them to the widget separately

**Comment by areyabhishek** [comment]
Sure, just don't do it too late or leave it out of the next projects. If we could do these together, we can announce new visual controls for text+button+table.

**Comment by mohanarpit** [comment]
@areyabhishek Created a new issue #1810 to track your recommendation separately.
