### ISSUE TITLE
Table property pane input bugs

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1773]
Some minor bugs. 
<img width="262" alt="Screen Shot 2020-11-18 at 1 21 57 PM" src="https://user-images.githubusercontent.com/30255708/99501447-c403f800-29a1-11eb-8b4e-7e1a8bd1a3b9.png">

bugs with dragging and reordering the column names.
https://www.loom.com/share/1ce2eb060b62406e905a5e78fed8b052https://www.loom.com/share/1ce2eb060b62406e905a5e78fed8b052

**Comment by riodeuno** [comment]
@areyabhishek closing this. For dragging and re-ordering we have another issue in the property pane enhancements.
