### ISSUE TITLE
[Bug]: Response height is not maintained properly for Api Pane in Context Switching

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#17749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/12022471/196883631-7ae7d286-1492-4fb0-9718-98cb5a6f224c.mov

### Steps To Reproduce

Switch between actions after changing the height of the response pane
See it does not restore the height correctly when coming back to that action

### Version

Release

**Comment by Richarex** [comment]
This is fixed now, verified it on release.
