### ISSUE TITLE
[Bug]: UI/UX issues in Templates.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#17745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [x] There's a lot of empty space on the left side which makes the layout look odd - this is different from how Apps tab is designed

![image](https://user-images.githubusercontent.com/109572422/196860300-7dd4ad61-8725-4f6e-998f-75593b9746ad.png)

- [x] A demarcation line is required on the left pane between the fixed footer and the functions list. Leads to bad UI because of the missing line (Attached a line that is used in the profile dialog box for reference)
![image](https://user-images.githubusercontent.com/109572422/196860694-b30fb04e-7a4f-48c4-9eae-3dc3a5bcc9c2.png)
![image](https://user-images.githubusercontent.com/109572422/196860833-64f62b21-2a55-4f52-9012-4f86b6f9a1d8.png)

- [x] Hover state is missing for `View all templates`
![image](https://user-images.githubusercontent.com/109572422/196861110-92fba587-ab0b-4cba-a55e-6c5ee3c3d9c7.png)

- [x] Hover state is missing for `Go back`

![image](https://user-images.githubusercontent.com/109572422/196861187-48eb82ee-513f-4d39-a38a-5bdc03c7c5e7.png)

- [x] The scrollbars are inconsistent. Some have rounded edges in dark grey and some have straight edges in a lighter shade of grey.

https://user-images.githubusercontent.com/109572422/196861611-0e4b85dd-84cf-4e2f-a676-0d2026d0ad65.mov

- [ ] The filters on the left pane need to be in an alphabetical order.

![image](https://user-images.githubusercontent.com/109572422/196861730-b212c941-bfee-4868-a747-07291d0bb0e8.png)

- [ ] There needs to be some kind of a `clear all` option for filters, reason being if a user has selected many filters, they would have to manually unselect all of them which isn't great UX

https://user-images.githubusercontent.com/109572422/196861989-68140c1c-a992-4663-adc8-ea12daa8da5a.mov

- [ ]  (a) The text within the `request for a template` card says that a github issue portal would be opened whereas it actually opens up to a form created with Appsmith itself. 

- [ ]  (b) The text needs to be changed and made more comprehensive. Sounds wordy right now

![image](https://user-images.githubusercontent.com/109572422/196862285-c63768d5-ed52-48d4-95ae-9ea8fa8b4d14.png)

### Steps To Reproduce

Navigate to the templates page and notice the above inconsistencies.

### Version

Cloud

**Comment by RoopKrrish9696** [comment]
Most of these bugs will be fixed in a larger story of **centre aligning the pages**. cc @kocharrahul7

**Comment by rahulbarwal** [comment]
Over all 3 points remain in this:
1. Filters in templates should be sorted alphabetically.
2. The filters should have a clear all functionality.
3. Request a template  says that a "github issue portal will be opened" but instead opens one appsmith app - Need better text for this.

We are ignoring the first 2 based on our discussions [here](https://theappsmith.slack.com/archives/C02RCR2PURZ/p1688059428209129?thread_ts=1688032518.811489&cid=C02RCR2PURZ)

Fixing last one in #24852

**Comment by kavitasmoolya** [comment]
Testing update : Verification done

Issue : Request a template says that a "github issue portal will be opened" but instead opens one appsmith app - Need better text for this.
Fix : updated the Request for a template message.

'Couldn’t find what you are looking for?
Submit suggestions for templates you'd like to see or upvote requests raised by others and our team will work on it."
Tested on : https://release.app.appsmith.com/

Attached image
:

![image](https://github.com/appsmithorg/appsmith/assets/134914630/f857ef83-3e4c-47b5-9a35-e5fe696476d9)
![image](https://github.com/appsmithorg/appsmith/assets/134914630/abf050d9-109d-4479-b1c5-a38352c58100)
