### ISSUE TITLE
[Epic]: Gray scales & component deduplication  

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#17741]
### Objective

We will be ironing out major inconsistencies that we find through the platform. 
1. Standardizing and updating the shades of gray we use (so that the app feels less like a wireframe, and also so our users have a better visual scanning experience)
2. Make the border radius 4px (again, for less of the wireframe feel)
3. We will be doing some deduplication - in our updates, if we see components that are better replaced by existing ones in the design system, or if the home of the component should be in the design system, we will be making it happen within this epic. 

### Success Metrics

| Metric         |
| -------------- |
| Customer satisfaction score increases  |
| Decrease churn rate down to 30%        |

### Prioritised User Stories

| User Story    |
| ------------- |
| e.g. as a user, I want to be able to access the platform via mobile phone  |
| e.g as a user, I want to be able to communicate with the other members on the canvas  |

### Developer Handoff Document in Figma

https://www.figma.com/file/4aZWeRRAyIBX660EbIQhXn/DS-Upgrade-Exploration?node-id=0%3A1

### RACI matrix

| ------------- | ------------- |
| Responsible   |               |
| Accountable   |               |
| Consulted     |               |
| Informed      |               |

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
