### ISSUE TITLE
[Docs]: Small updates to Super Admin page

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#17757]
The [Super Admin](https://docs.appsmith.com/getting-started/setup/instance-configuration/admin-settings) docs page seems to have a couple of small outdated bits. In particular:

- The location of the Admin Settings button
    - No longer under profile; is now located at bottom left of screen on dashboard
- Screenshot of the Admin Settings page does not include the **Access Control** or **Others** sections

**Comment by yashdkadam** [comment]
I would like to work on this. Could you please assign me this issue?

**Comment by spark-c** [comment]
Ticket created in error, after closer investigation these points are not outdated.
