### ISSUE TITLE
[Task]: Instrumentation for action execution performance

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#17752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. For every action that is executed -
    a. What is the network latency (to and fro)
    b. What is the query execution time
    c. What is Appsmith’s overhead on top of a. and b.
2. What is the average value for 1a, 1b and 1c
3. What is the average value of 1a + 1b + 1c over all queries
4. For every action that is executed -
    a. What is the size of the request in bytes
    b. What is the size of the response in bytes
5. What is the average size of 4a and 4b across all queries

**Comment by nidhi-nair** [comment]
We've instrumented the common part of the workflow, we'll reopen this issue when we decide to dig deeper into each plugin.
