### ISSUE TITLE
[Feature]: Icon selection for pages and groups

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#17770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

[Icon Selector](https://www.figma.com/proto/EkPT7FdqmArkk9L7mySA5S/NAV---Designs?page-id=621%3A242148&node-id=854%3A365253&viewport=201%2C-237%2C0.15&scaling=min-zoom&starting-point-node-id=854%3A365253)

**Comment by Nikhil-Nandagopal** [comment]
Covered in #2282
