### ISSUE TITLE
[Feature]: All navigation styles

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#17771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [Top + Stacked](https://www.figma.com/proto/EkPT7FdqmArkk9L7mySA5S/NAV---Designs?page-id=357%3A182882&node-id=853%3A363028&viewport=-1153%2C763%2C0.13&scaling=min-zoom&starting-point-node-id=853%3A363028&show-proto-sidebar=1)
- [Top + Inline](https://www.figma.com/proto/EkPT7FdqmArkk9L7mySA5S/NAV---Designs?page-id=357%3A182882&node-id=853%3A363104&viewport=-1153%2C763%2C0.13&scaling=min-zoom&starting-point-node-id=853%3A363104&show-proto-sidebar=1)
- [Sidebar](https://www.figma.com/proto/EkPT7FdqmArkk9L7mySA5S/NAV---Designs?page-id=357%3A182882&node-id=853%3A363180&viewport=-1153%2C763%2C0.13&scaling=min-zoom&starting-point-node-id=853%3A363180&show-proto-sidebar=1)
- [Sidebar - Collapsible](https://www.figma.com/proto/EkPT7FdqmArkk9L7mySA5S/NAV---Designs?page-id=357%3A182882&node-id=704%3A285865&viewport=-1153%2C763%2C0.13&scaling=min-zoom&starting-point-node-id=704%3A285865&show-proto-sidebar=1)
- [Sidebar - Minimal](https://www.figma.com/proto/EkPT7FdqmArkk9L7mySA5S/NAV---Designs?page-id=357%3A182882&node-id=579%3A238541&viewport=-1153%2C763%2C0.13&scaling=min-zoom&starting-point-node-id=579%3A238541&show-proto-sidebar=1)
- [Sidebar - Mobile](https://www.figma.com/proto/EkPT7FdqmArkk9L7mySA5S/NAV---Designs?page-id=357%3A182882&node-id=853%3A368259&viewport=-1153%2C763%2C0.13&scaling=min-zoom&starting-point-node-id=853%3A368259&show-proto-sidebar=1)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7r7gs)

**Comment by Team-wb** [comment]
Perfect, this is exactly what current web applications look like! Especially the sidebar! 
I would be very happy if the feature is implemented.

**Comment by sanjus-robotic-studio** [comment]
My freelance client asked for this type of feature

**Comment by sanjus-robotic-studio** [comment]
Can this feature be prioritised

**Comment by sanjus-robotic-studio** [comment]
Oh ok

**Comment by dhruvikn** [comment]
Please also let us know your feedback once you try out the feature. @sanjus-robotic-studio
