### ISSUE TITLE
[Bug]: Internal server error pop-up intermittently when working on the code editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Seen this a couple of times and has been reported by users as well. There's an intermittent `Internal Server Error` issue that shows up when working on the editor.

This sometimes also causes current edit to revert. Couldn't capture this on a recording unfortunately and couldn't repro.

There's no concrete steps to repro the issue except suggesting working on the code editor and causing errors every now and then. Refactoring, cut-copy-paste, delete etc are some actions that can be used. Will drop in more notes as and when I figure a way to consistently repro.

### Steps To Reproduce

https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100175110?view=List

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5vemk)

**Comment by bharath31** [comment]
could be related to https://github.com/appsmithorg/appsmith/issues/14755
cc: @ApekshaBhosale

**Comment by satbir121** [comment]
@riteshkew @subrata71 Please confirm if this issue is related to #14755

**Comment by riteshkew** [comment]
This issue is related #17619 and the PR is already in release. 
#14755 is a separate issue which is already in code review
