### ISSUE TITLE
[Enhancement]: Tables generated from "Generate page with data" does not support editable column

### ISSUE THREAD

**Issue by hoonkim** [appsmithorg/appsmith#17792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create page with "Generate page with data" function, the table included in the page does not support editable column(inline editing feature).
And also,  the configuration ui of the table created from "Generate page with data" is different from the table that I created manually. 

### Steps To Reproduce

1. create page with "Generate page with data" 
2. check configuration ui, and it does not support inline editing feature, and it has different UI on its settings. (may be old version of ui??)

Task List

- [ ] Fix the Appsmith App with generate data
- [ ] Update all deprecated widgets 
- [ ] Plan strategies to avoid this issue in the future

### Version

self hoster / 1.8.4 or 1.8.5 both

**Comment by GreenFlux** [comment]
@ginilpg @kocharrahul7 , could I please get an ETA on this feature? An enterprise customer is asking about it.

**Comment by kocharrahul7** [comment]
This is now done
