### ISSUE TITLE
[Bug]: Binding Not Working When Copy-Pasting a List Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#17815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user copy-pastes a List widget, sometimes the binding does not work (it forgets its source data). This issue is intermittent, and not always reproducible.
Workaround: Cut and paste the binding (or change and change back) to make it work again. 

### Steps To Reproduce

https://app.frontapp.com/open/msg_1f2fw1ak

### Version

Self Hosted

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5eslo)

**Comment by dilippitchika** [comment]
@ashit-rath @Tooluloope this is a common problem with list v1, can you please triage this for v2?

**Comment by ashit-rath** [comment]
@dilippitchika @ame-appsmith Is this similar to this issue [#15988](https://github.com/appsmithorg/appsmith/issues/15988)?

**Comment by dilippitchika** [comment]
Kind of, but not sure if border-radius box shadow is the way to trigger it.

**Comment by ashit-rath** [comment]
border-radius and other styling are not the factors here but the copy-paste operation. This needs to be worked on as a part of v2.

**Comment by dilippitchika** [comment]
Can  you update the previous issue description then and close this issue as duplicate. I don't think we need 2 issues because the root is the same problem

**Comment by ashit-rath** [comment]
Closing in favour of #15988
