### ISSUE TITLE
[Feature]: add prettify to code editors in property pane

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#17842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, prettifying code only works on the JS Editor, we should add support to prettify code in the code editors in the property pane as well.

### Why should this be worked on?

- The JS snippets in the property pane can become long, having prettifying ability can make the snippets easy to read automatically
- We should have consistency in the features we offer in every place we write Javascript

**Comment by bharath31** [comment]
@rimildeyjsr the Cmd + Shift + P prettify shortcut works on the property pane as well. Were you referring to something else?\
