### ISSUE TITLE
[Feature]: Remove multiple blank lines between code when prettified

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#17844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Prettifying code in the JS editor should remove unnecessary blank lines of code

For example:

```
const a = 18;




let sum = a + 26;
```

should be prettified to - 

```
const a = 18;
let sum = a + 26;
```

### Why should this be worked on?

This makes the prettify behaviour consistent with the auto-indent/prettify behaviour in IDE's

**Comment by ramsaptami** [comment]
Additional scenarios to consider
- [ ] space in between `.then` is not recognized during indent
![image](https://user-images.githubusercontent.com/79509062/231750924-733d8957-c06a-4797-912c-f56f2e2433fb.png)

- [ ] space before period and any space between brackets does not indent
![image](https://user-images.githubusercontent.com/79509062/231751522-3a643542-3187-4d7e-a2ae-4fa8ef0624ce.png)

- [ ] Prettify on [this](https://appsmith-fdgfnomco-get-appsmith.vercel.app/applications/62a1b93661c2701a373be948/pages/62a1b93661c2701a373be94b/edit/jsObjects/62a1b93661c2701a373be958) code (copied code block without any spaces in between)
