### ISSUE TITLE
[Bug]: Cannot update to v1.8.5 from v1.8.4 - Migration failing

### ISSUE THREAD

**Issue by sh-TU** [appsmithorg/appsmith#17848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upgrading to v1.8.5 fails using container. It give me this error.
```
backend stdout | [2022-10-24 15:16:34,790]  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongockInitializingBeanRunner' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Invocation of init method failed; nested exception is com.github.cloudyrock.mongock.exception.MongockException: Error in method[DatabaseChangelog2.updateSuperUsers] : No enum constant com.appsmith.server.acl.AclPermission.CREATE_WORKSPACES
```

### Steps To Reproduce

1. In community edition v1.8.4
2. Attempt an update using enterprise edition v1.8.5 image. *Setup **failed** due to license expired.
3. Update and use community edition v1.8.5 instead then this error happened.

### Version

Self Hosted - CE v1.8.5

**Comment by sh-TU** [comment]
@pranavkanade, @Nikhil-Nandagopal  any quickfixes you can recommend?

**Comment by sh-TU** [comment]
@pranavkanade  @Nikhil-Nandagopal FYI
I logged-in to the database and find the permission that is being mapped. I saw these non-existing permissions in community edition applied to `Instance Administrator Role` in `permissionGroup` table so clearing those permissions worked.

```
db.permissionGroup.findOneAndUpdate({name: "Instance Administrator Role"}, { $set: { permissions: [] } })
```

I'm sure this is not the best way to fix it but at least it got working now. Please let me know what could be the side effect of doing this and the correct fix so i can apply it. Thank you.

**Comment by sh-TU** [comment]
The migration that is failing gets re-applied as well 
```
backend stdout | [2022-10-26 03:20:33,997]  - RE-APPLIED - ChangeEntry{, "id"="update-super-users", "author"="", "class"="DatabaseChangelog2", "method"="updateSuperUsers"}
```

**Comment by rohan-arthur** [comment]
@sh-TU sorry you're facing this issue with update, and thank for sharing your analysis. We will look into this get back to you asap.
