### ISSUE TITLE
[Docs]: Troubleshooting Guide: How to get Logs for Support

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#17853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

A-Force now regularly asks users to test the backend logs of the self-hosted instance to provide a better quality of support.

This documentation currently does not exist, so when A-force asks users for logs they are often a bit confused on how to get them, so it would be great to create an official guide on how to get logs to speed up the process. Of users on how to obtain these docs currently some members of A-force use this [guide](https://github.com/felix-appsmith/guide-how-to-get-logs-appsmith) on how to obtain the logs to provide them to users.

### Describe the improvement

Create an official documentation of how to obtain the logs of a self-hosted instance so that A-force members can more easily provide users with the steps to obtain and send these logs

**Comment by danciaclara** [comment]
@felix-appsmith Are you referring to how users can share the backed logs for Docker. If yes, this information is present here - https://docs.appsmith.com/getting-started/setup/installation-guides/docker/ 

[Uploading... Screenshot 2022-11-16 at 15.54.33.png]

**Comment by jnikhila** [comment]
Let's add a screenshot of logs and reword the sentence to explicitly mention that the backend logs can be followed to [Docker logs section.](https://docs.appsmith.com/getting-started/setup/installation-guides/docker#docker-logs). You can take inspiration from[ this doc.](https://github.com/felix-appsmith/guide-how-to-get-logs-appsmith)

**Comment by harshilp24** [comment]
@danciaclara @jnikhila do I have to update the docker doc or create a Troubleshooting Guide?
