### ISSUE TITLE
[Feature] Add platform feature to call Redux actions after property update 

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Along with property update payload, we can pass platform redux actions to call after update
- This feature will enable call feature specific platform actions to be called after property updates
- This feature seems like a feasible approach, as `batchUpdateProperty` is a generic action. The alternative is to take every `batchUpdateProperty` and call the feature functionality if a specific property is being updated. The former seems like a more performant approach.

**Comment by riodeuno** [comment]
Closed in #17850

**Comment by kamakshibhat-appsmith** [comment]
This seems to be an internal change .
