### ISSUE TITLE
[Bug]: queryParams evaluation fails, when navigating to same page with query params

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#17876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The evaluation of query params values is not working when user tries to add query params to the same page and use it in some other widget to set the value.

### Steps To Reproduce

https://www.loom.com/share/3c5e48f192c84f3587c8c8f9861c80bf

### Version

v1.8.6

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5guq4)

**Comment by ame-appsmith** [comment]
I think this is the same bug: https://www.loom.com/share/a2cdeeda06ec42ebb9c4a23ae977f4a7
