### ISSUE TITLE
[Bug]: Unable to grab vertical scroll bar of a table with the mouse cursor

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#17874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I have a table with a vertical scroll bar I'm unable to grab that bar with my mouse.

I expect to be able to grab the vertical scroll bar and drag it to scroll the contents of the table.

This works fine for the horizontal scroll bar, but not vertical.

### Steps To Reproduce

1. D&D a table widget.
2. Resize the widget or add data so that the scroll bar appears.
3. Try to drag the scroll bar with the mouse.

### Version

Cloud 1.8.6-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5gnws)

**Comment by dilippitchika** [comment]
Closing in favor of #18230
