### ISSUE TITLE
[Enhancement]: Make template list sidebar consistent with Application page sidebar

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#17880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

**Current Application page**
![Screenshot 2022-10-26 at 1 17 07 PM](https://user-images.githubusercontent.com/890915/197965931-1f220e61-941c-4cc3-837b-949116c444cf.png)

**Current Template list page**
![Screenshot 2022-10-26 at 1 17 39 PM](https://user-images.githubusercontent.com/890915/197966043-1760d7ba-4e30-4ba9-a181-aba14cb93faf.png)

---
**Proposed Template list page**
![Screenshot 2022-10-26 at 1 18 06 PM](https://user-images.githubusercontent.com/890915/197966154-16290448-4c10-46b6-ba10-ca5ad00eb2fe.png)

**Comment by zetabug** [comment]
Hi there, I looked this up on the website, I think I can fix it and make it according to the proposed template. I want this issue assigned to me.
