### ISSUE TITLE
[Feature] Make it easy to access existing datasources and edit them

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1788]
## Summary

Make it easy to access existing data sources and edit them from the entity explorer.

## Motivation

Data sources are difficult to access today because they can only be accessed through the query creation workflow.

## Potential solution

Clicking the 'DB queries' entity opens the data sources page. Today clicking it unfurls the list of DB queries.

<img width="823" alt="Screen Shot 2020-11-18 at 7 17 06 PM" src="https://user-images.githubusercontent.com/30255708/99539272-080ff080-29d4-11eb-87af-9464d506fddb.png">

<img width="318" alt="Screen Shot 2020-11-18 at 7 26 23 PM" src="https://user-images.githubusercontent.com/30255708/99539262-05ad9680-29d4-11eb-873c-2103dff58d88.png">
@trishaanand @sharat87 Please give your thoughts here. @aakashDesign will work on a solution tomorrow.

**Comment by trishaanand** [comment]
@areyabhishek : What would you think of adding Datasources to the entity pane but it doesn't unfurl and show the data sources. When clicked, it simply opens the datasource page as mentioned above. This keeps the Queries and Datasources separate visually and there is a simple way to view/edit all your datasources.

**Comment by sharat87** [comment]
In addition to what @trishaanand wrote, such a Datasources section could have a `+` button, just like DB Queries has, which goes to adding a new datasource page. This will make the UI consistent and predictable, which creating a new datasource would be just a click away.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand @sharat87 I have a question
- Why would you want to edit a data source that is not part of an application, inside an application?
- If the goal is to simply edit any data source added in an org then would it make sense to introduce all data sources in a section at the org level?

**Comment by sharat87** [comment]
Yes. I’d like that even better. It also fixes the current quirk in the mental model where we are led to believe that data sources are inside applications.

**Comment by trishaanand** [comment]
I agree with @Nikhil-Nandagopal and @sharat87 here that an organization level way off accessing all the datasources would definitely help with the mental model. And it would be exceptionally useful as well.
But, I still would like a way to edit the datasources from within the application. Its inside the application that you end up using the datasources (using queries) and its at this particular level when you are bound to notice problems/handle new circumstances/etc. and would want to easily access and edit your datasources.
Also having a way to see all the datasources from within the application also lets me quickly generate a query using the datasource structure in my current application which is very useful. 

On another note, I also would like to not see the datasource structure in the entity pane but rather have it in the main query pane on the right hand side (or wherever its in focus while writing the query). Even though entity pane datasource lets me generate my queries, but when I am writing my query all on my own, using entity pane display is not the most natural and most user friendly way of visualising the table and its structure.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand but if you are using that data source in the app, it already shows up today. Did I miss something?

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : It does show up in the entity pane. I was talking about finding it more useful during writing queries. Thanks to more real estate in the query pane, we can display the data source structure in a better format making this a lot for useful. Today, when I try to use the entity pane, I face the following confusions :
1. All the datasources being used are clubbed together. If I have multiple datasources of the same type, I get confused and have to pay attention.
2. Scrolling all the datasources in the entity pane to reach the one I want seems a little harder than seeing the datasource on the right hand side in the query pane itself.

May be I spoke too soon about removing these from entity pane for auto generation of the queries. But as @nidhi-nair had suggested, it would be quite awesome to have the datasource structure in the query pane itself for better context during query writing.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand got it. I think we misunderstood the problem in the beginning. Let me try to rephrase and please correct me if I'm wrong. 
The problem is that it's hard to view the entities in a db while writing a query.
The other problem around editing a datasource exists but not such a big problem today.

**Comment by areyabhishek** [comment]
We'll pick up this task a little later because current problems are solved.

**Comment by aakashDesign** [comment]
Hey Team!

Take a look at this latest prototype for API creation and using datasources.
https://www.figma.com/proto/ko05rfZRuc8HzqBZRpg1fY/API-Pane-Updates?node-id=402%3A2659&viewport=927%2C654%2C0.25578033924102783&scaling=min-zoom


Existing datasources can be accessed in an Import sidebar when you create a new API.
<img width="1526" alt="Screenshot 2021-01-11 at 11 13 25 AM" src="https://user-images.githubusercontent.com/65771350/104149908-096eff80-53fe-11eb-988a-ed4cbdadf23d.png">
<img width="1514" alt="Screenshot 2021-01-11 at 11 13 41 AM" src="https://user-images.githubusercontent.com/65771350/104149922-11c73a80-53fe-11eb-8dad-94160861f699.png">
<img width="1622" alt="Screenshot 2021-01-11 at 11 13 57 AM" src="https://user-images.githubusercontent.com/65771350/104149932-1ab80c00-53fe-11eb-9ff7-95da1a655a4c.png">
