### ISSUE TITLE
[Bug]: Create a Template by deselecting a couple of pages - pages are listed and error with uncaught promise when clicked on

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On creating a template by deselecting a couple of pages, the pages are still listed in the menu dropdown, and on clicking any of the pages, Uncaught Promise Rejection error pops up.
Expected behavior, the two deselected pages should not be listed at all. 

### Steps To Reproduce

1. Create an app and "Start from a template" .. Choose the Vehicle maintenance template.
2. Deselect the Select All, and only choose Home Page and click on Add Selected Pages. 
3. From the Open Menu button in the Manage Services heading, the second and third pages are still listed 
4. If we click on either, an error comes up as below 
<img width="1040" alt="Screenshot 2022-10-27 at 10 57 57 AM" src="https://user-images.githubusercontent.com/101863839/198199426-67b16890-d814-4f4c-94b3-80569c434e75.png">

View the loom video for detailed steps - 
https://www.loom.com/share/f4969f740cff4ef6aa24c96ca8c51342

### Version

Production

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working now
