### ISSUE TITLE
[Bug]-[1988]:Could not import the App in the Organization

### ISSUE THREAD

**Issue by MythiliKrishnamurthy** [appsmithorg/appsmith#17903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When try to import the app in the organization ,I have noticed an error which forbids importing of the application.It shows the following error "Cannot read the properties of the undefinded (reading status)".
![image](https://user-images.githubusercontent.com/116805110/198270719-c59c1b22-30c6-46a9-83bc-21ff08fa72fd.png)
![Capture](https://user-images.githubusercontent.com/116805110/198270799-45439e37-00e6-4e19-b6c6-81078e32b075.PNG)

### Steps To Reproduce

When try to import the app in the organization ,I have noticed an error which forbids importing of the application.It shows the following error "Cannot read the properties of the undefinded (reading status)".

### Version

Appsmith v 1.7.9

**Comment by vuiets** [comment]
@AnaghHegde is this related to https://github.com/appsmithorg/appsmith/issues/17787? Can we fix both in one go?

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 497 |
| Effort (months)  | 0.5 |

**Comment by AnaghHegde** [comment]
@vuiets [For](https://github.com/appsmithorg/appsmith/issues/17787) is different from this issue. The import modal is disabled for some reason. The user is unable to upload the file.

**Comment by AnaghHegde** [comment]
@MythiliKrishnamurthy Could you please share the logs from the Appsmith instance?
You can send to me via email anagh at appsmith dot com or upload them here.

**Comment by AnaghHegde** [comment]
Closing this issue. Please feel free to reopen the
