### ISSUE TITLE
[Bug]: Fixing the logic of queries/datasources on the datasources page

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#17907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open the Datasources page in an app, I see the list of queries on the current page which are using that datasource, but if I go to a new page, and there are no queries using that datasource, it shows `No queries on this app`. Both screenshots are for the same app, but different pages. 1 says `No query in this application is using this datasource`, even though other pages have queries

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/20532920/198276626-41a60da6-f6c7-4ddf-a9c7-8c719b27ab6e.png">
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/20532920/198276675-939f9f38-2994-4bec-af62-43d1505a925b.png">

This could be a copy issue, but it would be better to solve this by fixing the actual logic to see how many queries on this app are using this datasource

### Steps To Reproduce

Create an app, and connect to a datasource
Write a query for this datasource
Create a new page
Observe

### Version

v1.8.6 Cloud

**Comment by sribalajig** [comment]
@parth-appsmith @ChandanBalajiBP lets figure out the right copy for this

**Comment by rohan-arthur** [comment]
fixed by new ia: datasources section is now apart from the app and pages
