### ISSUE TITLE
[Bug]: Omnibar documentation `connect to databases` selecting "elastic search" takes the user to DynamoDB

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#17910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open this page on the omnibar, and click on elastic search, I am redirected to the dynamoDB docs rather than the Elastic search.

This is correct on the docs website

https://user-images.githubusercontent.com/20532920/198283377-4600459d-4770-4b1c-a54f-ac076e3e83f1.mov

Seems to be an Omnibar specific issue, not an issue with the documentation page itself.

https://user-images.githubusercontent.com/20532920/198283599-5b870815-d8a1-4e46-acfc-11ade461f916.mov

### Steps To Reproduce

Connect to a new datasouce
Click on the documentation link
select elastic search

You will be redirected to DynamoDB rather than DynamoDB

### Version

v1.8.7

**Comment by Nikhil-Nandagopal** [comment]
This seems fixed
