### ISSUE TITLE
[Bug]: Couldn't redo or undo changes If we switched between different panes

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#17915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1) Go to any code editor pane and type your code
2) Switch to a different object or canvas and come back to the code editor
3) Undo/redo no longer work.

### Steps To Reproduce

1) Go to any code editor pane and type your code
2) Switch to a different object or canvas and come back to the code editor
3) Undo/redo no longer work.

https://www.loom.com/share/378489e60017434e9cd51613ec180a96

### Questions and answers:
Question | Answer
-- | --
How many states will we store in the undo-redo flow? | We will store 10 undo and redo states for the last 5 entities

### Version

Cloud

**Comment by rohan-arthur** [comment]
won't fix - project cancelled
