### ISSUE TITLE
[Bug]: Prompt user before deleting an action that's used in app

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#17913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

User shouldn't accidentaly delete an Api/Query/Jsobject that's being used elsewhere in the app.
(I've noticed this with API and assuming it's the case with other entities as well)

### Steps To Reproduce

1. Create an API
2. Bind `Api.data` / `Api.run` in some widgets.
3. Delete Api1.
4. We should prompt the user since API is being used in the app.

### Version

Cloud - Appsmith v1.8.6-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
Thanks for raising this @eco-monk but I'm not aligned on the solution and I believe instead, we should focus on making it easy to undo the operation
