### ISSUE TITLE
[Bug]: Back button behaviour is inconsistent after you create a new Query/API

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#17912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Back button on the API/Query page behaves inconsistently. It should always take you back to the canvas from an API/Query but it takes you back to the Active datasources page in certain cases.

Loom - https://www.loom.com/share/b20fcb92375c4186a9a7a3413fa5ee69

### Steps To Reproduce

1. Open an app in the editor.
2. Create a new API from the submenu.
3. Hit the back button on top of the API page
4. You will be taken back to the Active datasource page, even though you never visited it.

### Version

Cloud

**Comment by rohan-arthur** [comment]
@aakashDesign should the back button simply go `back`, i.e., the original source of the navigation? If it is more desirable to always navigate to the canvas, should the title of this button be something else like (bad example) `Go to Canvas'?

**Comment by ginilpg** [comment]
@aakashDesign Can you please confirm the expected behaviour here?

**Comment by aakashDesign** [comment]
Hey folks,

Here expected behavior for the back button  -

"When a user creates a new query/API from the explorer, the back button should take them back to canvas. Currently, the back button is navigating to the 'Active Datasources' page."
Similarly, if the new query/API has been created from the 'Datasource saved' page, the back button should still navigate users back to Canvas.


@rohan-arthur @ginilpg 

1. The expected behavior for the back button on query/API is to always take users back to the canvas. 
2. The browser back/forward buttons are there to take users back to the last screen.
3. When it comes to Datasource pages like Edit datasource or 'Datasource Saved' the button should take users to the last step, as it's been currently implemented.
4. We've discussed the idea of renaming the button to "Back to Canvas" but it has not been finalized.

If this is confusing please let me know, happy to explain this over a call.

**Comment by kocharrahul7** [comment]
We ahve removed the back button
