### ISSUE TITLE
[Feature]-[28.988]:Adjustable font size for Button Widgets

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#17928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently many of our widgets support the ability to change the font size of their text. It would be nice to have the same functionality for button widgets.

### Why should this be worked on?

This can allow users to make buttons stand out more or improve the text readability.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5i8p8)

**Comment by aseemcfosters** [comment]
Our use case for this would be making the button text easier to read. We are making a visitor sign-in app so this would be a very useful feature for us if it were to be implemented.

**Comment by Alcadeus0** [comment]
can i work on this?

**Comment by dilippitchika** [comment]
Hi, @Alcadeus0 this is a fundamental change to how a button works on appsmith. We would pick this up internally

**Comment by Alcadeus0** [comment]
Sure that's fine by me :)

**Comment by keembogeul** [comment]
Allow me to change the style settings of the button text.

**Comment by developer-honoru** [comment]
I really need this feature!

**Comment by Suyeon04** [comment]
I can't believe this feature doesn't exist!

**Comment by dilippitchika** [comment]
@Suyeon04 @developer-honoru @keembogeul can you please add your use-case of changing the size of a button text? I want to understand this a bit better.

**Comment by honoru-washswat** [comment]
https://discord.com/channels/725602949748752515/827256420398399500/1069197126174777374
CC..

**Comment by jsartisan** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2.672 |
| Effort (months)  | 0.5 |

**Comment by KelvinOm** [comment]
It looks like there hasn't been much activity for a while. This issue will be resolved within the Anvil project.
