### ISSUE TITLE
[Bug]: Text input does not work with "[]" 

### ISSUE THREAD

**Issue by jondoering** [appsmithorg/appsmith#17926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, 
When using multi-line or normal text input field in a form created from a postgres table, and try to input a json string starting with "[]", something seems to happen that changes the string and inserts an altered string into the database removing the "[]". The aim here is to store the full stringified version of the json as a text in the column. 

Examples:
[] is resulting in a null error (no string at all)
[{"a" : "b"}] in something like {"{"a" : "b"}"}

![Pasted_Image_27_10_2022__23_47](https://user-images.githubusercontent.com/13738458/198413351-f5ff7f6d-9f70-4d9f-b2db-6f528fa717f2.jpg)
![Pasted_Image_28_10_2022__00_06](https://user-images.githubusercontent.com/13738458/198414325-a5bacaa8-46f2-47ab-9ec3-d48fd1275098.jpg)

### Steps To Reproduce

* Create a form from a postgres database with a text field
* try to insert a json string into the data base with a text input or multitext input that is an array e.g. "[]"

### Version

Self hosted - Appsmith Community v1.8.3

**Comment by Nikhil-Nandagopal** [comment]
@jondoering this should work if you turn off the prepared statement option in the query
