### ISSUE TITLE
[Feature]: Filepicker to support parsing xls, tsv, json along with csvs

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Filepicker widget can automatically parse the following filetypes and convert them to arrays and objects

### Why should this be worked on?

Simplifies the workflows for users

**Comment by dilippitchika** [comment]
Within appsmith, we wish to support parsing files into arrays and objects without users having to build their own workflows to display these files in widgets.

For xls and xlsx files, the parsing will need to happen across all sheets. The format of data can be an array of objects with `sheet_name` and `sheet_data` as keys.

**Comment by dilippitchika** [comment]
@andrewdietekoki please make sure the following are present
1. TL;DR of the solution
2. Link to figma screens
3. Link to figma prototype

**Comment by dilippitchika** [comment]
@rajatagrawal can you check this out?

**Comment by rajatagrawal** [comment]
It is I think. I saw it on zenhub in the standup today and it shows here as well : 
![Screenshot 2023-05-31 at 7 59 43 PM](https://github.com/appsmithorg/appsmith/assets/1189106/68252f34-1ebf-4869-a2fe-3d18b7f7cb09)
