### ISSUE TITLE
[Task]: Context switching phase 2 for canvas

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#17975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

## Entity Explorer: 
- [x] Entity explorer should stay as you left it when you left the page (collapse levels)
- [x] Widget/explorer tab
- [x] Width - Should be the same across all pages of an app

## Canvas / Widgets:
- [x] Complex widgets, multi tier property panes
- [x] Tabs
- [x] Property Pane width

**Comment by Richarex** [comment]
- [ ] Entity explorer should stay as you left it when you left the page (collapse levels):- This is working as expected even the collapse levels are attaining it's previous state.
- [ ] Widget/explorer tab:- Working fine explorer/widgets are maintaining their previous states when switched between pages/api editor/query pages tested it on DP.
- [ ] Width - Should be the same across all pages of an app:- Working fine tested it on DP.
