### ISSUE TITLE
[Bug]: Read Only property not working as expected in Deploy mode

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#17977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upon changing the rating of the widget and then enabling the `Read Only` property, we see the default rating in deploy mode and not the one that is set by the developer.

https://www.loom.com/share/b25da1e61b2149bfa3201fa6b00b47b6

### Steps To Reproduce

1. D&D the rating widget.
2. Change the rating to anything but the default rating.
3. Now enable the `Read Only` property and deploy the app.

### Version

Cloud

**Comment by dilippitchika** [comment]
@shadabbuchh this is not a bug, it's like any input widget behavior -  Whatever text you add it doesn't stay the same in the deploy mode. We use the default value. This is because we treat deployment as a new session.
