### ISSUE TITLE
[Bug]: Internal server error is displayed when the user selects "Sheets" as datasource from Quick Page Wizard 

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#17974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user selects google sheets as datasources from the 'Quick Page Wizard' page internal server error is displayed.

### Steps To Reproduce

1. Go to this url:- https://release.app.appsmith.com/applications
2. Click on **New** button and create your workspace
3. Click on **Generate page from data table**
4. Now on **Quick Page Wizard** select **Sheets** as your datasource from the dropdown
5. Observe the error 

**Actual Result**
Internal server error is observed when **"Sheets"** as datasource is selected.

**Expected Result**
User should be able to select **"Sheets"** as datasource without any error.

**Note**
Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/uQ4egV0MQPmIK7Jp 

### Version

Release

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_61x1o)

**Comment by rohan-arthur** [comment]
happens only some times, some observations:
1. each time this happened, it was for a new app
2. out of 10 tries, I saw the error 4 times

**Comment by btsgh** [comment]
More observations - I am unable to see the internal server error, however, though I am able to select the Spreadsheet, and the sheet, I get an error as per this image.  And I see the same behavior on Prod too!!! This I am able to reproduce consistently.
<img width="1440" alt="Screenshot 2022-11-04 at 12 55 01 PM" src="https://user-images.githubusercontent.com/101863839/199916469-83830bf3-a09d-4297-ac72-38ab31fccc5f.png">

**Comment by sumitsum** [comment]
Removing `release blocker` tag since I am able to reproduce the same issue on prod as well with a older datasource. Primary investigation reveals that `refresh token` flow is failing on cloud services with the following error: 
```
		Nov 4 13:50:25 cloudservice-7b9c6d7d4c-pvrc6 cloudservice requestId=0f30169dbb64e28319d03cca680d24d4 - Retrieving authentication response
		 - Unable to retrieve access token for integration 609126dbdb29e66d63d69c94 with error 400 BAD_REQUEST
		 -
		com.appsmith.internal.exceptions.AppsmithException: Internal server error while processing request
			at com.appsmith.cloudservices.services.IntegrationServiceImpl.lambda$refreshAccessToken$13(IntegrationServiceImpl.java:153)
			Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
		Nov 4 13:50:25 cloudservice-7b9c6d7d4c-pvrc6 cloudservice Error Error has been observed at the following site(s):
			|_ checkpoint ⇢ Handler com.appsmith.cloudservices.controllers.IntegrationController#getAuthenticationResponse(Integration) [DispatcherHandler]
		Nov 4 13:50:25 cloudservice-7b9c6d7d4c-pvrc6 cloudservice trace Stack trace:
				at com.appsmith.cloudservices.services.IntegrationServiceImpl.lambda$refreshAccessToken$13(IntegrationServiceImpl.java:153)
				at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
				at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:127)
				at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
....
....
```

**Comment by btsgh** [comment]
> More observations - I am unable to see the internal server error, however, though I am able to select the Spreadsheet, and the sheet, I get an error as per this image. And I see the same behavior on Prod too!!! This I am able to reproduce consistently. <img alt="Screenshot 2022-11-04 at 12 55 01 PM" width="1440" src="https://user-images.githubusercontent.com/101863839/199916469-83830bf3-a09d-4297-ac72-38ab31fccc5f.png">

Raised a separate [bug](https://github.com/appsmithorg/appsmith/issues/18102) for this issue

**Comment by AmanAgarwal041** [comment]
After the using the generate page functionality. The crud operations created when we leave `tableHeaderIndex` empty result in error. Here's a loom video : 
[Loom Video Link](https://www.loom.com/share/cc753596a14c4ac082c917c72ee747d4)
