### ISSUE TITLE
[TASK]: The context value should be memoized to prevent re-renders of children.

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17982]
Not related to the current PR but the context value should be memoized to prevent re-renders of children which subscribe to the context. Currently it creates a new reference of context value on every render.

_Originally posted by @rahulramesha in https://github.com/appsmithorg/appsmith/pull/17960#discussion_r1009109400_

**Comment by ArjobanSingh** [comment]
Hey @riodeuno @SatishGandham 
I've raised a [PR](https://github.com/appsmithorg/appsmith/pull/20182) completing this memorization task, can you please review it?

Thanks

**Comment by nikhil-babar** [comment]
@SatishGandham are you working on this issue ?

**Comment by nikhil-babar** [comment]
@riodeuno I am interested in working on this issue, plz can you assign me

**Comment by riodeuno** [comment]
@nikhil-babar We've had an internal discussion, figured that this doesn't make an impact to the product and decided to remove this issue. 

I'm happy to assign any other Good First Issue that you would like to pick up.
