### ISSUE TITLE
[Task]: Cleanup & Performance: Declare function beforehand instead of declaring when passing as a prop

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17985]
should we have this function declared before the map it creates new function for each handle.

_Originally posted by @marks0351 in https://github.com/appsmithorg/appsmith/pull/17851#discussion_r1006462910_

**Comment by utkarshkumarawasthi98** [comment]
Hello, can you please assign this issue to me.

**Comment by Sonali-Behera** [comment]
Hey, Is this issue is still open. I would love to work on this. Please assign this to me.

**Comment by harshlakhara** [comment]
Hey, I'd like to work on this. Please assign to me.

**Comment by riodeuno** [comment]
Closing as this code is in maintenance mode, and active development on this has been paused.
