### ISSUE TITLE
[Bug]: Menu widget : After adding new item last item is displayed right aligned 

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#17992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Create new app >> add new Menu widget on canvas >> Click on Add new item, Item is added - Menu item 1. 

Observation:  it is displayed right aligned, other items are left alined 
Found in release and not reproducible on production

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/80756091/198987261-efbaaad3-86b5-4753-baa6-1b72192d541a.png">

### Steps To Reproduce

1. Add new menu widget
2. Click on add event
3. Select the menu widget and verify the alignment
4. Last item is miss-placed 

Other way to reproduce issue is keep icon as none for any item and change the position please check the recording

https://user-images.githubusercontent.com/80756091/199018815-1c862e9e-0e5e-441e-b742-51ca16e029d9.mov

### Version

cloud

**Comment by AnandiKulkarni** [comment]
@kamakshibhat-appsmith - Please check

**Comment by somangshu** [comment]
@dhruvikn lets first identify why this issue started occuring?
