### ISSUE TITLE
[Bug]: "Appsmith server is unavailable" error is displayed when user imports the GitHub app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

"Appsmith server is unavailable" error is displayed when user imports the GitHub app this happens to me in a specifically 1 repo
https://github.com/RakshaKShetty/apr-18regression
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/199014150-aafaa1b6-2ae6-4d3d-a22b-6ae525e82dc3.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/199014164-106149ea-ff93-495f-93a1-45ed9014806e.png">

### Steps To Reproduce

1. Go to home page
2. Click on meat ball icon 
3. Click on Import
4. select import from github
5. Add the SSH 
6. Then try to import The App card don't display until we refresh the page 
7. After the App card is displayed click on it the Appsmith server is unable error is displayed

### Version

release

**Comment by AnaghHegde** [comment]
The reason for this failure is that, the `pages` filed is missing from the application.json file in the repo. Hence, when imported, the defaultPage is not set. If the default page is not set in the application object then we will not be able to refer to the page collection to get the necessary details. 

Sample data with the page information. 

{
  "pages": [
    {
      "id": "Page1",
      "isDefault": true
    }
  ],
  "viewMode": false,
  "appIsExample": false,
  "unreadCommentThreads": 0,
  "color": "#FFEFDB",
  "icon": "frame",
  "evaluationVersion": 2,
  "applicationVersion": 1,
  "isManualUpdate": false,
  "deleted": false
}

**Comment by RakshaKShetty** [comment]
as its happening in only one repo

**Comment by IAmAnubhavSaini** [comment]
> The reason for this failure is that, the `pages` filed is missing from the application.json file in the repo. Hence, when imported, the defaultPage is not set. If the default page is not set in the application object then we will not be able to refer to the page collection to get the necessary details.
> 
> Sample data with the page information.
> 
> { "pages": [ { "id": "Page1", "isDefault": true } ], "viewMode": false, "appIsExample": false, "unreadCommentThreads": 0, "color": "#FFEFDB", "icon": "frame", "evaluationVersion": 2, "applicationVersion": 1, "isManualUpdate": false, "deleted": false }

How does this happen?

**Comment by AnaghHegde** [comment]
@IAmAnubhavSaini My hunch was that there was a bad merge conflict resolution. But could not find any commits for merge. I have asked Raksha to check if the original app is working. But i am out of ideas on how the app reached into this state.

**Comment by AnaghHegde** [comment]
Closing this as scenarios like this are handled with the mongodb transaction.
