### ISSUE TITLE
[Bug]: Search on home page brings up some unrelated apps along with the apps matching the criteria

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to search for an app in the Home Page area, some unrelated apps are also displayed

### Steps To Reproduce

1. Login to release and on the Home Page, try to search for an application. 
2. Note that along with the relevant apps, some apps which seem irrelevant also show up. 

I am searching for apps with "Feedback" in their name, but we see that another app called "testblackborder" is also seen

<img width="659" alt="Screenshot 2022-10-31 at 7 49 40 PM" src="https://user-images.githubusercontent.com/101863839/199035854-03a19880-e027-41b0-ba7d-70deb3090237.png">

Another example - Searching for apps with the name Direct, also am getting apps with names RestRecurring, AirtableNoInputIssue, Deprecated.. and so on. View images below

<img width="335" alt="Screenshot 2022-10-31 at 8 02 30 PM" src="https://user-images.githubusercontent.com/101863839/199037986-4eb79912-a0be-4d6e-9cb5-19743c6ca920.png">
<img width="334" alt="Screenshot 2022-10-31 at 8 02 34 PM" src="https://user-images.githubusercontent.com/101863839/199037999-a95ecc2b-11e3-412d-8923-3ad06fb1fa4c.png">

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
This is due to fuzze search I believe
