### ISSUE TITLE
[Bug]: When we use Vision Impaired, in developers appsmith section, user profiles not properly visible

### ISSUE THREAD

**Issue by sandeeprawat28** [appsmithorg/appsmith#18005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot (58)](https://user-images.githubusercontent.com/76909857/199054142-e9283203-1041-41d9-be32-8d63f0fdf538.png)

### Steps To Reproduce

Open Equally AI
Then select Vision Impaired
Turn on it
See the Developers Appsmith section 

### Version

release

**Comment by tejasahluwalia** [comment]
Unfortunately, it looks like this is not entirely in our hands. The accessibility plugin inverts all colors on the webpage including images when in `Vision Impaired` mode.

I have reached out to them to find a way to disable the inversion of colors for images alone. If that's not possible we can evaluate other options.

**Comment by tejasahluwalia** [comment]
Received a response from Equally.ai

> Thank you for contacting Equally AI.
>  
> To disable inverting colors of images when using "Vision Impaired" mode, after you select the ‘Vision Impaired’ option, navigate to the contrast settings below and toggle the 'Reverse Contrast' off.
>  
> Please do not hesitate to contact us if you have any further questions.
>  
> Thank you for choosing Equally.

This fixes the problem, so closing the issue.
