### ISSUE TITLE
[Bug]: Need to limit Auto scroll to widgets 

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#18015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are scrolling whenever a new widget is selected. Instead we should only do so when the widget is significantly out of the view port center

### Steps To Reproduce

1. Click on a widget
2. Click on another widget near it

https://user-images.githubusercontent.com/12022471/199164535-e7f009cc-f7a0-4d84-a3c6-1b98fca7a14b.mov

### Version

Cloud

**Comment by Richarex** [comment]
Fixed, verified it on release video:- https://jiju8jbmwa.vmaker.com/record/eQX6Mdjw5Z5fjrT9
