### ISSUE TITLE
[Bug]: Context Switching does not work on API pane url

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#18011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/12022471/199161605-34cc2803-adc0-4a56-9898-5d4d3e88b5e2.mov

### Steps To Reproduce

1. Navigate to API
2. Focus on the URL field
3. Navigate out of the API to any part of the app
4. Navigate back to the API

expected to have the focus and cursor be on the URL field

### Version

Cloud

**Comment by Richarex** [comment]
This is fixed, verified it on release video:- https://jiju8jbmwa.vmaker.com/record/DrN5yNH12T1xQm5T
