### ISSUE TITLE
[Bug]: Context Switching Scrolling issues in property pane

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#18013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Scroll top not working
https://www.loom.com/share/f3501752a6334aed8544bb18a1ab3f14

- Flickering issues due to auto scroll.
https://www.loom.com/share/7f1bffb7896a4ec992652df2509435fb
- Not focusing on correct property .
 https://www.loom.com/share/6cf64700098044a3a525a3d9b02f06e8

### Steps To Reproduce

Context Switching in property pane acts weirdly

### Version

Cloud

**Comment by Richarex** [comment]
This issue is fixed, verified it on release
