### ISSUE TITLE
[Feature] Applications on homescreen should be sorted by recently used instead of Alphabetically

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#1801]
## Summary

Apps in my org are sorted alphabetically. They should be sorted by most recently edited.

## Problem

Example - My most recent app is Untitled application 1 but it's usually lost in between.

<img width="1775" alt="Screenshot 2020-11-19 at 4 40 18 PM" src="https://user-images.githubusercontent.com/65771350/99658975-30f0be00-2a86-11eb-81bc-2908c8b9e871.png">

**Comment by nayan-rafiq** [comment]
This has been implemented already.
