### ISSUE TITLE
[Bug]: [Context Switching] Default focus not being set for new entities

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#18016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating new action entities, we are not resetting the focus states to their defaults

### Steps To Reproduce

https://user-images.githubusercontent.com/12022471/199164987-9fe9a211-c10e-4fbc-83cb-661ab4e7d2bf.mov

https://user-images.githubusercontent.com/12022471/199164991-0750f1c8-cc05-4396-b521-384d4ecb42e6.mov

https://user-images.githubusercontent.com/12022471/199165001-e8208af2-15b7-4c1d-82f7-5257138876ac.mov

### Version

Cloud

**Comment by Richarex** [comment]
This is working fine, verified it on release.
