### ISSUE TITLE
[Bug]: Manage Users -> Delete modal -> Remove button seems to be red in color

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on share and invoke the Manage Users -> Delete modal -> Remove button seems to be red in color as against the expected Orange.

### Steps To Reproduce

1. Login to appsmith and go to your workspace
2. Click on the Share button and invoke the Manage Users modal. 
3. Select a user and click Delete
4. This Delete modal has a Remove button

The color of the button is Red in color as against the expected orange. 

<img width="911" alt="Screenshot 2022-11-01 at 11 45 13 AM" src="https://user-images.githubusercontent.com/101863839/199180484-03868794-02c1-460b-b591-75208bb9761c.png">

### Version

Production

**Comment by rohitagarwal88** [comment]
Fixed in ADS 2.0
