### ISSUE TITLE
While creating a gsheet datasource, creation of the query should only be possible on valid datasource

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#18032]
design: https://www.figma.com/file/Qs7p5frNx7uEfVYpADGk0d/Query-Pane-Improvements?node-id=1132%3A45433

**Create Mode**
Current behaviour: when I click `save and authorize`, save happens first, then the user is shown the auth popup in a separate page. There are two possibilities here:
1. auth success: no problem, the datasource is saved with the successful auth, user sees the datasource overview page
2. auth failure: the datasource is saved without auth

Proposed change: 
1. auth success: no problem, the datasource is saved with the successful auth, show the datasource overview page
2. auth failure: _The datasource should be saved as it is today, but on the view datasource page, I should see an error banner as shown in the design, and the `New API` button should be disabled_

**Comment by prapullac** [comment]
1) As discussed Banner needs a  change from Re-Authorise to Authorise
2) As discussed the banner to be added on Active and edit page of the Datasource
