### ISSUE TITLE
[Bug]: Table Filter Text Loses Focus When User Is Typing

### ISSUE THREAD

**Issue by charles-bloomfield** [appsmithorg/appsmith#18040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have an appsmith app that has a table view with filtering enabled. If a user tried to filter one of the text fields (eg `Address contains XYZ`), the filter text input loses focus after a short delay after the user stops typing. This is causing UX issues for our users because if they type slowly, they have to click back into the text field to continue typing. It seems possible that the field is losing focus on debounce, tho we are not 100% sure. See the example below

![appsmith-table-filters](https://user-images.githubusercontent.com/109552196/199343420-f767ba71-4fa4-4561-9a2d-cad64dba1908.gif)

### Steps To Reproduce

1. create a table widget with a text field
2. enable filtering
3. try to filter text column and stop typing for a fraction of a second.

### Version

Appsmith Community v1.8.0

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6jdzg)

**Comment by dilippitchika** [comment]
@souma-ghosh can you triage this?

**Comment by souma-ghosh** [comment]
Sure @dilippitchika

**Comment by ame-appsmith** [comment]
[Another Discord user](https://app.frontapp.com/open/msg_1k4nw0ek?key=https://app.frontapp.com/open/cnv_v0d2yoc?key=3s1ZuG1IQPhkEaOgVDn6A8dnYReHhJQh) reported this issue and attached a video.
https://discord.com/channels/725602949748752515/1058171997030453359

https://user-images.githubusercontent.com/101268423/210302753-05fb1787-a43b-490e-8357-883211d164b6.mp4

**Comment by dilippitchika** [comment]
Thanks for the context @ame-appsmith, we will fix this soon.

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/msg_1kytkm4s?key=https://app.frontapp.com/open/cnv_viq358s?key=KHRWQcuX3_VxqPFERnOuFhWsyu8cUAS8) reported this bug.

**Comment by dilippitchika** [comment]
@souma-ghosh please triage this and add estimate to it next

**Comment by souma-ghosh** [comment]
@dilippitchika This is happening because the key for a parent component is changing on changing the filter text. Since key is  changing it causes the child element i.e. the input to re-render and lose focus. Should be a small fix but we should also investigate as to why the key was set like that and whether changing it will cause any issues or not. The current estimate seems fine.

**Comment by dilippitchika** [comment]
@souma-ghosh please pick this up once the date column issue is done
