### ISSUE TITLE
[Bug]: Unable to edit the name of the datasource even through demo user

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to edit the name of the datasource even on logging in with through demo user.

### Steps To Reproduce

View the following video for steps to reproduce.

https://ddpa7mfuvv.vmaker.com/record/b4v6ozxmqW7LuJoY

### Version

http://65.0.99.89/

**Comment by Nikhil-Nandagopal** [comment]
@btsgh please tag these issues to the RBAC epic as well

**Comment by btsgh** [comment]
> @btsgh please tag these issues to the RBAC epic as well

Will do.

**Comment by RakshaKShetty** [comment]
This issue is fixed
