### ISSUE TITLE
[Feature] Recognize base64 encoded string in Image Widget

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1805]
## Summary
If the image widget finds the image source to be a base64 encoded string without the `data:image/png;base64,` prefix, add this prefix automatically, so that the image can be rendered correctly.

## Motivation
An Api can return a base64 encoded string to be used in an image widget without the prefix. This will not allow it to be recognised by the browser as an appropriate image source. Resulting in the image failing to be displayed.

The application can figure this out and prefix `data:image/png;base64,` to the base64 encoded string
to render the image correctly in the image widget.

**Comment by navdeepsingh** [comment]
Hello @riodeuno !! Interested to solve this bug. Can help to assign to me.

**Comment by riodeuno** [comment]
@navdeepsingh Please go for it! We have something similar (not exactly) in the image cells of the table widget, for reference.

Here is a link to the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md)
