### ISSUE TITLE
[Bug]: Even if user has only view permission on Pages, user is able to update the Database through widgets

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user with view permissions on Pages tries to edit the table rows, the cells are editable and database also gets updated (Even though an error pops up with the message that account does not have access)

### Steps To Reproduce

View the video for detailed steps to reproduce the error.
https://ddpa7mfuvv.vmaker.com/record/UuaFbZmpbv4cDlzQ

<img width="1200" alt="Screenshot 2022-11-02 at 10 42 29 AM" src="https://user-images.githubusercontent.com/101863839/199476290-27579d95-7799-429c-9574-884b1b08fe75.png">

### Version

http://65.0.99.89/

**Comment by RakshaKShetty** [comment]
Not a issue
