### ISSUE TITLE
[Bug]: Update operation supported only on  first 12 columns for the pages created using CRUD wizard 

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#18061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/8299030/199526461-7db6be2f-46a1-4493-87a6-613dcdd38e26.mp4

### Steps To Reproduce

1) Create a new page using CRUD wizard
2) Select mysql/PostgreSQL datasource
3) Select a table which has more than 12 columns and create the new page
4) Try to update a column value that is after the 12th column on the newly created page.

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5mf64)

**Comment by Nikhil-Nandagopal** [comment]
@ginilpg this was by design since the CRUD page builder was meant to be more to teach users how to use Appsmith
