### ISSUE TITLE
[Feature] Allow links in a table to be opened in a new window

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1806]
## Summary

Links inside a table should be allowed to open in a new window instead of the same one. 

## Motivation

Users can open multiple links without worrying about navigating away from their app.

**Comment by Nikhil-Nandagopal** [comment]
does cmd + click / right click + open not work here today?

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek closing in favor of #1935
