### ISSUE TITLE
[Bug]: Creating a new workspace does not immediately show up in Admin settings. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a new workspace does not immediately show up in Admin settings. 
It shows up only on refresh. 
It should show up without having to refresh

### Steps To Reproduce

1. Create a new workspace (say Test_Workspace2) from Demo@appsmith.com
2. Go to Admin settings -> Roles
3. Go to a particular role and search for the workspace. 
Note that it is not listed. 
Only on refreshing the page, we can see this new workspace showing up.

Check [this](https://ddpa7mfuvv.vmaker.com/record/RzTilqt6wEzUBV2K) video to note the steps to reproduce (Watch from beginning till 1:22 seconds)

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/RzTilqt6wEzUBV2K

### Version

http://65.0.99.89/

**Comment by trishaanand** [comment]
This is expected as per the current design.
