### ISSUE TITLE
[Bug]: Getting resource not found error on deleting app, with delete and view role for application

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On trying to delete an app with delete and view roles for app from application resources tab , resource not found error is shown
<img width="1440" alt="Screenshot 2022-11-03 at 2 25 00 PM" src="https://user-images.githubusercontent.com/80334441/199681119-c384adde-6627-40ea-aea6-6a3909e97d71.png">

### Steps To Reproduce

1. Login as demo@appsmith.com
2. Create new role by checking Delete and View roles on application resources tab
3. Assign that role to user1
4. Login as user1 and try deleting application 
5. Observe resource not found error is shown

### Version

http://65.0.99.89/

**Comment by RakshaKShetty** [comment]
this issue is fixed
