### ISSUE TITLE
[Bug]: can't sign in when self-host

### ISSUE THREAD

**Issue by allenye0909** [appsmithorg/appsmith#18078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**self-host deploy Community v1.8.6**

+ when i sign up a account successed, and then i sign out , at last i sign in faild. message as follow:It looks like you may have entered incorrect/invalid credentials. Please try again or reset password using the button below.

### Steps To Reproduce

1. sign up a account
2. sign out this account
3. sign in this account, it show me  entered  incorrect/invalid credentials.

### Version

self-host-1.8.6

**Comment by allenye0909** [comment]
thx  for u reply!

**Comment by allenye0909** [comment]
error log as follow:

[2022-11-03 09:15:02,907]  - Operator called default onErrorDropped
backend stdout | reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException: The mapper returned a null value.
backend stdout | Caused by: java.lang.NullPointerException: The mapper returned a null value.
backend stdout |        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
backend stdout |        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout |        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout |        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout |        at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout |        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout |        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout |        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
backend stdout |        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:238)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout |        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
backend stdout |        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout |        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
backend stdout |        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout |        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout |        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout |        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout |        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout |        at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
backend stdout |        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
backend stdout |        at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout |        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout |        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
backend stdout |        at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout |        at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
backend stdout |        at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
backend stdout |        at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
backend stdout |        at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
backend stdout |        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703)
backend stdout |        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
backend stdout |        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
backend stdout |        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
backend stdout |        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
backend stdout |        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
backend stdout |        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
backend stdout |        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
backend stdout |        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
backend stdout |        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
backend stdout |        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
backend stdout |        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
backend stdout |        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
backend stdout |        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
backend stdout |        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
backend stdout |        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
backend stdout |        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
backend stdout |        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
backend stdout |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
backend stdout |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout |        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Nikhil-Nandagopal** [comment]
@allenye0909 could you please share a video of this? Are you sure the credentials are the same as the ones you created as a super admin?
