### ISSUE TITLE
[Docs]: Update Audit Logs Structure

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith#18082]
Combining Audit Logs docs back into a single page; consider redirect links

**Comment by vuiets** [comment]
Going to make a case for the events list alone here again, if I may. It is bound to grow so does it warrant a separate page?

**Comment by spark-c** [comment]
@danciaclara Do you have an opinion for this case?

**Comment by vuiets** [comment]
Thanks @spark-c, @danciaclara just shared why.

**Comment by spark-c** [comment]
Resolved by merged [PR 543](https://github.com/appsmithorg/appsmith-docs/pull/543)
