### ISSUE TITLE
[Feature]: Allow mutation of JS object variables

### ISSUE THREAD

**Issue by ChBrockmann** [appsmithorg/appsmith#18088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hey there,

I was recently reading about the [JS objects inside Appsmith](https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-use-js-object-within-appsmith) and I got quite confused.

In the documentation there are two values `myVar1` and `myVar2` declared which can be used in any component with the syntax `{{myscript.myVar1}}`. Naturally I thought, that I can change these values from functions inside the same JS object, but it didn't work.

So my feature request would be to make these fields mutable.

What I expected or thought was something like this:
```js
export default {
	myVar1: [],
	myVar2: {},
	myFun1: () => {
		myVar2 = {"Test": "Data"}
	},
	myFun2: async () => {
		//use async-await or promises
	}
}
```

### Why should this be worked on?

My Use case was, that I gathered data from three different sources, which should then be displayed on one page. 

After the fetching from different sources, some values need to be adjusted, or calculated. 

Although the data “depends” on another, it does not make sense to store or return it as one big json, because for that it is not related enough.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5nglo)

**Comment by Nikhil-Nandagopal** [comment]
Thanks for the feature request @ChBrockmann ! We do have this tracked here #14568

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 @ApekshaBhosale can we look into solving this?
