### ISSUE TITLE
[Feature]: Sort database tables by name in Datasources list

### ISSUE THREAD

**Issue by MrChrisRodriguez** [appsmithorg/appsmith#18089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

What a database is loaded as a datasource, all of its tables are listed out of order. Since this is a long list, it can make specific tables hard to find. Instead, the list should be alphabetically sorted.

![unsorted list](https://p141.p3.n0.cdn.getcloudapp.com/items/WnuDjwO5/94314e67-fb7c-4f18-823c-f54c81ef8394.jpg?v=4c0119efe362a1bf923ceab2b4604ecd)

### Why should this be worked on?

It'll simplify working with long table lists.

**Comment by Nikhil-Nandagopal** [comment]
@MrChrisRodriguez thanks for the feature request! That does make sense and we're looking into how we can make the schema more discoverable as well

**Comment by rohan-arthur** [comment]
we now have schema sorted and searchable for postgres, mysql, mongo.
![Screenshot 2024-04-15 at 10 43 17](https://github.com/appsmithorg/appsmith/assets/94514895/2cc99900-a1f7-4d1e-ac40-69cbc66e3040)
