### ISSUE TITLE
[Bug]: Postgres coalesce() function crashes Appsmith

### ISSUE THREAD

**Issue by bamboowonder** [appsmithorg/appsmith#18090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This select works correctly:  SELECT * FROM users where coalesce(gender,'') = 'male'

This select fails while typing it in with a toast notification "Cannot read properties of undefined (reading 'status')"
select coalesce(gender,'') as gender from users

while **sometimes** it works with a space after the function:
select coalesce (gender,'') as gender from users

And sometimes with fails with "Internal Server Error"

### Steps To Reproduce

Try to run a postgres version 14 query that includes the coalesce function in the columns select statement

### Version

self 1.8.6  (this has never worked on any version)

**Comment by rohan-arthur** [comment]
hi @babboowonder , this seems to be working now (I am testing on 1.8.13)https://images.zenhubusercontent.com/275993885/358dc569-018e-4b11-830a-738be097f4bd/screen_recording_2022_12_16_at_15_31_22.mov
