### ISSUE TITLE
[Feature] Introduce font sizes+alignment options in the text widget

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1810]
Could we introduce these font sizes+alignment options in the text widget too? They feel like related issues which should be tackled all together. It'll also mean that the text widget doesn't appear inconsistent compared to the table widget options. 
Current list of properties:
<img width="263" alt="Screen Shot 2020-11-18 at 1 16 54 PM" src="https://user-images.githubusercontent.com/30255708/99500406-586d5b00-29a0-11eb-806e-3852c860f4e0.png">

_Originally posted by @areyabhishek in https://github.com/appsmithorg/appsmith/issues/1771#issuecomment-729502237_

**Comment by riodeuno** [comment]
Note:
- The property pane controls are the same for this and the table widget
- The concept of vertical alignment would not exist here when the text widget is scrolling due to overflow in text
