### ISSUE TITLE
[Feature]: rename actions for REST and GraphQL in datasource pane

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#18107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![copy](https://user-images.githubusercontent.com/94514895/199973783-40e57ed3-7d3a-4b75-8be9-a575e99d21fb.png)

rename `Create new API` to `REST API`
rename `Create new GraphQL API` to `GraphQL API`

### Why should this be worked on?

wrong copy, aesthetic issue
https://theappsmith.slack.com/archives/CNQ9Q91C0/p1667562229980929

**Comment by bhuvanaindukuri** [comment]
PR : https://github.com/appsmithorg/appsmith/pull/18114

**Comment by prapullac** [comment]
The issue is tested on the local and looks good to go to release
