### ISSUE TITLE
[Bug]: Upgrading Appsmith has broken the application

### ISSUE THREAD

**Issue by patelbhavinoutlook** [appsmithorg/appsmith#18122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

Appsmith install with docker-compose. Upgraded with below command.

docker-compose pull && docker-compose rm -fsv appsmith && docker-compose up -d

But faced an issue and application does  not start.. 

Logs as below:

As attached..
[backend-73a829f134bd.log](https://github.com/appsmithorg/appsmith/files/9945922/backend-73a829f134bd.log)

Docker Compose file :
version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: artwebappsmithsvr
    ports:
      - "127.0.0.1:5679:80"
      - "127.0.0.1:5680:443"
      - "127.0.0.1:5684:9001"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
  #   # Uncomment the lines below to enable auto-update
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"

  # auto_update:
  #   image: containrrr/watchtower:latest-dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   # Update check interval in seconds.
  #   command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #   restart: unless-stopped

### Steps To Reproduce

1. Ubuntu 20.04
2.  Aapanel installed (if it has any issues)
3.  Trying to upgrade to 1.8.7 from 1.8.4

### Version

1.8.7

**Comment by jguce-supportninja** [comment]
also experienced this

**Comment by pranavkanade** [comment]
@jguce-supportninja can you please upgrade to v1.8.8? We've released a patch fix for this issue.
