### ISSUE TITLE
[Bug]: js/sql not execute on page load

### ISSUE THREAD

**Issue by findzhangvvv** [appsmithorg/appsmith#18124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I define a variable in the js action and the name of the js file is repeated, the js/sql will not be executed when the page is loaded. This is not necessarily repeated, but most of the time my web page cannot load data. I checked and read the appsmith code, and now I have some conclusions
1. I defined a tableData variable in the js func that is consistent with the name of the js file. When I update the js file. I read the back-end code and found that PageLoadActionUtilCEImpl constructDAG edges formed a circular dependency, because the edge already exists in the DAG, and this error is reported. Edge would induce a cycle, resulting in the dependency between the page and variables can not be correctly resolved, thus setting layoutOnLoadActions to an empty array;
2. I read the front-end code and found that when the page is loaded, the front-end will send a request according to the data of "layoutOnLoadActions" in the data returned by the back-end interface/api/v1/pages/{{pageId}}. This field probably returns those actions that are executed when the page is loaded. When circular dependency occurs, this layoutOnLoadActions is empty, resulting in no request from the front-end
3. The current scenario is
    a. Cyclic dependency occurs when variables and js files have the same name
    b. Circular dependency also occurs when strings have the same name as js files
4. My current solution is not to define variables/strings with the same name as the js file in the js file. It seems that it can solve this problem

### Steps To Reproduce

<img width="960" alt="image" src="https://user-images.githubusercontent.com/117616816/200223093-bb836cbe-3ffc-48c6-a71c-40dbdc6e580a.png">

The screenshot is here
I'm not sure whether this is a mistake. If so, please let me know. Thank you

### Public Sample App

no url

### Issue video log

no url

### Version

release-v1.8.4

**Comment by riteshkew** [comment]
@findzhangvvv You have come to the right conclusions and we are actively working on resolving these cyclic dependency errors. You can find more details on the epic here #17047. Your current workaround is the way to go until the changes are pushed to production.
