### ISSUE TITLE
[Bug]: DatePicker Display Issue in Table Widget Column Filters

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#18139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to apply a filter on a **Date** column of a Table widget, the date picker is displayed inside the filter pop-up and is not completely visible (see screenshots).
![image](https://user-images.githubusercontent.com/101268423/200940649-52836ac4-ea20-4a07-a139-2c7db634573b.png)
![image](https://user-images.githubusercontent.com/101268423/200940724-f10f4256-0124-4676-9773-f35c92ba68d4.png)

### Steps To Reproduce

1. Add a Table widget and populate it with data, making sure you have at least a column of type **Date**.
2. Try to add a filter on the date column, using the built-in filters of the Table widget.
3. Note how the datepicker gets displayed.

### Version

Cloud v1.8.7-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5qh58)

**Comment by dilippitchika** [comment]
@souma-ghosh i think this is a small issue, can you fix this with the date editing support?

**Comment by souma-ghosh** [comment]
Right now this is not reproducible on release
