### ISSUE TITLE
[Bug]: Unable to use some identifiers

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#18147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Appsmith, we are unable to use any identifiers that are already there inside [evaluate.ts](https://github.com/appsmithorg/appsmith/blob/14159c5593ea15945a0772ed6b5fa43c6d4f34af/app/client/src/workers/Evaluation/evaluate.ts) file since they are exposed to `evaluate` function. This leads to a lot of reserved keywords inside Appsmith.

https://user-images.githubusercontent.com/10436935/201354785-7a335004-1226-46f1-894b-9d437117274a.mov

### Steps To Reproduce

Add a binding with the global identifiers that we have on evaluate.ts file. example: `topLevelWorkerAPIs`,  `dataTree`,`beginsWithLineBreakRegex.toString()` etc.

### Version

cloud

**Comment by satbir121** [comment]
@Rishabh-Rathod Is there a quick fix for this?

**Comment by satbir121** [comment]
@aswathkk Can you please help us document all of the identifiers?

**Comment by Rishabh-Rathod** [comment]
Replacing `eval` with the `new Function()` constructor should resolve the above issue. I can notice something similar was tried earlier and reverted back here https://github.com/appsmithorg/appsmith/pull/5851/files#r1028856641. 

Waiting for @hetunandu's reply to understand the reason for the reversion.

**Comment by arunvjn** [comment]
This should be resolved with https://github.com/appsmithorg/appsmith/pull/17832

**Comment by Rishabh-Rathod** [comment]
> This should be resolved with #17832

Yes, indirect eval is a better way of solving it considering that would not need any change in the current eval script.

**Comment by Rishabh-Rathod** [comment]
@satbir121 Above PR to close this issue is not yet merged, was this issue closed by mistake?
