### ISSUE TITLE
[Bug]: Internal server error, password reset

### ISSUE THREAD

**Issue by juandl** [appsmithorg/appsmith#18149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/25650720/201526624-08fd9f6e-9adb-4744-b5f4-18b16079e67a.png)

### Steps To Reproduce

1. Request reset password
2. Click on the link email
3. Type the new password and submit
4. Error Internal appears

### Version

Self Hosted -  1.8.8

**Comment by sharat87** [comment]
This is the same error as in #18086.
