### ISSUE TITLE
[Bug]: Connection with Github got stuck and I can't Deploy new changes

### ISSUE THREAD

**Issue by ofsantana** [appsmithorg/appsmith#18145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Once an App is connected to Github, if I return to that app several days after the successful connection and make some changes, the screen to Commit the changes got stuck and I can't commit and of course release the new changes, the only thing that works is to disconnect the app from Git.

### Steps To Reproduce

I'm attaching a Loom video so you can see how to reproduce the error.
Thank you.

### Issue video log

https://www.loom.com/share/ea45096dc1be48b8827b701b41c100cd

### Version

Self Hosted / Appsmith Community v1.8.7

**Comment by AnaghHegde** [comment]
@ofsantana Apologies for the delayed response. Could you please share the logs from the machine where the Appsmith instance is running?

**Comment by AnaghHegde** [comment]
@ofsantana Are you still facing the issue? I will be closing the issue for the time and feel free to reopen the issue if you face the issue.
