### ISSUE TITLE
[Bug]: currentRow is undefined Inside the Options Property of a Select Column of a Table Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#18148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user has an editable **Select** column inside a **Table** widget. If trying to use `currentRow` inside the **Options** property of the **Select** column, the error `currentRow is undefined` displays, hence it is not possible to conditionally set the **Options** of the **Select** column based on other values from the current row of the table.
![image](https://user-images.githubusercontent.com/101268423/201374180-c83cd1c3-a818-4dc4-bbec-79f9471d853e.png)

### Steps To Reproduce

1. Add a Table widget and populate it with data.
2. Make one of the columns editable and set its type to **Select**.
3. Try to use `currentRow` inside the Options field of the Select column settings.

### Version

Appsmith v1.8.7-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/msg_1grm3vik)

**Comment by chandannkumar** [comment]
Tested this Issue and working as expected
- Tested currentRow functionality inside the options property of select column

**Comment by Nikhil-Nandagopal** [comment]
@chandannkumar it doesn't seem to be working for me. Which DP did you test it in?

**Comment by chandannkumar** [comment]
@Nikhil-Nandagopal I tested the fix on this DP: https://appsmith-git-feat-currentrow-access-select-options-get-appsmith.vercel.app/
The current vercel DP link seems broken now @sbalaji1192

**Comment by sbalaji1192** [comment]
@chandannkumar triggered another vercel dp - https://appsmith-grse0j68l-get-appsmith.vercel.app/applications

**Comment by sbalaji1192** [comment]
@chandannkumar Could you perform a regression on this issue? I have made some changes to fix a failing cypress test case.

**Comment by chandannkumar** [comment]
Re-Tested this issue and LGTM
