### ISSUE TITLE
[Feature]: [Custom JS Lib] Create empty controller

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#18155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Create a controller class so that the following endpoints can added later - add, delete, fetchAll.

### Why should this be worked on?

To enable custom JS lib feature.

**Comment by OladapoAjala** [comment]
Hi @sumitsum are you looking to create a template class that is reusable when implementing controllers?
