### ISSUE TITLE
[Bug]: Conflict in ports with RTS and App Server

### ISSUE THREAD

**Issue by juandl** [appsmithorg/appsmith#18154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If we change the PORT env on docker there's a conflict with RTS and App server as both have the same env name

App Server
https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/resources/application.properties#L1

RTS Server
https://github.com/appsmithorg/appsmith/blob/release/app/rts/src/server.ts#L39

```
appsmith                | rts stdout | Error: listen EADDRINUSE: address already in use :::8081
appsmith                | rts stdout |     at Server.setupListenHandle [as _listen2] (net.js:1331:16)
appsmith                | rts stdout |     at listenInCluster (net.js:1379:12)
appsmith                | rts stdout |     at Server.listen (net.js:1465:7)
appsmith                | rts stdout |     at Object.<anonymous> (/opt/appsmith/rts/server.js:59:8)
appsmith                | rts stdout |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
appsmith                | rts stdout |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
appsmith                | rts stdout |     at Module.load (internal/modules/cjs/loader.js:950:32)
appsmith                | rts stdout |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
appsmith                | rts stdout |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
appsmith                | rts stdout |     at internal/main/run_main_module.js:17:47
appsmith                | rts stdout | Emitted 'error' event on Server instance at:
appsmith                | rts stdout |     at emitErrorNT (net.js:1358:8)
appsmith                | rts stdout |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
appsmith                | rts stdout |   code: 'EADDRINUSE',
appsmith                | rts stdout |   errno: -98,
appsmith                | rts stdout |   syscall: 'listen',
appsmith                | rts stdout |   address: '::',
appsmith                | rts stdout |   port: 8081
appsmith                | rts stdout | }
appsmith                | rts stdout |
```

### Steps To Reproduce

1. Add "PORT=8081" to the docker
2. Run the app 

### Version

Self Hosted -  1.8.8

**Comment by Nikhil-Nandagopal** [comment]
@pratapaprasanna @sum35h could you have a look?

**Comment by sharat87** [comment]
Hey @juandl, nice catch, thank you for raising. The support for `PORT` env variable in both the backend server, and the RTS, is for use during dev time. In the Appsmith Docker container, there's a few places where we _assume_ that the backend server and RTS are started with the default ports inside the container. Since the container is expected to be run in a network namespace, this should usually be fine.

Is there a particular reason you are looking to set the `PORT` env variable on the Appsmith container?

**Comment by juandl** [comment]
> Hey @juandl, nice catch, thank you for raising. The support for `PORT` env variable in both the backend server and the RTS, is for use during dev time. In the Appsmith Docker container, there are a few places where we _assume_ that the backend server and RTS are started with the default ports inside the container. Since the container is expected to be run in a network namespace, this should usually be fine.
> 
> Is there a particular reason you are looking to set the `PORT` env variable on the Appsmith container?

I'm trying to change the port of the App Server, which is defined here https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-server/src/main/resources/application.properties#L1

but as soon as I change the port, it gets changed too on the RTS and the docker is trying to run RTS and APP Server on the same port. if you see "Error: listen EADDRINUSE: Address already in use :::8081" is coming from RTS

I'm trying to use this ENV because we are trying to run appmisth on "https://github.com/nginx-proxy/nginx-proxy"

**Comment by sharat87** [comment]
Hey @juandl, thank you for the details, and sorry for the delay in response here.

I understand that both server and RTS use `PORT` env variable, and this is not a bug. The `PORT` env variable is not intended to be set to a custom value when running the Appsmith Docker container.

The Appsmith Docker container has an NGINX proxy running inside of it, that'll route requests to RTS or the server, based on the path of the request.

If you want to setup another NGINX reverse proxy in front of Appsmith container, please start Appsmith container with a _single_ port binding and configure NGINX to proxy to that port.

Like, for example, if you want to use port 7000 for this, start Appsmith like this:

```bash
docker run -d -p 7000:80 -v "$PWD"/stacks:/appsmith-stacks appsmith/appsmith-ce
```

Then, you can have a `location` block in your NGINX config, something like this:

```nginx
location / {
  proxy_pass http://localhost:7000;
}
```

This would mean that your NGINX will pass requests to whatever is listening on port 7000. The `docker run` command above will mean that the Appsmith container, and in effect, the NGINX _inside_ the Appsmith container, will be listening on port 7000, and routing requests to the Java server or the RTS depending on the path. You shouldn't need to change the `PORT` environment variable.

**Comment by sum35h** [comment]
@sharat87  @pratapaprasanna  This port conflict is turning up in Paas like Azure app service and Herkou, because their runtime uses the same env var PORT.

**Comment by sum35h** [comment]
Update: Turns out that the conflict is actually between the RTS and the NGINX server (which also uses PORT)
