### ISSUE TITLE
[Docs]: Add documentation for setTimeout framework function

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#18163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

setTimeout framework function was added recently and relevant documentation should be added

### Describe the improvement

https://github.com/appsmithorg/appsmith/pull/17445

**Comment by danciaclara** [comment]
@arunvjn Could you please share the first draft with us for this function?

**Comment by jnikhila** [comment]
> @arunvjn Could you please share the first draft with us for this function?

@satbir121 / @riteshkew - Could you please help us get the first draft for this?

**Comment by arunvjn** [comment]
@danciaclara @jnikhila  `setTimeout` implementation in Appsmith is same as that of the browser. 
We can take inspiration from setTimeout docs on [mdn](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout).

**Comment by jnikhila** [comment]
Thanks @arunvjn for sharing this. I couldn't see the `setTimeout` function as part of actions to bind it on a say button click. However, it's available in JS Object, or if I bind it to button click by enabling a JS label. Please let me know if this understanding is correct. Could you please also share an example why the function was introduced that will help us understand it better?

**Comment by jnikhila** [comment]
Thanks @satbir121 for your help.

Here's a quick summary on the discussion:

> The `setTimeout()` works similar to `setInterval()` only the difference is it is executed once. You could use the `setTimeout` in JS objects, Property pane for widgets like 'onClick, onRowChanged etc'. However, can't be used for visible/disabled properties, and in Queries/API.

@satbir121 - Please add if I've missed anything.

**Comment by spark-c** [comment]
[PR available here](https://github.com/appsmithorg/appsmith-docs/pull/673)

**Comment by spark-c** [comment]
Should be ready to merge very soon pending final review / confirmation
