### ISSUE TITLE
[Docs]: Add documentation for postWindowMessage framework function

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#18162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

[This](https://github.com/appsmithorg/appsmith/pull/14925) PR introduces `postWindowMessage()` function to Appsmith and requires related documentation added to the repo

### Describe the improvement

![image](https://user-images.githubusercontent.com/79509062/201699514-6ca58863-0e99-4a20-871b-7a6ef71be2d8.png)

**Comment by jnikhila** [comment]
@ramsaptami - could you please verify if this is a duplicate of #14723?

**Comment by ramsaptami** [comment]
Yep, this is a duplicate. Closing this in favour of the previous ticket
