### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by hillyzhu** [appsmithorg/appsmith#18171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The Mysql plugin does not use the connection pool, unlike Postgres Plugin using the HikariPool

### Why should this be worked on?

For better performance, it is suggested that the Mysql Plugin can use the connection pool

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #17481 and #8419
