### ISSUE TITLE
[Task]: Make widget selection happen if the URL changes

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#18173]
## Description

Widget selection is a complicated feature. Depending on how and where a selection happens, the system handles and controls differently. There is also a hierarchy in widgets with containers, hidden via UI states with modals and tabs, and ability to select multiple widgets at once. 

Overtime we have added a lot of these features in a way that there is not a single way for the platform to select a widget. There are also specialised methods for different places that facilitate widget selection. Tabs widget is has an old issue regarding this 

We need to achieve the following:

- Have a streamlined way to select widget(s)
- Make widget selection work with browser back/forward buttons
- Have a single way to select/focus on any entity of Appsmith

### Solution
Refactor the widget selection to make it easier to select a widget. Make it as easy as it is to navigate to an action/datasource. Make selection happen via a url navigation so that browser navigation can work with platform navigation.

### SubTasks

- [x] #19570
- [x] #19571
- [x] #1282

**Comment by Richarex** [comment]
- [ ] Modal widget property pane is still displayed on the canvas when the user clicks on it. Please refer the attached video:- https://jIju8JbmWA.vmaker.com/record/sZpXijZ47Ds34SUB
