### ISSUE TITLE
[Bug]: Cursor icon on hover to 'Filters', 'Download' & 'Add new row' buttons of Table widget is a text edit cursor on view mode

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#18189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On hovering to buttons on  'Filters', 'Download' & 'Add new row' buttons of Table widget, the cursor should be visible with Hand cursor instead of text edit cursor

### Steps To Reproduce

1. Drag & Drop Table widget
2. Deploy the app
3. Hover on Filter & Download
4. Observe that the cursor icon is text edit cursor instead of hand cursor

### Issue video log

https://www.loom.com/share/b11ac766257f4418b5449b730d8f3249

### Version

cloud / release

**Comment by shadabbuchh** [comment]
The cursor icon in Edit mode is also not appropriate.
https://www.loom.com/share/9286b7b064f847d999bd0abe3626aa76
