### ISSUE TITLE
[Bug]: Encountered a exception using the FilePicker

### ISSUE THREAD

**Issue by ScjpCoder** [appsmithorg/appsmith#18182]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

 An exception occurred when I used the file selector to upload files larger than 5MB.
It seemed to be due to blob address concatenation. 
<img width="573" alt="Snipaste_2022-11-16_13-45-02" src="https://user-images.githubusercontent.com/45224663/202096529-d7bf2e75-baa7-42e4-abe2-2171517c7b3b.png">

### Steps To Reproduce

1. Open the console of the Chome.
2. Upload a file larger than 5MB.
3. Trigger the file upload request.
4. View the information printed on the Chome console.

### Version

1.8.8

**Comment by Nikhil-Nandagopal** [comment]
HI @ScjpCoder . This is related to #18245
