### ISSUE TITLE
[Bug]: Unable to delete the checkbox group items inside the list widget

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#18191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/10436935/202157515-7c98082f-9e38-49aa-8336-29dc868875ba.mov

Unable to delete the checkbox group item when the checkbox group widget is inside a list widget.

#### Edit
This also is being observed in Dynamic Height DP where we are unable to open the dropdown on the first click

https://user-images.githubusercontent.com/10436935/202455642-c3369d3d-8a8e-4139-89ad-45be07719f2a.mov

### Steps To Reproduce

1. DnD a list widget
2. Place a checkbox group widget inside the list widget
3. Try to delete checkbox group items

### Version

v1.8.7-SNAPSHOT

**Comment by aswathkk** [comment]
This looks like a bug came up due to the context-switching project's code which changes the focus when we click on some property controls. So, changed the label

**Comment by Richarex** [comment]
Both the issues are fixed, verified it on release. Able to delete the checkbox group items from the list widget & is able to open the dropdown on first click for dynamic height.

**Comment by Sripriya93** [comment]
Verified both issues, working fine, removing QA.
