### ISSUE TITLE
[Bug]: Issue with evaluation of pageSize with list v1 on reload

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#18206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/bf95456e9b064835895eaede04daa4cf

### Steps To Reproduce

1. Dnd a List widget 
2. Dnd a text widget and bind it with List page size to check the exact page size.
3. Move to another page say Postgres Query and add binding {{List1.pageSize}}
4. refresh the page and check the results in the query (You will see pageSize is coming as 2 instead of 3) but in the main canvas the pageSize is coming as 3 only
For more details check LOOM

### Version

Production

**Comment by dilippitchika** [comment]
@ashit-rath @Tooluloope please triage this in the current sprint and let me know if it's happening in v2

**Comment by ashit-rath** [comment]
@dilippitchika This is a v1 issue and we created this for tracking regression for v2. This does not happen in v2

**Comment by dilippitchika** [comment]
@ashit-rath got it, then can you link this in v2 bugs which will close once it goes live?
