### ISSUE TITLE
[Bug]: SaaS Integrations are missing on new deployments (Airtable, Twilio, HubSpot)

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#18209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When raising an instance either in docker-compose or in DigitalOcean, the `Airtable, Twilio, HubSpot` data sources do not appear.

[Logs](https://www.udrop.com/7yme/backend-8f1dd3092952.log)
[Performance log](https://www.udrop.com/7ymg/Profile-20221116T114955.json)

![image](https://user-images.githubusercontent.com/114161539/202241032-fba46c4c-08e0-432c-8d45-6813b2453525.png)

### Steps To Reproduce

1. If you have an active docker instance of Appsmith clear all the cache and update it to the latest version.
2. Once the version of the instance is updated and the cache is cleared, execute the instance.
3. Navigate to Data source and notice that the following API data sources `Airtable, Twilio, HubSpot` are not listed.
4. Create an instance from Appsmith's DigitalOcean marketplace and notice that the data sources don't appear  `Airtable, Twilio, HubSpot.` 

### Version

Self-hosted 1.8.8
Self-hosted 1.8.6

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5v6vg)

**Comment by felix-appsmith** [comment]
Appsmith Cloud seems to be working as expected. Tested some existing queries/apps and all of them work fine (HubSpot).

**Comment by felix-appsmith** [comment]
Added a link to the logs on the description.

**Comment by felix-appsmith** [comment]
We conducted an investigation where we found the following information.

We make a query to the Mongo database that has the plugins. It does not contain Airtable, Twilio, HubSpot.
![image](https://user-images.githubusercontent.com/114161539/202490071-0c72a9ac-509e-4a8c-b68f-f30d8172fe43.png)



We reviewed the relevant logs and found the following error in
cs.appsmuith.com
download the logs [here](https://www.udrop.com/7yuh/cs.appsmith.log)

![image](https://user-images.githubusercontent.com/114161539/202490235-30e3fd44-bf0e-4dd9-87fd-cab4c23af5b6.png)

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur @sumitsum can we fix this asap?

**Comment by rohan-arthur** [comment]
@felix-appsmith was this working before? If it's a regression, we can even mark it is critical

**Comment by felix-appsmith** [comment]
@rohan-arthur Yes this worked before

**Comment by nidhi-nair** [comment]
Potentially fixed in #18440 , will close the issue after confirming that this is reflected in the Docker image after promoting to master.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair closing it because it seems to be working on our end.
@felix-appsmith could you please re-verify?

**Comment by felix-appsmith** [comment]
It works well.

**Comment by felix-appsmith** [comment]
@Nikhil-Nandagopal 
This bug was solved before, but it broke again, it presents the same behavior, this problem is related to this other one.
https://github.com/appsmithorg/appsmith/issues/18211

**Comment by felix-appsmith** [comment]
Current version where is the problem: `1.9.5` Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@sbalaji1192 @nidhi-nair why does this keep breaking?

**Comment by sbalaji1192** [comment]
@sribalajig Please check the above comment.

**Comment by felix-appsmith** [comment]
This [user](https://app.frontapp.com/open/cnv_wao86a4?key=8H1SCc_wFf5GgCUBAOXlObr86LxBPszh) is being affected by this problem

**Comment by felix-appsmith** [comment]
![image](https://user-images.githubusercontent.com/114161539/216110515-b6f43d92-918e-4235-879f-517f046d538c.png)

**Comment by felix-appsmith** [comment]
It was solved
