### ISSUE TITLE
[Bug]: Generating Page with Data by connecting to a new datasource, from an existing page causes an error.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to generate page with data, by connecting to a new datasource, and choose say a sample datasource like movies or users (mongo/postgres), on selecting a table and clicking on Generate Page - an error pops up as below. 

<img width="1204" alt="Screenshot 2022-11-16 at 5 12 29 PM" src="https://user-images.githubusercontent.com/101863839/202179796-78d9eb24-50e8-4492-ab03-7ee4da1f0428.png">

### Steps To Reproduce

1. Open an existing application
2. Go to an existing page within the application
3. Click on the + sign next to Pages, and choose Generate Page With Data
4. Choose connect new data source in the Select Data source dropdown
5. Select users or movies from sample database
6. Choose an appropriate table
7. Click on Generate page
8. An error pops up - Unable to Process Page Generation request

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/GFvgdyG8L82pztda

### Version

Production

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 @akash-codemonk this seems like a bug in the new flow we introduced. How did this get missed in testing?

**Comment by NilanshBansal** [comment]
@kocharrahul7 @ginilpg @Nikhil-Nandagopal The `Generate Page With Data` implementation right now, is adding the data and widgets to the currently selected page, not to a new page.
Hence, when the current page's canvas area is not empty, the error `Unable to process page generation request, please use empty layout` is displayed, as there is no space on the canvas to add the generated widgets.
On the other hand, when a new page with an empty canvas area is used, the `Generate Page With Data` adds the data and widgets to the same selected page.
Is this the intended functionality or the `Generate Page With Data` should directly create a new page with the data populated widgets?

**Comment by Nikhil-Nandagopal** [comment]
@NilanshBansal this is weird. It should do it on a new page and not the current page.

cc: @kocharrahul7

**Comment by Richarex** [comment]
This is working fine, able to generate new page by connecting to a new datasource. Verified it on dp url.
![image.png](https://images.zenhubusercontent.com/62badfdc6f3cdb34fefec47e/dbb8089b-d69c-4ec5-a65c-ac28ae63c0b2)

**Comment by Richarex** [comment]
**Test Cases**
1. Verify that user is able to generate page with data, by connecting to a new datasource from an existing page.
**Expected Result**
It should generate page with data, from an existing page without any errors and all the tables added should work properly.
2. Verify that user is to generate page with data by connecting to new datasource from adding new page
**Expected Result**
It should generate page with data, from a new page by connecting to new datasource without any errors.
