### ISSUE TITLE
[Bug]: Select All text is darker than the rest of the options on disabling the checkbox group widget

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I disable the checkbox group widget, which has the Select All Options enabled, the Select All text is darker than the rest of the options.

### Steps To Reproduce

1. Drag and drop a checkbox group widget and add a few more options to it
2. Enable the Select All option for this from the property pane
3. Make the Disable toggle on
4. Note that the color of Select All text in the widget is darker than the rest of the options texts.
5. Same behavior is noted on canvas, preview as well as deploy mode. 
<img width="530" alt="SelectAllDarker" src="https://user-images.githubusercontent.com/101863839/202236670-7a610236-7edc-4acd-b853-1226c16bf5fc.png">

### Version

Production

**Comment by s-ashwin** [comment]
I think the labelTextColor check is now happening based on the prop **disabled**. which has to be replaced by **isDisabled**

Correct me if i am wrong

`<CheckboxLabel
          alignment={AlignWidgetTypes.LEFT}
          className="t--checkbox-widget-label"
          disabled={isDisabled}
          labelTextColor={disabled ? Colors.GREY_8 : "inherit"}
        >
          Select all
        </CheckboxLabel>`
        
`<CheckboxLabel
          alignment={AlignWidgetTypes.LEFT}
          className="t--checkbox-widget-label"
          disabled={isDisabled}
          labelTextColor={isDisabled ? Colors.GREY_8 : "inherit"}
        >
          Select all
        </CheckboxLabel>`

**Comment by royalpinto007** [comment]
Hello, can you please assign this issue to me?

**Comment by somangshu** [comment]
Greetings @royalpinto007, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and request us for a review here.

**Comment by royalpinto007** [comment]
Sure, will try me best to contribute at my earliest @somangshu

**Comment by royalpinto007** [comment]
Can you please share the path in which code is present, so that I can look into it? @somangshu

**Comment by dilippitchika** [comment]
@royalpinto007 this should be a change in app/client/src/widgets/CheckboxGroupWidget

**Comment by royalpinto007** [comment]
Great, let me just go through it. I was a bit busy for the last 2 days, sorry for that.

**Comment by royalpinto007** [comment]
I am unable to locate the code for other colors in the files. Could you assist me in finding it? @dilippitchika

**Comment by ArjobanSingh** [comment]
Hey @somangshu,
I've found the reason for this bug, Can you please assign it to me? I will raise a PR swiftly.

**Comment by somangshu** [comment]
Greetings @ArjobanSingh , thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and request us for a review here.

**Comment by ArjobanSingh** [comment]
Hey @somangshu ,

Raised a [PR](https://github.com/appsmithorg/appsmith/issues/20035) fixing this issue, can you please review it. And I've also raised a [PR](https://github.com/appsmithorg/appsmith/pull/19994) resolving the issue #18880 present in SelectAll component in Checkbox. Although I am not able to request any reviewers there, so can you please review that other PR as well?

Thanks

**Comment by somangshu** [comment]
Thanks @ArjobanSingh for working on this swiftly

@jsartisan is going to review your changes, we will try and merge this soon
