### ISSUE TITLE
[Feature]: Possibility to set ingressClassName for ingress resource for Kubernetes

### ISSUE THREAD

**Issue by crashev** [appsmithorg/appsmith#18207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, it's not possible to set ingressClassName for ingress resource. 
See: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
Empty in:
```
get ingress
NAME                  CLASS                  HOSTS                          ADDRESS        PORTS   AGE
appsmith-1668612629   <none>                 appsmith.oms.westwing.eu       10.144.187.9   80      30m
```

CLASS = none

We should be able to specify ingressClassName according to new versions specification like:
```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "appsmith.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "appsmith.namespace" . }}
  labels:
    {{- include "appsmith.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
     ingressClassName: {{ .Values.ingress.className }}
```

### Why should this be worked on?

It's being deprecated and later removed, so this will be a blocker for installing Appsmith in newer versions of Kubernetes.

See also: https://kubernetes.github.io/ingress-nginx/

section "What is an IngressClass and why is it important for users of Ingress-NGINX controller now ?"

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5y4p8)

**Comment by ErlendFax** [comment]
I have the same problem. Isn't this a bug? Since `ingress.className` is present and all?

**Comment by ErlendFax** [comment]
My *might* have been related but not sure. I couldn't get HTTPS working, and I thought it had to do with not being able to set the ingressClass. 

This is what I didn't to get it working:

https://community.appsmith.com/t/cant-configure-https-with-helm/1656/2

Still can't set ingressClass with appsmith Helm chart, but I got everything up so I'm happy for now.
