### ISSUE TITLE
[Task] - Change design system components gray colors and border radius

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#18215]

**Comment by albinAppsmith** [comment]
Change design system component gray colors to the new scale and change border radius to 4px.

https://www.figma.com/file/4aZWeRRAyIBX660EbIQhXn/DS-Upgrade-Exploration?node-id=1055%3A41500&t=tVdutHj64vOvvdfk-0

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
