### ISSUE TITLE
[Bug]: Version v1.8.5  By clicking on the 'A' entry in the table and then directly clicking the Modify button in the 'B' entry, the selectRow action does not get the data for the B entry, but for the 'A' entry

### ISSUE THREAD

**Issue by jeromelonglong** [appsmithorg/appsmith#18234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Version v1.8.5

By clicking on the 'A' entry in the table and then directly clicking the Modify button in the 'B' entry, the selectRow action does not get the data for the B entry, but for the 'A' entry

### Steps To Reproduce

Version v1.8.5

By clicking on the 'A' entry in the table and then directly clicking the Modify button in the 'B' entry, the selectRow action does not get the data for the B entry, but for the 'A' entry

### Version

v1.8.5

**Comment by Nikhil-Nandagopal** [comment]
@jeromelonglong this is the expected behavior. Clicking a button won't select a row in the table. If you want to get the row that was clicked, you can use `Table1.triggeredRow`
