### ISSUE TITLE
[Epic]: Problems Uploading Large Files

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#18245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to upload a file to a database that is larger than 20mb the file upload fails, this problem happens with different sizes for different users for some user the file upload fails when it is larger than 5mb but another when it is larger than 20mb this doesn't make much sense.

To get a better idea of this issue, create a repository with the tests that have been done.

[appsmith-problems-uploading-large-files](https://github.com/felix-appsmith/appsmith-problems-uploading-large-files)

Apart from this, here I attach issues that are related to the issue.

1. [Base64 files larger than 5 Mb fail to display in Appsmith](https://github.com/appsmithorg/appsmith/issues/17635)
2. [Upload of files larger than 5mb fails when changing port](https://github.com/appsmithorg/appsmith/issues/17816)
3. [Not able to upload files greater than 75 mb](https://github.com/appsmithorg/appsmith/issues/14293)
4. [How to increase Filepicker upload size on self-hosted](https://github.com/appsmithorg/appsmith/issues/14232)
5. [Issue with video uploads to S3 with files greater than 5MB](https://github.com/appsmithorg/appsmith/issues/11137)
6. [Increase the filepicker supported size on cloud](https://github.com/appsmithorg/appsmith/issues/11654)

### Steps To Reproduce

1. Enter this application: [app](https://app.appsmith.com/app/filesuploaderror/page1-636914a6b7d12f577aa56521)
2. Try to upload a video larger than 25mb

### Public Sample App

https://app.appsmith.com/app/filesuploaderror/page1-636914a6b7d12f577aa56521

### Version

Cloud : Appsmith v1.8.7-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_67d1o)

**Comment by tomjose92** [comment]
Another user reported facing this error while trying to upload a file larger than 50mb.

**Comment by AnaghHegde** [comment]
I have one more user who wants to upload large files( > 100mb ). Is there any workaround for this.

**Comment by dilippitchika** [comment]
Limitations
-  Spring in memory limit, 
- plugin specific limit
- and a few more things

If we are going to allow >100MB, we'll need to test and verify that it actually works

More context  -https://theappsmith.slack.com/archives/CGBPVEJ5C/p1669722874855689?thread_ts=1669700677.989409&cid=CGBPVEJ5C

**Comment by ereio** [comment]
Just adding as another example, we have files that are upwards of 300mb that we need uploaded.

**Comment by dilippitchika** [comment]
@ereio can you also add your use-case on why these large files need to be uploaded in your app? How is appsmith going to help here?

**Comment by ereio** [comment]
@dilippitchika For sure!

We have tool where management is going to upload large statement files instead of pulling them from where we normally do automatically. We don’t want to build a webpage outside appsmith that’s only for management to drag and drop large files to upload.

We have an API endpoint that can handling uploading very large files through multipart requests, and were hoping AppSmith could help us build out the UI part.

**Comment by pfilatov92** [comment]
> If we are going to allow >100MB, we'll need to test and verify that it actually works

Are you going to allow >100MB finally? We also need this for uploading video files in our admin panel

**Comment by dilippitchika** [comment]
Hey @pfilatov92 if you can help me understand your use case better, it will help us prioritise. Can you let me know what your users are doing next after uploading video files? What is their flow like?

**Comment by pfilatov92** [comment]
@dilippitchika We choose video files via admin panel, attach some meta-information, then video is uploading to s3 through our backend and then becomes available on our website

**Comment by Nikhil-Nandagopal** [comment]
@pfilatov92 we're working on this soon. Currently, it's a backend limitation with how we process these files. We're working on making it so that the system can upload larger files.

**Comment by ereio** [comment]
@nidhi-nair wanted to see what PR will / has fix this issue! This is still a big blocker for us!

**Comment by devdoshi** [comment]
This is the main blocker stopping me from moving an app to appsmith. 

My users need to upload PDF files that can be hundreds of megabytes. I'm uploading to Dropbox, which has a separate API flow for large uploads, so all the file input needs to do is allow the user to select files and I do the rest with javascript. I believe the Filepicker has all the functionality I need (based on https://docs.appsmith.com/connect-data/how-to-guides/how-to-integrate-dropbox), except I can't override the file size limit. It seems like the use case of "use appsmith to handle uploads" vs "use dropbox or some other host" are stuck in the same widget which is maybe causing issues -- maybe there should be 2 different ones? 

What is the recommended escape hatch for this kind of situation? In the meantime I've embedded an iframe with some html and javascript which can handle the upload process, but I have to host that code outside of appsmith so it's not ideal.

**Comment by GreenFlux** [comment]
@devdoshi are you using Appsmith Cloud, or your own self-hosted instance? If self-hosted, what version are you running?

**Comment by devdoshi** [comment]
> @devdoshi are you using Appsmith Cloud, or your own self-hosted instance? If self-hosted, what version are you running?

Appsmith cloud

**Comment by GreenFlux** [comment]
@devdoshi there's no way to increase the 100 Mb limit on Appsmith cloud. I think you might be able to increase it on a self-hosted instance though. I think your approach using an iframe is the only way around the limit on Appsmith cloud.

**Comment by leonlazic** [comment]
I too thave the same problem. I am developing an application for medical purposed and I need a functionality to upload large files like videos, ctct scans, 3d files ...
I am using Firebase Storage as the backend.
