### ISSUE TITLE
[Bug]: Deploy App - Resource Not Found

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#18252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On clicking the Publish App button, an error message pops up showing `Resource Not Found`
You can find the app [here](https://app.appsmith.com/app/false-alarms-app/login-page-63174322edfb4e0b6ffd1ec9/edit)

Error Screenshot 

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/25542733/202632997-af472683-3a12-4347-8516-4f54ae1c477e.png">

Network Tab 

API: https://app.appsmith.com/api/v1/applications/publish/62e789bd4003a7259a30242d
Method: POST
Response Status Code: 404
API Response: `{"responseMeta":{"status":404,"success":false,"error":{"code":4027,"message":"Unable to find action 636bb827b7d12f577aa5968b","errorType":"INTERNAL_ERROR"}}}`

Screenshot: 
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/25542733/202633792-4f545429-79c8-4c52-9509-f0b7b5bbb5a8.png">

### Steps To Reproduce

1. Edit the False Alarms App by clicking on the Edit Button. 
<img width="290" alt="image" src="https://user-images.githubusercontent.com/25542733/202634076-2426a0b6-8aad-4c56-99ac-58cede2744d3.png">

2. Click on Deploy button.

3. Error Pops up with the message "Resource Not Found" 
<img width="1432" alt="Screenshot 2022-11-18 at 11 37 19 AM" src="https://user-images.githubusercontent.com/25542733/202634518-189b74b9-a060-4b5e-b7cc-af1d05214f71.png">

### Version

v1.8.7-SNAPSHOT

**Comment by kamakshibhat-appsmith** [comment]
Not able to replicate the exact scenario from my end , and checked on the user's app with @NilanshBansal  , it is now working fine . hence , moving to verified
