### ISSUE TITLE
[Task]: App Theming Stylesheet Refactor

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#18253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Theme Stylesheets config has become really hard to manage. Need a way to make it simpler and move to the frontend.

**Comment by chandannkumar** [comment]
Here is my callout mentioned in PR [Link](https://github.com/appsmithorg/appsmith/pull/18258#issuecomment-1326632768)

**Comment by chandannkumar** [comment]
Tested this and LGTM
