### ISSUE TITLE
[Feature]: Update table to table v2 in CRUD generation

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#18250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Only update the table widget to table v2 for now in crud page

### Why should this be worked on?

People starting from crud pages are running into bugs which we are not fixing because of older versions of tables.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5w824)

**Comment by dilippitchika** [comment]
We have to follow the document here to make the change - https://www.notion.so/appsmith/How-to-update-CRUD-template-09594645bf8e4077b4161c2ec095c27c

**Comment by somangshu** [comment]
@dilippitchika what happened with this issue? It seems there is some conflict with the auto layout that will break all crud apps and templates because they use table v1 and is not compatible. We need to reprioritize this.

cc @keyurparalkar

**Comment by somangshu** [comment]
[Internal thread of conclusion](https://theappsmith.slack.com/archives/C02JV8G1MP0/p1698994512694269)
