### ISSUE TITLE
[Bug]: Fusion chart custom pallete keep a top padding that display a white background

### ISSUE THREAD

**Issue by CervarlCG** [appsmithorg/appsmith#18281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you render a custom chart with a background container different of white and set the properties bgColor to any color for some reason the widget has a padding top of 10px with a white background and occasionally has the same behavior for the right side but with 1px 

![Screenshot 2022-11-18 at 9 53 23](https://user-images.githubusercontent.com/53922412/202747015-66e7e549-490a-4c17-b201-4946081420f2.png)

### Steps To Reproduce

1. Add a container with a dark brackground
2. Add a Chart and set the type to custom
3. Edit the chart background color porperty to be the same as the container

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b0jkc)

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/cnv_10rre4zw?key=rVtsHIPnSlM9shpqUpKBqQBQZ52uhZOm) reported this issue.
