### ISSUE TITLE
[Bug]: Accessing Queryparams stopped working after connecting to git

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#18289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

connect an app with queryparam to git. params are not accessible.

https://ca9sxzlrgy.vmaker.com/record/6QlsV129wQ1FEqrU

### Steps To Reproduce

connect an app with queryparam to git. params are not accessible.

### Public Sample App

https://app.appsmith.com/app/urlparam/page1-61e9707f8e1c833631536749?branch=master

### Issue video log

https://ca9sxzlrgy.vmaker.com/record/6QlsV129wQ1FEqrU

### Version

Cloud

**Comment by ramsaptami** [comment]
Duplicate of #15433

**Comment by ramsaptami** [comment]
Issue exists on edit mode hence reopening this

**Comment by AnaghHegde** [comment]
@ramsaptami This looks like a clean URL issue, right?

**Comment by ramsaptami** [comment]
Yep, NDX should be handling this IMO @AnaghHegde

**Comment by hiteshjoshi** [comment]
@ginilpg please check this

**Comment by eco-monk** [comment]
This is working as expected in both prod and release.
https://www.loom.com/share/0c3fdcd550574a6186c6a084d1dcab1c
@ramsaptami can you help me with reproducing this?

**Comment by ramsaptami** [comment]
Looks like its working in prod now, should we close this? @eco-monk

**Comment by eco-monk** [comment]
Thanks @ramsaptami.!
Closing this.
