### ISSUE TITLE
[Task]: Remove parse JS Actions from View mode

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#18291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by somangshu** [comment]
This was re-opened due to regression #19089 

We will re-prioritiize this once #18471 is merged since that brings good improvement to the parseJSActions, this might not be required any more

**Comment by ramsaptami** [comment]
PR had to be reverted since actual performance did not improve
