### ISSUE TITLE
[Feature] In-app embed settings

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#18292]
Design: https://app.zeplin.io/project/6310825e7f4577131f79df64?seid=6364d838107c1413ea207110

Original issue: https://github.com/appsmithorg/appsmith/issues/1979

Self hosted DP: https://theappsmith.slack.com/archives/C02JT9CSE6L/p1671419543074509
Cloud DP: https://appsmith-du3yjz2xx-get-appsmith.vercel.app/

**Comment by ginilpg** [comment]
- [ ] Make it easy for developers to find a way to embed - Enable an embedding modal/popup which will allow users to access the embedding code block
- [ ] Make it easy for a developer to preview different embed sizes
- [ ]  Allow the user to configure settings within the modal - Making the header visible/invisible, setting the dimensions, on and making page names visible/invisible

**Comment by RoopKrrish9696** [comment]
**Design review for the [DP](http://167.71.229.90:8000/):** @akash-codemonk @kocharrahul7 @ginilpg 

1. Padding between tabs and body content should be 24px
2. Line spacing to be increased in the code snippet
3. Height of the input boxes should be 28px
4. Tooltip underline color in the app settings should be changed
5. Preview embedded app to be added ( We can take a decision later, but lets implement the design )

**Comment by akash-codemonk** [comment]
@RoopKrrish9696 Note that for non-admin we won't have top section so the snippet height will be bigger. 

<img width="716" alt="non-admin" src="https://user-images.githubusercontent.com/67054171/208585802-42c7ddcb-d503-4339-9ff5-8ae8b3d1add4.png">

**Comment by Richarex** [comment]
- [ ] Embed size is getting saved without any values, is this expected? Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/rN1VUHWO08nbWLpk
- [ ] **Link copied to clipboard** message is missing [as mentioned in the design doc] instead the text changes to **COPIED APPLICATION URL** when the user clicks on the **"COPY APPLICATION URL"** from the invite tab at the bottom. Please refer to the attached video:- https://www.loom.com/share/851685ee48ba4cce89e3b0436afb9a20
- [ ] When the user copy the link of the application the text **COPY APPLICATION URL** should be in bold with the text message **Link copied to clipboard** as mentioned in the design doc. Please refer to the attached video & SS:- https://jiju8jbmwa.vmaker.com/record/UFkzZfU6aENOBZ5f and Screenshot:- 
![Screenshot 2022-12-19 222122](https://user-images.githubusercontent.com/93259714/208477985-e53da875-0d87-4acf-880c-8dfe0e7e1b5b.png)
- [ ] On the **Invite tab** at the bottom it is mentioned **Mark the application public** instead of **Make the application public** as mentioned in the design doc. Please refer to the attached SS:- 
![Screenshot 2022-12-19 222911](https://user-images.githubusercontent.com/93259714/208479705-eb4cd855-d202-4c51-87f1-4b336efb4d16.png)
![Screenshot 2022-12-19 223018](https://user-images.githubusercontent.com/93259714/208479706-936705bc-853e-463b-a34b-f86bc2499aff.png)
- [ ]

**Comment by akash-codemonk** [comment]
> * [ ]  Embed size is getting saved without any values, is this expected? Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/rN1VUHWO08nbWLpk

If it is invalid we won't save. Have fixed some styling and added blank value validation.

> * [ ]  **Link copied to clipboard** message is missing [as mentioned in the design doc] instead the text changes to **COPIED APPLICATION URL** when the user clicks on the **"COPY APPLICATION URL"** from the invite tab at the bottom. Please refer to the attached video:- https://www.loom.com/share/851685ee48ba4cce89e3b0436afb9a20

We don't show toast since the modal is on view mode as well. Instead we update the text. 

> * [ ]  When the user copy the link of the application the text **COPY APPLICATION URL** should be in bold with the text message **Link copied to clipboard** as mentioned in the design doc. Please refer to the attached video & SS:- https://jiju8jbmwa.vmaker.com/record/UFkzZfU6aENOBZ5f and Screenshot:-
>   ![Screenshot 2022-12-19 222122](https://user-images.githubusercontent.com/93259714/208477985-e53da875-0d87-4acf-880c-8dfe0e7e1b5b.png)

Color wasn't correct. Have updated it.

> * [ ]  On the **Invite tab** at the bottom it is mentioned **Mark the application public** instead of **Make the application public** as mentioned in the design doc. Please refer to the attached SS:-
>   ![Screenshot 2022-12-19 222911](https://user-images.githubusercontent.com/93259714/208479705-eb4cd855-d202-4c51-87f1-4b336efb4d16.png)
>   ![Screenshot 2022-12-19 223018](https://user-images.githubusercontent.com/93259714/208479706-936705bc-853e-463b-a34b-f86bc2499aff.png)

Updated text

Will update the dp soon.

**Comment by Richarex** [comment]
@akash-codemonk these issues for Non- Admin users (cloud DP)
- [ ] values of the embed size and show navbar are not getting saved and it shows some default values when the field is kept empty is this expected? Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/HmJ3I7cww7aUNuqE
- [ ] Getting **Resource not found** error when clicked on **PREVIEW EMBEDDED APP** in the embed tab. Please refer to the attached video:- https://www.loom.com/share/f22e7dc3e5bd4a199abef10368433ef6
- [ ] when **Share & Embed** tab is accessed from the **APP SETTINGS** then there is inconsistency in the text below share & embed tab it's written **Make public** and inside the tab it shows **Mark application public**. Please refer to the attached SS:- 
![Screenshot 2022-12-20 132159](https://user-images.githubusercontent.com/93259714/208613826-b38e723c-802a-4943-8601-dd305c1529a9.png)
- [ ] When cursor is placed on **Mark application public** then tooltip message and tooltip is not aligned properly like the question mark icon should be displayed how we are handling for the **APP SETTINGS** tooltip. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/cimWzZPqyj4WVkVO
- [ ] When new workspace is created and clicked on the share button then on the **Share** tab **Make the application public** toggle is not visible only infinite loading spinner is seen. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/1RPz3pk4xuFrX3lW
- [ ] Once the user disables the **Make the application public** toggle then the user fails to enable it back again. Happens for all the applications even for the newly created ones. Note for the 1st when it's disabled **Resource not found** error is displayed on the canvas. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/0apUXZqrJrKspTeN
- [ ] For old applications **Make application public** toggle is not at all visible on the invite tab. Please refer to the attached SS:- 
![Screenshot 2022-12-20 135036](https://user-images.githubusercontent.com/93259714/208617899-190cf3c1-57ff-4bbd-99ac-38c13ace0b45.png)

**Comment by akash-codemonk** [comment]
> @akash-codemonk these issues for Non- Admin users (cloud DP)
> 
> * [x]  values of the embed size and show navbar are not getting saved and it shows some default values when the field is kept empty is this expected? Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/HmJ3I7cww7aUNuqE

Invalid values are not saved. It saves the last valid value.

> * [x]  Getting **Resource not found** error when clicked on **PREVIEW EMBEDDED APP** in the embed tab. Please refer to the attached video:- https://www.loom.com/share/f22e7dc3e5bd4a199abef10368433ef6

Have fixed this the url was incorrect.

> * [x]  when **Share & Embed** tab is accessed from the **APP SETTINGS** then there is inconsistency in the text below share & embed tab it's written **Make public** and inside the tab it shows **Mark application public**. Please refer to the attached SS:-
>   ![Screenshot 2022-12-20 132159](https://user-images.githubusercontent.com/93259714/208613826-b38e723c-802a-4943-8601-dd305c1529a9.png)

Have made it `Make` everywhere. 

> * [x]  When cursor is placed on **Mark application public** then tooltip message and tooltip is not aligned properly like the question mark icon should be displayed how we are handling for the **APP SETTINGS** tooltip. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/cimWzZPqyj4WVkVO

Fixed center aligned it

> * [x]  When new workspace is created and clicked on the share button then on the **Share** tab **Make the application public** toggle is not visible only infinite loading spinner is seen. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/1RPz3pk4xuFrX3lW

As discussed it was some temp issue.

> * [x]  Once the user disables the **Make the application public** toggle then the user fails to enable it back again. Happens for all the applications even for the newly created ones. Note for the 1st when it's disabled **Resource not found** error is displayed on the canvas. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/0apUXZqrJrKspTeN

Hiding this section if the user does not have permission.

> * [x]  For old applications **Make application public** toggle is not at all visible on the invite tab. Please refer to the attached SS:-
>   ![Screenshot 2022-12-20 135036](https://user-images.githubusercontent.com/93259714/208617899-190cf3c1-57ff-4bbd-99ac-38c13ace0b45.png)

As discussed the user here did not have permission so it was not visible. 

DP is updated

**Comment by Richarex** [comment]
@akash-codemonk 👍 verifying the issues

**Comment by Richarex** [comment]
Verified all the issues for Admin/Non-admin users and they are fixed
