### ISSUE TITLE
[Bug]: Text color formatting is not getting applied on Bold, Italic text of RTE

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#18305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On changing text color of texts written in Bold, Italic or both are not getting changed to applied text color in RTE

### Steps To Reproduce

1. Drag & Drop Rich text editor widget
2. Type anything on editor and make some words as Bold or Italic
3. Select all the words and change the color of the text
4. Observe that Bold, Italic words are still in Black color instead of Text color applied in formatting

### Issue video log

https://www.loom.com/share/5efc96e749244442bb7f4c74659a2298

### Version

Cloud / Production

**Comment by dilippitchika** [comment]
Fixed in #17402 @chandannkumar can you verify and close?

**Comment by chandannkumar** [comment]
This issue is fixed in #17402 (Tested & Verified)
