### ISSUE TITLE
[Bug]: Clicking a disabled delete icon triggers an error message.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we click a disabled delete icon of a home page on the Page Properties UI, an error message comes up "Cannot Delete the Home Page". This message seems redundant. 

Expected behavior - on clicking a disabled icon, no action should be triggered.

### Steps To Reproduce

1. On the Page Properties page, for a Page that is set as Home Page (say Page1), hover over the Delete icon on the right side
2. Note that the delete is disabled. This is correct. We should not be able to delete a Home Page
3. However, on clicking it, an error message comes up "Cannot Delete the Home Page"

This is redundant. If the icon is disabled and not clickable, it should not generate any message.

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/fT2LVXy655GSvSdE

### Version

Production

**Comment by kocharrahul7** [comment]
This has been resolved and is no longer an issue. The delete button no longer appears for the home page
