### ISSUE TITLE
[Bug] Invalid BSON field name $numberInt

### ISSUE THREAD

**Issue by sbansal6** [appsmithorg/appsmith#1831]
## Description
Setting up Server codebase using docker. 
When i run docker-compose.yml @ https://github.com/appsmithorg/appsmith/blob/release/app/server/docker-compose.yml

**seeing error** 

ppsmith-internal-server_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
appsmith-internal-server_1  |  - Application run failed
appsmith-internal-server_1  | java.lang.IllegalStateException: Failed to execute ApplicationRunner
appsmith-internal-server_1  |   at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778)
appsmith-internal-server_1  |   at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
appsmith-internal-server_1  |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
appsmith-internal-server_1  |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
appsmith-internal-server_1  |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
appsmith-internal-server_1  |   at com.appsmith.server.ServerApplication.main(ServerApplication.java:12)
appsmith-internal-server_1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
appsmith-internal-server_1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
appsmith-internal-server_1  |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
appsmith-internal-server_1  |   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
appsmith-internal-server_1  |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
appsmith-internal-server_1  |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
appsmith-internal-server_1  |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
appsmith-internal-server_1  |   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
appsmith-internal-server_1  | Caused by: com.github.cloudyrock.mongock.MongockException: **Invalid BSON field name $numberInt**
appsmith-internal-server_1  |   at com.github.cloudyrock.mongock.Mongock.executeMigration(Mongock.java:140)
appsmith-internal-server_1  |   at com.github.cloudyrock.mongock.Mongock.execute(Mongock.java:94)
appsmith-internal-server_1  |   at com.github.cloudyrock.mongock.SpringBootMongock.run(SpringBootMongock.java:24)
appsmith-internal-server_1  |   at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)

[What happened]

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Clone Repo
2. cd app/server
3. rename docker.env.example to docker.env
4. docker-compose -f docker-compose.yml up

**Comment by Nikhil-Nandagopal** [comment]
HI @sbansal6 👋 
Thank you for reporting this. @mohanarpit can you see why this is happening?

**Comment by mohanarpit** [comment]
@sbansal6  please check our [contribution guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/ServerSetup.md) to look at the steps of how to run the server code base on your local machine.

Incase you are looking to run the entire Appsmith product on your machine, please check the Getting Started Guide on docs.appsmith.com

**Comment by sbansal6** [comment]
@mohanarpit :- i have followed the guide, but seeing this error irrespective

**Comment by mohanarpit** [comment]
In our setup guide, we don't recommend using `docker-compose.yml` in the
app/server folder at all. Is there a particular reason you are using that
file to start the server? The docker-compose.yml file in the `app/server`
folder is old and needs to be removed from the codebase. It's no longer the
recommended way to start the server.

Alternatively, if you are looking to run the entire Appsmith project and
not just the server, please follow the steps at
https://docs.appsmith.com/quick-start.

Best

Arpit
