### ISSUE TITLE
[Feature]: Page Properties page - Clicking on Delete from this page, should bring up a Warning similar to the delete behavior from property pane MoreActions popup. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we click on the Delete icon for any page from the Page Properties UI, the page gets deleted immediately.
<img width="221" alt="Screenshot 2022-11-21 at 2 17 44 PM" src="https://user-images.githubusercontent.com/101863839/203005782-dffaebff-178c-4242-b8d6-33b9be6e753c.png">

Expected behavior - since this is a Delete action which is undoable, a warning should come up similar to what is shown on Delete from the Property pane More Actions popup. FYI - refer below image
<img width="453" alt="Delete_AreyouSure" src="https://user-images.githubusercontent.com/101863839/203005851-53461eb1-3c7c-4ec4-88d2-7202fd853429.png">

### Why should this be worked on?

Since this is a Delete action which is final and undoable, it give a very abrupt feeling on deleting immediately.
User might have clicked on Delete inadvertently.  
To help avoid such mistakes, a warning should come up similar to what is shown on Delete from the Property pane More Actions popup.

**Comment by kocharrahul7** [comment]
This issue has been resolved with the removal of the settings page, and introduction of the settings sidebar
