### ISSUE TITLE
[Bug]: Getting "Page Not Found" error when clicked on back button and trying to navigate to release app

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#18325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user clicks on back button to navigate back to the release app, then "Page Not Found" error is observed.

### Steps To Reproduce

1. Launch the release app
2. Drag and drop **Code Scanner** widget
3. On the property pane from **Basic** select 'Click to scan'  in **Events** select 'Navigate to' & in Type select 'URL'
4. Scan the QR code from your mobile
5. Now from mobile in google search for QR code scanner and click on images 
6. Select the 2nd QR code scanner (Hello Tech) & scan it
7. On Hello tech page click on browser back button & observe

**Actual Result**
Page not found error is observed when the user clicks on browser back button to navigate back to the release app.

**Expected Result**
User should be redirected to the release app when clicked on browser back button without any errors.

**Note**
Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/7eNEKhoYsFQ3grpq
Hello tech QR code:- 
![qrcode_www hellotech com](https://user-images.githubusercontent.com/93259714/203055453-3a2be7ac-444c-4ff4-a6d0-7fae4838ff7c.png)

Working fine with wikipedia QR code.

### Public Sample App

Release app

### Version

v1.8.8

**Comment by AnaghHegde** [comment]
@Richarex What is the issue related to Git Sync feature?

**Comment by dilippitchika** [comment]
@Richarex is this happening in deploy mode also or only in edit mode?

**Comment by Richarex** [comment]
This issue is not happening anymore after clearing the cache & doing hard refresh.

**Comment by Richarex** [comment]
> @Richarex is this happening in deploy mode also or only in edit mode?

Was happening only in edit mode.

**Comment by dilippitchika** [comment]
Then i don't think this is related to codescanner, i am assuming you are using navigateTo function to go to the new page. It should also happen in button or any other widget
