### ISSUE TITLE
[Bug]-[682]:Table v1 | line separating the column headers & the toolbar breaks below "Filters" & "Download"

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#18322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The line separating column headers & the toolbar is not consistent.
<img width="707" alt="Screenshot 2022-11-21 at 2 42 53 PM" src="https://user-images.githubusercontent.com/39921438/203035896-c7040086-77b7-4002-8300-aa1e6478ff91.png">

### Steps To Reproduce

1. Go to any old app that has Table v1 in it.

### Version

Cloud

**Comment by dilippitchika** [comment]
Assuming 20% users see this

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 682 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@somangshu this is a good first issue according to me. Let me know your thoughts

**Comment by somangshu** [comment]
Agreed. Should be a easy solve

Cc @vsvamsi1
