### ISSUE TITLE
[Bug]-[10680]:User is able to Delete sheet when the permission is not provided

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#18328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user has a provided permission to "Edit Create and Read" it is  observed that user can delete the sheet as well

### Steps To Reproduce

1) Click on GSheet 
2) Add Permission "Edit Create and Read"
3) Authorise the Gsheet
4) Create API 
5) Select command to delete 
6) Select Sheet name 
6) Click on RUN
and observe 
<img width="1280" alt="Screenshot 2022-11-21 at 6 58 43 PM" src="https://user-images.githubusercontent.com/71753653/203067476-d5cc1d5c-532a-434a-971e-43f773e09987.png">

### Version

Release /Production

**Comment by prapullac** [comment]
this is to bring to your notice that the  flow was working as expected , but seems to have broken sometime recently and hence marking it as Regression. and high

**Comment by rohan-arthur** [comment]
6m gsheets usage: 2670
assuming 10% use the read-only mode, reach = 267

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 267 |
| Effort (months)  | 0.25 |

**Comment by sneha122** [comment]
@prapullac According to thread here: https://theappsmith.slack.com/archives/C040LHZN03V/p1671460118536759, The scopes are valid at spreadsheet level, so even if we have scope of "Read, Edit and Create Files", and if we delete a sheet inside a spreadsheet, it should be a valid operation as this operation is not at spreadsheet level.

**Comment by prapullac** [comment]
As per above comment we can close the issue
