### ISSUE TITLE
[Bug]-[3373]:Resizing should either be stopped at the dropdown border or the dropdown size should also get resized

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#18320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we resize any dropdown widget, label is getting resized up to the lowest but the dropdown is resized only up to a point
so either the label should also be resized only up to a point or vice versa to resize up to the lowest.

<img width="142" alt="image" src="https://user-images.githubusercontent.com/104895602/203026115-818b3958-9917-401d-9b0d-11da5fbda2b4.png">

### Steps To Reproduce

1. Drag and drop any select widget
2. Resize to the lowest size in width
3. Observe the drop down border is outside the border of the widget/ the text inside the drop down is outside the border of the widget

### Version

Release

**Comment by Tooluloope** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3373 |
| Effort (months)  | 0.5 |

**Comment by somangshu** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3373 |
| Effort (months)  | 0.5 |
