### ISSUE TITLE
[Bug]: Line separating Columns header and toolbar is not till the end of Table widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#18339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The line separating the column header and toolbar should be fixed till the end of Table widget

![image](https://user-images.githubusercontent.com/95341241/203227471-9d81a594-f81b-4b86-9fb6-5a73d04e36d1.png)

### Steps To Reproduce

1. Drag & Drop Table widget
2. Reduce the width of Table widget
3. Scroll the Toolbar to the right
4. Observe that the line separator below toolbar is incomplete and not visible till the end of table widget

### Issue video log

https://www.loom.com/share/2ea4489735f4443bb5c6e712afc8b645

### Version

Cloud / Production

**Comment by chandannkumar** [comment]
#18322

**Comment by somangshu** [comment]
Hey @vsvamsi1, this seems like this is already taken care of, can you verify this
