### ISSUE TITLE
[Task]: Create an analytics event for navigating to files

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#18347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We require a mixpanel event which triggers whenever a user opens an action (jsObject, query, or API). This should be triggered when a user navigates to a page using the entity explorer. The event should have the following properties:
- Action name
- If the action has been opened in the last 5 actions already (true or false) (we maintain a queue of the last 5 actions which have been opened, and if the one being opened is in that queue, we return true, otherwise we return false)
- the length of the queue (if the user hasn't opened any items yet, this should return 0)

The max queue length we need to maintain is 5 actions. We don't need to consider what happens on the canvas, or what happens in each action page.

**Comment by eco-monk** [comment]
Will be handled in #18299.
