### ISSUE TITLE
[Bug]: 'Add new row' hides from toolbar on disabling Filter & Download property in Table widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#18346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When 'Add new row' property is enabled then it should get disabled automatically on disabling Filter & Download option from toolbar

### Steps To Reproduce

1. Drag & Drop Table Widget
2. Enable 'Add new row' property from property pane
3. Now disable Filter & Download option from Property pane
4. Observe that 'Add new row' option is not visible on toolbar

### Issue video log

https://www.loom.com/share/4d04c54c06614216bda35e9974c88f85

### Version

Cloud / Production

**Comment by dilippitchika** [comment]
@sbalaji1192 can you fix this on priority? @chandannkumar this wasn't caught in the testing in release and dp is it?

**Comment by chandannkumar** [comment]
> @sbalaji1192 can you fix this on priority? @chandannkumar this wasn't caught in the testing in release and dp is it?

We might have missed this
