### ISSUE TITLE
[Bug]: Add audit log events for new embed settings feature

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, the embed setting changes are done on the admin setting page so we should add an event that could capture in our audit log section 

### Steps To Reproduce

Add the events for embed setting

### Version

Deploy preview

**Comment by akash-codemonk** [comment]
Are there events already for other fields in admin settings? @RakshaKShetty

**Comment by ginilpg** [comment]
@akash-codemonk This is a blocker for [https://github.com/appsmithorg/appsmith/issues/15661](url)

**Comment by akash-codemonk** [comment]
Ok but we can still merge embed settings fronted changes right?

**Comment by akash-codemonk** [comment]
It is getting logged as expected as mentioned in https://theappsmith.slack.com/archives/C02JT9CSE6L/p1669187795025469?thread_ts=1669181384.529739&cid=C02JT9CSE6L.  
Closing this issue now as ee changes are merged with https://github.com/appsmithorg/appsmith-ee/pull/743.

**Comment by Richarex** [comment]
Verified this issue, working fine for embed settings feature events are getting captured.
![image](https://user-images.githubusercontent.com/93259714/208054390-ad09e3c2-d9e4-4094-866c-63dc4a8c298e.png)
