### ISSUE TITLE
[Bug] table loaded multiple times

### ISSUE THREAD

**Issue by AndreaPravato** [appsmithorg/appsmith#1834]
## Description

Table is unexpectedly loaded and displayed multiple times. This is more of a performance improvement request than an actual bug in the reproducible case described, but users could reasonably expect a single query/call. It seems related to https://github.com/appsmithorg/appsmith/issues/1494

### Steps to reproduce the behaviour:
1. Add a table with data in the page 
2. Inspect Element in the browser; network tab; set throttling to gprs to simulate a slow internet connection; 
3. visit the page
4. see the table load twice

![loading](https://user-images.githubusercontent.com/4329975/99872280-f8192c00-2be0-11eb-871e-1835bf7f1b81.gif)

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you have a look at why this is happening?
