### ISSUE TITLE
[Bug]: group widgets center align label

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#18359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Center align labels for group widgets namely `checkbox, radio, switch`. Today we have top aligned labels 
<img width="153" alt="image" src="https://user-images.githubusercontent.com/13429535/203343238-86091d8d-4e8c-43e4-9198-36cb464efb20.png">

- Add Tooltip to the `general section` similar to the `input widget`.

### Steps To Reproduce

1. Drag & Drop the `Switch, Radio` group widget.
2. Try to recreate the steps mentioned in the description

### Version

Cloud

**Comment by dilippitchika** [comment]
Hey @yaldram this change on the radio/ switch regarding alignment `style -> genera -> alignment` feels unnecessary as the items in the group don't look aligned. Is there a reason you are making this change?

**Comment by yaldram** [comment]
Hey @dilippitchika I noticed that there was a lot of space between the label and control so I removed the `width: 100%`, but the user can resize it anyways, I will remove this change. Thanks.

**Comment by somangshu** [comment]
Issue does not exist anymore
