### ISSUE TITLE
[Enhancement]: Update Datasource structure on test click

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#18356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Update the Datasource structure upon clicking of a test button on the configuration page. 

### Steps To Reproduce

1. Click on create a new data source/ select any existing data source
2. Choose a data source(in case of new data source)
3. Fill in all required configurations.
4. Click on the test button.

### Version

Cloud

**Comment by rohan-arthur** [comment]
@ChandanBalajiBP cool idea. Would you please explain more about why this would be impactful? 
Also, do you think `Test` can become an implicit action that is called behind `Save`, so that all of this can simply happen in the background?

**Comment by ChandanBalajiBP** [comment]
Let me explain this in the following steps(this was the reason behind creating this issue also)

1. Create Datasource with the wrong configurations.
2. Save this Datasource.
3. Now edit Datasource with the correct configurations and click on the test button.
4. So if the test is successful, the error display in the schema position is not updated until the user saves the correct configuration.
5. This same in the case of vice-versa(correct -> wrong configurations)

But there is a certain restriction in server implementation for this. Had a discussion with @subrata71 just now.
So schema is fetched on Datasource configurations present in mongo and mongo is only updated on click of the save button.

There are many ways to address this issue but will be a major fix.
> Fix 1: Save configurations on the test button click and update the schema.
> Drawback of this fix is that assume the user had saved the correct configuration and now he edits with the wrong one. The wrong configurations are saved in DB and he cannot revert back. But in the current scenario if unless he saves he can revert back to old configurations. This can be further solved in many ways but not worth the effort.
>Fix 2: Have a separate collection in mongo for this. But considering multiple environments we might end up creating many collections/huge data for a single Datasource.

And coming to the second question of Test can become an implicit action that is called behind Save
>I think this is not possible, because of the same drawbacks as in Fix 1.

Small suggestions - It would be better if we can give the Datasource status both in entity explorer as well as on the configuration page. 

cc: @sribalajig @riteshkew @rohan-arthur

**Comment by rohan-arthur** [comment]
Thanks @ChandanBalajiBP ! We are going to make the datasource save to be explicit, see https://github.com/appsmithorg/appsmith/issues/4381 

Would removing the auto save affect any of the considerations in the approaches described by you? It may be, that if the changes to datasources, either correct-->wrong or vice versa, are always triggered by a manual SAVE action, then we can afford to piggy back the TEST and "GET SCHEMA" actions along with it?

**Comment by ChandanBalajiBP** [comment]
@rohan-arthur I don't think removing the auto-save would affect any of the considerations in the above approaches.

**Comment by rohan-arthur** [comment]
@ChandanBalajiBP I'm closing this issue because we will be approaching this problem more systematically with the next project.
