### ISSUE TITLE
[Bug]: Changing the canvas size in the editor also affects the deployed app without deploying

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#18363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the canvas size in my editor, the canvas size of my deployed app also changes.

I expect the deployed app to never change unless I deploy a new version.

### Steps To Reproduce

1. Create a new App
2. Change the canvas size to Desktop
3. Place a widget on the canvas
4. Deploy the app
5. Observe that the deployed app is Desktop sized.
6. Return to the editor
7. Change the canvas size to mobile
8. Without re-deploying, go back to the app
9. Observe that it is now Mobile sized. (May have to refresh the page)

### Version

Cloud - 1.8.9-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5xyj0)

**Comment by Sripriya93** [comment]
Checked with all the canvas sizes and refreshing the deployed page, no changes. Marking as verified.
