### ISSUE TITLE
[Bug]: `navigateTo` function broken. Fails to set queryParams if the app is connected to Git

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#18376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

queryParams are not being set by `navigateTo` if the app is connected to Git

### Steps To Reproduce

1. Create a button with `navigateTo` and add some params
2. Connect your app to git
3. Click on the button, see there is no `queryParam` after navigation

### Issue video log

https://www.loom.com/share/4cea3ab835e345df87e6eb4bf2a801ef

### Version

Cloud - v1.8.10

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5zjf0)

**Comment by ginilpg** [comment]
This is reproducible with out git as well.

**Comment by Richarex** [comment]
This issue is fixed, verified it on release:- https://www.loom.com/share/b34860f3d87e4fe693d71a2eada5c221
