### ISSUE TITLE
[Bug]: When create permission is checked at app level and below, other permissions are not getting checked in Application Resources tab

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On checking the create role at app level or below in application resource tab, ideally edit, delete and view should also gets checked , like how we do it when checking create role at workspace level.

### Steps To Reproduce

1. Go to Roles , and Click on Create Role at app level in application resources tab
2. Observe the other permissions are not getting checked

### Version

http://65.0.99.89/

**Comment by RakshaKShetty** [comment]
This issue is fixed
