### ISSUE TITLE
[Bug]: Not able to edit queries when user has edit app role 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user has edit permission at workspace level in application resources tab, on opening any query in that app gives "An unexpected error occurred" error and user is not able to edit the query.
<img width="1440" alt="Screenshot 2022-11-22 at 9 17 03 PM" src="https://user-images.githubusercontent.com/80334441/203471026-4a950097-d391-4b58-a6cf-5dd64371aa94.png">

### Steps To Reproduce

1. Create a new role with edit permission at workspace level
2. Assign the role to user1
3. Login as user1
4. Click on query from entity explorer , it will take you to query editor
5. Observe An unexpected error occurred is shown

### Version

http://65.0.99.89/

**Comment by trishaanand** [comment]
This issue is reproducible if you give edit access to the application but do not give view access to the datasource. The client reaches this erroneous state.
