### ISSUE TITLE
[Feature]: Support searching datasources on the datasource page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#18375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, datasources page does not support search functionality so I need to use the browser feature to look up a datasource. Since this does not support fuzzy logic search, I have to know exactly which datasource I need else I have to go back to scrolling through a list to find what I'm looking for.

A [sorting functionality](https://github.com/appsmithorg/appsmith/issues/9240) would also greatly help improve the experience on the datasources page

### Why should this be worked on?

Ease of use when dealing with a long list of datasources connected to the app/org

https://www.loom.com/share/2bdac4e281cd45edbe39082274fd2cd9

**Comment by rohan-arthur** [comment]
will be done as part of a project, details: https://www.notion.so/Problem-identification-CRUD-query-funnel-7e3573f7fdb34575b8d2801420f65611
