### ISSUE TITLE
[Bug]: Currency widget input expecting a numeric value  inorder for the step-up/down  arrows to work

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#18385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currency widget input expecting a numeric value  inorder for the step-up/down  arrows to work

### Steps To Reproduce

1. Drop a currency widget
2. try to use step up/down arrows

### Issue video log

https://www.loom.com/share/4f4b86549b54450781e07508680aa240

### Version

Production

**Comment by ashit-rath** [comment]
@kamakshibhat-appsmith The Currency/Number inputs do not show the stepper buttons anymore.
cc: @somangshu @dilippitchika
