### ISSUE TITLE
[Bug]: Focus state is not being differentiated on button group

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#18383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

I observed this bug in the following DP where we've implemented the gray scale changes.
https://appsmith-git-shades-of-design-system-get-appsmith.vercel.app/

1. Active state of the BOLD and ITALIC buttons is not getting cleared if we click an active button.
2. Clicking outside the button group makes the first button active
3. When we navigate using the keyboard `Tab` key, once we reach the button group, there is no indication currently focused item.

https://user-images.githubusercontent.com/10436935/203499161-78377dc6-98bf-4a92-b3ee-d84c82d79f87.mov

**Comment by rohitagarwal88** [comment]
Fixed in ADS 2.0. Now using segmented control
