### ISSUE TITLE
[Bug]: The scroll is not working properly when container is set to Fixed height

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#18393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When container widget is set to Fixed height and widgets inside is set to Auto height, while the one widget gets taller the other widgets inside container are vanished from container instead of showing via scroll 

P.S: This is happening for all container type widgets like form, statbox & modal

### Steps To Reproduce

1. Drag & Drop container widget
2. Drag & Drop Text and JsonForm widget inside container
3. Make sure to add Text widget above of JSONForm widget
4. Make sure to set Height as 'Auto Height' for Text widget
5. Start typing input in Text widget until Text widget gets taller than container
6. Observe that JSONForm widget gets vanished from container entirely

### Issue video log

https://www.loom.com/share/acf184349bc0431fa909a09ef847f6f9

### Version

Cloud / Release

**Comment by laveena-en** [comment]
The same issue is also seen on the tabs widget.
