### ISSUE TITLE
[Bug]: Dropdown setting for height property needs to open below when there's enough space available

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#18396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Height property for the text widget opens up above the text which is incorrect since there's plenty of space available below.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/203562191-6d4ec3af-2069-47cb-8023-7180df0e8990.png)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami seems like this would be the case for any drop down and not just the height one

**Comment by ramsaptami** [comment]
Yep, that would be right @Nikhil-Nandagopal. Almost all dropdowns on the platform follows this principle but noticed this new change on the Dynamic height feature does not do so. Hence, raised a specific issue. I've asked the team to update this issue with more scenarios if we come across one.

**Comment by btsgh** [comment]
Noticed this behavior in Container, Statbox and Form widget as well for the Height property 
cc: @ramsaptami
