### ISSUE TITLE
[Bug]: Input widget Auto height for increased Font Size 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Input widget is made to have Auto Height, and the Font Size is increased to something high, say XXL, the input box size also doubles, along with the Label area. When the Font Size is reduced back to S, the input box size remains doubled. Also, user can enter a new line character in the input box, which is not possible with the usual default Fixed height. 

Expected behavior - Input box size should not be impacted on increasing Font Size. 

### Steps To Reproduce

1. Drag and Drop ad input widget
2. Set it to have Auto-height
3. Increase Font Size to something high, say XXL
Note that the input box size also doubles, along with increase in the Label area. When the Font Size is reduced back to S, the input box size remains doubled. Also, user can enter a new line character in the input box, which is not possible with the usual default Fixed height. 

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/8s3CujsdKwPcQmyu

### Version

Release

**Comment by somangshu** [comment]
Closing the issue as its not re-producible anymore
