### ISSUE TITLE
[Task]: clean urls QA

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#18411]
- [ ] Error state persists on custom URL field
(Caused by #17393)
https://www.loom.com/share/eb01034ad40642ce8b8450dd190de670
- [ ] The input box here is disabled here because of the URL not being updated but does not convey this information since cursor turns into edit icon but CTA amounts to nothing. Provide a better feedback when such an action is taking place.
(design system: https://github.com/appsmithorg/appsmith/issues/17431)
![image](https://user-images.githubusercontent.com/79509062/197133044-5e16d248-25ab-4c4a-bb96-160335bd429e.png)
- [x] Error message specify allowed characters () or - (consider app name and page name difference)

- [x] Text `"to new readable format to change this*"` does not provide ample information since `this*` does not have a link or a sub text explanation following the asterisk. Or add an asterisk to the `Change URL` text
(`this` means the Page URL field here, consider removing the asterisk)
![image](https://user-images.githubusercontent.com/79509062/197133063-426f0e30-0398-42d8-8355-ecfc2b699d9a.png)
- [x] Tooltip needs to be in 2 lines as seen in designs (done -> we're going with left aligned text, to prevent overflow in certain cases @RoopKrrish9696 )
![image](https://user-images.githubusercontent.com/79509062/199532052-b3ea1dbe-6895-4473-8c20-a108bcdacb85.png)
- [x] App name can be renamed with special characters at the current location above entity explorer but is not allowed from the new settings panel (done -> only - and braces are allowed now, let's create a separate issue for fixing this in entity explorer)
![image](https://user-images.githubusercontent.com/79509062/199463531-770f6015-11af-4c8d-9fb5-5269a7b4c50f.png)
- [x] Add a tooltip here since the purpose of this toggle is unclear (done)
![image](https://user-images.githubusercontent.com/79509062/197134021-f7fd7c42-04f6-4b53-b4ba-d1213efb44d3.png)

- [x] Incorrect tooltip on a non-home page page. Also, the tooltip needs a rephrase (rephrased)
![image](https://user-images.githubusercontent.com/79509062/197135032-62a3eac7-3fcd-46d0-ba00-ee389613ee82.png)

- [x] Need more space between error text and fixed content (done)
![image](https://user-images.githubusercontent.com/79509062/197131035-51a38084-04a8-4400-be84-b7095f8278e2.png)
![image](https://user-images.githubusercontent.com/79509062/197141907-d8aa9170-04bb-4387-abac-c3bb5798d2e1.png)

- [x] Text shows lint error but nothing shows up on hover (this is browser's grammer correction showing up)
![image](https://user-images.githubusercontent.com/79509062/197137773-a3ff5c2b-6a88-42a0-a3f2-72474140373e.png)

- [x] Functional testing issues observed from the video attached (navgiateTo -> page needs to be deployed for this to work)
https://www.loom.com/share/964088785a054ee9a026bd857f0229a4
- Need to improve the copy experience of the URL on page settings (fixed)
- Manually copying the URL from the field adds blank space which is incorrect (fixed)
- URL signature is incorrect when custom URL is set since it removes the page name (discussed, this is as per epic requirements)

- [x] Automatic URL redirection does not happen when page name is changed (issue could be cascaded to git connected apps as well) - issue that was addressed in v1 hence its a regressed issue (separate issue)

- [x] Home page tooltip does not show up until the page has been set as a home page (this is as per designs, because we want to convey this message only when the control is disabled. Which happens when a page is set as homepage)
https://www.loom.com/share/a1bf2cbf7a1544e890cb714c11a45e6a

- [x] Switch toggle is incorrect here since user can only mark a page as the home page, they can't un-mark it as a home page so this one-way interaction needs a re-think - can't be a switch or a checkbox
(When we uncheck -> something else needs to become a home page by default, the system cannot make an assumption on behalf of the user, hence this is disabled)
https://www.loom.com/share/a1bf2cbf7a1544e890cb714c11a45e6a

- [x] Signing in with shared URL with existing users returns a 404 (done)
https://www.loom.com/share/459880f2dc0442cabfaa6a46fcf5ebf8

- [x] Import app naming convention conflicts with page name format so an error shows up by default for an import (done)

- [x] URL update is not happening from update modal (done)

- [x] App shared link does not re-direct to app if user needs to login. Instead loads the workspace page
(done)
https://www.loom.com/share/b1e0c64eb6f24a70badeed7589288da4

---

(update modal issues can be taken separately)
- [x] There's a delay in closing update URL modal
https://1qd9hyxdc8.vmaker.com/editproject/sf4qwZvjHDyQ3Lho/

- [x] Update modal should say, `".....new app URL will be.."` not `"current app URL"`
![image](https://user-images.githubusercontent.com/79509062/197130778-03be5c44-2ab0-456e-85b2-ba95cdece168.png)

**Comment by ramsaptami** [comment]
> Switch toggle is incorrect here since user can only mark a page as the home page, they can't un-mark it as a home page so this one-way interaction needs a re-think - can't be a switch or a checkbox
> (When we uncheck -> something else needs to become a home page by default, the system cannot make an assumption on behalf of the user, hence this is disabled)

Meant that this needs to be a radio button kind of a setting, not switch or checkbox because they enable 2 way interaction which isn't possible for this setting

**Comment by eco-monk** [comment]
> > Switch toggle is incorrect here since user can only mark a page as the home page, they can't un-mark it as a home page so this one-way interaction needs a re-think - can't be a switch or a checkbox
> > (When we uncheck -> something else needs to become a home page by default, the system cannot make an assumption on behalf of the user, hence this is disabled)
> 
> Meant that this needs to be a radio button kind of a setting, not switch or checkbox because they enable 2 way interaction which isn't possible for this setting

@ramsaptami, I am interpreting this in two ways. Let me know if you meant something else.

Do you mean something like?
Set as homepage ()Yes  ()No
Here we'd run into the same problem. What happens when user selects no, some other page needs to become homepage.

Or 
() Page1
() Page2
() Page3
Here, The UI needs to be re-designed before we proceed.

**Comment by eco-monk** [comment]
Check app rename redirection. (can be taken seperately)

**Comment by eco-monk** [comment]
add warning for repetitive custom slug within an app (can be taken later)
