### ISSUE TITLE
[Task] Test cases for custom JS libs

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#18429]
## Tests to be covered

- [x] Installation/uninstallation of libraries
- [x] Autocomplete for installed library.
  - [x] Show completions when installed.
  - [x] Remove completions when uninstalled.
- [x] Linting throws errors for uninstalled libraries.
- [x] Detect Naming collision 
- [x] Installed libraries should persist when
  - [x] App is duplicated.
  - [x] App is forked.
  - [x] Import/Export.

###  Git scenarios
- [ ] Library changes in one branch should not show up on another.
- [ ] Merge library changes across branches in a git connected app.
- [ ] Discard library changes in a git connected app.
- [ ] Git import/export

**Comment by Rishabh-Rathod** [comment]
Done
