### ISSUE TITLE
[Task]: Update UI to address latest feedback and design updates | audit-logs

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#18420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

As per feedback from the team on readability we need to update the design for audit logs. This is purely an FE task and has no dependency on BE team.

## Old design

<img width="1223" alt="Screenshot 2022-11-24 at 12 48 13 PM" src="https://user-images.githubusercontent.com/1573771/203718532-5df97860-d1bd-434c-8d46-ad80f85202c6.png">

## New design

https://app.zeplin.io/project/62fdfc7503bdd428cd120a48/screen/63317d921f8fe51415a45f13

**Comment by infinitetrooper** [comment]
@ankitsrivas14 @IAmAnubhavSaini  - Please update the status of this issue. Thanks.

**Comment by ankitsrivas14** [comment]
Why we created this issue on CE?
We can close this issue. Already resolved by PR #811 in EE.

**Comment by IAmAnubhavSaini** [comment]
> Why we created this issue on CE?

CE repo is where we create the issues for tracking.
