### ISSUE TITLE
[Bug]: Auto-Height causes the gap to widen in the following scenario within Form with Auto height enabled

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we toggle between the edit and view mode, the gap widens between the video and the checkbox group widget.

### Steps To Reproduce

1. I have a Form widget with Auto height set, and a couple of video widgets below it. 
2. I add a checkbox widget below the video widgets. 
3. In this case, I bound the visible property of the chkbox widget to another chkbox widget. 
4. Now, it is noticed that the gaps between the video widgets and the input widget keeps widening as we switch between edit and view modes.

Application - 
https://release.app.appsmith.com/app/release-nov-21/page3-copy-637b13b9bc184f6baf89696a?branch=aparna

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/gQrlgeequ5bKfL9B

### Version

Release

**Comment by riodeuno** [comment]
@kamakshibhat-appsmith 
@btsgh This shouldn't be an issue anymore. Could we verify? If it is verified to not be an issue, please close this.
