### ISSUE TITLE
[Feature]: Add a salting feature allowing admins to generate a key and use it to encrypt and decrypt data in database

### ISSUE THREAD

**Issue by Hyperei** [appsmithorg/appsmith#18437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I want to start by quickly applauding the devs on this project. Absolutely game changing for my organization and so incredibly well designed.

For storing user data in apps, it would be great if we could have a feature that empowers Appsmith to handle the encryption and decryption of data stored in the database. 'Salting', I believe is the term - for added security in case the database is breached. It could be a checkbox labelled "Encrypted" in the widget settings that encrypts the input of a specific widget before sending to the database and decrypts the output of a specific widget after retrieving from the database. Keys could be encrypted and stored alongside other datastore credentials.

I am not a coder so forgive me if there is a better way to achieve this. Would be very helpful for my use-case.

### Why should this be worked on?

This could be helpful in enabling admins to keep user data more secure and private, enabling organizations to use the software for broader purposes.

**Comment by Nikhil-Nandagopal** [comment]
@Hyperei Glad you're enjoying the project! You can configure APPSMITH_ENCRYPTION_SALT in your Appsmith instance to encrypt the data!
