### ISSUE TITLE
[Bug]: Limit handles deselects widget when the mouse down happen on the canvas.

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#18458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Limit handles deselects widget when the mouse down happen on the canvas.

https://user-images.githubusercontent.com/113327629/203992348-11ab52ee-c1a9-4e3e-991e-293aa3bf4e9d.mov

### Steps To Reproduce

1. Dnd a widget
2. change it to Auto height with Limit
3. try to resize using signifier
you'll notice that the widget gets deselected

### Version

Release

**Comment by ankurrsinghal** [comment]
Fixed it here, https://github.com/appsmithorg/appsmith/pull/18455
