### ISSUE TITLE
[Feature]: automate actions on html elements and extract data (web scraping)

### ISSUE THREAD

**Issue by izac3d** [appsmithorg/appsmith#18456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great if I can create a web application for web scrapping. For example I get html element class/id/xpath then automate the tasks and store certain values that meat certain condition class/id/xpath. I write the logic steps using logical flow chart 

Storage can be google sheets or csv or else. example: app.dexi.io

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/23438535/203987305-a9ce1532-a22c-4579-9505-f5a0cbc6f71d.png">

### Why should this be worked on?

It is common request from my clients to build automation logic for certain tasks on web sites whether to reduce consumed time or collect data for analysis

**Comment by Nikhil-Nandagopal** [comment]
Hi @izac3d ! I really appreciate the effort you took to raise this issue. However, Appsmith isn't very well suited for building webscrapers. We do plan on introducing workflows in the future here #12589 so you can track that issue for updates but we don't have it planned any time soon
