### ISSUE TITLE
[Feature] APIs, DB queries, and JS functions should be at an App level and not at the page level

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1845]
## Summary

One paragraph description of the feature.

## Motivation

Why should this be worked on? What problems or use cases does it solve or
improve?

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #1911 closing in favor of that issue since the discussion is happening there
