### ISSUE TITLE
[Bug]: failed to deploy on aliyun k8s with docker image

### ISSUE THREAD

**Issue by Weidows** [appsmithorg/appsmith#18465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I using appsmith/appsmith-ce image to create deployment on aliyun k8s
mongo service seems not start correctly

I have tried many different versions of appsmith image, all comes this result
configuration: only set 80,443 port, no environment variable, volume by default

have tried this answer: https://docs.appsmith.com/help-and-support/troubleshooting-guide/deployment-errors#containers-failed-to-start, but not work

### Steps To Reproduce

there's some logs below

[logs.txt](https://github.com/appsmithorg/appsmith/files/10096026/logs.txt)

### Version

Self Hosted

**Comment by sharat87** [comment]
Hey @Weidows, thanks for reaching out. From your logs, there's not much information on MongoDB specifically, but if you still have access to that cluster/pod, can you share the file at this location please: `/appsmith-stacks/logs/mongodb/db.log.2022-11-26T09-21-23`?

I get this from this line in the logs you shared:

```
mongodb stdout | {"t":{"$date":"2022-11-26T09:21:24.049Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/appsmith-stacks/logs/mongodb/db.log","newLogPath":"/appsmith-stacks/logs/mongodb/db.log.2022-11-26T09-21-23"}}
```

I expect this should contain the details on why it failed to start.

Thank you very much, and sorry for the delay in response.

**Comment by Weidows** [comment]
@sharat87 hello, thanks for reply
I tried to run dockerfile manually, and find the problem: 

mongo service cannot start by supervised

```
root@appsmith-7957d587b6-kvxx4:/opt/appsmith# supervisorctl 

backend                          RUNNING   pid 1364, uptime 0:00:36

cron                             RUNNING   pid 1386, uptime 0:00:36

editor                           RUNNING   pid 1385, uptime 0:00:36

mongodb                          FATAL     Exited too quickly (process log may have details)

redis                            RUNNING   pid 1359, uptime 0:00:36

rts                              RUNNING   pid 1366, uptime 0:00:36

stdout                           RUNNING   pid 1358, uptime 0:00:36
```

then I tried to start manually
https://github.com/appsmithorg/appsmith/blob/release/deploy/docker/templates/supervisord/mongodb.conf

```
root@appsmith-7957d587b6-kvxx4:/appsmith-stacks/data/mongodb# mongod --port 27017 --dbpath . --logpath /appsmith-stacks/logs/mongodb/db.log --replSet mr1 --keyFile /mongodb-key --bind_ip localhost

{"t":{"$date":"2022-12-03T11:33:12.161Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/appsmith-stacks/logs/mongodb/db.log","newLogPath":"/appsmith-stacks/logs/mongodb/db.log.2022-12-03T11-33-12"}}

Aborted (core dumped)
```

But there seems to be some problems, maybe some dependency not match the machine.
Ashamed that I haven't found the final reason

**Comment by sharat87** [comment]
Hey @Weidows, are you still facing this problem? If yes, can you share the full log file requested in my prev message please? I understand that it must be very old now, so if you're still facing this problem, the current log files from the `stacks/logs/mongodb` folder should help us understand what's happening here.

**Comment by Weidows** [comment]
Sorry @sharat87 , I won't encounter this issue when deploying with Docker now. The previous environment has been deleted
If there are no similar issues, you could close this now
thanks for your time!

**Comment by sharat87** [comment]
Thanks for getting back @Weidows. Do let us know if you face any further problems with your deployment. 🙂 🙏

Closing.
