### ISSUE TITLE
[Bug] onPageLoad not working for queries

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1848]
## Description
After adding a query and binding it to a widget, the query is not run on page load

**Comment by hetunandu** [comment]
Need a way to reproduce consistently to see if it is a server or a client issue

**Comment by Nikhil-Nandagopal** [comment]
How did this not get caught in automation?

**Comment by hetunandu** [comment]
Not happening all the time. I am yet to be able to reproduce this issue

**Comment by nidhi-nair** [comment]
@hetunandu Have you been able to replicate this since then? We should downgrade this bug if not.

**Comment by hetunandu** [comment]
Yes. Since this bug was seen before your changes were pushed to self hosted, we can wait a while till we see this again

**Comment by Nikhil-Nandagopal** [comment]
Closing untill we're able to reproduce this
