### ISSUE TITLE
[Bug]: The add button is not displayed on hover in the  context menu but clicking the item triggers the menu

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The add button is not displayed on hover the data source on the context menu
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/204205913-04fd86da-11b8-4a7f-8de5-a32b9014bed7.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/204206009-b48399d8-ca3b-4c13-9ea2-1b09b85dcd71.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/204206034-dcd6a65b-04be-4f58-9d51-a7ff2fea6a27.png">

### Steps To Reproduce

1. Go to admin setting
2. click on roles tab
3. Create a new role
4. check on Create in application resource tab click on save
5. Now go to datasource & queries tab
6. Click on create,execute and view roles and save it
7. Now assign it to user1@appsmith.com
8. Now login as a user 1
9. Go to datasources section in context menu now hover on the table name The "add" is not displayed but clicking on it the queries are displayed inside the tooltip

### Version

localhost

**Comment by berzerkeer** [comment]
@RakshaKShetty Yes, we were aware of this sorry we didn't notify you earlier. This has been fixed and in PR waiting for review now. https://github.com/appsmithorg/appsmith/pull/18392. I will link this issue to that PR.
