### ISSUE TITLE
[Task]: Integrate Granular access control with Audit logs

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#18487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Integrate granular access control with Audit logs to keep a track of changes done in Access control settings. Document to follow for integration:
https://www.notion.so/appsmith/Integrating-Audit-Logs-into-your-features-13109f89f44e42ae92b68e52bcc54e55

**Comment by berzerkeer** [comment]
Reopened because the functionality is not there yet, we just added icons. The functionality PR for this will be linked.

**Comment by ankitakinger** [comment]
Re-opening as some more changes need to go in for this.

**Comment by berzerkeer** [comment]
Merged.
