### ISSUE TITLE
[Task]: Migration from JsonIgnore to JsonView

### ISSUE THREAD

**Issue by sidhantgoel** [appsmithorg/appsmith#18497]
In summary, the change comprises adding `JsonView` annotations on domain/model fields, controller methods, and arguments.
applying JsonView annotation on controller methods will include fields which are marked with the same view in domain objects.
Similarly, usage on controller method arguments will only deserialize the fields which are marked with same view in Domain object, which is helpful in case we don't want the client to send some fields for security reasons.
This change replaces the previous use of JsonIgnore for restricting fields in API response and allows for more flexibility and will enable us to have fine-grain control over fields serialized for different contexts, such as API response, export, and import.
The following views are defined as of now.
`View.Internal` - View used to serialize for internal use. It inherits from `Views.Public` and `Views.Export`, so it will also include those fields.
`Views.Public` - View used for API request/response.
`Views.Export` - View used for making field exportable, like in the case of Git sync and file export.
Also, we can define more views by adding an interface inside the Views class and Views can also inherit fields marked with different view by simple interface inheritance.

A small tutorial on JsonView - [Jackson JSON Views | Baeldung](https://www.baeldung.com/jackson-json-view-annotation)

**Comment by sidhantgoel** [comment]
PR: https://github.com/appsmithorg/appsmith/pull/19963

**Comment by AnaghHegde** [comment]
@sidhantgoel Lets close this?

**Comment by sidhantgoel** [comment]
CE PR https://github.com/appsmithorg/appsmith/pull/20086
EE PR https://github.com/appsmithorg/appsmith-ee/pull/1011
