### ISSUE TITLE
[Bug]: The few roles are not checked in the default role Administrator even when we have access for those roles

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The few roles are not checked in the default role Administrator even when we have access for those roles
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/204207925-2631b7bb-6180-47da-b327-51f5de002bc5.png">

### Steps To Reproduce

1. Go to admin setting
2. click on roles tab
3. click on the default role administrator 
4. Click on others tab
5. The admin has access to create workspace but from the UI when you check this The Create access is not checked for Create workspace

### Version

localhost

**Comment by trishaanand** [comment]
Not an issue. As an Administrator of a particular workspace does not give you the ability to create workspaces on the instance itself. This is expected.
