### ISSUE TITLE
[Bug]: Code generated on JS toggle is not readable when action contains a callback 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#18538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I choose an action with callbacks and toggle JS for the event, the generated code is hard to understand or modify. Switching to a better callback syntax `.then().catch()` and adding inline comments would improve the coding experience.

**Current Syntax** 
![Screenshot 2022-11-29 at 12 38 46 PM](https://user-images.githubusercontent.com/17562726/204463676-0c658808-c734-4c7a-8554-ebd25684edac.png)

**Suggested Syntax**
![Screenshot 2022-11-29 at 12 41 30 PM](https://user-images.githubusercontent.com/17562726/204463792-d0187260-5289-401c-a145-afb1766213d0.png)
[](url)

### Steps To Reproduce

1. Drag and drop a button
2. Configure the onClick action to execute a query
3. Configure the onSuccess and onError blocks to execute a query
4. Toggle JS for the onClick action and notice that the generated code is hard to understand or modify 

### Version

Cloud

**Comment by ravikp7** [comment]
@bharath31 Since, we now have the `then/catch` syntax. Do we need to add these comments `// onSuccess` or `// onError` in the respective blocks?

I think it'd be too verbose.

**Comment by bharath31** [comment]
Agreed. Closing this now
