### ISSUE TITLE
[Bug]: On saving role, some permissions are getting unchecked for groups and roles tab.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On trying to create new role by checking permissions on groups and role tab , on saving, the permissions are getting unchecked.

https://user-images.githubusercontent.com/80334441/204472539-eee0ed38-4350-49d4-9f12-44c9f3bae37b.mov

### Steps To Reproduce

1. Login as Admin, Go to Roles Tab
2. Create new Role, go to Groups and Roles tab
3. Check Create permission for groups , then check create permission for Roles
4. Save and observe.

### Version

http://65.0.99.89/

**Comment by trishaanand** [comment]
@ankitakinger @berzerkeer : I checked this. The client is only sending part of the update and hence only part of the update is getting applied. Assigning it to you folks.

**Comment by ankitakinger** [comment]
Re-opening for BE changes
