### ISSUE TITLE
[Bug]: In RBAC ->The resource not found error is displayed when user tries to duplicate the Apps

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The resource not found error is displayed when user tries to duplicate the Apps
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/204512812-1323aa8e-b892-4db9-90a8-3a2a3dad186a.png">

### Steps To Reproduce

1. Go to the admin setting 
2. Create a new role 
3. Select a work space where the app should have 3 pages
4. Now remove edit and view access of one page
5. give this role access to user 1
6. now login as user 1
7. duplicate the same app in the workspace 
8. the resource not found error is displayed

### Version

localhost

**Comment by Parthvi12** [comment]
We have to give create permission as well in order to duplicate app
