### ISSUE TITLE
[Bug]: Forward/Backward navigation buttons of browser doesn't work(fetch the updated URLs) when app crashes / is down at some point

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#18564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Forward/Backward navigation buttons of browser doesn't work(fetch the updated URls) when app crashes / is down at some point

### Steps To Reproduce

Loom : https://www.loom.com/share/c8d8194b04734d678709ef617a3352d0

### Version

Production

**Comment by Richarex** [comment]
This is fixed, verified it on release.
