### ISSUE TITLE
[Bug]: Preview mode - widget text overlaps with the tab area (with page names) on scrolling

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I scroll on the preview mode, the widget texts overlap with the tab area (with page names).

### Steps To Reproduce

Drag and drop a few widgets, say text/checkbox group/checkbox/switch etc. 
Now scroll up and down. 
Note that the text overlaps over the page tab area

<img width="1386" alt="Textoverlap" src="https://user-images.githubusercontent.com/101863839/204556515-6ee605db-3d5c-4c45-95a7-9d97151784fe.png">

### Version

Production

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working now
