### ISSUE TITLE
[Bug]: Entity explorer UI/UX issues

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#18568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. The scroll does not occupy the whole length of the explorer when all the items in it are expanded.
2. While adding a datasource we are not able to see a scroll in `Create New` pop up making it difficult for the user to know whether there are any more options below.
https://sqvpyjxewa.vmaker.com/record/Cc543h75lJdXjR2V
3. Tooltip is an oxymoron.
<img width="262" alt="Screenshot 2022-11-30 at 9 38 51 AM" src="https://user-images.githubusercontent.com/39921438/204705589-deaf5437-32d3-4ce6-ba0c-b8fcb0529d7f.png">

### Steps To Reproduce

1. Open the Entity Explorer.

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
The new IDE fixes most of this
