### ISSUE TITLE
[Bug]-[1280]:No. of pages change when i reach the last page of a table

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#18574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a table with -
1. server side pagination turned on
2. total record count is set

If the last page of the table doesn't have the same number of records as previous page then the pages are recalculated and this leads to confusion

### Steps To Reproduce

1. Add a table with server side pagination configured
2. Configure the total record count
3. Make sure the last page has lesser records than previous page
4. Observe the calculation re-occurs when the user reaches the last page

### Issue video log

https://www.loom.com/share/3eb6488b3e7944f2a475e667dcfcbfa7

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_61fgs)

**Comment by dilippitchika** [comment]
Problem deep-dive
1. This happens on for devs who have set server side pagination to true and total record count is set
2. Only when the user reaches the last page where the number of records are less than the expected number per page.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 320 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 25 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Why are people changing the page size?
- Devs want to show more data per page and then paginate. Lesser context switching for users.
- Users sometimes want the control on page number from the table which allows them to quickly change pageSize and run the query.

People are looking for a flexible way of controlling the page-size. Our solution hinges on if we want to allow for more flexibility and if so, how to guide devs towards implementing it correctly.

Solution exploration
1. Within the table add a new records per page property, which is the only way to control the records per page. 
   - This is different from pageSize. The pageSize property is only for understanding how many records can fit without a scrollbar.
   - This property controls the no. of records shown per page. If the dev wants people to change it we can allow that to happen.
   - This can be a new binding property with {{Table1.recordsPerPage}} which can be fed to queries now instead of {{table1.pageSize}}

2. Allow users to update the {{table1.pageSize}} property. Create a new internal property {{table1.pageRecordsFit}} which inherently points to the current value of {{table1.pageSize}}
  - This doesn't cause any change in pageSize and we calculate all our values from it. 
  - This property can be updated by devs and we use it to calculate number of pages
  - We can add a new design which allows users to change the pageSize.

3. We try to understand if the user is in the last page and we disable the next button
  - We can cache the number of pages until we reach the last page. Since today there is no way to directly go to last page. When we reach the last page we automatically stop the calculation. If the page
  - We can check if the number of records is less than the pageSize and disable the next button and hide the detail on page number and simply say last page or something.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 320 |
| Effort (months)  | 0.5 |

**Comment by iamenrique** [comment]
Looking forward for this fix. Thanks!
