### ISSUE TITLE
[Feature] Users on self-hosted instances should be able to see product updates

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1857]
## Summary

Users running Appsmith in a self-hosted envrionment should be able to see important messages that pertain to their installation. This will be shown as: 
1. A banner on the home page so that editors and viewers can look at the message. The banner should be dismissable and should not show up again incase it's been dismissed by the user.
2. A section called "What's new?" in the home page that links to the release notes for new releases happening with Appsmith.

## Motivation

Currently, we don't have a way to communicate messages with self-hosted instances. This is required to announce:
* New releases
* Link to release notes for each release
* Mark any important changes (such as in privacy policy, telemetry etc). 

## Additional Context

In order to do this, the Appsmith self-hosted instance should deprecate the `PingScheduledTask` which was being used only to measure keep-alive of instances and use it more effectively and fetch the details of any new release (if any) on a regular basis. This ensures that any outbound request made by the Appsmith product delivers value to our user.

The Appsmith cloud instance should store the details of the release and a link to the Github release notes incase there's a new release. It should also have a way for the Appsmith team to write a custom message that will be shown to the user. There will be an optional CTA attached to the message that will direct the user to a more appropriate location to read more information about the message.

**Comment by sharat87** [comment]
If I understand this correctly, I see two ways to implement this feature.

1. Calling home. We have an API endpoint that is active only on the cloud version, and all self-hosted versions call home at this endpoint to get announcements and banners that need to be shown.
1. Include in migrations. We could include this information in the database as part of the migrations and so when a self-hosted instance gets auto-updated, it would get the new announcements and banners to be shown. There won't be a need to call home to any endpoint to get this information.

Personally, I'm leaning towards the second option, but only slightly. Thoughts?

**Comment by aakashDesign** [comment]
@sharat87 @mohanarpit Hey, did some quick mockups, what do you think?

<img width="1279" alt="Screenshot 2020-11-24 at 3 33 09 PM" src="https://user-images.githubusercontent.com/65771350/100079319-848a4f80-2e6a-11eb-8071-ea69be7eeb0c.png">

<img width="1273" alt="Screenshot 2020-11-24 at 3 33 19 PM" src="https://user-images.githubusercontent.com/65771350/100079307-805e3200-2e6a-11eb-8e8e-ac43974a5ed1.png">

**Comment by sharat87** [comment]
I love the "Product Updates" mockup. Looks very to-the-point. Regarding the "What's new" mockup, I think we need to hint somehow there there's just been a new version released and that there's new stuff compared to like yesterday. I also think it's a bit too subtle and hard to notice. I was searching for it for a good 10 seconds even though I knew what I was looking for. I like the position of the "What's new" link though.

**Comment by aakashDesign** [comment]
@sharat87 Updating final designs, let me know if there are any issues.
Figma link - https://www.figma.com/file/WqXNZArTAd1HY3VHOXOsx3/Product-Updates-for-On-prem?node-id=0%3A1

1. What's New bar stickied to the bottom left with count for unseen updates. This should be the way to communicate non-critical updates.
<img width="1336" alt="Screenshot 2020-12-01 at 11 59 36 AM" src="https://user-images.githubusercontent.com/65771350/100705131-b2244b00-33cc-11eb-901e-548e89a8bcad.png">

2. Modal for reading updates after user clicks on What's new. We can auto-open this modal for users if the update is critical.
<img width="1334" alt="Screenshot 2020-12-01 at 12 00 45 PM" src="https://user-images.githubusercontent.com/65771350/100705219-dbdd7200-33cc-11eb-960b-21c18eae3e94.png">

3. Content structure inside modal. Let me know if anything needs to be added/removed.
<img width="1337" alt="Screenshot 2020-12-01 at 12 02 59 PM" src="https://user-images.githubusercontent.com/65771350/100705417-2b23a280-33cd-11eb-83f0-ed390bb561a2.png">

**Comment by sharat87** [comment]
@aakashDesign Perfect. Resolves all the reservations I had with the previous version.

Regarding the third point, perhaps we could add the version number that was released, along with the release date? My reason to do this that major version upgrades vs minor version upgrades both look the same, just dates. If we want them to be differentiable, including version numbers is one way to do it. If we intend to include the version number in the content, then we're good. @mohanarpit, what do you think?

**Comment by areyabhishek** [comment]
@sharat87 @mohanarpit What are your thoughts on how to create these release notes?

**Comment by sharat87** [comment]
I'd like it if the instance can get the release notes from GitHub release. I imagine this should be reasonably simple to implement as well. At startup, the instance can look up the URL `https://github.com/appsmithorg/appsmith/releases/tag/v{{currentVersion}}` (or talk to GitHub's API) to get the details and show them up. This way, dismissing of the "What's new" message can be remembered on a per-version basis.

**Comment by mohanarpit** [comment]
1. Alternatively, why not directly link to the Github release notes itself? Just a thought. 
2. @aakashDesign Apart from the "What's new?" section, we should have an option to highlight important things in the form of a banner on the page. These are important things that we want the user to see regardless of whether they open the "What's new" section or not. We'll use this sparingly, but it'll be an important facet in our communication matrix for self-hosted instances. For example, the addition of telemetry would have been one of those cases where we would have liked to inform the user up-front to check the release notes.

**Comment by sharat87** [comment]
Linking to the GitHub release notes is an even simpler solution. But I thought the point was to have the release notes included in the app itself, as opposed to navigating elsewhere? If that's not the case, then, yeah, linking should work great.

**Comment by aakashDesign** [comment]
@sharat87 Updated the designs with version number button- https://www.figma.com/file/WqXNZArTAd1HY3VHOXOsx3/Product-Updates-for-On-prem?node-id=0%3A1

<img width="1374" alt="Screenshot 2020-12-02 at 6 20 15 PM" src="https://user-images.githubusercontent.com/65771350/100874742-09104a00-34cb-11eb-84ba-5e5c92be48be.png">
<img width="1371" alt="Screenshot 2020-12-02 at 6 20 40 PM" src="https://user-images.githubusercontent.com/65771350/100874801-1c231a00-34cb-11eb-919d-38a66beb1197.png">

**Comment by areyabhishek** [comment]
Link to updated light mode/ dark mode designs for product updates.
<img width="742" alt="Screen Shot 2020-12-15 at 11 17 50 AM" src="https://user-images.githubusercontent.com/30255708/102176323-309de400-3ec7-11eb-9966-dd0529452692.png">
<img width="390" alt="Screen Shot 2020-12-15 at 11 18 13 AM" src="https://user-images.githubusercontent.com/30255708/102176362-3eec0000-3ec7-11eb-9978-def1a272ff7a.png">

Figma links: 
1. Light mode: https://www.figma.com/file/HteDR4ixMWpQyelyYXPuZh/Appsmith-new-designs?node-id=4369%3A469
2. Dark mode: https://www.figma.com/file/HteDR4ixMWpQyelyYXPuZh/Appsmith-new-designs?node-id=4369%3A2

**Comment by sharat87** [comment]
Closed as complete.
