### ISSUE TITLE
[Bug]: MultiSelect Widget crash

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#18578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When option is undefined or when a query for options fail

### Steps To Reproduce

Make a Query for options and let it fail.
No DefaultValue and MultiSelect seem to crash

https://app.intercom.com/a/inbox/y10e7138/inbox/shared/all/conversation/164629100185652?view=List

Link to app on release
https://release.app.appsmith.com/app/arce-bost-mobile-agents/mym-050wa-638726e06f683550e8f14add/edit

QA: Do let me know if you'll need access to the app

### Version

cloud

**Comment by laveena-en** [comment]
@Tooluloope Can you please provide me access to the app? laveena@appsmith.com

**Comment by Tooluloope** [comment]
@laveena-en I've added you
