### ISSUE TITLE
[Bug]-[77]:Dissalowed Value DD.MM.YYYY in the Display Date Format Property of a Column in the Table Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#18572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user is trying to use `DD.MM.YYYY` in the **Display Date Format** property of a table column, but it returns an error: `Dissalowed value`.
![image](https://user-images.githubusercontent.com/101268423/204741089-3c0329d9-dd84-4b6d-83c6-ac66a93509a2.png)

https://community.appsmith.com/t/cannot-set-dd-mm-yyyy-date-format-for-table-column/1694

### Steps To Reproduce

1. Add a **Table widget** to the canvas and bind it to some data (e.g., the `users` sample database). 
2. Try to change the format of a **date** column to `DD.MM.YYYY` in the  **Display Date Format** property.

### Version

Appsmith v1.8.10-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_61f9o)

**Comment by dilippitchika** [comment]
Assuming 10% of date users face this
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 77 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@vsvamsi1 please check this as well

**Comment by dilippitchika** [comment]
@vsvamsi1 the same dd.mm.yyyy works in the datepicker widget but not here in the table, is there a reason?

**Comment by vsvamsi1** [comment]
Hi @dilippitchika, Its very strange on the DatePicker there are no restrictions on the allowed in the formats. You could enter a random incorrect format like in the screenshot and there is no error from our app. For the datePicker it attempts to format what it can infer, whereas in the Table we limit it to a list. Im not sure what is the right behaviour.
![Screenshot 2023-03-21 at 11.03.38 AM.png](https://images.zenhubusercontent.com/63aacee5532b0364c531f322/c299d9f7-c3f2-48cf-aebd-c500184dbe8e)

**Comment by dilippitchika** [comment]
If we are the ones limiting to a list in datepickers inside tables, why can't we add DD.MM.YYYY? Regardind datepicker widget not validating, please create a separate issue

**Comment by vsvamsi1** [comment]
Sure @dilippitchika will do that and this new formats we should support for Display date format .

**Comment by dilippitchika** [comment]
We should support it for both i believe, display and original date

**Comment by ame-appsmith** [comment]
We have [another user on Discord](https://discord.com/channels/725602949748752515/1164543076895821874) who is trying to set the date format programmatically. The formats are supported in a Date Picker widget, but not in the Table Date column. 
Here are some examples of date formats that are disallowed in the Table column but supported in the Date Picker widget:
- DD/MM/YYYY hh:mm:ss A
- DD.MM.YYYY HH:mm:ss A
- MM/DD/YYYY hh:mm:ss A

**Comment by ame-appsmith** [comment]
Another user raised [the same issue on Discord](https://discord.com/channels/725602949748752515/1172100874621952010).

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith a workaround for this is to update the computed value and format it using moment
