### ISSUE TITLE
[Bug]: duplicate scrollbar when scrolling on the release notes modal

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#18584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is a ghost scrollbar on the page when scrolling on the release notes modal

https://www.loom.com/share/78a91dad82c14379b1fe514adc8b1051

### Steps To Reproduce

-

### Issue video log

https://www.loom.com/share/78a91dad82c14379b1fe514adc8b1051

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Non issue
