### ISSUE TITLE
[Deploy Preview]: Custom JS Libraries

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#18593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feedback
Thanks for testing an early deploy preview of [Custom JS Libraries](https://github.com/appsmithorg/appsmith/issues/2430). We would love to hear your feedback and make improvements to the feature. 

Feel free to drop any feedback, bug report, or feature request as a comment down below. If you're unable to get a particular library working, please share the installation URL and our team will look into it. 

### Finding custom JS libraries

1. You can explore libraries on popular CDN services like [jsDelivr](https://www.jsdelivr.com/) or [UNPKG](https://unpkg.com/). Copy a library’s URL and paste it on your app’s Library URL bar to install it. *eg:* [`https://cdn.jsdelivr.net/npm/dayjs@1.11.6/dayjs.min.js`](https://cdn.jsdelivr.net/npm/dayjs@1.11.6/dayjs.min.js)

2. Please ensure that your library supports a [UMD](https://github.com/umdjs/umd) build for it to work on Appsmith. Here’s the [basic pattern](https://github.com/umdjs/umd/blob/master/templates/commonjsStrict.js) of a UMD build. Most libraries will have a `.min.js` under the root or `/umd` or `/browser` folders. If the installation fails, it is most likely that the build you are trying to install isn’t a UMD build. If a library that you wish to use does not support a UMD build, you may use [browserify](https://browserify.org/) to generate one and host it in a CDN of your choice. 

### Platform limitations

Please note that you may not be able to install or use methods of certain libraries due to platform limitations: 

1. [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction) access: Libraries that try to manipulate document objects won’t work. eg: [https://d3js.org/](https://d3js.org/)
2. [XHR](https://www.notion.so/Custom-JS-Libraries-82c03d95918b4eaa8f3e0dd811f3cd00): Libraries that only rely on XHR won’t work. 
3. Other APIs: Library methods that try to access the [window object](https://developer.mozilla.org/en-US/docs/Web/API/Window) or use the following APIs under the hood won’t work: [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/setInterval), [clearInterval](https://developer.mozilla.org/en-US/docs/Web/API/clearInterval), [setImmediate](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate), [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) and [Navigator](https://developer.mozilla.org/en-US/docs/Web/API/Navigator)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_65eoc)

**Comment by oscni** [comment]
Good work done with this feature! ⭐
>Libraries that only rely on XHR won’t work.
Any plans on supporting this? Tried to use CouchDB to get realtime streaming of data but it uses XMLHttpRequest so it doesn't seem to work.
