### ISSUE TITLE
[Task] Tutorial

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1859]
## Concepts Covered
[ ] Building Interactive UI
[ ] Reading & Updating data from a database
[ ] Transforming data to fit into widgets
[ ] Working with multiple pages
[ ] Triggering multiple Queries onPageLoad & onButtonClick
[ ] Validating Forms
[ ] Triggering APIs

https://docs.google.com/document/d/1peAYKRVlQbd1sxHw5DFuDkDGs_MSAmtXUjzBy_3PjWE/edit#

**Comment by Nikhil-Nandagopal** [comment]
@pric-appsmith can you check the scope of these

**Comment by pric-appsmith** [comment]
- [ ] Building Interactive UI
- [ ] Reading & Updating data from a database
- [ ] Transforming data to fit into widgets
- [ ] Working with multiple pages
- [ ] Triggering multiple Queries onPageLoad & onButtonClick
- [ ] Validating Forms
- [ ] Triggering APIs

The tutorIal covers the checked ones.
