### ISSUE TITLE
[Bug]: Upgraded to v1.8.10 and now updatedRow is blank

### ISSUE THREAD

**Issue by alienfacepalm** [appsmithorg/appsmith#18590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

P0 bug. 

Old code accesses a Postgres table like 
```
TABLE_ORGS.updatedRow.id
```
Prior to upgrade worked fine. 
After upgrade all TABLE.updatedRow vars are blank. Entire app is hosed now, I rely on updatedRow for everything.

I saw a similar issue from August, but they said it was fixed. It is NOT fixed. 

### Steps To Reproduce

Create a Postgres DB Query, try to use updatedRow it will be blank

### Version

v1.8.10

**Comment by areyabhishek** [comment]
Hi Brendan, thanks for reporting this. We are looking into this right now.

**Comment by sbalaji1192** [comment]
@alienfacepalm Are you using the cloud or self-hosted version?

**Comment by alienfacepalm** [comment]
For now reviewing with self-hosted, plan on upgrading once I sell it to the
team though. I downgraded back to 1.8.6 and it's fine now.

**Comment by sbalaji1192** [comment]
@alienfacepalm Could you please share a sample app where I can repro the issue?

**Comment by dilippitchika** [comment]
Hi @alienfacepalm this looks like a serious issue, can you please help us out with the steps in detail?

Are you using updatedRow with editing of the table enabled or in some other way?

**Comment by alienfacepalm** [comment]
This appears fixed in 1.8.11 with the updated row change.
