### ISSUE TITLE
[Bug]-[9000]:Datasource save modal appears for a second before being dismissed while switching between datasources

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#18596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/67054171/204973411-f9b8704f-d36f-4617-b655-9eb0cfffebfa.mov

### Steps To Reproduce

Modal appears for a second when switching from a form which is not dirty(has no changes) to a view mode datasource.

### Version

Cloud - Release -  v1.8.11-SNAPSHOT

**Comment by sumitsum** [comment]
Assuming all datasources impacted, 6m usage: 18000
Impacted users % : 25
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4500 |
| Effort (months)  | 0.25 |

**Comment by prapullac** [comment]
Tested on the local and works as expeceted
