### ISSUE TITLE
[Task]: Check if cloning is needed inside parseJSActions function

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#18592]
Since we are only verifying if a function is async or not, we may not need cloning.
If we decide to remove the isAsync check this issue will no longer be valid.

**Comment by Rishabh-Rathod** [comment]
As mentioned above by @rimildeyjsr.  

If [removal of isFunctionAsync determination](https://www.notion.so/appsmith/RFC-JSObject-function-without-sync-async-differentiation-0de440cfae1d419da4c88b6705bb8acf) is picked then that would remove the cloning and hence we do not need to separately work on the above issue.
