### ISSUE TITLE
[Feature]-[2000]: Allow users to fork applications without them being example apps

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1860]
## Summary

Today, only example applications can be forked by users. We should give users a way to mark their public applications as "forkable" and allow those apps to be forked as well. 

## Motivation

It'll be beneficial to our community of users if we provide a set of template applications that are being used within Appsmith or by some of our other users. For example, as a new user, I can take a look at how Appsmith manages Github issues & releases using an Appsmith app. If I like the flow, I should be able to fork this application and bring it into my own organizatioon/workspace and start using it for my personal use. This will be immensely useful for users who are new to the platform and asking the question: "What's possible?"

This is also a segway into application templates.

## Additional Context

Food for thought while designing this feature are:

1. How do we deal with datasources that are linked to the original application? Is there a whitelist of datasources/datasource fields that we will copy over?
2. How will the user mark a given public application as "forkable"? Is there any incentive for an existing user to share their app publicly?
3. How will new users discover these template apps? Will it be primarily through social media? Or will there be a dedicated portal to facilitate this discovery?

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can we copy everything over and treat these like how we do example apps today i.e only we can publish example apps. If this works and people are forking our app, we enable the growth loop feature which allows others to mark apps as forkable

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 0.25 |

**Comment by kocharrahul7** [comment]
This is now enabled using Export-import, as well as forking from one organisation to another
