### ISSUE TITLE
[Feature]: How to use custom style ?

### ISSUE THREAD

**Issue by javaice007** [appsmithorg/appsmith#18618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

How to use custom style and custom css?

### Why should this be worked on?

Used in project development

**Comment by dilippitchika** [comment]
Hello @javaice007  it's an open issue for us, please check this issue - #3095

**Comment by ichik** [comment]
@javaice007 Hi. We've been working on a revamp of our layout and theming engines that should facilitate faster, more predictable, and more consistent styling of the widgets. While that is still work-in-progress the team wants to properly evaluate a common request for custom CSS, that has been asked by the community.
To that end I'd be interested in talking with you, to see what kind of ideas you have.
You can schedule [a call with me](https://www.getclockwise.com/c/vadim-appsmith-com/quick-meeting) if you're willing to talk or [drop me an email](mailto:vadim@appsmith.com).
