### ISSUE TITLE
[Bug]: Unable to initialise a JSObject variable 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#18631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I reinitialize a JSObject with a different value, the variable still retains the previously assigned value. A page refresh is required for the reinitialization to take effect. 

```
export default {
       // try assigning a new value to myVar1 or myVar2
	myVar1: [],
	myVar2: {},
	myFun1: () => {
		//write code here
		return this.myVar1
	},
	myFun2: async () => {
		//use async-await or promises
	}
}
```

### Steps To Reproduce

1. Create a new JSObject
2. Change the value of `myVar1` from `[]` to `1`
3. Add a return statement on `myFun1` to return myVar1's value `return this.myVar1`
4. Run the function
5. Notice that `myFun1` returns `[]` instead of `1`
6. Refresh the page and run the function again 
7. Notice that `myFun1` now returns `1`

### Version

Cloud

**Comment by bharath31** [comment]
@satbir121 can we run an RCA on this?

**Comment by bharath31** [comment]
Duplicate of #14568

**Comment by ramsaptami** [comment]
@bharath31 duplicate issue of #14568 & #14864 perhaps?
