### ISSUE TITLE
[Bug]-[600]:The dropdown for currency code change doesn't open in the first click when the focus is in the input box

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#18648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The dropdown for currency code change doesn't open in the first click but gets dismissed when the focus is in the input box

### Steps To Reproduce

1. DnD a currency widget
2. allow currency code change from property pane
3. shift the focus to the input box of the widget
4. click on the country icon to get the dropdown

### Issue video log

https://www.loom.com/share/e1f03771a56d4015af58fad17d2d6915
### Version

production

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 600 |
| Effort (months)  | 0.5 |

**Comment by kamakshibhat-appsmith** [comment]
@dilippitchika I dont see this issue with phone widgets . 
The loom you shared points to a different issue .I think you might be referring [this](https://github.com/appsmithorg/appsmith/issues/18561)

**Comment by somangshu** [comment]
This issue done not exist anymore on edit / view mode.

https://user-images.githubusercontent.com/11089579/232449434-9f059bdb-bd67-4416-803f-d15b2bc85ec5.mov

Closing this. cc @kamakshibhat-appsmith
