### ISSUE TITLE
To scroll all lines in 1 single page like google sheets

### ISSUE THREAD

**Issue by ocorporativodigital** [appsmithorg/appsmith#18651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

How can i scroll all lines/row in just 1 single page? 
I want to have all the lines on a single page and remove the option to change pages

### Why should this be worked on?

How can i scroll all lines/row in just 1 single page? 
I want to have all the lines on a single page and remove the option to change pages

**Comment by dilippitchika** [comment]
Hi this is an open issue in appsmith - https://github.com/appsmithorg/appsmith/issues/13921

For now you can 
1. Turn on Server side pagination
2. Turn off show pagination
As a workaround to acheive this
