### ISSUE TITLE
[Feature]: Apply RBAC on all Git Branches

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#18669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

RBAC does not successfully apply on Git branches because git follows the old import mechanism

### Why should this be worked on?

RBAC on git is critical for security

**Comment by hiteshjoshi** [comment]
https://github.com/appsmithorg/appsmith-ee/pull/772
