### ISSUE TITLE
[Bug]: Not able to create new workspaces in the  release

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No able to create new workspaces in the release
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/205554708-cf1789a6-74a1-4529-9804-83a1bf64d1c1.png">

### Steps To Reproduce

1. Login with any email id
2. on the left pane the create new workspace link is missing

### Version

release

**Comment by ankitakinger** [comment]
This issue is re-occuring. Hence re-opening the issue.
