### ISSUE TITLE
[Feature]: Helm chart: Read misc passwords from Kubernetes secrets 

### ISSUE THREAD

**Issue by schack** [appsmithorg/appsmith#18671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The Appsmith configuration contains several passwords/secrets in the applicationConfig.* section.
It would be good if these could be read from Kubernetes secrets instead of appearing in the setup script.

### Why should this be worked on?

Scripts for configuring Appsmith are likely to be committed to Git, that's not a good place to store secrets :-)

**Comment by pratapaprasanna** [comment]
Please use the latest helm charts in helm-ee.appsmith.com . We have added the ability there
