### ISSUE TITLE
[Bug]: Dropdowns in the property pane aren’t using the standard font.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#18677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/109572422/205605923-262d4cf9-1eb1-44fd-94c4-60cdf5d00c6c.png)
![image](https://user-images.githubusercontent.com/109572422/205605999-84f30185-ae87-4830-813d-96bb7505040b.png)

### Steps To Reproduce

Observe drop-downs in the property pane on dropping a widget.

### Version

Release

**Comment by tanvibhakta** [comment]
This issue happens only on some dropdowns likely due to this code: https://github.com/appsmithorg/appsmith/blob/8b0662160198672c985af70a62436e7a278918a6/app/client/src/components/propertyControls/StyledControls.tsx#L130-L141

Have reassigned the issue.
