### ISSUE TITLE
[Bug]: Slug path looses redirection param when user login fails

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#18670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On a private app where a user has to login to access app, the redirection path gets lost when user login fails so user is redirected to the home page and not the app link
- [x] #21750

### Steps To Reproduce

1. Use a private shared link to access an app on incognito
2. Cause a failed login attempt and notice the URL slug looses the `redirection` query param
3. Logging in correctly now causes the user to land on the Appsmith homepage and not the shared app link. User needs to reenter the shared URL to land on the correct page

![image](https://user-images.githubusercontent.com/79509062/205583407-2176d0d3-26a4-4fe7-9fb2-001eccfec9a6.png)

![image](https://user-images.githubusercontent.com/79509062/205583334-19fc7849-7a95-4fc4-8261-5a49c2330c40.png)

### Version

Cloud

**Comment by eco-monk** [comment]
Not related to clean url's.
This is a general bug in the login flow.
https://www.loom.com/share/e5384ee2938d4fb9b39e2f22bdaaf585

**Comment by eco-monk** [comment]
This needs to be fixed in the backend.

# Problem:
Right now, upon login failure we don't send back the redirect url.
`https://dev.appsmith.com/user/login?error=true`
https://www.loom.com/share/71349aee40544fb5b465f25fc9cb701c


# Solution:
It should include the redirect url for this to be fixed.
`https://dev.appsmith.com/user/login?error=true&redirectUrl=https%3A%2F%2Fdev.appsmith.com%2Fapp%2Fprivate-app%2Fpage1-64101d008ceea003546887e4`
https://www.loom.com/share/a5bd24aa541c4d578b265c09dec578e0

**Comment by Richarex** [comment]
Tested this on the DP url, it's working as expected.

**Comment by Richarex** [comment]
Tested this on the DP url, it's working as expected.

**Comment by Richarex** [comment]
Tested this on the DP url, it's working as expected.

**Comment by Richarex** [comment]
Tested this on the DP url, it's working as expected.

**Comment by Richarex** [comment]
Tested this on the DP url, it's working as expected.

**Comment by ramsaptami** [comment]
Seeing a 503 message after login. Need to refresh the page to see the app I was trying to access.
![image](https://user-images.githubusercontent.com/79509062/229468470-a9007300-da95-4e4f-81e4-13af4bd7016a.png)

Is this related to the fix here? - or raise a separate issue?

cc: @Richarex, @NilanshBansal

**Comment by NilanshBansal** [comment]
This is not related @ramsaptami
