### ISSUE TITLE
[Bug]: Hubspot is broken wrt POST commands 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#18674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user tries access Hubspot command after saving the datasource it is observed that the other fields wrt to the command selected does not appear 

### Steps To Reproduce

1) Add Hubspot Datasource
2) Click on Add new Datasource
3) Select "Create Table"
and observe

<img width="1278" alt="Screenshot 2022-12-05 at 2 24 30 PM" src="https://user-images.githubusercontent.com/71753653/205595715-567f3ab5-4b5f-49dc-9f05-e9dc42c7171a.png">

### Version

Release

**Comment by rohan-arthur** [comment]
hi @prapullac tested the steps above in release, this is working for me. Would you please check again?
https://images.zenhubusercontent.com/275993885/a1efca23-ab03-409f-9ddf-2f32e27d6576/screen_recording_2022_12_05_at_17_25_09.mov
