### ISSUE TITLE
[Bug]: Mustaches `{{}}` within input value are evaluated  

### ISSUE THREAD

**Issue by GENL** [appsmithorg/appsmith#18686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As a user, when I type a text containing the binding characters into an input field, the binding characters get evaluated as `null`.

### Steps To Reproduce

Given an input field `templateField` and a text written into it `Hello {{name}}, this is a template text.`. When I try to read this value to pass it as a request parameter like `{{templateField.text}}`, `{{name}}` is evaluated as `null`. So I and up with  `Hello null, this is a template text.` where I expect  `Hello {{name}}, this is a template text.`

My assumption is, appsmith considered {{name}} as data to bind and tries to evaluate it, but as `{{name}}` doesn't exist it returns null. Same for `Hello {{1}}`.

Here, I don't want `Hello {{name}}` or `Hello {{1}}` to be evaluated, but instead return as it is, so the exact text typed by the user can be recorded into the database. 

Proposed solution: provide another binding character that does not try to evaluate text inside a variable.

### Version

Self hosted - 1.8.6

**Comment by bharath31** [comment]
@GENL you can escape the {{}} evaluation for name by using this workaround: `{{"Hello {{name}}, this is a template text"}}`
