### ISSUE TITLE
[Bug]: Error is displayed for page name which does not have special character

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#18685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add the special character to the page name, Verify it displays error, Click on other page which has right page name, Error is displayed for that page

![image](https://user-images.githubusercontent.com/80756091/205622975-bce7181e-748a-4945-bed4-7a5e02f59c91.png)

### Steps To Reproduce

1. Click on '...' and setting for page1
2. Change the page name as page1_123
3. Error is displayed as only alphanumeric values are allowed
4. Click on page2 and verify error is displayed for Page2

### Version

cloud-release

**Comment by eco-monk** [comment]
I believe this is caused by #17393.
Will investigate this to see if there are any workarounds.

**Comment by ginilpg** [comment]
@eco-monk Error messages should be cleared when we open a new page's setting

**Comment by AnandiKulkarni** [comment]
@eco-monk this error message doesn't look good and taking space down. Not sure if design is discussed.

**Comment by eco-monk** [comment]
@AnandiKulkarni, we're using design system error messages for this, so there wasn't much to discuss.
It overlays on top of other components. So, We have added space manually for this.

This already mentioned in #17393. Please add your thoughts to this.

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 @eco-monk in this case, it should not overlap and push the rest of the components down right?
This obviously looks bad

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk I get the problem, I'm just saying lets fix it. We don't have to wait for the design system team, this seems like a simple component fix that we can contribute to that repo

**Comment by eco-monk** [comment]
Thanks @Nikhil-Nandagopal.
I thought, design-system was closed for contribution. Since there was nothing mentioned in the [main readme.md](https://github.com/appsmithorg/design-system/blob/main/README.md).
Just got to know about [this document](https://github.com/appsmithorg/design-system/blob/main/packages/design-system/README.md) nested inside.
Will use this as reference for future issues I run into.

For now, they've fixed this and it should be ready soon.

**Comment by eco-monk** [comment]
#18739
