### ISSUE TITLE
[Bug]: Error in data type handling

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#18683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a text `123-test` in the input widget and reference it in an API body, it gets evaluated as `"123-test"` and not `123-test`. 
![image](https://user-images.githubusercontent.com/55969597/205617694-e589024f-df1c-4d90-9ea6-056cb567ea47.png)
![image](https://user-images.githubusercontent.com/55969597/205617720-669b0a7d-88fa-460a-bedc-eb417f6b22bb.png)

### Steps To Reproduce

1. Create a new app and add an input widget on the canvas
2. Type `123-test` in the input widget
3. Reference it in the API body 

### Version

Cloud - 1.8.11

**Comment by nidhi-nair** [comment]
This is a smart substitution problem. We're looking at the value, gathering that it is a string without immediate quotes around it and adding the quotes ourselves. Data type handling allowed us to correctly recognize the value as a string and that's all. Do we want to solve for this within smart substitution? If yes, then I'd say this is a feature request to understand context around the binding.

**Comment by nidhi-nair** [comment]
Yes, I think the way this works has always been with immediate surroundings. That's the reason the value of the second property `bitlink_id` evaluates correctly. We've always suggested to users that they absorb the other part of the string into the JS binding as well, as `{{ "bit.ly/"  + Input1.text }}`

**Comment by sribalajig** [comment]
This issue is similar to the one reported [here](https://github.com/appsmithorg/appsmith/issues/17027).

**Comment by riteshkew** [comment]
Closing this instead of one reported [here]( https://github.com/appsmithorg/appsmith/issues/17027).
