### ISSUE TITLE
[Bug]: For query executions, the error tab is shown even when the query execution does not have any errors

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#18694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there is an error in the logs and the error log is open while I execute a query, if the query has executed successfully, I expect the response of that query to be shown and not the error log.
![Uploading hidden-results.png…]()

### Steps To Reproduce

1. Generate an error in the logs
2. Go to the query execution page for a valid query and open the error logs there.
3. Execute the query.
4. Although the query executed successfully, you will still see the error logs in focus. 
5. Since the query actually executed successfully, I expect the results to be shown instead.

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@sribalajig I think you submitted before your image was uploaded

**Comment by rohan-arthur** [comment]
not reproducible anymore
