### ISSUE TITLE
[Bug]: Duplicate page name are not allowed from Page manu but it is allowed from setting page

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#18698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Try to add same page name from Page manu and verify error is displayed as &Page& name is already being used 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/80756091/205645398-82267344-27e5-47e0-9c1c-2622c324bcd9.png">

Navigate to setting page and verify that the User is able to add duplicate page name 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/80756091/205645771-72f0f2ab-c90c-4df1-83d7-a968c0a97611.png">

### Steps To Reproduce

1. Click on add new page
2. Edit a Page name with already existing page name
3. Error is displayed that page name already exist
4. Navigate to page setting page and verify that user is able to add duplicate page name

### Version

Cloud -release

**Comment by Nikhil-Nandagopal** [comment]
This is high because if we allow it, it can break the entire app
