### ISSUE TITLE
[Feature]: Add localStorage support for Custom JS Libs

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#18708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow Custom JS Libs to access localStorage and sessionStorage APIslocal storage

### Why should this be worked on?

Libraries that depend on localStorage and sessionStorage APIs don't work as expected due to framework limitations. Adding support for storage APIs would increase compatibility. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_65emk)

**Comment by bharath31** [comment]
@arunvjn can we close this one out?

**Comment by arunvjn** [comment]
Yes, task completed in https://github.com/appsmithorg/appsmith/pull/19789
