### ISSUE TITLE
[Bug]: client compilation error: Toaster

### ISSUE THREAD

**Issue by fliot** [appsmithorg/appsmith#18703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When compiling the client, I get such error
```
Failed to compile.

TS2307: Cannot find module 'components/ads/Toast' or its corresponding type declarations.
    3 |
    4 | import { collabSetAppEditors } from "actions/appCollabActions";
  > 5 | import { Toaster } from "components/ads/Toast";
      |                         ^^^^^^^^^^^^^^^^^^^^^^
    6 | import {
    7 |   createMessage,
    8 |   INFO_VERSION_MISMATCH_FOUND_RELOAD_REQUEST,
```

Please note my environement was successfully compiling the client in version 1.8.5, and I face this issue for 1.8.10 and 1.8.11.

### Steps To Reproduce

```
cd app/client
yarn add @sentry/webpack-plugin --dev
npx browserslist@latest --update-db
./build.sh
```

### Version

1.8.11

**Comment by albinAppsmith** [comment]
@fliot is the codebase up to date? Because line number 5 looks different in the screenshot you have attached.
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/WebsocketSagas/handleAppLevelSocketEvents.tsx

**Comment by fliot** [comment]
Indeed, my very bad.....
Very good seen,
Great thanks for your support.
