### ISSUE TITLE
[Bug]-[35840]:API Headers - new line character is lost after Navigating to another page and returning to the API

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I reference an Input (or any widget) in an API, and the reference has new line character in it, if I move away to another page and get back to the API, it is seen that the new line is lost. 

### Steps To Reproduce

1. Create a new Page, say Page3, and drag and drop an input widget say Input1
2. Create a new api (Api1) and in the Headers tab, in the Value section, add the binding 
{{
Input1.text
}}
3. Navigate to Page1, and then return to Api1. 
4. Note that the binding is now showing up as {{Input1.text}}
The new line characters are lost

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/m0dAXHeTAitF7CWk

### Version

Production

**Comment by sneha122** [comment]
6m usage for REST API: 5600
Assuming 80% of users face this: 4480

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4480 |
| Effort (months)  | 0.25 |
