### ISSUE TITLE
[Bug]: On an offline host, git connect to privately deployed gogos, gitea will return error

### ISSUE THREAD

**Issue by mousheng** [appsmithorg/appsmith#18728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sometimes when the computer is disconnected from the internet, the git cannot connect to the gogos and gitea deployed locally, and shows some errors .Hope to fix ，thanks

### Steps To Reproduce

1.appsmith and gogos or gites on same host
2.disconnected from the internet
3.git connection to like url:ssh://git@localhost:22:test/test.git
4.show error:Internal server error while processing request
and error logs:
backend stdout | [2022-12-06 14:43:17,979] userEmail=xxxxxx@xx.com, sessionId=333e5feb-b70c-4bdb-80ad-55af9865f9ae, thread=reactor-http-epoll-4, requestId=8c2fba8d-9bff-4fb1-bf06-b1f1f807c101 -
backend stdout | org.springframework.web.reactive.function.client.WebClientRequestException: cs.appsmith.com: Name or service not known; nested exception is java.net.UnknownHostException: cs.appsmith.com: Name or service not known
backend stdout |        at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
backend stdout |        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
backend stdout | Error has been observed at the following site(s):
backend stdout |        *__checkpoint ⇢ Request to GET null [DefaultWebClient]
backend stdout |        *__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#connectApplicationToRemoteRepo(String, GitConnectDTO, String) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout |                at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)
backend stdout |                at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
backend stdout |                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout |                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
backend stdout |                at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
backend stdout |                at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerError(FluxConcatMap.java:309)
backend stdout |                at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onError(FluxConcatMap.java:875)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.Operators.error(Operators.java:198)
backend stdout |                at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
backend stdout |                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout |                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:451)
backend stdout |                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
backend stdout |                at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:491)
backend stdout |                at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:299)
backend stdout |                at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
backend stdout |                at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
backend stdout |                at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:190)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
backend stdout |                at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:304)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
backend stdout |                at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:155)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
backend stdout |                at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:477)
backend stdout |                at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431)
backend stdout |                at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:194)
backend stdout |                at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:538)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.Operators.error(Operators.java:198)
backend stdout |                at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
backend stdout |                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
backend stdout |                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
backend stdout |                at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onError(MDCConfig.java:58)
backend stdout |                at reactor.core.publisher.Operators.error(Operators.java:198)
backend stdout |                at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
backend stdout |                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout |                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
backend stdout |                at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:596)
backend stdout |                at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:516)
backend stdout |                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
backend stdout |                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
backend stdout |                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
backend stdout |                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
backend stdout |                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout |                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout |                at java.base/java.lang.Thread.run(Thread.java:829)
backend stdout | Caused by: java.net.UnknownHostException: cs.appsmith.com: Name or service not known
backend stdout |        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
backend stdout |        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
backend stdout |        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529)
backend stdout |        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
backend stdout |        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
backend stdout |        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
backend stdout |        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
backend stdout |        at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:169)
backend stdout |        at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:166)
backend stdout |        at java.base/java.security.AccessController.doPrivileged(Native Method)
backend stdout |        at io.netty.util.internal.SocketUtils.allAddressesByName(SocketUtils.java:166)
backend stdout |        at com.appsmith.util.WebClientUtils$NameResolver.doResolveAll(WebClientUtils.java:137)
backend stdout |        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79)
backend stdout |        at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:71)
backend stdout |        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:73)
backend stdout |        at io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:31)
backend stdout |        at io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:158)
backend stdout |        at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:300)
backend stdout |        at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:127)
backend stdout |        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
backend stdout |        at reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:596)
backend stdout |        at reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:516)
backend stdout |        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
backend stdout |        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
backend stdout |        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
backend stdout |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
backend stdout |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend stdout |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend stdout |        at java.base/java.lang.Thread.run(Thread.java:829)

### Version

v1.8.11

**Comment by hiteshjoshi** [comment]
@mousheng
Based on your logs line 3 ```git connection to like url:ssh://git@localhost:22:test/test.git```

Unfortunately, since Appsmith runs inside a docker. We cannot communicate with the localhost here is how to interact with the local network from docker. https://stackoverflow.com/a/24326540

Also, based on your logs, it seems like the Appsmith instance cannot communicate with cs.appsmith.com, which I assume is happening because of network failure. 

An Appsmith instance can only entirely run in an environment with internet access. For some data sources like Gsheet and Git, we use a central cloud server hosted at cs.appsmith.com
Please note none of your data at any point is shared with cs.appsmith.com, but it's used to perform critical actions like callback URLs and related things.

And without internet access, you'll not be able to use Git. 

I am closing this for now, please reopen if you have more questions or details in this context.
