### ISSUE TITLE
[Bug]-[35840]:API - New line is lost in a binding, on navigating to a different page and getting back

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When in an API, I bind Value 2 of Headers to say an input widget and the binding has new line characters included, on navigating to a different page and coming back to this API, I see that the new line is lost within the binding

### Steps To Reproduce

1. Drag and drop a widget, say Input1 on Page1
2. Create a new api API1, and in the headers tab, **Value2** section, enter a binding like this - 
{{
Input1.text
}}
3. Navigate to say Page2 and then come back to Page1 and open this API1
4. Note that **Value1** has curly braces automatically entered and Value2 has lost the new line characters.

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/RsXhctN9FuQ8cBNb

### Version

Production

**Comment by sneha122** [comment]
6m usage for REST API: 5600
Assuming 80% of users face this: 4480

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4480 |
| Effort (months)  | 0.25 |
