### ISSUE TITLE
[Bug]-[72]:Submit gets unclickable after deleting all array item from JSONForm

### ISSUE THREAD

**Issue by adarshverma07** [appsmithorg/appsmith#18752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/70b55b90403c4f10aefb15f1adb1799c

### Steps To Reproduce

1 Add JSON form onto a canvas
2 Add a new field as Array and let the field be a required field
3 Click on 'Add New' in the form to add more array items and let them be empty
4 Now delete all the entries and Observe that submit is not clickable

### Version

1.8.3

**Comment by kamakshibhat-appsmith** [comment]
hi @adarshverma07 Thanks for sharing .

**Comment by dilippitchika** [comment]
This is a bug, but a better fix would be to introduce validation on the arrays min and max items as well to make it more powerful

**Comment by dilippitchika** [comment]
All users who set any array field to required in json form
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 18 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
Got it, thanks Kamakshi
