### ISSUE TITLE
[Bug]: 404 error page after resetting password

### ISSUE THREAD

**Issue by xolyu** [appsmithorg/appsmith#18766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After successfully resetting the password, I get the following 404 error message every time:

![appsmith_404_error](https://user-images.githubusercontent.com/5889376/206275645-47519bb5-2094-4eff-a0cd-ae6c43e5e688.png)

What I expected is that I will be redirected to the sign in form.

### Steps To Reproduce

1. I fill in my email address in the "Reset password" form (/user/forgotPassword)
2. I got an email "Appsmith Password Reset" and clicking the "Reset Password" button
3. Type in the "New password" and clicking the "Reset" button
4. Got the 404 error page
   > **Oops! Something went wrong**
   > Please try again using the button below.
   > If the issue persists, please contact us

### Version

Self Hosted - v1.8.11

**Comment by sharat87** [comment]
Same as https://github.com/appsmithorg/appsmith/issues/18086, fix coming up in the next release.

The password change actually takes affect. So you can go back to the login page and use your new password to login.
