### ISSUE TITLE
[Bug]: Content-type Header Changes on its own

### ISSUE THREAD

**Issue by ClarksonCote** [appsmithorg/appsmith#18767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on a POST/GET endpoint query in Hubspot, (possibly when viewing the body of the query), when the header's `content-type` is `application/sql`, the act of clicking on the endpoint body changes this `content-type` to `text/plain`, breaking the endpoint functionality until I go back in to manually change the content-type back

### Steps To Reproduce

1. Create a POST or GET to an endpoint.
2. Under the Header tab, add a key of `content-type` and a value of `application/sql` or `application/graphql` (There may be other types affected too?)
3. Under the Body tab, add a relevant query.
4. Go back and look at the Header tab, and `content-type` will have changed to text/plain

Once the endpoint query is created, even the act of clicking the Body Tab, and then going back to selecting the Header Tab, will cause the `content-type` to change to the wrong `text/plain` value again. This is particularly annoying since it breaks the App each time and you need to manually change `content-type` back to the correct value.

### Version

Self Hosted

**Comment by ClarksonCote** [comment]
@Nikhil-Nandagopal see attached.
https://user-images.githubusercontent.com/99921274/206474765-32f4453a-4b52-4b3f-bd9b-bb8fd6784e4a.mov

**Comment by ClarksonCote** [comment]
@Nikhil-Nandagopal sure, please see attached.

https://user-images.githubusercontent.com/99921274/206479066-da66d0d2-a2a0-4282-b2e1-ed4d09857a87.mov

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur @sumitsum can we please fix this? This seems like an obvious bug

**Comment by rohan-arthur** [comment]
thanks for reporting this, it is an annoying bug indeed. We are working on it in issue #18473

**Comment by ClarksonCote** [comment]
@rohan-arthur thank you.
