### ISSUE TITLE
[Bug]:  Query doesn't reload my data in JSObject and WIdget

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#18774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I reload/ re-run the Query, I should get fresh data in JSObject and Widget

### Steps To Reproduce

Using a `splice` function to alter the data in-place

https://user-images.githubusercontent.com/31691737/206377132-e5e0de63-8843-4b7d-a2ff-024688b07ddd.mov

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope this is because you are using a static variable. We have an issue open for this already #14568 #18088

**Comment by bharath31** [comment]
@Nikhil-Nandagopal `myVar2` is actually a function in the above code
