### ISSUE TITLE
[Bug]: The home page icon is displayed for both old home page and new home page in roles page 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The home page icon is displayed for both old home page and new home page in roles page 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/206350540-de01db55-a419-49dc-9f0d-83b824ea04b8.png">

### Steps To Reproduce

1. Add a new app
2. Now the page one is a home page by default 
3. Generate a new crud page(thats page 2)
4. Now set page2 as home page
5. Now go to a roles tab
6. Check the Pages the home icon is displayed for both the pages

### Version

localhost

**Comment by ankitakinger** [comment]
This is expected. We show you a union of edit and view pages and hence you would see both the home pages aka home page in edit mode and home page in view mode
