### ISSUE TITLE
[Bug]: In Active tab the delete menu is displayed even when we dont have delete access for a database

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Active tab the delete menu is displayed even when we dont have delete access for a database
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/206461176-e4a1d86b-d50f-4ef8-b3bb-3254756daed3.png">

### Steps To Reproduce

1. create a app 
2. create a database
3. now give edit, create and view access to it
4. now assign this role to user 1
5. Login as user 1
6. Go to active tab 
7. click on meat ball icon next to database
8. The delete menu is enabled even when the access is not given

### Version

localhost

**Comment by berzerkeer** [comment]
The FE changes are done, but this also needs BE change.  Even after removing the said permissions, client still gets it from the server.
https://www.loom.com/share/3229293f81bf452e838cc7d4f4593d27

@trishaanand @RakshaKShetty
