### ISSUE TITLE
[Docs] Add documentation for the Firestore plugin

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1879]
## Documentation Link 

We need to add documentation on how to use the Firestore plugin

This should be available at: https://docs.appsmith.com/core-concepts/connecting-to-databases/querying-firestore

**Comment by serwer20** [comment]
Hi, also need this docs.
I don't understand field "Service Account Credentials"
, which credentials? To database secret like this? => DkgrgAHstvLju30XXXXXXzmdJ6mujXXdbT5LRX or what instead? 
Please help :)
Happy New Year BTW :D

**Comment by sharat87** [comment]
@serwer20 Happy New Year to you too!

Appsmith does indeed support Firestore and we have a few people with apps connecting to their Firestore instance. Unfortunately, as you pointed out, the docs weren't ready. I opened a [PR for this](https://github.com/appsmithorg/appsmith/issues/2426) just some time ago, which you can check out / review.

For your specific question though, the service account credentials is the content of the JSON file that is generated when we click on "Generate new private key" in your Firestore project settings. The whole JSON contents of this file is to be pasted in this field on Appsmith. The document in the linked PR contains additional details as well.

**Comment by sharat87** [comment]
This is now live at the URL posted in the issue description.
