### ISSUE TITLE
[Bug]: Default User Role shows up in groups and roles tab and not on Roles Page

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are seeing Default User Role under Roles section of groups & roles tab, however this Role doesn't show in Roles page. If not required we should remove it from the groups and roles tab also.
<img width="1434" alt="Screenshot 2022-12-09 at 11 04 36 AM" src="https://user-images.githubusercontent.com/80334441/206632182-aff26da3-0fa8-4c66-b495-4d84e19cd614.png">

### Steps To Reproduce

1. Login as super admin
2. Go to roles page
3. Go to Groups&Roles tab
4. Under Roles section, observe "Default User Role" is also shown

### Version

http://65.0.99.89/

**Comment by nsarupr** [comment]
Need information about what needs to be done here.
Whether it should be removed from there or should it be shown everywhere
@trishaanand

**Comment by trishaanand** [comment]
This issue has been fixed : https://github.com/appsmithorg/appsmith-ee/pull/835
