### ISSUE TITLE
[Task]: Check launching instance with cloud-run on gcp

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#18800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by yan-hic** [comment]
@pratapaprasanna what was the outcome of this ? Wanted some feedback before we are heading to cloud run for the same.
Ideally an official guide on the pitfalls, limitations when deploying on CR. A VM does not scale to zero.

**Comment by sharat87** [comment]
Closing this as duplicate of #23522, since there's more description there.

@yan-hic, update, we're working on this already and will very likely have docs for setting up Appsmith on CloudRun soon. Thanks! 🙏
