### ISSUE TITLE
[Feature]: CMD Click for string references

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#18808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We support cmd click for direct navigation to code references. We can also allow for string references to other entities like:

- showModal("Modal1")
- resetWidget("Input1")

### Why should this be worked on?

Such references are helpful in navigation

**Comment by rohan-arthur** [comment]
won't fix - project cancelled
