### ISSUE TITLE
[Bug]: Forking the app to the new workspace which has create access throws "resource not found error"

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Forking the app to the new workspace which has create access throws "resource not found error"
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/206633433-0f5a5174-e7ae-4c93-a4e4-23994af377fe.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/206633462-abb1c1a1-16f8-4d95-8a3f-56e3c9f77107.png">

### Steps To Reproduce

1. Go to admin setting
2. Check you should have 2 workspace
3. One workspace give just edit and view access
4. 2nd workspace give all crud access
5. Now assign it to user 1
6. Login as user 1
7. click 3 dot iconon app1 in workspace 1
8. Now click on fork menu
9. select workspace 2
10. Clcik on fork 
11. The resource not found error is displayed

### Version

localhost

**Comment by trishaanand** [comment]
Not reproducible with an empty app, app with pages and apis without datasources. This is only reproducible if you have datasource in the original app and the user does not have create datasource permission in the destination workspace. Please give create datasource permission to resolve this state.
