### ISSUE TITLE
[Bug]: When new line characters are used within binding, after refactoring, the braces lose their color

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#18813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With new line characters, when refactoring happens, the curly braces lose their dark blue color

### Steps To Reproduce

1. Drag and drop a text and an input widget.
2. Bind the label of the Input widget to the Text widget like - 
{{
Text1.text
}}
3. Change the name of the text widget. 
4. Note that in the binding reference, the dark blue colors of the binding are lost .

<img width="727" alt="AST_BindingColorLost with newline char" src="https://user-images.githubusercontent.com/101863839/206650748-4ffe4035-7072-468e-916c-9541c53a93f9.png">

### Version

Release

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/user-attachments/assets/11ad77e5-fbe6-4d11-9c0e-0880f579626b
