### ISSUE TITLE
[Bug] Property controls flicker before persisting value

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1883]
## Description
In some scenarios, the property control value flickers back to original value before the new value is persisted, after the user edits the value
### Steps to reproduce the behaviour:
![property-control-flicker](https://user-images.githubusercontent.com/103687/100081364-eea3f400-2e6c-11eb-8391-06d8398d9869.gif)

**Comment by marks0351** [comment]
@Nikhil-Nandagopal are you still seeing this?
I tried it with the example in the demo and a few other ways, wasn't able to reproduce it.

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 yay another magical fix. Closing this
