### ISSUE TITLE
[Task]: Audit Logs - Increase Cypress Test Coverage

### ISSUE THREAD

**Issue by vishnu-gp** [appsmithorg/appsmith#18849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently, the Cypress Tests related Audit Logs don't have enough coverage.
- Increase coverage to incorporate all possible Audit Log events
- Verify JSON payload, event name, event description (very important as this is FE generated)
- Clean code to avoid direct usage of strings like "`Untitled Application 1`"

**Comment by riteshkew** [comment]
Not relevant anymore.
