### ISSUE TITLE
[Bug]: Not able to see all admin settings for super admin, not able to create new workspace as well.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/206917154-a3e6baac-0cbc-468e-bea4-f3f5a6b52ba2.mov

<img width="1434" alt="Screenshot 2022-12-11 at 10 22 38 PM" src="https://user-images.githubusercontent.com/80334441/206917289-03fe1235-3eff-4ad6-8eb7-f7fc7b285263.png">
 
Logs: [logs.txt.zip](https://github.com/appsmithorg/appsmith/files/10202742/logs.txt.zip)

### Steps To Reproduce

1. Sign up as super admin on branch feature/rbac-ee

### Version

http://65.0.99.89/

**Comment by ankitakinger** [comment]
@trishaanand @nsarupr 
Debugged this. Tenant permissions are blank in the API response. Hence the issue.
<img width="404" alt="image" src="https://user-images.githubusercontent.com/28362912/206972060-4745a91f-16aa-4b74-ba43-6887fa42bcbc.png">

**Comment by Parthvi12** [comment]
@ankitakinger Along with this, we are seeing the sign up modal again after completing onboarding, which is an issue.

**Comment by Parthvi12** [comment]
This is fixed
