### ISSUE TITLE
[Bug]:  On the Home page, the font of the appsmith logo on the left top corner seems very small consider to the other two tabs

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 On the Home page, the font of the appsmith logo on the left top corner seems very small consider to the other two tabs text
 In release :
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/206855189-463363ab-0af0-44fe-8f67-33cb070047a2.png">

In Prod: <img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/206855060-9ccef57c-9578-4af4-8d89-b1039e516689.png">

### Steps To Reproduce

1. Login to the application
2. in the home page
3. On the left top corner 
4. the appsmith text seems to be smaller than the text of the tabs displayed next to it

### Version

release

**Comment by Nikhil-Nandagopal** [comment]
I think this is by design since it's an image and not a text so it's expected
