### ISSUE TITLE
[Bug]: New menu item titles are misaligned 

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#18867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we add new menu items in the Button Group widget, they are not aligned with the rest of the menu items by default.

<img width="410" alt="Screenshot 2022-12-12 at 11 54 48 AM" src="https://user-images.githubusercontent.com/39921438/206976046-99b1ce60-356a-44bd-83be-9fb5f87d9fa3.png">

### Steps To Reproduce

1. D&D a Button Group widget.
2. In the property pane click on the settings for the `More` button.
3. Click on `Add a new Menu Item`.

### Version

Cloud

**Comment by dilippitchika** [comment]
@dhruvikn assigning this to you since you fixed it in menu button. Can we close it this sprint? don't want to keep this hanging.
