### ISSUE TITLE
[Bug]: Screen shudders when clicked on Filter in Welcome tour

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#18877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user starts the Welcome tour and tries out the tool below before building an app, when clicked on Filter in table widget the screen shakes. This is noticed from the second click onwards.
Also when the user clicks on Filter and goes back to the home page and restarts the Welcome tour, the Filter tab is already present there from the last session.

https://loom.com/share/82fdd8920f7a4f4f8a26358f6eb8e1c1

### Steps To Reproduce

Scenario 1
1. Go to Welcome Tour
2. Click on Filters in table widget > Filter tab opens > Close it and open again

Scenario 2 
1. Go to Welcome Tour
2. Click on Filters in table widget
3. Keeping the filter tab open, go back to home page and click on Welcome tour again > Notice the filter tab is already present in the new session

### Issue video log

https://loom.com/share/82fdd8920f7a4f4f8a26358f6eb8e1c1

### Version

Cloud

**Comment by kocharrahul7** [comment]
Given the low priority, and likelihood of sunsetting the welcome tour, we won't be picking this up
