### ISSUE TITLE
[Bug]: 'Select All' option in Checkbox Group widget takes 2 clicks to checked/unchecked

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#18880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When 'select all' options is enabled for checkbox group widget, we can observe that 2 clicks is required to check/uncheck 'Select All' option

- This is only happing when user clicks on 'select all' label instead of on checkbox

![image](https://user-images.githubusercontent.com/95341241/207000952-77e0a578-3224-4411-966d-170943c9bba0.png)

### Steps To Reproduce

1. Drag & Drop Checkbox Group widget
2. Enable 'Select All Options' property from Property pane
3. Click on select all label on checkbox group widget
4. Observe that 2 clicks is required to check/uncheck options

### Version

Cloud / Production

**Comment by utkarshkumarawasthi98** [comment]
Hello, can you please assign this issue to me

**Comment by ampatzidhs** [comment]
Hello, i am interested to have this issue, would you assign me ?

**Comment by ArjobanSingh** [comment]
Hey @chandannkumar ,
Can you please assign me this, I've found the reason for this specific issue and would resolve this swiftly.
