### ISSUE TITLE
[Bug]: The internal server error is displayed when the user creates a child branch from master

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The internal server error is displayed when the user creates a child branch from master
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/207022483-87d42c53-5d3c-4113-9613-cd5175456522.png">

### Steps To Reproduce

1. Login as admin 
2. got to admin setting
3. create a new role with crud access for app
4. And execute and view access for Queries and datasources
5. Now Assign it to user 1
6. Now login as user 1
7. Connect app to git
8. Create a child branch 1
9. The internal server error will be displayed

### Version

localhost

**Comment by Parthvi12** [comment]
stack trace :

**Comment by Parthvi12** [comment]
backend stdout | [2022-12-23 06:24:48,831] userEmail=test4@appsmith.com, sessionId=5b167682-9430-4077-88b1-db28fa0785a7, thread=nioEventLoopGroup-3-6, requestId=622014df-08bc-42c3-aa76-2acc730ac80e - 

backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to find pageId 63a459fd70eedf53f0f05752, test/parthvi

backend stdout |  at com.appsmith.server.services.ce.NewPageServiceCEImpl.findRootApplicationIdFromNewPage(NewPageServiceCEImpl.java:598)

backend stdout |  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

backend stdout | Error has been observed at the following site(s):

backend stdout |  *__checkpoint ⇢ Handler com.appsmith.server.controllers.PageController#getAllPages(String, String, ApplicationMode, String) [DispatcherHandler]

backend stdout | Original Stack Trace:

backend stdout |  at com.appsmith.server.services.ce.NewPageServiceCEImpl.findRootApplicationIdFromNewPage(NewPageServiceCEImpl.java:598)

backend stdout |  at com.appsmith.server.services.ce.NewPageServiceCEImpl.findApplicationPages(NewPageServiceCEImpl.java:644)

backend stdout |  at com.appsmith.server.controllers.ce.PageControllerCE.getAllPages(PageControllerCE.java:169)

backend stdout |  at jdk.internal.reflect.GeneratedMethodAccessor755.invoke(Unknown Source)

backend stdout |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

backend stdout |  at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by sidhantgoel** [comment]
test

**Comment by RakshaKShetty** [comment]
Closed this issue as this as we dont have exact repro for this and its intermittent
