### ISSUE TITLE
[Bug]: Guided tour test is failing as expected initial information banner is not displayed intermittently

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#18883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When guided tour test is getting executed as soon as the Customer Support Dashboard applications is completed , postgres data connection is complete and proper message is displayed.

### Steps To Reproduce

1.Guided_tour spec is failing in automation intermittently.
2.Post choosing the Welcome Tour button
3.You start building an application
4.Once that is initiated you should be able to onboard with Proper banner messages.

Expected:
This Banner should be displayed to begin with
<img width="725" alt="Screenshot 2022-11-24 at 3 28 40 PM" src="https://user-images.githubusercontent.com/67676905/207013412-620044fe-d938-4d38-a17f-7f44bea75f54.png">

Actual:
In CI runs we have been noticing that initial banner is missed and below banner is shown directly.
<img width="1047" alt="Screenshot 2022-12-12 at 3 10 21 PM" src="https://user-images.githubusercontent.com/67676905/207017556-c29d56c5-3333-4f73-94c6-ae4439a867f6.png">

### Version

Appsmith v1.8.13-SNAPSHOT

**Comment by akash-codemonk** [comment]
@NandanAnantharamu Is this still happening? Doesn't look like it is happening now.

**Comment by NandanAnantharamu** [comment]
> @NandanAnantharamu Is this still happening? Doesn't look like it is happening now.

Will check the list of flaky tests as get back

**Comment by ginilpg** [comment]
@NandanAnantharamu Any updates here? We can close this if it's not happening now.

**Comment by akash-codemonk** [comment]
@NandanAnantharamu Closing this for now. Please reopen if it is happening again.
