### ISSUE TITLE
[Bug]: Object references are showing up as ''not defined"

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#18899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Widget or query reference shows up as ''not defined" lint error even though the entity is present

### Steps To Reproduce

1. Reference a widget/query in any JS-supported field and refresh the page
![image](https://user-images.githubusercontent.com/79509062/207091416-f6e3ce86-6bab-4e48-835c-1c1eb3790aae.png)

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami I'm not able to reproduce this. Could you share a link to your app?

**Comment by ramsaptami** [comment]
This has been showing up intermittently for the past 2 weeks. I've only been able to see this occur twice. We can observe this for now and find a favorable condition - if any.

**Comment by satbir121** [comment]
Waiting for another week to see if the issue still exists.

cc: @ramsaptami @AnandiKulkarni @bharath31

**Comment by bharath31** [comment]
@ramsaptami just wanted to check if you are able to consistently reproduce this now.

**Comment by ramsaptami** [comment]
Nope, let's close this. Can't repro this atm
