### ISSUE TITLE
[Bug] Tabs selected tab is not working

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1889]
### Steps to reproduce the behaviour:
1. Drag a tab widget
2. Drag a text widget
3. Bind the text widget to the selected tab {{Tabs1.selectedTab}}
4. Change the selected tab by clicking on it
5. The value of the text does not change

**Comment by prapullac** [comment]
The text does not change in the Input widget on selecting other tabs. Hence reopening the issue
