### ISSUE TITLE
[Bug]: Not able to navigate to a widget thru omnibar navigation that is in the different tab than what is currently in-view

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#18892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

we are unable to navigate to a child widget inside the tabs provided that tab is not currently in-view,

### Steps To Reproduce

1. Dnd a tab widget
2. Drop a widget in Tab 1
3. Select Tab 2 
4. Thru omnibar navigation, navigate to this child widget
 You can see the widget might be selected (as you would be able to see the properties) but not showing on the viewport since tab is not switched

### Issue video log

https://www.loom.com/share/fc61b6ef82d54c6b93effee4d8250fc7

### Version

Cloud

**Comment by ginilpg** [comment]
@kamakshibhat-appsmith I think this is related to [#17150](https://github.com/appsmithorg/appsmith/issues/17150)

**Comment by Richarex** [comment]
This is fixed, verified it on release.
