### ISSUE TITLE
[Bug]: In the git connected appCheckbox enable and disabling for a page has a issue 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the git connected appCheckbox enable and disabling for a page has a issue 
https://www.loom.com/share/bd1408ee30f74870a7e81235f9f5819e

### Steps To Reproduce

1. Add a app and connect it to git 
2. Add 2 to 3 pages in the app
3. Go to admin setting
4. Now add a custom role
5. Open the entire app and queries 
6. Now check the create role for page 2
7. The queries of the page 1 will get checked

### Version

localhost

**Comment by AnaghHegde** [comment]
@RakshaKShetty How is it related to git?

**Comment by RakshaKShetty** [comment]
@AnaghHegde this issue happening with the Git connected apps
