### ISSUE TITLE
[Bug]: Disabling "Allow Filtering" also disables "add new row"

### ISSUE THREAD

**Issue by bobbintb** [appsmithorg/appsmith#18901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using v1.8.12.
When "Allow Filtering" is disabled in the table properties, the "add new row" option in the table widget also disappears.

### Steps To Reproduce

Create a table widget. In the widget properties, disable "Allow Filtering". The filter icon/button in the table disappears but the "add new row" also disappears. The widget property "Allow adding a row" is still enabled, but is absent from the widget.

### Version

v1.8.12 self-hosted docker

**Comment by dilippitchika** [comment]
@sbalaji1192 @chandannkumar i thought this issue was resolved. Can you both please check and see if this is still happening? If yes, @sbalaji1192 can you estimate this issue and we will decide if we can pick it up this sprint or not

**Comment by sbalaji1192** [comment]
@dilippitchika We closed this issue last week. The fix will get released in the upcoming release this week. https://github.com/appsmithorg/appsmith/issues/18346

**Comment by dilippitchika** [comment]
Ok, @bobbintb this issue has been fixed as part of our recent fixes which will go live this week. Please keep an eye out for v1.8.13
