### ISSUE TITLE
[Bug]: Git commit flow requests double confirmation

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#18900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After committing changes on git, a second `commit and push` request shows up - sometimes with a different change log to what was previously committed and sometime an empty change log as seen in the video attached

### Steps To Reproduce

1. On a large, git connected app, make multiple changes on widget/pages and queries
2. Commit these changes and observe there's a second commit request that is sent as seen in the video attached

### Issue video log

https://www.loom.com/share/a7281b39e9bb450ba0df2820441086e2

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
If this is reproducible on that app, could you share the devtool logs.

**Comment by ramsaptami** [comment]
@IAmAnubhavSaini you can reproduce this quite easily on release now. Connect an app to git and in a few commits you'll start seeing this double confirmation

**Comment by AnaghHegde** [comment]
@ramsaptami Is this still reproducible after the custom js lib changes fix went in?
