### ISSUE TITLE
[Feature]: Expose onRowDeselected event 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#18911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the ability to run actions when a table row is deselected 

### Why should this be worked on?

A user wants to reset other widgets when a table row is deselected- https://discord.com/channels/725602949748752515/1052032905322442793

**Comment by dilippitchika** [comment]
@bharath31 closing as duplicate of #15891, there's a workaround listed in this issue. Can you please inform the user?

**Comment by bharath31** [comment]
@dilippitchika thanks! I'm not sure if the workaround mentioned in #15891 would be helpful. The use case is to simply reset another widget on table row deselection. There aren't any API calls involved here.

**Comment by developer-honoru** [comment]
i need this function
