### ISSUE TITLE
[Bug]: The Rbac event names should not be displayed in the audit log event dropdown 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Rbac event names Should not be displayed in the audit log event dropdown 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/207283723-5ec62d47-1348-4004-a651-e8bd2ba9e4ac.png">

### Steps To Reproduce

1. Login as a test@gmail.com(admin user)
2. go to admin setting page
3. click on audit log
4. Click on event dropdown
5. the rbac events are displayed 

### Version

release->localhost

**Comment by hiteshjoshi** [comment]
This is already taken care.
