### ISSUE TITLE
[Bug]: In Datasource & queries tab the checkboxes should be added on datasource level instead of workspace level 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Datasource & queries tab the checkboxes should be added on datasource level instead of workspace level 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/207519510-38eb3f99-5b8d-472c-834d-ca0066d236c3.png">

### Steps To Reproduce

1. login as admin
2.go to admin setting page
3.create a custom role
4.Go to datasource & queries tab
5.The checkboxes displayed at the workspace level should be shifted to datasource level

### Version

localhost

**Comment by infinitetrooper** [comment]
@RakshaKShetty  - I think this is okay, we could also add the check boxes at datasource level but, we should have them at workspace level as well or there will be no permissions assignment at the parent level.
