### ISSUE TITLE
[Bug]: Omnibar navigation order does not make sense

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#18963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The order in which the entities are shown in the omnibar (cmd/ctrl + P) are not representative of the recent items shows.
They sometimes show wrong links to pages
They also do not account for actions that are recently visited

### Steps To Reproduce

Navigate around the app and check on omni bar navigation list. They will not be accurate.

### Issue video log

https://user-images.githubusercontent.com/12022471/207785236-247d0763-37f0-4c2b-aec4-2208b29e1cd9.mov

### Version

Prod

**Comment by Richarex** [comment]
This is working as expected now the omnibar shows the most recent widgets, js objects, API queries accordingly.
