### ISSUE TITLE
[Bug]: Even without editing the user is displayed with Pop up in Auth API 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#18962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user click on edit of existing Datasource it is observed that the user without making any change the pop up is displayed to the user

### Steps To Reproduce

1) Ensure there is existing datasource
2) Click on Edit option 
3) Ensure not make any change 
Observe that the pop up is displayed to the user

### Issue video log

https://www.loom.com/share/ebe56e716afb4bc18a3e6e8a8c6c200f

### Version

Release

**Comment by rohan-arthur** [comment]
should ideally have been fixed with #18761 ?
