### ISSUE TITLE
[Bug]: Exist app has been deleted after checkout remote branch

### ISSUE THREAD

**Issue by thanhloc1993** [appsmithorg/appsmith#18960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are facing an issue when checkout the remote branch. If the json metadata is not valid. Application has been deleted.

### Steps To Reproduce

1. In master branch
2. Checkout to master1 branch. Make the json invalid. Then push code to master1
3. In appsmith UI, checkout remote branch master1
4. App deleted.

Maybe related that: https://github.com/appsmithorg/appsmith/blob/49f47ebe97abe5b7e723c1b95d954a2ad5ea413c/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java#L1166

### Version

lastest

**Comment by AnaghHegde** [comment]
This is fixed in the PR #18973
