### ISSUE TITLE
[Bug] Text overflows in button widget

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1896]
## Description

When we have a long text in the button widget, the widget itself overflows and looks extremely weird. 

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Drag a button widget
2. Update the text to be very long
3. Observe that the button is 
4. See error in attached screenshot

<img width="418" alt="Screenshot 2020-11-25 at 9 03 15 AM" src="https://user-images.githubusercontent.com/458946/100179947-1773ca00-2efd-11eb-8027-0ded7d53ae40.png">

### Important Details
 - Version: Cloud
 - OS: MacOSX
 - Browser: Firefox

**Comment by jsartisan** [comment]
@mohanarpit Adding ellipsis for text for overflowing text. 

It will look like

<img width="231" alt="Screenshot 2020-12-04 at 4 26 45 PM" src="https://user-images.githubusercontent.com/6636360/101155714-88c62200-364d-11eb-98f7-2797e4b3d591.png">
