### ISSUE TITLE
[Feature] Allow widget data to be updated using `setProperty`

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1897]
## Summary
Just as we can `storeValue` globally. 
Some scenarios can require widget properties to be updated, which cannot be handled using the bindings.
For example, `{{Api1.run(() => { Input1.setProperty("defaultText", "abc")}, () => {})}}`

Exact scenario where the bindings (pull/subscribe) mechanism fail: to be updated.

**Comment by Nikhil-Nandagopal** [comment]
Since this goes against the reactive paradigm, I'm closing this till we have more clarity on what exactly we're trying to achieve here. 
Updating a widget's property should always occur via updating the underlying data

**Comment by Nikhil-Nandagopal** [comment]
Reopening this so that the user can comment here.

**Comment by ofpiyush** [comment]
A user asked for a way to switch tab on tab widget on click of a button.

**Comment by areyabhishek** [comment]
What would be a good solution to their request? Can they use 'Navigate to 'tab''?

**Comment by ofpiyush** [comment]
I've created a longer request for the feature #2270

**Comment by hetunandu** [comment]
Closing this in the favour of #3532
