### ISSUE TITLE
[Bug]-[520]:Gsheet even when form is dirty, discard popup isnt shown

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#18982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we create gsheet datasource, save and authorize it, Now after editing this same datasource and changing the scope should ideally make the datasource form dirty and on click of back button it should show discard popup, but it is not showing discard popup. This happens only when we open gsheet datasource for editing from entity explorer.

### Steps To Reproduce

1. Create google sheet datasource and save it
2. Go back to canvas page
3. Now open this google sheet datasource to edit from entity explorer
4. Change the scope
5. Click on back button
6. We should see discard popup as form has been changed

### Version

Cloud/ Self-Hosted - 1.8.12

**Comment by sneha122** [comment]
6m usage of google sheet: 2600
Assuming 10% of users face this: 260

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 260 |
| Effort (months)  | 0.25 |

**Comment by rohan-arthur** [comment]
back button has been removed on datasource edit. When I click `Cancel` instead, I do see the save popup.
