### ISSUE TITLE
[Bug]: We show data from previous action momentarily when the action params change

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#18983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We momentarily show data from a previous query while the query with new params runs. I strongly disagree with this, I don’t see what that accomplishes or how it helps.

### Steps To Reproduce

Click on the table row while watching post id in comments table

### Public Sample App

https://app.appsmith.com/app/previous-response-issue/page1-633415a193ac462241a3af1e

### Version

Both

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6bp58)

**Comment by somangshu** [comment]
Somewhat related is it #9572?
Or this is related to #12308. Checkout the threads!
I am going to close this issue for now, @SatishGandham please open this again in case you think the issue is different
