### ISSUE TITLE
[Feature]: Enable analytics events for authorisation of google sheet datasource

### ISSUE THREAD

**Issue by vaibh1297** [appsmithorg/appsmith#18980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Enable analytics events for authorisation of google sheet datasource.

### Why should this be worked on?

This will help us to know the percentage of cases where google sheet authorisation has succeeded and improving upon that number.

https://www.notion.so/appsmith/Improve-GSheets-Conversions-e387633d9dbb4e37bd7c203bd9044b9f

**Comment by prapullac** [comment]
The "Success" and "InProgress" status is being tracked and verified on segment. Failure status is not being tracked however it would be done on another PR as per conversation  with @vaibh1297

**Comment by vaibh1297** [comment]
Failure event needs to be added on client side @sneha122

**Comment by prapullac** [comment]
Completed Testing the Failure status and observed that it is being tracked.
