### ISSUE TITLE
[Bug] Disable launching applications from home screen when they haven't been deployed

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#1899]
## Description
Draft versions of applications show the option to be launched, which only ends up throwing an error and leads to a page that says "Appsmith server is taking too long to respond". Users should not be allowed to launch such applications

### Steps to reproduce the behaviour:
1. Go to the home screen
2. Create a new application
3. Navigate back to home screen without deploying the new application
4. Hover over application to see the launch option, click through to see error.

### Important Details
 - Version: [Cloud]
 - OS: [MacOSX]
 - Browser [chrome]

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair this seems like an error, draft versions of applications have a special undeployed state that should show up

**Comment by trishaanand** [comment]
I think this should be a backend bug where the application is not being initialised with a published state with default page.
