### ISSUE TITLE
[Bug]-[800]:Inside Import modal save button doesn't get  enabled even after adding URI for mongo database

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Inside Import modal save button doesn't get  enabled even after adding URI for mongo database 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/208051154-80373b69-5534-4df0-ba5e-a9a96553041f.png">

### Steps To Reproduce

1. Login to the app
2. click on meat ball icon next to workspace name
3. click on import menu
4. Now import a app which has mongo datasource
5. No add the mongo URI
6. The save button doesnt get enabled 

### Version

release

**Comment by sneha122** [comment]
6m Usage of mongodb datasource: 2000
Assuming 20% of users face this: 400

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | 0.25 |
