### ISSUE TITLE
[Docs] Need documentation to run appsmith on a different port

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1900]
## Describe the problem

A lot of users try to run appsmith on an existing instance where the ports 80 & 443 are already taken. They frequently request a way to run appsmith on a separate port of their choice.
We can help these users by documenting this process

**Comment by mohanarpit** [comment]
This is already available at: https://github.com/appsmithorg/appsmith/discussions/1903. Are you suggesting that we add this to docs.appsmith.com as well?

**Comment by Nikhil-Nandagopal** [comment]
Yes. I think this is becoming commonplace and can be added to the docs
