### ISSUE TITLE
[Bug]: The addition and deletion of the groups event to users is captured as "group.remove_users" and "group.invite_users"

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The addition and deletion of the groups event to users is captured as "group.remove_users" and "group.invite_users" but here we are adding and deleting the groups not users
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/208232841-06e8d286-2b52-4632-9f13-939d2aa3d63e.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/208232845-d11e5f1d-c1da-4f0a-8e40-cae848d95e0d.png">

### Steps To Reproduce

1.Login as admin
2.go to admin setting page
3. go to users tab
4. click on user name
5. first assign some groups to user
6. Now check the log the event is captured as "group.invite_users" 
7. now remove the group from user 
8. the log is captured as "group.remove_users"
9. but here we are removing groups and adding new groups not the users

### Version

localhost

**Comment by trishaanand** [comment]
This is expected behaviour.

**Comment by RakshaKShetty** [comment]
Closing the issue as this is a expected behaviour
