### ISSUE TITLE
[Task]: Add missing titles to the Appsmith errors

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#19019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

A few Appsmith errors exist that don't have any value in the title field. The goal of this task is to add those missing titles.

**Comment by subrata71** [comment]
These are the **96** errors that I have found so far having no titles.

| Error Name  | Http Error Code |Appsmith Error Code|
| ------------- | ------------- | ------------- |
|INVALID_PARAMETER|	400|	4000|
|PLUGIN_NOT_INSTALLED|	400|	4001|
|PLUGIN_ID_NOT_GIVEN|	400|	4002|
|DATASOURCE_NOT_GIVEN|	400|	4003|
|PAGE_ID_NOT_GIVEN|	400|	4004|
|DUPLICATE_KEY_USER_ERROR|	400|	4005|
|PAGE_DOESNT_BELONG_TO_USER_WORKSPACE|	400|	4006|
|UNSUPPORTED_OPERATION|	400|	4007|
|DEPRECATED_API|	400|	4008|
|USER_DOESNT_BELONG_ANY_WORKSPACE|	400|	4009|
|USER_DOESNT_BELONG_TO_WORKSPACE|	400|	4010|
|NO_CONFIGURATION_FOUND_IN_DATASOURCE|	400|	4011|
|INVALID_ACTION_COLLECTION|	400|	4038|
|INVALID_ACTION|	400|	4012|
|INVALID_DATASOURCE|	400|	4013|
|INVALID_DATASOURCE_CONFIGURATION|	400|	4015|
|INVALID_ACTION_NAME|	400|	4014|
|NO_CONFIGURATION_FOUND_IN_ACTION|	400|	4016|
|NAME_CLASH_NOT_ALLOWED_IN_REFACTOR|	400|	4017|
|PAGE_DOESNT_BELONG_TO_APPLICATION|	400|	4018|
|INVALID_DYNAMIC_BINDING_REFERENCE|	400|	4022|
|USER_ALREADY_EXISTS_IN_WORKSPACE|	400|	4021|
|UNAUTHORIZED_DOMAIN|	401|	4019|
|USER_NOT_SIGNED_IN|	401|	4020|
|INVALID_PASSWORD_RESET|	400|	4020|
|INVALID_PASSWORD_LENGTH|	400|	4037|
|JSON_PROCESSING_ERROR|	400|	4022|
|INVALID_CREDENTIALS|	200|	4023|
|UNAUTHORIZED_ACCESS|	403|	4025|
|DUPLICATE_KEY|	409|	4024|
|USER_ALREADY_EXISTS_SIGNUP|	409|	4025|
|ACTION_IS_NOT_AUTHORIZED|	403|	4026|
|NO_RESOURCE_FOUND|	404|	4027|
|USER_NOT_FOUND|	404|	4027|
|ACL_NO_RESOURCE_FOUND|	404|	4028|
|GENERIC_BAD_REQUEST|	400|	4028|
|VALIDATION_FAILURE|	400|	4028|
|INVALID_CURL_COMMAND|	400|	4029|
|INVALID_LOGIN_METHOD|	401|	4030|
|INVALID_GIT_CONFIGURATION|	400|	4031|
|INVALID_GIT_SSH_CONFIGURATION|	400|	4032|
|INVALID_GIT_REPO|	400|	4033|
|DEFAULT_RESOURCES_UNAVAILABLE|	400|	4034|
|GIT_MERGE_FAILED_REMOTE_CHANGES|	406|	4036|
|GIT_MERGE_FAILED_LOCAL_CHANGES|	406|	4037|
|REMOVE_LAST_WORKSPACE_ADMIN_ERROR|	400|	4038|
|INVALID_CRUD_PAGE_REQUEST|	400|	4039|
|UNSUPPORTED_OPERATION_FOR_REMOTE_BRANCH|	400|	4040|
|ROLES_FROM_SAME_WORKSPACE|	400|	4041|
|INTERNAL_SERVER_ERROR|	500|	5000|
|REPOSITORY_SAVE_FAILED|	500|	5001|
|PLUGIN_INSTALLATION_FAILED_DOWNLOAD_ERROR|	500|	5002|
|PLUGIN_RUN_FAILED|	500|	5003|
|PLUGIN_EXECUTION_TIMEOUT|	504|	5040|
|PLUGIN_LOAD_FORM_JSON_FAIL|	500|	5004|
|PLUGIN_LOAD_TEMPLATES_FAIL|	500|	5005|
|IO_ERROR|	503|	5003|
|MARKETPLACE_TIMEOUT|	504|	5041|
|DATASOURCE_HAS_ACTIONS|	409|	4030|
|WORKSPACE_ID_NOT_GIVEN|	400|	4031|
|INVALID_CURL_METHOD|	400|	4032|
|OAUTH_NOT_AVAILABLE|	500|	5006|
|MARKETPLACE_NOT_CONFIGURED|	500|	5007|
|PAYLOAD_TOO_LARGE|	413|	4028|
|SIGNUP_DISABLED|	403|	4033|
|FAIL_UPDATE_USER_IN_SESSION|	500|	5008|
|APPLICATION_FORKING_NOT_ALLOWED|	403|	4034|
|GOOGLE_RECAPTCHA_TIMEOUT|	504|	5042|
|GOOGLE_RECAPTCHA_FAILED|	401|	4035|
|UNKNOWN_ACTION_RESULT_DATA_TYPE|	500|	5009|
|INVALID_CURL_HEADER|	400|	4036|
|AUTHENTICATION_FAILURE|	500|	5010|
|INSTANCE_REGISTRATION_FAILURE|	500|	5011|
|TOO_MANY_REQUESTS|	429|	4039|
|INVALID_JS_ACTION|	400|	4040|
|CYCLICAL_DEPENDENCY_ERROR|	400|	4041|
|CLOUD_SERVICES_ERROR|	500|	5012|
|GIT_APPLICATION_LIMIT_ERROR|	402|	4043|
|GIT_ACTION_FAILED|	400|	4044|
|GIT_FILE_SYSTEM_ERROR|	503|	5013|
|GIT_EXECUTION_TIMEOUT|	504|	5014|
|INCOMPATIBLE_IMPORTED_JSON|	400|	4045|
|GIT_MERGE_CONFLICTS|	400|	4046|
|GIT_PULL_CONFLICTS|	400|	4047|
|SSH_KEY_GENERATION_ERROR|	500|	5015|
|GIT_GENERIC_ERROR|	504|	5016|
|GIT_UPSTREAM_CHANGES|	400|	4048|
|GENERIC_JSON_IMPORT_ERROR|	400|	4049|
|FILE_PART_DATA_BUFFER_ERROR|	500|	5017|
|MIGRATION_ERROR|	500|	5018|
|INVALID_GIT_SSH_URL|	400|	4050|
|REPOSITORY_NOT_FOUND|	404|	4051|
|UNKNOWN_PLUGIN_REFERENCE|	400|	4052|
|ENV_FILE_NOT_FOUND|	500|	5019|
|PUBLIC_APP_NO_PERMISSION_GROUP|	500|	5020|
|RTS_SERVER_ERROR|	500|	5021|

**Comment by subrata71** [comment]
These are the proposed titles. @sbalaji1192 Can you please verify from your end?

| Error Name  | Http Error Code |Appsmith Error Code|Title|
| ------------- | ------------- | ------------- | ------------- |
|INVALID_PARAMETER|  400| 4000|    Invalid parameter|
|PLUGIN_NOT_INSTALLED|   400| 4001|    Plugin not installed|
|PLUGIN_ID_NOT_GIVEN|    400| 4002|    Missing plugin id|
|DATASOURCE_NOT_GIVEN|   400| 4003|    Missing datasource|
|PAGE_ID_NOT_GIVEN|  400| 4004|    Missing page id|
|DUPLICATE_KEY_USER_ERROR|   400| 4005|    Name already used|
|PAGE_DOESNT_BELONG_TO_USER_WORKSPACE|   400| 4006|    Page doesn''t belong to this workspace|
|UNSUPPORTED_OPERATION|  400| 4007|    Unsupported operation|
|DEPRECATED_API| 400| 4008|    Deprecated API|
|USER_DOESNT_BELONG_ANY_WORKSPACE|   400| 4009|    User doesn''t belong to any workspace|
|USER_DOESNT_BELONG_TO_WORKSPACE|    400| 4010|    User doesn''t belong to this workspace|
|NO_CONFIGURATION_FOUND_IN_DATASOURCE|   400| 4011|    Datasource configuration is invalid|
|INVALID_ACTION_COLLECTION|  400| 4038|    Collection configuration is invalid|
|INVALID_ACTION| 400| 4012|    Action configuration is invalid|
|INVALID_DATASOURCE| 400| 4013|    Datasource configuration is invalid|
|INVALID_DATASOURCE_CONFIGURATION|   400| 4015|    Datasource configuration is invalid|
|INVALID_ACTION_NAME|    400| 4014|    Invalid action name|
|NO_CONFIGURATION_FOUND_IN_ACTION|   400| 4016|    No configurations found in this action|
|NAME_CLASH_NOT_ALLOWED_IN_REFACTOR| 400| 4017|    Name already taken|
|PAGE_DOESNT_BELONG_TO_APPLICATION|  400| 4018|    Page doesn''t belong to this application|
|INVALID_DYNAMIC_BINDING_REFERENCE|  400| 4022|    Invalid dynamic binding reference|
|USER_ALREADY_EXISTS_IN_WORKSPACE|   400| 4021|    User already exists in this workspace|
|UNAUTHORIZED_DOMAIN|    401| 4019|    Invalid or unauthorized email domain|
|USER_NOT_SIGNED_IN| 401| 4020|    User not signed in|
|INVALID_PASSWORD_RESET| 400| 4020|    Invalid password reset request|
|INVALID_PASSWORD_LENGTH|    400| 4037|    Invalid password length|
|JSON_PROCESSING_ERROR|  400| 4022|    Json processing error|
|INVALID_CREDENTIALS|    200| 4023|    Invalid credentials|
|UNAUTHORIZED_ACCESS|    403| 4025|    Unauthorized access|
|DUPLICATE_KEY|  409| 4024|    Duplicate key|
|USER_ALREADY_EXISTS_SIGNUP| 409| 4025|    Account already exists with this email|
|ACTION_IS_NOT_AUTHORIZED|   403| 4026|    Permission denied|
|NO_RESOURCE_FOUND|  404| 4027|    No resource found|
|USER_NOT_FOUND| 404| 4027|    No user found|
|ACL_NO_RESOURCE_FOUND|  404| 4028|    No resource found or permission denied|
|GENERIC_BAD_REQUEST|    400| 4028|    Invalid request|
|VALIDATION_FAILURE| 400| 4028|    Validation failed|
|INVALID_CURL_COMMAND|   400| 4029|    Invalid cURL command|
|INVALID_LOGIN_METHOD|   401| 4030|    Invalid login method|
|INVALID_GIT_CONFIGURATION|  400| 4031|    Invalid Git configuration|
|INVALID_GIT_SSH_CONFIGURATION|  400| 4032|    SSH key not configured|
|INVALID_GIT_REPO|   400| 4033|    Invalid Git repository|
|DEFAULT_RESOURCES_UNAVAILABLE|  400| 4034|    Default resources not found|
|GIT_MERGE_FAILED_REMOTE_CHANGES|    406| 4036|    Git merge failed for remote changes|
|GIT_MERGE_FAILED_LOCAL_CHANGES| 406| 4037|    Git merge failed for local changes|
|REMOVE_LAST_WORKSPACE_ADMIN_ERROR|  400| 4038|    Last admin cannot be removed|
|INVALID_CRUD_PAGE_REQUEST|  400| 4039|    Invalid page generation request|
|UNSUPPORTED_OPERATION_FOR_REMOTE_BRANCH|    400| 4040|    Unsupported Operation|
|ROLES_FROM_SAME_WORKSPACE|  400| 4041|    Roles already exist|
|INTERNAL_SERVER_ERROR|  500| 5000|    Internal server error|
|REPOSITORY_SAVE_FAILED| 500| 5001|    Failed to save|
|PLUGIN_INSTALLATION_FAILED_DOWNLOAD_ERROR|  500| 5002|    Plugin installation failed|
|PLUGIN_RUN_FAILED|  500| 5003|    Plugin execution failed|
|PLUGIN_EXECUTION_TIMEOUT|   504| 5040|    Timeout in plugin execution|
|PLUGIN_LOAD_FORM_JSON_FAIL| 500| 5004|    Unable to load datasource form configuration|
|PLUGIN_LOAD_TEMPLATES_FAIL| 500| 5005|    Unable to load datasource templates|
|IO_ERROR|   503| 5003|    I/O error|
|MARKETPLACE_TIMEOUT|    504| 5041|    Timeout in marketplace|
|DATASOURCE_HAS_ACTIONS| 409| 4030|    Datasource cannot be deleted|
|WORKSPACE_ID_NOT_GIVEN| 400| 4031|    Missing workspace id|
|INVALID_CURL_METHOD|    400| 4032|    Invalid method in cURL command|
|OAUTH_NOT_AVAILABLE|    500| 5006|    Unsupported login method|
|MARKETPLACE_NOT_CONFIGURED| 500| 5007|    Marketplace not configured|
|PAYLOAD_TOO_LARGE|  413| 4028|    Payload exceeds max allowed size|
|SIGNUP_DISABLED|    403| 4033|    Signup disabled|
|FAIL_UPDATE_USER_IN_SESSION|    500| 5008|    Unable to update user in session|
|APPLICATION_FORKING_NOT_ALLOWED|    403| 4034|    Forking application not permitted|
|GOOGLE_RECAPTCHA_TIMEOUT|   504| 5042|    Timeout in Google recaptcha verification|
|GOOGLE_RECAPTCHA_FAILED|    401| 4035|    Google recaptcha verification failed|
|UNKNOWN_ACTION_RESULT_DATA_TYPE|    500| 5009|    Unexpected data type|
|INVALID_CURL_HEADER|    400| 4036|    Invalid header in cURL command|
|AUTHENTICATION_FAILURE| 500| 5010|    Authentication failed|
|INSTANCE_REGISTRATION_FAILURE|  500| 5011|    Registration failed for this instance|
|TOO_MANY_REQUESTS|  429| 4039|    Too many requests|
|INVALID_JS_ACTION|  400| 4040|    Invalid action in JS object|
|CYCLICAL_DEPENDENCY_ERROR|  400| 4041|    Cyclical Dependency in Page Load Actions|
|CLOUD_SERVICES_ERROR|   500| 5012|    Error in cloud services|
|GIT_APPLICATION_LIMIT_ERROR|    402| 4043|    Maximum number of Git repo connection limit reached|
|GIT_ACTION_FAILED|  400| 4044|    Git failed|
|GIT_FILE_SYSTEM_ERROR|  503| 5013|    Git file system error|
|GIT_EXECUTION_TIMEOUT|  504| 5014|    Timeout in Git command execution|
|INCOMPATIBLE_IMPORTED_JSON| 400| 4045|    Incompatible Json file|
|GIT_MERGE_CONFLICTS|    400| 4046|    Merge conflicts found|
|GIT_PULL_CONFLICTS| 400| 4047|    Merge conflicts found during the pull operation|
|SSH_KEY_GENERATION_ERROR|   500| 5015|    Failed to generate SSH keys|
|GIT_GENERIC_ERROR|  504| 5016|    Git command execution error|
|GIT_UPSTREAM_CHANGES|   400| 4048|    Git push failed for pending upstream changes|
|GENERIC_JSON_IMPORT_ERROR|  400| 4049|    Unable to import application in workspace|
|FILE_PART_DATA_BUFFER_ERROR|    500| 5017|    Failed to upload file|
|MIGRATION_ERROR|    500| 5018|    Action already migrated|
|INVALID_GIT_SSH_URL|    400| 4050|    Invalid SSH URL|
|REPOSITORY_NOT_FOUND|   404| 4051|    Repository not found|
|UNKNOWN_PLUGIN_REFERENCE|   400| 4052|    Unknown plugin|
|ENV_FILE_NOT_FOUND| 500| 5019|    Environment file not found|
|PUBLIC_APP_NO_PERMISSION_GROUP| 500| 5020|    Required permission missing for public access|
|RTS_SERVER_ERROR|   500| 5021|    RTS server error|

**Comment by sbalaji1192** [comment]
@sribalajig Please have a look at the above comment. CC @subrata71

**Comment by subrata71** [comment]
> @sribalajig Please have a look at the above comment. CC @subrata71

Sorry, My bad! :p Your usernames are almost analogous.
