### ISSUE TITLE
[Feature]: client only mode

### ISSUE THREAD

**Issue by oscni** [appsmithorg/appsmith#19010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Maybe this is more of a request of a new product rather than a feature request but lets go ;)
If not using any databases and instead only API calls it would be nice to design everything in appsmith and basically just push static files to a webserver/CDN. All the javascript and API calls would then be done/run directly from the browser.

### Why should this be worked on?

To remove the need for a code execution server where the future is APIs only. And also have support for real-time transfers via such protocols that uses longpolling, websockets etc...

**Comment by Nikhil-Nandagopal** [comment]
@oscni thanks for the request but you are right, this does seem like a different product as most API requests on Appsmith are authenticated and thus require a backend. You can still do API calls directly from the browser using our new `fetch` implementation
