### ISSUE TITLE
[Bug]: The role updated event is captured along with group deletion event when the user delete the group

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The role updated event is captured along with group deletion event when the user delete the group
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/208233831-d2bf79ce-2bfc-4be6-b54c-142e62e69d44.png">

### Steps To Reproduce

1.Login as admin
2.go to admin setting page
3. go to groups tab
4. now delete the group
5. now go to audit log page
6.The log for role updated for all the roles associated with the group is displayed 
7.now the group deleted log is captured

### Version

localhost

**Comment by nsarupr** [comment]
If the Role was associated to Deleted User Group, it would have been updated.
This is happening, because there is an analytics event call at the base service level.
@trishaanand can you suggest what should be done over here?

**Comment by RakshaKShetty** [comment]
This is expected behaviour
