### ISSUE TITLE
[Bug] An error message is displayed on making other tab except the 1st Tab as default 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1901]
Steps to reproduce:
1) Add a Tab widget 
2) Add multiple tab 
3)Change the name of the tab 
4) Navigate to default tab field 
5) Add any tab other than Tab1 as default 
and observe

Observation:
On adding any other tab as default it is observed that  an error message is displayed to user and field is highlighted to RED 

Expectation:
1) Error message nor the highlighting must be shown to user 
2) Any tab can be added to default tab 

![Screenshot 2020-11-25 at 12 18 44 PM](https://user-images.githubusercontent.com/71753653/100194480-c7583000-2f1b-11eb-9e05-23d1a3e2ce67.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac this seems to be working now. Can you check?

**Comment by prapullac** [comment]
This is working as expected hence we can close the issue.
