### ISSUE TITLE
[Bug]: Not able to fork and duplicate the application in workspace, when user has create permission for an application

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#19030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to fork first application created in new workspace: workspace1, to workspace2 which has create permission for app as well as datasource it fails with following error: 
Along with fork , duplicate also fails with same error for the first application created in workspace.
<img width="1440" alt="Screenshot 2022-12-19 at 9 53 29 AM" src="https://user-images.githubusercontent.com/80334441/208360131-16b30516-cfa3-47a1-99f4-8f4429540c42.png">

### Steps To Reproduce

1. Login as admin, create new workspace: workspace1 and a new app in it.
2. Create a new role, with edit permission for workspace1 in application resource tab and create permission for workspace1 at application resource tab as well as create permission for datasource.
3. Assign the role to user1
4. Login as user1 and try forking application from workspace1 to workspace2
5. Observe error is thrown.
6. Try Duplicating an app, that throws the same error.

### Version

http://65.0.99.89/

**Comment by ankitakinger** [comment]
This is completed and verified by QA.
