### ISSUE TITLE
[Feature]: Missing optional SSL Settings in MS SQL Datasource Settings

### ISSUE THREAD

**Issue by tw02d008** [appsmithorg/appsmith#19039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

According to the documentation 
https://docs.appsmith.com/reference/datasources/querying-mssql
there should be optional SSL Settings but the settings are missing.

Why do I miss the SSL settings? Because I am getting the error
Failed to initialize pool: Login failed for user 'XXXXX'. ClientConnectionId:afe37d2b-ea9e-4056-ae4e-253704a074d4
Other applications like grafana or budibase are able to connect to the same MS SQL Server with the same credentials from the same IP so therefore I guess it has something to do with SSL settings but I am not able to change thees due to the missing options. 

### Steps To Reproduce

1. Create new Datasource
2. Choose Microsoft SQL Server
3. Only setting groups, Connection and Authentication is visible, SSL is missing

### Version

Self Hosted / Appsmith Community v1.8.11

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6z9os)

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur @sumitsum could you check why this option is missing?

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal this is bug on the documentation side at the moment. We had never implemented SSL for MSSQL, but in the earlier version of Appsmith an SSL dropdown showed up on the datasource page - this bug has been rectified on the code front but the documentation still has it. We need to remove it from documentation as well. cc: @jnikhila
