### ISSUE TITLE
[Bug]: The Run button in js objects will be in disabled state even when the user open the app for the first in edit mode

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Run button In JS object page will be in disabled state when the user open the app for the first in edit mode
![image](https://user-images.githubusercontent.com/45958978/208424474-e3e90402-ac7d-43d4-a330-43116e799a62.png)
![image](https://user-images.githubusercontent.com/45958978/208424483-42b35d73-72b1-4ae1-97f4-ee7f1d5287e8.png)

### Steps To Reproduce

1. Login as admin
2. go to admin setting 
3. In app1 give edit and view access for all page
4. Select execute access for queries and db
5. Now assign this role to the user1 user
6. login as user 1
7. Go to edit mode
8. click on the Js object
9. The run button will be in disabled state

### Version

localhost

**Comment by trishaanand** [comment]
Closed and verified by QA
