### ISSUE TITLE
[Bug]: [CustomJSLib] Fix git sync related bugs on the server side 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#19038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

At the moment the following seems to work / fail:
- works:
Export, Import, Fork, Clone, Git Import on same instance, Git pull, Git merge
- fails:
  - Export also exports js lib meta data for published state separately causing duplication (but does not seem to cause issue with import)
  - Git Export does not export js lib meta data
  - Git Import fails to install js lib (although overall import succeeds) when importing across instance (because export fails to export meta data)
  - Git diff does not show status explicitly

### Steps To Reproduce

.

### Version

self hosted

**Comment by parth-appsmith** [comment]
Need more context on the issue.
