### ISSUE TITLE
Improvement in git connect modal message

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#19045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The git connect modal shows the following message when a user has 3 repos connected already
![image](https://user-images.githubusercontent.com/55969597/208487209-90ba87d7-ad3d-4c46-a09e-a101a6c296a4.png)

The message conveys that a user can only connect 3 repos for free. 
It should instead convey that a user can connect unlimited public repos and only 3 private repos for free. 

### Steps To Reproduce

1. Create a new app
2. Connect the app to git and the git connect modal should show the message

### Version

Cloud - 1.8.13

**Comment by infinitetrooper** [comment]
No longer valid, moved to Git Connect v2 in Q3 2023
