### ISSUE TITLE
[Bug]: The User doesn't able to deploy-the app even when he has all the Permissions

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The User doesn't able to deploy-the app even when he has all the Permissions
![image](https://user-images.githubusercontent.com/45958978/208587889-6c2b8fe2-c414-4ff8-933f-f6f8646bbc7f.png)

### Steps To Reproduce

1. Login as admin
2. create a new workspace
3. import a template
4. go to roles tab
5. Give all the access for the app
6. Assign it to user 1
7. login as user 1
8. go to edit mode 
9. Now try to deploy the app

### Version

localhost

**Comment by trishaanand** [comment]
Closed and verified by QA
