### ISSUE TITLE
[Feature] Currency datatype in the Input Widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1904]
## Summary
Quick and easy Currency input type would be helpful 
- Currency specific formatting 
- Setting different currency locale
- Validations based on currency

## Additional Context
<img width="470" alt="Screenshot 2020-11-25 at 1 24 23 PM" src="https://user-images.githubusercontent.com/12022471/100198217-8f53eb80-2f21-11eb-8aeb-06ee6f63e74b.png">

## Developer Handoff Link
https://www.figma.com/file/PopQorpIl38IqHNdODE0lR/Input-Widget-Types-Update-Number-and-Currency?node-id=2%3A1

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you shed more light on current based validations?

**Comment by somangshu** [comment]
Note: 
- Allows abbreviations eg. 1k = 1,000 2.5m = 2,500,000
- Prefix/Locale option eg. £ or $
- Can use arrow down/up to step
- Can allow/disallow decimals upto 2 places

[ex here](https://cchanxzy.github.io/react-currency-input-field/)
