### ISSUE TITLE
[Bug]: The query execution fails in the edit mode when there is no view permission for the queries

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The query execution fails in the edit mode when there is no view permission for the queries
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/208606443-0373431d-481d-4c30-94b3-dddbeff40813.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/208606480-7b6c4937-7f6f-45ca-937e-5153e003abf8.png">

### Steps To Reproduce

1. login as admin
2. in admin setting page
3. create a custom role
4. Add edit access on page but not on queries
5. Add view access on page not on queries 
6. Also give execute permission for all queries
7. Now  in the view mode the the page looks fine 
8. But when user open the app in edit mode the queries execution failed

### Version

localhost

**Comment by trishaanand** [comment]
@infinitetrooper @ankitakinger : Are we actively working on this? Thanks!

**Comment by ankitakinger** [comment]
@trishaanand actually nope. Was working on SSO for embedded apps and RBAC v1.1 app level invites. Should I pick this up on priority and work on app level invites after this?
