### ISSUE TITLE
[Bug]: "No permission" Toast is displayed randomly  Even when the user have Permission for edit and view the apps 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

"No permission" Toast is displayed randomly  Even when the user have Permission for edit and view the apps 
![image](https://user-images.githubusercontent.com/45958978/208588306-6a8d7ae0-38e9-4b68-b065-5d07e2321d3a.png)
![image](https://user-images.githubusercontent.com/45958978/208588320-43feb1a6-e2d9-41da-bf84-6f90a85900e5.png)

### Steps To Reproduce

1. login as admin
2. go to admin setting
3. in custom role just give view access
4. assign it to user 1
5. login as user 1
6. click on launch button
7. in view mode the pop up is displayed

### Version

localhost

**Comment by ankitakinger** [comment]
This is fixed and verified by QA
