### ISSUE TITLE
[Bug]: When a user who is invited to the workspace via a group, tries to leave the workspace, we see Internal server error toast message

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#19058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user who is invited to the workspace via a group, tries to leave the workspace, we see Internal server error toast message. We need to update the error message in this case that will notify the user he/she wouldn't be able to leave the workspace since he/she hasn't been added to the workspace directly but gets access to it via the group.

Also, update the cypress tests for the same.

<img width="1368" alt="Screenshot 2022-12-20 at 1 26 31 PM" src="https://user-images.githubusercontent.com/28362912/208613629-5620f231-4b2e-4c81-9b59-fda595e997c2.png">

Tests failing links: 
https://cloud.cypress.io/projects/n14p1y/runs/4454/test-results/5dfb44a6-9e5b-4476-ba23-d544625b5e21/video
https://github.com/appsmithorg/appsmith-ee/actions/runs/3738015503/jobs/6344075950

### Steps To Reproduce

1. Go to Group edit page on Admin settings page
2. Add user1 to that group
3. Assign Developer role for workspace1 to this Group
4. Now logout and login as user1
5. You will start seeing workspace1 on the homepage for user1
6. Click the context menu for this workspace1 and click Leave workspace option
7. Notice that we see a toast message saying "Internal server error"

### Version

GAC DP

**Comment by RakshaKShetty** [comment]
Todays date the leave workspace action can be performed only if the user has a appsmith default roles
