### ISSUE TITLE
[Bug]: Trying to switch the tabs without saving the permission details leads to the Multiple tab selection 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to switch the tabs without saving the permission details leads to the Multiple tab selection 
![image](https://user-images.githubusercontent.com/45958978/208827237-031ad221-99d2-4408-97ba-fb9bdb1b4260.png)

### Steps To Reproduce

1. Login as admin
2. Go to admin setting page
3. Create a custom role Select some permissions dont save it
4. Try to switch to the other tab 
5. Both Application resource Tab and other tab are selected 

### Version

localhost

**Comment by ankitakinger** [comment]
Re-opening to update DS version in `appsmith` repo which fixes this issue.
