### ISSUE TITLE
[Task]: Adopt Design components to use rebranding colors

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#19093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Components should change

- Checkbox
- Date Range Picker
- Dropdown - multiselect
- Tabs
- Rectangular switch
- Showcase carousal
- Statusbar
- Toggle
- Toast undo redo

**Comment by shadabbuchh** [comment]
This has been verified in release.
