### ISSUE TITLE
[Bug]: Git Connect | Flickers as we try to edit Git Remote URL when there is a configuration error already present

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#19092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/208852649-4555e471-be65-4813-930b-3ccd307841c7.mov

### Steps To Reproduce

1. Open an app & connect to Git
2. In the Git connection dialog - Give a remote url & Generate Key & observe there is an error
3. Now try to edit the Git Repo remote url & observe the flickering
4. Anything that user types is typed into the field but there is a to & fro in the screen which hinders with users view
5. **Expected: There should be no flickering when user tries to edit any editable fields in Git Connection modal**

### Version

Prod/v1.8.14

**Comment by AnaghHegde** [comment]
@ginilpg We need someone from FE to investigate this further.

**Comment by brayn003** [comment]
@ginilpg This issue is resolved with the ADS release. It is not occuring for the new modal
[My Second Application _ Editor _ Appsmith.webm](https://github.com/appsmithorg/appsmith/assets/8724051/97a2cf86-d944-4603-a2f6-b50c3bbe1c40)
