### ISSUE TITLE
[Bug]: Unable to commit new changes in a git connect app

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After making some changes to a git connected app, when I enter a commit message & click on `Commit`, I get the below error.
<img width="1440" alt="Screenshot 2022-12-21 at 4 26 32 PM" src="https://user-images.githubusercontent.com/39921438/208890506-2c99b29f-24ac-4e4d-ab14-d161bfe3c821.png">

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/app/release-dec-21/page1-63a2b8b9f3e63422b522be25/edit?branch=shadab
2. make some changes in a branch.
3. Commit those changes

### Version

Cloud

**Comment by AnaghHegde** [comment]
This is know issue and we have open ticket for this.
