### ISSUE TITLE
[Bug]: Child branch's theme is getting applied to master in view mode, even when we didn't merge the child branch changes to master

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#19130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/209078033-2ed8ceae-359c-4431-90da-920957c7c297.mov

### Steps To Reproduce

1. Go to this application: https://release.app.appsmith.com/app/theming-app/page1-632a9c3b9cc70b2afce4d98f/edit?branch=master
2. Go to latest deploy preview and observe

### Version

Release

**Comment by sidhantgoel** [comment]
test

**Comment by sidhantgoel** [comment]
test @sidhantgoel
