### ISSUE TITLE
[BUG]: CurrentItem is not updated in Table Widget and JSONForm Widget

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#19155]
Add a Table widget or JSONForm and change the Table Data or source data respectively to 

TableData
```
{{[
	currentItem
]}}
```
or Source Data
```
{{currentItem}}
```

The table or JSON Form doesn't receive the correct value when you switch pages

**Comment by ashit-rath** [comment]
Closing this issue in favour of merged [PR](https://github.com/appsmithorg/appsmith/pull/15839)
