### ISSUE TITLE
[Bug]: Query on MySql DS fails to execute when switched to a newly created branch

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#19169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a branch and switch to it, MySql query fails to execute on the new branch, while the other query (PostGreSQL) executes just fine.
Note: From the parent branch, the MySql query executes fine.

### Steps To Reproduce

1. In the Roles section (of a new role), Datasources and Queries tab, give Execute and View permissions on the MockDB, Users DB and MySql DB, add this role to Group1 and add User1 to Group1.
2. Also in the Application Resources tab, give Edit and View permissions to the queries associated with the above DB for that particular application (In this case Spring Boot 1)
3. Now login and edit the app with that particular user. 
4. Access all the queries (PostGres/MySQL) from Master and first created branch. All of the queries work
5. Create a new branch and switch to it - note there are errors related to the MySql query. 
6. Now run the MySql query by itself, still note it errors out.

<img width="614" alt="RBACNewBranchMySQLQeuryError" src="https://user-images.githubusercontent.com/101863839/209297993-bb51c440-1733-498d-9647-177c55db4268.png">

### Version

Instance

**Comment by RakshaKShetty** [comment]
Tried to repro the Issue but unable to do it closing the issue for now
