### ISSUE TITLE
[Task]: Change event when users invited to Workspace

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#19167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Change the event from `user.invite` to `role.assigned_users` when a user is assigned to a workspace.

**Comment by infinitetrooper** [comment]
@nsarupr  - If this is not closed. I would keep both events when adding new users. The reasoning is that at a workspace level inviting new users/associating a role happens at the same time and we need to track them separately. There would be cases where you just associate a role (like for example from the member's page), in which case you would only call the associate role event.

We need to always have an INVITE_USER event when a new user is being invited.

**Comment by nsarupr** [comment]
This has been resolved and tested.
