### ISSUE TITLE
[Bug]: Select Role or Group - Rename and Edit icon have the same functionality - Rename could be done away with.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#19165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the particular Group or Role UI, the Role name can be edited with the icon, and also through the Rename option available in the kebab menu. The Rename option can be discarded.

### Steps To Reproduce

Click on Roles and click on a particular Role to open it.
The Role name here can be edited with the icon, and also through the Rename option available in the kebab menu. The Rename option can be discarded.
Same goes with the Group UI
<img width="1128" alt="RBAC_Edit_Rename" src="https://user-images.githubusercontent.com/101863839/209287087-2bbac090-ef27-4d12-9f51-561b4a3136bb.png">

### Version

Instance

**Comment by infinitetrooper** [comment]
I think it's okay to have the two entry points to rename as some expect the edit functionalities to be in 3-dot menu. I'm closing this for now, we can revisit if we get additional feedback.
