### ISSUE TITLE
[Bug]:  The orders of pages is different from what is shown in the App, in the Roles UI

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#19162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The orders of Pages listed in the Roles UI is different from what is seen in the Application. This should be consistent - as seen in the Application.

### Steps To Reproduce

When we go to the Roles page of Admin settings, as a user I expect to see the pages in the same order as is seen in the application. 

<img width="311" alt="RBACAppOrder" src="https://user-images.githubusercontent.com/101863839/209286030-d2829473-2cbe-47e5-8634-0037266e26b6.png">
<img width="1110" alt="RBAC_RoleOrder" src="https://user-images.githubusercontent.com/101863839/209286039-9ff349e1-4982-4d6d-ab35-d8254d594c4c.png">

### Version

Instance

**Comment by Nikhil-Nandagopal** [comment]
This isn't valid as these 2 are not related in any way
