### ISSUE TITLE
[Bug]: Order of buttons not consistent in some pages

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

At some places we see `Primary Button` (orange in colour) on the left & the other place we have a Secondary Button on the left. 
<img width="1135" alt="Screenshot 2022-12-23 at 5 10 38 PM" src="https://user-images.githubusercontent.com/39921438/209330281-356d1357-41c9-4bba-b691-ecf5563f20ac.png">

### Steps To Reproduce

1. Go to `Admin Settings`.
2. Click on `Roles`.
3. Try to edit a Default role and then click on another Tab.

### Version

Cloud

**Comment by infinitetrooper** [comment]
@Debsourabh - Is this something we need to look at or was this made on purpose?

**Comment by ankitakinger** [comment]
I think this has been fixed with ADS 2.0 project. Closing this.
