### ISSUE TITLE
[Bug]: Adding page from template gives unable to find plugin error on trying to add pages when I login through a user other than super admin

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#19178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a page from a template, I get an unable to find plugin error when I login through a user other than super admin. 

### Steps To Reproduce

1. Login with a user other than demo@appsmith.com into this instance - http://65.0.99.89
2. Try to add a page from a template
3. Choose say S3 or PostGreSQL from datasources
4. Click on the template and add selected pages.
5. Note the error. 
<img width="909" alt="Screenshot 2022-12-23 at 3 11 09 PM" src="https://user-images.githubusercontent.com/101863839/209318796-b8860458-1950-4650-a092-29fa83a115c2.png">

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/8tNulzy2WHHPEiFv

### Version

Instance

**Comment by infinitetrooper** [comment]
@btsgh - This flow is not replicable in [test.appsmith.com ](https://test.appsmith.com/applications) which is running `Appsmith Business v1.8.15`, Can we reverify this in any other environment (release may be) and then we can decide to take it up.

**Comment by infinitetrooper** [comment]
@RakshaKShetty - Please verify and close if this is not reproducible.
