### ISSUE TITLE
[Bug]: Button variant used is incorrect on the Quick Page Wizard

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#19180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the quick page wizard, the Generate Page button variant used is incorrect, as per the design system specs (comparing also with Prod).  

### Steps To Reproduce

Try to create a page with the quick page wizard. Note the Generate Page button differs from what is used in Prod.

<img width="500" alt="ButtonColor1" src="https://user-images.githubusercontent.com/101863839/209331739-46953c37-0e1e-4b56-9706-15ba422c760c.png">
<img width="486" alt="ButtonColor" src="https://user-images.githubusercontent.com/101863839/209331754-b98e6f7a-ca93-4ccf-a1eb-d18de9a38e61.png">

### Version

Instance

**Comment by ankitakinger** [comment]
@btsgh could you re-check this and let me know if you're still seeing this? I'm not able to see the other variant on the instance. It looks same to me on prod and on instance.
