### ISSUE TITLE
[Bug]: When the user removes his own instance admin access, an "Unauthorised error" is shown

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#19197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user removes his own instance admin access, an "Unauthorised error" is shown on the GAC user screen, and when he goes back to any other page then he is still able to see admin settings unless he refreshes his page and loses access as expected.

So the solution here would be to redirect the user smoothly to the home page and not show any error. 

### Steps To Reproduce

1. Login as a user who is a super admin via getting the role `Instance Administrator`
2. Go to admin settings page
3. Go to users tab
4. Click your own user from the users list
5. Remove `Instance Administrator` role 
6. Notice that there is a toast message that reads `Unauthorised access`
7. Try switching pages within Admin settings nothing happens
8. Now refresh your page and notice you have lost access to Admin settings since you are not a Super admin anymore.

### Version

Self hosted - release

**Comment by sharanya-appsmith** [comment]
Facing this error again.

Recording: https://www.loom.com/share/bfb28e5c347a44a6af2e2fe98cff4a92?sid=01cecd34-9e57-427c-aae0-d64e6b8aa088

Steps:
1. Created a test user 
2. Assigned instance admin role 
3. Logged in as test user 
4. removed instance admin role 
5. refreshed page, admin settings ion left pane is removed as expected but unauthorised error is thrown on saving the changes in the user page.
