### ISSUE TITLE
[Bug]: No error thrown if Default value is not present in the Options list

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If we enter a Default value such that it is not mentioned in the `Options` field, no error is thrown.
https://www.loom.com/share/d35c7b0b3965458f87c23f71c01b026a

### Steps To Reproduce

1. D&D a Switch Group widget.
2. In the `Default Value` field enter any value that is not present in the `Options` field.

### Version

Cloud

**Comment by somangshu** [comment]
This is not an error, its expected. What if the values are coming from a server side query and the object does not have the default value right now, but might have it in certain cases, We must not throw an error for that. 

cc @dilippitchika please correct me if I am wrong

cc @yatinappsmith
