### ISSUE TITLE
[Bug]: Ensure Appsmith server starts only after RTS is up in fat container

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#19207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the server has an RTS health check at start up, we need to make sure that the RTS server is up before the server starts. 

### Steps To Reproduce

When the container is pulled up for the first time, RTS will always start first because of the migrations and other delays in Spring Boot start up. However, somewhere along its lifecycle, supervisor ends up pulling up rts a little after server during restarts.

[Here's](https://github.com/appsmithorg/appsmith-ee/actions/runs/3777307447) a CI run that mimics this.

### Version

Cloud

**Comment by pratapaprasanna** [comment]
https://github.com/appsmithorg/appsmith/pull/19218 Linked PR
