### ISSUE TITLE
[Feature] Allow users to save APIs as datasources so that they can be reused

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1920]
## Summary
Users should be able to save an API along with its configuration so that it can be reused.
The configuration that needs to be saved:
1. Headers
2. Params
3. Authorization

## Motivation

1. This will enable users to easily switch API endpoints when they need to move from release to prod endpoints
2. This will enable users to use a single endpoint multiple times across pages and apps

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek how is this different from our save API as a datasource feature today?

**Comment by areyabhishek** [comment]
It's the same one, needs some UX updates. I had created this issue for @aakashDesign

**Comment by aakashDesign** [comment]
Closing this issue, design shared with API Pane redesign team.

<img width="1351" alt="Screenshot 2021-01-11 at 11 10 35 AM" src="https://user-images.githubusercontent.com/65771350/104149803-a2e9e180-53fd-11eb-94d9-665ab447d5b0.png">

<img width="1368" alt="Screenshot 2021-01-11 at 11 10 20 AM" src="https://user-images.githubusercontent.com/65771350/104149796-99f91000-53fd-11eb-9d08-002782ae0927.png">
