### ISSUE TITLE
[Bug]: "Deploy" button turns black for a second after we refresh the page

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Deploy` button on the top right corner of the app turn black for a second before turning back to its original orange colour after we refresh the page.
https://www.loom.com/share/831c1c69924d4f78803bfc91d5d1ce3b

### Steps To Reproduce

1. Go to any app.
2. Refresh the page.

### Version

Cloud

**Comment by somangshu** [comment]
@jsartisan is this being worked on?

**Comment by jsartisan** [comment]
Closing as it's a duplicate of #19530
