### ISSUE TITLE
[Bug] Change the landing page text of a new app

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1921]
## Description
The landing page of a new app is misleading since there is no widget one can drag unless they click on the `+` icon next to widgets

<img width="1477" alt="Screenshot 2020-11-26 at 1 22 48 PM" src="https://user-images.githubusercontent.com/12022471/100322578-7cf1b480-2fea-11eb-9062-d8c51fee7287.png">

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we haven't seen any real problems with users figuring out drag and drop
