### ISSUE TITLE
[Bug]: Ambiguous error message when adding multiple default roles of the same workspace for an entity(user / user group)

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Video attached has 2 issues:

1. When permission groups have overlapping permissions and the user tries to add this then the error message is not clear enough and contains grammatical errors.

2. Multiple permission groups can be selected but when adding overlapping permission groups, all actions fail instead of stating to the user which exact permission group is causing the issue.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/209546030-4df44a99-b9d8-414a-a1c5-8042c538a736.png)

### Issue video log

https://www.loom.com/share/75eec10a6b654a82ad3268325aaa0c66

### Version

Self-hosted v1.9

**Comment by riteshkew** [comment]
Not valid anymore. Checked in v1.20
