### ISSUE TITLE
[Bug]: Errorneous `git pull` results in incorrect git history with respect to DB state

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#19211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the application is connected to git and have upstream changes Appsmith recommends to pull the changes to sync the application with remote. But in situations when the pull fails for some unknown reason we end up in a state where:
1. As per git perspective pull was successful and the history shown no upstream changes
2. From DB perspective as the flow was not completed DB does not have the latest changes from remote
This results in a situation where we can see the resources present in remote repo but the same are not present in Appsmith UI.  

### Steps To Reproduce

This is easy to reproduce in local setup as this is corner case:
1. Connect the existing application to git.
2. Add a random commit to remote so as to have upstream changes compared to local repo
3. Put a breakpoint in pull flow after the git pull is done (application import method is a good place here)
4. Kill the server
5. Restart the server and check the git-status response where no upstream changes are shown. 

### Version

Cloud: v1.8.14

**Comment by riteshkew** [comment]
Resolved as per the latest version and these states would be covered as part of native git
