### ISSUE TITLE
[Bug]: Invalid error reporting when `git-pull` fails

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#19215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When git-pull fails due to some unknown reason server is not reverting with the correct error please check the screenshot for ref. This is originating from the import flow as we are using this under the hood. 
https://github.com/appsmithorg/appsmith/blob/c7fc7cf7a9cf345d4f7e3b9053cc50e0d3f3528b/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java#L1227  

![image](https://user-images.githubusercontent.com/41686026/209915149-bed1b738-00b1-4e92-b6ba-26ce49e0c9d6.png)

 

### Steps To Reproduce

This is not easily reproducible as there might be some edge case that is causing import flow to result in an erroneous state. But we have seen this happening with different users.

https://app.frontapp.com/open/msg_1fmff26k?key=https://app.frontapp.com/open/cnv_s8tpln0?key=MVxr9a-AGjSoqs2WnZP6YgWqDda09yqM

https://community.appsmith.com/t/an-error-404-page-not-found-appeared-while-trying-to-connect-a-new-branch-in-the-github-repository/1794/3?u=abhvsn

### Version

Cloud: v1.8.14

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6tito)

**Comment by nayan-rafiq** [comment]
Failed to reproduce this. However, improved the following logs so that debugging is easier:
1. When a plugin in missing, added the name of the plugin to the error message as well as in the error log.
2. When plugin is missing, the list of available plugins are printed in the error log.

**Comment by infinitetrooper** [comment]
Closing as per above comment.
