### ISSUE TITLE
[Bug]: "Sorry, but your account doesn't have access" error is displayed In the Edit mode of the App

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

"Sorry, but your account doesnt have access" error is displayed In the Edit mode of the App
![image](https://user-images.githubusercontent.com/45958978/209549947-b609f514-388c-4e6d-824e-4ca351735dac.png)

### Steps To Reproduce

1. Login as admin
2. Create. anew app
3. in home page create a crud page now 
4. Now add new db 
5. from active tab 
6. Create a new crud page
7. The error is displayed when the page got created

### Version

release

**Comment by ankitakinger** [comment]
API is returning blank array for `userPermissions` when you click on `Generate page` from Datasources active tab:
API: https://release.app.appsmith.com/api/v1/layouts/:layoutId/pages/:pageId?applicationId=:appId
<img width="608" alt="image" src="https://user-images.githubusercontent.com/28362912/209566845-4a6c64eb-c741-439e-a5e9-3203e2ccbcd0.png">
<img width="603" alt="image" src="https://user-images.githubusercontent.com/28362912/209566857-3e5ca0c5-d606-42b2-b0cc-c49884233ec3.png">
<img width="603" alt="image" src="https://user-images.githubusercontent.com/28362912/209566867-e9704c4e-c81b-4211-9fa8-e8efbd7a48e1.png">

@nsarupr @trishaanand
