### ISSUE TITLE
[Bug]-[80]:app goes into bad state when we use Assignment operator instead of equality comparison operator in text widget

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#19221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/b62e126011a24ed394502dded9171ba1

App goes into bad state when we use "=" instead of "==" in the bindings with text widget and the value is an integer

### Steps To Reproduce

1. DnD a text widget
2. Dnd any other widget and use the binding anywhere "{{Text1.text=1}}"
3. app crashes

### Version

Production

**Comment by somangshu** [comment]
Assignment should not be possible AFAIK, @satbir121 can you tell me if that is right. 
In that case this will be the evaluation that will manage this issue

**Comment by bharath31** [comment]
Related to #17091

**Comment by bharath31** [comment]
this is not reproducible anymore

**Comment by kamakshibhat-appsmith** [comment]
@bharath31 This can be reproduced . Pls check [loom](https://www.loom.com/share/59223debd64244aeb413841816b85074)

**Comment by bharath31** [comment]
Assuming 1% of users who update widget properties face this issue

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 20 |
| Effort (months)  | 0.5 |
