### ISSUE TITLE
[Bug]: Incorrect error when editing default roles for RBAC

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user tries to edit default roles, we see an error for not having permission to edit role, nothing about the restrictions on modifying default roles.

### Steps To Reproduce

1. Try to modify a default role from admin settings page and note the error displayed

![image](https://user-images.githubusercontent.com/79509062/209550647-c240b585-08d9-4e3d-9ce8-647adedf7549.png)

![image](https://user-images.githubusercontent.com/79509062/209550678-2dd654e9-495a-4c49-b871-d42bb8fe1e38.png)

### Version

Self-hosted v1.9 release version

**Comment by ankitakinger** [comment]
@ramsaptami can we close this issue since this was happening on old fat container?

**Comment by ramsaptami** [comment]
Yep, closing it
