### ISSUE TITLE
[Bug]:Issue with URL Column type in Table widget

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#19225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For column type URL, the URL link is getting appende to the homepage link and hence incorrect behaviour is observed

### Steps To Reproduce

1. DnD a table widget
2. Bind any DB and change anyone column type to URL
3. Click on that URL link
you'll notice the link was appended to the home page URL

### Issue video log

https://www.loom.com/share/54fd482c08244f449be04c0b084942e5

### Version

production

**Comment by dilippitchika** [comment]
@kamakshibhat-appsmith can you check if this is same as #17022 because i think it is. If yes, can you please close it as a duplicate?

**Comment by kamakshibhat-appsmith** [comment]
Closing this as duplicate of [#17022](https://github.com/appsmithorg/appsmith/issues/17022)
