### ISSUE TITLE
[Bug]: Focus on the "Menu items source" property shifts when we switch on the options, to Menu label

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#19227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we enter some Label text in Menu widget property, and then switch between "Static" and "Dynamic" Menu items source property, user able to see the focus shifts to Label text property

### Steps To Reproduce

1. D&D a Menu widget
2. Enter some text in the Label property
3. Click on "Static" and then click on "Dynamic" in the Menu items source property
4. Repeat once or twice
5. Observe the focus shifts to the Label property.

### Issue video log

https://user-images.githubusercontent.com/104895602/209556574-5307c8a8-a37d-4595-b715-6745de24f6db.mp4

### Version

Release

**Comment by somangshu** [comment]
Could be something to do with Context switching / Property pane keyboard accessibility. cc @aswathkk @rahulramesha

**Comment by rahulramesha** [comment]
@Sripriya93 are there any specific steps, apart from the above mentioned? I seem to be unable to reproduce this bug on release

**Comment by vinay-appsmith** [comment]
No longer an issue / cannot be reprodocued with ADS 2.0.
