### ISSUE TITLE
[Bug]: The API is saved as datasource even when user doesnt want to save API as a datasource

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The API is saved as datasource even when user clicks on Dont save button 
https://40edv1d3xs.vmaker.com/record/hqwrqphKXylUHhIW

### Steps To Reproduce

1. Login to the appsmith
2. Create a new api
3. Now click on save as datasource
4. Click on back link on datasource edit page
5. Now click on dont save
6. now go back to API pane again click on save as datasource 
7. Again click on dont save 
8. Go back to API pane the API seems lit saved like a datasource

### Version

production

**Comment by sumitsum** [comment]
Closing it as this is not applicable anymore because auto save of datasource has been removed.
