### ISSUE TITLE
[Bug]: Reaching Internal server error state when inviting the same user with a different role via invite modal

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#19244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Reaching Internal server error state when inviting the same user with a different role via invite modal. It works fine if the role is changed via Members page dropdown.

While I noticed this with email ids being invited, this change of role via invite modal throws an error for groups. I think it should work the same with email ids.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/28362912/209639135-9809c645-6576-4997-8300-4eaaba3700dd.png">

### Steps To Reproduce

Adding the video recording here that explains the issue and the steps to reproduce the same:
https://cjrc9tc9nt.vmaker.com/record/iY2y6whhGQ0xQzw7

### Version

Cloud / Self Hosted - Release

**Comment by trishaanand** [comment]
This is an issue that we haven't solved for. The invite is only to add new users in the workspace. To change the role of a user, you have to be an administrator. Then you can head to members page and change the role of existing user.
