### ISSUE TITLE
[Bug]: When user has edit permission for application, they are able to copy the Queries/JSObject/ Api

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#19257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user has edit permission for applications, they are be able to copy the Queries/ JSObject/ Api however on refreshing these actions are going away. Ideally with edit only permission we should not be able to copy the actions

https://user-images.githubusercontent.com/80334441/209681307-4c136a24-4cd2-4a23-be90-5259e4ea1f9a.mov

### Steps To Reproduce

1. Login as admin and create new role with edit permission for application
2. Assign this role to user1
3. Login as user1 and go to the application
4. For any of the query/api/jsObject try copying them to other page
5. Observe we are able to copy these actions however on refresh it goes away.

### Version

Release

**Comment by ankitakinger** [comment]
@Parthvi12 this should have been fixed yesterday. Could you take latest docker pull for release and try reproducing this issue?

**Comment by ankitakinger** [comment]
This is fixed and verified by QA.
