### ISSUE TITLE
[Bug]: The execution of the API goes to Infinite loading in edit mode when API just have View and execute permission 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The execution of the API goes to Infinite loading in edit mode when API just have View and execute permission 
![image](https://user-images.githubusercontent.com/45958978/209667192-45b597ef-7981-4d1e-aae8-c1a22f3c0462.png)
![image](https://user-images.githubusercontent.com/45958978/209667206-7dfe88a9-25ea-45c9-bbfd-5df80266b2c4.png)

### Steps To Reproduce

1. Login as admin
2. go to admin setting page 
3. Imagine page has 2 apis
4. Give one API all crud permission
5. The other API just give View and execute permission
6. No assign it to user 1
7. Login as user 1
8. Now go to API section 
9. got to API which  has only view and execute access
10. Now run the API 
11. The api Is struck 

### Version

Localhost

**Comment by infinitetrooper** [comment]
Duplicate of #19055 as per `rbac_coverage`

**Comment by infinitetrooper** [comment]
Link #19055

**Comment by ankitakinger** [comment]
Not a duplicate of [#19055](https://github.com/appsmithorg/appsmith/issues/19055)
