### ISSUE TITLE
[Bug]: error when connecting to TiDB Cloud cluster

### ISSUE THREAD

**Issue by zhangyangyu** [appsmithorg/appsmith#19266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When connecting to TiDB Cloud Serverless Tier(a MySQL compatible database), it reports an error:
![image](https://user-images.githubusercontent.com/3690895/209770620-b1852bf1-9448-4d5e-b5dd-133822270f42.png)

Definitely, the server supports and requires SSL.

From the error message, seems appsmith is using r2dbc-mysql. Check this issue to see more detail: [fail to check capability in handshake packet · Issue #244 · mirromutth/r2dbc-mysql · GitHub](https://github.com/mirromutth/r2dbc-mysql/issues/244). Unfortunately r2dbc-mysql seems losing maintaince [Is the maintenance of this project stopped？ · Issue #243 · mirromutth/r2dbc-mysql · GitHub](https://github.com/mirromutth/r2dbc-mysql/issues/243). Maybe we could switch to r2dbc-mariadb. I make a try and the connection problem won’t happen.

### Steps To Reproduce

1. create data source and choose MySQL
2. type all the necessary info to connect(you need a TiDB Cloud serverless tier cluster, you can [create one for free](https://tidbcloud.com/free-trial))

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6hkek)

**Comment by sribalajig** [comment]
We've already switched our driver, so we need to validate if this issue still persists

**Comment by zhangyangyu** [comment]
Test appsmith cloud, it works well now. Nice! @sribalajig
