### ISSUE TITLE
[Bug]: In a git connected app after deleting the page the same page is still shown in role config tab

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#19270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Connect an app to git
2. Create a branch
3. Add custom role
4. Now delete a page in master branch and do not commit
5. Go to to admin setting role config tab
6. Observe that the deleted page is still shown in the roles tab

### Public Sample App

release

### Version

release

**Comment by trishaanand** [comment]
This is expected behaviour. The role configuration screen today shows a union of edit and deployed resources for the application. The page would stop getting listed once the app is deployed and the page is deleted from both edit and view modes.
