### ISSUE TITLE
[Bug]-[16872]:OAuth2 is giving error on prod while the same project works fine on release.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#19283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to execute a drop box project which used OAuth2.0, it runs fine on release. However, when the same project is exported to production, its showing error.

### Steps To Reproduce

1. Configure/ Edit the data source
2. Click on "Save and Authorise"

Observe - First, there is a success message and then there is an error message.

### Public Sample App

https://app.appsmith.com/app/drop-box/orders-638dd78c2913ba43778b913d

### Issue video log

https://www.loom.com/share/ec2459b1de564bff997d90bc14cb40a6

### Version

V1.8.14

**Comment by rohan-arthur** [comment]
6m REST API usage: 5624
let's say 75% of them use authenticated api: 4218
of these, let's say again 50% use Oauth2.0: 2109

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2109 |
| Effort (months)  | 0.25 |
