### ISSUE TITLE
[Bug]: Adding span html element causes the text widget to break into multiple lines  

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#19285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i add 
`this is a <span style=color:#ff0000 ; > span </span> thing`
into text widget, it breaks line. Span class should never break line.

### Steps To Reproduce

1. Add a new text widget
2. Add the text as `this is a <span style=color:#ff0000 ; > span </span> thing`
3. Observe that the text splits into multiple lines

### Version

Cloud

**Comment by dhruvikn** [comment]
[Here's where](https://github.com/appsmithorg/appsmith/blob/1de045d9d841299587b091f3947e4023c3af36ad/app/client/src/widgets/TextWidget/component/index.tsx#L147) the issue is originating from. Git Blame tells me it was added in #18341. Any idea @riodeuno
