### ISSUE TITLE
[Bug]: Multiple Environment Issues : Round 1

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#19313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**List of Issues**

### UI/UX issues
- [ ] “Value for production/staging” should not be displayed until Input field is selected 
- [ ] Cancel does not look like a button.
- [ ]  Bind Values should be active only after mandatory fields are added 

### NEED CLARITY
- [ ] The Advance setting is not functional 

### BLOCKED
- [ ]  GraphQL ,Auth API and Gsheet does not have Manage environment integrated 
- [ ] On unselecting the dropdown the watermark must be displayed.
          (Issue in design system, thread is being followed [here](https://theappsmith.slack.com/archives/C0293DVQACW/p1674223279615279).)
          
### Fixed (from dev, QA pending)
- [ ] #20041
<s>- [x] Clicking on “back” button on Manage environment page user is navigated to Active datasource page Expectation : user must be navigated to Datasource page as in “Cancel” </s>(https://www.loom.com/share/489f6b6f33d14bf4b668175b74cb97cd) **(VERIFIED and Fixed)**        
- [x] Manage environment page is broken (Intermitten Issue) **(VERIFIED and Fixed)**
- [x]  Auto save datasource Popup appears and then we switch the env click on don’t save and observe the user is landing on Invalid page instead of Active Datasource page
- [x] #20063
- [x] After I enter the details of the page if the switch the environment the data is lost and user has to re- enter is the expected <https://www.loom.com/share/01d466633c3941d69ebad81badade89d> **(VERIFIED and Fixed)**
- [x]  Fields does not appear on selection on Connection String URI in Mongo **(VERIFIED and Fixed)**<https://www.loom.com/share/f4ba5828f5b24f43acc0d7c4821dc342>
- [ ] #20062
- [x] Switching between bottom environment and click on “Don’t Save”  lands the user on Invalid page **(VERIFIED and Fixed)**
- [x] Missing the flows of "Auto Save" . <https://www.loom.com/share/de58f7b4349e41e0bb401e276660c7b3>
          1) User must be navigated to Manage environment with Save in backend
          2) Switching between footer environment dropdown with pop up is not changing the landing page on Manage 
               environment UI 
          3) Internal navigation is suggested for manage environment page from datasource page
- [x] Crash observed on the Postgres page by clicking on "Dont save" . Please observe a video here **(VERIFIED and Fixed)**
<https://www.loom.com/share/fc7563a12a3f40aea5c9d18a0e42d768>
- [x] Url is not having environment details when user clicks back from the datasource page. **(VERIFIED and Fixed)**
                  Steps to reproduce:
                  1) Go to an existing datasource, say - users (its there in the existing application under test)
                  2) Select an env Observe - Its there in the URL - .....   environment=production
                  3)Now, Press back
                  Observe - The env info is not present
                  Also, go to any page and then open a datasource. Env info is not embedded in the url
- [x] Open a datasource in edit mode. Change the env. Observe - its not getting changed.**(VERIFIED and Fixed)**
- [x]  Manage env - When the user configures a value for a particular fieldsc- say db name and clicks on “Bind values”, there is no CTA **(VERIFIED and Fixed)**
      Steps to reproduce:
            a. select a datasource
            b. click on manage env
            c. select an input field
            d. give a value
            e. Click on “Bind values”
            Observe - There is no network call / value is not getting submitted
- [x]  If the selected environment is staging, then also its coming production by default in configure env section in Manage environment section **(VERIFIED and Fixed)**
- [x] Manage environment configuration page - Few attributes missing in general across different data sources in Input field dropdown. **(VERIFIED and Fixed)**
- [x] Internal Navigation of Manage environment is important for user experience **(Due to Tech debt we are doing manage env after the datasource is saved)**
- [x] Clicking on Bind value the user is displayed with error message (its different each time and not understandable )
- [x] Though we can see the binding in DB ,Navigating back to Manage environment page from the datasource we observe that the variables are not saved and user is on production while we have configured variables for staging.
- [x] Clicking on “Manage Environment” button the Auto Save pop up appears click on “Don’t save” the user is lead to “Manage Environment” Page this make the manage environment variable dangling. **(VERIFIED and Fixed)**
**Expectation : user on Don’t save must be lead to create New datasource page**
- [x] Add a new datasource. Now change the environment. Observe - Alert comes and disappears and the page is refreshed. Environment is not changed **(VERIFIED and Fixed)**
- [x] Open an already saved datasource in edit mode. Change the env. Observe - env is not changed. **(VERIFIED and Fixed)**
- [x] In the rest API datasource, the endpoints are not getting saved according to stage and prod. Whatever, the user updates for an env, it gets updated for both the env **(VERIFIED and Fixed)**
- [x] #19980

**Comment by ayushpahwa** [comment]
@parth-appsmith @sribalajig please take a look at the issues tagged under UI/UX. Thanks.

@riteshkew

**Comment by btsgh** [comment]
1. Issues that are ticked by Dev have been verified and commented against by QA
2. Issues that are still open are tracked on the Notion doc [here](https://www.notion.so/appsmith/e7fb3c8e47e54bd2b2bc34821cfec8b8?v=bd58ca7e2d8b42a1bfee5485eeb8a56c).
3. Issues that are still reproducible have been opened as new bugs in github

Hence closing this issue
