### ISSUE TITLE
[Bug]: Performance improvement on Groups and roles Tab

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#19314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Performance improvement on Groups and roles Tab
unable to check the data in the Groups & roles tab until we refresh the page each time

### Steps To Reproduce

1. Login to instance http://65.0.99.89/user/login
2. Login as admin
3. go to admin setting Page 
4. Atleast try to have  10 workspace
5. Now got to roles tab 
6. Crate a custom role
7. Go to Groups and roles tab
8. The app breaks 

### Version

release

**Comment by trishaanand** [comment]
This would require both backend and frontend changes since the API response is changing to support performance.
