### ISSUE TITLE
[Feature] Open links in new tab on trigger

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#1932]
## Summary
Allow users to open custom URLs in a new browser tab in response to a trigger.

## Motivation
In some scenarios, the content which the user can follow by clicking on a button or on success of an API response will be available in an external page. The developer would want users to have the content open in a separate tab without losing Appsmith's context.

**Comment by areyabhishek** [comment]
Applicable widgets:
1. Text widget
2. Table widget

**Comment by mohanarpit** [comment]
Should this be the default behaviour of a link click in Appsmith? Are there scenarios where the user would like to click on a link & open the URL on the same page?

**Comment by Nikhil-Nandagopal** [comment]
I believe the use case here was to add a param to the navigateTo function so that it could open a page in a new tab. Links by default can be opened in a new tab using cmd + click or the <a href /> tag so that a single click opens in a new tab

**Comment by areyabhishek** [comment]
This issue was requested by a user because they were unable to include clickable URLs in the table widget. I created #1935 for that specific issue. But they also asked if they can use HTML in UI widgets and their use-case was to open links in a different tab.

**Comment by hetunandu** [comment]
This was fixed in #2706
