### ISSUE TITLE
[Task]: Create a toast component

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19331]

**Comment by tanvibhakta** [comment]
TODO: check the font of the toast on a windows machine

**Comment by tanvibhakta** [comment]
Depends on Icon https://github.com/appsmithorg/appsmith/issues/19332
Depends on Link https://github.com/appsmithorg/appsmith/issues/19345
Resolved dependency on Text https://github.com/appsmithorg/appsmith/issues/19325
