### ISSUE TITLE
[Feature] Introduce URL as a data type in table widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1935]
## Summary

Users want to display clickable URLs inside a table. This was requested by a user on Intercom.

## Additional Context
Properties for the URL field:
Same properties as text and:
1. Open in same tab? (check box) 'show icon beside URL on hover'
2. Underline URL?

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek @riodeuno 
Shall we change the open in same tab property to
**action:** with options 
- navigate to page
- open in new page 
- download file

What does underline do? aren't all URL's underlined?

**Comment by srijanshetty** [comment]
@Nikhil-Nandagopal your suggestion would cover 100% of my usecases. Here I want to either download a S3 file or open it in a new tab.

Instead of an underline, a markdown style alternative name for the URL would improve readability.

**Comment by Debsourabh** [comment]
https://www.figma.com/file/BDwcsdhWRjXOHOjcnMtz6S/?node-id=0%3A1

Kindly leave comments. This is for review only

**Comment by riodeuno** [comment]
Note:
- Links should look like as seen in the designs with the icon to mark it as a URL
- Links when clicked should open in a new tab

**Comment by Debsourabh** [comment]
Have made some changes to the design and updated it.
