### ISSUE TITLE
[Feature]: Create password-protected backup archives from `appsmithctl`, with salt and password included

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#19353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In the `appsmithctl backup` command we have today, we don't include the salt and password, deliberately. We inform the users of this command that they need to take these values separately, and save them safe. It never felt like a great experience, but we needed it so we don't export both the treasure-chest and the key togather.

This feature request is to include the salt and password in the generated backup archive, but then have the archive be password-protected. In the `appsmithctl backup` command, let's ask for a password for this purpose. If the user denies providing a password, or gives an empty password, continue to generate the archive without the salt and password, and inform them of this, as is currently the case.

We can also provide a `appsmithctl backup --non-interactive` that can be used in `cron` or other scripts, that doesn't ask for a password, and doesn't include the salt and password in the archive.

For backwards compatibility, let's ask for password _only_ if we detect a TTY being available.

### Why should this be worked on?

The backup archive created by `appsmithctl backup` doesn't include the salt and password, but the archive is almost useless without the salt and password. Despite illustrating this in [our docs](https://docs.appsmith.com/getting-started/setup/instance-management/appsmithctl#backup), and also in [the command's output](https://github.com/appsmithorg/appsmith/blob/c2a7face0c9b8a855a673829b3c4777b2041aa5d/deploy/docker/utils/bin/backup.js#L97-L99), people still miss this.

This feature would ensure that the user of the `appsmithctl backup` command has to pause and think about this, when the password prompt appears, or the command won't proceed.

**Comment by pratapaprasanna** [comment]
Fixed in this [PR](https://github.com/appsmithorg/appsmith/pull/29902)
