### ISSUE TITLE
[Bug] Copying text with Cmd+c or Ctrl+c doesn't work in API editor's Response Body tab

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#1937]
## Description

In the API action editor's UI, the response of an execution shows up in the *Response Body* tab. Although we can select text in this content, hitting `Cmd+c` or `Ctrl+c` doesn't copy the selected text. Right clicking the selected text and choosing `Copy` does copy the selected text however.

### Steps to reproduce the behaviour:

1. Create an API action to the URL `http://httpbin.org/get` (any URL should work for this test).
1. Execute the action and notice the resulting JSON in the *Response Body* tab.
1. Select some fragment of the content in the response body and hit `Cmd+c` or `Ctrl+c`.
1. Observe that the selected text has not been copied by attempting to paste elsewhere on your system.

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by Nikhil-Nandagopal** [comment]
This is actually true of anywhere on the appsmith editor today

**Comment by sharat87** [comment]
It is true of *non-editable CodeMirror instances* only. It works fine with editable CodeMirror instances.

**Comment by Nikhil-Nandagopal** [comment]
This is true of any non editable text not just code mirror. Try copying even the text "form widgets" from the widgets section and it doesn't

**Comment by Nikhil-Nandagopal** [comment]
This has become a high annoyance so bumping up the priority
