### ISSUE TITLE
[Task]: Deduplicate tooltip component in CE & EE

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19370]

**Comment by tanvibhakta** [comment]
List of blueprint tooltip usages: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1673270280336749

**Comment by rohitagarwal88** [comment]
Closing it coz of change in release plan. Tracking it in epic https://github.com/appsmithorg/appsmith/issues/20460
