### ISSUE TITLE
[Task]: Deduplicate components & Grayscale/theming support in Profile page

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19389]

**Comment by laveena-en** [comment]
Issues with profile page:

1. Hand cursor isn’t seen on hovering over the profile icon
2. An unintended tooltip is seen on hovering over the profile section 

https://user-images.githubusercontent.com/109572422/233547115-f43655d4-2287-4137-a8f6-d3749bb12489.mov


3. Can we have a tertiary button for `Upload profile picture` and a tertiart button for `Reset password`
![image](https://user-images.githubusercontent.com/109572422/233558515-4719308e-ce18-4f58-8194-dc55fcf5ae11.png)

4. Can we add in a heading `Profile` and `Display picture` as on release 
![image](https://user-images.githubusercontent.com/109572422/233558714-1ff749f3-e5e7-4493-9ffc-84a8460f4847.png)
![image](https://user-images.githubusercontent.com/109572422/233558757-344cdc53-90d8-4ddc-acfd-f53cfe51f934.png)

5. There seems to be a change in layout, is this intended?
6. Submit button to be changed sentence casing 
![image](https://user-images.githubusercontent.com/109572422/233559193-5689fbd5-dcea-4e3a-9874-c301c1d8fb8c.png)

![image](https://user-images.githubusercontent.com/109572422/233559110-e708403b-441b-4337-a78e-b3e57535dc8f.png)
