### ISSUE TITLE
[Task]: Deduplicate components & Grayscale/theming support in template page

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19387]

**Comment by laveena-en** [comment]
Issues with templates:

1. Grey background seems to be missing on the template images
2. Width of each template card has decreased when compared to prod
3. Icon is missing in the `Fork Template` dialog box
4. Components layout are broken on the `Reconnect datasources` screen

![image](https://user-images.githubusercontent.com/109572422/233418658-ea375138-ad3c-44e8-b4cf-f338bd29b8e4.png)

Loom for all the above mentioned issues: https://www.loom.com/share/2f54b110eb6e4aa4b06babb7eb9822e7
