### ISSUE TITLE
[Feature]: Create a side nav to reduce clutter in the Property pane

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#19419]
### Summary

Our entity explorer quickly grows to a massive size. this is quite annoying for users, and can quickly lead to confusion. We have noticed that there are a bunch of users who are wasting time searching for the right item in their entity explorer.

We are going to add different clear sections to clean up our entity explorer
1. Entities
2. Datasources
3. Libraries
4. Settings
5. Documentation

These will clearly organise easily accessible settings in the right places for users.  

### Why should this be worked on?

Our entity explorer quickly grows to a massive size. this is quite annoying for users, and can quickly lead to confusion. We have noticed that there are a bunch of users who are wasting time searching for the right item in their entity explorer.

Question | Answer
-- | --
Will we ship this behind a feature flag as well? | No. We will retain the current canvas states, where the user can collapse or show the entity explorer. We will remove this control once we remove the feature flag on the split pane view
What are the components in the side panel? | 1. Actions+ widgets, 2. Datasources, 3. Libraries, 4. Settings, 5. Docs

</ol>

**Comment by eco-monk** [comment]
Based on discussions.
Will revisit this when we get final designs.

- [ ] Add left section to open entity explorer - 1
- [ ] Split entity explorer based on left section selection - 3
- [ ] fix cypress cases - 4
- [ ] move settings pane to left side - 2
(investigate if this'll affect canvas rendering)
- [ ] fix cypress cases - 1

**Comment by eco-monk** [comment]
Documentation notes: (opening doc website as a pop-up instead of omnibar)
- Hide modal to preserve context (scroll, last opened page etc....)
- pause a video on closing
- hide -> close after 30 mins of hiding (performance reasons)

**Comment by kocharrahul7** [comment]
IDE 2.0 has solved this
