### ISSUE TITLE
[Bug]: Slowness in JS value properties eval

### ISSUE THREAD

**Issue by vsvamsi1** [appsmithorg/appsmith#19410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the JS Objects editor updates to properties like objects or arrays are not getting reflected immediately in the bindings. 

### Steps To Reproduce

In the JS Objects editor, I have defined a property myVar1 which is an array and later I have updated myVar1 array with a different value set. 
<img width="1198" alt="Screenshot 2022-12-31 at 12 56 16 AM" src="https://user-images.githubusercontent.com/121419957/210105694-082f9266-c436-4a4e-9827-a68cb863e650.png">

I have noticed that the new value does not get ingested in the bindings and continues to refer the older value. 
<img width="649" alt="Screenshot 2022-12-31 at 12 51 03 AM" src="https://user-images.githubusercontent.com/121419957/210105708-5f32a028-7c8e-488e-abc0-4dd6fd0c9e53.png">

Unless I perform a browser refresh does the value get reflected correctly.
I don't see this issue if the property is a function and any updates made here gets reflected immediately.

<img width="1440" alt="Screenshot 2022-12-31 at 1 01 31 AM" src="https://user-images.githubusercontent.com/121419957/210106022-6a0e5161-1302-4899-93b2-53b9267c55e6.png">

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is because of reactive variables not being supported yet

**Comment by somangshu** [comment]
@Nikhil-Nandagopal did not get how this is related to reactive variable; I think the problem says that JS objects sometimes stop evaluating correctly, even does not allow running the function; things start working as soon as you refresh the page. 

Can you please give a bit more context I am not getting what you are talking about?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu it's a bug in the platform where variables defined with a value aren't evaluated till the next render. Since they are only evaluated once at the time of load, this is the result.
