### ISSUE TITLE
[Task]: Update Lint errors to new interface

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#19421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Update all lint errors to newly designed interface.

**Comment by btsgh** [comment]
Observations -

- [ ]  console.log("Input4.text", Input4.text); - on adding this text in a JS object, and changing Input4 to say Inpu4, the lint error is generated correctly. However, on reverting it back to Input4, the error does not go away.

**Comment by btsgh** [comment]
Testsmith [link](https://github.com/appsmithorg/TestSmith/issues/2139)
