### ISSUE TITLE
[Bug]: Text Widget Inserts New Line When Using <span> Tag

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#19442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The **Text widget** inserts an unwanted new line when the user uses a `<span>` tag.
E.g., 
`this is a <span style=color:#ff0000 ; > span </span> thing`
results in:
```
This is a
span
thing
```
![image](https://user-images.githubusercontent.com/101268423/210304902-ceeb5150-302e-4ddd-9d7a-99a879f5c92d.png)
It should not add a line break before and after the `<span>` tag.

### Steps To Reproduce

1. Add a Text widget to the canvas.
2. Type some **text** and use a `<span>` tag. E.g.: `this is a <span style=color:#ff0000 ; > span </span> thing`
3. Note that **line breaks** are added before and after the text inside the `<span>` tag.

### Version

Appsmith v1.8.16-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6jeoc)

**Comment by dilippitchika** [comment]
@ame-appsmith we have closed this issue here - https://github.com/appsmithorg/appsmith/issues/19285 

It's already in release. Should be available in the next version

**Comment by tomgw** [comment]
I am on Appsmith Community 1.9.2 but it still does not work properly. The same error (inserted line breaks) happen when I enter'
` a <span style=color:#ff0000 ; > span </span> thing` in a text widget. Am I missing something?

**Comment by somangshu** [comment]
@dhruvikn is the given change has reached prod, can you kindly verify the above statement?

**Comment by dhruvikn** [comment]
Hey @somangshu @tomgw, I checked and it looks like this change will reach production in v1.9.3. The promotion happened yesterday https://github.com/appsmithorg/appsmith/pull/19545 

Please wait until the next release @tomgw. Thanks a lot.

**Comment by tomgw** [comment]
It works correctly in v1.9.3.1
Thanks!
