### ISSUE TITLE
[Bug]: Helm charts not picking up the values specified in values.yaml

### ISSUE THREAD

**Issue by rahul799** [appsmithorg/appsmith#19443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am using below commands to install appsmith helm charts
`helm install appsmith appsmith/appsmith -n appsmith --set applicationConfig.APPSMITH_ENCRYPTION_SALT="<salt>" --set applicationConfig.APPSMITH_ENCRYPTION_PASSWORD="<pass>"`
but when I ssh into the pod and do
`cat /appsmith-stacks/configuration/docker.env`
I find different values. It seems like charts are not picking up the values. 

### Steps To Reproduce

1. Run `helm install appsmith appsmith/appsmith -n appsmith --set applicationConfig.APPSMITH_ENCRYPTION_SALT="<salt>" --set applicationConfig.APPSMITH_ENCRYPTION_PASSWORD="<pass>"`
2. ssh into appsmith-0 pod
3. Run `cat /appsmith-stacks/configuration/docker.env`
4. Search for `APPSMITH_ENCRYPTION_PASSWORD` key and you will find a random value.

### Version

2.0.0

**Comment by rahul799** [comment]
I have also tried cloning the values.yaml locally and installing the application using below command
`helm install appsmith appsmith/appsmith -n appsmith -f values.yaml` but no luck.

**Comment by pratapaprasanna** [comment]
Hey, in kubernetes/helm based appsmith deployments the values mentioned in `applicationConfig` will be present as an environment variable. 

Thanks
