### ISSUE TITLE
[Bug]:  SSO (OIDC) with keycloak version 18.0.2 does not work.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#19449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user reported that keycloak version 18.0.2 does not work whereas version 19.0.2 + version works.

<img width="1039" alt="Screenshot 2023-01-03 at 2 01 53 PM" src="https://user-images.githubusercontent.com/13262095/210322623-63e087fe-8f27-43f8-ad99-3d573a3aca08.png">

### Steps To Reproduce

https://discord.com/channels/725602949748752515/1057219717938544751/1057996590964551720

### Version

v1.8.15

**Comment by infinitetrooper** [comment]
Appsmith only supports Keycloak v19+
