### ISSUE TITLE
Support App level invitation of users

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#19459]
App level invite feature will enable admins or developers to invite people to a specific application instead of the entire workspace.

**[Notion Page](https://www.notion.so/appsmith/App-Level-Invite-7b29e247e6484156a9286565d60c585c)**
**[Engineering Notion Page](https://www.notion.so/appsmith/App-Level-Invites-Engineering-27f821bfff4f4e818800a3144678459f#82f0047b53f842d5a507520976d4d6ea)**

**Comment by chethan27** [comment]
Hi @infinitetrooper , would like to work on this. can u assign it to me ?

**Comment by chethan27** [comment]
@infinitetrooper Thank you for letting me know. Will check out other issues.
