### ISSUE TITLE
[Feature]:  Add emoji picker to Rich Text Editor

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#19450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Community Request
https://community.appsmith.com/t/emoji-picker-widget/1818/2

<img width="575" alt="Screenshot 2023-01-03 at 2 13 10 PM" src="https://user-images.githubusercontent.com/13262095/210324109-2eb3cd22-adab-4662-bae5-be6a487aeb92.png">

### Why should this be worked on?

An emoji picker is very common across the board.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6jh3g)

**Comment by somangshu** [comment]
We need to add the [Emoticon plugin](https://www.tiny.cloud/docs/plugins/opensource/emoticons/) to the editor

Easy fix

**Comment by ampatzidhs** [comment]
i am interested to have this issue, can you assign me ?

**Comment by vsvamsi1** [comment]
HI @ampatzidhs I have raised a PR for this and it should move into production in the next few days.
