### ISSUE TITLE
[Task]:  Refactor dscontextserviceimpl methods to add custom map keys to avoid duplication in EE.

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#19451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In order to account for multiple environments changes, the `DatasourceContextServiceImpl.java` methods needs refactoring to achieve minimal code duplicity.
- Create class to hold the key for dscontext maps.
- Refactor methods in order to have minimum duplicity.

**Comment by AnandShahs123** [comment]
@sondermanish Tested following DS
Rest API
SAAS INtegration (Airtable)
Gsheet
Postgres
Mongo
S3
Mysql

Got issue on gsheet (which is an issue related to local) {"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}

Rest worked fine.
