### ISSUE TITLE
[Feature]: Notification Email Support for GAC

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#19462]
**[Notion Page](https://www.notion.so/appsmith/Notification-Emails-34ca2e26521d401fb5e2a3770dec2778)**

We will send notification emails when a user is invited through GAC along with support for workspace and app-level invites.

The welcome email will be discontinued for self-hosted instances.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7r9ho)

**Comment by infinitetrooper** [comment]
New Email Templates Attached below
[EmailsNew.zip](https://github.com/appsmithorg/appsmith/files/11219381/EmailsNew.zip)

**Comment by abhiappsmith** [comment]
MOM between me and Akhil on [Issue-19462](https://github.com/appsmithorg/appsmith/issues/19462)
1. Miro board link: https://www.notion.so/appsmith/Notification-Emails-34ca2e26521d401fb5e2a3770dec2778#9260ee57d7eb45948efd556c00970181
2. Invite another user has total 5 workflows.
3. New User(Yes) then Workspace invite -> New Trigger needed
4. New User(Yes) then AppShare invite -> New Trigger needed
5. New User(Yes) then GAC invite -> New Trigger needed
6. New User(No) then Workspace invite -> Trigger existed. Update required
7. New User(No) then AppShare invite -> New Trigger needed
8. Reset password HTML update required.
