### ISSUE TITLE
[Bug]: Logic for ascending sort order on table column for number type dataset is incorrect

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Logic for ascending sort order on table column for number type dataset is incorrect

### Steps To Reproduce

1. Go to sample app attached and sort the order or the first column
2. Observe that sorting happens based on the first digit and so it goes like, 1, 10, 11, 12.....2, 21, 22,....3, 31 and so on. Not 1, 2, ,3... and so on

### Public Sample App

https://app.appsmith.com/applications/63b3ecd95b7acd601d97d319/pages/63b3ecd95b7acd601d97d339?pod=FE%20Coders%20Pod

### Issue video log

https://www.loom.com/share/e214a65819784e189937fd0c7dd46ea5

### Version

Cloud

**Comment by somangshu** [comment]
Affects end user directly, To a point sorting becomes useless. Setting as high.

**Comment by vsvamsi1** [comment]
Hi its seems to be performing a lexicographical sort on the id column value. Can you please change the column type from text to number, then it should sort the rows correctly.![Screenshot 2023-01-05 at 3.34.29 PM.png](https://images.zenhubusercontent.com/63aacee5532b0364c531f322/0ec6b14a-3c5e-4ca8-9b65-7c0578529970)
