### ISSUE TITLE
[Feature]: allow signup with form login disabled

### ISSUE THREAD

**Issue by skoef** [appsmithorg/appsmith#19478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have my self-hosted instance of appsmith connected to Google OAuth. I only want my users to use their Google accounts. For new users to signup, they need to click "sign up" on the bottom of the login page and then click "continue with google". Then they can use the "continue with google" button on the login page afterwards.

I disabled the login form, since all my users will use the "continue with google" button anyway. This implies however that the signup button on the bottom of the screen is removed as well: when I enabled form signup but disabled form login, it was gone. So no way for my users to sign up when I disable the form login that won't work anyway.

Is this intended behaviour or could this be improved.

### Why should this be worked on?

I think more people use OAuth only and would like to be able to disable the form login because of it. I think it lowers a possible attack-vector and I certainly think the UX is improved when they're not offered a form login they should not use anyway.

**Comment by Nikhil-Nandagopal** [comment]
@skoef if they login with google, it will automatically sign them up if it's their first time so there is no need of the signup button if the form login is disabled
