### ISSUE TITLE
[Bug] Improve messaging when server is not running

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1947]
## Description

When the Appsmith server is not running, the toast message shown to the user on the frontend is `n is not defined`. This is a bad experience because the user doesn't know what is happening and what to expect from the application. 

This is also blocking our AWS AMI Marketplace approval because the reviewers think that the application has not booted correctly.

Instead of a cryptic error message like this, is it possible to show a more informative message saying: 

_The Appsmith server is not responding right now. If you just setup Appsmith, please try refreshing this page after some time._

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Start the wildcard-nginx docker image with a non-running Java server endpoint (eg. http://localhost:8080)
2. Open the URL dev.appsmith.com
4. See error `n is undefined`

### Important Details
 - Version: All
 - OS: All
 - Browser: All

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @hetunandu can we close this?

**Comment by hetunandu** [comment]
Current implementation in the attached PR has the user navigating to a different /500 url. Instead we want the user to stay on the same url as they landed on when they saw the error. Once this change is implemented, we can close this
