### ISSUE TITLE
[Bug]: perf regression after form keyboard accessibility enhancement 

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#19489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the merge of Widget accessibility PR, the performance results showed a drop in the action editing post title. This started happening after widget accessibility PR got merged

### Steps To Reproduce

...

### Version

Latest1.8.16

**Comment by somangshu** [comment]
@jsartisan is this specific to input widget?
