### ISSUE TITLE
[Bug]: RBAC code leak on CE where an intermittent error is displayed for user not having permissions to modify page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Intermittently RBAC code leak into CE cloud version where an error is displayed for user not having permission to create a page. Even though the page is created successfully, there's an error logged on toast and console.

App save state ends up in an error state at this point.

### Steps To Reproduce

1. Try to create a new page and on a rare occasion you'll see a toast with the following error
![image](https://user-images.githubusercontent.com/79509062/210519870-06dd0335-dbc0-44e7-8665-5710c305adbc.png)
2. API call details:
![image](https://user-images.githubusercontent.com/79509062/210520125-c61d1d0c-b9fd-466c-be00-c6941859101d.png)
![image](https://user-images.githubusercontent.com/79509062/210520085-5c291f8f-3387-46b6-bcee-f33455b8e045.png)

### Version

Cloud

**Comment by ankitakinger** [comment]
@ramsaptami could you share the exact steps to reproduce this? Also, where are you checking this? Release cloud?

**Comment by ramsaptami** [comment]
Unsure on repro steps cause I've seen it happen once and Raksha's seen it happen intermittently
Conditions where I saw it happen:
- Used an existing app that's git connected (unsure if git connection is related)
- Tried to add a blank page from `+` icon at pages

**Comment by infinitetrooper** [comment]
@RakshaKShetty - Are we able to reproduce this?

**Comment by infinitetrooper** [comment]
Closing this as it appears stale, please reopen if you can reproduce it.
