### ISSUE TITLE
[Bug]: Navigate To event fails when directed to a Page created by Generate Page With Data

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#19491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I assign an on click or on change event of Navigate to - to a Page - which was created by Generate Page With Data, the event leads to a Site cant be reached error page.

### Steps To Reproduce

1. Create a Page using the option Generate Page With Data [I used PostGreSQL db generated with the Public.yelp_users table]
2. Create another blank page and add any widget, say Switch widget
3. Now to this widget's Events onChange action - set it as Navigate To - Page Name - and choose the Public.yelp_users page created in step 1, set Target as Same window, leave the Query Params field as is. 
4. Toggle the switch widget. Note that this leads user to a site cant be reached error page.
Expected behavior - it should lead user to the page selected. 
Note: If we choose a regular page instead of the page created through the Generate Page with Data option, it works fine

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/tGJsB0io19iVHHXK

### Version

Production

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/269202a4-bbfc-4187-bee5-ff1846056cf8

not reproducible anymore, perhaps got fixed with another issue.
