### ISSUE TITLE
[Bug]: Looping on welcome page

### ISSUE THREAD

**Issue by MrSquaare** [appsmithorg/appsmith#19492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm stucked on the Welcome page

### Steps To Reproduce

1. Deploy Appsmith with Docker Compose / Docker Run
2. Go on http://localhost
3. Click on "Get started"
4. Fill the form
5. Continue
6. Click on "Make your first app"
7. Redirected to Welcome page

### Version

1.8.15

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6zaj0)

**Comment by akash-codemonk** [comment]
Unable to repro. @MrSquaare Could you help by posting a screen-recording?

**Comment by MrSquaare** [comment]
> Unable to repro. @MrSquaare Could you help by posting a screen-recording?

Hello @akash-codemonk ,
I've managed to reproduce it by specifying an invalid TDL for the email
Example: john@doe.doe (if I use `.com` as TDL, It will work as expected)

**Comment by akash-codemonk** [comment]
Removing critical tag and marking it as low. Frontend could handle this error better for improved UX similar to how it is handled on the signup screen.

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk could we fix this issue?

**Comment by rohan-arthur** [comment]
tested signup with a bunch of TLDs from [here](https://www.godaddy.com/en-in/domains/gtld-domain-names), it worked ok with all the valid ones. For the invalid TLDs, we now show an error `Please enter a valid parameter email.`
