### ISSUE TITLE
[Feature]: public jsobject that all page can invoke

### ISSUE THREAD

**Issue by wengad82** [appsmithorg/appsmith#19502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

appsmith can support a public jsobject,which all pages can invoke,it 's more power

### Why should this be worked on?

pages may have some same business ,such a filter project list,emp list ,etc.  a public jsobject can convenience

**Comment by Nikhil-Nandagopal** [comment]
Hello, we're working on this here #1911 please comment to upvote it! We'd also love to hear about your use case
