### ISSUE TITLE
[Bug]: cannot see workspaces when I fork a template

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#19500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I find a template the I like on the website and try to fork it, I cannot see my workspaces.
There is a workaround - I need to expand the workspaces dropdown twice in order to see the values.

https://user-images.githubusercontent.com/94514895/210748113-4b162eb4-0991-464b-9474-4d22feacf3ab.mov

### Steps To Reproduce

see in the attached video or follow these steps
1. go to https://www.appsmith.com/template/slackbot
2. click `Use this template`
3. expand the dropdown `Select Workspace`
--> the dropdown is empty
4. click somewhere else in the modal and expand the dropdown again
--> this time it works, I can see my workspaces

I think this should be at least a `medium` impact bug because although there is an easy workaround, a new user (explorer or trial) may not be aware of this workaround and me get confused/frustrated and hence in danger of bouncing.

### Version

Cloud

**Comment by ginilpg** [comment]
@rohan-arthur I'm unable to reproduce this. Is this reproducible for you?

**Comment by rohan-arthur** [comment]
@ginilpg you're right this is working now, thanks! I'll close the issue.
