### ISSUE TITLE
[Task]: Create a tag component variants

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19535]

**Comment by vasanthappsmith** [comment]
@shadabbuchh @Sripriya93 Here is the link to the Tag component with new colours. [Zeplin](zpl://components?pid=64c9171c858545222adefadd&cseid=6

<img width="1474" alt="Screenshot 2023-08-02 at 3 50 02 PM" src="https://github.com/appsmithorg/appsmith/assets/92305123/d76877aa-9f5a-4c54-a798-51988d0f673c">
4ca2970e4eed5246675fffd).
