### ISSUE TITLE
[Bug]: Email addresses containing non-latin characters like ö are not treated correctly

### ISSUE THREAD

**Issue by Gaibhne** [appsmithorg/appsmith#19559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I put an email address in a Text that contains an ö (for example), only the part after the special character is turned into an email link, like so:

mark.jö[rg@gmail.com](mailto:rg@gmail.com)

The link target is similarly mangled.

### Steps To Reproduce

Make a Text element that contains an email address containing the letter ö.

### Version

Appsmith Community v1.9.2

**Comment by rohan-arthur** [comment]
Today, appsmith doesn't render email addresses as links so this issue is not valid anymore
![Screenshot 2024-08-27 at 15 24 29](https://github.com/user-attachments/assets/d56f6d41-1f2d-4a29-8158-cc587c7b2de5)
