### ISSUE TITLE
[Feature]-[32000]:Copy fix url --> URL

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#19550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For example under REST API Pagination, we show the pagination parameters as `Next url` and `Previous url`. This should be changed to `Next URL” and “Previous URL”? 
all instances of `url` should be changed to `URL` in query and datasource forms

### Why should this be worked on?

`URL` is an acronym and as such all acronyms should be presented as uppercase characters to conform with widely accepted standard and improve readability.

**Comment by rohan-arthur** [comment]
1. This affects everyone, so the reach is max.
2. I have estimated the effort to be low because in my (probably naive) imagination, this should be an easy find+replace thing.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 16000 |
| Effort (months)  | 0.25 |

**Comment by RitikRG** [comment]
Hey guys!
I am willing to work on this issue if you allow me to, but I am a newbie so I might ask for help a few times but once I completely understood the task I will complete it for sure
So if you guys feel it's okay, allow me to work on the issue

**Comment by karuppiah7890** [comment]
I have raised a PR for this. Whom can I tag to review it?

**Comment by Lovakush** [comment]
This issue is still open ? @rohan-arthur

**Comment by rohan-arthur** [comment]
@Lovakush there's already a PR to fix this, it's currently in build
