### ISSUE TITLE
[Task]: Refactor to have a single action to update the selected widgets state and collate business logic

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#19570]

**Comment by Richarex** [comment]
- [ ] Modal widget property pane is still displayed on the canvas when the user clicks outside the modal. Please refer the attached video:- https://jIju8JbmWA.vmaker.com/record/sZpXijZ47Ds34SUB
- [ ]  Error is displayed on the canvas whenever the user switches between pages. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/1mP5si09TY6HhpIW
- [ ]  STATS BOX container widget is selected when the user is selecting the Multiple widgets inside the STATS box widget. Please refer to the attached video:- https://jiju8jbmwa.vmaker.com/record/KI6dMVnVJzYf0FP5
