### ISSUE TITLE
[Bug]: Distance between the right side signifier in Auto layout is more comparing to the left

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19596]
https://www.notion.so/appsmith/Mobile-Responsive-Bugs-4931b006dc1242f5a1a6e8ef5dce36f1?p=b1bc2da98ace4a049aee7cd56f2fcb6d&pm=s

**Comment by Sripriya93** [comment]
Distance between both side signifiers are equal now, moving to done.
