### ISSUE TITLE
[Bug]: Copying widget from one container and pasting to another container makes the positions of the widget in reverse order

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19592]
Details here: https://www.notion.so/appsmith/Mobile-Responsive-Bugs-4931b006dc1242f5a1a6e8ef5dce36f1?p=35238cb3f5b748e1b2ffc13043e9efd1&pm=s

**Comment by prsidhu** [comment]
Copied widgets are being stored as a stringified array. After JSON.parse the copied data, the order of the copied widgets is lost. This order is important for auto layout. How to solve for this problem? is it reasonable to save another string array of widget ids?

@riodeuno @marks0351 

![Image](https://user-images.githubusercontent.com/5424788/212210369-afb4402c-11dd-485d-b633-cabac6e9b237.png)
![Image](https://user-images.githubusercontent.com/5424788/212210370-71097e20-3a2a-4b0f-b786-816434f997b5.png)

**Comment by Sripriya93** [comment]
We are still able to see the issue here.

https://user-images.githubusercontent.com/104895602/220586881-5b161e89-3af5-4586-8e6f-e6b0626e5c78.mp4

**Comment by rahulramesha** [comment]
@Sripriya93 the latest fixes are being pushed into a different PR https://github.com/appsmithorg/appsmith/pull/20836, looks like this is being tested in the mobile/v1/main, which does not have the changes

**Comment by Sripriya93** [comment]
@rahulramesha Got it, Will check it in the above mentioned PR.

**Comment by Sripriya93** [comment]
Working as expected in the #20836 given PR. Moving to done.
