### ISSUE TITLE
[Bug]: Canvas resize indicators doesn’t work correctly when moved a little fast

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19606]
https://www.loom.com/share/9a487adab7764796b7a4c43705089e03

**Comment by marks0351** [comment]
@kamakshibhat-appsmith @Sripriya93 can we test this once, the re-sizer has gone through some iterations, i am not able to reproduce this now.

**Comment by Sripriya93** [comment]
@marks0351 Im still able to reproduce this but its different for different pages. 

https://user-images.githubusercontent.com/104895602/216923255-969e76eb-137d-414c-b3a4-bb1b5100d1a8.mp4

**Comment by Sripriya93** [comment]
Canvas resize is working fine, QA done. @marks0351
