### ISSUE TITLE
[Bug]: The auto height with limits placement indicators are not respecting the widgets placement

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19608]
https://www.loom.com/share/3a2b98b72f8c43ff9b7667f424c1b0b9

**Comment by rohitagarwal88** [comment]
we will be removing dynamic height properties for mobile responsiveness.
https://theappsmith.slack.com/archives/C040E1VG8P2/p1671535006461199

**Comment by marks0351** [comment]
closing this bug since its not relevant for auto layout editor.
cc: @rohitagarwal88 @Sripriya93 @kamakshibhat-appsmith
