### ISSUE TITLE
[Bug]: Flex does not work when we change layouts.

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19609]
https://www.notion.so/appsmith/Flex-does-not-work-when-we-change-layouts-50a4c4dabb1e4225849e828c6d48e5ee#f1f94dc43bb945e788088b5ae8aeaef2

**Comment by prsidhu** [comment]
Cannot reproduce this issue.

**Comment by Sripriya93** [comment]
In Auto layout we are not seeing other layouts anymore, while changing the layout by dragging the arrows in either side, we are able to see input widgets placed side by side is changed to be placed one below other, moving to done.
