### ISSUE TITLE
[Bug]: Canvas Size on Windows

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19611]
- On windows the canvas does not take full height of the viewport.
- Dragging and dropping container widgets like Statbox do not take the whole height assigned to them in the widget config.

https://user-images.githubusercontent.com/890915/211357724-b751c73d-d507-454e-a5b4-bf478c8d3fb3.webm

**Comment by Sripriya93** [comment]
While drag and drop widgets are displaying the whole height. Moving to done
