### ISSUE TITLE
[Bug]: Issue with dropping fill widgets on the fixed positioning mode

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19617]

**Comment by rohitagarwal88** [comment]
Low priority as  we have decided not to allow hybrid mode

**Comment by marks0351** [comment]
@rohitagarwal88 lets just close this issue since its not relevant. we can reopen this as a bug in conversion if this happens in the future.

**Comment by Sripriya93** [comment]
Moving to done based on the conversation above.
