### ISSUE TITLE
[Bug]: Chart widget breaks in Deploy mode

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19619]
Discussion: https://www.notion.so/appsmith/Mobile-Responsive-Bugs-4931b006dc1242f5a1a6e8ef5dce36f1?p=101a86a0498548b5af007ee7eb94a6ba&pm=s

**Comment by yaldram** [comment]
Cannot reproduce this issue anymore on the latest deploy preview - https://ce-20836.dp.appsmith.com/
