### ISSUE TITLE
[Bug]: If a text widget is empty, it vanishes from the canvas when mobile viewport is enabled

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19620]
https://www.loom.com/share/51ee3be2381e4bb3abdca441e4c0b5dd

[Discussion](https://www.notion.so/appsmith/Mobile-Responsive-Bugs-4931b006dc1242f5a1a6e8ef5dce36f1?p=ad6f546b13f24eb38bc5525a2cf011ae&pm=s)

**Comment by shadabbuchh** [comment]
This issue is resolved.
