### ISSUE TITLE
[Bug]: When 3 widgets are placed in the same wrapper, the extreme right widget does not take up the whole canvas space

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19628]
https://www.loom.com/share/8f0d58303eb94fb88a41ba77850e6984

**Comment by shadabbuchh** [comment]
@prsidhu Now the widget exceeds the right boundary of the canvas. 
**Note:** It does not matter from where you start dropping the widgets. Even if you start dropping the widgets from the right, after you have dropped the extreme left widget the widget moves out of the canvas boundary.

**Comment by prsidhu** [comment]
@shadabbuchh Can you share a loom video for this?

**Comment by shadabbuchh** [comment]
> @shadabbuchh Can you share a loom video for this?

https://www.loom.com/share/14bd9e08435f4cab8e4878ee0b41a951

**Comment by prsidhu** [comment]
@shadabbuchh This is a different issue. Statbox is a hug widget. Let's keep it open. It will be fixed next week.

**Comment by prsidhu** [comment]
Statbox widget can be resized to fix this problem. Excessive widgets in a single layer are allowed to overflow. That's the expected behaviour.
