### ISSUE TITLE
[Bug]: Forked Templates do not work in mobile responsive DP

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19623]

**Comment by prsidhu** [comment]
Steps to reproduce:
1. Import a template.
2. Containers in the template should render properly and should not overlap.

**Comment by Sripriya93** [comment]
When we change the layout from Fixed to Auto, and again to fixed, for each repeat we are able to see the container overlapping increases

https://user-images.githubusercontent.com/104895602/220603732-a91c890f-c880-4f1f-b1ea-541ef3b092e1.mp4

**Comment by prsidhu** [comment]
@Sripriya93 The overlapping issue is being tracked at #20234. If the forked templates are working well in Fixed mode. Let's close this one then.

**Comment by rahulbarwal** [comment]
Closing this as per above comment.
