### ISSUE TITLE
[Bug]: Issue in the latest D&D experience

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19626]
https://www.loom.com/share/eb6f04be9f544f78bf9a0cccab2e2669

**Comment by Sripriya93** [comment]
@prsidhu , please check the below loom, i feel its still the same as given above, please confirm.

https://user-images.githubusercontent.com/104895602/216609281-fb07645e-0d6c-4038-a40a-143e41149fa8.mp4

**Comment by prsidhu** [comment]
@Sripriya93 This is the expected behaviour right now.

**Comment by Sripriya93** [comment]
Moving to done based on the above comment.
