### ISSUE TITLE
[Bug]: Child widgets inside a layer are overlapping with each other when width is changed

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19629]
https://www.loom.com/share/12cba2db687441e181d4ecafef727d2f

**Comment by marks0351** [comment]
@kamakshibhat-appsmith we have removed resizing of 1D widgets and also have enhanced resizing, I am unable to reproduce this bug right now. pls check.

**Comment by kamakshibhat-appsmith** [comment]
unable to replicate , moving to Done @marks0351
