### ISSUE TITLE
[Bug]: Unable to show the first item as image in the container in the mobile view port(probably because it is not responsive)

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19635]
https://www.loom.com/share/0ff093bf68ef4dc99eb2a60141647c36

**Comment by rohitagarwal88** [comment]
@aswathkk  comment : Observations from DOM:
1. The height of `.t--widget-imagewidget` becomes “auto” in the mobile viewport is the issue

**Comment by Sripriya93** [comment]
Working as expected. Moving to done.
