### ISSUE TITLE
[Bug]: Not able to drop widgets inside a container in special cases. (Not able to see horizontal signifiers)

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19631]
https://www.loom.com/share/7e7d8a63b41d43a7919c336d2c48191c

**Comment by shadabbuchh** [comment]
@prsidhu I am still able to reproduce this issue:
https://www.loom.com/share/06793a0b135c4590bc88523b9d56dd86

**Comment by shadabbuchh** [comment]
This issue is resolved.
