### ISSUE TITLE
[Bug]: Issue with Icon Button Padding when dropped on the extreme edges

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19642]
https://www.loom.com/share/0546beb9551946c7a498aa2456a8b7a9

[Discussion](https://www.notion.so/appsmith/Mobile-Responsive-Bugs-4931b006dc1242f5a1a6e8ef5dce36f1?p=cd7c525a6ee54bd2bc1a5ea0c7cd6ed3&pm=s)

**Comment by aswathkk** [comment]
This go fixed in https://github.com/appsmithorg/appsmith/pull/19747
