### ISSUE TITLE
[Bug]: Can we add default selection when user tries t deselect the value in Scanner Layout in code scanner widget

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#19658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can we add default selection when user tries t deselect the value in Scanner Layout in code scanner widget

### Steps To Reproduce

1. DnD a code scanner widget
2. try to click on the selected value in scanner layoyt

There shud not be any state where there is nothing selected in the scanner layout

### Issue video log

https://www.loom.com/share/26ec927814a94f8ea74a5fd2a921aed0

### Version

Cloud

**Comment by somangshu** [comment]
This was supposedly fixed in #18533 

please checkout [this thread](https://theappsmith.slack.com/archives/C025SE88KNE/p1671186601347789) for more context

cc @kamakshibhat-appsmith @aswathkk
