### ISSUE TITLE
[Bug]: In edit mode, Multiple issues are coming w.r.t Modal UI 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#19657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 issues with modal in EDIT MODE:
1. If my widget on which I have configured Modal is below the fold , then on click the screen is moving to the top and then displaying modal
2. with modal, the entire is NOT getting blocked like it used to work before and also the scroll canvas is appearing which is disturbing the UI 

### Steps To Reproduce

1. open modal widget in edit mode

### Issue video log

https://www.loom.com/share/c51d0f433ca444f5811bb511ef9bb560
### Version

release

**Comment by kamakshibhat-appsmith** [comment]
Hey @somangshu Can we get this assigned to someone from the team? Seems to be pretty bad experience with modal

**Comment by somangshu** [comment]
@hetunandu @rahulramesha is this related to context switching? I see when the modal is opened in the edit mode, some identifier is added to the URL, that is what probably causes the issue. Can you shed some light here. 

There are no changes directly made to modal otherwise

**Comment by somangshu** [comment]
Setting this to medium as this accounts to poor UX and does not block users in any ways

**Comment by rahulramesha** [comment]
To Add more context to the Issue, From git Bisect it seems to be introduced from the Multi pane changes to the layout in https://github.com/appsmithorg/appsmith/pull/19261. This could most likely be the result of DOM structure changes as part of the project.

**Comment by kamakshibhat-appsmith** [comment]
@hetunandu Are we prioritising this issue ? I understand this is not a blocker however its creating confusion if we initiate the modal action from below the fold widgets giving an illusion that modal is not working. [LOOM](https://www.loom.com/share/6f8dad0e19a0478184fedbf5aed3cb54)
