### ISSUE TITLE
[Bug]: Double scroll appears on the share modal

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two scrolls appear on the share modal as seen in the video

### Steps To Reproduce

1. Open a workspace with at least 5-8 users so you can scroll on the share modal as seen in the video
2. Observe the double scroll 

### Issue video log

https://www.loom.com/share/a3a0fb53106a49339e92f625199f1cd2

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/user-attachments/assets/ba754a4b-4a94-4d70-9c30-055715df097e
