### ISSUE TITLE
[Bug]: Use a component from the Design System instead of creating a new component for the "App Positioning Type" selection

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19686]
Currently for the `App Positioning Type` selection we are using a component that is not from our design system. In order to keep it consistent with the design system we should utilise `Rectangular Switch` or `Button Group` for it.

![Image](https://user-images.githubusercontent.com/39921438/211709020-0a788774-8720-4175-afe5-3eb93975e6b3.png)

**Comment by aswathkk** [comment]
Closing this since we removed the usage of App positioning Type
