### ISSUE TITLE
[Bug]: Upload images to supabase

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#19684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The current problem with this is that it is not possible to load an image as such to a database, for example in this case that we are going to expose

I use supabase as a bucket and I load the image giving it its type as images and passing the data when uploading it to supabase this image cannot be opened or downloaded since it is broken, however if I upload it in base64 format I can view the image from Appsmith, but I can't download the image directly as this is a base64 string

I also did the test by uploading the image to PostgreSQL and I still can't see the image.

Furthermore, I attach a screenshot where you can see this behavior a little better:
![image](https://user-images.githubusercontent.com/114161539/211650469-2ad68307-fbc2-46ed-81b4-4e1bddc15183.png)

### Steps To Reproduce

I created this [application](https://app.appsmith.com/app/supabase/page1-638e4bf83b14013e8f50bd1f) to make it easier for you.

`Note: the supabase images are static, but were loaded from Appsmith.`

1. Create your database in Postgres use this container and follow this guide to build the Postgres database in a simple way [guide.](https://github.com/felix-appsmith/appsmith-quick-datasources#-postgresql)
2. Connect to the database, follow the same guide to do this.
3. Execute the query called `CreateTable.`
4 Load an image in the `filepicker` and press the submit button.

### Public Sample App

https://app.appsmith.com/app/supabase/page1-638e4bf83b14013e8f50bd1f

### Version

Appsmith v1.8.16-SNAPSHOT

**Comment by felix-appsmith** [comment]
For this problem, there is currently a workaround available. It involves using the Supabase library in Appsmith instead of connecting via OAuth and handling file uploads directly from JavaScript with code like this:

```js
export default {

	
	    uploadFile : async ()=>{
        let supabaseClient = supabase.createClient(appsmith.store.docApprovalAPIURL, appsmith.store.docApprovalAPIKey);

        var binaryString = FilePicker1.files[0].data;

        function binaryToArrayBuffer(binary) {
            var binaryString = binary;
            var bytes = new Uint8Array(binaryString.length);
            for (var i = 0; i < binaryString.length; i++) {
                bytes[i] = binaryString.charCodeAt(i);
            }
            return bytes.buffer;
        }

        const avatarFile = binaryToArrayBuffer(binaryString);
        const { data, error } = await supabaseClient
        .storage
        .from('bucket_documentApproval')
        .upload(FilePicker1.files[0].name, avatarFile)
        },
	
	
	keys() {
		storeValue('docApprovalAPIURL', 'https://mritzxpfuqsbselcjefc.supabase.co/storage/v1/object/')
		storeValue('docApprovalAPIKey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yaXR6eHBmdXFzYnNlbGNqZWZjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3MDM0NTM2OCwiZXhwIjoxOTg1OTIxMzY4fQ.XKtCf3M6jPjEgy9zIZqLMnfL94nSKeiMJFXDSeBJOhA')
	}
};

```


I notice that here they handle binary data in an ArrayBuffer. Would it be possible to add this functionality natively to our file picker to avoid the user having to write additional code?

This workarround was suggested by a user in this thread: https://app.frontapp.com/open/cnv_119oihfw?key=KWuOAoi16F7OwDUl8Bcoe7Xy27BYuc1w

**Comment by tegsramdhan** [comment]
Glad to help, Im BangTegs from discord. But it seem Supabase still set all the file as plain text. But its worked for now.
