### ISSUE TITLE
[Bug] User is unable to clear Initial location after converting to JS 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1968]
Steps to reproduce:
1) Add a MAP 
2) Now Click on the Property pane
3) Add an Initial Location
4) Click on JS 
5) Now navigate back to regular expression
6) Try to clear the initial location

Observation:
It is observed that user is unable to delete the Initial location. The user has to navigate back to JS mode to delete the initial location

Expectation:
User should be able to delete the initial location and add new location 

Video link 
https://www.loom.com/share/0536d037ba6745f5bd2ce5b5bc95501b

**Comment by ofpiyush** [comment]
Hi @prapullac

I just tried this on release, it seems to work. There's a test case that checks for this as well.

Can you make sure that you have the latest changes?

**Comment by prapullac** [comment]
Closing the issue as it works as expected
