### ISSUE TITLE
[Bug]: Unable to connect to Amazon Congito IdP

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#19692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cognito IdP integration is failing for a user. The issue seems to be related to scopes.

### Steps To Reproduce

Follow the steps in the SSO doc for Amazon Cognito.

### Version

v1.9.2

**Comment by infinitetrooper** [comment]
I'm reopening this as there's no QA validation for the fixes we've done. @RakshaKShetty  will update the status once QA is verified.

The user who reported this moved to AD but, we don't know yet if this is working for Cognito.

Slack Thread here - https://theappsmith.slack.com/archives/CPQNLFHTN/p1673362611104259

**Comment by infinitetrooper** [comment]
The issue was reported by webmethod.com - https://theappsmith.slack.com/archives/C02K2MZERSL/p1675415041117339
