### ISSUE TITLE
[Task]: Auto Layout Editor DnD

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#19715]
Objectives
-
- Should show alignement markers for left, center and right

---

- Should show alignment markers for new cell

---

- Should have smooth transitions when moving between alignment markers

---

- Should not trigger reflow(built for fixed canvas)

---

- Should render markers on the DraggingCanvas(stretch)

---

- Should not create glitches and widget jumping

---

- Post Drop the container must increase its height to accommodate all widgets

**Comment by Sripriya93** [comment]
When we drag and drop Modal widget we are seeing its taking up space invisibly until we drop any other widget, it affects the alignment of the markers

https://user-images.githubusercontent.com/104895602/216283228-000fc887-2677-4010-952c-1bd5c95a3870.mp4
