### ISSUE TITLE
[Task]: Restore point for Auto Layout Conversion BE

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#19720]
Terminology:
fixed apps - present day app where widgets are absolutely positioned
auto layout apps - apps that hold widgets in order

As part of Auto layout initiatives, we will be building a way to convert out present day fixed apps to auto layout apps. This conversion will be lossy because of the nature of auto layout.
So in order to make up for that, we will be providing a way to restore to the last point in time where the app was in fixed mode.

Miro Link: https://miro.com/app/board/uXjVPz_eBXA=/?share_link_id=986081276045

Requirements of the BE:

- an api to store app data as a snapshot.
- an api to use the snapshot to restore the app.
- this information should hold even if the app is deployed.
- an api to update layouts of all pages at once during app conversion.
- add snapshot information as part of application view api.
- all apis should with git sync without any issues.

**Comment by marks0351** [comment]
@momcilo-appsmith @rahulramesha the snapshot should only be of the layout(dsl) or all entities like jsobjects, queries, datasources as well?
pls confirm.

**Comment by momcilo-appsmith** [comment]
Yes, I confirm we will only revert the layout.
