### ISSUE TITLE
[Bug]: Weird formatting for text when accessing page settings in edit mode

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#19730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I access the page settings, the text displayed is weird. Please check screenshot below. 

<img width="528" alt="Screenshot 2023-01-11 at 2 55 22 PM" src="https://user-images.githubusercontent.com/458946/211769184-4327ffa2-488a-412c-ace6-e1aacd53ac93.png">

### Steps To Reproduce

1. Open any application in edit mode. 
2. Go to Application settings on the top left. 
3. Click on any page in the right pane. See that the text shown has weird spacing/formatting.

### Version

Cloud/Self-hosted

**Comment by hetunandu** [comment]
This is not happening on any browser anymore
