### ISSUE TITLE
[Bug]: Async code evaluates in sync context after .then

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#19733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Slack discussion: https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1673273779118359

![sync fields promise error](https://user-images.githubusercontent.com/23132741/211795146-bfc4369e-5e78-4397-8fe0-add5631d53d6.png)

### Steps To Reproduce

1. Install supabase library.
2. Copy below JSObject code.
```
export default {
	supabaseUrl: 'https://yourSubHost.supabase.co',
	supabaseKey: "YOUR_KEY", 
	s: supabase.createClient(this.supabaseUrl, this.supabaseKey),
	signUp: async () => {
		this.s.auth.signUp({ email: emailInput.inputText, password: passwordInput.inputText}).then((response) => {
			if(response.error){
				showAlert(String(response.error.message), "error")
				console.log("$$$-IS_ASYNC",self.IS_ASYNC);
			} else{
				storeValue("supabase_token", response)
				showAlert("Successfully signed up", "success")
			}
		}).catch((err) => {
			showAlert(String(err), "error");
		})

	}
}
```
3. Run the Signup function and notice an error in the console.

### Public Sample App

https://app.appsmith.com/app/playground-custom-js-libs/supabase-login-63a188f2749a014ec6e580fc

### Version

1.9.3

**Comment by bharath31** [comment]
@Rishabh-Rathod @arunvjn could you share an RCA?
