### ISSUE TITLE
[Bug]: Getting error on fetching appsmith's mock-api 

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#19745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Getting Internal server error on using mock-api of appsmith i.e https://mock-api.appsmith.com/users.
This issue can be seen on Production, Release and all DPs

![image](https://user-images.githubusercontent.com/95341241/211986870-53f6787e-286c-4d47-adad-d1b57facc89f.png)

### Steps To Reproduce

1. Create new API
2. Use mock api i.e https://mock-api.appsmith.com/users
3. Run the query and observe the error

### Version

Cloud/Production

**Comment by btsgh** [comment]
Note: Other APIs are working fine.

**Comment by sumitsum** [comment]
Closing it since it is not reproducible any more.
