### ISSUE TITLE
[Bug]: Git branch continues to show change icon even after discarding changes multiple times

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Git branch continues to show change log asterisks and commit modal shows commit/discard options without any change log displayed even after discarding changes multiple times. Unsure if this is caused by custom library installed or a core git issue.

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/cloak-of-invisibility/page1-6384f8db8dd69b039cb13319/edit?branch=branch1) location and try to discard changes made on child branch

### Public Sample App

https://release.app.appsmith.com/app/cloak-of-invisibility/page1-6384f8db8dd69b039cb13319/edit?branch=branch1

### Issue video log

https://www.loom.com/share/22810101b51f49409e3d8fabce85219c

### Version

Cloud

**Comment by AnaghHegde** [comment]
@ramsaptami Can you share the response from the console for the status API and discard API?

**Comment by ramsaptami** [comment]
@arunvjn change log does not seem to appear even on your PR 
@AnaghHegde: file https://github.com/ramsaptami/reimagined-octo-succotash/pull/1/files
Like I'd mentioned earlier, git issues that were harder to reproduce are now more easily done post custom libs change. I can't currently repro this issue all the time post-JS libs changes got merged but can repro it more often than on prod

**Comment by AnaghHegde** [comment]
The change log shows the customJs lib changes. I just tried with one of the apps i had on release env and i am able to reproduce the issue. @sumitsum Can you take a look at this?
