### ISSUE TITLE
[Bug]: Add Row button from the table disappears if all the items are removed from the header.

### ISSUE THREAD

**Issue by zeeshanahmed-nagarro-frontend** [appsmithorg/appsmith#19762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I hide all other controls like pagination, search, etc from the table, the ** + Add Row button** also disappears from the header. 

### Steps To Reproduce

1. Add a table widget.
2. Enable the "Add Row Button"
3. Disable all controls, such as filters, search box, pagination, download, etc. from the table so that only the table columns are left 
4. The moment all other controls disappear along with the **Add Row Button**

### Version

Cloud hosted

**Comment by somangshu** [comment]
This is happening since all other header options are hidden, the header bar also hides, this was not thought through while building the `add new row` feature. 
We need to include this check while we decide is the header needs to be hidden

**Comment by zeeshanahmed-nagarro-frontend** [comment]
Yes it would be good to make the header visible only in the case if there is at least one control present, otherwise not.
