### ISSUE TITLE
[Feature]: Capture Image using a function triggered from other widgets/JS

### ISSUE THREAD

**Issue by hashsome** [appsmithorg/appsmith#19765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

My usecase is to build an employees attendance app, the workflow of the app would be such that when the employee scans their id-card using the codescanner widget, it captures the QR code and performs validation using mysql as backend db.
If the employee code is valid the app should auto capture the image of the employee (Using same camera source which was used to scan the QR / or another camera source, from some other viewing angle).
The problem I'm facing is I'm unable to figure out how to perform auto image capture as the current image capture widget only works when the user manually clicks on the widget to save the image, which then later can be extracted as a blob url / rawbinary).
This makes the process of marking the attendance somewhat complicated, as the employee first have to scan the qr code then again for image capture, they have to press the capture button on image widget) for this method , I'm currently using the storevalue option.
What I'm looking for is how can i capture the image of user using the camera widget in invisible mode, when they scan the QR (which is live in continuous scanning mode) so that it becomes easy for the employees to mark their attendance just by scanning the QR, without having to interact with the system. Can this be achieved using  custom JS code? Any help in this regard is highly appreciated.

### Why should this be worked on?

If the image widget events can be controlled dynamically by some other widget or using JS code, then one can implement various use cases where auto image capture is the requirement.
- face detection.
- Webcam record video if motion is detected.

**Comment by Nikhil-Nandagopal** [comment]
@hashsome thanks for the feature request. I'm wondering how this would work because if you automatically trigger an image capture, it's possible the phone is not positioned correctly and doesn't capture the image of the employee correctly. It seems this would likely happen a lot and need them to re-take the image

**Comment by hashsome** [comment]
> @hashsome thanks for the feature request. I'm wondering how this would work because if you automatically trigger an image capture, it's possible the phone is not positioned correctly and doesn't capture the image of the employee correctly. It seems this would likely happen a lot and need them to re-take the image

Yes, I've given a thought about that issue earlier, hence while explaining my use case I had mentioned
_Using same camera source which was used to scan the QR / or another camera source, from some other viewing angle_

i.e one camera source to scan the QRcode and other camera mounted in such a fashion that it captures employee image properly. The second camera source would be use by the Image capture widget.

Workflow
scan QR using camera source 1.( CodeScanner widget)
If employee code is valid then capture image using camera source 2. (Imagecapture Widget)

If this usecase becomes possible then we can use this workflow in our Inventory management system as well
- our requirement is to take an image of each item which gets scanned (barcode/QR) while making inward / outward into the system.
Currently the operator has to do this in 2 steps, first qr is scanned and then image is taken again manually for record keeping purpose.
If this activity can be done in a single step it'll solve many of my issues.
Thank you for your kind consideration.

**Comment by Nikhil-Nandagopal** [comment]
@hashsome just to be clear, is the 2nd camera source on a different device entirely? How do the 2 devices communicate?

**Comment by hashsome** [comment]
> @hashsome just to be clear, is the 2nd camera source on a different device entirely? How do the 2 devices communicate?

Same device, multiple video streams from respective camera sources on a single web-page.

**Comment by Nikhil-Nandagopal** [comment]
@hashsome Could you tell us a bit about the hardware setup? Is the device a computer connected to 2 external cameras? Trying to understand how can a single device have 2 separate camera sources

**Comment by hashsome** [comment]
> @hashsome Could you tell us a bit about the hardware setup? Is the device a computer connected to 2 external cameras? Trying to understand how can a single device have 2 separate camera sources

Android OS tablet.
- one camera source would be the Inbuilt front camera, which would serve as a stream for CodeScanner widget and other would be using a usb/ wireless camera for capturing the image.
The image widget should have an automated event such that when QR gets scanned and validated through CodeScanner widget, it sends a command to image widget which would capture the image via other camera stream.

**Comment by Nikhil-Nandagopal** [comment]
@hashsome thanks! This gives us a lot of clarity. 
@dilippitchika this should be simple considering our camera already supports multiple streams. Could we simple add a 
`Camera1.captureImage())` method?

**Comment by dilippitchika** [comment]
Assuming 50% trial/builder users need this in camera widget

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 152 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@bharath31 can we discuss this once, we have gotten these kind of requests before and I want to understand how to scale the framework functions better

**Comment by bharath31** [comment]
@dilippitchika sure! happy to discuss and create a task for the FE-Coders pod.

**Comment by daaliachhak17** [comment]
What is the status of this please? Is anyone working on this?

**Comment by Nikhil-Nandagopal** [comment]
@daaliachhak17 we now have a code scanner widget so I believe this requirement is no longer necessary

**Comment by daaliachhak17** [comment]
Thanks for the update!
