### ISSUE TITLE
[Feature]: More informative error in the following scenario of a JSObject

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#19763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we use the curly brackets for referencing a widget in a JSObject (when infact we can reference them directly), the errors should be more informative to the user.

### Why should this be worked on?

At present, when we use something as below in a JSObject:

const num1 = 16/{{Input1.inputText}}; 

We get a vague error like - 

<img width="1280" alt="Binding_Error" src="https://user-images.githubusercontent.com/101863839/212079735-4db5a303-f03c-4cc0-8a93-dd063795c488.png">

Actually, the widgets can be directly referenced inside a JS Object, without curly brackets. The above error is not very informative and is misleading. In Appsmith, in all the areas, widgets are referenced using curly brackets, and its quite natural that we do the same within a JSObject.

Hence, If an error which is more informative or directs the user in the right direction indicating that he need not use curly brackets inside of a JSObject, it would be helpful

**Comment by Nikhil-Nandagopal** [comment]
This is not valid. This is a javascript error and here we're using mustache inside javascript. As part of that, this error is the right one that you would see in any IDE. Mustache is only valid outside the javascript world
