### ISSUE TITLE
[Bug]: Branch switching from git pop-up does not work sometimes; UI does not respond to clicks

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Branch switching from git pop-up does not work sometimes; UI does not respond to clicks

### Steps To Reproduce

1. Have multiple branches on git and perform a range of actions like commit, discard etc..
2. Switch between branches and notice the UI not registering clicks sometimes so branch switching is stuck

### Issue video log

https://www.loom.com/share/6dbb5ab9400b47ec847b19213302a1d8?highlightComment=10498171&t=152

### Version

Cloud

**Comment by infinitetrooper** [comment]
@brayn003 fixed this to show a loading state.
