### ISSUE TITLE
[Bug]: Importing application from git fails with Argument error on the git import modal 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#19779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On importing an app from git fails with following error, when use default configuration is checked, this is reproducible with this repo as well : https://github.com/Parthvi12/testduplicate
<img width="1438" alt="Screenshot 2023-01-13 at 2 15 34 PM" src="https://user-images.githubusercontent.com/80334441/212288868-3fbdde17-8cd6-474d-86d2-5bb577530f7f.png">

### Steps To Reproduce

1. Import an app from git 
2. Observe 

### Version

deploy preview

**Comment by AnaghHegde** [comment]
@Parthvi12 Can you share the repository with me? I am unable to reproduce this issue.

**Comment by Parthvi12** [comment]
Not able to reproduce this issue, hence closing it.

**Comment by Aishwarya-U-R** [comment]
@Vijetha-Kaja - Please add your findings here to reproduce this.

**Comment by Parthvi12** [comment]
Closing issue, hence this was gitea issue where we were adding same deploy key via api call in cypress which is not supoorted in gitea hence it was failing with this error.
