### ISSUE TITLE
[Task]: Add tests to check if the Infinite loading of the execution API in edit mode doesn't happen anymore

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#19772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Add tests to check if the execution of the API doesn't go to Infinite loading in edit mode when API just has View and execute permission

**Comment by infinitetrooper** [comment]
@ankitakinger - Should this issue be closed? I see the branch merged but, don't know why this is still open.

**Comment by ankitakinger** [comment]
@infinitetrooper this is to add automated tests. Let's keep it open.
