### ISSUE TITLE
[Feature]: Image widget that allows for annotation

### ISSUE THREAD

**Issue by vanscurvy** [appsmithorg/appsmith#19782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This feature request is for there to be an interactive widget that displays an image source and allows the user to add/remove markers and annotations on top of the image.  The widget should also be able to display markers and annotations pulled from available datasets.  This functionality is similar in nature to what is possible with the map widget.

Some of the specifics:
- Positioning of annotations should be defined by x and y coordinates, and image display options should give admin sufficient control of sizing so that the relative positioning of the annotations to the image is predictable and controllable.
- Widget should allow for multiple series of annotations that use different customizable icons, or JS-derived text.  Each series of annotations have should a "Visible" property, the state of which should control visibility for that series only.
- Widget should allow for a user to delete an annotation that they previously created.
- Widget should allow for a user to select/deselect an annotation (and make use of a selectedMarker binding property).  Selected annotation should be visually identifiable on the image.
- Widget should have a binding property that includes all series of annotations, each series having a name/id and containing an ordered list of each annotation's coordinates.

Here is an example of what this widget might look like.  In this example, there are two series of annotations, one which is using a star icon and one which has an arrow and text dynamically produced from a correlated dataset.  One of the star annotations is selected, identifiable by the highlight.  

*In this example the text annotations have an arrow that is pointed in different directions.  I do not think this is necessary and would be too complex.

![seamless-vector-topographic-map-background-line-topography-map-seamless-pattern-contour-background-geographic-grid-mountain-hiking-trail-over-2FNA341](https://user-images.githubusercontent.com/48229381/212360844-e37822c9-d322-4f74-ba96-e4b18afd674a.jpg)

### Why should this be worked on?

Use cases that could benefit from this include:
- creating reports for building inspections
- marking up floor maps for construction purposes
- logging field observations on topographical maps
- review and approval of graphical content by art directors

**Comment by vanscurvy** [comment]
Fyi, this feature request originated from this Appsmith community thread.  It has some relevant comments from other members as well.
https://community.appsmith.com/t/ideas-for-leaving-markers-on-image-widget-as-if-it-were-the-map-widget/1

**Comment by Nikhil-Nandagopal** [comment]
@vanscurvy this seems related to #3362 so I;m closing this in favor of that. But we'll use all the information you provided while launching this widget!

**Comment by vanscurvy** [comment]
sounds good, thanks @Nikhil-Nandagopal !
