### ISSUE TITLE
[Bug]: Setting editable using JS does not show all properties (Table Widget column settings)

### ISSUE THREAD

**Issue by souma-ghosh** [appsmithorg/appsmith#19806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In table widget column settings when we set editable to true using JS, the properties related to editing don't show up in the property pane.

### Steps To Reproduce

1. DnD Table widget
2. Go to column settings for a text / number type column
3. Turn editable to true and observer some extra properties show up
4. Turn editable off and then turn on the js toggle and set true by typing `{{true}}`
5. Observe that the editing related properties don't show up this time

### Version

v1.9

**Comment by somangshu** [comment]
@souma-ghosh any insight on why this is happening?

**Comment by dilippitchika** [comment]
Problem : When devs use JS to set the property they can't see the dependent properties. 

The fix for this is to show all dependent properties as soon as JS is enabled for editable, should be a small change. @somangshu lmk if you need more insight, also i think @vsvamsi1 can fix this easily in a good first issue.

**Comment by somangshu** [comment]
@dilippitchika can you elaborate on
> show all dependent properties as soon as JS is enabled for editable

**Comment by vsvamsi1** [comment]
I discussed with @sbalaji1192 and he confirmed this is not an issue. We need to turn on the column editable section for the validation section to show up. Also the editable JS section will not work on its own, the column editable section needs to be checked as well. It's sort of an AND between those two properties.
`column editable checkbox AND JS editable expression`

**Comment by vsvamsi1** [comment]
I discussed with @sbalaji1192 and he confirmed this is not an issue. We need to turn on the column editable section for the validation section to show up. Also the editable JS section will not work on its own, the column editable section needs to be checked as well. It's sort of an AND between those two properties.
`column editable checkbox AND JS editable expression`

**Comment by vsvamsi1** [comment]
I discussed with @sbalaji1192 and he confirmed this is not an issue. We need to turn on the column editable section for the validation section to show up. Also the editable JS section will not work on its own, the column editable section needs to be checked as well. It's sort of an AND between those two properties.
`column editable checkbox AND JS editable expression`
