### ISSUE TITLE
[Bug]: Unresponsive page when List widget's container is copy pasted

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#19808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When list widget is dropped on the canvas and container of list widget is copied a message is shown "This widget cannot be copied" however when you paste it the widgets gets overlapped with the existing widgets. When user pastes it the second time the page breaks.
https://loom.com/share/2ac9de56bcbe4aeb8896c50bdde42897

Scenario 2:
Drop a Tab widget now drop a List widget inside tab1. Now in the entity explorer expand the tab widget and notice Canvas3, Container & Canvas4 widgets appear. Click on Canvas 5 the property pane opens up > Copy and paste it on the canvas - the page becomes unresponsive after this action. Whereas when Canvas4 is copy pasted there is nothing seen on the canvas but in the entity explorer Canvas4Copy is seen.
(https://loom.com/share/a20f146436a54227bef166c5d1ffdc8f)

As seen on Windows machine

### Steps To Reproduce

1. Drag and drop List widget
2. In entity explorer click on list widget drop down 
3. Click on Container1 > Copy > Observe widget gets overlapped > Paste again 

### Version

cloud

**Comment by somangshu** [comment]
This should probably we solve with the list v2 implementation

cc @ashit-rath @Tooluloope

**Comment by Tooluloope** [comment]
Moving to Dev Closed as this is fixed in List Widget V2.
