### ISSUE TITLE
[Bug]-[7200]:On browser refresh the user clicks on "Dont Save" navigates to Invalid URL page

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#19801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to Datasource page  and creates an Auth API now user browser refreshes and is displayed with a popup then user clicks on "Don't Save" it is observed that the user is landed to "Invalid URL" page

### Steps To Reproduce

1) Click on Auth API
2) Now refresh the browser
3) Click on "Don't Save" from the Pop up 
and observe that the user is displayed with Invalid URL page

### Version

production

**Comment by rohan-arthur** [comment]
This affect all datasources, i.e., 18000 users. But not all of them end up facing this issue - this only happens on refresh with some unsaved changes. 
Let's assume 5% reach: 900

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 900 |
| Effort (months)  | 0.25 |

**Comment by prapullac** [comment]
Tested this on Local and works well
