### ISSUE TITLE
[Bug] Double Notification while deleting widget using keyboard shortcuts on Windows Machine

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#1981]
## Description

When deleting any widget using the DEL key shortcut there are two affirmative notifications. This might confuse the user that they are deleting two widgets and not one. 

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Drop any widget
2. Select Widget 
3. Press DEL key to delete it

### Important Details
 - Version: [Cloud ]
 - OS: [Windows 10]
 - Browser [chrome]

**Comment by riodeuno** [comment]
Fixed in #2262
