### ISSUE TITLE
[Bug] SAFARI : Page crashes on Safari on trying to add action

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1982]
Steps to reproduce:
1) Add an widget (Button, Text)
2) Click to open property pane
3) Navigate down to "On Click"
4) Select to add any action
and observe

Observation :
It is observed that the application crashes on try to add an action to the button

Expectation : 
The application must not crash and user must  be able add an action to widget

**Comment by ofpiyush** [comment]
Screenshot of console log from chat ![Screenshot 2020-12-01 at 3 44 48 PM](https://user-images.githubusercontent.com/292174/100729326-9df14580-33ee-11eb-96b9-48f9170641a2.png)

**Comment by ofpiyush** [comment]
@hetunandu from the console log, this looks like a string was `undefined` in https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx

**Comment by ofpiyush** [comment]
This is on Safari version 12

`matchAll` is only supported across ~86% devices

https://caniuse.com/?search=String.matchAll

**Comment by ofpiyush** [comment]
We have no users on the unsupported versions on Appsmith cloud today. (@areyabhishek checked)

If that changes, we can re-open and take this up.

In case this becomes important to solve later,  you can either
* use a [shim](https://www.npmjs.com/package/string.prototype.matchall)
* Change implementation in [ActionCreator](https://github.com/appsmithorg/appsmith/blob/94cae231c19bedeca7a78c6d4e1afab4b4ba6644/app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx)


If you plan to use `String.match`, you might need to skip `\g`.


---------------------------------

A decent path forward might be to warn users on unsupported browser versions.

Something along the lines of #1228

**Comment by prapullac** [comment]
On an Observation of the Stats we see that number of user on this particular browser is less and hence closing the issue for the issue
