### ISSUE TITLE
[Bug]: The Mobile Responsive DP does not render appropriately in Firefox

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19822]
Currently the DP breaks in Firefox

![Image](https://user-images.githubusercontent.com/39921438/212821621-91dbb7f4-5c69-409a-9d9a-d04bc87745f8.png)

**Comment by yaldram** [comment]
We found the root cause of this issue, the styles were breaking due to the polyfill, we have removed it @shadabbuchh reopen the issue if you still see the styles breaking.
