### ISSUE TITLE
[Task]: Create analytics event to track discovery of templates

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#19825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We need to create Mixpanel events that are triggered 

- when a user navigates to the Templates tab on the platform
<img width="1205" alt="Screenshot 2023-01-17 at 13 19 09" src="https://user-images.githubusercontent.com/32227135/212839517-5b798bde-e675-4c8a-86a9-078d20d03819.png">

- when a user adds a page from the Templates on the canvas
<img width="395" alt="Screenshot 2023-01-17 at 13 16 53" src="https://user-images.githubusercontent.com/32227135/212839182-bf6c1ea4-91d5-4b9e-a86e-f1afd23fd6e9.png">

- when user creates a new app from a template 
<img width="792" alt="Screenshot 2023-01-17 at 13 18 32" src="https://user-images.githubusercontent.com/32227135/212839407-d0c210c0-cf54-44d2-b25e-4944ffaec51f.png">

**Comment by kocharrahul7** [comment]
@danciaclara There are events for 2/3 of these already,
1.  Event name: `CANVAS_BLANK_PAGE_CTA_CLICK` property: `item = "ADD_PAGE_FROM_TEMPLATE"` for when a user creates a new app from a template
2. Event name: `ENTITY_EXPLORER_ADD_PAGE_CLICK` property: `item = "ADD_PAGE_FROM_TEMPLATE"` for when a user adds a page from the Templates on the canvas.

We will get the third one created as well

**Comment by danciaclara** [comment]
Great! Sorry missed that. Thanks :)

**Comment by akash-codemonk** [comment]
The pending event `TEMPLATES_TAB_CLICK` for templates tab is closed with https://github.com/appsmithorg/appsmith/issues/21024.
