### ISSUE TITLE
Update messaging when a group is invited through share modal in app and workspace

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#19832]
In the current scenario, when a group is associated with the role, the message mentions a user is invited. It should instead say that `The group has been invited successfully`

![a311672a224250f654f78b7341fb1df9.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/970a838e-baeb-4e2c-96e3-0cd690faa229)

**Comment by riteshkew** [comment]
Not valid anymore. Teste in v1.20
