### ISSUE TITLE
[Bug]: [Fixed Layout] Padding issue between two widgets in deploy mode resulting in overlapping on refresh

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#19836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The padding between two widgets seems to be different than what we set in edit mode

### Steps To Reproduce

1. Dnd two widgets one below the another
compare the padding between them in deploy and preview mode
2. Refresh the edit mode, you'll notice the reduction in padding reflects in edit mode as well

### Issue video log
https://www.loom.com/share/a2b907a72ddb4d75a9ef295d98b4b7e8

### Version

DP

**Comment by prsidhu** [comment]
@kamakshibhat-appsmith I'm unable to reproduce this bug. Can you still do it?

**Comment by kamakshibhat-appsmith** [comment]
Unable to replicate this now. we can close this
