### ISSUE TITLE
[Bug] Moving a disabled button needs to be simpler

### ISSUE THREAD

**Issue by ravivyas84** [appsmithorg/appsmith#1983]
You can't move a disabled button, you need to either enable it, or resize it [or get lucky =) ]. 

Please refer attached gif

![Bug_1](https://user-images.githubusercontent.com/283631/100728826-0a1f7980-33ee-11eb-9643-45c10a861ed0.gif)

### Important Details
 - Version: Cloud 
 - OS: MacOSX
 - Browser : Firefox 82.0.2 (64-bit)

**Comment by areyabhishek** [comment]
@ravivyas84 Thanks for reporting this. It's a firefox specific issue. We've not focused on Firefox because it's a small userbase.  Please keep reporting any other issues you see.

**Comment by ravivyas84** [comment]
Thanks. Checked on MS Edge Version 87.0.664.52 (Official build) (64-bit), no issues there.

**Comment by vihar** [comment]
This happens even if the Form is not validated.
