### ISSUE TITLE
[Bug] Message must be displayed to user when user tries to place widget on unselected tabs

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1984]
Steps to reproduce:
1) Add a Tab Widgets
2) Click on Property Pane 
3) Now delete the Default Tab added 
4) Try to place an widget on the tab
and observe 

Observation 
It is observed that the widget can not be placed on the tab widget.As the tab is not selected and user is not displayed with an message to select the Tab 

Expectation
User must be displayed with a message to select the tab when he tries to place a widget on unselected tab 

Loom link :
https://www.loom.com/share/e7f52fa016ff40778a092c96794701d8

**Comment by areyabhishek** [comment]
A good solution is to automatically choose the next available tab as the selected+default tab. It'll make it easier for the user to understand. What do you think? @prapullac

**Comment by prapullac** [comment]
@areyabhishek Yes, We can do as suggested. Look good to me 
However looking at the flipside if the user has an intention of not having a default tab and he wants the user to select the tab then we doing this would not go with the user intention

**Comment by areyabhishek** [comment]
I think that'll be a rare case where the user doesn't want any tab to be in a selected state. For now, we can assume that there'll always be a selected+default tab.

**Comment by prapullac** [comment]
Yes I do accept its a corner case. For now we can implement as you suggested

**Comment by rishabhsaxena** [comment]
@mohanarpit I guess would be better to do this at the backend, set another tab as default if the default tab is deleted?

**Comment by trishaanand** [comment]
@rishabhsaxena : Today the backend server actually doesn't understand the widgets. We have a very rudimentary understanding where we only care about the name of the widget and the dynamic bindings present in the widget. For the above to happen, we would need to start understanding the tab widget. 
This is definitely on the cards where the server and the client can share responsibilities around computations related to evals, etc. but this is not on the priority list.
