### ISSUE TITLE
[Bug]: Cannot create a new workspace

### ISSUE THREAD

**Issue by MyoThuraZaw** [appsmithorg/appsmith#19856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After signing up a new user account, there is no New Workspace button available.  Tried it with Google chrome and Safari.

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/39274823/213065839-881cef3e-be72-45d9-993a-2ebe1a4ada65.png">

### Steps To Reproduce

After signing up a new user account, there is no New Workspace button available.

### Version

Cloud 1.9.3.2

**Comment by Nikhil-Nandagopal** [comment]
@infinitetrooper @trishaanand could you have a look at this?

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal @infinitetrooper : Looking into this.
