### ISSUE TITLE
[Feature]: Expose a Table Widget Property That Indicates If a Table Widget Is in Edit Mode

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#19851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Users who use intervals to auto-update the data in a table would like to automatically stop the interval when a user starts inline editing a cell of the table. Using a switch that the user needs to turn off each time before editing a cell creates a bad UX. 
As of today, there is a workaround to use the internal property `Table1.editableCell.index`. If this value is -1, then the table is not in edit mode; otherwise, it returns the index of the edited row.
E.g.: 
`setInterval(() => { if (Table1.editableCell.index===-1) get_data.run()}, 2000, "autoupdate");`

However, as it is an internal property, it is subject to change in the future. Therefore, users need an indicator they can rely on.

### Why should this be worked on?

If the interval does not stop when a user starts editing a table cell, then inline editing is not possible. To create a better user experience, an indicator that the table is being edited needs to be exposed to users, so that they do not have to manually turn off the interval before editing a cell,

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6ufd8)

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith the correct way to achieve this is to submit the update using the onSubmit event of the column and not use an interval as a hack. Could you inform the user of this method and see if it works for them?
