### ISSUE TITLE
EVALUATED VALUE window blocking the input for query [Bug]: 

### ISSUE THREAD

**Issue by EdgarHnd** [appsmithorg/appsmith#19850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When ever I write a SQL query the EVALUATED VALUE window shows up and block the input field.
(It has been hapening for a very long time)
<img width="1179" alt="Capture d’écran 2023-01-17 à 18 08 58" src="https://user-images.githubusercontent.com/44275476/212965444-28dcefc8-8b88-4fd5-8ff9-5aa5fdf07e20.png">

### Steps To Reproduce

1. Go to add a new SQL query
2. Write a query

### Version

Appsmith v1.9.3.2-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
Thanks for reporting this @EdgarHnd. We're already tracking this issue here #4458

**Comment by EdgarHnd** [comment]
Alright thanks, sorry I didn't see that !
