### ISSUE TITLE
[Bug]: With feature flag introduction, unable to see Different canvas size for the existing flow

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#19868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With feature flag introduction, unable to see Different canvas size for the existing flow

### Steps To Reproduce

1. open any app via non-appsmith email
<img width="1788" alt="Screen Shot 2023-01-18 at 3 35 25 PM" src="https://user-images.githubusercontent.com/113327629/213143356-412dbc67-82f5-4675-921d-5bcb829e6477.png">

### Version

DP

**Comment by Sripriya93** [comment]
We are able to see different canvas size for a non appsmith user. Moving to done

![Image](https://user-images.githubusercontent.com/104895602/216597628-f1689dfc-6314-41c7-b5aa-22ebb70d3fc9.png)
