### ISSUE TITLE
[Bug]: Scrollbar appears in fields of the Git modal even when nothing is entered.

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even when nothing is entered in the fields of the Git modal, we are able to see a scrollbar.
<img width="506" alt="Screenshot 2023-01-18 at 11 30 05 AM" src="https://user-images.githubusercontent.com/39921438/213099078-3f4d0e40-1945-4b3e-af5e-5bcf556971d4.png">

### Steps To Reproduce

1. Open the Git modal.
2. Go to the `Deploy` tab.

### Version

Cloud

**Comment by infinitetrooper** [comment]
Closing this as it's no longer replicable.

![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/3cd7e955-6d81-470d-a2ce-67407a1a9621)
