### ISSUE TITLE
[Bug]: Docker container not starting after upgrading the latest version

### ISSUE THREAD

**Issue by baqirvd** [appsmithorg/appsmith#19862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I updated my installed AppSmith version to the latest one, I am unable to start the docker image and getting the below error

```

Error while trying to start up Appsmith instance: 
backend stdout | Looks like you skipped some required update(s), please go back to the mandatory upgrade path [v1.9.1], or refer to 'https://docs.appsmith.com/' for more info
```

### Steps To Reproduce

Update Appsmith to latest version using below command:
docker-compose pull && docker-compose rm -fsv appsmith && docker-compose up -d

### Public Sample App

https://qa-appsmith.vendians.com

### Version

1.9.3.1

**Comment by sum35h** [comment]
We apologize for the inconvenience, please follow the instruction on this [page](https://docs.appsmith.com/help-and-support/troubleshooting-guide/deployment-errors#server-shuts-down-with-schema-mismatch-error) to resolve you issue.

**Comment by baqirvd** [comment]
@sum35h I tried the steps but getting this error when trying to run container
`ERROR: manifest for appsmith/appsmith-ce:1.9.2 not found: manifest unknown: manifest unknown`
