### ISSUE TITLE
[Bug]: Function only returns data when it's not async

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#19882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Functions that are set to return data, fail to return data when the function is async

### Steps To Reproduce

1. Use the following code and observe behaviour of function execution when using/not using async code
```
myFun2: async () => {
		//Api1.run()
		return Api1.data
	}
```

### Issue video log

https://www.loom.com/share/abe16452e9994e00940f46f961c4e5a1

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami this is expected with async code execution. `API1.data` will be returned only when you run `await API1.run()`

the following code should work
```
	myFun1: async() => {
		//write code here
		await Api1.run()
		return Api1.data
	},
```
