### ISSUE TITLE
[Feature]: Add support for the custom ssh URL that does not begin with git@

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#19881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Why should this be worked on?

A self hosted or a private github organization can have ssh urls that does not begin with the keyword `git`. Hence such urls are not supported with Appsmith. We should support such use cases. 

Link to conversation - https://theappsmith.slack.com/archives/C0341RERY4R/p1674049012093039?thread_ts=1673636062.767679&cid=C0341RERY4R

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6vccs)

**Comment by luiznazari** [comment]
I'm unable to import an APP from a GitHub Repository because of this bug.
The SSH URL is as follow: `org-12345678@github.com:org_name/repository_name.git`.

![image](https://user-images.githubusercontent.com/7645409/213294878-d043f691-dfcb-401c-b850-1cb5c1b16bd9.png)

**Comment by amenasse** [comment]
This is also an issue for us integrating with Azure DevOps  repos.

**Comment by sondermanish** [comment]
Re-opened the issue because of ssh Url from user is not qualifying as a valid url

**Comment by ame-appsmith** [comment]
> Re-opened the issue because of ssh Url from user is not qualifying as a valid url

https://app.frontapp.com/open/cnv_1aixxm6k?key=Y8gJNqTiC8rbryEIijlfoRhkS9Xxt_CD

**Comment by amenasse** [comment]
Please reopen this #33426 doesn't handle valid usernames for Azure Devops such as those containing '-' 
See the regex for the previous fix  #30738

**Comment by sondermanish** [comment]
@amenasse Another fix : [#33482](https://github.com/appsmithorg/appsmith/pull/33482) went in last Thursday for the same. It will be available with the next tag.
