### ISSUE TITLE
Hide GAC nudge banners for instances onboarded onto the feature

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#19890]
We currently show the GAC nudge banner for all users, even if they're already using GAC features. This is irritating and provides a poor user experience.

![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/b7351291-60ea-4ab7-bfac-66f714d9d94f)

**Comment by infinitetrooper** [comment]
@Nikhil-Nandagopal @trishaanand - Thoughts on this?

**Comment by Nikhil-Nandagopal** [comment]
@infinitetrooper this is super poor. I wasn't aware this was implemented. We should have just added a new CTA in the role dropdown that said custom role and clicking it should take users to upgrade.

**Comment by infinitetrooper** [comment]
We do have that as well, in that case, we should just remove this nudge banner as it's an irritation for customers who just don't want to use GAC at all.

![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/ae821488-02a1-4556-8a5f-ac76495fddee)

**Comment by infinitetrooper** [comment]
@Debsourabh  - FYI, The issue I was talking about in the morning.

**Comment by pranayagarwal96** [comment]
Quick question here @infinitetrooper - both of these hooks are implemented only in BE right?

**Comment by infinitetrooper** [comment]
Yes @pranayagarwal96  - It's BE only.
