### ISSUE TITLE
Add documentation for JS object mutation

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#19896]
Release Date - March 17, 2023.

**Comment by jnikhila** [comment]
@rimildeyjsr - Could you please share the first draft?

**Comment by jnikhila** [comment]
@Rishabh-Rathod - Could you please share the first draft for this?

**Comment by Rishabh-Rathod** [comment]
@jnikhila I haven't started on the draft yet will need a few days for it.

**Comment by Rishabh-Rathod** [comment]
@jnikhila Initial draft link - https://www.notion.so/appsmith/JSObject-mutation-docs-f445d99a492a44938fdbd18589421dbb?pvs=4
