### ISSUE TITLE
Add linting for backward compatibility

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#19897]
### Description
Show a soft lint warning when API/Query data is assigned to JSObject variables so that users do not assume reactivity from the assignment.  
    
### Sample code snippet
```
export default {
  userData: _.filter(API1.data.users, 'active');
}
```
    
### Expectation:
When a  user references API or Query data on a JSObject variable's initial assignment, a linter warning has to be shown. **Warning message:** `JSObject variables are not reactive. Any updates to API/Query data will not be propagated to widget bindings. Re-assign the variable to update widgets.`

**Comment by bharath31** [comment]
@satbir121 this needs to be prioritized along with JSObject variable mutation.

**Comment by Rishabh-Rathod** [comment]
@bharath31 Did we notice user queries regarding confusion about reactivity not working for mentioned scenario? Last time we discussed about it, we planned to collect user queries to accordingly take action here AFAIK.

**Comment by satbir121** [comment]
There has been no signals that users are confused about JS object mutation.
