### ISSUE TITLE
[Bug]: Unable to delete newly created datasource from active tab

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#19904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On release, it is observed that data sources are not getting deleted even after deleting all queries of it.

### Steps To Reproduce

1. Create a new Data Source. eg: Postgres
2. Create a new query from same ds
3. Bind it with any widget and deploy the app once
4. Delete the used query
5. Now try to delete the Postgres Data source and observe that you are still seeing error and can't delete it

### Issue video log

https://bthrujcsw8.vmaker.com/record/Vq6VVt6HY7NVX3TE

### Version

Cloud / Release

**Comment by sumitsum** [comment]
Hi chandan, I think the datasource cannot be deleted because the published app is still using the query ie. once a query has been deleted, the apps using it need to be republished to enable datasource deletion.
