### ISSUE TITLE
[Bug]: [Fixed layout] Large scroll seen below Modal widget in older apps and templates

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#19901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we select Modal widget, we see a large scroll below the Modal widget

https://user-images.githubusercontent.com/104895602/213398307-a6c9ea85-acde-40ed-8fc0-dd9af7b45eea.mp4

### Steps To Reproduce

1. Select Modal widget from any older app / Templates
2. Scroll to see a large blank space below the Modal widget

### Version

Deploy preview

**Comment by Sripriya93** [comment]
As per the last discussion, moving it to in progress.

**Comment by aswathkk** [comment]
This is observed in production too. We are already tracking this in #19657
Once it is fixed, we will revisit this issue.

**Comment by Sripriya93** [comment]
Working fine, moving to done.
