### ISSUE TITLE
[Bug]: [Fixed layout] Scroll is not seen in container and Form widget in Fixed height 

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#19918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we dnd a container or form widget and change the height to Fixed in fixed layout, and have some widgets inside the container above the default space, we expect a scroll, but we are no able to see a scroll, even when the scroll contents is toggled on, this is impacting older applications as well

https://user-images.githubusercontent.com/104895602/213438008-f831d4e7-b445-47fb-bc6a-8b5c4e77c38a.mp4

### Steps To Reproduce

1. D&D  a Container widget or Form widget in fixed mode
2. Change Height from Auto height to Fixed 
3. Enlarge to some extent and place widgets down below 
4. Now lessen the height and observe no scroll is introduced

### Version

Deploy preview

**Comment by marks0351** [comment]
@Sripriya93 can we pls check if this is still reproducing?

**Comment by Sripriya93** [comment]
We are now able to see a scroll in Container and Form widgets in Fixed mode, moving to done.
