### ISSUE TITLE
[Bug]: Viewing a forkable app when not logged in immediately redirects the user to login

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#19938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Viewing a forkable app when not logged in immediately redirects the user to login

### Steps To Reproduce

1. Go to https://docs.appsmith.com/learning-and-resources/sample-apps
2. View any app
3. User is redirected to login page.

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1674192049701819

### Version

Cloud/Self hosted

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 @ginilpg why does this flow keep breaking? Can we please invest in some stability for this part of the product?

**Comment by Richarex** [comment]
**TestCase**
1. Download the Requestly app for Windows desktop url:- https://requestly.io/
2. Create a rule inside Requestly for delaying the API calls and save the created rule.
3. Test the Forkable app on the chrome browser and verify user is able to use the app.
