### ISSUE TITLE
[Bug]: Save option does not become ACTIVE when the user enters a few fields 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#19947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Consider the user  just enters "Account Name" and observes that he can not save the Datasource until he enters all the mandatory fields. However user is able to save the Datasource via Auto save feature 

Expectation : The save button must be active for a user on entering one field. This brings in consistency over other DB as well

Adding High as this impacts the flow of Multiple ENV

### Steps To Reproduce

1) Navigate to Snowflakes Datasource
2) Add a field 
and observe the Save button is not active

### Version

Prod
<img width="1280" alt="Screenshot 2023-01-20 at 2 21 17 PM" src="https://user-images.githubusercontent.com/71753653/213654469-5f14a9c6-2a98-4a85-bcbc-bd9e119398bd.png">

**Comment by sumitsum** [comment]
Closing it as this issue is not valid anymore becauses auto save for datasource has been removed now.
