### ISSUE TITLE
[Feature]: Flag to skip ReplicaSet check

### ISSUE THREAD

**Issue by rgdev** [appsmithorg/appsmith#19948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

During initialization, the fat container [runs](https://github.com/appsmithorg/appsmith/blob/3144c0a4527dbf2a4548d730151d8b63d4cbea65/deploy/docker/entrypoint.sh#L171) `rs.status()` which requires the `clusterMonitor` role however the managed DBaaS provider I use do not give me this role. I'm 100% positive my MongoDB instance runs in ReplicaSet mode so would it possible to bypass this check ?

Right now my only option is to mount a modified entrypoint.sh that removes this check.

### Why should this be worked on?

Impossible to run Appsmith with some MongoDB providers

**Comment by rgdev** [comment]
My suggestion would be adding an environment variable like `APPSMITH_MONGODB_SKIP_REPLICASET_CHECK=true`

**Comment by sharat87** [comment]
@rgdev, thanks for reporting. We intend to improve this check to only use the `read` permission, instead of the `clusterMonitor` role's features. I'll get this prioritized and push it soon.

**Comment by rgdev** [comment]
Hello @sharat87 and thank you for your swift answer :) I'm glad to know you are aware of the issue & prioritizing it. I'm looking forward to updates on this matter. Have a great day!
