### ISSUE TITLE
[Feature]: create a simple line graph chart 

### ISSUE THREAD

**Issue by whykay-01** [appsmithorg/appsmith#19946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi! I am writing this feature request because I found that it is not possible to customize the style of the existing line graph chart, so that the data is displayed simply in a form of **a line without any dots on it**. Currently, if the user wants to represent the data using the line graph option, every single data point will be reflected on the graph. Here is the screenshot on how it looks like:
![Screenshot 2023-01-20 at 15 09 03](https://user-images.githubusercontent.com/100032599/213648216-a8a8da13-6822-4dfa-9781-9534fa302a1b.png)

### Why should this be worked on?

The problem is that it gets really messy when you try to plot 100+ data points, as I did it on the screenshot. Hope that this feature could be adjustable in the future.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika @jsartisan is there no way to achieve this with our chart widget? Ideally, the chart should handle interpolation or simply hide the points as in this case

**Comment by jsartisan** [comment]
It's possible with a custom fusion chart. Just need to pass `"drawAnchors": "0"`.
![image](https://user-images.githubusercontent.com/6636360/213712645-1f736773-2507-4317-b1c9-799fe80f025d.png)

**Comment by whykay-01** [comment]
@jsartisan can you please send me the link for the projects which use this type of fusion chart?

**Comment by jsartisan** [comment]
https://app.appsmith.com/app/untitled-application-109/page1-63b2ca750bc0a80b30017e67

It's actually very simple. Just drop a chart widget, select the type chart "Custom Chart" and use this config

```{
  "type": "line",
  "dataSource": {
    "data": [
      {
        "label": "Product1",
        "value": 20000
      },
      {
        "label": "Product2",
        "value": 22000
      },
      {
        "label": "Product3",
        "value": 32000
      }
    ],
    "chart": {
			"drawAnchors": "0",
      "caption": "Sales Report",
      "xAxisName": "Product Line",
      "yAxisName": "Revenue($)",
      "theme": "fusion",
      "alignCaptionWithCanvas": 1,
      "captionFontSize": "24",
      "captionAlignment": "center",
      "captionPadding": "20",
      "captionFontColor": "#231F20",
      "legendIconSides": "4",
      "legendIconBgAlpha": "100",
      "legendIconAlpha": "100",
      "legendPosition": "top",
      "canvasPadding": "0",
      "chartLeftMargin": "20",
      "chartTopMargin": "10",
      "chartRightMargin": "40",
      "chartBottomMargin": "10",
      "xAxisNameFontSize": "14",
      "labelFontSize": "12",
      "labelFontColor": "#716e6e",
      "xAxisNameFontColor": "#716e6e",
      "yAxisNameFontSize": "14",
      "yAxisValueFontSize": "12",
      "yAxisValueFontColor": "#716e6e",
      "yAxisNameFontColor": "#716e6e"
    }
  }
}```

**Comment by whykay-01** [comment]
@jsartisan I got it, but once I re-adjust it, it says "This value does not evaluate to type Array<{ "x": "string", "y": "number Required" }>"

Is it possible that the customized chart only accepts string values for the x-axis, because my x-axis is the date value, which is produced as a result of the momentJs I apply to the data, once I map it?

**Comment by jsartisan** [comment]
can you share the screenshot of what code are you using in your config?

**Comment by whykay-01** [comment]
sure, here it is:
[
![Screenshot 2023-01-20 at 23 06 03](https://user-images.githubusercontent.com/100032599/213731245-72d936a7-5f47-4f73-9d2c-95f9b97adf19.png)
](url)

**Comment by jsartisan** [comment]
You forgot the step of selecting a custom chart type.

https://user-images.githubusercontent.com/6636360/213732450-d507d696-496b-4c35-b116-334891d57861.mov

**Comment by whykay-01** [comment]
@jsartisan thanks for the notice, however I tried to do what you showed, and it works. However, once I paste my data, the chart just says that there is no data to display... Even though the expected value contains all the data points. Could it be because I deployed Appsmith locally on my machine, and it does not support the fusion charts for some reason?
![Screenshot 2023-01-21 at 13 00 49](https://user-images.githubusercontent.com/100032599/213844414-8c435a54-2d1e-4685-913c-15e34f37b74e.png)

**Comment by jsartisan** [comment]
the data should have `label` and `value` properties but your data array's object have `x` and `y`. @whykay-01

**Comment by whykay-01** [comment]
Oh, you're right! Didn't notice that! Thanks a lot for your help. Appreciate it! @jsartisan

**Comment by jsartisan** [comment]
Closing as resolved.
