### ISSUE TITLE
TAsk: QA Callout-2

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#19941]
https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0

**Comment by kamakshibhat-appsmith** [comment]
QA Done, Moving to Dev Closed

**Comment by ashit-rath** [comment]
Closing this issue in favour of merged [PR](https://github.com/appsmithorg/appsmith/pull/15839)
