### ISSUE TITLE
[Bug]: GIT CONFIGURATION ERROR while trying to import an APP from GitHub repository

### ISSUE THREAD

**Issue by luiznazari** [appsmithorg/appsmith#19953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to import an APP from a GitHub repository on a Workspace that already have an App using a datasource with the same name as used by the APP being imported, results on error:

![appsmith_bug (1)](https://user-images.githubusercontent.com/7645409/213707789-2e94a43e-c089-4ae5-adb5-77bd13c4761e.png)

### Steps To Reproduce

1. Create a Workspace1;
2. Create an APP1 on Workspace1;
3. Create a Datasource (ex.: API  Datasource) on APP1;
4. Link the APP1 to a GitHub repository;
5. Create a Workspace2;
6. Create a random APP2 on Workspace2;
7. Create a Datasource on APP2 of the same type and the same name as the one created on step 3);
8. On Workspace2, try to import a new APP from the GitHub repository created on step 4).

### Version

v1.9.3.2-SNAPSHOT

**Comment by AnaghHegde** [comment]
@luiznazari Actually, this is an expected scenario, when an app is being imported from a git repo and the in the workspace if there is a data source of the same name and same type the import will fail. This is by design, we need to improve the error message so that the user can understand the cause of the failure.

**Comment by luiznazari** [comment]
@AnaghHegde So i'm unable to import a repo because of the original app has a datasource?

For a user perspective and for improved experience, i'd be a better solution to provide an option to rename the datasource, similar to the datasource config modal during an import.

**Comment by luiznazari** [comment]
@AnaghHegde It doesn't sound right to me to be unable to import a repo because the original app had a datasource. Don't you think so?

For a user perspective and for improved experience, i'd be a better solution to provide an option to rename the datasource, similar to the datasource config modal during an import.

**Comment by luiznazari** [comment]
My scenario: I have two Apps that use the same datasource. Both are linked to dedicated repositories. By this definition, I'll never be able to import the apps into another workspace.

**Comment by AnaghHegde** [comment]
@luiznazari Our current import floe does not support this and we understand that it is a valid use case and we have added this to our roadmap. Thanks a lot for reporting this :) 

The workaround for the movement is to delete the datasource from App1 and then import the app2 from the git repository.

**Comment by AnaghHegde** [comment]
@luiznazari Actually what you have is a valid use case and it should work. Could you please share the below details with me?

1. Are you on Appsmith cloud or self-hosted?
2. If self-hosted, what version of Appsmith are you using and could you also share the Appsmith logs here?
3. If on Appsmith cloud, could you share the App with me?
If you are not okay with sharing the details on this thread, please share them to the email  anagh at appsmith dot com

**Comment by luiznazari** [comment]
@AnaghHegde I shared a GitHub repository with you.

**Comment by AnaghHegde** [comment]
@luiznazari Can you share the information I asked above as well? It would be easier for me to debug the issue.

**Comment by luiznazari** [comment]
@AnaghHegde Sorry, I forgot to add the version info.
It occurred on Appsmith Cloud version v1.9.3.2-SNAPSHOT.

**Comment by AnaghHegde** [comment]
@luiznazari Can you share the app with me or support at appsmith dot com? Also share the app url here.

**Comment by Nikhil-Nandagopal** [comment]
@luiznazari we're closing this issue since we haven't heard back from you. Please do re-open it if you are still facing it
