### ISSUE TITLE
[Feature] Banner/Call-out for announcing breaking changes

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1996]
## Summary

A way to announce breaking changes and allow people to take action.
This banner should ideally appear for relevant user roles and for their organization.

User story:
1. This will help us direct a user's attention to an important change.
2. This can be a way of getting a user's consent for an opt-in or breaking change

**Comment by hiteshjoshi** [comment]
Can we close this for now?

**Comment by Nikhil-Nandagopal** [comment]
Year i think we should. We avoid breaking changes and if absolutely necessary we can use intercom. Let's reopen this if it becomes a priority
