### ISSUE TITLE
[Bug]: Docker image doesn't run on CPUs without AVX instructions

### ISSUE THREAD

**Issue by jarimayenburg** [appsmithorg/appsmith#19969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ever since Mongo v5, `mongod`, `mongos` and the legacy `mongo` client [require a CPU with AVX instructions](https://www.mongodb.com/docs/manual/administration/production-notes/#x86_64). The entrypoint script of the Docker image currently the `mongo` legacy client to validate the database. This prevents Appsmith from running on a CPU without AVX instructions even if you're using an external MongoDB instance.

Mongo now has a `mongosh` client that does not require these instructions and since we're only using the `mongo` client in the entrypoint script, it's relatively easy to replace it with `mongosh` to fix this issue. Besides, the `mongo` client has been deprecated since v5, so it's a good idea to migrate anyway.

Fixed in #19971

### Steps To Reproduce

1. Try to run the Appsmith CE Docker image on a CPU without AVX instructions.
2. Notice that the entrypoint script crashes with exit code 132 after the "Checking Replica Set of external MongoDB" step. This means that your CPU does not support the AVX required by the legacy Mongo client.

### Version

release

**Comment by sharat87** [comment]
Hey @jarimayenburg, thank you so much for reporting+raising this. I'll get this reviewed soon.
