### ISSUE TITLE
[Bug]: Rest API - Non standard headers get converted to text/plain when clicking Body tab 

### ISSUE THREAD

**Issue by alienfacepalm** [appsmithorg/appsmith#19961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Rest API Query

I require a non-standard Content-type header -> "application/json; domain-model=launchdarkly.semanticpatch". 

However, whenever I click the Body tab, and go back to the Headers tab it wipes out my header and replaces it with "text/plain". 

### Steps To Reproduce

1. Add a REST API PATCH query
2. Add Content-Type header with "application/json; domain-model=launchdarkly.semanticpatch" as the value (or any other non-standard content-type)
3. Click the Body tab
4. Click back to Headers tab
5. You will see it replaced the header value. 

If I don't remember to put the header back, the query stops working since it absolutely requires this Content-Type in order to function with json patching

### Version

1.9.4

**Comment by Nikhil-Nandagopal** [comment]
@alienfacepalm thanks for reporting this. We're tracking this issue here #14675 and fixing it soon!
