### ISSUE TITLE
[Bug]: The fields that cause errors in widgets do not get a red highlight without clicking on them

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We do not get to see the red highlight over the fields in the property pane that cause any errors in any widgets.
https://www.loom.com/share/a7e8ba9dd42545f1beecff592cacb8c0

### Steps To Reproduce

1. Go to any application.
2. Set up binding(s) in any widget in such a way that it throws an error.

### Version

Cloud

**Comment by somangshu** [comment]
@shadabbuchh please always mention the expected behaviour to give better clarity!

Right now from what I can perceive it seems like this is what is expected, until you click on the property pane field you will not see the red highlighted border
