### ISSUE TITLE
[Bug]: Page name is cut off in Preview mode

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#19984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Page name is cut off in Preview mode
![image](https://user-images.githubusercontent.com/92293815/214004440-362695cb-c819-422f-a82c-df287abd33a5.png)

### Steps To Reproduce

1. Create an application
2. Add 2 pages with long names
3. Click on _Preview_ button and observe the page names 

### Version

Cloud

**Comment by andrewdietekoki** [comment]
So on my end it truncates with ellipsis even though if feels off for the one circled in red. @dhruvikn 
@dilippitchika 
<img width="1680" alt="Screen Shot 2023-01-26 at 2 25 31 PM" src="https://user-images.githubusercontent.com/23283551/214847433-64c12fa1-41fa-4187-85d8-51312ff533cb.png">

**Comment by dhruvikn** [comment]
I think we need to rework the logic for the truncate. Will be resolved soon.

<img width="746" alt="CleanShot 2023-01-27 at 17 12 59@2x" src="https://user-images.githubusercontent.com/22471214/215078305-f943bd72-58c4-4c02-b75d-01515f0241f0.png">

**Comment by dilippitchika** [comment]
@dhruvikn can you retriage this and let me know what we do we need to do?
