### ISSUE TITLE
[Feature]: Collapse all invisible widgets in view and preview mode

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#19983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- When a widget within a container -- which has auto height enabled -- goes invisible -- in view and preview mode -- they should fully collapse, allowing widgets beneath them to take up the vacated space.
- We cannot have this enabled by default without consequences to existing apps. The reason for this, is that this will effect exiting page layouts and cause unexpected behaviour without the knowledge of the application developer.
- To mitigate this, we should enable this only for newly created applications. This way, application developers will notice the behaviour during development.
- This requires the application API response, to provide the client with a flag that informs the client of the fact that the application is a newly created application, allowing the client to enable this feature without consequences like breaking apps.
- The application API response can have a flag `collapseInvisibleWidgets: true`.
- If this flag exists and is `true`, the client will collapse all invisible widgets within an auto height enabled container.
- If this flag doesn't exist or is `false`, the client will not collapse all invisible widgets within an auto height enabled container.

### Why should this be worked on?

- Today, widgets which have auto height enabled, will collapse, allowing widgets below them to occupy their space.
- However, not all widgets have auto height. This leads to widgets like Button and Divider, always taking up space.
- Collapsing invisible widgets is a basic expectation when it comes to web UI.

**Comment by NilanshBansal** [comment]
Reopened, as @riodeuno is still working on this for the frontend.
