### ISSUE TITLE
[Bug]: Cannot position / move table filters

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#19986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Unable to position / move the table filters on the canvas.
[table-filters.webm](https://user-images.githubusercontent.com/13429535/214017697-686fc706-b3f3-450f-826a-fb0bee8e9157.webm)

### Steps To Reproduce

1. Drag and drop a table widget.
2. Click on the filters, try to move the filter pane using the `move` handle.

### Version

Release

**Comment by momcilo-appsmith** [comment]
@keyurparalkar can you or someone else find the reason why is moving the filters not working as it is supposed to?

**Comment by dilippitchika** [comment]
This is related to an issue in ui builders. We weren't able to triage it on our own. @somangshu can we get someone to take a look at this on priority?
