### ISSUE TITLE
[Bug] Line comments don't work inside Action.run() callback

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1998]
Given this piece of code
```
{{
    Api1.run(() => {
	// Something
	console.log('yo')
    })
}}
```
This gives a syntax error when executing.
`Syntax Error: missing ) after argument list`

Removing the comment or making it block comment resolves this issue

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu I'm lowering the priority here since it's not a blocker
