### ISSUE TITLE
Helm incorrect app version

### ISSUE THREAD

**Issue by atalakey4work** [appsmithorg/appsmith#20000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The helm app version is showing as 2.0.0 but is listed as 1.16.0 in [chart.yaml](https://github.com/appsmithorg/appsmith/blob/release/deploy/helm/Chart.yaml#L4)

### Steps To Reproduce

$ helm search repo appsmith

Output:

NAME             	CHART VERSION	APP VERSION	DESCRIPTION                                       
appsmith/appsmith	2.0.0        	2.0.0      	Appsmith is an open source framework to build a...

### Version

1.16.0

**Comment by pratapaprasanna** [comment]
This is a bug. which create confusion. we shall address it
