### ISSUE TITLE
How to downgrade from v1.9.3.1 to v1.8.15?

### ISSUE THREAD

**Issue by baqirvd** [appsmithorg/appsmith#20007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am facing several issues after updating to 1.9.3.1, I now want to move back to v1.8.15

### Steps To Reproduce

Update to latest version

### Public Sample App

https://qa-appsmith.vendians.com/

### Version

1.9.3.1

**Comment by pranavkanade** [comment]
You can do this by changing the appsmith-ce to appsmith-ce:v1.8.15 in your installation/upgrade steps

**Comment by pranavkanade** [comment]
@baqirvd please consider creating a [post on discord](https://discord.com/channels/725602949748752515/1006426744129069096) for help with the errors
