### ISSUE TITLE
[Bug]: Irrelevant logs in error tab, optimise the parsing error

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#20005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The blog widget has more than 20 errors linked to it. Do an RCA and fix the same.

### Steps To Reproduce

1. Open this app - https://app.appsmith.com/app/word-cloud/configure-63103fd8886f4b0a442bce3a?branch=master
2. Navigate to the explorer page

### Public Sample App

https://app.appsmith.com/app/word-cloud/configure-63103fd8886f4b0a442bce3a?branch=master

### Version

Cloud

**Comment by bharath31** [comment]
@ChandanBalajiBP what are the next steps here?
