### ISSUE TITLE
[Bug]: MySQL queries dependent on temporary tables has stopped working

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#20018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://app.frontapp.com/inboxes/teams/folders/15690316/archived/69384087244 

### Steps To Reproduce

https://app.frontapp.com/inboxes/teams/folders/15690316/archived/69384087244

### Version

cloud, self hosted

**Comment by sumitsum** [comment]
Please note that this was never an intended feature - i.e. multiple separate queries being able to access a temporary table. This was supported as a side effect of a bug that was long pending - i.e. we used to run queries on a single connection as opposed to a connection pool. Now that we have a connection pool each subsequent query may get allocated a different connection. As per the MySQL documentation: 
```
You can use the TEMPORARY keyword when creating a table. A TEMPORARY table is visible only within the current session, and is dropped automatically when the session is closed.
```
Ref: https://dev.mysql.com/doc/refman/8.0/en/create-temporary-table.html

In order to support this again we would have to introduce a new feature - i.e. something equivalent of pinning of single connection for a datasource or we allow users to create a connection pool with exaclty one connection in the pool. 
cc: @rohan-arthur @Nikhil-Nandagopal

**Comment by Irongade** [comment]
@felix-appsmith

**Comment by rohan-arthur** [comment]
https://mixpanel.com/project/2032485/view/178891/app/boards#id=4172284&edited-bookmark=53K8d9PeM9ky

**Comment by sumitsum** [comment]
Closing since this is the intended behaviour and we don't want to alter this any time soone.
