### ISSUE TITLE
[Bug]: Modals are being duplicated in the property pane on adding a new modal

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#20014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Modals are being duplicated in the property pane on adding a new modal. This also causes the modal to not open/close when it is bound to an event. 
![image](https://user-images.githubusercontent.com/109572422/214242763-00d9ef73-5ba7-4caf-bb98-58bc00fb4a45.png)

### Steps To Reproduce

1. Drop an icon widget (or any widget) onto the canvas
2. Set the onClick event to open a modal
3. Click on the `Add Modal` option in the property pane multiple times
4. Notice that the modal in the list has been duplicated

### Issue video log

https://www.loom.com/share/ff2e994c2539479dbe65b6e9b5e31de3

### Version

Cloud

**Comment by aswathkk** [comment]
This is not reproducible since the action selector UI changed. @laveena-en Can you confirm?

**Comment by laveena-en** [comment]
Yes, this isn’t relevant anymore since the action selector has changed.
