### ISSUE TITLE
[Bug] - Mongo DB -  gives a missing Default Database Name error. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20027]
Try to configure Manage Environments for Mongo DB - Prod and Staging
With all Production and Staging configured, click on Test Configuration
It gives an error - missing Default Database Name.

Expected behavior - Default DB is optional field, it should not error out due to that field missing 

https://ddpa7mfuvv.vmaker.com/record/lAmNkHLd6d7CXvat

**Comment by sondermanish** [comment]
Solved with DatasourceContext PR

**Comment by btsgh** [comment]
This seems to be resolved now. Default database name even went left blank, the test goes through
