### ISSUE TITLE
[Bug]: Inviting a new user who hasn't yet signed up on the instance shows "No one was associated" in Audit logs

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#20038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Inviting a new user who hasn't yet signed up on the instance or who doesn't exist on the instance, shows "No one was associated" in the Audit logs

<img width="1437" alt="Screenshot 2023-01-24 at 3 36 47 PM" src="https://user-images.githubusercontent.com/28362912/214317462-72eb108c-8d63-4187-a8db-d7b77be05e48.png">

### Steps To Reproduce

1. Go to the Users tab on Admin settings
2. Click on invite users button
3. Invite a new user who doesn't exist on the instance and assign any role to them
4. Now, once the invitation is successful, go to the audit logs page
5. See a new entry which reads "No one was associated" (refer screenshot).

### Version

Self Hosted - latest

**Comment by infinitetrooper** [comment]
Even though a user is being assigned the role, the title reads "No one was associated". It should read `User name was associated with role name`. I multiple users are associated with multiple roles, it should say `User name + 3 users were associated with role name + 3 roles. This same logic should apply for Role assigned/unassigned users, Role assigned/unassigned groups


![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/93e775b8-a7c9-4ce2-89f8-47183d30304e)
![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/064eb8ea-5686-415a-9fc3-d3450de9526b)

**Comment by vishnu-gp** [comment]
From the payload, it looks like the role assigned users list is empty hence the title is being that as a fallback. The users list is empty because the user account is yet to be created is my hunch. Looping in @nsarupr here

**Comment by infinitetrooper** [comment]
Events to handle @nsarupr 

- role.assigned_users
- role.unassigned_users
- role.assgined_groups
- role.unassigned_groups
- group.invite_users
- group.remove_users

**Comment by trishaanand** [comment]
This is completed.
