### ISSUE TITLE
[Bug]: In Manage Environments page, configure environment dropdown - options are starting with a small case letter

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I go to Manage Environments page, and click on configure environment dropdown - the Production and Staging options are starting with a small case letter

### Steps To Reproduce

1. Create and save a DS and Go to Manage environments for any datasource.
2. The prod and staging options are coming in small case letters.
3. Also note that in Zeplin, there are small circular colored icons next to each option. This is missing on the instance.
<img width="653" alt="MultipleEnv_ProdStaging_Smallcase" src="https://user-images.githubusercontent.com/101863839/214314059-a42273a3-f08a-46e1-9394-3cb5ed2f8098.png">

Refer Zeplin [here](https://app.zeplin.io/project/635b8c56ab73a736e7ac7fee/screen/635b8f3e9878f51688926284).

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
The FE code presents the name as sent by the server, this was done if in the future we might be getting env names generated by users causing these FE modifications to the name being raised as a bug. Anyways, I have added the fix in FE for now and marked this as a potential risk in the comments around the code change. We can refer back to this ticket if such a situation arises.

**Comment by btsgh** [comment]
@ayushpahwa Thanks for the resolution on the caps. One other thing - the red/green circles are still not showing up though, in the dropdown. As per [this](https://app.zeplin.io/project/635b8c56ab73a736e7ac7fee/screen/635b8f3e9878f51688926284) page on Zeplin. Would it be possible to fix that as well? 
Zeplin screenshot - 
<img width="352" alt="MultiEnv_ColoredCircles" src="https://user-images.githubusercontent.com/101863839/215021131-f224686b-bd47-4583-8c8e-067bfff2e433.png">

**Comment by btsgh** [comment]
Capslock issue is fixed. Keeping this bug open as this also deals with the icons missing on the environment [as per image in my comment above] @rohan-arthur

**Comment by btsgh** [comment]
Issue has been fixed.
