### ISSUE TITLE
[Bug]: Screen alignment on datasource page is not as per zeplin.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Screen alignment on create datasource page is not as per zeplin specification.

### Steps To Reproduce

Create a new datasource say PostGreSQL.
Screen alignment on this page is not as per Zeplin.

[Here](https://app.zeplin.io/project/635b8c56ab73a736e7ac7fee/screen/635b8f3a35b24335ab574ca4) is the Zeplin link

The current UI on the instance is - 
<img width="1287" alt="MultipleEnv_CreateDSPage" src="https://user-images.githubusercontent.com/101863839/214296254-74979c26-82ce-4c1a-aa5e-1cf660fc945a.png">

### Version

EC2 Instance

**Comment by rohan-arthur** [comment]
Attaching screenshot from zeplin here
![Screenshot 2023-02-24 at 13 41 26](https://user-images.githubusercontent.com/94514895/221126624-2be8710b-d0a9-48df-82a0-f66c194865e6.png)

@btsgh @ChandanBalajiBP would you please list the things that need to be changed?

**Comment by ayushpahwa** [comment]
Attaching notion cards for more info
https://www.notion.so/appsmith/Spacing-between-columns-is-inconsistent-26931e4d7e694be0a6a6b1d97d3baae6?pvs=4
https://www.notion.so/appsmith/The-header-spacing-is-off-73f7df5bb0c84ab4a7b3ec740f43a0ad?pvs=4
https://www.notion.so/appsmith/All-inputs-should-be-of-the-same-width-2db00bdf7ad549a4a0f3a6fff48c4165?pvs=4
https://www.notion.so/appsmith/Font-size-spacing-and-font-type-are-wrong-17188ad1cb984d0c8daeef85f421b4e1?pvs=4
https://www.notion.so/appsmith/Spacing-between-the-label-and-input-should-be-8px-484aa404a1f34565b70d78dded30c415?pvs=4

**Comment by btsgh** [comment]
I have raised this as a common issue across all datasources. [Zeplin references are available mainly only for OAuth and PostGreSQL screens]

**Comment by btsgh** [comment]
Some areas are still not reflecting the changes - 

![postgres_widthmismatch.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/50329cd8-3a4a-4e6e-b05f-7e15804ca12e)
![mongowidthmismatch.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/eeb87bf3-bddc-45bc-8402-20a477f7a833)
![mongowidthmismatch1.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/8cfc375b-9bde-4f6c-bc57-23416c46111c)

**Comment by Irongade** [comment]
@btsgh Uniform text and dropdown sizes, is not allowed as seen the Zeplin design, This has been done in the past and it was retracted as it looked weird.

cc: @ayushpahwa Kindly confirm the above.

**Comment by btsgh** [comment]
Adding @shadabbuchh as well to this to get this to a resolution.
