### ISSUE TITLE
[Bug]: For MySQL DS, un-required configuration options are listed in the Please Select an Option Dropdown. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For MySQL DS, when I go to Manage environments, I see extra configuration options listed in the Please Select an Option Dropdown, which are not a part of MySQL config. 

### Steps To Reproduce

1. Create a mysql DS and click on Manage Environments
2. In the Please select an Option dropdown, number of options are seen which are not a part of mysql configuration
<img width="620" alt="MultipleEnv_MySQL_ManageEnv_ConfigOptions" src="https://user-images.githubusercontent.com/101863839/214302019-5061f2e2-2b90-4330-bd55-3a3e2db4d37c.png">

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
This is a tech debt from the server. We are sending fields which are never rendered. The image for the same is added below. For our case, I have added a check to not show such fields in the dropdown. Maybe we can pick this up at a later time to remove these @nidhi-nair @sondermanish 


![image.png](https://images.zenhubusercontent.com/60d04e24be9e2f34b7493dfb/4817e903-4eb3-43b6-9329-7dd5b7e5b2ef)

**Comment by btsgh** [comment]
Resolved.
