### ISSUE TITLE
Use createImmerReducer to avoid spreading objects

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#20035]
This reducer should be using `createImmerReducer` instead of `createReducer` to avoid these types of spreads.

Additionally, we should identify the reducers which have this issue and fix them as well.

_Originally posted by @riodeuno in https://github.com/appsmithorg/appsmith/pull/19486#discussion_r1085327363_

**Comment by The-Saras** [comment]
Hey, is this issue still open?
I would like to work on it... :D

**Comment by akashIsCoding** [comment]
hey @riodeuno can you please assign this issue to me? Would like to work on this

**Comment by riodeuno** [comment]
Hi @The-Saras @akashIsCoding Thanks for showing interest in fixing this issue. I'm assigning this to you both.

**Comment by akashIsCoding** [comment]
hey @riodeuno sorry but I'm facing issues setting up the project. If anyone else wants to work in this issue in the mean while please let me know. I'll un-assign.

**Comment by riodeuno** [comment]
@akashIsCoding Noted. Thanks for letting us know. If you'd like help with your setup, please checkout our discord channel where team members and community members would be able to help.

**Comment by akashIsCoding** [comment]
Hey @riodeuno  I was able to setup the project finally! Will create a PR soon for this issue, looking forward to making contributions to this project :)

**Comment by riodeuno** [comment]
@akashIsCoding Glad to know that your dev environment is setup. We're looking forward to your contribution! 

Please look into other reducers which utilise the `createImmerReducer` if you'd like a reference for the implementation.

**Comment by akashIsCoding** [comment]
@riodeuno, Yes I was able to refactor this code, however there are 49 other files which are still using `createReducer` instead of 
`createImmerReducer`.  I don't mind refactoring all of them, should I go ahead? Might need some guidance for testing/QA this though...

**Comment by akashIsCoding** [comment]
@riodeuno  created a PR - #21562 to resolve this issue.

- From my understanding `createImmerReducer` should have been used whenever the handler is a generic object that is storing more than one function. 
- Found 42 such instances and have refactored `createReducer` to `createImmerReducer` in such cases. 

Kindly review. 
Thanks :)

**Comment by yasharma2301** [comment]
I can pick this
