### ISSUE TITLE
[Task]: Update highlight UI to a rounded rect.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20049]
Objective:

Highlights drawn on canvas during DnD should be a rounded rect with the following specifications:
- width - 4px.
- rounded corners - 4px.

**Comment by prsidhu** [comment]
https://user-images.githubusercontent.com/5424788/216989161-74fa0737-6e75-4b6f-8b5a-b13f22a6e2f3.mov

**Comment by prsidhu** [comment]
^ The highlights that are shown in drop zones during a widget drag have rounded corners and a white outline.

**Comment by Sripriya93** [comment]
Working fine, moving to done.
