### ISSUE TITLE
[Bug]: There should be no delete icon for only one Host Port combination

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the manage environments page, Delete icon exists for one host port endpoint, though it is non functional. 
Expected behavior - there should be no delete icon for one host port endpoint [View Zeplin]

### Steps To Reproduce

1. Create a datasource, save it and go to the manage env page
2. Note that even if there is one host port combination, delete icon is present, though it is not functional
3. This is incorrect. No delete icon should be present if there is just one host port combination
<img width="726" alt="MultiEnv_HostPort_Delete" src="https://user-images.githubusercontent.com/101863839/214355328-7a46777c-232f-4b5d-8591-4e8f58dd28dd.png">

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
This is an intended behaviour from the Kev value array. It will not just affect this but rest of the use cases too. Not sure if we should pick it up with multiple env.
cc: @riteshkew

**Comment by ayushpahwa** [comment]
Related to #20373
