### ISSUE TITLE
The sharable link is not getting copied when the user clicks on "Copy Application URL".

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20057]
1. Create an application
2. On the top right, click on “Share”
3. Click on “Copy Application URL” on the Pop-Up.
Observe - The link is not copied
<img width="1428" alt="sharable link" src="https://user-images.githubusercontent.com/119847783/214482837-7ddc2e04-0a49-44a4-b185-f21631442150.png">

**Comment by ayushpahwa** [comment]
This is not reproducible, can you please share a video?
