### ISSUE TITLE
[Bug]: Update the dependency on the same version of the chart breaking existing installation

### ISSUE THREAD

**Issue by WillyRL** [appsmithorg/appsmith#20056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This commit https://github.com/appsmithorg/appsmith/commit/c93ed4f54cad1978e383cdff5fd192238d0fd308 is breaking our existing appsmith installation, our MongoDB crashed with the error below :

```sh
 "ctx":"initandlisten","msg":"Wrong mongod version","attr":{"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: Location4926900: 
Invalid featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"4.4\" }.   
See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility. :: caused by :: Invalid feature compatibility version value, expected '5.0' or '5.3' or '6.0.   
See https://docs.mongodb.com/master/release-notes/5.0-compatibility/#feature-compatibility.).   
If the current featureCompatibilityVersion is below 5.0, see the documentation on upgrading at https://docs.mongodb.com/master/release-notes/5.0/#upgrade-procedures."}}
```

### Steps To Reproduce

1. Deploy the appsmith without this commit https://github.com/appsmithorg/appsmith/commit/c93ed4f54cad1978e383cdff5fd192238d0fd308
2. Update the installation and include this commit https://github.com/appsmithorg/appsmith/commit/c93ed4f54cad1978e383cdff5fd192238d0fd308 
3. Rollout restart the MongoDB cluster deployment 

### Version

Helm Chart 2.0.0

**Comment by pranavkanade** [comment]
@WillyRL this is a duplicate issue. Take a look - https://github.com/appsmithorg/appsmith/issues/19542#issuecomment-1401658198

**Comment by WillyRL** [comment]
> @WillyRL this is a duplicate issue. Take a look - [#19542 (comment)](https://github.com/appsmithorg/appsmith/issues/19542#issuecomment-1401658198)

I think it's quite different @pranavkanade, my concern is regarding the helm update chart strategy that updates the same version of the helm chart, it should publish under another version especially if the changes have breaking changes with the previous version.

**Comment by sharat87** [comment]
Hey @WillyRL, sorry just coming to this. Were you unblocked? This was a miss from our side. We now have a workflow that does the Helm chart deployment, and it checks if a version of Helm chart is already published, and if yes, it'll refuse to publish and fail. So this shouldn't happen again.

Sorry for the inconvenience this has caused. I'm closing this, but if you're still blocked, let me know and I'll reopen. Thank you! 🙏
