### ISSUE TITLE
[Bug]: NullPointerException: The mapper [com.appsmith.server.solutions.ce.PluginScheduledTaskCEImpl$$Lambda$2190/0x000000080178e448] returned a null value.

### ISSUE THREAD

**Issue by dharmavagabond** [appsmithorg/appsmith#20060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm executing `docker-compose up` and expect for the app to run, however, I got the following  error:
```
reactor.core.Exceptions$ErrorCallbackNotImplemented:
java.lang.NullPointerException: The mapper [com.appsmith.server.solutions.ce.PluginScheduledTaskCEImpl$$Lambda$2059/0x00000008016c1748] returned a null value.

Caused by: java.lang.NullPointerException:
The mapper [com.appsmith.server.solutions.ce.PluginScheduledTaskCEImpl$$Lambda$2059/0x00000008016c1748] returned a null value
```

### Steps To Reproduce

1. `curl -L https://bit.ly/3h08WqB -o $PWD/docker-compose.yml`
2. `docker-compose up`

### Version

Self Hosted - latest (v1.9.4)

**Comment by Nikhil-Nandagopal** [comment]
@dharmavagabond can you tell us what OS are you running appsmith on?

**Comment by dharmavagabond** [comment]
I tried it in **MacOS 10.15** with `podman` and `multipass`, and in a vps with **Ubuntu 22.10** and `docker`. Got the same error.

**Comment by Donglong** [comment]
setting APPSMITH_CLOUD_SERVICES_BASE_URL to **an empty string** can solve it

**Comment by Nikhil-Nandagopal** [comment]
@dharmavagabond I believe the error is benign and the app should still work once you open it in the browser
