### ISSUE TITLE
[Bug] : Bold the field names on Manage env page

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#20063]
The field name of Manage env page must be bold to distinguish

**Comment by ayushpahwa** [comment]
The difference is not in bold but the colour and size. @parth-appsmith the size definition of the variable name is not in the list of standard Design system values. I have matched the styles by setting custom values but please look into this in the future.

![image.png](https://images.zenhubusercontent.com/60d04e24be9e2f34b7493dfb/6b015419-70e1-4cb8-86df-a6a7fbbb6c13)

**Comment by btsgh** [comment]
Resolved
