### ISSUE TITLE
[Bug]: On giving app viewer access, nothing is shown for that user on app launch

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we give/share a user with app viewer access - nothing is seen on the page when that user logs in.

### Steps To Reproduce

1. Share an application to a user by giving only App Viewer access.
<img width="641" alt="Screenshot 2023-01-25 at 2 47 05 PM" src="https://user-images.githubusercontent.com/101863839/214524687-229af389-9a36-4f60-a1f9-10a346fd238f.png">

2. Login with that user. 
On launching, the page is blank. 
<img width="1210" alt="Screenshot 2023-01-25 at 2 43 57 PM" src="https://user-images.githubusercontent.com/101863839/214524727-87f3a20b-96fd-44cb-aa2d-a65889141ec3.png">

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
@btsgh tried replicating this but not getting the issue. Will it be possible to share a video. Also, this seems to be unrelated to the multiple env epic.

**Comment by ayushpahwa** [comment]
Unable to reproduce this, can you please check if you had deployed the app before sharing? @btsgh

**Comment by btsgh** [comment]
Unable to reproduce - Probably that was the case @ayushpahwa
