### ISSUE TITLE
[Bug]: The user lands on an error page if he changes the environment

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user lands on an error page if he adds a new datasource and changes the environment and chooses not to save the current environment data

### Steps To Reproduce

Steps:

1. Click + to add a new datasource.
2. Select a datasource, say - Postgres
3. From the bottom, change the environment
4. On the Alert message, click on "Don't save"
Observe - It lands on an error page

https://www.loom.com/share/9347da8e16aa44318690cb60591ea43f

### Version

Release v1.9.4

**Comment by ayushpahwa** [comment]
This will be fixed along with #20122
