### ISSUE TITLE
[Bug]: Data source goes to the view mode on changing the environment

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While creating a new data source, if the uses changes the environment and saves the data during changing the environment it lands on the datasource view page instead of view mode.

### Steps To Reproduce

Steps:

1. Create a new data source, say - postgres
2. Change the environment from the footer
3. Click "Save" from the Alert.
Observe - It shows the datasource in view mode

Expected behaviour - It should remain in Edit mode.

### Issue video log

https://www.loom.com/share/5507964bea984273b98e9dd4cb687d51

### Version

Release v1.9.4

**Comment by ayushpahwa** [comment]
This is in open discussion right now, blocked from product decision.
