### ISSUE TITLE
[Bug]: License flow issues in the home page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#20103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [x] The upgrade to business link is missing in the home page
- [x] The upgrade banner are not displayed in the home page
- [x] The user should be able to logout from the No subscription Page

### Steps To Reproduce

1. Have a ee instance up and running 
2. Now in the license page The logout option is  missing 
3. now add a correct license key
4. got to home page 
5. The upgrade links are missing 

### Version

localhost

**Comment by berzerkeer** [comment]
The upgrade banner and the upgrade to business link will only be displayed for trial licenses. 

For the header though, I will work on that,it will only have logout option.

**Comment by sbalaji1192** [comment]
This has been fixed in https://github.com/appsmithorg/appsmith-ee/pull/980
