### ISSUE TITLE
[Bug]: The new user signup is allowed even when the licensing flow is not completed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#20102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The new user signup is allowed even when the licensing flow is not completed

### Steps To Reproduce

1. Get ee instance up and running now fil the details in the Welcome screen
2. Now the license adding page will be displayed
3. Dont add the license
4. Open the URL in new browser
5. Try to signup
6. The user could signup 

### Version

Localhost

**Comment by abhvsn** [comment]
@sbalaji1192 @berzerkeer if we are getting the tenant config on page load and if the license key is missing we should not allow user to pass to login screen. Can you check if we are expecting something else here?

**Comment by sbalaji1192** [comment]
@pranayagarwal96 Shall we remove the signup link in this case when there is no active subscription ?

**Comment by pranayagarwal96** [comment]
Hey, as discussed, in corner case, where instance admin does not complete the set-up, and a new user tries to access the instance, we should still let the user sign-up, and post sign-up if there is no active license key - we will show the error page we had agreed upon [here](https://theappsmith.slack.com/archives/C04H5PFRN1H/p1673878588739689)

**Comment by berzerkeer** [comment]
@abhvsn Actually I just remembered, all these license flows are behind a feature flag, only usage@appsmith user will have these. The newly signed up user will have the existing flow.

**Comment by sbalaji1192** [comment]
@berzerkeer Can we enabled the usage and billing for  another email id `usage1@appsmith.com` ?
