### ISSUE TITLE
[Bug]: In EE instance the wrong data is displayed under the Billing section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#20115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In EE instance the wrong data is displayed under the Billing section
What is displayed 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/214839195-df05ac79-083f-47dc-84de-28036f063018.png">
Needs to displayed :
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/214839275-913dd21a-7467-4405-b940-5164727ec439.png">

 

### Steps To Reproduce

1. set up ee instance
2. Go to the admin setting
3. CLick on the Billing menu
4. Check the data displayed

### Version

localhost

**Comment by berzerkeer** [comment]
If you mean the new card with license key, this is part of the new update license key flow , for which we already have a PR open https://github.com/appsmithorg/appsmith-ee/pull/1000 .
