### ISSUE TITLE
[Bug]: Space is being occupied by modal widget on AutoLayout

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#20111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we open the modal, the space where we dropped the modal expands by shrinking the widgets next to it

https://user-images.githubusercontent.com/10436935/214827734-d6362822-0d16-4b48-adcd-c5c0626e08ba.mov

### Steps To Reproduce

1. Add a button to the center of an autoLayout layer.
2. Add a modal widget to the right of it
3. Open the modal to see the issue

### Version

autolayout latest dp

**Comment by kamakshibhat-appsmith** [comment]
This is not fixed @aswathkk @prsidhu

**Comment by aswathkk** [comment]
https://user-images.githubusercontent.com/10436935/233090548-8c421ba4-e4c3-462c-879e-a7aeb6cf953c.mov

Similar issue

**Comment by kamakshibhat-appsmith** [comment]
We have a new modal issue introduced after this fix
