### ISSUE TITLE
[Bug] Pages group in Entity Explorer does not collapse children

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2011]
## Description
Entity groups like Pages, Widgets, APIs and DB Queries need to have consistent behaviour. Pages group today cannot be toggled by clicking on the entity unlike Widgets, APIs and DB Queries.

### Steps to reproduce the behaviour:
![1](https://user-images.githubusercontent.com/103687/100982877-98bb0480-356e-11eb-92fb-1dff525015b0.gif)

**Comment by mohanarpit** [comment]
This is a sub-task for #2014
