### ISSUE TITLE
Clean the implementation of isAutoHeightEnabledForWidget

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#20110]
- [ ] Using flags for a specific purpose is difficult in terms of readability.
- [ ] Create a new function which does this special computation that is done today using the flag.
- [ ] Refactor any references.

_Originally posted by @marks0351 in https://github.com/appsmithorg/appsmith/pull/19082#discussion_r1086240821_

**Comment by theVJagrawal** [comment]
hey @riodeuno I want to work on this issue so can you please elaborate it more

**Comment by YoussefAbdellatif** [comment]
Can you assign that to me ?

**Comment by mudgil09** [comment]
heyy can you assign me that issue

**Comment by riodeuno** [comment]
@mudgil09 I'll be happy to assign this to you.
@YoussefAbdellatif I apologise for not getting to this sooner. Please check out one of the other `Good First Issue` tagged issues. I'll be happy to assign them to you.

**Comment by nikhil-babar** [comment]
@mudgil09 are you working on this issue

**Comment by riodeuno** [comment]
@nikhil-babar While we wait for @mudgil09 to respond. Would you like to try resolving this? Please let me know, and I can assign this to you.

**Comment by nikhil-babar** [comment]
Yes, please assign me this issue. It would be my first open source contribution

**Comment by riodeuno** [comment]
Done. I have assigned this to you.
