### ISSUE TITLE
[Bug]: WorkspaceImportApplication_spec fails due to server not accessible

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#20120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

WorkspaceImportApplication_spec fails due to server not accessible

### Steps To Reproduce

Failed test at 
https://cloud.cypress.io/projects/n14p1y/runs/025c23d7-a3ed-4982-b3fa-2cb11b85fb96/test-results/42b911a5-2429-4121-96ad-458ccd827c2b

### Version

Self hosted

**Comment by yatinappsmith** [comment]
Added high as test is constantly facing on EE

**Comment by infinitetrooper** [comment]
Stale
