### ISSUE TITLE
[Bug]: While creating a new data source, the values are not getting saved for any of the fields

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While creating a new data source, the values are not getting saved for any of the fields.

### Steps To Reproduce

steps:

1. Create a new datasource, say postgres
2. enter some value in say - host name etc
3. change the env
4. save the changes from the alert message
5. Now go and check if the values are saved

Observe - The values are not saved

### Issue video log

https://www.loom.com/share/b401f2602bb24b22821918a8c4091d71

### Version

Release v1.9.4

**Comment by ayushpahwa** [comment]
This is to be tackled under the datasource autosave changes.

**Comment by ayushpahwa** [comment]
@sribalajig @rohan-arthur FYI for autosave related bugs in multiple env

**Comment by ayushpahwa** [comment]
Will be fixed with #20122
