### ISSUE TITLE
[Bug]: Datasource is not getting saved on changing env.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user creates a new datasource, names it and changes the environment and saves the changes in the current environment, the datasource name is not getting saved.

### Steps To Reproduce

Steps:

1. Create a new datasource, say postgres
2. change the data source name from default to say - mypostgres
3. change the environment from bottom to staging
4. save it from the alert message

Observe - The default name is retained for both stage and production

### Issue video log

https://www.loom.com/share/5d7eea2c119941568ef3f322ccbd2380

### Version

Release v1.9.4

**Comment by ayushpahwa** [comment]
Datasource name change happens when you click outside of the box before changing the page by either reloading or any other action. Can you try doing that once? Also, these will be picked up with the datasource autosave changes.

**Comment by ayushpahwa** [comment]
@rohan-arthur @sribalajig  FYI for autosave bugs with multiple env

**Comment by prapullac** [comment]
The issue still exist please refer the video 
https://www.loom.com/share/9f9e383eb7f24febb77bad32765dab8f
