### ISSUE TITLE
[Bug]: Postgres: "admin" is always coming pre-filled as database name.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Postgres: "admin" is always coming pre-filled as database name. Even if the user deletes it, it gets saved.

### Steps To Reproduce

Steps:

1. Create a new postgres data source in
Observe - "admin" is pre-filled as database name
2. remove "admin"
3. change the env to staging
4. save on the alert message
5. Now go and check in the prod and stage configuration

Observe - database name is "admin"

### Issue video log

https://www.loom.com/share/42f1997c780c4a77b7672c993f1861c2

### Version

Release v1.9.4

**Comment by ayushpahwa** [comment]
This is the expected behaviour if you don't save the datasource. admin is the default value set there in case no value is set by user, this is done by the datasource config itself.
