### ISSUE TITLE
[Task]: Navigation - Logo - Handling alongside Branding

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#20135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

https://www.notion.so/appsmith/Logo-Handling-alongside-Branding-5735b11eb77b4a599ea6c18729437cf5

**Comment by chandannkumar** [comment]
Tested this PR and LGTM
- Tested Logo over default appsmith logo
- Tested Revert button
- Tested Navigation features
