### ISSUE TITLE
[Task]: Navigation - Logo Upload

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#20134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

https://www.notion.so/appsmith/Logo-Upload-fe20ec412b2046c5b44d6810d3c23913

**Comment by chandannkumar** [comment]
Added my observations here: https://github.com/appsmithorg/appsmith/pull/22297#issuecomment-1515677923

**Comment by chandannkumar** [comment]
Tested and verified Logo upload feature and it LGTM
