### ISSUE TITLE
[Feature]: Add support for files more than 5 MB on S3

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#20149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

RCA issue around uploading files in S3, determine max limit for this plugin, and check if this can at least meet our current 100MB max on cloud.

### Why should this be worked on?

Users have reported in multiple issues in the epic that hey are unable to use larger files with S3.

**Comment by nidhi-nair** [comment]
Findings:
- The transfer manager API has updated to internally manage files greater than 5 MB. I am not able to reproduce the issue with single or multiple file uploads anymore.
- There are two possible perf improvements in this plugin:
    - The request is not accompanied by total file size. This makes the TransferManager send this upload request as a single multipart request, slowing the upload down.
    - For multiple files, we're iterating through the list sequentially. This can be parallelized since the TransferManager takes care of queueing requests in case there are no port available.

**Comment by AnandShahs123** [comment]
file upload is failing when the data format is non- base 64. might be fixed by https://github.com/appsmithorg/appsmith/issues/20642
