### ISSUE TITLE
[Feature] Entity explorer redesign 

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#2014]
## Summary
The entity explorer currently feels a little overwhelming to use. Listing all the issue I found in it:

1. The accordion in list items of EE is inconsistent. I know this is the implementation issue but still pointing it out.
![1](https://user-images.githubusercontent.com/6636360/100994352-81831380-357c-11eb-97a6-e404d9661d11.gif)

2. The cross button in the widgets add section is feeling weird to me. It feels like it is meant to close the sidebar or close that section.

<img width="315" alt="Screenshot 2020-12-03 at 1 37 44 PM" src="https://user-images.githubusercontent.com/6636360/100994393-8ba51200-357c-11eb-870e-404f1e289f7a.png">

3. The search section feels diluted.

4. Not sure if we should use grid instead of the list for showing our list of widgets. Grid is mainly meant to consume image-rich content like in e-commerce.

5. The plus button for widgets/APIs/pages is not getting much attention.

**Comment by jsartisan** [comment]
For the 4th point, You can check this article - https://uxdesign.cc/ui-cheat-sheet-list-vs-grids-48151a7262a7

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan great points! Thanks for pointing these out.

**Comment by Nikhil-Nandagopal** [comment]
Closing this issue as part of the appsmith design system project. Next re-design will be with #1911
