### ISSUE TITLE
[Bug]: Download function always downloads images in png regardless of setting

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Download function always downloads images in png regardless of setting

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/215032939-8687d97d-82a5-494d-b4b1-29e53fa8e7fb.png)

[ Front conversation](https://app.frontapp.com/open/cnv_w1r02j0?key=kRB0sjV-jDxXvTmQ98HhGmlkqEL03M_3)

### Version

Cloud

**Comment by bharath31** [comment]
@rimildeyjsr could you investigate this issue and share the effort required for a fix?

**Comment by arunvjn** [comment]
Unable to replicate this bug. Need some help here. @ramsaptami @bharath31

**Comment by bharath31** [comment]
doesn't work for the default image `https://assets.appsmith.com/widgets/default.png` but works with other image URLs. we can close this for now
