### ISSUE TITLE
[Bug]: App crash on changing the datasource name after binding values

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I set environments for Prod, and then change the datasource name to a more meaningful one, the app crashes

### Steps To Reproduce

1. Create a new DS
2. Save it without entering any values
3. Now Edit and Manage environments - enter values for host/port, ds name, user, password and bind values
4. All the values are bound successfully
5. Try to now change the DS name to some meaningful name
6. The app crashes
On refresh, it comes back, but all the variables that were set are lost.

https://ddpa7mfuvv.vmaker.com/record/b30Vc3ofQGc0SogF

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
This is pending on the datasource rename changes from backend. @sondermanish when will those be done?

**Comment by ayushpahwa** [comment]
Will be closed with fix for #20025
