### ISSUE TITLE
[Bug]: Unable to test / configure Amazon S3 for multiple env

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to configure amazon s3 DS for multiple env - on binding values, it adds an end point url required field in the DS page, which is not part of S3  - On clicking Test Configuration, it goes to an infinite loop.

### Steps To Reproduce

1. Create a new amazon s3 DS and save it.
2. Go to Manage environments page
3. For Staging configuration, Add  values for S3 Service Provider, Access Key and Secret Key and bind these values
4. Note that values get bound successfully, but an additional end point url required field is added in the ds page
5. When we try to click on Test Configuration, it just goes into an infinite loop. 

<img width="756" alt="MultiEnv_TestConfigS3" src="https://user-images.githubusercontent.com/101863839/215075463-a3cd75fd-5723-4393-aefb-ca9ca0f1454b.png">

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
This is a front end bug. The ishidden logic is being affected by the presence of env variables. Will need to update this.

**Comment by btsgh** [comment]
I can test S3 and continue with creating queries. However, on setting up Prod and Staging through manage environments, the Endpoint URL field gets added to the edit ds screen, and still shows up as mandatory. This behavior is incorrect. This field should come up only for those providers for which it is mandatory. @ayushpahwa

**Comment by btsgh** [comment]
The Edit DS page still shows up with options common to all S3 Service Providers and also a couple of extra options - Custom Endpoint URL Key and s3 Service Provider Key. These two options are not part of any S3 Service Provider when selected from the dropdown on Release.
