### ISSUE TITLE
[Task] Create an API to update products table of Mock Database

### ISSUE THREAD

**Issue by pric-appsmith** [appsmithorg/appsmith#2016]
We'd like the users to be able to learn to use API in the tutorial. For that, we'd like to create an API

**Method**: POST 
**API**: https://mock-api.appsmith.com/products/:id/update
**Auth**: No auth
**Params**:  JSON with keys as column names
**Response**: JSON of updated product

--------------------------------------------------------------

**Sample Input**:
`POST` `https://mock-api.appsmith.com/products/4/update`
`{
"mrp" : 20.50
}`

**Sample Output**:
`HTTP 200 OK`
`{
   "entity":"product",
   "productId":4,
   "mrp":20.50,
   "listingPrice":37,
   "imageUrl":"http://res.cloudinary.com/drako999/image/upload/v1584095928/sl3ugfmotprtle3l3lk8.svg",
   "description":"tastyZ",
   "category":"DAIRY",
   "isListed":true,
   "availabilityDate":"2020-03-13",
   "channel":"WARE_HOUSE"
}`

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you please help us here. We're blocked on this to close the tutorials

**Comment by mohanarpit** [comment]
This has been done. You can now update products via the API:

**URL**
`PUT https://mock-api.appsmith.com/products/{productId}`

**Body**
```
{
    "productName": "Bamboo Shoots",
    "mrp": 16.99,
    "listingPrice": 28.99,
    "imageUrl": "https://robohash.org/consequaturvoluptatererum.jpg?size=50x50&set=set1",
    "description": null,
    "category": "BEVERAGES",
    "isListed": false,
    "availabilityDate": "2019-04-02",
    "channel": "WARE_HOUSE",
    "createdAt": null,
    "updatedAt": "2020-12-04T08:00:12.408Z"
}
``` 

Also, as part of this change, the field `productId` has been removed from the `products` table. This can now be referenced via the `id` field itself. In the tutorials, please modify all references of `products.productId` to `products.id`
