### ISSUE TITLE
[Bug]: Amazon S3 DS has extra options in Manage Env  on choose S3 as service provider

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to do a manage environments for Amazon S3 datasource, I see extra options in the dropdown

### Steps To Reproduce

1. Create a new amazon s3 ds, and save it without entering any values
2. Click on edit and then the Manage env button 
3. Click on select a new field dropdown
4. Note that End point url and region are not a part of the amazon s3 config for release when service provider chosen is S3

<img width="670" alt="MultiEnvS3_Extraoptions" src="https://user-images.githubusercontent.com/101863839/215069302-3dc769f1-1a27-4135-8dc8-17cdef0b051c.png">
**Options available on release -**
<img width="726" alt="MultienvS3_ReleaseOptions" src="https://user-images.githubusercontent.com/101863839/215069398-32d10cea-65ab-45a7-aab4-bc40a72e45f1.png">

### Version

ec2 instance

**Comment by ayushpahwa** [comment]
@btsgh this is not a bug. If you select the other option in the first dropdown you'll see the field. Pelase check.

**Comment by btsgh** [comment]
Yes, however, the bug is for on choosing **S3 as service provider.** 
On the Edit DS page, if I choose S3 as a service provider, am expecting only those options related to S3 as a service provider to appear in the Input Field, similarly, when I choose say Upcloud, only the options related to upcloud should come up and so on. @ayushpahwa 
Have changed the priority to medium though.

**Comment by ayushpahwa** [comment]
Need to update the isHidden logic for form rendering. This is related to another issue, will tag the number here.
