### ISSUE TITLE
[Bug]: For Redshift DS, un required fields are present in the manage env Select a new field dropdown

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In manage env, for redshift ds, un required fields are present in the Select a new field dropdown

### Steps To Reproduce

1. Create a new redshift DS 
2. Save and go to manage environments
3. Click on the Select a new field dropdown
4. Note extra options are present. 

<img width="676" alt="MultiEnv_RedShift_ExtraOptions" src="https://user-images.githubusercontent.com/101863839/215079828-909f12b0-9815-4ae1-b2d5-7c1055240fcf.png">

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
There is bloat in our form configs which include old unused fields. I'll need to either remove these from server side or add checks to now show these in FE. @nidhi-nair @sondermanish

**Comment by btsgh** [comment]
Has been fixed
