### ISSUE TITLE
[Bug] App crashed when writing JS in a table

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2017]
Not able to reproduce it but I have the logs
<img width="1680" alt="Screenshot 2020-12-03 at 5 32 02 PM" src="https://user-images.githubusercontent.com/3897254/101015825-f90d6e80-358d-11eb-8fbd-2b96d5aa6c4a.png">

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno @vicky-primathon please look into this

**Comment by vicky-primathon** [comment]
Fixed in [PR 2297 ](https://github.com/appsmithorg/appsmith/pull/2297/files)

**Comment by prapullac** [comment]
Closing the issue as I a, unable to reproduce the same
