### ISSUE TITLE
[Bug]: Date settings property visible under the Image column type table widget

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#20173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a column type is changed to image then, date settings are visible that are present in the date column type. 
![2023-01-27 06 07 07](https://user-images.githubusercontent.com/14138515/215100181-4357b392-bfaf-4c07-8828-2c5d75733a55.gif)

### Steps To Reproduce

1. Change the column type to Image in table widget
2. Observe that the date settings is visible.

### Version

Cloud

**Comment by somangshu** [comment]
Issue is already in the release, we need to prioritze this and verify the fix cc @kamakshibhat-appsmith @laveena-en 

cc @souma-ghosh
