### ISSUE TITLE
[Feature]: Build in support for Google Tables API

### ISSUE THREAD

**Issue by bamfdev** [appsmithorg/appsmith#20178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add Google Tables API as a supported datasource.

### Why should this be worked on?

Have you seen google tables?? It's awesome. Great concept, like NocoDB, Airtable, BaseRow, etc. It would make a ton of sense to have it as a datasource.
[https://tables.area120.google.com/about](https://tables.area120.google.com/about)

**Comment by Nikhil-Nandagopal** [comment]
@bamfdev thanks for the feature request! We'll probably wait for the datasource to gain a little more popularity before adding this to our roadmap

**Comment by bamfdev** [comment]
@Nikhil-Nandagopal You know what? I didn't do enough research before posting this. Supabase markets itself as an alternative, but instead of a Firestore, it just uses an internal PostgresDB. So, if you build in Postgres support, Supabase will likely automatically be supported as well. We can just ignore this request for now.
