### ISSUE TITLE
[Bug]: Default value property shows 'undefined' on Currency Input widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#20205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/95341241/215423894-5c0cda84-d40a-45b8-9a46-6feead7c5d0d.png)

![Screenshot (212)](https://user-images.githubusercontent.com/95341241/215423983-7e0cc8d1-d4d4-456e-ad7b-541827b12c9a.png)

### Steps To Reproduce

1. Drag & Drop Currency Input widget
2. Click on Default Value Property on Property pane
3. Observe that it shows 'undefined' instead of blank

### Version

Cloud / Production

**Comment by somangshu** [comment]
This is also expected @chandannkumar 
1. Do you think that the default value in the currency input should be 0? It might generate unexpected results. 
2. The way you are using this in the query does not makes sense! Lets think about real world scenarios in the future. 

Closing this for now
cc @dilippitchika
