### ISSUE TITLE
[Bug]: mongoDB not getting connected for a particular mongo connection string URI

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MongoDB not getting authenticated for a particular connection string URI, showing time out. However, the same string is getting connected on AppSmith Production.

### Steps To Reproduce

Steps:

1. Click to add a new datasource
2. Choose MongoDB
3. select "yes" from Use Mongo Connection String URI
4. Paste this URI - mongodb+srv://anand:anand@cluster0.afeeu9r.mongodb.net/user?authsource=admin&minpoolsize=0
observe - the same works for prod but not for ME

### Version

v1.9.4

**Comment by ayushpahwa** [comment]
@sondermanish can you take a look here?

**Comment by AnandShahs123** [comment]
still not working @sondermanish

**Comment by sondermanish** [comment]
Seems like a network problem, Confirming
