### ISSUE TITLE
[Bug]: Mongo: After adding a different value for an env, the previous env test doesn't pass

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user is in production and adds a different uri for stanging and test production again, the test fails. The user has to go and bind values again. And then, the test passes

### Steps To Reproduce

Steps:

1. Add a MongoDB datasource. Let the env be prod. Use this URI - mongodb+srv://mockdb-admin:oIvmxhw67hEmatML@mockdb.kce5o.mongodb.net/movies?retryWrites=true&w=majority
2. Test and save.
3. Open manage env
4. configure a different URI for Staging- Use this URI - mongodb+srv://raksha:Raksha123@cluster0.sn2li.mongodb.net/myFirstDatabase
5. Bind the values
6. Now, click on "Test configuration" [As env selected is production]
Observe - Error is - "Missing endpoints"
7. Now, go to Manage env again and select "Staging" and click on "Bind Values"
8. Now, again click on "test configurations"
Observe - It passes

### Issue video log

https://www.loom.com/share/d2d04403ce8a495e92a8023b372e0338

### Version

Release v1.9.4

**Comment by AnandShahs123** [comment]
still happening @sondermanish

**Comment by AnandShahs123** [comment]
@sondermanish - getting error on binding values now. not able to test

**Comment by sondermanish** [comment]
same as issue - 20262

**Comment by sondermanish** [comment]
This happens due to the datasource not having id in the payload, could you look at this once @ayushpahwa @ChandanBalajiBP.

**Comment by ayushpahwa** [comment]
If that is the case, this issue will be solved with #20262
