### ISSUE TITLE
[Bug]: Entity refactor is failing

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Entity name refactor is failing

### Steps To Reproduce

1. Add a JS objects
2. Add a reference to `myFun1` inside `myFun2` like: `JSObject1.myFun1()`
3. Change `myFun1` to `function1` and observe it's reference show up as an error

### Issue video log

https://www.loom.com/share/f9dce71fb55448ccb62c923bd2bd26a1
 https://ca9sxzlrgy.vmaker.com/record/hAyOoiIRwu6lBGP0

### Version

Cloud

**Comment by bharath31** [comment]
related to #19152? cc: @subrata71

**Comment by subrata71** [comment]
> related to #19152? cc: @subrata71

@bharath31 These two are unrelated. @ChandanBalajiBP Is this case covered in the refactoring logic through AST that you worked on?

**Comment by bharath31** [comment]
@ChandanBalajiBP ICYMI ^

**Comment by shwetha-ramesh** [comment]
Also when JSobj name is changed to number error is shown on the widget
https://www.loom.com/share/f874724025d74e118348ca37a0857da8

**Comment by rohan-arthur** [comment]
1. IMO, we should not refactor within the code
2. for the issue reported by shwetha-ramesh, we now show a specific error message that the name format is invalid, and we reject the renaming
