### ISSUE TITLE
[Bug]-[8000]:In table widget , Unable to see the Helper text for properties that come under Editable section in all column types

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#20235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 In table widget , Unable to see the Helper text for properties that come under Editable section in all column types 

### Steps To Reproduce

1. DND tablele widget
2. goto column type Plain text
3. switch property to editable
4. check the dependent properties . eg- regex
5. The "type / to access command " is missing in the input box

This can be replicated with Plain text, Number
<img width="435" alt="Screen Shot 2023-01-31 at 12 53 56 AM" src="https://user-images.githubusercontent.com/113327629/215575781-cdb2306a-0332-43e6-95b3-2d9ca0c647a9.png">

### Version

Cloud

**Comment by somangshu** [comment]
@kamakshibhat-appsmith is this what you are talking about?
![Screenshot 2023-02-02 at 2 47 51 PM](https://user-images.githubusercontent.com/11089579/216282642-d325603e-4e4a-434d-a62f-1cf19f9b0373.png)

cc @souma-ghosh @keyurparalkar

**Comment by kamakshibhat-appsmith** [comment]
Yes @somangshu

**Comment by keyurparalkar** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 8000 |
| Effort (months)  | 0.5 |
