### ISSUE TITLE
[Bug]-[400]:For select column type in the table widget where the options are dynamically set, the same doesn't show up during Add new row flow

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#20230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For select column type in the table widget where the options are dynamically set, the same doesn't show up during Add new row flow

https://www.loom.com/share/0d9fbce9249d4445b57a231b0f0ad9e9

### Steps To Reproduce

1. Dnd Table widget
2. Change column type to select
3. Set options dynamically thru API binding
4. Click on Add new Row
5. The options doesn't show up 

### Version

Production

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7kj2k)

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/msg_1n8d7v7w?key=z-D0c0UPWBC2qsHKYI2NSkFxIx6KWOrs) reported this issue.

**Comment by ame-appsmith** [comment]
[Another user](https://community.appsmith.com/t/select-in-table-options-not-showing-for-new-row/2099) reported this bug.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 100 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
This happens because the options property today only looks at data to create options today. We need to add support for new row here.


**Solution**

Show 2 new fields in the select column type, when the allow add new row is turned on in table 
  - SameOptionsInNewRow -- Boolean field ; When turned on the option for the first row is used in the new row. Default is true
     - Label : Use same options in new row
     - Tooltip : Toggle to display same choices for new row and editing existing row in column.
  - NewRowOptions -- Array field; when the above boolean is turned off we show this option to let people add options specifically for new row. Supports static and dynamic data, but doesn't support currentRow
    - Label: New row options
    - Tooltip : Options exclusively displayed in the column for new row addition.

**Comment by markomedin** [comment]
Hi All, will this bug be solved soon? For now my team will use a modal approach to overcome this when adding a new table row, skipping the add new row feature if the table widget. It's a step back for our business on the ui design and  we would really appreciate if this gets some attention. Thank you. :)

**Comment by adrian-stephens** [comment]
Same issue for me.  Clearly I can work around it with a Modal,  but it would be nice for the feature to work as intended.

**Comment by dilippitchika** [comment]
Hey folks, we have almost closed the development. Please keep an eye out in the PR linked to the issue.

**Comment by dilippitchika** [comment]
Folks @markomedin  @adrian-stephens this will be available in our on 17 Mar in production. Please keep an eye out. The way it works is listed here - https://github.com/appsmithorg/appsmith/issues/20230#issuecomment-1458101581

**Comment by markomedin** [comment]
Thank you for taking quick action on this issue. Big thumbs up for the AppSmith support team. :)
