### ISSUE TITLE
[Bug]: [Auto layout]Overlapping widgets issue with templates

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#20234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Overlapping widgets issue with templates

### Steps To Reproduce

1. Fork a template
2. switch positioning type from fixed to auto and then back to fixed

### Version

DP

**Comment by jacquesikot** [comment]
@kamakshibhat-appsmith is this still an issue? If  it is, how can i replicate it. Thanks
