### ISSUE TITLE
[Bug]: The scroll bar is missing in the Plan builder page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#20250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The scroll bar is missing in the Plan builder page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/215725423-8eeb863b-42dd-44ef-9f8c-6f6e801accb9.png">

### Steps To Reproduce

1. Login to https://release-customer.appsmith.com
2. go to plan builder page 
3. the scroll bar is missing because of which the data at the bottom are not visible

### Version

localhost

**Comment by ankitsrivas14** [comment]
Closing as it is fixed under issue 289 of cloud-services
