### ISSUE TITLE
[Bug]: Datasource review page is not accessible on second attempts

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to access the datasource review page after going to manage environments page, I am not able to access it.

### Steps To Reproduce

1. Login to appsmith
2. Go to an application with prod and staging env configured.
3. From the left panel, Datasources dropdown, click on the name of the datasource
4. The Datasource review page comes up
5. Click on edit, browse to manage environments, and then exit the page.
6. Now again from the left panel, Datasources dropdown, click on the name of the datasource
7. This time, the data source edit page comes up instead of review page.
8. This is incorrect. The review page should come up
We need to logout and log back in to access the review page again

### Issue video log

https://www.loom.com/share/b1aeba5e9709431aa081f2d52d54c174

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
@btsgh this is a feature under datasource autosave or context retention feature. Can you cross check with current release and see if there's a difference due to multiple env here? Thanks.

**Comment by btsgh** [comment]
@ayushpahwa  @riteshkew - as Ayush mentioned, this is existing in Prod as well. However, this issue needs to be fixed to make some sense on Multiple Environments. It is of no working use to the end user to have to log out and log back in to see review page in case of Multiple Environments. Can you please suggest how to go about this and make sure this is fixed in Release/Prod?

**Comment by ayushpahwa** [comment]
@rohan-arthur @sribalajig This seems like a side effect from datasource autosave.

**Comment by ayushpahwa** [comment]
Need to update config from BE @sondermanish
