### ISSUE TITLE
[Bug]: MongoDB: There is no mention of connection string URI on the datasource page if the "Use Mongo Connection String URI" is Yes

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MongoDB: There is no mention of connection string URI on the datasource page if the "Use Mongo Connection String URI" is Yes after the user has configured a different value for some other env through manage env

### Steps To Reproduce

Steps:

1. create a mongo datasource
2. go to manage env and add a connection string URI for other env
3. Bind values
Observe - On the datasource details page, there is no mention of the connection string URI

<img width="1440" alt="missing" src="https://user-images.githubusercontent.com/119847783/215745329-fad469af-db9e-4220-9688-0022fc7bb934.png">

### Version

Release v1.9.5

**Comment by ayushpahwa** [comment]
Related to #20165

**Comment by btsgh** [comment]
@ayushpahwa  - but if the user cannot see the connection string on this page, how does the user know about the connection string entered? @sribalajig ?

**Comment by ayushpahwa** [comment]
Will be fixed with #20165
