### ISSUE TITLE
[Bug]: Mongo: If the user selects user mongo connection string URI as "Yes", then also other fields are coming

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Mongo: If the user selects user mongo connection string URI as "Yes", then also other fields are coming which is confusing the user.

### Steps To Reproduce

Steps:

1. Create a new mongoDB connection. use this URI.
 mongodb+srv://mockdb-admin:oIvmxhw67hEmatML@mockdb.kce5o.mongodb.net/movies?retryWrites=true&w=majority

2. Edit
3. Go to manage env
4. bind a different value to stage. Use this URI:
mongodb+srv://raksha:Raksha123@cluster0.sn2li.mongodb.net/myFirstDatabase
5. Bind values
Observe - Other extra fields are coming

### Version

Release v1.9.5

**Comment by ayushpahwa** [comment]
Can you share a video? I think this was opened recently and concluded as an intentional feature.

**Comment by ayushpahwa** [comment]
Related to #20165

**Comment by btsgh** [comment]
@ayushpahwa - This is quite confusing to the user .. @sribalajig  I would think this needs to be fixed.. could you please give your comments also?

**Comment by ayushpahwa** [comment]
will be closed with #20165
