### ISSUE TITLE
[Bug]: MongoDB: user gets "missing endpoint" error on doing test configuration after configuring another environment

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user configures a value for a different environment through manage env, and then if he clicks on "test configuration" for any of the environment, there is an error "missing endpoint".

### Steps To Reproduce

Steps:

1. add a mongo datasource
2. edit and do manage env
3. configure a different value for another env
4. bind the value
5. perform test configuration
observe -  missing endpoint error

### Version

1.9.5

**Comment by AnandShahs123** [comment]
still hapenning @sondermanish

**Comment by sondermanish** [comment]
not reproducible

**Comment by btsgh** [comment]
As per discussion with @sribalajig  and @sondermanish - closing this as its not an issue.

**Comment by AnandShahs123** [comment]
@sondermanish - attaching video. this remains opened as per discussion with @sondermanish and @btsgh 

https://knynrq7fk9.vmaker.com/record/Tn66wIzKUahKL2jO

**Comment by sondermanish** [comment]
@ayushpahwa  @ChandanBalajiBP this happens due to client side not sending the id along with the datasourceConfig.

**Comment by sondermanish** [comment]
Server side has to improve the error messages.
