### ISSUE TITLE
[Bug]: {{appsmith.user.email}} is not available on page load

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#20275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The appsmith.user.email value is not populated in queries that run on page load

### Steps To Reproduce

1. create a query
2. bind it to appsmith.user.email
3. mark it to run on page load
4. check the network console and see that it's value is not passed to the query

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
User query https://community.appsmith.com/t/get-user-email-on-page-load/1946/3

**Comment by bharath31** [comment]
@Druthi @arunvjn could you add an RCA for this issue [here](https://www.notion.so/appsmith/Critical-Issue-RCAs-9106d8d7947a42b9bcbf09660fbe322a)?
