### ISSUE TITLE
[Bug]: Error message when git connection fails needs a few fixes

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/79509062/215834091-9ed9b19a-9ad8-4fa9-a2cb-798ec20f3b11.png)

### Steps To Reproduce

- [ ] remove comma after the string of alphanumeric text
- [ ] `Learn more` leads to [git page](https://docs.appsmith.com/advanced-concepts/version-control-with-git) rather than pointing to a possible way to resolve the error 
- [ ] Error is vague, action is to git 

### Version

Cloud

**Comment by riteshkew** [comment]
will be improved as part of git native.
