### ISSUE TITLE
[Bug]: Git setup failed for an app and now is in a dirty state 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Git setup on an app failed to connect but on page refresh shows successful connection but page with JS function set to run on page load returns a 404. Also fails to fetch git status

### Steps To Reproduce

1. Unsure how git setup failed

**DURING SETUP FAIL**
![delet](https://user-images.githubusercontent.com/79509062/215843857-843d61b8-f525-48ac-9b38-a594ba50ea20.png)
[git_connection_fail_400.zip](https://github.com/appsmithorg/appsmith/files/10549412/git_connection_fail_400.zip)

![image](https://user-images.githubusercontent.com/79509062/215844324-e9e10474-9a34-4a0e-a58d-f1578438b8bb.png)
![image](https://user-images.githubusercontent.com/79509062/215844433-f603f83a-331c-4e32-a145-728e95ab97dc.png)

**PAGE LOAD ERROR**
![image](https://user-images.githubusercontent.com/79509062/215850294-a20101c9-2272-4e65-b8fa-ed2d31bf5afb.png)
[404 for on page load actions.zip](https://github.com/appsmithorg/appsmith/files/10549655/404.for.on.page.load.actions.zip)
[git status failed Remote does not have refsORheadsORmaster available for fetch.zip](https://github.com/appsmithorg/appsmith/files/10549657/git.status.failed.Remote.does.not.have.refsORheadsORmaster.available.for.fetch.zip)
[git_connection_fail_400.zip](https://github.com/appsmithorg/appsmith/files/10549662/git_connection_fail_400.zip)

**ERROR MESSAGE WHEN TRYING TO COMMIT**
![image](https://user-images.githubusercontent.com/79509062/215852260-e5fd8710-5d64-4bbe-b1b2-c376e7c4db19.png)
![image](https://user-images.githubusercontent.com/79509062/215852315-6b4f3ec9-635d-4127-a08d-237b8b12c0d3.png)

### Public Sample App

https://release.app.appsmith.com/app/automation-test-cases/page-2-62c6ba550721a64d32ce5ef5/edit/jsObjects/62c6ba550721a64d32ce5f2f?branch=master

### Version

Cloud

**Comment by infinitetrooper** [comment]
@ramsaptami  - have you seen this with any other app, just want to see if there's a reliable way to replicate.

**Comment by ramsaptami** [comment]
@infinitetrooper haven't seen it happen on others
@Parthvi12 have you come across this at any point?

**Comment by infinitetrooper** [comment]
Okay, thanks. Closing as stale. Please reopen if this replicates.
