### ISSUE TITLE
[Bug]User setting for action on load gets reset when the action gets updated and gets re-evaluated according to the bindings

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2027]
## Description
An action's data is dynamically bound to a widget. This leads to the action getting identified as an on load action. The developer user does not want this action to run on page load. The user turns off this setting. So far so good.
When the developer user updates the action configuration, this leads to the action again getting marked for page on load.

**Comment by prapullac** [comment]
Hi @trishaanand 
As per discussion on the execution of the scenario I observe  that the issue still exists.Hence reopening the issue

**Comment by prapullac** [comment]
Closing the issue as it is working as expected
