### ISSUE TITLE
[Bug]: Firestore: After configuring stage, the test configuration fails for prod and if user selects prod, the queries fail to run for both

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Precondition: Assume prod is default env

After the user configures stage, the test configuration is failing for prod. Also, the queries give error if the selected env is prod.

### Steps To Reproduce

Steps:

1. Create a datasource. Create a query also.Assume env is prod by default
2. Go to manage env and configure a different value for stage. Also, create a query for stage
3. Change the env to prod again
4. Perform test configuration
Observe - There is an error here
5. Run the queries for both prod and stage.
Observe - They fail

### Version

1.9.5

**Comment by sondermanish** [comment]
Tested with Ayush, was not able to reproduce. putting in needs QA

**Comment by AnandShahs123** [comment]
This is not anymore reproducible. might have been fixed by some other fixes. @sondermanish you can close this

**Comment by AnandShahs123** [comment]
@ayushpahwa @sondermanish  not able to re-test. getting internal server error toast on binding values
