### ISSUE TITLE
[Bug]: v.1.9.5 Map Widget can't choose color on Markers and Unresponsive on updating (by requerying)

### ISSUE THREAD

**Issue by w12system** [appsmithorg/appsmith#20271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1246" alt="Screenshot 2023-02-01 at 00 13 35" src="https://user-images.githubusercontent.com/117699466/215836841-5019ff80-0b6d-4519-b9eb-9bea947f0143.png">
Before 1.9.5, i have a database of places with categories that linked to Map Widget and show colors based on the categories.

e.g. Category A showed by Red Marker
Category B showed by Green marker
etc.

![Screenshot 2023-01-30 at 15 43 25](https://user-images.githubusercontent.com/117699466/215837044-6aabbd35-e22e-454a-97f2-c2d18188caad.png)
Now on 1.9.5 revamp on using latest maps library, the color won't change based on it. And also when filtering the places based on their region/category (by re-quering), the webapp becomes unresponsive. And sometimes the filtered places didn't update properly.

### Steps To Reproduce

Video attached below:

Left Side: Self Hosted 1.9.4 (the expected function)

Right Side: Cloud 1.9.5
- Marker colors ignored
- Appsmith become slow when querying filter
- Maps showing unexpected, wrong, filtered places. (Expected result is shown on the left side)

### Issue video log

https://youtu.be/8vEL_00KgNs

### Version

Cloud - 1.9.5

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_753ik)

**Comment by jsartisan** [comment]
@w12system Hey, i have raised a PR for this issue, can you try this DP and check if it solves the problem the you are having?
https://appsmith-git-fix-google-map-marker-color-issue-get-appsmith.vercel.app/
