### ISSUE TITLE
[Bug]: Firestore: Service account credentials not visible on review and on datasource page.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Considering production being the default env, after the user configures stage, the service account credentials is not visible on review and datasource pages.

### Steps To Reproduce

Steps:

1. Add a datasource. Assume default env is prod
2. Configure stage through manage env

Observe - Service account credentials is visible for stage but not for prod on both review and datasource page

### Version

v1.9.5

**Comment by ayushpahwa** [comment]
Related to #20510
