### ISSUE TITLE
[Bug]: Password is visible after binding values in both the environments

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After binding values through manage environments, password is visible for both the environments in the data source page.

### Steps To Reproduce

Steps:

1. Create a datasource. Let prod be default env
2. bind a different set of values for stage

Observe - Password can be seen on the datasource page.

<img width="1440" alt="arrango pwd" src="https://user-images.githubusercontent.com/119847783/216008996-f471462e-8947-4cff-b38d-9ec5604171c6.png">

### Version

Release v1.9.5

**Comment by ayushpahwa** [comment]
This is fixed from FE but need to mask these values or not send them from server also. @sondermanish 
Also related to #20510
