### ISSUE TITLE
[Bug]: Arrango: User gets error message if the user taps device enter/ return button after renaming the default datasource name

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Arrango: User gets error message if the user taps device enter/ return button after renaming the default datasource name

### Steps To Reproduce

Steps:

1. Click to add new arrango data source
2. edit the default name
3. Press return button from laptop/ device

Observe - There is an error message

<img width="1439" alt="arrango" src="https://user-images.githubusercontent.com/119847783/215995129-6501f53f-6a9b-4609-9983-643221caa96d.png">

### Version

Release v1.9.5

**Comment by ayushpahwa** [comment]
@sondermanish seems like a server issue, can you take a look?

**Comment by ayushpahwa** [comment]
Will be fixed with #20025
