### ISSUE TITLE
[Bug]: Not-logged-in users given 404 when accessing private app

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#20299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A non-logged-in user going to the URL of a private app receives a 404 Page not found error instead of being directed to a login page.

### Steps To Reproduce

1. Make a private app
2. Go to share and get the URL
3. Open a fresh incognito window
4. Navigate to the URL

### Version

Cloud

**Comment by infinitetrooper** [comment]
This was closed in `v1.9.8`
