### ISSUE TITLE
[Bug]: Secure Appsmith CRUD operation page

### ISSUE THREAD

**Issue by junaidtk** [appsmithorg/appsmith#20298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have created a **CRUD** operation page for my application. Then I have embedded the page in one of my website by using the **iframe** embed option. This **CRUD** page accessing one of my table in the database and all the Create, Delete, Update operation can be done by using this page. 

So in order to make the page to embed on the website, I have to make the page as public. 
Then the issue will arise that,  This page can be opened by any one with the app page URL. So my database table is exposed to public. any can modify the DB entries.

So What are the measures to do to make the CRUD page from the unauthorised access ?

### Steps To Reproduce

- Create CRUD page.
- Make the page as public.
- Embed the page URL in any of the our website template.
- It will show the CRUD page in the website.
- Then copy the URL of the CRUD app and open in the private window. It can be accessed by anyone.

### Version

1.7.9

**Comment by pranavkanade** [comment]
@junaidtk, we are working on private embedded apps. The feature will be available with our business plan.
