### ISSUE TITLE
[Feature]: allow downloads in iframe

### ISSUE THREAD

**Issue by SvV-CWinJS** [appsmithorg/appsmith#20297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith now allows scripts and popups, for example, in iframes.
I would like it to also add "allow downloads" to the sandbox-mode.

### Why should this be worked on?

We have several small files as base64 data in our database.
We display through a single iframe some information about the file and a download link of the contents by
`<a href="<data URL>" download>fileName</a>`
Clicking on the link does nothing. The user needs to right click and do Save As. Most users are not that "techy" to know this workaround.
I suppose that "allow downloads" would make clicking the link result in a download.

**Comment by Nikhil-Nandagopal** [comment]
This is not directly possible but you can use postmessage to send the file data from the iFrame to the appsmith app and download it
