### ISSUE TITLE
[Bug]: Twitter and LinkedIn links are swapped on the about us page for team members

### ISSUE THREAD

**Issue by KritikaDas6** [appsmithorg/appsmith#20302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user clicks on a team member's Twitter profile, it leads them to their LinkedIn account. If a user clicks on their LinkedIn profile, it will take you to their Twitter profile.

The links on the icons are switched.  

### Steps To Reproduce

1) Go to Appsmith about-us page (https://www.appsmith.com/about-us#about-us-team-section-heading)
2) Click on the LinkedIn icon under a team-member 
3) It will take you to their Twitter Profile
4) Click on the Twitter Icon under a team-member
5) it will take you to their LinkedIn profile

### Issue video log

https://www.loom.com/share/156d5fe2f9a24933ac1c9211c5f5bdc3

### Version

Cloud/ Self Hosted- 1.6.6

**Comment by KritikaDas6** [comment]
@Nikhil-Nandagopal @pranavkanade Can I tackle this?

**Comment by srishtiprasadmanit12** [comment]
@Nikhil-Nandagopal @pranavkanade please assign me this issue

**Comment by tejasahluwalia** [comment]
Thanks for finding this. Has been fixed.
