### ISSUE TITLE
[Bug]: Review page has minimal details as against zeplin

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I view the review page, it does not have all the details as shown on Zeplin.

### Steps To Reproduce

1. Set Manage Environments for both Production and Staging environments (Host/Port/DB Name/Username/Password are all bound)
2. Go to the datasource review screen
3. Only Connection mode and database name are seen for both environments
As per [zeplin](https://app.zeplin.io/project/635b8c56ab73a736e7ac7fee/screen/635b8f379b8dcb35b3afa7f1), all the details should be shown on this page.
4. Also, though the database is bound, the value for db is showing up here explicitly and not as the environment variable

<img width="987" alt="MultiEnvDSReviewpage" src="https://user-images.githubusercontent.com/101863839/216264386-30536a51-36fe-49b0-a240-d5762e061c0e.png">

### Version

ec2 instance

**Comment by ayushpahwa** [comment]
@btsgh Please refer to [parth's comment](https://github.com/appsmithorg/appsmith/issues/20485#issuecomment-1429250229) in #20485

**Comment by btsgh** [comment]
Noted @ayushpahwa - with regards Parth's comments, I had a few queries.
What then is the final decision on the Review page? @sribalajig 
1. Since there was a Zeplin for this page, we are validating the UI with respect to the Zeplin. Hence this bug. Please advise on what should be the status of this bug?
2. Agreed RBAC will take care of this page. But functionality wise, without RBAC set, for the instance admin, it should work just the same way as it does on Release - This is what QA is testing against. Is this a valid assumption?
3. If above is true, then how should point 4 in the bug be addressed? The value for the DB should be showing up as the bound value.
