### ISSUE TITLE
[Bug]: Unable to upload binary files to S3

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#20315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Although the base64 option works for S3, the binary option results in corrupted data in S3. The upload does succeed with the correct size and type, this might be a case of unexpected encoding formats.

### Steps To Reproduce

1. Drop a filepicker widget and edit its properties to store binary data
2. Add a new S3 query to create a new file
3. Choose Text / Binary option for this query
4. Try to upload a PDF file to S3

### Issue video log

https://user-images.githubusercontent.com/5298848/216295545-993d62c2-61cf-497b-9686-5bf04d54c91d.mov

### Version

Cloud

**Comment by marcokiewit** [comment]
I had the same problem when uploading via post request.

**Comment by felix-appsmith** [comment]
This problem also affects the file upload to other APIs like Drive. This user reported it: https://app.frontapp.com/open/cnv_11do02bw?key=nOrL1kbM8-zURYl1tdYkhdU0cqbswQM0

**Comment by ankitgehlot123** [comment]
i am facing the same issue while uploading a zip file to S3 bucket using binary option in File Picker and S3 Query.

**Comment by rohan-arthur** [comment]
this works now, we recently shipped a fix but didn't get around to closing this issue. 

https://github.com/appsmithorg/appsmith/assets/94514895/1a44c823-daf8-4afd-91bc-9215106c853c
