### ISSUE TITLE
[Bug] Check for stale datasource connection before execution for Mysql plugin.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2032]
## Description
1. Check for stale datasource connection before execution for the Mysql plugin.
2. Return stale connection exception.

## Context
Currently, stale connection is not checked for, and hence an exception occurs during execution which gets returned to UI as it is. With a stale connection, the new action implementation class catches this exception and takes corrective action.

### Steps to reproduce the behavior:
1. Create MySQL datasource.
2. Restart MySQL to invalidate connection.
3. Run MySQL query.

### Important Details
 - Version: Any
 - OS: Any
 - Browser: Any

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum @mohanarpit why is this a low priority issue? This was faced by Ravi and now once again. This looks critical to me, it's faced by a user and it's blocking their flow

**Comment by ame-appsmith** [comment]
https://discord.com/channels/725602949748752515/1026404443517890571

**Comment by sumitsum** [comment]
Closing this issue since the issue mentioned on Discord link is a different issue. 
@ame-appsmith can you please check with the user if they are on latest version. If not then please ask them to upgrade to the latest which might fix their problem since a connection related fix was shipped in one of the earlier versions. If the issue was found in the lastest version then please create a separate GitHub issue for this.
