### ISSUE TITLE
[Feature]: JSObject : Allow cancelling of JS Object funtion run

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#20320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, if I trigger the function run for a sync function in JS object and it is taking too much time there is no way to cancel this run. 

### Why should this be worked on?

Improve JS Object usage experience.

**Comment by rohan-arthur** [comment]
duplicate of #19676
