### ISSUE TITLE
[Bug]: SMTP : Datasource review page does not show details

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#20329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user has saved the datasource page with variable details it is observed that the user is not able to view any config 

### Steps To Reproduce

1) Navigate to SMTP datasource
2) Add Manage environment details 
3) Bind and Save the datasource 
and observe the datasource review page 
<img width="1280" alt="Screenshot 2023-02-02 at 5 09 49 PM" src="https://user-images.githubusercontent.com/71753653/216369177-fe12e2a7-a148-40c4-9cc0-aa74a780161c.png">

### Version

DP

**Comment by riteshkew** [comment]
Last iteration bug
