### ISSUE TITLE
[Feature]: JS Object: Allow navigation when JS function is being run

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#20321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, if a JS function is being run and it is taking time, then the user cannot navigate away from the page say to check out another query or widget page because the Appsmith application seems to become unresponsive till the JSObject run is complete.

To reproduce:
1. Create a mysql query to insert a row. 
2. Create JS object function to run the above query 5000 times in a loop.

### Why should this be worked on?

Improve navigation experience.

**Comment by rohan-arthur** [comment]
it is now possible to navigate while the js function is being executed

https://github.com/user-attachments/assets/ca1b969c-8b20-4a86-bb25-696581fc0069
