### ISSUE TITLE
[Bug]: SMTP : Clicking on Test Config does not show any message on wrong config in the Environment variables

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#20330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user adds a wrong config on the variable page and binds the data in datasource it is observed clicking on the Test config no error message is displayed to user

### Steps To Reproduce

1) Add a SMTP datasource 
2) Save the datasource 
3) Click on Manage Environment 
4) Bind the wrong variable (add wrong Port)
5) Click on Test config and observe
 

### Version

DP

**Comment by sondermanish** [comment]
@AnandShahs123 could you retest, please also compare with release.app.appsmith.com
@ChandanBalajiBP some datasources don't have reliable test configuration.

**Comment by btsgh** [comment]
Re-tested. @sondermanish  - SMTP has test. configuration and it does not bring up an error on testing, as described in the bug. However, it is the same even on release.
