### ISSUE TITLE
[Feature] Custom widget

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2033]
## Summary
A way to include a custom component in Appsmith's canvas.

## Motivation
Some tools require very specific types of widgets to display, represent and interact with data.

![unknown](https://user-images.githubusercontent.com/103687/101244317-c7320e80-372b-11eb-8eed-e537c226a894.png)

These types of widget functionality may not be available in the default set of widgets in Appsmith.
Having a way to include these in applications can be helpful.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5aioc)

**Comment by ofpiyush** [comment]
Please read #2122 when we pick this.

**Comment by droggo** [comment]
+1 for this feature

**Comment by slysiou** [comment]
+1 would be great to have abilities to create custom Gant, D3js...

**Comment by Michael-sr** [comment]
+1

**Comment by wschacker** [comment]
+1

**Comment by jmaister** [comment]
If it is as straightforward as extending a React component, it would be easy to contribute to the palette of widgets with third-party widgets from other repositories.

Adding them as plugins on the AppSmith deployment.

**Comment by riodeuno** [comment]
@jmaister We have a [contribution guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/AppsmithWidgetDevelopmentGuide.md), which has a video demonstrating the mechanism in which we can convert a component into an Appsmith Widget.

The process is similar to what you have suggested.

**Comment by Nikhil-Nandagopal** [comment]
Another user on intercom asked about this option

**Comment by UMUTBAYGUT** [comment]
Is there any news about it ?

**Comment by Nikhil-Nandagopal** [comment]
@UMUTBAYGUT we don't have this planned yet. Is there a specific custom widget you're looking to integrate?

**Comment by josh900** [comment]
@Nikhil-Nandagopal , This is a really amazing tool, and we are quickly putting it to use, however, I wanted to mention 1-2 things that would take it to another level for me:
* Any method to edit the underlying code of any appsmith widget, to make modifications to the robust template you provide,
or
* A more robust method of creating custom html/css/js widgets in a page than the current src iframe.

per this issue:
https://community.appsmith.com/t/using-query-in-iframe/561

**Comment by willmartian** [comment]
(Taking some inspiration from prior art, Wordpress custom Gutenberg blocks: https://github.com/WordPress/gutenberg-examples/blob/trunk/01-basic-esnext/src/index.js )

For interoperability, I would want custom widgets to support the usage of custom elements more so than React components. 

Thinking out loud... Given a custom element definition, `myComponent.js`

```ts
import { MyComponent } from "myComponent.js";

defineWidget("My Component", {
  src: MyComponent,
  icon: "myComp.png",
  edit: "<my-component editing>Hello world (in editor)</my-component>",
  save: "<my-component>Hello world</my-component>"
});
```

Thoughts?

**Comment by Nikhil-Nandagopal** [comment]
@willmartian that sounds cool but we're thinking more along the lines of what if we didn't even need to write the code in another IDE and could code the entire widget inside Appsmith? Check out what someone tried to achieve here in an iFrame
https://community.appsmith.com/t/using-query-in-iframe/561
We're wondering how we could improve this experience so we could write the entire component in the browser!

**Comment by Nikhil-Nandagopal** [comment]
@manikumarnune123 could you mention which widget ar you looking to add?

**Comment by Nikhil-Nandagopal** [comment]
@dgorshkov we haven't begun with this yet. Is there a widget you find missing?

**Comment by sxwebster** [comment]
+1 for this. 

Sometimes there are things I want to do with other JS libraries beyond what is available in AppSmith  -eg using something from HighCharts instead of FusionCharts. It would be excellent if I could write a wrapper to include HighCharts and then provide data sources similar to how I would at the moment.

**Comment by pranavkanade** [comment]
@hiteshjoshi @Nikhil-Nandagopal A user is asking for this feature so that they can have a tabulator widget - http://tabulator.info

**Comment by dilippitchika** [comment]
Hello folks, we are going to start work on this soon. I am looking for volunteers who can help us with understanding the problem statement better and what the workflow of your app and this new widget will look like. If anyone is interested in contributing to this project, please feel free to block a slot here - https://calendly.com/dilip_pitchika/30min

**Comment by a10k** [comment]
Also, just a custom HTML block, where we can write some html snippet/use the {{}} to dynamically pass props to a web-component within it, while we add the libraries via script tag should be a great solution.  Or is this already possible in the app somehow and I missed it, please help. Thanks!

**Comment by dilippitchika** [comment]
Hey @a10k what are you trying to do in the custom html block? Can you please help me understand this?

**Comment by Nikhil-Nandagopal** [comment]
@ahmetsevki is there any reason you prefer manually uploading a component over writing the component code inside Appsmith itself as a widget?

**Comment by Nikhil-Nandagopal** [comment]
@ahmetsevki thanks for explaining the reasoning for not wanting the iFrame method. This will help build it better

**Comment by iamenrique** [comment]
In the meantime, can you kindly confirm this guide is still valid and up-to-date? https://github.com/appsmithorg/appsmith/blob/release/contributions/AppsmithWidgetDevelopmentGuide.md

[https://discord.com/channels/725602949748752515/1087821208608845844/1087821208608845844](Reported here as well)

**Comment by riodeuno** [comment]
Hi @iamenrique! Yes, the APIs described in the guide should work. 

We are looking to enhance the guide. So, please do share any suggestions you may have.

You can tag me or @rajatagrawal on GitHub, in case you have any queries when using the APIs described, or widget development in general.

We're also looking to add the property auto complete definitions to this guide, once the relevant changes have been merged into the code base.

**Comment by sbalaji1192** [comment]
Closing this as we have introduced the custom widget on cloud and self hosted instances.

Documentation links:
1. https://docs.appsmith.com/reference/widgets/custom
2. https://docs.appsmith.com/build-apps/how-to-guides/Create-Custom-Widgets-Using-Iframe
