### ISSUE TITLE
[Bug]: Arrango: queries not running and test configuration fails in a particular case

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user configures staging as well through manage env and then changes the environment to prod, the test configuration fails for prod. Also, the queries for both prod and stage cease to run afterwards.

Precondition - default env was prod

### Steps To Reproduce

Steps:

1. keep the env as prod
2. create a new arrango db
3. create query, run query
observe - the test configuration ran fine and queries were also executed

4. Now, configure stage through manage env
5. not change the env to stage

Observe - The test configuration would run fine and the queries are executed.

6. Now, change the env to prod

Observe - The test configuration gives error and both prod and stage queries wont run

### Version

Release v1.9.5

**Comment by ayushpahwa** [comment]
Hey @AnandShahs123 can you also share the credentials you are using and a video. Thanks!

**Comment by AnandShahs123** [comment]
@ayushpahwa - This issue is not happening anymore for me. Might have been fixed as a result of some other fix
