### ISSUE TITLE
[Bug]: Base64 of .pdf and/or .txt not working with Document Viewer

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#20342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I put a data URL of a pdf or txt file as source for the document viewer, the document is not shown. "No document url provided for viewer." is shown instead.

### Steps To Reproduce

1. Drag & Drop Document Viewer widget
2. Encode the pdf or txt file as base64
3. Set under "Document link" of a Document Viewer the following: data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,your base64

### Issue video log

https://bthrujcsw8.vmaker.com/record/62Ug5uzQEqYkwQ7i

### Version

Cloud / Production

**Comment by SvV-CWinJS** [comment]
Hi all
I can tell you that data URL's of pdf's are shown by the Document Viewer in my current version (v.1.9.5) (when formatted as data:application/pdf;base64,data.)

**Comment by chandannkumar** [comment]
Thanks @SvV-CWinJS for the information

**Comment by chandannkumar** [comment]
Closing this issue as it working fine when data is formatted as `data:application/pdf;base64,data`
