### ISSUE TITLE
[Task]: Responsive SORT_CONTROL

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#20340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Design

https://zpl.io/RMjYwZE

### Deploy preview
https://appsmith-dgogj7rpu-get-appsmith.vercel.app/

**Comment by Richarex** [comment]
Tested the changes on different browsers for Gsheet & Appsmith s3 datasources on DP url.
