### ISSUE TITLE
[Bug]: Helm Chart Published AppVersion does not match values.yaml Appsmith image.tag

### ISSUE THREAD

**Issue by atalakey4work** [appsmithorg/appsmith#20346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

AppVersion was removed from Chart.yaml file and in the default values.yaml the appsmith image has a "latest" tag with "IfNotPresent" pull policy. This will result in app not updating to LTS when chart release is upgraded using "helm upgrade".

### Steps To Reproduce

$ helm search repo appsmith
NAME             	        CHART VERSION	APP VERSION	DESCRIPTION                                       
appsmith/appsmith	2.0.0        	         2.0.0      	        Appsmith is an open source framework to build a...

https://github.com/appsmithorg/appsmith/commit/fa800a7704f9439dbd37183079032cb70f7d406a#diff-8119f1901925b84930049084b6beb3c39cec6a1c15ce1fed9242f279d79ddf8cL4
https://github.com/appsmithorg/appsmith/blob/release/deploy/helm/values.yaml#L65

### Version

2.0.0

**Comment by sharat87** [comment]
Hey @atalakey4work, sorry for the delay in getting back on this. Can you elaborate on what the problem here is please? Is the expectation here that a `helm upgrade` should also pull the latest Appsmith image and upgrade Appsmith as well?
