### ISSUE TITLE
Cannot Drag Components up[Bug]

### ISSUE THREAD

**Issue by ioloc** [appsmithorg/appsmith#2035]
## Description

Cannot drag Components upward.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

![issue drag up](https://user-images.githubusercontent.com/67845130/101260328-c7d0a200-3737-11eb-8dca-38e2230c632e.gif)

### Important Details
 - Version: Cloud
 - OS: Windows 10 Enterprise
 - Browser Brave and Chrome

**Comment by Nikhil-Nandagopal** [comment]
@ioloc thank you for reporting this. @riodeuno can you please look into this issue

**Comment by areyabhishek** [comment]
@riodeuno @rishabhsaxena Is this issue fixed?

**Comment by rishabhsaxena** [comment]
This isn't fixed yet. Although we can drag a widget up, if we move the cursor outside the window it doesn't scroll.
We could call it an enhancement instead of a bug.
