### ISSUE TITLE
Support Protected Branches in Git

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#20350]
Allow users to tag protected branches and prevent changes to that branch from Appsmith (either manually or through migration)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_78764)

**Comment by Gabriel-Azevedo** [comment]
Second this. My use case is similar to @metjm. This would be a great way to keep a stable "live" branch and avoid conflict when multiple people use Appsmith.

**Comment by infinitetrooper** [comment]
Thanks for the feedback @Gabriel-Azevedo and @metjm. We're thinking along the same lines, to ensure code security on deployment branches.

**Comment by infinitetrooper** [comment]
This has been released in Appsmith Enterprise `v1.9.46`
