### ISSUE TITLE
[Bug] Email not configured warning is not showing on Forgot Password and Invite Modal

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2036]
## Description
For self hosted instances, we used to show a warning if email was not configured on the instance. This warning is not shown anymore.

### Important Details
 - Version: Self-Hosted v1.2.21
 - OS: All
 - Browser: All

**Comment by rishabhsaxena** [comment]
@hetunandu 
I wasn't able to repro this on both `release` and `master`

![Screenshot from 2020-12-07 13-29-52](https://user-images.githubusercontent.com/1944800/101325007-147bc080-3891-11eb-81ad-cf37f9461ba3.png)

![Screenshot from 2020-12-07 13-30-06](https://user-images.githubusercontent.com/1944800/101325017-18a7de00-3891-11eb-8cb5-ac8128b32c6d.png)

**Comment by mohanarpit** [comment]
@rishabhsaxena If you look at https://release.app.appsmith.com, you'll see that this message doesn't show up. The relevant configuration for that server is: 

```
# ***** Email **********
APPSMITH_MAIL_ENABLED=false
# APPSMITH_MAIL_FROM=
# APPSMITH_REPLY_TO=
# APPSMITH_MAIL_HOST=
# APPSMITH_MAIL_PORT=
# ***** Set to true if providing a TLS port ******
# APPSMITH_MAIL_SMTP_TLS_ENABLED=
# APPSMITH_MAIL_USERNAME=
# APPSMITH_MAIL_PASSWORD=
# APPSMITH_MAIL_SMTP_AUTH=true
# ******************************
```

**Comment by rishabhsaxena** [comment]
yeah still can't reproduce, this is how the config looks
tried rebuilding, not sure if it's needed to rebuild server after env changes

![Screenshot from 2020-12-07 13-46-56](https://user-images.githubusercontent.com/1944800/101326068-bfd94500-3892-11eb-88e6-9ba2952e06c5.png)

**Comment by mohanarpit** [comment]
@rishabhsaxena Your configuration doesn't match the one I posted. Please take a closer look at the `APPSMITH_MAIL_ENABLED` field.

**Comment by mohanarpit** [comment]
@rishabhsaxena Can you restart the server as well? Just to see if it makes any difference. 

Sorry, I deleted my previous message because it wasn't correct.

**Comment by rishabhsaxena** [comment]
yeah tried restart+rebuild 
and both envs, at the project root and the one inside `/server`

![Screenshot from 2020-12-07 13-55-05](https://user-images.githubusercontent.com/1944800/101326813-d2a04980-3893-11eb-8b08-9cd396abf514.png)
