### ISSUE TITLE
[Bug]: RBAC - Multiple Env - Prod and Staging details are not seen separately on DS Review page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I go to DS Review page logging in as a user who has all access on both env, I cannot see Prod and Staging details separately on the Datasource Review page.

### Steps To Reproduce

1. Go to Roles, create a new role say role1, give your workspace full permissions, and give ur DS {say postgres}, full permissions
2. Also for both staging and prod, give all the permissions (Edit/Execute and View)
3. Save and add this role to a new group say group1 and add a new user (user1) to this group.
4. Signup and login as user1, click on the PostGres db from the left panel, to get to the Datasource Review page.
5. Note that user Cannot see prod and staging values separately. 

<img width="987" alt="MultiEnv_ReviewPage" src="https://user-images.githubusercontent.com/101863839/216550287-e61ca711-e03d-4692-9d3b-23f644f466c7.png">

### Version

EC2 instance

**Comment by sondermanish** [comment]
@ayushpahwa could you take a look.
