### ISSUE TITLE
[Bug] Tab widget's tab name updates are not getting saved properly

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2037]
### Steps to reproduce the behaviour:
1. Drop a tabs widget
2. Open the explorer with tab names showing
3. Rename the tabs
4. The old names still remain in the explorer
<img width="1260" alt="Screenshot 2020-12-06 at 11 50 51 PM" src="https://user-images.githubusercontent.com/12022471/101288676-e14c1980-381d-11eb-9974-3f1cb3d081ca.png">

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal 
Can we bump this priority? A user is seeing this and it is also causing his default selected tab to fail

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu why would this cause the default selected tab to fail? According to the description, it only does not rename in the entity explorer and it should get resolved on refresh
