### ISSUE TITLE
[Bug]: Manage env page: Learn more link is missing as per the design.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Learn more link is missing as per the design.

### Steps To Reproduce

Refer to the design screenshot.

<img width="1264" alt="learn more" src="https://user-images.githubusercontent.com/119847783/216591168-47a3a8c9-7639-4472-b079-cd2ea170f8ef.png">

### Version

1.9.5

**Comment by ayushpahwa** [comment]
@sribalajig @parth-appsmith where does this learn more link take the user?
