### ISSUE TITLE
[Bug]: RBAC - ME - user with full rights on Staging cannot see the values of bound variables on edit ds page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I login with a user having full rights on Staging, and full rights on Datasource, but none on Prod, user is not able to see the values of the bound variables on the edit DS page.

### Steps To Reproduce

1. Go to Roles, create a new role say role3, give your workspace full permissions, and give ur DS {say postgres}, full permissions
2. Now only for staging, give all permissions. Do not give any permission for Production
3. Save and add this role to a new group say group3 and add a new user (user3) to this group.
4. Signup and login as user3, click on the PostGres db from the left panel, to get to the Datasource Review page. Go to Edit DS page.
5. Here, User can view bound env variables for Staging but their values are masked. 
Expected behavior - Staging values should be visible to the user.

<img width="486" alt="MultiEnv_FullStagingAccess_Valeusmasked" src="https://user-images.githubusercontent.com/101863839/216621217-4cd3cc87-1de1-45ee-a7e5-d77a96910eac.png">

### Version

EC2 instance

**Comment by sondermanish** [comment]
backend-api sending as expected
