### ISSUE TITLE
[Bug]: RBAC - ME - Bound env variables are visible when user has no view rights on any env

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Edit DS Page - Bound env variables are visible even when user has no view rights on any env

### Steps To Reproduce

1. Go to Roles, create a new role say role2, give your workspace full permissions, and give ur DS {say postgres}, full permissions
2. Now for both staging and prod env, do not give any permissions
3. Save and add this role to a new group say group2 and add a new user (user2) to this group.
4. Signup and login as user2, click on the PostGres db from the left panel, to get to the Datasource Review page [This seems to work fine, no details with regards prod and staging are shown here].
5. Go to Edit DS page. 
6. Here, User can view bound env variables but not their values. 
Expected behaviour - bound env variables also should not be visible as user has no view rights on any env [Refer - [This](https://www.notion.so/appsmith/RBAC-for-environments-52b89549a1c2439593a9312c3f16e035#1ddb48fd4c7b46408378c527bd8184b7) Notion Doc link].
<img width="547" alt="Multienv_BoundVariables_Seen" src="https://user-images.githubusercontent.com/101863839/216580768-afd882d9-afcc-441c-a5fa-7c2ae3a1789a.png">

### Version

EC2 instance

**Comment by sondermanish** [comment]
@Aparna these are environmentVariable names, the variables are marked with **** in the page.

**Comment by sondermanish** [comment]
@sribalajig could you please verify this?

**Comment by sribalajig** [comment]
@btsgh can you please validate this against the RBAC figma.

**Comment by btsgh** [comment]
Right - @sribalajig - Makes sense. Validated against Figma. Since the values are masked anyway, this behavior seems fine
