### ISSUE TITLE
[Bug]: RBAC - ME - Test config gives error unauthorized access when user has no access to any env, but full access to the DS

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I do a test config by logging in as a user with no access to any env but all access to datasources, it fails with un-authorized access error message. 

### Steps To Reproduce

1. Go to Roles, create a new role say role2, give your workspace full permissions, and give ur DS {say postgres}, full permissions
2. Now for both staging and prod env, do not give any permissions
3. Save and add this role to a new group say group2 and add a new user (user2) to this group.
4. Signup and login as user2, click on the PostGres db from the left panel, to get to the Datasource Review page.
5. Go to Edit DS page. Click on Test Configuration button
6. An error pops up to the effect - Unauthorized access.
Test should pass as user has all access to the DS. 

<img width="722" alt="MultiEnv_UnauthorizedAccess" src="https://user-images.githubusercontent.com/101863839/216613255-8436bb81-87b6-4b78-9467-a0f0cde34af1.png">

### Version

EC2 instance

**Comment by btsgh** [comment]
This is still reproducible.

**Comment by sondermanish** [comment]
@sribalajig the user has to have execute access on either environments in order to test the datasource configuration/ execute queries!
Let me know if we think otherwise

**Comment by sribalajig** [comment]
@btsgh this looks like the correct behaviour to me. Let's close this.

**Comment by sondermanish** [comment]
closing the issue as it's as expected
