### ISSUE TITLE
[Feature]: Auto backup of Appsmith instance

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#20381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- Schedule automatic backup of Appsmith instance
- Upload the backup to a bucket storage or NFS

### Why should this be worked on?

Improves reliability/recovery of Appsmith instance.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_78gi4)

**Comment by Nikhil-Nandagopal** [comment]
@sum35h @sharat87 this is a business edition feature right?

**Comment by sum35h** [comment]
Yes @Nikhil-Nandagopal  it's a business edition feature. Should we close this and create this feat issue in the ee repo?

**Comment by sum35h** [comment]
Created an issue in EE repo https://github.com/appsmithorg/appsmith-ee/issues/1171
