### ISSUE TITLE
[Bug]: template fork button hidden on page refresh

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#20387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Template fork button is hidden on page refresh in the editor.

### Steps To Reproduce

1) Create an application/open an existing application
2) Open fork template modal from the canvas cta or page context menu from the explorer.
3) Every template has a `+` fork button visible.
4) Refresh the page and follow steps above from 1 to 2. The button is not visible.

### Version

Cloud/Self hosted

**Comment by Richarex** [comment]
**Test Case 1**
Verify that the user is able to click on the **+** icon on the template card and is redirected to the correct page.
Verify that when the user is on the template card and refreshes the page, after refresh the **+** icon on the template should be visible again.

**Comment by Richarex** [comment]
Verified this issue on the DP url, working as expected.
