### ISSUE TITLE
[Bug]: ME - unable to see correct data for Prod and Staging

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to see correct data for Prod and Staging. Production data was getting shown in staging environment as well. 

### Steps To Reproduce

1. Create a DS say PostGreSQL and configure both prod and staging [one to mockdb and one to amazonaws postgres - https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79#cd6a1610a7e84073b0491cd2c020de4e]
2. Create a query and switch between prod and staging
3. Note that same values come up for both prod and staging
4. This is incorrect behavior. 
Workaround - @sondermanish asked me to rename the datasource, after which this worked.
This issue was not happening earlier. It seems to have cropped up due to some other changes.

### Version

ec2 instance

**Comment by riteshkew** [comment]
Should not be reproducible now considering Manish pushed in a fix.

**Comment by sondermanish** [comment]
not reproducible

**Comment by btsgh** [comment]
Issue seems to have been fixed. Works fine now
