### ISSUE TITLE
[Bug]: Modal's background is missing in deploy mode

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#20405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Modal's background is missing in deployed view

https://www.loom.com/share/48e47ec1502845019cda25e0c5e183ea

### Steps To Reproduce

1. Add a modal to the canvas
2. Deploy the app
3. Notice that the modal's background is missing

### Issue video log

https://www.loom.com/share/48e47ec1502845019cda25e0c5e183ea

### Version

Release

**Comment by kamakshibhat-appsmith** [comment]
@riodeuno to check this 
cc: @somangshu
