### ISSUE TITLE
[Feature]: 在appsmith代码开发当中，使用何种方案可以引入诸如echarts中柱形图那样的图表？

### ISSUE THREAD

**Issue by Merry9** [appsmithorg/appsmith#20417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

为了在appsmith代码开发当中，引入诸如echarts中柱形图那样的图表，我需做什么？引入echarts的库可行吗？

### Why should this be worked on?

为了支持业务，根据后端返回数据绘制柱形图和饼状图，目前低代码没有这个组件功能，因此开发这样的组件或是从外部引入组件并加以改造可行吗？可行的话，大概需要怎么做呢？

**Comment by Nikhil-Nandagopal** [comment]
@Merry9 我们已经使用我们的图表小部件支持条形图、柱形图、饼图和许多其他自定义图表。
https://docs.appsmith.com/reference/widgets/chart

我们现在不支持 EChart，但我们有一个功能请求，可以在此处添加自定义小部件
#2033

**Comment by Merry9** [comment]
> @Merry9 我们已经使用我们的图表小部件支持条形图、柱形图、饼图和许多其他自定义图表。 https://docs.appsmith.com/reference/widgets/chart
> 
> 我们现在不支持 EChart，但我们有一个功能请求，可以在此处添加自定义小部件 #2033

OK ,thank you very much!
