### ISSUE TITLE
[Bug]: Moment does not work when user is not logged in

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#20414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a text box in a list which includes a date created using moment().  This works fine when editing.  It works fine when logged in and viewing.  But when set to Public and not logged in, the user sees a blank box for every item in the list (same number of items as are in the list, just the text is blank.

What is also strange, is the console.log request also does not appear in the console when not logged in.

I have tested it with removing the moment() function and everything works properly.

### Steps To Reproduce

This is simplified for testing and bug reports.

Take a list (this might also work with just a text widget), and include a text widget in it:

`{{currentItem.created_at != undefined ? ericTest.momentTest() + " - "+ currentItem.description  : currentItem}}`

ericTest is:

```
export default {
	momentTest: () => {
		let testResult = moment().format('MM/DD/YY')
		console.log(testResult)
		return testResult
	},

}
```

Deploy the app set to public.

Open the app as a logged in user, everything works.

Open an incognito window and access the app without logging in.  Now the text boxes are blank.

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7b218)

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS thanks for reporting this.

@bharat-patodi @satbir121 could you please have a look at this issue?

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/msg_1misrumk?key=qQkYOdWPC7yzK0p9rNUj8mGkdrsxekZQ) is facing this issue after updating to the latest release.

**Comment by pranavkanade** [comment]
A BE customer faced the same issue. Their app is embedded in an iframe

@bharath31 @satbir121

**Comment by Nikhil-Nandagopal** [comment]
Bumping this to critical since it seems like it broke. 
@bharath31 @satbir121 can we get an RCA for this?

**Comment by bharath31** [comment]
Fixed here: https://github.com/appsmithorg/appsmith-ee/pull/1067
