### ISSUE TITLE
[Bug]: "..." (show more) on list text will break lines mid-text

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#20413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Truncated text boxes will create new lines in the middle of words when the show more button is pressed.

Also there does not appear to be a way to control the properties of the show more modal, such as changing the title from "show more".

### Steps To Reproduce

Create a list
Put a text box in the list
Set overflow text to truncate
Fill it with data longer than the list
See that the "..." option is available
Click the "..." option

See that lines are often split in the middle of words,

### Version

Cloud

**Comment by somangshu** [comment]
Hey @eedwardsSGS, thanks for reporting the issue.

In the show more modal, we use `word-break: break-all;` css property and hence what you are seeing is expected. 
The other request you have is an enhancement. With everything listed above we are going to discuss this internally and get back with any question we have. Post that we will start prioritising the issue

cc @dilippitchika

**Comment by eedwardsSGS** [comment]
@somangshu In the meantime, could you consider swaping `word-break: break-all;` to `word-break: normal;` and `overflow-wrap: break-word;` which would generally keep the text readable?  Otherwise truncate doesn't seem very usable as long as the '...' remains an accessible option.

**Comment by somangshu** [comment]
@eedwardsSGS that sounds like a good suggestion!

@jsartisan what do you say?

**Comment by jsartisan** [comment]
Agreed. `word:-break: break-all` makes the text a little less readable. `word-break: normal` with `overflow-wrap: break-word;` is really a good option.

**Comment by dilippitchika** [comment]
Yeah this should be a really small change for us, we should always follow word-break to be normal and not break-all.
