### ISSUE TITLE
[Bug]: [Auto Layout] Unable to resize using canvas resize indicators when I switch to preview make some change and come back to edit mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#20410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to resize using canvas resize indicators when I switch to preview make some change and come back to edit mode

### Steps To Reproduce

https://www.loom.com/share/ea0343b1f2f347daad9012e22a9f26f7

### Version

DP

**Comment by Sripriya93** [comment]
Working fine, Moving to done.
