### ISSUE TITLE
[Task]: Raise nginx limit to 150 MB to allow base 64 encoded 100 MB files

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#20424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Also check other artificial bounds we have set for server

**Comment by AnandShahs123** [comment]
Tested this by using video, json and pdf files with file sizes of around 100 mb and little more. worked fine.

Got 2 other issues while testing


https://github.com/appsmithorg/appsmith/issues/20800

https://github.com/appsmithorg/appsmith/issues/20798
