### ISSUE TITLE
[Task]: Ensure REST and GraphQL plugins support 100 MB payloads

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#20425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Create test environment for both file uploads
- Test with both binary and base 64 formats

**Comment by AnandShahs123** [comment]
@nidhi-nair For REST API, its showing me the error when I hit the endpoints on appsmith editor, while the same works fine on postman. please find the video screendhot
https://knynrq7fk9.vmaker.com/record/JLy3UT2WumwjU9mG

**Comment by AnandShahs123** [comment]
Currently, its not testable becuase of some ngnix  issue..Large files are not getting uploaded. @nidhi-nair

**Comment by AnandShahs123** [comment]
As discussed with @nidhi-nair this might be becuase of slow response from ngrok or the container is not compatible with APPLE M2

**Comment by AnandShahs123** [comment]
Request is getting cancelled for large files. Please find the video screenshot. Re-opening this issues @nidhi-nair

**Comment by AnandShahs123** [comment]
@nidhi-nair @ayushpahwa both binary and base 64 format for file size around 100 MB is failing
