### ISSUE TITLE
[Bug]: Table widget/Client side Pagination, page number doesn't match with the real data in the table

### ISSUE THREAD

**Issue by done434** [appsmithorg/appsmith#20431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have 2 tables in the page, left table and right table. When I click one row in the left table, the right table will be refreshed to fetch the related data and fill in it.

When there are more than 1 pages in the right table, if navigate to the 2nd page of the table and select another row in the left table, then switch back to the 1st row in the left table, the 2nd page's data in the right table is still shown, but the page number is "1 of 2", not "2 of 2".

### Steps To Reproduce

1. Drag 2 tables to the page, left table and right table.
2. The onRowSelected() function of the left table will trigger a data fetch SQL for right table.
3. Preview the page result.
4. Select the 1st row in the left table, the right table will have 2 pages data shown
5. Click "Next Page" button in the right table, the right table show the 2nd page's data.
6. In the left table, click the 2nd row, the right table switch to another data.
7. In the left table, click the 1st row again, the right table show the correct 2nd page's data, but the page number is "1 of 2", but the correct one should be "2 of 2".

![image](https://user-images.githubusercontent.com/122418547/217220872-68fad031-8b60-4482-82f2-f06bfa6ca402.png)

### Version

Self hosted - 1.8.10

**Comment by Nikhil-Nandagopal** [comment]
@done434 this seems related to #20429
Please update your Appsmith version and don't forget to upgrade to the 1.9.1 and then 1.9.2 check point releases first!
