### ISSUE TITLE
[Bug]: Modal widget does not open when accessed from Navigateto onclick action

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#20439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Drop a Form widget in Page 1
In Page 2 Drop a Modal widget
From Page 1 > For Button widget inside Form widget add onClick action `navigateTo` pass the Modal widget URL 
Click on Submit 

### Steps To Reproduce

1. Drop a Form widget in Page 1
2. In Page 2 Drop a Modal widget
3. From Page 1 > For Button widget inside Form widget add onClick action `navigateTo` pass the Modal widget URL 
4. Click on Submit 

### Issue video log

https://loom.com/share/d545038e07d64f6eb7247da8c1d2743d

### Version

Cloud

**Comment by bharath31** [comment]
isn't this expected because modals are hidden by default? cc: @dilippitchika

**Comment by bharath31** [comment]
this is not related to evaluations/framework functions. removing the tag
