### ISSUE TITLE
[Bug]: On adding a partial evaluation in the table filter, the results being fetched are incorrect

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#20435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding a partial evaluation in the table filter, the results being fetched are incorrect

### Steps To Reproduce

1. D&D a table widget
2. Deploy the app
3. Add a valid condition in the filter 
4. Add a partial condition (without any attributes)
5. Notice that on adding the second filter, the data which is being fetched is incorrect

### Issue video log

https://www.loom.com/share/f051a226e2484f3db350c6e5cc882d28

### Version

Production

**Comment by dilippitchika** [comment]
Not an issue, discussed with laveena
