### ISSUE TITLE
[Bug]: [Fixed layout] Dimensions of widgets is different

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#20444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we measure the widgets are from inside, we are seeing the following differences

### Steps To Reproduce

1. DnD all widgets in full size and measure using any measuring extensions in browser and compare it with the release

Audio
<img width="422" alt="image" src="https://user-images.githubusercontent.com/104895602/217194222-98efb5a7-0dd8-4552-a956-c7e2193fd376.png">

Audio recorder
<img width="326" alt="image" src="https://user-images.githubusercontent.com/104895602/217194156-47fa991d-8904-461b-a8ba-77f6f06ef2fe.png">

Button group
<img width="347" alt="image" src="https://user-images.githubusercontent.com/104895602/217207292-350f31b6-7138-4bd3-af05-f6c847234fa8.png">

Camera
<img width="268" alt="image" src="https://user-images.githubusercontent.com/104895602/217207814-47ab03ba-eab8-448a-812b-961fe2f32922.png">

Category Slider
<img width="455" alt="image" src="https://user-images.githubusercontent.com/104895602/217208727-a3cbce2c-5554-4501-afea-926faf6486d4.png">

Checkbox
<img width="190" alt="image" src="https://user-images.githubusercontent.com/104895602/217213162-98e13ccd-a9e9-4c87-8623-4312d821b20c.png">

Checkbox group
<img width="267" alt="image" src="https://user-images.githubusercontent.com/104895602/217213623-5ac3b973-fa2c-4014-b42f-a47e76587762.png">

Container
<img width="296" alt="image" src="https://user-images.githubusercontent.com/104895602/217214609-7b6a2a5d-932e-4323-a596-61bc8c025c3a.png">

Currency input
<img width="225" alt="image" src="https://user-images.githubusercontent.com/104895602/217219129-81fa89c8-b940-48cb-bc0d-2f2130451c88.png">

Date picker
<img width="221" alt="image" src="https://user-images.githubusercontent.com/104895602/217220402-978a1889-c0b0-4907-be2a-e928765e1bd7.png">

Divider
<img width="223" alt="image" src="https://user-images.githubusercontent.com/104895602/217222633-8e184bda-6dd8-4a3f-8231-8e00a9f82003.png">

Document viewer
<img width="299" alt="image" src="https://user-images.githubusercontent.com/104895602/217223975-fa032710-7e1d-4441-8839-5afdb2b2eb34.png">

File picker
<img width="209" alt="image" src="https://user-images.githubusercontent.com/104895602/217224784-d179ffe6-8661-4ef3-b5a0-5c0b9d2074f5.png">

Icon button
<img width="212" alt="image" src="https://user-images.githubusercontent.com/104895602/217225213-cfc3782b-afc4-47cb-9344-7f23003bddc9.png">

Form
<img width="253" alt="image" src="https://user-images.githubusercontent.com/104895602/217232393-64279bfb-9108-456c-a932-cf3abbe13963.png">

Image
<img width="143" alt="image" src="https://user-images.githubusercontent.com/104895602/217233042-b0e81156-8206-4ba4-90bd-24dea30586bb.png">

Input 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/104895602/217234337-571f242d-ff09-4852-99e1-dff94be92307.png">

JSON form
<img width="328" alt="image" src="https://user-images.githubusercontent.com/104895602/217234772-7895667e-1f8b-4b02-a642-5b8a84343a02.png">

List
<img width="353" alt="image" src="https://user-images.githubusercontent.com/104895602/217236921-37a117e5-8abb-429d-92d7-ebd811ffd4b7.png">

Modal
<img width="454" alt="image" src="https://user-images.githubusercontent.com/104895602/217525785-c915e1d8-23c8-4f30-a316-ea8f22defb57.png">

Multitree select
<img width="222" alt="image" src="https://user-images.githubusercontent.com/104895602/217239601-15d80ad7-bde0-491b-a9d1-d931a22818fb.png">

Multiselect
<img width="247" alt="image" src="https://user-images.githubusercontent.com/104895602/217247708-81014c07-5d34-4d6b-a100-ec7eed3dfbec.png">

Number slider
<img width="401" alt="image" src="https://user-images.githubusercontent.com/104895602/217436911-e706b9c6-63d3-45f0-9929-297bd8059fcf.png">

Phone Input
<img width="220" alt="image" src="https://user-images.githubusercontent.com/104895602/217437437-ea3b47e9-ff16-4347-8a67-a7f9cee54aee.png">

Progress
<img width="304" alt="image" src="https://user-images.githubusercontent.com/104895602/217437809-119dda4a-63d1-434a-95dd-fcdfc814c453.png">

Radio group
<img width="226" alt="image" src="https://user-images.githubusercontent.com/104895602/217437975-831767c2-4e13-48fd-8452-8cf7a2b3eb7f.png">

Range slider
<img width="413" alt="image" src="https://user-images.githubusercontent.com/104895602/217438324-ff6f6f8c-83fd-4976-9651-ba3a0876c8af.png">

Rating
<img width="219" alt="image" src="https://user-images.githubusercontent.com/104895602/217509794-5f377519-ea82-4e44-a7ac-1a754aba1935.png">

Rick text editor
<img width="299" alt="image" src="https://user-images.githubusercontent.com/104895602/217511869-1feb9dc4-fa9f-4c28-9514-ccaf1b2f2aa0.png">

Select
<img width="223" alt="image" src="https://user-images.githubusercontent.com/104895602/217512284-43ddd160-44dd-44cf-9dbe-306f83989192.png">

Stats box
<img width="239" alt="image" src="https://user-images.githubusercontent.com/104895602/217512737-dac1c9a4-f05b-444c-913a-bc91ca96628b.png">

Switch
<img width="164" alt="image" src="https://user-images.githubusercontent.com/104895602/217514130-bd1bc017-51d3-4cac-a638-058a911f2ced.png">

Switch group
<img width="271" alt="image" src="https://user-images.githubusercontent.com/104895602/217519633-f12a5d6a-27ed-4ee9-becd-b0e703c509ad.png">

Table
<img width="392" alt="image" src="https://user-images.githubusercontent.com/104895602/217520144-25f02db4-7c16-4feb-91f3-99892c27449e.png">

Tabs
<img width="287" alt="image" src="https://user-images.githubusercontent.com/104895602/217520843-fbe7e315-dd87-40d7-b55a-a7591aa7fbd0.png">

Text
<img width="227" alt="image" src="https://user-images.githubusercontent.com/104895602/217522682-c718c1da-3e25-42e3-b848-337b7102d61e.png">

Tree select
<img width="217" alt="image" src="https://user-images.githubusercontent.com/104895602/217523804-7c6643cb-9da4-4e23-9024-05ae9112f110.png">

Video
<img width="290" alt="image" src="https://user-images.githubusercontent.com/104895602/217524342-0cefb54d-9675-4307-b996-a84034fa9ea8.png">

### Version

Deploy preview

**Comment by Sripriya93** [comment]
@marks0351 I have checked in the Tablet canvas as discussed but still able to see the difference that are mentioned above, also in Deploy mode we are not able to check the dimensions. We can have a call over this.

**Comment by marks0351** [comment]
@Sripriya93 lets have a discussion around this. If needed we can create a new ticket.
