### ISSUE TITLE
[Bug] Unable to pass an array of values to a where IN operator in queries

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2044]
## Description

The where IN operator in postgres requires each value to be wrapped in a single quote. This is not possible in our mustache bindings because the quotes are meant to be explicit instead of implicit

### Steps to reproduce the behaviour:
1. Drag a dropdown
2. Make it multi select
3. Create a query
4. add a select query to pass multiple options from the dropdown to the where clause
SELECT * FROM public."discord_messages" where msg_id IN ({{fetchDiscordMessages.data.map((message) => { return message.id }).join(',')}}) LIMIT 10;
5. Run the query

The query fails because it expects each message of the IN to be in quotes which is not possible to achieve

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal For now, this is possible via the following query: 

```
SELECT * FROM public."discord_messages" 
where msg_id IN 
(
{{fetchDiscordMessages.data.map((message) => { return "'"+ message.id + "'" }).join(',')}}
) 
LIMIT 10;
```

Let me know if this works.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand can you check if this works with prepared statements?

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : Please use =ANY intead of IN operator to pass arrays. Please find documentation for this here : https://docs.appsmith.com/datasource-reference/querying-postgres#using-arrays-in-prepared-statement
