### ISSUE TITLE
[Bug]: [Fixed and Auto layout] Modal widget is blank

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#20440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we drag and drop a Modal widget it is blank in all places

### Steps To Reproduce

1. Dnd a Modal widget
2. Observe it is blank in fixed and auto layout, in older apps and templates

<img width="519" alt="image" src="https://user-images.githubusercontent.com/104895602/217237271-de0875d8-4118-4616-a106-275b7909a758.png">

### Version

Deploy preview

**Comment by marks0351** [comment]
@Sripriya93 i have given a fix for this. pls check.

**Comment by Sripriya93** [comment]
Modal is working as expected. Moving to done.
