### ISSUE TITLE
[Bug]: Git count at the bottom bar is getting cropped  in Multienv deploy preview

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1440" alt="Screenshot 2023-02-07 at 5 37 37 PM" src="https://user-images.githubusercontent.com/80334441/217242112-f9d40b3f-80c8-47b2-a359-6e5b5170765c.png">

### Steps To Reproduce

1. Connect an app to git
2. Add some widget and refresh
3. Observe bottom bar

### Version

http://13.232.184.172/

**Comment by rohan-arthur** [comment]
top part of the bottom bar is getting clipped
![Screenshot 2023-02-27 at 16 27 21](https://user-images.githubusercontent.com/94514895/221546005-a8e504c3-0994-4f66-83f0-ba80bd5af5f3.png)

**Comment by btsgh** [comment]
This issue seems to be fixed.

**Comment by shadabbuchh** [comment]
> Tagging @shadabbuchh @parth-appsmith to provide more context on this

@btsgh the placement of the `number of changes to commit` seems off in the DP. Might be a padding issue.

**Comment by btsgh** [comment]
Based on the above comment by @shadabbuchh  -  moving it back to in progress

**Comment by btsgh** [comment]
Fixed.
