### ISSUE TITLE
[Bug]: On renaming datasource, the datasource configurations are going away on ME deploy preview

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/217252152-a62793a2-9996-417f-9a15-c3a433cf634e.mov

### Steps To Reproduce

1. Create new mongo datasource
2. Add configurations for staging and prod and save it
3. Rename the datasource and observe

### Version

http://13.232.184.172/

**Comment by sondermanish** [comment]
it is same as task #18027 https://app.zenhub.com/workspaces/data-platform-pod-6322a78c9f446835b89a3f82/issues/gh/appsmithorg/appsmith/18027
