### ISSUE TITLE
[Bug]: Firestore DB - Datasource Review page shows even the service account credentials details. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we get to the DS review page for Firestore DS, it shows even the service account credentials details. This should not be shown as per release behavior. 

### Steps To Reproduce

1. Configure a firestore DB. Details [here](https://docs.google.com/spreadsheets/d/1dP-x8b7gBFOfXtVBwr-A0I4M0nTiJmeysZO2ExI1Hhk/edit#gid=1780194877).
2. Configure both prod and staging env
3. Save the settings. 
4. Note that the Review screen shows even the service account credentials details. This should not be shown.

<img width="986" alt="MultiEnv_Firestore" src="https://user-images.githubusercontent.com/101863839/217241677-95933315-e8e4-4536-a694-6ad5909b1f44.png">

<img width="932" alt="MultiEnvRelease_Firestore" src="https://user-images.githubusercontent.com/101863839/217242273-af5fc31c-aa28-45af-ae9d-b138c3f04317.png">

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
Related to #20510
