### ISSUE TITLE
[Task]: Stop reporting non-actionable errors on Sentry

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#20443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

We're exhausting our Sentry quota every month and missing out on the platform-level errors that need attention. Two main contributing factors: 
1. We are tracking non-actionable user-generated errors like [this one](https://appsmith.sentry.io/issues/3829149627/)
2. We are tracking errors on dev environments _(DP, staging, release, etc...)_ that are not so useful

**Comment by bharath31** [comment]
@arunvjn could you identify more issues like [this](https://appsmith.sentry.io/issues/3829149627/) and prevent them from getting logged on Sentry? 

@pratapaprasanna @sharat87 could we add a config to solve issue#2 mentioned above? Error logs from deploy previews and other development environments need not be logged on Sentry.

**Comment by bharath31** [comment]
@arunvjn @pratapaprasanna @sharat87 bumping this up ICYMI

**Comment by bharath31** [comment]
Issues related to FE Coders pod: 
1. [5P0](https://appsmith.sentry.io/issues/3839650974/?project=1546547&query=is%3Aunresolved+worker&referrer=issue-stream&statsPeriod=14d)
2. [62G](https://appsmith.sentry.io/issues/3928721303/?project=1546547&query=is%3Aunresolved+worker&referrer=issue-stream&statsPeriod=14d)
3. [5RH](https://appsmith.sentry.io/issues/3863160466/?project=1546547&query=is%3Aunresolved+worker&referrer=issue-stream&statsPeriod=14d)
4. [5PV](https://appsmith.sentry.io/issues/3848335912/?project=1546547&query=is%3Aunresolved+worker&referrer=issue-stream&statsPeriod=14d)
5. [5NF](https://appsmith.sentry.io/issues/3831723983/?project=1546547&query=is%3Aunresolved+worker&referrer=issue-stream&statsPeriod=14d)

**Comment by sharat87** [comment]
> could we add a config to solve issue#2 mentioned above? Error logs from deploy previews and other development environments need not be logged on Sentry.

Removed from Vercel deploy previews.
