### ISSUE TITLE
[Bug]: Sidebar doesn't close as expected

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#20450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking on the "Close sidebar" icon in the top left corner, the sidebar doesn't close (video below).

https://user-images.githubusercontent.com/121817440/217281638-b2db7bf1-869c-407e-b2fd-615f046f1fdd.mov

### Steps To Reproduce

1. Click on the "Close sidebar" icon (top left corner)

### Version

v1.9.6

**Comment by kocharrahul7** [comment]
Hey @carinanfonseca, The sidebar is technically closing, but if you move your mouse, it should hide.

This is a UX issue which we are going to solve

**Comment by kocharrahul7** [comment]
Removed this functionality, and closing this issue
