### ISSUE TITLE
[Bug]: Unable to bind values for specific use-case

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#20453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user is trying to maintain the produciton/Staging variable with selected fields bind value is not working

### Steps To Reproduce

1.Login to app.
2.create an app and within that create a DS(Postgres/MYSQL) with host and port.
3.Navigate to manage environment and enter username and password
4.Now try Bind value action

Expected:
Binding should have been successful

Actual:
Error message is seen , refer the video attached

### Issue video log

https://user-images.githubusercontent.com/67676905/217309140-de03c2c5-5aaf-4e56-a964-2184b378bf09.mov

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
Not able to reproduce this @NandanAnantharamu . Can you clear your cache and try once more?
