### ISSUE TITLE
[Bug]: MongoDB: Queries giving blank response if the env selected is stage

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MongoDB: Queries from both environment giving blank response if the env selected is stage

### Steps To Reproduce

Steps:
Assume - Prod being the default env
1. Create new datasource on prod
2. Create a query - Observe - it runs
3. Configure stage
4. Create a query on stage
5. Run the query (env selected should be stage)
Observe - It gives an empty response. Query can be either prod or stage, both gives empty response if env is stage

### Version

1.9.6

**Comment by sondermanish** [comment]
requires re-test

**Comment by AnandShahs123** [comment]
re-tested. happening. Needs to be fixed @sondermanish
