### ISSUE TITLE
[Task]: Move GeoLocation APIs to worker

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#20465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently, geolocation APIs are implemented in such a way that the worker sends a message to the main thread for access to any value, and later on, values are sent back to the worker. 

It is now possible to implement geolocation API in the worker itself which would avoid the communication to the main thread.

**Comment by bharath31** [comment]
@Rishabh-Rathod could you share some estimated performance gains or outcomes for this task?

**Comment by rishabhrathod01** [comment]
This won't be possible as the [WorkerNavigator class](https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator) doesn't have access to geolocation APIs.
