### ISSUE TITLE
[Task]: Track ENTITY_BINDING_SUCCESS 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#20468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem
The `BINDING_SUCCESS` event is set to fire every time a widget property is successfully evaluated. This means that the event will be fired on the trigger of actions like "drag and drop", "page refresh", "widget rename", etc... The data from this event is too noisy to derive actual insights. The original purpose of this event was to track successful bindings triggered by user actions on a widget property. 

### Fix
Track a new event named `WIDGET_BINDING_SUCCESS` on successful evaluation based on a config set on the redux store.
Use this map to track the fields which have successful binding

**Comment by bharath31** [comment]
@ApekshaBhosale @Druthi could we also track the incoming entity type as a part of the event payload? eg:
```
{
"incomingEntityType": JS_OBJECT || WIGET || API || QUERY
}
``` 

here's what I mean by incoming entity: https://www.loom.com/share/4635712e3d8f4e33930f105ee0976534

**Comment by bharath31** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/20468?planning-poker) with Zenhub @Druthi

**Comment by Druthi** [comment]
Done

**Comment by bharath31** [comment]
The event is getting fired on drag and drop of widgets. Loom recording- https://www.loom.com/share/d128db5ee64e4034b71a338e4d532e7b

Ideally the event should only be fired when a user manually adds a successful binding

**Comment by bharath31** [comment]
edit: changed event name to `ENTITY_BINDING_SUCCESS`
