### ISSUE TITLE
[Bug]: Using null coalesce on the property pane shows up as undefined on the evaluated popup

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Null coalease is not recognized on the property pane when left hand operation returns an undefined (as stated by the error message)

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/217331846-d3d92af2-85a5-40cc-92bc-68fce0b89cc2.png)

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore
![Screenshot 2024-08-26 at 15 19 02](https://github.com/user-attachments/assets/ed7de9e8-5b54-42a9-8785-4754eed0ad03)
