### ISSUE TITLE
[Bug]: Mongo: Test config fails for stage for the first time

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MongoDB: Test config fails for the stage for the first time. The user has to again bind the values, then only the test configuration passes.

### Steps To Reproduce

Stopes:

Precondition - Assume prod is default env

1. Create a new mongoDB datasource
2. Test configuration on prod - it pass
3. Now, configure stage through manage env
4. Test configuration on stage -
Observe -  it fails
5. Again, bind values for stage with the existing value
6. Again, test configuration
Observe - it pass

### Version

1.9.6

**Comment by ayushpahwa** [comment]
Will be solved with the fix for #20262
