### ISSUE TITLE
[Bug]: Review screen: The term "Datasource saved" is coming which is not there in the design

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the review page, the term "Datasource saved" is coming after configuring staging which is not consistent with the design.

### Steps To Reproduce

1. Create and save a datasource
2. Configure staging through multiple environment
Observe - On the review page, the term "Datasource saved" is coming unlike the design.

refer to the screenshots attached for both design and the application UI
<img width="1440" alt="datasource saved" src="https://user-images.githubusercontent.com/119847783/217469551-7a31561e-4828-4c65-8eae-124f49a475ab.png">
<img width="1150" alt="design" src="https://user-images.githubusercontent.com/119847783/217469586-1f4ad742-456a-4cfd-9cc7-e2d39e8747e5.png">

### Version

1.9.6

**Comment by ayushpahwa** [comment]
Close it in favour of #20604

**Comment by AnandShahs123** [comment]
@parth-appsmith - Can you confirm?
