### ISSUE TITLE
[Bug]: Postgres: Review page: Only Connection Mode and Database Name fields are coming after configure staging.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For postgres datasource, only two fields with their values i.e Connection Mode and Database Name are coming once the user configures staging.

### Steps To Reproduce

Precondition - Prod is the default selected environment

1. Create a new postgres datasource
2. Configure the following fields - host, port, databaseName, username, password
3. Now, configure staging through Manage env

Observe - On the review page, only Connection Mode and Database Name are coming.

Use the exact below credentials to reproduce

Set 1 -

"Host: mockdb.internal.appsmith.com
Port: 5432
User: postgres
Password: plenty-cape-quality
Database: fakeapi

Set 2 -

"host: postgres-test-db.cz8diybf9wdj.ap-south-1.rds.amazonaws.com
port: 5432
databaseName: fakeapi
username: postgres
password: all-new-password-for-test-db

loom link  - https://www.loom.com/share/5943d3f32b1e4e049cd8dfa4354040d7
<img width="1440" alt="postgres" src="https://user-images.githubusercontent.com/119847783/217482952-0217eebc-cc1f-457a-9dd3-8eb4a4603693.png">

### Issue video log

](https://www.loom.com/share/5943d3f32b1e4e049cd8dfa4354040d7)
### Version

1.9.6

**Comment by ayushpahwa** [comment]
This is a product decision taken earlier. We only show connection related data, not sensitive data like username or password. @sribalajig @parth-appsmith do we want to change this behaviour now?

**Comment by parth-appsmith** [comment]
I agree if displaying information constitutes security leak then that information shouldn't be showing that but with introducing RBAC no user will be able to view this page if they don't have explicit permissions to do so. In case where we show the data like username, host address and etc it will only be visible to users who have the permissions to view it and no one else. RBAC negates the possibility of security leaks.
Also the purpose of the review page of a data source is to provide a view of how the DS is configured, just showing connection mode and data base name doesn't give the complete context. I believe the entire configuration should be shown in this page.

@sribalajig thoughts?

**Comment by AnandShahs123** [comment]
@ayushpahwa - Atleast host address should come as its coming in the release along with connection name and database name

**Comment by ayushpahwa** [comment]
Host name and port not coming, will fix this.

**Comment by AnandShahs123** [comment]
@ayushpahwa re-tested this .. still only connection mode and database name is coming

**Comment by ayushpahwa** [comment]
Will be closed with the fix for #20510
