### ISSUE TITLE
[Feature]: specify a column fixed on the rightmost of datatabl widget

### ISSUE THREAD

**Issue by wengad82** [appsmithorg/appsmith#20481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

can set a column (more often is menu buttons) in the table widget fixed on the left,then if the number of columns is a litter many ,the application user can never drag Horizontal Scroll Bar to rightmost, and click the menu button.
here we usually set menu button on the rightmost of table widget .

### Why should this be worked on?

the application user can never drag Horizontal Scroll Bar to rightmost, and click the menu button.
here we usually set menu button on the rightmost of table widget .

**Comment by dilippitchika** [comment]
@wengad82 we have fixed this in #3265 it should go live next week. Please track that issue.
