### ISSUE TITLE
[Bug]: Datasource listing page: Design is required

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Datasource listing page: Design is required

### Steps To Reproduce

Refer to the screenshot
<img width="1435" alt="listing design" src="https://user-images.githubusercontent.com/119847783/217535213-a1df9bf5-e545-40c8-965b-f1d12e442dd6.png">

### Version

1.9.6

**Comment by parth-appsmith** [comment]
@AnandShahs123 @ayushpahwa please find the designs for the active data sources list [here](https://www.figma.com/file/FC5XY2B57Fu41s0a0Wz93g/Multiple-Environments?node-id=3489%3A281116&t=VwcyKhcCgRTkehB4-4).
I've also uploaded the updated designs on the zeplin handoff file.
