### ISSUE TITLE
Update design of sharing anonymous usage data in Admin Settings

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#20492]
The current design of the toggle to share usage data in Admin Settings is confusing. The proposal is to change it to be similar to the Appsmith Watermark design(check the image below)

**Design**
Anonymous Usage Data

- [ ] Share anonymous usage data to help improve Appsmith

![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/b0c5e67e-b21f-4efe-bd58-a6aa686fee29)

**Comment by 1337ninja** [comment]
@riodeuno can I work on this?

**Comment by Govind783** [comment]
Hey I've updated the design from the toggle button to the check box could you please assign the issue so that I can create a pull request and also whats the process of merging the pull request. and lastly do you want the code in vanialla HTML , css and javascript or react coz I've implemented that in both.
Best Regards,
Govind

**Comment by infinitetrooper** [comment]
Thanks for showing interest 🎉  @Govind783. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Please request us for a review here once you raise a PR.

**Comment by Govind783** [comment]
Hey I've gone through the contribution guidelines. could you please tell me where is the code located, which specific file or folder, the line number

**Comment by infinitetrooper** [comment]
Please check this [file](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/ce/pages/AdminSettings/config/general.tsx)

**Comment by ankitakinger** [comment]
Hey @Govind783, you will have to install the dependencies in the `app/client` folder itself. Could you share the error you are seeing when you run `npm install` in the client folder? Ideally, it should have worked.

**Comment by Govind783** [comment]
hey @ankitakinger I tried running npm install in app/client folder it self it still gives this error. Even tried with --force  still this error persists 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: appsmith@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || 16" from @blueprintjs/select@3.14.2
npm ERR! node_modules/@blueprintjs/select
npm ERR!   @blueprintjs/select@"^3.10.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Govind783** [comment]
hey @infinitetrooper can you look into and suggest me how do i do forward with this

**Comment by ankitakinger** [comment]
@Govind783 Could you use `yarn` instead of `npm install`?

**Comment by Govind783** [comment]
nope tried with yarn as well but did not solve the error :(

**Comment by ankitakinger** [comment]
@Govind783 Since this needs to be fixed soon, I'm going ahead and picking this up. I'm sorry but you can try picking up another low-priority issue and contact us if you face any issues.
Ideally `yarn` should have helped. I'm using `1.22.17` yarn version and it works for me.

**Comment by ankitakinger** [comment]
This is completed now.
