### ISSUE TITLE
[Bug]: Mongo: Review page: Only connection mode and connection type is shown in a certain case

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Mongo: Review page: Only connection mode and connection type is shown in a certain case where is user by mistake configures production again through manage env.

Please note - It has been observed it happens on alternate trails.

### Steps To Reproduce

refer to the loom

### Issue video log

https://www.loom.com/share/865c841fe45a4efd92ef908b3d55a638

### Version

1.9.6

**Comment by ayushpahwa** [comment]
Issue with isHidden logic, this is already with another one of the same bug.

**Comment by ayushpahwa** [comment]
WIll be fixed with #20165
