### ISSUE TITLE
[Bug]: Error message while importing corrupted JSON is not clear 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While importing corrupted JSON file, Resource not found error is thrown, we should show clear error message stating the issue.

### Steps To Reproduce

1. Import corrupted json file.
2. Observe resource not found error is shown.

### Version

https://ce-14939.dp.appsmith.com/

**Comment by AnaghHegde** [comment]
@Parthvi12 This is reproducible on release as well. So this is not a blocker to merge the transaction PR. But we do need to fix this error.

**Comment by AnaghHegde** [comment]
This is an issue from client. We are sending the correct error message but the client is not handling it properly. 
![image](https://user-images.githubusercontent.com/12005551/217888644-76ad3afb-b094-4087-a564-ad436fbce963.png)
