### ISSUE TITLE
[Bug]: Elastic search: Manage env: Host address. There is no validation

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

host address field expects a format - https://aaa.aa . However, in the manage env page for elastic search the user can enter the URL without http or https.

### Steps To Reproduce

1. Create a new elastic search datasource
2. go to manage environment
3. write something like postgres-test-db.cz8diybf9wdj.ap-south-1.rds.amazonaws.com

Observe - The same format is not accepted while create the elastic search datasource. It expects prefix http ot https

### Version

1.9.6

**Comment by ayushpahwa** [comment]
The validations are controlled by server side json forms. @sondermanish can you take a look please.

@AnandShahs123 can you check this behaviour against release and let me know what should be the expected output here? If not should we be picking this up under multiple env?

**Comment by AnandShahs123** [comment]
@ayushpahwa @manish535 On release, there is validation. It should be fixed
