### ISSUE TITLE
[Bug]: If the user deletes the datasource, the manage env page still exists.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Manage environment page is not deleted even after the user deletes the datasource.

### Steps To Reproduce

Refer to the loom video

### Issue video log

https://www.loom.com/share/54f26dc494b04096b41fee24cde2a251

### Version

1.9.6

**Comment by ayushpahwa** [comment]
What should be the behaviour here? @parth-appsmith @sribalajig

**Comment by btsgh** [comment]
Now on deletion of the DS as shown in the above video, with manage env page active, the UI goes to a 404 page. The redirection is not correct, it should take the user to a valid page. [Maybe this needs to be discussed as to where it should land? ] @ayushpahwa @sribalajig
