### ISSUE TITLE
[Bug]: Failed to get JSON data from a MySQL database (Appsmith v1.9.5)

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#20502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MySQL fails to get data in JSON format.

The expected output is:
`{"age": "57", "gender": "Female", "height": "170", "weight": "60", "deviceId": "2153214432145163", "stepLength": "80"}`

The output received is this: 

`eyJhZ2UiOiAiNTciLCAiZ2VuZGVyIjogIkZlbWFsZSIsICJoZWlnaHQiOiAiMTcwIiwgIndlaWdodCI6ICI2MCIsICJkZXZpY2VJZCI6ICIyMTUzMjE0NDMyMTQ1MTYzIiwgInN0ZXBMZW5ndGgiOiAiODAifQ==`

This only happens in self-hosted version 1.9.5.

### Steps To Reproduce

1. Create a table with a JSON data type
```sql
CREATE TABLE FailedDataTest (
  data JSON
);
```

2. Insert a JSON type data

```sql
INSERT INTO FailedDataTest
  (data)
VALUES
  (
   '{"age": "57", "gender": "Female", "height": "170", "weight": "60", "deviceId": "2153214432145163", "stepLength": "80"}'
  );
```

3. execute the select to the created table and see the error (it has to be in a self-hosted version 1.9.5)

```sql
SELECT * FROM FailedDataTest1

```

### Version

Self-Hosted v1.9.5

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7e498)

**Comment by sumitsum** [comment]
Closed in https://github.com/appsmithorg/appsmith/issues/19867
