### ISSUE TITLE
[Bug]: MongoDB: When "Use Mongo Connection String URI" is "No" and the user configures staging, the host address is not shown on the review page

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MongoDB: When "Use Mongo Connection String URI" is "No" and the user configures staging, the host address is not shown on the review page. 

### Steps To Reproduce

1. Create a new mongoDB
2. Select "No" for "Use Mongo Connection String URI"
3. configure staging also. (assume prod was default env)
Observe - host address is not shown on the review page in this case.

<img width="1440" alt="mongo review hostadd missing" src="https://user-images.githubusercontent.com/119847783/217618760-6f6232da-5a60-410e-9f71-1567d12b7db7.png">

### Version

1.9.6

**Comment by ayushpahwa** [comment]
@AnandShahs123 can you check this behaviour against release and let me know what should be the expected output here?

**Comment by AnandShahs123** [comment]
@ayushpahwa have checked this on release. In this case the host address should be shown on the review page

**Comment by ayushpahwa** [comment]
Will be fixed with the solution for #20485
