### ISSUE TITLE
[Bug]: MongoDB: Values from previously created datasource is cached.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user creates and deletes a mongoDB datasources and then again creates a new one, the system remembers the values from the previously deleted datasource.

### Steps To Reproduce

Refer to the loom video

### Issue video log

https://www.loom.com/share/5286c6e9e72c4e50b719187b072216e4

### Version

1.9.6

**Comment by ayushpahwa** [comment]
This seems like a server issue, when the old datasource is being deleted, the env values are still being persisted. @sondermanish can you take a look?

**Comment by AnandShahs123** [comment]
@sondermanish - its still happening

**Comment by AnandShahs123** [comment]
@sondermanish its still happening for me

**Comment by sondermanish** [comment]
moving this bug to low priority. will do another round of rca on this.

**Comment by btsgh** [comment]
@sondermanish - didn't understand your comment above .. I am still able to reproduce the issue. Will there be a fix provided for this?
