### ISSUE TITLE
[Bug]: MySQL: Review page: The user is getting only "connection mode" and "database name" fields.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MySQL: Review page: The user is getting only connection mode and database name fields after the user configures staging also through manage environment.
<img width="1440" alt="MySQL" src="https://user-images.githubusercontent.com/119847783/217709907-11fa02f8-6089-4b2d-b219-56479e912d20.png">

### Steps To Reproduce

Precondition - Assume prod is default env

1. create a new MySQL Datasource.
2. Configure staging through manage env

Observe - Only "connection mode" and "database name" fields are coming

### Issue video log

https://www.loom.com/share/978625dd653a4996a117b54bcd16db8b

### Version

1.9.6

**Comment by ayushpahwa** [comment]
@AnandShahs123 can you check this behaviour against release and let me know what should be the expected output here?

**Comment by AnandShahs123** [comment]
@ayushpahwa - have checked on release. Here, Connection Mode, Host Address and Database Name i.e all 3 of them should come

**Comment by ayushpahwa** [comment]
Will be fixed with the solution for #20485
