### ISSUE TITLE
[Bug] The search in the multi select is not showing

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2051]
### Steps to reproduce the behaviour:
1. Drag a dropdown
2. Convert to multi select
3. Enter text in the multi select to filter options
4. The options get filtered but the text is not visible

**Comment by prapullac** [comment]
reopening the issue as it is not working as expected

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan the search should be cleared once the selection is made

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal I can see the search being cleared on selection. 

![1](https://user-images.githubusercontent.com/6636360/103754425-5a63aa00-5032-11eb-95f0-a59e5e8ea420.gif)

https://app.appsmith.com/applications/5ff584aa53b64c03e83001c4/pages/5ff584aa53b64c03e83001c6

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan strange it seems to be working now!
