### ISSUE TITLE
[Bug]: Firestore: Review page: Service account credentials is being shown.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Firestore: Review page: Service account credentials is being shown.

<img width="1440" alt="firestore" src="https://user-images.githubusercontent.com/119847783/217740227-064f801a-80ef-4e00-af06-a438ac6c3c5d.png">

### Steps To Reproduce

1. Create a new firestore datasource
2. Configure staging
Observe - The user can see "Service account credentials" on the review page

### Version

1.9.6

**Comment by ayushpahwa** [comment]
Will be fixed alongwith #20510
