### ISSUE TITLE
[Bug]: MS SQL Serve : Only Connection mode and Database Name fields are coming on the review page.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Bug]: MS SQL Serve : Only Connection mode and Database Name fields are coming on the review page once the user has configured staging through Manage env

<img width="1439" alt="SQL server" src="https://user-images.githubusercontent.com/119847783/217719444-baca8b8c-c170-464f-8e53-daeb30e2476d.png">

### Steps To Reproduce

1. Create a new MS Sql Server datasource
2. configure staging through manage env
Observe - Only Connection mode and Database Name fields are coming on the review page 

### Version

1.9.6

**Comment by ayushpahwa** [comment]
@AnandShahs123 can you check this behaviour against release and let me know what should be the expected output here?

**Comment by ayushpahwa** [comment]
Will be fixed alongwith #20485
