### ISSUE TITLE
[Feature]: Integration with Glide Data Grid

### ISSUE THREAD

**Issue by ofsantana** [appsmithorg/appsmith#20516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello Appsmith team.
I've been following the Glideapps platform since several months ago, in fact, I got to Appsmith, looking for an open-source alternative to Glide, and I'm delighted that I found you.
But the reason I'm telling you this is that I realize Glide is offering their fantastic table object as Open source: https://github.com/glideapps/glide-data-grid

Do you think it is possible to integrate this object into the Appsmith Platform?

Thank you guys for the amazing job you are doing.
Oscar

### Why should this be worked on?

I think this object can be very useful to work with data, in a very visual way.

**Comment by Nikhil-Nandagopal** [comment]
This is now possible with our custom widget! https://community.appsmith.com/template/data-grid

**Comment by ofsantana** [comment]
Yes, I saw it. Thanks a lot!
