### ISSUE TITLE
[Bug]: Redis: Review page: Hostname and port number missing on review page.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Redis: Review page: Hostname and port number missing on review page once the user configures staging through manage env.

<img width="1364" alt="Redis" src="https://user-images.githubusercontent.com/119847783/217717197-095afcb1-8c8a-42d5-807d-2b4c91a4b590.png">

### Steps To Reproduce

1. Create a new redis datasource
2. Configure staging through manage env
Observe - Both Hostname and port number are missing on the review page

### Version

1.9.6

**Comment by ayushpahwa** [comment]
@AnandShahs123 can you check this behaviour against release and let me know what should be the expected output here?

**Comment by AnandShahs123** [comment]
both should come @ayushpahwa

**Comment by ayushpahwa** [comment]
Will be fixed alongwith #20485
