### ISSUE TITLE
[Bug]: Redshift: Only connection mode and database name is coming on review page

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Redshift: Only connection mode and database name is coming on review page after the user configures staging.

### Steps To Reproduce

Assume rod is default env

1. Create a new redshift datasource
2. Configure staging through manage env

Observe - Only connection mode and database name are coming on the review page.

### Version

1.9.6

**Comment by ayushpahwa** [comment]
Will be fixed alongwith #20485
