### ISSUE TITLE
[Bug]: RBAC - ME : Error message while executing query should be improved, when user has all permissions on datasource but no execute permission on environments 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1440" alt="Screenshot 2023-02-09 at 2 53 46 PM" src="https://user-images.githubusercontent.com/80334441/217773630-64e515d6-be37-4a25-8cdb-4c1dac8d5c43.png">

### Steps To Reproduce

1. Login as admin and create a role with execute permissions for datasource but not for environment 
2. Assign this role to user
3. Login as that user and  execute query
4. Observe the error message is shown which is not very clear

### Version

http://13.232.184.172

**Comment by sondermanish** [comment]
I'll handle this post design discussion with subrata on how to design error messages!
