### ISSUE TITLE
[Bug]: Snowflake: Review page: Staging details coming before production.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Snowflake: Review page: Staging details coming before production.

<img width="1427" alt="SNowflake" src="https://user-images.githubusercontent.com/119847783/217788873-aee96503-c9fe-4780-aad0-f52ba81cd7c5.png">

### Steps To Reproduce

refer to the screenshot

### Version

1.9.6

**Comment by ayushpahwa** [comment]
Displaying the environments as sent by server. Need to add ordering logic from server side. @sondermanish

**Comment by AnandShahs123** [comment]
Resolved
