### ISSUE TITLE
[Bug]: S3: Secret key is showing up on review page.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

S3: Secret key is showing up on review page once the user has configured staging through manage env.

### Steps To Reproduce

1. Create a new S3 datasource
2. Configure staging also

Observe - The secret key is shown on the review page

### Version

1.9.6

**Comment by ayushpahwa** [comment]
Have to add masking from frontend for encrypted or not show them at all.  @sribalajig 

From the server side, need to not send these values or mask them. @sondermanish

**Comment by btsgh** [comment]
This issue still exists. I can see the secret key visible on the Review page. ![MultipleEnvS3SecretKey.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/0debaad0-b4bb-46b3-806b-b0e99c1bf88a)
