### ISSUE TITLE
[Bug]: getting "unable to find valid certification path to requested target" error while running API request.

### ISSUE THREAD

**Issue by junaidtk** [appsmithorg/appsmith#20527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have authentication POST API end points. Where I need to provide username and password as json format. But it is working fine by using the Postman.

But while configuring the API using the Appsmith and running the API. I am getting the error as "unable to find valid certification path to requested target". What will be the exact issue of this. 

Here my appsmith App is running on IP address without SSL. and the API endpoints URL is running on the WordPress which is having the SSL certificate also. 

### Steps To Reproduce

- Configure the API end points in Appsmith by using create new API option.
- Select POST method and pass the json data with username and password.
- Running the API

You will get the error as "unable to find valid certification path to requested target".

### Version

1.7.9

**Comment by sumitsum** [comment]
Hi @junaidtk sorry, the issue description is not clear at the moment. Can you please provide the following info: 
(1) Which Wordpress API were you using and how can we create this API to replicate the issue on our end
(2) Can you please share a screen recording / image showing your config for the API on both Postman and Appsmith ?
