### ISSUE TITLE
[Bug]: Unable to add widgets when switching between pages

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to add widgets from the widgets `+` icon when switching between pages

### Steps To Reproduce

1. Add 3 pages to an app
2. Select widgets tab on one page and switch to the next page and try to click on the plus icon next to widgets and observe, widgets panel does not show up

### Issue video log

https://www.loom.com/share/a89309efd30d494ea127ea5183d2b328

### Version

Cloud

**Comment by kocharrahul7** [comment]
This issue should no longer exist, since we have updated the entity explorer
