### ISSUE TITLE
[Bug] Multi select dropdown stops functioning if default value is undefined

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2052]
### Steps to reproduce the behavior:
1. Drag a dropdown
2. add {{ undefined }} in the default value field
3. Select multi-select option
4. Try to select a value
5. The dropdown doesn't work

### Additional Context
These are simplistic steps, the reason this is an important issue is because if the binding fails due to lack of data it breaks the app during use

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan is this issue resolved? I see the PR merged but it didn't get closed

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal This is resolved. Weird it didn't get closed.
