### ISSUE TITLE
[Bug]: SMTP: The user is not able to bind values. Some error is thrown.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 The user is not able to bind values. Some error is thrown.

Error is - Failure while trying to update env

### Steps To Reproduce

1. Create a new SMTP datasource
2. Configure different values for staging through Manage env
3. Click on bind values

Observe - There is an error toast.

### Issue video log

https://www.loom.com/share/9da0739b798a4f2bb8462163d5828b77

### Version

1.9.6

**Comment by riteshkew** [comment]
Verified from developer's end. Couldn't reproduce. Please verify and close this.

**Comment by AnandShahs123** [comment]
Tried to reproduce. Its still happening for me @riteshkew

**Comment by btsgh** [comment]
SMTP - unable to bind values at all for any env - it does not work. Please take a look .. First attempt itself fails

**Comment by sondermanish** [comment]
fixed with ee-PR  #1125
