### ISSUE TITLE
[Bug]: Arrango: Review page: Only database name is coming

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Arrango: Review page: Only database name is coming after the user has configured the staging through manage env

<img width="1440" alt="Arrango" src="https://user-images.githubusercontent.com/119847783/217791279-b8b44458-6e27-46d8-ab92-2dc486e55d10.png">

### Steps To Reproduce

1. Create an arrango ds
2. Configure staging through manage env

Observe - Only the database name field is coming

### Version

1.9.6

**Comment by riteshkew** [comment]
Verified against Production. As per design. Please verify and close this off.

**Comment by AnandShahs123** [comment]
@riteshkew - I had a re-look. "Host address" and "Port number" should also come along with the "Database name"
