### ISSUE TITLE
[Bug]: Datasource Reconnect Modal for Authenticated Datasource, all setting values are lost on export/import

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#20545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When exporting and importing an app that uses an Authenticated API datasource, the reconnect modal appears but all fields are blank. There are several unencrypted fields that should be retained, like the URL, content-type or accept headers, etc.  

### Steps To Reproduce

A user in Discord is facing this issue:
https://discord.com/channels/725602949748752515/725609493974614076/1073222215182581781

### Version

Appsmith v1.9.7-SNAPSHOT

**Comment by iamenrique** [comment]
Are these unencrypted fields expected to be blank when importing? It this an actual bug?

**Comment by GreenFlux** [comment]
Another user on Discord is facing this issue:
https://discord.com/channels/725602949748752515/725609493974614076/1080185000282038332

@kocharrahul7 @nayan-rafiq @sharat87 this is an issue affecting our templates as well.

**Comment by rohan-arthur** [comment]
@NilanshBansal this needs an [estimate](https://www.notion.so/appsmith/Agile-Estimations-fc322f8fc6784563a4e63c4c66ac4102?pvs=4#7626b21a5fee43508369b465987e9a2b)
