### ISSUE TITLE
[Bug]: ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by forrest-ubic** [appsmithorg/appsmith#20547]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Without an changes to the underlying code, our deployed application no longer can access the Moment() library. Any functions that use Moment() give an error "ReferenceError: moment is not defined". 

Our application is linked to GitHub, and embedded on our Wix site using the embed code provided in the Share menu.

*Note:* This is only present in the deployed site. The same page within the AppSmith editor works fine with the moment library.

### Steps To Reproduce

Create an application that uses any Moment() function. Even just using moment() to get the current date causes this issue.
Publish the site, and embed on a webpage (we are using wix).
Access the published site and trigger the moment() function.

### Version

Cloud Release v1.9.7

**Comment by forrest-ubic** [comment]
Could be related to [https://github.com/appsmithorg/appsmith/issues/20540](url), issue with external libraries in v1.96 - v1.97

**Comment by Nikhil-Nandagopal** [comment]
Hello, we're terribly sorry for the inconvenience. This issue was recently fixed here https://github.com/appsmithorg/appsmith/issues/20414 and will be available in the next release
