### ISSUE TITLE
[Bug]: Templates - Customer messaging tool template gives resource not found error

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I generate page from the Customer messaging tool template - i get a resource not found error

### Steps To Reproduce

1. Login to release
2. Go to an existing app or create a new app
3. Generate a page from template
4. Use Customer Messaging Tool template and try to add selected pages
5. An error comes up - Resource not found

<img width="1308" alt="Screenshot 2023-02-09 at 6 38 16 PM" src="https://user-images.githubusercontent.com/101863839/217824097-7265883c-87e2-4fd7-a634-38521e3ec168.png">

### Version

Release

**Comment by kocharrahul7** [comment]
Resolved by @jacquesikot
