### ISSUE TITLE
[Bug]: UI/ UX: Environment selection popover touching the border line

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

UI/ UX: Environment selection popover touching the border line

### Steps To Reproduce

Refer to the screenshot attached.

<img width="1439" alt="border" src="https://user-images.githubusercontent.com/119847783/217999374-29ae50d3-b4a5-4382-8828-8ca945b2cc28.png">

### Version

1.9.6

**Comment by rohan-arthur** [comment]
expected: [link](https://app.zeplin.io/project/635b8c56ab73a736e7ac7fee/screen/635b93462a26181c7b1b0d92)
![Screenshot 2023-02-27 at 16 29 03](https://user-images.githubusercontent.com/94514895/221546514-1b423466-f993-43d6-ae70-c3f8edf7047e.png)

actual:

![Screenshot 2023-02-27 at 16 29 26](https://user-images.githubusercontent.com/94514895/221546602-03704456-4f71-4f44-b096-d3546d4cdf97.png)

**Comment by ayushpahwa** [comment]
As per @Irongade this will require some inputs from the design system pod. Tagging @albinAppsmith for more info.

**Comment by Irongade** [comment]
@albinAppsmith The DropdownV2 component does not accept the modifiers prop, Hence it would be difficult to pass that into the underlying Popover component within the DropdownV2. The Popover component accepts the modifiers prop, but the one within DropdownV2 currently does not.
