### ISSUE TITLE
[Bug]: On discarding changes for datasources, app is crashing on visiting the datasource on ME deploy preview

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1440" alt="Screenshot 2023-02-09 at 6 04 41 PM" src="https://user-images.githubusercontent.com/80334441/217824633-47dd078e-e91c-47e2-aa65-7ac4946602c4.png">

### Steps To Reproduce

1. Go to this app http://13.232.184.172/app/applicant-tracker/1-track-applications-63e33d9b4c5b880da3a2100c/edit?branch=master&environment=production
2. Go to `test multi env` datasource
3. Observe the app crashes

### Version

 http://13.232.184.172/

**Comment by ayushpahwa** [comment]
Fix published, please verify.
