### ISSUE TITLE
[Bug]: RBAC - ME: Able to edit datasource configurations even with execute permission for datasource and environment 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/217806983-525e691e-4a74-476d-ba13-94ed1f7547fa.mov

### Steps To Reproduce

1. Login as admin and create new role with execute permission for datasource and execute permission for prod env
2. Assign this role to user and go to the datasource
3. Click edit and then manage environment
4. Edit port number and bind values
5. Ideally when there is no edit permission for environment, user should not be able to edit the fields

### Version

http://13.232.184.172/

**Comment by Parthvi12** [comment]
Also, when the env is changed from the Configure Environment dropdown, the toggle on the bottom right is not refreshed to show the same as the configure env selection

**Comment by Parthvi12** [comment]
Now on staging also I am getting unauthorised access when I try to edit, even when I have edit permission for staging.

https://user-images.githubusercontent.com/80334441/218645641-b929a298-c978-4641-84c8-3441deff74a7.mov

**Comment by sondermanish** [comment]
The configure environment Button is probably not working as expected, and all the changes are being made according to bottom dropdown.
@Parthvi12 could you try to saving variable only after switching to the right environment.
@ayushpahwa please take a look on the above issue

**Comment by Parthvi12** [comment]
@sondermanish, After switching env also I am getting unauthorised access when I try to bind values (Here I have edit permission for staging). Could you check?
<img width="1440" alt="Screenshot 2023-02-15 at 3 07 39 PM" src="https://user-images.githubusercontent.com/80334441/218990882-f9131d95-da21-4789-affc-0bbc1fb40672.png">
