### ISSUE TITLE
[Bug]: Canvas and property pane jitters when autocomplete and evaluated value pop-up show up on a binding

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Canvas and property pane jitters when autocomplete and evaluated value pop-up show up on a binding

### Steps To Reproduce

1. Create a binding on any widget field and observe the canvas jitter when autocomplete and evaluated value shows up (checkout attached video for more information)

### Issue video log

https://www.loom.com/share/65374d8094ef4bbaa9a23956fb297d41

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami I doubt this is on production. I see the peek overlay popup at 0:15.

**Comment by bharath31** [comment]
@ramsaptami could we close this since this is not reproducible on production?

**Comment by ramsaptami** [comment]
@bharath31 so this issue still occurs but happens when there's a text widget placed at the bottom of the canvas and displays large data from a binding. On clearing this binding, the canvas jitters

**Comment by bharath31** [comment]
@dilippitchika @somangshu have you seen this canvas jitter issue before?

**Comment by dilippitchika** [comment]
This might be due to auto-height that it jitters. @riodeuno can you please confirm?

**Comment by ramsaptami** [comment]
this is a non-issue on anvil layout system hence closing it
