### ISSUE TITLE
[Bug]: share the application ,click "copy application URL",but no action!

### ISSUE THREAD

**Issue by wengad82** [appsmithorg/appsmith#20574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i share the application ,and click "copy application URL",but copy nothing
![图片](https://user-images.githubusercontent.com/19250813/218259267-6ca14bad-1771-423b-b95c-fd2363867b0c.png)

### Steps To Reproduce

1.Click share on the top right corner
2. check "Make application public" to enable
3. click “copy application URL”
4. the system show no action!

### Version

1.9.6,1.9.7

**Comment by infinitetrooper** [comment]
@wengad82  - Is this issue still happening on your app, we could not reproduce it. 

If possible, can you invite `akhil@appsmith.com` to the app as an App-Viewer, We'd like to debug it. If not, can you please share a screen recording of the issue, thanks.

**Comment by wengad82** [comment]
op recording as following:
1/click share and show the pop diglogue.
2/click  COPY APPLICTION URL,but no action

Is there a problem with my operation?

https://user-images.githubusercontent.com/19250813/223944130-ff33d960-6482-4095-9f1e-e3b2e043334a.mp4

**Comment by infinitetrooper** [comment]
Okay understood, I see the issue now. @ankitakinger  - any ideas on why this issue might be happening?

@wengad82 - Is this issue happening on both Firefox and Chrome browsers?
