### ISSUE TITLE
[Bug]: Library namespace randomly changes to a different name and stops working 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#20572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I install a library and start using it, the namespace randomly changes when I head to the homepage and open the app again. 

Discord user report: https://discord.com/channels/725602949748752515/1072952744509448192

### Steps To Reproduce

1. Install jspdf-autotable by using this URL- https://cdn.jsdelivr.net/npm/jspdf-autotable@3.5.28/dist/jspdf.plugin.autotable.min.js
2. The library gets installed with the namespace `default`
3. Head back to the home page
4. Open the app again
5. See that the library's namespace has now changed to `__createTable`

### Issue video log

Loom recording: https://www.loom.com/share/7cdbcfed7f8e4acb9fb4a81234da80dc

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7dxos)

**Comment by bharath31** [comment]
@arunvjn I remember seeing this issue in an early DP and it was fixed later. Looks like it has regressed. Could you please investigate and fix this?

**Comment by bharath31** [comment]
Update: certain libraries have multiple accessors and we need to handle this edge case.

**Comment by rishabhrathod01** [comment]
The edge case is faced by one of our customers and is a blocker for them. We are re-opening this issue to resolve and unblock them.
