### ISSUE TITLE
[Bug]: Switching between the env change the env location in the dropdown

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#20607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Switching between the env changes the location of the env inside the dropdown
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/218641718-cccc9881-752c-4cf1-afe5-fc97083d4445.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/218641744-060dc0d2-d95a-41db-bd6a-d259b2e9a9ba.png">

### Steps To Reproduce

1. In the edit mode
2. Initially click on Env dropdown 
3. the production will be displayed above followed by stagging
4. Now change the env to stagging
5. the location of the env is changed now stagging displayed above followed by production

### Version

http://13.232.184.172/

**Comment by riteshkew** [comment]
Displaying whatever comes from server side. Need to define ordering from server side. @sondermanish
