### ISSUE TITLE
[Bug]: UI: Alignment of "New Query" button on review page not proper with the "edit" button.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Alignment of "New Query" button on review page not proper with the "edit" button.

<img width="1436" alt="alignment" src="https://user-images.githubusercontent.com/119847783/218632196-00e19b66-d624-4b0c-930e-84586f6c052f.png">

### Steps To Reproduce

Refer to the screenshot from the deployment preview and compare it to the curret release/ prod

### Version

1.9.7

**Comment by ChandanBalajiBP** [comment]
It started with the assumption that it is a small CSS fix, but it turned out to be a little bigger fix. Because the parent is a class component and needs alternate hooks implementation.
