### ISSUE TITLE
[Bug]: Show a lint error when a user is trying to set store using an imperative pattern 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#20618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I store an object using `storeValue()` and try to modify it using `appsmith.store.obj.key = x` the value changes during the current execution cycle and gives a false perception of store modification. 

This should be disallowed and a lint error should be thrown. Lint error: `User storeValue() method to modify the store`

### Steps To Reproduce

1. Write a function to store an object eg: `storeValue("user", user)`
2. Modify the user object by writing `appsmith.store.user.active = true`
3. Read the store and notice that the store is modified `console.log(appsmith.store.user)`
4. Head to a different page on the app or hit refresh 
5. Read the store again and notice the store pointing to the original object `console.log(appsmith.store.user)`

### Version

Cloud

**Comment by bharath31** [comment]
@Rishabh-Rathod could we reuse the lint error logic for imperative assignments on widget properties?

**Comment by Rishabh-Rathod** [comment]
Yes, that logic could be reused here. I will pick this up.

**Comment by ohansFavour** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/27708
