### ISSUE TITLE
[Feature]: Include the Workspace Name in the Appsmith Context Object

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#20621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The Workspace name should be accessible via the Appsmith Context Object.

### Why should this be worked on?

If users have multiple workspaces, they might need to get the name of the workspace for their app.
https://app.frontapp.com/open/msg_1mwxnr4c?key=XoXvMzYD1X2p1QZiD2uakPsoi9HodQuA

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7g9u4)

**Comment by ohansFavour** [comment]
This is closely related to [this](https://github.com/appsmithorg/appsmith/issues/12772). Closing this, and adding this use case in the other issue.
