### ISSUE TITLE
[Feature]: Add support for custom-ca certificates in helm charts

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#20630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

 custom CA root can be added to the ca-certs folder in stacks.

### Why should this be worked on?

This will help in using custom ca root in deploying appsmith which can be further used in various stages of appsmith

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7h364)

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/cnv_18121u4s?key=Ojr5aHnmguRK1lTP0loXaHenKDQcSKmU) requested for this feature.

**Comment by martzinj** [comment]
Hi, we urgently need this feature to be able to import our custom certificates via helm.
Helm is used widely in our company.
A manual solution such as fork, 'kubectl cp' or customization in dockerfiles is not helpful.

**Comment by felixthekraut** [comment]
This would be very helpful to have. We currently have to edit the stateful set's spec in order to mount a secret with the custom certificates.

**Comment by azai91** [comment]
bumping this issue - we want to deploy on kubernetes but we need to be able to pass in cust ca-certs.
