### ISSUE TITLE
[DOCS]: Add options argument for XMLParser library

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#20643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The XMLParser library we use in Appsmith ignores attributes by default. The parse function accepts an options object but this is not easily noticeable by users.

See [query thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1676052948641229)

**Comment by danciaclara** [comment]
@ohansFavour This ticket was missed because itdid not have the documentation tag. Does this still need to be documented?

**Comment by danciaclara** [comment]
Looks like it is added - https://docs.appsmith.com/write-code/reference/Built-in-JS-Libraries#fast-xml-parser
