### ISSUE TITLE
[Bug]: File size is larger in payload than actual

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#20642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The file size in execute request payload is larger than the original size of the file.
This is happening due to the JSON.stringify method.

### Steps To Reproduce

Try to upload a file in binary format to any plugin and verify the size of the payload. (I tried uploading to S3.)
Link to a sample file - https://drive.google.com/file/d/1Hb3VjKuzyrAdRvQCn51iK-8li6DliN_l/view?usp=sharing

### Version

Cloud

**Comment by ChandanBalajiBP** [comment]
Steps to reproduce the error

1. Add a file picker widget 
2. Set format to binary
3. Pick a file (You can use - https://drive.google.com/file/d/1Hb3VjKuzyrAdRvQCn51iK-8li6DliN_l/view?usp=sharing)
4. Upload this file to any plugin (we are using S3)
5. Verify the file length with the content length of the `execute` API request.

For the above file: 
- file size = 93306503 bytes
- execute API content-length = 193704755 bytes
We can observe the difference in size.

Reason 1: 
33% increase in size is expected (for ref: [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Base64))

Reason 2
When we convert the above file to Blob, we are seeing this increase in the size of the content.
The conversion to Blob appears in PluginActionSaga.

**Comment by btsgh** [comment]
Tested on release and found to be fixed in the above scenario. [Orginal file size = 93306503, the execute API content-length shows as 93307784, which is a very miniscule increase]
