### ISSUE TITLE
[Feature]: Allow widget navigation through anchors

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need to support widget navigation through either URL or a widely used method of anchors 

### Why should this be worked on?

**Use Case 1:**
I have 5 containers placed one below another and 5 buttons configured to navigate to specific containers based on user choice

**Use Case 2:** 
I have a form on Page 1 and want to navigate users to a specific section of the canvas on Page 2 based on user response on the form

**Comment by somangshu** [comment]
This can also belong to action selector where the `navigateTo` function address the enhancement requested for

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #8314
