### ISSUE TITLE
[Bug]: [Auto layout][Firefox] Jittering when we scroll thru the page with different widgets

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#20648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we are in firefox browser and in canvas we have multiple widgets in Auto layout, and if we scroll thru the page we are able to see some jittering in the page.

https://user-images.githubusercontent.com/104895602/219284357-3cd50f79-6443-4f8b-a78d-e5dece30080c.mp4

### Steps To Reproduce

1. Go to Firefox browser
2. Drag and drop multiple widget in the canvas in auto layout
3. Scroll thru the page
4. Observe some jitteriness in the widgets when we scroll with the cursor place at the middle of the page

### Version

Deploy preview

**Comment by marks0351** [comment]
@Sripriya93 are we talking about jittering when we use the canvas resizer?

**Comment by Sripriya93** [comment]
@marks0351 My bad uploaded a wrong loom. Please check now!
