### ISSUE TITLE
[Bug]: Unable to Upload File to S3 via FilePicker Widget If App Is Embedded and Served Through HTTP

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#20655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The File Picker widget does not upload files to S3 if embedded and served through HTTP instead of HTTPS - the file upload does not execute. When the webpage is served with SSL, it is working fine.
https://app.frontapp.com/open/msg_1mz4w5zg?key=f6NoPW9RCqhAkxCFrrWjdTlU0M1aTSnI

### Steps To Reproduce

Use a File Picker widget to upload files to S3. Embed the app and serve the webpage through HTTP. Note that the upload does not execute.

### Version

Appsmith v1.9.7-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7h3bg)

**Comment by somangshu** [comment]
This is expected as per the web standards @ame-appsmith. 
An error like 👇 should be visible in the console as well as pointed out [here](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)
> Mixed Content: The page at 'https://example.com/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example2.com/endpoint'. This request has been blocked; the content must be served over HTTPS.

cc @sharat87 can you please help me verify my analysis here. Is this a bug?
