### ISSUE TITLE
[Feature]: Icon Button Style as Binding Property

### ISSUE THREAD

**Issue by yarlanda** [appsmithorg/appsmith#20658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Not Sure if possible but I want to have Icon Button Style to be a binding property.
If that is possible we can set the Icon Style in a dynamic manner through JS Object.

### Why should this be worked on?

I have API Post Request that returns a json object. One field tells me it is in success or error.
I can have a JSObject to read that return field. Based on the output of that field this feature could set the Icon Style.

example:
My Icon widget is called: MyWidget

In my jsobject I would have:

if success:
   MyWidget.Icon = "info-sign"
else:
   MyWidget.Icon = "error"

**Comment by ramsaptami** [comment]
Icon widget's icon already supports this via the JS convertible option
![image](https://github.com/appsmithorg/appsmith/assets/79509062/18a39401-71b5-4bcc-8b2d-8f7c1df290b6)
