### ISSUE TITLE
[Feature] Ability to configure Appsmith user object

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2066]
##Summary
Can access to developer to configure the {{appsmith.user}} object with their own fields from their actions

## Motivation
If the developer has their own ACL set up for users, they can add it to this object and refer to it from anywhere

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu against allowing modifying our internal object. Users with ACL requirements should store that information in the store and access it. Anything less will always lead to object key conflicts
