### ISSUE TITLE
[Bug]: Deleting a page when present on the query page causes an RBAC error to pop up on cloud instance

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Deleting a page when present on the query page causes a GAC error to pop up on cloud instance

![image](https://user-images.githubusercontent.com/79509062/219345456-df03df5d-0e74-4375-bfab-c2e38723f952.png)
![image](https://user-images.githubusercontent.com/79509062/219345593-ed3930aa-58e8-4b8c-86f1-1e96d6279f5c.png)

### Steps To Reproduce

1. Create a CRUD app
2. Navigate to a query page
3. Deleting this page by selecting delete option from the entity explorer as seen in the video and notice the error message for GAC

### Issue video log

https://www.loom.com/share/9931c6551d6349c099fb19a2db2178e5

### Version

Cloud

**Comment by infinitetrooper** [comment]
@ramsaptami - I could not replicate this in `release.app.appsmith.com`, `app.appsmith.com`, release-ee.appsmith.com` and local BE. Is there a particular scenario I need to test? 

Also, can you share the app where this issue happened?

https://user-images.githubusercontent.com/16632903/220038055-57da65e5-48d1-4ed7-98ed-2c907d74f456.mov

**Comment by ramsaptami** [comment]
@infinitetrooper seems you're missing a step here, you'll need to be on a query page when you delete the page. Not from the canvas
I can repro this on prod too
![image](https://user-images.githubusercontent.com/79509062/220067837-399959ce-4bd9-4a69-ba07-ed31fce43ffb.png)

**Comment by infinitetrooper** [comment]
Yes, my bad. This is reproducible on prod. The action is going ahead but, the error is showing up.

@trishaanand @nsarupr - We need to take a look at this. This is medium priority though, a UX issue but, not a blocker to the core flow.
