### ISSUE TITLE
[Task]: Perf - Remove diffing post eval 

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#20684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Reason - 
During the post-eval operation, we take diff between the previously evaluated tree and the currently evaluated tree to apply those changes to redux(evaluate tree). check the below code line - 
https://github.com/appsmithorg/appsmith/blob/713ca6ffc4f84322b8526b66eedd63269fa0cae3/app/client/src/sagas/EvaluationsSaga.ts#L190
Related coneration - https://theappsmith.slack.com/archives/C04PL6T2V5J/p1676444268084839?thread_ts=1676385703.109499&cid=C04PL6T2V5J

Suggested solution - 
Let's not take diff at all. As we have evaluationOrder already and using this let's track paths with it's evaluated values to directly apply changes

**Comment by satbir121** [comment]
@ApekshaBhosale is looking into this issue and figuring out solutions.

**Comment by bharath31** [comment]
@ApekshaBhosale could you please confirm if this still needs to be worked on?

**Comment by rohan-arthur** [comment]
same as #31847
