### ISSUE TITLE
[Bug]: [Canvas Layout] Remove redundant scroll area at the bottom of the MainContainer.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20695]
Objective:
- Main canvas height should not extend beyond the necessary size to render all children.
- Remove excess white space at the bottom.

![Image](https://user-images.githubusercontent.com/5424788/219485302-b9c968bd-c8a7-4ee0-aab2-ff131859b86c.png)

**Comment by rahulramesha** [comment]
This seems to be already fixed

**Comment by Sripriya93** [comment]
No Redundant scroll area seen at the bottom of the main container, working fine in the PR [#20836 ](https://github.com/appsmithorg/appsmith/pull/20836). Moving to done.
