### ISSUE TITLE
[Bug]: [CanvasLayout] Fix scrollbar positioning.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20694]
Objective:
- Remove white space to the right of the canvas.
- Scroll bar should be aligned along the right edge.

![Image](https://user-images.githubusercontent.com/5424788/219484799-926d3050-5c71-4ddb-ac2f-c0a877986d1d.png)

**Comment by Sripriya93** [comment]
The scrollbar is now positioned within the canvas, working as expected in the PR [#20836](https://github.com/appsmithorg/appsmith/pull/20836) , Moving to done.
