### ISSUE TITLE
[Bug]: [Canvas Layout] Remove excess padding at the bottom of the canvas.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20693]
![Image](https://user-images.githubusercontent.com/5424788/219484390-fa16e280-9818-424e-9d49-755c9e398f79.png)

**Comment by marks0351** [comment]
@rahulramesha i think you might have fixed this issue. pls check.

**Comment by Sripriya93** [comment]
Excess padding is not seen at the bottom of the canvas, working as expected in the PR #20836. Moving to done.
