### ISSUE TITLE
[Bug]: [Canvas Resize] Canvas resize handle doesn't stick to the edge of the canvas during resize.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20696]
Resize handle overlaps with the canvas during resize.

Objective:
- Resize handle should stick to the right edge of the canvas during resize.

Check miro board for clarity:
https://miro.com/app/board/uXjVPnDYNkY=/

![Image](https://user-images.githubusercontent.com/5424788/219486473-aa99a942-47ec-463e-b78e-87192b92d90a.png)

**Comment by Sripriya93** [comment]
Resize handle doesn't overlap, working as expected in PR #20836 . Moving to done
