### ISSUE TITLE
[Bug]: [Highlights] Highlights are not rendered in correct positions in deeply nested containers.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20697]
Objective:
- Highlights should be drawn before and after widgets.
- Highlights should be visible in all situations. 

![Image](https://user-images.githubusercontent.com/5424788/219487280-9b3cd7d6-bc12-4d69-b50e-0a8abd65af07.png)

**Comment by prsidhu** [comment]
![Image](https://user-images.githubusercontent.com/5424788/219489504-1525d507-d6f0-46e6-b317-fa5cdae523ce.png)

**Comment by Sripriya93** [comment]
We are able to see highlights hidden under widgets at few more cases

https://user-images.githubusercontent.com/104895602/220892922-d39bd161-960a-45ce-9097-bcfe01bd134a.mp4
