### ISSUE TITLE
[Bug]: [Highlights] Horizontal highlights for Fill widgets are misaligned.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20702]
Objective:
- Horizontal highlights should have equal gap on either side.

![Image](https://user-images.githubusercontent.com/5424788/219489892-936ebd02-206c-4534-9e8d-507e02cf7d86.png)

**Comment by Sripriya93** [comment]
Highlights are horizontally aligned, moving to done.
