### ISSUE TITLE
[Bug]: Excess padding on the right side, within containers.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20705]
There is excess gap on the right side of the container.

Cause:
- Unused alignments continue to occupy 1px width even when all 64 columns are being occupied by others.

Objective:
- Hide unused alignments in AutoLayoutLayer, if all 64 columns are occupied.

![Image](https://user-images.githubusercontent.com/5424788/219492586-4d90d3ee-9380-456f-984e-ee28092f6dc9.png)

**Comment by rohitagarwal88** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mobile-Pod-63be72dba1b2cf00156925f1/issues/appsmithorg/appsmith/20705?planning-poker) with Zenhub @aswathkk @marks0351 @prsidhu @riodeuno @yaldram
