### ISSUE TITLE
[Bug]: Canvas width is not preserved between edit and preview modes.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#20704]
Use case:
- User resizes the canvas to mobile viewport.
- User opens the Preview mode.

Objective:
- Canvas should maintained the width set by the user in the edit mode.

Check miro for more details:
https://miro.com/app/board/uXjVPnDYNkY=/

**Comment by Sripriya93** [comment]
Canvas width is maintained when switching from edit to preview mode. Working as expected in #20836 . moving to done
