### ISSUE TITLE
[Bug]: In deploy mode, for discord bot template(so far ), the UI flickers in the beginning for a split second 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#20711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In deploy mode, for discord bot template(so far ),during page switching the UI flickers in the beginning for a split second which gives poor UX 

### Steps To Reproduce

1. import a discord bot template
2. Clone the same page 
3. Switch between both pages in deploy mode

### Issue video log

https://www.loom.com/share/b5425a55034c4766844439600eb212ed

### Version

Cloud/Release

**Comment by rahulbarwal** [comment]
The issue reported is resolved(by an unknown PR). But we still noticed a flicker in skeleton loader. Created #24661 to track that.
