### ISSUE TITLE
SetInterval - Should show callback function on Pop up window and clearinterval - Add key should be replaced by the added key

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#20739]

**Comment by AnandiKulkarni** [comment]
@ravikp7 this is not fixed for clear interval, cleare interval should show added key

**Comment by arunvjn** [comment]
@AnandiKulkarni https://appsmith-os11uxxpb-get-appsmith.vercel.app/ 
Could you please test this issue in this DP ?
