### ISSUE TITLE
[Bug] Page size and page number do not have a default value

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2073]
When an on load action depends on page size and page number (sql query with the mustache on limit), when triggered, page no and page size are null leading to zero rows being fetched from the query. This leads to the table (on which this action was attached) being empty. 

I tested that if the query is also dependent on search text of the table, and I add a default search text, this value is sent to the server for execution. So even though the widget probably hasn't come up when the action was executed, the default value for search did exist when the on load actions were triggered. This should also be the case for table size and table page number.

This issue is being faced by a user of Appsmith.

**Comment by mohanarpit** [comment]
Closing this as this is not an issue. A table widget's pageNumber defaults to the value 1 during the first page load. On the other hand, `pageSize` for a table widget is calculated dynamically based on the incoming data. On client-side pagination, this number depends on the height of the table widget while for server-side pagination, this depends on the incoming data. Hence, to reduce any confusions, on first page load, the Appsmith framework doesn't expose this information to the user. 

As a user, incase you wish to use the `Table.pageSize` property in an action, please set a default value via the dynamic binding as well. Example below:

```
{
  "pageSizeInAPI": {{ Table1.pageSize || 10 }}
}
```
