### ISSUE TITLE
Black block hover on `+` icon appears wider than the rest of the `+`  icon seen in Entity explorer

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#20731]

**Comment by ravikp7** [comment]
To be checked by Ayushi:
[d6ad4c2b-d6b5-4382-be04-f20a68b9b736.webm](https://user-images.githubusercontent.com/13567359/221494145-7f4aed14-f566-446e-b1ba-fc29288ed530.webm)

**Comment by shwetha-ramesh** [comment]
the `+` icon hover now conforms with other icons
![image](https://user-images.githubusercontent.com/92293815/222682334-714427b1-5289-4fde-87d9-377c9b4bd60e.png)
