### ISSUE TITLE
On Failure is coming after than block

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#20740]

**Comment by arunvjn** [comment]
Fixed in https://appsmith-c5su55jan-get-appsmith.vercel.app/

**Comment by AnandiKulkarni** [comment]
Verified - https://appsmith-c5su55jan-get-appsmith.vercel.app/app/actionrefactor/pag111-63bd4d008c8d557f2f972a3a/edit/widgets/ben9widl2o
