### ISSUE TITLE
[Feature]: currentItem should be available for the styling of list widget items

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#20758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently `currentItem` and `currentIndex` are unavailable when choosing the background color for list widget items. This prevents styling the items based on their item content.

### Why should this be worked on?

Adding this would enable users to style the list items according to the data being displayed in them. This could allow for status to be visible at a glance, brand/theme colors to be used based on content, and generally having more creative freedom for the way our users apps look. This seems like a missed opportunity.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7jgzw)

**Comment by somangshu** [comment]
@Tooluloope can you help evaluate the effort required. Based on that we can decide if its something that should be picked.

**Comment by Tooluloope** [comment]
@somangshu @AS-Laguna This has been handled in the current List V2

**Using `currentIndex`**

<img width="1280" alt="Screenshot 2023-02-20 at 10 08 36" src="https://user-images.githubusercontent.com/31691737/220076014-fcf5d3eb-d023-4d8b-8f34-917eb36888b0.png">

**Using `currentItem`**

<img width="1256" alt="Screenshot 2023-02-20 at 10 09 46" src="https://user-images.githubusercontent.com/31691737/220076023-919e2b17-70f2-430c-b2a8-6adc3e978c8a.png">

**Comment by dilippitchika** [comment]
@AS-Laguna this will be available in the new version of the list we will launch next week
