### ISSUE TITLE
[Bug]:  Update js collections calls are being sent before onPageLoad calls

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#20769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If there is a discrepancy in the backend and the client with respect to js collection, the client makes an update call to correct the values. 
This should take place after all evaluations are done as part of post eval process but in some case encountered this to be happening before on-page load actions are finished delaying entire loading time

### Steps To Reproduce

1. Create an workspace or go to existing one
2. import an app from github with a large JS object or multiple
3. after importing, go to a page which has js object and few on page load actions
4. check network tab, first PUT call for js object happened and then on page load actions got executed

### Version

Cloud

**Comment by Druthi** [comment]
Moving this card to Product backlog as we've encountered some blockers. We need some product discussion on this. 

Explained the issues here https://www.loom.com/share/ee6786b057824e0890214b0a8bc37800
