### ISSUE TITLE
[Bug]: datasource form error message gets garbled on smaller screen/larger zoom level

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#20760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I either increase zoom level or reduce the window size, the datasource form's field validation errors get garbled. Video: 

https://user-images.githubusercontent.com/94514895/219954065-af0ba1f4-f992-46c2-bce6-7063dd10604c.mov

Screenshot
![Screenshot 2023-02-17 at 12 33 40 PM](https://user-images.githubusercontent.com/94514895/219954082-f0701287-a8c0-4d28-b9fb-84ee1ecafbe0.png)

### Steps To Reproduce

1. increase the zoom level to 125%
2. reduce the window width a bit
3. add a new datasource, e.g. elasticsearch
4. enter a wrong url
--> the error message that is shown overlaps the field and is not clear

### Version

Cloud

**Comment by raza001** [comment]
I Think -This issue was"I think the issue has been solved.
`https://www.loom.com/share/479a1e7a7371473b84fdff6a7ad9290f`

**Comment by rohan-arthur** [comment]
thanks @raza001 you're right. This may have gotten fixed with some other issue. I am closing this one.
