### ISSUE TITLE
[Bug]: OAuth- In the Manage environments window of OAuth DS, the Input Field dropdown has a few options missing

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Manage environments window of OAuth DS, the Input Field dropdown has a few options missing

### Steps To Reproduce

1. Create an OAuth DS and Save it. Edit and go to Manage Env
2. Here note the Input Field Dropdown, some of the options are missing - 

-Headers
-Query Parameters
-Authentication Type
-Client Authentication
-Authorization URL
-Redirect URL
-Custom Authorization parameters
-Use Self-signed parameters

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
Authentication type and grant type had to be removed due to server constraints. Have added the rest, please check @btsgh

**Comment by btsgh** [comment]
Yes - Authentication Type and Grant type are not available. 
However, I don't see Headers, Query Parameters, Client Authentication, Redirect URL, Custom Authentication Parameters, 
If we choose use self signed certificates, Upload certificate field has to come up where we need to be able to select a cert file. This field is not present
