### ISSUE TITLE
[Bug]: OAuth- In the Manage environments window of OAuth DS, the Input Field dropdown gets cutoff. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Manage environments window of OAuth DS, the Input Field dropdown gets cutoff. 

### Steps To Reproduce

1. Create an OAuth DS and Save it. Edit and go to Manage Env
2. Here note the Input Field Dropdown - its getting cutoff

![MultipleenvOAuth](https://user-images.githubusercontent.com/101863839/220027723-4e69ab60-d343-4344-8e78-da7e2c3e70e6.jpeg)

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
Hmmm, not sure how to tackle this. The list for authenticated API is quite large.

**Comment by btsgh** [comment]
This is fixed in the latest instance

**Comment by btsgh** [comment]
Actually - Still able to reproduce it :( when I start adding the fields and the dropdown moves further down on the screen, the dropdown gets cutoff

**Comment by btsgh** [comment]
Actually - Still able to reproduce it :( when I start adding the fields and the dropdown moves further down on the screen, the dropdown gets cutoff

**Comment by ayushpahwa** [comment]
This will require design system intervention, the dropdown is just too big. @albinAppsmith can you please help here.

**Comment by albinAppsmith** [comment]
@ayushpahwa is it possible for you to make a fixed height to dropdown and make it scroll? Will that resolve your issue?
