### ISSUE TITLE
[Bug]: OAuth - As per zeplin - for the Authentication type as OAuth2.0, the manage env page is not matching

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 For OAuth DS - As per zeplin - for the Authentication type as OAuth2.0, the manage env page is not matching

### Steps To Reproduce

1. Create an OAuth DS. Save the DS. Go to Manage Env page
2. The UI for the fields here is not as per Zeplin. 
3. As per Zeplin -  When OAuth2.0 is selected as Authentication type, The fields associated with OAuth2.0 appear slightly tabbed to the right to indicate that they are Associated with Authentication Type.
4. Also, for each of the bound value representation is represented in the format "dsname.authentication_type.field_name"
5. At present, in the DP, the above format is not followed. It is only represented as "dsname.field_name"
6. Also there is no Authentication Type field available for selection at all

View zeplin screenshot below - 

![MultiEnvAuthType_representation](https://user-images.githubusercontent.com/101863839/220052575-25509d59-aed1-4f20-afd9-9ffae46a0e98.jpeg)

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
THis is done due to server restrictions. Let's connect and discuss further on this.
