### ISSUE TITLE
Pop up moves on scroll

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#20783]
https://www.loom.com/share/675176b03b4047c3a4bc6d51bbb26d27

**Comment by shwetha-ramesh** [comment]
@rimildeyjsr https://www.loom.com/share/675176b03b4047c3a4bc6d51bbb26d27

**Comment by arunvjn** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/19689/commits/cbecf3bbfc6e1ed9e7ddde3a48dad3a61a04376c

**Comment by arunvjn** [comment]
Fixed in https://appsmith-bnl4i9ht4-get-appsmith.vercel.app/

**Comment by rimildeyjsr** [comment]
Blocked on the design system pod

**Comment by ohansFavour** [comment]
@AnandiKulkarni can you kindly confirm that this is fixed?

**Comment by bharath31** [comment]
@rimildeyjsr is this fixed now?

**Comment by bharath31** [comment]
this is fixed on release
