### ISSUE TITLE
[Bug]: Double clicking a table row deselects the row

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#20808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Double clicking a table row selects and deselects the row. The proposed behaviour should be that no matter the amount of time the row is clicked it should remain selected

### Steps To Reproduce

1. Create a table
2. Double click a row in the table

### Version

Cloud & Self - Hosted 1.9.7

**Comment by keyurparalkar** [comment]
@dilippitchika is this a valid issue? How will the user deselect a row?
