### ISSUE TITLE
[Bug]: OAuth - Manage Environments - unable to bind values on adding a couple of fields and trying

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a couple of fields to the already existing bound values and try to bind the values, the binding fails with an error.

### Steps To Reproduce

1. Create an OAuth DS. Save. Go to Manage Environments
2. Add Grant Type, Add Access Token To, Header Prefix, Access Token URL, Client Id, Client Secret, Scope. 
3. Bind Values
4. Now again go to Manage Environments and add Send Scope with Refresh Token, Send Client Credentials with () and bind these fields also
5. Note an error pops up to the effect. - Error Updating Environment Variables

![MultipleEnv_ErrorUpdatingEnvVari](https://user-images.githubusercontent.com/101863839/220259442-25433862-56cf-4802-a040-177e008fbf5e.jpeg)

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
Please remove grant type. I have also removed the ability to add it now since it was a server restraint for now. @btsgh please let me know if you are still seeing this, couldn't reproduce it.

**Comment by btsgh** [comment]
Still able to reproduce this - inconsistently though. Unable to bind values at times.  Sometimes I get the message unable to bind values, and sometimes I get the error something went wrong. Suggest leaving this open till we are sure its not occuring anymore

**Comment by ayushpahwa** [comment]
This is resolved now, was happening since BE doesn't recognize isSendSession the same way it is shown. Please let me know if you face this again.
