### ISSUE TITLE
[Bug]: Cannot upgrade beyond 1.8.5 on ARM due to MongoDB 5

### ISSUE THREAD

**Issue by arminus** [appsmithorg/appsmith#20818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Docker appsmith-ce images don't work on Raspberry PI/ARM64 platforms since > 1.8.5 because the MongoDB included in that images crashes, resulting in a 503 for the appsmith server.

See also https://community.appsmith.com/t/cannot-update-docker-single-image-past-v1-8-15

At the [end of this post](https://community.appsmith.com/t/cannot-update-docker-single-image-past-v1-8-15/1912/6?u=arminus), I pointed out a possible solution which would require to pull a working MongoDB image from [here](https://andyfelong.com/2021/08/mongodb-4-4-under-raspberry-pi-os-64-bit-raspbian64/#comment-355013) or [here](https://codeberg.org/samsamros/mongodb-raspberry-pi4) into the appsmith-ce arm image instead of the non working 5.x.

### Steps To Reproduce

Pull and run any newer appsmith-ce/arm image on a RaspberryPi.

### Version

Self Hosted 1.8.5

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 could you evaluate whether this would work?

**Comment by sharat87** [comment]
@arminus, thank you for sharing this.

There's two points of note here. This method of installing MongoDB v5 is unofficial. The best binaries also not hosted by MongoDB's official website. So, I'm not very confident in including links to a binary, taken from a third-party website.

Secondly, the official instructions for running MongoDB on Raspberry Pi, at https://www.mongodb.com/developer/products/mongodb/mongodb-on-raspberry-pi/, only talk about MongoDB v4.4. But Appsmith today, requires MongoDB v5, and is only tested with MongoDB v5.

Considering the above two points, if you wish to run Appsmith on a Raspberry Pi, please use an external MongoDB. There's a generous free tier on MongoDB Atlas that should serve well for small workloads very well. Learn more about how to configure a custom MongoDB at https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-mongodb-redis#custom-mongodb.

Thank you!

**Comment by arminus** [comment]
Thanks for the response, I understand the reasoning of you guys not being able to include "unofficial binaries".

I did follow up on your suggestion to use an external MongoDB but I'm not succeeding yet. See [here](https://github.com/arminus/appsmith-docker/issues/1) and [here](https://community.appsmith.com/t/appsmith-does-not-connect-to-external-mongodb-exited-with-code-132/2072).
