### ISSUE TITLE
[Bug]: Table has additional rows even when content can fit

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#20831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i add a new table widget and configure data, I see more data than what fits in the table, thus introducing an additional scroll on it.

### Steps To Reproduce

1. Add a new table widget
2. Bind the users db to it using, {{Table1.pageSize}}
3. Observe the data exceeds the pagesize and scroll is visible

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_96c0c)

**Comment by Gabriel-Azevedo** [comment]
+1
