### ISSUE TITLE
Using slash command causes `/` to be inserted into the syntax and UI stops working

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#20847]
https://www.loom.com/share/0fd48561872e4763bde15230c4bccf16

**Comment by shwetha-ramesh** [comment]
When user clicks on / command and selects `insert snippet`. The pop up still remains in the background
![image.png](https://images.zenhubusercontent.com/616d4fa2500f63423c16eb15/406d54ef-914f-440b-9230-987d7881c78a)

**Comment by shwetha-ramesh** [comment]
Pop up shuts when evaluated value example is minimized
https://www.loom.com/share/b2cc3d8a0134476f85c002304f9529c9

**Comment by arunvjn** [comment]
Fixed in https://appsmith-jyazwicii-get-appsmith.vercel.app

**Comment by shwetha-ramesh** [comment]
Working as expected, moving to Done
