### ISSUE TITLE
[Bug]: Uncommitted changes and progress bar doesnt come up in git sync modal on committing and pushing changes related to theme

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/220542001-9726d897-880a-4df9-9f03-7d2ed97f38bb.mov

### Steps To Reproduce

1. Create an app and connect it to git
2. Change theme and commit changes
3. Observe uncommitted changes are not shown and progress bar doesn't come up

### Version

Release

**Comment by somangshu** [comment]
This is probably an ADS component that is not appearing. cc @albinAppsmith @tanvibhakta 

also @Parthvi12 I dont think theming would apply to any ADS components, Only branding has could have some effect here, for that I would ask @jsartisan @dilippitchika if you think this component should inherit some branding value and if its a similar problem we noticed on the deploy button.
