### ISSUE TITLE
[Bug]: After discarding changes, git sync modal still shows changes to commit.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/220544502-77c0b843-ab44-4fd8-8e42-36189046ad76.mov

### Steps To Reproduce

1. Go to this app https://release.app.appsmith.com/app/bug10773/page1-624064976c86dd5be6fdd2d2/edit?branch=main , discard changes and observe.

Git repository : https://github.com/Parthvi12/GitTests

### Version

Release

**Comment by AnaghHegde** [comment]
@Parthvi12 Can you commit the changes and confirm if the changes are not because of the migration?

**Comment by Parthvi12** [comment]
@AnaghHegde This is the commit.
<img width="1440" alt="Screenshot 2023-02-22 at 2 06 18 PM" src="https://user-images.githubusercontent.com/80334441/220566450-af5a74ff-b7c5-48f6-a04a-6e90b542dc79.png">

**Comment by AnaghHegde** [comment]
This is a migration change. As you can see in the canvas.json the version field is updated with the latest.
