### ISSUE TITLE
[Bug]: Error Toast just when onboarding tour starts

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#20852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I noticed that an error toast pops up right when the onboarding process starts (happens intermittently), and I believe this could potentially set users' expectations low and result in a drop in conversion rates.

As a user, I felt slightly discouraged when I saw the error message, and it made me wonder if the rest of the process would be difficult or prone to errors. This could potentially lead some users to abandon the process altogether, reducing the number of successful conversions.

I’d reconsider putting retries of function execution with load on screen till its done right to avoid setting negative expectations at the start of the onboarding process. By doing so, users will be more likely to remain engaged and feel positive about the experience, leading to a higher conversion rate.

<img width="1000" alt="download" src="https://user-images.githubusercontent.com/8299030/220535444-7b181c0d-8338-4cc6-87a6-ad29ac2d4a7e.png">

### Steps To Reproduce

Noticed that an error toast pops up right when the onboarding process starts (happens intermittently)

### Version

Cloud

**Comment by akash-codemonk** [comment]
On page load actions seems to be failing, even though the query runs successfully when executing it from the query pane. Have been able to repro in a new application. 
Will confirm with more testing and create a separate issue for this.

**Comment by akash-codemonk** [comment]
Working fine now.
