### ISSUE TITLE
[Bug]: Fix JS arguments labels not showing up in action selector

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#20851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Action selector, the labels for arguments for functions in js objects are not getting shown

### Steps To Reproduce

Open any jsobj function in action selector - you can see the issue

### Version

1.6.6

**Comment by AnandiKulkarni** [comment]
Verified on https://appsmith-bnl4i9ht4-get-appsmith.vercel.app/app/actionrefactor/pag111-63bd4d008c8d557f2f972a3a/edit/widgets/35rv4yed53
