### ISSUE TITLE
[Feature] Simplify table pagination when connected to a query/API

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#2086]
## Summary

We need to simplify the process of server-side pagination in the Table widget. Today it's fairly convoluted and not easy to understand for a user.

## Motivation

In order to enable server-side pagination, a user must:
1. Go to pagination settings and define the next/prev URLs (for URL based pagination). Alternatively, they need to bind `Table.pageNo` to their API or query. 
2. In the Table widget, they need to enable "Server-side pagination"
3. In the Table widget's property, they need to configure the API in the `onPageChange` field.

These are too many steps for a common use-case. 

Instead, we should configure the `onPageChange` property when the "Server side pagination" property is set in the property pane. The `onPageChange` property should call the same API/JS function that was used to populate the data in the table in the first place. This way, the user can eliminate 1 step in the process. 

Taking it one step further, we should enable the "Server side pagination" property in the table when the user configures the pagination setting in the API/Query.

**Comment by Nikhil-Nandagopal** [comment]
## More Details
To simplify the process of server-side pagination
On the creation of an API, the pagination tab will prompt a user to select a table to paginate. If no table is present, the user can add a table from here

### Creating a new Table
This will add a new table on the canvas while the user is still on the API pane. Closing the API pane will land the user on the table created without needing to scroll

### Selecting a Table
Selecting a table enables server-side pagination for that table and displays information to the user on how to paginate the API

### Pagination with Table PageNo
The information here will inform users on how to bind the Table.pageNo to the API with an example pageNo={{Table1.pageNo}}

### Pagination with Response URL
The information here will inform users on how to bind the response of the current API to the Previous & Next fields

**Comment by areyabhishek** [comment]
![Uploading API pagination.jpg…]()
