### ISSUE TITLE
[Bug]: Appsmith shouldn't attempt to STARTTLS if TLS is disabled in the config.

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#20884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When starting a server that has TLS disabled in the config, it will attempt STARTTLS anyway.

I expect the server to not try STARTTLS if TLS is disabled.

### Steps To Reproduce

1. Disable TLS in your instance config.
2. Start your instance and watch the logs.
3. Observer that STARTTLS is logged anyway.

### Version

1.9.7

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7mmfg)

**Comment by degude** [comment]
I think what could solve this is to try the following:
In [EnvManagerCEImpl.java](https://github.com/appsmithorg/appsmith/blob/92a60f775f46b1acf1507ff4504f81f46998143f/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java#L701) around line 700 to move the line `props.put("mail.smtp.starttls.enable", "true");` into the following if-else clause.

```
Properties props = mailSender.getJavaMailProperties();
props.put("mail.transport.protocol", "smtp");
props.put("mail.smtp.timeout", 7000); // 7 seconds

if (StringUtils.hasLength(requestDTO.getUsername())) {
    props.put("mail.smtp.starttls.enable", "true");
    props.put("mail.smtp.auth", "true");
    mailSender.setUsername(requestDTO.getUsername());
    mailSender.setPassword(requestDTO.getPassword());
} else {
    props.put("mail.smtp.starttls.enable", "false");
    props.put("mail.smtp.auth", "false");
}
props.put("mail.debug", "true");
```

This way **starttls** is only `true` when the TLS option is checked in the test mail form.

**Comment by sharat87** [comment]
@degude, indeed. Thanks for suggesting. We actually have a PR regarding that at #17952, but that was doing a little too much, which was causing problems in merging. I think I'll tone that PR back and _only_ solve this one problem so it can finally go in.

I'll take this up. Thanks!

**Comment by degude** [comment]
It works like a charm now, thank you guys ❤️
