### ISSUE TITLE
[Bug]: 404 Resources not found Error When Accessing GitHub Branch

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#20883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user created a new GitHub branch, made some additions there, then could not access the branch, getting a `404 Resources not found` error. They tried to create a new branch and re-do the changes, after which they received an `404` error again. However, a new branch with no modifications is accessible and works fine.
For more info, check [the screen recording of the bug](https://app.frontapp.com/open/msg_1n1wzt70?key=3LVIt08b-wLEmMihsgii8ynh5SA4qLiB) from the Front thread.

### Steps To Reproduce

1. In an app that is connected to Git and has 3 pages (page #1 is the home page), create a new GitHub branch from master.
2. In the new branch, set page #2 as home page, then delete page #1.
3. Commit the changes.
4. Leave the workspace.
5. Re-access the app in edit mode, then try to access the new branch created in step #1. 
You will get the error `404 Resources not found`.

### Version

Appsmith self-hosted

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7mlos)

**Comment by AnaghHegde** [comment]
Mom with @nayan-rafiq 
1. Behaviour of the product should not change.  Example, 404 should be thrown when the page is not accessible

2. When a user is switching the branch the user is interested in accessing the resources inside the branch and not is a specific page or any other resources per se

3. The existing API has support for accepting the applicationId and branchName and we can use this to fix the behaviour reported in the bug

4. We should have a discussion with someone from FE to make this change happen on the switch branch CTA. 

cc - @infinitetrooper

**Comment by infinitetrooper** [comment]
@AnaghHegde  - Is the way forward to redirect to the homepage when the branch is switched if the active page is not presented in the checked-out branch?

As you mentioned that user is looking for resources in a branch and is not necessarily on the same page across branches.

**Comment by AnaghHegde** [comment]
@infinitetrooper We have to redirect the user to the default page of the chosen branch. It can be the same page or a different page.

**Comment by infinitetrooper** [comment]
> @infinitetrooper We have to redirect the user to the default page of the chosen branch. It can be the same page or a different page.

If the same page exists in both branches, the user will still be on the same page when switching between branches right? We redirect the user to the default/homepage only if the page the user is on is deleted in the chosen branch.

**Comment by AnaghHegde** [comment]
@infinitetrooper Yes, that is correct. I believe it should be possible. This has a FE dependency and I can confirm after talking to someone from the team.
