### ISSUE TITLE
[Feature]: Allow Image() and document.createElement('canvas')

### ISSUE THREAD

**Issue by dncpax** [appsmithorg/appsmith#20882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

These days it's possible to resize images in the browser using js. This requires use of Image and Canvas which are sandboxed by appsmith.
Consequently, to resize images we have to use external APIs, when there is really no need.

### Why should this be worked on?

One use case is to upload images to a database and create the thumbnail on the fly in the browser. 
Another is to list a collection of images that cause a laggy experience in appsmith. Creating thumbnails in the browser is very fast, and would make listings smoother by showing these instead of the originals.
Another use case is to show cropped images with no need of 3rd party APIs. For instance, before uploading images we can crop them to the correct size.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7mjyk)

**Comment by jancoow** [comment]
I'm also encountering this issue. I need to crop an image, but I'm unable to do so because I cannot use the new Image() constructor. I'm not sure why this is sandboxed.

**Comment by Nikhil-Nandagopal** [comment]
Document access has been restricted due to security issues. What I can suggest here is to use the custom widget with a library that supports image cropping to achieve this
