### ISSUE TITLE
[Feature]: datasource variable for queries

### ISSUE THREAD

**Issue by taylorbrosnan** [appsmithorg/appsmith#20887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I want to create a singly query that can work with multiple datasources. The query should take a variable that AppSmith can change based on, for example, a value from a selection box.

### Why should this be worked on?

We have 50+ tenants that we would like to connect to our appserver. This is generating a massive number of datasources since we have prod and beta GQL API connections for each tenant coming in. Writing an identical query for each datasource is very painful.

**Comment by Nikhil-Nandagopal** [comment]
@taylorbrosnan you can write bindings in the GQL API datasource and it should work although autocomplete support is not there
