### ISSUE TITLE
[Bug]: The look and feel of cancel and delete buttons are different

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Delete is having borders, while cancel doesn't

### Steps To Reproduce

for delete:

1. create a datasource
2. click on edit

for cancel

1. create a datasource
2. edit
3. go to manage environments

### Version

1.9.8

**Comment by ayushpahwa** [comment]
This is controlled by the plugin json in the server. @sondermanish can you change the `datasourceButtonConfiguration` in the plugins. Just replace the DELETE with CANCEL

**Comment by btsgh** [comment]
Both are now Cancel. However, Cancel still has a border on the Edit DS page and has no border on the Manage Env page.
![cencelbutton1.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/29303f28-1e14-4902-8ad6-23ea849ec301)
![cancelbutton2.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/2e5a484d-3b26-4166-a1ea-5db1360638a0)

**Comment by prapullac** [comment]
The issue still exist on the DP hence moving it to IN Progress![Screenshot 2023-03-21 at 2.54.54 PM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/d54dc107-de49-491b-b83a-989ddc6bf5f3)
