### ISSUE TITLE
[Bug]: RBAC - ME - No icons present for Production and Staging on RBAC.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In RBAC - there are no icons in the RBAC screens for Staging and Production.

### Steps To Reproduce

1. Login as instance admin and go to admin settings
2. Go to the Roles tab
3. Here, in the Datasources and Queries tab, expand your workspace, expand the Environments option
4. Here note that there are no icons for Production and Staging. Also Production and Staging start with small letters
[[Figma](https://www.figma.com/file/FC5XY2B57Fu41s0a0Wz93g/Multiple-Environments?node-id=3290%3A270772&t=zotd9gUfDPF5Qga8-0) reference]

![icons](https://user-images.githubusercontent.com/101863839/220889339-fba406e2-b4b6-4bb0-941a-b5fce59fd924.jpeg)

### Version

EC2

**Comment by ayushpahwa** [comment]
This form is controlled by server. Tagging @sondermanish for more details

**Comment by sondermanish** [comment]
Assigning @sribalajig, will pick this up later.
