### ISSUE TITLE
[Feature]: onClick for every widget types.

### ISSUE THREAD

**Issue by SKovbel** [appsmithorg/appsmith#20903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Would be very usable if any widget has onClick functional

### Why should this be worked on?

Example: to make easy navigation between pages by clicking some text or orther elements

**Comment by Nikhil-Nandagopal** [comment]
Closing this because in general all widgets do not have onClicks and we only support the native event handlers of every widget. You can make a text clickable by making it a HTML link and specifying a navigation URL
