### ISSUE TITLE
[Bug]: FontSize of Errors section in Debugger is not consistent with other section

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#20900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image (14)](https://user-images.githubusercontent.com/23132741/220854189-810c675f-ca63-476c-8caa-a5f3bd66c7c9.png)
![image (15)](https://user-images.githubusercontent.com/23132741/220854203-e508bc78-a020-4346-932b-5fa25a06fbfd.png)

### Steps To Reproduce

1. Create a JSObject
2. Modify a function to create a linting error eg :- type `const a =`
3. Check the errors

### Version

1.9.8

**Comment by ChandanBalajiBP** [comment]
@Rishabh-Rathod can you provide steps to reproduce error in 1st image
