### ISSUE TITLE
[Bug]: RBAC - ME - Order of the resources in the DS and Queries tab is not as per Figma

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Order of the resources in the DS and Queries tab is not as per Figma

### Steps To Reproduce

1. Login as instance admin and go to admin settings
2. Go to the Roles tab
3. Here, in the Datasources and Queries tab, note that under workspaces, the order of Environments, Datasources and Applications is not as per Figma

Figma file [here](https://www.figma.com/file/FC5XY2B57Fu41s0a0Wz93g/Multiple-Environments?node-id=3290%3A270772&t=zotd9gUfDPF5Qga8-0)

![orderofenv](https://user-images.githubusercontent.com/101863839/220890880-41ce2b2e-85eb-4729-af44-66526fb791da.jpeg)

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
This page is not handled from FE. Tagging @sondermanish for more info
