### ISSUE TITLE
[Task]: Ensure that plugins support uploading files of size 100 MB

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#20904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

<s>- Postgres
- MySQL
- DynamoDB
- Redshift
- Snowflake
- ArangoDB
- Firestore</s>

High priorities- rest. postgres, mysql, mongo S3

**Comment by AnandShahs123** [comment]
getting 504 on uploading a large file on postgres @nidhi-nair . https://knynrq7fk9.vmaker.com/record/TbRZa1AaW6BE44Tp

**Comment by AnandShahs123** [comment]
@nidhi-nair @ayushpahwa - 
1. S3 is not supporting large files in binary format.
2. REST is not supporting large files in both binary and base 64 format
3. For postgres, video, PDF, JSON, ZIP formats are failing for binary format and Video and PDF are failing in base 64 format
4. For MySql  also, large files are failing in both binary and base 64 format
