### ISSUE TITLE
[Bug]: Manage env page: Text box and drop down box size should be the same

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20914]
<img width="1440" alt="text drop down size" src="https://user-images.githubusercontent.com/119847783/220897652-1a87477b-2302-4741-8ed4-305a835fe1b2.png">
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Text box and drop down box size are different. Drop down boxes length is smaller than text box.

### Steps To Reproduce

1. Create a datasource
2. Edit
3. Go to manage environment

### Version

1.9.8

**Comment by rohan-arthur** [comment]
expected:
[zeplin link](https://app.zeplin.io/project/635b8c56ab73a736e7ac7fee/screen/635b8f3e3188f4179584c437)
![Screenshot 2023-02-27 at 16 35 21](https://user-images.githubusercontent.com/94514895/221547691-2bbfff4f-d6b4-4f78-9066-de8f82bd7980.png)

**Comment by btsgh** [comment]
Still seeing a mismatch in sizes here - MySQL - Server timezone override. Will raise a separate issue for this. Closing this one out.
