### ISSUE TITLE
[Bug]: RBAC - Two different loaders come up on the roles page 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two different loaders come up on the roles page

### Steps To Reproduce

Login as Instance Admin and go into Admin Settings
Here, go to Roles. 
Click on Add a Role
Note: Two different loaders come up now. 
https://ddpa7mfuvv.vmaker.com/record/03avYSbOR6RrLQBc

### Version

Self Hosted

**Comment by infinitetrooper** [comment]
@btsgh  - Which instance was this tested on?

**Comment by btsgh** [comment]
@infinitetrooper  - tested it on a appsmith-ee:release pull as well as on our our multiple environments instance - https://envsmith.appsmith.com
