### ISSUE TITLE
[Bug]: Manage environment page: The text below the endpoint is little bigger than the design.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The font size is 13px, instead of 10px.

### Steps To Reproduce

1. Create a datasource
2. Edit
3. go to manage env

<img width="1440" alt="text below endpoint" src="https://user-images.githubusercontent.com/119847783/220892256-c75da730-89b5-42ac-8b5b-116bd6bc2e89.png">

### Version

1.9.8

**Comment by btsgh** [comment]
Seems to be fixed.
