### ISSUE TITLE
[Bug]: Manage environment page: font size of few titles are not as per figma specs.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Manage environment title shoule be 20 px, its 18px
Endpoints and datasource configurations should be 16px, its 18px

<img width="1440" alt="font size" src="https://user-images.githubusercontent.com/119847783/220900697-33664be9-d452-4b4b-9c4c-f560b543e044.png">

### Steps To Reproduce

1. Create a datasource
2. Edit
3. Go to manage environments

### Version

1.9.8

**Comment by ayushpahwa** [comment]
Attaching notion card for more info
https://www.notion.so/appsmith/Font-size-spacing-and-font-type-are-wrong-17188ad1cb984d0c8daeef85f421b4e1?pvs=4

**Comment by btsgh** [comment]
Resolved
