### ISSUE TITLE
[Bug]: Ordering is not proper in case of mongodb datasource on the manage environment screen.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fields like Authentication type is coming before username. 
<img width="1434" alt="ordering" src="https://user-images.githubusercontent.com/119847783/220903774-7592770d-de0a-43b9-9778-482d96449b17.png">

### Steps To Reproduce

1. Create a mongodb datasource
2. Edit 
3. Go to manage environment
4. Select "Authentication type" before selecting the "Username"
<img width="1434" alt="ordering" src="https://user-images.githubusercontent.com/119847783/220903296-bbc5476c-ab35-462c-995d-d6eb5e4da709.png">

### Version

1.9.8

**Comment by ayushpahwa** [comment]
I am building this from the form config. There is no guideline to order these. How should we proceed with this? @sribalajig

**Comment by sribalajig** [comment]
Works as per design.
