### ISSUE TITLE
[Bug]: Unable to re-order the columns via the headers on changing the table size when SSP is turned on

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#20922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/ca3858b9d9f24878b1fbcde926fd5747

Unable to re-order the columns via the headers on changing the table size

### Steps To Reproduce

1. D&D a table widget
2. Enable server side pagination
3. Re-size the table
4. Notice that it isn’t possible to re-order the columns via the headers

### Version

Cloud

**Comment by keyurparalkar** [comment]
This issue got fixed in this [PR](https://github.com/appsmithorg/appsmith/pull/20928). Hence closing this issue
