### ISSUE TITLE
[Bug]: Spacing between info icon and bug icon is different in release and multi env.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Spacing between info icon and bug icon is different in release and multi env. Spacing is more in multi env.

<img width="508" alt="Screenshot 2023-02-23 at 6 52 40 PM" src="https://user-images.githubusercontent.com/119847783/220920401-5775b2c7-a957-4038-b0ee-ef45ee67a31a.png">
<img width="417" alt="Screenshot 2023-02-23 at 6 52 51 PM" src="https://user-images.githubusercontent.com/119847783/220920409-c3151acf-aa5b-43f3-8752-5d08ea2a9634.png">

### Steps To Reproduce

Refer to the screenshot

### Version

1.9.8

**Comment by btsgh** [comment]
Seems fine now. Slight difference exists, but negligible
