### ISSUE TITLE
[Enhancement] Allow users to see the recently used organisation first.

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#2093]
## Summary
Currently, we show all lists of org without any sort of order. We should be showing the recently used org first.

**Comment by Nikhil-Nandagopal** [comment]
Marking as enhancement since we discussed that not as many users have > 2 orgs today.

**Comment by nayan-appsmith** [comment]
@Nikhil-Nandagopal what actions make an organization recently used? For example, an user just opened an app under an organization and didn't make any change. Will this action mark the organization as recently used?

**Comment by Nikhil-Nandagopal** [comment]
@nayan-appsmith yes that can also be counted. Let's make loading any page in an app be the event for recently used organisation
