### ISSUE TITLE
Show changes made to the app during Git Commit

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#20931]
We currently only list the number of changes made rather than the actual changes made to the app. This is vague and opaque, the developer loses confidence in their commit and sometime will need to go back to check the changes they made.

Showing the changes in a neat diff format will give them a chance to verify before final commit and breed confidence while using the Git feature.

**Comment by infinitetrooper** [comment]
User Request on [Front](https://app.frontapp.com/inboxes/teams/folders/15573836/archived/74195017036)

**Comment by infinitetrooper** [comment]
User Request on [Front](https://app.frontapp.com/open/cnv_11iz5nv0)

**Comment by infinitetrooper** [comment]
Customer Review on [Slack](https://theappsmith.slack.com/archives/C023V5Y0STH/p1688725526975069)

**Comment by riteshkew** [comment]
Closed with Git granular status
