### ISSUE TITLE
[Bug]: OAuth - On configuring Production, on clicking save and authorize, internal error pops up

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

OAuth - On configuring Production and binding values, when we fill in remaining fields on edit datasource page, clicking save and authorize, internal error pops up

### Steps To Reproduce

1. Create a new OAuth2.0 DS and save it with just the url. 
2. Click on Edit and go to Manage Environments
3. Here, fill up the details as per the video attached
4. Now bind values
5. Click on Save and Authorize
6. Note an error screen comes up as below -
{"responseMeta":{"status":400,"success":false,"error":{"code":"AE-APP-4028","title":"INTERNAL_ERROR","message":"Validation Failure(s): Missing Client Secret","errorType":"Validation failed"}},"errorDisplay":"AE-APP-4028: Validation Failure(s): Missing Client Secret"}

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/eUl35ZiVpjmgK9Iw

### Version

EC2

**Comment by btsgh** [comment]
Also, when we directly configure OAuth even without staging and prod config, the save and authorize flow goes through fine, but when we try to run a query [POST - https://api.dropboxapi.com/2/files/list_folder] - it gives invalid credentials error. This works fine on Release

**Comment by sondermanish** [comment]
@ayushpahwa please send structure calls for both environments as soon as we bind environments. pretty similar to how we do structure calls today after every update
