### ISSUE TITLE
OAuth/GraphQL: Manage env page: Too much blank space observed at the bottom once the user scrolls up the page after selecting drop down

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

OAuth: Manage env page: When the user opens the drop down and scrolls up the page, a big gap is seen at the bottom.

<img width="1440" alt="oauth" src="https://user-images.githubusercontent.com/119847783/221498794-a9b96572-b60a-44a0-bc88-19d88f0734ff.png">

### Steps To Reproduce

1. Create an oAuth datasource
2. Edit
3. Go to the manage environment page.
4. Open the drop down
5. Scroll up the page

### Environment

Deploy Preview (Default)

### Version

v1.9.8

**Comment by btsgh** [comment]
Here is a [video](https://ddpa7mfuvv.vmaker.com/record/yWvlNQfDYqVy3d77) to describe the issue - @rohan-arthur

**Comment by btsgh** [comment]
This issue is fixed.
