### ISSUE TITLE
[Bug]: OAuth: Create datasource form: "key" "value" as hint text are not coming in the headers and query parameters fields unlike the design

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the create datasource form, "key" "value" are missing as hint text in the headers and query parameters text boxes

<img width="1440" alt="key" src="https://user-images.githubusercontent.com/119847783/221151505-ab8f154b-5b56-4bd3-ac28-871f9a02e4a4.png">
<img width="1132" alt="value" src="https://user-images.githubusercontent.com/119847783/221151521-31262dc0-d8b6-402f-9e95-35a3e4fa2e6c.png">

### Steps To Reproduce

1. Click to create a new OAuth data source

### Environment

Production

### Version

1.9.8

**Comment by btsgh** [comment]
Has been fixed.
