### ISSUE TITLE
[Bug]: Elastic Search - all the bound variable values get masked in the following scenario

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Elastic Search - all the bound variable values get masked in the following scenario

### Steps To Reproduce

1. Create a new elastic search ds
2. Enter the host and port. 
3. Save the DS [without changing the name of the ds]
4. Click on manage env and configure say staging or prod or both and bind values
5. Now come back to the edit ds page. Here note all bound variables and their values are seen
6. Now, change the name of the DS. Note that on changing the name all the variable values get masked

### Environment

Deploy Preview (Default)

### Issue video log

Elastic Search - all the bound variable values get masked in the following scenario

### Version

EC2

**Comment by sondermanish** [comment]
related to the task number #18027

**Comment by rohan-arthur** [comment]
closing this since we are restarting the project
