### ISSUE TITLE
[Bug]: Elastic Search - Error pops up on Binding values

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I bind values for Production or Staging, I get errors. First time this worked, but the second time, the error popped up. 

### Steps To Reproduce

1. Create a new elastic search ds
2. Enter the host and port.
3. Save the DS [without changing the name of the ds]
4. Click on manage env and configure say staging or prod or both and bind values
Note error pops up
![ElasticSearchME_Error](https://user-images.githubusercontent.com/101863839/221226145-5cf1f2cd-9ff7-4067-9648-8f1234a5718b.jpeg)

### Environment

Deploy Preview (Default)

### Version

EC2

**Comment by sondermanish** [comment]
not reproducible

**Comment by btsgh** [comment]
This seems to have been fixed.
