### ISSUE TITLE
[Enhancement][Code] A separate method `parseConfigBool` to parse boolean config values

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2095]
```
    const parseConfig = (config) => {
      if (config.indexOf("__") === 0 || config.indexOf("$") === 0)
        return "";

      const result = config.trim();
      if (result.toLowerCase() === "false" || result === "") {
        return false;
      } else if (result.toLowerCase() === "true") {
        return true;
      }

      return result;
    }
```

here instead of a common method for strs and bools should we create another method `parseConfigBool` for boolean config values?

**Comment by mohanarpit** [comment]
@rishabhsaxena What's the philosophy behind this suggested change? What's the problem that we are solving?

**Comment by rishabhsaxena** [comment]
Just for consistency where we get a boolean or a string as expected. I guess it won't have any major implication since empty string are falsy anyway
