### ISSUE TITLE
[Bug]: Elastic Search - On changing the toggle from prod to staging, or viceversa, the authentication dropdown collapses

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On changing the toggle from prod to staging, or viceversa, the authentication dropdown collapses

### Steps To Reproduce

1. Create a new elastic search ds and give a name to it
2. Enter the username.
3. Save the DS .
4. Click on manage env and configure say staging or prod or both and bind values
5. Now toggle between prod and staging on the edit ds page. 
6. Note that the authentication dropdown collapses, even if we expand it on one environment, on toggle it collapses back

### Environment

Deploy Preview (Default)

### Version

EC2

**Comment by ayushpahwa** [comment]
This is expected designed behaviour to hide confidential information. Please advise on this @parth-appsmith @sribalajig
