### ISSUE TITLE
[Question][Cypress] Actions don't have a `Show Alert` option which we are referring in the `getAlert` cmd

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2096]
Tests still pass, so tests don't fail in case an assertion in commands fails?

```
Cypress.Commands.add("getAlert", alertcss => {
  cy.get(commonlocators.dropdownSelectButton).click({ force: true });
  cy.get(widgetsPage.menubar)
    .contains("Show Alert")
    .click({ force: true })
    .should("have.text", "Show Alert");

  cy.get(alertcss)
    .click({ force: true })
    .type("{command}{A}{del}")
    .type("hello")
    .should("not.to.be.empty");
  cy.get(".t--open-dropdown-Select-type").click({ force: true });
  cy.get(".bp3-popover-content .bp3-menu li")
    .contains("Success")
    .click({ force: true });
});
```

![Screenshot from 2020-12-09 12-09-18](https://user-images.githubusercontent.com/1944800/101594265-63536280-3a17-11eb-8b99-ca055db373e3.png)

**Comment by NandanAnantharamu** [comment]
@mohanarpit let me know if you still feel we need a test here.

**Comment by mohanarpit** [comment]
@NandanAnantharamu Can we remove any duplicate commands from Cypress tests? If I understand correctly, the Cypress test suite has duplicate commands & @rishabhsaxena was looking at the wrong one. Let's remove any redundant commands so that future devs don't face this issue.

**Comment by NandanAnantharamu** [comment]
Removed the redundant code during refactoring, hence closing the issue.
