### ISSUE TITLE
[Feature]: How to get scrolling list Widget in Appsmith

### ISSUE THREAD

**Issue by dreemhai** [appsmithorg/appsmith#20961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I am trying to build messaging app on app smith but list I am getting in pagination mode how can I get that in vertical scrolling mode ?enter image description here

### Why should this be worked on?

vertical scrolling mode

**Comment by Nikhil-Nandagopal** [comment]
This is still an open feature request #30447

**Comment by parlt** [comment]
Please reopen the ticket
