### ISSUE TITLE
[Bug] Query template options order could be more intuitive 

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#2097]
## Description

The order of options could be more intuitive as in it could be of the order
1) Create
2) Select
3) Update
4) Delete

**Comment by sharat87** [comment]
@Nikhil-Nandagopal, there was an effort to move away from these templates and instead leverage the templates from the structure instead right? Reason being that these templates are not database-aware. The Select button always creates a query that selects data from the `users` table, whether that table exists in the database or not.

So, will these templates be going away soon?

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 yes we want to but haven't planned for that yet because it involves reconciling the add query mechanism with the structure in the entity explorer. 
Since this is fairly straightforward can we do this because this is impactful for NUX onboarding which only uses our mock db
