### ISSUE TITLE
[Bug]: Review Screen: GraphQL: Headers and query parameters key value representation is not according to the design.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Review Screen: GraphQL: Headers and query parameters key value representation is not according to the design.

Expected format: {key1: value1, key2: value2...}

<img width="1440" alt="graphql review" src="https://user-images.githubusercontent.com/119847783/221471705-2af30a9f-5311-4e29-82cf-80ffd48c2811.png">
<img width="1438" alt="review design" src="https://user-images.githubusercontent.com/119847783/221471711-fda00220-7c43-4bd3-a7a6-9ce822712884.png">

### Steps To Reproduce

Please refer to the design screen and the bug screenshot.

### Environment

Deploy Preview (Default)

### Version

1.9.8

**Comment by ayushpahwa** [comment]
Will be fixed with the solution of #20898
