### ISSUE TITLE
[Bug]: Clicking on an entity link in an error log entry closes the error log

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#20991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there is an error and the user clicks on the entity link an error log entry, the navigation to the entity works. However, the error log is closed, which means that the user has lost context on the error by clicking on the entity link.

Please check the attached video for an example of a case where the user clicks on a the link to a JS object from a linting error and the error logs closes.

### Steps To Reproduce

1. Create a linting error in a JS object.
2. Navigate to the JS object via the entity link in the lint error log entry.
3. Observe that the error log gets closed - the expectation is that the error log remains open.

### Environment

Release

### Issue video log

https://nstjszrz5x.vmaker.com/record/RHVYab73KUJpFbWA

### Version

Cloud

**Comment by bharath31** [comment]
no longer reproducible
