### ISSUE TITLE
[Bug] Cannot access `this.params` as an object in bindings

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2100]
## Description

The `this.params` is not an actual object, but references to it are being substituted directly. So, any logic that uses this as an object will fail. For example, `{{ this.params && this.params.name ? this.params.name : "None" }}` won't work but `{{ this.params.name }}` works. We need to make this reliable.

## Reproduce

I have an action called `Api1` and a button that runs this action when clicked. The `onClick` handler for this button contains the following Javascript:

```javascript
{{ Api1.run(() => {}, () => {}, {name: '"Sherlock"'}) }}
```

Here, we are trying to run the `Api1` action with extra params, `name`, in the third argument, while the success and error handlers are empty functions.

Now, in the `Api1` action, we have a query param with key as `name` and value as the following:

```javascript
{{ this.params.name || "No name" }}
```

This gets replaced with `Sherlock` correctly, but when the action is called as `{{ Api1.run() }}`, then this is replaced with empty string, instead of `No name`.

The problem is because we are applying direct substitutions on `this.params` references instead of making an object available as `this.params`. So, any logic beyond just `{{this.params.name}}` won't work correctly.

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu isn't passing params to APIs not working right now?
