### ISSUE TITLE
[Feature]: Stored Procedures for PostgreSQL

### ISSUE THREAD

**Issue by Team-wb** [appsmithorg/appsmith#21003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It should be possible to call procedures and functions in addition to queries and updates.

Here a Example-Procedure:
```sql
CREATE OR REPLACE PROCEDURE public.get_emp_info(IN p_emp_id integer, OUT p_name character varying, OUT p_mail character varying)
 LANGUAGE plpgsql
AS $procedure$
declare
begin
select empname,
           mail
  into p_name,
       p_mail
  from spa_emp
 where emp_id = p_emp_id;
end 
$procedure$
;

```

And it would be great to call this procedure by
```sql
CALL public."get_emp_info"(
 p_emp_id => {{Input1.text}},
 p_name => {{EmpName.text}},
 p_mail => {{Mail.text}});
```

To achieve this, stored procedures need to be listed under Queries, and a specific call needs to be made.

A function call could look like this:
```sql
{ {{Text1.text}} = test_func(param1 => {{Input1.text}},
                             param2 => {{Input2.text}})
}
```

(In fact, I have almost finished this myself. However, I currently have a problem with the output variables. I have currently solved this by specifying all outputs using the notation :name and returning a single-line result set with a column for each output parameter.

My example above looks like this:
```sql
CALL public."get_emp_info"(
 p_emp_id => {{Input1.text}},
 p_name => :p_name,
 p_mail => :P_mail);
```

Here the (german) Example that works on my side: 
![Bildschirmfoto vom 2023-03-12 07-32-09](https://user-images.githubusercontent.com/124695680/224528521-afb40de8-32fe-4389-9cc3-81f06021b490.png)

You can see in Datasources, the procdures and functions are listed including their parameters and the Result of an call is a single "query" result line. 

Currently, the result columns are of type String. However, I plan to change this so that the data type can be appended to the column name using the @ symbol. The plan is as follows:
```sql
{ :result@INTEGER = test_func(param1 => {{Input1.text}},
                              param2 => {{Input2.text}})
}
```

But as I said, this is currently my internal solution.)

### Why should this be worked on?

Stored Procedures are an important feature ob Postges.

**Comment by dilippitchika** [comment]
@rohan-arthur can you take a look at it and get it triaged?

**Comment by Nikhil-Nandagopal** [comment]
@Team-wb did these solutions not work for you?
https://community.appsmith.com/t/how-do-i-execute-stored-procedures-sql-in-appsmith/856
https://docs.appsmith.com/learning-and-resources/how-to-guides/returning-data-from-a-stored-procedure
