### ISSUE TITLE
[Bug]: OAuth - Post query to dropbox fails. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#21029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On establishing a connection to dropbox using OAuth2.0, and running a post query - the query fails with the following errors - 

[PE-RST-5000]
An error occurred during the execution of your API. Please check the error logs for more details.
[400 BAD_REQUEST]
Error in call to API function "files/list_folder": request body: could not decode input as JSON

### Steps To Reproduce

1. Create an OAuth connection to dropbox. 
2. The connection goes through fine
3. Now create a new POST api entering the Body in JSON format as below -
{
--
"include_deleted": false,
"include_has_explicit_shared_members": false,
"include_media_info": false,
"include_mounted_folders": true,
"include_non_downloadable_files": true,
"path": "",
"recursive": false
}

4. Note that the query fails with the errors - 
[PE-RST-5000]
An error occurred during the execution of your API. Please check the error logs for more details.
[400 BAD_REQUEST]
Error in call to API function "files/list_folder": request body: could not decode input as JSON

This same query passes on Production.
**Note: Details of credentials as below -** 

URL - https://api.dropboxapi.com/2/files/list_folder
--
Authentication Type - OAuth2.0
Grant Type - Authorisation Code
Access Token URL - https://api.dropboxapi.com/oauth2/token
Client ID - 2lwiwmnrsektqim
Client Secret - s16uo7jhe1o971i
Scope - files.metadata.write
Authorisation URL - https://www.dropbox.com/oauth2/authorize
Redirect URL - https://release.app.appsmith.com/api/v1/datasources/authorize
Custom Authentication Parameters -
response_type = code
token_access_type = offline

Ensure your redirect URL is a part of the dropbox setup. 

### Environment

Release

### Version

Release Branched out

**Comment by btsgh** [comment]
![dropboxoautherror](https://user-images.githubusercontent.com/101863839/221777520-fca8be9e-be52-48d5-a203-caadec5f636b.jpeg)

**Comment by sumitsum** [comment]
Looks like a FE issue. Posted my analysis here: https://theappsmith.slack.com/archives/CTHN8GX5Y/p1677598620592509?thread_ts=1677567532.832279&cid=CTHN8GX5Y

**Comment by sumitsum** [comment]
Fixed as part of PR: https://github.com/appsmithorg/appsmith/pull/21057
