### ISSUE TITLE
[Feature] Introduce basic authentication that makes use of the Auth flow similar to OAuth2

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2103]
## Summary
As of today, users have no way of triggering basic authentication from scratch within Appsmith. If they do need to use this mechanism, they need to store their encoded credentials as a header. However, since we do not encrypt headers, this becomes a security threat.

Introducing basic authentication as part of the Auth flow will require answering the following questions:
1) What kind of design changes will this require?
2) Do we display the encoded header on the API pane?
3) So far all authentication and authorization related fields are only visible when they are created. If headers need to be displayed, we might want to add another layer of checking user details before displaying them

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair @mohanarpit  does this need design? Is it covered in the oauth flow already?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal the existing design covers all possible fields and can be combined to create the basic authentication page. I was wondering about the interaction between creating this authentication and displaying headers (if at all)

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair I would assume that after setting the username / password, an encrypted (Read-Only) header would be generated and displayed. Did you have something else in mind?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal Okay for some reason I thought APIs saved as datasources automatically import headers from the datasource as read-only headers in the API itself. Just checked to see that that is not the case. Although I think we should show these?

^ I raise this because that increases the types of headers to be displayed:
1) Manually types read-write headers
2) Read-only headers from datasource
3) Encrypted read-only headers for authorization. This would be the only kind that does not display header values

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair this doesn't happen today but it should be part of the oAuthe design we pick up. In case #3 it won't display the auth values but it will display the encrypted value that is being sent right?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal The header values are typically just base64 encoded, that would not provide any form of encryption as such. IMO we should make it appear similar to how we show database passwords, that is, write-once and then only show the field as "encrypted"

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair why should it be encrypted and not just base64 encoded? I don't see a security risk since the user who configures the action is the one who has access to view it
