### ISSUE TITLE
[Bug]: Existing / Imported git connected apps with actions show uncommitted changes related to queries due to new file structure , even when no changes are made.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For existing / imported git connected apps, git sync modal show 'n queries modified' even when there are no changes made by user in app, we should improve the  message in git sync modal to let user know that this change is due to migration / change in file structure from our end.

### Steps To Reproduce

1. Import an app connected to git which has actions
2. Open git sync modal and observe

### Environment

Deploy Preview (Default)

### Version

http://ec2-13-235-91-14.ap-south-1.compute.amazonaws.com/applications

**Comment by AnaghHegde** [comment]
@Parthvi12 This happens even on the production when you import an older application. We have to solve this via migration EPIC. 
cc - @infinitetrooper

**Comment by infinitetrooper** [comment]
Duplicate, Closing this in favor of https://github.com/appsmithorg/appsmith/issues/19209
