### ISSUE TITLE
[Bug]: File picker for google sheets doesn't show up on firefox

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#21033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For the new update for limited access google sheets after the authorization the file picker doesn't show up when using firefox browser .
Loom Video: https://www.loom.com/share/e0a108f599df4be7ab188b5d23a2bb3e

### Steps To Reproduce

1. Open the dp: https://ce-20778.dp.appsmith.com/applications
2. Create a new google sheet DS.
3. Provide required permissions.

### Environment

Deploy Preview (Default)

### Issue video log

https://www.loom.com/share/e0a108f599df4be7ab188b5d23a2bb3e

### Version

cloud

**Comment by rohan-arthur** [comment]
@parth-appsmith is using the latest version of firefox (downloaded last week)
