### ISSUE TITLE
[Bug]: Tab widget cuts emojis in tab titles

### ISSUE THREAD

**Issue by ed-parsadanyan** [appsmithorg/appsmith#21034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When adding emoji into Tab title of the Tabs widget, I can see that the icon is incorrectly cropped:

![image](https://user-images.githubusercontent.com/10472129/221789867-a4f78fd0-ef5c-47c8-8e0c-b6887e89f052.png)

### Steps To Reproduce

1. Add Tabs Widget
2. Rename tab and add an emoji
3. See that top part of the emoji is cropped

### Environment

Production

### Version

Self-hosted 1.9.8

**Comment by Nikhil-Nandagopal** [comment]
Seems to be the same as #21606 so closing this
