### ISSUE TITLE
[Bug]: misalignment in query response

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#21043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the column lines in the query response are misaligned:
![Screenshot 2023-02-28 at 16 20 31](https://user-images.githubusercontent.com/94514895/221832947-e693f940-3a37-481e-97a5-11de57b29b5b.png)

### Steps To Reproduce

1. run some postgres query
2. see the alignment problem

### Environment

Production

### Version

Cloud

**Comment by AmanAgarwal041** [comment]
This issue seems to be fixed. @rohan-arthur Can you check if this is reproducible ?
<img width="913" alt="Screenshot 2023-04-20 at 11 38 40 AM" src="https://user-images.githubusercontent.com/7565635/233273272-ec774ebf-e77d-41c4-ba51-b90719791273.png">

**Comment by rohan-arthur** [comment]
duplicate, already fixed
