### ISSUE TITLE
[Bug] Column reordering in property pane interaction is buggy

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2104]
## Description
see loom video:
https://www.loom.com/share/5ae41977e011499cad39b97f87f1e85c

bugs:
1. the edges of the column get cut off when dragging it
2. other columns move down the second you hold one column name(this should happen only when you are moving the column down)
3. The column shouldn't be dragged below the target drop area

**Comment by riodeuno** [comment]
The approach to solve this is to move away from react-beautiful-dnd and use react-spring to re-write the control. https://codesandbox.io/embed/r5qmj8m6lq
https://www.react-spring.io/docs/hooks/examples
