### ISSUE TITLE
[Feature] websockets as a datasource

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2105]
## Summary
For live apps that can subscribe to events

## Motivation
Would be useful for dashboards where data is updated in real-time.
Users could also add a chat window

Not sure, if it's in the roadmap currently, tried searching for websocket

**Comment by areyabhishek** [comment]
There's an issue filed a couple of weeks ago with this request. I had typed web sockets instead of websockets, so you couldn't find it. https://github.com/appsmithorg/appsmith/issues/1866. I updated it with your comments.
