### ISSUE TITLE
[Bug] When the user tries to upload a large file and the upload fails, the error message is not relevant.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error message is not relevant when a large file upload is failing.

### Steps To Reproduce

1. Use a filepicker widget to upload a large file like 90-100 mb
2. Use this endpoint for multipart upload

curl --location --request POST 'localhost:3002/rest/upload' \
--form 'file=@"/Users/cataclysm/Documents/test3.mp4"'

### Environment

Release

### Issue video log

https://knynrq7fk9.vmaker.com/record/P67fVlvxmIRB0Aso

### Version

1.9.9

**Comment by DevRishiJain** [comment]
Is anyone working on this issue. If not can you assign it to me.

**Comment by rohan-arthur** [comment]
we are removing toast messages in the editor with #35741 
This issue will not be valid after that
