### ISSUE TITLE
[Bug]-[1000]:Table data export to Excel displays column header as 0 whenever the column data type is Number

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#21075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever we have a table that has a column declared as Number, when this table is exported as Excel, the header to end column declared as Number is exported as Zero. 

[image/png] : https://cdn.discordapp.com/attachments/1080269931075076166/1080269931679068180/image.png
[image/png] : https://cdn.discordapp.com/attachments/1080269931075076166/1080269931913941082/image.png
[image/png] : https://cdn.discordapp.com/attachments/1080269931075076166/1080269932136235099/image.png
[image/png] : https://cdn.discordapp.com/attachments/1080269931075076166/1080269932425654352/image.png

### Steps To Reproduce

1. Create a table widget and populate with data that has a column whose data type is set to Number. 
2. Export the table as Excel

### Environment

Deploy Preview

### Version

Cloud / Self Hosted  1.9.7

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7sc3w)

**Comment by keyurparalkar** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 0.5 |

**Comment by Nikhil-Nandagopal** [comment]
This seems to be working
