### ISSUE TITLE
[Bug]: Selecting  page setting from JSeditor page, user has to select back to check the canvas and see the settings 

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#21073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Select the JSeditor>> select the Page setting >> Verify that the editor page is expanded and user has to select back button to navigate back to canvas.  Similar flow observed during Query pane
This issue exist in production 
Expected : Page setting should open if selected or users should be prompted to go back to canvas

https://user-images.githubusercontent.com/80756091/222069117-ac0e5453-37c3-4d2d-b4c3-889187ff9d9e.mov

### Steps To Reproduce

1. Select JSobject
2. Select page setting
3. Verify User is not navigated back to settings

### Environment

Production

### Version

cloud

**Comment by kocharrahul7** [comment]
This is no longer an issue since we have changed the settings, as well as the back button and page layout. It is now accessible from JSObjects
