### ISSUE TITLE
[Feature]: Change properties when sibling fields in an Array of a JSONForm is updated

### ISSUE THREAD

**Issue by wansadi** [appsmithorg/appsmith#21079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Say, I have a JSONForm that has an Array Field.
For each element in the Array it looks like this:
{"value":"112233","disabled",false}
value is an input widget , while disabled is a switch.

What I want to do is this: When disabled switch is turned on, the value widget will be set disabled. So what I can think of is to bind the disabled property of the value widget with disabled's value.
For now I can't find a way to do this when widget are in an array of a JSONForm. That is, I can't find a way to find a sibling widget in order to update its properties.

### Why should this be worked on?

Is there a way to do this?

**Comment by ashit-rath** [comment]
Hi @wansadi, thank you for the feature request.
We have a similar feature request in our pipeline https://github.com/appsmithorg/appsmith/issues/16343. Please do have a look at it and let us know if it covers your use-case.

**Comment by wansadi** [comment]
> #16343

That would be great. Looking forward to it

**Comment by somangshu** [comment]
Closing this in favour of #16343
