### ISSUE TITLE
[Bug]: group widgets start to expand when we add more options.

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#21083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- When we add more options to the group widgets (radio, switch, checkbox) the start to expand in width.

### Steps To Reproduce

1. Drag and Drop a group widget (Checkbox for example).
2. In the Data property add - 
```js
{{getAllMovies.data.map((movie) => ({
  label: movie.title,
  value: movie._id
}))}}
```
3. The widget starts to expand.

### Environment

Deploy Preview

### Issue video log

https://www.loom.com/share/09f04ad5c2a7477f8a79468c1e448135

### Version

feat/widget_responsive

**Comment by yaldram** [comment]
Not able to re-produce, with the latest pull.

**Comment by aswathkk** [comment]
Closing this since we've fixed it
