### ISSUE TITLE
[Bug]: Delete multiple rows in Google Sheets using a JS Object

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#21092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using a JS object to call the Google Sheets query that deletes a row in the Google Sheets table, it results in inconsistent deletions.

I have attached a video where the undesired behavior can be clearly seen.

https://user-images.githubusercontent.com/114161539/222181542-3953a4b1-b269-458f-a8e5-4f0b63c3d739.mp4

### Steps To Reproduce

   1. Create a simple sheet in Google Sheets.
   2.  Connect it to Appsmith.
   3. Create a query to fetch data from this sheet.
   4. Create a Google Sheets deletion query using `Entity (Sheet Rows)`.
   5. Create a JS object like this:
   ```js
   export default {
	create_subtask_from_preordertable: async () => {
		for (const fData of PreorderTable.tableData) {
      Clear_All_Data.run({rowIndex: fData.rowIndex})    
		}
	}
}
  ```
   6.  In our deletion query, write `{{this.params.rowIndex}}` in the ROW index.
   7.  Execute the JS object and observe the behavior.

### Public Sample App

https://app.appsmith.com/app/issuerowdelete/page1-63fe08ebcba7d14432258dd1

### Environment

Production

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7s3ik)

**Comment by felix-appsmith** [comment]
This bug seems to be related to this other one:#18616

**Comment by pranavkanade** [comment]
@felix-appsmith don't think it's a bug. Every time you delete a row, all rows below that one will have a new `rowIndex`. I think that's an expected behaviour, which is out of our control

**Comment by optisness** [comment]
> @felix-appsmith don't think it's a bug. Every time you delete a row, all rows below that one will have a new `rowIndex`. I think that's an expected behaviour, which is out of our control

I select from GoogleShits to the table only rows with column value = contact id. Is there any way to remove all rows of this table from GoogleShits?

**Comment by felix-appsmith** [comment]
Hi @optisness , currently, it is possible in Appsmith to delete all the rows of a Google Sheets using a recursive function in JavaScript. You can use the following code, but modify it to work with the names of your queries:

1.  In the Google Sheets delete query, write this in the Row Index field: {{this.params.rowIndex}}

2. Write a JavaScript object with this code.

```js
export default {
  Order_button: async () => {
    console.clear();

    await cleaner();

    async function cleaner() {
      try {
        await getPreorder.run();
        let i = getPreorder.data.length;
        if (i === 1) {
          await clear_preorder_table.run({ rowIndex: 0 });
        } else {
          while (i > 0) {
            await clear_preorder_table.run({ rowIndex: i });
            i--;
          }
        }
        await reviwetable();
      } catch (err) {
        console.error(err);
      }
    }

    async function reviwetable() {
      let i = await getPreorder.data.length;
      while (i > 0) {
        await cleaner();
        i = await getPreorder.data.length;
      }
    }
  },
};

```

3. Run the JavaScript object and watch as all the rows of your Google Sheets are deleted.

As for improving the grammar and spelling, I have corrected some minor mistakes and made the sentences more concise.

Attached example video:

https://user-images.githubusercontent.com/114161539/223573515-150da8df-e876-432a-a83c-629f108fcf17.mp4

**Comment by optisness** [comment]
Good afternoon. Please help improve the code so that rowindex = tableindex , not 0 or i
https://i.imgur.com/l5xCKpV.jpeg
https://i.imgur.com/9yF0fdX.jpeg
