### ISSUE TITLE
[Bug] Cannot read "length" of undefined in TableWidget selectedRowIndices

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2110]
## Description
Sometimes TableWidget's selectedRowIndices gets set to undefined and then Table widget tries to get the length of it.

![](https://cdn.discordapp.com/attachments/786263966984306698/786294005637185536/unknown.png)

### Important Details
 - Version: Self-Hosted

**Comment by hetunandu** [comment]
Ideally we should not be setting and manipulating meta properties in Table Widget's componentDidUpdate. We should find a better way to get this value correct on the user selection

**Comment by notacouch** [comment]
This seems to be related to enabling multi selection on tables.

When the error starts happening, I cannot select any rows on a table. Table Action buttons also do not provide filled `table.selectedRow` values. I tried using JSON stringify to display and it only showed `{}`. 

Once I disable multi selection, everything seems to work again (so far).
