### ISSUE TITLE
[Bug]: Stuck during discard changes

### ISSUE THREAD

**Issue by pramonow** [appsmithorg/appsmith#21100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1227" alt="Screen Shot 2023-03-02 at 16 03 18" src="https://user-images.githubusercontent.com/28787057/222383089-0b1fd0bb-e52b-4520-9bbf-4df6b4c96cda.png">

Error response:
{"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Provided file format is incompatible, please upgrade your instance to resolve this conflict.","errorType":"INTERNAL_ERROR"}}}

appsmith version v1.8.5

### Steps To Reproduce

1. Deploy
2. Discard Changes

### Environment

Production

### Version

1.8.5

**Comment by AnaghHegde** [comment]
@akash-codemonk 
1. The error message should be displayed inside the modal. We do this for all the other git flows
2. Yes the status bar should be reset and provide the option to retry.
cc - @infinitetrooper

**Comment by akash-codemonk** [comment]
Updated UI

https://user-images.githubusercontent.com/67054171/224610601-5fc9670f-4760-4fde-a0f1-f49e6600ed8e.mov

**Comment by akash-codemonk** [comment]
https://appsmith-f0vvksftr-get-appsmith.vercel.app/

**Comment by Parthvi12** [comment]
Verified the fix and it's working as expected<img width="1440" alt="Screenshot 2023-03-15 at 6 39 21 PM" src="https://user-images.githubusercontent.com/80334441/225318465-b0a8afc4-9f07-42d7-a2f1-67efe211a0dd.png">
