### ISSUE TITLE
[Feature]: Error state for Dropdown Control in the Property Pane

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#21109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

App developers ignore errors in the property pane when the control is a Dropdown Control. The User needs to see that there is an issue with the selection or perhaps a selection is required, but it's challenging to show the app developers this error using this control

### Why should this be worked on?

It helps prevent crashing and unwanted states within the widget development.

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope how can a dropdown have an error state? It should always have a finite set of working options right?

**Comment by Tooluloope** [comment]
> @Tooluloope how can a dropdown have an error state? It should always have a finite set of working options right?

You're right that a dropdown menu typically has a finite set of working options. However, there can be cases where an error state is necessary. For example, when a user is required to select an item from the dropdown but doesn't make a selection.

In such a scenario, an error state can be added to the dropdown to indicate that making a choice is mandatory. This can be done by visually highlighting the dropdown with an error message or an icon. The error state helps the user understand that they must select an option before proceeding or the widget requires the selection to render properly, ensuring that they select an option.
