### ISSUE TITLE
WDS: Color tokens structure and rules generation

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#21107]
- [x] #20358
- [x] #20715
- [x] #20716  
- [x] #21288 
- [x] #21913 
- [x] #22365
- [x] #22424 
- [x] #22512 
- [x] #22568 
- [x] #22630
- [x] #22699 
- [x] #22713 
- [x] #22823 
- [x] #22921
- [x] #23218 
- [x] #23870 
- [x] #24034 
- [x] #24033 
- [x] #23986 
- [x] #24209 
- [x] #23803 
- [x] #23802
- [x] #24461
- [x] #24513 
- [x] #24510 
- [x] #24511 
- [x] #24747
- [x] #24748
- [x] #24512 
- [x] #25018
- [x] #25060
- [x] #25196
- [x] #25306 
- [x] #25440
- [x] #25035
---

[Semantic color naming strategy](https://www.notion.so/appsmith/Semantic-Color-Naming-Strategy-1fa38c16bc1946479ecbb48bb6612abb?pvs=4)
[Parametric color schemes](https://www.notion.so/appsmith/WDS-parametric-color-themes-v0-1-0-aa98292782334fcabf048728e2aba64e?pvs=4)
[Color Generator POC4: Parametric theme from a single seed](https://www.figma.com/file/B9BZVgpzMwNhKOeG6Ocv5B/Color-Generator-POC4%3A-Parametric-theme-from-a-single-seed?node-id=0%3A1&t=4gjzAIpcC16pMU0H-1)

Naming hierarchy (type-role-modifiers-state) based on a visual functionality, e.g.:
`--bg-accent-light-hover` `--fg-onaccent` `--border-accent`.

The whole color scheme for widget set can be built from one initial accent color.

What we have now is some naive generation of colors from a key accent color e.g.:
```javascript
export const getComplementaryGrayscaleColor = (hex = "#000") => {
  const bg = parseColor(hex);
  const text = new Color("#fff");

  const contrast = bg.contrast(text, "APCA");

  // if contrast is less than -35 then the text color should be white
  if (contrast < -35) return "#fff";

  return "#000";
};
```
```javascript
export const calulateHoverColor = (hex = "#000") => {
  const color = parseColor(hex);

  switch (true) {
    case color.get("oklch.l") > 0.35:
      color.set("oklch.l", (l) => l + 0.03);
      break;
    case color.get("oklch.l") < 0.35:
      color.set("oklch.l", (l) => l - 0.03);
      break;
  }

  return color.toString({ format: "hex" });
};
```

---

This needs to evolve based on the following knowledge.

1. [APCA contrast](http://myndex.com/apca)

APCA contrast check returns a number in the range from `−107.9` to `106`. Contrast will be negative for light content on a dark background and positive for dark content on light background. In APCA it is important what is a background and what is a foreground, results of measurement differ. The absolute value of the contrast measurement is what defines whether the contrast is good/sufficient. APCA standard recommends taking into the consideration font size and weight for text content and has following guidelines that we can start from as a reference:

> 60 • The _minimum_ level recommended for content text that is not body[...] The minimums: no smaller than [...] 24px normal weight (400) [...] 16px/700. These values based on the reference font Helvetica.

> 75 • The _minimum_ level for columns of body text with a font no smaller than 24px/300 weight, 18px/400, 16px/500 and 14px/700. This level may be used with non-body text with a font no smaller than 15px/400. Also, Lc 75 should be considered a minimum for larger for any larger text where readability is important.

These are tough limitations for us considering information-dense widgets with small type, but no reason not to strive for contrast.

2. [oklch color space](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl)

Human-grokable perceptually uniform way to define colors. It follows the pattern of HSL (Hue-Saturation-Lightness) with Lightness-Chroma (roughly equivalent to saturation) and Hue. This makes it neat for operations such as “hover color should be 5% brighter” or “dark mode colors should be 10% less saturated”.

It avoids bugs of HSL color space such as hue rotation (changing hue from 30 to 50 has drastically different visual results from 230 to 250):

![Image](https://user-images.githubusercontent.com/80973/218701990-923f4ea0-4434-4636-8962-0985b069e485.png)

… or non-matching visual lightness for different hues:

![Image](https://user-images.githubusercontent.com/80973/218702515-37bc4c7a-f03a-4a62-9f40-08a18f5b9886.png)

3. [Dark mode](https://uxdesign.cc/designing-dark-mode-c7bd200eaa64)

A gross oversimplification: we're inverting the lightness of backgrounds and foregrounds. In practice this inversion applies only on the macro-level but within compositions progression from darker to lighter shades should match the light mode, to aid human perception of depth:

![image](https://github.com/appsmithorg/appsmith/assets/80973/18fad053-e70f-4726-bc5b-e549d9d6e837)

Shadows shouldn't become white highlights when switching to dark mode:

![Image](https://user-images.githubusercontent.com/80973/218708844-96c95d8d-d0fe-41fb-b0e0-3bf7a368a086.png)

General saturation / chroma should be lower for dark mode to account for the fact that dark backgrounds accentuate color perception.

Surrounding contrast may affect the perception. e.g. for a `light` style button variant we want to use light and less saturated version of the picked color for background and dark version for the foreground. In dark mode the background color keeps the rule of being light, but the foreground does the opposite of that and goes lighter.

![Image](https://user-images.githubusercontent.com/80973/218710632-e17d3031-430b-489f-833d-3bc192ba3694.png)

4. High contrast mode

This generally can be driven by setting higher tolerance for our initial contrast checks, but also by applying higher ratios in derivative colors (e.g. all `--color-foreground-onFOO` are X% lighter/darker in regular mode and X*N% ligher/darker in high contrast).

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9nex8)

**Comment by jjohnson5253** [comment]
Hi my team would really like a dark mode/theme option. It would be great if we could enable dark mode by default while embedding the Appsmith app as well! Will that be possible??

**Comment by somangshu** [comment]
Thanks for showing interest here @jjohnson5253. We are currently working on the color generation algo and will get to the dark mode config soon. 
Interesting to see you say we should enable the dark mode by default while embedding Appsmith apps, May I know the reasoning behind this?

**Comment by jjohnson5253** [comment]
> 

Awesome, thank! Our team's internal web app is dark mode by default, so having the option to show the embedded appsmith app as dark would make our app look a lot nicer!

**Comment by karurosux** [comment]
Hello  everyone, I am currently developing integration between appsmith and the product of the company where I work, I use appsmith on its embedded mode inside company's product and I was interested in this topic, I wonder if you guys will allow us to set this dark mode on through URL? via query param for example, then we can sync the container app and embedded appsmith in terms of dark mode being enabled or not, also, if it will be possible for us to configure the dark mode background color palette somehow, this so dark colors match with main container application.

Thanks in advance and thanks for creating such a nice app!

**Comment by karurosux** [comment]
> Hello everyone, I am currently developing integration between appsmith and the product of the company where I work, I use appsmith on its embedded mode inside company's product and I was interested in this topic, I wonder if you guys will allow us to set this dark mode on through URL? via query param for example, then we can sync the container app and embedded appsmith in terms of dark mode being enabled or not, also, if it will be possible for us to configure the dark mode background color palette somehow, this so dark colors match with main container application.
> 
> Thanks in advance and thanks for creating such a nice app!

Hello, any response about this?

**Comment by ichik** [comment]
@karurosux This is still very early on in development, so we haven't yet settled on how builders will be able to switch it, but we discussed potential mechanisms and query parameters that would be fairly easy to support.
As for background colors: the main color generation behavior that is being worked on is a full harmonious monochromatic palette so that the background is harmonious with the main accent. Various ways to override the default theme are being discussed.
