### ISSUE TITLE
Show/Hide Table Controls

### ISSUE THREAD

**Issue by ravivyas84** [appsmithorg/appsmith#2111]
## Summary

Provide the ability to selective hide table controls like:
1. Search box
2. Filters
3. Data download
4. Pagination controls

## Motivation

There are use cases where one would want to disable search/filtering/downloading of data or even hide the page next previous controls as one might be doing more complex pagination by themselves.

**Comment by Nikhil-Nandagopal** [comment]
@ravivyas84 thank you for the feature request! I'd like to understand more about the hiding of search & pagination controls.
Could you elaborate a bit on the use case here?

**Comment by ravivyas84** [comment]
I am working with a paginated API that does not have previous page controls, thus I have buttons outside the table to go to the next page and the first page. Thus I want to hide the next/previous buttons.

Another example is disabling CSV downloads.

**Comment by Nikhil-Nandagopal** [comment]
@ravivyas84 Thanks for clarifying this. Could you also clarify the need to hide search?

**Comment by ravivyas84** [comment]
If I build a segmentation/filtering capability outside the table using dropdowns and input fields, I would want to hide search

**Comment by riodeuno** [comment]
Note:
- This feature should be available in the property pane. One toggle for each feature on the table.
- If all features are toggled off, the header will not occupy any height
- In case of toggling off pagination, #2896 should be released in tandem
- When toggling off features, they will not be available in both edit and view modes.

**Comment by somangshu** [comment]
Design update: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=2%3A3024

`user flows > hide/show options flow`
