### ISSUE TITLE
[Bug]: Upload images to Airtable

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#21117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It's not possible to upload images to Airtable from Appsmith. We are getting the following error: {"error":{"type":"INVALID_ATTACHMENT_OBJECT","message":"Invalid attachment object for field imgs: "testIMG.jpg""}}

The object we are sending looks like this:

```js
   {
		url: FilePicker1.files[0].data,
		filename: FilePicker1.files[0].name,
		type: FilePicker1.files[0].type,
		size: imgBuffer.length
}
```

The object sent to Airtable looks like this:
```js
[{ "fields": { "Name":"test2", "imgs": {{imgAirtable.myFun1.data}} }}]
```
We also tried with this object:

```js
[{ "fields": { "Name":"test2", "imgs": {{FilePicker.files[0].data}} }}]
```
And this another object:

```js
[{ "fields": { "Name":"test2", "imgs": {{FilePicker.files[0].data}} }}]

```

### Steps To Reproduce

1. Connect to your Airtable data source.
2. Create a query to create records in Airtable.
3. Try uploading an image to Airtable using this object:

```js
[{ "fields": { "Name":"test2", "imgs": <<img>> }}]

```
4. Execute the query and check the error message

### Environment

Production

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7upvw)

**Comment by Tanguy** [comment]
Hi @Nikhil-Nandagopal & @pranavkanade! 
I came across this issue 4 days ago & report it to the support team. I would love to see this bug fix as it prevents me from finishing a small project on my end (airtable & appsmith integration). Don't hesitate to contact me if you want user feedback or want a direct, concrete business use-case showing the failure.
Cheers,
Tanguy

**Comment by sribalajig** [comment]
@Tanguy I'm from the Appsmith product team. Would like to talk more about this. Please feel free to setup time on my calendar [here](https://calendly.com/balaji-gopinath/appsmith-user-interview).

**Comment by nidhi-nair** [comment]
@Tanguy it would be super helpful if you could share the API specs for Airtable that mention support for direct image uploads. From what I can find it seems that they only support uploading images using a publicly accessible URL as of now.

**Comment by Tanguy** [comment]
Sorry for my late reply, here's the API doc from Airtable:
https://airtable.com/appjJ6ZManMBpEZfj/api/docs#curl/table:image_listing:fields

**Comment by nidhi-nair** [comment]
Sorry, this looks like docs for your workspace, and is not accessible to me, would appreciate it if you could take a screen grab / copy the text here / provide access. :)

**Comment by Tanguy** [comment]
I try to screenshot everything that seems relevant, hope that will help.
Ask me for more if needed :)

[image: Capture d’écran 2023-04-06 à 12.14.24.png][image: Capture
d’écran 2023-04-06 à 12.13.19.png][image: Capture d’écran 2023-04-06 à
12.13.38.png][image: Capture d’écran 2023-04-06 à 12.13.49.png][image:
Capture d’écran 2023-04-06 à 12.13.56.png][image: Capture d’écran
2023-04-06 à 12.14.11.png]

**Comment by nidhi-nair** [comment]
Hey sorry, looks like the images did not get uploaded in your response, perhaps because you are not using Github directly? Could you please retry uploading via Github or send this response as an email to me? (nidhi@appsmith.com) :)

**Comment by nidhi-nair** [comment]
@Tanguy I'm going to go ahead and close this issue since from our last discussion, we concluded that Airtable expects you to send a public URL for image uploads. If you think that this issue is unresolved for you, or you would like to propose another solution, please feel free to keep commenting here and we will re-evaluate. :)

**Comment by minimaxy** [comment]
I recently found Appsmith. I also found out that it is currently not possible. Is there any plan to develop a built-in DB like Budibase that is easy to set up and can store anything?
