### ISSUE TITLE
[Bug]: Tooltip shows up by hovering on border

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#21122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Tooltip for Onsuccess & Onfailure shows up everywhere when hovered on border and not only when hovered over the property name.

https://loom.com/share/f2d7421a49cd4c8697917e78f6c94ebc

### Steps To Reproduce

1. Add call back functions
2. Hover over the border

### Environment

Deploy Preview

### Version

ce

**Comment by rimildeyjsr** [comment]
available after dp refresh
