### ISSUE TITLE
Can't start appsmith local

### ISSUE THREAD

**Issue by thanhloc1993** [appsmithorg/appsmith#21124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error: http://localhost/api/v1/tenants/current 404 status

### Steps To Reproduce

I'm following this guide:
-https://github.com/appsmithorg/appsmith/blob/release/contributions/ServerSetup.md
and
- https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md

When yarn start.  After sign up and sign in. I'm facing this error: 
http://localhost/api/v1/tenants/current (404)

![2023-03-03_12-52](https://user-images.githubusercontent.com/91037551/222642199-ee407583-513b-4df2-b901-05f0597b8d54.png)

### Environment

Production

### Version

Self Host

**Comment by pranavkanade** [comment]
Can you please try this once with the release branch?
