### ISSUE TITLE
[Feature]: Cursor notion changes to hand when hovered on table widget

### ISSUE THREAD

**Issue by swathida-byte** [appsmithorg/appsmith#21134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Cursor should not change when hovered on the table when the option is selected as no action to perform when clicked on the row in the table.

### Why should this be worked on?

When the action selected on click is no action then the cursor should not change as it gives false notion to the user

**Comment by somangshu** [comment]
Hey @swathida-byte 👋, thanks for bringing this here.
According to me this is not a valid issue. The row selection itself is an action, so the point of wether a action is set on row selection is moot.
