### ISSUE TITLE
Settings multiple triggers and executing them does not run all actions

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#21135]
https://www.loom.com/share/fe6edd34b1794fdcb4ea1aeffe481af0

**Comment by arunvjn** [comment]
ShowAlert function mentioned in the loom video has incorrect parameters.
Please test this scenario in https://ce-19689.dp.appsmith.com/

**Comment by AnandiKulkarni** [comment]
Verified in https://appsmith-bnl4i9ht4-get-appsmith.vercel.app/app/actionrefactor/page1-63a074cf8ee2c20625765e14/edit/widgets/c13jy0r6u4
