### ISSUE TITLE
Add below function for button widget and select non js mode, Try to add on success action >> it deletes entire action

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#21136]
{{(()=>{
	Api1.run((s)=>{
		Api2.run((s)=>{showAlert('success')}).catch((s)=>{console.log('failed')})
	}).catch((s)=>{console.log('failed API1')})
})()}}

**Comment by arunvjn** [comment]
Fixed in https://ce-19689.dp.appsmith.com/
