### ISSUE TITLE
[Bug]-[672]:Link a newly created entity from the action selector flow back to the action

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#21133]
On a page with no queries/API/objects, selecting to add a new entity as suggested does not default to the newly created entity as it does while adding a new modal widget

https://loom.com/share/7bda7f4e454c47b7953346c77ee1ac89
https://www.loom.com/share/7e4a7f767c7f4f079db0357ca19e5faf

**Comment by ravikp7** [comment]
This issue exists with the current production version of Action Selector. We'll not pick this up for the first version of the redesign. cc @bharath31 @satbir121

**Comment by ravikp7** [comment]
@bharath31 I think the current product behavior is correct, the `Add a new query` is just an outbound action. It takes to the query page and creates a new query, where the user can then fill in the details (path etc.). Assigning that newly created query to the action selector (from where it originated) without filling in the details seems non-intuitive to me.

What do you think?

**Comment by bharath31** [comment]
@ravikp7 The expectation/intent for a subset of users is to create a new entity and also link the action to the event. Evidence: 14% of users who create a new JSObject from the property pane end up manually linking it to the action. 8% of users do this for APIs/Queries. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 336 |
| Effort (months)  | 0.5 |

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/appsmithorg/appsmith/assets/94514895/e41a81d4-c45a-4a97-bf94-9b807ddd2d69
