### ISSUE TITLE
[Bug]: On giving a new user instance admin role, and then signing up with it, default workspace is not created

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#21145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On giving a new user instance admin role, and then signing up with it, default workspace is not created

### Steps To Reproduce

1. Login as demo@appsmith.com on a newly deployed instance
2. Go to Admin settings and in the General section -> Admin email, add aparna@appsmith.com
3. Now logout as demo and sign up as aparna@appsmith.com
4. Note that default workspace is not present. 
![instanceadminsignup](https://user-images.githubusercontent.com/101863839/222685996-921de59e-54e2-4a26-a5f4-5e1a4119a6ba.jpeg)

### Environment

Release

### Version

Self Hosted

**Comment by infinitetrooper** [comment]
@trishaanand - Can we debug this next week? Looks to be an intersection of Super User and RBAC.

**Comment by infinitetrooper** [comment]
If a new user is being added as Instance Admin, a default workspace need not be created as we treat them as existing users signing up.

The issue with Default Role for All users will be handled in the ticket #21723

**Comment by sharat87** [comment]
If this is a GAC-specific issue, can we confirm if this isn't present in CE? Or is that already verified?
