### ISSUE TITLE
[Bug]: Error: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by akhilak2023** [appsmithorg/appsmith#21157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have to execute an INSERT query on button click. Before that I have to check whether the data is already existing in the database table or not. So, in that button onclick action, added a checking condition before executing the INSERT query.

`checkEntries.run();
if(checkEntries.data[0].rowcount != 0){
showAlert('Data is already existing in the database', 'warning');
}
else {
    insertquery.run(() => {....
.
.
.
}`

Expecting the value 0 for `checkEntries.data[0].rowcount`.
But getting **TypeError: Cannot read properties of undefined (reading '0')** alert while clicking the button on first time. On second click, data will be inserted to the database.

### Steps To Reproduce

Error: TypeError: Cannot read properties of undefined (reading '0')
    at main.b9f229aa.js:2:1323760
    at d (main.b9f229aa.js:2:9004099)
    at Generator._invoke (main.b9f229aa.js:2:9003852)
    at Generator.next (main.b9f229aa.js:2:9004462)
    at d (main.b9f229aa.js:2:1238902)
    at Object.c [as cont] (main.b9f229aa.js:2:1239237)
    at m (main.b9f229aa.js:2:1237750)
    at t.cont (main.b9f229aa.js:2:1237317)
    at d (main.b9f229aa.js:2:1238947)
    at Jr (main.b9f229aa.js:2:1238695)

### Environment

Production

### Version

Appsmith Community v1.9.9

**Comment by pranavkanade** [comment]
@akhilak2023 this is not a bug. You are running an async function `run` and using the result on the very next line. I think you should use async-await there to make the exe serial. https://docs.appsmith.com/core-concepts/writing-code/javascript-promises
