### ISSUE TITLE
[Bug]-[1600]:the frozen custom columns are not retaining its position when we change to a different query

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 ISSUE 1 : the Save/discard button is not retaining its position when we change to a different query
https://www.loom.com/share/ee06eeba09c74985bb891b425b2e1810

ISSUE 2: when we have a custom column along with editable field, and then we change to a different query , UI breaks
https://www.loom.com/share/fc9cc430988941459c6a06cf3f933ac8

### Steps To Reproduce

ISSUE 1

1. DnD a table widget
2. make any column editable 
3. delete dummy data and add a fresh query 
you will see the wrong positioning of Save / discard

ISSUE 2: 
1. DnD a table widget
2. make any column editable and add one custom column
3. delete dummy data and add a fresh query 
you will see the wrong positioning of Save / discard

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@rajatagrawal can you check this out?

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1600 |
| Effort (months)  | 0.5 |
