### ISSUE TITLE
[Design]Update design of embed modal to communicate public and private embedding

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#21164]
Main issue: https://github.com/appsmithorg/appsmith/issues/20578

**Comment by Debsourabh** [comment]
Design task for issue: https://github.com/appsmithorg/appsmith/issues/20578

**Comment by infinitetrooper** [comment]
I closed the duplicate

**Comment by trishaanand** [comment]
The design has been completed.
