### ISSUE TITLE
[Bug]: when we drag to select widgets inside a container type widget, the popover (cut/copy/delete/group) is going beyond the actual height of the container

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when we drag to select widgets inside a container type widget, the popover (cut/copy/delete/group) is going beyond the actual height of the container

### Steps To Reproduce

https://www.loom.com/share/3a22363a65884edbaf5d02473cf87e80

### Environment

Production

### Version

Cloud

**Comment by ramsaptami** [comment]
this is a non-issue on anvil layout system hence closing it
