### ISSUE TITLE
[Feature]: Redis: The username and password should not get filled without the user selecting them.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

While editing a Redis datasource, the username and password is getting auto-filled.

https://knynrq7fk9.vmaker.com/record/p5hJGVU0G1teyknO

### Why should this be worked on?

If the user doesn't observe, then it might end up adding an invalid datasource as some unwanted username and password which is not required will get saved.

**Comment by Nikhil-Nandagopal** [comment]
This is not happening to me so I think you have a plugin or password extension that is auto populating this
