### ISSUE TITLE
[Bug]: Intermittent & incorrect error about being unable to run page load actions when there are no page load action configured

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a JS object with page load settings is deleted and replaced with another object with the same name but without page load settings, then performing page level actions like clone or delete causes an incorrect message to show up saying: `Failed to execute actions during page load`

### Steps To Reproduce

1. Create a page and add a JS object, set myFun1 to run on page load. Now `JSObject1.myFun1` now exists under pageLoadActions
2. Add a second object, `JSObject2`
3. Delete both objects created
4. Add a new `JSObject1`
5. Clone the page and notice an incorrect error show up
6. If above step fails, repeat steps above or delete cloned page to notice the error

**Successfully deleting the object that had page load setting** (Step 3)
![image](https://user-images.githubusercontent.com/79509062/223085231-e10c8df8-669d-4dab-a223-c8b4ca6c0478.png)

**Page1 clone action - page does not have any onPageLoad actions**
API: https://release.app.appsmith.com/api/v1/pages/clone/6405b67afec54a0ec59a44bf
![image](https://user-images.githubusercontent.com/79509062/223082348-f52b27d4-1bf5-442d-b906-02e92c365e6c.png)

**Response after deleting Page2 from video**
API: https://release.app.appsmith.com/api/v1/pages/6405b67afec54a0ec59a44bf
![image](https://user-images.githubusercontent.com/79509062/223082522-afa64777-1ad8-4f72-a0da-e57ebfc58926.png)

![image](https://user-images.githubusercontent.com/79509062/223083840-178921fd-75e7-41dd-9c68-3f9c8e3cadd8.png)

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
This appears to be a failure on the backend APIs. Cc: @subrata71 @nidhi-nair @riteshkew

**Comment by GabrielMarques89** [comment]
Is there any bypass for this ??

**Comment by riteshkew** [comment]
@GabrielMarques89 Are you blocked on this issue in any way? If you can provide the details around it, that would help us understand it better and provide the appropriate workaround.

**Comment by rohan-arthur** [comment]
I repeated the steps from scratch 5 times, and each time, deleted and re-cloned the page about 5-6 times and never saw this error. Closing this issue
