### ISSUE TITLE
[Bug]: Firestore DB - Timestamp Path shows up as required field, while it is actually not

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#21180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create a query - Add Document to Collection, to a firestore DB, the Timestamp Path field shows up as a Required field, while it is actually not. 

### Steps To Reproduce

1. Create a new Firestore Datasource from appsmith and connect to it
2. Create a new query - and choose Add Document to Collection
3. Here note that there is a field Timestamp Path and it is marked mandatory
4. However, even if it is not entered, the query executes. 
5. The required option needs to be removed from this field
![firestoretimestamp_prod](https://user-images.githubusercontent.com/101863839/223058384-36eaeaa6-6a2d-4345-a743-679efc514645.jpeg)

### Environment

Production

### Version

Cloud

**Comment by pranavkanade** [comment]
@rohan-arthur it's blocking a user - https://app.frontapp.com/open/cnv_yveqcy4?key=JRptqC7CkKORVSBJqd8kGtVKgjrTDSBg

**Comment by harshmange44** [comment]
@btsgh @Nikhil-Nandagopal Hey, I'd like to try to fix this
