### ISSUE TITLE
[Bug]: Rest API response - last line is truncated in viewport

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#21198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/94514895/223119984-5d1ee742-6d66-485d-8aaa-1138df6abc1e.mov

### Steps To Reproduce

1. run a rest api request that has a long response
2. scroll to the bottom
--> see that the last line is truncated

### Environment

Production

### Version

Cloud

**Comment by CKanishka** [comment]
@rohan-arthur Can you please assign this to me?

**Comment by sumitsum** [comment]
Hi @CKanishka apologies for the delay in response. Thanks for showing interest in contributing to Appsmith. Would you be interested in picking this up ?

**Comment by CKanishka** [comment]
@sumitsum Sure will pick this up

**Comment by sumitsum** [comment]
Thanks @CKanishka , I have assigned the issue to you.

**Comment by CKanishka** [comment]
@sumitsum I have raised the PR for this fix, can you please review it?

**Comment by rohan-arthur** [comment]
fixed with #29534
