### ISSUE TITLE
[Bug]: Scroll bar visible in the top toolbar of the table widget even when all the controls are visible in the set width

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#21192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are seeing a horizontal scroll bar in the top toolbar of the table widget even when all the controls are visible without scrolling. Also when we hover over the scroll bar, the with of the same increases.

### Steps To Reproduce

1. Go to the below app.
2. In the Feature list tab hover over the top toolbar of the table.

**Expected:** The scroll bar should not appear as all the controls are visible by default.
**Actual:** We are able to see the scroll bar.

### Public Sample App

https://app.appsmith.com/app/appsmith-regression-app/feature-list-63845f073e748351b7e6b224

### Environment

Production

### Issue video log

https://www.loom.com/share/2b9ad6df3aa14a62a51478e348b15b33

### Version

Cloud

**Comment by rahulbarwal** [comment]
@shadabbuchh Can you try this again? We were unable to reproduce this one.

**Comment by shadabbuchh** [comment]
@rahulbarwal I am not able to reproduce this as well. Since this is an old issue, maybe it got fixed with some other changes.
