### ISSUE TITLE
[Bug]: Api query inside Api query is not working

### ISSUE THREAD

**Issue by ravikp7** [appsmithorg/appsmith#21194]

**Comment by arunvjn** [comment]
Fixed in [e94e1b6](https://github.com/appsmithorg/appsmith/pull/19689/commits/e94e1b6d6b4235051c1fd47701e8385d47b52747)
Please test https://ce-19689.dp.appsmith.com/

**Comment by AnandiKulkarni** [comment]
Verified in https://appsmith-bnl4i9ht4-get-appsmith.vercel.app/app/actionrefactor/page1-63a074cf8ee2c20625765e14/edit/widgets/c13jy0r6u4
