### ISSUE TITLE
[Bug]: Misleading "Use Template" CTA in Add Page From Template flow

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#21200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Issue description**
When I try to use the "Add Page From Template" option in my app, I encounter a problem. After the templates modal opens, I click on the "+" button that says "Use Template" expecting to be directed to the page selection screen. However, the entire template is imported into my app instead.

**Expected behavior**
When I click on the "+" button, I expect to be taken to the section where I can select the specific page I want to add from the template.

**Additional information:**
Clicking on the entire template container works correctly and takes me to the Page Select screen for the template, but this is not inferred from the UI or UX.

### Steps To Reproduce

1. Click on the "+" button beside Pages in the left side bar of the editor.
2. Select "Add Page From Template"
3. Click on the Orange plus button that says "Use Template"

### Environment

Production

### Version

Cloud v1.9.9-SNAPSHOT

**Comment by Richarex** [comment]
@rahulbarwal 

- [ ] User is not able to add pages from the template when clicked on the **+** icon use template button. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/HJOyMPE9PNLIlcEK

**Comment by rahulbarwal** [comment]
Hey @Richarex, 
Currently I am able to add the page by following the steps in the video.
The server response might have been slow when you tried this, can you please try again?

**Comment by Richarex** [comment]
@rahulbarwal ,
will test it again

**Comment by Richarex** [comment]
This is working as expected, tested  **Use Template** complete flow on the DP url.

**Comment by rahulbarwal** [comment]
Fixed and available on release.
