### ISSUE TITLE
[Bug]: Appsmith not pooling connections correctly

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#21203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm running Postgres on Supabase.  Since Appsmith advertises it has its own connection pooler, I am connecting directly to the database instead of using Supabase's connection pooler.  (I even disabled Supabase's connection pooler in case this was causing the issue).

When working with Appsmith, there are (correctly) 5 connections with Supabase.  After a period of inactivity with Appsmith, if I start using it again it establishes 5 more connections, but the first 5 connections are not closed.  The connections with Supabase do time out eventually, but sometimes not before my connection limit is hit near the end of the day.

### Steps To Reproduce

1. Connect to Supabase's direct port (5432, not the pooling port 6543)
2. Have some activity in Appsmith
3. Run SELECT * FROM pg_stat_activity; on Supabase
4. See 5 connections from Appsmith
5. Wait some time (not measured exactly... maybe 30 minutes?)
6. Have some activity in Appsmith
7. Run SELECT * FROM pg_stat_activity; on Supabase
8. See 10 connections from Appsmith
etc.

My workspace has already been shared with your support@ address. Link to app is https://app.appsmith.com/app/suntronic-ordering-ver-2/assembly-team-63f9fd14cbd9da52c0b4d414/edit (please fork before making any changes),

### Environment

Production

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7xia4)

**Comment by sumitsum** [comment]
@eedwardsSGS can you please share if you were self hosting CE or BE edition of Appsmith or if you were connecting from cloud ?

**Comment by eedwardsSGS** [comment]
Cloud.
