### ISSUE TITLE
[Feature]: Disabled State for Input Text in the propertyPane

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#21206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Enable a disabled state for the PropertyPane Input Control

### Why should this be worked on?

The primary reason for this

- Using the hidden property makes the property pan controls jump, so the user sometimes will not know what disappeared till they toggle again.

- Disabling some of these properties might be a better way to convey the dependency information we want the user to know rather than making it hidden

**Comment by Nikhil-Nandagopal** [comment]
I believe this is against our UX which is to only show the properties required and unveil new properties based on configuration. As such since this goes against our current belief, I'm closing this. Please write up a doc that talks about the real benefit of this change if you believe it's necessary
