### ISSUE TITLE
[Feature]: Paginate /new API on home page to improve page load performance

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#21210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We should paginate the response for the /new API on the home page. This API should return a limited set of workspaces and applications in those workspaces. This would involve:
1. Splitting the data for fetching workspaces and list of applications in a workspace. This would help the home page load the left pane and the main pane separately. 
2. Limit the number of workspaces and apps inside a workspace. This is because all the applications aren't shown above the fold. Loading limited data will help improve a user's time to interative. 

### Why should this be worked on?

The home page load is slow for users who have access to a lot of applications and workspaces. This is a poor experience for them. If we paginate the data, it will help us scale the home page to heavy users who use Appsmith to build a lot of applications.

**Comment by deepika-appsmith** [comment]
With the recent revamp of the homepage, we've introduced the "home" API, which furnishes comprehensive details about the workspaces. Additionally, the apps and packages are retrieved using other APIs upon selecting a workspace. The integration of consolidated APIs has notably enhanced performance. Therefore, it's evident that we've successfully achieved the intended outcome. Hence closing the ticket.
