### ISSUE TITLE
[Bug]: On opening git sync modal the application crashes in a particular app

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#21237]
https://release.app.appsmith.com/applications/623eecd66c86dd5be6fdd191/pages/623eecd66c86dd5be6fdd194/edit?branch=master, also I just noticed on opening git sync modal app is crashing, but its not reproducible in other apps.

_Originally posted by @Parthvi12 in https://github.com/appsmithorg/appsmith/issues/14829#issuecomment-1449386392_

**Comment by Parthvi12** [comment]
Reopening issue as commit is throwing error, this issue is observed in few other apps as well
https://user-images.githubusercontent.com/80334441/224339276-a85b4f04-aa49-420b-b2a1-132964e862d1.mov

**Comment by akash-codemonk** [comment]
@Parthvi12 I don't think the issue you mentioned is related to this issue. 

Regarding the issue it seems like a valid issue, but I am not sure what it means though. It indicates that we have to refresh, does that work? @AnaghHegde Any idea what the error means?

**Comment by Parthvi12** [comment]
@akash-codemonk  Yes I accidentally deleted the repo connected to this app, maybe thats the issue, closing it. But I am seeing this issue in other apps which were throwing internal server error initially , and whose git repo also exist in github.

**Comment by akash-codemonk** [comment]
> But I am seeing this issue in other apps which were throwing internal server error initially , and whose git repo also exist in github.

In that case please create a separate issue for this.

**Comment by Parthvi12** [comment]
> In that case please create a separate issue for this.

Yes filed it here https://github.com/appsmithorg/appsmith/issues/21338
