### ISSUE TITLE
Unable to import JSON file of an exported application

### ISSUE THREAD

**Issue by akhilak2023** [appsmithorg/appsmith#21231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I tried to import a JSON file of an AppSmith Apllication into a workspace, getting an error: **Unable to import application in workspace 63173ca*************5cfc**

`{"responseMeta":{"status":400,"success":false,"error":{"code":"AE-JSN-4049","title":"BAD_REQUEST","message":"Unable to import application in workspace 63173ca*************5cfc, ","errorType":"Unable to import application in workspace"}},"errorDisplay":"AE-JSN-4049: Unable to import application in workspace 63173ca*************5cfc, "}`

I was able to import the same JSON file 2 months back.
Tried with exported JSON files of different AppSmith applications which I had created and unable to import it.

### Steps To Reproduce

Export an Application from an AppSmith instance and import into another AppSmith instance.
This issue is getting in AppSmith v1.9.9 and when I tried to import the same file in AppSmith v1.7.14, it worked as expected.

### Environment

Production

### Version

Appsmith Community v1.9.9

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8aimk)

**Comment by pranavkanade** [comment]
@akhilak2023 could you please reach out to us on support@appsmith.com or discord? I think we need to look at the server logs to figure this out.

**Comment by franciscobonand** [comment]
Any news on this issue? The same error happened in my self-hosted AppSmith v1.9.9

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/msg_1p8c8pqk?key=6efDEDiTDESBNuCubACvFUHY7AlrTXZV) is facing this error.

**Comment by infinitetrooper** [comment]
An update on this: We're adding additional information to help us debug this issue in the next release, it should be released next week, and I will update this thread when it does. Once it's released, we request you upgrade to this version so we can debug and fix this issue on priority.

**Comment by franciscobonand** [comment]
Was able to solve this error by changing Mongo's `readPreference` to `primary`

**Comment by infinitetrooper** [comment]
Update: One scenario where we've seen this issue is with custom MongoDB, please check the below configuration on your instance. We're updating our documentation with this.

In a multi-node configuration of a MongoDB cluster, the `readPreference=primary` URL parameter needs to be added to the MongoDB connection string. This is required to support the app's Import-Export feature.

**Comment by infinitetrooper** [comment]
@JonHerberOtto  - can you share the logs of the error to `support@appsmith.com`. We'll debug the problem.

**Comment by infinitetrooper** [comment]
This issue was closed with this ticket - https://github.com/appsmithorg/appsmith/issues/21126

**Comment by guireload** [comment]
> Was able to solve this error by changing Mongo's `readPreference` to `primary`

sempre salvando Chiquinho.
