### ISSUE TITLE
[Bug]: Documentation link for Connecting to Datasources from omnibar gives 404.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/223470015-ed10bd5c-4b7e-4022-a6ac-3115f261f37e.mov

### Steps To Reproduce

1. Go to an application
2. Open omnibar and click on search documentation
3. Observe for Connecting to Datasources docs, datasource, queries and APIs links give 404 error

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 can we fix these links soon?
