### ISSUE TITLE
Issues related to Button1.text parsing

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#21252]
- typed {{Button1.text}} and then after parsing, it goes to code as Button1.text
- Button1.text is not visible on the UI of the action selector

![Screenshot 2023-03-06 at 4.07.09 PM (1).png](https://images.zenhubusercontent.com/6234201cb4b245c0826acc70/f257c9c4-42fc-4a9a-b61a-d16bf850562a)

![Screenshot 2023-03-06 at 4.07.00 PM (1).png](https://images.zenhubusercontent.com/6234201cb4b245c0826acc70/241be0d0-9ad3-4868-9e34-0124090e38bd)

- added {{Button1.text}} from the UI as an argument for JSObject1.myFun2 and after adding it, the argument fields disappeared and not showing up anymore, even after reloading the app.

![Screenshot 2023-03-06 at 5.41.46 PM (1).png](https://images.zenhubusercontent.com/6234201cb4b245c0826acc70/03430ca1-3479-44ec-bb69-4ed5d7c9290b)

![Screenshot 2023-03-06 at 5.41.37 PM (1).png](https://images.zenhubusercontent.com/6234201cb4b245c0826acc70/65844dc4-cb04-456e-bb2a-15f1fc2b3ce0)

**Comment by AnandiKulkarni** [comment]
Verified in https://appsmith-bnl4i9ht4-get-appsmith.vercel.app/app/actionrefactor/pag111-63bd4d008c8d557f2f972a3a/edit/widgets/qtj5qx284w

**Comment by ramsaptami** [comment]
The second scenario where Button.text is added as an argument does not show up 
cc: @rimildeyjsr

**Comment by ramsaptami** [comment]
this is working
