### ISSUE TITLE
[Bug]: the page becomes unresponsive when the we increase the page size of the nested List

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the page becomes unresponsive when the we increase the page size of the nested List

### Steps To Reproduce

https://www.loom.com/share/271e75fc05364c2a8f6d4cc178dfdcc6

### Environment

**Release**

### Version

Cloud/Release

**Comment by Sripriya93** [comment]
Similar issue when nesting List widget inside a Modal widget(Checked the same in release)

https://user-images.githubusercontent.com/104895602/224025086-07bf9d21-5cb8-489f-8fbe-a646a89a026b.mp4

**Comment by kamakshibhat-appsmith** [comment]
https://github.com/appsmithorg/appsmith/issues/21268#issuecomment-1461982693

@Tooluloope @marks0351 @prsidhu We might have to take this at priority

**Comment by kamakshibhat-appsmith** [comment]
LGTM!
