### ISSUE TITLE
[Feature]: 是否有计划在未来接入echart呢

### ISSUE THREAD

**Issue by qinjie1314520** [appsmithorg/appsmith#21266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

我们可能更加偏向使用echart这种开源免费的组件的图表相比较于fusioncharts，所以想问问是否有计划接入echart？
另外通过改动源代码的方式是否能够较为简单的接入echart的一些组件作为Widgets，期待你们的回复

### Why should this be worked on?

更多的小部件，更自定义的小部件，免费开源的产品

**Comment by Nikhil-Nandagopal** [comment]
Hello, we're evaluating this here #4437 so I'm closing this as a duplicate

**Comment by lifeneedspassion** [comment]
https://github.com/cloudtogo/pageplug 中国版 appsmith 集成了 echarts
