### ISSUE TITLE
[Bug] Page delete is not working

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2126]
## Description
Deleting a page shows a success response from server but does not actually delete the page and is returned again on refresh

### Steps to reproduce the behaviour:

![ezgif-7-8c629d243885](https://user-images.githubusercontent.com/12022471/101754360-aa198900-3af9-11eb-9e88-4e7a7e952504.gif)

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu seems to be working for me. What are the steps?

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal Seemed to be only happening on older apps on release

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit seeing issues with backward compatibility

**Comment by trishaanand** [comment]
@hetunandu : I tried reproducing this issue with quite a few older applications but failed to do so. Could you share the app with me so that I can debug this? Thanks!

**Comment by hetunandu** [comment]
Not sure what app was this. Will reopen again if i see it happening
