### ISSUE TITLE
[Bug] The cursor on the table rows should become a click hand if the table onRowSelect property is set

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2127]
## Summary
`cursor: pointer` for table rows if selectable

## Motivation
To make it more obvious that rows are clickable

## Additional Context
Another option would be to add a checkbox

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena can you elaborate on this please

**Comment by rishabhsaxena** [comment]
I meant the CSS property `cursor: pointer;`, since table rows are clickable if they are bound to an action, we should update the mouse cursor when we hover over a row

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena great catch. seems to be a bug. It's working on edit mode but not on view mode If I'm correct?

**Comment by rishabhsaxena** [comment]
I'm noticing the same behaviour for both modes, checked on `app.appsmith` apps
