### ISSUE TITLE
[Feature]: Oracle intgeration: add core query execution flow

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#21274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

 add core query execution flow for the Oracle plugin

### Why should this be worked on?

 add core query execution flow

## How to test 
(1) Create Oracle DS using the credentials provided on Notion 
(2) Test that the datasource `test` passes for valid creds and fails for invalid creds
(3) Save the datasource
(4) create a new query on datsource
(5) Run a sample query on datasource eg. 
```
SELECT *
FROM 
    user_tab_cols
ORDER BY 
    table_name, 
    column_id
```

**Comment by btsgh** [comment]
A few observations - 
1. Schema not available. 
2. If I use admin with blank password, the test passes!

**Comment by sumitsum** [comment]
@btsgh thanks, 
(1) This is to be picked up later as mentioned in the PR description.
(2), (3) - thanks for catching this - I will try to address it in the next PR. Since these are minor issues we may move forward with current PR as we are merging changes under a feature flag right now. 
(4) Not sure how to address this . Will check with FE folks and try to address this on one of the next PRs. 
(5) Will try to update the logo in one of the next PRs.
