### ISSUE TITLE
[Bug]: connection refused:localhost 27017

### ISSUE THREAD

**Issue by wengad82** [appsmithorg/appsmith#21281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

stop 1.9.9 docker contanier
and run 1.9.10 image base on 1.9.9 volume,it show can't connect to mongodb
![图片](https://user-images.githubusercontent.com/19250813/223942713-5bb255d3-19cf-4cec-b206-1274a2304cfd.png)

### Steps To Reproduce

1、stop v1.9.9 docker contanier
2、and run v1.9.10 image base on v1.9.9 volume,it show can't connect to mongodb
![图片](https://user-images.githubusercontent.com/19250813/223942713-5bb255d3-19cf-4cec-b206-1274a2304cfd.png)

### Environment

Production

### Version

1.9.10

**Comment by pranavkanade** [comment]
@wengad82 can you please share the full logs? Checkout this doc - https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-get-container-logs

**Comment by amarizky** [comment]
Have you tried using `host.docker.internal` instead of `localhost` or `127.0.0.1`?

**Comment by masterbalby2** [comment]
> [@wengad82](https://github.com/wengad82) can you please share the full logs? Checkout this doc - https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-get-container-logs

here are the requested logs. thanks

[logs.zip](https://github.com/user-attachments/files/20673081/logs.zip)
