### ISSUE TITLE
[Bug]: [Auto layout] Tab widget jumps while switching from one tab to another

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#21300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we drag and drop a tab widget and dnd some widgets inside the tab widget in both tab, now switch between tabs, we are able to see the a jump.

https://user-images.githubusercontent.com/104895602/224015059-70ee6a89-6c30-470f-b292-96962c12adcd.mp4

### Steps To Reproduce

1. Dnd a tab widget
2. Dnd some widgets in both tabs
3. Switch between both tabs
4. Observe a jump

### Environment

Deploy Preview

### Version

Appsmith Community v1.9.11-SNAPSHOT

**Comment by prsidhu** [comment]
@Sripriya93 TabsWidget exhibits this behaviour on release and prod as well. Can you confirm whether this is a bug?

**Comment by Sripriya93** [comment]
@prsidhu I couldnt observe the jump in Prod, but I think its specific to Auto layout mode alone. There is a clear difference when we switch tabs in Auto layout and fixed layout. Below loom is from prod and its same for Fixed layout. But in Auto layout we are able to see the behavior same as given in the above loom.

https://user-images.githubusercontent.com/104895602/231862503-d78f0a42-2e64-4b52-95b1-dab2fedab825.mp4

**Comment by prsidhu** [comment]
@marks0351 Can you take a look at this one?
