### ISSUE TITLE
[Bug]: Uncaught reference error: JSObject is not defined at eval

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#21303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user is facing this error while calling a JSObject function within a Promise.all block

Error: `Uncaught (in promise) ReferenceError: JSObject is not defined at eval`

### Steps To Reproduce

--

### Environment

Production

### Issue video log

https://drive.google.com/file/d/1HH2FWHgnFUnGgm2HodbyC2R3EwJL3U9G/view

### Version

Cloud

**Comment by bharath31** [comment]
@satbir121 could we run an RCA on this?

**Comment by Rishabh-Rathod** [comment]
I was able to reproduce this issue. The root cause was the `FunctionDeterminer.ts` class on `close` used to remove the entity from the global context. 

We are adding the fix for this [here](https://github.com/appsmithorg/appsmith/pull/20890/files#r1142968080)

**Comment by Rishabh-Rathod** [comment]
This is fixed with JSObject mutation PR.
