### ISSUE TITLE
[Bug]: Launching the forked and duplicated apps, throws 503 error

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/224226035-4d791737-d7bb-4cdd-b0af-bb27ab452f1f.mov

### Steps To Reproduce

1. Go to home page
2. Duplicate/fork an app
3. Launch forked app, observe error is thrown

### Environment

Deploy Preview

### Version

Deploy preview

**Comment by nayan-rafiq** [comment]
@Parthvi12 this bug is present in our current release also.
