### ISSUE TITLE
[Bug]: Unable to place widgets next to nested containers.

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#21311]
Highlights are not visible to place widgets next to a container inside a container.

Here's a video demonstrating the issue:

https://user-images.githubusercontent.com/10436935/224229929-b12d1c6f-1933-4386-aed8-192f40543089.mov

**Comment by kamakshibhat-appsmith** [comment]
@aswathkk can you pls check, it is still difficult to see indicators next to nested container

**Comment by kamakshibhat-appsmith** [comment]
@prsidhu Unable to see placement indicators in mobile viewport when dealing with nested containers

**Comment by kamakshibhat-appsmith** [comment]
New issues : 
1. Unable to see placement indicators in the innermost container when you scroll up the canvas a bit
2. The Placement indicators stats dysfunctioning for container )when you scroll up the canvas (related to 1. )
[LOOM](https://www.loom.com/share/4e1944e49a1b4874a7195660e5cb8368)

**Comment by kamakshibhat-appsmith** [comment]
New issues:
