### ISSUE TITLE
[Bug]: CI failure: Page randomly throws 503 on clicking welcome tour

### ISSUE THREAD

**Issue by Vijetha-Kaja** [appsmithorg/appsmith#21327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in CI, where on clicking on welcome tour button in homepage , page throws 503. Cannot be reproduced manually every time.
https://user-images.githubusercontent.com/119562824/224308636-614a6092-80f0-42d0-bfcb-92efd3abf86b.mp4

### Steps To Reproduce

1. Create a workspace
2. Create an app
3. Navigate to homepage
4. Click on welcome tour

### Environment

Release

### Version

Release

**Comment by Aishwarya-U-R** [comment]
Debugging reference:

https://user-images.githubusercontent.com/91450662/224618155-ba265436-442d-460e-8e97-fbf83842002c.mp4

Logs:
[dockerlogs-23.zip](https://github.com/appsmithorg/appsmith/files/10954034/dockerlogs-23.zip)
