### ISSUE TITLE
[Task - EE]: themes should inherit policies from applications when application related permissions are updated for roles.

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#21331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by RakshaKShetty** [comment]
reopening the issue As we are facing another critical issue from this fix,
The internal server error is displayed when user tries to create custom role
![image](https://user-images.githubusercontent.com/45958978/225572230-6b2bb32f-b237-4b39-a03d-b4063425d029.png)
