### ISSUE TITLE
[Bug] Patch API getting flagged on page load

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2133]
This API has been flagged as onPageLoad even though it's a PATCH API and its response is not bound to a view and it is being triggered by a widget
https://app.appsmith.com/applications/5fc8d29a357c3201e6a4f273/pages/5fc8d29a357c3201e6a4f275/edit/api/5fd212fe3261b502f6ce2536

**Comment by Nikhil-Nandagopal** [comment]
Update this might be due to copying an action to configure this but I don't remember if the previous action was explicitly marked onPageLoad.

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal I've been able to repro this by copying an existing API (which had onPageLoad set) but not by triggering the API call on button click. Invited you to this app to check repro steps:
https://app.appsmith.com/applications/5fbde54e58377818ddaec540/pages/5fbde54e58377818ddaec542/edit

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair yes that seems to be the issue. This is wrong since the API was not explicitly marked onPageLoad
