### ISSUE TITLE
[Bug]: UX papercuts for keypresses on JS object

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#21345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The JS object pane should support basic keyboard shortcuts that help developers write code faster and more effectively. These include: 
1. Pressing ESC when an autocomplete is open should only close the autocomplete menu. Right now, the user loses focus from the entire editor forcing me to use the mouse and regain my cursor position. 
2. Ctrl/Cmd + S initiates the browser's save page action. We should override it and display the same message as on the canvas. 
3. Cmd+click of an entity doesn't scroll the editor to the correct location. The cursor is put correctly but the editor doesn't scroll. This is confusing to the user. 
4. Auto format the code please. The keyboard shortcut to prettify the code opens an incognito window in Firefox. This causes frustration.

### Steps To Reproduce

1. Open the JS editor and perform any/all of the actions defined above to see behaviour.

### Environment

Production

### Version

Cloud/Self-hosted

**Comment by rimildeyjsr** [comment]
@bharath31 @satbir121 - we have separate tasks/issues filed for all the issues mentioned here. Closing this ticket in favor of the smaller tasks.

The tickets are mentioned here for quick reference - 
1. https://github.com/appsmithorg/appsmith/issues/21999
2. https://github.com/appsmithorg/appsmith/issues/22000
3. https://github.com/appsmithorg/appsmith/issues/22001
4. https://github.com/appsmithorg/appsmith/issues/22002

cc @mohanarpit
