### ISSUE TITLE
[Bug]: App settings pane doesn't show when user is not on canvas

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#21344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the application settings are opened from any non-canvas location, the settings drawer doesn't open. The behaviour of the settings pane should be consistent regardless of where it is open from.

### Steps To Reproduce

1. Open any application
2. Navigate to APIs/JS objects or any query
3. On the top left, click on the app name to open the dropdown 
4. Select "Settings"

We can see that the entity explorer closes, but the application settings drawer doesn't open on the right. This is a bug. 

### Environment

Production

### Version

Cloud/Self-hosted

**Comment by hetunandu** [comment]
This should be solved with the new Unified App Bar @kocharrahul7

**Comment by hetunandu** [comment]
fixed with #27534
