### ISSUE TITLE
[Bug]: Selecting a list item where an widget is fails to select that list item

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#21342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a list, there are a series of text widgets on that list.  I'd like my users to select a list item and then have a form populate with information about that item.

This generally works, but if the user clicks anywhere on the item where a widget exists, it does not select that list item.

This might make sense for a button or text input that the user is clearly meaning to select as opposed to the entire list item, but not for non-interactable elements such as text.  Even if it was an interactable element such as a button or text it should not be a problem to select that entire list element (and may aid in the user experience to notice what other elements are grouped with the text input).

### Steps To Reproduce

1. Create a list
2. Populate the list with a large text widget, but with the text "test" occupying a small portion of that widget
3. Deploy the app
4. View the deployed app
5. Click on the word test
6. Notice that the list item is not selected
7. Click on the empty space that is inside the test text widget but not on the word test
8. Notice the list item is not selected
9. Click on the list item in a space that is not inside the text widget at all
10. Notice the list item is now selected

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@eedwardsSGS we fixed the issue here #21409, this should be available in the next version
