### ISSUE TITLE
[Bug]: 503 Error and “Internal Server Error” Pops Up Until Clearing Browser Cookies

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#21353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A self-hosted user is getting 503 when trying to sign in. 
This error only gets resolved when they clear their cookies. 

On their console, they get an error saying -Token not active.

### Steps To Reproduce

1. Login to appsmith. 
2. Try to access other pages, we get a 503 on the self-hosted instance.

### Environment

Production

### Version

Cloud & Self - Hosted > 1.9.7

**Comment by Nikhil-Nandagopal** [comment]
Closing because I don't see any information that can help us debug or solve this
