### ISSUE TITLE
[Bug]: Active datasource listing: Show more button should become show less when clicked

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In the active datasource listing page, when the user clicks on "show more", the button name should be changed to "Show less" 

<img width="1440" alt="show more" src="https://user-images.githubusercontent.com/119847783/224718948-49f1376c-6ab3-4306-89b2-beac1d4371db.png">

### Why should this be worked on?

In general, show more is changed to show less as a good usability practice.

**Comment by Avi98** [comment]
This seem to be quick fix i can take this up if its okay

**Comment by girish6701** [comment]
Hi @AnandShahs123 

Is someone working on this issue?
If not, I can take up this issue.

**Comment by AnandShahs123** [comment]
@girish6701 i'm not sure if anyone is working on this issue

**Comment by sribalajig** [comment]
@girish6701 please assign this to yourself and work on it. It hasn't been picked up.

**Comment by iSatVeerSingh** [comment]
I want to work on this. can you assign me

**Comment by iSatVeerSingh** [comment]
I reproduced the issue

**Comment by iSatVeerSingh** [comment]
I am working on it

**Comment by zaineb-damak** [comment]
hello, i would like to work on this issue. can you assign it to me.

**Comment by iSatVeerSingh** [comment]
@zaineb-damak I am already working on it. Please read the code of conduct.

**Comment by iSatVeerSingh** [comment]
@AnandShahs123 can you please review my PR.
