### ISSUE TITLE
Support external CI/CD tools to deploy Appsmith Apps

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#21374]
Users would like to use Git code and external CI/CD pipelines to deploy Appsmith apps in production instances. This may be required as internal policies may prevent manual deployment (or) usage of a specific CI tool.

**Comment by infinitetrooper** [comment]
Discussion here - https://theappsmith.slack.com/archives/C02MUD8DNUR/p1678286993509089

**Comment by SidHiremath** [comment]
Did internal policies prevent manual deployment (or) usage of a specific CI tool. ?

Di you guys tested this?

**Comment by Nikhil-Nandagopal** [comment]
This is similar to #11522
