### ISSUE TITLE
[Task]: Make CodeScanner widget responsive

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#21378]
Code scanner widget has got "Scanner Layout" property which will change the layout of this widget from a camera like view to a button like view.

Button widget doesn't have a resize option and Camera should be resizable in vertical and horizontal direction.

**Comment by aswathkk** [comment]
@shastry-gg We need a product decision here.

**Comment by shastry-gg** [comment]
The decision has been updated on notion. Disabling the button view for 31 release
