### ISSUE TITLE
[Task]: tests for window listener

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#21379]
### Is there an existing issue for this?

Copy of https://github.com/appsmithorg/appsmith-ee/issues/1187

### Description

- [x] #21380
- [x] Clean up worker and main thread logic (right now, it's repetitive)
Watch out for handling error messages. (can we log into AppsmithConsole from the worker thread?)

https://theappsmith.slack.com/archives/C02JT9CSE6L/p1678367281902089
- cypress test overwrites `window.parent` (check if experimentalModifyObstructiveThirdPartyCode helps)
- unit test stringifies the callback (check if latest approach in handling callback helps)

**Comment by Richarex** [comment]
working as expected tested this on the DP url.
