### ISSUE TITLE
[Bug]: Evaluated pop up covers the field through which it gets triggered

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#21389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the GSheets query page, when we try to enter any query in the `Pagination Offset` field, the evaluated pop up blocks the view of the field making it difficult for the user to see what is being typed.

### Steps To Reproduce

1. Go to the GSheets page.
2. Select the desired `Spreadsheet` & `Sheet Name`.
3. Scroll down and enter a query in the `Pagination Offset` field.

**Expected:** If we try to enter a query in the field, the evaluated pop up should not cover up the field.
**Actual:** The field gets completely covered up by the evaluated pop up.

### Environment

Production

### Issue video log

https://www.loom.com/share/be14ecd6047c4d659c792eb198a39d81

### Version

Cloud

**Comment by bharath31** [comment]
@shadabbuchh I'm not able to reproduce this on production
