### ISSUE TITLE
Email verification of users

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#21387]
We need to verify the emails of signed-up users in self-hosted instances for an additional layer of security. This should be bundled with a default email service.

**Comment by RoopKrrish9696** [comment]
**Zeplin handoff link for the ticket:** @ginilpg @aakashDesign 
https://zpl.io/qyBelQ6

**Comment by akash-codemonk** [comment]
Subtasks
- [ ] Add a field to enable email validation
- [ ] On signup backend should validate if email validation is enabled. If yes redirect the client to the page where we show the  `Check your Inbox` UI.
- [ ] UI for Check your inbox. Company logo to be shown if custom branding is enabled on EE
- [ ] Api for client usage to resend email.
- [ ] Emails to be sent on signup. Note the differences in the template for EE and CE.

**Comment by shwetha-ramesh** [comment]
@NilanshBansal @hetunandu. Few things that are observed.
P.S : Testing in progress still

- [ ] Link expired screen different from designs. Also `Send new link` button appears small from rest of the other buttons.
![image](https://github.com/appsmithorg/appsmith/assets/92293815/ddd766d5-dd6e-405d-a000-117dab0220ee)

- [ ] On successful signup the user is taken to 'My first application' page and not `Welcome page`

- [ ] Signup with a new email id > verify user receives 'verification link' > click on `not you` > user redirected to login page > enter same email id and pwd > verify one more email is generated
https://www.loom.com/share/de1442b14f624d9fb4b9e8bc23b19c15

- [ ] `Back to sign up` link differs from Reset pwd page & designs
![image](https://github.com/appsmithorg/appsmith/assets/92293815/e54d3957-db49-4587-843e-2035955ce431)

- [ ] `Email already verified` screen the text background is short. A consistent width is maintained across all screens.
`Back to sign up` font color is different in 'Email already verified', 'Reset pwd' and in designs.
![image](https://github.com/appsmithorg/appsmith/assets/92293815/706f7250-7a8b-43af-ab41-2b8b05c3b7e1)
