### ISSUE TITLE
[Feature]: Improvements in stickiness of signposting

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#21403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Ensure signposting stays active until a user has **completed** either signposting OR onboarding on any app.

For now, it stays active until the user creates a new app, at which point it disappears.

### Why should this be worked on?

The conversion of users who do signposting is not bad, however, many users lose access to signposting when they go to their dashboard, and create a new app.

Ensuring that users are able to understand appsmith will be a major factor in users converting and beating retained.

**Comment by Richarex** [comment]
LGTM! verified it on release.
