### ISSUE TITLE
[Bug]: Commenting characters throw up parse error when GSheet query is run

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Comment a few lines in a GSheet query and observe the error displayed for parsing due to commenting characters. Disable commenting or display a clearer error text.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/225042744-4951b9a0-4d02-4145-94ad-0ed3af61e774.png)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami is this inside the JS or in the JSON? If it's in the JSON then this is not an expectation. Please re-open if it's the former
https://stackoverflow.com/questions/244777/can-comments-be-used-in-json#:~:text=JSON%20does%20not%20support%20comments,configuration%20file%20format%20for%20humans.
