### ISSUE TITLE
[Bug]:  onRowSelected should fire with “Default Selected Row”, but does no

### ISSUE THREAD

**Issue by Passana** [appsmithorg/appsmith#21402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I set “Default Selected Row” for a table to 0, the first line gets selected after updating the data source (which is fine)

But in that case, the “onRowSelected” does not fire. So I need to deselect the row, then select it again so that the event “onRowSelected” gets fired.
This is weird in terms of usability, as the user expects the event to fire (and update other data) when the default row gets selected.

What to fix: When "Default Selected Row" is set, then fire “onRowSelected” for this row when the data of the table gets updated

### Steps To Reproduce

1. Create a table, bind to data
2. Set "onRowSelected" event to show some data of the current selected row
3. Set "Default Selected Row" to 0
4. Update the data of the table
5. The first row is selected, bit the "onRowSelected" did not fire (as expected)

### Environment

Production

### Version

Self hosted 1.9.12

**Comment by pranavkanade** [comment]
@Passana I don't think this is a bug. AFAIK, we never had this functionality, to begin with.

Could you please describe your usecase here? Moreover, can't you get away with creating an init function using JS object.

**Comment by Nikhil-Nandagopal** [comment]
@Passana All event handlers fire only when a user interacts with a widget today. Do let us know if there was a use case we had not covered

**Comment by yonch** [comment]
Here is a use-case:
There is a large database with a hierarchy of tables: conference, talk, speaker. 

When the user selects a conference:
- onRowSelected for conferences triggers, the `talks` query runs.
- The `talks` datasource updates. TalksTable populates. The first talk is selected.
- onRowSelected on TalksTable does NOT fire, so the `speakers` query does not `run()`.

The result is a good update to TalksTable, but no update to SpeakersTable. It actually shows the speakers for the previous conference.. By triggering onRowSelected, it would be possible to cascade updates.

Is there a workaround to achieve this?

**Comment by Nikhil-Nandagopal** [comment]
@yonch this would be a suboptimal way of configuring the queries because the subsequent queries would only run once the next widget loads and that would lead to poor performance.
A simple way to achieve this would be
- When a user select a conference trigger a JS function
- This function should trigger a query fetchTalks
- After the query runs, fire a query fetchSpeakers by referencing the first talk returned in the fetchTalks query

Now simply bind the fetchTalks & fetchSpeakers to the individual tables.

Here's a doc on using javascript promises 
https://appsmith-docs-git-v-git-get-appsmith.vercel.app/core-concepts/writing-code/javascript-promises

**Comment by yonch** [comment]
Thank you for the explanation. I’ll try it out!

**Comment by Passana** [comment]
@Nikhil-Nandagopal 

Just checking your suggestion and in my eyes this is overcomplicating everything, because then I need 2 queries to fetch talks and 2 queries to fetch speaker: 

- one query that uses first conference row to get talks and one query to use first talk to get speaker
- and one query of each for the onRowSelected event of the user

= 4 queries (double) + 1 Javascript for something we could easily fix with one 2 queries only. 

It would be much more logical when the first row gets selected (by user or programmatically), the onRowSelected fires. 
Selecting programmatically or by user should not make a difference if you cascade the data. 

And I am using these cascading queries very often with appsmith and it's really annoying. The user has always to unselect/select the row to get the onRowSelected fired and to get the data populated to the next table.

**Comment by Nikhil-Nandagopal** [comment]
@Passana you just need 2 queries that are marked to run onPageLoad which read the selectedRow and trigger the same queries onRowSelected. You can add the JS function for abstraction and simplicity but you do not need double the number of queries.
