### ISSUE TITLE
[Bug]: Image that appears when no app is found in the homepage is not placed appropriately 

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#21401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When no apps appear based on the user's search, the image that is displayed should be more centrally aligned.
<img width="1440" alt="Screenshot 2023-03-14 at 4 51 29 PM" src="https://user-images.githubusercontent.com/39921438/225003501-bd40c657-07f2-43ac-ab7e-6c383e24d78a.png">

**Suggestion:** Can we have the Appsmith brand colours in this image?

### Steps To Reproduce

1. In the homepage, search for an app in such a way that no app has that name

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
No longer valid
