### ISSUE TITLE
[Bug]: Incorrect error displayed on GSheet query when inserting many but having selected 'Insert One'

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Incorrect error displayed on GSheet query when inserting many but having selected 'Insert One'

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/225041289-775f5d00-7422-42cd-ac44-6e2137f0f4ba.png)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami the error seems to be correct. Insert one expects a row object while insert many expects an array.
