### ISSUE TITLE
[Bug]:  JWT Malformed in Authenticate API with OAuth2.0 

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#21410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user has set up an authenticated API data source that uses OAuth 2.0 as the authentication type and has configured it to use the “Authorization Code” grant type. However, when making an API call with this data source, the API is rejecting requests due to an authentication failure, and the user has discovered that the access token Appsmith is sending is malformed. When switching to the “Client Credentials” grant type, the access token is not malformed, and calls to the API are successful. The user is seeking advice on how to resolve the issue with the “Authorization Code” grant type.

`Note: I suspect that this issue is due to the user's JWT token containing special characters, and Appsmith using encoding causing the new token with the encoding to be illegible for authentication`

slack thread: https://theappsmith.slack.com/archives/C0341RERY4R/p1678783039173719 

### Steps To Reproduce
The user provides us with the steps to reproduce this, in addition to a video, you can see it in this Frontapp link, I do not put it here because it is sensitive data.

FrontApp: https://app.frontapp.com/open/cnv_xtgdpcc?key=G07jmM9zPBbthx3spioepiFAcFLifmB5

### Public Sample App
[App](https://app.appsmith.com/app/cnv-xtgdpcc-jwt/page1-64131fe2d67ea94e3d9725ff)

### Environment

Production

### Version

Enterprise: 1.9.12 Enterprise / SNAPSHOT

**Comment by felix-appsmith** [comment]
Please update the steps to reproduce this issue. Do we have any workarounds to execute an OAuth 2.0 authentication from a JavaScript object?

**Comment by sumitsum** [comment]
> I update the steps to reproduce this issue. Do we have any workarounds to execute an OAuth 2.0 authentication from a JavaScript object?

@felix-appsmith it may be possible via 3rd party libraries, I think we have tried it in the past successfully for GSheet authentication.

**Comment by Nikhil-Nandagopal** [comment]
Closing this as we haven't heard back
