### ISSUE TITLE
[Bug] Deleting the last reference to an API datasource removes the datasource from the front end, but retains it in the database

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2142]
## Description
Once an API has been saved as a datasource, we should retain the datasource on the UI irrespective of whether the API exists anymore. Current behaviour makes it impossible to reuse a stored datasource and clutters the database

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create a new API
2. Save as datasource
3. Delete the API
4. The saved datasource also disappears, but an entry is retained in the database

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by nidhi-nair** [comment]
Also, the reference to this datasource still exists on the front end, which is evident when creating a new API (the option to reuse the datasource comes up as a type-ahead in the URL field). Looks like it's just the entity explorer area that ignores this datasource.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair this is being taken up as part of #1942 so closing this
