### ISSUE TITLE
[Bug]: resizing debugger causes log item to collapse

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#21423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have am sending an array of objects to `console.log()`.
When I expand one of these objects and then adjust the height of the debugger (to get a better view perhaps), my expanded object is getting collapsed.

### Steps To Reproduce

https://user-images.githubusercontent.com/94514895/225254158-89ff01bf-8f19-4897-a305-58806d73a1c0.mov

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
please tag @appsmithorg/query-js-pod if you wish to contribute a fix

**Comment by saiprabhu-dandanayak** [comment]
**@appsmithorg/query-js-pod** , i would like work on this issue.

**Comment by saiprabhu-dandanayak** [comment]
Hi **@rohan-arthur** , i have raised a pr on this issue , could you pls assign a reviewer for the same , i would happy to resolve the comments if any.
Thanks in advance.
