### ISSUE TITLE
[Bug]: SMTP: Not getting complete error message if the host address is left blank and the datasource is tested

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Complete error message is not shown if the user leave the host address filed as blank.

<img width="1440" alt="smtp complete message" src="https://user-images.githubusercontent.com/119847783/225238578-3fc47f25-9fad-42a2-b204-b888ddd9a5b0.png">

### Steps To Reproduce

1. Create an SMTP datasource
2. enter into all the fields except the host adress
3. click on test
observe - The error message which is coming from the backend is not fully shown

### Environment

Production

### Version

1.9.12

**Comment by sumitsum** [comment]
Hi Anand, this does not seem to be a bug, in case of multiple errors, only the first one would be shown in the toast IMO.

**Comment by subrata71** [comment]
Hey @sumitsum 
With the `error-handling phase 1` multiple toast messages are shown on the `datasource config` page. 

@ChandanBalajiBP Can you please confirm whether this applies to all the datasources?

**Comment by ChandanBalajiBP** [comment]
Yes, this applies to all datasources.

**Comment by ChandanBalajiBP** [comment]
But this issue was fixed with this [PR](https://github.com/appsmithorg/appsmith/pull/21304)
