### ISSUE TITLE
[Bug] Reusing a saved datasource does not auto-import the headers from the datasource in the API pane

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2143]
## Description
If a user saves headers with an API datasource, every instance of using this datasource should re-emphasize the use of these headers. They should be read-only headers displayed before all manually entered ones. These headers should also appear in the request tab of the output in the API pane.

### Steps to reproduce the behaviour:
1. Create a new API datasource, with headers
2. Create a new API that uses this datasource
3. Saved headers do not appear in this API
4. On running this API, the request tab does not show the saved headers as part of the request

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by hetunandu** [comment]
This will be implemented when we redesign the datasources page
