### ISSUE TITLE
[Task]: Create an IconName type for Icon in ds

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#21437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

With the new design system, we can import any remix icon, along with a bunch of custom icons. Write a type called IconName that is a subset of both these types. This will replace the [IconName type](https://github.com/appsmithorg/design-system/blob/7ccc2c232333836bff98d7c045e518bddad43528/packages/design-system-old/src/Icon/index.tsx#L468) that existed in ds-old. 

Revert [this commit](https://github.com/appsmithorg/design-system/commit/fac51028ac9d768ee1cf2f88c8b9f12cb16e4291) when you do so, and change the imports accordingly.

**Comment by jayeshchoudhary** [comment]
> Revert [this commit](https://github.com/appsmithorg/design-system/commit/fac51028ac9d768ee1cf2f88c8b9f12cb16e4291) when you do so, and change the imports accordingly.

This link is broken

**Comment by MrDBC** [comment]
>Revert [this commit](https://github.com/appsmithorg/design-system/commit/fac51028ac9d768ee1cf2f88c8b9f12cb16e4291) when you do so, and change the imports accordingly.

**Comment by MrDBC** [comment]
>Revert [this commit](https://github.com/appsmithorg/design-system/commit/fac51028ac9d768ee1cf2f88c8b9f12cb16e4291) when you do so, and change the imports accordingly.

could u plz update the broken link

**Comment by victor-echo-delta** [comment]
>Revert [this commit](https://github.com/appsmithorg/design-system/commit/fac51028ac9d768ee1cf2f88c8b9f12cb16e4291) when you do so, and change the imports accordingly.

reminder to fix broken link

**Comment by Narcos101** [comment]
the link is broken yet @tanvibhakta

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
