### ISSUE TITLE
[Bug]: Date picker pop-up calendar displaying only part

### ISSUE THREAD

**Issue by jomadata** [appsmithorg/appsmith#21448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a container onto which a date picker is added has a height of 6 rows and is located at the top of the display area, pop-up calendar only shows the bottom third of the calendar.
![Screenshot 2023-03-15 at 1 25 06 PM](https://user-images.githubusercontent.com/44227138/225391696-86ee6d58-8e4b-45ec-9216-7882fab99b44.png)

### Steps To Reproduce

1. Go to app editor
2. Create a narrow container that is around 6 rows high and spans across the whole field
3. Create another container right below the first one
4. Add couple of graphs to the top of the lower container, to have top area populated
5. Add a Date picker to the top container
6. Click on the date picker for the pop-up calendar

### Environment

Deploy Preview

### Version

cloud

**Comment by dilippitchika** [comment]
Hey @jomadata this only happens when the datepicker is in a container. We are tracking it here - https://github.com/appsmithorg/appsmith/issues/20487 we will fix this soon
