### ISSUE TITLE
[Bug]: The app begins to slow down on the cloud version when the app becomes complex

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#21467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when the user starts coding, performance is quite good but with time (as things become more complex), the response of their typing gets slower and slower. They have always had to wait a while until the text or code, that they write is the (https://www.loom.com/share/3cacb2cb93ec40cbb63fdc3095569246).
The app slows down everywhere: JS editor and widget editor
it was really good in the beginning and while coding their stuff it became slower and slower.

### Steps To Reproduce

1. Create a new app on the cloud
2. Build until things get very complex

### Environment

Production

### Version

Cloud 1.9.9

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_85wp8)

**Comment by Nikhil-Nandagopal** [comment]
@narhzih this is a little vague and hard for us to debug. Can you share an application that we can test the performance on?

**Comment by eco-monk** [comment]
@Nikhil-Nandagopal 
There's a slack thread where this is being discussed. The user has shared their app with the support account.

It is mentioned the user has a low config machine.
Probably why we weren't able to reproduce the behaviour locally.

We've created a fix based on the performance profile shared by the user.

https://theappsmith.slack.com/archives/C0341RERY4R/p1678863628299139
