### ISSUE TITLE
[Bug]: Toast 'Deleting application...' is not centered

### ISSUE THREAD

**Issue by meetwithyash** [appsmithorg/appsmith#21476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I do delete any application, the toast 'Deleting application...' comes at the top; But it is not centered horizontally (it is more towards the left).

<img width="1680" alt="toast-screenshot" src="https://user-images.githubusercontent.com/32828966/225598256-c2f01ada-5848-4e27-a8e5-ab14c1d12bad.png">

### Steps To Reproduce

1. Go to the main dashboard
2. Delete any existing application and observe the 'Deleting application...' toast position

### Environment

Production

### Version

Cloud

**Comment by meetwithyash** [comment]
@Nikhil-Nandagopal , Also, can I pick this up?

**Comment by dilippitchika** [comment]
Hey @meetwithyash thanks for adding the bug and showing interest to contribute, yes you can pick this up

**Comment by meetwithyash** [comment]
@Nikhil-Nandagopal @pranavkanade @dilippitchika , I have looked over this issue. The Toast component is part of the old-design-system npm package.

So shall I apply the CSS by using the class in the main client project?

**Comment by dilippitchika** [comment]
@albinAppsmith @tanvibhakta can you take a look here?
