### ISSUE TITLE
[Feature]-[756]:Automatically switch to bracket notation when an autocomplete result contains blank space

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#21473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to select an autocomplete result for an object key containing a blank space, automatically switch to bracket notation to avoid unexpected identifier errors on . notation

### Steps To Reproduce

1. Create an API that returns data with keys containing a space (eg: "first name")
2. Try binding this key on the property pane (eg: `{{API.data.first name}}`)
3. Notice binding failure due to Unexpected Identifier error 

Expectation: Automatically convert this to bracket notation to avoid this error. eg: `API.data["first name"]`

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
Report: https://mixpanel.com/s/2ZiyES

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 189 |
| Effort (months)  | 0.5 |

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 @satbir121 this is an enhancement rather than a bug since it isn't breaking existing functionality but is proposing a way to improve the experience
