### ISSUE TITLE
[Bug]: Inside the imported apps the custom themes are missing in the theme setting section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#21475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

inside the imported apps the custom themes are missing in the theme setting section
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/225596165-ce7dfa19-ff6c-45dc-b412-d65c1107752c.png">

### Steps To Reproduce

1. import a git connected app
2. click on app setting 
3. see the applied theme name 
4. the applied theme is not listed in featured themes section

### Environment

Production

### Version

release

**Comment by kamakshibhat-appsmith** [comment]
Closed as duplicate issue #14306
