### ISSUE TITLE
[Bug]: The custom themes are not displayed in the theme setting section when user create a new branch from master

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#21474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when user create new branch from master the newly created  custom theme is not displayed in the list 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/225594855-b5ef10ee-dab7-4745-b040-3b422e8929df.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/225595003-f51937b4-764a-41f2-a7bd-a164cdb89ac8.png">

### Steps To Reproduce

1. Create application
2. Customize the theme e.g. set primary color to black
3. Connect the app with Git
4. Create a new branch e.g. `dev` 
5. Change the primary color to something else on `dev` branch e.g. yellow
6. commit and push the `dev` branch
7. Go to `main` branch
8. Delete the `dev` branch
9. Checkout to the branch `origin/dev` 
10. Checkout to `main` again. Now, you should see primary color has been set to yellow. Although you’ve set black to `main` branch.
11. Delete the `dev` branch.
12. Refresh the page `main` branch. Now, check the primary color is set to default blue color. If you check the DB, themes set to `main` branch are deleted.

### Environment

Production

### Version

release

**Comment by dilippitchika** [comment]
I don't know if this is expected or a bug, @nayan-rafiq can you take a look?

**Comment by nayan-rafiq** [comment]
@dilippitchika Actually it's an expected behavior. We should turn this into a feature request.
