### ISSUE TITLE
[Bug]: Oracle Plugin issues found during QA

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#21487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is a bug with collection of issues found during the testing of Oracle Plugin [PR](https://github.com/appsmithorg/appsmith/issues/21274). 

### Steps To Reproduce

Refer the How To Test Section in [this](https://github.com/appsmithorg/appsmith/issues/21274) PR
While testing, found the following - 

- [x] Change name of plugin from `Oracle Plugin` to `Oracle`.

- [x] If I use admin user with blank password, the test passes.

- [x] Database name field should be shown as required field, since, if we leave it blank, it throws an error to the effect - missing database name.

- [x] This message is not seen on the Edit DS page. - Whitelist the IP 18.223.74.85 and 3.131.104.27 on your database instance to connect to it. Learn more

- [x] The Oracle logo image seems a little off - with some whitebackground - this is not consistent with the other logos
##
**While testing [this](https://github.com/appsmithorg/appsmith/pull/21744) PR, here are a few issues found:** 
- [x]  For the column with data type - timestamp with local time zone, interval year to month, interval day to second, raw(256),clob, nclob and blob - the values are garbled/different.

<img width="908" alt="other_garbled2" src="https://user-images.githubusercontent.com/101863839/228908784-79b517a8-6e28-4531-b862-54dc3c258523.png">
<img width="929" alt="other_garbled" src="https://user-images.githubusercontent.com/101863839/228908819-96f26e6f-c1cc-4b24-9e34-9e60902c642d.png">

- [x] The data displayed in the timestamp field is slightly different from what is displayed on the actual DB

<img width="187" alt="timestamp_db" src="https://user-images.githubusercontent.com/101863839/228906738-9fcf32e4-a708-416d-a61c-3ad9dcf22aeb.png">
<img width="252" alt="timestamp_appsmith" src="https://user-images.githubusercontent.com/101863839/228906746-057e3371-1c2c-44d8-baa7-12da030bad93.png">

- [x] The data displayed in the binary_float column is different from what is displayed in the actual DB

<img width="171" alt="binary_float_db" src="https://user-images.githubusercontent.com/101863839/228907942-d16e3e43-5b3c-4fe3-a4f6-10526bbe9cbe.png">
<img width="183" alt="binary_float_appsmith" src="https://user-images.githubusercontent.com/101863839/228907951-e0f2d172-a1e1-4769-8214-2d6dccef63a6.png">

- [x] Oracle logo needs to be changed. (It does not look like Oracle)

- [x] Found an issue of queries giving intermittent older responses/incorrect responses. Following couple of videos show the behavior -https://ddpa7mfuvv.vmaker.com/record/2ZLmcsM93YRDueE7
https://ddpa7mfuvv.vmaker.com/record/BMOQcZPP7VOkbNVa

- [ ] This particular select statement is giving errors, and am not able to select a row along with timestamp specified.
select * from test_ap_or where c_varchar2={{'7_varchar2'}}
and c_nvarchar2={{'7_nvarchar2'}}
and c_number={{6}}
and c_float={{161.09}}
and c_date={{'2002-11-04'}}
and c_binary_float={{161.09}}
and c_binary_double={{161.09}}
and c_timestamp=TO_TIMESTAMP({{'04-11-2002 09:26:50.124'}}) 
Note: The above select statement returns the correct row without the c_timestamp section added.
In this regard - we would need to investigate the usage of date time formats and details with regards this should be added to  the Oracle documentation so that the users know how to query for date time values.

- [ ] At present, the documentation links turn up empty when we access Documentation from Queries page

### Environment

Deploy Preview

### Version

DP

**Comment by btsgh** [comment]
On re-testing, found the following:

C_BLOB datatype is inserted as oracle.sql.BLOB@1ebc038f, but in the Oracle DB it is stored [BLOB]

**Comment by sumitsum** [comment]
Closing this issue as most of the issues are resolved, the pending ones cannot/should not be addressed and the documentation is in progress: 
- The datetime display follows the format that comes on official oracle cloud SQL console: 
![Screenshot 2023-05-01 at 1 10 29 PM](https://user-images.githubusercontent.com/1757421/235603352-120c8361-54e4-453b-b976-6a2ab1dbb00a.png)

- There is a [known issue](https://github.com/appsmithorg/appsmith/issues/14516) with client approximating very large numbers and deep fractional sequences.
- The raw and blob types display has been fixed, in order to read them properly uses need to write command like `select utl_raw.cast_to_varchar2(c_raw) as c_raw, utl_raw.cast_to_varchar2(c_blob) as c_blob from TYPESTEST4`
- Created [another issue](https://github.com/appsmithorg/appsmith/issues/22898) to track improved usage for inserting datetime values.
