### ISSUE TITLE
[Bug]: SMTP: Email is getting sent even if the email is wrong in "from email" in the query

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user provides an email which is different from what he has configured in the SMTP datasource, the email still get sent.

### Steps To Reproduce

1. Create a valid SMTP datasource
2. user an email id - say abc@gmail.com
3. Create a query
4. Give an email id - say abc1@gmail.com in the "from email" field

Observe - The email will be sent

### Environment

Production

### Version

1.9.12

**Comment by Nikhil-Nandagopal** [comment]
Hello,

This is expected. The datasource cannot validate whether an email actually exists before it sends it.
