### ISSUE TITLE
[Bug]: Linting incorrectly sees NULL as undefined

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#21494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have an insert SQL statement and one of the rows is this:
`{{appsmith.URL.queryParams.line2 ? decodeURIComponent(appsmith.URL.queryParams.line2) : NULL}}`

Linting says this is an error ("NULL" is not defined) and is increasing my error count. However when executed everything actually works properly.

Replacing it with `null` removes the linting error, but instead returns this error when executed:
`Uh oh! This is unexpected. Did not receive any information for the binding appsmith.URL.queryParams.line2 ? decodeURIComponent(appsmith.URL.queryParams.line2) : null. Please contact customer support at Appsmith.`

Replacing it with `'NULL'` removes the error and it executes, but it adds the string `NULL` to my database instead of just nulling the field.

### Steps To Reproduce

1. Create an insert Postgres query
2. For one of the values create a ternary operation where the intended result is a null.
3. Try null, NULL, and 'NULL'
4. Execute and see the errors and look at the results in the database

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
@eedwardsSGS thanks for flagging this! 

`NULL` isn't a valid JS data type and changing it to `null` was the right thing to do. The query execution error is definitely something to be concerned about. Could you share the complete query for us to debug this? 

I tried following your steps on a Postgres query and it executed successfully 
```
INSERT INTO users (name)
VALUES(
    {{appsmith.URL.queryParams.line2 ? decodeURIComponent(appsmith.URL.queryParams.line2) : null}}
);
```

**Comment by bharath31** [comment]
cc: @sribalajig @rohan-arthur

**Comment by eedwardsSGS** [comment]
@bharath31 full query is:

`INSERT INTO batch
  (ship_to_recipient, ship_to_address_line_1, ship_to_address_line_2, ship_to_address_line_3, ship_to_city, ship_to_state, ship_to_zip, ship_to_country, date_created)
VALUES
  (
    '{{decodeURIComponent(appsmith.URL.queryParams.recipient)}}',
    {{appsmith.URL.queryParams.line1 ? decodeURIComponent(appsmith.URL.queryParams.line1) : NULL}},
    {{appsmith.URL.queryParams.line2 ? decodeURIComponent(appsmith.URL.queryParams.line2) : NULL}},
    {{appsmith.URL.queryParams.line3 ? decodeURIComponent(appsmith.URL.queryParams.line3) : NULL}},
    '{{decodeURIComponent(appsmith.URL.queryParams.city)}}',
    '{{decodeURIComponent(appsmith.URL.queryParams.state)}}',
    '{{decodeURIComponent(appsmith.URL.queryParams.zip)}}',
    '{{decodeURIComponent(appsmith.URL.queryParams.country)}}',
    '{{moment().format('YYYY-MM-DD')}}'
  )
RETURNING id;
`

Tested it again today and while `NULL` still works (and gives a linting error), changing it to `null` now works.  I will switch everything over to `null` and if it starts giving that error again I'll reach out.

**Comment by rohan-arthur** [comment]
@eedwardsSGS thanks for explaining the steps. Please reopen this issue and let us know if you're still facing problems
