### ISSUE TITLE
[Task]: Link the Error messages when a query execution fails with right documentation- part 1

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#21525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

When the user clicks on a documentation link in the error logs, they want to see documentation specific to the error that they are facing, so that they can debug the error better.

As part of Error handling phase 2 we are handling documentation in increments.
this task is to handle all the documentation that will be helpful for debugging appsmith error codes.

**Comment by rohan-arthur** [comment]
not planned, will address this when we are working on the debugger
