### ISSUE TITLE
[Bug]: JSONForm fileds configuration not shown in Chrome

### ISSUE THREAD

**Issue by wansadi** [appsmithorg/appsmith#21537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a big JSONForm and since yesterday, field configuration which is supposed to be shown on the right pannel cannot be found. I tried refreshing the whole page and even tried relogin but it didn't help.

![WX20230317-175415](https://user-images.githubusercontent.com/22144525/225873506-8297dd7a-7102-4820-ad6c-c675bd78c24e.png)

I switched from chrome to Firefox and somehow everything worked.
Is this a bug?

And by the way is there any workaround if I have a JSONForm of over 50 fields?  For now JSONForm just won't render if it's bigger than 50 fields.

### Steps To Reproduce

Use chrome and setup a JSONForm.
Not sure when it will happen.

### Environment

Production

### Version

Self hosted docker 1.9.7

**Comment by Nikhil-Nandagopal** [comment]
@wansadi can you check whether QueryScene.data.data has any response in it?

**Comment by wansadi** [comment]
> 

Yeah. I'm pretty sure the API works fine. For the form is rendered with fields returned by response.

**Comment by Nikhil-Nandagopal** [comment]
@wansadi can you share a screenshot of the evaluated value in the source data field?

**Comment by Nikhil-Nandagopal** [comment]
I believe this is due to #13165
