### ISSUE TITLE
[Bug]: Deleted page remains active and visible in edit mode while switching between branches

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#21540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

* Create two branches
* Switch to branch-2  from branch-1
* In branch-2, mark another page as homepage and delete the previous homepage. **Don't commit the changes**
* Go back to branch-1 and open the homepage
* Switch back to branch-2, this will  still show the old homepage which is deleted in branch-2

### Steps To Reproduce

1) Create two branches
2) Switch to branch-2  from branch-1
3) In branch-2, mark another page as homepage and delete the previous homepage. **Don't commit the changes**
4) Go back to branch-1 and open the homepage
5) Switch back to branch-2, this will  still show the old homepage which is deleted in branch-2

### Environment

Production

### Version

Cloud

**Comment by AnaghHegde** [comment]
This is happening because of behaviour in #20883. This will also be fixed automatically when we work on a fix for #20883
