### ISSUE TITLE
[Bug]: [Conversion Algorithm] Issue with size of nested Check box and Switch widget inside Tabs widget

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#21559]
When Checkbox and switch widget are placed inside a tab widget along with other widgets, we are able to that Checkbox and Switch widget are enlarged

![Image](https://user-images.githubusercontent.com/104895602/226164814-b24022a7-11b2-42e8-a4d7-337ed5e76c9e.png)

![Image](https://user-images.githubusercontent.com/104895602/226164828-ca4df9c8-b347-4da3-893d-9b97ba735b97.png)

**Comment by rahulramesha** [comment]
@Sripriya93 Could you please provide additional info for this, with reproduction steps
