### ISSUE TITLE
[Feature]: Standardise Page heights

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#21555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow for scenarios where single pages with only one button widget to be embedded without having a scroll.

### Why should this be worked on?

In Appsmith, the pages have been designed to have a minimum height, as the expectations have been that users would like to embed pages with complex use-cases, requiring larger heights in pages.

Due to user requests we need to reconsider this and conclude on how we would like to handle the minimum height of pages. The scenario brought to attention is where there is only one button widget on the page.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_87ljg)

**Comment by ramsaptami** [comment]
this has been fixed on the anvil layout system

![image](https://github.com/user-attachments/assets/8eba4651-46e1-4176-9f06-9ecbf6517032)
