### ISSUE TITLE
[Bug]: [Widget resizing] Able to resize Button widgets in Auto layout

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#21560]
In Auto layout we are not having any resize handlers for button widgets but we are able to resize them

![Image](https://user-images.githubusercontent.com/104895602/226174090-4c8b35bd-ae52-4421-9dea-a5d3aa677168.png)

**Comment by yaldram** [comment]
We have fixed this issue in the `feat/widget_responsive` branch we will soon merge it into `mobile/v1/qa` branch.
