### ISSUE TITLE
[Bug]: Appsmith Database connection URI in error messages

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#21568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When data integrity is violated in the case of `DuplicateKeyException` sensitive information like Appsmith URI is exposed to error messages. This is a big security risk that needs to be fixed, and any error message shouldn't display Appsmith server credentials. E.g. Screenshot below.

### Steps To Reproduce

1.  Navigate to the main page of Appsmith, where all the applications are located.
2.  Type the name of an existing application in the search bar and click on “search”.
3.  Click on the “Add new application” button, which will display an error.

![image](https://user-images.githubusercontent.com/114161539/226934499-e4f304d5-3b97-49d2-be83-e89fc73a469a.png)

### Environment

Production

### Version

1.9.10/ Appsmith v1.9.12-SNAPSHOT

**Comment by subrata71** [comment]
FYI, This is an existing behavior. Error-handling phase 1 doesn't have any impact on this. @riteshkew

**Comment by subrata71** [comment]
It’s hard to reproduce such issue. But I took this shortcut path to reproduce this.

Start with a new mongo database.
Create a JS Object in a page (That will be the first JS object in your new database)
Now create a unique index on `UNPUBLISHEDCOLLECTION.NAME` in `actionCollection`
Create another page in your first app
Now try to create another JS object
You will see a `DuplicateKeyException` error message in the toast

**Comment by btsgh** [comment]
Hi @felixsuarez0727   - Would it be possible for you to add steps to reproduce [this](https://github.com/appsmithorg/appsmith/issues/21568) issue so that QA can test it?

**Comment by felix-appsmith** [comment]
Hi @btsgh , I have updated the issue and added the steps.
