### ISSUE TITLE
[Bug]: Docker Compose - Cant start Container

### ISSUE THREAD

**Issue by Pacerino** [appsmithorg/appsmith#21564]
### Is there an existing issue for this?

- [] I have searched the existing issues

### Description

I'm trying to create a local AppSmith Instance with the provided `docker-compose.yml`. After running `docker compose up -d` im getting following error and the container exits itself.

```bash
appsmith-ce  | /opt/appsmith/entrypoint.sh: line 136:    14 Illegal instruction     (core dumped) mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"
```

OS: `Linux docker 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux`
Docker: `Docker version 23.0.1, build a5ee5b1`
Docker Compose: `Docker Compose version v2.16.0`

### Steps To Reproduce

1. Create a `docker-compose.yml` with the provided content
2. Run `docker compose up -d`

### Environment

Production

### Version

Self Hosted - Latest (v1.9.12)

**Comment by Pacerino** [comment]
Hey @sharat87,
thank you for the advice! Actually you were right. My Docker is running within a VM from Proxmox. The default processor dont expose the AVX instructions by default. You have to change the Processor Type to `host` so the AVX instructions are getting exposed to the VM.

The Container is now running successful. Thank you!

**Comment by sharat87** [comment]
Got it. I didn't know that, thanks for sharing. 🍰

**Comment by alber70g** [comment]
Can this be added to the community docs: 
- https://docs.appsmith.com/getting-started/setup/installation-guides/docker
- https://docs.appsmith.com/getting-started/setup
I've been searching for it wondering what would be the issue only to find it in this closed GitHub issue. Maybe adding it to the `entrypoint.sh` would be nice as well
