### ISSUE TITLE
[Bug]: [Auto layout] Issue with Stat box and Rich text editor

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#21561]
Step 1: Drag and drop Stat box and Rich text editor 
Step 2: Convert to Auto layout
Step 3: Drag and drop another Stat box and Rich text editor
Step 4: Delete the Rich text editor
Step 5: Observe the Stat Box is cut to half or more
Step 6: Drag and drop a Rich text editor
Step 7: Observe Rich text editor is collapsed

https://user-images.githubusercontent.com/104895602/227112057-043b53a8-6860-4a71-ac22-c52c23081f0b.mp4

**Comment by marks0351** [comment]
@Sripriya93 this issues doesn't seem to be reproducing now. pls check.
