### ISSUE TITLE
 [Feature]: Add events of appsmith startup and display

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#21574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This will help in user-experience and instead of 503 bland page in the start we can make user meaningful messages

### Why should this be worked on?

enhanced user experience

**Comment by Nikhil-Nandagopal** [comment]
@pratapaprasanna this is a poorly written issue. Can you please add a better title and description so we can understand what the feature is about?

**Comment by sum35h** [comment]
https://github.com/appsmithorg/appsmith/issues/21631
