### ISSUE TITLE
[Conversion Algorithm] for non-appsmith accounts, the canvas is still behaving like fixed one after running the conversion algo

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21589]
https://www.loom.com/share/34cea85741274996bc25534f2a387792

**Comment by kamakshibhat-appsmith** [comment]
Can you check the most recent DP , this is not fixed . Do we need to generate a new DP? @marks0351

**Comment by Sripriya93** [comment]
Conversion Algorithm isnt allowed in Non appsmith IDs, so above issue isnt relevant. Moving to done.
