### ISSUE TITLE
[Bug]: In Audit log The date range logic for past months seems wrong when the user selects the past month from date picker

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#21583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Audit log The date range logic for past months seems wrong when the user selects the past month from date picker
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/226280049-fd69fe95-f6c0-428f-83f4-cedbe2ebc7df.png">

### Steps To Reproduce

1. go to https://release-ee.appsmith.com
2. Now go to admin setting from home page
3. click on audit log
4. now click on the date range filter
5. select past month option
6. The date selection seems off here the total no of days is only 28 days

### Environment

Production

### Version

release-ee

**Comment by shadabbuchh** [comment]
@RakshaKShetty you see only 28 days selected as we have the month of Feb in that selection. If you try some other month(s) you'll see it selects 30/31 days.

**Comment by albinAppsmith** [comment]
@RakshaKShetty  That's right. We are using blueprint date range picker and that's how it is behaving.
https://blueprintjs.com/docs/versions/3/#datetime/daterangepicker

**Comment by RakshaKShetty** [comment]
This is working as expected closing the issue
