### ISSUE TITLE
[Bug]: code to UI

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#21588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1.  Write below code in JS and verify in Non JS mode
{{ appsmith.store.rand ? storeValue('rand', undefined) : undefined}}
https://user-images.githubusercontent.com/80756091/226307141-301a4616-6095-493b-af93-52c994f7477c.mov

2. Below code is not blocked and neither translated properly, its take from table widget and if you drag and drop table widget and try to select action page breaks
{{currentRow.step === '#1' ? showAlert('Done', 'success') : currentRow.step === '#2' ? navigateTo('https://docs.appsmith.com/core-concepts/connecting-to-data-sources/querying-a-database',undefined,'NEW_WINDOW') : navigateTo('[https://docs.appsmith.com/core-concepts/displaying-data-read/display-data-tables',undefined,'NEW_WINDOW')}}](https://docs.appsmith.com/core-concepts/displaying-data-read/display-data-tables',undefined,'NEW_WINDOW')%7D%7D)

3. Standup app add new updated submit button - select UI mode and add new window for navigate to changes are not updated
{{createStandup.run(() => {
  showAlert('Successfully submitted your update', 'warning');
  navigateTo('Todays Updates');
}, () => {
  showAlert('Oops! Seems like we have a bug to fix :|', 'success');
}).then(() => {}).catch(() => {});}}

4. .then and .catch is getting added for callbacks when you update the code
{Api1.run(() => {
  showAlert("hi");
  Button1.isVisible ? showAlert("visible") : showAlert("not");
}, () => {
  showAlert("error", 'warning');
})

### Steps To Reproduce

Updated given code on NON JS mode and verify it on UI

### Environment

Deploy Preview

### Version

cloud

**Comment by shwetha-ramesh** [comment]
All issues have been addressed. Moving to done.
