### ISSUE TITLE
[Feature]: Change focus on submit

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#21607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a form is submitted (or maybe just on demand), we should be able to direct what widget will be focused on.

### Why should this be worked on?

I have a form that I expect users to fill out 100+ times in a session.  They capture serial numbers and their barcode scanner is set up to enter the scanned number and press tab.  They capture three different serial numbers for each item.  When the form is submitted (either onBlur or just via the submit button) the focus should go back to the beginning of the form.  The goal is to reduce the number of inputs a worker needs to make.

This would also help with some of the inconsistency tab ordering with AppSmith.  (For example, if I have two input fields and a button from top to bottom, tab goes input1->input2->button.  If I add a table between input2 and the button tab goes input1->input2->table->button.  If I hide the table then tab goes input1->input2 then stops no matter how many times you press tab.  The solution to control focus for forms could also help control focus with these corner cases.

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS thank you for raising this. We have this feature tracked here so I'm closing this in favor of that #4874.
@bharath31 can we also handle when we solve for setMeta?
