### ISSUE TITLE
[Bug]: Unable Connect to an Airtable Datasource

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#21605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When connecting to a new Airtable datasource, the app crashes with the error `Oops! Something went wrong`.
The error displayed in the browser's console is `TypeError: Cannot read properties of undefined (reading 'startsWith')`.

![image](https://user-images.githubusercontent.com/101268423/226434932-d05d9de2-4120-4ceb-a255-0d016538bc3c.png)

### Steps To Reproduce

1. When inside an app, click the + sign next to Datasources.
2. Click on the Airtable datasource.
3. Note that the page `Oops! Something went wrong` gets displayed.

### Environment

Production

### Version

Appsmith Cloud v1.9.12-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_87h1o)

**Comment by rohan-arthur** [comment]
[RCA](https://www.notion.so/appsmith/RCA-Appsmith-crashes-when-creating-Airtable-datasource-0c3b46c6353b4e4db2d0c569f91d5879)
