### ISSUE TITLE
[Bug]-[400]:Tab titles cut into text

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#21606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/123981587/226459874-455cc2e3-4cd4-47b2-8c93-632fa5eff9dd.png)

![image](https://user-images.githubusercontent.com/123981587/226459970-adcea0dc-1980-405f-8574-7bb9e3238c68.png)

Tabs appears to be cutting off a portion of the text.  The first screenshot is from my screen, the second is from one of the users of the same widget.

### Steps To Reproduce

Create a tabs widget
Add a tab
Add another tab title "Send to Shipping"

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@rajatagrawal small issue here! Check if you have the time!

**Comment by iSatVeerSingh** [comment]
Can I work on this?

**Comment by Prateek32177** [comment]
Hi @eedwardsSGS  , I reproduced this issue it looks fine, I tested it with all the available options and responsiveness as well and it is not breaking, is there any specific scenario with available options where  its breaking ? please mention I will test.

**Comment by eedwardsSGS** [comment]
@Prateek32177 that's strange.  I have a copy of my app shared with the appsmith team [here](https://app.appsmith.com/app/fork-for-appsmith/assembly-team-6425af66f9c3d40f7b79a610/edit/widgets/h4lrxyi4kn).  Settings are: 
![image](https://user-images.githubusercontent.com/123981587/229598922-932c2097-c816-4c94-af65-904a8eeeb8e0.png)

![image](https://user-images.githubusercontent.com/123981587/229598963-f62ae051-23fe-4cfa-8626-28ffe8062942.png)

And it is pretty clearly cutting off the bottom of this 'g' on my screen.

![image](https://user-images.githubusercontent.com/123981587/229599063-57aef6b3-549f-469e-92ad-39e9de3a1e21.png)

(Worse on my team member's screen).

It may be an interaction with the browser.  I'm viewing it on Firefox (because Chrome has such poor performance when editing in Appsmith), when I view in Chrome it looks fine.

**Comment by dilippitchika** [comment]
<img width="318" alt="Screenshot 2023-04-13 at 10 02 30 PM" src="https://user-images.githubusercontent.com/19730984/231825693-09df78d1-960c-4b52-9e30-778bd75e73ef.png">

The second part is reproducible

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | 0.5 |

**Comment by priyanka-mahour** [comment]
I am able to replicate this, can I work on this?

**Comment by dilippitchika** [comment]
@priyanka-mahour thanks for showing interest, feel free to pick this up

**Comment by priyanka-mahour** [comment]
Please review this fix https://github.com/appsmithorg/appsmith/pull/22486/commits/f39bb4c5fe1784c9f581367237afd26cce825f0f

**Comment by dilippitchika** [comment]
@somangshu can you help get this fix added to our repo so that we can test it?
