### ISSUE TITLE
fix: Backup and restore will mistakenly overwrite the mongo uri

### ISSUE THREAD

**Issue by geekyme-fsmk** [appsmithorg/appsmith#21603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Today I did a backup and restore of my appsmith instance from one environment to another. I noticed that when I restored using [this guide](https://docs.appsmith.com/getting-started/setup/instance-management/appsmithctl#restore-appsmith-instance), I run into the follow mongo auth error on application startup:

```
backend stdout | [2023-03-20 11:45:45,481]  - Error in mongock process. ABORTED MIGRATION
backend stdout | io.mongock.api.exception.MongockException: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-256, userName='appsmith', source='appsmith', password=<hidden>, mechanismProperties=<hidden>}
backend stdout |        at 
```

After extensive debugging, I finally noticed that:
1. For a fresh startup of appsmith it will create a fresh docker.env.
2. I went in and I saw the mongo url is different from what was in the old instance's docker.env.
3. So after backup and restore, the docker.env mongo url changed to the old instance's value and of course it wouldn't work since the credentials does not match the fresh mongo instance credentials.
4. I went into the docker.env and changed the mongo url back to the new one that was created in step 1
5. Then it works.

### Steps To Reproduce

1. Backup an appsmith instance data
2. Restore it to fresh appsmith instance
3. See the mongo error
4. Fix docker.env value for the mongo url back to the original docker.env

### Environment

Production

### Version

Self Hosted - 1.9.12

**Comment by JSpiner** [comment]
same to me

**Comment by sharat87** [comment]
Moving from Critical to High, since this is not impacting production instances for users, but is still fairly important.

We have a fix in the works, and should be out soon. We'll notify here.

FYI, @sum35h.
