### ISSUE TITLE
[Bug]: Update the sender details for BE emails and remove the content in the intro email

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#21617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- When a BE email is triggered the developer wants to update the sender name in the emails
- In the first BE email, details of Appsmith should not be mentioned

### Steps To Reproduce

1. Create a new BE instance
2. Add a new user to Appsmith

### Environment

Production

### Version

Business edition

**Comment by dilippitchika** [comment]
https://community.appsmith.com/t/can-appsmith-branding-be-removed-from-registration-reset-emails-on-business-plan/2159

**Comment by pranayagarwal96** [comment]
As part of branding changes on email templates, we've fixed the issue around having no details of Appsmith in the email subject, body and email styling/branding is in-line with branding of the instance. 

However, sender name for all emails still comes as "Appsmith" which ideally should be replaced with the name of tenant
