### ISSUE TITLE
[Bug] Misleading preview of API actions' data field in entity explorer

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2161]
## Description

In the entity explorer under API actions, the `{{Api1.data}}` field's value shows a small preview icon. When the mouse is hovered over it, we get a preview of the value. This preview is incorrect. It shows the whole action response instead of just the body.

### Steps to reproduce the behaviour:

1. Create an API action (for example, to `http://httpbin.org/get`)
1. Save and run this action.
1. Expand this API action in the entity explorer and find the `{{Api1.data}}` entry.
1. Hover the mouse over the little preview icon near this entry in the entity explorer.
1. Compare this body with what `{{Api1.data}}` renders as, in a label widget.

Screenshot:

<img width="1481" alt="Screenshot 2020-12-11 at 11 45 45" src="https://user-images.githubusercontent.com/120119/101873755-84e65280-3bad-11eb-8597-3b3aa6a25f2f.png">

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 great catch!
