### ISSUE TITLE
[Bug]: Some java files start with 'Q' just like 'com.appsmith.server.domains.QPermissionGroup' can not be found

### ISSUE THREAD

**Issue by MosenHaleshao** [appsmithorg/appsmith#21624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![图片](https://user-images.githubusercontent.com/92716829/226562835-bac04774-91ca-4f6b-b445-075616604c27.png)
![图片](https://user-images.githubusercontent.com/92716829/226562969-9729033a-1153-4c07-a38c-96073a053361.png)
![图片](https://user-images.githubusercontent.com/92716829/226564494-fecf1563-60bb-487d-8a35-fb927bbd6f63.png)
![图片](https://user-images.githubusercontent.com/92716829/226565531-65276f8c-9dc2-4c14-8b25-7d36604080f4.png)

### Steps To Reproduce

git clone release branch and build project

### Environment

Release

### Version

1.9.12

**Comment by Bhavyashu** [comment]
Is there a way I can contribute to this bug?  Is this the right channel to approach?

**Comment by micarner** [comment]
I am trying to set up my local dev environment but am encountering this issue. Are there any more details here? Not sure how to resolve this.

Should a Q<name> class actually just be <name>?

**Comment by mttsun** [comment]
Could you share how to fixed this bug? thanks

**Comment by keepsl** [comment]
Is this issue still open? Just now I downloaded the latest code, this problem also appeared, please help

**Comment by keepsl** [comment]
> ### 这是否存在问题？
> * [x] 我已经搜索了现有的问题
> 
> ### 描述
> ![图片](https://user-images.githubusercontent.com/92716829/226562835-bac04774-91ca-4f6b-b445-075616604c27.png) ![图片](https://user-images.githubusercontent.com/92716829/226562969-9729033a-1153-4c07-a38c-96073a053361.png) ![图片](https://user-images.githubusercontent.com/92716829/226564494-fecf1563-60bb-487d-8a35-fb927bbd6f63.png) ![图片](https://user-images.githubusercontent.com/92716829/226565531-65276f8c-9dc2-4c14-8b25-7d36604080f4.png)
> 
> ### 重现步骤
> git clone 发布分支并构建项目
> 
> ### 公共示例应用程序
> _没有反应_
> 
> ### 环境
> 发布
> 
> ### 发行视频日志
> _没有反应_
> 
> ### 版本
> 1.9.12

Do you still have this problem? How did you solve it?

**Comment by micarner** [comment]
@keepsl you need to run the build command before those Q- classes are generated:
`./build.sh -DskipTests`

**Comment by keepsl** [comment]
> @keepsl you need to run the build command before those Q- classes are generated: `./build.sh -DskipTests`

Thanks! perfect solution
