### ISSUE TITLE
[Bug]: "Select a widget to bind" message stays on the screen unless the user refreshes the page

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After running an API or a query, if the user selects "Select widget" option through which he can bind the response to the desire widget, the message stays on the screen even if the user changes the screen.

### Steps To Reproduce

1. Run an API
2. Select "select widget" . it will take the user to the canvas.
3. Now, change the page and come back to the query / API page
Observe - The "Select a widget to bind message is still there"

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/JcpIvgZ8xII9CYOJ

### Version

1.9.12

**Comment by rohan-arthur** [comment]
changed layout, so this experience is not valid anymore
