### ISSUE TITLE
[Bug]: REST/ GraphQL: If there is a space before the API, it throws an error unlike postman where spaces before API/ URI is allowed

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

graphQL/ Rest API -  If there is a space before the API, it throws an error unlike postman where spaces before API/ URI is allowed.

### Steps To Reproduce

1. Click on query to add a new balnk REST/ GraphQL API
2. Say the API is - https://countries.trevorblades.com
3. Query is - query CountryFilterInput{
    countries{
        code
        name
        capital
        continent{
            code
            name
        }
		}
}

4. Give a space before the API
Observe - The error message is - Illegal character in scheme name at index 0:  https://countries.trevorblades.com

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/gUA53Sv4EnHPtHYq

### Version

1.9.12

**Comment by PiyushPushkar02** [comment]
Notion doc for the issue and fix :https://www.notion.so/appsmith/API-GraphQL-URL-With-Whitespaces-449a8fa4f3fa49e490b4b4b0fe5a16d1
