### ISSUE TITLE
[Feature]: The response section is not having a scroll bar for both Rest and GraphQL unlike postman

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The response section can have a scroll bar to show when the user scrolls up in case of a big response. 

video screenshot - https://knynrq7fk9.vmaker.com/record/R4vjeUFPWAijaWrd

### Why should this be worked on?

This will make the response section little more interactive.

**Comment by sribalajig** [comment]
@AnandShahs123 video is deleted

**Comment by AnandShahs123** [comment]
@sribalajig - https://www.loom.com/share/3b8b77d768694e1392eca2d20304ad6d

attaching the video again

**Comment by btsgh** [comment]
Tested and found to be fixed on release
