### ISSUE TITLE
[Bug]: Feching valid image url from google sheet throws error

### ISSUE THREAD

**Issue by choicio** [appsmithorg/appsmith#21645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Feching valid image url from google sheet throws "This value does not evaluate to type: base64 encoded image | data uri | image url"

![image](https://user-images.githubusercontent.com/6296495/226647111-f01f0b6e-18de-44bc-9c0e-c537cca0b633.png)

![image](https://user-images.githubusercontent.com/6296495/226647347-cdcbaa35-92a6-44fa-abdb-1be683a427b6.png)

### Steps To Reproduce

screenshots included

### Environment

Deploy Preview

### Version

latest

**Comment by Nikhil-Nandagopal** [comment]
@choicio it seems you are binding the entire array in the image. You need to bind a single image in the image widget. If you want to display all the images, you can use a list widget and place an image inside it. Then you can pass the array to the list and bind the image to each item in the array
