### ISSUE TITLE
[Bug] [Widget responsiveness]the icon widgets inside stat box is not adhering to the correct height in mobile view port in autolayout mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21659]
<img width="747" alt="Screen Shot 2023-03-27 at 9 25 54 AM" src="https://user-images.githubusercontent.com/113327629/227837187-1c5aaa23-c6f2-4537-a4d6-0048cd974896.png">

**Comment by Sripriya93** [comment]
Icon widget inside Stat box is in correct height. Working fine, moving to done.
