### ISSUE TITLE
[Bug] [Widget Responsiveness][Auto layout]The textbox overflowing the designated borders in mobile viewport

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21651]
https://www.loom.com/share/12798c9901954a42b315876004b08c5a

**Comment by Sripriya93** [comment]
We are still able to see the overflowing, moving to reopen

![Image](https://user-images.githubusercontent.com/104895602/228358739-16af0006-c92a-4a04-b3a5-319d61a15f5f.png)
