### ISSUE TITLE
[bug][Conversion Algorithm][Widget responsivness] the switchbox on running conversion algorithm is not adhering properly with the boundary boxes

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21656]
https://www.loom.com/share/adae2b64a925457ab32029915c46146a

**Comment by aswathkk** [comment]
This is happening for other widgets such as
- Range Slider
- Number Slider
- Category Slider
- Audio Widget
- Audio Recorder widget
- Checkbox widget
- Progress widget
- Divider widget

**Comment by Sripriya93** [comment]
We are still able to see the space below the widgets which has longer labels. Moving to reopen.



![Image](https://user-images.githubusercontent.com/104895602/228202264-42e1515e-a121-4a1f-8e54-1348f7a6b4e8.png)

**Comment by aswathkk** [comment]
@Sripriya93 Can you check it in the latest DP: https://ce-21386.dp.appsmith.com/
