### ISSUE TITLE
[Bug][Widget responsiveness] The switch box group is not fitting inside the borders in mobile view port

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21654]
https://www.loom.com/share/a751a25f9bab4f8a90864893f2745ea4

**Comment by Sripriya93** [comment]
For the above issue we arent having vertical resizer for widgets but when we have more widgets in a page, when we try to resize the viewport to Mobile, we are able to see whatever widget is placed at the bottom, Its cut. Moving to reopen.

https://user-images.githubusercontent.com/104895602/228351126-fc187169-0172-425e-8082-0e02eb2653f9.mp4
