### ISSUE TITLE
Mongodb count is not working 

### ISSUE THREAD

**Issue by sharanraj124** [appsmithorg/appsmith#2166]
## Description

I want to use `count` query in mongodb. when I try following, I am getting an error.

```
{
	"count": "users",
	"filter":{}
}
```
## Error
```
Command failed with error 40415 (Location40415): 'BSON field 'count.filter' is an unknown field.' on server mongo:27017. The full response is {"ok": 0.0, "errmsg": "BSON field 'count.filter' is an unknown field.", "code": 40415, "codeName": "Location40415"}
```

### Important Details
 - Version: [docker 2.1.0.4]
 - OS: [MacOSX]
 - Browser: [chrome]

**Comment by Nikhil-Nandagopal** [comment]
@sharanraj124 thank you for reporting this. Having a quick look at the mongo documentation, it seems filter is not supported as part of count. instead, the key is query.
https://docs.mongodb.com/manual/reference/command/count/

**Comment by mohanarpit** [comment]
@sharanraj124 Can you please try the following query:

```
{
	"aggregate": "users",
	"pipeline": [
		{
      $count: "userCount"
    }
	],
	"cursor": { "batchSize": 25 }
}
```

We use the `db.runCommand()` behind the scenes. You can read more about it at https://docs.mongodb.com/manual/reference/operator/aggregation/count/#example
