### ISSUE TITLE
[Bug]: showAlert message pops up on page load although js function is not set to run on page load

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#21689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ShowAlert message pops up on page load although js function is not set to run on page load

### Steps To Reproduce

1. Create a new API (with an incorrect URL, eg. https://jsonplaceholder.typicode.com/post)
2. Create JSObject1 with the following content
```
export default {
	myFun2: async () => {
		//use async-await or promises
		await Api1.run()
		return Api1.data
	}
}
```
3. Create JSObject2 with the following content

```
export default {
	myFun2: () => {
		//use async-await or promises
		return JSObject2.myFun2().catch(e=>{
		showAlert(JSON.stringify(e))
		})
		
	}
}
```

4. Reload the page, and see toast messagean 

### Environment

Production

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8asek)

**Comment by ohansFavour** [comment]
### Cause of issue

The toast is shown during the process of "dry running" a function to determine its nature (sync or async).

**Comment by arunvjn** [comment]
@ohansFavour I believe this issue should be resolved with the recent changes we have made. Could you please check and close this ticket ?
