### ISSUE TITLE
[Bug][Widget responsiveness] When we convert the List widget from fixed to auto layout (using algo), it dispays only the first list ITEM and rest data is not renderinf

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21680]
![Image](https://user-images.githubusercontent.com/113327629/226839379-6eb3530b-97fa-4504-a9d5-9e604234942f.png)

**Comment by Sripriya93** [comment]
List widget items are displayed. Working fine, moving to done.
