### ISSUE TITLE
[Bug]: S3: Generate page: After editing an image file with a PDF, the user is not able to download the PDF file

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user edits and upload a PDF to an existing image file, he is not able to download an open the same file.

### Steps To Reproduce

Steps:
1. Generate page with data for S3
2. Edit a file - (Preferable image)
3. Upload a PDF
4. Save
5. Download the file again

Observe - Its not showing the name of the PDF which was uploaded. Also, the PDF is not downloaded

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/eOgj8pzK6Cloepf5

### Version

1.9.12

**Comment by Nikhil-Nandagopal** [comment]
This is expected because you tried to overwrite an image with a pdf file
