### ISSUE TITLE
[Enahcement]: ExportWithConfiguration flag is ignored when forking app with Authenticated REST API Datasource

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#21691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When forking an app with an Authenticated REST API datasource, the new workspace receives a working copy of the datasource (with credentials intact) regardless of the `exportWithConfiguration` flag's value. 

This property is missing in the app JSON at first, so I tested all 3 states:
`exportWithConfiguration=true` 
`exportWithConfiguration=false` 
`exportWithConfiguration=undefined` _initial state_ 

In all cases, the new app continues to function with the API credentials intact in the new workspace. This flag is not being checked when forking an app. 

### Steps To Reproduce

1. Create an app with an authenticated API datasource
2. Enable forking of an app by setting `forkingEnabled=true` 
3. View the app from a different account, then fork it to a new workspace
4. Observe that the datasource is copied with credentials and the app continues to function. 

Note: The forkingEnabled and exportWithConfiguration flags are not exposed on the UI. These values must be set via MongoDB query. This can be done using the Template Uploader app. 

### Environment

Production

### Version

Appsmith v1.9.12-SNAPSHOT

**Comment by GreenFlux** [comment]
cc @rlnorthcutt @jacquesikot

**Comment by GreenFlux** [comment]
Updating after discussion with @AnaghHegde. 

**There are two forking methods:** Template-Forking (uses S3 JSON), and Non-Forking (copies the live app).  

Currently the `exportWithConfiguration` flag only works with template forking. We want to extend this functionality to forking non-template apps, and remove Datasource credentials unless `exportWithConfiguration=true`. 

In its current form, the non-template forking button is only visible to workspace devs/admins. We intend to add a UI control for the forking flag so users can make their own apps forkable by non-workspace members. This issue will add the UI control: https://github.com/appsmithorg/appsmith/issues/20569


Once this is possible, users should also have the option to share (or remove) their datasource credentials when their app is forked. Since this will be using the non-template forking method, we should update that method to also observe the `exportWithConfiguration` flag.

**Comment by AnaghHegde** [comment]
@NilanshBansal Can you take this up?

**Comment by rahulbarwal** [comment]
Few updates about this: 
1. We will be using `forkWithConfiguration` instead of `exportWithConfiguration` flag.
        a. This is done for security reasons, we want to keep `exportWithConfiguration` flag completely internal.
2. For this ticket to go through, #22390 is a pre requisite
3. Earlier this went through to release with #22087 & #22157 , but had to be reverted due to reconnection modal functionality not being present in the forking code(#22390 aims to solve that)

Once above PR goes to release, we will observe it for a week for any more bugs or missing functionality. If all is good, we will close this.

Thanks @NilanshBansal for your inputs.
CC: @rlnorthcutt @abm17 @GreenFlux @jacquesikot

**Comment by NilanshBansal** [comment]
This issue got completed as part of this PR: https://github.com/appsmithorg/appsmith/pull/22390
CC: @rahulbarwal @rlnorthcutt @abm17 @GreenFlux @jacquesikot @kocharrahul7
