### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kuntik17** [appsmithorg/appsmith#21701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Everytime i try to invite someone with e-mail and try to give admin privilege, app crashes and i am seeing a page says "Oops! Something went wrong"

![Screenshot 2023-03-22 at 22 52 13](https://user-images.githubusercontent.com/43724968/227021285-c8e07648-b2aa-41fb-a5f7-9c3fed64f915.png)

### Steps To Reproduce

1. Go to your app
2. Top right corner click share
3. Try to invite a friend..

I am using Brave browser.

### Environment

Production

### Version

Cloud

**Comment by pranavkanade** [comment]
@kuntik17, could you please raise this issue on our discord - https://discord.gg/whSRGsn5

We need more information to debug the problem, if we realize that it's a bug then we can reopen this issue again.
