### ISSUE TITLE
org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 10485760[Bug]: 

### ISSUE THREAD

**Issue by ppatel26** [appsmithorg/appsmith#21705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello. Am stuck with this `DataBufferLimitException` issue. I know there is a way to increase that for self hosted but cannot find any documentation around it. Below are the screen shot of the issue.  

![CleanShot 2023-03-23 at 00 21 52](https://user-images.githubusercontent.com/22735144/227102341-57990d3b-3619-4946-a01b-737c77efbaed.png)

![CleanShot 2023-03-23 at 00 22 30](https://user-images.githubusercontent.com/22735144/227102425-980056fd-5aee-4f30-a515-feac1066e7cc.png)

This was discussed on another thread 
https://github.com/appsmithorg/appsmith/issues/3704#issuecomment-810135735

Although this doesn't go into the fix. How and what do I set the `APPSMITH_CODEC_SIZE` variable value 

![CleanShot 2023-03-23 at 00 29 17](https://user-images.githubusercontent.com/22735144/227103378-60f3e7c1-ea20-4cae-891e-eb64d9447cd2.png)

Any help will be appreciated. Thank you 🙏🏻 

### Steps To Reproduce

![CleanShot 2023-03-23 at 00 23 47](https://user-images.githubusercontent.com/22735144/227102617-28927cd3-bdf5-4175-98a9-9d70cc36e02c.png)

Fetching a bunch of rows 

### Environment

Production

### Version

Ubuntu 18 x86_64

**Comment by pranavkanade** [comment]
@ppatel26 the default limit here is 5MB, although you can increase it to say 100MB by setting it to - `APPSMITH_CODEC_SIZE=100`

**Comment by ppatel26** [comment]
> 

Hey @pranavkanade I added this `APPSMITH_CODEC_SIZE=100` while starting the image 

![CleanShot 2023-03-23 at 15 56 14](https://user-images.githubusercontent.com/22735144/227336514-441f5a7e-b4aa-4805-859a-6136caa1feb5.png)

unfortunately, I am still getting the same buffer limit error

![CleanShot 2023-03-23 at 15 57 21](https://user-images.githubusercontent.com/22735144/227336849-3bbb2ace-8fff-46d2-997e-f9ac58037331.png)

**Comment by sribalajig** [comment]
@AnandShahs123 is you query returning a large amount of data? What is the approximate number of rows being returned?
