### ISSUE TITLE
Clean up the interface between widgets and the platform

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#21718]
Architecture note: These need to be either auto generated from the widget properties or defined in the widget configuration. This is because we need to make sure that all widget related configurations exist in the widget folder (these folders are the ones in `widgets` directory). That way, we can make sure widgets are pluggable components and don't have any dependency on platform code like this.

_Originally posted by @riodeuno in https://github.com/appsmithorg/appsmith/pull/21712#discussion_r1145857265_

**Comment by iamenrique** [comment]
Hi! I'm not sure how is you workflow, but I've just pulled the changes from latest `release` branch and noticed the following: https://github.com/appsmithorg/appsmith/commit/e775e300e6a6357a89871935f07ea15de53cfc79#r109736199

Just wanted to bring attention that comment. Thanks!
