### ISSUE TITLE
[Bug] The total number of people is not showing on Home page

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2171]
## Description

When the number of people exceed 5, we used to show an icon with a number +n on the home page
<img width="254" alt="Screenshot 2020-12-11 at 9 22 41 PM" src="https://user-images.githubusercontent.com/3897254/101924808-1d54f500-3bf7-11eb-8e10-435a4be82edd.png">

**Comment by Nikhil-Nandagopal** [comment]
@devrk96 how did this get removed?

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal Closing this as this has been fixed in #2070. Will be available in production in our next release.
