### ISSUE TITLE
[Bug]: For migration changes in git connected apps, after committing changes git sync modal shows option to commit and push again.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/227171633-566e00bb-91dd-4234-8313-d44a5bf4bac1.mov

### Steps To Reproduce

1. Go to an old app which has migration change like page modified.
2. Try to commit changes and observe.

### Environment

Release

### Version

Release

**Comment by AnaghHegde** [comment]
@Parthvi12 Can you share the git repo with me? I would like to see the changes in both the commits.

**Comment by AnaghHegde** [comment]
I see the two new properties in the git repo. 
`"unpublishedApplicationDetail": {},
  "publishedApplicationDetail": {},`
@NilanshBansal Is this something you have added recently? Do we require them to be part of a git repo?

**Comment by NilanshBansal** [comment]
@AnaghHegde yes these two fields have been added recently. These contain the App Navigation Settings and the App Positioning properties which need to be part of the git repo. These fields depend on the Git Branches

**Comment by AnaghHegde** [comment]
@Parthvi12 Are there any specific steps you can tell me so that I can reproduce this issue? I am unable to reproduce the issue with the older apps I have.

**Comment by AnaghHegde** [comment]
@NilanshBansal Please refer to this - https://github.com/Parthvi12/6144fb81/commit/37aa6340d65180b5b4f0aa4e8edab1ff867d61e1

**Comment by Parthvi12** [comment]
In older apps, on creating new branch git sync modal shows changes to commit, but there is no change log.

https://user-images.githubusercontent.com/80334441/227876634-4509f677-b6a1-4ac1-87d8-28bd838cd69b.mov

**Comment by AnaghHegde** [comment]
@Parthvi12 When you commit the changes what changes do you see? Is this related to App Navigation Setting?

**Comment by NilanshBansal** [comment]
@Parthvi12 @RakshaKShetty after merging to release, the issue is resolved now.
Checking on this app: https://release.app.appsmith.com/app/new-crud-page/page2-6319b203f0c54953d493e2c0/edit?branch=master

https://user-images.githubusercontent.com/25542733/228408134-551187fc-8106-44cc-b426-5b45cb643dae.mov
