### ISSUE TITLE
[Feature]: Provide an option to quickly navigate to a function within an object

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, we show all functions within an object in the dropdown option at the top and show async functions within settings but there's no easy way to navigate to a specific function. This becomes even more important when the object contains multiple large functions and the only way to navigate is either by manually collapsing other functions till you get to the one you're looking for or browser search and filter through all occurrences of that keyword.

### Why should this be worked on?

Better usability

**Comment by bharath31** [comment]
closing this in favour of https://github.com/appsmithorg/appsmith/issues/14151
