### ISSUE TITLE
[Bug]: On exiting from the Datasources page without saving changes, an error is thrown and the app becomes unresponsive.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#21734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On exiting from the Datasources page without saving changes, an error is thrown and the app becomes unresponsive.

### Steps To Reproduce

1. Add a new page
2. Navigate to any Datasource
3. Click on a different page and don’t save the changes
4. Notice that an error is thrown and the page becomes unresponsive 

https://www.loom.com/share/5845ca51597c4782b126ba8adfdff7cf

### Environment

Release

### Issue video log

https://www.loom.com/share/5845ca51597c4782b126ba8adfdff7cf

### Version

Production

**Comment by sribalajig** [comment]
@laveena-en I tried the steps you mentioned, but the error is not reproducible. Can you please share a video?
