### ISSUE TITLE
[Bug]: In business edition theme and other color pickers in app should show brand colors

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#21736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using business edition, we want to see the brand colors in app. This should be only shown for business edition and not cloud (app.appsmith.com)

### Steps To Reproduce

1. Set brand colors in branding
2. Go to an app and observe brand colors are not shown in color picker

### Environment

Production

### Version

Business

**Comment by jsartisan** [comment]
No no, brand colors won't be shown on cloud. i have added a check for it.
