### ISSUE TITLE
[Bug]: Remove the term free from BE sign up page

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#21737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2023-03-23 at 5 40 42 PM](https://user-images.githubusercontent.com/19730984/227199825-d58f1bc3-505f-490d-9d75-4bf8ff2b913c.png)
In the sign up page the word free in business edition throws people off

### Steps To Reproduce

1. Go to business edition sign up page
2. Observe the term free to create an account

### Environment

Production

### Version

Business

**Comment by kamakshibhat-appsmith** [comment]
Free word won't be available in cloud version, is this discussed? @jsartisan

**Comment by dilippitchika** [comment]
Yes @kamakshibhat-appsmith anyone who comes to signup page of cloud is mostly aware it's free

**Comment by kamakshibhat-appsmith** [comment]
Moving this to Done
