### ISSUE TITLE
[Bug]: Switch group is not working when added inside child List widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#21745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://bthrujcsw8.vmaker.com/record/OhAnsL396yYuo3SW

https://bthrujcsw8.vmaker.com/record/ZAHBaXLoYhAAInki

### Steps To Reproduce

1. Drag & Drop a List widget
2. Add another List widget inside List widget
3. Add Switch group on child List widget
4. Observe that Toggle are not responding on clicking

### Environment

Production

### Version

Cloud/Production

**Comment by chandannkumar** [comment]
> Hi @chandannkumar Could you confirm if this issue has been fixed?

Hi @Tooluloope , i can still see this issue on production
https://www.loom.com/share/15196252c3824f729699ab0e559c51b8

**Comment by Tooluloope** [comment]
> Hi @Tooluloope , i can still see this issue on production
> 
> https://www.loom.com/share/15196252c3824f729699ab0e559c51b8

@chandannkumar, could you use this dp
https://appsmith-1dqvj1sua-get-appsmith.vercel.app/

The fix was in this PR https://github.com/appsmithorg/appsmith/pull/22682

**Comment by chandannkumar** [comment]
@Tooluloope Tested on above DP and issue seems fixed now

**Comment by Tooluloope** [comment]
Fixed in #22682
