### ISSUE TITLE
[Bug]: Importing app from git shows uncommitted changes on opening git sync modal

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app which is connected to git which contains empty queries, is imported shows uncommitted changes on opening git sync modal. Refer: 

https://user-images.githubusercontent.com/80334441/227262020-d9a1af7d-9b53-4bad-97b6-f1a1a3c52661.mov

### Steps To Reproduce

1. Import an app from git which contain empty queries.
2. Open git sync modal and observe uncommitted changes are observed.

### Environment

Release

### Version

Release

**Comment by AnaghHegde** [comment]
@Parthvi12 The issue https://github.com/appsmithorg/appsmith/issues/21727 and this are related. And this should be treated as a release blocker.

**Comment by AnaghHegde** [comment]
@Parthvi12 Can you share the git repo or the commit diff where you have experienced this issue?

**Comment by Parthvi12** [comment]
@AnaghHegde Shared the repo with you: https://github.com/Parthvi12/685c9340

**Comment by RakshaKShetty** [comment]
@AnaghHegde the issue still present

**Comment by Parthvi12** [comment]
Removing the release blocker label as issue exists on prod as well.
