### ISSUE TITLE
[Bug]: Page name is displayed  as "NULL" in the Duplicate Key error

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#21754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user tries to create a application after searching for a name of an application thta does not exists the user is displayed with an error    

### Steps To Reproduce

1) Navigate to the main page of Appsmith, where all the applications are located.
2) Type the name of an existing application in the search bar and click on “search”.
3) Click on the “Add new application” button, which will display an error.
<img width="1280" alt="Screenshot 2023-03-24 at 1 28 56 PM" src="https://user-images.githubusercontent.com/71753653/227496862-022fc7ad-a28c-473d-8506-7b3510deeeb8.png">

### Environment

Release

### Version

Release

**Comment by sbalaji1192** [comment]
@sribalajig Please check the above comment.

**Comment by prapullc** [comment]
Closing the issue as it does not exist.
