### ISSUE TITLE
[Bug] `ctrl+c` copy behaviour

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2175]
## Description

When a user tries to copy content in the property pane, as the widget is selected and the user isn't focused in an input field, `ctrl+c` defaults to copying the widget. 

### Steps to reproduce the behaviour:
https://media.discordapp.net/attachments/760761686549463060/787297223263387688/copypasteIssueKeystrokes.gif

**Comment by mohanarpit** [comment]
Closing as duplicate of #2261
