### ISSUE TITLE
[Bug]: OAuth: It shows  "Datasource not authorized" after having it authorized 

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the user authorises / re-authorises the OAuth datasource, it shows "datasource is not authorized" on the datasource page.
Note - Used googlesheet API for this. Credential can be provided on demand

### Steps To Reproduce

1. Add an Authenticated API
2. Use Oauth 2
3. Use googlespredsheet API
4. Get it authorized
Observe - The error message is "Datasource is not authorized"

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/xX6aVqBZipgstcwi

### Version

1.9.12

**Comment by rohan-arthur** [comment]
closing this in favour of #21297 - please reopen if you think this is a separate issue
