### ISSUE TITLE
[Bug]: [Widget resizing] Nested Group widget resizing isnt smooth

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#21758]
Step 1: Dnd a container widget
Step 2: Dnd a fill widget and hug widget in same line (Check box group, Swtich group, Radio group)
Step 3: Try to expand the hug widget
Step 4: Observe the fill widget is taking the whole space while we resize the hug widget
Step 5: Once we release we are able to see the hug widget is expanded
Step 6: Same happens when we reduce the size of hug widget
Step 7: If we add more options in the hug widgets and resize, the resize isnt done properly
Step 8: Check zoom for more clarity on the issue.

https://user-images.githubusercontent.com/104895602/227550082-17fb312e-7d65-4820-bc2b-8f8466471757.mp4

**Comment by marks0351** [comment]
@aswathkk  Most scenarios in this bug work fine today except for one, when a widget loses height via resize handles its container does not shrink coz we have checks to update canvas only when there is an increase in net height of widgets.
If I use the canvas-resizer i see that the container immediately updates to proper expected height.
We need to use one architecture to update heights of canvas.

We have resize, cut/copy/paste, canvas-resizer all making changes to position and size of widgets based on mobile break point algorithm and min width checks. Right now these algorithms are also making changes to the underlying parent canvas of effected widgets. we need to delegate updating canvas of any kind to auto height module after position and size based updates are made by the above mentioned algorithms.
This would help us
- Maintain the code.
- Make sure all use cases like borderRadiusOffset calculation are also taken care of when calculating height of a canvas/droppable widget.

cc: @riodeuno
