### ISSUE TITLE
[Bug]: Error message not relevant when the datasource validity is tested without port number/ with wrong port number

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user validated the Arrango DB datasource without the port number/ with a wrong port numbe, Error message is -
 "Could not find required authentication info. At least one of 'Username', 'Password', 'Database Name' fields is missing. Please edit the 'Username', 'Password' and 'Database Name' fields to provide authentication info.""

There is no mention of the port number missing.

### Steps To Reproduce

Steps:
1. Click to add an arrangoDB datasource
2. Fill all fields like - host address, database name, username, password.
3. Keep SSL mode 'Enabled'
4. Keep use CA certificate 'Disabled'
5. Click on Test
6. Keep the port blank or enter a wrong port

Observe - The error message has no mention of missing port number.

### Environment

Production

### Version

1.9.12

**Comment by 239yash** [comment]
@nidhi-nair Can I pick this up?

**Comment by 239yash** [comment]
I guess, you have already solved this. Can you please suggest to me some open issues from the backend module which I can pickup?

**Comment by rohan-arthur** [comment]
will get fixed with #32136
