### ISSUE TITLE
[Bug]: SMTP: The user keeps getting mail after configuring and sending the mail once.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As a user, after having created a query with a subject line and a body, I am constantly being sent the same email from the last many days multiple times a day.

### Steps To Reproduce

1. Creata a SMTP datasource
2. Create a query to send mails

Observation - The same mail keeps coming without fail too many a times randomly without getting stopped.

### Environment

Production

### Version

1.9.12

**Comment by Nikhil-Nandagopal** [comment]
@AnandShahs123 please share the app where this is happening

**Comment by AnandShahs123** [comment]
@Nikhil-Nandagopal - https://release.app.appsmith.com/app/mydynamo/page1-63fdcfa7e925565a06932031

Please refer to the SMTP datasource in this app

**Comment by rohan-arthur** [comment]
I set up an app with smtp while testing workflows, and couldn't reproduce this anymore
