### ISSUE TITLE
[Bug] Postgres connection mode of `read-only` is not working.

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2178]

**Comment by sumitsum** [comment]
Looks like a driver issue. The read only setting is not taking effect when configured the following ways: 
```
- connection.setReadOnly(true);
- config.addDataSourceProperty("readOnly", "true")
- config.setReadOnly(true)
```

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum @trishaanand what's the solution here? This seems like a big issue that we are allowing a read mode property but it doesn't work

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal I have raised a fix for this : https://github.com/appsmithorg/appsmith/pull/5848 . It seems that there is some communication gap in the `HikariCP` and `Postgres JDBC` documentation. I had to dig through some pretty old GitHub  discussion on their page to figure this out.
