### ISSUE TITLE
[Bug]: ArrangoDB: for create query, the example given can be modified.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the example, it shows nameInput.text for an Email Input. This might be changed to emailInput.text for better user understanding.
<img width="1440" alt="arrango" src="https://user-images.githubusercontent.com/119847783/227906995-9a7d36ad-66cb-4c5a-8f48-b2b5fda3c16a.png">

### Steps To Reproduce

Steps:
1. Create a valid Arrango datasource
2. Click to create a create query

Observe - In the example given, it shows nameInput.text for an Email Input.

### Environment

Production

### Version

1.9.12

**Comment by rohan-arthur** [comment]
probably got fixed with another issue, closing this.
![Screenshot 2023-04-22 at 10.54.41.png](https://images.zenhubusercontent.com/6196337f2def7ccca841bb55/9cfdedd1-abf0-4e6e-a72a-4728f20b5933)
