### ISSUE TITLE
[Bug]: 503 Server Error when refresh token and access token expires

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#21795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a situation where the refresh token expires and the access token expires (when using OIDC authentication), Appsmith starts returning a 503 Server Error. We'll have to manually clear the cookies for this to work again.

### Steps To Reproduce

1. Steps To Reproduce
2. Setup OIDC Authentication
3. Wait for the access token to expire (About 24 hours after login)

### Environment

Production

### Version

Self - Hosted 1.9.12

**Comment by abhvsn** [comment]
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1679291499997049
