### ISSUE TITLE
[Bug]: Date type column does not format date according to users' choice and returns an invalid date error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The date type column on the table widget returns an `invalid date` or `invalid value` when deriving values from moment library and setting `Date format` and `Display format` similar values as seen in the video attached

### Steps To Reproduce

1. Set table column type as date and set values as seen in the video attached. Observe the value displayed on the table widget

### Environment

Production

### Issue video log
https://www.loom.com/share/cda8e1a2b0a24af3b20aab5cda268d56

### Version

Cloud

**Comment by somangshu** [comment]
@ramsaptami the video throws a 404! Please check. 

cc @keyurparalkar

**Comment by ramsaptami** [comment]
Discussed this on a Slack [thread](https://theappsmith.slack.com/archives/C025SE88KNE/p1679989339727849) which provides more context around what was being done.
Basically, when moment library/incoming date format does not match selected `date format` field then we see an evaluation error `Invalid value/invalid date`. The evaluation error is correct given the logic explained by Dilip on the thread but this interaction isn't explained very well on our documentation.

**Comment by somangshu** [comment]
cc @danciaclara @jnikhila then we need to do a better job with documentation maybe!

**Comment by jnikhila** [comment]
@harshilp24 - Could you please triage this?
