### ISSUE TITLE
[Bug]: On-boarding flow's marker overlaps with text

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On-boarding flow's the circle on step 8/9 is being overlayed by the Deploy container

### Steps To Reproduce

<img width="2559" alt="Screenshot 2023-07-21 at 08 44 42" src="https://github.com/appsmithorg/appsmith/assets/121891/452b4380-1333-4d5c-92a6-02277c718a5a">

### Public Sample App

Just start a "Welcome Tour" and go into step 8/9

### Environment

Production

### Version

Cloud

**Comment by kavitasmoolya** [comment]
The fix is working fine on release Appsmith v1.9.32-SNAPSHOT
![image](https://github.com/appsmithorg/appsmith/assets/134914630/fff058dd-7644-43e9-8914-aca6563ecb5a)
