### ISSUE TITLE
[Bug]:  503 Server error when refresh token expires before the access token.

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#21794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a situation where the refresh token expires before the access token (when using OIDC authentication), Appsmith starts returning a 503 Server Error. We'll have to manually clear the cookies for this to work again. 

### Steps To Reproduce

1. Setup OIDC Authentication
2. Wait for the access token to expire (About 24 hours after login)

### Environment

Production

### Version

 Self - Hosted 1.9.12

**Comment by abhvsn** [comment]
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1679291499997049

**Comment by trishaanand** [comment]
This is completed.
