### ISSUE TITLE
[Bug]-[50]:Checkbox type column on a table widget does not center icon even when alignment is centered

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We see the checkbox icon right aligned when column type is a checkbox and alignment is centered. Applicable for other columns types like icon, image etc...

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/227925372-ee0d308b-3c7d-4b08-948a-03d80cf0166c.png)
![image](https://user-images.githubusercontent.com/79509062/227925627-7eee8338-1cad-4c22-abff-efed8c59bcf1.png)

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.5 |

**Comment by somangshu** [comment]
I am seeing something very weird, the option is actually applying on the column header! @ramsaptami were you reporting this? cc @dilippitchika is this expected?

https://user-images.githubusercontent.com/11089579/230597692-2b548c8c-512b-4ba1-9a5f-b4adc4848269.mov

**Comment by somangshu** [comment]
Also, basis above, the feature does not work, should this issue be high priority?

**Comment by rhlc** [comment]
I would like to work on this issue, can someone please assign

**Comment by ramsaptami** [comment]
@somangshu that's correct. only the header aligns itself

**Comment by rohan-choudharyy** [comment]
I would like to work on this issue

**Comment by rohan-choudharyy** [comment]
Sure!

**Comment by priyanka-mahour** [comment]
can I work on this?
Is the design decision finalized?

**Comment by somangshu** [comment]
@priyanka-mahour suggest you to maybe take a look at #13882

**Comment by priyanka-mahour** [comment]
> @priyanka-mahour suggest you to maybe take a look at #13882

sure, thank you for assigning me this feature

**Comment by iSatVeerSingh** [comment]
is this issue still unresolved?

**Comment by somangshu** [comment]
@iSatVeerSingh this is still open for development, LMK if you wish to pick this up

**Comment by iSatVeerSingh** [comment]
@somangshu Not interested now.

**Comment by Ashmash100** [comment]
I would like to to work on this issue, can someone please assign it to me?

**Comment by ramsaptami** [comment]
Please go for it @Ashmash100 , do let us know if you need any help

**Comment by Ashmash100** [comment]
Hi @ramsaptami 
In local, I'm trying to connect the table to a database but it shows I don't have access

<img width="1062" alt="Screenshot 2023-08-17 at 10 19 09 PM" src="https://github.com/appsmithorg/appsmith/assets/70318049/06b1adaa-2714-4e8b-a0d9-131c006c2faa">

**Comment by ramsaptami** [comment]
@Ashmash100 You may be pointing to a CE client and building to an EE server. That could be the reason for this error. Retry and let us know?

**Comment by Ashmash100** [comment]
I have done the above step. but now `https://dev.appsmith.com/` is not opening even after spinning up the dev server locally
<img width="1440" alt="Screenshot 2023-08-18 at 7 16 09 PM" src="https://github.com/appsmithorg/appsmith/assets/70318049/5ed2ca41-a60c-4d7a-bdb9-0cd8d6644ade">

**Comment by hetunandu** [comment]
@Ashmash100 can you run the this in the `app/client` directory
```
$ ./start-https.sh http://localhost:8080
```

**Comment by stgeer** [comment]
I would like to work on this issue. Can it be assigned to me please?

**Comment by ramsaptami** [comment]
@stgeer please take it up

**Comment by Thackermahima** [comment]
Hey, Is anyone working on this issue? @ramsaptami @stgeer ?

**Comment by dilippitchika** [comment]
@Thackermahima i don't think so, please take it up if you want to.

**Comment by somangshu** [comment]
@Thackermahima I have assigned the issue to you, please raise a PR in the next 2 days and let us know here.

**Comment by joekman990** [comment]
@Thackermahima @somangshu any updates on this? i am experiencing the same issue thanks!

**Comment by somangshu** [comment]
@joekman990 we do have this issue prioritised internally as of now.

**Comment by Mace111** [comment]
@Thackermahima  @somangshu any updates on this? i am experiencing the same issue thanks!
Use Case: Looks bad if everything else is nicely aligned but this checkbox is hart on the right side of the column in a table.

**Comment by Thackermahima** [comment]
Hey @Mace111  I want to tell you that I am not working on this issue as I got some other work. Thank you!

**Comment by akshat8605** [comment]
Hi Can this issue be assigned to me?

**Comment by ramsaptami** [comment]
please go ahead @akshat8605

**Comment by prajyot004** [comment]
Can I work on this issue ?

**Comment by ramsaptami** [comment]
please go for it @prajyot004

**Comment by moradebianchetti81** [comment]
hi, if this problem is not assigned I would like to take it

**Comment by SaiCharanChetpelly31** [comment]
Hi @ramsaptami @Nikhil-Nandagopal I have fixed the issue and working on cypress tests. I will raise PR with cypress tests.

**Comment by SaiCharanChetpelly31** [comment]
@ramsaptami @Nikhil-Nandagopal I raised pr for this issue. can you please assign a reviewer ?

**Comment by SaiCharanChetpelly31** [comment]
@ramsaptami I raised new PR, can you please assign @riodeuno to this PR. The previous PR which is closed is reviewed and approved by him. 
https://github.com/appsmithorg/appsmith/pull/34222

Thanks in advance
