### ISSUE TITLE
[Bug]: commit count does not get displayed until user refreshes the page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#21801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user gets the git connection for an application and user tries to make changes it is observed that the commit count does not get updated 

### Steps To Reproduce

1) Connect application to GIT
2) Add widget ,DS on the page 
Observe that the commit count does not get updated 
3) Refresh the page it is observed that the count  get updated 

### Environment

Release

### Version

release

**Comment by AnaghHegde** [comment]
@prapullac Can you please share if you notice any error in the browser console? Do you see any API failures?

**Comment by hetunandu** [comment]
While investigating I found that the api is not called to fetch the status on every change on the editor. This is the reason the count is not accurate. The client cannot calculate this and needs the server to get the accurate number at all times. Calling that api by: 
- Clicking on the plus icon
- Refreshing the page
Will reveal the real number of changes

**Comment by infinitetrooper** [comment]
Not an issue. Status only updates on intent (or) on page refresh.
