### ISSUE TITLE
[Bug]: Page generated with data should be deleted when the datasource is deleted.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If there is a page generated wit data for a particular datasource, the page should be deleted if all its queries are deleted and the user deletes the datasource itself.

### Steps To Reproduce

1. Create a datasource, Say Postgres
2. Use Generate page with data to auto-generate a page
3. Delete the queries related to the Auto-generated page
4. Now, Delete the datasource
Observe - The datasource get deleted, but the Auto-generated page still exists

### Environment

Production

### Version

1.9.12

**Comment by Nikhil-Nandagopal** [comment]
No it should not. The page is independent of the datasource and queries and deleting one should not delete the other
