### ISSUE TITLE
[Bug]-[3000]:On enabling a column to be editable, the focus isn’t seen on the Save/Discard column on the property pane.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#21811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On enabling a column to be editable, the focus isn’t seen on the Save/Discard column on the property pane.

https://theappsmith.slack.com/archives/C02JV8G1MP0/p1679918691965989

https://www.loom.com/share/906213a61447448a82041a1cdb654f6f

### Steps To Reproduce

1. D&D a table column
2. Ensure that the number of columns are large in number so that it introduces a scroll on the property pane
3. Enable any column to be editable
4. Notice that the scroll stops midway and the Save/Discard column isn’t in focus

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3000 |
| Effort (months)  | 0.5 |
