### ISSUE TITLE
[Bug]: Text widget's bounding box is not properly set when we add a widget next to it

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#21812]
Text widget's bounding box is not properly set in certain cases.

This happens since we are not processing the dimension updates when the layout is updating.

https://user-images.githubusercontent.com/10436935/228137988-cee083bc-5d7f-4041-85e3-9ff0f8c43edf.mov

**Comment by Sripriya93** [comment]
Working fine. Moving to done.
