### ISSUE TITLE
[Bug]: Border width mismatch

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#21829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Border bottom width mismatch above the right pane

### Steps To Reproduce

![border-mismatch](https://user-images.githubusercontent.com/8299030/228224811-3c53408b-2a54-4ebf-8d50-5a34afa14470.jpg)

![image](https://user-images.githubusercontent.com/8299030/229017711-dfb72904-687c-4c6f-8b64-285a08628aba.png)

### Environment

Production

### Version

cloud

**Comment by Richarex** [comment]
This issue is fixed verified it on the DP url.
