### ISSUE TITLE
[Feature]:  "Import in progress" indication on close of import modal

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#21826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While we are importing a JSON, clicking outside or on the close button closes the import modal. This time, there is no UI indication that import is happening  in the background. The popup should ideally be minimised, and there should be another indicator showing that importing is in progress.  

https://www.loom.com/share/8f3270722ba141ceb8e2cfeb88b2d6b1

### Steps To Reproduce

1) Go application homepage and click on import 
2) Upload the json file
3) While import is in progress, click outside of the modal
4) Modal closed and import has been cancelled

https://www.loom.com/share/8f3270722ba141ceb8e2cfeb88b2d6b1

### Environment

Production

### Issue video log

https://www.loom.com/share/8f3270722ba141ceb8e2cfeb88b2d6b1

### Version

Cloud

**Comment by riteshkew** [comment]
Will handle with the new IA. Closing for cleaning of backlog.
