### ISSUE TITLE
[Bug]: Home page element placement gets messed up occasionally

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observed this a few times in the past week, on page refresh or when navigated to the home page, elements seen in the screenshot move to the left of the screen

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/228220796-7eeef549-c5df-48fc-b328-b8f6d163561a.png)

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing unless we can reproduce
