### ISSUE TITLE
[Bug]: [Conversion Algorithm] List widget when placed side by side and convert from fixed to Auto layout Text widget is moving out of the container in the List widget

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#21839]
![Image](https://user-images.githubusercontent.com/104895602/228316661-344a2fc7-986a-43af-a1ca-0839c898d395.png)

**Comment by aswathkk** [comment]
@rahulramesha is right.
For the viewport shown in the screenshot, image widget has reached its min width. That's why the text got pushed to right side
