### ISSUE TITLE
[Bug] the placment indicators starts disfunctioning in auto layout mode when you place a modal on to canvas

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21835]
https://www.loom.com/share/1731596a11394392b8dd1591b01a1f47

**Comment by kamakshibhat-appsmith** [comment]
This is not fixed , [LOOM](https://www.loom.com/share/96dd23d46f31464b988a736929d89f84)

**Comment by andreevanatasha** [comment]
Check if it's still reproducible

**Comment by kamakshibhat-appsmith** [comment]
This can still be reproduced 
@prsidhu Pls check loom in the first comment for the detailed steps
