### ISSUE TITLE
[Bug]: DynamoDB: DescribeTable query not working.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Describe table query is not working.

### Steps To Reproduce

1. Use the list tables query to get the list of the table
2. Copy the table name and use this query for DescribeTable
{
    "TableName" : "four"
}

Observe - The error message is - 
User: arn:aws:iam::391311798816:user/dynamodb-tester is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:ap-south-1:391311798816:table/four because no identity-based policy allows the dynamodb:DescribeTable action (Service: DynamoDb, Status Code: 400, Request ID: GJCURRF059QGV02I86H7D83613VV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/Mgh64pqgcEZVtRZy

### Version

1.9.12

**Comment by sumitsum** [comment]
Hi based on the error msg it seems the issue is regarding user permission, and not related to the plugin.
