### ISSUE TITLE
[Task] Visual updates to code in Appsmith

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#21844]
- Update font-family of text in code editors.
- Apply new colors, spacing and size changes to the text in code editors.
- Add line highlight to indicate the current selected line.
- Remove the on focus border on JS Editor.

All the new changes are documented [here](https://www.notion.so/appsmith/Visual-changes-to-code-in-Appsmith-8bb530c60ee844e5b44adec039bf9280).

**Comment by siddheshJungade** [comment]
Hi @arunvjn I would like to work on this

**Comment by arunvjn** [comment]
Task completed in https://github.com/appsmithorg/appsmith/pull/22652
