### ISSUE TITLE
[Bug]: GoogleSpreadsheet Oauth2: Getting authorization successful message before actually getting authorized.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user gets "Authorization sucessful" toast message on cliking "Save and authorize" or "Save and re-authorize".

Expected. behaviour - The success message should come when the user select the email account.

### Steps To Reproduce

1. Configure a valid OAuth datasource by using google spreadsheet API
2. Click on ave and authorise
Observe - The user gets a message here itself "Authorization was successful". The message should come in the next step after selecting the email account.

### Environment

Production

### Issue video log

https://knynrq7fk9.vmaker.com/record/zmvOAOb5agIvd4zr

### Version

1.9.12

**Comment by rohan-arthur** [comment]
this is not happening anymore, guess it got fixed with some other PR
