### ISSUE TITLE
Enhancement : Adding the file size message to Filepicker in the Property pane  

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2187]
Steps to reproduce:
1) Add a file widget
2) Click on the property pane 
3) Navigate to "Max File Size"

Observation:
User is asked to add the "Max File Size" and it is observed that the user is not displayed with File size being specified (KB,GB,TB)

Expectation :
It is expected to mention the file size it would help user to understand the file size that needs to be uploaded or they are allowing the user to upload.

![Screenshot 2020-12-14 at 11 52 11 AM](https://user-images.githubusercontent.com/71753653/102053160-48189680-3e0d-11eb-9126-19d47e0507a5.png)

**Comment by marks0351** [comment]
![Screenshot 2021-03-18 at 4.54.44 PM.png](https://images.zenhubusercontent.com/6041f3b8ac4b18f94944edfc/552b42ca-49a4-4fcc-80eb-bccbaf3c0a3d)
Will this indication be enough?
@prapullac @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 maybe just (Mb) ?

**Comment by marks0351** [comment]
I was trying to match the placeholder which already had the text. ok il just have it as (Mb) on the Input label.
