### ISSUE TITLE
[task][Widget] Set the bg color of text widget properly in auto layout mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21896]
This was a limitation during Auto height implementation where the bg color only applues to the text size and not thru the entire boundary boxes of the widget

this can be replicated in production as well.

Creating this task to discuss if we should fix this or not

![Image](https://user-images.githubusercontent.com/113327629/228762888-86498e1b-eb92-4477-bf50-b6b697f56ab3.png)

**Comment by aswathkk** [comment]
![Image](https://user-images.githubusercontent.com/10436935/232386316-fa259b12-fece-4b64-9871-077f185cdf47.png)

@kamakshibhat-appsmith This is what I see now. It doesn't feel like an issue to me right now.

**Comment by kamakshibhat-appsmith** [comment]
the problem looks prominent with single line text only. do you think we should proceed with this ? @aswathkk

**Comment by aswathkk** [comment]
This is due to the minHeight defined for text widget is being 40px where as the line height of the text is being 20px.

@shastry-gg What should we do here?

**Comment by aswathkk** [comment]
@kamakshibhat-appsmith This got fixed in the linked PR.
