### ISSUE TITLE
[Bug] Dropdown icon must be displayed to user on "Type of file"

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2189]
Steps to reproduce:
1) Navigate to File picker
2) Click on the Property pane
3) Navigate to "Type of file" field
4) Click on the field and a dropdown 

Observation:
It is observed that the user understand the field to be text field and not a dropdown as he icon is not displayed to the user

Expectation:
Displaying a dropdown to the field make user feel that the field is dropdown and not a text field 
![Screenshot 2020-12-14 at 1 08 30 PM](https://user-images.githubusercontent.com/71753653/102054728-d0983680-3e0f-11eb-816c-ce61485f84d0.png)

**Comment by riodeuno** [comment]
@prapullac  This is fixed in `release.`
