### ISSUE TITLE
[Task]: Performance infra - stability

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#21892]
It was noted that perf infra has been failing on the CI workflow which in turn add up on `time to deploy`. Here are the following actionable to get better here
- [ ] Avoiding regression to go to prod is paramount for continued stability of the perf infra
- [ ] Auto re-running to get test passing is a strategy which will help us in this case
    - [ ] We will target to close that by mid of April (considering this will solve atleast 90% of the problem) -  there may be a delay here because of the ongoing task re-prioritizations

**Comment by somangshu** [comment]
@SatishGandham should this be closed in favour of #23787

**Comment by SatishGandham** [comment]
@somangshu , yes.
