### ISSUE TITLE
[Feature]: entity explorer sections should be unfurled on a new app

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#21893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a user creates a new app, the entity explorer sections should be unfurled

### Why should this be worked on?

We have noticed in user interviews that New users are unable to find queries, datasources and widgets that they create on the entity explorer that they have created. Users don't notice the entity explorer sections.

If we leave each section open by default, users are more likely to be able to successfully navigate

**Comment by Richarex** [comment]
This is fixed, verified it on release.
