### ISSUE TITLE
[Bug]: The redirect fails when user login with SAML sso

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#21905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is redirected to https://user/login?error=true when they try to login with saml SSO
```
com.appsmith.server.exceptions.AppsmithException: Unable to find action 641ddae87f3afb0cf19c04f0
at com.appsmith.server.services.ce.NewActionServiceCEImpl.findByBranchNameAndDefaultActionId(NewActionServiceCEImpl.java:2276)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
*__checkpoint ⇢ Handler com.appsmith.server.controllers.ActionController#executeAction(Flux, String, String) [DispatcherHandler]
```
![image](https://user-images.githubusercontent.com/45958978/228786618-13d14fd4-d728-49d8-b249-8b95960a5a51.png)

### Steps To Reproduce

1.Set up a local instance
2. Pick any one IDP do all the necessary set up
3. Add the Metadata URL and set up the SAML instance
4. Now logout and try to sign in with SAMl
5. the user is redirected to https://user/login?error=true

### Environment

Production

### Version

v1.9.9

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_8q6h8)

**Comment by RakshaKShetty** [comment]
@sharat87  @pranavkanade  @YatinChaubal I have a repro step for this issue I could repro this with OIDC and i have used Active directory as a IDP
1.Set up the local instance 
2.Now start adding the all the required data 
3. Now just add wrong data eg : we can add username attribute as email instead of sub 
4. now save and restart 
5. Now login out and try to signin with the OIDC
6. Now the user will end up in the above state with these steps i could repro it consistently

**Comment by trishaanand** [comment]
@RakshaKShetty : What is the bug here? You misconfigured SSO and hence you weren't able to log in.

Is the issue about better error handling here? If yes, I would recommend changing the label to better reflect the same.

**Comment by RakshaKShetty** [comment]
yes @trishaanand when we misconfigure the SSO. and try to login the user is  redirected to this url https://user/login?error=true

**Comment by Nikhil-Nandagopal** [comment]
In that case this isn't a bug and should be an enhancement
