### ISSUE TITLE
[Bug]: When the license key is very long, the license key in the license & billing page looks a little off on the UI.

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#21903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the license key is very long, the license key in the license & billing page looks a little off on the UI.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/228778758-bf40e8dc-76f8-4bcb-87b9-d8e9f1814bd4.png">

### Steps To Reproduce

1. Go to https://ee-1199.dp.appsmith.com/settings/billing
2. click on admin setting
3. click on license and billing tab
4. now in the license key section the ui looks off when key is very long

### Environment

Deploy Preview

### Version

https://ee-1199.dp.appsmith.com/settings/billing

**Comment by trishaanand** [comment]
This has been tackled and issue has been fixed.
