### ISSUE TITLE
[Bug]: Incorrect autocomplete suggestion shows up for object path reference

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#21904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Incorrect autocomplete suggestion shows up for object path reference and selecting this suggestion leads to a lint error

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/228772998-465f26a6-f6bf-4475-a2ff-a25badcb6a05.png)

### Environment

Production

### Issue video log
https://www.loom.com/share/9d69977b447140d8ad88ccad13ff44b4

### Version

Cloud

**Comment by bharath31** [comment]
@arunvjn is this related to #11912?

**Comment by bharath31** [comment]
closing this in favor of #11912
