### ISSUE TITLE
[Bug]: 503 when navigating to homepage

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#21915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In edit mode, navigating to homepage while the app is loading throws a 503.

- [ ] #21972

### Steps To Reproduce

https://www.loom.com/share/fc7a50f97a724227bdbccc63cf125da0

### Environment

Production

### Version

Appsmith v1.9.13-SNAPSHOT

**Comment by Richarex** [comment]
This issue is fixed, verified it on DP url.

**Comment by Richarex** [comment]
This is fixed, closing it.
