### ISSUE TITLE
[Task]: Feedback on App Navigation - Part 2

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#21946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We should think and work on the feedback mentioned by fellow teammates here - 
1. Make the application title more prominent.
2. Differentiate between Appsmith UI and the app's UI when previewing navigation.
3. Don't show the Appsmith logo inside the navigation in Appsmith cloud.
4. Disable interactions when previewing navigation.
5. Fork button text color - https://release.app.appsmith.com/app/test/page1-64245927069b3f723d1ae9e5

**Comment by chandannkumar** [comment]
Tested and verified all the above mentioned feedbacks
