### ISSUE TITLE
[Bug]: [Fixed Layout] Text widget in Auto height doesn't hug contents until its prompted

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#21960]
https://user-images.githubusercontent.com/104895602/229086967-c1491717-36e7-497a-ad98-4889f55809f1.mp4

**Comment by Sripriya93** [comment]
Happens with all text boxes, PFB for stat box


![Image](https://user-images.githubusercontent.com/104895602/229091009-e7caa25c-62d8-4691-bcba-8126c74d0499.png)

**Comment by kamakshibhat-appsmith** [comment]
FYI: this is happening with all widgets that has auto height property
