### ISSUE TITLE
[bug][fixed layout] Auto save keeps on failing when we have multiple simultanoeus layout changes going on

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21970]
https://www.loom.com/share/d83cf08a1db94cebb7bab1e9c7540cc5

**Comment by aswathkk** [comment]
I tried to replicate this issue on local and on DP as well. I was unable to replicate this.

**Comment by Sripriya93** [comment]
I have checked few Needs QA in same DP, before taking up this issue, im still able to see Save failed



![Image](https://user-images.githubusercontent.com/104895602/229474712-41f7b3f5-d834-4cd2-b27d-06dccafb5981.png)

**Comment by marks0351** [comment]
@kamakshibhat-appsmith @Sripriya93 Can you check any ce dp's for example https://ce-21582.dp.appsmith.com/
they all fails in these dps. pls try in this vercel dp https://appsmith-8c7g5o7v4-get-appsmith.vercel.app/ you would not see any saves failed coz the server is release env.

**Comment by Sripriya93** [comment]
@marks0351 yes the above mentioned works fine. Vercel DPs auto save function works. In ce DPs we are seeing the Auto save failure. Can we move this to done then? CC @kamakshibhat-appsmith
