### ISSUE TITLE
[Task]: Do not include deleted pages from edit mode in app export

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#21997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you delete some pages and export an app, deleted pages are still found in the exported file. They are not visible in the UI though.

### Steps To Reproduce

- Create an app with two pages.
- Delete one page.
- Export the App.

In the export file, search for the deleted page.

### Environment

Release

### Version

Both

**Comment by AnaghHegde** [comment]
This is not a bug. This is an expected behaviour.
