### ISSUE TITLE
[Bug] Table's DateTime data type does not work

### ISSUE THREAD

**Issue by alex-jitbit** [appsmithorg/appsmith#2199]
## Description

Appsmith sees DateTIme columns in MSFT SQL Server as int numbers. Even if I try to change the column's datatype in the table widget - it shows weird things (like "year 521234") or complains about invalid date

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add any `SELECT` data query that has a DateTime column in SQL Server
2. Run the query

### Important Details
 - Version: [Cloud]
 - Browser [chrome]

![image](https://user-images.githubusercontent.com/33555768/102132692-9d2fc900-3e5c-11eb-81d4-58ee9d4c0f4e.png)

**Comment by Nikhil-Nandagopal** [comment]
@alex-jitbit thank you for reporting this! Looks like an issue in our epoch date converter where we're using moment.unix for milliseconds. 

To get around this today, you can format the data in the table by mapping over it
{{ Query1.data.map((row) => { return  { ...row, id: moment(row.id).format("DD-MM-YYYY") } })}}

**Comment by alex-jitbit** [comment]
Thanks for fixing this so quickly. Any news when this will be deployed?

**Comment by mohanarpit** [comment]
@alex-jitbit This fix is already deployed on Appsmith Cloud ( https://app.appsmith.com ). For self-hosted instances, this will be available early next week.

**Comment by tlawrence-TAG** [comment]
I still see this issue on the latest version of the self-hosted app. When is getting fixed?

**Comment by Nikhil-Nandagopal** [comment]
@tlawrence-TAG this was fixed awhile back. Where are you seeing this issue? Can you share step to reproduce it?

**Comment by tlawrence-TAG** [comment]
You're right... it does look to be working. What I'm seeing is that if you have more results that don't fit into the page size that's displayed, it doesn't sort the entire set of data even though it knows the total amount of records and is holding the entire dataset in memory!

**Comment by jbaker43** [comment]
Still seeing this issue. Any update on this bug?

**Comment by Nikhil-Nandagopal** [comment]
@jbaker43 please file a new issue with a video describing the problem and some sample data of the table. It could simply be that the date format you selected is is epoc seconds and your data is in milliseconds but we'll need to investigate it
