### ISSUE TITLE
[Feature]: Prettify and save on Ctrl/Cmd + S 

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#22000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The JS object pane should support basic keyboard shortcuts that help developers write code faster and more effectively

Ctrl/Cmd + S initiates the browser's save page action. We should override it and display the same message as on the canvas.

### Steps To Reproduce

Open the JS editor and perform any/all of the actions defined above to see behaviour.

### Environment

Production

### Version

1.6.6

**Comment by bharath31** [comment]
@rimildeyjsr Cmd + S should perform the following: 
1. Prettify code 
2. Save code 

The current saving indicator should be shown while performing the above operations: 
![saving indicator](https://user-images.githubusercontent.com/17562726/229484114-5a2c93be-17b1-494d-856e-c597622a5efc.png)

**Comment by rimildeyjsr** [comment]
Note for QA - test in different browsers/platforms/incognito

**Comment by rimildeyjsr** [comment]
@bharath31 - one more question, do we need any analytics event to be added here?

**Comment by bharath31** [comment]
@rimildeyjsr Please track this event on Mixpanel.  

Event name: `PRETTIFY_AND_SAVE_KEYBOARD_SHORTCUT`

**Comment by ramsaptami** [comment]
The PR makes changes as mentioned in the comments above and is not meant to cover the toast msg seen when using `Ctrl+S` on canvas.
![image](https://user-images.githubusercontent.com/79509062/231747530-8c4047f7-f8a5-49f1-8783-ba6a4dfb0ba0.png)

Verified changes on DP
