### ISSUE TITLE
[Feature]: auto format code in JS editor

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#22002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The JS object pane should support basic keyboard shortcuts that help developers write code faster and more effectively.

Auto-format the code in the JS editor. The keyboard shortcut to prettify the code opens an incognito window in Firefox. This causes frustration

### Why should this be worked on?

- The keyboard shortcut to prettify the code opens an incognito window in Firefox. This causes frustration

**Comment by rimildeyjsr** [comment]
@bharath31 - will the prettify option remain in the menu(and as a shortcut) if we have auto indent? The behaviour will become redundant

**Comment by bharath31** [comment]
@rimildeyjsr let's continue supporting the existing shortcut for users who are already accustomed to this.

**Comment by bharath31** [comment]
closing this in favor of #22000
