### ISSUE TITLE
[Bug]: Hint text in create query shows nameInput.text 2 times. 

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#22011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For snowflake, create query, its should be something like emailInput.text which represents email filed  instead of nameInput.

<img width="1361" alt="snow" src="https://user-images.githubusercontent.com/119847783/229432687-0c5fdae6-d94b-412a-bcc0-6aa145c8fcfa.png">

### Steps To Reproduce

1. Create a valid Snowflake datasource
2. Click to add a new query for create query.
Observe - it shows nameInput.text for email email input in hint text

### Environment

Production

### Version

1.9.12

**Comment by sumitsum** [comment]
Related: https://github.com/appsmithorg/appsmith/issues/22117
