### ISSUE TITLE
[Bug][fixed Layout] There is a weird space seen at the bottom of side nav bar in Preview mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22013]
Preview Mode

![Image](https://user-images.githubusercontent.com/113327629/229434765-036d625d-6ded-4071-b26a-a017ef901990.png)

Live preview mode(this is a very minute difference so, please compare it with existing release instance)

![Image](https://user-images.githubusercontent.com/113327629/229435465-5dfd9027-08e4-4e0f-b4b1-4dc54499c105.png)

**Comment by kamakshibhat-appsmith** [comment]
@yaldram the Live-preview part is still not fixed. Moving this to Reopened

**Comment by yaldram** [comment]
I am on the latest `mobile/v1/qa` - 
<img width="317" alt="image" src="https://user-images.githubusercontent.com/13429535/230088452-92cf945c-2dab-4eef-8cd6-e819b2312b43.png">
