### ISSUE TITLE
Update the messages for default roles

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#22018]
Developer - Can edit and view this application along with inviting other users to this application.
App Viewer - Can view this application and invite other users to view this application.

![Untitled (2).png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/47f66450-37b4-4b7b-9cd4-6b49991b8e7b)

**Comment by vj-codes** [comment]
@trishaanand hey can I work on this please?

**Comment by builde7b0b** [comment]
![Untitled](https://user-images.githubusercontent.com/10110062/236595846-58f1e570-661f-4a26-852a-418eb209e1d9.png)

Is this issue Complete? I see an updated message now.

**Comment by utkarsh-shrivastav77** [comment]
Hi is this issue still open
