### ISSUE TITLE
[Bug]: Input widget always register inputs as strings regardless of the set data type

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#22010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the input widget data type is set to a number, it still reports as a string when using it within JsObjects. For places where a number is actually needed, we have to wrap the out of the Input widget with  `parseInt(<STRING_VALUE>)` before it works. 

### Steps To Reproduce

1. Drag an input widget to the canvas and set the Data type to Number
2. Probably within a JsObject,` console.log(typeof InputWidget.inputText)`, it will output "string"

I expect it to be a number. This is making some of our API queries fail and we have to wrap it with `parseInt` before it works. 

### Environment

Production

### Version

Cloud & Self - Hosted 1.9.13

**Comment by dilippitchika** [comment]
@narhzih you have to use inputWidget.text to get the value in number format. .inputText is an internal property, Closing this as it's not an issue.
