### ISSUE TITLE
[Bug]: When user has a developer access and click on share icon in the View mode access the drop downs are not visible

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user has a developer access and click on share icon in the View mode access the drop downs are not visible
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/45958978/229475661-86419810-1e3a-427d-8abc-7b2f1b513b0e.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/229475706-dabd4b48-29ae-4dde-8439-4dc447838172.png">

### Steps To Reproduce

1. Login to https://ee-1242.dp.appsmith.com/
2. create a new workspace/app
3. now deploy the app
4. share the app with developer access/ its app level with user 1
5. login as user 1
6. launch the app click on share icon 
7. The invite dropdown are missing in the share modal

### Environment

Deploy Preview

### Version

deploy preview

**Comment by ankitakinger** [comment]
This is known. will be fixed under https://github.com/appsmithorg/appsmith/issues/21950

**Comment by nsarupr** [comment]
This will be fixed by the PR: https://github.com/appsmithorg/appsmith-ee/pull/1251
Although the changes have been merged in so you can test the changes on DP.

**Comment by RakshaKShetty** [comment]
This issue is fixed in DP
