### ISSUE TITLE
Alignment of resource in members page

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#22020]
@Debsourabh  - What should be the correct design here?

![Untitled (3).png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/2f492c47-2328-4d7c-b169-48c87e5d71df)

**Comment by Debsourabh** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/34486435/229817906-b22a49f8-71bc-47e2-b806-5d59935b845d.png">

I have designed the expand icon for all the workspaces.
Does this now work?

**Comment by infinitetrooper** [comment]
What should we show when there are no apps? Should we have disabled icon (or) do we not show the icon at all?
