### ISSUE TITLE
[Bug]: When user want to  share the app from the deployed mode only app viewer access should be displayed in the share modal

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user want to  share the app from the deployed mode only app viewer access should be displayed in the share modal
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/229492458-70bedc2d-dbd1-4813-b585-6a84118a73a8.png">

### Steps To Reproduce

1. Login to https://ee-1242.dp.appsmith.com/
2. create a new workspace/app
3. now deploy the app
4.click on the share icon
5.click on roles dropdwon
6. both developer and viewer role are displayed instead of just viewer role

### Environment

Deploy Preview

### Version

deploy preview

**Comment by infinitetrooper** [comment]
@RakshaKShetty  - This should not be limited to App Viewer, it should be dependent on the access the invited has. If a developer is inviting then they will see both.

**Comment by RakshaKShetty** [comment]
This is not a issue
