### ISSUE TITLE
[Bug]: If the user changes the app level role from the manage users page, the dropdown menu should remain open and not close automatically

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user changes the app level role from the manage users page, the dropdown menu should remain open and not close automatically
https://www.loom.com/share/ca43864d74404c4c85cfb8f49dfa322d

### Steps To Reproduce

1. Login to https://ee-1242.dp.appsmith.com/
2. create a new workspace/app
3. now deploy the app
4. share the app with app developer access/ its app level with user 1
5. go to manage users page
6. Go to user 1 expand the resource column and change the role for the user 
7. the role gets changed but the dropdown collapse on it own which might confuse the user

### Environment

Deploy Preview

### Version

deploy preview

**Comment by RakshaKShetty** [comment]
This issue is fixed

**Comment by ankitakinger** [comment]
Re-opening as the changes on DS repo are yet to be merged.
