### ISSUE TITLE
[Bug]: The user names are not displayed in alphabetical order in the members page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user names are not displayed in alphabetical order in the members page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/229500479-b6eb0e14-3273-40b5-a397-ef368a68b65e.png">

### Steps To Reproduce

1. Login to https://ee-1242.dp.appsmith.com/
2. create a new workspace/app
3. now share the workspaces with multiple people
4. go to the members page just see everything in alphabetical order 
5. now invite a new user as a app developer access
6. now got to member page and check there is a issue with a aplhabetical order

### Environment

Deploy Preview

### Version

deploy preview

**Comment by ankitakinger** [comment]
@RakshaKShetty the usernames are displayed based on the user role. First, we show Administrators, then the Developers, then the App viewers, and then the No access ones. That is the order received from the backend even before we changed the Members page under app-level invites.

**Comment by infinitetrooper** [comment]
@RakshaKShetty  - Yes. There are two sorting mechanisms here. It's workspace role first (Admin, Developer, App Viewer, No Access).

For apps, they are alphabetical. `App` comes before `Bapp`. If those 2 are followed then we can close this ticket.

**Comment by RakshaKShetty** [comment]
This is not a issue
