### ISSUE TITLE
[Bug] Deploy dropdown always shows 'copy app publish link' tooltip

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2204]
## Description
<img width="447" alt="Screen Shot 2020-12-15 at 11 07 54 AM" src="https://user-images.githubusercontent.com/30255708/102175668-f4b64f00-3ec5-11eb-9d9a-7d55a3cc19b2.png">

Fixes required:
1. The tooltip shouldn't be visible
2. The tooltip message should say: 'Copy link to published app'

**Comment by mohanarpit** [comment]
@areyabhishek Should we just change the text or should the tooltip be removed completely? Is it an either-or situation or an AND situation?

**Comment by areyabhishek** [comment]
I should have given more details. This tooltip appears when I click the drop-down. 

Change required: It should only appear on hover. And update the text's language. Today it's always visible.
