### ISSUE TITLE
[Bug]: if there is only app level access and no workspace level access then the delete icon should not be displayed at the workspace level

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

if there is only app level access and no workspace level access then the delete icon should not be displayed at the workspace level
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/45958978/229507055-737960c2-b66f-4ed4-bf6a-8966b3556a5e.png">

### Steps To Reproduce

1. Login to https://ee-1242.dp.appsmith.com/
2. create a new workspace/app
3. now deploy the app
4. share the app with app viewer access/ its app level with user 1
5. now go to manager user page
6. go to user 1 and expand the resource column
7. The delete icon should not be there at workspace level because the user is having only app level access

### Environment

Deploy Preview

### Version

deploy preview

**Comment by RakshaKShetty** [comment]
This issue is fixed in DP , closing the issue
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/230548763-71041c84-c379-4787-ad83-1cccc9d80281.png">

**Comment by ankitakinger** [comment]
Re-opening as the changes on DS repo are yet to be merged.
