### ISSUE TITLE
[Bug]: App displays a server error when loaded in quick succession

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App returns a 503 when refreshed in quick succession but loads correctly when the page is refreshed again.

### Steps To Reproduce

1. When logging in using a shared app link, the app initially loads with a server error as seen in the video. Refreshing the page loads the app correctly **OR**
2. Refresh any app in quick succession

### Environment

Release

### Issue video log

https://www.loom.com/share/98b239568ea5431e92c0df58a8b3f750

### Version

Cloud

**Comment by NilanshBansal** [comment]
@ramsaptami this is an issue with NGINX 429 error (too many requests), it is not related to login. This happens only on release at any time. 

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/25542733/229696955-ece90dad-f27a-4b3e-ad8b-1b2294cec0de.png">

@ginilpg requesting assistance for devops pod here

**Comment by NilanshBansal** [comment]
@ramsaptami this even occurs if we refresh any page on release multiple times due to too many requests.


https://user-images.githubusercontent.com/25542733/229697949-bfd7d0f7-0e3c-4b32-bb31-507eb8db7d48.mov

**Comment by NilanshBansal** [comment]
@pratapaprasanna @sum35h can you pls check this

**Comment by NilanshBansal** [comment]
@pratapaprasanna disabled the NGINX rate limiting and post that the issue is not reproducible.

https://user-images.githubusercontent.com/25542733/229985407-6777ae6f-72a3-4b6e-b101-00428eed11fb.mov

**Comment by ramsaptami** [comment]
RPS limit has been increased to avoid this scenario hence closing the issue
