### ISSUE TITLE
[Feature]: data connection to Oracle Cloud

### ISSUE THREAD

**Issue by jacobsteffenBYU** [appsmithorg/appsmith#22056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Connection to oracle cloud databases. Separate from other types of oracle connections.

### Why should this be worked on?

Oracle cloud has lots of great features, being able to integrate with it would be great:
https://www.oracle.com/cloud/

**Comment by Nikhil-Nandagopal** [comment]
@jacobsteffenBYU I don't think this should be any different from our #10096 so we'll track it there
