### ISSUE TITLE
[Bug]: Clicking outside on the canvas/ Query pane the bottom panel must close 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#22052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user clicks on the canvas or on the query pane it is observed that panel does not close 

### Steps To Reproduce

1) Navigate to API pane 
2) Add the API with error
3) Run the API
4) Ensure he bottom panel is open 
5) Click outside the panel 

Observe that the panel does not close 

### Environment

Deploy Preview

### Version

DP

**Comment by bharath31** [comment]
@prapullac are you referring to the debugger pane? could you elaborate why the pane should close on canvas clicks? cc: @parth-appsmith
