### ISSUE TITLE
[Bug]: Improve UI for error messages

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The UI looks a bit off as the Error message is too long to fit in the box

### Steps To Reproduce

after reaching homepage, Switch Off network  ; and then try to open any app

<img width="1428" alt="Screenshot 2023-04-03 at 7 52 55 PM" src="https://user-images.githubusercontent.com/113327629/229708511-1a8985bf-f691-4098-9678-0faa6713127a.png">

### Environment

Release

### Version

Cloud/Release

**Comment by Richarex** [comment]
LGTM! verified it on release.
