### ISSUE TITLE
[Task]: Research SSH Tunneling for Databases

### ISSUE THREAD

**Issue by sanveer-osahan** [appsmithorg/appsmith#22064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Research on SSH Tunneling and write a document covering:
- Why SSH Tunneling is used?
- What type of users have it enabled for their databases?
- How many users will be affected? What will be the impact? 
- How to implement?

**Comment by sanveer-osahan** [comment]
@sribalajig Please review https://www.notion.so/appsmith/SSH-Tunneling-2820801d7ac740e8b4a6ae59f31e9d0e?d=fcd4fccd705a49b6b9005f15def346e8#d5b147a40d0749a2a35d48b77556c261

**Comment by rohan-arthur** [comment]
@sanveer-osahan marking this as done

**Comment by gabrielgarza** [comment]
Does this mean the feature is completed?

**Comment by sanveer-osahan** [comment]
Hi @gabrielgarza 
This task was for researching on SSH Tunnel feature.
Closed this as the research is now complete and we have a scope and design ready for having the SSH Tunnel feature

**Comment by prerak-jain** [comment]
Is this feature live? I still can't see SSH configurations while adding a new postgres data source.
