### ISSUE TITLE
[Bug / Feature]: Charset in response headers are not considered while decoding the response text 

### ISSUE THREAD

**Issue by balachandarsv** [appsmithorg/appsmith#22078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The response contents are always read in UTF-8 charset. Sometimes the response might be in some other charsets which are not considered while decoding the response.

### Steps To Reproduce

Try an API which sends the response in UTF-16

### Environment

Production

### Version

1.16

**Comment by balachandarsv** [comment]
Pull request : #20862

**Comment by sumitsum** [comment]
Hi @balachandarsv can you please confirm if you are still working on this problem ?
