### ISSUE TITLE
[Bug]: Switching tabs via buttons inside it does not work

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#22070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you have a button inside a Tabs widget that is used to switch between the tabs, it is not working.

### Steps To Reproduce

1. In a tabs widget add a button in the first tab (Tab 1)
2. The default value of the tab should be 
```{{ appsmith.store.selectedTab }}```
3. The onClick action of the button should be
```{{ storeValue("selectedTab", "Tab 2") }}```
4. Click on the button to switch the tab
5. Notice the tab does not switch

### Environment

Production

### Issue video log

https://user-images.githubusercontent.com/12022471/229713395-ed53e143-56d9-4012-8179-6a3af66429be.mov

### Version

v1.9.14

**Comment by Richarex** [comment]
Switching tabs via inside button is working as expected tested this on the DP url.

**Comment by Richarex** [comment]
This issue is fixed verified it on release.
