### ISSUE TITLE
[Bug][Widget Responsiveness] the space between child widgets are not static in different viewports for List widget _autolayout mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22093]
https://www.loom.com/share/f7448fc9c5fe4162be6d7a11858fc4e0

**Comment by aswathkk** [comment]
This happens since the processAutoLayoutDimensionUpdatesSaga only updates canvasWidget and not metaWidget.
We need to create an action similar to that of `UPDATE_MULTIPLE_WIDGET_PROPERTIES` specifically for metaWidget to make it work
