### ISSUE TITLE
[Bug][Conversion Algorithm] Is there a way to dynamically update the data in the Modal which gives the Latest snapshot timestamp

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22094]
https://www.loom.com/share/13d6c3f77a9644579bed3c67d1e801f1

Not the highest priority, might require product decision

**Comment by momcilo-appsmith** [comment]
@marks0351 We should have the correct time on both, especially since we are refreshing the page after every conversion.
