### ISSUE TITLE
[Bug][Fixed Layout] When widget URL nav kicks in , the app navigation header collapses in Preview mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22095]
https://www.loom.com/share/fe2c1c0fc15748faaf265e04c84353b6

Another way to replicate similar behaviour

https://www.loom.com/share/02309aa88d3f409aae0a4563698268d2

**Comment by kamakshibhat-appsmith** [comment]
@aswathkk did we disable Widget selection in preview mode?

**Comment by marks0351** [comment]
@kamakshibhat-appsmith yes I have disabled it in preview mode.
