### ISSUE TITLE
[Bug]: Widget Navigation doesnt work when you have container type widget in the page

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/8b2e3b3225344331a90340d972f60040

### Steps To Reproduce

1. Take 2 pages
2. In one page , add one container
3. Switch pages and see if you can navigate to the container again

### Environment

Production

### Version

Production

**Comment by Richarex** [comment]
Working fine, verified it on release.
