### ISSUE TITLE
[Bug]: Hint text can be improved in create query in postgres

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#22117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For the email ID, the hint text is being shown as nameInput.text

<img width="1440" alt="postgres" src="https://user-images.githubusercontent.com/119847783/230008229-5126256e-5353-4f32-b4cc-73238ddf4b8e.png">

### Steps To Reproduce

1. Create a postgres datasource
2. Create a create query

### Environment

Production

### Version

1.9.13

**Comment by sumitsum** [comment]
Related: https://github.com/appsmithorg/appsmith/issues/22011

**Comment by iSatVeerSingh** [comment]
@somangshu @sumitsum @AnandShahs123 I have reproduced this issue. I want to work on this. Please assign me.

**Comment by Nikhil-Nandagopal** [comment]
@iSatVeerSingh go for it, the solution should be to simply update the nameInput to emailInput

**Comment by iSatVeerSingh** [comment]
@Nikhil-Nandagopal can you please give a little bit of guidance about where to find this component in codebase.

**Comment by sumitsum** [comment]
@iSatVeerSingh please check out this file : app/server/appsmith-plugins/postgresPlugin/src/main/resources/templates/CREATE.sql

**Comment by iSatVeerSingh** [comment]
@sumitsum @riodeuno Please check this.

**Comment by sumitsum** [comment]
@iSatVeerSingh LGTM. Approved the PR.
