### ISSUE TITLE
[Bug]: Bindings on API and Query panes are not tracked via ENTITY_BINDING_SUCCESS

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#22125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a binding on an API or Query, I don't see it being tracked as a part of the ENTITY_BINDING_SUCCESS event

### Steps To Reproduce

Add any binding using {{ }} on an API or Query. Notice that the action is not being tracked.  

### Environment

Production

### Version

Cloud

**Comment by Druthi** [comment]
Checking
