### ISSUE TITLE
[Bug]: "Failed to fetch" when trying to use the fetch API in JSObject

### ISSUE THREAD

**Issue by nico-kow** [appsmithorg/appsmith#22135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to use the fetch API in JSObjects for cases where the normal APIs dont work. It should not throw error. 

### Steps To Reproduce

1. Create a new JSObject in any App.
2. Paste: 
export default {
	myFun2: async () => {
		const response = await fetch("http://example.com/movies.json");
  const jsonData = await response.json();
  console.log(jsonData);
	}
}
3. Run myFun2

![Bildschirmfoto vom 2023-04-05 17-41-44](https://user-images.githubusercontent.com/116407743/230057948-e55c2f77-f576-489b-b3af-9293bf6dfa48.png)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Hello, this doesn't seem to work on jsconsole.com either so it doesn't seem to be an issue with Appsmith

**Comment by SKarema** [comment]
I have the same issue. It says `TypeError: Failed to fetch at te...`

**Comment by mp-gh** [comment]
I am running into the same problem, "TypeError: Failed to fetch" , with a very simple example.  Is there any working example of being to able to fetch data from an api in javascript in appsmith?  

The code in your youtube video:
https://www.youtube.com/watch?v=sLt5oPJmVTM
looks the same, it would be nice if the youtube videos included links to the example projects, I can't seem to find that specific example project on your site to test it out.

If it "doesn't seem to work on jsconsole.com either so it doesn't seem to be an issue with Appsmith" then appsmith should implement another way to accomplish the functionality that is documented and advertised here:
https://docs.appsmith.com/write-code/reference/Fetch-API

**Comment by Nikhil-Nandagopal** [comment]
@mp-gh have you tried using the REST API?

**Comment by mp-gh** [comment]
@Nikhil-Nandagopal 
by "the REST API" I assume you mean a GET query under the APIs section of Queries/JS.  That works if you don't need to get the data in javascript.

Do you have a link to a working project using fetch() as described in your documentation?

**Comment by Nikhil-Nandagopal** [comment]
@mp-gh once you trigger the GET query, you can access it's data via javascript using {{Query1.data}} or even trigger it as {{Query1.run()}}

I believe the examples in our documentation works.

```
export default {
	myFun2: async () => {
		const questions = await fetch("https://opentdb.com/api.php?amount=10")
		return questions.json()
	}
}
```
Paste this in your JSObject and try it out

**Comment by Novack** [comment]
Also had issues using the fetch api with the same result:
_
> "TypeError: Failed to fetch at https://app.appsmith.com/static/js/evalWorker.ca30a746.chunk.js:1:..."
_

I reimplemented the request from js code into a rest api query and worked perfectly.
