### ISSUE TITLE
[Bug]: Recently edited app has incorrect information

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

User edit log on the homepage is broken.

- [ ] Users not currently editing the app show up as recent editors
- [ ] Latest edited app does not rearrange to the top of the list
- [ ] forked app shows owner's name and not current users name

### Steps To Reproduce

Observe above scenarios while working on apps within a workspace

### Environment

Production

### Version

Cloud

**Comment by deepika-appsmith** [comment]
All the mentioned 3 issues are not reproducible on the latest build. Hence closing the issue.

Uploading Screen Recording 2024-03-15 at 5.21.25 PM.mov…
