### ISSUE TITLE
[Bug] Action does not execute on page load if result is not bound to a widget

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#2217]
### Steps to reproduce the behaviour:
1. Create a [public request bin](https://requestbin.com/r)
2. Add API to a page, enable on page load (do not bind result to any widget)
3. Trigger a page load  by refreshing page OR deploy application.
4. No requests show up on request bin.
5. No calls to `/api/v1/actions/execute` show up on NetworkActivity of chrome DevTools

Once we bind result to any widget, requests start showing up.

### Important Details
 - Version: Cloud + local dev
 - OS: MacOSX (not relevant)
 - Browser: chrome (not relevant)

**Comment by nidhi-nair** [comment]
@ofpiyush I had not included this by design because I couldn't think of a good enough use case to refresh data / make a network request unless the data from the action was actually used on the page, they seemed like redundant calls. 

One use case I had thought of was like a POST request that does not use page data but simply updates their server (a page hit counter of some sort), do you think such requests make sense?

**Comment by ofpiyush** [comment]
> request that does not use page data but simply updates their server

> do you think such requests make sense?

Yes.

More generally, it is about setting simple rules and clear expectations from a system so that a user can reason about what is going on.

## Paths forward

If we want to support `ping` type use cases:
- Always  execute on page load actions.

If we want to keep the optimisation:
- Disable the ability to switch it "on page load" and show a warning till they use the response.
- Show a warning when they remove the last binding from a widget.

@Nikhil-Nandagopal thoughts?

**Comment by mohanarpit** [comment]
@nidhi-nair This is a legitimate bug. If the user is toggling the `Run on page load` for an Action, we should honour that. We do our magic up to the point the user plays with this toggle. As @ofpiyush mentioned, there are quite a few use-cases around pinging, analytics etc where the user simply wants to make an API call without actually caring about the response data.

**Comment by Nikhil-Nandagopal** [comment]
Agreed here, if the user expresses intent, we should honor it

**Comment by nidhi-nair** [comment]
Got it. For anyone taking up this issue, the change needs to be made in the `updateLayout` method of `LayoutActionServiceImpl`. The method currently only reads the dsl to find actions that need to be executed on page load. We will need to add an extra db query that fetches all actions for a particular page which have been set to execute on load by the user.
