### ISSUE TITLE
[Bug]: Resize loop 

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#22183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Resize loop due to autoLayoutDimensionObserver, and bounding box computation

https://user-images.githubusercontent.com/103687/230609541-5f228850-e990-400f-a365-f850a8c20f63.mov

### Steps To Reproduce

1. Add a few widgets include input widgets in desktop viewport
2. Resize quickly to lower than mobile viewport

### Environment

Deploy Preview

### Version

Deploy preview

**Comment by aswathkk** [comment]
Similar issue is observed with a combination of  Tabs & Checkbox Group widgets as well

https://www.loom.com/share/be895e364678422ea60d3761f0fba52c
