### ISSUE TITLE
[Bug]: Users can skip signup form if they hit enter on the keyboard

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#22184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user signs up for a new account, they can bypass the welcome form by selecting other, and hit enter

### Steps To Reproduce

1. Create a new account
2. Select other
3. Hit enter and observe
https://user-images.githubusercontent.com/20532920/230614241-3fb69784-9324-43b8-b76f-84220c1707c9.mov

### Environment

Production

### Version

Cloud v1.9.16

**Comment by Richarex** [comment]
This is fixed, verified it on the DP url. User is not able to skip the signup form when they hit enter from the keyboard.

**Comment by Richarex** [comment]
This is fixed verified it on release.
