### ISSUE TITLE
[Bug]: Code to UI breaking for  Action selector

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#22180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below code snippet is not working while doing toggle JS-NON JS, expected was to disable it when not able to translate 

```
`{{["UI Building", "Actions", "JS", "Autocomplete", "Widgets", "Pages", "Property Pane", "API Pane", "Query Editor", "Datasources", "ACL", "Login / Signup", "Telemetry", "Deployment"].forEach((label, index) => {
  Api1.run((res, param) => {
    let CritLen = 0;
    let HighLen = 0;
    let LowLen = 0;
    let NoPriLen = 0;
    res.map(issue => {
      let noPriVal = 1;
      issue.labels.map(label => {
        if (label.name === "Critical") {
          CritLen++;
          noPriVal = 0;
        } else if (label.name === "High") {
          HighLen++;
          noPriVal = 0;
        } else if (label.name === "Low") {
          LowLen++;
          noPriVal = 0;
        }
      });
      NoPriLen += noPriVal;
    });
    storeValue("Bug-" + param.index + "", {
      x: param.label,
      critY: CritLen,
      highY: HighLen,
      lowY: LowLen,
      noPriY: NoPriLen
    });
  }, undefined, {
    label: label,
    index: index
  });
  Query1.run((res, param) => {
    let CritLen = 0;
    let HighLen = 0;
    let LowLen = 0;
    let NoPriLen = 0;
    res.map(issue => {
      let noPriVal = 1;
      issue.labels.map(label => {
        if (label.name === "Critical") {
          CritLen++;
          noPriVal = 0;
        } else if (label.name === "High") {
          HighLen++;
          noPriVal = 0;
        } else if (label.name === "Low") {
          LowLen++;
          noPriVal = 0;
        }
      });
      NoPriLen += noPriVal;
    });
    storeValue("Feature-" + param.index, {
      x: param.label,
      critY: CritLen,
      highY: HighLen,
      lowY: LowLen,
      noPriY: NoPriLen
    });
  }, undefined, {
    label: label,
    index: index
  });
});}}`
```

code`{{
(function(){
    return  Promise.race([
            Api1.run({ name: 1 }),
            Api1.run({ name: 2 })
    ]).then((res) => {
        showAlert(`Winner: ${res.args.name}`)
    });
})()
}}`

Screenshot - 
<img width="591" alt="Screenshot 2023-04-07 at 4 18 09 PM" src="https://user-images.githubusercontent.com/80756091/230598813-a5f0de11-ed79-4148-8f36-32308d434b6f.png">

Working in DP - https://appsmith-ejs3m15tj-get-appsmith.vercel.app/app/actionrefactor/page1-63a074cf8ee2c20625765e14/edit/widgets/v88nz2t05x

### Steps To Reproduce

1. Add above code snippet and toggle between the Non JS mode and verify the the code in UI

### Environment

Release

### Version

cloud

**Comment by ramsaptami** [comment]
The first issue here is covered in #22505
The second issue mentioned here is around function declaration syntax error

> `code{{ (function(){ return  Promise.race([ Api1.run({ name: 1 }), Api1.run({ name: 2 }) ]).then((res) => { showAlert(Winner: ${res.args.name}) }); })() }}`
