### ISSUE TITLE
[Task]: Use published resources for app ImportExport across all the flows - Git, FileExport, Templates

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#22198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] https://github.com/appsmithorg/appsmith/issues/22434

_No response_

**Comment by nayan-rafiq** [comment]
We're going to implement this https://github.com/appsmithorg/appsmith/issues/24313 
Closing this issue.
