### ISSUE TITLE
Limit export resources to the branch in Git connected apps

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#22199]
When we export a Git-connected app, the export file contains default branch resources irrespective of whether they are present in the current branch. We should limit the export to the current active branch as that would allow users to export a version of app without unnecessary bloating.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_atx1o)

**Comment by brayn003** [comment]
Resolved with PR #26096
