### ISSUE TITLE
Banner component

### ISSUE THREAD

**Issue by vasanthappsmith** [appsmithorg/appsmith#22194]
![Image](https://user-images.githubusercontent.com/92305123/230824631-9f7b2243-7e62-4cce-ba18-b9c985315316.png)

Require a new variant based on the Billing console and debug. 

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/26279
```

**Comment by rohitagarwal88** [comment]
https://github.com/appsmithorg/appsmith/issues/26279

**Comment by vasanthappsmith** [comment]
@rohitagarwal88 Adding 1 more day for this as I will include documentation as part of this scope.

**Comment by vasanthappsmith** [comment]
Design : [Figma](https://www.figma.com/file/sz08OJt2VrEgxQ8eToFIqG/ADS2.0---Components?type=design&node-id=5427-5532&mode=design&t=O4scThOvmlbHNWI9-4) 
Documentation : [Notion](https://www.notion.so/appsmith/Banner-a3825273573d4dd1b2cf6aa805589d13?pvs=4)
