### ISSUE TITLE
[Bug]: The DP Breaks when user clicks on Share Button 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The DP Breaks when user clicks on Share Button in edit mode
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/230839286-0c3f9af4-7257-448f-9743-bc260b091202.png">

### Steps To Reproduce

1. go to https://ee-1242.dp.appsmith.com
2. share a app to user 1 with a app developer access
3. Now login as user 1
4. click on edit button now immediately click on share button
5. The oops something went wrong screen will be displayed

### Environment

Deploy Preview

### Version

deploy preview

**Comment by nsarupr** [comment]
From the testing point of view, it seems that the share button is being clocked before all it's dependencies are already loaded.
@ankitakinger can you once check what all dependencies are required before we can click on the share button?

**Comment by ankitakinger** [comment]
@nsarupr @RakshaKShetty This issue has come up after we introduced clean URLs, it's not related to app-level invites. When we click on the share button before the Application editor is completely loaded, we see the below error in the browser console:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/28362912/231694533-532ed6a2-2ead-445f-b66d-bdc1f0a0d456.png">

**Comment by RakshaKShetty** [comment]
reopening the issue still facing the issue 

1. open dp https://ce-22396.dp.appsmith.com/
2. from home page click on the edit mode of app
3. from the editor 
4. click on the deploy tab
5. as soon as view mode loads please click on share icon
6. the app breaks with "oops something wrong error"
