### ISSUE TITLE
[Bug]: add built on appsmith badge for error pages

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#22212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.figma.com/file/nVvIoLuCmTjvivejSnCML8/5XX-Error-states?node-id=2-179&t=ZNH2RybRhKQmYw3Q-0

https://github.com/appsmithorg/appsmith/pull/21917#issuecomment-1501492395

### Steps To Reproduce

Got to an error page (e.g. turn off network)
Notice built on appsmith badge missing in CE (cloud and self-hosted)
Shouldn't be shown on EE edition.

### Environment

Production

### Version

Appsmith v1.9.15-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
I don't think this makes any sense
