### ISSUE TITLE
[Feature]: Unfurl callback to show success and failure actions with specific count

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a new user/user trying to configure a new action, the UI response in the revamped design is accurate.

But as an advanced user who has already configured actions on the property pane and wants to modify child action instead of parent, seeing only `callbacks` with total action count (again) on the first click of a parent action does not convey enough information. The user needs to click again to see success/failure blocks - which then opens up the entire success & failure blocks instead of incrementally increasing the information provided to the user.

**Current interaction:**
Initial view:
![image](https://user-images.githubusercontent.com/79509062/230887311-e1025474-ed66-4963-b4f2-9fecf82f8580.png)

First click:
![image](https://user-images.githubusercontent.com/79509062/230887349-9cf2e8eb-4d23-40cd-a20f-41e4c76076e0.png)

Second click:
![image](https://user-images.githubusercontent.com/79509062/230886897-893d6172-654f-4b14-ad45-13420159e6c6.png)

### Why should this be worked on?

User flow should instead be augmented to:
1. First click on parent action: unfurl callback showing onSuccess/onFailure titles with total count under each action and make the title elements clickable
2. Second click on either success or failure child action: unfurl only the section selected by the user

**Comment by ramsaptami** [comment]
Issue on the on-boarding journey where text asks the user to click on + icon next to `onSuccess` but it's hidden under a chevron icon.
![image](https://user-images.githubusercontent.com/79509062/230953385-9c48a14a-d5ff-4784-9d6d-23ca3373c419.png)

**Comment by arunvjn** [comment]
Part of this issue (showing callback button by default) is fixed in #24071

**Comment by bharath31** [comment]
creating a new issue to handle the onboarding changes

**Comment by arunvjn** [comment]
@bharath31 Could you please look into the interaction that is mentioned in the description of this issue ?

**Comment by bharath31** [comment]
Let's tackle this as a part of https://github.com/appsmithorg/appsmith/issues/24251
