### ISSUE TITLE
[Bug]: UI changes on the action selector

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sentence case following text in the revamped action selector

- [x] not capital `k`
![image](https://user-images.githubusercontent.com/79509062/230877042-6059f1fd-a563-46af-89bf-94000741d9a3.png)

- [x] lower case `p`
![image](https://user-images.githubusercontent.com/79509062/230889674-c267cdc7-f372-4e84-89f8-27831c4460c1.png)

- [x] lower case `a` on alert
![image](https://user-images.githubusercontent.com/79509062/230889942-301becc0-2ac8-4e23-8c79-7022a6822a87.png)

- [x] lower case `m`
![image](https://user-images.githubusercontent.com/79509062/230890038-e814d5d6-a32d-4ffa-b912-9cf9d232a874.png)
![image](https://user-images.githubusercontent.com/79509062/230890092-0b41a272-4aee-4e09-91d8-a049d029d682.png)

- [x] lower case `w`
![image](https://user-images.githubusercontent.com/79509062/230890207-837cd1f1-b6e1-4553-bcd2-88e625dce544.png)

- [x] Field titles need to follow sentence casing while the others follow first letter capitization
![image](https://user-images.githubusercontent.com/79509062/230890708-a8b1b34d-868e-4c32-80b2-a51c40650fcb.png)
![image](https://user-images.githubusercontent.com/79509062/231066315-ba2e2c42-4467-49dc-ab8c-fdb74dde7c9f.png)
![image](https://user-images.githubusercontent.com/79509062/231066747-022317a3-0e7e-45eb-a1c5-cceac011a33a.png)
![image](https://user-images.githubusercontent.com/79509062/231066787-a16d213d-1304-4a14-8003-3523482f1e1b.png)
![image](https://user-images.githubusercontent.com/79509062/231066893-79b11251-1da8-41ed-98b9-19bef715732f.png)

- [x] Should geolocation be lower cased? If so then the 3 functions and their titles need an update

- [x] Tiny nitpick: On the pop-up its `Id` but on the property pane its `ID`
![image](https://user-images.githubusercontent.com/79509062/231066982-400d136e-aa7e-4190-9c1b-02742fcfe697.png)

### Steps To Reproduce

See above

### Environment

Release

### Version

Cloud

**Comment by mabbas112** [comment]
Hello, can I look into this issue?

**Comment by ravikp7** [comment]
@ramsaptami Since geolocation is not a proper noun. I'm lowering it's case as well

**Comment by shwetha-ramesh** [comment]
@ravikp7 Tested this DP, Show modal and Close modal fields `Modal name` do not follow sentence case. 
![image](https://github.com/appsmithorg/appsmith/assets/92293815/04ba4bf4-7895-4b73-afe4-c9613adfd651)

**Comment by shwetha-ramesh** [comment]
Tested on this DP https://appsmith-a49kxufsi-get-appsmith.vercel.app.
Working as expected. Moving to done.
