### ISSUE TITLE
[Task]: Fix highlights & widget position after introduction of vertical alignment & gaps

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#22228]
After the introduction of fixed amount of gaps between the rows in CSS, the position of highlights & widgets got broken.
We need to account for this gap in the calculation of highlights as well to resolve this issue.

![Image](https://user-images.githubusercontent.com/10436935/230932541-db545393-560d-415a-8f68-898af20938c6.png)
![Image](https://user-images.githubusercontent.com/10436935/230932542-ca8cc894-d712-4d09-9301-31b40f28c4d2.png)

**Comment by rohitagarwal88** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mobile-Pod-63be72dba1b2cf00156925f1/issues/appsmithorg/appsmith/22228?planning-poker) with Zenhub @aswathkk @marks0351 @prsidhu @riodeuno @yaldram
