### ISSUE TITLE
[Bug][Responsive canvas] The placement indicators stops showing up once you drop RATING widget on the canvas

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22237]
https://www.loom.com/share/40f5ddfe32e046ac90e640ebb5a8fc3c

**Comment by kamakshibhat-appsmith** [comment]
@prsidhu STEPS:
1. Drop a rating widget in the centre 
2. try dropping any other widget , notice no indicators are appearing https://www.loom.com/share/cda1d070894c417b99616dfc77f446bc

**Comment by andreevanatasha** [comment]
Need to confirm that it's related to Resize loop issue
