### ISSUE TITLE
[Bug]: DatePicker Default Date is not preserved when backed by a data source

### ISSUE THREAD

**Issue by netdragonx** [appsmithorg/appsmith#22249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a DatePicker element and set the Default Date to a dynamic value such as `{{data_table.selectedRow.start_date}}`, the field is immediately replaced by the value of the current date and time, so I am unable to use it in an update form.

### Steps To Reproduce

1. Add a DatePicker widget
2. Set the Default Date to a datasource field (my field source is PostgreSQL timestamptz)
3. Click out of widget
4. You should see it reset to current date/time

### Environment

Production

### Version

Appsmith Community v1.9.12

**Comment by somangshu** [comment]
this feel like its expected @netdragonx, appsmith follow the WYSIWYG mental model, so if the default data is bound to some value, it will always expected show that as the datepicker selection

**Comment by keyurparalkar** [comment]
@netdragonx are you trying to place this dynamic value in the default date field when the JS is turned off? Like below:
<img width="582" alt="Screenshot 2023-04-11 at 8 28 44 PM" src="https://user-images.githubusercontent.com/14138515/231203856-e56ac6bb-1f21-455d-8c86-8ac493a0e275.png">

Can you place this dynamic value when the JS toggle is turned on like below and try it out:
<img width="582" alt="Screenshot 2023-04-11 at 8 31 01 PM" src="https://user-images.githubusercontent.com/14138515/231204565-8f87d843-9b86-4ceb-8eff-76bbf89299da.png">
