### ISSUE TITLE
[Bug]: Copy icon on evaluated value pop-up spills out of it's display element

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The copy icon on the evaluated pop-up spills out of it's display box. Can be reproduced when there's a data type mismatch on returned data.

### Steps To Reproduce

1. Drop a button widget onto canvas
2. Bind a query data, like query1.data to button label field and observe the copy icon on the pop-up

![image](https://user-images.githubusercontent.com/79509062/230961739-6c4889ed-5a68-4b00-86c2-3a3115061908.png)

### Environment

Production

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
![evaluated-popup.png](https://images.zenhubusercontent.com/60c2f984f9be7454ac4d7382/d500a6d3-66e3-44a6-b3c3-55c405a6ad7a)

Seems like this is already fixed. Closing this for now. @ramsaptami do confirm once if it is otherwise.
