### ISSUE TITLE
[Bug]:[Auto layout] Height of the resize handler is smaller in preview mode

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#22246]
Height of the resize handler in Preview mode is smaller 

https://user-images.githubusercontent.com/104895602/230971127-9318032e-f3f5-461e-adea-26813f4d900a.mp4

**Comment by marks0351** [comment]
This has been fixed as part of https://github.com/appsmithorg/appsmith/issues/22238
