### ISSUE TITLE
[Bug]:[Widget responsiveness][Auto layout] Group widget label goes out of border and to the back of the widget placed beside

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#22245]
Issue - 1
When we have a Group widget and another widget beside it, and when we enter a longer text in Group widget label, we are able to the text goes out of the border of the widget

Issue - 2 
Also we are able to see the Container is not getting resized or collapsed when moving other widgets inside it

https://user-images.githubusercontent.com/104895602/230970349-2cb5da02-d0b7-4f34-b26d-1b3398a9e5ce.mp4

**Comment by KelvinOm** [comment]
Not relevant. Auto layout support will be available in a while.
