### ISSUE TITLE
[Bug]: Datasources are not getting displayed when logged in through Developer user.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we login as Developer user, the datasources are not getting listed and queries are failing

### Steps To Reproduce

1. Login as the instance admin user, and in the application, create a datasource (used Dynamo db), create a query, create a page, and in the page use a widget that gets data from the query.
2. Give a new user Developer access through share modal.
3. Signup with this new user, open the application. 
4. Note that there are error messages that come up as soon as the application is opened.
5. Try to run the query, the query fails. 
6. The datasources created as admin user are not listed in the datasource section. It is empty
<img width="1080" alt="ErrorOnDeveloperuserwithwidgetaccessingquery1" src="https://user-images.githubusercontent.com/101863839/231054238-1ab70c36-9d3a-4e08-a401-4d51084a7017.png">
<img width="927" alt="dsnotseen" src="https://user-images.githubusercontent.com/101863839/231054255-471a20fa-4abc-45fc-984b-79ff5fcbf4ce.png">
<img width="757" alt="developer" src="https://user-images.githubusercontent.com/101863839/231054275-3cf36441-cc78-49ad-8565-3dea21500690.png">

### Environment

Deploy Preview

### Version

Cloud

**Comment by RakshaKShetty** [comment]
This issue is fixed in DP. closing it
