### ISSUE TITLE
[Bug]: App takes long to load

### ISSUE THREAD

**Issue by FirstBloodForJava** [appsmithorg/appsmith#22258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is a lot of JS written on the page. In Edit mode, the page takes a long time to load. In Deploy mode, the page loads quickly.
The exported json file contents take Steps To Reproduce.

### Steps To Reproduce

The file content is too large to upload

### Environment

Production

### Version

newest

**Comment by Nikhil-Nandagopal** [comment]
@FirstBloodForJava is it possible to share a screen recording of the issue and invite support@appsmith.com to your application? We'll be happy to debug why this is occuring

**Comment by FirstBloodForJava** [comment]
In the website https://app.appsmith.com/ login,account: 116486497@qq.ocm,password: 1234qwer
The workspace is tableName.First application,Chinese name:表格首页.
I find that each time I export the application to a json file, the file space gets bigger

**Comment by somangshu** [comment]
Could be a problem related to the JS object Eval in view mode, Have we optimized and shipped it already @ApekshaBhosale / @arunvjn ?

cc @SatishGandham

**Comment by SatishGandham** [comment]
@FirstBloodForJava , can you please share the app with support@appsmith.com.

The app export size grows because, you have the published version and draft version in the export. To reduce the export size, publish the app before exporting.

We are working on reducing the app export size in general.
