### ISSUE TITLE
[Bug]: Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_defaultSelectedItem_spec.js

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#22252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_defaultSelectedItem_spec.js - failing in CI

### Steps To Reproduce

Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_defaultSelectedItem_spec.js
is failing in ci

### Environment

Release

### Version

self hosted

**Comment by somangshu** [comment]
cc @Tooluloope please triage this and understand the effort required!
