### ISSUE TITLE
[Bug]-[1800]:Remove inputText from autocomplete suggestion for input widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Input widgets' autocomplete suggestion shows `Input.inputText` and `Input.text` where `inputText` is an internal property that shouldn't be exposed as a suggestion.

[Slack thread](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1677757204941789)

### Steps To Reproduce

1. Drop an input widget on canvas and try to bind it's properties
![image](https://user-images.githubusercontent.com/79509062/231095994-3638ebfb-a07a-40cd-bbbf-a792cb4bc585.png)

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
@Rishabh-Rathod could you add an estimate here?

**Comment by bharath31** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1800 |
| Effort (months)  | 0.5 |
