### ISSUE TITLE
[Bug]: Edit icon on Preview mode does not redirect to editor

### ISSUE THREAD

**Issue by Vidushi-Gupta** [appsmithorg/appsmith#22260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After hitting the 'Preview' button in the editor to preview an app, when the edit icon is clicked, it does not redirect back into the editor. The only way to come back into the editor is by clicking again on the 'Preview' button. 

https://user-images.githubusercontent.com/55969597/231087194-f434137e-20ce-43f6-aec2-558c45a97d02.mp4

### Steps To Reproduce

1. Open an app
2. Hit the 'Preview' button
3. Hit the edit icon. It does not change back to the editor
4. Hit the 'Preview' button. It does go back to the editor

### Environment

Production

### Version

Cloud - v1.9.15

**Comment by iSatVeerSingh** [comment]
Same here. Edit icon not working.

**Comment by haithamkarim** [comment]
It seems it is not a browser-related issue. Any fix soon?

**Comment by dilippitchika** [comment]
@haithamkarim this is a coming from a  new feature we added to show a preview of our navigation. What is the trouble you are facing because of this? 

@dhruvikn can you ensure the edit button takes you back to edit mode in the preview state?

**Comment by haithamkarim** [comment]
@dilippitchika  the problem is once you open the preview then you cannot go back to the edit window because the edit button is not working. You have to go to the home page and then start editing the application from there

**Comment by dilippitchika** [comment]
@haithamkarim you can click on the preview button again to go back to edit mode

**Comment by haithamkarim** [comment]
@dilippitchika 
OK. That worked, I didn't know that. Thanks

**Comment by chandannkumar** [comment]
Tested this issue on [PR](https://github.com/appsmithorg/appsmith/pull/22297) and LGTM
