### ISSUE TITLE
[Bug] Table selectedRow is not populated when multi select is enabled

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2227]
<p>Steps</p>
<ul>
<li>Drag a table</li>
<li>Enable multi select</li>
<li>Add a row action to showAlert</li>
<li>Bind the value of the selectedRow to the showAlert message</li>
<li>Click the action button</li>
<li>The value of the selectedRow is not shown</li>
</ul>

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal We have another property for multi-select which updates in the case of multi-select tables. It is the `selectedRows` property.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno this goes back to our conversation yesterday about how do I identify the row of which button was clicked. selectedRows does not solve this problem

**Comment by ggs331** [comment]
Same issues when enabled multi select on table, the selectedrow will not populated but only selectedrows instead. But seems no way to identify which row was being selected if click a button column on the table. Is this a bug,or it's supposed to be like this if multi select was enabled? Is there work around to get selectedrow when a button in the table was clicked?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu can we get the identifier for the rowActionTriggered?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal we are talking this up with #2444 as part of the table widget enhancements planned

**Comment by somangshu** [comment]
@ggs331 before a while we had introduced an internal property `currentRow` in the table column settings, The above use case could be solved by passing this object properties to the API/query as `{{ Api1.run('undefined', 'undefined', { ...currentRow})`, More info [here](https://docs.appsmith.com/framework-reference/run#passing-params-to-run), Does this resolve your problem?

Additional we also plane to add another internal property `triggeredRow` which will be accessible in the table actions setting, You can use this property to fetch the last selected row while executing an action. This will be available in for single / multi select table.

**Comment by Nikhil-Nandagopal** [comment]
Yeah this makes sense lets close it in favor of #2444
