### ISSUE TITLE
[Bug]: The response section is not scrollable.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#22287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The response section is not scrollable.

### Steps To Reproduce

1. Create a find documents query 
2. After running the query, try to scroll up the response section

Observe - Its not scrollable

### Environment

Release

### Issue video log

https://knynrq7fk9.vmaker.com/record/LLC7JoulVxSJg8Gk

### Version

1.9.15

**Comment by Irongade** [comment]
Closing this issue, as it is not reproducible.

**Comment by ChandanBalajiBP** [comment]
This issue was addressed in the PR #22291.
