### ISSUE TITLE
[Bug]: Unable to see errors in the debugger when we are on the canvas

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/8effb467b8b548b984b09533ddce4184

### Steps To Reproduce

1. Add List widget
2. Check debbuger in query page and in Edit page

Link to app: https://release.app.appsmith.com/app/untitled-application-58/page1-6426a0bb1c4fef2243dd9bbd/edit/queries/6435426609e4e275bbbb6dc0

### Environment

Production

### Version

Release

**Comment by prapullac** [comment]
@ChandanBalajiBP : The issue exists on master as well 
As per my observation the **reference error** of list widget is not displayed in error tabs however when we tried to reproduce this error with Table or any other widget error messages  were displayed  on both query page as well as canvas.
Hence removing the tag "release blocker"

**Comment by bharath31** [comment]
@kamakshibhat-appsmith are you still able to reproduce this?

**Comment by AnandiKulkarni** [comment]
This is reproducible - Add list widget >> click on add data source >> click on debugger >> check for error pane from debugger, Number of errors for list widget is displayed, These errors are not displayed when user is moved to canvas

<img width="1424" alt="image" src="https://github.com/appsmithorg/appsmith/assets/80756091/263d7367-6432-4229-99ff-f2e6beea4235">

**Comment by satbir121** [comment]
@bharath31 to come back with why we are not showing errors on canvas - Discussion needed with Widgets pod.

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/user-attachments/assets/addb895d-b341-4d45-88e8-a38503d5b01c
