### ISSUE TITLE
[Feature] Allow users to configure a page size for server side pagination

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2230]
## Motivation

This will allow us to disable the next page button if the page size is lower than the expected page size. Read more about the conversation here #2107 & #1578

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon @vivekverma2312 @somangshu this feature doesn't work very well.
It's supposed to disable the next option for the pagination but doesn't do that. It's also meant to display this information to the user somewhere but it doesn't. This also feels specific to the server side pagination use case.
This also does not change the Table1.pageSize value.
I also don't think it should be this high in the order of properties. Header options is also too high and should be below actions

**Comment by somangshu** [comment]
@Nikhil-Nandagopal The `Total record count` is working in tandem with the `Page size`. Looks like `total count / page size = the number of pages`. Before we had to configure the offset of pagination in the query itself, this will help the developer change is easily, hence I find the `page size` useful. @vicky-primathon correct me if I am wrong.


https://user-images.githubusercontent.com/11089579/123612413-223e6680-d820-11eb-9e90-b833f1f13739.mov

@RakshaKShetty please create issues for the following:
- The `Total record count` and `Page size` should only be visible when the server side pagination is enabled.
- The above fields should not show any errors in their default state.
- The header option should be re-ordered before the `actions` section.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu you still need to set the offset in the query, it's set as {{Table1.pageSize}} and it's automatically calculated based on the height of the table.
The total record count should not be mandatory and it should work even if not specified
It doesn't give any visual indicator which it is supposed to as mentioned in the original request
It does not reflect the internal pageSize value which is very wrong

**Comment by somangshu** [comment]
@Nikhil-Nandagopal If `pageSize` should be calculated based on the table size, then I believe the field is not required at all. @vicky-primathon is this something possible in case of server side pagination? Why didn't we do it in the first place as it already exists for the client side pagination?

- Makes sense, @RakshaKShetty this should be included as well. 
- What is meant by a visual indicator, I can see that the buttons get disabled. Are you talking about something else?
- Again when we talk about the internal `pageSize`, is the expectation here to calculate it based on the table height which happens in case of the client side pagination.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu this fields serves a different purpose. Page size today is already auto calculated. This is for the case that on client the table can show 10 rows but the API only returns 8 rows. Now if we can configure this field, then the next button can be disabled when the API returns < 8 rows. It was a very small case we wanted to handle and in hind sight maybe instead of this field we should have a field called disableNextPage or something more obvious

**Comment by somangshu** [comment]
@vicky-primathon Note:
- The page size changes based on the table height, The `default page size` field should be removed.
- The `total row count` should disable the next / previous control based on the given formula `total count / page size = the number of pages`
- The fields should be hidden until `server side pagination` is enabled.

@Nikhil-Nandagopal please add if I am still missing something here

**Comment by RakshaKShetty** [comment]
There are issues that needs to be addressed so we are keeping this feature open

**Comment by somangshu** [comment]
We have reverted these changes. Shall pick this up based on the above discussion
