### ISSUE TITLE
[Bug]: Gsheet : The dropdown must open downwards 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#22309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to gsheet and selects from the dropdown it is observed that the dropdown opens upwards covering the other fields 

 expectation : it should open downwards so that user is able to see/view the other field

### Steps To Reproduce

1) Select Gsheet 
2) Select cmd "Fetch"
3) Select spreedsheet 
ensure there is large number on sheet in the dropdown 

<img width="1280" alt="Screenshot 2023-04-12 at 10 36 35 AM" src="https://user-images.githubusercontent.com/71753653/231360286-fda964cf-9289-4699-b27f-4a091d177247.png">

### Environment

Release

### Version

Release

**Comment by piyushkrmaurya** [comment]
This depends on the screen height. If there is a lesser space below, the dropdown opens above the button. Height of the dropdown is some fixed value. If we want it to always open down, the height will be have to be adjusted when there is lesser space   below, which may be difficult to calculate.

**Comment by prapullc** [comment]
Issue does not exists hence closing the issue
