### ISSUE TITLE
[Bug]: Change log in git sync modal shows hand icon which doesn't register a click.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#22319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Change log in git-sync modal shows hand icon which make it look clickable but it's not, ideally we should not show this icon to avoid confusion

https://user-images.githubusercontent.com/80334441/231395219-217add0c-ad44-4f7c-8bca-fd6cc3560aca.mov

### Steps To Reproduce

1. Go to git connected app
2. Open git sync modal with uncommitted changes.
3. Hover on the icon and observe hand icon is displayed

### Environment

Production

### Version

Cloud

**Comment by infinitetrooper** [comment]
This is fixed as of v1.9.47
