### ISSUE TITLE
[Bug]: Debugger shows up in canvas when navigating back from query page after running a query

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#22311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After a running a query from query page, when we navigate back to widgets, the debugger shows up in canvas

### Steps To Reproduce

1. Create a new API on query page
2. Run the query
3. Navigate back to widget page
4. Observe that there is a debugger pops up

### Environment

Release

### Issue video log

https://www.loom.com/share/6b459414c8d04edb85560dfcefd962da

### Version

Cloud / Release

**Comment by ChandanBalajiBP** [comment]
Addressed in #23077
