### ISSUE TITLE
[Bug]: Existing page load action with setTimeout is failing on an object

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Existing function set to run on page load with `setTimeout` + `setInterval` configured fails to run with the following error logged
![image](https://user-images.githubusercontent.com/79509062/231386574-920cf367-9afd-4f1d-b966-bfbc4ee819f4.png)
![image](https://user-images.githubusercontent.com/79509062/231386637-312b84d6-8cd1-4044-9f97-af79b58d2a0e.png)

Creating a new object with the same `setTimeout` + `setInterval` combination works fine when set to run on page load

### Steps To Reproduce

1. Go to the object at this location and observe the page load error displayed

### Public Sample App

https://release.app.appsmith.com/app/automation-test-cases-og/page-2-6434491376e3ea7c4708b858/edit/jsObjects/6434491476e3ea7c4708b8f8

### Environment

Release

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami could you share the code snippet for setInterval + setTimeout usage? 

also, could this be a regression of #20225?

**Comment by ramsaptami** [comment]
The sample application attached has the snippet @bharath31. It seems to be a specific scenario with old code that's failing and trying to toggle page load setting for that function `both` causes and execption
Tried out a [new code](https://release.app.appsmith.com/app/automation-test-cases-og/page-2-6434491376e3ea7c4708b858/edit/jsObjects/64365b1226582a36c38eaed4) with the same interval+timeout style but that is working fine on the same app/page

**Comment by ramsaptami** [comment]
Related to canvas changes on mobile responsiveness feature
cc: @rahulramesha

**Comment by rahulramesha** [comment]
@ramsaptami, I feel like the URL returning 404 and the type error could be unrelated. Need to check the same, Could you please help me with the snippet on the App, i'm unable to access the Application mentioned in your previous comment as well.

**Comment by rahulramesha** [comment]
Can confirm that the snapshot URL returning 404, is not related to this particular issue.
