### ISSUE TITLE
[Bug]: Cannot connect MSSQL Datasource.

### ISSUE THREAD

**Issue by BRM-SMS** [appsmithorg/appsmith#22326]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When im adding a MSSQL Datasource, there is no connection. When clicking Test, there is also no output, not even in the logs.
Datasource does not work. Hostname/IP is reachable and nothing blocked.

### Steps To Reproduce

1. Add MSSQL Datasource
2. Fill in correct Host,Port,User,Pass
3. Click Test

### Environment

Production

### Version

Self Hosted - v1.9.15

**Comment by Nikhil-Nandagopal** [comment]
@BRM-SMS are you able to write a query on top of the database?

**Comment by sumitsum** [comment]
Hi @BRM-SMS is this a named MsSQL instance ? If so, then please checkout this issue for a workaround: https://github.com/appsmithorg/appsmith/issues/15531
