### ISSUE TITLE
[Bug][Refactor bucket]: In auto layout mode, after discarding changes, app still shows uncommitted changes.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#22328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/231421635-813bc486-28b6-4892-8f78-16fe4693a187.mov

### Steps To Reproduce

1. Go to a git connected app
2. Click on convert to auto layout option
3. Commit changes
4. Drag and drop a button
5. Discard changes in git sync modal
6. Observe even after discarding, app still shows changes to commit.

### Environment

Release

### Version

Release

**Comment by RakshaKShetty** [comment]
The auto layout option has been changed and when we tried to repro the issue its not reproducible, hence closing the issue
