### ISSUE TITLE
[Bug][Widget Responsiveness] Issues with Date picker when coverted to auto layout for a specific app

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22325]
<img width="1003" alt="Screenshot 2023-04-12 at 2 43 00 PM" src="https://user-images.githubusercontent.com/113327629/231412466-dd691385-36c0-4cb1-bc10-0abcfd684536.png">
 this is happening for a specific app. 

https://ce-21386.dp.appsmith.com/app/appsmith-regression-app-2/dashboard-64366e8b8381eb4a87912e66

APP json

[Appsmith Regression App.json.zip](https://github.com/appsmithorg/appsmith/files/11213386/Appsmith.Regression.App.json.zip)

**Comment by aswathkk** [comment]
Datepicker in fixed mode had a left aligned Label.
In auto-layout, we will place it at the top.
The layout was getting broken since the DatePicker doesn't have auto-height enabled for it.
Enabling auto-height is going to fix this isse
