### ISSUE TITLE
[Feature]: Add fuzzy search to code autocompletion in editor

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#22331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

At the moment a developer has to type the complete case sensitive name to get the autocompletion suggestion. Usually a developer only remembers a few keywords of a function name.

The current autocompletion works on an exact match and thus isn't able to return suggestions many times when a developer tries to type the function name using a few keywords.

A fuzzy search on the autocompletion would help give suggestions from a few keywords and improve developer experience.

For example, to get Table1.currentSelectedRow, the user would be able to get suggestion by just typing `tbl1cuserow` instead of `Table1.currentSelectedRow` in the current implementation

### Why should this be worked on?

To improve developer coding experience and their speed in the editor.

**Comment by bharath31** [comment]
This should be tackled via error messages or auto-correct instead of fuzzy matches on autocomplete. Reason: fuzzy match would pollute autocomplete suggestions.

**Comment by rajatagrawal** [comment]
@bharath31 

Can you please suggest how this use case would be handled with error messages/auto correct ?

**Comment by bharath31** [comment]
@rajatagrawal I don't have a full solution here. Imagine a lint error that says `Tabl1 is undefined did you mean Table1?`. 

Fuzzy search isn't the right way to solve it based on reasons listed in my previous comment. So marking this issue closed. Let's take this discussion offline to brainstorm other potential solutions for this problem.
