### ISSUE TITLE
[Bug][Conversion Algorithm] The snapshot/restore api is failing for some of the apps

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22346]
1. A-force app

[A-force Roster.json.zip](https://github.com/appsmithorg/appsmith/files/11213362/A-force.Roster.json.zip)

2. Regression app

[Appsmith Regression App.json.zip](https://github.com/appsmithorg/appsmith/files/11213372/Appsmith.Regression.App.json.zip)

https://www.loom.com/share/30c1939a97144fe2bd1aaa2d5f5cd445

**Comment by rahulramesha** [comment]
Seems to be working as expected, not sure if something else has fixed it. please retest
