### ISSUE TITLE
[Bug] on selecting or deselecting the the data type Time the highlighter flickers

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2235]
Steps to reproduce:
1) Add a table
2) Click on action icon of the column
3)Click on Time as datatype
4) Now  select the output and input 
and observe
5) Click on Clear 
and observe

Observation :
it is observed that the highlighter flickers on selection and deselection

Expectation:
Highlighter should not flicker on selecting or deselecting the the data type Time 

Video Link:
https://www.loom.com/share/02e444a1baf5494a801af006ecb94858

**Comment by riodeuno** [comment]
We're changing the way column types are selected with the new table widget feature. So, this will be a non-issue.
