### ISSUE TITLE
[Bug]: selectedDate and formattedDate are inconsistent with each other

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#22352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `selectedDate` property of the Select widget will give the output in a UTC format (GMT) but the `formattedDate` property gives the output in your browser's locale format. When using the `No Time` setting of the widget this causes the `selectedDate` to be one day behind.

I expect the timezone to be the same in both instances and would like the added ability to choose whether to use UTC or my locale time.

### Steps To Reproduce

1. Set locale to one with active Daylight Saving Time.
2. Select a date after the start of DST (e.g. 1st April with the time 0:00)
3. Observe that the selected date is 1 hour, and by extension 1 day, behind. (e.g. 31st of March at 23:00)

### Environment

Production

### Version

Cloud 1.9.15-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9b0ss)

**Comment by umeshdiwekarrapiddata** [comment]
Any progress on this. I'm also facing the same issue

**Comment by Nikhil-Nandagopal** [comment]
This is not a bug. The formatted date is meant to be in the timezone of the users browser as it's a display date.
@umeshdiwekarrapiddata 
If you need to format the value based on timezone the correct option would be to use moment to format it.
`{{moment(DatePicker1.selectedDate).tz("America/Los_Angeles").format("DD-MM-YYYY HH:mm")}}`
