### ISSUE TITLE
[Bug]: The application is not loading in the air gaped instance

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The application is not loading in the air gaped instance
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/231701347-bd5ce295-81ae-4397-b8e8-f4234f19fb69.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet 
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up 
5. add air gapped license key
6. go to home page click on any app 
7. The app loads in a infinite loop

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
This works fine now.
