### ISSUE TITLE
[Bug]: AirGapped instance - Telemetry option is visible after entering details on the Welcome Page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While setting up an airgapped instance, the Usage Data Preference option is visible
As per design of Airgapped image, this should not be present.

### Steps To Reproduce

1. Pull the image with the command docker pull ankitakinger/appsmith:airgap
2. Switch off internet and execute the docker run command
3. Now start doing the set up. After entering all your details, on the next screen, note that the Usage Data Preference option is visible.
<img width="1043" alt="Airgapbug1" src="https://user-images.githubusercontent.com/101863839/231719848-10f4a920-bdd7-4d7e-bd1d-0c59c0190212.png">

### Environment

Release

### Version

Self Hosted

**Comment by berzerkeer** [comment]
This is being worked as part of onboarding revamp on usage and billig pod by @dipyamanbiswas07 Once this is done, we simply have to not show the `Telemetry` toast once the use completes signup and lands on the tutorial page.

**Comment by btsgh** [comment]
Taken straight to the license key- works as expected.
