### ISSUE TITLE
feat: WDS negative color tokens

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#22365]
Currently: hardcoded values.

Needed: check the seed for `isRed`, if it is: pick a maximally distant hue in the Red range (`29..50`), otherwise pick some default. Contrast and other checks for `-accent-` colors apply with minor adjustments (`negative`, being an error state color, can/should be more prominent that `accent`).

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/22365?planning-poker) with Zenhub @ichik @jsartisan @KelvinOm
