### ISSUE TITLE
[Bug]: In firefox browser the Image is missing in the license page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In firefox browser the Image is missing in the license page
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/45958978/231717882-357aa4d5-41c5-445e-a8c6-ea6543f339e2.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. In the license page the Image is missing the the extra text "No Active subscription "  is displayed

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
Image is present now.
