### ISSUE TITLE
[Bug]: AirGapped instance - License key UI looks a little off - It should be shortened.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In an airgapped intstance in the Admin settings page, the License and Billing tab, the License key shown to the user is quite long and seems a little off. Can this be shortened to a line? 

### Steps To Reproduce

1. Pull the image with the command docker pull ankitakinger/appsmith:airgap
2. Switch off internet and execute the following:
docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
3. Now do the set up
4. Add air gapped license key
5. On the home page, go to Admin Settings - > License and Billing tab
6. Here note that the License key shown to the user is quite long and seems a little off. Can this be shortened to a line? 
<img width="937" alt="Airgap_Licensekey" src="https://user-images.githubusercontent.com/101863839/231726243-474e15ad-1c96-4ef9-aa78-c7c4671d2750.png">

### Environment

Release

### Version

Self Hosted

**Comment by abhvsn** [comment]
Just to be clear when you said shorten are we saying having a similar UI to that of enterprise or self-serve licenses?

cc: @btsgh

**Comment by btsgh** [comment]
@abhvsn - what I meant here was there are too many xxx 's and the part of the key shown is also too long. Can we not make it show just like the first few characters and then a few x's and then a few dots and end it within one line ?

**Comment by abhvsn** [comment]
Let's follow the same format that we already have for enterprise and self-serve.
<img width="1130" alt="Screenshot 2023-04-13 at 11 26 36 PM" src="https://user-images.githubusercontent.com/41686026/231844215-2b1a8fea-c4dc-4fba-b363-c52659bc202c.png">

**Comment by btsgh** [comment]
Verified
