### ISSUE TITLE
[Bug]: In firefox browser the logo seems to be broken in the branding page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In firefox browser the logo seems to be broken in the branding page
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/45958978/231722508-b909b14e-d066-4de4-bec2-476d4b52ac58.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. add air gapped license key
6. go to home page 
7. click on admin setting
8. click on branding
9. The image seems to be broken in the last card

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
Fixed now

**Comment by btsgh** [comment]
Verified
