### ISSUE TITLE
[Bug]: In firefox browser,The image is broken in the License update model

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In firefox browser,The image is broken in the License update model
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/45958978/231723916-f7894138-dc11-4d5c-b587-02e9d8da6830.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. add air gapped license key
6. go to home page 
7. click on admin setting
8. Click on license & billing tab
9. Click on update button 
10. the image is missing

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
Tested and works fine
