### ISSUE TITLE
[Bug]: AirGappedinstance - License and Billing page - license is displayed as Trial. Home page - Upgrade links are visible

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 After setting up and logging into Air gapped instance, in the Admin Settings -> License and Billing page - License is displayed as Trial. Also, on the Home page - Upgrade links are visible.

### Steps To Reproduce

1. Pull the image with the command docker pull ankitakinger/appsmith:airgap
2. Switch off internet and execute the docker run command
3. Now do the set up
4. Add air gapped license key
5. On the home page, note that upgrade links are visible in two places.
6. Also in Admin settings - license and billing page, the key is displayed as trial version

<img width="1407" alt="Airgap_Upgradelink" src="https://user-images.githubusercontent.com/101863839/231724726-b54bdfaf-2a65-47f3-8645-6b6fedc6e95e.png">

<img width="1306" alt="Airgap_LicenseKey_Trial" src="https://user-images.githubusercontent.com/101863839/231724266-912f3268-ac1f-461d-a9f3-de17fe62599c.png">

### Environment

Release

### Version

Self Hosted

**Comment by abhvsn** [comment]
@btsgh added a type parameter in license manager app for generating PAID licenses, if you want to take a look into paid license UI.

**Comment by abhvsn** [comment]
@berzerkeer is this still pending? @btsgh are you able to test the flow for PAID license as well?

**Comment by abhvsn** [comment]
@berzerkeer is this still pending? @btsgh are you able to test the flow for PAID license as well?

**Comment by abhvsn** [comment]
@berzerkeer I was referring to upgrade link, this should not show up even if the license type in TRIAL right?

**Comment by btsgh** [comment]
@abhvsn  @berzerkeer - sorry for the delayed response on this. If I use a paid license, it works fine. I do not see both the issues. Will update here to observe what happens if I use the trial license

**Comment by btsgh** [comment]
@abhvsn @berzerkeer  - So if I use the trial license, here is what I observe: 
1. Upgrade links are still present. 
2. In the license and billing page, it shows up correctly as Trial.
<img width="1440" alt="Screenshot 2023-04-18 at 6 47 52 PM" src="https://user-images.githubusercontent.com/101863839/232790261-9cf34a1d-bf65-4602-bee3-b5d23f8a156b.png">

**Comment by abhvsn** [comment]
@berzerkeer basic premise is what happens after user clicks on upgrade? What are the next steps user can perform? IMO as this is airgapped nothing we can do here. User will have to come back to us via communication channel. 

cc: @infinitetrooper

**Comment by berzerkeer** [comment]
Yeah, nothing they can do. This `Upgrade` has no meaning in airgapped instances if we are going with `TRIAL` and `PAID` license format for airgap. I have a vague memory of @infinitetrooper mentioning that we won't be taking that route, where TRIAL licenses are nothing but `PAID` license with 30 days expiry and we won't have all these banners etc. 

But that being said, I have already made the change to remove the `Upgrade` links on Airgap trial licenses with `TRIAL` status. And its in my PR.https://github.com/appsmithorg/appsmith-ee/pull/1295

if you guys decide otherwise, we can revert the change.

**Comment by infinitetrooper** [comment]
Yes, we will insist on paid licenses only even for 30 day time period. Keep the ticket open but, this is Low.

**Comment by trishaanand** [comment]
This is completed.
