### ISSUE TITLE
[Bug]: The appsmith logo is missing in the view mode

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The appsmith logo is missing the view mode
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/45958978/231721812-4515f4a4-b862-4d27-a2a1-abb3e1ecec14.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. add air gapped license key
6. go to home page
7. click on launch application button
8. On the top left corner the appsmith logo is missing

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
Tested and works fine
