### ISSUE TITLE
[Bug]: In firefox browser the "No active subscription text is displayed in the home page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In firefox browser, the "No active subscription text is displayed in the home page
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/45958978/231720668-d9a77c3f-1f1e-4bd8-bef0-f14417634370.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. add the valid license key
6. Now go to home the unwanted text is displayed in the home page

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
Tested and found to be fixed.

**Comment by btsgh** [comment]
Verified
