### ISSUE TITLE
[Bug]: AirGappedinstance - Version not displayed correctly in Admin settings as well as Home Page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the home page as well as in the Admin Settings - Version tab, the version is displayed incorrectly.

### Steps To Reproduce

1. Pull the image with the command docker pull ankitakinger/appsmith:airgap
2. Switch off internet and execute the docker run command
3. Now do the set up
4. Add air gapped license key
5. On the home page, on the bottom left, Appsmith version does not come up
6. Also, in Admin Settings - Version tab, the version is displayed incorrectly.
<img width="539" alt="Airgap_Versionhomepage" src="https://user-images.githubusercontent.com/101863839/231722721-fbbc4d24-75ba-4a4a-9ee8-58e1decbc996.png">

<img width="648" alt="Airgap_Version_AdminSettings" src="https://user-images.githubusercontent.com/101863839/231722822-5c005f6d-dbf8-423b-a4bd-df2edc7824bc.png">

The correct method of display should be similar to below: 
<img width="1416" alt="image (8)" src="https://user-images.githubusercontent.com/101863839/231722982-80faadca-e64d-45ea-9457-15ed1938ddc4.png">

### Environment

Release

### Version

Self Hosted

**Comment by abhvsn** [comment]
Closing this as already fixed

**Comment by btsgh** [comment]
Reopening this issue to track the correct format of the version string that is to be displayed.

Edition - Appsmith Airgapped v1.9.xx
Image name - appsmith-airgap

**Comment by abhvsn** [comment]
Closing this as already merged.
