### ISSUE TITLE
[Bug]: The error message  should be intuitive when the user adds an invalid license key

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The proper error message is not displayed when the user adds an invalid license key
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/45958978/231719712-85362ac2-f3a7-4e0a-b20a-69c566b1de68.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. In the license page add the wrong license the error message displayed is not intutive

### Environment

Release

### Version

release

**Comment by abhvsn** [comment]
@RakshaKShetty can you also share the network logs to check which API returned with 4xx/5xx? This will help assign the issue to correct stakeholder.

**Comment by abhvsn** [comment]
We are not seeing this hence closing now!
