### ISSUE TITLE
[Bug]-[2]:Camera widget data url creation doesn't take the port number into account

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#22387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when creating an image data URL we're not taking the port number into account, so if the app smith is running on a port other than 80, an invalid imageDataURL is generated. 

### Steps To Reproduce

1. Run Appsmith in a port other than 80
2. add a camera widget
3. take a pic and observe that imageDataURL is wrong.

### Environment

Production

### Version

cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9gocs)

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2 |
| Effort (months)  | 0.5 |
