### ISSUE TITLE
[Bug]: Some unknow widgets are displayed in widgets section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some unknow widgets are displayed in widgets section
<img width="691" alt="image" src="https://user-images.githubusercontent.com/45958978/231847087-8232554f-51fd-4ab6-a1b2-f57dd33b16e0.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. add air gapped license key
6. go to home page
7. 

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
Tested and works fine now

**Comment by btsgh** [comment]
Verified
