### ISSUE TITLE
[Bug]: The icons are broken for authenticated API and authenticated GraphQL

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The icons are broken for authenticated API and authenticated GraphQL
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/45958978/231845670-4385a869-358e-4ade-8781-a860dbab7527.png">

### Steps To Reproduce

1. first pull the image docker pull ankitakinger/appsmith:airgap
2. now switch off the internet
3. now docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
4. Now do the set up
5. add air gapped license key
6. go to home page
7. click on edit 
8. click on + icon next to datasource
9. The icons are broken for authenticated API and authenticated GraphQL

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
@berzerkeer  - Issue still exists for OAuth API

**Comment by berzerkeer** [comment]
> @berzerkeer - Issue still exists for Auth API - refer screenshots for both chrome and firefox
> 
> <img alt="Screenshot 2023-04-17 at 3 42 04 PM" width="376" src="https://user-images.githubusercontent.com/101863839/232455207-30e3878e-121d-4a10-a183-307ec92d25be.png">
> 
> <img alt="Screenshot 2023-04-17 at 3 42 09 PM" width="390" src="https://user-images.githubusercontent.com/101863839/232455202-0a08104c-304b-42ad-8449-0fe052012d96.png">

Right, I think I added this after updating the docker image , I will update the image again. Also check if this https://github.com/appsmithorg/appsmith/issues/22437 has been fixed, if this is not, then its likely I haven't updated the image with the latest changes.

**Comment by btsgh** [comment]
Tested and works fine now

**Comment by btsgh** [comment]
Verified.
