### ISSUE TITLE
[Bug]: Air Gapped instance - Rich Text editor comes up blank on the canvas

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In an airgapped intstance, on DnD of Rich Text Editor widget, it comes up blank on canvas

### Steps To Reproduce

1. Pull the image with the command docker pull ankitakinger/appsmith:airgap
2. Switch off internet and execute the docker run command
3. Now do the set up
4. Add air gapped license key. 
5. Inside the application, try to DnD a Rich text editor widget. Note that it comes up blank

<img width="372" alt="Screenshot 2023-04-14 at 10 03 08 AM" src="https://user-images.githubusercontent.com/101863839/231944033-e3f67aeb-03af-478e-94db-57f4c5fc4261.png">

On Release it is like this - 
<img width="895" alt="RTE_Release" src="https://user-images.githubusercontent.com/101863839/231944238-dbba1562-b1f6-4e38-bb54-de03a4a6e52b.png">

### Environment

Release

### Version

Self Hosted

**Comment by berzerkeer** [comment]
Right now, we are loading the editor script (`TinyMCE`) via CDN. This should be changed to import via modules since we have the package already. I changed and tested it worked , but the styles for the text area didn't get applied. So working on that. Will get help from @jsartisan on this.
