### ISSUE TITLE
[Feature]: Need to support prettier for copied code blocks that don't have any spacing

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Copied code without any spaces in between does not prettify currently and the platform needs to support it

### Why should this be worked on?

Make code more readable

[Video](https://www.loom.com/share/206eb8edacb64a719e8adf2450cba796)

Attaching sample application with code that needs to be supported
[--prettify & error code sample.zip](https://github.com/appsmithorg/appsmith/files/11229942/--prettify.error.code.sample.zip)

**Comment by bharath31** [comment]
@ramsaptami could you please attach a loom video?

**Comment by bharath31** [comment]
closing this in favour of https://github.com/appsmithorg/appsmith/issues/24658
