### ISSUE TITLE
Incorrect modal message when removing App access to user in members page

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#22425]
We should replace "workspace" with "app"

![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/b87f40da-5d84-4997-86ac-7d30ec2657e2)

**Comment by RakshaKShetty** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/236478661-67a87c2f-3728-45ac-88da-33967ecc8f16.png">
