### ISSUE TITLE
[Bug]: JS object update calls are run during app load

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JS object update calls do not need to run on page load but it's been observed to do so

### Steps To Reproduce

1. Go to app at [this](https://release.app.appsmith.com/app/mutant/page1-640f0f6f1c0aec73be57f0cb/edit) location and observe network calls on app load

![image](https://user-images.githubusercontent.com/79509062/231994258-cf9ac507-f6fa-4a41-bc63-5b15b5d267a8.png)

### Public Sample App

https://release.app.appsmith.com/app/mutant/page1-640f0f6f1c0aec73be57f0cb/edit

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
@arunvjn any reason why we run the update calls on app load?

**Comment by bharath31** [comment]
@ramsaptami is this still an issue?

**Comment by shoaib-31** [comment]
@bharath31 Hi, please assign this issue to me. I want to contribute on it. This is my fisrt time, can confirm that the fix would just be to remove that PUT req. on page load?

**Comment by ramsaptami** [comment]
Does not seem to be happening on the sampled + new application anymore, do you'll want to still investigate this? @satbir121

**Comment by Nikhil-Nandagopal** [comment]
Closing this since it's not happening
