### ISSUE TITLE
[Bug]: Trying to sign up with a 64 character password fails

### ISSUE THREAD

**Issue by spantaleev** [appsmithorg/appsmith#22429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to register with a too-long password fails and you don't even get an indication about it.

### Steps To Reproduce

1. Install Appsmith using the [recommended docker-compose setup](https://docs.appsmith.com/getting-started/setup/installation-guides/docker)
2. Click the **Get Started** button
3. Enter your user information and make sure to use a 64 character password (well, or any password longer than 48 characters)
4. The page reloads, you temporarily end up on `/setup/welcome?error=Password+length+should+be+between+6+and+48`, but you don't see anything about this error on the page itself
5. A few seconds later, page reloads again and you're back on `/setup/welcome`

### Environment

Production

### Version

Self Hosted - latest

**Comment by rohan-arthur** [comment]
![Screenshot 2024-03-11 at 12 15 11](https://github.com/appsmithorg/appsmith/assets/94514895/69639b7f-b227-431a-ba9b-3a2b909b8ccd)

we show an appropriate error now
