### ISSUE TITLE
[Bug]: Unable to see the default images that comes on the first drop in Image widget

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

-

### Steps To Reproduce

<img width="724" alt="Screenshot 2023-04-14 at 3 22 52 PM" src="https://user-images.githubusercontent.com/113327629/232030784-4d02d5dc-7700-4f4c-95f3-cacf612f0b43.png">

Steps:
1. Drop a image widget or List widget(List has image as child)

### Environment

Release

### Version

release

**Comment by btsgh** [comment]
Tested and found to be fixed.

**Comment by btsgh** [comment]
Verified on latest pull.
