### ISSUE TITLE
[Bug]: In the file picker overlay, No internet connection error is showing up

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

-

### Steps To Reproduce

<img width="854" alt="Screenshot 2023-04-14 at 2 59 14 PM" src="https://user-images.githubusercontent.com/113327629/232029792-6de36831-b565-43db-9ace-b073f5f4d430.png">

### Environment

Deploy Preview

### Version

Release

**Comment by btsgh** [comment]
Verified
