### ISSUE TITLE
[Bug]: Air Gapped instance - Two icon widgets are displayed on the canvas

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#22441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In an airgap instance, when the user searches for the icon widget in the search bar then 2 icon widgets are displayed.

### Steps To Reproduce

1. Pull the image with the command docker ```pull docker pull appsmith/appsmith-airgap:test```
2. Switch off internet and execute the docker run command
3. Now do the set up
4. Add air gapped license key.
5. Inside the application, in the widget search bar search for **Icon** widget & observe
 **Note**
Please refer the attached SS:- 
![image](https://user-images.githubusercontent.com/93259714/232073610-ae1c0def-b8c3-409d-a722-60c97bac1c2c.png)

### Environment

Release

### Version

Self Hosted

**Comment by btsgh** [comment]
Verified and found to be fixed
