### ISSUE TITLE
[Feature] Ability to write comments / notes for Queries / APIs / widgets

### ISSUE THREAD

**Issue by pric-appsmith** [appsmithorg/appsmith#2245]
## Summary

Ability to write comments.

## Motivation

For complex queries / APIs / widgets, it helps to write a quick summary of what they do, or what data they have, for a better understanding of the code. 
For eg. an API URL like this `https://discord.com/api/channels/<channel_number>/messages` doesn't communicate which channel's data is being fetched. Here a comment would be helpful - It's similar to why we write comments in our codebase.
Or, another example, a table widget's `Table Data` could be a lengthy JS doing data-transformation. In this case also, a summary in words will be helpful to understand the code.

**Comment by Nikhil-Nandagopal** [comment]
@pric-appsmith thanks for the feature request! This would be really helpful for new devs coming into existing apps

**Comment by rishabhsaxena** [comment]
This is now being tracked as #5601
