### ISSUE TITLE
[Feature]: Increase the text limit for tab titles

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#22455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today the text limit of tab widget's characters is 20 characters post which it truncates. Developer wants to increase this to ensure the text doesn't cut off
<img width="467" alt="Screenshot 2023-04-17 at 10 06 54 AM" src="https://user-images.githubusercontent.com/19730984/232379280-351ae410-6e03-4260-9768-62249078678a.png">

### Why should this be worked on?

When I am organising content in tabs, I want to be able to use longer titles for my tabs so that I can provide more descriptive labels for my app's content and improve its usability.

**Comment by somangshu** [comment]
@dilippitchika do you have a solution in mind?

**Comment by dilippitchika** [comment]
Not yet, i have asked client team to let us know what the names of tabs they are looking to use are. Based on that we want to understand how to change this

**Comment by Vishrut19** [comment]
Hey! Can I work on this issue?

**Comment by dilippitchika** [comment]
Hey @Vishrut19 we are waiting for our client to suggest us the new limit, that's taking some time. Let me try to expedite it, in the mean time feel free to pick other good first issues.

**Comment by dilippitchika** [comment]
Hey folks @somangshu and @Vishrut19 the new limit for text should 25 characters or 160px, whichever is maximum

**Comment by Vishrut19** [comment]
Hey! I am interested to work on this issue. Can I do it?

**Comment by dilippitchika** [comment]
Thanks @Vishrut19 assigning to you. Please let us know if you can raise a PR in next 2-3 days.

**Comment by Vishrut19** [comment]
Sure! I will raise the PR asap.

**Comment by somangshu** [comment]
@Vishrut19 if you raise a PR please let us know here, It might get missed otherwise!

**Comment by Vishrut19** [comment]
> Thanks @Vishrut19 assigning to you. Please let us know if you can raise a PR in next 2-3 days.

Can you please send me some docs or something to run it locally?

**Comment by dilippitchika** [comment]
@Vishrut19 here's the link to our client setup - https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md

**Comment by palashkaria** [comment]
Hey @dilippitchika if this is still open, I have a fix ready locally. Let me know if I can take it up

**Comment by dilippitchika** [comment]
Hey @palashkaria thanks, i am assigning this to you. Feel free to take it up.

**Comment by Vishrut19** [comment]
Hey, @palashkaria are you on discord? I need to talk to u to understand something

**Comment by mainakpandit** [comment]
hi @dilippitchika, is this issue still open? If yes, can I pick it up?

**Comment by palashkaria** [comment]
Hey @Vishrut19, sure let's connect, I'm at palash#4479

@dilippitchika the PR is raised, but I'm not sure how to raise a review request?

**Comment by somangshu** [comment]
Thanks @palashkaria, I linked the PR to the Issue. We will review this and get the ball rolling

**Comment by Vishrut19** [comment]
> Hey @Vishrut19, sure let's connect, I'm at palash#4479
> 
> @dilippitchika the PR is raised (#23039), but I'm not sure how to raise a review request?

Hey @palashkaria! I have sent you a friend request on Discord. Please accept it.

**Comment by dilippitchika** [comment]
@Vishrut19 we are reviewing the code for the PR, feel free to checkout some other good first issues

**Comment by mr-molecule** [comment]
Good day, @somangshu. I am new to this community and possess some experience with Java, but I am not an expert. I am interested in working on this project and would appreciate your guidance on the necessary technologies to learn and any beginner-friendly issues to get started. If you can provide assistance, it would be greatly appreciated and would allow me to make a good start in contributing to this project.

**Comment by somangshu** [comment]
Greetings @mr-molecule, thanks for showing interest 🎉. To find issue that you could pick up, please filter by the `good first issue` label. You will not be able to identify if is backend / frontend, but going though the issue should give some context. Regardless, if you find an issue that you are interested in, feel free to tag me and ill get back with the info you need. 

Please don't forget to read the [Contribution Guidelines] to learn more about how to get started (https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md).
