### ISSUE TITLE
[Bug]: Air Gapped instance - Two of the same widgets are displayed on the entity explorer

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In an airgap instance, when the user searches for say, the date-picker widget or multi select widget in the search bar, note 2 of the same widgets are displayed.

### Steps To Reproduce

1. Pull the docker airgapped image
2. Switch off internet and execute the docker run command
3. Now run through the usual setup and add air gapped license key.
4. Inside the application, in the widget search bar search for say, date-picker widget & observe that there are two options listed for this widget.

Same behavior noted for the following:

Date-picker
Multi Select
File picker
Input
List
Progress
Select
Table

### Environment

Release

### Version

Self - Hosted

**Comment by trishaanand** [comment]
This is fixed already.
