### ISSUE TITLE
[Bug]: Air gapped instance - I Frame widget does not show up properly on dropping onto canvas.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I Frame widget does not show up properly on dropping onto canvas.

### Steps To Reproduce

1. Pull the image docker pull sangeethsivan/appsmith-multiarch:airgap
2. Now switch off the internet and do a docker run
3. Setup the instance
4. Go to the application and drag and drop an iframe widget

It does not load properly.
<img width="774" alt="Screenshot 2023-04-17 at 7 18 43 PM" src="https://user-images.githubusercontent.com/101863839/232504898-9d62cad9-b0a4-432d-8cc6-bd637a81b91d.png">

### Environment

Release

### Version

Self Hosted

**Comment by berzerkeer** [comment]
IFrame by default points `example.com` . We should change the URL to something in the local network and not public internet. There are few ways to go about it , have a new `airgap.html` or something in and show it for airgapped instances.
Or just point to the current origin, like if they are on appsmith.com/applications it will point to the origin which is `appsmith.com` @infinitetrooper

**Comment by abhvsn** [comment]
@berzerkeer as we are not putting any url for document viewer widget for airgap due to Internet dependency IMO we should just replicate this to every other widget where we face this issue to keep the consistency.

**Comment by berzerkeer** [comment]
@abhvsn Yeah, @infinitetrooper already pointed it out and right now for Iframe and Doc viewer it will be empty url only.

**Comment by btsgh** [comment]
Tested this and, I now see a blank widget in iframe, the URL link field is blank

**Comment by infinitetrooper** [comment]
Good to go for me @btsgh.
