### ISSUE TITLE
[Bug]: Air gapped instance - Document viewer widget does not load

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On dragging and dropping a Document viewer widget, the image / widget does not load and shows No internet message.

### Steps To Reproduce

1. Pull the image docker pull sangeethsivan/appsmith-multiarch:airgap
2. Now switch off the internet and do a docker run
3. Setup the instance
4. Go to the application and drag and drop a document viewer widget
Widget does not load and shows No internet message.

<img width="842" alt="Screenshot 2023-04-17 at 6 56 11 PM" src="https://user-images.githubusercontent.com/101863839/232498983-f4fdcc62-3f9d-4526-a44f-c30176506a9b.png">

### Environment

Release

### Version

Self Hosted

**Comment by berzerkeer** [comment]
This has an internet dependency since we load a sample pdf from internet by default. I have added it to the assets script to download and place it in the public folder to server locally. Should I proceed with this @infinitetrooper

**Comment by infinitetrooper** [comment]
As discussed, The default URL should be null for Airgapped.

**Comment by btsgh** [comment]
Tested this and, I now see the text "No document url provided for viewer ", the Document link field is blank

**Comment by infinitetrooper** [comment]
Good to go for me @btsgh.
