### ISSUE TITLE
[Docs] Page not accessible

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2248]
## Documentation Link 
https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/asset-upload.md 

## Describe the problem
This page is not accessible: https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/asset-upload.md
It has been mentioned here: https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/DB%20Integrations.md

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum thanks for pointing this out. It's now been resolved

**Comment by sumitsum** [comment]
Hi @Nikhil-Nandagopal  I am still not able to access it.
