### ISSUE TITLE
[Bug]: Debugger shortcut is line deletion shortcut on the editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Debugger shortcut `Ctrl/Cmd+D` causes line deletion action on the editor

### Steps To Reproduce

1. Add a JS object to an app and hit `Ctrl/Cmd+D` - observe the debugger open and close and code line deletion where the cursor is present

### Environment

Production

### Issue video log

https://www.loom.com/share/b59ba75bcc3b41b2b177fd13150738ff

### Version

Cloud

**Comment by piyushkrmaurya** [comment]
What should be the expected behavior here? Should `Ctrl/Cmd+D` always be reserved for debugger or should it be used for line deletion when inside the JS editor and prevent debugger while editing?

**Comment by ramsaptami** [comment]
If we have insights on shortcut usage for the above scenarios, we can take a favorable call. Else, since the debugger shortcut is used across the canvas, query & code editor, it would be preferable to retain this. We can then accommodate line deletion with a similar keyboard shortcut like using Alt/Shift keys instead. @bharath31

**Comment by bharath31** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/22499?planning-poker) with Zenhub @Druthi
