### ISSUE TITLE
[Bug]: when user adds the custom domain the server restart fails 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when user adds the custom domain the server restart fails 
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/45958978/232674050-9f1b83e0-163f-4ca4-aace-83f51d021488.png">

### Steps To Reproduce

1. first pull the image docker pull sangeethsivan/appsmith:airgap
2. now switch off the internet
3. nowdocker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -p 443:443  -v "$PWD/stacks:/appsmith-stacks" sangeethsivan/appsmith-multiarch:airgap
4. Now do the set up
5. go to admin setting
6. click on advanced tab
7. add the custom domain click on save and restart the restart fails

### Environment

Release

### Version

release

**Comment by abhvsn** [comment]
Closing this as this is not related to airgap, if needed please create another ticket to track this request.
