### ISSUE TITLE
[Feature]: Filter domain names that are invalid/ not supported by Let's encrypt, and display an appropriate error to the user

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#22508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Let's Encrypt cannot provide certificates for domain names that are high-risk and blacklisted. This also includes ephemeral domain names of the cloud platforms like aws ec2 fqdn ec2-xx-xx-xx.ap-south-1.compute.amazonaws.com

### Why should this be worked on?

Improves user experience, and reduces load on support team.

**Comment by sharat87** [comment]
Now that we use Caddy, we don't have to do this ourselves.
