### ISSUE TITLE
[Bug] GSheets Fork/Import Bugs

### ISSUE THREAD

**Issue by PiyushPushkar02** [appsmithorg/appsmith#22501]
The following ticket is to investigate the issues related to Google Sheets data source while forking and importing applications.

Note: Will update the estimates once I have had the chance to look at all the failing cases.

Please find the list of bugs below :
https://docs.google.com/spreadsheets/d/1XqFfLWt-_ydmurgpw1AE8ggb3fp-q6BwFsv-BhKqX7A/edit#gid=0

**Comment by rohan-arthur** [comment]
@PiyushPushkar02 please add an estimate for this

**Comment by PiyushPushkar02** [comment]
Please check the following doc for the issue investigation.
https://www.notion.so/appsmith/Google-Sheet-Bugs-1f7f060224274b928ba545cb8e9d3bdf
