### ISSUE TITLE
[Bug]: Inconsistency with checkbox selection in ListWidget

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#22526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When navigating to the "Pick and Pack" section in the "Orders" page and attempting to select products from the "lst_orderProducts" list starting from the first item, there is an inconsistency with the checkbox selection in the list.

Specifically, when selecting the second item, the first item gets unchecked even though the logic returns true to be checked. However, when selecting the third item, the first item checkbox gets reselected.

This behavior is unexpected as the checkbox for an item should stay selected until manually deselected by the user.

Please investigate this issue and provide a fix to ensure consistent checkbox selection in the "lst_orderProducts" list.

### Steps To Reproduce

1. Open the application and navigate to the "Orders" page.
2. Select an order from the table to view its details.
3. Click on the "Pick and Pack" button to open the "Pick and Pack" tab.
4. Locate the "lst_orderProducts" list and select the first item by clicking on its checkbox.
5. Continue down the list and select the second item by clicking on its checkbox.
6. Observe that the first item's checkbox gets unchecked even though the logic returns true to be checked.
7. Select the third item by clicking on its checkbox.
8. Observe that the first item's checkbox gets reselected.

### Environment

Production

### Issue video log

https://www.loom.com/share/87f10763f7414b0ea3db106fc94272b1

### Version

Cloud -  v1.9.15-SNAPSHOT

**Comment by somangshu** [comment]
@jacquesikot are you talking about some specific template where this is happening? Please five us details about that as well. 

While you do that, Can you also check if the template is using the latest version on the widget? This has notoriously shown many bugs in the past

**Comment by Tooluloope** [comment]
Hi @jacquesikot, Could you share a forked version of the app with me? I tried the app in View Mode, and it works fine. So I need to confirm if it also works fine in Edit mode.


https://user-images.githubusercontent.com/31691737/235440352-a535021f-cf47-4b65-a029-5dc4e677e6b6.mov

**Comment by Tooluloope** [comment]
## Update

https://user-images.githubusercontent.com/31691737/235446969-ca285b5b-ed31-42b6-8672-b16352a2d7a6.mov

Fixed in https://github.com/appsmithorg/appsmith/pull/22682
