### ISSUE TITLE
[Feature]: Property that includes all the added email-addresses in a workspace

### ISSUE THREAD

**Issue by JonHerberOtto** [appsmithorg/appsmith#22529]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

My request is a property, that returns an array/set/collection or anything of that kind which include all the e-mail addresses. 
E.g. {{appsmith.workspace.addressList}}

### Why should this be worked on?

My use-case is the following:
I want to send out a notification-e-mail everytime someboy changes some date within my app. This notification should reach everybody within the workspace. Hence my SMTP-query should include all the e-mailaddresses of every user in the workspace. Right now I would have to hardcode all those into the query.

**Comment by JonHerberOtto** [comment]
Hello @pranavkanade,

Sorry for this, that seems to be a typo that my auto-correction did.
The app handles some masterdata for our company. Users can add new entries, or edit old ones. Once they edited/added an entry I want to alert the other users, that something has changed. I could hardcode their e-mail addresses into the SMTP-query, however I would always have to alter that query, if a new employee wants to receive the updates.

**Comment by Nikhil-Nandagopal** [comment]
This would be a security flaw so we wouldn't support this. You can always connect to the internal mongodb as a datasource and fetch the users to achieve this
