### ISSUE TITLE
[Bug]: there appears to be a weird scroll on the canvas when Currency widget/Phone input dropdown is opened in Edit mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

there appears to be a weird scroll on the canvas when Currency widget dropdown is opened in Edit mode

### Steps To Reproduce

1. DnD currency widget/Phone input widget somewhere below the fold
2. Allow currency change/Change Country Code =true
3. click on the currency dropdown
https://www.loom.com/share/dcfdbf540fd0495aa46e2a91cb0298df

### Environment

Production

### Version

Production

**Comment by somangshu** [comment]
this issue is the same as #18561. Closing in favour of that.
