### ISSUE TITLE
[Bug]: mock_db_v2 database doesn't exist in docker postgres

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#22530]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

* Download and run a new appsmith docker container using docker-compose
* create a new app
* click on "generate page from page template" button
* This opens a quick page wizard
* Select Mock_DB_V2 as datasource.
* Immediately you will see "Failed fetching datasource structure, Please check your datasource configuration" error message on the page

![Screenshot_20230418_224833](https://user-images.githubusercontent.com/5801636/232854741-c72d1122-a9b9-44c8-8c11-ef74ef80a1fd.png)

### Steps To Reproduce

```
curl -L https://bit.ly/docker-compose-CE -o $PWD/docker-compose.yml
sudo docker-compose up -d
```

Then create a new account and create a new app. select 
This opens a quick page wizard
Select Mock_DB_V2 as datasource.

**Root cause analysis:** 
```
sudo docker exec -it  appsmith /bin/bash
psql -U postgres
postgres=# \l
```

```
Name    |  Owner   | Encoding | Collate |  Ctype  |   Access privileges
-----------+----------+----------+---------+---------+-----------------------
mockdb    | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
postgres  | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
template0 | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
|          |          |         |         | postgres=CTc/postgres
template1 | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
|          |          |         |         | postgres=CTc/postgres
users     | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
```

Frontend is looking fro mockdb_v2 database. However postgres has mockdb database.

**Probable fix**
rename db 
`ALTER DATABASE mockdb rename to mockdb_v2; 
`
Once I change this manually in my container, the error is fixed and tables are getting loaded. 

### Environment

Production

### Version

Appsmith Community v1.9.15

**Comment by kamalptw** [comment]
+1

**Comment by Nikhil-Nandagopal** [comment]
We're no longer able to reproduce this on the latest version so I'm closing this issue. Please let us know if this continues
