### ISSUE TITLE
[Bug]: Add errorId to DEBUGGER_NEW_ERROR_MESSAGE event

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#22558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add errorId to `DEBUGGER_NEW_ERROR_MESSAGE` telemetry event. And also make errorId uniquer for each of the `DEBUGGER_NEW_ERROR_MESSAGE` and `DEBUGGER_RESOLVED_ERROR_MESSAGE`

### Steps To Reproduce

This event is fired on new error in the log.

### Environment

Production

### Version

Cloud

**Comment by Richarex** [comment]
This is related to mix panel events.
