### ISSUE TITLE
[Bug][Widget Responsiveness] for lower screen sizes, the widgets are unable to gain their minimum dimensions when more widgets are placed next to them

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22555]
https://www.loom.com/share/5d66a356d1ec48c4b8cdd452fc76aae5

**Comment by prsidhu** [comment]
PR: https://github.com/appsmithorg/appsmith/pull/22688

**Comment by kamakshibhat-appsmith** [comment]
ISSUE --> Check [loom](https://www.loom.com/share/3bf2f315fe6a43eda0cae1712bee3d65)

The widget dimensions are messed up in lower screen sizes when you stack widgets horizontally

**Comment by kamakshibhat-appsmith** [comment]
Issue --> https://www.loom.com/share/c621cec58ce24f6ab3325457b4a3c608
