### ISSUE TITLE
[Feature]: Allow devs to enable/disable autofill in the email and password type inputs

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#22566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Devs should be able to disable the autofill in the input widget password and email fields. 
- Add a new field called "Allow autofill" in email and password type inputs and set it to true by default 

### Why should this be worked on?

Devs in financial companies would like to ensure this is a choice as they suggest it might be a safety concern for them. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9lifg)

**Comment by dilippitchika** [comment]
Some more details on the field
1. Field name should be "Allow autofill"
1. This field should be a part of general section
2. It should be a switch field turned on by default
3. When on the email or password input will accept autofill from the end-user's browser
4. When off the email or password input will not accept autofill from the end-user's browser

**Comment by vsvamsi1** [comment]
Hi @dilippitchika these changes apply to V2 version alone?

**Comment by dilippitchika** [comment]
Yes @vsvamsi1 only to v2 of input.

**Comment by vsvamsi1** [comment]
We will be supporting for json form text fields as well.
@dilippitchika @chandannkumar
