### ISSUE TITLE
[Bug][Widget Responsiveness] Map widget is getting cut on mobile viewport

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#22562]
![Image](https://user-images.githubusercontent.com/890915/233060313-5a41c97a-0ea8-4eb9-9530-799828eb2dde.gif)

**Comment by aswathkk** [comment]
https://user-images.githubusercontent.com/10436935/233065207-4ab98b2c-10ff-4e2e-af33-e8669ffa4db6.mov

@rohitagarwal88 I'm unable to reproduce it

**Comment by andreevanatasha** [comment]
Cannot reproduce
