### ISSUE TITLE
[Bug]: Input field validation is missing for display name

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#22578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is no input field validation for display name. (Note: Add validations in backend as well)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8299030/233259583-d86bd92f-fe12-41a6-b233-e4c27dd0a98c.png">

### Steps To Reproduce

1.  Got to profile page from top right menu
2. Edit the display name

### Environment

Production

### Version

Cloud

**Comment by Lovakush** [comment]
@ginilpg I want to contribute in this issue can you assign me ?

**Comment by eco-monk** [comment]
Hey @Lovakush thanks for your interest.
I recommend you go through issues that are tagged `Good first issue`.

We might do some backend changes for this, it is yet to be finalised.

**Comment by eco-monk** [comment]
We plan to add validations on client side that allows either a name without special characters (e.g. `User name`) or a valid email ID (e.g. `user-test@domain.com`).

Question:
- [ ] Do we need backend migrations to update existing display names which have an error? (We can default to email ID)

**Comment by eco-monk** [comment]
Alternate approach suggested:
- Identify invalid characters and replace them with `_` or ` ` (space).
Don't overwrite other language characters.

**Comment by Richarex** [comment]
Working as expected verified it on release.
