### ISSUE TITLE
[Bug]: When we run the airgapped changes on 8081 port the few images looks broken on the instance

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we run the airgapped changes on 8081 port the few images looks broken on the instance

### Steps To Reproduce

1. login to localhost 8081
2. on the top left corner the appsmith logo is broken

### Environment

Deploy Preview

### Version

deploy preview

**Comment by btsgh** [comment]
Tested this on latest pull - images are coming up now.
