### ISSUE TITLE
[Bug]: While deleting the No-Action there is uncaught exception

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#22596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Uncaught exception is displayed when User is trying to delete 'No Action'
[](url)
<img width="1011" alt="Screenshot 2023-04-20 at 3 43 40 PM" src="https://user-images.githubusercontent.com/80756091/233336308-8c55590e-ac5f-48de-9b52-1314a5b1a83d.png">

### Steps To Reproduce

1. Clcik on + on Action selector pane
2. 'No action' is added, 
3. Select No Action and try deleting it
4. Verify console log and exception is displayed

### Environment

Release

### Version

cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9ikcs)

**Comment by ravikp7** [comment]
Closed with #23480
