### ISSUE TITLE
[Bug]: Session id should change post login

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#22590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Instead of generating and setting a new session id post login, we end up re-using the same session id. This behaviour should change.

### Steps To Reproduce

1. Note the session id before login
2. Log into appsmith
3. Note the session id post login.

They match today.

### Environment

Production

### Version

All instances

**Comment by abhvsn** [comment]
@trishaanand Tried the same steps listed above but couldn't able to reproduce the issue. Few scenarios I tried to reproduce:

Scenario1: 
1. Open app.appsmith.com and note session id from cookie (No active session)
2. Sign in and check if the session id is altered for the subsequent request header => Success 

Scenario2:
1. Signup as a new user on app.appsmith.com
4. Note session id and Sign-out
5. Sign-in again in same browser check if the session ID is altered => Success

Scenario2:
1. Use the same user created in above scenario to test the flows for old users
2. Signin in existing browser to refresh the session id
3. Signin into another browser with same creds
4. Verify if the session id altered before and after the login => Success
6. Also check if session ids are different on separate browser => Success
7. Signout and signing again from second browser to check if the session id is refreshed => Success

**Comment by abhvsn** [comment]
This is a false alarm as the customer was trying to match `SessionId` from `Cookie` with `X-MDC-SessionId`. X-MDC-SessionId is not used in auth flows and only passed in request header for contextual logging. Closing this now as this is not a security concern.

Ref: https://github.com/appsmithorg/appsmith/blob/7b9b63ba0b6040da3d17c8a35260689b57706380/app/server/appsmith-server/src/main/java/com/appsmith/server/filters/MDCFilter.java#L67
