### ISSUE TITLE
[Feature]: Advanced file type validation is required on profile image upload

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#22592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There is a basic client side validation exists for validating the file extension. But Users can alter the file extension to image and upload it as their profile image. 

### Why should this be worked on?

The application allows the attacker to upload or transfer files of dangerous types that can be automatically processed within the product's environment.During the assessment, it was observed that application allows to upload the php and js based files to the application which is restricted to upload the file.By changing the extension it is possible to upload the malicious file.

**Comment by harshmange44** [comment]
Maybe, using mime-type validation on the backend side should be enough? and then malicious content validation further?

**Comment by eco-monk** [comment]
Need to update with latest version of DS.
And include backend changes.

**Comment by Richarex** [comment]
LGTM! verified it on there
