### ISSUE TITLE
[Bug] Padding/Margin issues with containers

### ISSUE THREAD

**Issue by ravivyas84** [appsmithorg/appsmith#2259]
## Description

If containers are next to each other, they overlap when published.

![Screen Shot 2020-12-17 at 23 29 56](https://user-images.githubusercontent.com/283631/102528488-a622d380-40c4-11eb-8970-3c8efa8cce0f.png)

If scrolling is disabled within the container, they don't overlap

![Screen Shot 2020-12-17 at 23 34 00](https://user-images.githubusercontent.com/283631/102528513-ac18b480-40c4-11eb-8b3d-0e1becaf0ef7.png)

### Important Details
 - Version: [Cloud /]
 - OS: [MacOSX]
 - Browser [MS Edge]

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal This is not happening anymore.  
I just created an application with a container similar to the screenshot posted above. - https://app.appsmith.com/applications/5ff452b30d17d27a05365ac3/pages/5ff452b30d17d27a05365ac5
