### ISSUE TITLE
[Bug][Widget Responsiveness] List item containers are getting cropped in the mobile  breakpoint

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22602]
https://www.loom.com/share/aea4bb58e6194f078b2d72537ace166f

**Comment by andreevanatasha** [comment]
@kamakshibhat-appsmith can we get more information and screenshots? Couldn't reproduce

**Comment by kamakshibhat-appsmith** [comment]
@andreevanatasha @aswathkk Apologies, I forgot to add loom link. I have added that in description now
