### ISSUE TITLE
[Bug][Widget responsiveness] the list item container height is not getting reduced when we remove the contents inside it

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22601]
https://www.loom.com/share/fe5e5328ae684503a37166ddfa860593

**Comment by mud1tx** [comment]
@kamakshibhat-appsmith Can you give more detail related to the issue?

**Comment by andreevanatasha** [comment]
Decided to add option to resize the first item of the list manually as a workaround
