### ISSUE TITLE
[Feature]: Run logic on app load

### ISSUE THREAD

**Issue by geekyme-fsmk** [appsmithorg/appsmith#22610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, I want to run a piece of code at the app level when the user first logs in. 
- My use case is to exchange appsmith's OAUTH token for a valid API bearer token for hitting my APIs.
- At the moment I see only the ability to 'Run on page load' and not 'Run on app load' or 'Run on login', etc.

### Why should this be worked on?

Without this, I will need to run that piece of logic on every page. This is a problem because:
- I will need to 'Copy to page' potentially 80 times.
- I will need to add more custom logic / state to check whether this logic has been run once.
- If there are more logic that I need to run on app load, I will need to perform the same steps above and this is a maintenance nightmare. 

This seems possible on a competitor product - https://docs.uibakery.io/basics/working-with-actions/action-basics

> On Page Load/**On App Load** - similar to a component trigger, special app and page triggers are available. These triggers allow you to load app configuration and reuse it later on in page actions and components.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9juh8)

**Comment by Nikhil-Nandagopal** [comment]
This is going to be solved with #1911
