### ISSUE TITLE
[Bug]: The logs are not tracked when users change user workspace role and delete workspace access

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The logs are not tracked when users are removed/ leave workspace-level access
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/233565264-46052875-10bb-4d9b-8c1b-847bfba502e0.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/233565378-e60cffb3-78c9-4816-a7ca-1b10197ae3c0.png">

### Steps To Reproduce

1. Login to https://ee-1281.dp.appsmith.com/
2. share a app with user 1 as admin access
3. now go to members page
4. and change user 1 role to developer 
5. now go to audit log the First access will be added in logs
6. when user role is changed from members page that log is not captured for workspace role changes

### Environment

Deploy Preview

### Version

deploy preview

**Comment by infinitetrooper** [comment]
Yep, this should be fixed. The user role updates in members page should also show up in Audit Logs.
