### ISSUE TITLE
[Task] Check if widget is selected while handling keyboard shortcuts

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2261]
Check if a widget is selected while handling keyboard shortcuts (for example cut, copy, paste commands)

**Comment by mohanarpit** [comment]
Is this an implementation detail of #1937?

**Comment by rishabhsaxena** [comment]
yeah part of the fix for #1937, the other part would be resetting the selected widget for one of the cases mentioned in the issue

**Comment by prapullac** [comment]
Reopening the issue as it is not working as expected.Here I was pressing "Delete" from the keyboard and observed and Copy of the widget. 
Attaching the video for the same 
https://www.loom.com/share/470ffbd66a4f4540826ff6145f08dc0e

**Comment by rishabhsaxena** [comment]
oh I made a typo here, thanks for catching this
