### ISSUE TITLE
[Feature]: Ability to disable queries

### ISSUE THREAD

**Issue by gurel** [appsmithorg/appsmith#22615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be a quite useful feature to be able to disable queries. The use case we have is custom authorization on what the user is able to see. We make an internal call to check whether the user should be able to see the data, and if not we try to disable the query. In order to achieve this every time we have to wrap the query in a JSObject to add a permission check.

I imagine on the settings portion of the query we could add a disabled rule.

### Why should this be worked on?

Simplifies query execution configuration.

**Comment by Nikhil-Nandagopal** [comment]
This is now possible via our RBAC and also via reusable packages
