### ISSUE TITLE
[Bug]: Airgapped - Able to access welcome tour through a link in Get Started module

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run through the Get Started module, and follow the step by step guide, at the end of the guide there is a link to have user take the welcome tour if he is not sure where to start. Once this is clicked, the user is taken through the complete Welcome Tour flow. 

### Steps To Reproduce

1. Pull the image with the command docker pull appsmith/appsmith-airgap:release
2. Switch off internet and execute the docker run command
3. Now setup the instance and enter the license key
4. Once inside the application, on the top left, you will find a Get Started section. Click on it. 
5. You will see a few steps that you need to perform
6. At the end of it, you will see a link "Not sure where to start? Take the welcome tour" 
7. On clicking it, the welcome tour and creation of customer support dashboard comes up. 
<img width="806" alt="Screenshot 2023-04-21 at 7 04 06 PM" src="https://user-images.githubusercontent.com/101863839/233652188-b802e53c-fed5-4af3-a37d-06b85d8dc812.png">

### Environment

Release

### Version

Self Hosted

**Comment by infinitetrooper** [comment]
Yep, we gotta hide this too. Just hide that whole row @berzerkeer.

**Comment by infinitetrooper** [comment]
The one at the bottom @berzerkeer - "Not sure where to start....."
