### ISSUE TITLE
[Bug]: Appsmith auto-updates not cleaning up old images after update

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#22620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The old images of Appsmith are not getting deleted when auto-updating the image.

### Steps To Reproduce

1. Launch Appsmith container with auto-update enabled
2. Wait for updated to be pushed
3. cmd: docker images
4. Observe the old images that have not been deleted

### Environment

Production

### Version

1.9.16

**Comment by sharat87** [comment]
@sum35h, were we able to reproduce this? If I recall right, we couldn't reproduce this, right?
