### ISSUE TITLE
feat: WDS `bdAccent`

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#22630]
1. Cutoff at Lc 15 may be too low even though it's passable according to APCA — increase cutoff to 20.
2. Fallback is exceptionally harsh (we immediately reach for lightest/darkest tones) — revise.

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/22630?planning-poker) with Zenhub @ichik @jsartisan @KelvinOm
