### ISSUE TITLE
[Feature]: Workspace option to "add new users to this workspace automatically" during user onboarding

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#22644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, users have to be added to each workspace separately, and manually. 

This request is for a new option in the Workspace settings page to "Add new users to this workspace automatically". When a new user signs up on a self-hosted instance, they should be automatically added to any/all workspaces with this toggle turned on. 

### Why should this be worked on?

This was a recent request from an enterprise customer. They have lots of workspaces and they said it's a lot of work to add a new user to all the right workspaces when onboarding an employee. They suggested we should have an option to auto-add users to certain workspaces.

**Comment by Nikhil-Nandagopal** [comment]
This is now possible with RBAC by editing the default roles
