### ISSUE TITLE
[Task]:  Optimisations of opened connection by Hikari CP 

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#22659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks
[QA] https://app.zenhub.com/workspaces/data-platform-pod-6322a78c9f446835b89a3f82/issues/zh/8

## Descriptions

While executing the queries, the hikari CP driver opens connections which are more than expected.
This task is to explore the Plugins with Hikari Driver and find the problem, and possibly fix it as well

The following are the possible plugins to look into:
MSSql
Redshift
SnowFlake
Oracle

**Comment by sondermanish** [comment]
Adding the observability metrics, so that we have a way forward for the next week's implementation.

**Comment by AnandShahs123** [comment]
@sondermanish As discussed, tested this for Snowflake.. No unwanted extra connection found.
