### ISSUE TITLE
[Bug]: Dsl not loading as a result tests failing [Only Seen in Automation]

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#22651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dsl fails to load within the time and tests are failing.

### Steps To Reproduce

Steps:
1.In automation test scripts with make sure "Auto Layout" is enabled.
2.Then upload Dsl and execute tests.

Expected:
Dsl should be loaded successfully

Actual:
Dsl load is failing intermittently and tests

refer the below dashboard links:
https://cloud.cypress.io/projects/eyxvp8/runs/32869/test-results/1e1d8645-2d8d-48ac-837f-c0ce64100d4b/screenshots

### Environment

Release

### Version

Appsmith v1.9.17-SNAPSHOT

**Comment by Aishwarya-U-R** [comment]
To convert to TS helper method to load DSL.
