### ISSUE TITLE
[Feature] Add ability to create document in Firestore with autogenerated key 

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#2267]
## Summary

In the Firestore plugin, as a user, I should be able to create a document with an auto-generated key.

## Motivation

Firestore has the ability to generate keys for newly created documents. The Firestore plugin should be able to leverage that feature to create documents.

**Comment by sharat87** [comment]
The current implementation of the Firestore plugin doesn't support the collection-level operation of *adding* a document. This is the operation that makes Firestore generate a new ID for the document. I'll take this next up and add support for this operation.
