### ISSUE TITLE
[Bug]: api/v1/applications is throwing 401 intermittently

### ISSUE THREAD

**Issue by Vijetha-Kaja** [appsmithorg/appsmith#22672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Sub-tasks
- [ ] #23511

### Description

This issue is observed in CI, where on navigating to a page `api/v1/applications` is throwing 401 error. As a result page is throwing unauthorised error.

![cypress-screenshot (21)](https://user-images.githubusercontent.com/119562824/233984539-de1b9c2c-0d77-44f5-9c87-61065a53882f.png)

### Steps To Reproduce

1. Login to appsmith through api
2. Visit any page in appsmith

### Environment

Release

### Issue video log

https://user-images.githubusercontent.com/119562824/233984612-5cc19dbf-0ea9-4c60-94aa-1e6b05497920.mp4
https://user-images.githubusercontent.com/119562824/233987073-83a00f06-29a6-43a4-b96e-6c0c49dfe31a.mp4

### Version

Release

**Comment by Vijetha-Kaja** [comment]
Recent runs with above failure [run1](https://cloud.cypress.io/projects/eyxvp8/runs/32920/test-results/cf74a194-c1c0-4587-ac08-95402ae4578c) [run2](https://cloud.cypress.io/projects/eyxvp8/runs/32899/test-results/a7e1d5d9-4f2b-4e02-bd28-ee1ba82b7d5e)

**Comment by Vijetha-Kaja** [comment]
Recent runs with above failure [run1](https://cloud.cypress.io/projects/eyxvp8/runs/32920/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22Regression_TestSuite%2FClientSideTests%2FIDE%2FCanvas_Context_Property_Pane_spec.js%22%2C%22value%22%3A%22%5B%5C%22b2b8bc5b-8423-494c-b9e6-4b0377070b8e%5C%22%5D%22%7D%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D) , [run2](https://cloud.cypress.io/projects/eyxvp8/runs/32941/test-results/309e9d19-01fd-4acb-b754-42cc106ed946)

**Comment by akash-codemonk** [comment]
The only way to replicate this scenario is when the `SESSION` cookie isn't present, so this is the most likely scenario.
