### ISSUE TITLE
[Feature]: Get all user details for App/AppSmith instance

### ISSUE THREAD

**Issue by johanloonesKP** [appsmithorg/appsmith#22689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Retrieving all user details programmatically via API or via variable

### Why should this be worked on?

Problem: User details need to be entered in the datasource manually.
Use case: For instance, in an app for tracking leaves we need to set user details like name, email, respective leaves, etc manually after a user has registered, which can be done at a click of a button provided most of the details are already present

**Comment by Nikhil-Nandagopal** [comment]
You can access user information as {{appsmith.user.email}} in any app

**Comment by johanloonesKP** [comment]
Hi Nikhil,

The issue was related to retrieving the user details for any user by the
app creator when the said user cannot edit the data source and the app
creator can fetch the details and populate the data source.

Regards,
Johan

**Comment by johanloonesKP** [comment]
So if the app is published by org admin only then all users data is
available is it?

**Comment by Nikhil-Nandagopal** [comment]
@rishabhrathod01 not a priority right now because this requires a backend call and it can technically be done today by using the appsmith unofficial API
