### ISSUE TITLE
[Bug]: [Column Space] Consider container border width in column space calculation

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#22680]
Issue:

Increasing border width of containers doesn't affect the sizes of child widgets, leading widgets to get cut off at the edges. Highlights along the edges are also not visible.

Fix:

Consider container border width for column space calculation. Correct column space will fix both the visible issues.

https://user-images.githubusercontent.com/5424788/234034426-93d55f97-905b-4534-bdec-78d4d55fee94.mov

**Comment by prsidhu** [comment]
PR: https://github.com/appsmithorg/appsmith/pull/22738

**Comment by kamakshibhat-appsmith** [comment]
@prsidhu Can we merge latest release and then verify this?
