### ISSUE TITLE
Refine `fgAccent` (light mode)

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#22699]
Quickly turns nearly black — good for readability, but perhaps a bit more chroma can be preserved for non-achromatic seeds.

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/22699?planning-poker) with Zenhub @ichik @jsartisan @KelvinOm
