### ISSUE TITLE
[Bug]the conversion algorithm starts failing when you switch branches in GIT connected apps. You need to manually refresh the page for the algorithm to work

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22698]
https://www.loom.com/share/e99f1e2ded4b491bb879c62cc1872a83

**Comment by rahulramesha** [comment]
@nayan-rafiq need your help on this one, The save layout call is returning 500, with just internal server error. Don't have much information in the error to debug this.
