### ISSUE TITLE
[Bug]: Store bindings on text widgets are displayed as plain text after clearing store and re-doing store action

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Store value bindings show up as plain text on text widget after clearing store and re-doing store action

### Steps To Reproduce

1. Go to any app and add a store value and clear store code as seen in the video and app attached and observe the behaviour
2. Make a binding on text widget as seen in the screenshot
3. Refresh or load the app and observe the bindings appears as text

![image](https://user-images.githubusercontent.com/79509062/234230321-965c9ab8-1ac6-4d18-a85e-feb044c73d43.png)
https://www.loom.com/share/29582c0c590548c6851f77520f72f02d

### Public Sample App

https://release-ee-https.appsmith.com/app/fe/page-1-6401ef3830ce2a073e2f61f3/edit/widgets/tvwn4pxtjo

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Unable to reproduce this @ramsaptami, i created a new account in release-ee and tried

**Comment by ramsaptami** [comment]
Hey @dilippitchika I'm adding more details around reproduction. It's related to storeValue imo, seeing this on [prod](https://app.appsmith.com/app/automation-test-cases-og/page-1-6437f39199d4922aba72d0c3/edit/widgets/96dlxdqrnf) & [release](https://release-ee-https.appsmith.com/app/fe/page-1-6401ef3830ce2a073e2f61f3/edit/widgets/0hmn8m90ei)

I've added your appsmith ID to both the workspaces, let me know if you can't access these apps or are unable to repro this further
https://www.loom.com/share/29582c0c590548c6851f77520f72f02d

**Comment by dilippitchika** [comment]
@ramsaptami still not able to reproduce in prod or release-ee, is there some more nuance? - https://www.loom.com/share/93c2314734b84c488f11559465b36e93
