### ISSUE TITLE
[Bug]Table widget and  input widget binding not working in a specific use-case

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#2273]
Steps:
1.Bind an input widget with a table widget with Selectedrow. id
2.Now in the table widget if we sort the id, even though the row id value changed the value is not reflecting in the input widget.
3.In table widget we have set the default row to be selected.

<img width="973" alt="Screenshot 2020-12-18 at 3 35 49 PM" src="https://user-images.githubusercontent.com/67676905/102601846-b7acbf80-4146-11eb-8cc6-c5893da7a4d6.png">

**Comment by prapullac** [comment]
Reopening the issue as it is not working as expected.
![Screenshot 2021-02-18 at 1 05 47 PM](https://user-images.githubusercontent.com/71753653/108321380-1267a380-71ea-11eb-9ef0-94fb30cc9456.png)

**Comment by riodeuno** [comment]
Closed as verified
