### ISSUE TITLE
Chore: Improve Layouting of Group components

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#22748]
Currently, the list of options in all group widgets ( checkbox group, radio group, switch group ) is messed up. We need a better way to align them by using a grid with multi-column layout and flex with a single column

- [ ] Update Layout for groups
- [ ] Add chromatic tests for switch group, radio group and checkbox group for all UI related props

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/22748?planning-poker) with Zenhub @KelvinOm @ichik @jsartisan

**Comment by KelvinOm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/22748?planning-poker) with Zenhub @ichik
