### ISSUE TITLE
Widget Development API Document update

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#22771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Add descriptions for the new `getPropertyPaneContentConfig` and `getPropertyPaneStyleConfig` APIs. ( We only have documentation for the `getPropertyPaneConfig` )

- Add descriptions for the `isDeprecated` property.

Documentation Link: https://github.com/appsmithorg/appsmith/blob/release/contributions/AppsmithWidgetDevelopmentGuide.md

**Comment by Manish254252** [comment]
Hi anyone working on this issue ?

**Comment by iamenrique** [comment]
Could you also describe the following properties? I'm not sure how to rely on those when writing blueprints with Canvas and Containers.

- `responsiveBehavior`
- `positioning`
- `useAutoLayout`

**Comment by skmanoj322** [comment]
@riodeuno is there some one working on this problem?

**Comment by CodeSinghh** [comment]
if the issue is not resolve yet can you please assign me

**Comment by riodeuno** [comment]
@CodeSinghh Thanks for volunteering to update the doc. I've assigned this to you.

@iamenrique These new configurations are subject to change, as we've used these for an upcoming feature, and we're not certain if the API will remain the same. So, I would refrain from using these configurations for the time being, until we update the docs with references and descriptions to these configurations.

**Comment by skmanoj322** [comment]
@riodeuno FIFO?

**Comment by skmanoj322** [comment]
No worries

**Comment by AnnaHariprasad5123** [comment]
HI @riodeuno, I have raised the PR by updating the widget development doc as you required. Please check it once.
PR link : https://github.com/appsmithorg/appsmith/pull/33612
