### ISSUE TITLE
[Bug]: App settings closes when the user tries to resize the canvas in auto-layout

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#22772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user is trying to resize the canvas, the app settings should remain open. This will have an effect on features like navigation as shown in the loom video

### Steps To Reproduce

1. Switch app to autolayout canvas
2. Open app settings
3. Try to resize the canvas, and observe

### Environment

Production

### Issue video log

https://www.loom.com/share/437f9f5a20ca41f78895fab5fc49274a

### Version

Appsmith v1.9.17-SNAPSHOT

**Comment by rohan-arthur** [comment]
this interaction is deprecated --> closing this issue
