### ISSUE TITLE
[Bug] Incorrect format of date is displayed to user 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2278]
Steps to reproduce:
1) Add a table widgets 
2) Navigate to action items
3) Select data type as Time
4) Observe the date output last row 

![Screenshot 2020-12-18 at 4 28 55 PM](https://user-images.githubusercontent.com/71753653/102608350-c055c380-414f-11eb-9d3d-47b48b6c67af.png)

**Comment by riodeuno** [comment]
This is an actual format option supported by momentjs. Closing as non-issue.
