### ISSUE TITLE
[Bug]: Page reordering on selection 

### ISSUE THREAD

**Issue by GadgetCheck** [appsmithorg/appsmith#22786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Simple and quick fix for now. 

On the selection of a page, the tab moves and it's disorienting for a user especially because the order shuffles. 
Let's keep it simple and elegant, on click let's not reorder the list keep the position locked. 

Remove the "Tick" and keep it simple, on selection the row is highlighted.

Discussion: https://theappsmith.slack.com/archives/CRVRBGU1K/p1680711511055479

### Steps To Reproduce

Video attached. 

### Environment

Production

### Issue video log

https://theappsmith.slack.com/files/U0335E0PK0C/F051JCGDVV5/kapture_2023-04-05_at_21.39.42.mp4

### Version

Appsmith v1.9.17-SNAPSHOT

**Comment by ginilpg** [comment]
This has been resolved
