### ISSUE TITLE
[Bug]: User is unable to scroll iFrame in preview mode

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#22799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is an issue raised by a real user. Attaching video for reference.

Sample App : https://cdn.discordapp.com/attachments/1098996907625431120/1098996908028088350/iframe_app.json
Video : https://cdn.discordapp.com/attachments/1098996907625431120/1098996908426530816/iframe_video.mp4

### Steps To Reproduce

Repro step:

1. Add an iFrame.
2. Make sure scrolling is working in Canvas mode.
3. Switch to preview mode.
4. Scrolling an iframe doesn't work.

Expected behavior : Scrolling an iFrame should work

### Environment

Production

### Version

Cloud

**Comment by chandannkumar** [comment]
Tested this and LGTM
