### ISSUE TITLE
[Bug]: Toggling visibility of widgets in List bricks the browser

### ISSUE THREAD

**Issue by ItsiW** [appsmithorg/appsmith#22794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Within the List widget, if I want to control visibility of one widget in the item with another widget in the item, my browser tab crashes. 

This only happens when launching the app, not in editing. This is in a local environment. When I open a new tab and open localhost, things work fine again (until I interact with these widgets again).

Replicated in Brave, Chrome, Firefox

### Steps To Reproduce

1. Create new app
2. Create a List
3. Create Radio Button and Input widgets and put them in the list items
4. Set visibility of Input widget to {{currentView.RadioGroup1.selectedOptionValue=='Y'}}
5. Deploy
6. Change one of the radio inputs
7. Observe browser freezing

### Environment

Deploy Preview

### Version

Self Hosted - Appsmith Community v1.9.12

**Comment by dilippitchika** [comment]
@ItsiW I wasn't able to reproduce it. Can you try using our latest version and let me know if it's still happening?
