### ISSUE TITLE
[Feature]: Custom App Layout - Easy way to split the UI in different sections.

### ISSUE THREAD

**Issue by iamenrique** [appsmithorg/appsmith#22796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Offer a feature to split the whole page UI in 2 or 3 sections, for example 50%-50%, or 25%-50%-25% columns.

The selected "layout" can be variable and depend on a binding to switch during runtime, instead of having sizing fixed.

Extra: Special layouts could be created to include an overlay section.

### Why should this be worked on?

I need to build an app with the following layouts and allow users to switch across available options.
![image](https://user-images.githubusercontent.com/7999776/235013478-e45a34aa-ed28-4d1e-8bce-f2fedf47d553.png)

**Comment by Nikhil-Nandagopal** [comment]
We're working on this as part of #4630
