### ISSUE TITLE
[Bug]: Debugger opens up during on-boarding causing important information to be hidden

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#22810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Debugger opens up in a blank state during on-boarding and stays open blocking important information a new user is trying to read. This shouldn't be the case, debugger should only open up when user chooses to view errors/logs.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/235070419-048ea73c-cec8-4a97-9287-f739d86eb127.png)

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
This happens on all apps, not just onboarding @sribalajig Can you please work on this

**Comment by satbir121** [comment]
@sribalajig How are we doing this? It is showing up in FE Coders inside Zenhub.
