### ISSUE TITLE
WDS color: `bdNeutralHover` (both modes)

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#22823]
Perceptually not visible at all currently in light mode, barely visible in dark mode.

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/22823?planning-poker) with Zenhub @ichik @jsartisan @KelvinOm
