### ISSUE TITLE
[Bug]: When importing the app into the Git-connected app on a specific branch, breaks the application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When importing the app into the Git-connected app on a specific branch, the app may break.
https://www.loom.com/share/74da40ad25984ab599a8bf73c1dc03e8

### Steps To Reproduce

1. go to https://appsmith-huxvaxjvc-get-appsmith.vercel.app/
2. open any git connect app
3. checkout from master to new branch
4. now import the app 
5. the imported app doesnt displayed and checkout to master break the application

### Environment

Deploy Preview

### Version

deploy preview

**Comment by abhvsn** [comment]
We are going ahead with disabling update app via JSON import for git connected application.

**Comment by infinitetrooper** [comment]
@berzerkeer - Please disable the import button for Git-connected apps with the below message.

"This feature is not supported for apps connected to Git. Please use Git Pull to update and sync your app."

**Comment by RakshaKShetty** [comment]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/45958978/236472562-69c27b9a-1b1c-4219-a235-071d210707ab.png">
