### ISSUE TITLE
[Bug]Widget URL navigation not working in auto layout

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22838]
Considering the selected widget is below the fold, on navigating back to the page(thru page refresh/page switching etc)the scroll to selected widget is failing
https://www.loom.com/share/fbc6d38dc72144249d97185871ddf2a2 

Dont use containers for testing (container has some issues with scroll)

**Comment by ramsaptami** [comment]
this has been fixed on Anvil layout
