### ISSUE TITLE
[Bug]: UUIDjs library throwing error

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#22830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Internal discussion ](https://theappsmith.slack.com/archives/C0341RERY4R/p1681763435840449)

### Steps To Reproduce

[Internal discussion ](https://theappsmith.slack.com/archives/C0341RERY4R/p1681763435840449)

### Environment

Production

### Version

Cloud

**Comment by rishabhrathod01** [comment]
This was a rare occurrance and wasn't faced again by any user for a year. Closing this as we don't have enough information to work on this.
