### ISSUE TITLE
Download app or page as a file?

### ISSUE THREAD

**Issue by shubhamsaxena7** [appsmithorg/appsmith#22853]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

<img width="707" alt="Screenshot 2023-04-30 at 8 33 42 PM" src="https://user-images.githubusercontent.com/75069701/235360265-3edcae01-b3fa-4d51-8caf-e2a9afabec1f.png">

Can I download the appsmith app or page as a file? Couldn't find it on the page. Also couldn't find it in the documentation. 

### Why should this be worked on?

It's not a feature request per se, just an observation to the naked eye. Please link me to the documentation if it exists

**Comment by Nikhil-Nandagopal** [comment]
yes you can from the settings menu at the top left
