### ISSUE TITLE
[Feature] Version control

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2285]
## Summary

Version control to return to a previous state.

## Motivation

Developers on twitter talking about how lack of version control turns them off. https://mobile.twitter.com/beatnikpicnic/status/1339635840214061057 
![Screenshot_20201219-035318](https://user-images.githubusercontent.com/30255708/102666857-f32ea480-41ad-11eb-8db7-2c7d5af68401.jpg)

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by mikefrancis** [comment]
Looking at the product roadmap, I think this can be closed as it's duplicated by this issue? 

https://github.com/appsmithorg/appsmith/issues/3199
