### ISSUE TITLE
[Feature]:  For S3 DS, On expanding the tables from the schema, the structure is not showing up.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I connect to S3 DS, and create a query, on the left entity explorer, on expanding the DS, and the bucket, the structure does not show up

### Steps To Reproduce

1. Connect to S3 DS
2. Create a new query
3. On the left entity explorer, on expanding the Redis DS, the DB schema is displayed.
4. Expand one of the buckets, nothing comes up below.

<img width="263" alt="Screenshot 2023-05-01 at 5 50 54 PM" src="https://user-images.githubusercontent.com/101863839/235466296-db5bbe95-91bc-44e1-b032-a5cca413d648.png">

### Environment

Release

### Version

Cloud

**Comment by sumitsum** [comment]
Just a clarification, the S3 integration was implemented this way, hence it is not a bug.
