### ISSUE TITLE
[Task]: Stop tracking the BINDING_SUCCESS event 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#22893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Now that we have the new `ENTITY_BINDING_SUCCESS` event firing correctly, let's stop tracking the `BINDING_SUCCESS` event on Mixpanel

**Comment by harshmange44** [comment]
@bharath31 @Druthi Hey, would like to try fixing this if possible
