### ISSUE TITLE
[Bug]: Autocomplete shows within strings in some cases

### ISSUE THREAD

**Issue by Druthi** [appsmithorg/appsmith#22894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/20187542/235594229-1007262e-9339-4669-ab94-91a4f9b2648a.png">

### Steps To Reproduce

1. Insert an empty string in a binding
2. Then go in between the string and type anything

### Environment

Production

### Version

Cloud v1.9.18

**Comment by ohansFavour** [comment]
### Expected behaviour

Autocompletion hints should only show up for string literals in a MemberExpression.

#### Example
JsObject1.myFun1["d"] => Show hint when the cursor is in front of "d"
JsObject1.myFun1"d" => Should not show hint

**Comment by rohan-arthur** [comment]
![Screenshot 2024-05-28 at 12 23 13](https://github.com/appsmithorg/appsmith/assets/94514895/bf78acb3-d45d-4617-b402-a7f7d5f53e32)
not reproducible anymore
