### ISSUE TITLE
[Bug]: Import application modal does not persist when an application is imported

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#22896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I drag and drop a file in the Import application modal, the modal disappears.

PFB video:

https://user-images.githubusercontent.com/14138515/235601003-5bf84c1d-25b0-4788-8952-b717dd907e57.mov

### Steps To Reproduce

1. Dnd a large JSON export of an app(attached below) into the import application modal.
2. Observe that the modal disappears
3. Click on the import button under the new app dropdown
4. Observe that the app is still loading.

JSON export:
[Untitled application 136 (1) (2).txt](https://github.com/appsmithorg/appsmith/files/11370552/Untitled.application.136.1.2.txt)

### Environment

Production

### Version

Cloud

**Comment by riteshkew** [comment]
Closing the issue as it is not reproducible in v1.20
