### ISSUE TITLE
[Bug][Table] Increasing the height of table in mobile viewport creates a blank space at bottom (with no cell borders)

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22907]
![Image](https://user-images.githubusercontent.com/113327629/235635732-36c5a8cb-1d9c-422b-a965-6fe2a0b6cfe1.png)

**Comment by aswathkk** [comment]
related to #2291

**Comment by Sripriya93** [comment]
No DP available. Moved to Inprogress.

**Comment by Sripriya93** [comment]
QA completed. Working fine, moving to done.
