### ISSUE TITLE
[Feature]: If a merge from ce to ee fails, the script can merge the last mergeable commit to ee.

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#22913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This will reduce the changes present in the merge conflict and also help to review the conflict later on if something gets broken.

If the script can automatically freeze the merges on ce/ee release, that would also help to reduce the unwanted changes in the merge conflict resolution.

`git bisect` could be helpful to find the last good commit.
https://stackoverflow.com/questions/4713088/how-to-use-git-bisect

### Why should this be worked on?

This will reduce human errors in conflict resolution/reduce CI time and improve developer productivity.

**Comment by sharat87** [comment]
This is done.
