### ISSUE TITLE
[Bug] the Table widgets pageSize property cannot be updated in mobile viewport

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22911]
https://www.loom.com/share/64a52913d2254122af468b2a5f58ff11

**Comment by aswathkk** [comment]
We need to take into account of mobileBottomRow property for the pageSize calculation within TableWidget

**Comment by andreevanatasha** [comment]
Duplicate of https://github.com/appsmithorg/appsmith/issues/22907
