### ISSUE TITLE
[Bug]: Text font gets changed on adding Rich text editor widget onto canvas

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#22937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding RTE widget onto canvas, we can observe that the text font of Preview, Share, Deploy and widget title gets bold automatically

### Steps To Reproduce

1. Drag & Drop a Rich Text Editor widget
2. Observe the Text font changed for Preview, Share, Deploy buttons

### Environment

Production

### Issue video log

https://www.loom.com/share/7e2cfc60666e4bd694d78f520ded4ec5

### Version

Cloud/ Production

**Comment by kamakshibhat-appsmith** [comment]
We can notice the entire app's font changes once dropping RTE . we can see font changes in Homepage aswell
