### ISSUE TITLE
[Bug]: Sentry exception in DatasourcesSagas.ts APPSMITH-5GQ

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#22947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/3791274468

### Steps To Reproduce

NA

### Environment

Production

### Version

ignore

**Comment by btsgh** [comment]
Since its a sentry issue, closing out as is as per discussion
