### ISSUE TITLE
[Bug]: Sentry exception in evaluatedQueryParameters APPSMITH-65B

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#22949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4080235268

### Steps To Reproduce

NA

### Environment

Production

### Version

ignore

**Comment by btsgh** [comment]
Since its a sentry issue, closing out as is as per discussion
