### ISSUE TITLE
[Bug]: Error when accessing GSheet API editor

### ISSUE THREAD

**Issue by tejasahluwalia** [appsmithorg/appsmith#22942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to open the editor for a Google Sheet API results in an error.

https://user-images.githubusercontent.com/39881648/235857023-ef3e0df7-4da7-48fa-9e8b-31562144c060.mov

### Steps To Reproduce

1. Try to create a new query or edit existing query of a Google Sheet datasource

### Environment

Production

### Version

Cloud

**Comment by GreenFlux** [comment]
@rohan-arthur @arunvjn could we please get an ETA on a fix for this? A user on Discord is asking.

**Comment by rohan-arthur** [comment]
@GreenFlux looks like any time now. Updates here: https://theappsmith.slack.com/archives/C02GAUE9P5H/p1683102772772769?thread_ts=1683102772.772769&cid=C02GAUE9P5H

**Comment by rohan-arthur** [comment]
this is resolved now
