### ISSUE TITLE
[Bug]: Sentry exception in ApiPaneSagas.ts APPSMITH-6AS

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#22945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4128183053

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by sumitsum** [comment]
Closing this as the error trace here is exactly same as in here: https://github.com/appsmithorg/appsmith/issues/22944
