### ISSUE TITLE
[Bug]: Sentry exception in PluginActionSaga.ts APPSMITH-5BW

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#22948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/3766512614

### Steps To Reproduce

NA

### Environment

Production

### Version

ignore

**Comment by sumitsum** [comment]
Could need help / change on the server side as well, but the investigation should start from the FE side.

**Comment by rohan-arthur** [comment]
less than 300 events, won't fix
