### ISSUE TITLE
[Bug]: Sentry exception from QueryEditorForm APPSMITH-5WA

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#22946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/3877084266

### Steps To Reproduce

NA

### Environment

Production

### Version

ignore

**Comment by btsgh** [comment]
Since its a sentry issue, closing out as is as per discussion
