### ISSUE TITLE
[Task]: Update Template filters

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#22959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Hide **Datasources** filter
- Rename **Function** to **Team**
- Update Human Resources (HR) to Human Resources

**Comment by rahulbarwal** [comment]
Hey @danciaclara / @jacquesikot  
I have made changes for the first two requests and are available at: https://ce-23361.dp.appsmith.com/

Regarding the third request:
> Update Human Resources (HR) to Human Resources

this comes from DB, to get this updated all you have to do is update the metadata in the respective tagged template. It'll appear correctly here.
