### ISSUE TITLE
[Bug]: Sentry exception in ApiPaneSagas APPSMITH-67C

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#22952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4098904996

### Steps To Reproduce

NA

### Environment

Production

### Version

ignore

**Comment by btsgh** [comment]
Since its a sentry issue, closing out as is as per discussion
