### ISSUE TITLE
[Bug]-[25]:'Editable' property in Table widget is not working when values are added as JS expression

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#22969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Table widget's column setting, editable property is not responding properly. Since on giving input as 'true' should show validation fields and hides when 'false'

### Steps To Reproduce

1. Drag & Drop a Table widget
2. Go to Column Configuration 
3. Enable js editor of 'Editable' property
4. Try adding 'true' or 'false' in editor
5. Observe that there is no response in opening/closing validation fields

### Environment

Production

### Issue video log

https://www.loom.com/share/8f311aaebd544b27bd9ef7a7aebbe752

### Version

Cloud/Production

**Comment by somangshu** [comment]
Assuming the affected user are the once who try to use a JS expression in this prop, the impact is

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach  | 50 |
| Effort (months)  | 1 |

**Comment by somangshu** [comment]
@keyurparalkar can you check this out once, maybe its not really a problem on table widget and this is how eval works. 
This is not a priority issue however

**Comment by dilippitchika** [comment]
I don't remember why this happens but you have to mark the column as editable in the table level, then setting JS will show the properties. 

@sbalaji1192 can you confirm and let me know?
