### ISSUE TITLE
[Bug]: Code editor loses focus when ESC is pressed

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#22960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The JS code editor loses focus when ESC is pressed. This issue has been seen in Chrome/Firefox.

Cause - This behaviour stems from the fact that the "type / for commands" in editors found in the JS pane has to be closed when escape is pressed. Since no such menus show up on the editor for JS objects, the focus is lost without menu closing

### Steps To Reproduce

1. Go to the JS Editor
2. Type something - make sure the autocomplete hinter is not showing
3. Press escape
4. Notice that the focus is lost and one needs to click on editor again to regain focus,

### Environment

Production

### Version

1.6.6

**Comment by ramsaptami** [comment]
lgtm
cc: @rimildeyjsr
