### ISSUE TITLE
[Bug]: Oracle Database icon is broken in the airgap version

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#22980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The icon for the oracle database seems to be broken in the airgapped version.
<img width="300" alt="Screenshot 2023-05-03 at 6 38 13 PM" src="https://user-images.githubusercontent.com/39921438/236130755-6d3360de-fda0-44e6-a773-16c25fd5d905.png">

### Steps To Reproduce

1. In an airgapped instance got to the Datasources page.
2. Check for the Oracle integration

### Environment

Release

### Version

Self Hosted

**Comment by btsgh** [comment]
Tested and found to be fixed.
