### ISSUE TITLE
[Bug] LHS looks loading on the welcome page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2298]
Steps to reproduce:
1) Create a new application
2) Welcome Page 
and observe the RHS 

Observation 
It is observed that the LHS (Widgets Pane) looks like it is loading 

Expectation:
We can completely remove the RHS pane when we are displaying the Welcome message.This increases the look and feel of the page 

![Screenshot 2020-12-21 at 3 05 52 PM](https://user-images.githubusercontent.com/71753653/102767328-62bab480-43a5-11eb-9ff6-239ac7be15c0.png)

**Comment by Nikhil-Nandagopal** [comment]
Won't be valid with the new onboarding
