### ISSUE TITLE
[Bug]: AirGappedinstance - Image widget throwing error on binding with camera imageblobUrl 

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#22985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On binding camera widget with image widget using {{Camera1.imageBlobURL}}, it show show the picture clicked on camera instead throwing an error

Note: This issue happens only in localhost

### Steps To Reproduce

1. Drag & Drop Camera widget
2. Drag & Drop Image widget
3. Bind image widget with `{{Camera1.imageBlobURL}}`
4. Click a photo on camera and save it
5. Observe there is no image shown on Image widget and throws error

### Environment

Production

### Issue video log

https://www.loom.com/share/34126bcf40794beebf0599f8257fc8ed

### Version

localhost

**Comment by somangshu** [comment]
@berzerkeer is this a valid issue, can you check the same on a cloud environment. 

cc @dhruvikn please help Sangeet if required.

**Comment by berzerkeer** [comment]
Attaching the slack thread here : https://theappsmith.slack.com/archives/C02K2MZERSL/p1681798986314589?thread_ts=1681715688.955619&cid=C02K2MZERSL

We decided to not solve for it at that time, but since it affects camera widget, I will raise a PR for this.

**Comment by dhruvikn** [comment]
Since it's only happening on localhost, removing the high-priority tag. Had a chat with @berzerkeer, and we will push a fix soon.

cc: @somangshu
