### ISSUE TITLE
[Bug] Getting infinite evaluations on the jarvis app

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2299]
## Description

The jarvis app re runs js evaluations in a repeated loop

### Steps to reproduce the behaviour:
1. Open the jarvis app
2. Navigate to the Github Projects Page
3. Click on the NUX project
4. Observe the js console

**Comment by Nikhil-Nandagopal** [comment]
On inspection this looks to be related to the store getting accumulated data
Also on avg we are evaluating 3 times for every API call

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal This seems to be working as expected can you check again. We should not look at number of evals because this will depend on how you have configured the app data workflow. We should rather optimise for the time each eval/render takes to make this performant
