### ISSUE TITLE
[Bug]: MsSQL: connection string is rejected when trying to connect to Azure SQL server instance. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#22998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error: `Driver.microsoft.sqlserver.jdbc.SQLServerDriver claims to not accept jdbcUrl`
Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1683087333331029 

### Steps To Reproduce

https://theappsmith.slack.com/archives/C0341RERY4R/p1683087333331029

### Environment

Production

### Version

self hosted, cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9w2oc)

**Comment by abhishekS14** [comment]
Hi, is there any way for me to check the steps the reproduce this? The Slack channel link doesn't have access to non-appsmith people,

**Comment by sumitsum** [comment]
Hi @abhishekS14 , this issue was reported for connecting to MsSQL server setup on Azure cloud. You may try to spin up a MsSQL server on Azure cloud and try to connect to it to check if you are able to reproduce the issue.

**Comment by sumitsum** [comment]
Could not reproduce it on my local setup, waiting to get an account on cloud (credit card details required) before we can test on cloud.

**Comment by mlcsyd** [comment]
Hello there, 

I am also experiencing this bug. Happy to share whatever is needed privately. 

I can reproduce the error when using a MSSQL Server 2019 instance. 

Sincerely,
MLC

**Comment by sumitsum** [comment]
Hi @mlcsyd can you please share your setup details: 
(1) MsSQL version
(2) Is MsSQL hosted on Azure cloud ?
(3) Is this a named instance ?

**Comment by mlcsyd** [comment]
> Hi @mlcsyd can you please share your setup details: (1) MsSQL version (2) Is MsSQL hosted on Azure cloud ? (3) Is this a named instance ?

Hello there, thank you for your response. 

1. MS SQL Server 2019 (15.0.4312.2) running on Windows Server 2019 Datacenter
2. No, it is hosted on an AWS VM. We can connect to Azure SQL Serverless Instances and do not receive this error. 
3. It is not a named instance.

**Comment by sumitsum** [comment]
Update: 
version `MS SQL Server 2019 (15.0.4312.2)` seems to be working fine when tested on Mac via an Ubuntu based docker image. 
```
docker pull mcr.microsoft.com/mssql/server:2019-CU20-ubuntu-20.04
docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=P@assw0rd' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-CU20-ubuntu-20.04
```
![Screenshot 2023-07-05 at 8 31 07 AM](https://github.com/appsmithorg/appsmith/assets/1757421/1765edbe-940f-4487-8be8-e507b95d4b4a)

**Comment by sumitsum** [comment]
Update: I am able to reproduce the error now. Fix is under review.
