### ISSUE TITLE
[Bug]: Dynamic table cell select options dont appear in new row select when table data is missing

### ISSUE THREAD

**Issue by darkqq** [appsmithorg/appsmith#23006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i dynamically add select options (from api response) in table cell they do not appear in new row select cell.
Works only with statically added options.

### Steps To Reproduce

1. Create table.
2. Change cell type to 'select'.
3. Set options to something like ```JSDropdownObject.getSelectOptions() (returns valid format options list)```
4. Click on '+ Add new row'.
5. There are no select options in dropdown.

### Environment

Production

### Version

Self Hosted 1.9.12

**Comment by shantanu1singh** [comment]
I have been facing the same issue

**Comment by esbenab** [comment]
[Select in table, new row.json.zip](https://github.com/appsmithorg/appsmith/files/11467768/Select.in.table.new.row.json.zip)
I have made a minimal example and exported it, it uses the mock databases users and recreates the description above.
Please  let me know if i can assist further.
/Esben

**Comment by shantanu1singh** [comment]
Just checking in - has this been triaged yet?

**Comment by dilippitchika** [comment]
Folks this is working for me @darkqq @shantanu1singh @esbenab 

The only scenario where it doesn't work is when the table data is empty. In that case, please turn off same options in new row and you can add the query again. 

Here's a video describing this - https://www.loom.com/share/d99bc59e98984823acb151fdb8e2b24c

I will update the bug to reflect the right information

**Comment by esbenab** [comment]
Thank you!
The workaround works! i was on a 4 month old version which lacked the options in the video got it all updated and everything is good now.

Thank you for your awesome work!

**Comment by jacquesikot** [comment]
This works
