### ISSUE TITLE
[Bug]: Debugger is open by default while trying to create a new data source on air-gapped instance

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#23002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Debugger is open by default while trying to create a new data source on air-gapped instance

on air-gapped:
![image](https://user-images.githubusercontent.com/79509062/236204283-835dbd33-4e1a-4483-98a8-655a804a4501.png)

on prod:
![image](https://user-images.githubusercontent.com/79509062/236204339-0030fce5-3743-4f03-8b68-c9066fddcdb5.png)

### Steps To Reproduce

.

### Environment

Release

### Version

Cloud

**Comment by infinitetrooper** [comment]
@ramsaptami  - is this limited to Airgapped (or) is this the behavior in community/business editions as well?

@rohan-arthur / @sribalajig  -  What is the expected experience here?

**Comment by abhvsn** [comment]
@infinitetrooper I don't think this has to do with airgapping but would wait for @ramsaptami to respond to get more context.

**Comment by ramsaptami** [comment]
I'm finding it hard to reproduce it on localhost this morning. Behaviour seems to be in line with other instances.

My suspicion is the tooltip for debugger icon was stuck on my local (seen in the screenshot) and that caused the debugger to open up previously. If that's the case then this issue should be in all instances. Will reopen this issue when I'm able to reproduce it consistently but closing it for now.
