### ISSUE TITLE
[Bug]: [Air gapped local host] Able to see "GETTING STARTED" steps whenever we open a new application

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#23007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we do docker setup with beta and open local host and click on new application we are able to see "GETTING STARTED" steps/ sequence which is expected only when we click on "BUILD MY OWN" option when we open application for the first time.

https://user-images.githubusercontent.com/104895602/236263149-713f546d-1685-4fd3-89a8-e226e41f625d.mp4

### Steps To Reproduce

1. Finish Docker setup and open local host
2. Open a new application 
3. Observe "GETTING STARTED" steps at the left top corner of editor
4. We are able to see the same for how many new application we may create

### Environment

Deploy Preview

### Version

Appsmith Airgapped v1.9.18-SNAPSHOT - Local host

**Comment by infinitetrooper** [comment]
Not an issue @Sripriya93  - We only removed the welcome tour, these are not part of that tour. These are just nudges to add data sources. Please reopen if there's a further issue.
