### ISSUE TITLE
[Bug]: [Air Gapped Instance] Unable to see any error messages in the file picker overlay

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#23001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to see any error messages in the file picker overlay

EXPECTED :
<img width="876" alt="Screenshot 2023-05-04 at 2 50 51 PM" src="https://user-images.githubusercontent.com/113327629/236202987-f2596d5b-214e-489d-8389-9af476210868.png">

<img width="684" alt="Screenshot 2023-05-04 at 2 51 30 PM" src="https://user-images.githubusercontent.com/113327629/236203105-0d39e776-dd70-4e9d-93c7-aad5f9fee7b1.png">

### Steps To Reproduce

1. Open File picker 
2. add any file that is not supported/ Add any file that is larger than the specified size

### Environment

Release

### Version

Self Hosted

**Comment by btsgh** [comment]
Tested and found to be fixed on airgapped image
