### ISSUE TITLE
[Bug]: [Air Gapped] handling of geolocation action errors in Airgapped instance

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#23009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

geolocation actions throws error in Airgapped instance

Since, geolocation won't work in airgapped instance, shall we incorporate other ways to handle it better(e.g remove it altogether/ Provide better error/info messages )

### Steps To Reproduce

https://user-images.githubusercontent.com/113327629/236276747-ac2db71a-0b2c-49f1-af90-1d7fa9be7a84.mov

### Environment

Release

### Version

Self hosted

**Comment by abhvsn** [comment]
Closing this as not needed.
