### ISSUE TITLE
[Task]: Integrations pod: Create pod history page

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#23020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

As the team keeps growing and adding new members, while the older members may or may not remain with the team, it is important the team retains reasoning around any key decision that it made in the past e.g. why it chose to go with complexity based estimation as opposed to the time based estimation, why it chose to keep 2 week sprints instead of 1 week, why it chose to include items of 0.2 complexity etc.

**Comment by rohan-arthur** [comment]
https://www.notion.so/appsmith/Pod-Practices-1d9f33150dab4f72ab35788a355aaa56
