### ISSUE TITLE
[Feature]:  Make the email whitelist for the workspace be able to commit to git

### ISSUE THREAD

**Issue by zixincheng** [appsmithorg/appsmith#23034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

On the shared button, whenever I add new members be able to view/edit the app, as it connects to git, it should show there is something to commit, so afterward if I import this project on a different machine or accidentally remove the image, we can easily recover the list that are able to view/edit the app instead of manually add back 1 by 1

### Why should this be worked on?

I have set up an app and hooked up with the git. Everything was good. I make the app private and add a couple of emails under the share button that can view the app for users. For the users who want to look at the app, they can use the emails that are already in the list and sign up, and then they are able to look at the app.

The problem I have is now I want to move the app into another server/or removed the image. I want to setup all again. The app itself is easy because I can just import from the github. But seems all the emails in the share button is not linked to github. I have to manually re-add the emails 1 by 1. 

Discord link: https://discord.com/channels/725602949748752515/1103819228383035462

**Comment by deepam-kapur** [comment]
can I fix this one? i want to contribute can you assign me some issues?

**Comment by zixincheng** [comment]
and also I wonder if possible that git can also track if the app public or private, basically all settings under share button

**Comment by Nikhil-Nandagopal** [comment]
Sorry this doesn't work for us because the users are added to the instance and the application is the only entity committed to git. Committing users to git is also a privacy violation
