### ISSUE TITLE
[Bug]: Design System - Modal - `right` attribute bound to incorrect prop

### ISSUE THREAD

**Issue by iamenrique** [appsmithorg/appsmith#23035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `ModalComponent` of the design system doesn't set the `right` attribute correctly. The component already supports the `right` attribute as a prop, but it's not bound to it (bound to `bottom` instead).

### Steps To Reproduce

1. Go to the file: [app/client/src/components/designSystems/appsmith/ModalComponent.tsx](https://github.com/appsmithorg/appsmith/blob/ed2f51e929607736db26029495eb2deccc00fb57/app/client/src/components/designSystems/appsmith/ModalComponent.tsx#L114)
2. Search for `props.right`. Then search for `props.bottom`. You'll notice the inconsistency.

### Environment

Release

### Version

Release

**Comment by iamenrique** [comment]
In fact also [the ModalWidget/component](https://github.com/appsmithorg/appsmith/blob/ed2f51e929607736db26029495eb2deccc00fb57/app/client/src/widgets/ModalWidget/component/index.tsx#L295) has the exact same issue.

**Comment by iSatVeerSingh** [comment]
@iamenrique Please take a look.
