### ISSUE TITLE
[Task]: Group and differentiate the git actions using a background color

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#23033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

![image](https://user-images.githubusercontent.com/8299030/236509418-b8bfe7cc-dd34-4fa7-854b-950c57cbdb00.png)

**Comment by deepam-kapur** [comment]
can I fix this one? i want to contribute can you assign me some issues?

**Comment by infinitetrooper** [comment]
We'll handle this with New IA redesign.
