### ISSUE TITLE
[Feature] New Date picker needs more default date options

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2304]
The date picker only has 5 different date formats, we need more that users in the US use.
<img width="324" alt="Screen Shot 2020-12-21 at 4 32 45 PM" src="https://user-images.githubusercontent.com/30255708/102770492-440aec80-43aa-11eb-9617-98c084c12dc6.png">

Tasks:
1. Identify and include more date options
2. Give examples of date options so that the user understands what the date type is like
3. Ensure date types in table widget, and date picker widget are consistent.

**Comment by riodeuno** [comment]
Note:
- The control for the format will change to the new control we have for the text size in table widget
- The main label will be today's formatted date. The sub-label will be the format string
