### ISSUE TITLE
[Bug]: pull appsmith-ce from docker-hub failed

### ISSUE THREAD

**Issue by wengad82** [appsmithorg/appsmith#23049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i pull appsmith-ce from docker-hub,but meet :manifest for docker.io/appsmith/appsmith-ce:v1.9.17 not found

# docker pull docker.io/appsmith/appsmith-ce:v1.9.17

Trying to pull repository docker.io/appsmith/appsmith-ce ... 
v1.9.17: Pulling from docker.io/appsmith/appsmith-ce
v1.9.17: Pulling from docker.io/appsmith/appsmith-ce

**manifest for docker.io/appsmith/appsmith-ce:v1.9.17 not found**

### Steps To Reproduce

# docker pull docker.io/appsmith/appsmith-ce:v1.9.17

Trying to pull repository docker.io/appsmith/appsmith-ce ... 
v1.9.17: Pulling from docker.io/appsmith/appsmith-ce
v1.9.17: Pulling from docker.io/appsmith/appsmith-ce

**manifest for docker.io/appsmith/appsmith-ce:v1.9.17 not found**

### Environment

Release

### Version

1.9.17

**Comment by sharat87** [comment]
@wengad82, I just tried the same pull command, and it seems to be working for me, this is quite strange. Do you see this error only with this image tag? Can you try `docker pull docker.io/appsmith/appsmith-ce:latest` or `docker pull docker.io/appsmith/appsmith-ce:v1.9.16` to see if those fail as well please?

Also, can you share the output of `docker info` so we have a better understanding of the environment and perhaps reproduce it better please?

Thanks!

**Comment by wengad82** [comment]
> 

[root@bg10 ~]# docker pull docker.io/appsmith/appsmith-ce:v1.9.16
Trying to pull repository docker.io/appsmith/appsmith-ce ... 
v1.9.16: Pulling from docker.io/appsmith/appsmith-ce
v1.9.16: Pulling from docker.io/appsmith/appsmith-ce
manifest for docker.io/appsmith/appsmith-ce:v1.9.16 not found
[root@bg10 ~]# docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 129
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 8891bca22c049cd2dcf13ba2438c0bac8d7f3343 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-957.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 16
Total Memory: 31.26 GiB
Name: bg10
ID: KNIB:DG2X:TMKZ:T4TK:FIZR:XHAN:KAPB:ZZWC:HDAV:YGOP:4QOE:SVF5
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 91.91.91.107:5000
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com
 http://hub-mirror.c.163.com
Live Restore Enabled: false
Registries: docker.io (secure)

**Comment by sharat87** [comment]
@wengad82, thanks for sharing. I see two points that, I don't know if are causing this, but do get highlighted.

1. Your Docker server version (`1.13.1`), is from 2017, which is _very_ old now. Is it possible to upgrade your Docker server version? If yes, can we do that and try please?
2. You have ~129 images on your system, but only 5 containers. So, I'm guessing a lot of those images aren't used and are taking up space on your system. You can do a `docker system prune` to clean up and claim your space back.

Let us know if the above suggestions help.

**Comment by wengad82** [comment]
thank you a lot sharat87 ,i upgrade docker-io from 1.13.1 to docker-ce v2.17.3,and then pull the v1.9.17,it can pull down well.
