### ISSUE TITLE
[Bug] Table data field shows an error when it's empty

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2306]
## Description
The table data field in the property pane shows an error even when there's nothing typed in the field.
<img width="630" alt="Screen Shot 2020-12-21 at 5 27 14 PM" src="https://user-images.githubusercontent.com/30255708/102774859-cba82980-43b1-11eb-9a49-f0e64632df49.png">

When the table data field is empty, the user should see the expected value but not an error.

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal Does this require designs? The table data field just shouldn't have an error when it's empty.

**Comment by Nikhil-Nandagopal** [comment]
Sorry designs not required, this got marked when I was mass marking issues

**Comment by riodeuno** [comment]
@areyabhishek @Nikhil-Nandagopal We're no longer seeing this issue, can you confirm if this issue still exists?

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working.
