### ISSUE TITLE
[Bug]: Arango DB query not parsed in the correct editor mode

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#23065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Arango DB query uses AQL (where `// `is used for comments instead of `--`), whereas the editor content is parsed in SQL mode.

### Steps To Reproduce

1. Create Arango DB query
2. In the query editor, press `CMD/CTRL + /`
3. Observe that the editor uses `--` instead of `//` for comments

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
fixed, now `cmd+/` adds comment as `//`
