### ISSUE TITLE
[Bug]: Remove broken image on Template details page

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#23069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is a broken image on every Template page under Widgets.

<img width="735" alt="Screenshot 2023-05-08 at 13 24 10" src="https://user-images.githubusercontent.com/32227135/236767957-28f05fa2-d220-4f06-b4d2-d033b3043c43.png">

### Steps To Reproduce

na

### Environment

Production

### Version

v1.9.18

**Comment by rahulbarwal** [comment]
I debugged this and found out that, this template is using `LIST_WIDGET `which is deprecated (hence icon and name are missing) and has been replaced with `LIST_WIDGET_V2`

The solution for this is:
We need to replace the older widget in the template by dragging and dropping a new list widget.
Update the template metadata to have `LIST_WIDGET_V2`

CC: @jacquesikot

**Comment by jacquesikot** [comment]
@rahulbarwal Thanks, i'd update all the old templates
