### ISSUE TITLE
[Bug]: App navigation Logo upload feature is not working on release

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#23068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Uploaded Logo isn't visible and broken image on app

### Steps To Reproduce

1. Open appsmith application
2. Go to App Settings> Navigation
3. Upload logo and observe that there is nothing visible after upload
4. Also, observe there is broken image instead of uploaded image on navigation bar

### Environment

Release

### Issue video log

https://www.loom.com/share/463db7ce548f47cdbe3aa9ecc8f570c3

### Version

Cloud/ Release

**Comment by NilanshBansal** [comment]
Duplicate: https://github.com/appsmithorg/appsmith/issues/23055

**Comment by dhruvikn** [comment]
Reopening the issue since it hasn't been verified by the FE and QA yet. cc: @NilanshBansal @somangshu @chandannkumar

**Comment by btsgh** [comment]
Also note, seeing this issue on all applications on Release. [Old and new applications, even without uploading a logo]

**Comment by chandannkumar** [comment]
@dhruvikn 
Still getting the broken image instead of default appsmith logo
![image.png](https://images.zenhubusercontent.com/61e65341d503e6aafa5df216/373bdbfd-0234-4eaa-a9c5-c26b3742dd8c)

cc: @NilanshBansal
