### ISSUE TITLE
[Feature]: Schedule auto-update of Appsmith image for ECS deployments

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#23076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Configure a way to schedule auto-update of the Appsmith image on ECS platform.

### Why should this be worked on?

Improve container management and manual efforts on the AWS ECS platform.

**Comment by cvsudheer108** [comment]
I have a suggestion along with Scheduled upgrade feature.
There is always a possibility that one of the upgrade might fail with one of the clients at some point in time. But for the customers, availability of the system close to 100% is crucial too. I have 2 suggestions in this regard:
1. Is it possible to provide an intelligent upgrade option, means after upgrade Appsmith can run some automatic sanity testing and it it fails, rollback to previous version. This is applicable for upgrade on any types of installation (EC2, ECS etc)
2. If the previous option is not possible sooner, then the provide an option to do upgrade manually (EC2 it is possible now, but not for ECS)
