### ISSUE TITLE
[Bug]: Event gets triggered even when option is not changed

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#23109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a TreeSelect widget, on configuring an event for the `onOptionChange` property we see that the said event gets triggered even when we do not change the selected option.

### Steps To Reproduce

1. D&D a TreeSelect widget.
2. Configure the `onOptionChange` event in such a way that we get to see an alert once we change the selected option.
3. Now open the dropdown of the widget & click on the already selected option.

**Expected:** The `onOptionChange` event should not get triggered as we did not change the option.
**Actual:** The event gets triggered.

### Environment

Production

### Issue video log

https://www.loom.com/share/48d0980974e646e9b08af14840755430

### Version

Cloud

**Comment by skmanoj322** [comment]
@shadabbuchh can i work on this???

**Comment by somangshu** [comment]
Greetings @skmanoj322, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. Please let me know here so that I can take it forward for a review

**Comment by Chandan9898Kumar** [comment]
@shadabbuchh  it is getting triggered because we are having Click event on the select. for the same Item if you don't want to get triggered then you have to use condition there. Hope it works for you.

**Comment by dilippitchika** [comment]
@Chandan9898Kumar will you be interested in picking this up?

**Comment by Chandan9898Kumar** [comment]
> dilippitchika

I love to work on this ticket,  please give me some time to set my repository.

**Comment by somangshu** [comment]
@Chandan9898Kumar thanks for showing the interest. Ill keep this issue assigned to you, please let us know here if you raise a PR fixing the issue.

**Comment by skmanoj322** [comment]
ya difficulties i faced is running docker and my pc didnt supported it

**Comment by Chandan9898Kumar** [comment]
> ya difficulties i faced is running docker and my pc didnt supported it

@skmanoj322  I understand that you are keen to work on this ticket, if you have resolved your docker issue then you can connect with @somangshu  before i start working on this ticket.

**Comment by harshitpandey0426** [comment]
The onOptionChange event should not get triggered for all these options right?
![image](https://github.com/appsmithorg/appsmith/assets/54776298/7d181907-0cd8-468d-8fd9-938e43a83e7b)

**Comment by Chandan9898Kumar** [comment]
@harshitpandey0426 go ahead if  @somangshu  agree with you, even currently I'm facing issues on setting my repo.

**Comment by dilippitchika** [comment]
@harshitpandey0426 yes that is correct, i am assigning this to you. Please feel free to raise a PR in the next 2 days. 

@Chandan9898Kumar @skmanoj322 please let us know what are the challenges faced by you in setting up the instance, we will try to support so that you can work on other issues.

**Comment by skmanoj322** [comment]
@dilippitchika running the docker in local machine is stressing my pc

**Comment by harshitpandey0426** [comment]
@dilippitchika @somangshu Raised PR please have a look

**Comment by dilippitchika** [comment]
Thanks let us check, @vsvamsi1 can you review this as well?

**Comment by harshitpandey0426** [comment]
### Recording for the test performed after change
>https://www.loom.com/share/008d87273b50441f9f56d8f5eef1ed73
