### ISSUE TITLE
[Bug]: [Bug]: Last 2 fields and both reset and submit button cannot be accessed in the Insert modal in generated page with data section.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#23124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the insert modal, both reset and submit button is not visible. Also, the last 2 fields in the form is also missing.

### Steps To Reproduce

1. Create a postgres datasource
2. Generate page with data
3. Click on + button to add a new record.

Observe - The last 2 fields are not visible along with the reset and submit button.

### Environment

Release

### Issue video log

https://www.loom.com/share/56f47798e4484044a2528633ee701be1

### Version

1.9.17

**Comment by kamakshibhat-appsmith** [comment]
This is not a bug, its intended behaviour as scroll contents property is off by default here. We can enable scroll contents by default in CRUD apps, but that can be taken separately.

**Comment by ankitezee** [comment]
Not able to insert any row into the datasource because of this. Any workaround ?

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/5b0ed57b-7285-4206-b2fe-1f135c98da17

not reproducible anymore
