### ISSUE TITLE
[Bug] onRowSelected getting triggered onRowAction

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2313]
## Description
The onRowSelected event is firing even when a row button is clicked

### Steps to reproduce the behaviour:
1. Drag a table
2. Add a row button
3. Display a message on row button clicked with showAlert('Row button Clicked')
4. Display a message on row selected with showAlert('Row selected')
5. Click a row button of the table
6. Both messages are displayed

**Comment by somangshu** [comment]
@riodeuno in this case, since we have decided that the action click will select the row as well, How do we handle onRowSelected not getting called? Should that be the case

**Comment by riodeuno** [comment]
Yes, this is for backwards compatibility. Any reason, why this shouldn't be the case?

**Comment by somangshu** [comment]
OP does not want the onRowSelected fired onRowAction, this is what I understand from the above

**Comment by riodeuno** [comment]
`onClick` of an action button, in many scenarios, our users have used `TableName.selectedRow` as a binding in the trigger
To do this correctly, we need to do the following
- Migrate all instances of `TableName.selectedRow` from the `onClick` trigger to `currentRow`.
- This way, `onClick` of a row button, we can do the following: 
   - Disable selection of the row
   - Disable onRowSelected trigger

**Comment by somangshu** [comment]
Decided from before:

> Clicking on a table row action should not un-select, however, it should select

The 2nd point in the above statement contradicts this point.
Also what exactly we mean by `Migrate all instances of TableName.selectedRow from the onClick trigger to currentRow`
