### ISSUE TITLE
[Bug]: Run appsmith on raspberry pi.

### ISSUE THREAD

**Issue by steveiliop56** [appsmithorg/appsmith#23150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to run the ``appsmith/appsmith-ce:latest`` docker image, but I noticed that MongoDB V5 does not support v8-A (the cortex-a72 CPU) and it has to be built manually. So how can I modify the Dockerfile to build the Appsmith image and compile MongoDB with a custom parameter. Last but not least I noticed that when trying to build the docker image, errors pop up about a cache key. Here are the logs just in case:

```
[+] Building 0.9s (14/27)
 => [internal] load build definition from Dockerfile                                                                            0.0s
 => => transferring dockerfile: 4.67kB                                                                                          0.0s
 => [internal] load .dockerignore                                                                                               0.1s
 => => transferring context: 2B                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                 0.5s
 => CANCELED [ 1/23] FROM docker.io/library/ubuntu:20.04@sha256:db8bf6f4fb351aa7a26e27ba2686cf35a6a409f65603e59d4c203e58387dc6  0.3s
 => => resolve docker.io/library/ubuntu:20.04@sha256:db8bf6f4fb351aa7a26e27ba2686cf35a6a409f65603e59d4c203e58387dc6b3           0.1s
 => => sha256:144e6a778925a0c11c4cd9fe5fce1172e620f215b0410bb43e7fa41bbcfe4522 424B / 424B                                      0.0s
 => => sha256:758cd4ebb2178eb0cd2ce78dea8ffad569f5bba415c4b33b694e891e7697e854 2.32kB / 2.32kB                                  0.0s
 => => sha256:8659cf1709ef03be2c0b2dc339b19432bff8a0753d2d7d53f47272f098f56ef4 0B / 25.97MB                                     0.2s
 => => sha256:db8bf6f4fb351aa7a26e27ba2686cf35a6a409f65603e59d4c203e58387dc6b3 1.13kB / 1.13kB                                  0.0s
 => [internal] load build context                                                                                               0.2s
 => => transferring context: 3.72kB                                                                                             0.2s
 => CACHED [ 2/23] WORKDIR /opt/appsmith                                                                                        0.0s
 => CACHED [ 3/23] RUN apt-get update   && apt-get upgrade --yes   && DEBIAN_FRONTEND=noninteractive apt-get install --no-inst  0.0s
 => CACHED [ 4/23] RUN curl --silent --show-error --location https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -  0.0s
 => CACHED [ 5/23] RUN rm -rf   /root/.cache   /root/.npm   /root/.pip   /usr/local/share/doc   /usr/share/doc   /usr/share/ma  0.0s
 => CACHED [ 6/23] RUN mkdir -p ./backend ./editor ./rts ./backend/plugins ./templates ./utils                                  0.0s
 => CACHED [ 7/23] COPY ./app/server/dist/server-*.jar backend/server.jar                                                       0.0s
 => CACHED [ 8/23] COPY ./app/server/dist/plugins/*.jar backend/plugins/                                                        0.0s
 => ERROR [ 9/23] COPY ./app/client/build editor/                                                                               0.0s
 => ERROR [10/23] COPY ./app/rts/package.json ./app/rts/dist rts/                                                               0.0s
------
 > [ 9/23] COPY ./app/client/build editor/:
------
------
 > [10/23] COPY ./app/rts/package.json ./app/rts/dist rts/:
------
Dockerfile:67
--------------------
  65 |
  66 |     # Add RTS - Application Layer
  67 | >>> COPY ./app/rts/package.json ./app/rts/dist rts/
  68 |
  69 |     # Nginx, MongoDB and PostgreSQL data config template - Configuration layer
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::n5mj8ksd5y42fkpal2rq8r4cq: "/app/rts/dist": not found
```

### Steps To Reproduce

1. Get a raspberry pi and flash Raspberry Pi OS 64bit.
2. Clone the repository with ```git clone --depth 1 https://github.com/appsmithorg/appsmith.git```
3. Try to build the image with this command ```docker build -t appsmith/appsmith-ce .```

### Environment

Release

### Version

V1.9.17

**Comment by sharat87** [comment]
Hey @steveiliop56, thanks for reaching out. Unfortunately, as you've realized as well, MongoDB v5 doesn't support running on Raspberry Pi. The best way to bypass this limitation, would be use an external MongoDB. You can get a free MongoDB cluster on MongoDB Atlas, that you can use with Appsmith running on your RPi. [Learn more](https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-mongodb-redis). This way, you don't have to build a custom Appsmith image either.

Regarding the error in your `docker build` command, you need to build `client` and `rts` as well, before running `docker build`. Those two folders also come with a `build.sh` scripts that you can use to build them. Once they are successful, the Docker image build should proceed.

Closing with external MongoDB as the recommended solution. Let us know if there's further problems there, happy to reopen.

**Comment by steveiliop56** [comment]
Hi @sharat87,

Could I use this docker image  https://hub.docker.com/r/arm64v8/mongo for the external db?

**Comment by sharat87** [comment]
@steveiliop56, unfortunately, we don't have experience running that image of MongoDB. That said, if it can be configured to run as a standard MongoDB replicaSet (even with just one node), then Appsmith should work fine. Note that it needs to be configured as a replicaSet. This configuration is done automatically by the Appsmith image, and by the MongoDB Atlas clusters, which is another reason we recommend choosing that.

**Comment by steveiliop56** [comment]
Hi @sharat87,

I want to completely self host appsmith without requiring a cloud service. Could you please provide me with the config that appsmith does so I can make it work?

**Comment by Cheizr** [comment]
Hey @steveiliop56 have you found a solution?
