### ISSUE TITLE
[Bug]: google sheets: Getting 404 on refreshing datasource page.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#23163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After authorising and selecting a google sheet, if the user refreshes the page, the error toast is - "something went wrong"

### Steps To Reproduce

1. Create a datasource
2. authorise the same
4. refresh the datasource page

### Environment

Release

### Issue video log

https://www.loom.com/share/310521f8fb53492081eb77dac141a9a9

### Version

v1.9.17

**Comment by prapullc** [comment]
Closing this issue as this is not reproducible
