### ISSUE TITLE
[Bug]-[544]:Post message issues

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#23167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add message for Action selector - postmessage -

1. Try typing bellow code in message box - 
`{{{ a:1, b:API1.data.users[0].name}}}`
Actual - only {{{}}} bracket is saved

2. Try adding below code 
'{{{a:1,b:2}}}'
Actual - only {a:1,b:2} is saved

https://github.com/appsmithorg/appsmith/assets/80756091/61b25b5a-9741-4aaf-b047-069404f0f85b

Message box is not storing the data properly

https://github.com/appsmithorg/appsmith/assets/80756091/80637eec-a851-48e4-9242-c5dcc40f7c89

### Steps To Reproduce

Post-message - message box is not storing the data properly

### Environment

Production

### Version

cloud

**Comment by bharath31** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 136 |
| Effort (months)  | 0.5 |
