### ISSUE TITLE
[Bug] Fit Appsmith editor for smaller resolution screens

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2317]
## Description

Appsmith editor resolution doesn't fit well on smaller screens. Need a way to reduce horizontal scroll on such screens.
https://www.loom.com/share/5297384d90da455ca43ce22fba941df8
The below video is on a Macbook Pro 13inch 1440*900 resolution.

**Comment by Nikhil-Nandagopal** [comment]
Closing as duplicate of #2577
