### ISSUE TITLE
[Bug]: Appsmith logo on header is not correct 

### ISSUE THREAD

**Issue by berzerkeer** [appsmithorg/appsmith#23184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

So the appsmith logo returned in the tenant api should actually be `appsmith-logo-no-margin.png` this file. But the logo we are actually getting from the backend is this one `appsmith-logo-full.png`. 

### Steps To Reproduce

1. Login to appsmith
2. See the logo on the header
3. It is different from the one we had previously

### Environment

Release

### Version

Cloud / Self-Hosted - 1.9.18

**Comment by btsgh** [comment]
This does not seem to be fixed? @berzerkeer .. The logo on release seems to be the same small one.
