### ISSUE TITLE
[Bug]: Unable to bind {{Table.pageSize}} to SQL Query

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#23194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to bind Table.pageSize in Users SQL query.

### Steps To Reproduce

1. Add sample Users DB Query.
2. Add a table and bind its data to the this query.
3. Update the select query to `SELECT * FROM users ORDER BY id LIMIT {{Table1.pageSize}}`
4. The binding fails to get attached and the saving spinner keeps rotating.

This issue happens most of the times but not all the times. Refresh the page/Replace the binding with a hard coded value and put the binding back again if the issue doesn't repro.

Happening on release tree starting from 8854493ff0.

Error screenshot:
![Screenshot 2023-05-10 at 7 34 20 PM](https://github.com/appsmithorg/appsmith/assets/1189106/869e73e8-5b2e-438e-be60-f3385d9f3ed0)

### Environment

Production

### Issue video log

https://www.loom.com/share/0d9ba48a5968430ea74067382cdac979

### Version

Cloud

**Comment by btsgh** [comment]
Tested - works fine
