### ISSUE TITLE
[Feature]: Improve toast message when cloud services is not accessible for templates endpoint

### ISSUE THREAD

**Issue by abm17** [appsmithorg/appsmith#23196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When the templates endpoint on cloud services is not reachable from the platform, toasts with a generic error message appear. The messaging needs to be improved to indicate that this owing to the templates (or any other relevant endpoint) on cloud services.
![Screenshot 2023-05-10 at 4 53 35 PM](https://github.com/appsmithorg/appsmith/assets/13333024/302d796a-14a6-4715-a51d-8934d74b596e)

### Why should this be worked on?

This would ensure that the user is not misguided by the error messages and is able to pinpoint what exactly the issue is and report it accordingly.

**Comment by AnaghHegde** [comment]
Changed the estimate to add unit test. It was missing.
