### ISSUE TITLE
[Bug]: Embed apps leave space for side nav bar on Deployed mode

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#23190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Navigation is set 'Side' and make the app `embed=true`, we can observe that the widgets in the app leave space for side nav bar

### Steps To Reproduce

1. Create an application
2.  Drop some widgets to left of the canvas
3. Go to App settings> Navigation
4. Select Orientation as 'Side'
5. Go to App Settings> Share & Embed
6. Copy the embed app link after making app public
7. Deploy the app
8. Paste the copied embed app link into browser
9. Observe that the widgets aren't covering entire screen and leaves space for side nav bar

### Environment

Production

### Issue video log

https://www.loom.com/share/1cf3e968058841d78b10211726776a4b

### Version

Cloud/Production

**Comment by somangshu** [comment]
@dhruvikn this seems to be a priority item. Please check this out, triage and identify the next pipeline this issue should move to.

**Comment by dhruvikn** [comment]
Because of [this PR](https://github.com/appsmithorg/appsmith/pull/23725#issuecomment-1573194773) Somangshu. Since it got merged yesterday, I have moved the issue away from the blocked pipeline.
