### ISSUE TITLE
[Bug]: Server restart is failing/taking longer intermittently in CI

### ISSUE THREAD

**Issue by Vijetha-Kaja** [appsmithorg/appsmith#23212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed in CI , where server restart fails on enabling/disabling Github/SAML/OIDC authentication in admin settings
![cypress-screenshot (27)](https://github.com/appsmithorg/appsmith/assets/119562824/b293045a-0c1b-429f-b010-3a93f4854d07)

### Steps To Reproduce

1. Login to Appsmith EE
2. Navigate to authentication tab in admin settings
3. Click on enable button of Github/SAML/OIDC
4. Give required credentials
5. Click on save & restart
**Note:** Issue can also be reproduced on disabling authentication.

### Environment

Release

### Issue video log

https://github.com/appsmithorg/appsmith/assets/119562824/8e58e10d-53fd-4e68-88f7-6eb9f6a3bb6b

### Version

Release

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/6599/test-results/687fce7b-b917-4a55-b8b7-127c32926cf3) with above failure - [Logs to help debug](https://github.com/appsmithorg/appsmith/files/11449863/15_ci-test.ci-test.14.txt)

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/7225/test-results/e501376c-fff3-445b-8735-a47a50447e52) with above failure

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/7444/test-results/34f20f53-33bd-4e26-ae21-cd3ef99495e0) with above failure - [Logs](https://github.com/appsmithorg/appsmith/files/11666631/43_ci-test.ci-test.42.txt)

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/n14p1y/runs/7603/test-results/01036502-b895-47d5-908d-c919533b8def) with above failure - [Logs](https://github.com/appsmithorg/appsmith/files/11720587/48_ci-test-limited.ci-test-limited.47.txt)

**Comment by RakshaKShetty** [comment]
verified by vijetha closing it
