### ISSUE TITLE
[Bug]: Progress bar gets stuck when commit doesnt go through

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#23210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1439" alt="Screenshot 2023-05-11 at 9 47 33 AM" src="https://github.com/appsmithorg/appsmith/assets/80334441/b0d18c4a-9477-4a0d-876e-b50ccb28fbba">

### Steps To Reproduce

1. Connect 4 public repos of git to apps
2. Make all of them private
3. Try commiting changes in one of the apps
4. Observe repo limit error is thrown
5. Open git sync modal again and observe commit gets stuck

### Environment

Release

### Version

Release

**Comment by brayn003** [comment]
Unable to replicate this
