### ISSUE TITLE
[Bug] New Query creation modal doesn't show the complete text of "New Query"

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2322]
<img width="1505" alt="Screenshot 2020-12-23 at 9 59 22 AM" src="https://user-images.githubusercontent.com/8403079/102959529-c825b700-4505-11eb-9437-22b42c3ef2b8.png">

**Comment by areyabhishek** [comment]
I saw a similar bug inside the query creator where delete isn't completely visible. #2301 
Something strange happened with the buttons.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno can you please help triage this? As Abhishek pointed out, we've seen it in a few places and it seems to be spreading. Which change has caused this? This could cause a lot of issues to NUX
