### ISSUE TITLE
[Bug]: hashed request returned unmatched

### ISSUE THREAD

**Issue by marssantoso** [appsmithorg/appsmith#23248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Background:**

My backend implements a security layer that requires request payload for a POST request to be hashed using hmac sha-256, and send this salt alongside the payload in header.

**How I do it in appsmith:**

By using this external lib, hashed the payload and send it with the request as expected.

**Result:**

Error from my backend saying that hashed value is invalid or mismatched compared to the sent payload.

**Expectation:**

A 200 success response from my backend. Because when I do hashed it manually (either from appsmith and console.log-ing the result or outside of appsmith) and use the result in postman or any other HTTP client it works fine.

**Question:**

Does appsmith somehow transform the original payload before sending the request to the designated backend, causing the hashed payload mismatched with the original one?

Is there any way to debug this or a possible workaround so my request would return a success?

### Steps To Reproduce

// will try to provide a sample project that could reproduce this, but it could be tricky since it's a private internal app

### Environment

Production

### Version

self hosted 1.9.13

**Comment by sumitsum** [comment]
Hi @marssantoso , if possible can you please share details of how you hashed your payload by providing your JS code (or screenshot), similarly please share details for your final REST API query config so that we may try to replicate the same on our side.
