### ISSUE TITLE
[Feature]: Review the need for `dynamicPropertyPathList` in Widget DSL

### ISSUE THREAD

**Issue by dvj1988** [appsmithorg/appsmith#23258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In a widget DSL the key `dynamicPropertyPathList` lists the widget properties which have been toggled to the JS mode. 
Can this be derived from the value set to these properties? The predefined values are usually a boolean or one of the values in a predefined enum. 
For eg. In a Button widget if the user toggles property `buttonVariant` to JS mode it is added to the `dynamicPropertyPathList`. Is it possible to derive this by checking if the value set to the property is equal to `'PRIMARY' | 'SECONDARY' | 'TERTIARY'`
Non JS Mode
<img width="280" alt="Screenshot 2023-05-12 at 12 11 41 PM" src="https://github.com/appsmithorg/appsmith/assets/18716465/51f0927c-c05f-4199-8035-0c66ae1de205">
JS Mode
<img width="361" alt="Screenshot 2023-05-12 at 12 12 58 PM" src="https://github.com/appsmithorg/appsmith/assets/18716465/a3aac357-969a-4832-87a4-c303565c4d8b">

In case of actions we could also evaluate the JS expression to identify if they can be represented in non JS mode. The validation logic seems to be already in place as we use the same to enable and disable the JS mode button.
![ezgif com-crop (1)](https://github.com/appsmithorg/appsmith/assets/18716465/f1643346-4a72-45a1-88f4-9c2080422d71)

### Why should this be worked on?

This could reduce the size of the application DSL and save us the trouble of maintaining a separate value.

**Comment by ohansFavour** [comment]
@dvj1988, we also use the `dynamicPropertyPathList` field to check whether a dynamic trigger uses "action selector" or js. This will be introduced [here](https://github.com/appsmithorg/appsmith/pull/24994).

In the event that we remove the `dynamicPropertyPathList` field, we'd need to change the logic for determining if a trigger event uses action selectors or not.
