### ISSUE TITLE
[Bug]: Please enter a valid parameter executeActionDTO

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#23253]
### Is there an existing issue for this?

- [X] I have searched the existing issues
Duplicate of #23250 

### Description

When trying to insert a value into MongoDB, we get the following error saying: `Please enter a valid parameter executeActionDTO`.

### Steps To Reproduce

1. Create a MongoDB data source. 
2. Try to insert anything into it from Appsmith

### Environment

Production

### Version

Cloud & Self - Hosted  > 1.9.16

**Comment by riteshkew** [comment]
Duplicate #23250
