### ISSUE TITLE
[Bug]: Clearing cache and reloading the app does not redirect to login page on release. Works fine on prod

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#23292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clear app cache on the browser and refresh the page - notice an error stating application can't be found and app goes into a perpetual loading state.

Behaviour on prod is to redirect the user to the login page on detecting user logout.

**On release**
![image](https://github.com/appsmithorg/appsmith/assets/79509062/f352a0db-cb4a-43ab-9586-c744bf72a851)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/36d4a743-1201-4264-9a85-0bd3790d6f56)behavior

**On prod**
![image](https://github.com/appsmithorg/appsmith/assets/79509062/8647efc5-72f3-40b8-b6b2-249656dcc733)

### Steps To Reproduce

1. Open an application
2. Delete site data from site settings
3. Refresh page and notice the error

### Environment

Release

### Version

Cloud

**Comment by SatishGandham** [comment]
@ramsaptami , can you tell me how to do this step.

> Delete site data from site settings

I deleted the cookies, as a result the user was logged out and redirected to login page.

**Comment by ramsaptami** [comment]
[Repro steps](https://www.loom.com/share/5521486e25654db4b204e935863e6f39)

**Comment by rohan-arthur** [comment]
checked today both on release and prod - upon deleting the site data and triggering a refresh in both scenarios I was redirected to login
