### ISSUE TITLE
[Task] Selected state of table is not visually distinct from hover state

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2331]
## SubTasks
- Choose a color for the selected state
- Remove alternate striping for table rows
- Choose a color for the hover state

**Comment by areyabhishek** [comment]
@vicky-primathon can you remove the alternate stripes for the table rows? It'll make the table widget work much better.

**Comment by billyrudi** [comment]
many time alternate color can help users to follow very large rows . it is not necessary to have hover or selected row differents colors but only even and odd .

**Comment by sharat87** [comment]
@billyrudi, since this is a closed issue, it might not get the attention it otherwise would. So I opened https://github.com/appsmithorg/appsmith/issues/8923 with the same topic.

**Comment by billyrudi** [comment]
Thanks, I appreciate it.
Your work is great.
May I help you with it?


Il giorno sab 30 ott 2021 alle ore 09:01 Shrikant Sharat Kandula <
***@***.***> ha scritto:
