### ISSUE TITLE
[Bug]: add workspace internal server error while processing request

### ISSUE THREAD

**Issue by jaruwatxtc** [appsmithorg/appsmith#23324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Click add new workspace
2. Err. internal server error while processing request
3. Re-Login page can't load

![image](https://github.com/appsmithorg/appsmith/assets/133617438/61d91733-87c9-463a-8a12-d2af50ff0adc)

### Steps To Reproduce

1. Restart docker

### Environment

Production

### Version

1.19.18

**Comment by pranavkanade** [comment]
@jaruwatxtc could you please reach out to our support team at support@appsmith.com so that they can help you get unblocked?
