### ISSUE TITLE
java: 找不到符号   符号:   类 QPermissionGroup   位置: 程序包 com.appsmith.server.domains

### ISSUE THREAD

**Issue by jynine** [appsmithorg/appsmith#23331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Java: symbol not found

Symbol: Class QPermissionGroup

Location: Package com.appsmith.server.domains

### Steps To Reproduce
Java: symbol not found

Symbol: Class QPermissionGroup

Location: Package com.appsmith.server.domains

### Environment

Production

### Version

V1.9.19

**Comment by pranavkanade** [comment]
@jynine could you please elaborate the issue you are facing?
