### ISSUE TITLE
[Bug]: User is allowed to save DS with same name as existing DS, though in back end it is stored as untitled datasource <no>

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#23334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even if the datasource name is already used, the datasource can still be saved with that name, and the toast messages that appears on the datasource being saved is pointing to a name that does not exist.

### Steps To Reproduce

1. Create a new DS - say mongo ds - and give it a name mongo. Save it
2. Create another new mongo DS and give it the same name as above -  mongo. Save it
3. Note that the datasource is still saved with the same name on the DS UI, though we get a prompt to change name as the DS name is already used. 
4. The toast messages that appear on datasource being saved are pointing to a name that does not exist.

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/eE83J1XxuFe4FYMD

### Version

Self Hosted

**Comment by rohan-arthur** [comment]
https://images.zenhubusercontent.com/275993885/0b526f40-ee0d-4838-bf6d-091ab657cdd0/screen_recording_2023_05_15_at_14_01_30.mov

we do show a validation error, but if the user still insists and clicks save, the datasource is saved with overridden name as `Untitled Datasource xx` (xx is a number)

Datasource save should not be allowed in this case, and an error should be shown to the user that the name is duplicate.

**Comment by sumitsum** [comment]
This seems to be a FE issue, as the client is sending the new name as a parameter to the API server. API server, by itself, returns error if duplicate name is found: 
`AE-APP-4091: Duplicate key error: An object with the name null already exists. Please use a different name or reach out to Appsmith customer support to resolve this.`

**Comment by sumitsum** [comment]
Update: closing this as it is not really a bug, may issue with UX. The datasource saves with `Untitleds Datasource xyz` because that is the name it gets initially assigned. When the user tries to update this name with a duplicate name it fails and shows an error to the user. When the user clicks on the save button it then accepts the earlier name because user specified name was not chosen.
