### ISSUE TITLE
Git - Analytics updates

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#23347]
1. Add the `appId` parameter to events. If `applicationId` exists, keep it as is.
2. Add `orgId` parameter for workspace. If `organisationId` exists, keep it as is.
3. Add `instanceId` if it doesn't exist.

**Events in question**
![image](https://github.com/appsmithorg/appsmith/assets/16632903/8abb44d7-28c0-4a35-aba8-b4edb80363f6)
![image](https://github.com/appsmithorg/appsmith/assets/16632903/2b1c14e8-ce47-4a7f-afc7-4f541ee0ff89)
![image](https://github.com/appsmithorg/appsmith/assets/16632903/cd591cb2-a4cb-40bc-a68a-538ea606adaa)

**Comment by nayan-rafiq** [comment]
@infinitetrooper these events are fired from backend and frontend. The event names with capital letters are FE events so we need to update the FE as well.

For the BE events, I've added two new parameters - `appId` and `orgId`. The `instanceId` is already there.
