### ISSUE TITLE
[Feature] `clearForm` action

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2335]
## Summary

A way to clear a form from outside the context of the form.

## Motivation

In some use-cases, developers would like to have the form clear its fields from an independent trigger.

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal @riodeuno is this about introducing a new action? What does the solution look like?

**Comment by Nikhil-Nandagopal** [comment]
Yes, the solution could like a reset action which takes in any widget Id and resets all fields in the widget and children to their default states
{{ resetWidget(widgetName: string, resetChildren: boolean) }}
