### ISSUE TITLE
[Bug]: Action like storeValue showing up in dataField autocompletion

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#23376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Avoid showing action in data field autocompletion.

### Steps To Reproduce

1. Add Input Widget
2. Add Default value binding and try typing `Store` and notice the issue

### Environment

Production

### Version

1.9.19

**Comment by arunvjn** [comment]
Completed in https://github.com/appsmithorg/appsmith/pull/28217
