### ISSUE TITLE
[Bug]: Autocomplete is glitchy on the property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#23389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Autocomplete causes an extra scroll to appear when it shows up on the property pane for certain keywords

### Steps To Reproduce

1. Drop a widget and try to type in `{{console.log()}}` on a field and observe the glitchy interaction

### Environment

Production

### Issue video log

https://www.loom.com/share/c98e28894e6446809a24f2d313819ad0

### Version

Cloud

**Comment by bharath31** [comment]
@ramsaptami I cannot reproduce this on production

**Comment by ramsaptami** [comment]
hey, this was introduced post ADS changes and they're still on release. It'll get pushed to prod in the next upgrade @bharath31

**Comment by bharath31** [comment]
unable to reproduce this issue
