### ISSUE TITLE
Hide developer-centric features on the homepage through a GAC permission

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#23386]
We currently show the below features on the homepage for app viewers. These are developer-centric and are unnecessary for App Viewrs to see when they login to Appsmith.

1. Templates
2. Join our discord
3. Documentation
4. Welcome Tour
5. What's New?
6. Last edited information of an app.
7. Recent users of a workspace.
8. Appsmith version information.

We should introduce a `Developer Actions` permission with `View` in the `Others` section of GAC.

This permission will be `ON` for Admin/Developer roles and will be `OFF` for App Viewer roles. Admins can use this to clean up the homepage for App Viewers.

**Comment by jmullins21** [comment]
Our team is also very interested in this being available. Our end users would be confused by having this view available to them.

**Comment by geekyme-fsmk** [comment]
+1. My end users are all business folks, so they don't need those developer-centric links on the side.

<img width="268" alt="Screenshot 2023-11-03 at 5 26 25 PM" src="https://github.com/appsmithorg/appsmith/assets/100678833/d8eab501-6b56-4743-a19c-772ecefb78a6">

**Comment by pranayagarwal96** [comment]
Hi folks, we are actually working on revamping this homepage to make it cleaner for app viewers/ end users and hide all the distractions that are not relevant for them. Along with that, we are also working on improving the search functionality and optimising home page performance. All these changes should be live in production in next 3-4 weeks. cc @RoopKrrish9696

**Comment by satyamkrishna** [comment]
Hey team, is there any update on this feature request. We also need exactly this feature. Our users are not that tech savy and they get confused from these features. We will also ideally want folks to not see `All Apps`

**Comment by pranayagarwal96** [comment]
@satyamkrishna we are in the final stages of pushing out this feature. It'll get merged to our release next week and should be able to all users in production in the first week of January

**Comment by pranayagarwal96** [comment]
We've finally shipped this feature as part of Appsmith 1.10.0 release (or you can try it out on [Appsmith cloud](https://app.appsmith.com/)! Apologies to everyone for significant delay in shipping this feature. Please feel free to share any feedback
