### ISSUE TITLE
[Bug] Unhelpful Action Error Toasts in Edit Mode

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2339]
For a page which has a lot of on page load actions out of which atleast one action is not configured correctly, there is an error toast shown with a simple message of EXECUTE_ACTION_ERROR. To debug this, one has to walk through all the actions to figure out which of them have errored out. Today, I would have appreciated atleast the action name in the error toast.

Related to #1357

**Comment by areyabhishek** [comment]
Does frontend know what action is failing? Is it a simple task to print something like: 'API connected to button is not executing'?

**Comment by jsartisan** [comment]
Fixed in #2355
