### ISSUE TITLE
[Bug]: Port from APPSMITH_MONGODB_URI is incorrectly parsed

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [appsmithorg/appsmith#23400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I start Appsmith with a Amazon DocumentDB cluster uri like so

```bash
APPSMITH_MOGODB_URI=mongodb://<username>:<password>@databaseb269d8bb-xxxxxxxxx.cluster-xxxxxxx.eu-west-1.docdb.amazonaws.com:27017?tls=true&tlsCAFile=/usr/local/share/ca-certificates/rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=primary&retryWrites=false
```

Parsing the URI fails to extract the port. From the Input and the error message below I suspect that the URI is split at the first "/" instead of correctly parsing the whole URI (using the Java [URL](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html) class) and then extracting the port using `getPort()`.

<summary>
<details>

> backend stdout | [2023-05-16 10:52:53,302]  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'customThemeRepositoryCEImpl' defined in URL [jar:file:/opt/appsmith/backend/server.jar!/BOOT-INF/classes!/com/appsmith/server/repositories/ce/CustomThemeRepositoryCEImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'reactiveMongoTemplate' defined in class path resource [com/appsmith/server/configurations/MongoConfig.class]: Unsatisfied dependency expressed through method 'reactiveMongoTemplate' parameter 0: Error creating bean with name 'reactiveMongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoReactiveDataAutoConfiguration.class]: Unsatisfied dependency expressed through method 'reactiveMongoDatabaseFactory' parameter 1: Error creating bean with name 'reactiveStreamsMongoClient' defined in class path resource [org/springframework/boot/autoconfigure/mongo/MongoReactiveAutoConfiguration.class]: Failed to instantiate [com.mongodb.reactivestreams.client.MongoClient]: Factory method 'reactiveStreamsMongoClient' threw exception with message: The connection string contains an invalid host 'databaseb269d8bb-0qq4zfnvoyrt.cluster-ckukpnzuka1f.eu-west-1.docdb.amazonaws.com:27017?tls=true&tlsCAFile='. The port '27017?tls=true&tlsCAFile=' is not a valid, it must be an integer between 0 and 65535

</details>

### Steps To Reproduce

Start an Appsmith instance with an external mongodb instance without a trailing slash

### Environment

Production

### Version

Self Hosted - 1.9.19

**Comment by sharat87** [comment]
Hey @matthias-pichler-warrify , thank you for reporting this. While I agree with you in principle, the reason `/` is assumed to be present in the URI, is that the MongoDB URI needs to have a database name, which shows up as a `/dbname` just after the port number. Not including this `/`, but adding query params with a `?` is actually an error. Refer the URI format at https://www.mongodb.com/docs/manual/reference/connection-string/#standard-connection-string-format, see that `/` needs to be included, if you want query params, even if you don't have a DB name.
