### ISSUE TITLE
[Feature] Add a table level trigger for page size change as it exists today for search text, row selected, page change, etc.

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2341]
## Summary

[Feature] When the row size of the table is changed, leading to the pageSize changing, we should be able to trigger an action so that the table data can be refreshed

## Motivation

Why should this be worked on? What problems or use cases does it solve or
improve?

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by tazmaniax** [comment]
The "Motivation" is that without triggering the query the table will not be fully populated immediately and will require non-intuitive follow on actions to get a full page of data. Also when going to the next page and then coming back the original page will not be what was before and there will be an overlap of items that could cause confusion - best to sync the query and the table asap

**Comment by Nikhil-Nandagopal** [comment]
@tazmaniax to understand your query correctly, you want the query to re-run when you resize the table? If this is the case, I think we should automatically run the query on resizing instead of providing a trigger because resizing is an action only a developer can perform and not an action an end-user can. Does that make sense?

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : Another scenario where the page size changes is when you change the row height. This option is available to the end user and not just the developer.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand thanks for the additional context. Will consider adding this for that use case.

**Comment by tazmaniax** [comment]
@Nikhil-Nandagopal yes as per what @trishaanand has mentioned, changing the row height by the end user is the main use case I was considering. What is the difference between a "trigger" and automatically running?

**Comment by Nikhil-Nandagopal** [comment]
@tazmaniax well providing a trigger would be to add a new option inside the table's property pane so you can configure onPageSizeChange -> Call API / Query / showMessage while doing it automatically would be to simply always re-run any API that's connected to the table whenever the Table's page size changes without exposing another configuration option to a developer

**Comment by tazmaniax** [comment]
@Nikhil-Nandagopal I think the latter option would be sufficient so that when the number of displayed rows change, primarily from changing the row height, then the existing onPageChange handler is triggered. I don't see the need at this point for a new separate onPageSizeChange - less is more :)

**Comment by riodeuno** [comment]
@trishaanand I was wondering if fixing #2340, make this issue moot.

**Comment by tazmaniax** [comment]
My 2c is that it depends if the fix for #2340 results in a re-execution of any dependent queries or APIs when paging is enabled. If not then when the page size is changed additional available data will not be loaded and displayed automatically as would be expected.

**Comment by Nikhil-Nandagopal** [comment]
This is also related to #2639 and we can come up with a complete fix for this issue

**Comment by riodeuno** [comment]
How are we moving forward with this?
Before #2639 is implemented. We will be adding another property called `onPageSizeChange` which will allow developers to trigger an API call when the table `pageSize` property changes.
