### ISSUE TITLE
[Feature] Un-select row

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2342]
## Summary
Ability to clear selection in a table without having the "multi select" option enabled.

## Motivation
In some cases, users would like to remove selection of the selected row.

**Comment by Devedunkey** [comment]
Is anyone working on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@Devedunkey you can go for it! I'm assigning it to you :)

**Comment by Devedunkey** [comment]
During the adjustment, I've figured out the selected row action does not trigger any event. Is it a bug?

**Comment by diegonc** [comment]
Hi, is there any event for the un-select action? I need to clear some store properties loaded on selection

**Comment by somangshu** [comment]
Not yet @diegonc, We only have an event for the selected state

cc @dilippitchika does this sound feasible, Should we think about this in the v2

**Comment by dilippitchika** [comment]
Created a new issue https://github.com/appsmithorg/appsmith/issues/15891, also @diegonc is it not possible to simply reassign the store value when a new row is selected? What is the use-case here exactly on clearing value on row unselection?

**Comment by diegonc** [comment]
@dilippitchika Sorry, I don't remember exactly right now, it's been a long time since I did any work on appsmith. I recall some fields not being cleared on form submit (the form where the selected row info was shown) but I'm not sure how that worked.

**Comment by MisfitMagikarp** [comment]
The use-case, is if you were to utilize "on-row selected" to load table/list-item data and then when you "unselect" the tables are allowed to be re-query-ed thus allowing the table to load the "null" or empty data as they should on "row-unselected".

**Comment by Fjury** [comment]
> [@MisfitMagikarp](https://github.com/MisfitMagikarp) that's already possible today by simply checking whether `{{Table1.selectedRow.column === null ? "Don't load data" : "load data" }}`

Not really what we like to do.... Or give us a working example with two tables please. 

Selecting a row in table1 triggers table2 to update it's content.
But on 'un-selecting' this row in table1 again, table2 has to update again - that's what we want, but is not working.
