### ISSUE TITLE
[Feature] Download RAW JSON

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2344]
## Summary
Allow for RAW JSON download/copy along with CSV from table.

## Motivation
The filtered output of the table widget is useful in JSON format. Having only CSV format available can be limiting.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno this should be possible via the download action today
https://docs.appsmith.com/function-reference/download

**Comment by notacouch** [comment]
@Nikhil-Nandagopal  Is there a way to copy to clipboard instead of downloading?

**Comment by Nikhil-Nandagopal** [comment]
@notacouch we don't have that option yet but I've added a feature request for this #2379. This should be fairly straight forward to implement.

**Comment by notacouch** [comment]
@Nikhil-Nandagopal  Nice. You and your team are awesome! 🎉

**Comment by riodeuno** [comment]
Closing this issue, as @Nikhil-Nandagopal  suggested, we can use https://docs.appsmith.com/function-reference/download to download the RAW JSON data.

**Comment by notacouch** [comment]
Just writing to confirm what I did was have another container with buttons to download all the table's data as JSON, and another button for downloading just the selected row.

**Comment by areyabhishek** [comment]
Glad you figured it out. Thanks for letting us know.
