### ISSUE TITLE
[Bug] Need to enable SSL options in mysql plugin

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2345]
## Description
Need to handle SSL options in mysql plugin

### Important Details
 - Version: Any
 - OS: Any
 - Browser: Any

**Comment by dineshshanmugam** [comment]
it would be great if this can be fixed , ideally cannot allow connection without ssl to any cloud db sites.

**Comment by sumitsum** [comment]
Closed in https://github.com/appsmithorg/appsmith/pull/3518

**Comment by mohanarpit** [comment]
@dineshshanmugam This has been fixed and will be available in our next release next week. Thank you for upvoting this feature!
