### ISSUE TITLE
Get host machine IP address from a CS endpoint

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#23467]
We currently get the IP address of the machine Appsmith is hosted on from http://api64.ipify.org/, meaning that customers running Appsmith on VPC need to whitelist this URL. Some customers raise questions from security POV. Handling this from cs.appsmith.com will be a cleaner implementation and remove doubt for some customers.

**Comment by abhvsn** [comment]
Closing this as already completed.
