### ISSUE TITLE
[Bug]: Async keyword is getting added in binding data

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#23496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Please find below behaviour when async keyword is getting added before function binding for same is getting updated with async keyword

https://github.com/appsmithorg/appsmith/assets/80756091/f2c831ec-ee6d-4fdd-afc3-b8f9d6cfe407

### Steps To Reproduce

Add async keyword before the below code and verify the behaviour - 
`	  myFunc131: async ()=>{
		return "Test3"
	}`

### Environment

Production

### Version

cloud

**Comment by bharath31** [comment]
@ohansFavour could you please run an RCA here? lint errors don't seem to be showing up

**Comment by ohansFavour** [comment]
@bharath31, this is a JSHint issue. The linter throws no error in this case. Eslint throws an error in this case. I have created[ a task](https://github.com/appsmithorg/appsmith/issues/23805) to explore the possibility of migrating to ESLint (I found [this browserified ESLint module](https://www.npmjs.com/package/eslint-linter-browserify))

**Comment by iSatVeerSingh** [comment]
What about something like [CodeMirror](https://codemirror.net/)

**Comment by rohan-arthur** [comment]
not reproducible anymore
