### ISSUE TITLE
[Feature]: Support DocumentDB as an alternative to MongoDB

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#23509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith requires MongoDB today, as it's database to store all application data.

DocumentDB is an AWS-native database service, that's reasonably compatible with MongoDB, but not 100%. Appsmith needs to be compatible with DocumentDB as well, so that it can be run with DocumentDB instead of MongoDB.

### Why should this be worked on?

For folks that are invested in the AWS cloud, it helps to have everything within their AWS account. But if they want to use a managed service for MongoDB with Appsmith, they have to get that from MongoDB Atlas, which is stepping out of AWS service suite. Since AWS offers DocumentDB, if Appsmith were compatible with it, users can have a managed database in AWS itself, and use Appsmith.

**Comment by matthias-pichler-warrify** [comment]
Ok I got everything up and running up until the point where the MongoDB database setup is performed. Then it fails because of the index name being too long. 

```js
backend stdout | io.mongock.api.exception.MongockException: Error in method[DatabaseChangelog1.addNewActionIndexForPageId] : Command failed with error 67: 'namespace name generated from index name is too long' on server databaseinstance1844f58fd-hrbfxlalfvhv.ckukpnzuka1f.eu-west-1.docdb.amazonaws.com:27017. The full response is 
{
    "ok": 0,
    "code": 67,
    "errmsg": "namespace name generated from index name is too long",
    "operationTime": {
        "$timestamp": {
            "t": 1684778575,
            "i": 1
        }
    }
}
```

Would it be possible to update the index name generation logic behind a feature flag `APPSMITH_INDEX_VERSION=2` to make it compatible?

**Comment by rhuanbarreto** [comment]
This task should support also Azure specific flavour of mongoDB: CosmosDB API for MongoDB

**Comment by sharat87** [comment]
@matthias-pichler-warrify, thanks, yes, that's the error we noticed as well, and is already fixed. We're facing further errors after fixing that though, and we're already working on them as well.

@rhuanbarreto, indeed, that's the plan. Thanks for mentioning that as well. 🙏

**Comment by aniket-flash** [comment]
I have the same reasons as mentioned by @sharat87 . I can see the ask is already in progress, it will be nice if we can get an ETA for this so that we can plan the migration accordingly.

**Comment by sharat87** [comment]
Hey @aniket-flash, thanks for sharing interest. We're still in initial stages of figuring out how much of existing Appsmith functionality fails with DocumentDB, and what it would take to fix those. So, it's a little hard to share an ETA without that visibility of how much fails. We'll share updates on this issue as we progress. Thanks again!

**Comment by geekyme-fsmk** [comment]
Upvoting on this - would prefer not to manage my own mongodb cluster and use documentdb.

**Comment by dixerus** [comment]
You can already connect to DocumentDB Elastic cluster using a direct connection. It works fine for us. 
The instance based DocumentDB requires pem files that Appsmith doesn't currently support.

**Comment by sharat87** [comment]
Hey @dixerus, thanks for sharing. In our tests, we noticed that several features don't work well, or don't work at all when Appsmith is running with DocumentDB. Your experience appears to be quite different, if I read that right. Can you confirm you're able to start Appsmith and use it with DocumentDB? I'd be very interested in comparing notes if that's the case. 🙂

**Comment by dixerus** [comment]
To make a specific distinction: we use DocumentDb as an app database, no Appsmith internal DB that uses mongo DB. And yes, DocumentDb functionality is a truncated version of mongo DB in terms of the query language. But whatever DocumentDb supports works fine on Appsmith, as we were able to build relatively complex queries and they work fine with an acceptable speed for an internal app.

**Comment by KyeNine** [comment]
Has anyone been able to get documentDB working with AppSmith as the instance's storage? We'd prefer to not setup atlas in favour of terraform/documentDB.

**Comment by AdamStrLSEC** [comment]
> Has anyone been able to get documentDB working with AppSmith as the instance's storage? We'd prefer to not setup atlas in favour of terraform/documentDB.

Unfortunately not, we tried this against a DocumentDB instance running MongoDB 5.0 and constantly hit a replicaset needs to be enabled error on container startup despite it all being setup.

**Comment by pksha-hideyuki-ishiwata** [comment]
Hello. I'm Japanese and testing Appsmith service working on AWS system.
I'm begineer with Appsmith and AWS.
My AWS DocumentDB study concluded Appsmith is unable to use DocumentDB.
Because DocumentDB requires tls(ssl) connection using DocumentDB cluster preparing pem key.
I realize Appsmith does not provide mongo db tls(ssl) connection too.Above other user said. 
I connected DocumentDB instance and executed "rs.status()" command. Response is good.
Of course this is cluster and multi instance works, replication will work.
Appsmith requires replication mode mongo db absolutely.Appsmith starting is fault if I set external mongo db which is not replication mode via container environment or Admin setting mongo db uri editting.
Appsmith's install manual notes about replication mongo db is required.

**Comment by pksha-hideyuki-ishiwata** [comment]
Hello. I'm Japanese. I'm testing Appsmith on AWS system.
I checked AWS DocumentDB.
My conclusion is Appsmith is unable to use AWS DocumentDB.
I set created DocumentDB tls mode off.
So, pem key requirement disappeared.
I got error message log:

Error even from changeStream MongoServerError: modifyChangeStreams has not been run for this collection/database/cluster...

 **************************************************************************************
      MongoDB Replica Set is not enabled
      Please ensure the credentials provided for MongoDB, has 'readWrite' role.
 ***************************************************************************************
I set task role policy AmazonDocDBFullAccess including install manual directing ssmmessages:CreateControlChannel,ssmmessages:CreateDataChannel, ... .

I logged in AWS Fargate container using command "aws ecs update-service --enable-execute-command" and "aws ecs execute-command ... --command '/bin/sh' ".
I could logged in DocumentDB from container using mongosh command.
Network and Security group setting was correct.
Maybe policy was ok.
I executed "rs.status()" command in documentDB and response was ok.Replica was working.
In AmazonDocDBFullAccess policy, "rds:ModifyDBCluster" and many other actions is allowed.
I watched this references:
https://docs.aws.amazon.com/documentdb/latest/developerguide/get-started-guide.html 

Must other actions must be set?
I realized DocumentDB system forbade replication control via application.
Clustering, replication core control will be in documentDB.

I'm AWS and Appsmith beginner. Please teach me about miss understanding.

more:
If DocumentDB's tls mode is on, global-bundle.pem key file must be set in any directory.
Request will be like this:

mongodb://<insertYourUserName>:<insertYourPassword>@document-db-connection-domainxxxxxxx.ap-northeast-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=/path/to/put/global-bundle.pem&retryWrites=false

I set global-bundle.pem in /opt/appsmith/global-bundle.pem in Fargate container and I connected DocumentDB using mongosh command and pem file.
Then I set mongoURI with string above replaced with data and tlsCAFile path /opt/appsmith/global-bundle.pem via Admin setting page.
Restart was fault. Cloudwatch log shows /opt/appsmith/global-bundle.pem  no such file or directory error.
Is this fault caused from putting key path miss? /appsmith-stock directory path? permission miss? I forgot file permission check. Or Can't Appsmith handle tlsCAFile path?

Anyway, DocumentDB using was fault.

**Comment by Nikhil-Nandagopal** [comment]
We're planning to support postgres instead of DocumentDB as we think that will be a better alternative.

**Comment by krishnvamsi03** [comment]
Hello,

I am considering using DocumentDB (without TLS) for Appsmith. Some older versions of Appsmith (v1.16 and older) worked with DocumentDB, but when I switched to the latest version (v1.26), it didn't work. The migration failed at Migration049RemoveLayoutBaseFields. Diving into the code, I found that the execute method uses an aggregation update. As far as I know, aggregation and pipeline queries are not supported in DocumentDB, and I believe that the aggregation update relies on these features.

Could you please confirm if my understanding is correct? Are there any workarounds for this issue, or should I consider that it is not advisable to use DocumentDB until it is officially supported by Appsmith?

Thank you.

**Comment by Nikhil-Nandagopal** [comment]
I'm closing this in favor of #30037
