### ISSUE TITLE
[Feature] Disable Sign Up for self hosted instances

### ISSUE THREAD

**Issue by sijomc** [appsmithorg/appsmith#2350]
We have deployed an Appsmith docker container in a public cloud and which is accessible publicly. It would be nice to have an option to disable sign up and add users from the admin panel. Is this option available?

Otherwise, we have to deploy it in a VPC and restrict access through a VPN. So our internal users only can access that URL.  Is this the option you suggest?

Thanks in advance.

**Comment by Nikhil-Nandagopal** [comment]
@sijomc thank you for reaching out. Right now this is not possible but we'll consider taking this up as a feature request. We do suggest deploying appsmith behind a VPN today.
Also just to be clear, any users signing up on your instance will not have access to your databases and apps unless they are explicitly invited to the organization in which you build them

**Comment by Nikhil-Nandagopal** [comment]
This has been asked for before as #1342 and #1362.

**Comment by sharat87** [comment]
After the next release, please set `APPSMITH_SIGNUP_DISABLED` environment variable to `true` to disable public signups on your Appsmith instance. Note that invited users will still be able to sign up as before.
