### ISSUE TITLE
[Bug]: Helm chart value incorrect (EE repo)

### ISSUE THREAD

**Issue by robtimmer** [appsmithorg/appsmith#23503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The helm chart has the url value of "https://helm-ee-appsmith-com/appsmith-3.0.2.tgz"

This gives issues with helm commands and the installation.

https://helm-ee.appsmith.com/appsmith-3.0.1.tgz is a example of a correct url.

Please fix so we can use the EE repo properly

### Steps To Reproduce

helm repo add appsmith-ee https://helm-ee.appsmith.com
helm repo update
helm show values appsmith-ee/appsmith > values.yaml

Last command gives a error because of the invalid URL

### Environment

Production

### Version

3.0.2 (EE Helm Chart)

**Comment by pranavkanade** [comment]
@robtimmer can you please provide a screen-shot of the exact error?

I just ran this on my machine and it works fine for me.

**Comment by sharat87** [comment]
@robtimmer, sorry for the delay in getting back. Are you still facing this issues? I see that the URL is correct for 3.0.2 now.

```
> curl -sS helm-ee.appsmith.com/index.yaml | grep appsmith-......tgz
    - https://helm-ee.appsmith.com/appsmith-3.0.2.tgz
    - https://helm-ee.appsmith.com/appsmith-3.0.1.tgz
    - https://helm-ee.appsmith.com/appsmith-3.0.0.tgz
    - https://helm-ee.appsmith.com/appsmith-2.0.0.tgz
```

Please let us know if you're still facing this issue, and we can reopen. Thanks!
