### ISSUE TITLE
[Bug]: Theming | Unable to consistenly type into Primary/Background color input fields

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#23501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/91450662/4b63fd3b-b098-4ae5-840e-9ab1df2f19ed

### Steps To Reproduce

1. Create an app, go to Theme settings
2. Remove the default values from Primary/Background color fields & start typing into it
3. Observe: Sometimes some characters/letters are skipping when the user us typing.
4. Expected - Field should be consistent in taking inputs from user & reflect the same

### Environment

Production

### Version

Cloud/Release v1.9.20

**Comment by KelvinOm** [comment]
We have a related [ticket](https://github.com/appsmithorg/appsmith/issues/22996). From my point of view, the current ColorPicker requires analysis and improvement from the UX side. At least I see a lack of validation and error highlighting if we can't parse the passed value. It is also unclear which color models (hex, rgb, etc) we support.

cc @ichik

**Comment by ramsaptami** [comment]
This issue exists on current anvil base DP

**Comment by ramsaptami** [comment]
yep, this has been fixed now
closing it
