### ISSUE TITLE
[Bug]: The User is given an instance admin access from the GAC screen and switches to the general tab the user's email is not updated until the user manually refreshes the page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#23514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The User is given an instance admin access from the GAC screen and switches to the general tab the user's email is not updated until the user manually refreshes the page

### Steps To Reproduce

1.  Set up your local ee instance
2. go to admin setting
3. now goto users tab add new user with instance admin role
4. now switch to general tab the user email is not reflected until we manually refresh the page

### Environment

Release

### Version

v.1.9.20

**Comment by ankitakinger** [comment]
@RakshaKShetty this should be fixed now. Could you verify and let us know?

**Comment by RakshaKShetty** [comment]
@ankitakinger this issue is fixed closing the issue
