### ISSUE TITLE
[Bug]: EE Parent message listening - show alert on invalid domain input

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#23510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Show error count when an error is logged in debugger (we have error logs, but footer doesn't show error count)
![image](https://github.com/appsmithorg/appsmith/assets/66776129/270de2b3-9370-412c-b7fc-02040809c10d)
- When user enters an invalid domain and tries to execute the method, show an error alert. (on both edit and view mode)

### Steps To Reproduce

https://docs.appsmith.com/reference/appsmith-framework/widget-actions/post-message#windowmessagelistener

### Environment

Production

### Version

EE - 1.9.20

**Comment by rohan-arthur** [comment]
not sure how to reproduce this - I created an API with invalid domain and upon running I see a proper error along with error count
