### ISSUE TITLE
[Bug]: for auto height with limits, unable to place widgets on the container canvas once you place a widget beyond the max height 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#23525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

for auto height with limits, unable to place widgets on the container canvas once you place a widget beyond the max height 

### Steps To Reproduce

1. Drop a container
2. Change height to auto height with limits
3. take any widget and place it beyond the max height of container
4. Now, try to place any widget towards the end of container

https://www.loom.com/share/923c930b62904ef1b515a956762e1911

### Environment

Production

### Version

Prod

**Comment by ramsaptami** [comment]
this is a non-issue on anvil layout system hence closing it
