### ISSUE TITLE
[Bug] On having long Dropdown scrolling down the menu scrolling along the canvas

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2356]
Steps to reproduce:
1) Add a Dropdown widget
2) Click on Property Pane 
3) Click on the add option (15)
4) Close the Property pane 
5) Click on the dropdown 
6) Scroll down 
and observe 

Observation:
It is observed that the dropdown menu scrolls around 

Expectation:
It is expected that the dropdown menu does scroll along the canvas
![Screenshot 2020-12-24 at 4 04 52 PM](https://user-images.githubusercontent.com/71753653/103083178-c9d4a500-4601-11eb-85cb-7b9e2f4d987c.png)

**Comment by Rishabh-Rathod** [comment]
I tried reproducing this issue but following above steps work fine.

I tried adding 21 values in a dropdown and then after closing property pane, i clicked on it and didn't face any such issue.

![Screenshot 2021-03-14 at 12 28 12 PM](https://user-images.githubusercontent.com/23132741/111060198-1c1ab900-84c1-11eb-9b1d-76724d02ed21.png)

**Comment by somangshu** [comment]
The issue occurs regardless of multi-select or single select. We must scroll the dropdown widget above the viewport to observe that the menubar/or option are sticking at the top of the canvas

https://images.zenhubusercontent.com/275993885/18be3b3d-f933-47ac-a910-d8ff7b3dd6e9/screen_recording_2021_04_26_at_6_36_47_pm.mov

**Comment by techbhavin** [comment]
In my observation when the select widget option menu popover position to right or left, it will scroll along with a canvas. 
also, I notice not the only select menu but a widget setting panel scroll around. 

to analyze all this situation I can say here popover and canvas are not working well together.

> I don't know the reason why pop over and canvas are not working as exceptions.


https://images.zenhubusercontent.com/275993885/aa1e83ba-26b2-40cf-9ce6-385e1b1669cd/screen_recording_dbuv4jm0.mov
