### ISSUE TITLE
[Bug]: App Nav bar setting fails to work in duplicate/ forked apps when we toggle the Show Nav Bar switch atleast once in the primary app and then clone it

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#23565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.loom.com/share/bdf23cd58df2414787c49350ca9dff26

### Steps To Reproduce

1. Take any application
2. Toggle the show app nav bar switch atleast once
3. Clone the application
4. Check the cloned app and try to change the settings for app navigation

### Environment

Production

### Version

Prod

**Comment by dhruvikn** [comment]
We recently deprecated the [duplicate app feature in this PR](https://github.com/appsmithorg/appsmith/pull/23461). This issue is not reproducible anymore, therefore, I'm closing it.
