### ISSUE TITLE
[Task]: Remove Action response data from unEvalTree ( DataTreeAction )

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#23570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Removes API/Query from unEvalTree
- Create an API/Query response handler in the eval worker that updates the evalTree and triggers evaluation
- For onPageLoad action run -> call the API/Query response handler

**Comment by ohansFavour** [comment]
### Performance Infra

~30% improvement in worker scripting time for MISC tests


<img width="1694" alt="Screenshot 2023-09-29 at 12 56 52" src="https://github.com/appsmithorg/appsmith/assets/46670083/5acea324-af00-49f7-8151-71f727b0c8b7">

<img width="1683" alt="Screenshot 2023-09-29 at 12 57 05" src="https://github.com/appsmithorg/appsmith/assets/46670083/54401f00-c9c5-4652-bd39-91f5a380fa0a">

**Comment by vsvamsi1** [comment]
Thanks @ohansFavour
