### ISSUE TITLE
[Bug]: Tree reducer very slow when there are lot of updates

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#23579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When there are lot of updates in an eval cycle, tree reducer becomes very slow due to the number of changes to apply.

We saw this problem on a client app with 75k table cells, where it took around 15seconds, the same happens in under 2seconds on our test app.

### Steps To Reproduce

1. Create a table with 100k cells with client side pagination enabled.
2. Add a button to change the table data completely.
3. Click the button to change the table data.

Record a performane profile when perofrming action #3 above. You will see applyChange in treeReducer taking a lot of time.

### Environment

Production

### Version

Self hosted

**Comment by ak4zh** [comment]
`applyChange` is directly changing the state for each update inside the `for..of` loop.
It should be done inside `produce` from the `immer` so it modifies the draftState and then finally return the changedState.

https://github.com/ak4zh/appsmith/blob/fix/treeReducer/app/client/src/reducers/evaluationReducers/treeReducer.ts

**Comment by SatishGandham** [comment]
@ak4zh , thats what is done in inside createImmerReducer. Problem is not with the reduce update, the apply function itself is taking lot of time.

**Comment by vsvamsi1** [comment]
Have investigated other libraries like fast json patch to replace the diff and patch operations, noticed similar performance.
Looked into skipping the diff for large dataset objects and directly updating values, this can help in reducing the diff and patch operations but investigating further in a more holistic solution around this issue.

**Comment by vsvamsi1** [comment]
Fixed as part of this tracker https://app.zenhub.com/workspaces/performance-board-6231ad37179efb001826a53f/issues/gh/appsmithorg/appsmith/24866
