### ISSUE TITLE
[Bug]: Mongo Pod CrashLoops When Running On Minikube or Kind

### ISSUE THREAD

**Issue by BrettNWoods** [appsmithorg/appsmith#23578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try and run Appsmith locally following [this documentation](https://docs.appsmith.com/getting-started/setup/installation-guides/kubernetes?current-configuration=Minikube), the `appsmith-mongodb-0` pod enters a CrashLoopBackOff state with the following output;

```
mongodb 05:41:55.73 INFO  ==> Advertised Hostname: appsmith-mongodb-0.appsmith-mongodb.default.svc.cluster.local
mongodb 05:41:55.76 INFO  ==> Advertised Port: 27017
realpath: /bitnami/mongodb/data/db: No such file or directory
mongodb 05:41:55.81 INFO  ==> Data dir empty, checking if the replica set already exists
MongoNetworkError: getaddrinfo ENOTFOUND appsmith-mongodb-0.appsmith-mongodb-headless.default.svc.cluster.local
mongodb 05:42:01.24 INFO  ==> Pod name matches initial primary pod name, configuring node as a primary
mongodb 05:42:01.40 
mongodb 05:42:01.42 Welcome to the Bitnami mongodb container
mongodb 05:42:01.44 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 05:42:01.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 05:42:01.49 
mongodb 05:42:01.51 INFO  ==> ** Starting MongoDB setup **
mongodb 05:42:01.68 INFO  ==> Validating settings in MONGODB_* env vars...
```

This happens using both Minikube and Kind. 

### Steps To Reproduce

1. Follow [the documentation](https://docs.appsmith.com/getting-started/setup/installation-guides/kubernetes?current-configuration=Minikube) to install the latest Appsmith helm chart from the repository.
2. Run `kubectl logs appsmith-mongodb-0` once the pod attempts to start up.

### Environment

Release

### Version

Self-Hosted - 2.0.2

**Comment by GRpro** [comment]
Facing same issue. Any updates?

**Comment by sharat87** [comment]
Hello, thank you reporting this. Unfortunately, support for MInikube and Kind are not on the roadmap right now. We'll update here when we revisit this decision in the future. Thank you for understanding. 🙏
