### ISSUE TITLE
[Bug]: Code editor theme breaks in a particular scenario

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#23585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Go to app at [this](https://release.app.appsmith.com/applications/62a1b93661c2701a373be948/pages/62a1b93661c2701a373be94b/edit/jsObjects/62a1b93661c2701a373be958) location and observe the theme breaks after a point

### Steps To Reproduce

Top of the code block:
![image](https://github.com/appsmithorg/appsmith/assets/79509062/48e6a243-9eaa-44a5-966d-3ed8404e2136)

Area where the theme starts to break:
![image](https://github.com/appsmithorg/appsmith/assets/79509062/5fa73493-8c16-477b-b40e-1676f132831a)

### Public Sample App

https://release.app.appsmith.com/applications/62a1b93661c2701a373be948/pages/62a1b93661c2701a373be94b/edit/jsObjects/62a1b93661c2701a373be958

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
@arunvjn could you please check what could be causing this?

**Comment by ramsaptami** [comment]
@arunvjn don't have a suitable example here

**Comment by bharath31** [comment]
@arunvjn @ramsaptami should we close this issue?

**Comment by ramsaptami** [comment]
I've seen this happen on other pieces of code when there's an error. The theme didn't fix itself when the error was cleared - caveat here is that the theme fixed itself when the page was refreshed hence wasn't able to accurately repro
@AnandiKulkarni could you keep an eye out for this too?

**Comment by ramsaptami** [comment]
sample code: `then` on the first line skips theme
![image](https://github.com/appsmithorg/appsmith/assets/79509062/09a69886-5a52-41ea-8513-48b516cdbdeb)
```
export default {
	async datatype () {
		setTimeout(() => {JSONForm1.setFormData(false).then(() => console.log('boolean pass')).catch(() => console.log('boolean error'))}, '1000')
	}
}
```

cc: @bharath31 @arunvjn

**Comment by ramsaptami** [comment]
another scenario where lint error on an array causes theme deviation but lint error on a regular text is fine
```
export default {
	myVar1: [],
	myVar2: {},
	myFun1 () {
		this.myVarible[1]
		this.myVar1[0]
	}
}
```
![image](https://github.com/appsmithorg/appsmith/assets/79509062/6c42429a-6401-4400-a96a-e157b03fc683)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/c5ff60bf-acfc-4c26-9273-0ff4a8fc144e)
