### ISSUE TITLE
[Bug] Too much spacing between option on multi selection option in Dropdown Widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2358]
Steps to reproduce:

1) Add a Dropdown widget
2) Click on Property Pane
3) Click on the add option (15)
4) make it multi selection option
5) Click on the dropdown
6) Select multiple option 
and observe

Observation:
It is observed that due to large spacing the user feels that the options are not added to the field. 

Expectation:
It is to reduce the space between option or increase the field size as the option are being added 
![Screenshot 2020-12-24 at 3 34 14 PM](https://user-images.githubusercontent.com/71753653/103084278-a2330c00-4604-11eb-98e4-ecb1833bedb1.png)

**Comment by somangshu** [comment]
This seems to have changed by now, The issue exist as mentioned in #772. The solution mentioned there will be opted. This should be linked to the same PR.
