### ISSUE TITLE
[Bug] Inconsistent behaviour of "drag" in editor mode across widgets

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#2361]
### Warning: Best watched at less than 50% volume.

<a href="
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2fa389bfdc6a43b58b588ccae9f093fd-00001.gif)](https://www.loom.com/share/2fa389bfdc6a43b58b588ccae9f093fd)

## What it feels like

Please feel free to correct me if I am wrong here.

Today, appsmith seems to operate with the following assumptions:
- Drag is the primary thing a user will do. (drag is direct vs opening property pane needs you to hover and aim)
- Every widget can be made draggable through the widget body.
- Every widget's native interaction can be made to co-exist with the global drag interaction.

As we enter the world of more complex and closely packed widgets, we need to re-ask if the assumptions above still hold true.
If yes, we need to find a solution for the following cases individually.

## A deeper dive into a few cases.

Throughout the rest of this, I will follow a color-scheme to mark different areas. Here's the color scheme.

<img width="856" alt="Screenshot 2020-12-24 at 5 19 50 PM" src="https://user-images.githubusercontent.com/292174/103087116-7451c580-460c-11eb-904b-b1060f659414.png">

### 1. Confusing cursor pointers.

<img width="296" alt="Screenshot 2020-12-24 at 5 11 11 PM" src="https://user-images.githubusercontent.com/292174/103086774-7404fa80-460b-11eb-97d5-fb3fd8f9c5f3.png">

Our drag cursor looks like a hand ready to grab in most cases, sometimes it changes for the interaction with the underlying element. This can be confusing.

### 2. Confusing drag areas.

<img width="646" alt="Screenshot 2020-12-24 at 5 45 19 PM" src="https://user-images.githubusercontent.com/292174/103088122-d7912700-460f-11eb-892e-cfdeb25130a0.png">

A user can not just click and drag anywhere. They've to aim and drag, and sometimes they'd not know what they should be aiming for. Every button should be marked yellow here.

<img width="581" alt="Screenshot 2020-12-24 at 5 54 54 PM" src="https://user-images.githubusercontent.com/292174/103088546-2a1f1300-4611-11eb-8ce5-e7f0d523e8bb.png">

The drag area here is a much smaller part of the entire UI. 

Every button is confusing because the user can't immediately intuit if clicking them will click the button or drag.

### 3. Confusing interaction on draggable/clickable layers in widgets.

Since the map has it's own drag and click behaviour *EVERYWHERE* this can get super annoying.

- If I drag a pin and try to re-adjust it, it drags widget instead.
- If I have enabled "create marker", I pretty much have to create a marker to interact with the map at all.
- Clicking might drop a pin, center the map or might trigger a drag if your mouse is sensitive enough.
- Drag might drag the widget, the pin or the map.
- Dragging a pin at the center may or may not work, dragging a pin off-center may or may not work.

https://user-images.githubusercontent.com/292174/103089444-f5608b00-4613-11eb-9529-c96aa7bb7d88.mov

### 4. No drag area

YouTube is on the extreme where you just can't drag anywhere within the widget and pretty much have to aim for the property pane.

**Comment by Nikhil-Nandagopal** [comment]
@ofpiyush thank you for opening this highly entertaining issue. Production quality 💯 
Do you have any suggestions here?

**Comment by ofpiyush** [comment]
The underlying reason is that the operations within a widget and on the global editor conflict with each other.  Simpler cases like buttons and labels do not suffer, complex widgets like table, map and rich text editor do.

The clean-ish fix for this we have to make modes of operation with clear boundaries.

Mode 1: You're interacting with the canvas.
Mode 2: You're interacting with the widget.

Implementation details of these modes and switching can vary, but any solution path needs us to think in terms of modes.

### Mode switching on a global level.

Add a button to enter "preview" mode. It is very similar to the deployed mode, except for a few major differences:
* This mode is heavily geared towards debugging, so everything is inspectable and editable, changes made to property values etc do not persist when we stop preview mode.
* Preview mode never gets saved like the deployed mode does, it's completely local.

This is how game editors solve it. When you're editing your scene, you drag and configure objects. Then you click `play` to interact with the objects like you would in the built game.

Vim, the editor, also has modes where navigation and writing code are switched between using a global key `esc`, `i`

### Mode switching per widget.

These solutions are per widget and belong to a `do X to unlock` model. where `X` can be things like clicking :lock: button, double click etc.

### Mode switch based on mouse location.

Example: If you're hovering over a widget, you see a drag handle all around the widget, that's the only thing you can use to drag a widget around.
As soon as your mouse is within the boundary of the widget itself, you're interacting with the widget.

**Comment by Curiouspaul1** [comment]
any update on this

**Comment by Nikhil-Nandagopal** [comment]
@Curiouspaul1 no and we won't be solving this so I'm closing this issue

**Comment by Curiouspaul1** [comment]
@Nikhil-Nandagopal why won't this issue be addressed if i may ask?

**Comment by Nikhil-Nandagopal** [comment]
@Curiouspaul1 because we believe that you need to both interact with widgets and configure their properties without needing to enter separate modes for them. We'll look for ways to ensure dragging a widget is possible wherever you hold it from but we'll avoid a separate mode
