### ISSUE TITLE
[Bug]: Search and filter functions in the table widget do not work as expected when the column is formatted as URL

### ISSUE THREAD

**Issue by gzarruk** [appsmithorg/appsmith#23636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the `Column Type` to URL and then search for a string or use the filters (e.g. column, contains `XYZ`) string is not found.

Seems like it is searching a combination of display text and url and only works partially. 

### Steps To Reproduce

1. Insert a table widget with random data
2. Change one of the Columns to URL type
3. Add any URL to the fields in the column
4. Search for one of the string or use the filters to find the text in that column. It might work with the first few charcters.

### Environment

Production

### Version

Self hosted v1.9.19

**Comment by gzarruk** [comment]
https://github.com/appsmithorg/appsmith/assets/24595022/f75f2637-80fc-4f8d-9fe4-20c6c486099b

**Comment by vsvamsi1** [comment]
This is a valid issue Sorting should take place by display text not computed value for the type column in the table.

**Comment by somangshu** [comment]
@vsvamsi1 not clear why this is happening. You are saying that we are only searching the computed values?

**Comment by berzerkeer** [comment]
I will look into it @somangshu .

**Comment by berzerkeer** [comment]
@dilippitchika Is it okay to search and sort table data by display value and not computed value ? 

cc: @vsvamsi1 @somangshu
