### ISSUE TITLE
Configure nginx to configure CDN at startup.

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#23639]
### 1
If CDN_URL env variable is set, then the following should be added to the index/view/edit.html files, and their gzipped version should also have this change
```
<script>
CDN_URL=<CDN_URL>
</script>
```

Feel free to change the env variable name.

### 2
We should also rewrite all static relative urls with absolute urls from CDN.

For example,
this
`/static/js/81621.58d65afe.chunk.js
`
changes to 

`https://cdn.app.appsmith.com/static/js/81621.58d65afe.chunk.js`

**Comment by sum35h** [comment]
PR : https://github.com/appsmithorg/appsmith/pull/23834
Update: ENV var is name `APPSMITH_CDN_URL`
