### ISSUE TITLE
[Task]: Documentation For Filter Query Issues

### ISSUE THREAD

**Issue by PiyushPushkar02** [appsmithorg/appsmith#23653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description ###
- After investigating these two issues #23148 and #23583 it seems there are multiple similar issues related to the where clause queries. It would be better to take them up as a project rather than as ad-hoc issues.
- As a follow up we have decided to document other related issues and possible solutions and share them with the team for further action.

**Comment by rohan-arthur** [comment]
https://www.notion.so/appsmith/Filter-Query-Related-Bugs-a950bfb9c8144005a1846fe9e6a9c4a7
