### ISSUE TITLE
[Bug] on horizonatally resizing of modal, the dimensions of the widgets get messed up

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#23658]
https://www.loom.com/share/c3ca8283dcea477b94ae3547ad518ef7

**Comment by aswathkk** [comment]
UPDATE_WIDGET_DIMENSION is already happening while resizing modal.
We need to call PROCESS_AUTO_LAYOUT_DIMENSION_UPDATES once the modal resizing is done.
