### ISSUE TITLE
[Feature]: To provide invitation emails with a branding. 

### ISSUE THREAD

**Issue by UMinky** [appsmithorg/appsmith#23665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We would be interested in the possibility to brand the invitation emails as well. 

### Why should this be worked on?

In order to achieve higher acceptance in the business environment

**Comment by infinitetrooper** [comment]
@UMinky  - What is the user flow you're expecting here? Do you want to be able to embed HTML (or) do you want to be able to edit the text of the email?

We will include the brand colors and logo in the upcoming notification emails ([HTML](https://codebeautify.org/htmlviewer/y232236c1) - The Appsmith colors and logo will be updated with custom branding). Let me know if that works for you (or) are you looking for something different?

**Comment by infinitetrooper** [comment]
Got it, Thanks Udo. We'll discuss this internally and update the ticket with progress.

**Comment by Nikhil-Nandagopal** [comment]
@UMinky this is fixed in our latest release. Give it a try and let us know if you still need more customization. Right now the brand colors and logo that you configured will show up in the emails
