### ISSUE TITLE
[Bug]: TypeError in DatasourceSection APPSMITH-6F3

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#23679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4201455215

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by btsgh** [comment]
Since its a sentry issue, closing out as is as per discussion
