### ISSUE TITLE
[Bug]: Switching branches is occasionally unresponsive

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#23673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

* Go to a got connected app in self hosted instance
* Try to switch between the branches
* Sometimes, api call becomes success 200 but no update on UI

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/8299030/21b417bb-fbdd-4709-bd1e-00bca29f420e)

### Environment

Production

### Version

Self hosted

**Comment by brayn003** [comment]
This is what happens when the user selects a new branch -
[https://www.loom.com/share/9f08081d912c411ba994f6ced111a36e](https://www.loom.com/share/9f08081d912c411ba994f6ced111a36e)

**Comment by nayan-rafiq** [comment]
This needs to be fixed for remote branches.

**Comment by brayn003** [comment]
Different issue for loading state of remote branches #25591
