### ISSUE TITLE
[Bug]: TypeError in DatasourcesSagas APPSMITH-6D7

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#23686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4183444471/

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by btsgh** [comment]
Since its a sentry issue, closing out as is as per discussion
