### ISSUE TITLE
[Bug]: Lower boundary for table is missing in the query response. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#23697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1684916741025529 
![Screenshot 2023-05-24 at 1 50 37 PM](https://github.com/appsmithorg/appsmith/assets/1757421/c65c6b95-5265-458c-9577-d3d25e8a8fbf)

### Steps To Reproduce

Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1684916741025529 

### Environment

Production

### Version

cloud, self hosted

**Comment by tanvibhakta** [comment]
<img width="1237" alt="Screenshot 2023-06-13 at 2 51 15 PM" src="https://github.com/appsmithorg/appsmith/assets/13763558/37ecbd0c-08b9-463e-80ba-7983104d9601">
