### ISSUE TITLE
[Task]: Add createdAt and updatedAt to sample postgres users table available on prod

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#23705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Having that column will help us sort entries in select query and see latest updates at the top.

![Screenshot 2023-05-30 at 12 26 02 PM](https://github.com/appsmithorg/appsmith/assets/1189106/0f23bc22-77ff-4200-b1a1-67dfaaee1f48)

**Comment by jacquesikot** [comment]
@abm17 which template is this for? We have a new user table on the new mock_db_v2 that has the updated and created fields

**Comment by rajatagrawal** [comment]
@jacquesikot 

Attaching a loom video of where createdAt and updatedAt isn't showing up for users postgres table in mock database : https://www.loom.com/share/c8d229b96aff4035bd737cb29709f28b

**Comment by abm17** [comment]
Created a PR for this: https://github.com/appsmithorg/cron/pull/35
