### ISSUE TITLE
[Task]: Add lint check for dangling `it.only` blocks in test files

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#23708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Dangling `it.only` skips  the other tests in that file and reduces our test coverage.

**Comment by me-heer** [comment]
Hi @rajatagrawal, can I work on this?

**Comment by rajatagrawal** [comment]
yes, you can pick this issue. @me-heer
