### ISSUE TITLE
[Bug] The default tab field does not get selected in property pane after deleting the current default tab

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2370]
Steps to reproduce:
1) Add a Tab Widget
2) Click on Property Pane 
3) Ensure TAB 1 is selected as Default Tab 
4) Now delete the Default Tab : Tab 1

Observation:
It is observed that the Tab widget Tab 2 is selected as Default Tab however it is not updated in the Tab widget Property pane.

Expectation.
When the current default tab is deleted and next tab is selected as default tab the field in the property pane must also be updated

![Screenshot 2020-12-28 at 11 49 16 AM](https://user-images.githubusercontent.com/71753653/103194473-ce50d480-4905-11eb-8924-e5c05b136c90.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac We should not update the value in the property pane by default. Overriding a user's explicit configuration would be very confusing especially when the user might write JS here.
