### ISSUE TITLE
[Bug]: Auto-layout Jank issues

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#23719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a few radio buttons in my app, and based on which radio button is selected a different input widget is shown - https://share.cleanshot.com/ZyXJsn86

If you see the GIF carefully, you will see that the input widget and date picker widget shifts a bit whenever the radio button selection is changed. This jank makes the UI look a bit bad. The logic to toggle between the input widget and date picker is very simple and is working perfectly.

I can confirm that this jank was not there before using auto layout. But after I started using auto layout, I am seeing this issue. Hopefully, this UI issue can be fixed.

### Steps To Reproduce

Try a similar setup as described in the GIF here,
https://share.cleanshot.com/ZyXJsn86

### Environment

Production

### Version

Cloud & Self - Hosted > 1.9.19

**Comment by aritraroy** [comment]
@narhzih Request you to correct the app version to `Appsmith Community v1.9.20.4`

**Comment by marks0351** [comment]
@aswathkk I believe this is happening coz of row gap issue. Can you confirm?

**Comment by Nikhil-Nandagopal** [comment]
Closing as we have a new layout builder
