### ISSUE TITLE
[Bug]: Application Welcome page/Application page not loading randomly

### ISSUE THREAD

**Issue by Vijetha-Kaja** [appsmithorg/appsmith#23713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

http://localhost/setup/welcome is not loading randomly in CI
![cypress-screenshot (30)](https://github.com/appsmithorg/appsmith/assets/119562824/d2c845af-c4d3-4fed-9b7e-c844ac9ca179)

### Steps To Reproduce

1. Navigate to http://localhost/setup/welcome

### Environment

Release

### Issue video log

https://github.com/appsmithorg/appsmith/assets/119562824/939d016e-871c-4501-826e-928f20e4c3b5

### Version

Self hosted

**Comment by Vijetha-Kaja** [comment]
[Logs](https://github.com/appsmithorg/appsmith/files/11561481/1_ci-test.ci-test.0.txt) to help debug

**Comment by Vijetha-Kaja** [comment]
Latest [run](https://cloud.cypress.io/projects/eyxvp8/runs/35154/test-results/2bcb39ce-0e71-4814-9259-d0b8c5c2ceb5) with above failure - [Logs](https://github.com/appsmithorg/appsmith/files/11592751/38_ci-test.ci-test.37.txt)

**Comment by Vijetha-Kaja** [comment]
Latest [run](https://cloud.cypress.io/projects/eyxvp8/runs/35203/test-results) with above failures - [Logs](https://github.com/appsmithorg/appsmith/files/11599911/2_ci-test.ci-test.1.txt)

**Comment by hetunandu** [comment]
There are two different scenarios in the failed runs. 
1. the welcome page does not come up at all (first step) 
2. the editor is loaded successfully (after login and create new application) but no app content is showing up. 

First seems flaky cause the server is not up. Second could be a concern but without logs not able to understand the problem. The error toast message in the video is empty as well.

**Comment by Vijetha-Kaja** [comment]
Latest [run](https://cloud.cypress.io/projects/n14p1y/runs/7459/test-results) with above failure - [Logs](https://github.com/appsmithorg/appsmith/files/11704651/29_Run.the.cypress.test.txt)

**Comment by Vijetha-Kaja** [comment]
Latest [run](https://cloud.cypress.io/projects/n14p1y/runs/7683/test-results/955fcf21-7f8e-4176-bb42-2610c5d9404d) with above failure - [Logs](https://github.com/appsmithorg/appsmith/files/11753364/30_ci-test.ci-test.29.txt)

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/36496/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D) with above failure

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/36613/test-results/5798d6e5-a04b-40b9-9e0e-0738a32131db) with above failure

**Comment by Vijetha-Kaja** [comment]
Recent [run](https://cloud.cypress.io/projects/eyxvp8/runs/36654/test-results) with above failure

**Comment by Aishwarya-U-R** [comment]
[Recent run](https://cloud.cypress.io/projects/n14p1y/runs/8115/test-results/5faf108a-17e2-4f68-8ac5-0d1b6697cde1) with this in CI today.

**Comment by akash-codemonk** [comment]
This hasn't happened in the last week so far. Please let me know if you find some test failing since last monday Jul - 10. @Vijetha-Kaja  @Aishwarya-U-R. 
Ideally this will have https://github.com/appsmithorg/appsmith/pull/25037#discussion_r1254330690 a stack trace displayed in the UI using which I should be able to debug further.

**Comment by ginilpg** [comment]
Moving back to product backlog. Will revisit this once we got more logs

**Comment by Aishwarya-U-R** [comment]
[Latest run with this failure](https://cloud.cypress.io/projects/n14p1y/runs/9037/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_campaign=view%20spec&utm_medium=failed&utm_source=slack)

**Comment by rohan-arthur** [comment]
@Aishwarya-U-R I see the last update is 2 months ago. is this still happening?

**Comment by Aishwarya-U-R** [comment]
Since this has been now fixed with some script updates, will further monitor this behavior in CI & re-open if needed.
