### ISSUE TITLE
[Bug] Unable to save API datasources

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2371]
### Steps to reproduce the behaviour:
1. Create an API
2. Select an existing data source
3. Edit the datasource
4. Update the headers
5. The save button is not enabled on the datasource page

https://user-images.githubusercontent.com/3897254/103197238-b2503180-490b-11eb-86e8-39331ff6c3c5.mov

**Comment by rishabhsaxena** [comment]
@Nikhil-Nandagopal Unable to reproduce this, the video isn't playing for some reason

**Comment by mohanarpit** [comment]
This happens only for older datasources without a value for field: `X-Appsmith-Signature`. 

In order to resolve this, we'll write a migration for all the past datasources to have the mandatory fields set with a default value.
