### ISSUE TITLE
[Bug]: Gap UI issue in the canvas

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#23721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am seeing an UI issue in the canvas. Here is the screenshot for it - https://share.cleanshot.com/CpzJ7Qwx

There is a gap between the sidebar right border and the canvas. If I use the app background as "white", then of course this issue is not visible. But if I use the app background as any other color then this gap is visible in preview and deploy mode as well.

This gap is present in both the left and right side of the canvas which makes the UI look a bit bad. It would be great if this issue can be fixed., of course,

### Steps To Reproduce

No steps really. 

### Environment

Production

### Version

Cloud & Self - Hosted 1.9.19

**Comment by aritraroy** [comment]
Looking forward to getting this issue fixed. This might be a small fix but will improve the look and feel of the deployed apps in appsmith.

**Comment by aritraroy** [comment]
@narhzih Please correct the app version to - `Appsmith Community v1.9.20.4`

**Comment by iSatVeerSingh** [comment]
Is this really an issue?
