### ISSUE TITLE
[Bug]: Error is not displayed when function is with same name

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#23720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JSfunction with same name should throw error

<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/80756091/d4299db0-21f1-4b44-9629-69883a70e0b1">

### Steps To Reproduce

1. Add two jsfunction with same name, it should throw error- This is not working

### Environment

Production

### Version

cloud

**Comment by bharath31** [comment]
@ohansFavour could you please investigate why a lint error isn't being thrown?

**Comment by ohansFavour** [comment]
@bharath31 this is a regression caused by the linting of individual properties of the JSObject, instead of the Object as a whole.

**Comment by bharath31** [comment]
@ohansFavour could you please run an RCA and fix this in the upcoming sprints?

**Comment by iSatVeerSingh** [comment]
@bharath31 @ohansFavour I want to work on this. Could you please help me regarding, where is the code for linting in codebase.
