### ISSUE TITLE
[Bug]: [Git Integration] Git SSH keys rotate every time the container restarts

### ISSUE THREAD

**Issue by rhuanbarreto** [appsmithorg/appsmith#23739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm deploying Appsmith Business through Azure Container Apps. I'm using persistent volumes in order to store the container data.

If for some reason (liveness probe, cluster upgrade, version upgrade), the container restarts, all SSH keys regenerate and therefore all git connections break.

### Steps To Reproduce

1. Deploy appsmith business v1.9.19 with a persistent volume
2. Connect an application to git
3. Update the image tag in appsmith to be v1.9.20
4. The application connection to git will be broken.

### Environment

Production

### Version

Business Self Hosted v1.9.20

**Comment by brayn003** [comment]
Hi @rhuanbarreto, are you still facing this issue?
I am unable to replicate this with the latest version. Would be happy to get on a call to understand the issue better 
You can schedule the call here - https://calendly.com/rudra-appsmith/30min

**Comment by rhuanbarreto** [comment]
I've been hosting appsmith through K8S, so this issue didn't appear anymore. You can close.
