### ISSUE TITLE
[Bug]: MSSQL Prepared Statement fails with unclear error - Incorrect syntax near '@P0'

### ISSUE THREAD

**Issue by micarner** [appsmithorg/appsmith#23742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using an input text field where a user can type in a number and then a query will execute using that number. I've set a default value (10) and it appears to be using that when I try to test the query. However, when I run the actual query I get this error:

```
Your query failed to execute:
Incorrect syntax near '@P0'.
[SQLSTATE: S0001]
```

This is the query I'm using:

```
select DISTINCT TOP {{MaxResultsInput.text}} jobid,a.createdate from jobsubmission a, Submissions b
where b.subtypeid = 257
and a.submid=b.Submid
```

I'm using prepared statements by default, but when I disable them the query goes through without issue.

### Steps To Reproduce

1. Add a Microsoft SQL datasource
2. Using that datasource, create a query with a parameter in the SELECT statement such as `SELECT TOP <param>...`
3. Attempt to execute that query

### Environment

Release

### Version

Self Hosted - 1.9.20.4

**Comment by micarner** [comment]
Upon further review, this error is from the JDBC because prepared statement parameters cannot be used in the SELECT statement (https://stackoverflow.com/a/40301857). At this point my question is:

Should Appsmith attempt to provide better context for this error to the non-user?

**Comment by sumitsum** [comment]
Creating a new feature request to track it: https://github.com/appsmithorg/appsmith/issues/24555
