### ISSUE TITLE
[Bug]:  "Failed to execute actions during page load" error is displayed When user imports Json app to rewrite existing app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#23744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 "Failed to execute actions during page load" error is displayed When user imports Json app to rewrite existing app
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/63203dd3-a383-4067-ae7e-861c9caf8cdc">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/72e39b50-d3ef-4869-b2f7-c93a1437004a">

### Steps To Reproduce

1. Create a new app and generate a crud page name it as app1
2. now  export the app1
3.  now in same org create a new app
4.  try to import the app1 
5. the app gets imported but the page reload doesn't happen and the error message will be displayed

### Environment

Release

### Version

v.1.9.20.5

**Comment by infinitetrooper** [comment]
@RakshaKShetty  - can you share the JSON or the app URL to this?

**Comment by nidhi-nair** [comment]
Closing as stale, please re-open with a fresh reproduction and details if required.
