### ISSUE TITLE
[Bug]: Empty space at the start of Top + Stacked navigation's page list

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#23751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Noticed the issue post ADS v2 changes. Attaching a screenshot.

![CleanShot 2023-05-26 at 12 07 12@2x](https://github.com/appsmithorg/appsmith/assets/22471214/4e5669ef-610f-4868-9efc-c04f9599dafe)

### Steps To Reproduce

1. Create an app.
2. Add two pages.
3. Observe the empty space at the left/start of the pagelist.

### Environment

Release

### Version

Appsmith v1.9.20.5-SNAPSHOT

**Comment by harshitpandey0426** [comment]
Spacing should be similar to prod env right?
![image](https://github.com/appsmithorg/appsmith/assets/54776298/c2920c36-3f9f-4b9a-a618-bc617c0f1c08)
