### ISSUE TITLE
[Task]: In property pane, replace box-shadow property icon with text

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#23760]
![Untitled (1).png](https://images.zenhubusercontent.com/620dea39dbc0b448e733d8e0/273e5cda-ae59-44db-b4e4-d50cd38d62b6)

Replace the icon with small, medium & large text.

**Comment by sheoranabhishek** [comment]
@rohitagarwal88 Is it expected to look something like : 
![image](https://github.com/appsmithorg/appsmith/assets/53663443/aa2cb700-7142-4a89-b334-364af9bfddfe)

And the hover should say 'Small', 'Medium' and 'Large'.

**Comment by harshitpandey0426** [comment]
@sheoranabhishek are you working on this? or this is the proposed UX?

**Comment by sheoranabhishek** [comment]
I'm working on this, also this is the proposed design.

**Comment by rohitagarwal88** [comment]
@sheoranabhishek thanks for picking up the issue. Please check the latest UI changes on https://release.app.appsmith.com.
The box-shadow property will look like as in the screenshot & Tooltip is not needed.
<img width="274" alt="Screenshot 2023-05-26 at 2 48 55 PM" src="https://github.com/appsmithorg/appsmith/assets/890915/80dc4c03-da2b-4107-90ec-1d84ec4e4226">

**Comment by harshitpandey0426** [comment]
@rohitagarwal88 
Opened a PR, please let me know if the code changes look good to you.

**Comment by sheoranabhishek** [comment]
@rohitagarwal88 Great ! The changes look clean. I have suggested some improvement. Please have a look.

**Comment by harshitpandey0426** [comment]
@rohitagarwal88 any update on this?

**Comment by rohitagarwal88** [comment]
Sry @harshitpandey0426 for the delay. @aswathkk will review the changes.

**Comment by Sripriya93** [comment]
QA completed, moving to done.
