### ISSUE TITLE
[Bug]: Datasource review page is broken when user edits the datasource name 

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#23775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user saves the data source and tries to edit the data source name from the review page it is observed that the config on the review page is lost.

### Steps To Reproduce

1) Select a data source
2) Add required fields
3) Save the data source 
4) The user is navigated to the review page 
5) Edit the name of the data source
and observe that the user is not displayed 

https://www.loom.com/share/4ccca530572b484bbb3671e17a493b7d

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
Note: This needs to be tested across all datasources.

**Comment by sharanya-appsmith** [comment]
Env tested: https://release.app.appsmith.com/
Added all available data sources, edited the name in the review page. All details about the data source is available for all the data sources.
