### ISSUE TITLE
[Bug]: Appsmith Login Screen when installed using AWS AMI

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#23774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Appsmith Login screen looks different when installed using AWS AMI. The login screen should be same irrespective of installation type.
![image](https://github.com/appsmithorg/appsmith/assets/99252011/a157fd2f-f589-4d72-b338-1f15b4f60198)

### Steps To Reproduce

- Install Appsmith using [AWS AMI installation ](https://docs.appsmith.com/getting-started/setup/installation-guides/aws-ami)steps.
- The login screen is displayed but it is not having the same look and feel.

### Environment

Production

### Version

NA

**Comment by sum35h** [comment]
This screen is not the one that's seen exclusively on BE. The AMI essentially runs the same Appsmith images on docker so it will be the same as other type of installation instances.
