### ISSUE TITLE
[Task]: Refactor sticky canvas Arena to avoid unnecessary forced reflow

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#23777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Refactor sticky canvas Arena to avoid unnecessary forced reflow. This is done by enabling the canvas to observe only when required i.e, only when user is using,
- [ ] Drag to select
- [ ] Dragging widgets

**Comment by somangshu** [comment]
@Sripriya93 tagging you here as discussed before

**Comment by Sripriya93** [comment]
QA done. Working as expected. @somangshu @rahulramesha
