### ISSUE TITLE
[Bug] CE : On placing the Map Widget the page crashes 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2378]
Steps to reproduce:
1) Add a Map widget 
and observe the map does not load 
2) Add any widget 
and observe the page crashes 

Expectation:
The page should not break 

Video:
https://www.loom.com/share/50c638c17182497aae0a6000e9aa5212

**Comment by Nikhil-Nandagopal** [comment]
@prapullac does this still occur?

**Comment by prapullac** [comment]
@Nikhil-Nandagopal : This does not exists anymore. Hence closing the issue
