### ISSUE TITLE
CLI args to run cypress locally in run mode does not work from TestAutomation.md

### ISSUE THREAD

**Issue by harshitpandey0426** [appsmithorg/appsmith#23798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The command written in TestAutomation.md doc seems to be deprecated as in latest version of cypress there is no Integration folder.

### Steps To Reproduce

Goto https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/TestAutomation.md
Check this
> For run mode, you can use CLI args. Example: To run the entire Regression_TestSuite, use $(npm bin)/cypress run --headless --browser chrome --spec "cypress/integration/Regression_TestSuite/*/*"

### Environment

Release

### Version

Cloud

**Comment by harshitpandey0426** [comment]
I think the command should be updated to 
> $(npm bin)/cypress run --headless --browser chrome --spec "cypress/e2e/Regression/*/*"
Let me know if this make sense, I will update the doc.

**Comment by harshitpandey0426** [comment]
Hi @somangshu, does this change make sense to you?

**Comment by somangshu** [comment]
Tagging relevant folks from the internal team.
@Aishwarya-U-R @Parthvi12 would you be able to help here?

cc @rajatagrawal

**Comment by Parthvi12** [comment]
@harshitpandey0426 Thanks for contributing, please go ahead with your change.

**Comment by Parthvi12** [comment]
@harshitpandey0426  We have also moved away from `app/client/cypress.json` to `app/client/cypress.config.ts`. Will you be able to update that as well? Thanks!
