### ISSUE TITLE
[Bug]: Code selection is broken when the width of property pane is larger than default

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#23796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Code selection feature breaks when a property pane is resized to a larger width.

Happening on release.app.appsmith.com, not on prod. May be related to ADS 2.0 changes

### Steps To Reproduce

1. DnD a chart widget
2. Choose Custom Chart
3. Select/Double click on any parameter passed in the property. Notice that it is selectable.
4. Increase the width of property pane.
5. Try to select/double click on any value mentioned in the pane. Notice that it is not selectable.

Expected behavior : It should be selectable.

### Environment

Production

### Issue video log

https://www.loom.com/share/a20bb0fb5e7a4b859f6fb0ebf65286c3

### Version

Cloud/ADS 2.0

**Comment by somangshu** [comment]
What is expected here is the property pane size is really small, how should the prettifying work?

**Comment by rajatagrawal** [comment]
@somangshu @rohitagarwal88 

Found a repro for this bug.

1. Dnd a chart widget on prod. Choose custom fusion chart
2. Notice that in custom fusion chart property pane field, there are no extra lines at the end of the text box.
3. Increase the width of the property pane for custom fusion chart.
4. Notice that there are blank extra lines at the end of custom fusion chart field.

Loom video : https://drive.google.com/file/d/1qiQX2U6M-oaqJ1dqCzjRhF7a9J1r9tuC/view?usp=drive_link
