### ISSUE TITLE
[Bug][List]Unable to place widgets and see drop targets when widget is dragged to a blank area (increase the height of list item and try dragging and releasing widget in the blank space )in List item container

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#23815]
[www.loom.com/share/0c41037da9ab4a1885bae9f3bb8adefd](http://www.loom.com/share/0c41037da9ab4a1885bae9f3bb8adefd)

**Comment by kamakshibhat-appsmith** [comment]
Marking it as high priority for now as it a natural user behaviour to hold the widget slightly away from the drop-target . @aswathkk

**Comment by Sripriya93** [comment]
https://images.zenhubusercontent.com/275993885/100cf470-f7ab-4e70-9eb3-f6a03e0ee2a8/untitled_application_65___editor___appsmith___4_july_2023.mp4

"Convert to Auto layout" option isnt available
Also if we check in Old apps we are still able to see the issue.
