### ISSUE TITLE
[Bug]: Importing app from git, shows uncommitted changes

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#23816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app containing datasource and query is imported from git, it shows uncomitted changes in git sync modal
<img width="1440" alt="Screenshot 2023-05-29 at 12 09 29 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/224b2cd4-8a37-429c-ab0c-3ef8e17ef0e8">

On committing it changes the gitSyncId: 
<img width="1391" alt="Screenshot 2023-05-29 at 12 16 58 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/3bacffbb-74b6-476d-a620-498d20501a43">

### Steps To Reproduce

1. Create an app and connect it to git
2. Add datasource and query, commit changes
3. Import the app from git
4. Open git sync modal and observe git sync modal shows uncommitted changes.

### Environment

Release

### Version

Release

**Comment by AnaghHegde** [comment]
This is because of the multiple environment changes. Can you commit the changes and share the diff here?
