### ISSUE TITLE
[Bug]: `inputText` for Inputs within List widget not accessible fro

### ISSUE THREAD

**Issue by prithweedas** [appsmithorg/appsmith#23814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to create a dynamic form that creates `n` inputs depending on data from a List of Labels.

However, when I try to access the input values it just shows undefined, and `List.items` shows that the `Input` property is an empty object
<img width="1031" alt="Screenshot 2023-05-29 at 11 46 14 AM" src="https://github.com/appsmithorg/appsmith/assets/24864756/368d724f-8a61-45ef-b02b-65d64f7808d8">

I can see in the logs that the `inputText` for that widget was updated but still not able to access it
<img width="448" alt="Screenshot 2023-05-29 at 11 49 05 AM" src="https://github.com/appsmithorg/appsmith/assets/24864756/17727944-bab6-4f97-9f69-b7b4d91803e8">

### Steps To Reproduce

1. Create a List widget
2. Add a list of strings as data
3. Add an Input Widget within the List Container
4. Add a Text widget
5. Add the following as `text` for the Text widget `{{JSON.stringify(List1.items)}}`
6. Try typing something in the inputs, the values in the text widget will not change

### Environment

Production

### Version

Self Hosted - v1.9.3.1

**Comment by somangshu** [comment]
Works for me as expected. 
https://github.com/appsmithorg/appsmith/assets/11089579/6cdd7f4e-c533-449f-bf20-2a843f4caa15

@prithweedas can you try using `List1.selectedItem` instead and see if it resolves the problem for you. 
I am assuming your use case is that, when you select a list item, the selected value shows up on the text widget. 
Closing for now, Ill reopen if I have misunderstood the problem
