### ISSUE TITLE
[Task] Add documentation for Widget property setter

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#23826]
- [ ] Add docs with example of widget property setter method
    - [ ] Explain async nature of it and relation with appsmith's reactivity
    - [ ] validation error example for `setDisabled`, `setVisibility`

**Comment by danciaclara** [comment]
@Rishabh-Rathod could you provide more information around what this is. Are you going to share a draft as well? Thanks

**Comment by Rishabh-Rathod** [comment]
@danciaclara This is the draft document for the widget property setters https://www.notion.so/appsmith/Widget-property-setters-f5f42abd1ee24ddcb582cd7648ce9f8c

Please let us know, if more information is needed.
