### ISSUE TITLE
[Task]: Measure Autocomplete Effectiveness

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#23838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

| Event | Additional properties to track | Existing properties to modify |
|--------|--------|--------|
| AUTO_COMPLETE_SELECT | `query`, `selectedResultIndex`, `selectedResultType`, `isBestMatch` | rename `searchString` -> `selectedResult`
| AUTO_COMPLETE_SHOW | `query`, `numberOfResults` |  --  |

Definitions: 
1. `query`: Search query typed by the user that triggered the autocomplete popup to show up
2. `selectedResultIndex`: Index of the autocomplete result that was selected 
3. `selectedResultType`: Type of the autocomplete result that was selected (eg: Function, Array, Object, etc..)
4. `isBestMatch`: Boolean value to indicate if the selected autocomplete result was a part of Best Match suggestions
5. `numberOfResults`: Number of results shown in the autocomplete popup

**Comment by bharath31** [comment]
@Druthi the `query` property is empty when the events are fired from JSObjects. Could you please fix this?

**Comment by Druthi** [comment]
Will check

**Comment by bharath31** [comment]
@Druthi let's also handle the [query param issue](https://www.loom.com/share/308373e570f746bc9d2b8c713406e716?sid=91439f09-0a69-4646-92d1-272f070eaf29) as a part of this
