### ISSUE TITLE
[Bug]: Issues related to GS Datasource 

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#23840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1) Edit datasource name is not functional
2) Edit and add query is not functional

### Steps To Reproduce

Steps to reproduce:
1) Authorise the GSheet datsource 
2) Click on Edit button 
and observe the button is not functional
3) The Add Query button is inactive and not functional
4) edit data source name is not displayed

### Environment

Release

### Version

cloud

**Comment by AmanAgarwal041** [comment]
RCA : When we authorize gsheet ds, then there is a request `/api/v1/saas/64785f2b14130308b062d88a/token?appsmithToken=${appsmithToken}` which is returning datasource object with userPermissions key as empty array after the authorisation is complete, which is resulting in the disabled edit and add button. This is a server side change.
