### ISSUE TITLE
[Bug]: Radio Group options are not aligned with the label

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith#23847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the label is on the left of the radio widget, the options are aligned to the top of the container. 

I expect the options to be in line with the label.

<img width="373" alt="image" src="https://github.com/appsmithorg/appsmith/assets/101155659/94f5bbb8-9972-444d-9cf3-8f22486bb928">

### Steps To Reproduce

1. Drag a radio widget to the canvas.
2. Set the label position to `left`.
3. Observe that the options are not in line with the label.

### Environment

Production

### Version

Cloud v1.9.20-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_aq764)

**Comment by iSatVeerSingh** [comment]
@Nikhil-Nandagopal @AS-Laguna @somangshu Please take a look at my PR.

**Comment by somangshu** [comment]
@iSatVeerSingh thanks for raising a PR, we are looking into the change, please stay updated on the PR with any comments from the moderators.
