### ISSUE TITLE
[Bug]: Branch list in git sync modal is not scrollable 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#23858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For git connected application, the branch list dropdown under merge section is not scrollable.
<img width="1440" alt="Screenshot 2023-05-30 at 12 37 41 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/278c7bd6-ed97-4ab0-8610-554d6c262780">

### Steps To Reproduce

1. Go to git connected app which has more then 4/5 branches
2. Open git sync modal, go to merge tab
3. Click on the select branch drop-down and try to scroll
4. Observe it is not scrollable

### Environment

Release

### Version

Release

**Comment by shadabbuchh** [comment]
Verified in release.

https://github.com/appsmithorg/appsmith/assets/39921438/f5147075-1b38-477b-9472-a47a5cc3443e
