### ISSUE TITLE
[Bug]: Text alignment issue on properties having both name and symbol

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#23859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The properties containing both name and symbol in the dropdown are misaligned and text is not in proper margin.
It is observed in Divider widget's style and cap property

![image](https://github.com/appsmithorg/appsmith/assets/95341241/ffc0a628-33ae-4934-a355-8274d6ce9686)

### Steps To Reproduce

1. Drag & Drop Divider widget
2. Navigate to Style tab in property pane
3. Observe the alignment of text and symbol is not proper in Style & Cap property

### Environment

Release

### Version

Cloud / Release

**Comment by iSatVeerSingh** [comment]
I think this issue happening in the "Select" component in design system.
