### ISSUE TITLE
[Bug]: Appsmith Logo has gotten smaller 

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#23853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I login to my account I can see that Appsmith logo has been resized and it looks too small.

### Steps To Reproduce

1. log in
2. look at the top left corner for the logo
<img width="274" alt="Screenshot 2023-05-30 at 07 01 50" src="https://github.com/appsmithorg/appsmith/assets/81744497/a873d9e6-b344-47ee-a1ef-8275fff21d56">

### Environment

Production

### Version

Cloud v1.9.20

**Comment by dhruvikn** [comment]
Related issue - https://github.com/appsmithorg/appsmith/issues/23184

@berzerkeer @abhvsn could you please take a look?

PS - [Here's a slack thread](https://theappsmith.slack.com/archives/C02GAUE9P5H/p1683691924190819) where a conversation wrt this issue happened.

cc: @dilippitchika @somangshu

**Comment by abhvsn** [comment]
@dhruvikn I can see the expected size on [release](https://release.app.appsmith.com/applications), is there anything that I can help you with? 
<img width="641" alt="Screenshot 2023-05-30 at 5 14 26 PM" src="https://github.com/appsmithorg/appsmith/assets/41686026/85c06638-36b8-4755-9d72-dfb594e0d24d">

**Comment by dilippitchika** [comment]
Closing this, thanks @abhvsn the issue was raised because of the current size in production
