### ISSUE TITLE
[Bug]: In DS Query-  Linting shows an error when the widget is added after the query is created

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#23868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a query referencing a widget, add add this widget later onto the canvas, the binding still shows up with the red tag underneath the widget name pointing out that widget does not exist, though the values/data of the widget can be seen on hover.``

### Steps To Reproduce

1. Create an S3 ds and create a new query [Create a new file query maybe]
2. Fill in the required fields
3. In content, enter {{FilePicker1.files[0]}}
4. Now go to canvas and add the file picker widget which is named FilePicker1
5. Go back to the query screen and note that the binding still shows up as an error and does not pick the FilePicker, though its data is evaluated properly on hover.

<img width="520" alt="Screenshot 2023-05-30 at 5 13 14 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/e82dfde4-cca5-4098-8261-c9b74270e02e">

<img width="823" alt="Screenshot 2023-05-30 at 5 08 26 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/4a3cc50d-b872-4e12-9471-3d7b22b70976">

### Environment

Production

### Version

Cloud

**Comment by ohansFavour** [comment]
This is related to https://github.com/appsmithorg/appsmith/issues/24194, and will be fixed [here](https://github.com/appsmithorg/appsmith/issues/24194)
