### ISSUE TITLE
[Bug]: Icon widget button color disappears on JS toggle

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#23866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Icon widget button color disappears on JS toggle.

### Steps To Reproduce

1. D&D Icon widget
2. In property pane under Styles for `Button Color` property, click on JS toggle twice

### Environment

Production

### Issue video log

https://www.loom.com/share/191d39060e7647bbaa6180d2fa66c3e9

### Version

Cloud

**Comment by ramsaptami** [comment]
fixed on anvil
