### ISSUE TITLE
[Bug]:When user tries to remove the user from user dropdown the hover state is missing

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#23879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user tries to remove the user from user dropdown the hover state is missing
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/b08092df-8f75-4046-8d14-81182aac4d0b">

### Steps To Reproduce

1. go to https://ee-1544.dp.appsmith.com
2. go to admin setting
3. go to audit logs
4. now select multiple users from user dropdown
5. Now try to remove it by clicking on close icon the hover state is missing 

### Environment

Release

### Version

v1.9.20.5

**Comment by riteshkew** [comment]
Fixed by ADS
