### ISSUE TITLE
[Task]: Make the icons load dynamically so that we don't make all the icons part of the bundle

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#23876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In design system, we are exporting all the icons, this will put all the icons in the bundle and most of the icons are never used.
We should have a wrapper around icons and load them on demand.

**Comment by rohitagarwal88** [comment]
@SatishGandham : Should we put on hold or any plan to work on it?

**Comment by SatishGandham** [comment]
There is already a pr for it, we should test that and merge.
https://github.com/appsmithorg/design-system/pull/491/files

Above has to be tested here
https://github.com/appsmithorg/appsmith/pull/24382

**Comment by rohitagarwal88** [comment]
@albinAppsmith / @shadabbuchh : can we please test it? If you have any queries feel free to ask?

**Comment by albinAppsmith** [comment]
This is completed in https://github.com/appsmithorg/appsmith/pull/24503
