### ISSUE TITLE
[Bug]:  Inconsistent Example and Missing Input Field Name

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#23892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, the Appsmith example does not work as initially indicated. Instead of `[{ "fields": { "name": "Test" }}]`, the example should be `{"records":[{"fields":{"name":"Test"}}]}`. This confusion causes users to encounter an error when they try to use the provided example.

Furthermore, in addition to all of this, this input field does not have a name as shown in this image.
![image](https://github.com/appsmithorg/appsmith/assets/114161539/41c672cd-396d-4861-9e91-846ca2bdb7f6)

### Steps To Reproduce
1. Create a new data insertion query.
2. In the content section, add the example mentioned above for the input: `[{ "fields": { "name": "Test" }}]`.
3. Execute the query and observe the failure.
4. Now, modify it in the following way: `{"records": [{ "fields": { "name": "Test" }}]}`.
5. Execute the query again and observe the successful outcome.

### Environment

Production

### Version

Cloud Appsmith v1.9.20-SNAPSHOT

**Comment by sumitsum** [comment]
I have updated it so that the original example should work as it is now ie. `[{ "fields": { "name": "Test" }}]` should work on release.
