### ISSUE TITLE
[Bug]: No validation happens when there are function names of the same name in an object

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#23919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Duplicate function name isn't validated inside an object

![image](https://github.com/appsmithorg/appsmith/assets/79509062/cae76022-365e-4d92-aa90-4621e0c7c775)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/2dd158f0-d3f4-412d-89cb-6f41d4cc829b)

### Steps To Reproduce

1. Add an object
2. Add a second myFun1 to the object and observe there is no validation error
3. Run `myFun1` and observe only the last occurance of myFun1 is executed

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
duplicate of #23720
