### ISSUE TITLE
[Bug]: Tab widget's title content is overflowing on the property pane when the text is large.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#23910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Tab's title content is overflowing on the property pane when the text is large.

![image](https://github.com/appsmithorg/appsmith/assets/109572422/f64dcd53-b0c6-47b6-b3f4-05df4c3275d0)

### Steps To Reproduce

1. Add a Tabs widget
2. Edit the tab's title with a long text
3. Notice that overflow of content is seen thus overlapping the options next to it

### Environment

Release

### Version

Release

**Comment by shadabbuchh** [comment]
Verified in release.
<img width="295" alt="Screenshot 2023-06-09 at 4 56 45 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/d15d801a-9456-4239-9087-c0bc56d13156">
