### ISSUE TITLE
[Bug]: Fail to add email server

### ISSUE THREAD

**Issue by durian530** [appsmithorg/appsmith#23937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add email server, I got a exception
![企业微信截图_16856003733966](https://github.com/appsmithorg/appsmith/assets/91531396/122f9664-3963-4669-a7ed-3ffd2e3edcb7)
![企业微信截图_16856004541038](https://github.com/appsmithorg/appsmith/assets/91531396/d2c9c169-ded9-4359-93d7-336d26537596)

### Steps To Reproduce

1. Go to **Admin Settings**->**Email**
2. Add email server info
3. Click **SEND TEST EAMIL**

### Environment

Release

### Version

Self Hosted - v1.9.20.4

**Comment by durian530** [comment]
![image](https://github.com/appsmithorg/appsmith/assets/91531396/0123bdb7-4776-4553-892c-0f507cab33d3)
I suppose that ssl was not configured, maybe following sentence can solve the problem:
` props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");`

**Comment by sharat87** [comment]
@durian530, unfortunately, implicit TLS for SMTP is currently not supported. Only `STARTTLS` (or explicit TLS) is supported today. Is it possible to use switch to port 80, which supports explicit TLS, according to https://www.alibabacloud.com/help/en/directmail/latest/smtp-service-address?
