### ISSUE TITLE
[Bug]: MySQL SELECT query doesn't work if there is any JSON data type with NULL as the value. ​

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#23930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a MySQL database and inside it a table that has a column that
stores data of JSON type, some of it is *NULL*. When executing a
*SELECT* query to fetch the records from said table, I get the
*java.lang.NullPointerException* error. On the other hand, when I run
the same query from DBeaver for example, it succeeds.
​
A workaround could be to cast the *NULL* values at the moment of doing
the SELECT query like this:
​
```
SELECT
    column1,
    column2,
    columnN,
IF(<<columnWithNullValues>> IS NULL, 'N/A',
<<columnWithNullValues>>) <<columnWithNullValues>>
​
FROM
    udgroup_req_payload;
​
```

### Steps To Reproduce

1.  Create a MySQL Database and a table inside it with some columns, one
    of those must have JSON data type.
​
```
CREATE TABLE test_table(  
    column1 int,  
    column2 varchar(255),  
    column3 json,  
);
```
​
2.  Store some records. Keep in mind that some of those must have the
    NULL value in the column that stores the JSON data.
​
```
INSERT INTO test_table (column1, column2, column3)  
    VALUES (1, "Jhoe", NULL),
​
    VALUES (2, "Doe", {"key":"value"}),
​
    VALUES (3, "Fran", NULL);
```
​
3.  On Appsmith, connect to the Database you created before, run a query
    like the following and notice the mentioned error:
​
```
SELECT * FROM test_table
```
​
Update the column whose data type is JSON by inserting values that
conform to the format *{"key":"value"}* for all records. Run the
*SELECT* query from the previous step and note that the response is
successful.
​
```
UPDATE test_table SET column3 = '{"key":"value"}'  
SELECT * FROM test_table
```
​

### Environment

Production

### Version

Cloud: Appsmith v1.9.20-SNAPSHOT  Self:Hosted: 1.9.17/ 1.9.20.4

**Comment by sumitsum** [comment]
Closing in favour of https://github.com/appsmithorg/appsmith/issues/27645
