### ISSUE TITLE
[Bug]: Navigation failure on sniping mode

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#23943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I enter sniping mode, I sometimes remain on the Query page instead of navigating to the canvas. 

### Steps To Reproduce

https://theappsmith.slack.com/archives/C054MBKNUSC/p1685608911170899

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
sniping has been removed now, so this issue is not valid anymore
