### ISSUE TITLE
[Bug]:Hyperlink text box doesn't support some domains (similar to #23576)

### ISSUE THREAD

**Issue by delattre** [appsmithorg/appsmith#23951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When importing a hyperlink from a Google Sheet, one would expect all domains to be supported by default. However, .life domains failed to work.  This seems to be similar to issue #23576 

### Steps To Reproduce

1. Connect to a Google Sheet resource with a column of website links
2. Create a table widget of the google sheet and make sure to add the column of website links.
3. Make sure the column type is a URL
4. Create a text widget pointing to the website link when you click on a row ID
5. For common domains the link in the text box will be a clickable URL, for .life is will not

### Public Sample App

https://app.appsmith.com/app/untitled-application-1/page1-641b1ffc53066d1510cc4946

### Environment

Production

### Version

Cloud

**Comment by delattre** [comment]
Make sure to click on any column besides the URL enabled columns to change the text box entry.
Clicking on row 4 will show the issue.

**Comment by delattre** [comment]
Hi, any progress on this?  No rush, just wanted to follow up :)
Thank you!

**Comment by Nikhil-Nandagopal** [comment]
Just checked and this seems to be working so I'm closing this issue now
