### ISSUE TITLE
[Bug]: Change in table data only shows columns that are common between the query when in deploy mode

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#23969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever there is a change in table data, columns that are common between the previous and the current table data is displayed. This behaviour is observed in deploy mode.

The expected behaviour is that the change in query/table data should reflect the correct columns in table when in deploy mode.

Discord query link: https://app.frontapp.com/inboxes/teams/folders/15690316/archived/79396567564

### Steps To Reproduce

1. Dnd a table widget and two buttons
2. Bind the table wdiget's tableData property with a JS expression like this: `{{appsmith.store.test === '0' ? query1.data : query2.data}}`
3. Change the appsmith store variable `test` when either of the above two buttons are clicked.
4. Deploy the app.
5. Change the data of table by click on these buttons.
6. Refresh the page.
7. Observe that on click of buttons again the above issue occurs

### Environment

Production

### Version

Cloud

**Comment by antlevy** [comment]
Hi, I got the same problem in one of my app. I have a self-hosted v1.9.20.4.
I tried a workaround but I didn't find any good way to avoid the problem.

I made an simple app reproducing the bug if this can helps : 
https://appsmith.dev.scalnyx.ovh/app/testing-table-refresh/page1-6478911a5a5ef969be838982

**Comment by ItsiW** [comment]
This is quite a problem for our application that requires a lot of pivot tables, so rows/columns are distinct for each page. Currently we have to work out of edit mode

**Comment by ItsiW** [comment]
https://www.loom.com/share/7a9a6c7e738d43a797d62052871a8c42

**Comment by somangshu** [comment]
@keyurparalkar why is this issue added to the sprint at the end of it?
Also how did we decide to pick this up without understanding the priority?

**Comment by keyurparalkar** [comment]
@somangshu I have marked this as High priority issue since it affects the the table in deployed mode.

**Comment by somangshu** [comment]
is it a release blocker? Please add the label if that is the case

**Comment by keyurparalkar** [comment]
No @somangshu its not a release blocker
