### ISSUE TITLE
[Feature]: Scrolling window alternative to pagination for large SQL data-sets

### ISSUE THREAD

**Issue by adrian-stephens** [appsmithorg/appsmith#23973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The current pagination method is awkward when working with large datasets,  but where page boundaries obscure the application's logic.  For example my app groups articles with printed pages.   I need to scroll so that the articles on a printed page are visible together.   If I used pagination,  a page boundary might occur in the middle, and make it hard to see them together.
I envisage the system maintaining a scroll window and prefetching data immediately before and after.  Data would be presented with scroll bars within a  table. The traditional "run" would be replaced by an "invalidate" that told the framework it needed to re-fetch data.

### Why should this be worked on?

Pagination doesn't fit well when the data viewed might have local coherence (i.e. all the articles on a printed page) and a pagination page boundary just happens to occur in the middle, thereby destroying the visual coherence of the data.    The alternative currently supported is just to scroll the entire data-set,  but this introduces unnecessary delays when there is a lot of data,  because time is spent transferring data that might never appear on screen.

**Comment by Nikhil-Nandagopal** [comment]
We're tracking this feature here #2896
