### ISSUE TITLE
[Bug]: MySQL Query Error: `java.lang.NullPointerException` When Data Type Is JSON and Column Has Null Value

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#23976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user tries to run a simple MySQL SELECT query and it returns a java.lang.NullPointerException Error. The table exists in the datasource. The same error persists with prepared statement On or Off. 
The error happens if the data type of attribute is JSON and there is `null `value in that column.

### Steps To Reproduce

Run a MySQL SELECT query on a table with data type of attribute is JSON and  `null `value in that column.

### Environment

Production

### Version

Appsmith Community Edition v1.9.17

**Comment by ame-appsmith** [comment]
Here is a **workaround** provided by Felix:
When doing the `SELECT * FROM users` query, we get the mentioned error, but if said column has values in the `{"key":"value"}` format, the query is successful.
![front_attachment](https://github.com/appsmithorg/appsmith/assets/101268423/dfa1620e-43f9-4422-9e7e-8a2eae708f27)
In this way, since it is not possible to assign default values to columns of type JSON, a workaround could be to cast the NULL values at the moment of doing the `SELECT` query like this:

```SELECT column1, column2, columnN, IF(<<columnWithNullValues>> IS NULL, 'N/A', <<columnWithNullValues>>) <<columnWithNullValues>> FROM users;```

**Comment by sumitsum** [comment]
Closing in favour of https://github.com/appsmithorg/appsmith/issues/27645
