### ISSUE TITLE
[Bug]: Airtable "Create Records" shows wrong example for "Records" field

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [appsmithorg/appsmith#23983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently the following is shown for the Airtable "Create Records" integration:

![Screenshot 2023-06-02 at 10 05 48](https://github.com/appsmithorg/appsmith/assets/48183213/559d6587-123d-4fe3-af81-2811274decad)

however when sending such a body:

```json
[
  { 
    "fields": { 
      "name": "Test" 
    }
  }
]
```

a 422 error is returned. The correct body would be:

```diff
+{ 
+  "records": {
[
  { 
    "fields": { 
      "name": "Test" 
    }
  }
]
+}
```

either the `records` key should be added automatically or the text should be updated

### Steps To Reproduce

1. Add a Airtable data source (configure the table to have a `name` field)
2. add a "Create Records" query
3. invoke it with the example body

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
thank you for reporting this issue. We are tracking this in #23893 so closing this one
