### ISSUE TITLE
[Bug]: CI: Reconnect modal appears again on skipping to application.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#24016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In CI, reconnect modal appears again after skipping to application, making cypress test flaky.
https://cloud.cypress.io/projects/eyxvp8/runs/35519/test-results/5491140a-bec6-4d37-90d0-56c9a3c011e9/video

### Steps To Reproduce

This issue is observed on CI and is not always reproducible 
Run to refer: https://github.com/appsmithorg/appsmith/actions/runs/5173059958

### Environment

Release

### Version

Release

**Comment by akash-codemonk** [comment]
Able to repro locally. The url for the skip button can be empty at times, causing it to reload the same page on click.

**Comment by Vijetha-Kaja** [comment]
Gave a script fix for now, will reopen the bug if we see this issue again
