### ISSUE TITLE
[Feature Request] Allow for installing in docker without using the install script.

### ISSUE THREAD

**Issue by laundmo** [appsmithorg/appsmith#2402]
## Summary
There should be a easy way users can bypass the install script if they dont need all the features provided by it.

## Motivation

The documentation only provides info on the setup using the install script, which in some cases wont be possible.
For example, if the server is already running a reverse-proxy on ports 80/443 that will route appsmith traffic, the following parts of the script are redundant or can cause issues: port check, certbot, domain setup, and ssl certificate creation.

## Additional Context

Ideally the required setup steps like database initialization would be run inside the container, and a example docker-compose/env file would be provided that can be edited by a user.

Related to:
- #1903

**Comment by sumitsum** [comment]
Copying from discord discussion by @laundmo : 
```
it seems that should work, i still dont like having to use a shell script that does the following:
- interact with host services
- attempt to start containers before i had the chance to edit their docker-compose config
- sends telemetry even after i opt out of it
```

**Comment by laundmo** [comment]
In this comment im going to add all the issues i had trying to set up without the install script:
 - nginx.conf contains env vars that need to be added by templating (bad because: cant change them later, fix: include substitution in container CMD)

**Comment by areyabhishek** [comment]
We have more people asking for this. Can we start working on this? 
<img width="656" alt="Screen Shot 2021-05-09 at 8 51 48 PM" src="https://user-images.githubusercontent.com/30255708/117577679-68245b80-b108-11eb-9bfb-aae2806b2170.png">

**Comment by mohanarpit** [comment]
Closing this in favour of #4191 as that has more details.
