### ISSUE TITLE
[Bug]: Update livenessProbes , startupProbe in helm charts

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#24020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When users deploy appsmith using helm charts. The livenessProbe and startupProbe help in restarting appsmith incase appsmith goes unhealthy.

### Steps To Reproduce

```
helm repo add appsmith https://helm.appsmith.com
helm repo update
helm install appsmith . -n appsmith --create-namespace

```
after 15 min
```
kubectl delete pod appsmith-mongo-0 -n appsmith
kubectl restart sts/appsmith -n appsmith
```
You can see appsmith doesnt restart though mongo/redis are back to normal state

### Environment

Production

### Version

v1.9.20.4

**Comment by sharat87** [comment]
@pratapaprasanna, from the commands in the description, it looks like we're deleting MongoDB pod, after which, Kubernetes will recreate that pod, right? So, once that is ready, if we restart Appsmith, it should connect to the new MongoDB pod, right?

If that's not happening, what's the error? Is there a connection failure? How is changing probes going to help here?
