### ISSUE TITLE
[Epic]: Use Flagsmith as our feature flagging service

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#24037]
### Objective

Integrate a feature flagging solution for Appsmith to make releasing features quicker, simpler and intuitive.

- It should not be heavily tech dependant. PMs and EMs should be able to control deployment of flags and values without tech intervention
- Have the ability to do A/B testing
- Have the ability to do staged rollouts
- User testing of features in prod and ability to have a beta channel for updates
- Give developers the confidence to ship daily

### Success Metrics

Goal of this integration is to improve our release confidence and overtime have the ability to do continuous deployment of our repo

#### Internal developers
Developers when developing a feature behind feature flags will first create the flag on the dashboard. The dev mode will run on the "Release" environment and flags will be accessible via Release backend. While behind feature flags, automated testing is not necessary but advisable. Shipping smaller parts of the feature is encouraged. Once feature is launched, the developer is responsible of cleanup of the feature flags.

#### Cloud
Cloud users have access to feature flags and can join the beta channel

#### Self hosted CE
CE users have access to feature flags

#### Self hosted EE
EE users have access to feature flags and can join the beta channel

#### Air gapped Instance
Air gapped instances will not have access to feature flags

### Tasklist
- [x] #22809
- [x] Remove unused feature flags
- [x] #24347
- [ ] #24878
- [x] [Phase 3](https://github.com/appsmithorg/appsmith-ee/issues/1679)

### RACI matrix

| Role | People |
| ------------- | ------------- |
| Responsible   | @NilanshBansal, @abhvsn, @hetunandu |
| Accountable   | @hetunandu |
| Consulted     | @Nikhil-Nandagopal, @mohanarpit, @sharat87, @nidhi-nair  |
| Informed      | @ginilpg |

**Comment by shwetha-ramesh** [comment]
QA Completed. @NilanshBansal
