### ISSUE TITLE
[Task]: Track JSObject variable usage

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#24038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Track events to measure usage of JSObject variables

| Event | Payload | Comment |
|--------|--------|--------|
| JS_VARIABLE_CREATED | { type: Array, String,  Boolean, Object, etc...   } | Track when a new variable is declared |
| JS_VARIABLE_MUTATED | { type: Array, String,  Boolean, Object, etc... ,  source: JSObject function, Widget property, etc...  } | Track when a variable is mutated  |

**Comment by Rishabh-Rathod** [comment]
@bharath31 for the `JS_VARIABLE_MUTATED` event's payload, the determination of the source of mutation between `JSObject function` and `Widget property` is complicated. We could start with tracking the event and the variable type.

**Comment by bharath31** [comment]
@Rishabh-Rathod sure! let's start with basic event tracking
