### ISSUE TITLE
[Bug]: Gsheet unsupported option are in bold

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#24050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Gsheet does not support Insert sheet and hence the option was in grey and in the current ADS it is observed that it is displayed in bold.

### Steps To Reproduce

1) create a Gsheet data source
2) Authorise the data source
3) click on Add Query 
4) Select Insert one 
5) Navigate to select the entity 
and observe that unsupported is also highlighted in blood 
<img width="1782" alt="Screenshot 2023-06-05 at 3 46 14 PM" src="https://github.com/appsmithorg/appsmith/assets/132243297/b3dd36c1-5865-4a51-bb82-36de07859a3f">

### Environment

Release

### Version

cloud

**Comment by rohan-arthur** [comment]
Marking this as low effort as a guess, considering this was working before and seems to have regressed.

**Comment by AmanAgarwal041** [comment]
This is an old issue. Not the unsupported option are light and cursor is disabled on them.
<img width="722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30f990da684b78ab7066d2799bfdd4d6db7f94ad/Screenshot%202024-04-09%20at%2012.28.14%20PM.png" alt="Screenshot 2024-04-09 at 12.28.14 PM.png" />

@rohan-arthur should we close this issue ?
