### ISSUE TITLE
[Task]: Show changed pages and query details in commit popup

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#24059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently, the commit popup just displays the overall number of changes. There is no way for a user to understand which changes are included in the commit. As a first step toward improved communication, we can begin displaying changed page names, queries, and API along with their count, in the commit popup.

**Comment by infinitetrooper** [comment]
Duplicate of #20931
