### ISSUE TITLE
Query Module: Required arguments / parameters from codebase

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#24062]
We need to add some arguments/parameters to the Queries, JS Objects and Widgets:
- root query
- is copied
- is updated
- last update

**Comment by somangshu** [comment]
@carinanfonseca what do you mean by `root query`?

@ApekshaBhosale @subrata71 @ashit-rath can we think holistically what params we need and how to go about implementing this?

**Comment by somangshu** [comment]
Doc on backend dependencies: https://www.notion.so/appsmith/Backend-dependency-for-modules-instrumentation-889462d461844745be0a2599c8555ca5?pvs=4

**Comment by subrata71** [comment]
Possible duplicate
https://github.com/appsmithorg/appsmith/issues/24734
@somangshu
