### ISSUE TITLE
[Bug]: Open repository button is not functional in git sync modal

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#24070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Open repository button is not functional in git sync modal, ideally on clicking this button should take user to git repository 

<img width="1440" alt="Screenshot 2023-06-05 at 10 15 36 AM" src="https://github.com/appsmithorg/appsmith/assets/80334441/5490d7a4-1570-447c-9ee1-1fe3a9ba47ef">

### Steps To Reproduce

1. Go to git connected app which has conflicts
2. Click on open repository button
3. Observe the click doesnt work

### Environment

Release

### Version

Release

**Comment by Parthvi12** [comment]
@AnaghHegde  I have shared the app with you https://release.app.appsmith.com/app/release-mar14-no-merge-freeze/smtp-64100ab78ceea00354688770/edit?branch=master

**Comment by AnaghHegde** [comment]
Its a frontend issue. Looks like its because of the ADS.
