### ISSUE TITLE
[Feature] Allow users to control visibility for widgets / pages based on roles

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2408]
## Summary

1. Let users control what roles can see a widget or a page
2. Let users discover how to write visibility logic in JS inside Appsmith for different user groups(you’ll see the JS snippet when you click JS toggle)

This will help a developer see widgets+pages in deployed version that are invisible to a business user.

1. Make visibility a dropdown instead of a toggle(example below)
2. The view mode pages shouldn’t slow down because at every page load we have to check visibility permissions for a user.
2. It should be easy to change visibility controls for a group of users from a single location when you deploy instead of having to visit 10 different places to make a change.
<img width="571" alt="Screen Shot 2020-12-30 at 2 48 20 PM" src="https://user-images.githubusercontent.com/30255708/103413168-60730a00-4b9e-11eb-8634-fed3a99f4d67.png">

**Comment by hiteshjoshi** [comment]
Moving this to IceBox. I believe we will cover this under RBAC?

**Comment by infinitetrooper** [comment]
[Slack Conversation](https://theappsmith.slack.com/archives/CNQ9Q91C0/p1674131768696809?thread_ts=1674037342.680279&cid=CNQ9Q91C0)

**Comment by infinitetrooper** [comment]
Demo Video

https://github.com/appsmithorg/appsmith/assets/16632903/1c5066f1-3f7e-4dfa-a01c-50f51838a1c7

**Comment by trishaanand** [comment]
Closing this since widget level acl has been merged into release.

**Comment by infinitetrooper** [comment]
This feature is part of Appsmith Business Edition v1.9.22
