### ISSUE TITLE
[Bug]: Placeholder not aligned in editor pages

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Placeholder in big dynamic text field are not aligned with other type of input fields in the editor page eg MongoDB

### Steps To Reproduce

![Screenshot 2023-06-06 at 10 43 36](https://github.com/appsmithorg/appsmith/assets/890915/aaba3d1a-3c23-43da-87b8-a9ead08441d6)

### Environment

Release

### Version

Cloud-latest

**Comment by shadabbuchh** [comment]
This issue is fixed & verified in https://github.com/appsmithorg/appsmith/pull/24387

**Comment by shadabbuchh** [comment]
Verified in release.

<img width="221" alt="Screenshot 2023-06-22 at 11 39 57 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/393e39d2-2c87-45ad-b7ba-7d722c70771d">
