### ISSUE TITLE
[Task]: Editable input error state not proper

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

All details are on [notion](https://www.notion.so/Editable-input-error-state-not-proper-071385f0d901437ea95629a1fbf96396)

**Comment by shadabbuchh** [comment]
This issue has been verified here: https://github.com/appsmithorg/appsmith/pull/24342
Waiting for a resolution on another issue which is also linked to the same PR.
