### ISSUE TITLE
[Task]: Update GIF on graphQL editor

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

New gif
![CleanShot 2023-05-26 at 09 53 48](https://github.com/appsmithorg/appsmith/assets/890915/59b2daf8-45c8-4195-b7f9-29ca03e160ea)

**Comment by tanvibhakta** [comment]
@vasanthappsmith can you also please provide a thumbnail for this gif?
