### ISSUE TITLE
[Task][Design]: Too much space below the bottom sticky section on left panel

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

All details are on [notion](https://www.notion.so/Too-much-space-below-the-bottom-sticky-section-on-left-panel-bcfc2e4e3c0646748c0b6a4e36fc83fd)

**Comment by rohitagarwal88** [comment]
@vasanthappsmith : is the design approved by NDX Pod designer? https://www.notion.so/appsmith/Task-Too-much-space-below-the-bottom-sticky-section-on-left-panel-71301f295bc1477a92ddf6e0489a543e

**Comment by vasanthappsmith** [comment]
This is verified and approved by @aakashDesign
