### ISSUE TITLE
[Task]: Preview button should be in pressed state when in preview mode

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

All details are on [notion](https://www.notion.so/Preview-button-should-be-in-pressed-state-when-in-preview-mode-8b420e7e189f4d7bb26c94345beb94b5)

**Comment by rohan-arthur** [comment]
context: https://theappsmith.slack.com/archives/C0293DVQACW/p1688026741314489
