### ISSUE TITLE
[Task]: Update template thumbnails to show primary feature of app

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#24094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Decide on which features to display within each new template
- Create the template images
- Update the platform with new images
- Check to see if we need to do this on the website too?

**Comment by jacquesikot** [comment]
@danciaclara do we need to update the website images too?

**Comment by danciaclara** [comment]
yeah, the same thumbnails should be used on the platform and the website.
