### ISSUE TITLE
[Task]: Update js Icon on JS Object Page

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24093]
### Description
Change the JS object icon to new yellow icon.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Detail are list on [notion](https://www.notion.so/appsmith/Update-js-Icon-on-JS-Object-Page-ff17bb42eb7e4814a6517658648c4ff8)

**Comment by albinAppsmith** [comment]
![js-yellow](https://github.com/appsmithorg/appsmith/assets/87797149/a15233ce-1eb7-4589-9465-b488769fa570)
