### ISSUE TITLE
[Bug]: The welcome screen alignment for new  user sign-up looks off in the release instance

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#24106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The welcome screen alignment for new  user sign-up looks off in the release instance
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/b5c97a2a-f6ac-4e7e-911c-1731f0185afb">

### Steps To Reproduce

1. Go to release.app.appsmith.com
2. click on sign up link
3. Now sign up with new email id
4. The welcome alignment looks off and also UI should be same as old

### Environment

Release

### Version

v1.9.20.5

**Comment by dipyamanbiswas07** [comment]
>also UI should be same as old

This is not a release blocker and will be tracking as a different issue. 

@pranayagarwal96  @RakshaKShetty

**Comment by ankitakinger** [comment]
@dipyamanbiswas07 Can we also change `Almost there` header here to use the color: `var(--ads-v2-color-fg-emphasis-plus)` while working on this issue?

**Comment by kavitasmoolya** [comment]
Validated on release https://release.app.appsmith.com/ and welcome page looks aligned for new user sign up. Refer Attached screen below 

![image](https://github.com/appsmithorg/appsmith/assets/134914630/9d0124ab-9ec6-4d0e-81f5-55c39b08cf9a)
