### ISSUE TITLE
[Bug]: On adding any query from the schema, the active ds page comes up first and then takes user to the query page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding any query from the schema, the active ds page comes up for a few seconds before taking user to the query page. This is true for any query created from schema for any DS

### Steps To Reproduce

1. As an example, create a connection to an S3 Datasource
2. Create a new page
3. In the property pane, expand the S3 datasource
4. Choose the bucket which has data.
5. Click on the Add button next to the bucket and choose say List Files
6. Note that for a few seconds, user is taken to the active DS page, and then the pre-created Query page comes up.
Expected behavior
The user should be directly taken to the Query page

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/ZSl4D83eDGL8212w

### Version

Cloud

**Comment by rohan-arthur** [comment]
we've removed the entity explorer, so this issue is not valid anymore
