### ISSUE TITLE
[Task]: Split out the common component between SuperUser and NonSuperUser form

### ISSUE THREAD

**Issue by dipyamanbiswas07** [appsmithorg/appsmith#24120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently both the Welcome Screen for super user and non super user use the same parent component. To Ensure that we can change both of these forms (Images,Text, Fields) independently we have to split out the components to be independent of each other.

**Comment by pranayagarwal96** [comment]
@ankitsrivas14 any documentation on how QA is supposed to test this?
cc @Harshask93 @RakshaKShetty

**Comment by ankitsrivas14** [comment]
This is basically a code change and nothing from UI and functionality side.
Super user sign-up and non-super user sign-up, after this change should work as it is. Here we have to check if the feature works without any issues due to this change.

cc: @Harshask93

**Comment by Harshask93** [comment]
Tested the signup and sign flow by taking ee release pull and the feature is working as expected.
