### ISSUE TITLE
[Bug]: When Using Auto-Layout, List V2 onItemClick Event Not Run If Clicking on Widgets Placed Inside The List Item

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#24139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Auto-Layout is enabled, if a user clicks on a list item that contains other widgets, such as images or text, the onItemClick event does not get fired. It only gets fired when clicking on the container/blank space. This happens in both edit and deployed modes.

This issue only happens when using Auto-Layout.
[Front thread](https://app.frontapp.com/open/cnv_10rdsdfw?key=6dEjyoOPjPblEvPy4m800Mg2I3gltjDt) - contains link to an app shared with support.

[Discord thread](https://discord.com/channels/725602949748752515/1115003810591547525)modes

### Steps To Reproduce

1. Add a **List widget** to the canvas.,
2. Add an **onItemClick** event (e.g., open a Modal).
3. In the app properties, select **Convert to Auto layout**.
![image](https://github.com/appsmithorg/appsmith/assets/101268423/9f0b283b-9753-4698-9b78-1db9196a1642)

### Environment

Production

### Version

Appsmith v1.9.20.5

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b2jyk)

**Comment by ame-appsmith** [comment]
[Another user](https://theappsmith.slack.com/archives/C04VADPRCCF/p1693244610505649) reported this issue.

**Comment by Nikhil-Nandagopal** [comment]
We're sunsetting autolayout so closing this
