### ISSUE TITLE
[Bug]: The user is not able to navigate back to customer portal once after opening the Docs links

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#24134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is not able to navigate back to customer portal once after opening the Docs links
https://www.loom.com/share/4c1da8be328341da9add2e65e8bb9beb

### Steps To Reproduce

1. go to release-customer portal
2. Click on other methods
3. Now Try to go back to customer portal the new docs tab is opened and we are not able to go to customer portal

### Environment

Release

### Version

v1.9.20.5

**Comment by ankitsrivas14** [comment]
Fixed by https://github.com/appsmithorg/cloud-services/pull/930
