### ISSUE TITLE
[Bug] Authentication after 404 not redirecting back to the original page

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2415]
## Description
If you land on a private app without authentication, it is shown as 404. But after you sign in, you are redirected back to the homepage instead of the app

Steps
1) Create a private app
2) Logout and visit the app
3) On seeing the 404 error, sign in
4) After sign in, you will go to the home page

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan @hetunandu Related to #1717
