### ISSUE TITLE
[Bug]: Fix RTS start failure script

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#24168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

RTS is not starting as node is trying to find `server.js` in `dist/rts/`, but `server.js` is located in `dist/`.

### Steps To Reproduce

Move to `RTS` folder in `client/packages`.
run `./start-server.sh`

### Environment

Production

### Version

Cloud

**Comment by btsgh** [comment]
As per cpmment in the chore about skiptestplan added, closing this out as verified and removing QA label
