### ISSUE TITLE
[Task]: Update git error message when importing an app.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#24170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

`Git file system error
Error while accessing the file system. Unable to import application in workspace 6474a40759741f20ca5de3e6. Error: Internal server error while processing request`

This error message needs to be updated to more useful and actionable message.

**Comment by infinitetrooper** [comment]
Duplicate of #21804
