### ISSUE TITLE
[Bug]: When click on new "Fork" button in templates - No workspace to fork error is shown

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#24176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Go to Templates and click on "Employee Feedback form" template and click on new "Fork" button at the top of the template image, we are able to see "No Workspaces to fork" error

https://github.com/appsmithorg/appsmith/assets/104895602/88209028-6440-4002-bcfc-b0d25ac0a161

### Steps To Reproduce

1. Go to Templates Tab
2. Click on any Templates
3. Click on "Fork" button at the top
4. Observe "No Workspaces to fork" error

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.20.5-SNAPSHOT

**Comment by rahulbarwal** [comment]
@Sripriya93 
We have updated the URL's for prod as well. This should be fixed now on DP URL's as well. Please check.

**Comment by Sripriya93** [comment]
@rahulbarwal The above issue is fixed but the fork drop down is having different options it isnt showing the workspace present for that particular DP, it actually shows workspaces available in prod

**Comment by Sripriya93** [comment]
@rahulbarwal QA done. Working fine.
