### ISSUE TITLE
[Bug]: Enable TLS Protected Connection toggle in Email settings [Admin Settings] seems nonfunctional

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The SMTP User name and SMTP Password fields are both available even if the Enable TLS Protected Connection is off. 

### Steps To Reproduce

1. Login as instance admin to release [CE or EE]
2. Navigate to Admin Settings, and click on the Email section
3. Here, note that the SMTP User name and SMTP Password fields are visible even though the Enable TLS Protected Connection is off. 

### Environment

Release

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/kBOpFfntxsDOSoMu

### Version

Cloud

**Comment by ankitakinger** [comment]
@btsgh this was intentionally changed by @sharat87 under this PR:
https://github.com/appsmithorg/appsmith/pull/17952

**Comment by btsgh** [comment]
As per above comments, this is intended behavior
