### ISSUE TITLE
[Bug]: Divider widget turns vertical when content in Direction property is removed

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#24191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

D&D a Divider widget, go to direction style property and click on JS toggle button, remove the content in the property, observe the Divider is turned vertical, but in property we are seeing Horizontal is selected.

### Steps To Reproduce

1. D&D Divider widget
2. Go to Direction property in style tab
3. Click on JS toggle button
4. Remove the contents
5. Observe Divider turns vertical
6. Toggle back the JS button
7. Observe Horizontal is selected

https://github.com/appsmithorg/appsmith/assets/104895602/49abae77-a142-491d-a9d9-3aca35680b50

### Environment

Deploy Preview

### Version

Appsmith v1.9.20.5-SNAPSHOT

**Comment by aswathkk** [comment]
Adding a proper validation for this property will resolve this issue.
This also needs a migration afterwards.
