### ISSUE TITLE
[Bug]: Incorrect lint error shows up after widget name refactor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a widget name is refactored, a lint error shows up for widget name stating widget is not defined

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/703fdda4-7e5c-4c26-88c0-30b158f6b2fc)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/250a3b1e-57d2-4051-a09f-8cb5667c076f)

1. Use a widget in a binding/query and rename the widget
2. Go back to the query and observe a lint error stating widget is not defined
3. Refresh page and notice the error is resolved

Issue is present on current release and will get promoted to master if not resolved before next promotion

### Environment

Release

### Version

Cloud

**Comment by bharath31** [comment]
@ohansFavour could you please investigate the root cause for this issue?

**Comment by ramsaptami** [comment]
I can see it on prod and release @ohansFavour 
https://www.loom.com/share/79731ab4c36e4fa1ac75474e16f56976
