### ISSUE TITLE
[Bug]:  Google Sheets Authentication expired after 2 hours

### ISSUE THREAD

**Issue by tommy1003** [appsmithorg/appsmith#24190]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Google Sheets Authentication expired after 2 hours after an update from on 06/06/2023

### Steps To Reproduce

1. Add Google Sheets Connection
2. Any Operation (fetch, update, delete rows)
3. Authentication expired after 2 hours (operation failed).

### Environment

Production

### Version

Appsmith v1.9.20.5-SNAPSHOT

**Comment by tommy1003** [comment]
![7e800ca6c8c9199740d8](https://github.com/appsmithorg/appsmith/assets/6297985/e5b52356-e65b-4460-8a10-c7f31b22607c)

**Comment by rohan-arthur** [comment]
@tommy1003 thank you for reporting this horrible issue. Yes, we are on top of it, and a fix is coming soon. Please keep your eyes on #24236 - meanwhile I'll close this issue
