### ISSUE TITLE
[Bug]: Table widget not showing data when its sorted on save/discard column

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#24200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bind the table with query and sort the save/discard column now double click on editable property verify data is not displayed This is also observed in production

https://github.com/appsmithorg/appsmith/assets/80756091/427d1215-f06c-429c-84e4-9071c705409d

### Steps To Reproduce

1. Add the table widget
2. Bind it with query {{query.data}}
3. sort the column - save/discard 
4. Click on editable property and verify that the table is not displaying any data

### Environment

Production

### Version

cloud

**Comment by dilippitchika** [comment]
Disable sorting on action columns.

**Comment by somangshu** [comment]
@dilippitchika on all action columns? even the once that are custom made by a user using a button column

**Comment by jacquesikot** [comment]
This property does not exist in the table property pane anymore
