### ISSUE TITLE
[Bug]: CRITICAL - DEFAULT_REST_DATASOURCE broken when creating new api query in version 1.9.21 + heading slash / sign incorrectly removed from query url

### ISSUE THREAD

**Issue by erwan-lemonnier** [appsmithorg/appsmith#24218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating or editing an api query will result in a broken configuration where the query's metadata.json lacks a dataSourceConfiguration as below:

```
{
  "pluginType": "API",
  "pluginId": "restapi-plugin",
  "unpublishedAction": {
    "name": "cancelBeat",
    "datasource": {
      "name": "DEFAULT_REST_DATASOURCE",
      "pluginId": "restapi-plugin",
      "datasourceConfiguration": {
        "url": ""
      },
      "invalids": [],
      "messages": [],
      "isAutoGenerated": false,
      "deleted": false,
      "policies": [],
      "userPermissions": []
    },
   ...
```

I also noticed that the first '/' sign in the query's url seems to be removed, resulting in a broken api url.
For example, when using the query editor to create the query updatePaidAdBeat (above) and giving the endpoint url 

`{{appsmith.store.api_url}}/bo/v2/campaign/{{this.params.campaign_id}}/beat/{{this.params.beat_id}}/cancel`

will result in appsmith saving the following metadata.json to git:

```

    "actionConfiguration": {
      "timeoutInMillisecond": 10000,
      "paginationType": "NONE",
      "path": "{{appsmith.store.beatly_api}}bo/v2/campaign/{{this.params.campaign_id}}/beat/paidad/{{this.params.beat_id}}/update",

```

Notice the missing / in the path url...

Needless to say, this renders the api query editor unusable and breaks existing api queries as soon as editing one...

### Steps To Reproduce

See description.

### Environment

Production

### Version

1.9.21

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_bwyoc)

**Comment by erwan-lemonnier** [comment]
Should mention that this bugs started at precisely the time you deployed 1.9.21 to the cloud editor. At exactly that moment, the queries I had been editing started returning errors like 

"PluginExecutionError: DELETE [cancelBeat] https://app.appsmith.com/): DEFAULT_REST_DATASOURCE is not correctly configured. Please fix the following and then re-run: [Missing URL.]"

Took me a few hours to trace the issue to defect metadata.json files and possibly the missing heading / in the path url...

**Comment by Nikhil-Nandagopal** [comment]
@erwan-lemonnier could you share the URL of the API query that is broken for you? It would also help if you could share a screen recording

**Comment by erwan-lemonnier** [comment]
Hi Nikhil!
I also started a discussion in discord, and have put more detailed examples there: https://discord.com/channels/725602949748752515/1116106957196120216

**Comment by sumitsum** [comment]
Tracking the editor crash issue separately [here](https://github.com/appsmithorg/appsmith/issues/24397). 
We will use this issue to track the REST API query failing error.
