### ISSUE TITLE
[Bug]: Divider widget style property "Stroke style" and "Cap style" dropdown are not aligned

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#24212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

D&D a divider widget and go to style property pane observe Stroke section Style dropdown and Cap drop down options are not aligned in one line
<img width="681" alt="image" src="https://github.com/appsmithorg/appsmith/assets/104895602/fc719c6f-7337-434c-9f09-7cfdd2a96cf4">

### Steps To Reproduce

1. D&D a Divider widget
2. Go to Style property pane
3. Observe Stroke style dropdown are not aligned in one line
4. Observe Cap dropdown options are not aligned in one line

### Environment

Production

### Version

Appsmith v1.9.20.5-SNAPSHOT

**Comment by iSatVeerSingh** [comment]
Duplicate of #23859 and has been fixed in #24289. Please close this.
