### ISSUE TITLE
[Bug]-[1]:Handle incorrect naming convention with an error - it currently breaks evaluations of an object

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is probably due to a JS restriction around naming convention - name an object starting with a number and observe evaluation breaks and any new function added to the object does not get picked up. Observe there are no errors or prompts to indicate incorrect naming convention - instead evaluation breaks and shows an `Invalid token` error **_only_** on a binding

### Steps To Reproduce

1. Add a JS object, rename it to `1`
2. Add a function `myFun3`
3. Drag a widget on to the canvas and try to bind `1.myFun3` - observe this option does not show up on autocomplete
4. Check run dropdown or run gutter element to run `myFun3` - observe this function is not updated on the object

### Environment

Production

### Issue video log

https://www.loom.com/share/c8bb2370335144a0aa016d5e81810876

### Version

Cloud

**Comment by bharath31** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     |1 |
| Effort (months)  | 0.5 |

**Comment by bharath31** [comment]
Deprioritising due to low reach

**Comment by ramsaptami** [comment]
@bharath31 this is applicable to other entities too (query+widgets) which impacts UX holistically even though pro-JS users might understand the semantics of entity names so would be great to pick this up to improve user experience.
