### ISSUE TITLE
[Bug]: Appsmith server is taking too long to respond

### ISSUE THREAD

**Issue by marcheschi** [appsmithorg/appsmith#24231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Installed on Ubuntu 20.04
sudo docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS                  PORTS                                                                      NAMES
76284bf62841   appsmith/appsmith-ce:latest   "/opt/appsmith/entry…"   23 hours ago   Up 23 hours (healthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   appsmith
d7a2e3340eed   containrrr/watchtower         "/watchtower --sched…"   41 hours ago   Up 40 hours             8080/tcp                                                                   appsmith_auto_update_1

When I try to edit my first App
![image](https://github.com/appsmithorg/appsmith/assets/3910408/a06f3be0-f8a2-42ee-ac60-9445c75dc6cc)

Logs:
`editor stdout | 10.96.26.140 - - [08/Jun/2023:06:51:48 +0000] "GET /api/v1/pages?pageId=647f441bb9009d5e1ccb6841&mode=EDIT HTTP/1.1" 200 497 "http://10.96.32.161/app/my-first-application/page1-647f441bb9009d5e1ccb6841/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"
editor stdout | 
rts stdout | ns:/# socket _uR-aKx-o11UwoKEAAAB joined the room app:647f441bb9009d5e1ccb683e
rts stdout | 
redis stdout | 1676:M 08 Jun 2023 06:51:48.280 * Background saving terminated with success
redis stdout | 
backend stdout | [2023-06-08 06:51:48,320] userEmail=paolo@ftgm.it, sessionId=b80a75a0-0c6e-4a3e-9eed-889424b3bdea, thread=lettuce-epollEventLoop-6-1, requestId=2350f68b-1c57-4481-8a1c-44e5910607ea - Going to get all unpublished action collections with params: {applicationId=[647f441bb9009d5e1ccb683e]}, branch: null
backend stdout | 
editor stdout | 10.96.26.140 - - [08/Jun/2023:06:51:48 +0000] "GET /api/v1/collections/actions?applicationId=647f441bb9009d5e1ccb683e HTTP/1.1" 200 101 "http://10.96.32.161/app/my-first-application/page1-647f441bb9009d5e1ccb6841/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"
editor stdout | 
editor stdout | 10.96.26.140 - - [08/Jun/2023:06:51:48 +0000] "GET /api/v1/themes/applications/647f441bb9009d5e1ccb683e/current?mode=EDIT HTTP/1.1" 200 1442 "http://10.96.32.161/app/my-first-application/page1-647f441bb9009d5e1ccb6841/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"
editor stdout | 
editor stdout | 10.96.26.140 - - [08/Jun/2023:06:51:48 +0000] "GET /api/v1/pages/647f441bb9009d5e1ccb6841 HTTP/1.1" 200 518 "http://10.96.32.161/app/my-first-application/page1-647f441bb9009d5e1ccb6841/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"
editor stdout | 
rts stdout | ns:/# socket _uR-aKx-o11UwoKEAAAB left the room app:647f441bb9009d5e1ccb683e
rts stdout | 
editor stdout | 10.96.26.140 - - [08/Jun/2023:06:51:48 +0000] "GET /api/v1/themes/applications/647f441bb9009d5e1ccb683e HTTP/1.1" 200 4624 "http://10.96.32.161/app/my-first-application/page1-647f441bb9009d5e1ccb6841/edit" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"
editor stdout | 
rts stdout | ns:/# socket _uR-aKx-o11UwoKEAAAB joined the room app:647f441bb9009d5e1ccb683e
rts stdout | 
backend stdout | [2023-06-08 06:51:48,397] userEmail=paolo@ftgm.it, sessionId=b80a75a0-0c6e-4a3e-9eed-889424b3bdea, thread=lettuce-epollEventLoop-6-1, requestId=4910e92d-c69a-4077-bf8b-da19a27cc71d - Going to get snapshot with application id: 647f441bb9009d5e1ccb683e, branch: null
backend stdout | 
backend stdout | [2023-06-08 06:51:48,404] userEmail=paolo@ftgm.it, sessionId=b80a75a0-0c6e-4a3e-9eed-889424b3bdea, thread=nioEventLoopGroup-3-5, requestId=4910e92d-c69a-4077-bf8b-da19a27cc71d - 
backend stdout | com.appsmith.server.exceptions.AppsmithException: Unable to find application 647f441bb9009d5e1ccb683e
backend stdout | 	at com.appsmith.server.services.ce.ApplicationSnapshotServiceCEImpl.getWithoutDataByApplicationId(ApplicationSnapshotServiceCEImpl.java:73)
backend stdout | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
backend stdout | Error has been observed at the following site(s):
backend stdout | 	*__checkpoint ⇢ Handler com.appsmith.server.controllers.ApplicationController#getSnapshotWithoutApplicationJson(String, String) [DispatcherHandler]
backend stdout | Original Stack Trace:
backend stdout | 		at com.appsmith.server.services.ce.ApplicationSnapshotServiceCEImpl.getWithoutDataByApplicationId(ApplicationSnapshotServiceCEImpl.java:73)
backend stdout | 		at com.appsmith.server.controllers.ce.ApplicationControllerCE.getSnapshotWithoutApplicationJson(ApplicationControllerCE.java:216)
backend stdout | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
backend stdout | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
backend stdout | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
backend stdout | 		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
backend stdout | 		at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:145)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:293)
backend stdout | 		at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:474)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
backend stdout | 		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:134)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 		at reactor.core.publisher.MonoSupplier$MonoSupplierSubscription.request(MonoSupplier.java:148)
backend stdout | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
backend stdout | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout | 		at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:48)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
backend stdout | 		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 		at reactor.core.publisher.Operators.complete(Operators.java:137)
backend stdout | 		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:145)
backend stdout | 		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
backend stdout | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
backend stdout | 		at reactor.core.publisher.MonoZip$ZipCoordinator.request(MonoZip.java:216)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(MonoIgnoreThen.java:134)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onSubscribe(MDCConfig.java:47)
backend stdout | 		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:125)
backend stdout | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout | 		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
backend stdout | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:189)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onComplete(MDCConfig.java:63)
backend stdout | 		at reactor.core.publisher.Operators.complete(Operators.java:137)
backend stdout | 		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:121)
backend stdout | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4485)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
backend stdout | 		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
backend stdout | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
backend stdout | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
backend stdout | 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
backend stdout | 		at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
`

### Steps To Reproduce

login
go to first app

### Environment

Deploy Preview

### Version

Self hosted with docker and autoupdate

**Comment by pranavkanade** [comment]
@marcheschi When do encounter this error? Is it during installation or when you try to open some app?

Also, please use this document to provide detailed container logs - https://docs.appsmith.com/learning-and-resources/how-to-guides/how-to-get-container-logs#docusaurus_skipToContent_fallback

**Comment by sharat87** [comment]
@marcheschi, sorry you're facing trouble here. Can you confirm the system capacity of the server you're running with? Like vCPU count, available memory etc., and if there's any other applications also running on this server, along with Appsmith please? Also, please share full logs as indicated in prev. message. Thanks!

**Comment by marcheschi** [comment]
Thank you @pranavkanade @sharat87 
I used a **dedicated** VM with 8 CPU and 16 GB of ram with 20 GB of disk
appsmith is the only app on the server.
The installation runs fine, and I can login
but when I try to edit my first app appears the message and the editor is not shown.
Logs:
https://drive.google.com/file/d/1rAleXljvo0edsNP8c8GPWarirWCt35ev/view?usp=sharing

**Comment by sharat87** [comment]
@marcheschi, thank you for the details. It looks like your server isn't connected to the Internet. Appsmith is unable to reach cs.appsmith.com, which is required for it's operation. More details about this in the callout at https://docs.appsmith.com/getting-started/setup#self-hosting-benefits.

Can you please confirm if your server has access to reach external endpoints in the Internet? If not, can we allow that access and restart Appsmith please?

**Comment by marcheschi** [comment]
The server has internet access, via proxy .

**Comment by marcheschi** [comment]
It does not work either.
I tried to recreate the container twice.
Too difficult and is a nonsense it needs a connection to the internet.
I'm sorry, Thank you for your assistance.

**Comment by sharat87** [comment]
Hey @marcheschi, sorry you feel that way. We need Internet access to make some features possible, and some others convenient. I hope you managed to resolve the issue, if not, we can help you out if you can share the logs and what's failing now. Thank you!

**Comment by sharat87** [comment]
Thanks @marcheschi for confirming. We actually have a provision to allow you to configure proxy in upper or lower case. We accept both. I'm wondering if uppercase env variables wasn't working for you? 🤔

Relevant code is in this function: https://github.com/appsmithorg/appsmith/blob/c4b9e272dbc0b08f307931c71c24e897435975a1/deploy/docker/entrypoint.sh#L97-L113
