### ISSUE TITLE
[Feature]: supervisor to be accessible via SSL

### ISSUE THREAD

**Issue by UMinky** [appsmithorg/appsmith#24237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We would like the supervisor to be accessible via SSL. 

### Why should this be worked on?

In our enterprise environment nonSSL connections are not allowed.

**Comment by UMinky** [comment]
Moin,
thanks for the advice. I seem to have overlooked that. I thought that I have already tried...

Es grüßt Sie
Udo Minkwitz, Data & Digital Transformation (H-HDI.IT-DD.H)

Von: Shrikant Sharat Kandula ***@***.***>
Gesendet: Dienstag, 1. August 2023 16:26
An: appsmithorg/appsmith ***@***.***>
Cc: Minkwitz, Udo ***@***.***>; Mention ***@***.***>
Betreff: Re: [appsmithorg/appsmith] [Feature]: supervisor to be accessible via SSL (Issue #24237)


(Closed by accident)

@UMinky<https://github.com/UMinky>, if you have SSL enabled on your Appsmith instance, then /supervisor will also be available on HTTPS. Do you see any error in that? If yes, can you share a screenshot of what you see please?

**Comment by sharat87** [comment]
Got it. Thanks for confirming @UMinky. I'll go ahead and close this issue then. If you do face any trouble with SSL, please do let us know, either reopening this, or creating a new issue.
