### ISSUE TITLE
[Bug] Testing "Pagination with Response Url" with a null next URL returns with a server error

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2424]
## Description
On testing with a null URL, Appsmith as a go-between should simply respond with whatever error the API itself returns. The null pointer is an error in the server's URL decode logic.

### Steps to reproduce the behaviour:
1. Go to any API
2. Click on "Pagination"
3. Choose "Pagination with Response Url"
4. Click on "Test" for Next url while the field is empty to see internal server error

![image](https://user-images.githubusercontent.com/5298848/103509752-d8d11800-4e89-11eb-8fde-6520d4717c2a.png)

### Important Details
 - Version: [Cloud]
 - OS: [MacOSX]
 - Browser [chrome]

**Comment by nidhi-nair** [comment]
@mohanarpit @hetunandu While this issue specifically addresses a 500 error for invalid inputs, do you think we should add a validation on the front end to disallow empty URLs anyway?

**Comment by hetunandu** [comment]
I would avoid adding more plugin related validation logic directly on the front-end. Maybe we can do some plugin defined logic which is run on the client.

**Comment by nidhi-nair** [comment]
That makes perfect sense for most plugins, but for the REST API that has been hard-coded on the frontend, we would again be splitting logic across layers. Do we intend to make the REST API plugin server driven in the long run?
