### ISSUE TITLE
[Bug]: When page name is bigger, tooltip is not popping up

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#24250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Enter a bigger page name and hover over the name, observe no tool tip is shown

### Steps To Reproduce

Go to Pages
Enter a bigger name
Hover over the page name
Observe No tooltip is popped up

### Environment

Release

### Version

Appsmith v1.9.22-SNAPSHOT

**Comment by iSatVeerSingh** [comment]
Also can not create page name more than 30 characters.

**Comment by kocharrahul7** [comment]
This seems to have been solved
