### ISSUE TITLE
[Bug]: One-click binding using Insert Snippet does not switch to JS mode causing poor UX

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking on `insert snippet` on table's one-click binding does not:
- insert code automatically to `table data` field, and
- `table data` field does not toggle to JS mode and copied code can't be directly pasted since snippet is read as search text

### Steps To Reproduce

1. On a fresh table widget, select `Insert snippet` from the `connect data` dropdown
2. Select and copy any snippet from the suggested list
3. Paste it on the `Table data` field - observe it's been pasted as a search text

Expectation: switch to JS mode when `insert snippet` is chosen 

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Removing the insert snippet option altogether. @sbalaji1192 can you link this issue with the PR, so that it autocloses when you merge your changes?

**Comment by sbalaji1192** [comment]
closed by https://github.com/appsmithorg/appsmith/pull/24090
CC @dilippitchika
