### ISSUE TITLE
[Bug]: Appsmith Not Rendering on Mobile After Release v1.9.21

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#24276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After updating to v1.9.21, apps are not rendering on mobile. Even if accessing `app.appsmith.com`, a blank page is displayed. This is reproducible on iPhone 11 Pro and iPhone 13 on Google Chrome and Safari browsers.
![image](https://github.com/appsmithorg/appsmith/assets/101268423/9ca519bf-58a5-46d8-8545-8d9b8c1120f0)

### Steps To Reproduce

Navigate to app.appsmith.com or open any Appsmith app (v.1.9.21) on an iPhone 11 Pro or iPhone 13 using the Google Chrome or Safari browser.

### Environment

Production

### Version

Appsmith v1.9.21

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b93ik)

**Comment by dilippitchika** [comment]
@somangshu i think if people cannot access app.appsmith.com then it might be an ADS issue. Who should i ask to check this?

CC @laveena-en

**Comment by somangshu** [comment]
Cant say for sure why ADS is responsible @dilippitchika. But since its specifically happening on mobile, I am wondering if its a problem with Auto layout

@ame-appsmith can you tell me if its all apps or some special config was enabled?

cc @rohitagarwal88

**Comment by somangshu** [comment]
I was able to reproduce this error on browserstack right on the homepage with the same error that a-force team points to. @dilippitchika is probably right, this is related to a wider change, probably ADS.

**Comment by ame-appsmith** [comment]
> @ame-appsmith can you tell me if its all apps or some special config was enabled?

It's all apps and even the dashboard. The same issue happens if I just try to access app.appsmith.com
