### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by kaidatar** [appsmithorg/appsmith#24293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I am building a system that emulates Excel spreadsheet but the data can be stored in database real time. 
Appsmith table widget is not an excel table. As you know excel has a lot of cell level control, 
I want to build cell level features on our system by having the user first click on the cell they want to edit and then populate some other UI widgets based on the cell user clicked. 
I want to know which cell the user clicked on and do something afterwards programmatically.

### Why should this be worked on?

So developers can have cell / column context rather than just row context. Being able to know which cell is selected / updated can have a lot of use.

**Comment by Nikhil-Nandagopal** [comment]
@kaidatar this will be a feature we add as a new widget
