### ISSUE TITLE
[Feature] Import Custom JS libraries into Appsmith

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2430]
## Summary

Import additional JS libraries that I can use. Creating this issue as a placeholder

- Support CDN based and JS SDK
### List of library support requested by users
- jsPDF
- https://www.npmjs.com/package/node-forge
- [firebase-admin](https://www.npmjs.com/package/firebase-admin)
- segment library
- https://github.com/digitalbazaar/forge
- firebase-auth
- [JsonPath](https://github.com/dchester/jsonpath)
- supabase js client for authentication and signup flows.
- mParticle
- Amplitude
- Datadog
- mathjax
- Danfo JS
- CryptoJS
- UZip
- JWT
- ESRI js
- axios

Please mention the library you would like to use with Appsmith using this feature. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5cpl8)

**Comment by Nikhil-Nandagopal** [comment]
A great reason why this feature is really important instead of us supporting different functions within the platform
https://github.com/lodash/lodash/issues/5130#issuecomment-840494799

**Comment by vishaldfreak** [comment]
+1 for this request
I'd like to be able to import custom JS library in the header 
I am trying to create a PDF label from custom data but I don't think it's possible as of now unless I can import jsPDF library.

**Comment by Nikhil-Nandagopal** [comment]
A user has a need for node forge to be added. @hetunandu for the time being can we quickly add this to our list of default libs?
https://www.npmjs.com/package/node-forge

**Comment by tomjose92** [comment]
> A user has a need for node forge to be added. @hetunandu for the time being can we quickly add this to our list of default libs?
> https://www.npmjs.com/package/node-forge

Yes, it would be great to have a custom import for this 'node-forge' library for authentication workflows.

**Comment by anvaynk** [comment]
@Nikhil-Nandagopal Is there a way to add such libraries from the UI ?

**Comment by Nikhil-Nandagopal** [comment]
@anvaynk we're currently working on the ability to add it from the UI. For now we're simply adding libraries on a case by case basis.

**Comment by anvaynk** [comment]
Sounds good. Thanks!

**Comment by vishalvijay** [comment]
Waiting to get this feature out. Any update?

**Comment by areyabhishek** [comment]
@vishalvijay we are working to launch this. Could you tell us the libraries you'd like to use? We can include them for you

**Comment by vishalvijay** [comment]
Thanks for reply @areyabhishek 

[firebase-admin](https://www.npmjs.com/package/firebase-admin) is something we use commonly.

**Comment by Nikhil-Nandagopal** [comment]
Another user reported wanting to add firebase admin

**Comment by morandalex** [comment]
in a self hosted environment , how can import libraries?

**Comment by Nikhil-Nandagopal** [comment]
@morandalex unfortunately there is no way to do this right now. We will be working on this feature in Q1 of next year

**Comment by R-Peleg** [comment]
+1 For this. My need is to add the `crypto` library for generating secure random tokens inside the application

**Comment by Nikhil-Nandagopal** [comment]
@R-Peleg we have forge included which has some functions to generate secure tokens. Does this work for you?
You can use it as {{forge.sha256.create().update("test").digest().toHex()}}
This is the documentation for the library
https://github.com/digitalbazaar/forge

**Comment by Nikhil-Nandagopal** [comment]
A user wants to add https://ably.com

**Comment by paulochang** [comment]
I'm using Supabase... but without the ability to import the supabase JS library.. it becomes a glorified cloud-hosted postgres instance.... so what's the point of using supabase instead of just hosting my own postgres instance anymore?

**Comment by benjamin-kirkbride** [comment]
@paulochang exact same situation here. I'm not even sure that it's possible to authenticate with Supabase without using their lib..

**Comment by Rishabh-Rathod** [comment]
One of the users on discord wanted to use https://github.com/nextapps-de/winbox inside Appsmith which needs this feature and also support for custom CSS addition as some libraries also need that. 

https://discord.com/channels/725602949748752515/725609493974614076/922053078042165278

**Comment by tomhollingworth** [comment]
I'd be keen to add in https://unpkg.com/mqtt/dist/mqtt.min.js for MQTT communication via WebSockets.

An alternative solution would be some kind of WebSocket data source.

**Comment by alvin-reyes** [comment]
We have a request to send encrypted and signed messages to a persistent database and can only be done with a specific library. If we can somehow have support on this, that would be extremely great. :)

**Comment by billyrudi** [comment]
questo interessa anche a me

**Comment by jingrenlim** [comment]
We have a use case where we have image and pdf files to package into a zip folder and initiate a download. If we could import libraries like JSZip, that would be great help for us. Especially with the new JS Editor on appsmith. Thanks! My use case at this moment involves only public JS libraries.

**Comment by pcgeek86** [comment]
I need to install the AWS SDK so I can write custom data sources, using the JS Object feature in Appsmith.

I would like to build my own self-hosted AWS Management Console replacement, using Appsmith, since the AWS Management Console UI is terrible.

Appsmith looks really slick! Just learned about it a few moments ago and spun it up with Docker Compose, in seconds. 🚀🚀🚀

**Comment by jmgilman** [comment]
It's currently impossible to communicate to any Google service which requires a signed JWT from a service account. This means it's impossible to consume API endpoints, cloud functions, etc. that are protected by an IAM service account. 

The first step to solving this is being able to generate a signed JWT using a service account private key which means there's a need to import a third-party library for support. I'm sure there's more required - but this feature at least starts the process.

**Comment by marino-t** [comment]
> I'm using Supabase... but without the ability to import the supabase JS library.. it becomes a glorified cloud-hosted postgres instance.... so what's the point of using supabase instead of just hosting my own postgres instance anymore?

There are a lot of no-code/low-code backends platforms (perfect to pair with appsmith) that have their own js SDK.

Might it be easier to allow import of js lib from CDN instead of "installing"?

**Comment by Nikhil-Nandagopal** [comment]
Hey folks! thank you for your attention on this issue. We're still wrapping up our current JS Editor which was a massive project but we'll be picking this up right after that!

**Comment by billyrudi** [comment]
I’m waiting to use this

**Comment by Nikhil-Nandagopal** [comment]
@billyrudi we haven't begun development on this yet. We do plan to start on this in March

**Comment by msdrigg** [comment]
Also +1 to including supabase client in appsmith js libraries list

**Comment by Nikhil-Nandagopal** [comment]
@msdrigg is there any reason you don't want to connect to supabase directly with the postgres integration?

**Comment by msdrigg** [comment]
I am interested in the authentication and signup flows. Their js client makes these flows very simple and easy.

**Comment by shubh1m** [comment]
+1. Need this capability to import [JsonPath](https://github.com/dchester/jsonpath) which we need to use to extract out only relevant data from a very bulky json.

**Comment by avaranze** [comment]
This is really important for Appsmith to be viable for my use cases.

**Comment by Nikhil-Nandagopal** [comment]
@avaranze could you tell us which libraries do you need to import? It will help us plan this feature better

**Comment by sindema8** [comment]
+1 We need this to import firebase-auth and firebase-auth. This is key for authentication to our API calls

**Comment by kazhuravlev** [comment]
+1 for uuid generation

**Comment by unknown1337** [comment]
Please allow a mechanism to not only import existing NPM libraries but also 'private NPM repo's' which allow proper coding and debugging with e.g. classes, TS, auto formatting, refactoring, debugger statements, re-use off curstom created classes (e.g. logging) across projects,in e.g. VScode. I think this is a huge gain w.r.t. the build in editor

**Comment by mackgorski** [comment]
mParticle, Amplitude, Datadog

What is the progress?

**Comment by mackgorski** [comment]
> @morandalex unfortunately there is no way to do this right now. We will be working on this feature in Q1 of next year

Q1 is over :) any progress on this? :)

**Comment by mstellingwerff** [comment]
Would like to have D3.js (https://www.npmjs.com/package/d3) available for complex visualizations of data.

**Comment by mackgorski** [comment]
@Rishabh-Rathod any news on progress with these? When we will be able to use these libraries or include custom ones?

**Comment by Rishabh-Rathod** [comment]
Hey @mackgorski, we haven't begun development on this yet. We will update this thread with new timelines soon.

**Comment by unknown1337** [comment]
Dear all, I see the actions pod label was removed. Does this mean that it's unlikely to be picked up soon? May I ask you to at least support the supabase auth JS client libs soon? (and possibly the others on the list @Nikhil-Nandagopal  :))

**Comment by Nikhil-Nandagopal** [comment]
@unknown1337 yes unfortunately we haven't been able to prioritize this yet but we are keeping a keen eye on it. I think this will get picked up by end of this year. The reason we haven't added libraries out of the box yet is because we're wary of bloating the apps with unused libraries

**Comment by unknown1337** [comment]
@Nikhil-Nandagopal , thanks for your quick reply. Would it be possible to 'simply' achieve this on a self hosted appsmith instance?

**Comment by mackgorski** [comment]
> @Nikhil-Nandagopal , thanks for your quick reply. Would it be possible to 'simply' achieve this on a self hosted appsmith instance? (given the benefits of being able to include additional NPM packages)

+1 to this we could include some libraries on our own in CE self-hosted edition and then maybe even consider donating this to Open Source code for others to use. We have some apps we need to be able to integrate with libraries. Any guidance or help how to start with that on OSS would be awesome!

**Comment by Nikhil-Nandagopal** [comment]
We can provide a simple way to add libraries but the problem is that most use cases won't work out of the box. Like for D3.js, we need a way to connect it with a widget and specify how to plot the chart. This is why simply importing custom libraries is non trivial.

**Comment by slysiou** [comment]
Hi, I can understand for visual element. But, I was thinking of back-end lib. With JS Objects Editor, this will be very powerfull!

**Comment by Nikhil-Nandagopal** [comment]
@slysiou for backend libraries, we'll need a different approach of being able to achieve that. This feature only talks about frontend libraries right now

**Comment by mackgorski** [comment]
Yes but the simple implementation should enable users to work with libraries such as Amplitude or Datadog for simply sending events with parameters or OneLogin to get info about users ACLs to know if a user can perform an action or not. So, still would be very useful to have this.

**Comment by Nikhil-Nandagopal** [comment]
@mackgorski yes that use case we'll definitely handle

**Comment by juandl** [comment]
any update about this?

**Comment by Nikhil-Nandagopal** [comment]
Hi @juandl unfortunately we don't have an update on this issue yet. We should have some idea in a week or 2 and we'll post the plans for this then!

**Comment by HimakeerthiSatheesh** [comment]
Is there a way we can use the JS snippets + Firebase Admin SDK in App Smith?

**Comment by muezz** [comment]
I would like addition of Danfo JS or a an equivalent library that lets me automate excel related tasks.

My particular scenario is that the user chooses an excel file and I would use the library to trigger a set of tasks that will "re"-organize the data and give it back to me in a better and more use-able format. This works in my situation because the file chosen by the user will always be in the same format (it is system generated like bank account statement).

**Comment by Deanang** [comment]
> ## Summary
> Import additional JS libraries that I can use. Creating this issue as a placeholder
> 
> * Support CDN based and JS SDK
> 
> ### List of library support requested by users
> * jsPDF
> * https://www.npmjs.com/package/node-forge
> * [firebase-admin](https://www.npmjs.com/package/firebase-admin)
> * segment library
> * https://github.com/digitalbazaar/forge
> * firebase-auth
> * [JsonPath](https://github.com/dchester/jsonpath)
> * supabase js client for authentication and signup flows.
> * mParticle
> * Amplitude
> * Datadog
> 
> Please mention the library you would like to use with Appsmith using this feature.

Please add mathjax pls.

**Comment by slysiou** [comment]
I would like to use https://parseplatform.org/ (similar to Firebase or supabase)

**Comment by bharath31** [comment]
Hey @juandl! We've prioritized this feature and we're actively working on it. We should have a rough release timeline by the end of next week.

**Comment by satbir121** [comment]
> > ## Summary
> > Import additional JS libraries that I can use. Creating this issue as a placeholder
> > 
> > * Support CDN based and JS SDK
> > 
> > ### List of library support requested by users
> > 
> > * jsPDF
> > * https://www.npmjs.com/package/node-forge
> > * [firebase-admin](https://www.npmjs.com/package/firebase-admin)
> > * segment library
> > * https://github.com/digitalbazaar/forge
> > * firebase-auth
> > * [JsonPath](https://github.com/dchester/jsonpath)
> > * supabase js client for authentication and signup flows.
> > * mParticle
> > * Amplitude
> > * Datadog
> > 
> > Please mention the library you would like to use with Appsmith using this feature.
> 
> Please add mathjax pls.

@Deanang What is the use case for Mathjax? It looks like a component library and would need to be developed as a widget.

**Comment by Deanang** [comment]
> > > ## Summary
> > > Import additional JS libraries that I can use. Creating this issue as a placeholder
> > > 
> > > * Support CDN based and JS SDK
> > > 
> > > ### List of library support requested by users
> > > 
> > > * jsPDF
> > > * https://www.npmjs.com/package/node-forge
> > > * [firebase-admin](https://www.npmjs.com/package/firebase-admin)
> > > * segment library
> > > * https://github.com/digitalbazaar/forge
> > > * firebase-auth
> > > * [JsonPath](https://github.com/dchester/jsonpath)
> > > * supabase js client for authentication and signup flows.
> > > * mParticle
> > > * Amplitude
> > > * Datadog
> > > 
> > > Please mention the library you would like to use with Appsmith using this feature.
> > 
> > Please add mathjax pls.
> 
> @Deanang What is the use case for Mathjax? It looks like a component library and would need to be developed as a widget.

I am creating a cms which houses searchable past year mathematics questions and solutions. The mathematics symbols need mathjax to be rendered properly.

**Comment by thanhloc1993** [comment]
+1 for CryptoJS

**Comment by bharath31** [comment]
JS library to encode/decode JWT within Appsmith client

- https://www.npmjs.com/package/jsonwebtoken
- https://www.npmjs.com/package/jose

**Comment by bedoyanl** [comment]
https://developers.arcgis.com/javascript/latest/install-and-set-up/

It would be great to be able to use the ESRI JS libraries into Appsmith. Helpful for field crews who are unfamiliar with ESRI.  Thank you appsmith for making your resource open source so that folks can use all sorts of applications.

**Comment by bedoyanl** [comment]
I can connect to a public service for adding, deleting or editing features with a url. But would like to call the ESRI js library with this command:
addFeatures({
  url: featureServiceLayerUrl,
  features: [featureToAdd],
  authentication
})

**Comment by bedoyanl** [comment]
https://developers.arcgis.com/arcgis-rest-js/install/#browsers
I should have specified, sorry.
Having these specific npm installations would be very helpful:
npm install @esri/arcgis-rest-request
npm install @esri/arcgis-rest-feature-service
npm install @esri/arcgis-rest-geocoding
npm install @esri/arcgis-rest-routing
npm install @esri/arcgis-rest-demographics
npm install @esri/arcgis-rest-portal

**Comment by samlander25** [comment]
as an aside: axios would be brilliant as the current api bulder doesnt cover every use case. sometimes we need to be able to manage the resonse ourselves. Currently I dont see any way of using an authenticated API for downloading a file. I am building a communication hub that also includes emails and downloading attachments. at present, to use the current system requires me generating a random download link and feeding it into the download() function. this is not ideal, even though its just for a moment it is still exposing publicly a file. Much better if i could just do my own axios call and handle the response directly.

**Comment by juandl** [comment]
> Hey @juandl! We've prioritized this feature and we're actively working on it. We should have a rough release timeline by the end of next week.

Hi Guys! hope you are doing well, any update on this feature?

**Comment by Nikhil-Nandagopal** [comment]
@juandl we are testing it out now internally. Could you share which libraries are you looking to integrate? We have some limitations with libraries that rely on xhr requests and the window object

**Comment by juandl** [comment]
> @juandl we are testing it out now internally. Could you share which libraries are you looking to integrate? We have some limitations with libraries that rely on xhr requests and the window object

Mostly internal libraries, we have some internal libraries like "helpers" nothing related with xhr or using window object

**Comment by bharath31** [comment]
@juandl could you let us know where these internal libraries are hosted? Are the private libraries? Would you in the future require Appsmith to host them for you?

**Comment by juandl** [comment]
> @juandl could you let us know where these internal libraries are hosted? Are the private libraries? Would you in the future require Appsmith to host them for you? 

We hosted in popular providers cdn, I think that would be the best way, same as similar platforms as appsmith

**Comment by a-c-m** [comment]
Being able to track usage (segment, analytics etc) is critical to understanding how tools are used. Very big +1 for support for a way to achieve this.

**Comment by bharath31** [comment]
@a-c-m can you share which libraries or analytics providers you are specifically looking to integrate?

**Comment by a-c-m** [comment]
Personally, https://segment.com/ and probably Google Analytics. But really I would like something more deeply integrated for analytics, similarly to https://docs.retool.com/docs/analytics, so you have the ability to trigger payloads to the analytics service at specific events in the app, as well as more generally tracking.

**Comment by deepaknverma** [comment]
it will be good to have cloud sdks part of this. Most of the solutions are hosted on cloud and would be good to have ability in appsmith to perform cloud operations

**Comment by bharath31** [comment]
@deepaknverma thanks for the suggestion. is there a specific cloud SDK you would be interested in using? could you also share your use case?

**Comment by bedoyanl** [comment]
Thank you for getting this feature rolling appsmith team! I have tried the demo and am getting this issue when trying to install https://js.arcgis.com/4.25/ as a custom library. 
https://developers.arcgis.com/javascript/latest/install-and-set-up/
<img width="400" alt="Screen Shot 2022-12-05 at 9 49 36 AM" src="https://user-images.githubusercontent.com/80067766/205707965-31298983-d931-4362-9d0b-34e8ef7433ca.png">

**Comment by chriscervantes** [comment]
> it will be good to have cloud sdks part of this. Most of the solutions are hosted on cloud and would be good to have ability in appsmith to perform cloud operations

we want AWS-SDK in particular.

**Comment by bharath31** [comment]
> Thank you for getting this feature rolling appsmith team! I have tried the demo and am getting this issue when trying to install https://js.arcgis.com/4.25/ as a custom library. https://developers.arcgis.com/javascript/latest/install-and-set-up/ <img alt="Screen Shot 2022-12-05 at 9 49 36 AM" width="400" src="https://user-images.githubusercontent.com/80067766/205707965-31298983-d931-4362-9d0b-34e8ef7433ca.png">

@bedoyanl This seems to be an invalid URL. Could you please paste a URL to the library's index file? Also make sure that the library has a UMD build. You can learn more about finding custom JS libs here- https://github.com/appsmithorg/appsmith/issues/18593

**Comment by OvrAp3x** [comment]
Would like to use appwrite https://appwrite.io/
as a firebase alternative.

**Comment by praneetloke** [comment]
AWS SDK would be nice to have especially since https://github.com/appsmithorg/appsmith/issues/8377 isn't supported yet. The SDK would allow one to manually handle AWS service interactions via an AppSmith `JSObject`, all while leveraging the AWS SDK capability to load credentials from the default environment. Assuming that the `JSObject` functions run on the server and can access the host environment? I _think_ it should just work but I don't know the AppSmith engine's execution environment well-enough to know if something else might pose a problem.

**Comment by bharath31** [comment]
@praneetloke the [AWS JS SDK](https://sdk.amazonaws.com/js/aws-sdk-2.410.0.min.js) will be supported on Appsmith :)

Re: credentials, AWS has a [guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-browser.html) on setting credentials in the web browser. I've tried using a Cognito Identity Pool ID to authenticate requests and can confirm that it works.

**Comment by bharath31** [comment]
🚀  Update on release timelines: The ETA for the general availability of this feature is Friday, Jan 27.  However, this is already available on our release branch- https://release.app.appsmith.com/.  Feel free to take it out for a spin and let us know your feedback 🙂

**Comment by bharath31** [comment]
> hi guy, The web3 sector is supposed to work only frontend so it can be really helpful to add `ethersjs` as web3 library to unlock blockchain use cases to interact with evm smart contracts. here the library: https://docs.ethers.org/v5/

@morandalex could you please check this [issue](https://github.com/appsmithorg/appsmith/issues/18351) out? we have a live deploy preview that allows you to test out web3 use cases.

**Comment by bharath31** [comment]
> 🚀 Update on release timelines: The ETA for the general availability of this feature is Friday, Jan 27. However, this is already available on our release branch- https://release.app.appsmith.com/. Feel free to take it out for a spin and let us know your feedback 🙂

Apologies- there's been a slight delay in the release. We're planning to roll this out next week 🙂
