### ISSUE TITLE
[Bug]: UI cutoff in the response tab of query pane in this particular scenario

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

UI cutoff in the response tab of query pane in this particular scenario

### Steps To Reproduce

1. Create a postgres ds
2. Create a query to select with a limit of 1. [e.g: SELECT * FROM users Limit 1;]
3. Reduce the Response/Error section [as per the video]
4. Click on run
5. Note the response section automatically expands, however the result row is cutoff though there is space for it to be shown completely.

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/YoHlPBtbCkD3P73F

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore
