### ISSUE TITLE
[Bug] Seeing an error toast when none is expected during evaulation

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2432]
## Description

A toast shows up saying "Unexpected error occurred while evaluating the app" when an action is triggered which leads to some widgets reloading. Before the widget loads with the new data, a toast stating the aforementioned error is displayed.

This particular state (before the new data is put in the widgets) is expected and the error is breaking the user expectations.

Attaching the following video which captures this issue : 
https://www.loom.com/share/b0592774411547c0b679bc45d463839a

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can we cherry pick this onto master

**Comment by hetunandu** [comment]
> @hetunandu can we cherry pick this onto master

Already have. It is not getting deployed because of onboarding test failure. Working with arpit on this

**Comment by pcg-software** [comment]
Been banging my head over this all day. Safe to say it's internal bug yes?
