### ISSUE TITLE
[Bug]: Even if Save button is disabled on an Edit DS page, the save changes pop up comes up

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Even if Save button is disabled on an Edit DS page, the save changes pop up comes up

### Steps To Reproduce

1. Click on create a new ds, and choose say a Firestore DS. 
2. Do not enter any details. Note that the Save button is rightly disabled on this page.
3. Try to navigate to some other page or widget
4. Note that the Save/dont save dialog comes up prompting user to save or not

This feels unnecessary at this point, as Save button was anyway disabled and did not allow the user to Save. What would be the need for the save dialog box to come up?  

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/PCpKP71LxmLAbQXA

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore, tested with firestore. I guess it got fixed in the meantime
