### ISSUE TITLE
[Bug]: Text/placeholder shift in Text area

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#24338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Text/placeholder shifts when we land on query pages.

https://github.com/appsmithorg/appsmith/assets/39921438/79dfb69f-4bb6-4f47-abd8-9e8095bf89bf

This happens in all such places

### Steps To Reproduce

1. Visit any app.
2. Go to any JS Object/Query editor 

### Environment

Production

### Version

Cloud

**Comment by shadabbuchh** [comment]
@tanvibhakta It is still reproducible in https://github.com/appsmithorg/appsmith/pull/24387

**Comment by tanvibhakta** [comment]
Closing this in favour of https://github.com/appsmithorg/appsmith/issues/24460
