### ISSUE TITLE
[Feature]: Option to Show Navigation on All pages, including hidden ones

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#24348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Say I have a page with a table listing products, then when you click on a product, I want to navigate to a "Product Detail" page. I don't want this to appear on the navigation as it's a page at the same level as the product list page, since clicking on the detail page with no context is meaningless.

However, if I select not to show the page in the navigation, it doesn't show the nav bar at all when you click on that detail page, so users can't go elsewhere unless I add some specific link on the detail page back to some other page that does have nav enabled

### Why should this be worked on?

It would be nice to have the option to enable "show pagination on all pages, including hidden pages or pages that have disabled navigation."

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3g5cb0)

**Comment by ykag** [comment]
I would like to see this added to AppSmith too, for the same reasons that the original issue creator describes, we have sub-level pages that we don't want shown on a main navigation bar, but we require the main navigation to be shown on all pages.

We have so many pages too, we can't realistically use buttons or widgets to create a menu on each page, this would take up a lot of time and become a maintenance nightmare - although it might become a feasible option when the reusable widgets feature is implemented.
