### ISSUE TITLE
[Feature] Parse bindings with AST

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2435]
## Summary
Replace current string based lookup for references with AST

## Motivation
We find dependencies to a particular binding with very coarse string based lookup today. This can be improved with AST for more robust parsing

**Comment by oeddyo** [comment]
Thanks for the issue. 

Two questions:
1. Is there any prior benchmarking against AST that you can share? One major concern is since the eval takes off so frequently in appsmith, the performance might be critical. 
2. Any preferred AST library? Acron and espress both seem decent

**Comment by hetunandu** [comment]
Hey @oeddyo thanks for taking the time and working on this. Really appreciate it 😁
1) We have not done any performance benchmarking for AST vs our current implementation. We do have some perf logging for the different sections of the app, once you implement AST, you can compare it against the old numbers.
2) Acorn is already a dependency via Tern so I think that should be good enough.

**Comment by ofpiyush** [comment]
@oeddyo Thanks for taking this up! We recently ran into a bug where parsed AST would have made our lives easier.

To scope it things out, I've taken a very cursory look at `acorn` and `acorn-walk` as we already have them as dependencies.

As far as I can tell, this function is the only place you'll need to parse and work with the AST.

https://github.com/appsmithorg/appsmith/blob/ddad022ffff60edc2be6531b4cd154f119ff9a3e/app/client/src/workers/evaluation.worker.ts#L1268-L1293


> Is there any prior benchmarking against AST that you can share?

Based on very quick and dirty eyeball numbers, parsing and walking the AST is slower (~3x-ish), but still within the order of magnitude of the current solve. Logic to extract expressions should not add a lot more than that.

That's not too bad, especially considering that eval time is not our primary bottleneck now and this is a small-ish part of entire eval.

> One major concern is since the eval takes off so frequently in Appsmith, the performance might be critical.

@hetunandu has made changes to avoid a lot of the unnecessary evals and parsing, so this is much better now!
Parsing AST would ensure correctness and avoid weird bugs. Definitely worth paying the small price in perf tbh.

Disclaimer: I am not very familiar with the ESTree spec or acorn, and this is based on an hour-ish of playing around, so take the rest of this more as a starting point.

Once you've parsed the `path` string, you'll need to process at least the `Identifier` and `MemberExpression` node types, maybe more.
Beware that you'll see things like `Table1` as an Identifier where the entire expression is `Table1.selectedRow.email`. So you'll need to ignore the Identifiers which have MemberExpression ancestors.

I hope this helps you get set on the right path. This is definitely a fun problem to work through. Really looking forward to your PR!

**Comment by hetunandu** [comment]
Hey @oeddyo since we did not see any movement on this issue since some time, we are thinking it should be picked up by the internal team. Let me know if you still plan to work on this.
