### ISSUE TITLE
[Feature]: Autocomplete needs to accommodate lower case entry

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Autocomplete is currently case-sensitive and does not automatically detect widget names when typed in lower case. For example: `text4.` will not produce any suggestions, whereas `Text4.` will show expected suggestions

https://www.loom.com/share/1b3d00f899114e0ea0070c43bfc55d5clowercase

### Why should this be worked on?

To help user experience be more organic and easy - not have the user capital case the first letter to enable autocomplete

**Comment by bharath31** [comment]
this is the expected behaviour
