### ISSUE TITLE
[Bug]: Glitchy key-value fields on the API query page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- placeholders on the API query page glitch when deleting empty rows (see video for details)
- toggle between headers and params properties on the query page and observe the second key-value row adjust itself to accommodate left padding

### Steps To Reproduce

1. Add an API query to an app and try to delete the placeholder informa

### Environment

Production

### Issue video log

https://www.loom.com/share/9789539c98b64e35a0c57cffb4c57fb0

### Version

Cloud

**Comment by shadabbuchh** [comment]
Fixed here: https://github.com/appsmithorg/appsmith/pull/24012

**Comment by shadabbuchh** [comment]
Verified in release.


https://github.com/appsmithorg/appsmith/assets/39921438/2b01f29a-5a22-4e63-9ca4-0d00ed3320f1
