### ISSUE TITLE
[Bug]: In the import modal Save button is enabled even without entering data when Read only mode is selected. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to import or fork an app, In the import modal Save button is enabled even without entering data when Read only mode is selected. 

### Steps To Reproduce

1. Try to import an app by choosing an application json file which is having postgres and other DS configured
2. In the import modal that comes up, for PostGreSQL DS, Read/Write option is selected by default. 
3. Save button is correctly disabled as no values are entered in any field. 
4. Choose Read only option
5. Note that the Save button is enabled here though no values are still entered in any field

<img width="1436" alt="Screenshot 2023-06-13 at 9 15 31 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/13d55130-a6be-4be9-b088-64e7aaecb326">
<img width="1431" alt="Screenshot 2023-06-13 at 9 15 23 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/3e3e6d64-8f55-4cfc-95e6-bac5cd4f1713">
ou

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
same behaviour exists in the "normal" datasource form as well, and my argument is that it is valid: Changing from read-write to read-only correctly renders the form dirty, and enables the save button
