### ISSUE TITLE
[Bug]: Queries containing colons `:` cannot be executed in MySQL.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#24381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Queries that contain colons `:` cannot be executed in MySQL because they will always result in the error: `java.lang.IllegalStateException: Parameter at position 0 is not set`. For example, the following query cannot be executed in Appsmith but can be executed in DBeaver:
```sql
SELECT @media_id := MAX(id) FROM media;
```

WorkArround:

```sql
SELECT MAX(id) AS media_id FROM media;
```

### Steps To Reproduce

1. Create a table.
```sql
CREATE TABLE media (
  id INT AUTO_INCREMENT PRIMARY KEY,
  media_type VARCHAR(50),
  entry_datetime DATETIME,
  discovery_notes TEXT,
  short_list INT
)
```

2. Insert data into the table.

```sql
INSERT INTO media (media_type, entry_datetime, discovery_notes, short_list)
VALUES ('book', '2023-06-12 10:00:00', 'Some discovery notes', 1),
       ('movie', '2023-06-11 15:30:00', 'Another discovery notes', 0),
       ('music', '2023-06-10 08:45:00', 'More discovery notes', 1);

```

3. Write the SELECT query with colons and you will see it fails.
```sql
SELECT @media_id := MAX(id) FROM media;
```

4. Use the same query in DBeaver and you will see that it works correctly.

5. Use the workaround in Appsmith and you will see that it works correctly.
```sql
SELECT MAX(id) AS media_id FROM media;

```

### Environment

Production

### Version

Cloud/ Self Hosted v1.9.21

**Comment by rohan-arthur** [comment]
this works now
