### ISSUE TITLE
[Task]: Remove `Default Role for all users` from Default Roles list, in `Groups & Roles tab` in Role configuration screen

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#24398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

The **Default Role for All Users** exists for all users, and we should not let anyone be able to edit the configurations for the same. Only the Instance Administrators should be able to access the role. 

At the moment, anyone with **Create Permission Groups** permission can create a Permission Group and give permissions for **Default Role for All Users**. Hence, we want to remove this role from the GAC Screen, so that only the Instance Administrators are shown this Role and can edit it's configuration.

**Comment by riteshkew** [comment]
Done.
