### ISSUE TITLE
[Bug]: Un-assignable groups on user edit page is not disabled similar to un-assignable roles

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#24394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I go to the user edit page under GAC, I am able to un-assign a group which should be un-assignable based on remove user permission, which then leads to error state. that

### Steps To Reproduce

1. Go to the user edit page under GAC
2. Un-assign a group that should be un-assignable based on the remove user permission.
3. Notice that it is not disabled and you are able to un-assign it. 
4. When you click on save button, it leads to an error state. 

### Environment

Production

### Version

Self hosted - latest

**Comment by ankitakinger** [comment]
Re-opened for the backend changes which are yet to be picked up.

**Comment by shubham7saxena7** [comment]
since only instance admin has access to the users tab, and they have access to all possible groups, there are no un-assignable groups
<img width="1518" alt="Screenshot 2023-06-15 at 1 07 49 PM" src="https://github.com/appsmithorg/appsmith/assets/136057998/a33f29be-4c58-4f42-b6f1-684ff3228e6b">

**Comment by ankitakinger** [comment]
@shubham7saxena7 makes sense. We can close this issue in that case.

**Comment by ankitakinger** [comment]
@shubham7saxena7 sorry I just realized. With SCIM, we may have SCIM groups that should not have remove users access even for the Instance Administrator. Correct me if I'm wrong @trishaanand @nsarupr

**Comment by shubham7saxena7** [comment]
@ankitakinger, I had a discussion with @trishaanand  and this makes sense. I am working to raise a PR to manage the group permissions from the backend
