### ISSUE TITLE
[Bug]: Fix Oracle documentation page link on Oracle query page. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#24399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Fix Oracle documentation page link on Oracle query page.

### Steps To Reproduce

1. Create a new Oracle query. 
2. Click on the documentation logo. 

### Environment

Production

### Version

cloud, self hosted

**Comment by btsgh** [comment]
Verified on release.
