### ISSUE TITLE
[Bug]: Property pane does not automatically scroll to display success/failure blocks of a trigger fields

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When events field is at the end of the property pane, expanding the callback section does not automatically bring the success/failure blocks in view, user has to scroll the property pane to view the expanded blocks.

![image](https://github.com/appsmithorg/appsmith/assets/79509062/f7112cdf-5f6f-45a4-b19f-b1bdb5f5aea1)

### Steps To Reproduce

1. Drop a category slider widget or any other widget that's got a trigger field at the end of the property pane
2. Configure a parent action, like `navigate to`
3. Click on Callbacks and notice the property pane does not automatically bring the success/failure blocks into view - the interaction should be the same as adding a new event to the trigger field - automatically adjust to fit all fields within viewport 

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore
![Screenshot 2024-09-19 at 14 53 28](https://github.com/user-attachments/assets/cc73520d-e633-4d56-80f7-93f5a4179542)
