### ISSUE TITLE
Old Templates Refresh

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#24409]
We are refreshing all old templates, fixing bugs, removing old widgets, checking broken and outdated datasources, etc.

**Comment by jacquesikot** [comment]
@danciaclara you can add the list or order notion doc here so we can use this to track the progress

**Comment by yozlet** [comment]
Glad to hear this is happening, I was trying the Customer Messaging Tool yesterday and it still uses the old List widget.

**Comment by rahulbarwal** [comment]
@jacquesikot lets take care of outdated widgets on templates next week.

**Comment by jacquesikot** [comment]
Vehicle Maintenance app
Fund raising CRM
Whatsapp CRM
Business Analytics Dashboard
Customer Messaging tool
Maintenance Order Management

The following templates have been updated with the latest List and Button widgets where applicable.
