### ISSUE TITLE
[Bug]: Deployed app link for a git connected app incorrectly points to current branch + page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking on `Current deployed version` on a git connected app - from a branch and from a page that does not exist on the master branch causes incorrect page and message to be displayed to a user

![image](https://github.com/appsmithorg/appsmith/assets/79509062/e24e608c-c814-46bb-b6ca-982db8bad42e)

### Steps To Reproduce

1. On a git connected app - navigate to a branch
2. Create a new page, drop a few widgets
3. Click on `current deployed version` on the top right and observe current branch + new page are displayed instead of current deployed app

### Environment

Production

### Issue video log

https://www.loom.com/share/8f79a07b550f4497aa319903647dd8f8

### Version

Cloud

**Comment by riteshkew** [comment]
Resolved as part of default resources.
