### ISSUE TITLE
[Task]: Remove papa parse package. Use SheetJS instead

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#24442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We are using both papa parse and sheet js in our code. Papaparse is used for parsing csv and SheetJS for parsing XLSX/XLS files. SheetJS also supports parsing csv files. We can thus remove Papaparse from our codebase and make the bundle size smaller.

**Comment by somangshu** [comment]
@berzerkeer check this out, see if you can pick this up!

**Comment by berzerkeer** [comment]
> @berzerkeer check this out, see if you can pick this up!

Sure @somangshu , I will take a look.
