### ISSUE TITLE
[Enhancement] Add an internal property to detect the action triggered in a table

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2444]
## Description

Today to detect the row of the action triggered in a table, we use the selectedRow property. This however breaks if a user enables the multi-select option of a table because it populates the selectedRows property which also allows for deselection.

To avoid this, can we introduce a `triggeredRow` property which is set with the last row from which the action was triggered

**Comment by somangshu** [comment]
@Nikhil-Nandagopal we already have `selectedRows<Array>` in the table when multi select is on. What problem will `triggeredRow` solve. 

However I think this should be an action `onRowSelected` which can trigger a certain action.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal I might be wrong here, But I feel bulk operations and row level operations are two separate things and should be considered separately. 

IIUC what we are trying to achieve here is get the `last selected row` in the table?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu I want to delete a row in a multi select table that has a button called delete. How do I bind the delete query to the row that was clicked?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal As you said have a triggered row? This will be the same as selected row when we are have multi select disabled?

**Comment by somangshu** [comment]
Note:

- TriggeredRow will refer to the row where an action took place (button click)
- The action click should not trigger select row.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal for this requirement, we plane to add another internal property `triggeredRow` which will be accessible in the table actions setting, You can use this property to fetch the last selected row while executing an action. This will be available for single / multi select table. This will only store the `selectedRow` in `triggeredRow` and not do anything while deselecting.
