### ISSUE TITLE
[SCIM - Task - FE]: Frontend tasks for Admin Settings

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#24451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ankitakinger** [comment]
Closing this issue, I have split this task into multiple smaller tasks:
https://github.com/appsmithorg/appsmith/issues/25264
https://github.com/appsmithorg/appsmith/issues/25265
https://github.com/appsmithorg/appsmith/issues/25266
https://github.com/appsmithorg/appsmith/issues/25267
https://github.com/appsmithorg/appsmith/issues/25268
https://github.com/appsmithorg/appsmith/issues/25269
