### ISSUE TITLE
[Feature]: make column widths adjustable in the query response

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#24465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

context: https://theappsmith.slack.com/archives/C040LHZN03V/p1686734826608749

currently the column widths are fixed, and cannot be dragged to resize. 

### Why should this be worked on?

I can't see the contents of fields beyond a certain length in the query response. Fixing this will help the user experience

**Comment by Irongade** [comment]
https://theappsmith.slack.com/archives/C040LHZN03V/p1686734826608749

**Comment by btsgh** [comment]
does not require testing as skiptestplan added to PR
