### ISSUE TITLE
[Bug]: Email Setting SMTP Can't convert socket to TLS

### ISSUE THREAD

**Issue by jrsittirat** [appsmithorg/appsmith#24509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Email Setting SMTP Can't convert socket to TLS.
![image](https://github.com/appsmithorg/appsmith/assets/136780529/3423a1ca-73c0-4ece-b910-e52cd9940435)

### Steps To Reproduce

1. Admin Setting > EMAIL 
2.  Set smtp.domain.com
3. Enable TLS or None 

### Environment

Production

### Version

1.9.21

**Comment by jrsittirat** [comment]
@sharat87  Thank you for info. 
I tried. not work
I not sure, Appsmith 's support TLS 1.1, 1.2, 1.3 ( smtp enable 1.2 Only )

**Comment by sharat87** [comment]
@jrsittirat, sorry just seeing this. Can you share the logs of the Appsmith container from when you tried using explicit TLS please?

**Comment by jrsittirat** [comment]
> @jrsittirat, sorry just seeing this. Can you share the logs of the Appsmith container from when you tried using explicit TLS please?

![image](https://github.com/appsmithorg/appsmith/assets/136780529/47753078-c9bb-44d3-9726-dd54c9d7db74)
![image](https://github.com/appsmithorg/appsmith/assets/136780529/f3bcf033-a92a-4490-8f7c-7dcb45162202)

**Comment by pakinming** [comment]
### I encountered this issue as well with the Datasource: SMTP connection failed when using TLS.

![Screenshot 2567-11-11 at 17 16 14](https://github.com/user-attachments/assets/48da8f7a-0cc8-4098-a591-abc9c0ce14aa)

### logging error: Could not convert socket to TLS
![Screenshot 2567-11-11 at 17 17 35](https://github.com/user-attachments/assets/f3fad346-7dcf-423e-bdaf-444bf8bcbe70)

**Comment by sharat87** [comment]
Hey, sorry for not responding @jrsittirat, that error is implicit-TLS, trying to convert the socket to TLS. Explicit TLS is where we use the `STARTTLS` extension to the SMTP protocol.

@pakinming, thanks for sharing, but it's the same as above.

Appsmith doesn't support connecting to SMTP with implicit-TLS. Only explicit TLS (via `STARTTLS`) is supported today. We have an issue for adding support for implicit TLS at #19690. Thank you!
