### ISSUE TITLE
[Feature]: Select Widget allows entry of free text

### ISSUE THREAD

**Issue by adrian-stephens** [appsmithorg/appsmith#24514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A select widget requires selection of one of the alternatives listed.
However, there is a use case for such a widget that also allows entry of free text,  i.e., text that is not in the list of 
options.
For example,  I have a database of articles by member organisations.  When entering an article,  the member organisation is well-defined and should be a "constrained" selection.  But the authors change frequently.  A member might forward the request to provide an article to an individual I have never seen before.  With the current functionality,  I have to make the Author field a free text entry,  but it would save me time if it was a list of everybody who was previously an author, and allow me to add an author not on that list.

### Why should this be worked on?

It saves time for users of this feature,  adding to the power of the user-interface.

**Comment by Nikhil-Nandagopal** [comment]
Thanks for the feature request. We're tracking this here #6928

**Comment by adrian-stephens** [comment]
For what it's worth,  I did find a workable workaround.
I have a select widget to select among existing authors.   I add an "<other>" entry to the select options.
I add an onSelectChanged javascript to check for "<other>" and show a modal for free text entry of a value.  This is written to the table.updatedRows entry.  This gets sent to the backend by the multiple-row save javascript function.

The only awkwardness with this is that "<other>" is shown in the table after a value has been supplied by the modal.  This placeholder is replaced by the user supplied value once the change is written to the backend,  and once the updated dataset has been read.
