### ISSUE TITLE
[Task]: Create Category token for switch component

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24536]

**Comment by shadabbuchh** [comment]
Bug:

1. Incorrect background color in Not selected & disabled state. Expected is `#cdd5df`
![Screenshot 2023-08-09 at 5.55.46 PM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/4fa4269b-d306-4569-a665-007b9e070024)

2. Incorrect background color in Selected & disabled state. Expected is `#4c5664`
![Screenshot 2023-08-09 at 5.57.07 PM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/2148bf12-1ebc-4b6b-b1c9-72bdc81cec6f)
