### ISSUE TITLE
[Task]: Create Category token for link component

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24549]

**Comment by Sripriya93** [comment]
For Primary Link - On Active state we should see #ca520f, but instead we are seeing only default state font color. 
On Focus state No particular color is defined as it is same as default, unlike Secondary Link.

CC: @albinAppsmith 

Moving to Sprint Backlog

**Comment by albinAppsmith** [comment]
Fixed all these
