### ISSUE TITLE
[Bug]: MSSQL Count query breaks application

### ISSUE THREAD

**Issue by berzerkeer** [appsmithorg/appsmith#24556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Video : https://vdqm24wed6.vmaker.com/record/EAF4tKnxpg8bC1IE

### Description
- When executing a count query for MSSQL the application breaks.

### Steps To Reproduce

1. Connect to a MSSQL datasource.
2. Create a new SELECT query.
3. Write a query to get the total records count. ( SELECT COUNT(*) FROM <table-name> )
4. Click `Run` to execute the query.
5. App breaks.

## Workaround
Provide a column name using the `as` keyword e.g. `select @@version as version`.

### Environment

Release

### Issue video log

https://vdqm24wed6.vmaker.com/record/EAF4tKnxpg8bC1IE

### Version

Cloud / Self - Hosted 1.9.22

**Comment by sumitsum** [comment]
Related: https://github.com/appsmithorg/appsmith/issues/25091

**Comment by sumitsum** [comment]
RCA: the app seems to crash because it expects the query response to be in a key value format where the key is non empty. However, in this case, the key is an empty string e.g. `{"": "100"}`

**Comment by berzerkeer** [comment]
can we close this @sumitsum  ?

**Comment by berzerkeer** [comment]
Thanks @sumitsum Got it !

**Comment by berzerkeer** [comment]
Thanks @sumitsum Got it !
