### ISSUE TITLE
[Bug]: 504 error while merging branches

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#24569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
Getting a 504 error when performing a git merge operation. 

![Screenshot 2023-06-08 at 4 43 05 PM](https://github.com/appsmithorg/appsmith/assets/8299030/d19bac87-ad2a-4c7a-87b0-5d4a7aee39d0)

### Steps To Reproduce

![Screenshot 2023-06-08 at 4 43 05 PM](https://github.com/appsmithorg/appsmith/assets/8299030/93b9ee49-168c-4e92-b59b-3e0ed8b665f4)

### Environment

Production

### Version

Self hosted

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_iucss)

**Comment by ginilpg** [comment]
* Refer to [slack thread1](https://theappsmith.slack.com/archives/C0341RERY4R/p1686209222717389) 
* Refer to [slack thread2](https://theappsmith.slack.com/archives/C03GQQ06934/p1686223013126899)

**Comment by nidhi-nair** [comment]
Closing as irreproducible. Please re-open and provide the following details if this issue is persistent.

1. Logs from git failure
2. Details of Appsmith deployment
3. Details of git provider being used
