### ISSUE TITLE
[Bug]: Unable to Re-Authorize Google Sheets Datasource After Forking App to New Workspace

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#24566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After forking an app that is connected to a Google Sheets datasource to a new workspace, users get an error when trying to re-authorize the datasource. 
[Front thread](https://app.frontapp.com/open/cnv_116n09e4?key=iI2Mr-RePsIhbhb09vxQqNDQ-jloEqUS)

![image](https://github.com/appsmithorg/appsmith/assets/101268423/9edf72a1-2695-4ab8-9c07-be253cdfb5f1)

![image](https://github.com/appsmithorg/appsmith/assets/101268423/f06a35c9-3acf-4cc1-85bc-4c7cf5256657)

![image](https://github.com/appsmithorg/appsmith/assets/101268423/1add6b43-88ab-4f05-b712-eb581b23e742)

The workaround is to create a new GS datasource from scratch and connect the queries to it.

### Steps To Reproduce

1. Create an app with **Google Sheets** as datasource.
2. Fork it to another workspace.
3. When opening the app, Appsmith will ask us to re-authorize.
4. If trying to re-authorize, errors are displayed.

### Environment

Production

### Version

Cloud v1,9,23

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fijik)

**Comment by sneha122** [comment]
https://theappsmith.slack.com/archives/C0341RERY4R/p1686935585764669

**Comment by btsgh** [comment]
Tested and works fine
