### ISSUE TITLE
[Feature] Chart Point Click Event

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2459]
## Summary

Users need an event which can trigger an action when a bar / point / pie slice is clicked on a chart widget. This can be the 
onDataPointClick event

## Motivation

This is useful for users to perform contextual drilldown. One use case for it is to be able to view all the widget issues when clicking the widget bar on the jarvis app

**Comment by hetunandu** [comment]
This is a very useful feature. Along with this, we should also allow for the chart "slice" to have more contextual info than just the x and y coordinates. This info will be exposed with the selectedSlice object and can be read up for further querying. This is something like the id property or key property which may or may not be same as the y "label" property
