### ISSUE TITLE
[Bug]:  Calling structure api returns duplicate key error on existing datasources for which structure exists

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#24628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While calling the api/v1/datasources/structure for existing datasources, we are getting a duplicate key error. 

### Steps To Reproduce

Calling the structure api via any of the flows,

- One click table setup
- click on datasource structure reveal

### Environment

Release

### Version

Cloud

**Comment by chandannkumar** [comment]
Tested & Verified on release and LGTM
