### ISSUE TITLE
[Bug]: Amazon S3 is broken on the Fork app reconnect datasource modal 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I fork app into a new workspace, and try to reconnect the amazon s3 datasource, I see an additional field added and am unable to proceed with the 

### Steps To Reproduce

1. Fork an application containing a few datasources, including S3, into a new workspace.
2. When you select s3 in the fork reconnect modal, you see an additional option for amazon s3 service provider
3. We are unable to save the settings for this DS from the modal. 

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/s3xF3CNMq5pwU362

### Version

Cloud

**Comment by ramsaptami** [comment]
[Workaround](https://www.loom.com/share/bbbb7446728b4194a8793bdc86820ece) to activate Save button

**Comment by btsgh** [comment]
Verified
