### ISSUE TITLE
[Feature]: Add findAndModify to MongoDb query types

### ISSUE THREAD

**Issue by nzidol** [appsmithorg/appsmith#24651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add findAndModify to MongoDb query types 
https://www.mongodb.com/docs/manual/reference/command/findAndModify/ 

### Why should this be worked on?

Allows a single transaction to find and modify a record which is useful in multi-user environments and maintaining sequences.

**Comment by Nikhil-Nandagopal** [comment]
@nzidol the update query allows you to specify the document you want to search for and update using the query field so it does accomplish this

**Comment by nzidol** [comment]
But it does not return the data, so you need 2 transactions to update and
retrieve data which in multi user can go wrong.....
