### ISSUE TITLE
[Bug]: Importing an app with datasource credentials asks for reauthorization 

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#24665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When importing an application with datasource credentials it continues to ask for reauthorisation.  It is expected that the app is imported with the datasources credentials configured as supplied in the json. 

This issue is noticed when
- the target workspace has an un-authorised datasources and
- there exists a datasource with the same name as the one in the imported file

### Steps To Reproduce

1. Create a workspace. Import an application with a datasource named say "test". Import it without the datasource credentials.
2. You should see a reconnect modal asking for credentials to authorise. Skip to app and go back to home screen. 
3. Import an application with datasource credentials. The datasource name should be "test" here i.e match the existing datasource name in the target workspace.
4. You should see a reconnect modal asking for credentials to authorise.

https://github.com/appsmithorg/appsmith/assets/67054171/00cf2ec0-ea3a-4b0a-b26a-a138502eeb5b

### Environment

Production

### Version

Cloud / Self hosted - v1.9.23-SNAPSHOT

**Comment by ginilpg** [comment]
@nayan-rafiq This is a high priority one because it's resulting in a flaky test

**Comment by AnaghHegde** [comment]
As mentioned in the issue description 
- the target workspace has an un-authorised datasources and
- there exists a datasource with the same name as the one in the imported file

The above case is a valid scenario and if the ds exists, we do not modify the config values of the ds. 
Detailed discussion can be found here - https://theappsmith.slack.com/archives/C04HERDNZPA/p1689587159127389?thread_ts=1688965577.374599&cid=C04HERDNZPA
