### ISSUE TITLE
[Bug]: Forking of Dynamo DB is erroring out.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we fork an application with Dynamo DB, and enter all details in the Dynamo DB section, Test configuration fails. 

### Steps To Reproduce

1. Fork an application with Dynamo DB into a new workspace
2. Enter all details in the Dynamo DB section [Refer: https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79?pvs=4#a44f411db2a94d17841810a5d682b62d]
3. Click on Test configuration 
4. Note that it fails. 

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/XRKKwsw2ep1OMEVQ

### Version

Cloud

**Comment by ramsaptami** [comment]
[Workaround demo](https://www.loom.com/share/a6517f99031e47d1b082c5a3a06bb4be)

**Comment by NilanshBansal** [comment]
Fixed with #24683 as approved by @btsgh
