### ISSUE TITLE
[Bug]: Copy pasting a valid javascript object doesn't work in a property pane field having ValidationTypes.Object

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#24662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The evaluations should support typing a valid javascript object in a property pane field which has ValidationTypes.Object validation property in its property configuration.

The final expected data type of evaluated value in this case is Object, so copy pasting a valid javascript object should work out of the box as well. The user shouldn't need to put it inside mustache syntax

### Steps To Reproduce

1. Go to this DP https://appsmith-rl2cnfsls-get-appsmith.vercel.app/applications and DnD chart widget v2
2. Select Custom chart from "Chart Type" dropdown.
3. In the Custom Chart Data property pane, copy paste the following javascript object.
4. Actual behavior : Evaluations throw an invalid object error
5. Expected Behavior : The evaluation error should not be thrown as a valid Javascript object has been copy pasted.

Javascript Object

```
{
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'shadow'
    }
  },
  legend: {
    data: ['Profit', 'Expenses', 'Income']
  },
  grid: {
    left: '3%',
    right: '4%',
    bottom: '3%',
    containLabel: true
  },
  xAxis: [
    {
      type: 'value'
    }
  ],
  yAxis: [
    {
      type: 'category',
      axisTick: {
        show: false
      },
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    }
  ],
  series: [
    {
      name: 'Profit',
      type: 'bar',
      label: {
        show: true,
        position: 'inside'
      },
      emphasis: {
        focus: 'series'
      },
      data: [200, 170, 240, 244, 200, 220, 210]
    },
    {
      name: 'Income',
      type: 'bar',
      stack: 'Total',
      label: {
        show: true
      },
      emphasis: {
        focus: 'series'
      },
      data: [320, 302, 341, 374, 390, 450, 420]
    },
    {
      name: 'Expenses',
      type: 'bar',
      stack: 'Total',
      label: {
        show: true,
        position: 'left'
      },
      emphasis: {
        focus: 'series'
      },
      data: [-120, -132, -101, -134, -190, -230, -210]
    }
  ]
}
```

### Environment

Production

### Version

Cloud

**Comment by bharath31** [comment]
Closing this issue based on an [internal conversation](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1687407841367529?thread_ts=1686310542.940239&cid=C02K0SZQ7V3)
