### ISSUE TITLE
[Bug]: Evaluation errors don't show up when a page with existing evaluation errors is reloaded

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#24664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`__evaluations__` property doesn't have evaluation errors populated in it if a page with existing evaluation errors is reloaded.

### Steps To Reproduce

1. Go to this DP https://appsmith-rl2cnfsls-get-appsmith.vercel.app/applications and DnD chart widget v2
3. In the Chart Dataset field, remove any comma from the json values and introduce a syntax error in that property.
4. Put a debugger in componentDidUpdate and check the props for __evaluation__ key and notice that errors are present.
5. Refresh the page with the syntax errors and check the props again when the breakpoint is hit.
6. Observed behavior : Validation errors are not present in `__evaluations__` field.
7. They are actually present in `'__evaluations__` key.
8. Expected behavior : The evaluation errors should be present in `__evaluations__` key

### Environment

Production

### Version

Cloud

**Comment by rajatagrawal** [comment]
I think there is another scenario which is happening because of this bug.

1. Make validation errors on chart widget in the property pane.
2. Reload the page.
3. Click on the property pane input field which had the validation errors.
4. Observed Behavior : The red border on the property input field is missing and the pop up that shows the error message is missing.

Expected behavior : The red border and the error pop up should show up.

**Comment by bharath31** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/24664?planning-poker) with Zenhub @arunvjn

**Comment by AnandiKulkarni** [comment]
verified on page refresh -
<img width="1440" alt="Screenshot 2023-07-04 at 4 38 19 PM" src="https://github.com/appsmithorg/appsmith/assets/80756091/ac1642e3-dbc7-4001-bcfc-fd7ca1244003">
