### ISSUE TITLE
[Bug]: Mongo DB - Connection string URI - Empty key error on DS page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On choosing yes from the use connection string uri option of Mongo DS, enter the connection string from the doc: https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79?pvs=4#548f42ade97d403892d47a85ba59ec36

Note that user gets an error "Empty Key"

### Steps To Reproduce

1. Go to Create new DS, choose mongo, choose use connection string uri as yes and add the details from the above notion doc. 
2. Click on Test config, and note the error Empty Key

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/5EoOxXFcYk41en3x

### Version

Cloud

**Comment by btsgh** [comment]
Also, on forking an app with the above connection string URI set to Yes, we get an error, and are unable to fork with this setting. [Workaround, with the use connection string set to no, and all details entered, we can proceed with forking]
<img width="941" alt="Screenshot 2023-06-20 at 1 52 57 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/6d328308-73dd-4672-869a-88ee254cfbf1">

**Comment by GreenFlux** [comment]
@btsgh a user on Discord is facing a similar issue with MongoDB connection strings, but the error message is different. Is this related? 
https://discord.com/channels/725602949748752515/725609493974614076/threads/1120607300059664434

**Comment by btsgh** [comment]
I have created a separate issue for Forking, as mentioned above, and marked that as critical and marked this one as High-as there is a workaround available for this.
