### ISSUE TITLE
Make the API's marked in the screenshot below to use page id instead of application and workspace ids.

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#24671]
### Change
Make the API's marked in the screenshot use pageId instead of applicationId.

### Why
We have the page id as soon as the main bundle is initialized. 
We can not make these essential API calls unless we have the application ID. We depend on another API to get the application id making the first meaningful paint slower by 2*(300-600)ms.

### Possible way to handle it
Add an additional step to these API handlers on backend to translate page id to application id, this is an extra query, but we are ok with it.

### Considerations
Should we leave the original API end points intact for when we have the applicationId.

![image](https://user-images.githubusercontent.com/66776129/231360903-4c7238d1-bee8-4188-aa19-1d5e7311d73d.png)

**Comment by SatishGandham** [comment]
List of API to modify.

**View mode** 
v1/actions/view?applicationId={id}
v1/collections/actions/view?applicationId={id}
v1/themes/applications/${applicationId}/current?mode=${mode}
v1/themes/applications/${applicationId}

**Edit mode**
v1/actions?applicationId={id}
v1/collections/actions?applicationId={id}
same 2 theme API's
api/v1/plugins?workspaceId=${workspaceId}
v1/datasources?workspaceId=${workspaceId}



Don't deprecate the existing API's

**Comment by sumitsum** [comment]
Closing this in favour of consolidated APIs project.

**Comment by sumitsum** [comment]
https://github.com/appsmithorg/appsmith/pull/29251
