### ISSUE TITLE
[Bug]: Scroll bar does not appear when debugger is open on the settings page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Scroll bar does not appear when debugger is open on the settings page

![image](https://github.com/appsmithorg/appsmith/assets/79509062/466e2a97-5cc3-48ba-9b04-a057b0d2fc67)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/ca225cc0-7f18-4bfe-aa71-3237f3bcdcd0)

### Steps To Reproduce

1. Configure >4 async functions on a JS object
2. Navigate to the settings tab and open up the debugger - observe that there is no scroll bar to scroll and view the hidden functions

### Environment

Production

### Version

Cloud

**Comment by arunvjn** [comment]
@ramsaptami This issue seems to have been fixed already. Could you please verify ?

**Comment by AnandiKulkarni** [comment]
@arunvjn this is working fine closing the issue

https://github.com/appsmithorg/appsmith/assets/80756091/6e0e519c-b86a-432a-ac9f-fbba10b53309

**Comment by AnandiKulkarni** [comment]
closing
