### ISSUE TITLE
[Bug]: "Error - SupabaseUrl is required" when trying to use supabase client

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#24674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Supabase library throws a 'supabaseUrl is required' error when I try to call the 'createClient()' method. 
I used the same credentials on my Node Environment and it worked. 

### Steps To Reproduce

1. Install the Supabase client library on Appsmith. 
2. Try to call the `createClient()` method and add the necessary parameters. 

### Environment

Production

### Version

Appsmith Cloud

**Comment by bharath31** [comment]
@narhzih could you share your code snippet? I just tried using the following code snippet and it worked. 
```
export default {
   SUPABASE_URL: "<INSERT YOUR PROJECT URL>",
   SUPABASE_PUBLIC_KEY: "<INSERT YOUR PUBLIC KEY>",
    async getUsers () {
	const supabaseInstance = supabase.createClient(this.SUPABASE_URL, this.SUPABASE_PUBLIC_KEY)
	let users = await supabaseInstance.from('users').select('*')
	return users
    }
}
```
