### ISSUE TITLE
[Task]: Deprecate saas manager app

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#24712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

saas manager app is buggy and has caused problems in live datasources simply by editing it. We should remove db access from this app, so that no more changes are made inadvertently.

**Comment by sumitsum** [comment]
Details are available [here](https://www.notion.so/appsmith/Deprecating-SaaS-Integration-Manager-431f492e5def43178e7704519955f5f1).
