### ISSUE TITLE
[Bug]: Auto-Layout covers Widget when screen size changes 

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#24728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was playing around with the auto-layout and used one of the templates I found on Appsmith to see if it worked better than it does on my own app.

What I have noticed is that the layout seems to resize when the screen is made smaller; however, it reaches a certain size and the screen begins to cover the widgets.
In the three attached pics, the full-width is fine... when it is reduced slightly, the right-hand chart is covered, and then when further reduced, it eventually stacks the charts.

**Full-Width Image** - https://cdn.discordapp.com/attachments/1121007468244389938/1121007468449894400/image.png
**Slightly-Reduced screen size** - https://cdn.discordapp.com/attachments/1121007468244389938/1121007468789645342/image.png
**Small Screen size** - https://cdn.discordapp.com/attachments/1121007468244389938/1121007469095833651/image.png,

### Steps To Reproduce

1. Put three widgets side by side (as specified in the first screenshot)
2. Try to reduce the screen size of your computer. 

### Environment

Production

### Version

Cloud & Self-hosted > 1.9.20

**Comment by Nikhil-Nandagopal** [comment]
Closing as we're building a new canvas with Anvil
