### ISSUE TITLE
[Bug] Home page does not get updated until we refresh 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2472]
Steps to reproduce:
1) Add multiple page 
2) Click on the action icon next to the page 
3) Select "Set Homepage"
and observe

Observation:
The set homepage does not get updated until user refreshes the page

Expectation : 
The homepage should get updated as it is selects

**Comment by riodeuno** [comment]
@prapullac can you confirm if this issue exists?

**Comment by prapullac** [comment]
@riodeuno this is working as expected and hence we can close the issue
