### ISSUE TITLE
[Feature]: Automating multiple instances with a single script

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#24739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi, can I use the REST APIs of appsmith to automate some of my appsmith setups more easily?
My use case:  I have multiple appsmith instances running in multiple countries. I need to perform these things in every instance:

- Update user roles, groups, and permissions
- Update brand color
- Other admin settings.
- I want to have a single script that I can apply to all my instances.

### Why should this be worked on?

It would be easy to manage multiple instances without having duplicated Admin settings

**Comment by infinitetrooper** [comment]
Closing in favour of #24841
