### ISSUE TITLE
[Bug]: Unable to right click on the link present in URL column type of table widget

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#24769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a column is of type URL, it is observed that we cannot right click on the link.

### Steps To Reproduce

1. Dnd table and bind a data to it such that it has a URL column type.
2. Observe that you cannot right click on the links present in this column type

### Environment

Production

### Version

Cloud

**Comment by hilton** [comment]
How was this fixed? I think we have the same issue. The URL type values are not implemented as HTML `a` elements, which means that right-clicking doesn’t offer browser functionality for links: copying the URL and choosing whether to open the link in the same/different tab.

Related: URL column values seem to always open in a new tab, which annoys our users.

**Comment by rahulbarwal** [comment]
@hilton Thanks for clarifying, you are correct, this is not working right now. we will prioritize this.

**Comment by hilton** [comment]
@rahulbarwal Thanks for the update. Depending on how you resolve this, that might also resolve feature request #37174.
