### ISSUE TITLE
[Bug]: The submit button, i.e Sign In should be autoselected if users credentials are prefilled in input fields during sign in

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#24788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user has logged out and tries to login again, the "Sign In" isn't enabled even though the credentials are prefilled in it. It gets enabled when I click on any of "username" or "password" field

### Steps To Reproduce

1. Make sure that login credentials are saved in chrome already.
2. Logout of Appsmith.
3. Close the tab.
4. Visit app.appsmith.com
5. Notice that the sign in button is disabled by default. It gets enabled when a user clicks on any of the input fields.

Expected behavior : The Sign In button should be enabled by default if login credentials are already prefilled.

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/8ddf7580-47d9-4eee-8c0d-bc1c350d179c

seems to have got fixed with some other PR, this is not reproducible anymore

**Comment by rajatagrawal** [comment]
With different steps (refreshing the page), the issue is happening for me on prod:


https://github.com/appsmithorg/appsmith/assets/1189106/2a0faea3-4403-414e-838b-c17a0ad9de2e

@rohan-arthur Can you please confirm if the issues is reproducible on your end ?
