### ISSUE TITLE
[Task]: De-risking servers-side filtering project

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#24782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The task is to triage the following requirement:
- Fix Apply button in filter pane
- Introduce new properties in table widget:
    - `Table1.sqlFilter`
    - `Table1.mongoFilters`
    - etc.
-  New properties in property pane:
    - Enable server side filtering
    - onFiltersChange

**Comment by keyurparalkar** [comment]
Doc for Server side filtering Project: https://www.notion.so/appsmith/Server-Side-Filtering-For-Table-Widget-e73f581cf8a94f75856b248cdea9880e?pvs=4

@laveena-en @chandannkumar can you define test cases for this project? This will help us to find blindspots if any.

**Comment by chandannkumar** [comment]
Doc for the Test cases and current issues on Server side filtering
https://docs.google.com/spreadsheets/d/1TgKPH5XPzIuaHAPooYr5o5jrhpjxFhBTq_Q6wv5rnVk/edit#gid=0
