### ISSUE TITLE
[Bug]: Sign posting modal is seen for user completed with welcome tour

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#24792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a user in work space 1 with an app starts signposting flow and leave it in mid way (assume completes 2 steps ) then completes welcome tour for another app in separate workspace and comes back to previous app and finds sign posting modal appears and  on refresh the page it is ending signposting for that app.

Expected result : Sign posting modal should not be shown if user completes welcome tour.

### Steps To Reproduce

**Step to reproduce :** 

1. Create a workspace  1 > Add an app 1 >  Begin the sign posting flow > complete few steps (lets say  step 1 & 2 )
2. Now create a new workspace  2 > Add an app  1 > Initiate the welcome tour > complete the welcome tour.
4. In workspace 1 > Select existing old app (from step 1)  > click help > observe sign posting modal shows up with step 1 and 2 completed and on refresh the page it is ending signposting for that app.
5. Add new app in any workspace > and observe sign posting modal will not shown up because we have already completed welcome tour.

### Environment

Release

### Issue video log

https://www.loom.com/share/1ad15cb8926841f0a33dd664b41207bb?sid=bd035ae1-3756-4603-b5c0-a928d4e4c632

### Version

Appsmith v1.9.24-SNAPSHOT

**Comment by kavitasmoolya** [comment]
@akash-codemonk Please add your inputs if requires.

**Comment by rohan-arthur** [comment]
signposting is deprecated now, closing this issue as it is no longer valid
