### ISSUE TITLE
[Bug]: start-https.sh not working

### ISSUE THREAD

**Issue by ayush03dev** [appsmithorg/appsmith#24806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to run the client locally. Everything was working fine except the command `./start-https.sh`. I realized then when I perform ./start-https.sh command, it starts the nginx container for a few seconds and then it stops immediately. I looked through the logs of the container and it gave me this error line:

`2023-06-24 15:12:44 2023/06/24 09:42:44 [emerg] 1#1: invalid log level "Source" in /etc/nginx/nginx.conf:4
2023-06-24 15:12:44 nginx: [emerg] invalid log level "Source" in /etc/nginx/nginx.conf:4`

Because this container won't start, I was not able to access the client webpage since the nginx container acts as a proxy.

### Fix:

The reason for the error is that my project's parent folder has a spacing in it. For example this is my PWD: `home/ayush/Open Source Projects/appsmith`. As you can see the first word after the space is `Source` hence it was logged in the console (quoted word in the above log). 

After I realized this, I then re-created the project with this directory: `home/ayush/projects/appsmith` and it worked like how it was supposed to.

### Steps To Reproduce

1. Make a folder with words separated by space. Example: `Open Source Projects`
2. Clone the project inside this folder
3. Follow the steps as shown in the [**ClientSetup.md**](https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md) file.
4. Execute ./start-https.sh (With or without argument, it won't work in any case)
5. Although console will log that it started the nginx on docker container, the docker container stops immediately. 

### Environment

Production

### Version

1.9.23

**Comment by ayush03dev** [comment]
Can I update [ClientSetup.md](https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md) by adding instruction to not have spacing in the parent folder and open a PR?

**Comment by Nikhil-Nandagopal** [comment]
This is no longer valid
