### ISSUE TITLE
[Feature]: Show schema on query page

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#24812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Notion: https://www.notion.so/appsmith/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f

### ### Designs

Loading state:

https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=533-56867&mode=design&t=01g0X0pmKoSFDGIL-0

Error state:

https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=533-62081&mode=design&t=01g0X0pmKoSFDGIL-0

Working state:

https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=533-64974&mode=design&t=01g0X0pmKoSFDGIL-0

Template query:

https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=533-62939&mode=design&t=01g0X0pmKoSFDGIL-0

Schema search:

https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=533-64439&mode=design&t=01g0X0pmKoSFDGIL-0

### User flow

****************************Loading state([[design](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21)](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21))**

When a user creates a query, the the schema of the underlying datasource by be available(success case) or not(failure case).

In either case, the user should first see a [[loading state](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21)](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21).

************************Failure case([[design](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21)](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21))**

If there is some error in getting the datasource schema, the user should see an error. Also, considering that in most error cases the datasource configuration is invalid, the user should also see a cta to edit the datasource, upon clicking this, they should be taken to the datasource edit form.

****************Success case([[design](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21)](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21))**

When the schema is available, the user should see it as shown in the design.

**Template query([[design](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21)](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21))**

The user can also make use of a template query as shown in the design, doing this should work exactly as `smart templates` work today. i.e., a new query should be created with the generated template query.

****************************Search([[design](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21)](https://www.notion.so/Show-schema-on-query-page-720da69ac71845dab07694c880549a6f?pvs=21))**

The user should also be able to search in the schema as shown in the design.

### Data

1. number of times schema fetch failed/passed
2. number of times the user chose a template query
3. A/B test: roughly 50% of users should see this new flow, the remaining should see the old flow
    1. I should be able to see on mixpanel the users who saw the new and old flows

### Why should this be worked on?

for activation project

**Comment by Irongade** [comment]
Increasing the complexity because a few refactors need to be made.

cc: @rohan-arthur
