### ISSUE TITLE
[Bug]: Map widget zoom level 

### ISSUE THREAD

**Issue by jrsittirat** [appsmithorg/appsmith#24819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Map widget : error double '%' when entry data zoom level.
![image](https://github.com/appsmithorg/appsmith/assets/136780529/9385a814-5fc2-417d-ab2d-7d13c49cfb70)

### Steps To Reproduce

1. Key data in text zoom level
2. Map not display and  double '%' and can't delete or change

### Environment

Production

### Version

1.9.23

**Comment by somangshu** [comment]
Greetings @jrsittirat, thanks a ton for raising this issue. This is definitely some thing we need to solve and is also probably a regression.

**Comment by iSatVeerSingh** [comment]
I would like to work on this.

**Comment by somangshu** [comment]
@iSatVeerSingh sorry we are already working on this issue
