### ISSUE TITLE
[Feature]: New binding pane

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#24810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Design: https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=43-19957&mode=design&t=2qZMFmvPTKakZTEu-0

Notion: https://www.notion.so/appsmith/Activation-60c64894f42d4cdcb92220c1dbc73802?p=7c9a22fa873c4ab9a1a3df7921150398&pm=s

1. The suggested widgets should be shown along with their icons
    1. When I have a successful query, I should see the `Bindings` section as shown in the design (ignore the tooltip/tutorial for this story)
2. Connect to existing widget:
    1. if there are no existing widgets on the canvas, I should see message ‘No existing widgets’ like in the design above
    2. if there are connecting widgets:
        1. we need design for this
        2. [[Open question](https://theappsmith.slack.com/archives/C056PSE5X0E/p1687522136381749?thread_ts=1687520736.508259&cid=C056PSE5X0E)](https://theappsmith.slack.com/archives/C056PSE5X0E/p1687522136381749?thread_ts=1687520736.508259&cid=C056PSE5X0E), please create a new issue if the solution isn’t trivial. For now, leave the existing `Select widget` button as it is. On clicking this, the existing flow should continue, i.e., I should be taken to the canvas and I can snipe to an existing widget.
        
        ![Screenshot 2023-06-23 at 16.02.42.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b76f9827-37cb-416b-816b-6df710c1555f/Screenshot_2023-06-23_at_16.02.42.png)
        
3. Connect to new widget:
    1. Upon clicking on one of the widgets, the existing snipe flow should kick in, i.e., I should be taken to the canvas and a new widget should be created with the proper data binding from the query response.
4. I should not see the `Relationships` section anymore

### Data

1. Snipe mode used by user
2. Which widget is used in snipe mode
3. A/B test: roughly 50% of users should see this new flow, the remaining should see the old flow
    1. I should be able to see on mixpanel the users who saw the new and old flows

### Why should this be worked on?

for activation project

**Comment by sneha122** [comment]
PR has been merged into feature branch `fix/activation-phase-1`
