### ISSUE TITLE
[Feature] Show 'last saved' time or versions on hovering over 'saved' icon.

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2483]
## Summary

We should show the last saved time when someone hovers over the green check mark.

## Motivation

Users keep trying to click or hover on it because it's a dynamic element. I've seen this multiple times on Smartlook.

**Comment by Debsourabh** [comment]
Here is the design for the same.

https://www.figma.com/file/DI69SVZlVvKXckU5mATFbN/?node-id=452%3A2

We show two options. 

- Either it was saved moments(Few Seconds) ago.
- Either it was saved 2 (specific) number minutes ago.

**Comment by aswathkk** [comment]
Hi,
I would like to work on this issue.

Should we show the last saved time for the initial render?

**Comment by Nikhil-Nandagopal** [comment]
@aswathkk this requires some backend work to show the last time the page was saved in the API

**Comment by aswathkk** [comment]
@Nikhil-Nandagopal We need backend work only if we plan to show the last saved time in the initial render.
Otherwise, we can keep track of the last saved time in a variable on the frontend itself.

**Comment by Nikhil-Nandagopal** [comment]
@aswathkk it needs to be in the backend because 2 developers working on the same app might make changes

**Comment by aswathkk** [comment]
@Nikhil-Nandagopal Correct. I didn't think about that case.

**Comment by gvrayden** [comment]
Would like to pickup the backend part of this, does it need a separate BE issue ?
Also where should I start looking?

**Comment by trishaanand** [comment]
@gvrayden : 
On the backend side, we should introduce a transient field called lastUpdatedTime which reads from already present field "updatedAt" and sets it. This field should be added inside `NewPage.unpublishedPage`. This field should be set only when the pages are fetched using the API endpoint `api/v1/pages/{pageId}`. 
When the page is saved using the API endpoint `api/v1/{layoutId}/pages/{pageId}`, we don't need to set this. Let the client keep a track of when the page was last saved by the client and display that to the user. 
Only when the page is fetched from the server using GET call does the server return the `lastUpdatedTime`. In other scenarios, the client displays the last time the page was saved by the client itself.

Please let me know if you have any other doubts.

**Comment by abhinandansharma** [comment]
Hey guys.
Is the backend work done?
I was thinking about adding this on the front-end.

**Comment by trishaanand** [comment]
@gvrayden : Would you be picking this up? If you aren't, @abhinandansharma would like to take this up.

**Comment by gvrayden** [comment]
Go ahead, I won't be able to pick this up anytime soon.

**Comment by abhinandansharma** [comment]
Alright, Let me try to fix it.
Just one more thing, Are we storing last updated time in the back-end now? I guess it's required for the initial get request, after that everything can be handled through client side.

**Comment by nayan-appsmith** [comment]
@abhinandansharma Yes, the last updated time is stored in the backend. The `updatedAt` field in the `newPage` document is updated whenever there is a change in an unpublished page.

**Comment by abhinandansharma** [comment]
Got it @nayan-appsmith
Thanks 😊
