### ISSUE TITLE
[Feature] Show the app icon in the nav bar

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2484]
## Summary
1. App icon should show up in the nav bar so that the user knows which icon was chosen for their app. Today the app icon is chosen randomly so the user doesn't even know that an icon was chosen in the first place.
2. User should be able to change the app icon in the nav bar

**Comment by mohanarpit** [comment]
On a slightly related note, is it possible for us to change the favicon colour for edit & deploy modes of the Appsmith application? It will make it easier for a user with multiple tabs open to see which ones are in Edit mode and which ones in view mode.

**Comment by Nikhil-Nandagopal** [comment]
@Debsourabh are we doing this?

**Comment by Debsourabh** [comment]
I haven't designed it yet. I will pick it up post Search

**Comment by Nikhil-Nandagopal** [comment]
Closing since I think we've decided not to use the app icon in the nav bar anymore
