### ISSUE TITLE
[Bug]: Auto-Layout Display Inconsistency When User Is Logged In vs. Not Logged In

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#24848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When auto-layout is enabled, there is a discrepancy between how the app is displayed when a user is signed in and when no user is signed in. The difference is more obvious when using a mobile view.
[Discord thread
](https://discord.com/channels/725602949748752515/1122722062587404420)
Anonymous user:

![image](https://github.com/appsmithorg/appsmith/assets/101268423/829ec96c-6eff-4a02-9350-289c5561c32e)

Logged-in user:

![image](https://github.com/appsmithorg/appsmith/assets/101268423/55cda50e-dede-4cad-bb91-22a31569150a)

### Steps To Reproduce

Open the attached sample app in a browser where a user is logged in and also open this app on an incognito browser (same screen size).

[AutoLayout_Discrepancy.zip](https://github.com/appsmithorg/appsmith/files/11871015/AutoLayout_Discrepancy.zip)

### Public Sample App

https://app.appsmith.com/app/autolayout-discrepancy/page1-6499ade85148951fb1edb207

### Environment

Production

### Version

Cloud/Self-Hosted v1.9.24

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_kc7po)

**Comment by GustantoC** [comment]
https://discord.com/channels/725602949748752515/1122722062587404420/1123061911215415326
