### ISSUE TITLE
[Bug]: S3 datasource - Save button disabled on page refresh,

### ISSUE THREAD

**Issue by sharanya-appsmith** [appsmithorg/appsmith#24844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The S3 cred fields are automatically filled with data, Was unable to edit the same. So I had to refresh and the cred fields were editable but save button is disabled.

### Steps To Reproduce

Prerequisite 
1. Datasource 
2. Select S3
4. Refresh the page 
5. Save button is disabled even on entering the cred reqd.

### Environment

Release

### Version

Appsmith Business v1.9.24-SNAPSHOT

**Comment by sumitsum** [comment]
Closing it as this issue is not reproducible on prod: 

https://github.com/appsmithorg/appsmith/assets/1757421/7611ccec-2bd6-4d37-a8d5-a4f24f28d86d
