### ISSUE TITLE
[Bug]: Unable to access Users page / Audit logs page on the Promotion DP.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#24853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on Admin Settings and try to access Users / Audit Logs - error toasts pop up. 

### Steps To Reproduce

1. Login as instance admin and click on Users / Audit logs [https://ee-1703.dp.appsmith.com/]
2. Note error toasts pop up

Tried on incognito as well. Same issue exists. 

<img width="1429" alt="Screenshot 2023-06-26 at 8 17 00 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/14feb9c8-43b7-4e24-90fe-61fc977ca564">
<img width="1381" alt="Screenshot 2023-06-26 at 8 16 14 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/c9490c16-d854-46e3-b63d-63319e8ab4f5">

### Environment

Release

### Version

Cloud

**Comment by trishaanand** [comment]
This was a data problem in the release database dump. I have fixed the data. Closing the same since its not a code issue.

**Comment by btsgh** [comment]
Verified on the DP now and the issue is not seen.
