### ISSUE TITLE
[Bug] Cursor always jumps to the end in sign-up form

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2485]
## Description

[What happened]

### Steps to reproduce the behaviour:
1. Type an email and password
2. Click in the middle of the email id and start editing the email
3. See the cursor just jump to the end of the field
4. Also happens for the password field

Loom video:
https://www.loom.com/share/29df0ef6c1da47eb8bb1c0e4a25996c5

**Comment by mohanarpit** [comment]
@rishabhsaxena Reopening this issue because this is happening in the release environment after the UI changes to the Login page.
