### ISSUE TITLE
[Task]: Remove the stale index lock file which is not deleted due to the pod restart 

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#24854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Sometimes when the pods restart on kubernetes during a git operation, a stale lock file is created. As of now, user need to manually remove this file to continue with git operations. Ideally We should remove this file automatically

**Comment by sharat87** [comment]
Can we instead solve this at the application-level? Like, before performing a git operation, check for an existing lock file, and if it exists, delete it and then perform the operation? That way, if a lock file is leftover for any other reason, we're still resilient to all such cases.

**Comment by infinitetrooper** [comment]
Event Name git_stale_lock_file_deleted

Properties
- default properties(segment source name, version, instance_id)
- repo_url
- lock_file_age (how old the lock file is - in seconds)
