### ISSUE TITLE
[Bug] If a widget's property pane is open, then clicking on another widget's border opens up that property pane

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2486]
## Description

1. Open widget 1's property pane.
2. Click on the border of widget 2
3. The property pane of widget 2 opens

Video: https://www.loom.com/share/49691659aabe4e8398f319ab1b015bab

**Comment by riodeuno** [comment]
Closing this as discussed, with the new changes in the property pane, this issue is moot.

**Comment by prapullac** [comment]
As said in above comment closing the issue
