### ISSUE TITLE
[Task]: Update widget search algorithm

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#24868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Widget search should also search for category names, along with widget names and their alternative search terms as we do today.

**Comment by iSatVeerSingh** [comment]
@dhruvikn Do you need any help?

**Comment by dhruvikn** [comment]
Thanks @iSatVeerSingh, but this is already done, just not merged.
