### ISSUE TITLE
[Task]: Update all widget configs with respective categories

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith#24867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Subtask for https://github.com/appsmithorg/appsmith/issues/24865
- We will need to [update all widget configs](https://www.notion.so/appsmith/Widget-Discoverability-755cf059a1904950888304b90b74106f?pvs=4#cbc416b7525041a892d70b0a0a3f75fd) to contain the categories.

**Comment by iSatVeerSingh** [comment]
@dhruvikn Need any help?

**Comment by dhruvikn** [comment]
Thanks @iSatVeerSingh, but this is already done, just not merged yet.
