### ISSUE TITLE
[Bug]: Getting internal server error intermittently on git connected app 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#24861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1436" alt="Screenshot 2023-06-27 at 1 47 03 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/6f3854c7-4319-4672-90f7-ea42b6569f97">

### Steps To Reproduce

1. Go to promotion [DP](https://ee-1703.dp.appsmith.com/applications), open any git connected app e.g. https://ee-1703.dp.appsmith.com/app/gitimporttests/page1-6257bd287d19044d68b1c659/edit?branch=master
2. Observe internal server error is thrown
Note: This is not reproducible always

### Environment

Deploy Preview

### Version

https://ee-1703.dp.appsmith.com/applications

**Comment by infinitetrooper** [comment]
Stale
