### ISSUE TITLE
[Task]: Remove FF4J support

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#24872]

**Comment by NilanshBansal** [comment]
@hetunandu @ginilpg can we move this as part of phase 1.1 or phase 2, as discussed [here](https://www.notion.so/appsmith/Phase-1-9b3be11313844c3f89ce1adae68585fa?pvs=4#ef3a8250b2bd4dc296ccbb616cada875)

**Comment by hetunandu** [comment]
Done

> @hetunandu @ginilpg can we move this as part of phase 1.1 or phase 2, as discussed [here](https://www.notion.so/appsmith/Phase-1-9b3be11313844c3f89ce1adae68585fa?pvs=4#ef3a8250b2bd4dc296ccbb616cada875)
