### ISSUE TITLE
[Bug]: Browser back button does not work

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#24892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While pressing the browser back, the url is changing but the app does not respond to the changes

### Steps To Reproduce

1. Click on multiple entities on the entity explorer
2. Press the back button
3. Notice the app does not go back to the older entity

### Environment

Production

### Issue video log

https://github.com/appsmithorg/appsmith/assets/12022471/79219b8e-1116-405e-a1e3-a827c903e6a5

### Version

v1.9.15

**Comment by Aishwarya-U-R** [comment]
Navigating from View mode to Application via Browser back is also having same issue:
https://github.com/appsmithorg/appsmith/assets/91450662/a5c947ec-d987-4933-be41-0d6d74e3a172

**Comment by hetunandu** [comment]
Consistent recreate with the following steps:
- Hard refresh on applications page
- Go to an app (edit / view)
- Go to different pages / widgets / apis 
- Press browser back and forward
- Notice the url changes but app does not update

Initial findings:
- Only happens when we went from applications page to app pages. Hard refresh on app and pressing back works as expected
- Top level router is not getting the new url updates
- Adding a native history listener function locally solved the issue automagically. Commenting it out caused the issue again

**Comment by hetunandu** [comment]
> @hetunandu The history.listen has been present in the application for months now. Are you sure this is causing the problem?

We have recently noticed this issue and could be introduced earlier. I am sure because uncommenting that line makes the browser back button work correctly

**Comment by dipyamanbiswas07** [comment]
> > @hetunandu The history.listen has been present in the application for months now. Are you sure this is causing the problem?
> 
> We have recently noticed this issue and could be introduced earlier. I am sure because uncommenting that line makes the browser back button work correctly

Alright. We'll take a look.
