### ISSUE TITLE
[Bug]: Can’t connect RESTful API to Appsmith with Bearer Link (PE-RST-5000)

### ISSUE THREAD

**Issue by degude** [appsmithorg/appsmith#24910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I connected our Restful API Services via Oauth 2.0 and Bearer tokens to Appsmith. Since version 1.21.0 I can’t create data sources from these APIs. Up to version 1.20.4 it was working.

We have a Microsoft Access Token URL that creates a Bearer token for Oauth 2.0. The Access URL ensures that the bearer tokens do not expire. The Access Token URL then seems to provide the API call on the microservice with the header argument “Authorization” and as its key the bearer token.

For the authorization we use a self-signed certificate.

Up to version 1.20.4 this method is working as well and from 1.21.0 and upwards not, so its very likely, that this release caused the problem. The self-signed certificate, as well as the bearer tokens are working.

![image](https://github.com/appsmithorg/appsmith/assets/5718806/58071fc1-bdf2-4768-a188-4ea1f6471dc4)

I found this similar issue, but I am not sure whether it relates one to one to this problem.
https://github.com/appsmithorg/appsmith/issues/24221

### Steps To Reproduce

Use Version >= 1.9.21
1.	Create a new API connection
2.	Select Grant Type Client Credentials
3.	Select Access Token to Request Header
4.	Enter Access Token URL and Credentials
5.	Select Client Authentication = Send as Basic Auth Header
6.	Add a self-signed certificate

![image](https://github.com/appsmithorg/appsmith/assets/5718806/a4636ed1-8e11-4f55-bf82-ce48f3a24220)

Alternative:
1.	Create a new API connection
2.	Set the Header Argument to “Authorization”: {{Bearer Token}}
3.	Add self-signed certificate

### Environment

Production

### Version

Self Hosted

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_tzerw)

**Comment by sharat87** [comment]
Hey @degude, can you confirm that the endpoint you are using does indeed use a self-signed certificate? You can do this by running a curl on that request, and you should see this in the output:

```
curl: (60) SSL certificate problem: self signed certificate
```

I tried with an endpoint that's using a self-signed certificate, and I see the same error in both `v1.9.20.4` and `v1.9.25`. I'm attaching the video here. Can you confirm if you get similar/same output from a curl command to your endpoint please?

https://github.com/appsmithorg/appsmith/assets/120119/db27bdc2-9d8c-4181-8184-cf1a5ba51046
