### ISSUE TITLE
[Feature]: Implement math.js on input fields

### ISSUE THREAD

**Issue by rodrigoscdc** [appsmithorg/appsmith#24912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I was searching for this and couldn't see anything similar. So implement this feature to input fields could be very nice to create some applications which we need apply some math operations to values.
https://mathjs.org/

### Why should this be worked on?

When we create some application which have some input fields which handle with numbers, sometimes we need to perform some conversion between units, so if numeric input fields could make this result after press enter or tab should solve the necessity.
In the demo of mathjs you could see some exemples of the feature.
https://mathjs.org/

**Comment by somangshu** [comment]
Did not get your requirement @rodrigoscdc 
I believe the example you are sharing can easily be achieved with the help of JS function which execute on button clicks and takes value from the input you want. I am finding it hard to understand why does this need to be a out of the box implementation on input widget. 

cc @dilippitchika @sbalaji1192

**Comment by sbalaji1192** [comment]
@rodrigoscdc You can use the custom libraries feature to install the math js on your application to achieve this https://docs.appsmith.com/core-concepts/writing-code/ext-libraries
