### ISSUE TITLE
[Bug] Clicking in wrong places / white space opens up query editor.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2492]
## Description
1. Query editor needs to open up when user clicks on Create/Select/Update/Delete options. However, it opens up by clicking elsewhere as well, which seems unintended. Please check out the image attached. Clicking anywhere inside the red box opens up query editor.

![Screenshot 2021-01-08 at 4 37 33 PM](https://user-images.githubusercontent.com/1757421/104008788-efe87080-51cf-11eb-8f83-d92abc3ab1fc.png)

### Steps to reproduce the behaviour:
1. Create a datasource.
2. Create a new query for datasource.
3. Click in the area show by red box in the attached image.

### Important Details
 - Version: Cloud
 - OS: Linux
 - Browser: Chrome

**Comment by areyabhishek** [comment]
@sumitsum This design is to allow people to create a blank query by clicking in the white space. The other links are to allow users to use a template. Perhaps we should include 'Blank' as one of the options in the list below? It might make it more obvious.

**Comment by sumitsum** [comment]
@areyabhishek yes it would be good to create another option, right now users may perceive it as a programming error.

**Comment by Nikhil-Nandagopal** [comment]
While this behavior is intended, I do remember a few people being confused by "how do I create a blank query?"

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal Just adding one more point here to think over - all the query options - query / select / update / delete, they don't impose any conditions i.e. they are as good as a blank query - so is there any use providing different query options ?

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum the use of the options is not for conditions but to give users a quick starting point for the syntax. This is especially useful for mongo where the query language is the non standard bson format.

**Comment by hetunandu** [comment]
Should be fixed with #3628
