### ISSUE TITLE
[Bug]: Cannot connect with HTTPS

### ISSUE THREAD

**Issue by AdrKacz** [appsmithorg/appsmith#24929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created an Appsmith instance with EC2 AMI, I can connect to it via HTTP, but impossible via HTTPS (the secure group is correctly configured)

I tried several step on top of the tutorial, all unsuccessful:
1. Connect the domain to Route53 with an Elastic IP
2. Don't use the AMI, instead turn up a Lightsail instance a boot Appsmith with `docker-compose`, same I can only connect with `HTTP` even with correct network (open to `443`)

### Steps To Reproduce

Follow the tutorial for AWS AMI.

### Public Sample App

https://54.216.211.140

### Environment

Production

### Version

Self-Hosted AMI

**Comment by sharat87** [comment]
@AdrKacz, thank you for reaching out. Can you confirm if you've followed [this guide in docs](https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-domain) for getting HTTPS?

If yes, can you elaborate on what failure you're seeing please? What's the error when you try to access on HTTPS? Can you share a screenshot? If you have the custom domain configured on Appsmith like in the docs linked above, and yet HTTPS isn't working, can you share the full container logs as well please? Feel free to send them to support@appsmith.com and mention this issue number, if you don't want to share them publicly here.

Thanks!

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we haven't heard back from you. Let us know if you're still facing an issue
