### ISSUE TITLE
[Bug]: Cypress Test coverage for the git flows

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#24926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Last couple of Sprints we have noticed couple of bugs in prod. This happened mostly because of the missing coverage in tests for the git flows. 
Top of mind i can thin of Git Discard with Navigation settings, Check out remote branch. 

Creating this issue to revisit the cypress test cases, coverage and all the scenarios we are testing. 

### Environment

Production

### Version

Latest

**Comment by infinitetrooper** [comment]
Make ticket more actionable
