### ISSUE TITLE
[Bug]: Not able to discard app settings changes for the first time in git connected app

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#24920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Discarding navigation changes is not working when we discard it for the first time, once navigation changes are committed to remote and then when we try to add navigation settings and discard changes, it works fine.

### Steps To Reproduce

1. Create new app, connect it to git
2. Modify navigation settings changes inside app settings
3. Discard changes
4. Observe it doesn't get discarded 

### Environment

Release

### Version

Release

**Comment by Parthvi12** [comment]
Along with navigation changes, canvas size changes are also not getting discarded for the first time. @dhruvikn let me know if you want me to create a separate ticket for it.

**Comment by dhruvikn** [comment]
No worries, @Parthvi12, I'll take a look along with this ticket only.
