### ISSUE TITLE
[Bug]: Error while importing external libraries

### ISSUE THREAD

**Issue by AruljothySundaramoorthy** [appsmithorg/appsmith#24923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I tried to install the crypto-js library using CDN , it was throwing error which was attached in the screenshot.

### Steps To Reproduce

-

### Public Sample App

https://imgur.com/a/b7SdUd9

### Environment

Production

### Version

docker version

**Comment by bharath31** [comment]
@AruljothySundaramoorthy please try installing using the following URL: `https://cdn.jsdelivr.net/npm/crypto-js@4.1.1/index.min.js`

**Comment by AruljothySundaramoorthy** [comment]
@bharath31 It's working, but if I want to install some other library(https://cdn.jsdelivr.net/npm/md5.js@1.3.5/index.min.js) , it was throwing an error.

**Comment by bharath31** [comment]
@AruljothySundaramoorthy gotcha! I'm guessing the `md5` library does not support a minified UMD build. You can learn more about checking library compatibility [here](https://docs.appsmith.com/core-concepts/writing-code/ext-libraries#library-compatibility).
