### ISSUE TITLE
[Bug]: Last deployed status is not updated during the git pull on the UI

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#24945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After doing the git pull, modal is showing last deployed was X days ago. This creates a confusion with the user whether the  deployment didn’t happen or not. 

### Steps To Reproduce

Go to any git connect app and do not commit but pull the changes directly and then observer this. 

### Environment

Production

### Version

Cloud

**Comment by infinitetrooper** [comment]
Replication
1. Have two instances of the same app, A & B
2. In A, Make changes and push them to the remote repo
3. In B, make any change, open the commit modal, and click Discard & Pull
4. The commit made in A will get deployed but the message isn't updating.
5. Please check this with normal pull flow as well.


![image.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/87c0fae4-a683-4d04-b748-a90942a90ec0)
