### ISSUE TITLE
[Bug]: Order of properties is changing in the JSONPathKeys on canvas file

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#24944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While committing the order of values inside the jsonPathkeys is changing in git connected app and this is coming as a modified change and hence the issue. 

### Steps To Reproduce

https://github.com/appsmithorg/license-manager-app/pull/8/files
https://theappsmith.slack.com/archives/C04HERDNZPA/p1687866844653819

### Environment

Production

### Version

Cloud

**Comment by ame-appsmith** [comment]
[Another BE user](https://app.frontapp.com/open/cnv_19me5g98?key=ehRvswdNtt--GvmietuaZUvayfb4Pf9F) reported this issue.

**Comment by RakshaKShetty** [comment]
This has been removed now there wont be issue of change in order
<img width="1083" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/161eed55-2819-4e74-aa89-0db34a152bdd">
