### ISSUE TITLE
[Feature]: Option to hide `Type` errors originating due to `undefined` data properties

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#24977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The user wants an option to hide the errors originating from `undefined` data properties. Usually, these can be safely ignored  as they'll go away when the data is available later in the app flow.

### Why should this be worked on?

This pollutes the error pane and can lead to a user missing other important errors like query failures etc.

**Comment by bharath31** [comment]
@pranavkanade  They can use nullish coalescing to prevent these errors from throwing up. eg: `{{appsmith.store.name ?? "Anonymous"}}`
