### ISSUE TITLE
[Enhancement]: Show entity names at the top and then list supported functions on autocomplete

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#24975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This was a feature before, can't remember why or when this got changed but we need to list entity names at the top to let users quickly use keys to navigate to the entity before jumping to the supportive actions.

For exmaple, if there are 4 select widgets on canvas, suggestions first shows all possible actions on Select1 and then starts to list Select2 and so on
 
It needs to first start by listing down all matching entities named select and then filter down to the next level of actions on the autocomplete.

![image](https://github.com/appsmithorg/appsmith/assets/79509062/8b99e86d-45ec-411b-9f46-d5e71a34c782)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/453c7c30-b61e-4719-9e59-4b60adb3e529)

### Why should this be worked on?

Improves ease of usage and experience of autocomplete

**Comment by bharath31** [comment]
Related to improving relevance of autocomplete results
