### ISSUE TITLE
[Bug]: Debugger logs tab should remain selected by clicking on "Run" button

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#24989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user clicks on "Run" button, the "Response" tab in debugger gets selected. Expected behavior would be that the current selected tab in debugger should remain selected.

### Steps To Reproduce

1. Go to JS Object Editor.
2. Write a console log statement in a function
3. Select Logs tab in debugger.
4. Click on Run.
5. Observed Behavior : Response tab in debugger gets selected.
6. Expected behavior : Logs tab should remain selected

### Environment

Production

### Issue video log

https://www.loom.com/share/efb90009e52d4470bd6e0eea4dce5353

### Version

Cloud

**Comment by ramsaptami** [comment]
related to #24440

**Comment by ramsaptami** [comment]
Duplicate of #23108
