### ISSUE TITLE
[Bug]: Discard and pull doesn't discard changes

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#24987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If there are local changes and a user clicks on discard and pull, the changes don't get discarded and still show up after the page reloads triggered by discard and pull.

### Steps To Reproduce

Please check loom video for repro steps.

1. Open an app which is already integrated with git. Make sure there are no uncommitted changes.
2. Make some changes in the app.
3. Click on discard and pull.
4. The page refreshes.
5. Go to merge tab.
6. Observed Behavior : The merge tab shows that there are uncommitted changes.
7. Expected Behavior : Uncommitted changes shouldn't be there as the user has just done a discard and pull.

### Environment

Production

### Issue video log

https://www.loom.com/share/77c972bdce61479dbd25358b92386ea5

### Version

Cloud

**Comment by iSatVeerSingh** [comment]
Can not reproduce? Please explain how to reproduce.

**Comment by rajatagrawal** [comment]
@iSatVeerSingh Updated the repro steps in the issue description

**Comment by iSatVeerSingh** [comment]
@rajatagrawal Not reproducible.

**Comment by infinitetrooper** [comment]
@rajatagrawal  - This is due to DSL migrations. When the page loads on the client after discard, the client migrates the DSL to the latest version and the change shows up again. It's a known issue being dealt with in this epic https://github.com/appsmithorg/appsmith/issues/24793.
