### ISSUE TITLE
[Bug]: Unable to import app from git, getting file system error

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#24998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For one particular repo, when I try to import from git, it gives file system error, adding screenshot:
<img width="1439" alt="Screenshot 2023-07-03 at 10 02 13 AM" src="https://github.com/appsmithorg/appsmith/assets/80334441/5777e7f4-0a79-4ee4-9ada-f79de97d5326">

### Steps To Reproduce

1. Import this app from git repo: git@github.com:Parthvi12/template2.git
2. Observe it fails while importing

### Environment

Production

### Version

Cloud

**Comment by vernonstinebaker** [comment]
I'm experiencing the same problem.

**Comment by AnaghHegde** [comment]
@Parthvi12 This is an older version of File system. But that should not be the issue. After going through the repo, in the application.json file, please remove the `createdAt` field and try again. This is causing the issue.

**Comment by vernonstinebaker** [comment]
@AnaghHegde I tried the solution you suggested to Parthvi12 and it worked for me. By removing createdAt I'm now able to load the repository. Thanks!
