### ISSUE TITLE
[Bug]: GSheet | Learn more does not give any results

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#25004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
**From Release - CE**
![Screenshot 2023-07-03 at 12 24 08 PM](https://github.com/appsmithorg/appsmith/assets/91450662/c39417cb-ef93-40af-b61d-d753eeb9de22)

**From Production:**

<img width="778" alt="Screenshot 2023-07-03 at 12 38 41 PM" src="https://github.com/appsmithorg/appsmith/assets/91450662/aa5ff9ec-d8a3-4b06-89ee-38186dc82998">

### Steps To Reproduce

1. Open a new GSheet DS
2. Click on Learn more
3. Observe No results are returned
4. **Expected - Users should get some appropriate helping documents when Learn more is clicked from anywhere within the app**

### Environment

Release

### Version

Prod/Release v1.9.26

**Comment by shwetha-ramesh** [comment]
Also, searching for any documentation from the omnibar does not give any results. And on click on Documentation icon does nothing
https://www.loom.com/share/3c9ebe8eb76a465898a93d337ee3b3f9

**Comment by sneha122** [comment]
@shwetha-ramesh This was removed purposely. More details can be found here: https://theappsmith.slack.com/archives/C040LHZN03V/p1688369927255419?thread_ts=1688367423.304759&cid=C040LHZN03V

CC: @hetunandu
