### ISSUE TITLE
[Bug]: After upgrading to latest Release version on every browser refresh we are seeing internal server error message

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#25012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After upgrading to latest Release version on every browser refresh we are seeing internal server error message
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/0324550c-cf9e-4e95-8203-626d6ccd2fa7">

### Steps To Reproduce

1. Go to https://release-ee-https.appsmith.com/user/login
2. refresh thye browser window 
3. or try to login with any login methods
4. the internal server error toast message is displayed

### Environment

Release

### Version

v1.9.26

**Comment by NilanshBansal** [comment]
@pratapaprasanna the cloud services url should be updated here for the release env. 
Currently, the env is pointing to https://cs.appsmith.com which should be updated to https://release-cs.appsmith.com.
CC: @RakshaKShetty

**Comment by jsartisan** [comment]
@RakshaKShetty This does not belong to branding. Removing myself from assignees.

**Comment by RakshaKShetty** [comment]
This issue is fixed
