### ISSUE TITLE
[Feature] Delete an organisation

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2502]
## Summary
Ability to delete an organisation

## Motivation
To avoid having old dangling orgs in my org list

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu duplicate of #924

**Comment by tlawrence-TAG** [comment]
When is this functionality being implemented?

**Comment by Nikhil-Nandagopal** [comment]
@tlawrence-TAG this isn't prioritised yet. Any reason this is urgent for you? If you're on cloud, I can help delete your org. If you're self hosted, you can add a dummy admin and leave your org

**Comment by tlawrence-TAG** [comment]
Not a priority, just an inconvenience.

**Comment by ebecaf** [comment]
> @tlawrence-TAG this isn't prioritised yet. Any reason this is urgent for you? If you're on cloud, I can help delete your org. If you're self hosted, you can add a dummy admin and leave your org

I'm on cloud and want to delete my org, and also want the option to delete my account please.
Org ID is 617d840255c1eb6167b9944b

**Comment by Nikhil-Nandagopal** [comment]
@ebecaf could you please write to support@appsmith.com from the email of the account you'd like deleted?
