### ISSUE TITLE
[Bug]: Image and Default Image property accepting 2 different format at the same time without showing any error.

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#25027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The issue is set one format of image in `IMAGE `proeprty and another format of different image in `DEFAUTL IMAGE` property then deploy it picks DEFAULT IMAGE property image only.
**image in IMAGE property :** https://assets.appsmith.com/widgets/default.png
**image in DEFAULT IMAGE property :** https://jpeg.org/images/jpegsystems-home.jpg

Attached image : 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/f2426183-4929-4c82-9739-a1d6f66d3c5b)

Expected Result : Application should throw error message saying that we can not insert 2 different images at the same time.

### Steps To Reproduce

1. Drag and drop an Image widget
2. Set  https://assets.appsmith.com/widgets/default.png in IMAGE property
3. Set  https://jpeg.org/images/jpegsystems-home.jpg in DEFAULT IMAGE property 
4. Now deploy the app 
5. Observe app is picking default image property value and is not showing error when we set 2 different values in both property fields.

### Environment

Production

### Version

Appsmith v1.9.25-SNAPSHOT

**Comment by somangshu** [comment]
Why do you think so @kavitasmoolya 

I think this is expected behaviour 
cc @kamakshibhat-appsmith
