### ISSUE TITLE
[Task]: GSheet issue (description kept obscure on purpose)

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#25039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Ref: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1688385460964199

**Comment by rohan-arthur** [comment]
[RCA doc](https://www.notion.so/appsmith/RCA-Gsheets-forking-vulnerability-issue-286cbac2892d45819ac84977cde3bd76)
