### ISSUE TITLE
[Bug]: List Widget is different style at first row

### ISSUE THREAD

**Issue by jrsittirat** [appsmithorg/appsmith#25050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Why the List widget is different style at first row and other row?
![image](https://github.com/appsmithorg/appsmith/assets/136780529/501351a6-f3e1-4940-8131-059cbd1c84da)

### Steps To Reproduce

at first row is bold and black shade, other row is normal and gray shade.

### Environment

Production

### Version

1.9.23

**Comment by pranavkanade** [comment]
@jrsittirat In edit mode, the first element is representative of how other elements will look when you deploy the app. This is a design choice the team has made to ensure it stands out. It's not a bug.
