### ISSUE TITLE
[Bug]: there comes a scroll bar in the container for fixed mode even though the content is not overflowing

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

there comes a scroll bar in the container for fixed mode even though the content is not overflowing

### Steps To Reproduce

1. Dnd A container
2. change height to fixed mode
3. notice there is a scroll in EDIT MODE
https://www.loom.com/share/8960a9f4f90e4250988b5df34738b22c

### Environment

Production

### Version

Cloud/Self-hosted

**Comment by ramsaptami** [comment]
this is a non-issue on anvil layout system hence closing it
