### ISSUE TITLE
[Bug]: empty object is getting added on editing function 

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#25065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Issue is related to mutation on editing the function this.myVar1 is getting updated 
steps to reproduce - Add and remove ";" in function myFunc1 verify the this.myVar1 value increased
`export default {
	myVar1: [{
		"id":"1",
		"Name":"test",
		"Gove":22,
	  "date": new Date()
	}],
	myVar2: {},
	myFun1 () {
		this.myVar1.push([])
	},
	async myFun2 () {
    Table3.setData(this.myVar1)
	}
}`

https://github.com/appsmithorg/appsmith/assets/80756091/bf12dd05-19bf-47a3-88b6-fefa255984e0

### Steps To Reproduce

mentioned as above

### Environment

Release

### Version

cloud

**Comment by bharath31** [comment]
@Rishabh-Rathod looks like the function dry runs are mutating variables. can you look into this?

**Comment by ohansFavour** [comment]
This will be resolved as part of #25399. We are removing all dry runs.
