### ISSUE TITLE
[Feature] Button add a widget, API, or DB query in empty state

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2507]
## Summary

Most users spend a couple of seconds reading the message displayed in empty folder of widgets, APIs, DB queries before figuring out that they need to click '+' button. 

In the smart look video below, the user takes ~40 seconds to figure out how to add widgets: https://www.loom.com/share/6d917187e86e43a496da6056a6a6863b

We see new users take a few seconds to understand that the '+' button is the way to add widgets

Solution here:
1. introduce an 'add widget' button similar to the one we have in the NUX flow in empty states
2. Always include it when someone unfurls 'widget', 'API' or 'DB queries' because it's simpler to add widgets like that

**Comment by aakashDesign** [comment]
@areyabhishek Linking an older issue https://github.com/appsmithorg/appsmith/issues/1818 , contains some wireframes.
Can we get Stead to take a look at these?

**Comment by pranavkanade** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/5558
