### ISSUE TITLE
[Bug]: The Discard button in Table widget is not visible due to min-dimensions of button-type widget

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Discard button in Table widget is not visible due to min-dimensions of button-type widget

### Steps To Reproduce

<img width="961" alt="Screenshot 2023-07-04 at 6 30 55 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/5fcb0a5f-0d97-402a-b02d-12fcca7c1908">
<img width="900" alt="Screenshot 2023-07-04 at 6 30 34 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/c7bdd0d3-6ed6-4253-a652-2a7d71d94782">

### Environment

Production

### Version

Cloud/Self-hosted

**Comment by aswathkk** [comment]
This is no longer reproducible.
I guess the refactor we did in #24627 might resolved this issue.

@kamakshibhat-appsmith please re-open if this is still reproducible
