### ISSUE TITLE
[Bug]: "Resource not found" in sample databases. Both Movies and Users.

### ISSUE THREAD

**Issue by iSatVeerSingh** [appsmithorg/appsmith#25089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I want to add a sample data source. The application throws a "Resource not found" error. 

### Steps To Reproduce

1. Go to Datasources.
2. Try to add a new sample data source.
3. See the error in the toast.

### Environment

Production

### Issue video log

https://www.loom.com/share/af7b3dc3dd154df2b5b960bee6c14371?sid=062a8e63-a054-4403-93f7-0d21a3cae906

### Version

Self Hosted / Development - 1.9.25

**Comment by pranavkanade** [comment]
@iSatVeerSingh, are you also running the appsmith backend on your local machine?

**Comment by iSatVeerSingh** [comment]
@pranavkanade No, I am using release backend.

**Comment by pheonix-18** [comment]
I am also facing the same issue. I setup an app smith backend docker running and start frontend. I got the same error.

**Comment by pheonix-18** [comment]
@pranavkanade Any updates on this?

**Comment by Irongade** [comment]
This issue is due to multiple environment changes.

Kindly check this thread on slack: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1687515124130089

@rohan-arthur @riteshkew. This might have to be prioritized and looked at.

**Comment by nidhi-nair** [comment]
@pheonix-18 @iSatVeerSingh could you please point out the steps that you have followed to set up server on your local?

**Comment by iSatVeerSingh** [comment]
@nidhi-nair Here is the step-by-step walkthrough.
[Screencast from 2023-07-22 13-31-48.webm](https://github.com/appsmithorg/appsmith/assets/85070570/0e7de694-1fd3-4b14-8353-e26451298962)

**Comment by nidhi-nair** [comment]
Hey @iSatVeerSingh ! Thanks for sharing the video. My question was more around how you have set up your server. You mentioned earlier that you are using release backend. I assume that is the nginx routing that has changed. If you are pointing to `release.app.appsmith.com`, this endpoint has been deprecated for use for community contributors. May I suggest running the server locally using a [docker image](https://github.com/appsmithorg/appsmith/blob/master/contributions/ServerSetup.md#setup)?

**Comment by pheonix-18** [comment]
@nidhi-nair I have tried earlier using local docker setup instead of appsmith backend server. The data sources were working at that time. 

Could you update the contributing guide so it will be helpful to new contributors. 

Thank You

**Comment by nidhi-nair** [comment]
@sum35h could you please take a look at this? Let's update docs based on whether we're going to host a CE compatible server anytime soon.
