### ISSUE TITLE
[Bug]: On toggling the JS mode in Table Data field, the page load property of the query switches from On to off

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On toggling the JS mode in Table Data field, the page load property of the query switches from On to off

### Steps To Reproduce

https://www.loom.com/share/ac6ca87b12d24ff08a62c9fd1080e7f8

### Environment

Production

### Version

Cloud/Self hosted

**Comment by chandannkumar** [comment]
Because of the above behavior, we can observe a issue where Error is thrown on Table data after Updating the table record

https://www.loom.com/share/398b722093e94e6196f21bfa20f5e66e?sid=4cdfe7a7-a06b-41a2-a2f9-95cfadab74e9

cc: @kamakshibhat-appsmith
