### ISSUE TITLE
[Bug]: Query response table showing extra empty column

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#25090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Query response table is showing extra empty column in the end. 
![Screenshot 2023-07-05 at 7 55 58 AM](https://github.com/appsmithorg/appsmith/assets/1757421/8efeecb5-ca43-4e80-8e39-87039f10e603)

### Steps To Reproduce

1. Run a sql query to fetch a single row. 
2. Check the data rendered as table. 

### Environment

Production

### Version

self hosted, latest as on 5 July 2023

**Comment by DarshanDixit05** [comment]
Hey ! I want to work on this issue, can you please assign it to me? Ill fix it.

**Comment by sumitsum** [comment]
Closing it as it is not reproducible anymore.
