### ISSUE TITLE
[Task]: Switch feature flag for ME as per release plan

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#25118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Add not cloud segment
- Add beta users to opt in segment

**Comment by sondermanish** [comment]
appsmith email domains enabled for release.app.appsmith.com,
enabled for internal.appsmith.com
appsmith prod will only have 5 default emails.
Rest of the instance id on appsmith-ee will get depending upon product call.
