### ISSUE TITLE
[Bug]: UI issues in new binding section design

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#25121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

UI issues for binding section mentioned in [thread](https://theappsmith.slack.com/docs/TGA9SH07N/F05F32WKVKQ)

### Steps To Reproduce

1. Create datasource
2. Create query
3. Run it
4. Checkout the bindings section

### Environment

Deploy Preview

### Version

Cloud - v1.8.6

**Comment by AmanAgarwal041** [comment]
Closing as the featured branch is merged
