### ISSUE TITLE
[Bug]: New query plus icon in entity explorer does not function on Firefox in certain scroll positions

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on the New Query plus icon in the entity explorer, the create new pop up does not get invoked

### Steps To Reproduce

1. On a firefox browser, on appsmith, Create a new application
2. In the entity explorer, expand datasources, widgets and queries.
3. Scroll down, and then click on the plus icon under queries or even the plus sign next to the table name to see the select/insert overlay.
4. Note that the overlay does not get invoked
5. If we scroll up and try, it pops up occasionally.
<img width="542" alt="PopupCreatenew" src="https://github.com/appsmithorg/appsmith/assets/101863839/7cb7eb84-4986-4893-8b85-61b9a4f1aa00">

<img width="439" alt="Screenshot 2023-07-06 at 11 26 44 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/49a4db52-869e-498b-a330-aef9329543b2">

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
closing this issue as this interaction is deprecated now
