### ISSUE TITLE
[Bug]: Issues with centring of the widget in Edit mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Issue with JSON form - When there are multiple fields in JSON form , and your click on the first one to add some details , the widget starts centring and the current input field goes out of view
2. Issues with dropdown (for select widgets, phone etc)
3. Issue with Modal, on clicking the child widget inside the modal, the main canvas starts scrolling

### Steps To Reproduce

https://www.loom.com/share/17b287ca5e794602bb47c51c930fe7d8

Link to app-->
[Untitled application 97 (2).json.zip](https://github.com/appsmithorg/appsmith/files/11965214/Untitled.application.97.2.json.zip)

### Environment

Production

### Version

Cloud/Self-hosted

**Comment by kavitasmoolya** [comment]
Validated on release Appsmith v1.9.32-SNAPSHOT
Issue with JSON form - When there are multiple fields in JSON form , and your click on the first one to add some details , the widget starts centring and the current input field goes out of view 
Issue with Modal, on clicking the child widget inside the modal, the main canvas starts scrolling

Working fine
