### ISSUE TITLE
[Task]: Update branding configuration to use tenant configuration instead of env

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#25186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by sharat87** [comment]
@ankitakinger, branding doesn't use env variables, does it? If I recall right, it was the first configuration that was powered by Tenant configuration. Can you elaborate if I misunderstood please?

**Comment by ankitakinger** [comment]
When we click on submit button, we call the /env API and not the tenant API. That is something that needs to be updated now since we have tenant API for updation.

**Comment by sharat87** [comment]
Ahh you mean the API we're using... yes, this is a tech debt that me and Arpit took back then. Yes, we have to repay this. In the `/env` API's implementation for this though, the data is stored in Tenant Configuration only, right?

**Comment by ankitakinger** [comment]
Yes. But wait a minute, this issue is actually been taken care of by me and Nilesh under this duplicate issue: https://github.com/appsmithorg/appsmith/issues/26016

So we can close this one.

**Comment by sharat87** [comment]
Oh you operating on negative time there? Cool! 😜

Closing then.
