### ISSUE TITLE
[Bug]: Add page from templates option seems to appear and disappear sporadically

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#25239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

These screenshots were taken less than a minute apart. The option to add a page from a template seems to sporadically appear and disappear

<img width="526" alt="image" src="https://github.com/appsmithorg/appsmith/assets/20532920/9e9698e0-27da-450d-8987-a632b55fe73a">

![Screenshot 2023-07-10 at 12 50 26 PM](https://github.com/appsmithorg/appsmith/assets/20532920/550dcf85-1a12-4f63-8b9b-851b2bd3caf1)

### Steps To Reproduce

This seems flaky. Not able to find out why this happens

### Environment

Production

### Version

 v1.9.26-SNAPSHOT

**Comment by kocharrahul7** [comment]
This is intended behaviour. This option disappeared for the auto layout canvas.

**Comment by akash-codemonk** [comment]
There are two scenarios where it will be hidden. 
- when on an airgap instance
- when auto layout is enabled.
