### ISSUE TITLE
[Bug]: An internal server error pops up when we fork an application

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I fork an application into a new workspace, an internal server error pops up. 

### Steps To Reproduce

1. In app.appsmith.com, create a new workspace 
2. Fork an existing application with some datasources into this workspace
3. Note an internal server error pops up and then the fork modal comes up.

Tried this with multiple apps, and the error comes up on all of them

<img width="1426" alt="Screenshot 2023-07-10 at 4 28 07 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/9efad318-ec27-4cce-a259-3fa30920d7a4">

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/appsmithorg/appsmith/assets/94514895/eb2ad049-f633-4114-b091-43696e263908
