### ISSUE TITLE
[Feature] Allow batching widget property updates

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2528]
## Summary

Allow evaluations to handle `batchUpdateWidgetProperties` OR `updateWidgetProperties`.

## Motivation

Today if multiple properties of a widget needs to be updated, calling `updateWidgetProperty` on each of the properties MAY cause more than one evaluations, when only one would ideally be necessary.
If we can update the unevalTree with multiple updates at once, one evaluation would suffice. 

## Additional Context

Suggested API: `updateWidgetProperties(propertiesToUpdate: Array<{widgetId: string, propertyPath: string, propertyValue: any}>) => void`

**Comment by hetunandu** [comment]
Implemented in #2685
