### ISSUE TITLE
[Bug]: Unable to authorize new GSheets on an environment which has been upgraded from last version

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the upgraded release environment, Unable to authorize new or existing GSheets 

### Steps To Reproduce

1. Sign into https://release-ee-https.appsmith.com/applications
2. Create a new workspace, and create a new gsheets datasource
3. Click on save and authorize.
4. Note user is taken to the error page - 
 {"responseMeta" : {"status": 500, "success": false, "error": {"code":5000, "message" : "Internal server error while processing request"}}}

<img width="1061" alt="Screenshot 2023-07-11 at 11 36 54 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/e1b1e631-5097-4ac3-aaa0-84ddc3cbdf41">

### Environment

Release

### Version

Cloud

**Comment by sumitsum** [comment]
Looks like the API server is using release-cs now but when it started up the first time it used cs.appsmith and registered itself there. So it does not seem like a code issue but a setup issue.

**Comment by btsgh** [comment]
@sumitsum - Just tried creating a new Gsheets DS and tried to authorize the same on [release-ee ](https://release-ee.appsmith.com/)- it throws the same error.

**Comment by sumitsum** [comment]
Closing it as evidence points it towards a setup issue. _[details](https://theappsmith.slack.com/archives/C02GAUE9P5H/p1689062518814799)_
