### ISSUE TITLE
Feature: Support on Azure container apps

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith#25283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Document Appsmith deployment on Azure container apps platform

### Why should this be worked on?

More deployment options on Azure.

**Comment by danciaclara** [comment]
@sum35h Could you share more details and info around this ticket? thanks

**Comment by danciaclara** [comment]
@sum35h are we doing this?

**Comment by jnikhila** [comment]
@sharat87 and @pratapaprasanna - Could you please help us out here?
