### ISSUE TITLE
[Bug]: Getting duplicate configuration error on saving staging datasource

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#25299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1439" alt="Screenshot 2023-07-11 at 2 42 05 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/86a862fc-a293-4aac-a825-452c7275f690">
<img width="1439" alt="Screenshot 2023-07-11 at 2 42 49 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/58b6dff8-9f42-45d3-99f7-7bc6fbb07e8e">
<img width="1439" alt="Screenshot 2023-07-11 at 2 42 55 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/47c43acc-74a3-4ad8-885c-3a11057d4582">

### Steps To Reproduce

1. Go to [this](https://ee-1471.dp.appsmith.com/app/untitled-application-2/page1-64ab95687e0b0d72d1dbb42e/edit) app
2. Go to active datasource and open 'duplicateconfigissue' mongo datasource
3. Switch to staging env for it and fill details
4. Try to save the dataource, observe error is thrown

### Environment

Deploy Preview

### Version

https://ee-1471.dp.appsmith.com/

**Comment by kamakshibhat-appsmith** [comment]
https://www.loom.com/share/10d023b0b0f74d00baff5a8f52a0024e 
cc: @btsgh
