### ISSUE TITLE
[Feature]: Ability to access image/canvas element in appsmith

### ISSUE THREAD

**Issue by mrharmonies** [appsmithorg/appsmith#25310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

hello good people of the appsmith-land.!

im trying to use teachable machine library to classify image in appsmith. i drop an image widget, Image1, and load an image in base64. the image displays.

i initialize the tensorflow.js and tmimage.js, load the trained model then i try to use the tmimage.predict function to make prediction, by using model.predict(Image1.image). It didnt work. it get  "TypeError: Cannot read properties of null (reading 'drawImage') error". 

I assumed the model.predict wants an image element instead of URL of the image (Image1.image only returns the base64 url). According to documentation, model.predict expect this:

`model.predict(
  image: HTMLImageElement | HTMLCanvasElement | HTMLVideoElement | ImageBitmap,
  flipped = false
)`

I request the ability to access the image element/canvas element appsmith. I think this feature is beneficial for many developers using appsmith especially when using ML library to read and classify images and also accessing image/canvas for image/canvas manipulation.

### Why should this be worked on?

I think this feature is beneficial for many developers using appsmith especially when using ML library to classify images and also accessing image/canvas for image/canvas manipulation.

**Comment by Nikhil-Nandagopal** [comment]
@mrharmonies you can access the image of the appsmith image widget but I am unclear on why you need access to the canvas as an image.
