### ISSUE TITLE
[Feature]: Add workspace level actions on the left side as well

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#25321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Most app interactions from the onboarding form; homepage navigation from an application by clicking on the logo; listing and navigating between workspaces; admin page access etc are left-sided operations on Appsmith but, a user has to move to the right side to perform actions like import, add new application, members etc.

Intuition is to have it on the left itself for quicker navigation

### Why should this be worked on?

Improve accessibility

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we're moving it to the top
