### ISSUE TITLE
[Bug]: Incorrect formatting indent

### ISSUE THREAD

**Issue by fguizc** [appsmithorg/appsmith#25325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create the API, before I write the request parameters, which are formatted as JSON, when I press command s to save, an error occurs with the indentation of the default formatting

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/12797847/0a95f19b-aaf5-4d9e-a7d8-117a4ec766b4

### Environment

Production

### Issue video log

https://github.com/appsmithorg/appsmith/assets/12797847/0a95f19b-aaf5-4d9e-a7d8-117a4ec766b4

### Version

Appsmith Community v1.9.22

**Comment by arunvjn** [comment]
We are relying on code-mirror's built in indent function to achieve prettification. The expression 
```js
{{ 
{  
x: 2, y: 3
} 
}}
```
is recognised and treated as a block statement and not a JS Object. We'll need to implement some custom prettification logic here to solve this.
