### ISSUE TITLE
[Bug]: Service account credentials get displayed on review page in the following scenario

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After trying to edit the prod and staging ds - and changing the service account creds or reentering it and saving, on the review page, these creds get displayed. This is a security issue. These details should not be listed on the Review page

### Steps To Reproduce

1. Go to Firestore DS and create a DS with Prod and staging creds. Save both - Note that the review page comes up and only Database URL and Project Id are displayed - as per requirement
2. Click edit and modify the service account creds for say Prod and save 
3. Note that on the review page - the service account creds are also displayed!

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/OsqPQaftnHidtyre

### Version

Cloud

**Comment by btsgh** [comment]
This is seen even on the Active DS page in the above scenario

**Comment by ayushpahwa** [comment]
This is since info like this is not supposed to be sent by the frontend. @sondermanish @nidhi-nair please check. We can also add a check from fe
