### ISSUE TITLE
[Bug]: Incorrect color logic generation for "Apply button" of Table filter

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#25330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The color combination in Apply button of Table widget filters isn't appropriate.  The background and text color makes the "Apply button" unattractive

![Screenshot 2023-07-12 at 3 56 25 PM](https://github.com/appsmithorg/appsmith/assets/95341241/b9b640c4-d559-4c7d-ad75-69f45bf80b24)

### Steps To Reproduce

1. Drag & drop a Table widget
2. Try to add a Filter for table data
3. Observe the "Apply" button for theme - Modern

### Environment

Production

### Version

Cloud/Production

**Comment by rohityadav2604** [comment]
@somangshu can you please assign this to me, i will look into it

**Comment by somangshu** [comment]
Greetings @rohityadav2604, thanks for showing interest 🎉 This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and let us know here.

**Comment by keyurparalkar** [comment]
@somangshu this issue is already been addressed in the PR: https://github.com/appsmithorg/appsmith/pull/25732. 

@rohityadav2604 apologies for this but can you pickup other good first issues?
