### ISSUE TITLE
[Enhancement]: Toggling in the datasource review page should be disabled

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the datasource review page toggling of environment from bottom dropdown should be disabled
Since prod and staging details are anyway shown on the review page, we do not need the dropdown to be enabled. Toggling it does not cause any data to be changed in the UI. 

### Steps To Reproduce

1. Create a DS with Prod and Staging details entered and saved. Note that the Bottom dropdown is disabled here. 
2. Get to the DS Review page - here all the details of Production and staging are shown
3. However the bottom dropdown is enabled here and we can toggle between prod and staging. 

Toggling it does not cause any data to be changed in the UI and Prod and staging details are anyway shown on the review page - hence we do not need the dropdown to be enabled.

### Environment

Production

### Version

Cloud

**Comment by ayushpahwa** [comment]
This is as per the designs. Please advise here @sribalajig @parth-appsmith

**Comment by parth-appsmith** [comment]
@btsgh As per my understanding, the datasource review page is within an application as it leads to application-level actions like creating a new query/API. Users should be able to switch the environment from within the scope of the application. 
The reason for disabling the switching of environments in datasource edit mode is that datasources reside at the workspace level and not the application level.

**Comment by btsgh** [comment]
@parth-appsmith -Hmm .. I am looking at the review page as being part of datasource scope as it shows DS details. 
The thought behind this enhancement is that, on this page, changing the dropdown to prod or staging achieves nothing, so why have it?

**Comment by riteshkew** [comment]
Closing this as per last comment and assuming the enhancement is no longer valid.
