### ISSUE TITLE
[Bug]: App sharing with app viewer access from deploy mode to me-qa2 user - me-qa2 user cannot see the Env toggle dropdown

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user tries to share an with app viewer access from deploy mode, to me-qa2@appsmith.cpm user - on logging in with that user,  the Env toggle dropdown is not visible.

### Steps To Reproduce

1. Login as me-qa1 into the [DP](https://ee-1471.dp.appsmith.com/)
2. Edit the bug verifications app
3. Deploy the app. Note that production and staging dropdown is seen in the bottom left and user can switch between the two.
4. Click on the share icon on the top right
5. Add the user me-qa1@appsmith.com and give Appviewer rights
6. Now signin to the above dp using me-qa2@appsmith.com in **incognito** mode. 
7. Note that the user can see app and launch it
8. However, the  production and staging dropdown is not seen in the bottom left

As me-qa2 is a user for which feature should be seen, with appviewer rights also, he should be able to view the prod and staging data.
<img width="1103" alt="Screenshot 2023-07-13 at 1 41 15 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/3a8bbbbb-5c83-4f23-a7e8-c0e9a4ce5d5a">
<img width="633" alt="Screenshot 2023-07-13 at 1 41 04 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/3eac276d-a1e1-492b-93f9-62d01534c56e">

### Environment

Deploy Preview

### Version

Cloud

**Comment by btsgh** [comment]
Note: Also seeing the same issue even when me-qa2 user is given app developer rights. Not seeing dropdown even on Edit in Canvas.

**Comment by ayushpahwa** [comment]
@nidhi-nair @sondermanish please take a look. Looks like a feature flag permission is maybe missing.
