### ISSUE TITLE
[Bug]: In the Active DS page, show more details does not get updated based on Prod Staging dropdown

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Active DS page, when we click on show more details, and switch between prod and staging, the details does not get updated based on Prod Staging dropdown

### Steps To Reproduce

1. Create any DS - say firestore / mongo with both prod and staging- Test connection and save for both prod and staging.
2. Go to the Active Datasources page. 
3. For firestore or mongo, expand the show more dropdown [Note that the env dropdown selected is Production]
4. Note the details displayed are of prod. 
5. Now change the dropdown value to Staging
6. Note that the show more details do not get updated to Staging values, they are retained with prod values.

### Environment

Deploy Preview

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/2HzTo7Xr5dMiWoFG

### Version

Cloud

**Comment by ayushpahwa** [comment]
@ChandanBalajiBP please add current env as a dependency for the ds info. @btsgh is this a critical issue?
