### ISSUE TITLE
[Bug]: App goes into infinite loop on selecting datasources

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#25356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/80334441/377565c8-013e-403b-b208-432880d3992d

### Steps To Reproduce

1. Login as me-qa1@appsmith.com and go to [this](https://ee-1471.dp.appsmith.com/app/untitled-application-1/page1-64afae1d682cc713e1b9e9de/edit) app (If you're on release you can use this [link](https://release.app.appsmith.com/app/untitled-application-1-1/page1-64b75e833ad38f49142abb4b/edit?environment=production))
2. Switch between pages, then switch between datasource
3. Observe it goes into infinite loop until we do hard refresh

### Environment

Deploy Preview

### Version

https://ee-1471.dp.appsmith.com/

**Comment by ayushpahwa** [comment]
@Parthvi12 @btsgh this seems like it is present on release also. Attaching slack thread for more info https://theappsmith.slack.com/archives/CPG2ZTXEY/p1689738666914739

**Comment by kavitasmoolya** [comment]
Validated on release Appsmith v1.9.32-SNAPSHOT and working fine now.
