### ISSUE TITLE
[Bug]: Calling the setDisabled method of the component resets the values already assigned by the JS script.

### ISSUE THREAD

**Issue by 31604086** [appsmithorg/appsmith#25364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I used the setter method for the component, I found that the values assigned by the previous variable were reset.

### Steps To Reproduce

1.Drag an input onto the canvas.
2.Create JS scripts.
3.JS scripts Code.
export default {
	myVar1: [],
	myVar2: {},
	myVar:'',
	myFun1 () {
		this.myVar = 'Hello'
		Input1.setDisabled(false)
		console.log(this.myVar) 
	},
}
4.The runtime observed the value of the variable myVar and found that myVar was reset.

### Environment

Release

### Version

Appsmith v1.9.27-SNAPSHOT

**Comment by bharath31** [comment]
@Druthi @Rishabh-Rathod could you please investigate this issue?

**Comment by Rishabh-Rathod** [comment]
@31604086 The JS variable value is a stored as session store ( on a refresh of the page the value resets ).

Does run time here mean the deployed version?  If yes, then JSObject variable is expected to reset back to initial value in deployed version.

**Comment by Druthi** [comment]
I was able to reproduce this. It is something to do with `unevalTree = dataTreeEvaluator.getOldUnevalTree();` in `evalTreeWithChanges` function. This seems to be taking the older state of the unEvalTree before the `myVar` was updated.

**Comment by 31604086** [comment]
In the deployed version, variables are reset, but arrays and objects are not.

> @31604086 The JS variable value is a stored as session store ( on a refresh of the page the value resets ).
> 
> Does run time here mean the deployed version? If yes, then JSObject variable is expected to reset back to initial value in deployed version.
