### ISSUE TITLE
[Feature]: Show widget modification trail during git commit

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#25389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Change log on git commit modal should include widgets as well.

### Why should this be worked on?

Encountered a scenario recently when entity refactor failed and because of this widget binding changed as well as seen in the video. 
The intention was to only change the function type to async and commit this single change but its related widget binding changed as well and caused incomplete information to be relayed during git commit and introduce a breaking change on the deployed app. 

Adding a change log about widget changes can help reduce such instances

https://www.loom.com/share/b0067fea4aa74c879a6b5a6d0d896990?sid=546a49bb-35d3-4fb5-bc7f-98c4f9eb75c7

**Comment by infinitetrooper** [comment]
We're solving this in this epic #24668
