### ISSUE TITLE
[Bug]:This value does not evaluate to type Video URL

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#25386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to give a static Ip address to the video widget, it returns: "This value does not evaluate to type Video URL."
The strange thing is when I bind the I.P. address to an Iframe with a 'video' tag, it works.
I'm on the latest version (1.9.27), self-hosted with Docker.

### Steps To Reproduce

1. Drag a video widget to the canvas
2. Try to use an IP address for the URL. 

### Environment

Production

### Version

Cloud & Self - Hosted 1.9.27

**Comment by Dorian6005** [comment]
Just reported this issue on the discord server. We need this feature because on a self-hosted application we may not have an internet connection sometimes, but we have a LAN and a server to take the things we need. The video is needed because we use it as "proof" of a taken action.

**Comment by alzerwv** [comment]
same issue, please save me ,baby.

**Comment by dilippitchika** [comment]
Should be an easy fix, @somangshu @sbalaji1192 can this be a good first issue?

**Comment by sbalaji1192** [comment]
@dilippitchika Yes, need to update the validation of the property.

**Comment by HyMike** [comment]
Hi, would love to help out. Is this completed already>?

**Comment by Nikhil-Nandagopal** [comment]
@HyMike this is not yet done, you can pick it up

**Comment by Nirupam-Naragund** [comment]
Hi,i would love to contribute to this , is this still open?

**Comment by becmorrell** [comment]
Hi, is this issue still open? @Nirupam-Naragund have you fixed?
