### ISSUE TITLE
[Bug]: Hitting connection pool error when trying to config ORACLE datasource

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#25383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I tried to config staging with same creds as that of Prod it is observed that the user is displayed with error message 

### Steps To Reproduce

1) Navigate to oracle DS
2) Config the prod DS 
3) Navigate to staging and try to config same creds as of Prod 
4) Click on test config on Staging 
and observe that user is displayed with error 
 
<img width="1792" alt="Screenshot 2023-07-14 at 12 49 04 PM" src="https://github.com/appsmithorg/appsmith/assets/132243297/e39dae2c-9755-4ca0-a005-d992b17526ff">

### Environment

Deploy Preview

### Version

Cloud

**Comment by nidhi-nair** [comment]
Closing since this was a config issue
