### ISSUE TITLE
[Bug]: Appsmith API Error `java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "o" is null`

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#25408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user encounters the error `java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "o" is null `when making a `GET` request to an `API`. It also happens with `POST` requests.

### Steps To Reproduce

API Endpoint: `https://mock-api.appsmith.com/users`
Body: `{"a":1}`
HTTP Method: `POST`
![image](https://github.com/appsmithorg/appsmith/assets/114161539/ca32b9ac-8a3d-499c-8103-bd6cc9ddca09)

For more details about this issue, you can refer to the [Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1689005370629189) and the conversation with the [user](https://app.frontapp.com/open/cnv_11zxo570?key=PigvRTBY6rExgYlM_JhlcCFGXwqBOl9Z).

### Environment

Production

### Version

Cloud: Appsmith v1.9.27-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_wr32k)

**Comment by mgperry1** [comment]
Any ETA on this bug,  without a fix we are stuck not being able to use one of our API servers.  Thanks

**Comment by mgperry1** [comment]
How about someone  setup a class on how to troubleshot and fix backend issues in the Appsmith code base.. I'd signup and help out with little bugs like this one.

**Comment by riteshkew** [comment]
@mgperry1 Thank you for showing interest. We'll definitely take this suggestion and find something to enable developers to fix bugs like this one.

**Comment by sondermanish** [comment]
@mgperry1 are you able to reproduce the above issue as it's mentioned (with https://mock-api.appsmith.com/users)? 
I'm getting a successful response when using a GET request. the POST doesn't work on appsmith or postman.

**Comment by riteshkew** [comment]
@morandalex Please elaborate more on the issue you are facing. What endpoint you are using, which version of appsmith you are on and whether the same API works on any other client, such as Postman.

**Comment by riteshkew** [comment]
@mgperry1 Are you still facing the issue? We can get on a call to help debug this faster.

**Comment by learnbasicsfun** [comment]
I still face this issue.

I self host appsmith in docker and wanted to make api calls to other containers on the same docker network but unable to do using the container name as host in the api endpoint.

The container I am trying to connect was a django app

![image](https://github.com/appsmithorg/appsmith/assets/87423035/523285a3-05f2-49aa-85e2-24fa75cb78cb)

But the api call works fine when the if I use internal ip of the docker container

![image](https://github.com/appsmithorg/appsmith/assets/87423035/204ccd04-7da8-4824-90e6-935674104b73)

When I make a ping from the appsmith container it works fine

![image](https://github.com/appsmithorg/appsmith/assets/87423035/d07f565d-5ffb-43d8-bfcb-59bdd0c8f4b1)


All the other data sources are using the container name as the host name and works fine, Recently we figured out a similar issue with some of our django container that django does a validation of host name for the incoming request to be a ip or domain name, On updating that to support for container names as well the issue as solved but I don't have much idea why appsmith datasources can be container name but the not the apis, @Nikhil-Nandagopal @mohanarpit
