### ISSUE TITLE
[Bug]: No longer possible to use JS in RestAPI DataSource's URL

### ISSUE THREAD

**Issue by nguyennk92** [appsmithorg/appsmith#25421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After updating to version > 1.9.24, our API using stored JS in DataSource no longer works, it gave the following error:
```
Your API failed to execute:
Illegal character in authority at index 7: http://{{appsmith.store.token_api_endpoint[appsmith.store.env]}}/v1/admin/tokens

{
"actionId":"64b606f1d661ba5f071e74fa"
"requestedAt":"2023-07-18 10:40:52"
"headers":[...]
"httpMethod":"GET"
"url":"{{appsmith.store.token_api_endpoint[appsmith.store.env]}}/v1/admin/tokens"
}
```
We are current config our datasource like so:
<img width="482" alt="image" src="https://github.com/appsmithorg/appsmith/assets/30664183/88aa1f25-2d92-43e5-afac-14da1a087f9b">
We have a script to put these value into store:
<img width="854" alt="Screen Shot 2023-07-18 at 10 42 16" src="https://github.com/appsmithorg/appsmith/assets/30664183/5d90f5b4-74bf-412e-a65c-c3a8798d6ad2">

### Steps To Reproduce

1. Create a RestAPI DataSource
2. Use JS in URL fields
3. Create an API using the above RestAPI DataSource then run it

### Environment

Production

### Version

Self Hosted - 1.9.26

**Comment by pranavkanade** [comment]
@rohan-arthur, did we ever allow this?

**Comment by Nikhil-Nandagopal** [comment]
I believe this is now fixed
