### ISSUE TITLE
[Bug]: The text alignment and spacing of activation section in Query page looks off. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Login to an account where only Activation **schema** is enabled, and note that in the DS query page, the heading text are not aligned in a straight line, and also the spacing between Connect widget and Add new widget is higher than the spacing between the rest. The text font spacing/size also seem to be different. 

### Steps To Reproduce

1. Create a new DS [from an account where only Activation **schema** is enabled]
2. Create a new query and note the following on the query page's right section which has Schema displayed - 
The headings text are not aligned in a straight line
The spacing between Connect widget and Add new widget is higher than the spacing between the rest. 
The text font spacing/size also seem to be different. 

<img width="287" alt="Activation" src="https://github.com/appsmithorg/appsmith/assets/101863839/7d9955ce-b0ae-4a88-bb60-0394bb73a108">

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
we've updated to a new layout in the query page, this does not occur anymore
![Screenshot 2024-01-29 at 12 11 03](https://github.com/appsmithorg/appsmith/assets/94514895/9a3f837e-b200-428e-b3d1-e437e3d75c28)
