### ISSUE TITLE
[Task]: Cypress test with All widgets for canvas splitting

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#25433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Create a git connected App and create feature branch
- Add all the widgets in the canvas and commit the changes
- Merge the feature branch back to master
- Verify all the widgets are present or not

**Comment by AnaghHegde** [comment]
@ginilpg @Parthvi12 Can we pick this up in this week or next week?

**Comment by infinitetrooper** [comment]
@Parthvi12  - did we add this already?

**Comment by peyush99** [comment]
@AnaghHegde @ginilpg @Parthvi12 , has this been worked upon ,or do we still need to add this?

**Comment by akshayvijayjain** [comment]
@AnaghHegde 

is Canvas splitting same as auto-layout?

https://community.appsmith.com/content/blog/shifting-auto-layout-maintenance-mode

and since auto-layout is discontinued, will it make sense to add cypress test for canvas splitting.

**Comment by peyush99** [comment]
@AnaghHegde 

As I comprehend it, canvas splitting is linked with the auto layout feature. However, auto layout feature has been deprecated and is behind a feature flag. Considering that some users might still be utilizing the deprecated auto layout feature, I came up with the following cypress test scenarios for it : 


**1. Widget Rendering and Placement in sections**
**Test Case 1.1:** Verify that each type of widget is rendered correctly on the canvas.
**Test Case 1.2:** Ensure widgets can be moved to any position on the canvas or removed without issues.
**Test Case 1.3:** Test resizing of widgets and verify the new size is applied correctly.

**2. Canvas Splitting (multiple sections or containers within the canvas)**
**Test Case 2.1:** Split the canvas into two sections and ensure both sections are rendered correctly.
**Test Case 2.2:** Move widgets between the split sections and verify their correct placement.
**Test Case 2.3:** Merge the split sections back into one and ensure no data is lost and widgets maintain their position.

**3. User Interactions**
**Test Case 3.3:** Perform multiple split and merge operations and check for any anomalies.
**Test Case 3.4:** Check functionality for copy, paste, undo, redo for the widgets.


Your insights would be greatly appreciated on these test scenarios.
Please inform me if there are any misunderstandings or gaps in my understanding of this issue.

**Comment by akshayvijayjain** [comment]
some relevant links
https://www.appsmith.com/blog/introducing-new-mobile-responsiveness-feature 

https://www.appsmith.com/blog/intent-driven-design-mobile 

https://community.appsmith.com/tag/auto-layout 

https://www.appsmith.com/blog/building-responsive-ui-tools-3 

https://tbrizitsky.medium.com/rethinking-ui-building-in-appsmith-part-i-18bb08fa0232

 https://www.youtube.com/watch?v=qa3WgvO_ZWo
 
 @peyush99 
 Please add the way to enable auto layout through feature flag

**Comment by akshayvijayjain** [comment]
@Nikhil-Nandagopal 

what can be next steps for this issue. 

@ginilpg @Parthvi12 

we left it for now, since we are not very clear with this canvas splitting feature.

**Comment by daaliachhak17** [comment]
Any update on this ticket? Do we need to work on this or it is on hold ?

**Comment by infinitetrooper** [comment]
Closing in favour of an updated testing plan.
