### ISSUE TITLE
[Bug]: Page is bydefault hidden on  adding"KYC Dashboard" template

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#25435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Added page is by default hidden when user fork " KYC Dashboard" template

Expected : Page should not be hidden but in show mode

Attached screen shot : 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/453c632b-5154-41d1-a22f-3fb419bc8efe)
![image](https://github.com/appsmithorg/appsmith/assets/134914630/c5149115-e2fe-4e8f-9250-ecea7583d174)

### Steps To Reproduce

1. Go to template section 
2. Fork  "KYC Dashboard" template
3. Observe page is hidden by default

### Environment

Production

### Version

Appsmith v1.9.27-SNAPSHOT

**Comment by jacquesikot** [comment]
The page was set to show and a new app json was uploaded to S3.
