### ISSUE TITLE
[Bug]: Admin settings - Branding - Color theme - While we "Click" on a button we are able to see a different color or the default color theme in the application

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#25446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When admin have changed the settings of color theme in the application, we are able to see a default color when we click on a button.

https://github.com/appsmithorg/appsmith/assets/104895602/2b2c5bf7-047e-4e05-b5ac-8d103da91055

### Steps To Reproduce

1. Go to Admin setting and change the color theme to a different color
2. Click on any button in the application
3. Observe while clicking on the button we are able to see a change of color 

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.28-SNAPSHOT

**Comment by rohitagarwal88** [comment]
@ginilpg : could you please prioritise BE bandwidth for the task. It's an EE feature & effect the branding

**Comment by albinAppsmith** [comment]
**MOM of discussion happened with @NilanshBansal** 
1. Needs to add "active" parameter in v1/admin/env API.
2. Same value should be fetched in v1/tenants/current.
3. @NilanshBansal suggested that we should do a migration for the customers who already chose the branding color. This migration should populate the active value in DB.

**Comment by albinAppsmith** [comment]
As discussed, I will be writing a fallback function which will triggered in case if the branding color exist and active color doesn't exist in tenant API. This fallback is to handle the existing customers who have chosen a custom brand color and don't have an active color.

cc: @dilippitchika @rohitagarwal88
