### ISSUE TITLE
[Bug]: Cell range option fails and throws an error related to Memory 

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#25447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user navigates from Where clause to Cell range for "Fetch many" cmd it is observed that cell range is not being executed and throws an error "Appsmith In Memory Filtering Failed"

### Steps To Reproduce

1) Authorise Gsheet
2) Select Fetch Many
3) Select and add filter format for "Where Clause" 
4) add the necessary filter
5) Click on RUN
6) Select "Cell range" in the drop down in filter format 
7) Add the range field 
8) Click on RUN 
and observe the error displayed to the user
<img width="1785" alt="Screenshot 2023-07-18 at 4 56 37 PM" src="https://github.com/appsmithorg/appsmith/assets/132243297/a74c71c3-2341-47c0-ab97-4a2907350a01">

### Environment

Production

### Version

cloud

**Comment by Aishwarya-U-R** [comment]
@prapullc - can you please add error snaps for better understanding of issue?
