### ISSUE TITLE
[Bug] JS bound tabs allow more operations than required

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#2545]
## Description

Individual tabs can be removed from the `TabsWidget` by using JS and removing elements from the array.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create a `TabsWidget`
2. Bind tabs to a js variable.
3. Use a button to change the number of elements in the tabs array.
4. The tab removed from the array gets deleted in editor mode.

### Important Details
 - Version: Cloud
 - OS: All
 - Browser: All

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon @ofpiyush @riodeuno after thinking this through for a while, let's go ahead and disable js for tabs but also allow users to configure the isVisible property dynamically for each tab.

As a quick fix today, we can simply add the isVisible as a property in the tabs array but long term we can move this to a panel stack the way we do for table widgets
