### ISSUE TITLE
[Bug]: The application name tends to disappear on page reload.

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The application name tends to disappear on multiple page reloads. No specific pattern . Just keep on refreshing edit mode couple of time and the issue appears

### Steps To Reproduce

1. Do a page refresh in edit mode multiple times

https://www.loom.com/share/7ad77c6335614eaabe8a06106065ffe2

### Environment

Release

### Version

Cloud/Release

**Comment by kavitasmoolya** [comment]
Verified the fix on release Appsmith v1.9.32-SNAPSHOT and working fine now.
