### ISSUE TITLE
[Enhancement]: OIDC redirect URL should change when custom domain change

### ISSUE THREAD

**Issue by rhuanbarreto** [appsmithorg/appsmith#25453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When changing the custom domain in the settings, the OIDC redirect URL should change. If you don't have a user registered by form, all users get locked out due to wrong redirect URLs.

### Steps To Reproduce

1. Configure appsmith with a custom domain
2. Configure OIDC
3. Change custom domain
4. You can't login with OIDC anymore

### Environment

Production

### Version

Business Self Hosted v1.9.27

**Comment by pranavkanade** [comment]
Hey!

The workaround - when setting up Appsmith, you should first setup the custom domain and then configure the SSO.

**Comment by pranavkanade** [comment]
This is a feature request. As there was no feature to manage this automatically.

**Comment by rhuanbarreto** [comment]
If I already setup a domain and I change it, all hardcoded references to Appsmith Custom URL must be updated to reflect the new URL, or the backend should use `request.getHeader("referer")` in order to create a redirect URL. Today you need to first disable SSO and then change URL as a workaround.

From the user perspective and also semantically, this is a bug that should have been taken in consideration when the feature was developed and should be treated accordingly. Giving the user the ability to update the redirect URL automatically when the custom domain is updated doesn't sound like a feature at all.
