### ISSUE TITLE
[Feature]: Pass alt text to Avatar

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#25461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Since the images in Avatar component is not purely presentational, it is important for it to have an alt text. 

- [ ] Allow alt text in the component 
- [ ] get the first letter from the alt text to make it a fallback when image doesn't load 

### Why should this be worked on?

Better functionality

**Comment by Sripriya93** [comment]
QA done, working as expected. CC: @tanvibhakta
