### ISSUE TITLE
[Enhancement]: User experience : "Add Query" button next to the environment description on Review page 

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#25486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to review page user can see following
1) Edit and Add Query 
2) DS config details 
Now when the user tries to create query he is unaware of which environment he is trying to create in. For the user to identify which environment he needs to look at the bottom dropdown and understand the setup for the same making this difficult for user to configure which environment he is creating data for 

Expectation : we can move the Add query button next to environment DS config this would help user to understand 

### Steps To Reproduce

1) Config the DS for both environment 
2) On review page click on Add query 
and observe 

### Environment

Deploy Preview

### Version

Cloud

**Comment by parth-appsmith** [comment]
@prapullc datasources and their configurations are at a workspace level while the selected environment of the application is at an app level. 
When you're on a datasource review page and trigger create a query the query is created using the current selected application-level environment. Displaying add query option next to the selected application environment configuration on the datasource review page breaks the current IA. 

This should get solved with the new changes coming along with the IA redesign project,

**Comment by ayushpahwa** [comment]
Removing this from multiple env project in this case. @riteshkew
