### ISSUE TITLE
[Bug]: Auto save modal comes up for mongo on moving from prod to staging in edit DS page

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#25489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I have more than one datasource, one being mongo , on switching between the datasources and then switching between envs for mongo pops up autosave modal, ideally when there are no changes it should not come

### Steps To Reproduce

1. Create an app with multiple datasources containing mongo too
2. Switch between envs for mongo
3. Observe autosave modal comes up
Note: Not reproducible always

### Environment

Deploy Preview

### Version

deploy preview

**Comment by ayushpahwa** [comment]
This seems like a side effect due to the autofill from browser. Please verify if that is the case.
