### ISSUE TITLE
feat: WDS assistive color improvements

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#25497]
Improve color generation algo for cases when very dark seed in light mode or very light in dark mode, then the assistive color looks exactly the same.

![254316321-a70a8c87-e8cb-499b-9964-a345cdc96b1d.png](https://images.zenhubusercontent.com/64350c6b960bc9adc99eb4ac/f3297c15-f2bc-4b29-9e67-e232a95feaf4)![254316334-5c475b1a-5a38-4c16-9010-ba686c31c6dd.png](https://images.zenhubusercontent.com/64350c6b960bc9adc99eb4ac/065da9fe-8fd8-4fc7-8f1a-551e114a1fa1)

**Comment by ichik** [comment]
Any alternatives would be worse than the status quo for the case (achromatic seed, assistive being visually the same as accent).
