### ISSUE TITLE
[Bug]: Better error messaging should be provided if both environments permissions are not given

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Prod and Staging env permissions are not given on Roles for a user, when logged in as that user, it Currently throws an error toast to the effect -  unable to find env id
Better error handling required if both environments permissions are not given.

### Steps To Reproduce

1. Create a new role, and for this role, under datasources and queries, do not give execute permissions on both Production and Staging for a particular applicatio 
<img width="684" alt="Screenshot 2023-07-19 at 5 00 39 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/2109178c-9829-4e9b-ae6b-b267258dc452">
2. Now assign this role to a group and add a user to this group. 
3. Login with the particular user
4. Open the above application, and note the following error that pops up
<img width="805" alt="Screenshot 2023-07-19 at 5 06 48 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/8df8f5fc-5b61-4672-9de5-180046fce8c8">

### Environment

Deploy Preview

### Version

Cloud

**Comment by nidhi-nair** [comment]
Similar to #25485
