### ISSUE TITLE
[Task]: Update doc URLs in code

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith#25513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Update the doc urls in the codebase:
* The doc urls with versions are no longer maintained and will redirect the users to the docs homepage, so the code should be updated to point the URLs to actual pages. For example, in this [file](https://github.com/appsmithorg/appsmith/blob/82d7bccffa9f40f85db8a232bda0dc00e0fa0a0a/app/client/src/widgets/MapWidget/widget/index.tsx#L460).

#### List of URLs
[Doc urls](https://github.com/search?q=repo%3Aappsmithorg%2Fappsmith%20https%3A%2F%2Fdocs.appsmith.com%2Fv%2F&type=code) - The urls that are still pointing to the versioned URLs.

**Comment by jnikhila** [comment]
@somangshu and @dilippitchika - As the change is in the widget, I've assigned it to you. If this doesn't fall in your pod's purview, please assign it accordingly.

**Comment by somangshu** [comment]
@jnikhila what should the URL be changed to?

**Comment by jnikhila** [comment]
@somangshu - For the old url - https://docs.appsmith.com/v/v1.2.1/setup/docker/google-maps the new url is https://docs.appsmith.com/getting-started/setup/instance-configuration/google-maps.

For the other URLs, I'll share a spreadsheet.

**Comment by Ricky004** [comment]
This issue is still open. Can I contribute?

**Comment by dilippitchika** [comment]
Greetings @Ricky004  thanks for showing interest 🎉 , This is all yours. Assigning this to you now.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days. let us know here

**Comment by rohityadav2604** [comment]
Hi @dilippitchika can you assign this to me and share the spreadsheet of the new urls which needs to be changed. i will do it as soon as you will assign

**Comment by somangshu** [comment]
Sure @rohityadav2604. We can assign this to you. But I think it can be a little difficult to manage. 
However, [here is the link](https://docs.google.com/spreadsheets/d/10qLHfy4XIjNN_8CPzTu8B7ZNYUrCJM212ZOo8Qfkt9Q/edit?usp=sharing) to see all the URLs that need to be updated in our codebase. 

Let me know if you have any questions.

**Comment by ayerandge** [comment]
Question: Are all the URL's in "appsmith" repo? or they are spread across the repositories under appsmithorg?

Finding: Tried to do a spot check on few URL's, was able to find only few in "appsmith" repo.

**Comment by jnikhila** [comment]
@ayerandge - Please note that the spreadsheet contains a list of modified document URLs. Please use this spreadsheet as a reference to update URLs specifically within the appsmith repository. If you have any further queries, please feel free to ask. Thank you.

**Comment by nasserabd** [comment]
is this issue still open? I would love to contribute!

**Comment by somangshu** [comment]
@jnikhila is the work still not complete with the above linked PR?
What is exactly pending now?

**Comment by jnikhila** [comment]
@somangshu - The [list](https://github.com/appsmithorg/appsmith/issues/25513#issue-1813221038) added to the comment still shows the files with the old URLs.

**Comment by pkawale** [comment]
Hi @jnikhila , @somangshu - Is this issue still open ?  Thank you!

**Comment by dilippitchika** [comment]
Hello @pkawale it's still open, do you want to pick this up?

**Comment by pkawale** [comment]
Hi @dilippitchika , yes . I will start working on it. Thank you!

**Comment by digvijaysinghh** [comment]
Hi @dilippitchika, @somangshu Is this issue still open for contribution? would love to work on this!

**Comment by Gretel8** [comment]
Hi  @dilippitchika and @jnikhila, I would like to work on this issue if it is still open. Please assign it to me, thanks!

**Comment by jnikhila** [comment]
Sure @Gretel8, assigning it to you.

**Comment by digvijaysinghh** [comment]
@jnikhila Hey Nikhila, I also asked for the issue earlier, could you please tell me if I can work on it now? if so, please assign it to me!

**Comment by Gretel8** [comment]
> Sure @Gretel8, assigning it to you.

Thank you! I am working on it already, if @digvijaysinghh would like to split the work with me, I do not mind collaborating.

**Comment by jnikhila** [comment]
Thanks @Gretel8. @digvijaysinghh - Would you like to collaborate?

**Comment by digvijaysinghh** [comment]
@jnikhila @Gretel8 Thank you! I'll be happy to collaborate.

**Comment by jnikhila** [comment]
@digvijaysinghh - Great! I've assigned the ticket to you too.

**Comment by digvijaysinghh** [comment]
@Gretel8 Hi, Please tell me something that you want me to work on! so we could work together without issues!

**Comment by Gretel8** [comment]
@digvijaysinghh I can work on the first 233 URLs listed on the spreadsheet and you can work on the rest starting at 234.

**Comment by Gretel8** [comment]
> Hi @Gretel8 , I've checked and replaced all the URLs assigned by you to me from (234-467)! Shall I raise a PR?

Yes, go ahead and raise the PR. Thanks!

**Comment by Gretel8** [comment]
@jnikhila, @somangshu, @dilippitchika I have raised PR https://github.com/appsmithorg/appsmith/pull/27798, please review at your earliest convenience. Thanks!

**Comment by jnikhila** [comment]
@Gretel8 and @digvijaysinghh - Thank you for your contribution.
@somangshu - The PR is ready to merge.
