### ISSUE TITLE
[Bug]When an action is triggered using button, the timeout used is different than the user configured

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#2553]
## Description

User's API usually responds in 20-25 seconds. The user has configured a timeout of 60 seconds. But the client seems to be cancelling the API at 20 second mark.

**Comment by tazmaniax** [comment]
This 20 second timeout, ignoring the configured timeout, occurs, at least, for both a button onClick and a dropdown onOptionChange and only in "deployed" mode not "design" mode
