### ISSUE TITLE
[Bug]: Share app with a user with developer rights - on logging in with that user, Deploy errors out

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I share app with a user with developer rights - on logging in with that user, Deploy errors out

### Steps To Reproduce

1. Login as me-qa1 into the [DP](https://ee-1471.dp.appsmith.com/)
2. Edit [this](https://ee-1471.dp.appsmith.com/app/bugverifcations/uqi-64b8cf75b8318221bc0f3b7c) app
3. Deploy the app. Note that production and staging dropdown is seen in the bottom left and user can switch between the two.
4. Click on the share icon on the top right
5. Add the user [me-qa2@appsmith.com](mailto:me-qa1@appsmith.com) and give Developer rights
6. Now signin to the above dp using [me-qa2@appsmith.com](mailto:me-qa2@appsmith.com) in incognito mode.
7. Note that the user can edit the app. From inside the app, try to Deploy it, note that it fails with an error

<img width="1134" alt="Screenshot 2023-07-20 at 4 40 31 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/9c887cfc-6d82-4920-afea-1c4dda2a1f58">

https://github.com/appsmithorg/appsmith/assets/101863839/d6027317-3b07-4574-a32e-2d2f4bfe9705

### Environment

Deploy Preview

### Version

Cloud

**Comment by nidhi-nair** [comment]
@hiteshjoshi this is an app share issue with applications containing JS objects, reassigning to you for triaging.
