### ISSUE TITLE
[Task]: Revert Save and Refresh to Save for Google Maps License Key

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#25560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Relevant Slack thread : https://theappsmith.slack.com/archives/C02JV8G1MP0/p1689920542480849?thread_ts=1689740931.583169&cid=C02JV8G1MP0

**Comment by sharat87** [comment]
[This is the commit](https://github.com/appsmithorg/appsmith/pull/20771/commits/70e72368aeea7fbdde90c1cb0b3e91b4bdf21aec) we want to undo, and Maps Settings page should go back to showing "Save" button automatically.

**Comment by dhruvikn** [comment]
Closing wrt [this](https://github.com/appsmithorg/appsmith/issues/25559#issuecomment-1709810597).
