### ISSUE TITLE
[Enhancement]: Add a clear discoverable signifier to add an action when an event handler has no actions 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#25565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I view an event handler with no actions, I should see a clear discoverable signifier to add a new action so that, I have a clear entry point to configure the event handler via the action selector

### Steps To Reproduce

Open the property pane for a button widget and try spotting the CTA for adding a new action for any event handler 

### Solution

[Design Specs](https://www.notion.so/appsmith/Action-selector-Improvements-becaaa6bd5b54215bb2615547fb5ffa2?d=dd84e541af9a4a108c85b67f60dae027)

**Comment by arunvjn** [comment]
Fixed in [96d7903](https://github.com/appsmithorg/appsmith/commit/96d7903b7988781ca69c011409d4c531f9b67727)
