### ISSUE TITLE
[Bug]: On importing any json file, we see an error on the modal - Authorization failed, please check your details or try again

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#25578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Import any JSON file, observe the error on the modal as attached in the screenshot
https://drive.google.com/file/d/1czMu42-yC9uL-RbDG077sVOO2MHd6Aeg/view?usp=drive_link

### Steps To Reproduce

Import any JSON and observe the error in the modal

### Environment

Production

### Version

1.9.28

**Comment by rohan-arthur** [comment]
not reproducible anymore, maybe got fixed with something else

https://github.com/appsmithorg/appsmith/assets/94514895/21a3b7c7-56c1-4c38-965d-95a2ab074ee9
