### ISSUE TITLE
Update Git Pull to Fetch and Rebase

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#25590]
1. We currently do Fetch and Merge when we do Git Pull
2. This causes there to be a local merge commit in some cases
3. This commit cannot be pushed if there is a branch protection rule on the branch.
4. Fetch and Rebase will result in a clean history and solve this issue.

**Comment by pchambless** [comment]
I'm wondering if this will help my issue... I cannot pull the main branch into Appsmith even though I've resolved any differences in the main branch outside of Appsmith.  everything checks out in GitHub.

**Comment by AnaghHegde** [comment]
@pchambless What error do you see when you pull the changes? Do you see merge conflicts? 
It would be helpful if you can share more details on the issue you are facing.

**Comment by pchambless** [comment]
When I successfully completed all of these steps:
Step 1:  in Appsmith, create a branch from master branch
Step 2: Go to Github and create a Pull Request - compare the new branch to original branch
Step 3: Click Resolve differences and work through the conflcts, resolving the differences
Step 4: Merge the new branch into origin branch
Step 5: Open Appsmith: go to origin branch
Step 6: Discard and Pull changes

The changes I was trying to Merge in did not show up.

**Comment by pchambless** [comment]
My current situation... 

- I have a branch that has my desired changes. called **safe-copy**. 
- I want these changes in the master branch
- In Appsmith I have tried the Merge feature 
![image](https://github.com/appsmithorg/appsmith/assets/44928133/f4985c8c-15e1-4b59-a3ca-5bf1c02894d0)
- the changes do not propagate.

**Comment by CWatson-Tactile** [comment]
@pchambless 
I know this is quite old, but did you ever get a solution to this issue?

**Comment by pchambless** [comment]
It IS quite old... I'm not sure that I'm concerned about it anymore.  The company I was working for when I had these issues, I'm not working for anymore...

**Comment by CWatson-Tactile** [comment]
Ah, ok.
I am having a similar issue and their support hasn't done anything...

Thanks anyway!


----------------------------------------------------------
Connor Watson
Director of Information Systems - Tactile Engineering
----------------------------------------------------------




________________________________
