### ISSUE TITLE
[Bug]: Regenerate SSH key error comes up intermittently in git connected app on ME DP

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#25601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For git connected app, when we perform various git operations like commit, discard and merge and switching envs, sometimes following error comes up in dp:
<img width="1440" alt="Screenshot 2023-07-21 at 6 41 57 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/53b2612b-d783-4c38-bad3-5a55a1e20428">

### Steps To Reproduce

1. Connect an app to git
2. Perform git operations and switch between envs
3. Observe ssh key error is thrown

### Environment

Deploy Preview

### Version

Deploy preview

**Comment by ayushpahwa** [comment]
@Parthvi12 is this still applicable? I am not able to reproduce this issue.

**Comment by Parthvi12** [comment]
Closing as not reproducible
