### ISSUE TITLE
[Bug]: The SCIM representation icon is missing in the users page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#25612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The SCIM representation icon is missing in the users page
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/66793b7c-f12c-4b39-9df0-66e3fc468a0b">

### Steps To Reproduce

1. go to https://ee-1822.dp.appsmith.com
2. Login as admin
3. click on admin setting
4. click on users tab
5. check the Users which are linked from scim the icon is missing

### Environment

Deploy Preview

### Version

v1.9.26

**Comment by ankitakinger** [comment]
This is not a bug @RakshaKShetty. Shubham's changes are yet to go in. Hence you cannot see this icon. But let's keep this open for tracking.
