### ISSUE TITLE
[Bug]: The users are not getting deleted from Appsmith when those are deleted from the AD

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#25631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The users are not getting deleted from Appsmith when those are deleted from the AD
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/d498737f-5fc8-45b7-ad5a-e3915ddc5832">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/88217a6f-0fb5-4e1f-a54a-a120ca20f59a">

### Steps To Reproduce

1. go to https://ee-1822.dp.appsmith.com
2. make sure you have a user that is connected to AD
3. now go to AD and delete the user 
4. now wait for 30 min once the sync happens 
5. check the user that is deleted from the ad
6. the user  still exists in the appsmith User list

### Environment

Deploy Preview

### Version

v1.9.26

**Comment by infinitetrooper** [comment]
This is working, reopen if you can replicate.
