### ISSUE TITLE
[Feature]: [Test] create a user test to check the effectiveness of the table widget

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#25630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Create a table widget on the canvas by default for 10% of new users.

This is a test to see how users respond, and if it has a positive impact on user experience and activation.

This test should last 2 weeks, and the results will be analysed. If the results are not satisfactory, we will reverse this feature, and return to our current base state.

### Why should this be worked on?

We have noticed that users are finding a lot of success with the table widget. A large of users who drag and drop a table widget go on to connect their own datasource, and from that point are finding continued success.

**Comment by kavitasmoolya** [comment]
Note : it is behind a feature flag and the experiment is already complete.
