### ISSUE TITLE
[Bug]: GSheets - on creating a new query, the dropdowns size has increased and there is an overlap

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The dropdowns size [Operation, Entity, etc ] has increased, and there is an overlap in the Spread Sheet, Sheet name, Table heading row index dropdowns

### Steps To Reproduce

Create a new GSheets ds, and create a new query on it.
Note that the dropdowns sizes have increased. 
Also there is an overlap in the Spread Sheet, Sheet name, Table heading row index drop-downs

<img width="887" alt="gsheets" src="https://github.com/appsmithorg/appsmith/assets/101863839/29f88bc6-1da7-4ef8-a445-b13abe71f763">

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
DS page of S3, Mongo etc has also been impacted.

**Comment by prapullc** [comment]
Please refer to the screenshot misplaced close icon

<img width="1786" alt="Screenshot 2023-07-24 at 5 32 07 PM" src="https://github.com/appsmithorg/appsmith/assets/132243297/2634bbfc-6a36-42d6-b630-199c33a357eb">
