### ISSUE TITLE
[Bug] Evaluated pane floats away when said property is scrolled outside of view (screenshot)

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#2564]
## Description

Evaluated pane floats away when a property is scrolled outside of view
<img width="2043" alt="Screenshot 2021-01-13 at 6 54 06 PM" src="https://user-images.githubusercontent.com/65771350/104459046-396efc00-55d2-11eb-84f0-29c1a22ec900.png">

### Steps to reproduce the behavior:
1. Open property pane for the table widget.
2. Input a few lines of text inside table data
3. Scroll while the evaluated value pane is visible.

**Comment by SatishGandham** [comment]
Evaluated popup position is broken on the query editor screen. Needs more work.

**Comment by somangshu** [comment]
This will be taken up in docked property pane
