### ISSUE TITLE
[Feature]: Allow instance admin to configure OIDC connection name

### ISSUE THREAD

**Issue by geekyme-fsmk** [appsmithorg/appsmith#25660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, configuring an OIDC connection for appsmith signin results in this text being shown:

<img width="484" alt="Screenshot 2023-07-24 at 10 26 32 PM" src="https://github.com/appsmithorg/appsmith/assets/100678833/0611dfb9-a997-4adf-be49-53dd81a9143b">

Instead of just showing "Sign in with OIDC SSO", allow the instance admin to configure the text such as "Sign in with Google Login". 

### Why should this be worked on?

For users (especially non-technical ones) of this instance, it is not intuitive what OIDC means. 
Fixing this could enhance the user experience.

**Comment by infinitetrooper** [comment]
@hiteshjoshi @trishaanand  - What do you think about the complexity of implementing this? The value makes sense to me as users can use their IdP (or) Tenant names instead of SAML and OIDC which most end users lack the context of.

**Comment by colin-precisionos** [comment]
I would like to see this as well as it's confusing for our users since they don't know what OIDC is.  We use Microsoft ADD - since there's only a few options for providers, can you just hardcode Microsoft, Google, etc

**Comment by infinitetrooper** [comment]
@deepikaappsmith  - Let's discuss the complexity of this before the next sprint planning. The idea is to allow users to configure a keyword that can be used to replace OIDC/SAML. The final button text will read `Sign in with #keyword`, for example - `Sign in with Active Directory` (or) `Sign in with One Login` etc.

**Comment by colin-precisionos** [comment]
This sounds fine.  The keyword can be set in the SSO config and default to OIDC
