### ISSUE TITLE
[Bug]: The Active directory Provisioning goes to a quarantined state when the instance go down 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#25666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Active directory Provisioning goes to a quarantined state when the instance go down 
<img width="1165" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/4d77d915-133b-4d0b-8cb7-5bc43035762a">

### Steps To Reproduce

1. Go to active directory 
2. now add few groups and users to the application
3. and start provisioning 
4. now say suppose the instance https://ee-1822.dp.appsmith.com go down for some reason
5. now the provisioning go for quarantined state

### Environment

Deploy Preview

### Version

v1.9.26

**Comment by infinitetrooper** [comment]
More information here - https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/application-provisioning-quarantine-status
