### ISSUE TITLE
[Bug]: Custom JS Library methods occasionally do not work in view mode

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#25674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I execute some code that contains a reference to a custom JS library method, I occasionally face errors in view mode

### Steps To Reproduce

User report: https://discord.com/channels/725602949748752515/1133016939145470013

### Environment

Production

### Version

Cloud

**Comment by arunvjn** [comment]
This issue is not reproducible. The user's app somehow got into a corrupted state and re-importing the app fixed it. 
Will reopen the issue if we encounter this issue again. 
cc: @narhzih
