### ISSUE TITLE
[Bug] While rearranging the tabs in the property pane they jump around and overlap

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#2569]
### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to Tabs Property Pane
2. Click on the dots to reorder the tabs
3. See error

<img width="1680" alt="Screenshot 2021-01-14 at 12 01 54 AM" src="https://user-images.githubusercontent.com/34486435/104494231-2d982f80-55fc-11eb-94a2-5348db16ffe7.png">

**Comment by areyabhishek** [comment]
This is similar to #2104 Hopefully one can fix the other.
