### ISSUE TITLE
[Bug]: User createdAt trait not getting added in flagsmith user identifier

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#25702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The flagsmith user `createdAt` trait is not getting added to the user identifiers. 

### Steps To Reproduce

1. Signup with a new user on app.appsmith.com
2. Check the flagsmith dashboard for the newly created user traits. 
3. All the other traits are added but `createdAt` trait is missing

### Environment

Production

### Version

v1.9.29-SNAPSHOT

**Comment by kavitasmoolya** [comment]
Paired up with @NilanshBansal to Verify it on release and looks good to me
