### ISSUE TITLE
[Bug]: Select widget throws an incorrect error for missing value property

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#25706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Select widget throws an incorrect error for missing value property when source data in fact has a valid array. Can be reproduced on a new binding on a new widget too.

Affects view mode too, i.e. widget displays empty data

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/de358a65-28a5-4834-997f-9efabe822b87)

### Environment

Release

### Issue video log
https://www.loom.com/share/d059cbfff59b43d5b4dfbea9e4007b17?focus_title=1&muted=1&from_recorder=1

### Version

Cloud

**Comment by AnandiKulkarni** [comment]
@Rishabh-Rathod Working fine 
[screen-capture (3).webm](https://github.com/appsmithorg/appsmith/assets/80756091/76ea3535-4824-4d7a-aeb6-aa00d124865f)
