### ISSUE TITLE
[Bug]: Committing to app fails when there is only one environment  configured and query is created on different env

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#25715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an app is connected to git, and there is only staging configured. On creating query on prod and comitting fails with following error : 
<img width="1440" alt="Screenshot 2023-07-26 at 10 11 54 AM" src="https://github.com/appsmithorg/appsmith/assets/80334441/e12de478-0cc2-441e-9818-71bbe6b86887">

### Steps To Reproduce

1. Connect an app to git
2. Create only staging env for any DS e.g. MySQL
3. Create new query on prod for this datasource
4. Switch to staging and create one more query and run
5. Refresh the app and observe internal server error is thrown
6. Try committing changes it gives error

### Environment

Deploy Preview

### Version

Deploy preview

**Comment by btsgh** [comment]
Verified and found to be fixed on Release [cc: @Parthvi12 ]
