### ISSUE TITLE
[Bug]: Staging not configured - Dual error on toggling env with data bound to table in Table Data  section - Both errors seem in appropriate

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Staging is not configured [for any ds] - Dual error on toggling env with data bound to table in Table Data section of property pane - Both errors seem in appropriate

### Steps To Reproduce

1. Create an application. Create a new DS. Ensure the bottom left dropdown is on Staging
2. Configure Production env for the DS and leave Staging blank
3. Now create a new select query to get data from the table on the above DS.
4. Run the query and bind the query data to a table
5. On the canvas, Note that the data is displayed as per prod env config
6. Change the Environment to Staging
7. Note on the property pane section, the Table Data errors out with two errors. 
8. First an error comes up [Data is undefined, re-run your query or fix the data], it flickers out, and then the second error is displayed [This value does not evaluate to type Array<Object>}]
9. Both errors seem inappropriate
Only one error should come up.
Also The error should be more useful/appropriate.

<img width="1182" alt="ErrorWhileSwitchingDataimage" src="https://github.com/appsmithorg/appsmith/assets/101863839/0387832d-3881-4899-98e6-e2711c881ed1">

https://github.com/appsmithorg/appsmith/assets/101863839/48857039-fe3d-4cc5-9adf-a32f1be6c607

### Environment

Release

### Version

Cloud

**Comment by ayushpahwa** [comment]
Hey @btsgh can you reverify this behaviour on release? I am not able to reproduce

**Comment by btsgh** [comment]
Yes - @ayushpahwa  - not able to reproduce now. Moved it to Done.
