### ISSUE TITLE
[Feature] Allow users to create a table in the mock database

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2572]
## Summary

Allow users to created tables in the mock database.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek what is the use case here? The mock DB is reset every hour so this doesn't seem very valuable. I would suggest we ship with a separate DB for a user instead as mentioned in this issue #2506

**Comment by areyabhishek** [comment]
This is only for the self-hosted scenarios. A user on discord asked this question.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek the mock DB in self-hosted is the same as the one in cloud-hosted so I don't see any difference here.
@mohanarpit am I mistaken about this?

**Comment by areyabhishek** [comment]
I didn't realize that. I thought the mock DB ships with the container. Then I'll close the issue. 
I understand @nidhi-nair's question on stand up call today.
