### ISSUE TITLE
[Bug]: Git connected apps in v1.9.27 or older versions containing datasources, shows uncommitted changes with all datasource modified 

### ISSUE THREAD

**Issue by Vijetha-Kaja** [appsmithorg/appsmith#25739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We have an app in automation which is created in v1.9.24, we are importing the app in latest version & observed that it is showing uncommitted changes for all the data sources although we didn't make any changes 
<img width="744" alt="Screenshot 2023-07-26 at 12 26 00 PM" src="https://github.com/appsmithorg/appsmith/assets/119562824/81006729-745c-4e7e-acc0-19b9232bc25c">

### Steps To Reproduce

1. Import any git connected app (created in 1.9.27 or older version) with datasource and queries on release.
2. Click on the commit button & it shows uncommitted changes in git sync modal with all datasources modified.

### Environment

Release

### Version

Release

**Comment by Parthvi12** [comment]
E.g commit: https://github.com/Parthvi12/testmigration101/commit/7ccdf8369e17250a6d786de0f6f7b24d90c90c30

**Comment by Parthvi12** [comment]
Not treating it as blocker, refer here: https://theappsmith.slack.com/archives/CTHN8GX5Y/p1690373931042059

**Comment by nidhi-nair** [comment]
This one isn't a bug in itself, closing the issue for this reason. We'll create another issue for removing the messages field in datasources from persistence on version control.
