### ISSUE TITLE
[Feature] Enable markdown in the Rich Text Editor

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2574]
## Motivation

Users are likely to be used to markdown for their online writing experiences. I personally find it inconvenient to use formatting from the options.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair markdown editors need a preview mode which is incompatible with the RIch Text Editor, hence we've planned for a separate markdown component. I'm closing this in favor of that #2047
