### ISSUE TITLE
[Bug]: geolocation.currentposition.coords.lat is giving error also on map geololation is giving lint error

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#25746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below code gives error - 
`func44:async()=>{
appsmith.geolocation.getcurrentposition()
let var1 =    appsmith.geolocation.currentPosition.coords.latitude
}`

<img width="442" alt="image" src="https://github.com/appsmithorg/appsmith/assets/80756091/69177ef4-82db-4d7b-976b-7143a0d354a1">

Also  below data in map  is giving async/sync lint error

[
  {
    "lat": {{appsmith.geolocation.currentPosition.coords.latitude}},
    "long": 50.132,
    "title": "Location1"
  }
]

Recording:

https://github.com/appsmithorg/appsmith/assets/80756091/9471eccf-fb10-4983-b67c-e1d449c1d768

### Steps To Reproduce

Add above code and run 

### Environment

Production

### Version

cloud

**Comment by Druthi** [comment]
So 
1. the right method to be using to get the location is `getCurrentPosition` and not `getcurrentposition`
2. `appsmith.geolocation.getCurrentPosition()` is an async operation and so `appsmith.geolocation` will still be an empty object until the location is retrieved. 

@AnandiKulkarni 

If you try the code below, it should work.
`func44:	async()=>{ 
		const location = await appsmith.geolocation.getCurrentPosition(); 
		let var1 = location.coords.latitude; 
	},`

**Comment by AnandiKulkarni** [comment]
@Druthi could you please try this - ```
const location = await appsmith.geolocation.getCurrentPosition();
		let var1 = appsmith.geolocation.currentPosition.coords.latitude
		return var1
```

**Comment by AnandiKulkarni** [comment]
@arunvjn @Druthi Hey Arun could you please help here, do let me know if this function should return coord of geolocation currently there is error coming  as 'undefined
`func44: async()=>{ const location = await appsmith.geolocation.getCurrentPosition(); let var1 = location.coords.latitude; }'`

**Comment by Druthi** [comment]
@AnandiKulkarni Spoke to @arunvjn and concluded that `var1` should not be undefined. So looking into a fix for this. Will update you once it is done
