### ISSUE TITLE
[Bug]: SAML - unable to disconnect, when server went down during SAML configuration

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#25758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While configuring SAML on the EE dp, the instance went down. When it came up, it showed SAML as configured, but I was unable to login. Gave a keycloak error. On trying to disconnect SAML - it gives unexpected error

### Steps To Reproduce

1. As an instance admin, configure SAML [DP - https://ee-1916.dp.appsmith.com/]
2. At this point, while saving and restarting SAML config, the DP went down
3. After the DP came up, SAML shows up as configured
4. However, user is unable to login with SAML sso
5. On trying to disconnect SAML to reconfigure - it gives unexpected error

https://github.com/appsmithorg/appsmith/assets/101863839/c94f970a-5354-438c-8208-d5526097cdbe

### Environment

Release

### Version

Cloud

**Comment by hiteshjoshi** [comment]
Closing this until this happens again, due to lack of logs and a possibility of misconfigured SAML due to DP restart(server restart)
