### ISSUE TITLE
[Bug]: A delay in update of table rows in edit mode when the source is storeValue or mutableJS

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#25762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Discord Link](https://discord.com/channels/725602949748752515/1124321780425838653/1130756314243551273)

https://github.com/appsmithorg/appsmith/assets/1189106/a2393adb-8cf2-4b9f-bca5-b113d380c3b7

### Steps To Reproduce

Steps to repro are in the description

### Environment

Production

### Version

Cloud

**Comment by jacquesikot** [comment]
Not reproducible in prod
