### ISSUE TITLE
[Feature] Generate an app from a database Table

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2576]
## Summary

The feature could allow us to generate a template app for any db table. This would allow users to select multiple table's from their database and the app would generate a page for each table. The page would allow users to perform simple crud on the table i.e
- (C) Allow user to create a new row in the table
- (R) Search/filter the rows of the paginated table
- (U) Allow users to edit the rows of the table
- (D) Allow users to delete a row in the table

## Motivation

Most use cases are a variation of a simple CRUD over a database. This gives users a further relevant starting point instead of having to guess what their admin panel should do. This also acts as a great learning tool because users are most comfortable with their data and would be able to grok what the app is doing much faster. Since the app will be understandable as well, it will be easy to modify for users and will only require simple changes

**Comment by somangshu** [comment]
An existing example to this could be [Django Admin Panels](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/). This refers to the meta information of the DB models and create basic operations on the models really easy.
