### ISSUE TITLE
[Feature] Allow users to configure the max / min stretch width of an app

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2577]
## Summary

Today our canvas is at a fixed width and on different devices, this causes either a large white space or a horizontal scroll to appear. Allowing users to configure a range within which they would like the app to stretch would allow them to design the optimal experience for the devices they want to support.

## Motivation

A user had reached out with a use case of using appsmith on a tablet. They did not need a fully responsive UI but simply a way to design the UI so that it would fit correctly on the screen size they needed. This is a simple solution and can be the first step towards becoming fully responsive. The extension to this could be to allow users to specify breakpoints that will trigger reflow.

**Comment by areyabhishek** [comment]
I got one more request for this on Intercom over the weekend.

**Comment by Nikhil-Nandagopal** [comment]
Got one more request for this today. @riodeuno Can we start with a simple on/off switch that just stretches the width if on?

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal Yes we can get started on this. I agree with the solution of a toggle between fixed width and fluid width. We will get started with the design of the toggle.

**Comment by Debsourabh** [comment]
https://www.figma.com/file/41R0ELrx4SVDnZfijSNzvq/?node-id=110%3A0

Design

**Comment by riodeuno** [comment]
Note:
- Users will be able to switch between fluid or fixed width canvas.
- Fluid: The canvas takes up 90% of the available viewport width (after the entity explorer). This results in a "responsive" canvas width, hence, fluid
- Fixed: The canvas works as it does today.
- Fixed can be enhanced to add multiple values for the canvas width in pixels.

**Comment by marks0351** [comment]
Should we have this config be on an application level or Page level?

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 I was thinking at the app level. What do you think?

**Comment by marks0351** [comment]
was thinking the same, else it wud become very confusing as to why the app is behaving differently for different pages within the same app. wanted to confirm.

**Comment by areyabhishek** [comment]
We don't have page-level settings today. So today this setting can show up at the exact location like this, but it behaves as an application-level setting. 

We don't want to introduce this in the navbar because it is not relevant to APIs, DB queries, Data sources, and other places which share the navbar. Let's do this as the first version and then improve it once we have page-level settings.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek which icon is the final version?

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal @marks0351 @areyabhishek 
Updated product note:
- The solution is to define the "maxWidth" of the canvas.
- If the viewport does not facilitate the "maxWidth" of the canvas, the canvas will shrink to take up 90% of the available space
- If the viewport can facilitate the "maxWidth" and more, the canvas will be centered in the available space with its width = maxWidth
- There will be 4 options for the max width available to the users: Mobile, Tablet, Desktop, Always stretch to take 90% width
- The minimum width will be set to a minimum viable value like 500px (The canvas will not shrink below this value)
- This will be a property of the page. When the default max width is update, all pages will update their values to the set value.  Any new pages will be using this value by default.
- Designs for the UX to set this property - currently in design.

**Comment by Nikhil-Nandagopal** [comment]
Thanks @riodeuno This sounds great. Setting the maxWidth to Mobile on a desktop will show a small canvas?
