### ISSUE TITLE
[Bug]: On importing the app, the source data (with server-side data configured) is not getting evaluated

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On importing the app, the source data (with server-side data configured) is not getting evaluated

### Steps To Reproduce

https://www.loom.com/share/3372e61a30b64aa88fa80eb6dac6acf9

Link to APP
[Untitled application 6.json.zip](https://github.com/appsmithorg/appsmith/files/12183648/Untitled.application.6.json.zip)

### Environment
Release

### Version

Cloud/Release

**Comment by arunvjn** [comment]
Fixed along with https://github.com/appsmithorg/appsmith/pull/25799
