### ISSUE TITLE
[Bug]: Importing an old app with select widget bound to a JS variable throws an error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#25792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Evaluation of select widget binding fails when an old app is imported. Refreshing the app clears the error. 

### Steps To Reproduce

1. Import the attached app
2. Go to the select widget seen in the video and observe the evaluation of the binding fails on first load causing incorrect errors on the property pane but refreshing the page shows the correct values

[Automation test cases (1).zip](https://github.com/appsmithorg/appsmith/files/12183557/Automation.test.cases.1.zip)

### Environment

Production

### Issue video log

https://www.loom.com/share/b7880713c2e6485cb84df44c836c9545

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
@ramsaptami could you please confirm once if this is still reproducible?

**Comment by Rishabh-Rathod** [comment]
Closing this for now. @ramsaptami please re-open this if it is reproducible again.
