### ISSUE TITLE
[Task]: Fix firing logic for DEBUGGER_RESOLVED_ERROR

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#25794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The `DEBUGGER_RESOLVED_ERROR` sometimes gets fired even when an error is not resolved

Steps to reproduce: Try introducing a lint error on a JSObject and watch the event getting fired even without fixing the error

**Comment by bharath31** [comment]
@Rishabh-Rathod could you please investigate this?

**Comment by ohansFavour** [comment]
#### Observation

There are two categories of error resolution logs

1. DEBUGGER_RESOLVED_ERROR

2. DEBUGGER_RESOLVED_ERROR_MESSAGE

`DEBUGGER_RESOLVED_ERROR` - This is fired when a path's **error** is fixed (error in path is resolved)

`DEBUGGER_RESOLVED_ERROR_MESSAGE` -  This is fired when an **error message** is resolved (to depict that the error message no longer occurs). This still gets fired even if the error in the path hasn't been fixed, as long as the error message has changed.

For example

User types `{{ unknownVariable }}` in code editor  => Both `DEBUGGER_NEW_ERROR` and `DEBUGGER_NEW_ERROR_MESSAGE` are fired. To indicate that a new error has occurred, and a new error message has occurred respectively.

User edits value to  `{{ unknownVariable2 }}` => Both `DEBUGGER_NEW_ERROR_MESSAGE` and `DEBUGGER_RESOLVED_ERROR_MESSAGE` get fired. To indicate that a new error message has occurred (`unknownVariable2 does not exist`) and one error message has been resolved ("`unknownVariable does not exist`" has been resolved) respectively.

User edits value to `{{}}` =>  Both `DEBUGGER_RESOLVED_ERROR` and `DEBUGGER_RESOLVED_ERROR_MESSAGE` get fired. To indicate that error in the path has been fixed, and one error message has been resolved ("`unknownVariable2 does not exist`" has been resolved).




**Both of these work as expected.**
