### ISSUE TITLE
[Bug]: Git connected apps have datasources messages property populated 

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#25814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Git connected apps/ export jsons have datasouce messages populated when datasource storage has some messages.
The Ideal scenario is to have that property being empty

### Steps To Reproduce

1. Open a git connected app/ create an app and connect it to git , add some datasources
2. Create a datasource and set it endpoint to localhost 
3. add a query for the above mentioned datasource
4. commit changes

When the commit patch is checked the messages property in datasource is populated with hint message.

### Environment

Production

### Version

1.9.21+

**Comment by RakshaKShetty** [comment]
before fixing 
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/b13313db-1799-42b2-ba61-216d6ca2f3ba">
After fix
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/a887eb6d-a432-46e0-a0e5-942ac3f7ab83">
