### ISSUE TITLE
[Task]: Support feature flags with values

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#25815]
Right now we support only boolean values for the feature flag. That means we can set either true or false. Going forward we need to support non boolean values also here.

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by abhvsn** [comment]
We should start supporting multi-variate flags which should cover all types of AB testing scenarios.
https://docs.flagsmith.com/basic-features/managing-features#multi-variate-flags
