### ISSUE TITLE
[Task]: Fix ENTITY_BINDING_SUCCESS tracking

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#25810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

[Loom](https://www.loom.com/share/1ff7b0d40c094e2aaabc36cf602d0165?sid=9efe7e23-8b54-434d-b02c-0119412c75ad)

**Comment by Druthi** [comment]
Debugged this and was able to reproduce. However this is a very specific case and it is not easy to ensure the firing of success event only for the tableData property as it isn't easy to find the source of the evaluation.

Parking this for now. @bharath31 is exploring managing this in mixpanel for now.
