### ISSUE TITLE
[Bug]: Datasource Configuration screen not visible on firxfox 

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#25822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

Firefox Browser version - 115.0.2
1. Import an application - attached the sample file 
2. Skip the configure datasource modal and go to edit mode
3. Now go to the Edit datasource modal and observe that configure datasource in not visible

![image (1)](https://github.com/appsmithorg/appsmith/assets/12005551/f8fdeaf3-58eb-4424-abeb-f418ea1aae3a)

### Environment

Production

### Version

1.9.29

**Comment by AnaghHegde** [comment]
Unable to attach the json file. Please reach out to me, i will share the sample json file

**Comment by rohan-arthur** [comment]
@AnaghHegde I tried with a couple of apps that contained a mix of the following datasources: REST, postgres, gsheets. In all cases, I was able to see the datasources after skipping config. So I'm thinking maybe: 
- it got solved with some other PR
- there is something specific going on with your app 

In either case, I'll close this issue. Please reopen if you face problems again.
