### ISSUE TITLE
[Task]: Investigate the root cause of generic Promise.all error

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#25847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Original issue

https://github.com/appsmithorg/appsmith/issues/12352

**Comment by ohansFavour** [comment]
#### Root cause

When there is no `onError` handler supplied to `action.run`, and an error occurs while executing the action, responseData is not added to the `PluginTriggerFailureError` error object.

**Comment by GabrielMarques89** [comment]
Is there a way to fix this on older appsmith versions ?
