### ISSUE TITLE
[Task]: Add support for feature flags in Airgap

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#25874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Feature flag overrides should be allowed in air gap instances without having to reach out to Flagsmith.

**Comment by NilanshBansal** [comment]
For Airgapped instances, the local feature flagging system (FF4J) is supported. No calls are being made to CS to fetch the remote flags.
This PR ([#1820](https://github.com/appsmithorg/appsmith-ee/pull/1820/files)) enables the feature flagging for air-gapped instances. 

Also, you can go ahead integrating the same flag for FF4J and merge it to release. The remote flags from flagsmith will take priority over local flags if the flags have the same name, in case of non-airgapped instances.

**Comment by NilanshBansal** [comment]
No action required hence closing this ticket.
