### ISSUE TITLE
Container styles

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2587]
Containers should have more styles than the current rounded borders and shadow

**Comment by Debsourabh** [comment]
Here is the design for the same:

https://www.figma.com/file/DI69SVZlVvKXckU5mATFbN/?node-id=5%3A3376

**Comment by somangshu** [comment]
note:

- Outline colour / Border colour: Should have the colour picker
- Outline stoke / Border width: The width of border used
- Corner radius / Border radius: The radius/curve on each corner of the container
- Fill Colour / Background colour: Should have the colour picker


Please use the developer savvy terminologies here/.

**Comment by vibhandikyash** [comment]
Discussed with @marks0351. Planning to build a wrapper div that can handle this kind of styling.
cc: @somangshu

**Comment by somangshu** [comment]
Additionally we want to implement box-shadow in the following manner. Please use the same control implemented before

![Screenshot 2021-08-04 at 6 36 13 PM](https://user-images.githubusercontent.com/11089579/128185875-93b7f346-edf9-4b63-a028-2db15700588e.png)

**Comment by segfall** [comment]
Looking forward to this being addressed. The current white background on gray is rather unsightly compared to how [appsmith looked previously](https://user-images.githubusercontent.com/30255708/102681529-1118fb00-41e8-11eb-865c-22bd7c32147c.png)
