### ISSUE TITLE
[Feature]: Allow plugin specific logical implementation on client side

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#25884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Make sure that the client can support features not just on the basis of config, but in code.

### Why should this be worked on?

Allows us to start supporting feature hierarchies on the client side as well.

**Comment by rohan-arthur** [comment]
issue unclear; if this is still needed, please reopen with more detailed description including the problem statement and the solution.
