### ISSUE TITLE
[Feature] Align widgets on the canvas

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2588]
Allow users to align items within a canvas.

**Comment by momcilo-appsmith** [comment]
![Screenshot 2021-08-30 at 08 38 04](https://user-images.githubusercontent.com/81744497/131296068-426d29ea-1e04-4436-97da-e5db185a407d.png)
Adding a screenshot here from Figma.
@riodeuno Is this what you mean?

**Comment by riodeuno** [comment]
@momcilo-appsmith Yes. We need to look into how vertical alignments would work, as we need to consider the fact that canvas (container, main container, form, tabs) can have infinite height, as they can be made to scroll contents.
