### ISSUE TITLE
[Bug]: Audit log issues related to SCIM

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#25885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [ ] #26311
- [ ] #26312
- [x] #25972
- [x] #26094 / #25989
- [x] When we add a user to an existing group the remove user Log is being triggered->Not able to repro
- [x] The provisioningUser username should be replaced with "Provisioning User"

### Steps To Reproduce

 Following are the logs that needs to captured as a part of the SCIM feature
- [ ] User Created[When the provisioned user is synced to Appsmith] ->Doesnt get captured
- [ ] User Deleted[When the provisioned user is  deleted from idp synced to Appsmith]->Captured
- [ ] Assigned to group[When the user is assigned to group in IDP is synced to Appsmith]->Not captured
- [ ] Unassigned to Group[When the assigned user to group is removed from IDP is synced to Appsmith]->captured
- [ ] Group Created [when the group is created and pushed to appsmith]->Captured
- [ ] Group Deleted[When the group is deleted from IDP and synced with appsmith]->captured
- [ ] When the Group name is updated in the IDP the Logs are Added->Captured
- [ ] There is no Event when the existing user is sync to provisioning->ISSUE
- [ ] When user edit the user display name the User removed log is being triggered->ISSUE
- [ ] When we add a user to an existing group the remove user Log is being triggered->ISSUE
- [ ] The provisioningUser username should be replaced with "Provisioning User"->ISSUE

### Environment

Release

### Version

v.1.9.30

**Comment by RakshaKShetty** [comment]
@infinitetrooper , @nsarupr the list of cases covered here let me know if i have missed anything here

**Comment by nsarupr** [comment]
> There is no log when a user (not existing in Appsmith) is provisioned by assigning user to IdP Application. (Present in both Okta and AD)

In current implementation, there is no such log when the user is created. Logs only exists for `User Logging In`, `User Signing Up`, `User being associated with a Role` or `User being invited to a Group`.

**Comment by nsarupr** [comment]
> There is no log when a user (existing in Appsmith) is provisioned by assigning user to IdP Application. (Present in both Okta and AD)

We currently have no event when an existing user is provisioned.

**Comment by nsarupr** [comment]
> When a user's name is updated in Okta, a `User Removed from Group` audit log is triggered for all the groups, the user is not part of.

This is currently being fixed. It will not trigger the `Remove user from group` audit log for groups the user is not already a part of.

**Comment by nsarupr** [comment]
> When a user's name is updated, there is no Audit Log event for the same. (Present in both Okta and AD)

Currently there is no support for Audit log for updating the user's name.

**Comment by nsarupr** [comment]
> The provisioningUser username should be replaced with "Provisioning User"

Name of this user will need to change through a migration.

**Comment by nsarupr** [comment]
> When a user is assigned to a Provisioned Group, `Update Group` Audit log is being triggered multiple times. (4 times to be exact).
