### ISSUE TITLE
[Bug] Jarvis : header get overlapped on the description/ Modal widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2591]
Steps to reproduce:
1) Navigate to Jarvis App 
2) Navigate to GitHub Projects
3) Select any issue with POD
4) Select on any issue in To Do list 
and observe the pop up 

Observation:
It is observed that Header gets overlapped on the modal widget

**Comment by trishaanand** [comment]
@prapullac : Is this not being seen on app.appsmith.com?

**Comment by Nikhil-Nandagopal** [comment]
@prapullac this seems to be working so closing this
