### ISSUE TITLE
[Bug] Cyclical dependency in the action config

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2593]
## Description
Saw cyclical dependency error with the node being in the action config. 

### Steps to reproduce the behaviour:
> TODO

### Important Details
 - Version: Prod
 - Plugin: Firebase

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu please add the impact / effort and get these cyclic issues closed

**Comment by hetunandu** [comment]
Fixed with #3259
