### ISSUE TITLE
[Bug] Text gets hidden behind the lightning menu

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2594]
## Description
When you write in an input with the lightning menu, text gets hidden behind it.

[What happened]

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12022471/104798609-508a3580-57ee-11eb-90a5-9a7d16dda601.gif)

**Comment by areyabhishek** [comment]
@aakashDesign This seems to be a flaw in the design. Is there an easy solution here?

**Comment by riodeuno** [comment]
Closing as this is fixed in `release`.
