### ISSUE TITLE
[Bug]: List Widget onItemClick actions fails to execute when we click on empty space inside the List Item container

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

List Widget onItemClick actions fails to execute when we click on empty space inside the List Item container

### Steps To Reproduce

https://www.loom.com/share/110d875cdff44e75b7068c51e908aca9

### Environment

Release

### Version

Cloud/Release

**Comment by AmanAgarwal041** [comment]
[RCA-for-List-Widget-onItemClick-actions-fails](https://www.notion.so/appsmith/RCA-for-List-Widget-onItemClick-actions-fails-9f0b9052f8144fd1b5640eaf01f36f82)
