### ISSUE TITLE
[Bug]: In preview mode with SIDE NAV enabled, we get to see the bottom of the content (in the side bar) cut off

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#25949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In preview mode with SIDE NAV enabled, we get to see the bottom of the content (in the side bar) cut off.

This might be because we tend to disappear the footer in preview mode but with ME , since we show the env dropdown, the contents are overflowing(Though not completely sure)

### Steps To Reproduce

<img width="1082" alt="Screenshot 2023-08-02 at 6 29 39 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/30266a81-844e-4be0-8ab4-b578d5c8c406">

You can switch to SIDE NAV thru , app settings-->Navigation-->side

**_### Please re-assign to the correct team if not relevant to ME team_**

### Environment

Production

### Version

Cloud/Prod

**Comment by dhruvikn** [comment]
@kamakshibhat-appsmith - nothing has changed in app navigation recently. Will triage the issue this week.
