### ISSUE TITLE
[Bug]: Schema search is not working for MySQL

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#25945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to MySQL and tries to search for the scheme it is observed that it is not functional

### Steps To Reproduce

1) Establish connection to Mysql Datasource
2) Click on "Add Query"
3) Click on the Search field of the schema
4) Add keywords
and observe

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
@prapullc as discussed in the stand up, kindly verify this bug again since we shipped a related fix recently

**Comment by prapullc** [comment]
Sorry for the delayed reply 
Attaching the video for the same 
https://nwshheskua.vmaker.com/record/DIozsfWs1VYHnHdD

**Comment by Irongade** [comment]
I can't reproduce this issue. Loom video can be found [here](https://www.loom.com/share/8a3c428beac0423c9b695eb2417f78e5).

cc: @prapullc @rohan-arthur

**Comment by prapullc** [comment]
This issue seems to be working on the release and hence closing the issue
