### ISSUE TITLE
[Task]: Add property to Instance_stats

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#25950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Add a property `numAnonymousUsers` to the event instance_stats, which will allow us to better track the number of users who are using appsmith apps on self-hosted instances.

**Comment by rohan-arthur** [comment]
from standup: 
- need to track this continuously so this needs to be an event
- this should be a backend event

**Comment by rohan-arthur** [comment]
closing with ref to #27184
