### ISSUE TITLE
[Bug]: Command type for a query changes on navigating between queries

### ISSUE THREAD

**Issue by tkAppsmith** [appsmithorg/appsmith#25982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Command type for a query changes when navigating away from it and then navigating back from it.

### Steps To Reproduce

Use the public app with support account. Go to edit mode. Navigate to uploadImages s3 query and then got to mongo InsertQuery. Then navigate to formatedData's insert method by clicking insert of {{formatedData.insert()}}. Then navigate to  by image js object by clicking "let images = await image.upload();"' upload method. Then navigate to s3 query by clicking on "let res = await uploadImages.run()"'s uploadImages keyword. The command type of s3 query wouldve been changed to "LIST" from "UPLOAD_MULTIPLE_FILES_FROM_BODY".
OR
Do some random navigations between queries and it should repro as well.

https://app.appsmith.com/app/allyworkspaces/workspaces-63e254236b8ca42af5ad8a06?branch=master

### Public Sample App

https://app.appsmith.com/app/allyworkspaces/workspaces-63e254236b8ca42af5ad8a06?branch=master

### Environment

Production

### Version

Cloud

**Comment by tkAppsmith** [comment]
https://github.com/appsmithorg/appsmith/assets/131347120/f8602fda-43f5-42a7-ae68-db21643c5d10

**Comment by sumitsum** [comment]
Related issues: 
https://github.com/appsmithorg/appsmith/issues/21396 
https://github.com/appsmithorg/appsmith/issues/16077
