### ISSUE TITLE
[Bug] Data field in the chart widget shows an error by default only for the latest data series

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2599]
1. Drag and drop a chart widget.
2. Add a new series of data
3. See that the first field is in error state, but the second field is not in an error state.
Loom video: https://www.loom.com/share/4e8e8cd6a7424a319008abf779b71221

**Comment by hetunandu** [comment]
We should also update the default value being set for these series. 
```
[{ x: "label", y: 50 }]
```
This will not cause errors for a user in the default text
