### ISSUE TITLE
[Feature]: [Experiment] Adaptive/guided onboarding for users

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#26003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We want to create a version of signposting which is guided. This will allow users to see more detailed instructions and a GIF to describe what they need to do next.

We will run this as an experiment with some users, gather feedback, and based on that, continue to iterate and improve it till we are confident this will help users get to success.

### Why should this be worked on?

We have noticed that many users notice the first step of onboarding/signposting, but most don't open this after. We want to test if this is a visibility/information problem.

We will be running this as a user test behind a feature flag

https://www.notion.so/appsmith/Improve-the-discoverability-of-this-after-the-first-step-experiment-66f38e77d64548f8a838b7ead4931feb

**Comment by kavitasmoolya** [comment]
Verified on release version Appsmith v1.9.37-SNAPSHOT 
Looks good to me
