### ISSUE TITLE
[Feature] Show examples of JS code which are accepted by widgets' data fields

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2600]
## Summary
1. Users struggle to understand what JS to write in data fields of widgets. They could be helped by examples.
2. Improve the transformation error message and the contrast, it's not human-readable
3. Make the lightning menu smart otherwise it just gives the wrong direction to people. If the field requires a string just do a JSON.stringify if it needs an array search for the array in an object, if it needs an array with a specific object type, generate a map function.
4. Show focus to the data type mismatch in a human-readable way

Example of a user struggling: https://app.smartlook.com/org/9b6c5c859e85745d01196fa4/project/e373e3a21d27278fd281d8b0/recordings/filter/f5f581a901cd027401d363f5a20a013aec0fcf1736fae531b98743cfbdcc3397?playSession=6fTdORv8wT4&playVisitor=e72BMfCgFkU

**Comment by Nikhil-Nandagopal** [comment]
Related to #4737
