### ISSUE TITLE
[Enhancement]: Allow users to jump to the source of lint errors 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#26013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I encounter a lint error, I'm unable to jump to the source of the error from the debugger console.

![image](https://github.com/appsmithorg/appsmith/assets/17562726/c3b9969f-d229-4091-8515-a4cf29e5ef0f)

### Steps To Reproduce

1. Introduce a lint error on a JSObject function
2. Notice the error on the debugger 
3. Try navigating to the line of function from the error message

### Environment

Production

### Version

Cloud

**Comment by akash-codemonk** [comment]
This is fixed here in this DP. https://ce-25775.dp.appsmith.com/.

**Comment by Druthi** [comment]
This seems to be fixed. Working fine on prod. @satbir121 @bharath31
