### ISSUE TITLE
[Feature] Show an error state for all widgets with the property pane closed

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2601]
## Summary
Today if a widget is in an error state, then it's only visible if the property pane is open. We should indicate the widget is in an error state in the editing mode to the developer.

Cases when this applies:
1. When the JS written in the data field isn't evaluated correctly
2. When a widget is in a circular dependency error

Potential solutions:
1. Show the error state [!] beside the widget name with a red border
2. Show an error state in the entity explorer
<img width="349" alt="Screen Shot 2021-01-18 at 12 12 49 AM" src="https://user-images.githubusercontent.com/30255708/104852597-ea063400-5921-11eb-88cb-1b73e4afd7b1.png">

**Comment by Debsourabh** [comment]
Designs for the same

https://www.figma.com/file/DI69SVZlVvKXckU5mATFbN/?node-id=477%3A2

**Comment by akash-codemonk** [comment]
Closed with #4558
