### ISSUE TITLE
[Feature]-[2000]:Tab based navigation for all open Entities

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2602]
## Summary

Allow users to see all entities as tabs. This is similar to how VScode works and developers as used to seeing all their files as tabs. This would solve some of the navigation issues that users face today.

Things we could show in tabs:
1. Canvas
2. APIs
3. Queries
4. Documentation help

## Motivation
Being able to access your APIs, canvas

Two ways of creating tabs:
1. Show all tabs on a single Appsmith page
2. Use the browser's tabs to show each page, query, or API in a different browser tab. Users could differentiate between tabs by seeing the favicons.

**Comment by GreenFlux** [comment]
I was just going to suggest this feature. Now that we have the JS Objects, I'm often bouncing back and forth between a widget and a JS Object. 

It takes a few extra clicks and scrolling to find the JS Object again when you have a long list of APIs/Datasources. It would be a lot easier if the JS Object pane could just stay open as a tab.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 1 |

**Comment by rohan-arthur** [comment]
won't fix - project cancelled

**Comment by kocharrahul7** [comment]
This has now been done in the new IDE 2.0
