### ISSUE TITLE
[Feature]: Support Aurora MySQL Instead of MongoDB/PostgreSQL for HA

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#26059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Users should be offered the possibility to use Aurora MySQL instead of MongoDB/PostgreSQL for [High Availability and Scalability](https://docs.appsmith.com/getting-started/setup/installation-guides/kubernetes/configure-high-availability#docusaurus_skipToContent_fallback). 

[Slack thread](https://theappsmith.slack.com/archives/C05JS629SC8/p1690987664616039)

### Why should this be worked on?

This enhances the user experience by giving them more options for setting up high availability and scalability. For example, some companies are restricted to using only some kind of databases (e.g., MySQL).

**Comment by Nikhil-Nandagopal** [comment]
We won't be supporting this as we will only support postgres #17304
