### ISSUE TITLE
[Bug]: Handle the scenario when the last state of the page is not a selected widget(DS page ,queries etc) and user moves to preview mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#26075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Handle the scenario when the last state of the page is not a selected widget(DS page ,queries etc) and user moves to preview mode

### Steps To Reproduce

https://www.loom.com/share/be9014ea18864fb6bbf75b23739821d2

### Environment

Production

### Version

Cloud/Self hosted

**Comment by rohan-arthur** [comment]
Uploading Screen Recording 2024-06-11 at 12.14.15.mov…

not reproducible anymore

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/9fc6be17-88bb-4c66-af15-5d9cf0cad2e1
