### ISSUE TITLE
[Bug]: Fund Raising CMR Template is broken

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#26071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to Templates from the home page and selects the "Fund Riser" template it is observed that the page gets generated but the data does. not get populated 

### Steps To Reproduce

1) Navigate to home page
2) Click on templates
3) Select the "Fund Raising CMR" template
4) observe the page gets generated 
5) Navigate to DS review page and observe it is Authorised 
the data does not get populated on the table 

https://nwshheskua.vmaker.com/record/98hkIjYNlEz0UJfC

### Environment

Release

### Version

Cloud

**Comment by jacquesikot** [comment]
I have set up dummy data within the template and set it up to work with dummy data when the users has not authenticated the google sheet datasource. Once they authenticate, the queries will work and dummy data will no longer be used.
