### ISSUE TITLE
Create Documentation for Popover component

### ISSUE THREAD

**Issue by vasanthappsmith** [appsmithorg/appsmith#26070]
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/26285
```

**Comment by vasanthappsmith** [comment]
@tanvibhakta Completed the documentation. Can you review the same? 
https://www.notion.so/appsmith/Popover-Documentation-11017cc81fde45bd847f897d86af6e2b?pvs=4

**Comment by rohitagarwal88** [comment]
@tanvibhakta has to create document on storybook

**Comment by tanvibhakta** [comment]
Documentation on usage of size variants of popover has to be created by @vasanthappsmith

**Comment by vasanthappsmith** [comment]
Size variants and Scroll should be added as well I believe?
