### ISSUE TITLE
[Bug]: Business Edition Helm Chart cannot enable high availability

### ISSUE THREAD

**Issue by rhuanbarreto** [appsmithorg/appsmith#26080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Due to the removal of the v2beta1 version of HPA (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125), if you add `autoscaling.enable = true` in the Helm Release, you get the following error:

```
no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
```

### Steps To Reproduce

1. Use a k8s cluster with version >= 1.25. In my case I'm on AKS with v1.25.11
2. Try to deploy the Business Edition Helm Chart v3.0.4
3. You get an error

### Environment

Production

### Version

Self Hosted Business Helm Chart Version 3.0.4

**Comment by sum35h** [comment]
Reff: https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy-removal-faq.html

**Comment by pratapaprasanna** [comment]
@rhuanbarreto  we shall cover pdb  in a different feature and we have created an issue for the same [here](https://github.com/appsmithorg/appsmith/issues/27185)

**Comment by rhuanbarreto** [comment]
Any updates on when this fix will come?

**Comment by pratapaprasanna** [comment]
> Any updates on when this fix will come?

You can pull the latest helm charts and you can use the helm charts.
Thankyou

**Comment by rhuanbarreto** [comment]
I pulled. But still having issues for having a PVC with ReadWriteMany to be used. I'm on Azure, so I cannot use EFS.
