### ISSUE TITLE
[Bug]: Calling a validate function on an input doesn't allow setting a custom validate message

### ISSUE THREAD

**Issue by glennslaven** [appsmithorg/appsmith#26101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a `validate` function on a JS object that I set as the Valid property for an input widget.  I also have a `msg` attribute on that JS object to put the validation message in when the validation fails.

The function is called when the input widget's content changes, but it never updates the `msg` attribute.

### Steps To Reproduce

1. Create an input widget
2. Create a validate function that populates a message field.
3. Fail the validation
4. See that the message field is not populated and you just get the default validation message.

### Environment

Production

### Issue video log

https://www.loom.com/share/5c4255e8b6b045ac9cfb8a21cdf0501e?sid=72364450-5ccb-4789-8bfe-649ae34bd709

### Version

Appsmith Business v1.9.31

**Comment by Nikhil-Nandagopal** [comment]
This was incorrect assignment. You have to bind the message field to the value
