### ISSUE TITLE
chore: revert tag but release special and premium tags

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#26102]
The update of the default kind of tag from `neutral` to `info` has resulted in the eye being unnecessarily drawn to them throughout the platform.
Slack: https://theappsmith.slack.com/archives/C0293DVQACW/p1691145475834899

To unblock team-managers, we are going to revert the previous changes, but release only the special and premium tags.

**Comment by tanvibhakta** [comment]
Needs testing 
- special tag to follow design 
- premium tag to follow design 
- regular (neutral) tag to follow tag that is currently in production (no design, please use app.appsmith.com to compare)

**Comment by Sripriya93** [comment]
QA done. Colors of special & premium tags are as expected. CC: @tanvibhakta
