### ISSUE TITLE
Task : Develop toggle button size variant

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#26111]

**Comment by rohitagarwal88** [comment]
@vasanthappsmith to link zeplin

**Comment by vasanthappsmith** [comment]
@albinAppsmith Part of this can we also consider #24105 as the JS button is too small

**Comment by vasanthappsmith** [comment]
@albinAppsmith https://zpl.io/09dPQkQ Zeplin link

**Comment by albinAppsmith** [comment]
> #24105

Are you saying that we need to increase the JS icon size more? If yes the what are the sizes?

**Comment by albinAppsmith** [comment]
> @albinAppsmith Part of this can we also consider #24105 as the JS button is too small

@vasanthappsmith  Are you saying that we need to increase the JS icon size more? If yes the what are the sizes?
