### ISSUE TITLE
[Bug]: IT asset tracker template does not load template details in iframe

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#26110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attached screen shot : 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/c729dc31-5f88-4f7f-825a-0bb1af02cccf)

**expected result** : It should show details of template.

**Note** : Clicking on "click here to retry" loads the template details can be alternative for now.

### Steps To Reproduce

1. Go to template section 
2. Select IT Asset Tracker template https://app.appsmith.com/templates/62db0d0de8e73110ce25390e
3. Observe "Oops, Something went wrong.Click here to retry" error on description page

### Environment

Production

### Version

Appsmith v1.9.32-SNAPSHOT

**Comment by rahulbarwal** [comment]
This is fixed now. Please reopen if you face something like this again.
