### ISSUE TITLE
Task: Replace old grey/orange with new grey/orange in batch control

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#26112]
![Screenshot 2023-08-08 at 11.36.36 AM.png](https://images.zenhubusercontent.com/620dea39dbc0b448e733d8e0/0552b609-52a4-40ca-9dca-0bc4bf08bcb2)

**Comment by vasanthappsmith** [comment]
@rohitagarwal88 

Canvas | #F8FAFC
Container | #E3E8EF
Border | #CDD5DF
Use Icon Button for the icons. |  

![image](https://github.com/appsmithorg/appsmith/assets/92305123/98dcc491-af40-4172-9c21-7258e1f5357f)

![image](https://github.com/appsmithorg/appsmith/assets/92305123/25b10783-7ffd-46b6-bdef-c5f5da64fa0e)

Note: For now let's not update the orange. We will update once we get the new colour palette ready,

**Comment by rohitagarwal88** [comment]
@vasanthappsmith: We cannot change the canvas colour because it impacts app building experience. we should update the orange colour with our new ADS colours. 
When we are updating the colour palette, the new color palette changes will reflect

**Comment by vasanthappsmith** [comment]
![image](https://github.com/appsmithorg/appsmith/assets/92305123/bc7d93c2-ebe7-438a-afb1-8de11faca9c1)

**Comment by vasanthappsmith** [comment]
@rohitagarwal88 Is this closed?
