### ISSUE TITLE
[Task]: Showing progress bar with progress percentage

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#26123]
Can we provide a commit progress bar with percentage progress? If we do that, we can also do rid of the client timeout. At the moment, it's quite challenging for a user to figure out what's going on in the background, and for complex apps, the commit api times out on the client.
 
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/8299030/b2509c34-4f8d-4d8a-bc2c-c4a4ab7a5fbd">

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by infinitetrooper** [comment]
Not possible with Git commit
