### ISSUE TITLE
[Bug]: Authentication failed error is seen for Gsheets on the reconnect modal while importing an app

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#26170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Authentication failed error is seen for Gsheets on the reconnect modal while importing an app, the first time we try to authorize the Gsheet. On retry, it works fine. Attaching the video for steps to reproduce this:

https://cjrc9tc9nt.vmaker.com/record/aATdkdgtL282oA0H

### Steps To Reproduce

Follow the steps as shown in the video. This is happening on CE and EE release fat containers.

### Environment

Release

### Version

Self Hosted - release

**Comment by ankitakinger** [comment]
Backend logs and app used for importing (update it to `.json`, as it is not supported here adding `.txt` file instead)

[backend-a021335a852b.log](https://github.com/appsmithorg/appsmith/files/12292328/backend-a021335a852b.log)
[Gsheettesting.txt](https://github.com/appsmithorg/appsmith/files/12292342/Gsheettesting.txt)

**Comment by rohan-arthur** [comment]
this should be fixed with #28952
