### ISSUE TITLE
[Bug]: With uncommitted changes, once a new branch is created, the parent branch should no longer have changes.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#26232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently when we have uncommitted changes on master and then create a branch from it, child branch as well as master branch both have those uncomitted changes, ideally master should no longer have changes once child branch is created.

### Steps To Reproduce

1. Add a widget on master
2. Create new branch from master
3. Verify widget exist on master as well 

### Environment

Production

### Version

Production

**Comment by riteshkew** [comment]
resolved as part of auto-commit, not reproducible now/
