### ISSUE TITLE
[Task]: Comparative study of callout vs Banner

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#26279]

**Comment by vasanthappsmith** [comment]
[Notion Link ](https://www.notion.so/appsmith/Banner-vs-Callout-88189395fc6b4dbfaf35dd58e5930873?pvs=4)

**Comment by vasanthappsmith** [comment]
Slack thread 
https://theappsmith.slack.com/archives/C0293DVQACW/p1692270000282189

**Comment by vasanthappsmith** [comment]
We have decided to make it a separate component and call it "**Banner**

Slack thread. 
https://theappsmith.slack.com/archives/C0293DVQACW/p1692270000282189
