### ISSUE TITLE
[Bug]: Omnibar search design

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#26294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The text `Press ↵ to navigate to <>` in the omnibar search area is misaligned 

https://github.com/appsmithorg/appsmith/assets/20532920/fff1102d-20b8-4ebf-a731-c4ffe856df80

### Steps To Reproduce

Open an app in edit mode
Click on the omnibar
Start to search for an item
Look at the results area

### Environment

Production

### Version

Appsmith v1.9.32-SNAPSHOT

**Comment by kavitasmoolya** [comment]
@akash-codemonk I still see misalignment
![image](https://github.com/appsmithorg/appsmith/assets/134914630/2759c976-c5d3-49c8-813a-f52e5afcd815)

**Comment by akash-codemonk** [comment]
Release may not be updated. Please check after some time.

**Comment by kavitasmoolya** [comment]
> @akash-codemonk I still see misalignment ![image](https://user-images.githubusercontent.com/134914630/264256116-2759c976-c5d3-49c8-813a-f52e5afcd815.png)

Verified on release (Appsmith v1.9.37-SNAPSHOT) and looks good to me 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/8fb0a0d4-9ad4-4edb-83fa-1092b13c557e)
