### ISSUE TITLE
[Bug]: MongoDB data source is suddenly VERY slow and it takes 5-10 minutes for a basic query.

### ISSUE THREAD

**Issue by tkeidar** [appsmithorg/appsmith#26303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

All the pages with MongoDB integrations are now very slow, and it takes 5-10 minutes for page to load, the exact same page was loading in no time up until a week ago.
The data source also doesn't load the mongo collections and it shows the following error:
"Appsmith has failed to get database structure. Please provide read permission on the database to fix this." although there are permissions.

The message I see when displaying the collections:
![image](https://github.com/appsmithorg/appsmith/assets/44050297/d8680830-48c4-480b-84b3-f8648ea1601c)

The page is loading for 5-10 minutes until it displays the content:
![image](https://github.com/appsmithorg/appsmith/assets/44050297/78c4213b-211d-40b4-854e-d5d6198e0c76)

Some errors I see on the devtools, not sure it's related:
![image](https://github.com/appsmithorg/appsmith/assets/44050297/d752ac59-6f37-4224-88d0-3829650d0014)

![image](https://github.com/appsmithorg/appsmith/assets/44050297/45bf43f3-95c0-434d-8208-7ea1df878c5e)

![image](https://github.com/appsmithorg/appsmith/assets/44050297/62435803-dc7c-4ca3-be26-275004ed6cc1)

### Steps To Reproduce

It happens on every page with MongoDB queries

### Environment

Production

### Version

Appsmith v1.9.32-SNAPSHOT Released 2 days ago

**Comment by GreenFlux** [comment]
cc @rohan-arthur 
https://discord.com/channels/725602949748752515/725609493974614076/threads/1140244131436830770

**Comment by tkeidar** [comment]
UPDATE:
I tried creating another new empty app, I added the MongoDB data source using both a connection string and a user and password, it accepts the parameters and the data source is being created successfully, however it can't fetch the list of collections with the same message:
![image](https://github.com/appsmithorg/appsmith/assets/44050297/f249058c-b0d9-4006-9c0a-80ba020df5f7)

Then I created a query and the query is being executed successfully:
![image](https://github.com/appsmithorg/appsmith/assets/44050297/504c89ad-dea1-42bc-b7f9-f0e6b6148e78)

I added a blank page to display the query results and it works fine.

**Comment by sergei-sofokus** [comment]
The same issue with Firestore, I waited a lot of minutes to get a result from aquery. In console, I can see:

**main.0b199ed7.js:2 WebSocket connection to 'wss://app.appsmith.com/rts/?EIO=4&transport=websocket' failed:**

**Comment by tkeidar** [comment]
not sure if it's related, here are some other errors I see on the console when editing a page:

![image](https://github.com/appsmithorg/appsmith/assets/44050297/552d5563-7d2a-402a-84fe-3d2cc49515ca)

**Comment by tkeidar** [comment]
When I open the query page (every query) on edit mode, it shows an unending loader and if I try to execute the query it does return the results:
![image](https://github.com/appsmithorg/appsmith/assets/44050297/1c0df397-8943-4f1c-bca4-55f9a863ab45)

**Comment by sumitsum** [comment]
Hi @tkeidar are you working on `app.appsmith` or is your instance self hosted ?

**Comment by sumitsum** [comment]
> @GreenFlux @rohan-arthur @Nikhil-Nandagopal @pranavkanade UPDATE: I tried creating another new empty app, I added the MongoDB data source using both a connection string and a user and password, it accepts the parameters and the data source is being created successfully, however it can't fetch the list of collections with the same message: ![image](https://user-images.githubusercontent.com/44050297/260386747-f249058c-b0d9-4006-9c0a-80ba020df5f7.png)
> 
> Then I created a query and the query is being executed successfully: ![image](https://user-images.githubusercontent.com/44050297/260384214-504c89ad-dea1-42bc-b7f9-f0e6b6148e78.png)
> 
> I added a blank page to display the query results and it works fine. I hope it will help you resolving this issue, because we can't use our app for more than a week now and it's crucial for us.

@tkeidar was the app able to fetch the list of collections earlier for the same Mongo datasource ?

**Comment by tkeidar** [comment]
@sumitsum `app.appsmith`

**Comment by tkeidar** [comment]
> > @GreenFlux @rohan-arthur @Nikhil-Nandagopal @pranavkanade UPDATE: I tried creating another new empty app, I added the MongoDB data source using both a connection string and a user and password, it accepts the parameters and the data source is being created successfully, however it can't fetch the list of collections with the same message: ![image](https://user-images.githubusercontent.com/44050297/260386747-f249058c-b0d9-4006-9c0a-80ba020df5f7.png)
> > Then I created a query and the query is being executed successfully: ![image](https://user-images.githubusercontent.com/44050297/260384214-504c89ad-dea1-42bc-b7f9-f0e6b6148e78.png)
> > I added a blank page to display the query results and it works fine. I hope it will help you resolving this issue, because we can't use our app for more than a week now and it's crucial for us.
> 
> @tkeidar was the app able to fetch the list of collections earlier for the same Mongo datasource ?

To be honest I'm not sure.

**Comment by sumitsum** [comment]
> @sumitsum `app.appsmith`

@tkeidar thanks for sharing the info. If possible, would you be able to invite`support@appsmith.com` to your app ?

**Comment by tkeidar** [comment]
> > @sumitsum `app.appsmith`
> 
> @tkeidar thanks for sharing the info. If possible, would you be able to invite `support@appsmith.com` to your app ?

Unfortunately I can't, due to security concerns. We can jump on a call and I'll share my screen.
wdyt?

**Comment by sumitsum** [comment]
@tkeidar thanks. Is it ok if I share a zoom call link ? Can you please share your time zone so that I can schedule the call accordingly ?

**Comment by tkeidar** [comment]
> @tkeidar thanks. Is it ok if I share a zoom call link ? Can you please share your time zone so that I can schedule the call accordingly ?

Sure, my timezone GMT+3
this issue is urgent for us so if possible, let's do it now.
TNX

**Comment by sumitsum** [comment]
> > @tkeidar thanks. Is it ok if I share a zoom call link ? Can you please share your time zone so that I can schedule the call accordingly ?
> 
> @sumitsum Sure, my timezone GMT+3 this issue is urgent for us so if possible, let's do it now. TNX

@tkeidar thanks, is IST 5 pm ok for you ? i.e. around 2 hours from now ?

**Comment by tkeidar** [comment]
> > > @tkeidar thanks. Is it ok if I share a zoom call link ? Can you please share your time zone so that I can schedule the call accordingly ?
> > 
> > 
> > @sumitsum Sure, my timezone GMT+3 this issue is urgent for us so if possible, let's do it now. TNX
> 
> @tkeidar thanks, is IST 5 pm ok for you ? i.e. around 2 hours from now ?

Yes, perfect

**Comment by sumitsum** [comment]
@tkeidar thanks, I will share the zoom link 5 min before the scheduled time. See you then.

**Comment by sumitsum** [comment]
@tkeidar please join this link: https://us02web.zoom.us/j/88025213645?pwd=WkpqaGRJb3BGN1ZYMWRqa0l6djZCdz09

**Comment by tkeidar** [comment]
> @tkeidar please join this link: https://us02web.zoom.us/j/88025213645?pwd=WkpqaGRJb3BGN1ZYMWRqa0l6djZCdz09

sorry, I don't know why but it doesn't work.
can we try with google meet? https://meet.google.com/nmj-orcr-okq

**Comment by rohan-arthur** [comment]
we have shipped a fix for this and communicated over email as well. Kindly reopen if the issue persists.

**Comment by SplendidFarzad** [comment]
> @GreenFlux @rohan-arthur @Nikhil-Nandagopal @pranavkanade UPDATE: I tried creating another new empty app, I added the MongoDB data source using both a connection string and a user and password, it accepts the parameters and the data source is being created successfully, however it can't fetch the list of collections with the same message: ![image](https://private-user-images.githubusercontent.com/44050297/260386747-f249058c-b0d9-4006-9c0a-80ba020df5f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODc3MjYsIm5iZiI6MTcxNjI4NzQyNiwicGF0aCI6Ii80NDA1MDI5Ny8yNjAzODY3NDctZjI0OTA1OGMtYjBkOS00MDA2LTljMGEtODBiYTAyMGRmNWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZWI0YzNmZmIxZTNmZDc0NWFiZjgxNzhkYzdhNjk1YmQxM2M3MmU0MjI1MDE1NjgwNTcxN2M5ZGFhYzM1MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dNbxdyBIk8xdGwSYE6-gXuFPz7TpaMHeB6WEanxrVY)
> 
> Then I created a query and the query is being executed successfully: ![image](https://private-user-images.githubusercontent.com/44050297/260384214-504c89ad-dea1-42bc-b7f9-f0e6b6148e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODc3MjYsIm5iZiI6MTcxNjI4NzQyNiwicGF0aCI6Ii80NDA1MDI5Ny8yNjAzODQyMTQtNTA0Yzg5YWQtZGVhMS00MmJjLWI3ZjktZjBlNmI2MTQ4ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNTEwZTdjZjI1ZThiMWIzM2UyM2Y4NWU5NGY2OTg3YjY2YTc3ZGJmNTk5ZTRiZjg4NzNiZTYzZjNkNTZiOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SSA5qL8JpJ1DV2vPmt7kDTup6bSdE0ef6LM84jwblEs)
> 
> I added a blank page to display the query results and it works fine. I hope it will help you resolving this issue, because we can't use our app for more than a week now and it's crucial for us.

I am experiencing this exact issue on the latest version of AppSmith. We have self-hopsted the instance on docker. We are giving it access to an internal mongo DB instance. It simply does not see any collections. But access to those collections are possible if we switch to Raw and manually run. How should I fix it?

**Comment by Nikhil-Nandagopal** [comment]
@SplendidFarzad that looks like more a problem with the permissions of the role you connected to the DB with. It's likely that particular role may not have certain permissions that are necessary to scan all the collections and return them. Also do you know how many collections are in the database? The schema query might be timing out

**Comment by SplendidFarzad** [comment]
> @SplendidFarzad that looks like more a problem with the permissions of the role you connected to the DB with. It's likely that particular role may not have certain permissions that are necessary to scan all the collections and return them. Also do you know how many collections are in the database? The schema query might be timing out

I am using the root user, which has full access to all databses. All data is viewed and can be maniupulated with other tools, such as Compass. As mentioned, data can also be manipulated using the "raw" query type within AppSmith as well. But only the raw type can be used. List of available structure is not fetched in the collection lists; therefore operators like find documents, insert, etc cannot be used. This seems to be a bug that has not been fixed yet. Already have tested with 3 different mongo DB and self-hosted containers.

**Comment by Nikhil-Nandagopal** [comment]
@SplendidFarzad could you please raise a new issue with a video of the problem? We'll have someone look into it
