### ISSUE TITLE
bug: WDS switch knob color

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#26318]
We're using `bg` for knob which can have insufficient contrast with `bgAccent`, e.g. with light seeds in light mode:
<img width="172" alt="Screenshot 2023-08-14 at 10 47 45" src="https://github.com/appsmithorg/appsmith/assets/80973/e426eb52-7620-4ec8-be2f-35f987717740">

We should consider using different token / introducing new token to tackle problem generically.

For light combinations we should consider additional elements, e.g. shadow, see related: #25511

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/26318?planning-poker) with Zenhub @ichik @jsartisan @KelvinOm

**Comment by ichik** [comment]
Have been fixed with #32964
