### ISSUE TITLE
[Bug]: Unexpected Overlapping Containers

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#26324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two containers are overlapping in the user's app.
The way to fix it is by resizing or moving them until they are placed as desired.

[Slack thread](https://theappsmith.slack.com/archives/C03GQQ06934/p1691748579983969)

### Steps To Reproduce

The issue is present in [this app](https://theappsmith.slack.com/archives/C03GQQ06934/p1691751551337269?thread_ts=1691748579.983969&cid=C03GQQ06934).

### Environment

Production

### Issue video log

https://simpplr.slack.com/files/U01NV9EPRA7/F05M73USPK8/screen_recording_2023-08-11_at_3.33.11_pm.mov

### Version

Appsmith Business v1.9.32

**Comment by ame-appsmith** [comment]
This could have happened because of a git merge between two branches with overlapping widgets.

**Comment by Nikhil-Nandagopal** [comment]
Closing since we can't repro and it's likely due to a git merge
