### ISSUE TITLE
[Feature] Support lists in the datasource create/edit pane

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2634]
## Summary

The current functionality is limited to arrays of objects, which would have key value pairs. This can be extended to msimpler lists of Strings as well. Such an extension will allow us to support multiselects, and other such elements.

**Comment by nidhi-nair** [comment]
@rashmi-rai could you please close this issue by attaching the multiselect dropdown PR to it?

**Comment by rashmi-rai** [comment]
Closed via https://github.com/appsmithorg/appsmith/pull/8777
