### ISSUE TITLE
[Bug]: Page unresponsive due to large number of tables in ds for schema on action change

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#26361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Page becomes unresponsive due to large number of tables in postgres db which gets rendered for schema structure.
Slack thread : https://theappsmith.slack.com/archives/C0341RERY4R/p1692014095222679

### Steps To Reproduce

1. Create a postgres datasource having large number of tables
2. Create multiple action for the above datasource
3. Observe on switching between actions the page becomes unresponsive

### Environment

Production

### Version

Cloud

**Comment by Rakshapk** [comment]
Can i know the status or when this issue can be resolved ?
