### ISSUE TITLE
[Bug]: Performance Issue

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#26372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Data population is taking more than 5 mins for customers, even though the data fetching is completed within first 5 secs.

### Steps To Reproduce

https://theappsmith.slack.com/archives/C0341RERY4R/p1692013417747689

### Environment

Production

### Version

latest

**Comment by criticalpixel** [comment]
Also having this issue as described.

**Comment by deepaknverma** [comment]
Please see profiling metrics
<img width="848" alt="Screen Shot 2023-08-16 at 7 46 23 pm" src="https://github.com/appsmithorg/appsmith/assets/1562835/8792baa7-5e19-46cd-83f9-4d8d8a5639b9">

**Comment by pranavkanade** [comment]
This issue has been fixed in v1.9.33
Duplicate of https://github.com/appsmithorg/appsmith/issues/26400
