### ISSUE TITLE
[Bug]: Unable to create new branch in appsmith app

### ISSUE THREAD

**Issue by Shravanth10** [appsmithorg/appsmith#26371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upon my attempt to generate a new branch from the main parent branch, an error message is presented as follows:

"Unable to import application in workspace 64ca1208c019312e083ad46e. Error: The invocation of the method "Object.getClass()" cannot be executed due to the null status of the 'key'."

<img width="1792" alt="Screenshot 2023-08-16 at 12 39 30" src="https://github.com/appsmithorg/appsmith/assets/108858078/2f0afe45-c729-4ade-b6b6-638b8feaab0e">

### Steps To Reproduce

1. Begin by switching to a specific branch within a Git repository.
2. Attempt to generate a new branch derived from the currently active branch.
3. Encounter an issue where the process of establishing the new branch fails.

Additionally, when attempting to create a fresh branch directly through the GitHub platform, the branch's changes or updates might not be successfully incorporated into the Appsmith application.

### Environment

Production

### Version

self hosted - 1.9.29

**Comment by riteshkew** [comment]
@Shravanth10 Apologies for getting to this late, and I can empathize with how frustrating these small issues can be—just checking in here again to see if this is still a concern for you or if the issue is resolved.
