### ISSUE TITLE
[Bug]: Mongo query fails to populate the select/multi-select widget when specific (primary) columns are chosen as label

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#26370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Mongo query fails to populate the select/multi-select widget when specific (primary) columns are chosen as label

### Steps To Reproduce

1. D&D a select/multi-select widget
2. Choose mongo DS via one-click binding
3. Choose a primary column (i.e., _id in this case) as label
4. Choose any value key
5. Notice that the query fails

### Environment

Release

### Issue video log

https://www.loom.com/share/19431a89002c462481bf5667f1246533

### Version

Release

**Comment by jacquesikot** [comment]
We are not able to replicate this issue. When using One Click Binding with the Select or Multiselect widget, the autogenerated query works as expected for Mongo, Postgres and GSheets datasource.
