### ISSUE TITLE
[Bug]: Text widgets are not updated from selected row data

### ISSUE THREAD

**Issue by umpfel** [appsmithorg/appsmith#26398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Widget (e.g. Input, Text) are not updated when "quickly" switching between rows.
onRowSelected is executing a query & javascript to aggregate some data that is shown in a list

![Selection_024](https://github.com/appsmithorg/appsmith/assets/25528268/2d63f254-f911-4c93-85f6-055ebfb9cc80)

### Steps To Reproduce

I managed to reproduce the issue using the user example database:
[My first application.json.zip](https://github.com/appsmithorg/appsmith/files/12363658/My.first.application.json.zip)

- Import the application
- Connect to the example user db
- deploy it
- "Quickly" switch between the rows and sometimes the input fields are showing a previous value
 
In my actual application quick means switch between rows within 2-3 seconds. In this small example I need to be much faster but I am still able to reproduce it quite often.

### Environment

Production

### Version

Self Hosted - v1.9.32

**Comment by somangshu** [comment]
Seems like something to do with evaluation cycle. Please confirm @vsvamsi1

**Comment by bharath31** [comment]
@vsvamsi1 do you have any updates here?

**Comment by vsvamsi1** [comment]
Sorry @bharath31 haven't had a chance to look into this, will look into this bug.

**Comment by vsvamsi1** [comment]
Hi @umpfel 
Apologies for the delay in response and thank you for providing all the details to understand the issue.

https://github.com/appsmithorg/appsmith/assets/121419957/6fe50ab2-5d2a-4f6a-bfdc-da9c4b2040eb


I selected rows incrementally roughly 12 rows and in parallel I have timed my interaction. I did it in about 12-14 seconds this entire interaction, roughly in 1 -1.2 seconds per row. The behaviour looks fine to me i have attached a screen cast of my interaction. We have made some improvements over the last month and half, I hope that has alleviated your issue. Can you please let me know if its better for you now.

cc @bharath31 @somangshu @satbir121

**Comment by umpfel** [comment]
Sorry, for the late reply.
The issue still exists for me. On the small app that I provided the performance improved, so it became hard to reproduce. On my "big application" I can reproduce it quite easily. It runs a slightly bigger query on the "onRowSelected" and the database is not very fast.

[Screencast from 2023-11-06 17-00-59.webm](https://github.com/appsmithorg/appsmith/assets/25528268/709a8191-d786-46c5-a849-096d551fa6bb)

**Comment by vsvamsi1** [comment]
Hi @umpfel 
Thank you for response, please give me some time I will get back to you by tomorrow.
cc @rajatagrawal

**Comment by vsvamsi1** [comment]
Hi @umpfel 
I would like to analyse your application, can you please share your application with me with your updated onRowSelected query, just like how you have done earlier. I will analyse and get back to you as soon as possible.

cc @rajatagrawal

**Comment by Nikhil-Nandagopal** [comment]
We're closing this issue as we haven't heard back from you in awhile. Feel free to reopen it if you are still facing it
