### ISSUE TITLE
[Bug]: when user tries to import the app in new workspace the reconnect datasource modal is not displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#26403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when user tries to import the app in new workspace the reconnect datasource modal is not displayed
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/4867d8f7-c034-42d3-a603-84341554528b">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/10c282f0-b148-4d03-910b-8bbf7093df67">

### Steps To Reproduce

1. go to https://ee-2077.dp.appsmith.com/applications
2. click on new workspace link
3. now the new work space is created clcik on 3 dot icon click on import 
4. now import via json select any app in your local which has datasources in it 
5. now the import happens either it doesnt pop up the reconnect datasource modal or it through the error

### Environment

Release

### Version

v1.9.33

**Comment by infinitetrooper** [comment]
Stale
