### ISSUE TITLE
[Bug]: Performance issue due to dependencyMap addNodes method

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#26400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Performance issues
- 

### Steps To Reproduce

User issues

### Environment

Production

### Version

1.9.32

**Comment by ohansFavour** [comment]
RCA for this issue has been published [here](https://appsmith.notion.site/RCA-Performance-degradation-due-to-the-addNodes-method-Bug-26400-6189ec9305114b0296c0f1413c1eb1e2?pvs=4)
