### ISSUE TITLE
[Bug]: Uncommitted changes doesn't come up for app settings & theme changes, also on comitting these changes progress bar doesn't come up

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#26418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a git connected app, when app settings or theme is modified, it doesn't reflect in bottom bar pull count. Also on committing these changes, progress bar doesn't come up

### Steps To Reproduce

1. Connect an app to git
2. Add app settings or theme
3. Refresh the app and observe the count is not shown in bottom bar
4. Open git sync modal and commit changes
5. Observe progress bar doesnt come up

### Environment

Production

### Version

cloud

**Comment by RakshaKShetty** [comment]
Now we can see the changes and also commit it
<img width="788" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/394554c2-82d8-4436-bf29-5bd9ef1af642">
