### ISSUE TITLE
[Feature]function navigateTo allow open url in new page 

### ISSUE THREAD

**Issue by jk2K** [appsmithorg/appsmith#2644]
## Summary

allow open url in new page 

## Motivation

HTML a tag has this feature

## Additional Context

![image](https://user-images.githubusercontent.com/4025839/105172094-0b516500-5b5a-11eb-9cfb-0e1353bfcd45.png)

**Comment by Nikhil-Nandagopal** [comment]
@jk2K thank you for this feature request. This should be fairly simple to add.
@hetunandu could you please help here

**Comment by Nikhil-Nandagopal** [comment]
@jk2K this feature has been merged to our release version and will be available in all community editions by early next week :)
