### ISSUE TITLE
[Task]: Enable scheduled backups for all Business users by default

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#26481]

**Comment by sum35h** [comment]
@sharat87  Since the config is in docker.env, would it be acceptable to take effect only for new installs?

Also, the backups are enabled by default, leaving an option for users to disable them if they choose to do so?

**Comment by sharat87** [comment]
@sum35h, as per [this line](https://github.com/appsmithorg/appsmith-ee/blob/ccbb938e851dcb7bd565653ff1542c8062ba9d32/deploy/docker/templates/docker.env.sh#L105), existing instances should have this configuration commented out. That means the env variable `APPSMITH_BACKUP_CRON_EXPRESSION` wouldn't even be set to anything.

So let's change the default of what happens when this is not set. If someone explicitly sets it to `""`, then scheduled backups are disabled for them. If they explicitly set it to a cron expression, then scheduled backups are enabled for them. If they don't set it at all, which is what happens when this line is commented, let's behave as if it's explicitly set to `"0 */24 * * *"`.

Am I making sense? 🤔
(I may have misunderstood your question though, let me know if so).
