### ISSUE TITLE
bug: `ButtonGroup` border styling

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#26505]
We [divide border-width by 2](https://github.com/appsmithorg/appsmith/blob/013adf782c32b0ab3c938902cae0cd5e32877d26/app/client/packages/design-system/widgets/src/components/ButtonGroup/index.styled.tsx#L39) to make the whole border from two buttons.
It's a neat trick, but causes problems (shifting of borders by 1px on press) and may hinder features in the future (e.g. we allow to set density and disconnect the buttons).

https://github.com/appsmithorg/appsmith/assets/80973/fada95b7-d49f-49c2-b261-1b9141a9388b

We can follow [an example of Spectrum](https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html#density), and set small negative gap (z-index order for the elements inside is reversed).

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/26505?planning-poker) with Zenhub @ichik @jsartisan @KelvinOm
