### ISSUE TITLE
[Bug]: SCIM integration tests are being flaky when we update a group using PUT request

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#26536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

SCIM integration tests are being flaky when we update a group using PUT request

### Steps To Reproduce

1. Run the SCIMConfigResourcesViaUI_spec.ts test on CI
2. Notice that the UpdateGroup API test is flaky and the group name and description doesn't update at times.

### Environment

Production

### Version

Self Hosted - latest

**Comment by RakshaKShetty** [comment]
cant be tested manually this is covered in unit tests
