### ISSUE TITLE
[Feature]: Improve the user experience for the git branch list modal

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#26546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

What i am proposing is that we keep that CTA for list/Switch Branch as it is. But instead of that small modal we use the Top Search bar with list of branches as a drop down. The search will be enabled and lets the user search for a branch and CTA to create a new one if the branch does not exist. This experience is similar across many IDE's and looks very neat. 

### Why should this be worked on?

The current list branch modal opens at the left bottom and gets very cluttered when there are too many branches. Becomes very hard for user to look for the branch.

**Comment by Nikhil-Nandagopal** [comment]
Closing as we'r redesigning the git experience
