### ISSUE TITLE
[Docs] Typo: 'beverates' instead of 'beverages'

### ISSUE THREAD

**Issue by michaelairola** [appsmithorg/appsmith#2658]
## Documentation Link(s)
[getting-started/tutorial-1/part-2-using-forms/creating-a-form.md](https://github.com/appsmithorg/appsmith-docs/blob/v1.2/getting-started/tutorial-1/part-2-using-forms/creating-a-form.md)
[tutorial/part-2-creating-a-basic-form/creating-a-form.md](https://github.com/appsmithorg/appsmith-docs/blob/v1.2/tutorial/part-2-creating-a-basic-form/creating-a-form.md)
[tutorial/part-2-using-forms/creating-a-form.md](https://github.com/appsmithorg/appsmith-docs/blob/v1.2/tutorial/part-2-using-forms/creating-a-form.md)

## Describe the problem
I think the word 'beverates' on each of these pages should be 'beverages'

## Describe the improvement

These type words are all in 'copy and paste' code, which means when they are copied and pasted it doesn't work the way it should. Fix for better user experience

**Comment by areyabhishek** [comment]
@michaelairola Thanks for reporting. I just updated the docs.
