### ISSUE TITLE
[Bug]: Existing git connected apps throws `repository not found error` while opening app for the first time

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#26586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1440" alt="Screenshot 2023-08-23 at 1 20 30 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/5b99bda0-931c-4f34-ab81-c738cc7ac280">

https://github.com/appsmithorg/appsmith/assets/80334441/f5e733b9-ade7-43ab-b31e-554ef021c538

### Steps To Reproduce

1. Login to this https://ee-2119.dp.appsmith.com/
2. Open any git connected app
3. Observe error toast comes up

### Environment

Production

### Version

Regression Deploy preview

**Comment by AnaghHegde** [comment]
This is because the promotion DP does not have EFS volume used in release env.
