### ISSUE TITLE
[Bug]: MySQL: test datasource shows pass when port number field is left blank

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#26636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://theappsmith.slack.com/archives/C040LHZN03V/p1692927779184399

### Steps To Reproduce

https://theappsmith.slack.com/archives/C040LHZN03V/p1692927779184399

### Environment

Production

### Issue video log

https://theappsmith.slack.com/archives/C040LHZN03V/p1692927779184399

### Version

cloud, self hosted

**Comment by rohan-arthur** [comment]
not reproducible anymore
