### ISSUE TITLE
[Bug]: Duplicate Key error seen on the Activations DP while Saving Dynamo / MySQL DS

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#26647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I save a dynamo or mysql or any other DS on the Activations DP - seeing the duplicate key error

### Steps To Reproduce

1. Create a new DS [https://ce-26381.dp.appsmith.com/]
2. Fill in all the details
3. Test and Save config
4. Note the duplicate key error that comes up
<img width="1134" alt="duplicate" src="https://github.com/appsmithorg/appsmith/assets/101863839/be644291-4eb1-4ca6-b35d-664f467147be">

https://github.com/appsmithorg/appsmith/assets/101863839/320ac312-1806-4b37-830d-1866e69f6ce0

### Environment

Deploy Preview

### Version

Cloud

**Comment by rohan-arthur** [comment]
since the DP is long ago defunct, I looked at incidence of this error on prod. There are [0 errors in the last 6 months](https://mixpanel.com/project/2032485/view/178891/app/boards#id=5486396&edited-bookmark=c5fsGU9btqKJ), so closing this issue.
