### ISSUE TITLE
[Bug]: Alert shows twice for select widget

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#26696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attached screen shot : 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/2cbde085-de21-4422-95cf-3bd8d02e6f90)

### Steps To Reproduce

- Drag and drop select widget
- For an event "onDropdownClosed" > Set an action of `show alert `= Drop down closed 
- Now open the drop down of select widget and collapse the drop down and observe alerts shows 2 times

### Environment

Production

### Version

Appsmith v1.9.35-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
This no longer occurs

**Comment by SunnyTitus** [comment]
Generated the possible solution through ChatGPT:

Technical Solution (ChatGPT)

Frontend (React)

Ensure that the event listener for "onDropdownClosed" is correctly debounced or throttled to prevent multiple triggers.import React, { useState } from 'react';import Select from 'react-select'; // Assuming use of react-select library

const CustomSelect = () => {  const [isDropdownOpen, setDropdownOpen] = useState(false);

  const handleDropdownClose = () => {    if (isDropdownOpen) {      alert('Drop down closed');      setDropdownOpen(false);    }  };

  return (    <Select      options={[{ value: '1', label: 'Option 1' }, { value: '2', label: 'Option 2' }]}      onMenuOpen={() => setDropdownOpen(true)}      onMenuClose={handleDropdownClose}    />  );};

export default CustomSelect;

Backend (Spring Boot)

Ensure the backend processes any event related to dropdown closing only once, if applicable.

This might not be needed specifically for the dropdown closing event, but ensure idempotency in API calls if any backend actions are triggered by UI events.

**Solution Summary**
To fix the issue where the alert shows twice for the select widget when the dropdown is closed, the "onDropdownClosed" event should be handled in such a way that it only triggers once. This can be achieved by implementing a flag to check if the dropdown is open and setting it appropriately. The provided React code snippet demonstrates how to achieve this using state management to ensure the alert is shown only once.

**Comment by PrasadMadine** [comment]
Hi @Nikhil-Nandagopal , I'm picking this issue.

**Comment by kamakshibhat-appsmith** [comment]
This issue occurs if we click on the widget again to close the dropdown . [loom](https://www.loom.com/share/f52f260bd974466cb81ac8ea8c1c9b16)

**Comment by rahulbarwal** [comment]
Fixed via: https://github.com/appsmithorg/appsmith/pull/34812
