### ISSUE TITLE
[Bug]: Intemittent : On selected Gsheet all the sheet are dispalyed to the user 

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#26709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to Gsheet and adds scope as "Selected Gsheet" on review page it is observed that all the sheet are displayed to the user 

### Steps To Reproduce

1) Navigate to Gsheet
2) Add scope as "Selected Gsheet"
3) Authorise the sheet 
4) Select one sheet from the modal
5) preview is displayed on the Review page 
6) Click on the dropdown 
and observe that all the sheet are displayed

![Screenshot 2023-08-28 at 4 08 42 PM (1)](https://github.com/appsmithorg/appsmith/assets/132243297/e2919fe7-12cd-4a10-b81d-762746cfc811)

### Environment

Release

### Version

Cloud

**Comment by sneha122** [comment]
@prapullc Can you please share this application with me?

**Comment by sneha122** [comment]
@btsgh

**Comment by rohan-arthur** [comment]
@btsgh kindly reopen if the issue comes back
