### ISSUE TITLE
[Bug]: Traversing between movies default mongo, and edit ds page of postgres/mysql adds an additional host port field

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#26711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I traverse between Movies default mongo db, and the PostGreSQL DB Edit page, additional host port fields get added

### Steps To Reproduce

1. Create a movies db 
2. Create a postgres db - u can use the postgres details from servers and creds page notion
3. Create a query from each of the above
4. Now click on Movies DS on the left entity explorer
5. Click on PGSQL DS on the left entity explorer. Click on Edit DS from review page
6. Click back on Movies DS on the left entity explorer
7. Click again on PGSQL
8. Do this back and forth
9. Note that every back and forth to the PGSQL edit ds page, adds a row of host port combination

https://github.com/appsmithorg/appsmith/assets/101863839/a20a852d-15e1-41bd-94f2-fd9171081883

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
no entity explorer anymore, so this issue won't occur.
