### ISSUE TITLE
[Bug]: Though in Roles, DS Execute/Create/View permissions are given, user is not able to Generate page with data

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#26738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I give DS Execute Create and View permissions, the Generate page with data CTA does not work. 

### Steps To Reproduce

1. Through Admin settings, for a new workspace, create a role and give the all application resource permission and in the DS and Env tab - give Execute/Create/View for the DS
2. Now assign this role to a group and add a user to the group
3. Now Login as the above user and try Generate page with data
4. Note that it errors out

https://github.com/appsmithorg/appsmith/assets/101863839/7cf6ce51-ce42-4f4b-a966-d8bdb05de399

Note: If we give Edit permission to the above DS, then the generate page function works

### Environment

Production

### Version

Cloud

**Comment by btsgh** [comment]
FYI - it is happening on release-ee as well as on older version [checked on v1.9.32].

**Comment by trishaanand** [comment]
RCA :  This issue is happening because during generate page from datasource, edit permission is used. But here, edit permission was not being used. We should instead use "Create" permission because technically we are creating actions on top of the datasource and not editing the datasource.
