### ISSUE TITLE
[Feature]-[12000]:Validate and show errored out action fields

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2675]
## Summary
Today if you add a bad binding or config inside the action fields, they don't show any error. This should behave similar to how widget fields work

## Motivation
Inform the user about a bad binding or config before they run an action

**Comment by rohan-arthur** [comment]
applying 50% requirement, 6m usage: 6000
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 6000 |
| Effort (months)  | 0.25 |

**Comment by rohan-arthur** [comment]
we'll tackle this as a project, so closing this issue. Details: https://www.notion.so/Problem-identification-CRUD-query-funnel-7e3573f7fdb34575b8d2801420f65611
