### ISSUE TITLE
Config for Auto Commit migration

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#26772]
Making changes on a git repo automatically is not a great idea. This should be a setting which the user can turn ON or OFF.

**Comment by AnaghHegde** [comment]
Added Estimate is for backend tasks only

**Comment by AnaghHegde** [comment]
We have decided that it will be part of App settings

**Comment by riteshkew** [comment]
Closing this as it is being handled as part of separate ticket #26769 and #29127
