### ISSUE TITLE
Logic to apply the Java migrations to git file system when the properties are modified

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#26790]
There are two cases
1. The added Java migration modifies a property that does not affect git file system
2. Modifies the property which is part of the git file system

In 2nd case, we need to apply these migrations to the file system properties. So to do that we should have a way to detect the server side migrations and then apply this.

**Comment by AnaghHegde** [comment]
Adding Structural changes for the migration class to support the schema migration.

**Comment by AnaghHegde** [comment]
- [ ] Code Split for JSON Schema Migrations
- [ ] ServerSchema Version upgrade in java file
- [ ] Notion doc for the backend devs
- [ ] Adding Structural changes for the migration class to support the schema migration - low priority

**Comment by brayn003** [comment]
We have taken a different approach for this with auto-commit migrations
