### ISSUE TITLE
[Bug]: Preview different for Order Fulfilment Tracker

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#26799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![CleanShot 2023-08-24 at 17 37 24](https://github.com/appsmithorg/appsmith/assets/32227135/51b898d5-527f-4d15-9887-7d4ba8f2cac5)

### Steps To Reproduce

na

### Environment

Production

### Version

v1.9.34

**Comment by rahulbarwal** [comment]
This was due to a pending deployment of the appsmith app on which this template was based on.
@jacquesikot helped and deployed that. This should be resolved now.
