### ISSUE TITLE
[Feature]: Integration of hardware authentication devices in AppSmith apps

### ISSUE THREAD

**Issue by tukaianirban** [appsmithorg/appsmith#26806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We have a use-case where our backoffice personnel will need to encrypt certain data elements of a database based on certain inputs. We are using YubiKey for this purpose.

The user experience is expected to be:

- with a table row selected, or a pop-up open, the user should be able to encrypt a certain data field (string type).
- they click a button that triggers a check on the local workmachine (where the browser window containing AppSmith app is open) whether a hardware security key is plugged in or not.
- if a matching device is found on the local workmachine, then a signature attempt should be triggered towards it.
- the user authenticates themselves with a biometric fingerprint on the Yubikey.
- If the authentication is successful, a signature is performed using a private key that is stored inside the YubiKey.
- the signed data is then available back on AppSmith app.

### Why should this be worked on?

Backoffice functions often include authentication flows including a security hardware token / device.

For elevated actions by privileged users in backoffice functions, they might need to signing data elements, or even collection of data elements for use.

**Comment by Nikhil-Nandagopal** [comment]
This should already be possible if the device supports REST APIs
