### ISSUE TITLE
[Task]: Draft documentation for MySQL SSH tunnel

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#26807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Add documentation for the MySQL SSH tunnel feature.

**Comment by sumitsum** [comment]
Draft documentation available here: https://www.notion.so/appsmith/Documentation-for-MySQL-SSH-tunnel-dbc646ed7fbb4d6cb284bd31939181b7

**Comment by rohan-arthur** [comment]
@sumitsum there's a new process now, so bringing this back according to [this comment](https://github.com/appsmithorg/appsmith/issues/27446#issuecomment-1736733567)

**Comment by sumitsum** [comment]
https://github.com/appsmithorg/appsmith-docs/pull/1759

**Comment by sumitsum** [comment]
Closing it because changes are available on the doc page now.
