### ISSUE TITLE
[Bug]: The emails are not received when the user is added as a instance admin

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#26836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The emails are not received when the user is assed as a instance admin

### Steps To Reproduce

1. go to https://ce-26692.dp.appsmith.com/
2. sign up as email@appsmith.com
3. go to admin setting
4. go to general tab
5. add a email@appsmith.com as a instance admin save and restart
8. Now login to email@appsmith.com email and check the appsmith instance email
9. The email are not being recieved by users

### Environment

Deploy Preview

### Version

v1.9.35

**Comment by riteshkew** [comment]
Closing this. Deploy preview.
