### ISSUE TITLE
[Bug]: Emails are not received when user try to reset the password

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#26833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Emails are not received when user try to reset the password

### Steps To Reproduce

1. go to https://ce-26692.dp.appsmith.com/
2. sign up as email@appsmith.com
3. go to edit profile
4. under general tab
5. click on reset password 
6. the user is logged out
7. But not seeing a reset password emails

### Environment

Deploy Preview

### Version

v1.9.35

**Comment by ankitakinger** [comment]
This seems to be working now. Closing and adding QA label.
