### ISSUE TITLE
[Bug]: Notification emails UI issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#26832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Notification emails UI issues

### Steps To Reproduce

Go to https://ce-26692.dp.appsmith.com

- [x] The template box seems like overlapped on a grey line-->Fixed
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/e02a46e5-bc95-4590-b6d5-5d3dd1a07763">

- [x] There are extra quotes at the bottom of the email-->Fixed
- [x] The "Hey" Text should not be in bold-->Fixed
- [x] The content inside the workspace administrator/developer/viewer email doesn't match with email template in notion
- [x] The CTA name inside the workspace administrator/developer/viewer email doesnt match with CTA in notion
- [x] The show behind the temple box should be covered as in figma-->Fixed
<img width="531" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/3aac8b68-1f21-4a3c-9041-49e7d386ae47">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/39d5e1a4-fc9a-4e0c-8185-e6c69c16ea5e">

### Environment

Deploy Preview

### Version

v1.9.35

**Comment by ankitakinger** [comment]
@RakshaKShetty the hey test is supposed to be bold.

**Comment by RakshaKShetty** [comment]
@ankitakinger  had a chat with roop Instead keeping font-weight: 600 can we keep it 500 that looks same has the other fonts other while it looks like a highlighted

**Comment by ankitakinger** [comment]
@RakshaKShetty Sure we can do this.

**Comment by ankitakinger** [comment]
@RakshaKShetty 
This issue that you listed above matches with the notion. Could you let us know what exactly is different here?
`The content inside the workspace administrator/developer/viewer email doesn't match with email template in notion`

**Comment by RakshaKShetty** [comment]
Attaching the screenshot for reference the sentence looks off here
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/5826fa2d-4d38-4851-9ca4-a2409b753cba">

**Comment by ankitakinger** [comment]
Closing this as we have resolved all issues mentioned in this bug:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmR2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af63a66d074f3c2bfb97281870a530b05e5a0846/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmh2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c008009831f14555805d89464ca30bb62fc95be3/image.png)
