### ISSUE TITLE
[Feature]: Notify potential partners about our appsmith partner program

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#26857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Notify users who are inviting users from outside their domain in self-hosted instances about the appsmith partner program

### Why should this be worked on?

We believe that this is a great proactive way to get people to reach out about the partner program

Design for reference

https://www.figma.com/file/SXwzSICaZKzZMFXjq0nFRK/Appsmith-Partner-Program-callout?type=design&node-id=0-1&mode=design

Link for the users:
https://www.appsmith.com/partner-program

**Comment by kavitasmoolya** [comment]
Validated on release (Appsmith v1.9.39-SNAPSHOT) and looks good to me.
