### ISSUE TITLE
[Task]: Improve focus color logic

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#26852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The current logic is that the focus color becomes reddish if the seed color is blueish. The red focus color makes it seem as if the component is in an error state. We will need to imrove the logic for this (monochromatic or follow seed).

**Comment by ichik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/26852?planning-poker) with Zenhub @jsartisan @KelvinOm @dhruvikn
