### ISSUE TITLE
[Task]: Improve Foreground Neutral Subtle color logic

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#26854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We need to improve logic for our neutral subtle color ( used in placeholder text's color ).

**Comment by ichik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/26854?planning-poker) with Zenhub @jsartisan @KelvinOm
