### ISSUE TITLE
[Task]: analytics event for navigation in the DP

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#26879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- The timer starts when the user hits the more button
- The timer ends when the user navigates to the next page
This should be added to a new event called DP_NAVIGATION_TIME

**Comment by akash-codemonk** [comment]
Start timer when user clicks on more, end timer when we switch to a different entity.
