### ISSUE TITLE
[Feature]: Hide env dropdown in view mode if there's only one env enabled

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#26880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Proposed changes for visibility of env switch dropdown

- for edit mode, we’ll show dropdown if user has access to one or more envs.
     - In case of one env access, the dropdown will be disabled
- In view mode
     - Dropdown is visible and enabled only if user has access to two or more envs
     - If the user has access to only one env and that env is production, the dropdown will be hidden
     - If the user has access to only one env and that env is the default env(in this case production), the dropdown will be hidden
     - If the user has access to only one env and that env is not the default env(in this case staging), the dropdown will be shown but disabled

### Why should this be worked on?

The env dropdown in view mode is not helpful in cases when only one env is there so we need to hide it.

**Comment by kostyay** [comment]
I would also like this feature. I don't want to confuse our viewer users with that bar!

**Comment by ChandanBalajiBP** [comment]
Hey @geekyme-fsmk @kostyay 
This feature is in progress and will be available asap. Please follow this issue for the updates.

**Comment by patrickmast** [comment]
I think if the app is publicly available, no selection of env switch dropdown is needed. No footer is needed in public apps.
Thank you! 🙏

**Comment by shantanu1singh** [comment]
Same here. Hoping this feature is released soon! My users are getting confused by the env bar.

**Comment by davd-edia** [comment]
Same here.

**Comment by areyabhishek** [comment]
This issue has shown up again, reopening it.

**Comment by areyabhishek** [comment]
Issue is fixed for view mode for viewers
