### ISSUE TITLE
[Bug]: Inappropriate watermark and message is disaplyed on scehma search on review page and query page

### ISSUE THREAD

**Issue by prapullc** [appsmithorg/appsmith#26882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to the review page after establishing a connection, the user tries to search for schema and observes the message stating "table or attribute" where we are only allowing user to search wrt table name.

### Steps To Reproduce

1) Establish the connection
2) Navigate to review page 
3) Observe the search bar on the schema for the message  
attaching the video the for same below 
https://czqtakk0ok.vmaker.com/record/gVkLwZE16BXVHXuc

### Environment

Deploy Preview

### Version

Cloud

**Comment by rohan-arthur** [comment]
the hint text has been changed some time ago to `search for table` . This issue is no longer valid.
