### ISSUE TITLE
[Feature]: Add support for passing function definitions from eval thread to main thread

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#26884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The users would like to specify function definition for echarts configuration in the property pane [like this](https://echarts.apache.org/examples/en/editor.html?c=scatter-label-align-top). At the moment, there is ability to pass only evaluated values of a function to main thread. There is a requirement to pass function definition rather than function return value for ECharts

### Why should this be worked on?

This enables the user to use ECharts inside Appsmith. Without this feature, we won't be able to release Custom ECharts to our users. This is a blocking issue.

**Comment by dustinrecko** [comment]
@bharath31 would love to see this. I currently use echarts in appsmith but I am exactly missing this functionality. Thanks

**Comment by bharath31** [comment]
@satbir121 could we estimate the effort here?

**Comment by rajatagrawal** [comment]
@dustinrecko 

Thanks for reaching out.

Can you please give us an example of how are you using ECharts in Appsmith right now ? This will help us understand your use case better. Thanks!

cc : @somangshu @dilippitchika

**Comment by dustinrecko** [comment]
@rajatagrawal , basically as described in this issue. For many axis label formatting requirements it is needed to pass a function to echart's formatter option because otherwise it's quite limited.

**Comment by dilippitchika** [comment]
@dustinrecko can you let me know the following?
1. Are you using e-charts via iframe? Have you installed the echarts library using our custom JS libs feature?
2. Is there a reason you are using e-charts? Did fusion charts not work for you?

**Comment by dustinrecko** [comment]
hi @dilippitchika , 

1. no, I'm using the native solution that is currently in progress as far as I understand (I accidentally stumbled upon the fact that I can use CUSTOM_ECHART as chart type value and then it works in appsmith cloud)
2. I just remember that I had an issue with fusion charts so I started some research and during that research I figured out that you are currently working on a migration to echarts so I stopped with fusion charts :)

**Comment by dilippitchika** [comment]
@dustinrecko thanks for letting me know, can you suggest which chart are you using from custom_echart?

**Comment by dustinrecko** [comment]
@dilippitchika , what do you mean exactly?  this is how it looks for me:
![image](https://github.com/appsmithorg/appsmith/assets/16578820/e7288be2-5b0f-43a0-840c-ed9e39173d70)

**Comment by cch264** [comment]
Is this being worked on? Would love to be able to pass functions in the echart option config object.

**Comment by rajatagrawal** [comment]
This is already implemented and available with ECharts in Chart Widget. Can you please check it out @cch264 ?
