### ISSUE TITLE
[Bug]: Sliding when adding a row to a Google Sheets sheet

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#26890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user reported that when adding new rows to their Goggle Sheets, the data shifts one column to the right.

I have tested to determine the cause of this problem and noticed that this situation occurs when there are previous empty columns. In the case of the user, column A of the sheet was empty causing that, when adding data in a new row, it would start from column C and not from column B (as it should be).

### Steps To Reproduce

1. Create a test Google Sheets sheet and set it up as shown in the image below:

![1](https://github.com/appsmithorg/appsmith/assets/114161539/61fa5562-be46-4eab-96ff-538807064b0a)

2. In an Appsmith app, set Google Sheets as the data source and create an Insert One query to add rows to the sheet.

![2](https://github.com/appsmithorg/appsmith/assets/114161539/23ad2668-7142-4dca-9a1c-c49e3af7a403)

3. Run the query and see that the row has been successfully added to the sheet.

![3-1](https://github.com/appsmithorg/appsmith/assets/114161539/e0073591-10fd-4ed8-9e3c-b3e3cf8ba7ba)
![3-2](https://github.com/appsmithorg/appsmith/assets/114161539/3b49ec82-ad0e-43da-a6c4-701da47604a2)

4. Now modify the sheet by inserting a column to the left, i.e., column A should be left empty.

![4](https://github.com/appsmithorg/appsmith/assets/114161539/7c3fc0ab-d00c-40be-bcf0-03600b651f30)

5. Run the same query above and notice that the row has been added to the sheet but shifted to the right.

![5](https://github.com/appsmithorg/appsmith/assets/114161539/6f9678b1-7dee-43c3-ae35-1dbb56894438)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is expected
