### ISSUE TITLE
[Task]: Install NodeJS directly, instead of the script from NodeSource

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#26891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The NodeSource installation script we're using in the Docker image is deprecated.

![shot-2023-09-01-03-37-15@2x](https://github.com/appsmithorg/appsmith/assets/120119/f8ba456f-bb91-4083-8924-988dd09b58cc)

Let's move away from this script and install NodeJS directly from [nodejs.org](https://nodejs.org).

1. Download the latest v18 LTS Archive from https://nodejs.org/en/download, for the architecture we're building the Docker image.
2. Verify the checksum of the downloaded archive. Let's hardcode the checksums in the Dockerfile.
3. Extract NodeJS to `/opt/nodejs`.
4. Add to `$PATH` so that `node` executable is available.

**Comment by Addyk16** [comment]
Is this issue still open?
Also, why are you not using nvm to download NodeJS?

**Comment by Addyk16** [comment]
I've got the coded solution for the issue, but I am new to contribution. So, can you help me with that?

**Comment by sharat87** [comment]
Hey @Addyk16, thank you for your interest to contribute. Yes, this issue is still very much open. 🙂

> why are you not using nvm to download NodeJS?
Since this is for installing NodeJS in the Docker image, as part of CI, we'd prefer there be fewer external dependencies and links in the chain, as possible. Using `nvm` is better suited for development environment in my opinion, and I fear it'll be another NodeSource that we'll have to come back to take a look at again in the future.

That's the reason for my preference to download the tar directly and extract to `/opt/nodejs`. Own the installation in the Dockerfile itself.

> I've got the coded solution for the issue, but I am new to contribution. So, can you help me with that?
Sure. Please raise a PR with your changes and we can discuss on the PR itself from there. There's more instructions and help at https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md.

Thanks!

**Comment by sharat87** [comment]
Hey @Addyk16, have you started working on this? Asking because I just realized NodeSource has a DEB repository at https://github.com/nodesource/distributions#installation-instructions, which might be the easier way out here. I've updated the issue description as well. Thanks!
