### ISSUE TITLE
[Bug] Duplicate Accounts with Same Email - Field is Case Sensitive

### ISSUE THREAD

**Issue by myevo8u** [appsmithorg/appsmith#2689]
## Description

[What happened]
I couldn't remember the email associated with my account and tried everything. Next step was to go into Mongo and view the user records, realized I used a capitol letter in the email. No problem, went back to login using the case sensitive string and was in. 

So for testing reasons, I decided to create another account with the same email using all lowercase letters. I was successfully able to create two accounts tied to the same email. 

### Steps to reproduce the behavior:
Add steps to reproduce this behavior, include console / network logs & screenshots
1. Go to ' Sign up page'
2. Create an account with an email such as 'test@domain.com'
3. Enter password and create account
4. Sign out of that account
5. Go to sign up again
6. Create another account  with an email 'TesT@domain.com
7. enter password and create account.
4. You should now have two separate accounts with the same email. 

### Important Details
 - Version: [Self-Hosted v1.3.1]
 - OS: [Synology NAS DSM 6.2.3]
 - Browser [Chrome]

**Comment by Nikhil-Nandagopal** [comment]
Hi @myevo8u, thank you for reporting this. I'm sorry you faced this issue, we'll look into this.
@sharat87 could you look into how we can normalize emails?
