### ISSUE TITLE
[Bug]: The instance name doesn't change in the body based on the Notification email design

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#26914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The instance name doesn't change based on the Notification email design
<img width="505" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/6fac0b5e-1bc1-45b2-bea8-6c6f784bd4a3">
<img width="1108" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/c70bc067-835a-48ab-b060-a84451e2d7e8">

### Steps To Reproduce

1. go to https://ee-2123.dp.appsmith.com
2.  Go to general setting chnage the instnace name to "XXX"
3. Now signout and try to send a forgot password 
4. Now in the email the instance name is changed in the subject not in the body

### Environment

Deploy Preview

### Version

v1.9.35

**Comment by ankitakinger** [comment]
This seems to be fixed now. Closing and adding QA label.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1Z2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--132fd94470cfd0b91d18ed94c35def76c68ceefc/image.png)

**Comment by RakshaKShetty** [comment]
<img width="780" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/20c72086-bbcd-471b-bed1-04096d0aaa99">
