### ISSUE TITLE
[Task]: Breakdown and analysis of effort required to add a new integration

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#26931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Provide a breakdown and analysis of how much time is required and why so for adding a new integration.

**Comment by rohan-arthur** [comment]
[not urgent] @sumitsum have you created a doc for this? If yes would you please link it?

**Comment by sumitsum** [comment]
Writeup is available [here](https://www.notion.so/appsmith/Why-adding-a-new-Integration-takes-upto-3-months-6b27e913c3784ae8a2af9caef2783ce4). cc: @rohan-arthur
