### ISSUE TITLE
[Task]: Integrate widgetPositions observer with css based layout

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#26947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Integrate widgetPositions observer with css based layout. Since the completion of widget positions has a dependency on css based layout. This task is to integrate the widget positions observer regardless of which feature goes in first to release

**Comment by riodeuno** [comment]
- Make sure positions observer is setup as a module with two outputs
  - Component that will be wrapped around or a hook for anything that we want to listen for dimension and position changes
  - Reducers are filled with the current positions `widgetPositionsReducer`
