### ISSUE TITLE
Simplify app view experience

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#26952]
Currently, Appsmith experience for an end-user is exactly same as what it is for a developer. However, organisations often want to a much simpler experience for end-users. Lot of features/ information that is relevant for developers typically is not relevant for end-users and often results in confusion when they are exposed to this confusion. The idea is to simplify end-user experience when they sign-up for Appsmith.

**Comment by Debsourabh** [comment]
- [ ] Figure our the current issues
- [ ] Look for edge cases and other tools
- [ ] How will GAC affect this?
- [ ] Design changes

**Comment by Debsourabh** [comment]
Here is the design research deck : https://www.figma.com/file/JlcP5XIvUuxZranbLibMRr/Viewer-Mode-Scenario%2FFlow?type=whiteboard&node-id=0%3A1&t=46M8tI5aHBSaWehn-1

**Comment by Nikhil-Nandagopal** [comment]
Closing in favor of #23386
