### ISSUE TITLE
[Bug]: Opening git connected apps for the first time gives internal server error on DP

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#26954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1418" alt="Screenshot 2023-09-05 at 11 21 28 AM" src="https://github.com/appsmithorg/appsmith/assets/80334441/2424eaba-18c9-49c2-bb49-731958e21591">

### Steps To Reproduce

1. Go to https://ee-2239.dp.appsmith.com/
2. Open any existing git connected app
3. Observe error toast is thrown for the first time

### Environment

Release

### Version

Deploy preview: https://ee-2239.dp.appsmith.com/

**Comment by sum35h** [comment]
@Parthvi12  We've verified that this was due to the missing git files when restoring the release db snapshot.
Can we close this now?
