### ISSUE TITLE
[Bug]: `Full color picker` field toggles off automatically

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#26960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`Full color picker` field toggles off automatically when user changes from Primary color to Background color and vice versa.
Also the color palette does not close on mouse click once opened

### Steps To Reproduce

Go to App settings > Theme

### Environment

Release

### Issue video log

https://www.loom.com/share/691e33deb7414f9db24e9ef55d6c0e3d

### Version

Cloud

**Comment by somangshu** [comment]
@KelvinOm please check this issue, some more UX inconsistency with the full color picker. 
Priority is `LOW`.

**Comment by shwetha-ramesh** [comment]
> The fix is [here](https://github.com/appsmithorg/appsmith/pull/27028).

@KelvinOm  Tested this fix. Works as expected.
