### ISSUE TITLE
[Bug]: Adding more than 3 templates throws error

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#26975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error is thrown when a user adds more than 3 templates to an application.
![image](https://github.com/appsmithorg/appsmith/assets/92293815/9a491393-a80c-4c1d-b4cb-75da3604b793)

### Steps To Reproduce

1. Click on `Add page from templates`
2. Add more than 3 templates and observe

### Environment

Release

### Issue video log

https://www.loom.com/share/27855b1070cd410899f80e4d0d1bfe15

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Seems to work
