### ISSUE TITLE
[Bug]: Discard fails with 'Unable to import application in workspace' error in a specific app

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#26970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1440" alt="Screenshot 2023-09-05 at 1 24 19 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/762db765-f6bf-455f-8954-fc85bc3dcca3">

### Steps To Reproduce

1. Go to this app: https://ee-2239.dp.appsmith.com/app/template-app/page1-642ba359d6d8807c599f7b19/edit?branch=master
2. Try to discard, observe it fails
Note: On release discarding works fine on this app

### Environment

Deploy Preview

### Version

Deploy preview

**Comment by tkAppsmith** [comment]
@Parthvi12 this is working now
