### ISSUE TITLE
[Bug]: Extra commit comes up in git modal after committing queries related changes

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#26999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After committing datasource query, an extra commit is coming up as below , not able to discard this change: 

<img width="1440" alt="Screenshot 2023-09-05 at 10 17 49 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/cffd410a-9dab-45c7-ad21-d10eacf90c4d">
[](url)

### Steps To Reproduce

1. Create a datasource and some queries in git connected app
2. Commit the changes
3. Observe after completion, it still shows uncommitted changes as datasource modified

### Environment

Deploy Preview

### Version

https://ee-2239.dp.appsmith.com/

**Comment by btsgh** [comment]
Since this is on a deploy preview, marking as high, as critical issues are reserved for issues on Production
