### ISSUE TITLE
[Task]: Add layout to MainContainer.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#27007]
If user creates an app on Anvil layout system, The DSL for MainContainer should container a layout property.

```
  layout: [
   {
      layoutId: "",
      layoutType: "ALIGNED_COLUMN",
      layout: [],
      isDropTarget: true,
      isPermanent: true,
      childTemplate: {
         layoutId: "",
         layoutType: "ALIGNED_ROW",
         layout: [],
         insertChild: true,
      }
   }
  ]
```

**Comment by aswathkk** [comment]
Also take a look if we can rename appPositioningType to LayoutSystemType

**Comment by prsidhu** [comment]
@aswathkk There is a separate task for that.

**Comment by NilanshBansal** [comment]
The `dsl` key is a JSON Object in the backend codebase, which means that we can add any more keys to this object. 
The client can pass the new layout key in the api request and the backend already supports that today.

This is a client-side-only task, which requires no BE bandwidth. 
cc: @somangshu @prsidhu @marks0351

**Comment by riodeuno** [comment]
- DSL Migrations should not run for Anvil applications
- Properties like `leftColumn`, `rightColumn`, `parentRowSpace`, etc, should not be added to the DSL in any flow
- DSL migrations in Anvil is technically possible (avoidable but still possible), so we need a way to migrate only Anvil DSLs.
- Migrations assume a hierarchy that is widget -> children[], this may change in Anvil, so Migrations are even more not feasible.
