### ISSUE TITLE
[Task]: Create sagas for Anvil.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#27005]
Sagas should handle the following functionalities:
1. `addNewWidget`:
a) if parentLayout uses a `childTemplate`. Construct a new layout using childTemplate json and add the movedWidgets to it.
b) Add childTemplate / movedWidgets to the `parentLayout` using components static method `addChild`.
c) Store the updated parent widget in redux.

2. `removeWidget`:
a) For each widget - 
b) Traverse the layout tree of parentLayout to find the layoutId of the layout that wraps the widget.
c) Remove the widgetId from `layout` property of the affectedLayout.
d) If `affectedLayout.layout` is empty and `affectedLayout.canBeDeleted`, remove affectedLayoutId from the layout property of its parent layout.
e) Recursively perform the step d) until (i) parentLayout is reached; or (ii) current layout is not empty.

**Comment by prsidhu** [comment]
should `canBeDeleted` be replaced by `cantDelete`, since the latter are going to be fewer in number?

**Comment by aswathkk** [comment]
We also need unit testing for these

**Comment by aswathkk** [comment]
We also need unit testing for these
