### ISSUE TITLE
[Task][Design]: Typography scale Research

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#27015]

**Comment by AbhaySM** [comment]
New typography tests and results. Tested the type in as many scenarios as I could find, works alright and looks much cleaner than the app is today—
https://www.figma.com/file/wvN4v0Dxazlegk8XbTdhv7/Typography-Update-Trials?type=design&node-id=0%3A1&mode=design&t=CmZrgywPcJU6bdNe-1
