### ISSUE TITLE
[Bug]: binding walkthrough crashing

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#27032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The walkthrough component uses `querySelector`. This throws an exception for selectors starting with a number and some other characters. Fix here is to escape the selectors for these cases. 

### Steps To Reproduce

- Signup as a new user
- Create a query, run it successfully
- Add table widget from suggested widget. Note that the widget id must start with a number to repro the crash. 
- Wait for 5 seconds for the walkthrough to appear, app crashes.

### Environment

Release

### Version

Cloud / Self hosted

**Comment by kavitasmoolya** [comment]
Verified on release version (Appsmith v1.9.39-SNAPSHOT)
![image](https://github.com/appsmithorg/appsmith/assets/134914630/855b13c6-5f0f-4439-ab95-33600fa827c9)
