### ISSUE TITLE
[Bug]: Fix layout of pie chart for smaller heights

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#27035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The title of the pie chart should not overlap with legend when the height of pie chart is less.

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by chandannkumar** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbm1UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--659dfc4193f3a9b5bfaf278b50787a4047112aa0/image.png)

The actual pie chart seems smaller as expected because the fix is similar to the fusion chart layout

**Comment by chandannkumar** [comment]
Tested this issue and LGTM
