### ISSUE TITLE
[Bug] Date picker validation has regressed

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#2703]
## Description

Any date is always invalid. Valid dates between min and max dates error out.

### Steps to reproduce the behaviour:
<img width="719" alt="Date picker regression" src="https://user-images.githubusercontent.com/292174/105674245-3565a700-5f0d-11eb-9739-647e6ad163ff.png">

### Important Details
 - Version: Cloud
 - OS: N/A
 - Browser N/A

**Comment by Nikhil-Nandagopal** [comment]
I think the date picker has become a mess. Can we take some strong decisions around this?
- The property pane will require a date type to be set and this will not change based on the format
- The format will inject a new property called formatted date into the date picker.
- We'll have to handle migration for this or deprecation of the previous date property.
@riodeuno @jsartisan

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno @jsartisan can we pick this up on priority? Related to #1476
