### ISSUE TITLE
[Bug]: Welcome Mailer received on every signin request

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#27054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Everytime I login using google, I receive a welcome email.
Slack Thread: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1694063599126149

### Steps To Reproduce

1. Signin on app.appsmith.com using google auth
2. Check your inbox for the welcome emailer.

### Edit
Signin using username password also triggers welcome emailer
Ref: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1694433365069269?thread_ts=1694063599.126149&cid=CGBPVEJ5C

### Environment

Production

### Version

v1.9.36-SNAPSHOT

**Comment by kavitasmoolya** [comment]
Validated on release Appsmith v1.9.39-SNAPSHOT
