### ISSUE TITLE
[Bug] Video Widget doesn't play

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2707]
## Description

The video widget doesn't play the video once it is clicked

### Steps to reproduce the behaviour:
1. Drag a video widget
2. Click the play button
3. An error is seen
4. The video plays on you tube
<img width="839" alt="error" src="https://user-images.githubusercontent.com/3897254/105693928-55ee2b00-5f26-11eb-9bef-157a3ed35ba0.png">

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal I just tried few URLs from youtube on the video widget on production. Seems to be working for me. Is this happening for specific URLs or every URL?

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan looks to be a youtube specific problem so closing this issue
