### ISSUE TITLE
[Bug]: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [appsmithorg/appsmith#27083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

ScreenShot
<img width="944" alt="Screenshot 2023-09-08 100137" src="https://github.com/appsmithorg/appsmith/assets/91591901/e008b517-7dac-4c72-8b95-b69f40a53a6a">

### Steps To Reproduce

Scroll to footer section and see twitter old logo

Additional Context
Won't change anything in the code as such would replace the twitter-logo with a new file. No code will be touched.

@mohanarpit , @Nikhil-Nandagopal , @pranavkanade 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Public Sample App

https://www.appsmith.com/

### Environment

Production

### Version

latest

**Comment by VikraMS66** [comment]
Hi, I'm beginner, can I work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@VikraMS66 @lalitkumawat1m unfortunately our website code is not open source and hence we don't accept contributions to it
