### ISSUE TITLE
[Bug]: JS Object Stops Working After Change

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#27098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After making a small change to a JS Object, and then changing it back, it does not work anymore. After cloning the app, the JS Object still does not work, even if there was no change made.
[Slack thread](https://theappsmith.slack.com/archives/C05QUCS74J2/p1694097242479089)

### Steps To Reproduce

1. Make a small change to a JS Object.
2. Change it back.
3. Clone the app.
4. Note that it does not work anymore in the original or cloned app.

### Environment

Production

### Version

Appsmith Business

**Comment by bharath31** [comment]
@satbir121 could you please triage this?

**Comment by Nikhil-Nandagopal** [comment]
I believe this was the performance problem so we'll close it
