### ISSUE TITLE
[Bug]: IS NULL operator doesn't work in MySQL

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#27090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When writing a SELECT statement in MySQL, using the IS NULL operator returns an error saying `Your query failed to execute`.
This is supported in MySQL by default but it doesn't work in Appsmith. 

### Steps To Reproduce

Create a select statement and with a Field set to IS NULL in the WHERE clause. e.g.:
 `SELECT * FROM users WHERE name IS NULL;`

### Environment

Production

### Version

Cloud / Self-hosted - 1.9.37

**Comment by rohan-arthur** [comment]
@narhzih please try this statement with the prepared statement setting turned off as shown in the screenshot.
![Screenshot 2024-03-13 at 15 51 17](https://github.com/appsmithorg/appsmith/assets/94514895/c190b600-4f8a-4c41-9bc8-7e2dd40d9342)

More on prepared statements [here](https://docs.appsmith.com/connect-data/concepts/how-to-use-prepared-statements).
