### ISSUE TITLE
[Bug]: `resetWidget()` Not Working for Input Widget Where `setValue()` Was Used

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#27119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When running the `resetWidget()` method for an Input widget for which we previously ran the `setValue()` method, the widget does not reset to its default value. Even after manually typing something else in the Input widget, if then running `resetWidget()`, it gets set to the value that was provided with the `setValue()` method, as if it has overwritten the default value.
However, on page refresh, the **Default Value** is shown again in the input widget as expected. It seems that this is the only way to reset the Input widget to its default value after the `setValue()` method was used.

### Steps To Reproduce

1. Add an **Input widget** called `Input1` to the canvas.
2. Enter a **Default Value** for it (e.g., `John`).
3. Add a **Button widget** to the canvas and set its **onClick** method to `{{Input1.setValue('Hello!')}}`.
4. Add another **Button widget** to the canvas and set its **OnClick** method to `{{resetWidget("Input1")}}`.
5. Click the **first button** that sets the value.
6. Click the **second button** that is supposed to reset it.
7. Type something else in the **Input widget**.
8. Click again the **button** that is supposed to reset it.
9. Refresh the page.

### Environment

Production

### Issue video log

https://www.loom.com/share/a514cfec83cf4e2f854e1a63312c40f1

### Version

Appsmith v1.9.36

**Comment by eli-wolf-sinovia** [comment]
I am experiencing this issue with the select widget as well.

**Comment by Druthi** [comment]
@bharath31 The way we implemented `setValue` was with the understanding that `setValue` is setting the `defaultValue` of the widget. 

Therefore in this case, when you click on `resetWidget` it will reset it back to the last updated `defaultValue` which is `Hello!` in the above case. So this is the expected behavior for all the widgets.
