### ISSUE TITLE
[Bug] Map Widget Initial Location doesn't get updated

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2711]
## Description

The initial location of the map widget does not get set from the property pane till the widget is moved

### Steps to reproduce the behaviour:
1. Add a map widget
2. Enter a value in the initial region
3. The map does not scroll to that region

**Comment by riodeuno** [comment]
Steps to reproduce:
- Enable create marker
- Add a marker
- Change the initial location
