### ISSUE TITLE
[Bug] Duplicate property for map widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2712]
## Description

The map widget shows 2 properties mapCenter and center which both have the same values in the auto complete

**Comment by Devedunkey** [comment]
![Screenshot from 2021-02-14 02-38-20](https://user-images.githubusercontent.com/29448764/107871240-c2957f00-6e6d-11eb-8abe-10880e29584e.png)
Would you clarify this issue? I created the map, but I don't see the same value printed.

**Comment by Nikhil-Nandagopal** [comment]
@Devedunkey when you try to bind the map to a text widget you will see this.
Drag a text widget, in the text field type {{Map1.
in the auto complete you will see 2 values center and map center

**Comment by Devedunkey** [comment]
@Nikhil-Nandagopal 
Thank you. I got it. Would you assign this to me?

**Comment by Nikhil-Nandagopal** [comment]
@Devedunkey go for it!
