### ISSUE TITLE
[Feature] MDI Icons available in buttons and elsewhere

### ISSUE THREAD

**Issue by gqetre** [appsmithorg/appsmith#2713]
## Summary

Make (color selectable and resizeable?) MDI icons available inside buttons
Make (color selectable and resizeable?) MDI icons available as Widget

## Motivation

UI Space-saving,  e.g. 1 character/MDI buttons
Allow users to develop slicker more intuitive user interfaces in less time

## Additional Context

http://code.meta-platform.com/assets/mdi/preview.html

https://material.io/resources/icons/?style=baseline

**Comment by Nikhil-Nandagopal** [comment]
@gqetre thank you for the feature request! Every contribution to our roadmap helps make appsmith better :)

**Comment by Nikhil-Nandagopal** [comment]
Closing this because button icons will be picked up as part of #27864
