### ISSUE TITLE
[Task]: Update the binding icon in the ADS

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#27142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Figma Link to the component: https://www.figma.com/file/d5VUToHStOs5ADFkvAJp74/Widget-binding-Success?type=design&node-id=212-18452&mode=design&t=Wf4G0gQCYGGOZZoo-4

SVG Code: 
![Binding icon](https://github.com/appsmithorg/appsmith/assets/92779003/ee548178-46fb-4c54-95e7-e8440340a179)

**Comment by albinAppsmith** [comment]
Also adding bill-line, file-paper-2-line from remix as requested by @Debsourabh
