### ISSUE TITLE
[Feature]: Add a monospace font

### ISSUE THREAD

**Issue by cwarnock** [appsmithorg/appsmith#27167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be useful to be able to display text using a monospace font, such as courier, as it would allow text in the Text widget to be aligned

### Why should this be worked on?

I have this text which is the output of a javscript function: https://i.imgur.com/jg72MRa.png
But as none of the fonts available in appsmith are monospace it displays like this: https://i.imgur.com/gu6ftnB.png

**Comment by ichik** [comment]
@cwarnock have you considered using a different output formats, e.g. a table?

**Comment by fwhdzh** [comment]
I want this feature too. Sometimes I want to display some formatted texts on the interface, like a code snippet or a simple image composed of characters. A monospace font can help a lot.

**Comment by KelvinOm** [comment]
Will fixed this here https://github.com/appsmithorg/appsmith/issues/20365
