### ISSUE TITLE
[Task]: Remove feature flag of server side filtering for table widget and update documentation

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#27164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by dhruvikn** [comment]
Adding some more context here - we'll not only need to remove the `release_table_serverside_filtering_enabled` flag, but also we'll need to test if older apps require migrations. If yes, we'll need to add the migration for adding the `enableServerSideFiltering` property to the widget and set a default value of `false`.
