### ISSUE TITLE
[Bug]: BigQuery Reauthorization Required to Authenticate API

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#27175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A [user](https://app.frontapp.com/open/cnv_13c9zqa4?key=z0mwErCKCM1_Ogo_fYZPUAuTSh0TJ0lt) reported that they have an application that integrates an Authenticated API with BigQuery, which they configured by following this [guide](https://www.appsmith.com/blog/integrate-bigquery). They said everything worked perfectly at first, however, after 24 hours, they encountered an authorization error which they fixed by editing the data source and then clicking “Save and Authorize”. This is the error they get:

![image](https://github.com/appsmithorg/appsmith/assets/114161539/34130861-fd7b-4075-ba90-746ba6425c87)

### Steps To Reproduce

What I tried to replicate the problem was the following:

1. I configured an Authenticated API for Big Query using this [guide](https://www.appsmith.com/blog/integrate-bigquery).
2. I ran a query to check that the data source configuration worked. I obtained a successful response.
3. I waited 48 hours and I re-ran that query again, without having to reauthorize, and it worked correctly.

Furthermore, I left my API for 3 days, and I ran it again later without any issues. Due to the above, I couldn't see the error. 

### Public Sample App

https://app.appsmith.com/app/analisa/main-64dbce0e0c90753f8da62324

### Environment

Production

### Issue video log

https://app.frontapp.com/open/msg_1z1d04gc?key=z0mwErCKCM1_Ogo_fYZPUAuTSh0TJ0lt

### Version

Cloud and Appsmith v1.9.33-SNAPSHOT

**Comment by rohan-arthur** [comment]
follow conversation here: https://theappsmith.slack.com/archives/C0341RERY4R/p1694443624416289?thread_ts=1687454536.009099&cid=C0341RERY4R

**Comment by pedrorjbr** [comment]
I am the user who reported. I am wondering if the issue might be correlated with using a personal user. Should a system user be used instead?

**Comment by pedrorjbr** [comment]
The link is not workig: https://app.appsmith.com/app/analisa/main-64dbce0e0c90753f8da62324
I would like to see the real example.

**Comment by Nikhil-Nandagopal** [comment]
@pedrorjbr is this issue still a problem for you? I think it should have been resolved and so I'm closing it. Let me know if you still face this
