### ISSUE TITLE
[Bug]: The user is logged out of the instance when we try to authenticate app level imported Gsheet

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is logged out of the instance when we try to authenticate app level imported Gsheet
![image](https://github.com/appsmithorg/appsmith/assets/45958978/7bdc3f00-4b83-44f6-9de1-3ab385e0d6dd)
https://www.loom.com/share/70584f0b7c644b988f9ac7809c704a89?sid=e3b68b70-9a74-4619-8b9a-41267cbbbb3e

### Steps To Reproduce

1. Go to https://ee-2281.dp.appsmith.com/
2. create a new workspace and a app
3. Not in edit mode
4. click on app setting then on Import 
5. Now import any one of your json app which has gsheet datasource
6. once the reconnect modal is up try to authenticate the gsheet datasource 
7. Noe the user is redirected to login page

### Environment

Release

### Version

v1.9.38

**Comment by btsgh** [comment]
Note - this issue happens when we fork an app with gsheets DS as well.
