### ISSUE TITLE
[Feature] datasource form: mark mandatory fields to distiniguish them from optional fields

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2717]
## Summary
1. when filling datasource form, if mandatory field is not filled then the save button is not enabled. This can confuse a user as the user does not know that few fields are mandatory and few are optional. 
2. Additionaly, hovering mouse pointer over disabled save button could show a message saying that one of the mandatory fields is empty.

<img width="1792" alt="Screenshot 2021-01-26 at 11 38 40 AM" src="https://user-images.githubusercontent.com/1757421/105807255-a7042a80-5fcb-11eb-994a-bae66a9cf4ae.png">

**Comment by rashmi-rai** [comment]
we have a related issue here https://github.com/appsmithorg/appsmith/issues/8303

**Comment by sumitsum** [comment]
@rashmi-rai is #8303 related to `UQI` ? The issue here talks about defining the `isRequired` tag in `UQI` in case it has not been done yet.

**Comment by rashmi-rai** [comment]
@sumitsum It was part of UQI epic and was intended to be picked along with UQI component dev.

**Comment by sumitsum** [comment]
Closing in favor of #8303.
