### ISSUE TITLE
[Bug]: Modal doesn't open automatically when URL has the widgetId

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#27204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Related to #20439

Modal widget doesn't open when accessed via the URL. In Appsmith, if the widgetId is referred in the URL with paths ending with `/widgets/<widgetId>`, the application scrolls to the respective widget after loading.
However, this doesn't happen for a Modal widget, nor for its children.

https://github.com/appsmithorg/appsmith/assets/103687/f58f2ce0-690a-4fb7-b749-d21c5ba9cab9

### Steps To Reproduce

1. Add a modal widget to a page
2. The modal should be open and the URL must have the `widgets/<modal widget id>` suffix in the path.
3. Reload the page

The modal widget doesn't open.

### Environment

Production

### Version

Cloud 1.9.36 (Should be replicable in all instances)

**Comment by shadabbuchh** [comment]
Verified on release:

https://github.com/appsmithorg/appsmith/assets/39921438/5075793c-6d74-4f68-a1fd-190afa4ee791
