### ISSUE TITLE
[Bug] The error state within the create organization modal looks quite different from other places

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2720]
In addition to the toast message, there are two iterations of the error message within the modal.

![image](https://user-images.githubusercontent.com/5298848/105838692-6ec61180-5ff6-11eb-8691-d57b3b258d34.png)

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by Nikhil-Nandagopal** [comment]
@Debsourabh can we get designs for this? This looks pretty bad

**Comment by Debsourabh** [comment]
We should do the same experience we do for creating a new application today. When they create a new organization we just let them go to the new state with edit name as the active state.
