### ISSUE TITLE
(Done) Error seen on Saving a custom environment configuration for movies DS [https://drive.google.com/file/d/1UUdW54a50A5CI2TFigftnLc2C5GbSsU4/view?usp=drive_link]

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#27212]
Issue video link - https://drive.google.com/file/d/1UUdW54a50A5CI2TFigftnLc2C5GbSsU4/view?usp=drive_link

**Comment by btsgh** [comment]
Not seeing this error, but seeing Duplicate configuration error issue. Raising a separate [bug](https://github.com/appsmithorg/appsmith/issues/28030) for that.
