### ISSUE TITLE
[Task]: Change of onboarding point to start creating application behind feature flag

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#27236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Change the creation of application flow : Choose between template or scratch
- Fix the test cases if failing or support if for A/B test `false` value.
Notion doc : https://www.notion.so/appsmith/By-improving-the-templates-discoverability-we-ll-increase-the-of-users-who-start-from-a-template--5f219f72c5d74466a31662b9d928b01d

Designs: https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=2338-29522&mode=design&t=yFOm2Xh625BLfr41-0

**Comment by rohan-arthur** [comment]
from the test party: we need to fix one bug before shipping https://www.notion.so/appsmith/06a556f6c8984125a292f231647bacc5?v=fbaffbe2830b4cb7b5f6a573cb4630ef&p=9437501105a8458489640065dcb41a51&pm=s
