### ISSUE TITLE
[Bug] Renaming an application to have the same name as an existing application raises a Sentry issue

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2724]
Even though the UI shows a clean error, the backend seems to log this error externally. This error should be part of the internally logged errors.

**Comment by nidhi-nair** [comment]
@trishaanand Assigning this to you since you were taking a look at server side exceptions.

**Comment by sharat87** [comment]
If the problem here is that the error shouldn't be reported to Sentry (presumably because this is a user-error), will #2351 fix this?

**Comment by nidhi-nair** [comment]
The error I am talking about is not an `AppsmithPluginException`, neither is it wrapped by an `AppsmithException` (ref: [Sentry issue](https://sentry.io/organizations/appsmith/issues/2026372030/?query=&statsPeriod=14d)). We should ideally wrap this into an AppsmithException @sharat87

**Comment by nidhi-nair** [comment]
@sharat87 Was this resolved in another issue? I see that the Sentry issue associated to this has been marked as resolved.

**Comment by sharat87** [comment]
Sorry @nidhi-nair, not in the loop for this issue to have context. I'm not aware if it's fixed already.

**Comment by nidhi-nair** [comment]
Ah okay, I saw your user as the one that marked the Sentry issue as resolved, so asked. I'll test this on prod and triage again. :)

**Comment by sharat87** [comment]
Ohh I see. I think I misunderstood, this is my bad. The issue I fixed was with a clash in organization names, not application names. I mistakenly linked that PR (which was fixing org names) to the issue (which was about app names). Sorry for the confusion. 🤦‍♂️

**Comment by nidhi-nair** [comment]
Verified that this does not happen anymore, closing the issue.
