### ISSUE TITLE
[Feature]: Deployment of custom application with new Appsmith deployment

### ISSUE THREAD

**Issue by k0muc** [appsmithorg/appsmith#27253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be good if it were possible to specify to the docker/chart the possibility of importing a custom Application (GIT or JSON) via a variable or other parameter.
This is currently not possible.

### Why should this be worked on?

This would streamline the CI/CD process in particular for new deployments on new instances.
I am currently working with a team on several Openshift instances where we want to deploy an application built on Appsmith - and we would like to simplify the whole process as much as possible.
As much as possible, so that after deploying Appsmith (docker or charta) - we can deliver the app as quickly as possible.

**Comment by Nikhil-Nandagopal** [comment]
We're working on this as part of #git ci/cd
