### ISSUE TITLE
[Bug]: In the EE instance, branding Changes are not applied in the Instance admin email invite

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the EE instance, branding Changes are not applied in the Instance admin email invite
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/cde185a4-710a-403e-bdd3-9966d530764a">

### Steps To Reproduce

1. go to https://ee-2123.dp.appsmith.com/
2. login as admin user go to genral and add a new user as admin 
3. say suppose xx@gmail.com
4. Now go to email of xx@gmail.com and check the email format
5. The branding colours are not applied in this email

### Environment

Deploy Preview

### Version

v1.9.38

**Comment by riteshkew** [comment]
completed as part of branchding changes
