### ISSUE TITLE
[Bug]: confirm before calling not available

### ISSUE THREAD

**Issue by neozhu** [appsmithorg/appsmith#27251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/appsmithorg/appsmith/assets/1549611/e0f912bc-2839-412b-9dba-2ad3e7676269)
test by run button it's  working,
but via  click button in widget it's not available

### Steps To Reproduce

test by run button it's  working,
but via  click button in widget it's not available

### Public Sample App

https://app.appsmith.com/app/untitled-application-1/page1-64fd9e5d86fe8853288160f3/edit/widgets/an0agf0jv7

### Environment

Production

### Version

1.9.37

**Comment by LagunaElectric** [comment]
Potential duplicate of #17500

@arunvjn

**Comment by bharath31** [comment]
@satbir121 @arunvjn let's sunset this feature since it does not meet expectations.

**Comment by satbir121** [comment]
We are going to sunset this feature. It is tracked here: [Sunset Confirm Before calling a function](https://github.com/appsmithorg/appsmith/issues/29248)
