### ISSUE TITLE
[Bug]: `Internal server error` When Editing Default Roles

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#27265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The application went into a bad state and when the instance admin tries to edit a default role, an `internal server error` is returned. 
Since role configuration insists on sanity of ALL objects in the database, the API call to fetch any role configuration fails.

![image](https://github.com/appsmithorg/appsmith/assets/101268423/7493b110-b3fb-490d-8748-12f0e699d8ff)

[Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1694451309072619)
[ZD ticket](https://appsmith3239.zendesk.com/agent/tickets/531)

### Steps To Reproduce

1. Make sure you are the **instance admin**.
2. Click on **Admin Settings**.
3. Click on **Roles** in the sidebar.
4. Toggle to show the **default roles**.
5. Choose **any role** and click on it.
6. You will get an `internal server error`.

### Environment

Production

### Version

Appsmith Business v1.9.36

**Comment by RakshaKShetty** [comment]
This cant be manually tested as we cant create a scenario where the application doesn't have a default page
