### ISSUE TITLE
[Bug] env key APPSMITH_SIGNUP_DISABLED for Docker doesn't exist or doesn't work 

### ISSUE THREAD

**Issue by Gi972** [appsmithorg/appsmith#2727]
## Description

[What happened]
Hello

In docker version, When I Go on locahost , the login page is always present .
I try set the key APPSMITH_SIGNUP_DISABLED=true in docker.env
but first the key doesn't exist, so I don't know if is normal and when I add it in docker.env and I restart the server and go and the page the login is always present.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to docker.env
2. set key APPSMITH_SIGNUP_DISABLED=true
3. Save
4. Restart server

### Important Details
 - Version: [Self-Hosted  1.3.1]
 - OS: [MacOSX]
 - Browser [chrome]

Thanks

**Comment by Nikhil-Nandagopal** [comment]
@Gi972 the login / signup page will be present but it will throw an error when you try to sign up unless you have been invited by a user

**Comment by Gi972** [comment]
I make screenshoots for you 

docker.env :
![image](https://user-images.githubusercontent.com/1606247/105974391-21957e80-608e-11eb-9c44-3757a67b1586.png)


![image](https://user-images.githubusercontent.com/1606247/105974182-ef841c80-608d-11eb-94ea-33c7d1fd7cb6.png)

**Comment by Gi972** [comment]
I restart the container with this command
`
sudo docker-compose rm -fsv appsmith-internal-server nginx && sudo docker-compose up -d
`

**Comment by Nikhil-Nandagopal** [comment]
@Gi972 once you try to sign up, you should see this error
![Uploading Screenshot 2021-01-27 at 6.21.37 PM.png…]()

**Comment by Gi972** [comment]
Yes Right,

this step is mandatory?
And how  can  I to connect with admin?  with credential in docker.env?

**Comment by Nikhil-Nandagopal** [comment]
@Gi972 you can add a docker.env value for
APPSMITH_ADMIN_EMAILS=your admin email
and only this user will be allowed to sign up. The rest of the users will need to be invited by an administrator

**Comment by Gi972** [comment]
Ah ok , I understand, Maybe let's the key in the docker.env and comment it and specify at doc you need to signup to start, 
because it's confusing, we think this key disable the login and signup panel.

So, but It works that's good.
 
thanks for helping :-)

**Comment by Nikhil-Nandagopal** [comment]
@Gi972 thank you for bringing this to our notice. 
I've updated the docs below with this information. Thank you for helping make appsmith better :)
https://docs.appsmith.com/getting-started/setting-up/docker#disable-signup
