### ISSUE TITLE
[Bug]: For git imported apps where default branch is not set as master, disconnecting app times out 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#27283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For an app which is imported via git and has a default branch set as some other branch and not master , disconnecting git is throwing error

<img width="1439" alt="Screenshot 2023-09-13 at 2 14 41 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/c9139192-dc22-457e-b345-045b8e0d5901">

### Steps To Reproduce

1. Create new branch as develop and make it as default
2. Sync with appsmith app and import the app
3. Try disconnecting app , it gets stuck on modal and app becomes non functional

### Environment

Release

### Version

Release

**Comment by nidhi-nair** [comment]
Closing as irreproducible.
