### ISSUE TITLE
[Bug] Server Can Default to IPv6

### ISSUE THREAD

**Issue by osis** [appsmithorg/appsmith#2728]
## Description

Related to https://github.com/appsmithorg/appsmith/issues/1755

While playing around with server for the first time I was having trouble getting Nginx working with the server following the guide. Noticed that the server was the only thing using IPv6 and WSL2 networking was being inconsistent with how it handled it.

### Steps to reproduce the behaviour:

```
$ apt install openjdk-11-jre-headless
$ apt install maven
``` 
Run the Docker containers in https://github.com/appsmithorg/appsmith/blob/release/contributions/ServerSetup.md#setting-up-a-local-mongodb)
```
$ cd app/server
$ cp envs/dev.env.example .env

$ ./scripts/start-dev-server.sh
$ netstat -tupln

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::8080                 :::*                    LISTEN      2529/java
```
### Important Details
 - Version: https://github.com/appsmithorg/appsmith/commit/c9b3059498e8cc9b0d9d10c65ffe3b42d961402e
 - OS: Linux on WSL2
 - Browser: N/A

**Comment by osis** [comment]
I was able to fix with by adding `JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true` to my .env file

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you review this
