### ISSUE TITLE
Changes are lost when user disconnects application from Git

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#27285]
When an user disconnects their Application from Git, the application resets to the old default branch version even if that branch is deleted. Ideally it should represent the changes in the current default branch or the current branch from where user is disconnecting. 

Here are the steps to reproduce this:
1. Connect application to Git and check the default branch name e.g. `main`
2. Create a new branch `develop`
3. Make some changes in the application e.g. add a page named "MyPage"
4. Commit and push the `develop` branch
5. Go to github and change the default branch from `main` to `develop`
6. Open the application in Appsmith and sync the branches by clicking the sync icon on top of the branch list popup
7. Delete the `main` branch.
8. Disconnect from Git and check that application is in same state as it was in main branch. The "MyPage" you added in the `develop` branch is lost.

**Comment by riteshkew** [comment]
Very specific scenario and expecting to be resolved as part of new IA and native Git. Closing for now.
