### ISSUE TITLE
[Feature]: sepreate dockerifle to build and webapp and backend app. in dockerfile ,use yarn build to build 

### ISSUE THREAD

**Issue by jixianyihao** [appsmithorg/appsmith#27289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

provide dockerfile to build source , not in CI workflows

### Why should this be worked on?

it's more isloate, and easy development

**Comment by Nikhil-Nandagopal** [comment]
@jixianyihao there is a docker compose file provided in our docs
https://docs.appsmith.com/getting-started/setup/installation-guides/docker?current-edition=community_edition
