### ISSUE TITLE
Remove left side labels form WDS components

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#27298]
Do not forget to delete the prop `labelWidth` associated with this.

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/27298?planning-poker) with Zenhub @dhruvikn @ichik @jsartisan @KelvinOm

**Comment by dhruvikn** [comment]
Can we add a bit more context here? 

> labelWidth associated with this
Would be helpfl

**Comment by KelvinOm** [comment]
@dhruvikn You can find more context in [this discussion](https://theappsmith.slack.com/archives/C04P60V0VQE/p1694616665486979).
