### ISSUE TITLE
[Feature]: Dynamically render multi charts?

### ISSUE THREAD

**Issue by dingweihua** [appsmithorg/appsmith#27300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Can we support dynamically rendering multi charts based on the queried data?

### Why should this be worked on?

My use case is getting the data from one query (POST API). Then i will translate the data into multiple groups while the groups' total number is uncertain. At last, I will dynamically render each group of data into a scatter chart. So there would be multiple chart while the total number is also uncertain. Is it possible right now?

**Comment by Nikhil-Nandagopal** [comment]
@dingweihua this is possible using the customer echart widget type. You can use bindings to substitute the value.

**Comment by dingweihua** [comment]
@Nikhil-Nandagopal you mean custom chart, right? (Seems it doesn't support **APACHE ECHARTS** now) Could you give me an example or how can i build 2 charts by designing the custom fusion chart structure?

**Comment by Nikhil-Nandagopal** [comment]
@dingweihua sorry maybe I didn't understand your original question exactly. Do you want a separate chart for every data group or a different scatter plot group for every data group? It would be helpful if you could share an example design/image of what you are looking for. If you want a separate chart, you can use the list widget with a chart inside it to dynamically create a chart

**Comment by dingweihua** [comment]
@Nikhil-Nandagopal Yes, I want a separate chart for each data group. List widget seems to be a good choice. I wanna multi custom charts in the list widget. I dragged a list widget and the default data is:
[
  {
    "id": "001",
    "name": "Blue",
    "img": "https://assets.appsmith.com/widgets/default.png"
  },
  {
    "id": "002",
    "name": "Green",
    "img": "https://assets.appsmith.com/widgets/default.png"
  },
  {
    "id": "003",
    "name": "Red",
    "img": "https://assets.appsmith.com/widgets/default.png"
  }
]

Then i wanna each item be **a separate custom chart**. How could i design the item data structure?

**Comment by Nikhil-Nandagopal** [comment]
@dingweihua you have to send the data for each chart widget as an array to the list and then inside the chart, you can access its data in the chart data field as {{currentItem}}
