### ISSUE TITLE
[Bug]: Save changes confirmation modal while switching envs even if there are no changes to save

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#27313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/appsmithorg/appsmith/assets/8299030/0d752edb-8e05-4fe7-91da-35c7284e36ff)

1) Go to edit datasource config
2) Switch from production to stage
3) A confirmation popup appears to save the changes, even if there are no changes to save

Expected behaviour: Show this confirmation only if there are some changes to save

### Steps To Reproduce

1) Go to edit datasource config
2) Switch from production to stage
3) A confirmation popup appears to save the changes, even if there are no changes to save

Expected behaviour: Show this confirmation only if there are some changes to save

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
@ayushpahwa  - is this because of auto correct? fyi - I don't see this happening at my end for any DS except for [OAuth](https://github.com/appsmithorg/appsmith/issues/27317).

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/2cf0a651-12e2-484a-b99a-0c255113af2c

not reproducible anymore
