### ISSUE TITLE
[Bug] when query response is object, we get a message "no records to display"

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2732]
## Description

When the response of a query is a single object, as opposed to an array of objects, a message is shown saying "No records to display" and yet the response object is rendered fine in the UI. This message is misleading since there is indeed a response from the query execution.

### Steps to reproduce the behaviour:

Run a Firestore query with the method `Get Single Document` with a valid document path and see the response.

Notice that the response object is rendered fine, but there's a message saying "No records to display", which is misleading.

![Screenshot 2021-01-27 at 08 20 23](https://user-images.githubusercontent.com/120119/105935760-8c3bbf80-6078-11eb-9d49-7a3c851ea7ca.png)

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by sharat87** [comment]
This is now confirmed as being observed in the DynamoDB plugin as well, and is suspected to be occurring in the upcoming S3 plugin as well. In light of that, can we move it Low to High?

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal @mohanarpit This is also seen with S3 Plugin.
