### ISSUE TITLE
[Bug]: Importing an app brings up auth error even if no Auth related DS are present + auto redirection issue from home page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is observed specifically on CE When I import the attached application - Importing an app brings up auth error even if no Auth related DS are present
Also, after clicking on Home page, user is auto redirected into the application from home page

### Steps To Reproduce

Use the attached app [rename it to .json and use], import it from inside an app, and click on go to application
Note the authorization error that pops up though this app has no oauth or gsheets datasources
Also on clicking Home page, user is automatically redirected to inside the app

[SnowflakeApp.txt](https://github.com/appsmithorg/appsmith/files/12610351/SnowflakeApp.txt)

https://github.com/appsmithorg/appsmith/assets/101863839/dd5f6b29-3b8c-4a97-92fa-1902cd6dbfbe

### Environment

Production

### Version

Self Hosted

**Comment by riteshkew** [comment]
Not reproducible in v1.18 production
