### ISSUE TITLE
[Bug]: Unable to create new queries and js objects, and also unable to update existing queries and objects

### ISSUE THREAD

**Issue by azka-rafif** [appsmithorg/appsmith#27333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i create a new git branch and try to create a new query or js object, it does not give me an error message when the error popup appears, i have tried doing this in different branches and 2 different devices and 2 different web browsers (firefox and chrome)

- [ ] Device 1
![image](https://github.com/appsmithorg/appsmith/assets/140485516/6665b3d5-fe89-4da3-9a80-803c66903aa0)

- [ ] Device 2
![image](https://github.com/appsmithorg/appsmith/assets/140485516/5eb00cdb-2799-4fea-8903-9087f0b36a18)

although the error appears in the git changes when i commit it, i can't find a way to fix it except for creating a new branch and hoping it does not have this effect as well

- [ ] Git Changes 
![image](https://github.com/appsmithorg/appsmith/assets/140485516/cf9b8b00-f888-4e11-ac39-8b25f32ddb5f)

this has happened to me in all of the appsmith projects that i have developed, and the most effective way to work around this is to just create a new branch and hope this bug does not happen

### Steps To Reproduce

1. Create new app with Git integration or import from Git
2. Create new branch from main or any other branch
3. Create new query or js object
4. error pop-up appears with no error message
5. commit the new changes
6. view the git changes and see that unable to find plugin and or datasource

### Environment

Deploy Preview

### Version

Self Hosted - v1.9.10

**Comment by Nikhil-Nandagopal** [comment]
@azka-rafif could you please update to the latest version of Appsmith and let us know if this issue still persists? I'm closing this issue till then so feel free to re-open it if the issue persists
