### ISSUE TITLE
[Feature]: Multiple Environment Walkthrough/Exploration

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#27335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Implement walkthrough to improve ME discoverability as per the [designs](https://www.figma.com/file/QbU4HFVRLpWtbQQIcEFEca/Multiple-Environments-Phase-2?type=design&node-id=398-12681&mode=design&t=VmgjjgrGG3omZvB0-4)

Notion [link](https://www.notion.so/appsmith/Environments-Phase-2-9cc5f1153fe94dcf8fe86e6ede9931b6#f945dc70b8b547979e1789abb9bd0b99)

### Why should this be worked on?

Users are not able to explore new ME feature as per expectation. Hence this walkthrough will help user to get introduced to ME first time.

**Comment by ayushpahwa** [comment]
EE PR is still pending
