### ISSUE TITLE
[Bug]: Homepage UI is broken on mobile screen on release-ee

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#27339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Homepage UI is broken on mobile screen on release-ee:
![Image 2023-09-15 at 12 32 48](https://github.com/appsmithorg/appsmith/assets/28362912/e8547b54-68f4-4f0b-a75e-1c9a67304160)

Also, in certain scenarios extra space is showing up on desktop home page:
<img width="1266" alt="image" src="https://github.com/appsmithorg/appsmith/assets/28362912/961d90f9-2655-4fed-9f8a-72437549c5d5">

### Steps To Reproduce

Open home page for release-ee on mobile. See that the UI is broken.

### Environment

Release

### Version

Self Hosted - latest

**Comment by RakshaKShetty** [comment]
Fixed
<img width="519" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/e8e1895d-4cdc-4b75-8c88-39dd6fd32497">
