### ISSUE TITLE
[Bug] Dropdown widget's default is applied even if it's invalid

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2733]
## Description

The vanilla dropdown widget has a few options, of which, one have the value `VEG`. Additionally, there's a default value field which is prefilled with `VEG`. Now if we change the options array to something else, something that does NOT contain the `VEG` option, that would mean the value in the default is no longer valid. Yet, when nothing is selected in the dropdown widget, `Dropdown1.selectedOptionValue` evaluates to `VEG`, which is very confusing.

When the value provided for default value is not among the options array, can we have the `.selectedOptionValue` evaluate to something falsy (like `null` or `""`)? This is useful because oftentimes, a button's disabled state is being toggled by the existence of a valid value in the `.selectedOptionValue`.

### Steps to reproduce the behaviour:

1. Add a dropdown widget to the canvas.
2. Drag a text widget to the canvas and set it's text to `{{Dropdown1.selectedOptionValue}}`.
3. Now change the `VEG` option value in the dropdown's properties' `Options` field to something else like `VEG1`.
4. The text widget still shows `VEG` although the dropdown widget's UI indicates that nothing has been selected.

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by somangshu** [comment]
In this case the {{Select1. selectedOptionValue}} should be `null/""`

![Screenshot 2021-05-14 at 12.31.02 PM.png](https://images.zenhubusercontent.com/60583007e1e4e5398dc9ec58/6c02d089-2622-43cc-bffe-d1dc939504ea)

**Comment by somangshu** [comment]
@vicky-primathon is this related to #4230. Please help

**Comment by vicky-primathon** [comment]
@somangshu [here](https://github.com/appsmithorg/appsmith/pull/4358) , the selectedOptionValue is undefined when no default option or value is selected in dropdown

**Comment by Tooluloope** [comment]
@somangshu, Noticed  [this](https://github.com/appsmithorg/appsmith/pull/4358) solved the issue
@vicky-primathon

**Comment by somangshu** [comment]
@vicky-primathon please add this issue to the PR after verifying the above!
