### ISSUE TITLE
[Bug] Setting hidden on the endpoints port field is hiding the host as well

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2734]
## Description

In the MongoDB datasource configuration UI, we want to hide the port input fields in endpoint configuration, when the connection type is `Replica Set`. However, adding a `hidden` logic to the port inputs is hiding not just the port inputs, but also the host inputs.

Here's how the section looks like after adding the `hidden` logic:

```json
{
  "sectionName": null,
  "children": [
	{
	  "label": "Host Address",
	  "configProperty": "datasourceConfiguration.endpoints[*].host",
	  "controlType": "KEYVALUE_ARRAY",
	  "validationMessage": "Please enter a valid host",
	  "validationRegex": "^((?![/:]).)*$"
	},
	{
	  "label": "Port",
	  "configProperty": "datasourceConfiguration.endpoints[*].port",
	  "dataType": "NUMBER",
	  "hidden": {
		"path": "datasourceConfiguration.connection.type",
		"comparison": "EQUALS",
		"value": "REPLICA_SET"
	  },
	  "controlType": "KEYVALUE_ARRAY"
	}
  ]
}
```

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by ofpiyush** [comment]
@sharat87 The `KEY_VALUE_ARRAY` control is treated like 1 section, it's `hidden` is taken from the 2nd element.

It might be easier to use a separate config key for the replica set  use case.

Then you can configure `hidden` to show or hide the relevant sections.

**Comment by sharat87** [comment]
Ah that's a good workaround. Let me try that out.

**Comment by hetunandu** [comment]
@sharat87 Were you able to work around this issue?

**Comment by sharat87** [comment]
@hetunandu, honestly, I don't recall. It looks like we have set the `hidden` field on both host and port currently though.

https://github.com/appsmithorg/appsmith/blob/0ec3604eac2f2125476124fcd3ed85a995188a06/app/server/appsmith-plugins/mongoPlugin/src/main/resources/form.json#L92-L115

**Comment by Nikhil-Nandagopal** [comment]
@ayushpahwa will UQI solve the problems in the datasource form as well?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal UQI will end up revising all the base components used to render forms and will hence be looking at what kind of props we need to add for each of those. Datasources that can use new components will mostly be a side effect.
