### ISSUE TITLE
[Feature]: Use of SVG arrow in top banner design.

### ISSUE THREAD

**Issue by nis06** [appsmithorg/appsmith#27369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I recommend using an SVG  arrow icon  instead o (->)  to represent an arrow.
<img width="960" alt="Screenshot 2023-09-16 210227" src="https://github.com/appsmithorg/appsmith/assets/112106948/d7c0dd61-dbc3-4e20-8917-061e007561dc">
 

### Why should this be worked on?

Using an SVG arrow icon is a good idea because it will make the arrow look clearer and nicer on all devices, it's a modern design choice, and it gives us more flexibility in how we design things

**Comment by Nikhil-Nandagopal** [comment]
@nis06 thanks for reporting this. We track issues related to the website separately since it's not part of the open source product so I'm closing this here. Looping in @tejasahluwalia to look at this issue
