### ISSUE TITLE
[Feature]: Authenticated API AppSmith Signature to include user information

### ISSUE THREAD

**Issue by ktalebian** [appsmithorg/appsmith#27365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The AppSmith `x-appsmith-signature` does not contain any information other than expiry date. 

Ideally, we can control what other payload is put into this JWT token, or at the very least, information about the user is provided, such as email, name, etc. 

If this does not work, it would be great if the header section of the Authenticated API datastore supported templating, so you could potentially do `x-appsmith-user: {{ appsmith.user.email }}` (this does not work right now as the request just sends over the string "{{ appsmith.user.email }}".

### Why should this be worked on?

JWT token are great and should include more information!

**Comment by ooraini** [comment]
Related to #24221

**Comment by Nikhil-Nandagopal** [comment]
@ktalebian the original purpose of this was to validate the API requests coming from Appsmith. Could you tell us how you plan on using this feature?

**Comment by ktalebian** [comment]
@Nikhil-Nandagopal that's exactly what I want to do. On my app, I receive a request from AppSmith. I verify the JWT token from the `x-appsmith-signature` and confirm the request is from AppSmith. 

However, I also want to know which user made this request. So I want to be able to include a payload (basically include `appsmith.user` variable) with the JWT token so that after verifying the token, I can decode it and get the user email address.

Right now I do this by manually including `{{appsmith.user.email}}` as a header with _every_ API call.

**Comment by Nikhil-Nandagopal** [comment]
You can achieve this in thedatasource now so I'm closing this

**Comment by carlossless** [comment]
@Nikhil-Nandagopal could you elaborate on how this can be achieved in the data source now? I'm struggling to find information about it, and the docs [here](https://docs.appsmith.com/connect-data/reference/authenticated-api#headers) state that:
>The datasource configuration fields do not accept JavaScript code or bindings using mustache {{}} syntax.
