### ISSUE TITLE
PIE - JS Objects & Queries

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#27378]
## JS Objects & queries
JS objects consists of 2 parts: JS Objects itself and DB queries. In the current exported JSON these translate to `actionList` and `actionCollectionList`

### Frontend
- [ ] Export a list of IDs to be exported.

### Backend
- [ ] Get JSON for these IDs and respond with JSON

### Frontend
- [ ] Make sure that when import finishes, JS Objects are visible in the app.
- [ ] Invoke necessary redux actions for this.

### Backend
- [ ] Upon receiving a JSON with the necessary information add the JS Object to the current app of the app.

**Comment by AnaghHegde** [comment]
Backend changes - https://github.com/appsmithorg/appsmith/pull/28177
