### ISSUE TITLE
[Bug]: [Sentry CLOUD-SERVICES-B] AppsmithException in google sheets

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#27445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4303851481/?project=4505277114220544

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by NilanshBansal** [comment]
Added more logging info to sentry to know the exact root cause of this issue. 
Ref PR https://github.com/appsmithorg/cloud-services/pull/1455

We will monitor this issue for a few weeks and then get back to this.

**Comment by NilanshBansal** [comment]
https://appsmith.sentry.io/issues/4303851481/events/latest/?project=4505277114220544&referrer=latest-event

**Comment by NilanshBansal** [comment]
Work is on hold due to a critical high priority issue with mysql stale connection issue.

**Comment by NilanshBansal** [comment]
This issue is only occurring for 2 users. For one of them the occurrence is ~72% 

<img width="1332" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/e479d3cf-3597-4ea8-8171-b285e0389ff9">

**Comment by NilanshBansal** [comment]
Info received after updating the logs
<img width="1231" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/bfed984f-b4e9-4d95-8141-04c13d2e25e0">

**Comment by NilanshBansal** [comment]
The expectation was to get the plugin Id and the complete authentication response from google, but from the logs it seems that is not the case. 
We are not getting to view the complete auth response.

**Comment by NilanshBansal** [comment]
This issue is not reproducible. Also, we are not able to find much info from the logs. This issue is only occurring for some users and our hunch is that it is due to their google configuration.
To protect our sentry quota, we are disabling the logging of this issue to sentry but will continue to log this to mezmo. 
cc: @rohan-arthur
