### ISSUE TITLE
[Task]: Debug editor going to loading state with an empty toast message on cypress CI

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#27489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Original issue where this was reported https://github.com/appsmithorg/appsmith/issues/24174

Seems to be more frequent on EE. 

<img width="1200" alt="editor" src="https://github.com/appsmithorg/appsmith/assets/67054171/25d269a6-24d8-40da-9f75-b0fe070d303a">

Failed test: https://internal.appsmith.com/app/cypressdashboard/specdetails-64ec3df0c632e24c00764939?branch=master&specID=937535&testsstatus=failed

**Comment by akash-codemonk** [comment]
[Recent run with this failure after logs added](https://internal.appsmith.com/app/cypressdashboard/rundetails-64ec3df0c632e24c00764938?branch=master&workflowId=6428382607&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail)
[cypress-console-logs (1).zip](https://github.com/appsmithorg/appsmith/files/12828639/cypress-console-logs.1.zip)

**Comment by akash-codemonk** [comment]
This is happening because `fetchPluginFormConfigsSaga` is throwing an error. 

This is observed from the console logs of the  run(attached [here](https://github.com/appsmithorg/appsmith/issues/27489#issuecomment-1750255765)) where we see a log mentioning `FETCH_PLUGIN_FORM_CONFIGS_ERROR`.  This also seems to be happening at the editor initialisation phase, https://github.com/appsmithorg/appsmith/blob/release/app/client/src/entities/Engine/AppEditorEngine.ts#L193, since this is required to run successfully to initialise the editor, on failing the app stays in loading state. 

The empty toast message we see in the screenshot is because [validateResponse](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/PluginSagas.ts#L105) seems to be called with an empty response, following which we throw an blank string as an error [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/ErrorSagas.tsx#L90)

It is unclear why the api is failing occasionally on cypress CI. This will need to be debugged further from the backed for these cypress runs. 

Can this be taken up from here on by the data-integrations pod since this is related to datasource plugin forms?
cc @rohan-arthur @Aishwarya-U-R

**Comment by akash-codemonk** [comment]
@Aishwarya-U-R Please help with a link for this failure when you get one. The screenshots on the dashboard for the ones linked above are expired now. cc @sneha122

**Comment by Aishwarya-U-R** [comment]
@sneha122 - please refer to logs from [bug](https://github.com/appsmithorg/appsmith/issues/24174), since that is the original bug & we will add it to that bug incase logs are neede.

**Comment by sneha122** [comment]
Closing this as issue is resolved in https://github.com/appsmithorg/appsmith/pull/28172
