### ISSUE TITLE
[Bug]: Unable to Fork Certain Sample Apps

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#27509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Users are not able to fork certain sample apps. In the browser's console, the error `Resource Not Found` gets displayed when clicking the **Fork** button.
This happens only for a git connected App. 

### Steps To Reproduce

1. Go to [this sample app](https://app.appsmith.com/applications/61e11a42eb0501052b9fab3e/pages/61efe524be698f35db551f91?_gl=1*1j506tu*_ga*Njk4NzM4Nzc0LjE2ODU2ODg2NDM.*_ga_D1VS24CQXE*MTY5NTIxMzM3Mi4zMTkuMC4xNjk1MjEzMzcyLjAuMC4w).
2. Click the **Fork** button.
3. Select a **workspace** and click **Fork** in the popup.
4. Note that the app does not get forked or displayed in the selected workspace.

### Environment

Production

### Issue video log

https://www.loom.com/share/c8105dc1d8a248ac9f2bafa36e2c9003

### Version

Appsmith v1.9.39-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
@rahulbarwal you are looking into this right?

**Comment by rahulbarwal** [comment]
Yes @Nikhil-Nandagopal. From our initial investigations this is somehow related to git, I've involved relevant people and we are checking this.

**Comment by AnaghHegde** [comment]
@ame-appsmith Is there any other apps where we can reproduce this error?
