### ISSUE TITLE
[Bug]: The primary buttons across the instance disappear on mouse hover.

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#27501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Buttons on the welcome screen disappear on mouse hover.

### Steps To Reproduce

**Steps to reproduce:**
1. Take a latest pull from the release
2. ENter the details on first welcome/onboarding screen
3. Mouse hover on "Continue" button

Observe that the button disappears. 
A similar observation is made on the next two screens as well. 

Please find the video below.

https://github.com/appsmithorg/appsmith/assets/132880870/21303d6d-157e-42b2-a893-4dd7d672c91f

### Environment

Release

### Version

Appsmith Business v1.9.39-SNAPSHOT

**Comment by Harshask93** [comment]
Observation made on few other buttons as listed below:
1. License & Plans page :: adding a key and mouse hover on "Activate" button
2. "New" button  for creating a new application
3. "Save and Restart" button on Admin settings page
4. "Upgrade" button.

Below or the video's for reference:
https://theappsmith.slack.com/files/U04NT91Q4SK/F05THKY0XG9/screen_recording_2023-09-20_at_5.30.28_pm.mov

https://theappsmith.slack.com/files/U04NT91Q4SK/F05THL6M5UZ/screen_recording_2023-09-20_at_5.31.59_pm.mov

https://theappsmith.slack.com/files/U04NT91Q4SK/F05T7ENM48L/screen_recording_2023-09-20_at_5.31.19_pm.mov

**Comment by laveena-en** [comment]
Verified for the above mentioned scenarios on the [DP](https://github.com/appsmithorg/appsmith-ee/pull/2182#issuecomment-1727583116). Changes look good to me!
cc: @albinAppsmith

**Comment by Harshask93** [comment]
Verified on the latest release.
