### ISSUE TITLE
[Feature] Allow rotate buttons on image widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2751]
## Summary

Users want the ability to rotate an image, especially if they are using it to label data for ML purposes.

We need a property to show image rotation controls on an image widget. This should be turned off by default.

## Developer handoff file:
https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Widgets-Library?node-id=106%3A5453

**Comment by somangshu** [comment]
@areyabhishek here the controls need to be on the image once the property is enabled from the property pane? 

Also, we will need a design for this!

**Comment by areyabhishek** [comment]
Yea, we can show it on the image widget on hover. It'll need to be something that works for all sorts of image colors.

**Comment by somangshu** [comment]
Sure, We will show `rotate` icons (clockwise and anticlockwise) with a dark translucent overlay between the icons and the image (for visibility)

**Comment by techbhavin** [comment]
@somangshu, @areyabhishek  

will it be a better solution to give "rotate" property inside propertyPaneConfig of Image widget same as zoom Level? instead of showing the `rotate` icon (clockwise and anticlockwise).

**Comment by somangshu** [comment]
@techbhavin the functionality is intended for an app user and not the developer. The user of the app should be able to rotate the image given the developer has enabled the option.
