### ISSUE TITLE
[Bug]: JSobject still present after `Move`

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#27516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Move a Jsobj from page1 to page2 > The user is redirected to the JSobj in page2, but when user navigates back to page1 the Jsobj is still present.

### Steps To Reproduce

1. Have two pages
2. Create JSObject in Page1 > `Move` JSObject to Page2
3. Navigate back to Page1

### Environment

Production

### Issue video log

https://www.loom.com/share/d70e1b593d8e48fead578a855d5ca0ca

### Version

Cloud

**Comment by bharath31** [comment]
Ideal behaviour: 
- JSObject window should be closed 
- JSObject should be moved to new page

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/b24bedbe-bdd2-43d5-b728-b9af79eeffb8

issue not reproducible with the new IA
