### ISSUE TITLE
[Bug]: Helm chart uses images with vulnerabilities

### ISSUE THREAD

**Issue by felixthekraut** [appsmithorg/appsmith#27523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When scanning using Amazon's ECR service, a number of Critical and High vulnerabilities are flagged in third party images used in the Appsmith helm chart.

`helm pull appsmith/appsmith --untar --namespace appsmith`

The following images need to be updated:
1 year old: `bitnami/redis-cluster:6.2.7-debian-10-r23 -> bitnami/redis-cluster:7.0.13-debian-11-r10`

4 months old: `bitnami/mongodb:5.0.17-debian-11-r5 -> bitnami/mongodb:5.0.21-debian-11-r5`

1 year old: `bitnami/mongodb-sharded:5.0.9-debian-10-r0 -> bitnami/mongodb-sharded:5.0.21-debian-11-r5`

Here are the scan outputs:

[appsmith-ce-latest.json.txt](https://github.com/appsmithorg/appsmith/files/12677663/appsmith-ce-latest.json.txt)
[redis-6.2.7-debian-10-r23.json.txt](https://github.com/appsmithorg/appsmith/files/12677664/redis-6.2.7-debian-10-r23.json.txt)
[redis-6.2-alpine.json.txt](https://github.com/appsmithorg/appsmith/files/12677665/redis-6.2-alpine.json.txt)
[mongodb-5.0.17-debian-11-r5.json.txt](https://github.com/appsmithorg/appsmith/files/12677666/mongodb-5.0.17-debian-11-r5.json.txt)
[mongodb-5.0.9-debian-10-r0.json.txt](https://github.com/appsmithorg/appsmith/files/12677667/mongodb-5.0.9-debian-10-r0.json.txt)

### Steps To Reproduce

Scan Appsmith helm chart in Amazon ECR

### Environment

Production

### Version

Appsmith Community v1.9.33

**Comment by Mershab99** [comment]
Hi, this is also a blocker for ARM based deployments, as this, and the 'Chart.lock' file use versions of Redis and MongoDB Bitnami chart dependencies, that themselves do not link to ARM images.
