### ISSUE TITLE
[Bug]: Importing an app with many DS - on encountering GSheets, does not go through the other app config flows

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to import an application which has many datasources, when gsheets DS is encountered and authorized, instead of coming back to the import modal, other configurations are skipped and user is taken into the application

### Steps To Reproduce

1. Login to release.app.appsmith.com
2. Create a new workspace
3. Import the attached file from the import option on the home page [rename it to json and then use]
4. In the import modal, fill in configs and continue to save
5. Note that when gsheets DS is encountered and saved and authorized, On authorization, instead of coming back to the import modal, other configurations are skipped and user is taken into the application

[OldApp_DSTesting1.9.24.txt](https://github.com/appsmithorg/appsmith/files/12675747/OldApp_DSTesting1.9.24.txt)

Here is the video showing the issue:

https://github.com/appsmithorg/appsmith/assets/101863839/8779dfec-5746-44c4-a0b7-d2199316c82b

### Environment

Release

### Version

Cloud

**Comment by brayn003** [comment]
The issue seems to be related to redirection from Google Auth. This issue also occurs when just reloading the page using `cmd + r` while the reconnect datasource modal is open.
Some observations, the url briefly shows `?environment=production` and then it disappears
