### ISSUE TITLE
[Bug]: Raw Id Token is not refreshing when using OIDC with AWS Cognito

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#27524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user asked for help refreshing the access token that AWS Cognito provides when logging in with OIDC in Appsmith. Currently, the token is not automatically refreshing as it is supposed to be as stipulated in this [document](https://community.appsmith.com/content/guide/appsmith-oauth2-authentication-guide).

For logins, such as Google, an [update](https://github.com/appsmithorg/appsmith-ee/blob/fd9bf1a6669e68759a564cbfbbcdb5a667ff503c/app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomServerOAuth2AuthorizationRequestResolver.java#L97C21-L97C21) was made to the source code in which two additional parameters were incorporated that allow the access token to be refreshed.

According to this [AWS guide](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-refresh-token.html), to generate a new access token it is necessary to have the `refresh_token` that AWS Cognito provides when authentication happens. However, Appsmith does not allow access to that token, making the user unable to refresh it on their own.

### Steps To Reproduce

1. Configure an OIDC login following this [guide](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/aws-cognito).

2. Run some query by passing `Bearer <<APPSMITH_USER_OAUTH2_ACCESS_TOKEN>>` as the value of the `Authorization` header to verify that the token is working.

3. By default, It takes 60 min for the token to expire. Wait that time and try to run the query again, and you'll see the token expired.

### Environment

Production

### Version

Appsmith Business v1.9.37

**Comment by Peterkrol12** [comment]
I've reported this issue more than a week ago, do we have any updates on this? As it stands, I have to sign out and sign in every hour.

**Comment by infinitetrooper** [comment]
@Peterkrol12  - We're discussing solutions for this internally. We'll update the status of this ticket once it goes to dev.

**Comment by Peterkrol12** [comment]
@infinitetrooper - Thanks for the response, will keep an eye on the issue :)

**Comment by nsarupr** [comment]
@RakshaKShetty  can you once please verify the issue. I have tried reproducing the same on my system, but I am able to get the new access tokens, once the earlier token expires.
If you are able to reproduce the issue, can you please help me with the steps.
cc: @infinitetrooper @trishaanand @deepikaappsmith

**Comment by infinitetrooper** [comment]
@Peterkrol12  - can you help us out with your config? Are you using Cognito user pool directly or are you using Cognito Federated Identities to connect external IdP through Cognito?

**Comment by Peterkrol12** [comment]
@infinitetrooper - Sure!

We are using Cognito user pool directly, no (external) federated identities are being used, see screenshot below for our app client configuration.

![image](https://github.com/appsmithorg/appsmith/assets/42931791/60902dff-c422-4a78-b212-f11df8960c88)

**Comment by nsarupr** [comment]
@felix-appsmith can you please setup some time using this [calendly link](https://calendly.com/nilesh_appsmith/30min)? Let's get on a call and then take this forward. 
Also, can you please help us with the version of Appsmith you are on?

**Comment by nsarupr** [comment]
Sorry for the confusion. @Peterkrol12, please use the above calendly link to schedule a call. Also please provide the information asked above.

**Comment by nsarupr** [comment]
@Peterkrol12  is using `appsmith.user.rawIdToken` for authenticating their API Calls, and it is not getting refreshed.
At the moment, we are only refreshing the Access token, and will need to add a flow for refreshing the `rawIdToken`.

**Comment by Peterkrol12** [comment]
Fixed in version `v1.9.44`
