### ISSUE TITLE
[Bug] Table Column Image shows 'Invalid Image' for base64 encoded images

### ISSUE THREAD

**Issue by WillemJann** [appsmithorg/appsmith#2753]
## Description

For a table column with data type 'Image', base64 encoded images are not rendered:

![image](https://user-images.githubusercontent.com/3678597/106114359-c4620180-614f-11eb-8214-f4d1bf69f252.png)

### Steps to reproduce the behaviour:

1. Create a widget 'Table'.
2. Add data, with in one column some base64 encoded images.

![image](https://user-images.githubusercontent.com/3678597/106114717-2c184c80-6150-11eb-9fb9-950228cc2ba3.png)

3. Change the table column data type to 'Image'.

![image](https://user-images.githubusercontent.com/3678597/106114812-4a7e4800-6150-11eb-889b-e8ee34f6c8c2.png)

4. Observe the above error. No images are shown, but the error "Invalid ImageInvalid Image".

### Important Details
 - Version: Self-Hosted v1.3.1
 - OS: Windows 10
 - Browser: Chrome 88

**Comment by osis** [comment]
FYI, I have a version of this working.

![Capture](https://user-images.githubusercontent.com/347097/106216941-2fd4bf00-61a2-11eb-95a8-23ca3afd5a59.PNG)

![Capture2](https://user-images.githubusercontent.com/347097/106216954-35320980-61a2-11eb-9eda-a5843cf34f8f.PNG)

**Comment by riodeuno** [comment]
Fixed in #2769
