### ISSUE TITLE
[Bug]: Unable to import attached json file in the airgapped image

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to import the attached application, I get an error to the effect unable to connect to server.

### Steps To Reproduce

1. Take the pull of the airgapped image, and set it up without internet
2. Try to import the attached file [rename it to json]
3. Note that import does not work and error pops up.

[OldApp_DSTesting1.9.24.txt](https://github.com/appsmithorg/appsmith/files/12682453/OldApp_DSTesting1.9.24.txt)
<img width="1151" alt="Screenshot 2023-09-21 at 2 04 04 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/765837e4-2747-4571-b5b6-e73aa17423c6">

Note: The attached app has Airtable / GSheets and other SAAS plugins. Since Airgapped does not support these plugins, if thats the reason for this failure, then an appropriate message needs to be given - or there should be some way of handling that portion in the import modal. 

### Environment

Release

### Version

Self Hosted

**Comment by infinitetrooper** [comment]
It's because of the unsupported DS

**Comment by btsgh** [comment]
In the current airgapped regression also we are seeing the above issue, and also, sometimes we see a broken UI, which is not such a great user experience. Though it is a case with unsupported datasources, it should be handled gracefully. 

https://github.com/appsmithorg/appsmith/assets/101863839/036d9f61-a8c9-486d-8031-2c03d2341095

**Comment by infinitetrooper** [comment]
@btsgh  - GSheets is not supported and should not exist in Airgapped apps. Any failues because of that can be ignored.
