### ISSUE TITLE
[Bug] Misleading title to datasource view pane

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2754]
## Description
'Datasource Connected' seems to be a constant heading to the datasource view pane. Such a heading does not make sense when the datasource is invalid. For example: I have not filled any of the fields in the datasource below.

![image](https://user-images.githubusercontent.com/5298848/106117483-166b4d00-6179-11eb-9b52-66df20d398fa.png)

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create any DB datasource.
2. Do no fill any fields, just go back to the datasource view pane in the least valid state.
3. create a query with created datasource
4. go to created datasource from entity explorer (left navigation bar)
5. datasource page shows "Datasource Connected"

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by nidhi-nair** [comment]
Design changes will be required to make the objective of this text clear. Do we want to indicate whether the datasource was successfully configured or whether the test was successful? Current design makes it seem like the datasource test was always successful.

**Comment by ApekshaBhosale** [comment]
text change from "Datasource connected" to "Datasource Saved"
file - [Connected.tsx](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/DataSourceEditor/Connected.tsx)

**Comment by vj-codes** [comment]
@ApekshaBhosale I have created a PR #8028
Please have a look, thankss in advance:)
