### ISSUE TITLE
Remove storybook from EE 

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#27541]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3JCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--718d7b4903bb97af374dbd3b086a5ce1cbe9fdb7/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202023-09-21%20%D0%B2%2012.07.34.png)

**Comment by ichik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/27541?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm
