### ISSUE TITLE
[Bug][Airgap]: Icons of datasource is missing from one-click binding dropdown

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#27555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Airgap instance: 
<img width="696" alt="no icon of datasource" src="https://github.com/appsmithorg/appsmith/assets/95341241/af30d893-4e4b-4bfb-a418-bb57044b6208">

Prod: 
![image](https://github.com/appsmithorg/appsmith/assets/95341241/cf3db81c-22b4-4e7b-ba81-85cb7f1aca83)

**Note**: Happening on Table & Select widget's one-click binding

### Steps To Reproduce

1. D&D Table widget
2. Click on Table data dropdown
3. Observe that there is no icon visible for of any of the datasource in one-click binding dropdown

### Environment

Release

### Version

Airgap

**Comment by sbalaji1192** [comment]
@chandannkumar Can you please test this?
