### ISSUE TITLE
[Bug]: Cell missing value when "*" is in the table widget's column name

### ISSUE THREAD

**Issue by BorenTsaiAMD** [appsmithorg/appsmith#27572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bug:
When this particular string appears in table widget's column name, cell values will disappear
The string that causes the problem: "*" (double quote, star, double quote connected together)
use case :
The application that I'm developing is a table builder that lets the user build a table template which the user can define column names / how many rows should be in it. The users will define the column name so they made this column name: `Answer"*"`
how the fix will be useful for you:
Not have the cell value missing.
Additional information that I think might help:
![image](https://github.com/appsmithorg/appsmith/assets/132530265/b5c85bcf-1bac-4ea5-b492-f7c2bb050c88)
![image](https://github.com/appsmithorg/appsmith/assets/132530265/243783a6-a54f-496a-9655-e40a87f2c5d6)
`[
  {
    "RowName": "Row\"*\"",
    "Answer*\"\"": "(Editable Text)"
  }
]
This is the function's return value.`

### Steps To Reproduce

Have a table widget's data like this:
`[
  {
    "RowName": "Row\"*\"",
    "Answer*\"\"": "(Editable Text)"
  }
]`

### Environment

Production

### Version

1.9.12

**Comment by Nikhil-Nandagopal** [comment]
@BorenTsaiAMD you need to escape the quotes in the table by replacing " with \"
