### ISSUE TITLE
[Bug]: [intermittent ]"Error network" error is displayed when the user deploy the apps in air-gapped instance

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

"Error network" error is displayed when the user deploy the apps in air-gapped instance
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/17a99c1b-6fca-4205-b8a3-634e33499724">

### Steps To Reproduce

1. pull airgap image open the instance in firefox sign-up with new user
2. edit the app 
3. Drag and drop the table widget
4. Now go to home page click on launch button
5. The error network page is displayed instead of displaying deployed app

### Environment

Release

### Version

v1.9.39

**Comment by ankitakinger** [comment]
Closing this issue as it is no longer reproducible on promotion branches and release branch.
