### ISSUE TITLE
[Bug]: Generate page with data is not working for Mongo DS, if Environment is Staging in switch env dropdown

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On trying to generate page with data with mongo DS, from Staging Environment, an error is thrown when we choose a specific collection and click generate page [disease / aanime / anime etc]
Note, these same collections work if we configure this DS for production and run generate page with data from there.

### Steps To Reproduce

1. Login to appsmith
2. Create a mongo DB ds, and configure prod and staging. Use the servers and credentials notion doc mongo DS details for production.  
3. Use this configuration for staging - mongodb+srv://****:****@cluster0.sn2li.mongodb.net/myFirstDatabase?authsource=admin&minpoolsize=0 
4. Ping me for credentials
5. Now switch env to staging
6. Do a Generate page with data, and choose collection as one of the above mentioned ones [disease / aanime / anime]
7. Click generate page and note the error that pops up. User is unable to generate page with data in this case.
FYI - the same ds if configured for prod, from prod env dropdown, the page gets generated successfully

https://github.com/appsmithorg/appsmith/assets/101863839/314b900a-8ede-4093-aae9-6cce3ddd8e02

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
we are deprecating generate page, so closing this issue
