### ISSUE TITLE
[Bug]: In welcome tour, the 4th and 5th steps, property name reference is incorrect

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The info talks about Default Text property, but the actual property name in the property pane is Default Value

### Steps To Reproduce

1. Login to appsmith and click on Welcome Tour
2. Go through the first 3 steps
3. On the 4th and 5th step, the info to the user talks about **Default Text** property, but the actual property name in the property pane is **Default Value**
<img width="1418" alt="Screenshot 2023-09-26 at 10 47 38 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/5480762f-93af-4d8a-bed8-d22daaf78344">

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
welcome tour has been deprecated, so closing this issue
