### ISSUE TITLE
[Task]: Add analytics points for MySQL SSH tunnel usage 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#27616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Add / update analytics event for datasource save with SSH tunnel for MySQL.

### Steps To Reproduce

NA

### Environment

Production

### Version

cloud, self hosted

**Comment by rohan-arthur** [comment]
closing this with ref to #27767
