### ISSUE TITLE
[Bug]: Forking an application gives an unexpected error

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to fork the attached application, an unexpected error pops up. 

### Steps To Reproduce

Use the following link to access the app. 
Try to fork with 
Have shared it with @nsarupr @dipyamanbiswas07 

https://ee-2453.dp.appsmith.com/app/rbac-me/page1-65119bc00d18687a5ed05707

### Environment

Deploy Preview

### Version

Cloud

**Comment by btsgh** [comment]
Also, after this flow, Enterprise -> Community -> Business -> Enterprise 
Seeing an error on forking an application. Video below describes the issue.
https://github.com/appsmithorg/appsmith/assets/101863839/0ddbb773-7047-4a29-9dfd-4b0199dedc65

Steps - 
Login to the appsmith instance and import the RBAC-ME app [attached json [rename txt to json]]
Create a new workspace and fork above app into that workspace
Note the error

[RBAC-ME.txt](https://github.com/appsmithorg/appsmith/files/12765526/RBAC-ME.txt)

**Comment by abhvsn** [comment]
@btsgh can you list down the steps as we have recreated the DP, I'm not seeing the issue for import as well as fork workflow.

**Comment by btsgh** [comment]
@abhvsn - I am not seeing this error now for import or fork.

**Comment by abhvsn** [comment]
@btsgh closing this issue in that case? Please feel free to open if you face this.
