### ISSUE TITLE
[Bug]: On downgrading instance to community edition, where more than 3 apps are connected to private repos doesn't show repolimit exceed modal

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#27639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we downgrade from enterprise to community edition, and have 4 apps connected to private repos, the apps work fine, ideally for community edition we should allow only 3 apps in a workspace

### Steps To Reproduce

1. For https://ee-2453.dp.appsmith.com connect 4 apps to git (prviate repos)
2. Downgrade to community edition
3. Observe all 4 apps in workspace works fine

### Environment

Deploy Preview

### Version

https://ee-2453.dp.appsmith.com

**Comment by abhvsn** [comment]
@Parthvi12 can you check if you are able to commit from any of the app connected with the private repo?

**Comment by Parthvi12** [comment]
Not an issue, app's commit and push fails which is expected, for improved error message, creating another ticker.
