### ISSUE TITLE
[Bug]: The admin looses the access to admin setting when user downgrade from paid plan to free plan

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The admin looses the access to admin setting when user downgrade from paid plan to free plan

### Steps To Reproduce

1. login to https://ee-2453.dp.appsmith.com/
2. Add the paid license and now create some apps 
3. now expire you license from LMA app
4. Now from the downgrade/upgrade page
5. choose the community version 
6. Now once the instance is downgraded the user lost the access to the admin setting

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by RakshaKShetty** [comment]
This issue is fixed

**Comment by dipyamanbiswas07** [comment]
Closing this.
