### ISSUE TITLE
[Bug]: Getting error if using json_extract in a MySQL query: Cannot invoke "Object.getClass()" because "columnValue" is null

### ISSUE THREAD

**Issue by patrioticcow** [appsmithorg/appsmith#27645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Getting error if using `json_extract` in a MySQL query, or just querying a field that is of `json` type.

```
SELECT
	id,
	createdAt as date,
	json_extract(details, '$.editor') AS editor
FROM
	`User`
ORDER BY
	id DESC
LIMIT 10
```

### Steps To Reproduce

1. Run a MuSQL query on a table that has a json type field

## Workaround
https://github.com/appsmithorg/appsmith/issues/27645#issuecomment-1738373167

### Environment

Production

### Version

self host, V1.9.37.1

**Comment by subrata71** [comment]
@patrioticcow 
Could it be due to the `null` value returned by `json_extract(details, '$.editor')`?

Can you please give the following queries a try?

### Using IFNULL

```
SELECT
	id,
	createdAt as date,
	IFNULL(json_extract(details, '$.editor'), 'N/A') AS editor
FROM
	`User`
ORDER BY
	id DESC
LIMIT 10
```

### Using COALESCE

```
SELECT
	id,
	createdAt as date,
	COALESCE(json_extract(details, '$.editor'), 'N/A') AS editor
FROM
	`User`
ORDER BY
	id DESC
LIMIT 10
```

**Comment by sumitsum** [comment]
As Subrata has mentioned seems like the issue occurs when the queried key is missing from the column JSON value returning null as the value against the key: 
![Screenshot 2023-09-28 at 8 17 31 AM](https://github.com/appsmithorg/appsmith/assets/1757421/bd2dc06c-677d-47e8-b920-7a954e97a72e)
![Screenshot 2023-09-28 at 8 24 09 AM](https://github.com/appsmithorg/appsmith/assets/1757421/27a96e60-6798-4516-8b8b-f839dadca686)
![Screenshot 2023-09-28 at 8 27 12 AM](https://github.com/appsmithorg/appsmith/assets/1757421/db643799-4ef8-42eb-bb52-52c0fcafa8dd)

**Comment by sumitsum** [comment]
Hi @patrioticcow sharing a work around, please mention here if this helps. Re-writing the query like this should filter out all the null value results: 
```
select json_extract(c_json, '$.key3') as result from test_json_type where json_type(json_extract(c_json, '$.key3')) != 'NULL';
```
