### ISSUE TITLE
[Feature] Add a generic S3 plugin that can be used with any cloud storage service that uses the S3 protocol

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2765]
## Summary

The AWS S3 plugin is currently designed to be used for AWS endpoints. Most other cloud storage providers have enabled compatibility with AWS APIs. This enhancement requests making the S3 endpoint configurable to support other providers.

## Motivation

Users may have a preference towards certain providers.

## Additional Context

[Here](https://www.coralnodes.com/amazon-s3-alternatives/) is a list of additional cloud storage providers that use the same protocol. From this list, a few have documentation that supports using their APIs using the AWS SDK.
- [Wasabi](https://wasabi-support.zendesk.com/hc/en-us/articles/360021962192-How-do-I-use-AWS-SDK-for-Java-v2-with-Wasabi-)
- [DigitalOcean Spaces](https://www.digitalocean.com/docs/spaces/resources/s3-sdk-examples/)
- [Linode](https://www.linode.com/community/questions/20585/s3-object-storage)
- [DreamObjects](https://help.dreamhost.com/hc/en-us/articles/215694518-Sample-Java-Code-Using-DreamObjects-S3-compatible-API)

**Comment by areyabhishek** [comment]
@sumitsum Will this be compatible with Upcloud? https://upcloud.com/community/tutorials/object-storage/ I got a request on Intercom for Upcloud. How easy is it to use the same S3 connection for different providers?

**Comment by hawisizu** [comment]
I would want to be compatible with OVH: https://docs.ovh.com/gb/en/public-cloud/getting_started_with_the_swift_S3_API/
