### ISSUE TITLE
[Bug]: Notification email should be handled based on the user downgrade from Paid to free plan

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Notification email should be handled based on the user downgrade from Paid to free plan

### Steps To Reproduce

1. Go to https://ee-2453.dp.appsmith.com/applications
2. Now image the user is in Paid instance 
3. go to edit profile page 
4. now click on reset password
5. Now the email will be sent to user with the custom "instance name"
6. now downgrade the instance 
7. go to edit profile page 
4. now click on reset password
5. The email sent for password reset should not have a custom  instance name instead should have a default instance name

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by abhvsn** [comment]
@nsarupr is this also resolved and merged to release?
