### ISSUE TITLE
[Bug]: API Screen UI - the run button, and edit datasource buttons are touching the edge - there is no spacing

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we click on new rest api or oauth api - the run button and edit ds button is touching the edge of the chrome page. This was not the case before. There should be a spacing between the buttons and the edge of the page

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/cef57cc1-0285-416c-86e9-14d1dad002ce

### Environment

Release

### Version

Cloud

**Comment by RakshaKShetty** [comment]
Fixed
<img width="742" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/60cad137-382c-4bec-9d3f-e667daf9f77d">
