### ISSUE TITLE
[Bug][intermittent ] The user sees the unable to pageid or layout id toast when they are just navigate to home page from edit mode

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user sees the unable to pageid or layout id toast when they are just navigated to home page from edit mode
![image](https://github.com/appsmithorg/appsmith/assets/45958978/910d417a-dc76-4db7-814a-fda9e722980c)

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com/
2. click on edit on any one app 
3. now go back to home page 
4. this is very Intermittent and not reproducible all the time

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by dipyamanbiswas07** [comment]
can you post which Network call is failing here?

**Comment by btsgh** [comment]
https://github.com/appsmithorg/appsmith/assets/101863839/d87d3f74-5b6a-4f99-928b-7699c24629e4

**Comment by btsgh** [comment]
@dipyamanbiswas07  - does this recording help? I do not see any network call in red / failing.. but console has these errors
