### ISSUE TITLE
[Bug]: When the https://ee-2453.dp.appsmith.com dp instance is kept ideal for long time the user is redirected to the license page 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the https://ee-2453.dp.appsmith.com dp instance is kept ideal for long time the user is redirected to the license page on the browser refresh the user is navigated to application page

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com
2. keep the tab ideal for some time 
3. Then go to the Tab now the user is navigated to the license page

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by abhvsn** [comment]
@RakshaKShetty can you provide the network logs. Also, what's the idle time we are looking at here?

**Comment by pranayagarwal96** [comment]
The banner will be removed if the instance is kept idle for sometime (Works on refresh) - @Harshask93
