### ISSUE TITLE
[Bug]: Checkbox when being used in canvas is getting focus even on click

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#27677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we used our new WDS checkbox, the checkbox is getting the focus on click as well. The focus should only come on when using keyboard. 
Also, the checkbox outside canvas works fine.

https://github.com/appsmithorg/appsmith/assets/6636360/72f49e30-4cac-49e2-be16-7824b3a5be74

### Steps To Reproduce

Drop the newly made checkbox widget v2, and drop it on canvas. and click on it multiple times. You will see the focus styles coming up.

### Environment

Production

### Version

Latest

**Comment by raghav1030** [comment]
Heyy I'd like to work upon this issue. Could you please assign it to me?

**Comment by KelvinOm** [comment]
It is played the same way for Radio and Switch
