### ISSUE TITLE
[Task]: Modify custom JS library doc to include ESM support

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#27680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Now that we've started supporting ESM libraries, the documentation needs to be updated to reflect this additional support

**Comment by arunvjn** [comment]
PR created [here](https://github.com/appsmithorg/appsmith-docs/pull/1878)

**Comment by arunvjn** [comment]
Completed https://github.com/appsmithorg/appsmith-docs/pull/1878
