### ISSUE TITLE
[Bug]: Seeing internal server error on the application on upgrading to Business edition from Community

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After upgrading to business edition from community edition, we are seeing an internal server error when we navigate anywhere in the application, or home page, or logout.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/7b8976f4-d1d3-4731-8ac3-c8ed36a66cfe

https://github.com/appsmithorg/appsmith/assets/101863839/340be38d-96f9-4351-aa2f-8d205ad067a2

### Environment

Deploy Preview

### Version

Cloud

**Comment by dipyamanbiswas07** [comment]
can you post which Network call is failing here?

**Comment by btsgh** [comment]
Will try to get details and post as soon as we see the issue again

**Comment by dipyamanbiswas07** [comment]
Sure Aparna, thank you,

**Comment by RakshaKShetty** [comment]
closing the issue as we are not seeing it after the DP updates
