### ISSUE TITLE
[Bug]: OIDC access token used in Authenticated APIs not refreshed

### ISSUE THREAD

**Issue by ifc** [appsmithorg/appsmith#27699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When logging in to Appsmith via OIDC, the access token retrieved by using <<APPSMITH_USER_OAUTH2_ACCESS_TOKEN>> for Authenticated API datasources expires after an hour and is not refreshed. This causes API calls that are reliant on this token to fail.  

### Steps To Reproduce

1. Set up authentication via [OIDC through Otka](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/openid-connect-oidc/okta) . Refresh token is set here.
2. Create a new Authenticated API Datasource. For authentication type, select 'Bearer token'. For the token itself, enter '<<APPSMITH_USER_OAUTH2_ACCESS_TOKEN>>' as instructed [here](https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/json-web-tokens-jwt#access-token)
3. Create an API from this datasource. Authentication will work for the first hour, but fail afterwards because the access token has expired.
4. As a temporary way to address, you can edit the above data source by reentering '<<APPSMITH_USER_OAUTH2_ACCESS_TOKEN>>' and saving. This seems to update the token and the application will work for all users for the next hour.

### Environment

Production

### Version

Self Hosted v1.9.32

**Comment by infinitetrooper** [comment]
@rohan-arthur  - I know we don't intentionally support this, can you shed more light on why we don't? Thank you

**Comment by trishaanand** [comment]
This feature works as expected as long as OIDC is configured correctly. Adding `offline_access` scope in OIDC configuration on Appsmith triggers the refreshing of access token once it expires.

**Comment by trishaanand** [comment]
Re-opening this issue because the OIDC access token variable when stored in datasource does not get updated.
