### ISSUE TITLE
[Bug]: Message listener functions shows up as an error on JS objects

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#27691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Message listener functions shows up as an error on JS objects but works fine on trigger field of a widget

### Steps To Reproduce

1. Go to GAC DP https://ee-2453.dp.appsmith.com/
2. Type in `windowMessageListener()` on a widget trigger field and JS object and observe the error on the object

### Public Sample App

https://ee-2453.dp.appsmith.com/

### Environment

Deploy Preview

### Version

Cloud

**Comment by dipyamanbiswas07** [comment]
Message listener not available on this DP
@RakshaKShetty

**Comment by dipyamanbiswas07** [comment]
Message listener not available on this DP
@RakshaKShetty
