### ISSUE TITLE
[Bug]: The admin email id's are not displayed on the admin settings page.

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#27717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

All the email id's which has admin access should be displayed in the field but currently the field is empty.

### Steps To Reproduce

1. Login with admin credentials
2. Navigate to "Admin settings" page

Observe the "Admin Email" field 
![Instance_Admin_mail](https://github.com/appsmithorg/appsmith/assets/132880870/1ef4d10a-6370-4171-a801-81007bed7b8f)

DP: https://ee-2453.dp.appsmith.com

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.39-SNAPSHOT

**Comment by RakshaKShetty** [comment]
This issue is fixed clsoing the issue
