### ISSUE TITLE
[Bug]: Unable to see the Appsmith Watermark on deploy [Upgrade / Downgrade flow: Enterprise -> Community -> Business -> Enterprise]

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the 1click deploy preview, Though Show appsmith watermark is checked, unable to see the water mark on deploying the app. 
Upgrade / Downgrade flow: Enterprise -> Community -> Business -> Enterprise

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/f6627b21-1292-4e7c-bfcd-1d304030ef0c

### Environment

Deploy Preview

### Version

Cloud

**Comment by dipyamanbiswas07** [comment]
https://github.com/appsmithorg/appsmith/assets/26247571/52e4fcb2-5146-4a46-9016-64be8e3cce2d
