### ISSUE TITLE
[Bug] First tab of the tabs widget is perpetually in a loading state

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2772]
Due to a bad migration, the first tab in the tabs widget went into a bad state

**Comment by jsartisan** [comment]
@hetunandu Any steps to reproduce this?

**Comment by hetunandu** [comment]
> @hetunandu Any steps to reproduce this?

Not possible since you will need an older version of appsmith and run a migration on that. Added a fix for this
