### ISSUE TITLE
[Bug]: Show navbar Toggle under App settings>Navigation Turned ON Is Not Persisted 

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#27721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When turning on the **Show navbar** toggle in **App settings**>**Navigation**, it does not show the child options (Orientation, Variant, etc.), and the setting does not persist after moving away from the **Navigation** pane, nor does the navigation bar show up in the deployed view.

![image](https://github.com/appsmithorg/appsmith/assets/101268423/1cb39f26-18b6-4e9b-a8d4-384109ddcb7f)

More details (screen recording, shared app) in the [Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1695980383566339).

### Steps To Reproduce

1. Go to **App settings**>**Navigation**.
2. Turn on the **Show navbar** toggle.
3. Move away from the **Navigation** pane.
4. Come back to the **Navigation** pane and note that the **Show navbar** is OFF.

### Environment

Production

### Version

v1.9.37.1

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith I'm able to see it and it seems to be working. Please share a video
