### ISSUE TITLE
[Task]: Junit Test cases

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#27742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by TanyaAgarwal28** [comment]
Hi @sneha122 , Can you please provide more insights on this issue? Will like to pick it up.

**Comment by sneha122** [comment]
Hi @TanyaAgarwal28 This task is to write JUnit test cases for an ongoing feature of [Rate limit](https://github.com/appsmithorg/appsmith/issues/27745), This may a little complex to pick it up as feature is not complete yet, meanwhile please feel free to check out the [Good first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22)

**Comment by TanyaAgarwal28** [comment]
Oh okay thanks
