### ISSUE TITLE
Create new WDS table widget

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#27763]
This should be just a fork of the current table widget. This is necessary to start testing Anvil. Later we will add tokens to the table.

**Comment by Aditya-Chaurasia11** [comment]
can you please assign this issue to me?

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/27763?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm
