### ISSUE TITLE
[Bug]: The user sees 503 error when he is downgraded from EE to CE by removing the license from license & billing page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user sees 503 error when he is downgraded from EE to CE by removing the license from the license & billing page

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com/
2. Make sure the instance have EE license 
3. now go to admin setting license & billing tab 
4. click on remove license and downgrade 
5. The user sees error on the UI and then the instance goes with 503 error for some time 

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by abhvsn** [comment]
@RakshaKShetty checking if the form login was disabled on this instance before the downgrade happened? This is expected as we haven't handled the downgrade migrations on client side as yet and @dipyamanbiswas07 is planning to pick this up as an upcoming task.

**Comment by RakshaKShetty** [comment]
This is fixed
