### ISSUE TITLE
Create new WDS Text widget

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#27769]
Property pane requirements — https://www.notion.so/appsmith/Widgets-Properties-Audit-3832f6a7be5f47cc9bfa3bd1ddae31fa

Will we separate current implementation to Text widget and Html widget? cc @ichik

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/27769?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm

**Comment by ichik** [comment]
@KelvinOm the possibility to write arbitrary HTML shouldn't exist on the text widget definitely. Whether we add HTML widget to WDS is less clear to me. That would be definitely needed if we would support automatic migrations.

**Comment by jsartisan** [comment]
Closing as it is done.
