### ISSUE TITLE
[Feature]: [one click binding] table and columns dropdown should have search functionality

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#27772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

<img width="275" alt="Screenshot 2023-10-03 at 1 42 37 PM" src="https://github.com/appsmithorg/appsmith/assets/5328605/909df602-e705-4b18-9a2a-eccf4cac92fc">
The table and column dropdown doesn't have searchable functionality, as a result, it is difficult to use it when there are a lot of options available.

### Why should this be worked on?

Improves usability of the whole feature.

**Comment by dilippitchika** [comment]
Also remove the icons in the select components (not menu component), making it easy to search. The icon doesn't hold any significance.
