### ISSUE TITLE
[Feature]: Update Twitter Icon 

### ISSUE THREAD

**Issue by pragyamishra56** [appsmithorg/appsmith#27796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When updating an icon with colors or making changes to styles, it's common to adjust the associated CSS styles to ensure proper alignment, positioning, or to maintain a cohesive design.

### Addressing a Pain Point: 
If the feature request addresses a known issue or pain point for users, highlight how implementing it would resolve or mitigate those problems.

### Staying Competitive: 
In a competitive landscape, features that enhance a product's functionality or aesthetics can contribute to staying competitive in the market.

### Aligning with User Expectations: 
If users have certain expectations based on current industry trends or standards, fulfilling these expectations can be a strong rationale for the feature.

### Bug Fix or Improvement: 
If the feature request is tied to fixing a bug or improving existing functionality, emphasize the impact it would have on the stability or performance of the application.

### Strategic Importance: 
If the feature aligns with the long-term strategy or vision for the product, emphasize how it contributes to achieving broader goals.

### Feature should be added
![Screenshot 2023-10-04 000751](https://github.com/appsmithorg/appsmith/assets/115208912/9ce0b165-d127-4cbf-915a-a9cd94db26fc)

**Comment by Nikhil-Nandagopal** [comment]
Hi unfortunately our website is not part of our open source project so we maintain these issue separately. Closing this for now

**Comment by pragyamishra56** [comment]
@Nikhil-Nandagopal  Have no issues but if you have any good first issue please assign it to me I'm interested in working on the issue. Could you please confirm if it's still open and if I can get started on it? I want to contribute
