### ISSUE TITLE
[Bug]: Unable to login to app with github user when github is configured

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On configuring SSO with Github, I am unable to login with the github login it asks for credentials, authcode, but then brings up an internal server error. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/6131226e-c811-4cce-a765-3e3e3f76f550

### Environment

Deploy Preview

### Version

Cloud

**Comment by btsgh** [comment]
<img width="1246" alt="Screenshot 2023-10-04 at 11 50 33 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/46ad496d-fe23-41a3-b1fb-5c44e2f4b961">

**Comment by abhvsn** [comment]
As this is not reproduceable can we close this ticket?

cc: @btsgh @RakshaKShetty

**Comment by RakshaKShetty** [comment]
Not seeing this issue with the latest changes closing the issue
