### ISSUE TITLE
[Bug]: When the user is downgraded and invited as Admin for a CE instance in the email subject body the instance name is displayed  as the custom instance name that was present in the EE 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user is downgraded and invited as Admin for a CE instance in the email subject body the instance name is displayed  as the custom instance name that was present in the EE 
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/04c22b42-e534-4542-8b72-495e695f155a">

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com
2. now add a license key either BE/ EE
3. Now go to the admin setting in the general tab add the instance name as Test
4. Now Remove the license and go to ce Version
5. go to admin setting in general tab add a user email id
6. Go to the added user email and check the email in the subject
7. The instance name is displayed as a custom email that we have used in the EE instance

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by abhvsn** [comment]
@nsarupr I think you have already resolved this, did the PR got merged for this fix?

**Comment by RakshaKShetty** [comment]
This issue is fixed 
<img width="707" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/a647f92c-5cb1-47cb-8bba-1392a578af35">
