### ISSUE TITLE
[Task]: Add an Anvil Layout Default Config api for all widgets and use only whats needed for anvil.

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#27806]
code changes look good, But should we add an Anvil Layout Default Config api for all widgets and use only whats needed for anvil.
@prsidhu @riodeuno

_Originally posted by @marks0351 in https://github.com/appsmithorg/appsmith/pull/27700#pullrequestreview-1656664492_

**Comment by marks0351** [comment]
clsoing this in favour of #28401
