### ISSUE TITLE
[Bug]: ModifiedBy key returns incorrect value when another user edits the app

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#27838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

in the API `/api/v1/applications/new`, the ModifiedBy key is always returning the user who first created the app

If another user with the edit access updates the app, theModifiedBy value doesn't update.

### Steps To Reproduce

https://www.loom.com/share/962b644de3544ad4b45e21005338985a

### Environment

Production

### Version

Cloud/Selfhosted

**Comment by kamakshibhat-appsmith** [comment]
Related to https://github.com/appsmithorg/appsmith/issues/26120

**Comment by deepika-appsmith** [comment]
This issue is resolved and not producible, attached a video for reference.

https://github.com/appsmithorg/appsmith/assets/161307325/0c01de66-8804-4b18-ad22-28561b0fe96f
