### ISSUE TITLE
[Bug]: On opening an application at random on the 1click DP, unable to find environment id error pops up

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open an application on the 1click DP , I see the error "unable to find environment id" 

### Steps To Reproduce

1. Login to the 1click DP 
2. Click on any of the application [old app DS app or rbac me app]
3. Unable to find environment production error comes up

<img width="1057" alt="Screenshot 2023-10-05 at 2 10 33 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/d83bdfa6-51ad-46a0-a215-12d84d29fe83">

Log trail:
[log.txt](https://github.com/appsmithorg/appsmith/files/12816427/log.txt)

### Environment

Deploy Preview

### Version

Cloud

**Comment by dipyamanbiswas07** [comment]
@abhvsn  can you check why the api is failing in this case?

**Comment by abhvsn** [comment]
@RakshaKShetty @btsgh can I get the re-produceable steps if possible?

**Comment by btsgh** [comment]
@abhvsn It seems to be flaky. Intermittently reproducible, but saw it today as well. Logged in with admin user itself [demo@appsmith.com], and just opened the apps [try with OldAppDSTesting app, or RBAC-ME app] and found it.
This does not seem to be GAC related. We can keep the priority medium and track it later.

**Comment by btsgh** [comment]
<img width="1433" alt="Screenshot 2023-10-13 at 9 10 50 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/a0225b14-df66-4080-963c-cbc56e16e17b">
<img width="1430" alt="Screenshot 2023-10-13 at 9 09 52 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/9ae5e683-a3f8-4da6-ac72-7df4142e4921">

**Comment by btsgh** [comment]
Spoke to Environments team. Added these details to the issue we are tracking [there](https://github.com/appsmithorg/appsmith/issues/26621). Closing this out.
