### ISSUE TITLE
[Bug]: walkthrough is not visible for every New signup users

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#27842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While testing walkthrough feature, we always need to signup via new email id. 
I observed that not every new signup user is able to see the walkthrough UI.

### Steps To Reproduce

1. Signup on appsmith as a new user
2. Go to create new js/query
3. click on datasource  to create a query(postgres - user)
4. Observe that walkthrough should popup for "Schema" and "bindings"
5. Observe the 4th step on each new user signup. It does not popup for every new users

### Environment

Production

### Issue video log

https://www.loom.com/share/2bb939069a72455db8981c189d676474?sid=5e10d4da-36a3-4bff-a93f-0daf885429b6

### Version

Cloud/Production

**Comment by rohan-arthur** [comment]
https://www.notion.so/appsmith/Walkthrough-is-not-shown-for-some-users-ed151992a74b4baaa59fcfeee22dc863

**Comment by NilanshBansal** [comment]
Here's the root cause for this bug. 
https://drive.google.com/file/d/1a4iFPoxKG0hv-bJS_LSi0Jjj8zZ5lA0p/view?usp=sharing

cc: @rohan-arthur @AmanAgarwal041 @chandannkumar

**Comment by NilanshBansal** [comment]
As per our research, we found out that this is not a problem for new users signing up on the platform.
The mixpanel funnel that we were tracking was not appropriate to return the right results.
Ref: https://www.notion.so/appsmith/Error-prone-data-events-63b1bcc8532d4c2aaf16f75ec6662530
