### ISSUE TITLE
[Bug]: Can't change the size of the labels area in charts

### ISSUE THREAD

**Issue by jfior** [appsmithorg/appsmith#27845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a bar chart with long labels on the y axis, those labels go to a new line as they pleases and sometimes they are not even all shown. I want to be able to expand the label area and reduce the value area as i please.

This is what happens:
<img width="648" alt="Screenshot 2023-10-05 alle 14 14 11" src="https://github.com/appsmithorg/appsmith/assets/41690762/bbec074e-33d1-43f3-b9d0-9d9e8dd7e3fa">

While this is the result I would like. The following screenshot was taken in development but after deploy it transformed into the previous one. After sharing the application with the support now it appears in the previous way also in development.
![image](https://github.com/appsmithorg/appsmith/assets/41690762/43c83850-12a6-40cb-8630-ad16a00e8529)

### Steps To Reproduce

Create a bar chart with long strings as labels where one of the values is a lot higher then the rest.

### Environment

Deploy Preview

### Version

cloud

**Comment by somangshu** [comment]
We have made some change to the way the label works on chart widget for a better end user experience. 
Can you please check again and let us know what you think now @jfior

**Comment by jfior** [comment]
The end result now is perfect. Thank you.

**Comment by somangshu** [comment]
@jfior glad to know that. Do you mind sharing a screenshot of how things look now?
