### ISSUE TITLE
[Bug]: Activation: schema review page is not shown by default when user saves DB config

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#27843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user saves a database [PostgreSQL, MongoDB or MySQL], we should redirect them to the data preview page, where we show them the schema of their database and a preview of the databases tables/collection that they select from the schema. 

However, the behaviour we are seeing is that users are instead redirected to the configurations tab on saving, which is incorrect.

[reference](https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=933c27ea91af48db813cfd84632ae56a&pm=s)

### Steps To Reproduce

[reference](https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=933c27ea91af48db813cfd84632ae56a&pm=s)

### Environment

Production

### Version

cloud, self hosted

**Comment by sumitsum** [comment]
As per my investigation:
* The issue is reproducible only on production, not on release or latest dev setup. 
* The image hosted on prod is undergoing some changes due to investigation for stability issue that recently came up - i.e. the behaviour is expected to be temporary till. Once the stability issue is resolved or post the next promotion from release to prod, we should see this issue fixed on prod as well. 

Moving this PR to monitoring status for now because of the two pts above. If the issue on prod is fixed, we might want to close it then.

**Comment by rohan-arthur** [comment]
[not reproducible](https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=25a341ee5b0f41748293f69b774564b6&pm=s) - will reopen if the error comes back

**Comment by sumitsum** [comment]
Re-opening because of : https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=25a341ee5b0f41748293f69b774564b6&pm=s
