### ISSUE TITLE
[Bug]: License & Plans page :: The start and end date has the value "Invalid Date" for business and enterprise trial key

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#27858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the key entered is in trial phase, start and end date data is not displayed.

### Steps To Reproduce

1. Login to https://ee-2453.dp.appsmith.com with admin credential (demo@appsmith.com/demo@appsmith.com)
2. Click on "Adin settings" and navigate to "License and plans page"
(A trial key should be entered)
3. observe the plan details.

![image](https://github.com/appsmithorg/appsmith/assets/132880870/ba5da310-06f4-44bc-9612-f1ebd35c32c3)

**Note:** Observation made for a business trial key also.

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.39

**Comment by Harshask93** [comment]
@dipyamanbiswas07 Are we not showing the dates for trial key as part of fixing this ?

**Comment by dipyamanbiswas07** [comment]
Yes we are not showing dates for trial
