### ISSUE TITLE
[Feature] Ability to set page order

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2786]
## Summary
Should be able to set the ordering of pages

## Motivation
Pages can be built in different order from what you want to display. Developer should be able to set an order of page tabs being shown

**Comment by areyabhishek** [comment]
Figma link to designs: https://www.figma.com/file/NJB6wtUsWfYKIKICXKwWzY/Dynamic-Page-Visibility?node-id=150%3A2616

**Comment by riodeuno** [comment]
Related to #1092.
Note:
- Pages can be edited by opening the "Pages" pane from the entity explorer (In designs)
- Pages can be: reordered, renamed, set as homepage, deleted and copied and pasted to duplicate
- In the pages pane, users can view and edit: page url, visibility
- In the pages pane, users can also create a new page.

**Comment by sharat87** [comment]
@jsartisan, I'm thinking we have an `order` field in the objects inside `application.pages`. This will be a numeric field that'll determine the order of the pages. The API to reorder would be something like:

```http
PUT /api/v1/applications/page/{pageId}/reorder?order=2
```

This will get the page given by `pageId` to move to position `2`, and incrementing other pages' order values appropriately.

Any new page gets added to the end of the list, and can promptly be reordered using this same API. Does this sound good?

**Comment by jsartisan** [comment]
Reopening this issue as I will be starting the integration with UI.

**Comment by areyabhishek** [comment]
Is there an update to this issue?

**Comment by jsartisan** [comment]
The API to sort the pages got merged into release this Monday. I will be integrating it now.

**Comment by gaurav-wagh-tark** [comment]
Can we change Page order?

**Comment by hetunandu** [comment]
> Can we change Page order?

@gaurav-wagh-tark Yes you can! Go to settings and use the drag handle to adjust the page order you like

<img width="697" alt="Image" src="https://github.com/user-attachments/assets/ca0926cc-2cc2-45ee-a97c-67a02dcd13ca" />
