### ISSUE TITLE
[Feature]: Activation: Shorten the feature walkthrough delay time

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#27863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- Set the delay time to 2 sec for before showing walkthrough to users. 
- [reference](https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=39ccfdc9a4634a58b717d07fdb6e9e63&pm=s)

### Why should this be worked on?

Activation.

**Comment by btsgh** [comment]
Checked on latest prod with a new user, and the time delay has been reduced.
