### ISSUE TITLE
[Bug]: Linting error is oserved on upgrading or restart by admin

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#27865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observation is made when the user is switching between plans. The app works fine but observe a Linting error.

### Steps To Reproduce

1. Login to https://ee-2453.dp.appsmith.com (e  on enterprise version)
2. Setup an app including window message listener
Observe that the app works as expected
3. Make any changes under admin settings and click on "Save and Restart"

Observe that post restart, below error is observed.

![Linting image (1)](https://github.com/appsmithorg/appsmith/assets/132880870/580ee0a6-6de3-43e5-94c5-c7ebecc6eead)
![Linting image 2](https://github.com/appsmithorg/appsmith/assets/132880870/d367f95f-b73b-4197-83b6-9101c2de4b7a)
![Linting image 3](https://github.com/appsmithorg/appsmith/assets/132880870/52758f14-1d64-43f1-b38a-bd5e81113d10)

**Note:** Similar observation is made when user switch between plans i.e upgrade/downgrade.

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.39

**Comment by dipyamanbiswas07** [comment]
@Harshask93 is this happening on downgrade? That's expected. windowMessageListener and unlisten methods should only work for PAID plans and not free.

**Comment by Harshask93** [comment]
@dipyamanbiswas07 Not on downgrading to CE (this scenario works fine). Issue happens on upgrading and downgrade here means from EE to business which is still a paid plan. 

Below is the exact flow:
Enterprise trail --> CE --> Business Trial --> Business Paid --> Enterprise Paid

**Comment by dipyamanbiswas07** [comment]
Not sure how you go to this issue, but probably due to a bad state.
Attaching a video on the DP testing branch to show it is working fine.


https://github.com/appsmithorg/appsmith/assets/26247571/fcc4b9c2-2878-4c42-9c21-6b5b3ff8277b

**Comment by Harshask93** [comment]
Closing as the issue is not reproducible and working as expected without error.
