### ISSUE TITLE
Limit autocomplete results based on context

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#27871]
Autocomplete results should be limited based on the expected value type for a property or function param instead of results that cannot be used. 

for instance, 
- autocomplete results should not include functions on data fields 
- autocomplete results should not include strings for a function parameter that is of type object 
- etc...
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/28106
- [ ] https://github.com/appsmithorg/appsmith/issues/28107
```

**Comment by arunvjn** [comment]
Closing this issue since both the subtasks are completed
