### ISSUE TITLE
[Feature]: Sync RBAC permissions across multiple instances

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#27879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We should be able to sync roles, groups, and permissions across multiple Appsmith instances.

### Why should this be worked on?

Say I have a global company. I would like to deploy an instance of Appsmith in different regions to contain them in our company VPCs so they have access to our internal APIs. When doing this we currently have to update each instances RBAC manually any time there is a change, and this is time consuming. This produces a lot of potential maintenance overhead.

**Comment by kostyay** [comment]
Hi
This is really useful for multi region deployments when you have a replica of appsmith installed in different locations.
I personally think that it should be possible do define roles in Application Level. This way if I sync an app via github the roles and the bindings would be recreated as well.

**Comment by Nikhil-Nandagopal** [comment]
I'm closing this in favor of #32298
