### ISSUE TITLE
[Bug]: Missing precision issue with JSONForm

### ISSUE THREAD

**Issue by AppsmithCN** [appsmithorg/appsmith#27881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I obtained an ID in the database, it could not be displayed properly due to the issue of missing accuracy. I demonstrated it through the input component
<img width="1402" alt="image" src="https://github.com/appsmithorg/appsmith/assets/104495020/653f3487-efb6-4d4c-914a-5e4d1356bf55">

### Steps To Reproduce

1、Enter 1234567890123456789 in the input component
2、In the JSON form component, select one of the options to set, such as Employee ID
3、Select Field Type as Select
4、Used in Default selected value with {{input1.text}}

### Environment

Production

### Version

1.9.37

**Comment by We13b-MD** [comment]
Hi @Nikhil-Nandagopal  i will live to work on this issue with you is there any way I can help. I have proficiency in JavaScript
