### ISSUE TITLE
[Bug]: Postgres: Error: Prepared statement "S_2" already exists

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#27897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- When insert query is run on loop, this error occurs: 
```
SQLSTATE: 42P05
Error: Prepared statement "S_2" already exists
```
- Please check [this](https://theappsmith.slack.com/archives/C0341RERY4R/p1696276603506489) thread for more info.
```
Is prepared statement toggle on ?
Yes we're using prepared statements, and will keep this on to prevent SQL injection security issues

Which DB service are you using ?
Supabase

DB version ?
PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit (per select version();)

Any manually defined prepared statements ? 
No
```

More info:
```
As expected, it works with prepared statement disabled for testing.
We're using Supabase's default connection pooling (I think PgBouncer; I don't think they've rolled out Supavisor yet)
I've got a NodeJS bulk import script for this same project & table that imports several thousand rows with no issues (using separate insert commands for each). This doesn't go through PgBouncer so not sure if that's causing an issue, but that's a widely-used piece of software so I'd be surprised if it was causing the issue
I've switched to using the Supabase client and loading the rows via the API for now, so not a blocker any more, but definitely would like to see this resolved so we can remove the workaround
```

### Steps To Reproduce

[ref](https://theappsmith.slack.com/archives/C0341RERY4R/p1696276603506489)

### Workaround
Either one of the two should work:
1. Disable the prepared statement toggle. 
2. Use REST API to make the insert query.

### Environment

Production

### Version

cloud, self hosted

**Comment by Nikhil-Nandagopal** [comment]
Closing as it seems provider specific and might be solved with the new supabase updates

**Comment by thebadking** [comment]
I am having the same issue, the problem seems to happen randomly which seems to indicate a problem on Appsmith side

**Comment by Nikhil-Nandagopal** [comment]
@thebadking are you using supabase as well? and is this happening when you are running a loop?

**Comment by thebadking** [comment]
it happens when I trigger any basic query with or without prepared statements, manually or on page load it is the same

**Comment by thebadking** [comment]
re-open and fix this issue please....

**Comment by Nikhil-Nandagopal** [comment]
@thebadking I'm not able to reproduce this on our end and we use supabase too. Are you using the session mode with connection pooling enabled and port 5432?

**Comment by eedwardsSGS** [comment]
@thebadking note that you could previously set Supabase up for 'session' transactions on port 6543, but now that is locked to 'transaction' which doesn't play nicely with prepared statements, and the new way of handling this is port 5432 for 'session' connections.  This is a change Supabase made.

**Comment by thebadking** [comment]
thats the seeting I have
