### ISSUE TITLE
[Bug]: Appsmith fails to start after auto updated to v1.9.38, mongodb fails

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#27890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Mongodb won't start after the latest update, gives this error in the "mongodb.log" file:

`{"t":{"$date":"2023-10-09T07:13:18.343+00:00"},"s":"F",  "c":"CONTROL",  "id":20573,   "ctx":"initandlisten","msg":"Wrong mongod version","attr":{"error":"UPGRADE PROBLEM: Found an invalid featureCompatibilityVersion document (ERROR: Location4926900: Invalid featureCompatibilityVersion document in admin.system.version: { _id: \"featureCompatibilityVersion\", version: \"4.4\" }. See https://docs.mongodb.com/master/releas>{"t":{"$date":"2023-10-09T07:13:18.343+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":15000}}
`

Seems to be the same issue we hade last time, referenced here: https://github.com/appsmithorg/appsmith/issues/27362

### Steps To Reproduce

Se description above.

### Environment

Production

### Version

Self hosted / 1.9.38

**Comment by ashutosh1211** [comment]
Any updates on this, as we are not able to use it.

**Comment by shaneconnolly** [comment]
Also having this same issue

**Comment by meedsharif** [comment]
I'm experiencing the same issue. Any updates on this would be greatly appreciated.

**Comment by Nikhil-Nandagopal** [comment]
Hi, we recently released a new version of Appsmith. You can update to that and it should be safe to upgrade
