### ISSUE TITLE
[Bug]: Not able to enable the email notification feature once user downgrade and upgrade again

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not able to enable the email notification feature once user downgrade and upgrade again
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/8eaf7860-bed4-4e61-b540-7f84d2a6cbeb">

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com
2. donagrade the instance to ce 
3. now go to admin setting with admin cred the user is not able to enable email notification from form login 
4. now upgrade the instance to ce or ee its a same issue 

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by dipyamanbiswas07** [comment]
is the SMTP setup being removed on downgrade?

**Comment by abhvsn** [comment]
@dipyamanbiswas07 no that should not be the case. I think SMTP was not enabled at first place, I will let Raksha confirm on this though.
Also can we add some pointer why the admin is not able to enable the email verification even a small tool tip would be sufficient to avoid this confusion.

**Comment by dipyamanbiswas07** [comment]
Yes asked @pranayagarwal96 to add the item to the backlog to show why Email Verification is disabled

**Comment by RakshaKShetty** [comment]
@abhvsn , @dipyamanbiswas07 thats connect after dp got recreated the data was lost so i dint check that again, That is the reason i was not able to enable the email verification but its very confusing as we a user i am clueless why is it not allowing me to enable

**Comment by RakshaKShetty** [comment]
closing the issue this is picked up by different team as a enhancement
