### ISSUE TITLE
[Bug]: Widgets disappearing from Git

### ISSUE THREAD

**Issue by zelenzaMMdev** [appsmithorg/appsmith#27917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When committing an application to Git, with a nested widget in this case a tab with a form, it not appear to save to git, but still in the visual

### Steps To Reproduce

1. Create a component hierarchy ~ MainContainer > Tabs > Container  > form [many fields]
2. do a push
3. Input widget should disappear from Git

### Environment

Production

### Version

v1.9.27

**Comment by Parthvi12** [comment]
@zelenzaMMdev Sorry that you are facing this issue, it has been fixed here https://github.com/appsmithorg/appsmith/pull/25411 and released in v1.9.28 . You can follow these steps to rectify the situation:

1. Upgrade your instance to v1.9.28.
2. Revert your branch to the commit before v1.9.27 and push to remote repo.
   a. This is the last commit they made before upgrading to v1.9.27.
   b.This can be done by cloning the repo locally or through the GitHub desktop app.
   c. Refer to [Revert](https://www.atlassian.com/git/tutorials/undoing-changes/git-revert#:~:text=Out%20and%20Reverting.-,Summary,in%20regards%20to%20losing%20work) and [GitHub Desktop Revert Docs](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit-in-github-desktop).
3. Pull the reverted branch on Appsmith.

Please reach out incase you have any queries.
