### ISSUE TITLE
[Bug]: iFrame Rendering Inconsistent With Real Page Within Appsmith Project

### ISSUE THREAD

**Issue by Fiddler46** [appsmithorg/appsmith#27925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The iframe I have in the main page renders another page within the same Appsmith project. However, upon changing the structure/widgets that exist on the page, the iframe does not fully reflect and render those changes.

What is expected is the changes made within the page reflect back into the iframe which has a connection to that specific page via a URL.

Within the iframe:
![image](https://github.com/appsmithorg/appsmith/assets/23459452/6a5ae8c8-7919-47b6-8275-d2ccb20a344b)

Within the page:
![image](https://github.com/appsmithorg/appsmith/assets/23459452/3dcbc96b-13c2-41af-8e45-8c8c22804d07)

### Steps To Reproduce

1. Go to designated public sample [app](url)
2. Go to the 'Infrastructure' page and make whatever changes (adding, subtracting, modifying widgets) and then save.
3. Go back to the main page and press the 'Infrastructure Plane' button on the 'Planes' page.
4. The iframe should still be rendering the same static image even though the changes are visibly different within the other page.

### Public Sample App

https://app.appsmith.com/app/iframe-rendering-discrepancy/planes-page-65254112914ac4223097e57d

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@Fiddler46 there are 2 things to be aware of here
1. The change will only be reflected once you deploy the app after you make the changes
2. The change will only reflect once you refresh the webpage since the web page in the iFrame is already loaded in the browser
Let me know if it still doesn't work

**Comment by Fiddler46** [comment]
Appreciate the answer, worked after it was deployed and I could test the changes. Thanks! @Nikhil-Nandagopal
