### ISSUE TITLE
[Bug]: On downgrading to CE, the watermark option is not enabled by default.

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#27922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observation is made when the option is unchecked in paid plans and then a downgrade to CE is performed.

### Steps To Reproduce

1. Login to dp - https://ee-2453.dp.appsmith.com
2. When on a business plan, uncheck the watermark option on admin settings
3. Downgrade to CE by removing the license
4. On successful downgrade, navigate to admin setting page
5.Navigate to "General settings" page

observe that watermark option is still unchecked.

![image](https://github.com/appsmithorg/appsmith/assets/132880870/7617ea85-5b19-4467-8c1a-baaf95708cd2)

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.39

**Comment by dipyamanbiswas07** [comment]
@abhvsn please take a look

**Comment by abhvsn** [comment]
To fix this I would suggest to move the env `APPSMITH_HIDE_WATERMARK` to DB and remove the dependency on env file. This means we won't need the restart anymore and will need some client-side changes as well. This way code will be much more concise.

This variable should be consumed under the Branding service IMO.

cc: @dipyamanbiswas07 @vivonk
