### ISSUE TITLE
[Bug]: App level sharing is functional in production instance.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App level sharing is functional in production instance. This is a Business Edition feature, and hence should not be present on app.appsmith.com, which is a community edition instance.

### Steps To Reproduce

1. Login to app.appsmith.com
2. Open an existing application
3. Click on the share option available on the top right of nav bar inside the application.
4. Here, note that the modal showing up is that of applevel sharing. And the option is available for user to share only this application
5. This is incorrect. Community edition user should not be allowed to share only the application. They should be able to share only the entire workspace.

https://github.com/appsmithorg/appsmith/assets/101863839/70562d08-0559-478c-a80a-5b756f5c9c3d

### Environment

Production

### Version

Cloud

**Comment by abhvsn** [comment]
Closing this as it's fixed by updating the filters on Flagsmith.

Related thread: https://theappsmith.slack.com/archives/C02MUD8DNUR/p1697001745597039
