### ISSUE TITLE
[Task]: Update the sql datasource preview data UI

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#27946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Update the UI for datasource preview data as per new designs
- Convert the above components as common for supporting gsheet preview data UI as well.

**Comment by rohan-arthur** [comment]
@AmanAgarwal041 this needs an [estimate](https://www.notion.so/appsmith/Agile-Estimations-fc322f8fc6784563a4e63c4c66ac4102?pvs=4#7626b21a5fee43508369b465987e9a2b)
