### ISSUE TITLE
[Task]:  Move app settings to the left

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#27949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Figma: https://www.figma.com/proto/GTOUFv2RYxDjmxfbGYoWpn/IA-changes?type=design&node-id=408-39046&t=tjYviuVkHVLgh2NQ-0&scaling=min-zoom&page-id=408%3A23992

**Comment by rohan-arthur** [comment]
duplicate of #27955
