### ISSUE TITLE
[Bug]: Seeing modifications to be commited, even when no changes have been made on the app

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a git connected app, after committing and deploying, when I browse to the api and come back to home page, I see that though I have not made any changes on the query, or app, the message on git modal asks me to commit as there have been changes since last deployment

### Steps To Reproduce

1. Create a git connected app
2. Create two branches A and A-test
3. In the A-test branch, create an api, run the api, attach it to a table on a page and rename the page
4. Now commit changes and deploy the app
5. Merge changes from A-test to A branch
6. Do not change anything in either of the branches, but just browse through the page, query and come back to page
7. Observe after a while that one modification tool tip pops up and on the modal, the message indicates user to commit since there have been changes since last deployment. Even if we discard and pull, this still does not go away
8. The screenshot below is from the file committed on github repo

<img width="932" alt="Screenshot 2023-10-11 at 12 44 52 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/8ff42413-6cfd-4241-9fdf-1313c82676a6">

Application url - 
https://app.appsmith.com/app/gitissuetest/page1-652646902be41c5c758b0d65?branch=master

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/T0ZC7jXDLddaHzNc

### Version

Cloud

**Comment by RakshaKShetty** [comment]
Issue still exists
<img width="1393" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/37d807b5-2f37-44b9-bde4-4ef378761731">

**Comment by nidhi-nair** [comment]
@rohan-arthur @sumitsum could you folks help with information on this property? Who owns the assignment of this property and would it be okay to not persist the value at all?

**Comment by sumitsum** [comment]
IMO, autoGeneratedHeader logic resides on the client. Adding @AmanAgarwal041 @sneha122 for help.

**Comment by sumitsum** [comment]
Regarding persistence, it needs to be persisted in the DB, otherwise query execution will fail. Should this be shared via export feature - this can be debated.

**Comment by sneha122** [comment]
@nidhi-nair The autoGeneratedHeaders was introduced to solve [this issue](https://www.notion.so/appsmith/The-issue-with-API-Content-Types-84c2dfdc31fd4c87827176904de58b27), if we remove it, it would cause issue mentioned in the notion doc. We can probably check why this field is getting introduced as changes in the first place with [] array and then determine the fix for this

**Comment by nidhi-nair** [comment]
Thanks for the context Sneha, Sumit! From what Sneha has mentioned, and the implementation details in the doc, I agree that the field itself cannot be removed from exported files. 

I am going to re-assign this issue to you Sneha to triage and figure out how this value can be initialized correctly on the server itself. I suppose a default empty list value should do the trick. I'll work with the team to introduce mechanisms that ensure addition of such fields in the future would always be compliant with git.

**Comment by sneha122** [comment]
@nidhi-nair I have created a fix for the issue, please check the Pr once, it was a frontend change because all defaults are getting initialised in the frontend. @btsgh Please test out the changes on DP once as well
