### ISSUE TITLE
[Bug]: The SCIM icons are displayed even when user downgrades from EE to BE

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The SCIM icons are displayed even when user downgrades from EE to BE
![image](https://github.com/appsmithorg/appsmith/assets/45958978/0b95e3aa-182b-48ff-9f08-6f52471c6026)

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com
2. add a enterprise license in the instance now connect it to scim
3. Now once the scim user are linked with the instance downgrade it to business 
4. now go to users and groups tab we can still see the scim icon 

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by dipyamanbiswas07** [comment]
@ankitsrivas14 can you take a look at this please?

**Comment by dipyamanbiswas07** [comment]
This is fixed. Moving this to needs QA
