### ISSUE TITLE
[Feature] Create UI support to directly upload / attach files to a query

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2795]
## Summary
1. In case a file needs to be uploaded to be used by a query, then it must be fetched via the filepicker widget and then added to the query via moustache expression. This flow can be complicated/inconvenient for some application developers. In order to make it easy and intuitive to link files with any query, some kind of UI support is required - not sure what. Lack of this feature was felt during S3 plugin development, where filepicker widget is used instead. The intent of this issue is to make it easy for application developers to link files with a query and possibly avoid using a moustache binding.
  
## Motivation
1. Ease of use.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum If the upload button is provided on the query form, then how will the end user upload the file?

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal This intent of this issue is to help application developer - some way to circumvent the moustache binding. I hadn't thought through when suggesting upload button - actually it does not seem very helpful. The actual idea is to provide some kind of UI construct to avoid writing the moustache binding - not sure how to achieve this or if this is possible.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum ah got it, basically a way to test quickly on the query pane. Retagging this as a query enhancement

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal I was also thinking something along these lines, not sure if it will work here - a drop down where all the filepicker names are listed, so that the instead of writing the moustache binding, an app developer can simply select one of the filepicker widgets to use as a upload medium.

**Comment by mohanarpit** [comment]
Closing this as this is not a functionality that the user would be building for a real-world application. We should let plugins bind to specific data only instead of giving file upload inside the action.
