### ISSUE TITLE
[Feature]: Canvas Size

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#27957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://www.notion.so/appsmith/Unified-add-panel-18a94e51a498410aa5503379babb6ef0?p=2ab807106922432993fd2766d1b19fde&pm=s

### Why should this be worked on?

part of unified add panel

**Comment by hetunandu** [comment]
Fixed with #28248
