### ISSUE TITLE
[Feature]: Add new selected state colour on DS repo

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#27960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://www.notion.so/appsmith/Unified-add-panel-18a94e51a498410aa5503379babb6ef0?p=cce00a1ac41146d1b7385735420376b9&pm=s

### Why should this be worked on?

part of unified add panel

**Comment by laveena-en** [comment]
@hetunandu The icon active colour doesn’t seem to be a darker shade of grey as suggested in design

DP:

![image](https://github.com/appsmithorg/appsmith/assets/109572422/4f9758a1-e414-4fc4-891b-efe33e7c6f98)

Design:

![image](https://github.com/appsmithorg/appsmith/assets/109572422/b8b27b01-76ca-4481-b6bc-4783f2c88946)
