### ISSUE TITLE
[Bug]: JS object properties not set

### ISSUE THREAD

**Issue by chomni** [appsmithorg/appsmith#27978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since 1-2 days ago (release v1.9.38 or v1.9.39? in the AppSmith-hosted SaaS), we are facing a issues with setting properties in JS objects.

The following code snippet of a JS object, `JSObject`, illustrates the issues.
```
export default {
  data: [],

  async getData() {
    await APIQuery.run()
    return APIQuery.data
  },

  async myFun1() {
    this.data = await this.getData()
    console.log(this.data) // prints "[]", this.data is not set
  },
  async myFun2() {
    const data = await this.getData()
    this.data = data
    console.log(this.data) // prints result of this.getData(), this.data is properly set
    // however, setting a UI element (table) to {{ JSObject.data }} does not populate the table
  },
  async myFun3() {
    await APIQuery.run()
    const data = APIQuery.data
    this.data = data
    // this properly populates the table when setting a UI element (table) to {{ JSObject.data }}
  },
}
```

Previously, `myFun1()` has worked as expected for us - the table UI element has been populated with the results of `getData()` (the query). But since a few days ago, only `myFun3()` will work in this way.

### Steps To Reproduce

1. Create an API query to an API returning a JSON array and name it `APIQuery`.
2. Create a JS object named `JSObject`, containing the code snippet in the description.
3. Create a table and a button in the UI.
4. Set the button `onClick` property of the button to `{{ await myFun1() }}`.
5. Set the `Table data` property of the table to `{{ JSObject.data }}`.
6. Click the button.
7. The table is not populated.
8. Return to step 4, first replace `myFun1` with `myFun2` and continue to step 7, then replace it with `myFun3` and to the same. Only `myFun3` populates the table.

### Environment

Production

### Version

v1.9.40-SNAPSHOT

**Comment by bharath31** [comment]
@arunvjn @ohansFavour could you please run an RCA here? Looks like something broke with variable mutation. 

cc: @Rishabh-Rathod
