### ISSUE TITLE
[Feature]: Request for an information/message to user when Meeting Scheduler template's list events fails, asking user to re-authorization DS

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we fork the Meeting Scheduler template to a workspace, since it uses OAuth2.0 datasource to connect to the google api, the List Events action fails, and no data is displayed on the template. User has to go to the OAuth2.0 datasource, re-authorize the DS and then this action and other associated actions start to work.

https://github.com/appsmithorg/appsmith/assets/101863839/d51f291d-aba5-4788-8ab6-6dea6938bb46

### Why should this be worked on?

Though this is probably is an expected behavior, Can an information be provided to the user that the particular DS needs to be re-authorized for the template to work
This is requred, since it is not a great experience for the user to see the template error out the first time, and it might probably take a while for user to figure out what the issue is. A help or information here will be directional for them to get started quickly

**Comment by jacquesikot** [comment]
New meeting scheduler template has been uploaded to the platform, and it fixes this issue.
