### ISSUE TITLE
[Bug]: Though enterprise key has been added, developer settings-> license pool size still shows up as Enterprise feature and is non editable

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#27997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/101863839/f0783a49-180a-4976-bfdf-10c9d9d744f0

### Steps To Reproduce

1. Login as an instance admin to any DP [https://ee-2209.dp.appsmith.com]
3. Go to Admin Settings, and ensure we are on Enterprise plan
4. Select Developer Settings here
5. Note that the connection pooling field is disabled and has the Enterprise tag or ramp, though user is already on Enterprise

### Environment

Deploy Preview

### Version

Cloud

**Comment by abhvsn** [comment]
Closing this as already resolved https://theappsmith.slack.com/archives/CTHN8GX5Y/p1697458577449479

**Comment by btsgh** [comment]
Reopening as issue is still reproducible.
