### ISSUE TITLE
[Bug]: Datasource name not readable in reconnect data source modal, if name is long.

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#28008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Reported internally: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1696943251648119
<img width="827" alt="Screenshot 2023-10-12 at 5 18 40 PM" src="https://github.com/appsmithorg/appsmith/assets/6761673/e41b9322-3b2e-439d-94de-6bc63e0473fe">

* Here you can get full name only if you hover `i` icon
* We should also get a tooltip when name is hoverd

### Steps To Reproduce

1. Fork any template with authenticated datasource.
2. In the reconnect datasource modal, hover over the i icon

### Environment

Production

### Version

Appsmith v1.9.40-SNAPSHOT

**Comment by jacquesikot** [comment]
@rahulbarwal Right now, the tooltip shows up whenever a user hovers over the icon. We should maintain that for hovering over the title right?
