### ISSUE TITLE
[Bug]: On Deploy, the modal that comes up, refers to Staging and Production, where as now we have custom environments as well. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On creating an app with a few pages and DS, when we deploy, information here has reference to Staging and Production env only, where as now we have support for custom environments

### Steps To Reproduce

1. Create an application, connect to a datasource and bind it to a table
2. Deploy this app
3. Note that on the deploy modal, information has reference to Staging and Production env only, where as now we have support for custom environments

`To isolate application changes between Staging and Production, connect your apps to a Git repo and create branches for Staging and Production`

<img width="1018" alt="Screenshot 2023-10-12 at 4 40 45 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/052029e8-db0b-43cb-a162-c92338cb716e">

### Environment

Deploy Preview

### Version

Cloud

**Comment by ayushpahwa** [comment]
Modal is now removed

**Comment by btsgh** [comment]
Yes - works fine
