### ISSUE TITLE
[Bug]: When new member is added to a workspace, front-end does not render updated user list

### ISSUE THREAD

**Issue by yasharma2301** [appsmithorg/appsmith#28013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a new member is successfully added to a workspace, the front end does not render the updated user list on /applications page. But the same works on the dedicated manage users page. 

For applications page:
[POST] /invite is called
[GET] /member is called after addition
But it is not put back in the state or a rerender is not done even after the modal is closed.

![image](https://github.com/appsmithorg/appsmith/assets/58696571/ec83d5b7-5f51-4d4f-8b78-1c858958c8fd)

### Steps To Reproduce

1. Open /applications page.
2. Create a workspace if none is available.
3. Share the workspace with another email.
4. Close the Share modal.

### Environment

Production

### Version

Cloud

**Comment by yasharma2301** [comment]
I can pick up this issue once verified

**Comment by yasharma2301** [comment]
There is an inconsistent state for reading workspace users at different places

## state.ui.applications.userWorkspaces
![image](https://github.com/appsmithorg/appsmith/assets/58696571/40b57f9c-6662-41db-a642-9bc294000301)

This list contains 2 types of user objects, one has all keys which are returned from the backend.
The next one is a user object containing only {username, permissionGroupId}
This inconsistency is generated from inviteUsers function present in userSagas.tsx

There is another state 

## state.ui.workspaces.workspaceUsers
![image](https://github.com/appsmithorg/appsmith/assets/58696571/4af29b04-d94d-472b-a241-119fb446411d)

This  is updated after the /members call returns success response
This contains the correct user object with all details

# Issue
![image](https://github.com/appsmithorg/appsmith/assets/58696571/a00d33e5-d8e0-4315-be71-48ce7c4d2979)
Before rendering allUsers, filter is applied on userId and as the newly users added to state have inconsistent object definition they are not rendered

# Solutions

1. Either remove the filter check and let all users be rendered in the pane irrespective of object structure difference.
2. When the /members call is succeeded change the state of state.ui.applications.userWorkspaces (This is possible as you have workspaceId and users array readily available)

Let me which one makes sense here, will raise a PR for the same

**Comment by yasharma2301** [comment]
@Nikhil-Nandagopal any comments here?

**Comment by ankitakinger** [comment]
@yasharma2301 I think the first solution looks good. I don't see any impacts of removing the filter there.

**Comment by yasharma2301** [comment]
Added **uniqBy** filter so that it does not break #17728 till the backend code fix is pushed. Let me know if you would like the plain approach of just removing the filter function instead of handling unique users.

**Comment by ankitakinger** [comment]
@yasharma2301 I appreciate that you fixed the issue while taking care we don't introduce an old bug. Personally I'm not a big fan of lodash functions because sometimes they lead to performance issues. I would prefer doing the plain approach and get this fixed on backend.
