### ISSUE TITLE
[Bug]: "On trying to commit for one of the app connected to a private repo, the app remains in loading state.

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#28021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Observation is made when more than 3 private repo apps are present and the instance is downgraded to CE. Post downgrade the commit action is being performed for one of the apps.
Tested on DP: https://ee-2453.dp.appsmith.com/

### Steps To Reproduce

1. On a paid version, create 4 diff apps and connect each one to a private git repo
2. Downgarde the instance to CE by removing the key
3. Open one of the app and make changes
4. Click on "Commit" icon
5. Click on "Commit and push"

observe that it remains in the loading state.

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.40

**Comment by infinitetrooper** [comment]
Stale
