### ISSUE TITLE
[Bug]: An empty toast error is displayed each time when user navigate to postgres DB with view access for muti env

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#28029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

An empty toast error is displayed each time when user navigate to postgres DB with view access for muti env
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/a285e2df-e2f8-4b09-8c3d-1877cbbf07b1">

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com
2. login with me+cv@gmail.com/ e+cv@gmail.com
3. go to edit mode of the application
4. click on postgres db 
5. The error message is displayed  as in the attached screenshot

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by dipyamanbiswas07** [comment]
@ankitsrivas14 please take a look. related to multiple environments

**Comment by deepikaappsmith** [comment]
we no more see this issue and hence closing the ticket.
