### ISSUE TITLE
[Bug]: Though Prod is not configured, after configuring two environments, on review page, Prod environment is listed

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I configure Staging, and one other environment for Mongo DS, On testing and saving both, the review page shows Production details also, when production is not configured at all. 

### Steps To Reproduce

1. Login to application in a workspace with a few custom environments created.
2. Select to create a mongo datasource
3. Fill in details for Staging, test and save. Review page shows Staging config
4. Now go to edit ds page, and enter details for any other custom environment. Test and Save
5. Review page shows Production with nothing below it, Staging and Custom Env
6. Production should not be shown at all here as Staging and Custom Env were the only ones configured.

https://github.com/appsmithorg/appsmith/assets/101863839/a3a8d245-b631-4834-bf1f-99a336fd716d

### Environment

Deploy Preview

### Version

Cloud

**Comment by ayushpahwa** [comment]
I have fixed the method, should not be seen in newly created datasources

**Comment by btsgh** [comment]
Tested this and the issue is no longer seen in newly created datasources. 
However - modifying existing datasources still has the issue. @ayushpahwa  - do you think that should be addressed as well? Will there be a scenario with a customer having only Staging DS on his app and he creates more environments?

**Comment by btsgh** [comment]
Moving to QA Done - the existing DS issue will not occur as custom env is a new feature
