### ISSUE TITLE
[Bug]: Seeing Duplicate configuration on trying to save third environment for any DS

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to save a third environment on mongo  or postgres ds, I get a duplicate configuration error. 

### Steps To Reproduce

1. Go to an application in a workspace, having many custom environments
2. Configure Mongo for Staging, test and save, one custom env test and save, second custom env try to test and save
3. An error pops up on Save
 
https://github.com/appsmithorg/appsmith/assets/101863839/fd4cb3a0-002c-46d8-93a2-b9b9c009f595

<img width="1420" alt="Screenshot 2023-10-13 at 9 22 42 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/11d75805-6d60-4624-86b1-bd39ea91393d">

### Environment

Deploy Preview

### Version

Cloud

**Comment by ayushpahwa** [comment]
I have fixed the method, should not be seen in newly created datasources

**Comment by btsgh** [comment]
Tested - not able to see the issue any more
