### ISSUE TITLE
[Bug]: Count of total datasources in workspace is incorrect, SAAS Integrations are also being counted. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Manage Environments page, in the configurations column, the count of Total datasources in workspace is incorrect. None of the SAAS integrations should be counted in the total count. At present, only Google Sheets is being ignored from the total count, while rest of the integrations are being counted.

### Steps To Reproduce

1. Create an application, and add three Saas integrations - say Google sheets, Hubspot and Airtable and Save these configs on Prod
2. Note that the count of total datasources in the config column of Environments page shows as 2.
3. As per the discussion, the SAAS integrations should not be counted as datasources. So in this case, the total datasources should be 0, as google sheets, hubspot and airtable are saas plugins, but we see the count as 1. 

<img width="1136" alt="Screenshot 2023-10-13 at 1 29 17 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/3279df7c-3f1d-487d-840f-dfef5077eac6">

<img width="1185" alt="Screenshot 2023-10-13 at 1 29 53 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/b3276e9b-79b0-4f1a-8ba6-fcc224b8c074">

### Environment

Deploy Preview

### Version

Cloud

**Comment by ayushpahwa** [comment]
@sondermanish ds count is being sent via the server. Can you please take a look?

**Comment by btsgh** [comment]
fixed in latest dp
