### ISSUE TITLE
[Task - Server Test Suite]: Reduce the number of logs related to feature flag caching.

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#28049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

We need to reduce the quantity of logs related to feature flag caching when running the server test suite. The amount of logs have increased drastically, and that leads to developers not being able to find what they are looking for. Also, at times, only half of the logs are present. (Basically you have to reload the logs again.)

**Comment by abhvsn** [comment]
Closed via https://github.com/appsmithorg/appsmith/pull/28285
