### ISSUE TITLE
[Bug]: Users with previous Super User access lost super user privileges after instance upgraded to 1-click 

### ISSUE THREAD

**Issue by dipyamanbiswas07** [appsmithorg/appsmith#28059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Bug]: Users with previous Super User access lost super user privileges after instance upgraded to 1-click 

### Steps To Reproduce

Login to the user having previous super user access.

Observe we do not have access to Admin Settings anymore

### Environment

Release

### Version

v1.9.41

**Comment by abhvsn** [comment]
This is not an issue as this happened because the instance was downgraded and the users were given the tenant admin access via the custom group. Now as the feature flag for GAC was turned off all the users lost the access for admin setting.
