### ISSUE TITLE
[Bug]: On sharing workspace with appviewer rights, cannot see data on launch from the appviewer login.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I share a workspace with appviewer rights to user me-qa1@appsmith.com and login with me-qa1 user, I do not see any data on launching the app. 

### Steps To Reproduce

1. create an application with google sheets DS. 
2. Create a query and bind some data to a table
3. Deploy the app
4. Share the workspace with me-qa1@appsmith.com user, and give the user App Viewer rights
5. Login with me-qa1 and launch the app
6. Note no data is seen

https://ddpa7mfuvv.vmaker.com/record/DFrFimmwHlSJ0xYo

### Environment

Deploy Preview

### Version

Cloud

**Comment by ayushpahwa** [comment]
@btsgh parking this till rbac is completed

**Comment by sondermanish** [comment]
@btsgh This is not reproducible anymore,
The user listed here has been given app-viewer access only, the data could be seen in the table
<img width="1426" alt="image" src="https://github.com/appsmithorg/appsmith/assets/107841575/8216fb42-d862-4da2-ba23-b959a264cd0d">

**Comment by btsgh** [comment]
Still able to reproduce the issue @sondermanish @ayushpahwa 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGx2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f59f31a2f4ff49e8aa215444c26b17968fd7dc4e/Screen%20Recording%202023-10-25%20at%208.23.19%20PM.mov)

**Comment by btsgh** [comment]
This issue is fixed in new environments, but in existing env still able to reproduce it. Since you have mentioned above that this is a problem that you are aware of, rechecking here.
From my perspective, this can be faced by a customer with existing GSheets connection, and upgraded to Enterprise to use Custom environments, so I would want to reopen the issue.
