### ISSUE TITLE
[Bug]: Git import doesn't support Azure Repos URL

### ISSUE THREAD

**Issue by rhuanbarreto** [appsmithorg/appsmith#28061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If I try to put an Azure Repos git SSH URL like:

```
git@ssh.dev.azure.com:v3/[org]/[project]/[repo]
```

I get the following error on the frontend:

```
Please enter a valid SSH URL of your repository
```

### Steps To Reproduce

1. try to import a git repository on a workspace.
2. Input the SSH repository url from Azure repos
3. You get the error

### Environment

Production

### Version

Business 1.9.39

**Comment by rhuanbarreto** [comment]
I sent an email to Appsmith support asking to send our confidential URL to you. we are using v1.9.47

**Comment by rhuanbarreto** [comment]
In which version this will be released?

**Comment by brayn003** [comment]
Hi @rhuanbarreto I have raised a fix for this already. It should start reflecting from v1.9.51 .
Hope this helps
