### ISSUE TITLE
[Bug]: When I add the same email id multiple times on the share modal and click invite, the API responds with multiple users with the same info

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#28067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add the same email id multiple times on the share modal and click invite, the API responds with multiple users with the same info.
Thread: https://theappsmith.slack.com/archives/C02K2MZERSL/p1697201766174849

### Steps To Reproduce

1. Go to any Appsmith instance
2. Open share modal for a workspace
3. Add an email, eg. user1@gmail.com, multiple times in the text field
4. Select a role and click invite
5. Notice the response of the API. It returns same number of users with exactly same info, instead of returning just 1 user info.

### Environment

Production

### Version

Cloud / Self Hosted - latest

**Comment by yasharma2301** [comment]
This looks like a good first issue, I can take it up. The approach would be simple, filter for unique users before entering the inviteUsers business logic.
If some other solution has to implemented let me know

**Comment by RakshaKShetty** [comment]
It is displayed only once now , closing the isssue
<img width="744" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/288e9586-c0db-427c-8a0d-46deabb0f8b0">
