### ISSUE TITLE
[Bug] When a new query is created for DynamoDB (and any datasource with a default dropdown) the default option is not parsed

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2809]
### Steps to reproduce the behaviour:
1. Create a DynamoDB datasource
2. Create a new query for this datasource
3. Run the query without editing any options
4. The action throws an error saying "Missing action name (like `ListTables`, `GetItem` etc.)." even though the default option exists.
![image](https://user-images.githubusercontent.com/5298848/106523380-08b22080-6507-11eb-9cb0-cafaa779bea3.png)

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by nidhi-nair** [comment]
@trishaanand @sharat87 was this the bug you guys were referring to yesterday?

**Comment by sharat87** [comment]
I think yes, this is what Trisha was talking about. I, on the other hand, misunderstood and went on an unrelated tangent 😛

**Comment by nidhi-nair** [comment]
@AmanAgarwal041, another scenario that might be related to this:

https://user-images.githubusercontent.com/5298848/145522749-bd42fbf5-4108-4b45-94ff-13d9293646a0.mov

**Comment by nidhi-nair** [comment]
This is not an issue anymore with the new form validations. DynamoDB will have this fixed in due time after it is ported.
