### ISSUE TITLE
[Feature]: Set up a process to keep the embedded DB up to date with template db schemas.

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#28093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Right now, self hosted users cannot use a lot of the templates on the platform because the embedded Postgres does not contain the updated schema for the templates.

We need a solution that allows us update the embedded Postgres periodically, or when changes have been made to any template apps that require the embedded db.

### Why should this be worked on?

We have gotten feedback from users trying to complete tutorials from our docs, or use templates. They are blocked because the template uses the embedded postgres, and it is not updated to handle the app they are trying to use.

**Comment by AnaghHegde** [comment]
@jacquesikot This has been solved via the RDS fix where we moved from embed and removed the redirction from localhost to the actual end point for the actions. Hence closing the issue
