### ISSUE TITLE
[Feature] Backend server container should automatically restart when it crashes due to `OutOfMemory` error

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2810]
## Summary

The server goes into a non-functional state when it runs out of memory and throws an `OutOfMemory` exception. Resolving this needs manual intervention for the container needs to be restarted. We can minimize the downtime if this restart can be made automatic.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 but why should a container even go into this OOME state?

**Comment by sharat87** [comment]
Yes, that's an issue I'd like to be investigated separately. The point of this issue is not to say that OOMs are okay. They are not. But if they do happen, I think there's value in having the container restart.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 how will we differentiate between manual killing and killed due to OOM so should restart?

**Comment by nidhi-nair** [comment]
Docker has  a `restart` property that might help with this configuration. You can specify manual killing as an exception to those.

**Comment by sharat87** [comment]
We haven't seen an OOM in several months on the cloud now. The `restart:` configuration is also added to the standard `docker-compose.yml` files, so I think we can close this.

@superali, this issue was actually talking about the cloud. 🙂

**Comment by crato-ctl** [comment]
sorry, but i have this issue, how can reporting?

**Comment by Nikhil-Nandagopal** [comment]
@crato-ctl can you share the logs of the docker container?

**Comment by crato-ctl** [comment]
sure, !!thanks in advance
[appsmith.zip](https://github.com/appsmithorg/appsmith/files/7988190/appsmith.zip)
!

**Comment by sharat87** [comment]
Hey @crato-ctl, thanks of sharing the logs. I don't see an `OutOfMemory` error from the logs, which is the topic of the issue. In fact, I don't see any error in the backend logs that should be causing instance impact for you. Can you share what user-facing errors or user experience degradation you are noticing please? If it's different from this issue, please feel free to open a new issue with these details so it's easier to track and investigate. Thanks!

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 this was a frontend related issue that we solved on a call :)
