### ISSUE TITLE
[Bug]: On upgrading test env to latest release version - logging in with SAML gives an 502 Bad Gateway error

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://release-ee-https.appsmith.com/applications

After upgrading this environment to the latest release version, which had SAML configured, we get an  502 bad gateway nginx error on trying to login with SAML

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/f3029af3-9961-4072-bd9f-2d425e852562

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
Refer this slack thread 
https://theappsmith.slack.com/archives/CTHN8GX5Y/p1697451400565959

**Comment by sharat87** [comment]
Have we seen this again since then? Do we have more information to investigate? If not, can we close?

**Comment by riteshkew** [comment]
Closing considering the last comment
