### ISSUE TITLE
[Task]: Add trace for evaluation action on local perf test

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#28119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The trace for evaluation action should be able to be captured on a local load test.
The trace should begin when the evaluation action receives a message.
The trace should end when the evaluation sends the message back to the main thread.
The trace should split the time taken between evaluation logic and /execute api call.

**Comment by vsvamsi1** [comment]
Was able to export telemetrics to graphana, but as per this [slack conversation](https://theappsmith.slack.com/archives/C024GUDM0LT/p1698386477997889) I am closing this task. We plan to use new relic.
