### ISSUE TITLE
[Bug]: App title drop down pop up is not getting closed automatically when user opens up omnibar using hotkeys

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#28114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

screen shot : 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/41ae3bfc-f024-4a19-970e-ece10f11f081)

### Steps To Reproduce

1. Expand app title drop down 
2. then from keyboard press ctrl+k to open omnibar pop up 

Work around : Expands app title drop down then click on omnibar without using hot keys

### Environment

Production

### Version

Appsmith v1.9.40-SNAPSHOT

**Comment by yashnirmal** [comment]
Can I work on this one?

**Comment by Shree0310** [comment]
Hi, @Nikhil-Nandagopal  will it be possible for you to assign this to me?

**Comment by Nikhil-Nandagopal** [comment]
@Shree0310 you can pick it up.

**Comment by Shree0310** [comment]
@rajatagrawal here's the issue assigned to me. Currently I am going through https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md

**Comment by rajatagrawal** [comment]
@Shree0310 

Can you please paste screenshot/logs of the error that you are facing so that I can understand the problem that you are facing ?

**Comment by saicharan-zemoso** [comment]
Hello @rohan-arthur , I am picking this issue.

**Comment by rohan-arthur** [comment]
@saicharan-zemoso awesome, and thank you!
