### ISSUE TITLE
[Task]: Create a docker image to host grafana visualizer/prometheus/tempo/grafana agent

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#28117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The docker image will be used by local appsmith code and local performance test to visualize the test results.

The docker image should have

1. Grafana agent (this will act as an agent)
2. Tempo (this will act as datastore for traces)
3. Prometheus (this will act as datastore for metrics)
4. Grafana visualizer (this will visualize data stored in step 2 and step 3)

**Comment by shubham7saxena7** [comment]
we will not be using grafana tooling anymore for telemetry and hence do not need this. Closing this issue
