### ISSUE TITLE
[Bug]: Creating a child branch from master fails to copy over queries

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#28111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a child branch from master fails to copy over queries

### Steps To Reproduce

1. Go to regression [DP](https://ee-2657.dp.appsmith.com/app/my-first-application)
2. Create a branch from master and observe queries aren't copied over to the child branch

### Public Sample App

https://ee-2657.dp.appsmith.com/app/my-first-application

### Environment

Release

### Issue video log

https://www.loom.com/share/6b7ef019d0a9450c8e615e4aefdd7922

### Version

Cloud

**Comment by Parthvi12** [comment]
Reducing priority as it's not reproducible in other apps.
