### ISSUE TITLE
[Task]: Add traces for api/v1/pages?pageId=&mode=EDIT for local perf testing

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#28118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. The trace should should be able to run on local perf test.
2. The trace should be able to split the duration of the action between server processing and mongo db querying

**Comment by shubham7saxena7** [comment]
we will not be using grafana tooling anymore for telemetry or load testing so do not need this for now

**Comment by rajatagrawal** [comment]
This is task is about ensuring that we have open telemetry for /page/edit url either on grafana or new relic. Is open telemetry present for /page/edit url in new relic ?

**Comment by shubham7saxena7** [comment]
We will have telemetry for it outside the box

**Comment by shubham7saxena7** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1PQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c23c713eb7f61f160b0326ab063ab047421c9009/Screenshot%202023-11-01%20at%2011.56.45%E2%80%AFAM.png)

https://one.newrelic.com/nr1-core/apm-features/transactions/NDIwOTU0OHxBUE18QVBQTElDQVRJT058MTA0NzA0NTEwMQ?account=4209548&duration=1800000&state=287c915a-087c-5df1-9f15-c484af414989

it is present.
