### ISSUE TITLE
[Task]: Add web vitals library to frontend metrics and report the metrics to prometheus/grafana

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#28120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The web vitals library should be included in the frontend code and report LCP and other metrics.
The metrics can pushed to local grafana instance for dev mode and cloud grafana in prod.
```[tasklist]
### Tasks
```

**Comment by shubham7saxena7** [comment]
we will open a separate task to do this via newrelic.
