### ISSUE TITLE
[Bug]: In List widget if there are more items then it show pagination. There is no option to make it in a single page.

### ISSUE THREAD

**Issue by KevalKhambhaliya1** [appsmithorg/appsmith#28125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Put a list widget. Add data source with 20-25 items. There will be auto pagination. There is no option to remove pagination and make it in single page.

### Steps To Reproduce

1. Put a list widget
2. Add data source with 20-25 items.
3. There will be auto pagination
4. There is no option to remove pagination and make it in single page.

### Environment

Production

### Version

v1.9.35

**Comment by Nikhil-Nandagopal** [comment]
Hello, we're working on scroll for the List widget here #6293

**Comment by KevalKhambhaliya1** [comment]
Thanks for the updates Nikhil.
