### ISSUE TITLE
[Bug]: App import from within the App doesn't update Query data , themes in the first go .

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#28126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you import an app from within the app , the themes , query data etc doesn't reflect immediately after importing. You need to refresh the page for the query and themes to show up in the app .

### Steps To Reproduce

1. Export a json which has some query data and themes (Choose some different theme to easily identify error )
2. Import the same JSON from within the app, 
3. Notice the updated theme and queries are not coming 
4. refresh the app, Now the data and theme will come into effect

https://www.loom.com/share/31973aa7b9cf42c8996b8dcffed1d601

### Environment

Production

### Version

Cloud/SelfHosted

**Comment by infinitetrooper** [comment]
Not a bug, the refresh needs to happen for published resources to take affect.
