### ISSUE TITLE
[Task]: Add and configure cloud grafana agent and cloud tempo instance to collect traces from prod code

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#28121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The cloud grafana agent and cloud temp should be able to receive traces from prod frontend and backend and be configured in cloud grafana visualizer for the results to be pulled from

The client should be able to push the traces to grafana agent and cloud tempo.

The existing grafana visualizer should be able to visualize the traces data stored in this grafana agent/tempo setup.

The architecture of the system can be referred to [here](https://grafana.com/docs/tempo/latest/getting-started/?pg=oss-tempo&plcmt=resources)

**Comment by shubham7saxena7** [comment]
we will not be using grafana tooling anymore so closing this.
