### ISSUE TITLE
[Bug]: Window listener function shows up as an error after upgrade

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#28157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Newly added window listener function shows up as an error after upgrade

![image](https://github.com/appsmithorg/appsmith/assets/79509062/364f5ee1-2081-45b5-966c-97e2ee75bd68)

### Steps To Reproduce

1. Type in `windowMessageListener` to the upgraded EE instance and notice the lint error

### Environment

Release

### Version

Cloud

**Comment by dipyamanbiswas07** [comment]
Could you help me with the steps? I'm unable to reproduce this on the DP.

**Comment by ramsaptami** [comment]
Seeing the error because of incorrect syntax, not related to upgrade flow. Hence closing this out
cc: @dipyamanbiswas07
