### ISSUE TITLE
[Feature]: allow setting a custom label on the `Sign in with OIDC SSO` button

### ISSUE THREAD

**Issue by SamWoolerton** [appsmithorg/appsmith#28173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Apparently this button can't be removed (would also be helpful for my client), but would be great to be able to update this text to e.g. `Sign in with SSO Okta` for a more polished user experience

### Why should this be worked on?

Doesn't sound super hard to implement, and adds more polish for business & enterprise use

**Comment by infinitetrooper** [comment]
Duplicate of https://github.com/appsmithorg/appsmith/issues/25660, closing this ticket in favour of the earlier one.
