### ISSUE TITLE
[Bug]: User is landed on "Your license is inactive" page and works on reload.

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#28171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is an intermittent issue and observed on promotional dp - https://ee-2657.dp.appsmith.com and release-ee.

### Steps To Reproduce

There is no specific steps. 
While the user was working on the instance, "Appsmith is initialising" screen appears and user land on "Inactive subscription" page.
On refresh the instance is back working

![inactive_dp](https://github.com/appsmithorg/appsmith/assets/132880870/097454e6-62c4-4dc2-96e5-9b4ad276510c)
![inactive_release_ee](https://github.com/appsmithorg/appsmith/assets/132880870/e2b84a35-b2bd-4ac0-8da0-9d25992a3430)

### Environment

Release

### Version

Appsmith v1.9.41

**Comment by btsgh** [comment]
Seeing on prod as well, after merge.

**Comment by dipyamanbiswas07** [comment]
This is fixed.
