### ISSUE TITLE
[Bug]: WDS - Input widget issues

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#28186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. When the `Required` prop is enabled, we see a red outline upon entering any text for a fraction of second.

https://github.com/appsmithorg/appsmith/assets/39921438/62ae5f2a-b804-43d1-adfe-a1a56acc71d2

2. Add punctuations for error messages:
<img width="376" alt="Screenshot 2023-10-18 at 2 29 52 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/fa33b7f7-c0fa-41a2-9b65-93693b000add">

### Steps To Reproduce

1. Enable the WDS feature flag.
2. DnD the input widget.
3. Enable the `Required` prop.
4. Now enter any text in the widget.

**Expected:** The outline should not turn red upon entering any text.
**Actual:** The outline/border turns red.

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by KelvinOm** [comment]
<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0c973d2a5822e500585c096c918669eac045a35/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-03-27%20%D0%B2%2012.37.32.png" alt="Снимок экрана 2024-03-27 в 12.37.32.png" />

Not relevant anymore.
