### ISSUE TITLE
[Bug]: ENV_APPSMITH_SUPERVISOR_USER cannot be expanded

### ISSUE THREAD

**Issue by zelenzaMMdev** [appsmithorg/appsmith#28185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

on a installation of appsmith with watchtower, this night has updated from v1..9.39 to v1.9.40 (self hosted), when tried to start the container shows this error

Format string '%(ENV_APPSMITH_SUPERVISOR_USER)s' for 'inet_http_server.username' contains names ('ENV_APPSMITH_SUPERVISOR_USER') which cannot be expanded

searching into the .env file, cannot find the ENV_APPSMITH_SUPERVISOR_USER or APPSMITH_SUPERVISOR_USER name
this file has not been modified for a long time 

this is the literal from log

Error: Format string '%(ENV_APPSMITH_SUPERVISOR_USER)s' for 'inet_http_server.username' contains names ('ENV_APPSMITH_SUPERVISOR_USER') which cannot be expanded. Available names: ENV_APPSMITH_ADMIN_EMAILS, ENV_APPSMITH_ALGOLIA_API_ID, ENV_APPSMITH_ALGOLIA_API_KEY, ENV_APPSMITH_ALGOLIA_SEARCH_INDEX_NAME, ENV_APPSMITH_API_BASE_URL, ENV_APPSMITH_CLIENT_LOG_LEVEL, ENV_APPSMITH_CLOUD_SERVICES_BASE_URL, ENV_APPSMITH_CUSTOM_DOMAIN, ENV_APPSMITH_DISABLE_TELEMETRY, ENV_APPSMITH_ENCRYPTION_PASSWORD, ENV_APPSMITH_ENCRYPTION_SALT, ENV_APPSMITH_GOOGLE_MAPS_API_KEY, ENV_APPSMITH_INSTANCE_NAME, ENV_APPSMITH_MAIL_ENABLED, ENV_APPSMITH_MAIL_FROM, ENV_APPSMITH_MAIL_HOST, ENV_APPSMITH_MAIL_PASSWORD, ENV_APPSMITH_MAIL_PORT, ENV_APPSMITH_MAIL_SMTP_AUTH, ENV_APPSMITH_MAIL_SMTP_TLS_ENABLED, ENV_APPSMITH_MAIL_USERNAME, ENV_APPSMITH_MARKETPLACE_ENABLED, ENV_APPSMITH_MONGODB_URI, ENV_APPSMITH_MONGO_HOST, ENV_APPSMITH_OPTIMIZELY_KEY, ENV_APPSMITH_RAPID_API_KEY_VALUE, ENV_APPSMITH_REDIS_URL, ENV_APPSMITH_REPLY_TO, ENV_APPSMITH_SEGMENT_CE_KEY, ENV_APPSMITH_SEGMENT_KEY, ENV_APPSMITH_SENTRY_DSN, ENV_APPSMITH_SMART_LOOK_ID, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_MONGODB_TMP_KEY_PATH, ENV_MONGO_INITDB_DATABASE, ENV_MONGO_INITDB_ROOT_PASSWORD, ENV_MONGO_INITDB_ROOT_USERNAME, ENV_NGINX_WWW_PATH, ENV_NO_PROXY, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_SUPERVISORD_CONF_TARGET, ENV_TMP

### Steps To Reproduce

1. take a from v1..9.39 installation
2. upgrade to v1.9.40 (in this case via watchtowerrr)
3. start the container
4. wait for the log

### Environment

Production

### Version

Self Hosted - 1.9.40

**Comment by Nikhil-Nandagopal** [comment]
We've merged a fix in for this and you can expect an update soon
