### ISSUE TITLE
[Bug] Fix recursive calls in DynamoDB plugin for different types

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2819]
The plugin currently only handles recursive calls for SdkPojo types. We need to introduce recursive references to Maps, and Lists as well.

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by sumitsum** [comment]
Closing it since the issue had been fixed in one of the earlier commits.
