### ISSUE TITLE
[Bug]: Removing a license throws resource not found exception if triggered by a user who get the access via custom group

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#28199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As user groups are a paid feature, removing license key fails to go to completion if the user who triggered the flow has got manage tenant permission via the user group. This is happening because as per the current flow we check the `MANAGE_TENANT` while syncing the license plan which is one of the steps in removing license flow.

Possible solution:
Add a new role `MANAGE_LICENSE` and assign this to all the instance admin even if the admin is added via custom group and use this for all the license-related CRUD ops. 

### Steps To Reproduce

1. Add business/enterprise license
2. Create a custom group and assign the instance admin role to this group
3. Invite a new user to this group
4. Signup with the new user invited in the above step
5. Try to remove the license
6. Result: No resource found exception is thrown

We end up in a situation where the Appsmith instance and the CS are out of sync. 

### Environment

Deploy Preview

### Version

v1.9.41-SNAPSHOT

**Comment by Harshask93** [comment]
Tested on the dp - https://ee-2494.dp.appsmith.com/
