### ISSUE TITLE
[Feature]: Mongo collections dropdown filtering

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#28190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

follow-up to #23962

The collection dropdown in MongoDB query editor typing to filter doesn't work, and hitting a key like u doesn't scroll to the next item starting with u. It looks like the only way is to manually scan the entire list looking for what I need, right? 

https://github.com/appsmithorg/appsmith/assets/94514895/a0223128-781a-4a96-a1db-d2dd5297441b

Conversation: https://theappsmith.slack.com/archives/C040LHZN03V/p1697624827865869

Issue for collection isn't sorted: https://github.com/appsmithorg/appsmith/issues/35842

### Why should this be worked on?

improve experience of selcting the collection - this can be a pain if there is a large number of collections

**Comment by 1Aditya7** [comment]
Hey @rohan-arthur, I'd like to pick this up and work on this! I'd like to target two main objectives:

1. Enable searching through the items of the collection
2. Enable keyboard navigation to traverse through the items of a selected/clicked alphabet one after another.

Thanks!

**Comment by rohan-arthur** [comment]
Hi @1Aditya7, thanks for your interest! Unfortunately, this issue isn't ready to be picked up yet - we need to first get a component into our design system.

Please look at issues with the label `Up for grabs`, and see if you find anything interesting there.

**Comment by 1Aditya7** [comment]
No worries, @rohan-arthur!

Sure I'll have a look at up for grabs issues, thanks!

**Comment by Naveen-Goud** [comment]
Hii @rohan-arthur , Can I pick this ticket ?
