### ISSUE TITLE
[Feature]: Connect to BitBucket with username and password

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#28200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user would like to connect their apps to BitBucket using a username and password instead of SSH.

### Why should this be worked on?

The users company does not allow SSH key authentication on Bitbucket under their company’s security policy. They are limited to the username and password. They also cannot use a service other than BitBucket.

**Comment by Nikhil-Nandagopal** [comment]
I believe this is the same as #20082 so closing this in favor of that
