### ISSUE TITLE
[Bug] Table colour must be displayed to user based on the selection priority 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2821]
Steps to reproduce:
1) Add a table
2) Navigate to a column setting
3) Add a background colour to a column
4) Navigate to table setting 
5) Add a background colour to entire column
and observe

Observation:
It is observed that the column with respective colour does not display any colour

Expectation:
1) We should either show the respective column colour selected by the user
OR
2) overlap the respective Table colour to be displayed to the user 

Please find the video attached below:
https://www.loom.com/share/a848eabec85149bf8fa550b896779c54

**Comment by riodeuno** [comment]
Closing this, as a design decision.
