### ISSUE TITLE
[Feature]: Rest API plugin: enable HTTP 2.0 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#28226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- Enable HTTP 2.0 protocol for web client based requests. 
- [ref](https://github.com/appsmithorg/appsmith/issues/27919)
- Update (25 Oct 2023):
  * My understanding so far had been that if multiple HTTP protocols are enabled then the webclient and the remote server can negotiate (e.g ALPN protocol) automatically on which protocol to use. 
  * An CI failure caught an [edge case](https://docs.arangodb.com/3.11/develop/http/general-request-handling/#switch-protocols) where the remote server was not able to automatically figure out which protocol to use between `HTTP` and `H2C` - thus causing the API request to fail.  
  * Based on the above two points my new understanding is that the preferred solution to this problem should be a selector configuration provided to the user on the action configuration page to select the preferred protocol
  * [previous attempt at fix](https://github.com/appsmithorg/appsmith/pull/28247) 

### Why should this be worked on?

- new feature

**Comment by NilanshBansal** [comment]
Release blockers being prioritised
