### ISSUE TITLE
Investigate LCP vs Speed Index

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#28228]

**Comment by SatishGandham** [comment]
Speed index is not part of core web vitals. We might not be able to capture it for every user, even if we did, might not be a good idea.

> Speed Index measures how quickly content is visually displayed during page load. Lighthouse first captures a video of the page loading in the browser and computes the visual progression between frames. Lighthouse then uses the [Speedline Node.js module](https://github.com/paulirish/speedline) to generate the Speed Index score.
