### ISSUE TITLE
[Bug]: Nav bar menu overlapping on appsmith.com

### ISSUE THREAD

**Issue by minkyngkm** [appsmithorg/appsmith#28234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It might be a minor issue but I just found out that this menu item "Pricing" and "Book a demo" button on the nav bar overlap on appsmith.com on medium screens. Maybe it looks better if it's fixed? 🙂

![image](https://github.com/appsmithorg/appsmith/assets/57550290/b919029f-7e9a-41aa-8824-12bdea9ed3ce)

### Steps To Reproduce

1. Go to https://www.appsmith.com
2. Scroll down a bit until you see "Book a demo" button switched from "Login" button
3. Reduce screen size and see the bug.

### Environment

Production

### Version

N/A

**Comment by Nikhil-Nandagopal** [comment]
Thanks for reporting! This is an issue related to our website and we track those internally.
