### ISSUE TITLE
[Bug]: Add validations for Emphasis property

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#28252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Although the Expected structure says `String`, on entering a value starting with upper case for `Emphasis` does not render appropriately. Can we please make this consistent?
<img width="714" alt="Screenshot 2023-10-20 at 11 54 10 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/94c7f6d0-7fbf-42d7-95b3-87f597c7c703">

### Steps To Reproduce

1. DnD a Text widget.
2. Go to the property pane and enable the `JS` option for `Emphasis`.
3. Now enter `Bold` or `Italic`.

**Expected:** We should get an `Disallowed value` error as the first character is in upper case.
**Actual:** We neither get an error nor does the emphasis render on the canvas

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
