### ISSUE TITLE
Enhancement : The table name and column name does not get dynamically updated 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2826]
Steps to reproduce:
1) Add a table
2) Click on property pane of the table
3) Click on the column control setting 
4) Rename the column or the table name 
and observe 

Observation :
It is observed that the column name does not get updated dynamically however it gets updated upon a click 

Expectation:
A consistent behaviour is an expectation where the column name or data get dynamically updated into the column as and when we type

**Comment by riodeuno** [comment]
This feature is fixed now. @prapullac Please re-open if this still exists
