### ISSUE TITLE
[Bug]: Unable to edit Environment even if user has edit permissions on the Environment.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user is given edit permission on an environment, he is still unable to edit the environment

### Steps To Reproduce

1. For a role, give a user only edit permissions on an environment for a particular workspace. 
2. Assign this to a group to which you can add a user.
3. Login with the above user, and note that he is not able edit the environments in manage environments screen

https://github.com/appsmithorg/appsmith/assets/101863839/649a91d7-464f-419b-8dde-f86aa8aebe1a

### Environment

Deploy Preview

### Version

Cloud

**Comment by u6516595** [comment]
Hello. Can i try this?
