### ISSUE TITLE
[Bug]: How to add GitHub OAuth users??

### ISSUE THREAD

**Issue by mehaase** [appsmithorg/appsmith#28274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I see #1018 is already open for inviting github users. My report is not a duplicate because I'm asking what is the workaround for #1018. Details below...

I've got Github OAuth set up and working. Now I want to add a GitHub user to my workspace. So I invite a user (my own test account in a separate browser profile), click the invite link, it takes me to appsmith, I click "continue with github" and go through that, then it brings me back to appsmith. Now I'm signed in but I just see a personal workspace, I don't see the workspace that I was invited to.

In my profile the "email" is actually my github name and there's no way to change it. I can't "invite" somebody based on a GitHub username, only email, but it seems that access control is tied to email only... which doesn't get populated from GitHub. (I mean... even if you did get the email address from the GitHub API, what would happen if it doesn't match the invitation email? E.g. I invited my work email address but signed in with a github account linked to my personal email.)

**Is there a workaround? I don't mind doing some extra steps, I just feel like GitHub Oauth is completely unusable in its current state. How you grant access to a github user?? Am I missing something?**

### Steps To Reproduce

1. invite a test user
2. click the invite link
3. it takes me to appsmith
4. click "continue with github" and go through Oauth flow
5. it brings me back to appsmith
6. Now I'm signed in but I just see a personal workspace, I don't see the workspace that I was invited to

### Environment

Production

### Version

Appsmith Community v1.9.37.1

**Comment by mehaase** [comment]
I'm a little confused. Seems like there are two types of invite links. Once contains an email address: `http://localhost/user/signup?email=foobar%40company.com`. The other contains an application link: `http://localhost/applications#6511dd93002f8e59377561f3`.

Even if you use the email link, your email field is still set incorrectly. The other link seems to be stateless, i.e. the permission is already granted and the email is more like a notification?? I.e. clicking the link doesn't "accept" the invitation, it just takes you to the app you've already been granted to?

**Comment by mehaase** [comment]
Doing more investigation... it seems like users can sign up on my appsmith instance with any github account, regardless of whether they were invited or not.

That's definitely not ideal. Random people can start running code on my server and using my resources.

**Comment by mehaase** [comment]
I found i can workaround with some mongo and redis commands:

```
> db.permissionGroup.updateOne({_id: ObjectId("6532967aef28476c3d0a1be5")}, {"$push": {assignedToUserIds: "65329617ef28476c3d0a1bd6"}})

> db.permissionGroup.find({name: "App Viewer - Important Stuff"},{"name": true, "assignedToUserIds": true})
[
  {
    _id: ObjectId("6532967aef28476c3d0a1be5"),
    name: 'App Viewer - Important Stuff',
    assignedToUserIds: [ '6532972bef28476c3d0a1be6', '65329617ef28476c3d0a1bd6' ]
  }
]
```

and then I need to flush the redis cache:

```
127.0.0.1:6379> flushall
OK
127.0.0.1:6379> keys *
(empty list or set)
```

This logs everybody out 😢 but it works! Is there a workaround that's less kludgey?

**Comment by Nikhil-Nandagopal** [comment]
@mehaase Your assessment is correct and we don't have a workaround for this. #1018 is the issue to track
To disable signups of uninvited users, you can configure this environment variable 
https://docs.appsmith.com/getting-started/setup/instance-configuration/disable-user-signup#disable-signup

You cannot invite a GitHub user account to a workspace and only invite an email ID.

**Comment by mehaase** [comment]
Thank you for the reply @Nikhil-Nandagopal. Is there any feature in the enterprise version that overcomes this? I see there are some access and provisioning features in enteprise but I'm not sure what those are.
