### ISSUE TITLE
[Bug]: Onload queries have stopped working

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#28288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Onload queries of exsisting App stopped working

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1698039103129319

Appsmith version: Appsmith Business v1.9.39-SNAPSHOT

### Steps To Reproduce

Steps
1) Launch the app 
2) Go to edit mode
3) Go to Page "Other Stats"
4) all queries on this page fail to load

### Public Sample App

https://internal.appsmith.com/app/cypressdashboard/allruns-64ec3df0c632e24c00764937?branch=master

### Environment

Production

### Issue video log

https://www.loom.com/share/842297cffae545fb95a79c551df60202

### Version

Self-Hosted  v1.9.39-SNAPSHOT

**Comment by rohan-arthur** [comment]
conversation here: https://theappsmith.slack.com/archives/C040LHZN03V/p1698058169035069

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we couldn't reproduce and won't fix
