### ISSUE TITLE
[Bug]: tab navigation gets stuck when an non-focusable widget is on the way

### ISSUE THREAD

**Issue by danguilherme** [appsmithorg/appsmith#28341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, Appsmith stops tab navigation if a non-focusable element is on the way. Let's consider the following UI:

<img width="568" alt="image" src="https://github.com/appsmithorg/appsmith/assets/1488378/797a68ad-b88b-4b55-8f00-0deebf9ae31d">

If you have the focus on the first input, pressing tab wouldn't do anything.

Video of the behaviour:

https://github.com/appsmithorg/appsmith/assets/1488378/6cac6e01-a8ff-47cf-bf6b-b95e7c599128

### Steps To Reproduce

1. Create a new/open existing project
2. Add focusable widget like an input or button
3. Add a non-focusable widget like the chart or map widget
4. Focus the focusable widget and press tab
5. Nothing happens.

### Public Sample App

https://app.appsmith.com/app/tab-navigation-bug-demo/page1-64edb2da8f62002e5ee23be4

### Environment

Production

### Issue video log

https://github.com/appsmithorg/appsmith/assets/1488378/6cac6e01-a8ff-47cf-bf6b-b95e7c599128

### Version

Cloud (app.appsmith.com)

**Comment by Nikhil-Nandagopal** [comment]
@danguilherme thank you for the contribution! @jsartisan from our team is reviewing your PR.
