### ISSUE TITLE
[Bug] Editor form label is not displayed on UI

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2835]
## Description
1. Label 'Content' is not displayed with the following editor.json file configuration used for s3 plugin query editor: 
```
 {
  "editor": [
    {
      "sectionName": "",
      "id": 1,
      "children": [
        {
          "label": "Action",
          "configProperty": "actionConfiguration.pluginSpecifiedTemplates[0].value",
          "controlType": "DROP_DOWN",
          "isRequired": true,
          "initialValue": "LIST",
          "options": [
            {
              "label": "List all files in bucket",
              "value": "LIST"
            },
            {
              "label": "Create a new file",
              "value": "UPLOAD_FILE_FROM_BODY"
            },
            {
              "label": "Read file",
              "value": "READ_FILE"
            },
            {
              "label": "Delete file",
              "value": "DELETE_FILE"
            }
          ]
        },
        {
          "label": "Bucket Name",
          "configProperty": "actionConfiguration.pluginSpecifiedTemplates[1].value",
          "controlType": "INPUT_TEXT",
          "isRequired": true,
          "initialValue": ""
        },
        {
          "label": "File Path",
          "configProperty": "actionConfiguration.path",
          "controlType": "INPUT_TEXT",
          "initialValue": ""
        },
        {
          "label": "Content",
          "configProperty": "actionConfiguration.body",
          "controlType": "QUERY_DYNAMIC_TEXT",
          "initialValue": ""
        }
      ]
    }
  ]
}

```
![Screenshot 2021-02-03 at 12 02 11 PM](https://user-images.githubusercontent.com/1757421/106707740-bdd3fe00-6617-11eb-989f-6a54c9643979.png)

### Steps to reproduce the behaviour:
1. Copy the above configuration in an editor.json file for any plugin.
2. Run appsmith server. 
3. Create new query. 
4. Check that label is missing in the query editor form.

### Important Details
 - Version: Cloud
 - OS: MacOS
 - Browser: Chrome

**Comment by Nikhil-Nandagopal** [comment]
Instead of 2 separate fields for QUERY_DYNAMIC_TEXT and INPUT_TEXT, can we have a single field that simply expands as it does everywhere else in the application?

**Comment by ofpiyush** [comment]
@Nikhil-Nandagopal the problem is figuring out which context the code is running under.

Dynamic text needs to know which entity it is associated with. I had to do the same for #2983

I guess we can use state to populate or pass on this information, but that will be larger refactor for some day.

**Comment by Nikhil-Nandagopal** [comment]
@ofpiyush @hetunandu sounds like a code design problem. I don't see why the component should be aware of that since it's only doing auto-complete. If it's for validation then that can be optionally passed to the component
