### ISSUE TITLE
[Task]: Make `createdAt` field transient in ActionDTO

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#28355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Reference - https://theappsmith.slack.com/archives/CPQNLFHTN/p1698215852771549

**Comment by riteshkew** [comment]
@sondermanish @nidhi-nair Is this already resolved as part of Git DSL cleanup?

**Comment by nidhi-nair** [comment]
This should be fixed.
