### ISSUE TITLE
[Bug]: Deleting a page with table widget that's connected to API data causes page crash

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#28373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a table is populated with data from an API query (other than appsmith mock API), and the page is deleted, the app crashes as seen in the video

![image](https://github.com/appsmithorg/appsmith/assets/79509062/ebbc8b5a-e515-4c22-acf1-86ff8cc42906)

### Steps To Reproduce

1. create an API query using any API other than appsmith mock URL 
(eg: https://jsonplaceholder.typicode.com/posts or https://restcountries.com/v3.1/all)
2. Run the API and add a table to the page from snipping mode
3. Confirm table is present on the page
4. Now delete the page and observe the page crash

### Environment

Production

### Issue video log

https://www.loom.com/share/3cdd130b6d6f4643b38273177bb30788

### Version

Cloud

**Comment by btsgh** [comment]
Couple of observations - 

1. Tried with some random apis like - 
https://datausa.io/api/data?drilldowns=Nation&measures=Population 
https://api.publicapis.org/entries
https://reqres.in/api/users?page=2
and the crash is not reproducible on them either on release or on Prod. 

2. The crash is reproducible on both the above apis that @ramsaptami  has shared - on prod as well as release.

Question @ramsaptami  - do you think we need not treat it as a release blocker as its already on prod? We could mark it critical on Prod for now.

**Comment by mohanarpit** [comment]
Aside: The 500 error page belongs to the old design. Is there a reason that the UI is showing an older design instead of the ADS compatible error page in this instance?

**Comment by rohan-arthur** [comment]
quoting Sneha from [here](https://theappsmith.slack.com/archives/C040LHZN03V/p1698300281867299?thread_ts=1698299447.160289&cid=C040LHZN03V):
The issue is not specific to REST API plugin, its originating somewhere in one click binding of widget, even if we do not bind the query to widget and delete the page, we see the error. Can someone from widgets team check this out? given that they would have more context on this
