### ISSUE TITLE
[Feature]: Table header API 

### ISSUE THREAD

**Issue by wangwwwork** [appsmithorg/appsmith#28418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The table header is from table data; How to modify this by api?

### Why should this be worked on?

We have the api that return the table header； We want to load the header through the api data;

**Comment by Nikhil-Nandagopal** [comment]
@wangwwwork you can change the names of the keys of the table data using javascript to alter the header

**Comment by wangwwwork** [comment]
> @wangwwwork您可以使用 javascript 更改表数据的键名称来更改标题

Sorry, I need help!  The data from api  like this [{age: 12....}]， then the header is show "age"; I want alter the "age" to "B.E" , but the field name "age" is param for update。So I could not th change the data to [{"B.E": 12...}]

**Comment by Nikhil-Nandagopal** [comment]
@wangwwwork you can get help on our discord community https://discord.com/invite/rBTTVJp
