### ISSUE TITLE
[Feature] Git configuration sync

### ISSUE THREAD

**Issue by mikefrancis** [appsmithorg/appsmith#2842]
## Summary

Configure AppSmith to fetch it's applications from a Git repository

## Motivation

Rather than having a database as the source of truth for applications, it would be great if they could be persisted in a Git repository which AppSmith instances can then (via a URL and custom branch) read and/or write to/from via SSH.

This unlocks the ability to have dev, staging and production instances of AppSmith with their apps managed in a GitFlow workflow.

**Comment by Nikhil-Nandagopal** [comment]
@mikefrancis thank you for the feature request. This is indeed something we are considering today. We'll implement this as a part of version control tracked in this issue #2285 and will allow users to revert apps to previous versions as well as import/export applications.

**Comment by mikefrancis** [comment]
Closing as duplicated by #2285
