### ISSUE TITLE
[Bug]: Need a tooltip for the Edit/Roles/Delete buttons on the Environments page.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the environments page, there are buttons for edit/delete and to get to roles page .. but currently there is no text or tooltip to indicate the use of the buttons. A tooltip is required for these. [Especially for the roles button, as the image is not an indicator at all as to where user will be taken]

### Steps To Reproduce

<img width="998" alt="Screenshot 2023-10-27 at 11 37 13 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/83b520eb-bd49-43fd-800f-464f4fcc1737">

### Environment

Deploy Preview

### Version

Cloud

**Comment by ayushpahwa** [comment]
@parth-appsmith please look into this

**Comment by Nikhil-Nandagopal** [comment]
Nice enhancement but since it wasn't expected in the first place, let's wait for users to give this feedback
