### ISSUE TITLE
[Bug]: The scroll bar should be displayed on configuration page when there are more than 2 custom environments 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#28439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The scroll bar should be displayed on configuration page when there are more than 2 custom environments 
![image](https://github.com/appsmithorg/appsmith/assets/45958978/86e03fb8-a87c-431d-9242-b87f93baf59c)

### Steps To Reproduce

1. go to https://ee-2209.dp.appsmith.com/
2.login with admin emails
3.go to datasources
4. add the datsurces with 2 to 3 custom env
5. now go to configuration page 
6. we cant see the data of more than 2 custom env as there is a missing scroll bar 

### Environment

Deploy Preview

### Version

v1.9.43

**Comment by btsgh** [comment]
Tested in Latest dp - has been fixed.

**Comment by btsgh** [comment]
Is reproducible on promotion [DP](https://ee-2817.dp.appsmith.com/)

**Comment by btsgh** [comment]
Tested on the promo dp - works fine now.
