### ISSUE TITLE
[Bug]: The error message is displayed under binding section when user switchs between the different environment 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#28440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The error message is displayed under binding section when user switchs between the different environment 
![image](https://github.com/appsmithorg/appsmith/assets/45958978/c4ac5157-2971-488f-a5c8-7b003ffb7b15)

### Steps To Reproduce

1. go to https://ee-2209.dp.appsmith.com/
2. login with admin cred
3. add few datasources
4. now add few custom envs
5. Now drag and drop a table and bing it with a data
6. now switch between the envs the error message is displayed in property pane under table data 

### Environment

Deploy Preview

### Version

v1.9.43

**Comment by btsgh** [comment]
Tested and found to be fixed in latest dp
