### ISSUE TITLE
[Task]: Update Appsmith app to talk to Launch Darkly instead of Flagsmith with the exact same functionality that we have today on the self serve app 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#28442]
App link: https://app.appsmith.com/app/flagsmith-control/user-flags-65029f781045a805525b3e3d

**Comment by deepika-appsmith** [comment]
closing ticket as the app is available to use.
https://internal.appsmith.com/app/feature-flag-launch-darkly/segments-65d5d1ff52b5d661d34dc751
