### ISSUE TITLE
[Bug]: The data inside the delete environment modal is not intuitive 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#28444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The data inside the delete environment modal is not intuitive  below are the few cases
No differentiation between the env name, workspace name
All 1 Datasources does not make sense.
Env name starts with capital in some places, and small case in some
![image](https://github.com/appsmithorg/appsmith/assets/45958978/fda2963b-d5e0-4471-ae8f-bdb9e6c87bc3)

### Steps To Reproduce

1. go to https://ee-2209.dp.appsmith.com/
2. Add few custom env
3. No go to the environments tab and try to delete any one env
4. The data inside the delete environment modal is not intuitive to users

### Environment

Deploy Preview

### Version

v1.9.43

**Comment by ayushpahwa** [comment]
Duplicate for https://github.com/appsmithorg/appsmith/issues/28016
