### ISSUE TITLE
[Feature]: All pages can share js file

### ISSUE THREAD

**Issue by yangfq998** [appsmithorg/appsmith#28457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In our project, in many cases, multiple pages need to use the same js files and methods, so we would like to have a solution that has common js for the entire APP, thank you!

### Why should this be worked on?

Instead of copying the same js file for each page, we can define global methods that work together.

**Comment by Nikhil-Nandagopal** [comment]
@yangfq998 we're working on this feature here #1911 
You can register for the beta program and get early access to it along with sharing your feedback on the feature on the link below
https://app.appsmith.com/app/betasmith/registration-652933ef23a9db3488a04d25?id=7

**Comment by yangfq998** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
