### ISSUE TITLE
Create WDS select component

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#28466]

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/28466?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm

**Comment by dhruvikn** [comment]
@KelvinOm - before adding my estimate for the planning poker, can you please add the designs and/or any relevant docs for this component? I would like to gather some context before estimating.

**Comment by jsartisan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/28466?planning-poker) with Zenhub @jsartisan

**Comment by KelvinOm** [comment]
@dhruvikn

- Reuse the wds components [Menu](https://release--64c89da059b7d62ad3a60544.chromatic.com/?path=/docs/design-system-widgets-menu--docs) and [TextInput](https://release--64c89da059b7d62ad3a60544.chromatic.com/?path=/docs/design-system-widgets-textinput--docs) as the basis of the Select. 
- As part of the task, it is necessary to analyse the property pane in prod and add the necessary functionality (create tickets for this).

**Comment by dhruvikn** [comment]
Have added my estimate.
