### ISSUE TITLE
Apply WDS tokens in navigation tabs

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#28467]

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/28467?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm

**Comment by dhruvikn** [comment]
@KelvinOm - would this be for the app navigation?

**Comment by KelvinOm** [comment]
@dhruvikn Yes, this is one of the pieces of the puzzle that we have to do before release new UI/UX.

<img width="841" alt="Снимок экрана 2023-11-15 в 11 56 33" src="https://github.com/appsmithorg/appsmith/assets/11555074/5d839379-6278-4541-81a1-29e63585a4dd">
