### ISSUE TITLE
[Task]: Decrease Z-index of connect overlay for widgets like Table widget

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#28471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Table widget uses something called connect overlay which currently is an absolutely positioned 9 div.
This makes it harder for the mouse to access the parent canvas layer while Drag and Dropping.
Lets make it a less z index div also positioned relative to the widget wrapper so that the canvas is accessible to DnD.

**Comment by carinanfonseca** [comment]
Closing this one since it will addressed by Anvil.
