### ISSUE TITLE
[Bug] The form gets reset to the wrong value post update

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2848]
### Steps to reproduce the behavior:
1. Drag a table and bind it to a data set
2. Drag a form and bind the input in it to a column in a table
3. Create a query to update the data and fetch the new results
4. Bind it to the form button
5. Update a data set
6. The value in the form is reset to the wrong value

https://user-images.githubusercontent.com/3897254/106753851-3c4d9180-6652-11eb-9f95-91a28374a9b0.mov

**Comment by hetunandu** [comment]
Narrowed down to an issue with the MetaHOC and how it manages state of the widget. Problem stems from multiple updates to properties after the input has been reset because of the form. If you remove the input from the form , the issue does not happen.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu this issue is critical because
- Reported by user
- Very common flow
- Breaks all existing apps and makes people think that it did not get updated

**Comment by Nikhil-Nandagopal** [comment]
Closing as it seems to be working

**Comment by Nikhil-Nandagopal** [comment]
Reopening because if the default row is set, the value in the form is not updated to it
