### ISSUE TITLE
[Bug] Default row of table does not set "selectedRow" property on page load

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2849]
## Steps
1. Drop a table with a default selected row
2. Bind a text widget with the table selected row
3. Refresh the page
4: Observe: The text does not get the selected row value

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno can we please fix this?

**Comment by vicky-primathon** [comment]
@hetunandu  this issue is working on release. 
https://www.loom.com/share/36ed0b21abd04a9fa7ada235392468c4

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working
