### ISSUE TITLE
[Bug]: When only appviewer access is given to a git connected app, unable to see data on logging in as appviewer

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When only appviewer access is given to a git connected app, unable to see data on logging in as appviewer [https://ee-2776.dp.appsmith.com/]

This works fine on release-ee.

### Steps To Reproduce

1. Open a git connected app, share the application from with the app with a user, by giving only app-viewer rights
2. Login with the above user.
3. Launch the app and note that no data is seen.

https://ddpa7mfuvv.vmaker.com/record/pGBEAkp9pH1EkEHe

### Environment

Deploy Preview

### Version

Cloud

**Comment by btsgh** [comment]
FYI - a [bug](https://github.com/appsmithorg/appsmith/issues/28052) similar to this was found on a custom env DP, which was fixed on the DP by @sondermanish .

**Comment by nsarupr** [comment]
@btsgh, if this issue is easily reproducible, can you re-record the same with the network tab opened, so that we can take what is failing exactly. Because in the video, there is an error thrown, `Resource not found`, and I would like to know which resource is throwing that errlr.

**Comment by btsgh** [comment]
https://github.com/appsmithorg/appsmith/assets/101863839/ebfd894d-a932-439e-b865-df59207f765e

@nsarupr hope this helps

**Comment by nsarupr** [comment]
> Screen.Recording.2023-10-31.at.5.16.00.PM.mov 
> @nsarupr hope this helps

Thanks for sharing this. From the looks of it, it would seem that there is no API which is failing. And hence, we will need to take a deeper look into this. 
@sondermanish can you please check if this has something to do with the Environments, since there is no permission error being thrown.

**Comment by sondermanish** [comment]
We are not able to reliably reproduce this issue on any other apps, apart from one app. 
reducing the priority to critical instead of release blocker.
@nsarupr @deepikaappsmith

**Comment by btsgh** [comment]
https://github.com/appsmithorg/appsmith/assets/101863839/bd24c238-8d92-432d-9c5a-1a680ea74c0c

**Comment by deepika-appsmith** [comment]
@btsgh - is this something we see even now? if not lets close the issue please.

**Comment by btsgh** [comment]
Unable to reproduce this on release. Tried this on one git connected app and as an appviewer, I was able to view the data on launching.
