### ISSUE TITLE
Create a separate theme settings panel for WDS

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#28516]
As part of the task, we need to create separate theme settings panel for WDS under `ab_wds_enabled` feature flag.

The difference between the new theme settings panel and the existing one:
— remove secondary color
— change label to be “accent color”
— add dark mode switch
— remove shadow
— remove redundant label "App font"
— remove theme thingie at the top

![image](https://github.com/appsmithorg/appsmith/assets/11555074/3daf4f59-f199-4eaf-b730-f125b3cc71e7)

**Comment by somangshu** [comment]
@ichik do we need to detail the requirement more development?

**Comment by ichik** [comment]
@somangshu should be already clear, I think.

**Comment by KelvinOm** [comment]
@Vadim Do we need add density and sizing controls to theme?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2YwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0959139584eb50d830ad52d1c15ff1a43887c7c0/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202023-11-21%20%D0%B2%2015.53.38.png)

**Comment by ichik** [comment]
Let's change labels to be a bit more human-readable for these controls. Should read like this:
```
Density
dense ------ loose

Sizing
small ------- big
```

**Comment by somangshu** [comment]
fyi @riodeuno
