### ISSUE TITLE
[EPIC]: Custom widgets

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#28537]
Provide a way for app developer to write custom components in their app.

designs - https://www.figma.com/file/dM8iA63UdQfVYMvO9u1eNB/%E2%9A%99%EF%B8%8F-Custom-Widget?type=design&node-id=282-10267&mode=design&t=YqKv3TbRZEMnTU63-0

**Comment by somangshu** [comment]
Related issue https://github.com/appsmithorg/appsmith/issues/2033

cc @sbalaji1192 please make sure that the main issue is closed when the code is merged in!
