### ISSUE TITLE
[Feature]: Datasource Environment as AppSmith Property

### ISSUE THREAD

**Issue by elbiedeswardt-troy** [appsmithorg/appsmith#28540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be very helpful to have the current AppSmith Datasource Environment (production / staging) as an AppSmith property to be accessed during coding. A lot like  the `appsmith.mode` property.

### Why should this be worked on?

We have a scenario where our queries tenant values need to be appended with the word "demo" in the staging environment and I therefore require a way to distinguish the two.

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/cnv_17zsaw3w?key=-xoaG17MDmVJKCwibNOiq-rF_wXqI5-8) requested for this feature.

**Comment by Nikhil-Nandagopal** [comment]
@elbiedeswardt-troy @ame-appsmith this can be picked from the URL query params so I'm closing this issue

**Comment by kylemantesso** [comment]
@Nikhil-Nandagopal it doesnt load with that query param though, it only gets added after it has been selected

**Comment by Nikhil-Nandagopal** [comment]
@kylemantesso that is because by default the value is production so that is the fallback you may need to add to your code.
