### ISSUE TITLE
[Bug]: Download as Excel feature for table widget

### ISSUE THREAD

**Issue by BorenTsaiAMD** [appsmithorg/appsmith#28541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/appsmithorg/appsmith/assets/132530265/8bbe71a9-fd94-47e9-aa24-7c0cc54f4ea8)
When I use the auto repair feature in Excel to open the file with above error, I get this message and the file's still broken:
Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Illegal xml character. Line 252, column 3636.

I wasn't able to replicate the issue on the dev environment of ours, the problem only occurs on our client's prod environment.
I feel this might have something to do with specific texts in the data of the table widget.

### Steps To Reproduce

1. Populate a table widget with some data
2. Use table widget's download feature to download as excel
3. Open the excel to find the error message

### Environment

Production

### Version

Self hosted v1.9.43

**Comment by Nikhil-Nandagopal** [comment]
@BorenTsaiAMD it's a bit difficult to debug this issue without an example of the data where it fails. Could you help us with that data so we can debug it?
