### ISSUE TITLE
[Task]: Add a new flag for including changes of start with data, if we use existing flag of templates, all half done changes will be visible in the prod

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#28548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

https://www.notion.so/appsmith/Task-breakdown-Start-with-data-787dd729e71e452abe14b46acae6e931?p=3c1ace36a65149519b6bc59d718cae2d&pm=s

**Comment by sumitsum** [comment]
[Introduced a new flag](https://theappsmith.slack.com/archives/C05P3ME9MBR/p1699259057461029) for development of this feature.

**Comment by sumitsum** [comment]
Re-opened it to add some minor code changes.
