### ISSUE TITLE
[Bug]: Form input field display value not updated

### ISSUE THREAD

**Issue by maksd** [appsmithorg/appsmith#28558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Form text input field display value is not updated (but the value is), when we quickly select an item from a table widget.

I discovered that if I removed the onSelectedRow JS event from the table widget this behaviour is gone. Also, it seems to be happening only on Single-line and Multi-line text widgets.

Unfortunately I cannot share the application.

### Steps To Reproduce

1. Add a "onSelectedRow" JS event to a table widget, anything would do, ex: `{{JSObject1.myvar1 = table.selectedRow.name}}`
2. Create a form with each table column link to a widget
3. Quickly select items from the table widget

here is a sample data from the video [tabledata.json](https://github.com/appsmithorg/appsmith/files/13230243/tabledata.json)

### Environment

Release

### Issue video log

https://www.loom.com/share/ef167dfe79a44b36b6087c557652015f?sid=0c93eebb-526f-4186-94bc-1587695e008e

### Version

Self Hosted - 1.9.42

**Comment by Nikhil-Nandagopal** [comment]
@maksd I'm not able to reproduce this issue. Could you try replacing the table widget with a new table widget by dragging a new one to see if this persists? If it does, could you create a sample application where you can reproduce this on app.appsmith.com and share that with us?
