### ISSUE TITLE
[Bug]: Auto-Layout - Height of Text Widget Not Fitting MultiLine Text Set Programmatically in Text Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#28556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user has enabled auto-layout and updates the text of a Text widget programmatically, at the click of a button that runs a JS function. If the height of the new content exceeds the initial height of the Text widget, the text is cropped and the height of the text widget does not increase to fit the new content. This issue occurs only in the deployed view of the app and works fine in edit mode.

### Steps To Reproduce

1. Add a **Text widget** and a **Button widget** to the canvas.
2. Create a JS function that sets the text of the Text widget programmatically, and run this function onClick of the button.
3. Ensure the new text set programmatically in the Text widget is multi-line and exceeds the height of the initial content.
4. Deploy the app and click the button to set the text programmatically (see screen recording and sample app).

### Public Sample App

https://app.appsmith.com/app/autolayout-text-height/page1-65424143e13a2c24b30e0014

### Environment

Production

### Issue video log

https://www.loom.com/share/b8579966032c4526af25f56c5662d372

### Version

v1.9.43

**Comment by Shree0310** [comment]
Hi, @Nikhil-Nandagopal  if this is still ongoing, then I'd like to contribute to this.

**Comment by Nikhil-Nandagopal** [comment]
@Shree0310 this is not a good first issue. I've already assigned one to you

**Comment by janbre** [comment]
Is there any progress on this issue? It impacts several of our users who use our Appsmith apps on their phone, and it's a major annoyance having to work around this issue in order to have necessary information in the apps displayed and readable.

This is a regression, as the feature has worked fine in previous releases, and considering it's a paid product we expect it to be fixed and prioritized higher than adding new features.

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith @janbre this seems to be working for me on the latest release on cloud. Are you still able to reproduce this?

**Comment by ame-appsmith** [comment]
@Nikhil-Nandagopal it is still reproducible if auto-layout is enabled (see [sample app](https://app.appsmith.com/app/autolayout-text-height/page1-65424143e13a2c24b30e0014)).

**Comment by Nikhil-Nandagopal** [comment]
@janbre we're looking into this issue. There are some problems with our auto-layout feature and we're actively re-hauling it which may take some time. Are your users using the app both on desktop and mobile? Is a mobile only app an option for you?

**Comment by riodeuno** [comment]
@ame-appsmith @janbre We've found the root cause of the issue, and are working on a fix at the moment. We'll have the fix available to users as soon as we can.

**Comment by janbre** [comment]
Great! Thanks for the update and quick response! 
We use the app both on mobile and desktop, as it's used by people in the office and out in the field doing service at customers locations so we cannot use a fixed layout.
