### ISSUE TITLE
[Task]: Handle skip, open application editor

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#28554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://www.notion.so/appsmith/Task-breakdown-Start-with-data-787dd729e71e452abe14b46acae6e931?p=80d3c81a780a45408563d1fb40f98044&pm=s

### Why should this be worked on?

activation - onboarding revamp

**Comment by Nikhil-Nandagopal** [comment]
This is a task not a feature

**Comment by AmanAgarwal041** [comment]
This is already handled by https://github.com/appsmithorg/appsmith/pull/29020
