### ISSUE TITLE
[Task]: Datasources page changes in package editor

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#28568]
https://www.notion.so/appsmith/How-are-we-planning-to-handle-the-New-query-button-for-packages-Today-this-button-needs-page-perm-bf440edd642c41b990c44cd8aefa108b?pvs=4#d9b2221d917f4e88b43f4fc1b9d1f492

**Comment by kamakshibhat-appsmith** [comment]
1. Create new datasource from Module editor is not redirecting to datasources page- Need to handle this as well 
<img width="1132" alt="Screenshot 2023-11-08 at 4 56 10 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/1774b157-6d2c-436a-95f0-9fa20e5f4c75">
@ashit-rath
