### ISSUE TITLE
[Bug] copyToClipboard action does not work with multiline text

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2857]
## Summary
Allow for users to copy multi-line text.
Message from cinemawern on Discord:
For example: {{copyToClipboard('First Line\n Second Line?')}}
So it gets copied as multiline:
First Line
Second Line etc..

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu looks like a big miss in the action

**Comment by Nikhil-Nandagopal** [comment]
Closing since it looks like it's related to #2862
