### ISSUE TITLE
[Task]: Update position usage in WidetNameCanvas

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#28586]
Current implementation - Positions are used directly from the store.

Objective:

1. Fetch positions from store and recursively keep adding to the left and top values from parentDropTargetLayouts until MainCanvas is reached.

**Comment by marks0351** [comment]
I am not going to change left, top values that we already capture instead i am going to add offsetTop and offsetLeft for all layout positions. so no changes would we required for this task. so closing it.
cc: @prsidhu @riodeuno
