### ISSUE TITLE
[task]: [custom widgets] Support for Scss and editor settings dropdown

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#28614]
- [ ]  Add support for SCSS for more extensive styling options.

**Comment by somangshu** [comment]
@sbalaji1192 isnt this is good to have?
cc @dilippitchika @AbhaySM

**Comment by sbalaji1192** [comment]
@somangshu Yes. But I thought we could have it in v1 since it will improve user experience.

**Comment by somangshu** [comment]
Got it. 
Please note that prioritising the complex must haves before this
