### ISSUE TITLE
[Bug] Modify dynamic binding evaluation to support escaped characters without double escapes

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2862]
Escape characters (like `\t`, `\n` etc) are currently not read as such during evaluation. They need to be written as a double escaped `\\n` for the character to make sense while evaluation. This is non-intuitive since the editor space is not represented as a string literal.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu @mohanarpit @trishaanand re-opening this as I reported today

**Comment by Nikhil-Nandagopal** [comment]
Reopening this as it's still happening. We're back and forth on this issue a lot!
@hetunandu @trishaanand what's happening here?

**Comment by ajinkyakulkarni** [comment]
<img width="1335" alt="escape" src="https://user-images.githubusercontent.com/800578/125903892-1828c0ec-a1f4-4492-a128-b6466424ba45.png">

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : I closed this because I assumed it was reopened due to #5328

**Comment by trishaanand** [comment]
After speaking to @hetunandu, turns out it was my mistake closing it the first time since this scenario was only covered in the smart substitution/prepared statement scenarios.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu is this hard to support?

**Comment by ramsaptami** [comment]
This issue is causing linting to break when escape characters are used
https://github.com/appsmithorg/appsmith/issues/6900

**Comment by arunvjn** [comment]
This would be a breaking change. 
Code editor today persists "\n" as \"\\n\" and "\\n" as \"\\\n\" which is correct. 
We unescape the JS string we get for evaluations, which translates \"\\n\" to \"***actual new line***\" and \"\\\n\" to "\\n".
The solution here is to not unescape the JS string during evaluations.
To ensure backward compatibility, we can translate all the existing usage of "\\n" to "\n" but that would mean that a user will never be able to actually output the string '\n' (by typing \\n), which although rare, is another bug.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @arunvjn this seems risky. Can we do this in a safer way? Should we not allow auto-update for this version?

**Comment by ramsaptami** [comment]
Saptami Ram is inviting you to a scheduled Zoom meeting.

Topic: [appsmithorg/appsmith] [Bug] Modify dynamic binding evaluation to
support escaped characters without double escapes (#2862)
Time: Sep 20, 2021 04:30 PM India

Join Zoom Meeting
https://zoom.us/j/9333609750?pwd=ZkZUVzV6NnAzd25XVzR2N09iUFFSQT09

Meeting ID: 933 360 9750
Passcode: 86ZJpd

**Comment by ramsaptami** [comment]
Reopening this issue since freshly cloned apps are unable to handle single backslash on new line character. The others, `\b` `\t` work as expected.
![image](https://user-images.githubusercontent.com/79509062/143016798-7b4e3c88-4dac-47fa-8211-b0167d036720.png)

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand can we fix this issue with cloned apps? It seems to work fine for other apps but this inconsistency is bad

**Comment by ohansFavour** [comment]
Let's test that this works for export/import flow before closing.

cc: @ramsaptami @abhvsn

**Comment by abhvsn** [comment]
> Let's test that this works for export/import flow before closing.
> 
> cc: @ramsaptami @abhvsn

I have tested this for duplicate, fork and import-export flows and works as expected.
