### ISSUE TITLE
[Feature]: Be able to set default selected value for select columns in Tables

### ISSUE THREAD

**Issue by mike-gigs** [appsmithorg/appsmith#28628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When using a standalone Select widget, we are able to set a default selected value. This is helpful when creating apps that require users to input data, as they can be prefilled in various ways, saving time. When a column is set as a select in a Table, the default value option is not there. It will be helpful if there is a way to set this similar to standalone select widgets so time can be saved for users.

### Why should this be worked on?

Our use case is we are utilizing a table widget for data entry, as it allows us to have scroll-able columns and handles having an unknown amount of rows. The table widget receives the column structure and a few prefilled columns from an API. The two prefilled columns can be edited, and the other 7 columns must be manually entered. For most of these columns the data will be the same across all rows, so it will save our users time if there is a way to auto-fill the subsequent rows after the data is selected in the first row.

**Comment by Nikhil-Nandagopal** [comment]
@mike-gigs thanks for the feature request! Could you tell us why you aren't using the JSON Form widget for this use case?

**Comment by mike-gigs** [comment]
Hi @Nikhil-Nandagopal thank you for your suggestion, this may actually be a good solution for us. I will do some testing to confirm this can accomplish everything we need, I appreciate your help

**Comment by mike-gigs** [comment]
@Nikhil-Nandagopal we followed your suggestion and implemented this with the JSON Form. We had to make some changes from the original design in our application, but satisfied what we were looking to achieve
