### ISSUE TITLE
[Feature]: Hide workspace list if there's only 1 workspace and current user cannot create workspace

### ISSUE THREAD

**Issue by geekyme-fsmk** [appsmithorg/appsmith#28625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hide workspace list if there's only 1 workspace and current user cannot create workspace

### Why should this be worked on?

Because in setups where there's only 1 workspace, and the current user is a business user with no permission to create workspace, then there's no need to view the list of workspaces on the side. Otherwise, this takes up a lot of screen real-estate.

<img width="592" alt="Screenshot 2023-11-03 at 5 28 34 PM" src="https://github.com/appsmithorg/appsmith/assets/100678833/8a330c14-4cdc-4092-89da-a7cc127ceafa">

**Comment by Nikhil-Nandagopal** [comment]
Thanks for the feature request @pranayagarwal96 is looking at the business user experience and can take this as input

**Comment by pranayagarwal96** [comment]
@geekyme-fsmk instead of having a way to completely hide the workspace view, if you were able to set default app urls for users/ groups of users, so that if users login to the platform they would directly get redirected to the one application, would that help? cc @RoopKrrish9696
