### ISSUE TITLE
[Task]: Manual creation of Zones from Sections.

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#28644]

**Comment by somangshu** [comment]
ref
<img width="1279" alt="Screenshot 2023-11-08 at 2 20 34 PM" src="https://github.com/appsmithorg/appsmith/assets/11089579/0f97738a-270d-40de-aba2-ab21e07ee42e">
<img width="1278" alt="Screenshot 2023-11-08 at 2 20 16 PM" src="https://github.com/appsmithorg/appsmith/assets/11089579/2abc5a4f-2f07-46e8-b064-dabacb26bfaa">
<img width="1316" alt="Screenshot 2023-11-08 at 2 21 38 PM" src="https://github.com/appsmithorg/appsmith/assets/11089579/9c8e31ce-c0b2-4bd1-9b14-47795e746e99">

**Comment by marks0351** [comment]
Didnt see that we already had a issue created my bad, closing this issue in favor of this #28863
