### ISSUE TITLE
[Task]: Zone space distribution management

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#28645]
- create data structure on sections to hold space distributed values in columns. a section shall be divided into 12 columns.
- create edit layer on sections to edit space distributed amongst zones.
  - handles to drag
    - should be visible on hover in between two zones
    - dragging is not pixel based but column based.
  - add limits to extend a zone(not beyond the section limit of 12 columns or less than 2 columns per zone).
  - add responsive behaviour to zones to not fold below 2 columns.
- sagas to update sections or zones(based on datastructure decided for holding space of zones).

Miscellaneous: 
- make sure to test user-select cases in safari
- make sure the handle is not continuing to be held even after mouse down like in canvas resizer

**Comment by somangshu** [comment]
[Internal discussion ref](https://theappsmith.slack.com/archives/C063JD5N1P0/p1699281647341439)

**Comment by marks0351** [comment]
This has been completed.
