### ISSUE TITLE
[Bug]: UI issues in "Add JS libraries" popup

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#28668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Hitting Enter key in the Library URL input box doesn't do anything. Only clicking on the "Install" button works.
2. Trying out multiple failing URLs one after another, shows multiple error message boxes which looks confusing and unintended (since there's no margin between them).
3. The error message and the info icon tooltip disagree with each other.
4. The "Report issue" links to [a specific GitHub issue](https://github.com/appsmithorg/appsmith/issues/19037), that's asking for comments, but doesn't seem to be getting responses. Can we streamline this process?
5. The "Learn more" link is the same docs page link as linked just above, and isn't anything specific to that error message.

![shot-2023-11-06-14-33-40](https://github.com/appsmithorg/appsmith/assets/120119/30e58d8d-fc48-4759-9a4f-7dc6c481c6b4)

### Steps To Reproduce

Click on the `+` icon next to "Libraries" in the sidebar to check these behaviours.

### Environment

Production

### Version

Cloud & Self-Hosted

**Comment by rohan-arthur** [comment]
larger initiative, will be fixed with [this](https://theappsmith.slack.com/archives/C05P3ME9MBR/p1716560789266839)
