### ISSUE TITLE
[Bug]: When user migrates the license from business to enterprise through license manager  the license seems like not migrated in the instance 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#28663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user migrates the license from business to enterprise through license manager  the license seems like not migrated in the instance 
![image](https://github.com/appsmithorg/appsmith/assets/45958978/f4841fe0-5701-40c1-a2a4-ba9bb8c4eb5c)

### Steps To Reproduce

1. create a new license from the customer portal 
2. add this license in your local instance
3. now convert this busniess key to enterprise key from license manager app
4. Now once its converted to an enterprise key 
5. We still see that enterprise label in front of provisioning  fetaure 

### Environment

Production

### Version

v1.9.43

**Comment by abhvsn** [comment]
Closing this as we haven't heard from QA team.
