### ISSUE TITLE
[Bug]: Statbox widget has inconsistent min heights

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#28677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When dragging and dropping a statbox widget, the min-height for auto height is set to 14 rows. For Container widgets the default min height is 9 rows. 

When switching the value of the `height` property from `Fixed` to `Auto Height` -- for the statbox widget -- the min-height is reset to 9 rows.

Due to the above reasons:
- When we delete the bottom few widgets in a freshly dropped statbox widget, the statbox widget's height doesn't go below 14 rows, leaving a lot of white space at the bottom of the widget
- However, if we toggle the `height` property of the statbox widget, the widget now properly collapses to a minimum of 9 rows.

This inconsistent behaviour is unexpected.

The reason this logic was intentionally put in to the Statbox widget, is due to the way Auto Height works.
When we first drop a statbox widget.
- Widget is rendered
- Widget triggers an auto height update
- Widget changes height based on the auto height computations

The three steps above causes a "flicker" when we first drop the widget, as the widget height changes. To mitigate this, we added a default `min-height` of 14 rows to the statbox widget.

### Steps To Reproduce

1. Drop a fresh statbox widget
2. Delete 2 or 3 of the bottom most widgets in the statbox widget
3. Notice that the height doesn't change
4. Toggle the "height" property of the statbox widget to "Fixed", then back to "Auto Height"
5. The statbox widget collapses appropriately to get rid of the white space at the bottom.

### Environment

Production

### Version

Cloud and Self hosted - 1.9.44

**Comment by LuisVicenteCorreia** [comment]
Hello, I'm interested in contributing to Appsmith and would like to work on fixing this bug. Could I take this issue?

**Comment by riodeuno** [comment]
Hi @LuisVicenteCorreia! 
As this effect was intentional (as mentioned in the issue description) I'm afraid that this issue needs a product exploration in the team to resolve and will not be open for external contribution.

If you haven't contributed to Appsmith earlier, I would encourage you to take a look at some of the issues with the label: "good first issue".

**Comment by riodeuno** [comment]
@LuisVicenteCorreia
To consistently replicate the flicker issue we need to try dropping the statbox widget in different viewport editors. When the viewport width changes the "auto height" feature adapts the contents of the statbox widget and causes it to re-render with a different height.

Any value that we use that is larger than 9 will have this issue.

Thanks for sharing the fix for the original issue. We'll review it.
