### ISSUE TITLE
[Feature] Ability to Table widget control column visibility programmatically 

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2869]
## Summary
Developer user wants to give the ability to handle column visibility directly to the business user. They want to create a bulk way to handle column visibility for this purpose

## Additional Context
Original discussion 
#2865

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu the user should be able to expose this in the new table widget by binding the isVisible of the column to a dropdown

**Comment by riodeuno** [comment]
@hetunandu @Nikhil-Nandagopal We'll be taking this up in #3250.  Closing this. https://github.com/appsmithorg/appsmith/issues/3250#issuecomment-800015797
