### ISSUE TITLE
[Bug]: Favicon image is broken

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Favicon image is broken on the Appsmith tab and in Admin settings Branding page.

### Steps To Reproduce

In the Appsmith Chrome tab, the appsmith fav icon is missing 
Also in the Admin settings -> Branding page, the preview of Fav icon has image missing/broken
This is observed in both [CE](https://ce-28674.dp.appsmith.com/) and [EE](https://ee-2817.dp.appsmith.com/) DP

<img width="1133" alt="Screenshot 2023-11-08 at 10 07 41 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/00fe2dc2-d04e-4dd4-9e4a-d1cd87c49178">

<img width="649" alt="favicon" src="https://github.com/appsmithorg/appsmith/assets/101863839/a87176e3-f348-46ad-a7a9-1aefe91d0561">

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
Looks like this issue is already resolved
