### ISSUE TITLE
[Bug]: Page setting section is blank when user opens an app

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#28718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Setting pane is blank when page setting is selected while opening an app

Note : issue can be seen on prod

Video is attached : https://www.loom.com/share/e532f7ce8cc84f8b8a9abb5277d753f6?sid=bf2f681b-9759-428a-b48b-d719f5452ef2

### Steps To Reproduce

1. Open an app 
2. Select any page
3. Click setting of the page and page setting window can be seen
4. now close the app
5. Open a fresh app and observe page setting is blank 

### Environment

Production

### Version

Appsmith v1.9.44-SNAPSHOT

**Comment by kocharrahul7** [comment]
This can no longer be reproduced
