### ISSUE TITLE
[Bug]: Unable to access a page via its URL while being on a child branch on a git connected app. 

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#28723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to access a page via its URL while being on a child branch on a git connected app. It throws a 404 error.

### Steps To Reproduce

1. Create a git connected app
2. Create a child branch on the app
3. Add a page on the child branch
4. Access the Change Page URL section under Page Settings
5. Try to access the page via the URL. A 404 error is thrown

### Environment

Production

### Issue video log

https://www.loom.com/share/066fd09893b940fcaa40e513abd1e0f2?sid=eaeb0ffc-8c3c-4bb0-aebd-49450e98a4d6

### Version

v1.9.44

**Comment by rohan-arthur** [comment]
there's a regression, the page url is no longer copy-able and I've reported it here https://github.com/appsmithorg/appsmith/issues/33849

However, the core issue is not reproducible anymore. I am able to create a page on a branch and open it using the url.
