### ISSUE TITLE
[Bug]: REST API File upload issue

### ISSUE THREAD

**Issue by saivikash405** [appsmithorg/appsmith#28735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

We are currently utilizing the file picker widget to upload files in
binary format to our S3 buckets through an API. However, we've
encountered an issue with certain PDF files where the file picker
appears to encounter a parsing problem. After investigating, we've
determined that this issue occurs with files having a PDF encoding
version higher than 1.4.

To illustrate, when we attempted to upload a file with a PDF encoding
version of 1.7, it resulted in a failure. On the other hand, when we
downgraded the PDF encoding version to 1.4 or below, the upload
process was successful.

We have included the file data for both the successful and failed
scenarios for your review. Please take a look and provide any insights
or solutions to address this issue. Your assistance is greatly
appreciated.

// WORKING
{
  "type": "application/pdf",
  "id": "uppy-manage/hh/pdf-1d-1e-application/pdf-432507-1699371074290",
  "data": "%PDF-1.4\n#õ¿¦¡Å|\u0014Ó..."
  "meta": {
    "relativePath": null,
    "name": "Manage-HH.pdf",
    "type": "application/pdf"
  },
  "name": "Manage-HH.pdf",
  "size": 432507,
  "dataFormat": "Binary"
}
{
  "type": "application/pdf",
  "id": "uppy-cheltenham///printed/copy/pdf-10-1d-10-10-1e-application/pdf-277184-1699424427348",
  "data": "%PDF-1.3\n%Äåòåë§ó ÐÄÆ\n3..."
  "meta": {
    "relativePath": null,
    "name": "Cheltenham - PRINTED COPY.pdf",
    "type": "application/pdf"
  },
  "name": "Cheltenham - PRINTED COPY.pdf",
  "size": 277184,
  "dataFormat": "Binary"
}

// NOT WORKING
// Your API failed to execute:
org.springframework.web.reactive.function.client.WebClientRequestException:
Unable to parse content. Expected to receive an array or object of
multipart data
{
  "type": "application/pdf",
  "id": "uppy-cheltenham///cdc///fod/wodc///loa/2023//3//pdf-10-application/pdf-365512-1699371076647",
  "data": "%PDF-1.7\r\n%¡³Å×\r\n104 0...",
  "meta": {
    "relativePath": null,
    "name": "Cheltenham - CDC - FOD WODC - LOA 2023 (3).pdf",
    "type": "application/pdf"
  },
  "name": "Cheltenham - CDC - FOD WODC - LOA 2023 (3).pdf",
  "size": 365512,
  "dataFormat": "Binary"
}

### Steps To Reproduce

1. We are passing the mentioned pdf file as an input to our internal api (which is working fine in the postman, but creating the issue in the appsmith because of the pdf encoding in the appsmith)
2. Some of the files where the pdf  encoding version is less than 1.4 is getting uploaded Succesfully
3. And the other files which have pdf encoding version greater than 1.4 is creating the issue and returing the below error
Your API failed to execute:
org.springframework.web.reactive.function.client.WebClientRequestException:
Unable to parse content. Expected to receive an array or object of
multipart data
4. Here we are sharing the screen shots for reference and in the upload_mpans function we are just calling the s3_upload api
<img width="1131" alt="Screenshot 2023-11-08 at 5 45 28 PM" src="https://github.com/appsmithorg/appsmith/assets/79797763/c69f4fd6-92a8-4ce5-ab7c-fadbe2291ccd">
<img width="1136" alt="Screenshot 2023-11-08 at 5 45 52 PM" src="https://github.com/appsmithorg/appsmith/assets/79797763/6e621cd0-9837-49e2-8a5e-bb2e6d28a7a3">
<img width="959" alt="s3upload1" src="https://github.com/appsmithorg/appsmith/assets/79797763/72aae61d-0191-4412-a828-0c924da3756e">
<img width="916" alt="s3upload_2" src="https://github.com/appsmithorg/appsmith/assets/79797763/f7efaa11-c045-454d-9a0d-eb1bf2b72819">
<img width="907" alt="s3upload_3" src="https://github.com/appsmithorg/appsmith/assets/79797763/62492c53-851c-46c9-8676-48f0a0900ab7">

### Environment

Production

### Version

1.9.42

**Comment by Nikhil-Nandagopal** [comment]
@saivikash405 have you tried uploading the file using our S3 integration?

**Comment by saivikash405** [comment]
@Nikhil-Nandagopal, yes, even there, when I attempted to upload the file with PDF version 1.7, it threw an error. However, the file with PDF version 1.4 uploaded successfully. The challenge here is that there is no binary data type available in the query (only base64 and text are available) for creating a new file. Interestingly, in the "create multiple files" command, the text/binary option is available, but when I attempted it, it resulted in an error again.
I have attached some screenshots please verify.
**SINGLE FILE SUCCESS RESPONSE**
<img width="897" alt="successpdfresponse" src="https://github.com/appsmithorg/appsmith/assets/79797763/6b67a3d3-e2ae-4a8c-9525-97ff7357c092">
**SINGLE FILE UNABLE TO OPEN IN S3**
<img width="1149" alt="sucesspdfunabletoopen" src="https://github.com/appsmithorg/appsmith/assets/79797763/57feaff1-ba3a-4c1f-ba42-aeeab6bce32f">
**FAILED FILE RESPONSE**
<img width="890" alt="failedpdferror" src="https://github.com/appsmithorg/appsmith/assets/79797763/1f877fd1-5f5c-4abb-9c17-9cb98ba1a459">
**MULTIPLE FILES FAILED RESPONSE**
<img width="897" alt="multifilesfailedorg" src="https://github.com/appsmithorg/appsmith/assets/79797763/0cd7c014-2fd0-4f30-9543-8d2a64f53d31">

The content in all Screenshots is {{FilePicker1.files[0]}} only

Your insights or guidance on this matter would be greatly appreciated. Thank you.

**Comment by Nikhil-Nandagopal** [comment]
@saivikash405 for the S3 integration I don't think the data format needs to be binary. Can you try with the base64 option?

**Comment by saivikash405** [comment]
Hi @Nikhil-Nandagopal It is working fine(for the pdf file with version 1.7 also) with base 64 format in the filepicker and in the query aswell. But we previously have been using the S3 integrations directly which was 1 year ago, then the s3 integrations were going down in between which has created some issue, that's why we have opted for the API to upload the files into s3.

**Comment by Nikhil-Nandagopal** [comment]
@saivikash405 sorry you had a bad experience with it. I think our S3 integration is a lot more stable now and it should solve your use case. If you have any trouble with it, please let me know

**Comment by NilanshBansal** [comment]
@saivikash405 pdf v1.7 upload to s3 using the file picker widget works fine for me. [Here](https://drive.google.com/file/d/1lc7zP6vZ7ODQmbYciTkmOB100hns4R8W/view?usp=sharing) is the screen recording for the same. 
File uploaded - https://drive.google.com/file/d/1fCkrztaLnDN5iFi5R_5crC-S4U5Scwce/view?usp=sharing

**Is this something specific to the file you are uploading?** If yes, can you pls share that file with us on support@appsmith.com

Feel free to schedule a call here https://calendly.com/nilansh/30min

**Comment by saivikash405** [comment]
Hi @NilanshBansal , through S3 Integrations , It is working fine, but we are uploading the file using the api, there it is throwing an error, but we will update our app and start using the s3 integrations as Nikhil said it is lot stable now. We will try it and let you know, Incase we face any-other issues.

**Comment by NilanshBansal** [comment]
@saivikash405 Glad to hear that the S3 integration is working fine for you. I am closing this issue atm, please feel free to reopen it if the issue persists.
