### ISSUE TITLE
[Bug]: Changing default branch from remote doesnt work on DP

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#28746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Changing default branch doesnt work for protected branch feature here :https://ee-2816.dp.appsmith.com/

### Steps To Reproduce

1. Connect app to git, change default branch from remote
2. Try syncing branches observe default branch is not updated

### Environment

Production

### Version

https://ee-2816.dp.appsmith.com/

**Comment by infinitetrooper** [comment]
This is fixed, @Parthvi12  - please reopen if not.
