### ISSUE TITLE
[Bug]: Old default branch is not getting removed from protected branch list

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#28756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/80334441/e8594c62-3587-4213-ae76-fa8f8535441e

### Steps To Reproduce

1. Connect app to git, protect default branch master on appsmith
2. Change default branch in remote
3. Sycn branches in appsmith
4. Observe master is still protected 
Ideally it should make it unprotected

### Environment

Release

### Version

Release

**Comment by infinitetrooper** [comment]
This is fixed, @Parthvi12  - please reopen if not closed.
