### ISSUE TITLE
[Bug] On adding a new data the existing column font setting changes

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2875]
Steps to reproduce:
1) Add a Table widget
2) Click on Property pane of the table widget
3) Add "Bold" and BG colour to the table 
4) Now navigate to one of the column setting (Control Pane)
5) Deselect "Bold"
6) Observe the table column gets normal
7) Navigate  Property pane of the table widget
8) Add a Set of value to the table
Observe the table 

Observation:
It is observed that the table setting overlaps the Column setting on adding data 

Expectation:
The column setting must not be overlapped when the data is been added 

Please refer the video
https://www.loom.com/share/790f5b243f8f419fab5301e5f313da35

**Comment by riodeuno** [comment]
@prapullac Please verify this again.

**Comment by prapullac** [comment]
@riodeuno : It is working as expected on deploy preview. We can close the issue
