### ISSUE TITLE
[Bug]: Digit '0' & a horizontal scroll present at the bottom left of the screen

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#28778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We see `0` at the bottom left of the screen in deploy mode. Also there are additional horizontal & vertical scrolls introduced.
<img width="1920" alt="Screenshot 2023-11-10 at 10 24 47 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/29fc42c2-22de-48df-a1e7-c4a1bc6dd056">
<img width="1920" alt="Screenshot 2023-11-10 at 10 29 10 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/bc7ce83e-c7ba-4e30-b81f-b18220b1a4e9">

**Note:** This can be seen in the latest promotional CE DP as well: https://ce-28674.dp.appsmith.com/

### Steps To Reproduce

1. Go to 'https://release.app.appsmith.com/' and open an app.
2. Deploy the app and scroll to the bottom.

**Expected:** No extra horizontal scrolls or digits should be displayed at the bottom.
**Actual:** We get to see `0` at the bottom left & additional vertical & horizontal scrolls in deploy mode.

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
Note: @ayushpahwa  - this seems to have been introduced by this [PR](https://github.com/appsmithorg/appsmith/pull/27043) 
This is not happening on EE environment.

**Comment by btsgh** [comment]
Tested on promo dp - found to be fixed.
