### ISSUE TITLE
[Task]: Add analytics events for starter building blocks

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#28780]
Based on the conversation here: https://theappsmith.slack.com/archives/C05P3ME9MBR/p1699528712852149

1. When a user hovers over a starter template
2. User clicks on a starter template - [Backend]
3. User clicks on the connect data CTA

**Comment by jacquesikot** [comment]
@rahulbarwal any exact name for event 1 and 3? Also, any specifics on the eventData that should be sent?

**Comment by rahulbarwal** [comment]
1. `STARTER_BUILDING_BLOCK_HOVER`
2. We already have this event with `FORK_APLICATIONTEMPLATE`
3. `STARTER_BUILDING_BLOCK_CONNECT_DATA_CLICK`

@jacquesikot
