### ISSUE TITLE
[Bug]: Flakiness of Publish community template flow

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#28796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://theappsmith.slack.com/archives/C02RCR2PURZ/p1699530553472389

### Steps To Reproduce

https://theappsmith.slack.com/archives/C02RCR2PURZ/p1699530553472389

### Environment

Production

### Version

Cloud

**Comment by rahulbarwal** [comment]
We will revisit this on 19th December.

**Comment by AnaghHegde** [comment]
Will be handled via https://github.com/appsmithorg/appsmith/issues/29914
