### ISSUE TITLE
[Bug]: MySQL stale connection issue

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#28813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user is facing stale connection issue when running query on mySQL datasource, for more info, checkout [thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1692035286459429)

### Steps To Reproduce

1. Create MySQL datasource
2. Create a query on it
3. Observe the error

### Environment

Production

### Version

Cloud/ Self-Hosted - 1.9.31

**Comment by sneha122** [comment]
Putting this issue back in spring backlog as we need more info from user: [thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1699862406668319?thread_ts=1692035286.459429&cid=C040LHZN03V)

**Comment by NilanshBansal** [comment]
Data shared by the user for their SQL connection
<img width="663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXlSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9db0e77f81686e71879e3a3a0e38999f982b6f2f/image.png" alt="image.png" />

<img width="436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a458517861a43fbaa9e6063ba974096fa28db5a0/image.png" alt="image.png" />

**Comment by NilanshBansal** [comment]
Logs show `com.appsmith.external.exceptions.pluginExceptions.AppsmithPluginException: get_wipe_sesults_all_trans timed out in 10,000 milliseconds. Please increase timeout.`

**Comment by NilanshBansal** [comment]
The user instantiated a new instance with the latest version and the issue was not reproducible on that.

**Comment by NilanshBansal** [comment]
Closing this issue with reference to the above.
Ref: https://theappsmith.slack.com/archives/C05QUCS74J2/p1704458236359719?thread_ts=1703709101.302939&cid=C05QUCS74J2
