### ISSUE TITLE
Improve MongoDB preview data for MongoDB with Nested Arrays

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#28825]
When viewing the MongoDB tables data with nested arrays, the current representation lacks clarity and usability. This becomes prominent when dealing with complex data structures like those encountered in MongoDB, where arrays are commonly used as attributes.

**Comment by carinanfonseca** [comment]
[Proposal](https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=2805-67369&mode=design&t=4S6Shuay5ccC7zaN-0):

Proposal's description and rationale:
- JSON tree view for nested arrays: Use a JSON tree view instead of a table to represent MongoDB collections with nested arrays. It preserves hierarchy for better visualization and understanding of complex data structures, leveraging developers' familiarity with the JSON tree view format.
- Enhance existing features: Improve the current JSON viewer (query response tab) by adding expandable and collapsible options.

**Comment by carinanfonseca** [comment]
To discuss: 
- does it make sense to keep the toggle Table | JSON?
- (to keep consistency) can we also improve the response tab as well by applying the collapsable/expandable functionality?

**Comment by NilanshBansal** [comment]
Currently, we already show the collapsible/expandible JSON view in the query response. 
<img width="1428" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/39fe0798-368e-443e-99e2-583ec98fa3dd">

We have the [CodeEditor](https://github.com/appsmithorg/appsmith/tree/release/app/client/src/components/editorComponents/CodeEditor) component in the code which can be imported and reused for the same. 
@carinanfonseca

**Comment by sneha122** [comment]
@NilanshBansal @rohan-arthur I have added task breakdown with estimations in this [doc](https://www.notion.so/appsmith/Schema-preview-for-MongoDB-1dc3d3c3145f41beab18a20f027e1092)

**Comment by NilanshBansal** [comment]
Since this task was only a breakdown estimation and design review task. Marking this as done.
