### ISSUE TITLE
[Feature]: Support arbitrary user ids for Appsmith's container image to properly work on Openshift

### ISSUE THREAD

**Issue by aminedj** [appsmithorg/appsmith#28828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Openshift requires container images to support arbitrary uids to be able to run as explained here: https://docs.openshift.com/container-platform/4.14/openshift_images/create-images.html#use-uid_create-images

This would help enterprise customers running on Openshift to take advantage of Appsmith without having to create their own Container image as explained here https://github.com/appsmithorg/appsmith/issues/9067#issuecomment-1437046119

### Why should this be worked on?

Striaght forward enough to implement and gives you native support to run Appsmith on Openshift (largest k8s enterprise platform) with no regression to other container platforms.

**Comment by Nikhil-Nandagopal** [comment]
This is now supported!
