### ISSUE TITLE
Make it possible to collapse apps and packages section in the workspace

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#28852]
Feedback received [here](https://theappsmith.slack.com/archives/C04GRCN4CS3/p1697095277359479?thread_ts=1696733512.503849&cid=C04GRCN4CS3)

The solution design is [here](https://zpl.io/Dl53Yoq).

Description:
- 50% transparency for the workspaces that are not selected (already presented in the previous designs, but it wasn't implemented)
- Collapsable/Expandable sections for apps and packages.

**Comment by ankitakinger** [comment]
@carinanfonseca @pedro-santos-rodrigues Since new home page experience is being worked on and should be getting merged soon, which will basically display only 1 workspace at a time, do we need to implement the collapsible apps and packages section in workspace now?

**Comment by carinanfonseca** [comment]
No, let's wait to see how it works with the new behavior. We'll get back to this if it is necessary. Thanks for asking, Ankita.

**Comment by pedro-santos-rodrigues** [comment]
Closing since this doesn't make sense anymore with the new design of the Appsmith home since only one workspace is shown at a time as @ankitakinger had mentioned.
