### ISSUE TITLE
[Bug]Deletion of Tab from entity explorer is not working

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#2885]
Steps:

1.Delete one of the 2 default tabs in the tab widget from entity explorer.
2.Tab deleted message is seen but it's not reflecting in the widget and also in the property pane.

**Comment by Nikhil-Nandagopal** [comment]
@NandanAnantharamu this seems to be working, can you verify?

**Comment by NandanAnantharamu** [comment]
> @NandanAnantharamu this seems to be working, can you verify?
This issue still exists on release

**Comment by NandanAnantharamu** [comment]
This issue still exists in the release, 

https://user-images.githubusercontent.com/67676905/110006775-0b8b7580-7d40-11eb-81b3-6b867bb0be42.mov

**Comment by akash-codemonk** [comment]
@NandanAnantharamu This as it seems to be working now. Please verify.
