### ISSUE TITLE
[Bug]: Not able to add templates within app

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#28875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Open a new app and add template 'Maintenance order management' from `Add page from template`

![image](https://github.com/appsmithorg/appsmith/assets/92293815/000b9ca0-04b3-4931-87c9-684ca1cf6536)

### Steps To Reproduce

1. Open a new app
2. Click on `Add page from template`
3. Add 'Maintenance order management' template and observe there are no pages to add

### Environment

Release

### Version

Cloud

**Comment by AnaghHegde** [comment]
The CS entry for the above template does not have the page data.

**Comment by rahulbarwal** [comment]
This is fixed now. Please reopen if you face this again.

**Comment by rahulbarwal** [comment]
Earlier was fixed on prod. Fixed in release as well.
