### ISSUE TITLE
[Bug]: On trying to edit existing or add a new role in the release-ee environment, an internal server error is thrown

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are seeing an internal server error on Roles page, when we try to edit existing or add a new role in the [release-ee](https://release-ee.appsmith.com/) environment.

### Steps To Reproduce

Login as instance admin into the release-ee environment
Go to Admin settings
Click on Roles
Click on Add a role or try to edit an existing role

The following errors are seen. 

<img width="1062" alt="Screenshot 2023-11-15 at 4 30 49 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/55b3c162-970b-4c51-9bf5-a6c079d4165b">

### Environment

Release

### Version

Cloud

**Comment by sondermanish** [comment]
This Issue was due to duplicate policy in environments in one workspace.  Removed the corrupted policy manually for two environments. This is working fine now.
