### ISSUE TITLE
[Bug]: The heading is inconsistent, on DS page and on the IA redesign panel

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the new IA redesign page, the heading for SAAS integrations, is mentioned as just "Integrations" This is inconsistent with the Create New Datasources page side which reads as SAAS Integrations.

### Steps To Reproduce

<img width="1387" alt="inconsistentname" src="https://github.com/appsmithorg/appsmith/assets/101863839/1c58fd27-ac3d-4684-9485-0c327b0c3187">

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
[conversation](https://theappsmith.slack.com/archives/C05P3ME9MBR/p1710756000615889)

**Comment by NilanshBansal** [comment]
@rohan-arthur was there a PR raised for this issue? If not, I can take this up.

**Comment by hetunandu** [comment]
I think it should be renamed to "Integrations" as well

**Comment by NilanshBansal** [comment]
> I think it should be renamed to "Integrations" as well

@hetunandu are you saying we rename `Saas Integrations` to `Integrations` and keep the others as it is?
What about `AI Integrations` header? 
cc: @carinanfonseca 

<img width="1050" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/8f0643c2-97a2-400c-b42f-fdfc31fe9db1">

**Comment by carinanfonseca** [comment]
I see 2 options here:
1- we have SaaS integrations and AI integrations in the datasources list and the we keep the same titles in the left panel/explorer. 
2 - we keep integrations on the left panel/explorer and, in the datasources list, we merge SaaS integrations and AI integrations in a section called Integrations

The separation between SaaS and AI is important in terms of experience, and it helps users to consume that info more easily. I would suggest to go with the first approach (number 1). Is that possible?

**Comment by NilanshBansal** [comment]
@hetunandu how does the approach 1 sound to you? Also, is this on IA roadmap already?

cc: @vinay-appsmith @kocharrahul7

**Comment by hetunandu** [comment]
@NilanshBansal @carinanfonseca option 1 sounds reasonable. This is not part of IA roadmap and can be picked up by the Data Integrations team. Feel free to reach out for clarifications on the changes needed
