### ISSUE TITLE
[Bug]: Feature Flag issue - IA Redesign is visible for all users, should be enabled only for appsmith/moolya

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#28891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On release and release-ee, the IA redesign should be visible only for appsmith and moolya users. However, on logging in as a random user - test@abcd.in, I can see this feature on both the above environments.

### Steps To Reproduce

On logging into appsmith and opening an application, we are able to see IA redesign feature for any user. Non appsmith and non moolya users, are also able to seeing the feature.

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
@rohan-arthur - as per our slack [discussion](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1700058658767899?thread_ts=1700027177.550459&cid=CGBPVEJ5C), retesting this on release-ee - will update once we complete testing.

**Comment by RakshaKShetty** [comment]
@rohan-arthur  have  a small question here when i create new user on the instance with non appsmith id  i am not able to see this new chnage  but fro the existing non appsmith id user i can still see the feature is this something expected attaching screenshot for refrence
