### ISSUE TITLE
[Feature] Have an option so that app viewer don't see the sample apps

### ISSUE THREAD

**Issue by hawisizu** [appsmithorg/appsmith#2890]
In my case, the app viewer don't even know what appsmith is, I want it to be as easy as possible for them to use the app. They should have only the app that they will use, and ideally in such case with users that are app viewer with only 1 app, they could skip entirely the welcome page and directly go to the home page of their only app.

**Comment by areyabhishek** [comment]
Thanks! We'll figure out a good solution for this.
Some solutions here:
1. If a new user is invited as a viewer, they shouldn't have an organization automatically created for them
2. They see example apps only when they create their first organization
3. If they only have one app in their org, they directly skip the homepage and access the application

**Comment by hawisizu** [comment]
This would be perfect!
