### ISSUE TITLE
[Bug]: Google sheet Authorisation is not working , giving 403 Forbidden to retrieve appsmith token

### ISSUE THREAD

**Issue by neeraj0786** [appsmithorg/appsmith#28923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is happening since your 8 November '23 release and is still recurring ,
while adding this data source 

When we are trying to authorise a google sheet datasource its failing, 

On checking the network tab , we have observed the oauth api 

api/v1/saas/6553a6ed2a8eb72ce75dfa03/pages/64a56eeb2dc55c5e46d7c634/oauth

{
    "responseMeta": {
        "status": 500,
        "success": false,
        "error": {
            "code": "AE-APP-5010",
            "title": "AUTHENTICATION_ERROR",
            "message": "Authentication failed with error: Unable to retrieve appsmith token with error 403 FORBIDDEN",
            "errorType": "Authentication failed"
        }
    },
    "errorDisplay": "AE-APP-5010: Authentication failed with error: Unable to retrieve appsmith token with error 403 FORBIDDEN"
}

in your BE code on further checking I have seen 
request to cloudServicesConfig.getBaseUrl() + "/api/v1/integrations/oauth/appsmith")
under public Mono<String> getAppsmithTokenapi is failing 

### Steps To Reproduce

while adding this data source 

<img width="1243" alt="image" src="https://github.com/appsmithorg/appsmith/assets/33028072/5ad25049-6b1c-41ef-b762-b777e85f3e40">

getting error 
<img width="1512" alt="image" src="https://github.com/appsmithorg/appsmith/assets/33028072/e1a60ff2-4b88-4e56-890c-b35652cbef64">

<img width="1246" alt="image" src="https://github.com/appsmithorg/appsmith/assets/33028072/6ae61243-6a1e-4246-b11b-1f461b24ecf1">

### Environment

Production

### Version

Self Hosted - v1.9.46

**Comment by Nikhil-Nandagopal** [comment]
@neeraj0786 apologies for this issue. We're looking into it. If this is hampering your operations or development in anyway, you can consider rolling back to a previous version if you had taken a backup

**Comment by NilanshBansal** [comment]
@neeraj0786 apologies for the inconvenience. You can resolve this issue by following the steps below.

1. Run the command on your mongo database  `db.config.updateOne({"name": "appsmith_registered"}, {$set: {"config.value": false}})`
2. Restart the instance.

**Comment by neeraj0786** [comment]
Thanks @NilanshBansal  working fine now !
