### ISSUE TITLE
[Task]: Update instance registration check and re- registration flow

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#28952]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

- A [use case](https://theappsmith.slack.com/archives/C040LHZN03V/p1700206435426579) surfaced recently wherein a user's instance failed to register itself with the remote cloud service. Although we do not know the root cause for why a registration would fail or if the user's instance was marked with `true` or `false` for the `appsmith_registered` config document, it may be useful to update the flows where registration is required to attempt a re-registration if the previous attempt failed: 
  - Attempt to get Appsmith token immediately post registration to check if registration succeeded. 
    - Mark `appsmith_registered` value `true` or `false` based on whether the Appsmith token could be fetched. 
  - In case of flows where Appsmith token is required, first check if the `appsmith_registered` value is `true` or `false`. If it is `false`, then re-trigger the registration flow first e.g. Google sheets authorization
    -  if Appsmith token could not be fetched then show proper error on the client.

**Comment by NilanshBansal** [comment]
Recent issue logged around this: https://github.com/appsmithorg/appsmith/issues/28923
