### ISSUE TITLE
[Bug] Table has a vertical scrollbar even if content fits

### ISSUE THREAD

**Issue by anthony-zhou** [appsmithorg/appsmith#2895]
## Description

A table always has a vertical scrollbar, whether or not the content of the table fits within the page. 

### Expected Behavior

The table should never need a vertical scrollbar, because it should load just as many rows as it can display on a single page. 

### Steps to reproduce the behaviour:

1. Open any table
2. Try scrolling in the table

Here's a loom recording showing what I mean:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9c895fb2a2124d479ae4f72cafb444f6-00001.gif)](https://www.loom.com/share/9c895fb2a2124d479ae4f72cafb444f6)

### Important Details
 - Version: Self-Hosted v1.3.3
 - OS: MacOSX (client), Ubuntu (server)
 - Browser: Chrome, Firefox (probably others too)

**Comment by areyabhishek** [comment]
@anthony-zhou thanks for the loom video and reporting this, we'll fix it.

**Comment by riodeuno** [comment]
Mentioned in #3248

**Comment by somangshu** [comment]
#3966 is related?

**Comment by rfenaux** [comment]
https://user-images.githubusercontent.com/19254107/220286538-820db046-500d-4cd5-afe5-80926a2d5fb3.mov

Hi there, was there a fix for this ?
@Nikhil-Nandagopal @areyabhishek 🙏🏼

**Comment by dilippitchika** [comment]
Thanks for reporting @rfenaux there is another bug which i am not able to find, but it's the same issue. We will prioritise this.

**Comment by dilippitchika** [comment]
Tracking in #20831, @rfenaux please follow that issue

**Comment by chriscupas** [comment]
Following up on this update ...

**Comment by dilippitchika** [comment]
@chriscupas please follow #20831 for updates
