### ISSUE TITLE
Add the ability to specify a page for server pagination

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#28964]
The way server side pagination works is by triggering an API bound to `onPageChange` when page changes. In the API you can use `table.pageOffset` as a parameter to share where the records start from. `table.pageOffset` is a variable which is just `table.pageSize*(table.pageNo-1)`. It says start from the 500th record and not from the 1st record, depending on `pageSize` and `pageNo`.

Related thread:
https://theappsmith.slack.com/archives/CNQ9Q91C0/p1700475844249509?thread_ts=1700469391.664719&cid=CNQ9Q91C0

**Comment by ame-appsmith** [comment]
We have a similar feature request here: https://github.com/appsmithorg/appsmith/issues/24973
