### ISSUE TITLE
[Feature] Users would like to enable optional encoding of URI for APIs

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2897]
A default true option for encoding allows users to skip a forced decoding step in case their URI components are already encoded.

**Comment by nidhi-nair** [comment]
Additional context: The gap was felt against a developer experience with tools like Postman that allow complete configuration for the API. [REF](https://github.com/postmanlabs/postman-app-support/issues/8154)

**Comment by sumitsum** [comment]
Re-opening this issue because UI change is pending.
@Nikhil-Nandagopal - assigning it to you so that it can be re-assigned.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum I think settings UI is config driven from backend.
@mohanarpit isn't that so?

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal @mohanarpit 

I was able to find a form.json file that maps values to datasourceConfiguration object but couldn't see any such .json file to map values to actionConfiguration. Also, I am not sure if a toggle kind of UI element is supported via .json file - I can try to add a dropdown with Enable/disable option and map to datasourceConfiguration if that is okay.

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal @sumitsum The action settings are driven by the backend config JSON only for the query pane, not API pane. 

The API pane is still a custom React component and the settings are driven by [this file](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/mockResponses/ActionSettings.tsx). We need to add a setting in the JSON here and also handle that setting when the action is saved.

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal need your opinion here.

**Comment by mohanarpit** [comment]
@ofpiyush Assigning this to you. Is it possible for you to add this to the API settings page quickly? We'll be able to close this feature then.

**Comment by ofpiyush** [comment]
We should run a migration to set this to true on existing actions + configure new action creation to set this to true so that UI doesn't look wrong.

Right now, it will look unchecked by default, but be on.
