### ISSUE TITLE
[Tracker]: Hompage experience v2 FE tracker

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks ~~(9.5)~~  ~~(11.5sp)~~ ~~(13sp)~~ (16sp)

- [x] -  #28786 - 1sp
- [x] -  #28899 - 1sp
- [x] -  #28789 - 1sp
- [x] -  #28790 - 1sp
- [x] -  #28787 - 2sp
- [x] -  #28978 - 0.5sp
- [x] - #29043 - 1sp
- [x] - #29042 - 0.5sp
- [x] -  #28788 - 2sp
- [x] -  #28980 - 3sp
- [x] - #29080 - 1sp
- [x] - #29083 - 2sp

**Comment by deepikaappsmith** [comment]
all the issues tracked here are closed, hence closing the ticket
