### ISSUE TITLE
[Task]: Handle search bar in new sign up flow - Homepage Experience

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We have implemented a new search bar on the header we show on homepage.
The new sign-up flow also uses the `/applications` route, so the search bar is visible there. This needs to be handled.

<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/7651f861-f740-4515-9b49-11ab2f8b912f">

**Comment by deepikaappsmith** [comment]
fixed and merged to release. Hence closing the ticket
