### ISSUE TITLE
[Bug]: Autocomplete option does not get selected in JSON Form

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#28982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I configure a JSON Form to Edit some data and I try to edit the onSubmit action, autocomplete selection inside onSubmit action does not work. The autocomplete suggestions are shown but selection does not happen.

### Steps To Reproduce

1. Create a Table and connect it to Appsmith Mock DB public.employees
2. Configure a JSONForm for Editing public.employees
3. Go to onSubmit event and try to add params as following: 
```
{
    last_name : JSON
}
```
4. Try to select an `JSONFrom1.formData`
5. The selection does not work.

<img width="509" alt="Screenshot 2023-11-21 at 9 46 48 AM" src="https://github.com/appsmithorg/appsmith/assets/39981226/150e6b9d-90c1-4cb4-834d-5e08554b8604">

### Environment

Production

### Issue video log

https://www.loom.com/share/4fa046f37aba49f8bf2d7fc57b5b7f9d

### Version

Cloud - Appsmith v1.9.46-SNAPSHOT

**Comment by rishabhrathod01** [comment]
I was unable to reproduce this issue. Please reopen if reproducible. 

https://github.com/appsmithorg/appsmith/assets/23132741/cc70d0c1-db4c-44f0-972c-e5bb1afc2beb
