### ISSUE TITLE
[Bug]: Evaluated value shows up over query editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#28991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Evaluated value shows up over the editor as seen in the video

### Steps To Reproduce

1. write up a query on a postgres as seen in the video and observe the evaluated pane show up over the query editor

### Environment

Production

### Issue video log

https://www.loom.com/share/87b86abb92b140569e2b186905acead7

### Version

Cloud

**Comment by satbir121** [comment]
Bumping priority on this issue. This also happens for API pane.

Here is the [slack thread](https://theappsmith.slack.com/archives/CNQ9Q91C0/p1702974637645069)

**Comment by arunvjn** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/29912
