### ISSUE TITLE
[Bug] Update db with new documentation page links

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2900]
## Description
The documention link on Appsmith's query / datasource page points to old URL. Post change in documentation structure, these links have become invalid. 

### Steps to reproduce the behaviour:
1. Go to postgres plugin query page.
2. Click on documentation link.

### Important Details
 - Version: Cloud
 - OS: Linux
 - Browser: Chrome

**Comment by nidhi-nair** [comment]
@sumitsum Closing this since #2909 has fixed this issue.
