### ISSUE TITLE
[Bug]: CANNOT SHARE EMAIL PROPERLY (REGEX ERROR)

### ISSUE THREAD

**Issue by mrayushmehrotra** [appsmithorg/appsmith#29038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I Want to share my deployed app in the by the appsmith share button but when i enter this email  carrer@learnbasics.fun which is a valid email address , it didn't provide me the invite button 
![Screenshot from 2023-11-22 16-28-02](https://github.com/appsmithorg/appsmith/assets/110099419/b08201c6-a099-40c1-a450-4bfdf05e25c2)

### Steps To Reproduce

1-create and deploy your app
2-Share the app with email address

### Environment

Production

### Version

Cloud

**Comment by deepikaappsmith** [comment]
https://github.com/appsmithorg/appsmith/assets/130959931/bb788317-3b15-4da8-bc74-89d4b985f10d

@mrayushmehrotra - I used the same credentials you provided and could share the app. I have attached the video for reference. Should I be doing something differently?

**Comment by mrayushmehrotra** [comment]
I don't know, now it's working fine, but in real I have got that error (that's not a fake image I have posted, the cursor style was block at that invite button) so I will close the issue.

**Comment by deepikaappsmith** [comment]
@mrayushmehrotra - I had no intention of suggesting the bug was fabricated. I was curious if there was a different sequence of actions that triggered it. I appreciate you closing the bug, and if you encounter a similar situation in the future, please don't hesitate to reach out. Thanks
