### ISSUE TITLE
[Task]: Update the Empty Screens / Not found screens in Homepage experience

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#29042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

<img width="482" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/c80240f6-5c74-43b0-bd8d-72da93781fd4">

<img width="846" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/19df961c-9af8-4dde-a6d2-22195ef349e8">

**Comment by deepikaappsmith** [comment]
This is fixed with homepage
