### ISSUE TITLE
[Bug]: Link broken on autocomplete information pop-up box

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Docs link on the new autocomplete information pop-up box does not have a link even though a click icon appears on hover. So clicking on the link simply closes the autocomplete suggestion instead of opening documentation link

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/f243cd98-d773-4db2-af92-ce11d793544a)

### Environment

Production

### Version

Cloud

**Comment by rishabhrathod01** [comment]
Link working as expected. Re-open if this is reproducible.
