### ISSUE TITLE
[Task]: Improve the Documentation 

### ISSUE THREAD

**Issue by mrayushmehrotra** [appsmithorg/appsmith#29063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Sub Task:  Write a better docs for how to remove duplicate data which are coming from the database  Like in this image how to remove multiple instance of the same thing 
![Screenshot from 2023-11-23 20-26-04](https://github.com/appsmithorg/appsmith/assets/110099419/e0dbb86a-fdfc-4569-87e4-3a701d3558f4)

Anyone know how to solve this issue?.

**Comment by bastien-naturavelo** [comment]
Hello, what's your datasource ?
You can remove duplicate in your query (for sql it could be : https://www.w3schools.com/sql/sql_distinct.asp)
or you can transform the result of your query with js in the [Source Data](https://docs.appsmith.com/reference/widgets/select#data) of the widget with reduce, map or _lodash_ uniq function
