### ISSUE TITLE
[Bug]-[160]:JS option missing for the following style items in table

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2906]
Steps to reproduce:
1) Add a table 
2) Click on the property pane 
3) Scroll and observe

Table styles
    1. Font Style
    2. Text Align
    3. Vertical Alignment

**Comment by somangshu** [comment]
@vivekverma2312 @prapullac @ramsaptami 
We need some dedicated QA efforts towards finding more use cases across widgets like the above mentioned. This is one goal for September. Kindly prfioritize.

cc @yatinappsmith

**Comment by iocampomx** [comment]
This was in theory fixed on #4918, but checking the commit I see a message "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.", it's weird.

The run failed as can be seen here https://github.com/appsmithorg/appsmith/commits/2dee6cd99b4ab0bf2ab940e1719ce833f9448fc7/app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts and here https://github.com/appsmithorg/appsmith/runs/2742842124

I don't know how the pipeline of this project works, if it failed maybe was never merged on master or the appropriated branch.

**Comment by Tooluloope** [comment]
Hi @iocampomx 
Apologies for just getting back to you.
Yeah, I was working on this issue, but we needed to have the full context of all that needed JS Format so we don't go back and forth. I'd try to raise the priority for this issue.


cc @somangshu @dilippitchika 
Issue is currently in icebox

**Comment by dilippitchika** [comment]
Solved partially in #3369, needs to be added for other items. 
After theming the following properties need to be JS controllable
1. Font style
2. Text align
3. Vertical alignment

**Comment by dilippitchika** [comment]
Assuming 10% of these property users wanted to config JS

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.25 |

**Comment by dilippitchika** [comment]
@aswathkk this issue is being planned to get picked up soon, should we pick it up before the prop pane changes go in and your changes will infer the change or you will have to do it again?

**Comment by aswathkk** [comment]
@dilippitchika Changes to the Table widget already merged to release (under feature flag).
I'm planning to remove the feature flag and merge the code by tomorrow.

Can you wait till that?

Now, you will be able to see multiple places in the codebase that are referring to the property.
example: 
- https://github.com/appsmithorg/appsmith/blob/e36a28d7da859211c2e355f151cf6cecde6a9668/app/client/src/widgets/TableWidgetV2/widget/propertyConfig/Styles.ts#L73
- https://github.com/appsmithorg/appsmith/blob/e36a28d7da859211c2e355f151cf6cecde6a9668/app/client/src/widgets/TableWidgetV2/widget/propertyConfig/styleConfig.ts#L70

If you change it in both places, it will be good to go.

**Comment by dilippitchika** [comment]
Cool, let's wait for you to merge then we can fix it on our end
