### ISSUE TITLE
[Bug]: Getting snapshot error exception on Appsmith while using dashboard as 5xx

### ISSUE THREAD

**Issue by harshit98** [appsmithorg/appsmith#29067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi team, 

I'm currently working on creating few dashboards on the Appsmith and was exploring some features of it. I was checking logs and found out that whenever I am using my deployed dashboard in Appsmith, an exception raises on load balancer with 5xx status code.

```
Original Stack Trace:
	*__checkpoint ⇢ Handler com.appsmith.server.controllers.ApplicationController#getSnapshotWithoutApplicationJson(String, String) [DispatcherHandler]
Error has been observed at the following site(s):
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
	at com.appsmith.server.services.ce.ApplicationSnapshotServiceCEImpl.getWithoutDataByApplicationId(ApplicationSnapshotServiceCEImpl.java:71)
com.appsmith.server.exceptions.AppsmithException: Unable to find application 646cbfsdsd28ce0d28193n3f99
```

Not sure why this is happening but, looking into the exception logs - seems like some kind of snapshot activity was running in the background. Although, I haven't enabled any snapshot feature on Appsmith. Not sure if this issue can be resolved from my end - that is why opening it as a bug report.

### Steps To Reproduce

1. Create dashboard and deploy on the dashboard.
2. Use dashboard frequently and check 5xx logs related to snapshot.

### Environment

Production

### Version

v1.9.19

**Comment by Nikhil-Nandagopal** [comment]
@harshit98 it seems you are a couple of releases behind. Could you try updating and seeing whether this works on the latest release?

**Comment by harshit98** [comment]
@Nikhil-Nandagopal 

I've already skimmed through the appsmith releases after v1.9.19 but didn't found anything relevant to this error. The error somewhat seems to be related to some kind of snapshot activity going in background which I want to understand in detail. I'm also looking to understand what kind of behaviour would be letting to raise this kind of issue as an 5xx exception. If an engineer from your team can have a quick look - maybe that could help and I can proceed accordingly?

**Comment by nidhi-nair** [comment]
@harshit98 This error should not affect your usage of Appsmith. We'll keep this issue open to make sure that the error message stops polluting our logs, but do let us know if there are any symptoms you're facing that has you especially worried about the error. 🙂

**Comment by harshit98** [comment]
Hi @Nikhil-Nandagopal @nidhi-nair 

Apologies for getting back on this a bit late. I understand that it would not affect our usage of the Appsmith and also (seems to be) it's harmless. But, I want to understand if there is any background activity ongoing which takes the snapshot? I looked into the code from the stack trace and it probably seems to be snapshot activity. Here for [code reference](https://github.com/appsmithorg/appsmith/blob/f4aa8307004177f846484afc9afe091077b942d1/app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java#L253).
