### ISSUE TITLE
[Bug] Widget wise list of field that does not have JS option 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2907]
Property Pane:

1. Button
    1. ButtonStyle
2. Chart
    1. ~~Allow horizontal scroll~~
    2. ~~Chart Data~~
3. Container
    1. Background Color
    2. ~~Scroll Contents~~
4. Dropdown
    1. ~~Selection Type~~
    2. ~~Option~~
    3. ~~Default Option~~
5. Radiobutton
    1. ~~Default Selected Value~~
6. Rich Text Editor
    1. ~~Default text~~
8. Text 
    1.  Text Align
    2.  Text Style
    3. ~~Enable Scroll~~
9. Forms
    1.  ~~Scroll Contents~~
    2. Background Color
10. Table 
    1. ~~Server Side Pagination~~
    2.~~Enable multi row selection~~

**Comment by somangshu** [comment]
@riodeuno can you verify this once

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified this feature and Js option is available for all the above mentioned widgets except 'Container' and 'Form' - Background colour 

<img width="1280" alt="Screenshot 2021-07-06 at 3 14 28 PM" src="https://user-images.githubusercontent.com/35128442/124579727-0749a300-de6d-11eb-92f0-e9cc3eda001a.png">

**Comment by YogeshJayaseelan** [comment]
@Tooluloope @somangshu Retested this now we have JS for Container and Form - Background colour
