### ISSUE TITLE
[Task]: Improve JS binding discovery by showing a transform data option on the canvas 

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#29074]
We believe that the need to transform data arises when users look at the actual data on the widget. By providing a more prominent option on the canvas to write JS transformations, users would discover bindings and JS mode easily.

**Comment by arunvjn** [comment]
PR at https://github.com/appsmithorg/appsmith/pull/29300
DP - https://github.com/appsmithorg/appsmith/pull/29300
