### ISSUE TITLE
[Bug]: Error/outline not displayed when no option is selected (when “Required" is enabled)

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error/red outline is not displayed when we do not select an option (when “Required" is enabled).
<img width="218" alt="Screenshot 2023-11-23 at 10 19 26 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/c8ccc112-5a94-47ed-8d9b-dfd31b61f84a">

### Steps To Reproduce

1. Go to https://ce-28848.dp.appsmith.com/ (this is an Anvil DP. The URL can change in the future).
2. DnD a SwitchGroup widget.
3. Enable the `Required` property.
4. Do not select any option.

**Expected:** We should see an error/red outline when no option is selected.
**Actual:** We do not see any error/outline

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
<img width="1698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3dVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed0656bcfde3f91dd7ef05bdee4c23b033955bf9/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-03-27%20%D0%B2%2013.01.20.png" alt="Снимок экрана 2024-03-27 в 13.01.20.png" />
