### ISSUE TITLE
[Task]: JEST unit test coverage of existing and new components in Home Page Experience

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#29083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Fix the existing failing unit test cases.
2. Add more test case coverage for existing components.
3. Add test case coverage to newly created components.

**Comment by deepikaappsmith** [comment]
The existing JEST test case and cypress covers the functionality and we don't need new JEST. Fixed the failing test cases and hence closing the ticket
