### ISSUE TITLE
[Bug]: Input widgets are overflowing their bounding boxes

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Input widgets are overflowing their bounding boxes:
<img width="419" alt="283349489-5e481cc8-c15e-4974-aacf-aea7f03ba5c1" src="https://github.com/appsmithorg/appsmith/assets/39921438/855a0149-423e-4f15-813f-81eb896c4835">
https://www.loom.com/share/97f9e8c1c1da4f93b43e8dffaaa72e5e

### Steps To Reproduce

1. Go to https://ce-28848.dp.appsmith.com/ (this is an Anvil DP. The URL can change in the future).
2. DnD any input widget.
3. Add more than 1 Zones in the same Section

**Expected:** The input widgets should obey their respective bounding boxes.
**Actual:** The input widgets exceed their boxes.

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29088?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm

**Comment by shadabbuchh** [comment]
@jsartisan opening this, as we are able to reproduce this in certain scenarios.
https://www.notion.so/appsmith/Input-widgets-are-overflowing-their-bounding-boxes-6e69f3eeb4eb4f5b91f0d3114973cf68?pvs=4

**Comment by jsartisan** [comment]
@shadabbuchh Moving this to needs info as it needs some changes from anvil side too.

**Comment by somangshu** [comment]
@jsartisan is this being discussed with the Anvil team? Have you already highlighted this internally?
cc @ramsaptami

**Comment by somangshu** [comment]
This was also something that we saw on the hackathon app, this is easily reproducible and comes up during user tests as well. Should be prioritized

**Comment by KelvinOm** [comment]
@somangshu I'm working on it
