### ISSUE TITLE
[Bug]: Setting the Orientation to “Horizontal” does not display the widget entirely if we have multiple Zones

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we set the orientation to “Horizontal” in group widgets, if we have multiple Zones, the widget is not visible entirely.
<img width="844" alt="Screenshot 2023-11-23 at 10 12 31 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/72c9e6f4-7d73-4083-8a5e-98f5753a69bc">
<img width="544" alt="Screenshot 2023-11-24 at 3 41 49 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/23c89c83-3336-4b37-a9f9-c2eb01867f40">

This also leads to the options going out of canvas and introduces horizontal scroll when we add more items to the group: https://www.loom.com/share/3a1ac99cd3594c4ab1275586f57b8bfe

### Steps To Reproduce

1. Go to https://ce-28848.dp.appsmith.com/ (this is an Anvil DP. The URL can change in the future).
2. DnD any group widget.
3. Add more Zones to the Section.
4. Make the `Orientation` of the widget as `Horizontal`.

**Expected:** The complete widget should be visible.
**Actual:** Widget gets clipped

### Environment

Deploy Preview

### Version

Cloud

**Comment by ramsaptami** [comment]
this has been fixed, widget content does not overflow from the canvas
![image](https://github.com/appsmithorg/appsmith/assets/79509062/96fd7a7c-5e80-44d3-b23d-3db822ae6365)
