### ISSUE TITLE
[Bug]: “Show step arrows” property missing in WDS - Currency Input widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

“Show step arrows” property is missing in the new WDS - Currency Input widget

How it is in prod:
<img width="308" alt="Screenshot 2023-11-24 at 3 20 30 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/3c4c5ea3-5644-4cbc-8371-73745654208b">

### Steps To Reproduce

1. Go to https://ce-28848.dp.appsmith.com/ (this is an Anvil DP. The URL can change in the future).
2. DnD a Currency Input widget.

Notice that the `Show step arrows` property under the General section is missing.

### Environment

Deploy Preview

### Version

Cloud

**Comment by dhruvikn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29094?planning-poker) with Zenhub @jsartisan @KelvinOm

**Comment by KelvinOm** [comment]
https://react-spectrum.adobe.com/react-spectrum/NumberField.html

**Comment by KelvinOm** [comment]
Not relevant anymore.
