### ISSUE TITLE
[Bug]: Tooltip issues in the WDS - Table widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On hovering over cells that have an ellipsis, we get to see a vertical tooltip.
https://www.loom.com/share/2eca46353acf452984027599e768e620
<img width="405" alt="Screenshot 2023-11-24 at 3 59 53 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/b52ee36c-9ff1-4ec4-b135-6d8df98c27b8">

### Steps To Reproduce

1. Go to https://ce-28848.dp.appsmith.com/ (this is an Anvil DP. The URL can change in the future).
2. DnD a Table widget and bind it with some data.
3. Hover over cells that have an ellipsis at the end.

**Expected:** We should see a tooltip that is legible.
**Actual:** The tooltip displayed is vertical and not legible.

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29092?planning-poker) with Zenhub @ichik @jsartisan

**Comment by jsartisan** [comment]
@ramsaptami Closing the app as it is not relevant anymore. Instead of tooltip, we use title attribute now.
