### ISSUE TITLE
[Bug]: Auto height issues in Input widgets

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we have a longer label for input widgets, we can see that the Label overlaps with the input area.
<img width="300" alt="Screenshot_2023-11-22_151547" src="https://github.com/appsmithorg/appsmith/assets/39921438/84424c28-904f-4e81-968a-4d20abf4b73a">

### Steps To Reproduce

1. Go to https://ce-28848.dp.appsmith.com/ (this is an Anvil DP. The URL can change in the future).
2. DnD any input widget.
3. Add a multiline label

**Expected:** The label should not overlap with the input area.
**Actual:** The label overlaps.

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29091?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm
