### ISSUE TITLE
[Task]: Migrate user flags to LaunchDarkly

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#29096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Update Appsmith app to talk to Launch Darkly instead of Flagsmith with the exact same functionality that we have today on the self serve app https://github.com/appsmithorg/appsmith/issues/28442
- [x] #29097
- [x] #29098

**Comment by abhvsn** [comment]
This is completed for the staging environment.

**Comment by deepikaappsmith** [comment]
There are other priority items and hence the appsmith app wasn't taken on priority. appsmith app will be looked after we have some bandwidth. As the migration has completed closing this task
