### ISSUE TITLE
[Bug]: Google Maps fetch Address coordinates not working anymore

### ISSUE THREAD

**Issue by pchambless** [appsmithorg/appsmith#29107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I haven't revisited this API Query for a while, but it used to work and now it doesn't.  I have an API call to Google maps to fetch coordinates based on a supplied address.  My response is consistently:
_{
  "error_message": "You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account",
  "results": [],
  "status": "REQUEST_DENIED"
}_

I've tried changing the key to 'key', 'api_key', 'API_KEY' in the Data Source.  I've tried adding it to the Header and to the Params.  Nothing good happens.  
I've updated the Google Maps API key in the docker.env file and I've also updated it in the Admin settings.  It doesn't work either place.  I DO get a different error response when I include 'key': <my API KEY> in the params

![image](https://github.com/appsmithorg/appsmith/assets/44928133/f719255b-fc7d-45ad-bc87-faa751d15544)

### Steps To Reproduce

[2023-11-24 Google Maps API Call.zip]

### Environment

Production

### Version

Appsmith Community v1.9.47 Released 2 days ago

**Comment by pchambless** [comment]
OK... ChatGPT suggested this code to me in a JSObject
```
export default {
fetchGeoCodes: async (address) => { 

const apiKey = "MyAPIKEY";

const apiUrl = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(address)}&key=${apiKey}`;

fetch(apiUrl)
  .then(response => response.json())
  .then(data => {
    if (data.status === 'OK' && data.results.length > 0) {
      const location = data.results[0].geometry.location;
      {{uLat.setValue(location.lat)}};
			{{uLng.setValue(location.lng)}};
      console.log(`Latitude: ${latitude}, Longitude: ${longitude}`);
    } else {
      console.error('Failed to geocode address');
    }
  })
  .catch(error => console.error('Error:', error));
}
}
```
This works for me.

**Comment by Nikhil-Nandagopal** [comment]
This seems like a change in the way maps handles API keys. I think this should work in the REST API as well if you add it as a query param. Closing this for now but let me know if it still doesn't work there
