### ISSUE TITLE
[Bug] Appsmith can never delete a datasource

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#2912]
There is an endless loop of users not being able to delete datasources that are referenced by APIs, and data sources not being visible when they have no references. This means that once a datasource is created, it stays in our system forever. Users will unknowingly bloat the size of our database for no reason because of it.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair thanks for pointing this out. This is certainly an issue. We've deprioritized this for now because we'll have a holistic solution once we implement global actions

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal How will global actions solve this? 

In this case, don't we just need to display all the datasources in an organization and allow users to manage them?

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit sorry you're right, we need an org level display

**Comment by arunvjn** [comment]
Will be closed along with [https://app.zenhub.com/workspaces/appsmith-actions-pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4567](url)

**Comment by Nikhil-Nandagopal** [comment]
@arunvjn How are these 2 issues related?

**Comment by arunvjn** [comment]
@Nikhil-Nandagopal We provide a list of datasources in API Editor from where the users can navigate to the datasource form. This flow allows a user to finally delete a datasource. Here is the deploy preview for you reference. [https://deploy-preview-4587--appsmith-editor-ce.netlify.app/](url)

**Comment by ajinkyakulkarni** [comment]
We now have a way to delete a data source. So closing this action.

**Comment by ajinkyakulkarni** [comment]
Correction: we have fixed this only for API data sources and not for DB query data sources. Open a new issue - https://github.com/appsmithorg/appsmith/issues/5027
