### ISSUE TITLE
[Bug]: Renaming a JSobj does not get updated on entity explorer 

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#29131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user renames a JSobject it does not get renamed on the entity explorer also a tooltip is constantly seen 
![image](https://github.com/appsmithorg/appsmith/assets/92293815/333ea35f-3d32-42d3-86b9-f1804e212ee0)

### Steps To Reproduce

1. Create a new JSObj and rename it

### Environment

Release

### Issue video log

https://www.loom.com/share/ce94949a6272438389dc160e440b8c8c

### Version

Cloud

**Comment by btsgh** [comment]
Removing release blocker tag and marking as critical as this is also existing on Production. [slack [thread](https://theappsmith.slack.com/archives/CTHN8GX5Y/p1701071301445259)]

**Comment by arunvjn** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/29174
