### ISSUE TITLE
chore: WDS IconButton, sizing refinement

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#29138]
Context:
- https://theappsmith.slack.com/archives/C04P60V0VQE/p1700233776321719?thread_ts=1700233527.286549&cid=C04P60V0VQE
- https://www.notion.so/appsmith/Alignment-and-size-issues-b7fcbe8420164b04b0b40620c82a416f?pvs=4#3baaa44a6a894ef59b598ee31f6d62be

Desired result: button with icon should be the same height as icon with text, it should be of square proportions. We know corresponding cap-size of the text and inner spacing used in a button. Width can be then set with `aspect-ratio: 1`.

**Comment by KelvinOm** [comment]
Close this task as it will be solved in #30426
