### ISSUE TITLE
[Feature] Improve property pane v2

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2914]
## Problem statement
1. Allow it to be dragged and placed anywhere
2. It should open in the same location where it was placed
3. It should scroll with the screen.
4. Opening the property pane should be one click
5. The header of the property pane should be sticky and not scroll away from view
6. JS button design needs to be updated.

**Comment by riodeuno** [comment]
@areyabhishek Also, shortcut for opening the property pane of a selected widget.

**Comment by areyabhishek** [comment]
Either double click or even bring back single click to open.

Single click might not be so annoying.
If the property pane floats and stays in the same location as last time, then we can actually open the property pane automatically for every selected widget. The previous experience of property pane opening up on its own was annoying because it would keep opening up and interrupt what you were trying to do.

**Comment by marks0351** [comment]
More notes on the property pane that we have today when I try to open the property pane by clicking on the setting button often the resize is triggered so I think the double click wud be a great interaction. we can have the pane floating on a corner of the canvas and have a minimize button to minimize the pane, we can give an option to dock it on the side if people prefer the right side docked property pane. thoughts?

**Comment by mohanarpit** [comment]
At the risk of repeating myself, why not enable a right-click interaction to open the property pane? Isn't that a more intuitive way to open settings for any particular widget?

**Comment by areyabhishek** [comment]
We'll consider the right click too. We've discussed this before, we need a moveable property pane for it.
1. With right click, the property pane needs to open up in the same location as the click. That could cover up the widget. Right click-->move property pane-->then make changes. 
2. Right click generally works as a menu, so there's potential to use it for something else.

**Comment by codedmind** [comment]
It should be possible to resize the pane, when we need to write js code... more than one function is complicated view the all code
