### ISSUE TITLE
feat: WDS key-value display mode for input widgets

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#29145]
Cheap solution: a boolean `readonly` on inputs, that turns off borders and backgrounds, sets foreground to `neutral` and turns of editability.

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29145?planning-poker) with Zenhub @KelvinOm @dhruvikn @jsartisan
