### ISSUE TITLE
[Bug]: Widget labels overlap with the Input area

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When viewing on a mobile device or a tablet, the label of WDS widgets overlap with the input area.
<img width="300" alt="Screenshot_2023-10-25_at_4 42 48_PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/39a480ef-b6ce-4712-b442-e13905d706eb">

Sometimes it gets clipped:
<img width="1000" alt="Screenshot_2023-11-24_at_10 20 41_AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/ee4fea85-d55a-4727-8e56-54601b79a765">
 

### Steps To Reproduce

1. DnD a WDS widgets that supports a label e.g. Input, SwitchGroup, CheckboxGroup etc.
2. Deploy the app.
3. View the app in a mobile/tablet viewport.

**Expected:** The widgets should appear without any ui issues.
**Actual:** The labels of the widgets overlap with the input area & sometimes it gets clipped.

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
Not relevant anymore.
