### ISSUE TITLE
[Bug]: JS Object names are not released post deletion

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#29162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Renaming a new JS Obejct to a one that was previous deleted is not working

### Steps To Reproduce

1. Create a JSObject - JSObject1
2. Create another JSObject and renamed it to JSObj
3. Delete JSObj
4. Create a JSObject and try to rename it as JSObj 

Observe that it is disallowed

### Environment

Production

### Version

Cloud

**Comment by btsgh** [comment]
This is handled through another issue opened [here](https://github.com/appsmithorg/appsmith/issues/28766).
