### ISSUE TITLE
[Bug]: Setting APPSMITH_SERVER_TIMEOUT bigger than 60sec do not help with query running longer thant 60sec

### ISSUE THREAD

**Issue by ChriRene99** [appsmithorg/appsmith#29217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I need to increase the timeout with Oracle datasource. 
We set APPSMITH_SERVER_TIMEOUT=1800, but it fails with this error after 60sec:
Deployement on Kubernetes using bitnami chart.

backend container error:
boundedElastic-2: Execute Error closing Oracle StatementClosed Connection

frontend container error:
023/11/16 09:54:29 [error] 111#111: *209 upstream timed out (110: Connection timed out) while reading response header from upstream, 
client: xxxx server: _, request: "POST /api/v1/actions/execute HTTP/1.1", upstream: "http://xxx/api/v1/actions/execute", host: "xx", r
eferrer: "http://xxxx/app/my-first-application/page1-6555e3eb2e0478728a9497f7/edit/queries/6555e43a2e0478728a9497fd?editName=true&showTemplate=false&from=datasources"

### Steps To Reproduce

in the oracle db, create the following function:

create or replace function func
return number
as
begin
  dbms_lock.sleep(80);
  return 0;
end;
/

create a dummy oracle query:
select func from dual

run the query from appsmith

### Environment

Release

### Version

Selfhosted, kubernetes, v1.9.44

**Comment by Nikhil-Nandagopal** [comment]
@ChriRene99 did you change the timeout settings in the query?

**Comment by ChriRene99** [comment]
yes of course, the timeout in the setting query has been set to something bigger than 60sec.
In the gui, I dont get timeout error but: An unexpected error occurred

**Comment by daaliachhak17** [comment]
What is the status of this ticket?

**Comment by NilanshBansal** [comment]
This issue is occurring due to `READ TIMEOUT` configuration not present in Caddy config. 
https://github.com/appsmithorg/appsmith/issues/37244

Assigning this issue to the Devops team.
