### ISSUE TITLE
[Bug]: Select and MultiSelect widgets clear user choices when the filtered options do not contain these choices

### ISSUE THREAD

**Issue by hweissig** [appsmithorg/appsmith#29222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For Select and MultiSelect widgets with server-side filtering enabled, when a user picks one or more options and then filters the remaining options using text not contained in the previously chosen ones, those choices are cleared by the widget.

As a user, I expect my selected options to remain even if they are not in the filtered available options.

### Steps To Reproduce

1. In the linked sample app, choose a name from the list.
2. Type a random string.
3. The previously selected name will disappear unless it matches the filter text.

### Public Sample App

https://app.appsmith.com/app/select-and-multiselect-bug/page1-65677457dceb3203679b73fc

### Environment

Production

### Version

Cloud v1.9.49-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
@hweissig I think you didn't deploy your app. Could you deploy it and mark it as forkable?

**Comment by hweissig** [comment]
Oops… done.

**Comment by Nikhil-Nandagopal** [comment]
@hweissig thanks! I'm able to see it now. Really sorry you faced this issue. We'll have someone from the team look into this.

**Comment by somangshu** [comment]
Upon rechecking, even if the options are present in the filtered list, they still get removed from selection!

**Comment by hweissig** [comment]
Hi! Just checking if there has been progress on this. We've tried some frontend workarounds but have not been able to fix it that way, unfortunately.

**Comment by sbalaji1192** [comment]
Hey @hweissig , We're picking this up early next week.

**Comment by hweissig** [comment]
That's great news, @sbalaji1192 !

**Comment by sbalaji1192** [comment]
@hweissig  We debugged and found the issue. Working on a solution and will tag a PR here soon.
