### ISSUE TITLE
[Feature]: Connector - Databricks

### ISSUE THREAD

**Issue by jordandakota** [appsmithorg/appsmith#29246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Databricks has a REST api for dbsql, but it would be good to have a built in connector like we do for Snowflake.

https://docs.databricks.com/api/workspace/statementexecution/executestatement

### Why should this be worked on?

This would enable users to interact with Databricks data without having to build a custom rest api.

**Comment by GreenFlux** [comment]
Closed by: https://github.com/appsmithorg/appsmith/pull/29746
