### ISSUE TITLE
[Bug]: Meeting scheduler Template shows Page Not Found error on trying to invoke it. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to use the Meeting Scheduler template, the template view shows up with Page Not Found error. This works fine on app.appsmith.com

### Steps To Reproduce

Release

<img width="1419" alt="Screenshot 2023-12-01 at 12 46 49 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/64196e86-ca63-4ecb-94b8-4781c85a6829">

Production

<img width="1434" alt="Screenshot 2023-12-01 at 12 46 57 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/b4c94d92-bdbb-4881-bb2b-e7f88bce0857">

### Environment

Release

### Version

Cloud

**Comment by rahulbarwal** [comment]
It is available now: https://release.app.appsmith.com/templates/631f7e8a47a7d75706eb6ef7

Please reopen if you notice this again.
