### ISSUE TITLE
[Bug] Confirmation option is not displayed to the user on refreshing page

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2925]
Steps to reproduce:
1) Navigate to API Pane
2) Add an API
3) Navigate to setting
4) Check on "Confirm before running"
5) Add an Table widget
6) Bind an API for the same
7) Refresh a Page 
and observe

Observation:
It is observed that the table does not load and confirmation message is not displayed to user

Expectation:
A confirmation pop up must be displayed to user and on confirmation message the table must load

Video
https://www.loom.com/share/f3824154099e4f6ca17e69f94639b624

**Comment by hetunandu** [comment]
Confirmation will not show since the action is not called. Action onLoad has been turned off as you can see from the video. If you turn that on, it should show the confirmation
