### ISSUE TITLE
New theme settings Integration

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#29262]
After the backend team sets up the API for new theme setting, we will need to integrate it with new theme setting panel.

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29262?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm
