### ISSUE TITLE
[Bug]: List widget is missing most of its setter methods

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#29295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to set my List widgets data programmatically I see that it only has a `setVisibility` function.

I expected to see functions for `setData`, `setDataIdentifier` and the rest of its properties.

### Steps To Reproduce

1. D&D a List widget
2. Create a new JS Object.
3. Type `List1.set` into one of the functions and observe `setVisibility` is the only option.

### Environment

Production

### Version

Cloud - 1.9.50-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3j6frg)

**Comment by Nikhil-Nandagopal** [comment]
Not a bug. There are only a few setters available for some widgets where users like using the imperative programming style. By default setting values in the property pane reactively is best
