### ISSUE TITLE
[Bug] UX  : API timeout option does not look like an editable field

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2930]
Steps to reproduce:
1) Add an API 
2) Navigate to Setting option 
and observe

Observation:
1) The API timeout option is not visible as an editable field 
2) As we focus on the field it is highlighted with Red border. 

Expectation:
In Appsmith we use red border around the field to indicate incorrect or empty mandatory field this would let user get confused.hence would recommend to have deep embedding field/ Grey coloured field.

**Comment by Nikhil-Nandagopal** [comment]
This is solved in the new API Pane UX

**Comment by prapullac** [comment]
Hi Nikhil
The field is highlighted in "RED". Hence reopening the issue 

![Screenshot 2021-02-12 at 10 37 17 AM](https://user-images.githubusercontent.com/71753653/107732447-5c4e1680-6d1e-11eb-83bc-ccbf766f2dc8.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac I believe that is the expected behavior. Does this match the design?

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal this is focused state from our ads and thus this is expected

**Comment by prapullac** [comment]
Closing the issue as per above comment
