### ISSUE TITLE
Pages hidden for "Inventory management" template

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#29311]
[Inventory management templater](https://app.appsmith.com/templates/641e7b9024394b5e2a662530)

When I fork this template all pages are hidden by default.
<img width="316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL293QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9750d7a842d8015fccdb5aa5a43acad227b4e82/Screenshot%202023-12-05%20at%202.15.52%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 2.15.52 PM.png" />

Expected: Pages should be in visible state by default.

**Comment by jacquesikot** [comment]
I have set the pages to show on the template app and re uploaded the app JSON to S3.
