### ISSUE TITLE
[Task]: Client side module instance issues

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#29317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- After every module publish there is a copy of module that gets created for the application.
expected behaviour was that after publish the module will auto updated and there won’t be any duplication of module.
- Action update call i.e., confirm before execute settings update only happens for the case when we want to make it true which means we are not updating it when user is making confirm before execute false

### Steps to reproduce
https://theappsmith.slack.com/archives/C04GRCN4CS3/p1701768833099089

**Comment by pedro-santos-rodrigues** [comment]
Isn't this bug already solved @ashit-rath @ApekshaBhosale @ankitakinger ?

**Comment by ashit-rath** [comment]
Yes, this is resolved
