### ISSUE TITLE
[Bug]: workspace selection scroll overreaches - cannot see the CTAs

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#29314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I select a workspace, the scroll to that workspace is a bit over by a few pixels: I can't see the workspace CTAs. 

https://github.com/appsmithorg/appsmith/assets/94514895/783b4aa7-0973-4380-b1a5-8527bb7a87a7

### Steps To Reproduce

follow the steps in the attached video, or:
1. login to appsmith with an account that has many workspaces
2. select some workspace that is below the first default viewport
3. upon selection, a scroll occurs
--> notice that the workspace name and the workspace CTAs are not visible. They are just above the viewport.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing since the new homepage won't have a scroll
