### ISSUE TITLE
[Bug]: Unnecessary scroll added to snipping mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unnecessary scroll is added to snipping mode instead of listing down all the options in the space below and adds too many scrolls to the UI

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/e7cad682-b953-4f2b-b28a-eaae851b2c4c)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/600ecba1-c5cb-4b79-a400-eb15b6d77e90)

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
also being tracked here: https://www.notion.so/appsmith/Unnecessary-scrollbars-in-the-binding-pane-on-query-page-9ba6ac7ce2da4d969a41773505969dd4
