### ISSUE TITLE
[Bug]: Application logo icon on homepage does not respond to clicks even though a click icon appears on hover

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Exit icon that appears on top of the page with a click icon on hover but does not amount to any action on clicking

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/2ba255a3-c9e0-4113-8590-5f6ee5d8f171)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami I don't see this

**Comment by ramsaptami** [comment]
shows up for admin users of an instance @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami still not seeing it. Can you share a video?

**Comment by ramsaptami** [comment]
Ok this is for the application logo defined under branding. Looks like it was configured to be an exit icon on the instance we were testing. So app logo on the workspace page does not do anything even though a click icon appears on hover.

**Comment by Nikhil-Nandagopal** [comment]
I think that's expected and seen on most products like Gmail where the homepage icon is clickable does just refreshes the current page. Closing this
