### ISSUE TITLE
[Bug]: Unable to run the query module in a git connected application

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to run a query module from a published package, inside a git connected app, I get an error

### Steps To Reproduce

<img width="966" alt="Screenshot 2023-12-05 at 5 46 32 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/986300d8-631b-4a63-a9c6-3bb5314d7c37">

https://github.com/appsmithorg/appsmith/assets/101863839/06a1250e-7402-4033-8920-6ffb41372085

### Environment

Release

### Version

Cloud

**Comment by nidhi-nair** [comment]
Hasn't been implemented as a functionality yet, part of our deliverable this week. Keeping it open all the same.

**Comment by nidhi-nair** [comment]
@btsgh could you please re-verify this and close the issue if things look okay?
