### ISSUE TITLE
[Bug]: On trying to create a query module from a new mongo db, automatic query does not get generated. Collection also does not get populated

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create a new Mongo DS with details frm [here](https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79?pvs=4#548f42ade97d403892d47a85ba59ec36), the auto query does not get populated, as well as the collection dropdown is empty.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/4d9f760f-137b-437e-a79e-67f134d7bd6a

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
