### ISSUE TITLE
[Bug] API datasource are not listed in the list of datasources

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#2933]
Steps to reproduce:
1) Add a API datasource
2) Click on Edit Datasource
3) Now edit and save the datasource
4) Click on the back navigation 
and observe

Observation:
It is observed that the user is navigated to the list with query datasource and API datasources are not listed 

Expectation:
When user is navigated to "List of datasource" page when user is back navigated from the API datasource this is misleading to the user and takes a while in understanding which page he is on.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu we've deliberately separated these. The solve here should be to not take the user to the data source screen on pressing back but to take him to the API pane
