### ISSUE TITLE
[Bug]: On hovering over a long label, we do not see a tooltip

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For all WDS widgets that support a label, when we hover over a long label, we do not see a tooltip to display the whole label.

### Steps To Reproduce

1. Go to any latest Anvil instance.
2. DnD any widget that supports a label.
3. Enter a long label.

**Expected:** On hovering over a long label name, a tooltip should be appear to display the whole label.
**Actual:** No such tooltip appears.

### Environment

Deploy Preview

### Version

Cloud

**Comment by ramsaptami** [comment]
<img width="402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d537973a35750bc43dee549a005b1591220d765a/image.png" alt="image.png" />
