### ISSUE TITLE
[Bug]: Options in WDS radio group widget get distorted in a Section with > 1 Zone

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The options of a Radio group widget get distorted when `Orientation` is set to `Horizontal`.
<img width="300" alt="Screenshot_2023-11-28_at_4 38 47_PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/36a82f5f-c517-46d5-8203-1b3b6a69137d">

### Steps To Reproduce

1. Go to the latest Anvil instance.
2. DnD a Radio group widget.
3. Add some more options & set the `Orientation` to `Horizontal`.

**Expected:** The options should be displayed appropriately.
**Actual:** The options get distorted.

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
We also do not display options. We have 5 shares here and it shows only 3
![Снимок экрана 2024-02-27 в 14 04 46](https://github.com/appsmithorg/appsmith/assets/11555074/fb948259-bd19-417d-b8de-4f38d5a82c6c)
