### ISSUE TITLE
[Bug]: WDS PhoneInput input area displays “+” & country code in different lines

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The WDS phoneInput input area displays “+” & country code in different lines.
<img width="300" alt="Screenshot_2023-12-04_at_3 03 22_PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/af334696-828a-42f5-81ad-cb1c65b040fd">

### Steps To Reproduce

1. Go to the latest Anvil instance.
2. DnD a Phone Input widget.

**Expected:** The `+` & country code should come in a single line.
**Actual:** They appear in different lines

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29362?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm
