### ISSUE TITLE
[Bug]: Alignment issues with WDS Button group widget

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The WDS button group widget being a fill widget should occupy the whole row space available. However we can see that it does not do so and because of this it looks as if it is left aligned when the app is deployed.
https://www.loom.com/share/a3b387fbd4c84125b8ddcbe14a01f740

### Steps To Reproduce

1. Go to any latest Anvil instance.
2. DnD a button group widget such that it is the only widget inside a Zone.
3. Deploy the app.

**Expected:** The button group widget should occupy the whole horizontal space in a Zone.
**Actual:** The widget does not occupy the whole space.

### Environment

Deploy Preview

### Version

Cloud

**Comment by KelvinOm** [comment]
Will be fixed as part of [task](https://github.com/appsmithorg/appsmith/issues/29426)
