### ISSUE TITLE
[Bug]: Instance is crashing on navigating or performing any action on Canary browser.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#29370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Instance is crashing on navigating or performing any action on Canary browser.

https://github.com/appsmithorg/appsmith/assets/109572422/65aa27fb-98d9-486d-91b6-94f305d2bb60

### Steps To Reproduce

1. Log into Appsmith on Canary browser
2. Create an app
3. Try to navigate between pages/data or any other section. 
4. Notice that the instance crashes repeatedly
![image](https://github.com/appsmithorg/appsmith/assets/109572422/f70de263-abc2-4bcd-aebb-f9c039eeac70)
![image](https://github.com/appsmithorg/appsmith/assets/109572422/403c9142-5ecf-476b-bc8c-6a0450593790)

### Environment

Production

### Version

v1.9.50

**Comment by somangshu** [comment]
Is this specific to Canary @laveena-en ?

**Comment by laveena-en** [comment]
Yes @somangshu Specific to Canary and happens whenever the user navigates between different sections of the app.  
Changing the priority to high since the issue is highly likely to migrate to Chrome browser as well.

**Comment by rohan-arthur** [comment]
Here's a video of my test on canary, looks like things are working as expected. Please reopen this issue if you still see problems. 

https://github.com/appsmithorg/appsmith/assets/94514895/5e990392-e3d2-4372-a2ad-8c161d5f2b9b
