### ISSUE TITLE
[Feature] IN operator for action editor forms' hidden field logic

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2938]
## Summary

This is about adding an `IN` and `NOT_IN` operators to the supported comparisons in action editor forms.

## Motivation

For the Firestore plugin, we need to hide the body input field when the operation selected doesn't need a body. That is, when the operation is one of `GET_DOCUMENT` or `GET_COLLECTION`, or even `DELETE_DOCUMENT`. So, if an `IN` operator is supported, we'll be able to configure the visibility of the body field something like the following:

```json
{
  "label": "Body",
  "configProperty": "actionConfiguration.body",
  "controlType": "QUERY_DYNAMIC_TEXT",
  "hidden": {
    "path": "actionConfiguration.pluginSpecifiedTemplates[0].value",
    "comparison": "IN",
    "value": ["GET_DOCUMENT", "GET_COLLECTION", "DELETE_DOCUMENT"]
  }
}
```

This is solvable if a `REGEX_MATCH` operator is available instead of an `IN` operator, but `IN` seemed simpler. I'm perfectly fine with either.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 doesn't this require frontend change as well? What we can do is start using a JS eval instead of this custom logic here
