### ISSUE TITLE
[Bug]: [Sentry] AppsmithPluginException   com.internal.helpers.DataUtils in parseJsonBody | CLOUD-SERVICES-8

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#29381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4303630673/

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by sneha122** [comment]
Checked out this issue briefly, it looks like a legit issue from user's end, where the JSON is not in the correct format. Also looking at sentry, the issue has occurred only for this 1 user for 819 times, In such case:
- We can either reach out to this user, if possible, to help them correct the JSON formatting for this specific action
- Or we can suppress this event on sentry as it's a legit issue in JSON

CC: @rohan-arthur

**Comment by NilanshBansal** [comment]
Closing this as this is a user issue. Also the occurrences are limited.

**Comment by rohan-arthur** [comment]
reopening this issue because it is a valid error for malformed json, we should not be logging to sentry.

**Comment by NilanshBansal** [comment]
From the sentry logs, it seems that this issue is only occurring for the Airtable plugin. 
This is evident from the response structure.

<img width="631" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/3d2c7c66-7799-453a-9d51-9ed719253e7f">

**Comment by NilanshBansal** [comment]
Closing this as completed in https://github.com/appsmithorg/cloud-services/pull/1564
