### ISSUE TITLE
[Bug]: Unable to delete a module once created

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Once a module package is added from the entity explorer, selecting 'delete' does not amount to anything.

### Steps To Reproduce

1. Add a module package from the entity explorer and try to delete it from the options and observe nothing happens

### Environment

Release

### Version

Cloud

**Comment by vaibhavchobisa** [comment]
Hi @ramsaptami 
I would love to resolve this issue, can you please describe it more?

I tried to install an uninstall packages from the left panel and it seems to be working for me.

**Comment by ramsaptami** [comment]
@vaibhavchobisa this is a WIP feature that the team is not yet public. Please take a look at issues marked [Good first issue](https://github.com/appsmithorg/appsmith/labels/Good%20First%20Issue) if you're looking to contribute.

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by pedro-santos-rodrigues** [comment]
Isn't this already fixed @ashit-rath @ApekshaBhosale @ankitakinger ?
