### ISSUE TITLE
[Bug]: 400 response leads the user away from application page when Oauth configuration is not right

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App error state and message is displayed outside the application when OAuth configuration is not correctly done instead of showing a prompt on the application

### Steps To Reproduce

1. Create an authenticated api DS and enter only client secret under OAuth configuration
2. save and authorize and observe the user is navigated to a black screen with a 400 message instead of on in-app prompt

### Environment

Production

### Issue video log

https://www.loom.com/share/f219be10afa44204b7329895de646a3f

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
this is largely expected because we don't know whether the credentials are correct until they hit the 3rd party provider
