### ISSUE TITLE
[Bug]: Container widget with height (adjust with limits option) - the content adjusts, but with a scroll bar until the invisible items

### ISSUE THREAD

**Issue by leonardo-ciandt** [appsmithorg/appsmith#29403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we use the widget container with the "Adjust with limits" option with 3 labels, for example vertically, when there is the logic of not displaying labels 2 and 3, the content is adjusted to the minimum height but a scroll is created and the ideal would be not have

### Steps To Reproduce

1 - put widget container
2 - put 3 labels inside
3 - put the minimum height up to the first label
4 - make the last 2 labels invisible

the content will adjust but with a scroll bar

### Environment

Production

### Version

Self hosted - 1.9.45

**Comment by Nikhil-Nandagopal** [comment]
@leonardo-ciandt I'm not able to reproduce this issue. Could you share a sample public app on https://app.appsmith.com

**Comment by Nikhil-Nandagopal** [comment]
@leonardo-ciandt that's pretty odd and shouldn't be the case. Let me know if you are able to reproduce it on a new app and we can take a look
