### ISSUE TITLE
[Bug]: Import modal AI datasource throws internal server error on Test configuration

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on Test configuration while importing AI ds, I get an internal server error. This works fine when I connect from data flow inside the application 

### Steps To Reproduce

<img width="1438" alt="Screenshot 2023-12-07 at 9 57 15 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/5471d3ad-e609-465b-a6f0-9989c1b9abf2">

### Environment

Release

### Version

Cloud

**Comment by sneha122** [comment]
Discussed with @sondermanish, He will be picking this up as it concerns open AI plugin implementation for import export.

**Comment by laveena-en** [comment]
This issue is occurring again on release.app.appsmith.com 
![image](https://github.com/appsmithorg/appsmith/assets/109572422/d4b46f32-120b-451e-b34e-b9977bf28952)
