### ISSUE TITLE
[Feature] Auto-completions in bindings in action editor controls from JSON forms

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#2940]
## Summary

Bindings inside action editor fields are supported and work when the action is executed, but there's no indication of this fact when writing the binding. There's no auto-completion and there's no syntax highlighting either. This gives the false impression that bindings aren't supported in this field (like one recent user was wondering).

![Screenshot 2021-02-09 at 19 08 24](https://user-images.githubusercontent.com/120119/107371341-30f2de00-6b0a-11eb-8ddc-a712f1b540d7.png)

## Motivation

Treating these input fields like other input fields that have support for bindings will help set the right expectations.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu @mohanarpit can we do this on priority? Feels like most of our new data sources won't be useful without this feature. How do we make it so that this is just the default experience when building UI? All Input fields come with the autocomplete and evaluated value

**Comment by mohanarpit** [comment]
Yes. We will pick this up on priority. Since all the datasources use the same underlying components, this fix should be global in nature.

**Comment by hetunandu** [comment]
Is this not an action configuration? Datasources are not part of data tree today and may need more work

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu this is a query not a datasource
