### ISSUE TITLE
[Bug]: App name and side panel margins don't align on the new IDE design

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Application name and side panel margins need to align, currently app name margin is slight off to the left of that margin.

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/ebf8ee9f-7727-4286-bced-7327387b92cd)

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
no longer valid, app name has been moved now
![Screenshot 2024-05-30 at 15 42 37](https://github.com/appsmithorg/appsmith/assets/94514895/01ce5812-8a0b-4d57-8e13-e848163e0bce)
