### ISSUE TITLE
[Bug]: ECharts are not clickable in the preview mode and when deployed

### ISSUE THREAD

**Issue by ed-parsadanyan** [appsmithorg/appsmith#29406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the new custom ECharts, they seem to be non-clickable in the Preview mode and when the app is deployed. Only during the edit mode Charts need to be first selected and then hover effects are activated.
Setting silent = false doesn't help: https://echarts.apache.org/en/option.html#series-bar.silent

[appsmith-echart-bug.webm](https://github.com/appsmithorg/appsmith/assets/10472129/44624638-58cc-408c-849f-9277beafbc67)

### Steps To Reproduce

1. Create a new app
2. Put a Chart Widget
3. Select "Custom EChart" type
4. In the edit window you first need to click on the widged before hover effects appear.
5. In the preview / deployed mode the charts are completely non-clickable

### Environment

Production

### Version

Self-hosted Appsmith Community v1.9.50

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3n3r9o)

**Comment by owlyjieun** [comment]
I'm having the same issue. Due to the issue, I'm unable to display tooltip and create an interactive table that changes the data dynamically based on the user's click. This is a huge problem. I can't use a custom Echart with a bug like this. I'm very concerned that the custom fusion chart will be deprecated when custom Echart is not fully functioning.

**Comment by ed-parsadanyan** [comment]
> I'm having the same issue. Due to the issue, I'm unable to display tooltip and create an interactive table that changes the data dynamically based on the user's click. This is a huge problem. I can't use a custom Echart with a bug like this. I'm very concerned that the custom fusion chart will be deprecated when custom Echart is not fully functioning.

I hope this is an easy-fixable bug. The issue would affect many users if kept untouched, I believe.

**Comment by rajatagrawal** [comment]
Apologies for the bug @ed-parsadanyan @owlyjieun.

This issue has been resolved [here](https://github.com/appsmithorg/appsmith/issues/29226). The bug fix should be available in the next release cycle.
