### ISSUE TITLE
[Bug]: Export/import is not working when no entity is selected from the modal 

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#29414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Empty json is exported if user does not select any entity from partial import export modal and on importing the same json no entity is imported. Only success message shown off

Attached loom here : https://www.loom.com/share/7f25316d914a4d338a510eb65746baed?sid=2fd68dfb-da80-4784-a10a-891b49ee5e4e

### Steps To Reproduce

1. Create a page 
2. add some entity like widgets, JSobj and queries
3. Deploy the app
4. Export it without selecting any entity individually
5. create a new page in the same app
6. Import the json and observe

### Environment

Production

### Version

Appsmith v1.9.50-SNAPSHOT

**Comment by AnaghHegde** [comment]
This is expected behaviour, hence closing this ticket.

**Comment by rahulbarwal** [comment]
We can disable the export button if nothing is selected. I'll take care of this, reopening ticket.

**Comment by rahulbarwal** [comment]
Already fixed with: https://github.com/appsmithorg/appsmith/pull/29546
