### ISSUE TITLE
[Bug]: Path details of a URL cannot be added during app import configuration

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Previously, path details, like `/posts` could be added while reconfiguring datasources during app import. Save button would be enabled to proceed with this configuration
Now, only the domain information is accepted and save button is disabled if path details exist.

Post import, user can navigate to the datasources page and add in the path information to their saved API datasource

### Steps To Reproduce

1. Export and import an app that has a saved API datasource
2. On the configuration modal, enter `https://jsonplaceholder.typicode.com/posts` and observe the save button is disabled
3. Remove path information and observe the save button gets enabled
4. Save the configuration and navigate to the datasource inside the application and edit the URL to contain path details and observe this is allowed.

### Environment

Production

### Version

Cloud

**Comment by riteshkew** [comment]
Since it is an issue on the Datasource configuration modal which comes up post the app import is successful, moving it to Integrations pod

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/f362977a-f9d1-47f2-bdeb-56dbd0ebc666

not replicable anymore, maybe got fixed somewhere else
