### ISSUE TITLE
chore: WDS adjust inner spacing steps

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#29423]
Currently, the minimum inner spacing step has a value of around 6px.
We need smaller inner spacing for microelements, e.g. `TagGroup` that is currently being worked on.

Todo:
- adjust inner-spacing-1 to about 4
- previous usages of inner-spacing-1 may need to switch to step 2

**Comment by ichik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29423?planning-poker) with Zenhub @jsartisan @KelvinOm
