### ISSUE TITLE
[Bug]: Suggested query option is missing when we try to add a query module

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create a query module, I do not see the suggested query option in the New Query generation page.

### Steps To Reproduce

<img width="386" alt="Screenshot 2023-12-07 at 4 15 51 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/35cceeca-8622-49ad-b45d-8502bf8c0e35">

This is how it is shown in an application when we try to create a query. This option is not available for a query module.
<img width="419" alt="Screenshot 2023-12-07 at 4 15 44 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/415733cf-ba58-42b9-9371-feda55fb2235">

### Environment

Release

### Version

Cloud

**Comment by ankitakinger** [comment]
This should be fixed now. @kamakshibhat-appsmith @btsgh could you re-verify?

**Comment by kamakshibhat-appsmith** [comment]
looks good @ankitakinger

**Comment by ankitakinger** [comment]
Closing this in that case.
