### ISSUE TITLE
[Bug]: Issue with MySQL SSH Tunnel Datasource on Creating New CRUD Pages

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#29449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I attempt to create a new page on an app and select "New Page from Datasource" with a MySQL SSH tunnel datasource, the operation fails.

What I expect is for the new CRUD page creation to proceed successfully without encountering errors.

### Steps To Reproduce

1. Have a MySQL SSH tunnel datasource set up.
2. Create a new page on an app and select "new page" from the datasource.
3. Upon selecting the datasource, the operation fails.
4. Edit the datasource, reload the certificate, and the page works fine.

### Environment

Production

### Version

Cloud 1.9.49-SNAPSHOT

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3n80y4)

**Comment by sumitsum** [comment]
Hi @LagunaElectric are you clicking on the `Test configuration` and `Save` buttons on the datasource before clicking on create new crud page ?
