### ISSUE TITLE
Split Text widget

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#29446]
It is necessary to divide the current text widget into two
1. Header — everything is the same as it is now, but the default font size is **heading**
2. Paragraph —  everything is the same as it is now. We just change the names of the widget.

Also, as part of the task, it is necessary to remove the ability to set the **text color**

**Comment by kushalsng** [comment]
Hi @KelvinOm 
I would like to fix this issue. Please assign it to me

**Comment by KelvinOm** [comment]
Hi @kushalsng, first of all, thank you for the request and your proactivity.

This task does not relate to the current functionality. We in WDS team are currently developing a new set of widgets under the feature flag, so this can be bit complicated. If you want to get acquainted with the workflow, then I would suggest starting with a task under the label [good first issue](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22).

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/29446?planning-poker) with Zenhub @dhruvikn @jsartisan @KelvinOm
