### ISSUE TITLE
[Feature] Generate Forms from DB structures for creating/inserting/adding entries

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2948]
## Summary
A way for users to generate forms easily using the database structure.

- It should be automatically be able identify the datatypes and associated widgets for the form
- It should be able to add basic validations which can be enhanced by the user
- It should be able to automatically connect the submit buttons to the relevant queries.

## Motivation
One of the most common operations in any DB is the insert/add/create entry operation. It would go a long way to save user time by generating the scaffolding, if not the complete widget for users.

## Additional Context
Design for validations and UX for the form generating wizard needs to be discussed.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno closing as it's a duplicate of #2504
