### ISSUE TITLE
[Bug]: Renaming new JS Object not working instantly

### ISSUE THREAD

**Issue by moloyb-22** [appsmithorg/appsmith#29482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a new JS object for custom code works fine but after creation if I try to rename this new object from default name (JSObject1), it doesn't work instantly. It shows some error popup which is confusing too with text `<js_object_name> is already being used or is a restricted keyword`

Refreshing the page however solves this problem and renaming takes effect immediately.

### Steps To Reproduce

1. Open any AppSmith Page.
2. Try to create New JS Object.
3. New JS Object is created with name JSObject1.
4. Try to rename it for better readability as per choice.
5. Error is shown to restrict the renaming.
6. Refresh the page, renamed JS Object appears fine.

Attached screen recording to understand the steps.

### Environment

Production

### Issue video log

https://www.loom.com/share/079c300282d84574a6bf0e827dc73b62?sid=441feb86-f0a6-4355-98fc-967929d20729

### Version

v1.9.50

**Comment by bharath31** [comment]
@arunvjn could you investigate this?

**Comment by vaibhavchobisa** [comment]
Hi @Nikhil-Nandagopal, @bharath31, @arunvjn 
I have just raised a PR that fixes the issue. Can you please review the code, and generate a DP? Thanks!

**Comment by satbir121** [comment]
Thanks for the contribution @vaibhavchobisa! We will get back to you soon.
