### ISSUE TITLE
[Bug]: "Hey! There is a new version" pop up doesn't go away after clicking the "Refresh" button

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#29506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Running self hosted community version witch docker-compose on Ubuntu 20.04.6.

After the automatic update to 1.9.51 the "Hey! There is a new version" pop up appears. When clicking the "Refresh" button the page reloads but the pop up appears again.

I've tried clearing chromes cookies/cache but no difference. The problem also occurs in Edge and Firefox.

Tried restarting the server Appsmith runs on but that didn't work either.

### Steps To Reproduce

1. Open any page, in either editor och viewer modes
2. Click the "Refresh" button on the "Hey! There is a new version" pop up"
3. The page reloads and the pop apears agan and again

### Environment

Production

### Version

Self hosted / 1.9.51

**Comment by sharat87** [comment]
Hey @oskarannas, we're working to push the fix as a new version and should be out soon (in the next ~2h).

Thank you for your patience.

**Comment by oskarannas** [comment]
> Hey @oskarannas, we're working to push the fix as a new version and should be out soon (in the next ~2h).
> 
> Thank you for your patience.

Wow, thats great! Thanks :)

**Comment by oskarannas** [comment]
Can confirm the fix works after upgrading, big thanks!
