### ISSUE TITLE
[Bug]: Unable to use public apps with module instances as an anon user

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#29518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We're missing calls to `/moduleinstances` and `/moduleinstances/entities` in the view mode when using an app as anon

### Steps To Reproduce

1. Create a module and publish
2. Consume in an app, and publish. Make app public
3. Log out and try to access app in view mode as anon

### Environment

Release

### Version

Self Hosted

**Comment by ankitakinger** [comment]
We have enabled the feature flag for release EE instance to test this feature out with public apps.
