### ISSUE TITLE
[Bug]: Unable to run airtable queries from the release-ee-https environment

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to run a query on airtable DS, from the https://release-ee-https.appsmith.com/ environment [It is an upgraded environment which we use for regression testing, to emulate customer scenario], it throws an unauthorized access error. The same query, connected to the same airtable, works on https://release.app.appsmith.com/

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/2b8b6d51-c670-4a90-b9f6-d9e372c8c37f

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
This seems to be true for Twilio / Hubspot as well.

**Comment by rohan-arthur** [comment]
being discussed and tracked [here](https://theappsmith.slack.com/archives/C040LHZN03V/p1702291102611099)

**Comment by sneha122** [comment]
The issue has been fixed as [thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1702291102611099) @btsgh Please check  once
