### ISSUE TITLE
[Docs] Add a guide to whitelist MongoDB

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2951]
# Description
A guide to whitelisting the appsmith instance IP on mongocloud

**Comment by devbret** [comment]
I'm new to Open Source, and would like to give this issue a try. Is it still open? And if so, can I work on it?

**Comment by Nikhil-Nandagopal** [comment]
Hi @devbret 👋 
Please I'm assigning this to you. Go for it!

**Comment by devbret** [comment]
Thank you, I will be working on this tonight and throughout the week if need be. Can I ask questions if I get stuck?

**Comment by mohanarpit** [comment]
@devbret Absolutely! Feel free to ask questions if you get stuck at any point. Please take a look at our [Documentation Contribution Guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) for details on how to improve Appsmith's documentation.

**Comment by devbret** [comment]
@mohanarpit Thank you for the link and the comment. I will be reviewing these documents tonight.

**Comment by devbret** [comment]
@mohanarpit After having reviewed the Documentation Contribution Guide, I am wondering where you would like me to add the information about whitelisting MonogoDB? Is there a particular document you'd like me to add it to? Or do I need to create a new file?

**Comment by Nikhil-Nandagopal** [comment]
@devbret you can create a new one similar to this
https://docs.appsmith.com/v/v1.2.1/core-concepts/connecting-to-data-sources/aws-whitelist

**Comment by devbret** [comment]
@Nikhil-Nandagopal Alright, thank you for the example. I will continue working on this example tonight and throughout the week.

**Comment by devbret** [comment]
I'd like to make sure I'm documenting the correct MongoDB Cloud service for this project. Is [this the service](https://www.mongodb.com/cloud) I should be making a guide for?

**Comment by mohanarpit** [comment]
@devbret Correct. You have the correct URL.

**Comment by devbret** [comment]
@mohanarpit I am getting close to finishing the guide, but I wanted to give you a heads up that the images I'm using are not of the same high quality as those in the example document linked to earlier on. I lack the photo editing software to make images that are beautiful. Is this alright?

**Comment by mohanarpit** [comment]
It depends on how the images that you upload look. Will be able to give a more definitive answer once we see the PR. Typically, as long as the image text is readable & understandable for users, it's fine. That's the goal.

**Comment by Nikhil-Nandagopal** [comment]
@devbret These are our image guidelines
https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/UploadingAssets.md
We don't use any editing software ourselves, we simply use screenshots right from our machines. The key is to focus the screenshot on the area you're describing and not capturing the entire window. This will give the focus area more attention

**Comment by devbret** [comment]
I took a look at your image guidelines and I'm now much more confident about what I will be submitting to you when I've finished. In other words, my screenshots appear to be what you're looking for.

Thank you for answering all of my questions throughout this project. You've both made my first Open Source experience quite enjoyable.

**Comment by devbret** [comment]
I have included all of the steps for adding an IP address to MongoCloud. Here is the document I've been working on - https://github.com/devbret/appsmith-docs/blob/v1.2.1/core-concepts/connecting-to-data-sources/mongocloud-whitelist.md

But I'm curious how I should finish the document. In your example (https://github.com/devbret/appsmith-docs/blob/v1.2.1/core-concepts/connecting-to-data-sources/aws-whitelist.md) I notice that your file closes with a sentence about being able to access the relevant service. Is there anything you'd like me to include as a closing thought? Also, please let me know if there are any improvements I can make to my contribution.

Thank you for your help in working with your Open Source project. I've learned a lot about collaboration and am interested in doing more Open Source work with other applications in the future.

**Comment by Nikhil-Nandagopal** [comment]
@devbret can you please raise a PR to the docs repo so we can review it

**Comment by devbret** [comment]
Okay, I've gone ahead and raised a PR for you to review. Please let me know if there is anything I can improve and/or add.

**Comment by areyabhishek** [comment]
Thanks for the contribution @devbret! We merged your PR in. Sorry it took us a bit of time.

**Comment by devbret** [comment]
I am happy to have helped. Thank you for guiding me along the way, as this was my first Open Source contribution.

**Comment by areyabhishek** [comment]
That's awesome!
