### ISSUE TITLE
[Bug]: Loading widgets with async variables (store)

### ISSUE THREAD

**Issue by leonardo-ciandt** [appsmithorg/appsmith#29525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Would it be possible to manipulate the loading state of widgets through variables in local storage asynchronously?

I don't know if it's actually a bug, but when I try to work with the storage variables in the **Animate Loading** property, it doesn't seem to work so well

### Steps To Reproduce

1 - put widget
2 - set **Animate Loading** property of local storage (appsmith.store.anyVariable)
3 - create async function when change this value (true to false)

### Environment

Production

### Version

Self hosted - 1.9.45

**Comment by leonardo-ciandt** [comment]
**Example:**

- Display the skeleton loading until the variable asynchronously is set to true after the content is loaded

**Comment by Nikhil-Nandagopal** [comment]
@leonardo-ciandt it should automatically happen if your widget is bound to the async function and the async function is returning the promise of the queries it is running. You don't need to manipulate animateLoading, that property is only to disable the loading option.

**Comment by Nikhil-Nandagopal** [comment]
I'm closing this issue for now. Let me know if it's not resolved

**Comment by leonardo-ciandt** [comment]
@Nikhil-Nandagopal I understood, but if my widget is bound to the store variable, is not possible?

**Comment by leonardo-ciandt** [comment]
@Nikhil-Nandagopal Thanks so much!
