### ISSUE TITLE
[Docs] Create a guide on how to embed appsmith into another tool

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2952]
## Describe the problem

We need a how-to guide on embedding appsmith into existing applications. This can be achieved by setting the embed=true parameter in the URL of the page, making the app public and embedding it in an iframe inside the parent application. Access to the application then needs to be controlled by integrating with the parent applications authentication

**Comment by PrathameshAshra** [comment]
Can i Take care of this ? 
I am planning to create a readme doc with the steps.

**Comment by mohanarpit** [comment]
@PrathameshAshra It's all yours! 🎉 

Please don't forget to read the [Docs Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/contributions/docs/CONTRIBUTING.md). Would appreciate it if you can open a PR within the next 2 days.

**Comment by PrathameshAshra** [comment]
Thanks @mohanarpit  Will Update you in next 48 hours.

**Comment by mohanarpit** [comment]
Closing as this is present at: https://docs.appsmith.com/how-to-guides/embed-appsmith-into-existing-application
