### ISSUE TITLE
[Bug]: Preview image for some templates seems to be broken & is different from prod

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The preview image for View/Edit/Update data templates in release is different from prod.
https://www.loom.com/share/b6d4e0ff281142d1a94c40a36841ccb8

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/templates
2. search for View/Update/Edit data templates

**Expected:** The preview image for all the above templates should be appropriate (matching with something we have in prod)

### Environment

Release

### Version

Cloud

**Comment by jacquesikot** [comment]
This is a data problem, and it is an ongoing experiment, that may keep on changing. If you see such changes in the next week, please don’t take them as blockers, we are still testing things there.
