### ISSUE TITLE
[Bug]: Bottom of the REST API response is not reachable with scroll

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#29534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

coming from [here](https://www.notion.so/appsmith/Issues-in-developing-Raven-and-more-ce55b055ac93494f96ae36cd009d3bfd?pvs=4#09b1364caf8c40ed9c29d41d01a53453)
Say you have a long response to your REST API query, such that it is not completely visible in the current viewport. Scrolling through bottoms out before reaching the actual bottom of the response, and it only possible to reach this place with the "down" strokes on the keyboard.

### Steps To Reproduce

1. create a blank API with URL `https://httpbun.com/any'
2. make sure the height of the response window is short, so that you can't see the entire response
3. try to reach the bottom of the response via scrolling, and see that some part of the response is actually still not shown even when the scroll has reached the bottom.

### Environment

Production

### Version

Cloud

**Comment by vaibhavchobisa** [comment]
Hi @Nikhil-Nandagopal, @rohan-arthur 

I can see that the scrollbar is escaping the viewport.
Can you please assign this issue to me? Will fix it ASAP.

**Comment by rohan-arthur** [comment]
@vaibhavchobisa thank you for your interest! Can you describe your solution approach briefly?

**Comment by vaibhavchobisa** [comment]
@rohan-arthur sure!
One of the descendent components of the response view component is causing the issue due to its excessive height. To fix the issue, its height has to be made such that it doesn't cross the viewport.
Assigning its height to something like (ParentHeight - SiblingComponentsHeight) should do the trick.

**Comment by sneha122** [comment]
Thanks a lot @vaibhavchobisa for checking out the issue and thinking of the fix. It looks like it may as well be the case that one of the internal divs has height not configured correctly. Please feel free to go ahead and raise PR for this. Please make sure to check out the [contributing guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md).

**Comment by vaibhavchobisa** [comment]
Thanks @sneha122!
I have resolved the issue but am unable to test it on dev (dev.appsmith.com) as I don't have access to make API calls over dev (I am getting Unauthorized Access error).

**Comment by rohan-arthur** [comment]
@vaibhavchobisa if you're confident of the fix, you can also push it to a PR (check contribution guide for steps) and we can create a deploy preview for you to test it.

**Comment by vaibhavchobisa** [comment]
Hey @rohan-arthur
I have pushed the PR, could you please help me with the deploy preview for testing? Thanks!

**Comment by sneha122** [comment]
@vaibhavchobisa The deploy preview is generated using `/build-deploy-preview skip-tests=true` comment. DP is generated for your PR and available here: https://ce-29830.dp.appsmith.com/

**Comment by vaibhavchobisa** [comment]
Hey @rohan-arthur 
The linked PR has been approved by @sneha122.

**Comment by vaibhavchobisa** [comment]
Hi @rohan-arthur 
Can you please review the PR for merging? Thanks!
