### ISSUE TITLE
[Task]: Create a DP for user testing where onboarding flow is visible for all users

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#29540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The task is to create a DP for user testing where start with data onboarding flow is visible for all users. This DP has been requested by @carinanfonseca so that she can carry out the user testing of this feature seamlessly

**Comment by sneha122** [comment]
Moving it to blocked as no active work is required on this issue, it's only open because DP is required for user testing

**Comment by rohan-arthur** [comment]
@sneha122 I'll close this because Carina has confirmed that the testing is finished.
