### ISSUE TITLE
[Bug] The app tries to trigger an action on page load action even if it is deleted

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2954]
## Description
The app tries to trigger an action on page load action even if it is deleted

### Steps to reproduce the behaviour:
1. create an api
2. set it to run on page load
3. delete the api
4. reload the page, we get an error toast as `unable to find action`

**Comment by trishaanand** [comment]
Demoting this from Critical because this is an edge case scenario. If any update of action/page happens, the page would resume back to being in a good state.

**Comment by Nikhil-Nandagopal** [comment]
This seems to be working now
