### ISSUE TITLE
[Bug]: Recent and multiple caddy changes in Docker breaks appsmith 

### ISSUE THREAD

**Issue by mewhomaker** [appsmithorg/appsmith#29596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Appsmith automatically updated to the latest version using the autoupdate and appsmith docker stack goes into a restart loop.
The UI is not accessible at all.
Here are the relevant logs - seems related to caddy port bindings
2023-12-13 22:57:43,161 INFO exited: editor (exit status 1; not expected)
2023-12-13 22:57:43,164 INFO spawned: 'editor' with pid 191447
2023-12-13 22:57:43,169 INFO success: editor entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
editor stdout | Load environment configuration
editor stdout | 
editor stdout | /tmp/appsmith/www /opt/appsmith
editor stdout | 
editor stdout | /opt/appsmith
editor stdout | 
editor stderr | {"level":"info","ts":1702508264.1925185,"msg":"using provided configuration","config_file":"/tmp/appsmith/Caddyfile","config_adapter":""}
editor stderr | 
editor stderr | Error: couldn't determine admin API address: adapting config using caddyfile: server listening on [:80] is HTTP, but attempts to configure TLS connection policies
editor stderr | 
editor stderr | {"level":"info","ts":1702508264.4619856,"msg":"using provided configuration","config_file":"/tmp/appsmith/Caddyfile","config_adapter":""}
editor stderr | 
editor stderr | Error: adapting config using caddyfile: server listening on [:80] is HTTP, but attempts to configure TLS connection policies
editor stderr | 
2023-12-13 22:57:45,477 INFO exited: editor (exit status 1; not expected)
2023-12-13 22:57:45,494 INFO spawned: 'editor' with pid 191497
2023-12-13 22:57:45,547 INFO success: editor entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

### Steps To Reproduce

Just autoupdate or manually update docker version to latest version or even a couple of versions back.

### Environment

Production

### Version

Self Hosted v1.9.56

**Comment by mewhomaker** [comment]
I even downgraded to v1.9.50 - the UI showed up but Appsmith keeps crashing and restarting.
Note - I do NOT exclusively use this server for Appsmith and instead have another caddy container getting the SSL certs etc.
It is the simplest caddy config which just proxies Appsmith

https://appsmith.mydomain.com {
    reverse_proxy http://host.docker.internal:8080
}

The name host.docker.internal is just the docker host defined in docker-compose.yml as
    extra_hosts:
      - "host.docker.internal:host-gateway"

This arrangement has been working for a year plus but now the recent changes have broken it all.

Thanks

**Comment by harsh3195** [comment]
Facing this same issue. The latest release is not showing anything on the UI

**Comment by sharat87** [comment]
Hey @mewhomaker, sorry for the trouble faced here. From what I see, I think you have `APPSMITH_CUSTOM_DOMAIN` set in your configuration. If yes, can you please comment it out and restart Appsmith?

As a user of Caddy already, you can probably tell that Caddy's handling of TLS is quite stable and smooth. This was the reason we switched from NGINX to Caddy. However, in our previous NGINX stack, we had a fallback where if cert provisioning fails, we fallback to HTTP. Looks like Caddy is not doing that fallback correctly. I'm working on bringing that fallback with Caddy as well, and that fix is going through QA now.

If you have a separate reverse-proxy in front of Appsmith, like Caddy, or NGINX ,or anything else, you don't need the `APPSMITH_CUSTOM_DOMAIN` set.

**Comment by mewhomaker** [comment]
@sharat87 Thanks for checking into this.
As of now Appsmith is still down.
APPSMITH_CUSTOM_DOMAIN is not set - any other suggestions - we are dead in the water for over 24 hours now.

<img width="302" alt="image" src="https://github.com/appsmithorg/appsmith/assets/65513219/ccfb5d2f-b654-4f77-9641-a13c65bbcb11">

Thanks for your help

**Comment by mewhomaker** [comment]
Update - I have added all kinds of values to APPSMITH_CUSTOM_DOMAIN  like

1. appsmith.mydomain.com:80
2. appsmith.mydomain.com:443
3. Left it blank
Nothing works 

@sharat87 - Where can I modify the caddy file (my past experience with caddy and docker took days to nail down so I would suggest reverting the change for now as getting it fully right for all scenarios will take time

Thank you

**Comment by sharat87** [comment]
Hey @mewhomaker, sorry for the trouble. Can we get on a call to troubleshoot. Let me know a time you'll be available and we'll get on a call. Or find some time at https://cal.com/shrismith/i29596. Either is fine.

**Comment by sharat87** [comment]
Thank you @mewhomaker for the conversation. I've identified the edge case causing your instance's Caddy to not come up. I'll pick this up first thing tomorrow.

Reg. backend going into a crash loop, as discussed, please scale your server with higher capacity and try again. The minimum we recommend for running just Appsmith and nothing else is 2 vCPUs and 4GB of memory. Since you have other services also running, please consider scaling up.

If you still have trouble on the new server as well, please feel free to book another time on the same link above. I'll keep that link and this issue open for the time being.

Thanks again, and happy holidays!

**Comment by sharat87** [comment]
Thanks for confirming @mewhomaker. I'll close this issue in that case. Please reach out again if you face any trouble.
