### ISSUE TITLE
[Task]: When user clicks on create new query, it should use the entity selected in the schema preview to create template query

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#29600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

from [here](https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=7e38744c80234346b880979f28e45d38&pm=s)

This behaviour should apply only to: postgres, mysql, gsheets and moviesdb. For the rest of the plugins, the default query can continue to be a random table (the first one from getstructure call)

**Comment by sneha122** [comment]
Moving this back to product backlog as other priority items have come up, I have committed the in progress code in this branch `feat/default-new-query`
