### ISSUE TITLE
[Bug] The default height of the canvas is larger than the screen area

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2962]
## Description

A user has a single table on the screen but the canvas has a large scroll area below it

**Comment by riodeuno** [comment]
Note:
When we save the DSL, we save it with the canvas height being one row more than the bottom of the lowest widget. This way the deployed page will not scroll if the user doesn't put a widget too far below. And when we render the canvas, we use `max(dslbottom, viewportbottom)` so editing experience doesn't suffer.
