### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by novembersky** [appsmithorg/appsmith#29638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I pass SQL statements in the API interface, which contain parameter variables. The first parameter can be parsed normally, and the second parameter will become a~symbol. I have tested it multiple times (such as swapping parameter order), and this is true. So I suspect this is a bug.
![企业微信截图_17024462041894](https://github.com/appsmithorg/appsmith/assets/2901717/196bfb47-4178-48d8-b6d2-eb0feed02637)

![企业微信截图_17024462403168](https://github.com/appsmithorg/appsmith/assets/2901717/56e1f62e-83de-4a10-927d-060257c0a2ba)
![企业微信截图_17024462584183](https://github.com/appsmithorg/appsmith/assets/2901717/a99beb7b-cbf9-46d3-a284-2b099b3a19fa)
![企业微信截图_17024462781222](https://github.com/appsmithorg/appsmith/assets/2901717/57f47417-4bd6-446f-a942-d66c6428220f)

### Steps To Reproduce

![企业微信截图_17024462403168](https://github.com/appsmithorg/appsmith/assets/2901717/0c6a1c0a-9bdb-43f3-99b7-f255516d571b)
![企业微信截图_17024462584183](https://github.com/appsmithorg/appsmith/assets/2901717/4dbf0529-032a-442f-8b0a-abe8ab9a0caa)

### Environment

Production

### Version

Self host

**Comment by Nikhil-Nandagopal** [comment]
@novembersky can you try adding it directly in the params tab? It should work there

**Comment by novembersky** [comment]
> @novembersky can you try adding it directly in the params tab? It should work there

Yes, it works。Think you
