### ISSUE TITLE
[Bug]: Widget image broken in Templates overview page

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The image for certain widgets is broken inside the template overview page.
<img width="483" alt="Screenshot 2023-12-15 at 11 57 51 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/d5d882a7-bb71-4ef4-8f94-fc274666ae0f">
<img width="268" alt="Screenshot 2023-12-15 at 11 58 01 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/ab5ae421-af13-4f57-91b8-3fb216261706">

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/
2. Go to the templates page & click on any template.
3. In the overview page scroll down to the widgets section

**Expected:** The widget images should not be broken

### Environment

Release

### Version

Cloud

**Comment by jacquesikot** [comment]
The issue was caused by an outdated entry for the List widget icon. The current entry was LIST_WIDGET, I updated it to LIST_WIDGET_V2 to fix the issue in all release templates.
