### ISSUE TITLE
[Bug]: GSheet integration is throwing error in when added via Package

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#29658]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Slack conversation-->https://theappsmith.slack.com/archives/C04GRCN4CS3/p1702459350590329
Associated link to bug-->
https://docs.google.com/spreadsheets/d/1zZX8wrnBvfNaQltCMFBq8s0_I3frxti7RKEflMxHrWQ/edit#gid=0&range=14:14

### Steps To Reproduce

Try to add Gsheet DS via package .

### Environment

Release

### Version

Cloud/Release

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by pedro-santos-rodrigues** [comment]
This issue seems the same of [https://github.com/appsmithorg/appsmith/issues/29324](https://github.com/appsmithorg/appsmith/issues/29324)
