### ISSUE TITLE
[Bug] Run API on Page load configuration does not get duplicated when the application is duplicated 

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2969]
## Description
1. Create a new API
2. Set it to `run on page load` from the settings tab
3. Go to the applications page and duplicate the app
4. Check the API settings within the duplicated application, `run on page load` value it not set the same

**Comment by sumitsum** [comment]
@trishaanand assigning it to myself as per today's action pod meeting.
