### ISSUE TITLE
[Task]: Update blank and add states

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#29696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Current blank and app states are not working out in terms of guiding the user to the correct place. Needs a new design 

- Datasource List
- Query List
- UI List

**Comment by momcilo-appsmith** [comment]
@hetunandu can you start working with the sketches here? 
https://www.figma.com/file/DDP4RXK4YOTEJnuC8ocm47/IDE-Exploration?type=design&node-id=8536-42274&mode=design&t=xG51N6oDzXbuGK7Q-4

I owe you some icons, and copy edits.
