### ISSUE TITLE
[Feature]: Access to DOM object for getting referrer.

### ISSUE THREAD

**Issue by asingh072318** [appsmithorg/appsmith#29709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Need a way to get referrer information from DOM object.

### Why should this be worked on?

It is crucial to get referrer information in order to identify customers for our use case.

**Comment by Nikhil-Nandagopal** [comment]
@asingh072318 accessing the dom object is a potential security risk which is why we don't enable direct access to it. Can you explain the type of application you are building and why the referrer information is in the DOM?
