### ISSUE TITLE
[Feature] Allow removing time input from the date picker

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#2971]
## Summary
Allow remove time input from the date picker

## Motivation
Currently, there isn't an option to hide the time input which might be confusing to end users

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #1579

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal How do you remember duplicates?! Pretty impressive memory for issues!

**Comment by Nikhil-Nandagopal** [comment]
I usually just think if I'm surprised by the issue then it's probably something we haven't filed. If I'm not then I do a quick search using the keywords to find the related issue :)
