### ISSUE TITLE
[Bug]: clearInterval() does not work as expected

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#29725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Setting clearInterval with some id stops executing the wrong Interval.

### Steps To Reproduce

1. Go to an app & create a JS object.
2. Set an interval `Interval1` such that `setInterval(() => {showAlert('What?', 'success')}, 2000, 'Interval1')`.
3. Now in `async myFun2 ()` clear the interval with a different id such as `clearInterval('Interval2')`.

**Expected:** As the id mentioned in the `clearInterval` is different from the one that is being set, `Interval1` should not be stopped.
**Actual:** Wrong interval (Interval1) is being stopped.

### Environment

Production

### Issue video log

https://www.loom.com/share/8532ced9b1e746feab5148353e98bfa8

### Version

Cloud

**Comment by vaibhavchobisa** [comment]
Hi @satbir121 
I would love to work on this, can you please assign this to me?

**Comment by satbir121** [comment]
Hi @vaibhavchobisa! Thanks for offering help here. Please follow these [contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md). This issue has high priority, so turnaround time also needs to be low. If, due to some constraints, you are not able to create a PR with test cases by Thursday, someone from the internal team will have to take it up. 

Again, thanks for taking this up! Looking forward to your contribution.

**Comment by vaibhavchobisa** [comment]
Hey @satbir121! I have fixed the issue, just need to add test cases. I will push a PR before the first half.

**Comment by vaibhavchobisa** [comment]
Hey @satbir121 

I have raised the PR along with the test cases.

Some observations:
1. While setInterval does return a default number ID, when the user chooses to pass a value inside the third 'custom' id parameter, they can then use clearInterval ONLY on the set custom ID. This might be confusing for programmers who are habitual in using clearInterval using the default ID number returned by setInterval.
2. Documentation of setInterval says that the id parameter allows only for 'string' values, but the programming logic allows for both 'string' and 'number' values.
3. clearAllIntervals method has been defined in the code, but we haven't provided the functionality to the user to use it in our web app. Should we add this functionality for the user?

**Comment by satbir121** [comment]
Thanks @vaibhavchobisa for a quick turnaround.

@arunvjn Can you please look at the [PR](https://github.com/appsmithorg/appsmith/pull/29805)?
