### ISSUE TITLE
[Bug] S3 Plugin: Add encrypted tag to the secret key

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#2972]
## Description

It is not apparent that the AWS Secret key is encrypted when filling out the datasource form. Refer to MySQL & PostgreSQL plugins for the UI.

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by sumitsum** [comment]
Fixed - PR #2979
