### ISSUE TITLE
[Bug]: Oracle Stored Procedure Error (a-force)

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#29752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is trying to run a stored procedure on Oracle, but gets the error SQL command not properly ended , when using the [modified syntax from our docs](https://docs.appsmith.com/connect-data/concepts/returning-data-from-a-stored-procedure) (see screenshot 1). The only way to get it to execute is with the begin and end sections (see screenshot 2). How can they make Appsmith's response show the output variables instead of the ‘affectedRows’?

Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1701770043308369

### Steps To Reproduce

Ref: https://theappsmith.slack.com/archives/C0341RERY4R/p1701770043308369

### Environment

Production

### Version

v1.9.36-SNAPSHOT

**Comment by NilanshBansal** [comment]
Needs a documentation update on how to create and run procedures in appsmith using MySQL, Postgres and Oracle DBs.
Started a thread [here](https://theappsmith.slack.com/archives/C040LHZN03V/p1703069218122229).

**Comment by rohan-arthur** [comment]
haven't heard back from the use, closing issue meanwhile
