### ISSUE TITLE
[Task]: Add null check for applicationId in URL params

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#29761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

When you are on an App editor and you hard refresh the page, you start seeing this type error -> TypeError: Cannot read properties of undefined (reading ‘applicationId’).
<img width="1017" alt="image" src="https://github.com/appsmithorg/appsmith/assets/28362912/ac959f60-16ec-47ef-bcb9-622499a4b0e7">

Slack Thread: https://theappsmith.slack.com/archives/CPG2ZTXEY/p1703064982422089

**Comment by paridhisharma24** [comment]
can I work on this

**Comment by hetunandu** [comment]
Already fixed
