### ISSUE TITLE
[Bug]: Users are getting errors when saving changes - `'Internal server error while processing request'`

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#29776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We've seen multiple users complain about users being unable to save the changes. 

### Steps To Reproduce

Internal Convo - https://theappsmith.slack.com/archives/CGBPVEJ5C/p1703091470645489

### Environment

Production

### Version

v1.9.57

**Comment by rajatagrawal** [comment]
The erroneous piece of code related to capturing telemetry has been reverted. 500 errors are not happening anymore.
