### ISSUE TITLE
[Bug]: import_db and restore (from two different instances) fail

### ISSUE THREAD

**Issue by faif** [appsmithorg/appsmith#29781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When importing the database, I expect no errors, instead I'm getting the following:

```shell
root@machine:/appsmith-stacks/data# appsmithctl import_db
Importing database
stop backend & rts application before import database
backend: stopped
rts: stopped
uncaught exception: Error: listCollections failed: {
        "ok" : 0,
        "errmsg" : "command listCollections requires authentication",
        "code" : 13,
        "codeName" : "Unauthorized",
        "$clusterTime" : {
                "clusterTime" : Timestamp(1703151667, 1),
                "signature" : {
                        "hash" : BinData(0,"kxHjBz3enS5cw9uPkFUmJupnEWc="),
                        "keyId" : NumberLong("7314662134988668933")
                }
        },
        "operationTime" : Timestamp(1703151667, 1)
} :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype._getCollectionInfosCommand@src/mongo/shell/db.js:723:15
DB.prototype._getCollectionNamesInternal@src/mongo/shell/db.js:795:12
DB.prototype.getCollectionNames@src/mongo/shell/db.js:804:12
@(shell eval):1:1
exiting with code -4
import_database  ....
2023-12-21T09:41:15.209+0000    error parsing command line options: error parsing uri: scheme must be "mongodb" or "mongodb+srv"
2023-12-21T09:41:15.209+0000    try 'mongorestore --help' for more information
import_database done
start backend & rts application after import database
backend: started
rts: started
``` 

I also see a similar error when performing a `appsmitchctl restore`:
```shell
Extracting the Appsmith backup archive at /appsmith-stacks/data/backup/appsmith-backup-2023-12-21T00-00-00.726Z.tar.gz
Extracting the backup archive completed
Current Appsmith Version: v1.9.57
Restore Appsmith Version: v1.9.57
The restore instance is compatible with the current appsmith version
****************************************************************
Restoring Appsmith instance from the backup at /appsmith-stacks/data/backup/appsmith-backup-2023-12-21T00-00-00.726Z.tar.gz
Stopping backend rts
backend: stopped
rts: stopped
Stopped backend rts
Restoring database  ....
2023-12-21T09:55:39.443+0000    error parsing command line options: error parsing uri: scheme must be "mongodb" or "mongodb+srv"
2023-12-21T09:55:39.443+0000    try 'mongorestore --help' for more information
undefined
Starting backend rts
backend: started
rts: started
Started backend rts
```

### Steps To Reproduce

1. Export the database from an instance running appsmith (in this case version 1.9.57) using `appsmithctl export_db`
2. Copy the exported file (`appsmith-data.archive`) to another instance in `/appsmith-stacks/data`
3. Import the database to another instance running appsmith (same version) using `appsmithctl import_db`

Similar for `appsmithctl restore`. I confirm that `APPSMITH_ENCRYPTION_PASSWORD` and `APPSMITH_ENCRYPTION_SALT` have the right values

### Environment

Deploy Preview

### Version

1.9.57

**Comment by Nikhil-Nandagopal** [comment]
@faif but is your instance successfully getting restored?

**Comment by faif** [comment]
No it's not, it's in an incomplete state with many 404s and an unreadable message:
![image](https://github.com/appsmithorg/appsmith/assets/1304661/cc6d30a2-d9eb-47c8-abe1-77bcc659ddbb)

**Comment by faif** [comment]
Is it the case that restoring an instance also restores `docker.env`? I wouldn't expect that, since the documentation clearly states that this shouldn't be the case, that's why you need to provide the `*ENCRYPTION` info interactively when restoring

**Comment by sharat87** [comment]
@faif, sorry for the trouble you're seeing here. In the output of `import_db` command, it looks like the credentials used for MongoDB don't have all the necessary permissions. Can you give admin access to those credentials and retry please?

I'm suspecting it's the same problem with `restore` as well, and if yes, we'll see if we can improve the error message reporting there.

**Comment by faif** [comment]
Hi,

I've retried and it worked as expected. Not sure what went wrong the first time, but closing this
