### ISSUE TITLE
[Feature]: Customisable page URLs

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#29793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The customer wants to customize the page URLs so that they remain statics when the user deploys an app to different instances.

### Why should this be worked on?

This customer uses Appsmith to embed it in their production tool. Every time they deploy on a different instance, they have to go to the config and change the embedded page URLs. This is a very laborious manual task as they have 20+ embedded pages for a single tool.

**Comment by Nikhil-Nandagopal** [comment]
@pranavkanade now you can import on the same app and the URL won';t change. Also you can use git to avoid the URL changing

**Comment by pranavkanade** [comment]
I'll give it a try
