### ISSUE TITLE
[Bug] postgres template missing

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2980]
<b style="color:red">yellowCJ</b><br/>I see this exception when I've  logged in and tried to open the template. Does anyone know where this is coming from. It is postgre plugin. Can anyone help?</b><br/><br/><br/><b style="color:red">areyabhishek</b><br/><@!542230157419872276> could you give me more information about your account? Is this on a self-hosted environment or the cloud environment? Is this happening for all query templates or just one of them?</b><br/><br/><br/><b style="color:red">yellowCJ</b><br/>Thank you so much. I deleted the local mongoDB directory and redeployed. It works.</b><br/>

**Comment by mohanarpit** [comment]
From the conversation, it seems like this is an issue when running the code via IntelliJ IDE. The IDE doesn't pick up the plugins automatically. It requires extra settings in order to get everything to run smoothly.

**Comment by Nikhil-Nandagopal** [comment]
Closing coz this was just a test of Jarvis :)
