### ISSUE TITLE
[Bug]: Date column doesn't sort correctly when using timestamps

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#29800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I sort a Date column in my table and my dates are unix timestamps, the dates aren't in the expected order.

![image](https://github.com/appsmithorg/appsmith/assets/6085143/c6d26ca6-f014-4941-b86c-b31fb6856a40)

I expect them to be sorted by date.

### Steps To Reproduce

1. Drag a new table widget and populate it with the following test data: 
```js
{{[
  { guid: 'abc123', createdAt: 1678886400 },
  { guid: 'def456', createdAt: 1747968000 },
  { guid: 'ghi789', createdAt: 1646582400 },
  { guid: 'jkl012', createdAt: 1668806400 },
  { guid: 'mno345', createdAt: 1677840000 },
  { guid: 'pqr678', createdAt: 1649670400 },
  { guid: 'stu901', createdAt: 1683552000 },
  { guid: 'vwx234', createdAt: 1642137600 },
  { guid: 'yzab567', createdAt: 1661740800 },
  { guid: 'cde890', createdAt: 1670563200 }
]}}
```
2. Edit the column settings for the `createdAt` column:
	a. Set the `Date format` to `UNIX timestamp (s)`
	b. Set the `Display format` to anything you like. I used MM/DD/YYYY.
3. Sort the `createdAt` column in any order.
4. Observe that the rows are not in the correct order.

### Public Sample App

https://app.appsmith.com/app/unix-dates-don-t-sort/example-65899eefd9bd957e06b80ece

### Environment

Production

### Version

Cloud - 1.9.58-SNAPSHOT

**Comment by paridhisharma24** [comment]
canI work on this?

**Comment by Nikhil-Nandagopal** [comment]
@paridhisharma24 sure you can go for it. It should be an issue with the Table Widgets Sort functionality
