### ISSUE TITLE
[Bug]: [Intermittent] Returning to hompage from an app is entering the bulk delete mode

### ISSUE THREAD

**Issue by deepikaappsmith** [appsmithorg/appsmith#29833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user uses the browser’s back button to go from an app to /applications page it puts users to bulk delete mode i.e. 1st app starts to wiggle and the Delete button in the top right corner is seen.
![Screenshot 2023-12-02 at 2 16 58 PM](https://github.com/appsmithorg/appsmith/assets/130959931/f1013977-526a-4d74-a387-555c4ebcda3c)

### Steps To Reproduce

There are no concrete steps to reproduce, as it is an intermittent issue.

### Environment

Production

### Version

Cloud v1.9.58-SNAPSHOT

**Comment by deepika-appsmith** [comment]
now that we have removed this functionality this issue isn't valid. Hence closing the ticket.
