### ISSUE TITLE
Remove custom js libs from git commit when it's not edited

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#29835]
After a major refactor, we've ended up in a case where custom js libs are written to file for every git operation. This can lead to serious performance issue when the application has couple of js libs. 

We should write the JS lib to file only when there's a change.

**Comment by riteshkew** [comment]
@nidhi-nair @sondermanish Can you confirm if this would be still relevant post Git DSL cleanup

**Comment by riteshkew** [comment]
Resolved as part of auto-commit
