### ISSUE TITLE
graph api worked and now it doesn't [Bug]: 

### ISSUE THREAD

**Issue by zoldanOS** [appsmithorg/appsmith#29840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I run API to linear, it worked, it works in postman, and stop work on your side. When I click run it just upload for ever. Please contact me ASAP

### Steps To Reproduce

1. go to the app
2. try to run the api of linear
3. 3. it keep saving and saving and running and running

### Environment

Production

### Version

Self-Hosted -1.6.6

**Comment by zoldanOS** [comment]
Its not saving changes in the api call.

**Comment by Nikhil-Nandagopal** [comment]
@zoldanOS it seems you are on a very old version of Appmith and it may have already been fixed on a newer version. Could you try upgrading to the latest version and see if it still persists?
If it still persists, can you share the CURL of the API that is not working?

**Comment by zoldanOS** [comment]
Thanks Nikhil!
lets see
+Engineering Team ***@***.***> can someone help me here?

**Comment by Nikhil-Nandagopal** [comment]
Hello! We haven't heard back from you in a while so I'm closing this isse. Feel free to re-open it if it's not solved.
