### ISSUE TITLE
[Bug]: Fields Misplaced When Inserting New Row in Google Sheets That Contains an Empty Column

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#29889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Google Sheets, if we have an empty column and insert a new row, the fields of the new row get shifted after the empty column.

![image](https://github.com/appsmithorg/appsmith/assets/101268423/4290bcac-b7ad-447e-9766-9706826a699a)
![image](https://github.com/appsmithorg/appsmith/assets/101268423/4e2e7891-2873-402e-822d-fbd33c998dbc)

It gets inserted correctly if we delete the empty column or add a header to it. So the workaround is to use a header such as `_` if we want to keep the empty column.

### Steps To Reproduce

1. Connect to a Google Sheets Datasource.
2. Make sure you use a sheet that contains an empty column.
3. Create a query that inserts a new row into the sheet.
4. Note that the fields are not getting inserted correctly.

### Environment

Production

### Version

v1.9.58

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_44ttvw)

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith This is not a bug and actually expected for Google Sheets that there are no gaps in the columns.
