### ISSUE TITLE
[Task]: Upload client build's source map to s3 bucket

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#29885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The source maps are required for debugging performance profiles shared by users. Without the source maps, the performance profiles contain obfuscated info about the stack trace. Source maps de obfuscated the stack trace and add actual function names.

The source maps are generated when a client build is made.

Suggested solution:
1. The source maps can be uploaded to s3 bucket whenever a build is tagged or code is merged to master.
2. The source maps would need to be annotated with workflow run ids in the s3 bucket.
3. The source maps are deleted at the moment [here](https://theappsmith.slack.com/archives/C02MUD8DNUR/p1703595851064469?thread_ts=1703593101.905399&cid=C02MUD8DNUR)
4. We can decide to not delete the source maps at the step mentioned above and instead add it to client build workflow. The steps are mentioned [here](https://theappsmith.slack.com/archives/C02MUD8DNUR/p1703658870402449?thread_ts=1703593101.905399&cid=C02MUD8DNUR).
5. The upload script should delete source maps in the s3 bucket older than 6 months.

**Comment by sumitsum** [comment]
Closing because team has decided to add source map to production build.
