### ISSUE TITLE
[Feature] Add fields to user management

### ISSUE THREAD

**Issue by hawisizu** [appsmithorg/appsmith#2989]
## Summary

Add fiels to user management system. 

Typically, firstname and lastname. 
Super simple version: these fields are accessible in the "invite" form, as well as in the "manage user" screen
the info of these fields can be retrieved from `{{ appsmith.user.firstname }}` and `{{ appsmith.user.lastname }}` exactly as email now. 

more advanced: have a user page where users can edit these fields, as well as likely change their password and stuff, but this isn't needed for me at the moment 

## Motivation

This would allow a better user management

**Comment by Nikhil-Nandagopal** [comment]
@hawisizu we'll be picking this feature up along with options to reset password this week

**Comment by Nikhil-Nandagopal** [comment]
These are the designs!
https://www.figma.com/file/Q1ZcMVxghtZcKtWY5zpqLp/Profile-Page?node-id=3%3A261
