### ISSUE TITLE
[Task]: Integrate NewRelic by default in docker images which can be enabled by setting relevant environment variables

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#29892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Having new relic integration by default in self hosted instances will help to monitor its system health on demand.

We should be able to share a license key for new relic with customers on demand. A new license key should be generated for every customer on demand and shared with them. Once the monitoring needs to stop, we can delete the license key from new relic console.

Self hosted customers should be able to report new relic data to our account by these environment variables.
1. APPSMITH_ENABLE_NEW_RELIC_LOGGING=TRUE
2. APPSMITH_NEW_RELIC_LICENSE_KEY=<provided on demand by customer support. This key is generated by us manually on demand. It can be deleted on demand as well>
3. APPSMITH_NEW_RELIC_APP_NAME=<provided on demand by customer support>

When the monitoring needs to be stopped, we can either request the customer to disable the environment variables or we can delete the license key that was generated for this customer specifically.

**Comment by sumitsum** [comment]
Possible duplicate #28857
