### ISSUE TITLE
Appsmith currently has a very vanilla version of JSON Forms.  After reading up a little on JSON Forms documentation I'm hoping a more robust support for JSON Forms might be implemented and/or enabled with the upcoming Custom Widgets implementation

### ISSUE THREAD

**Issue by pchambless** [appsmithorg/appsmith#29908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

JSON Forms for Vue / React allows for highly configurable forms with horizontal placement of fields, grouping of fields, data validation and more.  

### Why should this be worked on?

I have several JSON Forms in my Apps.  I love that you don't have to generate a bunch of Input widgets and the Queries to update/insert are way more straightforward.  However, forms with numerous fields get very tedious to work through.  The ability to place like data on a single row (i.e. Address, City, State, Zip) or (First Name, Last Name, Birthdate) would be very nice!  If I need to save space, as I frequently do, I have to go to the Form widget which offers much more flexibility in formatting, but is much more tedious to write queries for.  Thanks for your consideration.

**Comment by Nikhil-Nandagopal** [comment]
@pchambless are you referring to this widget?
https://jsonforms.io/

**Comment by Nikhil-Nandagopal** [comment]
This issue is tracked here #12995 I'm closing this for now. Let me know if it's any different
