### ISSUE TITLE
[Feature]: Expose onClick() from buttons or onSubmit() from form

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#29905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

onClick() method for buttons than when run, runs the same action as clicking them, onSubmit() method on forms that runs whatever action is assigned on that form, and/or an 'on submit' event listener on the form that listens for submits for any of the fields in the form.

### Why should this be worked on?

Right now, when setting up a form, I need to code the onSubmit for each field or at least the last field in case the user just hits enter, and then also code the onClick for the submit button.  If this changes I have to remember to change it for each field.   As a workaround, I can have each of the fields reference a jsObject, for example instead of each one of them running codeJS.get(parameters) I could have them reference helperJS.submit() which in turn runs codeJS.get(paremeters) but this seems clunky and at odds with the direction Appsmith is moving in.

Instead, I should be able to run submitButton.onClick() or form.onSubmit() or container.onSubmit() in order to key all of my fields into the same option.

OR have the form have an onSubmit even that listens to ALL of the fields inside the form.

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS actually the JSObject would be the right way to do this, I'm not sure why you think it's at odds with our product direction because in code, abstracting logic inside a function seems like the right thing to do as opposed to allowing spoofing a onClick trigger from another field.

**Comment by eedwardsSGS** [comment]
Because of your new(ish) JS setter methods.  Prior to the setters if you wanted a changeable default or setting it was common to use jsObject.string and bind that on the widget, then if you wanted to change the widget, you'd just jsObject.string = 'whateverTheNewThingIs'.

This still works, but with the push of the setters the more-documented way of resolving this is having (for example) the button's color be '#FF0011' and then using button.setColor('#FF0000').

And I think for the common audience this is intuitive, you're taking an action on X widget, instead of having the widget reference this other thing that you take action on.

As we both have said, this isn't necessary at all, but this does appear to be the path the setter methods imply.

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS I agree that the setters are useful and intuitive for most programmers. However, I think there's a misunderstanding that onClick and onSubmit are functions that can trigger a click. They are actually event listeners that fire the function passed to them. So if you configure the onClick event handler for a button, to show an alert, it's the code equivalent of  `button.onClick(() => showAlert('alert'))`
So this wouldn't trigger a click, it would set the event handler to run when the button is clicked. 
Something like `button.click()` is also uncommon in coding frameworks because it simulates a UI event and forcefully triggers the event handler.

**Comment by eedwardsSGS** [comment]
@Nikhil-Nandagopal - Okay, how about from another angle: buttons have a "form settings" on them that is "disabled invalid forms" (possibly should be 'disabled ON invalid forms'?) and 'reset form on success'.  If you turn them on, then you also want the onClick for that button to not be something that resets the form because you're handling that with a toggle.

Now users are used to being able to hit "enter" in some fields to trigger submissions of forms (where it is intuitive from the UX/UI) so in order to enable that you give the onSubmit for the input field to trigger a similar function as the submit button, but now need to manually handle resetting the form.  So you make a function that runs the same function as the submit button, but is wrapped with a reset on success.

It just feels very inconsistent in the way Appsmith currently expects this to be handled.  Perhaps the feature / event listener should be listening at the form level, and checking for submits from anywhere in the form (which still wouldn't be quite right because the onClick of the button isn't a submit).  Forms are really important for key Appsmith uses, app users will interact with them over and over, so the method by which they are deployed should make a good user experience the "default" or "easy" way to deploy them.  Tab progression and resetting to the correct field upon submit are parts of this in a different feature request, but a simple way of being consistent about what happens when you submit, no matter where in the form you are submitting (hitting enter on a certain field, clicking on a button, etc) I feel is important.

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS I think the real issue you are trying to solve is having enter in an input trigger the onSubmit which makes sense to me. I understand your point and I'll consider it but right now this won't be a priority for us in the near future
