### ISSUE TITLE
[Bug]: The gsheet authentication fails when user does partial import and export

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#29915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The gsheet authentication fails when user does partial import and export

### Steps To Reproduce

1. Go to release.app.appsmith.com
2. Open the application which has the Gsheet Crud page
3. Now go the page inside the app which has Gsheet crud
4. Now click on that page and open the 3 dot meat ball icon and click on export now inside the modal select all datasource , widgets and queries
5. now once the page is exported 
6. create a new workspace and a app now try to import that part in the new app 
7. the app gets imported and try to authenticate the GSheet 
8. the user will be navigated to` {"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}`

### Environment

Release

### Version

v1.9.58

**Comment by rahulbarwal** [comment]
@AnaghHegde Please take a look at this. 
ON the new workspace, when we try to `Save and Authorize`, we get a success modal(for a split second) 
and we are redirected to https://release-cs.appsmith.com/api/v1/integrations/oauth/authorize?appsmithToken=undefined

and get response as stated in description.

**Comment by AnaghHegde** [comment]
@rahulbarwal This is architecture issue. Whenever a new Datasource is created client sends the default value as a part of the payload. 
During the import flow by file or git, what happens is that we send the list of the newly created datasources to client along with the other data to show this on a reconnected modal. Once the modal is opened, the client calls the update API with default value for each datasource via the default value. Doing the same would solve the current issue as well.
