### ISSUE TITLE
[Feature]: Quiz widget

### ISSUE THREAD

**Issue by izac3d** [appsmithorg/appsmith#29935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Instead of creating quiz with different widgets manually and design each page for that, A quiz widget can be feed with questions and questions types for example like: choices, writing, drawing . This widget should manage timer , compare with correct answers and pass test/quiz result data 

### Why should this be worked on?

It will make creating quizzes and questions very easily instead of designing each page for that

**Comment by Nikhil-Nandagopal** [comment]
@izac3d thank you for the feature request. However a quiz widget does not align with our vision of improving the way internal software is built. You can still achieve this via our custom widget and export / share it with the community however we won't build this as a native part of the platform.
