### ISSUE TITLE
[Feature]: Widget for drawing like windows paint and other users see the drawing in real time

### ISSUE THREAD

**Issue by izac3d** [appsmithorg/appsmith#29934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Draw lines, arrows with different colors and thickness. also highlight important notes. Then this drawing can be stores in db  and printed as pdf.

### Why should this be worked on?

Drawing for illustration can be used in software that mange meetings or for education. User can draw over a background image, and other users see the drawing in real time in addition it can be used to collect signature

**Comment by Nikhil-Nandagopal** [comment]
@izac3d thank you for the feature request. This looks similar to #28699 so I'm closing this in favor of that. Feel free to leave a comment there in support of the feature
