### ISSUE TITLE
[Feature]: Which product does appsmith-ee use for its workflow engine?

### ISSUE THREAD

**Issue by zhouzhou19950825** [appsmithorg/appsmith#29949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello
Which product does appsmith-ee use for its workflow engine?
Thanks!

### Why should this be worked on?

Which product does appsmith-ee use for its workflow engine?

**Comment by Nikhil-Nandagopal** [comment]
Hi @zhouzhou19950825 is there a specific reason why you are asking for this?
