### ISSUE TITLE
[Task]: Page Switcher

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#29955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Visual Requirements

- Animate slide down the panel to reveal the list of pages
- Show the list of pages

https://github.com/appsmithorg/appsmith/assets/12022471/3283a2ea-f53f-409e-ab52-810afaf9374f

### Functional Requirements

- Have a state controlled by the Top Bar trigger.
- Adding new pages and navigating to it
- Re order the pages via drag
- Switch pages on click
- On switch, restore the context of the  destination page

**Comment by rohan-arthur** [comment]
@albinAppsmith what's the estimate?
