### ISSUE TITLE
[Bug]: Appsmith store should show lint error when reassinged or mutated

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#29969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Store value does not change value when mutated or using push function which either needs to be handled by a lint error or enable the functionality

### Steps To Reproduce

https://theappsmith.slack.com/archives/C0341RERY4R/p1704169992778679?thread_ts=1703873472.896449&cid=C0341RERY4R

### Environment

Production

### Version

Cloud

**Comment by rishabhrathod01** [comment]
@ramsaptami store value would remain immutable and hence we show go-ahead to show lint error when using push or assigning the value. I will change the title of the task accordingly.
