### ISSUE TITLE
[Bug] Editing page name in entity explorer navigates the user to the page

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2997]
1. I'm on page 1.
2. I try to edit the name of page 2. Instead of staying on the page I was on, I get navigated to the page because it registers the click to edit the name as a click to navigate away.

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena can we fix this?

**Comment by Nikhil-Nandagopal** [comment]
@prapullac please verify
