### ISSUE TITLE
[Bug]: Gsheets save and authorise logging out the user

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#29987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On release.app.appsmith.com, when I create a gsheet datasource and authorise it, it logs me out

### Steps To Reproduce

1. Go to release.app.appsmith.com
2. Create a google sheet datasource
3. Save and authorise

### Environment

Release

### Version

Cloud/ Self-Hosted - 1.9.58

**Comment by sneha122** [comment]
The RCA for this and resolution is being discussed [here](https://theappsmith.slack.com/archives/C040LHZN03V/p1703846194177649)

**Comment by rohan-arthur** [comment]
this is fixed now according to the slack thread linked above
