### ISSUE TITLE
[Bug]: Issue with sample app forking: app getting added to workspace, but fork request getting cancelled and user not taken to newly created app.

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#29993]
I am not able to fork few sample apps cc: <@U04V0N2K0G1> <@U02QA4TCSHE> - <https://app.appsmith.com/applications/61e11a42eb0501052b9fab3e/pages/6256ffb40d3d384069c08487?fork=true>

[Slack Message](https://theappsmith.slack.com/archives/C02RCR2PURZ/p1704260614619099?thread_ts=1704260614.619099&cid=C02RCR2PURZ)

**Comment by AnaghHegde** [comment]
Found the below error happening in Application forking flow. This not always but intermittent and this is what is causing the fork flow to fail for few apps  - `java.util.ConcurrentModificationException:` 

I will update the thread once i find the root cause for this error.

**Comment by AnaghHegde** [comment]
This is not the actual reason for the failure. We are unable to reproduce the issue any more.

**Comment by rahulbarwal** [comment]
Based on the conversation here: https://theappsmith.slack.com/archives/C02RCR2PURZ/p1704976129544819?thread_ts=1704969434.012179&cid=C02RCR2PURZ

The sample app in docs did not get updated in all places last time, due to this when a user lands on the faulty app and tries to fork it, is facing issues. 
@danciaclara will take this up with docs team to update in all places. 
@AnaghHegde Add a comment if something is amiss.
