### ISSUE TITLE
[Bug]: API Key showing in console log

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#30009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a datasource that uses an api key for authentication.  When I run a query of that data source the API key is visible in the log.

Internal conversation :- https://theappsmith.slack.com/archives/C040LHZN03V/p1704354949494669 

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/123981587/729f47f6-5ae5-404b-ab90-324b1036a172)

1. Create data source 'authenticated api'
2. Set authentication to apikey
3. Give it an apikey
4. Create a query for that data source
5. Run the query
6. Go to your logs
7. Expand the log for the query

Note that if you edit that data source it hides the API key from you.  So if you are hiding it from the user on the edit screen you should not make it visible in the log.

### Environment

Production

### Version

Self-hosted -  v1.9.44

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS thanks for raising this issue. We'll pick this up in our next sprint

**Comment by rohan-arthur** [comment]
IMO we should leave the decision to the user to specify which params should be treated as a secret.

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur but this isn't an arbitrary param. This is a specific param called API Key in the authentication which is a secret

**Comment by rohan-arthur** [comment]
@Nikhil-Nandagopal thanks! I got it confused with another feature request. Agree, this is indeed more straightforward.

**Comment by rishabhrathod01** [comment]
Paused work on this to resolve the A-force issue mentioned here https://github.com/appsmithorg/appsmith/issues/33601
