### ISSUE TITLE
[Bug]: gitlab integration in a self hosted environment behind a firewall causes internal error because cs.appsmith.com can't be reached

### ISSUE THREAD

**Issue by mp-gh** [appsmithorg/appsmith#30008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you try to set up gitlab integration for an app while behind a firewall without external internet access you get:
INTERNAL ERROR
Internal server error while processing request

### Steps To Reproduce

1. install self-hosted appsmith behind a firewall without external internet access to cs.appsmith.com
2. try to set up gitlab integration
3. you get:
INTERNAL ERROR
Internal server error while processing request

Looking at the server logs, 
/usr/lib/appsmith/stacks/logs/backend/backend-bbc5791b431d.log shows:
[2024-01-03 22:16:32,349] userEmail=mp-gh@redacted.org, sessionId=acae5b50-32b1-40c2-bfda-d8cf5775c1d9, thread=reactor-http-epoll-1, requestId=6367e241-c12a-4dd9-b222-11136f22e552 -
org.springframework.web.reactive.function.client.WebClientRequestException: cs.appsmith.com: Name or service not known
        at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ Request to GET null [DefaultWebClient]
        *__checkpoint ⇢ Handler com.appsmith.server.controllers.GitController#connectApplicationToRemoteRepo(String, GitConnectDTO, String) [DispatcherHandler]

Even if you decide you don't want to allow self-hosted instances without phoning home, the error could be handled better. 

### Environment

Deploy Preview

### Version

Appsmith Community v1.9.41

**Comment by Nikhil-Nandagopal** [comment]
@mp-gh yes we could potentially handle this better. Right now we don't support air-gapping in the community edition and you will need to write to sales@appsmith.com to get access to an airgapped instance.
