### ISSUE TITLE
[Bug] Cannot navigate with keys in the datasources suggestion for API pane

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3000]
![image](https://user-images.githubusercontent.com/5298848/107734707-0f6d3e80-6d24-11eb-8315-b24a6cc86fa1.png)

- [ ] the keyboard navigation doesn't work in HTTP method dropdown.
- [ ] The dropdowns don't have a hover state

**Comment by hetunandu** [comment]
Can store add multiple datasources and see if you still see this? Mostly it seems to be an issue with highlighted state not being very obvious

**Comment by nidhi-nair** [comment]
Lol yes I have no idea which one is selected.
![image](https://user-images.githubusercontent.com/5298848/107741541-6595ae00-6d33-11eb-9975-14fd51856819.png)

**Comment by mohanarpit** [comment]
@aakashDesign Can you re-look at the colour scheme here?
