### ISSUE TITLE
[Feature] Add theme switching on the editor navbar

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3001]
## Summary

Today, the theme can only be switched on the home page. It'll be consistent & useful for the theme switching to also take place in the editor's navbar as well. 

## Motivation

It feels inconsistent to have the user's profile button on the navbar with different options showing in the dropdown based on the screen that the user is on. Having this consistency will make features more discoverable to users.

**Comment by Nikhil-Nandagopal** [comment]
Closing sine we're killing themes
