### ISSUE TITLE
[Feature] Allow for more space when editing an App

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3003]
## Summary

Allow users to have more space in the editor by collapsing the entity explorer.

## Motivation

Users sometimes need more space when editing in Appsmith. The ability to hide the entity explorer, without losing the ability to quickly access another entity will be useful

# Additional Specification

- When a user opens an entity, it adds a tab (like any other IDE)
- Users start with the home page's tab
- Entity Explorer can be collapsed.
- When the entity explorer is collapsed, hovering over the collapsed entity explorer expands it until the mouse pointer goes outside the bounds of the explorer.
- When the same name Action exists in different pages, we show `pageName/actionName` in the tab name

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno removing this from UI building since this affects entity explorer across the board. We'll pick this up along with simplifying the entity explorer

**Comment by kocharrahul7** [comment]
This was solved in [this](https://github.com/appsmithorg/appsmith/pull/9811) PR
