### ISSUE TITLE
[Feature]: Appsmith AI

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#30047]
## Summary
We are clearly in a new age where generative AI has gained a lot of popularity. We recently launched integrations with OpenAI, Anthropic, and Gemini to help users build internal apps with AI capabilities. Appsmith AI further reduces the barrier to embedding AI capabilities on your internal app. With Appsmith AI, our mission is to make business processes more efficient by adding an extra layer of intelligence. 

## Key Features

- Appsmith AI is a fully managed AI datasource with all batteries included. You can instantly get started by simply selecting an action, writing a prompt and running the query. 
- Supported actions: Text generation, Text classification, Text summarisation, Entity extraction from text, Image generation, Image captioning, Image classification, Entity extraction from image
- You can also run AI queries on custom context such as large PDF/Markdown documents (eg: ask AI to generate responses based on your internal knowledge base or SOP documents)

**Comment by Aayushp2002** [comment]
Can I work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
Hi @Aayushp2002 , this is not a good first issue so I'd recommend starting by filtering for those first!
