### ISSUE TITLE
Users should not see any package section till they actually created one via the new button

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#30049]
Context: https://theappsmith.slack.com/archives/CRVRBGU1K/p1703163336131549
[Design](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Appsmith-Reusability?type=design&node-id=4758-85163&mode=design&t=1hTtEVDsKqdOSMgv-0)

**Comment by ashit-rath** [comment]
Closing this as this is already implemented
cc: @pedro-santos-rodrigues
