### ISSUE TITLE
[Bug]: Unable to delete the API datasource

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#30071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://theappsmith.slack.com/archives/C040LHZN03V/p1704429009634409

### Steps To Reproduce

https://theappsmith.slack.com/archives/C040LHZN03V/p1704429009634409

### Environment

Production

### Version

v1.9.58-SNAPSHOT

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #16866
