### ISSUE TITLE
Improve UI control that allows to set boolean values of JS Object function settings

### ISSUE THREAD

**Issue by pedro-santos-rodrigues** [appsmithorg/appsmith#30098]
**Goal:** Change boolean UI controls to change value of JS Object function settings that are presented in a table from radio buttons to toggles/switches.

[Figma design](https://www.figma.com/file/eazTgr34kBO3PNNA11lzZr/IDE-Continuous-Improvements?type=design&node-id=3-7677&mode=design&t=m3Z6wcHk4798UgOP-4)

![image](https://github.com/appsmithorg/appsmith/assets/36523902/cac80675-903c-4bb3-839a-5ea7dc7537d6)

**Rationale:**
As UI improvement, changing from radio buttons to switch/toggle reduces the repetitive amount of information that can lead to visual noise by repeating “Yes” and “No” for each function and setting, making it cleaner and easier to identify what are the settings that have their value set to True/Yes

**Applicable to:**

- JS Object function settings table
- JS Module instance function settings table
- Any other place where boolean JS function settings are presented in a table

**Comment by Rhitottam** [comment]
HI @pedro-santos-rodrigues, I would like to work on this improvement. It could be a small change to replace the Radio group with a Switch control.

**Comment by pedro-santos-rodrigues** [comment]
Completed in this PR: https://github.com/appsmithorg/appsmith/pull/30760
