### ISSUE TITLE
[Feature]: Support Validation Section and Required Toggle for Select Column Type

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#30091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The validation section and required toggle are not available for Select column types.
We only provide the Required toggle and the Validation section for Plain Text column types, but not for Select column types. 

### Why should this be worked on?

A user who uses the editable table with a Select column type may want to make this field required.

[Front thread](https://app.frontapp.com/open/cnv_17c1zn9o?key=D_DYOgA4TJ0FAMJncD9gtO48E5mJZGtm)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4e78y4)

**Comment by simonfvr** [comment]
Hello, what's the status of this issue? [I can see in the documentation](https://docs.appsmith.com/reference/widgets/select#required-boolean) information about the `required` option, but I'm not able to set a select column required in Appsmith.

**Comment by Nikhil-Nandagopal** [comment]
@simonfvr we don't currently have it for the table widget though it exists for the select widget separately

**Comment by simonfvr** [comment]
@Nikhil-Nandagopal thanks for your answer, is it planned to implement it for the table widget?

**Comment by Nikhil-Nandagopal** [comment]
@simonfvr we do, we're just currently backed up with a lot of feature requests. We'll update this Github issue once it's picked up
