### ISSUE TITLE
Cleanup activities

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#30105]

**Comment by srix** [comment]
- approvalInbox api endpoints needs to be renamed to more generic like approval. Since inbox is one of the way we can solve this requirement.
- Donot use runid in the code in java or proxy. because it is used in temporal and appears in logs
- Donot use workfowlid in java server because it’s used by temporal for tracking workflow instances and appears in logs
- page id cleanup (ayush raised a github task for it)

**Comment by nsarupr** [comment]
```
public class ApprovalRequestCreationDTO {
    ...
    String runId; // Change this to workflowRunId;
}
```
