### ISSUE TITLE
[Bug]: Not able to delete datasource query in workflow

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#30126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to delete a query associated to any datasource i.e. postgres or mongo, not able to delete it. Attaching video: 

https://github.com/appsmithorg/appsmith/assets/80334441/3b6c758c-f292-4c45-8753-66b171baa315

### Steps To Reproduce

1. Go to workflow
2. Create new datasource eg postgres and create new query for it
3. Try to delete the query
4. Observe we are not able to delete the query

### Environment

Release

### Version

https://release-ee.appsmith.com/applications

**Comment by nsarupr** [comment]
Delete API call isn't happening when one clicks on Delete.
