### ISSUE TITLE
[Bug]: Able to access workflow without edit permission for it

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#30136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 I am able to see edit workflow option even with only delete or view run history permissions, getting in edit mode says invalid url.

https://github.com/appsmithorg/appsmith/assets/80334441/a293dccd-2fdf-4618-9825-619093f0c6e0

### Steps To Reproduce

1. Login as admin, create new role with delete or view history permission at workflow level, and create permission at workspace level.
2. Assign this role to user1
3. Login as user1, observe you should be able to go in edit mode of workflow

### Environment

Release

### Version

https://release-ee.appsmith.com/

**Comment by ayushpahwa** [comment]
Tested on workflows DP. When following the steps given, server stops sending the workflows in fetch API. @nsarupr is this the desired behaviour? Also, I don't see the view history permission in roles page.
<img width="1158" alt="image" src="https://github.com/appsmithorg/appsmith/assets/8526215/68a809db-67e3-4d0d-af14-a863efb247f8">
<img width="889" alt="image" src="https://github.com/appsmithorg/appsmith/assets/8526215/04048672-5cc5-4ebf-9748-e2bd91a15393">

**Comment by nsarupr** [comment]
The View History permission is given as a side effect with Edit.
