### ISSUE TITLE
[Bug]: When I rectify a code, the errors associated with the code do not go away automatically in the console. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I rectify a code, the errors associated with the code do not go away automatically in the Console. 

### Steps To Reproduce

1. Add a code for a widget in the javascript section [or HTML section]
2. Remove a curly bracket in the code
3. Note that an error pops up
4. Now add the single curly bracket back.
5. The error does not go away. We have to manually clear the errors. This is true for errors in any section. [HTML, CSS, Javascript]

Note: If we look at the same behavior in the JS Object code window, as soon as the error is rectified, the error from the console goes away. 

https://github.com/appsmithorg/appsmith/assets/101863839/e696fed8-9444-46ee-bf40-5d12d62feccc

### Environment

Release

### Version

Cloud

**Comment by sbalaji1192** [comment]
Closing this as it is fixed in latest release
