### ISSUE TITLE
[Bug] Icon are not added to action items in API page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3015]
Steps to reproduce:
1) Navigate to API Pane 
2) Click on Action items (Three Dots)
and observe

Expectation :
As per FIGMA we observe that every action has a icon corresponding to the action items which is missing in the current implementation

**Comment by areyabhishek** [comment]
@prapullac Could you please leave screenshots here? It'll be easier to understand these visual problems

**Comment by prapullac** [comment]
Sure @areyabhishek attaching below

![Screenshot 2021-02-12 at 2 58 29 PM](https://user-images.githubusercontent.com/71753653/107751426-65051380-6d43-11eb-86eb-e40e97876555.png)
![Screenshot 2021-02-12 at 2 58 43 PM](https://user-images.githubusercontent.com/71753653/107751499-7c440100-6d43-11eb-8d33-0e8114c85c41.png)
