### ISSUE TITLE
[Bug]: Learn more documentation on create datasource takes us to basic application setup documentation page

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#30169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We have this banner on create datasource page for whitelisting IP and we have a CTA to learn more, when clicked on learn more it takes me to [this doc page](https://docs.appsmith.com/getting-started/tutorials/start-building#connect-to-a-database), I was expecting this doc page to have info on either datasources or white listing the IP but instead this page has info on basics of application setup. We should fix this and make learn more CTA take us to respective datasource's documentation page: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1704804571691129?thread_ts=1704803786.978579&cid=CGBPVEJ5C

![Screenshot 2024-01-09 at 6 02 41 PM](https://github.com/appsmithorg/appsmith/assets/30018882/65013fc0-7510-4fe1-bf1b-eecdb16b096f)

### Steps To Reproduce

1. Create a datasource
2. Observe the banner that appears on top
3. Click on Learn More

### Environment

Production

### Version

Cloud/ Self-Hosted - 1.8.4

**Comment by Nikhil-Nandagopal** [comment]
@sneha122 can you fix this? It should go to the respective datasource page

**Comment by sneha122** [comment]
@Nikhil-Nandagopal Yes I will take this up

**Comment by rohan-arthur** [comment]
this has regressed further: https://theappsmith.slack.com/archives/C040LHZN03V/p1710834929148849

**Comment by rahulbarwal** [comment]
Adding to the above comment, lets ensure we check the click functionality on different browsers. 

On Arc and firefox, it is opening 2 tabs - one of which is blank.
On Safari it works expectedly.

**Comment by NilanshBansal** [comment]
Datasource Name | Documentation Link | Link Configured Correctly?
-- | -- | --
Google Sheets | https://docs.appsmith.com/connect-data/reference/querying-google-sheets#create-queries | Yes
REST API | NA | NA
PostgreSQL | https://docs.appsmith.com/connect-data/reference/querying-postgres | No
MySQL | https://docs.appsmith.com/connect-data/reference/querying-mysql | No
MongoDB | https://docs.appsmith.com/connect-data/reference/querying-mongodb | No
GraphQL API | NA | NA
Authenticated API | NA | NA
Authenticated GraphQL API | NA | NA
CURL Import | NA | NA
Elasticsearch | https://docs.appsmith.com/connect-data/reference/querying-elasticsearch | No
DynamoDB | https://docs.appsmith.com/connect-data/reference/querying-dynamodb | No
Redis | https://docs.appsmith.com/connect-data/reference/querying-redis | No
Microsoft SQL Server | https://docs.appsmith.com/connect-data/reference/querying-mssql | No
Firestore | https://docs.appsmith.com/connect-data/reference/querying-firestore | No
Redshift | https://docs.appsmith.com/connect-data/reference/querying-redshift | No
S3 | https://docs.appsmith.com/connect-data/reference/querying-amazon-s3 | No
Snowflake | https://docs.appsmith.com/connect-data/reference/querying-snowflake-db | No
ArangoDB | https://docs.appsmith.com/connect-data/reference/querying-arango-db | No
SMTP | https://docs.appsmith.com/connect-data/reference/using-smtp | No
Oracle | https://docs.appsmith.com/connect-data/reference/querying-oracle | No
Databricks | https://docs.appsmith.com/connect-data/reference/databricks | No
Airtable | NA | NA
AWS Lambda | NA | NA
HubSpot | NA | NA
Twilio | NA | NA
Anthropic | NA | NA
Appsmith AI | NA | NA
Google AI | NA | NA
Open AI | NA | NA

**Comment by NilanshBansal** [comment]
As per the code written in the client side, the open documentation codebase is not specific to each plugin. It is a single piece of code which can take in a common link to the documentation for all plugins.
For the current scenario, we need separate links to each plugin. 

Ref: https://github.com/appsmithorg/appsmith/blob/d38e4b0b38cbbaee87a27e8fef710cfb25974593/app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx#L86-L106


Also, the documentation link reference in the codebase is not read from the database field `plugin.documentationLink` rather it is hardcoded [here](https://github.com/appsmithorg/appsmith/blob/d38e4b0b38cbbaee87a27e8fef710cfb25974593/app/client/src/constants/DocumentationLinks.ts#L16).

**Comment by NilanshBansal** [comment]
Deproioritising this because of a performance improvement that needs immediate attention.
https://github.com/appsmithorg/appsmith-ee/issues/4061
