### ISSUE TITLE
[Feature]: Add Cypress test for templates revamp content flow

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#30161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need to setup a cypress test for the main templates gallery flows.

### Why should this be worked on?

We will need a Cypress test in addition to the unit tests in this issue #30024 to test the entire templates gallery content flow. We have the filters, search, template and building block cards existing on that page. We need to test the actions together.

**Comment by rahulbarwal** [comment]
Done.
