### ISSUE TITLE
[Bug] Missing feature on API re-design according to figma 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3016]
1. Debug request is called as Request in current implementation
2. Timeout is not displayed in body
3. Bulk Edit option is not displayed to user
4. Notification not available in header
5. Save API for Reuse option is not available

**Comment by Nikhil-Nandagopal** [comment]
@prapullac we de-scoped these features. @hetunandu can we close this?

**Comment by hetunandu** [comment]
These requirements were changed while implementation. Can be closed
