### ISSUE TITLE
[Task] Update context menu adding module instances and icons

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#30163]
- [x] Update context menu of adding module instances to group by package name 
- [x] Update module instance icons in entity explorer
- [x] Update icon in module instance editor 
- [x] Send modules metadata in `/consumables` API ([backend task](https://github.com/appsmithorg/appsmith/issues/31569))

[Figma](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Appsmith-Reusability?type=design&node-id=4063-161664&mode=design&t=p9hWuXEsBjzCYdTE-0)

**Comment by subrata71** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modules-POD-63e0d668a7fea03850c89c6f/issues/appsmithorg/appsmith/30163?planning-poker) with Zenhub @ankitakinger
