### ISSUE TITLE
[Bug]: First time connecting to a git repo shows changes to commit *, though it has just been connected to a new repo

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I connect to git repo first time, in the bottom left panel, there is a * shown next to master, though there is nothing new added, and we are connecting the app for the first time. 

### Steps To Reproduce

<img width="663" alt="newlycreatedgit_showschangestocommit" src="https://github.com/appsmithorg/appsmith/assets/101863839/17f0b9f7-cd28-42b5-9fef-a3fa88cc4764">

https://github.com/appsmithorg/appsmith/assets/101863839/73baa074-5c0f-4385-abf9-e896574c05d8

### Environment

Production

### Version

Cloud

**Comment by RakshaKShetty** [comment]
Fixed
<img width="827" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/d1170f37-6ca6-4bb3-8bec-12291ecc5ba2">
