### ISSUE TITLE
[Bug]: While saving and authorizing google sheets, the ui text font size increases momentarily before going to the google auth page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a new gsheets DS, While saving and authorizing the DS, the ui text font size increases momentarily before going to the google auth page

### Steps To Reproduce

On Release - 
https://github.com/appsmithorg/appsmith/assets/101863839/4cb8c13f-94d8-41bf-b044-08d7c732c4ed

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by rohan-arthur** [comment]
not reproducible anymore on release
https://github.com/appsmithorg/appsmith/assets/94514895/3cdbf5d0-b042-41f6-99ec-5e08dc4117d5
