### ISSUE TITLE
[Feature] [Table widget] Option to disable the download button

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#3019]
## Summary
An option to disable the download button

## Motivation
In some instances, the app owners might not be comfortable with an explicit option to download the table data

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno can we do a quick fix here?

**Comment by areyabhishek** [comment]
We should expose these as table controls right?

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek yes related to #2111

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal We're picking this up in #2111. Closing this.
