### ISSUE TITLE
[Bug]: The Custom widget example code doesnt seems to be working as expected

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Code that has been given as a example in the Documents gives a empty widget when it's used in the Application
In the below screen shot it says its an eg: for creating image carousel
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/03a7b5f0-fd67-49bf-a287-b08b17db0cc4">

### Steps To Reproduce

1. go to the Appsmith docs page 
2. Now navigate to custom widget docs
3. try to copy-paste the code that has been shared
4. the empty page is displayed

### Environment

Release

### Version

v1.9.59

**Comment by sbalaji1192** [comment]
@harshilp24 Can you check if this is still valid and close accordingly?

**Comment by harshilp24** [comment]
@sbalaji1192 we have updated the docs; also @RakshaKShetty did you encounter any issues after completing the entire guide, or were the challenges limited to the initial steps?

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
