### ISSUE TITLE
[Bug]: CPU Overload After Auto-Heal

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#30216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The instance got stuck twice. It looks like it launched the auto-heal, but immediately the CPU got overloaded and the service was not available anyway. The issue was fixed only after a manual reboot.
![image](https://github.com/appsmithorg/appsmith/assets/101268423/247aae12-4189-4d37-9c36-85141853f0d4)

### Steps To Reproduce

[ZD ticket](https://appsmith3239.zendesk.com/agent/tickets/1293)

### Environment

Production

### Version

v1.9.56

**Comment by rajatagrawal** [comment]
The issue seems to be resolved as per the ZD ticket associated for this github issue. Closing the issue.
