### ISSUE TITLE
[Bug]: On creating a new OpenAI DS, authentication details aren't mentioned on the edit DS screen

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#30222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On creating a new OpenAI DS, authentication details aren't mentioned on the edit DS screen

### Steps To Reproduce

1. Create and configure a new OpenAI DS and save it
2. Notice that the authentication details aren’t seen 
<img width="1430" alt="image" src="https://github.com/appsmithorg/appsmith/assets/109572422/82f2f1c0-83c4-456c-bcb6-18ea3d87b82f">

Expected:
Authentication details such as it's type must be seen on the page. 
<img width="1080" alt="image" src="https://github.com/appsmithorg/appsmith/assets/109572422/4eb155e3-e9a9-475a-a019-f36d1c7eef0c">

### Environment

Production

### Version

Version v1.9.59

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working now
