### ISSUE TITLE
[Bug]: Salesforce Auth Token doesn't refresh automatically

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#30239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App Link: https://internal.appsmith.com/app/license-tracker/clients-645b6543a56f84769dcbc32d/edit
Issue Description: https://theappsmith.slack.com/archives/CNQ9Q91C0/p1702972094026239

### Steps To Reproduce

https://theappsmith.slack.com/archives/CNQ9Q91C0/p1702972094026239

### Environment

Production

### Version

v1.9.59-SNAPSHOT

**Comment by sneha122** [comment]
Closing this completed. Please check epic https://github.com/appsmithorg/appsmith/issues/30826

**Comment by NilanshBansal** [comment]
Reopening this, as the issue is still reproducible on the production environment.
cc: @tomjose92 @sneha122 @rohan-arthur

**Comment by NilanshBansal** [comment]
Update: Tested by creating an app on Appsmith Cloud with 3 queries setting the token refresh time to 600 seconds. The app is working for the last 48 hrs.
https://www.notion.so/appsmith/Salesforce-355d3963e05d4428b570b06e089a1001?pvs=4

**Comment by NilanshBansal** [comment]
The salesforce refresh OAuth token flow was failing because the configuration for salesforce OAuth was not correctly done in Appsmith. 
The `Send Scope With Refresh Token` dropdown had to be set as `No`. 
I have added all the relevant information for configuring salesforce here.
https://www.notion.so/appsmith/OAuth2-How-and-what-01c224ee730c4b77a79459256f0a4a9d?pvs=4#8f4bb462378b4e909c5f9e5a79029c8d

cc: @sneha122 @rohan-arthur

**Comment by NilanshBansal** [comment]
The application has stopped working after 2 days hence reopening this issue. 

Our hunch is that the current issue why apps are failing is due to this:
https://salesforce.stackexchange.com/questions/65590/connected-app-avoiding-a-limit-on-a-number-of-issued-tokens-token-expiration
The above question has 70 upvotes and is a widely faced issue with salesforce and we are facing the exact same behaviour. We are further drilling down onto this.

**Comment by NilanshBansal** [comment]
Discussion Thread: https://theappsmith.slack.com/archives/CNQ9Q91C0/p1702972094026239

**Comment by NilanshBansal** [comment]
Update: We are getting the same error from Salesforce after 1-2 days. Here is the screenshot of the error log from my local system. The logs are not informative enough. It is related to this https://github.com/appsmithorg/appsmith/issues/30239#issuecomment-1970802839
<img width="1227" alt="SCR-20240229-muy" src="https://github.com/appsmithorg/appsmith/assets/25542733/7db2c94c-a946-44aa-a633-c370c8b12a46">

**Comment by NilanshBansal** [comment]
Had enabled the refresh token rotation in salesforce on 29th Feb, 2024 at 5 pm IST. The idea behind doing this is [here](https://theappsmith.slack.com/archives/CNQ9Q91C0/p1709201663596309?thread_ts=1702972094.026239&cid=CNQ9Q91C0)

![image (16)](https://github.com/appsmithorg/appsmith/assets/25542733/0e687865-354b-4f93-8940-fd3d044caaf2)

**Comment by NilanshBansal** [comment]
Update: The appsmith app is working fine since the last 28 hours. The usage count in the salesforce dashboard has gone up to 77 now! 

<img width="1134" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/37e30ab6-b67b-4898-9d85-225f4f159a9b">

**Comment by NilanshBansal** [comment]
Update: The appsmith [app](https://app.appsmith.com/app/salesforce-dev/page1-65dc5b3688b4847d61fca1d6) is working fine since the last 3 days.  
The usage count stands at 85 now. 

<img width="1433" alt="SCR-20240303-o4m" src="https://github.com/appsmithorg/appsmith/assets/25542733/f17c3494-942e-4085-b59a-10b18fb8bbc6">


This marks the permanent fix for this issue! The salesforce-connected app is working perfectly fine auto refreshing the tokens.
