### ISSUE TITLE
[Bug]: user not able to save after running Postgres query

### ISSUE THREAD

**Issue by toxicflux** [appsmithorg/appsmith#30234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We're hosting our application in the K8 cluster in Azure and are experiencing performance issues that occur from time to time. The problem is related to running Postgres queries, and instance restarts are often needed to solve the problem.

When I go to the Postgres query and I manually click "run", a query that is usually fast (some hundred milliseconds) suddenly takes several minutes to respond. This happens not every time; maybe 1 of 100. If this happens, the entire instance gets very slow for many minutes or even hours. Sometimes it never recovers, and the problem continues indefinitely.  As a consequence, it's not possible to save any changes to work (redux timeout, it says a never-ending "Saving..." in page header) and work is lost if user refresh page. This makes it impossible to work with the instance after the crash occurs.

![Executive-Outlook-Editor-Appsmith (1)](https://github.com/appsmithorg/appsmith/assets/103540352/99cdea54-5e85-46d6-9f89-616da5d44631)

JS console
`main.9ce7b334.js:2  Error
    at main.9ce7b334.js:2:1444807
    at p (main.9ce7b334.js:2:5642717)
    at Generator.<anonymous> (main.9ce7b334.js:2:5644060)
    at Generator.next (main.9ce7b334.js:2:5643080)
    at d (main.9ce7b334.js:2:1722707)
    at ca (main.9ce7b334.js:2:1722499)
    at main.9ce7b334.js:2:1722234
    at p (main.9ce7b334.js:2:1723250)
    at d (main.9ce7b334.js:2:1722769)
    at s (main.9ce7b334.js:2:1723031) {type: 'UPDATE_JS_ACTION_BODY_ERROR', payload: {…}, @@redux-saga/SAGA_ACTION: true}`

### Steps To Reproduce

1) Go to Postgres query
2) Trigger "run" 
If the results in a extremely slow query (several minutes or never-ending query), the bug is triggered 
3) Change the content of a JS Object. 
=>  instance is in a useless state in which the user cannot save changes

### Environment

Production

### Version

1.9.47

**Comment by Nikhil-Nandagopal** [comment]
@toxicflux can you tell us how many rows are being returned and potentially share the query? You can replace any sensitive table or column names.

**Comment by sumitsum** [comment]
Hi @toxicflux few questions:
(1) When this issue occurs, if you open the application in a new tab or refresh the page, does it work ? 
(2) Is the application able to respond normally after few minutes / hours ? 
(3) Does the application work properly after restarting the Appsmith instance ? 
(4) What is the maximum number of rows x columns that could be returned from the database queries running on the application ? 
(5) Does this problem only occur when a Postgres query is triggered ? 
(6) Do other queries work ( apart from the one that triggered this issue or other database queries) after this issue has occured ?

**Comment by toxicflux** [comment]
(1) Not, it is not possible to recover from this state
(2) Yes, app uses max 10 seconds to load in normal conditions. If this problem occurs, everything becomes slow.
(3) Yes, as I write in the description, restarting the instance solves the problem.
(4) The query that broke application had 5 columns and 11 rows.
(5) My impression is that this is directly related to clicking "run" in Postgres query and the problem related to saving  follows immediately after.
(6) Any Postgres query can fail like this. It's not related to the query itself.

(a) We restarted the instance, so now the problem is fixed. I can make a recording next time this occurs.
(b) We can share server/Appsmith logs if you contact me directly.
(c) then we have to be able to trigger this bug again, which might take days, since it happens from time to time.

**Comment by sumitsum** [comment]
Hi @toxicflux thanks for the response. If possible, can you please share your [application log files](https://docs.appsmith.com/getting-started/setup/instance-management/how-to-get-container-logs) to `sumit@appsmith.com`. 
 Few other follow up questions:
(1) Which version of Appsmith are you using ? 
(2) Are you using any 3rd party Postgres service (like Supabase) ? If so, which one ? 
(3) Would it be possible to check how many open connections postgres DB has when the Appsmith Postgres query fails ? 
(4) Just asking for confirmation - when this issue occurs, opening a new tab and accessing the application via the new tab does not help ? 
Also, as you have mentioned, can you please share a screen recording of when this issue happens next. Please try to include the `network` tab and the `console` tab data from Chrome inspector as well.

**Comment by rohan-arthur** [comment]
Sumit, I have removed the label `Postgres` so that this issue doesn't show up in the integrations board. Please add it back if needed.

**Comment by sumitsum** [comment]
Hi @toxicflux gentle reminder, if possible, please do share the info mention [here](https://github.com/appsmithorg/appsmith/issues/30234#issuecomment-1888534799) so that we may be able to debug this further.

**Comment by Nikhil-Nandagopal** [comment]
@toxicflux we're closing this issue now. Hops this is fixed!
