### ISSUE TITLE
Self hosted users not able to fork sample apps

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#30237]

**Comment by danciaclara** [comment]
We need to allow people to download apps from our cloud URLs. Example: https://app.appsmith.com/app/pdf-files/generatepdf-fromformdata-62a76c1284b913372519db81 This app can’t be forked by a self-hosted user(85% of our user base)

We can just provide a way to download the JSON (our Export app feature) when users open these kind of apps.

**Comment by AnaghHegde** [comment]
https://www.notion.so/appsmith/Forking-Sample-Apps-Self-Hosted-Instance-13bb853b0ebd499ba58fd162e8f9fd9c

**Comment by rahulbarwal** [comment]
We are going to track this as a project based on doc shared above. Closing this issue for now.
