### ISSUE TITLE
[Bug]: Add static file path error reporting

### ISSUE THREAD

**Issue by yhcui01** [appsmithorg/appsmith#30259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A packaging error occurred when I added the static file request path. His prompts are shown in the figure below.

<img width="883" alt="image" src="https://github.com/appsmithorg/appsmith/assets/51847910/f53ace9e-d9f6-4510-ab86-472da2e8bcb4">

### Steps To Reproduce

 1.Add under the craco configuration file

 webpack: {
    plugins: plugins,
    configure: (webpackConfig) => {
      webpackConfig.output.publicPath = webpackConfig.output.publicPath =
        "./test/smith" + webpackConfig.output.publicPath.replace(/\//g, "\\/");

      return webpackConfig;
    },
  },
  
 2. yarn run build 
 
 3. He will get it. 😫
 
<img width="741" alt="image" src="https://github.com/appsmithorg/appsmith/assets/51847910/98a14925-0d6b-42f9-ba01-788cf0419895">

### Environment

Production

### Version

1.9.35

**Comment by Nikhil-Nandagopal** [comment]
@yhcui01 it seems you are on a very old version of the platform, could you try pulling the latest code? 
Also for code contribution issues, you can reach out to us on our discord
https://discord.com/invite/rBTTVJp
