### ISSUE TITLE
[Bug] table selected row property is not getting updated in image widget in deploy mode.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3026]
## Description
In deploy mode, selecting a different row does not update the selected row property bound to an image widget.
https://user-images.githubusercontent.com/1757421/107853399-c14b5e80-6e3b-11eb-9099-e1656aa1d6a0.mov

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Bind table selected row property to image widget.
2. Open deploy mode.
3. Select different rows and check if image widget gets the correct value from the selected row.

### Important Details
 - Version: Cloud
 - OS: Linux
 - Browser: chrome

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno looks like a big issue with the new table widget

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal @riodeuno I was trying the same thing today, but didn't see the problem. Not sure if this was a one time thing or any elusive / transient issue.

**Comment by Nikhil-Nandagopal** [comment]
@prapullac can you see if you're able to reproduce this issue?

**Comment by prapullac** [comment]
Hi @Nikhil-Nandagopal 

The image rendering is working as expected but after sorting the correct image is not rendered and the issue for this is logged #3021
