### ISSUE TITLE
[Bug]: White space on the right of Building blocks preview

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#30269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1440" alt="Screenshot 2024-01-12 at 15 54 36" src="https://github.com/appsmithorg/appsmith/assets/32227135/e28026d8-83b1-4d48-9190-9872b751d9dd">

it looks different from the preview on the usecase templates

### Steps To Reproduce

na

### Environment

Production

### Version

v1.9.59

**Comment by rahulbarwal** [comment]
Fixed here: https://github.com/appsmithorg/appsmith/pull/30313
