### ISSUE TITLE
[Bug]: The Source editor panes are not expandable / draggable

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open the source editor, and try and expand the code pane or the console pane, they cannot be expanded. The expected behavior is that the mouse pointer should change to two way pointer and the panes should be draggable to give view as desired by user, as is the case in queries/js windows.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/618bffbc-f11b-4cb6-bd53-8a0f2007f80e

### Environment

Release

### Version

Cloud

**Comment by sbalaji1192** [comment]
@btsgh We will be doing this an enhancement.

**Comment by sbalaji1192** [comment]
done as part of https://github.com/appsmithorg/appsmith/issues/30821
