### ISSUE TITLE
[Task]: Replace static wait in cypress/e2e/Regression/ClientSide/Autocomplete/BracketNotation_AC_spec.ts

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#30277]
### SubTasks

- This task will belong to all SDETS
- Since @sharanya-appsmith @sarojsarab are also not able to fix the spec flakiness, creating this task for tracking.

**Comment by NilanshBansal** [comment]
Duplicate Task: https://github.com/appsmithorg/appsmith/issues/35134
