### ISSUE TITLE
[Bug]: The modal text spacing and the button sizes seem to be inconsistent

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a blank or some other template in the source editor, the modal that pops up has smaller buttons and the spacing/padding between the heading and the text does not seem correct.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/93f3d125-7ca5-49f9-bf39-80ec5be9fa0a

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
