### ISSUE TITLE
[Bug]-[1400]:Download action is not working in button widget when configured as second action

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3027]
## Description
Download action is not working when configured as a second action i.e 1st action is to run query and 2nd action is to download.  Two problems I can see - (1) filename missing error pops up even when filename is provided (2) JS function written inside JS editor box is lost. 
https://user-images.githubusercontent.com/1757421/107853992-08871e80-6e3f-11eb-8e5e-af73b0cf3f25.mov

### Steps to reproduce the behaviour:
1. Create a button widget
2. Add 1st action as run query
3. Add onSuccess action as download.
4. Click on the button widget.

### Important Details
 - Version: Cloud
 - OS: Linux
 - Browser: Chrome

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal This looks like it is an action creator issue.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum lowering priority since you don't need to send a function into the download field, you can pass the actual value there directly. Also anonymous functions work!

**Comment by hetunandu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/3027?planning-poker) with ZenHub @sumitsum

**Comment by vnodecg** [comment]
This error is cause by this line https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/editorComponents/ActionCreator/index.tsx#L140

Regex breaks when we have a closing `)`

<img width="1147" alt="Screenshot 2021-09-06 at 17 22 15" src="https://user-images.githubusercontent.com/4994565/132213814-98059b02-61b4-4bac-b3cb-4d9df19b2ed2.png">

**Comment by rohan-arthur** [comment]
WIDGET_PROPERTY_UPDATE
- propertyName = onClick
- updatedValue contains "=> download"
6m usage: 63

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 63 |
| Effort (months)  | 0.25 |

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur this would happen for any widget though it's reported for button

**Comment by rohan-arthur** [comment]
@Nikhil-Nandagopal , WIDGET_PROPERTY_UPDATE should include all properties I guess?

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur yes it will

**Comment by bharath31** [comment]
@ramsaptami could you verify if the issue still exists?

**Comment by ramsaptami** [comment]
Closing this as it seems to be working as expected now

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami this isn't working for me. In fact it's clearing the data in the download configuration and it's completely broken

Uploading Screen Recording 2022-08-23 at 7.42.28 PM.mov…

**Comment by ramsaptami** [comment]
My bad for prematurely closing this issue, I missed watching the video attached. 
Tested using direct widget binding `{{Table1.selectedRows}}` or `{{Chart1.chartData}}` which works fine but the original issue still exists as mentioned in Nikhil's comment above

**Comment by bharath31** [comment]
@rimildeyjsr could you check this as a part of the action selector refactor epic?

**Comment by ravikp7** [comment]
I'm not able to re-produce this issue now. @ramsaptami Can you please test on your side and close it?

cc @bharath31

**Comment by AnandiKulkarni** [comment]
@rimildeyjsr @bharath31 this is not completely fixed - Original issue mentions two problem which seems to be working
 (1) filename missing error pops up even when filename is provided  (2) JS function written inside JS editor box is lost.
But there is no download if user provides data - {{function (){return "ababab"}()}} and 2 observation can be seen

https://github.com/appsmithorg/appsmith/assets/80756091/34183fd3-fb47-4581-a9f2-5650807527e1

**Comment by bharath31** [comment]
@Rishabh-Rathod could you please take a stab at this?

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod could you please take a stab at this?

This seems to be working fine for me. @AnandiKulkarni in the above example `.txt` extension was missed.

**Comment by AnandiKulkarni** [comment]
@Rishabh-Rathod @bharath31: Code is not getting evaluated and saved for  :   '{{function () { return "ababab";}()}} '  where user has not wrapped  the function in(), but in widget such as text,input,default values of button above code gets evaluated and saved. Download works fine for code : '{{(function () { return "ababab";})()}} ' 

@bharath31 please suggest

**Comment by Rishabh-Rathod** [comment]
When using `function () { return "ababab";}()` in the browser it results in the error mentioned below. 

![image](https://github.com/appsmithorg/appsmith/assets/23132741/1dc3f1e0-6e3c-4b7d-adb7-d484d9d548e0)

**Comment by AnandiKulkarni** [comment]
closing this issue as per discussion in standup
