### ISSUE TITLE
[Bug]: JSEditor | JSObject with async & sync functions throws random error toast

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#30271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/91450662/37ca058b-4347-44fd-95ee-2c333bb71906

### Steps To Reproduce

1. Create a new JS Object with below:
2. ```export default {
        myVar1: [],
        myVar2: {},
        myFun1: () => {	},
        myFun2: async () => {	},
        myFun3: async () => {	},
        myFun4: async () => {	},
        myFun5: async () => {	},
        myFun6: async () => {	},
        myFun7: () => {	},
      }```
3. Move to settings page to verify the async settings of the async functions
4. Observe the async functions are all not showing plus there is random error toast 'JSObject1.myfun5 already exists'
5. Expected: User should have smooth experience in creating the async, sync functions in JSEditor

### Environment

Production

### Version

Cloud/Release v1.9.59

**Comment by Aishwarya-U-R** [comment]
[Run details](https://internal.appsmith.com/app/cypress-dashboard/run-details-65890b3c81d7400d08fa9ee5?branch=master&workflowId=7500777654&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail) [Workflow link](https://github.com/appsmithorg/appsmith-ee/actions/runs/7500777654). with docker logs if it helps 
[dockerlogs.zip](https://github.com/appsmithorg/appsmith/files/13918263/dockerlogs.zip)

**Comment by Aishwarya-U-R** [comment]
Similar [Bug](https://github.com/appsmithorg/appsmith/issues/19152) reported here

**Comment by rohan-arthur** [comment]
not reproducible anymore, maybe it got fixed along with another PR.

https://github.com/appsmithorg/appsmith/assets/94514895/87ec57de-5775-40f2-b56b-981c6c7b930b
