### ISSUE TITLE
[Bug]: Rename functionality for a modal is broken

### ISSUE THREAD

**Issue by pranayagarwal96** [appsmithorg/appsmith#30281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user renames the modal, all underlying linkages don't get updated automatically and have to be updated manually

### Steps To Reproduce

1. Drag & drop a button widget. 
2. Open a new modal on click of a button
3. Rename the modal. 
4. Try and click the button again

Link to video [here](https://ru2fwekpma.vmaker.com/record/DRoLnTtfOV7WIY1i)

### Environment

Production

### Issue video log

https://ru2fwekpma.vmaker.com/record/DRoLnTtfOV7WIY1i

### Version

Cloud

**Comment by sharat87** [comment]
Same as https://github.com/appsmithorg/appsmith/issues/23475 I think.
