### ISSUE TITLE
[Bug]: The JSObject query page scroll is not working as expected

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I scroll on the JSObject query code page, the Code and Settings tab disappear, and we have to scroll back up to access the Settings tab. The scroll should be such that the Code and Settings tabs remain, only the code area should scroll. Compare the behavior with Datasource query page, the behavior should be similar to that. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/323aa8c5-6181-4032-9a5a-15d67ed74339

### Environment

Production

### Version

Cloud

**Comment by AmanAgarwal041** [comment]
This doesn't seem to be an issue anymore. Hence, closing this issue.
https://github.com/appsmithorg/appsmith/assets/7565635/8b015b9c-9e96-4a99-b9da-f66815ec94cd
