### ISSUE TITLE
[Bug]: Multiple scrollbars visible for connections tab in query pages

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#30296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We get to see multiple scrollbars inside the connections tab of the query page.

### Steps To Reproduce

1. Run some query.
2. Scroll inside the connections tab.

**Expected:** We should only see 1 scroll bar.

### Environment

Production

### Issue video log

https://www.loom.com/share/8ee5729ed523422c97c52c0bfbff3b7a

### Version

Cloud

**Comment by rohan-arthur** [comment]
Will be addressed in this issue: https://github.com/appsmithorg/appsmith/issues/29322
