### ISSUE TITLE
How to enter my current session again after closing the previous one? 

### ISSUE THREAD

**Issue by ambuje** [appsmithorg/appsmith#303]
Hi,
When I install appsmith It works perfectly but  when I shut down my laptop and try to open again appsmith them I am unable to do so. I have to uninstall it and install it again. 

Could you help me to know how to open my session again?

Thanks

**Comment by mohanarpit** [comment]
Hey @ambuje 

When you shut down your laptop the Docker containers would have shut down. In order to start them up again
1. Go to the folder where appsmith was installed ( by default, the script would have named this `appsmith` )
2. Run the command: `sudo docker-compose up -d` 

This should start all the required containers again. In order to verify this, run the command `sudo docker-compose ps`. You should see 5 containers running. You can now access Appsmith again by visiting `http://localhost` on your machine.

Let me know if this works for you.

**Comment by ambuje** [comment]
Hi 

Starting appsmith_appsmith-internal-server_1 ... error

ERROR: for appsmith_appsmith-internal-server_1  Cannot start service appsmith-internal-server: OCI runtime create failed: container with id exists: 77420e00e3e872d29b405aca0acfd071cff3e1eb9136fec8d51186fb7d07b413: unknown

ERROR: for appsmith-internal-server  Cannot start service appsmith-internal-server: OCI runtime create failed: container with id exists: 77420e00e3e872d29b405aca0acfd071cff3e1eb9136fec8d51186fb7d07b413: unknown
ERROR: Encountered errors while bringing up the project.

I encountered this error while running sudo docker-compose up -d

sudo docker-compose ps

               Name                              Command                State                      Ports                  
--------------------------------------------------------------------------------------------------------------------------
appsmith_appsmith-internal-server_1   /bin/sh -c /entrypoint.sh        Exit 255                                           
appsmith_certbot_1                    /bin/sh -c trap exit TERM; ...   Up         443/tcp, 80/tcp                         
appsmith_mongo_1                      docker-entrypoint.sh mongod      Up         27017/tcp                               
appsmith_nginx_1                      /bin/sh -c while :; do sle ...   Exit 255   0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
appsmith_redis_1                      docker-entrypoint.sh redis ...   Up         6379/tcp

**Comment by ambuje** [comment]
I was able to run but I had to delete appsmith_appsmith-internal-server_1 
docker rm appsmith_appsmith-internal-server_1
and then run 
sudo docker-compose up -d 
to get to the appsmith page

**Comment by Nikhil-Nandagopal** [comment]
@ambuje Glad that worked for you! I'm closing this issue now. If you face any other problems, feel free to open another one :)
