### ISSUE TITLE
[Enhancements] Add Firestore document metadata to returned result data object

### ISSUE THREAD

**Issue by tazmaniax** [appsmithorg/appsmith#3030]
## Summary

Add Firestore document metadata to returned results, specifically the associated document id and reference.

## Motivation

A Firestore document id and/or reference is required for passing to other queries to update or delete a specific document returned from a query. As well the document reference can be used to build sub collection queries, which at the moment is not possible

## Additional Context

One potential solution is to add a `_document` object within the returned document object that contains the `id` and `ref` attributes from the DocumentSnapshot

**Comment by sharat87** [comment]
Hey @tazmaniax, I've just submitted a PR for review on this. I made slight change to the interface you requested to bring it line with how reference data type fields are already represented. The `$ref` field in every document will have an `id` and `path` fields, just a reference field type.

**Comment by tazmaniax** [comment]
@sharat87 that's fantastic - this unlocks real functionality with Firestore, thx! When will this be available in the cloud version?

**Comment by sharat87** [comment]
@tazmaniax, glad to hear that. Unfortunately, I can't give an exact timeline, but should be within a day.

**Comment by tazmaniax** [comment]
@sharat87 of course understand but if it's around that time frame then great! I'm ready and prepped for when it's released :)

**Comment by sharat87** [comment]
@tazmaniax This is now live on app.appsmith.com :)

**Comment by tazmaniax** [comment]
@sharat87 I'm on it!! Thanks to you and the team for shifting this out the door so quickly!
