### ISSUE TITLE
[Bug]: Backslashes/Escape Characters Returned in Evaluations When Using HTML and JSON Data in an iFrame Widget

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#30301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using moustache syntax in the srcDoc of an iFrame, the JSON object looks correct, but when adding some other HTML tags, the double quotes are escaped with backslashes.

**Workaround**: Generate the whole srcDoc in a JS function and then call it in iFrame srcDoc property.

![image](https://github.com/appsmithorg/appsmith/assets/101268423/919eaaf2-eb92-4fe1-a947-39d0e39c0b46)

This is an issue that was reported by several users:

>How do I format JSON from a function into the srcDoc of an iFrame, without the escape characters?
> 
> - have run a simple test, with a function that simply returns { type: 'hello world' }
> - when it's the only value in the srcDoc, it looks perfect
> - when I insert any HTML into the srcDoc, it changes to have escape characters
> 
> I tried this with JSON.stringify() and got the same results.

![image](https://github.com/appsmithorg/appsmith/assets/101268423/d0726140-0c4d-44c0-9d65-16073ebb35c4)
![image](https://github.com/appsmithorg/appsmith/assets/101268423/651d4ebd-8be5-44f1-bdd0-1cd11591e2f4)

Tickets:
- [Front thread #1](https://app.frontapp.com/open/msg_1rqaof2k?key=NHGs83f4akViW0p86xgUwY43A2PJmwIj)
- [Front thread #2](https://app.frontapp.com/open/cnv_153jdggc?key=BKqyJszdMc8K97DFHg1mx2Y_T5EevTNK)
- [Front thread #3](https://app.frontapp.com/open/cnv_17qr3ma4?key=S1xTWxclRikY4aqe-fuUrAbVSruk3EF5)

### Steps To Reproduce

1. Add an iFrame widget to the canvas.
2. In the srcDoc property, add some HTML tags and some JSON data. For the JSON data use a dynamic binding (e.g., JS function, widget - see the above screenshots for more details).

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ame-appsmith since the content is returned as a string, it must be escaped and the correct way to deal with this is to parse the string with JSON.parse()
