### ISSUE TITLE
[Bug]: Table pagination - last page number is based on page size, but it should be based on pagination limit

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#30305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/94514895/c70027a0-b9aa-4522-9c17-bd5106f42f89

I have a table widget connected to Google sheets data. The data has 20 rows the table is set up for pagination with a limit of two rows at a time.
In the table widget properties, when I enter the total record count as 20, the last page is computed to be four because the table size is five rows. However my query is set up with the pagination limit of two records.

Expected: the last page is 10
Actual: the last page is 4

### Steps To Reproduce

explained in the video

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur this is expected. The developer is expected to configure the page limit to the page size and not the other way around since the table page size is static
