### ISSUE TITLE
[Enhancement] Register AMI in Europe, other regions

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3032]

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you help with this? The user wants an AMI in other regions

**Comment by mohanarpit** [comment]
Hey, we are revamping our installation script to a V2 version which improves some of our auto-updating processes. We are holding out on registering new AMIs with AWS marketplace till we launch this new version of the installation.

This may take another week for us to test the migration of older instances to the new process. Post that, we'll start registering the new AMI in other regions as well.

**Comment by mohanarpit** [comment]
This task is now complete. Appsmith AMI is now available in multiple AWS regions across the globe (including Europe, Asia, Middle east etc)
