### ISSUE TITLE
[Bug]: Appsmith keep generating code "createdAt"

### ISSUE THREAD

**Issue by AnnPei-YTL** [appsmithorg/appsmith#30327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I upgrade appsmith to v1.9.58, it generate code "createdAt: <current_timestamp>" to every metadata.json, which is fine.

Problems is that it will generate again everytime I want to push a commit even when the "createdAt" generated code is already there in the branch

This will cause problems when I use multiple ENV with same GIT repo as every ENV will generate the same "createdAt" code with different timestamp

### Steps To Reproduce

1. Upgrade Appsmith to v1.9.58
2. Commit "createdAt" generated code by Appsmith and push it to sub branch
3. Merge sub branch to main branch
4. Create another commit from main branch in Appsmith, Appsmith will generate the same code
5. Same when using another ENV, Appsmith will generate the same code

### Environment

Production

### Version

Self Hosted v1.9.58

**Comment by Nikhil-Nandagopal** [comment]
@AnnPei-YTL I didn't fully understand the issue here. What is the problem with createdAt getting regenerated? Could you share a video?

**Comment by infinitetrooper** [comment]
@AnnPei-YTL  - This is a bug, we should not be exposing the variable as that is unique to the app in that instance, we're currently fixing it. We'll keep you updated on this ticket.

cc: @riteshkew

**Comment by AnnPei-YTL** [comment]
You can refer the video below for the issue. I create a temp branch with the generated code and merge the branch into dev (my main branch), somehow the same code still getting generated in dev branch

https://github.com/appsmithorg/appsmith/assets/141106381/3b7af805-a644-43b5-af68-0115f64e6891

**Comment by infinitetrooper** [comment]
@AnnPei-YTL  - We've just tagged v1.9.60 which has a fix for this bug. Please let us know if you're facing any other issues.

**Comment by AnnPei-YTL** [comment]
@infinitetrooper it is fixed, thanks!
