### ISSUE TITLE
[Bug]: Error seen when there are no workspaces present

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Signup and logging in with a new user having no workspaces throws 'cannot read properties of undefined' error.
This error is also seen when all the workspaces are deleted. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/bfc0eda3-995d-40c1-8969-a2cf9558427e

### Environment

Deploy Preview

### Version

Cloud

**Comment by deepikaappsmith** [comment]
I believe this is completed.

https://github.com/appsmithorg/appsmith/assets/130959931/6f2ea8c4-274b-48ca-ba3e-b393a773d465

**Comment by btsgh** [comment]
Tested in latest release and found to be fixed.
