### ISSUE TITLE
[Bug]: Query data fast popup visible everywhere

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#30339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Query data fast popup appears in other places then the query page. I remember seeing it on the canvas too, but today the user saw it in the apps list page after visiting the query page.

![image](https://github.com/appsmithorg/appsmith/assets/81744497/f2a28d42-2dfb-4af7-b0ec-386d54cda017)

### Steps To Reproduce

Go to the query page for the first time then click on the appsmith logo

### Environment

Release

### Version

1.9.59

**Comment by rohan-arthur** [comment]
we should sunset walkthroughs: https://theappsmith.slack.com/archives/C05P3ME9MBR/p1706007688059509
