### ISSUE TITLE
[Bug]: UI/UX issues in the new homepage revamp

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#30340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attached is a video explaining the below issues:
1. `New` button has additional icon & text when comparing CE & EE.
2. Search menu not sourced from ADS.
3. Scroll bars inside search menu even when they are not required.
4. `No search results found` text persists even when we clear our search.
5. Icon & text when no applications are present do not seem center aligned. Additionally icon for no applications seems to be stretched.
6. Icons when there are no packages & workflows are similar. Should we have different icons for them?

### Steps To Reproduce

1. Go to https://ce-29282.dp.appsmith.com/, https://ee-2987.dp.appsmith.com/
2. Login & land on the home page.

### Environment

Deploy Preview

### Issue video log

https://www.loom.com/share/e3b4cdfe1c984b8591cbc0923abbf534

### Version

Cloud

**Comment by shadabbuchh** [comment]
Name of the bottom most workspace gets clipped. 
<img width="438" alt="Screenshot 2024-01-16 at 5 37 28 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/28215749-537f-4384-9c7b-13f03d885a04">

**Comment by btsgh** [comment]
There should be a hamburger menu next to the workspace name on the left pane, so that we can delete the workspace easily, rather than having to navigate far left to the workspace kebab menu. 

<img width="1434" alt="hamburgmenu" src="https://github.com/appsmithorg/appsmith/assets/101863839/329cd9ac-e896-416e-95ad-cac072ca79a0">

**Comment by deepikaappsmith** [comment]
#5 in description - https://app.zeplin.io/project/653f7de4c1d563203f817bce/screen/653f7eebadfd2f2035ba469e design link, it is centrally aligned to the left component and not the complete page.
#6 - the respective team will remove empty state for package and workflows.
#7 - template page opens when we use the templates route.

The search functionality is intended to work across workspaces.

**Comment by deepikaappsmith** [comment]
@btsgh - We don't have the hamburger menu at the moment and wasn't a part of this project. Will check if this is required, if yes will take it into further iteration.
