### ISSUE TITLE
[Bug]: The scrolling action on pages section is not working as expected

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The scrolling action on pages section is not working as expected

### Steps To Reproduce

1. go to release.app.appsmith.com
2. Open any one app which has 6 pages
3. Now scroll to end of the page and select page 5 
4. The page 5 gets selected but user gets scrolled to page 1 

### Environment

Release

### Version

v1.9.60

**Comment by btsgh** [comment]
This is working fine on Prod.
