### ISSUE TITLE
[Feature]: Multil select in a table

### ISSUE THREAD

**Issue by anhsao104** [appsmithorg/appsmith#30379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

My database table had a column that contained multiple selects, like a category that can have multiple subcategories. But in the table, there is no column type like multiple select. I think we need to develop this new feature

### Why should this be worked on?

it will be very helpful in development.

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #16026
