### ISSUE TITLE
[Bug]: With particular permissions given, the UI for the kebab menu is broken in Home page.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a role, when I give all application resource permissions for an application, except make public and export, and login with a user with this role, the kebab menu is still seen next to Create New on the Home Page, and on clicking it, it comes up empty

### Steps To Reproduce
<img width="1433" alt="Screenshot 2024-01-17 at 12 53 11 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/89ab0754-0af8-4666-aeb4-111ae256d1ec">

Expected Behavior - the kebab menu should not be present at all in this case.

### Environment

Deploy Preview

### Version

Cloud

**Comment by ankitsrivas14** [comment]
@btsgh - Fixed and deployed.

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
