### ISSUE TITLE
[Bug]: Adding feature in table is error now

### ISSUE THREAD

**Issue by anhsao104** [appsmithorg/appsmith#30382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I enable feature pagination and use a table,. As I stand on the first page, I select the "Add new row" button. Then everything is alright.
But when I am on another page, e.g., the last page, I cannot add a new row.

### Steps To Reproduce

1. Go to the last page in the list
2. Click to 'Add a new row' button
3. There is no new row for me to edit.

### Environment

Deploy Preview

### Version

Self hosted v1.9.58

**Comment by carinanfonseca** [comment]
Closing this issue because it is not reproducible in production.
