### ISSUE TITLE
[Bug]: Groups and Roles page do not load at all, though for particular Groups and Roles Edit+View access is given

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a role, when I give all application resource permissions for an application, except make public and export, and for a custom role I give edit and view permission, as well as give edit and view for a group, on logging in with a user having the above role, When I click on the Settings CTA, the Groups and Roles page do not load at all.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/5d066266-3186-4cb7-93cb-d075e015788b

### Environment

Deploy Preview

### Version

Cloud

**Comment by ankitsrivas14** [comment]
Please check 
https://www.loom.com/share/eada8e6012d74b3a8c5d7c76e97d54f6
@btsgh

**Comment by btsgh** [comment]
Hi @ankitsrivas14  - we are still able to reproduce this issue. Sometimes it shows the loader on refreshing the page, even though first time it loads. Can you try that. cc: @deepikaappsmith

**Comment by ankitsrivas14** [comment]
Tried one more time.
https://www.loom.com/share/b811c0cd477c4dc6a7282f2d9082e45b
cc: @deepikaappsmith 

@btsgh - `user-groups` API is responsible for getting the data on Groups page. It would help if you open the Network tab and filter for this API, and then provide a screen recording. 
In the above recording you added, this API is not visible.

<img width="314" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/dedf20fa-afc0-4507-b448-c1ef4c800b8a">

And `roles` API for the Roles page
<img width="289" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/bd0510a7-615e-49de-8a5f-fe89ba040cce">

**Comment by btsgh** [comment]
Hi @ankitsrivas14 - here is a recording. i could not find user-groups, instead found only groups .. Hope this helps
https://github.com/appsmithorg/appsmith/assets/101863839/f166aafa-5b08-4a91-b79b-0ea9a8b55e95

**Comment by dipyamanbiswas07** [comment]
I've tried reproducing this but it seems to work fine on the DP, @btsgh @deepikaappsmith  please check.

https://github.com/appsmithorg/appsmith/assets/26247571/a390a191-bbf8-4c5d-850d-f14ff3c0c40f

**Comment by deepikaappsmith** [comment]
Changed the priority after discussing with @btsgh as it not occurring for everyone

**Comment by btsgh** [comment]
This is no longer happening - refer slack [thread](https://theappsmith.slack.com/archives/C04H5PFRN1H/p1706154361115059?thread_ts=1706015560.014209&cid=C04H5PFRN1H).
