### ISSUE TITLE
[Bug]: Try Guided Tour option comes up in this scenario, but nothing opens when we click on it.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a role, Give only Edit and View access to a workspace, in Application Resources. Login with a user having this role. Note that the Try Guided Tour option is seen in the Help menu, however nothing happens on clicking it

Expected behavior - the Try Guided Tour option itself should not be present. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/803cdf30-043e-4fe2-b65c-4bfa114a9249

### Environment

Deploy Preview

### Version

Cloud

**Comment by deepikaappsmith** [comment]
@dipyamanbiswas07 - remove the Guided tour option altogether.

**Comment by RakshaKShetty** [comment]
This issue is fixed closing the issue
