### ISSUE TITLE
[Bug]: Invoking a S3 List Query errors out in the following scenario

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a role, when I give all application resource permissions for an application, except make public and export, and for a custom role I give edit and view permission, as well as give edit and view for a group, and Execute for Prod env, and Execute only for S3 DS, on logging in with a user having the above role, S3 List files query brings up an error message v[m] is undefined

### Steps To Reproduce

<img width="1255" alt="Screenshot 2024-01-17 at 1 39 14 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/4f101435-88b9-48a3-b59c-9e4ff2505e83">

https://github.com/appsmithorg/appsmith/assets/101863839/b2ef3ee4-5ace-4503-8b89-2b18033a775e

Note: This scenario erroring out is specific to the HomePage DP, and works fine on a local release-ee pull

### Environment

Deploy Preview

### Version

Cloud

**Comment by dipyamanbiswas07** [comment]
Unable to reproduce this @deepikaappsmith  @btsgh

**Comment by dipyamanbiswas07** [comment]
https://www.notion.so/appsmith/RBAC-fa566dd7442a44dbb32394e5e8d3e452?pvs=4

**Comment by btsgh** [comment]
Unable to reproduce it - maybe an intermittent issue, reduced the priority for now - will update here in case of any other findings cc: @dipyamanbiswas07

**Comment by btsgh** [comment]
Closing as not able to reproduce
