### ISSUE TITLE
Fix the empty state for preview data

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#30390]
Design here: https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3187-16310&mode=design&t=C3JU3bVGCdgcv7Gq-0

In the implementation, we don't have any padding and the text is not centered (screenshot attached)
<img width="1640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1hTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7990c5c60768cc2009bb329e6f5fb62601e36cb/Screenshot%202024-01-17%20at%2011.14.44.png" alt="Screenshot 2024-01-17 at 11.14.44.png" />

**Comment by rohan-arthur** [comment]
already fixed
