### ISSUE TITLE
[Bug] Enhancement : Query error message must be displayed to user with in a box 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3040]
Steps to reproduce:
1) Navigate to Datasource Pane 
2) Click on "Amazon S3"
3) Add credentials
4) Test and Save Datasource
5) Click on "Add Query"
6) Add inappropriate data
7) Click on "Run"
and observe

Observation:
It is observed that the query error is simply displayed in the pane 

Expectation:
It is expected that the query error must be displayed inside a box like that of success reply.

![Screenshot 2021-02-15 at 2 17 18 PM](https://user-images.githubusercontent.com/71753653/107933432-bd871b80-6fa4-11eb-91e1-7876877230b7.png)

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal assigning to you since it looks like a UI issue and would need to be re-assigned.

**Comment by Devedunkey** [comment]
Is anyone working on this issue? I would like to dive into AWS with Appsmith.

**Comment by nidhi-nair** [comment]
@Devedunkey This issue has more to do with the design of the query pane editor, to allow a seamless experience between success and error states of execution. The error message itself will likely remain the same, so it won't be touching any of the AWS APIs.

**Comment by hetunandu** [comment]
Will be fixed with #3629
