### ISSUE TITLE
[Bug]: Issues with the new homepage revamp on smaller screens (responsiveness)

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#30411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. The apps aren't taking up the entire width of the screen
2. The three-dot drop menu is missing
<img width="309" alt="image" src="https://github.com/appsmithorg/appsmith/assets/109572422/c487b796-9a1c-4ed6-bc1f-8e9ca0a9127a">

### Steps To Reproduce

1. Log in to DP
2. And notice the above issues in responsive mode

### Environment

Deploy Preview

### Version

Cloud

**Comment by dipyamanbiswas07** [comment]
![image](https://github.com/appsmithorg/appsmith/assets/26247571/d927e807-ad22-479d-b395-9a8bffeaa0b1)


3 Dot menu is not seen on release as well @laveena-en , @deepikaappsmith this is not part of the homepage changes, I'll fix the apps not taking the entire width of the screen

**Comment by laveena-en** [comment]
Verified! Changes look good.
