### ISSUE TITLE
[Bug]: On searching for a particular workspace, the apps present within it aren't displayed

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#30421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On searching for a particular workspace, the apps present within it aren't displayed. Instead, the `There are no apps in this workspace.` message is shown

### Steps To Reproduce

1. Login to Appsmith
2. Create a new workspace and create some apps within it
3. Search for the workspace by its name on the searchbar present on the homepage
4. Notice that the apps aren't displayed

### Environment

Production

### Issue video log

https://www.loom.com/share/a8b69b4a96f040fcbf126d4f4a09bb7b?sid=27c828df-05c7-4b68-897e-52d14f129818

### Version

Appsmith v1.9.61

**Comment by laveena-en** [comment]
@rohan-arthur Tagging you since the TM pod's label came up. Please re-assign if I'm mistaken.

**Comment by laveena-en** [comment]
Related cypress test is also failing `cypress/e2e/Regression/ClientSide/Workspace/ShareAppTests_Spec.ts`
cc: @sarojsarab

**Comment by deepika-appsmith** [comment]
the way the apps and workspaces are displayed has changed. Also, the search functionality has changed about a month ago. I don't think this bug is relevant anymore.
cc @btsgh @laveena-en
