### ISSUE TITLE
[Bug]: Many Appsmith app calls are failing

### ISSUE THREAD

**Issue by thebadking** [appsmithorg/appsmith#30431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a new application it does not resolve on the FE you need to refresh to see the newly generated app
<img width="343" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/2e4ccbe0-17fb-4d20-b268-d91793d75687">
after a long loading I get the " +" button back but no application
<img width="330" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/6e777ab9-c73c-431a-9db6-9e1b18c28bcd">

only after refreshing the page it will appear:
<img width="293" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/10710e32-6203-4c49-81a8-4b18353291e0">

when I generate a page using the wizzard and the default "users" dataset provided as an example by appsmith I get an error
<img width="703" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/4f22fb75-c5bb-4ed0-a102-0b49e589fe08">

### Steps To Reproduce

1.go to cloud Appsmith, applications dashboard and click on "New +" wait for the button to resolve, the application won't show

2.go the app editor
<img width="758" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/dae05407-755f-4f8b-9bbf-c2334c80c30a">

click on generate page
<img width="714" alt="image" src="https://github.com/appsmithorg/appsmith/assets/53491595/dfad7e27-ab3b-4a62-915f-1402896a1d3a">

### Environment

Production

### Version

Cloud

**Comment by thebadking** [comment]
I keep finding more and more errors, I think your production is completely broken

**Comment by areyabhishek** [comment]
HI! We are facing a temporary problem with MongoDB Atlas service right now. Their services have degraded. We expect to be back online soon.

**Comment by pranavkanade** [comment]
@thebadking This is a known issue and the team is working on this. We'll update on discord and here within next 6 hours. https://discord.com/channels/725602949748752515/1197466028175802388

**Comment by mohanarpit** [comment]
This has now been resolved. This happened for 2 reasons: 
1. MongoDB Atlas had a service degradation. Please check status.mongodb.com for details. This affected Appsmith as well.
2. MongoDB indexes weren't being honored because of a change to the collation type in the query. This is now fixed. 

Appsmith cloud performance is back to normal. Hence, closing the ticket.

**Comment by thebadking** [comment]
Solved
