### ISSUE TITLE
[Bug] Default Tab1 gets deleted from the entity explorer 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3044]
Steps to reproduce:
1)  Add a Tabs widget on the canvas
2) Delete Default Tab2  from the Property pane 
3)  Delete Default Tab1  from the Entity Explorer
and observe

Observation:
It is observed that the mandatory default Tab1 can be delete from the  Entity Explorer however can not be deleted from the Property pane 

Expectation :
User should not be allowed to delete the Default Tab1 from Entity explorer 

Video:
https://www.loom.com/share/2aba828041434f45abb0f303eca75d84

**Comment by riodeuno** [comment]
@prapullac @vivekverma2312 can you check if this is still and issue today. I'm asking because we've made changes to the TabsWidget in April and this might be related.

**Comment by prapullac** [comment]
@riodeuno : The is issue is fixed and the user is unable to delete the tab (Property pane and Entity explorer)when its only tab that exsist on the widget.
Hence we can close the issue
