### ISSUE TITLE
[Feature] Infinite scrolling on list widget

### ISSUE THREAD

**Issue by umeshdiwekarrapiddata** [appsmithorg/appsmith#30447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Do we have any plan for implementing the infinite scroll for the list widget.

### Why should this be worked on?

I have use case where I don't want any pagination

**Comment by pranavkanade** [comment]
Duplicate - https://github.com/appsmithorg/appsmith/issues/6293

**Comment by parlt** [comment]
Please reopen the ticket
