### ISSUE TITLE
[Feature] Modal issues

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3047]
The modal widget is reported to have the following issues:
- [ ] Modal form type does not work as a form. The name is misleading
- [x] Default modal form type size is too big for a small form.
- [ ] Dragging and dropping large widgets like form into the modal is inconvenient
- [x] Modal is not re-sizable
- [ ] Modal does not have the context of an entity whose trigger action was to open the modal.
- [ ] The contents of a modal don't get copied and pasted easily.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno for the resetting thing, the real solution should be to enable reset as a property on all buttons and to reset any parent container

**Comment by Nikhil-Nandagopal** [comment]
Closing this in favor of #3850
