### ISSUE TITLE
[Bug]: Onboarding flow isn't seen when a user has been invited to a workspace before they have signed up.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#30489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Onboarding flow isn't seen when a user has been invited to a WS before they have signed up via the `/user/signup` path

### Steps To Reproduce

1. Invite a user to a particular workspace. Ensure that they haven't signed up already
2. Now, sign up as a new user via the `/user/signup` path
3. Notice that the onboarding flow isnt shown to the new user

### Environment

Production

### Issue video log

https://www.loom.com/share/5baca13858f041bbbe40c1af67e024a6?sid=f76d76cd-3a4a-428e-9670-9b2f1ebcc2f6

### Version

Appsmith v1.9.62

**Comment by rohan-arthur** [comment]
@laveena-en sorry, I had the wrong understanding. I confirmed that the requirement is indeed that the onboarding flow should not be shown for an invited user, whether they access appsmith via the invite link or via `/user/signup`
