### ISSUE TITLE
[Bug]: Scroll Position Not Resetting When Navigating Between Pages

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#30481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user is on one page and has scrolled down, then navigates to another page either by clicking the respective page in the Navigation bar or by clicking a button where the NavigateTo method was used, the user is not directed to the top of the second page, but to a scrolled down position. It seems that the scroll position does not get reset when navigating between pages.

### Steps To Reproduce

1. Create 2 pages and add some widgets so that the content is longer and you need to scroll to get to the bottom of the pages.
2. Deploy the app.
3. Go to the first page and scroll to the bottom, then click on the second page in the navigation bar (or use a button placed at the bottom of the page with the `navigateTo` method).
4. Note that you will be directed lower on the second page and have to scroll up to reach the top.

### Public Sample App

https://app.appsmith.com/app/navigateto-scroll-issue/page1-65aa86044ffa034b7c300ccd

### Environment

Production

### Issue video log

https://www.loom.com/share/df64b68189ef4128a600e0896525a05b

### Version

v1.9.62

**Comment by davd-edia** [comment]
Hey. This disorients users, when a page is longer and the top is out of view. When you navigate to another page you don't see where you are anymore... nav bar is not visible, any header/title is not visible. And it's not expected behavior from a webpage.

**Comment by Nikhil-Nandagopal** [comment]
@davd-edia we're fixing this
