### ISSUE TITLE
[Bug]: Commits show up in modal even after successful completion of auto-commit, and + sign indicating no new commits

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On opening an old git connected app [6month old], auto commit progress bar goes through without any hiccups, and the + sigh shows no changes to be committed. However, on clicking on the plus sign to invoke the git modal, it shows up with changes and asks users to commit. 

Expected behavior - it should ideally have no changes to commit. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/093fbfdc-15e6-4ab3-9c33-a70f86375a64

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
Application is shared with @nayan-rafiq  - here is the [url](https://release.app.appsmith.com/app/untitled-application-26/page1-649e7f6cf784ae71167625fd?branch=master)

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by brayn003** [comment]
This should be resolved with the count fix in the granular status feature. Closing this for now. Please reopen if the issue reoccurs
