### ISSUE TITLE
[Bug]: Master branch shows no commits, while child Branch shows more commits in modal than the number showing up in the plus sign

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Master branch shows no changes to commit, even when the modal has changes. Child branch shows 2 changes to commit, where as the modal shows up with a total of 5 changes

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/775c791a-a689-4f95-95af-7665dc77f1f9

https://github.com/appsmithorg/appsmith/assets/101863839/0f327806-2bc3-4496-a4bb-ea0c96819686

### Environment

Release

### Version

Cloud

**Comment by brayn003** [comment]
This should be resolved with the new git status changes. Also, verified this on app.appsmith.com, seems to work fine. Closing this
