### ISSUE TITLE
[Bug]: Creating a new workspace is copying default application from existing workspace

### ISSUE THREAD

**Issue by dipyamanbiswas07** [appsmithorg/appsmith#30502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a new workspace is copying default application from existing workspace

### Steps To Reproduce

Creating a new workspace is copying default application from the existing workspace & upon refresh all are lost. Not sure how this test passed previously.

### Environment

Deploy Preview

### Version

DP

**Comment by ankitsrivas14** [comment]
@dipyamanbiswas07 - Could you please add a recording or steps to repro?
https://www.loom.com/share/08d6dd17a27a43d5bb417fe8c5accd24

**Comment by dipyamanbiswas07** [comment]
https://theappsmith.slack.com/archives/C04H5PFRN1H/p1705912465780899?thread_ts=1705554428.041219&cid=C04H5PFRN1H

**Comment by btsgh** [comment]
FYI - This issue is happening with non-appsmith users @ankitsrivas14 
This is not happening for users like [aparna+1@appsmith.com](mailto:aparna+1@appsmith.com). It is happening for users like [test1@abcd.com](http://test1.abcd.com/)

**Comment by RakshaKShetty** [comment]
The issue is fixed
