### ISSUE TITLE
[Bug]: Forking expects the particular dialog requesting for workspace which is not appearing.

### ISSUE THREAD

**Issue by dipyamanbiswas07** [appsmithorg/appsmith#30501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

/Templates/Fork_Template_spec.js is failing because when forking its expecting the below dialog which is not appearing & hence failure in HomePage revamp PR.

![image](https://github.com/appsmithorg/appsmith/assets/26247571/9d73c6b9-e471-4f31-93f1-e46c8a37c811)

### Steps To Reproduce

Fork Application

### Environment

Deploy Preview

### Version

DP

**Comment by deepikaappsmith** [comment]
This is fixed with homepage changes and available on prod
