### ISSUE TITLE
Use WDS components and tokens in WDS Table widget body

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#30500]

**Comment by somangshu** [comment]
@KelvinOm whats the delay here? This has been pending for 3 sprints now!

**Comment by KelvinOm** [comment]
@somangshu I can't get started on this yet because sufficient focus work time is needed for this task, while I don't have it yet. It takes a lot of time right now to meetings, organising the work of the team, activity related to hiring, reviewing PRs, fix minor bugs, etc.

**Comment by somangshu** [comment]
1. Can @jsartisan take up the implementation here? 
2. @andreevanatasha this still hold the priority?

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/30500?planning-poker) with Zenhub @ichik @jsartisan
