### ISSUE TITLE
[Bug]: Internal server error on oauth2 request

### ISSUE THREAD

**Issue by jancoow** [appsmithorg/appsmith#30515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm building an app to generate a shipping label using the UPS API. This API uses oauth2 
I configured it correctly, and it seems to authenticate the service successfully. 

However, I do get this error when I press 'save & authorize' in a new browser tab with the following JSON: 

```
{
responseMeta: {
status: 500,
success: false,
error: {
code: "AE-APP-5000",
title: "Internal server error",
message: "Internal server error while processing request",
errorType: "INTERNAL_ERROR"
}
},
errorDisplay: "AE-APP-5000: Internal server error while processing request"
}
```

When editing the service again, it still says 'Datasource not authorized'. However, when I execute an API call it sends a valid bearer token. 

 Why do I get this error? 

The problem is that the bearer token expires after some time. However, when re-executing the api call it won't automatically make a new oauth requests. The app will show an unauthorized error on the api. The only way to fix this is go back to the datasource, make a change in the form so I can press 'save & authorize' again. 

How can I solve this? 

### Steps To Reproduce

1. Create OAuth 2.0 API source with grant type client credentials 
2. Press 'save & authorize' 

### Environment

Production

### Version

Appsmith v1.9.58

**Comment by jancoow** [comment]
I use: 

https://developer.ups.com/api/reference?loc=en_US#tag/OAuthClientCredentials_other

Client Credentials Grant Type

**Comment by jancoow** [comment]
Also, when  I manually want to generate a token with a regular api request,  I am receiving the error: 
"Your API failed to execute:
org.springframework.web.reactive.function.client.WebClientRequestException: Validation failed for header 'Authorization'"

So there is no way for me to resolve this problem.

**Comment by sneha122** [comment]
Thanks @jancoow for reporting this problem. In order to understand issue further, can you please check if UPS oauth supports refresh token flow for client credentials grant type?

**Comment by Nikhil-Nandagopal** [comment]
@jancoow please try using the authorization code grant type, I believe that will return a refresh token and ensure that it doesn't expire

**Comment by jancoow** [comment]
> @jancoow please try using the authorization code grant type, I believe that will return a refresh token and ensure that it doesn't expire. I'm closing this for now. Let us know if it still does not work

I'm unable to use the authorization code grant type because UPS keeps returning an error that the redirect uri is invalid.

**Comment by jancoow** [comment]
Apperently I got a org.springframework.web.reactive.function.client.WebClientRequestException: Validation failed for header 'Authorization'" error when you have a newline character (enter) in a header parameter. Very clear message for such a simple error.

**Comment by Nikhil-Nandagopal** [comment]
@jancoow sorry that error message certainly needs to be improved. It's not handled and java is just throwing up it's exception. Is this now working for you or is it still a problem?

**Comment by jancoow** [comment]
> @jancoow sorry that error message certainly needs to be improved. It's not handled and java is just throwing up it's exception. Is this now working for you or is it still a problem?

I'm doing manual the oauth request now. This works fine. I'm still unable to use the automatic oauth flow which is build in due the 500 error. There is no way for me to debug what I am doing wrong.

**Comment by rwariyar-docunav** [comment]
Seeing the same issue with a different OAuth provider. Looking forward to this fix. Thx.

**Comment by ranjwarrior** [comment]
Seeing the same error with a different OAuth provider (custom internal app). Looking forward to the fix. Thx.

**Comment by Nikhil-Nandagopal** [comment]
We had a bug in our client credentials flow. This is now fixed in the next release.
#31207
