### ISSUE TITLE
[Feature]: Remove the account update screen for SAML

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#30520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a user first logs into the instance they are presented with an `Update Account Info` screen. I would like to disable this feature for my users.

### Why should this be worked on?

The account info should be pulled from our SSO provider instead.

**Comment by mmcallister-selkirk** [comment]
We would also like to see this feature.

**Comment by Nikhil-Nandagopal** [comment]
@mmcallister-selkirk can you share a video of this issue? If a user signs up with SSO they should not see any screen with account information

**Comment by mmcallister-selkirk** [comment]
Hi @Nikhil-Nandagopal, the first video shows the initial login, after adding a new user to the AD group and in Appsmith.  The second video shows the second login attempt, and the error that appears has the bad password that was entered in the 'Update Account Information' window.  This instance is 1.9.35 so maybe its already been fixed?

https://github.com/appsmithorg/appsmith/assets/121312970/d9a53f46-d7cd-451b-ac7c-68fb0c45f73d
https://github.com/appsmithorg/appsmith/assets/121312970/9cd60599-a2f5-4585-b0b3-47a04300be86

**Comment by Nikhil-Nandagopal** [comment]
@mmcallister-selkirk thanks for the info! We'll look into prioritising this.

**Comment by mmcallister-selkirk** [comment]
Hi @Nikhil-Nandagopal, I tested again on 1.9.60 and saw the same 'Update Account Information' screen on initial login.  Thanks for looking at this!

**Comment by pratapaprasanna** [comment]
Hey I did this and it worked.

* Get keycloak credentials
      * exec into the docker container with `docker exec -it -u root appsmith bash`
      * cat /appsmith-stacks/configuration/docker.env | grep -i keycloak  make a note of the credentials visit [https://](https://l/)<domain_name>/auth login with the credentials noted in the  previous step
       * Select appsmith realm as shown in the picture <OrangeMarker>
       * select user profile and Delete firstName and lastName as shown <BlueMarker> and going forward any new user who signs up with SAML SSO will not be asked for firstname and lastName
       
![image](https://github.com/appsmithorg/appsmith/assets/15846947/d81610ff-8f75-4115-979d-7c32fbc89534)

**Comment by infinitetrooper** [comment]
@pratapaprasanna  - In your config, will the screen not be shown at all or only will it be still shown for the userName (email) field?

**Comment by mmcallister-selkirk** [comment]
Hi, I was wondering why this was closed?  I'm still seeing the Update Account Information screen when a user first logs in.
