### ISSUE TITLE
Remove unnecessary space between form and the CTA for GSheets in the datasource review form (onboarding step)

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#30523]
Problem:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeC9wQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e0f9af90f233e63ff74e34b84df071519574bf9/Unecessary%20space.mov)

Solution: 
- Remove the unnecessary space ([design](https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=5340-6425&mode=design&t=0EXdE30l5U090Tzc-0))

Additional improvements (also presented in the previous design link)
- Keep the title "Connect data" and supplementary test "Your data's security is our priority."
- Replace the current dropdown by radio buttons.
- Move the callout to after the permissions | scope property. 
- Limit the width of the white section

**Comment by rohan-arthur** [comment]
screenshot of the desired design:
![Screenshot 2024-08-06 at 15 25 42](https://github.com/user-attachments/assets/f4a66cef-2402-47ed-b2a4-b94cd0740b6d)

**Comment by Shivam-z** [comment]
@rohan-arthur picking up this task
