### ISSUE TITLE
[Bug]: Git app, commit number shows up as 1, while the modal shows 3 commits

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On a branch, I make application forkable [Share and embed], I change Theme, I create a new page and add a few widgets. and then refresh the page. Now I see that the count on the plus sign shows up as 1, but on invoking the modal, the number of changes show up as 3.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/9d783dcf-9f77-4737-aa25-578faa72302c

### Environment

Production

### Version

Release

**Comment by btsgh** [comment]
Application [url](https://release.app.appsmith.com/app/oldapp-dstesting1-9-24/oauth20-65af3230129f496d4bb1dc13?branch=master)

Shared with @nayan-rafiq  and @brayn003

**Comment by RakshaKShetty** [comment]
<img width="838" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/baf2d83f-4504-4cb4-8372-969a1c1875fd">
