### ISSUE TITLE
[Bug]: Hard coded host port for RTS service

### ISSUE THREAD

**Issue by josueneo** [appsmithorg/appsmith#30548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have installed RTS server separately and I noticed the RTS service host is hardcoded causing the Backend service to always call to localhost even if there is no RTS there.

Is this intended by design?

https://github.com/appsmithorg/appsmith/blob/c2dc2bb35b490f3536817a4c7899b965665a1ddc/app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java#L136-L138

### Steps To Reproduce

General design question

### Environment

Production

### Version

Latest

**Comment by pranavkanade** [comment]
@josueneo Can you give some more context around the issue - Why are using the RTS server separately? We officially recommend a single container setup to all our users.

I'd also like to understand the use case here. How does custom port help you?

**Comment by Nikhil-Nandagopal** [comment]
@josueneo we're not exactly sure since we didn't create or manage that helm chart. Could you try our official documented method of deployment?
https://docs.appsmith.com/getting-started/setup/installation-guides/kubernetes

**Comment by josueneo** [comment]
Tested with official Helm chart, and works without issues, however, I will leave this up to you and you can close this issue, don't you think hardcoding the url is not a good practice?

**Comment by sharat87** [comment]
Hey @josueneo, thank you for confirming. Glad that it's working for you now.

I agree that hard-coding things in general is a bad practice, but too much configuration means too many moving pieces and too many combinations of configurations to test. I don't think we should take no-hard-coding as a hard rule. In this case in particular, we don't expect there to be any reason to have any other port for RTS, in official deployment methods, so we don't make it configurable. Hope you understand. Thank you.

**Comment by hendramaulana** [comment]
The bug is back again
https://github.com/search?q=repo%3Aappsmithorg%2Fappsmith+BASE_API_URL&type=code

<img width="446" height="60" alt="Image" src="https://github.com/user-attachments/assets/4824928d-beb2-41de-a031-66a27dd4bb83" />
