### ISSUE TITLE
[Feature]: Logging of user actions and data changes

### ISSUE THREAD

**Issue by Eudod** [appsmithorg/appsmith#30545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have a small CRM built on Appsmith. It has user profiles management and transactions (payments) management parts.
When a user details got updated or payment transaction added or modified, those actions have to be logged for internal control and compliance purposes. This requirement is quite common for many apps, I believe.
For example [Directus](https://v8.docs.directus.io/guides/accountability.html#system-fields) has such a feature out of the box - they log every data change request if an admin enables this in system settings.
For now I have a function which stores the form data in local storage and push this and the updated data into the log. But this solution is not scalable and prone to errors. 
 I.e. when I update or delete a record a the table, I want the app to store in the log the data before and after modification. 

### Why should this be worked on?

This is one of the fundamental features about system observability and compliance.
Thanks in advance for considering this request!

**Comment by Nikhil-Nandagopal** [comment]
@Eudod we already have audit logs available in our business edition.
https://docs.appsmith.com/advanced-concepts/audit-logs

This should meet your needs

**Comment by fitu86** [comment]
Thank you for sharing your CRM requirements. It's understandable that you need to log user profile updates and payment transactions for internal control and compliance purposes. While Directus offers a logging feature out of the box, it's important to note that its approach may not align perfectly with your needs.Directus logs every data change request if enabled by an admin in system settings, but this logging mechanism operates within the Directus system itself. As a result, if modifications are made directly to the database outside of Directus, such as through manual queries or database tools, these changes may not be captured in Directus' logs. Additionally, if you're looking for a scalable and centralized solution, Directus' logging feature may not provide the flexibility and control you require.Instead, consider implementing a centralized "activity" table within your CRM application. This approach involves designing an API endpoint or middleware layer that intercepts and logs all relevant data modifications, regardless of whether they occur through user interactions in the CRM interface or direct database operations. By centralizing your logging logic within your CRM application, you can ensure that all data changes are captured consistently and comprehensively, regardless of their origin.A single "activity" table can store records of all relevant events, including user profile updates and payment transactions, along with metadata such as timestamps, user IDs, and details of the changes made. This provides a unified and scalable solution for system observability and compliance, allowing you to easily monitor and analyze activity across your CRM application.In summary, while Directus offers a logging feature, a centralized "activity" table within your CRM application may better suit your requirements for system observability and compliance. This approach provides greater flexibility, control, and scalability, ensuring that all data changes are reliably logged for internal control and compliance purposes.
