### ISSUE TITLE
[Bug]: In the release customer portal we are seeing the error message in the Billing and usage tab

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the release customer portal we are seeing the error message in the Billing and usage tab
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/3efecf67-863e-4d46-a332-1ccbd3aa4adb">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/eff5e71d-a839-45e9-ace8-a700fdbf86ac">

### Steps To Reproduce

1. go to https://release-customer.appsmith.com/
2. sign in as ferajoy189@grassdev.com
3. password : Appsmith@123
4. Now click on Billing and usage tab
5. The usage section is displayed with error

### Environment

Production

### Version

v1.10

**Comment by deepikaappsmith** [comment]
@RakshaKShetty @btsgh - can you test this once, the issue from Togai on staging is resolved.

**Comment by RakshaKShetty** [comment]
@deepikaappsmith Seeing this issue again this weeks regression along with the error on customer pportal i am not seeing the usage capture on the togais sandbox attaching the screenshot here
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/1e0e76ef-cecb-402f-aaa9-7c6b71f39c23">

**Comment by RakshaKShetty** [comment]
Closing the issue for now as the data is displaying in customer portal now but will track same in next regression as we faced this continuously twice in weekly regressions
