### ISSUE TITLE
Task: IDE Widget Selection updates

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#30578]
Update the following functionalities related to Widget Selections:

1. Keep showing the widget drawer after dropping a widget
We saw in user testing that selecting a widget slows down the user when they are trying to add multiple widgets. Since the IDE will switch to the widget list on selecting a widget (when dropped), the user has to click back on the new widget button to add another widget. By still showing the widget drawer when dropped, we are avoiding this issue and following the principle of only updating IDE states based on user actions

**Comment by riodeuno** [comment]
@hetunandu Could you elaborate on why we need point 1 in the description?
