### ISSUE TITLE
[Bug]: Datasource icons are missing on templates when the user signs up via the `Start with Templates` flow

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#30586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Datasource icons are missing on templates when the user signs up via the `Start with Templates` flow

![image](https://github.com/appsmithorg/appsmith/assets/109572422/5de7c03c-47e4-4631-89a5-2cf3c8fae1cc)
![image](https://github.com/appsmithorg/appsmith/assets/109572422/90a4cf29-f492-4023-8ad6-41ae9c008376)

### Steps To Reproduce

1. Sign up as a new user
2. Choose to `Start with templates`
3. Notice that the icons are missing on the template cards and template info page

### Environment

Production

### Version

Cloud

**Comment by rahulbarwal** [comment]
`Start with template` is no longer an option. We will create a task to clean up this from code as well.
