### ISSUE TITLE
[Bug]: Deleting app frm inside the application does not immediately reflect on the workspce

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I delete an app from inside an application, on being redirected to the workspace, the app still seems visible on the workspace. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/92c35523-78e4-425c-b03f-b5b56a12f0b4

### Environment

Production

### Version

Cloud

**Comment by deepikaappsmith** [comment]
@btsgh - can you please test this on our release environment? with new homepage I don't see this issue anymore

**Comment by btsgh** [comment]
Not seeing this issue with the new home page experience .. closing it out
