### ISSUE TITLE
[Bug]: Skeleton loader does not have a card for the initial load of the app - Homepage Revamp

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#30591]
### SubTasks

Skeleton loader does not have a card for the initial load of the app

<img width="1107" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/e6b2ac16-6cb3-4769-b6aa-581eff245c5d">

**Comment by deepikaappsmith** [comment]
this was fixed with homepage changes
