### ISSUE TITLE
[Bug] Adding a long organisation name does not get truncated on editing from the organisational setting page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3061]
Steps to reproduce:
1) Navigate to Home page 
2) Click on organisation dropdown 
3) Click on Rename of organisation
4) Add a long name to the organisation
5) Navigate to organisational Setting
and observe the organisation name 

Observation:
It is observed that the organisation name is not truncated 

Expectation:
It is expected that when the organisational name is long it needs to be truncated

![Screenshot 2021-02-16 at 4 22 42 PM](https://user-images.githubusercontent.com/71753653/108053545-8df31480-7073-11eb-9dcf-3ca5c4c03d67.png)

**Comment by varenaggarwal** [comment]
I'll like to take this up
/assign

**Comment by mohanarpit** [comment]
@varenaggarwal Welcome to the Appsmith community! It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md).

**Comment by Nikhil-Nandagopal** [comment]
Hey, @varenaggarwal I haven't seen a PR for this issue so I'm unassigning this from you. Feel free to come back and pick up one of our many open-good first issues! :)

**Comment by prapullac** [comment]
The long names are displayed to user in the dots format indicating the name is long
