### ISSUE TITLE
[Bug]: The DSL changes seems to be displayed in both system genrated commit and Users first commit

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The DSL changes seems to be displayed in both system generated commit and Users first commit
system generated commit
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/b73c60b5-9dc0-444b-a2a0-7e13345d5c48">
first commit by user
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/5cd9f6c2-ae6d-4971-992b-3f4cd95671b4">

### Steps To Reproduce

1. Image we have upgraded from the instance from v1.9.35 to v1.10
2. When we check the system commit on page level we see the version Change commit
3. Now check the first commit that user has done
4. check the changes on pages 
5. we see the version change along with other changes
6. In the commits it looks like the version has been downgraded from the higher version which seems little off

### Environment

Release

### Version

v1.10

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by brayn003** [comment]
This should be resolved with the auto-commit fixes. Closing this for now, feel free to reopen if the issue re-occurs
