### ISSUE TITLE
[Bug]: No toast message displayed after auto commit is complete

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#30647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The design files show that a Toast message should be displayed once the auto commit is complete but right now we do not see the toast.

### Steps To Reproduce

1. take a local pull with " docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:v1.9.35"
2. Now import any bigger app
3. Now upgrade the instance keeping the old stack
4. docker run -d --name appsmith-ee -p 80:80 -p 9001:9001 -e APPSMITH_CLOUD_SERVICES_BASE_URL="https://release-cs.appsmith.com/" -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:release
5. now open the git connected app to auto commit bar is displayed

**Expected:** A toast message should be displayed indicating that the auto commit was successful.

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
