### ISSUE TITLE
[Bug]: undefined value in the bindings pane of explorer

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#30648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://www.notion.so/appsmith/Fix-the-bindings-that-show-undefined-values-23d6e18c1ebf4bd2856279ad221f89cf

### Steps To Reproduce

1. Add a Table widget
2. Bind data to it
3. Open the explorer, click on more option for table widget and select show bindings
4. Notice that all the binding values are `undefined`. 

### Environment

Production

### Version

1.9.61

**Comment by rohan-arthur** [comment]
related, maybe can be picked up separately: #30670
