### ISSUE TITLE
[Task]: GAC with workflow testing

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#30646]
### SubTasks

Testsmith link : https://github.com/appsmithorg/TestSmith/issues/2539

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/30646?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
