### ISSUE TITLE
[Bug]: WDS Modal critical issues

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#30653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Dealbreakers:**
- [x] While modal is open, when we click on the onClick handler for a child widget (Button Widget) in the property pane, the modal closes and one widget shows a crash. @riodeuno  - _this happens for any and all bindings on the modal widget property pane_

- [x] raised #33380
1. modal reopens if modal deletion + undo delete was followed by another widget's deletion and undo delete action
2. close icon is highlighted when modal deletion is undone

- [x] raised #33381

- [x]  Drop indicators work differently in modal @marks0351 raised #33318
https://www.loom.com/share/a322171f605047eb882aa8bae6f564f9

- [x] Modal widget cannot be opened via actions in preview and view mode. The system responds with an error when we trigger opening a modal by, for example, clicking a button widget. @riodeuno 

- [ ] Modal is trimmed off on edit mode and cuts off the entire last section on preview mode
![image](https://github.com/appsmithorg/appsmith/assets/79509062/78d884ef-3d7d-456c-91af-22da144131c6)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/207e56ea-806c-4c00-8b8b-a8e4b9a788f6)

- [x] raised #33382
https://www.loom.com/share/1cb06c325bf841d4868cdc2814586b2f?focus_title=1&muted=1&from_recorder=1 - @marks0351 

### Further exploration

We can go with the 1. as it seems like the more reasonable approach.
![Снимок экрана 2024-01-26 в 11 56 29](https://github.com/appsmithorg/appsmith/assets/103687/a8a74dd5-74d1-421b-808d-c753670f242b)

- Users can have two modal widgets open at the same time. Today, the stacking order is the order in which they're shown in the entity explorer. The solution is to make sure that the currently "selected" modal widget is at the top. However, due to the solution chosen in issue 1 above, the previously open modal will automatically close when a second modal is selected.
![Screenshot 2024-01-26 at 2 42 20 PM](https://github.com/appsmithorg/appsmith/assets/103687/cde9529f-8a86-4289-88b6-f6929f67e1e1)

**Done:**
- [x] Modal widget gets clipped in preview and view mode @marks0351 
https://github.com/appsmithorg/appsmith/assets/103687/81f491d4-f83e-41b9-a62a-1afae3ecea64

- [x] Modal selection is not consistent when opening a modal.
https://github.com/appsmithorg/appsmith/assets/103687/567b6cb3-36db-480a-87d6-331366d66458

- [x] Users can select non modal widgets from the entity explorer while a modal widget is open. There are two ways to solve for this:
  - Close the modal widget if a non modal widget is selected. 
  - Don't allow selecting a non modal widget if a modal widget is open

- [x]  unable to see highlights at times when the modal has a scroll.

- [x] https://www.notion.so/appsmith/widget-selection-QA-52a124d2e160488396b466fb1f6464f7?pvs=4#df3cf8bbfbf346d8a524e1dbd6fb7f4d @marks0351 

### Steps To Reproduce

Issue 1: Select a widget on the Main canvas while a modal is open from the property pane
Issue 2: Select another modal while one modal is open. Make sure that the selected modal is shown before the open modal in the entity explorer.

### Environment

Deploy Preview

### Version

https://ce-28238.dp.appsmith.com/

**Comment by ramsaptami** [comment]
more issues: 
- [ ] https://www.loom.com/share/e0f52d46b14c4da6b446e47cad45a10d
- [ ] #33205

**Comment by ramsaptami** [comment]
@riodeuno sorry, which issue specifically here?

**Comment by marks0351** [comment]
@riodeuno if you are talking about not being able to type into the widget name search while a modal is open, then its been fixed by one of my last prs.
cc: @ramsaptami
