### ISSUE TITLE
[Bug]: Empty Input1.text evaluates as 'null' in Postgres query

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#30668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the last update a users query behavior has changed. When running the following query with an empty Input it now tries to insert `'null'` instead of an empty string. If they try saving to an INT column they get an error.

```sql
UPDATE table SET title = '{{InputTitle.text}}'
```

### Steps To Reproduce

1. Drag and drop an input widget onto the canvas.
2. Create an update query to update a text column Postgres datasource using this snippet: `UPDATE table SET title = '{{InputTitle.text}}'`. Replace `table` and `title` according to your test setup.
3. Run the query.
4. Observe that the updated row now has a value of "null" in the updated column.

### Environment

Production

### Version

Self-Hosted 1.9.61

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_50fh1o)

**Comment by Nikhil-Nandagopal** [comment]
@LagunaElectric they should remove the quotes if they are using prepared statements. Quotes will enforce a string type conversion. I'm not sure if this was a recent change. They were likely on a very old version
