### ISSUE TITLE
[Feature][Table element][Date column]Add format DD/MM/YYYY

### ISSUE THREAD

**Issue by hawisizu** [appsmithorg/appsmith#3068]
## Summary

I have in a postgres DB a date in the date format, so YYYY-MM-DD. The table element can read it of course, but not display it as I need it: DD/MM/YYYY

![image](https://user-images.githubusercontent.com/48994518/108080960-b6c5da80-7070-11eb-93e0-66b26c9aaccd.png)

Solution would be to either add this format or let the user chose their format. 

This format DD/MM/YYYY is the most common in Europe and is already implemented in the date picker, so in my opinion it would make sense to have it in all compenents.

**Comment by Nikhil-Nandagopal** [comment]
@hawisizu thank you for this feature request. This is fixed in our new table widget and should be out next week. To get around this, you can map over your data and manually format the date.
{{ API.data.map((row) => {
     return {
        ...row,
        date: moment(row.date, "YYYY-MM-DD").format("DD/MM/YYYY")
     }
   })
}}. Hope this helps 😄

**Comment by hawisizu** [comment]
Yes perfect! 

For once that I open a request before asking in support :), turns out no request was needed.... 

thanks!
