### ISSUE TITLE
[Bug]: Applications appear in the search results for users without proper access.

### ISSUE THREAD

**Issue by deepikaappsmith** [appsmithorg/appsmith#30689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With new search functionality added, we happen to see the apps in list which user doesn't have access to

<img width="1840" alt="Screenshot 2024-01-29 at 11 39 57 AM" src="https://github.com/appsmithorg/appsmith/assets/130959931/662ce65c-23ab-4b84-a5b5-63002a5db2c0">

### Steps To Reproduce

1. login to appsmith cloud
2. go to search and type app
3. you will see the list of apps user doesn't have access to.

### Environment

Release

### Version

Cloud - Appsmith v1.10.0-SNAPSHOT

**Comment by shadabbuchh** [comment]
Verified in release. Working fine now
<img width="1440" alt="Screenshot 2024-01-30 at 12 45 44 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/26009115-69dc-4d2e-8d56-49d31e58fc26">
