### ISSUE TITLE
[Bug]: table preview from schema fails if the table name contains a hyphen

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#30692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/94514895/2fe345cf-7e1d-4723-9461-8eda1501a6a2

### Steps To Reproduce

1. create two postgres tables, one with and one without hyphens. E.g., `test-with-hyphen` and `test`
2. ensure both tables contain some records
3. create a datasource on appsmith pointing to this db
4. check the schema preview - both the tables are shown in the schema
--> now see that the table preview works ok for table `test`, but preview for `test-with-hyphen` errors out as you can see in the attached video

### Environment

Production

### Version

Cloud

**Comment by woodmin** [comment]
This also applies to Self-hosted, not only Cloud

**Comment by raushan3737** [comment]
Hi @rohan-arthur  I am picking up this issue. I will add solution approach after debugging the code.

**Comment by raushan3737** [comment]
Hi @Nikhil-Nandagopal , @riteshkew , @rohan-arthur, I have submitted a PR that fixes the issue with table previews for tables containing hyphens in their names. Please review and proceed with the next steps.

Thank you

**Comment by rohan-arthur** [comment]
thank you, @raushan3737 for this! Would you please attach a video in the PR demoing and explaining the fix?

**Comment by raushan3737** [comment]
Hi @rohan-arthur , I have attached the video in the PR. Could you please check and review.
PR link:  https://github.com/appsmithorg/appsmith/pull/35391
