### ISSUE TITLE
[Bug]: When we try to change the logo of an application from a branch in a git connected app, Resource Not Found error pops up

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to change the logo of an application from a branch in a git connected app, Resource Not Found error pops up

### Steps To Reproduce

1. Open a git connected app
2. Go to a branch
3. Go to App Settings and go to the Navigation section, enable Show Logo
4. Change or add a logo
5. Note that a Resource not found error pops up
6. When we navigate away from this branch and get back to this branch, the Show Logo comes up as disabled

<img width="1431" alt="Screenshot 2024-01-29 at 3 23 37 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/5e53dee1-e15a-4562-bbcf-1c4f638f4957">

<img width="1416" alt="Screenshot 2024-01-29 at 3 23 25 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/25c9976c-1e9c-402e-91b6-10b20830c421">

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/ad5e0fd6-ad50-4994-8d47-33149789bb33
