### ISSUE TITLE
[Bug]: On upgrading to a higher version, all of the previous commits are seen as uncommitted changes.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#30716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On upgrading to a higher version, all of the previous commits are seen as uncommitted changes.

### Steps To Reproduce

1. Create an app and connect it to git. (Ensure that the app is created on an old version of appsmith. v1.9.35 in this case)
2. Make changes to the app and commit them
3. Next, either upgrade the instance or import the app onto latest release release
4. Notice that the previously committed changes are seen as uncommitted changes

### Environment

Deploy Preview

### Issue video log

https://www.loom.com/share/7faa5876c9574d84afefd7858415f3c7?sid=737185f2-6aac-4aa0-b268-8f85388f4ed4

### Version

Release

**Comment by nayan-rafiq** [comment]
In step 3, how you are importing the app to latest release? Is it import from Git?

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by brayn003** [comment]
This issue was occurring because of a feature flag issue. It is now resolved. Closing this for now, feel free to open if it re-occurs

**Comment by laveena-en** [comment]
This issue has been resolved
