### ISSUE TITLE
[Bug]: Bindings are not updated in widgets when the queries and jsobject names are refactored

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#30710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the entities names are refactored due to name clashing/duplicate names the bindings are not updated for widgets. 

### Environment

Production

### Version

Cloud

**Comment by rahulbarwal** [comment]
This should be fixed with our recent changes for the partial block api. We will confirm and close this.
