### ISSUE TITLE
[Bug]:When I git import old version of attached app into release - auto commit does not run, there is no system generated commit either

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For the attached application, when I git import old version into release, the auto commit does not run, and there is no system generated commit for the same. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/1c9938e3-b63a-48e8-b21a-a618fc2d3f0e

Imported application [url](https://release.app.appsmith.com/app/autocommit3/oauth20-65b246611f7b9934024955f8?branch=master)

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by brayn003** [comment]
This seems like a valid issue, on committing the uncommitted changes, I can see the changes include version increment.
Ideally auto-commit should have gotten triggered
Reference repo - https://github.com/btsgh/autocommit3
