### ISSUE TITLE
[Bug]: Rephrase the text that comes up when no workspaces are available

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#30748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Text on screen when no workspaces are available is not right. It asks the user to `try selecting one of them to access a workspace.` (how can the user select something when there is no workspace?)

<img width="1440" alt="Screenshot 2024-01-30 at 3 48 18 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/1e288228-3e36-4abb-8b86-6a59d4ba6a53">

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/
2. Delete all the workspaces

**Expected:** The text on the screen should be more appropriate instead of what we have right now.

### Environment

Release

### Version

Cloud

**Comment by laveena-en** [comment]
Also, on deleting a workspace, the `Oops! No workspace found` message is seen. Ideally the first workspace should get selected by default https://www.loom.com/share/266e6aeb6c8047b1b3a7f4817fa7e1d7?sid=092db7b4-0f03-43db-a6c0-e1aaba8b7d45

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
