### ISSUE TITLE
[Bug]: Even if we clear the search, the last searched item shows up in the dropdown

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Type a text in the search box, and manually delete it out by using delete or backspace. The search dropdown reappears with the last searched item

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/8bd97805-ccee-4f4b-a7b0-25fa898d48f8

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
