### ISSUE TITLE
[Bug]: Protected branch disables Dropdown and Select widgets. 

### ISSUE THREAD

**Issue by pchambless** [appsmithorg/appsmith#30756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I protect my 'main' branch, then try to utilize a Datepicker or Select widgets in a new JSONForm merged into 'main',  these widgets are frozen.  If I unprotect the branch they work again.  

The strange thing about this is, this is only happening for a JSONForm that I just added because my old regular form was outdated and was acting up.  I replaced it with the new JSONForm and that seems to be the only form that is disabled.  A spot check shows that other pre-existing widgets still function.

### Steps To Reproduce

1.  in feature branch - create a new JSON Form with DatePicker and Select widget fields.
2.  Merge this into the 'main' or 'master' branch
3.  Protect the 'main' or 'master' branch.
4.  Try to use the JSON form widget functionality.  For me they are frozen.
5.  Unprotect the 'main' or 'master' branch.
6.  The JSON form field functionality are now enabled.

### Environment

Production

### Version

Appsmith Community v1.9.61 - Self hosted.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_53bsb0)

**Comment by pchambless** [comment]
I just noticed another quirk which may be unintentional.  When I tried to create a branch from my protected **master** branch I was unable to do it until I unprotected my **master** branch.

**Comment by brayn003** [comment]
Seems like widget interactions are disabled when preview/protected flag is true. Will have to revisit why it was done like this in the first place

**Comment by Nikhil-Nandagopal** [comment]
@brayn003 @infinitetrooper ideally this should work just like preview mode

**Comment by infinitetrooper** [comment]
Closed with https://github.com/appsmithorg/appsmith/issues/34128
