### ISSUE TITLE
[Bug] Migration issues on older tables 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3075]
Steps to reproduce:
1) Navigate to any application with Table 
and observe 

Observation:
1) The table does not get populated even with simple example table 
2) Displays cyclic dependency option
3) Table column gets duplicated 

Expectation:
The data must be displayed appropriately 

Video link:
https://www.loom.com/share/651047e3063c4787beebdc6d61cf5da0

![Screenshot 2021-02-17 at 10 32 35 AM](https://user-images.githubusercontent.com/71753653/108159620-68b2e480-710d-11eb-9cfa-c1b75cdbd307.png)

**Comment by riodeuno** [comment]
This happened because the table was in a bad state from the previous updates to the table widget. It conflicts with the latest updates.
Closing for now, please re-open if this happens again.
