### ISSUE TITLE
[Feature]: SSH Tunnel for Postgres

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#30792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Most of the companies have their production database behind a server. So providing an SSH tunnel will enable those users to use the platform with confidence and not compromising on security.

### Why should this be worked on?

We have requests for this on https://github.com/appsmithorg/appsmith/issues/518

**Comment by gabrielgarza** [comment]
We can't use appsmith without this

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/cnv_18grwccs?key=cGM8ak8w5XPZHjo7nI-qErtPz1ap9WKL) asked about this feature.

**Comment by rohan-arthur** [comment]
will be added with #31326

**Comment by cdolan92** [comment]
Unable to use Appsmith without SSH tunnelling, wish this was supported!

**Comment by Nikhil-Nandagopal** [comment]
@cdolan92 I believe this is now supported. Which version are you on?

**Comment by cdolan92** [comment]
Postgres 16 and I just installed appsmith via docker @Nikhil-Nandagopal 

MySQL seems to have the option but Postgres does not

**Comment by cdolan92** [comment]
Here is a screenshot of a fresh installation via Docker of the Community Edition: 

notice there is no option for "SSH Tunnel" connection option like there is for MySQL

<img width="1145" alt="image" src="https://github.com/appsmithorg/appsmith/assets/2132262/11667867-4e3d-4cd6-b45d-8bb9fbea8e6e">

**Comment by rohan-arthur** [comment]
@cdolan92 thank you for reaching out to us. We're real close to releasing this feature, you can track it on #5183

**Comment by sumitsum** [comment]
Hi @rohan-arthur I think there might be small confusion here. Please correct me if that is not the case. This particular issue is for `SSH` feature while #5183 is for `SSL`. I am reopening this issue. Please close it if this is not the case.

**Comment by GreenFlux** [comment]
@rohan-arthur a user in Discord reported a similar issue with MySQL. Should we create a separate issue for it? 
https://discord.com/channels/725602949748752515/1225186370096726157/1225594304383156344

**Comment by cdolan92** [comment]
Correct this is for SSH tunneling for a Postgres DB

Not related to SSL certificates

**Comment by sumitsum** [comment]
Hi @GreenFlux SSH tunnel should already be available for MySQL.

**Comment by sebak2003** [comment]
**My main problem with SSH to connect to MYSQL is that it is disconnected every day** (or I guess every few hours of inactivity), then the end user cannot access the data to use the application. It requires a developer to go to the configuration and save it again. And then reconnect. 

I have connected to this database with the same SSH key with other applications like n8n, or Tableplus. Same connection and none of them ask for the data every day to reconnect. 

**How can I get Appsmith to allow the connection or auto connect for end users automatically?** 

I just leave this here in case it is something that can be solved for both mysql and postgresql in its connection with SSH which is fundamental. Thanks!

**Comment by sumitsum** [comment]
Hi @sebak2003 thanks for reporting this issue. I have created [another issue](https://github.com/appsmithorg/appsmith/issues/32494) to track it.

**Comment by prerakhere** [comment]
Hi, any update for SSH tunnel support for Postgres? This was a blocker for me 6-8 months ago and it still is. Really hoping this comes out fast!

**Comment by rohan-arthur** [comment]
This is already done for mysql. We should extend this functionality to postgres. Links to the mysql issues below

Closed | Estimate | Assignees | Labels
-- | -- | -- | --
[Feature] MySQL ssh tunnel: migration for older datasourcesappsmith #26789 | 2 |   | BE Coders PodBackendEnhancement+ 4
Task: MySQL SSH tunnel: Add Junit TCappsmith #26254 | 1 |   | BE Coders PodBackendIntegrations Pod+ 2
[FEATURE] SSH Tunnel for Database connections (MySQL)appsmith #518 |   |   | BE Coders PodCommunity ReportedEnhancement+ 3
[Feature] MySQL SSH tunnel: Add ssh context in datasource context and related lifecycle changesappsmith #26253 | 1 |   | BE Coders PodEnhancementIntegrations Pod+ 1
[Feature] MySQL SSH tunnel: Update datasource form and enable the featureappsmith #26255 | 1 |   | BE Coders PodBackendEnhancement+ 2
[Feature] MySQL SSH tunnel: Update connection create flow with SSH tunnel contextappsmith #26252 | 2 |   | BE Coders PodBackendEnhancement+ 3
[Feature] MySQL SSH tunnel: Add utility method to create SSH tunnelappsmith #26251 | 1 |   | BE Coders PodBackendEnhancement+ 2
[Feature] Add a new object to handle SSH tunnel context and migrate MySQL plugin to use this new connection objectappsmith #26518 | 1 |   | BE Coders PodEnhancementIntegrations Pod+ 2
[Task] MySQL SSH tunnel: data modelling + datasource config form designappsmith #26250 | 2 |   | BE Coders PodBackendIntegrations Pod+ 2

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 would you be interested in picking up this issue?

**Comment by daaliachhak17** [comment]
@AnnaHariprasad5123 -created ticket on Jira-https://zemoso.atlassian.net/browse/TNOSB-457

**Comment by AnnaHariprasad5123** [comment]
@appsmithorg/contributor-support, I started working on this.

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 I have assigned this issue to you!

**Comment by Annahariprasad** [comment]
HI @rohan-arthur, I submitted the PR, Could you assign anyone to review this pr.

**Comment by AnnaHariprasad5123** [comment]
HI @rohan-arthur, I submitted the PR, Could you assign anyone to review this pr.

**Comment by rohan-arthur** [comment]
Thanks @AnnaHariprasad5123  for this! The video demo looks thorough. The team will be taking a look, we are a bit tied up with a critical issue right now. Expect some news early next week.
