### ISSUE TITLE
[Bug]: App Settings -> All tabs - if number of pages are high, then the scroll functionality is broken

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I go to Settings inside an application which has 10 or more Pages, the scroll on any of the sub option screens is broken.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/fa820829-c759-47b7-8388-c9db4ac7368c

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
fixed now

https://github.com/appsmithorg/appsmith/assets/94514895/384027c8-938d-4c14-b5df-176aaa56220c
