### ISSUE TITLE
[Bug]: Text for updating the page URL is incomplete does not make sense

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#30798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For a git connected app, the text that we show in the page settings pane to update our URL is not complete & does not make sense.
<img width="300" alt="Screenshot 2024-01-31 at 4 22 05 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/611215b3-cea2-4607-961f-5a54f90a32b0">

### Steps To Reproduce

1. Go to https://app.appsmith.com/
2. Create an app & connect it to Git.
3. Then go to Page settings.

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
This text has been updated
