### ISSUE TITLE
[Bug]: Unnecessary JSObject PUT call to update on pageLoad

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#30794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a JSObject had a function with params, it was noticed that the JSObject update call was triggered on page load. This is not expected as the user has not changed the code for the JSObject. 

### Steps To Reproduce

1. Create a JSObject
2. Add params to function
3. Refresh the page and check network tab in dev tools for the update call

### Environment

Production

### Version

1.9.61

**Comment by dvj1988** [comment]
@rohan-arthur This issue was fixed by [this PR](https://github.com/appsmithorg/appsmith/pull/33139). Can we close this?

**Comment by rishabhrathod01** [comment]
Closing the bug according to the [comment](https://github.com/appsmithorg/appsmith/issues/30794#issuecomment-2097539186)
