### ISSUE TITLE
[Feature]: Add setSelected or setValue for Radio Button Group in javascript

### ISSUE THREAD

**Issue by pbrink231** [appsmithorg/appsmith#30811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to be able to change the selected value in a Radio Group when some other action on the page happens.  There is no setValue or setSelected methods on the Radio Box Input.

![image](https://github.com/appsmithorg/appsmith/assets/8224560/bf049537-4cdc-4c22-ac98-c719e08f6e28)

### Why should this be worked on?

I am sure my use case is more specific.  I am using a input field where the user can scan barcodes on a wall to quickly fill out the form.  This has product barcodes, quantity barcodes and department barcodes.  When they scan a department barcode I want to select the radio box for them.   I have all this working with a table which adds products as they scan and updates the quantity of the last product added when they scan quantity barcodes.

I am going to try and work on this myself when I get time but will probably take me a lot longer than someone who knows exactly where to look.

**Comment by Nikhil-Nandagopal** [comment]
@pbrink231 instead of directly setting the value, you can return the value you expect based on the condition and invoke the function in the radio buttons default selected value property

**Comment by pbrink231** [comment]
@Nikhil-Nandagopal Thank you for that suggestion, didnt know that was possible.

Unfortunately for this will not work for my use case.  The user is interacting with a different input field and I am setting this radio group from that input field so the code is not run inside of that widget.  

My current fix is to use a single select widget and I can set the value in that element.

**Comment by Nikhil-Nandagopal** [comment]
@pbrink231 it will work for you. Code in appsmith is reactive so if in the radio group default value you have a binding like
{{ Input1.text == "A" ? "Option1" : "Option2" }} it will get automatically re-evaluated whenever the input text value is changed.

Feel free to share an app which is public and forkable where you don't find this working and we can help out 
or you can refer to our docs
https://docs.appsmith.com

**Comment by pbrink231** [comment]
In this case its more of a button press and an action but to your point I am saving the data now to an array in a code block and setting the bind to that array and it all just works.

Amazing app.  Thank you for pointing this out to me.
