### ISSUE TITLE
[Task]: Cypress- Write e2e tests for workflow: add DBEntry

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#30823]
### SubTasks

1. Workflow to add DBEntry

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/30823?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
