### ISSUE TITLE
[Task]: Workflows to get sorted based on recently used objects per user in a workspace

### ISSUE THREAD

**Issue by deepikaappsmith** [appsmithorg/appsmith#30841]
### SubTasks

The app within a workspace gets sorted based on the user action, i.e the last edited app is seen as the first card. This ordering is not present for the workflows.
Ref PR for getting workspaces and apps in recently used order https://github.com/appsmithorg/appsmith/pull/29004

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/30841?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
