### ISSUE TITLE
[Feature]-[6000]:CMD+Click to access APIs/Entities/queries

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3087]
## Summary
1. Allow users to cmd+click in the property pane to access the APIs or entities

**Comment by rohan-arthur** [comment]
@areyabhishek would you please help with more information about this idea? What is the problem that we are trying to solve?

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur this helps users navigate to an entity the way they do in code by cmd + clicking the class / variable name

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 1 |

**Comment by bharath31** [comment]
Handled by #15652
