### ISSUE TITLE
[Feature]: list widgets don't let you set the page programmatically

### ISSUE THREAD

**Issue by japrogramer** [appsmithorg/appsmith#30881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I require to set the page of the list widget when paginating server side sometimes back to one
but the widget does not have a method for me to do this :O
I also need to be able to recalculate the total number of results each time the query is rerun, I suspect that it doesn't do that either.
This is a huge problem for me.

### Why should this be worked on?

it is an anti-pattern for other widgets to be able to set their variable properties via code but not the list widget on
the pagination.

it is also a core functionality in all frameworks to be able to set the page number.

**Comment by Nikhil-Nandagopal** [comment]
@japrogramer you can just trigger resetWidget('List1') and this should set the page back to the starting page.

**Comment by japrogramer** [comment]
@Nikhil-Nandagopal that worked.
