### ISSUE TITLE
[Bug]: Settings tab is shown in JSObject for workflows

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#30885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Settings tab has run on page load option, ideally we should remove it or if settings tab is irrelevant remove the settings tab altogether 
<img width="1440" alt="Screenshot 2024-02-05 at 11 26 27 AM" src="https://github.com/appsmithorg/appsmith/assets/80334441/41fdf440-f8da-4a2a-bbba-02eabcef6e61">

### Steps To Reproduce

1. Go to workflows
2. Create JSObject
3. Observe settings tab is shown

### Environment

Release

### Version

Release

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/30885?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
