### ISSUE TITLE
[Feature] Move/Copy application from one organization to another

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3089]
## Summary
An application made in one organization can be copied or moved to another organization.

**Comment by chrdoud** [comment]
Use case :
Basic and simple error
Multi society, dev for one, duplicate on other and do light param
Developing on 'reserved to developp' Organization and 'deploy' in 'production Organization'

**Comment by codedmind** [comment]
Use case:
Maybe add the option to export/import in the case that the develop and production are different instances
