### ISSUE TITLE
[Feature]: Weak password policy  for users created on appsmith

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#30905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently user can signup with any password and there is no explicit password policy set

### Why should this be worked on?

This in general helps in enhancing security and better usability of product

**Comment by sharat87** [comment]
Fixed by https://github.com/appsmithorg/appsmith/pull/31605.
