### ISSUE TITLE
[Bug]: In this new menu UI I cannot add a widget??

### ISSUE THREAD

**Issue by hpriehle** [appsmithorg/appsmith#30908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click "add a widget" or the + icon, nothing happens, cannot add new widget

### Steps To Reproduce

Click "add a widget"

### Environment

Production

### Issue video log

https://www.loom.com/share/977d067869e048ad9916e69036ade416?sid=ffdf3623-e5f9-4ea5-a912-80b17143ca99

### Version

Self Hosted - 1.6.6

**Comment by pranavkanade** [comment]
@hpriehle I don't think you are using v1.6.6. Can you confirm once again, by clicking on the `Help` button in the bottom right corner?

Also, this issue shouldn't be an issue in the latest version, so you could also upgrade to resolve the issue.

**Comment by amitm02** [comment]
same issue with v1.9.50

**Comment by hetunandu** [comment]
@amitm02 @hpriehle we seem to have messed up our Feature Flagging and caused an incomplete feature surface on an older appsmith version. We are working on fixing this issue. Please wait upto 2 hours to start seeing the correct interface for your appsmith version again
