### ISSUE TITLE
[Bug]: the info [question mark] option is not present on the Home page in airgapped images.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Home page, the Question Mark - info icon - is not present in airgapped image.

### Steps To Reproduce

Airgapped

<img width="1429" alt="Screenshot 2024-02-06 at 10 44 31 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/6b1dc525-aab3-453d-923b-8a8226a6527c">

Nightly 

<img width="1300" alt="Screenshot 2024-02-06 at 10 44 22 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/102daa86-4311-4d61-ace4-a929989f6634">

### Environment

Production

### Version

Cloud v1.11

**Comment by AmanAgarwal041** [comment]
Closing the issue after the discussion on the thread https://theappsmith.slack.com/archives/CTHN8GX5Y/p1707204036099499  to remove the [question mark] option from the home page for airgap instance.
