### ISSUE TITLE
[Bug]: User attention consistently gets diverted because of the red dot on the `Help` option

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#30917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After a user has signed up on the airgap version for the first time we are shown the signposting pop up. Even after dismissing the modal we get to see a red dot after we do any activity or refresh the page. This diverts the attention from the canvas and leads to a bad UX. This issue is not reproducible on prod.

### Steps To Reproduce

1. docker pull appsmith/appsmith-airgap:nightly
2. docker run -d --name appsmith-airgap -p 80:80 -p 9001:9001 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-airgap:nightly
3. Enter license key and complete the sign up flow.
4. Once on the application canvas, dismiss the sign posting modal the first time.
5. Refresh the page.

**Expected:** The red dot on the `Help` option should not appear as the user has opted to dismiss it.
**Actual:** The red dot indicating incomplete steps should not appear after dismissing the modal.

### Environment

Production

### Issue video log

https://www.loom.com/share/63fb74b0030a4a88bdd0c30982a265b4

### Version

Self Hosted v1.11

**Comment by rohan-arthur** [comment]
we've removed this option, so issue is not valid anymore
