### ISSUE TITLE
[Bug]: The instance break when user click on active tab on datasource page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The instance break when user click on active tab on data source page
![image](https://github.com/appsmithorg/appsmith/assets/45958978/4f24609e-b0f1-4987-b02d-ac04edbc21f7)
![image](https://github.com/appsmithorg/appsmith/assets/45958978/039fab4c-2b67-4a1e-a293-3d03b4825aac)

### Steps To Reproduce

1. docker pull appsmith/appsmith-airgap:nightly
2. docker run -d --name appsmith-airgap -p 80:80 -p 9001:9001 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-airgap:nightly
3. Enter license key and open an application
4. Import any app
5. Click on go to application button on datasource modal
6. now click on active tab
7. The instance breaks with a message

### Environment

Production

### Version

v1.11.0

**Comment by hetunandu** [comment]
fixed in #30923
