### ISSUE TITLE
[Bug]: Unable to see partial import export options in air-gapped image

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#30913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I pull an air-gapped nightly image, I am unable to see the Partial Import Export options.

### Steps To Reproduce

1. docker pull appsmith/appsmith-airgap:nightly
2. docker run -d --name appsmith-airgap -p 80:80 -p 9001:9001 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-airgap:nightly
3. Enter license key and open an application
4. Note that the Page level or partial import export options are not available

### Environment

Production

### Version

Self Hosted v1.11

**Comment by btsgh** [comment]
This is not a blocker for air-gapped. Thread [here](https://theappsmith.slack.com/archives/CTHN8GX5Y/p1707199772277469).

**Comment by rahulbarwal** [comment]
We will remove the feature flag when the feature becomes more stable. 
Till that time, we can close this.
