### ISSUE TITLE
[Bug]: The members link is still present under app when user click on 3 dot icon

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The members link is still present under app when user click on 3 dot icon
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/f8994fa3-ae11-47b5-beb4-c86000998e6a">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/85d63765-d2cd-4be2-9f94-f8110dc5c637">

### Steps To Reproduce

1. docker pull appsmith/appsmith-airgap:nightly
2. docker run -d --name appsmith-airgap -p 80:80 -p 9001:9001 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-airgap:nightly
3. Enter license key 
4. Now on home page click on 3 dot icon below the application
5. The members page link is present 

### Environment

Production

### Version

v.11.0

**Comment by AmanAgarwal041** [comment]
According to the thread : https://theappsmith.slack.com/archives/CTHN8GX5Y/p1707205884660009
We decided to remove the Member's link in the individual app menu

**Comment by RakshaKShetty** [comment]
Fixed
