### ISSUE TITLE
[Bug]: Google Sheets DS isn't working with Workflows.

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#30932]
At the moment, Google Sheet DS has an API `/saas/{datasourceId}/pages/{pageId}/oauth`, which is tightly coupled with pages.
We need to take care of this.

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by nsarupr** [comment]
@Nikhil-Nandagopal , this was merged last friday into the release.
- https://github.com/appsmithorg/appsmith/pull/31064
- https://github.com/appsmithorg/appsmith-ee/pull/3533

**Comment by Nikhil-Nandagopal** [comment]
@nsarupr then why is it still open? Please close it
