### ISSUE TITLE
[Bug]: The Admins are unable to invite new users through custom groups

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#30936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Admins are unable to invite new users through custom groups
![image](https://github.com/appsmithorg/appsmith/assets/45958978/31d9cdc6-d6bd-4d95-8ff8-d2428043343f)
![image](https://github.com/appsmithorg/appsmith/assets/45958978/32fd9880-ebb2-4a60-96b2-cbc69d4634ed)

### Steps To Reproduce

1. Login as an admin user
2. go to admin settings and click on groups create a new group " group1" and assign some roles 
3. now go back to the application page and click on share button
4. Inside the share mode Type the Group name 
5. The name suggests will not be displayed and also it says the group name is invalid 

### Environment

Production

### Version

v.11.0

**Comment by btsgh** [comment]
Fixed
