### ISSUE TITLE
[Bug]: API without saving as datasource doesn't work in workflows

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#30948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In order for api to work we need to save it as datasource in workflows, ideally APIs without saving as ds should work fine.

### Steps To Reproduce

1. Create a workflow with rest api
2. Trigger the workflow
3. Observe workflow isnt triggered

### Environment

Release

### Version

Release

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/30948?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12

**Comment by srix** [comment]
@Parthvi12 please updat with screenshot and error message

**Comment by nsarupr** [comment]
Triage: 
When executing a Rest API action, RTS doesn't have the context of environment id, and that leads to the failure.
This also happens, when we are executing the cURL execute without environment header.
