### ISSUE TITLE
[Task]: Cypress- Test run history for workflows

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#30940]
### SubTasks

- Click on run history, verify workflow execution started.
- Verify run details
- Verify failed runs
- Verify all runs

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/30940?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12

**Comment by Parthvi12** [comment]
Closing as divided into sub tasks
