### ISSUE TITLE
[Bug] Incorrect binding is failing the whole workflow - Lint Error

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#30941]
When I write this kind of binding, the workflow stops working altogether, i.e. Activities before that line of code are also not being run, meaning this may be an issue with eval. Even if the code there is wrong, we should handle it better(graceful fail).

<img width="1050" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0EyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05400ce7f9df01b238f0d5ef5fed37d229e504d9/image.png" alt="image.png" />

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/30941?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12

**Comment by srix** [comment]
what is the expected behaviour? do you have something as proposal. else we can discuss in biweekly @infinitetrooper

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by ayushpahwa** [comment]
This is closed with recent try catch fixes
