### ISSUE TITLE
[Bug]: `Protected branch` feature isn't available on airgap. And the newer UI for git connection isn't seen.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#30954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`Protected branch` feature isn't available on airgap. And the newer UI for git connection isn't seen.

Old UI:
![image](https://github.com/appsmithorg/appsmith/assets/109572422/af79eca4-dc0d-4093-a213-45dbf88aa645)

Expected new UI:

![image](https://github.com/appsmithorg/appsmith/assets/109572422/bab117c9-22e1-4529-9720-3da587d5fc7d)

### Steps To Reproduce

1. docker pull appsmith/appsmith-airgap:nightly
2. docker run -d --name appsmith-airgap -p 80:80 -p 9001:9001 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-airgap:nightly
3. Enter license key and open an application
4. Click on `Connect Git`, notice that the new UI isn't seen and branch protection feature isn't available

### Environment

Production

### Version

v.11.0

**Comment by trishaanand** [comment]
This issue has been closed in PR 30962 and PR 3506

**Comment by laveena-en** [comment]
Tested and verified on the new airgap nightly image. Changes LGTM.
