### ISSUE TITLE
[Feature] Input widget for phone number with ISD codes

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3097]
## Summary

See this input interaction:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d51262ff3b554022bf5c2fed259fac5e-00001.gif)](https://www.loom.com/share/d51262ff3b554022bf5c2fed259fac5e)

Seems like a useful widget for forms so that users can create forms with phone numbers.

## Developer Handoff Link
https://www.figma.com/file/PopQorpIl38IqHNdODE0lR/Input-Widget-Types-Update-Number-and-Currency?node-id=2%3A1

**Comment by riodeuno** [comment]
@areyabhishek Should this be solved by providing an icon dropdown widget? In conjunction with this widget and the input widget with a regex, this workflow can be achieved.

**Comment by somangshu** [comment]
This can be most related to button-widget. We can say when the type is `phone` can a configurable option to show the county codes as dropdown options. In material design this is called as [Input Adornments](https://material-ui.com/components/text-fields/#input-adornments)

**Comment by somangshu** [comment]
@jsartisan @areyabhishek @riodeuno we are contemplating if this should also be separated as a separate widget. Since we have to add an input adornment to accommodate this feature, we might as well think of discoverability here. Please check out the developer handoff design in the comment ☝️ .

**Comment by somangshu** [comment]
Debate:

- Should the widget be thought of as a separate entity (new widget)? (ANS) Yes, it should be, It increases the discoverability, but it should also be present under the input widget.
- Should the country code selected be editable? (ANS) Should only be editable from the dropdown.
- Should the country dropdown stretch as much as the input?
- Should there be a choice for the developer to let users change the country selection or not?

**Comment by vicky-primathon** [comment]
@somangshu  we need data to list countries with country code. We can use a single API call to get data with currency or country code based on data query.

**Comment by somangshu** [comment]
@vicky-primathon Let's build the feature with static data as before, Link the PR and then change it to draft until the backend team can get back to us. 

@riodeuno any feedback?

**Comment by vicky-primathon** [comment]
Unrelated test case of button widget is failing here

**Comment by ramsaptami** [comment]
@vicky-primathon Can we look at the alignment and also making the edges sharp on the corner there?
![image](https://user-images.githubusercontent.com/79509062/133432812-c8b73eef-10e2-49c9-9de2-28ba881f9622.png)

**Comment by somangshu** [comment]
@ramsaptami please raise such issue separately and dont reopen the features. 

This is been taken care in #7477. Closing this again
