### ISSUE TITLE
[Bug] User should be able to SAVE the datasource even when the credentials are not added 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3103]
Steps to reproduce:
1) Add an API
2) Click on Add an Datasource
3) Add OAuth2 in "Authentication Type"
observe the layer for Authentication 

Observation:
Save option  is active until the credentials are added 

Expectation:
It is expected that the Save button must be active

**Comment by nidhi-nair** [comment]
@ofpiyush Could you please take a look at this? I imagine we'll need to remove client side validation?
