### ISSUE TITLE
[Bug]: Not able to create a page form "Meeting Scheduler" template in release

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not able to add a page from the "Meeting Scheduler" template in https://release.app.appsmith.com/. When we try the same in https://app.appsmith.com/ with the same template, we are able to go through.

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/.
2. Create an app and then click on `Add page from template` from the pages section.

**Expected:** The page should get added successfully just like it does in prod.
**Actual:** Th page does not get added.

### Environment

Release

### Issue video log

https://www.loom.com/share/f780fa0d8cb84f92aea6285d17488e0e

### Version

Cloud

**Comment by jacquesikot** [comment]
App JSON has been re uploaded for this app and pages entry in CS has been updated.
