### ISSUE TITLE
[Bug]: Create module option is coming up for workflow queries

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#31048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since we are not supporting module for workflow query we should remove it
<img width="1438" alt="Screenshot 2024-02-12 at 11 57 35 AM" src="https://github.com/appsmithorg/appsmith/assets/80334441/2f13923c-8491-46e4-b862-e1f754734410">

### Steps To Reproduce

1. Create new workflow
2. Create an app in same workspace
3. Create new workflow query
4. Click on three dots and observe create module option is there

### Environment

Release

### Version

Release

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31048?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
