### ISSUE TITLE
[Bug] Formatting SQL breaks query

### ISSUE THREAD

**Issue by Racle** [appsmithorg/appsmith#3107]
## Description

For some reason appsmith doesn't handle well select.

I noticed (when I was debugging this) that when I added empty space after `SELECT `, query works just fine.
But if it's just `SELECT` and new line, it doesn't work.

### Steps to reproduce the behaviour:
1. Create query and format it with ex. Dbeaver automatically so it looks like this
```sql
SELECT
    'data',
    'data2'
FROM
    `mysql`.db
```

On `Query response` view it says 
```
affectedRows       |
--------------------
0                  |
``` 

But if I change query to this (or only add space after select)
```sql
SELECT 'data',
    'data2'
FROM
    `mysql`.db
``` 
it runs normally and displays multiple `data | data2` rows in `Query response`.

### Important Details
 - Version: Docker, Appsmith v1.3.5.1
 - OS: Linux (irrelevant)
 - Browser: Firefox (irrelevant)

**Comment by Nikhil-Nandagopal** [comment]
@Racle thank you for pointing this out! This is indeed an issue.
@sharat87 are we perhaps stripping all new lines before execution? Maybe we should replace them with spaces instead?

**Comment by sharat87** [comment]
This is a bug in the code identifies whether the query is a `SELECT` query or not.

Thanks for reporting @Racle.
