### ISSUE TITLE
[Bug]: Datepicker on the Canvas Should Open at the Bottom

### ISSUE THREAD

**Issue by vasanthappsmith** [appsmithorg/appsmith#31076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The current position of the datepicker in the canvas interface is obstructing its view. To make it more accessible, it is recommended to relocate the datepicker to the bottom of the picker. Also, when the datepicker reaches the bottom of the page, it should shift to the top to stay visible.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/92305123/7562fcc6-ece5-4f36-af16-636ba5f4a5e2

### Environment

Production

### Version

`

**Comment by Nikhil-Nandagopal** [comment]
Not able to reproduce please provide better steps
