### ISSUE TITLE
[Bug] API and datasource has same name 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3108]
Steps to reproduce:
1) Add an API 
2) Navigate to API datasource page 
3) Add the credentials 
4) Edit the name 
5) Save the datasource
6) Now click on Add API 
7) Add credentials 
8) Edit the name and add same name as datasource
9) Now open the API datasource page 
and observe

Observation:
It is observed that the API datasource and API can be Save at first but on trying to open the API datasource page  displays an error

Expectation:
It is expected to not save and display an error at first place

![Screenshot 2021-02-19 at 6 34 49 PM](https://user-images.githubusercontent.com/71753653/108510322-5d65e180-72e4-11eb-9df6-ecf3931ffea0.png)
when widget have same name

**Comment by ofpiyush** [comment]
Datasource names need not be unique from actions/widgets as they're not "in scope" for evaluations.

**Comment by nidhi-nair** [comment]
@ofpiyush I'm not sure about that, we do not seem to allow re-use of names currently either.

**Comment by ofpiyush** [comment]
API or Widget of the same name will cause an issue with Eval, datasource causes no such issues and hence need not be unique.

Moreover, we'd need to know names of all actions and widgets across all apps of an org to disallow name conflicts on a datasource.

> we do not seem to allow re-use of names currently either.

We went a little overboard on name conflict fixes with this PR https://github.com/appsmithorg/appsmith/pull/1781

**Comment by prapullac** [comment]
Closing the issue as per above comment
