### ISSUE TITLE
[Bug]: Data validation based on unfiltered table instead of filtered table

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#31105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When searching/filtering a table, items that use currentRow to determine their max or min value use the data from the unfiltered table instead of the filtered currentRow.

My use case is a table of quantities to prepare where the user inputs how many they have prepared, they should not be able to prepare more than the amount that is ordered, but when they filter the table to find a specific order, the data validation no longer works as expected.

### Steps To Reproduce

1. Create a table
2. Populate it with 4 rows of data:
ID | maxQty | Qty
10 | 1 | 0
11 | 5 | 0
20 | 4 | 0
21 | 8 | 0

3. Make qty editable and set the maximum valid amount to table.currentRow.maxQty
4. Search the table for "2", hiding the first two rows and moving the second two rows up to the first two.
5. Edit the quantity for ID 20 to be 1.  This is valid.  Edit it to be 2, this is not valid but should be.
6. Edit the quantity for ID 21 to be 4.  This is valid.  Edit it to be 7, this is not valid but should be.

### Environment

Production

### Version

Self Hosted - 1.6.60

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS this seems to work for me. The maxQty is based on the row that you are editing and has nothing to do with the filtered or unfiltered data. So I'm unable to understand the problem here. Please check whether the column type is correctly set to number for maxQty.

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS thanks for the video. This makes it clear

**Comment by rahulbarwal** [comment]
Fixed with: https://github.com/appsmithorg/appsmith/pull/35390

Please reopen if you see this issue again.
