### ISSUE TITLE
[Bug] Evaluated value does not wrap

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3110]
## Description

When the evalauted value has a long string of text, it scrolls instead of wrapping. This makes debugging issues very difficult

**Comment by ApekshaBhosale** [comment]
@Nikhil-Nandagopal Is this issue still happening? I tried to reproduce this and work as intended. can you please confirm?

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale seems to be working now so closing this
