### ISSUE TITLE
[Bug]: `isVisible` property of JSON From is not exposed for autocomplete

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On trying to bind a widget with JSON Form we see that the `isVisible` property does not show up in the autocomplete suggestions. Since we are exposing this property for all other widgets, in order to maintain consistency we should do the same for JSON Form as well.

### Steps To Reproduce

1. DnD JSON Form & Text widgets.
2. In the `visible` property for text widget type: `{{JSONForm1.}}`.

**Expected:** We should see the `isVisible` suggestion for autocomplete.

### Environment

Production

### Issue video log

https://www.loom.com/share/cbe46f930c7448e5984903cbc474706b

### Version

Cloud

**Comment by SaiCharanChetpelly31** [comment]
Hi @sbalaji1192 @shadabbuchh I am picking up this issue.
**Approach:**
Make sure `isVisible` is exposed for autocomplete in JSONForm widget.
