### ISSUE TITLE
[Task]: Set Default JSMode to be enabled for 1-click binding

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#31110]
### SubTasks

Currently, when users use 1-click binding with a Query in JSONForm they see the bindings instead of the query name in UI. We need to enable it for all the widgets. 

![image](https://github.com/appsmithorg/appsmith/assets/23132741/66b45284-9d95-41dd-8058-d20b5479c27d)

- [ ] JSON Form ( for APIs )
- [x] Table widget 
- [x] Select widget
- [x] Multi-Select widget

**Comment by AmanAgarwal041** [comment]
For JSONForm widget, a new issue to be addressed https://github.com/appsmithorg/appsmith/issues/31185
