### ISSUE TITLE
[Bug]:  App Crash With Browser OOM Error

### ISSUE THREAD

**Issue by amelia-c0n** [appsmithorg/appsmith#31132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The app is crashing and the browser displays an out-of-memory error. 
This is happening in the Microsoft Edge browser on Windows 10.

[ZD ticket](https://appsmith3239.zendesk.com/agent/tickets/1472)

### Steps To Reproduce

Open the application, log in, get to the main screen, and then let it sit. After some time, the error occurs.

### Environment

Production

### Version

Airgap EE

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #30610
