### ISSUE TITLE
[Bug]: After committing, Files changed tab in remote shows changes that were not made in the local branch 

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Files changed` section in remote shows some changes that were not made in the local branch in the first place.

### Steps To Reproduce

1. Create an app & connect it to git.
2. From `master` create couple of branches.
3. In one of the branches make some changes e.g. Dnd widgets, change the theme etc.
4. Now commit these changes.
5. Go to remote and create a pull request.
6. Navigate to the `Files changed` tab and check the changes that show up.

**Expected:** Only changes that are made in local branches only should show up in the `Files changed` tab.
**Actual:** Random changes show up in the `Files changed` tab

### Environment

Production

### Issue video log

https://www.loom.com/share/4894b8812e7f4746b2059e18c8b0504e

### Version

Cloud

**Comment by infinitetrooper** [comment]
This is expected. Adding a widget changes the properties of a page, in this case, the dimensions and that will affect some properties of other widgets. Widgets on a page don't exist in isolation, they do sometimes get affected by changes in other widgets.
