### ISSUE TITLE
[Feature] Allow a way for users to quickly reach back to last edited canvas from Api pane / query pane / datasource pane.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3114]
## Summary
Allow a way for users to quickly reach back to last edited canvas from Api pane / query pane / datasource pane.

## Motivation
To ensure that a user's work flow on the canvas is not interrupted because they need to edit Api/query/datasource.

## Additional Context
This discussion came up during smart look session on 19 Feb 2021.

**Comment by pranavkanade** [comment]
Fixed with https://github.com/appsmithorg/appsmith/pull/5558
