### ISSUE TITLE
[Bug]: The Errors,Logs,Inspect Entity tabs on the query editor do not go away on navigating to the Edit DS page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run a query or an api, and it errors out, if I open the Error tab [or Logs/Inspect Entity], and then with it open, I navigate to the Edit DS screen, the tabs remain open. 

### Steps To Reproduce

1. In an application, create a new api
2. Type some random, incorrect url, and run the api
3. Errors get generated in the console below. 
4. Click on Error tab [or Logs/Inspect Entity tab]
5. Now navigate to Data-> go to any datasource, and click to edit the datasource details
6. Note that the Error tab Error tab [or Logs/Inspect Entity tab] do not get closed. 

https://github.com/appsmithorg/appsmith/assets/101863839/cfe25823-5e59-404a-afcf-2ad09d9d7940

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
this is fixed now and can be tested on release
