### ISSUE TITLE
[Bug]: Empty state is seen on navigating to the Gsheets query section. 

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#31144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Empty state is seen on navigating to the Gsheets query section. 

### Steps To Reproduce

1. Create a Gsheets query
2. Navigate away from the query section and return back to it
3. Notice that an empty state is seen

Note: This bug is only seen with Gsheets. Checked with other DS like mongo and postgres as well

### Environment

Production

### Issue video log

https://www.loom.com/share/db7f062613764ddaa8b6bb98b508693f?sid=2fe521eb-97a0-4bd7-956e-9837ef983c08

### Version

Cloud

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=63502fd30bce4de98589d3c145ab85e2&pm=s

**Comment by hetunandu** [comment]
Fixed in #31378
