### ISSUE TITLE
[Task]: Create new user in mock_db_v2

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#31153]
### SubTasks

- Create a new user in the mock_db_v2 database with limited permissions that can be shared in docs.
- The plan is to make sure that users with exiting forked templates do not get broken after this new user is created and implemented.

**Comment by rahulbarwal** [comment]
Duplicate: https://app.zenhub.com/workspaces/templates-pod-642d00683718250012716861/issues/zh/75
