### ISSUE TITLE
UI refinements to the Widget explorer

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#31152]
While working on updating thumbnails and icons of widgets, we discussed various UI refinements that can be done on widget explorer to make more consistent. This task deals with all those refinements.

Follow-up to #31085

**Comment by somangshu** [comment]
What are the things we are thinking about?

**Comment by ichik** [comment]
@somangshu detailed list of changes is pending. Preliminary I'd recommend decreasing the padding on the widget list container.

**Comment by ichik** [comment]
This will be tackled in the overall development of Anvil.
