### ISSUE TITLE
[Bug]: Extremely slow function execution due to reactivity callbacks

### ISSUE THREAD

**Issue by thegoodhen** [appsmithorg/appsmith#31160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`export default {
	message:"Click the button to lag the reactivity system.",
	lagComputer () {
		for(let i=0;i<10000;i++)
		{
			this.dontDoMuchAtAll()
		}
		this.message="Well that was laggy! Here is a random number for free: "+Math.random();//ensure update
	},
	dontDoMuchAtAll()
	{
		return 0;
	},
	async myFun2 () {
		//	use async-await or promises
		//	await storeValue('varName', 'hello world')
	}

}`

Calling lagComputer from, say, a button callback will do as the name suggests. The reactivity system is unresponsive, meaning that if there are any elements that use the "message" value, they won't update for several seconds, while the cpu usage goes through the roof.
I believe that there are callbacks connected to the execution of user functions.
The following app showcases this behavior.
https://app.appsmith.com/app/performancehitreactivity/page1-65ce24bcd51e9c12429e8455

### Steps To Reproduce

1) Go to the app I shared.
2) Click "Lag reactivity system." You may need to do this several times before the problem becomes apparent.
3) the reactive heading will take a several seconds to update.

### Workaround

If you need to call some function many times, you can nest it inside the function you want to call it from, which circumvents the issue.

### Public Sample App

https://app.appsmith.com/app/performancehitreactivity/page1-65ce24bcd51e9c12429e8455

### Environment

Production

### Version

Cloud

**Comment by rajatagrawal** [comment]
Hello @thegoodhen 

Apologies for the inconvenience faced. As you have correctly suggested, upon triaging the issue, we found out that the anonymous analytics function that captures an execution of a js object function is getting called as many times as in the loop.

This falls in line with your suggestion for the workaround since that would only make one analytics call.

@bharath31 @rishabhrathod01 Any suggestions to address this issue ?

**Comment by rajatagrawal** [comment]
The following analytics events are getting fired on each js object function call: [Analytics event 1](https://github.com/appsmithorg/appsmith/blob/90a53cb4389a089d3c8a1aef3af25a2070d83f82/app/client/src/ce/sagas/analyticsSaga.ts#L180) and [Analytics event 2](https://github.com/appsmithorg/appsmith/blob/90a53cb4389a089d3c8a1aef3af25a2070d83f82/app/client/src/ce/sagas/analyticsSaga.ts#L203)

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 @rajatagrawal lets remove analytics for JS function executions? I don't believe we're using this today and this can be quite a performance bottleneck especially in the case of loops

**Comment by rajatagrawal** [comment]
@bharath31 please let me know if there is any use case that we are currently observing for this analytic. I can raise a PR based on your response.

**Comment by bharath31** [comment]
@rajatagrawal cold we batch these analytics calls and run them on a different thread maybe? Alternate solution: for recursive runs, we could just log the analytics event for the last run with an additional `runCount` parameter
