### ISSUE TITLE
[Bug]: Google Sheets query performance is slow

### ISSUE THREAD

**Issue by JetUni** [appsmithorg/appsmith#31164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I query Google Sheets for rows matching a certain criteria with filter on a sheet that has 17,000+ rows, the query takes around 20+ seconds to complete. What I expect is for the query to take much less time by filtering in a more performant way

### Steps To Reproduce

1. Add a Google sheets query (banking transactions)
2. Fetch many rows
3. Add a filter where date IN an array of dates
4. Add another filter where amount IN array of dates
5. Run the query and see the slow performance

### Environment

Production

### Version

Cloud

**Comment by pranavkanade** [comment]
@JetUni could you please try adding pagination? That's the ideal way to build a webpage with lots of records. - https://docs.appsmith.com/connect-data/how-to-guides/filter-data-google-sheet#server-side-pagination
