### ISSUE TITLE
[Task]: Add accelerator and isUserCreated properties in execute_ACTION_TRIGGERED event for 1-click binding

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#31174]
### SubTasks

Notion doc: https://www.notion.so/appsmith/Add-accelerator-and-isUserCreated-properties-in-execute_ACTION_TRIGGERED-event-for-1-click-binding-02db8353ce9b438d9f27380484eb1c9d?pvs=4

**Comment by AmanAgarwal041** [comment]
PR is merged, hence closing this one
