### ISSUE TITLE
[Task]: Add accelerator and isUserCreated properties in ENTITY_BINDING_SUCCESS event for 1-click binding adding query directly

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#31175]
### SubTasks

Notion doc: https://www.notion.so/appsmith/Add-accelerator-and-isUserCreated-properties-in-ENTITY_BINDING_SUCCESS-event-for-1-click-binding-add-f2b308aca2f84956ba9ce4694f3f9832?pvs=4

**Comment by sumitsum** [comment]
Un-assigning myself because I will be OOO for the next one week. @rohan-arthur @sneha122
