### ISSUE TITLE
[Feature]: Add rest api support to app-data

### ISSUE THREAD

**Issue by Torpedro1978** [appsmithorg/appsmith#31186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I want to access data in an appsmith app via api CRUD.

### Why should this be worked on?

I need this so i can use the data from multiple systems for an automation engine, in my case Powershell.
So basically a User enters data via the web-GUI and this can be processed from a powershell script or retreived (authorized via token of course) from anywhere via REST api.

Just like a webshop, but the backend worker is not intergrated directry within the app, but only utilizes the data.
It then processes data from a table (e.g. execute powershell scripts asynchronously) and reports the output of it's operations back to another table.

This would integrate perfectly into appsmith to allow flexible data management hot only from a user, but also from an automation side.

**Comment by Nikhil-Nandagopal** [comment]
@Torpedro1978 we're currently building this out as part of #1950 you can subscribe to that feature and opt to join our beta program
