### ISSUE TITLE
[Bug]: In Version CE 1.1.3 Self-Hosted: Custom Widget grows vertically when page is loaded

### ISSUE THREAD

**Issue by pchambless** [appsmithorg/appsmith#31189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a Custom Widget to a new Tab in my page, the Widget grows vertically before my eyes without me performing any actions.  This is the base Custom Widget.

P.S.  I tried this in my Cloud account and it does not grow.

### Steps To Reproduce

1.  Add a Custom Widget to a Tab.
2.  Watch it grow.

I'm not good at loom, but this should be easy to reproduce.

### Environment

Production

### Version

Self Hosted CE 1.1.3

**Comment by pchambless** [comment]
Update... I just added a Custom Widget to my Self-Hosted app and it did not grow.  I don't know what changed except it is a new day.

**Comment by robhzm** [comment]
I have the same issue after upgrading to v1.13. It is impossible to edit the page where it happens. Re-adding the widget is not helping either.

**Comment by sbalaji1192** [comment]
@robhzm @pchambless Can you please provide more info.
- Are you using a Fixed layout or Auto layout?

**Comment by robhzm** [comment]
Hi @sbalaji1192, I am using the Auto Layout. I also cleared my browser cache. Version CE 1.1.2 has the same problem.

This is how it looks like.
![Arc_nEL8qC7Ddd](https://github.com/appsmithorg/appsmith/assets/44999675/3c358cb2-c939-4473-ac01-1da9bc797243)

**Comment by pchambless** [comment]
I'm getting this again as well:  https://www.loom.com/share/07ab367dc8a64387acd07b77180d08e3?sid=cc6c1b5f-7a47-43e6-8c2e-533f69259cce

**Comment by pchambless** [comment]
Here's a new twist:   https://www.loom.com/share/efc3405598ee4dcba262ea2728e55de8?sid=0a667c69-aede-4372-8a89-77afd0f8d551

**Comment by sbalaji1192** [comment]
@pchambless Can you please share the app link where you're facing the above issue, if you can ?

**Comment by pchambless** [comment]
This page:  https://appsmith-tmg.whatsfresh.app/app/admin/work-flow-65a6ab74f252e546aa746718/edit/widgets/0?branch=main

I shared with support@appsmith.com.  Hope you can get to it!

**Comment by sbalaji1192** [comment]
@pchambless Can you please provide access to `balaji@appsmith.com`

**Comment by sbalaji1192** [comment]
Closing this as this issue has been fixed in the latest release v1.14
