### ISSUE TITLE
[Bug]: issue with context switching when we convert existing query to module 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 issue with context switching when we convert existing query to module 

### Steps To Reproduce

https://www.loom.com/share/9a3e53bebb2c4a7d90f164b8c6a8e52d

### Environment

Production

### Version

self-hosted

**Comment by pedro-santos-rodrigues** [comment]
@kamakshibhat-appsmith do you know if this was already solved?

**Comment by kamakshibhat-appsmith** [comment]
@pedro-santos-rodrigues No, ,the issue is still unresolved

**Comment by hetunandu** [comment]
@kamakshibhat-appsmith we have removed the context retention logic where we would have an item always selected in a segment. This was done to make the segments be more consistent with how tabs actually work. Removing this logic fixed the issue as a side effect
