### ISSUE TITLE
[Bug]: Cannot perform backup due to file not exist

### ISSUE THREAD

**Issue by shirobachi** [appsmithorg/appsmith#31197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When do backup (follow [this](https://docs.appsmith.com/getting-started/setup/instance-management/appsmithctl?current-command-type=kubernetes-commands)) I got `Error: ENOENT: no such file or directory, open '/opt/appsmith/info.json'`

I manage to solve it by making fake `info.json`  (copied content from fresh docker-compose version)

### Steps To Reproduce

Try do backup when info.json not exist (question is why it's not exists)

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by pranavkanade** [comment]
@shirobachi can you share a screenshot of the  /opt/appsmith dir?

**Comment by shirobachi** [comment]
Here you go:
```sh
backend
editor
entrypoint.sh
healthcheck.sh
init_ssl_cert.sh
install_docker.sh
prepare-image.mjs
pull_resource.sh
renew-certificate.sh
rts
run-java.sh
run-keycloak.sh
run-nginx.sh
run-postgres.sh
run-starting-page-init.sh
run-with-env.sh
start_app.sh
starting-page-init.py
templates
update-and-restart-supervisor.sh
utils
```

**Comment by Nikhil-Nandagopal** [comment]
@shirobachi I'm glad this is resolved. This was likely an issue with older deployments. Let us know if you see this again
