### ISSUE TITLE
[Bug]: Authenticated API with OAuth 2.0 and Grant type "client credentials" is broken

### ISSUE THREAD

**Issue by pboehm** [appsmithorg/appsmith#31207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I want to use an Authenticated API data source with OAuth 2.0 authentication and the "client credentials" grant type, clicking on "Save & Authorize" fails with 500 and the following exception is logged:

```
appsmith  | backend stdout | java.lang.IllegalArgumentException: URI must not be null                                                                                                                             
appsmith  | backend stdout |    at org.springframework.util.Assert.notNull(Assert.java:204)                                                                                                                       
appsmith  | backend stdout |    at org.springframework.web.util.UriComponentsBuilder.fromUriString(UriComponentsBuilder.java:228)                                                                                 
appsmith  | backend stdout |    at com.appsmith.server.solutions.ce.AuthenticationServiceCEImpl.lambda$getAuthorizationCodeURLForGenericOAuth2$3(AuthenticationServiceCEImpl.java:145)                            
appsmith  | backend stdout |    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)                                                                                                    
appsmith  | backend stdout |    at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)                                                                                        
appsmith  | backend stdout |    at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:293) 
appsmith  | backend stdout |    at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:474)
appsmith  | backend stdout |    at com.appsmith.server.configurations.MDCConfig$MdcContextLifter.onNext(MDCConfig.java:53)
...
```

By examining the code in `AuthenticationServiceCEImpl.java` I would suspect that the "client credentials" grant is not implemented correctly or is treated as an "authorization code" grant internally, as it requires an "Authorization URL". This is the cause of the `IllegalArgumentException: URI must not be null` from the stack trace above.

### Steps To Reproduce

The exception happens before any communication is done with the API, so no real OAuth 2 service is required to reproduce the failure, so `https://auth.example.com` is used as a placeholder.

1. Create an new application
2. Create a new "Authenticated API" datasource
3. Use `https://auth.example.com` as URL
4. Select "OAuth 2.0" as authentication
5. Select "Client Credentials" as grant type
6. Use `https://auth.example.com/oauth/token` or any other URL as "Access Token URL"
7. Insert `test` for "Client ID" and "Client Secret"
8. Use any scope like `openid`
9. Use `https://auth.example.com/` as "Audience" and "Resource"
10. Click on "Save & Authorize"
11. Receive a 500er response:

```
{
  "responseMeta": {
    "status": 500,
    "success": false,
    "error": {
      "code": "AE-APP-5000",
      "title": "Internal server error",
      "message": "Internal server error while processing request",
      "errorType": "INTERNAL_ERROR"
    }
  },
  "errorDisplay": "AE-APP-5000: Internal server error while processing request"
}
```

### Environment

Production

### Version

Community Self Hosted - v1.13

**Comment by Nikhil-Nandagopal** [comment]
@pboehm can you tell us which provider are you trying to authenticate with? It'll help us reproduce the issue internally

**Comment by pboehm** [comment]
Hi @Nikhil-Nandagopal,

I'm using a self-hosted [Keycloak](https://www.keycloak.org/) instance to handle authentication/authorization for an internal API for which I'm building the corresponding Appsmith App.

When I select [`Authorization Code`](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow) as grant type for the Authenticated API Datasource in Appsmith and provide "Access Token URL" and "Authorization URL" and all other input values, I can click on "Save & Authorize" and I'm being redirected to Keycloak to authorize Appsmith to act on behalf of a normal real Keycloak user. This works as expected and Appsmith can talk to the internal API on behalf of the normal Keycloak user.

But I do not want Appsmith to act on behalf of a normal Keycloak user and instead act as itself via a "Service Account" and that is what the [`Client Credentials`](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow) grant type is for. The client credentials flow does not require an "Authorization URL" but only an "Access Token URL" because there is no authorization redirect involved. The Appsmith frontend seems to handle this correctly, but the Appsmith backend requires an "Authorization URL" to be present even for `Client Credentials` and throws the shown `IllegalArgumentException`.

I'm not providing a step-by-step guide for reproducing this with Keycloak here, because you can reproduce it without a real "OAuth Server" by using any Access Token URL (`https://auth.example.com/oauth/token` as an example), because the exception is thrown before any kind of communication between Appsmith and the OAuth Server takes place.

**Comment by sneha122** [comment]
@pboehm Thanks a lot for reporting this issue!! While we are working to resolve the issue, can you please try creating queries on that datasource even if authorisation has failed? I believe the queries should be working fine. Please let us know if queries work or not.

**Comment by pboehm** [comment]
> @pboehm Thanks a lot for reporting this issue!! While we are working to resolve the issue, can you please try creating queries on that datasource even if authorisation has failed? I believe the queries should be working fine. Please let us know if queries work or not.

Hi @sneha122,

I can confirm that queries actually work fine if I ignore the errors during datasource creation with grant type `client credentials`. Thanks for the workaround!

**Comment by sneha122** [comment]
@pboehm Awesome!! Thanks a lot for checking and confirming the same, we will soon be fixing the errors on datasource creation as well.
