### ISSUE TITLE
[Bug]: Unable to Create Appsmith AI Datasource

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#31209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to create a new AI Datasource and uploading a file as context, the Save action fails with the error: `Your query failed to execute`. 
![image](https://github.com/appsmithorg/appsmith/assets/101268423/c82cac5e-d8a9-4448-85db-98b66dd9fa56)
When attempting to click the Save button for the second time, the error `Duplicate key error: An object with the name null already exists. Please use a different name or reach out to Appsmith customer support to resolve this.` gets displayed.
![image](https://github.com/appsmithorg/appsmith/assets/101268423/91882030-5edb-4342-b43f-61016a0e04d2)

### Steps To Reproduce

1. Create a new **Appsmith AI** Datasource.
2. Upload a **file** as context.
3. Click the **Save** button.

### Environment

Production

### Version

Appsmith Cloud v1.14

**Comment by dvj1988** [comment]
@ame-appsmith This is resolved. Attaching a video of the flow here.

https://github.com/appsmithorg/appsmith/assets/18716465/4be98242-522e-40a7-aec1-2d3e306786ca
