### ISSUE TITLE
[Bug] Sections UI doesn't work for Action editor forms like it does for Datasource editor forms

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3121]
## Description

I have configured a section in an action form for the Firestore actions, but the section title is not rendered and a collapsible section (like in Datasource forms) is not generated.

Example, [Firestore's `editor.json`](https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor.json#L95):

![Screenshot 2021-02-20 at 17 41 51](https://user-images.githubusercontent.com/120119/108594937-ecd1ca00-73a2-11eb-8294-ff2dd9f7c39a.png)

Example, [Postgres' `form.json`](https://github.com/appsmithorg/appsmith/blob/release/app/server/appsmith-plugins/postgresPlugin/src/main/resources/form.json#L51):

![Screenshot 2021-02-20 at 17 42 21](https://user-images.githubusercontent.com/120119/108594945-fe1ad680-73a2-11eb-854a-b851a045ece9.png)

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @hetunandu can you guys look into this?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal we do not have collapsible sections on the query editor as per UQI designs today. Do we want to extend scope to add this to UQI?

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair right this is no longer valid
