### ISSUE TITLE
chore: refine WDS modal header layout

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#31252]
Currently heading uses `caption` token incorrectly and is too spread out.
<img width="669" alt="image" src="https://github.com/appsmithorg/appsmith/assets/80973/52fa6f20-6ed3-4d45-96fd-4d86608d7d9c">

Better placement of elements is needed, e.g.
<img width="554" alt="image" src="https://github.com/appsmithorg/appsmith/assets/80973/3421f9ab-a1b9-4130-b514-2669faa2e339">

**Comment by ichik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/31252?planning-poker) with Zenhub @KelvinOm @tbrizitsky

**Comment by KelvinOm** [comment]
It seems that we use caption text variant in the header ˆ(
