### ISSUE TITLE
[Bug]: `Internal server error` When Removing User from Workspace

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#31264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user is on Cloud and is not able to remove users from a particular workspace, even though he is the creator of the workspace and has Administrator rights, getting an `internal server error`. They get the same error even if trying to change the Role of a user. These operations are working fine in another workspace.

More details and a screen recording are in [this Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1708675392175179).

### Steps To Reproduce

Click on Share and try to remove users from the workspace.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This was a bad state that the user reached in their workspace and is now fixed so closing this.
