### ISSUE TITLE
[Bug]: TypeError: Queryname.run is not a function

### ISSUE THREAD

**Issue by LPTrungGTN** [appsmithorg/appsmith#31262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

TypeError: Queryname.run is not a function
    at Object.$$result (eval at e (indirectEval.ts:4:14), <anonymous>:17:14)

in my application when update sub application first time it okay, however next time it will log this error, however with another location action no proble.

about solution in this page https://community.appsmith.com/solution/querynamerun-not-function
it fail because query function stay in another locations can not use this

### Steps To Reproduce

i don't know to description, because It only happens when performing the action for the second time in the only 3 tabs in my entire application, I have tried logging all the steps and everything is ok, only the run query step is the second time I get an error above.

### Environment

Deploy Preview

### Version

Community v1.10

**Comment by Nikhil-Nandagopal** [comment]
@LPTrungGTN we'd like some more information on how to reproduce it with a video & a set of logs when the error occurs. Please reach out when you have that information

**Comment by LPTrungGTN** [comment]
@Nikhil-Nandagopal  thanks you i already fix it, i thinks because appsmith not good support asynchronous, after i set await full it working oke.
