### ISSUE TITLE
[Bug] Appsmith logo weird stretch in view mode on safari 

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3126]
## Description
<img width="272" alt="Screen Shot 2021-02-20 at 10 08 04 PM" src="https://user-images.githubusercontent.com/12022471/108617124-cf037400-7439-11eb-9354-05dc34feac85.png">

### Important Details
 - Version: All
 - OS: MacOSX
 - Browser safari

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena can we quickly push this out?
