### ISSUE TITLE
Radio cannot be without the selected value

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#31290]
<img width="440" alt="Untitled" src="https://github.com/appsmithorg/appsmith/assets/11555074/6fe04a85-dedf-4b33-92d7-bd30964ebf36">

**Comment by marks0351** [comment]
observation: by default(when a radio group is dropped and no changes are made) accessibility is fine but when I am creating custom options like the number options in the radio group accessibility seems to be lost.
cc: @KelvinOm @jsartisan

**Comment by jsartisan** [comment]
This is fixed here - https://github.com/appsmithorg/appsmith/pull/31382
