### ISSUE TITLE
[Bug]: On pulling the remote changes, no positive feedback is given and the screen remains still for a good 6-7 seconds

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we pull remote changes into our branch, we do not see a loading state or a response that lets the user know that his action has been performed for at least a few seconds. This will lead the user to click the pull button multiple times till they realise that the changes are being pulled.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/39921438/09b1b699-4aed-4dc4-975a-0834c462a3ea

1. For a git connected app, make changes to the remote branch.
2. Now come to the app and refresh the page.
3. Click on the pull button in the bottom bar.

**Expected:** As soon as the user clicks on the pull button, they should get a response/loader which lets them know that the changes are being pulled.
**Actual:** No visual feedback is given to the user for 6-7 seconds.

### Environment

Production

### Version

Cloud

**Comment by brayn003** [comment]
Just tested this on app.appsmith.com. It seems to be working fine.
Attaching loom video for reference - https://www.loom.com/share/155c1eb98a214c8b84af824e8cf448b5?sid=a4fd6454-efbd-4d5c-9b32-5d77f8e7831b

**Comment by brayn003** [comment]
Closing this for now

**Comment by shadabbuchh** [comment]
@brayn003 I am still able to reproduce it from my end. In your video I see that you are pulling changes for a protected branch. Can you please try for an unprotected branch. 
https://www.loom.com/share/f82649c549a64a5e838b34ad75fba110

**Comment by brayn003** [comment]
Looks like this issue persists for non-protected branches. Will take a look

**Comment by shadabbuchh** [comment]
Loading state for pull action verified on release:
https://jam.dev/c/fad0685d-624a-4142-bc06-ce22f2b04deb
