### ISSUE TITLE
[Feature]: Improve Partial Import Export (PIE) API to allow adding building blocks to apps.

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#31315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The primary aim of this feature is to empower users by enabling them to seamlessly integrate building blocks along with their associated components (queries, JavaScript, datasources, and widgets) into their existing applications through drag-and-drop functionality.

**Proposal**
To achieve this objective, the proposed approach involves enhancing the PIE API to facilitate backend operations. This enhancement will allow the backend to efficiently add queries, JavaScript functions, and datasources to existing applications. Subsequently, the updated application's widget structure will be transmitted back to the client for rendering, ensuring a smooth and cohesive user experience.

### Why should this be worked on?

This process is critical for the successful implementation of building blocks in the explorer and the client side cannot effectively manage the operations of queries, JS and datasources within an App. These processes are better handled on the backend.

**Comment by AnaghHegde** [comment]
Tasks in backend
- [ ] Fetch the json from the cs with error handling
- [ ] Partial Import method to create resources for the blocks
- [ ] Check for entity refactored and then update the DSL accordingly to keep binding correctly
- [ ] Add tests for the above step, rest all are already covered

**Comment by AnaghHegde** [comment]
API contract after discussion with @jacquesikot 

POST /{workspaceId}/{pageId}?templateId={templatedId}
