### ISSUE TITLE
[Feature] Appsmith functions should have object based signatures instead of functional arguments

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3132]
## Summary

Appsmith functions should have object based signatures instead of functional arguments.

## Motivation

It's very hard to debug & understand the code when functions such as `Api1.run(undefined, undefined, params)` are written. A much better way to write these functions would be: 
```
Api1.run(
onSuccess: () => {},
onError: () => {},
params: {}
)
```
This ensures cleanliness of code & much greater user understandability of the Appsmith product.

**Comment by rishabhrathod01** [comment]
`Api.run` now supports params as object. Also, success and failure callbacks can not be then and catch block. I believe this was the intention with above feature request hence closing this now.
