### ISSUE TITLE
[Bug]: On adding any new template, an internal server error pops up.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to add any new template from the Create New menu, an internal server error pops up.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/5dd7b95f-c9be-4861-93a3-24158eb1c7bf

### Environment

Release

### Version

Cloud

**Comment by sneha122** [comment]
This issue is fixed with [EE PR](https://github.com/appsmithorg/appsmith-ee/pull/3612)
