### ISSUE TITLE
[Bug]: Renaming workflow from within a workflow throws error

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#31333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1431" alt="Screenshot 2024-02-28 at 1 36 22 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/af9d96f6-c932-449e-a142-df84d0ae770f">

### Steps To Reproduce

1. Go inside workflow
2. Rename workflow from the General settings of Workflows or from the Workflow's page.
3. Observe it throws error

### Environment

Release

### Version

Release

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31333?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
