### ISSUE TITLE
[Task]: unit test case for RTS- workflowproxy ( reponse data structure)

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#31349]

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31349?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by ayushpahwa** [comment]
Stale generic issue, broken down now
