### ISSUE TITLE
[Task]: Navigation issue in cypress runs for workflow

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#31340]
### SubTasks

For cypress tests for workflow, on navigating to settings/data it fails blocking tests to run locally

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31340?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
