### ISSUE TITLE
Update logo and beta tag for Workflows

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#31357]
@parth-appsmith  - TBD

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31357?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
