### ISSUE TITLE
[Bug]: error handling for worker exceptions

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#31359]
worker launch retry
create default namespace,. if it doesn't exist
create search attribute , if it doesn't exist

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31359?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
