### ISSUE TITLE
[Task]: Benchmark concurrent workflows on a T2.MEDIUM

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#31356]
```[tasklist]
### Tasks
```

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31356?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
