### ISSUE TITLE
Workflow/packages should only show up in workspace if there is at-least one resource

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#31358]
There should be no default state for Workflows and Packages in a workspace

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31358?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31358?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
