### ISSUE TITLE
[Task]: Analytics Events

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#31355]
[Notion Doc](https://www.notion.so/appsmith/Workflows-Analytics-0c6bc3ace7fa4671a6d042cbef4d8ba0)

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31355?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12
