### ISSUE TITLE
[Task]: documentation wiki

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#31360]

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31360?planning-poker) with Zenhub @ayushpahwa @nsarupr @Parthvi12

**Comment by srix** [comment]
2 hour peer activity

**Comment by nsarupr** [comment]
Closing this as basic documentation is complete.
