### ISSUE TITLE
[Bug]: Entering or exiting split pane mode with query selected - query's title gets selected for renaming

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open up or close out the split pane view with a query selected, the query's title gets selected for edit/renaming

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/b1c7487f-045d-4522-854e-4217a2865cbc

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=ed060833054f4e54890c1c8cc46640db&pm=s
