### ISSUE TITLE
[Bug]: In the split pane compressed view, some tabs are not visible, and bottom pane comes up empty if errors selected in expanded view. [For API queries]

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the split pane view, the Errors/ Logs/ Inspect Entity tabs are not seen. We cannot see the errors in the compressed split pane view due to this. 
In this scenario, if in the expanded view, Errors tab is selected, and we compress to view in the split pane mode, the bottom pane comes up as empty and the focus goes to the Api text box [This seems to be specific for API queries]

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/4dd3f1d2-b447-40ba-bf5e-157bf46fa72d

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=191cfd6d0acf450abd71e5550aa7f23a&pm=s
