### ISSUE TITLE
[Bug]: Appsmith Backup Runs Every Day With `APPSMITH_BACKUP_CRON_EXPRESSION=disable`

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#31393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Appsmith backup runs every day event though the user is using the expression `APPSMITH_BACKUP_CRON_EXPRESSION=disable`.
[Front thread](https://app.frontapp.com/open/cnv_17m4gnrg?key=CJAFHzuLbMy4SAVQbFtrNQ-0COWq8u3y) for more details.

### Steps To Reproduce

1. Set the expression `APPSMITH_BACKUP_CRON_EXPRESSION=disable`.
2. Restart Appsmith.

### Environment

Production

### Version

self-hosted

**Comment by pratapaprasanna** [comment]
This issue is resolved
