### ISSUE TITLE
[Bug]: The edit Link seems to be missing in the rename application dropdown

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#31399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The edit Link seems to be missing in the rename application dropdown
<img width="385" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/48cbb197-acfe-434e-a3f6-600120f355ec">
<img width="631" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/83e51544-9d1e-4059-b4c5-c74da5f5d535">

### Steps To Reproduce

1. go to application 
2. click on app name 
3. inside the rename dropdown the edit link is missing as it is present in our current versions

### Environment

Release

### Version

v1.15

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=ee5d7f88f31d4246a67271e65911d307&pm=s

**Comment by hetunandu** [comment]
We have removed this as part of IA change
