### ISSUE TITLE
[Bug]: The user should be allowed to Adjust the Slipt screen according to his needs and also same goes in pages section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#31401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user should be allowed to Adjust the Slipt screen according to his needs and also same goes in pages section

### Steps To Reproduce

1. go to application
2. enable split screen 
3. Now try to adjust the screen to make the query screen little bigger 
4. this is not enabled 

### Environment

Release

### Version

v1.15

**Comment by rohan-arthur** [comment]
closing this as it is not a requirement for this milestone, and a known limitation,
