### ISSUE TITLE
[Bug]: scrolling inconsistency is seen in the Error tab 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#31409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

scrolling inconsistency is seen in the Error tab 
https://www.loom.com/share/02e723bf531844a0b3135813955f5a38?sid=d4961233-7c2d-47f4-9f0a-21af9a404d5c

### Steps To Reproduce

1. go to application
2. go to edit mode and enable split screen 
3. now add some new query and try to run it
4. make sure there is some miss in query and it throws error
5. now scroll in the error tab

### Environment

Release

### Version

v1.15

**Comment by hetunandu** [comment]
Issue is resolved by not showing the error tab in the Query section when on split screen
