### ISSUE TITLE
[Bug]: The new query editor looks empty when user tries to add the new curl API 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#31408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The new query editor looks empty when user tries to add the new curl API 
https://www.loom.com/share/fbaaf26a70684646b437405c0163e2ce?sid=960387d1-a0e7-425f-aea1-ba1cbf9b9f9e

### Steps To Reproduce

1. go to application
2. go to edit mode and enable split screen
3. got to queries tab 
4. click on + icon try to add new curl datasource
5. the query pane looks empty now

### Environment

Release

### Version

v1.1.5

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=b659d0f88329406abc685173f5b06633&pm=s
