### ISSUE TITLE
[Bug]: Command + D does not close / open the debugger in the Queries section in split pane views.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I do Command + D, it does not open or close the debugger in the Queries / JS view, both in expanded and compressed state.
Note: This works only for the UI view. 
In non split pane views [current prod], Command + D works on both UI as well as Queries view.

### Steps To Reproduce

1. Create a new query or js object
2. Try to close the debugger using Command + D for the query view. It does nothing. 
3. Try the same in the UI view, it works. 

### Environment

Release

### Issue video log

https://www.loom.com/share/fa09fcc562a343569bd68cbe459c6659

### Version

Cloud

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=d2ee79eb0ae44d228741d2da37dfd332&pm=s
