### ISSUE TITLE
[Bug]: The error code and tab names overlaps in the query response section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#31407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The error code and tab names overlap in the query response section
![image](https://github.com/appsmithorg/appsmith/assets/45958978/3f63d3d1-3e68-4a09-bc62-ec18cc853b68)

### Steps To Reproduce

1. go to application
2. go to edit mode and enable the split screen 
3. add any new api
4. run the api make sure that the api fails
5. Now check the response section

### Environment

Release

### Version

v1.15

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by hetunandu** [comment]
Solved by moving the API run meta to a new row inside the response tab
