### ISSUE TITLE
[Bug]: Generate page with Data - Created Queries are hidden in the dropdown and not immediately visible to user

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Queries created through generate page with data are not immediately visible - though they are present in the number dropdown on the right side.

### Steps To Reproduce

https://www.loom.com/share/4b1b131253784b1f9dec875d8bf827f4

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=ba5c0e79ed224a61ad8265c29f6b05d9&pm=s

**Comment by hetunandu** [comment]
Solved with IDE tabs Revamp
