### ISSUE TITLE
For Module instance missing state in app, we are getting the CTA for Import Package, instead of update package

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31439]
https://www.notion.so/For-Module-instance-missing-state-in-app-we-are-getting-the-CTA-for-Import-Package-instead-of-upda-b9b9b576ceeb4961a78c8820b96bd210

**Comment by kamakshibhat-appsmith** [comment]
Steps 
1. Add APP first, you'll get Import package CTA
2. now Add Package , publish, the CTA is not updating
In multiple cases, these type of states are not refreshing
[UpdateCTA APP.json](https://github.com/appsmithorg/appsmith/files/14513893/UpdateCTA.APP.json)

[UpdateCTAPACKAGE.json](https://github.com/appsmithorg/appsmith/files/14513888/UpdateCTAPACKAGE.json)

**Comment by subrata71** [comment]
RCA: The packageUUID in these two files are different. Can you please try with a packageUUID which matches the ones present in the application? @kamakshibhat-appsmith

**Comment by kamakshibhat-appsmith** [comment]
Not reproducible, closing it for now @subrata71
