### ISSUE TITLE
For app level share with developer access, in the feature branches, module Instance API is not returning any existing previous data If a new module instance is created , the data is updating 

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31434]
https://www.notion.so/For-app-level-share-with-developer-access-in-the-feature-branches-module-Instance-API-is-not-retur-8a329e048df04d6bb9b3ee4e0be7975a

**Comment by kamakshibhat-appsmith** [comment]
@nidhi-nair The same problem is happening with multi-page apps . Other than page 1(homepage), rest of the pages are not having any instance data in the APIs for app based developer access

**Comment by kamakshibhat-appsmith** [comment]
Fixed @nidhi-nair

**Comment by kamakshibhat-appsmith** [comment]
Fixed @nidhi-nair
