### ISSUE TITLE
Unable to import an app with module instances if the package version is now ahead of the version when module instances were createdScenario 1: Create a git connected app which has module instances, Republish the package and try to import the app. Error is thrownScenario 2: Create a git connected app which has module instances and atleast one feature branch(feature branch is insync with main), import the git app , now republish the package                     Notice if you create a local out of remote feature branch in the imported app, it throws error working with older instanceScenario 3. export an app with module instances. Republish the package. try to import in the same workspace(Non-Git connected scenario)

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31432]
https://www.notion.so/Unable-to-import-an-app-with-module-instances-if-the-package-version-is-now-ahead-of-the-version-whe-ee8af40b07f34fc9adc50ab79a40e7ac

Unable to import an app with module instances if the package version is now ahead of the version when module instances were created
Scenario 1: Create a git connected app which has module instances, Republish the package and try to import the app. Error is thrown

Scenario 2: Create a git connected app which has module instances and atleast one feature branch(feature branch is insync with main), import the git app , now republish the package Notice if you create a local out of remote feature branch in the imported app, it throws error working with older instance

Scenario 3. export an app with module instances. Republish the package. try to import in the same workspace(Non-Git connected scenario)

**Comment by kamakshibhat-appsmith** [comment]
Scenario 2 is failing , Please confirm . If this is unrelated to BE, let me know will create a separate ticket for FE and close this @nidhi-nair

**Comment by kamakshibhat-appsmith** [comment]
@nidhi-nair 
one addition in Scenario 2: After all the below steps are done, you will get suspended states in the app. Republish the package for the suspended states to disappear and app starts crashing 

> Create a git connected app which has module instances and atleast one feature branch(feature branch is insync with main), import the git app , now republish the package Notice if you create a local out of remote feature branch in the importe

d app,

**Comment by kamakshibhat-appsmith** [comment]
@nidhi-nair  Please check this as well

**Comment by kamakshibhat-appsmith** [comment]
Fixed @nidhi-nair
