### ISSUE TITLE
On package import, the validation for package name and UUID for import is failing . If package has different name but same UUID, the validation is not happening and import is not failing

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31441]
https://www.notion.so/On-package-import-the-validation-for-packahe-name-and-UUID-for-import-is-failing-If-package-has-d-ddc951028b6d4edebff6327fca5e5605

**Comment by kamakshibhat-appsmith** [comment]
Reopening as the latest PR doesn't seem to fix this on release-ee

**Comment by kamakshibhat-appsmith** [comment]
This use case is working now @nidhi-nair
