### ISSUE TITLE
[Bug]: Page reference is incorrect on navigating between queries

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#31458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Page reference is getting lost on navigating between queries

### Steps To Reproduce

1. Create an app
2. Create two pages within the app, with one containing queries. And one being empty (with no queries/widgets etc)
3. Follow the remaining steps as mentioned here https://www.loom.com/share/91e2e240170a447b9c7a8a34316b8ab3?sid=d5e1a5f3-611b-4a08-80d6-7aa8d1428507

### Environment

Release

### Severity

High (Blocker to building)

### Issue video log

https://www.loom.com/share/5e228126304742259d90c8d35fd92ce8

### Version

Release

**Comment by rohan-arthur** [comment]
for internal tracking: https://www.notion.so/appsmith/Page-reference-is-incorrect-on-navigating-between-queries-28a34b4f394c4caabfabb49bd0934dc9
