### ISSUE TITLE
[Bug]: Making application Public, and making application Forkable are not treated as new commits in a git connected app. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Making application Public, and making application Forkable are not treated as new commits in a git connected app. 

### Steps To Reproduce

1. Create a git connected app, add a few pages/widgets etc on master, and create a few branches say test1 and test2 from master.
2. Now, in the test1 branch, From Settings - > Share and Embed -> Turn on "Make Application Public" and "Make Application Forkable"
3. Click on the Commit Changes, and note that there are no changes to commit. 
4. Now merge this branch to test2 branch
5. Go to Settings - > Share and Embed in test2 branch. 
6. Note that Make Application Public is enabled, but Make Application Forkable is disabled.

This behavior seems incorrect. 
1. If the two settings are not required to be recognised by git, as they are app level changes, then both options should have been enabled even in test2 branch
2. If they are required to be recognised by git as new commits, then, they should appear as commits in the test1 modal, and on merging test1 to test2, test2 should have both the settings enabled.

### Environment

Production

### Severity

High (Blocker to building)

### Issue video log

https://www.loom.com/share/6fc4f403faea48fd8283e0847e568354

### Version

Cloud

**Comment by RakshaKShetty** [comment]
Still we can repro it 
<img width="369" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/6576fa9c-e2eb-4965-adcc-052766410c29">

**Comment by nidhi-nair** [comment]
@RakshaKShetty is this just for sharing or forkable? Sharing would not be treated as a git persisted property since permissions are local to an instance.

**Comment by nidhi-nair** [comment]
Closing as both these properties are meant to be tracked at instance level only.
