### ISSUE TITLE
[Bug]: Excessive space is seen below the pages dropdown

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#31450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Excessive space is seen when only one page is present

### Steps To Reproduce

1. Create an app
2. Notice that excessive space is seen between the listed page and the entity explorer
<img width="819" alt="Screenshot 2024-03-04 at 10 29 08 AM" src="https://github.com/appsmithorg/appsmith/assets/109572422/17d655aa-3c85-40b1-a5e1-2cf6da8de813">

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/bf4c06deff9e4fc3aa7ffba827379237

### Version

Release

**Comment by laveena-en** [comment]
![image](https://github.com/appsmithorg/appsmith/assets/109572422/5f695b74-2fc2-4f89-9bd4-648fd38cfcf6)

**Comment by rohan-arthur** [comment]
for internal tracking: https://www.notion.so/appsmith/Excessive-space-is-seen-below-the-pages-dropdown-5a5c7933051e48739607562b2ac33376
