### ISSUE TITLE
[Bug]: Queries section is seen in the preview mode instead of the canvas.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#31451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Queries section is seen in the preview mode instead of the canvas/UI.

![image](https://github.com/appsmithorg/appsmith/assets/109572422/24da7ba9-83d5-485c-b301-0f5007eee1e4)

### Steps To Reproduce

1. Create an app
2. Create a page within the app and open the query pane
3. Switch to preview mode
4. Notice that the edit query page is seen in preview mode instead of the canvas/widget

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/939ccbcd2a5b48b4b9c81fc7734568a9

### Version

v1.15

**Comment by rohan-arthur** [comment]
for internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=8cf1b431b27248b09ac079908a111a5e&pm=s
