### ISSUE TITLE
[Feature]: Ability to deploy changes made in one branch to other users

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#31474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When a user makes changes to one branch (like merge to master), trigger an automation to show the changes to other users (instead of relying on them to click on a button)

### Why should this be worked on?

This will help in developing apps distributed among users easily

**Comment by infinitetrooper** [comment]
@pratapaprasanna  - Do you mean a user should see there are upstream changes on a branch is someone makes a commit to that branch?

**Comment by Nikhil-Nandagopal** [comment]
Closing this issue
