### ISSUE TITLE
[Feature]: ability to show popup for end users when app crashes

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#31473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When an app crashes in appsmith. If appsmith has an ability to show a popup to end users in case of app crashes that would help in sharing the issues directly with the appsmith team

### Why should this be worked on?

This helps in sharing bug-report or any related information faster with with the respective teams

**Comment by Nikhil-Nandagopal** [comment]
End users wouldn't have information to share with Appsmith. Developers can have a way to get the logs and share it with us
