### ISSUE TITLE
[Bug]  oAuth is not functional 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3148]
Steps to reproduce:
1) Add an API
2) Click on the "Set as datasource"
3) Add details "Authentication Type : oAUTH 2.0 "
4) Add Grant Type : Authorization Code
5) Click on Save and Authorize 
and Observe

Observation:
It is observed that an error is displayed to the user 
"{"responseMeta":{"status":500,"success":false,"error":{"code":5000,"message":"Internal server error while processing request"}}}"

Video:
https://www.loom.com/share/7246db665a6547bb9ffd1e33ebad128e

**Comment by prapullac** [comment]
Reopening the issue as it is still displays 
Authorisation Error
Error 400: invalid_request
Missing required parameter: scope


![Screenshot 2021-02-23 at 3 50 54 PM](https://user-images.githubusercontent.com/71753653/108830089-fcdde980-75ee-11eb-870e-698ff5591b0a.png)

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal  This is a requirement specific to authorization servers. For example Google needs a scope, and needs specific values for this scope. How do solve for UX here?

**Comment by Nikhil-Nandagopal** [comment]
@prapullac we can close this since the screen is giving information on the parameters which are missing.
@nidhi-nair is scope mandatory? If it is we can add that check.

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal  It is not, depends entirely on the Auth server (Google needs it, Facebook does not)

**Comment by prapullac** [comment]
@nidhi-nair:
Please find the screenshot after entering the required fields

![Screenshot 2021-02-23 at 5 29 11 PM](https://user-images.githubusercontent.com/71753653/108841009-1e45d200-75fd-11eb-9767-92782bb63bfe.png)

**Comment by prapullac** [comment]
Closing this issue as it is working as expected
