### ISSUE TITLE
[Bug]: Entering a page URL does not take us to the desired page in a git connected app

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a git connected app with a couple of branches, on copying a page URL & pasting it in another tab, I am not redirected to the desired page (of which I copy pasted the URL).
Please watch the attached video to understand the issue in detail.

### Steps To Reproduce

1. Open a git connected app.
2. Create a couple of branches in addition to the master branch.
3. Go to any branch (apart from the default one) and copy the URL of any one of the pages.
4. Paste the URL in a different tab.

**Expected:** The page of which the URL was copied should open in the new tab.
**Actual:** In same instances the screen goes blank and in other cases we end up on a different page of a completely different branch.

### Environment

Production

### Severity

High (Blocker to building)

### Issue video log

https://www.loom.com/share/dc2625ae5ac341f1b2234431faaafd6f

### Version

Cloud

**Comment by rohan-arthur** [comment]
internal tracking: https://www.notion.so/appsmith/Test-party-New-IDE-457ce3d37cbc44c08f4a8b877de2f984?p=14c3c6186fa54de9956a222ab4d4ff16&pm=s

**Comment by hetunandu** [comment]
This is not an IDE issue. Removing the labels and assigning the correct pod members

**Comment by brayn003** [comment]
Hello @shadabbuchh, this seems to be working fine on my end. Sharing a loom video for the same -
https://www.loom.com/share/d1efdf1d8f4a4283860280cc50d856c1?sid=68df2eed-4cb0-488d-acc2-172f21c64f45

**Comment by brayn003** [comment]
Closing this issue for now, feel free to reopen it if I am missing something
