### ISSUE TITLE
When a new package is created, that particular workspace should come at the top when homepage is revisited.

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31502]
https://www.notion.so/When-a-new-package-is-created-that-particular-workspace-should-come-at-the-top-when-homepage-is-rev-6cee2f0b20b1446c808bbc512cd83097

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by subrata71** [comment]
Related issue: https://github.com/appsmithorg/appsmith/issues/29590
