### ISSUE TITLE
[Intermediate Issue ]After adding the datasource, the schema is showing permission error but works on refresh

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31500]
https://www.notion.so/After-changing-the-query-name-the-schema-is-showing-permission-error-but-works-on-refresh-1b7f81dd84b74021b1a97c62f837ef52

LOOM--> https://www.loom.com/share/9d32066099d34f05bbef56e929a32d99

**Comment by kamakshibhat-appsmith** [comment]
This is still happening @subrata71

**Comment by kamakshibhat-appsmith** [comment]
This is still happening https://www.loom.com/share/eefaca11e42e45bcb915c53b5987fc7a @subrata71

**Comment by kamakshibhat-appsmith** [comment]
This is not reproducible
