### ISSUE TITLE
1. Click on Save Datasource in API editor2. You will be redirected to the datasource config page and then SAVE it3. you will be redirected to the wrong URL expectation: redirect to the same API editor page 

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31506]
https://www.notion.so/1-Click-on-Save-Datasource-in-API-editor2-You-will-be-redirected-to-the-datasource-config-page-and-018e74d77e5740fea33987839c1a111b

https://www.loom.com/share/33eef1ea703743eaa30860376ebdf552

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
