### ISSUE TITLE
[Fork] Should we allow forking if I delete all the module instances in the edited version but the published version still has references?Reason : We fork the edited version and not published version Parked it to have discussion later on for v2

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31511]
https://www.notion.so/Fork-Should-we-allow-forking-if-I-delete-all-the-module-instances-in-the-edited-version-but-the-pub-b045c9deb1fe47508e33fa5c8f2777c6

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
