### ISSUE TITLE
Count of queries using the datasource in a package editor is incorrect

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31513]
https://www.notion.so/Count-of-queries-using-the-datasource-in-a-package-editor-is-incorrect-e95a4ac557e5418494f9b578d74d2972

**Comment by subrata71** [comment]
Changed the assignee based on [this](https://docs.google.com/spreadsheets/d/1zZX8wrnBvfNaQltCMFBq8s0_I3frxti7RKEflMxHrWQ/edit#gid=0&range=52:52)

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
