### ISSUE TITLE
[Task]: Buttons on inline buttons widget shift positions after being placed on canvas

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31537]
### SubTasks

- related to WDS (accessed on Anvil DP: https://ce-28238.dp.appsmith.com/)
- [recording](https://www.loom.com/share/e8175a32e3fc452c83d392111fbf7f25?focus_title=1&muted=1&from_recorder=1)

**Comment by jsartisan** [comment]
This is fixed with https://github.com/appsmithorg/appsmith/pull/31701
