### ISSUE TITLE
[Bug]: List of pages does not load seamlessly when we click on `Editor`

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The list of pages loads with a lag once we go to `Editor`.

### Steps To Reproduce

1. Login with the below credentials in release:
-username: ide-test@appsmith.com
-password: ide-test@appsmith.com
2. Create an app with 4-5 pages.
3. Now from `Data` go to `Editor`.

**Expected:** The list of pages should load seamlessly.
**Actual:** We see a lag in loading the list of pages.

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/04badc3c2c0a480cbada8fdd563ceda0

### Version

Cloud

**Comment by hetunandu** [comment]
Closing as we added a dropdown for the pages now
