### ISSUE TITLE
[Bug]: Authenticated API & Authenticated graphQL API with OAuth2 throws 404 error in workflows

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#31554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/80334441/0d9b9f0b-6ce5-442e-b935-ff637b75257b

### Steps To Reproduce

1. Go to workflow
2. Create authenticated api
3. Select oauth2 as authentication type
4. Observe it throws 404 error 

### Environment

Release

### Severity

High (Blocker to building)

### Version

release

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
