### ISSUE TITLE
[Bug]: Unable to delete module instances which are there in the imported app (the instances fail to delete even after relevant packages are imported and instance is no longer in error state)

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to delete module instances which are there in the imported app (the instances fail to delete even after relevant packages are imported and instance is no longer in error state)

### Steps To Reproduce

1. Import an app with suspended module instance states
2. Import the relevant package and refresh the app page such that no errors are thrown now and module instances start to work
3. try delete these module instances, Error is thrown

### Environment

Release

### Severity

High (Blocker to building)

### Version

Cloud/Release

**Comment by subrata71** [comment]
Closing this issue as it is already resolved and confirmed by @kamakshibhat-appsmith . This [PR](https://github.com/appsmithorg/appsmith-ee/pull/3691) might have resolved this issue.
