### ISSUE TITLE
[Bug]: Ellipsis at the end of every entity name in tabs even in the expanded form

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For the smallest of the names also we are seeing ellipsis at the end in all tabs for Queries & JS Objects.
<img width="304" alt="Screenshot 2024-03-06 at 9 41 12 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/203b20b1-647f-4843-b2e5-a7a853ed0990">
<img width="210" alt="Screenshot 2024-03-06 at 9 41 17 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/70c69011-16ca-44b1-8d42-008ea83b2383">

### Steps To Reproduce

1. Login with the below credentials in release:
-username: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
-password: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
2. Create multiple queries/JS Objects.

**Expected:** The complete name of entities should be visible at least in the expanded mode.
**Actual:** We see ellipsis at the end of every name.

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by hetunandu** [comment]
Solved with IDE revamp
