### ISSUE TITLE
[Bug]: User gets incorrect error messages while creating JS Objects

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On trying to add JS Objects quickly, we see incorrect error messages indicating that the JS Object is already present when in reality it is not.
Please have a look at the video for more details

### Steps To Reproduce

1. Login with the below credentials in release:
-username: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
-password: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
2. In an app after adding the 1st JS Object, add new JS Objects by clicking on `+` button.

**Expected:** The new JS Objects should be created successfully.
**Actual:** We see incorrect error messages.

### Environment

Release

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/9fc8a612960c44cdaebcae60a7fbb9d5

### Version

Cloud

**Comment by hetunandu** [comment]
Resolved by adding a loading state between JS creations
