### ISSUE TITLE
[Feature]: Make both sides of the split pane interact-able

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It will be ideal if the canvas side is also interact-able. Also there should be a way where Entity pane, the canvas & the Property pane are visible to the user so that they can actually utilise and see the value of this feature.

### Why should this be worked on?

Having only one side of the pane (queries part) editable/interact-able in the split pane scenario is like a job half done. User cannot edit queries and at the same time interact with widgets in one screen.
https://www.loom.com/share/0e86342ca9174a70aaa71f84530d3155

**Comment by kocharrahul7** [comment]
This has been addressed already, and will be in release soon.
