### ISSUE TITLE
[Bug]: Order of adding Queries/JS Objects is unconventional

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

New queries/JS objects get added on the LHS of the current entity. Instead they should get added on the RHS.

### Steps To Reproduce

1. Login with the below credentials in release:
-username: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
-password: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
2. Create multiple JS Objects/Queries in an app

**Expected:** The conventional way is to add a new entity on the RHS of the current one.
**Actual:** The new queries are getting added on the LHS of the current one.

### Environment

Release

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/34d408e0cc44483ca5baba0f673b11f6

### Version

Cloud

**Comment by hetunandu** [comment]
Solved with IDE revamp
