### ISSUE TITLE
[Bug]: editable text component for Module instance name

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

there is definitely some change here in this editable text component for Module instance name. The word is getting trimmed now.  sharing the comparison how it used to be before

### Steps To Reproduce

<img width="783" alt="Screenshot 2024-02-29 at 9 19 58 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/d2fb6a2d-a281-412e-b4bd-c8f1ec1a3b88">
<img width="789" alt="Screenshot 2024-02-29 at 9 20 17 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/1be558a9-0c7e-4424-aa65-a167a01668f2">

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud/Self hosted

**Comment by ankitakinger** [comment]
@albinAppsmith This seems to have happened after your change. Could you please take a look?
<img width="1157" alt="image" src="https://github.com/appsmithorg/appsmith/assets/28362912/7cdb1f8a-47c9-4648-be0b-6d4f2a92ef14">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/28362912/87e217bf-16e4-4c18-bf0b-1a2ab642ac0d">
