### ISSUE TITLE
[Bug] Home page does not get dynamically updated until refreshed

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3160]
Steps to reproduce:
1) Ensure there are multiple pages 
2) Add other page as home page 
and observe the page does not get updated

observation:
It is observed that the page does not get updated with home icon until the page is refreshed 

Expectation:
It is expected that the page should get updated dynamically

Video:
https://www.loom.com/share/9936745d5f2f40e192000b2744f08bcb

**Comment by akash-codemonk** [comment]
@prapullac This seems to be working on release.

**Comment by Nikhil-Nandagopal** [comment]
@prapullac please verify
