### ISSUE TITLE
[Bug]: Number formatting changes on read-only text on a read-only widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Number separator, comma, disappears on interacting with the read-only widget

### Steps To Reproduce

1. Drop an input widget and make it number type
2. Make it read-only
3. Enter some number value as its default value and interact with this number in preview mode

[original thread](https://theappsmith.slack.com/archives/C04P60V0VQE/p1709731762264609)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log
https://theappsmith.slack.com/files/U01MZDG0QTA/F06MS2RADQF/screen_recording_2024-03-06_at_6.57.36___pm.mov

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by ramsaptami** [comment]
This is related to current WDS changes on keyValue widget, hence reopening it for further investigation
