### ISSUE TITLE
[Bug]: 302 Redirect Loop with Specific Host Header

### ISSUE THREAD

**Issue by shirobachi** [appsmithorg/appsmith#31613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We've encountered an issue where setting the Host header set to `APPSMITH_HOSTNAME` triggers a continuous loop of 302 redirects to the same URL. Interestingly, when the Host header is incorrect or not set, the server returns a 200 status code. Direct port forwarding to the pod from a browser operates correctly without any issues

### Steps To Reproduce

1. Set the Host header to APPSMITH_HOSTNAME (the one from helm value `appsmith.ingress.hosts[].host`
2. Observe a continuous loop of 302 redirects to APPSMITH_HOSTNAME

### Environment

Production

### Severity

Critical (Broken applications)

### Version

docker tag `v1.11` or `airgap-v1.11` or `release` (on top of helm chart `3.0.7` or `3.0.13`)

**Comment by Nikhil-Nandagopal** [comment]
@shirobachi our airgap version is only available on our enterprise plan. You will have to reach out to sales@appsmith.com to be able to use it.

**Comment by pratapaprasanna** [comment]
We observerd that APPSMITH_CUSTOM_DOMAIN is present for a kubernetes setup which caused this issue
