### ISSUE TITLE
[Bug]: UI/UX issues in the new split pane

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#31612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [x] `Rename application` tooltip appears in hovering over the Workspace name.
<img width="361" alt="Screenshot 2024-02-29 at 3 34 35 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/bb025d19-77f9-4231-95e4-682cde49e344">

- [x] No text/message when there are no JS Objects in split pane
<img width="605" alt="Screenshot 2024-03-01 at 11 46 24 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/019e6faf-38d4-4a2b-b6a8-49597683ed6a">

- [x] The `+` button should be on the RHS of the pane. That is the convention everyone follows. Why are we deviating from the basics?
<img width="59" alt="Screenshot 2024-03-06 at 9 43 32 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/c3bbf688-5cd5-4447-b297-1d39c3714dbb">

- [x] Number showing additional queries should have a `+` in front. e.g. `+2`.
<img width="130" alt="Screenshot 2024-03-06 at 10 08 55 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/8c57167c-1bf4-469b-83a8-3d07ab7b08bd">

- [ ] The query name at the bottom of the dropdown gets clipped.
<img width="226" alt="Screenshot 2024-03-06 at 11 25 56 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/2136dfe3-04ad-4dd2-8508-4771fc4478d0">

- [x] We see a tooltip even when a query doe not have ellipsis & the name is completely visible.
<img width="122" alt="Screenshot 2024-03-06 at 4 24 36 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/4034bb41-2ae5-4f52-9e4e-272a2de0b9cc">

- [x] Not all of the queries show up in tabs in both the expanded & split pane form.
<img width="1089" alt="Screenshot 2024-03-06 at 4 28 52 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/ddf27e44-4748-46ce-bc7d-73772e7806a4">

- [x] There should’ve been a pane resizer in order to increase/decrease the width of the query pane as per user preference.
- [x] Complete content is not visible for queries.
<img width="293" alt="Screenshot 2024-03-08 at 6 17 27 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/9bef2ac3-c056-42e4-9513-fab1cd75c38b">
<img width="173" alt="Screenshot 2024-03-08 at 6 21 32 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/f2c51321-0e3a-4a0e-b64c-d2f35dcfd96e">

### Steps To Reproduce

1. Login with the below credentials in release:
-username: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
-password: [ide-test@appsmith.com](mailto:ide-test@appsmith.com)
2. Create a new app & add some JS Objects/Queries

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by hetunandu** [comment]
All items in this issue are resolved
