### ISSUE TITLE
Sign up button in create new for Workflows Beta program

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#31651]
In the create new button on the workspace, hyperlink the sign-up page for workflow beta access.

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31651?planning-poker) with Zenhub @ayushpahwa @nsarupr
