### ISSUE TITLE
[Bug]: Unable to merge changes into the master branch of one of the forked template apps.

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#31650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to merge changes into the master branch of one of the forked template apps.

### Steps To Reproduce

1. go to release.app.appsmith.com
2. create a new workspace and new app connect it to git and create a new own branch "xxx" 
3. now for the maintenance order template
4. now make home page of the template as a home page and also visible
5. now commit the changes the commit is asked twice here do that
6. After that try to merge change to master 
7. The task doesn't happen

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.17

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod
