### ISSUE TITLE
[Bug]: After deleting a function inside a JS module and republishing, we can still see the deleted function in the app where the module instance was created out of this module

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After deleting a function inside a JS module and republishing, we can still see the deleted function in the app where the module instance was created out of this module

### Steps To Reproduce

https://www.loom.com/share/239600a8c5504f3b8e7956087d0fa392

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud/Release

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod
