### ISSUE TITLE
[Bug] No Validation between Access Token URL and Client ID and secret

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3166]
Steps to reproduce:
1) Add an API
2) Click on "Set as Datasource"
3) Select Authentication Type : Autho 2.0
4) Add inappropriate Access Token URL 
5) Add correct Client ID and secret 
6) Click on Save 
7) Now navigate to API pane 
8) Click on Run 
and observe 

Observation:
It is observed that the it depends on the API inserted and no Authentication done if the API belongs to said Client ID and secret

Video:
https://www.loom.com/share/90f0aad436f643d9acf6e631152f4d2b

**Comment by ofpiyush** [comment]
Isn't this the expected behaviour here?

**Comment by nidhi-nair** [comment]
It is, I'm wondering if we should add some kind of validation while execution to disallow execution if you added extra credentials :D That might be more irksome though.

**Comment by ofpiyush** [comment]
@Nikhil-Nandagopal thoughts?

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair @ofpiyush is any kind of validation even possible here? We don't know what are inappropriate Access URLs right?

**Comment by nidhi-nair** [comment]
We don't, we'll only know after we've hit it and not come back with a useful response. @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
Then I guess this is sort of moot? Is there a soln here?
