### ISSUE TITLE
[Feature]: When Selecting Text in JS Object Editor, Highlight All the Exact Same Texts

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#31704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The JS Object Editor should provide the functionality to highlight all the same text when the user selects a text, which is supported in most code editors. 

At this juncture, the workaround is to use the Google Chrome browser and the search functionality of the browser. When entering a text in the search box of the browser, it highlights all the same text in the editor.

### Why should this be worked on?

This would improve the user experience by enabling users to faster debug their code.

**Comment by Nikhil-Nandagopal** [comment]
This is a duplicate of #9330
