### ISSUE TITLE
[Bug]: Unable to import application due to missing binding path `primaryColumns._class.computedValue`

### ISSUE THREAD

**Issue by brayn003** [appsmithorg/appsmith#31729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a user tries to import an application, the operation fails due to a missing binding path.
The binding path in question is - `primaryColumns._class.computedValue`

Actual Error:
```
com.appsmith.server.exceptions.AppsmithException: Unable to import application in workspace xxx. Error: "widgetType" : "xxx", "bindingPath" : "primaryColumns._class.computedValue", "currentKey" : "_class", "message" : "Binding path in the widget not found. Please reach out to Appsmith customer support to resolve this.
```

### Steps To Reproduce

1. Eport an app
2. Import an app with the JSON
3. Import fails

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by brayn003** [comment]
Seems like a duplicate of https://github.com/appsmithorg/appsmith/issues/20744
