### ISSUE TITLE
Task: rename our templates db `Mock_DB_V2`

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#31734]
* Name of our DB must accurately represent its intend and should not be confusing to our users.
* We also have to ensure after update existing apps don't break.
* One idea🤔 is to set up an alias and use that alias going forward.

**Comment by rahulbarwal** [comment]
Can be done alongside #33084

**Comment by jacquesikot** [comment]
All templates and building blocks datasource names have been changes from Mock_DB_V2 to Sample Database
