### ISSUE TITLE
[Feature]: Showing the size of a widget

### ISSUE THREAD

**Issue by JakubNajvarekBringauto** [appsmithorg/appsmith#31735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I think there when resizing a widget there should be some sort of size atribute or something that would show the size of a widget.

### Why should this be worked on?

Because right now when trying to make an app. Its really hard to tell if the widget is the same size as some other  widget or if its in the middle etc.

**Comment by Nikhil-Nandagopal** [comment]
@JakubNajvarekBringauto I understand this is a problem of aligning widgets and making your UI look perfect. We are now investing in a new drag and drop building that will allow you to achieve this without needing to configure every widget. You can follow this issue #4630
