### ISSUE TITLE
[Bug]: Cannot delete a datasource which is created during import of an app with module instances in a fresh workspace because it has queries associated to it. The queries are the ones belong to previously published modules. Users cannot delete such datasource in such scenario

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cannot delete a datasource which is created. during import of an app with module instances in a fresh workspace because it has queries associated to it. The queries are the ones belong to previously published modules. Users cannot delete such datasource in such scenario.

EXPECTATION:
if in the imported app's workspace, there are no consuming module instances , the user should be able to delete the datasource associated with the modules. 

POINT TO NOTE: the package / APP module instance in the previous workspace from where the app/package was imported should be atomic and unaffected.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/113327629/f438f596-f254-4dcf-b9db-c0d043098eec

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud/Release

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by kamakshibhat-appsmith** [comment]
Reopening with correct labels
