### ISSUE TITLE
[Bug]: stale records in onPageLoadActions array inside the page DSL even after module instance is deleted

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

stale records in onPageLoadActions array inside the page DSL even after module instance is deleted

### Steps To Reproduce

[OnPageLoad Issue with JS Module.json](https://github.com/appsmithorg/appsmith/files/14586352/OnPageLoad.Issue.with.JS.Module.json)
[Util Package.json](https://github.com/appsmithorg/appsmith/files/14586357/Util.Package.json)

https://www.loom.com/share/044e0b920e5b472fa328eb08f0e674c9

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud/Release

**Comment by nidhi-nair** [comment]
N/A , was a result of another bug around public and private functions. Closing since that issues has been fixed.
