### ISSUE TITLE
[Bug]: Widget labels are misaligned at times

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/appsmithorg/appsmith/assets/79509062/2de31cb4-bc09-4d78-a128-b3ddcf0a8c5e)
 
![image](https://github.com/appsmithorg/appsmith/assets/79509062/140e54c3-a700-438c-a1c1-d1bb3b6bdde5)

![image](https://github.com/appsmithorg/appsmith/assets/79509062/61321229-8397-4f1f-b3bc-10b8ad38b160)

### Steps To Reproduce

Use the current Anvil DP to repro the issue above
https://ce-28238.dp.appsmith.com

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by ramsaptami** [comment]
added the team label hence reopening it

**Comment by KelvinOm** [comment]
Will fix this here #31947
