### ISSUE TITLE
[Bug]: Navigation to UI mode does not happen on clicking any area of a widget.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Though there is a message to this effect -
💡 ⌘ click a widget to navigate to UI mode.
When we click any area in the widget, nothing happens. Only in clicking the name of the widget, the navigation happens.
This navigation to UI mode should happen on clicking any area of the widget.

### Steps To Reproduce

Uploading Screen Recording 2024-03-13 at 7.43.34 PM.mov…

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by rohan-arthur** [comment]
I think the video upload failed, so I can't see the issue reproduction. My guess is that this is about the new "canvas selected mode". In this case, I have the same explanation as [here](https://github.com/appsmithorg/appsmith/issues/32495#issuecomment-2132711997)
