### ISSUE TITLE
[Bug]: Tabs in query editor when datasource is an API have a wrong spacing to the URL

### ISSUE THREAD

**Issue by pedro-santos-rodrigues** [appsmithorg/appsmith#31763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The spacing of the tabs to the URL now is shorter

- Before
![image](https://github.com/appsmithorg/appsmith/assets/36523902/0de39920-4a32-4dea-8f4f-a138a83f92e9)

- Now
![image](https://github.com/appsmithorg/appsmith/assets/36523902/18d8a287-d28e-45b8-b346-f0c9a96d1a92)

### Steps To Reproduce

1. Open application
2. Open query with API datasource

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Version

3e084fcc

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by razelos** [comment]
Hello, I am interested in picking up this issue as part of my first open source contribution. I am a student contributing as an assignment in university so any guidance as to where to start would be much appreciated. Thank you!

**Comment by rohan-arthur** [comment]
@pedro-santos-rodrigues please take a look at these designs, and feel free to close this issue if the problem has been adequately addressed there. https://www.figma.com/design/8L9BXMzNTKboGWlHpdXyYP/Appsmith-IDE?node-id=252-38130&t=9oQwury8zuw4vPQD-0
