### ISSUE TITLE
JsObject icon and the code editor are not left aligned.

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#31771]
The file icon and the tabs are not left aligned the icon has a padding of 20px while the tabs have  a padding of 24px.<img width="1652" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bff51feb8e27c66ec21ede1338c1a92eeb369d5/Untitled2.png" alt="Untitled2.png" />

**Comment by ayushpahwa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31771?planning-poker) with Zenhub @nsarupr @srix

**Comment by ayushpahwa** [comment]
<img width="743" alt="image" src="https://github.com/user-attachments/assets/82b0b473-080f-43eb-bdda-fdf117999126">
This is now fixed
