### ISSUE TITLE
Remove back button for all workflow queries.

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#31772]
JsObjects in a workflow aside from Main file should have a back button similar to queries and apis.<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDdiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e7691727f95bf1f291051b516283329df6fd25a/Untitled%205.png" alt="Untitled 5.png" />

**Comment by ayushpahwa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31772?planning-poker) with Zenhub @nsarupr @srix
