### ISSUE TITLE
[Bug]: Generate CRUD failing for GSheets datasource as well through connect data for other datasources

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I generate crud using gsheets ds, the data does not get displayed and an error is seen. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/557e8f17-c246-458d-9de4-50c8d1a11434

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by btsgh** [comment]
Adding another scenario observed - 
https://github.com/appsmithorg/appsmith/assets/101863839/3a4a2b40-207a-4be2-9160-9355be320f94

**Comment by Nikhil-Nandagopal** [comment]
@btsgh so can you close this?

**Comment by btsgh** [comment]
https://theappsmith.slack.com/archives/C02GAUE9P5H/p1710389754970079?thread_ts=1710306687.706329&cid=C02GAUE9P5H
