### ISSUE TITLE
[Task - Client]: Run history and debugger shouldn't be open at the same time.

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#31773]
Run history and debugger are both bottom panes and at a time only one should be opened. 
1. Run history and debugger should toggle one another. That is if a debugger is opened and someone clicks on run history the debugger should close and the run history should open up. 
2. Both of them cannot be expanded at the same time. 
3. Opening one shouldn't open the other automatically.<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5iQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5aca92ba05c78fe74213c6be4afe2df6adc2c92/Untitled%204.png" alt="Untitled 4.png" />

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31773?planning-poker) with Zenhub @ayushpahwa @nsarupr
