### ISSUE TITLE
[Feature]: Paragraph widget needs to support linebreaks, HTML, or markdown

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Paragraph widget needs to support linebreaks, HTML, or markdown to make use of links, line breaks, font styles etc

### Why should this be worked on?

to support formatting

**Comment by KelvinOm** [comment]
I am closing this task because it is necessary to work out a product solution here. Now it is unclear what to do with it.
