### ISSUE TITLE
[Bug] Update default data for each widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3179]
## Description
Every widget shows default data. It's an opportunity to educate the user about Appsmith and help them understand the widget better.

## Requirement:

| Title | Desc | Comment |
| ----- | ------ | ------- |
| Multi-select widget | Cut short data to max 3 objects, Make it consistent to the select widget | - |

**Comment by somangshu** [comment]
[] List Widget
    - [x] Drag and drop list widget
    - [] Create a query `fetch_users` with the Mock DB
    - [] Bind the query to the list widget using `{{ }}` 
    - [] Refer any object property using the widget internal property `currentRow`

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal @somangshu I believe this is done. Can we close this?
