### ISSUE TITLE
[Bug]: Input widget label is unnecessarily larger and darker

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Input widget label is unnecessarily larger and darker on the new WDS changes (https://ce-28238.dp.appsmith.com)

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/e43f7c65-39f4-4833-966a-4a947808694c)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by KelvinOm** [comment]
<img width="1064" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeElWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e1f0427cd6bab8654bcc9cba87c68ff6808ffc4/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-03-27%20%D0%B2%2015.39.54.png" alt="Снимок экрана 2024-03-27 в 15.39.54.png" />

Not relevant. The input has been redesigned
