### ISSUE TITLE
[Enhancement] Tabs reskinning

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3180]
https://www.notion.so/appsmith/Tabs-42a6b3e57fbe450caebb0a4dfbb86ca7

Sometimes we want to have a custom styles of containers in the tabs of the tab widgets. An option to add custom style to tabs like background color would be great.

**Comment by dilippitchika** [comment]
Adding this to widget reskinning, will track it there.

**Comment by laveena-en** [comment]
Tested and verified.
