### ISSUE TITLE
[Bug]: Mouse click and drag to select input text causes widget grab icon to appear on WDS

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Mouse click and drag to select input text causes widget grab icon to appear on WDS

### Steps To Reproduce

1. Use Anvil DP (https://ce-28238.dp.appsmith.com currently)
2. drop an input widget and set ''data type" to **single line text**
3. enter some values
4. click and drag the text - observe the grab icon show up instead of the typing icon

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/6e36e2bc9121487a95c08cd21472ff55

### Version

cloud

**Comment by KelvinOm** [comment]
It will not be relevant once  we merge this https://github.com/appsmithorg/appsmith/pull/32025
