### ISSUE TITLE
[Bug]: Country names are incorrectly displayed during search action

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Country names are incorrectly displayed during search action

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/b529206c-0c5d-4349-a743-7d258f1e4add)

![image](https://github.com/appsmithorg/appsmith/assets/79509062/5d186598-b3a5-4a00-8bd4-dc17b3ab6823)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by KelvinOm** [comment]
This is beyond the scope of our team. Can someone take care of this?

cc @somangshu

**Comment by ramsaptami** [comment]
Can we keep this ticket and simply reassign to the right team please?

**Comment by KelvinOm** [comment]
@somangshu This is about how the component works in the property pane and as Saptami correctly noted, it will affect the prod as well. Don't we have anyone who would be responsible for this?

We can take this task if there is no one else, but we need to understand the priority. cc @andreevanatasha

**Comment by somangshu** [comment]
@KelvinOm please note that this issue is also on the widget. We need to solve the underlying problem.. this is exactly what we noticed in our user test. 

Yes this is also a problem on prod, you are right that we need to solve this for the existing widget on fixed layout. However, this also needs to be solved for the wds widget.

**Comment by KelvinOm** [comment]
@somangshu This is not relevant in the WDS widget right now, since at the time of development we did not have an understanding of how all this would work and we do not have this functionality now anyway. [There's a bug about it](https://github.com/appsmithorg/appsmith/issues/32031).

**Comment by somangshu** [comment]
@KelvinOm regardless, the behaviour is still valid and wds must support this behaviour. We track it in the other bug or elsewhere, is besides the point
