### ISSUE TITLE
[Feature]: add an icon into the statbox default state, otherwise it's not discoverable

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

add an icon into the statbox default state, otherwise it's not discoverable

### Why should this be worked on?

https://www.notion.so/appsmith/Anvil-R1-usability-testing-5809dc222b3e4f64af74751ae92897c1?pvs=4#bd2946459ea447a1be54dbab2164f12b

**Comment by andreevanatasha** [comment]
Done as part of #32647
