### ISSUE TITLE
[Feature]:  FR to have control over main value colour

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

 FR to have control over main value colour

### Why should this be worked on?

sometimes it's the number itself which is ‘warning’ or ‘negative’ and not the value change (e.g. too many open tickets) 

https://www.notion.so/appsmith/Anvil-R1-usability-testing-5809dc222b3e4f64af74751ae92897c1?pvs=4#d9c2a9a5dbc141c693051437157d5090

**Comment by KelvinOm** [comment]
I close this as it is necessary to work out this issue from a product point of view. It's not clear what to do about it right now.
