### ISSUE TITLE
[Bug]: App import flow is breaking via the import option present within an application

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#31827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App import flow is breaking via the import option present within an application. The pages show up only after refresh.

### Steps To Reproduce

1. Create an app
2. Within the app, navigate to the import option within settings
3. Import any application's json
4. Notice that the pages do not show up unless the app is refreshed

Expected behaviour: The app should've auto-refreshed and displayed all the pages without the need for the user to refresh

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/c2a95b73aa8a465b914c239c23e26bfe?sid=daab3030-955f-42d8-9b20-ce74a8f9ea13

### Version

Cloud

**Comment by ashit-rath** [comment]
@laveena-en @rahulbarwal I believe this was fixed [here](https://github.com/appsmithorg/appsmith/pull/31834). Can we verify and close this issue?

**Comment by nidhi-nair** [comment]
Closing as fixed like Ashit mentioned, please re-open if that is not the case.
