### ISSUE TITLE
[Task - Server]: Update trigger workflow endpoint and request body to proxy trigger endpoint to have correct data

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#31823]
- [ ] Send the trigger proxy data to workflow proxy based on whether the published or unpublished run is requested.
- [ ] Add a query-param to distinguish test vs actual runs.
- [ ] Update the request body to send boolean flag to distinguish test vs actual runs.

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31823?planning-poker) with Zenhub @nsarupr

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31823?planning-poker) with Zenhub @nsarupr
