### ISSUE TITLE
[Task - RTS]: Set 365 day limit to store run history details

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#31831]

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31831?planning-poker) with Zenhub @nsarupr

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31831?planning-poker) with Zenhub @nsarupr
