### ISSUE TITLE
remove linting error for private entity code on the consumer side (reference is also coming plus we should ot show private action in general)App for reference : https://release-ee.appsmith.com/app/untitled-application-1/page1-65c4ac9b64418d40ff353765/edit?environment=production

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#31836]
https://www.notion.so/remove-linting-error-for-private-entity-code-on-the-consumer-side-reference-is-also-coming-plus-we--f91bafb1d09f4578a428a396b8552b91
<img width="838" alt="Screenshot 2024-03-15 at 4 46 50 PM" src="https://github.com/appsmithorg/appsmith/assets/113327629/2c04cf4c-bb6e-4799-af14-dc8f8145bb47">

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
