### ISSUE TITLE
[Bug]: Statbox widgets with and and without sub-labels have different heights

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Statbox widgets with and and without sub-labels have different heights and look odd side-by-side

![image](https://github.com/appsmithorg/appsmith/assets/79509062/f8f51df5-e365-498c-a257-f48273814230)

### Steps To Reproduce

1. Drop 2 statbox widgets side but side on the Anvil base DP (https://ce-28238.dp.appsmith.com/)
2. Add a sub-label to one and observe the height difference

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by KelvinOm** [comment]
I close this as it is necessary to work out this issue from a product point of view. It's not clear what to do about it right now
