### ISSUE TITLE
[Bug]: Key-Value widgets cannot be placed horizontally in a zone

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Key-Value widgets cannot be placed horizontally in a zone, despite the fact that the zone width is quite substantial ~800px

### Steps To Reproduce

1. Drop and keyValue widget on the Anvil base DP (https://ce-28238.dp.appsmith.com/) and observe the above

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by KelvinOm** [comment]
I'm closing this task for now because the horizontal positioning of the label should apply to other widgets as well and requires a systematic approach.
