### ISSUE TITLE
[Bug]: Search bar is by default unnecessarily long on table widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Search bar is by default unnecessarily long on table widget even when not focused 

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/5a1ecc95-db97-4232-b208-9075ce4e1c1a)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by AnshulKahar2729** [comment]
Do we want to work on this issue?

**Comment by jsartisan** [comment]
Fixed in #32112
