### ISSUE TITLE
[Bug]: Table Widget doesn’t fill space in zones vertically

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table Widget doesn’t fill space in zones vertically

### Steps To Reproduce

1. Open an existing app with widgets on the Anvil base DP (https://ce-28238.dp.appsmith.com/)
2. Drag and drop a table widget and connect with a large dataset
3. Drag this table widget on to a long zone

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by jsartisan** [comment]
@ramsaptami Closing the app as it is not relevant anymore. we provided number of rows for table now.
