### ISSUE TITLE
[Bug]: Cannot add styles to the submit and cancel buttons in Modal Widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cannot add styles to the submit and cancel buttons in Modal Widget

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/5d9cc16d-5210-43a4-9c0d-d21a17ea9a27)

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by KelvinOm** [comment]
Will fix this here — #31421
