### ISSUE TITLE
[Task - Server]: Update the Run History APIs to have the parameter to determine the type of run (test or actual)

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#31885]

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31885?planning-poker) with Zenhub @nsarupr

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31885?planning-poker) with Zenhub @nsarupr

**Comment by nsarupr** [comment]
This is not required, because all this is a proxy api and all the parameters which are being sent to the server will be sent as is to the Proxy. The server will then just respond with the result it receives from the proxy.
