### ISSUE TITLE
[Task - Server]: Create a terminate workflow API

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#31886]

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31886?planning-poker) with Zenhub @nsarupr

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/31886?planning-poker) with Zenhub @nsarupr
