### ISSUE TITLE
[Bug]: Improve the app menu

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#31896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The app menu has unnecessary help items. We'd like to funnel all help through intercom.

### Steps To Reproduce

1. Click the app menu from the app name in the editor
2. Click help and see 4 option.
3. It should only show Chat with us, Report a Bug, Documentation

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by hetunandu** [comment]
Fixed with #31986
