### ISSUE TITLE
[Bug]: #ffffff does not set theme to white, it's light grey instead

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

#ffffff does not set theme to white, it's light grey instead, because of which modal's background cannot be fully white

![image](https://github.com/appsmithorg/appsmith/assets/79509062/fb5bb6a6-a62e-45c2-8a59-e3dc1eb01d1f)

### Steps To Reproduce

1. drop a few widgets including a modal widget on the canvas on Anvil DP (https://ce-28238.dp.appsmith.com/ currently)
2. change the theme to #ffffff and observe the colour displayed on canvas/modal

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by KelvinOm** [comment]
This is no longer relevant. We have updated the colors and also changed the background color in the modal. Anyway, a pure white color for the background will not work, this is the expected behaviour.

cc @ichik
