### ISSUE TITLE
[Feature]: Paragraph widgets have intents for warning, danger, etc.

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Paragraph widgets have intents for warning, danger, etc.

### Why should this be worked on?

to support different user intents

**Comment by KelvinOm** [comment]
While the WDS component can take values, we deliberately removed this feature from the text widget. We will add when there will be a product decision for this
