### ISSUE TITLE
Chore: cleanup building block apps.

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#31902]
[Notion card](https://www.notion.so/appsmith/Strategy-on-managing-data-for-our-templates-building-blocks-and-mock-data-6d773a07704a4629b44c4a3c2355e019?pvs=4#f73993da2db6463190987dcd5fc49baf)

* Basically there are multiple (unused) datasources present in the apps which are used for BBs.
* Intention is to clean them up, so that user gets only one Building block.

**Comment by jacquesikot** [comment]
All building blocks apps have been updated, datasource has been moved to Sample Database for all building blocks.
