### ISSUE TITLE
[Bug] API settings page is not getting updated on selecting a different API

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3191]
## Description
API settings page is not getting updated on selecting a different API. The correct page shows up after selecting a different page and then coming back to the settings page.

https://user-images.githubusercontent.com/1757421/108990504-f7e76b80-76bc-11eb-8b21-98bc1f7ace10.mov

### Steps to reproduce the behaviour:
1. Go to Api1 settings.
2. Click on execute on load.
3. Select Api2.
4. See that settings page has not changed to reflect Api2 settings. 

### Important Details
 - Version: Cloud
 - OS: Linux
 - Browser: Chrome

**Comment by cokoghenun** [comment]
I also faced this on Firefox on my Linux computer
