### ISSUE TITLE
[Bug]: phone input's country code gets distorted when zone width is minimum

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

phone input's country code gets distorted when zone width is minimum

![image](https://github.com/appsmithorg/appsmith/assets/79509062/2812de05-d91e-4e7f-a574-43e4ac5d53d9)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/b47f1322-9b29-4002-86a8-3b58a65cbdbe)

### Steps To Reproduce

1. Drop a phone widget on to the latest Anvil DP
2. reduce the zone size to minimum (2)
3. observe the country code on the widget

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by KelvinOm** [comment]
Fix in release
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFE2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0eb5754523e4bdb3f4f7d6f424a636148846b45f/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-04-05%20%D0%B2%2015.46.35.png" alt="Снимок экрана 2024-04-05 в 15.46.35.png" />
