### ISSUE TITLE
[Feature] Show "Save as a Datasource" option for API even when the URL field is empty

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3193]
## Summary
I had a very hard time figuring out where the "Save as a Datasource" button was in the new API design since it remains hidden until the user types in some URL. 

![Screenshot 2021-02-24 at 4 42 17 PM](https://user-images.githubusercontent.com/1757421/108992796-b5735e00-76bf-11eb-8649-c59063ea7ead.png)

**Comment by hetunandu** [comment]
The button can be shown but it should be in a disabled state till someone writes a datasource
