### ISSUE TITLE
[Bug]: Hover popup that comes up on a binding is getting cutoff in split pane view

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#31946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the split pane mode, when I hover over a binding to get the pop up and check what value is being passed, the pop up gets cut off. 

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/9f2c099f-b1df-4ad6-b695-fd02dff35697

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by rohan-arthur** [comment]
I think it got fixed with some other issue, I can't replicate this anymore

https://github.com/appsmithorg/appsmith/assets/94514895/ef267a81-c618-498b-8e27-d46663e562a6
