### ISSUE TITLE
[Bug]: The edit icon appears inconsistent between packages and queries pane

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#31953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The edit icon appears inconsistent between APIs and Queries
<img width="1064" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/2b7d239f-97a5-4b79-aa1e-0c6f45839926">
<img width="1005" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/39e32de9-c377-442d-be29-cedf0e0f3e00">

### Steps To Reproduce

1. Go to application
2. Create an API and Create a query
3. check the edit button on both the Editors
4. There is a UI inconsistency as in the attached screenshot

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Version

v1.17

**Comment by rohan-arthur** [comment]
@RakshaKShetty what is the ui inconstistency? Do you mean that the space between the query name and the edit icon are different? If yes, we should close one issue, either this one or #32594
