### ISSUE TITLE
[Bug]: Table widget column type cannot be changed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table widget column cannot be changed to any other type other than 'plain text' on the Anvil instance

### Steps To Reproduce

1. drop a table widget on the latest Anvil instance
2. connect sample data
3. try to modify column type on any of the columns - observe there's on change on mouse click

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/01b9811a085d4a6da67c978b4894429b

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by ramsaptami** [comment]
Correct label has already been added & pod assignment has been made by the bot

**Comment by jsartisan** [comment]
Closing as it was not reproducible by me on the new WDS table widget. Let me know if you are still able to reproduce it.
@ramsaptami
