### ISSUE TITLE
[Bug]: Theme and font resets when color is picked from full colour picker mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When in dark mode, theme and font resets when color is picked from full colour picker mode

### Steps To Reproduce

1. Change theme to dark theme on an app on the latest anvil instance
2. Now select a colour from the 'full colour picker mode' - observe the system reset to light mode
3. Set dark theme again
4. Now change the font - observe it reset to 'system default'

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/eeee59ece03647c4869af65d343b9990

### Version

cloud

**Comment by ramsaptami** [comment]
Correct label has already been added & pod assignment has been made by the bot

**Comment by somangshu** [comment]
@ramsaptami who should this be assigned?

**Comment by ramsaptami** [comment]
it's been [fixed](https://theappsmith.slack.com/archives/C025SE88KNE/p1714393706580829?thread_ts=1714379864.821889&cid=C025SE88KNE) by Pawan already, just needs to be merged and closed
