### ISSUE TITLE
chore: WDS, refine icon stroke weights

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith#31982]
In particular bigger size in Statbox seems problematic:
<img width="207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeC83QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92c51dcd23ca5ec2bd90fbdea8d3a681de3efce2/image.png" alt="image.png" />

**Comment by KelvinOm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Anvil-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/31982?planning-poker) with Zenhub @ichik
