### ISSUE TITLE
[Bug]:`Operation not permitted` Error When Starting Instance on Kubernetes

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#31997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The instance of the user is not starting on k8s. The error returned in the logs is:
```/opt/appsmith/entrypoint.sh: line 590: /opt/caddy/caddy: Operation not permitted```

### Steps To Reproduce

More details in this [Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1709963623964309). 

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.16

**Comment by pratapaprasanna** [comment]
Closed in this [PR](https://github.com/appsmithorg/appsmith/pull/33387)

**Comment by pratapaprasanna** [comment]
You can set this env variable 
`APPSMITH_RATE_LIMIT=disabled` and this will solve this issue
