### ISSUE TITLE
[Bug]: Buttons on an in-line widget shift every time buttons are added or deleted

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Buttons on an in-line widget shift every time buttons are added or deleted

### Steps To Reproduce

1. Use the latest Anvil DP and drop an in-line widget onto canvas
2. Add buttons from the property pane as seen in the video and observe the jumpy interaction
3. Delete buttons from the property pane and observe the jumpy interaction

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/da4083d14cad42f49a3a5ef2db1709dc

### Version

cloud

**Comment by KelvinOm** [comment]
Seems like not relevant anymore.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEVXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f01fe226983bb3d5bc05ba161029ef2b82e064c6/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-03-27%20%D0%B2%2018.51.40.mov)
