### ISSUE TITLE
[Feature] Allow developers to see and access backend logs

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3200]
## Summary
1. To debug issues, there's a need for backend logs that show what queries were run and for what endpoint
2. Either we should show the logs or allow for connecting to some APM tool

Today developers can see logs for their actions, but they can't see this information for their users.
Need to add this to #1236

**Comment by marcius** [comment]
I would include as many log types as possible:
- requests received by the frontend
- queries to the databases
- any other call to external services

**Comment by Shivam-z** [comment]
@areyabhishek I think we have this feature already 
If we run a query and press **ctrl+D** in the UI, then we can get the logs

![Screenshot from 2024-06-04 15-10-46](https://github.com/appsmithorg/appsmith/assets/127818049/5b6386dd-9469-4e81-9583-eb97e877be9c)

**Comment by Nikhil-Nandagopal** [comment]
@Shivam-z the request was for monitoring the logs of the developers users which are also now possible via the audit log feature. So we can close this.
