### ISSUE TITLE
[Bug]: Resizer for the page list section is missing

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#32005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The resize handle for the sections that displays list of pages is missing. It used to let the users see more than two pages at once and reduced the need for excessive scrolling

### Steps To Reproduce

1. Go to any app with more than 3 pages.
2. In the section where the list of pages is displayed, we no longer see the resizer.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/96c18b4878214b059618236c7a48ab4a

### Version

Cloud

**Comment by hetunandu** [comment]
Fixed in #32486
