### ISSUE TITLE
[Bug]: Missing hover state for Manage Env

### ISSUE THREAD

**Issue by brayn003** [appsmithorg/appsmith#32008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hover state is not working for Manage Environment button while creating a Datasource

### Steps To Reproduce

1. Create a new application on Appsmith
2. Go to Datasource, click on create new
3. Choose Mongodb
4. You will find the Manage Env with persistent bg color at the bottom of the screen

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

All EE versions

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod
