### ISSUE TITLE
[Bug]: Empty space on the `Bind Data` menu

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#32019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On clicking the `Bind Data` button, we see empty space on the menu. This is not present in the latest image. Also please implement sentence case for the `Bind Data` button.
<img width="286" alt="Screenshot 2024-03-22 at 3 00 18 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/01e10929-aae0-43d2-833a-4a28f060bdb7">

### Steps To Reproduce

1. Run an API query for page with no widgets on the canvas.
2. In the response section click on the `Bind Data` button.

**Expected:** The menu should open and look aesthetic.
**Actual:** We see an empty white space in the menu.

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by rohan-arthur** [comment]
same as #32947 - fixed now
