### ISSUE TITLE
[Bug]: Clicking on settings icon should close app settings when open

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When app settings pane is open and user wants to switch back to editing mode, there's a confusing interaction where it's not entirely clear which button can "take me back to the canvas", so I often end up clicking on the settings icon since it's highlighted in it's selected state.

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/3e1c9d25-ea57-4ee0-bd9c-b0c5ab9db926)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by rohan-arthur** [comment]
we're discussing this [here](https://theappsmith.slack.com/archives/C05FUJNDL0P/p1716790813708659)

**Comment by saiprabhu-dandanayak** [comment]
Hi **@ramsaptami** , I am picking up this issue .

**Comment by ramsaptami** [comment]
@saiprabhu-dandanayak please go for it and try and close a PR within 2 days

**Comment by hetunandu** [comment]
This issue should not be worked on as it requests a user experience that does not currently align to the IDE usability. Closing this
