### ISSUE TITLE
[Feature] Make storeValue synchronous by evaluating the updateStored immediately

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3203]
## Description
Store Value is an async function today but people generally think of it as a synchronous function. There is also no callback to this function and introducing one would muddle the function signature. The correct solve seems to be to provide an evaluated data tree once a synchronous action that manipulates the data tree such as storeValue is executed

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal should we be allowing an option to keep this async as well? All functions should be able to run async if we are to not hit performance issues in the future.

**Comment by thebf** [comment]
I suggest a wrapper function that takes a list of functions as parameters and executes them in sequence. This would allow for a flexible solution where needed while keeping the async by default paradigm.

**Comment by Nikhil-Nandagopal** [comment]
Hey guys, thanks for weighing in here. I just wanted to clarify that all code executed is always done so asynchronously from the UI so that we never hang the UI. This is just about making the storeValue synchronous in that context so it's easier to write
{{ storeValue("key", "value"); showAlert(appsmith.store.key); }} Rather than having to chain these values. They will be executed asynchronously as a whole but synchronously relative to each other :)

**Comment by thebf** [comment]
If you have multiple widgets subscribing and you're using it as a parameter for an api you can quickly get situations with inconsistent data being displayed.
The current approach is okay for simple uses but limits the usefulness of the store quite severely.

Took me 3 days of active use before I stumbled upon a couple of edge cases.

**Comment by Nikhil-Nandagopal** [comment]
Hey @thebf ,
I understand the problem you're facing. The solution I'm proposing is to allow the following code to execute correctly
```
{{ storeValue("key", "value"); API1.run(); }}
```
where API1 is reading a value from the store and is still receiving a consistent value. Could you point out where you see this would limit the usefulness? This code is executed entirely asynchronously but API.run is executed synchronously after storeValue. Basically, the entire binding is executed async but the API is run only after storeValue completes.

**Comment by thebf** [comment]
I misread at first, that would be a good solution.
