### ISSUE TITLE
[Task]: Set default JS Mode enable for all the widgets data binding property when user generates building block 

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32041]
### SubTasks

https://www.notion.so/appsmith/Learnability-task-breakdown-f269350501724248b4b83cfa3898121d?p=230129a257d04e5688a7cf5fc3baa0ea&pm=s

**Comment by sneha122** [comment]
Moving this to blocked as I need to clarify a couple of things with @jacquesikot, once those are answered, will move it back to in progress and start working on it

**Comment by sneha122** [comment]
This feature is implemented for all building blocks having table and json form widget, closing it
