### ISSUE TITLE
[Bug]: On selection of add access token to and client authentication in API ds renders empty

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#32055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you click on 2nd option in the dropdowns of add access token to and client authentication, the option value renders empty in the selected display of dropdown.

<div>
    <a href="https://www.loom.com/share/2c11a756899c4ec6b049186a4a50602f">
      <p>API datasource form fields misbehaving</p>
    </a>
    <a href="https://www.loom.com/share/2c11a756899c4ec6b049186a4a50602f">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/2c11a756899c4ec6b049186a4a50602f-with-play.gif">
    </a>
  </div>

### Steps To Reproduce

1. Go to API datasource form
2. Select Oauth 2 as an authentication type
3. Select 2nd option in add access token to or client authentication
4. Notice the empty selected value
5. If you select the 2nd option again, it renders correctly

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/2c11a756899c4ec6b049186a4a50602f

### Version

Both

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod
