### ISSUE TITLE
[Bug]: App crashes when using an arrow function within a map function

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App crashes every time I'm trying to type out arrow function inside a map function

### Steps To Reproduce

1. Use a checkbox widget
2. Switch to JS mode on options and type out an arrow function inside a map function as seen in the video and observe the app crash

### Environment

Deploy Preview

### Severity

Critical

### Issue video log

https://www.loom.com/share/220d1edb1ef747609dc15a004108bc0f

### Version

cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Anvil-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/32053?planning-poker) with Zenhub @jsartisan @marks0351 @riodeuno

**Comment by ramsaptami** [comment]
fixed in the latest build hence closing this issue
