### ISSUE TITLE
[Bug]: `//` in Strings and String Literals is failing the workflow

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#32065]
<img width="1103" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1NQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28a591f278c08dc0f38a2d9add91b88c26586652/image.png" alt="image.png" />

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32065?planning-poker) with Zenhub @ayushpahwa @nsarupr
