### ISSUE TITLE
[Bug]: Width of tooltip box is larger than text on the property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Width of tooltip box is larger than text on the property pane

This issue exists on current production too

### Steps To Reproduce

1.Drop a widget on canvas like text or radio
2. Make sure its property pane is open
3. Hover over various tooltips on the property pane

![image](https://github.com/appsmithorg/appsmith/assets/79509062/efad6c31-1d7d-4c43-8c4e-12d294bccf01)

![image](https://github.com/appsmithorg/appsmith/assets/79509062/9f00d326-0925-4977-9256-a821b579ec79)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by KelvinOm** [comment]
@somangshu This is not the responsibility of our team. Can we pass this on to someone who work with ADS? It should be reproduced in the prod as well.

**Comment by ALOK9442** [comment]
hey @ramsaptami , I wanna work on this issue but I couldn't find the issue like how to check this issue in the prod. or development?

**Comment by ramsaptami** [comment]
@ALOK9442, drop a widget and hover over its properties on the right panel that opens up, you should be able to see this behaviour

**Comment by ALOK9442** [comment]
Hello @ramsaptami , I still couldn't figure out, sorry to bother you again could you please explain it to me.

**Comment by ramsaptami** [comment]
@ALOK9442 I've updated the description and steps, please follow

**Comment by ALOK9442** [comment]
hey @ramsaptami , I wanna work on this issue can you assign it to me?

**Comment by ALOK9442** [comment]
hey @ramsaptami , a gentle reminder.
also I have the solution ready, if you could assign it to me then I can raise a pr for it.
> hey @ramsaptami , I wanna work on this issue can you assign it to me?

**Comment by Nikhil-Nandagopal** [comment]
@ALOK9442 I've assigned it to you

**Comment by ALOK9442** [comment]
Hey @Nikhil-Nandagopal , can you check and tell if there's any change require, It's my first pr in this repo so please let me know what I need to improve.
