### ISSUE TITLE
[Bug]: The app tends to be in suspended states when we create feature branch from main and main has instances added from more than one package

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#32087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The app tends to be in suspended states when we create feature branch from master and master has module instances added from more than one package`
https://www.loom.com/share/5820cb9f22c042c29f135fc20a05115d

### Steps To Reproduce

1. Create a git connected app and make sure the master has atleast two module instance each coming from DIFFERENT PACKGE
2. Create a feature branch, you will notice the branch is in suspended state
3. Now go back to master, the master will also be broken and in suspended state
POINT TO NOTE: there seems to be one additional system generated commit after STEP 2 which is removing all sorts of configs

Another scenario reported by Tom  where this was observed:

I had a need to pull and discard my changes in an App. After doing so, i again reached this state where my packages aren't connected. Not able to work properly on any of the Apps or dev branches I create, which are connected to packages.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud/Release

**Comment by subrata71** [comment]
The issue is also reproducible without connecting the app to git. Here are the steps:

- Create workspace 1
- Create Package 1 and publish
- Create Package 2 and publish
- Create an app e.g. Multi Pkg Import Test
- Create module instances from both packages inside the app
- Export the app and the packages
- Create workspace 2
- Import Package 1 and publish
- Import Package 2 and publish
- Import the app
- Check the module instances are in suspended state

cc: @kamakshibhat-appsmith

**Comment by subrata71** [comment]
### RCA
The `findAllPublishedByUniqueReference` generates a query equivalent to the following in the case of multiple packages

```
{
  "$and": [
    {
      "originPackageId": {
        "$exists": true
      },
      "workspaceId": "6603ca49600fcd4753ac0eab"
    },
    {
      "$and": [
        {
          "packageUUID": "6603d51f363c4243de8ddc06",
          "latest": true
        },
        {
          "packageUUID": "6603d54c363c4243de8ddc1a",
          "latest": true
        }
      ]
    },
    {
      "$and": [
        {
          "$or": [
            {
              "deleted": {
                "$exists": false
              }
            },
            {
              "deleted": false
            }
          ]
        },
        {
          "deletedAt": null
        }
      ]
    }
  ]
}
```
The issue with the above query lies in the second $and array. In MongoDB, an object cannot have multiple fields with the same key at the same level. In the second $and array, you're trying to specify two different values for the `packageUUID` field, which is causing the query to be invalid.
