### ISSUE TITLE
[Bug]: Apps not opening on mobile view

### ISSUE THREAD

**Issue by diegorolf** [appsmithorg/appsmith#32084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you open the mobile version of the homepage pressing the apps no longer works. Should be an easy fix (I hope).

https://discordapp.com/channels/725602949748752515/1222085505231884350

### Steps To Reproduce

1. Go to homepage on phone (or devtools emulate)
2. Click app card

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/2874df05f246486e82ac8074548f3553?sid=ae25f99c-7bfc-4861-bb3f-40f36c5ff14a

### Version

Self hosted -1.18

**Comment by pranayagarwal96** [comment]
@diegorolf thanks a lot for highlighting this issue. Just for your context, this bug got recently introduced in the platform when we added a [small feature to launch apps quicker](https://github.com/appsmithorg/appsmith/issues/29829). We've fixed this issue and it should be available on [Appsmith cloud](https://app.appsmith.com/) from tomorrow

**Comment by diegorolf** [comment]
@pranavkanade We are currently using appsmith-ce:latest. When can we expect the issue to be fixed there?

**Comment by pranayagarwal96** [comment]
@diegorolf we tag once a week, so the fix should be available in `appsmith-ce:latest` by the same time next week. Again, apologies for the inconvenience here
