### ISSUE TITLE
[Bug]: Toolbar button widget issues on Anvil DP

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Icons are ignored when displayed inside “kebab” menu (must be there)
2. Separators are displayed incorrectly when inside the “kebab” menu (must be separators, not menu items)

[original post](https://theappsmith.slack.com/archives/C025SE88KNE/p1711538797233839)

### Steps To Reproduce

1. drop a toolbar widget on the new Anvil instance
2. Add 2-3 more buttons to the list so they appear under the "kebab" menu
3. Assign icons to the options and observe the behaviour

![image](https://github.com/appsmithorg/appsmith/assets/79509062/719b70d2-06e7-4737-b464-65b170d40767)

### Environment

Deploy Preview

### Severity

High

### Version

cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Anvil-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/32109?planning-poker) with Zenhub @jsartisan @marks0351 @riodeuno
