### ISSUE TITLE
[Bug]: Text highlight overlaps with the border of the input widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Think about having more paddings on the input text since text highlight overlaps by a few pixels on the border of the widget

### Steps To Reproduce

1. Drop an input widget on the current Anvil base DP
2. Enter text on the input box and highlight the text - observe the highlight overlap

![image](https://github.com/appsmithorg/appsmith/assets/79509062/01165a90-24da-457c-b1f2-382370dd3938)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by KelvinOm** [comment]
<img width="418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8453314395dee409abf6e3785af15e59f9769fce/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-03-27%20%D0%B2%2018.38.14.png" alt="Снимок экрана 2024-03-27 в 18.38.14.png" />

Seems like not relevant anymore.

**Comment by ramsaptami** [comment]
reopening since this can be seen when the border is set to be rounded
