### ISSUE TITLE
[Bug]: Linting error for windowMessageListener for BE instance

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#32126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

windowMessageListener API is enabled for BE users and for CE users it is expected to show linting error but it was noticed that on BE instance too it showed linting error. 

User issue :- https://theappsmith.slack.com/archives/C03U7UZFF2R/p1711379192333129

### Steps To Reproduce

1. Go to BE instance, new application
2. Create new JSObject 
3. write `windowMessageListener` and notice the linting error

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

1.18

**Comment by ApekshaBhosale** [comment]
I am picking this up as part of DMI. This is blocking our test case from coming back to main suite. 

cc @rishabhrathod01 @nerbos

**Comment by trishaanand** [comment]
Closed as part of PR 33049. 

@ApekshaBhosale : Since the format was not correct in adding Fixes in the description, the ticket did not get closed automatically. FYI
