### ISSUE TITLE
[Bug]: resetWidget function is not evaluating Disabled code on widgets

### ISSUE THREAD

**Issue by ACANRandy** [appsmithorg/appsmith#32133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an input field, who's Disabled field code resolves to true, is explicitly enabled (setDisabled(false)), it will stay enabled, even after executing resetWidget("inputWidget").

### Steps To Reproduce

1. Add a Table1 to the page.  Put any data in it.  Set default selected row to -1.
2. Add Input1 to page.  Set Disabled to {{Table1.selectedRowIndex < 0}}
3. Add Button1 - onClick {{Input1.setDisabled(false)}}
4. Add Button2 - onClick {{resetWidget("Input1")}}
5. Reload the page (Table will have no row selected, -1, so Input1 will be disabled)
6. Click Button1 - Input1 is now enabled.
7. Click Button2 - Input1 is still enabled.
8. Select a row in the table.  Input1 is still enabled.
9. Select the same row in the table (index = -1), Input1 is disabled.
10. Go to step 6 to repeat behavior.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/4c26cc1f4f864619a61b11f604a07a4a?sid=e72afcb2-ea9b-4637-938d-6bda433f8b78

### Version

Self Hosted 1.9.60

**Comment by ACANRandy** [comment]
I just discovered the same behavior with a button.  It's Disabled code is not being evaluated with the resetWidget function.  Replace Input1 with Button3 in the steps above and you will see the same behavior with Button3.

**Comment by Nikhil-Nandagopal** [comment]
Reset widget is only to reset the inputs given to a widget and not to reset programmatic manipulations to the property

**Comment by siderov-vay** [comment]
> Reset widget is only to reset the inputs given to a widget and not to reset programmatic manipulations to the property

I've noticed that the value ( set by `setValue` ) does get reset, but the disabled prop does not. How are they different?
