### ISSUE TITLE
[Bug]: Connect data CTA doesn’t work in split mode

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32146]
https://www.notion.so/Connect-data-CTA-doesn-t-work-in-split-mode-3adbd022097c4e969f17d2ee710e49af

**Comment by hetunandu** [comment]
Closed the wrong issue by mistake

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
