### ISSUE TITLE
Nudge for users to create a datasource

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32157]
https://www.notion.so/Nudge-for-users-to-connect-their-own-datasource-c62b5194bae84383b6301e4fe2e3ad80

**Comment by rishabhrathod01** [comment]
@rohan-arthur the notion doc has below comment.  
```
Out of scope: 
1. checking for valid datasources
2. checking whether the user has access to the datasource via RBAC
More simply, the requirement is: “If the app is in a workspace that has 0 datasources, we should show the new icon and tooltip”
``` 
Could you please check if we want to pick this up?

**Comment by rohan-arthur** [comment]
@rishabhrathod01 yes, this scope is aligned with design and product. Hope the estimate looks ok.
