### ISSUE TITLE
Users don’t test their datasources before saving it, leading to saving invalid connections

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32182]
https://www.notion.so/Users-don-t-test-their-datasources-before-saving-it-leading-to-saving-invalid-connections-190c46337bce45faa0e33a97a4d0982c

**Comment by sribalajig** [comment]
Duplicate of - https://app.zenhub.com/workspaces/activation-6604f423cc09d10016792707/issues/gh/appsmithorg/appsmith/32151
