### ISSUE TITLE
[Bug]: Avoid reducing paddings in a background-free zone when at least one zone in a section has a background on

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With conditional paddings depending on visual separation it might make sense to reintroduce another constraint: we don’t reduce/remove paddings in a background-free zone as long as at least one zone in a section has background on. This will prevent situations when a content of bordering zones is misaligned.

### Steps To Reproduce

1. add multiple zones to a section
2. Turn off the background on one of the zones and observe the shift in the UI

![image](https://github.com/appsmithorg/appsmith/assets/79509062/709bda1f-fd7b-472e-b069-a87b3d9d976f)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://theappsmith.slack.com/files/U03JBF3Q8JE/F06RQK11TNY/cleanshot_2024-03-27_at_20.46.02.mp4

### Version

cloud

**Comment by ramsaptami** [comment]
related to #32924

**Comment by ramsaptami** [comment]
an additional side-effect of this: distribution handles appear closer to widgets on a background-free zone
![image](https://github.com/appsmithorg/appsmith/assets/79509062/e808bd3f-be51-4c48-9041-126db94c9b3e)

**Comment by somangshu** [comment]
@riodeuno are you picking this up?
This has been moving through sprint but still have not closed.
