### ISSUE TITLE
[Bug]: "Hidden fields in data" option not working

### ISSUE THREAD

**Issue by rubenstolk** [appsmithorg/appsmith#32212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a form with a few fields hidden but the "Hidden fields in data" option enabled, I still get empty (null) values in my result when executing a query from that form.

### Steps To Reproduce

- Create a form, add a few fields of which a couple are hidden and enable the "Hidden fields in data" option.
- Add a submit handler that calls a query that uses data from the form

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by pranavkanade** [comment]
@rubenstolk could you please share a small sample app or screen recording of the issue in action? I am not sure where are you seeing `Hidden fields in data` option.

**Comment by rubenstolk** [comment]
Hi @pranavkanade please see attached recording

https://github.com/appsmithorg/appsmith/assets/692644/4005dfd2-547b-4df3-8343-fb3c72e238f6
