### ISSUE TITLE
[Bug]: Workflow with extra JS object other than Main is failing after execution start

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#32239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Workflow with extra JS object other than Main is failing after execution start

### Steps To Reproduce

1. Go to workflow
2. Create new jsobject
3. Trigger workflow, observe it fails.

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by ayushpahwa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32239?planning-poker) with Zenhub @nsarupr @srix
