### ISSUE TITLE
[Bug]: Increasing or decreasing page size on the table widget does not work as intended

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Increasing or decreasing page size on the table widget does not work as intended

### Steps To Reproduce

1. Drop a table widget on canvas on the latest Anvil DP
2. Bind data from mock DB
3. Increase and decrease page size and notice the page size changes but data listed does not alter as per this setting

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/4330c4385e2045f59e3f323c90eafaeb

### Version

cloud

**Comment by jsartisan** [comment]
I am not able to repro it. can you check if you still able to repro it?

**Comment by ramsaptami** [comment]
this seems to be fixed
