### ISSUE TITLE
[Bug]: Phone & currency input widget displays default values on different lines on smaller screens

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Phone & currency input widget displays default values on different lines on smaller screens
![image](https://github.com/appsmithorg/appsmith/assets/79509062/e7b41cd8-9f55-420b-bb49-87b9fc42db2f)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/b9f3290e-d254-4f97-9477-50393b146c67)

### Steps To Reproduce

1. Select any country code with 2 or more digits in it's default code
2. Go to preview mode and reduce the screen size

Observe the default digit appear on different rows

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by KelvinOm** [comment]
Should be fixed.
