### ISSUE TITLE
[Bug]: Issues Cannot Showing Echart in Appsmith Community v1.16

### ISSUE THREAD

**Issue by nuriansyahmalik** [appsmithorg/appsmith#32269]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I used echart in the previous version, but in Appsmith Community v1.16 it can't be blank chart
<img width="1143" alt="image" src="https://github.com/appsmithorg/appsmith/assets/140485624/4cbbd7aa-1051-4f72-903b-3e260712482c">

### Steps To Reproduce

Create a new chart then select the eChart blank immediately already follow the documentation also remain blank

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Self Housted v1.16

**Comment by Nikhil-Nandagopal** [comment]
@nuriansyahmalik can you please share the configuration of the chart?

**Comment by nuriansyahmalik** [comment]
> @nuriansyahmalik can you please share the configuration of the chart?

It seems that in low mode there is no configuration, I just use what is available, and there is no need to set the configuration. Can you explain what configuration you mean?

`{{
{
  "dataset": {
    "source": [
      [
        "Day",
        "Baidu",
        "Google",
        "Bing"
      ],
      [
        "Mon",
        620,
        120,
        60
      ],
      [
        "Tue",
        732,
        132,
        72
      ],
      [
        "Wed",
        701,
        101,
        71
      ],
      [
        "Thu",
        734,
        134,
        74
      ],
      [
        "Fri",
        1090,
        290,
        190
      ],
      [
        "Sat",
        1130,
        230,
        130
      ],
      [
        "Sun",
        1120,
        220,
        110
      ]
    ]
  },
  "tooltip": {
    "trigger": "axis",
    "axisPointer": {
      "type": "shadow"
    }
  },
  "title": {
    "text": "Search Engine Usage",
    "left": "center",
    "textStyle": {
      "width": 200,
      "overflow": "truncate"
    }
  },
  "legend": {
    "top": 40,
    "type": "scroll"
  },
  "grid": {
    "left": 15,
    "right": 15,
    "bottom": 30,
    "top": 100,
    "containLabel": true
  },
  "xAxis": [
    {
      "type": "category"
    }
  ],
  "yAxis": [
    {
      "type": "value"
    }
  ],
  "series": [
    {
      "type": "bar",
      "stack": "Search Engine"
    },
    {
      "type": "bar",
      "stack": "Search Engine"
    },
    {
      "type": "bar",
      "stack": "Search Engine"
    }
  ]
}
}}`

**Comment by Nikhil-Nandagopal** [comment]
@nuriansyahmalik yes that is correct. That configuration seems to work for me. Did you set the chart type to custom e chart?
![Screenshot 2024-04-02 at 12 10 43 PM](https://github.com/appsmithorg/appsmith/assets/3897254/5759d9fb-368e-45ff-be2d-848ff1e00f5a)

**Comment by nuriansyahmalik** [comment]
> @nuriansyahmalik yes that is correct. That configuration seems to work for me. Did you set the chart type to custom e chart? ![Screenshot 2024-04-02 at 12 10 43 PM](https://private-user-images.githubusercontent.com/3897254/318670233-5759d9fb-368e-45ff-be2d-848ff1e00f5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDEzNTQsIm5iZiI6MTcxMjA0MTA1NCwicGF0aCI6Ii8zODk3MjU0LzMxODY3MDIzMy01NzU5ZDlmYi0zNjhlLTQ1ZmYtYmUyZC04NDhmZjFlMDBmNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDY1NzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmY0NTJlNWY5ZGI1YzQ3MGY4NzNmYzc5ZTVmZDVmMTE0NWJhOWU3ZDc1MDQ3ZjQ2MjkzMGZhODRkZWU5NzI2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GB0-kEuJhL3QQC-9Lnz8pxAq8B74axkPplerZ2wmz1k)

already set active custom echart
<img width="214" alt="image" src="https://github.com/appsmithorg/appsmith/assets/140485624/559ebb54-9c9a-43e5-8ac9-6ba16b458996">

**Comment by nuriansyahmalik** [comment]
> can you try dragging a new chart and copying the confiugration over? Maybe that will help

still same sir 
<img width="1033" alt="image" src="https://github.com/appsmithorg/appsmith/assets/140485624/e8474afd-fca6-4a83-aa64-f83b574fe216">
and this the configuration
`{{
{
  "dataset": {
    "source": [
      [
        "Day",
        "Baidu",
        "Google",
        "Bing"
      ],
      [
        "Mon",
        620,
        120,
        60
      ],
      [
        "Tue",
        732,
        132,
        72
      ],
      [
        "Wed",
        701,
        101,
        71
      ],
      [
        "Thu",
        734,
        134,
        74
      ],
      [
        "Fri",
        1090,
        290,
        190
      ],
      [
        "Sat",
        1130,
        230,
        130
      ],
      [
        "Sun",
        1120,
        220,
        110
      ]
    ]
  },
  "tooltip": {
    "trigger": "axis",
    "axisPointer": {
      "type": "shadow"
    }
  },
  "title": {
    "text": "Search Engine Usage",
    "left": "center",
    "textStyle": {
      "width": 200,
      "overflow": "truncate"
    }
  },
  "legend": {
    "top": 40,
    "type": "scroll"
  },
  "grid": {
    "left": 15,
    "right": 15,
    "bottom": 30,
    "top": 100,
    "containLabel": true
  },
  "xAxis": [
    {
      "type": "category"
    }
  ],
  "yAxis": [
    {
      "type": "value"
    }
  ],
  "series": [
    {
      "type": "bar",
      "stack": "Search Engine"
    },
    {
      "type": "bar",
      "stack": "Search Engine"
    },
    {
      "type": "bar",
      "stack": "Search Engine"
    }
  ]
}
}}`

**Comment by Nikhil-Nandagopal** [comment]
@nuriansyahmalik maybe you need to update to the latest version of Appsmith. I'm not seeing this on v1.18
Also which browser are you using?

**Comment by nuriansyahmalik** [comment]
> @nuriansyahmalik maybe you need to update to the latest version of Appsmith. I'm not seeing this on v1.18 Also which browser are you using?

im using microsoftedge

**Comment by nuriansyahmalik** [comment]
@Nikhil-Nandagopal i already version v1.18 but keep can't using echart

**Comment by Nikhil-Nandagopal** [comment]
@nuriansyahmalik I'm struggling to reproduce this on edge as well. This is an app I created
https://app.appsmith.com/app/untitled-application-1/page1-6597d3ee426df65912524517
Are you able to see the chart? Can you fork it and see if it works for you? I'm not sure what is different in your app with mine

**Comment by Himanshi62** [comment]
@Nikhil-Nandagopal @somangshu 
{
  "__fn_keys__": [],
  "unProcessedChart": {
    "title": {
      "text": "Un-Processed POS Totals"
    },
    "tooltip": {
      "trigger": "axis"
    },
    "xAxis": {
      "type": "category",
      "data": [
        "Fatehsagar",
        "Shobhagpura",
        "Syphon",
        "B2B",
        "Tapri"
      ]
    },
    "yAxis": {
      "type": "value"
    },
    "series": [
      {
        "name": "Total ",
        "type": "bar",
        "data": [
          45874.32000000005,
          40864.390000000065,
          201041.69999999992,
          168299.67,
          4487.21
        ]
      }
    ]
  },
  "processedChart": {
    "title": {
      "text": "Processed POS Totals"
    },
    "tooltip": {
      "trigger": "axis"
    },
    "xAxis": {
      "type": "category",
      "data": [
        "Syphon",
        "B2B",
        "Tapri",
        "Fatehsagar",
        "Shobhagpura"
      ]
    },
    "yAxis": {
      "type": "value"
    },
    "series": [
      {
        "name": "Total",
        "type": "bar",
        "data": [
          4421.99,
          332.5,
          821.4200000000001,
          30,
          135
        ]
      }
    ]
  }
}

I am getting this evaluated data in ecustom chart, but still the chart is blank.

**Comment by Nikhil-Nandagopal** [comment]
@Himanshi62 I don't know what unprocessed chart and processes chart is. If you want to use a simple bar chart with multiple series, that is already supported by default and you just need to add the data. If you are using a custom chart, you have to follow the data format of the examples provided
https://echarts.apache.org/examples/en/index.html
