### ISSUE TITLE
[Task]: Correct the source information being sent in identify user call under Analytics

### ISSUE THREAD

**Issue by deepika-appsmith** [appsmithorg/appsmith#32266]
### SubTasks

correct the source

**Comment by MahmoudCodeDev** [comment]
I would like to take care of this.

**Comment by MahmoudCodeDev** [comment]
I only have read permissions, how can I fix this?

**Comment by ankitakinger** [comment]
`userType` will be handled on the backend. I'll be looking into the other 2 on frontend.
