### ISSUE TITLE
[Bug]: Whole canvas is flickering when navigating to Navigation tab in App Settings

### ISSUE THREAD

**Issue by CaptainT33mo** [appsmithorg/appsmith#32265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i am navigating to the `Navigation` section inside the `App Settings` from any other section the canvas UI is flickering as shown in the video attached. What should happen is it should not flicker like it doesn't in the other sections.

### Steps To Reproduce

1. Go to your `App Settings`
2. Navigate to any section in App Settings and observe the canvas
3. Navigate to the `Navigation` section and observe the canvas. It will start flickering

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/a15f7c80d4634d5abc3a4fa7bd185ca7?sid=a4c7f615-396a-4bef-af32-405269301cfd

### Version

Cloud - 1.18

**Comment by rohan-arthur** [comment]
thanks, @CaptainT33mo for reporting this issue. I think we may have fixed it with some other PR, as today I am not able to replicate the jittering anymore. Please reopen this issue if you still face issues.

https://github.com/appsmithorg/appsmith/assets/94514895/a4658fb8-abcd-429a-9313-ee5b6fa52353
