### ISSUE TITLE
[Bug]: The Multi environment feature Ramps is missing in edit page 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#32270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Multi environment feature Ramps is missing in edit page 
![image](https://github.com/appsmithorg/appsmith/assets/45958978/109515ed-2f9a-4580-a066-8aaa5b5b19bc)
![image](https://github.com/appsmithorg/appsmith/assets/45958978/5fc37367-f8aa-4241-a23e-2f4393157da9)

### Steps To Reproduce

1. go to release .app.appsmith.com
2. open any one app
3. on edit mode now on the left bottom corner
4. check fo the environment change
5. The env dropdown is missing this is present in latest as attached in the screenshot

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.19

**Comment by riteshkew** [comment]
Original PR reverted. No longer applicable
