### ISSUE TITLE
[Bug] [Tables] custom columns use ids instead of label when data is empty

### ISSUE THREAD

**Issue by hawisizu** [appsmithorg/appsmith#3228]
## Description
I have a table with custom columns that I changed the names of. If my tables has rows, no problem, but if it has no row, the custom columns show with their IDs rather than with the nice names, in my case it shows customColumn1. As soon as there is a least one row, the problem is solved. 

![image](https://user-images.githubusercontent.com/48994518/109214993-d36dbb00-77b2-11eb-81d6-418b43d5e505.png)

**Comment by riodeuno** [comment]
Table widget issues are compiled in #3248

**Comment by riodeuno** [comment]
@prapullac Can you verify this issue? I can't see this issue existing anymore in release.

**Comment by prapullac** [comment]
@riodeuno Unable to reproduce the issue on release.

**Comment by prapullac** [comment]
@riodeuno Unable to reproduce the issue on release.
