### ISSUE TITLE
[Bug]: Text gets truncated on the menu button's dropdown

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Text of alphabets like `y, g, j` get truncated at the bottom on the dropdown menu items

![image](https://github.com/appsmithorg/appsmith/assets/79509062/52a1efd2-0689-4d7d-8b2b-499e8c3218e3)

### Steps To Reproduce

1. Drop a menu button on the canvas on latest Anvil DP
2. Add menu names that contain `y,g or j` and observe the names getting trimmed off as seen in the screenshot

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Anvil-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/32299?planning-poker) with Zenhub @jsartisan @marks0351 @riodeuno
