### ISSUE TITLE
[Feature] Add an option to keep the date picker open

### ISSUE THREAD

**Issue by thebf** [appsmithorg/appsmith#3229]
The datepicker currently works for 2 scenarios: Time of day of current day or date.
The date picker should have an option to stay open until positive feeback (button) is given.

This would allow for a much improved workflow when handling date time.

**Comment by Nikhil-Nandagopal** [comment]
@thebf thank you for pointing this out! This is definitely an issue today

**Comment by marks0351** [comment]
@vicky-primathon another user on discord has raised this issue.

**Comment by vibhandikyash** [comment]
@areyabhishek @momcilo-appsmith @riodeuno @somangshu 
Here, As per the current implementation, the datepicker will close on date selection and as per the feature request above blueprint provides something similar to this (shown in video). It behaves like a popover where it will only close once you click outside of the datepicker.

Kindly let me know how are we looking to implement this one in terms of **design and development**. 

https://user-images.githubusercontent.com/17437380/121026177-82169400-c7c3-11eb-9019-d062ba73d5e1.mov

**Comment by areyabhishek** [comment]
Yup, this interaction makes sense to me.

**Comment by somangshu** [comment]
@areyabhishek that would not suffice the requirement raised by the user. They have pointed out that they wish to close the date picker at the click of a button. I am not sure if I am following that right!

**Comment by areyabhishek** [comment]
I think a click outside is a good feedback to close the dropdown. 
Also could we include shortcuts like the following. They seem really useful.
<img width="649" alt="Screen Shot 2021-06-08 at 1 38 39 AM" src="https://user-images.githubusercontent.com/30255708/121081413-52cf4980-c7fa-11eb-9870-b1d594b67739.png">
