### ISSUE TITLE
[Feature]: Statbox background and border to be handled by Anvil instead of the widget itself

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Statbox background and border to be handled by Anvil instead of the widget itself

### Why should this be worked on?
https://www.notion.so/appsmith/Stats-box-card-design-0b60ac1057c0445b84e13fa4a6ea37cc

**Comment by andreevanatasha** [comment]
Requires additional design inputs, see https://www.notion.so/appsmith/Stats-box-card-design-0b60ac1057c0445b84e13fa4a6ea37cc (WIP)
