### ISSUE TITLE
[Bug]: Canvas gets cutoff on preview mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Canvas gets trimmed on preview mode

![image](https://github.com/appsmithorg/appsmith/assets/79509062/e6e44436-cf08-4bda-bad3-9b9192399946)

### Steps To Reproduce

1. drop multiple widgets onto the canvas on the Anvil DP so it's a long page with a scroll
2. Scroll to the bottom and observe the bottom bit of the canvas truncated

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by ramsaptami** [comment]
Anvil layout label was renamed to Anvil team hence pod linkage wasn't working. I've made relevant changes on the app so correct pod assignment should happen

**Comment by KelvinOm** [comment]
How reproduce this? For me it's look like this.
<img width="1313" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--973589820689879c39c9ec2289eaf30a8686c498/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-05-01%20%D0%B2%2016.07.21.png" alt="Снимок экрана 2024-05-01 в 16.07.21.png" />

**Comment by ramsaptami** [comment]
hmm, I can see this happen on a windows system @KelvinOm 
![image](https://github.com/appsmithorg/appsmith/assets/79509062/2fac8748-be89-4980-ac26-3e0ede451142)

**Comment by KelvinOm** [comment]
@ramsaptami With browser do you use? Chrome?

**Comment by ramsaptami** [comment]
Yep, latest chrome @KelvinOm
