### ISSUE TITLE
Use WDS Tokens and components in Table columns

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#32303]

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Anvil-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/32303?planning-poker) with Zenhub @jsartisan @marks0351 @riodeuno

**Comment by jsartisan** [comment]
Closing as the PR associated with it is merged.
