### ISSUE TITLE
[Feature]: Modal widget overlay opacity settings

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Modal wigdet's overlay opacity is fixed and cannot be modified through a setting right now, but the overlay experience needs to either:
- adjust based on colour/theme setting applied, or
- provide a setting on the property pane for user to figure it out

### Why should this be worked on?

- There's not a lot of visual separation between the 2 layers on the current implementation
- There are times when users would not want to expose information behind a modal without users taking required action to access the main canvas

**Comment by somangshu** [comment]
@ichik is this relevant or taken care of elsewhere?

**Comment by ichik** [comment]
@somangshu algo has been tweaked recently for better separation, so would be good if @ramsaptami could verify it again (in particular if specific seeds lead to inadequate results).

**Comment by ramsaptami** [comment]
most colours are showing up a good contrast IMO, some fringe cases shows up like the one attached in the screenshot
do you think this overlay looks fine @ichik ?
color code is  `#d1d1d1`
![image](https://github.com/appsmithorg/appsmith/assets/79509062/111238cf-6b08-4856-8dc2-315bc5db222f)

**Comment by ichik** [comment]
@ramsaptami I see, light seeds may use a bit more darkening additionally. Will get around to that next week.
