### ISSUE TITLE
[Bug] When the table has fewer columns than it's size, the columns don't expand to fit the width

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3230]
## Description

The table looks very weird if the number of columns in the table are smaller than the widget of the actual table. If this is the case, the columns should expand to take up the remaining space. 

Screenshost: 
<img width="944" alt="Screenshot 2021-02-26 at 9 38 56 AM" src="https://user-images.githubusercontent.com/458946/109253954-faf66f00-7816-11eb-9e75-65e94029d8fc.png">

The black box is just me hiding the actual information.

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by vicky-primathon** [comment]
@mohanarpit cannot reproduce this issue.![Screenshot 2021-03-09 at 5.50.34 PM.png](https://images.zenhubusercontent.com/6041ffa5a2bd1760a7e766e9/90f6fcf5-2e37-4334-a18e-ceb2f5bfa06d)

**Comment by mohanarpit** [comment]
Closing as this seems to have been fixed.
