### ISSUE TITLE
[Bug]: Heading widget alignment does not follow user setting

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Text on a heading widget does not conform to user setting and remains on left-aligned

### Steps To Reproduce

1. Drop a heading widget on canvas on the latest Anvil DP
2. Change it's alignment setting to center or right from the property pane

Observe the text remain on left alignment

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://theappsmith.slack.com/files/U0535KG900Y/F06S4FGUPC5/screen_recording_2024-04-01_at_15.11.17.mov

### Version

cloud

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Anvil-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/32308?planning-poker) with Zenhub @jsartisan @marks0351 @riodeuno
