### ISSUE TITLE
[Feat]: Toolbar Buttons widget horizontal alignment

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Allow users to align button in Toolbar widget left or right.

E.g. in case on the screenshot I would like to be able to align all buttons to the right.

![image](https://github.com/appsmithorg/appsmith/assets/79509062/2327f648-955a-4872-9caf-09970913e463)

We can reuse the 'position' control (screenshot from Statbox's property pane):
<img width="212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6138e9e1c778f35a1af407d9e4f2f8e32a300702/image.png" alt="image.png" />

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by KelvinOm** [comment]
As I know, we don't need it. Taras correct me.

**Comment by tbrizitsky** [comment]
I do see Natasha's point. Let's add the alignment, it might be handy in some scenarios.

**Comment by KelvinOm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Anvil-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/32309?planning-poker) with Zenhub @jsartisan
