### ISSUE TITLE
[Feat]: Add polling for the run history details section of the pane

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#32322]
- Add polling for the run history details section of the pane
    - Polling time of 2secs

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32322?planning-poker) with Zenhub @ayushpahwa @nsarupr
