### ISSUE TITLE
[Bug] Enable both the Test & Save button when datasource form is invalid

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3233]
## Description

When some of the fields in a datasource form are in error state, the Save button is disabled, but the Test button is not.

![Screenshot 2021-02-26 at 11 28 22](https://user-images.githubusercontent.com/120119/109261424-c76f1100-7825-11eb-8046-a20094634c7e.png)

Both buttons should be enabled even if the datasource is invalid.

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by mohanarpit** [comment]
Closing as we should allow folks to test datasources even if the configuration is invalid.

**Comment by sharat87** [comment]
Then I think the Save button should not be disabled as well. Why is testing invalid configurations allowed but saving is not? This inconsistency here is what's bothering me.

**Comment by mohanarpit** [comment]
Agreed. Re-opening with a modified title & description.

**Comment by arunvjn** [comment]
Closing this issue since it is fixed already.
