### ISSUE TITLE
[Bug]: rest api receive binary

### ISSUE THREAD

**Issue by ahkimkoo** [appsmithorg/appsmith#32353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Send a POST request to my server in json format and return the binary data of mp3. When requesting my server using appsmith rest api, a garbled string is returned. Why? Does appsmith automatically serialize binary? How can I stop it from doing this.

### Steps To Reproduce

Send a POST request to my server in json format and return the binary data of mp3. When requesting my server using appsmith rest api, a garbled string is returned. Why? Does appsmith automatically serialize binary? How can I stop it from doing this.

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

1.6.6

**Comment by Nikhil-Nandagopal** [comment]
@ahkimkoo you seem to be on a very old version of Appsmith. Could you update to the latest and try again? I'd also like an example API where we can test this

**Comment by ame-appsmith** [comment]
Similar request - https://github.com/appsmithorg/appsmith/issues/32378
