### ISSUE TITLE
[Bug]: Workspace name editor input is gone when mouse hovers over other menu options

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#32359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Very hard to describe, but the title and the video below should illustrate the problem. The workspace editor input control should stay as an input control when I move the mouse around.

[Slack conversation](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1712128768080829).

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/120119/f33cc961-e04f-419d-82a3-0dab4a257cce

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud & Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod
