### ISSUE TITLE
[Bug]: Switch env dropdown - Admin - View mode - at first has Please Select an.. option, instead of Production selected by default

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#32357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I deploy an application on nightly, the switch environment dropdown does not have production selected by default. It shows up a text 'Please select an ...'

### Steps To Reproduce

<img width="652" alt="Screenshot 2024-04-03 at 11 29 02 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/7a0fb628-ca95-4484-b3d4-9699523c0495">

This looks like due the changes done to switch environment

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by riteshkew** [comment]
PR that brought in this bug has been reverted. Closing this now.
