### ISSUE TITLE
[Bug]: Appsmith "Oops! Something went wrong"

### ISSUE THREAD

**Issue by fkrahmad** [appsmithorg/appsmith#32366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This problem occurs when opening this tab :
![image](https://github.com/appsmithorg/appsmith/assets/150654188/6abf3328-5645-4da5-ae38-64abe3fabbeb)

then after waiting a while, this error appeared :
![image](https://github.com/appsmithorg/appsmith/assets/150654188/750cfa65-8d2f-4203-bc16-3b8ddd1bfbe3)

console error:
![image](https://github.com/appsmithorg/appsmith/assets/150654188/cfe94dd7-6dc7-44e2-b78d-61c243460f55)

Attached video : 
https://github.com/appsmithorg/appsmith/assets/150654188/3b827165-f72b-4581-b601-d0dff2fbac0e

### Steps To Reproduce

1. Open the appsmith application as usual
2. Press the "+" button to see the changes to the application
3. Waiting...
4. The Errors showing up

### Public Sample App

-

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Appsmith Community v1.18

**Comment by fkrahmad** [comment]
Does upgrading the version require anything to be done? In the last few days, I upgraded the Appsmith version, the last time I tried it was version 1.16 and it doesn't seem to have this problem.

**Comment by brayn003** [comment]
Hi @fkrahmad, are you still facing this issue after upgrading Appsmith?

**Comment by Nikhil-Nandagopal** [comment]
Closing this issue as we haven't heard back from you in awhile
