### ISSUE TITLE
[Bug]: Keyboard accessibility is still active on the canvas edit mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Keyboard accessibility is still active on the canvas edit mode via Ctrl/Alt/Shift keys

### Steps To Reproduce

1. Drop multiple input widgets on the latest Anvil DP
2. Select a widget by clicking on it
3. Unselect the same widget by using `Ctrl+click` or `Shift+click` or `Alt+click`- this should bring control to the canvas
4. Now use `tab` to move control between widgets and observe a cursor appear on the input boxes

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/a447205955b44712981e582e1948aecb

### Version

cloud

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod

**Comment by ramsaptami** [comment]
Issue with Github manager app, I've reassigned `Anvil team` label mapping to `Anvil Pod`
