### ISSUE TITLE
[Bug]: The new query button is displayed with secondary button for mysql datasource

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#32374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The button colour should be displayed with primary colour but it seems be displayed with secondary button for mysql datasource
![image](https://github.com/appsmithorg/appsmith/assets/45958978/05079710-2a26-450c-afc6-19d5b976a510)

### Steps To Reproduce

1. go to release.app.appsmith.com
2.create a new app and then  create a MySQL datasource
3. now Check the new query button 
4. as attached in the above screenshot the Secondary button is displayed

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

v1.19

**Comment by rohan-arthur** [comment]
not reproducible anymore
![Screenshot 2024-07-10 at 11 53 10](https://github.com/appsmithorg/appsmith/assets/94514895/4f72e99d-5beb-4deb-a7d9-bda9bdcc509a)
