### ISSUE TITLE
Text on CTA in modal during import via git should be &#x60;Import App&#x60;

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#32388]
[Slack Message](https://theappsmith.slack.com/archives/C04HERDNZPA/p1712154948604379?thread_ts=1712154948.604379&cid=C04HERDNZPA)

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed
