### ISSUE TITLE
[Feature]: install a different version of appsmith 

### ISSUE THREAD

**Issue by fkrahmad** [appsmithorg/appsmith#32398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://docs.appsmith.com/getting-started/setup/installation-guides/docker
how to install appsmith with selected version? let say the latest is 1.18, but i want to install the 1.16 on local.
thank you

### Why should this be worked on?

for development purposes, it would be helpful to be able to determine which version to use

**Comment by Nikhil-Nandagopal** [comment]
@fkrahmad you can specify the version in the docker compose file as appsmith-ee:v1.16
