### ISSUE TITLE
[Feature]: Steps to deploy Appsmith on Openshift

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#32392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith currently can be deployed and managed on openshift. We need a detailed instruction guide on how to deploy.

### Why should this be worked on?

This will help in more adaption of appsmith

**Comment by Nikhil-Nandagopal** [comment]
@pratapaprasanna can you raise this on the docs repo?
