### ISSUE TITLE
[Task] - IDE tabs revamp - close button and overflow scroll

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#32407]
Notion Doc - https://www.notion.so/appsmith/Tab-Management-499e69f9d5b74291ba40e5b309bff332
Figma - https://www.figma.com/file/DDP4RXK4YOTEJnuC8ocm47/IDE-Exploration?type=design&node-id=12264-306687&mode=design&t=KHJGKJBAKyzf6FMi-0

**Comment by hetunandu** [comment]
We should break down this task. Close button can be done independently

**Comment by hetunandu** [comment]
Yes. I believe you have not considered the testing complexity in the estimates
