### ISSUE TITLE
[Task] - Change add button to RHS with feature flage

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#32438]
Show the all files inside a menu with search.
Design - https://zpl.io/KEpdGpW 

<img width="530" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODA0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbad4d2fdbab6c86df6ec0d205c24005d8120d09/Screenshot%202024-04-05%20at%2010.58.12.png" alt="Screenshot 2024-04-05 at 10.58.12.png" />

**Comment by hetunandu** [comment]
Will this also handle moving the plus button to the right?
