### ISSUE TITLE
[Task] - IDE tabs revamp - right click context menu

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#32439]
Add entity explorer more menu to the tabs right click context menu.
Design - https://zpl.io/7GlPwwK
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVE0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd6746429d8a236844fa74de2e24bb9e432fad10/Screenshot%202024-04-05%20at%2011.04.22.png" alt="Screenshot 2024-04-05 at 11.04.22.png" />

**Comment by hetunandu** [comment]
We will not be doing this as it is unnecessary complication. We do not do context menu right clicks on the platform today
