### ISSUE TITLE
[Bug] Property pane state does not get reset between two instances

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3244]
## Description

This seems specific to the table widget, where navigating to the column properties retains that state after switching to the property pane for another widget.

https://user-images.githubusercontent.com/5298848/109287471-9bfe1d80-7849-11eb-9047-c1c9984e36ed.mov

### Important Details
 - Version: Cloud
 - OS: MacOSX
 - Browser: chrome

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon can you please pick this up
