### ISSUE TITLE
[Task] - IDE tabs revamp - editable tab name

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#32440]
1. Each tab name needs to be editable inside tab itself. This can be triggered from context menu as well as a single click on active tab.
2. Add unit test case to ensure the renaming functionality.

Design - https://zpl.io/AOjRmme
<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU00QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b040a34a58df0aad1d9f6e8a583ec190595cc6bf/Screenshot%202024-04-05%20at%2011.00.58.png" alt="Screenshot 2024-04-05 at 11.00.58.png" />

**Comment by hetunandu** [comment]
Either we move this in the Query Redesign milestone or remove the editable name capability in the action forms right now. I vote for the former
