### ISSUE TITLE
[Bug]: CRUD page generation is failing - data isn't being populated.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#32443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CRUD page generation is failing - data isn't being populated.

### Steps To Reproduce

1. Create an app
2. Try to generate a CRUD page from the pages section or from the datasource review page
3. Notice that it fails and no data is seen

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/ed727ce1d01f434994203b5beb3c1ed3

### Version

Release v1.19

**Comment by rohan-arthur** [comment]
not reproducible anymore, also it is fixed according to [this](https://theappsmith.slack.com/archives/CTHN8GX5Y/p1712297035436339) thread.
