### ISSUE TITLE
[Bug]: Inconsistent widget selection while using keyboard shortcuts

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`Shift` + selecting typically selects consecutive elements, so selecting the first and 4th element in a sequence automatically selects 1,2,3 & 4 but this behaviour is random on Appsmith canvas and does not follow this behaviour

### Steps To Reproduce

1. Drop mutliple widget of the same kind (eg: all buttons) and different kind ( eg: button, stat box, input etc) on the latest Anvil instance - make sure these groups of widgets are inside the same zone
2. Press down on `Ctrl` and select a few widgets at random and observe single widget selection happens as expected
3. Press down on `Shift` and select widgets at random as seen in the video and observe widgets in between these are not selected as per expected behaviour

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/19069aeaa5b64fd2b96f66d80e58996f

### Version

cloud

**Comment by KelvinOm** [comment]
@marks0351 @ramsaptami Could you check how it works with the latest changes.

**Comment by ramsaptami** [comment]
it works!! 🎉
