### ISSUE TITLE
[Bug]: Asterics gets clipped when label name is long

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Asterics gets clipped when label name is long

![image](https://github.com/appsmithorg/appsmith/assets/79509062/f2cce87f-1716-4996-a629-aa8e1af6b446)

### Steps To Reproduce

1. enter a long label name and observe the asterics getting clipped

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by Usama4745** [comment]
@ramsaptami how we can add Asterics to our input label

**Comment by ramsaptami** [comment]
this issue is on a feature that's WIP, please pick other issues marked 'Good First Issue' @Usama4745

**Comment by Annahariprasad** [comment]
Where Can I find the astrick symbol. Even though I given long text to the label component and make it as required. I didn't get the asterick.
