### ISSUE TITLE
[Bug]: Multiselect widgets don't work when they're placed inside a modal

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Multiselect widgets don't work when they're placed inside a modal

### Steps To Reproduce

1. Drop a modal on the latest Anvil DP
2. Drop any multiselect widget like checkbox
3. switch to preview mode
4. try selecting options on the checkbox and observe nothing happens
5. Try the same action with a checkbox on the main canvas and observe the widget register user inputs

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/01036afbcb8a42b1a0b30e04d4b0ddd1

### Version

cloud

**Comment by akshat8605** [comment]
HI Can this issue be assigned to me?
