### ISSUE TITLE
[Bug]: Canvas incorrectly highlights when a modal is being dropped on top of another modal

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to drop a modal on top of another modal shows drop indicators but nothing happens when user drops the second one.

We should ideally not see the drop indicator or need to close the first modal to accommodate the second one

### Steps To Reproduce

1. Drop a modal widget on the latest Anvil DP
2. Try to drop another modal widget with the first open and observe the canvas being highlighted
3. Let go of the modal grab action and observe nothing happens even though canvas indicated that it's a possible action

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/bd4ce00af9e142b9b7ca3fd0902f2e58

### Version

cloud

**Comment by marks0351** [comment]
@ramsaptami this has been fixed, pls verify once the on canvas UI changes are merged to the experimental dp.
