### ISSUE TITLE
[Bug]: Table widget does not show a scroll when displayed on a small screen hence widget appears truncated

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

table widget does not show a scroll when displayed on a small screen hence widget appears truncated

### Steps To Reproduce

1. Connect data to a table widget on the Anvil instance
2. Deploy app and view it on a small screen

Observe table displayed as a truncated widget

![image](https://github.com/appsmithorg/appsmith/assets/79509062/c5fdef87-26e8-4cbe-84ff-b8c2a211c308)

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by jsartisan** [comment]
@ramsaptami I am not able to repro this bug. I can see the scrollbar on smaller screen

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2R4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f31e3380c287933ef0ba09ab270a5b84c3e9d73a/CleanShot%202024-04-18%20at%2016.31.23.mp4)

**Comment by ramsaptami** [comment]
recent table widget changes have fixed these issues
