### ISSUE TITLE
[Feature] Create custom buttons/text on the table

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3247]
## Summary
Ability to create a custom button(s) on the table widget to add extra info/action in context of the table

## Motivation
We allow adding custom button columns but not something on the table header for aggregate info or table actions
This would be useful for table contained info in a complicated app

<img width="868" alt="Screenshot 2021-02-26 at 4 10 55 PM" src="https://user-images.githubusercontent.com/12022471/109290328-796e0380-784d-11eb-9379-18456349769e.png">

**Comment by somangshu** [comment]
@hetunandu will this be solved with #2281

**Comment by Nikhil-Nandagopal** [comment]
I don't think this is a good idea. I can't think of a table that allows an API to add a button anywhere inside it. The user can simply drag a button above the table to achieve this so why is this feature needed @hetunandu ?

**Comment by aniston** [comment]
Hi, my2c, having a refresh as a button will satisfy a user experience from my side, any update on this or is it already implemented ?
