### ISSUE TITLE
[Bug]: An arbitrary condition disallows creating new sections during widget drop on a modal

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

An arbitrary condition disallows creating new sections during widget drop on a modal

### Steps To Reproduce

1. Drop a modal widget on the latest Anvil instance
2. Drop a few more widgets such that it's creating a new section each time

Observe that drop indicators appear inside an existing section but these indicators do not show up at potential section creation points.

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/0661fde64b0649258d7c8263f963c526

### Version

cloud

**Comment by marks0351** [comment]
@ramsaptami This issue has been fixed as part of #32839
