### ISSUE TITLE
[Bug]: Buttons on a table widget overlap with their icons on a small screen

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Buttons on a table widget overlap with their icons on a small screen

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/95d56dee-134c-4c24-80db-d144243d1af4)

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by jsartisan** [comment]
@ramsaptami This should be fixed as well with the new table widget updates.

**Comment by ramsaptami** [comment]
@jsartisan the download options don't seem to be overlapping as before but the lack of icons makes the information unclear
![image](https://github.com/appsmithorg/appsmith/assets/79509062/4d5c9c4c-cbf9-4430-a6fb-01a2c122d967)

**Comment by jsartisan** [comment]
@ramsaptami This was fixed. Closing it.

**Comment by jsartisan** [comment]
>@jsartisan the download options don't seem to be overlapping as before but the lack of icons makes the information unclear

This is a separate issue btw.
