### ISSUE TITLE
[Bug]: Appsmith going down when reached high memory 

### ISSUE THREAD

**Issue by ariretiarno** [appsmithorg/appsmith#32488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I'm using appsmith for a long time, the memory is increasing, and the appsmith application is taking too long to respond, sometime on my console browser show 504 gateway timeout. after i restarted the appsmith apps, it's going normal again. i didn’t see error anything on appsmith, it's just going slow and i just reboot the services it's back to normal

What i expect is appsmith is normal to access, not slow when reach some memory value

<img width="1360" alt="image" src="https://github.com/appsmithorg/appsmith/assets/46735686/78e9ab22-8aac-493c-bdd5-75732e5f649a">

### Steps To Reproduce

1. Appsmith is using on production
2. After a couple of hour, memory increasing
3. appsmith is going to slow, and sometimes give 504 timeout
4. restart appsmith
5. back normal

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Self Hosted - v1.16

**Comment by rajatagrawal** [comment]
Need more observability to understand the repro steps by having logs from the customer's instance. Currently blocked by this [github issue](https://github.com/appsmithorg/appsmith/pull/32613).

cc : @pratapaprasanna

**Comment by Nikhil-Nandagopal** [comment]
@rajatagrawal can we get a date by when we can debug this?

**Comment by rajatagrawal** [comment]
@ariretiarno Apologies for the slow response. Would it be possible to get on a call to help triage this issue ?

**Comment by AdeshAtole** [comment]
@ariretiarno if it is still happening, can you please take a thread dump when the issue occurs and send it across?

You can use `jstack`  to take a thread dump. I would recommend to take a heap dump using `jmap` as well, but it can't be shared across in public, as it will contain sensitive data.

**Comment by Nikhil-Nandagopal** [comment]
Closing this issue as we haven't heard back from you in a while
