### ISSUE TITLE
[Bug] Certain types of JS code does not work in column bindings

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3248]
## Description

- [ ] Certain types of function markups don't work in table actions
<img width="1180" alt="Screenshot 2021-02-26 at 4 16 23 PM" src="https://user-images.githubusercontent.com/103687/109290774-0d3fcf80-784e-11eb-8f36-e17e9852096f.png">

**Comment by hawisizu** [comment]
Hey there! here is a new one, quite low prio though
On chrome and Firefox, I always get scrolbars in tables, on Firefox even horizontal ones, although there is no scroll needed since the table has pages. 

![image](https://user-images.githubusercontent.com/48994518/109291933-ea9bbf80-7829-11eb-8f00-d54bdf089a65.png)

This is even happening if the table has only 1 line for example. 
I would be nicer to not have these scrollbars.

**Comment by Tooluloope** [comment]
@riodeuno Could you drop a comment on this issue

**Comment by riodeuno** [comment]
@Tolulope as shown in the screenshot above, when it comes to column properties' action bindings. Once type of code works while the other doesn't. This is related to how we manipulate the bindings to account for the inclusion of `currentRow`, and mapping the table data to provide a value to the `currentRow`. We need to look into how the bindings are finally set in both scenarios, and what the evaluations return in both scenarios to debug this.

**Comment by techbhavin** [comment]
Normal function is called in the following format:

```
{{function(){
showAlert("on click")
}()}}
```
But when the same function is written inside table column actions it is converted as bellow:

```
{{(currentRow) => { function(){
showAlert("on click")
}() }}}
```

This transformation is causing an error

if we wrap the function by round brackets, it is working as per the self-invoking function.
```
{{(currentRow) => { (function(){
showAlert("on click")
})() } }}
```

@riodeuno  @Tooluloope @somangshu

**Comment by riodeuno** [comment]
@techbhavin Yes, it is as I had expected. 
@sbalaji1192 Could you look into this and provide a solution approach? I am available to discuss this if needed. This can also be taken up in Table Widget V2.

**Comment by sbalaji1192** [comment]
@riodeuno This appears to be working now - https://www.loom.com/share/6ae4dc37affe412585199e50683d7294
