### ISSUE TITLE
[Bug]: Incorrect zone highlight when trying to move a multiselect widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Incorrect zone highlight when trying to move a multiselect widget

### Steps To Reproduce

1. Drop different mutliselect widgtes (checkbox, radio etc) on different zones on the Anvil DP
2. Drag the widget and notice top indicator get activated as seen in the video

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/3853d82db5d84dc9bbc3ced323751587

### Version

cloud

**Comment by KelvinOm** [comment]
@marks0351 @ramsaptami  Could you check how it works with the latest changes.
