### ISSUE TITLE
[Feature] Add isVisible property for all columns & isDisabled property for button column in Table Widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3250]
## Summary
Add disable property on a row button which can be controlled via JS

## Motivation
For some row actions that should not enabled, we should be able to control button disability via js

**Comment by riodeuno** [comment]
Note: 
- Add Disabled and Visible properties in the button column properties, which works the same way as any other widget's properties.
- Here the users can make use of `currentRow` in bindings.

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon @riodeuno we had another request for this feature today

**Comment by marks0351** [comment]
@Tooluloope another user has asked for this feature. the user also wants to dynamically change the column's name(column label).
@somangshu @riodeuno

**Comment by Tooluloope** [comment]
> @Tooluloope another user has asked for this feature. the user also wants to dynamically change the column's name(column label).
> @somangshu @riodeuno

Currently working on this.
