### ISSUE TITLE
[Bug] Table columns being reset when DB query changes

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3251]
## Description
1. I have a table with column properties
2. When I change the query that talks to the table, the column settings get reset

**Comment by riodeuno** [comment]
@areyabhishek We've made updates to this, in which, only if the table columns are different in the new query, will the column properties get reset.

**Comment by riodeuno** [comment]
@prapullac Can you verify this issue? The above note explains how it is supposed to work.

**Comment by prapullac** [comment]
Hi @riodeuno 
Tested on the release and observed this is working as expected and we can close the issue.
