### ISSUE TITLE
[Bug] Email not setup message is shown to user even though email is setup

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3252]
### Steps to reproduce the behaviour:
1. create a fresh install with a fresh org with user registration disabled and no email settings entered, invite users, have them register. No way to reset a users pass manually
2. Try to add email settings to env and restart container, following sendgrid directions, password recovery still says email is not setup and reset email did eventually get sent even though it says
 `You haven’t setup any email service yet. Please configure your email service to receive a reset link`

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by rishabhsaxena** [comment]
@mohanarpit Hey is this still an issue? I couldn't reproduce it using the following steps:
- Disable signup
- Create an account using the admin email
- Invite a new user -> sign-up with the new user
- Setup email settings -> restart using the cmds from the docs
- Try forgot password flow, the forgot password modal showed the success message

**Comment by 0sanity** [comment]
Yes 

![image](https://user-images.githubusercontent.com/4790732/110955861-04ec9780-8318-11eb-870e-e63cc7834bf7.png)

```
/ # env | grep -i mail
APPSMITH_MAIL_PORT=587
APPSMITH_MAIL_ENABLED=true
APPSMITH_MAIL_USERNAME=apikey
APPSMITH_MAIL_SMTP_AUTH=true
APPSMITH_MAIL_FROM=XXXXXXX@XXXXXX.com
APPSMITH_MAIL_SMTP_TLS_ENABLED=true
APPSMITH_MAIL_PASSWORD=SG.XXXXXXXXXXXXXXXXXXXX
APPSMITH_ADMIN_EMAILS=YYYYYY@YYYYYYY.com
APPSMITH_MAIL_HOST=smtp.sendgrid.net
```

**Comment by 0sanity** [comment]
Okay after adding the environment variables to the editor container, the message went away
Seems like a config issue causes this
Do you really need all the SMTP login details in the editor? Which ones specifically are needed to avoid this issue?

**Comment by rishabhsaxena** [comment]
> Okay after adding the environment variables to the editor container, the message went away
> Seems like a config issue causes this
> Do you really need all the SMTP login details in the editor? Which ones specifically are needed to avoid this issue?

@0sanity
Here just adding `APPSMITH_MAIL_ENABLED=true`, would hide the warning message on the client. If that's what you meant.
