### ISSUE TITLE
[Feature] [DatePicker] There should be no time field in the UI if the format is date only

### ISSUE THREAD

**Issue by hawisizu** [appsmithorg/appsmith#3253]
## Summary

If the display format is date only ("YYYY-MM-DD", "DD/MM/YYYY"), there should be no timepicker in the UI below the date picker. 

Also, in such case, the timezone should not be taken into consideration. 
Right now, if I pick a date only like 2021-02-14, because I am in Berlin the selected date is actually 2021-02-13 23:00
I think this makes sense for datetimes fields, but not for dates only. 
This can be corrected in the update query, by doing stuff like: 
`mydate = {{moment(Input_ev_fo_date.selectedDate).format("YYYY-MM-DD")}}`

But it would be much nicer to be able to do simply: 

`mydate = {{Input_ev_fo_date.selectedDate}}`

I'm not sure what is the best solution here, maybe to have  date picker and a datetime picker that are separated and behave differently. In any case it would be nice to document the "recommended solution" for date-only datepicker, I think this is a very common case. 
Thanks!

**Comment by Nikhil-Nandagopal** [comment]
@hawisizu you can access the formatted date directly instead of the selectedDate {{DatePicker.formattedDate}}. Does this solve your issue? There is also an open issue to disable time selection here #1579

**Comment by Nikhil-Nandagopal** [comment]
@hawisizu Closing since I haven't heard back from you. Feel free to re-open if you still think this doesn't work
