### ISSUE TITLE
[Bug]: Resolution metadata is not being sent back once the request is resolved

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#32530]
Metadata sent during the resolution of a request from app is not being linked in the response of the `assignRequest`, that object is empty.

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32530?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by nsarupr** [comment]
Closing this as the PR related to this is merged.
