### ISSUE TITLE
[Task]: Remove hardcoded RTS server url

### ISSUE THREAD

**Issue by SorsOps** [appsmithorg/appsmith#32532]
### SubTasks

- [] Remove the hardcoded RTS server url at https://github.com/appsmithorg/appsmith/blob/021b4177eac01a445cacf8bfb4688de449366701/app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java#L137
and replace it with support for `APPSMITH_RTS_HOST` env var to better support containerization. The RTS server can currently only be run on the same VM as the backend, and cannot be run as an independent pod in kubernetes

**Comment by sharat87** [comment]
Hey @SorsOps, thank you for raising this along with a PR. Can you elaborate on a use-case this is solving please? We don't expect or need RTS running on a separate host from the backend server today. Honestly, I don't think it's even just a matter of not having the host hard-coded. Can you share some details on what this is solving for you please?

**Comment by SorsOps** [comment]
Hi @sharat87 , pretty much the same reasoning as supplied above. I don't want to run it on the same pod and I want to follow proper principles of horizontal scaling by separating out the servers on kubernetes. Adding support for this poses no regression risk to Appsmith

**Comment by sharat87** [comment]
@SorsOps, thank you. Unfortunately, that's not supported. The backend server, RTS and Caddy aren't seen as separate services for the purposes of horizontal scaling. The three go togather very tightly, and are best seen as a single entity, as an abstraction. More on this strategy has been written on our blog in the past. See https://www.appsmith.com/blog/appsmith-deployment-architecture.

Closing this as won't fix. Thank you.
