### ISSUE TITLE
[Bug] The Evaluated values popover hinders the API Editor when in "Raw" mode

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3254]
The evaluated values popover comes over the API editor in raw mode.

<img width="943" alt="Screenshot 2021-02-27 at 4 17 41 PM" src="https://user-images.githubusercontent.com/6636360/109385097-6162b680-7917-11eb-960e-7b275e950f7b.png">

**Comment by areyabhishek** [comment]
The solution for this is to make this moveable like the property pane too.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek I don't feel that's the best solution here. If every time I come to this page I have to move the evaluated value it'll be really annoying.

**Comment by hetunandu** [comment]
The reason this is happening is because the evaluated value popover has a logic to never render above the input which is focused. So another solution is to make the input of less wide. Since the api pane has become full width, the input has become full width too which is not really needed. Most use cases would need half the width it is currently and still be sufficient. That way the evaluated value can be rendered on the right side of the input. This is also a problem in the JSON mode where it covers the gutter of the input

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal @areyabhishek, should I ahead and implement the solution I mentioned above?

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu I don't think that will look visually good. @aakashDesign can you have a look at this?

**Comment by areyabhishek** [comment]
One is to split the pane and have a permanent section with the evaluated value section visible. 
![Uploading Screen Shot 2021-03-16 at 11.59.14 AM.png…]()

**Comment by Nikhil-Nandagopal** [comment]
I like this solution!

**Comment by aakashDesign** [comment]
@Nikhil-Nandagopal @areyabhishek 
Collapsible evaluated value pane
Added designs here - https://www.figma.com/file/XI7Yg0bedTxncLmIUmXTpH/Query-Pane?node-id=0%3A1

![Screenshot 2021-04-05 at 11.39.01 AM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/2a95fd1e-1c79-4390-a626-810893f17ff4)![Screenshot 2021-04-05 at 11.39.43 AM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/c05bb6a2-c484-4c0a-bb05-7d5bf583aeab)![Screenshot 2021-04-05 at 11.39.59 AM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/01fc7157-1f2b-4ee4-bce4-f207080dc81b)![Screenshot 2021-04-05 at 11.39.25 AM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/3171ea80-42b9-4d7e-aeea-24236133b4fa)

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign same design for API pane body right?

**Comment by hetunandu** [comment]
We have closed this issue for now by reducing the width of the body field. In case we still want to redesign this, we can reopen the issue. @areyabhishek @Nikhil-Nandagopal @aakashDesign
