### ISSUE TITLE
[Bug]: Importing App from Git Removes Default Branch Protection

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith#32550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upon importing an app from Git, the branch protection feature is removed, allowing changes to be made to the master branch.

Video - https://github.com/appsmithorg/appsmith/assets/43263619/3c7b70bc-b137-4416-bc1f-1c2c708a5ef8

### Steps To Reproduce

1. Import an application using Git.
2. Open Git settings to see the changes.

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://github.com/appsmithorg/appsmith/assets/43263619/3c7b70bc-b137-4416-bc1f-1c2c708a5ef8

### Version

v1.20.0

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it does not have an appropriate label associated with a pod
