### ISSUE TITLE
[Bug]: UI bug in Triggers screen that is automatically switching off webhook

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#32579]
Replication - Enable webhook, go to main + publish and return to triggers and the webhook trigger switch is off. It doesn't seem to affect the copied webhook though, that's still working, just the UI is wrong.

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32579?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by ayushpahwa** [comment]
Closing since #33022 is going to fix this

**Comment by infinitetrooper** [comment]
This workflow has it's webhook setup and working but, the UI shows it as off.

![image](https://github.com/appsmithorg/appsmith/assets/16632903/acb15858-b989-47ee-98c1-d83bde1503d1)

**Comment by infinitetrooper** [comment]
<img width="1264" alt="Screenshot 2024-07-09 at 3 19 22 PM" src="https://github.com/appsmithorg/appsmith/assets/16632903/d752b9ba-d866-431d-9149-6b8f0f337fbf">

**Comment by nsarupr** [comment]
Currently, we have created this [Workflow](https://internal.appsmith.com/workflow/66ab3d7cb3cf5c74a105a75e/jsObjects/66ab3d7cb3cf5c74a105a763). The workflow has a token generated and published.

The tokenGenerated is updated only during the creation or deletion of the token. There are no other instances in the code where tokenGenerated is manually updated.

We will monitor the workflow mentioned above to identify any issues.
