### ISSUE TITLE
[Feature] Multiple where conditions support in Firestore queries

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3257]
Currently, we can only set a single *where* condition in Firestore queries. Please add support for setting multiple where conditions.

**Comment by aakashDesign** [comment]
Design with current design system -
A simple Condition card with three inputs and "+ Add Another" input
Figma - https://www.figma.com/file/fSQka3FpHBA6KnFqSZ6X1N/Firestore-Query-form?node-id=0%3A1
![Screenshot 2021-04-26 at 4.51.44 PM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/c6305632-2680-4112-be4e-002490a15b29)

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign 
can we also have an option to convert to JS? 
How does a user delete a field?
How does a user select whether it's an and/or condition?
I don't think "leave empty" is a great state. Notions empty state for filters would work great here!

**Comment by aakashDesign** [comment]
@Nikhil-Nandagopal Thanks for the great feedback, I've updated the design @ApekshaBhosale

- Added delete button
- Better empty state
- And/Or dropdown after the first condition

I checked with @mohanarpit we can't have JS input for firestore.
https://www.figma.com/file/fSQka3FpHBA6KnFqSZ6X1N/Firestore-Query-form?node-id=0%3A1

![Screenshot 2021-04-27 at 2.46.13 PM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/92b5f2bf-d77d-4af3-9d81-2d7150eee5f3)![Screenshot 2021-04-27 at 2.46.31 PM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/4020eaa4-9199-4e8c-8d89-8487ce9064b3)![Screenshot 2021-04-27 at 2.46.50 PM.png](https://images.zenhubusercontent.com/6045bc6eeca45c6cfee6dd46/f8c6087d-124c-4b0a-9a63-87d65d1efb77)

**Comment by Nikhil-Nandagopal** [comment]
That's weird, why is that the case. Under the hood it should just be a json that is editable right? @mohanarpit

**Comment by ApekshaBhosale** [comment]
@sumitsum are we supporting nested conditions as well? If yes, @aakashDesign how will this design work in that case?
what about grouping the conditions? 
Example  - Condition1 || ( Condition2 && Condition3 )

**Comment by ajinkyakulkarni** [comment]
Linking internal discussion document related to this https://www.notion.so/appsmith/Firestore-where-conditionals-design-preliminary-thoughts-eaf6f5e2c4284fd885d9bba93673f4a3

**Comment by YogeshJayaseelan** [comment]
1) The value field is breaking and due to that delete button is not in user focus
2) There is no And/or Condition dropdown

<img width="1280" alt="Screenshot 2021-06-10 at 11 30 44 AM" src="https://user-images.githubusercontent.com/35128442/121474431-b4054180-c9e1-11eb-90bf-6c56176c72af.png">

**Comment by sumitsum** [comment]
@YogeshJayaseelan can you please describe how to reproduce this ? I am not able to see this on my setup : 
![Screenshot 2021-06-10 at 12 00 54 PM](https://user-images.githubusercontent.com/1757421/121475972-b8caf500-c9e3-11eb-8b12-fdaf83d2a43a.png)

**Comment by sumitsum** [comment]
@YogeshJayaseelan `And/or` condition dropdown wouldn't exist because firestore does not support `or` condition.
