### ISSUE TITLE
Temporal silent quitting - No error is shown then temporal fails on code not related to activity

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#32596]
Temporal silent quitting is a real problem, we gotta propagate the errors back up. Like today, we did `label.toLowerCase` instead of `label.name.toLowerCase` and it completely gave up after the first line with us not knowing what's wrong.

[Slack Message](https://theappsmith.slack.com/archives/C05QG0J87UL/p1712776629059279?thread_ts=1712776629.059279&cid=C05QG0J87UL)

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32596?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by srix** [comment]
duplicate of #33027
