### ISSUE TITLE
[Feature] Add Menu Widget

### ISSUE THREAD

**Issue by tazmaniax** [appsmithorg/appsmith#3261]
## Summary

Add 3 dot button that presents a menu of action options

## Motivation

Often in constrained spaced UIs it's necessary to provide a set of actions but there is not enough space to have separate buttons for each action. In these situations a 3 dot button is needed that when selected presents a set of available action.

## Additional Context

The 3 dot button is a variation of the [hamburger button](https://en.wikipedia.org/wiki/Hamburger_button) but is used in places other than just the top corner of the UI to reveal the main menu.

This 3 dot button can come in both vertical (aka "kebab") and horizontal (aka "meatballs") layout as per [StackOverflow: What is the hamburger menu icon called and the three vertical dots icon called?](https://stackoverflow.com/questions/34755666/what-is-the-hamburger-menu-icon-called-and-the-three-vertical-dots-icon-called)

The visual aspect of the 3 dot menu should be configurable.

# Developer Handoff Design
Link to the developer Handoff Document: [Figma link](https://www.figma.com/file/tVBQrt0G0XI89eS9m8cT5H/Menu-Widget?node-id=1%3A27)

**Comment by Nikhil-Nandagopal** [comment]
Hi @tazmaniax 👋 thanks for the feature request as always :)
Doing a little digging, I think hamburgers are generally used for topbar navigation but this seems like a more generic request so I'm thinking of something like a Button Group here. This is Blueprint's implementation of the same
https://blueprintjs.com/docs/#core/components/button-group
So if the space can fit the buttons, they show up side by side but the buttons which cannot show up go into an overflow-like menu and retain the same properties.
Does this sound good to you?

**Comment by tazmaniax** [comment]
Hi @Nikhil-Nandagopal yes that would be the ideal as long as ultimately it can be collapsed down to a single "[more](https://material.io/resources/icons/?icon=more_vert&style=baseline)" button, aka [ellipse button](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/e/ellipsis-button). In my case I only have space for one button so it needs to just be "more" - instead of the text "View" I would expect to see a horizontal or vertical ellipse (three dots) that when selected displays the menu of actions of which one option would be "View.
![CleanShot 2021-02-28 at 20 02 06](https://user-images.githubusercontent.com/1079943/109473749-a3047600-7a6b-11eb-801f-babbbfb5ce53.png)

I agree that the hamburger is most commonly used for the topbar navigation and that's why I was suggesting using the alternative horizontal and vertical three dot button which means "more" and I believe can be used anywhere.

**Comment by somangshu** [comment]
Note - 

 - The requirement here is to get a [Hamburg](https://ant.design/components/menu/#header)/[Menu](https://material-ui.com/components/menus/#menus) widget which contains multiple actions with a configurable `onClick` action
 - This is an independent widget and can also be added as a table colum type
 - The behaviour of this component can exist in two ways:
     - Ellipsis mode
     - Expanded mode

@jsartisan @riodeuno please add anything I might have missed.

**Comment by jsartisan** [comment]
@somangshu @Nikhil-Nandagopal @areyabhishek 

We are thinking to make two widgets: Menu Widget and Button Group Widget.

Menu widget will work like this: https://material-ui.com/components/menus/
We will create an icon control for our property pane for this.

Button group will work like this: https://blueprintjs.com/docs/#core/components/button-group
The Button group will be in two phases. The second phase will have a nested menu for the button group.

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan if you look closely at the button group in the blueprint lib, it does not support nested menus, nested menus is a complex combination of button group with a popover. 
@somangshu I feel a button group is a better solution here than a menu in this case because a menu is for when you know that you want all the items in the drawer while a button group can decide what actions to show upfront vs in the drawer based on the space it has to render. A menu also needs a lot more configuration such as nested menus, icons, etc. which a button group does not.
The menu widget might also need to be created like a modal because the menu can be attached to any element. Any reason we're not considering doing it with blueprint itself? https://blueprintjs.com/docs/#core/components/menu

**Comment by somangshu** [comment]
@Nikhil-Nandagopal The original problem talks about a hamburg/drawer like behaviour. Thats why @jsartisan is pointing to the [material example](https://material-ui.com/components/menus/) which also is present in [blueprint](https://blueprintjs.com/docs/#core/components/menu.dropdowns) as you mentioned. The [idea](https://stackoverflow.com/questions/34755666/what-is-the-hamburger-menu-icon-called-and-the-three-vertical-dots-icon-called) behind this (also pointed out by the user) is to show more options/actions.

From our research, we understand that button group does not solve anything here as it's just a group of buttons and menus, And hence the proposal to first build a menu widget (solves current problem) and then button group which combines both buttons and menus. 

Additionally I will quote the [authors response](https://github.com/appsmithorg/appsmith/issues/3261#issuecomment-787783942) for some extra clarity 
> as long as ultimately it can be collapsed down to a single "more" button

**Comment by Nikhil-Nandagopal** [comment]
@somangshu got your point. I misunderstood that a button group would also dynamically allow collapsing of widgets.

**Comment by somangshu** [comment]
Raised a separate requirement for button group widget #4889

**Comment by jsartisan** [comment]
Here is the design file for the menu widget - https://www.figma.com/file/tVBQrt0G0XI89eS9m8cT5H/Menu-Widget?node-id=1%3A27

**Comment by somangshu** [comment]
Note:
- Component library to use
- Widget implementation
- New icon type control
- Test case for the implementation
- Documentation

@jsartisan @momcilo-appsmith Kindly confirm the icon set we are going to be using, to begin with.

**Comment by jsartisan** [comment]
@somangshu Creating a list of icons from the design system that we can use in the menu widget:

1. Three dots
2. Hamburger
3. Home
4. Edit/Pen
5. Delete
6. Add / Plus
7. Question mark
8. User
9. Settings
10. Close/Cross
11. Link
12. Documents
13. Share
14. Eye
15. Minus Circle
16. Add Circle

**Comment by jsartisan** [comment]
@somangshu Do you think we have variant + styles options here too like we are going to do with icon button widget instead of giving background and text color option?

**Comment by somangshu** [comment]
@jsartisan Yes that sounds like a valuable enhancement. Can we take it after the initial implementation.

**Comment by areyabhishek** [comment]
@tazmaniax Thanks for requesting this feature! We launched it last week. Try it out

**Comment by tazmaniax** [comment]
@areyabhishek just having a look now - very excited!

**Comment by tazmaniax** [comment]
Awesome, this is how it looks now from the original that you can see [here](https://github.com/appsmithorg/appsmith/issues/3261#issuecomment-787783942). There is much more room to show the very long field value and I can provide multiple options - it's super useable, thx! I hope others find it just as useful
![CleanShot 2021-07-25 at 18 36 32](https://user-images.githubusercontent.com/1079943/126908119-4ff35a0e-ad15-46d2-8dbd-ebf4f087fc7e.png)
