### ISSUE TITLE
[Bug]: SSH key misconfiguration when connecting a new app to BitBucket on a custom SSH port

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#32636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The customer is using an airgapped image of Appsmith and have deployed BitBucket internally on a custom port. When they try to connect a new application to Git, they get SSH key misconfiguration error, no other git functionality works(commit, pull, push). When they import an already existing application through Git, everything seems to work fine.

[Relevent user conversation](https://theappsmith.slack.com/archives/C0341RERY4R/p1712908495924689?thread_ts=1712667891.728369&cid=C0341RERY4R)

### Steps To Reproduce

1. Deploy Bitbucket on a custom port
2. Create a new application within Appsmith
3. Try to connect the application with Git and configure keys for Bitbucket. Both ECDSA and RSA keys.
4. See an error related to SSH key misconfigured.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

1.11

**Comment by brayn003** [comment]
https://jira.atlassian.com/browse/BSERV-19297

**Comment by nidhi-nair** [comment]
Closed in https://github.com/appsmithorg/appsmith/pull/32777
