### ISSUE TITLE
[Bug]: Changing alignment from vertical to horizontal retains zone height and does not auto-adjust

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Allotted zone height does not readjust when widget orientation is changed leaving uneven gaps

### Steps To Reproduce

1. Drop a checkbox group widget
2. add a button widget next to it as seen in the video
3. change orientation of the checkbox widget and observe the gaps as seen in the video

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/0ac666fb385f4f8280d7af2c62c5a79d

### Version

cloud

**Comment by ichik** [comment]
This is expected.

**Comment by ramsaptami** [comment]
hmm, but looks off a bit, no? _(preview mode)_
![image](https://github.com/appsmithorg/appsmith/assets/79509062/470ebb8b-d626-429f-851d-c71b57788734)

**Comment by ichik** [comment]
@ramsaptami The chief offender here is the header that simply shouldn't be horizontally aligned with other widgets by itself and in fact should take the whole line. This has been discussed and planned, I believe, but not yet implemented.

**Comment by ramsaptami** [comment]
I added the heading widget to offer some perspective about alignment which was [called out today](https://theappsmith.slack.com/archives/C025SE88KNE/p1714642331000479)

> This has been discussed and planned, I believe, but not yet implemented.
noted

**Comment by ramsaptami** [comment]
I added the heading widget to offer some perspective about alignment which was [called out today](https://theappsmith.slack.com/archives/C025SE88KNE/p1714642331000479)

> This has been discussed and planned, I believe, but not yet implemented.

noted

**Comment by KelvinOm** [comment]
@ramsaptami I think we should close this bug. All this will fixed as separate activities.
