### ISSUE TITLE
[Task]: Return query_type even when we update actions

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#32652]
### SubTasks

In this https://github.com/appsmithorg/appsmith/issues/32554 we are returning query_type in the consolidated API for unpublished Actions. This would work fine and would suggest us fetch queries correctly on page load, but during application development, if a user modifies a query or creates a new query, its query type property is not getting updated immediately, it will only reflect when we load the page again. 

The behaviour should not be like this, irrespective of however we add actions in app, I should be able to see its reflections in suggestions

Check for all following cases:
- Generate CRUD
- Forking building blocks / templates
- Copy query
- Create action
- Import application

**Comment by rohan-arthur** [comment]
changed direction, not valid anymore [link](https://www.notion.so/appsmith/Suggested-Queries-Implementation-Plan-Task-Breakdown-8b9bdfc61ccf41f2b56abb703823d182)
