### ISSUE TITLE
[Feature] Add sticky columns to the table widget

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3265]
## Summary

Add the capability to make columns sticky in the table widget. 

## Motivation

When the table renders data with a lot of columns, sticky columns makes it easier for users to be able to scroll through the table horizontally.

## Additional Context
There is an extension available for react-table for this feature.
[https://github.com/GuillaumeJasmin/react-table-sticky](https://github.com/GuillaumeJasmin/react-table-sticky)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6uefg)

**Comment by somangshu** [comment]
Another user asked for this on discord

**Comment by pchambless** [comment]
Not a huge deal, but this would be great for users!

**Comment by ame-appsmith** [comment]
[Another user requested this feature](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100162103#part_id=initial-part-164629100162103-1416901874).

**Comment by sumetbua** [comment]
We are also interested in this feature and want to use it like a google sheet

**Comment by keyurparalkar** [comment]
Dev estimate - 7 SP

**Comment by charles-bloomfield** [comment]
This is pretty critical for our users!

**Comment by dilippitchika** [comment]
Hello @charles-bloomfield this is next in line for development, we will be sharing an update soon

**Comment by dilippitchika** [comment]
Meeting notes - 
1. Unfreeze will push the column to first or last
2. Change the control to a button group
3. Frozen columns take higher priority than hidden columns

**Comment by yoav-edikted** [comment]
Also waiting for this feature :)
