### ISSUE TITLE
[Bug]: AudioContext is undefined

### ISSUE THREAD

**Issue by ahkimkoo** [appsmithorg/appsmith#32669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

let audioContext=null;
if(window.AudioContext){
	audioContext = new window.AudioContext();
}else if(window.webkitAudioContext){
	audioContext = new window.webkitAudioContext();
}else{
	console.log(typeof AudioContext);
	console.log(typeof webkitAudioContext);
}

### Steps To Reproduce

typeof AudioContext is undedfined, My chrome browser supports AudioContext, but this problem occurs in appsmith

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

1.6.6

**Comment by Nikhil-Nandagopal** [comment]
@ahkimkoo appsmith limits access to window objects for security reasons. You can access it inside an iFrame or custom widget
