### ISSUE TITLE
[Task - Client]: Hide creating JS Objects in Workflows.

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#32670]

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32670?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by ayushpahwa** [comment]
Closing this in favour #32065
