### ISSUE TITLE
[Bug]: Label and sub-label have the same font weight on statbox widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Label and sub-label have the same font weight on statbox widget

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/e322bb25-d0f2-4ffd-88f7-4e596532a839)

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by KelvinOm** [comment]
I think is expected. Taras should we do something about this?

**Comment by ichik** [comment]
Using more font-weights than 2 on such a small number of elements would have a negative effect (too much emphasis).

**Comment by KelvinOm** [comment]
So we can close this bug, right?
