### ISSUE TITLE
[Bug]: Not able to copy page URL from page settings panel

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#32693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are not able to copy the page URL from the page settings panel.

### Steps To Reproduce

1. Go to an app.
2. Click on the settings icon & in the page settings section click on any page.
3. Try to copy the page URL.

**Expected:** The URL should get highlighted while selecting it & should also get copied.
**Actual:** The URL is not getting copied.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/643f8aee2f0f4345a99ec8ec27ba81d6

### Version

Cloud

**Comment by rohan-arthur** [comment]
I'm sorry I don't understand a couple of things. 
1. What is the expected behaviour? Should the URL be copy-able or not?
2. Also, saw that in both release and prod the copy is not possible. Isn't the tag `release blocker` for regressions caught on release and not on prod?

**Comment by shadabbuchh** [comment]
> I'm sorry I don't understand a couple of things.
> 
> 1. What is the expected behaviour? Should the URL be copy-able or not?
> 2. Also, saw that in both release and prod the copy is not possible. Isn't the tag `release blocker` for regressions caught on release and not on prod?

https://theappsmith.slack.com/archives/CTHN8GX5Y/p1713247158789679?thread_ts=1713246401.528689&cid=CTHN8GX5Y
