### ISSUE TITLE
[Bug]: Property pane has a margin on the right that looks odd when there is no scrollbar

### ISSUE THREAD

**Issue by vinay-appsmith** [appsmithorg/appsmith#32702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The property pane has a margin-right reserved for the scroll-bar. This looks odd as the section separators don't span the full-width and this is more apparent when the sections of the property pane are collapsed by default.
<img width="605" alt="image" src="https://github.com/appsmithorg/appsmith/assets/101088862/41e91aef-24c7-4f6d-b780-039d1664166b">

Possible solutions:
- Set the scrollbar's overflow behaviour to `overlay` or,
- Have equal horizontal padding on both the sides.

### Steps To Reproduce

Collapse the sections of a widget on the property pane. You will see the 'odd space' that exists to the right.

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by raushan3737** [comment]
Hi @somangshu , @Nikhil-Nandagopal : I am picking up this issue.

**Comment by Naveen-Goud** [comment]
Hi @vinay-appsmith  @Nikhil-Nandagopal , I am picking up this issue !

**Comment by Nikhil-Nandagopal** [comment]
@Naveen-Goud this is not a good issue to pick up. Please look at our good first issues and the ones labeled inviting contributions
