### ISSUE TITLE
[Epic] SaaS Integrations v1

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3270]
This epic tracks the effort required to set up SaaS integrations via Appsmith cloud services. We expect to be able to integrate any RESTful service through this new plugin type. All such plugins should follow the UQI.

**Comment by ajinkyakulkarni** [comment]
For details see meeting notes https://www.notion.so/appsmith/API-Marketplace-Estimation-Meeting-May-13-2021-20f12a65255044a6ac3890dd91d415f7

**Comment by nidhi-nair** [comment]
Closing as completed, open issues do not belong to v1.
