### ISSUE TITLE
[Bug]: Empty icon present on icon tray

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Icon named `brand-kbin` is empty 

### Steps To Reproduce

1. Drop an icon widget on the latest anvil DP
2. search for `brand-kbin` and observe the search result

![image](https://github.com/appsmithorg/appsmith/assets/79509062/2a19da1b-8adf-459d-b888-b79255f9a4cc)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by ramsaptami** [comment]
@ichik is this something that falls within your purview?

**Comment by ramsaptami** [comment]
@ichik is this something that falls within your purview?

**Comment by ichik** [comment]
@ramsaptami not really, this seems like a bug rather than case of deficiency in the design.

**Comment by ramsaptami** [comment]
closing this as an icon button without icon works well as a status indicator
