### ISSUE TITLE
[Bug]: Git Deployed App, Protected Branch Doesn't Work as Expected. Must Remove Branch Protection for App to Work on Same Branch.

### ISSUE THREAD

**Issue by trey-thompson** [appsmithorg/appsmith#32716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With an Appsmith Business account and in my Git deployed application, my app works on my default branch; however, as soon as I protect that branch, the same code on the same branch somehow no longer works.

### Steps To Reproduce

Follow the steps laid out in this Scribe link:
https://scribehow.com/shared/Appsmith_Bug_Git_Deployed_App_Protected_Branch_Doesnt_Work_as_Expected_Must_Remove_Branch_Protection_for_App_to_Work_on_Same_Branch__-bqjl69XSJ2o4Lg6b9FEzw

### Public Sample App

https://data.pdiaa.mcgit.cc/app/advantage-analyzer-data-manager/products-65f0b0efb9357c71bceae531/edit?branch=production

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self Hosted v1.16

**Comment by infinitetrooper** [comment]
Hey @trey-thompson - thanks for reporting this. You should not see this issue in view mode(deployed version of the app), it's a bug in the preview mode of protected branches in your editor. Let me know if you see any issues in your deployed app.

We're gonna prioritize and fix this soon, sorry about the poor experience.

**Comment by infinitetrooper** [comment]
A similar issue to https://github.com/appsmithorg/appsmith/issues/30756, should be closed together with the same fix.

**Comment by brayn003** [comment]
Will continue posting any updates on https://github.com/appsmithorg/appsmith/issues/30756

**Comment by infinitetrooper** [comment]
Closed with https://github.com/appsmithorg/appsmith/issues/34128
