### ISSUE TITLE
[Bug]: Deleting a query from a page gives information that page is removed, instead of page modified

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#32733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I delete a query from a page, it comes up as " Page removed" instead of "Page modified"

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/6e079dd1-9799-4db5-83f1-cd41cf1d519a

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by brayn003** [comment]
Issue is resolved with this PR https://github.com/appsmithorg/appsmith/pull/32730
