### ISSUE TITLE
[Bug]: Application name change , share enable, fork enable - these actions show no commits on git status

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#32735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we change application name, enable share, enable fork - these actions show no commits on git status

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/c1564226-6ef5-482d-b737-1864c739bc81

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by Vardhannn** [comment]
No, this is the first issue raised so far will try to resolve ASAP.

**Comment by nidhi-nair** [comment]
Closing for the reasons mentioned by Rudra above.
