### ISSUE TITLE
[Bug]: Renaming objects show up as deleted and added in Git status modal

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#32740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the page name is modified the event name should be displayed as page x modified instead of showing page added and deleted  as 2 seperate events

### Steps To Reproduce

1. go to git connected app
2. Now change a name of the existing page
3. The event name is displayed as "Page added and deleted " instead of Page Modified"

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

v1.21

**Comment by btsgh** [comment]
https://www.notion.so/appsmith/Incorrect-information-in-the-git-modal-on-renaming-a-query-e2d25bbd9a6944e58af48f592e92d8fb?pvs=4

As per this comment, it is out of scope.

However, we would still like to track this to being fixed, as this is not a great experience for the user, as he has not removed anything.

**Comment by brayn003** [comment]
As of yet, we don’t support renaming objects, as it is not supported by jgit currently. As an alternative, we show "a" is removed and "b" is added.

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by RoopKrrish9696** [comment]
This is expected behaviour wrt git.
