### ISSUE TITLE
[Task]: In git status the "added" text next to each event looks repetitive. Instead, we can simply place the 'added' text at the top of the event

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#32741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The "added" text next to each event looks repetitive. Instead, we can simply place the 'added' text at the top 
<img width="645" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/b5629984-ee23-45f1-86ef-a4a4c3f787e9">

### Steps To Reproduce

1. go to git connected app
2. generate the crud page
3. Now click on the + icon
4. in the git deploy modal
5. In the query added section each query is displayed with the text added next to it which looks repetative

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

v1.21

**Comment by infinitetrooper** [comment]
@RakshaKShetty  - Noted, we're gonna update to a more symbol/color model when we move to the new IA. We tried multiple such designs in modal but, the UI always looked off.

**Comment by btsgh** [comment]
@infinitetrooper .. so if I add many queries, the commit modal shows up with 4 queries added
   DeleteQuery added
   UpdateQuery added
   SelectQuery added
   InsertQuery added

**Comment by infinitetrooper** [comment]
But, try with 1 add, 1 delete and 1 edit - we need to show individual for that scenario and if we do that there, we have to keep it consistent elsewhere.

**Comment by brayn003** [comment]
Closing this for the reasons mentioned above
