### ISSUE TITLE
[Bug]: Incorrect information in the git modal on renaming a query

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#32742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upon renaming a query the change is displayed in such a way that it makes on think that a query was deleted & a new one was added.

### Steps To Reproduce

1. Add a query and commit the changes.
2. Now rename the query.

**Expected:** The message should be something like: Query <old name> renamed as <new name>.
**Actual:** Instead we see: <old name> removed, <new name> added.

### Environment

Release

### Severity

Medium (Frustrating UX)

### Issue video log
https://www.loom.com/share/afbc25b8cd8943b191ca7845cc02bd75

_No response_

### Version

Cloud

**Comment by shadabbuchh** [comment]
https://www.notion.so/appsmith/Incorrect-information-in-the-git-modal-on-renaming-a-query-e2d25bbd9a6944e58af48f592e92d8fb?pvs=4

**Comment by brayn003** [comment]
As of yet, we don’t support renaming objects, as it is not supported by jgit currently. As an alternative, we show "a" is removed and "b" is added.

**Comment by brayn003** [comment]
Closing this as a duplicate for #32740
