### ISSUE TITLE
[Bug]: No info shown for DnDing a widget in a specific scenario

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#32745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We do not see any information on the git modal on dropping a widget after creating a new page. 

### Steps To Reproduce

1. Create a new page.
2. Without committing the change, DnD a widget.
3. Now click on the commit icon.

**Expected:** We should see information about both the page getting added & the widget being dropped.
**Actual:** We only see info about the page getting added. 

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/5b43763b59dd40799f4b5cda54f094a8

### Version

Cloud

**Comment by btsgh** [comment]
Note: incase of a jsobject or a query - the respective jsobject or query is listed granularly under the page, where as for widgets it is not.

**Comment by shadabbuchh** [comment]
https://www.notion.so/appsmith/No-info-shown-for-DnDing-a-widget-in-a-specific-scenario-859803115a87492ba7cab318b5692403?pvs=4

**Comment by brayn003** [comment]
In this scenario, the correct behaviour is to show page added and not page modified. This is because the entire page was added and not committed. Eg - If a page is added with any resources, the messaging will be page added. Also currently, our system does not support widget level changes

**Comment by brayn003** [comment]
Also, this should be resolved with this PR https://github.com/appsmithorg/appsmith/pull/32730
So closing this
