### ISSUE TITLE
[Bug]: error log is not copy-able

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I have an erroneous query, I see the error both in response and error tabs. In neither of these tabs can I copy the error itself - this is important because I may want to search on google or stackoverflow etc. to rectify the error. 

This was working before, so treating this as a regression.

https://github.com/appsmithorg/appsmith/assets/94514895/2ed2d611-4161-4843-bb32-927b75e37860

### Steps To Reproduce

1. create an erroneous query
2. execute it
3. see that there's an error response
4. try to copy the error --> not able to copy

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by wawa79** [comment]
Happy to see I am not alone. This is making SQL debuggin terrible with long queries :-)

If it may help, it was working properly in AppSmith version 1.17 and I noticed the issue after upgrading to 1.21. 

Running latest version of Chrome Browser.
