### ISSUE TITLE
[TASK- RTS] JEST and cypress testcases for RTS changes for temporal test run

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#32765]

**Comment by nsarupr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32765?planning-poker) with Zenhub @ayushpahwa @srix

**Comment by nsarupr** [comment]
Closing this because this task has been divided to multiple issues.
