### ISSUE TITLE
[Bug]: Toggling 'allow currency change' does not reflect on the UI

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Toggling 'allow currency change' does not reflect on the UI

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/521bdc68-e425-4412-a890-4ed14b7f2b72)

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Version

cloud

**Comment by andreevanatasha** [comment]
Duplicate of #32031
