### ISSUE TITLE
[Bug] Activity failing with error "No datasource configuration found. Please configure it and try again" even when there is a working datasource

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#32787]
[logs.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk55QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f20d7f88ad0ddacc127c792ae9368aff4890aeb3/logs.txt)

Steps to produce it:
1. Create a Datasource.
2. Create a Workflow.
3. Create the API key.
4. Create a query on datasource above.
5. Publish the workflow.
6. Trigger the workflow via webhook.

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32787?planning-poker) with Zenhub @ayushpahwa @nsarupr
