### ISSUE TITLE
[Bug]: Tables containing the same data navigate between pages when only one is interacted with

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

moving across pages on a table widget while having another table widget connected to the same datasource on a page causes both tables to switch pages

### Steps To Reproduce

1. drop 2 table widgets on canvas of the latest anvil DP
2. connect both to the same datasource
3. navigate to across pages on one table and notice both table load different pages

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/bc16760309414512a676801fedef490e

### Version

cloud

**Comment by jsartisan** [comment]
@ramsaptami Most likely this was happening when using server side pagination, and we have removed it, so not relevant. Feel free to re-open it if you find it again.
