### ISSUE TITLE
[Bug]: Make the entity name UI more intuitive

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#32790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Right now if we add a query or a JS Object, the name of the entity is displayed in normal colors. This make it hard to understand what was added and does not feel intuitive. We should think of making it more readable & intuitive by displaying the name of the entity with better UI (probably highlighting/changing the color of the name).
<img width="440" alt="Screenshot 2024-04-18 at 5 18 45 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/a0d9daf4-5e08-452c-8b47-3b241cdeec2d">

### Steps To Reproduce

1. Add a query `Query 1`.
2. Click on the commit icon.

**Expected:** From just looking at the modal the user should make out the name of the query added.
**Actual:** It is hard to do so as because the name is displayed in plain text

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by brayn003** [comment]
Thanks for the input.
Although, this is more an enhancement request. Internally, we had a lot of debate on how to approach this and then we settled on this UI. This will be changed in the future when IA changes come in. Would appreciate if you could point this out during feature planning.

**Comment by brayn003** [comment]
Closing this, will raise an epic when doing the IA changes
