### ISSUE TITLE
[Task]: Write integration tests for happy paths of JS module

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#32792]
### SubTasks

- Create a JS module
- Add a private JS to an existing JS module
- Add a private query to an existing JS module

[Relevant Slack Thread](https://theappsmith.slack.com/archives/C04GRCN4CS3/p1713417729339709)

**Comment by ashit-rath** [comment]
Closing this in favour of https://github.com/appsmithorg/appsmith/issues/32010
