### ISSUE TITLE
[Bug]: Table cell and text colour pickers do not get updated after changing app theme colour

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table cell and text colour pickers do not get updated after changing app theme colour

### Steps To Reproduce

1. Change app theme colour on an a table widget on the Anvil instance
2. Drop a table widget on the canvas and connect to some data
3. Navigate to the style tab and notice colours listed under `theme colours` and `application colours`

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/7aef9641655147b9bbc3a36cd9119737

### Version

cloud

**Comment by ramsaptami** [comment]
@jsartisan should we keep this open still when this property no longer exists on the table?

**Comment by KelvinOm** [comment]
Seems like not relevant already. @ramsaptami could you check this please?
