### ISSUE TITLE
[Bug]: Extra scroll bar appears on screen when scrolling from the bottom to the top of the property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Extra scroll bar appears on screen when scrolling from the bottom to the top of the property pane. This occurs intermittently for the modal + input combo.

### Steps To Reproduce

1. Drop any widget which has a long property pane, like table, input etc...
2. Open up it's property pane
3. Scroll to the bottom of the property pane and pause for a few seconds
4. Scroll back up to the top and notice an extra scroll bar appear on screen

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/e1a4d99ac4a842c58efda86d431d413d

### Version

cloud

**Comment by KelvinOm** [comment]
@ramsaptami I can't reproduce it on my side. Which browser is this?

**Comment by ramsaptami** [comment]
I've updated the description to accurately repro this, _hopefully_
I'm using the latest Chrome + windows 12
