### ISSUE TITLE
[Feature]-[100]:Have a feedback loop for Beta Widget.

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#3284]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.25 |

**Comment by Nikhil-Nandagopal** [comment]
@Debsourabh nice feature request. This also ties back to #3035 and should work for both. Can you look into how do products like Gitlab / Rudderstack do this?

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.25 |
