### ISSUE TITLE
[Task]: Test widget selection DP

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32854]
### SubTasks

- w/o visual separation for all layers
- 3 layers of selection via canvas
- naming convention
- grab and move

logging issues [here](https://www.notion.so/appsmith/widget-selection-QA-52a124d2e160488396b466fb1f6464f7)

**Comment by somangshu** [comment]
@ramsaptami should this be closed?

also are we now creating separate tasks to test features?

**Comment by ramsaptami** [comment]
I'll close this, and yes, creating a task for QA - helps with visibility
