### ISSUE TITLE
[Bug]: Unable to select modal widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to select modal widget

originally raised during [QA](https://www.notion.so/appsmith/widget-selection-QA-f5a98995b1b643108771b343aed7a2d3?pvs=4#0dd04cfa00b2442a8eaeda6a75522d57) for the widget selection DP but this is on the base DP and so raising it separate

### Steps To Reproduce

1. drop a modal widget on canvas
2. drop widgets into the modal
3. try selecting the modal widget

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by marks0351** [comment]
This has been fixed as part of #32839
