### ISSUE TITLE
[Bug - RTS] Activity status is shown as success even though the activity failed

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#32875]
### SubTasks

![Error message not showing properly in run history](https://github.com/appsmithorg/appsmith/assets/20905988/5527a25d-4478-44c6-9a83-5f36caa10e8e)

**Comment by Sheryar-bit** [comment]
Can I work on this issue ?

**Comment by Sheryar-bit** [comment]
can you please provide some more info?

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/32875?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by srix** [comment]
Thanks for asking @Sheryar-bit . This bug is for an enterprise feature and not part of the Community edition code. I  encourage you to check the other Good first issues.
