### ISSUE TITLE
[Task]: Implement show more option for Slash Menu

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#32896]
### Current Scenario

Today we only show the first 5 queries even if the api result has more queries. 

https://github.com/appsmithorg/appsmith/assets/25542733/37003a85-52e9-4bed-ab85-9c12cf3619f4

### Design

https://www.figma.com/proto/85kYou9qfqrxMXFuJLDKeU/Integrations-and-Templates%2FBuilding-blocks?type=design&node-id=694-96755&t=CqV6h29lfyTLGpys-0&scaling=min-zoom&page-id=351%3A70390

### Implementation

- We want to show load N more queries when we have more than 4 queries where the `N = total number of queries -4`
For example:- if we have 10 queries, 4 will be displayed to user with load 6 more queries
  - On click of load 6 more, user will see all 10 queries in the menu itself.

Ref: https://www.notion.so/appsmith/FE-Implementation-for-queries-Load-N-More-for-slash-menu-7427081559614a07a5f67d727bfaac29

**Comment by sneha122** [comment]
Moving it to blocked state as awaiting a decision on this on what approach to take: https://theappsmith.slack.com/archives/C05P3ME9MBR/p1714543171479949

**Comment by sneha122** [comment]
Updating the estimate to 2, as it is not as straightforward as it looked initially
