### ISSUE TITLE
[Bug]: Bind data menu in the query or API response doesn't hug the content's height.

### ISSUE THREAD

**Issue by vinay-appsmith** [appsmithorg/appsmith#32947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Bind data menu in the query or API response doesn't hug the content's height leaving an empty space. This looks odd.
Also, the menu heading should say 'Bind to a new widget' instead of 'Add widget'
https://pasteboard.co/WJMsLWJgQKsU.png

### Steps To Reproduce

Query -> Run -> Response tab -> Bind data 

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by rohan-arthur** [comment]
@vinay-appsmith I think this may have gotten fixed with some other issue, below is the screenshot from prod
![Screenshot 2024-05-27 at 11 29 22](https://github.com/appsmithorg/appsmith/assets/94514895/160b38a6-54ba-4d7c-a83a-4d7cb1eca16d)
