### ISSUE TITLE
[Bug] UX : User can use same name for two columns in Table  

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3295]
Steps to reproduce:
1) Add a table widget
2) Click on Property Pane 
3) Add a 2 custom column 
4) Add a same name for the column 

Observation:
It is observed that name of the column is same 

Expectation:
On binding the column to an input we see conflict to identify the data . Hence when a user tries to add same name to the column an error message must be displayed to user 

![Screenshot 2021-03-01 at 3 16 19 PM](https://user-images.githubusercontent.com/71753653/109480233-4c199380-7aa1-11eb-85cd-73a898eba1cd.png)

**Comment by riodeuno** [comment]
@prapullac This should not effect the functionality of the Table. Also, some columns can have the same name. I consider this a non-issue.

**Comment by prapullac** [comment]
@riodeuno as per above comment we can close the issue.
