### ISSUE TITLE
[Bug] Datepicker replaces Day with Month when default date is used with moment

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3297]
On using moment with a specific format in the default date, datepicker shows the same date with day and month interchanged.

<img width="762" alt="Screenshot 2021-03-01 at 5 41 16 PM" src="https://user-images.githubusercontent.com/6636360/109495484-580f5080-7ab5-11eb-93b6-b1eba76ea71c.png">

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan @vicky-primathon the correct solution here should be to validate that the default date only accepts ISO strings.

**Comment by jsartisan** [comment]
<img width="797" alt="Screenshot 2021-03-04 at 6 20 46 PM@riodeuno "https://user-images.githubusercontent.com/6636360/109966516-5c867400-7d16-11eb-9edf-b3d637d02648.png">

@riodeuno @vicky-primathon Getting this error when using moment for default date

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan you should use ISO strings. Either {{ moment() }} or {{ moment().toISOString() }}
