### ISSUE TITLE
[Feature]:  Run crypress with mongodb profiler to analyze any slow queries

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#32972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Running cypress tests with mongodb profilers helps in analyzing and marking any slow queries  thereby helping the stability

### Why should this be worked on?

Helps in stability

**Comment by Nikhil-Nandagopal** [comment]
@pratapaprasanna since we're moving to postgres, this no longer makes sense right?
