### ISSUE TITLE
[Feature]: Implement Widget Archiving Functionality

### ISSUE THREAD

**Issue by LuisVicenteCorreia** [appsmithorg/appsmith#32977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Introduce a new feature that allows users to archive widgets. Archived widgets will be hidden from the main canvas but stored in memory for potential later reuse. This feature will include a new section for archived widgets in the left editor side pane for management, and a dedicated archiving button in the property pane, next to existing buttons like Copy and Delete. If possible, @ARibeiro3110 and I would like to work on this feature.

### Why should this be worked on?

Archiving widgets enhances the flexibility and usability of the canvas, allowing users to declutter their workspace without permanently losing their configurations.

**Comment by Nikhil-Nandagopal** [comment]
@LuisVicenteCorreia I'm not exactly clear on the problem you are trying to solve here with this feature. If it's to reuse widgets, we are already working on this functionality here #5229
