### ISSUE TITLE
[Task]: Hyperlink to the workspace name in the top-bar in the IDE.

### ISSUE THREAD

**Issue by vinay-appsmith** [appsmithorg/appsmith#32982]
### SubTasks

- [ ] Remove 'Back to all apps' in the app-name dropdown
- [ ] Hyperlink the preceding workspace name to take the user back to workspace.

https://pasteboard.co/8rVCdfuqpWHc.png

**Comment by alex-golovanov** [comment]
@momcilo-appsmith can you take a look if everything meets the eye? Here is the preview url - https://ce-34313.dp.appsmith.com

**Comment by momcilo-appsmith** [comment]
@alex-golovanov well done, you can push this. Did you use a component from our design system for this?

**Comment by alex-golovanov** [comment]
> Did you use a component from our design system for this?

Certainly, it uses the standard Link component.
