### ISSUE TITLE
[Bug]: client not showing correct value for workflow names returned from the workflow api

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#33017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

random values are returned from client even though server API is giving correct values. 

### Steps To Reproduce

* login 
* go to homepage
* search for a workflow name

### Environment

Release

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud

**Comment by ayushpahwa** [comment]
Closed with Ankita's changes
https://theappsmith.slack.com/archives/C05QG0J87UL/p1714744417206099
