### ISSUE TITLE
[Bug - RTS] Activity status is shown as success even though the activity failed

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#33019]

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33019?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by nsarupr** [comment]
Duplicate of #32875
