### ISSUE TITLE
[Task - RTS] Try catch for malformed JS.Failure in SQL queries and other activity errors needs to be propagated up, it’s impossible to debug otherwise. Temporal silent quitting. (Src property must be a valid json error is coming for datasource query) 

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#33027]

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33027?planning-poker) with Zenhub @ayushpahwa @nsarupr
