### ISSUE TITLE
[Bug]: Roles and Groups listing page are not loading for non-super admin users having access to view these pages via GAC

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#33034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Give a user access to view admin settings while not being a super admin. Login as that user and notice that the Groups & Roles listing pages keep showing a loader and no API is getting called to fetch the information to be shown.

### Steps To Reproduce

1. Login as super admin
2. Create a custom role and give access to view groups & roles
3. Assign this role to a user and login as that user
4. After logging in, go to admin settings page and notice that the Groups & Roles listing pages keep showing a loader and no API is getting called to fetch the information to be shown.

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Self Hosted - latest

**Comment by btsgh** [comment]
FYI - this seems similar to an issue that was seen a few months back, this issue was seen specifically on a DP and logged [here](https://github.com/appsmithorg/appsmith/issues/30381)  - however after taking the release pull, the issue did not seem reproducible.

**Comment by btsgh** [comment]
Tested and found to be fixed [30th Apr 2024]
