### ISSUE TITLE
[Feature]: Implementation of Widget Functionality for Embedding Other Pages

### ISSUE THREAD

**Issue by Alt-er** [appsmithorg/appsmith#33044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to propose the implementation of a widget functionality within the Appsmith low-code platform. This widget should enable the embedding of other pages, facilitating the creation of dynamic page layouts where users can switch between different embedded pages based on interactions such as button clicks.

While the traditional iframe approach can achieve some desired effects, it also introduces a plethora of other challenging issues that are difficult to resolve.

### Why should this be worked on?

The implementation of this feature is essential to facilitate the management of left-right page structures within the platform. By enabling users to embed different pages and switch between them based on interactions such as menu selections, we empower users to create dynamic and intuitive page layouts. This functionality enhances the usability and flexibility of the platform, allowing for the creation of diverse applications with varying page structures and content arrangements. Ultimately, it provides users with greater control over their application designs and improves the overall user experience.

**Comment by Nikhil-Nandagopal** [comment]
@Alt-er I believe we will solve this with #5229 You can follow that issue which will enable reusing and embedding groups of widgets across different pages and applications
