### ISSUE TITLE
[Bug]: Widget does not vertically center align when the adjacent zone has a vertically larger widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Widget does not vertically center align when the adjacent zone has a larger widget

![image](https://github.com/appsmithorg/appsmith/assets/79509062/630ab1fe-8480-4857-98b2-fb1991bc428f)

### Steps To Reproduce

1. Drop a radio group widget or any other widget with a label on canvas
2. Drop a toolbar button widget in a new zone next to it 

observe the toolbar widget is not vertically aligned

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by KelvinOm** [comment]
This is expected behavior. We don't align widgets in different zones, but only in same zone. 

@tbrizitsky @ichik

**Comment by ramsaptami** [comment]
this is the same behaviour when the 2 widget types mentioned here are placed in the same zone too
![image](https://github.com/appsmithorg/appsmith/assets/79509062/ff6aaed4-a829-40f9-bdb5-306470368b15)

this alignment is persistent on view mode too
cc: @KelvinOm
