### ISSUE TITLE
Task: update all templates and building blocks mock DB credentials 

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#33084]
The all 19 building blocks and all 22 use case templates have been updated. The following changes were made

- Update datasource name from Mock_DB_V2 to Sample Database
- Update datasource user from postgres to templates, re-authenticate datasource and re upload all app JSONs
- Migrated the following templates (Google Maps Navigation, Vehicle Maintenance, Whatsapp CRM, Employee Time Tracker, Business Analytics Dashboard, IT Asset Tracker) to mockdb_v2 (Sample Database)

**Comment by rahulbarwal** [comment]
along with this take care of #31734

**Comment by jacquesikot** [comment]
The following templates and building blocks got their credentials changes to template user and datasource name changed from Mock_DB_V2 to Sample Database

**Templates**
- [x] Customer Support Dashboard
- [x] Order Fulfilment Tracker
- [x] Content Management System
- [x] KYC Dashboard
- [x] Product Catalog CRUD
- [x] Loan Approval App
- [x] Inventory Management Dashboard
- [x] Todo App
- [x] Crypto Live Tracker
- [x] Delivery Service Management
- [x] Maintenance Order Management
- [x] IT Asset Tracker
- [x] Customer Messaging Tool
- [x] Applicant Tracker
- [x] Bugs and Issues Manager
- [x] Business Analytics Dashboard
- [x] Meeting Scheduler
- [x] Employee Time Tracker
- [x] Whatsapp CRM
- [x] Google Maps Navigation
- [x] Fund Raising CRM
- [x] Vehicle Maintenance App

**Building Blocks**
- [x] View Data
- [x] Edit Data
- [x] Table Lookup
- [x] Update Data
- [x] Sort & Filter Table
- [x] Date Filter
- [x] Validated Form
- [x] Insert Data
- [x] Delete Data
- [x] Conditional Formatting
- [x] Upload Files
- [x] Camera Upload
- [x] Login Flow
- [x] Editable Table
- [x] Action List
- [x] Address Map
- [x] Refresh on Click
