### ISSUE TITLE
[Bug]: Unable to Sync backup to S3 bucket

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#33098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are few changes to the latest backup and restore in appsmith and post that uploading backups to s3 isn't  working

### Steps To Reproduce

start appsmith and run the below command

docker-compose exec appsmith appsmithctl backup --upload-to-s3

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

latest

**Comment by db-nfwf** [comment]
S3 backup not working (have a Business plan):

`Created final archive
Finished creating an encrypted a backup archive at /appsmith-stacks/data/backup/appsmith-backup-2024-05-16T12-37-35.763Z.tar.gz.enc
Uploading backup archive to S3 bucket ********** (masked)
Error: ENOENT: no such file or directory, open '/appsmith-stacks/data/backup/appsmith-backup-2024-05-16T12-37-35.763Z.tar.gz'
    at async open (node:internal/fs/promises:636:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async Object.uploadArchiveToS3Bucket (/opt/appsmith/utils/bin/aws.js:54:25)
    at async Object.run (/opt/appsmith/utils/bin/backup.js:76:7)`
