### ISSUE TITLE
[Feature]: onFocus and onBlur Events for RichTextEditor

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#33117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need to add the onFocus and onBlur events to the RichTextEditor. These are available for other input widgets, but not for the RichTextEditor.
[Use case of a user](https://app.frontapp.com/open/cnv_1ahw6oi4?key=SK6AoZi5Tpozx1cdDVtSoM7b7DX8r26r): Show the RTE toolbar onFocus and hide it onBlur.

### Why should this be worked on?

This feature would improve the UX and provide users the ability to implement various use cases.

**Comment by Nikhil-Nandagopal** [comment]
The use case to show/hide the RTE toolbar isn't very apparent to us. I'm closing this issue but if the user facing this would like to add more context, please do explain why this is necessary.
