### ISSUE TITLE
[Bug]: Input parameters for queries are not showing up in Run history for some activities

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#33137]
<@U025TQ6P4MA> - When I pass input params like this, why is it not showing up in run history? It's showing up in other workflows though.

[Slack Message](https://theappsmith.slack.com/archives/C05QG0J87UL/p1714649013621519)

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33137?planning-poker) with Zenhub @ayushpahwa @nsarupr
