### ISSUE TITLE
[Bug]: query.data references in a subsequent workflow query is not working 

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#33143]
Reproduction

1. Create a workflow with 2 queries
2. Use `query.data` from query 1 in query 2
3. Write workflow to run query 1 and then query 2
4. Trigger the workflow

You should see an error for query 2 - src property must be a valid json

In my case, the reference was `query1.data.data.closed.count`, consider if that is a special case, putting images below of workflow.

<img width="952" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWF1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1302df83a82d2f40fbdea3c79e498c32c422ebe/image.png" alt="image.png" />
<img width="1867" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWV1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e228b205232efa6b50851375dc63afb483d9bc2/image.png" alt="image.png" />

**Comment by infinitetrooper** [comment]
This could be related to https://github.com/appsmithorg/appsmith/issues/33163

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33143?planning-poker) with Zenhub @ayushpahwa @nsarupr
