### ISSUE TITLE
[Bug]: Intermittent Internal Server Error when deploying a workflow

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#33168]
This appears sometimes but, workflow deploys when we click on deploy again.

**Comment by nsarupr** [comment]
Not able to reproduce this issue on my Local. 
Also, the logs related to the previous error aren't present on Mezmo anymore.
[Slack thread](https://theappsmith.slack.com/archives/C05QG0J87UL/p1715840992984679)

**Comment by nsarupr** [comment]
For the moment, closing the ticket.
Will re-open it if this issue is resurfaced.
