### ISSUE TITLE
[Bug]: Not all activities details are being shown run history of a run

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#33164]
There should be 32 loops here, it's only showing 15 loops. The workflow is successful as we can see the final result after all the loop.

<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFd6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee44443cabc6ade2d857f3cdae68764b0402848c/image.png" alt="image.png" />

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33164?planning-poker) with Zenhub @ayushpahwa @nsarupr
