### ISSUE TITLE
[Bug]: Bindings on nested objects passed as params are not being recognised

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#33163]
The bindings are working when individual parameters are being sent

<img width="952" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFN6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ac4f377a0a0a297a9f0a3242a8e1abe7cf4caa1/image.png" alt="image.png" />

**Comment by nsarupr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33163?planning-poker) with Zenhub @ayushpahwa @srix
