### ISSUE TITLE
[Bug]: Persistent Delete Button After Data Source Deletion 

### ISSUE THREAD

**Issue by ashwin-solanki-789** [appsmithorg/appsmith#33182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever we create a new Database source and then delete it. The confirmation state persist for the default state as well.

### Steps To Reproduce

1. Navigate to the data source management section of the website.
2. Click on the option to add a new data source.
3. Once added, observe the delete button displayed on the right side of the added data source.
4. Click on the delete button to initiate the deletion process.
5. Confirm the deletion when prompted.
6. Notice that while the data icon on the left disappears and the default data icon is selected, the popup for the delete button remains visible, which is not the expected behavior.

### Environment

Release

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://www.loom.com/share/02541e794f9a4bee9cce3ebb4cacc1d0

### Version

Self Hosted

**Comment by Nikhil-Nandagopal** [comment]
Thanks for reporting this @ashwin-solanki-789 . We're tracking this issue here already so I'm closing this as a duplicate
#32954
