### ISSUE TITLE
[Bug] UX : An additional option  "No Selection" must be displayed under Date Format

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3318]
Steps to reproduce:
1) Add a table widget
2) Navigate to property pane 
3) Add a custom column
4) Click on setting of column
5) Add Column Type as "Date"
6) Navigate to Date Format
and observe the dropdown 

Observation:
It is observed that the user selects an format and use is not displayed with de-selection 

Expectation:
Displaying  option  "No Selection"  helps user go back to default option

Screenshot:
![Screenshot 2021-03-02 at 4 38 58 PM](https://user-images.githubusercontent.com/71753653/109639947-daf7e000-7b75-11eb-8187-a556489b6b37.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac a format must always be present so here the option can be Original Format

**Comment by somangshu** [comment]
@Nikhil-Nandagopal today in the date picker we have the default format set as `YYYY-MM-DD HH:mm`. Does it solve the problem here. I feel we do not need to show a separate option for as there is a default selected from before.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu it doesn't because the table receives a date in the user's format which we do not know.

**Comment by somangshu** [comment]
![Screenshot 2021-05-06 at 10.43.55 AM.png](https://images.zenhubusercontent.com/60583007e1e4e5398dc9ec58/3953ecc9-62d1-4dce-8a64-b1b1a53c25bc)
