### ISSUE TITLE
[Bug]: Text and links on datasource screen don't work after no selection of GSheet

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#33195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If we don't select a particular GSheet after choosing "Authorize datasource for selected Google sheets" option, the text and links on the screen don't work. The text cannot be selected/copied. The links to "Authorize datasource" or "Contact support" aren't clickable.

<img width="1380" alt="Screenshot 2024-05-06 at 1 59 43 PM" src="https://github.com/appsmithorg/appsmith/assets/458946/c33a223c-c557-4964-8074-660ae94ec4d1">

### Steps To Reproduce

1. Create GSheets datasource. 
2. Choose "Authorize selected Gsheet only" option. 
3. When asked to select the particular GSheet, close the modal without any selection. 
4. See that the datasource page doesn't have any working links.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud / Self-hosted

**Comment by rohan-arthur** [comment]
https://github.com/appsmithorg/appsmith/assets/94514895/8d918dff-aa3d-4da8-ab14-b1de7849951f

- _the links are clickable_: Please see attached video, not able to replicate this. I am using chrome, also tested on firefox. 
- _the text is not cipy-able_: this is a more systemic issue, we are discussing it [here](https://theappsmith.slack.com/archives/C02JT9CSE6L/p1717397621676459) and [here](https://github.com/appsmithorg/appsmith/issues/33849)
