### ISSUE TITLE
[Bug]: Widget tooltip gets overlapped with canvas boundary

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Any widget placed on the top row of the canvas and has a configured tooltip gets overlapped with canvas boundary

![image](https://github.com/appsmithorg/appsmith/assets/79509062/bc71ba5e-a3b6-48c7-8fb9-e67b49e73ba9)

### Steps To Reproduce

1. Drop an icon widget on the top row of the canvas
2. set a tooltip on it's property pane
3. go to preview mode and check the tooltip behaviour

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by somangshu** [comment]
@marks0351 need to triage this for the effort required.

**Comment by KelvinOm** [comment]
This happens when navigation is active. To fix this correctly, we need to redo the navigation. Now we have disabled navigation by default.
