### ISSUE TITLE
[Enhancement] [Dropdown Widget] Allow removing search input for filtering options

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#3321]
## Summary
Allow removing search input for filtering options

**Comment by KishkinJ10** [comment]
I am a beginner can i work on this?

**Comment by aswathkk** [comment]
@KishkinJ10 Sorry, I didn't see your comment. I'm already working on this and raised a PR.

**Comment by KishkinJ10** [comment]
Ok sir no problem.
