### ISSUE TITLE
[Feature]: PWA (Progressive Web Apps)

### ISSUE THREAD

**Issue by visethhul** [appsmithorg/appsmith#33226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

looking nice all widget  I checking on channel youtube appsmith. but  i don't see guy showing with PWA. 
if we have this feature. looking great.   

### Why should this be worked on?

it's very save time for development . the same time we development web app and mobile app.

**Comment by Nikhil-Nandagopal** [comment]
@visethhul we have this feature tracked here #2266 and we're working on a responsive mobile builder to achieve this.
I'm closing this issue in favor of that.
