### ISSUE TITLE
[Bug]: Splitpanes - Extra space in the hamburger query menu. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Note that there is an extra space in the hamburger menu for queries in the split panes mode.

### Steps To Reproduce

<img width="499" alt="Screenshot 2024-05-07 at 11 00 31 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/a4a8c122-46d8-4852-8763-001ae89a74e8">

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud v1.24

**Comment by rohan-arthur** [comment]
we've updated the add state to span the full length now, so this issue is not valid anymore
![Screenshot 2024-09-05 at 17 26 25](https://github.com/user-attachments/assets/2a489779-c079-4666-8b5c-9ae5eb18361b)
