### ISSUE TITLE
[Feature] Option to get documents from Firestore in descending order of a field

### ISSUE THREAD

**Issue by mayurdhurpate** [appsmithorg/appsmith#3322]
## Summary

Currently, Firestore order by field takes a JSON array as an input with the name of fields to be ordered by. 
There is no way to specify the descending order for ordering.

Documentation reference: https://docs.appsmith.com/v/v1.2.1/datasource-reference/querying-firestore#fetching-multiple-documents

**Comment by sharat87** [comment]
Fixed in #3340.

**Comment by mayurdhurpate** [comment]
Hi @sharat87, is this live? Would love some pointers/documentation on how to use it.

**Comment by sharat87** [comment]
Hey, yeah this is live I just merged the [documentation PR](https://github.com/appsmithorg/appsmith-docs/pull/116) for this. You should see the docs also update soon.
