### ISSUE TITLE
[Bug]: Phone widget throws an undefined message when valid property field is configured

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When `valid` property is configured for a phone widget then the widget displays `undefined` text that cannot be cleared from view mode - this is not the same behaviour on other input widgets

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/01cfbfbf-2cdf-45ad-b2f0-dd002a6061e2)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/0a139aef-3f8d-4175-b7d2-c569ca91fd4f)

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by jsartisan** [comment]
@ramsaptami I am not able to repro this issue. Can you check if it is still happening? Please share reproducible steps.

**Comment by ramsaptami** [comment]
I can't seem to repro this either, I'm going to close this issue @jsartisan
