### ISSUE TITLE
[Bug]: Container does not have "Height" Property. 

### ISSUE THREAD

**Issue by rbudigelli** [appsmithorg/appsmith#33246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Container does not have "Height" Property. It only has "Visible" and "Animate Loading". This on Self Hosting version. 

### Steps To Reproduce

Container does not have "Height" Property. It only has "Visible" and "Animate Loading". This on Self Hosting version. 
Add a container to any Page. 

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Appsmith Community v1.18

**Comment by rbudigelli** [comment]
Additional Details - 
I see `Height` when switched to "Fixed Layout". When you have a container has a table and that table has more rows than the height, you don't have a way to scroll those table rowsd!

**Comment by Nikhil-Nandagopal** [comment]
@rbudigelli I'm not able to fully understand your issue.
By default the container has auto height and will wrap any widget you drop inside it
If you change it to fixed, you can manually resize the height
