### ISSUE TITLE
[Bug]: Git connected app shows uncommitted changes sometimes even after discard 

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#33265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Git connected app shows uncommitted changes even after discarding the changes

### Steps To Reproduce

1. Create a git connected app
2. Create a new page (page1), add queries to it and commit the changes
3. Add a new page (page2)
4. Discard the changes (Addition of page 2)
5. Notice that although page 2 gets discarded, the `+` icon shows uncommitted changes from the previous commit

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/8d5167f445f24ed38a60dbee1afeae80

### Version

Appsmith v1.24.0

**Comment by nidhi-nair** [comment]
@laveena-en for issues of this nature it would help debugging and triaging the issue if you also include information of what the exact change that starts to show up on the modal is. To do this, you would need to branch out of the app at the point where you see these unwanted changes and diff that new branch on the remote repo against your current branch.

This is also so that in case the issue gets lost and takes time to pick up, we have all the information we need about the issue without having to involve you.

**Comment by laveena-en** [comment]
Sure Nidhi, adding the details below:

Repo: https://github.com/laveena-en/april8-ee
Branch where the bug occurred: `bug-origin`
New branch created against it: `bug-branch`

Also adding in another loom [here](https://www.loom.com/share/999bdd6066f248b4ba8ea208cee80e95?sid=44b42a83-1416-46a4-8a77-f7033be95ea9) for better understanding of reproducing the bug

**Comment by nidhi-nair** [comment]
Thanks @laveena-en ! From [this](https://github.com/laveena-en/april8-ee/compare/bug_origin...bug_branch) diff, we can see that the property added was that of the timeout for all the actions in your app. Can you share more details of how you created these queries? Was it an import, a generate crud, a template query, or a manual one?

**Comment by laveena-en** [comment]
@nidhi-nair The queries were created via one click binding from the table widget (sample datasource-Users in this case)

**Comment by nidhi-nair** [comment]
Thanks! That's a great starting point now :) @rohan-arthur could you please help out here? Queries should possess all required default fields at the point of creation otherwise they will require updates and hence show up as diffs on git.

**Comment by NilanshBansal** [comment]
This issue is not reproducible now on app.appsmith.com. Hence closing this issue.
Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1719895360935799?thread_ts=1719558797.500369&cid=C040LHZN03V
cc: @laveena-en @rohan-arthur @nidhi-nair
