### ISSUE TITLE
[Bug]: fetch is not defined

### ISSUE THREAD

**Issue by Bleoo** [appsmithorg/appsmith#33268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="315" alt="image" src="https://github.com/appsmithorg/appsmith/assets/11569795/111a5d72-d917-4777-b534-632616d600a3">
After upgrading to v1.23, my app no ​​longer works

### Steps To Reproduce

-

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

self host v1.23

**Comment by Nikhil-Nandagopal** [comment]
@Bleoo is it only in edit mode or did the deployed app stop working?
does this issue persist after you make a small edit to the code?

**Comment by rishabhrathod01** [comment]
@Bleoo when the above function is run, what is the error message you see in the logs section? 

We have a bug where fetch shows an incorrect linting error currently hence we just want to make sure if the fetch API is functional in your case or not.

**Comment by Bleoo** [comment]
> @Bleoo when the above function is run, what is the error message you see in the logs section?
> 
> We have a bug where fetch shows an incorrect linting error currently hence we just want to make sure if the fetch API is functional in your case or not.

no error message show, it just cannot work.

**Comment by rishabhrathod01** [comment]
@Bleoo we would like to connect with you and debug your issue. Could you please send an email to support@appsmith.com with this GitHub issue URL.

**Comment by Bleoo** [comment]
> @Bleoo we would like to connect with you and debug your issue. Could you please send an email to [support@appsmith.com](mailto:support@appsmith.com) with this GitHub issue URL.

i can't, i did rollback to v1.21

**Comment by rishabhrathod01** [comment]
@Bleoo we have fixed the false linting error for the `fetch` API and we were not able to reproduce the fetch API not working as mentioned in the above comments. For now, as it cannot be reproduced, we are going ahead to close this. If this happens feel free to reopen this issue.
