### ISSUE TITLE
[Feature]: Add possibility to connect to Snowflake via Key Pair Authentication

### ISSUE THREAD

**Issue by sosdarko** [appsmithorg/appsmith#33278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When creating a Snowflake connection, add possibility to use private key (or just path) and also a passphrase for encrypted private keys.

### Why should this be worked on?

This is standard feature across many tools, like dbt, dbeaver and even SnowSQL. This would allow for many users to connect to Snowflake, where their companies require such an authorization. Also, if under the hood you already use SnowSQL or any driver that already supports private keys, it's just a matter of updating the connection Form and passing new parameters to the connector.

**Comment by csp33** [comment]
Hi, this feature is very important because it would allow configuring MFA for service users

**Comment by Annahariprasad** [comment]
Hi @sosdarko,

I have started working on this.

**Comment by AnnaHariprasad5123** [comment]
Hi @sosdarko,

I have started working on this.

**Comment by rohan-arthur** [comment]
@AnnaHariprasad5123 thank you for your interest. Our team is already working to solve this. 

In future, please check with us before picking up something, as described in the updated code contribution guide [here](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md), so that we don't both end up working on the same thing.

(By the way, the requirements description is spot on)

**Comment by AnnaHariprasad5123** [comment]
Thank you @rohan-arthur

**Comment by sosdarko** [comment]
Thank you all, looking forward for this feature!

**Comment by rohan-arthur** [comment]
@sosdarko this feature is now available in the latest release, i.e., v1.43

**Comment by sosdarko** [comment]
Hi, sorry for late response, thanks a lot @rohan-arthur for this!
My self-hosted instance has automatically updated (wasn't aware of this feature) and I've tested the key-pair authentication and it works :)
Thanks a lot, this definitely raises confidence in this product!
