### ISSUE TITLE
[Feature]: create binary deployment option

### ISSUE THREAD

**Issue by alessandromorandi** [appsmithorg/appsmith#33279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

if you check for pocketdb or nocodb you have the opportunity to run the software using a single binary.

https://docs.nocodb.com/0.109.7/getting-started/installation/#executables

https://pocketbase.io/docs/

### Why should this be worked on?

is it possible to install appsmith with a single binary ?

**Comment by Nikhil-Nandagopal** [comment]
@alessandromorandi what's the benefit of doing this over using docker? Binaries are hard to manage and update and require a lot of operating system specific maintenance. For those reasons, I will not be accepting this feature request unless there is a great reason to do this.
