### ISSUE TITLE
[Bug]: Git import a repo onto a workspace in app.appsmith.com shows up uncommitted changes related to a page.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I git import a repo onto a workspace in app.appsmith.com, I see uncommitted changes related to a page.

### Steps To Reproduce

Git import git@github.com:btsgh/11AprDpro.git repo onto a workspace in app.appsmith.com
Note that there are uncommitted changes related to datasources as well as pages.
Attached screenshots for the pages difference in both the app and the git repo which shows up as uncommitted changes. 

<img width="664" alt="Screenshot 2024-05-09 at 10 54 34 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/3a7cff2d-6558-4bac-8319-d607d2dbbf90">

<img width="1145" alt="Screenshot 2024-05-09 at 10 55 12 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/371ad919-0f50-43c7-950e-bc71b162d20c">

Note: The datasources related issue is tracked [here](https://github.com/appsmithorg/appsmith/issues/32425)

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by peyush99** [comment]
Hi @btsgh 

I'm not able to reproduce the issue with my git repository. Seems this issue is specific for this particular repo : [git@github.com](mailto:git@github.com):btsgh/11AprDpro.git

Can you please provide access to this repository.

**Comment by peyush99** [comment]
Hi,

I've been working to reproduce this issue by importing a forked repo of : [git@github.com](mailto:git@github.com):btsgh/11AprDpro.git

I'm able to reproduce the uncommitted changes related to pages(schedule modified) , but unable to do so for data sources as I do not have the credentials for it

![image](https://github.com/appsmithorg/appsmith/assets/99179162/159576ca-7bbd-478e-96c5-9d193f9c2b0d)


Could you please share the details?

**Comment by infinitetrooper** [comment]
Migration changes.
