### ISSUE TITLE
[Bug]: The .clear function of any API or Query is not working inside a workflow

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#33300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was using a workflow which is looping through a set of data, and running APIs on each record to extract some data.
And there are scenarios where I would not need to run an API if a parameter is missing from the looped object. So i added a line of code like Query1.clear() to clear the API's data, so that the previous records API data will not be used to fill in the ongoing records extraction.
But surprisingly the workflow does not seem to recognise the .clear() function of an API or Query.

https://theappsmith.slack.com/archives/C05QG0J87UL/p1715183551513749

### Steps To Reproduce

Invoke the .clear function of any API or Query inside the workflow, and the workflow run will not happen stating that this function was not found.

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Self Hosted - Nightly Build

**Comment by nsarupr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33300?planning-poker) with Zenhub @ayushpahwa @srix
