### ISSUE TITLE
[Bug]: Icon property field stretches beyond the property pane boundary

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Icon property field stretches beyond the property pane boundary

### Steps To Reproduce

1. Drop a button widget
2. toggle to JS mode on icon property on `style` tab
3. toggle back to UI mode and notice the field stretching to the right as seen in the video

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/fefee05f70564ec38f8511c1274eccd3

### Version

cloud

**Comment by jsartisan** [comment]
@ichik Should we consider this as an issue? I feel this is not an issue. I haven't seen an asterisk on a single checkbox component. 🤔
