### ISSUE TITLE
[Bug]: Unprotect branch option unprotects all branches

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#33310]
If I add a second branch as a protected branch and unprotect it fro m the option at the top of the screen, all my branches end up getting unprotected.

https://github.com/appsmithorg/appsmith/assets/5298848/a086ca97-9653-41d3-b8a1-99e18a0ac068

**Comment by AnkitaGupta111** [comment]
@nidhi-nair @Nikhil-Nandagopal I tried replicating this issue but couldn't replicate. This Feature of protecting multiple branches is removed from non enterprise appsmith edition it seems. I am able to protect only master branch.


https://github.com/appsmithorg/appsmith/assets/51366428/80bca50a-0fb8-4834-8446-b0d65d90426c

**Comment by Nikhil-Nandagopal** [comment]
@AnkitaGupta111 this is an enterprise specific issue so you will not be able to see it
