### ISSUE TITLE
[Bug]: When adding the json form inside a modal in a git connected app, the form is not detected as a change.

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#33356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A git connected app which has an existing json form inside a modal has its name changed then the changes are not reflected in the git. The older json would be deleted from changelist and the new one is not added.

### Steps To Reproduce

1. Create an app, connect to git
2. Create a modal and add a json form inside it. commit
3. Change the name of json form and re-commit, see the diff

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

1.21

**Comment by Shirisha-Manthoju** [comment]
Hello @sondermanish , I tried to reproduce this issue.
I have followed the below steps : 

1. Created an app and connected with git 
2. Created a branch with name : [feature-json-form]
3. Created a new page with title : [model_json_page]
4. Created a model and created the json form with sample movies data in that page
5. Did not do any changes , just created the model and json form inside it and committed those changes  (commit msg : added sample modal and json form)
6. After committing , made changes to the model title name , model name , json name and json form title name. 
7. I have committed these changes. (commit msg: renamed titles(title, model and json))

I could able to see the difference between my first commit and second commit 

Link : https://github.com/Shirisha-Manthoju/appsmith-sample-repo/pull/1/commits/c4d6dfb3c2c230dbb7bbf02073a82fdd981f595e

![Screenshot from 2024-06-07 14-14-09](https://github.com/appsmithorg/appsmith/assets/119922471/d4940689-5a2f-47a1-8adb-9a66ed34216c)

can you able to brief this issue, what exact difference or changes that we are looking for, which are not reflected in the git? 

Thank you.
