### ISSUE TITLE
[Feature]: Additional decimal 

### ISSUE THREAD

**Issue by CWatson-Tactile** [appsmithorg/appsmith#33361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I use Appsmith for my companies inventory management system and we have a lot of parts that have sub-dollar cost. Currently, I can only select 0, 1, or 2 decimal places. Would be nice to allow 3 decimal places at least.  Some of our parts are ordered in the tens of thousands, so even 4th decimal places can add up fast and significantly affect our estimates for ordering.

Specifically, I am using a JSON form with the 'Currency Input' field type. 

![image](https://github.com/appsmithorg/appsmith/assets/89869972/4e815665-3aa2-439c-b8db-e7e1db67b99c)
![image](https://github.com/appsmithorg/appsmith/assets/89869972/acf5521b-8ac5-419d-9b40-8d5f039e4854)

### Why should this be worked on?

More decimal places are needed to use with sub-dollar priced items for use with accounting and inventory management at large scales.

**Comment by AnnaHariprasad5123** [comment]
HI @CWatson-Tactile , I have raised a pr. Could you review it once.
