### ISSUE TITLE
[Bug] Multi select dropdown does not get reset inside a form

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3339]
### Steps to reproduce the behaviour:
1. Drag a dropdown
2. Make it multi select
3. Select 3 values
4. Reset the form
5. The dropdown does not get reset

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon can we get a fix for this merged? It looks like this happened again

**Comment by somangshu** [comment]
@prapullac @vicky-primathon this is not yet fixed completely. While the Dropdown gets reset, I think there is some problem with the default value in the release environment. When the default value is set, the option is not selected in the initial state and then when we try to make a selection other options in the dropdown gets selected.

https://user-images.githubusercontent.com/11089579/116654353-938ba580-a9a6-11eb-88e1-5f173099e475.mov

**Comment by sumitsum** [comment]
Re-opening this issue till @somangshu's comment is resolved.

**Comment by somangshu** [comment]
@sumitsum we are taking this issue as a new fix in #4230. This is slightly different from what the original bug is.

**Comment by sumitsum** [comment]
Thanks for the update @somangshu . Closing this issue as we are taking this up in #4230
