### ISSUE TITLE
Statbox polish

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#33397]
1. Make statbox is hug type widget.
2. Also add changes according to the documentation —https://www.notion.so/appsmith/Stats-box-card-design-0b60ac1057c0445b84e13fa4a6ea37cc

**Comment by tbrizitsky** [comment]
_The notion doc above is still the source of truth, the task breakdown is presented for convenience._

- The widget's new name is Stats (widget picker label, new widget's name in the entity explorer)
- Stats is a fill widget, not a large widget
- Value has a semantic color (see the referred doc for details)
- Property panel names are to be updated according to the document
- add onClick action (Vadim is a source of truth for exact visual tokens)
- Add optional background  (described in the doc)
