### ISSUE TITLE
[Bug]: Zone space distributor bounces back to its original position when adjusted

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On a refreshed app page, zone space distributor bounces back to its original position when adjusted

### Steps To Reproduce

1. Drop a couple of widgets as seen in the video
2. Move the zone space distributor and observe the handle bounce back - refresh the page and try again if this is not reproducible

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by ramsaptami** [comment]
reducing priority to tackle this post beta release
cc: @marks0351

**Comment by Shivam-z** [comment]
Hi , can anybody please provide us a loom video to reproduce this issue?

**Comment by ramsaptami** [comment]
@Shivam-z take a look at issues marked 'good first issue' if you're looking to contribute

**Comment by Shivam-z** [comment]
@ramsaptami  I tried to reproduce this issue but could not able to reproduce it.
Here is loom for the same: https://www.loom.com/share/d1866ac0120c44c0a0f3c5a78600e752?sid=db04badc-ca38-4f23-afa2-8c8e9eefcc7f
