### ISSUE TITLE
[Bug]: Unusual spacing & line breaks observed after font family update

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#33413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are noticing instances of unusual spacing & line breaks after the font family got updated to `PTRootUI`.

- [ ] Git modal
<img width="618" alt="Screenshot 2024-05-13 at 10 43 44 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/c7a2eabd-51e1-4f81-9fc9-1acc10e40cd9">

- [ ] Toast message - 
<img width="1295" alt="Screenshot 2024-05-14 at 10 22 57 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/84aac46f-e1d2-4c5c-847b-4fe79bb4dd6d">

- [ ] Share & Embed settings - 
<img width="318" alt="Screenshot 2024-05-14 at 11 07 32 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/37424191-b3f9-4d8a-9f24-22f001bf912d">

- [ ] Import settings - 
<img width="318" alt="Screenshot 2024-05-14 at 11 07 44 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/e02a8891-016a-44be-8b56-783bb6de1ce6">

- [ ] License screens - 
<img width="641" alt="Screenshot 2024-05-14 at 11 16 19 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/5a964b9d-5510-4643-a2fe-aec75d2d4a6f">

- [ ] Custom env deletion - 
<img width="617" alt="Screenshot 2024-05-14 at 5 25 22 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/4ecf64da-c849-4d26-b189-60287cd781b1">

### Steps To Reproduce

1. Go to https://app.appsmith.com/

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by shadabbuchh** [comment]
https://theappsmith.slack.com/archives/C02JT9CSE6L/p1715663269631909

**Comment by SaiCharanChetpelly31** [comment]
@shadabbuchh I can't find PTRootUI in dropdown here.
![image](https://github.com/appsmithorg/appsmith/assets/119920490/cc7eff7c-ccf1-48fd-8a9f-6e0b36f84a29)

**Comment by rohan-arthur** [comment]
fixed according to [this](https://theappsmith.slack.com/archives/C02JT9CSE6L/p1715773848189639?thread_ts=1715663269.631909&cid=C02JT9CSE6L)
