### ISSUE TITLE
[Bug]: Base.Dockerfile caddy-builder image go version outdated

### ISSUE THREAD

**Issue by anksingh-zuora** [appsmithorg/appsmith#33412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

anksingh💻[~/Desktop/setup/asmith]<n_rebase> $ docker build -t appsmith .
[+] Building 50.8s (8/21)                                                                     docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                          0.1s
 => => transferring dockerfile: 4.33kB                                                                        0.0s
 => [internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                               0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                               5.6s
 => [internal] load metadata for docker.io/library/caddy:builder-alpine                                       5.5s
 => [stage-1  1/14] FROM docker.io/library/ubuntu:20.04@sha256:874aca52f79ae5f8258faff03e10ce99ae836f6e7d2df  0.0s
 => [internal] load build context                                                                            45.0s
 => => transferring context: 662.31MB                                                                        44.4s
 => [caddybuilder 1/2] FROM docker.io/library/caddy:builder-alpine@sha256:d801a9cb39c58bd783848058affb9eaa6  16.2s
 => => resolve docker.io/library/caddy:builder-alpine@sha256:d801a9cb39c58bd783848058affb9eaa64c7c08e6db239a  0.0s
 => => sha256:a4c1c7ee20762a65dff2197ead8c8d5393fdaa1edfc57fdbddbef13593f13898 5.04kB / 5.04kB                0.0s
 => => sha256:c5342516f2484c34a836a7a863eb81f3105c46c1073d5369d8d555cd3886bf21 173B / 173B                    0.4s
 => => sha256:081870b0a3a575371a47514a1587d72b3ed20393e0b814e018af644ae02d4354 64.11MB / 64.11MB              4.7s
 => => sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B                      0.3s
 => => sha256:d801a9cb39c58bd783848058affb9eaa64c7c08e6db239a79377d6be098b0e42 7.83kB / 7.83kB                0.0s
 => => sha256:304d65fa80a604d16734f10f7b24cb5fe411e2544902073681e3b77a964a57b4 2.69kB / 2.69kB                0.0s
 => => sha256:65bba47559bb65192116ff634bc5d776d7e73d55d8ba3412a36c9b1c5d3a69cf 5.06MB / 5.06MB                2.2s
 => => sha256:96bcd29e26ec8031e395a727e3070ee0e25bc834f8111c18581618663f06ea58 1.30MB / 1.30MB                1.8s
 => => sha256:4fc1a630d1ff6c946122bf9031b5ab2bca9106fb7f496df07006c352720c0a9c 406B / 406B                    2.0s
 => => extracting sha256:081870b0a3a575371a47514a1587d72b3ed20393e0b814e018af644ae02d4354                     8.9s
 => => extracting sha256:c5342516f2484c34a836a7a863eb81f3105c46c1073d5369d8d555cd3886bf21                     0.0s
 => => extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1                     0.0s
 => => extracting sha256:65bba47559bb65192116ff634bc5d776d7e73d55d8ba3412a36c9b1c5d3a69cf                     0.6s
 => => extracting sha256:96bcd29e26ec8031e395a727e3070ee0e25bc834f8111c18581618663f06ea58                     0.3s
 => => extracting sha256:4fc1a630d1ff6c946122bf9031b5ab2bca9106fb7f496df07006c352720c0a9c                     0.0s
 => ERROR [caddybuilder 2/2] RUN xcaddy build   --with github.com/mholt/caddy-ratelimit                      28.8s
------
 > [caddybuilder 2/2] RUN xcaddy build   --with github.com/mholt/caddy-ratelimit:
1.044 2024/05/13 23:21:21 [INFO] absolute output file path: /usr/bin/caddy
1.047 2024/05/13 23:21:21 [INFO] Temporary folder: /tmp/buildenv_2024-05-13-2321.1582549832
1.047 2024/05/13 23:21:21 [INFO] Writing main module: /tmp/buildenv_2024-05-13-2321.1582549832/main.go
1.047 package main
1.047
1.047 import (
1.047 	caddycmd "github.com/caddyserver/caddy/v2/cmd"
1.047
1.047 	// plug in Caddy modules here
1.047 	_ "github.com/caddyserver/caddy/v2/modules/standard"
1.047 	_ "github.com/mholt/caddy-ratelimit"
1.047 )
1.047
1.047 func main() {
1.047 	caddycmd.Main()
1.047 }
1.048 2024/05/13 23:21:21 [INFO] Initializing Go module
1.049 2024/05/13 23:21:21 [INFO] exec (timeout=0s): /usr/local/go/bin/go mod init caddy
1.061 go: creating new go.mod: module caddy
1.064 go: to add module requirements and sums:
1.064 	go mod tidy
1.078 2024/05/13 23:21:21 [INFO] Pinning versions
1.078 2024/05/13 23:21:21 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.7.6
2.877 go: downloading github.com/caddyserver/caddy/v2 v2.7.6
5.231 go: downloading github.com/caddyserver/certmagic v0.20.0
5.372 go: downloading github.com/google/uuid v1.3.1
5.508 go: downloading github.com/prometheus/client_golang v1.15.1
5.850 go: downloading github.com/quic-go/quic-go v0.40.0
6.620 go: downloading go.uber.org/zap v1.25.0
6.920 go: downloading golang.org/x/sys v0.14.0
8.036 go: downloading golang.org/x/term v0.13.0
8.783 go: downloading github.com/klauspost/cpuid/v2 v2.2.5
8.920 go: downloading github.com/libdns/libdns v0.2.1
9.014 go: downloading github.com/mholt/acmez v1.2.0
9.132 go: downloading github.com/miekg/dns v1.1.55
9.335 go: downloading github.com/zeebo/blake3 v0.2.3
9.467 go: downloading golang.org/x/crypto v0.14.0
10.09 go: downloading golang.org/x/net v0.17.0
11.26 go: downloading github.com/beorn7/perks v1.0.1
11.35 go: downloading github.com/cespare/xxhash/v2 v2.2.0
11.48 go: downloading github.com/cespare/xxhash v1.1.0
11.60 go: downloading github.com/prometheus/client_model v0.4.0
11.68 go: downloading github.com/prometheus/common v0.42.0
11.99 go: downloading github.com/prometheus/procfs v0.9.0
12.26 go: downloading google.golang.org/protobuf v1.31.0
13.26 go: downloading github.com/onsi/ginkgo/v2 v2.9.5
14.00 go: downloading go.uber.org/mock v0.3.0
14.22 go: downloading golang.org/x/exp v0.0.0-20230310171629-522b1b587ee0
14.63 go: downloading github.com/quic-go/qpack v0.4.0
14.86 go: downloading go.uber.org/multierr v1.11.0
15.17 go: downloading golang.org/x/tools v0.10.0
17.14 go: downloading golang.org/x/text v0.13.0
21.69 go: downloading github.com/golang/protobuf v1.5.3
21.92 go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
22.10 go: downloading golang.org/x/mod v0.11.0
22.43 go: downloading github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
22.52 go: downloading github.com/quic-go/qtls-go1-20 v0.4.1
22.91 go: downloading github.com/google/pprof v0.0.0-20210720184732-4bb14d4b1be1
27.37 go: added github.com/beorn7/perks v1.0.1
27.37 go: added github.com/caddyserver/caddy/v2 v2.7.6
27.37 go: added github.com/caddyserver/certmagic v0.20.0
27.37 go: added github.com/cespare/xxhash/v2 v2.2.0
27.37 go: added github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
27.37 go: added github.com/golang/protobuf v1.5.3
27.37 go: added github.com/google/pprof v0.0.0-20210720184732-4bb14d4b1be1
27.37 go: added github.com/google/uuid v1.3.1
27.37 go: added github.com/klauspost/cpuid/v2 v2.2.5
27.37 go: added github.com/libdns/libdns v0.2.1
27.37 go: added github.com/matttproud/golang_protobuf_extensions v1.0.4
27.37 go: added github.com/mholt/acmez v1.2.0
27.37 go: added github.com/miekg/dns v1.1.55
27.37 go: added github.com/onsi/ginkgo/v2 v2.9.5
27.37 go: added github.com/prometheus/client_golang v1.15.1
27.37 go: added github.com/prometheus/client_model v0.4.0
27.37 go: added github.com/prometheus/common v0.42.0
27.37 go: added github.com/prometheus/procfs v0.9.0
27.37 go: added github.com/quic-go/qpack v0.4.0
27.37 go: added github.com/quic-go/qtls-go1-20 v0.4.1
27.37 go: added github.com/quic-go/quic-go v0.40.0
27.37 go: added github.com/zeebo/blake3 v0.2.3
27.37 go: added go.uber.org/mock v0.3.0
27.37 go: added go.uber.org/multierr v1.11.0
27.37 go: added go.uber.org/zap v1.25.0
27.37 go: added golang.org/x/crypto v0.14.0
27.37 go: added golang.org/x/exp v0.0.0-20230310171629-522b1b587ee0
27.37 go: added golang.org/x/mod v0.11.0
27.37 go: added golang.org/x/net v0.17.0
27.37 go: added golang.org/x/sys v0.14.0
27.37 go: added golang.org/x/term v0.13.0
27.37 go: added golang.org/x/text v0.13.0
27.37 go: added golang.org/x/tools v0.10.0
27.37 go: added google.golang.org/protobuf v1.31.0
27.38 2024/05/13 23:21:47 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/mholt/caddy-ratelimit github.com/caddyserver/caddy/v2@v2.7.6
27.76 go: downloading github.com/mholt/caddy-ratelimit v0.0.0-20240513211706-2d18cd2c76cc
27.84 go: github.com/mholt/caddy-ratelimit@v0.0.0-20240513211706-2d18cd2c76cc requires go >= 1.22.0 (running go 1.21.10; GOTOOLCHAIN=local)
27.85 2024/05/13 23:21:48 [FATAL] exit status 1
------
Dockerfile:3
--------------------
   2 |
   3 | >>> RUN xcaddy build \
   4 | >>>   --with github.com/mholt/caddy-ratelimit
   5 |
--------------------
ERROR: failed to solve: process "/bin/sh -c xcaddy build   --with github.com/mholt/caddy-ratelimit" did not complete successfully: exit code: 1

### Steps To Reproduce

Build dockerimage

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

latest

**Comment by anksingh-zuora** [comment]
Fixed by using `FROM caddy:2.8-builder-alpine AS caddybuilder`

**Comment by Nikhil-Nandagopal** [comment]
@anksingh-zuora glad you fixed it. I'm now closing this issue
