### ISSUE TITLE
[Bug]: Privacy policy and Terms and Conditions pages fonts are not updated.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Privacy policy and Terms and Conditions pages fonts are not updated.

### Steps To Reproduce

<img width="1425" alt="Screenshot 2024-05-14 at 12 38 11 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/5c80cbe2-36fd-4892-af40-e9d3d742aeea">
<img width="1101" alt="Screenshot 2024-05-14 at 1 18 32 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/8709d1de-4e44-4488-a904-409cd26a1190">

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by zoispyridi** [comment]
Hello, I am interested in picking up this issue as part of my first open source contribution. I am a student contributing as an assignment in university so any guidance as to where to start would be much appreciated. Thank you!

**Comment by rohan-arthur** [comment]
@zoispyridi thank you for your interest! You can check out the contribution guide here: https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md

**Comment by zoispyridi** [comment]
@rohan-arthur thank you for directing me to contribution guide!Could you please clarify the preferred font style to be used for the text content on these pages? Your guidance on this matter would greatly assist me in ensuring that the styling of these pages meets the project's requirements. Thank you!!
