### ISSUE TITLE
[Task] - New UI for overflow tabs

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#33432]
Design: https://app.zeplin.io/project/660e4f58a0437c27988148ee/screen/663e2c9e114e0421d24d08a1

**Comment by akshayvijayjain** [comment]
@albinAppsmith , can the design be made public?
we can pick it for development

**Comment by albinAppsmith** [comment]
@akshayvijayjain, Thank you for showing interest in this task. I have already picked it up, but I encourage you to explore other opportunities, such as the [Good First Issues](https://github.com/appsmithorg/appsmith/labels/Good%20First%20Issue).
