### ISSUE TITLE
[Feature] Checkbox Group Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3344]
# RACI matrix
| Label | Value | 
| ------------- | ------------- |
| Responsible | @jsartisan, @wmdev0808   |
| Accountable | @somangshu  |
| Consulted | @areyabhishek, @momcilo-appsmith   |
| Informed |  @Nikhil-Nandagopal |

# Objective

We need a checkbox group to allow users to easily configure multiple checkboxes together

# Success Metrics

| Goal  | Metric |
| ------------- | ------------- |
| Decrease the time needed to build a collection of checkbox operating as a unit  | Time that user spends creating a group of checkbox |

# Requirements

| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Add checkbox | Ability to add new checkbox & drag to reorder the sequence | High  | - |
| Display as a row | Ability to change the view of checkbox group as a row or column; Boolean/Toggle value | High  | - |
| All properties of checkbox | Inherit all the properties of checkbox widget for each row | High  | - |
| Internal property - `selectedValues` | API reference to get all selected values from the checkbox group  | High  | - |
| Action - `onCheckChanged` | API to trigger an action on check/uncheck of a checkbox inside the group | High  | - |

# Developer Handoff Document in Figma:

https://www.figma.com/file/u0IE1Vqr2MKcQcQKCpHO4O/Checkbox-Group-Widget?node-id=2%3A3

**Comment by somangshu** [comment]
@areyabhishek @momcilo-appsmith we will need designs here. Please check the scope above.

**Comment by momcilo-appsmith** [comment]
@somangshu I saw that Pawan has already started working on this.

**Comment by somangshu** [comment]
Hey @momcilo-appsmith, I updated the RACI above but forgot to tell you personally.
