### ISSUE TITLE
[Bug]: Fill type widget shows center alignment indicators

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fill type widget - radio group incorrectly shows center alignment indicator even though it never center aligns

### Steps To Reproduce

1. Add a button widget to a zone
2. attempt to add a radio group widget to the same zone and notice a center alignment indicator shows up 

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/27becef599404eb688a401b71717e786

### Version

cloud

**Comment by KelvinOm** [comment]
@tbrizitsky should we do something about this?

**Comment by tbrizitsky** [comment]
This looks like a recently introduced bug.
@KelvinOm could you estimate the task and see if we can address it in the upcoming sprints?
