### ISSUE TITLE
[Bug]: Checkbox widget does not show an asterisk to indicate it's a required

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Checkbox widget does not show an asterisk to indicate it's required but shows a validation highlight in 'red'

![image](https://github.com/appsmithorg/appsmith/assets/79509062/e8579cce-7a4c-41b5-9a86-eacc4e23237f)

### Steps To Reproduce

1. drop a checkbox and checkbox group widget on canvas
2. mark both of them `required` on the property pane
3. notice the checkbox group widget shows an asterisk and validation error in 'red' - but the checkbox widget does not display an asterisk

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by jsartisan** [comment]
@ichik Should we consider this as an issue? Not sure if it is wise to add asterik on a single checkbox widget. 🤔 What do you think?

**Comment by ichik** [comment]
@jsartisan I think it's valid, e.g. something like “accept terms and conditions” checkbox.
