### ISSUE TITLE
[Task] Module reusability - Deprecate Private Query / JS section

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#33458]
- Add button icon: When a JS Module with private entities is opened, the section of Queries/JS is still visible but without the “Add” button icon.   
- Callout: The Main JS File should show a callout with information that the experience was improved and other modules could be accessed directly. All the other private entities of the JS Module shouldn’t show the callout when opened.
- Learn more link: Should redirect to a new documentation page that will explain how to reference other modules from a module (this should be aligned with @harshilp24 so that the learn more link is included when this documentation page is available)

[Figma design](https://www.figma.com/design/Z0QsSdGOydURn6WIMQ3rHM/Appsmith-Reusability?node-id=6164-44487&t=c5TZdTASX6hlGs9c-4)

[Draft pull request of prototype](https://github.com/appsmithorg/appsmith-ee/pull/4526)

**Comment by SunnyTitus** [comment]
Hi @ashit-rath, can you please provide additional details for this ticket? Maybe a short description or screenshots?
