### ISSUE TITLE
[Task]: Create Knowledge Base and Learnings document for Caching Tenant Information implementation done in #33309

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#33452]
### SubTasks

Create Knowledge Base and Learnings document for Caching Tenant Information implementation done in [#33309](https://github.com/appsmithorg/appsmith/pull/33309). 
This will help in transferring knowledge to other members of the Integrations Pod.

**Comment by akshayvijayjain** [comment]
Hi @NilanshBansal ,

Please share if there is a format required for the resultant knowledge document, we are creating the document and would like to create in a form that conforms to appsmith's other knowledge document format

**Comment by akshayvijayjain** [comment]
seems like https://github.com/appsmithorg/appsmith/issues/33504

there was an issue with feature implemented. https://github.com/appsmithorg/appsmith/issues/33504

so this issue can also is blocked, until the feature is implemented again.
cc @NilanshBansal

**Comment by NilanshBansal** [comment]
Closing this issue as it would be demoed in Engineering Meetup for Integrations Pod. Will re-open if there's a need for this document.
