### ISSUE TITLE
[Task]: Refactor module instances across modules when source module's name is changed

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#33465]
### SubTasks

When the origin module name is changed, it should also refactor all the module instances of this type in other modules.

#### Example

Before changing the name of `QueryModule1`

```
QueryModule1

JSModule1
   func1
      return QueryModule1.run();

JSModule2
   func1
      return QueryModule1.run();


```

After changing the module name from `QueryModule1` to `QueryModuleNewName`
```
QueryModuleNewName

JSModule1
   func1
      return QueryModuleNewName.run();

JSModule2
   func1
      return QueryModuleNewName.run();


```

**Comment by Shazad-khan** [comment]
Can you help me with more information about it?

**Comment by ashit-rath** [comment]
Hello @Shazad-khan, this Github issue is representation of an internal task and meant for internal contributors only. If you are looking for contribution to Appsmith then please check this out [Code Contributions Guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md). If you need any other help, please do let me know
