### ISSUE TITLE
[Task]: Adjust onPageLoad logic w.r.t. module instances used inside modules

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#33466]
### Description

Currently, when a module consumes other modules, references to those nested modules are treated as module instances. These nested module instances are hidden from direct use by the consumer but are triggered internally whenever the outermost module references them.

To ensure consistency, if the outermost module is set to run on page load, all nested module instances it references should also be marked to run on page load automatically. This adjustment is necessary to maintain the expected behavior and ensure that all dependent modules initialize correctly when the page loads.

**Comment by Harshithazemoso** [comment]
Hello @subrata71 
We picked this issue, and our finding is that modules is available in business edition, 
so in current codebase we cannot fix anything about this issue.
Please confirm if our understanding is correct
@akshayvijayjain

**Comment by subrata71** [comment]
Thanks, @Harshithazemoso for showing interest in solving this issue. Yes, you are correct! `Modules` is available in the business edition only.

**Comment by subrata71** [comment]
Yes, that's correct. @akshayvijayjain
