### ISSUE TITLE
Bug: Resizing bug when side by side editor is enabled

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#33483]
Noticed a weird resizing bug when I have side by side enabled: <https://www.loom.com/share/d279d24aa3db4c4e9fd05b955e2e7998>
Not sure whom to tag.
<@U01MZDG0QTA> tagging you, since I saw some changes in `StickyCanvasArena.tsx` file.

[Slack Message](https://theappsmith.slack.com/archives/CPG2ZTXEY/p1715580392427459?thread_ts=1715580392.427459&cid=CPG2ZTXEY)

**Comment by alex-golovanov** [comment]
Seems that the video has been taken down <img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1VQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34cd5eb8c3e03e5e68a69a0287be8bac060c4a1c/image.png" alt="image.png" />

**Comment by rahulbarwal** [comment]
Hey @alex-golovanov , So sorry about this, I was doing a cleanup and unfortunately the above link is unrecoverable.
Fortunately [this message](https://theappsmith.slack.com/archives/C02RCR2PURZ/p1715337585336189?thread_ts=1714543659.414419&cid=C02RCR2PURZ) also talks about it.
In this video Arpit talks about 2 issues:

1. Canvas not getting updating on page switch.
2. gap between explrorer and canvas. (this is the issue that I've reported here)

**Comment by rahulbarwal** [comment]
@alex-golovanov One more screenshot to help you see the issue. This happens intermittently but notice space between canvas and other sides.
![Screenshot 2024-06-27 at 7 08 32 PM](https://github.com/appsmithorg/appsmith/assets/6761673/19f4733c-e0c5-4ce9-b073-27003e616207)
