### ISSUE TITLE
[Task]: Invalid Tenant Cache should not bring the instance down - [Stability]

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#33504]
### SubTasks

The instance is heavily dependent on the tenants response in the consolidated API to work. 
Recently we saw an occurrence when the release was down because of a serialization error in the tenant cache. https://theappsmith.slack.com/archives/CGBPVEJ5C/p1715747695304469

The system should be fault-tolerant and be able to auto-heal in such scenarios. If the redis cache is invalid or if serializing from redis has an issue, the code should default to querying the database and return response.

**Comment by NilanshBansal** [comment]
Not required now as the [change](https://github.com/appsmithorg/appsmith/pull/33512) is reverted.

**Comment by NilanshBansal** [comment]
Re-opening as we may implement this again by handling GAC permissions.
Ref: https://theappsmith.slack.com/archives/C02K2MZERSL/p1715847322614589?thread_ts=1715829340.668969&cid=C02K2MZERSL

**Comment by AdeshAtole** [comment]
Hi @NilanshBansal , I would like to see what went wrong during deserialization / serialization and would also like to fix the root cause. I am part of the community discord server, if you want to connect there. I can look at this if no one else is.

**Comment by NilanshBansal** [comment]
Implemented in this commit https://github.com/appsmithorg/appsmith/pull/33641/commits/d11d404f3c06109859282601d7bfed4f8feb1922.
The PR is in draft state as there should be test cases and a counterpart EE PR to complete the functionality of implementing tenant caching
