### ISSUE TITLE
[Feature]: setSelectedOption() should trigger "on option change" in widget

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#33500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A select widget can be set to trigger a function if the selected option changes.

setSelectedOption() is a function of that widget that can change the selected option.

Using the setter function bypasses the on option change trigger.

While this could be useful to have a way to override the user's selection, it is not very logical when building the app that you need to reproduce the on option change logic everywhere you use a setter function.

Perhaps a second parameter could be added, boolean (optional, default false to make this backwards compatible), if true triggers the on option change event.

### Why should this be worked on?

Make logical chains of actions consistent and prevent from having to duplicate the logic multiple places in the UI.

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS event triggers are only for user interactions and not for system changes to data. If we were to trigger this for this case, it would create a cascading effect to also trigger it when the default selected option changed.
This is similar to this feature request #4490 and we'll consider it in the future
