### ISSUE TITLE
[Bug]: An empty `Connect Datasource` modal is seen on trying to fork a template onto some specific workspaces

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#33514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

An empty `Connect Datasource` modal is seen on trying to fork a template onto some workspaces. This issue is seen only on specific workspaces

Ideal behaviour: Data should've been populated automatically. In case of templates that need DS credentials, fields to enter the credentials should've been seen

@rahulbarwal @AnaghHegde Invited you folks to the workspace named May 14th where this issue is seen 

### Steps To Reproduce

1. Create a workspace
2. Fork a template
3. Notice that one some workspaces, the data doesnt get populated and an empty `Connect datasource` modal is seen

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/be6bc7639290480d971bc333f396102c

### Version

Appsmith v1.25.0

**Comment by rahulbarwal** [comment]
@laveena-en It seems that somehow this datasource is incorrectly configured in the workspace. 
1. we can fix it by adding correct  password and all of the errors will go away.
2. Before that, I want you to test this in other workspaces, old and new both - want to know in what conditions we land up in this state.

**Comment by rahulbarwal** [comment]
>With respect to 1., even though it was a wrong password for the Maintenance.. template, shouldn’t building blocks be created successfully since they don’t depend on user input for credentials?

@laveena-en Correct, building blocks should come with their own creds. But in this case I am assuming the workspace already had a datasource with the same name as one in BBs and the code assumed not to configure the new one. 
@AnaghHegde feel free to correct me.

**Comment by laveena-en** [comment]
Issue was resolved post adding the right credentials for datasources. Closing this issue.
