### ISSUE TITLE
[Bug]: When a widget is hidden a blank space is shown where the widget is shown instead of the UI not auto adjusting.

### ISSUE THREAD

**Issue by naveenthontepu** [appsmithorg/appsmith#33519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a widget is hidden a blank space is shown where the widget is shown instead of the UI not auto adjusting.

### Steps To Reproduce

1. Put 2 tables in a page 1 bellow the other.
2. Hide the top table.
3. The 2nd second table does not come up instead stays at the bottom.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self Hosted.

**Comment by Nikhil-Nandagopal** [comment]
@naveenthontepu the UI will auto adjust if you set the above widget or parent container to auto-height. We're also working on a new UI building to solve this so I'm closing this issue.
