### ISSUE TITLE
[Bug]: The entity explorer pane UI seems to be broken 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#33522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The entity explorer pane UI seems to be broken 
![image](https://github.com/appsmithorg/appsmith/assets/45958978/125d91a1-c89b-41af-9b82-7ae4d180d683)
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/d3f9d035-637d-4a0b-ba44-d28ac974c926">

Elements that are not present in the implementation, 
- [ ] Search bar
- [ ] the divider between existing and new datasources 
- [ ] and the absence of Load more option in case of more than 5 datasource

### Steps To Reproduce

1. go to edit mode of application 
2. add a new datasource
3. now try to create anew query from entity explorer pane
4. The UI doesn't match with the figma

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

v1.9.25

**Comment by rohan-arthur** [comment]
we have added these states now
![Screenshot 2024-07-30 at 12 26 53](https://github.com/user-attachments/assets/91fa3d93-4dee-4c88-834c-519d30f09c6e)
