### ISSUE TITLE
[Bug]: The custom widget Icon seems to be broken when user search for a widgets in widgets section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#33523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The custom widget Icon seems to be broken when user search for a widgets in widgets section
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/a8051be4-94d3-4486-9387-11f4a954ade3">

### Steps To Reproduce

1. go to edit mode of the application
2. In the entity explorer section click on UI tab
3. search for the widget name which is not present
4. The custom widget icon will be displayed but seems like broken as in attached screenshot

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

v1.25

**Comment by raza001** [comment]
#33535
