### ISSUE TITLE
[Bug]: Button widget overflows from the canvas even on preview mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Button widget overflows from canvas boundary even on preview mode as seen in the image

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/2437ba4d-ef26-4b05-9132-5fc342c34c4c)

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by raza001** [comment]
Pls Attach **video** if possible  @ramsaptami
