### ISSUE TITLE
[Epic] Form Widget

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3353]

**Comment by hawisizu** [comment]
I would want to implement something to alert users before changing page with unsaved changes. But to do that I am missing a feature on the form widget: a properties that would be like `form_1.has_changes` , that would be true if any of the fields has been manually changed after loading its default value.

**Comment by somangshu** [comment]
@hawisizu thanks great input, We will definitely discuss this and take it up soon.
