### ISSUE TITLE
[Bug]: Horizontal Scroll Bar in Table Widget Gone

### ISSUE THREAD

**Issue by sjr267** [appsmithorg/appsmith#33557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a table widget with more columns than will fit across the screen at once. In the past, there was a horizontal scroll bar at the bottom of the table that could be used to move the view to these columns, but this disappeared after yesterday's update. The only way I've found to scroll to these invisible columns is with the center wheel/button of the mouse.

### Steps To Reproduce

In the editor, I can only get the horizontal scroll bar to appear in the table widget for a wide table if the table is the height of an integer number of rows. When I turn on cell wrapping and the rows become different heights based on the content, the horizontal scroll bar disappears because the table is no longer the height of an integer number of rows. 

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/4d80b47b1fd645ed80a7a8afe355aaee?sid=3a2c1df5-e647-4805-b952-e1029a570867

### Version

Self hosted CE v1.25

**Comment by bejenaru** [comment]
on [Cloud](https://app.appsmith.com) same issue

**Comment by sjr267** [comment]
Just discovered that this issue affects the vertical scroll bars as well. https://www.loom.com/share/5772acb273634974ac2a610f17c4233a?sid=ca1a14b4-07e0-49f7-ac05-5867d24c5032

**Comment by ame-appsmith** [comment]
[Another user](https://discord.com/channels/725602949748752515/1241178156401033407) reported this bug.

**Comment by Nikhil-Nandagopal** [comment]
@bejenaru @sjr267 we have a preview of the fix here
https://ce-33806.dp.appsmith.com

Can you try it out and let us know if it solves the problem? You will need to create a new account on the URL I shared as it's a completely separate instance

**Comment by bejenaru** [comment]
Hi @Nikhil-Nandagopal
It is working ok on this instance!
 
![image](https://github.com/appsmithorg/appsmith/assets/5692150/fa13f6e9-bcb8-476a-a6eb-469676239def)

**Comment by Nikhil-Nandagopal** [comment]
@bejenaru glad to hear it, the fix should be merged in soon
