### ISSUE TITLE
[Feature] Progress Bar widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3356]
## Summary

Users need a widget to display the progress of a long-running task

## Figma Design Links:
[Icon Design](https://www.figma.com/file/ATfTB5F9Q7ZiI0yYckuXW7/Deprecated-Design-System?node-id=172%3A5437)
[Widget Design](https://www.figma.com/file/mxIUUL3LM363xWInQnhjDW/New-Widgets-Exploration?node-id=44%3A3054)

**Comment by areyabhishek** [comment]
This is already an issue in #2519

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek I need to reopen this because it's an individual piece of work. So estimating and prioritizing needs to happen on this task while referencing details from there. Ideally, we should keep issues related to a single piece of work

**Comment by somangshu** [comment]
@Nikhil-Nandagopal is [this](https://ant.design/components/progress/#header) or [this](https://material-ui.com/components/progress/#linear-determinate) an apt example for this?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu yes they are

**Comment by sbalaji1192** [comment]
@techbhavin here is the Figma link for progress bar widget https://www.figma.com/file/mxIUUL3LM363xWInQnhjDW/New-Widgets-Exploration?node-id=44%3A3054

**Comment by riodeuno** [comment]
Feature requirements
---
Using the progress bar Appsmith developers should be able to:
- Set the progress bar to be indeterminate in progress, signifies that some process is running, whose progress cannot be determined.
- Set the value dynamically by binding a "progress" property
- Set the fill colour of the progress bar.
- Set the label to be visible or invisible, depending on whether they want a textual value displayed for the progress.

Other details
- Value should be in percentage. Hence, it should be validated to have a number value between 0 and 100.

The progress bar is for display purposes only, as a result it may not have any action triggers at the moment. This is open for discussion if we have a valid use-case.
