### ISSUE TITLE
[Feature] Rate Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3357]
## Summary
Users need a widget to display and capture ratings

**Comment by jsartisan** [comment]
Here is the design spec file - https://www.figma.com/file/XSywzAyFni1tS4s73XclwC/Rate-Widget?node-id=121%3A330

**Comment by somangshu** [comment]
Note: 

- Max Count: The maximum value / number of stars possible for the input
- Default value: The default value which the widget loads with (number of filled stars)
- Active color: The color used for filled stars / selected value 
- Inactive color: The color used for unfilled stars / unselected value
- Tooltips: This is an array of string which will be matched to the index of each star for showing a tooltip/message. If the star index does not exist in the tooltip array then no message will be shown. 
- Size: the size of each rating icon, There will be 3 variations - Small, Medium, Large
- Allow half: This allows 0.5 precision on the value. The widget will allow user to select half stars when this is enabled
- Visible: This property shows / hides the widget. This can function based on a JS expression as well
- Disabled: This will not let the user interact with the widget. We show the not allowed cursor pointer on mouse hover. The value will still be accessible but cannot be updated
- Actions: As seen in other widgets, the rating widget will have a set of action which can be performed `onChange` of value.
- The rating widget API will have the value property which can be used anywhere in the app ex: `rating.value` will be equal to selected value.

**Comment by areyabhishek** [comment]
Got a comment from a discord user who wants the option to use other symbols for the rating widget. 
<img width="783" alt="Screen Shot 2021-07-17 at 4 48 15 PM" src="https://user-images.githubusercontent.com/30255708/126035231-796ddee9-1c3e-4ad5-b9f4-a437bb775c40.png">

**Comment by somangshu** [comment]
Having other icons in the rate widget does make sense with a limited set.

However I suggest the progress bar widget remain separate.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu Actually custom images are pretty common for rate widget implementations. They generally ask for a full image, half image, and empty image and use that. Ex. eatfit has smiley faces for rating while swiggy has stars

**Comment by somangshu** [comment]
@Nikhil-Nandagopal what you are referring to is a custom implementation involving animations. As far as I understand having a font/icon is common. I have not really seen `images` in any implementations. ([ref1](https://material-ui.com/components/rating/#rating), [ref2](https://ant.design/components/rate)). I have also observed separate separate icons for each rate count.
