### ISSUE TITLE
[Bug]: Execute API not working in view mode

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#33651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When an application is created using partial import export and deployed, some of the queries are not working in deployed mode. 

For more details check: https://theappsmith.slack.com/archives/CNQ9Q91C0/p1715948138327279

https://github.com/appsmithorg/appsmith/assets/30018882/22ca7f47-d44f-4b9a-ad5b-1e629195fc9d

The APIs for which we get error are not getting published for some reason

### Steps To Reproduce

1. Use partial import export to create application
2. Deploy the app
3. Observe certain APIs failing

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud - v1.25

**Comment by tomjose92** [comment]
Here are the steps to reproduce the issue.

1. I created a basic App and added few widgets connected to a query called `fetch_users`
2. Then I partial exported all the widgets and queries of the Page
3. In the exported JSON file, I see name and fullyQualifiedName of the query to have the value `fetch_users`
4. Next step I imported this to another App and renamed the query from fetch_users to `get_all_users`

After this change, in edit mode its working fine. But in deployed mode I get an error stating that `get_all_users` is not defined

When I export the new App and check its JSON, i see that its name is set as get_all_users but the fullyQualifiedName is still set as the old value, ie fetch_users.
