### ISSUE TITLE
[Bug]: Drop indicator displays lines that does not support movement

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Drop indicator displays lines that does not support movement

### Steps To Reproduce

1. Create multiple zones with buttons widget placed next to each other
2. Confirm the widgets are on new lines
3. Try moving the button widgets using the lines that appear right next to the widget as seen in the video
4. Observe that the widget does not move at the required spot as seen in the video

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/219aea28862a4341bb1b19edaf49656f

### Version

cloud

**Comment by marks0351** [comment]
@ramsaptami from the loom I can observe that things are operating as expected however the UX is confusing,
button looks to be on a new line because it has been wrapped in its alignment.

**Comment by ramsaptami** [comment]
doesn't make sense cause on the UI we're showing lines to drop the widget but only place the widget there when we pick a position much further from the first line

**Comment by KelvinOm** [comment]
@tbrizitsky we really need you input here.

**Comment by tbrizitsky** [comment]
It's a known limitation of the system. Let's close/deprioritize it for now.
