### ISSUE TITLE
[Bug]: GraphQL query editor: Headers tab is the default one after a reload

### ISSUE THREAD

**Issue by danguilherme** [appsmithorg/appsmith#33695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The GraphQL query editor differs from other editors as its default tab is the "Body" tab, instead of the "Headers" tab.
After reloading the page while in the GraphQL editor, the "Headers" tab is selected instead of the "Body" tab.

### Steps To Reproduce

In an existing application:
1. Create a new GraphQL query
2. Reload the page

https://github.com/appsmithorg/appsmith/assets/1488378/c731efa6-2d7d-4605-97df-9cf249bfc7f9

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud - Appsmith v1.27.0-SNAPSHOT

**Comment by AmanAgarwal041** [comment]
Moving it back to papercuts as it already has a pr attached to it.
