### ISSUE TITLE
[Bug]: On deleting a generated page [with data], git connected app shows git status as datasource removed. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I delete a CRUD page from a git connected app, the git status shows up with datasource removed [along with other components.]. However, datasource is workspace level, and it does not actually get removed. Hence this is incorrect. 

### Steps To Reproduce

1. Create a git connected app. Create a branch
2. Create a CRUD page with an S3 datasource
3. Delete this page
4. Click on commit
5. Note the modal that comes up shows that S3 datasource has been deleted
6. However, the datasource is actually not deleted. 
This message is misleading, as, on deleting a page from an application, the datasource does not get deleted as datasources are workspace level. 

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/4ebfdee8-128c-4948-b18f-7701e25accad

### Version

Cloud

**Comment by nidhi-nair** [comment]
This is expected Aparna, while the workspace may still have the datasource, from the perspective of the app, the datasource is no longer required. So in the committed version of the app, the datasource would be expected to be deleted.
