### ISSUE TITLE
[Bug]: Connect data button is active on preview mode and triggers property pane pop-up

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Connect data button on a table is active on preview mode and triggers property pane pop-up

![image](https://github.com/appsmithorg/appsmith/assets/79509062/7e09a1df-c535-405b-bd0a-87cb24a42dce)

### Steps To Reproduce

1. Drop a table on the canvas
2. Go to preview mode and click on 'Connect data' button
3. Notice the property pane pop-up show on preview mode

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by jsartisan** [comment]
@ichik Should we show empty table in this case?

**Comment by ichik** [comment]
@jsartisan yes.

**Comment by KelvinOm** [comment]
Let's do this instead 
https://app.zenhub.com/workspaces/project-anvil-6434e3402be2c1002ea740be/issues/gh/appsmithorg/appsmith/33388
