### ISSUE TITLE
[Bug]: Fixed layout widgets can be pasted on Anvil apps; albeit with compatibility issues

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fixed layout widgets can be pasted on Anvil apps; albeit with compatibility issues

![image](https://github.com/appsmithorg/appsmith/assets/79509062/eced72cf-f4ce-4b6b-929d-7e2057e989ba)

### Steps To Reproduce

1. Open a fixed layout app
2. Copy a few widgets
3. Open an Anvil app
4. Paste the widgets 

observe the widgets can be pasted but with errors in them

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by jsartisan** [comment]
What is the expected UX for this? @KelvinOm @ichik

**Comment by KelvinOm** [comment]
> What is the expected UX for this? @KelvinOm @ichik

We plan to prevent the copying of widgets from different systems.

https://www.notion.so/appsmith/Anvil-Beta-Release-Phase-I-Exploration-e35a5f316ee34a068406db12c03abd89#288038915a324151923ac5272924f425
