### ISSUE TITLE
[Bug]: Template thumbnails are broken

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#33736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Templates thumbnails are broken on release

### Steps To Reproduce

1. Click on templates on the homepage
2. Notice that most of the thumbnails are broken
![image](https://github.com/appsmithorg/appsmith/assets/109572422/2f1ec13c-1456-4a49-9278-9a080013e1e8)

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

Release

**Comment by jacquesikot** [comment]
The template images have been replaced with images from Contentful.
