### ISSUE TITLE
[Bug]  The failed runs tab also show successful runs

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#33745]
The failed runs tab also show successful runs. See the end of video below.

**Comment by srix** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33745?planning-poker) with Zenhub @ayushpahwa @nsarupr

**Comment by nsarupr** [comment]
The `Failed Runs` tab is showing the successful runs because the client is sending the `status=FAILED_RUNS` but rts is expecting `status'FAILED`. Due to this, the RTS is sending the all the successful runs in the request.
