### ISSUE TITLE
[Bug]: Admin emails configured from docker file is not able to access Admin Settings

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#33741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I as an administrator of my instance, had forgotten the password of my email id. And sadly I hadnt configured the email settings on my instance yet. So I signed up with a different user account, and from the docker file I had updated the APPSMITH_ADMIN_EMAILS to include the new email account as well.

On refreshing the instance, I logged in as the new user, but I am not able to see the admin settings.

Much later, i finally got hold of the password of the original administrator account. And when I logged in and went to administrator settings, I am able to see the second user's email account in the list of Admins.
But that user is still not able to see Admin settings when logged into.

Attached screenshots below, of the instance after updating the email id in the docker file.

<img width="724" alt="Screenshot 2024-05-27 at 11 45 10 AM" src="https://github.com/appsmithorg/appsmith/assets/5265702/c7c3dc90-905e-4e23-bdfc-0eea4957ceee">
<img width="502" alt="Screenshot 2024-05-27 at 11 45 23 AM" src="https://github.com/appsmithorg/appsmith/assets/5265702/d8cc2153-017c-454b-b4e2-9f410e26289e">

### Steps To Reproduce

1. Edit stacks/configuration/docker.env file, and add another email id to the environment variable APPSMITH_ADMIN_EMAILS
2. Restart the instance
3. Sign up/Login as the user
4. The user will not be able to see the Admin settings

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Self Hosted 1.26

**Comment by nsarupr** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33741?planning-poker) with Zenhub @ayushpahwa

**Comment by riteshkew** [comment]
need to prioritise

**Comment by trishaanand** [comment]
Not able to reproduce this issue.

**Comment by trishaanand** [comment]
This issue is only reproducible on EE and not on CE. Re-opening this.
