### ISSUE TITLE
[Bug]: Unable to see the horizontal scrollbar at times when there are multiple columns inside a Table widget

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#33746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a table with multiple columns. But the horizontal scrollbar doesn't show up at times for me to realise that there are more columns. I am still able to scroll horizontally using my mouse trackpad but the scrollbar is not visible.

A user initially noticed that whenever he searches for something thats not present in the table, Empty table shows up and along with it the horizontal scrollbar disappears.

I tested the same, and also tried introduced another table having lesser records than the table size. In this scenario as well the horizontal scrollbar is not showing up.

I understood the issue to be that even if I have multiple columns in a table, the horizontal scrollbar does not show up, unless the vertical scrollbar is also present. That is, if there are multiple records in the table for me to scroll then only the horizontal scrollbar is seen.

Attached both screenshots below of 
1. When horizontal scroll bar is not visible with lesser records
<img width="810" alt="Screenshot 2024-05-27 at 12 01 13 PM" src="https://github.com/appsmithorg/appsmith/assets/5265702/0cf80c08-3f39-446e-8c06-975d041ec49b">
2. Horizontal scrollbar is visible only when there are more records and the vertical scrollbar is also visible.
<img width="649" alt="Screenshot 2024-05-27 at 12 03 41 PM" src="https://github.com/appsmithorg/appsmith/assets/5265702/77146c42-8022-448d-81da-b14d7012082b">

### Steps To Reproduce

1. Introduce a Table having multiple columns
2. Have only fewer records compared to the total Table size.
3. Now notice that the horizontal scrollbar is not visible to scroll from.

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Self Hosted - 1.26

**Comment by Nikhil-Nandagopal** [comment]
@ankitakinger

**Comment by ankitakinger** [comment]
@riteshkew Could you check this out please?
