### ISSUE TITLE
[Bug]: First time on logging in to airgapped - error pops up - We couldn't connect to our servers. Please check your internet connection

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

First time on logging in to an airgapped image, we get an error message - We couldn't connect to our servers. Please check your internet connection

### Steps To Reproduce

Slack [thread](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1716184774075049)

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Airgap

**Comment by riteshkew** [comment]
Not reproducible in the latest version v1.44
