### ISSUE TITLE
[Bug]: Issues with importing apps in airgap version

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#33779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Some apps are not getting imported at all and we are seeing the below error.
App: 
[OldApp_DSTesting1.9.24_Latest.json](https://github.com/appsmithorg/appsmith/files/15464564/OldApp_DSTesting1.9.24_Latest.json)

https://github.com/appsmithorg/appsmith/assets/39921438/ca36ee56-e6d9-409f-b83f-98b5bfbb18f7

2. Other apps are getting imported but we see blank toasts & some connectivity errors.
App: 
[Automation test cases - recent edit.json](https://github.com/appsmithorg/appsmith/files/15464570/Automation.test.cases.-.recent.edit.json)

https://github.com/appsmithorg/appsmith/assets/39921438/d70c595c-f783-4908-a99f-ad97e4189bc0

### Steps To Reproduce

1. In the airgap version try importing an app

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Airgap

**Comment by shadabbuchh** [comment]
Reducing the priority. For more reference: https://theappsmith.slack.com/archives/CTHN8GX5Y/p1716956857466309?thread_ts=1716875929.473809&cid=CTHN8GX5Y

**Comment by riteshkew** [comment]
specific to this app that has saas plugins. Airgap doesn't;t support, so closing this.
