### ISSUE TITLE
[Bug]: Unable to view entire table. Missing vertical scrollbar when cell wrapping enabled

### ISSUE THREAD

**Issue by ryanjj509** [appsmithorg/appsmith#33774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After the latest update, when there is a table with cell wrapping enabled, we do not always see the full contents as we can not scroll to view the rest.

### Steps To Reproduce

Add table with large amount of data in a column, turn on text wrapping

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self Hosted v1.26

**Comment by Nikhil-Nandagopal** [comment]
@ryanjj509 can you share a screenshot of this?

**Comment by ryanjj509** [comment]
![chrome_upXDOctw9u](https://github.com/appsmithorg/appsmith/assets/87915795/702a5895-0b93-4fbd-8bc3-89a813ffb3b8)

In this screenshot, there is a table with four rows. Three of the rows have wrapping text in the third column. The wrapping text causes us not to be able to see the fourth row. The delete button is slightly visible but we can't get down there. We've had to disable cell wrapping for the time being.

**Comment by Nikhil-Nandagopal** [comment]
@ryanjj509 we have a preview of the fix here
https://ce-33806.dp.appsmith.com/

Can you try it out and let us know if it solves the problem? You will need to create a new account on the URL I shared as it's a completely separate instance

**Comment by ryanjj509** [comment]
@Nikhil-Nandagopal  Yes, it does.
