### ISSUE TITLE
[Bug]: Validation of Column during Inline editing inside a Table widget does not work properly

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#33789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am using Inline Editing inside a Table and I wanted to do some validations during column edits.
I am using currentRow.columnName as the input value to validate. I realised that even if the validation fails while I am typing the value the first time, I am still able to click outside the cell and click on Save.
Only when I edit it again does the error message pop up.

I tried the same when adding a new row and this issue does not occur. I see the error message while typing itself if the validation fails.

### Steps To Reproduce

1. Introduce a Table widget and connect to some data
2. Make one of the columns editable
3. Inside the column, give an expression for the validation field. Something as simple as
{{currentRow.<columnName>.length > 3}}
4. Now edit that particular column of any row in the table.
5. Purposefully type in a value that fails the validation you have set

Notice that on the first time you edit the row with the wrong value, no error message shows up and you are able to click outside the cell to go ahead and click Save button.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/abc1cb8ad63e449295f644c8e8901411?sid=35c6422c-9b93-4363-841a-fdf7df3d6f78

### Version

Cloud/Self Hosted 1.26

**Comment by rahulbarwal** [comment]
@tomjose92 
This isn't working because `currentRow` property that is available in autocomplete always points to unedited values. We also have another argument: `editedValue` available that you can use to validate upon. 

Let me know if this works out as a solution for you or if you have any more questions.

**Comment by rahulbarwal** [comment]
Closing this, based on above comment. @harshilp24 to ensure that our documentation is updated with required information.
