### ISSUE TITLE
[Epic] Server-side Workflows

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3378]
## Problem statement

Allow users to create workflows

**Comment by filipesmedeiros** [comment]
Hey! Not trying to rush anything (thanks for all your amazing work), but just curious about the status of this?

**Comment by Nikhil-Nandagopal** [comment]
@filipesmedeiros we're currently shipping out a beta of this feature. I'm closing this issue since we're tracking this here #1950
