### ISSUE TITLE
[Feature]: Fix typos in Publish-helm-chart.md: depencies -> dependencies

### ISSUE THREAD

**Issue by hydrationn** [appsmithorg/appsmith#33795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This PR corrects typos in the Publish-helm-chart.md file.

Changes made:
- Line 12: Corrected "depencies" to "dependencies".
- Line 79: Corrected "depencies" to "dependencies".

### Why should this be worked on?

These changes help improve the readability and accuracy of the documentation.

**Comment by hydrationn** [comment]
Could you please merge my PR? Thank you!

**Comment by Nikhil-Nandagopal** [comment]
@hydrationn can you link your PR here

**Comment by hydrationn** [comment]
I'm sorry for the delay. Here is the link. Thank you!
https://github.com/appsmithorg/appsmith/pull/33889
