### ISSUE TITLE
[Bug]: If we click on the commit icon of a github connected app on airgapped, the app crashes. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a git connected app connecting to a github repository [connected with internet], then go offline and click on the commit button - the app crashes.
Expected behavior - app should not crash - this scenario should be handled gracefully

### Steps To Reproduce

1. Create an app on airgapped
2. Go online
3. Connect to git hub repository
4. Now go offline
5. Open the above app
6. Click on the commit button
App crashes.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Airgapped

**Comment by btsgh** [comment]
https://github.com/appsmithorg/appsmith/assets/101863839/4ecae023-c635-4027-9158-f0e40dd1f709

**Comment by VigneswarV** [comment]
I have Fixed and created a PR for this 
https://github.com/appsmithorg/appsmith/pull/34673

**Comment by akshayvijayjain** [comment]
@brayn003 @btsgh Please help with reviewer for the pr https://github.com/appsmithorg/appsmith/pull/34673

**Comment by btsgh** [comment]
@brayn003 / @nidhi-nair  bumping it up to your notice - this is a high priority issue logged for air-gapped and looks like the external contributor has raised a pr for this and is looking for review.
