### ISSUE TITLE
[Bug]: query response counts error as one record

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#33813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Tested with mongo and postgres, and I think this may apply to all plugins. 
When there is an error, the response shows as `Result: 1 Record`, it should be shown as `Result: Error`
<img width="581" alt="Screenshot 2024-05-29 at 12 21 01" src="https://github.com/appsmithorg/appsmith/assets/94514895/4ba4c368-586b-4cd2-a472-1371d1a14cbb">

### Steps To Reproduce

1. Create a valid postgresql datasource
2. run a valid select query and see that the results are showing the correct record count
3. run an obviously invalid query that should generate an error in the response. In this case, see that the records count is wrongly shown as 1

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by raushan3737** [comment]
Hi @rohan-arthur , @Nikhil-Nandagopal : I am picking up this issue.

**Comment by daaliachhak17** [comment]
created issue on Jira-https://zemoso.atlassian.net/browse/TNOSB-400
