### ISSUE TITLE
[Bug]: UI consistency is missing in the Edit datasource page

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I traverse between different datasources in the Edit mode, the bottom division ui is not consistent across all datasources

### Steps To Reproduce

1. Create many datasources in an application
2. Go the edit option of each datasource and observe the ui consistency in the bottom section where the test / save / cancel buttons are present. 

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://jam.dev/c/9ced90bc-e23c-426a-8075-352b3940ca87

### Version

Cloud

**Comment by AmanAgarwal041** [comment]
Similar Ui inconsistency for reconnect modal : https://github.com/appsmithorg/appsmith/issues/33970
