### ISSUE TITLE
[Bug]: Firefox issues on anvil app

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Firefox issues on anvil app

![image](https://github.com/appsmithorg/appsmith/assets/79509062/0f24bc02-8f60-45ff-b4fe-2988a764b518)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/e6ac3133-21c8-4f92-886c-3546b1996f26)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/fde4c712-5ee1-44f8-935c-28811a1c0c0b)
https://www.loom.com/share/57e6f7f8937a4334ba1f92e583dbc1d6

### Steps To Reproduce

1. Open an anvil app on firefox ([link](https://ce-28238.dp.appsmith.com/app/sample/single-widget-in-a-zone-663cb1459ac8920a5c72ea2e))
2. Observe the checkboxes and switch widget boxes being off it's center and flicker when zooming into the app

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by ramsaptami** [comment]
@ichik some more accessibility issues to investigate
also, to note, firefox is not frequently used by our end users based on data that was collected a few months ago

**Comment by ichik** [comment]
@ramsaptami is this on Windows? I can't reproduce this in FF on Mac and Linux.

@KelvinOm @jsartisan can you take a look?
