### ISSUE TITLE
[Bug]: Merging [fetch status/check mergeability and merge actions] error with timeout out 3 out of 5 times on the dp

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Merge operations like fetch status/check mergeability and merge actions error with timeout out 3 out of 5 times on the dp

### Steps To Reproduce
**Fetch Status:**
<img width="1423" alt="504Timeout_Mergingchanges_Getsstuckthere" src="https://github.com/appsmithorg/appsmith/assets/101863839/c3629e3e-4f5b-40ca-af25-60ce9aaf0fd3">

**Merge:**
<img width="1353" alt="504Timeout_MergeabilityCheck_Seenmultipletimes" src="https://github.com/appsmithorg/appsmith/assets/101863839/531473ee-e08a-47c5-b866-db21df7ad5d9">

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Cloud DP

**Comment by btsgh** [comment]
The json export of the git connected apps where the issue was faced:

[BugVerifcations (2).json](https://github.com/user-attachments/files/15510866/BugVerifcations.2.json)
[31jandpromo.json](https://github.com/user-attachments/files/15510868/31jandpromo.json)

**Comment by btsgh** [comment]
I still see the issue during merge. Attaching latest video recording. Merge does not complete and gives a 504 gateway timeout error in network tab

https://github.com/appsmithorg/appsmith/assets/101863839/c2f764e1-ddf0-4889-82f2-a1a8e7c32b7b

@sondermanish

**Comment by btsgh** [comment]
Seeing merge issue on release-ee as well. Getting stuck on the merge screen, not everytime, but intermittently reproducible

https://jam.dev/c/fee2c7a2-53f0-445f-b7f7-a09f5fdb44cf

**Comment by btsgh** [comment]
Marking this as medium as this is seen once in 4/5 times.

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by btsgh** [comment]
@sondermanish - checked this on the CR dp, which also has the above changes as discussed with you - did not see the check mergeability or status fetch or merge action erroring out. Closing out this issue.
