### ISSUE TITLE
Design inconsistencies in pass test payload section of the response pane

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#33876]
- The input is missing label `data` .
- Spacing between the subtext and the input is incorrect.
- Spacing between the input payload and run CTA’s are not as per design.

<img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7238910a4773aa93da81b298d6c7cd1e6ee4e87/Untitled.png" alt="Untitled.png" />

- The lighting menu indicator is not required here. This input cannot be used to bind anything.

<img width="382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekFvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4398203778c6c7bef282636b6c6df953ec0ba90c/Untitled%20%282%29.png" alt="Untitled (2).png" />

**Comment by parth-appsmith** [comment]
@ayushpahwa as discussed, creating a separate ticket to track the error and warning state for test payload input.

**Comment by ayushpahwa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/33876?planning-poker) with Zenhub @nsarupr @srix

**Comment by ayushpahwa** [comment]
Stop cta is not integrated at the moment. I am moving that as a separate task.
