### ISSUE TITLE
[Bug] - Test run goes into a zombie state during a long loop execution

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#33882]
`for(var i =0; i < 10000; i++){
			console.log(i, " : run");
			let data = random_fact.run();
			console.log(i," : ",data.content)
		}`

When this code is executed the test run goes into a zombie state and after execution started for workflow log the polling just keeps loading without new logs appearing. 

<img width="924" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f11064248201701c3e9ed144cd73d840b246b225/Screenshot%202024-05-31%20at%2010.51.53%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 10.51.53 AM.png" />

If I reduce the for loop to run 100 times then the rest of the logs are visible.

**Comment by nsarupr** [comment]
The issue arises due to a restriction on the number of activities that can be executed on Temporal.
![image](https://github.com/user-attachments/assets/486e13ae-dc4b-4c25-8183-eca393912aae)

**Comment by nsarupr** [comment]
[Slack conversation](https://theappsmith.slack.com/archives/C05QG0J87UL/p1722590027840959)
