### ISSUE TITLE
The execution should stop after encountering the first error. 

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#33881]
**Ideal behaviour**
During execution once an error is encountered the workflow should terminate the execution and fail the run.

Current state
<img width="959" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFVvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e461a0a72af79a0d29025379e42fb74e6d65b30/Untitled%20%288%29.png" alt="Untitled (8).png" />

**Comment by nsarupr** [comment]
The workflow execution fails now, when an error is encountered when executing a query.
