### ISSUE TITLE
[Bug]: Publish-package fails with `resource not found` exception

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#33890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user has an application with two packages containing datasource queries. They develop the app and packages on a staging instance, and 'update' their other instance once the functionality has been accepted on this instance. They update the other instance by 'exporting' the 'updated' staging instance application and 'importing' this JSON file in the other instance application. When they then publish the packages on that other instance, they get a 'Resource not found' error banner with the following response:

```
{ "responseMeta": { "status": 404, "success": false, "error": { "code": "AE-ACL-4004", "title": "INTERNAL_ERROR", "message": "Unable to find applicationId APPLICATION_ID. Either the asset doesn't exist or you don't have required permissions", "errorType": "No resource found or permission denied" } }, "errorDisplay": "AE-ACL-4004: Unable to find applicationId APPLICATION_ID. Either the asset doesn't exist or you don't have required permissions" }
```
Also, the issue seems to be intermittent. Sometimes when they update, the connection/relation is not screwed up, and publishing the packages works as expected.

https://theappsmith.slack.com/archives/C0341RERY4R/p1716988963393449

### Steps To Reproduce

Hard to reproduce but it's failing in the update layout call due to a non-existing application.It's hard

### Environment

Production

### Severity

None

### Issue video log

https://www.youtube.com/watch?v=IBmzMHUmRtM

### Version

Self Hosted

**Comment by Peterkrol12** [comment]
This issue happened to us, support suggested to create a new workspace and import the applications there. While this solution worked, both parties agreed this was a temporary work around. Eventually after diagnosing the problem, support came back with the note that the publish of the packages was successful, even though an erroneous message was shown. I checked and I can confirm that the publish of the package does succeed, but the error banner persists.

**Comment by subrata71** [comment]
@ Peterkrol12 Thank you for confirming the latter finding is working for you. We are working to find the root cause of this issue and will devise a systemic fix for the same. Thanks again for being with us!
