### ISSUE TITLE
[Bug]: DB icons not visible on template cards

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#33914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are not able to see different DB icons on template cards while trying to import them.

### Steps To Reproduce

1. Go to a workspace.
2. Try to fork a template.

**Expected:** The database icons should be visible on the template cards

### Environment

Release

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by zoispyridi** [comment]
Hello, I am interested in picking up this issue as part of my first open source contribution. I am a student contributing as an assignment in university so any guidance as to where to start would be much appreciated. Thank you!

**Comment by zoispyridi** [comment]
After reviewing and testing the template cards, I found that the database icons are correctly displayed for the majority of the templates. Specifically, each template that has an associated database properly shows its corresponding icon.

**Comment by rahulbarwal** [comment]
@zoispyridi, we really appreciate your interest in addressing this issue. However, we must handle this internally as it concerns our [release env](https://release.appsmith.com). We appreciate your understanding.
@jacquesikot, please take care of uploading the correct icons.

**Comment by jacquesikot** [comment]
This was a data issue. The templates on release have been updated to have their correct datasource in release.
