### ISSUE TITLE
[Bug]: Git Auto commit issues on Git lab and bit bucket

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#33919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

issues observed in Git lab and bit bucket

1. The auto commit bar is too fast for a medium sized app
2. The uncommitted changes is displayed in the app when there are any edits done in the original app and committed it
3. The Git lock error is displayed when the app is imported
4. The protected branch is not retained and the auto commit runs on that branch

![image](https://github.com/appsmithorg/appsmith/assets/45958978/4b11c6d2-a955-49f2-8b3b-49857a928fc5)
![image](https://github.com/appsmithorg/appsmith/assets/45958978/ca15a0c7-c9e7-4ee5-a205-70882d77b5a8)

### Steps To Reproduce

1. go to https://ee-4305.dp.appsmith.com/
2. import a app from git lab 
3. the app should have a protected branch the default branch other than main and some newly added commits
4. When the app is imported 
5. The user doesn't see auto commit bar
6. The protected branch no more a protected branch
7. Git file lock error is displayed on app import
8. Some uncommitted changed related to query is displayed

Note : Import the below json app connect it to git and try the above steps or use this git hub link for importing git@gitlab.com:raksha7/all-templates.git
[Untitled application 1 (22).json](https://github.com/user-attachments/files/15531041/Untitled.application.1.22.json)

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud-dp

**Comment by btsgh** [comment]
Not seen any of these issues on release. Hence closing this out.
