### ISSUE TITLE
[Bug]: Input widget should add a scroll when text gets longer rather than increasing the widget size

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When input widget is set to multiline and input text starts to occupy more space than available, then the widget should add a scroll to handle the text overflow rather than increase the size of the widget

### Steps To Reproduce

1. Set input widget to multiline
2. Drop/add a long text until the widget starts to expand
3. Keep adding text and notice the section height has increased causing an unsavory UI layout

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/f18b85c7f3c4456784aecadd37a71696

### Version

cloud

**Comment by KelvinOm** [comment]
@ichik should we add max-height for multiline input?

**Comment by ichik** [comment]
@KelvinOm TBH that seems like something that should be controlled by builders. For dense UI max-height should be default.
