### ISSUE TITLE
[Bug]: Remove changing country code on phone and currency widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Remove changing country code on phone and currency widget since this option does not work

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/bdfbc405-34a2-4ae1-b717-01d2a0e7fcc2)

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by razelos** [comment]
Hey, I'm interested in picking up this issue if it's available!

**Comment by razelos** [comment]
After looking into this issue, the option to change country code works fine on my version both for the phone and the currency widget. This issue should be closed.
