### ISSUE TITLE
[Bug]: Inline widget takes up vertical display type when it can no longer fit in a zone width which does not make sense

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Inline widget takes up vertical display type when it can no longer fit in a zone width which does not make sense

### Steps To Reproduce

![image](https://github.com/appsmithorg/appsmith/assets/79509062/1fd00cef-119a-4a32-9b79-dd2cbe81cfd3)

1. Drop an inline button widget on a wide zone
2. Keep adding buttons until you see the widget change it's orientation to vertical

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by ahmadmangla** [comment]
Hi, I can fix it. Can you assign this to me?

**Comment by KelvinOm** [comment]
@ramsaptami This is the expected behavior.  cc @tbrizitsky

**Comment by ramsaptami** [comment]
@tbrizitsky we'll need to pick this up as a polish item since the behavior is unusual and needs to be addressed

**Comment by tbrizitsky** [comment]
That's an expected behavior.
We might tweak a few things in the future, but that's exactly how the widget was designed to work.
