### ISSUE TITLE
[Bug]: Cannot scroll when menu button options are open

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cannot scroll when a menu button's options are open on canvas

### Steps To Reproduce

1. Drop a number of widgets on canvas to get a scroll - including a menu button widget
2. Go to preview mode
3. Open the menu options
4. Try to scroll on canvas and observe

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by KelvinOm** [comment]
This is by design. You need to click somewhere to close the popover. This is how Spectrum works and there is no setting to change it. 

cc @ichik
