### ISSUE TITLE
[Bug]: One uncommitted change is displayed in the Old git connected app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#33944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

One uncommitted change is displayed in the Old git connected app
![image](https://github.com/appsmithorg/appsmith/assets/45958978/4d619da7-eaf9-4bac-ae66-905c9f0a670c)
https://release.app.appsmith.com/app/oldapp-dstesting1-9-24/oauth20-656581cd7fe4812e226c61a7?branch=aparnatomerge

### Steps To Reproduce

1. go to release.app.appsmith.com
2. Open the app https://release.app.appsmith.com/app/oldapp-dstesting1-9-24/oauth20-656581cd7fe4812e226c61a7?branch=aparnatomerge
3. You can see the 1 uncommited change in the branch master  this change is related to application setting which we have not changed
4. and also we have created a new branch jun4th test where we don't see the uncommitted change

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

release v1.27

**Comment by btsgh** [comment]
Difference that is causing this commit to appear: 
<img width="1413" alt="Screenshot 2024-06-04 at 11 23 36 AM" src="https://github.com/appsmithorg/appsmith/assets/101863839/d5496c26-22b8-40df-8c1a-603bc2396422">

**Comment by RakshaKShetty** [comment]
This issue is fixed
