### ISSUE TITLE
[Bug]: On git importing an app having protected branch set, the setting is not retained

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I git import an application with a protected branch set from within appsmith, the protected branch setting is not retained, and also auto-commit runs on that branch.

### Steps To Reproduce

In a git connected application on release, set a protected branch
Now, git import this application on the DP
Note that the protected branch setting is not retained, and also auto-commit runs on that branch.

Found while testing [this](https://www.notion.so/appsmith/Git-test-bed-71152f655776475b95b3641ef0d7f428?pvs=4#4742261deaf94f0697538633cc2da98c) scenario on imported apps.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by sondermanish** [comment]
This is not a PR blocker as this is by design.

**Comment by sondermanish** [comment]
We are moving away from automatic protection any ways. the designs will change

**Comment by btsgh** [comment]
As per this [thread](https://theappsmith.slack.com/archives/C04HERDNZPA/p1717500152274179?thread_ts=1717143808.455439&cid=C04HERDNZPA), reopening the issue, as the behavior is not as per user expectation. However, not treating it as a PR Blocker.

**Comment by sondermanish** [comment]
This indeed is an issue with git itself, however this part of changes is not in scope of the current autocommit feature branch PR.
