### ISSUE TITLE
[Bug]: Default branch modified in the repo is not reflected in the application on the DP

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#33969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the default branch to something other than master or what is set in the app, even on syncing the branch, I do not see the default branch reflecting in the app. It still points to the old default. 

### Steps To Reproduce

https://jam.dev/c/b150f8e5-985b-41c5-bd64-3ced91707998

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Cloud DP

**Comment by sondermanish** [comment]
This is a feature on EE branch, if you follow the steps on internal and release, both would give different results.
This has been done intentionally in EE to allow users to switch their default branches in EE itself.

**Comment by sondermanish** [comment]
@btsgh it's not a PR blocker, let's consider closing it?

**Comment by btsgh** [comment]
Yes - closing as the DP is on an EE branch. The behavior is similar to as seen on release-ee.
