### ISSUE TITLE
[Bug]: The instance goes down when user merge the themes to master branch

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#33963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The instance goes down when user merge the themes to master branch
![image](https://github.com/appsmithorg/appsmith/assets/45958978/789f5f01-c938-463d-be52-ff293e422504)

### Steps To Reproduce

1. go to https://ee-4305.dp.appsmith.com/
2. Connect a application to git
3. now create a new branch from master branch create. acrud page now happy a theme customize its colour
4. now commit 
5. now merge it master and switch to master branch  the application breaks with oops something went wrong message

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

DP

**Comment by RakshaKShetty** [comment]
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/0df504b1-9b9f-4bf6-b387-3bcb46bc5023">

**Comment by btsgh** [comment]
This issue does not occur on release-ee. Tried it on a few applications, by creating themes and commiting, merging and opening the master branch
