### ISSUE TITLE
Task: Tests for Copy Paste

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#33982]
Unit Tests: 
- Paste non modal widgets onto destined parent
  - paste into main canvas
  - paste into section
    - update space distribution of section after pasting
    - update zone count of section after pasting
  - paste into zone
- paste modal widgets only onto main canvas
- select newly copied widgets after paste and set url and history.
- Indetify destined parent based on widget selected.
  - main canvas is the destined parent if no widget is selected
  - copied widgets should have a higher hierarchy than the destined parent

**Comment by razelos** [comment]
Hey, I would love to help on this issue if it's available! Is there something specific I should look into? Thanks
