### ISSUE TITLE
[Bug]: Widget error states does not have different styles for different selection states

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Widget error states does not have different styles for different selection states

![image](https://github.com/appsmithorg/appsmith/assets/79509062/04b3b1e9-3124-4231-98d6-36582363e3e5)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/23a3ed9d-96d8-42fc-ac16-ec1a4b7d9527)

### Steps To Reproduce

1. Hover over a widget in error state
2. Select a widget in error state
3. Observe both states have the same design style

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by ramsaptami** [comment]
@tbrizitsky can we have designs for this so it can be part of widget polish?

**Comment by somangshu** [comment]
This is as per the design
