### ISSUE TITLE
[Bug]: Remove option to change country code on phone widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Continuation of https://github.com/appsmithorg/appsmith/issues/32031 since it was a partial fix
Remove option to change country code on phone input widget

### Steps To Reproduce

1. Drop a phone widget
2. Observe behaviour when 'allow currency change' toggle is modified

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by saiprabhu-dandanayak** [comment]
Hi **@ramsaptami , @Nikhil-Nandagopal** , i have raised a PR for this could you please assign a reviewer for this .
Thanks in advance.

**Comment by ramsaptami** [comment]
hey @saiprabhu-dandanayak, please take a look at issues marked '[Good first issue](https://github.com/appsmithorg/appsmith/labels/Good%20First%20Issue)' for your contribution. 
This issue is unfortunately related to a project that's still WIP so we wouldn't be able to take this PR forward

**Comment by ramsaptami** [comment]
field has been removed
