### ISSUE TITLE
[Epic] Table selectedRow and action trigger UX improvement

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3407]
- [x] #6636
- [x] #2444
- [x] #2313
- [ ] Some users use `TableName.selectedRow` to fetch some data in the row's onClick, this will fail if we stopPropagation. We need to migrated all references to the current table's `selectedRow` to `currentRow`, for this to not fail existing applications.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal here is what we have thought: 
- Clicking on a table row action should not un-select, however, it should select
- Un-selecting a table row should call the `onRowUnselected` trigger (we do not want to mix this with the onRowSelected action as it will fail many use cases, Ex opening a form/modal when a row is selected)
- When onRowSelected is called, a new object called triggerRow is available for bindings within onRowSelected trigger (Do we also need the property to be bindable outside the table widget ex: `{{Table1.triggeredRow}}`)
- We can unselect a row by clicking it again

**Comment by Nikhil-Nandagopal** [comment]
@somangshu we should think about re-designing the action selectors soon. Too many action selectors make the property pane un-readable and most aren't used.
The rest look good. Good solve for selecting the row but not unselecting it when a button is clicked

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal We'll be picking up property pane redesign project with @aakashDesign very soon. We'll do a Figma style property pane

**Comment by somangshu** [comment]
@vicky-primathon Note:

1. The triggered row(s) selection will only lead to onRowSelected
2. onClick of the row action button should not select the row and only set a new property called as triggered row
3. Inside column property, Migrate all selected rows to currentRow in the button onClick Action
