### ISSUE TITLE
[Task]: Tests for app theming

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34082]
### SubTasks

[tests](https://www.notion.so/appsmith/819689ccf69a490cbe36145acb50894c?v=1805e5aa2de2483e95eaddf582e471ec&p=bafaa589838c481fb08efa3e5b34bb6f&pm=s)

**Comment by somangshu** [comment]
@jsartisan who is reviewing this? where is the PR?

cc @KelvinOm

**Comment by KelvinOm** [comment]
@somangshu PR is [here](https://github.com/appsmithorg/appsmith/pull/34839). I need to fix conflicts and then I'll  merge it.
