### ISSUE TITLE
[Bug]: appsmith-ee helm chart does not allow for external postgresql keycloak db

### ISSUE THREAD

**Issue by dsanders1234** [appsmithorg/appsmith#34107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I disable postgres in helm values and set APPSMITH_KEYCLOAK_DB_DRIVER to postgresql, I get an error:

Helm install failed for release appsmith/appsmith with chart appsmith@3.1.0: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 18: mapping key "APPSMITH_KEYCLOAK_DB_DRIVER" already defined at line 17
  
  I believe this is because the config map template has:
  
  ```
  {{- if (eq "APPSMITH_KEYCLOAK_DB_DRIVER" $key) }}
  {{ $key }}: {{ $.Values.postgresql.enabled | ternary "postgresql" "h2" | quote }}
  {{- end }}
  ```

instead of:

```
  {{- if (eq "APPSMITH_KEYCLOAK_DB_DRIVER" $key)  ( not $value) }} 
  {{ $key }}: {{ $.Values.postgresql.enabled | ternary "postgresql" "h2" | quote }}
  {{- end }}
```

like the other entries.

### Steps To Reproduce

In the helm chart for appsmith-ee (v3.1.0), set this combination in the helm values.yaml:

```
postgresql:
    enabled: false
applicationConfig:
   APPSMITH_KEYCLOAK_DB_DRIVER: postgresql
```

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted on AWS EKS using appsmith-ee helm chart v3.1.0

**Comment by pratapaprasanna** [comment]
Hey @dsanders1234 Thanks for reporting this . We are fixing it in our new helm charts version 3.1.2
