### ISSUE TITLE
[Bug]: appsmith-ee helm chart v3.1.0 ignores secretName setting in values.yaml

### ISSUE THREAD

**Issue by dsanders1234** [appsmithorg/appsmith#34109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We have an external secret that contains applicationConfig settings that ultimately come from an "aws secrets store csi driver."  We rely on being able to get these settings into the environment from this secret.  We are aware that this helm chart supports other config options such as "externalSecret" and "secret," but these options either rely on another external secret operator or embedding secrets in the values.yaml.  Neither of those solutions are good solutions for us.  This secretName setting in values.yaml works in the community version of the helm chart, and it does exist in the default values.yaml of the appsmith-ee chart v3.1.0, but it is not used in this ee version of the chart package for some reason.

The envFrom section of the Deployment.yaml in the helm chart templates should have (in addition to its current setup):
```
{{- if .Values.secretName }}
      - secretRef:
           name: {{ .Values.secretName }}
{{- end }}
```

### Steps To Reproduce

Try to use secretName: "my-secret" in the values.yaml and notice that the Deployment environment does not get updated.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted on AWS EKS using appsmith-ee helm chart v3.1.0

**Comment by pratapaprasanna** [comment]
hey @dsanders1234,
Thanks for reporting this.
we are looking into this and the next helm chart release will solve this
