### ISSUE TITLE
[Bug]: There is no existing way to remove scrollbar from Cell wrapping enabled table. 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#34149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 There is no way to remove scrollbar from Cell wrapping enabled table. 

### Steps To Reproduce

https://www.loom.com/share/0082da631d494a4195e7bd889b041bf6

1. bind table widget to any data 
2. Enable cell wrapping in any one cell which is overflowing 
3. increase the Size vertically of the widget such that the no of rows correctly fits in the table without overflowing
4. You will notice scroll bar is still there

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud/Selfhosted

**Comment by kamakshibhat-appsmith** [comment]
FYR : https://github.com/appsmithorg/appsmith/pull/33806#issuecomment-2139129709

**Comment by Nikhil-Nandagopal** [comment]
@kamakshibhat-appsmith we're ok with this behaviour and so we're not going to fix this and let it get fixed with Anvil. Closing this issue because of that
