### ISSUE TITLE
[Bug]: appsmith-ee helm v3.1.0 - Temporal relies on keycloak postgres database url having all information and does not allow @ symbol in password

### ISSUE THREAD

**Issue by dsanders1234** [appsmithorg/appsmith#34153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When setting up an external postgres database for keycloak, the helm chart expects separate APPSMITH_KEYCLOAK_DB_DRIVER, APPSMITH_KEYCLOAK_DB_USERNAME, APPSMITH_KEYCLOAK_DB_PASSWORD, APPSMITH_KEYCLOAK_DB_NAME and APPSMITH_KEYCLOAK_DB_URL, to build a final URL.  Temporal however expects the APPSMITH_KEYCLOAK_DB_URL to contain the username/password, etc.  Also, if the password contains an '@' symbol, the parsing fails.

### Steps To Reproduce

Setup appsmith-ee helm v3.1.0 with an external postgres KEYCLOAK database.  Set the various parameters.  Also try a full url that contains the username password in the url and add an @ symbol as the password.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted on AWS EKS using appsmith-ee helm chart v3.1.0

**Comment by nsarupr** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/34153?planning-poker) with Zenhub @ayushpahwa

**Comment by srix** [comment]
slack discussion relevant to this. https://theappsmith.slack.com/archives/C02MUD8DNUR/p1718966991612869

**Comment by ssichynskyi** [comment]
@srix so, what is the right format for `APPSMITH_KEYCLOAK_DB_URL` now? [Documentations](https://docs.appsmith.com/getting-started/setup/environment-variables#appsmith_keycloak_db_url) says: `jdbc:postgresql://<hostname>:<port>/<database_name>` but it doesn't seem to work.
