### ISSUE TITLE
[Bug]: Fetch CORS issue

### ISSUE THREAD

**Issue by gootik** [appsmithorg/appsmith#34152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I use fetch() on the client side it cannot load resources because of CORS issue.

### Steps To Reproduce

1. Go to Edit mode of any application
2. create a custom JS function
3. add a fetch operation like `await fetch('https://api.ipify.org?format=json')`
4. See that browser blocks call with "CORS Missing Allow Origin" error

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted - v1.27

**Comment by Nikhil-Nandagopal** [comment]
@gootik we'll look into this. In the meanwhile, you can hit that URL using the regular API query
<img width="952" alt="Screenshot 2024-06-11 at 12 48 49 PM" src="https://github.com/appsmithorg/appsmith/assets/3897254/b0d93264-2a06-4cfb-b2fd-7643b1f6feac">

**Comment by rishabhrathod01** [comment]
@gootik Could you please share the exact error you notice in the browser by sharing a screenshot of the same? 

Also, the implementation for extracting the JSON with a fetch for your case should be as shown below.

```
async myFun2 () {
	return await fetch('https://api.ipify.org?format=json').then(res => res.json())
}
```
