### ISSUE TITLE
[Bug]: The default branch in the release-ee instance remains unchanged when the user updates it from GitHub

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#34173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The default branch in the release-ee instance remains unchanged when the user updates it from GitHub
https://jam.dev/c/e4751bc9-46f6-4230-9417-8cff9f95c3f1

### Steps To Reproduce

1. Go to release-ee.app.appsmith.com
2. Connect a application to git
3. Now the master branch is a default branch 
4. Now create a branch out of it 
5. Now go to git hub repo got to setting tab, general change the default branch name from master to newly created branch
6. Now go to application in appsmith and do sync branch 
7. the new default branch will not be changed in  release-ee instance

Note: But in release instance the default branch will be changed to the newly assigned default branch

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

release. v1.27

**Comment by RakshaKShetty** [comment]
Also the other issue that needs to be taken care of here is When the user import the app from the GitHub The  name of the default branch will always be master which might be confusing for the users when they have changed it from there side

**Comment by AnnaHariprasad5123** [comment]
Hi @RakshaKShetty,

I have checked the issue in the re-release of Appsmith, and it works fine on my end. Could you please verify and let me know if it is fixed on your side as well?

Thank you!

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by nidhi-nair** [comment]
@RakshaKShetty this is as per expectation. In EE, the default branch functionality allows users to maintain a default branch per instance instead of relying on the remote default.
