### ISSUE TITLE
[Bug]: Zone cell is retained which causes double drop indicators to appear - on older app

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Zone cell is retained which causes double drop indicators to appear - on older app

### Steps To Reproduce

1. Navigate to [this](https://ce-28238.dp.appsmith.com/app/my-finances/page1-copy-66683e9ec357c2626ed0e6e4/edit/widgets/9h56m8tpfm/add) app
2. Add a widget below the stat box row
3. Delete the widget and try to drop a widget again 
4. Notice 2 drop indicators show up inside the zone

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/4313c9e52cfe4f3e8b9883a6a05fb015

### Version

cloud

**Comment by KelvinOm** [comment]
@riodeuno could you check it out? According to the description, it seems to be related to DSL.

**Comment by marks0351** [comment]
This is caused because we did not migrate older stats widgets widget_type property to the new type. so an entry is present on the dsl, however the widget factory does not know how to render the widget.
cc: @riodeuno @KelvinOm

**Comment by riodeuno** [comment]
The way to fix this cleanly is to migrate widgets if they are renamed.
Closing this for now.
