### ISSUE TITLE
[Feature] More Viewport options

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3419]
## Summary

We need different viewport options for the canvas.

## Motivation

When users are viewing apps in smaller viewports, they result in unexpected layouts. By restricting the responsive feature within an acceptable range, the layout is not effected, however there can be a horizontal scroll.

## Additional Context
- Let's reuse the icons for all mobile, tablet and desktop viewports
- Let's mention the min-max viewport width in the options

**Comment by Nikhil-Nandagopal** [comment]
Updating this after our conversation
We can have 4 classes of devices that scale between a range of widths
Desktop: 1224 - 1024
Tablet L: 1024 - 824
Tablet: 720 - 520
Phone: 420 - 340
Fluid: Any Width

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal I would suggest:
Desktop: Old - 1224, New 1160 - 1280
Tablet L: Old - NA, New 960 - 1080
Tablet: Old - 1024, New 650 - 800
Mobile: Old - 720, New 350 - 450

**Comment by sharat87** [comment]
The API should already be able to handle this change right? I don't see any backend changes needing here. Let me know if something comes up.

**Comment by sharat87** [comment]
@marks0351, this is done right? Can we close this?

**Comment by Nikhil-Nandagopal** [comment]
Yup closing this
