### ISSUE TITLE
[Bug]: Table widget's scroll disappears when it's zone background is turned off

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table widget's scroll disappears when it's zone background is turned off and returns when the table is interacted with

### Steps To Reproduce

1. Drop a table widget onto the canvas and connect to some data
2. Turn off it's zone's background and notice it's scroll disappear as seen in the video

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/5358dd51a2d84bd18016bb78a88e164b

### Version

cloud

**Comment by KelvinOm** [comment]
@ramsaptami Can't reproduce this even on Windows Chrome. Could you check this?

**Comment by ramsaptami** [comment]
this seems fixed too
