### ISSUE TITLE
[Bug]: Table Widget horizontal scrollbars not showing if vertical not triggered

### ISSUE THREAD

**Issue by Thossine** [appsmithorg/appsmith#34227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If a widget table haven't enough row to trigger the display of the vertical bar, the horizontal scrollbar never shows.
It assume that the table have enough columns to not fit in the actual view.

Once you add enough data to the table so it has enough rows to trigger the vertical scrollbar, then the horizontal scrollbar is shown too.

Also when there are to few rows, but enough to not fir verticaly, the bars not showing.
For instance, let's assume the current view can show 10 rows, if you have datas for 12 rows, the vertical scroll bar is not triggering. Once you'll have 12-13 + rows then the bars will start triggering.

If the user doesn't have a mouse with an horizontal scroll wheel, he can't scroll horizontaly unless he select a cell and use arrows on the keyboard ....

### Steps To Reproduce

1 - Add a widget Table
2 - make it tall enough that all data can be displayed in the current view
3 - Add enough columns so all columns cannot fit in the current view.
4 - Hover the table, no scrollbars showing
5 - Add enough datas to the table source so there are more rows than it can fit in the current view
6 - Hover the table, both horizontal and vertical scrollbars are now showing up

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://drive.google.com/file/d/1ECeUW5ciVGM9nS4lfn5Y9F7Sc1aK0lWO/view?usp=drive_link

### Version

Self Hosted v1.26

**Comment by Nikhil-Nandagopal** [comment]
@Thossine this issue was fixed in the latest release. Please update and let us know if you still face this issue
#33557

**Comment by Thossine** [comment]
> @Thossine this issue was fixed in the latest release. Please update and let us know if you still face this issue #33557

Hi, it solved 100% the issue !

Nice job , thanks
