### ISSUE TITLE
[Feature]: iframe reset Tabs navigation 

### ISSUE THREAD

**Issue by SauerWorkflow** [appsmithorg/appsmith#34232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi, 
I would like to know if there is the possibility to not refresh the iframe widget when it is present in a tab widget?
For example, in tab 1 I have an iframe widget that display the Appsmith 1 public application and on tab 2 I have another iframe widget that display the Appsmith 2 public application.
So if I'm on tab 1, I'm working on my Appsmith 1 public app, and on this app I'm opening a modal, for example. Then I open tab 2, accessing my Appsmith 2 public app. If I return to tab 1, the tab's content is refreshed. 

Is it possible to not refresh the content

Regards

### Why should this be worked on?

Do not reset the iframe widget when navigating a tab widget

**Comment by Nikhil-Nandagopal** [comment]
@SauerWorkflow we destroy all views on tab navigation to optimise the performance of the app. One solution to this would be to save the state of the iFrame using a URL variable or storeValue and then rehydrate that state when you navigate back to the tab
