### ISSUE TITLE
[Bug]: Date column set as required does not making it mandatory for adding new Table row

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#34258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user has a Table widget with a date column, and has enabled `Adding a row`. He has set the date column to be required.
But when adding a new row, and not giving any value to the Date column, he is still able to click on Save row button. And there is no error shown stating that the Date field is required.

### Steps To Reproduce

1. Drag and drop a table widget
2. Connect data to it and enable Add new Row
3. Configure one of the columns as Date column and set it as required
4. Try adding a new Row without setting value for the date column

You can see, the `Save row` is not disabled, even though I haven't given any value for the Date column which is set as required.

**Note**: This issue is not seen while editing a Table row as the error message is seen when no value is given.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by saiprabhu-dandanayak** [comment]
Hi **@pranavkanade** , could you please review this [PR](https://github.com/zemoso-int/appsmith-from-the-business/pull/88) , Let me know if any corrections or adjustments are needed.
