### ISSUE TITLE
[Feature]: Remove option to clear option when select widget is required

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#34262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Developers would like to enforce validation on select widgets to ensure that users cannot clear them

### Why should this be worked on?

It ensures that forms are submitted with valid information

**Comment by AnnaHariprasad5123** [comment]
Hi @Nikhil-Nandagopal, Can I work on this?

**Comment by AnnaHariprasad5123** [comment]
Hi @Nikhil-Nandagopal, 

The multi-select and multi-tree select widgets are highlighting in red when no values are selected and they are set as required."

![image](https://github.com/user-attachments/assets/0ace48d5-f854-44d2-b0d6-2fbfa33f803b)

Could you suggest a solution we could take for them?"

**Comment by rahulbarwal** [comment]
Closed with https://github.com/appsmithorg/appsmith/pull/35060
