### ISSUE TITLE
[Bug]: "temporal namespace is not created" message

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#34271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We observe in cicd we get "temporal namespace not created " message. Suscpicion is on the postgres starting too late.  

### Steps To Reproduce

* Start new selh hosted version 1.28 of EE
* create a new workflow project
* try to trigger workflow test run

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

selfhosted 1.28

**Comment by nsarupr** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/34271?planning-poker) with Zenhub @ayushpahwa

**Comment by srix** [comment]
unable to reproduce after multiple tries locally and remotely. so closing for now.
