### ISSUE TITLE
[Bug]: There appears to be a wrong spacing at the top of the JS Module editor view when the content inside editor goes below the fold

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#34275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There appears to be a wrong spacing at the top of the JS Module editor view when the content inside editor goes below the fold

### Steps To Reproduce

https://www.loom.com/share/d3b7e6edce7e4758a566b3998da8629d

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud/Selfhosted

**Comment by rohan-arthur** [comment]
@kamakshibhat-appsmith please share the DP link

**Comment by kamakshibhat-appsmith** [comment]
Hey @rohan-arthur , you can check this on prod/release.
