### ISSUE TITLE
[Bug]:  Test app not launching.

### ISSUE THREAD

**Issue by princepyhack** [appsmithorg/appsmith#34289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

One of my test app not launching but other one does.

### Steps To Reproduce

Launch the app from the app workspace. 

It might be specific to my app only. 

### Public Sample App

https://app.appsmith.com/app/bug-finder/page1-66702916305d964efdaed0ab/edit

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/a0f3ea525e484c2e8bdd9771bd7ac43f?sid=d707feef-6f3d-4228-9119-2f0050e7e8ac

### Version

Appsmith d9263ad5

**Comment by Nikhil-Nandagopal** [comment]
@princepyhack did you hit deploy inside the edit mode? It seems like that is the likely reason
