### ISSUE TITLE
[Bug]: Post refreshing my page after embedding video in my rich text widget , page keeps loading and video disappears.

### ISSUE THREAD

**Issue by princepyhack** [appsmithorg/appsmith#34288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Page keeps loading with multiple  console errors. 
2. Video disappears. 

### Steps To Reproduce

1. Drag rich text
2. Embed YouTube videos
3. Refresh the page and validate
4. Refresh again and validate. 

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/8d90ef5d2e2b49908ed32616716323ba?sid=aefacd5d-c638-4a4e-9a8f-2009de2d2ebf

### Version

Appsmith d9263ad5

**Comment by AnnaHariprasad5123** [comment]
Hi @princepyhack,

Did you check with other content instead of embedding YouTube in the text editor widget? In my observations, no widget is persisting the content that we provide.

**Comment by Nikhil-Nandagopal** [comment]
@AnnaHariprasad5123 @princepyhack you can set the default value in the widget if you want some content to be persisted by default. 
A widget will not persist the content input by a user by default. You need to persist it using the storeValue method if you want your end user inputs to be persisted.
