### ISSUE TITLE
[Feature] Tab widget should have navigation arrows when the tabs don't fit 

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3429]
## Summary

When a tab widget has many pages and not enough space to show all of them, there need to be arrows that allow the user to navigate the list and find the tab they need.
A search for tabs could be optional and useful too.

**Comment by momcilo-appsmith** [comment]
@vasanth-appsmith Can you leave the link to the design here?

**Comment by vasanth-appsmith** [comment]
@momcilo-appsmith 
Here is the design file for the tab widget 
[Figma](https://www.figma.com/file/8SXzt8gGPRi5nSU5gsE8J7/Tab-Widget?node-id=0%3A1)
