### ISSUE TITLE
[Feature]: Retry mechanism for SSO dance

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#34300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

During the SSO user login flow, there is a 500 error when appsmith triggers the callback URL with auth code from OIDC provider. Catch these exceptions and add retry mechanisms on such errors.

### Why should this be worked on?

These errors are quite common in cloud environments, especially in enterprise deployments.

**Comment by holylander** [comment]
looking forward to get this implemented. I have seen that auth0 oidc enpoints randomly resets the connection
