### ISSUE TITLE
[Bug]: Duplicate workspace in the workspace page

### ISSUE THREAD

**Issue by Shazad-khan** [appsmithorg/appsmith#34331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Navigate to [Appsmith](https://appsmith.z-apps.io/)
2. Enter {Username} and {Password}.
3. Click on the submit button.
4. You are on the workspace page.
5. Click on the {+} icon multiple times to create a workspace.
6. Rename all the workspace with the same {workspace name}

### Expected Result

The user should not be able to create duplicate workspaces and it should show a proper error message.

### Actual Result

The user is able to create duplicate workspace.

![image](https://github.com/appsmithorg/appsmith/assets/100838455/efb03998-a9d1-4eb2-9ff4-3c19eebeac87)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Release v1.28

**Comment by Nikhil-Nandagopal** [comment]
Sorry but this isn't a hard requirement. Workspace names do not need to be unique

**Comment by KrishnaSaiVadlamani** [comment]
Hi @Nikhil-Nandagopal ,

It is okay to have duplicate name, 

but there is a logic in frontend, that incrementally creates new names

for example: untitled workspace 1, untitled workspace 2, ....

but this logic also fails, when you hit new workspace button quickly, 

so I have added debounce to solve this problem

and in the rare case two users of same workspace from different tabs try to create new application, in then still you will see two "untitled workspace 3" as this is how the current logic it.


so to solve that issue, we are adding a 3 digit random string in the name to make it look like "untitled workspace 3-abd"


let us know your thoughts, here is the pr for the solution I am proposing
https://github.com/appsmithorg/appsmith/pull/34352

and this is the loom video 
https://www.loom.com/share/2d0fa9816e494d6aaa7c2ac243f796ec?sid=1349383e-f083-4d72-9a59-909ae75230e0

**Comment by Nikhil-Nandagopal** [comment]
@KrishnaSaiVadlamani I understand the problem but it's not a problem worth solving and it's overkill so we'll just ignore it for now.
