### ISSUE TITLE
[Bug]: Unable to Upload .SVG image for Logo in Branding

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#34330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to upload any .svg image in the **Logo** section of **Admin Settings** > **Branding**, an error that the file is in the incorrect format is displayed: `Uploaded file must be in .SVG, .PNG, and .JPG formats`. However, the .svg file is valid and this error gets displayed for any file in this format.

### Steps To Reproduce

1. Log in with an instance admin.
2. Go to **Admin Settings** > **Branding**.
3. Upload any .svg file in the **Logo** section.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.28

**Comment by Nikhil-Nandagopal** [comment]
Somangshu already filed this here so I'm marking this as a duplicate #34329
