### ISSUE TITLE
Create a working CRUD app with snowflake datasource with user/pw and with key pair auth

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#34342]
https://www.notion.so/Create-a-working-CRUD-app-with-snowflake-datasource-with-user-pw-and-with-key-pair-auth-21980e59b65d4ae1bc4a24851f9ee6da

**Comment by rishabhrathod01** [comment]
Application link - https://release.app.appsmith.com/app/untitled-application-1/page1-665fe30888a1c7442331441d
