### ISSUE TITLE
[Bug]: `currentRow` doesn't work correctly when the table is filtered

### ISSUE THREAD

**Issue by simonfvr** [appsmithorg/appsmith#34346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm computing the max value of a number column in a table. To compute this I'm using the `currentRow` value. When the table is filtered, e.g., sorting by any column or making a search, the `currentRow` value is incorrect, showing the data for the row that was in that index when the table was not filtered.

Seems that `currentRow` is computed using `currentIndex`over the full data, instead of over the filtered data.

Although I found this when setting the Max value for a column, this could be happening in other validation fields.

### Steps To Reproduce

1. Create a table and fill it with data.
2. Make the columns editables.
3. Create a JS object with a method to log the row passed as parameter.
4. Set this method to one of the columns in the max validation field passing the current row as parameter, `{{ js_object.method(currentRow) }}`.
5. Filter the table sorting by a column or searching anything.
6. Click on the column previously configured with the max validation field.
7. Check in the console that the value returned for the `currentRow` is incorrect.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Appsmith v1.28

**Comment by Naveen-Goud** [comment]
Hii @rahulbarwal ,
Can I work on this ticket?

**Comment by simonfvr** [comment]
Sure, thanks!

**Comment by simonfvr** [comment]
Yesterday I experienced an issue that probably is also related with this one:
- There's a table with data coming from a SQL query.
- This table is filtered and one row is selected.
- The data in this table is reloaded after performing a write SQL query (insert, update, delete).
- After this, the selected row changes, pointing to the index in the raw data, not in the filtered data.

I'll leave a video showing it.

Take into account that this doesn't happen when the read query is re-executed, only happens when a write query is executed (and this write query doesn't have to be related with the table).

**Comment by simonfvr** [comment]
https://github.com/appsmithorg/appsmith/assets/160487186/324080c2-67fd-4526-b71e-eee5d899ef77

### Video explanation
1. In the column "Invoice Number" appears the `currentIndex` for each row.
2. The row with `currentIndex = 1` is selected, and it's still selected after reloading the data.
3. The data is filtered, and now the `currentIndex = 1` is the first in the filtered data, let's say `currentFilteredIndex = 0`.
4. After reloading the data, everything is correct.
5. After performing a write query (delete data in a different table) the data is reloaded using exactly the same method as in step 4.
6. Now, `currentFilteredIndex = currentIndex = 1`, selecting the wrong row.

**Comment by SwilsonGC** [comment]
I've also had this issue, where a max value validation for a field within a table is dependent on another value in the same row, using  Max value = currentRow.columnName, where columnName contains an integer.  Filtering removes all validation, allowing any number to be input

**Comment by Naveen-Goud** [comment]
Hii @simonfvr @Nikhil-Nandagopal , I have worked on this ticket and identified that , we are loging it from the max in validation from propertypane. 
When I  logged the props in max function observed that its taking the table data directly with query.
Attaching  a screen shot below , you can have a look at it.

![Screenshot from 2024-07-22 10-06-21](https://github.com/user-attachments/assets/3db1f3d8-c16b-4540-9901-58720d82aa61)

in the above ss , in console logs, the table data is directly from the {{query1.data}}, but it should not take it directly.

to know clearly, I have modified the query and observes the ouput, it was working fine.

currently  figuring out . how can we pass the props currenlty so that the max in validation works properly by taking filtered data as well.

**Comment by simonfvr** [comment]
@Nikhil-Nandagopal hello, this error is still happening

https://github.com/appsmithorg/appsmith/issues/34346#issuecomment-2205827882
