### ISSUE TITLE
[Bug]: Intermittent issues seen with git actions - Discard & pull, pull from remote.

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#34360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Intermittent issues seen with git actions - Discard & pull, pull from remote.

### Steps To Reproduce

Issue 1: 
Uncommitted changes are seen even after discarding them.
Steps:
	1. Create a git connected app
	2. Add a few pages (Page1, Page 2) and commit them
	3. Add another page (Page 3) and discard and pull
	4. Notice that page 3 still remains in the app. However it does get removed post refreshing the page
	
Loom: https://www.loom.com/share/c71f31bd0d424df381f4454a8b86402e?sid=a8f075f5-3f89-4535-b1fd-0a6afaf4ea16
Repo: https://github.com/laveena-en/june20-ee

I created a branch called `test-bug` post this issue to help with debugging via the diff.

Issue 2:
Changes aren't seen on pulling remote changes.
Steps:
	1. Create a git connected app
	2. Add a few pages (Page1, Page 2) and commit them
	3. Delete one of the pages from the remote repo
	4. Pull changes on the app
	5. Notice that the changes don't reflect until the page is refreshed
Loom: https://www.loom.com/share/71c72615e7e6498fb1c18416743f0173
Repo: https://github.com/laveena-en/june20-ee

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.28

**Comment by btsgh** [comment]
Issue 3:
Though already committed, the pages show up as uncommitted, after discard and pull of a new page.
Steps:
1. Create a new app and connect it to git.
2. Note that Page1 already exists on the app.
3. Add a few pages (Page 2, Page3) and commit them
4. Now add Page4.
5. Click on the commit modal, and discard the changes.
6. Now note that though Page4 is discarded, Page 2 and Page 3 show up as changes to be commited, though they were already committed in step 3.
7. On committing again, the diff in repo shows up as below: 
<img width="1404" alt="Screenshot 2024-06-20 at 2 59 39 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/97701118-6265-4298-bc24-04e0cd487cdd">

The recording of the issue:
https://github.com/appsmithorg/appsmith/assets/101863839/63f2790e-50df-4f34-bd42-1335ac1a891e

**Comment by riteshkew** [comment]
Not reproducible as part of latest version.
