### ISSUE TITLE
[Bug]: Apps Breaking After Updating Appsmith due to Evaluation Issues in Widgets

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#34365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user has built an app on an old version of Appsmith and it was working fine in v1.9.12. However, after updating the instance to v1.27, they are facing the following abnormal widget behavior:
- All select widgets show errors and the evaluated value for the source data is empty. The issue gets fixed by deleting the source data and retyping it.
- In the Table widgets, the **Display text** of **URL** columns returns unexpected evaluated values. The issue gets fixed by deleting the **Display text** and retyping it.
This is an awful user experience and frustrating for the user because the existing apps are breaking after the update and all these widgets need to be adjusted manually again.

Tickerts:
- [Table widget](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=2204) 
- [Select widget](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=2203)
More details in [this slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1718865846780259).

### Steps To Reproduce

Update the Appsmith version from v1.9.12 to v1.27

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.27

**Comment by Nikhil-Nandagopal** [comment]
@carinanfonseca @somangshu what's the update with this issue?

**Comment by somangshu** [comment]
This was probably because of a large jump between versions. 

@vsvamsi1 what did you conclude here?

**Comment by vsvamsi1** [comment]
My apologies I have not gotten a chance to look into this. Since its only one reported incident and that user has been unblocked using a workaround([slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1718969449534449?thread_ts=1718865846.780259&cid=C0341RERY4R)), I think we can reduce priority of this issue now and once I have bandwidth I will look into debugging this.

**Comment by Nikhil-Nandagopal** [comment]
Ok lets close this then

**Comment by btsgh** [comment]
FYI - this was reproducible inhouse. Sharing the video here with steps on how I was able to reproduce this for records. https://jam.dev/c/02bf850a-d280-44d1-bc24-e9e17e4de3c8
