### ISSUE TITLE
[Epic] Collaboration

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3437]
## Problem statement

Internal tools involve multiple stakeholders including developers, business users, and product managers. All communication around the tool happens offline via other tools today. This leads to a lot of back and forth in the process of building the tool. Developers also have to help onboard new users and developers onto a tool.

# Objective
By introducing the collaboration feature we want to allow our users to easily communicate with each other right on the canvas.

# Success Metrics
| Goal  | Metric |
| ------------- | ------------- |
| Increase communication between team members on the platform  | Number of comments and conversations per team  |

# Assumptions
- Developers want to get feedback from their team members
- Other team members want to give feedback to the developers

# Requirements
| Requirement   | Importance | User Story | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Must be real-time | HIGH |
| Has to be very fast and responsive | HIGH |
| The user should be able to see everyone that is currently editing or viewing the app (like in Notion) | MEDIUM |
| The user has to have the ability to move everyone's comments around | MEDIUM |
| The user should have the ability to tag other people | HIGH |
| Every comment should have his own id, but replies shouldn't | HIGH |
| The user should have the ability to delete, edit or resolve a comment | HIGH |
| Resolved comments should be seen only when the user decides he wants to see them | HIGH |
| Resolved and unresolved comments should be separated in the "All comments" panel | HIGH |
| The user should be able to tell the difference between the resolved and unresolved comment both, on the canvas and inside of the "All comments" panel | HIGH |
| The user should be notified both on the platform and outside (email) if someone has commented on their work. | MEDIUM |
| The user should be able to react to other comments | LOW |

# Developer Handoff Document in Figma
[Link to the developer Handoff Document](https://www.figma.com/file/XSVhOqRy1W8VS8Cd5nhor9/Collaboration-feature-Tue-20-April-2021?node-id=2%3A1) 
[Email Tempaltes](https://www.figma.com/file/3IcOgXOZ5BmnM8WMjYmZEo/Collaboration-Email-Templates-Handoff?node-id=11%3A3) 

# Questions
| Question  | Answer | Date Answered |
| ------------- | ------------- | ------------- |
| How might we ensure that the comments panel doesn't cover up the UI | The comment section should be on the left side panel  | 19th April 2021  |

**Comment by momcilo-appsmith** [comment]
I updated the requirements to much the update.

**Comment by momcilo-appsmith** [comment]
I updated the requirements with the new designs that Emy made.
