### ISSUE TITLE
[Bug]: Performance Issues with Large Number of Components

### ISSUE THREAD

**Issue by zhouzhou19950825** [appsmithorg/appsmith#34376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello Appsmith team,

I'm experiencing significant performance issues when using a large number of components in my applications. Specifically, I have around 10 table components and 100 input components, each with an event listener. I'm noticing that on machines with lower CPU speeds (e.g., 2.4GHz), the application runs extremely slowly, while it performs well on higher-speed CPUs (e.g., 3.8GHz).

Are there any recommended hardware specifications for running Appsmith smoothly? Are there any optimization techniques within Appsmith to handle such scenarios more efficiently?

Thank you for your assistance!

### Steps To Reproduce

I have around 10 table components and 100 input components, each with an event listener.

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

1.5

**Comment by zhouzhou19950825** [comment]
Hello,
Does appsmith have any recommendations for configuration requirements for computer clients?
Thanks!

**Comment by Nikhil-Nandagopal** [comment]
@zhouzhou19950825 off the top of my head it first seems that you are on a very old version of the platform that does not have the latest performance improvements. Can you upgrade to the latest version and see if you are still facing this issue?

**Comment by vsvamsi1** [comment]
Hi @zhouzhou19950825 
I can think of the follow design practises to help improve of your app:
- Are all the components of your app in a single page? Is is possible if they can be split across multiple pages, you should be able see much better performance then.
<img width="257" alt="Screenshot 2024-06-25 at 4 03 52 PM" src="https://github.com/appsmithorg/appsmith/assets/121419957/23870eba-d75e-4fff-b51d-e149fa9bf5bc">

- If there are large datasets driving a table we recommend using the table's server side pagination feature to load smaller chunks of data, this should also help in improving the performance of you app.
<img width="291" alt="Screenshot 2024-06-25 at 4 07 42 PM" src="https://github.com/appsmithorg/appsmith/assets/121419957/3b464e4c-e433-45e4-86b4-d0a339c4817f">
