### ISSUE TITLE
[Bug]: User is able to select same color for both active and inactive state in the Rating UI element in Content section

### ISSUE THREAD

**Issue by samhithav27** [appsmithorg/appsmith#34385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the rating element of the app in the Content section in App Page, the colors for active (selected) and inactive (unselected) states are the same. This makes it difficult for users to differentiate between selected and unselected ratings, leading to potential usability and accessibility issues and misinterpretation of ratings can occur, especially in contexts where ratings influence decisions or outcomes.

### Steps To Reproduce

1. Open the app and navigate to Content section and select the rating element.
2. Navigate to the style section in rating element 
3. Select the same color for active and inactive ratings

![Screenshot from 2024-06-21 14-47-30](https://github.com/appsmithorg/appsmith/assets/98387561/bddeaf34-9d47-468c-b3b4-9de2ef0ff856)

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

v1.28

**Comment by Nikhil-Nandagopal** [comment]
@samhithav27 this seems like a user error and not a system error so I'm closing this issue
