### ISSUE TITLE
[Feature]: Call the setter method of the component in JS Function, hoping to pass in multiple parameters

### ISSUE THREAD

**Issue by rennzhang** [appsmithorg/appsmith#34381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Call the setter method of the component in JS Function, hoping to pass in multiple parameters

### Why should this be worked on?

Here is the translation of the provided Markdown content into coherent English:

For example: I need to access an Ant-design Form component, which itself contains some instance methods, such as: https://ant.design/components/form#forminstance;

I hope to support users in writing code in this way:
<img width="584" alt="image" src="https://github.com/appsmithorg/appsmith/assets/50518861/19345ead-bb84-4697-b17e-c2ca2491d1c9">

```
AntdForm1.validateFields(["name"], { validateOnly: true })
```
Through the above code, set the parameters to the `validateFieldsParams` property. After the component observes that the `validateFieldsParams` property value has changed, I can trigger the component's internal `formRef.current.validateFields` method, and get the value of the `validateFieldsParams` property. The actual call result is:
```
formRef.current.validateFields(["name"], { validateOnly: true });
```
This is just an example. For other components, it would also increase flexibility, enabling more features.

---
Of course, I can also require users to pass in parameters like this:
```
AntdForm1.validateFields({nameList: ["name"], options: { validateOnly: true }})
```
However, this does not conform to user intuition and requires additional training and explanation, thereby increasing the difficulty of building applications on the platform.

**Comment by Nikhil-Nandagopal** [comment]
@rennzhang Apologies but we can't accept this contribution. We don't believe this is a better experience and are unable to understand the need to manually trigger the validation of fields on the platform

**Comment by rennzhang** [comment]
> @rennzhang Apologies but we can't accept this contribution. We don't believe this is a better experience and are unable to understand the need to manually trigger the validation of fields on the platform

Okay, my requirement is based on the existing logic. Is there any good solution?

**Comment by Nikhil-Nandagopal** [comment]
Can you tell us about your application and what you are trying to achieve in it?
