### ISSUE TITLE
[Bug]Losing primary columns custom column formatting after getting a cyclical dependency issue on table columns

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#3440]

**Comment by trishaanand** [comment]
This issue can be easily recreated by following the steps as below :
1. Drop a table and attach it to an action.
2. Let the primary columns form on the basis of the data.
3. Add some custom formatting like changing the name of the columns, etc.
4. Now open a setting of one of the columns and in the text colour field, turn on JS and in the binding, start with writing the table's own name. This would create the cyclical dependency.
5. Now observe that all the formatting that you had done before introducing the cyclical dependency has been lost.

**Comment by tazmaniax** [comment]
This is the warning that was displayed
<img width="282" alt="CleanShot 2021-03-08 at 13 18 19@2x" src="https://user-images.githubusercontent.com/1079943/110336855-3108cf80-801d-11eb-84a1-0eadd73d8476.png">

I also encountered this same error for two other tables on the same page that I did not specify the table name in a JS binding

**Comment by prapullac** [comment]
Hi @trishaanand 
I am seeing this is still exists on Release 

![Screenshot 2021-03-12 at 1 11 32 PM](https://user-images.githubusercontent.com/71753653/110908299-9a962000-8334-11eb-8df6-25dcbf2a5d85.png)
