### ISSUE TITLE
[Bug] Bound input widgets don't update their value if edited, when the resulting value has not changed

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3443]
This issue is best demonstrated with a video:

https://user-images.githubusercontent.com/120119/110352149-92e82a00-805b-11eb-9c42-b4d89e07e898.mov

In words,

1. Drop a table and an input widget.
2. Bind the input widget's default value to `{{Table1.selectedRow.email}}` (assuming `email` is a valid column in the table, and at least two rows have the **same** value for `email`.
3. Now select a row with the duplicated email.
4. Edit the text inside the input widget.
5. Now select a row with a different email. Notice that the email is updated in the input widget.
6. Now select the email from point 3 again.
7. Edit the text inside the input widget, like point 4 again.
8. Now select a row with the *same* email. Notice that the email is **not** updated in the input widget.

The inconsistency in behavior in points 5 and 8 is unexpected.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu looks like we regressed on this. Can we please add a test case on this

**Comment by ashrafaa** [comment]
hi @Nikhil-Nandagopal is there any update to this? It does make the user confused when the previous value still exist after selecting new row 😕

**Comment by hetunandu** [comment]
Hey @ashrafaa, this seems to be an odd case. I'll debug this further and get a good solution. Today we seem to be doing the overwrite of default values by value comparison but maybe we should change that looking at this issue. Ill pick this up on priority

**Comment by hetunandu** [comment]
Hey @ashrafaa, we have fixed this issue and it should be included in the next release 😄

**Comment by ashrafaa** [comment]
Nice one @hetunandu 👍  I'm looking forward for the release 😄

**Comment by ashrafaa** [comment]
@hetunandu has this fix been included in release 1.4.5?

**Comment by hetunandu** [comment]
Hey @ashrafaa, yes, it is included in the release. Is it not working for you?

**Comment by ashrafaa** [comment]
ok cool I have not yet updated to latest; just reviewed the release note and could not find reference to this ticket. Thanks @hetunandu

**Comment by hetunandu** [comment]
Oops. Sorry, it looks like we missed out on mentioning this issue. Your on-prem installation must have auto-updated. Can you confirm if it is working for you?
