### ISSUE TITLE
[Bug]: Several components have label display issues

### ISSUE THREAD

**Issue by samhithav27** [appsmithorg/appsmith#34433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For some components Button Label, Mapchart (Title), Chart (Title) in Display Section , Menu button, Button Label in Layout section of JSON Form, File Picker 

Whenever I give a very long text in the field label/title, only a certain portion of the text is being displayed. There is no way users can see the entire label (not even on hovering). 

### Steps To Reproduce

1. Go to the elements 
2. Click on the title/label and give a really long text. For eg: {There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.}
3. Only a portion of text is seen 
![Screenshot from 2024-06-24 15-18-19](https://github.com/appsmithorg/appsmith/assets/98387561/033f5671-949e-45fd-bdaa-1962e59329b8)
![Screenshot from 2024-06-24 15-17-58](https://github.com/appsmithorg/appsmith/assets/98387561/9082d71c-3eb0-41d9-a802-c6a3fd510703)

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

v1.28

**Comment by Harshithazemoso** [comment]
hello @Nikhil-Nandagopal I am picking up this issue
