### ISSUE TITLE
[Research]: Find if there is a library that supports IDE component nee

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#34438]
Find a UI library which can help in heavy lifting of the IDE structure requirements.
Features needed:

- Can define Views / Panels of different shapes and sizes
- Can support a grid structure (Rows and Columns)
- Can animate change of size and view. Can pass custom spring config for the animations
- End user can resize the Views / Panels

**Comment by alex-golovanov** [comment]
Given the constraints of react-spring and the need for resizable columns there are no good readily available libraries. CSS grid appears to cover all of the requirements and is the most performant solution as well.
