### ISSUE TITLE
[Feature]: Simplify Git connection management across apps

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#34440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, each Appsmith app requires a specific deploy key for connection to Git, which introduces management overhead when scaling. Additionally, managing specific access controls for developers within enterprises can be cumbersome. 
A simple one-time connection setup at the instance level which handles all the subsequent requests would be the ideal way.x`

### Why should this be worked on?

As the number of apps within an organization scale, it becomes increasingly challenging to manage "deploy keys" for each of them. Enterprises would gain following benefits
- Reduced overhead in managing deploy keys across multiple apps.
- Enhanced security and compliance with better access control mechanisms.

**Comment by infinitetrooper** [comment]
Fixed with Monorepo - https://github.com/appsmithorg/appsmith/issues/11120
