### ISSUE TITLE
[Bug]: Widget label is persistent when property pane pop-ups are opened

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Widget label is persistent when property pane pop-ups are opened

![image](https://github.com/appsmithorg/appsmith/assets/79509062/1bf45ef6-28be-4a28-b3af-46115b910356)

### Steps To Reproduce

1. Highlight a widget
2. Open it's action selector pop-up as seen in the screenshot

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by LagunaElectric** [comment]
This is happening for the site footer bar and the error pane as well.

https://www.loom.com/share/04ccc8013d3c4a88ac582112ab37b3b3?sid=47d4912a-fef3-43cd-bdb5-787867a742f4
