### ISSUE TITLE
[Bug]: As a user, I try to add and discard googlesheet as datasources and app crashes

### ISSUE THREAD

**Issue by sagar-qa007** [appsmithorg/appsmith#34478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have tried to unsave my data sources error with "google sheet" and app got crash.

https://github.com/appsmithorg/appsmith/assets/27190171/1716b2bc-b160-4345-b42e-75e13a95f009

### Steps To Reproduce

1. Go to data sources page.
2. Select googlesheet as data source and then do not save it.
3. Again follow the step 2.
4. Find out that app got crash.

Try to add datasource as google sheet and then discard it. Please refer video for more details.

https://github.com/appsmithorg/appsmith/assets/27190171/83882f39-a215-442d-a6da-2ce0476fc164

<img width="1437" alt="Screenshot 2024-06-26 at 11 50 22 AM" src="https://github.com/appsmithorg/appsmith/assets/27190171/196beb56-9294-456a-b784-7c55c39443e1">

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud - Appsmith 8971aaf8

**Comment by rohan-arthur** [comment]
I've not been able to replicate the crash, but @packages pod, maybe you want to take a look at this considering the error in the console? 

https://github.com/appsmithorg/appsmith/assets/94514895/46395cde-89c5-44f2-836f-5acd228b7708

**Comment by rohan-arthur** [comment]
not reproducible, and could not find anything on sentry either. Please reopen if the issue persists
