### ISSUE TITLE
[Bug]: When the origin module name gets changed all the references to that module don’t get refactored

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#34492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the origin module name gets changed all the references to that module don’t get refactored

### Steps To Reproduce

.

### Severity

Medium (Frustrating UX)

### Version

Cloud/Selfhosted

**Comment by subrata71** [comment]
Duplicate of https://github.com/appsmithorg/appsmith/issues/33465
