### ISSUE TITLE
[Bug]: There are two loading spinners when renaming a module instance

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#34499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/appsmithorg/appsmith/assets/113327629/ce46747a-a9e9-4e2b-8294-0686b2ce0022

### Steps To Reproduce

.

### Environment

Deploy Preview

### Severity

Low (Cosmetic UI issues)

### Version

Cloud/Selfhosted

**Comment by admirhusic** [comment]
Can you assign this ticket to me? Thanks! :)
