### ISSUE TITLE
[Bug]: Auto-commit does not run for this old app on app.appsmith.com

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#34505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Auto-commit does not run for this old app on app.appsmith.com. Repo is here - git@github.com:btsgh/testapp.git

### Steps To Reproduce

1. Open an existing git connected app on app.appsmith.com
2. Wait for the auto commit bar to appear. It never appears and commits show up for manual commit. 
3. Also checked the repo, and no auto commit entry has happened.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/56e6148f-672f-49e6-ab14-3617b11b1675

### Version

Cloud

**Comment by btsgh** [comment]
Shared the app's with @sondermanish [https://app.appsmith.com/app/testapp/snowflakedata-65031cb71045a805525b4a36?branch=master]

**Comment by sondermanish** [comment]
@btsgh On the first app, the autocommit won't happen because the Remote is ahead of the local, as it's seen in the pull bar.

**Comment by sondermanish** [comment]
In the second app which belongs to repo: https://github.com/btsgh/GitTest_Oauth
had some changes in the cloud which was not commited. These changes could be found on this commit:
https://github.com/btsgh/GitTest_Oauth/commit/69b70676a77e459ff8c429cc4efde01cdf771aba

**Comment by sondermanish** [comment]
@btsgh Both scenarios are expected given the conditions.

**Comment by btsgh** [comment]
Ok noted @sondermanish .. will try out the discard and pull for the first case

**Comment by btsgh** [comment]
> @btsgh On the first app, the autocommit won't happen because the Remote is ahead of the local, as it's seen in the pull bar. <img alt="image" width="292" src="https://private-user-images.githubusercontent.com/107841575/343152224-c41c3bcb-8429-48e9-9a9a-8695c6ffb64a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTM0NDcsIm5iZiI6MTcxOTQxMzE0NywicGF0aCI6Ii8xMDc4NDE1NzUvMzQzMTUyMjI0LWM0MWMzYmNiLTg0MjktNDhlOS05YTlhLTg2OTVjNmZmYjY0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxNDQ1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjNjM2VjYTNlOWUwNGQyM2EyNTZiNjU4MTIxMzZhNzMzYzUxMmFkYjdjNDE4MTdjOGI2NzVlZDk5MDAwNmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.698StaAn9ZuLaAj0i6Mspuep8RmGugDPGaY4CpQoFQI"> Let's try discard and pull?

So when I discarded and pulled, auto-commit ran, and the system generated commit for the new changes is seen in the repo as well @sondermanish

**Comment by sondermanish** [comment]
closing this issue, as the scenarios meet the expectation.
