### ISSUE TITLE
[Task]: Remove "from" from sections headings when adding a new query

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#34530]
### SubTasks

The word "from" should be removed from all the headings, except the top one when adding a new query to prevent repeating it constantly.

Design example:
https://www.figma.com/design/DDP4RXK4YOTEJnuC8ocm47/IDE-Exploration?node-id=13100-82327&t=U9cKBziqtYqL8BGh-4

**Comment by albinAppsmith** [comment]
Closed by https://github.com/appsmithorg/appsmith/pull/34981
