### ISSUE TITLE
[Task]: Double click to rename a file/tab

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#34536]
### SubTasks

In side-by-side there will be 3 ways to rename a file:
1. List of all files (more options menu -> rename)
2. Double-click on the tab name in the tabs list
3. More options menu in the new action bar (will be implemented in another project)

2 and 3 are very important ways to rename a file for efficiency and the mental model that our users have about how files should be renamed ([more on that in this research](https://www.notion.so/appsmith/Naming-and-renaming-files-tabs-4f293537fce84b05b413ff4bff6aa885?pvs=4)). They will also not be possible without implementing the rename design from here: https://www.figma.com/design/DDP4RXK4YOTEJnuC8ocm47/IDE-Exploration?node-id=13052-82500&t=U9cKBziqtYqL8BGh-4

**Comment by hetunandu** [comment]
Fixed #36968
