### ISSUE TITLE
[Task]: The queries tab is not attention grabbing enough, and users click on the data tab rather than on the Queries tab

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#34549]
### SubTasks

Emphasise queries rather than de-emphasize the datasources tab.
- [ ] show the number of queries.
- [ ] Increase the font-weight of the text.

**Comment by kocharrahul7** [comment]
@vinay-appsmith @momcilo-appsmith Can we get an indication of the font-weight we should use for this

**Comment by kocharrahul7** [comment]
`Add a count next to the queries, JS, UI to reflect the number of entities. Font-weight changes to 500 in the segmented control.`
from: @vinay-appsmith

**Comment by hetunandu** [comment]
Closing this in favor of #37881
