### ISSUE TITLE
[Feature]: Make Session age configurable

### ISSUE THREAD

**Issue by gootik** [appsmithorg/appsmith#34567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi there,
We have a usecase where a 30 day session age is not desirable. We want to auto kill the session from browser after 2 hours, essentially logging the user out. Currently this is not possible since the session max age is hard coded to 30 days. 

There has been a request previously https://github.com/appsmithorg/appsmith/issues/3981 which was solved by the OP through an other approach.

### Why should this be worked on?

This helps with tight security needs when use cases requires stricter user session configs.

**Comment by Nikhil-Nandagopal** [comment]
@gootik this is now possible here 
https://github.com/appsmithorg/appsmith/issues/24455#issuecomment-2018024266
