### ISSUE TITLE
[Bug] Launch option is not function when on other pages 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3457]
Steps to reproduce:
1) Navigate to page 
2) Navigate to widget bar 
3) now click on Global search
4) Search for an entity
5) Click on launch icon

Observation :
It is observed that click on the lunch icon the user is not navigated to the respective page 

Expectation:
User must be able to navigate to respective page 

Video
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c3172834d48148bfb638cdf7f4880cc4-00001.gif)](https://www.loom.com/share/c3172834d48148bfb638cdf7f4880cc4)

**Comment by Itashamodi** [comment]
assign me
