### ISSUE TITLE
[Bug]:The default value for PhoneInput is set to text, which is invalid.

### ISSUE THREAD

**Issue by raza001** [appsmithorg/appsmith#34594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The widget gets a text through the default value and does not show an error.

### Steps To Reproduce

1 . First Go and select Phone Input  from Ui Section
2. Right Side Bar - There default value 
3 . Only accept number for  phone input 

### Environment

Production

### Severity

Critical (Broken Production apps)

### Issue video log

https://www.loom.com/share/5f33f947dc384d1899cd14bbc1a801f1?sid=488efc5e-9b81-495b-bd8c-03def98e686e

### Version

cloud

**Comment by Harshithazemoso** [comment]
hello @Nikhil-Nandagopal I am picking this issue

**Comment by Harshithazemoso** [comment]
Hello @Nikhil-Nandagopal, @Pranvkakde,

**Approach 1**: The user will see an error message if they enter text in the default field, and the value will not be added to the widget until a number is entered.

**Approach 2**: Do not allow the user to enter text in a field where a number is expected, eliminating the need for an error message.

I have noticed that the entire application currently follows Approach 1. Could you please explain why Approach 2 is not being used?

I will proceed with **Approach 1**.

**Testing**:
Cypress/Jest tests will be created to cover the new behavior of the PhoneInput widget.

Thank you.

**Comment by Nikhil-Nandagopal** [comment]
This is expected, validations are only for user input and not for developer configurations. Looking at Ant design, it follows the same experience

**Comment by Harshithazemoso** [comment]
Okay got it @Nikhil-Nandagopal,
 Thank you
