### ISSUE TITLE
[Bug]: Dashes in Postgres Datasource Table Name Fail to Load

### ISSUE THREAD

**Issue by JosTheDude** [appsmithorg/appsmith#34596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I currently am using a Postgres Datasource for my AppSmith UIs via AppSmith Cloud. However, when a table I'm working with has a dash in the name:

Example:
![image](https://github.com/appsmithorg/appsmith/assets/43651265/dc38dc5c-a43f-4f3c-b34f-79646f6cf16d)

It completely fails to load: 
![image](https://github.com/appsmithorg/appsmith/assets/43651265/5a9b4fc9-ffa0-4612-9f48-79aab1481a23)

All other data tables without dashes load fine.

### Steps To Reproduce

1) Use a Postgres Datasource in AppSmith Cloud
2) Create a table in the Postgres Database
3) View the Datasource in AppSmith / attempt work with it

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by JosTheDude** [comment]
Most databases follow proper Postgres snakecase table name convention, however, this particular dataset didn't follow that convention hence the discovery.

**Comment by rohan-arthur** [comment]
@JosTheDude thank you for reporting the annoying bug! We are already tracking it in #30692 , so I am closing this one
