### ISSUE TITLE
[Bug]: datasource deletion refers to "action(s)", which is meaningless to the user

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#34604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Try deleting a datasource that has some queries on top of it. The error says: `Cannot delete datasource since it has 1 action(s) using it`

The word "action" is internal to the codebase, and means nothing to the user. Ideally, the error should be `Cannot delete datasource since it has 1 query using it`

There are two problems with the error message:
1. `action` should change to `query`
2. the error should be intelligent to know between `query`(in case there is only 1) and `queries` (in case > 1)

### Steps To Reproduce

1. create any datasource
2. create a query on top of it
3. go back and try to delete the datasource
4. see the error toast

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by AnnaHariprasad5123** [comment]
Hi @rohan-arthur , I will do this change.

**Comment by NilanshBansal** [comment]
Updated the estimate to 1 as the test failures are a lot on the draft PR
Ref: https://github.com/appsmithorg/appsmith/pull/34863
<img width="753" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/7a5dbd67-5920-4fd5-87f3-9df95ac997de">

**Comment by daaliachhak17** [comment]
As per comment- closing ticket-https://zemoso.atlassian.net/browse/TNOSB-296
