### ISSUE TITLE
[Bug]: Improper Input validation in Git user config page

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#34602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In `Git user config` page, the username input doesn't have enough validation checks as required by industry standards.

It should at least match [Github validations](https://github.com/shinnn/github-username-regex).

### Steps To Reproduce

1. Go to `Edit profile` page, by clicking on the profile avatar icon
2. Go to `Git user config` page
3. username Input doesn't have the required checks as industry standards

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud - 1.29

**Comment by brayn003** [comment]
So, this field is not the github username. This is the user full name that goes inside commit details.
Adding this link for reference - https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git

**Comment by riteshkew** [comment]
Closing this as per above. It is as expected.
