### ISSUE TITLE
[Feature]: UI component is missing a calendar component

### ISSUE THREAD

**Issue by sigilzen** [appsmithorg/appsmith#34636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

 UI component is missing a calendar component

### Why should this be worked on?

Hello, the UI component is missing a calendar component, that is, a component with different display modes such as month view, week view, and day view. I found a calendar component in tooljet. Hopefully, appsmith will also complement this important component.
![eefd21c40af278c2e4f31f7eab7f6d07](https://github.com/appsmithorg/appsmith/assets/77775133/d68dc87a-51ea-4f05-84f0-e217e135b0e7)

**Comment by Nikhil-Nandagopal** [comment]
@sigilzen you can find this feature request here #2410 
We also have a community custom widget that you can use
https://community.appsmith.com/template/calendar
