### ISSUE TITLE
[Type]-[400]:Forward, backward navigation across Appsmith

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3464]
## Summary
Using the browser back and forward keys on the browser should work as the user would expect. Today they don't navigate as expected and make it difficult to go back and forward inside Appsmith.

What would a good solution look like?
Say I'm on the canvas with the property pane of a widget open. I then navigate to the API pane to create a new API. I should be able to navigate back to the canvas with the exact location I was on inside the property pane.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 100 |
| Effort (months)  | 0.5 |

**Comment by rohan-arthur** [comment]
won't fix - project cancelled
