### ISSUE TITLE
[Task] Update use prepared statement UI in settings

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#34670]
<img width="280" alt="Screenshot 2024-07-29 at 10 11 14 AM" src="https://github.com/user-attachments/assets/bf44befc-94b3-438d-bd85-e5b8b02c5695">

Show a warning banner in response tab when the prepared statement toggle is on.
Design: https://app.zeplin.io/project/6683c698d2210f2b0697d978/screen/66951e174073dc249b335471

**Comment by albinAppsmith** [comment]
Closing this task since this is moved to individual query config update tasks.
