### ISSUE TITLE
[Bug]: <JSObject function> is not a function

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#34681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever the user lands on a page directly, the buttons call a few JSObject functions that were working fine but when they were navigated to the same page, from another particular page, an error was thrown stating that the  <JSObject function> was not a function

### Steps To Reproduce

Import application and follow the steps in the video mentioned here - https://theappsmith.slack.com/archives/C040LHZN03V/p1720008717797009?thread_ts=1720008260.264769&cid=C040LHZN03V 

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

1.29

**Comment by rishabhrathod01** [comment]
Workaround for the current user :- 
when the user commented out certain store value lines of code, then it worked properly. But if those lines of code were present, then functions stopped working on the navigated page.

**Comment by tomjose92** [comment]
This issue was occurring  for the user only in deployed mode of the App.
In edit mode their original piece of code was working completely fine without breaking the other page functionalities  like JSObject functions.

**Comment by PaulMcF1987** [comment]
I am suffering from the same problem.
Occasionally, the app works fine but more often than not it fails, telling me, in console 'xxxx.fun is not a function'
I have messed around with the js but no joy
It only seems to happen with certain 'storevalue values' 
I know the values that cause the issue but have no way of sorting it

**Comment by rishabhrathod01** [comment]
> I am suffering from the same problem. Occasionally, the app works fine but more often than not it fails, telling me, in console 'xxxx.fun is not a function' I have messed around with the js but no joy It only seems to happen with certain 'storevalue values' I know the values that cause the issue but have no way of sorting it

@PaulMcF1987 which version of appsmith are you using?

**Comment by PaulMcF1987** [comment]
@rishabhrathod01 Sorry, I missed your reply. I am using self hosted Appsmith Community v1.33.
Not sure if the version may have updated since posting above

**Comment by rishabhrathod01** [comment]
@PaulMcF1987 are you facing the above issue in version 1.33 ?

**Comment by PaulMcF1987** [comment]
@rishabhrathod01  Seems to be working ok at the minute
