### ISSUE TITLE
[Bug]: Preview of triggeredRow is not actually the current stored value

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#34690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/appsmithorg/appsmith/assets/123981587/5903322a-7d71-417f-bca7-6ca2c484f0fb)

When I am writing code that relates to a storedValue the preview window that pops up does not display the current stored value.  See screenshot with preview window in upper right corner and a text widget displaying the actual stored value in bottom left.

This makes it difficult for testing as if I hard-code a value that the preview is giving me, it won't be what I recently stored.

### Steps To Reproduce

Load a page with stored values and confirm they display.

Write a storeValue operation that should overwrite it.

Execute that and see that the preview does not update.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self Hosted 1.26

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS I'm not able to reproduce this issue. Can you share a video recording?
