### ISSUE TITLE
[Bug]: Adding any template from home page brings up errors. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#34720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a template from the home page [this is true for any template added .. tried with Applicant tracker, WhatsApp CRM, meeting scheduler etc], we see a Response not valid error. 

### Steps To Reproduce

https://jam.dev/c/1ad4b383-0b71-4b94-b7fb-b584146fb5c9

<img width="1090" alt="Screenshot 2024-07-04 at 3 56 22 PM" src="https://github.com/appsmithorg/appsmith/assets/101863839/d8d6d61f-a8ae-4407-bcb9-bbe2ab66436d">

Also, we see at first instance, the queries fail as well, and only pass on refresh.
https://jam.dev/c/225578ea-080e-4a6c-9d58-3834e41b74a4

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Cloud

**Comment by SunnyTitus** [comment]
Please find the possible solution through my findings:

"To address the issue of errors when adding templates from the home page, the solution involves enhancing error handling and implementing retry mechanisms for API calls and query executions. By catching and handling errors gracefully in the frontend and ensuring robust validation in the backend, the user experience can be significantly improved, allowing for seamless template addition without encountering initial errors or requiring page refreshes.."

Our team will be working on this issue and update accordingly.

**Comment by btsgh** [comment]
Issue seen on Production - recording as below: 

https://github.com/appsmithorg/appsmith/assets/101863839/8e015a9d-c956-4c4c-8573-23d88150f602

**Comment by btsgh** [comment]
The 'Response not valid' issue can be reproduced on latest v1.29 version as well as Prod
Removing the  blocker tag, but it is a critical issue as it is with customers already, and would need to be fixed to go with the next release at least.
