### ISSUE TITLE
[Bug]: Unable to find CSS for custom widgets, this is very important

### ISSUE THREAD

**Issue by sangyuan6122** [appsmithorg/appsmith#34737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to find CSS for custom widgets, this is very important

### Steps To Reproduce

Unable to find CSS for custom widgets, this is very important

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

V1.29

**Comment by Nikhil-Nandagopal** [comment]
@sangyuan6122 we have this issue tracked here #3095 so I'm closing this as duplicate.

Can you tell us why this is so important to you?
