### ISSUE TITLE
[Feature] Add support for Firestore's delete field and server time stamp field values

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3475]
Currently, there's no way to delete (aka `unset`) individual fields in an existing document on Firestore. In the Java API, this is done by doing an update operation with the value of the field set to `admin.firestore.FieldValue.delete()`. Like so:

```json
{
  "name": "New name",
  "role": <The magical value of admin.firestore.FieldValue.delete()>
}
```

This, when placed in the body of an update query in Firestore action, should update the `name` field with `"New name"` and *unset* the `role` field in the document.

Similarly, support is needed for the `admin.firestore.FieldValue.serverTimestamp()` field value which sets the field to the current server timestamp.

**Comment by tazmaniax** [comment]
Also I think to able to store a Timestamp value it's necessary to use the [Firestore API](https://firebase.google.com/docs/reference/js/firebase.firestore.Timestamp#constructors_1), e.g `new admin.firestore.Timestamp(seconds, nanoseconds)`. Would this be supported in #3693 ?

**Comment by sumitsum** [comment]
Hi @tazmaniax , thanks for bringing this to our attention. As per the current plan, the scope of the PR  #3693 is to provide FieldValue.delete() and FieldValue.serverTimestamp() support. I have raise another Github issue to track `firebase.firestore.Timestamp` and `firebase.firestore.GeoPoint APIs` : https://github.com/appsmithorg/appsmith/issues/3741

**Comment by tazmaniax** [comment]
@sumitsum thx!
