### ISSUE TITLE
[Bug]: Snowflake key pair auth - Test configuration is successful without private key

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#34761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upon editing an authorised Snowflake datasource (using key pair auth), the private key is not displayed in the field & clicking the `Test configuration` button does not throw any error instead it renders successful.

### Steps To Reproduce

1. Authorise a Snowflake DS using key pair auth.
2. Now edit the configuration.

**Expected:** 
1. The private key should be displayed.
2. Clicking on the `Test configuration` without a private key should throw an error.

**Actual:**
1. Private key is not displayed in the field.
2. No error is thrown on clicking the `Test configuration` button without the private key.

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Issue video log
https://jam.dev/c/13a1b04f-9086-4866-b419-d0cd23b4923e

_No response_

### Version

Cloud

**Comment by rohan-arthur** [comment]
same as [this](https://github.com/appsmithorg/appsmith/issues/14783#issuecomment-1165157508)
