### ISSUE TITLE
[Bug]: Error console can't be open when Queries or JS tab is selected.

### ISSUE THREAD

**Issue by znamenskii-ilia** [appsmithorg/appsmith#34764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Given I have some linting errors and Queries tab is selected, when I click the error icon then nothing is happen

### Steps To Reproduce

1. Add button widget
2. In "onClick" field write some invalid js. "xxx" for example
3. See an error icon at the bottom right corner
4. Select Queries or JS tab in the left pane
5. Click the error icon

![image](https://github.com/appsmithorg/appsmith/assets/5811832/c56e810f-1578-4454-bde2-95a6b9db8a05)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 @hetunandu can you have a look?

**Comment by gauravshinde1816** [comment]
@Nikhil-Nandagopal  Can I take a look into this issue.

**Comment by Nikhil-Nandagopal** [comment]
@gauravshinde1816 this feature is still under development so this is not a good issue to pick up

**Comment by gauravshinde1816** [comment]
Ok

**Comment by rohan-arthur** [comment]
same as #34274
