### ISSUE TITLE
[Bug]: `Generate new page` button not seen for mock databases & Gsheets

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#34771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When do not see the `Generate new page` button at the bottom of the datasource screen for mock databases & Gsheets.

### Steps To Reproduce

1. Authorise mock/Gsheet datasource.
2. Save the configuration.

**Expected:** `Generate new page` button should appear at the bottom of the screen upon successful authorisation.
**Actual:** The button is not visible

### Environment

Release

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://jam.dev/c/98481a5f-d267-4d88-a8fb-2c0fa2547b7e

### Version

Cloud

**Comment by rahulbarwal** [comment]
Hey @shadabbuchh 
this was done as a part of https://github.com/appsmithorg/appsmith/pull/34655

The `Generate new page` is hidden when drag and drop of building blocks is enabled(which is true for everyone on release).

**Comment by shadabbuchh** [comment]
> The `Generate new page` is hidden when drag and drop of building blocks is enabled(which is true for everyone on release).

@rahulbarwal if that is the case then why do we see the button for rest of the datasources?
https://jam.dev/c/c3a41046-9f7e-4296-b6c7-c7cca0ddf1a0

**Comment by rahulbarwal** [comment]
> > The `Generate new page` is hidden when drag and drop of building blocks is enabled(which is true for everyone on release).
> 
> @rahulbarwal if that is the case then why do we see the button for rest of the datasources? https://jam.dev/c/c3a41046-9f7e-4296-b6c7-c7cca0ddf1a0

@jacquesikot can you please check this ?

**Comment by jacquesikot** [comment]
@shadabbuchh @rahulbarwal I am looking into this. The button should be disabled for all datasources

**Comment by shadabbuchh** [comment]
Verified on release.
https://jam.dev/c/bbf55f6c-673d-4d72-8fa1-e05669a3bdc0
