### ISSUE TITLE
[Feature] Mailto Action

### ISSUE THREAD

**Issue by Pjirlip** [appsmithorg/appsmith#3478]
## Summary

It would be great to be able to use an mail dispatch "action" for forms etc. The option could be made dependent on whether the server has a mail configuration or not. 

Something like: 

```javascript
{{  
       mailto(<FromMail>, <toMail>, <Subject>, <Message> )
}}

// Used like:
{{ 
    mailto(Mail_From_Input.text, "receiver@example.com",  "Your Request", RICH_Input.text)
}}
```

## Motivation

I want to build an input mask for our GitLab service desk using Appsmith.

Unfortunately, GitLab does not currently provide an API endpoint for the [Service Desk feature](https://docs.gitlab.com/ee/user/project/service_desk.html), so I would like to use a form to simulate that a customer has sent an email. However, I can't send an e-mail using Appsmith. (At least I would not know how?). 

Therefore I currently have to use the GitLab API for normal issues, which does not offer the features of a service-desk-issue.

Regardless of my problem, though, there are certainly some possible usage scenarios for the feature.

## Additional Context

- If it is not clear what I meant, I will be happy to answer any questions.

**Comment by Nikhil-Nandagopal** [comment]
Hey @Pjirlip 👋  thank you for the issue contribution. The way we think about sending emails is by introducing an email service as a datasource and triggering the email through them. So if you have access to
- Sendgrid
- AWS SES
- Twillio
- Any other email service

You should be able to trigger their email API with these fields. We don't have this as part of appsmith as configuring a mail server on our end could lead to a large drop in domain authority from users abusing the feature. So we recommend integrating with a third-party service to accomplish this. I hope this helps and we will definitely introduce a plugin for communicating with these services in the future 😃

**Comment by Pjirlip** [comment]
Hello Nikhil,

thank you for your quick reply! 

I can understand that, but using an external provider does not prevent potential misuse. It just shifts the potential negative reputation due to the misuse.

Especially since in my example only internal mail traffic is used. In Appsmith my mail server is stored with mailbox appmsith@mydomain.com and should send to gitlab@mydomain.com for the use case. The mail never leaves the mail server. Usually you don't use filters for local mailboxes. Accordingly, no negative repuattion can occur. I think this applies to most use cases concerning internal tooling. 

Of course, this should be used with caution when sending to external addresses. (Maybe the feature is better suited with a restriction to mailboxes of the deposited domain). But I don't think it's any less dangerous than using click-built forms that use APIs or execute database queries. 😄 

Thanks a lot for all the work you put into Appsmith and for being so diligent.

**Comment by nidhi-nair** [comment]
Hey @Pjirlip ! It's been a while, but I'd like to circle back on this issue if it is still relevant to you. Appsmith now supports an SMTP plugin that might serve your use case. Do you think that's something you'd like to try out?

**Comment by rohan-arthur** [comment]
@Pjirlip there are a couple of ways you can trigger emails, either with the SMTP plugin, or even with Twilio if you like. Closing the issue now, please re-open if your requirement is not met.
