### ISSUE TITLE
[Bug]: In Checkbox Element a Position tabs are working in opposite direction.

### ISSUE THREAD

**Issue by veerprashant** [appsmithorg/appsmith#34791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In checkbox element , I am trying to change position of checkbox icon from content section by clicking on Left and Right tab . When i click on Left tab checkbox goes to right side and when i click on right tab checkbox goes to left side. 

### Steps To Reproduce

1. Drag and drop simple checkbox .
2. go to content section
3. click on left position tab
4. go to checkbox element , check checkbox position
5. click on right position tab
6. go to checkbox element , check checkbox position
7. position tab working in opposite direction

![Screenshot from 2024-07-08 17-42-36](https://github.com/appsmithorg/appsmith/assets/112857707/0c70c47c-9523-49a0-aee1-fedc83961474)
![Screenshot from 2024-07-08 17-42-08](https://github.com/appsmithorg/appsmith/assets/112857707/e67cec5e-0887-414f-add8-22a3f1c33d07)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/b245d749eebb4b0e92300b0de97a3e04?sid=2888d0dc-b63e-409a-bb10-5b426fcb1c0b

### Version

v1.28

**Comment by Nikhil-Nandagopal** [comment]
@veerprashant the property is for the position of the label and not the checkbox

**Comment by veerprashant** [comment]
> @veerprashant the property is for the position of the label and not the checkbox

@Nikhil-Nandagopal if the position is the property of label then the checkbox should not move from it's place , but in this case label is not moving only the checkbox is moving left and right. can you please check it once and confirm? 
You can also see it in loom video.

**Comment by Nikhil-Nandagopal** [comment]
@veerprashant the left / right property determines whether the label is to the left or right of the checkbox. The alignment property determines whether it is aligned to the left or the right of the widget

**Comment by veerprashant** [comment]
> @veerprashant the left / right property determines whether the label is to the left or right of the checkbox. The alignment property determines whether it is aligned to the left or the right of the widget

@Nikhil-Nandagopal I got it , Thanks for explaining it.
