### ISSUE TITLE
[Bug]: Statbox icon appears close to a dot when occupying the smallest space

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When statbox widget is placed next to widgets it occupies the smallest space and shrinks it's icon to close to an unidentifiable blob

![image](https://github.com/appsmithorg/appsmith/assets/79509062/14cc5be2-a9ef-4a8a-b110-57cf5d15d2ac)
![image](https://github.com/appsmithorg/appsmith/assets/79509062/411c1722-3649-41d4-8e9e-3489f4802e7c)

### Steps To Reproduce

1. Drop a statbox as seen in the screenshots

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

cloud

**Comment by ichik** [comment]
@jsartisan @KelvinOm icon should not resize at all.

**Comment by KelvinOm** [comment]
@ramsaptami Could you check this. Should be fixed.
