### ISSUE TITLE
[Bug]: Sections are only hoverable from the side and between zones

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#34802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It’s not possible to highlight a Section when hovering from the top or bottom if there is only one zone. You can hover from the right side and there is a tiny, like 2-3px, area where you’re hovering the section itself. If there are two or more zones you can also hover the section by hovering between zones.

### Steps To Reproduce

1. Drag a Zone onto the canvas.
2. Try to hover the section from any side. You will need to move slowly or you'll miss it!
3. Observe that you cannot hover the Section from the top, bottom, or left sides.
4. Observe that you can just barely hover the Section from the right side.
5. Add another Zone to the Section.
6. Observe that you can hover the Section between ones, just above and below the Zone resize handle.

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

Appsmith v1.31.0-SNAPSHOT

**Comment by somangshu** [comment]
[Somewhat related](https://github.com/appsmithorg/appsmith/issues/32924)

This is covered under the on-canvas UI change that Taras has proposed. Closing this.
