### ISSUE TITLE
[Bug]: CURL code editor not visible in split view in special cases

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#34832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to add a curl import in split view, we are redirected to the empty state.

**Note:** 

- This is only reproducible in split view 
- Happens only when we do not have any existing query
- Does not happen in the latest tagged version (hence marking it as a regression)

### Steps To Reproduce

1. Create a new app.
2. Now switch to split view & try to create a new cURL import.

**Expected:** The cURL command editor should be visible in split view.
**Actual:** We do not see the editor & are redirected to the empty state.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/1603f64c-5061-4c5d-815d-0c1f1445c1f4

### Version

Cloud

**Comment by hetunandu** [comment]
fixed in https://github.com/appsmithorg/appsmith/pull/34830
