### ISSUE TITLE
[Bug] redirectUrl's with query params shows a 502 bad gateway page

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#3487]
## Description

If a redirectUrl has a search param it redirects to page showing 502 Bad Gateway

### Steps to reproduce the behaviour:
1. Sign In
2. Create an api
3. Copy the url with query param saying `?editName=true`
4. Sign out
5. Paste and go to the url. It goes to the sign in page. Sign in with creds.
6. It redirects to a page showing 502 Bad Gateway

[Loom recording](https://www.loom.com/share/f7411995227247f3ae0e26f658cc03af)

**Comment by rishabhsaxena** [comment]
This has been fixed
