### ISSUE TITLE
[Bug]: Cross Referencing: Unable to re -authenticate ghseet in reconnect datasource modal when user import the JSON and Git connected apps

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#34917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to re -authenticate ghseet in reconnect datasource modal when user import the JSON and Git connected apps. the user is redirected to https://release-cs.appsmith.com
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/697c08f7-1b73-4e67-84b4-61c71b1f8464">

### Steps To Reproduce

1. go to https://ee-4056.dp.appsmith.com
2. Import a git connected app
3. Noe authenticate the git connected app
4. The user is redirected to release-cs

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

deploy preview

**Comment by btsgh** [comment]
Tested and found to be fixed now.
