### ISSUE TITLE
[Bug]: Raising to track Airgapped TBP failure due to RBAC tests

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#34930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are failures in the Airgapped TBP starting 15th July. This bug is raised to track the same. 

cypress/e2e/EE/Enterprise/RBAC/RBACFunctionalTests/ViewPermission_spec.js
cypress/e2e/EE/Enterprise/RBAC/RBACFunctionalTests/MultiplePermissionApplicationResources.js

Cypress dashboard [link](https://internal.appsmith.com/app/cypress-dashboard/run-details-65890b3c81d7400d08fa9ee5?workflowId=9932032727&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail)
TBP [link](https://github.com/appsmithorg/appsmith-ee/actions/runs/9932032727)

### Steps To Reproduce

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1721017358172029

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by riteshkew** [comment]
Resolved as per the slack thread.
