### ISSUE TITLE
[Bug]: Cross Referencing: On adding a template from a branch, the reconnect modal comes up

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#34931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a template from a branch in the cross referencing DP, the reconnect modal comes up, instead of the pages getting created directly and getting redirected to the app.

### Steps To Reproduce

Create a git connected app. 
Create a branch
From the branch, add a template - say the Vehicle Maintenance app template.
Note that user is taken to the reconnect modal, instead of being redirected directly to the application.

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/13cb6b1e-d006-422a-8f7f-11b70b576354

### Version

Cloud

**Comment by btsgh** [comment]
Note: This issue is existing even on a non-git connected app on this DP, when we add a page from template, from inside the application .. instead of redirecting into the application, the reconnect modal comes up

**Comment by btsgh** [comment]
So if there is a datasource that is not configured and is used by the app in a query/widget, then the reconnect modal comes up. This behavior is seen on release also as Nidhi explained earlier. Wanted to understand here, since there is a fix that you have merged, is there anything else that I shud be testing here? Or shall I move this issue to release ? @brayn003

**Comment by brayn003** [comment]
@btsgh let's move the issue to release. We can verify this, once we have merged to release

**Comment by btsgh** [comment]
Noted. Done

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by nidhi-nair** [comment]
Closing as expected in the scenario mentioned
