### ISSUE TITLE
[Bug]: Cross referencing: Redirection after adding a building block is incorrect. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#34934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On adding a building block from template section into a page, user is redirected to a wrong page, instead of the newly added page/pages

### Steps To Reproduce

1. In a git connected app, go to a branch, add a building block from a template
2. Note that on adding and going to the application, instead of redirecting to the newly added page, user gets redirected to an already existing page

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/2af85c0c-d4ce-4e11-9afe-dbfb330d4edd

### Version

Cloud

**Comment by brayn003** [comment]
Should work fine now

**Comment by btsgh** [comment]
This is working fine on the latest DP
