### ISSUE TITLE
[Bug]: A-force -> Query timeout after v1.29 upgrade

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#34932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A Trial customer is complaining that after v1.29 upgrade they started getting query timeouts. Is there any change we shipped in the last few releases that might’ve caused this? FYI - they recently upgraded their setup to v1.29 K8s + HA.
https://theappsmith.slack.com/archives/C074GD1DP1A/p1720698651642659?thread_ts=1720694634.187349&cid=C074GD1DP1A

### Steps To Reproduce

A Trial customer is complaining that after v1.29 upgrade they started getting query timeouts. Is there any change we shipped in the last few releases that might’ve caused this? FYI - they recently upgraded their setup to v1.29 K8s + HA.
https://theappsmith.slack.com/archives/C074GD1DP1A/p1720698651642659?thread_ts=1720694634.187349&cid=C074GD1DP1A

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self hosted - 1.29.0

**Comment by sneha122** [comment]
Checked the logs provided by user and they were indicating about the JSObject function not found in DB issue, later on realised that there are actually two issues:
- One with query timeouts (For which we are waiting for heap dump and comprehensive logs for this from customer) -> [Conversation link](https://theappsmith.slack.com/archives/C0341RERY4R/p1721039279648029?thread_ts=1720700775.396329&cid=C0341RERY4R)
- Other issue is with JsObjects function not defined - [Conversation](https://theappsmith.slack.com/archives/C0341RERY4R/p1721036524418079?thread_ts=1720700775.396329&cid=C0341RERY4R) - [Similar issue in progress](https://github.com/appsmithorg/appsmith/issues/34681)

**Comment by sneha122** [comment]
Moving it to blocked state till we receive further information on this so that we can take next course of action.

**Comment by rohan-arthur** [comment]
Follow-up today yielded no further news; will reopen if we get further updates.
