### ISSUE TITLE
End of R1 widget + canvas polish tasks

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#34949]

**Comment by somangshu** [comment]
@ramsaptami our mental model is to have milestones corresponding to the roadmap project / sub-projects. This way we know the scope we are prioritising and actually make progress. You can set additional guideline around the same. Like get every engineer to reserve 25% of the time for the polish milestone. Based on this heuristic you can also divide all issues into phases. 

Kindly put this in order
