### ISSUE TITLE
[Bug]: The error is displayed when user tries to push groups through SCIM

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#34959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The error is displayed when user tries to push groups through SCIM
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5021ab88-bb57-43df-b1bf-f73003ea2496">

### Steps To Reproduce

Note: We ahave already connected appsmith with Okta IDP
1. go to okta .com
2. Create a new group and  and push it to appsmith
3. The group will be displayed but unable to edit it 
4. But when we see in okta it seems that groups push is failed

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by riteshkew** [comment]
Resolved as part of v1.33
