### ISSUE TITLE
[Bug]: GraphQL Logo seems to be incorrect

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#34961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The GRAPHQL plugin logo is shown same as RestAPI plugin. 

### Steps To Reproduce

<img width="677" alt="Screenshot 2024-07-16 at 1 13 33 PM" src="https://github.com/user-attachments/assets/7f5e4f5f-5395-4631-a728-4b635d329d02">

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by shubham88fru** [comment]
Hi @rohan-arthur , I can work on fixing this as my first open source contribution. Can I start working on this?

**Comment by rohan-arthur** [comment]
@shubham88fru go for it. The code should already have the correct assets, let me know if you need help

**Comment by shubham88fru** [comment]
Thanks @rohan-arthur! I'll first setup the project on my local and fix this bug.

**Comment by shubham88fru** [comment]
Hi @rohan-arthur  can you guide me as to how do I add cypress test results in the PR description for this issue? I see other PRs for different issues have added the result of cypress test. Thanks.

**Comment by shubham88fru** [comment]
PR created
