### ISSUE TITLE
[Task]: Add linting checks for JSON configs to avoid parsing errors

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#34969]
### SubTasks

Recently we observed that due to an error in the setting JSON, the smart JSON substitution toggle was removed from the UI.
Ref: https://theappsmith.slack.com/archives/C040LHZN03V/p1721124893238579

**Comment by raza001** [comment]
pls provide access of slack if possible

**Comment by NilanshBansal** [comment]
Moved to in progress now, as this is getting prioritised now.
