### ISSUE TITLE
[Bug]: Export table XLSX

### ISSUE THREAD

**Issue by alessandro-gh79** [appsmithorg/appsmith#34967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In my application I created a table that also has date-type fields. Using the download button of the table in XLSX format, the date column when I open it in Excel is treated as a string.
How do I solve it? I've tried various ways with Javascript to no avail.

### Steps To Reproduce

Create Table with data column.
Download XLSX file.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Appsmith Community v1.26

**Comment by Nikhil-Nandagopal** [comment]
@alessandro-gh79 the table downloads data using the display format in the table. You can simply edit the column and change the display format to the format you want to download the date in, or add a hidden column that has a separate display format, or implement download separately as a button

**Comment by Nikhil-Nandagopal** [comment]
@alessandro-gh79 I think you just need to change the column type in excel after you download the file
