### ISSUE TITLE
[Feature]: Authentication method SAML and/or OIDC optional for business model

### ISSUE THREAD

**Issue by leuedaniel** [appsmithorg/appsmith#34998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great if the authentication functionality via SAML and/or OIDC and possibly also provisioning could be ordered as separate additional packages to the business model. In our case, we currently use Appsmith locally in the business model and would still need SAML or OIDC to authenticate our users and connect them to our existing Keycloak system. However, just to cover this functionality does not justify us booking the Enterprise Model. It would therefore be great if we could only book this functionality at an additional cost to our Business Model.

### Why should this be worked on?

Currently, as in our case, small companies such as start-ups or sports associations work with the business model because we cannot afford the enterprise model. With this feature, such customers could book an additional service and implement individual functionalities. The customer would be happy as they could implement their projects and Appsmith could sell a little more, which is not the case in our case today.

**Comment by Nikhil-Nandagopal** [comment]
@leuedaniel have you spoken to our sales team and asked for a custom pricing tailored to your use case?

I'm going to close this issue because it's not a feature request but rather a request to enable a feature on a separate plan. You can write to sales@appsmith.com and see if this is possible.
