### ISSUE TITLE
[Bug]: appsmith backup fails while taking backup

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#34996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to take a backup of appsmith we see that it fails. 

However, when we try 
```
export APPSMITH_DB_URL=mongodb://appsmith:YQrNSIqBadOHG@localhost:27017/appsmith

root@ee240a85f275:/opt/appsmith# appsmithctl backup
.
.
Finished taking an encrypted backup archive at /appsmith-stacks/data/backup/appsmith-backup-2024-07-17T11-38-20.213Z.tar.gz.enc
Starting the cleanup task after taking a backup.
Cleanup task completed.
```

the value into APPSMITH_DB_URL as mentioned [here](https://github.com/appsmithorg/appsmith/blob/a46c7311790c0f8a68bc2ea28ada67333e9d8a88/deploy/docker/fs/opt/appsmith/utils/bin/mongo_shell_utils.js#L9) is not computed correctly 

### Steps To Reproduce

login to a container using 
```
sudo docker exec -it -u root ee240a85f275 bash
```
and do 

```
root@ee240a85f275:/opt/appsmith# appsmithctl backup
Available free space at /appsmith-stacks
4349689856


Exporting database
2024-07-17T11:41:40.201+0000	error parsing command line options: error parsing uri: scheme must be "mongodb" or "mongodb+srv"
2024-07-17T11:41:40.201+0000	try 'mongodump --help' for more information
Starting the cleanup task after taking a backup.
Cleanup task completed.
```

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

selfhosted

**Comment by alfonsoasenjo** [comment]
the issue starts on 1.29, previous versions working fine
