### ISSUE TITLE
[Bug]: file upload to s3 via REST API results in corrupted file

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#34991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From [here](https://theappsmith.slack.com/archives/C0341RERY4R/p1721146073809139)

The user's unique requirement (due to some security restrictions in their company) is to upload files to s3 not via appsmith's native s3 integration, but via [REST API](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAPI.html).

They want to upload excel files.
The query apparently runs successfully with base64 format and content-type as file type i.e. for excel "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

However, the file upload occurs, but the file ends up getting corrupted.

### Steps To Reproduce

NA

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

CE v1.29

**Comment by rohan-arthur** [comment]
have asked the user for data:
1. does the thing work on postman
2. try uploading a dummy excel file, and share the original and corrupted files with us

**Comment by rohan-arthur** [comment]
haven't heard back in more than a week, will reopen if/when needed

**Comment by richardwhatever** [comment]
i have this same problem.

**Comment by Nikhil-Nandagopal** [comment]
@richardwhatever please share the file details and a sample app that we can use to debug the issue
