### ISSUE TITLE
[Bug]: On triggering a workflow from a feature branch, an error is seen

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#34994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="868" alt="image" src="https://github.com/user-attachments/assets/4f4859be-a742-437d-863c-81d2a5cd5a81">
On triggering a workflow from a feature branch, the above error is seen

### Steps To Reproduce

1. Create a git connected app
2. Create a workflow (For example, a workflow that sends a slack message) and publish it
3. Trigger the workflow from the main branch of the git connected app. Notice that the workflow gets triggered
4. Similarly, trigger the same workflow from a branch. Notice that an error is seen

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

v1.31

**Comment by brayn003** [comment]
Unable to replicate this, I think this is solved while solving other issues. Please recheck?

**Comment by laveena-en** [comment]
This has been resolved

**Comment by laveena-en** [comment]
Re-opening this issue as it has resurfaced.

**Comment by laveena-en** [comment]
Re-opening this issue as it has resurfaced.

**Comment by laveena-en** [comment]
Closing this issue as it has been fixed by CR changes https://theappsmith.slack.com/archives/CTHN8GX5Y/p1723126256283339

**Comment by laveena-en** [comment]
> Closing this issue as it has been fixed by CR changes [theappsmith.slack.com/archives/CTHN8GX5Y/p1723126256283339](https://theappsmith.slack.com/archives/CTHN8GX5Y/p1723126256283339)
