### ISSUE TITLE
[Bug]: Action execution should only trigger after all entities are saved

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#34995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

 Body + update action one set has to finish before the second set of body + update action occurs.

**Context**: The user is getting the message `Appsmith Server is taking too Long to Respond` when editing JS Objects or working in the Page editor with widgets. It happens when saving or just loading queries.
The root cause is that the JS Object did not finish saving before the user tried to execute another action. To work around this problem, when the saving of a particular JS Object is still in progress, users need to wait until it finishes before moving to another page/entity or making new changes in the UI.

More information in [this ticket](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=2336) and [Slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1720801738024479).

### Why should this be worked on?

We need to improve the user experience if the JS Object that was edited is not saved yet when a new action is done.

**Comment by nghialm269** [comment]
Hi, I've been seeing the same message (`Appsmith Server is taking too Long to Respond`) a lot recently while working on my app.

Whenever I edited a jsobject file (~300 lines), a `Saving` spinner showed up at the top, and the message appeared after a while (I guess the save request timed out after 20s or so).

After too many timeouts like that, the code editor refreshed itself (it scrolls to the top) and my changes were lost.

I've tried to split the jsobject file into smaller files as advised, it helps a bit but not too much.

For some more context, when I tried to create a new jsobject in the same app and add a new line, it took ~3s to save. This app has 2 jsobject files with 300 lines, 1 with 100 lines, and 4 with 50 lines.

When I tried the same with a smaller app (1 file with 15 lines), it took ~300ms to save.

**Comment by rishabhrathod01** [comment]
This issue title and description got mixed up of multiple different issues, i have create separate issues for each problem 
- JSObject update taking too long - https://github.com/appsmithorg/appsmith/issues/35542
- Creation of identical names JSObject - https://github.com/appsmithorg/appsmith/issues/35385
