### ISSUE TITLE
[Bug]: Cross referencing: Unable to see Response and Schema tabs in the shared app.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I added a snowflake crud page on one of the applications, I was unable to see the schema and response tabs, though the number of records showed up correctly on the right side. In split pane view, none of the tabs were seen at all. 

### Steps To Reproduce

https://jam.dev/c/d77dad31-8193-4ff2-a5e1-339dd96df896

This seems to be seen on a couple of applications. 
App [link](https://ee-4056.dp.appsmith.com/app/cr-newapp/oauthdropbox-668ffe42504732047357a7fb?branch=master)
Have added Nidhi as admin to the workspace.
<img width="1418" alt="Screenshot 2024-07-17 at 7 29 34 PM" src="https://github.com/user-attachments/assets/51a0f5f5-d89c-496d-9d88-48f8d1a05508">
<img width="631" alt="Screenshot 2024-07-17 at 6 40 20 PM" src="https://github.com/user-attachments/assets/c0f8643d-69c4-4051-9706-36e39e0f6e82">

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by shadabbuchh** [comment]
Able to replicate this. Query runs fine on the master branch but on another branch no schema is displayed.
https://jam.dev/c/55ff7646-4bfe-44a8-8a47-b3b4100dcd23

**Comment by btsgh** [comment]
Seems to be fixed on the latest DP.
