### ISSUE TITLE
[Task]: Add support for JIRA integration

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#35038]
### SubTasks

One of our enterprise customers has requested JIRA integration. In order to add this integration via SaaS manager app, we have to do following steps:

Get the swagger API json for JIRA
Use this app: https://app.appsmith.com/app/saas-contributions/page1-6698a73044326f091c3971d9 to contribute the new integration, verify all details after importing swagger and submit.

**Comment by NilanshBansal** [comment]
I am interested to contribute

**Comment by NilanshBansal** [comment]
I am interested to contribute.

**Comment by rohan-arthur** [comment]
ignore: dummy issue created for hackathon
