### ISSUE TITLE
chore: Fix typos in the codebase.

### ISSUE THREAD

**Issue by shubham88fru** [appsmithorg/appsmith#35049]
### SubTasks

There are multiple typos in the production codebase. E.g. method and variable names in Java files, test files etc.

**Comment by shubham88fru** [comment]
@Nikhil-Nandagopal can I work on correcting the typos in codebase and create a PR?

**Comment by Nikhil-Nandagopal** [comment]
@shubham88fru no thanks this will likely cause more problems that it will solve
