### ISSUE TITLE
[Feature] S3: detect non base64 encoded data and return error if the file type is multimedia

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3507]
## Summary
detect non base64 encoded data and return error if the file type is multimedia

## Motivation
Users are not able to manually configure the base64 option and send non encoded data to the server when encoded data is required. By throwing an exception we can make user aware of the need to encode data.

**Comment by Nikhil-Nandagopal** [comment]
Fixed in #3514
