### ISSUE TITLE
[Bug]: Able to see uncommitted changes on discarding changes 

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#35089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we try to discard a changed, upon successful doing so we are able to see uncommitted changes.

### Steps To Reproduce

1. On a git connected app, create 2 branches from master (e.g. test & merge)
2. Make changes to the theme in merge branch and commit them.
3. Now add a page & discard this change.

**Actual:** Changes should get discarded successfully & no further uncommitted changes should be seen.
**Expected:** Upon successfully discarding changes, we are still able to see uncommitted changes.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/e807bf4b-ae34-48e3-8d7d-6c5d55bd02ba

### Version

Cloud

**Comment by nidhi-nair** [comment]
@shadabbuchh please provide the usual amount of data here for uncommitted changes kind of bugs

**Comment by shadabbuchh** [comment]
@nidhi-nair 
App URL: https://app.appsmith.com/app/untitled-application-1/page1-66b5c6187f8a1a08d62c0e42?branch=otherBranch
Repo: https://github.com/shadabbuchh/prodFor35089
Diff: https://github.com/shadabbuchh/prodFor35089/commit/1a5134b4fed7cf1fafa5b7b3c1f12b18c548fade
<img width="1440" alt="Screenshot 2024-08-09 at 1 11 32 PM" src="https://github.com/user-attachments/assets/34a65e35-efb1-4009-909f-1eda3102a0af">

**Comment by riteshkew** [comment]
Not reproducible within the latest version v1.41.
