### ISSUE TITLE
[Feature]: File Picker Widget Exceeds Maximum File Count Limit After Update

### ISSUE THREAD

**Issue by saiprabhu-dandanayak** [appsmithorg/appsmith#35081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
In the current implementation of the **FilePickerWidget**, users can select and upload files using the Uppy library. However, when the maximum number of files (**maxNumFiles**) is updated and excess files are not being **removed** from the selected files and the **displayed file count** does not accurately reflect the **current number** of selected files. This leads to a **discrepancy** between the **actual** and **displayed** file count, potentially causing confusion for users.

### screenshot
![image](https://github.com/user-attachments/assets/248be50b-a947-4cec-a340-2f4171f25546)

### Note
whenever we change the **maxNumFiles** say from 3 to 2 still the widget shows 3 files selected and if we click on the widget we can see 3 files , but if we deployed the application and try to upload the 3rd files it says `you can upload only 2 files` 

![image](https://github.com/user-attachments/assets/88806aa7-7e2b-43ad-a62e-aaa33f8836e2)

### Actual behavior expected
Just as the application correctly handles the  **maxNumFiles** configuration upon deployment, it should also dynamically adapt to any updates to this limit in real-time.

### Steps to reproduce?

-  Drag and drop **FilePicker** widget.

- In the property pane section for **Max no of files** field enter value as **3** and upload **3 files**.

- Now Change the value of **Max no of files** to **2** , and check the widget it still shows 3 files uploaded and in the selected files also.

**Comment by daaliachhak17** [comment]
created issue in Jira-https://zemoso.atlassian.net/browse/TNOSB-413

**Comment by Nikhil-Nandagopal** [comment]
This is not an issue, the configuration is for future usage of the widget and not to manipulate past usage. Any fixes will just complicate the code and cause more issues
