### ISSUE TITLE
[Bug]: `Internal server error` When Logging in with GitHub

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#35094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

GitHub login does not work. Users trying to log in via GitHub OAuth on Appsmith Cloud, get the following error:
```
{"responseMeta":{"status":500,"success":false,"error":{"code":"500","message":"Internal Server Error"}},"errorDisplay":"500: Internal Server Error"}
```

[Ticket](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=cnv_1c8gyw98)

### Steps To Reproduce

1. Go to https://app.appsmith.com/user/login
2. Click the GitHub login button.
3. Enter the GitHub credentials and proceed.
4. Note the error message. 
Refreshing the page or accessing https://app.appsmith.com/ again does not help. Users are not able to log in with this method.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by rohitdoddapani** [comment]
Waiting for this fix. I struck here unable to log in now

**Comment by zbezdac1f** [comment]
me either. i tried all ways to clear my cookies and cache, but still unable to login. please fix it

**Comment by webeasymail** [comment]
Please fix it as soon as possible, I am unable to use my application

**Comment by zbezdac1f** [comment]
wow! problem has been solved. now i am able to login through github. thank you very much
