### ISSUE TITLE
[Bug]: Informative window for suggestions on autocomplete doesn't change on hover.  

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#35111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While writing code the autocomplete window shows up and the suggestion in focus is paired with a second window that provides additional information about the suggestion. 
When you navigate across the autocomplete menu using keyboard the information window also updates based on the suggestion in focus but when hovering via a mouse the information window doesn't changes as per the hovered suggestion within the autocomplete.

https://github.com/user-attachments/assets/b23f6b58-8b69-4d85-8b7c-dcc9719670c0

### Steps To Reproduce

1. Open a JsObject.
2. Start typing code till the autocomplete shows up. 
3. Hover over the autocomplete options. 

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud/Self hosted

**Comment by Nikhil-Nandagopal** [comment]
That is expected and all IDEs behave this way
