### ISSUE TITLE
[Feature]: Editable scroll bar

### ISSUE THREAD

**Issue by Iamkaterynavashchenko** [appsmithorg/appsmith#35130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the ability to edit the scroll bar, including changing its color and width, to improve visibility and usability with different design themes. Additionally, propose to implement horizontal table scrolling with a mouse, similar to touchpad functionality, allowing users to easily view additional table columns by hovering over the table and scrolling

### Why should this be worked on?

Enhancing the scroll bar customization and introducing mouse-based horizontal table scrolling are essential improvements that would significantly boost user experience. The ability to adjust the scroll bar's color and width would ensure that it stands out against any theme, making the application more accessible and easier to navigate. Moreover, enabling horizontal scrolling with a mouse, just like with a touchpad, would harmonize the user experience across different devices. This feature is particularly crucial for users who rely on a mouse, as the current scrolling limitations are cumbersome. Implementing these enhancements would make the application more intuitive and accessible to a broader range of users.

**Comment by Nikhil-Nandagopal** [comment]
@Iamkaterynavashchenko we aim to simplify app development and therefore we will ensure that the scrollbar works well against any theme by default without app developers needing to configure it. Feel free to make suggestions where it does not today.
