### ISSUE TITLE
[Epic]: Fix Cypress Flakiness - Query&JS Pod

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#35131]
### Objective

This epic aims to resolve all the cypress flaky issues linked to the Query&JS Pod. The list of all the flaky tests is present here
https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master&environment=production

### Success Metrics

| Metric         |
| -------------- |
| Remove the flakiness for all the 15 cypress tests associated with the Query&JS Pod    |

### Prioritised User Stories

| User Story    |
| ------------- |
| As an engineer of appsmith, I should be confident that there is complete cypress coverage of my code |

### RACI matrix

| Role | People |
| ------------- | ------------- |
| Responsible   |   @NilanshBansal , @sneha122 , @AmanAgarwal041, @rishabhrathod01             |
| Accountable   |    @NilanshBansal            |
| Consulted     | @ApekshaBhosale @rohan-arthur  |
| Informed      |     @nerbos @carinanfonseca  @rohan-arthur          |

**Comment by AmanAgarwal041** [comment]
All the issues are fixed!
