### ISSUE TITLE
[Bug] [Rich Text Editor]

### ISSUE THREAD

**Issue by hawisizu** [appsmithorg/appsmith#3515]
## Description

[What happened]

RTE set to show a field of an object stored in the Appsmith Store. 

Changing the object: RTE sometimes updates, sometimes not. See attached video: 

Also, I still see problem with new BR being inserted between elements of bullet point lists or numbered list, which was supposed to be already solved. (https://github.com/appsmithorg/appsmith/issues/2852)

See video of the problem
https://drive.google.com/file/d/12y7YnnCX-JF7kWlfo-TBDtc79EHBUQDe/view?usp=sharing

Not specially urgent, will use a non rich text editor for now

**Comment by Nikhil-Nandagopal** [comment]
@hawisizu this is solved in our release branch as this just got merged in #3055
