### ISSUE TITLE
[Bug]: After successful auto-commit we still see some uncommitted changes

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After successful auto-commit we still see some uncommitted changes
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/09c487d1-2ce5-4bf8-a3ca-2ade85780509">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/cadc52fc-da03-4131-bfe0-01a068bdc802">
Diff we saw after committing that unknown change
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/096ebe11-4c1b-4267-80ba-a3d0937bbad8">

### Steps To Reproduce

1. login to release.app.appsmith.com
2. Open any git connected app which is 4 weeks old
3. the auto commit happens successfully 
4. now we see some uncommitted change
5. try to discard it it doesnt go away 

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

v1.33

**Comment by shadabbuchh** [comment]
App: https://app.appsmith.com/app/regression-apr-15/page1-661d22f237b5e72878311adf/edit?branch=master
Diff link: https://github.com/RakshaKShetty/regression-apr-15/commit/1f180e452715cec913334558dc759f0f3604a483
