### ISSUE TITLE
[Bug]: Turning on background on the statbox alters the alignment of other widgets in the zone

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#35185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Turning on background on the statbox alters the alignment of other widgets in the zone & changes the zone colour

![image](https://github.com/user-attachments/assets/74560577-d346-4f34-ae42-5712656a77ac)
![image](https://github.com/user-attachments/assets/569e909f-3c86-4b43-a556-d28012b15e61)

### Steps To Reproduce

1. Drop a statbox and paragraph widget on the same zone as seen in the screenshot
2. Observe the behaviour of paragraph alignment when visual separation is toggled on the statbox
3. Observe the colour of the zone background when above step is performed

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by ichik** [comment]
@ramsaptami the control is called “visual separation”, therefore it produces visual changes. This is intended behavior.

**Comment by ramsaptami** [comment]
Agreed, but the visual change can't be markedly different from the neighboring zone. It's visual disharmony at this stage.

Also, the turning on background separation causes extra space to be added to the top of the paragraph widget seen above, which is another part of the issue here.

**Comment by ramsaptami** [comment]
Adding a clear screenshot to help it's case
![image](https://github.com/user-attachments/assets/c7cdebd0-bd79-4961-b250-b314288b672e)

**Comment by ichik** [comment]
> the visual change can't be markedly different from the neighboring zone.
Different visual settings produce different visual results. Those are not disharmonious.

> turning on background separation causes extra space
The option is not called “turning on background”. It is called “visual separation”. The spacing is needed to produce said visual separation. Subtly difference just in the background is not going to be sufficiently perceptible to produce the visual separation.

This is working as intended.
