### ISSUE TITLE
[Bug]: Mongodb find query with limit = 0 behaviour inconsistent with mongodb docs

### ISSUE THREAD

**Issue by tejasahluwalia** [appsmithorg/appsmith#35182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Running a find query with limit specified as 0, returns no results. 

This is unexpected because according to mongodb docs;
> A [limit()](https://www.mongodb.com/docs/manual/reference/method/cursor.limit/#mongodb-method-cursor.limit) value of 0 (i.e. [.limit(0)](https://www.mongodb.com/docs/manual/reference/method/cursor.limit/#mongodb-method-cursor.limit)) is equivalent to setting no limit.

https://www.mongodb.com/docs/manual/reference/method/cursor.limit/#zero-value

Using `{ "limit": 0 }` in a raw query works as expected and returns all docs in the collection.

### Steps To Reproduce

1. Create & run a find query for a mongodb datasource with limit = 0

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Limit is meant to obfuscate that logic to simplify the query for the user

**Comment by tejasahluwalia** [comment]
Thanks for the response. 

Obfuscating doesn't mean it should change the logic, right? 
Limit = 0 in raw query - All results as expected
Limit = 0 in form query builder - Empty response

As a user it made me feel like I was making a mistake when appsmith was changing the logic. Happy to work on a PR.
Maybe a line in the docs for the time being about this would be helpful?
