### ISSUE TITLE
[Bug]: Postgres migration: An internal server error comes up on trying to login with google sso

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On setting up SSO with google authentication, I get an internal server error on trying to login with google sso

### Steps To Reproduce

https://jam.dev/c/da8faa8e-f450-4a8c-be6c-145b440e5202

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted

**Comment by RakshaKShetty** [comment]
Same issue with OIDC login
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f9fdb00f-f809-410b-84aa-5ab172660f32">

**Comment by abhvsn** [comment]
@RakshaKShetty @btsgh this has been fixed with the updated DP can we verify once.

**Comment by RakshaKShetty** [comment]
The issue is fixed

**Comment by RakshaKShetty** [comment]
@abhvsn , @btsgh currently only SAML has a issue with Local and we are not able to login, lets try this scenario in DP. Same issue exists in release .
[backend-58dcc31ac393.log](https://github.com/user-attachments/files/16557287/backend-58dcc31ac393.log)
