### ISSUE TITLE
[Bug]: Zone dotted highlight is not showing up on new anvil apps

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#35231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Zone dotted highlight is not showing up on new anvil apps

![image](https://github.com/user-attachments/assets/1aab67ef-b4c5-428c-922d-57b9359952d5)

### Steps To Reproduce

1. Add 2 zones to a section
2. Use space distribution handles to move it around
3. Notice the dotted highlight is missing

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

cloud

**Comment by jsartisan** [comment]
What is the expected behaviour here? Any idea? @riodeuno @KelvinOm
