### ISSUE TITLE
[Feature]: Horizontal list and grid list widget

### ISSUE THREAD

**Issue by leonlazic** [appsmithorg/appsmith#35241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would really like to see two alternate versions of the list widget. A horizontal list widget and a grid list widget. 

**Grid list** would be great for displaying photos or dense item/service/product selection options.
Example of a grid list:
![image](https://github.com/user-attachments/assets/24f77b3f-f776-442f-894a-0728a9ebdd02)

**Horizontal list** would be great for creating pricing plans or also showing photographs.
Example of a horizontal list:
![Screenshot](https://github.com/user-attachments/assets/28a9019b-09e5-40be-955a-90f31aa2b980)

### Why should this be worked on?

The current vertical list uses up a lot of space vertically. To use the ui efficiently we either lower the height of the list item making it quite similar to a table then or you narrow the width of the list and put some ui on the side. But most of the time putting ui side by side isn't the most flattering or logical solution. Much better option would be to dense up the list items by either breaking them into multiple columns with the grid view or to make a horizontal list. That way you can keep the top to bottom flow of the page without wasting so much space.

**Comment by Nikhil-Nandagopal** [comment]
@leonlazic we already have these issues tracked here so you can leave you comment on the original issue #2389 #9475
