### ISSUE TITLE
[Feature]: Scrollable list

### ISSUE THREAD

**Issue by leonlazic** [appsmithorg/appsmith#35242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A scrollable list instead of a paginated one would be a great addition. And option to either scroll or have pages. A trigger event when a certain list item show in the viewport could be used to still paginate the query in the back end in order to avoid problems with large queries in comibnation to a scrollable list. Would also be a perfect addition to [this horizontal list request](https://github.com/appsmithorg/appsmith/issues/35241).

### Why should this be worked on?

Scrolling trough options is faster and easier for the user.

**Comment by Nikhil-Nandagopal** [comment]
@leonlazic we already have these issues tracked here so you can leave you comment on the original issue #6293
