### ISSUE TITLE
[Feature]: allow the user to choose the number of data items per page

### ISSUE THREAD

**Issue by clairearondel** [appsmithorg/appsmith#35246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It will be nice to have the total records disconnected  from the pageSize. Or, we can choose the pageSize with an the value of an Input for example. Or, simply not see the "Total records" and we can put our "total records" in a text widget.

### Why should this be worked on?

I've connected a table widget (server side pagination) with a custom widget (Leaflet map) and users may need to see more data displayed on the map. So they need to be able to choose the number of data per page.

If I put: SELECT * from mytable limit {{Input1.text}} offset({{Table1.pageNo - 1}} * {{Input1.text}})
And a : Select count(*) from my table for Total Records with {{getCountDataTable.data[0].count}}
The number of records will be OK, but not the number of pages. 

So I had to do: {{
Math.round((getCountDataTable.data[0].count / Input1.text) * Table1.pageSize)
}} the number of pages is OK, but not the number of records.

This doesn't inform the user very well. I see this feature request https://github.com/appsmithorg/appsmith/issues/2230 but I don't know how can I do otherwise.

**Comment by Nikhil-Nandagopal** [comment]
@clairearondel you can simply set {{Table1.pageSize}} as the limit
Turn on server side pagination and set the total records based on a new query and it will work. Here's a guide for this:
https://docs.appsmith.com/build-apps/how-to-guides/display-search-and-filter-table-data

**Comment by clairearondel** [comment]
@Nikhil-Nandagopal I want to allow to the users to choose the number of data per page. So I put an Input widget and they can choose like that. So, for example, the user choose 20 in the input limit but the PageSize is 13. The user can scroll through the widget table. 
If the user can change the page size, it could also be useful

**Comment by Nikhil-Nandagopal** [comment]
@clairearondel so you can read the limit from the input and that will make the page scroll if the server side pagination option is turned on

**Comment by clairearondel** [comment]
Yes but the Total records is not good.
For example, i have 100 data. I put a limit of 20 data per page with a pagesize of 13 and I see 60 records next to the page. But it should be 100 records and not 60. I don't know if I explain well.

**Comment by Nikhil-Nandagopal** [comment]
@clairearondel under pagination section there is a total records field. Create a query to count the number of records in the database and return the count to that field. It will then return 100.

**Comment by clairearondel** [comment]
I have my query : "Select * from myTable" and my query count "Select count(*) from myTable" (I have 100 records)
And I put an Input Text "Input1" where I can put a number of data per page. I put : 20 
On my PageSize, I have : 12

If I put on Total Records : {{getCountDataTable.data[0].count}}, I have 100 records and 9 pages but Pages 6 to 9 are blank.
![Capture d’écran 2024-07-30 094636](https://github.com/user-attachments/assets/b6ef6725-331e-4fb9-981d-a2ea48cb686f)

If I put on Total Records to avoid seeing empty pages : {{Math.round((getCountDataTable.data[0].count / Input1.text) * Table1.pageSize)}} I have 60 records (but it's wrong, I still have my 100 data) and 5 pages. No empty pages.
![Capture d’écran 2024-07-30 094538](https://github.com/user-attachments/assets/9f8dfe0b-b675-4b67-a818-10ff97305bfb)

**Comment by rjackson-achieva** [comment]
Seeing the same issue here. I can manually set how many rows get returned in my query by passing in the value via a select widget. Lets say I want to return 50 rows for example. That works fine and I have 50 rows until I have to page to the next page, but to @clairearondel's point, This throws off the pagination. At the end of my dataset, I have blank pages because pagination thinks I'm using table1.pagesize in my query when in reality I'm passing in a "total records to display" in a select widget and is calculating incorrectly as a result. Is there a way to set the pagesize property that I'm overlooking?

**Comment by gonnsuarez** [comment]
+1 for this! with server side pagination enabled there should be a way to change the fixed auto calculated page size (number of rows that fits in the table size), and also changing that number should change the total calculated number of pages.
