### ISSUE TITLE
[Bug]: The fullyQualifiedName property is conflicting with the updated action name resulting in error

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#35261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the action object has a property `fullyQualifiedName` then on updating the action name, the `name` property and all the references to the action gets updated but the `fullyQualifiedName` remains the same. 
When we navigate to deploy mode it gives the updated references but gives the action name equal to `fullyQualifiedName` instead of the updated name, which results in the error of the action not defined.

### Steps To Reproduce

https://theappsmith.slack.com/archives/C040LHZN03V/p1722223771549209
https://theappsmith.slack.com/archives/C0341RERY4R/p1721834743033699

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Self Hosted

**Comment by sneha122** [comment]
Similar issue: https://github.com/appsmithorg/appsmith/issues/33651
