### ISSUE TITLE
[Bug]: Postgres migration: Queries created on Twilio integration does not seem to be working on this environment

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create an integration with Twilio with relevant details, the queries fail with 
```
Your query failed to execute:
401 Unauthorized from POST https://api.twilio.com/2010-04-01/Accounts/<apikey>/Messages.json
```

### Steps To Reproduce

1. Create a Twilio saas integration
2. Enter valid credentials for Twilio SID and Auth Token
3. Save and create a Create Message query [or List Message query]
4. Specify all the details like to / from phone numbers, message text etc. 
5. Run the query
6. It fails with 
`401 Unauthorized from POST https://api.twilio.com/2010-04-01/Accounts/<apikey>/Messages.json`
7. The same passes on production/release environments

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/174efd35-eb48-4ee4-8495-ee7373a9562b

### Version

Self Hosted

**Comment by AnaghHegde** [comment]
This fix is available on the dp

**Comment by RakshaKShetty** [comment]
Issue is fixed
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/70a10051-cacf-4721-9637-8ca459eec8a0">
