### ISSUE TITLE
[Bug]: Label key functions not working as expected

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith#35269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This worked on a version prior to 1.30, but the bug is present on 1.30 and 1.33.

When using a function to get a dynamic label key or value key, it is not interpreted as a key but instead as the label itself:
![image](https://github.com/user-attachments/assets/31eb05a8-9f86-417e-b7de-ccad058410b2)

### Steps To Reproduce

1. Create a select widget
2. Create a JS object called "test"
3. Create an array in the JS object "select: [{label: 'first label', key: 'first key'}]",
4. Bind the select widget's source data to {{test.select}}
5. Set the label key to JS
6. Enter the word "label" as the entry in label key
7. Note the widget now says "first label" in the dropdown
![image](https://github.com/user-attachments/assets/0e123d92-80bb-4dfb-81e1-418b32f7649e)

8. Enter a function that should return the string "label" as the entry in label key
9. Note that the widget now says "label" in the dropdown
![image](https://github.com/user-attachments/assets/0c604c8b-972a-44b7-82a3-17d285823163)

For some reason now returning a string 'label' is not being interpreted the same way as just writing 'label' in the box.

The reason I have this function there is because Appsmith gives me says there are errors in the log when the query that populates my source data hasn't been run yet.  I can just ignore the errors, I just added this length check so I could cut down on the number of displayed errors and hopefully only see the ones that matter.

However, if I actually did need to have a dynamic label or value for whatever reason, this would be a blocker.

It would also be nice if it just didn't give label key and value key errors if the source data length is 0 / empty.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self-Hosted 1.33

**Comment by jacquesikot** [comment]
@eedwardsSGS Thanks for reporting the issue, we'd be able to pick this up by mid August.
