### ISSUE TITLE
[Bug]: In the CR DP, If there is a package version update , unable to merge to other branches even though all version update changes are committed. 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#35286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After republishing a package, there appears to be updates in all the instances consuming it (version update), after commiting all those version update changes , merge is still showing errors 

### Steps To Reproduce

https://www.loom.com/share/dc70e5f07f7f456e90b4cbfd04bc1ec5

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud/Self-Hosted

**Comment by btsgh** [comment]
Note-  this works fine on release

**Comment by brayn003** [comment]
In summary, this is what's happening. When a package is published, all the modules get a version bump.
If the modules are connected to a git connected application. It reflects as a status change.
If the app has two or more branches, all the branches reflect the status change.
The issue occurs, if we try to merge b1 -> master
In both release-ee and dp the status change reflects in both the branches
In release-ee, after committing the changes in b1, trying to merge goes without any issues
In dp, after committing the changes in b1, trying to merge shows "uncommited changes in master" error

**Comment by nidhi-nair** [comment]
As discussed internally, this was actually expected behaviour that seems to have been broken on release and is now fixed with default resources project.

**Comment by btsgh** [comment]
Hey @nidhi-nair - haven't had a chance to recheck. this based on Rudra's comments.. keeping this open for a while more till I understand the issue pls.

**Comment by kamakshibhat-appsmith** [comment]
@nidhi-nair if this is the expected behaviour, version bump in packages would never get merged . What could be done here?

> As discussed internally, this was actually expected behaviour that seems to have been broken on release and is now fixed with default resources project.

**Comment by nidhi-nair** [comment]
We'd need to discard the change on the base branch and then trigger a merge, or commit that change first and then attempt merge @kamakshibhat-appsmith .. Sub-optimal behaviour perhaps, but the change needs to be intentional from the user's side.

**Comment by kamakshibhat-appsmith** [comment]
> As discussed internally, this was actually expected behaviour that seems to have been broken on release and is now fixed with default resources project.
