### ISSUE TITLE
[Bug]: Page settings not opening on first click after reordering pages

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#35304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the Page Settings section, if we rearrange the order of pages and then click on a page name, the settings for that page do not open on the first click. It requires a second click to access the page's settings.

### Steps To Reproduce

1. Go to an app with multiple pages.
2. Go to the Page settings section & reorder the pages.
3. Now click on the top most page.

**Expected:** The page settings of that page should open on the first click.
**Actual:** Page settings open on the second click.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/62f982c8-cbe4-44cf-b631-e8b86fe9c1a0

### Version

Cloud

**Comment by rohan-arthur** [comment]
Not able to reproduce both issues:
- the description, the page settings is shown with the first click
- from the video, there appears to be some glitches with page reordering, this too is not reproducible (attached video)

https://github.com/user-attachments/assets/e76e5814-7b9d-4c44-a688-586d161f7c3d

**Comment by shadabbuchh** [comment]
@rohan-arthur although the page settings now open on the first click, but I still see the glitch. You can try on this app:
[OldApp_DSTesting1.9.24 (1).json](https://github.com/user-attachments/files/16796892/OldApp_DSTesting1.9.24.1.json)

Video attached:

https://github.com/user-attachments/assets/eae9a19a-f16d-4c45-a4fd-d3ef8198622b
