### ISSUE TITLE
[Bug]:  As soon as I am attempting to rename the JS module instance or a JS object, some random instances are coming up

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#35313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="947" alt="Screenshot 2024-07-31 at 3 15 41 PM" src="https://github.com/user-attachments/assets/c7334006-fdf0-4b08-a328-5397cc6bf40c">

### Steps To Reproduce

1. Add any JS module instance
2. rename the instance
OR
1. Add any JS module instance
2. Add JS OBject
3. rename the JS Object

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Cloud/Self-hosted

**Comment by kamakshibhat-appsmith** [comment]
@brayn003  @nidhi-nair  Can we treat this as high priority ? Looks like quite a bad UX

**Comment by nidhi-nair** [comment]
This has been fixed
