### ISSUE TITLE
[Bug] Resetting the Table widget does not work well

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3531]
### Steps to reproduce the behaviour:
1. Drag a table
2. Drag a text widget
3. Bind the Text to the table's selected Row {{Table1.selectedRow}}
4. Drag a button
5. Reset the table widget
6. Notice that the text still contains data of the selected row fields but the fields are empty. The selectedRow should revert back to the original value when no row was selected

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal not able to reproduce this with the given steps.![QuickTime movie.gif](https://images.zenhubusercontent.com/603cb0a4edb533cdbad0d71a/11433a08-d8af-47ef-9984-792477468a4f)

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu bind it to a text widget. the text widget gets an empty object with keys but not values instead of only an empty object

**Comment by hetunandu** [comment]
That is the feature of Table widget selected row. It enables the autocomplete to work even when no row is selected

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu got it closing this since it's expected
