### ISSUE TITLE
[Bug]: Updates made to function name of branched JSObject results in internal server error . 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#35322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Updates made to function name of a branched JSObject results in internal server error . 

### Steps To Reproduce

1. Make sure `master` branch has one JSObject say `JSObject1`
2. branch out from master , say `test/1` branch
3. change the function name of JSObject1 (say `fun1` --> `funtest`) in the `test/1` branch
4. refactor action API is throwing error

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud/selfhosted

**Comment by btsgh** [comment]
This issue is happening on the latest released version as well. 
<img width="1260" alt="Screenshot 2024-07-31 at 8 48 59 PM" src="https://github.com/user-attachments/assets/d29262fb-e8a8-4929-9dd2-092ec62f5999">

**Comment by btsgh** [comment]
https://jam.dev/c/c91e4215-2ddc-4376-8c3a-cf29042dabab
