### ISSUE TITLE
[Epic]: Widget property setters

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3532]
## Summary
Create functions on widgets to set meta property values on them

## Motivation
1. Setting meta properties directly is useful for workflows that need to change values depending on user action dynamically. Instead of encoding this logic in the default value, it is easier to set this value directly. 
2. Users commonly attempt to set value by trying {{Button.text = "Confirm"}} but this doesn't work obviously

## Additional Context

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5ba6k)

**Comment by 4n70w4** [comment]
Hi! Any news?

**Comment by BigBrotherAlex2** [comment]
It's a pretty common basic feature. Appsmith NEEDS this.

**Comment by hetunandu** [comment]
Thanks for your interest @BigBrotherAlex2 and @4n70w4 

We will prioritise this again next meeting 
cc @ajinkyakulkarni @Nikhil-Nandagopal

**Comment by sfbrophy** [comment]
Yes, this should be considered a must-have. For comparison, Retool provides this functionality via their `setValue()` method on components.

**Comment by Rishabh-Rathod** [comment]
Needs Discussion on product level on this feature.
cc: @ajinkyakulkarni  @rohan-arthur

**Comment by ajinkyakulkarni** [comment]
We will be soon starting a discussion for this feature in this Q1 2022

**Comment by fibigerg** [comment]
Hi, I am confused. Is there any way to update input field programically (eg. setting 25% of a value of a different input field after clicking a button labeled 25%)?

**Comment by Nikhil-Nandagopal** [comment]
@fibigerg this is indeed possible by storing the value using {{storeValue('val', 25)}} in the onClick and binding the stored key to the input {{appsmith.store.val}}
This is an example app that achieves this
https://app.appsmith.com/applications/61e14d22eb0501052b9fae0b/pages/61e14d22eb0501052b9fae0e

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.5 |

**Comment by iwesselk** [comment]
I would like to add some more use cases and thought to get this better prioritized. I think every dev coming from frontend dev tries to do `MyLabel.text = "blah"` from a JSObject. OR `MyJSObject.textlabel = "blah"` where MyLabel set text to `{{MyJSObject.textlabel}}`, which doesnt' work.

On another issue (I am not finding it right now, but was related to the global JSObjects) it was mentioned trying to keep things simple and towards what a user will want to do. The above not working goes against that.

Commonly there are situations with app state where you would typically NOT want to store in the browser store. I don't have a good example at this moment, but I know that I have had situations where I don't want data in the browser store (where storeValue saves to, or is analogous to).

Depending on level of effort, another option like `storeTempValue` which has no persistence would help some. Better documentation that this is how you are expected to do this type of app state.

**Comment by ZackKnopp** [comment]
My use case was a "delete" button that, when clicked, displays a "confirm" button and text. Because I can't store and update state in the js object, or change state of a widget when a button is clicked, I have to store the state in the browser store.

**Comment by Nikhil-Nandagopal** [comment]
@ZackKnopp @iwesselk if you specify false in the 3rd parameter of storeValue, it will not use the local storage and only store it in the state. 
`{{storeValue('key', 'val', false)}}`
We do agree however that direct assignment will be a better option. Look forward to us picking this up soon!

**Comment by charles-bloomfield** [comment]
additional use case described here https://discord.com/channels/725602949748752515/1022536980166361149/1022536980166361149

**Comment by Svarto** [comment]
Any update here? Almost been a year and I agree with everyone that this is something that I as a frontend dev just intuitively expected to work. Would be great to get this prioritized

**Comment by Nikhil-Nandagopal** [comment]
@Svarto this is being picked up in Jan. Stay tuned for updates!

**Comment by Svarto** [comment]
@Nikhil-Nandagopal that is awesome, I encountered this issue for Input widget. I need to programmatically "clean up" the text that a user enters and from a UX perspective it would be good if the user can see the end result in their own input widget.

e.g. I tried to set `Input1.text = "cleaned text"` which of course doesn't work right now :)

**Comment by Nikhil-Nandagopal** [comment]
@Svarto
We might not be able to achieve `Input1.text = "cleaned text"` but we'll be introducing a Input1.setText('cleaned text') option
Does that work?

**Comment by Svarto** [comment]
> @Svarto
> We might not be able to achieve `Input1.text = "cleaned text"` but we'll be introducing a Input1.setText('cleaned text') option
> Does that work?

Of course that sounds perfect and fully in line with React type of programming. Makes total sense
