### ISSUE TITLE
[Bug]: Icon on a toolbar moves position based on presence of associated text

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#35427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Icon on a toolbar moves position based on presence of associated text

### Steps To Reproduce

1. Drop a toolbar widget
2. Add/remove text on a button with icon style
3. Observe the position of the icon

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/36cb62d476904188a42b0b622e2c7d74

### Version

cloud

**Comment by ichik** [comment]
This is fine, absence of text requires different visual balancing, so IconButton and regular Button have different paddings.
