### ISSUE TITLE
[Bug] Invite success text is always plural even when only 1 user is invited

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3542]
The invite text says: "Users have been invited." when I invited only one user. It should say, 'The user has been invited successfully' for one email and 'Users have been invited' for multiple emails.

<img width="331" alt="Screen Shot 2021-03-14 at 2 02 18 AM" src="https://user-images.githubusercontent.com/30255708/111043618-7720c180-8469-11eb-901e-5d8119a8c85d.png">

**Comment by Nikhil-Nandagopal** [comment]
@kaushik94 this is another good first issue that you can pick up
