### ISSUE TITLE
[Bug]: Zone auto height is broken

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#35464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Zone auto height is broken

![image](https://github.com/user-attachments/assets/ce14bfbe-7484-4d10-bca8-11cd670477d5)

### Steps To Reproduce

1. Add a button followed by an input below it
2. Add a statbox to create a new zone and another below it as seen in the video
3. Observe height of the two zones

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/c2f8c03f23f648a1aa1bc0c01566ae14

### Version

cloud

**Comment by riodeuno** [comment]
Closing as fixed.
