### ISSUE TITLE
[Feature]: List widget .setSelectedItemIndex

### ISSUE THREAD

**Issue by leonlazic** [appsmithorg/appsmith#35467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Just noticed that unlike the table widget the list widget does not have a function to set a selected item index. I think this would be nice to have.

### Why should this be worked on?

I think it's just more elegant than using placeholder variables in the jsobject file and setting the default selected item on that list to the variable, then triggering the wanted behaviour by mutating that value.

**Comment by Nikhil-Nandagopal** [comment]
This issue is already being tracked here so I'm closing it as a duplicate #30810
