### ISSUE TITLE
[Bug]: Pie charts on the Chart blocks are erroring out

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On dragging and dropping any chart block - the pie charts are erroring out

### Steps To Reproduce

1. Login to an application, and drag and drop a chart building block
2. Note that the pie chart errors out
3. The error seen is invalid value at index1
![Screenshot 2024-08-07 at 10 11 12 AM](https://github.com/user-attachments/assets/e5c5a89f-db01-4a13-99f4-b23c1240afd1)

<img width="878" alt="Screenshot 2024-08-06 at 8 16 45 PM" src="https://github.com/user-attachments/assets/fa2f41d0-d23a-4698-9682-3c47bddc9b59">

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by jacquesikot** [comment]
This is caused by inconsistent data from the query for Sample Database. I have updated both chart building blocks and uploaded to S3, adding a default fallback when data is incomplete.
