### ISSUE TITLE
[Feature]: Static Page IDs for having same url endpoints for multiple "instances" of the app

### ISSUE THREAD

**Issue by PrinceofCamunda** [appsmithorg/appsmith#35471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This request is from Patrick Wouterse (Low Code Product Manager on iTAC Software AG site):

Is it possible to have a "fixed" client ID on the instance?
This means that the shared application link follows a specific logic that's for example:
 
![image](https://github.com/user-attachments/assets/0c7394da-28d1-4598-be89-609a930cc002)

"url": "https://appsmith.mom-qa.itac.intra/app/master-data-part-types/mainpage?embed=true&ssoTrigger=oidc",
instead of: "url": "https://appsmith.mom-qa.itac.intra/app/master-data-part-types/mainpage-65f01111cde10368ce689377?embed=true&ssoTrigger=oidc",

![image](https://github.com/user-attachments/assets/cdc4f35b-6a76-409f-a930-8433e56b06d1)

Or in other words can we  maybe in the near future remove the Unique ID number that's created for each application on the URL of the application call?
I remember we discussed this feature request in the past, maybe it found it way on the roadmap. Because we are looking for a way to have "expected" URLs for each deployment on customer site.

### Why should this be worked on?

Because the interoperability with automatized deployment processes would be improved a lot

Currently on iTAC Site we see the issue that we need to "deploy" manually a big amount of UIs (> 30 UIs for each instance) while every application receives a UID after the "mainpage" for the to be called URL

**Comment by Nikhil-Nandagopal** [comment]
@PrinceofCamunda is there a reason why you aren't able to setup CI/CD for this? That should solve this problem

**Comment by Nikhil-Nandagopal** [comment]
@PrinceofCamunda can we do a call to understand what you are trying to achieve better?
https://calendly.com/appsmith-nikhil/30min

**Comment by Nikhil-Nandagopal** [comment]
We have this tracked here #35556
