### ISSUE TITLE
[Bug]: Unable to switch branches

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#35482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

User created a branch and tried switch to it, but it doesn't work.

### Steps To Reproduce

1. Create new branch from remote:  They see following error when creating a new branch -
![Screenshot 2024-08-07 at 2 08 19 PM](https://github.com/user-attachments/assets/65c2d325-69f6-4b13-8f0a-6cb29c21ea04)

2. User doesn't get redirected to the newly created local branch
3. They refresh the branch list.
4. See their new branch in the list
5. Click on that to switch to it but it doesn't take them to the new branch.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.29

**Comment by riteshkew** [comment]
Not reproducible in the latest version v1.41.
