### ISSUE TITLE
Create API in RTS to show concurrent users in the app

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#3548]
The RTS will maintain a list of users who are currently working on an application.

**Comment by RakshaKShetty** [comment]
Reopening the issue I am not able to see the concurrent user. I have opened the same application in 2 different browser with 2 different id but I am not able to see the User  name on the header section attaching the screenshot
![image](https://user-images.githubusercontent.com/45958978/129515189-92786216-37fc-4747-998d-de3dfde94d73.png)
![image](https://user-images.githubusercontent.com/45958978/129515212-91207608-4815-4855-997c-6904aad336df.png)
