### ISSUE TITLE
[Bug]: French characters encoding issue in PUT API payload

### ISSUE THREAD

**Issue by maheshingle05** [appsmithorg/appsmith#35516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

payload containing French world with accentuation character ends up giving DecoderFallbackException. Same API is working on postman. 

### Steps To Reproduce

payload containing French world with accentuation character ends up giving DecoderFallbackException. Same API is working on postman. 
![Screenshot 2024-08-07 163358](https://github.com/user-attachments/assets/7588948d-a520-40a1-be80-2376c76b717f)

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

self hosted/ 1.27

**Comment by maheshingle05** [comment]
Hello Team,

I hope you're doing well. I wanted to kindly check on the status of this ticket as the issue is quite urgent. Could you please provide an update or estimated timeline for resolution?

Thank you for your attention to this matter. I look forward to hearing from you soon.

Regards,
Mahesh

**Comment by Nikhil-Nandagopal** [comment]
@maheshingle05 have you tried turning off smart substitution for this?

**Comment by maheshingle05** [comment]
@Nikhil-Nandagopal Yes, I did. It does not affect the outcome. I am still receiving the same error.

**Comment by rohan-arthur** [comment]
@maheshingle05 thank you for confirming. We need more help to debug this:

1. the screenshot you've attached is visible as a thumbnail, but github isn't allowing me to view it enlarged. Would you please try re-attaching it in a comment?
2. would you please also share a screenshot from the `execute` call in the browser network tab? The example screenshot below that when I try a simple request, it seems to work ok
![Screenshot 2024-09-17 at 18 31 26](https://github.com/user-attachments/assets/ccd00b0f-7910-4bda-9f75-cb165a9bdefb)




3. Best case: if we can see this error ourselves. There are two options: 
       a. you can set up a sample endpoint for us to test and reproduce this issue
       b. or invite `support@appsmith.com` to the workspace

**Comment by maheshingle05** [comment]
@rohan-arthur  please find the attachment for reference.
![Screenshot 2024-09-18 174533](https://github.com/user-attachments/assets/c862d217-5afb-4f95-8d60-ea6c641b9e38)

**Comment by rohan-arthur** [comment]
Thanks @maheshingle05 !

Our team will look into it. Meanwhile, it would be greatly helpful if you can give us access to an app where we can see this error. 

If that is difficult to do, we can also try to debug this on a call at a time suitable for you (we'll share a calendar link)

**Comment by rishabhrathod01** [comment]
@maheshingle05 Could you please share the JSON request data and the complete stack track from the `response.body.StackTrace`?

**Comment by rishabhrathod01** [comment]
@maheshingle05 Could you schedule a call to help us debug this issue with you. https://calendly.com/rishabh-rathod

**Comment by rishabhrathod01** [comment]
Removed my assignment to avoid confusion here

**Comment by NilanshBansal** [comment]
@maheshingle05 we suspect the issue to be due to some locale configurations in the self-hosting of appsmith. Can you please try if the same query and payload works on https://app.appsmith.com?

**Comment by NilanshBansal** [comment]
https://theappsmith.slack.com/archives/C0341RERY4R/p1728406814749239?thread_ts=1726499243.849989&cid=C0341RERY4R

**Comment by rohan-arthur** [comment]
We have closed the issue because there isn't more information to proceed, and we were not able to establish the fact that this was a bug on appsmith.
For future users running into this problem: please feel welcome to reopen this issue and add a comment describing the problem.
