### ISSUE TITLE
[Bug]: cannot create gsheets datasource, blocked by google

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#35523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2024-08-07 at 18 06 53](https://github.com/user-attachments/assets/0290ccb8-ffad-4851-94d7-858a0164081b)

### Steps To Reproduce

1. Add a new gsheets datasource
2. Select scope that is anything other than `Selected google sheets`
3. Save and authorise
4. Authorise a non-appsmith email domain
See the error.

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Cloud

**Comment by sneha122** [comment]
We have submitted the google project responsible for google sheets integration for verification with google. This is moved to blocked state as verification is in progress.

**Comment by rohan-arthur** [comment]
verification still in progress
