### ISSUE TITLE
[Task]: Design fixes for the new toolbar

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#35529]
Design:
[Figma](https://www.figma.com/design/8L9BXMzNTKboGWlHpdXyYP/Appsmith-IDE?node-id=197-20588&t=WEEjMziQORcBrBUd-4)
[Zeplin](https://app.zeplin.io/project/6683c698d2210f2b0697d978/styleguide/components?coid=6683c85e401b3970bedd3cbd)

To do:
- [ ] Update component sizing according to new design.
- [ ] Update padding & gap according to new design.
- [ ] Function selector is a select component as of now, this needs to be changed to menu component

**Comment by nairvismaya** [comment]
please assign me this task

**Comment by alex-golovanov** [comment]
> please assign me this task

Appreciate you offer to help @nairvismaya, but this task will need to be completed internally.
