### ISSUE TITLE
[Bug]: Erroring out while connecting to server on billing page for business users

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error message is displayed under the billing and usage tab for business users
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/cfb63b24-ff64-43f8-bd2f-e7c6395b7465">

### Steps To Reproduce

1. login to https://release-customer.appsmith.com/billing
2.  username wawobal406@foraro.com password : Appsmith@123
3. Click on billing and usage tab 
4. the error message is displayed 

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

release

**Comment by abhvsn** [comment]
This has been resolved by the billing provider. Please verify from your end @RakshaKShetty.

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by abhvsn** [comment]
Closing this as it's fixed. @RakshaKShetty feel free to reopen if needed.
