### ISSUE TITLE
[Task]: Update JS Object  padding to consume fullscreen

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#35545]

**Comment by udayxyz** [comment]
I am a beginner can i work on this issue? I would also like a description of the issue

**Comment by albinAppsmith** [comment]
Closing this as it has already covered in https://github.com/appsmithorg/appsmith/issues/35509

**Comment by albinAppsmith** [comment]
Hello @udayxyz,

Please feel free to pick up from [Inviting Contribution](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Inviting+Contribution%22) list.
