### ISSUE TITLE
[Bug]: Icon disappears when data type as number and position is right in phone input widget

### ISSUE THREAD

**Issue by PrasadMadine** [appsmithorg/appsmith#35549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Description :** In the current implementation of the InputWidget, user has an option to select the data type as single-line text, multi-line text, number, email and password. when the user select the data type as number and add the icon from styles and set the position as left then the icon is appearing, but when user select the position as right then the icon is disappearing.

**Image when position is selected as left:**
![image](https://github.com/user-attachments/assets/94347322-13c4-4b1e-a56f-128395165ac9)

**Image when position is selected as right:**
![image](https://github.com/user-attachments/assets/1e28c7b0-c859-4d8a-948c-2c581c823500)

### Steps To Reproduce

1. Drag and drop InputWidget.
2. In the property pane section for DataType select Number.
3. Select the Styles in property pane section and add the icon. 
4. Now check for left position the icon will be shown and when selecting right position, the icon gets disappeared.

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

1.34

**Comment by rahulbarwal** [comment]
Fixed via: https://github.com/appsmithorg/appsmith/pull/35992
