### ISSUE TITLE
[Bug]: Linter shows error for `URL` API in JS

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#35559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Description
The linter in Appsmith shows an error when using the native URL API in JavaScript within the Appsmith editor. This issue causes false positives and may confuse developers who are using standard JavaScript APIs.

Expected Behavior
The linter should recognize and accept the native URL API without throwing an error, as this is a standard JavaScript feature.

Current Behavior
When using the URL constructor in JavaScript, the Appsmith linter throws an error suggesting that the URL is undefined or not recognized. This occurs despite the fact that the code functions correctly when executed. 

![image](https://github.com/user-attachments/assets/7762092c-487a-45f1-a7c3-c28c5811ba3d)

### Steps To Reproduce

1. Open the Appsmith editor.
2. Create a new JavaScript action or modify an existing one.
3. Use the URL API, such as new URL("https://example.com").
4. Observe the linter error.

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

1.33.1

**Comment by LagunaElectric** [comment]
Potential duplicate of #33611

**Comment by rishabhrathod01** [comment]
@LagunaElectric Thanks for pointing this out.
