### ISSUE TITLE
[Bug]: Currency Input widget issues to format currency on changing country dropdown

### ISSUE THREAD

**Issue by PrasadMadine** [appsmithorg/appsmith#35550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Description:** In the current implementation of the CurrencyInputWidget, users have the option to select a country, such as India,USA and etc.. and input a value. when I change the dropdown to USA or India or other countries, the value does not automatically formatted according to the country selected. Currently, I have to click inside the widget and then outside the widget , to format the currency according to dropdown selected.
![image](https://github.com/user-attachments/assets/d5bea608-4eb1-4af4-973a-7fdae83e7a43)
![image](https://github.com/user-attachments/assets/5a7d7016-30ed-4caa-8a83-379ad0cb7a9b)
![image](https://github.com/user-attachments/assets/47cf3c5f-6175-4f26-9f73-a26c25c7b770)

### Steps To Reproduce

1. Drag and drop CurrencyInputWidget.
2. In the property pane section for currency dropdown select USD .
3. Now try to enter a value as 1000000 and then select India from dropdown and check the value inside the widget, it was not formatted automatically.
4. Now try clicking inside the widget and then outside the widget for formatting the currency , it will be converted to 10,00,000.

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

1.34

**Comment by PrasadMadine** [comment]
Hello @Nikhil-Nandagopal , I am picking this issue

**Comment by Nikhil-Nandagopal** [comment]
@PrasadMadine this is not really a problem since the edit mode is only accessible to developers and hence I'm going to close this issue as invalid because we don't want to pick it up
