### ISSUE TITLE
[Bug] Disable table pagination buttons when pagination isn't enabled

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3558]
When the table doesn't have additional pages, the pagination buttons should be disabled. See video below where the page buttons work even when there are no additional pages.

https://user-images.githubusercontent.com/30255708/111145737-99702780-85ae-11eb-9698-737ab13d2961.mov

**Comment by somangshu** [comment]
This happens when server side pagination is enabled.

**Comment by Nikhil-Nandagopal** [comment]
Related to #1578

**Comment by Nikhil-Nandagopal** [comment]
@somangshu with reactive actions users will no longer need to configure onPageChange for pagination.
OnPageChange might still be used for other cases like displaying a message, resetting a form, etc. So it is still useful

**Comment by somangshu** [comment]
Makes sense @Nikhil-Nandagopal, in that case, there is no change required here correct? The combination of `server side pagination` and reactive actions should resolve this?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu we still need a field where users can configure the maximum dataset size so that the table can disable the next button when the last page is reached. Today there is no concept of last page in server side pagination because the client doesn't know the data set size

**Comment by somangshu** [comment]
@Nikhil-Nandagopal correct. I believe we will be picking that up with #1578. Should this be closed?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu oh yeah sure!
