### ISSUE TITLE
[Bug]: Auto-commit does not happen when editing certain older apps

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#35592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When editing certain older apps, auto-commit does not occur. While this issue isn't present in all apps, it has been observed in some of the older ones.

App: https://release.app.appsmith.com/app/oldapp-dstesting1-9-24/oauth20-665869463328c50d30e20520?branch=branch_01
Repo: https://github.com/shadabbuchh/autoCommit

### Steps To Reproduce

1. Edit an app that has an older DSL version.

**Expected:** Auto-commit should take place & we should not see any uncommitted changes post that.
**Actual:** Auto-commit doe not take place.

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/3667422e-f25b-4ea3-b3b6-9470cf25abca

### Version

Cloud

**Comment by sondermanish** [comment]
closing this issue, as autocommit doesn't start if there are remote changes present for the connected application. 
This is done to avoid merge conflicts.
