### ISSUE TITLE
[Bug] Download function expects a data URL to be included with the data, while action result blobs do not provide this

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3559]
Noticed in the S3 plugin, let's say we try to download a pdf file that is present in an S# bucket. The downloaded file gets corrupted because the download function cannot understand the data without a data URL. The action result however only returns the base64 encoded version of the pdf file itself, without a data URL.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu @nidhi-nair what would be a good solve here?

**Comment by nidhi-nair** [comment]
Thinking out loud here: The use case of loading binary files into Appsmith is always either going to be to represent it visually or transfer the file into another system. We will never expect manipulation of such files within Appsmith. With that in mind, we can possibly prepend the returned action result or add an attribute from the server itself to indicate what metadata is required to build this data URL. Either a `dataURL` field itself or two separate `mimeType` and `isBase64Encoded` fields.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair nice or the download action can take in a data type as either base64 or base64URI and prepend it based on this.

**Comment by nidhi-nair** [comment]
What you suggested also seems like a good solve for this. @hetunandu is this doable?

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal @nidhi-nair is there a way to find the datatype just by seeing the base64 string?

**Comment by nidhi-nair** [comment]
Not a reliable one. So with Nikhil's solution, we'll need metadata, but also a way in the download function to add dataurl. The benefit of doing that is that we don't corrupt the action execution result itself.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu @nidhi-nair can we look at the mime type and if its base 64, check if it starts with "data: " if it does, then its a data URI otherwise prepend it?

**Comment by zee-bit** [comment]
Hi guys, Just found this open discussion here. Is there a fix for it finalized yet?
I have a similar issue, where I am trying to download an Excel (.xlsx) file via an API, but the downloaded file gets corrupted. Is there a temporary fix(workaround) that I can follow to get through with this?

**Comment by rohan-arthur** [comment]
@zee-bit we think it is to do with supporting binary data transfer, and we're looking into this currently. 
Meanwhile as a possible workaround: can you make your API return the file as a data URL?

**Comment by ohansFavour** [comment]
Related: https://github.com/rndme/download/issues/59

**Comment by Rishabh-Rathod** [comment]
> Related: [rndme/download#59](https://github.com/rndme/download/issues/59)

The issue with pdf seems to be related to the [issue](https://github.com/rndme/download/issues/59) of downloadjs mentioned above. 

Possible solution - 
Check the mime-type and if it is pdf then handle the edge case by solution as mentioned in the [issue](https://github.com/rndme/download/issues/59) comments.


cc: @nidhi-nair  Can you please confirm if the issue was understood correctly?
