### ISSUE TITLE
[Bug]: File upload to S3 fails for certain files

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith#35601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When uploading a file to S3, the user gets the following error:
```
Your query failed to execute:
String value length (20054016) exceeds the maximum allowed (20000000, from StreamReadConstraints.getMaxStringLength()) (through reference chain: com.appsmith.external.dtos.MultipartFormDataDTO["data"])
```

[relevant slack thread](https://theappsmith.slack.com/archives/C0341RERY4R/p1719269999147919)

### Steps To Reproduce

1. Go to S3
2. Upload a file in the range of 14-15MB
3. Query fails with below error
`String value length (20054016) exceeds the maximum allowed (20000000, from StreamReadConstraints.getMaxStringLength()) (through reference chain: com.appsmith.external.dtos.MultipartFormDataDTO["data"])`

### Public Sample App

https://app.appsmith.com/app/lighthouse/brand-editor-649995898d0dab7461898401/edit/widgets/ss3d9grtsm?branch=master

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://screenrec.com/share/tcQLwTJrjY

### Version

Cloud - 1.33

**Comment by Nikhil-Nandagopal** [comment]
@richardwhatever are you on self-hosted or cloud?

**Comment by ericambo** [comment]
Just bumping this since we are experiencing this same issue and it's impacting production efficiency.

**Comment by richardwhatever** [comment]
> @richardwhatever are you on self-hosted or cloud?

we're on cloud

**Comment by Nikhil-Nandagopal** [comment]
@richardwhatever it should now be fixed in the cloud

**Comment by codeinwill** [comment]
Hi @Nikhil-Nandagopal @richardwhatever . how to fix this on self-host?

**Comment by Nikhil-Nandagopal** [comment]
@codeinwill once you update to the latest release it will be fixed on self-hosted
