### ISSUE TITLE
[Bug]: On trying to create a new workflow, an error is seen although the workflow gets created

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#35612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On trying to create a new workflow, an error is seen although the workflow gets created
![image](https://github.com/user-attachments/assets/77c0a8af-315e-4d27-9f1b-1040573e1cc0)

### Steps To Reproduce

1. Try to create a workflow
2. Notice that considerable lag is seen and an error toast pops up. The workflow is seen only after refresh

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/1e17d750e4bf48618b55055ab9134fd4

### Version

Self hosted

**Comment by abhvsn** [comment]
Closing this and tracking under https://github.com/appsmithorg/appsmith/issues/35623, as this is related to the slow query response time when communicating with external DB.
