### ISSUE TITLE
[Bug]: On importing the attached application, the New Query button does not come up

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On importing the attached applications, we are unable to see the New Query button

### Steps To Reproduce

1. Try to import storytelling details.json
2. Click on Go to Application
3. Now check the datasource page. Note that there is no New Query button for any datasource.
4. Try to save and authorize gsheets. 
5. Even then the new query button does not come up

Note: The applications jsons were created in 2022/2021. 

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by btsgh** [comment]
App 1 - [StorytellingDetails.json](https://github.com/user-attachments/files/16580880/StorytellingDetails.json)
App 2 - [BlogConvertor.json](https://github.com/user-attachments/files/16580886/BlogConvertor.json)

**Comment by btsgh** [comment]
<img width="1432" alt="Screenshot 2024-08-12 at 4 55 35 PM" src="https://github.com/user-attachments/assets/acc11bef-a3c2-46be-b10d-9f637af4fddb">

**Comment by btsgh** [comment]
Also attaching the video of a scenario where I see it in a branch in a git connected app. 
https://jam.dev/c/ef345283-7590-43d2-80cb-f2afe6496a4d
This was consistently reproducible for a while, and then after a few attempts, the redirection happened to app from applications in a wee bit of a second.

**Comment by infinitetrooper** [comment]
This is not an import error. Updating labels.

**Comment by btsgh** [comment]
@sneha122 - we are seeing this now on new applications as well. On app.appsmith.com .. Attaching a video from today.
https://jam.dev/c/9a3a62bf-d907-4b64-a18d-922a658debe3

Is this something that can be looked at on priority?
