### ISSUE TITLE
[Bug]: Move to Postgres : The queries are not added for the crud pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The queries are not added for the crud pages
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/42a30fa6-9561-46fc-b404-a4c85d9e0762">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/3714ae68-bb18-4225-b273-4c5a06d9b4e7">

### Steps To Reproduce

1. Pull postgres abhijeetappsmith/appsmith:ee-pg locally
2. login as admin and go to admin setting advance section
3. add the custom postgres uri
4. once save and restart
5. Try to create a new app the creation takes lot of time

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

deploy preview

**Comment by AnaghHegde** [comment]
@shadabbuchh When you say custom url do you mean remote url? If yes what hosting are you using? I tried with locally running the pg and the generate crud seems to be working fine for me.

**Comment by AnaghHegde** [comment]
Tracking this via the performance issue with external pg end point as its reporducible only on when we use external pg.

**Comment by RakshaKShetty** [comment]
Fixed on DP with external postgres with AWS
