### ISSUE TITLE
[Bug]: Move to Postgres : The instance performance is very slow when we use external db

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Move to Postgres : The instance performance is very slow when we use external db

### Steps To Reproduce

1. Pull postgres abhijeetappsmith/appsmith:ee-pg locally
2. login as admin and go to admin setting advance section
3. add the custom postgres uri
4. once save and restart
5. Try to create a new app the creation takes lot of time 

### Environment

Deploy Preview

### Severity

Critical (Broken Production apps)

### Version

deploy preview

**Comment by AnaghHegde** [comment]
Move to Postgres : The queries are not added for the crud pages - https://github.com/appsmithorg/appsmith/issues/35625

**Comment by abhvsn** [comment]
Another issue which is a side-effect of slow queries: https://github.com/appsmithorg/appsmith/issues/35612

**Comment by abhvsn** [comment]
Closing this as this was fixed after upgrading the indices.
