### ISSUE TITLE
[Bug]: incorrect Unix Timestamp value when updating a Date type column

### ISSUE THREAD

**Issue by simonfvr** [appsmithorg/appsmith#35631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I update a Date type column in a table with data extracted from a database, the Unix timestamp value returned is incorrect.

E.g., when setting 2024-08-13 in the datepicker, the updated value internally is `8iAug 13, 2024i02con20`.

This makes impossible the update of the date for any table row.

### Steps To Reproduce

1. Create a table widget.
2. Extract data from a DB with any date column.
3. For that date column, set type as Date, date format as Unix Timestamp (ms) and display format as YYYY-MM-DD
4. Make the column editable.
5. Change the value of the column using the datepicker.
6. Now, if you check the computed value, it is incorrect.

![imagen](https://github.com/user-attachments/assets/34c0242b-03bb-474c-9442-346477e5d256)

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Appsmith v1.31.1

**Comment by Nikhil-Nandagopal** [comment]
@simonfvr it's possible the unix timestamp format being supplied as the data may be incorrect. Can you share a sample of the data that the table widget has?

**Comment by simonfvr** [comment]
The unix timestamp in the data is correct as you can see in the following image.
<img width="592" alt="imagen" src="https://github.com/user-attachments/assets/37c00f77-7d5a-4c11-b6ad-f5786676ff6a">
The first row has been updated to show the incorrect timestamp format.

**Comment by simonfvr** [comment]
Hello, what's the status of this?

**Comment by carinanfonseca** [comment]
Thanks for reporting this @simonfvr. We'll analyze this and get back to you as soon as possible.

**Comment by simonfvr** [comment]
@carinanfonseca Hello Carina, this is a high severity error since users are not able to update the dates in a column with Date type. Please, solve it ASAP.

**Comment by jacquesikot** [comment]
@simonfvr I will pick this up this week. Sorry for the delays.

**Comment by jacquesikot** [comment]
@simonfvr This PR will be available in the next release - 1.44
