### ISSUE TITLE
[Bug]: List widget throws an error when created

### ISSUE THREAD

**Issue by saicharan-zemoso** [appsmithorg/appsmith#35647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The List widget shows and throws an error when created this is observed in release.app.appsmith and recently observed in app.appsmith.com as well.

observed behaviour on local,release and in app.appsmith.com from today:

![image](https://github.com/user-attachments/assets/ac297b68-39db-42f7-9592-337b115c83b0)

expected behaviour:
![image](https://github.com/user-attachments/assets/2c5d0e80-8c04-4cee-bf59-2e903fb3dad6)

additional info:
1.Only first container shows the text and image and in secound and third containers are not showing any errors
2. The currentItemsView ,selectedItemsView and triggeredItemView are returning as undefined.

video reference:
https://drive.google.com/file/d/1AkmK_zp3StSjhF8KOTEoEkWX2VDmXhlj/view?usp=sharing

observed in :
[release](https://release.app.appsmith.com)
[appsmith](https://app.appsmith.com)

### Steps To Reproduce

1. create or open an application.
2. search for list widget.
3. drag and drop the list widget.
4. observe the error thrown in the UI

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://drive.google.com/file/d/1AkmK_zp3StSjhF8KOTEoEkWX2VDmXhlj/view?usp=sharing

### Version

V1.34

**Comment by shadabbuchh** [comment]
This issue has been fixed by: https://github.com/appsmithorg/appsmith/pull/35622
Once app.appsmith.com gets updated with the latest image, the fix will be available there as well.
