### ISSUE TITLE
[Feature]: FilePicker widget needs reset method

### ISSUE THREAD

**Issue by rlnorthcutt** [appsmithorg/appsmith#35642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When using the FilePicker widget, we need a way to `reset` the widget. For example, if I upload a file for processing, and either finish the workflow OR want to start over, I need to reset the widget. This puts it back into its initial state and removes any files that have been uploaded.

### Why should this be worked on?

The inabilility to reset the FilePicker widget is an expected method.

Actually, I expect there to be a `set` method for creating/adding files, but that introduces a whole host of potential complications. The ability to `reset` the widget will enable the user to easily add new files, and will also help maintain smooth user flow.

Right now, the user will have to ipen the FilePicker, remove the files manually, and then reupload... this is workable, but provides a disjointed user flow.

**Comment by Nikhil-Nandagopal** [comment]
@rlnorthcutt you can use the resetWidget method and pass in the filepicker name to achieve this today.

**Comment by rlnorthcutt** [comment]
Thank you!!!!
