### ISSUE TITLE
[Bug] Setting `onSuccess` for a button's action and then resetting it, takes the button to a broken state

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3570]
Recording:

https://user-images.githubusercontent.com/120119/111266528-aba2a200-8650-11eb-8b46-2ccdd2bba9e4.mov

After the button enters the bad state, the code behind `onClick` looks like this: (Note that this is not valid Javascript syntax anymore)

![Screenshot 2021-03-16 at 11 21 46](https://user-images.githubusercontent.com/120119/111266624-d0971500-8650-11eb-9187-f2bbc7d45bd6.png)

**Comment by Nikhil-Nandagopal** [comment]
Noi able to see the video but I think this is now working. @vivekverma2312 please verify this
