### ISSUE TITLE
Blockhound Check To Unblock endpoints & apis

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#35712]
## Description
In order to improve stability, we need to go through the api endpoints and remove processes from blocking threads.
- i.e. move process/calls from main thread which serves request to non-blocking async threads.
- This Epic will contain list of endpoints/apis which needs to be unblocked.

**Comment by NilanshBansal** [comment]
The execute API blockhound compliance is tracked here: https://github.com/appsmithorg/appsmith/issues/35928
cc: @rajatagrawal

**Comment by nidhi-nair** [comment]
Closing as completed @sondermanish
