### ISSUE TITLE
[Task]: Removing toast message errors in the editor

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#35741]
Do not show error messages as toasts when the user is inside the editor. 

This is being done because of the following reasons.

1. When there are multiple errors in an app, the app is completely blocked with toast messages that show up on top. This creates a "Toast Wall"
2. These errors are hard to dismiss because the toast message does not have a button to close them
3. Since these errors disappear in some time, it is hard check back on them

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Toast messages should not appear inside the editor**
  - Given the user is working within the editor
  - When an error occurs in the code
  - Then toast messages should not be displayed to avoid blocking the view and provide a better user experience

**Comment by neehhaa06** [comment]
Hello @hetunandu :)

```
Suppress toast notifications for errors when the user is in the editor. Instead, display errors in a dedicated panel within the editor for better visibility and management.
```
