### ISSUE TITLE
[Bug]: Workflow run history logs get cut off horizontally even if the screen is big

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#35747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Workflow run history logs get cut off even if the screen is big

### Steps To Reproduce

1. Do a test run on workflows
2. Notice logs get cut off in big screen

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

C

**Comment by ALOK9442** [comment]
Hey @ayushpahwa , I wanna work on this issue, can you tell me how to replicate the issue  as I couldn't produce it with the given instructions

**Comment by ayushpahwa** [comment]
Hey @ALOK9442 this issue is part of the business edition and hence not available for contribution from external contributors

**Comment by ALOK9442** [comment]
hey @ayushpahwa , thanks for clearing this out and I understand, can you also tell me what issues I can contribute to as I really want to learn about these stuffs and contribute to
