### ISSUE TITLE
[Bug]: Move to Postgres - Error while importing/forking apps

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#35764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We encounter a `400 Bad Request` error when importing apps, which prevents input fields for datasources from appearing in the reconnect datasource modal.
![Screenshot 2024-08-19 at 7 10 01 PM](https://github.com/user-attachments/assets/54dc6bae-e51b-416d-b147-42090f2f5f61)

### Steps To Reproduce

1. Pull `abhijeetappsmith/appsmith:ee-pg` locally.
2. In the homepage, try to import an app.

**Expected:** The app should get imported successfully without any errors & the user should be able to add details in the input fields.
**Actual:** We see a 400 Bad request error.

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/0e9b6e15-f052-4ecd-a90f-6d65c21b8334

### Version

Self hosted

**Comment by AnaghHegde** [comment]
@shadabbuchh Can you share the json file?

**Comment by shadabbuchh** [comment]
> @shadabbuchh Can you share the json file?

1. [OldApp_DSTesting1.9.24 (1).json](https://github.com/user-attachments/files/16668214/OldApp_DSTesting1.9.24.1.json)
2. [try.to.covermore.2.json](https://github.com/user-attachments/files/16668215/try.to.covermore.2.json)

**Comment by btsgh** [comment]
Also seeing this error popping up in the Fork application flow.

**Comment by btsgh** [comment]
Actually, most of the flows [e.g. OAuth2.0 Datasource saving / Gsheets Datasource Saving / Fork app] are erroring out with the same error

**Comment by abhvsn** [comment]
Closing as this is fixed.
