### ISSUE TITLE
[Bug]: Show bindings menu does not appear in split mode

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#35775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Show bindings menu does not appear in split mode. However, it works fine in the general mode.

### Steps To Reproduce

1. Add queries/JS objects
2. In split mode click on the `Show Bindings` menu.

**Expected:** The sub menu should show up.
**Actual:** The sub menu does not show up in the split mode.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/c56ff876-d561-4914-b1fb-931c0b334f34

### Version

Cloud

**Comment by shadabbuchh** [comment]
The Show bindings sub menu now shows up in split view as well (probably because of this fix), however the position of the said menu is not appropriate.
https://jam.dev/c/aae6d0be-bcb6-44d5-bfa9-08c494eb4850

**Comment by a6hishekpandey** [comment]
@hetunandu fixed this bug, can you please help me with the review?
