### ISSUE TITLE
Make input morphable

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#35781]
The list of widgets in Widget Entries panel should be the same as the list of widgets in the select in the property panel. 
We take the properties and values as is. When changing widgets in the select, the values in the same type of properties have to be saved. 

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHB0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab259bc03a1ef4887fa9d027f66eb003c36df12d/__________________________2024-04-03____18.31.28_720.png" alt="__________________________2024-04-03____18.31.28_720.png" />

A list of widgets that should be present in the lists:
- Input
- Multi-line input
- KeyValue
- Currency Input
- Phone Input
- Number input
- Password input
- Email input

**Comment by jsartisan** [comment]
closing as done.
