### ISSUE TITLE
[Bug] Page hide functionality is broken when pages are empty 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3578]
Steps to reproduce:
1) Add multiple pages 
2) Click on action item of the page (Three dots)
3) Click on hide on any one page 
4) Click on deploy 
and observed

Observation:
Scenario 1:
It is observed that on hiding the single page and deploy the application the user is not displayed with empty pages 
Scenario 2:
It is observed that if the pages are not hidden on deploy the empty page is displayed to user 

However when any page has a widget the empty page are displayed and hidden page is not displayed to user 

Expected behaviour:
On selecting the hidden option only the page with selected option must not be displayed to user. However the other page must be displayed even when the page is empty .

**Comment by Nikhil-Nandagopal** [comment]
@prapullac if you are on the hidden page, no other page will be displayed to you. If you are on the other pages, the hidden page will not be displayed. So this is expected. In the future, we'll improve the hidden page messaging by letting users control the routing of these pages
