### ISSUE TITLE
[Task] Add Workflows documentation link in the Main JS object

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#35788]
Add the Workflows documentation link(https://docs.appsmith.com/workflows) like this 
![image](https://github.com/user-attachments/assets/4a34c9fe-e559-4c67-bfa3-5274745294c2)

In the Main JS Object
![image](https://github.com/user-attachments/assets/797bf273-c09f-4112-9a05-84cb02d5669b)

**Comment by ayushpahwa** [comment]
Already added to bottom pane
