### ISSUE TITLE
[Feature]: Add a variable containing the name of the environment the deployed app is pointing to

### ISSUE THREAD

**Issue by jonhwangla** [appsmithorg/appsmith#35797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi. I make use of the stage and production toggle a lot. It's very helpful. But there are times either in the editor or using the deployed app where you'll forget where you're pointing to. I'd like to create a text box at the top of my app where i can put in big letters: "STAGE environment" or "PRODUCTION env" sort of thing. If I could just call something like appsmith.env,  and have it spit out "Stage" or "Production"  that would be great!

### Why should this be worked on?

I've run into a few times where I almost accidentally used the tool in prod when I was trying to test in stage.  It's safer to let devs put an env label prominently in the app/tool they're creating.

**Comment by Nikhil-Nandagopal** [comment]
@jonhwangla have you tried simply using the URL parameter {{appsmith.URL.queryParams.environment}}

**Comment by jonhwangla** [comment]
Just tried it @Nikhil-Nandagopal .Works! Thanks. New to Appsmith so just learning as I go.  Thanks.

**Comment by Nikhil-Nandagopal** [comment]
Happy to help!

**Comment by jonhwangla** [comment]
@Nikhil-Nandagopal So when I use {{appsmith.URL.queryParams.environment}} and print it as text in the editor, it puts "stage" or "production". That's great. But when I deploy the app, the string doesn't print stage or prod. Doesn't print anything at all. Any idea what I'm doing wrong in that it shows in editor but not when deployed?

**Comment by Nikhil-Nandagopal** [comment]
@jonhwangla by default if there is no variable, the setup is pointing to production. To go to staging, you need to navigate to the page with the environment query param set to staging
