### ISSUE TITLE
[Bug] [Property Pane] Dropdown control should get icon and sub text

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3580]
## Description
This was not covered in the redesign of the property pane, but a dropdown option can also show an icon and some subtext

<img width="258" alt="Screenshot 2021-03-16 at 2 48 02 PM" src="https://user-images.githubusercontent.com/12022471/111288844-9175bd80-866a-11eb-82c5-5c2dbbc258eb.png">

**Comment by riodeuno** [comment]
This is available in release.
