### ISSUE TITLE
[Bug]: On forking an application unable to extract JDBC error is displayed 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On forking an application unable to extract JDBC error is displayed  and page doesnt load with the data
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b12524b8-0a0c-4267-aedb-24c51e351bd9">

### Steps To Reproduce

1. Pull postgres abhijeetappsmith/appsmith:ee-pg locally
2. login as admin and go to admin setting advance section
3. add the custom postgres uri
4. once save and restart
5. Import a application[
[try to covermore.json](https://github.com/user-attachments/files/16691116/try.to.covermore.json)
6.Now fork this application to new workspace
7.And try to open the app now
8.The error is displayed as in the attached screenshot

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

deploy preview

**Comment by abhvsn** [comment]
Closing this as its fixed.

**Comment by RakshaKShetty** [comment]
Able fork the application without any error in the DP
