### ISSUE TITLE
[Bug]: On importing, the gsheets datasource authentication fails with getting redirected to the release-cs url - internal server error

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 On importing, the gsheets datasource authentication fails with getting redirected to the release-cs url - internal server error
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/0c3b3240-1876-465f-945e-63dc1400abb3">

### Steps To Reproduce

1. Pull postgres abhijeetappsmith/appsmith:ee-pg locally
2. login as admin and go to admin setting advance section
3. add the custom postgres uri
4. once save and restart
5. now create a new app import any old app which has gsheet
6. now try to authorize this ghseet 
7. The error is displayed as in attached screenshot

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Deploy preview

**Comment by abhvsn** [comment]
@btsgh I'm not seeing this issue with latest build can we check this and confirm.

**Comment by RakshaKShetty** [comment]
This issue is fixed in the new DP

**Comment by btsgh** [comment]
This is happening again on the local pull [docker run -d --name appsmith -p 80:80 --pull always -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ee:pg]
This time we are using the google cloud postgres uri

**Comment by AnaghHegde** [comment]
https://www.loom.com/share/7a9c8b44b267439594d67187eb6d0389. Closing this issue since i am unable to reproduce the issue even after 3-4 tries with the latest pull. Feel free to reopen this if you can share the exact steps to reproduce the issue.

**Comment by btsgh** [comment]
Video recording of exact steps here @AnaghHegde - https://jam.dev/c/abb06b46-38af-4258-a413-d883519d5035

**Comment by RakshaKShetty** [comment]
Closing the issue as this issue is resolved
