### ISSUE TITLE
[Bug]: On changing the database in Admin settings, and saving and restarting, page does not refresh 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the db from a default to an external, or from one external to another external, the page sits there forever with the loader, and does not automatically refresh. When we manually refresh we see an unauthorized access error. We then have to logout and sign up to go to the correct home page.
The page should not sit there idly, and appropriate information should be provided to the user

### Steps To Reproduce

<img width="1174" alt="Screenshot 2024-08-21 at 4 09 51 PM" src="https://github.com/user-attachments/assets/2163df9a-7f38-429d-a7ef-39f9c20d31ca">

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by abhvsn** [comment]
@btsgh we were not able to reproduce this can we reverify again?

**Comment by AnaghHegde** [comment]
@btsgh Any updates on this issue?

**Comment by btsgh** [comment]
Not able to reproduce this any more. Seeing the following screen on changing the DB. Hence closing the issue. 
<img width="1417" alt="Screenshot 2024-09-23 at 4 22 06 PM" src="https://github.com/user-attachments/assets/7a85be74-cafd-4599-a726-e63fa9989ca8">
