### ISSUE TITLE
[Bug]: Unable to add a task in the default TO DO Template - errors with permission denied

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#35834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a TO DO template, and try to ADD TASK from the home page, it fails with an error createTask failed to execute. Logs give an error to the effect: 
```
Your query failed to execute:
ERROR: permission denied for sequence todo_task_id_seq
[SQLSTATE: 42501]
```

### Steps To Reproduce

https://jam.dev/c/4eb93adf-d963-4b3e-ac7b-ee0dbcbaf91b

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by jacquesikot** [comment]
Issue has been resolved. Issue was from permissions with Postgres auto id sequence. The addTask function has bee implemented to use locally generated ID.
