### ISSUE TITLE
Task: Update latest cypress setup guide to help internal and external contributors.

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#35852]
Publish the recent changes to cypress setup(with TED and everything) <https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#running-tests-on-client|This >seems inadequate.

[Slack Message](https://theappsmith.slack.com/archives/C06FWBV74GH/p1724389352802439?thread_ts=1724389352.802439&cid=C06FWBV74GH)

**Comment by sagar-qa007** [comment]
https://github.com/appsmithorg/appsmith/pull/35968
