### ISSUE TITLE
[Task] Refactoring of Google Sheets plugin for better UX

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3589]
- [x] Differentiate between Authorize and Re-authorize
- [x] Swap the text to say Authorize and then Save
- [ ] Move the Create API button to the bottom of the form, add logic to only enable this button after authorization
- [ ] Also make the Re-authorize button of secondary type
- [ ] Attach templates for all requests that need a body

**Comment by nidhi-nair** [comment]
Dropping a few notes from @aakashDesign here:

- [ ] The google sheet icon on New API page isn't the right size, and a little skewed. We can try 48x48px
- [ ] Can we jump to new datasource form if there are no gsheet datasources.
- [ ] Hide api button and reauthorise button design. 
- [x] We should select read/write by default here.
<img width="1430" alt="Screenshot 2021-03-26 at 4 12 56 PM" src="https://user-images.githubusercontent.com/5298848/112931757-59767c00-913a-11eb-89f6-28284e1ed2b3.png">

@hetunandu @ApekshaBhosale could one of you please help with these?

**Comment by rohan-arthur** [comment]
@nidhi-nair would you please explain the second point? //Can we jump to new datasource form if there are no gsheet datasources.//

**Comment by nidhi-nair** [comment]
@rohan-arthur I think that one's been fixed as part of a redesign project some time last year. The issue was that when there were no GSheets datasources configured for the app, the new datasource page used to still go to the list of available datasources and have an option to create a new datasource as another click from there.

**Comment by rohan-arthur** [comment]
Thanks Nidhi. Closing the issue then
