### ISSUE TITLE
[Bug] Theme does not get stored on the application 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3590]
Steps to reproduce:
1) Login to  application
2) The default theme is Dark
3) Change the theme to light 
4) Logout of the application
5) login to an application
and observe 

Observation:
It is observed that the application goes back to default on login back to the application

Expectation:
The Theme must be stored based as it the selection of the user and needs to be re-logged in using with the user selection

**Comment by hetunandu** [comment]
This is the expected behaviour. On logout we will clear the user perferenace

**Comment by prapullac** [comment]
@hetunandu : Closing the issue as per above comment
