### ISSUE TITLE
[Bug]: Duplicate page name error does not disappear on navigating to other pages

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#35949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error on setting duplicate page name does not disappear when we got to some other page's settings.

### Steps To Reproduce

1. Create an application & add 3 pages (Page1, Page2, Page3).
2. Go to Page2 settings & rename it to Page1. This will throw an error as expected.
3. Now go to Page3 settings.

**Expected:** The error should disappear when navigating to a different page's settings.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/e28bed4e-c5a4-4e2c-8326-ebccec882ea6

### Version

Cloud

**Comment by raushan3737** [comment]
Hi @shadabbuchh , @rohan-arthur, I would like to work on this Issue. Can i pick this issue?

**Comment by rohan-arthur** [comment]
@raushan3737 please go ahead and thank you!

**Comment by Shivam-z** [comment]
Hi @rohan-arthur, @raushan3737 has transitioned to another project, so I will be taking over this ticket now.

**Comment by a6hishekpandey** [comment]
Hi @rohan-arthur and @shadabbuchh, I have worked on the issue and raised the PR. Can someone please review the PR for the same?
