### ISSUE TITLE
[Bug]: Dropdown option invisible but visible in preview

### ISSUE THREAD

**Issue by gokaco** [appsmithorg/appsmith#35953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/user-attachments/assets/38afc570-f7b9-416d-a89a-086d57281785

### Steps To Reproduce

Label key Js is not wokring which was working earlier

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

1.38.0

**Comment by jacquesikot** [comment]
@gokaco please can I see what your source data looks like so I can debug further, thanks.

**Comment by gokaco** [comment]
> @gokaco please can I see what your source data looks like so I can debug further, thanks.

Something like
```
[
  {
    "liveClassThumbnailURL": "https://res.cloudinary.com",
    "cover": {
      "vidURL": "https://res.cloudinary.com"
    },
    "email": "dfsdfsdf@adf.com",
    "name": "Kartikeya Goswami",
    "imgURL": "https://res.cloudinary.com",
    "password": "abcdefg",
    "roles": [
      {
        "roleId": "uuid"
      },
      {
        "roleId": "uuid"
      }
    ],
    "subCategory": "COACH",
    "expertise": [],
    "trainerId": "uuid",
    "category": "category",
    "description": "description"
  }
]
```

**Comment by jacquesikot** [comment]
Thanks @gokaco. The label key cannot be the joined string you are using in the video, the label key needs to be one of the keys from your object above, e.g name. Add. name as the label key and see if it works.

**Comment by rahulbarwal** [comment]
@gokaco Did above comment help resolve your issue?

**Comment by gokaco** [comment]
> Thanks @gokaco. The label key cannot be the joined string you are using in the video, the label key needs to be one of the keys from your object above, e.g name. Add. name as the label key and see if it works.

@jacquesikot But earlier this was working. And this issue started happening from some days only. How it was working earlier? Have any changes been made in the new release?

**Comment by Nikhil-Nandagopal** [comment]
@gokaco We don't think anything has changed in the recent release. The key field should be one of the keys in your JSON. This should work for your use case, please let us know if there's anything that is not working.
