### ISSUE TITLE
[Bug]: Disabled fields in JSON form are shown as not disabled

### ISSUE THREAD

**Issue by marcjaner** [appsmithorg/appsmith#35974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a JSON form that is linked to a table so that, when a row in the table is selected its info is shown in the JSON form to be edited. 

However, I don't want all of the fields to be editable, thus I've configured them as `disabled = true` . But I'm facing a bug that causes some of this fields to become editable. 
![imagen](https://github.com/user-attachments/assets/7723920f-f119-4dba-a046-9e688052c355)
![imagen](https://github.com/user-attachments/assets/df9ae32b-0d21-454a-8ff6-f3c01ab7b9de)

I've been able to narrow it down to the following escenario.
1. As i load the page, all the disabled fields are correctly disabled.
2. When i select another row (different than the first one, which is selected by default), some of the disabled fields become active
3. Thay stay active no matter what I do. 

Things I've tried to disable the fields:
 - Using the toogle and setting it as true
 - Using `js`
    - Using `appsmith.user.email` to check for a condition that always evaluates to true
    - Using `true === true`

![imagen](https://github.com/user-attachments/assets/b2eeb87a-c80b-4516-8ed2-152778575e12)

But, even though this options disable the given field initially, they still become active afterwards. So, after a bit more testing I've realized that the `JS` expression I'm evaluating for checking if it is disabled or not seems to 'disappear' as i click another row in the table:
- The field becomes active
- The `js` expression dissappears from the disabled input container
- I can not change to non-`JS` mode because it tells me that the container first needs to be empty

![imagen](https://github.com/user-attachments/assets/337c8fde-6e6b-4951-a97e-70ca0dab07b7)
![imagen](https://github.com/user-attachments/assets/f6fc92f4-8809-46b2-b349-81492f56f8c1)

### Steps To Reproduce

1. Link database to JSON Form
2. Disable some of the fields in the JSON form
3. Select a row different than the default one
4. Some of the disabled fields will become active

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Self hosted

**Comment by Nikhil-Nandagopal** [comment]
@marcjaner instead of {{true===true}} can you simply add {{true}} in the field?
Can you also please share a video of the issue?
If you can share a public application that can reproduce this, that would be the best way for us to debug why this is happening

**Comment by jacquesikot** [comment]
@marcjaner I am unable to reproduce this, can you please send a video or public sample app?
