### ISSUE TITLE
[Bug]: One uncommitted change is seen on pulling remote changes on the main branch

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#35984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

One uncommitted change is seen on pulling remote changes on the main branch. 
![image](https://github.com/user-attachments/assets/1361163e-703a-4039-8d39-dab59918458d)

### Steps To Reproduce

1. Create an app and connect it to git
2. Create several branches
3. On the main branch, delete a page(page 4 in this example) from the remote repo
4. Notice that there would be remote changes to be pulled on the app. Go ahead and pull these changes from the app
5. Notice that one uncommitted change `Application settings modified` is seen

PS, this issue is only seen on pulling changes onto the main branch

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/ac2d3e13902c4bef94866630163a1024

### Version

Cloud

**Comment by riteshkew** [comment]
Not reproducible in the latest version v1.41, hence closing this. Was specific to the app here in this case.
