### ISSUE TITLE
[Bug]: Development and Production Environments Using the Same Git Branch Out of Sync

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#36007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user has multi-instance deployments. Their development and production environments are both using the same GitHub branch (master). Both have the latest version (no uncommitted changes).
But the development environment's version doesn't have some of the queries (that are committed to git), but their production environment has.
Deleting the local master branch in their dev environment and checking out the remote branch did not help.
They had to delete the app in the dev environment and re-import it from GitHub to fix the issue.

### Steps To Reproduce

[Ticket](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=2728)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self-Hosted

**Comment by riteshkew** [comment]
Resolved. It was a permission related issue.
