### ISSUE TITLE
[Docs]  Add a page about Appsmith's architecture

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3600]
A user I spoke to wanted to see Appsmith's architecture diagram to understand how data flows under the hood. This is a common question in the minds of developers who self-host Appsmith. We should have a dedicated page with diagrams and explanations about the architecture diagram.

We should also write a blog post about the architecture because developers considering Appsmith would love to read about technical decisions and the reasoning behind them.

**Comment by covering** [comment]
Any progress about this one?

**Comment by carbonara-mac** [comment]
I'm taking a class on Software Architecture and this would be perfect for my class. Is this issue still up for grabs?

**Comment by Rooney30** [comment]
> I'm taking a class on Software Architecture and this would be perfect for my class. Is this issue still up for grabs?

I am also in this class. Any chance we could contribute part of it? @areyabhishek

**Comment by areyabhishek** [comment]
@carbonara-mac @Rooney30 I missed your message. You can absolutely contribute to this. I'll assign the issue to both of you.

**Comment by danciaclara** [comment]
We recently published a page about [Deployment Architecture ](https://docs.appsmith.com/getting-started/setup/deployment-architecture)which covers this. So closing this issue.
