### ISSUE TITLE
[Docs]  Update page about Appsmith security with more details

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3601]
We need a page that we send to users when they ask about the security of Appsmith. This is a big concern for any mid-large company. Today our security section is sparse and doesn't inspire confidence.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek we have this page.
https://docs.appsmith.com/v/v1.2.1/security
Any ideas on what additional information we should add? Or good references to similar pages?

One point I remember was about the overall architecture of the platform is missing

Sentry has a good page but I think this might stem from a lack of some of these features
https://sentry.io/security/

**Comment by areyabhishek** [comment]
Oh I had forgotten about this. We just need to modify this one then.
1. We can add a few more details about the location of our servers.
2. How organization security works(you can't access apps unless you've been invited)
3. People can create accounts on different self-hosted instances, but they won't be able to access data of a different organization
4. How to disable self-hosted sign ups to ensure new accounts don't get created.

Airtable: https://airtable.com/security
Freshworks: https://www.freshworks.com/security/
Zendesk: https://www.zendesk.com/product/zendesk-security/
Slack: https://slack.com/intl/en-in/trust/security

**Comment by idivyanshbansal** [comment]
I would like to do work for this

**Comment by Nikhil-Nandagopal** [comment]
@idivyanshbansal go for it! I'm assigning this issue to you. Do have a look at our contribution guidelines and raise a PR in 4 days

**Comment by idivyanshbansal** [comment]
@Nikhil-Nandagopal got it sir 🙌
