### ISSUE TITLE
Add ComboBox Component and Widget

### ISSUE THREAD

**Issue by znamenskii-ilia** [appsmithorg/appsmith#36015]
Add ComboBox component from Spectrum https://react-spectrum.adobe.com/react-aria/ComboBox.html

**Comment by leonlazic** [comment]
It would be very useful if this would have the ability to display images as show here https://react-spectrum.adobe.com/react-aria/examples/user-combobox.html

**Comment by ichik** [comment]
If the selection is empty and the user typed something into the text field *don't clear the input on losing focus*. Preserve the typed-in value in the control (show error if necessary).
If the selection is empty and the user typed an exact match of the option *select that option on loss of focus*.
