### ISSUE TITLE
[Bug]: Update app through file import fails with 400

### ISSUE THREAD

**Issue by pedro-santos-rodrigues** [appsmithorg/appsmith#36018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I exported an app file and I tried to update the same app that I had exported previously to a different workspace using the "Update through file import" with the new .json file, it failed with a 400 error:

`https://app.appsmith.com/api/v1/pages?applicationId=66d1b4aabe3db57c56c421e5&pageId=undefined&mode=undefined`
```json
{
    "responseMeta": {
        "status": 400,
        "success": false,
        "error": {
            "code": "AE-BAD-4000",
            "title": "Invalid request",
            "message": "Bad request: Malformed parameter 'mode' for PageController.getAllPages",
            "errorType": "BAD_REQUEST"
        }
    },
    "errorDisplay": "AE-BAD-4000: Bad request: Malformed parameter 'mode' for PageController.getAllPages"
}
```

[StupidApp-unpublished.json](https://github.com/user-attachments/files/16816828/StupidApp-unpublished.json)
[StupidApp-published.json](https://github.com/user-attachments/files/16816827/StupidApp-published.json)

### Steps To Reproduce

1. Created application
2. Added a text widget with `Stupid V1`
3. Exported the application to the file [StupidApp-unpublished.json](https://github.com/user-attachments/files/16816828/StupidApp-unpublished.json)
4. Opened a different workspace
5. Imported the app to this workspace using the import option available in the create new button 
![image](https://github.com/user-attachments/assets/3a8861c1-a152-434a-8f8b-31e189d13aa5)
6. Got back the workspace where I was developing the app
7. Deployed the app with `Stupid V1` visible in the page
8. Edited te app to have `Stupid V2` visible in the page
9. Exported the application to the file [StupidApp-published.json](https://github.com/user-attachments/files/16816827/StupidApp-published.json)
10. Went to the app in edit mode in the other workspace (that I had imported in step 5)
11. Went to settings
12. Imported the file [StupidApp-published.json](https://github.com/user-attachments/files/16816827/StupidApp-published.json) using the "Update through file import" operation
![image](https://github.com/user-attachments/assets/6c53ae1d-740c-481e-b3e6-43aae2fbe774)

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

cabbd34e

**Comment by infinitetrooper** [comment]
@pedro-santos-rodrigues  - Is this limited to this one app or is it happening with your other apps?

**Comment by pedro-santos-rodrigues** [comment]
I have just tried this with this application. I haven't tried the same steps with another app to check if it also happens.

**Comment by riteshkew** [comment]
Not reproducible on latest versions for other apps. Seems to be related to this specific app. Taken a note of this for further investigation
