### ISSUE TITLE
[Feature]: Add selectable option for text widget

### ISSUE THREAD

**Issue by Heming9** [appsmithorg/appsmith#36023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add option to make text selectable

### Why should this be worked on?

Some entity info is displayed by the text widget, like user account, address, order number, etc., which is used to search frequently.  It's convenient for copying if the text is made selectable, eliminating the need to add a copy button or manual input.

**Comment by Nikhil-Nandagopal** [comment]
@Heming9 the text in the text widget should be selectable in view mode. Can you share a video of the challenge you are facing?

**Comment by Heming9** [comment]
> @Heming9 the text in the text widget should be selectable in view mode. Can you share a video of the challenge you are facing?

Okay, I was in edit mode. It works fine in view mode.
