### ISSUE TITLE
[Bug]: AI Integrations do not work

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The google AI Integration doesnt work
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/16f76ad7-b3d5-4084-ac6c-e7fc14872522">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/95eb8965-d9ed-4da4-b42f-68fb6f0c5cf2">

### Steps To Reproduce

1. go to https://ee-4517.dp.appsmith.com/
2. Now go to application
3. navigate to AI intergration section and add google AI now add the api integration detailes and save it
4. Now open a new query on Ai and add the detailes in API
5. now click on run 
6. the error is displayed as in attached screenshot same API key works in release instance

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Deploy preview

**Comment by RakshaKShetty** [comment]
@AnaghHegde Please check anthropic and Open AI we seems to have issue in those 2 plugin also

**Comment by AnaghHegde** [comment]
This is also fixed, should be available in the next build.
