### ISSUE TITLE
[Bug]: Move to Postgres - 504 errors when importing, editing, or deleting large apps on DP

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#36039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When attempting to import, edit, or delete a large app on the DP, we encounter 504 errors, along with toast messages indicating that the server is taking too long to respond. Occasionally, after refreshing the page, UI elements like buttons and the search bar on the homepage become misaligned. Additionally, the app takes an extended time to load.

**Note:** Performing these actions with the same app in `release` does not result in any errors, and no issues are observed.

<img width="1440" alt="Screenshot 2024-09-02 at 10 55 20 AM" src="https://github.com/user-attachments/assets/4d9c54ba-a88e-4669-881f-e329f92a8b96">
<img width="1440" alt="Screenshot 2024-09-02 at 10 58 57 AM" src="https://github.com/user-attachments/assets/34d0cc5f-a20d-4273-88f5-10aa94ff779d">

### Steps To Reproduce

1. Visit https://ee-4987.dp.appsmith.com/
2. Import the app using this file: [license-manager-app - dummy pages.json](https://github.com/user-attachments/files/16832780/license-manager-app.-.dummy.pages.json).
3. Attempt to edit or delete the app.

**Expected Results:**

1. The app should import without any errors.
2. You should be able to edit the app without issues.
3. You should be able to delete the app without encountering any errors.

**Actual Results:**
When importing the app, the reconnect datasource modal does not appear, and an error is displayed. Attempting to edit or delete the app results in 504 errors, and the homepage takes over 5 seconds to load.

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/34ab29c1-4e45-429f-afd0-3b7db06693e6

### Version

Cloud

**Comment by abhvsn** [comment]
@shadabbuchh is this still relevant after performance optimization?

**Comment by shadabbuchh** [comment]
> @shadabbuchh is this still relevant after performance optimization?

@abhvsn performance has improved for the above actions after the optimization. We can close the issue for now. If I notice any performance issue, I'll reopen it again.

**Comment by abhvsn** [comment]
Closing this!
