### ISSUE TITLE
[Bug]: Clicking on `+` in list view does not create a new query

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#36066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking on the `+` button in split view does not do anything when we are in the list view.

### Steps To Reproduce

1. Go to an app & select split view.
2. Click on Add a new query & then click on the list view button.
3. Now from there click on the + button.

**Expected:** User should get redirected to the New Query tab or a new tab should open altogether.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/02780f3a-fa42-48e6-812a-a89e7a94c202

### Version

Cloud

**Comment by rohan-arthur** [comment]
nice one! In this case, IMO we should focus back on the already open `new query` tab

**Comment by a6hishekpandey** [comment]
@rohan-arthur and @hetunandu, I am picking this issue.

**Comment by hetunandu** [comment]
> @rohan-arthur and @hetunandu, I am picking this issue.

Go for it

**Comment by a6hishekpandey** [comment]
hey @hetunandu, I have raised a PR for this issue can you please help me with the review whenever you have sometime
