### ISSUE TITLE
[Bug] Typo in deploy script

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3606]
### Description

The second command in the following line should be "sudo" instead of "sudmo"

https://github.com/appsmithorg/appsmith/blob/release/deploy/aws_ami/base-install.sh#L68

**Comment by areyabhishek** [comment]
Made a commit directly since the solution was simple. https://github.com/appsmithorg/appsmith/commit/b9150115562343ef6458301f9719481eb74a90c7
