### ISSUE TITLE
[Bug]: chart widget flickers at first then remains in loading state - community issues app

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#36076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

open our community issues internal app and look at the defect rate. This works
Try to select a pod to see that pod's defect rate, then you can see that all the charts in the page go into an unending loading state. (video attached)

Interestingly, this is only in view mode. In edit mode there are no flickers.

https://github.com/user-attachments/assets/229d0288-31f1-47a2-be92-58b504884b68

### Steps To Reproduce

-

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by rahulbarwal** [comment]
Its working perfectly right now. https://internal.appsmith.com/app/application/page-664c91c09285181c8ada66b0?branch=main&environment=production

Feel free to reopen if you notice this again.
