### ISSUE TITLE
[Bug]: Inaccurate search results for queries/JS objects

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#36071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Search results for Queries and JS Objects are inaccurate when entities have names ending with similar characters.

### Steps To Reproduce

1. Create 2 JS Objects:
- copied_in_page_2
- fromPage_2

2. Now in the search bar search with `_2`

**Expected:** Both of the Js objects should be filtered.
**Actual:** Only 1 is getting filtered

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/9d4e386d-9562-456f-848c-272b1aeceb46

### Version

Cloud

**Comment by alex-golovanov** [comment]
@rohan-arthur @shadabbuchh cannot reproduce this, seems like it's been fixed. Could you verify this please?
