### ISSUE TITLE
[Bug]: The table widget is no longer scrollable

### ISSUE THREAD

**Issue by clairearondel** [appsmithorg/appsmith#36079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change the number of records, which then becomes greater than the page size, the table becomes scrollable only by adding + 1 data item, but does not display the number of records. I don't get an error message, just a display problem, because if I increase the size of my page, my data is well below it. It worked fine before the 1.36 update.

### Steps To Reproduce

1. Drag and drop a Table widget (a pageSize around 10 rows)
2. Drag and drop a Input widget
3. Create a query : Select * from mytable limit {{Input.text}}
4. Put this Query1.data on the Table widget
5. And put 100 data in the Input widget
6. The table is scrollable but I see only 11 data

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self-hosted - 1.36

**Comment by Nikhil-Nandagopal** [comment]
@clairearondel can you please share a video of the issue?

**Comment by clairearondel** [comment]
@Nikhil-Nandagopal I found a way. It's a strange one. In my Table widget, “Show pagination” and “server-side pagination” are not enabled. But for my table to be scrollable to display the number of data on the page corresponding to the number displayed in my {{Input1.text}} I have to put in Total records the total number of data. But if I remove it, the table is no longer scrollable.

**Comment by Nikhil-Nandagopal** [comment]
@clairearondel right to make it scrollable you just need to enable server side pagination
