### ISSUE TITLE
[Bug]: Unable to see environments creation option as well as Staging is inaccessible on the performance DP

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#36127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 When I login to the performance dp of postgres, I am unable to see environments creation option as well as Staging is inaccessible on the performance DP

### Steps To Reproduce

Google login into performence dp https://ee-4987.dp.appsmith.com/applications
Note that Staging is not accessible
There are no Environments option on the workspace menu option either

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by abhvsn** [comment]
@btsgh this is expected considering this is a release dump. All the paid features are disabled for this DP.
