### ISSUE TITLE
[Bug]: Move to Postgres - Performance issues in Git-connected apps:

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#36123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are experiencing performance issues with Git-connected apps:

1. The Git icons in the bottom toolbar are taking significantly longer to load compared to `release`.
2. Branch names are being duplicated, and not all branches are appearing in the menu.

P.S: Please speed up the video to watch the whole thing.

### Steps To Reproduce

Steps to reproduce:

1. Navigate to [https://ee-4987.dp.appsmith.com/](https://ee-4987.dp.appsmith.com/) and open a Git-connected app.
2. Perform basic actions like opening the branch menu, syncing branches, or clicking the commit button.

**Expected Result:** All actions should execute smoothly without any delays or issues.

**Actual Result:** The icons take considerable time to load, and there is noticeable performance lag when carrying out the above actions.

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/01189d2e-db61-423d-b73a-f577e1f6421b

### Version

Cloud

**Comment by RakshaKShetty** [comment]
Adding few more areas to this In the newly created app we are seeing slowness on 
1. Create new branch and merge actions

**Comment by abhvsn** [comment]
Closing this as already resolved for AWS RDS instance.
