### ISSUE TITLE
[Bug]: On forking an application to a new workspace, the datasources and queries are not forked - the datasource section is empty

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#36134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the performance DP, when I fork an application to a new workspace, the datasources and queries are not seen in the forked application.

### Steps To Reproduce

1. Login to the performance DP. 
2. Try to fork a git connected app with datasources and queries
3. Internal server error comes up - which comes on release as well
4. On release, post that the datasources/queries etc are seen on the forked application, and we can configure and use the app
5. On the performance DP, however, the datasources/queries etc are not at all present in the forked application and app is rendered unusable

https://jam.dev/c/2e88348c-6c77-4b41-b7c2-4ea2c4a20214

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by AnaghHegde** [comment]
@Aparna this is fixed, can you verify and close the issue.

**Comment by abhvsn** [comment]
Closing this as we are not seeing this on AWS RDS instance. For GCP we are tracking this under #36163
