### ISSUE TITLE
[Bug]: Queries return AE-DTS-4013 after porting from v1.34 to a clean install of v1.39

### ISSUE THREAD

**Issue by markzerobrush** [appsmithorg/appsmith#36139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

(Note: I searched existing issues and found similar-sounding issues, but none related to this version of the community edition of Appsmith.)
 
 I needed to move our app from an old vm to a new one.   After pulling the app from git into the new instance I found that all of my REST API queries returned this:
 
**AE-DTS-4013
DEFAULT_REST_DATASOURCE is not correctly configured. Please fix the following and then re-run: [No datasource configuration found. Please configure it and try again.]**   (None of my queries requires a default datasource, by the way.)

I stumbled upon a "fix" by editing a broken query's url.  If I add a space at the beginning, it then works -- it seems it is provoking appsmith to regenerate its metadata but including a section that was missing before.

After checking in the code and comparing the metadata between the working and non-working versions of the query, I see that the "working one" has an additional "**datasourceConfiguration**" section under "datasource" (that's missing in the broken one).   Enclosed is a screenshot of the diff.

<img width="775" alt="AE-DTS-4013" src="https://github.com/user-attachments/assets/19a7b821-081d-4b8d-83d3-1637c289906f">

Thank you!   (Hope this helps.  I spent a lot of time on this and learned a few things.  ;-) )

### Steps To Reproduce

1. bring up a new appsmith instance (in this case, the latest, v1.39).
2. connect it to git, and bring down the bits
3. REST API queries that worked previously now all return AE-DTS-4013
4. see description section above for what I found that seems to be the problem in the metadata.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self-hosted v1.39

**Comment by ericambo** [comment]
I can confirm I'm having this same issue.  self-hosted v1.36.1

**Comment by Nikhil-Nandagopal** [comment]
@markzerobrush @ericambo which version was your application on before the upgrade?

**Comment by Nikhil-Nandagopal** [comment]
Closing this till we have more information
