### ISSUE TITLE
[Bug]: Unable to get database schema for the older apps on performance DP

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to get database schema for the older apps on performance DP
![image](https://github.com/user-attachments/assets/af1aa3e6-cc70-4802-9722-813500b82470)

### Steps To Reproduce

1. go to https://ee-4987.dp.appsmith.com/
2. Open any one existing app
3. go to datasources section
4. click on postgres DB 
5. check first if the db is valid or not once its valid
6. go to view datasection can click on schema refresh button
7. the json error is displayed as in attached screenshot

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Deploy preview

**Comment by AnaghHegde** [comment]
Fixed via https://github.com/appsmithorg/appsmith/pull/35346/commits/23616e594020df6265c79a67bd2e6bac9d21d5df

**Comment by AnaghHegde** [comment]
This is fixed
