### ISSUE TITLE
[Bug]: The workspaces are getting created at random places instead at the bottom of workspace section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The workspaces are getting created at random places instead at the bottom of workspace section

### Steps To Reproduce

1. go to https://ee-4987.dp.appsmith.com/
2. login as a google
3. in the home page 
4. Click on create workspace 
5. view the place where the workspace got created

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

deploy preview

**Comment by AnaghHegde** [comment]
@RakshaKShetty This is fixed, check the dp 4517.

**Comment by abhvsn** [comment]
@RakshaKShetty let's recheck and close if this is fixed.

**Comment by AnaghHegde** [comment]
@RakshaKShetty Closing this issue from our last conversation.
