### ISSUE TITLE
[Bug]: Move to Postgres - Google cloud URI - Error while importing apps and "Edit" does not redirect to the canvas

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#36162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When importing apps, an error appears indicating that the server is taking too long to respond. After refreshing, the imported app is visible, but clicking "Edit" does not redirect to the canvas.

### Steps To Reproduce

1. Pull this image: appsmith/appsmith-ee:pg
2. After the image is up and running go to Advanced section in Settings and replace the Appsmith DB uri with: postgresql://<username>:<password>@34.100.241.177:5432/appsmith
3. Go to homepage & import [license-manager-app - dummy pages.json](https://github.com/user-attachments/files/16908221/license-manager-app.-.dummy.pages.json)

**Expected:** The app should get imported without any errors & user should be able to edit the app.
**Actual:** We see errors while importing & are not able to edit the app.

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/845b49bd-9497-4109-9bf2-0070e82287d2

### Version

Cloud

**Comment by AnaghHegde** [comment]
@shadabbuchh I am unable to reproduce this error locally. The application works in edit mode.

**Comment by shadabbuchh** [comment]
> @shadabbuchh I am unable to reproduce this error locally or on dp. The application works in edit mode. Is this happening only when the docker image pulled and gcp end point?

Yes this happens when we change the URI with GCP. Will verify it with the new end point that has been provided to us.

**Comment by shadabbuchh** [comment]
@AnaghHegde tried it out with the new URI. Able to reproduce the issue there as well. 
https://jam.dev/c/0ab26435-6737-41d9-ae9a-3a55745a2afd

**Comment by AnaghHegde** [comment]
@shadabbuchh I have verified the scenario, it is bit slower compared to RDS instance. But the import flow is working fine. https://www.loom.com/share/9231c41d360c4e129dcb69e08497eae2

**Comment by shadabbuchh** [comment]
This is fixed in: http://34.93.159.52/applications
https://jam.dev/c/1192d192-e3f2-43cb-8de9-2d5b8f08f360
