### ISSUE TITLE
[Bug]: Forking gives an error & though the app is created in the background, the queries are missing for many datasources. 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#36163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I fork an application on the pg image pulled locally, Forking gives an error & though the app is created in the background, the queries are missing for many datasources. 
This is incorrect behavior, as compared to the 4517 dp and release. In both 4517 and release, though the error comes up, the app is created successfully in the background and there are no missing queries. 

### Steps To Reproduce

1. Do a docker pull and run of appsmith/appsmith-ee:pg
2. Open localhost and go through the usual process of logging in as a new user
3. Now go to admin settings and change the postgres url to the google cloud url [ping me for details]
4. Now sign up as a new user 
5. Import attached application 
6. Fork it into a new workspace
7. Note that it gives an error & though the app is created in the background, the queries are missing for many datasources. 

Video:
https://jam.dev/c/c98d89db-33ed-4abe-b456-c47440cbbc8a
You can go through the entire video for context, however, to see the Issue of missing queries,  forward to 2:19 where Main custom widget page queries are missing, forward to the 2:37 minute of the recording where queries of page API_pixabay and also

[OldApp_DSTesting1.9.24_latest_3rdSep_awsdynapistwilioetc.json](https://github.com/user-attachments/files/16908956/OldApp_DSTesting1.9.24_latest_3rdSep_awsdynapistwilioetc.json)

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted pg image

**Comment by abhvsn** [comment]
@AnaghHegde can you please take a look into this and if this is not reproducible let's close.

**Comment by RakshaKShetty** [comment]
issue is fixed
