### ISSUE TITLE
[Bug]: Error `Unable to import artifact in workspace` When Creating New Git Branch

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#36167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user had issues creating a new branch on the staging environment, In production, it works fine.

### Steps To Reproduce

More info and screen recording with the reproduction steps in [this ticket](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=2588).

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.34

**Comment by riteshkew** [comment]
Issue was resolved as part of v1.36. Upgrading to the latest would resolve the issues.
