### ISSUE TITLE
[Bug]: The Fly way schema history is empty and also seeing a migration error when we are using GCP postgres URI

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Fly way schema history is empty and also seeing a migration error when we are using GCP postgres URI

### Steps To Reproduce

1.  Pull the pg image locally
2. Now once image is up and runnnign from advanced tab change the uri from default to 
3. Now start creating apps
4. Keep instance ideal for some time
5. Now try to use the instance again the instance is down and unable to use

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Deploy preview

**Comment by abhvsn** [comment]
@RakshaKShetty let's see if this happens again after the creation of brand new DB as earlier had the exposed password.

**Comment by AnaghHegde** [comment]
@RakshaKShetty Is this happening on the new db as well?

**Comment by abhvsn** [comment]
Closing this as we haven't seen abrupt deletions after the URI upgrade.
