### ISSUE TITLE
java.net.UnknownHostException: cs.appsmith.com: System error

### ISSUE THREAD

**Issue by kovaxur** [appsmithorg/appsmith#3623]
Hi,
I'm trying to install appsmith, everything seems to be fine, however, when the backend starts, after a few minutes (probably after some timeout), I get the following exception:
![image](https://user-images.githubusercontent.com/9846259/111679043-30dcb100-8821-11eb-90c8-98e758755404.png)

```
 - Opened connection [connectionId{localValue:4, serverValue:33}] to mongo-service:27017
 - Error fetching release notes from cloud services
java.net.UnknownHostException: cs.appsmith.com: System error
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ⇢ Request to GET null [DefaultWebClient]
```

We are behind a company proxy, I didn't really find any proxy settings in the manuals, so I tried adding some java http settings:
-Dhttp.proxyHost=X.X.X.X -Dhttp.proxyPort=YYYY, but it looks like it wont help.

Please help, how could I add a proxy server, or disable the requests towards the internet.

Thanks

**Comment by nidhi-nair** [comment]
@kovaxur  Our server does not as yet support proxies, but we have recently prioritized a fix for this for our datasources (#3311). Please keep an eye out for updates on that issue. 

In the meantime, I'd say you can safely ignore the errors. These failures indicate an inability of your instance to retrieve release notes from our server, but that is the only feature that has been shipped out so far that is affected by this.

**Comment by dncpax** [comment]
I think this should be reopened... with the latest 1.6.17(?) there's now a new Templates section that does not work since appsmith cannot access the appsmith endpoint to get the templates...
Also, in my case, appsmith cannot start unless I point cs.appsmith.com to an internal IP address.

**Comment by Nikhil-Nandagopal** [comment]
@dncpax can you try whitelisting cs.appsmith.com on your firewall?

**Comment by dncpax** [comment]
it's not a firewall, i can reach cs.appsmith.com. it's a proxy, so all requests in this network go through the proxy. afaik appsmith uses netty so there is no automatic support for -Dhttp.proxy java settings.
the only way I can see for users to enable appsmith container access to internet is to somehow configure a transparent proxy for docker... which I haven't been able to do on my own.

**Comment by saccohuo** [comment]
Is any update? I met the same problem.

**Comment by dncpax** [comment]
I'm a user, but I think it's implemented: https://github.com/appsmithorg/appsmith/pull/20929

**Comment by Nikhil-Nandagopal** [comment]
@saccohuo if you are facing a similar issue please raise a new bug with the logs and description of the issue

**Comment by thomas-ej-worm** [comment]
I am facing the same issue:  
https://github.com/appsmithorg/appsmith/issues/35673
