### ISSUE TITLE
[Bug]: Post auto-commit being executed on existing apps, we are seeing uncommitted changes

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#36258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I open an existing app, auto-commit runs successfully. Post that there are still some uncommitted changes which seem related to the datasource auto-commit section that was introduced recently

### Steps To Reproduce

1. Open the master branch of this [application](https://app.appsmith.com/app/automation-test-cases-recent-edit/page-2-654d0bb6eea249205480f84b?branch=master_diff)
2. Auto-commit ran on this branch, but still we can see 4 uncommitted changes
3. On creating a new branch out of this, we see the following differences:
<img width="1404" alt="Screenshot 2024-09-11 at 7 20 52 PM" src="https://github.com/user-attachments/assets/ac0cb295-fe5e-45b1-900e-65e163595745">
<img width="1410" alt="Screenshot 2024-09-11 at 7 20 47 PM" src="https://github.com/user-attachments/assets/f0b4a84c-8738-4a9f-8d0e-64cf8b3e6da3">
4. Repo link - git@github.com:btsgh/ForQATesting_AutomationTestCases.git

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud v1.40

**Comment by riteshkew** [comment]
This is resolved as part of v1.41
