### ISSUE TITLE
[Bug]: Move to Postgres - GCP URI - Performance issues

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#36269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are noticing performance issues while doing basic actions such as creating applications, adding queries/JS Objects, deleting application & workspaces.

### Steps To Reproduce

1. Pull this image: appsmith/appsmith-ee:pg
2. After the image is up and running go to Advanced section in Settings and replace the Appsmith DB URI with the GCP URI.
3. Perform basic actions such as creating applications, adding queries/JS Objects, deleting application & workspaces.

**Expected:** There should be no performance lag & the time taken to perform all these actions should be on par with `release`.

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://jam.dev/c/4417ff82-a952-4388-b878-33261b000ca4

### Version

Self hosted

**Comment by abhvsn** [comment]
@AnaghHegde just like we have expected this morning. Please take a look into this.

**Comment by laveena-en** [comment]
FYI @AnaghHegde performance issues are also being seen on git actions

**Comment by RakshaKShetty** [comment]
The time difference seen
Generate page  took 6.86s, while on release it takes 1.64s
New page - 1.85s, while on release it is 213ms
New DS Save and authorize click on. gsheets - 1.98s, while on release it is 254.94ms
Create new application - 3.01s, while on release it is 472.36ms
Import action to bring up the modal for a json file: 10.04s, while on release it is 1.13s for the same file

**Comment by abhvsn** [comment]
As per Anagh we are seeing the connection pool limit reached exception which is causing the DBOps to queue. We have reached devops to check tghe connection limit set on GCP to verify if this is the issue.

**Comment by abhvsn** [comment]
@RakshaKShetty @shadabbuchh let's retest this as we have moved the DB and VM with same provider, in same region.
DP: http://34.93.159.52/applications

**Comment by shadabbuchh** [comment]
Verified actions such as creating applications, adding queries/JS Objects, deleting application & workspaces. The performance seems to have improved & is now at par with release. However there is still some lag in performance when trying to delete bigger applications: https://jam.dev/c/02eec56a-aaa6-4dd7-971b-0b4cfd00399f

Time taken to delete an app in release:
<img width="1440" alt="Screenshot 2024-09-24 at 12 20 36 PM" src="https://github.com/user-attachments/assets/5b537fe1-e472-4a37-8277-edacb1e83b97">

Time taken to delete an app in the new DP:
<img width="1440" alt="Screenshot 2024-09-24 at 12 20 23 PM" src="https://github.com/user-attachments/assets/6df50887-13c1-49ab-b054-531c5176cfd3">

**Comment by RakshaKShetty** [comment]
![image](https://github.com/user-attachments/assets/dad2b1d7-9166-40f1-8c92-188b8e64aa33)
![image](https://github.com/user-attachments/assets/e3f75fa5-f5f4-4eab-b072-2f6484a9bd02)

**Comment by AnaghHegde** [comment]
@RakshaKShetty Are we good to close this issue? The performance is on par with release.

**Comment by RakshaKShetty** [comment]
@AnaghHegde Did we fix the slowness seen on Delete application

**Comment by AnaghHegde** [comment]
@RakshaKShetty Can you check the dp now?

**Comment by shadabbuchh** [comment]
@AnaghHegde the delete performance issue is still reproducible in the DP. Also I see the error on importing apps that was fixed couple of days ago:
https://jam.dev/c/17df82b5-c3d1-4d10-8e2e-0581596c8370

**Comment by AnaghHegde** [comment]
@shadabbuchh The delete issue is fixed in 4517. The gcp instance does not have latest code. Its the same since last week. I am not sure why the import is failing now.

**Comment by shadabbuchh** [comment]
Tried it on 4517 as well. There seems to be a lag in deleting the apps:
https://jam.dev/c/1f7c54c1-3f0a-48ee-9eae-fe9cddd45520
DP:
<img width="1434" alt="Screenshot 2024-09-26 at 3 37 04 PM" src="https://github.com/user-attachments/assets/431fc068-0a07-4e31-9538-3187aca12178">
Release:
<img width="1416" alt="Screenshot 2024-09-26 at 3 37 26 PM" src="https://github.com/user-attachments/assets/743c4f8f-31fe-4bdd-906e-634a29c28f4f">

**Comment by AnaghHegde** [comment]
#36650 can be used to tackle the performance issues.
