### ISSUE TITLE
[Ticket] postgres upgrade fails with continous waiting for postgres 13 to comeup - Rudra

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#36271]

**Comment by srix** [comment]
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1725452427957749

**Comment by littlebull** [comment]
Hi, can I get additional information about that as I experience the same and can not access the Slack channel?

**Comment by NickVrgr** [comment]
> Hi, can I get additional information about that as I experience the same and can not access the Slack channel?

+1
