### ISSUE TITLE
[Bug]: Show bindings sub-menu position has been displaced 

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#36285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When clicking the `Show bindings` option, the menu appears at a distance from the left section's border. This behavior is a regression, as it functions correctly in the latest version (v1.40).
<img width="368" alt="Screenshot 2024-09-12 at 5 39 02 PM" src="https://github.com/user-attachments/assets/e3e30d78-4ff5-4730-b1fe-3ae59ef70c8b">

### Steps To Reproduce

1. Create a JS Object.
2. In normal view click on the 3 dots next to the JS Object name & then click on `Show bindings`.

**Expected:** The menu should be placed next to the border of the left section

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Issue video log

https://jam.dev/c/9c9184e3-a3ea-4835-999d-3cad21ae17e4

### Version

Cloud

**Comment by btsgh** [comment]
Seems to be impacting other drop-downs as well. 
<img width="1157" alt="Screenshot 2024-09-13 at 9 15 16 AM" src="https://github.com/user-attachments/assets/c940444d-0cd2-4f1a-a6c3-713f84a0a75c">

**Comment by shadabbuchh** [comment]
Verified this on `release`. The sub menu now shows up properly.
<img width="335" alt="Screenshot 2024-09-17 at 3 51 30 PM" src="https://github.com/user-attachments/assets/056173e3-3a3c-4698-8354-588504105590">
<img width="390" alt="Screenshot 2024-09-17 at 3 51 36 PM" src="https://github.com/user-attachments/assets/8dc222b6-b0ec-4c79-9613-5adcfa0b30d5">
