### ISSUE TITLE
[Bug]: The Application rename dropdown UX is broken  

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Application rename dropdown UX is broken  
![image](https://github.com/user-attachments/assets/3d74a0bd-3abf-4a0c-8afb-a21c74461b45)

### Steps To Reproduce

1. Go to release.app.appsmith.com
2. login to application
3. go to home page
4. create new application
5. try to rename the application
6. the drop-down is displayed in the canvas as in screenshot

### Environment

release
### Severity

High (Blocker to building or releasing)

### Version

release

**Comment by AnaghHegde** [comment]
@RakshaKShetty This would mostly be from release. We do not have any FE changes in this branch,
