### ISSUE TITLE
[Bug]: GCP URI - Logging in with instance admin user throws internal server error for a particular workspace

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#36287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to login as demo@appsmith.com who is an instance admin user, I see an internal server error pop up for a particular workspace. I am able to select other workspaces and work with them, or create new workspaces and work with them. 

### Steps To Reproduce

https://jam.dev/c/871ad014-9945-4fbc-ac34-4a0932a7344a

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted

**Comment by AnaghHegde** [comment]
@btsgh Can you share the logs here please? Since this is specific to a workspace, i would need more information to debug this.

**Comment by AnaghHegde** [comment]
@btsgh This due to the padding issue in encryption. Since all the QA members are using the same external db and same database. But all of you are running the docker locally and hence the Salt used for encryption is different that was causing this failure. Hence closing the issue.
