### ISSUE TITLE
[Feature]: Allow setting page size manually for a table

### ISSUE THREAD

**Issue by nikguhl89** [appsmithorg/appsmith#36290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This feature would allow a user to set the page size for a table manually to a value that would work for their use case. This is available on a lot of other editors, but is not yet on appsmith. This would also allow for onPageChange events to trigger when the page was changed.

### Why should this be worked on?

I am writing an application to pull in game deal information. The api I am using only processes 25 results per request. I was going to limit my page results to 25 so I could just run the api call per page of 25 items. This would also make things easier for api's that return a large amount of data so that the table can display the results more customized for the user experience.

**Comment by Nikhil-Nandagopal** [comment]
@nikguhl89 generally most APIs accept a limit parameter which you can bind to the table page size. If your API has a hardcoded number, you have to manually increase the size of your table to make 25 rows and this will work. Let me know if you are facing any issues with this

**Comment by nikguhl89** [comment]
Thank you for the update, looks like everything is functioning correctly. Is it possible to have an event run on page change without using server-side pagination?

**Comment by Nikhil-Nandagopal** [comment]
@nikguhl89 actually it will trigger onPageChange even if server side pagination is off. Turn it on, configure on page change, turn it off. it should still work

**Comment by nikguhl89** [comment]
So the current issue I am running into is that the api I am using can only process 25 items at a time, when using client side pagination it still returns all results (currently 40) and it will try to process and fail even with the page size set at 25 or under. Is there any way around this while still using the pagination within the table?
