### ISSUE TITLE
[Bug]: Move to Postgres - GCP URI The Billing is not  reflecting on release-customer portal for both enterprise and business keys

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Move to Postgres - GCP URI The Billing is reflecting on release-customer portal for both enterprise and business keys
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e1e579d6-4a09-4301-8d48-4aa691a9d070">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/25de050c-5e03-4b1c-a9a9-7c8438bba22f">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/abdc54d8-4f63-4d5f-89f9-017784dc50b7">

### Steps To Reproduce

1. pull pg locally
2. Add google cloud uri 
3. login to application 
4. go to license page add enterprise license 
5. Now create some usage pulse 
6. Do same for business license 
7. Now checkin customer portal for the total usage 
8. The usage looks blank as in attached screenshot

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

deploy preview

**Comment by abhvsn** [comment]
@RakshaKShetty this is not related to GCP uri or even the Postgres specific change. This should be raised in CS repo and may be happening with specific license. Can we verify if this is the issue with all the licenses?

**Comment by RakshaKShetty** [comment]
Able to see the daa on customer portal fix was from togai side
