### ISSUE TITLE
Response view switcher

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3630]
A multi switcher to switch the response between Table, JSON and Raw. It needs a server-side change to tell the client when a response could be viewed as a table

**Comment by aakashDesign** [comment]
@parth-appsmith We can use the button group component here, also used on Body

<img width="996" alt="Screenshot 2021-12-13 at 12 29 37 PM" src="https://user-images.githubusercontent.com/65771350/145766559-6d74e15a-1019-4b5b-aa76-a8f739c20586.png">
