### ISSUE TITLE
[Bug]: List widget always include opacity from the second Item.

### ISSUE THREAD

**Issue by huylocit14054** [appsmithorg/appsmith#36306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The opacity of the **List** widget is always set at 0.8 for all items except the first item. 
I do not think of any reason for doing so, even when selecting the second item the opacity does not change.

https://github.com/user-attachments/assets/85342560-a871-4807-acb6-9eb1a73cacfb

### Steps To Reproduce

1. Add a list widget.
2. Remove the content and add a text widget to show the title.
3. Select the item and see the behavior of the opacity. 

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Appsmith website

**Comment by Nikhil-Nandagopal** [comment]
@huylocit14054 this is only in edit mode to signify that you can only drop widgets inside the first element. In view mode, there is no difference in opacity
