### ISSUE TITLE
[Feature]: Widget table trigger the enter key when searching

### ISSUE THREAD

**Issue by rblachon** [appsmithorg/appsmith#36321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Need a trigger when the user press the enter key on the search input of the widget table

<img width="298" alt="image" src="https://github.com/user-attachments/assets/08529f0d-f01b-4825-bb9d-dbeca405ddda">

### Why should this be worked on?

For exemple when searching and press enter, we could run backside event

**Comment by Nikhil-Nandagopal** [comment]
@rblachon you can use the onSearchTextChange event to do this

**Comment by Too-Smart** [comment]
@Nikhil-Nandagopal Thanks for your answer.
The problem is onSearchTextChange is triggered every time a charater is entered.

We need to trigger the Enter key that is not triggered by onSearchTextChange.

**Comment by rblachon** [comment]
@Nikhil-Nandagopal Thanks for your answer.
The problem is onSearchTextChange is triggered every time a charater is entered.

We need to trigger the Enter key that is not triggered by onSearchTextChange.
