### ISSUE TITLE
[Feature]: Login (Authentication) that actually works (!?)

### ISSUE THREAD

**Issue by danieltkw** [appsmithorg/appsmith#36384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The bot answered me about the authentication, and something or someone else warned me the bot was wrong. Then, in the chat, I was required to fill out these forms here.  

// In a JSObject
export default {
checkAuthAndRedirect: () => {
if (appsmith.user.isLoggedIn) {
// User is logged in, navigate to the main page
navigateTo('MainPage');
} else {
// User is not logged in, keep them on or send them to the login page
navigateTo('LoginPage');
}
}
}

It gave me this answer about having an authentication that *actually* works and makes sense because I need the user to enter the page only if he made the correct login, and for safe coding if a user is somehow on a page not logged, return to the login. The most crucial part is that the other pages get blocked if the user has not entered them. The user must have the correct credentials or cannot go to the different pages.

### Why should this be worked on?

Well, I need a login feature, this is fundamental for any app that has credentials. I was also required by chat to ask here, so this is a basic procedure. I'm kinda confused if Appsmith doesn't have this yet or If I'm just dumb and don't know how to implement xD. As I was warned on chat, I imagine that it doesn't. 
For any app with a login, the user must only access the following pages if logged in.

**Comment by Nikhil-Nandagopal** [comment]
@danieltkw if you are using SSO or the Appsmith in-built login, then you only require to use our RBAC feature (business edition) to control which pages a user has access to and the platform will take care of the rest.
https://docs.appsmith.com/advanced-concepts/granular-access-control/reference/custom-roles#restrict-access-to-page

If you have a custom authentication backend which you must integrate with then you can follow this guide
https://docs.appsmith.com/advanced-concepts/custom-authentication

Hope this helps!
