### ISSUE TITLE
[Feature] Add a onClick trigger for icon widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3639]
## Summary
The icon widget used inside a modal can have an onClick trigger to execute something when the modal is closed

**Comment by somangshu** [comment]
@hetunandu Should this instead be modal property like `onClose/onEscapeKeyDown/onBackdropClick`? Additionally `onRendered` can also be useful.

**Comment by hetunandu** [comment]
@somangshu if i am not wrong, the modal does not really have control over when it is closed. You point is valid that one can close the modal without clicking on the icon too. I think having a listed icon widget with onclick still makes sense. We can probably divide these into two separate issues

**Comment by somangshu** [comment]
@hetunandu [check this out](https://material-ui.com/api/modal/).

What you have suggested makes sense, One follow up question. For example as you suggested in the use case, The `onClick` of the icon will be used to close the model, How do I then add the event ex: `afterClose`?

**Comment by hetunandu** [comment]
Let's divide this up into two issues

- Add a onClose event for a modal widget which will get triggered whenever for any way the modal is closed

- Icon widget is not listed in the widget today. Lets add an icon widget with the onClick event for use cases where the icon click matters

**Comment by somangshu** [comment]
The second requirement to get the icon button as a separate widget will be taken up in #4353. 

In this issue, we will be resolving the `onClose` property in the  modal widget
