### ISSUE TITLE
[Bug]: Appsmithbot Chat bug

### ISSUE THREAD

**Issue by bellehop** [appsmithorg/appsmith#36401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Appsmithbot bug occurs if you request to speak to a human agent after the bot answers your query. The bot starts to malfunction and repeat the same messages.

### Steps To Reproduce

1. Go to the help section

![Screenshot 2024-09-18 132310](https://github.com/user-attachments/assets/028f5add-2bfb-47f9-b168-720d8809b704)

2. Select 'Chat with us'
![Screenshot 2024-09-18 132403](https://github.com/user-attachments/assets/5cd21daa-2b43-4f0b-af0c-6c416a8b6996)

3. Ask a question

4. After the bot responds, request to speak with a human agent.

5. The bot will get stuck in a loop and either repeat this message
![Screenshot 2024-09-18 ](https://github.com/user-attachments/assets/8d471826-7091-4194-9906-38e61ec0829b)

Or the bot will repeat its answer to your original query.

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

1.41.0

**Comment by Nikhil-Nandagopal** [comment]
@bellehop thanks for reporting this. This should now be fixed!
