### ISSUE TITLE
[Epic] Git Airgap Oct '24

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#36403]

**Comment by brayn003** [comment]
[In Progress] release_git_autocommit_feature_enabled
[Removed, need addressing] release_git_branch_protection_enabled
[Removed, need addressing] release_git_autocommit_eligibility_enabled

[Needs removal] release_drag_drop_building_blocks_enabled
[Not present] ab_show_templates_instead_of_blank_canvas_enabled

[Not present] release_git_cleanup_feature_enabled
[Not present] release_git_server_autocommit_feature_enabled
[Removed] release_git_connect_v2_enabled
[Removed] release_show_partial_import_export_enabled
[Removed] release_server_dsl_migrations_enabled
[Removed] release_git_status_lite_enabled
[Removed] release_git_continuous_delivery_enabled
[Removed] release_git_status_granular_enabled
