### ISSUE TITLE
Make it possible to make snapshot tests. Prepare environment for snapshot testing.

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#36419]
We cannot use snapshot tests, since the local environment and the environment in CI are different.

Related thread:
https://theappsmith.slack.com/archives/C025SE88KNE/p1726734752809939?thread_ts=1726721979.435589&cid=C025SE88KNE

**Comment by sagar-qa007** [comment]
Fixed the chrome version. Re enabling test and verifying results.

**Comment by sagar-qa007** [comment]
Found pixel mismatch, Writing CI for updating screenshot and store in zip file.
