### ISSUE TITLE
[Feature] Ability to configure the Appsmith signature header's content

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3641]
## Summary
We might want to send some extra information inside the signature header that can be used for verification or authentication. To enable this we can make the token configurable via `{{ }}` bindings

## Motivation
Add more information in the appsmith verification header

## Additional Context
https://docs.appsmith.com/core-concepts/connecting-to-data-sources/connect-to-apis/signature-header-in-api-actions

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu why can't the additional information be sent in the header field?

**Comment by hetunandu** [comment]
It can be. This is more of a convenience feature where you can unbundle one token to find everything you would need

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu but is that a good idea? It feels like we're complicating this feature for something that can easily be achieved using the header field.

**Comment by mohanarpit** [comment]
I suggest that we include a library to encode & decode JWTs within Appsmith JS as well. This ensures that users don't have to end up binding specific data into the signature header field. The idea of the signature header was for it to be a consistent token that assures other servers of the origin of the request. If any other custom data needs to be sent to downstream servers, I think including a way for users to encode/decode JWTs will be a much better solution. 

 This would also allow users to create & bind JWTs in other parts of their Appsmith application.

**Comment by mohanarpit** [comment]
Closing in favor of #3806.
