### ISSUE TITLE
[Feature] Expose response headers, specifically response status, in the API action

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3643]
Users would like more control of how to handle their API responses on the basis of their response status codes. We could expose this information in a separate field inside the action object.

**Comment by hetunandu** [comment]
The quick way to do this would be to add a third argument to the function.
```
onError = function (responseBody, params, responseMeta): void
```
If we add this in the first argument, that would be a breaking change. 

The better experience would probably be to be an object structure from which you can deconstruct the items you need

**Comment by nidhi-nair** [comment]
I think we can achieve both elements from what you have suggested above if we keep the response body object as is and use the new paramter as the encapsulated object for all other information. May be something we can follow across the board.

**Comment by reisw** [comment]
+1 for this feature request. Have an api that only returns authentication session information in response headers. Looking to use this specifically https://demo.microstrategy.com/MicroStrategyLibrary/api-docs/index.html#/Authentication/postLogin
