### ISSUE TITLE
[Feature]: Remove isFocus and isDirty prop from evaluations in InputField

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#36446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have noticed that for an onFocus event which sets isFocussed meta value to true of an inputField triggers an evaluation. What is the necessity for triggering an evaluation here, I thought another widget could tap this widget's focussed state but that property does not appear to be accessible there. Is it necessary an evaluation needs to be triggered here can we remove it? If there are multiple input widgets in a page i can imagine evaluations to be frequently triggered just by the user moving his cursor around.

### Why should this be worked on?

Reducing the number of evaluations run on a page will greatly improve the performance of the application.

**Comment by ALOK9442** [comment]
hey @jacquesikot could you please explain a little more about this issue?
