### ISSUE TITLE
[Bug]: Issue: (self hosting)  showing Internal server error, when stop internet, when running locally(localhost:8080) through docker single instance command: cd deploy/docker    docker-compose up -d            can any help to resolve this(or tell where I have to do changes)?

### ISSUE THREAD

**Issue by deepakk0109** [appsmithorg/appsmith#36440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot_20-9-2024_11019_localhost](https://github.com/user-attachments/assets/adb868e6-658f-462a-87ec-ea48e9be0673)

showing Internal server error, when stop internet, when running locally(localhost:8080) through docker single instance command: cd deploy/docker    docker-compose up -d            can any help to resolve this(or tell where I have to do changes)?

### Steps To Reproduce

1. Clone the repo
2. cd deploy/docker
3. docker-compose up -d
4. Open in browser localhost:8080
5. Disconnect the internet

### Environment

Deploy Preview

### Severity

Medium (Frustrating UX)

### Version

Self hosted v1.41.0

**Comment by Nikhil-Nandagopal** [comment]
@deepakk0109 appsmith does not support running without internet except in the air-gapped edition. You will need an enterprise license for air-gapping
