### ISSUE TITLE
[Bug]: DP-4517 regression-Unable to create new workspace on newly signed up user

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

DP-4517 regression-Unable to create new workspace on newly signed up user
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/49ab1a10-7368-4027-ba32-a539e71bf4e4">

### Steps To Reproduce

1. go to https://ee-4517.dp.appsmith.com
2. signup as new user
3. now try to sign up as a new user
4. try to create a new workspace
5. Unable to create new workspace

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

Deploy Preview

**Comment by AnaghHegde** [comment]
This is fixed and he changes are available on the dp 4517. @RakshaKShetty Feel free to reopen this if you are facing the issue again.
