### ISSUE TITLE
[Bug]: App crashes while toggling between queries in a specific app

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#36443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

App crashes while toggling between queries in a specific 
https://github.com/user-attachments/assets/7fe51e53-7040-4fe9-9ed7-555ad061664f

### Steps To Reproduce

Steps:

1.Import the app
2.Navigate to queries section
3.Toggle between the queries and the app crashes

Refer the video attached
Also Cypress test has failed attaching the dashboard link

https://internal.appsmith.com/app/cypress-dashboard/run-details-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10935988191&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail

loom video : 
https://www.loom.com/share/11075b5eecbc4141a35fc00719e451a7?sid=08ddea69-6fd3-42e7-915e-ad55cabf9438

<img width="1363" alt="Screenshot 2024-09-20 at 4 23 39 PM" src="https://github.com/user-attachments/assets/5bf5af2b-0f5b-4378-a17a-065ffaf2668f">

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

Appsmith v1.42.0-SNAPSHOT

**Comment by hetunandu** [comment]
Superseeded by https://github.com/appsmithorg/appsmith/issues/36673
