### ISSUE TITLE
[Task] Update temporary documentation link in private entity deprecation notification

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#36450]

**Comment by pedro-santos-rodrigues** [comment]
When clicking on the "Learn more" link that of the info callout, the following page should be opened in a new tab:
https://appsmith-docs-git-new-package-2-get-appsmith.vercel.app/packages/how-to-guides/pass-date-between-modules


https://github.com/user-attachments/assets/c56cc2ba-f8a7-4109-b4aa-8e8327a5ca05


Then when this feature reaches GA this documentation link should be updated to the public documentation one as mentioned here: https://github.com/appsmithorg/appsmith/issues/36462
