### ISSUE TITLE
[Bug]: DP-4517 regression-> unable to create new roles "Unexpected error toast" is displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

DP-4517 regression-> unable to create new roles "Unexpected error toast" is displayed

### Steps To Reproduce

1. go to 4517 dp 
2. login as admin user
3. go to admin setting click on roles tab
4. Click on add new role button
5. new role is added now click on that role 
6. unable to assign any custom control 

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

deploy preview

**Comment by AnaghHegde** [comment]
@RakshaKShetty I am noticing the similar behaviour in release ee. This is not specific to pg branch.

**Comment by AnaghHegde** [comment]
Closing this via the https://github.com/appsmithorg/appsmith/issues/36489
