### ISSUE TITLE
[Task]: Update packages overview documentation link when inter-module references feature flag is enabled

### ISSUE THREAD

**Issue by pedro-santos-rodrigues** [appsmithorg/appsmith#36463]
### Change required
When the inter-module references feature flag `release_module_reference_enabled` is enabled, the documentation link that exists in the empty state right after creating a new package should be updated to the following documentation preview in Vercel:

| Documentation link trigger point in product | Desired link |
|--------|--------|
| Packages editor empty state <img width="1510" alt="Packages overview documentation link in packages editor empty state" src="https://github.com/user-attachments/assets/2341db0b-6989-410a-bef6-26e6191ec1ae"> | [https://appsmith-docs-git-new-package-2-get-appsmith.vercel.app/packages/overview](https://appsmith-docs-git-new-package-2-get-appsmith.vercel.app/packages/overview) |

### Why is this change needed?
The changes included in the `release_module_reference_enabled` feature flag changed the model of what a module can contain in such a way that instead of a JS Module could contain private queries and JS Objects within it, it can easily just access other Query Modules and JS Modules that belong to the same package. This change contributed to less cognitive load needed, easier learning process of packages, and more productivity of to packages developers.

Therefore, the documentation present when the feature flag is enabled needs to be updated accordingly so that the documentation explain that Query Modules and JS Modules are at the same level and it's possible to pass data between them rather than having private queries and JS Objects withing JS Modules which is what was previously mentioned in the documentation.

**Comment by ashit-rath** [comment]
Fixed in https://github.com/appsmithorg/appsmith-ee/pull/5198
