### ISSUE TITLE
[Bug]: Reverted temporary changes made to a codebase that were never pushed were shown in the change diff in Bitbucket

### ISSUE THREAD

**Issue by MaxSunlife** [appsmithorg/appsmith#36486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I hard coded a value to test something, but reversed the change before I pushed to the repo because that test value was never meant to be part of the update (only a test). However, when I pushed to the repo the change was visible in the repo's change diff page even though it was never pushed. After pushing we pulled to a different environment and confirmed that change was not part of the codebase. So why is it still in the change diff if that change was never pushed and isn't part of the repo? 

![image](https://github.com/user-attachments/assets/69e6b7e1-cfcc-40ae-855c-ccaf06444614)

### Steps To Reproduce

1. make an intended change
2. make a separate temporary change
3. revert the temporary change
4. push intended change to the repo
5. check the change dif to find the temporary change that was never pushed

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Self-Hosted v1.19

**Comment by MaxSunlife** [comment]
Hi Nikhil,

No, that’s the weird thing about it. There were 2 pushes that were part of this change’s branch.


  1.  Was an initial push after making no changes. Immediately after the new branch was created and discard / pull was hit there were 2 changes that needed to be pushed. Likely these were Appsmith specific, we’ve encountered this before, where Appsmith requires updates to projects as part of the tool itself. After I pushed those the new branch showed itself to be up to date. This push was made before any changes happened to the branch. Because of how opaque the Appsmith git implementation is though we cannot even see which parts of the project these (or any) changes took place in. It only tells us the number of items and their general type (like query or page).
  2.  The second push was to 2 JavaScript files (commented out some problem code). There were changes the tool pushed to the page jsons as a result of this but nothing manual was changed there.

Between 1 and 2 I also changed 2 queries to have a hard coded value to test with. I undid those changes before I pushed the JS file updates. Because there was a net zero change between pushes though this should have been invisible to bitbucket. 1 of those 2 hard coded value changes made for testing purposes still shows up in the change diff after the 2nd push though, even though that change is not in the code base itself and is not present when we deploy the code to other environments. This is the oddity we want to investigate.

Do you have time to hop on a call this afternoon to take a look with us in the bitbucket repo?

**Comment by Nikhil-Nandagopal** [comment]
@MaxSunlife ok I understand what you are experiencing now. The changes you are seeing are in the jsonPathKey variable which is actually calculated on the fly and does not need to be tracked via git at all. We can can probably pick up not tracking it as an enhancement but essentially what happened here is that the variable did not get recomputed but did get tracked and therefore showed an older value. I assume you are not seeing any discrepency in the behavior of the application.
