### ISSUE TITLE
[Bug] Unexpected behaviour when deleting multiple widgets consecutively without waiting for dsl update toast

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3649]
## Description
When trying to delete widgets one after the other, if there is a lag in the page that results in a delayed response for update in DSL, the DSL value used for last delete is the one with all widgets present. This means that if I delete 5 widgets, eventually only the 5th one will appear deleted (maintains consistency in data so the page isn't broken, but is incorrect)

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno looks like a dangerous issue

**Comment by rahulramesha** [comment]
This seems to be not reproducible anymore, moved to QA to get it verified in release
