### ISSUE TITLE
[Feature]: Auto height for list containers

### ISSUE THREAD

**Issue by matangilad-fiverr** [appsmithorg/appsmith#36501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow the containers in a list elements to have the option for auto height.

### Why should this be worked on?

To allow creating a list where each element is expandable / collapsable. For example a list where you can show basic data on each element and then more data when user pressed an expand button if interested in a specific entry in the list.

**Comment by Nikhil-Nandagopal** [comment]
@matangilad-fiverr this issue is tracked here #31616
