### ISSUE TITLE
[Task]: Implement pull API to upgrade module instances in application on edit mode

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#36523]
### SubTasks

- Create a new API to trigger the pull-based auto-upgrade for the current branch (git-connected) or the current application (non-git-connected app)
- Build a mechanism to pull changes for the selected version

#### API to pull changes for a specific version
Request:
POST `/api/v1/packages/{branchedApplicationId}/pull?requestPageId={branchedPageId}`
Body:
```
N/A
```

Response:
```
{
  "responseMeta": {
    "status": 200,
    "success": true
  },
  "data": {
    "moduleInstances": [],
    "entities": [],
    "consumables": {
      "modulesMetadata": [],
      "modules": [],
      "packages": []
    }
  },
  "errorDisplay": ""
}
```

Note: The data returned by the consumables API can vary based on the scenario of the version mismatch. 
There are three distinct cases for the version mismatch. 

**Case 1: App imported with module instances connected to version 0.0.4 of PackageA**
_TL;DR: This is the best case scenario where the expected version is present along with other available versions_

```
{
  "responseMeta": {
    "status": 200,
    "success": true
  },
  "data": {
    "packages": [
      {
        "id": "abc",
        "originPackageId": "xyz",
        "packageUUID": "pUUID",
        "workspaceId": "wsId",
        "name": "Package A",
        "icon": "package",
        "color": "#9747FF1A",
        "customJSLibs": [],
        "userPermissions": [
          "publish:packages",
          "manage:packages",
          "export:packages",
          "read:packageModuleInstances",
          "read:packages",
          "create:modules",
          "create:packageModuleInstances",
          "delete:packages"
        ],
        "modifiedAt": "2024-09-18T13:15:16.150Z",
        "modifiedBy": "subrata@appsmith.com",
        "lastPublishedAt": "2024-09-18T13:17:08.934Z",
        "versions": [
          "0.0.1",
          "0.0.2",
          "0.0.3",
          "0.0.4",
          "0.0.5"
        ],
        "activeVersion": "0.0.4"
      }
    ],
    "modules": [
      {
        // Module A
      },
      {
        // Module B
      }
    ],
    "moduleMetadata": [
      {
        // Module A
      },
      {
        // Module B
      }
    ]
  },
  "errorDisplay": ""
}
```
**Case 2: App imported with broken module instances expected version 0.0.4 of PackageA whhen other versions are available**
_TL;DR: Since the expected version is missing the versions array should contain all the available versions but modules and moduleMetadata will essentially be empty_

```
{
  "responseMeta": {
    "status": 200,
    "success": true
  },
  "data": {
    "packages": [
      {
        "packageUUID": "pUUID",
        "name": "Package A",
        "versions": [
          "0.0.5",
          "0.0.6"
        ],
        "activeVersion": "0.0.4"
      }
    ],
    "modules": [//Empty],
    "moduleMetadata": [
      //Empty
    ]
  },
  "errorDisplay": ""
}
```

**Case 3: App imported with broken module instances expected version 0.0.4 of PackageA whhen the entire package is missing**
_TL;DR: Since the entire package is missing the versions array should be empty_

```
{
  "responseMeta": {
    "status": 200,
    "success": true
  },
  "data": {
    "packages": [
      {
        "packageUUID": "pUUID",
        "name": "Package A",
        "versions": [//Empty],
        "activeVersion": "0.0.4"
      }
    ],
    "modules": [//Empty],
    "moduleMetadata": [
      //Empty
    ]
  },
  "errorDisplay": ""
}
```

**Comment by ashit-rath** [comment]
@subrata71 
1. Why is it a PUT rather than a POST?
2. Can this API return the module instances, instance entities, and updated consumable modules?

**Comment by subrata71** [comment]
@ashit-rath It's PUT because it actullay updates the existing module instances but I  okay to change it to POST.
I thought after the pull succeeds the front-end will reload the page that ensures getting what you asked for.

**Comment by ashit-rath** [comment]
> I thought after the pull succeeds the front-end will reload the page that ensures getting what you asked for.

For this to happen, we would have to call 3 APIs, get module instance, get consumable modules and get module instance entities and a package pull may only affect a specific set of module instances so it might not be good to call and wait for these API to succeed where we can just get the updates from the pull API call.
