### ISSUE TITLE
[Bug]: When connecting to the sample database (i.e: movie or sample users) during the development mode I am not able to add them.

### ISSUE THREAD

**Issue by ALOK9442** [appsmithorg/appsmith#36570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
I am facing this issue when I am in development mode
When after adding table widget or any widget related to data, and trying to connect it with the sample database (i.e: movie or sample users) during the development mode I am not able to add them it says "You do not have access to this enviroment. Please contact your workspace administrator to gain access" even tho i am the administrator.
as you can see in left prop panel 
![Screenshot 2024-09-26 172136](https://github.com/user-attachments/assets/29786f2f-037a-414b-8692-e106dfb7bbad)

### Steps To Reproduce

1. you must be in development mode 
2. Select a table widget
3. click on connect data
4.  select movie data or sample users from dropdown or connect data in left panel

### Environment

Release

### Severity

Low (Cosmetic UI issues)

### Version

NA

**Comment by Nikhil-Nandagopal** [comment]
@ALOK9442 you may actually not be the administrator depending on the role assigned to you. You can try going to the queries and directly querying the data to check if it works.

**Comment by ALOK9442** [comment]
Hello @Nikhil-Nandagopal , when I am doing anything related to query or database I am getting this error 
{
    "responseMeta": {
        "status": 401,
        "success": false,
        "error": {
            "code": "AE-ACL-4009",
            "title": "INTERNAL_ERROR",
            "message": "You do not have access to this environment. Please contact your workspace administrator to gain access",
            "errorType": "No resource available for access"
        }
    },
    "errorDisplay": "AE-ACL-4009: You do not have access to this environment. Please contact your workspace administrator to gain access"
}

**Comment by trishaanand** [comment]
@ALOK9442 : Could we get on a quick debugging call? I would like to check the state of your workspace and what exactly seems to be corrupted. Here's my [calendly](https://calendly.com/trishaanand/30min). Thanks!

**Comment by trishaanand** [comment]
This is a setup issue. Client run on local is built from CE repository. Whereas the backend is release.app.appsmith.com which is an EE backend. This caused the error. 

ClientContribution.md needs to be updated.
