### ISSUE TITLE
[Feature]: Creating deployed urls for each environment

### ISSUE THREAD

**Issue by sonali-humanedge** [appsmithorg/appsmith#36616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, the only way to perform testing is in edit. The preview mode seems to have a bug as reported [here](https://github.com/appsmithorg/appsmith/issues/31266). However, the app that is deployed when embedded in another website, there is no way to test the app. It would be a good idea if by a query param or subdomain url we can have a live version of each environment.

### Why should this be worked on?

When using embedding, there is no way to test the application.

**Comment by Nikhil-Nandagopal** [comment]
@sonali-humanedge in the deployed mode, you can just change the query param to environment=staging and it will load the staging version of the application

**Comment by sonali-humanedge** [comment]
@Nikhil-Nandagopal I have tried multiple times to add the query param `environment=staging`. But this doesn't work.

**Comment by Nikhil-Nandagopal** [comment]
@sonali-humanedge apologies this is an issue on our end. We're currently fixing this you can track #31266
