### ISSUE TITLE
[Bug]: All the toast error seems to be broken

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

All the toast error seems to be broken
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/85a1bfb7-8e0f-47a8-a683-e51400919c53">

### Steps To Reproduce

1. go to release.app.appsmith.com
2.create a new application
3.drag and drop a button
4.bind it with modal with none and then with modal 1
6. now see the toast error its broken

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

release

**Comment by albinAppsmith** [comment]
This is fixed by this PR
https://github.com/appsmithorg/appsmith/pull/36643
