### ISSUE TITLE
[Feature]: Better access rights info from the global user context object

### ISSUE THREAD

**Issue by suavdebird** [appsmithorg/appsmith#36646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add appName and workspaceName to the properties in the appsmith global object.

### Why should this be worked on?

This will allow to cross reference the roles you're in with the name of the workspace to verify whether you have the necessary e.g. "Admin - ${workspaceName}".

**Comment by suavdebird** [comment]
# Background
Hi, in our infrastructure it makes sense to have one instance of appSmith that manages multiple environments. This is to simplify the instance management (upgrades, backups, user&groups management, etc..) . Each of our environments (prod, stage, test) are represented by workspaces.
# Use Case 1

Some functionalities need to be controlled per workspace, so we create roles following the default app smith naming convention (<role> - <workspace>, e.g. "Super User - Prod"). Now depending if you do have the Super User rights in a particular workspace or not, we should show a button there or not. The only way to achieve that is to check the role name, but to do that we need the name of the current workspace since the you may have different rights per  workspace.

# Usecase 2
Currently there's no way to tell which workspace am I using at the moment. If we had workspace in the global object we could simply display it at the top of the page.

# Alternative to Usecase 1
this particular usecase could also be satisfied if there was a programatic call to see if the current user has the right to execute a specific data source, which doesn't seem to be possible by any way other than trying to use it. 

I hope this helps. Thanks!

**Comment by Nikhil-Nandagopal** [comment]
@suavdebird thank you for the information!

**Comment by Nikhil-Nandagopal** [comment]
I'm going to close this in favor of #26610
