### ISSUE TITLE
[Bug]: Performance issues faced on nightly adaptive image

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Performance issues faced on nightly adaptive image
1.Create workspace take  time after first workspace creation
2.Page take time to save when queries and js are created
3.Home page -> Create new -> Template -> Select Template -> Use Template - very slow. Also saw `Resource not found` error once or twice
4.Import app [OldAppsDS] is giving internal server error. It gets imported in the background

### Steps To Reproduce

1. pull nightly image locally
2. user postgres uri with RDS its not reproducible in local db
3. perform actions to observe performance issue 

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

production

**Comment by shadabbuchh** [comment]
As saving takes time, code entered in the editor also disappears sometimes:
https://jam.dev/c/9ff1fdfc-4be5-4f17-8e43-4ecfba5eda98

**Comment by btsgh** [comment]
This issue is still seen even on release v1.47: 
4. Import app [OldAppsDS] is giving internal server error. It gets imported in the background.

**Comment by btsgh** [comment]
We are still seeing performance issues even on the v1.47 version. App creation, Loading of app in edit mode, Deploy mode, Datasource test connection etc.
