### ISSUE TITLE
[Bug] Link to whitelisting IP document link is broken

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3666]
The link that shows up on datasources page is broken. 
<img width="706" alt="Screen Shot 2021-03-22 at 3 20 09 PM" src="https://user-images.githubusercontent.com/30255708/111971186-1a38a180-8b22-11eb-9e1c-8b75d4924aee.png">

Correct link: https://docs.appsmith.com/v/v1.2.1/core-concepts/connecting-to-data-sources

Edit: Updated with version in the URL so it never breaks

**Comment by ApekshaBhosale** [comment]
@mohanarpit  why not add whitelist page url rather than datasource? Because I think 'how to' page will be expected here unless we want them to land on datasource page. what do you think?
