### ISSUE TITLE
[Bug]: Workflow scheduler save CTA should be disabled if there are no changes in the form

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#36786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the workflow scheduler screen, the form submit CTA should be disabled if there are no changes to be saved.

### Steps To Reproduce

1. Open workflow scheduler settings and save a schedule.
2. The CTA is still enabled (should be disabled since there are no new changes to save)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Self hosted

**Comment by srix** [comment]
pr is merged
