### ISSUE TITLE
[Bug]: Default Branch Overridden by 'Master' When Opening App via Search Bar

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#36782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you search for an application and launch it via the search bar, it launches the application using the ‘master’ branch even though the default may be something different.

### Steps To Reproduce

Screen recording in [this ticket](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=3065).

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.34.1

**Comment by riteshkew** [comment]
Reducing the priority based on internal discussion.
