### ISSUE TITLE
[Bug]: Edit and Launch buttons fail to appear if mouse pointer is hovering over the Application box while loading webpage

### ISSUE THREAD

**Issue by vipulnayyar** [appsmithorg/appsmith#36804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While loading the page https://app.appsmith.com/applications, if the mouse pointer is hovering over an area where an application box is supposed to load, the `Edit` and `Launch` buttons fail to appear. The mouse pointer needs to be removed away from the application box, for these two buttons to appear normally when the mouse pointer is again returned to the same place.

### Steps To Reproduce

1. Go to https://app.appsmith.com/applications or the same location on your self-hosted setup.
2. Refresh the page. While the site is loading, keep your mouse pointer on one of the application boxes.
3. When all the components of the page have loaded, the `Edit` and `Launch` buttons do not appear, even if the mouse pointer is moved or clicked all over the application box.
4. When the mouse pointer is moved outside the application box and returned, both the buttons appear normally.

https://github.com/user-attachments/assets/794805bd-d28c-470c-a9f7-24ac6e196bbd

 

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud : v1.45.0-SNAPSHOT / Self-hosted : v1.44.0-SNAPSHOT

**Comment by ALOK9442** [comment]
hey @Nikhil-Nandagopal I would like to take up this issue to work on

**Comment by ALOK9442** [comment]
hey @Nikhil-Nandagopal @pranavkanade , I have my solution ready if you could assign me this issue then I can raise the pr as well, thanks!!

**Comment by PrasadMadine** [comment]
Hello @Nikhil-Nandagopal , I'm interested in picking up this issue.

**Comment by ALOK9442** [comment]
> hey @Nikhil-Nandagopal @pranavkanade , I have my solution ready if you could assign me this issue then I can raise the pr as well, thanks!!

hey @Nikhil-Nandagopal , a gentle reminder

**Comment by riteshkew** [comment]
@ALOK9442 I have assigned this to you. Please go ahead and raise the PR.

**Comment by ALOK9442** [comment]
hey @riteshkew @Nikhil-Nandagopal , I am getting this issue in mobile screen like there is nothing like hovering and showing a overlay of edit and launch in smaller screen 
i think I didn't explain properly , so I will upload a video and you can check it , I just want to know is it desired flow or like is it an issue,
issue:- the overlay is not coming on hover and after clicking on it is taking me to page which says this page seems to be blank please add widgets

https://github.com/user-attachments/assets/dfb2ca9f-23b7-4574-a4bd-38cf2d85aa83

**Comment by ALOK9442** [comment]
hey @riteshkew @Nikhil-Nandagopal , I am getting this issue in mobile screen like there is nothing like hovering and showing a overlay of edit and launch in smaller screen and after clicking on it, it takes me to page which says This page is blank please add widgets
i think I didn't explain properly , so I will upload a video and you can check it , I just want to know is it desired flow or like is it an issue,

https://github.com/user-attachments/assets/7ec871fa-e64a-4ff8-9c51-4544f044e219

**Comment by Nikhil-Nandagopal** [comment]
@ALOK9442 this is for desktop not for mobile. there's no hover on mobile

**Comment by ALOK9442** [comment]
hey @Nikhil-Nandagopal , could you help me with this error  
I ran the command to commit the changes 
![Screenshot 2024-10-17 200519](https://github.com/user-attachments/assets/3131d988-e01b-4ccb-bff0-4e9d50425778)

**Comment by ALOK9442** [comment]
hey @Nikhil-Nandagopal @riteshkew , I have raised the pr could you please review it and tell changes if any required,  thanks!!
