### ISSUE TITLE
[Feature] Render as HTML should be an option in the text widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3682]
Today the text widget renders HTML by default, but it should be an option that is default ON and can be turned by the user if necessary.

<img width="330" alt="Screen Shot 2021-03-24 at 3 53 44 AM" src="https://user-images.githubusercontent.com/30255708/112226726-8adfdb00-8c54-11eb-8746-a7e4f049fb6d.png">

**Comment by somangshu** [comment]
note:
- A switch based option should be given in the text property pane to render as HTML
- If the option is enabled the text widget should render the HTML content as it is and not compile it.

**Comment by somangshu** [comment]
@hetunandu can you help us understand what is required here

**Comment by Tooluloope** [comment]
@somangshu @areyabhishek  to be Clear.
1) Once the switch is turned on, it should render as HTML.
2) if the switch isn't turned on and it contains HTML tags, it should just render everything including the Tag as text.
3) if the Switch is turned on but no tags are inputted it should default to <p></p> tag.

**Comment by somangshu** [comment]
@Tooluloope you are right.

Stating again:
- Text widget property pane will have a toggle switch `render as HTML`.
- When its enabled > HTML will render as text (with tags)
- When its disabled >HTML will render as compiled
