### ISSUE TITLE
[Bug]: Query Editor window - Resizable and not fixed!

### ISSUE THREAD

**Issue by tlawrence-TAG** [appsmithorg/appsmith#36847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The query editor window needs to be resizable and not fixed. Currently, it's super tiny and not helpful!

### Why should this be worked on?

Who can write queries in that small of a box?

**Comment by LagunaElectric** [comment]
I agree that it's too small, especially so to be a fixed size, when building larger/complex queries. It should expand to the top of the result pane now that the Use prepared statements toggle has been moved exclusively to the settings tab. It would also be nice to have a drag handle for horizontal expansion. So much unused whitespace on the query editor.

**Comment by rohan-arthur** [comment]
@albinAppsmith @momcilo-appsmith feedback on the query box

**Comment by albinAppsmith** [comment]
@rohan-arthur  yeah this is there in my radar.

**Comment by sebak2003** [comment]
It's a bug more that a feature right? Because the jsobject has full height.

![image](https://github.com/user-attachments/assets/6910d9fb-abf2-4b5f-91ac-5d4bfdb3f7f5)

**Comment by Nikhil-Nandagopal** [comment]
@sebak2003 yes you're absolutely right. The query editor is meant to expand as you write code.
@albinAppsmith can you please provide a timeline for the fix?

**Comment by albinAppsmith** [comment]
@Nikhil-Nandagopal I'm starting with this today and will mostly be available in prod by end of this week.

**Comment by sebak2003** [comment]
@Nikhil-Nandagopal  Similra issue here. Large table with 29 columns is tedius to scroll to edit each column in such tiny place. And below you have tons of empty space without use. 

![cap1](https://github.com/user-attachments/assets/d76381df-568a-4d24-a8d0-479029cdaba8)
