### ISSUE TITLE
[Bug]: Invited users suddenly cannot access their app and missing from workspace shared list

### ISSUE THREAD

**Issue by imajiddiffa** [appsmithorg/appsmith#36856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some of our apps which has already shared to specific users cannot be accessed by said user and also the users are missing from the workspace shared list after checked by admin. This happens intermitten and if left unchecked, not returning to normal. But after clicking add new workspace, the user suddenly able to access their app again and showing on workspace shared list.

### Steps To Reproduce

1. Create app
2. Invite users
3. Use it for a while
4. User suddenly cannot access their app, getting 404 page
5. Admin check the workspace shared list, the user is missing
6. Admin create a new empty workspace
7. User can access the app again and showing on the workspace shared list

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Self hosted - v1.44. happening on 1.39 but patching to latest still not solving the issue

**Comment by trishaanand** [comment]
This sounds like a corruption of cache line for the particular user. Creating a new workspace clears the cache line which then leads to recomputation of the cache line. 

@imajiddiffa : Would you know what steps the user take to reach this corrupted state?

**Comment by imajiddiffa** [comment]
@trishaanand we're not entirely sure what causes it. what we know is when it happened, we've tried to create a new workspace+fork app, invite the users to that new workspace and user can use the app again.

but after a while, even on new workspace, user cannot access it again. 
also, when on manage user menu, when changing betwee general settings and members tab, sometimes the user is not shown correctly or mostly missing. after refreshing a few times, it shows again

**Comment by trishaanand** [comment]
@imajiddiffa : This is concerning behaviour that unfortunately we haven't observed before. Could we get on a debugging call to try and reproduce this? : https://calendly.com/trishaanand/30min?preview_source=et_card
