### ISSUE TITLE
[Feature] Support array of conditions for hidden field in query pane editor

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3687]
The hidden field only supports one clause right now, but we should add support for an array that `ANDs` all clauses so that the more complicated forms can be rendered with checks for multiple conditions.

What it looks like right now:
```
"hidden": {
            "path": "prop_path",
            "comparison": "operator",
            "value": "absolute_value"
          }
```
What it should be:
```
"hidden": [
    {
        "path": "prop_path1",
        "comparison": "operator1",
        "value": "absolute_value1"
    },
    {
        "path": "prop_path2",
        "comparison": "operator2",
        "value": "absolute_value2"
    }
]
```

**Comment by nidhi-nair** [comment]
Can we increase the scope for this change to support a condition like the following? This example is only to show what kind of condition needs to be supported.

```
hidden = prop_path1 == "value1" || (prop_path2 == "value2" && prop_path3 == "value3")
```

**Comment by sumitsum** [comment]
Hi @ApekshaBhosale would the fix for this also take care of https://github.com/appsmithorg/appsmith/issues/1803 ?

**Comment by ApekshaBhosale** [comment]
Yes but the structure is little different. @sumitsum
