### ISSUE TITLE
[Feature]: Access responseMeta for Query Modules (Packages)

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#36884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Regular queries have the `responseMeta` property, but for Query Modules used inside an app, it is not possible to access the response meta.

### Why should this be worked on?

Users may want to check the response meta, for example, check if the execution was successful or not by using `responseMeta.isExecutionSuccess`, which is not possible if they are using packages.

**Comment by sonali-humanedge** [comment]
What is the plan for this?

**Comment by ashit-rath** [comment]
@sonali-humanedge Apologies for the delayed reply, we have added this property in query modules and you can expect this to be available in next week's release i.e v1.47.

**Comment by sonali-humanedge** [comment]
@ashit-rath thanks for the update
