### ISSUE TITLE
[Bug]: Phone number widget does not have setValue function

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#36916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user reported an issue where she found there is an inconsistency in the phone number widget compared to other inputs widgets.
All input widgets support the setter function, but the phone number widget does not have it

### Steps To Reproduce

1. Drag and Drop a phone number widget named PhoneNumber
2. Add a JSObject and create function
3. Try typing `PhoneNumber.` and you will see a list of options as part of the autocomplete
4. You will notice there is no setValue function for this

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Please open a new feature request rather than treating this as a bug.
