### ISSUE TITLE
[Task]: Survey of test coverage on action selector feature

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#36966]
### SubTasks

We want to reduce the manual tests overall, and one of the identified areas of heavy manual intervention is action selector.
The scenarios are listed [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A1), and this task is to fill in the 4th column `Test spec`, i.e., identify those methods that already have automated test coverage.

**Comment by sneha122** [comment]
Marking this as closed
