### ISSUE TITLE
[Bug] Changing JS in the tabs deletes all widgets in the tab

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3696]
Srijan lost all his work with this issue
### Steps to reproduce the behaviour:

1. Drag a tab widget
2. add widgets in the tabs
3. convert it to js
4. edit the js and make an error
5. All the tabs and widgets are lost forever

## Solution
Disallow dynamic creation of tabs and allow dynamically setting tabs as visible or not

**Comment by srijanshetty** [comment]
I lost data again today. This time with the dynamic visible option. Just toggling JS on off deletes and wipes off all data. @Nikhil-Nandagopal

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal @srijanshetty As an immediate fix for this critical issue, we'll be adding a panel mechanism ( like the table widget's columns property) which disallows JS binding in the tabs, however, allows users to use JS for the `isVisible` property of the individual tabs within the panel.
