### ISSUE TITLE
[Bug]: In application embed mode get all packages in the workspaces is throwing 401 leading to re authentication

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#36963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The user has embedded the app in their website. The first page is loading fine, but when navigating to the second page by clicking a table row, it asks for authentication. The packages call is returning as unauthorized. The user has admin access to the workspace, so it shouldn't be a permissions issue.

### Steps To Reproduce

1. Create an app with 2 pages
2. In the first page have a button which on click navigates to 2nd page
3. Make the shareable and copy the embed link from settings
4. Use the link in an iframe and click on the button, the app would now require authentication

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

1.45

**Comment by ashit-rath** [comment]
@sonali-humanedge This issue is fixed, you can expect the fix in this week's release.

**Comment by sonali-humanedge** [comment]
@ashit-rath thanks for the update. When should I expect the release to happen?

**Comment by ashit-rath** [comment]
@sonali-humanedge It is scheduled for 24th
