### ISSUE TITLE
[Bug]: MongoDB Replica Set is not enabled

### ISSUE THREAD

**Issue by matheusF-cavalho** [appsmithorg/appsmith#36975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a container with the appsmith image, I configured the environment variables, and added my database with Replica Set, but it gives the error that it is disabled.
![image](https://github.com/user-attachments/assets/035abf34-5495-4342-85d5-c964fe4ee548)
my mongo user is configured as readWrite, admin and clusterMonitor
![image](https://github.com/user-attachments/assets/cc07fdbe-2109-4907-bf09-2d3ffc8fa153)

### Steps To Reproduce

create a container in rancher with the appsmith/appsmith-ee docker hub image
configure the environment variables according to your mongo database with replica set

return
![image](https://github.com/user-attachments/assets/0d4529c6-e485-4b11-b6b0-00aecc86998f)

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Rancher v2.8.5

**Comment by Dmmesserschmidt** [comment]
Same problem

**Comment by Nikhil-Nandagopal** [comment]
@Dmmesserschmidt @matheusF-cavalho is this related to Appsmith? I don't know why you mentioned rancher in the issue description. Which version of appsmith are you deploying? 
Are you using docker, k8s, or building from source?

**Comment by matheusF-cavalho** [comment]
@Nikhil-Nandagopal the appmith version used is v1.47, we are using kubernet K8S, the appsmith image used is appsmith/appsmith-ee, the error happens when we try to connect an external bank, both in the appsmith interface and in K8S.
When we try to upload the K8S container the error above is the result, when we try through the interface, the application crashes and we need to upload a new one.

**Comment by pratapaprasanna** [comment]
Hey @Dmmesserschmidt @matheusF-cavalho . Can you trying accessing mongodb from a sample pod in the same cluster?
We have seen cases where we have seen the same issue if the db is not accessible from the pod

**Comment by matheusF-cavalho** [comment]
@Nikhil-Nandagopal @pratapaprasanna . I managed to upload the container from the following connection string mongodb+srv://SimAppsmithUser:K66%3DEKl52xQiRyl@hostinterno/?authSource=SimAppsmithDB&replicaSet=RSMongoDEV&retryWrites=true&w=majority&tls=false, using the MONGODB_URI variable, the container is running normally, however Inside the interface in the settings it just loads.
![image](https://github.com/user-attachments/assets/9c3f9ec4-7144-4b1b-879a-5008f110d04d)
