### ISSUE TITLE
[Bug] install.sh delete docker.env file on linux Centos

### ISSUE THREAD

**Issue by ghost** [appsmithorg/appsmith#3699]
## Description

When I run $HOME/install.sh and create self hosted installation in $HOME/appsmith folder if is present a $HOME/docker.env file is deleted.

### Steps to reproduce the behaviour:

1. backup a copy of $HOME/appsmith/docker.env file
2. delete $HOME/appsmith folder
3. run $HOME/install.sh again
4. With ls -la not find docker.env in $HOME/

### Important Details
 - Version: Self-Hosted v3.7 [from $HOME/appsmith/docker-compose.yml]
 - OS: CentOS Stream release 8

**Comment by sharat87** [comment]
Testing steps:

1. Download `install.sh` script using the curl command from the documentation.
2. Create a file called `docker.env` with some dummy content with a command like `echo my awesome secret stuff > docker.env`.
3. Now run the install script with `bash install.sh`.
5. Confirm the installation proceeds and finishes as expected.
6. Now verify that the `docker.env` file you have created in step 2 has not been tampered with. Run `cat docker.env` and you should see `my awesome secret stuff` as the output.
