### ISSUE TITLE
[Bug]: File data more than 500kb cannot be passed in this.params

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#37045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When uploading the file data using multi part file upload API, if we are passing file data in params, then we get an error `org.springframework.web.reactive.function.client.WebClientRequestException: Unable to parse content. Expected to receive an array or object of multipart data`

https://github.com/user-attachments/assets/66f622e0-8fd0-454a-a289-259ab05883a9

### Steps To Reproduce

1. Create a file upload API with multipart format
2. Create a filepicker and upload a file more than 500kb
3. Create jsobject and call the file upload api by passing in the file data in params
4. Use the file data from params in the api

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.47

**Comment by shanid544** [comment]
From the recorded video and from the error message its clear that issue with input of fileName value - {{this.param.file.name]}} (there is one extra square bracket). that's why we are getting parse error.

Suggested Fix:
Update the input format to correct the square bracket issue:
{{this.param.file.name}}

Do we need validations for these fields?
![Screenshot from 2024-10-24 14-23-15](https://github.com/user-attachments/assets/a24c919c-0652-49e2-b0df-25de2249711d)

**Comment by shanid544** [comment]
This is not a bug

**Comment by shanid544** [comment]
@sneha122 @Nikhil-Nandagopal @Nikhil-Nandagopal @rohan-arthur Do we need to consider this as a BUG

**Comment by sneha122** [comment]
@shanid544 Thanks for checking this out, even if you remove the square bracket and try to upload the file with more than 500kb, then we get a parsing error as shown in the video, the square bracket was simply a miss from my end and that's not actually the cause of the issue

**Comment by shanid544** [comment]
@sneha122 Please try with type as File. (I am not able see selected type)
![Screenshot from 2024-10-24 16-47-58](https://github.com/user-attachments/assets/04aec87d-812b-47f7-9358-e70a246d2f5a)
I am able to upload

**Comment by sneha122** [comment]
Thanks @shanid544 for looking into this, in my application also the file type is selected, but I get error. Upon checking this further, I realised that this is for a specific file which is of 530kb and my hunch was it always throws error for >500kb files which is not true, looks like this specific file might have some encoding/parsing issues. I will close this issue for now. If in future we see this issue for more such pdf files, we can reopen and investigate. Until then we have a workaround to pass fileIndex and send the file using Filepicker widget object instead of params.
