### ISSUE TITLE
[Bug]: Import of larger applications is failing with internal server error on postgresdb with v1.47

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#37057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I import the attached application, I see an internal server error. On refresh the app is seen and user can go ahead and configure the datasources

### Steps To Reproduce

1. Docker pull v1.47. 
2. Put in a postgres DB uri value in the Admin settings
3. On restart, create a new workspace and import the attached application 
4. Note it fails with an internal server error
[OldApp_DSTesting1.9.24_latest_3rdSep_awsdynapistwilioetc.json](https://github.com/user-attachments/files/17504035/OldApp_DSTesting1.9.24_latest_3rdSep_awsdynapistwilioetc.json)

Note: Also, we cannot work with gsheets post this failed import, as it goes to an erroring out release-cs url.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.47

**Comment by abhvsn** [comment]
For me the import took around ~1.7sec on local setup, can you let me know if this is not the case for you?
<img width="542" alt="Screenshot 2024-11-06 at 3 30 29 PM" src="https://github.com/user-attachments/assets/425ab988-c7ca-4292-aa55-c0eaa6722ae0">

**Comment by abhvsn** [comment]
Closing this, please open if we see this issue again
