### ISSUE TITLE
[Bug]: Title is too close to the input element need some padding to align with other styles

### ISSUE THREAD

**Issue by sans-byte** [appsmithorg/appsmith#37053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2024-10-24 114244](https://github.com/user-attachments/assets/08219016-5aa9-431d-acac-2e7409ab4618)

### Steps To Reproduce

1. Pickup any element from UI elements and drag it to the main canvas.
2. On Right we can see a panel to edit that UI element, look for title on top

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by sans-byte** [comment]
I would like to work on this and open a PR assign it to me @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@sans-byte this is not an issue we want to invest in fixing. You can have a look at our inviting contributions tag to find issues we're happy to receive contritions to
