### ISSUE TITLE
[Feature]: External User / Groups / Roles Management

### ISSUE THREAD

**Issue by muji786** [appsmithorg/appsmith#37075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The ability to programmatically create / update / delete - users / groups / roles externally from Appsmith

### Why should this be worked on?

For organizations that do not have SCIM syncing , having the ability to create / update / delete - users groups and roles would make user provisioning much easier rather than going through the manual process of logging into appsmith and going through that process

**Comment by Nikhil-Nandagopal** [comment]
@muji786 we're working on this here #32298 We're exposing an API that you can use to trigger this. You can reach out to the team on slack to get access to this. I'm closing this issue
