### ISSUE TITLE
[Bug]: Performance lags seen on v1.47 with postgres db

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#37071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Various actions on the appsmith local instance when configured with postgres db are having performance delays

### Steps To Reproduce

Try the following actions after taking a pull of appsmith v1.47 locally, and setting it up to connect to postgres db
1. App creation, 
2. Loading of app in edit mode, 
3. Deploy mode, 
4. Datasource test connection, 
5. Send test email in admin settings 

[6:05](https://theappsmith.slack.com/archives/D038MLNPR4H/p1729773327816889)

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.47

**Comment by laveena-en** [comment]
Performance lag is also seen on git operations

**Comment by abhvsn** [comment]
Closing this, please open if we see this issue again!
