### ISSUE TITLE
[Bug]: GSheet Authorization fails on the imported app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#37085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

GSheet Authorization fails on the imported app

### Steps To Reproduce

1. Docker pull v1.47.
2. Put in a postgres DB uri value in the Admin settings
3. On restart, create a new workspace and import the application which has gsheet datasource
4. Unable to authorize it

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.47

**Comment by abhvsn** [comment]
@RakshaKShetty GSheet verification is going through for the imported app as well, can we please verify this once again?
<img width="905" alt="Screenshot 2024-11-06 at 3 37 09 PM" src="https://github.com/user-attachments/assets/57e917f3-37ea-421a-b18b-63de257391e7">

**Comment by abhvsn** [comment]
Closing this, please open if we see this issue again!
