### ISSUE TITLE
[Bug]: DatePicker widget validation invalid within a Form when Min date is today and current day selected

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#37083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When setting the **Min date** to the current date by using `{{moment().startOf('day')}}`, the DatePicker can select the current date, but the form becomes invalid and the Submit button is disabled. However, if clicking Today, the form is valid and the Submit button gets enabled, although it is using the same date that was picked before.

[Ticket](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=cnv_1dzejqq4)

### Steps To Reproduce

1. Add a DatePicker widget within a Form widget.
2. Set the **Min date** = `{{moment().startOf('day')}}` and set **Time Precision** = 'None'.
3. Pick today's date by clicking on it in the calendar. Note that the form is invalid and the Submit button is disabled.
4. Click Today to automatically select today's date. Note that the Submit button gets enabled.
5. 
Expected behavior: The form should be valid and the Submit button enabled in both scenarios when today's date is selected.

### Public Sample App

https://app.appsmith.com/app/untitled-application-2/page1-671b3fd7de92ab7dd5fce582

_No response_

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/cf3184c9f7c3421ab6d942c039cb677e

### Version

v1.48

**Comment by hebase** [comment]
@Nikhil-Nandagopal @carinanfonseca @rahulbarwal @somangshu Could you please help me understand the timeline for solving this bug?

**Comment by sonali-humanedge** [comment]
@Nikhil-Nandagopal @carinanfonseca @rahulbarwal @somangshu Could you provide an update on this bug?

**Comment by rahulbarwal** [comment]
Hey @sonali-humanedge, @hebase 
We are evaluating this and will prioritize soon, we will keep you updated.

**Comment by rahulbarwal** [comment]
Hey @sonali-humanedge, No, this will be released in next tagged version.

**Comment by sonali-humanedge** [comment]
Noted. When is that scheduled for?
