### ISSUE TITLE
[Task]: Setup new nightly instance running on postgres

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#37097]
Ref: https://theappsmith.slack.com/archives/C06CG2HNUKB/p1729754638510859

Name: nightly-pg(New Instance)	
Tag: appsmith-ee:nightly	
Url: https://nightly-pg.appsmith.com/	
Cluster type: uat-cluster	
Update frequency: once in 2hrs between monday to friday	
Description: Instance to test EE features for nightly tag with Postgres DB

**Comment by AnaghHegde** [comment]
Done via https://github.com/appsmithorg/cloud-deployment/pull/653
