### ISSUE TITLE
[Feature]: NocoDB data source

### ISSUE THREAD

**Issue by LucBerge** [appsmithorg/appsmith#37107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

 A new data source for NocoDB

### Why should this be worked on?

The NocoDB community is desperately looking for a dashboard tool in order to visualize data. If you implement it, the NocoDB community will rush to use appsmith.

https://github.com/nocodb/nocodb/issues/9223

**Comment by Nikhil-Nandagopal** [comment]
We already have this feature request tracked here. You can follow it #16877
