### ISSUE TITLE
[Bug]: The datasource name is not getting updated in the bottom pane 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#37118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The datasource name is not getting updated in the bottom pane 

### Steps To Reproduce

<img width="936" alt="Screenshot 2024-10-28 at 3 55 44 PM" src="https://github.com/user-attachments/assets/0a9a17e3-e4f2-4d9b-a8b9-05ff9fc36834">

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by shubham88fru** [comment]
Hi @kamakshibhat-appsmith @Nikhil-Nandagopal @rohan-arthur, if anyone of you can give me some more details on how to replicate this issue and no one already working on it, I'll be interested in giving this a shot.

Please let me know.

Thanks.

**Comment by skjameela** [comment]
@kamakshibhat-appsmith changed one is database here below users is table name im thinking thats why it is not changing correct me if im wrong ?

**Comment by albinAppsmith** [comment]
Hello @shubham88fru,
Appreciate your interest in taking this up, but this is something we need to fix internally. So kindly look into something from [Good first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22). :) 

@skjameela the items below the search bar is table names and the users which @kamakshibhat-appsmith pointed out is datasource name.
