### ISSUE TITLE
[Feature] Use text widget as label along with input widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3712]
1. Today input widget requires a text widget to act as a label
2. We can reduce the effort by allowing users to drop an input widget that always gets dropped with a text widget
3. If the user doesn't want a label, they can delete the text widget

## Developer Handoff Link
https://www.figma.com/file/O1tKizBK5SHhWPcPT4RWIs/Input-Updates-Label-and-Tooltip?node-id=2%3A1

**Comment by somangshu** [comment]
As an alternative the user can also use a new input widget property say `label=string`, When this property is used a label is displayed with the input.

**Comment by areyabhishek** [comment]
Yes that could work if the user has control over the look and feel of the text. Like alignment options, text size, etc

**Comment by somangshu** [comment]
This was taken up with #4024
