### ISSUE TITLE
[Bug] The application are not displayed to user when shared in View Mode

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3713]
Steps to reproduce:
1) Add an application (Admin Role)
2) Now add multiple widget into the application
3) Click on the share button
4) Share the application as View mode to XYZ email ID 
5) Now login into XYZ with View Role
6) Click on the Share button
7) Now add an email ID (ABC)and select role as View 
8) Now Login to ABC Organisation 
and observe the application 

Observation :
User is not displayed with an empty organisation name and no application are displayed.

Expectation:
Application should be accessible to user when an View user has shared application in View mode

**Comment by mosinuga** [comment]
We seem to be experiencing this problem as well. It seems to be erratic. If the user is changed to admin and then changed back to viewer, it seems to be working as expected.
Is there any fix that is being looked at?

**Comment by mohanarpit** [comment]
Yes, we are working on triaging the issue on high priority. Thanks for the data point around changing roles which causes the applications to show up. Will be helpful for us to zero in on the problem.
