### ISSUE TITLE
[Bug]: Cannot deploy AppSmith-ce using the latest Helm Chart (2.1.0)

### ISSUE THREAD

**Issue by Shaltz** [appsmithorg/appsmith#37134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm just trying to deploy appsmith on one of my kubernetes clusters with the latest helm chart (2.1.0). 
I use the default values (meaning I havent changed, edited or uncommented anything in the values) except for the ingress part.
The 2 mongodb related pods (mongodb-0 and mangodb-arbiter-0) keep on failing 
whith a crashLoopBackOff error. 

The message in these pods logs is the same:

mongodb INFO  ==> ** Starting MongoDB setup **
mongodb INFO  ==> Validating settings in MONGODB_* env vars...
mongodb INFO  ==> Initializing MongoDB...
mongodb INFO  ==> Writing keyfile for replica set authentication...
/opt/bitnami/scripts/libmongodb.sh: line 760: /opt/bitnami/mongodb/conf/keyfile: Permission denied

### Steps To Reproduce

Follow the Kubernetes installation guide.
when the mongodb pods are deployed, they cannot start because of the error mentionned above.

### Environment

Deploy Preview

### Severity

Critical (Broken Production apps)

### Version

Self Hosted on Kubernetes, Helm chart 2.1.0

**Comment by Shaltz** [comment]
I tried deploying the 3.4.3 helm chart from the helm-ee.appsmith.com repo.
Exact same error... :(

**Comment by Shaltz** [comment]
Just tried with the appsmith-ce chart version 2.2.0.
Same error :(

**Comment by pratapaprasanna** [comment]
Can you try cleaning up all the old pvcs and give it a shot ?
