### ISSUE TITLE
[Bug] UX : End Tour option must be displayed to user on the Tour Pop up 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3714]
Steps to reproduce:
1) Navigate to application
2) Click on Welcome tour
3) Now navigate through the app 
and observe the pop up

Observation:
End tour option is not displayed on the Pop up however this is placed on the header.

Expectation:
Since the user focus is on the Pop up that is helping him to navigate or travel through the app it would be great help to display the  "End Tour" option on the Pop Up

**Comment by rishabhsaxena** [comment]
![image](https://user-images.githubusercontent.com/1944800/131658397-fd57eb54-a9bb-4e16-bb79-cababf33e257.png)

we have a skip tour button now
