### ISSUE TITLE
[Bug] Table : The header of the table does not align with the data  alignment set in property pane 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3715]
Steps to reproduce:
1) Add a table 
2) Bind a query to table (Considering the query since we get large data and it is easy for observation)
3) Now click on the Property Pane 
4) Now scroll down to Font Style,Text Align,Vertical Alignment
and any changes done with these is not displayed to the header of the table 

Observation:
It is observed that the any changes done with these is not displayed to the header of the table 

Expectation:
The changes must be applicable to header of the table
![Screenshot 2021-03-26 at 3 47 22 PM](https://user-images.githubusercontent.com/71753653/112617210-aca2b300-8e4a-11eb-8c17-571c88a0f1e3.png)

**Comment by areyabhishek** [comment]
Closing this issue. The header title now aligns with the body of the text. We don't want to apply other styles to the header because it won't visually look good. 
![Uploading Screen Shot 2021-05-27 at 12.14.30 AM.png…]()
