### ISSUE TITLE
[Task] Analyse the JSObject creation flow metrics

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#37151]
This task analyses the logs when:

- JS object is created and we copy paste another huge JS object into this one, typically when we paste a jsobject which creates 35-40 new actions, the update API times out.

**Comment by sneha122** [comment]
The log analysis is done by following the traces mentioned here: https://onenr.io/0VwgZL0K0QJ

Considering JS object which is creating 40 new actions: https://onenr.io/0oQDqnmGNwy
Each action is created with createAction function call. From the traces above we can see that if create action takes ~17s of time, 1st component takes around ~14s, 2nd component takes around 2s and last one takes around few ms.
<img width="783" alt="Screenshot 2024-11-11 at 8 04 03 PM" src="https://github.com/user-attachments/assets/c807a25d-79b7-4108-8252-254f952eeddd">

After analysing the logs, we can see that there are three components that are causing delays:
1. When we check if the name is allowed or not -> This component takes 80-90% of the total create action time, if we optimise this function we can take care of most of the timeout issues
3. Fetching the page data from DB -> This is the second time consuming part, it takes around 5-7% of the create action time
4. Saving the actions in DB -> This takes around 3-5% of the create action time (Only in exceptional cases it takes more)

We should definitely prioritise and fix 1st component and subsequently rest of the components can be taken up.

CC: @rishabhrathod01

**Comment by sneha122** [comment]
Closing this issue and will create separate tasks for each optimisation proposed here
