### ISSUE TITLE
[Bug]: A-force issue with downloading PDF file

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#37192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This users API call to fetch a PDF works fine in Postman but fails in Appsmith with an error stating that charset=binary is unsupported. They have tried changing their accept header but that didn't work.
`org.springframework.http.InvalidMediaTypeException: Invalid mime type "application/pdf; charset=binary": unsupported charset 'binary'
`

https://theappsmith.slack.com/archives/C0341RERY4R/p1729182780165509

### Steps To Reproduce

1. Create an API which fetches pdf file

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.47

**Comment by shanid544** [comment]
@sneha122 Could you please provide the API which you tried. since it is working for me with this API - [link-pdf_API](https://www.irs.gov/pub/irs-pdf/f1040.pdf)

**Comment by sneha122** [comment]
@shanid544 Thanks for checking this out! this is a user's specific API which has content type configured with charset of binary, hence the parsing error.

**Comment by shanid544** [comment]
@sneha122 , https://theappsmith.slack.com/archives/C0341RERY4R/p1729182780165509, no access to this. could u please provide any snaps, or screen-record

**Comment by sneha122** [comment]
Hi @shanid544 Thanks so much for your interest in this issue! I’ve already made some progress on it, would you like to pick up a different issue instead?

**Comment by sneha122** [comment]
Moving this to done as the user will fix the PDF api to accept content type in correct format and we have also provided  solution on how they can open this PDF response in a new tab:

```
async getPDFAndOpenInNewTab() {
        const res = await <API_name_that_fetches_pdf>.run();
        const uint8Array = new Uint8Array(res.length);
        for (let i = 0; i < res.length; i++) {
            uint8Array[i] = res.charCodeAt(i);
        }
    
        const blob = new Blob([uint8Array], { type: 'application/pdf' });
        const dataUrl = URL.createObjectURL(blob);
        navigateTo(dataUrl, {}, "NEW_WINDOW");
}
```
