### ISSUE TITLE
[Feature]: Ability to have custom attributes for users

### ISSUE THREAD

**Issue by muji786** [appsmithorg/appsmith#37212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Sometimes Information about Appsmith users exists in systems outside of Appsmith. With user attributes, you can bring this information into Appsmith and store it on the user object – across all of your Appsmith apps.

### Why should this be worked on?

You can create and add attributes to users to enable custom experiences in Appsmith. Admins can create and apply attributes to any Appsmith user. When building Appsmith apps, you can reference attributes through the appsmith.user object to control functionality. Attributes are secure by default: bad actors cannot spoof data passed into queries that reference attributes.

**Comment by Nikhil-Nandagopal** [comment]
@muji786 we have this feature tracked here #36757 You can follow that issue
