### ISSUE TITLE
[AR] Response tab/table update

### ISSUE THREAD

**Issue by alex-golovanov** [appsmithorg/appsmith#37223]

**Comment by alex-golovanov** [comment]
https://www.loom.com/share/0584cc03faea4a61b09b30a8e7e276fd?sid=b260d208-28e7-48cd-814d-8aa208571aaa

**Comment by albinAppsmith** [comment]
@alex-golovanov  closing this task as we already have a task for this.
https://github.com/appsmithorg/appsmith/issues/35290
