### ISSUE TITLE
[Bug] Fork and edit buttons can both appear simultaneously

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#3722]
## Description
Fork and edit buttons can both appear simultaneously

## Steps to reproduce:
[TODO]

<img width="368" alt="Screen Shot 2021-03-23 at 11 47 27 PM" src="https://user-images.githubusercontent.com/1944800/112634156-3dd05480-8e60-11eb-9e10-02a2d0475ef6.png">

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena can we merge this?
