### ISSUE TITLE
[Docs] Update information on firestore database URL

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#3726]
https://docs.appsmith.com/datasource-reference/querying-firestore#fetching-database-url

As mentioned in the docs the Database URL is not present in the code snippet anymore

The Database URL need to be formed using the project settings > firebase project ID in the following manner

`your-project-id.firebaseio.com`

**Comment by Nikhil-Nandagopal** [comment]
@vihar can you please update this

**Comment by KishkinJ10** [comment]
I am a beginner can i work on this?? can you guide me how should i start?

**Comment by Nikhil-Nandagopal** [comment]
Hi @KishkinJ10 you can work on this. This is the guide for updating our documentation.
https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md

**Comment by mohanarpit** [comment]
This is already done. Closing this issuue.
