### ISSUE TITLE
[Feature]: Integration to Neo4j Aura via Cypher (GQL)

### ISSUE THREAD

**Issue by Flyer-Boy** [appsmithorg/appsmith#37282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Neo4j Aura Graph database Integration to retrieve and create/update data via Cypher/GQL.  

### Why should this be worked on?

In May 2024, ISO published a GQL standard language for querying Graph data databases (https://www.iso.org/standard/76120.html). This is as relevant as SQL for RDBMSs and opens the door to a new type of application that can be developed using Graph instead of RDBMSs. 
GQL is almost entirely based on Neo4j's Cypher, and now, most (if not all) Graph database vendors will include QGL as a query language. Having an integration to Neo4j Aura via Cypher/GQL would enable developers to start building Graph applications. There are new approaches to developing applications using Graphs (read my article: https://medium.com/@marcospinedo/a-new-approach-to-application-development-using-cypher-gql-graphs-7d191e0c55d3).

**Comment by Nikhil-Nandagopal** [comment]
I'm just going to link this to the original ticket #14197 
It will make sense for it to be implemented as part of that
