### ISSUE TITLE
[Feature]: Execução de Função de Aplicação no Workflow | Application Function Execution in Workflow

### ISSUE THREAD

**Issue by VulgoFelp** [appsmithorg/appsmith#37305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Gostaria de sugerir a possibilidade de executar uma função de uma aplicação diretamente na configuração do workflow. Dessa forma, sempre que um endpoint específico for acionado, essa função seria automaticamente chamada para todos os usuários atualmente logados na aplicação.

I would like to suggest the ability to execute an application function directly in the workflow configuration. This way, whenever a specific endpoint is triggered, the function would automatically be called for all users currently logged into the application.

### Why should this be worked on?

No meu caso, essa função chamaria uma consulta SQL que garantiria que os dados exibidos na tela para todos os usuários logados estejam sempre sincronizados e consistentes. Esse recurso seria extremamente útil em cenários onde é essencial que todos os usuários tenham informações atualizadas ao mesmo tempo, após uma determinada ação.

In my case, this function would run an SQL query to ensure that the data displayed on the screen is synchronized and consistent for all logged-in users. This feature would be extremely useful in scenarios where it is crucial that all users see updated information simultaneously after a particular action is performed.

**Comment by Nikhil-Nandagopal** [comment]
@VulgoFelp I think what you are looking for is a way to integrate websockets into the application because that would be the only way I can think of to implement this. 
One way to work around this today is to update the information in the backend and continuously poll information on the frontend. Let me know if there is another challenge you are facing
https://docs.appsmith.com/build-apps/how-to-guides/set-up-websockets
https://docs.appsmith.com/build-apps/how-to-guides/setup-polling

**Comment by VulgoFelp** [comment]
O método atual, utilizando polling contínuo, resulta em um loop constante
de consultas, o que pode impactar significativamente o desempenho do
sistema, especialmente em ambientes de produção. Seria ideal que as
atualizações ocorressem apenas quando o endpoint fosse chamado, eliminando
a necessidade de verificações contínuas e otimizando tanto o consumo de
recursos quanto a eficiência do aplicativo.

The current method, using continuous polling, results in a constant loop of
queries, which can significantly impact system performance, especially in
production environments. Ideally, updates would only occur when the
endpoint is called, eliminating the need for continuous checks and
optimizing both resource consumption and application efficiency.

Em seg., 11 de nov. de 2024 às 05:25, Nikhil Nandagopal <
***@***.***> escreveu:

**Comment by Nikhil-Nandagopal** [comment]
@VulgoFelp you can use a websocket to achieve this efficiently
https://docs.appsmith.com/build-apps/how-to-guides/set-up-websockets

**Comment by VulgoFelp** [comment]
Could you give me an example that I can use for my example above? @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@VulgoFelp the documentation link I shared explains how to use websockets.
You will need to setup a backend server to send socket data to the frontend.
