### ISSUE TITLE
[Bug] Abnormal UX when trying to reposition/edit a widget 

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#3730]
## Description
1. When hovering over `widget label + gear icon` the cursor stays `grab` rather than `pointer`, which doesn't give out a sense that it is clickable.
2. Even when the cursor is visually out of a widget it stays `grab` and allows widget repositioning.

### Steps to reproduce the behaviour:
1. Try editing / repositioning any existing/new widget.

https://user-images.githubusercontent.com/13262095/112749376-a560de00-8fdf-11eb-8da5-701d9874821f.mov

**Comment by Nikhil-Nandagopal** [comment]
@pskanade thanks for opening this issue! We appreciate the time you took to give us this feedback. We'll work on improving the D&D experience

**Comment by aswathkk** [comment]
Looks like this issue is happening only on Firefox.
The CSS property `cursor: grab` is only working on Firefox and not in Chromium-based browsers in my test. This might be the primary reason for the issue I guess.

FYI: I was testing in a Ubuntu machine.
