### ISSUE TITLE
[Feature]: Definir Altura Fixa e Tela Cheia Responsiva | Set Fixed Height and Full-Screen Responsive Design

### ISSUE THREAD

**Issue by VulgoFelp** [appsmithorg/appsmith#37306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Gostaria de sugerir a inclusão da possibilidade de definir a altura fixa para os componentes na aplicação, similar ao que é feito no Power Apps, da Microsoft. Esse recurso permitiria o desenvolvimento de aplicações totalmente responsivas, otimizadas para dispositivos móveis e tablets, onde todo o conteúdo se ajusta perfeitamente à tela inteira, sem exibir barras de rolagem.

I would like to suggest adding the ability to set a fixed height for components in the application, similar to how it is implemented in Microsoft's Power Apps. This feature would allow the development of fully responsive applications, optimized for mobile devices and tablets, where all the content fits perfectly into the entire screen without showing any scroll bars.

### Why should this be worked on?

A intenção é possibilitar a criação de aplicações que se adaptem 100% à altura e largura da tela dos dispositivos móveis, oferecendo uma experiência de usuário muito mais fluida, sem a necessidade de rolar a página. Isso seria extremamente útil para desenvolvedores que desejam criar interfaces otimizadas para celulares e tablets, garantindo que o layout seja aproveitado ao máximo, independentemente do dispositivo.

The goal is to enable the creation of applications that adapt 100% to the height and width of mobile device screens, providing a much smoother user experience without the need for scrolling. This would be extremely beneficial for developers who want to create interfaces optimized for mobile and tablet devices, ensuring that the layout is fully utilized, regardless of the device being used.

**Comment by Nikhil-Nandagopal** [comment]
@VulgoFelp this issue is being tracked here #4630
