### ISSUE TITLE
[Bug] Firestore where condition values are always treated as strings

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3733]
The "Where condition value" for Firestore actions, when getting multiple documents from a collection, only supports string values. If we set it to filter for `GT 5`, it should be setting the value `5` as a number, instead it does this as the string `"5"`, which results in Firestore not returning any results.

**Comment by arturokunder** [comment]
Possible duplicate of #6060 ?

**Comment by mohanarpit** [comment]
Thanks @arturokunder , you are right. Closing this in favour of #6060.
