### ISSUE TITLE
[task] PRD for webhook response

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#37359]
Please share what is  expected behaviour if custom return type is mentioned . if not are we defaulting to current response type which includes workflow runid.

also include acceptance criteria, what is the concurrency expected etc

**Comment by srix** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/37359?planning-poker) with Zenhub @ayushpahwa

**Comment by infinitetrooper** [comment]
[PRD](https://www.notion.so/appsmith/Webhook-Response-131fe271b0e28187aa15f6920bd0bbc9)
