### ISSUE TITLE
[Feature]: App URL to include custom Workspace information

### ISSUE THREAD

**Issue by muji786** [appsmithorg/appsmith#37416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

At the moment, the default behavior of appsmith is that every app that gets created gets a URL like **app/product-catalog** .
It means that if apps get forked, it follows a convention like **app/product-catalog-1** . With many apps, a convention like that could become difficult to manage.
What could be more useful is the ability to include workplace information in the URL ... For example **app/finance/product-catalog** and **app/accounting/product-catalog** to have same APP name just as part of different Workspaces

### Why should this be worked on?

This feature can help with scaling and proliferation of apps with proper names belonging to specific workspaces without going down the route of adding product-catalog-1 or product-catalog-2 etc.

**Comment by muji786** [comment]
If https://github.com/appsmithorg/appsmith/issues/37074 this gets implemented, perhaps a little more thought would need to be put in on how this requested enhancement could work

**Comment by Nikhil-Nandagopal** [comment]
@muji786 instead of adding this to the app URL, we will consider adding it directly to the appsmith object as part of #26610
