### ISSUE TITLE
[Bug]-[8000]:Table widget should not show scroll bars when it's not focused or being hovered on

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3744]
Today the table widget shows scroll bars even when we don't hover over it. Hovering or interacting with the table widget should reveal the scroll bars. 

<img width="416" alt="Screen Shot 2021-03-29 at 6 17 35 PM" src="https://user-images.githubusercontent.com/30255708/112838880-2d67e600-90bb-11eb-8cd8-9d4fceffe15c.png">

**Comment by momcilo-appsmith** [comment]
@somangshu this has already been done and is already in the table handoff file.
Here: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=8%3A7176

**Comment by dilippitchika** [comment]
Table headers being tracked in here - #6518. Using this issue to track the scrollbars showing up.

**Comment by dilippitchika** [comment]
Observation
1. The scroll on the height appears when the last row of the table doesn't fit the space available -- This we can fix with dynamic height.
2. Scrollbars are always visible even when my mouse is not on the table -- We should fix this

**Comment by dilippitchika** [comment]
Updated the issue description.
