### ISSUE TITLE
[Bug][Performance] Action Execution delay

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3751]
## Description

The delay between loading the page and calling an execute on an action which is set to execute on page load.
We noticed that although the XHR requests for the pages and layout returned, the subsequent call to execute was delayed by ~20 seconds.

### Important Details
Release 1.4.5

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu could be because large eval time is stalling it? This is on Srijan's app so we can get access to it

**Comment by hetunandu** [comment]
That could be the reason because we always eval once before executing any onLoad actions. Access to the logs/app would help me identify the cause correctly

**Comment by riodeuno** [comment]
@hetunandu Can you mention the specifics of which logs you would need?

**Comment by srijanshetty** [comment]
Happy to help in any way possible :)

**Comment by hetunandu** [comment]
Thanks, @srijanshetty! Could you do the following steps to send me your logs

- Open your console
- Refresh the app, all the logs will get printed on the console
- Wait till all your actions are loaded
- filter your console with this regex string
`/(timeTaken|EVAl)/`
- Make sure all objects in the logs are expanded, especially the time taken ones
- right click on the console and save as...

You can send this file to me so I can diagnose what is taking the most time

**Comment by srijanshetty** [comment]
@hetunandu shared the file on discord.

**Comment by hetunandu** [comment]
Found that the main issue was around the amount of widgets (Tabs widget with many children) on the page that needed an evaluation before we could run the onPageLoad actions. Suggested that @srijanshetty split it across multiple pages to improve performance.
