### ISSUE TITLE
[Bug]: Scroll functionality in the API screen looks off in the API screens on selection of a body type as json or binary

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#37576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Scroll functionality in the API screen looks off in the API screens on selection of a body type as json or binary

### Steps To Reproduce

1. Create an application and create a new api
2. Choose the body tab, and from the dropdown choose json or binary
3. Scroll and observe the scroll bar
4. It seems to overflow

https://jam.dev/c/ad46be10-3094-40ca-87f4-b48df587c050

Expected behavior - the scroll bar should be positioned out of the text box as it is scrolling the entire area and not just the text box

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

Cloud

**Comment by alex-golovanov** [comment]
This has been fixed recently in #38135
