### ISSUE TITLE
Update the existing Segmented Control component in ADS to have a hover state

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#37614]
Update the existing Segmented Control component in ADS to have a hover state.
https://www.notion.so/appsmith/Segmented-control-153fe271b0e2805a8bd0f81f97a610b0?pvs=4#153fe271b0e280dbbae5f6b261b72c95

Component: https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/formControls/SegmentedControl.tsx

**Comment by nerbos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-Pod-60507ad1d4b98d00150a2858/issues/appsmithorg/appsmith/37614?planning-poker) with Zenhub @alex-golovanov @ankitakinger @hetunandu
