### ISSUE TITLE
Abstract out the UI component of Segmented Header

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#37612]
- [x] Abstract out the UI component for Segmented Header component containing just the UI structure, without any logic being part of it.
- [x] Get the `selectedSegment` and `onSegmentChange` value from props.
- [x] This should take care of the padding and background for segmented header.
- [x] Allow for children that will have more UI controls. These will be placed on the right side of the segments.
- [x] It should take `options` as props to show the custom segments in segmented header
- [x] Replace the old implementation across the product with this new component, keeping intact the test ids being used for unit & integration tests.
- [x] Add a story in the storybook for this new ADS component.

Component: https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/IDE/EditorPane/components/SegmentedHeader.tsx

Hover state for segments:
Link to design: https://www.figma.com/design/dHNLeHtZqHZgTRLPR8kPHM/Entity-explorer-components?node-id=122-12721
Link to prototype: https://www.figma.com/proto/dHNLeHtZqHZgTRLPR8kPHM/Entity-explorer-components?node-id=122-12754&node-type=frame&t=KgMekgMem8AgJ2dm-0&scaling=min-zoom&content-scaling=fixed&page-id=122%3A12721&starting-point-node-id=122%3A12754

**Comment by nerbos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-Pod-60507ad1d4b98d00150a2858/issues/appsmithorg/appsmith/37612?planning-poker) with Zenhub @alex-golovanov @ankitakinger @hetunandu
