### ISSUE TITLE
Update `onSegmentChange` function logic to get it via props

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#37611]
- [ ] The `useSegmentNavigation` hook uses `pageId` for navigation, while not all IDEs can have the `pageId`. The navigation shouldn't be dependent on `pageId`. Hence, update the onSegmentChange function to use `baseParentEntityId` by getting the `editorType`.

Component: https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/IDE/EditorPane/components/SegmentedHeader.tsx

**Comment by nerbos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-Pod-60507ad1d4b98d00150a2858/issues/appsmithorg/appsmith/37611?planning-poker) with Zenhub @alex-golovanov @ankitakinger @hetunandu
