### ISSUE TITLE
[Bug] Table Row show/Hide :  The eye icon does not update onClick based on show/hide value

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3762]
Steps to reproduce:
1) Add a Table 
2) Click on Property Pane 
3) Bind the Table to API/ Query
4) Now Hide an column
5) Move the same column downwards 
6) Unhide the column
and observe the column hide icon 

Observation:
The column hide icon stay in the same state until moved to the original position

Expectation:
Irrespective of the placement of the column the functionality must be functional

Video:
https://www.loom.com/share/0fec0dea9b2340d1b8a55c6948467dd2

**Comment by riodeuno** [comment]
@prapullac Can we verify if this issue still exists?

**Comment by prapullac** [comment]
@riodeuno The issue does not exists on the current release. We can close the issue.
