### ISSUE TITLE
[Bug]: Docker container crash while "Initializing Replica Set for local database"

### ISSUE THREAD

**Issue by lnxredir** [appsmithorg/appsmith#37656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When installing using Docker compose (Both CE and EE) the container runs fine until it tries to create a local mongoDB, where it crashes and restarts indefinitely, giving the error below:

`2024-11-22T14:41:33.802Z Checking environment configuration
2024-11-22T14:41:33.811Z Configuring database connection URL
2024-11-22T14:41:33.824Z Checking APPSMITH_DB_URL
2024-11-22T14:41:33.828Z Detected local DB
2024-11-22T14:41:33.834Z Initializing MongoDB
2024-11-22T14:41:33.839Z Initializing local database
'/appsmith-stacks/data/mongodb/key' -> '/tmp/appsmith/mongodb-key'
2024-11-22T14:41:33.863Z Checking initialized database
2024-11-22T14:41:33.869Z Initializing Replica Set for local database
/opt/appsmith/entrypoint.sh: line 248:   111 Illegal instruction     (core dumped) mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"
`

OS: Ubuntu 24.04
Docker version: 27.3.1, build ce12230
AppSmith Version: v1.49

### Steps To Reproduce

1. Install Docker via the official method
2. Use docker-compose to install Appsmith (CE or EE)
3. Check the logs and see the crash while creating the local db

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self hosted - v1.49

**Comment by guowei1651** [comment]
I also encountered

**Comment by sharat87** [comment]
This is [documented here](https://docs.appsmith.com/help-and-support/troubleshooting-guide/deployment-error-guides/mongodb-startup-error-postv5). The CPU you're running with is inadequate and is not supported. We recommend using an external MongoDB, perhaps from MongoDB Atlas, and using that instead.

Closing.
