### ISSUE TITLE
Allow `Add tab` customization so that the add items can be changed based on usage

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#37651]
When you click on add tab button, the content seen on the screen needs to be customized so that the items can be changed based on the usage/IDE. This can be different for different IDEs.

**Comment by farzan190** [comment]
can you provide more details about it ?

**Comment by ankitakinger** [comment]
@farzan190 Thank you for your interest. This is part of a project that we are going to start working on, and I will be updating the description for this one. If you're looking to contribute, I would recommend picking up an issue with the labels `Good first issue` or `Community Contributor` or `Inviting contribution`.

**Comment by ankitakinger** [comment]
Not needed.
