### ISSUE TITLE
[Bug]: Clicking an Input gives errors in the console

### ISSUE THREAD

**Issue by LagunaElectric** [appsmithorg/appsmith#37658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you click an Input widget in Appsmith you get two errors in the console:

1. `Executing undefined action`
2. `Failed to fetch`

This doesn't appear to affect app functionality at the time of writing.

### Steps To Reproduce

1. Drag a new input onto the canvas.
2. Open the browser console.
3. Click into the input.
4. Observe the above errors in the console.

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Not a valid issue

**Comment by artyyouth** [comment]
In fact, this is a valid bug, If you have a default value in the input widget, then clear the input widget, the input.text value will remain the same as uncleared...this is a showstopper bug for us to use appsmith...
