### ISSUE TITLE
[Bug]: The server encountered a failure when more than 21 actions were executed during page load with concurrent user access

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#37698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The server encountered a failure when more than 21 actions were executed during page load with concurrent user access

### Steps To Reproduce

1. Create an ec-2 instance with  4 CPUs and 8 GB of memory
2. pull the docker version v1.47
3. create a app with 21 action where each action has a reponse of min 2mb
4. Now share this app with 2 to 3 users 
5. Now try to access the app concurrently with all the 3 users
6. The instance goes down

### Environment

Production

### Severity

Critical

### Version

production

**Comment by RakshaKShetty** [comment]
We have reproduced this issue but debugging is taking time here as we couldn't get the logs

**Comment by drajeshkumar** [comment]
Hi, Can we increase the severity, please?  "Low (Cosmetic UI issues)" doesn't feel right since the app completely goes down.  @Nikhil-Nandagopal @ApekshaBhosale

**Comment by Nikhil-Nandagopal** [comment]
@drajeshkumar we're increased the severity for this
