### ISSUE TITLE
[Bug]: Two different applications on the org - Changing the Datasource config of one app changes the other too

### ISSUE THREAD

**Issue by jainishjain5** [appsmithorg/appsmith#37693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Two different applications on the org - Changing the Datasource config of one app changes the other too

### Steps To Reproduce

Two different applications on the org - Changing the Datasource config of one app changes the other too

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

.

**Comment by Nikhil-Nandagopal** [comment]
Hello, datasources are shared at a workspace level so that it's easy to build new applications inside a workspace
