### ISSUE TITLE
[Bug]: Unable to access the google sheet shared drive files in app.appsmith.com

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#37714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to access the shared drive files in app.appsmith.com
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/20d10287-0ad8-4539-9174-a611a030c723">

### Steps To Reproduce

1. go to app.appsmith.com
2. create new workspace and then a app
3. now go to datasources  section create a new gsheet datasource and authorize it
4. select a file from the shared drive 
5. now we dont see any data in the view data section

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

v1.50

**Comment by sneha122** [comment]
This feature is enabled behind a feature flag for now. The feature flag is a tenant based feature flag enabled only for staging instance `release_google_sheets_shared_drive_support_enabled`.

**Comment by sneha122** [comment]
Test party details: https://www.notion.so/appsmith/Test-Party-Google-sheet-shared-drive-150fe271b0e28049bb11cbee5e3c963e
