### ISSUE TITLE
[Bug] Performance degradation in table onRowSelected trigger

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3772]
A user has reported huge delays for the entire application after using v1.4.5. File attached here shows network activity for their self-hosted instance.

[appsmith.zip](https://github.com/appsmithorg/appsmith/files/6228652/appsmith.zip)

**Comment by hetunandu** [comment]
Need to improve our performance tracking since we are not able to compare this with any benchmarks currently

**Comment by hetunandu** [comment]
@mosinuga Can you give us more insight on this [comment](https://github.com/appsmithorg/appsmith/issues/3704#issuecomment-810157824)?

Does updating widgets/actions also feel slow or is it just the first load?

**Comment by mosinuga** [comment]
My colleague thinks the problem may be due to this change, which has made it synchronous, which is also consistent to why we have errors popping up when quickly switching rows or moving to another interaction

We made the storeValue function calls synchronous. You can now access those values directly in any action runs just after creating/updating store values! (#3663)

**Comment by hetunandu** [comment]
> My colleague thinks the problem may be due to this change, which has made it synchronous, which is also consistent to why we have errors popping up when quickly switching rows or moving to another interaction
> 
> We made the storeValue function calls synchronous. You can now access those values directly in any action runs just after creating/updating store values! (#3663)

Hi @mosinuga, that is a valuable insight! Can you share the binding you have with store value in table row change which has the storeValue function call? Also please share the errors you mention here

**Comment by mosinuga** [comment]
This is the errors for that quick switching of rows
<img width="1680" alt="Screenshot 2021-03-31 at 10 50 25" src="https://user-images.githubusercontent.com/43381160/113126341-7466f000-920f-11eb-9b9d-4a71244aab94.png">

**Comment by hetunandu** [comment]
Hey @mosinuga, thanks for this. Please share the binding you have set in your Table onRowSelected action as well so that I can get a complete picture

**Comment by mosinuga** [comment]
Does this help?
<img width="1680" alt="Screenshot 2021-03-31 at 11 37 30" src="https://user-images.githubusercontent.com/43381160/113131880-aa0ed780-9215-11eb-9483-928072139a7f.png">

**Comment by hetunandu** [comment]
@mosinuga, from what I see, this is happening because multiple storeValue calls are running in sync, which is causing the errors. Another question: Are these values you are storing being used in your dropdowns `RI_OPY`, `RI_CSY` `RI_STATUS`, `RI_Certainty` etc. or the last action `ILog_File_Intervention_Count.run()`

**Comment by mosinuga** [comment]
@hetunandu Do you think reversion to asynchronous is an option? I have just been told that the app is unusable as it takes 30 seconds to load!

**Comment by hetunandu** [comment]
> We are using the store values because the multi-choice drop-downs cannot feed off the table using the table.selectedRow feature like the other elements of the form. Instead, they need to be separately triggered because we need to collect multiple values into an array. The store value is used in the multiple-choice drop-downs like this
> 
> <img width="681" alt="Screenshot 2021-03-31 at 14 43 55" src="https://user-images.githubusercontent.com/43381160/113155259-bd7b6c00-9230-11eb-91fc-685a86b48e6e.png">
> 
> 
@mosinuga 
I think this can be solved without storeValue. I can help you in writing this in an optimised way. Are you on our discord server? You can ping me there [at]hetu, or if you feel like, you can also email me at hetu[at]appsmith.com

**Comment by hetunandu** [comment]
Hey @mosinug, I haven't heard from your colleague regarding this issue on discord. Will it be possible to get in touch this week?

**Comment by mosinuga** [comment]
@hetunandu My colleague seems to have been chatting/working with some of your colleagues (Sumit)

**Comment by hetunandu** [comment]
Thanks @mosinuga. I have connected with him on discord and discussing the details

**Comment by Nikhil-Nandagopal** [comment]
Hi 👋 @mosinuga , we've added a few performance updates to appsmith. Your app should be much faster now. Do let us know if you're still facing a problem here
