### ISSUE TITLE
[Bug] Action Dropdown of widget open inappropriately when on the right most corner 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3773]
Steps to reproduce:
1) Add a widget
2) Ensure the property pane is on topmost 
3) Contract the general section 
4) click on the actions dropdown 
and observe

Observation:
It is observed that user is unable to view the entire action dropdown when the property pane is placed in the topmost corner 

Expectation:
The user must be able to view the entire actions dropdown irrespective of the placement 

![Screenshot 2021-03-30 at 5 05 09 PM](https://user-images.githubusercontent.com/71753653/113091477-a412f980-9209-11eb-9993-b048e7b43c6b.png)

**Comment by areyabhishek** [comment]
@prapullac This is one of those cases where a screenshot or a video would be very helpful. Could you please include a video in most issues? It'll save a ton of time.

**Comment by prapullac** [comment]
@areyabhishek : Sorry Abhishek I forgot to include. I have added the screenshot for the same
