### ISSUE TITLE
[Bug] Tab Widget: Hide icon is not functional 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3774]
Similar to Table issue:
Steps to reproduce:
1) Add a tab widget
2) Add  multiple Tab
3) Click on Hide icon 
and observe

Observation:
Tabs will be hidden but icon does not display the same
Expectation:
when the tab is hidden the tab hide icon must be displayed appropriately to user

**Comment by marks0351** [comment]
Was fixed as part of the feature.
