### ISSUE TITLE
Create `filterList` util

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#37769]
Create a util function `filterList`:
- This is a util that can takes `list of items` and `searchTerm` state for easy inclusion of search anywhere
- It returns: `filteredList` using the function parameters

**Comment by nerbos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-Pod-60507ad1d4b98d00150a2858/issues/appsmithorg/appsmith/37769?planning-poker) with Zenhub @alex-golovanov @ankitakinger @hetunandu

**Comment by alex-golovanov** [comment]
Should take filter function, not searchTerm.

**Comment by ankitakinger** [comment]
@alex-golovanov I referred the miro board and call recording and we had finalized on sending the `searchTerm` and `list of items` as params.

**Comment by alex-golovanov** [comment]
> @alex-golovanov I referred the miro board and call recording and we had finalized on sending the `searchTerm` and `list of items` as params.

Sure, still though, search could be done based on other criteria.
