### ISSUE TITLE
[Feature] Need a framework to add sub text to label via editor.json / form.json

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3779]
## Summary
Need support in editor.json / form.json to add sub-text like here (the Hint text): 
![Screenshot 2021-03-30 at 7 16 18 PM](https://user-images.githubusercontent.com/1757421/112999576-b1d66980-918c-11eb-9274-831f7af3512a.png)

It can be used to provide useful info about how to use a query / datasource form field.

**Comment by mohanarpit** [comment]
@sumitsum Any particular place you thought this hint would be useful?

**Comment by sumitsum** [comment]
@mohanarpit I thought it could be used to add the following text as a sub not to Firestore's Timestamp field : "use dot(.) notation to reference nested key e.g. ["key1.key2"]"

**Comment by nidhi-nair** [comment]
@rashmi-rai @ayushpahwa We need to tag this issue to the relevant PR.
