### ISSUE TITLE
[Bug] Editing the date/time in the datetime widget doesn't apply changes

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3784]
The UI for the datetime widget allows users to edit and change the value by directly editing the widget's text, but on focus-lose, the widget reverts to showing the current datetime. This is counter to user's expectations where, if editing is at all allowed, the changes should be impactful. If that is not the case, editing the values in the widget directly shouldn't be allowed at all.

![](https://cdn.discordapp.com/attachments/760761686549463060/826464221554409543/unknown.png)

In the screenshot above, editing at red-arrow is allowed by the UI, but the changes are overwritten immediately on unfocusing the widget.

**Comment by vicky-primathon** [comment]
@sharat87  can you please share me a loom video with the steps to reproduce this error. I am not able to reproduce this issue on release.

**Comment by sharat87** [comment]
This is weird. I don't if its the same issue but I'm noticing different behavior here:

The date and month keep swapping around. This is also noticeable in production. However, I can't reproduce the behaviour described in this issue so if you want, I can close this and open another issue for the following.

https://user-images.githubusercontent.com/120119/114169499-48561800-994f-11eb-95a4-25b33e399780.mov

**Comment by somangshu** [comment]
This is not reproducible, We observed another issue on production. Created that separately.
