### ISSUE TITLE
[Task]: Discuss the product requirement and engineering implementation for adding Analytics events for Native Integrations

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#37850]
### SubTasks

- Discuss with the product team on the actual use case
- Figure out if we can do it on Mixpanel or NewRelic
- Are these events Atomic or can be derived from some other events?
- Are some of these events already present on Mixpanel?
- Are these client side or server side events?
Ref: https://www.notion.so/appsmith/Analytics-14afe271b0e2802c9636e917f92df452?pvs=25

**Comment by carinanfonseca** [comment]
The team had a call with the performance team and as an action item, Rajat will create the integration performance dashboard in Graphana according to our needs. Additionally, I will create the Mixpanel dashboard for other metrics we need.
