### ISSUE TITLE
[Task]: Implement the UI for Request a new Integration

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#37854]
### SubTasks

**UX/UI:**
- Add a fixed bottom bar in the Datasources list page with the text: “Are you looking for something different? Request a new integration.”
- When the button “Request a new integration” is clicked, a modal should open allowing the user to provide: 
   Integration (mandatory)
   Tell us more about your use case (optional)
   Email (optional, pre-filled by Appsmith)
- Ensure the “Request integration” button is disabled if the “Integration” field is empty.
- When the request is submitted, Appsmith shows a success toast message "Thank you! We are looking into your request."
   
[Figma link
](https://www.figma.com/design/kbU9xPv44neCfv1FFo9Ndu/User-Activation?node-id=5998-8874&node-type=section&t=6lW0FVSSmQu5Bx7d-0)

![image](https://github.com/user-attachments/assets/d7ebcbc0-9b56-431b-8762-e94b0f3d5139)

**Metrics:**
- REQUEST_INTEGRATION_CTA to check the number of users who clicked the button “Request a new integration”.
- REQUEST_INTEGRATION_SUBMITTED to check the Number of users who clicked “Request integration” in the modal, with properties:
         - integration_name
         - use_case_description
         - email

**Comment by NilanshBansal** [comment]
@carinanfonseca please validate the product requirements here. 
@AmanAgarwal041 to add the estimations.

**Comment by AmanAgarwal041** [comment]
@carinanfonseca do we open a modal with a form or we redirect it to a url ? If its url where to create it ?

**Comment by carinanfonseca** [comment]
I updated the description with all the details. Let me know if something is missing.
