### ISSUE TITLE
[Task]: Implement the UI for Premium Tag Integrations in CE

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#37853]
**UX/UI:**

- Include Salesforce, Zendesk, Slack, and JIRA as new integrations in the Datasources page, tagged as “Premium”.
- Clicking there, we open a modal with information about premium and upgrading. 
    **If the email domain is relevant**  [Figma link](https://www.figma.com/design/kbU9xPv44neCfv1FFo9Ndu/User-Activation?node-id=5998-11701&node-type=frame&t=6lW0FVSSmQu5Bx7d-0)
    - Provide a secondary CTA: Learn more about Premium (opens appsmith.com/pricing)
    - Provide a primary CTA: Schedule a call (opens a calendly llink - to be added)
 
    **If the email is not relevant** [Figma link](https://www.figma.com/design/kbU9xPv44neCfv1FFo9Ndu/User-Activation?node-id=5998-12192&node-type=frame&t=6lW0FVSSmQu5Bx7d-0)
    - Display an Email field (pre-filled by Appsmith)
    - Provide a secondary CTA: Learn more about Premium (opens appsmith.com/pricing)
    - Provide a primary CTA: Submit (sends the information to Mixpanel/Segment)
    - After closing the modal, show a success toast message "Thank you! The Appsmith Team will contact you shortly."
  
<img width="712" alt="Screenshot 2024-12-03 at 17 14 48" src="https://github.com/user-attachments/assets/ec07d1f8-4c37-4c86-8268-5bcfc89985d9">

  
**Metrics:**
- PREMIUM_INTEGRATION_CTA: Number of users who clicked on a Premium Integration (Salesforce, Zendesk, Slack, JIRA) on the Datasources page
- PREMIUM_MODAL_RELEVANT_LEARN_MORE: Number of users who saw the modal for relevant email domains and clicked on the Learn more button, with property: integration_name (e.g., Salesforce, Zendesk, etc.)
- PREMIUM_MODAL_RELEVANT_SCHEDULE_CALL: Number of users who saw the modal for relevant email domains and clicked on the Schedule a call button, with property:  integration_name (e.g., Salesforce, Zendesk, etc.)
- PREMIUM_MODAL_NOT_RELEVANT_SUBMIT: Number of users who saw the modal for non-relevant email domains and clicked on Submit, with properties:
   integration_name
   email
- PREMIUM_MODAL_NOT_RELEVANT_LEARN_MORE: Number of users who saw the modal for non-relevant email domains and clicked on Submit, with properties:
   integration_name
   email

**Comment by NilanshBansal** [comment]
@carinanfonseca please validate the product requirements here. 
@AmanAgarwal041 to add the estimations.

**Comment by danielmorris-as** [comment]
@AmanAgarwal041 

- Why are we using in-line styling for these new colours? Is this just for testing purposes?
- Tag `fonts-size` should be `10px`.
- My advice to best-practices around accessibility is to enter tag text as "Soon" and "Premium" in the markup, then style with  `text-transform: uppercase;`. The all-caps rendition of this text is more of an aesthetic choice than a practical one.
- `Font-weight` should be `bold`.
- Not sure about embedding a `<span>` within a `<span>`. For best practices I'd suggest the tag itself to be a `<div>` with the inner text being a `<span>`. But this should be an engineering choice in the end.
- Padding settings should be: `padding: 6px 4px`;
