### ISSUE TITLE
Abstract out the UI component for Search & Add bar

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#37888]
- [x] Move the current AddAndSearchBar component to ADS
- [x] Get the `searchTerm`, `onSearch` for Search component via props
- [x] Make sure the add button gets the `onClick` functionality via a prop for allowing it to be customized based on segments & IDEs.
- [x] Make sure the permission to show the add button is also being used via props.
- [x] Allow for optional custom placeholder.
- [ ] Replace the old implementation across the product with this new component, keeping intact the test ids being used for unit & integration tests.
- [ ] Add a story in the storybook for this new ADS component.

Note: No need for conditionally showing the search bar (like the UI segment has only a button), because that can directly be implemented using the ADS button component.

**Comment by nerbos** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-Pod-60507ad1d4b98d00150a2858/issues/appsmithorg/appsmith/37888?planning-poker) with Zenhub @hetunandu @alex-golovanov @ankitakinger
