### ISSUE TITLE
[Task]: Implement the UI for Soon Tag Integrations in EE

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#37924]
**UX/UI:**

- Include Salesforce, Zendesk, Slack, and JIRA as new integrations in the Datasources page, tagged as “Soon”.
- Clicking there, we open a modal explaining we are evaluating it, and we'll inform them when this integration is available for them to test. 
- Provide a primary CTA: Notify me
- Show a success toast message "Thank you. Stay tuned and wait for the news!"

[Figma link
](https://www.figma.com/design/kbU9xPv44neCfv1FFo9Ndu/User-Activation?node-id=5998-12172&node-type=section&t=6lW0FVSSmQu5Bx7d-0)

  
<img width="854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNBQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9753c16f338c309305b3d69ec74b346bab31890a/Screenshot%202024-12-03%20at%2017.23.11.png" alt="Screenshot 2024-12-03 at 17.23.11.png" />

  
**Metrics:**
- SOON_INTEGRATION_CTA: Number of users who clicked on a Soon Integration (Salesforce, Zendesk, Slack, JIRA) on the Datasources page
- SOON_NOTIFY_REQUEST: Number of users who saw the modal and clicked on the Notify me button, with property: 
   integration_name (e.g., Salesforce, Zendesk, etc.), 
   email

**Comment by AmanAgarwal041** [comment]
As there were no business logic changes to the implementation other than the license check which eventually gets handled on the business and enterprise edition. Hence nothing new implementation was required specific to EE. 
CE PR is already merged, hence closing this issue as the completed task.
