### ISSUE TITLE
[Bug] Text widget : Same property pane will be opened when moved to next text widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3792]
Steps to reproduce:
1) Add multiple Text widget 
2) Add colour and config to one of the Text widget(Text 1)
3) Focus on "Search for the widget "
4) Enter Keyword "Text"
5) Now click on first Text widget 
Ensure the property pane opens
6) Now click on second Text widget on the entity explorer
and observe

Observation:
It is observed that Only name of the widget changes but the config remains of the first widget
On click also it is same 

Expectation:
The property pane must be respective to the widget

Video:
https://www.loom.com/share/426e801c62274021ab3768d200057a5b

**Comment by marks0351** [comment]
@prapullac looks like the branch that was tested was not harbouring the latest release version changes, it has been redeployed with the latest version. pls, verify.

**Comment by prapullac** [comment]
@marks0351 : Working as expected and hence we can close the issue
