### ISSUE TITLE
[Task]: Create an endpoint in CS for the cloud services proxy to Paragon Proxy API

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#37967]
### SubTasks

- Create an endpoint in CS for the cloud services proxy to Paragon Proxy API. 
- Validate the installation if the request is from a valid one.
- This API will be requested by the Appsmith server to execute the API calls and fetch the data from Paragon for the queried integration.
- It should check for token expiry and refresh token if expired, then make a request to paragon proxy.
- Add error handling for the response if required.

**Comment by NilanshBansal** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Query--JS-Pod-6322a759b3296d249ce5c4ed/issues/appsmithorg/appsmith/37967?planning-poker) with Zenhub @AmanAgarwal041 @sneha122

**Comment by NilanshBansal** [comment]
Setting the final estimate to 2 as per planning poker estimate.

**Comment by sneha122** [comment]
Changes added in this CS Pr: https://github.com/appsmithorg/cloud-services/pull/1769
