### ISSUE TITLE
[Task]: Add support for new plugin type for different sagas

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#37972]
### SubTasks

There are some checks in the codebase for managing different types of plugin, we need to support the new type of plugin.

**Comment by AmanAgarwal041** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Query--JS-Pod-6322a759b3296d249ce5c4ed/issues/appsmithorg/appsmith/37972?planning-poker) with Zenhub @NilanshBansal @sneha122

**Comment by NilanshBansal** [comment]
Completed in the https://github.com/appsmithorg/appsmith-ee/pull/5771
Will be merged with the completed functionality
