### ISSUE TITLE
[Task]: Create Uqi action forms for action apis of paragon integrations

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#37987]
### SubTasks

Ability to create action using uqi forms for paragon type integrations.

**Comment by AmanAgarwal041** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Query--JS-Pod-6322a759b3296d249ce5c4ed/issues/appsmithorg/appsmith/37987?planning-poker) with Zenhub @NilanshBansal @sneha122

**Comment by NilanshBansal** [comment]
Duplicate to https://github.com/appsmithorg/appsmith/issues/37962
