### ISSUE TITLE
[Task]: Ability to bind the widgets after running the queries for paragon integrations

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#37988]
### SubTasks

When the action is run for paragon integrations, then it should be able to bind the data to the widget.

**Comment by AmanAgarwal041** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Query--JS-Pod-6322a759b3296d249ce5c4ed/issues/appsmithorg/appsmith/37988?planning-poker) with Zenhub @NilanshBansal @sneha122

**Comment by NilanshBansal** [comment]
Closing this as the API is already present to do this. 
cc: @AmanAgarwal041 @sneha122
