### ISSUE TITLE
[Feature]: Add currentPageName, workspaceName and appName to appsmith context object

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#38046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The following information should be accessible as properties under the Appsmith namespace.

Workspace name
App name
Page name

For example {{ appsmith.currentPageName }} (or similar) should return the name of the page the function is called on.

### Why should this be worked on?

Why should this be worked on?
This allows for scripting to be written without knowing what page it will end up on. For example we have a script that uses navigateTo() to navigate to the same page the user is already on and update the query parameters. This works great, but we have to tweak it for each page or refer to a variable in a JSObject that has the page's name. If we could programmatically collect the page's name, then we could copy that script to each of our pages without having to edit it.

Workspace name is also very useful as many users use it as a kind of test/production environment split, If you could write scripts that notice that you are in a specific workspace, you could cause certain things to function differently if you are in test mode or production mode.

**Comment by Nikhil-Nandagopal** [comment]
We want to add the current environment variable as well to this.

**Comment by sneha122** [comment]
> We want to add the current environment variable as well to this.

@Nikhil-Nandagopal Created separate feature request for environment variable as making changes in current Pr was causing cyclic dependency issues of dependencies and we may need to do CE and EE split to resolve this. Taking it up separately as it has its own complexities. https://github.com/appsmithorg/appsmith/issues/38306
