### ISSUE TITLE
[Bug] Everytime a row is selected in a table the Property Pane opens 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3805]
Steps to reproduce:
1) Add a table 
2) Close the property pane 
3) Select the row 
and observe 

Observation:
It is observed that the table property pane opens every time the user selects a row 

Expectation:
It is expected that the property pane must not be on selection of a row 

Video:
https://www.loom.com/share/bc92e725fcea41d3ac30c61133a57dc1

**Comment by marks0351** [comment]
@prapullac property pane is shown as soon as a widget is selected so in this case, it will show up. to not have it interfere with the interaction we can drag and move it away from the canvas.

**Comment by prapullac** [comment]
@marks0351 As per above comment closing the issue as it is part of the requirement
