### ISSUE TITLE
[Feature] Add JS library to encode/decode JWT within Appsmith client

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3806]
## Summary

Being able to encode/decode JWT within an Appsmith application will be useful for a lot of users

## Motivation

At times, we want to send some JWT encoded information to backend APIs. Having a way to easily perform this encoding/decoding within Appsmith will make it easier for users to be able to do this.

**Comment by Nikhil-Nandagopal** [comment]
Related to #2430

**Comment by bharath31** [comment]
Will be possible after the release of Custom JS Libs https://github.com/appsmithorg/appsmith/issues/2430
