### ISSUE TITLE
[Docs] Ignoring parameters is not clearly described

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3813]
## Documentation Link 

https://docs.appsmith.com/framework-reference/navigateto

## Describe the problem

`params` and `target` are both optional, but it isn't clearly defined how to ignore only the `params` argument and yet include the `target` argument

## Describe the improvement
If we only want to pass the first `pageNameOrUrl` argument, without passing the rest of the arguments, it should work if we ignore the rest when calling the function. Unfortunately, if we want to include the `target` argument, while ignoring the `params` argument, we must pass `undefined` as the second(`params`) argument.

**Comment by hetunandu** [comment]
This will be fixed by #3132
