### ISSUE TITLE
[Bug]: Action Redesign : Handle the maximum number of characters allowed for function name or show ellipsis after a specified length to avoid overflow

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#38149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Handle the maximum number of characters allowed for function name or show ellipsis after a specified length to avoid overflow. 

### Steps To Reproduce

<img width="1122" alt="Screenshot 2024-12-13 at 1 39 36 PM" src="https://github.com/user-attachments/assets/b6048bd4-8beb-425a-ad11-eb06c4c907cf" />

Also, the same needs to be handled in the function dropdown

<img width="754" alt="Screenshot 2024-12-13 at 1 53 05 PM" src="https://github.com/user-attachments/assets/a21b9c85-a1df-489d-a770-1d43f01f0178" />
<img width="474" alt="Screenshot 2024-12-13 at 1 53 25 PM" src="https://github.com/user-attachments/assets/9ee125b7-71b4-43b8-a021-58f4b6819218" />

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

Cloud/SelfHosted

**Comment by alex-golovanov** [comment]
This has been fixed in #38150
