### ISSUE TITLE
[Bug]: Setting a function to run on page load makes it difficult to access the page during setup.

### ISSUE THREAD

**Issue by kavitakanojiya** [appsmithorg/appsmith#38147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I adding functions to run on page load, it works perfectly when running in deployment mode. However, I should be able to access all the pages for modifications in setup mode.

### Steps To Reproduce

1. Create Page 1, add container and a text element
2. Create Page 2, add container and a text element
3. Go to Page 1 -> JS -> add a function to navigate to Page 2
4. Add this function to run on page load
5. Now, try to access Page 1 in the setup mode. It loads Page 2 due to this function, making it impossible to access Page 1 for modifications.

I have attached the video link (public) below.

### Public Sample App

https://app.appsmith.com/app/untitled-application-1/page2-675bd84b137a525d63a9ef5c/edit/jsObjects/675bda9afdcbec2133de043d

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://drive.google.com/file/d/1X5eyHjoQznBglOjBaqEkgFlFgJ1DjsNL/view?usp=drive_link

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Hello! We have this issue filed here #32524
