### ISSUE TITLE
[Feature]: Allow Appsmith devs to expose utility functions in the global context for the client editor

### ISSUE THREAD

**Issue by jtaylor3rd** [appsmithorg/appsmith#38213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello,

I want to provide a function that can be accessed from any input widget through the widget properties panel. I would like the function to appear in the context list of available functions/objects accessed through mustache syntax:

<img width="1139" alt="Screenshot 2024-12-16 at 4 03 40 PM" src="https://github.com/user-attachments/assets/014015ac-35f1-49a5-a62d-f6fd58c5fb0d" />

I was able to expose a function as an action in this list, but it cannot be invoked:

<img width="1136" alt="Screenshot 2024-12-16 at 4 03 13 PM" src="https://github.com/user-attachments/assets/f1001998-996f-4043-96ce-e698eb1f62eb" />

Note: I am aware of JSObjects but do not want to create one. This function needs to be available for all end-users of the appsmith framework we provide. I also do not want to expose the function through the JSObject tab for modification.

### Why should this be worked on?

In general, I believe it can be useful for appsmith devs to provide global functions to appsmith end-users.

Specifically, I am trying to integrate i18n into the appsmith we plan to make available to users. I've seen an example of [this](https://community.appsmith.com/template/multilingual-app-ai-translations) working for an individual page, but want to provide a solution for all pages without exposing the implementation details through JSObjects.

**Comment by Nikhil-Nandagopal** [comment]
@jtaylor3rd global functions can be provided via our packages feature on the business plan
