### ISSUE TITLE
[Bug] Query Params do not encoded when the datasource url is a binding

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3821]
## Description
Where there is a datasource binding, the client cannot split the URL correctly and sets everything in the datasource URL field. We should extract and split this out in the server and encode the API request's correct parts before executing.

### Steps to reproduce the behaviour:
1. Create an API
2. Add a binding in the datasource instead of a string like `https://example.com.`
3. Add params to the same URL after `?` that need encoding
4. execute the request

### Observation
The params are not encoded.

**Comment by rohan-arthur** [comment]
works now, see #11795
