### ISSUE TITLE
[Bug]: Navigation between Jsobjects not working properly

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#38216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we have multiple pages with each having different jsobjects. If we try to navigate between jsobjects in one page its taking user to different page incorrectly

### Steps To Reproduce

1.Mantain 3 pages with 5 jsobjects in each with different name
2.Select a page and randomly click on different jsobjects.

Expected:
It should go to the clicked jsobject

Actual:
Its randomly navigating to different jsobject in different page.

https://github.com/user-attachments/assets/fa6f0592-4738-4af5-917c-999cad7d5862

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.53

**Comment by shadabbuchh** [comment]
This is not restricted to JS Objects. This can be seen for all queries:
https://jam.dev/c/cd6fe922-f574-4202-87b3-41b4225696ee

**Comment by hetunandu** [comment]
This is a major bug and should have been impossible to be skip past our test cases. Can you share when did this started happening? The Version mentioned is 1.42 which is quite old

@NandanAnantharamu

**Comment by NandanAnantharamu** [comment]
> This is a major bug and should have been impossible to be skip past our test cases. Can you share when did this started happening? The Version mentioned is 1.42 which is quite old
> 
> @NandanAnantharamu

@hetunandu issue seen on version v1.53

**Comment by shadabbuchh** [comment]
Verified on release to be working fine. Thanks.
https://jam.dev/c/c3e49bc4-f145-47b8-8f34-79dc793c8424
