### ISSUE TITLE
[Feature] Allow downloading data from a table as an Excel file

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3822]
The table widget today can already export data as a CSV file, but importing CSV files into Excel is a painful process. Setting the encoding and CSV formatting settings when importing is a fragile and error-prone process.

So, if the table widget can export an Excel file directly, it'd be a lot more convenient export format to work with.

**Comment by somangshu** [comment]
We will we showing download options as a dropdown > [designs here ](https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=2%3A3024)
