### ISSUE TITLE
[Bug] Setting of the API pane is broken

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3823]
Steps to reproduce:
1) Navigate to API Pane
2) Add an API 
3) Navigate to Setting 
4) Refresh the page
5) Navigate to setting
and observe

Observation:
It is observed that the page is broken when navigated to API setting page 

Expectation:
It is expected that page must be displayed to user with functionality

![Screenshot 2021-04-01 at 12 51 03 PM](https://user-images.githubusercontent.com/71753653/113258780-02170e00-92ea-11eb-932e-6e49e9ed9b65.png)

**Comment by hetunandu** [comment]
Not able to reproduce. @prapullac did you create a new org where you saw this was happening? Can you also share the console errors

**Comment by prapullac** [comment]
Hi Hetu 
it is in the old organisation only. Adding the video and console logs as well 
Video :
https://www.loom.com/share/814a7a0e56564e25a3ba7f989dbbb34d

Screenshot:
![Uploading Screenshot 2021-04-01 at 1.11.49 PM.png…]()

**Comment by prapullac** [comment]
@hetunandu : This issue is not reproducible on new API however it is reproducible on older API

Steps to reproduce:
1) Open an existing API 
2)  Click on Setting
and observe

Observation:
The API Setting Pane is broken

**Comment by hetunandu** [comment]
It looks like this fix never got deployed. I have re-run the workflow and will let you know if it was successful to test this again.

**Comment by hetunandu** [comment]
@prapullac Can you verify this now?

**Comment by prapullac** [comment]
@hetunandu  Working as expected hence closing the issue
