### ISSUE TITLE
[Bug] Canvas breaks for new users

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3825]
## Description

A few users on smartlook have a broken canvas that cannot be used
https://app.smartlook.com/org/9b6c5c859e85745d01196fa4/project/e373e3a21d27278fd281d8b0/recordings?filter=e072f0526cba4d894bf7765c0d2f52c94f3950db86a7c623e39fc359c88dc938&playSession=J9j2VR8AOkh&playVisitor=YsZlYJHwx-U

**Comment by somangshu** [comment]
Similar behaviour was observed in #3963. The issue was specific to Safari, In the above case it is Windows and chrome.
