### ISSUE TITLE
[Bug] Child widget tooltips are hidden behind parents

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3826]
## Description

Widget name and other tooltips in a child widget get hidden behind the parent and do not overflow to be completely visible.

This needs a re structure of the stacking contexts of particular elements of child widgets to make them visible.

**Comment by areyabhishek** [comment]
Got this on Discord from Joseph today. https://www.awesomescreenshot.com/video/5274881?key=3653ec9c5719e628e80150ee2026adf1

**Comment by vuiets** [comment]
Closing this as it is a duplicate of [#8415](https://github.com/appsmithorg/appsmith/issues/8415).
