### ISSUE TITLE
[Enhancement] On empty API field if user clicks on "Save As Datasource" info message must be displayed to user

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3833]
Steps to reproduce:
1) Click on "Add an API"
2) Now observe the "Save As Datasource" is Inactive
3) Click on  "Save As Datasource"
and observe

Observation:
It is observed that clicking on the  "Save As Datasource" does not do any action. User might take sometime to understand only after adding data into the API we can 

Expectation:
When user tries to click on the "Save As Datasource" user must be displayed with info message asking user to add the API

**Comment by sumitsum** [comment]
@prapullac can you please check if this problem is valid anymore ?

**Comment by tauantcamargo** [comment]
@areyabhishek hey dude could i get it?

**Comment by mohanarpit** [comment]
@tauantcamargo Thank you for your interest in Appsmith. This is actually not a valid bug any more. Hence, I'm closing it. Would encourage you to volunteer and pick up another "Good First Issue".
