### ISSUE TITLE
[Bug] Clicking a row in edit mode doesn't select a table widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3838]
1. Clicking a row in a table widget doesn't select it.
2. Clicking it only shows the table in a hover state
3. Thus you can't delete tables or open the property pane with a click

**Comment by riodeuno** [comment]
@vicky-primathon Let's remove the e.stopPropagation from the Table.tsx row select handler. This will make sure that the event propagates and lets the property pane open.
