### ISSUE TITLE
[Bug]Hidden page widgets are visible when published

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#3840]
Steps:

1.Make sure you have multiple pages in entity explorer, i.e. page1,page2, and page3.
2.add different widgets to each page.
3.Make sure you click page3 and perform the "Hide" action
4.Now Deploy.

Expected:
1.Except Page3, all other Pages should be visible.

Actual:
1.Page3 widget is visible other pages are not seen

https://user-images.githubusercontent.com/67676905/113337166-09b7d080-9345-11eb-8b30-3da3b5b4c2f9.mov

**Comment by riodeuno** [comment]
@NandanAnantharamu @jsartisan Let's fix this and add a cypress test for this scenario.

**Comment by NandanAnantharamu** [comment]
@riodeuno cypress test is in place, I saw this bug while automating this use-case.

**Comment by Nikhil-Nandagopal** [comment]
@NandanAnantharamu this is not a bug but a slight UX mishap. When deploying you are on page 3 so it is showing only page 3 which is expected. Maybe the right solve here is to rename it from hidden to mark as internal page

**Comment by NandanAnantharamu** [comment]
@Nikhil-Nandagopal when I am highlighting and deploying being on Page 3 it is not showing the other pages if you see, Page1 and Page2 tabs which also need to be taken care of.

**Comment by Nikhil-Nandagopal** [comment]
@NandanAnantharamu that's the expected case. The page is meant to be hidden from the navigation. So it cannot be seen from other pages and other pages cannot be seen from it

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno @jsartisan maybe instead of hidden, we can change it to a page type and call it navigation page or internal page? How does react-router or any other navigation lib differentiate these types of pages?
