### ISSUE TITLE
[Feature] Modal should have customizable sizes

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#3850]
## Summary

As a user I should be able to customize the modal size by changing the size property from the property pane or dragging the borders within the canvas.

## Motivation

If a user wants to use the modal to show more information; ex comprising of tables, charts etc, he should be able to create a bigger modal viewport in order to create his own layout.

**Comment by areyabhishek** [comment]
@somangshu a better way would be allow them to resize the modal by dragging the boundaries. Why not do that instead of giving size options through property pane?

**Comment by somangshu** [comment]
@areyabhishek I agree. This is better is terms of customization!

**Comment by jsartisan** [comment]
@areyabhishek @somangshu I feel just giving 3-4 sizes to users like small, medium, large and huge would suffice every usecase.

**Comment by jsartisan** [comment]
Just got another request for resizing option today.

**Comment by GreenFlux** [comment]
> a better way would be allow them to resize the modal by dragging the boundaries.

Yes, and allow individual anchoring the boundaries to each window edge. This could be used to create a sidebar menu that anchors on the top, left, and bottom, with a fixed width, and navigation sidebar that pops up from a 'hamburger menu'.

**Comment by somangshu** [comment]
> Yes, and allow individual anchoring the boundaries to each window edge. This could be used to create a sidebar menu that anchors on the top, left, and bottom, with a fixed width, and navigation sidebar that pops up from a 'hamburger menu'.

@GreenFlux does this mean that the user should also be able to move the modal position?

**Comment by somangshu** [comment]
@GreenFlux thanks for taking the time to write such a detailed explanation 🙂🙏. Really liked the idea of having a drawer menu for navigation 🚀. In modern design principles like material UI we have examples of bottom sheets, side sheets and full screen dialogue. We are currently evaluating these options as either new widgets or making changes to the current modal. We will discuss this internally and try to quickly come up with solutions.

**Comment by somangshu** [comment]
@marks0351 can the modal resize be the same as widget resize? Also can we change the position on the modal based on props? ex: Two options, Centered or defined offset. Please share a better approach, If any

Another user requested for this feature today.

**Comment by somangshu** [comment]
> Based on a discussion with @marks0351 

Because of a platform limitation, Implementing resize handles need custom implementation. Resize handles today work for a widget only if it has a parent, which is not the case here. He can take this ahead in the following manner.
- Introduce a type property: This tells us what kind of modal we need
    - Traditional: Modal is center positioned with the height and width defined.
    - BottomSheet: Modal is bottom positioned (anchored) with height and width defined.
    - SideSheet: Modal is right/left positioned (anchored) with height (100% and disabled) and width defined.
        - Additional Properties: Alignment: Left/Right
- We also introduce rounded corners

This still is not the appropriate UX as the property pane is going to be in the view port when the above value have changed.

cc: @areyabhishek @momcilo-appsmith @Nikhil-Nandagopal

**Comment by areyabhishek** [comment]
We should introduce a good way to resize the modals instead of introducing the other properties. The main thing people need is a bigger modal. The other properties sound interesting, but not sure if they'll get used.

Different issue, but we also need an animation for opening and closing the modal. Today it pops open abruptly.

**Comment by somangshu** [comment]
@areyabhishek implementing resize handles is a bigger engineering effort and will take time, This is a much requested feature  and hence the above proposed solutions. The side/bottom sheets are also important because they will allow our user to use this widgets for multiple use cases ex: a drawer. 

@marks0351 approx. how much time will be need to implement the resize handle feature?

**Comment by marks0351** [comment]
let me lay down the use cases that need a solve for this. should not take more than a sprint.

**Comment by tomjose92** [comment]
Hey guys, any timeline on when this enhancement will be rolled out?
And what is the final option provided, resizing by drag or by defining height/width

**Comment by marks0351** [comment]
Hi @tomjose92 apologies, this got delayed because of the existing pipeline of features. we will soon update this issue with the details of the timeline and enhancements to Modal widget.
