### ISSUE TITLE
[Bug] Irrecoverable API

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3851]
## Description
The API pane shows the error page when trying to edit the API. This completely blocks the user from editing the API.

> Self-hosted
> 1.4.6
> The action `"GetWarehouseItems" has failed. ERROR: "GetWarehouseItems is not correctly configured. Please fix the following and then re-run: {Unable to find datasource 6038c64d7b83e5140be4ff99}"`
> Editing gets the building site page.
> Copying the now broken APIs also replicates the issue.

`{"responseMeta":{"status":200,"success":true},"data":{"statusCode":"4012","body":"GetWarehouseItems is not correctly configured. Please fix the following and then re-run: \n{Unable to find datasource 6038c64d7b83e5140be4ff99}","isExecutionSuccess":false}}
`

![API error](https://user-images.githubusercontent.com/103687/113442107-0c7df880-940d-11eb-9fc2-ec0b9d7c70e5.png)

**Comment by riodeuno** [comment]
This error occurred when the user was trying to modify a copied API. The modified API works fine.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno any steps or URL to the app so we can debug how this happened?
@hetunandu @ApekshaBhosale looks like a serious problem with the API editor

**Comment by thebf** [comment]
My guess is that the check that silently runs to see if it can delete the datasource when the last reference to is has been deleted misfired somehow and deleted the data source when there were in fact other API calls still referencing it.

If it helps in bisecting this issue: The api call were several iterations of copies and moves across pages as I've been building a multi-page prototype.

It happened after I modified the URL of this last copied API call to remove it's reference to the datasource.

**Comment by hetunandu** [comment]
> My guess is that the check that silently runs to see if it can delete the datasource when the last reference to is has been deleted misfired somehow and deleted the data source when there were in fact other API calls still referencing it.
> 
> If it helps in bisecting this issue: The api call were several iterations of copies and moves across pages as I've been building a multi-page prototype.
> 
> It happened after I modified the URL of this last copied API call to remove it's reference to the datasource.
> 
> New APIs with and without references to new data sources have worked fine too.

Thanks for the details @thebf! Do you still have the action that is crashing the page or is it deleted?

**Comment by thebf** [comment]
I still have the error message as I haven't recreated and reconnected all the API calls yet.

**Comment by hetunandu** [comment]
@thebf 
I would like to see the action object that is stored. 
If you could send me the network responses for actions and data sources, it would help me a lot.
When you refresh your app, all this information is called for via APIs. In your network console could you filter the requests with `/(actions\?|datasources\?)/` regex and send me the responses of these API calls on discord

**Comment by nidhi-nair** [comment]
Lowering the priority of this issue till we have more information on what the database looks like for @thebf

**Comment by nidhi-nair** [comment]
More information on this:

It seems that the user's datasource document went into a bad state. The datasource being referenced in their actions did exist in the backend (not deleted), but did not show any similarity to the domain definition. Attaching document structure for reference. Initial thoughts are to check if it is possible that the update happened as a BaseDomain instead of the Datasource domain.

```
{
        "_id" : ObjectId(<redacted>),
        "pluginId" : <redacted>,
        "updatedAt" : ISODate("2021-04-08T12:00:16.303Z"),
        "deleted" : false,
        "policies" : [
                {
                        "permission" : "execute:datasources",
                        "users" : [
                                "anonymousUser"
                        ],
                        "groups" : [ ]
                }
        ],
        "_class" : "com.appsmith.server.domains.Datasource"
}
```

**Comment by Nikhil-Nandagopal** [comment]
Closing this as we haven't had activity on it for awhile
