### ISSUE TITLE
[Bug] Input widget validation issues

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3860]
## Description

When set to be not required within a form widget, the input widget with type "number" does not accept `undefined` values.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add a form widget, add an input widget into the form
2. Set the input widget to be of type "number"
3. The submit button is disabled, even though the input widget is no a required field in the form

The reason for the above is that the value `undefined` (or for that matter any non number value) translates to the field being `invalid` to which the form widget reacts by disabling the submit button.

### Important Details
Release 1.4.6

**Comment by Daddy2200** [comment]
`delete`

**Comment by somangshu** [comment]
Check for the rest of the input types as well
