### ISSUE TITLE
[Feature] Allow users to copy evaluated values

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3862]
## Summary

Evaluated value popup should have a copy button to copy the evaluated value.

**Comment by ajinkyakulkarni** [comment]
@mohanarpit @ayushpahwa Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/3862?planning-poker)
