### ISSUE TITLE
[Bug] Appsmith Crashes if table has _ in the data

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3865]
### Steps to reproduce the behaviour:
1. fetch all apps from appsmith prod
2. bind it to a table
3. move the table
4. refresh the app
5. The app crashes

**Comment by trishaanand** [comment]
Fixed as part of PR #3887

**Comment by Nikhil-Nandagopal** [comment]
Reopening as this is still happening

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal @hetunandu @nidhi-nair  I believe we've merged a fix for this today. Can we close this?

**Comment by nidhi-nair** [comment]
Yeah, sorry didn't know there was an issue open for it.
