### ISSUE TITLE
[Bug] [Dropdown] Values are not resetting on form submit.

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3866]
Dropdown widgets are not resetting when 'Reset form on success' is set to true.

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan seems to be working for me. Can you please add the steps to reproduce?

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal Closing it as the value get resets to the default value which is expected behavior. Sorry for the confusion.
