### ISSUE TITLE
[Bug] JSON substitution for REST API breaking with surrounding single and double quotes

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3868]
With JSON substitution turned on, if the dynamic binding is not explicitly surrounded by quotes, the parsing is successful. But if we include quotes during usage, the parsing breaks.

Example Body:
```
{
  "key": "{{Input1.text}}"
}
```

**Comment by trishaanand** [comment]
Can't reproduce. Closing for now.
