### ISSUE TITLE
Valid JSON Request is Identified as Undefined in the Expected Value section 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3873]
**Expected Result:**
Expected Value section should accepts the valid JSON Request 

**Request Body:** 
{
“name”: “{{“animals”}}“,
}

**Actual Result:**
Submitting valid JSON Body the Expected Value section identifies the value as 'Undefined'  

**Steps to Reproduce:**
1. Launch AppSmith app in Release Environment 
2. Expand API Pane 
3. Click on Create New
4. Choose method as POST
5. Use the following header - https://f40723136b502119bdb86ecde31d1751.m.pipedream.net
6. Enter the following JSON Request in the Body - 
{
“name”: “{{“animals”}}“,
}
7.Check the value in the Expected Value section 
8.Click on API Settings and Enable the Beta Checkbox
9. Open developer Tool and Navigate to Network tab 
10. Click on Run button 
11. Verify the Response log message in the network section (The name value will be Null)

<img width="1280" alt="Prepared_Statement Undefined" src="https://user-images.githubusercontent.com/35128442/113663902-77a72380-96c8-11eb-83b9-14bd86db6ba6.png">

**Steps to Overcome:**
1. Use the following header - https://f40723136b502119bdb86ecde31d1751.m.pipedream.net
2. Enter the following JSON Request in the Body - 
{
“name”: “{{“animals”}}“,
}
3. Value will be undefined in the Expected Value section 
4. Remove the Double quotation inside JSON Request From "{{"animals"}}" to "{{animals}}"
5. Then again add the Double Quotations which is removed and make it original - "{{"animals"}}"
6. Now, check the value in the Expected Value section

**Comment by hetunandu** [comment]
The quote characters `“` used here are not valid javascript. Did you paste this from some other application or was this typing? The body below works fine
```
{
  “name”: “{{"animals"}}“,
}
```

Notice the quotes inside the bindings are not *italic*
