### ISSUE TITLE
Mock database is not present in Datasource list

### ISSUE THREAD

**Issue by sanjeed5** [appsmithorg/appsmith#3878]
## Description

Couldn't find the mock database to add as a Datasource. 

### Steps to reproduce the behaviour:
1. Signup using Github
2. Follow the tutorial and create a new app with the name given in the tutorial, **under the default organization.** 
3. Click + near DB Queries
4. Click New Datasource
5. No Mock Database listed in the options
![image](https://user-images.githubusercontent.com/40694326/113686638-839ae180-96d8-11eb-8f60-33c6dc89d944.png)

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser: Brave Browser Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)

Note: App was created under the default organization as given.

**Comment by Nikhil-Nandagopal** [comment]
@sanjeed5 thanks for pointing this out! We've now fixed this for all new users :)
