### ISSUE TITLE
[Bug] Copy and paste functionality isn't functional for List widget

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3881]
Steps to reproduce:
1) Add a list widget
2) Now "Copy" a widget (keyboard control)
3) Now Paste the widget
and observe

Observation:
It is observed that the list widget does not get pasted 

Expectation:
it is expected to get pasted when on keyboard action 

Note: Safari (12.1.4) copy option is not functional

**Comment by jsartisan** [comment]
Merged into release #4189
