### ISSUE TITLE
[Bug] Inconsistent editing experience custom chart config

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3894]
## Description

Unlike the Table widget's tableData property control, the custom chart config control doesn't allow JSON strings outside of bindings.
`{{ {type: "", dataSource: {}} }}` works but `{type: "", dataSource: {}}` does not.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to custom chart config property in chart widget's property pane
2. Try entering `{type: "", dataSource: {}}`
3. See error

### Important Details
Release 1.4.7

Fix:
We should use the same mechanism as the tableData control by trying to parse the string without bindings.

**Comment by techbhavin** [comment]
@riodeuno  @somangshu  

Here I notice common behavior with the table widget & chart behavior as well.

it was a parsing error for both widgets. 

when we type`{type: "", dataSource: {}}` it showing json parsing error.  or  `{"type": "", "dataSource": {}}` is working fine. 

<img width="914" alt="Screenshot 2021-05-24 at 12 55 00 PM" src="https://user-images.githubusercontent.com/58818598/119344566-71d7c280-bcb5-11eb-8200-8c49bdfbacd2.png">

is there common behavior in a current code base? 
or not how we can fix it? it will be great if I can get some reference documents related to the same?

**Comment by somangshu** [comment]
@riodeuno this seems to be working now. The chart data under the `custom chart` works without the mustache binding as well.

**Comment by riodeuno** [comment]
@somangshu Awesome! @vivekverma2312 Please verify this and close this issue if it looks good to you.

**Comment by somangshu** [comment]
@techbhavin @vihar documentation update  is required if this is resolved!

**Comment by vivekverma2312** [comment]
@techbhavin I see the same observation which was reported on the issue. If we use `{{ {type: “BAR_CHART”, dataSource: {}} }} `it is not throwing error but if we use `{type: “BAR_CHART”, dataSource: {}}` the error is coming. 
In case of error the syntax is matching the syntax mentioned in error message.

<img width="812" alt="Screenshot 2021-05-27 at 11 30 43 AM" src="https://user-images.githubusercontent.com/83569920/119776433-8e0c7700-bee2-11eb-8146-cdb49bca5ed0.png">
<img width="849" alt="Screenshot 2021-05-27 at 11 30 13 AM" src="https://user-images.githubusercontent.com/83569920/119776446-919ffe00-bee2-11eb-9f6f-787bbf5dd88b.png">

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @vivekverma2312 The validation for the type field is very poor. Can we tell users the accepted types and link to the doc?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal we will take the helper update in #4696 once the documentation is updated properly. @vihar is looking into that.

From a UX point of view do you think we should separate the `type` and `datasource` property. It makes it simpler to perceive as well. Otherwise the user needs to create the full object based on our schema and then add it here. 

@riodeuno @jsartisan any technical challenges in doing that?

**Comment by Nikhil-Nandagopal** [comment]
To clarify I am ok with the field being the same just that our errors should be more informative around what is wrong instead of simply does not evaluate to type, datasource.
Can we link to the docs from this error?

**Comment by techbhavin** [comment]
> @techbhavin I see the same observation which was reported on the issue. If we use `{{ {type: “BAR_CHART”, dataSource: {}} }} `it is not throwing error but if we use `{type: “BAR_CHART”, dataSource: {}}` the error is coming.
> In case of error the syntax is matching the syntax mentioned in error message.
> 
> <img alt="Screenshot 2021-05-27 at 11 30 43 AM" width="812" src="https://user-images.githubusercontent.com/83569920/119776433-8e0c7700-bee2-11eb-8146-cdb49bca5ed0.png">
> 
> <img alt="Screenshot 2021-05-27 at 11 30 13 AM" width="849" src="https://user-images.githubusercontent.com/83569920/119776446-919ffe00-bee2-11eb-9f6f-787bbf5dd88b.png">

Hi @vivekverma2312 
 I notice as you attached in the screenshot. are you using it without **double quote** in  **object key**. 
 
 can you please re-test it again using the same as [mention in comment](https://github.com/appsmithorg/appsmith/issues/3894#issuecomment-847000265) .
 
 example. `{"type": "", "dataSource": {}}`

**Comment by somangshu** [comment]
@vivekverma2312 @techbhavin in case this works, we need to update the error message to properly show what is required! Also as mentioned earlier the debug link should connect to the chart custom config documentation!

**Comment by vivekverma2312** [comment]
@techbhavin Checked with `{"type": "BAR_CHART", "dataSource": {}}` and it's working fine.

<img width="808" alt="Screenshot 2021-05-31 at 6 28 02 PM" src="https://user-images.githubusercontent.com/83569920/120196875-fab6a700-c23d-11eb-9893-9323c9fd9717.png">
