### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by mosinuga** [appsmithorg/appsmith#3904]
## Summary

Disable sign up

## Motivation

We have a requirement for security purposes to disable signup

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by nidhi-nair** [comment]
@mosinuga Disabling sign ups for an Appsmith instance is possible by setting an environment variablein your `docker.env` file. This is described in more detail, with a few other customization options, in our documentation [here](https://docs.appsmith.com/how-to-guides/restricting-signup#disable-sign-up). Is this what you were looking for?

**Comment by mosinuga** [comment]
Yes, thank you!
