### ISSUE TITLE
[Feature]-[700]: Add handling for JSON-LD types in REST APIs 

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3911]
## Description

API calls with JSON-LD content types are not handled and are simply parsed as strings.

### Steps to reproduce the behaviour:
1. Create a new GET request for this sample URL: `https://sources.wikibus.org/books`
2. Run this action, and notice that the response is a stringified JSON
3. Simply running this request on the browser shows a response header with a content-type of `application/ld+json`

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by nidhi-nair** [comment]
Also another example of an instance when metadata along with response body (response headers in this case) would be useful to help users debug their issues.

**Comment by jbertoen** [comment]
Not only application/ld+json also with application/vnd.api+json you experience this issue (JSON API).

**Comment by rohan-arthur** [comment]
REST 6m usage: 3500
assume 10% requirement: 350
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 350 |
| Effort (months)  | 0.25 |
