### ISSUE TITLE
Audio recorder widget

### ISSUE THREAD

**Issue by dusadvarshit** [appsmithorg/appsmith#3912]
Hello team,

Thank you for fantastic work with Appsmith.

I have been exploring the app and was wondering how one can add a voice recorder and an audio player to the app?
That would be a very helpful for the app feature we are trying to build in our team.

Thanks!

# RACI matrix
| Label | Value | 
| ------------- | ------------- |
| Responsible |  @jsartisan, @wmdev0808   |
| Accountable | @somangshu  |
| Consulted | @momcilo-appsmith  |
| Informed |  @Nikhil-Nandagopal |

# Objective

We need a voice recorder widget that allows users to record using there microphone, Listen to the playback and be able to export the data to a datasource.

# Success Metrics

| Goal  | Metric |
| ------------- | ------------- |
| New widget  | Increase use case coverage |
| Data type: Speech  | introduce a new data type; Ability to record voice etc. |

# Requirements

| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Allow Playback | recording and playing the feedback should be part of the experience, this will depend on the developer config | High | - |
| Recording states | state will allow the user to pause / play or stop the recording. Once the recording is stopped the audio should be available for the playback if the dev has enable the option. | High  | - |
| Allow download | The dev will have an option to allow users to download the recorded playback. | Low  | - |
| `.value`  | And internal property should expose an API to access the file | High  | - |
| isVisible |  Dev can set this attributes to show/hide with toggle or even a JS expression (JS convertible)  | High  | - |
| isDisabled | Dev can set this attributes to disable the widget with toggle or even a JS expression (JS convertible) | High | - |
| Action - `OnRecordingStopped` | API to trigger an action on recording stopped | High  | - |
| `.multipart` | File data should also be available as multipart | High  | - |
| Recording state message | All states should be well handled with Recording state message: ex - recording in progress | Medium | - |
| Style | The widget can have style customisation | low | if required |
| Tooltip | An helper text on the recording button for the end user. This will only show up when when you  are on the initial state of the widget | Medium | - | 

# Questions:

| Question   | Answer |
| ------------- | ------------- |
|  |  |

# Developer Handoff Document in Figma:

https://www.figma.com/file/WUnCZ4TcUSOYLpSSGWIsPx/Audio-Recorder-Widget?node-id=5%3A493

**Comment by dusadvarshit** [comment]
Alright, so I can play audio by putting the public url of my audio in the video player. 
Though still wondering how to use in-built recorder widget.

**Comment by hetunandu** [comment]
Hey, @dusadvarshit! Thanks for the widget request. We will add this to our backlog of new widgets

**Comment by somangshu** [comment]
note:

- The audio widget is configurable to record voice, From the property pane the user should be able to do so.
- User can also give paste url of the audio source or upload to the file to play.
- User can choose to auto play media on load.
- User can show hide the widget
- User has the following events
    - onPlay
    - onPause
    - onEnd
- If the record option is `true`
    - Available events:
        - onRecordingStart
        - onRecordingEnd

**Comment by Nikhil-Nandagopal** [comment]
@somangshu can you share the component we're considering using for this?
I think we should separate audio player and voice recorder. Both seem to be doing 2 different tasks. One is taking input, while the other is giving output.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal here the audio player is only used to provide the feedback of recording, Its very normal to listen to something you have recorded before we are actual saving. To me it sounds like a unified and complete experience. 

[Ref1](https://www.npmjs.com/package/audio-react-recorder)
[Ref2](https://www.npmjs.com/package/react-voice-recorder)

**Comment by Nikhil-Nandagopal** [comment]
@somangshu that makes perfect sense. I got confused because I thought there was also a URL that the user could use for a playback.
The libs don't seem very popular. Maybe we should make something custom with this audio player?
https://github.com/justinmc/react-audio-player#readme
