### ISSUE TITLE
[Bug]Changing the Zoom level of image 1 from page 1 is getting applied to all the images in the List Widget

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3925]
## Description
Changing the Zoom Level of any particular image the same level is getting applied to other images in the list widgets

**Expected Result:**
Changing the Zoom level for a particular image the zoom level should be applied only to the particular image

**Actual Result:**
Changing the Zoom level for a particular image the zoom level is applied to all other images within the List Widget

### Steps to reproduce the behaviour:
1. Launch Appsmith app in the Deploy Environment 
2. Drag and Drop List Widget 
3. Click Edit on the Image 1 from page 1
4. Change the Zoom level from the Image Property pane
5. Navigate to Page 2, 3 , 4 and observe the image

Video Link:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bf43c0cdc4044d6795e9138d58a4d041-00001.gif)](https://www.loom.com/share/bf43c0cdc4044d6795e9138d58a4d041)

### Important Details
 - Version: [ 14.0.3 (16610.4.3.1.7)]
 - OS: [macOS Big Sur 11.2.3]
 - Browser [safari]

**Comment by ashit-rath** [comment]
@dilippitchika Can we close this issue,  the behaviour seems to be correct here
