### ISSUE TITLE
[Bug] Clicking on Documentation link user is lead to an inappropriate page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3944]
Steps to reproduce:
1) Add an datasource
2) Click on "Add API"
3) Click on "Documentation link"
and observe

Observation:
It is observed that the user is lead to inappropriate page 

Expectation:
User must be lead to respective document page

![Screenshot 2021-04-09 at 12 37 29 PM](https://user-images.githubusercontent.com/71753653/114143338-aaa02000-9931-11eb-990b-951263da4438.png)

**Comment by areyabhishek** [comment]
The screenshot seems to be wrong. Could you share the incorrect link as well?

**Comment by prapullac** [comment]
@areyabhishek : The above mentioned screenshot is the exact page where user is navigated to on Google sheet datasource which we are testing on test environment.

**Comment by nidhi-nair** [comment]
This is a TODO, need to format [this](https://www.notion.so/appsmith/Docs-1fed57c682734187a601aa540a602a76) draft and add it to docs. @vihar could you please check to see if this is understandable?

**Comment by nidhi-nair** [comment]
@vihar, is it fair to upload the docs as they are right now and improve upon them as we fin pain points for users?

**Comment by areyabhishek** [comment]
@vihar  is out of action. I went through the Notion doc and made a few changes. Looks good to go for me.

**Comment by nidhi-nair** [comment]
Fixed via documentation update
