### ISSUE TITLE
[Feature] Widget pane issues

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#3949]

**Comment by riodeuno** [comment]
- [ ] It is easier for users to grok text. Unfamiliar icons are not so easy to understand.

**Comment by somangshu** [comment]
[ ] User should be able to pin his fav widgets to the top
[ ] Maybe its better if the user can see the widgets divided into folders logically

**Comment by somangshu** [comment]
@momcilo-appsmith seems like we have covered most of this, Can you please take a look and close it
