### ISSUE TITLE
Editor.json : Add functionality to read data into the form from datasource configuration or datasource structure

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#3951]

**Comment by somangshu** [comment]
Is this a duplicate? https://github.com/appsmithorg/appsmith/issues/2504

**Comment by trishaanand** [comment]
@somangshu : No. #2504 is a feature request for generation of queries. This is simply an enhancement of editor.json which is used to display the query pane. As part of this change, we should be able to provide dynamic data to the generated fields via editor.json for better usability of query pane. One use case is that when creating a query for mongo, you should be able to select the collection name from a dropdown instead of writing the name as raw text. This would reduce the developer user errors in writing the collection name

**Comment by nidhi-nair** [comment]
@trishaanand is this the same as dynamic triggers?

**Comment by trishaanand** [comment]
> @trishaanand is this the same as dynamic triggers?

Yes it is. We can close this once trigger functionality is in release.

**Comment by nidhi-nair** [comment]
@ayushpahwa Please attach the dynamic trigger PR to this issue.
