### ISSUE TITLE
[Bug] Yarn start error

### ISSUE THREAD

**Issue by multorteam9** [appsmithorg/appsmith#3955]
## Description
After `yarn start` i got this error 
```
Failed to compile.

/home/student1/Desktop/appsmith-release/app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
TypeScript error in /home/student1/Desktop/appsmith-release/app/client/src/components/designSystems/blueprint/DropdownComponent.tsx(297,17):
No overload matches this call.
  Overload 1 of 2, '(props: Pick<Pick<IMultiSelectProps<DropdownOption> & RefAttributes<MultiSelect<DropdownOption>> & { ...; }, "ref" | ... 31 more ... | "hideCloseButtonIndex"> & Partial<...>, "ref" | ... 31 more ... | "hideCloseButtonIndex"> & { ...; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type '(_tag: string, index: number) => void' is not assignable to type '(value: ReactNode, index: number) => void'.
      Types of parameters '_tag' and 'value' are incompatible.
        Type 'ReactNode' is not assignable to type 'string'.
          Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<new (props: IMultiSelectProps<DropdownOption>) => MultiSelect<DropdownOption>, Theme, { hideCloseButtonIndex: number; height: number; width: number; }, never>): ReactElement<...>', gave the following error.
    Type '(_tag: string, index: number) => void' is not assignable to type '(value: ReactNode, index: number) => void'.  TS2769

    295 |               height={this.props.height}
    296 |               tagInputProps={{
  > 297 |                 onRemove: this.onItemRemoved,
        |                 ^
    298 |                 tagProps: (value, index) => ({
    299 |                   minimal: true,
    300 |                   interactive:



```

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to 'cd app/client'
2. Click on  Terminal    'yarn start'  
3. See error

### Important Details
 - Version: [Self-Hosted appsmith-release]
 - OS: [centos]
 - Browser [chrome]

**Comment by areyabhishek** [comment]
@sharat87 can you see this error on centos?

**Comment by multorteam9** [comment]
Yes

**Comment by hetunandu** [comment]
@multorteam9 Looks like there is some issue with your node environment. Could you delete your `node_modules` directory, and install again via `yarn` and then run `yarn start`

**Comment by multorteam9** [comment]
I did but problem still remains.

Please NOTE: Master branch works properly only release branch have this problem. Seems it related to type script or programmatic.

**Comment by hetunandu** [comment]
@multorteam9 that is because release and master would have different dependencies. 
Can you also try to install after clearing cache?
```
yarn cache clean
```

**Comment by multorteam9** [comment]
I did but not fixed.

**Comment by riodeuno** [comment]
Hi @multorteam9 !
Can you provide us with the following details:
- The version of `node` which is used by `yarn`
- Has the `yarn.lock` file has deviated from the original `yarn.lock` file in `release` branch?

**Comment by Nikhil-Nandagopal** [comment]
@multorteam9, I'm closing this as there's no traction on this issue. Feel free to re-open this
