### ISSUE TITLE
[Bug] Safari : The canvas is not completely displayed to user 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3963]
Steps to reproduce:
1) Add the application
and observe the canvas
2) Changing the canvas the size of the canvas does not get effected 
3) Click on the widget '+'
and observe the it fluctuates twice before being stagnant

Expectation:
The entire canvas must be displayed to user and widget pane must open with fluctuating

**Comment by riodeuno** [comment]
@prapullac This does not seem to be an issue anymore. Please confirm.

**Comment by prapullac** [comment]
@riodeuno: This does not exist anymore we can close the issue
