### ISSUE TITLE
[Bug]The icons Search, Filter, Download and Row Height are truncated with the table scroll bar

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3966]
## Description
Its is observed that in the table widget the icons Search, Filter, Download and Row Height are truncated with the scroll bar 

**Expected Result:**
Icons should be clearly visible and should not trunacte 

**Actual Result:**
Search , Filter, Download and Row Height icons are truncated

### Steps to reproduce the behaviour:
1. Launch Appsmith app in the Release Environment  
2. Drag and Drop table widget 
3. Observe the Icons Search, Filter, Download and Row Height

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [macOS Big Sur 11.2.3]
 - Browser [
<img width="528" alt="Table Widget - Icons Truncate" src="https://user-images.githubusercontent.com/35128442/114362461-fdc5dd00-9b94-11eb-8fd5-88a036670f58.png">
safari]

**Comment by vicky-primathon** [comment]
Fixed in PR https://github.com/appsmithorg/appsmith/pull/4006
