### ISSUE TITLE
[Bug] When the image is added to the table it does not follow alignment

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#3967]
Steps to reproduce:
1) Add a table
2) Bind to API with image
3) Click on Property Pane of the table
4) Add an alignment 
5) Click on the image control pane 
6) Add datatype as image 
and observe

Observation:
The table alignment is applicable to all the columns except for the image 

Expectation:
When the table alignment is added it must be add to all the data type 

![Screenshot 2021-04-12 at 1 50 17 PM](https://user-images.githubusercontent.com/71753653/114364873-7cbc1500-9b97-11eb-930b-96b932c07cc4.png)

**Comment by somangshu** [comment]
Similar behavior observed for type `URL`
