### ISSUE TITLE
[Bug]Unable to select text inside the search field using mouse drag selection 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#3969]
## Description
It is observed that in table widget the text inside search field is not selectable 

Expected Result:
User should be able to select text inside the search field using mouse selection 

Actual Result:
User is not able to select text from search field using mouse selection

[What happened]

### Steps to reproduce the behaviour:
1. Launch Appsmith app in the Release Environment
2. Drag and Drop Table widget 
3. Click on search button and Type some text (Eg.Peter)
4. Try to select the text using mouse option and observe

**VideoLink:**
https://www.loom.com/share/eb379fd6bc18476bb39f3f5a9a599409

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [macOS Big Sur 11.2.3]
 - Browser [safari]

**Comment by somangshu** [comment]
This bug is not reproducible in the view mode. Only in the edit mode the mouse drag function doesn't function.
