### ISSUE TITLE
[Bug] curl 7.29.0 --data-raw is unknown

### ISSUE THREAD

**Issue by zimkjh** [appsmithorg/appsmith#3972]
## Description

I'v tried to setup "self-host appsmith" using installation scripts, using [this guide](https://docs.appsmith.com/setup/docker)
I've found --data-raw option is not suitable for my situation.
So, I replaced --data-raw -> --data, and it successfully worked!!
![image](https://user-images.githubusercontent.com/31986639/114408618-8f107000-9be4-11eb-9b7f-93bed006479a.png)

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. `curl -O https://raw.githubusercontent.com/appsmithorg/appsmith/master/deploy/install.sh`
2. `chmod +x install.sh`
3. `./install.sh`
4. error : `curl: option --data-raw: is unknown`

### Important Details
 - Version: Self-Hosted / docker / 1.2.1
 - OS: CentOS Linux release 7.4.1708 (Core)
 - Curl : curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.28.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3

- About version
![image](https://user-images.githubusercontent.com/31986639/114409142-1827a700-9be5-11eb-832c-bef0c24bc9b1.png)
- About OS
![image](https://user-images.githubusercontent.com/31986639/114409296-44dbbe80-9be5-11eb-9663-0b8ab65b6797.png)
- About curl
![image](https://user-images.githubusercontent.com/31986639/114409419-689f0480-9be5-11eb-9fae-185609e2df9d.png)

**Comment by Nikhil-Nandagopal** [comment]
@zimkjh thank you so much for your contribution! 🥳
