### ISSUE TITLE
[Feature] Tweak install script to work with AWS AMIs

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#3980]
The AWS CentOS image responds to the following command

```
cat /etc/*-release | awk -F= '$1 == "NAME" { gsub(/"/, ""); print $2; exit }'
```

with the value `Amazon Linux`. This does not necessarily point directly to CentOS, we will need to check how the AMIs differ from one to the other.

**Comment by Nikhil-Nandagopal** [comment]
This is now solved
