### ISSUE TITLE
[Feature] Configurable cookie auth duration (session/max age)

### ISSUE THREAD

**Issue by zegerhoogeboom** [appsmithorg/appsmith#3981]
## Summary

Currently the built-in authentication sets a cookie `SESSION` with "session" expiry. While I'm happy with the built-in auth I'd like to configure the cookie to instead be valid for e.g. a year to stay logged in. If such a configuration option is added the default can of course remain session expiry such that it's not a breaking change.

## Motivation

I'm using "Digital signage" software ([Xibo](https://xibo.org.uk/)) by which I can push content to screens remotely. I'd also like to show Appsmith content but the issue is that every time the software re-opens the auth session is gone and it needs to be logged in again. These screens are mostly "passive" to look at as in there is no keyboard/mouse even attached to them to log in. If the auth cookie duration could be configurable this would solve my use case. 

## Additional Context

This is the cookie I'm referring to. 

![image](https://user-images.githubusercontent.com/5371096/114530953-bcdccf80-9c4b-11eb-8a16-5bd0e2fb5e41.png)

**Comment by Nikhil-Nandagopal** [comment]
@zegerhoogeboom would making the application public solve this for you? You can click share and make the application public so that the appsmith content can always be shown.

**Comment by zegerhoogeboom** [comment]
Oh wow that's perfect actually, thanks a lot!

**Comment by Nikhil-Nandagopal** [comment]
Always happy to help 😄
