### ISSUE TITLE
Sessions are not supported by the MongoDB cluster to which this client is connected - When connecting to a single Instance MongoDB [BUG]

### ISSUE THREAD

**Issue by SushritPasupuleti** [appsmithorg/appsmith#399]
## Description

When you try to connect to a single instance mongodb, i.e one without any replica sets. The connection process seems to run into problems. Was able to verify this with one of the guys on the chat! (Great support btw!)

### Steps to reproduce the behaviour:
1. Go to ` Data Sources > MongoDB `
2. Enter your credentials and other necessary info
3. Click on test
4. A popup on the top right corner would indicate "Sessions are not supported by the MongoDB cluster to which this client is connected"

### What you expected to happen
It should have connected as the documentation would suggest.

### Screenshots
![1](https://user-images.githubusercontent.com/14891901/90907009-0d1ecd00-e3f0-11ea-9cb4-a0c41be57ebe.png)

### Important Details

How are you running appsmith?
SaaS (appsmith.com)

Which browser / OS are you using?
Chrome on Windows 10 (All of the latest updates and patches)

**Comment by sharat87** [comment]
Hello @SushritPasupuleti, thank you for taking the time to report with such detail. Appreciate it.

We were able to quickly zero-in on this problem and it is now fixed and in production. Can you try this now and confirm please?

I'm closing this issue now, but if you notice that the problem persists, please get back to us and we'll re-open.

Thanks again!

**Comment by SushritPasupuleti** [comment]
Yes! Can confirm that it's working perfectly! Cheers!
