### ISSUE TITLE
[Bug] Evaluated Value is displayed as undefined by passing valid Request Query

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4008]
## Test Environment - Its is observed that by passing valid Request Query the evaluated value shows undefined

**Expected Result:**
Evaluated value should show the actual value which is passed in the request query 

**Actual Result:**
Evaluated value is displayed as undefined by passing valid request query 

### Steps to reproduce the behaviour:
1. Launch Appsmith app in the Test Environment 
2. Expand Api and Click on Googlesheet 
3. Click on Add new Datasource and Configure Email 
4. Click on Add new Api 
5. Choose option as 'Create new Spreadsheet'
6. Enter the sheet name 
7. Pass the following Request - [ { "row_id": "1", "Name": "AppSmith", "Email": "Appmsith@gmail.com" } ]
8. Click inside the Row Objects and check the Evaluated Value

**VideoLink:**
https://www.loom.com/share/7eef1378fc6e4cd9b14882b34fa3bc18

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [e.g.MacOS Big Sur 11.2.3]
 - Browser [Safari]

**Comment by nidhi-nair** [comment]
@ApekshaBhosale This happens only for the QUERY_DYNAMIC_TEXT widget, on test.appsmith.com 

Could you help triage this?
