### ISSUE TITLE
[Feature] Allow moving applications between organizations

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4009]
It is possible that users use certain organizations only for developing an application, and do not want to give users access to this organization. If we allow moving apps between organizations, it creates an extra layer of abstraction for users.

**Comment by benlagrange** [comment]
Thank you @nidhi-nair. My use case is: Our organisation requires different levels of user access for our different Appsmith apps. I want to create a "godmode" organisation, with higher-tier apps that can have financial/operational impact as well as a "Customer Service" organisation with safer apps that our least technical employees can use without danger. Users will be invited to organisations based on their level within the company.

At the moment, all my apps live in one organisation, and to achieve User Access Control through different organisations, I'll have to copy-paste them widget by widget into a new organisation. If implemented, I will definitely use it like described in your use case as well.

**Comment by codedmind** [comment]
I suggest merge this request as the export/import function... that way we can move apps between instances or event between different orgs inside the same instances.

**Comment by Nikhil-Nandagopal** [comment]
Related to #3089 
Closing this as we're picking it up in 3089 :)
