### ISSUE TITLE
[Bug] Undefined response is received while inserting single sheet row, inserting bulk sheet row and update sheet row by passing valid request query

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4011]
## Description
Test Environment - Its is observed that by passing valid request query for inserting single sheet row, inserting bulk sheet row and update sheet row, undefined error is received 

**Expected Result:**
Inserting single sheet row, Inserting bulk sheet row and updating row sheet with valid request query should update the google sheet

**Actual Result:**
Inserting single sheet, Inserting Bulk sheet and updating sheet row with valid request input 'undefined' error is displayed

### Steps to reproduce the behaviour:
1. Launch Appmsith app in the Test Environment
2. Expand API and click on Google sheet 
3. Click on Add new Datasource and configure with email 
4. Click on new api 
5. Copy the existing spreadsheet url 
6. Choose the option as 'Insert sheet row'
7. Enter the existing sheet name 
8. Pass the following row objects -  { "row_id": "3", "Name": "AppSmith", "Email": "Appmsith@gmail.com" }
9. click on run and observe 

Similarly, use the following row objects for Bulk insert sheet row - [ { "row_id": "4", "Name": "AppSmith4", "Email": "Appmsith4@gmail.com" } , { "row_id": "5", "Name": "AppSmith5", "Email": "Appmsith5@gmail.com" } ] and for update row sheet { "row_id": "3", "Name": "AppSmith", "Email": "Appmsith@gmail.com" } and observe

**VideoLink:**
https://www.loom.com/share/90ad6802e50940268a9af0a7cd5c8d86

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [MacOS Big sur 11.2.3]
 - Browser [Safari]

**Comment by nidhi-nair** [comment]
This was happening under the following scenarios:
- No data in sheet
- Only table heading in sheet

Similar bug that has also been solved:
- Complete mismatch between columns headings and provided data behaved inconsistently. This has been handled now by always ignoring columns that do not match the existing structure. If no structure exists, the incoming data is assumed to be the intended structure.
