### ISSUE TITLE
[Bug][MultiSelect Dropdown Widget] The widget doesn't get reset on clicking the reset button

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#4012]
## Description
The widget doesn't get reset on clicking the reset button within the form widget

### Steps to reproduce the behaviour:
1. Add a form widget
2. Add a couple of dropdowns, configure one as multi select
3. Select values for both the dropdowns
4. Click on the reset button
5.  The multiselect dropdown doesn't get reset to its original state

#### Additional Context

https://user-images.githubusercontent.com/1944800/114858145-b9417800-9e06-11eb-973c-518f95993fa7.mov

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #3339
