### ISSUE TITLE
[Bug] Widget pane animation flickering on safari

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4019]
## Description

The widget pane while opening flicker in the safari browser

### Steps to reproduce the behavior:
1. Go to 'edit app mode'
2. Click on '+ icon next to widgets'
3. Check how the widget pane flickers

### Important Details
 - Version: [Cloud]
 - OS: [MacOSX Big Sur]
 - Browser [safari 14.03]

https://user-images.githubusercontent.com/11089579/114893365-3e3e8880-9e2b-11eb-931f-38b897e8adb9.mov

**Comment by somangshu** [comment]
also reported in #3963

**Comment by somangshu** [comment]
@vivekverma2312 please check to see if this is still valid. Otherwise close this

**Comment by vivekverma2312** [comment]
@somangshu Not able to repro so closing the issue.
