### ISSUE TITLE
[Bug] Vertical Scroller is visible to user when the alignment and Row height is changed 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4022]
Steps to reproduce:
1) Add a table 
2) Bind the API 
3) Add the alignment and Row height 
4) Reduce the table size
5) Now change the alignment and Row height 
and observe

Observation:
Observation 1:
It is observed that the vertical scroller is visible to user on scrolling 

Expectation:
It is expected that the vertical scroller must not be displayed to user 

Environment:
https://deploy-preview-4006--appsmith-editor-ce.netlify.app

![Screenshot 2021-04-15 at 5 46 21 PM](https://user-images.githubusercontent.com/71753653/114906694-eeb28980-9e37-11eb-934d-d6afcc507308.png)

**Comment by riodeuno** [comment]
@prapullac In this scenario, the amount of space available to show the first row is not enough, hence there is a vertical scrollbar.

**Comment by prapullac** [comment]
@riodeuno Since we read the row height of the we can restrict the user to resize until that. This will improve the experience of the user

**Comment by riodeuno** [comment]
@prapullac Yes, we're looking into restrictions on the widget dimensions. A set of minColumns and minRows, however, there are no such restrictions at the moment.

**Comment by somangshu** [comment]
@areyabhishek we need some inputs from design here. The table has a vertical scrollbar when the row height is set to `tall` and the no of table rows in the body is an odd number. as pointed by @riodeuno, we will need restrictions on the widget dimensions.

**Comment by areyabhishek** [comment]
Can the scroll bar be removed unless someone is actually scrolling? It's the empty state scrollbar that looks ugly.

**Comment by vicky-primathon** [comment]
New table design we do not have the table row size option, this extra scrollbar won't be present if we remove row size option.

**Comment by areyabhishek** [comment]
@vicky-primathon my point is not to show a scroll bar unless the user is actually scrolling. I don't see scroll bars on long webpages unless I'm scrolling. Why show a scrollbar to the user when they are not scrolling?

We need row height options. If it's not in new designs, then it's a mistake.

**Comment by somangshu** [comment]
@momcilo-appsmith kindly check this. We have to update the table designs.

**Comment by areyabhishek** [comment]
@somangshu @momcilo-appsmith My bad here. We'll have row height controls, but it'll be inside the property pane and not in the table header. This option is useful for developers and not for end users.

**Comment by riodeuno** [comment]
We now show the scrollbars only when we begin scroll. Closing this for now.
