### ISSUE TITLE
[Feature] Need a tooltip option for input widgets

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4024]
1. Input widgets will get used in forms
2. It'll be helpful for an input widget to have a tooltip so that the end-user can read information about the input field.

This can be a tooltip which is turned on or off from the property pane.

## Developer Handoff Link
https://www.figma.com/file/O1tKizBK5SHhWPcPT4RWIs/Input-Updates-Label-and-Tooltip?node-id=2%3A1

**Comment by somangshu** [comment]
[Helper text](https://material-ui.com/components/text-fields/#form-props) from material UI is also a modern style that can be considered while designing, I like this more because the information is proactively visible to the user.

**Comment by areyabhishek** [comment]
Makes sense. This design is better

**Comment by areyabhishek** [comment]
@somangshu @momcilo-appsmith I think there's a lot more we can do with the simple input widget. [Here's the link to the BlueprintJS input component details.](https://blueprintjs.com/docs/#core/components/file-input) We can enable every single Blueprint JS property.

1. How about using the helper text style of the material UI style instead of tooltip? Blueprintjs already allows that.
<img width="245" alt="Screen Shot 2021-05-21 at 1 32 18 AM" src="https://user-images.githubusercontent.com/30255708/119041631-790c8100-b9d4-11eb-9c21-08772f461394.png">
2. How about introducing a few different styles of input fields?
<img width="675" alt="Screen Shot 2021-05-21 at 1 32 33 AM" src="https://user-images.githubusercontent.com/30255708/119041635-7a3dae00-b9d4-11eb-88f6-e008c4f8cc79.png">
3. How would the hover, active, and disabled states look like? (these same states should also be used for datepicker+select widget) 
4. For more ideas on improving the input widget [see design files for the previous input widget.](https://www.figma.com/file/moGQyQffFfyUhHUMO9xqn3/Appsmith-v1.0-Final?node-id=1821%3A5093) We hadn't implemented everything in thie old file, but perhaps now is the time to finally do this.
5. Property pane for the previous designs. [Figma file](https://www.figma.com/file/moGQyQffFfyUhHUMO9xqn3/Appsmith-v1.0-Final?node-id=2981%3A5521)

**Comment by somangshu** [comment]
@areyabhishek @momcilo-appsmith 

1. The placeholder inside the input on focus becomes a label in material UI. This solves the technical constraints of the grid size too. However, the helper text under the input still adds to the height which is dynamic (as the user/conditions can choose to show or hide it). How should this problem be solved?
2. The material UI components are visually different compared to the blueprint's design system. Can we accommodate this together. or should we decide on following a certain design guideline as otherwise, it might lead to UI inconsistency.

**Comment by areyabhishek** [comment]
Showing helper text below the input widget is useful because they are mobile UI friendly. We can also use the space to show error messages (if defined by the developer).

We could solve it by resizing the input field? Or we could resize the boundaries of entire widget automatically. We've never tried resizing boundaries automatically. @riodeuno might know if it's possible.

**Comment by somangshu** [comment]
Closing this in favor of #5525
