### ISSUE TITLE
[Bug] Enhancement :Sorting the Google API method in the dropdown 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4029]
Steps to reproduce:
1) Add a Google API datasource
2) Select a scope 
3) Save the datasource
4) Click on "Create API"
5) Click on method dropdown 
and observe

Observation:
It is observed that the google API method are randomly displayed and user needs to search it over

Expectation:
Arranging them alphabetically or according the process would help the user in navigation 

Environment:
test.appsmith.com

**Comment by nidhi-nair** [comment]
Hey @prapullac, we had actually arranged this list in the order we thought would be most relevant to users when using the plugin as a CRUD datasource. Do you have any suggestions of what a more intuitive ordering would be?
