### ISSUE TITLE
[Bug] Table widget pagination number is not aligned in the centre of input

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4035]
Step to reproduce:
1) Add the table 
2) resize the table 
and observe the Pagination

Observation:
The pagination number is not placed appropriately inside the box

Expectation:
The page number must be placed inside the box 

Environment:
https://deploy-preview-4006--appsmith-editor-ce.netlify.app/

<img width="807" alt="Screenshot 2021-04-18 at 8 04 32 PM" src="https://user-images.githubusercontent.com/11089579/115149373-632c3900-a081-11eb-8de0-8f38b3e95c3e.png">

**Comment by vicky-primathon** [comment]
Fixed in PR https://github.com/appsmithorg/appsmith/pull/4006
