### ISSUE TITLE
[Bug] Table continues to apply client side searching even when onSearchChange is configured

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#4039]
### Steps to reproduce the behaviour:
1. Drag a table
2. Create a query and add a where clause to use similarity in PGSQL
3. Display the query in the table
4. Search for a query string like Jean Luc
5. The query returns similar results like Jean Claude but the table filters these out on the client side

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal What's the exact solution here? Could you describe it? We can ask @vicky-primathon to take a look at this.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek @riodeuno @vicky-primathon 
The solution I was thinking of was to disable the client-side search if the user has configured a query onSearchTextChange.

**Comment by areyabhishek** [comment]
And re-enable client side search if onSearchTextChange is reset. Sounds simple enough.
