### ISSUE TITLE
[Bug] Watermark on the API response body is misleading 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4043]
Steps to reproduce :
1) Navigate to API pane 
2) Select an Google API
3) Select the method of Create update etc 
and observe the response body 

Observation:
It is observed that the Response body watermark has an misleading syntax which might confuse the user 

Expectation:
Add an appropriate watermark to response body that would help user to understand the syntax .

Environment:
test.app.appsmith.com

![Screenshot 2021-04-19 at 10 18 21 AM](https://user-images.githubusercontent.com/71753653/115184753-1c2f5980-a0fc-11eb-9830-e1e28afa3fc1.png)

**Comment by nidhi-nair** [comment]
Hey @prapullac! Could you specify what you found misleading about this hint? The idea was to convey that the request takes in a JSON object.
