### ISSUE TITLE
[Bug]API - Create new Spreadhseets Query response pane is displayed when other methods are selected 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4044]
## Description
Test Environment - API Google Sheet - It is observed that when the user creates a new speadsheet and received query response pane. The query response pane is still displayed when the user chooses any other methods like (Delete Row, Fetch Sheets, list sheets)

**Expected Result:**
The query response pane of one method should not be displayed for another methods

**Actual Result:**
The query response pane of create spreadsheet is displayed for other methods

### Steps to reproduce the behaviour:
1. Launch Appsmith app in the Test Environment 
2. Expand API and Click on Google sheet
3. Click on Add new Datasource and sync Email 
4. Click on New API
5. Choose method and Create New Spreadsheet and pass valid date and run and check the response query 
6.  Choose the different method apart from create new spreadsheet and observe

**Video Link:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9fbc21639edd49209177d62dadbf3076-00001.gif)](https://www.loom.com/share/9fbc21639edd49209177d62dadbf3076)

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [macOS Big Sur 11.2.3]
 - Browser [Safari]

**Comment by nidhi-nair** [comment]
@ApekshaBhosale is this possible to fix?

**Comment by ajinkyakulkarni** [comment]
@mohanarpit @ayushpahwa Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4044?planning-poker)

**Comment by mohanarpit** [comment]
IMO, this is not a bug. All our actions behave in the same manner. Changing fields/parameters in the request doesn't change the response until the action is executed again.

If we clear the response on the basis of request parameters, for consistency we'll have to do it not just for other actions but also for other request fields as well. This will lead to a lot of confusion for users.
