### ISSUE TITLE
[Bug]Deleting a row with index of 0 deletes the table header instead of the data value of index 0

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4049]
## Description
Test Environment - Api Google sheet - it is observed that when the user tires to delete the row of index 0 the table header is deleted instead of the actual data value

**Expected Result:**
Deleting index of 0 should delete the actual data value of index of 0 and should not delete the Header row

**Actual Result:**
Deleting a row of index 0 deletes the table header row

### Steps to reproduce the behaviour:
1.Launch Appsmith app in the Test Environment
2.Expand API and click on Google sheet
3.Click on Add new Datasource and sync Email
4.Get any of the existing google sheet url and note down the sheet name
5.Choose the method name as 'Delete Row'
6.Pass the spreadsheet url which is noted at step 4
7. pass the index as 0 
8. click on run and verify the success message 
9. open the google sheet and verify the row which is deleted

**Video link:**
https://www.loom.com/share/380c6472313149ea9f3f9a6828c0eccf

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [macOS Big Sur 11.2.3]
 - Browser [Safari]

**Comment by nidhi-nair** [comment]
Fixed in 90640f1
