### ISSUE TITLE
[Enhancement] user is unable to Update Header of the table using google API 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4050]
Steps to reproduce:
1) Navigate to Google API
2) Select Update method
3) Add Raw body to update the Header
and observe

Observation:
User can not update the header of google sheet 

Expectation:
it is expected to update the header of google sheet

**Comment by Nikhil-Nandagopal** [comment]
Closing this as it's not expected that column header should be updatable
