### ISSUE TITLE
[Bug] Inconsistence in the meta properties fallbacks in widgets

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#4058]
## Description
In the input widget, when the `defaultText` is updated, the bindings all update. However, when we clear out the text in the input widget, the bindings propagate as empty text.
This is not consistent in the date picker widget. The `defaultDate` is always a fallback when the date is cleared from the widget.

There are two solutions here:
- [ ] We should make this consistent by making sure that all meta properties behave like they do in the datepicker widget's `defaultDate`.  (fallback to default values if they exist)
- [x] Or fix this for the date picker widget.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Add an input widget and a datepicker widget. Add `defaultText` and `defaultDate` respectively in the property panes
2. Add two text widgets, each binding to the input widget's text and datepicker's `selectedDate` respectively.
3. Try changing the text widget by making it empty and clearing the date from the date picker widget.

### Important Details
- Release 1.4.9

**Comment by hawisizu** [comment]
In my opinion it's the 2nd option the correct one. 

The 1st one would be a nightmare: that would mean that if you remove the text from an input, you reset to the value it had before, this is non sense. If you do that it means you do want to clear the value, not reset it.

**Comment by somangshu** [comment]
Hey @hawisizu, Thanks for the input on this. What you are saying does make sense and is straightforward!

While our thought has been on the following lines:
If you use `default text / default date`, as the name suggests, it should be the fallback default when no value is present. When a user leaves the input blank, the value should fallback to the default.

Allow me to discuss this with the team. Ill will get back here soon.

**Comment by somangshu** [comment]
In the favor of consistency, we will be going ahead and make changes to the datepicker widget. On clearing the input value, it shouldn't fall back to the default value.

**Comment by somangshu** [comment]
Seems like `getDerivedPropertiesMap()` does not get called `onClick' of `clear` in `datepicker`. This introduces another bug, When the default date is selected for the first time and clear is pressed, the datepicker input does not clear.

**Comment by somangshu** [comment]
@riodeuno another user requesting this fix on Discord. Can we prioritize this to find an ETA?

**Comment by somangshu** [comment]
#5052 should be picked up in tandem

**Comment by vicky-primathon** [comment]
@riodeuno @somangshu  default text does not get cleared until we are clearing text from Default Text field in Input widget properties. This is consistent with DatePicker's Default Date behaviour. Please re verify and let me know what needs to be done.  

Steps:
1. Add some text in Default Text field on Input Widget.
2. Change Default Date field in Date Widget or leave it same.
3. Bind {{Input1.text}} and {{DatePicker1.selectedDate}} to separate Text Widgets.
3. Change text in Input Widget.
4. Select date in Date Picker.
5. Clear both Input Widget and Date Picker.
6. The values selected in both Input and Date Picker widgets are default values that we added in steps 1 and 2.

**Comment by somangshu** [comment]
@vicky-primathon This is the inconsistency the issue talks about; The `selectedDate` does not clear up, where as the `text` does. For consistency we decided that clear should just clear and not fallback to default. Thats more like reset. 

https://user-images.githubusercontent.com/11089579/125251070-8b3fd700-e314-11eb-9961-5e0699f519c7.mov

With this, A change made in #5382 should also be merged here.
