### ISSUE TITLE
[Enhancement] User should be able to create a new sheet inside a created spreadsheets doc

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4064]
Steps to reproduce:
1) Create a spreadsheet 
2) Try to create a new sheet inside the created doc 
and observe

Expectation:
It is observed that the user can only create a spreadsheet document but we have no method to create an  addition new sheet into the created document. 
User still has a need to create a new sheet into the document manually.

**Comment by nidhi-nair** [comment]
Closing as this is the same as #8287
