### ISSUE TITLE
[Bug] Creating action from lightning menu does not update the property pane

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#4068]
## Description
When we use the lightning menu to create an API or Query, it does not update the field where the lightning menu is triggered

### Steps to reproduce the behaviour:
1. Drop a table
2. Click on the lightning menu  on the table data and create an API
3. Navigate back to the table
4. The table data does not have any information

**Comment by ApekshaBhosale** [comment]
@hetunandu when user creates an API using lightning menu we take them to create API page but when they come back to table, how will they have context which was created using lightning?

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale you can fill the field with the {{API.data}} binding as soon the API is created from the lightning menu
