### ISSUE TITLE
[Feature] Move widgets on the canvas with the help of arrow keys

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4076]
## Summary

As a user, I want to be able to move the widgets in all directions on the canvas with the help of arrow keys.

## Motivation

This is a good UX that can help users to make the minor movement of widgets to get the overall look and feel of the final app.

## Additional Context

The behavior exists on draw.io

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #3264

**Comment by szalapski** [comment]
I'm guessing https://github.com/appsmithorg/appsmith/issues/3264 was mistakenly thought unnecessary in light of auto-layout, but auto-layout is now dead, so I have created a new one, https://github.com/appsmithorg/appsmith/issues/40863.
