### ISSUE TITLE
[Feature] Use default widget data and actions to showcase platform features

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4079]
## Summary

The default widget data which is used initially as soon as a widget is dropped on the canvas can be used to give a platform walkthrough to the user. 

Ex: In the table widget, The example data can be a set of steps to show how to use the table widget as follows:
- [x] Drag and drop the table widget on the canvas.
- [ ] Connect to a datasource - CTA: DB queries
- [ ] Connect to an API - CTA: APIs
- [ ] Map your data to the widget - CTA: Open property pane
- [ ] Additional Features - CTA: documentation to table widget

**any additional info that could be required

This way the user has the information available every time he uses the widget.

## Motivation

It is often seen, especially for the first-time user, are not clear with the steps involved to use a widget. The widget data is already available and should be used to make this experience better.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu really nice idea! We can pick this up.
