### ISSUE TITLE
[Feature] Ability to drag the filter pane in Table widget. 

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4088]
## Summary

As a user, I should be able to drag the filter pane on the table widget anywhere on the canvas, just like how I can do with the property pane. 

## Motivation

When the filter pane of the table widget is open it blocks and many actions and also the table data and rows, which can be a frustrating experience to the user. In order to resolve this, the filter pane can now be dragged across the canvas.

## Additional Context

[Check designs here](https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=2%3A3024), 

`user flows > Table Options Dropdowns > Filter option start`

**Comment by riodeuno** [comment]
Note:
- Change remove filter icon
- Change Apply mechanism
- Add apply button
- Make Filters pane draggable
- Add functionality to close filters pane when clicked outside the pane or filters are applied
- Remove footer
- Add header
- Style dropdowns

**Comment by YogeshJayaseelan** [comment]
@vibhandikyash @somangshu Tested the fixes and it working as expected
