### ISSUE TITLE
[Feature] Confirmation before delete widget action

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4097]
## Summary

As a user, I should receive a confirmation intent (confirm modal) before a delete widget action can complete. Only if the user clicks continue/ok/yes the widget gets deleted.

## Motivation

When a user is working on a complex UI there are chances they might delete the wrong widget. Undo widget can solve this, but a proactive intent is always better.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu I think this goes against our design philosophy. Reversible actions should not ask for confirmation but simply allow reversal.

**Comment by somangshu** [comment]
@nikhil I agree with the thought. However, can you help me understand if the reversal is a permanent option in our platform right now? i.e. can I reverse the action once the temporarily undo snack bar is gone?

**Comment by Nikhil-Nandagopal** [comment]
Right now no but my point is that it should be so #3916 should be the right solution to this problem :)

**Comment by somangshu** [comment]
Agreed, Closing in favour of the above comment.
