### ISSUE TITLE
[Bug] Intermittent : Page get broken on adding an widget from the API

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4100]
Steps to reproduce:
1) Add an Google API
2) Create an List API
3) Click on "ADD Widget"
and observe

Observation:
It is observed that the page gets broken when the Widget gets added

Expectation:
It is expected the widget must get added to the Canvas 

![Screenshot 2021-04-22 at 2 28 00 PM](https://user-images.githubusercontent.com/71753653/115687433-ca930300-a377-11eb-81b5-939c054bcea9.png)

**Comment by prapullac** [comment]
Changing the priority of the issue as this is intermittent.

**Comment by nidhi-nair** [comment]
@jsartisan Is this the same as #3756 ?

**Comment by riodeuno** [comment]
@marks0351  @vivekverma2312 Please verify this

**Comment by vivekverma2312** [comment]
@marks0351 This issue is still observed.
https://www.loom.com/share/8684730fee9648158eb61e08b50f417b
