### ISSUE TITLE
[Bug]Binding API with tabs the particular tab disappears

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4124]
## Description
Environment - https://deploy-preview-4014--appsmith-editor-ce.netlify.app/
It is observed that when binding an api with tab that particular tab disappears

**Expected Result:**
Tabs should not disappear when Binding API with tabs

**Actual Result:**
Binding API with tabs the tab disappears

### Steps to reproduce the behaviour:
1. Launch Appsmith app in the Deploy Environment - https://deploy-preview-4014--appsmith-editor-ce.netlify.app/
2. Click on API and click on create new API
3. Pass the following header - https://enmbt55ts7rbb96.m.pipedream.net/
4. Method should be Get and save the API
5. Expand Widget 
6. Drag and Drop Tabs widget 
7. Click on tab1 and from the property pane click on the setting icon of tab1
8. Click on binding symbol 
9. Choose the API which is created at step 4 and observe

**Video Link:**
https://www.loom.com/share/71db2b27ebb94f8f8ea89dee0e4e96d0

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [macOS Big Sur 11.2.3]
 - Browser [Safari]

**Comment by marks0351** [comment]
closing this issue @YogeshJayaseelan as discussed this is working as expected.
