### ISSUE TITLE
[Feature] A static table widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4138]
## Summary
The goal of this widget is to show a simple table which is only for display of data with no functions like row selection, actions, etc. This can be shown for key value pairs. This is a common use case where you can show information like: 
<img width="698" alt="Screen Shot 2021-04-25 at 5 33 10 AM" src="https://user-images.githubusercontent.com/30255708/115976054-baea0900-a587-11eb-9ab1-3762c130b5b3.png">
<img width="459" alt="Screen Shot 2021-04-25 at 5 33 56 AM" src="https://user-images.githubusercontent.com/30255708/115976057-d6551400-a587-11eb-9977-231d4bc58892.png">

1. A component that displays key value pair
2. This could be a very simple static table without row selection, any column borders, search, download, pagination, etc.
3. Allowing styling similar to the text widget styling options
This widget will work really well to create good looking static tables. The reason to do this as a different widget is to keep this widget super simple, quick load, and without too many properties.

**Comment by somangshu** [comment]
@momcilo-appsmith 

# Objective
As a user, I wish to be able to convert a json object to a static table which does not have any options like row selection, actions, pagination and only displays data. 

# Success Metrics
List of all metrics you are tracking and the desired goal.
| Goal  | Metric |
| ------------- | ------------- |
|  Simplify user experience  | The user is easily able to display simple json object as tables without any fuss   |

# Assumptions

- User does not wish to use the current table widget feature because it is too complex to setup or shows up with too many features like search, filter, pagination, download etc.
- User wishes to show json key/value pair as simple table, ex: a user profile. Some dish details.



# Developer Handoff Document in Figma
Link to the developer Handoff Document:

**Comment by areyabhishek** [comment]
Example of a static table. Here the height of every row is different. We should enable tables like this to work. This can't happen in our current table, nor in the key value pair widget of our competitor.

<img width="751" alt="Screen Shot 2021-05-07 at 3 29 13 AM" src="https://user-images.githubusercontent.com/30255708/117370743-7abe4b00-aee4-11eb-9078-32b795220e4a.png">

**Comment by areyabhishek** [comment]
We should make this in the list widget instead of the table widget. There'll be a lot more flexibility with column sizes and the like.

**Comment by somangshu** [comment]
@areyabhishek do you mean using `list widget` instead of `table widget` to show the JSON object? This will still remain to be a separate widget?

**Comment by areyabhishek** [comment]
Yes exactly. We generate something that looks like a table, but is actually the list widget. It'll be flexible

**Comment by somangshu** [comment]
@areyabhishek one more question, do we give an option to the user to choose table or list as a view?

**Comment by somangshu** [comment]
@riodeuno can you leave a product note here

**Comment by riodeuno** [comment]
As @areyabhishek mentioned, the goal is to help developers display data in a tabular format with emphasis on alignment of data.

### Preliminary feature notes.

An HTML table with a few styles can achieve this goal. https://css-tricks.com/complete-guide-table-element/
Let's call this `Static Table` or `Static Data Grid`

#### Characteristics of the table:
- There are no interactions in this table. This means there will be no action triggers in the table's property pane.
- The table can render HTML
- The table can render rows with varying heights. (Multi-line content is allowed and an important feature here)
- The table component by default takes up the height of the widget, when the table component's height goes beyond the table widget, it becomes scrollable. Scrollbars should not change the width or height of the table when they appear or disappear.
- Styling options
     - Cell contents can be styled as any text widget today.
     - Headers can be styled as any text widget today. (styles apply to all headers)
     - Headers can be hidden from the property pane
     - Column and row separator grid designs will be limited. The list of options TBD (@momcilo-appsmith)
     - Column and row separators can be hidden.
- Headers can be made to be sticky
- Table should be virtualised by default to render large datasets. This will need a library like [`react-window`](https://github.com/bvaughn/react-window) which already exists as a dependency in our codebase.
