### ISSUE TITLE
[Feature] Setting to truncate text in the text widgets

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4141]
## Summary
Today the text widget truncates long text by showing only the center lines and hides the rest of it. See screenshot.
<img width="594" alt="Screen Shot 2021-04-26 at 4 04 41 AM" src="https://user-images.githubusercontent.com/30255708/116011841-a6b81180-a644-11eb-8cdb-57fd4444a528.png">

Some solutions to improve this
1. To show the entire text without truncating it. This would overflow onto other widgets, but it would serve the purpose of displaying the entire text
2. Give the user the option of truncating the text in the property pane. I saw a good way inside Glide apps to do this.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/437277aeaec840b186f83468700a35e5-00001.gif)](https://www.loom.com/share/437277aeaec840b186f83468700a35e5)

## Figma Design Link

https://www.figma.com/file/5Gmo3788ASY2CJcHMJsU7u/Text-Style?node-id=2%3A262

**Comment by somangshu** [comment]
@riodeuno we have verified that this issue is not related to #1610.

**Comment by areyabhishek** [comment]
@somangshu @momcilo-appsmith We need to pick this up as an improvement for the text widget. The text widget isn't very usable when the text is bigger than the developer intended.

**Comment by ramsaptami** [comment]
Text widget adds a scroll on when there's insufficient spacing on Windows OS
![image](https://user-images.githubusercontent.com/79509062/132179731-2b3cde9f-cada-4d20-b08e-ca4d54e7b4b7.png)

**Comment by momcilo-appsmith** [comment]
Added the Design link to the issue description.

**Comment by somangshu** [comment]
@vibhandikyash is the documentation related to this updated

cc @dilippitchika @Pranay105
