### ISSUE TITLE
Add retry limits for Mongo connection in the Mongo plugin

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#4142]

**Comment by sumitsum** [comment]
Tried this param with the mongo driver:  `serverSelectionTryOnce=true` , but it seems like this option is not supported :
` - Connection string contains unsupported option 'serverselectiontryonce'`
https://docs.mongodb.com/manual/reference/connection-string/#server-selection-and-discovery-options

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit is this still valid?

**Comment by yatinappsmith** [comment]
Verified as part of regression testing
