### ISSUE TITLE
[Bug]Image Widget inside the tab widget flickers in both edit and deploy mode upon binding an api with default tab 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4148]
## Description
It is observed that the image widget which is placed inside tab widget flickers in both edit and deploy mode when an api is binded to the default tab

**Expected Result:**
Image widget placed inside tab widget should not flicker 

**Actual Result:**
Image widget placed inside tab widget flickers upon binding an api to the default tab

### Steps to reproduce the behaviour:
1.Launch App Smith app in the deploy environment - 
2.Expand API and click on new api 
3.Choose the method as GET
4.Pass the following header url - https://enmbt55ts7rbb96.m.pipedream.net/
5. Click on Run button and name the API
6. Expand Widget and Drag and drop tab widget 
7. Drag and Drop image widget inside tab widget 
8. Click edit on the tab 
9. On the Property pane of Tab widget bind the existing API to the Default tab and observe

**VideoLink:**
https://www.loom.com/share/6eecc3cab2df42b4a2d824d4b78d3b0e

### Important Details
 - Version: [14.0.3 (16610.4.3.1.7)]
 - OS: [MacOS Big Sur 11.2.3]
 - Browser [safari]

**Comment by marks0351** [comment]
@YogeshJayaseelan this does not seem to be a valid use case since the default selected tab expects a string(that should also match one of the tabs) while you are binding an object.
