### ISSUE TITLE
[Feature] Style customisation in the button widget.

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4149]
## Summary

As a user, I should be able to change button style as follows:
 - The background colour can change with a hex code
 - font colour can change with hex code
 - elevation (box-shadow)
 - There should be button variant `contained (solid button)`, `outlined (only borders)`, `text (text buttons)`
 - Button can be multiple sizes: Large, Medium, Small
 - Button can have an `end icon` or `start icon`
 - ~~Button `end/start icon` can have a dropdown group as well. (button adornment)~~

These changes should also extend to the button widget used elsewhere, Ex: in the table widget.

## Motivation

I should be able to customize the button beyond primary/secondary/danger types.

## RACI matrix

| Attributes | Members | 
| ------------- | ------------- |
| Responsible |  @wmdev0808  |
| Accountable | @somangshu  |
| Consulted | @areyabhishek, @momcilo-appsmith  |
| Informed |  @Nikhil-Nandagopal |

**Comment by areyabhishek** [comment]
Also need a dropdown button. 
<img width="303" alt="Screen Shot 2021-05-07 at 4 40 46 AM" src="https://user-images.githubusercontent.com/30255708/117376268-697a3c00-aeee-11eb-8131-84f73fce064e.png">

**Comment by somangshu** [comment]
> Also need a dropdown button.

This will be resolved with #4889

**Comment by somangshu** [comment]
Buttons should also have icons configurable to provide an extra level of visual representations

**Comment by somangshu** [comment]
Note:
- Hex colour picker control for background and font colour 
![Screenshot 2021-07-07 at 4 36 58 PM](https://user-images.githubusercontent.com/11089579/124749211-91fbd200-df41-11eb-8eaf-3ad4efdb545a.png)

- Elevation will follow the following design and control. 
![Screenshot 2021-07-07 at 4 48 24 PM](https://user-images.githubusercontent.com/11089579/124750536-34688500-df43-11eb-83c0-54def24e7159.png)


- Button variant will use dropdown control with 3 values
    a.  contained (solid button), 
    b. outlined (only borders), 
    c. text (text buttons)

- Button size will be a dropdown control with 3 values
    a. Large, 
    b. Medium, 
    c. Small

- Button will have an icon control to choose an icon from 
![Screenshot 2021-07-07 at 4 44 52 PM](https://user-images.githubusercontent.com/11089579/124750093-ad1b1180-df42-11eb-9d51-3e5e6dc0b873.png)

- The icon can be aligned to the start or end of the button wrapper/container; this property will only be available when icon is set. 
![Screenshot 2021-07-07 at 4 46 32 PM](https://user-images.githubusercontent.com/11089579/124750305-ed7a8f80-df42-11eb-9df4-2be599b0e2b1.png)

- Icon color will be allowed to change with a hex colour picker

**Comment by somangshu** [comment]
@areyabhishek @Nikhil-Nandagopal We have a query here:
- When we are going to introduce the Background, Colour & Variant properties actually speaking the button style prop (primary, secondary, danger) is not required any more, Should it be removed?
- In case we are removing this, Me might have a challenge while taking this up in themification.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu yes we can kill it. I don't see what challenge it would pose, underneath the hood the style is just reading from the primary color.

**Comment by areyabhishek** [comment]
Can we kill this once we have theming built? Don't change this now.
Users are used to using primary, secondary styles today and will struggle to do the same thing if we expect them to now choose every color before using a button.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek Experience should remain fairly the same right?
Primary: Green 
Danger: Red
Secondary: No Color
By default, all buttons are green (primary today), if they want they can select another color.

**Comment by areyabhishek** [comment]
We change colours of background, border, and font for secondary button
style. Secondary style has a green border and font color along with no
background.

Let's spend a little time to find the solution here or wait for theming. I
don't want to annoy existing users.

**Comment by Nikhil-Nandagopal** [comment]
Ok I thought it was only a color change. In that case, can we treat this like we do column overrides in tables? Where the color overrides the style and updating the style resets the color.

**Comment by areyabhishek** [comment]
That sounds acceptable for now

**Comment by somangshu** [comment]
@areyabhishek @Nikhil-Nandagopal looking at the discussion ☝️  I suggest something as follows:

- we use more button styles: Primary, Secondary, Warning, Info etc
- we pair this with button variant
- This remain inline with themefication

We followed this approach in the icon button as well

![Screenshot 2021-07-15 at 1 28 13 PM](https://user-images.githubusercontent.com/11089579/125751644-a1b34f6b-214b-46a5-bda0-321e5bc24e58.png)

If this makes sense here is what we will do. 
- Button style remains as above
- Font color will automatically set as before based on the accent
- This is paired with button variant as shown above

**Comment by Nikhil-Nandagopal** [comment]
@somangshu I agree that we should have this but it doesn't solve the user request of "Can I change the button color". We've heard this way too many times so is it also possible to give a simple color picker that just overwrites the style?

**Comment by somangshu** [comment]
In that case we do ahead with the initial requirement, We give hex code for background and font colour with variants (solid, outlined and ghost/text)?

**Comment by areyabhishek** [comment]
So we'll have options like the icon button along with options to over ride
the colors?

Sounds good to me.

**Comment by somangshu** [comment]
@areyabhishek we have have either of them, 
- Choose from the preset (with more added options)
- Choose a HEX colour from background and font

**Comment by areyabhishek** [comment]
Can't it be both?
Where's the deploy preview for the icon button? I'll try it again.

**Comment by somangshu** [comment]
Sure, Check it out [here](https://deploy-preview-5723--appsmith-editor-ce.netlify.app/) (Icon button deploy preview)

**Comment by somangshu** [comment]
@Nikhil-Nandagopal another discussion happened. Here is what was proposed
- The button style has: Primary, Secondary, Info, Warning, Danger, Success, `Custom`
- If the `custom` option is selected we will show background, font, hover colour which can change. 
- The rest of the styling prop remains as it is

cc: @areyabhishek @momcilo-appsmith

**Comment by Nikhil-Nandagopal** [comment]
Great solution!

**Comment by somangshu** [comment]
@wmdev0808 found another solution which probably provides a better UX:

- The button style will have: Primary, Secondary, Info, Warning, Danger, `Custom`
- The `custom` option will expose the background colour property for the button, At this point we keep the last selected button style intact.
- When the user selects a new background colour we set the Font and Hover colour for them using the [tinycolor](https://www.npmjs.com/package/tinycolor2) library.
- For the font color we first use the [isDark](https://www.npmjs.com/package/tinycolor2#isdark) method from the above library, If the background is dark we use the light colour from our theme otherwise we use the dark colour.
- For the Hover colour we use the [darken](https://www.npmjs.com/package/tinycolor2#darken) method. We will darken the background colour by 40 (scale 0 - 100).

@Nikhil-Nandagopal @areyabhishek please let us know if you feel this is not the right way to go.

credit: @jsartisan
