### ISSUE TITLE
[Feature]-[1000]:Add unstable disclaimer banner on Appsmith platform for the safari browser

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4166]
## Summary

Since the app making experience in the `safari ` browser is not so smooth and there are a lot of unknown bugs as well, We should add a dismissible banner that clearly states this fact.

**Comment by zachary-thomas-115** [comment]
Hello all!
I am new to open source and would love to help with this!

**Comment by somangshu** [comment]
Thanks a lot for showing intrest @zachary-thomas-115, Please go ahead its all yours, I am assigning this to you. 

@momcilo-appsmith can we help out the contributor with the design change required?

**Comment by somangshu** [comment]
@zachary-thomas-115 here is the [design](https://www.figma.com/file/SBuzJ6e7IKtYRT30lnJYzy/Safari-Warning?node-id=1%3A1683)

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 800 |
| Effort (months)  | 0.5|

**Comment by tauantcamargo** [comment]
@somangshu zachary did it? if not, can i do it?

**Comment by mohanarpit** [comment]
@tauantcamargo It's all yours! 🎉 


Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.
