### ISSUE TITLE
[FEATURE] Integrate with Elasticsearch DB

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#419]
## Summary

We would like to integrate with elasticsearch DB.

## Motivation

Elasticsearch DB is a commonly used database for quick access of data. We would like to integrate with it to provide users a better experience with Appsmith

## Additional Context

For this issue, we will operate almost exclusively in the maven module `appsmith-plugins` . Each of these integrations is a plugin to the Appsmith platform. 

1. In the module `appsmith-plugins` , create a new module for the specific integration that you are developing. Copy the `pom.xml` from other modules to ensure that you have the basic structure in place.
2. Add the name of your new module to the parent `pom.xml` in `appsmith-plugins`. If you don't add this, your plugin will not be compiled.
3. When you write a plugin, you will also add test cases for this plugin. Please check the other plugins as a sample for how to do this. For databases, we will use [https://www.testcontainers.org/](https://www.testcontainers.org/) for bringing up containers to test against.
4. For all plugins, the interface that the plugin implementation needs to satisfy is: `PluginExecutor.java`
5. Each integration must support basic CRUD capabilities. Any additional features may be mentioned later through a separate issue/PR.

**Comment by ifelse-codes** [comment]
@mohanarpit I have started working on this feature

**Comment by pc9795** [comment]
Hi 👋 
In the "Additional Context" of the issue, point no 5, where can I find the "specific task page". I am interested in this issue.

**Comment by mohanarpit** [comment]
@pc9795 Welcome to the Appsmith community! 🎉 

Thanks for volunteering to pick up this issue. Normally, I'd ask you to pick something simpler but based on your comments on other issues, you seem fairly well-versed with Java & are able to navigate through a larger project 😄 

The integration with ES, unfortunately, requires some underlying changes to the Appsmith platform that we didn't know till this came up. Hence, I wouldn't recommend this specific integration if you're new to the code base.

Can I recommend [Redis Integration](https://github.com/appsmithorg/appsmith/issues/1016) instead? That's a much cleaner implementation and still follows the same instruction set.

**Comment by pc9795** [comment]
Sure. Let me have a look 👀
