### ISSUE TITLE
[Bug] Install script fails if user doesn't have write permissions to working directory

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4190]
Consider the following sequence of commands:

```sh
cd /restricted-folder
bash /home/myself/install.sh
```

Now, when the script asks for the installation directory, I provide `/home/myself/appsmith`. This will then fail with the error:

```
./install.sh: line 747: nginx_app.conf: Permission denied
```

This is because we are writing to current working directory, and so unintentionally assuming write access to the current directory.

**Comment by sharat87** [comment]
Testing steps:

1. Download `install.sh` script using the curl command from the documentation. Save it as `~/install.sh`.
2. Change to a folder where your user doesn't have write permissions. Like `cd /`.
3. Confirm you don't have write access by running `touch check`. If you don't see an error, you do have write access. Please change to a folder where you don't. If you do see an error, please proceed to the next script.
4. Run the install script with the command `bash ~/install.sh`.
5. Confirm the installation proceeds and finishes as expected.

**Comment by vivekverma2312** [comment]
@sharat87 I tried following the testing steps but got stuck at step 2. I have been continuously getting  option to enter email id.
I have closed one terminal tab so you will not be able to see few steps here. Please check the screenshot for reference.

<img width="769" alt="Screenshot 2021-05-18 at 6 14 15 PM" src="https://user-images.githubusercontent.com/83569920/118655490-3a759b80-b807-11eb-8221-d8ef76c473dc.png">
