### ISSUE TITLE
[Docs] Document a way to install Appsmith manually without the install.sh script

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4191]
There have been requests to provide a document with an initial template of `docker-compose.yml` file and then list out what needs to be done to get an Appsmith instance up. This will be a useful alternative when folks don't want to (or are unable to) run the `install.sh` script to get started.

**Comment by alderson59** [comment]
The install script requires non sudo or root, and does not provide visibility over parameters such as volume mounts, environment variables and ports. It could limit deployability on a more customised configuration.

Nevertheless, I do acknowledge that the `docker-compose.yml` appears after the install script is run, and maybe the install script does simplify the install process for some.

Perhaps consider including the docker-compose.yml in the repository directly, so we could just run from the docker compose file without the install script? If anything, it reduces one level of complexity, and that's always a win in my book :) Docker is pretty standard anyway, so newcomers to this project should be able to get it up and running easily.

Cheers

**Comment by AndrewBedscastle** [comment]
I did it like this:
- Installed it via script in a fresh ubuntu 20.04 "playground" vm
- Stopped it via docker-compose down
- Zipped the whole directory and downloaded it to my PC
- Changed the docker-compose.yml to my needs
-- No external port 80 publishing, added traefik configuration instead
- Uploaded it to the target machine and unzipped the package
- Started it via docker-compose up -d

-> I got a nice clean installation, leaving everything intact, not (potentially) changing my production docker environment

The script itself is insanely well done, chapeau! 
It fits nicely for machines without docker, docker-compose etc.

But it does not fit for production docker environments with bound ports 80 / 443 and existing reverse proxy configurations, e.g. traefik.

**Comment by ozanyolyapar** [comment]
I don't like to run shell scripts directly from repositories either. I understand, that this project is mainly for "no code" guys with not much experience, but for those, who have already a production environment, this installation method is not ideal.

Having a docker-compose.yml and some .env files would be better for the most existing environments. The installation script also collects the IP address as "installation id" and (currently) 23 events over a web-hook in the install.sh script. I could not find the place in the documentation where this is described and the script also does not seem to ask for consent. I can understand, that the developers want to know, what happens and where their application is installed, but this behavior should be at least declared in the documentation. 

@AndrewBedscastle's workaround brings more effort to launch the app, but seems the only good way to get the "clean" compose files. I tried to copy everything from the scripts in the deploy folder (deploy/template/) but it requires some customization, which I do not have time for.

**Comment by areyabhishek** [comment]
@ozanyolyapar We are working on this issue right now. 
We've described the data we collect in this [telemetry link](https://docs.appsmith.com/telemetry). This used to be under the setup folder of the document, which made it difficult to find it. But I just moved it to a top level folder so that it's easier to find.
This is the data that we collect to identify errors during the installation process.
<img width="772" alt="Screen Shot 2021-05-09 at 11 24 33 PM" src="https://user-images.githubusercontent.com/30255708/117582053-c871c800-b11d-11eb-8c0e-3ffd4c8aa4b3.png">

**Comment by brasilikum** [comment]
Nice! Looks like there is now a fat container!
Is it already documented somewhere?

**Comment by sharat87** [comment]
Hey @brasilikum, yep, we do have a fat container now, but its currently a little lacking in documentation. I'm running it through a few more rounds of testing before publishing it to the wider audience. Coming super soon 🤞

**Comment by javakonsult** [comment]
Great news, I have followed the guideline (https://github.com/appsmithorg/appsmith/tree/release/deploy/fat_container)to test the fat_container however it seems that this image is never been pushed to docker hub. Or am I missing something? :) Thank you
