### ISSUE TITLE
[Feature] Allow dismissing property pane with escape

### ISSUE THREAD

**Issue by zdb999** [appsmithorg/appsmith#4203]
Quite frequently when I'm using Appsmith, the property pane pops up and when I don't want it to. This often happens when I'm rearranging a layout or resizing things. Also, sometimes I click the wrong widget.

It would be nice if I could dismiss the property pane by hitting the escape key, instead of having to click the "x" each time. This would speed things up quite a bit, and make working with Appsmith more fluid. It also intuitively feels like something you should be able to do.

**Comment by Nikhil-Nandagopal** [comment]
@zdb999 thanks for the request. This is a great point.
@marks0351 can we do a small improvement here?
