### ISSUE TITLE
[Bug] App crashes when switching between google sheets action and another normal api action

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4204]
## Description
When trying to navigate to the debugger from the toast message that pops up on action execution failure, the debugger does not open. Trying to navigate back to the canvas also crashes the app. Captured this in a 2 minute long video for all scenarios I could think of.

### Steps to reproduce the behaviour:
1. Create any error for page load (cyclical dependency might be easy to repro)
2. Navigate to any of the datasources/query editors/API pane/etc and refresh page to trigger the error
3. Try to click on debug on the toast message.
4. Navigation fails
5. Exit the current pane, expecting to go back to the canvas. Here the app will crash.

https://user-images.githubusercontent.com/5298848/116508482-1ea16880-a8df-11eb-88cd-0283f4a78384.mov

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair thanks for the great catch!

**Comment by akash-codemonk** [comment]
The crash seems to be an issue with the datasource url editor(codeeditor) in the api pane while switching from a google sheets action to a normal api action. 

Steps
1) Create a new application
2) Create a google sheet api action 
3) Create a normal api action
4) Switch between the two actions it crashes

[Loom recording](https://www.loom.com/share/8be75a8f92174a2f9b5370487498533f)
