### ISSUE TITLE
[Feature] Allow users to define static constants

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4206]
## Summary

User requested feature:
<img width="518" alt="screen_shot_2021-04-29_at_2 19 05_am" src="https://user-images.githubusercontent.com/30255708/116513957-f5390a80-a8e7-11eb-9afe-f0924ea7c5bd.png">

**Comment by hetunandu** [comment]
We will be picking this up as part of the JS editor
