### ISSUE TITLE
[Bug] Collab Issues

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#4210]

**Comment by Nikhil-Nandagopal** [comment]
- [ ] Comments in the comments pane should be ordered by their updated timestamp
- [ ] Users should be able to tag other users using their user name
- [ ] There needs to be a visual way of switching between the comment mode and edit mode in the topbar
- [ ] The Emoji box needs better styling and looks much larger than the comment box today
- [ ] There is too much vertical spacing between comments in the thread and comments pane
- [ ] There is no marker for read / under comments in the comments pin and the unread dot never disappears from the thread
- [ ] Dropping a comment should not open the property pane of the widget 
- [ ] The comment box can expand until the max height of the comment thread while typing multiple lines
- [ ] The max height of the comment thread can expand to take up 80% of the screen height
- [ ] Hitting cancel should close the comment thread

- [ ] The comment filters do not work. Either kill or fix
- [ ] The reactions do not work. Either kill or fix
- [ ] There can be a Shortcut to enter comments mode like `c`

**Comment by sharat87** [comment]
Reactions API tracked as #4392.

**Comment by rishabhsaxena** [comment]
- [ ] Duplicate comments are getting created on adding a new comment

**Comment by Nikhil-Nandagopal** [comment]
- Z index comment behind the table
- Translucent thread
- Comments on table headers
- Internal server error on enabling the comments mode
- All comments across pages in the app section
- Clicking on the comment should navigate to the corresponding page
- Toggle comment mode for the viewer
- Show comment drawer on view mode
- Add a tooltip for new users to click on comments (Unread comments)

**Comment by rishabhsaxena** [comment]
Separate issues have been created for the remaining ones:

- Comments discovery tooltip
- Z-index issues
- Tooltip for showing users who have added reactions
