### ISSUE TITLE
[Bug] Postgres plugin returns JSON representation of "citext" columns instead of string representation

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4225]
Columns of type `citext` are essentially the same as the `text` type, but are case insensitive. It's a Postgres plugin that provides a case-insensitive text type. Ref: <https://www.postgresql.org/docs/current/citext.html>.

Currently, columns of this type look like this:

![](https://cdn.discordapp.com/attachments/760761686549463060/837510088197013524/Screenshot_from_2021-04-29_18-56-16.png)

**Comment by sharat87** [comment]
Marking Critical since there is no workaround to access the data inside `citext` columns currently. If there is indeed a workaround, please feel free to change to High.

**Comment by sharat87** [comment]
A workaround is to use `::text` on the column, like so:

```sql
select a_citext_column::text from my_table;
```

This will cast the column's value to being plain `text` type, which Appsmith handle nicely.

**Comment by Nikhil-Nandagopal** [comment]
Looks related to #4226

**Comment by bamboowonder** [comment]
I'm curious if this is an straight forward fix as it seemed closely related to issue #4226 
Thanks a bunch

**Comment by bamboowonder** [comment]
Wondering if it is ok to bump this bug again?   Every text column in all our postgres databases is citext (it's great as it takes care of case-sensitivity).    It takes so much time to manually json.parse or cast as ::text.    Now that #4226 is solved can that fix be applied to this bug?
Thank you,
