### ISSUE TITLE
[Bug] JSON column values should be the object directly in the result for Postgres plugin

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4226]
When querying a Postgres plugin with a JSON column type, like the following query:

```sql
select a_json_column from my_table
```

The result looks like the following:

```json
{
  "data": [
    {
       "a_json_column": {
         "type": "jsonb",
         "value": "{\"key\":\"value\"}"
       }
    }
  ]
}
```

The JSON value in the database is available in serialized format under the value field. Instead, we could have the JSON object directly in the row, like this:

```json
{
  "data": [
    {
       "a_json_column": {
         "key": "value"
       }
    }
  ]
}
```

This brings JSON column values inline with other data type, where the value is directly available in the row objects, as opposed to being inside a wrapper object with a `type` and `value` fields.

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum @nidhi-nair can someone pick this up?

**Comment by sumitsum** [comment]
Picking this up.

**Comment by bamboowonder** [comment]
Thank you.  working around this adds a lot of extra coding that I'll have to revert when it's fixed.  n8n handles this really well, in that when a query result (a postgres table with various text columns and a jsonb column),  is displayed, the first layer object are the text columns, and the json is an embedded object.  it makes it really pleasant to deal with.

**Comment by bamboowonder** [comment]
As far as I can see, this *appears* to be fixed, but actually isn't.  When I SELECT a jsonb column and then try to parse it, it is still considered text.  Should I be CASTing it as jsonb somehow?
For example, my jsonb column has data that looks something like this:
{
  "id": "1",
  "dma": "0",
  "city": "Portage La Prairie",
  "postal": "R1N",
  "region": "MB",
  "status": "Complete",
  "country": "Canada",
  "link_id": "9970306",
  "referer": ""
}
If I run a MAP function like this: 
{{Query1.data.map(row => ({city: row.city,postal: row.postal}))}}
I just get a blank array.
Am I missing something?

**Comment by bamboowonder** [comment]
Or here is a screenshot.  In the "Evaluated Value" it looks like the json is being seen as text.   When I try to map over it i just get blank arrays with no errors.
![Screenshot from 2021-06-10 20-21-30](https://user-images.githubusercontent.com/15368570/121626077-9956bb00-ca29-11eb-82c3-b799a0dca574.png)

**Comment by sumitsum** [comment]
Thanks for bringing this to our attention @bamboowonder . I will re-open this issue to investigate it further. For now, can you please try using `JSON.parse()` to convert into a json object from string object.

**Comment by bamboowonder** [comment]
ah ok thank you.

Jun 10, 2021 8:42:42 PM Sumit Kumar ***@***.***>:
