### ISSUE TITLE
[Bug] On Reseting the multi-select dropdown of a form widget the default value does not get selected 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4230]
Steps to reproduce:
1) Drag a dropdown
2) Make it multi select
3) Select a default value 
4) Select 3 values
5) Reset the form
6) The dropdown get reset
and observe

Observation:
after reset the default value is not displayed to user  

Expectation:
Default value must be displayed to user 

https://user-images.githubusercontent.com/71753653/116655457-c2a31680-a9a8-11eb-8c59-b071c7deb36f.mov

**Comment by somangshu** [comment]
related to #3339. Resolving this separately

**Comment by riodeuno** [comment]
Fixed in #5228
