### ISSUE TITLE
Snowflake DB support in Appsmith

### ISSUE THREAD

**Issue by shubham-maurya** [appsmithorg/appsmith#4238]
## Summary

Do you plan to integrate Snowflake DB support so that we can write Snowflake queries to power widgets? There is a widely used Snowflake Connector for Java and Python - would be great to leverage that in Appsmith.

## Motivation

I would like to build internal tools for my CS team to utilize in their day to day tasks.

**Comment by areyabhishek** [comment]
@shubham-maurya thanks for creating the issue. We do intend to create a connector for Snowflake. Have you ever done a Snowflake integration before? We'll check out their docs, but would love to know what your experience was and how long did it take you

**Comment by shubham-maurya** [comment]
Thanks for the response, @areyabhishek. I used the [python connector](https://docs.snowflake.com/en/user-guide/python-connector.html). It was very seamless - just had to pip install, and i was up and running. wrote some custom functions to make it easy to consume, but that took < 2 days dev effort.

**Comment by areyabhishek** [comment]
That's great to hear. Possible for you to do a call for 15mins with one of our backend engineers to show what you'd want to do with Snowflake? If there's a tool that you are using in house, we'd like to see that so that we can scope this integration out. We've never used Snowflake so this would be incredibly helpful! I'll email you on your commerceIQ id if you agree. LMK.

**Comment by shubham-maurya** [comment]
@areyabhishek Happy to. Will look out for your email.

**Comment by awhite** [comment]
Has there been any update on this? Our team is also looking to use Snowflake as a datasource.

**Comment by nidhi-nair** [comment]
Hey @awhite! We'll be picking this up as our next integration, do let us know if you think we should be wary of anything in particular while we implement this! 😄
