### ISSUE TITLE
[Bug]Evaluated value is 'undefined' on entering item spacing in numbers

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4241]
## Description
Release Environment - List Widget 
It is observed that when the user enters item spacing in numbers for example 150, 100 the evaluated is displayed as undefined

**Expected Result:**
Evaluated value needs to match the value entered in the Item spacing field

**Actual Result:**
Evaluated value is displayed as undefined

### Steps to reproduce the behaviour:
1. Launch Appsmith app in the release environment 
2. Drag and Drop List widget 
3. Click edit on the list widget 
4. Enter values in the item spacing field and observe the evaluated value

### Important Details
 - Version: [Safari - 14.1 (16611.1.21.161.3), Chrome - 90.0.4430.93]
 - OS: [macOS Big Sur 11.3]
 - Browser [Chrome, Safari]

<img width="891" alt="Regresison List Widget - Item Spacing undefined" src="https://user-images.githubusercontent.com/35128442/116678754-55eb4480-a9c7-11eb-99e4-f799b4eb4583.png">

**Comment by jsartisan** [comment]
Fixed in #4247

**Comment by jsartisan** [comment]
@YogeshJayaseelan the fix for this up on release.

**Comment by somangshu** [comment]
@YogeshJayaseelan confirmed that this works as expected
