### ISSUE TITLE
[Feature] Default table widget should not have any scrollbars

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4242]
## Summary

As a user, When I drag and drop a table widget, I should not see any scrollbars by default. 

## Motivation

Showing a scrollbar on the default view can leave an untidy experience for the end-user.

## Additional Context

The current default looks like this 
![Screenshot 2021-04-30 at 3 21 01 PM](https://user-images.githubusercontent.com/11089579/116679089-b8444500-a9c7-11eb-99af-a425d5fcd5dc.png)

- We wish to reduce the column width to fit all the column in the default view
- We wish to increase the table size so that there is no scroll in the header value.
- In any case, the vertical scrollbar on the body should not occur as well. 

The new default should look like this:
![Screenshot 2021-04-30 at 3 21 08 PM](https://user-images.githubusercontent.com/11089579/116679293-fe010d80-a9c7-11eb-8850-ab73ad5b03f2.png)

**Comment by somangshu** [comment]
#4022 is a related issue and will be taken up with this issue

**Comment by somangshu** [comment]
@vicky-primathon there are instances where the table shows many extra rows. Can you check to see if you can reproduce and find the issue.

@vivekverma2312 You have reproduced the issue before. Check to see if you find the issue. Do comment here in that case. We should solve scroll issues at once

**Comment by vivekverma2312** [comment]
@somangshu @vicky-primathon For old table in any application I am able to see extra rows and see a scrollbar.

https://www.loom.com/share/c9f158f896684fb7bbb9bba1034583ba

**Comment by vicky-primathon** [comment]
@somangshu can you share me any app with table widget having extra empty rows. I was not able to reproduce it at my end.

**Comment by vivekverma2312** [comment]
@vicky-primathon Please find the application to repro.
https://app.appsmith.com/applications/60ab3f3198f6c43a4b8550f7/pages/60ab3f3198f6c43a4b8550fc

**Comment by vicky-primathon** [comment]
@somangshu  **parentRowSpace** property of table widget in application shared has a value of 40 which is way bigger than usual value 10. This is causing **pageSize** to be calculated as 70 in example app. But since we have only 15 data rows we are showing remaining rows as empty. I am not aware of any recent migration that could have changed the parentRowSpace property value.

**Comment by somangshu** [comment]
#4782 is related to this. The user points out that it could be because of the new grid size. @marks0351 can you provide some insight here?
