### ISSUE TITLE
[Bug] Mongo Plugin: Return count of items in collection on query {"count" : "collection"}

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#4251]
- Return count of items in collection on query {"count" : "collection"}
  - This cmd returns the count in a different attribute that we don't return back as a response. 
- We currently rely on aggregate based cmds to get the count. 
- Note: the new form based interface for mongo will also provide a count action.

**Comment by Nikhil-Nandagopal** [comment]
This should be working in the new mongo form
