### ISSUE TITLE
[Bug] On duplicate error the application the name does not get dynamically updated to "Untitled application"

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4253]
Steps to reproduce:
1) Navigate to organisation
2) Click on the application
3) Add a name same as that of existing name in the organisation
4) observe an error is displayed
5)now observe the name of the application

Observation:
Consider application name to be "Regression"  and ensure the name exists inside the organisation, an error  message is displayed to user. 

Expectation:
However since the name is duplicate ,the name should be back "Untitled Application"

Video:
https://www.loom.com/share/1662e9ae5dba4ec7a1c26d9fbe1e01f5

**Comment by Nikhil-Nandagopal** [comment]
@pskanade is this related to your change?

**Comment by pskanade** [comment]
@Nikhil-Nandagopal Nope, this is different. Although, looks simple & I should be able to fix it quickly. I'll take it up.
