### ISSUE TITLE
[Bug] Download action : closing brackets go missing

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#4262]
## Description
1. Closing bracket ')' is not saved on Download action in table widget. The same issue exists with button widget also. 

### Steps to reproduce the behaviour:

https://user-images.githubusercontent.com/1757421/116868316-356ff400-ac2c-11eb-9e75-40e030078d7a.mov

**Comment by areyabhishek** [comment]
@arunvjn this is a critical issue. Is there a fix for this yet?

**Comment by arunvjn** [comment]
@areyabhishek We will be fixing this when we introduce a superior JS parser in Appsmith. Will update the documentation to remove this feature for now.

**Comment by nidhi-nair** [comment]
Lowering priority in light of the documentation update

**Comment by Nikhil-Nandagopal** [comment]
@arunvjn @ajinkyakulkarni can we please fix this? This is a really bad experience

**Comment by ajinkyakulkarni** [comment]
Do we want to use https://github.com/appsmithorg/appsmith/issues/2435?

**Comment by hetunandu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4262?planning-poker) with ZenHub @sumitsum

**Comment by mohanarpit** [comment]
Closing in favour of #3027
