### ISSUE TITLE
[Bug] Users unable to drag a column outside of viewport of a property pane to rearrange column order

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4266]
Issue reported by a user. They have a table with many columns(over 25+ at least). There's a bug that makes it difficult to reorder columns.
1. If you drag the column header in the table, it's a bit awkward to get it scrolling but it does work. This needs some improvement. See video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f9ec0e8dde15486cb20fb141d7e15bd6-00001.gif)](https://www.loom.com/share/f9ec0e8dde15486cb20fb141d7e15bd6)
2. Reordering inside the property pane is not possible. Ideal solution is to detect that the user is trying to scroll upwards and automatically scroll the property page downwards. See gifs and screenshots by the user below.

![Screen_Shot_2021-05-03_at_10 51 57_AM](https://user-images.githubusercontent.com/30255708/116894904-37e44500-ac50-11eb-891a-aac2e92d90c0.png)

How it works inside Google Appsheet:
![2021-05-03_11 00 41](https://user-images.githubusercontent.com/30255708/116894892-331f9100-ac50-11eb-9554-97e722faec2e.gif)

**Comment by nidhi-nair** [comment]
Another possible approach from a user input on Discord: 

> Regarding the draggin/reordering/scrolling a long list of columns, in other apps I've found that I can click and drag and then use the scrollwheel on mouse, or click-drag and hit PGUP PGDOWN keys. (I haven't tested this yet with Appsmith)

**Comment by areyabhishek** [comment]
@somangshu @vicky-primathon Could we get to this issue? I ran into this today and was quite difficult to deal with.

**Comment by somangshu** [comment]
@areyabhishek apologies for completely missing this. We will prfioritize this.

The UX below sound like the right solution.

> > Regarding the draggin/reordering/scrolling a long list of columns, in other apps I've found that I can click and drag and then use the scrollwheel on mouse, or click-drag and hit PGUP PGDOWN keys. (I haven't tested this yet with Appsmith)

Note: 
| Requirement | Priority | Comments |
| The user can select a column tile by clicking on the drag icon, the user can then use PGUP and PGDOWN to move/reorder the time | High | - |   
| The user can click and drag a tile, The scroll should be automatic when the tile touches the top/bottom of the section, The scroll should stop when the tile is not touching the top/bottom of the section. | High | - |

Please suggest any changes required.

@riodeuno why is this issue in the icebox, Any reasoning behind this?

**Comment by areyabhishek** [comment]
@somangshu  Should we assign this to Li? Or this too much for him right now?

**Comment by somangshu** [comment]
Li can work on this, But might take some time to get a hold of it. Its better to get somebody who is aware of the table widget and the tile drag control.

**Comment by vicky-primathon** [comment]
We are only fixing the the issue here. The enhancement i.e. 
`The user can select a column tile by clicking on the drag icon, the user can then use PGUP and PGDOWN to move/reorder the time`
will be worked upon as an enhancement in table/tabs widget.

**Comment by somangshu** [comment]
Is the implementation based on the above PRD complete @vicky-primathon, I am confused with the above comment

**Comment by vicky-primathon** [comment]
@somangshu  2nd part of the requirement mentioned is completed 
`The user can click and drag a tile, The scroll should be automatic when the tile touches the top/bottom of the section, The scroll should stop when the tile is not touching the top/bottom of the section.`

But since 1st requirement mentioned was an enhancement we skipped it as of now after discussing with Nikhil.  As discussed with Nikhil this requirement can be taken up as an enhancement and not immediately required to fix the issue.

**Comment by somangshu** [comment]
@vicky-primathon this dosent seem to function on release / prod, re opening this issue, Please link it to #10046 is we are fixing it there
