### ISSUE TITLE
[Bug] Date filter in the table doesn't let you type a time

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4277]
### Steps to reproduce the behaviour:
1. Choose a column type as date
2. Try to filter by date, but notice that you can't type anything in the time input.
3. Just clicking the time input closes the popup
https://www.loom.com/share/763d5181b9f941c4bfc147ae40c8d2b4

**Comment by Rishabh-Rathod** [comment]
Hi, I would like to resolve this issue.

**Comment by Rishabh-Rathod** [comment]
Same behavior when clicked `month` or `year` also instead of `time`. 
I would like to resolve this issue.

**Comment by somangshu** [comment]
👋 Hi @Rishabh-Rathod, Thanks for showing interest in contributing to Appsmith. We look forward to it. 

To get you started here is a doc that talks about [Running Client Codebase](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md). Please let us know if you have any queries. 😃

**Comment by Rishabh-Rathod** [comment]
While debugging this issue I found that when clicked on `DatePicker` in the filter,  the triggered event propagates to the **Popover** in `TableFilter.tsx` https://github.com/appsmithorg/appsmith/blob/639cba9095ba844177b096436a05a79e8047d0a8/app/client/src/components/designSystems/appsmith/TableComponent/TableFilters.tsx#L165-L174

and hence `onClose` is called which leads to the closing of the table filter.

Ideally, the  Popover in [ErrorTooltip](https://github.com/appsmithorg/appsmith/blob/639cba9095ba844177b096436a05a79e8047d0a8/app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx#L139) which wraps DatePicker, should stop the event propagation. 

https://github.com/appsmithorg/appsmith/blob/639cba9095ba844177b096436a05a79e8047d0a8/app/client/src/components/editorComponents/ErrorTooltip.tsx#L46-L56

I tried to stop event propagation from this Popover but this had no effect and to my surprise, the `onClose` doesn't even get called
```js
onClose={(e)=>{e.stopPropagation()}}
```

I also tried to increase `z-index` of the Popover which wraps DatePicker but that also didn't help.

Any thoughts?

**Comment by somangshu** [comment]
Hey, @Rishabh-Rathod this makes sense, Please create a PR with your solution, We will be more than happy to receive your contributions. 

Kindly let us know if you need any help from our side with this!

**Comment by Rishabh-Rathod** [comment]
One of the resolution to this is by adding a backdrop to **Popover** in `TableFilter.tsx`

```jsx
<Popover
   {...otherProps}
   hasBackdrop  // adding this prop
/>
 ```

But this changes the behaviour of table filter popover, on click of any other component it will only close the popover as the backdrop will handle the click.

currently on click of any other component popover closes but the click is also handled.
For eg - After the table filter is opened if the user clicks on Table property pan's any property then

**Currently**
1. Table filter is closed.
2. Property Pan gets focused which is normal onClick behaviour.

**After Above Change** 
1. Only the Table filter is closed.
2. User will again need to click on Property Pan to get it in focus.

@somangshu let me know what is the expected behaviour, should it behave as same as before or the above-mentioned change will be fine?

**Comment by somangshu** [comment]
@Rishabh-Rathod got it, This would a major change to the UX. @Debsourabh @momcilo-appsmith what are your thoughts here? 

@marks0351 can you think of a better solution?

**Comment by vicky-primathon** [comment]
@somangshu  By controlling the click propagation inside date picker popover the clicks can be stops from reaching to TableFilter popover. By this approach the current filters UX will also remain intact.

**Comment by somangshu** [comment]
@vicky-primathon thats a good point, We have a property in the core component which allows the popover to remain open on click of the date etc, Does this resolve our problem?

**Comment by vicky-primathon** [comment]
Yes, will be used isOpen property of date time picker component along with capturing clicks.
