### ISSUE TITLE
[Bug] Date picker's time resets on clicking outside

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4278]
## Description

While using date picker in YYYY:MM:DD HH:MM:SS format, the input field resets to 11:00 when the user chooses 23:00

### Important Details
 - Version: [Cloud]

**Comment by avishekwrx** [comment]
https://drive.google.com/file/d/1PtLaL3cfdy5ns18fZGsPJ6UKZD2IQVte/view?usp=sharing

**Comment by somangshu** [comment]
@areyabhishek if you correctly check, The moment format used here consist of `hh` and not `HH`. As per the moment docs, `hh` is 12 hour format and `HH` is 24 hour format. So we can safely say that the behaviour is intended. However, I think the improvement here is to include `A` in the date format such that AM/PM shows up with the time stamp in this case. 

Here is what the [moment docs say](https://momentjs.com/docs/#/parsing/string-format/)

H HH | 0..23 | Hours (24 hour time)
-- | -- | --
h hh | 1..12 | Hours (12 hour time used with a A.)

**Comment by avishekwrx** [comment]
Thank you for the clarification.

Currently, there is no way for the user to select a date of anytime after
12 PM in this format.

Also the query is picking up the corresponding AM timestamp in back-end
instead of the PM timestamp.

Avishek

**Comment by somangshu** [comment]
Dev note: 
 - We need to add `A` or `P` to the date format `YYYY-MM-DD hh:mm:ss` such that all time after 12PM show up correctly
 - We should also check the rest of the formats for any other errors.
