### ISSUE TITLE
[Bug] App crash on dragging Table widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4280]
### Steps to reproduce the behaviour:
1. Go to Page
2. Click on Add widget icon
3. Drag Table widget on page
4. Observe the crash with below error

Error message: Cyclic dependency found while evaluating. Node was: product.config

### Important Details
 - Environment: release
 - OS: MacOSX
 - Browser: chrome
 - 
<img width="1785" alt="Screenshot 2021-05-04 at 11 25 23 AM" src="https://user-images.githubusercontent.com/83569920/116966519-ff834c00-accd-11eb-9173-d897140979c2.png">

**Comment by giubueno** [comment]
Which version, please?

**Comment by somangshu** [comment]
Hey @giubueno, This occurred on the release environment if that's what you are asking. Let me know if this answers your question?

**Comment by vivekverma2312** [comment]
Issue has been verified and working fine now.
