### ISSUE TITLE
[Bug] Debugger shows errors for evaluations done on page load

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4298]
## Description

When there are actions that run on page load, the dynamic binding does not evaluate to a valid value and hence the debugger  always shows a set of errors that would typically disappear after action execution.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create a page with an API that executes on load, and is displayed in a widget
2. Refresh the page
3. Debugger will show an error for data being invalid

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by prapullac** [comment]
The error is been recorded in the Log section of the Debugger however the error numbering is not displayed 
Adding the video:
https://www.loom.com/share/969b760fae5f4e5eb906826dbe8b778d

**Comment by Nikhil-Nandagopal** [comment]
@prapullac this is technically fine because the table was in an error state before the API loaded but then recovered after

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal Is there no way to prevent erroring out before evals take place? This has pretty poor UX on page load with minimal APIs running. A lot of our users have long running APIs that would show their pages in broken state till the pages load.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair The problem is that the user did not add a check in their code and wrote something like
{{ API1.data.map(() => { ... }) }}
while API1.data is undefined at the start. I think this is actually good to inform them that they have missed adding this check which can break in other scenarios as well.

**Comment by nidhi-nair** [comment]
That's a fair point @Nikhil-Nandagopal , I don't dispute the value addition to safe handling of data. But to be able to achieve this I think we should be displaying the evaluated value in the debugger. Or hint at the fact that the data may not have loaded at that point. Right now we're not conveying this intent to the user.

A user that looks at their screen and sees something similar to this shot would just end up getting more confused. I imagine proper use cases would take more time for these fields to load, and hence the errors would last longer.

https://user-images.githubusercontent.com/5298848/119324786-d5ee8c80-bc9d-11eb-8fec-7250864716b8.mov

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair Great point, we're adding the evaluated value to the debugger. Hopefully, with the addition of the JS errors it will be clear that the data did not load yet.
