### ISSUE TITLE
[Bug] Cannot delete datasource and debugger doesn't work

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4302]
Report from a user:
R"Cannot delete data source as 1 action is using it". This error pops up when I tried to delete a datasource. The data source isn't being used by any widget or call, couldn't make sense of this message. Also, the debug button below in the error message doesn't do anything
![image (13)](https://user-images.githubusercontent.com/30255708/117070664-b2de5600-ad4b-11eb-9798-42191143bff7.png)

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk can we remove the debug button from system errors

**Comment by akash-codemonk** [comment]
The debug button no longer appears for this error. Closed with #4311
