### ISSUE TITLE
[Bug] Sorting table column with numbers is not working properly

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4320]
## If any column have numbers then the sorting is not working properly

What happened -- Looks like it is sorting the numbers as string

### Steps to reproduce the behaviour:
1. Go to page and add table widget
2. Create a column with numerical values in it (eg, 10, 12, 21, 103 etc)
3. Click in sort icon for that column
4. Observe that sorting do not populate the correct result

<img width="390" alt="Screenshot 2021-05-05 at 10 50 30 AM" src="https://user-images.githubusercontent.com/83569920/117107554-63297a00-ad9f-11eb-8c5a-e49bb56f16ad.png">

**Comment by techbhavin** [comment]
@somangshu @vivekverma2312  
here when we add number data in a column type `Plain Text`. then it is sorting like string. 

when we have column type `Number` then is working as expected.
https://user-images.githubusercontent.com/58818598/119962589-d2704380-bfc4-11eb-90e3-004c1bf94799.mov

**Comment by somangshu** [comment]
@riodeuno need you help regarding the above ☝️
