### ISSUE TITLE
[Bug] Table UI associated with Google API is broken on forked application 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4324]
Steps to reproduce:
1) Add a organisation A --> Application A
2) Now add an Google Sheet API (List )
3) Add an Table widget
4) Now navigate to home page 
5) Click on Action 
6) Click on Fork and select an organisation 
7) Now open the forked Application A
and observe 

observation:
Error message stating Auth error and a distorted table is displayed  to user

Expectation:
It is expected that an empty table is displayed to user with an Auth error message

![Screenshot 2021-05-05 at 11 52 40 AM](https://user-images.githubusercontent.com/71753653/117125507-384b2000-adb7-11eb-8bf6-39081979b8f7.png)

**Comment by techbhavin** [comment]
@prapullac  

can you give more detail on what auth error message we want to display here?

cc: @somangshu

**Comment by somangshu** [comment]
@techbhavin I think the table needs to be empty and not have the headers as we can see the image. Check out the expected behaviour in the description

**Comment by prapullac** [comment]
Hi @techbhavin 
Here the Auth message is correct ,however we are to concentrate on the distorted table  ie header of the table is not alinged with the rows.

**Comment by techbhavin** [comment]
thanks, @prapullac forgive more clarity on this issue.

I am not able to reproduce the issue with the given step in [comment -876278392](https://github.com/appsmithorg/appsmith/issues/4324#issue-876278392). 

can you please help me with this? 

![image](https://user-images.githubusercontent.com/58818598/118105012-7d93d100-b3f9-11eb-94ff-32b2e1dfcc9d.png)

**Comment by prapullac** [comment]
Hi @techbhavin 
I am unable to reproduce the issue hence we can close the issue
