### ISSUE TITLE
[Docs] Improve main Readme to show step required for client side development

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4330]
## Documentation Link 

[Main repo readme](https://github.com/appsmithorg/appsmith#readme)

## Describe the problem

The `Contributing` section in the document does not talk about the relevant setup required for the frontend development, The result of this is that somebody new always spends time setting up things they didn't need in the first place. 

## Describe the improvement

Clearly state that if the developer is here to contribute to the client-side code then this should be a great starting point.

**Comment by areyabhishek** [comment]
This is fantastic improvement :D
