### ISSUE TITLE
[Feature] FAB or Icon buttons

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4353]
Need a button widget which just shows an icon, along with all other button properties.

<img width="677" alt="Screen Shot 2021-05-07 at 4 30 40 AM" src="https://user-images.githubusercontent.com/30255708/117375639-0f2cab80-aeed-11eb-9bd7-492dda683231.png">
<img width="380" alt="Screen Shot 2021-05-07 at 4 36 35 AM" src="https://user-images.githubusercontent.com/30255708/117375977-d50fd980-aeed-11eb-938f-1715245faeb8.png">

Product requirements:
1. User should be able to choose a button shape: square or circle.
2. User should be able to choose a style: filled shape, outline, or no outline(only icon)
3. User should be able to choose an icon from a library for the button

The button can unfurl a menu or a dropdown. 
<img width="137" alt="Screen Shot 2021-05-07 at 4 38 17 AM" src="https://user-images.githubusercontent.com/30255708/117376104-13a59400-aeee-11eb-83c0-d740994b6727.png">

Not sure if this should be combined with #4149 or be a separate button. A separate button makes sense for discoverability.

## Product requirement document
https://www.notion.so/appsmith/Icon-Button-FAB-Widget-bc4d8100007c4602a59eef78fce24747

## Developer handoff designs:
https://www.figma.com/file/A4rNSbo0GXGjubJmqwK8Db/Icon-Button-Widget?node-id=0%3A1

**Comment by somangshu** [comment]
In favour of discoverability, We should keep the `icon button` widget as a separate entity.

**Comment by jsartisan** [comment]
@somangshu @areyabhishek The icon button with a dropdown can be created with the menu widget itself.

**Comment by somangshu** [comment]
agreed @jsartisan, The menu button takes care of one bit, We should come up with `Icon Button Widget` in this requirement

**Comment by areyabhishek** [comment]
This should also be included in the table widget where an icon button will be more useful

**Comment by jsartisan** [comment]
Here is the design file for the widget - https://www.figma.com/file/A4rNSbo0GXGjubJmqwK8Db/Icon-Button-Widget?node-id=0%3A1
