### ISSUE TITLE
[Feature] Need color agnostic hover states for buttons and table cells

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4354]
## Summary
Every button should have a hover and active state irrespective of the color of the button.

## Motivation
Users are used to seeing buttons that react to their mouse and it's a natural part of every web product.

## Additional Context
Different kinds of hover states:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/85f805dc874a4a40b1e7b4ca5a9f5c4b-00001.gif)](https://www.loom.com/share/85f805dc874a4a40b1e7b4ca5a9f5c4b)

Related to #4149 #4353

**Comment by jsartisan** [comment]
@areyabhishek My rule of thumb for hover state is using the darker shade of whatever the color of the button is. For eg. - if the button color is white, we can use a light shade of grey as the hover color.

If the button color is dark, use a lighter shade of that color.

For e.g from these colors - https://tailwindcss.com/docs/customizing-colors

if the button color is red500, I will use red700 for hover.
if the button color is red700 or higher, I will use red500 as the hover color.

**Comment by momcilo-appsmith** [comment]
@riodeuno @somangshu This has been solved for the button widget but is not for the button in the table widget. How can we solve this for both?

**Comment by riodeuno** [comment]
Proposed solution
==

- The hover effect should be made a function of the underlying button component of the button widget. 
- The components should be extracted into `widgets/common/components` folder and re-used in both the button widget as well as the table widget.
- The same component can also be re-used in button group, menu button and filepicker widgets.
- We should also expose the same properties which style the button widget today to all the other widgets mentioned above.

**Comment by dilippitchika** [comment]
Document on the solution - https://www.notion.so/appsmith/Widget-hover-colors-165e54b304ca4e83a355e4e14d7aa3cb

Please discuss with me before estimating

**Comment by dilippitchika** [comment]
Document has been updated, needs a review from @momcilo-appsmith 

https://www.notion.so/appsmith/Widget-hover-colors-165e54b304ca4e83a355e4e14d7aa3cb

**Comment by momcilo-appsmith** [comment]
@dilippitchika I just reviewed it. Looks good to go!

**Comment by dilippitchika** [comment]
@jsartisan I am moving this to icebox and removing out of the sprint. I will add this to widget reskinning epic.

**Comment by somangshu** [comment]
@dilippitchika in that case this should be merged into theming and have any changes that are needed, I suggest it gets reviewed and shipped with theming, is there any other blocker or a reson we pick this up in widget reskinning ?

cc @jsartisan do you think that might be a challange?

**Comment by dilippitchika** [comment]
My bad i added this in theming epic but wrote widget reskinning in the above comment. Unless Pawan raises any concerns it's part of theming

**Comment by somangshu** [comment]
@wmdev0808 is there a PR for this? I am wondering if we have something to merge into theming and then continue work on that 

cc @jsartisan @dilippitchika

**Comment by dilippitchika** [comment]
Hey @somangshu, i believe @jsartisan closed the PR for this. I already verified the PR and it's working fine.

**Comment by somangshu** [comment]
Again my question is if we have the code written here is merged in App theming and how are we gonna track the work on it, With the help of this issue?

**Comment by dilippitchika** [comment]
I believe the code is not merged in app theming @jsartisan can you confirm?

**Comment by jsartisan** [comment]
This is already fixed. 

cc: @dilippitchika
