### ISSUE TITLE
[Bug] What's with the G in table widget

### ISSUE THREAD

**Issue by vasani-arpit** [appsmithorg/appsmith#4365]
## Description

URL is being cut off when there is multiple images in table column. 

![image](https://user-images.githubusercontent.com/6497827/117410945-a9621300-af30-11eb-8af6-047c19e8f17a.png)
![image](https://user-images.githubusercontent.com/6497827/117411550-4fae1880-af31-11eb-83da-8153d82d671f.png)

### Steps to reproduce the behavior:
Add steps to reproduce this behavior, include console / network logs & screenshots
1. Create a page in appsmith cloud
2. add a table widget
3. remove the sample data and add this `[ {"img":"https://t4.ftcdn.net/jpg/02/25/46/33/360_F_225463322_MGgmerZgA9kcbpwfhD1MkS9xC05f9fVM.jpg,https://t4.ftcdn.net/jpg/02/25/46/33/360_F_225463322_MGgmerZgA9kcbpwfhD1MkS9xC05f9fVM.jpg"}
]`
4. change column type to image

### Expected behavior
Small preview of both the images should be shown in the row. 

### Actual behavior
Seeing only small preview of last image

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser: Chrome

### Workaround
add a space before comma 🤷‍♂️

_feel free to close this if this is a duplicate._

**Comment by Nikhil-Nandagopal** [comment]
@vasani-arpit thank you for the issue report! We don't currently support multiple images in a single column. You can display these by assigning them individual keys. We'll take this up as an enhancement to the table but for now, you can achieve this by splitting the image under 2 keys :)

[{ "img1": "", "img2": "" }]

**Comment by vasani-arpit** [comment]
For now I have set computed value to `currentRow.productImages.split(",").join(" ,")` and it is working as I want it to. 
![image](https://user-images.githubusercontent.com/6497827/117448967-070c5480-af5d-11eb-8300-aaf11849e470.png)

Let's see what future holds. 

_You can close this one if you need to_

**Comment by Nikhil-Nandagopal** [comment]
🤯 Ok that is my bad, I didn't think we supported that! This is clearly a bug then.
