### ISSUE TITLE
[Bug] I get a 'Oops! Something went wrong' screen when trying to search for something in the entity explorer

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#4370]
## Description

I tried to search for something in the entity explorer, and I got a 'Oops! Something went wrong' message.

### Steps to reproduce the behavior:
1. Go to the search bar in the entity explorer
2. Try typing anything and wait a few seconds
4. See an error

### Important Details
 - Version: Cloud
 - Browser: Chrome

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena @kaushik94 can someone have a look at this?

**Comment by RakshaKShetty** [comment]
we have removed the entity explore search, closing this bug
