### ISSUE TITLE
[Bug] Table row is not rendering the example data properly when table widget is dropped on the canvas the first time. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#4376]
## Description
![Screenshot 2021-05-07 at 10 49 58 PM](https://user-images.githubusercontent.com/1757421/117486087-d0e3ca80-af86-11eb-89f1-1929fd942f90.png)

**Comment by somangshu** [comment]
@sumitsum can you add the steps to reproduce this bug. I can't do it when I check in the safari/chrome browser.

**Comment by vivekverma2312** [comment]
@somangshu 
Steps to repro the issue:
1. Drag and drop Table 1
2. Do binding with any DB query/API
3. Now drag and drop Table 2
4. Observe that Table 2 data is not coming

<img width="1093" alt="Screenshot 2021-05-19 at 4 43 06 PM" src="https://user-images.githubusercontent.com/83569920/118805339-73734600-b8c3-11eb-9e2f-237d2f1f4957.png">

**Comment by somangshu** [comment]
This happens until the old table is removed
