### ISSUE TITLE
[Bug] Error with debugger for table

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4384]
I am trying to build application as here "https://blog.appsmith.com/building-a-store-catalogue-management-system-using-appsmith-and-graphql"
but when I faced issue while editing Table widget property  and when I click on debug it is not working. The very first time it worked, but after that it doesn't work.

[Editor _ Appsmith - Google Chrome 2021-05-05 15-38-17.zip](https://github.com/appsmithorg/appsmith/files/6426359/Editor._.Appsmith.-.Google.Chrome.2021-05-05.15-38-17.zip)

_Originally posted by @MusafirRahi123 in https://github.com/appsmithorg/appsmith/discussions/4326_

**Comment by akash-codemonk** [comment]
Closing this for now as this seems to be working. Added a comment as well https://github.com/appsmithorg/appsmith/discussions/4326#discussioncomment-746998
