### ISSUE TITLE
[Bug] Can't copy text from response body of Google sheets

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4385]
## Description

I can't copy anything from the API response of Google sheets. This is pretty inconvenient.
<img width="601" alt="Screen Shot 2021-05-09 at 10 01 45 PM" src="https://user-images.githubusercontent.com/30255708/117579808-34e6ca00-b112-11eb-89e8-ddb04c8cecb9.png">

**Comment by nidhi-nair** [comment]
@areyabhishek This is a debugger related bug and is picked up in #4335 I believe. Please correct me if I'm wrong, @Nikhil-Nandagopal?

**Comment by areyabhishek** [comment]
@nidhi-nair This now works on release. I'm closing this issue.
