### ISSUE TITLE
[Bug] Inconsistency in year selection range for Date picker field and default/min/max field

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4408]
### Steps to reproduce the behaviour:
1. Drag and drop a Date picker widget
2. Click on widget to open calendar
3. Click on  year and scroll -- Observe the selection ranges from 1921-2041
4. Now click on property pane and select default/min/max field
5. If I click on year drop-down from calendar 
6. Observe that the year ranges from 2001 - 2041

Environment: Prod

<img width="429" alt="Screenshot 2021-05-10 at 6 31 45 PM" src="https://user-images.githubusercontent.com/83569920/117663202-04f50080-b1be-11eb-8781-1e37de3a5a46.png">

<img width="466" alt="Screenshot 2021-05-10 at 5 49 04 PM" src="https://user-images.githubusercontent.com/83569920/117663339-32da4500-b1be-11eb-9d23-585e6a3205e2.png">

**Comment by techbhavin** [comment]
In issue #4137 we already extend the min and max field to 100 years.

 this issue is related to issue #4137.

**Comment by somangshu** [comment]
@techbhavin this issue is related to inconsistency between the date-picker input limit and the property pane input limit. 

If you think that this issue is fixed in a certain PR please link this issue to the PR, we will test it out.
