### ISSUE TITLE
[Bug] Color picker covers the input field in small property panes

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4413]
## Description
Open the color picker inside the container widget, see that the input field is covered. 
<img width="329" alt="Screen Shot 2021-05-11 at 2 51 57 AM" src="https://user-images.githubusercontent.com/30255708/117726276-f9c4c380-b203-11eb-8da4-a8e612efebb6.png">

**Comment by areyabhishek** [comment]
The problem is that the popover always opens up when you focus on the input.  But this is a small issue. We can improve it when we relook at the property pane.

**Comment by somangshu** [comment]
Hey, that is indeed an issue, We can fix this easily by not showing the popover on input focus.

**Comment by somangshu** [comment]
The new colour picker design aims to resolve all this better. Right now the user can use the JS option write a hex code directly.

@vibhandikyash lets find the right fix for #6978 in this PR and get that out soon.
