### ISSUE TITLE
[Feature] Text widget should have padding controls

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4419]
## Summary
The text widget has no padding controls so it looks ugly when you color the background.

<img width="480" alt="Screen Shot 2021-05-11 at 4 32 32 AM" src="https://user-images.githubusercontent.com/30255708/117734884-00f2ce00-b212-11eb-833c-a915642b7bc7.png">
Providing padding controls will allow the developer to create better looking text cards.

**Comment by somangshu** [comment]
@vibhandikyash we will introduce a property `margin`. This will apply on all the sides.

<img width="538" alt="Screenshot 2021-07-01 at 4 46 37 PM" src="https://user-images.githubusercontent.com/11089579/124115905-f6bfb400-da8b-11eb-84d9-ff3b9781cffd.png">

**Comment by vibhandikyash** [comment]
As per discussion with @marks0351, Will be resolving this issue with 2587.
