### ISSUE TITLE
TabIndex and a11y in form controls

### ISSUE THREAD

**Issue by vasani-arpit** [appsmithorg/appsmith#4436]
## Description

Okay. So there is two issues. Both are related to each other so I will combine it into one. 

See this gif first
![I6sfJQMRsh](https://user-images.githubusercontent.com/6497827/117860472-f554e500-b2ad-11eb-8ba2-e8c0b0aa7371.gif)

Bug 1) When user reaches to dropdown widget via hitting tab tab tab it is not highlighting as other controls like textbox but control has reached there, It is just not showing it. You will know it by hitting ⬆ ⬇ key
Bug 2) when dropdown is open and user is navigating in the options the same thing happens. Control is navigating but it is not showing the way when it shows with mouse hover event

### Steps to reproduce the behavior:
steps to reproduce this behavior, include console / network logs & screenshots
1. Take a form widget
2. add text box and drop down widget same as shown in gif
3. hit keyboard keys same as shown in gif

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser: Chrome

**Comment by marks0351** [comment]
- Focused state for dropdown
- Focused state for dropdown entries
- Focused state for datepicker
- Borders on datepicker field 
- Borders on datepicker popup when placed inside a container.
- Focused state for checkbox
- Focused state for radio
- Focused state for switch

@momcilo-appsmith @Tooluloope we would need designs for these widgets and their appropriate states.
we need to make sure to reach these widgets using keyboard interactions. Today most of them are interactable but we don't show a difference(by highlighting) when they are focused.

**Comment by vasani-arpit** [comment]
Is there any approx timeline which you can provide me for this? I can understand it's a lot to ask as the appsmith service and code is free. and of course you have a other things which are ongoing. 
But the thing is we have built an **entire stock management system using appsmith cloud**. The fact that we can do this without writing front-end or backend code is really really remarkable. so thank you for making appsmith.

For us it is time to go to production, and these data entry people can't afford to use mouse while entering thousands of entries.

It is confusing when you are jumping in the long form using tab.... tab.... tab.... and boom, it vanishes like thanos snapped it out of existence.

**Comment by somangshu** [comment]
Hi @vasani-arpit, Thanks for the kind words. While we started looking into this we realized that this is something we need to work on product wide scale to provide a better UX. Hence we have taken to call to properly design this and then develop it. Given all that, this falls low on our priority list and I do not have the right timelines for this. I will still try my best to push this ahead and keep you posted about it here.

**Comment by YogeshJayaseelan** [comment]
@Tooluloope This issue still exists in release 

https://loom.com/share/96fba8f765394376bf4c25fe63c27a7d

**Comment by yaldram** [comment]
The a11y controls don't work for all the widgets, `Button Widget` when used inside a form does not get focus on a tab press. This is very crucial, especially for the `Submit & Reset` buttons inside the Form.

**Comment by dilippitchika** [comment]
Fixed in https://github.com/appsmithorg/appsmith/issues/7757
