### ISSUE TITLE
[Feature] Evaluate other Custom charts

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#4437]
## Summary

It seems d3.js enables a greater level of customisation and flexibility than other charting libraries. Can be called as D3JS widget

There are some other alternatives
- https://echarts.apache.org/ - t’s a popular open source Apache project. Seemed pretty decent. They also had themes & customization for colours out of the box
- https://plotly.com/javascript/ - very powerful, well adopted & performant. Also open source

**Comment by thebf** [comment]
There are lots of high quality examples and it would be a good start for read only custom widgets, as long as there is a good user story for feeding it data from the overall appsmith app.

**Comment by SamWoolerton** [comment]
ChartJS is also worth considering; I'm using it in an iframe for one project, [here's a link](https://discord.com/channels/725602949748752515/1084928429352300604/1084928616879624243) to my message in Discord with the code

echarts and plotly look good too though

**Comment by somangshu** [comment]
@rajatagrawal Can we drop a conclusion here and close the ticket?

**Comment by rajatagrawal** [comment]
We have decided to go with ECharts. The complete analysis of the research is here : https://www.notion.so/appsmith/Fusion-Charts-Deprecation-Alternatives-7b1a1b9a4f75462db13d1b3796b75c3a

**Comment by marc-sommer** [comment]
@rajatagrawal thats great news! do you have a rough timeline on when you'd expect to migrate from FusionCharts to ECharts?

**Comment by rajatagrawal** [comment]
@marc-sommer 
We have already released ECharts for basic charts like line chart & area chart. Custom ECharts should be rolled out by the end of August.
