### ISSUE TITLE
[Feature] Progressive loading in dropdown/select widget

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4444]
Currently, the select widget loads and shows all options given to it. It can be populated by the response from an API action, but if there's a lot of items in the dropdown, it can get slow to even load all of those items from the API action. There should be a way to load just a few, and then load more as the user scrolls down for more, or perhaps when they filter for something specific inside the dropdown.

**Comment by kritid11** [comment]
I have a form where I need input from the dropdown which is getting data from the server. If the data is too much, It might take time to load all the contents in one go. So If we can keep loading the data in chunks, as and when the user scrolls down, would help.
I am already using the table widget and selected row feature for the update functionality. But while creating a record, I need to show all the data in the dropdown.

**Comment by somangshu** [comment]
@Tooluloope kindly identify a solution around this

**Comment by Tooluloope** [comment]
> @Tooluloope kindly identify a solution around this
> 

I currently, use a Virtual scrolling feature enabled on the RC-Select to handle this performance issue.

It's still need a deep thought, cos there might be time you'd want to access some thing like ```Multiselect1.SelectedOptionValues[1000]``` or even do some filtering or some random JS logic on the options which might require you having all the data or options to be able to run such logic

**Comment by Tooluloope** [comment]
Also @somangshu isn't this the same as #5081, since they both have to be served rendered to filter or load options

**Comment by Nikhil-Nandagopal** [comment]
+1 Maybe the dropdown isn't the best widget for this. Should we do a typeahead widget instead?

**Comment by somangshu** [comment]
@Tooluloope @Nikhil-Nandagopal this is related to virtualisation of the list and infinite loading. The filtering is raised inside #5018 where the discussion also points to an autocomplete/typeahead widget for async loading.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu Technically you are right but my question is should we even support infinite scrolling in a dropdown. I am not sure if dropdowns typically behave that way and the right UX pattern here maybe to use a typeahead

**Comment by somangshu** [comment]
Closing this in favour of [#5018](https://github.com/appsmithorg/appsmith/issues/5018#issuecomment-872301707)
