### ISSUE TITLE
[Bug] When added wrong data type in list widget page crash

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#4449]
## Description
When added wrong data to List widget whole application crashes

### Steps to reproduce the behaviour:
1. Add List widget to any application
2. edit data for list widget eg. {{[appsmith.URL.fullpath]}}
3. try to edit above 'appsmith.URL.fullpath' in data panel
4. App crashes

https://user-images.githubusercontent.com/7846888/117942662-f119dd80-b328-11eb-98e8-e17e955a6815.mov

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by jsartisan** [comment]
Merged into release #4189
