### ISSUE TITLE
[Bug]Evaluated value popup overlaps the DB query editor when the browser is minimized

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4458]
## Description
Release Environment - PostgresSQL - It is observed that due to overlapping the cursor in the DB query editor is hidden due to which the user feels he/she cannot complete the action 

Expected Result:
Cursor should be visible clearly in the minimized mode and the evaluated value popup should be placed appropriately 

Actual Result:
Due to overlapping the cursor in the DB query editor is hidden due to which the user feels he/she cannot complete the action 

### Steps to reproduce the behaviour:
1. Launch Appmsith app in the Release Environment 
2. Expand DB
3. Create new Datasource with postgresSQL
4. Set up authentication 
5. Minimise the screen to 70-80% mode 
6. Check for the Evaluated value popup overlap and the DB query Cursor 

**VideoLink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/805ca00592614bdb8f4b02535927e760-00001.gif)](https://www.loom.com/share/805ca00592614bdb8f4b02535927e760)

### Important Details
 - Version: [Chrome - 90.0.4430.212 ]**
 - OS: [MacOS Big Sur 11.3]
 - Browser [Chrome]

**Comment by rohan-arthur** [comment]
@parth-appsmith wdyt should be the expected behaviour here?

**Comment by rohan-arthur** [comment]
design link: https://www.notion.so/appsmith/Bug-Eval-window-overlaps-query-editor-b5b4cb0c75da4deda4827bc14049ada3

**Comment by Irongade** [comment]
@rohan-arthur  That notion link has been deleted

**Comment by prapullac** [comment]
@Irongade  : looks the evaluated values is overlapping on the query pane. Please find the attachment of screenshot.
![Screenshot 2022-10-22 at 10.34.20 PM.png](https://images.zenhubusercontent.com/60a4cfb7dc106bf49dc146ad/ac75f9f4-22df-4bdf-9653-b260af7184b1)

**Comment by sumitsum** [comment]
@AmanAgarwal041 can you please check if what @prapullac has mentioned is valid wrt this issue / PR.

**Comment by prapullac** [comment]
1) The evaluated value popup disappears on movements
