### ISSUE TITLE
[Bug]-[50]:

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#4468]
## Description

In app edit mode if user tries to change the app name, and in doing so removes the complete string- they get an error right away; even if they are not trying to save an empty string. Error should be shown only if user tries to save the empty app name. 

### Steps to reproduce the behavior:
1. Open any app in edit mode
2. Try to edit the app name
3. Remove the complete string
4. On top right you'll see an error toast

### Important Details
 - Version: Cloud

https://user-images.githubusercontent.com/13262095/118106331-1f67ed80-b3fb-11eb-80a3-587e3d84744a.mp4

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 25 |
| Effort (months)  | 0.25 |

**Comment by Nikhil-Nandagopal** [comment]
Closing since this is a consistent experience even on APIs/Queries
