### ISSUE TITLE
[Bug] Datasource form: success toast message on `Test` is not displayed if url is set to 'localhost' 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#4488]
### Steps to reproduce the behaviour:
1. Create postgres / mysql plugin and reach the datasource editor form.
2. Enter URL as 'localhost' (need to have a postgres / MySQL db running on localhost)
3. Fill correct credentials, then click `Test`
4. A toast message is expected but does not appear.

**Comment by somangshu** [comment]
@sumitsum this is not reproducible and shows the error alert/toast message correctly.

Let us know if there are additional steps here. 

@vibhandikyash please attach a screenshot of what you see.

**Comment by somangshu** [comment]
@vibhandikyash Note:

- The issue exists for the success flow and not otherwise
- The environment needs to be able to connect to localhost
- To test the issue we need to set up both client and server via install script

**Comment by sumitsum** [comment]
https://user-images.githubusercontent.com/1757421/119465582-6d68e380-bd61-11eb-805d-b6ac649085a1.mov

**Comment by sumitsum** [comment]
@somangshu If possible, can we prioritize this issue, since it might send a wrong signal to any first time users, that the connection to their db on localhost has failed ?

**Comment by somangshu** [comment]
@ajinkyakulkarni please help us prioritise this!
