### ISSUE TITLE
[Feature] Rename Widgets "Actions" to "Events"

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#4495]
## Summary

This feature aims to rename 'Actions' to 'Events' in the property pane

## Motivation

Events communicate better the intent of that section in the property pane

https://user-images.githubusercontent.com/17744578/118364523-9d3c0e00-b54d-11eb-8f47-c5a629fbda48.mp4

**Comment by hetunandu** [comment]
I think they should be called "event triggers"

**Comment by cokoghenun** [comment]
Nice suggestion, but that may be too lengthy for the property pane or what do you think?

**Comment by cokoghenun** [comment]
...and ideally, event triggers refers to the interaction that starts the process (i.e on mouse over or on click) and not the response to the event

**Comment by yatinappsmith** [comment]
Verification not required
