### ISSUE TITLE
Check for authentication types  (OAuth) that datasources will require

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#4510]

**Comment by sumitsum** [comment]
We seem to have Domain objects in place for OAuth 2.0. Not sure if we want to support OAuth 1.0.

**Comment by sumitsum** [comment]
No changes required from OAuth2.0 perspective, hence closing it. Not addressing OAuth1.0 right now, as discussed on Slack actions-pod channel.
