### ISSUE TITLE
[Feature] Remove Entity Explore Search

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#4520]
## Summary

We need to remove the search from the entity explorer and direct all search to the omnibar

## Motivation

Having a single point of search will help users form a habit faster and make it easier to know where to find help

**Comment by pranavkanade** [comment]
@RakshaKShetty when you close this issue please also close #4370

**Comment by RakshaKShetty** [comment]
We have removed the entity Explore search
