### ISSUE TITLE
[FEATURE] JS for downloading files

### ISSUE THREAD

**Issue by bakerfugu** [appsmithorg/appsmith#453]
## Summary

Add a utility function that can be used in JS that downloads files to the user's file system. 

## Motivation

This feature would be useful for a number of customer support dashboard use cases. For example, a database that stores data for cars could have several images of each car: front, back, sides, interior (stored in base64). I want to email those images to a customer or another member of my team. Ideally, there would be a button with a few lines of JS that downloads each of those images to my computer, so I can then send those images in an email.

## Additional Context

This appears to be what I'm looking for:

http://danml.com/download.html

**Comment by Nikhil-Nandagopal** [comment]
@bakerfugu this feature is now live on https://app.appsmith.com 🎉 
You can download files using {{ download(object | base64, fileName, type(optional)) }}
You can run this through a loop if you want to download multiple files on a single event. Thank you and @hetunandu for your contributions in making appsmith better 😃
