### ISSUE TITLE
[Bug] Error is displayed in property pane and text is showing enabled if we bind currentItem in the visible property of list

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4530]
### Steps to reproduce the behaviour:

1. Drag and drop List widget
2. Observe the default data is populated
3. Open the property pane of any text widget inside the list 
4. In visible property enter {{currentItem.name === "Bulbasur"}} 
5. Observe the error is displayed and the text is in enabled state.
5. Now enter the value which is present ie {{currentItem.name === "Bulbasaur"}}
6. Observe that the error is still present 

Expected result: when text in field is "Bulbasaur"
1. When {{currentItem.name === "Bulbasur"}} is entered in visible property the error message should not come and text field should be in disabled state
2. when {{currentItem.name === "Bulbasaur"}} is entered then error message should not come and the text field should be enabled

### Important Details
 - Env : Prod
 - OS: .MacOSX
 - Browser : chrome
 
<img width="742" alt="Screenshot 2021-05-17 at 4 22 28 PM" src="https://user-images.githubusercontent.com/83569920/118477649-8c95be80-b72c-11eb-855f-b0985640ab8e.png">
<img width="754" alt="Screenshot 2021-05-17 at 4 22 08 PM" src="https://user-images.githubusercontent.com/83569920/118477667-90c1dc00-b72c-11eb-8a20-c4c1a7be2644.png">

**Comment by somangshu** [comment]
the problem here is that we cant refer the `currentItem` in the `visible` property of text. Needs to be checked for other elements as well!

**Comment by jsartisan** [comment]
Merged into release via #4189
