### ISSUE TITLE
[Bug]In property pane, the options on top to close, copy, delete and explore widget related doc section is cropped in the lower resolution devices

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4531]
In property pane, the options on top to close, copy, delete and explore widget related doc section is cropped in the lower resolution devices

Steps to reproduce the behaviour:
1.Go to Widgets Section
2.Drag and drop input Widget
3.Verify the display of floating window

Expected result : the floating window top section should be in focus

Actual result: The floating window header section should not be cropped out of the view
<img width="957" alt="floatingwindow_bug" src="https://user-images.githubusercontent.com/45958978/118477591-77b92b00-b72c-11eb-948c-a03608c5af8d.png">

 - Version: Cloud
 - OS: windows
 - Browser : Chrome
 - Resolution of the laptop: 1920*1080
 - Model number : 14 inch (M409D

**Comment by somangshu** [comment]
@vivekverma2312 can we verify this still exists?

**Comment by vivekverma2312** [comment]
@somangshu This issue still exist and specific to windows. @RakshaKShetty is able to reproduce it in her system.

**Comment by riodeuno** [comment]
We're working on the docked property pane. This will be resolved in that.
