### ISSUE TITLE
Redirect anonymous users on public apps to sign in

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#4533]

**Comment by RakshaKShetty** [comment]
@rishabhsaxena When the user copy paste the URL in the New browser and when the link is shared to the new user then the application redirects to the Login page As of now only for the appsmith user the comment and view icon is displayed 

The other testcase that need to be tested which is pending currently is when the feature is live when the link is shared with the other users does the comment and view icon is displayed once the user login
