### ISSUE TITLE
[Bug] JS in a field not allowing using strings which match the parent entity's name because it creates a cyclical dependency

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#4535]
## Description

When writing javascript function inside a widget field, if using a string value which matches the widget name, cyclical dependency issue is thrown

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Drop Input1 widget on the canvas
2. Add the following javascript to Input1's Text field :
```
{{
    function(){
    const showValue = `Input1`;
    return showValue;
    }();
}}
```

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #5621
