### ISSUE TITLE
[Bug] Different charts are showing when chart widget is dragged in a list and outside a list when chart type condition is set

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4538]
### Steps to reproduce the behaviour:

1. Drag and drop a List widget
2. Drag and drop a button and chart widget
3. In Chart widget property pane enable JS for chart type
4. In Chart type property enter {{Button1.text === "sumit" ? "LINE_CHART" : "BAR_CHART"}}
5. Observe that Bar chart is showing 
6. Now drag and drop the chart widget in list widget container 
7. Observe that the line chart is showing in chart now
8. Now if you change the chart type property to {{Button1.text === "submit" ? "LINE_CHART" : "BAR_CHART"}}
9. Observe that no change is visible in chart 
10. Now drag and drop the chart widget out side the list widget into canvas the chart refresh to correct chart type

### Important Details
 - Environment: Production
 - OS: MacOSX
 - Browser : chrome

https://www.loom.com/share/604cd2d31c6141a19a0c472779525b19

**Comment by jsartisan** [comment]
Merged into release #4189
