### ISSUE TITLE
[Feature] Slash commands in autocomplete

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#4540]
https://www.figma.com/file/YUkuwA7yugQf5eMHvtCez8/JS-Editor-%26-Commands-Menu-Handoff?node-id=1%3A59

**Comment by arunvjn** [comment]
Design doc : [https://www.figma.com/file/YUkuwA7yugQf5eMHvtCez8/JS-Editor-%26-Commands-Menu-Handoff?node-id=1%3A59](url)
