### ISSUE TITLE
[Feature] Support for query params in API datasources

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#4568]
## Summary

Currently user is not able to create a API datasource with query parameters in some special use-cases like 
`{base_uri}/{typeOfEndpoint}?api_key=***&otherParams`
Where typeOfEndpoint => search/translate/trending etc 

## Motivation

There are quite a few platform that structure their apis in the format provided. To support such platforms datasources supporting query params can be useful

## Additional Context
Check API ref for Giphy

**Comment by nidhi-nair** [comment]
A slight deviation for this particular use case. Should we be adding this as an authentication mechanism @mohanarpit?

**Comment by nidhi-nair** [comment]
Closing as resolved.
