### ISSUE TITLE
[Bug]When the User drag and drop the Chart widget->and select the custom chart from chart type->the chart type not supported text is displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4573]
## Description

When the User drag and drop the Chart widget->and select the custom chart from chart type->the "chart type not supported text" is displayed 

1.Go to Widgets Section
2.Drag and drop Chart Widget
3.On the floating window select the chart type as custom chart
4.verify the display of the Message displayed on the chart
<img width="960" alt="Chartwidget" src="https://user-images.githubusercontent.com/45958978/118773295-511d0080-b8a2-11eb-9738-4ead8886af20.png">

expected result: The Message should be changed to please enter chart data in chart data section as we have option to build the custom chart

actual result: The Message is displayed as "chart type not supported" which is not a valid message

### Important Details
 - Version: Cloud 
 - OS: Windows
 - Browser Chrome

**Comment by RakshaKShetty** [comment]
@vibhandikyash The current observation as below
1.Drag and drop the chart widget 
2.select Custom from chart type
3.delete the data from chart data
4. now verify the display of the chart  on canvas again it says "Chart type not supported" but there should be some text saying **"enter data to view the chart"**
![image](https://user-images.githubusercontent.com/45958978/121187801-0fbab800-c886-11eb-91b3-4ec8c949974b.png)

**Comment by somangshu** [comment]
Hey @vivekverma2312 in this fix, Instead of changing the message we have added a default object to the custom chart data which will show a sample config to the user. @prapullac suggested the same today!

Were you able to see the config. How did you reach here?

**Comment by RakshaKShetty** [comment]
Hi @somangshu for the first time when i drag and drop the widget and select the custom chart  the data looks fine. but the issue is when we delete the data added in that chart data section. if this okay then i will close the issue.

**Comment by somangshu** [comment]
@RakshaKShetty this error is the default when the chart data/type is not valid. Hence we added default data to the custom chart config so that the message is not visible by default. 

You can consider this closed if the default data works well according to you.
