### ISSUE TITLE
[Bug]Safari - Unwanted lines are displayed in the Query Editor section when the user expands log response section

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4576]
## Description
Release Environment - Safari - MongoDB - It is observed that connecting mango DB via URI connection and creating new query and expanding log response section unwanted lines are displayed in the query editor

**Expected Result:**
Expanding log response section unwanted lines should not be displayed in the query editor

**Actual Result:**
Expanding log response section unwanted lines are displayed in the query editor

### Steps to reproduce the behaviour:
1. Launch app smith app in the release Environment
2. Click on Database
3. Add new Datasource
4. Select Mongo DB
5. Change the connection as Yes for URI
6. Pass the following url - mongodb+srv://fortest:123testing@mock.0rat3.mongodb.net/heroku_bcmprc4k
7. Click on Save button
8. Click onNew Query

**Video Link:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ac4b524174d74bc99ed6fb3c1ada0e7c-00001.gif)](https://www.loom.com/share/ac4b524174d74bc99ed6fb3c1ada0e7c)

### Important Details
 - Version: [Safari - 14.1 (16611.1.21.161.3)
 - OS: [MacOS big sur 11.3]
 - Browser [Safari]

**Comment by YogeshJayaseelan** [comment]
This issue also happens for the Google Sheet Query editor

**Comment by YogeshJayaseelan** [comment]
We observed this issue in release frozen environment as well

**Comment by Nikhil-Nandagopal** [comment]
@YogeshJayaseelan can you verify that this has been fixed?
