### ISSUE TITLE
[Feature] Widget to scan QR code through device camera

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4577]
## Summary

As a user, I should be able to scan a QR code through the device camera. This QR code can consist of data which can further be connected to an API/Query to fetch entries from any datasource.

## Motivation

If a developer wants to provide ease of access to the end user for accessing data, this feature is very helpful.

## Additional Context

Request from a user who wishes to build a QC app for their logistics chain and wanted such an option to quickly access the SKU details quickly which needs to be QC'ed.

**Comment by billyrudi** [comment]
This is a very useful tool

**Comment by marks0351** [comment]
another user on discord(WSDsuperace) wishes for this widget.

**Comment by WSDsuperace** [comment]
Hi, is there any update on this widget? How high priority does it have? Is it possible to "guesstimate" when it might be available?

**Comment by Nikhil-Nandagopal** [comment]
@WSDsuperace we haven't prioritised this widget yet. We will try to pick it up in the next quarter

**Comment by DeanMann** [comment]
I have a immediate application for this scanning QR and barcodes. Will need to embed app smith in iframe inside Vue app using capacitor to access the camera until then. So I think this would be a very good feature for internal tools covering inventory etc

**Comment by st-trade** [comment]
> I have a immediate application for this scanning QR and barcodes. Will need to embed app smith in iframe inside Vue app using capacitor to access the camera until then. So I think this would be a very good feature for internal tools covering inventory etc

Have a very similar use case.

**Comment by raoul3000** [comment]
Since Covid 19 , QRcodes enter massively in our life . As an entrepreneur , i should be able to build the product my customers want using Appsmith . That is why a native qrcode reader widget would be a great step to ease my work and satisfy my clientele . Thank you

**Comment by raoul3000** [comment]
Hello :-) Qr code reader ? I would say that tooljet have one and to set up and to decode qr code it is so quick and easy . In appsmith have built the dashboard part of my project, the rest in webflow and wized . A qrcode reader is the piece that i miss .

**Comment by ralfwenske** [comment]
I am working on a inventory type app. Webapps with **obvious and fast** interfaces allow use by nearly anybody without much introduction overhead. So to eg. add or remove items - most of which carry EAN and other barcodes - scanning the ID would eliminate typing errors and time! In addition - when creating an entry for a new item - a photo taken and stored in the database would further improve useability by affirming the user visually to handle the right item.
Also think of POS.
For a quick test: [this library](https://github.com/mebjas/html5-qrcode) scans EAN in firefox even on my 2013 i5 macbook.
So a widget which pushes the scanned code into an input field would be **obvious and fast** for the developer also.

**Comment by dilippitchika** [comment]
@chandannkumar @laveena-en PRD can be found here - https://www.notion.so/appsmith/QR-scanner-PRD-29f5a1f703b648acaeee463ab5ff6483

Will update after discussion with @dhruvikn
