### ISSUE TITLE
[Feature] Add app name in the title (on the editor page)

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#4583]
## Summary

We'll need to add the Application Name in the title on the editor page. 

## Motivation

Usually, most of the developer's browsers are filled with lot's of tabs. This makes it difficult to find a particular Appsmith tab when using/building multiple applications at a time. Hence, adding the Application Name in the title tag save time to navigate between tabs on the browser fastly. 

## Additional Context

At present, when we build the app the title says `Editor | Appsmith` this can be modified to `<App Name> | Editor | Appsmith`. Any suggestions for the format are welcome!

Below is a screenshot for reference:

![Screenshot](https://i.imgur.com/2Ig6oqP.jpg)

**Comment by somangshu** [comment]
@Tooluloope get an understanding here first, If you find clarity pick this up, else let me know!
