### ISSUE TITLE
Identify and fix the flaky test cases

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#4585]

**Comment by yatinappsmith** [comment]
Following tests are identified as flaky tests.

Smoke_TestSuite/ClientSideTests/Binding/Bind_InputWidget_Table_Sorting_spec.js
Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_Unique_name_spec.js
Smoke_TestSuite/ClientSideTests/Binding/Bind_API_with_List_Widget_spec.js
Smoke_TestSuite/ClientSideTests/Binding/Bind_TableTextPagination_spec.js
Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js
Smoke_TestSuite/ClientSideTests/GlobalSearch/GlobalSearch_spec.js
Smoke_TestSuite/ClientSideTests/Binding/aTobAndbToaBasictest_spec.js
Smoke_TestSuite/ClientSideTests/Binding/loadashBasictest_spec.js
Smoke_TestSuite/ClientSideTests/Binding/momentBasictest_spec.js
Smoke_TestSuite/ServerSideTests/QueryPane/AddWidget_spec.js
Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js
