### ISSUE TITLE
[Bug] On scrolling the screen after widget drag and drop the property pane shift on top of widget panel

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4594]
### Steps to reproduce the behaviour:
1. Click on Widgets
2. Drag and drop a widget in canvas
3. Observe the property pane is in open state
4. Scroll the screen
5. Observe that the property pane shift on top on widget panel

### Important Details
 - Env: Prod

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/29eac747be244067bf968e2c7a738521-00001.gif)](https://www.loom.com/share/29eac747be244067bf968e2c7a738521)

**Comment by somangshu** [comment]
this is resolved with docked property pane
