### ISSUE TITLE
[Feature] APIs with Self-signed Certs with Appsmith

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4608]
## Summary

Hitting HTTPs APIs with self-signed certificates fails with the following error:

```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

## Motivation

A lot of internal APIs in companies tend to have HTTPs with self-signed certificates and they are currently inaccessible with Appsmith.

Appsmith supports talking to HTTPs with CA-verified certificates and insecure HTTP endpoints as well. APIs with HTTPs on self-signed certs fall somewhere in the middle of these two scenarios and can be a valuable addition to Appsmith.

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni maybe we should allow them to configure this at the API / Datasource level

**Comment by aswathkk** [comment]
Any progress on this issue?
Faced this today while making use of some internal APIs

**Comment by aznj** [comment]
Any update on this issue?

**Comment by noe-charmet** [comment]
Encountering this issue too right now. Would be great to either be able to upload a custom CA certificate, or to disable SSL verification entirely for some datasources

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni can we look into prioritising this?

**Comment by DaiZack** [comment]
Got the same issue for the ElasticSearch connection. Looking forward the update

**Comment by nidhi-nair** [comment]
Hi @DaiZack! This feature is GA already, are you having trouble using it for your use case?
