### ISSUE TITLE
[Bug] Next/previous is clickable on Table pagination after enabling server side pagination from property pane

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4614]
### Steps to reproduce the behaviour:

1. Drag and drop table widget
2. Query a table data with multiple pages 
3. From property pane enable server side pagination
4. Observe that Next/Previous page is still clickable on table

### Important Details
 - Environment : Prod
 - OS: MacOSX
 - Browser chrome

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/89d04b26cae7484fa0870ce5cb995007-00001.gif)](https://www.loom.com/share/89d04b26cae7484fa0870ce5cb995007)

**Comment by somangshu** [comment]
Closing this in favour of #1578 & #2230

**Comment by vivekverma2312** [comment]
Issues still exist thus reopening it.

**Comment by somangshu** [comment]
@vivekverma2312 the pagination is not configured in the above example and the behaviour is appropriate. Once we add the pageSize and offset to the query you will see pagination work better, We also have the total record count now to disable pagination. When its not set the pagination control will remain as it is. The onus here is on the end user

**Comment by vivekverma2312** [comment]
@somangshu When the issue was raised the pageSize and offset to the query options were not available. Now after applying pageSize and offset to the query the infinite scroll do not work. After adding pageSize and offset to the query also the next/previous button button is available. Can you please suggest if we can link the issue to any epic or reopen this?
