### ISSUE TITLE
[BUG] Alias is not supported in mysql query.

### ISSUE THREAD

**Issue by sagargulabani** [appsmithorg/appsmith#462]
## Description

The mysql alias doesn't show up. This is an issue when joining tables having columns with the same name.
https://www.mysqltutorial.org/mysql-alias/

### Steps to reproduce the behaviour:
1. Go to mysql query
2. Type the following query select id as`idname` from guests;
3. The alias doesn't show up

Good items to include here include:
- Console / network logs from your browser

### What you expected to happen
The alias should show up as the name of the column.

### Screenshots
<img width="865" alt="Screenshot 2020-08-28 at 10 55 31 PM" src="https://user-images.githubusercontent.com/7789813/91595695-96e71100-e981-11ea-8368-e0e8f2c04d8c.png">

### Important Details

How are you running appsmith?

SaaS (appsmith.com)

Which browser / OS are you using?
 - OS: MacOSX
 - Browser chrome

**Comment by Nikhil-Nandagopal** [comment]
Thank you for reporting this @sagargulabani . We'll look into this and revert with a fix..

**Comment by Nikhil-Nandagopal** [comment]
@sagargulabani We've merged the fix for this issue in. It should now be working as expected! 😄 
Do let us know if you face any further problems

**Comment by sagargulabani** [comment]
I think this has not yet been merged with app.appsmith.com

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 can you check? It looks like the pr has been merged but @sagargulabani is still facing an issue

**Comment by sharat87** [comment]
Hi @sagargulabani, this issue should now be resolved. Sorry for the back-and-forth on this. Let us know if you face any further problems with this. Thanks!

![Screenshot 2020-09-07 at 10 21 02](https://user-images.githubusercontent.com/120119/92349475-d6d19500-f0f3-11ea-86cd-1d0eb123fb63.png)
