### ISSUE TITLE
[Bug] Error and Log in the API pane remains constant even and carry older execution API data  when user is moved to another  API 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4622]
Steps to reproduce:
1) Add an API 
2) Now run the API 
3) Observe the response is recorded with Status error 
4) Now navigate to another API 
and observe

Observation
It is observed that the Error and Log section does not clear and displays the older API data 

Expectation:
As the user moves to new API like the response body get clear with respect to the API the error and Log must also get cleared and not carry older execution API data

**Comment by Nikhil-Nandagopal** [comment]
@prapullac can you verify if this is still happening?
