### ISSUE TITLE
[Bug]Mongo DB - Error message should be understandable to user 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4623]
## Description
Release - Mongo DB - It is observed that when the user submit invalid query appropriate error message is displayed but the message is too hard to understand. 

**Expected Result:**
Error message should be easily understandable

**Actual Result:**
For invalid query the following error message is displayed - readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is ARRAY. 

### Steps to reproduce the behaviour:

1.Launch appsmith app in the release Environment 
2.Expand Database 
3.Click on Create New Datasource 
4.Select Mongo DB
5. Choose option as with uri and pass the following uri - mongodb+srv://fortest:123testing@mock.0rat3.mongodb.net/heroku_bcmprc4k
6. Click on Save 
7. Click on Add new Query 
8. Choose the Type as - Form Input 
9. Choose Command as 'Delete one or more documents'
10. Pass the following invalid query in the query field - [{ status: "A" }]
11. Click on Run and observe

### Important Details
 - Version: [14.1 (16611.1.21.161.3)]
 - OS: [MacOS Big sur 11.3]
 - Browser [S
<img width="1280" alt="Screenshot 2021-05-21 at 4 26 57 PM" src="https://user-images.githubusercontent.com/35128442/119131652-5c655d00-ba57-11eb-9cbf-9b8c97bb8b58.png">
afari]

**Comment by ajinkyakulkarni** [comment]
This also happens if there is any space or new line in the fields. And when this happens it is very difficult to figure out as a new user why this is happening.    
![image](https://user-images.githubusercontent.com/800578/133059808-9253eada-0b6b-45b3-a717-3d37cdc22f8a.png)
