### ISSUE TITLE
[Bug] Onboarding cards require a 'skip' button

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4628]
## Description
Users are unable to escape from errors in the onboarding flow because there's no skip button. 
https://www.loom.com/share/c1955f4f41084e608a03c344292f3162

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal Can we add a skip button? Saw another user stuck with errors because they can't get out of the onboarding flow.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek actually there is a skip button but it's very subdued on the top right corner. @Debsourabh can you help with this?

**Comment by RakshaKShetty** [comment]
@akash-codemonk end tour is missing in last step of onboarding

**Comment by akash-codemonk** [comment]
@RakshaKShetty Skip is present on the card now
