### ISSUE TITLE
[Bug] Error running appsmith codebase

### ISSUE THREAD

**Issue by duytv14** [appsmithorg/appsmith#4638]
## Cannot resolve symbol in backend
import com.appsmith.external.models.QBaseDomain;
import com.appsmith.server.domains.QApplication;
import com.appsmith.server.domains.QConfig;
import com.appsmith.server.domains.QDatasource;
import com.appsmith.server.domains.QNewAction;
import com.appsmith.server.domains.QOrganization;
import com.appsmith.server.domains.QPlugin;
import com.appsmith.server.domains.QUserData;
import com.appsmith.server.domains.QUser;
import com.appsmith.external.models.QActionConfiguration;
import com.appsmith.server.domains.QAction;
import com.appsmith.server.domains.QLayout;
import com.appsmith.server.domains.QNewPage;
import com.appsmith.server.domains.QOrganization;
import com.appsmith.server.domains.QPage;
import com.appsmith.server.domains.QComment;
import com.appsmith.server.domains.QCommentThread;

![image](https://user-images.githubusercontent.com/39907246/119286407-788f1700-bc6e-11eb-9a18-bcb2b28f0c55.png)

## Cannot start frontend
PS D:\appsmith\app\client> npm start
Debugger attached.

> appsmith@0.1.0 start D:\appsmith\app\client
> BROWSER=none EXTEND_ESLINT=true REACT_APP_ENVIRONMENT=DEVELOPMENT HOST=dev.appsmith.com craco start

'BROWSER' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appsmith@0.1.0 start: `BROWSER=none EXTEND_ESLINT=true REACT_APP_ENVIRONMENT=DEVELOPMENT HOST=dev.appsmith.com craco start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appsmith@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by abhvsn** [comment]
@duytv14 which IDE are you using? If it's IntelliJ can you try invalidating cache once (To resolve backend issue)

<img width="546" alt="Screenshot 2021-05-24 at 11 14 28 AM" src="https://user-images.githubusercontent.com/41686026/119302581-f9a3d980-bc81-11eb-9fd4-8f1db37367df.png">

**Comment by nayan-appsmith** [comment]
@duytv14 you need to use `yarn` instead of `npm` to start the frontend. Please check the [Client setup guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md) 

As described in the doc, please install `yarn` globally first with `npm` and then use the `yarn` command to install the dependencies and run the project.

As you already run the `npm start` command, I suggest you to delete the `node_modules` directory first and then try the command as described in the doc.

**Comment by duytv14** [comment]
> @duytv14 which IDE are you using? If it's IntelliJ can you try invalidating cache once (To resolve backend issue)
> 
> <img alt="Screenshot 2021-05-24 at 11 14 28 AM" width="546" src="https://user-images.githubusercontent.com/41686026/119302581-f9a3d980-bc81-11eb-9fd4-8f1db37367df.png">

Thank @abhvsn 
I tried it but it still won't work :(
In package com.appsmith.server.domains i can't find the class:
    import com.appsmith.server.domains.QApplication;
    import com.appsmith.server.domains.QConfig;
    import com.appsmith.server.domains.QDatasource;
    import com.appsmith.server.domains.QNewAction;
    import com.appsmith.server.domains.QOrganization;
    import com.appsmith.server.domains.QPlugin;

**Comment by abhvsn** [comment]
> > @duytv14 which IDE are you using? If it's IntelliJ can you try invalidating cache once (To resolve backend issue)
> > <img alt="Screenshot 2021-05-24 at 11 14 28 AM" width="546" src="https://user-images.githubusercontent.com/41686026/119302581-f9a3d980-bc81-11eb-9fd4-8f1db37367df.png">
> 
> Thank @abhvsn
> I tried it but it still won't work :(
> In package com.appsmith.server.domains i can't find the class:
> import com.appsmith.server.domains.QApplication;
> import com.appsmith.server.domains.QConfig;
> import com.appsmith.server.domains.QDatasource;
> import com.appsmith.server.domains.QNewAction;
> import com.appsmith.server.domains.QOrganization;
> import com.appsmith.server.domains.QPlugin;

Yeah the classes that look like QDomainModel are actually generated classes with field names as strings. You have to build the project with Maven once for them to be generated. IntelliJ doesn’t do that code generation for some reason. Use the build.sh to build with Maven and you should have those classes after that.

**Comment by jk2K** [comment]
Don't forget to run ``./build.sh -Dmaven.test.skip=true``

**Comment by Nikhil-Nandagopal** [comment]
@duytv14 I'm going ahead and closing this issue. Feel free to reopen it if you're still facing this

**Comment by anksingh-zuora** [comment]
@Nikhil-Nandagopal  Sometimes this gets stuck, everything was working fine and the build started failing.
i am building from terminal.
The Qclasses are not getting generated, even mvn clean compile fails.
<img width="842" alt="image" src="https://github.com/appsmithorg/appsmith/assets/163037416/8f7716d9-d657-4d81-8ccc-08fd94aa6283">

**Comment by Nikhil-Nandagopal** [comment]
@anksingh-zuora you can get some help regarding this on our discord server. We'll need to debug the issue with details around your setup https://discord.gg/ejTqpNF2
