### ISSUE TITLE
[Bug] Table widget action - Error in evaluation trigger - Function statements require a function name

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4647]
## Description

In the table widget action, the following snippet does not work:

```
{{ function(){
...
}()
}} 

```

The workaround to this is:

```
{{ (function(){
...
})()
}} 
```

### Steps to reproduce the behaviour:
1. Drag and drop and table widget
2. Change column type to `button`
3. Add an IIFE like above
4. See an error: `Error occurred while evaluating trigger: Function statements require a function name`

### Important Details
 - Version: Cloud / Self-Hosted vx.x
 - Browser - chrome, safari

** reported by discord user

**Comment by somangshu** [comment]
@riodeuno will we require some help from the actions pod here?

**Comment by somangshu** [comment]
@riodeuno @vibhandikyash we need to triage this issue and move towards resolution here, Kindly look into this

**Comment by somangshu** [comment]
@riodeuno need help triaging this

**Comment by Nikhil-Nandagopal** [comment]
@somangshu I think this has now been fixed

**Comment by Nikhil-Nandagopal** [comment]
My mistake I didn't realise this was a table specific problem

**Comment by riodeuno** [comment]
@somangshu Let me triage this and get back to this thread.

**Comment by somangshu** [comment]
@sbalaji1192 kindly triage and reassign

**Comment by sbalaji1192** [comment]
@somangshu This is a javascript behavior. you need to convert the function into an expression by enclosing it in a bracket to execute it immediately. (you can also prefix the function with + or - to make it an expression).
https://www.loom.com/share/a33cadbdda544588a9b8417f0a8cc151
