### ISSUE TITLE
Enhancement - Mongo DB - Mandatory fields should be marked with *

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4652]
## Summary
Release Environment - Mongo DB - Mandatory fields needs to be highlighted with * 

## Motivation

For the update statement user focus will be mainly on the 'Update Syntax' and they might forget to fill other fields.
<img width="1280" alt="Screenshot 2021-05-24 at 5 36 01 PM" src="https://user-images.githubusercontent.com/35128442/119345853-10185800-bcb7-11eb-85b2-615d2d555ab6.png">

**Comment by trishaanand** [comment]
This requires changes in the Label strings. To make this change, please head to `mongoPlugin/src/main/resources/editor/`. This folder contains the UI configuration for all the query types.
