### ISSUE TITLE
[Bug]Mongo DB - Incorrect key passed in the update query are showing as updated 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4654]
## Description
Release Environment - Mongo DB - Form Input - It is observed that when the user passed incorrect key in the update query the incorrect key is updated to an existing query.

**Expected Result:**
Incorrect key should not be accepted appropriate error message should be displayed (Key no matching)

**Actual Result:**
Incorrect key passed in the update query are showing as updated

### Steps to reproduce the behaviour:
1. Launch appsmith app in the release environment 
2. Expand DB and click on create new DataSource 
3. Choose DB as Mongo Plugin 
4. Choose option as with uri and pass the following uri - mongodb+srv://fortest:123testing@mock.0rat3.mongodb.net/heroku_bcmprc4k
5.Click on Create new Query 
6.Choose the type as Form input 
7. choose the command as 'Insert a document'
8. Enter collection name in the insert query enter the following query 
 {
      "documents": [ 
            { "_id": 1, "user": "Appsmith", status: "Active" } 
      ]
   }
9.Click on run and ensure document is inserted successfully 
10.Now, choose the command as 'Update Document'
11.Enter the same collection name used for insert 
12.Enter the following value in query field - {}
13.Enter the following query in the update query field 
{ "$set": { "Reason": "active" }}
14.Click on run and observe

### Important Details
 - Version: [14.1 (16611.1.21.161.3)]
 - OS: [MacOS big sur 11.3]
 - Browser [Safari]

**Comment by ajinkyakulkarni** [comment]
@nidhi-nair @arunvjn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4654?planning-poker)

**Comment by nidhi-nair** [comment]
I'm not sure we want to fix this? Isn't this expected behaviour from a NoSQL database @mohanarpit ?
