### ISSUE TITLE
[Bug]Mongo DB - Key values are not Case Sensitive 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4655]
## Description
Release Environment - Mongo DB - It is observed that when the user tries to change the key value of status(small letter during insert) and in the update statement instead of status if the user passes Status(S caps) then new key and value gets updated to the document.

Expected Result:
Key name should be case sensitive

Actual result:
Key value are not-case sensitive 

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Launch appsmith app in the release environment
Expand DB and click on create new DataSource
Choose DB as Mongo Plugin
Choose option as with uri and pass the following uri - mongodb+srv://fortest:123testing@mock.0rat3.mongodb.net/heroku_bcmprc4k
5.Click on Create new Query
6.Choose the type as Form input
choose the command as 'Insert a document'
Enter collection name in the insert query enter the following query
{
"documents": [
{ "_id": 1, "user": "Appsmith", status: "Active" }
]
}
9.Click on run and ensure document is inserted successfully
10.Now, choose the command as 'Update Document'
11.Enter the same collection name used for insert
12.Enter the following value in query field - {}
13.Enter the following query in the update query field
{ "$set": { "Status": "A" }}
14.Click on run and observe

### Important Details
 - Version: [14.1 (16611.1.21.161.3)]
 - OS: [MacOS Big sur 11.3]
 - Browser [Safari]

**Comment by ajinkyakulkarni** [comment]
@nidhi-nair @arunvjn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4655?planning-poker)

**Comment by nidhi-nair** [comment]
Similar to #4654, this is expected behaviour from a NoSQL database. Closing till there is a difference in opinion.
