### ISSUE TITLE
[Bug]In error tab When there is error to display then the text message should be " No Error to Display

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4661]
## Description
In error tab When there is error to display then the text message should be " No Error to Display
[What happened]

### Steps to reproduce the behaviour:

1.Click on + icon from DB queries 
2.Select any one added data source
3.Click on Add new query
4.Click on Error tab
5.Verify the display

expected result:
In error tab When there is error to display then the text message should be " No Error to Display
Actual Result:
In error tab When there is error to display then the text message is displayed as "No logs to show"
![image](https://user-images.githubusercontent.com/45958978/119434564-14d02100-bd36-11eb-8d2f-c5590d36fb5d.png)

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser: Chrome

**Comment by UdattaChowdhury** [comment]
Would like to work on this issue. Can you please assign this to me?

**Comment by Nikhil-Nandagopal** [comment]
@UdattaChowdhury go for it!

**Comment by UdattaChowdhury** [comment]
Where exactly can I find this issue in the codebase. Actually, I am a beginner.

**Comment by akash-codemonk** [comment]
Hey @UdattaChowdhury the change to be made is at https://github.com/appsmithorg/appsmith/blob/b75dcc384dda5a82de26c0be6f5c74097b19535c/app/client/src/components/editorComponents/Debugger/helpers.tsx#L39. 

We could pass the text to be shown as a prop to the blank state component based on the tab.

**Comment by UdattaChowdhury** [comment]
So, basically in this line, I need to use props. Right?
