### ISSUE TITLE
[Bug]In Logs Tab->The drop to select and view the logs as per the status is too white and difficult to make out that it’s a dropdown

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4662]
## Description

]In Logs Tab->The drop to select and view the logs as per the status is too white and difficult to make out that it’s a dropdown
[What happened]

### Steps to reproduce the behaviour:

1.Click on + icon from DB queries 
2.Select any one added data source
3.Click on Add new query
4.Click on Logs tab
5.Verify the display of All Dropdown

expected result:
In Logs Tab->The drop to select and view the logs as per the status should be bit highlighted same has a filter so it will be easy for user 
Actual Result:
In Logs Tab->The drop to select and view the logs as per the status is too white and difficult to make out that it’s a dropdown
![image](https://user-images.githubusercontent.com/45958978/119434949-d9822200-bd36-11eb-99a5-22e52cba0f12.png)

### Important Details
 - Version: Cloud
 - OS: Windows
 - Browser: Chrome

**Comment by UdattaChowdhury** [comment]
I would like to work on this issue, can you assign me.

**Comment by UdattaChowdhury** [comment]
Actually, I am a beginner at open source. Can you tell me in which folder can I find this issue?

**Comment by RakshaKShetty** [comment]
@UdattaChowdhury i have assigned defect to you, its a design issue you can start working once i share design with you

**Comment by UdattaChowdhury** [comment]
Sure, got it.

**Comment by RakshaKShetty** [comment]
Hi @UdattaChowdhury  we have finalized the design use can check the design in the link https://www.figma.com/file/i6Dy8zT5WJbq37MusZ2DgZ/?node-id=29%3A34 can start working on it

**Comment by UdattaChowdhury** [comment]
Sure.

**Comment by somangshu** [comment]
Hi @pcastro3, Assigning this to you. Please let us know here if you need any help.

**Comment by pcastro3** [comment]
Hey @somangshu, I'm having a bit of trouble trying to run the client's codebase so that I can see the changes I make on the browser. I haven't done this before, and I can't seem to get things to execute. When I try to run the command `cp .env.example .env` it says the file or directory doesn't exist. I tried to run these commands through my git bash, and there doesn't seem to be specific instructions for Windows OS. 

Am I supposed to run these commands through Linux? If so, how do I do that?

**Comment by somangshu** [comment]
Hey @pcastro3, I understand you might have gotten confused somewhere with the docs. If you are trying to run the local environment on a windows machine, You could WSL2 for which we have even upgraded our documentation just a couple of days ago. Find them [here](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#windows-wsl2-setup). You can also point the client side to use our release server [like this](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#if-you-would-like-to-hit-a-different-appsmith-server).

Please get in touch with us on our [Discord server](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#if-you-would-like-to-hit-a-different-appsmith-server) to get more help in detail. You can also DM me there to make the conversation faster. 

We also have our [community forum](https://community.appsmith.com/) now, Feel free to drop a question here if required, We respond to that well.

**Comment by EkaterinaMozheiko** [comment]
Hey @somangshu, I'd like to work on this issue. Is Figma link actual?

**Comment by somangshu** [comment]
Hey @EkaterinaMozheiko, Thanks for showing interest. I am not sure if this issue is still open. @hiteshjoshi can you kindly confirm that and assign this. 

Also @EkaterinaMozheiko just a small tip, Searching issues under the hactoberfest label will give you better issues to work on

**Comment by Nikhil-Nandagopal** [comment]
Hi, this will no longer be valid with our new release as such we're closing this issue :)
