### ISSUE TITLE
[Bug] Installation script fails when Curl not available in Ubuntu in some cases

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4664]
## Description

When curl is not installed, the install script fails to continue. Since it already installs docker if it's not available, we should do the same thing for installing curl if it's not available as well.

### Important Details
 - OS: Ubuntu

**Comment by erganeshsharma** [comment]
@sharat87 @Pranay105 @Nikhil-Nandagopal can I pick this issue?

**Comment by sharat87** [comment]
@erganeshsharma, thank you for your interest in this. Unfortunately, this is a stale issue that's talking about the installation script, that was removed several months ago, and isn't supported anymore. I encourage you to review the list of Good First Issues, and pick a more recent one.

Thanks again! 🍻
