### ISSUE TITLE
[Bug] Custom error callback in action does not suppress default action error alert

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#4669]
A user on discord wanted to show a error message that he is getting from the api on failure. I can write the following function that can do this:

`{{MyApi1.run(
	(response) => {},
	(response) => {
	showAlert(response.errors.message)
	}
)}}`

But when I do so, we still get `MyApi1 failed to execute. Please check its configuration` along with a second alert written in the query.

![Screenshot_9](https://user-images.githubusercontent.com/6636360/119479385-33eaa500-bd6e-11eb-8ebb-d408d999302a.png)

Should we suppress these errors in view mode if the user has written a custom error callback for action?

**Comment by ajinkyakulkarni** [comment]
@ApekshaBhosale @vnodecg Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4669?planning-poker)
