### ISSUE TITLE
[Bug] Clicking on the image in Table widget takes the user to the URL of the image

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#4676]
## Description
A user on discord reported this bug. He felt this is an unintended behaviour. The image in the table widget takes the user to the URL of the image.

### Steps to reproduce the behaviour:

1. Drag and drop table widget
2. Change column type to `image`
3. Click on the image displayed in the table widget
4. A new tab is opened with the image URL

### Important Details
 - Version: [Cloud]
 - OS: [MacOSX]
 - Browser [chrome, safari]
 - Environment - [Production]

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal @somangshu @areyabhishek Should we have a toggle like "Open image in new tab on click" instead of forcing this action on the user?

Also, for the normal image widget, we should have this toggle too instead of the pinch zoom feature.

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan both use cases seem plausible. Can we simply. allow the user to set the onClick of the image the way we do in the image widget?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal does `onClick` really make sense on the image widget, specially in case of the table widget. 

I feel the use case @jsartisan is pointing out is that the user would want to view a zoomed image and the way it happens today is not user friendly. A better way would be to either open the image in a bigger modal or open the full size image in a new tab. This functionality can be archived by a toggle value.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu what if the user wants to trigger a modal where a user can change the image using a file picker?

**Comment by somangshu** [comment]
@riodeuno @areyabhishek need you help here to understand to the right way to move forward.

**Comment by areyabhishek** [comment]
@somangshu @Nikhil-Nandagopal We always get requests for flexibility from our users. So Nikhil's point about onClick makes sense even though it might seem unnecessary. I'm sure someone will use it and appreciate the option to either see the image in a modal, or edit the image in a modal or even click to open the image in a container beside the table.

**Comment by somangshu** [comment]
@areyabhishek got it.

Note:
- We will go ahead and add an `onClick` action inside the table column type `image`

@Nikhil-Nandagopal Please let me know if you think this should be taken up differently!
