### ISSUE TITLE
[Bug] How can we use the text from RTE widget without the HTML tags

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#4682]
## Describe the problem

While using the text from the `RTE` widget, on Gmail/Gsheets it's adding the HTML tags. Is there a hack to not add these HTML tags? Here's a screenshot post by one of our community members:

![](https://i.imgur.com/GeDxP4T.png)

Not sure if this a bug, or if it can be solved using JS. Might need to update documentation regarding the same.

**Comment by Nikhil-Nandagopal** [comment]
@vihar the response from RTE has to be HTML because that is how the RTE styles it. What is the user looking to do?
AFAIK text that is styled must be in either markdown or rich text. Other wise, they can simply use a multi line input

**Comment by vihar** [comment]
@Nikhil-Nandagopal, this was one of the questions that was raised on Discord. The user is trying to post data to Gmail API and using the `text` from `RTE` to the Mail body. But is there a hack to use RTE for this? 


Also, the user tried copying the RichTextEditor.text to the clipboard first, so he could just manually paste in the HTML once the email opens. 

```
{{copyToClipboard(RichTextEditor1.text);navigateTo("https://mail.google.com/mail/u/0/",{fs:1,to:tbl_getOrders.selectedRow.email,su:"Order is Ready",bcc:"someone.else@example.com",tf:"cm",body:encodeURI(RichTextEditor1.text)},"NEW_WINDOW")}}
```

Even this didn't work.

**Comment by Nikhil-Nandagopal** [comment]
@vihar something like this might work
https://stackoverflow.com/questions/2583928/prefilling-gmail-compose-screen-with-html-text
