### ISSUE TITLE
[Bug] Objects returned in widgets property bindings get escaped

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#4688]
## Description
JSON smart substitution is only happening on actions today. We should enable this feature for widget properties that expect a JSON or object/array structure

### Steps to reproduce the behaviour:
1. Drop a chart widget
2. Add this in the series data field 
```
[
{{
  {
    "x": "Mon",
    "y": 10000
  }
}}
]
```
3. The evaluated value is a string with escaped quotes and not an object

**Comment by vivekverma2312** [comment]
Working fine and good to go on prod.
