### ISSUE TITLE
Cyclic dependency not shown for API 

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#4694]
## Description

Cyclic dependency error is NOT thrown when on API url path same API is referred

### Steps to reproduce the behaviour:
1. Go to any application
2. Click on api
3. Create new api (Api1)
4. add url path as https://google.com/{{Api1.isLoading}}

![image](https://user-images.githubusercontent.com/7846888/119671762-a6837f80-be57-11eb-9b72-753ca0fe6d94.png)

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [e.g.MacOSX]

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale this need not be a cyclic dependency because it's not referencing to a value that references back to the API URL.
