### ISSUE TITLE
[Bug] Chart widget - Custom Charts - onDataPointClick does not work

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4695]
## Description
The `onDataPointClick` does not work in case of a custom chart, whereas it works for all other chart types types.

### Steps to reproduce the behaviour:

1. Drag and drop chart widget
2. Select custom chart under the chart types
3. Add chart data (follow the guide added under appsmith docs)
4. add `onDataPointClick` action
5. Click on a data point
6. nothing happens

When compared to other chart types, we see that the action given in `onDataPointClick` completes

https://user-images.githubusercontent.com/11089579/119675687-e26c1400-be5a-11eb-87fd-fc0a12620f1a.mov

### Important Details
 - Version: [Cloud / Self-Hosted]
 - OS: [MacOSX]
 - Browser [chrome]
 - Environment - production

**Comment by Nikhil-Nandagopal** [comment]
Re-opening as this still doesn't work in view mode. Seems to be working in edit mode.

**Comment by somangshu** [comment]
@vivekverma2312 can you confirm this?

**Comment by vivekverma2312** [comment]
@somangshu For me it's working on view mode but not working on edit mode.
