### ISSUE TITLE
[Bug] Custom chart data helper is not appropriate

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4696]
## Description

Today the helper given in the custom chart data is not useful for the user. This rather needs to point to the [custom chart documentation](https://docs.appsmith.com/widget-reference/chart#custom-chart) under Appsmith docs

### Important Details
 - Version: [Cloud / Self-Hosted vx.x]
 - OS: [MacOSX]
 - Browser [chrome]
 - environment: production

**Comment by somangshu** [comment]
The link to the docs from error should be available.

**Comment by techbhavin** [comment]
link is updated in the UI building project in [PR#4835](https://github.com/appsmithorg/appsmith/pull/4835)

**Comment by somangshu** [comment]
@Nikhil-Nandagopal how can the same documentation be added from the debugger?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu if the errors are added to the documentation, they will automatically show up in the debugger
https://docs.appsmith.com/troubleshooting-guide/widget-errors
