### ISSUE TITLE
[BUG] DB queries aren't running on page load.

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#470]
## Description
I set a query to run on page load, but it doesn't run

See the public URL of the app here: https://app.appsmith.com/applications/5f3641d380ca1f6faaed4f64/pages/5f3641d380ca1f6faaed4f6f

### Screenshots
[](url)
### Important Details

How are you running appsmith?

SaaS (appsmith.com)

Which browser / OS are you using?
-MacOS
- Chrome

**Comment by trishaanand** [comment]
My first observation is that the action 'fetchConfigs' permissions have been overwritten somehow and right now only 'nikhil@appsmith.com' now has permissions to read/write/execute. This is the case even though the application and the pages have permissions for public as well as a few other users.

**Comment by Nikhil-Nandagopal** [comment]
Closing this issue as we've detected it was a data migration issue
