### ISSUE TITLE
[Bug] Error occurred while evaluating trigger: Unexpected token ')' date in form

### ISSUE THREAD

**Issue by ChristopherMarais** [appsmithorg/appsmith#4700]
## Description

This happened whenever I have a form that I want to submit to insert an entry into a mysql database. It is whenever I have a date picker widget in the form.

**Comment by Nikhil-Nandagopal** [comment]
Hi @ChristopherMarais , could you share the evaluated value of your query or a screenshot of the query with the field in focus?

**Comment by ChristopherMarais** [comment]
So I just rebuilt the form in the exact same way and it worked.
*Christopher Marais*

MIT Big Data Science *|* University of Pretoria *|* Centre for
Bioinformatics and Computational Biology *| *Forest Molecular Genetics
(FMG) *| *Forestry and Agricultural Biotechnology Institute (FABI:
https://www.fabinet.up.ac.za/index.php/people-profile?profile=1465 ) *|* South
African Sustainable Development Goal Hub (SASDG Hub:
http://sasdghub.org/people/) *|* LinkedIn:
https://www.linkedin.com/in/christopher-marais/ *|* Mobile: +27-76-3439-444

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
21/05/27,
08:21:01

**Comment by Nikhil-Nandagopal** [comment]
Thanks for the update @ChristopherMarais let us know if you face any other trouble!

**Comment by Nikhil-Nandagopal** [comment]
@colomboipl could you add nikhil@appsmith.com to your application. I can help debug this
