### ISSUE TITLE
[Bug] After installation through install.sh, restarting the VM stops app working 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#4705]
## Description

User followed installation guide to install the app on VM and successfully deployed it, but after VM restart app stopped working
 
### Steps to reproduce the behaviour:
1. Install app on VM through install.sh
2. Restart the VM instance  

### Important Details
 - Version: Self-Hosted : Oracle cloud
 - OS: Ubantu 20

**Comment by sharat87** [comment]
This is expected behaviour. The Appsmith instance doesn't come up automatically on restart of the machine. Instead, we have to go to the installation directory and do a `docker-compose up -d` to bring it up. That command may need a `sudo` at the start, depending on your operating system.

@abhvsn Can we add this the docs and then close this issue perhaps? Thanks!

**Comment by abhvsn** [comment]
@vihar if we have made the changes in docs can we close this?

**Comment by abulka** [comment]
Surely there is a way to auto start AppSmith when the VM boots up? Making a sysadmin log in manually and doing a `docker-compose up -d` is not a good solution. 

There seem be to be [two schools of thought](https://stackoverflow.com/questions/43671482/how-to-run-docker-compose-up-d-at-system-start-up) re starting up docker containers automatically on boot. One is to use external tools like cron/systemctl, the other to use a docker restart policy. 

I tried adding `restart: always` to the `docker-compose.yml` for the `nginx` service but that didn't work.
So I tried adding `restart: always` to all the services in the `docker-compose.yml` and that did work!  

Perhaps there is a better way of doing this, but shouldn't this be documented? Everybody that self hosts will probably want to do this.

**Comment by sharat87** [comment]
Hey @abulka, thank you for sharing. I just created PR #6428 with this change. 🎉

**Comment by abulka** [comment]
@sharat87 cool! By the way, I'm not an expert at Docker, so hopefully the solution I found is 'best practice'!

**Comment by sharat87** [comment]
@abulka, I would think it _is_. Considering that Docker documentation states that the containers can be manually stopped, and that won't trigger a autostart, it should be fine.

Also, being an expert is overrated. 😉
