### ISSUE TITLE
Create setting tab

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#4715]
- Create a setting tab for function
- Run onPageLoad setting needs a dropdown to select which function should run when there are multiple functions in the JS class
- Add support for testing parameter data needed by the function  - add a new tab (like AWS Lambda)
    - Add Test (Run) button with parameters, add logic for executing functions

**Comment by hetunandu** [comment]
Test function (with parameters) needs design and should not be part of the settings tab

**Comment by ApekshaBhosale** [comment]
close this as design as design has been changed
