### ISSUE TITLE
[Bug] Clicking on  "Debug" button does not lead the user to Error pane

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4718]
Steps to reproduce:
1) Add an API
2) Add inappropriate data in the body 
3) Click on the Body 
4) click on Debugger

or 
1. Add Table widget
2. open debugger
3. click on logs pane
4. add inappropriate data in tabelData 
5. Click on debug button in evaluated popup
6. it stays on logs tab

Observation:
It is observed that the clicking on "Debug" button does not lead the user to the Error pane rather than staying on the opened pane

Expectation:
When there is an error displayed like on canvas the user must be navigated to Error pane and not stay on the response apne

**Comment by RakshaKShetty** [comment]
The first scenario works the second scenario is not valid as per the new changes
