### ISSUE TITLE
Create JS function plugin type in action

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#4727]

**Comment by nidhi-nair** [comment]
This issue will require the following changes:
1. New plugin for JS functions
2. Field in action configuration to store list of test values

**Comment by hetunandu** [comment]
JS action entity actionConfiguration should have the following properties:
- body: `string`, the raw js class file written by the user
- constants: `List<{ name: string, body: string }>`, user-defined constants in the class file
- functions: `List<name: string, body: string, arguments: List<string>, testArguments: List<string>>`, user-defined functions in the class file

All these properties need to be available in the view-mode as well.

**Comment by nidhi-nair** [comment]
Fixed in #4861
