### ISSUE TITLE
JS Actions functionality for onPageLoad

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#4729]
- Only async js function actions need onPageLoad checks
- Actions referenced in sync JS functions need to be set onPageLoad

**Comment by nidhi-nair** [comment]
@hetunandu How does the requirement for this issue change now that we are creating classes instead of functions? I'd assume a single class can have both sync and async functions, which means a single action could have both as well. Has there been any discussion on this so far?

**Comment by sumitsum** [comment]
This issue is no longer valid as changes have been overwritten as part of JS editor epic.

**Comment by prapullac** [comment]
As per above comment we can close the issue
