### ISSUE TITLE
[Enhancement] Spacing between the API must be trimmed

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4732]
Steps to reproduced:
1) Navigate to API pane 
2) Add an API 
3) Click "Enter" to create a space in the API 
4) Click on RUN
and observe

Observation:
Clicking on "Enter" or creating a space would lead the user to an illegal error

Expectation:
Space must be trimmed so that the user is not lead to an error

Video:
https://www.loom.com/share/b6853ec008bc474aaa10ce2a7265f949

**Comment by hetunandu** [comment]
I don't think this is a valid use case to solve for @Nikhil-Nandagopal @mohanarpit thoughts?

**Comment by Nikhil-Nandagopal** [comment]
We shouldn't even allow enter in the URL right?

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal 
We need to allow it for new line characters in between bindings. When focusing out, we show it as a single line input and when focused we show the multi line input

**Comment by Nikhil-Nandagopal** [comment]
Then this seems invalid. Closing it
