### ISSUE TITLE
[Bug] The date and time format does not get updated on the binding to a widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4746]
Steps to reproduce:
1) Add a Date Picker
2) Add a text widget
3) Bind the widgets
4) Change the format of the date widget
5) Observe the format does not get applied on the Text widget even selecting a date on the widget
6) Select the option “Today” on the date picker
7)Observe the Text widget binding
8) the time and date does not get updated to the exact date and time

Observation
1) Format selected on the date picker is not displayed on the text widget
2) Even after clicking on "Today " button only the date picker gets updated however the Text widget goes one day behind and time is not displayed appropriately 

Video:
https://www.loom.com/share/37555c20ba184cd79d66816e3277daaa

**Comment by Nikhil-Nandagopal** [comment]
@prapullac the selectedDate will always be in ISO format. The formatted date field will be in the format of the date picker
