### ISSUE TITLE
[Bug] Error if I change background/text colour in Rich editor and click on submit

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4754]
## Description: If I change the background colour or text colour in "Rich editor widget" then I am getting error on clicking submit.

Application for debug: [Retrospective App](https://app.appsmith.com/applications/60af658e7bf92558fd17f1f1/pages/60af658e7bf92558fd17f1f3)

### Steps to reproduce the behaviour:
1. Drag and drop few Rich Text Editor widget
2. Drag and drop a button widget
3. Purpose is to create a form with rich text editor
4. If I change the background/text colour in text editor and click on submit then error is displayed.

Important Details: The string is changing to -> `Please mention <span style="background-color: #f1c40f;">all the points whi</span>ch you think went well during the sprint.` The quotes are causing the problem.

- OS: MacOSX
- Browser: chrome
- Environment: production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/094bab31bcb443978687c10d878d27d4-00001.gif)](https://www.loom.com/share/094bab31bcb443978687c10d878d27d4)

**Comment by AsianCat54x** [comment]
Hey, Can I work on this issue?

**Comment by somangshu** [comment]
@AsianCat54x this issue is more involved, we still need to understand what is happening underneath. Please look at the other issues to work on

**Comment by nidhi-nair** [comment]
This issue isn't there when BSON smart substitution is turned on. That is expected because smart substitution handles escaping of characters. Closing as a non-issue.
