### ISSUE TITLE
[Feature] Add table column header name for reference while adding a binding in API & DB query

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#4757]
## Summary

Currently while binding the API params/DB query params we are using the table column field names and not the header names which is visible to user. This is creating confusion as user might alter the column header which is relevant to the data and try to bind with the header name. _(User reported this when OP was trying to add customColumn in a table)_

## Additional Context

<img width="966" alt="Screenshot 2021-05-28 at 11 27 37 AM" src="https://user-images.githubusercontent.com/41686026/119937067-c629bd80-bfa7-11eb-8347-25a839e7a825.png">

<img width="463" alt="Screenshot 2021-05-28 at 9 40 45 AM" src="https://user-images.githubusercontent.com/41686026/119936742-469bee80-bfa7-11eb-86ae-b023a0fa265c.png">

**Comment by somangshu** [comment]
Changing ref `customColumn` to `newHeaderName` without spaces and special character will solve the problem. We should make sure that column settings should not be lost when changing this. Also any errors with the old binding should be pointed out.

**Comment by somangshu** [comment]
@riodeuno need some help here, If we do the above, How will the old references work? Can you check if we are talking up the right approch

**Comment by riodeuno** [comment]
One approach suggested by @areyabhishek Is to use `_` separated column names internally, while replacing `_` with spaces when displaying in the column headers.

**Comment by somangshu** [comment]
Would we do the same for the old apps? It might break them.

**Comment by somangshu** [comment]
@sbalaji1192 @ashit-rath need next steps on this, Is this already resolved in V2? We should close it in that case

**Comment by sbalaji1192** [comment]
@somangshu @ashit-rath This is not resolved in the Table widget v2. Do we want to expose the column names in the selectedRow object instead of column id?. if we do then we can update the autocomplete system to use the square bracket notion when it encounters special characters in the key.

**Comment by somangshu** [comment]
I am not sure if that is desirable anymore. @dilippitchika can you get us some metrics here?

**Comment by sbalaji1192** [comment]
@ashit-rath With the current implementation of the Table widget, we use the column names as given in the table Data. puny code generated key is only used for the ID purpose.

**Comment by dilippitchika** [comment]
Linking to #17142, will discuss next week with the team

**Comment by dilippitchika** [comment]
This issue is fixed with #17142
