### ISSUE TITLE
Show something in the home page when user have no organization

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#4759]
When issue #4572 will be done, users will have option to leave an organization. Users can leave all of the current organizations. When this happens, the home page will be empty with a search bar to search application. See the attachment to get an idea of how it looks like now.![Screenshot 2021-05-27 at 7.34.39 PM.png](https://images.zenhubusercontent.com/60895f8ab5b6d976f672b095/4089d046-fdb1-401e-95f1-09fca4c5539b)

A new home page should be designed for this state. It may contain some messages to guide users about the state and where to go from here.

**Comment by Nikhil-Nandagopal** [comment]
Not valid since users cannot leave their own personal organization and a very edge case so closing it till someone complains
