### ISSUE TITLE
[Bug] On hover, long entity name should show a popover with full name.

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#4764]
Currently, there is no way to see the full entity name of a very long name in entity explorer. A popover that displays the full entity name on hover would be ideal.

<img width="312" alt="Screenshot 2021-05-28 at 2 23 13 PM" src="https://user-images.githubusercontent.com/6636360/119958270-815e5080-bfc0-11eb-81e0-0fc72e924899.png">

**Comment by pranavkanade** [comment]
has been fixed
