### ISSUE TITLE
[Bug] Error message is displayed on empty default field of date picker widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4765]
Steps to reproduce:
1) Add a date picker
2) Click on the Property pane 
3) Remove the Default date value 
and observe

Observation: 
It is observed that the error message is displayed to the user 

Expectation: 
It is expected that an error message must not be displayed to the user and allowed to set empty
![Screenshot 2021-05-28 at 2 17 56 PM](https://user-images.githubusercontent.com/71753653/119958146-6095fb00-bfc0-11eb-9604-7ff42482040a.png)

**Comment by areyabhishek** [comment]
Closing this because this is fixed now
