### ISSUE TITLE
[Bug] The onSelectedRow actions are not triggered when a table selects the default selection

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4771]
App link: https://app.appsmith.com/applications/60b0ca5f7bf92558fd17f577/pages/60b0ca5f7bf92558fd17f579

1. Select any entry in the table.
2. Notice that the corresponding selected row's data is shown below the table.
3. Now search using the input at the top for something has a single result, like `tuna`.
4. Notice that the text below the table doesn't show the Tuna product's details, although that's the selected one. We also can't un-select and re-select it to get the data to show.

Let me know if you need an invitation to the app to see it in edit mode.

### Important Details

- Version: Cloud
- OS: macOS
- Browser: Firefox
- Environment: <https://app.appsmith.com>

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 you should actually call the API onSearch again. This will become easier with #4490 but it's intentional because implicit change in data does not trigger actions today. Only user interaction does
