### ISSUE TITLE
[Bug] Old tables not paginating after Appsmupdateith due to pageSize miscalculation

### ISSUE THREAD

**Issue by zdb999** [appsmithorg/appsmith#4782]
## Description

After updating to the most recent version of Appsmith, some of my tables existing with client side pagination stopped paginating properly. The query works correctly, and the hidden rows are there, and you can surface them by filtering the table, but the pagination buttons are disabled. Deleting and recreating the exact same table restored the pagination functionality.

This issue did not occur in all tables, and I haven't been able to pinpoint why it happened in some and not others.

### Steps to reproduce the behaviour:

1. Have an old table from a previous version of Appsmith (about two weeks ago)/
2. Update Appsmith to the latest version.
3. Add some more data, and try to paginate through the results.
4. Create a new table with the exact same data source. See that pagination is possible with the new table, but not the old.

### Important Details

- Version: Self hosted Docker
- Browser: Firefox
- Environment: Both in the editor and when deployed.

**Comment by zdb999** [comment]
Sorry, I accidentally closed the issue. I've reopened it.

**Comment by Nikhil-Nandagopal** [comment]
@zdb999 thank you for reporting this. We're extremely sorry you had to face this issue. There was indeed a few issues reported in our latest release and we're actively working on resolving them

**Comment by zdb999** [comment]
No worries. I see the improvements going on all over the app, and I know regressions sometimes happen.

**Comment by zdb999** [comment]
I did some more digging, and I think the problem is with all the old tables. (Some still had pagination due to the large number of items in them.) The issue is that the previous formula calculating the table pageSize is pegged to the size of the grid elements. The update replaced the old grid with a finer one, but the calculation is off for old tables, which are still pegged to the old grid size. This means that the table is including around 50 rows for every 10 visible ones. You can see these mis-allocated them by scrolling down in the table, though the scroll bar is hidden.

**Comment by somangshu** [comment]
👋  @zdb999, Really interesting find, Allow me some time to look into this. We will get back to you with a solution! 😃

**Comment by somangshu** [comment]
@zdb999 you are right, this issue is happening because of the finer grid we released last week. We are talking this up right now and will have it fixed before the next release! Please let us know in case you see any other problems around this. Thanks for taking the time the time to debug. Mean a lot to us 💯 😊

**Comment by somangshu** [comment]
@vivekverma2312 Can we test this out urgently. Let me know if you are facing any challanges

**Comment by vivekverma2312** [comment]
@somangshu This is tested on release and working fine.

**Comment by zdb999** [comment]
I can confirm that the problem is fixed. Thanks for your prompt response and hard work on this issue!
