### ISSUE TITLE
[Feature] Allow access_token fetch URL  in data source to be dynamic

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#4784]
usecase: managing users in various auth0 tenants - so based on drop down selection(tenant name) ill have to hit a different API endpoint, in other words, the API end point I hit to fetch the access_token is dynamic, hence having the data source's access_token fetch url to be static doesn't help me well here.
infact, even my data source URL is dynamic

**Comment by vrishinvv** [comment]
So it would be great if not just the "access_token fetch URL", but also other optional fields (like audience, resource, scopes), and data source main URL too be made dynamic too!

**Comment by Nikhil-Nandagopal** [comment]
@vrishinvv is this because you have a separate tenant for each environment (staging / production)?
Would allowing you to configure multiple tenants and simply switch between them work? 
Related to #2836

**Comment by Nikhil-Nandagopal** [comment]
We'll be solving this as part of gitsync and multi envs
