### ISSUE TITLE
Autocomplete refinements specific to JS Editor

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#4787]
- [x] Show autocomplete in js editor without `{{ }}` - This is done
- [ ] #9480
- [ ] Autocomplete for function arguments - this is part of #7712

**Comment by ajinkyakulkarni** [comment]
@mohanarpit @ayushpahwa Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4787?planning-poker)

**Comment by mohanarpit** [comment]
Can we add more details to this issue? It's not clear what refinements need to be done here.
