### ISSUE TITLE
[Feature]: JS function arguments tooltip

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#4789]
Objective: Show function arguments in the autocomplete suggestions and allow users to configure parameters upon selecting an autocomplete result. 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5869e7a7c8d34a91b5a93b61c5c98baa-00001.gif)](https://www.loom.com/share/5869e7a7c8d34a91b5a93b61c5c98baa)

**Comment by ajinkyakulkarni** [comment]
@mohanarpit @ayushpahwa Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4789?planning-poker)

**Comment by ajinkyakulkarni** [comment]
Please look at this #7712 well.

**Comment by eco-monk** [comment]
1. JSEditor - arguments doesn't show up in autocomplete
2. Calling functions on property pane (show param hints, action creator UI, auto fill default values in action creator)

**Comment by eco-monk** [comment]
Discussing designs for showing function signature.

**Comment by eco-monk** [comment]
Looking at tooltips for multi-line function calls
![image.png](https://images.zenhubusercontent.com/61531fe29d35475e13482574/7be2b9ec-547f-494f-a2ae-f90fa9a58979)

**Comment by eco-monk** [comment]
Found that this could be an issue with one of codemirror's functions.
`innerMode` -> used to identify position of the argument we're working with.

**Comment by parth-appsmith** [comment]
@eco-monk we are currently designing a similar functionality for application level actions. You can refer the designs there for the same. 
https://www.figma.com/file/6DvoFPG0Gr5ggdLTyvzA84/Developer-handoff---App-Level-Actions?node-id=23%3A31521
1. The autocomplete lists the functions itself and we use the evaluated window component to show the signature of the function while the user is interacting with the autocomplete to select the function.
2. Once the function is selected, the expected arguments are shown as a placeholder to indicate the expected arguments to be passed.
3. There will be a persistent tooltip that appears when the user is inside the function parentheses showing the order in which the arguments are expected.

**Comment by rohan-arthur** [comment]
as discussed, issue for multi-line: https://github.com/appsmithorg/appsmith/issues/11899

**Comment by eco-monk** [comment]
The old PR: https://github.com/appsmithorg/appsmith/pull/10076

@rimildeyjsr, the logic we use here can be re-used in peek overlay.
Let's have discussion around this when this/peek overlay is started. (will attach a task for peek overlay shortly)

**Comment by arunvjn** [comment]
@bharath31 Is this peek overlay for functions ?

**Comment by bharath31** [comment]
> @bharath31 Is this peek overlay for functions?
@arunvjn nope. that is tracked [here](https://github.com/appsmithorg/appsmith/issues/27872)

The objective of this task is to show function arguments on the autocomplete result and also allow users to configure them after selecting the result.
