### ISSUE TITLE
[Bug] Error message toast clipped when connecting Google OAuth credentials for template Calendly app

### ISSUE THREAD

**Issue by shry4ns** [appsmithorg/appsmith#4795]
## Description
The toast message that appears when there's an error with the list_events on the Calendly template app is cut off. The suggestion, which is also part of the same toast message, is also cut off. On click, the message disappears. The full message still appears in the debugger. 

[What happened]
I was building a personal calendly clone using Nikhil's template app that is available [here](https://www.appsmith.com/templates). While doing so, I was putting the right credentials for both Zoom as well as Google calendar. After I put in the zoom and then Google credentials (which I believe were correct because the issue resolved itself), the error toast popped up.

### Steps to reproduce the behaviour:
1. Follow the template example in Appsmith for the Calendly app. 
    a. When you build the Google OAuth App, do not enable the calendar API (it should be disabled by default). 
2. When you're done putting in the credentials for Google calendar, immediately try to run the Google calendar API. It will ask you to log in with the account you built the OAuth app with, and then validate the credentials correctly. But then this message pops up. 

![Screen Shot 2021-05-30 at 10 21 41 PM](https://user-images.githubusercontent.com/29705742/120148416-cd221d00-c1ad-11eb-9b39-cc462cb80f45.png)

### Important Details

- Version: Cloud
- OS: MacOSx
- Browser Safari
- Environment: Production
- Screen size: 24inch Monitor, 1080p FHD resolution

**Comment by Nikhil-Nandagopal** [comment]
Hey @shry4ns was this because the calendar API was not enabled in the google backend?

**Comment by shry4ns** [comment]
Yes, that when the error toast popped up. But the error message was cut off
