### ISSUE TITLE
[Bug] Chart Data  goes empty on changing the type of chart

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4806]
Steps to reproduce:
1) Navigate the older app
2) Ensure the app has a Chart widget
3) Now click on the Property pane
4) Scroll down to the Chart data section and ensure for data
5) Close all the section
6) now navigate to Chart Type 
6) Ensure to select the different type 
7) Now Expand the section
and observe

Observation:
Data stays on the chart but in the property pane the data go invisble/ Empty

Expectation:
Chart Data must be displayed to a user 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/a334f51eebe9477f96161bf521ba6ac5-00001.gif)](https://www.loom.com/share/a334f51eebe9477f96161bf521ba6ac5)

**Comment by riodeuno** [comment]
With default custom chart configs available, this is no longer an issue.
