### ISSUE TITLE
[Bug]The Welcome Tour fails->The error pop up when the user clicks the Lets go button quickly

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4808]
## Description

[What happened ] In Welcome tour feature->When the user click on Do it for me button continuously then the error is displayed in widget and we are not able to continue the tour

Steps to reproduce the behaviour:

1.In the application page
2.click on Welcome tour
3.Click on Lets go Button
4.Click on Start Building button
5.Clik on do it for me button continuously
6.Validate the Functionality

expected result:
In Welcome tour feature->When the user click on Do it for me button continuously there should be pause or button should be disabled until the action is completed then allow to click on Lets go button so there should not be error
Actual Result:
In Welcome tour feature->When the user click on Do it for me button continuously then the error is displayed in widget and we are not able to continue the tour

**Attached Video**
https://drive.google.com/file/d/1R1PCrTERBWUofOVtNaZ3yjfpQN-fZkDp/view

### Important Details

- Version: Cloud 
- OS: Windows
- Browser Chrome
- Environment Production

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk can you have a look at this?
