### ISSUE TITLE
[Enhancement] In Welcome Tour ->once the tour is completed there should be close icon to close the pop up. 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4809]
## Description

[What happened ] In Welcome tour feature->once the tour is completed there should be close icon to close the pop up. currently we can only go to home or got to next mission which is making difficult to see what is the data displayed in the built table

Steps to reproduce the behaviour:

1.In the application page
2.click on Welcome tour
3.Click on Lets go Button
4.Click on Start Building button
5.Clik on do it for me button continuously
6.Validate the Functionality

expected result:
 In Welcome tour feature->once the tour is completed there should be close icon to close the pop up. 
Actual Result:
 In Welcome tour feature->once the tour is completed there should be close icon to close the pop up. currently we can only go to home or got to next mission which is making difficult to see what is the data displayed in the built table

![image](https://user-images.githubusercontent.com/45958978/120202510-49ffd600-c244-11eb-87db-5ad8857797e3.png)

Important Details
Version: Cloud
OS: Windows
Browser Chrome
Environment Production

**Comment by somangshu** [comment]
@Nikhil-Nandagopal is this even possible or intended?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu it wasn't but we can pick this up as an enhancement
