### ISSUE TITLE
[Bug]] In Welcome tour feature fails when the user attempts himself instead of using Do it for me button

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4810]
## Description

[What happened ] In Welcome tour feature->If user Try to attempt the welcome tour by himself instead of clicking the Do it for me button. and after doing it himself if he try to click on "Do it for me button" it fails and give the error message

Steps to reproduce the behaviour:

1.In the application page
2.click on Welcome tour
3.Click on Lets go Button
4.Click on Start Building button
5.Clik on do it for me button continuously
6.Validate the Functionality

expected result:
In Welcome tour feature->If user Try to attempt the welcome tour by himself instead of clicking the Do it for me button. and after doing it himself if he try to click on "Do it for me button" it should continue the tour

Actual Result:
In Welcome tour feature->If user Try to attempt the welcome tour by himself instead of clicking the Do it for me button. and after doing it himself if he try to click on "Do it for me button" it fails and give the error message

**Attached Video**
![image](https://user-images.githubusercontent.com/45958978/120203734-a9121a80-c245-11eb-9fa9-05eb55559107.png)

Important Details
Version: Cloud
OS: Windows
Browser Chrome
Environment Production

**Comment by akash-codemonk** [comment]
@RakshaKShetty Can you please clarify the scenario where this happens?

**Comment by akash-codemonk** [comment]
Closing it for now as we are no longer able to replicate this.
