### ISSUE TITLE
[Bug] Duplication Application name error

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4811]
## Description

[[What happened ] When the user try to add a duplicate name for the application there should be simple error message “The application with this name already exists 

Steps to reproduce the behaviour:

1.In the application page
2.click on Welcome tour
3.Click on Lets go Button
4.Click on Start Building button
5.Clik on do it for me button continuously
6.Validate the Functionality

expected result:
When the user try to add a duplicate name for the application there should be simple error message “The application with this name already exists. Please enter a different name"
Actual Result:
When the user try to add a duplicate name for the application the duplicate key Error message is displayed

![image](https://user-images.githubusercontent.com/45958978/120204554-95b37f00-c246-11eb-992e-ac260b316a62.png)

Important Details
Version: Cloud
OS: Windows
Browser Chrome
Environment Production

**Comment by Nikhil-Nandagopal** [comment]
@pranavkanade is this related to your change?

**Comment by pranavkanade** [comment]
@abhvsn this error string has to be handled from BE.
