### ISSUE TITLE
[Bug] Numbering for Table filtering  is not displayed 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4813]
Steps to reproduce:
1) Add a Table
2) Add a filter 
and observe

Observation
It is observed that the number of filters added are not displayed to the user 

Expectation:
It is expected that the numbering must be displayed to user which would help them to understand that filter is added into the table

**Comment by somangshu** [comment]
This is missing from the new design @momcilo-appsmith, How can we take care of this?

**Comment by Nikhil-Nandagopal** [comment]
@prapullac please tag the table widget as well in the issues

**Comment by momcilo-appsmith** [comment]
I just tagged you @somangshu and @prapullac in this file: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=0%3A1 at the update.
