### ISSUE TITLE
[Bug] Table order not working as expected when table data is dynamically set.

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#4814]
## Description

One of the users on discord reported that columns were not ordered as expected. 
He was trying to dynamically add data to the table on the change of a dropdown widget.
In one of the cases the "added column"(which is not dynamically created from table data but explicitly added from the property pane) was not showing up at the end but was showing up at the last but one position which is not expected.

### Steps to reproduce the behavior:

I saw the user reproduce the issue again and agian but I myself cud not reproduce it.
having this as a placeholder so that I can update it if I am able to reproduce it.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
@vivekverma2312 can we find the reproducible steps for this?

**Comment by marks0351** [comment]
@somangshu @vivekverma2312 sry forgot to update this yesterday. turns out it was coz of some parameters returned by the user's API. he was able to get it to work right. Closing this bug.
