### ISSUE TITLE
[Feature] Improve release workflow

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#4815]
Update our release promotion process to unblock developers and testers by keeping the `release` free for merging

Solution:
Whenever we want to promote to master, we checkout the current release branch into an RC (release-candidate) branch and raise a PR from the RC branch to master

- [ ] Create an RC label to be attached to the PR 
- Create a Github actions workflow when the RC label is present
  - [ ] Build client code and deploy on rc.app.appsmith.com
  - [ ] Build server code and deploy on rc.app.appsmith.com
  - [ ] get the current release drafter release notes and comment on the PR

**Comment by nidhi-nair** [comment]
Closed as redundant
