### ISSUE TITLE
[Bug] Access tokens are not being cleared when forking an application

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4823]

**Comment by AnaghHegde** [comment]
@sharat87 After doing some investigation, I discovered that, we are already clearing the `AuthenticationResponse` when forking which consists of `refreshToken `and `authToken`. This logic is present in `cloneDatasource` method of `ExamplesOrganizationCloner..java`.  

I did try cloning the app and after cloning i am getting the error which says invalid access tokens. 
`"Expected datasource to have valid authentication tokens at this point"`

Hence i will be closing this issue.
