### ISSUE TITLE
[Bug] When all the rows are hidden the user must not be displayed with number of records or pages in the Deploy mode

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4833]
Steps to reproduce:
1) Add a table
2) Hide all column
3) Now click on deploy
and observe

Observation: 
It is observed that the "Number of records and pages" are displayed to the user 

Expectation:
It is expected not to show the records when all the rows are hidden which leads to confusion by showing the details

![Screenshot 2021-06-01 at 1 55 51 PM](https://user-images.githubusercontent.com/71753653/120293190-a44f7400-c2e2-11eb-8136-d9832dcd4fdf.png)

**Comment by somangshu** [comment]
@prapullac hiding all columns does not mean the data set is empty. According to me, the behaviour is right, since its the columns which are hidden and not the rows!

**Comment by prapullac** [comment]
@somangshu: Since the data is hidden, showing the records or pagination would lead the user to confusion and search for the data in the table rather this is a rare scenario where all the columns are hidden which ends have data not being added.

**Comment by dilippitchika** [comment]
I would add an error if all the columns are hidden in the edit mode, but anything extra seems not worth it. 

Can't this be done by the dev, by an if condition in the visible property of the table which devs can define? Like if data is empty then show, else hide or any other rules. Don't think we need to solve this. 

@somangshu

**Comment by somangshu** [comment]
@dilippitchika today the header show/hide option is not JS convertible, we should definitely provide that and leave the onus of this error on the dev

**Comment by dilippitchika** [comment]
Hey @somangshu was referring to the isVisible property for the table. Dev can hide the table if the data is empty. Won't that solve it?

**Comment by somangshu** [comment]
Hiding the whole component from the viewport might not solve users problem because the user is still not informed wether there is an error or not.

also to the original point, I feel hiding all the columns does not mean that the data set is empty and hence this is actually a non-issue. However, providing the dev an option to choose to do this is good enough I feel
