### ISSUE TITLE
[Bug] Starting the tutorial for collaboration does not reset to canvas

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4840]
If a user starts the tutorial while on the API pane, the hint for the tutorial comes up in the canvas area, but the overlay of API pane is still present, so the tutorial itself cannot proceed till the user manually goes back to the canvas.

<img width="1536" alt="Screenshot 2021-06-01 at 7 21 23 PM" src="https://user-images.githubusercontent.com/5298848/120334780-8f88d580-c30e-11eb-8920-1f0d38d008b2.png">

**Comment by rishabhsaxena** [comment]
The option to toggle to comment mode is now hidden from other pages (apart from the canvas). So this should be fixed now
