### ISSUE TITLE
[Bug]In Application Page->user is able to keep the Display name empty 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4842]
## Description

[What happened ] In Application Page->When user is able to keep the Display name empty 

Steps to reproduce the behaviour:

1.In the application page
2.Click on User Name on left corner-
3.Click on edit Profile
4.Delete the  Display name 
5.Click on Profile text 
6.Verify the display of username displayed

expected result:
In Application Page->When user is should not be allowed to keep Display name empty
Actual Result:
In Application Page->When user is able to keep the Display name empty 
![image](https://user-images.githubusercontent.com/45958978/120351962-ef3aad00-c31d-11eb-9c2c-d0d5eb323225.png)

- Important Details
Version: Cloud
OS: Windows
Browser Chrome
Environment Release

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty doesn't seem like there's any dangerous impact so lowering priority

**Comment by TheRakeshPurohit** [comment]
I'd like to work on this.

**Comment by RakshaKShetty** [comment]
@TheRakeshPurohit This issue has been fixed as part of another issue you can pick up some other issues to work on using good first label.
