### ISSUE TITLE
[Bug]The tooltip should be displayed when the Organization name is too big

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4843]
## Description

The tooltip should be displayed when the Organization name is too big

Steps to reproduce the behaviour:

1.In the application page
2.Keep the organization name very big
3.Hover on the organization name 
4.verify the display

expected result:
In Application Page->When organization name is very big the tooltip should be displayed 
Actual Result:
In Application Page->When the Application name is very big there should be tooltip And in the organization section the tooltip should be displayed correctly when organization name is very big
![image](https://user-images.githubusercontent.com/45958978/120353281-31182300-c31f-11eb-9fc0-4361be7d4658.png)
![image](https://user-images.githubusercontent.com/45958978/120353296-337a7d00-c31f-11eb-9e48-0e59c4ddb4ed.png)

- Important Details
Version: Cloud
OS: Windows
Browser Chrome
Environment Production

**Comment by ashish921998** [comment]
@Pranay105 @RakshaKShetty @somangshu I would love to work on this issue.

**Comment by somangshu** [comment]
@hiteshjoshi can this be worked on, I am not sure is this already covered. Kindly check and assign @ashish921998

**Comment by hiteshjoshi** [comment]
Hi @ashish921998  This is no longer valid. It was resolved long back. Someone must missed closing this.
