### ISSUE TITLE
[Enhancement] : On edit mode user must be allowed to copy small chuck of data from Input widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4855]
Steps to reproduce:
1) Add an Input  widget
2) Add a long text 
3) Try to copy only a small part of the text 
and observe

Observation:
It is observed that when the user tried to copy the text the entire widget gets moved or has to use Keyboard shortcuts which copies the entire widget data 

Expectation:
User must be able to copy a small chuck data inside the text or input widget

**Comment by somangshu** [comment]
@prapullac I feel this is not valid because meta properties in the edit mode are just temporary. Also, this hinders with our default functionality. I am closing this issue, Feel free to re-open this if required
