### ISSUE TITLE
[Enhancement] Clicking on the Widget name showing error the debugger must open 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4856]
Steps to reproduce:
1) Add a widget
2) Add inappropriate data 
3) Error is displayed in the widget name
4) Click on the Widget name
and observe

Observation:
User is not displayed with any action

Expectation:
It is expected that the user is navigate/Highlighted to Debugger or open the debugger as such

**Comment by Nikhil-Nandagopal** [comment]
@prapullac when the property pane is open, the error field must be highlighted in red and that should be showing the error message and debug action. Is this not happening?

**Comment by prapullac** [comment]
@Nikhil-Nandagopal Yes this is working as expected.

**Comment by Nikhil-Nandagopal** [comment]
@prapullac I didn't understand then what was the enhancement about?

**Comment by prapullac** [comment]
So the expectation here was that instead of taking a property pane path we could consider that when the user clicks on the error notification (exclamatory mark) on the widget name we can open the debugger which would help the user

**Comment by Nikhil-Nandagopal** [comment]
Closing this as I think this might be unexpected since the user is used to seeing the property pane open
