### ISSUE TITLE
[Bug] MySQL tests don't run on an M1 Silicon Mac

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4860]
The MySQL tests in the server codebase use the `mysql:5.7` image. But this image is only available for `linux/amd64` architecture and not for `arm64`. Running this on M1 Silicon Mac needs the image to be available for the `arm64` architecture as well.

Alternatives include the [mysql/mysql-server](https://hub.docker.com/r/mysql/mysql-server/tags) images that are maintained by the Oracle team, or to use the mariadb image instead, which is reasonably compatible MySQL server.

@AnaghHegde, can you test out both the options above to see if they resolve the problem on your system and we can take a call based on the results?

**Comment by AnaghHegde** [comment]
@sharat87 It doesnt work with the existing configuration. What i mean is that `mysql-mysql-server` and `mariadb` instances run on different port. The current configurations in the `MySQLTest` class uses the default values from the `MySQLContainer`.  I am not sure if i should make these changes.
