### ISSUE TITLE
[Bug]Add a New query-> There is red thin line displayed around Textboxes when trying to add a new query

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4866]
## Description

Add a New query-> There is red thin line displayed around Textboxes when trying to add a new query

Steps to reproduce the behaviour:

1.Drag and drop a table and form widget
2.Select mongo DB as Data Source
3.Click on create query
4.Add the Collection and Query
5.Verify the display

expected result:
The red line should not be displayed around the text boxes when there is no error
Actual Result:
Add a New query-> There is red thin line displayed around Textboxes when trying to add a new query
![image](https://user-images.githubusercontent.com/45958978/120496444-3175f400-c3db-11eb-8ffb-9bbe2d394365.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment  deploy preview

**Comment by hetunandu** [comment]
Can you reconform this @RakshaKShetty

**Comment by RakshaKShetty** [comment]
Hi @hetunandu This issue is related to that particular deploy preview I am not facing this issue in any other environment, The issue is in the DP 4483. When the user create a new query for MongoDB and try to add collection and query, the red highlight is displayed around as in screenshot
![image](https://user-images.githubusercontent.com/45958978/123584942-e5627780-d7ff-11eb-8ed1-f78f1d3a6011.png)
