### ISSUE TITLE
[Bug]Add a New query-> There is red thin line displayed click on the textbox inside the Debug pop up debug button is not clickable

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4867]
## Description

Add a New query-> There is red thin line displayed click on the textbox inside the Debug pop up debug button is not clickable

Steps to reproduce the behaviour:

1.Drag and drop a table and form widget
2.Select mongo DB as Data Source
3.Click on create query
4.Add the Collection and Query
5.Click on the Textbox Inside the pop up click on Debug button
5.Verify the functionality

expected result:
The debug Button displayed inside the pop up when there are error is not clickable 
Actual Result:
Add a New query-> There is red thin line displayed when the user hover on it a pop up is displayed with debug button but that debug button is disabled

![image](https://user-images.githubusercontent.com/45958978/120496984-aa754b80-c3db-11eb-9603-ae63a4cb04bb.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment  deploy preview

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale is someone looking into this?

**Comment by hetunandu** [comment]
Can you reconfirm this @RakshaKShetty
