### ISSUE TITLE
[Bug]Widgets pane-> the user is not able to hover and drag the radio, switch ,Text widget 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4868]
## Description

[What happened]Widgets pane-> the user is not able to hover and drag the radio, switch ,Text widget 

### Steps to reproduce the behaviour:

1.Click on Widgets
2.hover on the radio, switch and text widgets
3.verify the display and functionality
![image](https://user-images.githubusercontent.com/45958978/120498505-e5c44a00-c3dc-11eb-9eac-956d12df17cd.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment  deploy preview

**Comment by RakshaKShetty** [comment]
hi @somangshu this issue is happening in Deploy preview, In the widget pane when the user hover on the radio, switch and Text widget it wont highlight and as a user i am not able to drag it 

In the attached video you can see when the user could easy drag and drop the rich text editor widget but 3when the user hover on the radio widget there was no highlight and was not able to drag the widget

https://drive.google.com/file/d/1mgEEdnyYF41i_O8m6EavMgtTvVjVmNsj/view

**Comment by somangshu** [comment]
@RakshaKShetty since this already merged into release, Kindly check if you can replicate the issue there, If not we can close this!

**Comment by RakshaKShetty** [comment]
> @RakshaKShetty since this already merged into release, Kindly check if you can replicate the issue there, If not we can close this!

ya sure

**Comment by marks0351** [comment]
^^ move the Netlify menu to the right of the screen and try. This issue is coz of it. It wont happen in our environments.

**Comment by RakshaKShetty** [comment]
> ^^ move the Netlify menu to the right of the screen and try. This issue is coz of it. It wont happen in our environments.

Thank you Ashok above solution worked for me

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty can we please close this if its no longer valid?
