### ISSUE TITLE
[Bug]API Datasource page redirects to the Database Datasource page

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4869]
## Description
Release Environment - It is observed that the API Datasource page redirects to the Database datasource type page

**Expected Result:**
Clicking on back button from the API Datasource page should remain with API pane page 

**Actual Result:**
Clicking on back button from API Datasource page redirects to the Database datasource page

### Steps to reproduce the behaviour:
1.Click on API and Click create new 
2.Pass any valid API url  - Get Method - https://reqres.in/api/users?page=2
3. Click on Save as Datasource 
4. Ensure new datasource will be generated 
5. Click on back button and observe

**VideoLink:**
https://www.loom.com/share/7993114218374562a454eebade189e90

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release]

**Comment by nidhi-nair** [comment]
@arunvjn Is this a quick fix? @YogeshJayaseelan also mentioned that during the `Save datasource` call, the page shown in the interim says `Select Datasource type` which should also be something we can avoid.

**Comment by YogeshJayaseelan** [comment]
It is also observed by clicking on 'save as Datasource' - Page loads and 'Select Datasource type' message will be displayed until page loads and then the new API datasource will be generated
