### ISSUE TITLE
[Bug]In Application Page->Click on Import menu->Inside the import pop up scroll bar is displayed for a single line text

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4870]
## Description

[What happened]In Application Page->Click on Import menu->Inside the import pop up scroll bar is displayed for a single line text

### Steps to reproduce the behaviour:

1.In the application page
2.Click on Application name
3.Click on import menu
4.verify the display inside the pop 

Expected result:
The scroll bar should not be displayed
Actual Result:
There is scroll bar displayed for a single line Text as in screenshot

![image](https://user-images.githubusercontent.com/45958978/120499782-f3c69a80-c3dd-11eb-8b8b-804719031377.png)

### Important Details

- Version: Cloud 
- OS: Windows
- Browser  chrome
- Environment  deploy preview
- Resolution 1920*1080

**Comment by pranavkanade** [comment]
This is fixed with new UI - https://deploy-preview-4483--appsmith-editor-ce.netlify.app/
