### ISSUE TITLE
[Bug]Import/Export->export a Application from org 1 then import it in Org 2 deploy then there is error when we deploy it

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4872]
## Description

[What happened]Import/Export->export a Application from org 1 then import it in Org 2 deploy then there is error when we deploy it

### Steps to reproduce the behaviour:

1.In the application page
2.Click on Application name
3.Click on import menu
4.verify the display inside the pop 

Expected result:
Import/Export->export a Application from org 1 then import it in Org 2 deploy then there should not be any error
Actual Result:
Import/Export->export a Application from org 1 then import it in Org 2 deploy then there is error when we deploy it

### Important Details

- Version: Cloud 
- OS: Windows
- Browser  chrome
- Environment  deploy preview
- Resolution 1920*1080

**Comment by abhvsn** [comment]
Need more clarity on this. Will it be possible to test the complete flow?

**Flow that I tried:**

Flow 1 :
1. Create pristine application in an organization/in a separate instance
2. Insert dummy widget 
3. Export app without deploying
4. Import the app in new instance/ new organization / same organization
5. Application will open in edit mode
6. Deploy the application and now can be opened in view mode

Flow2 : 
1. Repeat 1 and 2
2. Deploy the app
3. Repeat step 4
4. Now you can either open the application in view mode or edit mode both should work

**Comment by abhvsn** [comment]
@RakshaKShetty Can we close this?

**Comment by RakshaKShetty** [comment]
> @RakshaKShetty Can we close this?

ya Abhijeet it worked fine for me now closing the issue

**Comment by RakshaKShetty** [comment]
Closing the issue as its working fine in DP
