### ISSUE TITLE
[Bug] Application break for onLoadActions when duplicate action names are present

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#4876]
## Description

On load actions does not execute if the exported application have duplicate action names

### Steps to reproduce the behaviour:

1. Create application with duplicate action names in separate pages with onLoad configuration 
2. Import application from source instance
3. Export the .json file in destination instance
4. onLoadActions fail to execute

**Comment by Nikhil-Nandagopal** [comment]
@abhvsn can we close this?
