### ISSUE TITLE
[Feature] Add support in `navigateTo` function for generic protocols

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4878]
## Summary

A user would like to navigate to a locally available page on `obsidian`. Since our `navigateTo` function does not recognize such protocols, the navigation forcefully prepends `https` to the URL. We should allow a more generous validation for URLs.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_67cr0)

**Comment by GreenFlux** [comment]
**I have another use-case, and several new protocols that I would like to add to this request.** 
FileMaker Pro previously used `fmp://` for all files, but recently added the version number. So now there is `fmp18://`, `fmp19://`, etc. They also use `fmnet://` for connecting to hosted files. 
https://www.seedcode.com/filemaker-18-fmp-urls/

Perhaps the app definition could store a list of allowed protocols to treat as clickable links. This would be similar to the list of allowed file extensions for the File-Picker widget, but at the app level for protocols. 

I've noticed standard `https://` urls are automatically converted to clickable links in some places. If this functionality could be combined with a list of allowed protocols, it would greatly increase compatibility for integrating with other platforms. This would allow us to call up other apps and pass parameters to any new app/protocol, even local ones we create.

**Comment by samlander25** [comment]
I also have use cases that rely on custom protocols, the prepending of https and/or stripping of the semicolon makes that impossible.

**Comment by bharath31** [comment]
A user on Discord requested support for `sms://` https://discord.com/channels/725602949748752515/1048442331130494986/1048442331130494986

We should add support for app URI schemes so that navigation works as expected on phones.

**Comment by GreenFlux** [comment]
@satbir121 @bharath31 , we're seeing a lot more requests for other protocols lately in Discord. And it's leading to a lot of support threads, troubleshooting why these protocols are not working. 
https://discord.com/channels/725602949748752515/1060004966837788784

It's mostly for `tel://` and `sms://` at this point, but it would be great if we could solve for this in a way that enables generic protocols as well. 

Maybe we can have a few protocols that are allowed by default, then an option to enable all, or specify your own-- similar to the _allowed file types_ dropdown in the FilePicker widget.

**Comment by bharath31** [comment]
@GreenFlux thanks for flagging! I'm bumping the priority up.
