### ISSUE TITLE
[Task] Add documentation for Mongo form

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4881]
- Create usage reference for each field
- Add examples for which use cases are solved, and which ones are not

**Comment by ajinkyakulkarni** [comment]
@mohanarpit @ayushpahwa Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4881?planning-poker)

**Comment by sumitsum** [comment]
@nidhi-nair can we close this, since the doc now shows usage wrt the form : https://docs.appsmith.com/datasource-reference/querying-mongodb ?
