### ISSUE TITLE
[Bug] Property pane scrolls when we enable scroll on widgets

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#4883]
## Description

Property pane scrolls when we enable scroll on certain widgets. Loom recording attached:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c9baa7d93fc64f54bb28c7d1865edd54-00001.gif)](https://www.loom.com/share/c9baa7d93fc64f54bb28c7d1865edd54)

### Steps to reproduce the behaviour:

1. Drag and drop a container widget and enable scroll from property pane
2. Add any widget inside the container and open its property pane
3. Scroll the container. In this case, the property pane moves up while scrolling.

**Comment by somangshu** [comment]
@marks0351 is this something that is easy to work on or we need to identify the issue here?

**Comment by jsartisan** [comment]
Fixed with docked property pane.
