### ISSUE TITLE
Handle comment threads and links for tabs and modals

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#4886]
- We could also consider nested tabs while implementing this feature

**Comment by Nikhil-Nandagopal** [comment]
This doesn't work for modals also

**Comment by pranavkanade** [comment]
The primary blocker - Blocked by the current mechanism of updating the meta props of the widget. Need to get some ppl from UI pod.

**Comment by pranavkanade** [comment]
To resolve this issue we need a mechanism to update the meta properties of the widgets. ATM this is not permitted in the arch. Will need to do some more digging around the widget arch and state management for a widget.

Parking it for now.
