### ISSUE TITLE
[Bug]API Datasource updated successfully messages appears when clicking on 'New Query'

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4893]
## Description
Release Environment - API Datasource - It is observed that datasource updated successfully message appears after setting up and saving Credentials Grant type Datasource and the message appears upon clicking on New query as well

**Expected Result:**
Clicking on new query - The API is created successfully message only needs to be displayed 

**Actual Result:**
Clicking on new query - Both messages 'Datasource updated successfully' and 'Api is created successfully' appears

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the release Environment 
2. Expand API and click on new api 
3. Pass valid API url 
4. save as datasource 
5. Choose Authentication type as Oauth 2.0
6. Select grant type as - Credentials
7.Pass client id , secret, authentication code
8. Click on Save you will get message datasource updated successfully
9. Click on new query and observe the message 

**Video Link:**
https://www.loom.com/share/c2922196e9684ab5b0e846dfd0832f10

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release]

**Comment by nidhi-nair** [comment]
We're performing a save on the datasource and then creating a new API, which is why the message shows up. Is it counter intuitive to expect the save to happen? Should we simply change the button CTA to indicate that a save is expected? @ajinkyakulkarni assigning to you since this needs triaging.
