### ISSUE TITLE
[Bug] Text 'OAUTH2.0' is partially hidden in the right side of the suggestion box

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4897]
## Description
Release Environment - API - It is observed that when the user tries to pass new API url the suggestion box appears with the existing data source and its authentication type details and authentication type OAUTH2.0 is partially hidden 

**Expected Result:**
Authentication type should be clearly visible 

**Actual Result:**
Authentication type OAUTH2.0 is partially hidden in the suggestion box

### Steps to reproduce the behaviour:

1.Launch Appmsith app in the release Environment
2.Expand API and click on create new API
3.Pass valid url and click on save as datasource 
4.Choose the authentication type as Oauth2.0
5.Choose grant type as - Credentials 
6.Pass valid Client id, client secret , authentication token url and audience 
7.Click on save 
8.Repeat step 2
9. Click on the API header field to get the Suggestion box 
10. Observe the authentication type 

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release
<img width="1280" alt="Screenshot 2021-06-03 at 12 28 23 PM" src="https://user-images.githubusercontent.com/35128442/120613127-8e24ed80-c473-11eb-9711-be4572ab71e5.png">
]

**Comment by nidhi-nair** [comment]
@arunvjn Looks like a browser specific requirement as well.
