### ISSUE TITLE
[Bug]Dragging and Dropping Select widget and Tab Widget 'The value at selectedIndexArr is invalid' and 'The value at selectedTab is invalid' error occurs in the debugger

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4901]
Release Environment - Table Widget - It is observed that by dragging and dropping select widget 'The value at selectedIndexArr is invalid and for tabs widget 'The value at selectedTab is invalid' error occurs in the debugger

Expected Result:
Error should not occur by Dragging and Dropping any widgets

Actual Result:
Dragging and Dropping table widget error select and tabs widget 'The value at selectedIndexArr is invalid' and 'The value at selectedTab is invalid' occurs in the debugger

Steps to reproduce the behaviour:
1.Launch Appsmith app in the release Environment
2.Expand Widgets
3.Drag and Drop select and tabs widget and observe

**VideoLink:**
https://www.loom.com/share/7575307410a94034991e98f55d4849a9

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release]

**Comment by vibhandikyash** [comment]
@somangshu I checked this issue on local as well as on live and it seems to work fine now and no error can be seen in the debugger. @vivekverma2312 Just for double-checking can you also comment on the same so we can close this up directly.

**Comment by vivekverma2312** [comment]
@vibhandikyash Not able to repro this on prod or release environment. @YogeshJayaseelan Is there any specific step to repro this?

**Comment by YogeshJayaseelan** [comment]
@vivekverma2312 Not able to repro this in prod or release @vivekverma2312 There is no specific steps for this just by dragging and dropping select and tabs we got that error earlier. Now this is not happening
