### ISSUE TITLE
Show confirmation before leaving an organization

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#4903]
Users can leave an organization from two places:

- By clicking the "Leave organization" from the organization popup which appears after clicking the organization name in home page
- By clicking the delete icon in the members page

As leave organization is a destructive operation, it'll be nice to have a confirmation from the user before calling the API. UX can be same as we have now when deleting an app.

**Comment by RakshaKShetty** [comment]
In release freeze->there is 2nd level check when the user need to leave a organization or a user is being removed from the organization, as it is working as per requirement closing the item

**Comment by RakshaKShetty** [comment]
We have tested the leave org feature now when the user click on leave org or admin delete any of the user then the pop will be displayed.
Closing the issue
