### ISSUE TITLE
[Bug] Widget tag on bottom right has lower z-index

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4906]
## Description

Settings for widgets become inaccessible when placed close to each other because the tag is hidden.

### Steps to reproduce the behaviour:

https://user-images.githubusercontent.com/5298848/120630137-25923c80-c484-11eb-9643-6baeab9e865c.mov

**Comment by somangshu** [comment]
@marks0351 need your help understanding the effort here. Please drop a note!

**Comment by marks0351** [comment]
@somangshu this a low-effort bug.I am fixing this as part of widget grouping phase II. will tag bug in the PR.

**Comment by areyabhishek** [comment]
Will widget grouping be ready for prod? We should do a new release today or tomorrow. If this issue persists when we do that, then our prod will be broken.
