### ISSUE TITLE
[Bug] Multipart form data in REST APIs does not recognize content type

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4907]
## Description

Multipart form data does not seem to be able to recognize content length since it sends the information in chunks. The content type for individual parts is also not recognized properly.

### Subtasks: 
- Fix Content-type for parts
- Add Content-length to request (can we modify the chunked encoding here?)
- Optional filename information for a part

**Comment by ajinkyakulkarni** [comment]
Related issue - https://github.com/appsmithorg/appsmith/issues/1586

Internal discussion about this bug - https://theappsmith.slack.com/archives/C01HXJPFWBC/p1622621985103300

**Comment by nidhi-nair** [comment]
Moving up in priority since this is causing a break in experience.

**Comment by aakashDesign** [comment]
@nidhi-nair @hetunandu You can find the design here- https://www.figma.com/file/ko05rfZRuc8HzqBZRpg1fY/API-Pane-Updates?node-id=119%3A2

<img width="1562" alt="Screenshot 2021-06-28 at 11 22 03 AM" src="https://user-images.githubusercontent.com/65771350/123586909-12fcf000-d803-11eb-81b3-0eca9b5e7eb5.png">
