### ISSUE TITLE
[Bug] Improve restricted entity names to include JS global variables

### ISSUE THREAD

**Issue by BlueWater86** [appsmithorg/appsmith#4919]
## Description

Error occurred while evaluating trigger: Cannot set property location of #<WorkerGlobalScope> which has only a getter

### Steps to reproduce the behaviour:

We were building a form with a field named "location" it appears that there are many possible global variables that can be broken like this.

1. Add modal widget to a page
2. Change the property/name of the modal or any child control on the modal to "location"
3. Add a button widget to a page
4. Set the onclick action of the button to show the modal above
5. Click the button

### Important Details

- Version: Self-Hosted latest
- OS: Ubuntu
- Browser chrome
- Environment release

**Comment by hetunandu** [comment]
@BlueWater86 Thanks for raising this issue. It seems like we missed out on some critical variables in the JS global scope. Will ensure that this is not possible to save in the first place.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu will this be an entity name validation?

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal That is correct
