### ISSUE TITLE
[Bug] API -  Passing valid credentials and API header 400 Bad request is received

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4927]
## Description
Release Environment - API - It is observed that by passing valid authentication credentials and API header 400 bad request is received

Expected Result:
API should run successfully by passing valid authentication credentials and API header

Actual Result:
400 Bad Request in received by passing valid authentication credentials and API header

### Steps to reproduce the behaviour:

1. Launch Appmsmith app in the release environment
2.Expand API and click on new api
3.Pass the following valid API header -  https://test-cc-audience-1.us.auth0.com/api/v2/client-grants
4.Click save as Datasource
5.Choose the authentication type as - Oauth2.0
6.Pass the following client id , client secret, authentication url, audience

audience: https://test-cc-audience-1.us.auth0.com/api/v2/
client id: oaUGCQzqwDqqHX66wTTptFdrVxsJEs8o
client secret: NtfJDEz740A2hoEFz1wCEqiCP5zh2Z6GbOSTXlTs_XHv6pyMIYdUl7ELv14uTUml

7.Execute the API and observe

**VideoLink:**
https://www.loom.com/share/3947758ea5ff4776bf9b1289d11a8f19

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release]

**Comment by YogeshJayaseelan** [comment]
@nidhi-nair @prapullac now the following error occurs 'Illegal character in the scheme index at 0' with status code 5000

![Screenshot 2021-07-19 at 11 50 43 AM](https://user-images.githubusercontent.com/35128442/126113022-f0ff1ecb-6816-47c7-bd82-48298a996b58.png)

**Comment by nidhi-nair** [comment]
@YogeshJayaseelan looks like there's an extra space at the start of the URL, can you confirm?

**Comment by YogeshJayaseelan** [comment]
@nidhi-nair We tried again now with valid header url and the API runs successfully..

<img width="1680" alt="Screenshot 2021-07-28 at 11 44 18 AM" src="https://user-images.githubusercontent.com/35128442/127273568-70eac408-4cdc-4564-aa93-541739f6d556.png">

<img width="1680" alt="Screenshot 2021-07-28 at 11 44 33 AM" src="https://user-images.githubusercontent.com/35128442/127273603-6c9b9eb6-2654-4327-9742-9c45537d47f4.png">

**Comment by nidhi-nair** [comment]
Closing this as the error was because of incorrect set up.
