### ISSUE TITLE
[Bug] Chart Widget - 'The value at the Custom Fusion chart config is invalid' error occurs when user first clicks on ChartData field and then any other fields 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4932]
## Description
Release frozen - Chart Widget - It is observed that when the user changes the chart type to custom and clicking on chartdata field initially and clicking on any other fields error occurs with the chartData field 'The value at the custom fusion chart config is invalid'

**Expected Result:**
Clicking on chartdata field and then clicking on any other fields error should not occur. For some reasons user might go back to any other chart to get the actual chartdata field value.

**Actual Result:**
Clicking on chartdata field initially and then clicking on any fields 'The value at the Custom Fusion chart config is invalid'

### Steps to reproduce the behaviour:

1.Launch Appmsith app in the release frozen environment - http://rc.app.appsmith.com
2.Drag and drop chart widget 
3.Change the chart type to Custom chart 
4.Click on ChartData field 
5.Click on any other fields and observe

**VideoLink:**
https://www.loom.com/share/8fcea8a29d07451a84aa4d665131070f

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release Frozen]

**Comment by somangshu** [comment]
In this case, the chart data field is `dirty` and `empty` and hence the validation kicks in. I think it's the correct behaviour. 

@jsartisan @vibhandikyash what do you guys think?
