### ISSUE TITLE
[Bug] Unable export an application when the user is "App Viewer"

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4933]
Steps to reproduce:
1) Share the Application to Account B from Account A
2) As App viewer
3) Now navigate to Account B 
4) Ensure we can launch the application 
5) Now click on the action button
6) Click on Export option 
and observe the file downloaded 

Observation:
The file gets downloaded opening the doc displays an error 

Expectation:
The export option must not be displayed to the user  or if displayed must be functional

Video:
https://www.loom.com/share/b21023e112d3422185176b79f28c256a

![Screenshot 2021-06-04 at 6 23 39 PM](https://user-images.githubusercontent.com/71753653/120804920-ce16ce00-c562-11eb-823f-00e4e4fcd4c5.png)

**Comment by abhvsn** [comment]
This is expected behavior as while exporting the app, sensitive fields like DB passwords will also be shared to which app viewers don't have the required permissions. Any other views?

**Comment by prapullac** [comment]
Considering this is not applicable for a particular role we should not be providing an option to the user.

**Comment by abhvsn** [comment]
Yeah, that sounds like a good option.

**Comment by pranavkanade** [comment]
@abhvsn @prapullac #4938 will take care of this issue.

**Comment by RakshaKShetty** [comment]
@pranavkanade i have tested the the issue in release frozen now the user who has viewer access cant export the application, issue is fixed
closing the bug
