### ISSUE TITLE
[Bug] Clicking on options inside the Property pane of the table opens 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4948]
Steps to reproduce:
1) Add a table
2) BInd with an API 
3) Click on  any of the option "Filter, Download and Row height"
and observe

Observation:
It is observed that the  property pane opens and option are overlapped

Expectation:
The property pane must not open when the user clicks inside the table widget  

![Screenshot 2021-06-07 at 12 50 22 PM](https://user-images.githubusercontent.com/71753653/120975520-f256f280-c78e-11eb-839f-ba5e1005ea6c.png)

**Comment by somangshu** [comment]
@prapullac this is the default behaviour. Clicking on the widget in edit mode will open the property pane! Closing this for now.

@marks0351 please correct me if I am wrong.
