### ISSUE TITLE
[Bug] Not able to place widget at bottom of canvas due to slow loading of grid

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4951]
### Steps to reproduce the behaviour:

1. Drag and drop a widget on canvas
2. Now scroll the canvas till bottom
3. Try to drag and drop another widget at bottom of canvas
4. Observe that the grid is taking time to load at bottom of canvas and due to this the widget could not be placed

### Important Details
- Environment : release-frozen regression
- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

https://www.loom.com/share/3cc23e01296d4fec8d98793f060ac37b

**Comment by marks0351** [comment]
@vivekverma2312 can u check this against the new DnD?
if this is fine we can close this issue.

**Comment by YogeshJayaseelan** [comment]
@marks0351 @vivekverma2312 Verified this and now able to place widget at the bottom of the canvas
