### ISSUE TITLE
[Bug] GoogleSheet - GoogleAPI Documentation leads to Database Documentation content 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4953]
## Description
Release Frozen - GoogleSheet - Its is observed that when the user navigates to GoogleAPI --> Settings --> Documentation, Database documentation content is displayed

**Expected Result:**
GoogleAPI documentation should show content related to GoogleAPI

**Actual Result:**
GoogleAPI documentation leads to Database Documentation content

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the Release frozen environment 
2. Click on API
3. Click on GoogleAPI
4. Sync Google Datasource 
5. Click on new API
6. Click on Settings menu 
7. Click on Documentation and observe

**VideoLink:**
https://www.loom.com/share/25aa1dafb9974f4d8149e8f79ed29449

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release Frozen]

**Comment by nidhi-nair** [comment]
@somangshu This seems to be an issue with the way the omnibar is picking up the relevant page to show in the results. The google sheet documentation link is correctly linked to: https://docs.appsmith.com/datasource-reference/querying-google-sheets

This is also seen for redis, with no real result shown from docs, I see this on clicking `Documentation` inside a Redis Query pane.
<img width="748" alt="Screenshot 2021-06-08 at 11 30 20 AM" src="https://user-images.githubusercontent.com/5298848/121131071-ea5d8800-c84c-11eb-8e91-5b47f425bb33.png">

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk can you fix this?
