### ISSUE TITLE
[Bug] Table widget doesn't update when changing the page number and hitting the return key

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#4955]
## Description

In table widget when you change the page number, it doesn't update until the input looses focus.
Expected behaviour: Hitting enter should update the page.

### Steps to reproduce the behaviour:

- Create a table with at least 10 pages.
- Update the page number and hit enter, it doesn't react.

![Table navigation issue](https://user-images.githubusercontent.com/441914/121006177-39a0ab80-c7ae-11eb-87c5-125fa48d6d74.jpg)

**Comment by Devedunkey** [comment]
@Nikhil-Nandagopal Is there anyone working on the issue? It does not sound like a lot of involvement. I can go and try it out.

**Comment by Nikhil-Nandagopal** [comment]
@Devedunkey go for it!
