### ISSUE TITLE
Add pagination and other fields to Notifications

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#4958]
The GET notifications API should have a pagination so that it returns a limited number of records at a time. Also need some fields:

- timestamp
- field for comment links:
  - applicationId
  - pageId
  - resolved state
  - comment thread id for both commentThread and comment notifications
- user display name for profile images
- using `type` for displaying the notification content, most probably it was missing for the new comment notification
- might need application name as well

**Comment by Nikhil-Nandagopal** [comment]
Need a Read / Unread API for notifications
