### ISSUE TITLE
[Feature] Improve Mock Datasets

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#4962]
# Problem
Today our mock data is used for examples, tutorials, onboarding, and for users to play around with. This makes it difficult for new users to understand how to use the data.
Our data is also all in postgres while many users use MongoDB.

# Solution
Keep all our data for example apps & tutorials in fakeapi
Have a separate database for users in postgres
Have a separate database for movies in mongodb
Have a separate database for super standup onboarding in postgres
Show only the super standup db in the onboarding flow

**Comment by AnaghHegde** [comment]
@Nikhil-Nandagopal @vihar @sharat87  This is done. I have made changes to the cron job to include new workflows which will restore the mock data for all the use cases mentioned in the issue. 
Please have a look and let me know if there are any concerns.

**Comment by Nikhil-Nandagopal** [comment]
@AnaghHegde can you document the DBs somewhere and share it?

**Comment by AnaghHegde** [comment]
@Nikhil-Nandagopal

Movies collection 
`mongodb+srv://shri:find@mock.0rat3.mongodb.net/movie_store?authSource=admin&replicaSet=atlas-omu29w-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true`

Users mock data 
```
PGHOST=fake-api.cvuydmurdlas.us-east-1.rds.amazonaws.com 
PGUSER=users 
PGDATABASE=users 
PGPASSWORD=new-users-db-pass 
```

Super Standup
```
PGHOST=fake-api.cvuydmurdlas.us-east-1.rds.amazonaws.com 
PGUSER=super_standup 
PGDATABASE=super_standup
PGPASSWORD=super-standup-super-password 
```
This is temporary, once @vihar @cokoghenun confirms after testing, i will update theses in the right place.

**Comment by AnaghHegde** [comment]
@Nikhil-Nandagopal You can find the details here

https://www.notion.so/appsmith/Mock-Data-for-Users-0fae07801fe54e32a01b41b84231a7d2

**Comment by AnaghHegde** [comment]
Workflow ran successfully. I guess we can close this. 
![image](https://user-images.githubusercontent.com/12005551/123279185-3f73ec00-d525-11eb-9cfc-c6edb76c5109.png)
