### ISSUE TITLE
[Bug] Multiple options with different label but same value stopped working

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4966]
Having multiple options with same `value` in a dropdown widget used to show all the labels that have the same value, as different options in the dropdown. However, this stopped working recently and we only see a **single** option in the dropdown.

![Screenshot 2021-06-07 at 19 23 11](https://user-images.githubusercontent.com/120119/121029278-171a8c80-c7c6-11eb-87aa-00cb3ff18f04.png)

**Comment by somangshu** [comment]
@sharat87 what is the expected behaviour? I think removing the duplicate option is the right behaviour.

**Comment by sharat87** [comment]
@somangshu it's not _exactly_ a duplicate option right? The label is a human-readable, user-friendly piece of text. But the value is for machine consumption. So it's possible to have cases where we want to show multiple different options to the user, for APIs powering it, they probably just need the value. If the APIs need to differentiate further, they can use `.selectedLabel` just as well.

Additionally, I also think allowing this would mean adding synonym options with the same value to improve finding items in the filter.

Nonetheless, apparently this was working previously and only started dropping the duplicate options in the latest (or last to latest) release. So it's breaking apps. :|

**Comment by Nikhil-Nandagopal** [comment]
Actually, this should be a validation error right? @somangshu

**Comment by somangshu** [comment]
@Nikhil-Nandagopal we can do that, But @sharat87 is talking about this being a valid case and old apps making use of this.

@sharat87 correct me if I am wrong!

**Comment by Nikhil-Nandagopal** [comment]
Yeah I misunderstood when sharat shared this as well. I thought both labels were the same. This isn't valid

**Comment by sharat87** [comment]
@somangshu, yep, correct.

@Nikhil-Nandagopal, I'm not sure I follow. The labels are different, but the value is same. Is such use case going to be invalid?

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 no value is meant to be unique in the dropdown

**Comment by sharat87** [comment]
Alright. This is a change in behavior for the dropdown widget then.

Closing as won't fix.

**Comment by Nikhil-Nandagopal** [comment]
@sharadagg thank you for explaining your use case. There needs to be a unique id to identify the selection in the dropdown, hence the value field is used for this. Since price is not unique, you can use the itemId for the value and then look up the price from your data based on the Id that is selected. Does that make sense?
