### ISSUE TITLE
[Bug] Widget title hidden behind widgets

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4969]
<img width="527" alt="Screen Shot 2021-06-08 at 1 43 53 AM" src="https://user-images.githubusercontent.com/30255708/121082073-2f58ce80-c7fb-11eb-93ed-a97437601a04.png">
<img width="199" alt="Screen Shot 2021-06-08 at 1 44 11 AM" src="https://user-images.githubusercontent.com/30255708/121082076-31229200-c7fb-11eb-9dc0-38f0e929efe7.png">
<img width="283" alt="Screen Shot 2021-06-08 at 1 44 29 AM" src="https://user-images.githubusercontent.com/30255708/121082079-31bb2880-c7fb-11eb-8e20-9d75677d1ca8.png">

**Comment by somangshu** [comment]
Closing this in favour of #4906
