### ISSUE TITLE
[Bug][UI Performance] Saving a page seems to block UI thread

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#4973]
## Description

The auto-save feature works by saving edits to the page's properties in a debounced manner. 

A user reported that their UI thread is blocked while they're in the middle of editing a property like a widget's name, it was noted that the page was in the middle of being saved when the UI thread freeze occurred.

## Next steps
- [ ] Triage issue and figure out the cause for the UI thread block
- [ ] Figure out a different, non-blocking approach for the auto save or prevent the UI from blocking while saving.

### Important Details

- Version: 1.5.3.2
- Environment production

**Comment by SatishGandham** [comment]
UI freezes because the whole canvas is rendered when a property changes, it's not because of the save or the network request.
This should be improved as a result of this
https://github.com/appsmithorg/appsmith/issues/4992
