### ISSUE TITLE
[Bug] Filter is not displayed to user when the data is changed

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4974]
Steps to reproduce:
1) Add a table widget
2) Add a filter
3) Now bind the table
4) observe the table does get  populated
5) Filter value is displayed 
6) Click on the filter
and observe

Observation:
It is observed that the applied filter is not displayed in the option 

Expectation:
When there is  new data added the filter option must be cleared or applied filter must be displayed to user so that user can clear the data

Deploy preview: 
https://deploy-preview-4916--appsmith-editor-ce.netlify.app/

**Comment by somangshu** [comment]
@prapullac please attach a screen recording for some clarity here

**Comment by prapullac** [comment]
@somangshu : Attaching a video below for the same 
https://www.loom.com/share/217d7cef57d140cc978421765ba4fc33
