### ISSUE TITLE
[bug]When the user enable "Make the application public" the edit and Comment toggle is not displayed on the top section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4978]
1.Create a new app
2.click on deploy button
3.Click on share icon on top section
4.inside the share pop up
5.enable the "Make the application public
6.verify the display of edit comment toggle
![image.png](https://images.zenhubusercontent.com/60a213f9a1e4f1bd65b83f42/e6cc02c4-d400-408e-bdd3-d403685f7faa)

**Comment by areyabhishek** [comment]
@RakshaKShetty the edit+comment icons are a new feature that's only available to @appsmith.com users today. It's for the new commenting feature that we are testing.

**Comment by Nikhil-Nandagopal** [comment]
Re-opening for the same reason as prev issue, we're using these as a checklist for devs. @RakshaKShetty maybe we can demarcate these with the release tag

**Comment by RakshaKShetty** [comment]
The View and comment icon is displayed when the user enable the application public in Share pop up
