### ISSUE TITLE
[bug]create a new app->click on deploy button->there is an edit icon display on top icon->and it is non functional currently 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4979]
1.Create a new app
2.click on deploy button
3.verify the display of edit icon
![image.png](https://images.zenhubusercontent.com/60a213f9a1e4f1bd65b83f42/f80edcb0-a621-4e1c-8a27-11db7c9cb787)
expectation: As there is no functionality associated with it i don't see any use of the icon so it can be removed

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek Raksha is filing the bug as part of the test so the devs can pick it up
