### ISSUE TITLE
[Bug] Column order is reset when using server side search on table widget

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#4984]
## Description

https://user-images.githubusercontent.com/103687/121185726-fd3f7f00-c883-11eb-94dc-71dd7a624d2c.mov

### Important Details

- Version: 1.5.3.2

**Comment by Tooluloope** [comment]
@riodeuno This works fine now 
https://www.loom.com/share/6c7d5604e65e490e9d939750b3e25736

**Comment by somangshu** [comment]
Reopening this issue, @Nikhil-Nandagopal still faced the same problem

**Comment by riodeuno** [comment]
@somangshu @Nikhil-Nandagopal 
Issue context
-------------
When changing the search text, the server returns a new tableData. Ideally, if the columns are the same (or similar), the order should be preserved. However, if they're different, they will be reset, as the data object keys are used as a reference for the column order. 

This is checked in the `createTablePrimaryColumns` and `updateColumnProperties` in the table widget code.


@somangshu Please re-assign this.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno with every new column added, the order seems to be getting reset. You can checkout the JS Snippets app

**Comment by Tooluloope** [comment]
@somangshu @riodeuno Still not able to reproduce this

**Comment by Nikhil-Nandagopal** [comment]
We have the scenario now, its when a single row as [{}]

**Comment by Tooluloope** [comment]
Reproducible steps
Create a table
Create a query that fetches data
Mark it as onPageLoad false
bind it as {{ Query1.data.length > 0 ? Query1.data : [{}] }}
Change the order of columns in the table
refresh the page
Go to the api run the query
The table columns are all reset
