### ISSUE TITLE
[Bug] Deploy Preview - List Widget Phase 2 Issues

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4985]
## Description
https://deploy-preview-4189--appsmith-editor-ce.netlify.app/

Issues:
1. Unable to expand list section till the pagination area
2. Unable to place container widget inside list widget 
3. Placing Chart widget inside list widget is not smooth as the list widget space is smaller
4. Trying to place Table widget or Tabs widget inside list widget should throw the alert message "Table or tabs widget cannot be placed inside list widget"
5. If the list widget's window is decreased at some point the list sections are not visible - Can we implement decreasing limit so that the list section is visible always.
6. Item background turns black If the Item background colour is set to any colour and then changed to No colour 
7) Checkbox widget alignment is not functional when placed on the List widget
8) Outer boundary of the list widget overlaps on the inner widget and this makes the pagination overlap on the list widget
9) On overlapping of the boundaries does not allow smooth movements for resizing 

**VideoLink:**

The below video link is for the 5th point alone

https://www.loom.com/share/da12c2e3e8ac49cc92fb6b4732ced384

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [deploy preview]

**Comment by prapullac** [comment]
Phase 2 Issues:
1) On overlapping of items and outer border it is observed that there is no smooth movement back separating them.

**Comment by jsartisan** [comment]
Merged into release #4189
