### ISSUE TITLE
[Bug] Multi-select dropdown doesn't update the value sometimes

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4988]
The dropdown widget, when multi-select is turned on, doesn't update it's value when it is connected to the `selectedRow` of a table widget.

![](https://cdn.discordapp.com/attachments/760761686549463060/851831330580332605/Screen_Shot_2021-06-08_at_10.32.58_PM.png)

https://user-images.githubusercontent.com/120119/121302676-ab483900-c917-11eb-8e8d-88b10d474040.mov

**Comment by somangshu** [comment]
@vivekverma2312 can you add steps to reproduce here as well

**Comment by phangs** [comment]
The setup is basically, API call provides data to the table (getPowerups).
On row select (table), the form on the right is populated by the selected row (Powerup record)

1. Click/select select record to be updated
2. Modify the Related Powerup dropdown.
3. Click submit.

Submit sends a PUT request to the api server to update the record and a GET request to fetch the new record set.

After the latest records have been placed on the table, selecting any record shows that the Releated Powerup field no longer update correctly as seen on the video.

**Comment by somangshu** [comment]
👋  @phangs, Thank you so much for giving us this information. This will be really helpful to us 😄

**Comment by somangshu** [comment]
@phangs can you help me understand if you are using `selectedOptionValue` or `selectedOptionValues` in your API binding while updating?

**Comment by phangs** [comment]
> @phangs can you help me understand if you are using `selectedOptionValue` or `selectedOptionValues` in your API binding while updating?

I am using this, "relatedPowerUps": {{selRelatedPowerups.selectedOptionValues}},

**Comment by somangshu** [comment]
Hey, I replicated a similar situation on my end as well, [Find it here](https://release.app.appsmith.com/applications/60c0c1ff0acd7442a2aacc66/pages/60c0c1ff0acd7442a2aacc68). Still cant seem to figure the issue here. Ill try to get back to as soon as I find something here.

**Comment by phangs** [comment]
> Hey, I replicated a similar situation on my end as well, [Find it here](https://release.app.appsmith.com/applications/60c0c1ff0acd7442a2aacc66/pages/60c0c1ff0acd7442a2aacc68). Still can't seem to figure the issue here. I'll try to get back to you as soon as I find something here.
> 
> Please let me know if I am doing something wrong/different here

I've checked the your link, yeah it doesn't show up there. I do not know if it will help but I am attaching the exact json response from the API.

Also here is the JS for the submit button:
`{{
    updatePowerup.run(
        () => {
            showAlert('Powerup updated','success');
            getPowerups.run();
            },
    () => showAlert('Update failed','error'))
}}`


Options for the related powerup field:
`{{tblPowerups.tableData.map((powerup) =>{
	return{
		label: powerup.displayText,
		value: powerup.id
	}
})}}`

Default option for related powerup field:
`{{tblPowerups.selectedRow.relatedPowerUps}}`

Table Data:
`{{
_.orderBy(getPowerups.data, ['displayText'], ['asc']);
}}`


[STG_Get_All_PowerUps-1623250608337.json.zip](https://github.com/appsmithorg/appsmith/files/6624786/STG_Get_All_PowerUps-1623250608337.json.zip)


Hope this helps.

**Comment by hetunandu** [comment]
On further investigation, we found that the dependency between `Select.defaultSelectedValue` and `Select.selectedOptionValueArr` gets deleted during form reset.

**Comment by hetunandu** [comment]
Fixed with #5333
