### ISSUE TITLE
[Bug] Selected row gets removed on updating the details but if we do not make any changes and click on update  it stays selected

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4990]
### Steps to reproduce the behaviour:

1. Select any row on app->  https://app.appsmith.com/applications/60c074c1357edd365a168762/pages/60c074c1357edd365a168764/edit
2. Observe the data get populated on the form
3. Change the data and click on update button
4. Observe the row is not selected on table
5. Now select a row on table and data get populated on form
6. Do not make any change and click on Update button
7. Observe the row is still selected

Expected behaviour: Row should be selected in both the cases.

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser chrome
- Environment: production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9ff4656a9e234b1486bb48dadfb90e4b-00001.gif)](https://www.loom.com/share/9ff4656a9e234b1486bb48dadfb90e4b)

**Comment by somangshu** [comment]
@Tooluloope can you help triage this issue?

**Comment by somangshu** [comment]
@riodeuno need help triaging this

**Comment by somangshu** [comment]
@riodeuno one solution here is to ask the user for selecting a column which can be the primary key to identify the data, So based on this key we can decide what row needs to be selected after the table data has updated. Let me know if this does not make sense

**Comment by SatishGandham** [comment]
Having a primary key also helps with react performance.

**Comment by somangshu** [comment]
Quoting @SatishGandham 
> We should fallback to index if primary key is not given. Else we will break existing apps.

**Comment by SatishGandham** [comment]
We should fallback to index if primary key is not given. Else we will break existing apps.
The whole thing should be a small change on how we save the selection, or how we store a row reference, everything else should fall in place automatically.

**Comment by somangshu** [comment]
Note:
- New property: Selected row key > Dropdown control which contains all columns options
- Helper: Lets you persist a selected row based on unique row value in a column on table data update, if left blank this will be set to the rowIndex. 

Q: do we need a append some random char to the row value to be sure that it is unique, Or we leave the onus on dev? Based on this the helper will change

**Comment by chandannkumar** [comment]
Issue still exists.
Expected Behavior: default selected row should always be the same as selectedRow by user in both the cases

**Comment by somangshu** [comment]
@chandannkumar here we have introduced a property called as the primary key column, On setting this you will see that the row selection is persisted. Without that we have no way to identify what was the selected column as we are comparing the objects
