### ISSUE TITLE
UI Performance July

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#4992]
## Objective
Improve UI performance of editing a property in the property pane.
- Codemirror binding based property updates

# Success Metrics
| Goal  | Goal Metric | Current Metric
| ------------- | ------------- | -------------- |
| Minimise UI thread blockage when changing a property of a widget  |  300-500ms delay between two character changes | 1500 ms delay between two character changes

# Requirements
| Requirement  | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
|  Smooth typing experience for property update  |  User should be able to edit any property on a property pane without noticeable UI freeze. The UI should not jitter while typing code inside the property pane  | High | Slowdown 4x CPU for testing

# Benchmark system specs
- Browser: Chrome
- Browser Settings: Regular, without throttle.
![Screenshot 2021-07-04 at 9 53 11 AM](https://user-images.githubusercontent.com/441914/124373173-a9229180-dcad-11eb-8172-7f372bc1245e.jpg)

Demo of how the typing experience will be like: https://satishgandham.com/input-delay-glitch/

**Comment by somangshu** [comment]
@SatishGandham can you close this, We something here belongs to the aug plan then lets take it out of here
