### ISSUE TITLE
[Bug] Widgets are displayed partially outside the container widget if resized

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4993]
### Steps to reproduce the behaviour:

1. Drag and drop container widget
2. Drag and drop table widget on top of container widget
3. Resize the container widget
4. Observe that the table widget can be partially outside the container widget.

### Important Details: Similar issue is observed for List and Form widget

- Version: Cloud 
- OS: MacOSX
- Browser : chrome
- Environment Release

https://www.loom.com/share/97583ca65c1b41d485ec2747ba7241d0

**Comment by ajinkyakulkarni** [comment]
A similar issue https://github.com/appsmithorg/appsmith/issues/5679
