### ISSUE TITLE
[Bug]collab->Overlapping of the comment icon should not be allowed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4996]
[What happened]

Overlapping of the comment icon should not be allowed

Steps:

1. Create new application
2. Click on comment mode
3. drop a comment and add the comment
4. Now try to drop the comment on the previous added comment

When the user  drag and drop the 2 comment icon It should not Overlap on each other as in screenshot
![image](https://user-images.githubusercontent.com/45958978/121342334-283ad900-c93f-11eb-9283-3b3382d1e187.png)

### Important Details

- Version: Cloud
- OS: Window
- Browser Chrome
- Environment  release

**Comment by pranavkanade** [comment]
Nikhil's opinion on this -
> I think overlap is fine so long as we support movement of the pin

Closing this issue as the draggable pins feature is already in release. https://github.com/appsmithorg/appsmith/pull/6742
