### ISSUE TITLE
[Bug]The comments icon Added outside the widget(pointed to the widget) doesn't move when the user Drag and drop the widget in different location

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4997]
[What happened]

The comments icon Added outside the widget(pointed to the widget) doesn't move when the user Drag and drop the widget in different location
Steps:

1. Create new application
2. Click on comment mode
3. drop a comment and add the comment
4. Now try to drop the comment on the previous added comment

When the comment icon are added  near the widget Pointing to the widget but not inside the widget now drag the widget and place it in different position now the comment icon outside the widget which was pointing to widget wont be moving along with it
![image](https://user-images.githubusercontent.com/45958978/121343974-db580200-c940-11eb-8741-1d7d25da4278.png)

### Important Details

- Version: Cloud
- OS: Window
- Browser Chrome
- Environment  release

**Comment by rishabhsaxena** [comment]
@RakshaKShetty think we can close it for now, we can address this later if users request for this feature.
