### ISSUE TITLE
[Bug] Mongo datasource test results are incorrect

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#5005]
When trying to test a Mongo db datasource, the result is shown as a success even when should not be considered successful. A failing case would be one in which we assign the authentication database incorrectly. The check, however, still passes.

**Comment by ajinkyakulkarni** [comment]
@nidhi-nair @arunvjn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5005?planning-poker)

**Comment by trishaanand** [comment]
Need to investigate a better command which all db users would have access to, to ascertain if the connection can be established. I would reckon that this is not a Good First Issue.

**Comment by leotom2000** [comment]
Below are few scenarios analysed and we need to discuss it those need to be fixed.

 
![image](https://user-images.githubusercontent.com/8027694/147561027-8dbf432b-b415-4b60-bdde-d1f3653b49fc.png)

**Comment by mojtab23** [comment]
> Below are few scenarios analysed and we need to discuss if those need to be fixed.
> 
> ![image](https://user-images.githubusercontent.com/8027694/147561607-1b0799be-6cd1-42ac-af26-9330014ba44c.png)

For item number 8, in mongoPlugin `testDatasource()`s code we explicitly ignore the unauthorized error that comes from MongoDB, because we call an admin-level query that might fail even if the user has access to a certain _non-system_ collection or database. But in this case, if the user enters invalid credentials it should show an unauthorized error but we are ignoring that and show OK. 
We can get a list of collections of the _default database_ in case of unauthorized error and then show the datasource test result.

**Comment by mojtab23** [comment]
> Below are few scenarios analysed and we need to discuss if those need to be fixed.
> 
> ![image](https://user-images.githubusercontent.com/8027694/147561607-1b0799be-6cd1-42ac-af26-9330014ba44c.png)

This PR https://github.com/appsmithorg/appsmith/pull/11124 tries to solve number 8 in the list.

**Comment by mojtab23** [comment]
Didn't see item 6 when tested again. I think https://github.com/appsmithorg/appsmith/pull/11124 also resolved this one.

> ![image](https://user-images.githubusercontent.com/8027694/147561607-1b0799be-6cd1-42ac-af26-9330014ba44c.png)

**Comment by mojtab23** [comment]
> Below are a few scenarios analyzed and we need to discuss if those need to be fixed.
> 
> ![image](https://user-images.githubusercontent.com/8027694/147561607-1b0799be-6cd1-42ac-af26-9330014ba44c.png)

This PR https://github.com/appsmithorg/appsmith/pull/11238 fixes item number 4 of this list, and after this PR is bing accepted we can close this issue.
