### ISSUE TITLE
[FEATURE] Enable selection of multiple rows in Table

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#501]
## Summary

A user needs the option to select multiple rows in a table widget and perform an action on the rows selected.

## Motivation

The reason a multi select dropdown doesn't work for the user is because the table data is fragmented and the users of the application need to look at a combination of columns in order to make a decision as to which rows should be acted upon

**Comment by mohammadnajmuzzaman** [comment]
Would love this feature 😍

**Comment by Nikhil-Nandagopal** [comment]
@mohammadnajmuzzaman this feature has been deployed! Check it out and let us know your feedback 😃
