### ISSUE TITLE
Context Menu for selected widgets

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#5013]
- [x] show selected widgets with context menu for actions
- [x] highlight selected widgets by showing a border around them
- [x] enable existing bulk operations implemented(Cut/Copy/Paste)

https://www.figma.com/file/okCgRwbn6qazHVLmh7MGnU/Widget-Grouping?node-id=665%3A574

**Comment by vivekverma2312** [comment]
@jsartisan Issues:
Container [issue 1-4]: https://www.loom.com/share/1f3c44bfe2a94f4c8cb3cca97cdca121
1. Cut/copy is still not consistent
2. Multiple drawing box after drawing box and scroll
3. Multiple context menu after copy/paste
4. Bound box is displayed outside the container widget if one widget is selected then scroll and then select another widget https://www.loom.com/share/24fe1c26f1e047b19708bd28586c84b4
5. In form widget horizontal scroll is created when widgets are in corner to show context menu but it is not visible by default
6. Also when we shift + click can we restrict property pane to open as it makes selecting very difficult in many cases
Form: https://www.loom.com/share/40653f30b23945c1bf903977cccb649f
