### ISSUE TITLE
[Feature] Enable Server Side Filtering on Dropdown Menu

### ISSUE THREAD

**Issue by zdb999** [appsmithorg/appsmith#5018]
It would be great if you could filter an Appsmith drop-down menu on the server side. I want to be able to select an item out of a list that will eventually include tens of thousands of options, and a drop-down is a much more natural way to do this than using a full table for selections (my current workaround.)

Ideally, the user would type in the drop-down's search box to filter the values and the application would send an updated DB query with the new filter, just like with paginated tables. I believe this would only require exposing the current value of the search box as a property, and firing an event with every change in it's value.

**Comment by Nikhil-Nandagopal** [comment]
@zdb999 thank you for the feature request! This is a pretty interesting idea.
@somangshu could you have a look at this?

**Comment by zdb999** [comment]
I think this is close but not quite what I have in mind. The current drop down widget has an integrated auto-complete search box that works perfectly right now for static client side drop downs. I just would like to be able to move the filtering to the server side when it makes sense, by getting access to the value of that search box and its change event.

Are you suggesting I use a separate input widget as a filter, distinct from the drop down's integrated search box? This would work, but it would be very bad user experience in my view. There would then be two independent filter boxes, one acting on the client side and one on the server. Also, the drop down would close when you are using the input widget.

**Comment by somangshu** [comment]
@zdb999 that not what I was suggesting. I didn't convey it really well. An Example of what I was suggesting is [here](https://material-ui.com/components/autocomplete/#country-select), This will be a separate widget and will let you connect to server APIs as well. 

Right now we are in the process of making a decision to separate the multi-select widget completely, And I will make sure that this point is taken into consideration. Let me know if you have any feedback on this.

**Comment by zdb999** [comment]
Ahh, yes, that makes a lot more sense. I think I may not have been using the most standard terminology either, which added to the confusion.

Thanks for taking this into consideration!

**Comment by zdb999** [comment]
Just to clarify, I like the way the widget works right now, I would just like more hooks for it.

**Comment by somangshu** [comment]
@Tooluloope note:
- We will introduce an internal property/API `filterText` which can be used to asynchronously load data. 
- A toggle `server side filtering` is required in the select/multiselect widget.
- Enabling this should enable action `onFilterUpdate` which can call the same API used in options data.
