### ISSUE TITLE
[Bug] Default option becomes inactive when the user moves from single select to multi-select and vice versa

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5022]
Steps to reproduce:
1) Add a select widget
2) Select "Selection Type" as a Single 
3) Add a "Default option"
4) now observe the widget the default option is displayed 
5) Click to open the property pane 
6) Select "Selection Type" as a Multiple 
and observe 

Observation :
we observe that the default option must be redefined and does not pull data that is already defined 

Expectation:
It is expected that the already defined data must be displayed to a user.

**Comment by YogeshJayaseelan** [comment]
@Tooluloope This feature has been separated into two widgets (Select , Multi-select) so this bug does not exists and hence closing this
