### ISSUE TITLE
[Bug] Debugger errors keep linking to an old error

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5028]
## Description
As a workflow to fix errors, I would keep the debugger open and keep resolving errors, during this I noticed that the deep liking to the entity is broken and keeps pointing to an old entity that has already been resolved

### Steps to reproduce the behaviour:

https://user-images.githubusercontent.com/12022471/121496091-c7230c00-c9f7-11eb-9b1a-6699af683f03.mov

**Comment by akash-codemonk** [comment]
This doesn't seem to be happening anymore.
