### ISSUE TITLE
[Enhancement] In Application Page -when the user scroll to a specific org the org name should be highlighted in the create organization section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5036]
## Description

[Bug]In Application Page -when the user scroll to a specific org the org name should be highlighted in the create organization section

### Steps to reproduce the behaviour:

1. Go to home page
2. Scroll down to application which is at the bottom
4. now verify the org highlight on the left pane (under create org section)

Actual result:
In Application Page -when the user scroll to a specific org the org name is not highlighted in the create organization section
expected result:
In Application Page -when the user scroll to a specific org the org name should be highlighted in the create organization section

if you see the screenshot the user is in Raksha App org but in left pane the org name is not highlighted
![Uploading image.png…]()

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by Alcadeus0** [comment]
Hi, i'd like to work on this

**Comment by pranay-0512** [comment]
Can anyone tell me where exactly do I locate this issue. I can't seem to find it

**Comment by git-sumana** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Highlight Organization Name</title>
<style>
  .highlighted {
    background-color: yellow;
  }
</style>
</head>
<body>

<div id="organizationList">
  <h2>Organizations</h2>
  <ul>
    <li id="org1">Organization 1</li>
    <li id="org2">Organization 2</li>
    <li id="org3">Organization 3</li>
  </ul>
</div>

<div id="createOrganization">
  <h2>Create Organization</h2>
  <form>
    <label for="orgName">Organization Name:</label>
    <input type="text" id="orgName" name="orgName">
    <button type="submit">Create</button>
  </form>
</div>

<script>
window.addEventListener('scroll', function() {
  var orgList = document.getElementById('organizationList');
  var createOrgSection = document.getElementById('createOrganization');
  var orgs = orgList.getElementsByTagName('li');

  for (var i = 0; i < orgs.length; i++) {
    var org = orgs[i];
    var orgRect = org.getBoundingClientRect();

    if (orgRect.top >= 0 && orgRect.bottom <= window.innerHeight) {
      var orgNameInput = document.getElementById('orgName');
      orgNameInput.value = org.textContent;
      org.classList.add('highlighted');
    } else {
      org.classList.remove('highlighted');
    }
  }
});
</script>

</body>
</html>

**Comment by Nikhil-Nandagopal** [comment]
No longer valid
