### ISSUE TITLE
[Perf]  Optimize switching between empty code editors

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#5046]
Switching between two CodeEditors is quick. But if you try switching between two empty CodeEditors, the whole thing gets much slower

Sometimes, to render an empty CodeEditor, we pass it the value of undefined.  That works mostly fine – except for handleChange, where we’re comparing this.props.input.value with this.editor.getValue() and failing the equality check.
And because
this.props.input.value // undefined
!==
this.editor.getValue() // ""
we end up calling this.props.onChange() and recalculating the whole app data tree.

solution here is to flatten the this.props.input object (which only has two fields: onChange and value) and use defaultProps:
```
<CodeEditor
  // Before
  input={{
    onChange: onChange,
    value: value,
  }}
  // After
  onChange={onChange}
  value={value}
/>;
// and...
class CodeEditor extends Component {
  defaultProps = {
    value: "",
  };
}
```
This way, we won’t need to remember to add || "" every time (and, thus, prevent similar issues in the future).

**Comment by rahulramesha** [comment]
@SatishGandham Tried flattening the props but that in the end created some more issues, current solution without flattened props with just checks looks like the best solution.
Closing this.
