### ISSUE TITLE
[Bug] Meta properties associated with default properties do not update

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#5052]
## Description

When updating a default property, the associated meta property in the store does not change, resulting in the derived properties based on the meta properties in question not updating.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Add a datepicker widget
2. Add a text widget and bind it to `{{Datepicker1.selectedDate}}`
3. Update the default date of the datepicker widget
4. Clear the datepicker value from the widget
5. The text widget's text does not clear out

### Important Details

- Version: 1.5.3.2

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno this seems to be working now!
