### ISSUE TITLE
Full regression of all widget Properties

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#5068]

**Comment by somangshu** [comment]
@vivekverma2312 what is the update on this

**Comment by vivekverma2312** [comment]
@somangshu Widget validation structure is tested and in release now, we will be testing this as part of regression on release-frozen now. Can we close this issues.

**Comment by somangshu** [comment]
I will leave that you totally, If you are keeping a track of this separately, Please go ahead and close it
