### ISSUE TITLE
[Bug] Curl Import button goes out of Curl window in minimized mode

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5078]
## Description
Release Frozen - Curl - Its is observed that when the screen window is minimised to 70-80% the import button goes out of the curl window

**Expected result:**
Import button should be visible within curl window 

**Actual result:**
When the screen is minimised to 70-80% the import button goes out of curl window

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the Release Frozen Environment 
2. Expand API
3. Click on Curl 
4. Minimise the screen to 70-80% and observe the Import button

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release Frozen]
<img width="1280" alt="Screenshot 2021-06-11 at 9 13 46 AM" src="https://user-images.githubusercontent.com/35128442/121700105-30d11200-caed-11eb-83e5-0048fb5d36a6.png">

**Comment by hetunandu** [comment]
Not able to reproduce @YogeshJayaseelan

**Comment by prapullac** [comment]
@hetunandu  not able to reproduce as the import icon is inside the pane
