### ISSUE TITLE
[Bug] Video widget do not resize under the canvas on changing view mode

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5079]
### Steps to reproduce the behaviour:

1. Drag and drop video widget on canvas
2. Now change the view mode 
3. Observe that the video widget do not resize to fit inside the canvas
4. Post deployment it works fine.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

https://www.loom.com/share/50825475a3014feea249bbf3e9657363

**Comment by somangshu** [comment]
@vivekverma2312 this issue is to do with fluid width of widgets based on the canvas viewport. Today Appsmith is not compatible to do so.
