### ISSUE TITLE
[Feature] ./install.sh does not detect Docker in WSL2

### ISSUE THREAD

**Issue by ageofabenius** [appsmithorg/appsmith#5084]
## Description

When running ./install.sh in WSL2, the check `if ! sudo systemctl is-active docker.service > /dev/null` does not work as WSL2 does not include systemd.  A solution would be to use the check `if docker info > /dev/null 2>&1` when running in WSL2 instead.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Run ./install.sh in WSL2

### Important Details

- OS: WSL2 running on Windows 10

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 can opt it pick this up?

**Comment by Nikhil-Nandagopal** [comment]
This is now solved :)
