### ISSUE TITLE
z-index issues related to comments

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5100]

**Comment by pranavkanade** [comment]
Observed issues related to pins -

- [ ] Pins at the edges
- [ ] New comment pins should be on top of old comment pins
- [ ] Unpublished comment pin is below the widget / table widget column


https://user-images.githubusercontent.com/13262095/131613053-d624afc6-0a2c-4085-9201-6e6a801f4204.mov

**Comment by marks0351** [comment]
@pranavkanade some of the CSS changes in this fix have broken Layout control.
#7195
as discussed lets revert some of the changes and think of a fix accommodating both features.

**Comment by pranavkanade** [comment]
With this PR - https://github.com/appsmithorg/appsmith/pull/7502 the bug comment pins being cut off at the top of canvas will be reintroduced. Tracking it through https://github.com/appsmithorg/appsmith/issues/7396
