### ISSUE TITLE
[Bug] Collab - few comments are missing from the app

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#5105]
## Description
Noticed one missing comment.

### Steps to reproduce the behaviour:
Originally I went through following steps.
1. Create a new application
2. Share it with 2 brand new developer accounts
3. Access the app through, dev1 account and comment.
4. Access the app through, dev2 acc. **Even before the app loads click on comment feature btn**.
5. The comment was no where to be found. After this, tried sharing with admin users, but the comment is still missing.
6. But, if I log back to dev1 acc the comment is there.

#### Original View for Dev1 (it shows comment #1)
![original-dev1](https://user-images.githubusercontent.com/13262095/121852408-12496180-cd0d-11eb-92c6-0f4960371067.png)

#### Comment view for Dev2 (comment #1 is missing here)
![missing-comment-dev2](https://user-images.githubusercontent.com/13262095/121852574-4fadef00-cd0d-11eb-8734-3703ef3acd90.png)

### Important Details

- Version: Cloud(release)
- OS: manjaro
- Browser chrome
- Environment release

**Comment by rishabhsaxena** [comment]
@nayan-rafiq Think this could be related to the comment permissions, where new users don't have permissions to view the already added comments. Please have a look.

**Comment by pranavkanade** [comment]
@nayan-rafiq when u invite a brand new user, and log in using their creds. Try clicking on comment mode btn even before the app is loaded and ready. It is what I did to re produce the problem.
