### ISSUE TITLE
[Task] Add mode field for the first_login event which is used to track invites

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#5110]
In the `AuthenticationSuccessHandler` class, we are sending an analytics event called `FIRST_LOGIN` that is sent when a user is logged in for the first time. Along with this event, we pass additional information of isFromSignup only. Can we add another key to that additional information map to identify the method of login, like form or google or github

**Comment by RakshaKShetty** [comment]
The backend actions are not getting captured in Segment app for release RC. I have tested with local instance and it is capturing backend action correctly. So we will check that backend actions are getting captured correctly once it is moved to production. it looks fine for now
