### ISSUE TITLE
[Enhancement] Keyboard "Enter" key is not functional on confirm pop up of API setting 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5111]
## Description
Steps to reproduce:
1) Add an API 
2) Use `Cmd+Enter` to run the action.
3) Navigate to Setting 
4) Check "Request confirmation before running API"
5) Run using `Cmd+Enter` and observe that the pop up appears 
6) Check that pressing the `Enter` key does not confirm the pop up.

Observation:
The `Enter` key is not functional on the confirm pop up.

Expectation:
The pop up must accept `confirm` on pressing `Enter` key.

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d8660434f17047a0bb5e2d018e4d32f1-00001.gif)](https://www.loom.com/share/d8660434f17047a0bb5e2d018e4d32f1)

## Contribution

**Guidelines**
Please read the [Code Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md) to understand the process to get started with solving a Github issue.

**How to fix**
- Map the `Enter` key to the `Confirm` button on the pop up. 

**Relevant files and methods**
- [ConfirmRunModal.tsx](https://github.com/appsmithorg/appsmith/blob/3380227cbb64097a86ab49b44a5712694927ca76/app/client/src/pages/Editor/ConfirmRunModal.tsx)
  - Please edit the `ConfirmRunModal` component to add the `onKeyDown` event to perform the same action as `onClick`.
  
**Test Cases**
- Please write a test case to simulate the `Enter` button press in [this](https://github.com/appsmithorg/appsmith/blob/09eea59330df96c2acbbefa1fcc401ff8026ee12/app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js) file.

**Comment by aditirao7** [comment]
Has this been fixed? May I work on it?

**Comment by parul5sahoo** [comment]
@prapullac hey can I work on this issue?

**Comment by sims-keshri** [comment]
Can I pick this up if it's still open? @prapullac, @sumitsum
