### ISSUE TITLE
[Bug] - Error 'The value at Config.Body is Invalid' occurs on widget debugger on executing PostgreSql query

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5113]
Description:
Release Frozen - It is observed that whenever PostgreSQL query is executed and when the user navigates to the Widget section the error 'The value at the Config.Body is Invalid' occurs on the Widget Debugger

Expected Result:
Executing PostgreSQL queries error should not occur in the Widget Debugger section

Actual Result:
The value at the Config.Body is Invalid' error occurs on widget debugger when PostgreSQL is executed

Steps to Reproduce:
1/Launch Appsmith app in release Frozen Environment 
2.Expand Database 
3.Click on Add add new datasource or any existing PostgreSQL Datasource 
4.Execute a query 
5.Navigate to Widget section and observe

VideoLink:
https://www.loom.com/share/d4b82b3f7e0d40459c6d2b451e3a63bb

Important Details
Version: [14.1 (16611.1.21.161.3)]
OS: [MacOS]
Browser [Safari]
Environment [Release Frozen]

**Comment by Nikhil-Nandagopal** [comment]
This is expected. You are looking at the canvas but not zooming into a specific widget
