### ISSUE TITLE
[Feature] Responsive Navigation Bar & Navigation Bar on Canvas

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#5116]
# Objective
There are three objectives for the new Navigation bar Version 1. In this first version, we want to allow the user to see it on the canvas and also to have new, responsive navigation. We also want to let them change some basic properties.

## Related issues
[ ] #3429 
[ ] #2282 

# Success Metrics
List of all metrics you are tracking and the desired goal.
| Goal  | Metric |
| ------------- | ------------- |
| Allowing the user to change the properties | Number of people that change the properties of the navigation widget |

# Assumptions
- Developers want to see the navigation bar in the editor
- Developers want to change the visibility of this widget in some rare occasions 

# Requirements
| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Responsive navigation bar | As a user I want the navigation for the mobile view to be different than the navigation for the desktop view | High | This should also include the edge case when there are too many pages |
| Dropdown item | As a user I want to have dropdown menu items inside my navigation | Medium |  |
| Navigation bar as a widget on the canvas with properties | As a user, I want to see my navigation in the editor and be able to edit some properties | High |  |

# Out of Scope
List the things that are out of cope or might be revisited after the first release.
- Left-side navigation
- Adding logotype 

# Developer Handoff Document in Figma
RESPONSIVE NAVIGATION: 
https://www.figma.com/file/LET3RLKRoqx03BMaQHkOu3/Responsive-navbar?node-id=0%3A1

# Questions
| Question  | Answer | Date Answered |
| ------------- | ------------- | ------------- |
| Do we let the user add their own logo? is this premium only feature? | Yes, a premium feature for now |  |
| Do we let the user to arrange the pages  | Yes | Mon 14 June 2021 |
| Do we let the user move the navigation | No, in the first version the position should not change on drag | Mon 14 June 2021 |
| Do we let the user remove the navigation bar? | Yes, but only their navigation bar, not ours with our logo. Also, they will only be able to remove it via the "Visible" option in the property pane. | Mon 14 June 2021 |

**Comment by momcilo-appsmith** [comment]
@somangshu I added the developer handoff link for the responsive navigation

**Comment by Nikhil-Nandagopal** [comment]
This seems tackled
