### ISSUE TITLE
[Feature] Support WSL2!

### ISSUE THREAD

**Issue by bharatkashyap** [appsmithorg/appsmith#5119]
## Summary

Appsmith currently doesn't support WSL2. This is prohibitive for the growing WSL community to use it and build on it/for it!

## Motivation

My own self not being able to install Appsmith, since I'm on WSL.

## Additional Context

WSL is Windows Subsystem for Linux, a newly launched capability to run Linux distributions natively inside Windows. WSL2 is the latest version of this feature and is now GA for all Windows 10 users. There is a growing community around WSL2.

**Comment by Nikhil-Nandagopal** [comment]
@bharatkashyap thank you for the issue. We do indeed need to improve our WSL2 support. Unfortunately, no one on our team has windows right now so maintaining this has been a challenge.
