### ISSUE TITLE
[Enhancement] Ability to rename an importing app right when the user is done uploading it.

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#5125]
## Summary

One of the users on discord wanted to rename his importing application right when he was done uploading it.

## Motivation

- the user had to go to the app and rename it instead which felt tedious.
- saves the user the hassle to know what the app might have been named to search and select it after uploading.

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 right after import, the user is taken to the editor where they can rename it in the top left corner.
