### ISSUE TITLE
[Bug]The user is not allowed to add the special character in there page name and widget name

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5126]
## Description

[What happened]The user is not allowed to add the special character in there page name and widget name

### Steps to reproduce the behaviour:

1. Go to Application
2. Click on Page name /Widget name
3. Try Entering Special Character /UTF 8 Character
4. Verify the display

Actual  Result: The user is not allowed to enter the Special Character

expected result: The user should be allowed to add Special Character as Page and Widget name 

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by kaushik94** [comment]
@RakshaKShetty can you please mention which utf-8 character you used in the page name? There was a solve for this issue: https://github.com/appsmithorg/appsmith/issues/2210
Thanks so much.

**Comment by RakshaKShetty** [comment]
Hi @kaushik94 I am not able to use @,$,& all these character in my page names

**Comment by kaushik94** [comment]
Understood. Working on it.

**Comment by hetunandu** [comment]
Special characters should not be allowed as discussed in #765

**Comment by mohanarpit** [comment]
For more detail, since page names & widget names are used as variables while writing JS code, we cannot allow special characters in their name. This will violate JS coding conventions.
