### ISSUE TITLE
[Bug] Modal is created inside a Modal widget on copy paste

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5128]
### Steps to reproduce the behaviour:

1. Drag and drop a modal widget
2. Copy this modal (cmd + c)
3. Click on the canvas to close first modal
4. Paste a new modal (cmd + v)
5. Not able to open second modal
6. Observe that Modal is getting created inside a modal in entity explorer

- Version: [Cloud / Self-Hosted vx.x]
- OS: MacOSX
- Browser: chrome
- Environment: production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/95284526fa944a339d8ab910164f44f5-00001.gif)](https://www.loom.com/share/95284526fa944a339d8ab910164f44f5)

**Comment by somangshu** [comment]
@vibhandikyash we will need to triage this issue. Please let me know if you figure out the problem here

**Comment by somangshu** [comment]
@rahulramesha this might be a case we cover in the copy paste exp EPIC

**Comment by rahulramesha** [comment]
Closing this as this was fixed.
@vivekverma2312, please let me know if this has to be re-openend
