### ISSUE TITLE
[Bug]"https://app.appsmith.com/applications?isFromSignup=true" Even the old user is able to fill Type form multiple time by using the URL

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5133]
## Description

[What happened]"https://app.appsmith.com/applications?isFromSignup=true" Even the old user is able to fill Type form by using the URL

### Steps to reproduce the behaviour:

1. Enter the url "https://app.appsmith.com/applications?isFromSignup=true" 
2. Verify the display

Expected Result : https://app.appsmith.com/applications?isFromSignup=true Even the old user should be redirected to application page

Actual Result: https://app.appsmith.com/applications?isFromSignup=true Even the old user is able to fill Type form by Pasting the URL

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser: Chrome
- Environment [production]

**Comment by rishabhsaxena** [comment]
Closing this since I feel it's an edge case and does not effect the experience a lot
