### ISSUE TITLE
[Bug] Table data is not populating when extra space inside the mustache binding

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5134]
Issues occurs when extra space is provided in mustache binding:

```
{{
currentRow.dob == null ? "no birth" : moment(currentRow.dob).add(24, "years") < moment() ? "small" : moment(currentRow.dob).add(18, "years") < moment() ? "very small" : "very very small"
}}
```
Worked fine for:
`{{currentRow.dob == null ? "no birth" : moment(currentRow.dob).add(24, "years") < moment() ? "small" : moment(currentRow.dob).add(18, "years") < moment() ? "very small" : "very very small"}}
`

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

**Comment by somangshu** [comment]
@hetunandu can you please list out the dependency here, What is pending right now, do we need some help from the UI building pod?

**Comment by hetunandu** [comment]
I was expecting the UI building pod to work on it since the change would also need migrations. Pasting the previous response here

> This seems to happen only for column properties. The reason for this is that there is a map function under the hood to enable "currentRow". When a \n is added that the beginning of the binding, it makes it invalid. Same problem occurs in List widget child widget's properties
The template today is:
```Table1.sanatizedTableData.map((currentRow) => { return currentRow.abc })```
If we add a enter here, the js becomes invalid (cant have \n after return
```Table1.sanatizedTableData.map((currentRow) => { return 
currentRow.abc })```
One solution is to make the template as this
```Table1.sanatizedTableData.map((currentRow) => currentRow.abc )```
I tried this and it works.

> I have created a branch with changes to Table widget. List widget is still not handled in this. Also we will need to migrate old DSLs
fix/new-line-in-start-of-binding
