### ISSUE TITLE
[Bug]-[134]:"Add" option in the entity explorer does not display templates

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5137]
Steps to reproduce:
1) Navigate to Firebase DB 
2) Establish a connection
3) Navigate to the 
![Screenshot 2021-06-15 at 6 07 21 PM](https://user-images.githubusercontent.com/71753653/122053707-9df1e980-ce04-11eb-8a87-1c78656144f9.png)
application
4) Navigate to Entity explorer
5) Hover the ADD option next to the DB
and observe 

Observation:
It is observed the template is not added to the add options 

Expectation:
A template related to the DB must be added to the option

**Comment by nidhi-nair** [comment]
Closing this as verified @Irongade

**Comment by st-trade** [comment]
Have this issue

**Comment by rohan-arthur** [comment]
still reproducible, see video
https://images.zenhubusercontent.com/275993885/6738b488-a579-48b3-bb11-24949e53f3d0/screen_recording_2022_06_05_at_10_32_51.mov

**Comment by rohan-arthur** [comment]
Firestore 6m usage: 334
assume 1/5 users use this feature: 67

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 67 |
| Effort (months)  | <<number>> |

**Comment by chinmoykalita** [comment]
@Nikhil-Nandagopal, is someone working on this issue?

**Comment by rohan-arthur** [comment]
closing this issue as we have sunset this feature
