### ISSUE TITLE
[Bug] No validation on the field of Fire base DB query

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5139]
Steps to reproduce:
1) Add a query
2) Click on the field
and observe

Observation:
User is not displayed with "Expected Value"  and on adding inappropriate data the user is not displayed with an error message

Expectation:
It is expected that the user must be displayed with "Expected Value"  along with "Evaluated Value" and an error message must be displayed when inappropriate data is added 

![Screenshot 2021-06-15 at 6 22 33 PM](https://user-images.githubusercontent.com/71753653/122055974-c975d380-ce06-11eb-8a54-0b0a33807e53.png)

**Comment by ajinkyakulkarni** [comment]
This will be worked as part of UQI.

**Comment by ayushpahwa** [comment]
Closing in favour of #5702 and #9525
