### ISSUE TITLE
[Bug] Property pane is not open by default when Modal widget is dropped on canvas

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5141]
### Steps to reproduce the behaviour:

1. Drag and drop Modal widget on canvas
2. Observe that by default property pane do not open
3. Need to click twice to open the property pane

- Version: Cloud
- OS: MacOSX
- Browser: chrome
- Environment: production

https://www.loom.com/share/ee8198a437e9483eab3e9e5af192a140

**Comment by marks0351** [comment]
this has been fixed as part of #6262
