### ISSUE TITLE
[Bug]Collab->When User delete all the comments from the application "OOPs something went wrong " page is displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5142]
## Description

[What happened]When User delete all the comments from the application "OOPs something went wrong " page is displayed

### Steps to reproduce the behaviour:

1. Go to application which has the comments added
2. delete all the comments from comments section
3. verify the display

Expected result When user delete all the comments the user should be present in the comment section

Actual result : when user delete all the comments the "oops something went wrong" page is displayed
![image](https://user-images.githubusercontent.com/45958978/122059216-07282b80-ce0a-11eb-8487-bd2ad4b69fe1.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by rishabhsaxena** [comment]
@RakshaKShetty might need your help in reproducing this
