### ISSUE TITLE
[Bug] "AND" command must be explicitly displayed to user when Multiple Where  conditions are added in Firebase DB

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5143]
Steps to reproduce:
1) Add a Firebase DB query
2) Navigate to multiple Where section
3) Add the condition
and observe

Observation:
It is observed that multiple conditions can be added but the condition (AND)is only displayed at the action point

Expectation:
It is expected that the condition can be displayed to the user explicitly as we display in the Table widget filter option

**Comment by ajinkyakulkarni** [comment]
@nidhi-nair @arunvjn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5143?planning-poker)

**Comment by ayushpahwa** [comment]
Hey @prapullac , with the new UQI changes, this is already covered. The changes will reflect as each plugin is ported to UQI.
![image](https://user-images.githubusercontent.com/8526215/144400541-eef66271-b0dd-4b4e-8b02-a9c0b1422265.png)

**Comment by sumitsum** [comment]
Closed with https://github.com/appsmithorg/appsmith/pull/9393
