### ISSUE TITLE
[Bug] Unexpected token error if no action is set for run() method on table's property

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5145]
### Steps to reproduce the behaviour:

1. Drag and drop a table widget
2. Bind with a query
3. On page change property execute DB query
4. Do not set anything on success message
5. Observe that changing page throws Unexpected error

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

<img width="312" alt="Screenshot 2021-06-15 at 7 16 13 PM" src="https://user-images.githubusercontent.com/83569920/122065271-6dfc1380-ce0f-11eb-97ce-262f692d34c7.png">

**Comment by Nikhil-Nandagopal** [comment]
@vivekverma2312 closing this as we're not able to repro it. Please open if you can
