### ISSUE TITLE
[Bug] Client goes in a redirect loop when session token is invalid

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5149]
## Description
If for some reason the session token is invalidated while the user is on an app page and then they click on the appsmith logo to go to the application list page, the client goes into a redirect loop

### Steps to reproduce the behaviour:
1. Go on any app
2. In your chrome dev tools -> application -> cookies -> delete the `SESSION` cookie
3. Click on the appsmith logo on the top left
4. App gets stuck in a redirect loop

https://user-images.githubusercontent.com/12022471/122087825-cc7ebd00-ce22-11eb-9a25-ce70b83316f4.mov

Looking at the network logs, it seems like the client keeps trying to the the application list API and despite failing (401) it keeps retrying it

### Important Details

- Version: Cloud / Self-Hosted
- Environment production

**Comment by vivekverma2312** [comment]
@rishabhsaxena After I clear the session cookies and click on appsmith logo the app crashes.

https://www.loom.com/share/356289e8cc8c44c1bc8a4feb6e88c10d
