### ISSUE TITLE
[Bug] The copied Modal is not functional 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5151]
Steps to reproduce:
1) Add a Modal 
2) Click on the Property pane 
3) Copy the modal 
4) Now try to open the modal via Entity explorer
and observe
5) Now connect the Copy modal to a button
and observe 

Observation:
it is observed that by clicking on the modal via Entity explorer the modal does not appear.
Clicking on the connected button to "On click" it is observed that the modal does not appear

Expectation:
It is expected that the modal must open 

Video:
https://www.loom.com/share/d05428bdb76745ebbe8ebb3943d719e3

**Comment by somangshu** [comment]
Closing this in favour of #5128
