### ISSUE TITLE
[Feature] Add "required" option to Rich Text Editor when used in forms

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#5161]
## Summary

When using an RTE in a form it would be nice to be able to set it to "required" so the built in form validations can be used.

## Motivation

This solves the problem where a user can submit a form without filling in an RTE that should be required.

## Additional Context

The "required" option for the RTE should look and work the same as the ones in the other form fields.

**Comment by Nikhil-Nandagopal** [comment]
@oskarannas thank you for the feature request!
@somangshu this seems like a really quick win for us to add
