### ISSUE TITLE
[Bug]When the number of users is increasing  when the user click on Share button and in the Share pop up the Application name is hidden

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5164]
## Description

[What happened]When the number of users is increasing  when the user click on Share button and in the Share pop up the Application name is hidden

### Steps to reproduce the behaviour:

1. Go to deploy page
2. click on share icon
3. there should be atleast more than 7 user with home the app has been shared already
4. now verify the display of Application name inside the pop up

Expected result : The application page name should be displayed correctly

Actual result:When the number of users is increasing  when the user click on Share button and in the Share pop up the Application name is hidden
![image](https://user-images.githubusercontent.com/45958978/122189462-925afd00-ceae-11eb-860a-02ecb95d01ee.png)

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by rishabhsaxena** [comment]
@RakshaKShetty Please verify this again. Looks fixed on release
