### ISSUE TITLE
[Bug]The comments added for the application will not be displayed when we open same app next day

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5165]
## Description

[What happened]The comments added for the application will not be displayed tomorrow(the next day)

### Steps to reproduce the behaviour:

1. Go to deploy page
2. click on comment icon
3. verify the display of the comments added for the application
4. Else click on edit button 
5. in edit window click on comment icon 
6. verify the display of comments in comment pane on the left side

Expected result : The comment added for the application should be displayed

Actual result: The comments added for the application will not be displayed tommorow

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by rishabhsaxena** [comment]
@nayan-rafiq Not sure if this is fixed. Please have a look

**Comment by nayan-rafiq** [comment]
Closed this because there another issue for the same bug: #5194
