### ISSUE TITLE
[Feature] Remove Table Head (Filter etc.)

### ISSUE THREAD

**Issue by TheMorgner** [appsmithorg/appsmith#5168]
## Summary

It should be possible to remove the header (filter/pagination...) of the table to only show data. 

## Motivation

1. Sometimes i only want to show some data or filter it with my database features. So the header is just confusing for my useres.
2. I use it to design a german programm. So my filter functions and buttons are outside the table in German Language.
3. When i use a database with 1000+ Entrys and 30 fields per entry (my phonebook) Appsmith just gets slow when loading all data and use the table filter functions. Veeeerrryyy slow.

## Additional Context

Just wanna say Appsmith is totally great!!!!

**Comment by Nikhil-Nandagopal** [comment]
@TheMorgner thank you for the feature request! I believe we have this in the pipeline here #2111 
I'm closing this in favor of that but you can track it there to know when it will be released!

**Comment by areyabhishek** [comment]
@TheMorgner We've released this feature. You can control the buttons that appear in the property pane. Please try it out. 
<img width="1116" alt="Screen Shot 2021-06-24 at 1 18 40 AM" src="https://user-images.githubusercontent.com/30255708/123159027-25390000-d48a-11eb-8d5b-2e6662ec42f8.png">

**Comment by TheMorgner** [comment]
Thanks. You are great

abhishek nayak ***@***.***> schrieb am Mi., 23. Juni 2021,
21:49:
