### ISSUE TITLE
[Bug] MongoDB queries fail after a little bit of idle time and start working after a page refresh

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#5177]
As reported from a member of our user community:

> Am having random errors like
> `The action "getPlans" has failed. ERROR: "Prematurely reached end of stream"`
> This is a DB call, so it seems like somehow, when the connection to DB is "cold" its failing. And subsequent calls are ok. 
> The "fix" appears to be a page refresh, how do I make this more stable?

The problem is with a MongoDB query and trying to use the SRV URI for configuring the datasource instead of the form didn't seem to help. The error still shows up once in a while.

### Important Details

- Version: Self Hosted
- OS: ?
- Browser: ?

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand @nidhi-nair can someone help here?

**Comment by trishaanand** [comment]
@sharat87 has reached out to the user requesting for a call for the same to debug this issue.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand @sharat87 is there an update here?

**Comment by prapullac** [comment]
Hi 
Got clarity from @trishaanand that this does not have exact steps reproduce hence would wait on the customer to verify the details.
Not adding the label: "Verified" for the above mentioned reason 
Thank you
