### ISSUE TITLE
[Bug] When I click on "go to comment" in the email, it just takes me to the applications page

### ISSUE THREAD

**Issue by kaushik94** [appsmithorg/appsmith#5178]
## Description

[What happened] Clicking on `go to comment` just takes me to the applications page. Expected to land on the comment.

### Steps to reproduce the behavior:

1. Go to email
2. Click on 'go to comment'
<img width="1195" alt="Screenshot 2021-06-16 at 7 01 17 PM" src="https://user-images.githubusercontent.com/6545467/122228217-42dbf780-ced5-11eb-826b-66993d9e06f9.png">

3. Lands on applications page

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

**Comment by rishabhsaxena** [comment]
Comment links are working on email notifications on prod
