### ISSUE TITLE
[FEATURE] SSH Tunnel for Database connections (MySQL)

### ISSUE THREAD

**Issue by akbansa** [appsmithorg/appsmith#518]
## Summary

I believe you guys must have SSH Tunnel support to connect to a database (for MySQL).

## Motivation

Most of the companies have their production database behind a server. So providing an SSH tunnel will enable those users to use the platform with confidence and not compromising on security.

Update:
Related: https://github.com/appsmithorg/appsmith/issues/24030

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_62qdo)

**Comment by Nikhil-Nandagopal** [comment]
@akbansa Thanks for the feature request! I believe we do support this feature today. Were you having trouble accessing it? What type of database are you trying to connect to?

Here is a screenshot of our tunnel feature
![image](https://user-images.githubusercontent.com/3897254/92571308-95321d00-f2a0-11ea-9b94-b0ce0212d302.png)

**Comment by akbansa** [comment]
@Nikhil-Nandagopal Yes, it's there for PostgreSQL but not for MySQL.

Here is the screenshot for the same:
![image](https://user-images.githubusercontent.com/13042781/92574117-52724400-f2a4-11ea-8540-aa478d563c8b.png)

**Comment by Nikhil-Nandagopal** [comment]
Thanks for the update and the clarification! We'll get this prioritised and
ship this out soon

**Comment by sharat87** [comment]
Hello @akbansa, thank you for reporting this. The SSH Tunnel configuration in the Postgres datasources is a bug, since the feature is not currently supported by Appsmith. A solution to this problem is currently already being worked upon.

**Comment by Nikhil-Nandagopal** [comment]
After a bit of deliberation, we recommend anyone trying to access their db behind a VPC to [whitelist our ip](https://docs.appsmith.com/core-concepts/connecting-to-databases#database-connections)
In the meanwhile, we'll work on a slightly more involved solution to support SSH Tunnel and remove the incorrect tunnel option for other databases.

**Comment by areyabhishek** [comment]
Got another request from a friend about SSH for MySQL.

**Comment by sharat87** [comment]
@areyabhishek, I've written about this in a GitHub discussion recently (link: https://github.com/appsmithorg/appsmith/discussions/4094#discussioncomment-652646). Is there a reason they prefer to connect via SSH tunneling as opposed to whitelisting our IP for direct connections? Asking because that'll put into perspective whatever I'm missing in their use cases.

**Comment by ajinkyakulkarni** [comment]
Linking an internal discussion thread regarding this issue https://theappsmith.slack.com/archives/C01HUHMDPS9/p1622718510217300 for future reference.

**Comment by pcollellmir** [comment]
It would be basic to have this feature for my company to start using AppSmith

**Comment by marcgeldon** [comment]
What time can we expect a SSH tunnel for MySQL / MariaDB?

**Comment by rodrigoscdc** [comment]
Hello Guys do you have any update about this feature on the near roadmap of developing? This feature will be great because my Postgres and MsSql are in local server and the connections we do by ssh certificate.

**Comment by lgallego-nq** [comment]
Hi guys, any update about this feature. I'm really interested on it.
Thanks

**Comment by andredealmei** [comment]
we need this

**Comment by gabrielgarza** [comment]
We need this feature too, we can't connect to our Postgres DB unless we have SSH Tunneling. We would start using Appsmith if not for this

**Comment by daoudbahaz** [comment]
Interesting! The SSH Tunneling gives us the best security when accessing our data remotely.
I think it's a must for now.

**Comment by zackkatz** [comment]
My web host only allows database connections via a SSH tunnel. I'm trying to connect to WordPress-powered ecommerce data. This is a blocker for me to be able to use Appsmith—please add!

**Comment by danieliser** [comment]
Though this should definitely be there as most hosts block all access by default and some setups, specifically using Appsmith via docker locally might have roaming/changing IPs, so whitelisting can be tedious every time you connect.

Workaround for some users might be to create local MySQL DB and then use Airbyte, which does offer MySQL over SSH, to sync to a local DB on the same server as Appsmith or another of your choice as Airbyte is a 2 way sync tool.

Essentially you would be making your own data-warehouse, but it is a simple solution.

**Comment by nitzanav** [comment]
+1

**Comment by baender** [comment]
I agree with the others. Our SysOps-Team decided that SSH tunnel for database access is the way to go. As a developer I can not circumvent that setup, I also can not make them whiteliste an IP for direct access.

I would love to use appsmith for development but the lack of this feature prevents me from using your product.

**Comment by fahall** [comment]
Any Updates on this?

This is a blocker for my team too. Without SSH Tunneling for DB connections, we cannot use Appsmith.

**Comment by zackkatz** [comment]
@fahall Good news: @mohanarpit shared on Hacker News that they were going to bump this on the internal priority list!

https://news.ycombinator.com/item?id=35371190

**Comment by fahall** [comment]
Looks like there's now a task for this https://github.com/appsmithorg/appsmith/issues/22064. 🤞

**Comment by sumitsum** [comment]
Closing it as core changes have been merged in release.

**Comment by prerak-jain** [comment]
I still can't see SSH options while connecting to my postgres database sitting inside an isolated subnet inside a VPC. I can only connect to my database by SSHing through a bastion host.

**Comment by sumitsum** [comment]
Hi @prerak-jain the SSH tunnel feature is only implement for MySQL integration at the moment.

**Comment by prerak-jain** [comment]
Any workarounds you would suggest in case of postgres? Otherwise I can't access my the data and I am completely blocked in that case.

**Comment by sumitsum** [comment]
+ @rohan-arthur @sribalajig

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Same as @prerakhere, we can not use Appsmith until SSH Tunnel to PostgreSQL database is possible as our database is secured behind a Bastion.

**Comment by Nikhil-Nandagopal** [comment]
@andredealmei @prerakhere I've raised a feature request for this here #30792 you can leave a comment there to get it prioritised
