### ISSUE TITLE
[Bug] Evaluated Value is not displayed to user  in REDIS

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5180]
Steps to reproduce:
1) Establish a connection to Redis
2) Click on "Add Query"
3) Add a query 
and observe 

Observation:
It is observed that the Evaluated value is not displayed to the user.

Expectation:
It is expected that the evaluated value must be displayed to the user.

![Screenshot 2021-06-16 at 7 44 10 PM](https://user-images.githubusercontent.com/71753653/122235407-4c685e00-cedb-11eb-833d-23f224d04750.png)

**Comment by sumitsum** [comment]
The bug does not look valid. The action has executed as expected on Redis db server, and the Redis db server has returned a response saying that the cmd has not been properly used. It is similar to what would happen if incorrect SQL syntax was used with MySQL db. Attaching a video of test run for this cmd:


https://user-images.githubusercontent.com/1757421/122355401-7d926e00-cf6f-11eb-8bb3-c6695f11eea8.mov

Here is another video of running 5 of these conrunnetly: 

https://user-images.githubusercontent.com/1757421/122355451-88e59980-cf6f-11eb-838f-9deeaca99213.mov

reference: https://redis.io/commands/PFCOUNT
