### ISSUE TITLE
[Bug] Exporting from cloud to self hosted gives plugin not found error

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5181]
## Description
When exporting an app from the cloud instance to a self hosted instance, the plugins dont seem to get exported and hence a plugin not found error occurs

### Steps to reproduce the behaviour:

1. Export app from app.appsmith.com
2. Create a new self hosted instance
3. Import app in the new instance
4. Open the app

**Comment by codedmind** [comment]
The app in cause don't have "nothing" special it only uses api (https) access for baserow database

**Comment by abhvsn** [comment]
The issue seems to be occurring when we have APIs without datasource

**Comment by Nikhil-Nandagopal** [comment]
@abhvsn do we have a fix for this? @RakshaKShetty looks like this got missed in testing

**Comment by RakshaKShetty** [comment]
Ya @Nikhil-Nandagopal i have missed it in my testcases will add it

**Comment by abhvsn** [comment]
I'm working on the fix will push it by tomorrow.
