### ISSUE TITLE
[Feature] Select all option in multi select

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#5182]
## Summary

A user wants a select all option in a multi select widget

**Comment by Nikhil-Nandagopal** [comment]
@somangshu is it possible to get this prioritised? The user simply needs a convenience option to select all in either the multi select or the table

**Comment by somangshu** [comment]
@Nikhil-Nandagopal Currently we are working towards separating the Multiselct widget, And as soon as the initial bit of work is done related to that, Ill pick this up on priority!
