### ISSUE TITLE
[Feature]-[3000]:Support uploading a SSL CA certificate for MySQL/Postgres datasource

### ISSUE THREAD

**Issue by guillerodriguez** [appsmithorg/appsmith#5183]
## Summary

MySQL connections [already support SSL](https://docs.appsmith.com/datasource-reference/querying-mysql#ssl) but apparently don't support uploading a CA certificate chain (note that this feature **is** supported by appsmith for other DBs such as [MSSQL](https://docs.appsmith.com/datasource-reference/querying-mssql#ssl) or [RedShift](https://docs.appsmith.com/datasource-reference/querying-redshift#ssl).)

## Motivation

This is necessary in order to support self-signed server certificates.

Self-signed server certificates are commonly used with SSL connections in MySQL, and actually documented in the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-rsa-files.html).

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5abik)

**Comment by areyabhishek** [comment]
@guillerodriguez Thanks for creating an issue. We'll get to this soon.

**Comment by shubhanshusingh** [comment]
yes same applies for MongoDB as well.

**Comment by mjyoung** [comment]
Any update to this? I can't hook up appsmith to my Cloud SQL Postgres DB without this?

**Comment by RoryO** [comment]
Yes, currently it is impossible to use appsmith with Google Cloud SQL. Google only supports SSL with their own self signed certificates.

https://cloud.google.com/sql/docs/postgres/configure-ssl-instance

**Comment by mjyoung** [comment]
Only way I found around this was to use the [Cloud SQL Proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy) and install that on my VM instance

**Comment by RoryO** [comment]
Yes that will work for self hosted systems. I'd prefer to use the hosted version of Appsmith. I don't run any services or containers on my own, preferring to use hosted versions and paying vendors (and supporting OSS financially) to deal with that part. This is a blocker for us giving money to Appsmith.

**Comment by rohan-arthur** [comment]
MySQL and Mongo usage, 6m: 2000
assume 75% requirement, 1500

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1500 |
| Effort (months)  | <<number>> |

**Comment by BatHands** [comment]
+1 for Google Cloud SQL use case.

This is extremely important for enforcing security requirements on Google Cloud SQL databases. Without the ability to upload a client certificate you cannot fully enforce SSL connections from the database side itself.

**Comment by rohan-arthur** [comment]
We're currently testing this feature, and it should be out soon

**Comment by rohan-arthur** [comment]
![Screenshot 2024-05-06 at 12 54 58](https://github.com/appsmithorg/appsmith/assets/94514895/d78d0cd0-5b2f-4d73-b5e3-85986d2e8c32)
This functionality is now available for the postgres plugin. Created a new issue to track MySQL implementation: #33194
