### ISSUE TITLE
[Bug] Moving one property pane in a page affects all the property panes

### ISSUE THREAD

**Issue by kaushik94** [appsmithorg/appsmith#5184]
## Description

When I move a property pane in the canvas, other property panes also get moved to the same place.

### Steps to reproduce the behavior:

1. Go to canvas
2. Drag and drop 2-3 widgets
3. Go to any widget's property pane, grab it and drag to some other place in the canvas
4. Click on another widget's property pane. It appears in the same place.

Expected that other property panes should not be affected due to the movement of one pane

**Comment by areyabhishek** [comment]
Hey this is actually a feature, and not a bug. It's to ensure that the location of the property pane doesn't change every single time.
