### ISSUE TITLE
[BUG] Tunnel option showing for Postgres and Mongo

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#520]
## Description

SSH Tunnel options are displayed while configuring a database but they don't work as referenced in issue #518 

### Steps to reproduce the behaviour:
#518 

## Solution

Remove the option for today, direct users to [whitelist our IP](https://docs.appsmith.com/core-concepts/connecting-to-databases#database-connections) and introduce the feature as a holistic solution tracked as #518 

### Important Details
 - Version: [Cloud]
 - OS: [MacOSX]
 - Browser [chrome]

**Comment by mohanarpit** [comment]
Have removed the SSH tunnel option for Mongo and Postgres plugins. Will add these options back in the UI when the plugins implement this feature on the server-side. Reference #518
