### ISSUE TITLE
[Bug] Instead of ‘compact mode' it should be titled ‘row height' in property pane

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5201]
- Version: Cloud 
- OS: MacOSX
- Browser: chrome, safari
- Environment: production

<img width="949" alt="Screenshot 2021-06-17 at 12 50 48 PM" src="https://user-images.githubusercontent.com/83569920/122351247-94cf5c80-cf6b-11eb-86bf-a3d92c630f19.png">

<img width="357" alt="Screenshot 2021-06-17 at 3 42 22 PM" src="https://user-images.githubusercontent.com/83569920/122377407-b0922d00-cf82-11eb-81ae-510f841c6471.png">

**Comment by somangshu** [comment]
Also add `Row height` as the label on the table option header
