### ISSUE TITLE
[Feature] Allow text color to have bindings

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5235]
## Summary
Text widget's color property does not allow bindings today so you cannot set it dynamically

## Motivation
Changing text color based on API response

<img width="272" alt="Screenshot 2021-06-17 at 10 39 24 PM" src="https://user-images.githubusercontent.com/12022471/122443111-e2c08080-cfbc-11eb-9148-656826cbe931.png">

**Comment by somangshu** [comment]
Note:
- The text colour can have a js convertible binding
- Writing tests cases
- Documentation change (if any)
