### ISSUE TITLE
[Feature] Support use of client certs for MySQL connections

### ISSUE THREAD

**Issue by guillerodriguez** [appsmithorg/appsmith#5236]
## Summary

Support use of client certificates for MySQL connections.

That this feature is already supported by appsmith for other DBs such as [MSSQL](https://docs.appsmith.com/datasource-reference/querying-mssql#ssl) or [RedShift](https://docs.appsmith.com/datasource-reference/querying-redshift#ssl).

Related: #5183 

## Motivation

This allows to better protect the backend by only allowing incoming connections with valid client certificates.

**Comment by rohan-arthur** [comment]
closing this, we'll use https://github.com/appsmithorg/appsmith/issues/5183 to track this
