### ISSUE TITLE
[Bug]Table Widget - Column values are displayed even if the computed values are removed

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5240]
## Description
Release Environment - Table Widget - It is observed that the column values are displayed and accessible even if the computed values are removed

**Expected Result:**
Computed values are the actual values that are displayed to any specific columns and without computed value the column value should not be displayed

**Actual Result:**
Column values are displayed even if the computed values are removed

### Steps to reproduce the behaviour:

1. Launch appsmith app in the release Environment 
2. Drag and Drop Table Widget 
3. Click on property pane and click on setting icon on any of the column
4. Ensure by default the computed values will be displayed 
5. Remove the computed values and observe 

**VideoLink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/856161573a314cce90cf1535566af4f4-00001.gif)](https://www.loom.com/share/856161573a314cce90cf1535566af4f4)

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release]

**Comment by somangshu** [comment]
@YogeshJayaseelan this is the default behaviour, The computed value will remain in the table until another expression is given. Same goes for the table widget header, you will see that persists even when you remove the table data. 

@riodeuno please correct me here if I am wrong. If you agree please close the issues

**Comment by sbalaji1192** [comment]
When the computed value is empty we just take the values from the tableData. Do we need to change the behavior to show empty cells when computedValue is empty?

**Comment by riodeuno** [comment]
@sbalaji1192 Yes, IMO, the integrity of the data configured, should be maintained. 

In this scenario: This means that if the URLs of the entries are not configured, then the click should like to an empty page/tab.

**Comment by Nikhil-Nandagopal** [comment]
Closing because it's too outdated
