### ISSUE TITLE
[Bug] Deploy Preview - List widget - On overlapping of items and outer border it is observed that there is no smooth movement back separating them

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5241]
## Description
Deploy Preview - List Widget - It is observed that On overlapping of items and outer border it is observed that there is no smooth movement back separating them

**Expected Result:**
When the item container is dragged below the pagination section and after that it should be smoother to separate item container with the list widget container 

**Actual Result:**
If the item container are dragged beyond list widget container it is difficult to bring back the item container 

### Steps to reproduce the behaviour:
1.Launch Appmsith app in the Deploy preview - https://deploy-preview-4189--appsmith-editor-ce.netlify.app/
2.Drag and Drop list widget 
3.Select any item container 
4.Drag the item container beyond pagination area
5.Try to pull back the item container and observe

**Videolink:**
https://www.loom.com/share/79fa2896884242fbbef2da7029917c00

### Important Details
Version: [14.1 (16611.1.21.161.3)]
OS: [MacOS]
Browser [Safari]
Environment [Deploy Preview]

**Comment by jsartisan** [comment]
Closing this one as well as it was related to #5259. There is a limit on the height of the item container.
