### ISSUE TITLE
[Bug] DB queries are not triggering on page-load while navigating between pages in editor mode

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#5247]
## Description

DB queries are not triggering on page-load while navigating between pages in editor mode

https://www.loom.com/share/f7088c16a2164abc8d4934d3946028c6

### Steps to reproduce the behaviour:

1. Create Two pages
2. On `Page Two`, use a table widget and bind any data with a DB query and set on-page load to true
3. On `Page One` use a button and set the on-click property to navigate to "Page 2"
4. Now, from `Page One` click the button in edit mode; this will take you to page 2 but not run the DB Query
5. The same thing works well in View Mode (after Deployed)

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment production

**Comment by aswathkk** [comment]
Looks like the `EXECUTE_PAGE_LOAD_ACTIONS` are not getting dispatched in the Editor UI on page load.
I would like to raise a PR that will resolve this issue.

**Comment by ajinkyakulkarni** [comment]
This issue is also happening for APIs as well. A user on [Discord](https://discord.com/channels/725602949748752515/760761686549463060/859425233454628885) reported the same problem where when navigated to another page using navigateTo(), the APIs were not called/refreshed automatically.

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni @hetunandu This is important for our generate app project so can we get this prioritised?
