### ISSUE TITLE
[Bug] No error message is displayed in the connection sections 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5253]
Steps to reproduce:
1) Navigate to Snowflakes DB
2) Add inappropriate Schema or DB name wrt to Warehouse 
3) Click on "Test" button
and observe

Observation:
It is observed that no message is displayed to the user indicating why the test execution failed.

Expectation:
It is expected that the user must be displayed with an error message for a better understanding of the error.

**Comment by ajinkyakulkarni** [comment]
@nidhi-nair @arunvjn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5253?planning-poker)
