### ISSUE TITLE
[Bug] On lengthy Dropdowns in the table filter is not scrollable 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5254]
Steps to reproduce:
1) Add a Query with many columns
2) Bind the Query to the Table
3) Now click on the Filter option 
and observe

Observation:
It is observed that the List is not scrollable and make it difficult to  select the topmost or bottom most criteria

Expectation:
It is expected that making the filter scrollable
![Screenshot 2021-06-18 at 3 24 17 PM](https://user-images.githubusercontent.com/71753653/122544228-3d53ee00-d04a-11eb-8458-39cc3df3d732.png)

**Comment by somangshu** [comment]
The fix here is to give a `max-height` to the  visible popper
