### ISSUE TITLE
[Bug] Tabs Widget's selectedTab is not populated in time for onPageLoad in view mode

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5255]
## Description
If you have a onPageLoad Api that needs the TabWidget selectedTab value, it works sometimes in edit mode but fails always in view mode

### Steps to reproduce the behaviour:

1. Create a Tab widget with a default selected tab
2. Create an API to read from the `TabWidget.selectedTab` property and set it onPageLoad
3. Deploy and check in view mode
4. The value is not evaluated in time and fails the API

### Important Details
- Environment: Production

**Comment by hetunandu** [comment]
With a cursory view, I noticed that selectedTab is a derived property that depends on selectedTabWidgetId. selectedTabWidgetId does not have a default property assigned directly and is updated via the widget. This is causing the evaluation for the property to take time

**Comment by areyabhishek** [comment]
@hetunandu Is this a critical or a high issue?

**Comment by somangshu** [comment]
@hetunandu any probable solutions here from the widgets point of view?

**Comment by hetunandu** [comment]
@areyabhishek @somangshu I think the problem stems from the UX of Tabs widget property pane. We want the user to write a Tab Name as a default value but the widget really wants a TabWidgetId. To combat this, the widget does the calculation once loaded but that is too late and the onPageLoad already has run by this time. This in turn makes the user confused about why it did not run and they need to add some default value in their bindings of the action like `{{ Tab.selectedTab || "myDefaultTab" }}` to get it to work as expected.

**Comment by vibhandikyash** [comment]
@hetunandu I am facing issue reproducing this issue. Can you please create a screen recoding and put it here so I can follow in the same steps?
