### ISSUE TITLE
[Bug] Able to drag the list widget when cursor is below the actual widget area

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5259]
## Description: I am able to drag the list widget even before the cursor reaches the widget from bottom. Cursor also changes way before the cursor reaches the widget outer container.

Expected Behaviour : Drag for widget should only be allowed when cursor is on widget and not near to the widget

https://www.loom.com/share/ff88c99f4392485ab0268df699ff9800

**Comment by jsartisan** [comment]
Closing this one because it is very hard to make the item container beyond the pagination area.
