### ISSUE TITLE
[Bug] Column definition gets truncated while copying a table

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5279]
## Description

[What happened]

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a new table and bind a query with data
2. Copy `ctrl/cmd+c` and paste it `ctrl/cmd+v`
3. Data is missing from some columns
4. On checking the column definition, it seems the column definition is truncated to for example:`{{entRow.tag}}`

![image](https://user-images.githubusercontent.com/1944800/122735031-44723a80-d29c-11eb-9d87-1fbea9965604.png)

### Related info
```
Interestingly in another column I'm using currentRow twice and only the first one is truncated
```

**Comment by somangshu** [comment]
@vicky-primathon please triage this and see if you find something.

**Comment by vicky-primathon** [comment]
Sure, @somangshu

**Comment by vicky-primathon** [comment]
@somangshu  The computable value of columns in DSL of new table (copy table) is correct. But we are passing widgetName instead of widgetId to getInputComputedValue function when computing the value of input field. Thus few unknown letters are getting truncated.
