### ISSUE TITLE
[Bug] File picker keeps in loading state when File select property is set

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5287]
### Steps to reproduce the behaviour:

1. Drag and drop file picker widget
2. Set "On file selected property"
3. Now try uploading the file
4. Observe that after upload the loader on the widget keeps in loading state

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

https://www.loom.com/share/dcc6387e38e24a80a243de0439e798c2

**Comment by somangshu** [comment]
@vivekverma2312 does the file get uploaded regardless of the loader?

**Comment by vivekverma2312** [comment]
@somangshu Yes the files are getting loaded but the loader keeps in loading state. Due to this the file picker widget becomes disable for 2nd upload.
