### ISSUE TITLE
[ESLINT] Client ES Linting error Fixes for rule 'jsx-no-bind' in the Comments related files

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#5288]
ESLint Rule "react/jsx-no-bind" needs to be added to the client-side codebase to potentially decrease unnecessary Re-renders and improve performance.

As part of that Effort, this issue is created to track the progress of the rule related fixes in the following folders,
- appsmith/app/client/src/comments/

**Comment by rahulramesha** [comment]
LintCount: 34

**Comment by mohanarpit** [comment]
@rahulramesha How are these issues being created? Is it an automated static code analysis tool creating these issues? If not, I'd recommend adding more details to the issue description and giving the issue a better title that can be understood easily. Right now, I don't really understand the problem by simply looking at the issue.

**Comment by rahulramesha** [comment]
Hey @mohanarpit, I was breaking down an epic to help work and track the ESlint fixes because of the number of files that needed modifying.
It's my bad, I created the issues in zenhub and didn't anticipate how it will look like on Github. I'll add proper descriptions and change the titles to help understand the issues better.

**Comment by riodeuno** [comment]
No picking this up right now.
