### ISSUE TITLE
[EPIC]-[8000]:Widget Discovery

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#5296]
# Problem statements
Developers find it difficult to find a way to add UI widgets and discover all the widgets in Appsmith.

# Objectives
1. Make it easy for Appsmith users to discover and access UI widgets.
2. Create a system to show widgets that is extendible for the future
3. Enable easy access to the most commonly used widgets
4. Introduce keyboard shortcuts to find and add widgets

# Success Metrics
List of all metrics you are tracking and the desired goal.
| Goal  | Metric |
| ------------- | ------------- |
| First-time users immediately understand how to add new widgets  | Activation rate goes up  |
| Repeat users find it easy to discover and explore widgets  | Improves Ui creation speed by 20% |
| Repeat users Appsmith quicker to use than competing products  | Satisfaction rating goes up ​|

# Assumptions
List any assumptions that you have about your users, technical constraints, or business goals (e.g., Most users will access this feature from a tablet).

- Users will mostly use 5 widgets repeatedly
- Keyboard shortcuts 
- Design will work even for 50+ widgets

# Requirements
| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Trigger to add widgets has to be prominent  | Users shouldn't have to scan or hunt for the add button  | High  |  |
| User should be able to see preview of widgets | Users sometimes don't understand what a rarely used widget does till they drop it on the canvas  | High  |  |
| Top toolbar or navbar should be compact  | Vertical space is rare for users on small screens, so any solution should ensure the canvas space is vast| High  |  |
| A way of closing the widget pane | Returning to the entity explorer should be easy | High  |  |
| A small toolbar to show high-frequency widgets | Users shouldn't have to scan or hunt for the add button  | High  | Text, Input, Table, List, Container, Button |
| Show a preview of each widget | Either a hi-fi image or gif | Medium  |  |
| The toolbar should be contextual to the canvas and disappear when the user is on API/datasources/DB query | App name, Appsmith logo, edit/comment/preview mode, CMD+K, help icon(?), icons of live users, save icon, invite, deploy, etc. | High  |  |
| New widgets can be tagged with a label/pill | Medium  |  |
| Keyboard shortcuts for major actions | Display these shortcuts at the appropriate time | Medium  |  |
| Ability to add or remove shortcuts from the toolbar | Easy one click way to edit the toolbar | Low  |  |
| Show the last used widget | To let a user access a widget if they deleted the first one | Low  |  |

# Additional notes
- Display widget in 2 columns
- Add sorting by categorisation of widget
- Add colour coding
- 
# Optional
- Canvas redesign for the addition of pages
- Addition of APIs/Datasources/JS files

# Out of Scope
List the things that are out of cope or might be revisited after the first release.
- Entity explorer redesign
- Property pane redesign
- Show menu of shortcuts

# Developer Handoff Document in Figma
Link to the developer Handoff Document: 

# Questions
| Question  | Answer | Date Answered |
| ------------- | ------------- | ------------- |
| e.g. How might we ensure that the comments section doesn't cover the canvas | Content Cell  | Content Cell  |

**Comment by momcilo-appsmith** [comment]
@areyabhishek only two things that I would add in the requirements under low or medium are:
* the ability to add/remove tools from the toolbar
* the last used tool

**Comment by Nikhil-Nandagopal** [comment]
Related issue #3949

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 8000 |
| Effort (months)  | 2|
