### ISSUE TITLE
[Bug]Release frozen ->In application page ->click on ? icon ->when user click on Chart with us it is redirected to 404 error

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5306]
## Description

[What happened]In application page ->click on ? icon ->when user click on Chart with us it is redirected to 404 error

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to application page 
2. Click on ? icon
3. click on chart with us
4. verify the display

Expected result: When the user click on chart with us menu the Bot should open 
![image](https://user-images.githubusercontent.com/45958978/122773460-012cc180-d2c6-11eb-91fb-4640a055c26a.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment release frozen

**Comment by sharat87** [comment]
I see that the `Chat with us` item is pointing to the discussions page directly, for non-cloud installations. We've recently disabled discussions on our repository so this shows a 404 now. We've moved to a Discourse forum available at <https://community.appsmith.com>. For our cloud installation (app.appsmith.com), this instead works to invoke Intercom.

From this situation, how about we add another link saying `Forums` or `Join our forums` or some such, just above the `Join our Discord` which points to https://community.appsmith.com, and the `Chat with us` item just won't be there at all, if Intercom is not available. This way, we have a link to our Forums as well as Intercom on our cloud instance. I don't see a reason to not link to our forum site when Intercom is available. What say @somangshu?
