### ISSUE TITLE
[Bug]Release Frozen->In Radio button widget->the Autocomplete is not working as expected the value is missing

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5307]
[What happened]In Canvas->the Autocomplete is not working inside the mustache for binding

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to widgets 
2. drag and drop any widget
3. try to bind a db query/API
4. validate the autocomplete

Expected result: The auto complete should work as expected
In the below screenshot if you check we are binding the Query for radio button but for the gender auto complete is not working

![image](https://user-images.githubusercontent.com/45958978/122774189-9d56c880-d2c6-11eb-894c-6192052c7867.png)

Screencast: https://drive.google.com/file/d/1GLaO7rWHwfv0-zmDMTcSF2QY5oa8vXLm/view

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment release frozen

**Comment by somangshu** [comment]
@RakshaKShetty can you please refactor the description so that it's easier to understand.

**Comment by RakshaKShetty** [comment]
> @RakshaKShetty can you please refactor the description so that it's easier to understand.

@somangshu i have updated the summary

**Comment by sharat87** [comment]
Hey @RakshaKShetty, can you include details like the following to help make this issue clearer please?

1. Your description states that the autocomplete is not working, yet in the screenshot we do see an autocomplete show up. So I'm guessing you meant that the autocomplete is not behaving as expected. Can you share what the expected autocomplete is here? Is there an unexpected entry that shouldn't have been there, or is there an entry that's missing?
2. It looks like you are getting the autocomplete suggestions from a `Table1.selectedRow`. Without knowing what's in the table called `Table1`, it's hard to understand what's missing here. Can you share a screenshot or paste the value of what the `Table1.selectedRow` contains please?

If possible, perhaps a Loom screencast showing the table widget, it's data, and then the autocomplete here, with you explaining what's missing might help as well. Thanks!

**Comment by RakshaKShetty** [comment]
Hi @sharat87 i am attaching the screencast with audio what was the expectation 
https://drive.google.com/file/d/1GLaO7rWHwfv0-zmDMTcSF2QY5oa8vXLm/view

**Comment by Nikhil-Nandagopal** [comment]
This is solved
