### ISSUE TITLE
[Bug]The tooltip is not displayed when the user hover on the org name in Create org section 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5308]
## Description

[What happened]The tooltip is not displayed when the user hover on the org name in Create org section Only when the organization name is very large but it should be consistent

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to application page
2. under the create organization section
3. hover on organization name
4.verify the display

The Organization name should be displayed inside the tooltip

![image](https://user-images.githubusercontent.com/45958978/122779263-55867000-d2cb-11eb-85a9-fa2034e7c236.png)
![image](https://user-images.githubusercontent.com/45958978/122779274-57e8ca00-d2cb-11eb-847d-bf5ebbb5d783.png)

Important Details
Version: [Cloud ]
OS: Windows
Browser Chrome
Environment Production

**Comment by SandipPalit** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Nikhil-Nandagopal** [comment]
Hi @SandipPalit , I think you already have a few issues assigned to you. So please complete those before taking on new ones! Looking forward to your contribution :)

**Comment by SandipPalit** [comment]
@Nikhil-Nandagopal Some of my PRs are pending. So please assign this issue. I will complete the rest of the issues also.

**Comment by hiteshjoshi** [comment]
This is not happening for me right now. Closing.
