### ISSUE TITLE
[Bug]In Mysql when the user delete the record through delete query in response it shows 0 row effected but in result it shows 1 record 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5310]
## Description

[What happened]In Mysql when the user delete the record through delete query in response it shows 0 row effected but in result it shows 1 record 

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a MySql datasource
2. Create a Delete db Query
3.Run the Query
4.verify the display of affected rows in response tab

https://drive.google.com/file/d/1woRjVZvKXSGwWswpAeyp3kPj_Aac3F4n/view

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by trishaanand** [comment]
The number of records shows the size of the response, whereas the response itself is showing the results of the query execution. Closing this because both the variables are different and have no relationship.

**Comment by trishaanand** [comment]
The issue actually is : 
Delete command has executed successfully but the response is `affectedRow` 0. @RakshaKShetty  : Can you confirm if this is the problem that you are facing?

**Comment by RakshaKShetty** [comment]
@trishaanand attaching the new video for more reference https://drive.google.com/file/d/1lICB5cd14ZkwmhqaRFx6g4gcfBgHwFLT/view

the problem is Even after the Row item got deleted the affected row display '0' which is wrong ideally it should be 1

**Comment by trishaanand** [comment]
This is a valid bug. Could you update the issue description to correctly reflect the problem? Thanks!
