### ISSUE TITLE
[Bug] Filepicker button gets stuck in a loading state if we set the action to `copyToClipboard`

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5312]
## Description
Filepicker button gets stuck in a loading state if we set the action to `copyToClipboard`

### Steps to reproduce the behaviour:
1. Drag a filepicker to the canvas
2. Set the `onFilesSelected` action as `copyToClipboard`
3. Upload a file
4. The filepicker gets stuck in a loading state

![image](https://user-images.githubusercontent.com/1944800/122795802-4e675e00-d2db-11eb-92ef-8e12c9b1d5ec.png)

**Comment by vibhandikyash** [comment]
Similar to #5287 Will be fixed with its PR.
cc: @vivekverma2312

**Comment by somangshu** [comment]
@vibhandikyash please do not forget to link this to the PR is its getting fixed!
