### ISSUE TITLE
[Bug] 'Name is used already' error message occurs when widget name is named for an Api

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5313]
## Description
It is observed then when the user names the widget name to any of the API's - the name is already used message is displayed

**Expected Result:
Any Widget name's can be used for API name or Datasource name
 

Actual Result:**
Widget name is not accepted for API name

### Steps to reproduce the behaviour:

1.Launch Appmith app in release frozen Environment 
2.Expand Widget
3.Drag and Drop input widget
4. pass the following value in default field - [{"rowIndex":"1", "Name":"Yogesh", "Email":"Yogikingston57it@gmail.com", "Mobile":"9952563100"}]
5. Rename the widget to - Create_Spreadsheet
6. Expand API
7. Click on GoogleSheet 
8. Sync Data source 
9. Click on Create new Query 
10. Choose the type as Create New Spreadsheet
11. Enter spreadsheet name
12. Bind the input widget with the row object 
13. Execute the query 
14. Rename the API name to - Create_Spreadsheet and observe the error message

**VideoLink:**
https://www.loom.com/share/9ef3836b430d40b9ba3479a4a95697a8

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release Frozen]

**Comment by somangshu** [comment]
@YogeshJayaseelan this is an invalid issue, The actual result is expected. `names are variables used for binding so duplicates cannot exist even across entities`

Closing this
