### ISSUE TITLE
[Bug]In mongo db->For distinct query->The response is not correct under response tab it display an error

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5317]
## Description

[What happened]In mongo db->For distinct query->The response is not displayed correctly under response tab it display an error

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to Datasource page 
2. Select the Mongo Db
3. Select the new query 
4. Select Distinct from command 
4. add all mandatory fields
5. Click on Run
6. Verify the display

Expected Result : The response should be displayed correctly

Actual result :  In mongo db->For distinct query->The response is not displayed correctly under response tab it display an error "ERROR":{
"message":"src property must be a valid json object" even thought query ran successfully

https://drive.google.com/file/d/1CSbiq4X8bTmS8XRhBlj55er0PU1xl8RA/view
### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by trishaanand** [comment]
This is a UI issue where the display does not handle response of the following format : 
```
[
  0:""
  1:"aarav"
  2:"deeksha"
  3:"kushi"
  4:"raksha"
  5:"vaibhavi"
  6:"vaish"
]
```

**Comment by mohanarpit** [comment]
@trishaanand Shouldn't the server be returning proper JSON objects back to the client? The sample data you've posted is not valid JSON.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand can we please fix this?

**Comment by trishaanand** [comment]
The result is returned in the following format : 
```
["FORM", "GITHUB", "GOOGLE"]
```
The UI is not handling this correctly. An array of strings is what distinct command sends.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand the UI is not expected to handle this format, queries are expected to return an array of objects. In this case, the key should be the key on which the distinct is being performed right?

**Comment by ajinkyakulkarni** [comment]
@nidhi-nair @arunvjn Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5317?planning-poker)
