### ISSUE TITLE
[Bug]when the user click on on generate widget icon inside the DB query the Table widget is going out of canvas when the canvas is full

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5318]
## Description

[What happened]MySql->when the user click on on generate widget icon inside the DB query the Table widget is going out of canvas when the canvas is full

https://drive.google.com/file/d/1wVphgmPyJ5cVC8Br6umOKuBFR1yXs56P/view

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by somangshu** [comment]
Closing this in favour of #5322
