### ISSUE TITLE
[Bug]Specific to windows->In text widget ->for enable scroll-> even when its enabled or disabled when the text is too big the scroll is displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5319]
## Description

[What happened]Specific to windows->In text widget ->for enable scroll-> even when its enabled or disabled when the text is too big the scroll is displayed

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to widgets
2. Drag and drop the text widget 
3. In the text add the Paragraph
4. Don't enable the scroll
5. Verify the display

Expected Output : The vertical scroll should be displayed be display when the user enable the Scroll bar and when it is disabled the scroll bar should not be displayed

https://drive.google.com/file/d/1N_pt01MPibfgVelrDJMgIcwLulu_595p/view

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by somangshu** [comment]
Since the text entered is a single string the horizontal scroll appears, this can be resolved using something like `word-wrap: break-word;` in CSS.

**Comment by stanikella2** [comment]
hello I am new to open source can I get assigned this to work on

**Comment by somangshu** [comment]
Hi @stanikella2 👋 , Thanks for showing interest to contribute. Please go ahead and implement, I'll assign this to you 😃 . Here are a few notes to help you get started:

To understand the client side codebase setup for local development, [check this out](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md)
You can also point the client side to use our release server [like this](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#if-you-would-like-to-hit-a-different-appsmith-server) and avoid setting up the backend.

Please get in touch with us on our [Discord server](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#if-you-would-like-to-hit-a-different-appsmith-server) to get more help in detail. You can also DM me there to make the conversation faster. 

We also have our [community forum](https://community.appsmith.com/) now, Feel free to drop a question here if required, We respond to that well.
