### ISSUE TITLE
[Bug] Parsing strings with newline character causes error in a select widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5328]
## Description

While using the `select` widget if there is a `\n` or a `newline` in the string against label/value the widget can't parse the object/array and gets an error. 

### Steps to reproduce the behaviour:

1. Drag and drop and select widget
2. In the options error add a newline inside any of the option strings
3. An error is thrown and no options are shown on the widget popper

<img width="1009" alt="Screenshot 2021-06-22 at 3 17 29 PM" src="https://user-images.githubusercontent.com/11089579/122903386-fb3deb80-d36c-11eb-9ff2-7f51ce8cd934.png">

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [production]

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu is this related to #2862?

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : Is this even a valid JSON? Newline is one of the special characters which are not supported in JSON. 
Refer to Section 9 (Strings) here : https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

Pasting the reference text here : 

> A string is a sequence of Unicode code points wrapped with quotation marks (U+0022). All code points may
be placed within the quotation marks except for the code points that must be escaped: quotation mark
(U+0022), reverse solidus (U+005C), and the control characters U+0000 to U+001F. There are two-character
escape sequence representations of some characters.
\" represents the quotation mark character (U+0022).
\\ represents the reverse solidus character (U+005C).
\/ represents the solidus character (U+002F).
\b represents the backspace character (U+0008).
\f represents the form feed character (U+000C).
\n represents the line feed character (U+000A).
\r represents the carriage return character (U+000D).
\t represents the character tabulation character (U+0009).

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand good point since https://jsoneditoronline.org/ does not allow it, neither should we
