### ISSUE TITLE
[Bug] `Radar` chart config doesn't work for the Chart Widget

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5335]
`Radar` chart config doesn't work for the Chart Widget

### Steps to reproduce the behaviour:

1. Drag a chart widget and select type as `Custom Chart`
2. Update the chart config using sample json from: [https://docs.appsmith.com/widget-reference/chart#custom-chart](https://www.fusioncharts.com/dev/chart-attributes/radar), based on the format mentioned: [https://docs.appsmith.com/widget-reference/chart#custom-chart](https://docs.appsmith.com/widget-reference/chart#custom-chart)
3. The chart doesn't render. We get a chart type not supported message

**Comment by dantosXD** [comment]
Thank you!

**Comment by somangshu** [comment]
@vibhandikyash we should triage this and take it up while fixing #3899.
