### ISSUE TITLE
[Enhancement] Need a design for unsubscribe from notification emails

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#5347]
Currently, we send an email notification to users who have participated or tagged in a comment thread. User's should be able to unsubscribe from the email notifications. To do this, there is a link in the email template: https://www.figma.com/file/3IcOgXOZ5BmnM8WMjYmZEo/Collaboration-Email-Templates-Handoff?node-id=11%3A3

If an user clicks on this link, they'll be taken to a page aka unsubscribe page. Couple of points about this page:

- Should be accessible if user is not logged in also
- Tell user about what's going on e.g. you are going to unsubscribe from the comment thread. You'll miss what's going on etc.
- A checkbox with checked by default - subscribe again if I add a new comment or someone tags me
- A unsubscribe/turn off button
- Clicking on the button will show a confirmation message right on this page or redirect to another

## Developer Handoff Link
https://www.figma.com/file/XSVhOqRy1W8VS8Cd5nhor9/Collaboration-feature-Tue-20-April-2021?node-id=1031%3A26620

**Comment by momcilo-appsmith** [comment]
@nayan-rafiq I added the handoff link

**Comment by areyabhishek** [comment]
1. Email me when someone tags me in a comment
2. Email me when someone I invited joins
3. Email me when someone joins an organization that I created
4. Email me when someone joins an app that I created
