### ISSUE TITLE
[Enhancement] Update the email template for comments

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#5349]

**Comment by RakshaKShetty** [comment]
@nayan-rafiq this issue we cant test in the release as we don't have an email support

**Comment by RakshaKShetty** [comment]
Following are the items fixed in this PR.
1.The Display of appsmith logo
2.The header will be displayed in 2 lines instead of 3
3.Turn off comment link is added and it's functional 
4.Display and functionality of social icons
5.View comment button is functionality works fine
