### ISSUE TITLE
[Bug]release->The google sheet has an Auth error and lead to different URL

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5355]
## Description

[What happened]In release instance->The google sheet has an Auth error and lead to different URL

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to Import API page
2. Click on Google sheet
2. Create a new datasource 
3. click on continue 
4. Verify the display

https://drive.google.com/file/d/1g9234qRPpZCdSM1QKGZYF42iEtmGXeTw/view

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [Release]

**Comment by nidhi-nair** [comment]
@RakshaKShetty could you please mention which url the page redirects to? Also is this issue present in apis that you create from scratch? (When it is not imported?)

**Comment by RakshaKShetty** [comment]
@nidhi-nair this is the url which i got directed "https://release-cs.appsmith.com/api/v1/integrations/oauth/authorize?appsmithToken=undefined" and this is we are facing when we create a Api from scratch

**Comment by nidhi-nair** [comment]
This was an issue with cloud-services not being configured for release, closing this as this has been fixed by @mohanarpit
