### ISSUE TITLE
[Bug] Onboarding Flow Step 1 is Broken

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#5357]
## Description

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Start the onboardingflow
2. Click add a query
3. Click do it for me
4. See an error

There are 2 solutions needed here.
1. Fix this step so that do it for me only runs the query
2. Show the toast message below the run button so it does not block the run

**Comment by areyabhishek** [comment]
#4628 Can we solve this too? We have users who are just stuck in a bad state inside the Appsmith editor.

**Comment by Nikhil-Nandagopal** [comment]
Yes. Quick fix is to simply make the End Tour the correct orange style. Better fix needs
@Debsourabh

**Comment by RakshaKShetty** [comment]
@akash-codemonk the bug is fixed
tested items
1.The error message is not displayed when the user perform action on their own 
2.The Toast message is displayed under the run button its not overlapping now
