### ISSUE TITLE
[Feature] Support `storeValue` within `IIFE` bindings

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5371]
## Summary
Support `storeValue` within `IIFE` bindings

For instance:
```
{{(() => {
    let a=["None","Alpha","Beta","Gamma","Delta"];
    storeValue("nameTypes", a, false);
    return "Page Title";
})()}}
```

## Motivation
- Use it as a workaround for the on page load event

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena we don't plan to support this because these types of functions should not be triggerable in display properties. This will be supported in the JS Editor
