### ISSUE TITLE
[Bug] Label text widget gets converted into link automatically without option to Disable the link

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#5377]
## Description

Label text widget, when entered with something that resembles a link or an email gets converted into a link. With no option to disable it.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to the Editor page
2. Drag Label Text Widget to the canvas
3. Add text as "Employee.Id" or "Ph.No"
4. The text gets converted to a link without an option to disable it.

![image](https://user-images.githubusercontent.com/71900764/123208529-e97b5600-d4dc-11eb-81ef-5f5d59032712.png)

### Important Details

- Version: [Cloud]
- Browser [chrome]
- Environment [production]

**Comment by somangshu** [comment]
@rahulramesha we have automated parsing in the Text widget for email and links. I have seen a similar behaviour in other famous text editors. I think should be left as a default. 

@riodeuno your thoughts?

**Comment by riodeuno** [comment]
@somangshu I agree. `xxx.id` is a legitimate URL, hence this auto parses. 
However, as OP mentioned this is unexpected. We should allow for an option in the text widget's property pane to disable parsing links.
