### ISSUE TITLE
[Bug] Deploy Preview - Rich Text Editor - Submit button of form widget is enabled when RTE is required and there is no text in RTE

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5380]
## Description
Deploy Preview :https://deploy-preview-5330--appsmith-editor-ce.netlify.app/applications
It is observed that the submit button can be enabled when there is no text in Rich Text editor and the rich text editor is enabled for required

**Expected Result:**
When the Rich text is enabled for required and when there is not text in rich text editor then the submit button of form should not be enabled

**Actual Result:**
The submit button of form widget can be enabled when there is no text in Rich Text editor and the rich text editor is enabled for required

### Steps to reproduce the behaviour:

1. Launch appmsith app in the Deploy Preview - https://deploy-preview-5330--appsmith-editor-ce.netlify.app/applications
2. Drag and drop form widget 
3. Place Rich Text editor inside form widget 
4. Enable 'Required' button of Rich Text editor 
5. Remove text inside rich text editor and observe the submit button of form is disabled
6. Open property pane of submit button and Disable the 'Disabled Invalid Forms' and observe

**VideoLink:**
https://www.loom.com/share/b45840429550468b836b3ad6ee0bd153

### Important Details

Version: [14.1 (16611.1.21.161.3)]
OS: [MacOS]
Browser [Chrome, safari]
Environment [deploy preview]

**Comment by vicky-primathon** [comment]
This is working as intended
