### ISSUE TITLE
[Feature] Add type `time` to the input widget

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5381]
## Summary
 Add type `time` to the input widget

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena I think this is related to #2033

**Comment by rishabhsaxena** [comment]
@Nikhil-Nandagopal Actually meant adding a type for the input widget types dropdown:
![image](https://user-images.githubusercontent.com/1944800/123220735-d91ea780-d4eb-11eb-8d3e-4cd3267eff40.png)

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena thanks for clarifying. Though this should probably be another widget

**Comment by somangshu** [comment]
@rishabhsaxena @Nikhil-Nandagopal agreed, This should be taken up with #3346
