### ISSUE TITLE
[Bug] Header count  is added into the API Datasource when no header is added into the API

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5383]
Steps to reproduce:
1) Navigate to API pane 
2) Add an API 
3) Click on the datasource
4) observe no header is added 
5) Navigate back to the API pane 
and observe the header tab 

Observation:
Header count  is added into the API Datasource when no header is added into the API

Expectation:
Only when the header has added the Header it must be displayed to the user

Video Link :
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/af5bba82844b428cad3833601944b44c-00001.gif)](https://www.loom.com/share/af5bba82844b428cad3833601944b44c)

**Comment by mkumar09** [comment]
Hi moderators, I am a beginner and looking to contribute to appsmith. Is this issue still reproducible? If yes, I am looking to fix this bug

**Comment by prapullc** [comment]
Closing the issue as this is fixed
