### ISSUE TITLE
[Bug] Smart Substitution in the API pane is not functional

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5386]
Steps to reproduce:
1) Navigate to API 
2) Add a POST API 
3) Add a Body with Smart Substitution
4) Navigate to Setting and add JSON substitution
5) Click on Run 
and observe

Observation:
It is observed that the Substitution details are not being displayed to the user

Expectation:
It is expected  that the user is displayed with the data type 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/37226201243a4bf688777a80ef03f9a4-00001.gif)](https://www.loom.com/share/37226201243a4bf688777a80ef03f9a4)

**Comment by trishaanand** [comment]
Closing this since Smart Substitution works in Rest API as we stand today.
