### ISSUE TITLE
[Bug] On Substitution of API pane evaluated value is not displayed appropriately

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5387]
Steps to reproduce:
1) Navigate to API pane 
2) Add a POST API 
3) Navigate to Setting and select the JSON substitution
4) Add a Body with the same 
and observed the Evaluated area

Observation:
It is observed that the Evaluated value does not represent the JSON substitution

Video 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/37226201243a4bf688777a80ef03f9a4-00001.gif)](https://www.loom.com/share/37226201243a4bf688777a80ef03f9a4)

**Comment by Rishabh-Rathod** [comment]
<img width="1901" alt="Screenshot 2021-11-17 at 2 07 31 PM" src="https://user-images.githubusercontent.com/23132741/142165853-cf849c06-764d-4dcc-a107-4baadf985016.png">

@prapullac  when tried the above example I wasn't able to reproduce this issue. 
Can you help me understand how to reproduce it?

**Comment by prapullac** [comment]
Closing the issue as it is working as expected as the format has changed.
