### ISSUE TITLE
[Feature]-[1292]:Support targetWindow.postMessage for iframe

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#5390]
Add support for targetWindow.postMessage to pass data from window to iframe.

**Comment by somangshu** [comment]
This is already implemented and enhanced in #5897. Closing this

**Comment by Nikhil-Nandagopal** [comment]
@somangshu this is slightly different. This is to add a message property in the iFrame which will post the message to the iFrame and the embedded app can handle

**Comment by somangshu** [comment]
The use case is to receive a postMessage from the embedded app into the iFrame. I dont see how the iFrame can postMessage to the embedded app. Can you please tag an example here @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@somangshu 
Introduce a property called message. Whenever message changes, post a message to the iframe
https://stackoverflow.com/questions/61548354/how-to-postmessage-into-iframe

**Comment by somangshu** [comment]
@Nikhil-Nandagopal you are getting the use case wrong here I feel, Its the embedded app sending the message to iFrame using the postMessage(). (As also mentioned in the SO post). This is already implemented in out iframe. We have also exposed the message API in Appsmith to be used anywhere

Lets discuss if required

![Screenshot 2021-08-06 at 4 36 39 PM](https://user-images.githubusercontent.com/11089579/128501609-daba95dc-5160-49a0-a13e-9d93e1daf4f8.png)
![Screenshot 2021-08-06 at 4 37 04 PM](https://user-images.githubusercontent.com/11089579/128501618-3fd1dc4e-3996-41d6-bb7d-b0b1c36ac203.png)

**Comment by Nikhil-Nandagopal** [comment]
@somangshu I get the use case of iFrame -> appsmith communication, which is a solved problem with onMessageReceived. There is also a use-case of appsmith -> iFrame communication, this needs to be solved

**Comment by cokoghenun** [comment]
Any progress on this? @somangshu  @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@dncpax @cokoghenun you can send messages to the iFrame today using the query params of the URL. You can then read those query params in the loaded webpage. Does that not work for you?

**Comment by cokoghenun** [comment]
@Nikhil-Nandagopal I know as a workaround query params can be used, but the native iframe HTML element support postMessage. As a result, lots of our users expect this to also work with the iframe widget on Appsmith as they already have their codebase built around postMessage and not query params. And sometimes, they might need to embed third party websites (which they can't modify) that only accept data through postMessage.

Think of the button widget without an onClick action. That's how our users feel about the iframe widget without the postMessage action

**Comment by dncpax** [comment]
Well not really since you in fact reload the iframe web page which is not
that desirable. It works as a workaround and that's what I'm doing at the
moment for a simple use case.

A sexta, 26/11/2021, 08:09, Nikhil Nandagopal ***@***.***>
escreveu:

**Comment by cokoghenun** [comment]
Yeah that's right @dncpax . @Nikhil-Nandagopal  changing query params to send data would cause a reload, which will make the embedded website loose local state

**Comment by Nikhil-Nandagopal** [comment]
@cokoghenun @dncpax thanks for your inputs. I think the right way forward for this would be to add a message property to the iFrame that internally does an iFrame.postMessage whenever it changes. postMessage doesn't make sense as an event handler like onClick because it's not an event a user raised but rather a method to be triggered on the iFrame.

cc: @sbalaji1192 @somangshu @jsartisan

**Comment by rohan-arthur** [comment]
WIDGET_CARD_DRAG, widgetType = `IFRAME_WIDGET`, 6m = 750
Apply 20% requirement: 150
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 150 |
| Effort (months)  | <<number>> |

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur I increased the reach since it's a basic communication requirement for the iFrame widget.

**Comment by rohan-arthur** [comment]
WIDGET_CARD_DRAG, widgetType = `IFRAME_WIDGET`, 6m = 750
Apply 70% requirement: 500
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  |  |

**Comment by rimildeyjsr** [comment]
This is being worked on here - https://app.zenhub.com/workspaces/fe-coders-pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/7241

Closing this issue in favour of 7241

**Comment by dilippitchika** [comment]
@rimildeyjsr can you let us know if this problem is also being solved now?

User wants to post a message from appsmith to an iframe widget, can they use the solution in #7241

**Comment by dilippitchika** [comment]
Following what @Nikhil-Nandagopal suggested, @sbalaji1192 to explore this idea-
We want to add a new message property to iframe, which when updated triggers the postMessage event on the iframe which the dev can then use to update the child.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika @sbalaji1192 rethinking this, maybe the message should not be a property of the iFrame since the message is a transient data value? Shall we just reuse the postMessage function that we're exposing?

**Comment by dncpax** [comment]
I'm not an expert but I thought it could something we can bind to a store value, so that we can manipulate that store value and send it to the iframe. So more of a new property we can bind to.

**Comment by dilippitchika** [comment]
Not sure if we can, @sbalaji1192 can you check this next week?

**Comment by sbalaji1192** [comment]
@rimildeyjsr I'm reassigning this to you based on the slack convo. Please add this to the list of issues that will get fixed once you push in your changes for `postMessage` function.

**Comment by pranavkanade** [comment]
@rimildeyjsr did we release this feature? There is no document around it?
cc - @jnikhila

**Comment by pranavkanade** [comment]
@somangshu Did we release this feature?

**Comment by dilippitchika** [comment]
@pranavkanade you have to check with @rimildeyjsr and fe-coders. cc @bharath31

**Comment by somangshu** [comment]
It's been tracked somewhere else #7241
This got merged just a while ago. Please check with @rimildeyjsr from FE coders for more info

**Comment by bharath31** [comment]
@pranavkanade this is still in QA cc: @AnandiKulkarni

**Comment by AnandiKulkarni** [comment]
https://github.com/appsmithorg/appsmith/pull/14925 PR which is released today, I am yet to test it on release
