### ISSUE TITLE
[Feature] Enable a default sort order for Tables

### ISSUE THREAD

**Issue by jmcouffin** [appsmithorg/appsmith#5391]
## Summary

provide ability to automatically sort data from tables, dropdown, ...

## Motivation

tedious process to use js function to do so every single time

## Additional Context

usually it has to look like this:

```
{{
    (function(){ 

return  (
source_data.data.map((member)=>{ return {label: member.name,value: member.gid}})
).sort((a, b) => {
    const aName = a.label;
    const bName = b.label;
    return aName.localeCompare(bName);
  });
  })()
}}
```

**Comment by Nikhil-Nandagopal** [comment]
@jmcouffin clicking on the column of the table will automatically sort it. Is this not working for you?

**Comment by jmcouffin** [comment]
not exactly as expected:
I want the data to be sorted beforehand, while fetched by the ressource / at the source level maybe.
Right now, fetching data from a rest api, it comes out by creation date basically / id. so if I want to create a dropdown with this data, I have to file in the code quoted above to make it do the thing.

is a 'sort' option possible in the dropdown options (and all other widgets)?

**Comment by Nikhil-Nandagopal** [comment]
@jmcouffin Ah I see, you're looking for a default sort order property in the table. Thanks for clarifying that!

If you have a large dataset, I still recommend you configure your API to do this as it can be inefficient in memory :)

**Comment by jmcouffin** [comment]
we are small 😃 
usually 4 pages tops.
I understand that in much bigger datasets I would better go through a middle man database;

**Comment by jmcouffin** [comment]
but my usecase is mostly for dropdown. Right now my workaround is to assemble 3 queries results in one in a table and then use the table data in the dropdown.

**Comment by Nikhil-Nandagopal** [comment]
@jmcouffin I'm not sure if dropdowns are inherently meant to do sorting by default. Would a reusable JS sort function that could be run on top of the API be a better fit here?

**Comment by jmcouffin** [comment]
on top of the API? how/where? in the ressource or on the dropdown widget?

**Comment by Nikhil-Nandagopal** [comment]
@jmcouffin in the API itself, we're planning to introduce an option to add a JS function so that users can transform the response of their API in a single place and then just use that in the widget.

**Comment by jmcouffin** [comment]
that would make sense. 
a bit like in retool in the transform section where you can add your code to transform the data (but not the query itself)

**Comment by Nikhil-Nandagopal** [comment]
Yes! This is currently being worked on as part of #1751

**Comment by somangshu** [comment]
Closing this in favour of #1751
