### ISSUE TITLE
[Bug] [release] Multiple statements (separated by `;`) within moustache bindings don't work

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5396]
## Description
Multiple statement within moustache bindings don't work on release.
This works on prod

### Steps to reproduce the behaviour:
1. Drag a button to the canvas
2. Set the `onClick` action as:
```
{{
  storeValue('middleTabs','showTabsValue');
  storeValue('showTabs',"Region");
}}
```
3. Bind the store values in two different text widgets
4. Only the first `storeValue` is executed

**Comment by hetunandu** [comment]
Fixed with #5613
