### ISSUE TITLE
Several suggestions about the table components

### ISSUE THREAD

**Issue by meimosor** [appsmithorg/appsmith#5400]
## Feature Suggestions

1. Table Components supports editing within the line, which is often used
2. Support tree table
3. Tables support column drag and drop to adjust the width and can be filtered, such as by state, rather than using query criteria

**Comment by Nikhil-Nandagopal** [comment]
@meimosor thank you for the feature request! 
for 
1. Do you mean an in-line editor of the table?
2. Is this an example of a tree table? https://barista.dynatrace.com/components/tree-table
3. This should be possible today/ Is this not working for you??

**Comment by meimosor** [comment]
> @meimosor thank you for the feature request!
> for
> 
> 1. Do you mean an in-line editor of the table? Like this https://ant.design/components/table/#header
> 2. Is this an example of a tree table? https://barista.dynatrace.com/components/tree-table
> 3. This should be possible today/ Is this not working for you??

Yes, I refer to the component documentation still can't achieve these two functions, can provide an example？

**Comment by Nikhil-Nandagopal** [comment]
@meimosor I';ve attached a video of how to achieve #3. Can you tell me if this works?

https://user-images.githubusercontent.com/3897254/123395012-5bc36780-d5bd-11eb-84d9-c033ba90c6a2.mov

**Comment by meimosor** [comment]
Table drag and drop is OK, but can tree tables and row editing be implemented？

**Comment by Nikhil-Nandagopal** [comment]
@meimosor yes! I have raised features for them. You can leave any specific details you;d like in the issue
#5415
#4183
