### ISSUE TITLE
[Bug] Dependency map seems to not get updated for queries with SQL datasources

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#5408]
## Description

The dependency map does not seem to get updated initially on page load for queries with sql datasources such as postgres and ms sql server

### Steps to reproduce the behaviour:

1. Add a binding say {{Button1.text}} to query with a postgres datasource
2. Reload the page
3. Check the inverse dependency map in logs and see that the query is not in the inverse dependency list of `Button1.text`

https://user-images.githubusercontent.com/67054171/123392813-156d0900-d5bb-11eb-86e4-441d5edba952.mov

<img width="501" alt="deps" src="https://user-images.githubusercontent.com/67054171/123392899-32094100-d5bb-11eb-9a1a-08f7fdadfe2e.png">

In the above image note that Query12(has postgres datasource) and Query7(ms sql server) is missing.

The use case for this is that the dependency map is used as input to show the dependencies in the inspect element section of the debugger.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by ohansFavour** [comment]
Hey @akash-codemonk , I am unable to reproduce this. Could you please confirm that this no longer applies?
