### ISSUE TITLE
[Bug] Table displays an error when placed for the first time

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5410]
Steps to reproduce:
1) Drag and drop the table widget

Observation:
It is observed that the error is displayed on the label of the table. However, it is not displayed on the debugger

Expectation :
It is expected that the fields can be placed by default else not highlight in red 

<img width="265" alt="Screenshot 2021-06-25 at 12 24 42 PM" src="https://user-images.githubusercontent.com/71753653/123394185-7b0dc500-d5bc-11eb-870c-4a983aa12927.png">

**Comment by riodeuno** [comment]
Closing this as it is fixed in release.
