### ISSUE TITLE
[Bug]The iframe outline is thicker on top and left side than the bottom and the right side

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5411]
## Description
It is observed that the iframe outline is thicker in left and top where as it s thin in right side and bottom

Expected Result:
All the sides should have equal thickness in outline

Actual Result:
outline is thicker in left and top where as it s thin in right side and bottom

### Steps to reproduce the behaviour:

1.Drag and Drop iFrame and observe

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [
<img width="1280" alt="Screenshot 2021-06-25 at 1 53 43 PM" src="https://user-images.githubusercontent.com/35128442/123395215-93321400-d5bd-11eb-9c50-3fe4adac3182.png">
release]

**Comment by somangshu** [comment]
This is default iFrame behaviour, Since it treats borders and inset it gives out an illusion of width being different. 

Closing this for now

**Comment by vivekverma2312** [comment]
@somangshu Can you please check for the fix. I will reopen this issue for now.
<img width="1319" alt="Screenshot 2021-07-01 at 1 21 39 PM" src="https://user-images.githubusercontent.com/83569920/124087351-899e2580-da6f-11eb-84f6-09a3e9491239.png">

**Comment by somangshu** [comment]
This can be solved using `border-style: solid` for the iframe node
