### ISSUE TITLE
[Feature]-[6000]:Minimise the context switching for updating a API and layout

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#5412]
## Summary

Today in Appsmith we have separate screens to update page layout and actions (DB query/ APIs). So when the user is updating the layout which needs an action update user will have to go to and fro between the action screen and layout screen. Creating a split-screen option can enhance the UX  

## Additional Context

![split_screen](https://user-images.githubusercontent.com/41686026/123395800-3b47dd00-d5be-11eb-8703-eb620e86bb42.png)

**Comment by jmcouffin** [comment]
from this discussion https://discord.com/channels/725602949748752515/760761686549463060/857894702975418408

**Comment by Nikhil-Nandagopal** [comment]
@jmcouffin do you think introducing tabs for each entity and allowing users to organize the tabs in a split view like code sandbox does would make sense here?

**Comment by jmcouffin** [comment]
definitely, but that would kind of change the whole UI layout I guess. 
maybe a toggle button to anchor left or right APIs, Query, Page?

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 9000 |
| Effort (months)  | 3 |

**Comment by kocharrahul7** [comment]
This is now handled as a part of IDE 2.0
