### ISSUE TITLE
[Bug] iFrame - The content inside the iframe are not updated dynamically unless the entire page is refreshed

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5417]
## Description
It is observed that the content in the iframe is not dynamically updated 

**Expected Result:**
Content of iframe should be updated dynamically 

**Actual Result:**
Content in the iframe are not updated dynamically

### Steps to reproduce the behaviour:

1.Drag and Drop iframe 
2.Copy the current appmsith url and paste in the source and ensure the current appsmith page is displayed in iframe
3. Drag and drop any other widget outside iframe and observe
4. Refresh the entire page and observe

Videolink:
https://www.loom.com/share/98b8e41782604716ba2a124f102415fe

### Important Details

Version: [14.1 (16611.1.21.161.3)]
OS: [MacOS]
Browser [chrome, safari]
Environment [release]

**Comment by somangshu** [comment]
This is expected; iFrame can't be expected to pull data/page-view in real time.
