### ISSUE TITLE
[Feature] Possibility to expand JS coding window to be able to make more complex solutions

### ISSUE THREAD

**Issue by vongohren** [appsmithorg/appsmith#5418]
## Summary

I just found the JS toggle formula. And its great, but with one nested layer things become complex.
Im feeling the same thing here as I feel over at coda.io.
https://community.coda.io/t/expand-formula-editor/14438/10
They release a cool feature that helps alot
https://community.coda.io/t/launched-formula-building-now-bigger-and-better/22850

## Motivation

It will be easier to resonate around the formulas, it really helps with autoformat to make sure that the code is readable and can be more productive

## Additional Context

Just showcasing. Now I just added a qurey, and I want to add a message after the query.
<img width="341" alt="Screenshot 2021-06-25 at 11 19 07" src="https://user-images.githubusercontent.com/1012055/123401536-31ff4600-d5a7-11eb-99d7-be577e507444.png">

This is not easy to ressonate with

**Comment by Nikhil-Nandagopal** [comment]
Hi @vongohren 👋  Thank you for the feature request! We're actually in the process of developing this feature right now! You can check out the issue and the designs below. We're very excited about it :)
#1751

**Comment by Nikhil-Nandagopal** [comment]
I really like the code example by the way! @aakashDesign @hetunandu maybe we can incorproate an expand interaction like this as well?

**Comment by vongohren** [comment]
No problem. Happy to help with such a great product! Look forward to see how it will become :D !
Should we just close this for now as you have referenced the other issue and that is where you are working :D 
Or you like to close all related issues after completion :D

**Comment by Nikhil-Nandagopal** [comment]
@vongohren we'll close it because we generally tend to forget and get buried under a ton of issues :)
