### ISSUE TITLE
[Enhancement] Open Property pane only on clicking on widget name

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#5424]
## Summary

- Open property pane only via the widget toggle(widget name) instead of opening it up on clicking on the widget/ resizing/ dragging.
- Open property pane when a new widget is dropped into canvas.

## Motivation

Property pane often comes in the way when the user wants to just move around widgets or resize them or interact with them which ends up into a bad UX. 

## Additional Context

When a new widget is added property pane is shown.

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 @areyabhishek can we do this along with the enter / double click feature? I don't think we should ship this without an easy way to open it. It might negatively impact new users

**Comment by marks0351** [comment]
@areyabhishek I agree with @Nikhil-Nandagopal. thoughts?

**Comment by areyabhishek** [comment]
Sounds good.

**Comment by areyabhishek** [comment]
BTW, what's the ETA of this feature?

**Comment by marks0351** [comment]
@Nikhil-Nandagopal @areyabhishek This was suppose to come out last week. I have hit a road block on this wrt to checkbox and radio buttons of blueprint which simulate multiple clicks which I am trying to figure out why.
