### ISSUE TITLE
[Feature] Server side pagination for table

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#5426]
Seeing a user struggle with basic features of server side pagination. Multiple problems:
1. Couldn’t figure out where to turn on server side pagination(the gif makes it look like there’s a toggle for server side pagination in API settings and not the table widget). If the gif showed there was a table property pane involved, he wouldn’t be so frustrated.
2. They couldn’t find the server side pagination action inside the property pane of the table because the dummy data covered most of the screen and the user simply didn’t scroll to find what they needed.
3. The server side pagination setting should be close to the server side pagination action.

**Comment by somangshu** [comment]
1. Content related change
2. There is another issues addressing this 
3. covered in #8845

**Comment by jnikhila** [comment]
@somangshu - Do you think this is a duplicate? If not, could you please merge the two tickets so we can close this?

**Comment by somangshu** [comment]
@jnikhila please point to the potential duplicate you are talking about

**Comment by jnikhila** [comment]
@somangshu - [here](https://github.com/appsmithorg/appsmith/issues/5426#issuecomment-964989751)

**Comment by somangshu** [comment]
The related context change request is as below
> Couldn’t figure out where to turn on server side pagination(the gif makes it look like there’s a toggle for server side pagination in API settings and not the table widget). If the gif showed there was a table property pane involved, he wouldn’t be so frustrated.

Let me know if you need any additional details; I am not sure what duplicate you are talking about!
