### ISSUE TITLE
[Task] Add analytics events for the new editor navigation

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5427]
Analytics events for the changes done for simplifying the editor navigation:

- ~~Create new datasource CTA on the property pane~~
- ~~Run button at the response tab for actions~~

Suggested widgets (payload data for incoming / outgoing):
- ~~Click on connect to selected widget from the actions right side bar~~ (out of scope)
- ~~Use a suggested widget from the api / query pane~~

Associated entities:
- ~~Click on associated entity from the actions side bar~~
- ~~Click on associated entity dropdown from the property pane~~
- ~~Select an associated entity from the associated entity dropdown at the property pane~~

~~Sniping mode:~~
- ~~Start visual sniping mode~~
- ~~Select a widget via visual sniping mode~~

Slash commands:
- Triggered slash commands menu (via button click or code mirror)
- ~~Execute a slash command (with command details in the payload)~~

Backend events:
- ~~Create a mock datasource~~
- ~~Create a mock datasource query~~

**Comment by pranavkanade** [comment]
Added events for sniping mode.

**Comment by AnaghHegde** [comment]
Added event for mock-data creation

**Comment by RakshaKShetty** [comment]
@pranavkanade, @AnaghHegde, @akash-codemonk can you give me the events name for each action so that it would be easier for me to test

**Comment by AnaghHegde** [comment]
@RakshaKShetty Event name is `CREATE` and attribute is `MockDataSource `

**Comment by akash-codemonk** [comment]
Create new datasource CTA on the property pane - `CONNECT_DATA_CLICK`
Run button at the response tab for actions - `RESPONSE_TAB_RUN_ACTION_CLICK`
Use a suggested widget from the api / query pane - `SUGGESTED_WIDGET_CLICK`
Click on associated entity from the actions side bar - `ASSOCIATED_ENTITY_CLICK`
Click on associated entity dropdown from the property pane - `ASSOCIATED_ENTITY_DROPDOWN_CLICK`
Select an associated entity from the associated entity dropdown at the property pane - `ASSOCIATED_ENTITY_CLICK`
