### ISSUE TITLE
[Bug] Unable to download Excel Spreadsheet (Media type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5428]
## Description
Quoting from this discussion on discord:
https://discord.com/channels/725602949748752515/760761686549463060/858014134444228638

I've written some code that returns an Excel Spreadsheet (Media type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'). I've dockerized the code and added it in to the Appsmith docker-compose so that it's visible from the APPSMITH internal network and also exposed a port so I could reach it directly. 

In my APPSMITH ui, I have three widgets. 2 of them set the arguments for the API call and the third is a button. The onClick action runs the API call, and onSuccess call of that onClick action is the download action.  The data it donwloads is {{APICALL.data}} and has a manually entered filename (for simplicity; eventually, I would like to pull the filename from the content-disposition header). 

The issue is that the file is corrupted when downloaded from appsmith, and not when downloaded directly from the API. There are some size differences in the file

Response from the api:
https://gist.githubusercontent.com/pgvee/c54d1aa7f5a6bbb59f33ef07caf37d6a/raw/172e097f5bca7c1cec7dec542219a9277c7b7a79/response.json

Details of the api:
```
return StreamingResponse(tmp,
        media_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 
        headers={"content-disposition": f"attachment; filename=reorderReport-{end_date}-{strat}.xlsx"})
```

![1](https://user-images.githubusercontent.com/1944800/123457689-cb5b4600-d601-11eb-985e-3840792056b3.png)
![2](https://user-images.githubusercontent.com/1944800/123457703-cf876380-d601-11eb-8b16-16d2f72ee7b3.png)

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can we do something here?

**Comment by nidhi-nair** [comment]
@hetunandu has updated the docs for this temporarily, we need to find a way to allow downloads for blobs.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you detail what the problem here is?

**Comment by Hexiaopi** [comment]
I also encountered a similar problem, and the downloaded Excel file could not be opened

**Comment by shantanu1singh** [comment]
@Nikhil-Nandagopal @rishabhsaxena was this fixed? I'm trying to download an excel spreadsheet too but the file that gets downloaded is eventually corrupted. Here are all the ways I've tried downloading the file but they all failed:

`let templateData = Query.run();
const blob = new Blob([Query.data], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
const url = URL.createObjectURL(blob);
download(url, "file.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");`
	
`let templateData = Query.run();
const blob = new Blob([Query.data], {type: 'application/vnd.ms-excel'});
const url = URL.createObjectURL(blob);
download(url, "file.xls", "application/vnd.ms-excel");`
	
`let templateData = Query.run();
download(Query.data, "file.xls", "application/vnd.ms-excel");`

`download("https://test.com/file.xlsx", "a.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");`

`download("https://test.com/file.xls", "a.xls", "application/vnd.ms-excel");`
