### ISSUE TITLE
[Bug]The notification is not displayed in the bell icon for the Users after First few notification

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5435]
## Description

[What happened]The notification is not displayed in the bell icon for the Users after First few notification

### Steps to reproduce the behaviour:

1. Go to application page
2. Click on bell icon
3. Verify the display of Notification

If we compare the below screenshot the new comment thread is added to RakshaShetty but if we see the bell icon for the notification in the second screenshot the notification is not received 
![image](https://user-images.githubusercontent.com/45958978/123577277-256e2e00-d7f1-11eb-9fa8-b5271bc5a553.png)
![image](https://user-images.githubusercontent.com/45958978/123577370-53ec0900-d7f1-11eb-8fd0-d489c5fd3402.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment Release

**Comment by rishabhsaxena** [comment]
Actually these could be different:
- the notification icon is related to the unread notifications count
- the comment icon within an app is related to the unread threads for that application
