### ISSUE TITLE
[Bug] Not able to launch Appsmith AMI on EC2 

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5456]
## Description

A user on Discord [reported](https://discord.com/channels/725602949748752515/760761686549463060/859112436796096512)  that there is a problem launching Appsmith AMI.

<img width="1406" alt="ec21" src="https://user-images.githubusercontent.com/800578/123676343-7453ac00-d861-11eb-8de6-5438056229b8.png">

<img width="1221" alt="ec22" src="https://user-images.githubusercontent.com/800578/123676357-787fc980-d861-11eb-980d-0918c8b82b1e.png">

### Steps to reproduce the behaviour:

1. Go to EC2 > Launch Instance > Community AMIs and search for Appsmith 
2. Launch Appsmith AMI
3. See the error at the last step

### Important Details

- Version: AMI

**Comment by mohanarpit** [comment]
The new AMI version 1.3 has been released. The AMI can be accessed at: [https://aws.amazon.com/marketplace/pp/prodview-mclslaty46ah4](https://aws.amazon.com/marketplace/pp/prodview-mclslaty46ah4)
