### ISSUE TITLE
[Bug]The "Total record count" and "Default Page size" is showing errors in their default state.

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5459]
## Description

[What happened]The "Total record count" and "Default Page size" is showing errors in their default state.

### Steps to reproduce the behaviour:

1. Drag and drop the table
2. verify the display of Error in the "Total record count" and "Default Page size" input boxes
![image](https://user-images.githubusercontent.com/45958978/123734972-f7095500-d8bb-11eb-8ea8-3cfafa0b5d68.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment release

**Comment by somangshu** [comment]
This is related to #2230, Please follow the discussion for any update. We will fix it there. 

Closing this
