### ISSUE TITLE
[Bug]The page size should change based on the table height and the default page size field should be removed.

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5460]
## Description

[What happened]The page size should change based on the table height and the default page size field should be removed.

### Steps to reproduce the behaviour:

1. Drag and drop the table widget
2. Enable server side pagination
3. Resize the Table widget 
4. Observe the display of data

Expected result: The page size should change based on the table height and the data should change accordingly this should work for both server-side pagination and for the default pagination.

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment Release

**Comment by ramsaptami** [comment]
Issue still exists on release.
https://www.loom.com/share/bc5d32b47d904e539597f253254314a2

**Comment by somangshu** [comment]
@ramsaptami the issue you are pointing to is not related to above, Suggest you raise it separately

Closing this
