### ISSUE TITLE
[Docs] The new server side pagination changes should be updated for the table widget

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5461]
## Documentation Link 

1. Disable the next option for the pagination 
2. Tooltip for the new input fields 
3. The display of input filed only when the server-side pagination is enabled. 
4. The page size changes based on the table height
5. Header options is also too high and should be below actions

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

The new server-side pagination changes should be updated for the table widget.

**Comment by somangshu** [comment]
Pending pull request is available, Closing this here
