### ISSUE TITLE
[Bug]When the post api request fails, the body is empty in the error logs

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5462]
## Description

[What happened]When the post api request fails, the body is empty in the error logs

### Steps to reproduce the behaviour:

https://drive.google.com/file/d/1UKKb9fZBQNPA4NHoRDLarA2ym8kFIlk3/view

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by akash-codemonk** [comment]
The request object is received as part of the response of run action api. This is used to show the error in the debugger. For form data fields, the `bodyFormData` field seems to be missing in the response. Can the backend team help with this?
