### ISSUE TITLE
[Task] Navigation Bar Dropdown

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#5463]
# Summary
| Label | Value | 
| ------------- | ------------- |
| Responsible | @momcilo-appsmith, @rahulramesha  |
| Accountable | @momcilo-appsmith  |
| Consulted | @areyabhishek  |
| Informed | @somangshu |

# Problem statement
The most important actions are hard to access and are all over the place.

# Objective
Put the most important actions in one place.

# Success Metrics
| Goal  | Metric |
| ------------- | ------------- |
| The user sees all the possible actions while trying to find another action  | Increased use of the actions inside of the menu |

# Requirements
| Requirement   | Importance | User Story | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Must have all the actions listed in the menu | HIGH |

# Milestones
| Milestone | Start Date | End Date |
| ------------- | ------------- | ------------- |
| Move Edit Application name Action to a different button | 29.06.2021 | 30.06.2021 |
| Create Dropdown | 30.06.2021 | 02.07.2021 |
| Create elements in the Dropdown | 30.06.2021 | 02.07.2021 |
| Bind Actions to the Dropdown Elements | 01.07.2021 | 05.07.2021 |

# Developer Handoff Document in Figma
[Link to the developer Handoff Document](https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=553%3A6794)

**Comment by momcilo-appsmith** [comment]
@somangshu can you help me with the milestones section? Also, can you assign someone?

**Comment by rahulramesha** [comment]
Milestones:
- Move Edit Application name Action to a different button
- Create Dropdown
- Create elements in the Dropdown
- Bind Actions to the Dropdown Elements

**Comment by Nikhil-Nandagopal** [comment]
@momcilo-appsmith @areyabhishek I just saw this today and I see 2 issues
1. The Deploy menu item has current deploy version which is same as the view menu item's view option, I think these should be made a little more intuitive.
2. The deploy button has consistently had a problem where users click the down arrow instead of the text and get confused when they land on the empty canvas instead of their deployed app. This new navbar feels like it will amplify the problem. Can we please re-look at this button's visuals?

**Comment by rahulramesha** [comment]
In Navigation Menu items, the Below items were implemeted:

- Rename
- View Modes -> Edit Mode
                        -> Comment Mode

- Deploy -> Deploy
               -> Current Deployed Version

- Shortcuts
- Help -> Community Forum
            -> Discord Channel
            -> Github
            -> Documentation
- Delete Application
