### ISSUE TITLE
[Bug]When making an API from the API builder, while adding the body in  JSON tab the output is shown as a string in the body field

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5466]
## Description

[What happened]When making an API from the API builder, while adding the body in the JSON tab the output is shown as a string in the body field

### Steps to reproduce the behaviour:
https://drive.google.com/file/d/14dk9DMhI6w2IkbBOaRvzM7yttBluZVqo/view

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by ajinkyakulkarni** [comment]
From the video, it looks like when the API errors out,  body/params are logged in the error tab (which is expected behavior). It doesn't look like a bug.

**Comment by akash-codemonk** [comment]
This seems like expected behaviour. JSON will be shown as string.

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk why is it not a parsed object?

**Comment by akash-codemonk** [comment]
The execute(run action) api returns the request object as part of the response. This is what is shown for the errors in the debugger. Also the value in `body` here could be anything it could be a random string. In this case the actual value in body would be something like `{\n\t\"foo1\": \"bar1\",\n\t\"foo2\": \"bar2\"\n}` with new line characters.

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk since the body type is JSON, can we try to parse the JSON, and if it fails fallback to this?
