### ISSUE TITLE
[Bug] API Keys not working in datasource

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5471]
Steps to reproduce:
1) Add an API with API keys
2) Click on Datasource
3) Select Authentication Type as API_Key 
4) Add a required credential
5) Save the data source
6) now navigate to the same API 
7) Click on RUN 
and observe 

Observation:
it is observed that an error message asking for  Authentication  is displayed to the user 

Expectation:
An appropriate error stating multiple  Authentication must be displayed to the user 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/32f4433c5b8f439b92befeef7b0ac2e5-00001.gif)](https://www.loom.com/share/32f4433c5b8f439b92befeef7b0ac2e5)

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair @sumitsum this seems like a big issue. Why didn't the authentication work here?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal  this happens because the API now has 2 copies of the same auth param and the endpoint rejects such an API call. Should we prioritize the API level params and ignore the datasource in such a scenario?

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair In this case I see a few things
- We should have params in a datasource and it should be obvious that the params in being sent once you convert the API to the datasource
- Once the API field is added in authentication, we should inform the user that there is a duplicate field with the same key. This should be true of headers as well right?

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal Can you please explain the first point ? Are you saying that we add a params field in the datasource section as well - which would copy over values from the API params section ? What should happen in case multiple APIs use the same datasource and each one has different params ?

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum I would expect the same thing that happens when multiple APIs have different headers and use the same datasource.

**Comment by sumitsum** [comment]
Re-opening it since Client side changes are pending. API server changes have been merged. @ajinkyakulkarni need some help here to implement the following on the client side:
* add a query parameter field to API datasource page on the lines of the header field.
* show warning messages on the API query pane.

**Comment by prapullac** [comment]
Information is been displayed to user on duplication of keys and further actions to be taken to display the right data.
And the system works accordingly.
