### ISSUE TITLE
[Bug] Authentication Headers are not displayed in API

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5473]
Steps to reproduce:
1) Add an API 
2) Click on Save as a data source
3) Select Auth type as "API Key"
4) Add KEY and Value 
5) Select the "Add to" option as Header 
6) Save the data source
7) navigate to API Pane 
and observe

Observation:
The Auth data is not added into the header or Params section and clicking on the RUN option error is system displayed to user.

Expectation:
1) when user selects the "Add to" as Header the data must be displayed in the header section 
OR
2) Appropriate error message must be displayed to user stating Key value is placed inappropriately

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum @nidhi-nair can we fix this? It's very hard to debug the API requests
