### ISSUE TITLE
[Bug] When using "Use Prepared Statement", decimal point value of a floating point number is changed

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5474]
## Description

A user on [Discord](https://discord.com/channels/725602949748752515/760761686549463060/859357631382421545) reported that when a float valued is saved into the database, the decimal places are not saved correctly in the database.

<img width="1111" alt="Screen_Shot_2021-06-29_at_4 48 43_PM" src="https://user-images.githubusercontent.com/800578/123793332-360cca00-d8ff-11eb-9caa-289fa33c0731.png">

### Steps to reproduce the behaviour:

1. Follow this tutorial https://docs.appsmith.com/tutorial-1/part-2-using-forms/creating-a-form
2. Go to the database or connect it to a table widget
3.  You will find that entered value is not saved correctly (maybe during substitutions/conversion, the floating-point value is changed)

I was able to reproduce this bug. 

<img width="668" alt="decimal bug" src="https://user-images.githubusercontent.com/800578/123793838-cea34a00-d8ff-11eb-8db0-baf25e391b4d.png">

When I turned off "Use Prepared Statement" flag, I was able to save the value as expected.

<img width="1055" alt="decimal2" src="https://user-images.githubusercontent.com/800578/123795287-7e2cec00-d901-11eb-9bc0-e02695053941.png">

### Important Details

- Version: Cloud
- Environment production

**Comment by betochf** [comment]
Hey @ajinkyakulkarni, I would like to try to solve this

**Comment by ajinkyakulkarni** [comment]
@betochf - Assigned this action to you. Please let us know if you need help.

**Comment by ajinkyakulkarni** [comment]
@ApekshaBhosale @vnodecg Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5474?planning-poker)
