### ISSUE TITLE
[Feature] Switching to live mode / syncing apps with a cloud instance

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#5482]
- Enter cloud url or sign-up
- Select org to sync the app to
- Settings to sync the app: for example auto vs manual

**Comment by rishabhsaxena** [comment]
- Toggle mode button
- Cloud host url option (replace this with the base url for APIs in online mode)
- Related changes in auth flow 
- Show or hide app sections in offline mode
