### ISSUE TITLE
[Feature] Include a new property in file picker to support multipart uploads

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#5503]
## Summary

Today, the only source of binary data within Appsmith is the file picker. However, this source is not automatically usable for multipart uploads in the REST API, since the widget abstracts away certain information like, filename, content-type, etc.

We should add a new property that captures this data in a readily consumable format by the user when they choose to use the multipart upload option.

**Comment by somangshu** [comment]
@nidhi-nair IIUC we want to fetch multi-part data from the file-picker widget to consume it in a REST API?

**Comment by nidhi-nair** [comment]
@somangshu yes, the backend implementation expects a json object in the value field with the following format:
```
{
  "filename": "test.json",
  "contentType": "application/json",
  "part": "{\"key\":\"value\"}"
}
```

**Comment by somangshu** [comment]
Got it, Note:

- Internal property: `multipart`.
- Ref to this API should return `{
  "filename": "test.json",
  "contentType": "application/json",
  "part": "{\"key\":\"value\"}"
}`
- This can be a collection of similar objects if multiple files are selected

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @nidhi-nair 
Do we need a separate multipart property for this? filename and content type are already a part of the file object. Can't we just add the part field?

**Comment by nidhi-nair** [comment]
The idea behind using a separate property was to allow users to directly bind that property in the API pane and not have to worry about the format. It also protects this use case filed m future modifications. It felt like easier UX in the long run.

**Comment by Nikhil-Nandagopal** [comment]
The problem is this might lead to data bloat because the file object is already pretty large and that slows down the application. What if we modify the current object to match the specification?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal can we pick this up, Or do you suggest any changes here?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu go for it. Just check whether there is no duplication of file content in the bindings otherwise it will lead to perf challenges

**Comment by techbhavin** [comment]
@somangshu  @nidhi-nair  @Nikhil-Nandagopal 

As discussed with @nidhi-nair  as we have already present `files` property, there is no need to Include a new property in the file picker to support multipart uploads.

so if everyone is agree on this then can we close this issue?

**Comment by nidhi-nair** [comment]
The implementation for multipart requires #5547, but we can default to the structure that already exists as @Nikhil-Nandagopal suggested. I am a little skeptical of whether the raw data is stored accurately on the backend, but that will be a separate issue to solve, if it exists. Closing this issue with the directive that we always use the following structure to achieve this goal:
```
{
  "name": <filename>,
  "type": <mime_type>,
  "data": <file_data_in_raw_or_base64>
}
```
