### ISSUE TITLE
[Enhancement] Bearer token gets placed into the header when added via API url

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5506]
Steps to reproduce:
1) Add an API with Bearer token
2) Click on Add Datasource
and observe the header

Observation:
It is observed that the Bearer token gets placed into the Header field and under list of API datasource, it is represented as a header and not as a Bearer token. 

Expectation:
It is expected that the API has a defined Bearer token hence must be placed into the data source reading that 

Screenshot:
![Screenshot 2021-06-30 at 7 16 15 PM](https://user-images.githubusercontent.com/71753653/123975753-37132980-d9db-11eb-905e-e55851830b8a.png)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac I didn;'t understand this. Bearer tokens are usually sent via the headers itself.
