### ISSUE TITLE
[Feature] Remove Mixpanel and segment from Self Hosted

### ISSUE THREAD

**Issue by wlatic** [appsmithorg/appsmith#5512]
## Summary

Would be good to remove Mixpanel and Segment from the selfhosted version of appsmith (Im guessing this could actually mess up some of your reporting).

In the future I'd be 100% for "sharing metrics" to ensure my instance can be used to improve appsmith.

## Motivation

We have a private application and external tracking is worrying!

## Additional Context

No additional context

**Comment by Nikhil-Nandagopal** [comment]
Hi @wlatic 👋 actually our telemetry is completely opt in and does not track anything unless you agree to it during installation. You can find details on this in our documentation with easy steps to disable it in case this was accidentally enabled for you.
https://docs.appsmith.com/telemetry#disable-telemetry
Hope this helps 🙂

**Comment by wlatic** [comment]
This was me enabling what i thought was needed for you guys but wasnt!
