### ISSUE TITLE
[FEATURE] Show message when trying to connect to local host

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#552]
## Summary

Users some times try to connect to a local host and don't understand why they can't see any data

## Motivation
Showing a helpful error message will unblock the user.

**Comment by sumitsum** [comment]
Closed in https://github.com/appsmithorg/appsmith/pull/3611

**Comment by sumitsum** [comment]
Re-opening to track client side changes. Server side changes had been merged with the linked PR.
