### ISSUE TITLE
[Bug] Clicking on a specific comment notification redirects me to homepage

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#5520]
## Description

I was clicking on notifications on Appsmith's Standup App. For one of the comments, it kept redirecting me back to the home page.

### Steps to reproduce the behaviour:

https://www.loom.com/share/8158e96018ab4a2e952df9f33c2cfa92

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@nayan-rafiq this should be fixed now right?

**Comment by rishabhsaxena** [comment]
Yeah this should be fixed now, we have the `pageId` missing for this comment and we updated the link logic to use this field.

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena not working on prod

**Comment by rishabhsaxena** [comment]
I had verified the above comment, it was an old comment with the `pageId` missing
