### ISSUE TITLE
Input widget - low effort enhancements

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5525]
# RACI matrix
| Label | Value | 
| ------------- | ------------- |
| Responsible |  @techbhavin |
| Accountable | @somangshu  |
| Consulted | @areyabhishek, @momcilo-appsmith |
| Informed |  @Nikhil-Nandagopal |

## Features:
- [x] Tooltip text - Helper for input
- [x] Label text - This text appears beside or on the top of the input widget
- [x] Auto Focus - This can be a switch and will determine whether the input text will automatically bring up the keyboard and gain focus on load
- [x] Icon - Choose an icon to show in the input field
 - [x] Icon alignment - left or right
- [x] Max Chars - This number specifies the maximum number of characters

# Requirements

| Requirement | User story | Priority | Comment |
| ----- | ------ | ------- |  -------- |
| Tooltip text | Helper for input | High | [Design](https://www.figma.com/file/O1tKizBK5SHhWPcPT4RWIs/Input-Updates-(Label-%26-Tooltip)?node-id=2%3A1) | 
| Label text | This text appears beside or on the top of the input widget | High | [Design](https://www.figma.com/file/O1tKizBK5SHhWPcPT4RWIs/Input-Updates-(Label-%26-Tooltip)?node-id=2%3A1) |
| Auto Focus | This can be a switch and will determine whether the input text will automatically bring up the keyboard and gain focus on load | High | - |
| Icon | Choose an icon to show in the input field | High | - |
| Icon alignment | left or right | High | - |
| Max Chars | This number specifies the maximum number of characters | High | - |
| isValid | JS convertible toggle to set the validation using expressions instead of regex | Medium | - |

**Comment by YogeshJayaseelan** [comment]
@techbhavin Tested this feature and i could verify the following points 

**Verified:**
1)Tooltip text | Helper for input 
2)Label text | This text appears beside or on the top of the input widget

**Not Verified: - Implementation is required**
3)Auto Focus | This can be a switch and will determine whether the input text will automatically bring up the keyboard and gain focus on load 
4)Icon | Choose an icon to show in the input field 
5)Icon alignment | left or right

**Comment by techbhavin** [comment]
waiting for close issue #3261

**Comment by somangshu** [comment]
@techbhavin please merge branch to use the new control here.

**Comment by areyabhishek** [comment]
@techbhavin Great work! Noticed a bug: By the default the input widget is in an error state because of the 'Max chars' field being empty. This shouldn't happen.

@somangshu We need to provide styling controls for the label. Exact same controls like in the text widget. These controls can be in the property pane under 'styles'

**Comment by somangshu** [comment]
@techbavin lets add the following:
- Label color: Hex color picker
- Label size: All sizes available for the text widget
- Label font style: Bold/Italics

**Comment by rishabhsaxena** [comment]
@somangshu @Nikhil-Nandagopal 
should we also add another field to the input widget `isValid` similar to `isDisabled`? might make it easier to set the validation state of the input without using regex.
