### ISSUE TITLE
[Bug] Not able to rename the API name from the entity explorer

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5554]
## Description

I am not able to rename an API name from the entity explorer to a new non-existent name. I can do this from the API pane but not from the entity explorer. For example, I have Api4 on Page 2, but not on Page3.  On Page3, I can't rename my API to Api4.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/680a50c3cbe74fbfaf95d5e36fcbcbee-00001.gif)](https://www.loom.com/share/680a50c3cbe74fbfaf95d5e36fcbcbee)

### Steps to reproduce the behaviour:

 
1. Add a page with 2 APIs (call them Api1, Api2)
2. Add another page and now add an API
3. Try to rename new API on page 2 to Api2.
4. You should see the error

### Important Details

- Version: Cloud
- Environment: Production

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni IIRC, names are meant to be unique across pages so the fix should be to disallow it from the API pane

**Comment by sumitsum** [comment]
I have noticed that if I have `Api1` on page 1 and then I create a new API on page 2, then it gets created as `Api1` by default. This would have to be changed as well, in case the names are scoped across all pages.

**Comment by sumitsum** [comment]
@Nikhil-Nandagopal As per the discussion we had today in the actions pod daily standup, the action names should be unique only within a page. Across pages, the names can coincide. There is another issue raised regarding this : https://github.com/appsmithorg/appsmith/issues/7301

**Comment by sumitsum** [comment]
Closing in favor of #7301.
