### ISSUE TITLE
[Bug] Table widget breaks on drag and drop 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5559]
Steps to reproduce:
1) Navigate to Datasource
2) Create a Query
3) Click on Add widget/Generate widget
4) Now click on Widget
5) Add a table widget
and observe

Observation:
It is observed that the table breaks on simple drag and drop after the widget are binded to a Query

Expectation:
It is expected that the table works on simple drag and drop 

Video:
https://www.loom.com/share/5aca6f0979094fc6867d93ad4e4ca023

![Screenshot 2021-07-02 at 5 20 05 PM](https://user-images.githubusercontent.com/71753653/124278639-1f1ae180-db64-11eb-9887-b37e94b22162.png)

**Comment by somangshu** [comment]
This is already been taken care in #4376. Closing this
