### ISSUE TITLE
[Bug] Select widget binding error state

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#5560]
## Description

Hey guys, I'm binding this in my select widget:

```
{{getCompanyInfo.data.map((item) => {
  return {
    label: item.Teams,
    value: item.Teams,
  };
});
}}
```

I'm still seeing This value does not evaluate to type "Array<{ label: string, value: string }>". Transform it using JS inside '{{ }}' this error.

The error state does not go off, even the binding matches the expected datatype.  

<img width="620" alt="CleanShot 2021-06-11 at 19 31 18@2x" src="https://user-images.githubusercontent.com/16307796/124284552-baaf5080-db6a-11eb-8eb2-ad9a7e6a9c31.png">

### Steps to reproduce the behaviour:

1. Add a select widget
2. Bind data with a map function

**Comment by Nikhil-Nandagopal** [comment]
@vihar are there any duplicates in the array? That is known to cause this issue

**Comment by Nikhil-Nandagopal** [comment]
@somangshu we need to fix the messaging here to indicate that the error is due to a duplicate

**Comment by vihar** [comment]
> @vihar are there any duplicates in the array? That is known to cause this issue

No, I don't have any duplicate objects in my array. However, I'll cross-check this again and get back.

**Comment by vihar** [comment]
My data has duplicate values, removing this solves the issue. Thanks, @Nikhil-Nandagopal.
