### ISSUE TITLE
[Bug] API fetching JSON file fails

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#5561]
## Description

A user was trying to fetch the contents of the below file in the API pane but is getting an error around JSON parsing
https://media.goodgamestudios.com/Moonshots/BigFarmHomeAndGarden/Rooms/v5/Android/AndroidVersions.json

**Comment by mohanarpit** [comment]
This is happening because the response header for this link is `application/json` but the file content is invalid JSON. This needs to be resolved by the API itself.

Closing this issue. Please re-open if required.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit reopening this because postman handles this. The idea is that we don't necessarily need to parse the response because of the content header. Isn't that a valid point?

**Comment by mohanarpit** [comment]
Hmm ... the reason that we parse the JSON into an object is so that the client can simply refer to JSON objects in the response. 

A quick solution for this would be to attempt parsing the JSON on the server and if we fail, we simply set the raw String in the response body. Will test this flow out.

**Comment by Nikhil-Nandagopal** [comment]
Yeah I think that's a good solution. The response can be a string in this case

**Comment by ajinkyakulkarni** [comment]
Another use is facing this problem. This time error this error that is being returned is **"Plugin failed to parse JSON"**

**Comment by ClarksonCote** [comment]
I'm having a similar failure right now in AppSmith, is there a chance this issue has cropped back up?

I get a "Plugin failed to parse JSON" message. I am trying to POST to graphql, and our method works fine in Postman but this error appears here. Presumably because it's parsing the graphQL statement as JSON instead of treating as raw.
