### ISSUE TITLE
[Feature] Dummy data in a table.

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#5564]
Thoughts on improving the dummy data in a table. 
- We see a lot of users confused by the dummy data and they try to modify the JSON body instead of adding an API. 
- The dummy data is long, so they miss the other table controls.
- Only first time users benefit from the dummy data that shows them a few features of the table. Repeat users need to repeatedly clear the table before using it.
- When there’s no data in the table we see ‘This value doesn’t evaluate to Array<object>’ Do users understand what this means? I don’t find any results in our documentation nor on Google when I search this phrase.

Suggestions on improving it:
- We shouldn’t show the JSON body in the table at all and keep it empty. We have a new upcoming CTA that’ll ask the user to connect to data. 
- If we have to show dummy data, can we hide the actual hard coded data in the property pane because users are confused by it?
@somangshu @Debsourabh @momcilo-appsmith @Nikhil-Nandagopal Thoughts on this?

**Comment by Nikhil-Nandagopal** [comment]
Maybe we can show the input in a special state that indicates there is mock data and when you focus on the field, the input becomes empty and you should connect your own data. If you focus away, it comes back. This way it's not confusing why the table has data but the input is empty.
I see this as a consistent experience we should give for Table / Chart / List / Dropdown

**Comment by somangshu** [comment]
Yes init state makes sense here, where we:
- Reduce the height of the `table data`
- Show as a comment / helper that this is dummy / mock data.
- onClick empty the field and also show a placeholder of how to connect to API

Question: Should in general `codeEditor` consume less space when property pane loads and expand to full height onFocus?

**Comment by areyabhishek** [comment]
Agreed with the solutions. Few more points:
1. Empty data state shouldn't be an error state like it is today
2. Can mock data only appear as a single line instead of being long?

The general code editor shouldn't occupy less space because users switch between property pane and other APIs quickly. it'll be painful to expand the editor and make a small change.

**Comment by somangshu** [comment]
@areyabhishek:
1. I dont think its right to do this. The widget is actually at an error state without data. Do you wish to change this default behaviour, Or only in specific case this should not show up any errors.
2. By default, even if the mock data is in a single like the amount of space it covers is not going to be less. 

We will need some design help to prototype this before we can actually pick this up for implementation. Let me know if a discussion is requrired

**Comment by areyabhishek** [comment]
@somangshu About point 1, not having any data shouldn't be an error state for the table. It's something we should do across the board. Most widgets are not in an error state when there's no data. @vivekverma2312 could you check this?

Let's talk to @momcilo-appsmith and try some design prototypes.
