### ISSUE TITLE
[Bug] Binding instruction shows up when / commands are open

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#5565]
The instruction to type {{ }} shouldn't show up in the input fields when the / commands are open. The blue card peeking behind the / menu shouldn't show up.
1. <img width="265" alt="Screen Shot 2021-07-03 at 4 21 59 AM" src="https://user-images.githubusercontent.com/30255708/124334918-37b3e780-dbb6-11eb-8952-f04616bef680.png">
2. <img width="322" alt="Screen Shot 2021-07-03 at 4 21 40 AM" src="https://user-images.githubusercontent.com/30255708/124335002-7a75bf80-dbb6-11eb-9973-92f4b76dccdd.png">

**Comment by pranavkanade** [comment]
Fixed with https://github.com/appsmithorg/appsmith/pull/5558
