### ISSUE TITLE
[Feature] Simplify Appsmith deployment experience for non-developers

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5592]
## Summary

We need a way for non-developers to quickly self-host Appsmith.  A [user](https://discord.com/channels/725602949748752515/725609493974614076/861507513865994240) on Discord asked for this feature.

## Motivation

Current deployment methods require exposure to deploying applications and some complicated dev/DB setup. It would be very helpful to streamline the current deployment experience further.

**Comment by Nikhil-Nandagopal** [comment]
Non-developers should use our cloud version. We'll relook at this later
