### ISSUE TITLE
[Bug] UX : The colour code in the Form widget property pane overlaps the field 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5595]
Steps to reproduce:
1) Add a form widget
2) Click on the property pane of the widget
3) Click on the background-color 
and observe

Observation:
It is observed that the form widget color palette overlaps on the field and user has less visibility on the field 

Expectation:
The color palette must be placed in such a way that the user would be able to see and focus on the field 

Screenshot
![Screenshot 2021-07-05 at 2 53 18 PM](https://user-images.githubusercontent.com/71753653/124453960-896e9480-dda5-11eb-9df3-74fe41c98153.png)

**Comment by somangshu** [comment]
Resolved in #4413. Please check the deploy preview

**Comment by jsartisan** [comment]
Closing as it's been fixed.
