### ISSUE TITLE
[Bug] SSL Mode dropdown is creating extra white space in the lower half of the screen and creating a extra scroll bar in PostgreSQL Plugin

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5618]
## Description

[What happened]

### Steps to reproduce the behaviour:
https://drive.google.com/file/d/19AOUsF9nv3ULsMTjLXoPFItE8uinp-Jb/view

### Important Details

- Version: [Cloud]
- OS: Windows, Mac
- Browser Chrome
- Environment [production]

**Comment by hetunandu** [comment]
Not able to reproduce anymore 

https://user-images.githubusercontent.com/12022471/135251169-4fdafe86-1992-40aa-bac8-0f0c68c63a7b.mov

**Comment by prapullac** [comment]
@hetunandu Unable to reproduce this as the dropdown opens upwards
