### ISSUE TITLE
[Bug]  Cyclic dependency when JS binding contains strings matching with widget names

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5621]
## Description

I was helping a user debug a cyclic dependency problem. As soon as I added  "atm" key in a widget binding (which is returned from the API), the error showed up. After a lot of time, I figured out that the user also has the switch widget called "atm" which is referring to the widget.  But this is not real cyclic dependency and key "atm" is different from element "atm".    

For more information, please refer to this internal thread https://theappsmith.slack.com/archives/C01HXJPFWBC/p1625498880378500 

### Steps to reproduce the behaviour:

1. Have your API output a key called "atm" and bind it to a list widget specifically by using doing something { "atm" : data["atm"]}
2. Create a widget called "atm"
3.  In this widget, use the "atm" key from the list widget.
4. You should now see the cyclic dependency 

### Important Details

- Version: Cloud 
- Browser Chrome
- Environment: Production

**Comment by ajinkyakulkarni** [comment]
Split this issue into two, another one here now https://github.com/appsmithorg/appsmith/issues/5657

**Comment by hetunandu** [comment]
Will be fixed with #2435
