### ISSUE TITLE
[Bug][Deploy Preview-5558]The Bind data autocomplete dropdown should not be  displayed for any of the input boxes in the query pane

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5623]
## Description

[What happened]The bind data autocomplete dropdown should not be  displayed for any of the input boxes in the query pane

### Steps to reproduce the behaviour:

1.Go to the Datasource page
2.Select the Mongo Db
3.Select the new query
4.click on the collection name input box
5.The bind data autocomplete is displayed 

Expected result: The bind data autocomplete should not be displayed inside the query pane
![image](https://user-images.githubusercontent.com/45958978/124540654-81623380-de3d-11eb-8197-2ce51eae4541.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment [production]

**Comment by pranavkanade** [comment]
Deploy Preview link - https://deploy-preview-5558--appsmith-editor-ce.netlify.app/
Original PR - #5558

**Comment by pranavkanade** [comment]
Fixed Check - https://deploy-preview-5558--appsmith-editor-ce.netlify.app/
