### ISSUE TITLE
[Bug][Deploy Preview-5558]The evaluated value pop up is not closing inside the query pane 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5624]
[What happened]The evaluated value pop up is not closing inside the query pane 

Steps to reproduce the behaviour:
1.Go to the Datasource page
2.Select the Mongo Db
3.Select the new query
4.click on the collection name input box
5.Verify the display of evaluated value pop up

Expected result: The evaluated value pop should close when the user clicks outside the query pane
![image](https://user-images.githubusercontent.com/45958978/124541084-56c4aa80-de3e-11eb-96d2-cf476beef2d3.png)

Important Details
Version: [Cloud ]
OS: Windows
Browser Chrome
Environment [production]

**Comment by pranavkanade** [comment]
Deploy Preview link - https://deploy-preview-5558--appsmith-editor-ce.netlify.app/

**Comment by pranavkanade** [comment]
@ajinkyakulkarni could you please ask somebody to take this on priority?

**Comment by pranavkanade** [comment]
Fixed - https://deploy-preview-5558--appsmith-editor-ce.netlify.app/
