### ISSUE TITLE
[BUG] Large query responses lead to page timeouts

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#563]
## Description

Queries returning large amounts of data cause /actions to time out preventing users from editing the application. 
This happens rarely with queries of response sizes > 1 - 2mb.
The core cause is the response cache which is used to generate the autocomplete for queries

**Comment by mohanarpit** [comment]
This has been pushed to `master`. We no longer send the cached response. In future, we'll implement a better solution to extract the schema of the JSON body and only send that metadata. 

For now, closing this issue.
