### ISSUE TITLE
Include refresh button in the table

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5630]

**Comment by somangshu** [comment]
@momcilo-appsmith we need design help here. @vibhandikyash please get in touch we when we get here

**Comment by somangshu** [comment]
@Nikhil-Nandagopal do you think this should be worked on given there is an alternate present today

**Comment by Nikhil-Nandagopal** [comment]
I think this is slightly different but can be achieved using an external button so not a big priority. Also not many community requests
