### ISSUE TITLE
[Feature] : Support Currency as a new column in the table widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5632]
# Objective:
Introduce a new column type currency in the table widget.

# Requirement:

| Title | Description  | Comment | 
| ------ | ------ | ------- | 
| Column properties | Just like button properties this will appear | | 
| Auto format | The value computed in the currency column will be auto formatted | - |
| Currency symbol | The user will be provided a dropdown to select the currency of there choice | - |
| Decimals | Precision point for the computed value | - |

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5h28c)

**Comment by GreenFlux** [comment]
Another user in Discord is requesting this feature:
https://discord.com/channels/725602949748752515/1076320585002532976
