### ISSUE TITLE
Include menu button as column type

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5636]
# Objective
We will introduce the menu button in the table column, Follow all properties of the button column type and the menu button widget.

# Requirement
| Title | Desc | Comment | 
| ------ | ------- | ------ |
| Inherit props | All props from the menu button should be imported | We need to check if the same UX will be suffice here to add menu items, Since we are already one level down in the table column | | 
| others | All other properties from the button column | |

**Comment by somangshu** [comment]
@Tooluloope please consult @momcilo-appsmith & @riodeuno for the UX we are developing here.

**Comment by momcilo-appsmith** [comment]
@somangshu I have just seen this issue - I think the menu button can work the same way, but @Tooluloope if you can show this on one of our standups that will be good.

**Comment by somangshu** [comment]
@momcilo-appsmith apologies for completely missing this, Please check [this](https://deploy-preview-7039--appsmith-editor-ce.netlify.app/) deploy preview out, Let me know if you have any queries

**Comment by momcilo-appsmith** [comment]
@somangshu This deploy preview is not working as well. Is there a time period in which I can view these and they get deleted after that?

**Comment by somangshu** [comment]
@momcilo-appsmith nothing like that I think, It seems to be working on my end. Let me know on DM if you still face problems
