### ISSUE TITLE
[Bug]Rest Api plugin not encoding character properly in response

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#5639]
## Description

If the response of the API contains Chinese characters (supported by UTF-8), the response body seen by the user has incorrect Chinese characters than expected

If the expected response is as follows :
```
[
 {
   "id" : "1",
   "name" : "刘备"
 }
]
```
The user sees the following in the rest API response body : 
```
[
 {
   "id" : "1",
   "name" : "鍒樺"
 }
]
```

The Chinese characters seem to get translated erroneously

**Comment by trishaanand** [comment]
Expected output : 
![expected](https://user-images.githubusercontent.com/8403079/124587947-db7eeb00-de75-11eb-8ae0-29147d84abd5.png)

The response received on the other hand in rest api plugin is :
![eral](https://user-images.githubusercontent.com/8403079/124587998-e8034380-de75-11eb-8928-31c82cfbe1f6.png)

**Comment by prapullac** [comment]
Adding verified label as the user has verified the issue
