### ISSUE TITLE
[Epic] Custom JS Library

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#5668]
**Problem statement**
Provide a way to add or remove Javascript packages at runtime. Currently, we provide few Javascript packages that are configured before the app is built, hence if a user needs any other Javascript package, they must edit the app and re-build. 

**Success Criteria**
(1) Provide a search box where user can find any available Javascript package. 
(2) Javascript package can be added or removed at runtime. Any addition / removal is per application level. 
(3) Auto-complete works with any custom Javascript package that gets added. 

Reference:
https://www.notion.so/appsmith/Custom-JS-Libs-V2-5a17144434e744a38d6d2868b158dea8

**Comment by trepatk** [comment]
Hi,
Is it possible for us to install a JavaScript library via npm to use in our app.  In particular we are interested in the, 
ACL JavaScript library based on the Zend Permissions ACL which is a 100% pure Javascript library which we think would lend itself perfectly to appsmith.

Thanks

**Comment by billyrudi** [comment]
There are many npm packages that are useful:
Mqtt.js or sweetalert or leaflet or pdf creator etc...
So the ability to add the is a great.

**Comment by ahmadalibaloch** [comment]
Need to export page is PNG or PDF!

**Comment by sumitsum** [comment]
Thanks @billyrudi and @ahmadalibaloch for bringing these use cases to our notice 🙌 . We will try to incorporate these libraries in v1 of this feature release.

**Comment by chrispytoes** [comment]
Sorry, I'm a little new to Appsmith and I'm trying to figure out how to add custom packages myself, and from your original post it sounds like you're implying that it is currently possible to add custom packages with a little extra work.

> hence if a user needs any other Javascript package, they must edit the app and re-build.

What do you mean by this? Are you talking about editing and re-building the entire Appsmith server, or just the application I'm creating? What do I need to edit to add custom packages currently?

**Comment by sumitsum** [comment]
Hi @chrispytoes , yes currently the Appsmith client code needs to be re-built in order to add a new custom JS package.

**Comment by arunvjn** [comment]
This project will be tracked in https://github.com/appsmithorg/appsmith/issues/16394
