### ISSUE TITLE
[Feature] Versioning History

### ISSUE THREAD

**Issue by exAntares** [appsmithorg/appsmith#5673]
## Summary

Ever seen the google spreadsheet history, or Git history, it would be great to have such historic changes on the admin panel, in case someone breaks something it is possible to rollback to a previous version and redeploy.

## Motivation

There is an UNDO button that appears after deleting some widgets. But if I start changing JS code inside widgets, and change them again, and then delete their content, I may forget what some widgets had before.

## Additional Context

Example from google spread sheets
![image](https://user-images.githubusercontent.com/3364232/124757817-45f36200-df2e-11eb-87d2-3ae605b41668.png)

**Comment by Nikhil-Nandagopal** [comment]
Hi @exAntares 👋 
We're now integrating with git repositories #3199. This will allow for branching and version control :)

**Comment by exAntares** [comment]
Would that be available for the cloud hosted?

**Comment by Nikhil-Nandagopal** [comment]
Yes it will be! 🙂
