### ISSUE TITLE
[Bug]In the query pane the evaluated value pop up is moving up and down when the user is scrolling the page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5687]
## Description
[What happened]In the query pane the evaluated value pop up is moving up and down when the user is scrolling the page

### Steps to reproduce the behaviour:

1.Click on + icon Datasources in entity pane
2.Connect to mongo database
3.From the active tab 
4.click on the new query button
5.under the query tab 
6.click on the collections name input box 
7.do the page scroll up and down 
8.the evaluated value pop up is moving around the page 

![image](https://user-images.githubusercontent.com/45958978/124853552-ad0f2600-dfc3-11eb-8a07-6360384c46b0.png)

https://drive.google.com/file/d/1uPkT_kRQY7H58lDocFIBgYFe9kaCe02N/view
### Important Details

- Version: [Cloud ]
- OS: Windows
- BrowserChrome
- Environment  release

**Comment by bharath31** [comment]
this is no longer reproducible with the new evaluated value pane improvements
