### ISSUE TITLE
[Bug]The dropdown should close instead of sticky dropdowns when user is scrolling in the database query pane

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5688]
## Description

[What happened]The dropdown should close instead of sticky dropdowns when user is scrolling in the database query pane

### Steps to reproduce the behaviour:

1.Click on + icon Datasources in entity pane
2.Connect to MySql database
3.Inside the database connection page
4.click on SSL option dropdown
5.Scroll the page Up and down
6.the dropdown is moving up and down along with the scroll

![image](https://user-images.githubusercontent.com/45958978/124855085-0ed08f80-dfc6-11eb-87f2-08a45b504033.png)

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment release

**Comment by Nikhil-Nandagopal** [comment]
@albinAppsmith seems like a problem with our design system
