### ISSUE TITLE
[Bug]when the user click on new API its throwing an error in google sheet

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5689]
## Description

[What happened]when the user clicks on new API it's throwing an error in the google sheet

### Steps to reproduce the behaviour:

1. Go to create new data sources page
2. Connect to google sheet data source
3. click on the google sheet from the entity pane
4. click on new API Button 
5. It throws an error

![image](https://user-images.githubusercontent.com/45958978/124856477-37598900-dfc8-11eb-80de-9720df5c5dc0.png)

https://drive.google.com/file/d/1dEtFbOf9_awBRAXWhVSk2Z4eC4PTgibb/view

### Important Details

- Version: [Cloud]
- OS: Windows
- Browser chrome
- Environment release

**Comment by pranavkanade** [comment]
Duplicate of #5680
