### ISSUE TITLE
[Feature] Need an option to wrap text inside a table

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#5693]
PRD

<h2>Objective</h2>
<p>Today our app-viewers have to hover on a cell to see the details for a long text field. We want to allow developers to choose if they want to wrap long text in a column for easier display.</p>
<h2>Success Metrics *</h2>

Goal | Metric
-- | --
Allow devs to customise their apps better | Customer satisfaction score increases

## Requirements

Requirement | User story
-- | --
Appsmith developers can enable ”Wrap text” property for columns, which results in content in columns getting wrapped, while it increases the height of the whole row if necessary. | As a user I want to wrap column text than show it on hover to facilitate consumption easily
“Wrap text” can be a JS convertible property | As a user, I want to wrap only for a specific scenario which I can control
“Wrap text” property will have the Break words ( word-break) or Break all ( break-all)  and No wrapping (off) as options | As a user, I want to only wrap words when they reach a break point or wrap even if there’s no break depending on the width(useful for urls).
“Wrap text” property is only applicable for plain text and url type columns. Not applicable for the rest. |  

<p>“Wrap text” can be switched on for multiple columns, the expected behavior is to increase height of the row based on the column which needs the max height.</p>
<p>Upon width change of a column by a user, impact will be on the column’s height. This must also be considered.</p>
<p><strong>Pagination</strong></p>
<p>For client side pagination, upon word-wrap the pageSize changes dynamically.</p>
<p>For tables with server side pagination, if OnPageSizeChange is off. Then all the data will be shown with scroll, just like today.</p>
<blockquote>
<p>For tables with server side pagination, if OnPageSizeChange is ON. Then ?</p>
</blockquote>

## Documentation
<ul>
<li>Column properties will have a wrap text option. How does it work with pagination</li>
</ul>

## Out of Scope

- Text alignment of the wrapped column - left, right center (Needs to be discussed)

## Developer Handoff Document in Figma
Figma Link here

## RACI Matrix
Responsible |  
-- | --
Accountable |  
Consulted |  
Informed |

**Comment by somangshu** [comment]
@Nikhil-Nandagopal we cannot do this because it will require dynamically changing the height of the table component based on the content. There are other issues stuck because of the same problem.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu why would it need to change the height of the table? It should only update the height of the row right and rows that cannot fit the height will just be pushed to the next page / scroll right?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal We have the row height property which is fixed and the pageSize calculation is also based on that, changing the row hight dynamically could cause a problem

**Comment by Nikhil-Nandagopal** [comment]
Can we investigate how hard that would be? I thought this would be a simple fix

**Comment by Jiani0** [comment]
Is it possible to word wrap just the header of the table?
In production I see a lot of headers that have 2 or more words but the actual data in the column is just 2 or 3 characters long. But we need to preserve the enlarged column width in order to keep all the words in the header visible

**Comment by dncpax** [comment]
This is something I miss very much. Presently it seems table only works with short content. How do you propose to show a "remarks" column that can be 200 characters long? Or a full address?
If you show the entire column, then there's only space for just 1 or 2 columns before needing to scroll.
If you clip it there is no content, just the very short beginning. Even the on hover does not wrap...
Legacy apps do this effortlessly - but of course they suck in many other ways ;)

If not a table, is there an alternative? For instance, can a list do this?

**Comment by areyabhishek** [comment]
@dncpax Thanks for the request. We'll discuss this tomorrow like @ramsaptami mentioned. 
As a quick fix, would you be satisfied with a wrapped message in the on-hover tooltip?

**Comment by dncpax** [comment]
Hi there @areyabhishek. Well, honestly, it's not really a very good work around, but it would mitigate the situation a bit, since you could at least read what's there as opposed to now that you can't.

**Comment by Nikhil-Nandagopal** [comment]
@dncpax one workaround you could use is to use a list instead of a table. This way you can easily define the height of your large content and your users can read it upfront

**Comment by dncpax** [comment]
@Nikhil-Nandagopal yes, I thought about that and I'm trying it out. The issue here is that you have to fix the height of your text boxes, which defeats the purpose of having a table that adapts its height to the wrapped content. The only thing that is configured is the width of each column. The rest is native behaviour.
This is an example of a native html table in a legacy app:
![image](https://user-images.githubusercontent.com/2836636/142221075-0c0b60c7-9d28-4b2b-96c1-f441aaa980cc.png)
You can see the text wrapping, and the row height varying according to content.
I don't expect appsmith to mimick exactly this, but was hoping for a way to display some larger content.

**Comment by Nikhil-Nandagopal** [comment]
@dncpax totally understand, we'll work on a solution for this and make the text box heights dynamic too. 
You can make the text boxes scrollable in the list as a workaround till we ship this fix :)

**Comment by dncpax** [comment]
@Nikhil-Nandagopal That's actually a very nice idea!! I'll try it out!

**Comment by dncpax** [comment]
On that note, but a different matter, text box could use a vertical align option so every element can align perfectly side-by-side, to mimic a table...

**Comment by dilippitchika** [comment]
Updated PRD, needs some discussion @somangshu @sbalaji1192 @riodeuno 

CC @Nikhil-Nandagopal

**Comment by dilippitchika** [comment]
inline edit+word wrap

**Comment by somangshu** [comment]
@dilippitchika we could take a call to remove the onPageChange event as you suggested, let discuss ahead

**Comment by sbalaji1192** [comment]
@dilippitchika Currently pageSize is determined by the height of the widget divided by row height (currently constant across all rows). Recomputing the pageSize based on the wrapped cell will have its own problem. 
1. We will only know the height of the rows when they get rendered. so we need to calculate the pageSize after render as well. if there is a change in pageSize, UI would be jumpy.
2. When put together with inline editing, if the user edits a cell and enters a huge cell. we would need to recompute the pageSize.

So text wrapping will *not* have any effect on the pageSize, as a result, onPageSizeChange wouldn't get triggered.

**Comment by somangshu** [comment]
@sbalaji1192 small question, Given the formula to calc the pageSize, how is it that the wrapping does not effect the pageSize, cause I am assuming with wrapping the rowSize will obviously change. What am I missing here?

**Comment by sbalaji1192** [comment]
@somangshu Currently we have three size options for `DEFAULT`, `SHORT` and `TALL`. Each has a constant height and we use that to calculate the pageSize. We compute in such a way that there is no vertical scrollbar. With text wrapping, the size options will become minimum height of cells. And we use the minimum height to compute the pageSize. So with or without wrapped cell, the pageSize gonna be constant.

**Comment by somangshu** [comment]
Smart 🙂 

> We compute in such a way that there is no vertical scrollbar

How does this work, Specially without dynamic height?

**Comment by sbalaji1192** [comment]
Yeah. That should be the case with text wrapping. Based on the wrapped text, row height would increase thus the table body height will increase. so we will have a scrollbar visible.

**Comment by dilippitchika** [comment]
Adding suggestions on how word-wrap should work with inline-editing

**Inline editing independent of word-wrap**

When pressing shift enter while editing a cell | It should go into new line and resize but it should then wrap on the basis of the wrap type in the column.
-- | --
when the word is too long in a edited cell | It should go into new line but after changes are done, it should then wrap on the basis of the wrap type in the column

**Inline editing dependent on word-wrap**
When pressing shift enter while editing a cell | If wrap is enabled then pressing shift enter works, else it doesn’t
-- | --
when the word is too long in a edited cell | If wrap is enabled then it will go to the next line automatically, else user keeps typing in the same line

@momcilo-appsmith @sbalaji1192 please take a look

**Comment by momcilo-appsmith** [comment]
@dilippitchika This makes sense.

**Comment by momcilo-appsmith** [comment]
@dilippitchika @sbalaji1192 I just added a new section in the handoff file for Cell Wrapping. Let me know if you find anything that you think doesn't make sense.
[Figma link to designs](https://www.figma.com/file/JEalu7g3jDLzWWnKsfE6mB/Table-Improvements-2022?node-id=980%3A9163)
