### ISSUE TITLE
Remove old Gitlab CI build scripts

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#573]
## Summary

Remove older build scripts `.gitlab-ci.yml` from the entire code base as we no longer use Gitlab CI and have migrated to using Github Actions for building & testing Appsmith.

## Motivation

Having redundant files in the codebase can lead to confusion for new contributors.

**Comment by ari-hacks** [comment]
👋🏾 I'd like to take this one.

**Comment by ari-hacks** [comment]
Hey, @mohanarpit @Nikhil-Nandagopal is this issue up for grabs?

**Comment by mohanarpit** [comment]
@ari-hacks Yes. It's still available. Would you like to have a go at it?

**Comment by ari-hacks** [comment]
Yea, thanks!
