### ISSUE TITLE
[Feature] Support for converting API form workflow to curl requests

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#5736]
## Summary

Conversion of a curl Request to form flow is done on Appsmith under APIs, but it would be great if we can have a form flow converted back to a curl request, containing references to appsmith.store values and widget values. This way we can copy paste the url and paste in another project.

## Motivation

Appsmith provides an amazing functionality to copy paste widgets and containers across projects. 
`Trick: You can paste across multiple tabs with the copy paste shortcuts 😄.`
But it doesn't have any option to share APIs across projects. We currently depend on copy pasting the values switching tabs.

## Additional Context

I believe there are a lot of features being developed on the [JS Editor](https://github.com/appsmithorg/appsmith/issues/1751), and its an amazing Epic to be looking forward for. Not sure if this functionality is being resolved in that.
Until then if this request can be quickly done, it would be great. The same would be great for copy pasting Pages.

**Comment by Nikhil-Nandagopal** [comment]
@tomjose92 thanks for the feature request! As discussed, we need a way to copy APIs to other projects.

**Comment by GreenFlux** [comment]
+1, I was just about to make the same request. It would be amazing if we could copy the entire API with all the widget/JS binding and have them re-bind to matching widgets/JS in the destination app. This would be a great first step towards reusable modules that consist of multiple widgets, queries, and JS Objects. 

Alternatively, if we could just export a curl of all the _evaluated values_ from the API, without the bindings, that would still be useful to import into the next app. Even if the bindings have to be added back in manually, just being able to copy the curl request to the clipboard would save a lot of time in duplicating APIs between apps.
@rlnorthcutt

**Comment by aswathkk** [comment]
This would be a great addition since this helps us in debugging API requests.

#### My use case
I was getting an error from the API saying that one parameter that I pass in the URL should be an integer. While taking a look at the evaluated value for the URL, I found the parameter to be an integer only and I didn't get what did I do wrong. To know what exactly is being passed to the API, it would be great to have a cURL export feature.

**Comment by riteshkew** [comment]
This request will be covered as part of Packages. Closing the request here.
