### ISSUE TITLE
[FEATURE] AWS DynamoDB Integration

### ISSUE THREAD

**Issue by jerriclynsjohn** [appsmithorg/appsmith#574]
## Summary

We use DynamoDB extensively for our application and it'll be great if there was an integration for DynamoDB to build our internal applications.

## Motivation

There's a huge community of DynamoDB users that could benefit from this integration. There's an obvious push from AWS to support DynamoDB for some of their managed services like AppSync. It'll be great to see this integration come to life

**Comment by Nikhil-Nandagopal** [comment]
@jerriclynsjohn thank you for raising this feature request! @mohanarpit can we look at how to get this integration prioritised?

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 please update once you start picking this up 😃
