### ISSUE TITLE
[Bug] [intermittent] Drag and drop the widget and  click on slash icon  all the data sources suggestion are not displayed in the dropdown

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5741]
## Description

[What happened]when the first time user drag and drop the widget and  click on slash icon  all the data sources suggestion are not displayed in the dropdown

### Steps to reproduce the behaviour:

https://drive.google.com/file/d/18YDJywyBGVKVPjyxE4SLg1-Asj09zpr3/view

### Important Details

- Version: [Cloud ]
- OS: Windows
- Browser Chrome
- Environment  release

**Comment by arunvjn** [comment]
Displayed datasources are limited to 3. Other datasources are suggested as the user starts typing @RakshaKShetty

**Comment by RakshaKShetty** [comment]
Ya @arunvjn  but if see the below screenshot there is not suggest displayed 
![image](https://user-images.githubusercontent.com/45958978/125890581-181a5e15-9b86-4beb-8d67-63a425717d2a.png)

**Comment by RakshaKShetty** [comment]
As this issue is an intermediate issue I am reopening this

**Comment by Nikhil-Nandagopal** [comment]
This seems to be working now @RakshaKShetty can you re-verify?
