### ISSUE TITLE
[Bug] Binding get deleted on clicking JS and get reset to true by default

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5754]
Observation: Binding get deleted on clicking JS for all the property with toggle options.

### Steps to reproduce the behaviour:

1. Drag and drop a container widget
2. For visible property click on JS
3. Bind visible property 
4. Now click on JS and observe that toggle is enable
5. Again click on JS now you will observe that binding disappears

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3a22954151ef4c6f80485cd2fde433d1-00001.gif)](https://www.loom.com/share/3a22954151ef4c6f80485cd2fde433d1)

- Version: Cloud
- OS: MacOSX
- Browser e.g. chrome
- Environment: production

**Comment by Nikhil-Nandagopal** [comment]
This is the expected behavior
