### ISSUE TITLE
[Bug] For google sheet datasource, on successful connection user gets redirected back to same page

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#5759]
## Description
User get redirected back to same editor page for google sheet datasource on successful connection

### Steps to reproduce the behaviour:
1. Create New Google sheet datasource
2. Click Continue
3. Follow all steps

### Important Details
- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [release]

**Comment by RakshaKShetty** [comment]
@nidhi-nair the issue still persists User gets redirected back to the same editor page for google sheet Datasource on successful connection

**Comment by pranavkanade** [comment]
fixed with https://github.com/appsmithorg/cloud-services/pull/30 & https://github.com/appsmithorg/cloud-services/pull/31
