### ISSUE TITLE
[Bug] Aarango DB : CA Certificate String  is not encoded and visible to the user before saving it

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5762]
Steps to reproduce:
1) Navigate to Aarango DB 
2) Add credentials 
3) navigate to SSL 
4) Add SSL Mode : Enabled 
5) Add Use CA Certificate : Base 64 String
6) Add "Base64 Encoded CA Certificate String "
and observe

Observation:
it is observed that the Base64 Encoded CA Certificate String is displayed as it is and can be copied by others. However, this is visible only until save 

Expectation:
Since it is encrypted it must be displayed in asterisks or dots like other database keys

![Screenshot 2021-07-08 at 3 22 27 PM](https://user-images.githubusercontent.com/71753653/125063913-b389c480-e0cd-11eb-8db8-9bb701d2d5e8.png)

**Comment by sumitsum** [comment]
Closed via https://theappsmith.slack.com/archives/CPQNLFHTN/p1628592522041700
