### ISSUE TITLE
[Bug] Download is not functional on image widget if we pass URL in image property

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#5764]
Observation: 

### Steps to reproduce the behaviour:
1. Drag and drop a image widget
2. Enter image url in image property (`https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg`)
3. Enable download property
4. Now if I click on download icon then nothing happens

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser  chrome, safari
- Environment release and release-frozen

<img width="1792" alt="Screenshot 2021-07-09 at 4 56 58 PM" src="https://user-images.githubusercontent.com/83569920/125071262-b0df9d00-e0d6-11eb-8bd4-a81ff503646b.png">

**Comment by aswathkk** [comment]
This happens due to the CORS issue.
We may need to set up a proxy that bypasses CORS to download files.

**Comment by somangshu** [comment]
👋  @aswathkk, Thanks for talking the time to understand the problem here 😃 . We will look into this further and build a fix around it soon. This is only happening in specific cases. Otherwise the feature is working as intended.

**Comment by somangshu** [comment]
@vivekverma2312 Based on [this](https://www.codeproject.com/Questions/5273909/How-to-download-image-file-from-cross-domain), the image will not be downloaded as the origin website does not allow cross origin, As @aswathkk  has pointed out ☝️  this could be achieved with the help of a backend API which adds the necessary headers, Thats is something we will have to prfioritize low. However, We can do the following:
- If we receive the error we open the image in the browser, in a new tab. This resolves the immediate problem.
- The fallback from this would be to show an error toast > "The origin website does not allow download of this image"

cc @areyabhishek
