### ISSUE TITLE
[Bug] Google Sheet Auth redirect to different URL 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5787]
Steps to reproduce:
1) Navigate to Datasource
2) Click on Google Sheet 
3) Add permission "Read and Write"
4) Click on "Continue"
5) User can select Gmail Id for use
6) Add permission 
and observe

Observation:
it is observed that the Google sheet permission is navigated to a different environment

Expectation:
User must be able navigate to query page 
![Screenshot 2021-07-12 at 11 37 18 AM](https://user-images.githubusercontent.com/71753653/125289664-2187f300-e33d-11eb-83dc-6ad526328157.png)

**Comment by nidhi-nair** [comment]
@prapullac Closing this since it was related to the set up of the release frozen environment and has been fixed.
