### ISSUE TITLE
[BUG] Install script fails without helpful message if curl fails on line install.sh:338

### ISSUE THREAD

**Issue by srijanshetty** [appsmithorg/appsmith#579]
## Description

curl failed on line install.sh:338 and the script exited without any helpful message

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Run install script
2. If curl fails, no helpful message is seen

### Important Details
 - Version: [release v1.2.4]
 - OS: [Ubuntu 20.04]

**Comment by Nikhil-Nandagopal** [comment]
@srijanshetty thank you for the issue and the fix! Will prioritise getting this reviewed

**Comment by mohanarpit** [comment]
Thanks @srijanshetty for this PR!  🎉 

This has been merged into our `release` branch. Will be available on `master` in Appsmith's next version.
