### ISSUE TITLE
[Feature] Ability to watch a remote branch: auto deploy when the remote branch has new commits

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5791]

**Comment by abhvsn** [comment]
@hiteshjoshi this can be a potential duplicate of https://github.com/appsmithorg/appsmith/issues/11522, should we close this as more context is present in the other ticket?

**Comment by abhvsn** [comment]
Closing this as possible duplicate of https://github.com/appsmithorg/appsmith/issues/11522
