### ISSUE TITLE
[Feature] Keep scroll position while adding comments to scrollable containers / widgets

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5795]

**Comment by pranavkanade** [comment]
Initial investigation investigation into the issue points to `re-rendering` as a prominent cause. Adding the profiling outputs for following case - 
User has scrolled into a container and when switches to comment mode.
> The first image clearly shows the table widget being re-rendered.
> Flame graph in second image shows that all the child components under `Table` widget components also re-rendered. Which resets the scrollbar position.

![Screenshot 2021-07-22 at 3 45 48 PM](https://user-images.githubusercontent.com/13262095/126632663-5b9ecf69-c7ee-4abc-a07d-324b2bb0e586.png)
![Screenshot 2021-07-22 at 4 57 05 PM](https://user-images.githubusercontent.com/13262095/126632670-770ba789-62b7-45f1-abaf-ecef7c401b60.png)

**Comment by rishabhsaxena** [comment]
Actually this issue has two parts, apart from preventing re-renders we would also like to add the comment pin at the correct offset based on the scroll. That could be a part of another PR
