### ISSUE TITLE
[Bug]Property Pane - The “Add api” is missing in the dropdown on click action Widget: List/Table/Tab/Chart/Select

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#5802]
## Description

[What happened]

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@arslanhaiderbuttar I don't see a description here

**Comment by arslanhaiderbuttar** [comment]
@Nikhil-Nandagopal It's added. Check now.
