### ISSUE TITLE
[Bug] Comment icon showing red dot but no comments present in the list

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#5803]
## Description

When I click on the comment icon, I can see a red dot indicating that I have unread comments. But on switching to comment mode, I see no comments in the list.

<img width="593" alt="Screenshot 2021-07-12 at 9 04 39 PM" src="https://user-images.githubusercontent.com/458946/125315693-ff01d400-e354-11eb-86b9-c39ede6c23ed.png">

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by rishabhsaxena** [comment]
Closing this, since the fix is merged to release
