### ISSUE TITLE
[Bug]Property Pane - The “Add api” is missing in the dropdown on click action Widget: List/Table/Tab/Chart/Select

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#5804]
## Description
Property Pane - The “Add api” is missing in the dropdown on click action Widget: List/Table/Tab/Chart/Select

### Steps to reproduce the behaviour:

1. Go to link https://app.appsmith.com/user/login
2. Login into Appsmith through your user credentials.
3. Go to the widget screen by clicking on the Add icon of widgets  
4. Drag and drop the list/table widget
5. Go to the Widget property
6. Go to on Click Action section and see the drop down menu will appear but the call an API option is not exist
7. Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [release/frozen]

###ScreenShot:

https://www.screencast.com/t/sTZAHoGn
https://www.screencast.com/t/ThG6ZCs0

**Comment by vivekverma2312** [comment]
@somangshu @techbhavin Issues is on http://rc.app.appsmith.com/

**Comment by vivekverma2312** [comment]
@techbhavin This is observed on all the widgets.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal do you know anything about this? Is there a chance that this was changed while working on the new connect data flow or is this intented?

**Comment by Nikhil-Nandagopal** [comment]
Yes this is intended. APIs and Queries are now merged into a single flow
