### ISSUE TITLE
[Bug] List/Table Widget - Property Pane - “Visible” functionality is not working properly for toggle JS Widget: List/Table

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#5805]
## Description

[List/Table Widget - Property Pane - “Visible” functionality is not working properly for toggle JS
Widget: List/Table
]

### Steps to reproduce the behaviour:

Go to link https://app.appsmith.com/user/login
Login into Appsmith through your user credentials.
Go to the widget screen by clicking on the Add icon of widgets  
Drag and drop the list/table widget
Go to the Widget property
Enable the visible JS
Enter the value false and then publish the widget
List/Table widget is still visible. Issue

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [release/frozen]

###ScreenShot
https://www.screencast.com/t/9ginvzAZU9GI
###Video: 
https://www.loom.com/share/667428eb57734e56834cc585c293ef71

**Comment by Nikhil-Nandagopal** [comment]
@arslanhaiderbuttar please add the right tags for the issues so it goes to the correct pod

**Comment by jsartisan** [comment]
Fixed in #6226
