### ISSUE TITLE
[Feature] Add support to refresh data by widget

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#5809]
## Summary

Often times, a page with a lot of network calls fails due to timeout issues. It is rare that such a page will load on refresh. To make the page usable for users with poor internet connectivity, we should allow loading per widget. In this way, the number of APIs to load can be reduced for a particular page.

## Additional Context

Something to think about here is how we would solve dependencies. May be an additional feature requirement to solve for this is to add a status field for every action, that stores the last run status code for each of them. We can trigger re-runs for dependencies if the status was not a 200, or trigger it all the time if the action is set to run on page load (this will still be a subset for widget refresh)

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair I didn't quite understand this. The API failing will not lead to the page failing right? Also isn't the API run only on page load if it is set to a widget?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal the page itself will load but since some APIs from led, the widgets will be empty. The only way to recover from this today is to refresh the page. But a retry with the same conditions does not have any better chances of success. Allowing refresh by per widget will let users reduce the number of calls that need to be made and hence allow allow all the widgets to load with data.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair this seems like a bandaid for the underlying issue that the APIs failed. I think we should try to solve that issue instead because this doesn't seem like a common pattern on the internet that a part of the page fails to load so we allow you to refresh only that part. It happens rarely for widgets like videos and maybe tables. But ultimately a band-aid solution for the real problem. Can we instead outline why do the APIs fail and what should we do to solve that?

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal That's a fair assessment. The client can possibly hang around if the TTFB for the execute requests was lower. I raised this issue because our internal apps weren't loading for me at all even after multiple refreshes. Will profile the request next time I'm able to reproduce this.
