### ISSUE TITLE
[Bug] Comment threads are not marked as unread when a new reply is added

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5814]
## Description
Comment threads are not marked as unread when a new reply is added. Also adding a new comment to a resolved thread does not mark is as unresolved.

### Steps to reproduce the behaviour:

1. Create a new app
2. Invite another user
3. Add a new comment thread
4. Log in from the other user in incognito
5. There's an unread comment thread
6. Click on the thread it's marked as unread
7. Reply on the thread from the other user
8. The thread is still marked as read (can be checked from the pin color, which is orange for unread)

**Comment by rishabhsaxena** [comment]
@nayan I guess we can close this?

**Comment by nayan-rafiq** [comment]
Also we need to mark an resolved thread as unresolved if there is new comment in the thread.
