### ISSUE TITLE
[Bug] The 'Menu Button' text truncates when placing 'Add Menu Button' widget inside container/form/tabs/list widgets

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5815]
## Description
Deploy Preview - https://deploy-preview-5334--appsmith-editor-ce.netlify.app/applications
It is observed that the text 'Menu button' truncates when placing the 'Add Menu Button' widget inside container/form/list/tabs widget 

**Expected Result:**
Text should not truncate when placing add menu widgets in Container/List/Tabs/Form widget

### Steps to reproduce the behaviour:

1. Launch appmsith app in the deploy preview - https://deploy-preview-5334--appsmith-editor-ce.netlify.app/applications
2. Place Add menu Widget inside Container/List/Form/Tabs widget and observe

VideoLink:
https://loom.com/share/15402439065a4a298836e18b1563d7ca

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS big Sur 11.3]
- Browser [chrome, safari]
- Environment [deploy preview]

**Comment by somangshu** [comment]
This is not related to the widget, The widget tag behaves this way whenever there is less space. We need a global fix for this
