### ISSUE TITLE
[Feature] Show Appsmith platform specific errors

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5819]
- [x] #2560 
- [ ] #5822

**Comment by ajinkyakulkarni** [comment]
@mohanarpit @ayushpahwa Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5819?planning-poker)
