### ISSUE TITLE
[Bug][deploy preview] generate table issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5828]
- [x] 1.In the Select database dropdown, the mock and the other data sources should be separated->**Seperation is not done but all the data sources are displayed**

- [x] 2.when the user clicks on creating a new data source, navigation is taken to create a new data source. create new data source tab is not highlighted and when the user clicks on it the active tab is displayed until that the tab is not displayed ->**the new fix doesn't show the create tab instead it displays the entire page as data sources**
![image](https://user-images.githubusercontent.com/45958978/125416521-28913484-65d9-4cdd-a43e-c0b7b7e24655.png)

- [x] 3.In the Select database dropdown If the user has the Datasources which cant generate the table then the generate table button is not displayed -->**Fixed**

- [x] 4.There are no icons for table selection and column selection-->**Fixed**

- [x] 5."Select a searchable field from users” should be displayed as “Select searchable column" in the dropdown name->**as per the new changes it's correct**

- [x] 6.Instead of "Generate application "the button name has been changed to "Generate new page"->**as per the new changes it's correct**

- [x] 7.The DB which are not yet developed is not displayed in the select data source Dropdown->Fixed

- [x] 8.when the user creates a new page and generate a table then a new page is created and the old page is left as the same->**Fixed**

- [x] 9.the user is allowed to click on generate page without selecting the column ->**This is allowed as per discussion**

- [x] 10. In the active tab If the user has the Datasources which cant generate the table then the generate table button is not displayed-->**Fixed**
![image](https://user-images.githubusercontent.com/45958978/125417004-8ba81b15-569a-46a0-8cd8-5ce95f95a42b.png)

- [x] 11.When the user navigates between the pages or click on the same page the generate table page will disappear and a blank page is displayed->**As per the below comments as of now this okay we can break the flow**

- [x] When the user clicks on the 3 dot icon the pop up which display delete and edit is not good

- [x] When the user selects generate new data source from the dropdown then select any data source and instead of saving clicked on delete then the generate new page flow is broken->**Fixed**

- [x] **clarification required -**>All the page names are getting auto-generated and the Admin page prefix is added in all the page names-->**Now its removed**

- [x] When the structure is not yet fetched, the Select Table dropdown should go into a loading state->**Fixed**
- [x] If the structure call fails, show the user an error below the dropdown. “We were unable to fetch the structure of this data source. Please check the configuration and ensure that the necessary permissions are available”. Edit CTA

- [x] When there is no table for the selected data source then the error message should be displayed->**Not Fixed**
- [x] when the user selects My SQL ->then the select table and column even when the cred is correct the error is thrown and we are not able to create a table
- [x] When the user selects the DB which have not connected with correct cred the error message displayed is not correct

### Important Details

- Version: [Cloud ]
- OS: mac
- Browser [Chrome]
- Environment [ deploy preview]

**Comment by Rishabh-Rathod** [comment]
> * .In the Select database dropdown, the mock and the other data sources should be separated

I think the design is not updated for few cases, here we decided to show all the datasource together, irrespective of if they were created using mock DB.

**Comment by Rishabh-Rathod** [comment]
> * 3.In the Select database dropdown If the user has the Datasources which cant generate the table then the generate table button is not displayed

1. Currently, frontend shouldn't show the datasources which are not supported to generate template page like google sheet, Firestore, ArangoDB if those were visible to you in the **Select Datasource** dropdown then it is a bug and please let me know more about that else 
2. if it is a datasource that doesn't have any table and hence the user cannot select a table to generate page then the website will need to show an error and ask the user to select another datasource.

**Comment by Rishabh-Rathod** [comment]
> * 5."Select a searchable field from users” should be displayed as “Select searchable column" in the dropdown name

@RakshaKShetty 
Currently, the Label depends upon the kind of datasource user has selected. 

For eg -  for your use, it seems you selected a MongoDB-based datasource. In that case, `Select a searchable field` makes sense as there is no table and column concept in MongoDB. 

 ```
{
    DATASOURCE: "MongoDB",
    TABLE: "collection",
    COLUMN: "field",
  },
   {
    DATASOURCE: "S3",
    TABLE: "bucket",
    COLUMN: "keys",
  },
  {
    DATASOURCE: "SQL Based",
    TABLE: "table",
    COLUMN: "column",
  }

```

**Comment by Rishabh-Rathod** [comment]
> * 6.Instead of "Generate application "the button name has been changed to "Generate new page"

@RakshaKShetty 
This was suggested by Nikhil and the design might not be updated for this.

**Comment by Rishabh-Rathod** [comment]
> * 7.The DB which are not yet developed is not displayed in the select data source Dropdown

@RakshaKShetty Can you please elaborate more on this, I didn't understand what _**not yet developed**_ means.

**Comment by Rishabh-Rathod** [comment]
> * 8.when the user creates a new page and generate a table then a new page is created and the old page is left as the same

Do you mean when the user clicks on `GENERATE NEW PAGE` in datasources' ACTIVE section, then we create a new page instead of overwriting the existing page? 
If yes then that is an expected flow, correct? 
if no then, can you please explain your point with an example or more detail.

**Comment by Rishabh-Rathod** [comment]
> * 9.the user is allowed to click on generate page without selecting the column

@Debsourabh Are the Datasource card, In the `Datasources'` ACTIVE section meant to be selectable? 
As the design currently shows it as a selected datasource with a checkbox next to the name of the datasource.
If yes then what actions are allowed with multiple selected datasource.
> PS: I don't think we can allow users to generate a template page for multiple datasource in a single go.

**Comment by Rishabh-Rathod** [comment]
> * 10. In the active tab If the user has the Datasources which cant generate the table then the generate table button is not displayed

@RakshaKShetty 
Not sure why is that incorrect? Isn't that expected or do you mean the button should be visible but in a disabled state with on hover it says "Generate a new page with this datasource is currently not supported"?

**Comment by Rishabh-Rathod** [comment]
> * 2.when the user clicks on creating a new data source, navigation is taken to create a new data source. create new data source tab is not highlighted and when the user clicks on it the active tab is displayed until that the tab is not displayed

Yes, this is a bug, I will fix this.

**Comment by Rishabh-Rathod** [comment]
> * When the user clicks on the 3 dot icon the pop up which display delete and edit is not good

@Debsourabh Can you please share a UI for this?

**Comment by Rishabh-Rathod** [comment]
> * **clarification required -**>All the page names are getting auto-generated and the Admin page prefix is added in all the page names

@abhvsn can you please comment on this.

**Comment by abhvsn** [comment]
>  * **clarification required -**>All the page names are getting auto-generated and the Admin page prefix is added in all the page names
> 
> @abhvsn can you please comment on this.

Yes currently we are following the naming nomenclature as **Admin Page:_TableName_**. But if there is already a page with the same name counter suffix is appended like **Admin Page:_TableName_{count}**. Do we want to alter the implementation here?

**Comment by Debsourabh** [comment]
> > * 9.the user is allowed to click on generate page without selecting the column
> 
> @Debsourabh Are the Datasource card, In the `Datasources'` ACTIVE section meant to be selectable?
> As the design currently shows it as a selected datasource with a checkbox next to the name of the datasource.
> If yes then what actions are allowed with multiple selected datasource.
> 
> > PS: I don't think we can allow users to generate a template page for multiple datasource in a single go.

I am little confused here. This was an requirement for GSheets. You mentioned that some fields can be optional. In that case they can go ahead with the rest.

**Comment by RakshaKShetty** [comment]
There are 2 issues pending
1.when the user selects My SQL ->then select table and column even when the cred is correct the error is thrown and we are not able to create a table 
![image](https://user-images.githubusercontent.com/45958978/125732047-e4f6bace-3fcf-4aa1-815c-bf17b99bb68d.png)
2.When the user select the DB which have not connected with correct cred the error message displayed is not correct
![image](https://user-images.githubusercontent.com/45958978/125732163-005ec194-f332-4d13-aa5b-9151fdd93d05.png)
