### ISSUE TITLE
[Bug] Active API datasource displays incorrect button name

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5831]
Steps to reproduce:
1) Ensure to have an active API data source
2) Navigate to datasources
3) Click on Active tab
and observe the active API data source 

Observation:
It is observed that the button says "Add New Query" 

Expectation:
User must be displayed with an option "Add New API "

![Screenshot 2021-07-13 at 3 16 05 PM](https://user-images.githubusercontent.com/71753653/125431566-4655e297-adc7-44cf-b574-8d530fa42c61.png)

**Comment by SandipPalit** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by rasyidmi** [comment]
Good morning. I am interested in solving this issue, can I work on it? @dilippitchika

**Comment by dilippitchika** [comment]
I don't think this issue exists now, closing this
