### ISSUE TITLE
[Bug] User is not able view the delete option

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5833]
Steps to reproduce:
1) Navigate to datasource
2) Select create New
3) Add an API from Datasource
4) Click on RUN 
and observe

Observation:
It is observed that the API pane does not have a API header delete button 
On adding a longer API the option "Save as Datasource" is not visible to user . 

Expectation:
It is expected that the  API header delete button must be displayed to user 
![Screenshot 2021-07-13 at 2 50 40 PM](https://user-images.githubusercontent.com/71753653/125442056-055aac88-816b-4d6f-a6f8-7688edc129dd.png)

**Comment by areyabhishek** [comment]
You can delete the datasource by deleting the URL. Is that not obvious to users?

**Comment by prapullac** [comment]
@areyabhishek : The data source can be deleted once the attached API is deleted however here I am talking about the delete icon which helps the user to delete the added header or params that is displayed in the section.

**Comment by hetunandu** [comment]
Fixed with #5895
