### ISSUE TITLE
[Bug] Redirect to login on public app (without auth)

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5834]
## Description

The user is trying to load a public app in view mode and is redirected repeatedly to the login page. The user should be allowed to access the public app without requiring authentication.

[smartlook recording](https://app.smartlook.com/org/9b6c5c859e85745d01196fa4/project/e373e3a21d27278fd281d8b0/recordings?playSession=C9LSZjrhggD&playVisitor=s0b70s77Kn&segment=_m6CENrQty)

**Comment by Nikhil-Nandagopal** [comment]
Checked and its not an issue. The user has configured a button to redirect people to login. This is the app. If you click the button at the bottom you're taken to the login page.

**Comment by somangshu** [comment]
That is not the case @Nikhil-Nandagopal, this is my app. And I have not configured such behaviour. I faced a similar situation in another public app as well.

**Comment by somangshu** [comment]
@vivekverma2312 has this been pushed to production?

**Comment by abulka** [comment]
I'm also getting this problem - making an app public is broken (using latest AppSmith online as of 7th Aug 2021).

Very easy to reproduce:
- Create an app with a single widget
- Click the Deploy button
- Click the Share button - make it public - copy the link.

Anyone using the link is redirected to the login page!

**Comment by rishabhsaxena** [comment]
@abulka thanks for pointing this out! A fix for this issue has been merged, it should now work as expected.
Sorry for the inconvenience
