### ISSUE TITLE
[Bug]Collab Issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5835]
- [x] whenever the user login the 1 unread conversation tooltip is displayed->specific to incognito

- [x] when the user click on the invite user button the share pop up opens and the comments pop is overlapped on it 

- [x] #5858

- [ ] when the user hovers the reaction added to their own comment then tooltip is not displayed->less priority

- [x] when the user click on a comment from notification then the comments are opened in deployed mode 

- [x] After the user click on the comment from the notification section the user is navigated to the comment section in deploy mode and the comment pop up will be open but the 1 unread conversation tooltip and red icon is displayed until some action is performed or page is refreshed

- [x] Mark as reading button always display the same color it is a bit confusing

- [x] #5859

- [x] when the user add any data in edit mode and dint deploy it then in viewer mode the comments will be displayed when user click on it infinite loop will be displayed

- [x] The user receives a notification only for new comments added there is no notification for deletion, resolved comments

- [x] #5860

- [x] when the user completes the onboarding the drop the comment icon to start commenting the tooltip display is retained when switched to edit mode

- [ ] The onboarding is not displayed in release for the new users(incognito mode)
- [x] The invite option should show up as soon as there are no matches while the user is typing @
- [x] Users in the invite list should be ordered based on their search results
- [x] User should not be able to tag themselves in the UI
- [ ]  The new user login  and clicks on create new button for few seconds the view icon is displayed
- [ ] The onboarding starts the image rendering is a little slow
- [x] The default added email address should be highlighted because the start tutorial button is disabled and the user might get confused 
- [x] when the comment thread reached its height limit the scroll is not displayed
- [x] Click on the comment displayed on the comment pane the comment doesn't open up on the canvas
- [ ] When the user clicks on the emoji icon the pop up should not open top of the comment pop up
- [ ] The error message should display correctly when there are no comments for the selected filter in the comment pane
- [ ] The Resolve tooltip is not displayed for the new user. when there are previously added comments, so this might be a bit confusing to the user
- [x] The notification is not sent when the user tags a user along with a comment 
- [ ] The onboarding is not displayed for user 2 when user 1 has finished onboarding on the same browser
- [ ] If more than 5 users had added the same reaction the tooltip is not displayed with all the username

### Important Details

- Version: [Cloud ]
- OS: [mac]
- Browser Chrome
- Environment [Release]

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty please tag the issue to the epic as well :)

**Comment by Nikhil-Nandagopal** [comment]
More issues
- [ ] Bring focus to input in the onboarding form
- [ ] On replies:
    - [ ] Mark it as unread
    - [ ] Un-resolve the thread
- [ ] Thread link not clickable from app comments
- [ ] Don’t send bot thread for viewers

**Comment by nayan-rafiq** [comment]
Closing this in v1. There are some enhancements still pending which we'll do in v2.
