### ISSUE TITLE
[BUG] Distorted UI when there are too many characters in Org name

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#584]
Email ID: 
wejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffff4444444444444444444444444444444444444ttttttttttttttttttttttttttttttttttttttttttttttttttttfwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffff4444444444444444444444444444444444444ttttttttttttttttttttttttttttttttttttttttttttttttttttfwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffff4444444444444444444444444444444444444ttttttttttttttttttttttttttttttttttttttttttttttttttttfwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffff4444444444444444444444444444444444444tttttttttttttttttttttttttttttttttttttttttttttttttttttttttggggggggggggggggggggggtttttggggggggggggggggggggggtttttggggggggggggggggggggggtttttggggggggggggggggggggggfwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffwejkbgfhjwefffff4444444444444444444444444444444444444tttttttttttttttttttttttttttttttttttttttttttttttttttttttttgggggggggggggggggggggg@d.com

Issue: UI is distorted when there are too many characters in the email ID.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Expected Result: UI should behave nice even if there are too many characters in the email ID.

Attachment: https://drive.google.com/file/d/1gL9EGNnIry7TG-2WeDjRaBXTF9aBv-qt/view?usp=sharing

Steps to replicate :
1. Hit https://app.appsmith.com/user/login
2. Enter the email ID given above and type a password with 6 characters.
3. Login

**Comment by Saket2** [comment]
Unable to add the label 'above-them'

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 thanks for the bug report!

**Comment by riodeuno** [comment]
One potential solution is to use CSS and add ellipsis to the text and prevent it from overflowing the parent bounds. This will also need a tooltip to show the full text on hover.

**Comment by reachtokish** [comment]
Is there a PR for this issue? Wanted to make my first contribution to this project.

**Comment by Nikhil-Nandagopal** [comment]
@reachtokish go for it. No one has claimed this yet. Please read our contribution guidelines first and raise a pr in the next 2 days 🙂

**Comment by reachtokish** [comment]
@Nikhil-Nandagopal Sure. Thnx.

**Comment by reachtokish** [comment]
What I can see `patra.kishore65's Personal Organization` - coming from api. Kindly refer the below screenshot. I was thinking of ellipsis but like `patra.kishore...'s Personal Organization` rather than `patra.kishore65's Personal Orga...`. @Nikhil-Nandagopal kindly help me should I go with `patra.kishore...'s Personal Organization` - this or `patra.kishore65's Personal Orga...`? If the first one is the choice then we need a backend change here

![image](https://user-images.githubusercontent.com/10685261/95113097-846dad80-075f-11eb-8d8c-f1b3d7b08d57.png)

**Comment by Nikhil-Nandagopal** [comment]
@reachtokish let's ellipsize towards the end after 40% of screen width?

**Comment by reachtokish** [comment]
Got it. Thnx
