### ISSUE TITLE
[Bug] Incorrect error message in Select widget when there are duplicate values

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5840]
## Description

When you have duplicate values for items in Select widget, it still throws the error `This value does not evaluate to type "Array<{ label: string, value: string }>".`

<img width="758" alt="selecterror" src="https://user-images.githubusercontent.com/800578/125479296-5e4345b5-7d08-4163-9a1f-04cc35df5fd2.png">

This is very misleading and has caused few [users](https://discord.com/channels/725602949748752515/760761579708219412/864525056335151125) to spend a lot of time debugging a wrong problem.  

### Steps to reproduce the behaviour:

1. Add Select widget
2. Add items with the same values
3. See the error

### Important Details

- Version: Cloud  
- Environment: Production

**Comment by ajinkyakulkarni** [comment]
@hetunandu is this a JS evaluation issue or a widget issue?

**Comment by somangshu** [comment]
This looks like a validation issue. @riodeuno is this handled or can be archived with the new change in widget validations?

**Comment by riodeuno** [comment]
We're not updating the `unique` property which is applied in the validations configurations, to this error message. We need more comprehensive error messages.

This involves the debugger.
