### ISSUE TITLE
[Bug] Scan command doesn't work in Redis plugin

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#5849]
## Description

As a user I should be able to execute all Redis commands via the Appsmith platform. The `scan 0` command doesn't work because it returns a list of lists. The `RedisPlugin` only handles plain objects or a list of objects. We need to add support for list of lists as well.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a Redis datasource
2. Create a query
3. Execute the action with the command `scan 0` 

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by sumitsum** [comment]
Closing in favour of https://github.com/appsmithorg/appsmith/issues/6185
