### ISSUE TITLE
[BUG] Error message while switching between email or password is unnecessary

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#585]
Issue: While switching between Email and Password, messages 'Please enter an email' and 'Please enter the password' are highlighted.

Expected Result: It should only be highlighted while trying to login/signup without providing these details.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Link to access the attachments :
https://drive.google.com/drive/folders/1dZPYeln-LoUhkPRoXHPyN4vS8kypLkw0?usp=sharing

Steps to replicate :
1. Hit https://app.appsmith.com/user/login
2. Keep switching between Email and Password.

**Comment by Saket2** [comment]
Unable to add the label 'above-them'.

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 I believe experience was to be similar to how [Airtable](https://airtable.com/signup) worked in this case and error was to show on blur of that field. Closing this issue but feel free to re-open if you disagree

**Comment by Saket2** [comment]
@Nikhil-Nandagopal  I just checked 'Airtable' and there the field itself is highlighted. As in, when I click on 'First Name'/'Last Name', respective field is highlighted. Which is fine even in Appsmith's case. What I'm talking about is the messages:
'Please enter an email'/'Please enter the password' in Appsmith's case. I have attached the video for reference.
