### ISSUE TITLE
[Bug][deploy preview]new nav suggested widgets/sniping mode issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5850]
- [] The query pane should be big as in the Figma even now its feels very small->**still needs to be improved**
- [x] The back to canvas link is missing in the right pane->**fixed**
- [x] Connect to already present table name is not present ->**As per the discussion not required**
- [x] the generating widget  button should be removed in the console->**fixed**
- [ ] Below select existing canvas there should be a link “how this works?”
- [x] when the user select the widget from "add new widget" the user is navigated to canvas the data is binded to the widget but in the property pane, the autocomplete is not opened->**Not Required**
- [x] In Add widget section the widget image is not displayed correctly->**fixed**
- [x] when the user doesn't add any widget to the canvas and directly create a query and run it then instead of add a widget          it  should be displayed as a suggested widget->**fixed**
- [x] when the user clicked on the select the widget from canvas the user is navigated to the canvas but the canvas is displayed blank this scenario occurs only when the user creates a new application->**This is Expected**
- [x] when the user hovers on the outgoing and incoming connection in the relationship section the tooltip should be displayed->**fixed**
- [x] In the API query pane ->The tab name is displayed as a connection but in Figma it says widgets (I think connections make sense here as it can contain both integrations and widgets)->**required**
- [x] when the incoming entity fails the error is not displayed in the property pane (changes in the combined branch)->**Fixed**
- [ ] Suggested widgets should always work with the bindings event for chart widget and select widget
- [ ] Text widget is not showing for suggested widgets

### Important Details

- Version: [Cloud ]
- OS: [Mac]
- Browser Chrome
- Environment Deploy preview

**Comment by akash-codemonk** [comment]
> * 1.The query pane should be big as in the Figma even now its feels very small

Can you please elaborate on this? Not sure what the query pane size is about.
> * 3.Connect to already present table name is not present ->needs to check 

Not sure what is this about as well. Is it related to some issue with connections?

**Comment by RakshaKShetty** [comment]
![image](https://user-images.githubusercontent.com/45958978/125743914-ddcee553-725a-4f93-bef8-82ff8720107a.png)
The query pane is still small  it should be the same as in the Figma

3.Connect to already present table name is not present -the highlighted section in the figma screenshot is missing in the application
![image](https://user-images.githubusercontent.com/45958978/125744831-edc393f5-9ec5-49b4-b325-fbf4b8c64aa1.png)

**Comment by RakshaKShetty** [comment]
Issues:

- [ ] In add widget section the widget images should be displayed 
- [ ] when there is the empty object the add widget suggestion should not show text widget
- [ ] change the UI for the Inspect entity Tab in the debugger to match this relationship section
- [ ] In the relationship section, change the text
Relationships
See all connected entities
Incoming entities
Outgoing entities
- [ ] When the query output is a string or a number in the add widget section only the text widget suggestion is displayed but there should be both text and input widgets 
- [ ] when the query output is an array in the add widget section the text widget is not displayed 

Clarification Required :
@Nikhil-Nandagopal 
point 1. Following are the widget suggestion not displayed in Add widget section for any query output
1.Button
2.Checkbox
3.Container
4.Datepicker
5.Divider
6.Filepicker
7.Form
8.IFrame
9.Image
10.Map
11.Menu
12.Modal
13.Radio
14.Rating
15.Text editor
16.Switch
17.Tab

Point 2. Should we show the radio button on array output?

Point 3.for Select and chart the error will be displayed on adding a new widget because these widgets require the data in the particular format. Is this a valid bug?

Point 4. In the List widget, we have 1 image and 2 text boxes. when we bind the data if there is no image it shows as undefined and only the first text box is binded to the correct column. in the second text box, a random key is binded which is not there in the output. Is this a valid bug?

point 5:when the user selects the widget from add widget should it capture in the logs?

Point 6: In the outgoing entity section if there is an error in an outgoing entity which is a widget, it is not shown in the outgoing entity. if there is an error in the API / DB query then the outgoing entity is shown with an error and debug option. Is that the correct functionality?

**Comment by RakshaKShetty** [comment]
Tagging to epic #3299

**Comment by akash-codemonk** [comment]
- [ ] Suggested widgets should always work with the bindings event for chart widget and select widget
- [ ] Text widget is not showing for suggested widgets
- [ ] when there is the empty object the add widget suggestion should not show text widget
- [ ] When the query output is a string or a number in the add widget section only the text widget suggestion is displayed but there should be both text and input widgets 
- [ ] when the query output is an array in the add widget section the text widget is not displayed 

@AnaghHegde Could you help out with these?

**Comment by akash-codemonk** [comment]
> Issues:
> 
> * [ ]  change the UI for the Inspect entity Tab in the debugger to match this relationship section

@Debsourabh Could you please help out with this
