### ISSUE TITLE
[Bug] Query filters not fitting into the container

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#5854]
## Description
Here is a Loom video describing the issue
[Loom](
[![LOOM DEMO](
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7960026e8d994be79b018cb648ccc719-00001.gif)](https://www.loom.com/share/7960026e8d994be79b018cb648ccc719)

### Steps to reproduce the behaviour:
Adding a new Query using Firestore Datasource

**Comment by ajinkyakulkarni** [comment]
@trishaanand Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5854?planning-poker)

**Comment by ajinkyakulkarni** [comment]
@trishaanand @ohansFavour Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5854?planning-poker)
