### ISSUE TITLE
when the user tries to add the new user the email id of the user is retained and when the user clicks on post the internal server error is displayed

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5858]
### steps

1. Try the invite user flow through a comment
2. Close the share modal
3. Click on the post button
4. We see an internal server error

https://user-images.githubusercontent.com/1944800/125651389-8410dfb9-51ac-4dd1-98dc-81c527b1e821.mov

**Comment by nayan-rafiq** [comment]
It's already fixed and waiting to be merged to release. There is already an issue #5193 for this so closing this one.
