### ISSUE TITLE
8.f the user changes the role of the users in the application than the old comments won't be retained

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5859]

**Comment by rishabhsaxena** [comment]
@RakshaKShetty could you please add the steps to reproduce the issue?

**Comment by RakshaKShetty** [comment]
Steps to reproduce 
1. log in as a user 1 the user 1 should be as admin start a new comment thread tag a user 2 
2. log in as a user 2 the role of user 2 should be a developer so. now he can see the new comment thread 
3. Now change the role of User 2 to the viewer sign in and check the user is unable to see any comments logout 
4. Now again ask admin to give back the developer role and login as user 2 the user 2 is unable to the old comments
