### ISSUE TITLE
[BUG]  'Reset password' should not be enabled until an email ID is provided in proper format

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#586]
Issue: 'Reset password' should not be enabled until an email ID is provided in proper format.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Attachment:  https://drive.google.com/file/d/1PDhic5-oSbwhLUeIZ9clSyDMzyY98y40/view?usp=sharing

Steps to replicate :
1. Hit https://app.appsmith.com/user/login
2. Click on 'forgot password'
3. Enter something in the email field.

Expected Result: 'Reset' button shouldn't be enabled until an email ID is provided in proper format.
Note: On the login page 'Login' isn't enabled until an email ID is provided in proper format. 'Reset' should also work in the same way.

Actual Result:  'Reset' button is enabled as soon as we enter 1st  character.

**Comment by Saket2** [comment]
Unable to add the label 'above-them'.

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 thanks for the bug report

**Comment by rutulganatra** [comment]
Can i take this issue ?

**Comment by Nikhil-Nandagopal** [comment]
@rutulganatra go for it! Please read our contribution guide on how to get started!
