### ISSUE TITLE
11 .when the viewer share the app the comments that user has access will be shown to the new user so if the admin add any new comments he wont be able to see it but he can see the old comments

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5860]
### steps

1. As an admin add few comments
2. Invite a new viewer (as an admin)
3. Invite a new viewer (as a viewer)
4. Add new comment from the admin user
5. The new comments added from the admin do not show up for the viewer

**Comment by nayan-rafiq** [comment]
This is same as #5859 so closing this.
