### ISSUE TITLE
Invite support user from comment

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#5869]
If user tags `appsmith`, the application will initiate the invite user flow for the support user. 

For example, an user tags `appsmith` in their comment. This will show a message to the user and take them to the flow where they can invite the `support@appsmith.com` email address.

**Comment by rishabhsaxena** [comment]
https://user-images.githubusercontent.com/1944800/131656896-975280db-d4eb-426a-8052-a7f66439af51.mov
