### ISSUE TITLE
[BUG] Wrong use of warning sign

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#587]
Issue: Wrong use of warning sign.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate :
Way 1:
1. Hit https://app.appsmith.com/user/login
2. Click on 'forgot password' 
3. Enter 'fwefkn@gmaknf.com' in email and click on 'Reset'.
4. Message appears 'Unable to find user with id fwefkn@gmaknf.com' with a red warning sign.

Way 2:
1. Hit https://app.appsmith.com/user/login
2. Provide an invalid email ID and a password
3. Click on 'Login'
4. Message appears 'It looks like you may have entered incorrect/invalid credentials. Please try again or reset password using the button below.' with a red warning sign.

Expected Result: 1. There should be a proper warning symbol. 2. It looks like a close button, in that case 'close' button functionality doesn't work.
Actual Result: Red color warning sign with a close symbol is misleading. 

Attachment: https://drive.google.com/drive/folders/1HGnKt8r-UuzUok-ydCOYlG3x_LlI1f68?usp=sharing

**Comment by Saket2** [comment]
Unable to add the label 'above-them'.

**Comment by jmakhack** [comment]
Hey @Nikhil-Nandagopal, I should be able to pick up this issue and create a PR.
Can you assign it to me?

**Comment by Nikhil-Nandagopal** [comment]
@jmakhack seems like we need an icon for this. @Debsourabh can you help with an icon here

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal @Debsourabh The icon is not needed since the blueprint design system already had this. This is what the implemented PR looks like
<img width="690" alt="Screenshot 2020-10-07 at 12 06 03 PM" src="https://user-images.githubusercontent.com/12022471/95295980-9c474d80-0895-11eb-9e28-9bc9ca66d739.png">
