### ISSUE TITLE
[Bug] Download functionality is broken for zip files (corrupt files are downloaded)

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#5878]
## Description

The [user](https://discord.com/channels/725602949748752515/760761686549463060/865144230438633482) is not able to download a zip file using the download function.

I was able to reproduce this
<img width="812" alt="downloadzip" src="https://user-images.githubusercontent.com/800578/125757456-f92f1efc-b4af-4b68-a13d-ef33b296e400.png">

### Steps to reproduce the behaviour:

 

1. Select download action on button click
2.  Enter this JS ```{{download('https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-large-zip-file.zip','abc.zip','application/zip')}}```
3.  Download the file
4.  You will notice that the downloaded file is corrupt.

In my case, the downloaded file was just had the URL, not the data -

<img width="602" alt="downloadedfile" src="https://user-images.githubusercontent.com/800578/125758012-131f3ee9-5a0c-4e5b-aca3-b3feac704503.png">

However, that is not always the case when downloading a response from an API as a zip 
```{{download(fetchUsers_asd.data, "file.zip")}}```

Internal slack discussions link https://theappsmith.slack.com/archives/CGBPVEJ5C/p1626335088137500

### Important Details

- Version: Cloud
- Browser Chrome
- Environment: Production

**Comment by ajinkyakulkarni** [comment]
Looks like the download.js library is not updated in a long time. We should consider switching to an another library.
![Uploading downloadfileold.png…]()

**Comment by ajinkyakulkarni** [comment]
Maybe use https://github.com/eligrey/FileSaver.js#supported-browsers ?

**Comment by ajinkyakulkarni** [comment]
I am reopening this because following use case still needs to be fixed-
 
<img width="2117" alt="downloaderror" src="https://user-images.githubusercontent.com/800578/126115989-f1004c19-0441-448b-8ba8-0b170f36c562.png">

**Comment by prapullac** [comment]
Closing the issue as it is working as expected
