### ISSUE TITLE
[BUG] Inconsistency in notification 'Unable to find user with ID 'ID' (intermittent issue)

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#588]
Issue: Inconsistency in notification 'Unable to find user with ID 'ID'

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate :
1.Hit https://app.appsmith.com/user/login
2. Click on 'forgot password'
3. Enter 'fwefkn@gmaknf.com' in email and click on 'Reset'.
4. Message appears 'Unable to find user with id fwefkn@gmaknf.com' 

Actual Result: There is a message that appears on the top right corner of the screen. Issue is that it doesn't appear everytime we hit 'Reset Password', it only appears once in a while. 
Expected Result: Either message on the top right corner should appear everytime 'Reset Password' is hit or it shouldn't appear at all.

Note: In the attached video, it can be seen that, message on the top right corner doesn't appear after multiple attempts but it appears suddenly (Can be seen at video length : 1:03 minutes)

Attachment: https://drive.google.com/drive/folders/1brzHtxuK-mNRbNyaeBodcD_sU534VYuU?usp=sharing

**Comment by Saket2** [comment]
Unable to add the label 'above-them'.

**Comment by gagandeepp** [comment]
please assign this to me

**Comment by Nikhil-Nandagopal** [comment]
Hi @gagandeepp , I've assigned the issue to you. We haven't had a chance to debug this so do let us know what you find so we can discuss a solution :)

**Comment by trdillon** [comment]
Has this issue been resolved? I was not able to replicate it on the current cloud version, the notification consistently pops up for me in both Chrome and Firefox. The video linked in the attachment is no longer available to view the issue as it had occurred.
