### ISSUE TITLE
[Bug] 'Comment mode' window is hidden behind the tools panel

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#5884]
## Description

On clicking on 'Comment Mode' button, a window pops up hidden under the tools panel on the left. This can't be moved nor accessed due to the tools panel blocking it.

### Steps to reproduce the behaviour:

1. Click on the 'Comment Mode' at the top of the page
2. A pop-up window appears at the bottom of the page but is hidden behind the tools panel

- Version: Cloud
- OS: Windows10
- Browser: Chrome
- Environment : Production

![image](https://user-images.githubusercontent.com/79509062/125779992-fdb410a3-9037-42a8-a6d8-25b7e0492040.png)

**Comment by rishabhsaxena** [comment]
Actually, the fix for this has been merged to release
