### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#5899]
## Summary

Request for the *Evaluated Value* JSON viewer to be made available as a Widget, so that it can be used in deployed apps, instead of only in Editor Mode. 
## Motivation

This display type would be beneficial in deployed apps too, not just in the editor. Nested JSON data is best viewed with the collapsable tree view. The nested data has to be flattened before displaying in a table, but is easy to browse with the tree view. 

Although we can currently display the JSON in a text or input field, that does not provide the same color coding or collapsable objects.  

## Additional Context

![Screen Shot 2021-07-15 at 8 22 01 PM](https://user-images.githubusercontent.com/24459976/125873964-2c252007-88de-40b1-9934-010afe125462.png)

**Comment by Nikhil-Nandagopal** [comment]
@GreenFlux Thank you for the feature request! We have a feature request for #5003  so closing this in favor of that
