### ISSUE TITLE
[BUG] Bad Request while trying to reset password

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#590]
Issue: Bad Request while trying to reset password.

Browser Details: Firefox 68.12.0esr (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Attachments: https://drive.google.com/drive/folders/14F5yWQpK6A4rA_1hiPifQwUVos-YiRc4?usp=sharing

Steps to replicate :
1. Hit https://app.appsmith.com/user/login
2. Click on 'forgot password'
3. Enter 'ffekwjn@gmaill.com' in the email field.
Actual Result: Bad Request: Missing request header 'Origin' for method parameter of type String

Expected Result: Message 'It looks like you may have entered incorrect/invalid credentials. Please try again or reset password using the button below.'

**Comment by Saket2** [comment]
Unable to add the label 'above-them'

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit seeing different messages for these 2 issues
#637

**Comment by mohanarpit** [comment]
This error is being thrown by the Spring framework because the client hasn't sent us the mandatory header `Origin`. Typically, the browser adds this header on it's own for all requests. That's why I'm unable to reproduce this issue on my system.

@Saket2 Is this error consistently showing up for you? Or was it a one-time thing?

**Comment by Saket2** [comment]
@mohanarpit It was consistent. In fact, I reproduced it just now. Here is the thing:
#590 occurs on Firefox (Consistently).
#637 Occurs on Chrome (Consistently).

**Comment by Nikhil-Nandagopal** [comment]
@prapullac can you repro this on firefox?

**Comment by prapullac** [comment]
@Nikhil-Nandagopal  I am unable to reproduce the issue on firefox. I am displayed with an error " Unable to find user with emailID xxxx@gmail.com"
