### ISSUE TITLE
Move tern server to web worker

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#5902]
Currently tern server takes 30% of the scripting time on keypress. We would gain that time by moving it to a web worker.
![Screenshot 2021-07-15 at 4 44 19 PM](https://user-images.githubusercontent.com/441914/125896304-9d6c198b-a486-4ac1-a357-5d58d023ea5f.jpg)

**Comment by hetunandu** [comment]
Improved performance by optimising the updateDef call of Tern Server.
