### ISSUE TITLE
[Bug] Documentation Links are broken for a few datasources

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#5905]
## Description

Users try to access our documentation links from the query page and don't get a result because they are configured incorrectly
Google Sheets, SnowFlake etc.

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni super small fix that can help a lot of users

**Comment by ajinkyakulkarni** [comment]
@ApekshaBhosale @vnodecg Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/5905?planning-poker)

**Comment by arunvjn** [comment]
Looks like this is fixed in current release.
