### ISSUE TITLE
[Feature] Table widget: Sort order API

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5906]
## Summary

As a dev, I should have access to the table sort column if any through the `{{table.sortOrder}}` API. This will return an object when sort is active > `{column: string, order: enum|‘asc’|'desc'}`. There should also be a `onSortChange` action available which can trigger an API

## Motivation

Devs would like to take control of sorting in the API while doing server side pagination in table widget

**Comment by ajinkyakulkarni** [comment]
Following is a use case from the [user](https://discord.com/channels/725602949748752515/725609493974614076/865455325744988160) 
```I have an api which supports sortOrder and sortBy params. So, just wanted to pass these value for server side computation. Similar to how pageNo and pageSize is working.```
