### ISSUE TITLE
[Feature] Change selected row background for dark/high contrast cell backgrounds

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#5915]
## Summary

Currently, selected row has a fixed background which conflicts with contrast when cell background colour is set to a dark/bright shade. Font colour can't be set to a light shade in this case without compromising on the legibility of selected row. Could change selected row background to a shade that compliments the selected background instead perhaps?

![image](https://user-images.githubusercontent.com/79509062/125945088-e53b829d-6ad4-4cd4-82a4-65cedf5d1d54.png)

![image](https://user-images.githubusercontent.com/79509062/125945137-6c7bb566-efaf-4286-91ea-b1be4efdc827.png)

**Comment by dilippitchika** [comment]
Reach: 288 in 6 months

**Comment by jsartisan** [comment]
Fixed in #17228

**Comment by ramsaptami** [comment]
Selected row contrast is now legible as intended.
