### ISSUE TITLE
[Bug] Table widget: Filter with `does not contain` dosent work well

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#5916]
## Description

Filter “Does Not Contain” is not working
Widget: Table

### Steps to reproduce the behavior:

Go to link https://app.appsmith.com/user/login
Login into Appsmith through your user credentials.
Go to the widget screen by clicking on the Add icon of widgets  
Drag and drop the table widget
Click on Filters and select where attribute
Click on attribute the dropdown menu will appear and select the option “does not contain” 
Enter the value which you don’t want in the table 

### Important Details

- Version: [Cloud / Self-Hosted]
- OS: [Mac OSX]
- Browser [Chrome, Safari]
- Environment [Release/Frozen]
### Video Link:
https://www.loom.com/share/1850edd35d7a46b782482d38a0092749
### Screenshot Link:
https://www.screencast.com/t/CxppfVJqy

**Comment by Nikhil-Nandagopal** [comment]
@arslanhaiderbuttar please tag the priority and the table widget
