### ISSUE TITLE
[BUG] Security Bug - Signup happens with any random email ID i.e. a@c.com

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#592]
Issue:
Security Bug - Signup happens with any random email ID i.e. a@c.com

Steps to replicate:
1. Hit https://app.appsmith.com/user/login
2. Go to the sign up page
3. Type any random email ID (Just take care of the format a@b.com). I had given 'a@c.com'
4. Sign up

Expectation: There should be an email verification or some sort of check at sign up screen. It can't let user sign up with any ID.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Attachment:  https://drive.google.com/drive/folders/1zOgQzuVSGrHeBMX1NQPPHvTG9-Y-_29H?usp=sharing

**Comment by Saket2** [comment]
Unable to add the label 'above-them'.

**Comment by Nikhil-Nandagopal** [comment]
Decided that we will allow this since passwords can be reset. In the future we'll add an activation mechanism for users but don't want to block signups for this
