### ISSUE TITLE
[Bug]Deploy Preview - Table Widget - Table Data - Clicking on table data field and expanding/clicking on any of the expected property types 'ReferenceError: fetch_users not defined' error occurs

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5925]
## Description
Deploy Preview - https://deploy-preview-5270--appsmith-editor-ce.netlify.app/applications
It is observed that by clicking on the table data and expanding any of the expected property type - 'ReferenceError: fetch_users is not defined' error occurs

Expected Result:
User should be able to expand any of the expected property types without any errors

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the Deploy Preview -  https://deploy-preview-5270--appsmith-editor-ce.netlify.app/applications
2. Drag and Drop table widget 
3. Click on Table data 
4. Try to click or expand any of the expected property types and observe

Screenshot:

<img width="1280" alt="Screenshot 2021-07-15 at 12 00 02 PM" src="https://user-images.githubusercontent.com/35128442/126028908-4d65fa44-32b9-4a81-929c-34cbd0e416d2.png">

### Important Details

- Version: [Version 11.3]
- OS: [MacOS big Sur]
- Browser [chrome, safari]
- Environment [deploy preview]

**Comment by riodeuno** [comment]
@YogeshJayaseelan This has been fixed. Closing this issue.
