### ISSUE TITLE
[BUG]? is hidden on the bottom right corner because of Operator suggestions

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#593]
Issue: ? is hidden on the bottom right corner because of Operator suggestions

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate :
1. Hit https://app.appsmith.com/user/login
2. Sign up

Expected Result: With operator suggestions, ? on the bottom right should be visible.
Actual Result : With operator suggestions, ? is hidden.

Attachment: https://drive.google.com/drive/folders/1BiZCDCXlOM1fhU9gloNSzCTQtUEerg3f?usp=sharing

**Comment by areyabhishek** [comment]
Thanks for reporting this. Try using loom chrome extension to record this so that it can be embedded in the issue itself.

**Comment by Saket2** [comment]
@areyabhishek Apologies. Please find attached another screenshot which clearly displays the issue.
<img width="1734" alt="Re-submission" src="https://user-images.githubusercontent.com/49346036/93694674-41d78e80-fb2c-11ea-98c7-44fdceb39c36.png">

**Comment by mohanarpit** [comment]
Closing this issue as it is no longer a problem
