### ISSUE TITLE
[Bug] Link to documentation takes user to incorrect location

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#5932]
Documentation link for an error on Google Sheets takes user to incorrect link for DynamoDB instead

1. Error while binding data from Google Sheets
2. Click on error link on the log for documentation and it displays incorrect link

- Version: Cloud
- OS: Windows 10
- Browser Chrome
- Environment: Production

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami can you please share the error or attach a screenshot as well?

**Comment by ramsaptami** [comment]
Don't know why the loom video didn't get added in here. Re-attaching it.
[https://www.loom.com/share/e795b24ba92141b69f31be02d4b4d782?sharedAppSource=personal_library](url)

![image](https://user-images.githubusercontent.com/79509062/126107763-f4fdc2ac-464e-450d-b9fe-872647b9603f.png)

**Comment by ramsaptami** [comment]
Closing this issue since it was incorrectly raised.

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami why is it incorrectly raised?

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal it is a legit issue that I've properly documented on #5939. This bug was accidentally posted prematurely and so had too many edits without all the necessary information. Closed this and raised a new one for better readability.
