### ISSUE TITLE
[Bug] Link to documentation takes user to incorrect location

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#5939]
## Description
Documentation link for an error on Google Sheets takes user to incorrect link for DynamoDB instead

### Steps to reproduce the behaviour:
1. Error while binding data from Google Sheets
2. Click on error link on the log for documentation and it displays incorrect link

### Important Details
Version: Cloud
OS: Windows 10
Browser Chrome
Environment: Production

https://www.loom.com/share/e795b24ba92141b69f31be02d4b4d782?sharedAppSource=personal_library

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair @vihar it seems like we don't have correct documentation here

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal  this seems like it is related to #4953, the backend documentation link is the same, I'm guessing we need to fix the search keywords for the omnibar.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair @vihar yes this is because the documentation does not have this error

**Comment by ramsaptami** [comment]
Links show Google Sheets documentation
