### ISSUE TITLE
[BUG] 500 server error while trying to manage users

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#594]
Issue: 500 server error while trying to manage users

Steps to replicate:
1. Hit https://app.appsmith.com/user/login
2. Sign up
3. Click on 'share' from https://app.appsmith.com/applications page.

Result: 500 server unavailable error

Attachment: https://drive.google.com/drive/folders/1eC2OzgR9msaDO6h_B8-kkVKX7nIO0aRc?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 unable to repro this. Are these steps consistent?

**Comment by Saket2** [comment]
@Nikhil-Nandagopal - Unable to reproduce it. It just happened twice - When it actually happened for the 1st time and 2nd time when I tried it to capture the screenshot.
I think it was a specific window when server would be down.
