### ISSUE TITLE
[Bug] Some Disabled Widgets can't be moved or dragged on Firefox

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#5944]
## Description
Some widgets don't move or drag on Firefox version 90.0

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d670b08f977a4a54b512d448ffbbeffe-00001.gif)](https://www.loom.com/share/d670b08f977a4a54b512d448ffbbeffe)

**Comment by aswathkk** [comment]
@Tooluloope The Video link seems to be broken.

**Comment by riodeuno** [comment]
@Tooluloope Please share the recording again. This can be a high priority issue.

**Comment by Tooluloope** [comment]
@riodeuno @aswathkk Seems it's working fine now
