### ISSUE TITLE
[Bug] Stretch icon isn't displayed on the right side of the table widget 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#5946]
## Description
Expand symbol should appear on all sides of the table widget irrespective of where it's placed - but does not appear when widget is placed such that the edit panel appears on the right. 

### Steps to reproduce the behaviour:
1. Add table widget to the center of the page 
2. Try to expand size on the right side of the widget
3. Click away from the table so the edit panel disappears - now the expand symbol is present (inconsistent behaviour)
4. Drag table to the right side of the page such that the edit panel now appears on the left side of the widget and the expand symbol is shown (inconsistent behaviour)

### UPDATE
This is a recurrent issue with other widgets too - check box, date picker. charts, file picker, iFrame, image, radioGroup, ratings, richText, divider, switch, tabs, text, video widget can't be stretched if properties pane is on the right side.
In addition, maps and forms widget on first placement have the stretch icon appear on the right but when these widgets are relocated, the stretch icon disappears from the right.

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Chrome
- Environment : Production
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/332dd6be75fc4136a47b26d5b8b28e7e-00001.gif)](https://www.loom.com/share/332dd6be75fc4136a47b26d5b8b28e7e)

**Comment by somangshu** [comment]
@ramsaptami Can you attach some screenshot to explain what you are talking about. When you say the edit panel are you talking about the property pane? What exactly is the `expand symbol`?

**Comment by ramsaptami** [comment]
Yeah, it's the properties pane that I'm referring to here (sorry, still catching up on the jargons here). By expand, I mean the stretch icon that appears on the boundaries of the table. Currently we see the cursor itself on the right side of the table boundary. 
![image](https://user-images.githubusercontent.com/79509062/126142399-5c34e77a-4b4d-48b1-89ff-3f4b87837b9b.png)


Don't know why the screen record hasn't captured the icon. Don't seem to be able to capture it over screenshot either. Could get on call if it's unclear since I'm not able to capture it as evidence.

**Comment by somangshu** [comment]
The expand should work when we drag any of the pivots provided for expansions. Also the property pane moves automatically based on the space available. I am closing this for now because of no clarity here. Please feel free to open this again if required.

**Comment by ramsaptami** [comment]
There's an inconsistency in behaviour here which I feel can be addressed for better user experience. The property pane moves in tandem with the space available as you've explained _if_ present on the left side of the table. But this functionality isn't consistent when property pane is on the right side.

**Comment by Nikhil-Nandagopal** [comment]
Closing since we're docking the property pane
