### ISSUE TITLE
[BUG] After inviting the user, email ID is copied to Name field as well

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#595]
Issue: After inviting the user, email ID is copied to Name field as well. Either Name should be left blank or it should be updated later on.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate :
1.Login to https://app.appsmith.com/user/login
2. go to 'Manage users'.
3. Click on 'Invite Users'
4. Fill up the details and click on 'invite'.

Actual Result: 'email ID' provided is also copied to the Name field.
Expected Result: email ID provided should not be copied to the Name field.

Attachment: https://drive.google.com/drive/folders/1dP-YRPvK_9zalv9qAKOQjs7hM8xob6HW?usp=sharing

**Comment by trdillon** [comment]
I would like to work on this issue if it is still available. I would just like to clarify the scope of this so I know what direction to work in. Should this be addressed by just preventing the copying of the `Email` into the `Name` field and leaving it blank? Or should the functionality to edit the user's `Name` be added as well?

**Comment by Nikhil-Nandagopal** [comment]
@trdillon go for it! I think for now just preventing the copy should be great, once we have an additional page for account setting, this makes sense
