### ISSUE TITLE
[Bug]Unable to access previously created Apps 

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#5954]
Steps:

Release v1.5.8
1.After the latest update i am not able to access my previously created apps and org.

the below call is failing
api/v1/datasources?organizationId=6024c54a70eb652de1947810
takes long time, leading to error

**Comment by Nikhil-Nandagopal** [comment]
@NandanAnantharamu can you paste the URL of the app you're not able to access
