### ISSUE TITLE
[Bug] No visual Feedback while Duplicating Apps

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#5956]
## Description

I think this issue is with newly created Orgs.
Duplication worked fine for Apps in older Orgs

https://www.loom.com/share/807899cee8f548c3acd10b91344875e5

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope its working for me. Can you try with a new org?

**Comment by Tooluloope** [comment]
> @Tooluloope its working for me. Can you try with a new org?

Yeah, I'll close this now, 
I think it was the jarvis app that had issues with duplicating.
