### ISSUE TITLE
Refactor commenting API to allow comments in other parts of the application

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#5962]
To support adding a comment to any part of the application, we may need to change the current comment API so that they can be tagged to other parts of the application. Currently, we can only add comments to canvas.

**Comment by Nikhil-Nandagopal** [comment]
Related to #5601

**Comment by hiteshjoshi** [comment]
Closing this as its a subset of task we will do for extending comments.
