### ISSUE TITLE
Sync branches with remote counterpart (how far behind or ahead is local repo from remote)

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5967]
- [ ] Show how far behind is local from remote counter part using the status api, display this count along with the bottom bar pull button
- [ ] Fetch git status during app init so that the status is updated on navigating to an app and checking out a branch

**Comment by AnaghHegde** [comment]
@rishabhsaxena This is done right? Can we close this ?

**Comment by rishabhsaxena** [comment]
@AnaghHegde would close this along with the pull button changes
