### ISSUE TITLE
Import app flow into the org via GIT

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5969]
- Import link at organisation context menu at the home page
- Import modal at the home page. Steps:
    - Generate a standalone ssh key 
    - Connect step: Import api that supports local git config, repo URL or flag to use local / global
    - Message: datasources won’t contain secrets
    - On completion should navigate to the newly created app with the default branch checked out

Edge cases to consider:
- On quitting the flow after generating the key should a new app be created or only on completion?
- Datasources should need to to be updated only if the app is being imported into a new org which doesn't contain the datasources

### Tasks
- [x] #9755
  - [x] Make the SSH generation API independent of application id
  - [x] API for connect to git should work independent of application id  
- [x] #9754
- [ ] #9753
- [x] #10700
- [x] #10882
- [x] #10700 
- [x] #10884 
- [ ] #10950

**Comment by hiteshjoshi** [comment]
Next actions : 
Convert datasource flow to wireframes, UI etc.

**Comment by hiteshjoshi** [comment]
Next actions : 
@vuiets to get mixpanel events for git import for create datasource.
