### ISSUE TITLE
[BUG] Sorting isn't needed for 'delete' column.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#597]
Issue: Sorting isn't needed for 'delete' column.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate :
1.Login to https://app.appsmith.com/user/login
2. Go to Manage Users
3. Sort the columns

Actual Result: On the 'delete' column, there is a sorting option.
Expected Result: Sorting isn't needed for 'delete' column.

Attachment: https://drive.google.com/drive/folders/1XEVSLwZO7GovCHNg40Y3XTBEGC8q99C5?usp=sharing

**Comment by trdillon** [comment]
I would like to take this on if it is available to work on.

**Comment by Nikhil-Nandagopal** [comment]
@trdillon that's great to hear! Go for it 🎉 
I'm assigning this to you. @riodeuno will help you with the PR
