### ISSUE TITLE
[BUG] Search doesn't work properly

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#598]
Issue: Search doesn't work properly

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate :
1.Login to https://app.appsmith.com/user/login

Example 1 :  type 'tally' and 'table tutorial' appears as a matching result.
Example 2 : type 'facebook' and no matching result appears. There should be a message informing the user that there are no matching results. We can also display 'Create New' option in 'no match found' cases if users wants to go for a new one.

Attachment: https://drive.google.com/drive/folders/1yFtTqoGf8FM7L-NlYeOYQ8fNsI9cCGqq?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 the search is fuzzy and powered by algolia so can't control it much. Will work on adding a message for no results found. Thanks!
