### ISSUE TITLE
[Enhancement] Table Widget Filter Pane - clear button to remove all filter

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5980]
## Description
Deploy Preview - https://github.com/appsmithorg/appsmith/pull/5886
Table Widget - Filter pane - Suggestion to have clear button in the filter pane so that the user can clear applied filters without removing the applied filters.

### Steps to reproduce the behaviour:

1.Launch Appmsith app in the Deploy Preview - https://github.com/appsmithorg/appsmith/pull/5886
2.Drag and Drop Table Widget 
3.Open filter pane 
4.Apply any filter and check there is no option to clear applied filter

### Important Details

- Version: [11.3 ]
- OS: [MacOS  Big Sur]
- Browser [chrome, safari]
- Environment [
<img width="1280" alt="Screenshot 2021-07-20 at 9 30 12 AM" src="https://user-images.githubusercontent.com/35128442/126260282-b3618c47-c39d-4c9e-90c0-5b0238d8d5b1.png">
deploy preview]

## Figma Designs Link
New modal design: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=816%3A1266
Cancel (X) button on hover: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=841%3A1186

**Comment by somangshu** [comment]
@momcilo-appsmith need design for clear all filters in the filter pane
