### ISSUE TITLE
[Bug]The queries are failing when the user is trying to generate a query from the database structure in the entity pane 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#5989]
## Description

[What happened]The queries are failing when the user is trying to generate a query from the database structure in the entity pane 

### Steps to reproduce the behaviour:

1. In MYSQL-> the Only Update  query is failing
Link:https://drive.google.com/file/d/12G7MrHw62KwVj7VV-keG7rutp3DBbOcH/view
2.In PostgreSQL->Update and delete query is failing.       
link:https://drive.google.com/file/d/1288FTJzkg-OlkF0b27qfgZuyi4VZ5UI9/view
3.In MongoDb->Other than find all the other query is failed as we have to manually enter the objectID otherwise it fails
link:https://drive.google.com/file/d/1UttKPC_Z6vkisZiIUgXfgL31pB8m82rz/view
4.Snowflake->Insert Update and Delete queries are failing 

### Important Details

- Version: [Cloud ]
- OS: MAC
- Browser Chrome
- Environment Deploy preview

**Comment by pranavkanade** [comment]
This is an old bug (not sure when it got introduced), I could trace it back to at least early this month on master branch.

**Comment by pranavkanade** [comment]
caveat - 
following unedited template query fails - 
```
UPDATE public."employees" SET
    "employee_id" = 1
    "employee_name" = ''
    "phone" = ''
    "email" = ''
    "department_id" = 1
    "calendar" = ''
  WHERE 1 = 0;
```

Although when tried to update only one field, it works - 
```
UPDATE public."employees" SET
    "employee_name" = ''
  WHERE 1 = 0;
```

PS - if user tries to update anymore than 1 field this query fails with `Syntax Error`

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni  can someone help with this?

**Comment by RakshaKShetty** [comment]
@nidhi-nair The issue is not fixed still the query fails
When I try to execute the Update query for Postgre I can still see the error in the debugger

**Comment by nidhi-nair** [comment]
@RakshaKShetty could you please record a video of this? I'm unable to reproduce the error on release.
