### ISSUE TITLE
[Enhancement] Auto encode / decode s3 file data

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5990]
## Description
When a user chooses not to encode the response type, it may corrupt the data when sending it to the client. 

## Possible solution
Always encode the data in base64 before returning the response to the client. The client would then decode it back to a binary to avoid breaking any functionality. 

We came to the following conclusion via the meeting on 20-07-2021: 
The server will send a flag to the client to indicate whether the data returned should be decoded or not, irrespective of whether the data is encoded. This should take care of the situation when a user has turned on/off the base64 encode option for s3. 
We should use the same flag for the REST API implementation as well.

**Comment by trishaanand** [comment]
I think that the UX still needs to be finalised for this interaction. Even though the change itself should be minor and easy to be picked up as a Good First Issue, this needs to be discussed in the team for the ramifications. Removing the GFI tag.

**Comment by nidhi-nair** [comment]
Should be handled by enabling support for binary data instead. Closing in favour of #8431
