### ISSUE TITLE
[Bug] Comment is not refocused on closing the comment thread and clicking on it again

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#5993]
## Description

- Add a comment at a position such that we need to scroll
- Click on the comment card link from the sidebar
- Close the comment thread, scroll away and click on the same card again
- The comment card is not refocused

**Comment by RakshaKShetty** [comment]
The issue is not fixed. When i followed the above-mentioned steps they could reproduce the issue. so reopening the issue

**Comment by RakshaKShetty** [comment]
@rishabhsaxena, the comment is not refocused, correctly  when the user clicks on the comment card link from the sidebar screenshot:
![image](https://user-images.githubusercontent.com/45958978/127951474-87a5de18-aff5-4390-978a-c3987f9a837e.png)
