### ISSUE TITLE
[Feature]-[1000]:Improve navigation for mock data queries

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#5994]
In the options to use new mock datasources, for a first time user, it takes a bunch of clicks before the first query is actually set up. Can we navigate directly to a pre-filled select query instead?

Steps:
1. Click on + datasources on entity explorer
2. Click on Mock database - movies => navigated to active datasources page
3. Click on new query - movies => navigated to new empty query form
4. Since the structure for this database is not known, and since I already knew that I can get the structure from the entity explorer, I clicked on new query from the populated structure. => creates another query leaving the empty query behind
5. Execute query using Run button

Ref: https://theappsmith.slack.com/archives/C01HUHMDPS9/p1626700863338900

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 0.5|

**Comment by akash-codemonk** [comment]
To be clear we want to land on the query page directly instead of going to the the active tab for mock datasources?

**Comment by kocharrahul7** [comment]
Ideally, we should also unfurl the entity explorer for any newly created DB, so the user can understand at least the collection/db list, and can unfurl it further to expose the db structure.

Going directly to the query page breaks the information flow.

**Comment by kocharrahul7** [comment]
This is no longer relevant. The datasources are no longer reflected on the entity explorer
