### ISSUE TITLE
[Task] Update Storybook with example for Dropdown's (components/ads) new props

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#6002]
## Demo example for `renderOption`

- [ ] Create a custom dropdown option component and use it with `renderOption`.

**Comment by areyabhishek** [comment]
Will we start using storybook again? We'll be updating the Appsmith design system, so wondering if we should storybook during the process.

**Comment by Rishabh-Rathod** [comment]
We have removed storybook examples currently. Hence closing this issue.
