### ISSUE TITLE
[Bug] Select widget - disable functionality dosent work

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6007]
## Description

The disable functionality in the select widget seems to be broken. On changing the toggle or adding a JS binding no change is observed

### Steps to reproduce the behaviour:

1. Drag & drop a select widget
2. Toggle disable prop
3. Observe that the widget does not disable

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Browser [chrome, safari]
- Environment [production,]

**Comment by somangshu** [comment]
@Tooluloope lets triage the issue here, how was this bug introduced

**Comment by Tooluloope** [comment]
@somangshu this is already fixed in the Multiselect PR,
Check the video if it's exactly what you mean
https://www.loom.com/share/4499c1712b4a47a088f1cb49b4b821f6

**Comment by areyabhishek** [comment]
It seems that the select widget is disabled, but it doesn't look disabled. 

@Tooluloope Can you ensure the disabled states look same for all input widgets? Please ask for help from Momcilo if you need designs.

**Comment by somangshu** [comment]
@Tooluloope @vivekverma2312 is this verified for the select widget as well?

**Comment by vivekverma2312** [comment]
@somangshu It's tested and working fine for both select and multi-select on deploy preview 
https://deploy-preview-5228--appsmith-editor-ce.netlify.app/
https://www.loom.com/share/8f45a58f9b2b42779d56687d282cdb44
