### ISSUE TITLE
[BUG]  Timer doesn't work in pre-fill form. Gender field should have more options.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#601]
Issue:  Timer doesn't work in pre-fill form

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login https://app.appsmith.com/user/login
2. Form Tutorial --> Launch 
3. Go to Pre-fill form

Actual Result: Timer doesn't work in date-of-birth. While picking date and time, only date can be picked and even if user tries to select a timing, it's not getting picked from the calendar to the input field.

Small suggestion: In this world of wide possibilities, let's not stick to 2 genders : Male and Female. We can have multiple options here.

Attachment: https://drive.google.com/drive/folders/1U8NYuPaifjG4puZA_m7zcKU5UbUIGTl7?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 can you expand on what do you mean by timer doesn't work?

**Comment by Saket2** [comment]
@Nikhil-Nandagopal Updated the actual result.
