### ISSUE TITLE
Onboarding tours / help content

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#6015]
Onboarding tours / help content, for example:

- Going live from local mode
    - How deploy previews work
    - Prompt to update datasource credentials
- Git related help
    - Managing conflicts
    - Info related to auto rehydrating db when pulling changes from another branch
- Tour at the home page to explain how applications work across branches

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal @Debsourabh when does this onboarding get triggered?

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek we haven't thought through this yet. The team just added the issue so they can get an overall estimate.
