### ISSUE TITLE
[Feature] Change text on datasources page

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6019]
1. 'Create new' should be 'Create new API'
2. CURL should be 'CURL import'
Suggesting this change now because it feels

<img width="493" alt="Screen Shot 2021-07-21 at 1 14 59 AM" src="https://user-images.githubusercontent.com/30255708/126386012-78b705b4-c15e-4f44-8731-e0f51034d577.png">

**Comment by prapullac** [comment]
Hi @ohansFavour 
Reopening the issue as I do not this these changes on the release. Attaching the screenshot for reference.
![Screenshot 2021-07-30 at 12 30 51 PM](https://user-images.githubusercontent.com/71753653/127614084-274beabe-4983-4e9d-9f12-a21af762cfe2.png)

**Comment by prapullac** [comment]
Closing the issue as it is been changed accordingly.
