### ISSUE TITLE
[BUG] 'Update User' doesn't work in pre-fill form

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#602]
Issue: Update User doesn't work in pre-fill form

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login https://app.appsmith.com/user/login
2. Form Tutorial --> Launch
3. Go to Pre-fill form
4. Fill information and click on 'Update User'

Actual Result: Throws an error (attachment provided)

Attachment: https://drive.google.com/drive/folders/1Mp94ixuAbaRuKhfQ5FML5mCWr0z1xSfr?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 this is part of the example apps, if you edit the app, the instructions become clearer
