### ISSUE TITLE
[Bug] Video widget label and property pane does not move in tandem with widget when resized

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6021]
## Description

When the video widget size is either increased or decreased, the widget label and property pane does not move in tandem with the size as it's meant to. It remains in its original position and at times gets hidden behind the video widget making it inaccessible to the user. If widget is stretch over the label then user is unable to access to widget label thereby, no access to property pane or move function.

### Steps to reproduce the behaviour:

1. Go to add widgets
2. Drop video widget onto the canvas
3. Increase size of the widget and observe the label and properties pane remain in the original position instead of moving in tandem with each other

### Important Details

- Version: Cloud
- OS: Win10
- Browser: chrome
- Environment: production
https://www.loom.com/share/5b5cc0be1e944a2f84c773e132d494b5

**Comment by rahulramesha** [comment]
This issue was fixed in https://github.com/appsmithorg/appsmith/pull/5823. Fix is already in release, It should be fixed once it is moved to production.
