### ISSUE TITLE
[Bug] Video widget once resized, reverts back to original size and cannot be relocated

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6022]
## Description
When video widget is resized and user tries to move widget location the widget snaps back to the original position and also back into its original size.

### Steps to reproduce the behaviour:

1. Go to add widgets
2. Drag and drop video widget on to canvas
3. Reduce size of the widget and try to move it to different location (expanding widget currently blocks access of label under #6021 but can replicate this by refreshing the page after expanding and then trying to relocate the widget)

### Important Details

- Version: Cloud
- OS: Win10
- Browser: chrome
- Environment: production
https://www.loom.com/share/e8170e21b9fb4728a9b5f2ae8b4fea67

**Comment by rahulramesha** [comment]
This issue was fixed in https://github.com/appsmithorg/appsmith/pull/5823. Fix is already in release, It should be fixed once it is moved to production.
