### ISSUE TITLE
[Enhancement][JS Snippets] Deploy Mongodb + AWS Lambda + Algolia pipeline in production.

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#6025]
Following would be required: 
(1) Set up Event bus to connect AWS Lambda to Mongo Atlas.
(2) Upload Lambda deployment package. 
(3) Set up Algolia Index.

**Comment by sumitsum** [comment]
The pipeline has been deployed and tested with sample documents.
