### ISSUE TITLE
[Bug] Duplicate Entries in Autocomplete with Maps and slash command

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#6028]
## Description

Observed Duplicate entries in Map Widget autocomplete while using slash command.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Add map widget
2. Open Property Pane
3. Click Default Marker. Cmd+A , del
4. Press / and select map from Bind data

https://www.loom.com/share/a844ebf853f849228e871a181d8a78bc

### Important Details

- Version: cloud
- OS: MacOS 11.3.1(Apple m1)
- Browser: Chromium Version 94.0.4582.0 (Developer Build) (x86_64 translated)
- Environment: release-frozen(Created on 19July2021)

**Comment by hetunandu** [comment]
Fixed with #5798
