### ISSUE TITLE
[BUG] Issues due to long organization name

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#603]
Issues:
1. UI is distorted
2. Down arrow stops working
3. There should be a limit on long organization name or there should be a way to handle it on the UI

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login https://app.appsmith.com/user/login
2. Click on 'Create Organization'
3. Type a long name in Organization name and then submit.

Attachment:  https://drive.google.com/drive/folders/1tDL7LQ2kUxoBKeAylWyl8CNoHqvSc_zp?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@satbir121 can you verify this

**Comment by satbir121** [comment]
@Nikhil-Nandagopal Could not reproduce the issue. UI breaks and the dropdown might not be in the viewport in few machines. A possible solution would be to fix the length of org name and add an ellipsis to the dropdown.

**Comment by satbir121** [comment]
Duplicate #713 #735
