### ISSUE TITLE
[Bug] Enabling/Disabling Switch Widget should change default Selected Value

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#6031]
## Description

Enabling/Disabling Switch Widget should change default Selected Value

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Add switch Widget
2. Add open Modal onChange
3. Set Default selected to True
4. Click switch widget
5. 
https://www.loom.com/share/44148b3b82dd4002b2621bf96ff463ee

### Important Details

Version: cloud
OS: MacOS 11.3.1(Apple m1)
Browser: Chromium Version 94.0.4582.0 (Developer Build) (x86_64 translated)
Environment: release-frozen(Created on 19July2021)

**Comment by Nikhil-Nandagopal** [comment]
@yatinappsmith this is incorrect. The default value is the value the widget is meant to have on load. The user changing this value does not affect its value on next load.
