### ISSUE TITLE
[Bug] File picker widget display modal and property pane on click and exits both on click of 'esc' key

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6032]
## Description
On clicking the file picker widget, both the modal window and property pane pop up and on pressing the 'esc' key both windows exit.

Other widgets such as Label, Switch, Select, Radio Group follow the same pattern where click function dually triggers **widget specific click event and displays property pane** but think this can be revisited if the click function is meant for end user only?

### Steps to reproduce the behaviour:

1. Drag and drop file picker widget from widgets toolbar
2. Click on the widget and observe modal and property pane windows pop-up
3. Press 'esc' key. Both windows close from the 'esc function'

### Important Details

- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e0417c81f2634cc2bc9795b68f4112c2-00001.gif)](https://www.loom.com/share/e0417c81f2634cc2bc9795b68f4112c2)

**Comment by somangshu** [comment]
@areyabhishek @marks0351 would you consider this to be an acceptable behaviour? A similar problem also occurs when implementing the double click opens property pane. Do we need a UX change here?

**Comment by areyabhishek** [comment]
Will double click prevent the upload modal from opening up? That's the ideal scenario.

**Comment by somangshu** [comment]
@areyabhishek as per the current requirement changes, we are not implementing the double click open property pane and only on first drag and drop the property pane will show up, Post that clicking the widget tag will open the property pane. 

If this is acceptable then this argument stands invalid.

**Comment by dilippitchika** [comment]
@somangshu can you confirm if this is applicable anymore? If not, let's close this.
