### ISSUE TITLE
[BUG] Wrong error message while trying to create an organization with no name

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#604]
Issue: Wrong error message while trying to create an organization with no name

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login https://app.appsmith.com/user/login
2. Click on 'create organization'
3. Without providing a name, click on 'submit' button.

Expected Result: Proper error message notifying user that organization name is a mandatory field.
Actual Result: Error message 'Bad Request: Validation failure'

<img width="1792" alt="Screen Shot 2020-09-19 at 10 46 57 PM" src="https://user-images.githubusercontent.com/49346036/93677427-626efc80-faca-11ea-875f-6f689060c8dd.png">

**Comment by trishaanand** [comment]
Analysis : This is happening because we are using Spring's validation check here instead of doing the validation manually.

**Comment by pc9795** [comment]
I am looking 👀 into this.

**Comment by mohanarpit** [comment]
@pc9795 Go for it ! 🎉 

You can customize the error message by referencing [this article](https://www.baeldung.com/spring-validation-message-interpolation)
