### ISSUE TITLE
[Bug] Property pane toggles from right to left on placing widgets on to the bottom of a page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6040]
## Description
This is observed for large widget like **chart, map, container, form, map, rich text, table, video widgets** (except list widget)
- While placing a widget to the **center bottom or left bottom of a long page (when page height is automatically increased)**, the property pane first appears on the right and then docks itself on to the top left corner of the workspace.
- When user places the widget on to the **right bottom of a long page (when page height is automatically increased)** then property pane appears on the left side and then docks itself to the top left corner of the workspace
- In the case of **form widget**, property pane toggles from right to left and then back to the right.

### Steps to reproduce the behaviour:
1. Drag and drop mentioned widgets on to canvas of a long page either to the left, center or the right of the page and observe behaviour of the property pane

### Important Details

- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5d4cb30a3f5d4ca1afcf814fbdcb1adf-00001.gif)](https://www.loom.com/share/5d4cb30a3f5d4ca1afcf814fbdcb1adf)

**Comment by areyabhishek** [comment]
When this occurs, the top of the property pane isn't visible. This means the user can't close or move the property pane to a different location.

**Comment by Nikhil-Nandagopal** [comment]
Closing since we're docking the property pane
