### ISSUE TITLE
[Bug] Resolve UnsupportedOperationException due to updates in ImmutableCollection error in analytics service

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#6050]
Due to updates in properties compiler is throwing ImmutableCollection error :

java.lang.UnsupportedOperationException: null
at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java)at java.base/java.util.ImmutableCollections$AbstractImmutableMap.put(ImmutableCollections.java)

**Comment by RakshaKShetty** [comment]
The backend actions are not getting captured in Segment app for release RC. I have tested with local instance and it is capturing backend action correctly. So we will check that backend actions are getting captured correctly once it is moved to production. it looks fine for now
