### ISSUE TITLE
[Bug]For Firestore the add button in entity pane to auto generate the query is not clickable and not working

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6054]
## Description For Firestore the add button in the entity pane to auto-generate the query is not clickable and not working

Step to reproduce:

https://loom.com/share/f81b1dcf38f44c1185cc95b689cf5722

- Version: [Cloud ]
- OS: Mac
- Browser safari
- Environment: release frozen

**Comment by rohan-arthur** [comment]
this feature is not available for firestore, and the `Add` button doesn't show up now anymore
