### ISSUE TITLE
[Bug]In ArangoDB the response is not displayed when the action is successful for Insert,Delete and update query

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6055]
## Description In ArangoDB the response is not displayed correctly when the action is successful for Insert, Delete and update query

[What happened]

### Steps to reproduce the behaviour:

https://loom.com/share/6c7622e6edd84aa0aa337676f213815f

### Important Details

- Version: [Cloud]
- OS: Mac
- Browser [Safari]
- Environment release frozen

**Comment by nidhi-nair** [comment]
Related to #4263

**Comment by RakshaKShetty** [comment]
![image](https://user-images.githubusercontent.com/45958978/133375821-62596331-e5e8-4c68-b1be-c74a6668a683.png)
