### ISSUE TITLE
[Bug]In the snowflakes database when the user executes update query the text is not displayed fully and also no tooltip in the response tab 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6057]
## Description In the update query for snowflakes  in the response tab the text is not displayed fully in the table for the "Number of multi-" and there is no tooltip displayed

[What happened]

### Steps to reproduce the behaviour:

1.Add the new data source Snowflakes
2.Now create an insert query and add few details
3.Now update the raw items using a update query 
4. verify the response displayed after successful execution of the query

expected result: The text  looks broken as in the screenshot attached the full text should be displayed inside the table or the tooltip should be displayed

![image](https://user-images.githubusercontent.com/45958978/126504613-f1ba6c37-a81f-4fc0-8460-f7d2c73f1df8.png)

### Important Details

- Version: [Cloud /]
- OS: [MAc]
- Browser [Safari]
- Environment [release freeze]

**Comment by nidhi-nair** [comment]
@ajinkyakulkarni This issue is a front end bug, the API response returns with the correct headers, but the display seems to break it off at the hyphen.

**Comment by nidhi-nair** [comment]
Related to #4263

**Comment by ajinkyakulkarni** [comment]
@trishaanand Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6057?planning-poker)

**Comment by ajinkyakulkarni** [comment]
@trishaanand @ohansFavour Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6057?planning-poker)

**Comment by ohansFavour** [comment]
Hi @aakashDesign, what do you suggest as the expected display when the text size is larger than expected size?

**Comment by RakshaKShetty** [comment]
![image](https://user-images.githubusercontent.com/45958978/133380892-a116f003-2ed0-4519-9907-987aeee8c557.png)
