### ISSUE TITLE
[Bug] the tooltip "Click on the icon to access comments." highlights both the comment icon and Edit icon when the viewer completes the onboarding

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6059]
## Description when the viewer complete the onboarding the tooltip "Click on the icon to access comments." highlights both the comment icon and Edit icon

[What happened]

### Steps to reproduce the behaviour:

when the "click on the icon to access comments " tooltip is displayed only the comment icon should be highlighted 
![image](https://user-images.githubusercontent.com/45958978/126507092-ae4876b9-a6f1-49d6-8a6d-f5ba36f3d3be.png)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser [safari]
- Environment release frozen

**Comment by rishabhsaxena** [comment]
@RakshaKShetty closing this since we're highlighting the comment mode button through the pulsing dot, even though both the options are highlighted.
