### ISSUE TITLE
[FEATURE] Installation Support For Debian

### ISSUE THREAD

**Issue by amneo** [appsmithorg/appsmith#606]
## Summary

Installation support for Debian

## Motivation

Ubuntu installation support exists, thus supporting Debian would not be a trouble.

Since Ubuntu has been derived from Debian and their repositories co-exists.

**Comment by mohanarpit** [comment]
@amneo Our current installation process already supports Debian. Do check out the [Getting Started Guide](https://docs.appsmith.com/quick-start#docker) and execute the steps on a Debian server. 

If you face any issues in the installation steps, do let me know. For now, I'm closing the issue.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit re opening this because @amneo was facing an issue while installing on Debian. Can you check this out?
