### ISSUE TITLE
[Bug] Inconsistent stretch icon on widget corners

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6061]
## Description
Widget box corners show diagonal arrows on hover to indicate diagonal stretch on all except the top left corner. This icon would need to change to maintain consistency.

### Steps to reproduce the behaviour:
1. Drag and drop any widget from toolbar and hover over the corners
2. All corners except the top left one are diagonal with diagonal stretch feature.

### Important Details
- Version: Cloud
- OS: Win10, MacOS
- Browser: Chrome, Firefox, Safari
- Environment: Production

https://www.loom.com/share/60a5fda4587b42c39ae104474f0e8264

**Comment by haojin111** [comment]
Hello, @areyabhishek !
You mean when user stretching corner with diagonal arrow, cursor shouldn't be changed while dragging?

**Comment by ramsaptami** [comment]
So on all corners of any widget (except the top left), we see a diagonal icon to indicate stretch action.
On the top left corner, the icon is a vertical icon instead. This would need to be diagonal too to be consistent.

**Comment by somangshu** [comment]
@ramsaptami can you test this out?
