### ISSUE TITLE
[BUG] Option to download the chat is hidden while at the latest message.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#607]
Issue: Option to download the chat is hidden while at the latest message.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login https://app.appsmith.com/user/login
2. Click on '?'
3. Click on 'Chat with us'
4. Now type a few things

Actual Result: Option to download the chat is hidden. It's only visible if user goes to top of the chat i.e. towards the 1st message in the conversation.
Expected Result: It should be visible irrespective of which message is user at.

Attachment: https://drive.google.com/drive/folders/1skJxTd47mLu5TjXTfChfnvfFDwKThDKf?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 this is part of intercom so not something that's under our control
https://app.intercom.com/
