### ISSUE TITLE
[Bug] Spacing in the pagination page slash command API pane pagination of 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6079]
Steps to reproduce:

1) Navigate to Datasources
2) Navigate to API Pane
3) Add an API 
4) Navigate to the Pagination page 
5) Select Paginate with Response Url
6) Focus on Previous and Next URL
and observe spacing around the Slash cmd

<img width="726" alt="Screen Shot 2021-07-22 at 6 05 52 PM" src="https://user-images.githubusercontent.com/71753653/126645637-bd1f735e-e090-4426-ae1e-8bcef7fbd5b1.png">
<img width="1099" alt="Screen Shot 2021-07-22 at 6 06 12 PM" src="https://user-images.githubusercontent.com/71753653/126645652-56280ea8-4fd4-46c0-a0d6-ef3aabd9eea3.png">

**Comment by areyabhishek** [comment]
Closing this because Arun created an issue for this already.
