### ISSUE TITLE
[BUG]Cancel button doesn't function.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#608]
Issue: Cancel button doesn't function.

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login https://app.appsmith.com/user/login
2. Go to Customer Support Dashboard --> launch --> Select User --> View User --> Edit --> cancel

Actual Result: Cancel button doesn't work

<img width="1737" alt="Screen Shot 2020-09-20 at 12 03 59 AM" src="https://user-images.githubusercontent.com/49346036/93686656-53417c00-fad5-11ea-95e7-df3ecbb6a1c2.png">

**Comment by harishkotra** [comment]
Support dashboard is an example and the Cancel button doesn't have an action attached to it. Not a bug (See attached below)

![image](https://user-images.githubusercontent.com/4999463/93687597-6a379c80-fadc-11ea-814a-2845271b9b79.png)

Cc: @Nikhil-Nandagopal

**Comment by Saket2** [comment]
Thanks for the clarification. This is not a bug.

**Comment by hetunandu** [comment]
Thanks @harishkotra and @Saket2 
Closing the issue
