### ISSUE TITLE
[Bug] UX : API pane tab panel moves when swapped between tabs

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6080]
Steps to reproduce:
Scenario 2 :
1) Navigate to Datasources
2) Navigate to API Pane
3) Add an API 
4) Swap between Tab Panel of API setting 
and observe there is the movement of header where there is swapping

Observation:
when the user moves between the header and pagination it is observed that there is movement 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f473098047484ff7b764205a33d1617d-00001.gif)](https://www.loom.com/share/f473098047484ff7b764205a33d1617d)

**Comment by hetunandu** [comment]
Cannot reproduce

**Comment by prapullac** [comment]
@hetunandu Can not reproduce the issue hence closing the issue
