### ISSUE TITLE
[Bug] Table selectedRows property doesn't work in multi-select

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6082]
The selectedRows property doesn't work. It used to work, but it doesn't anymore.

**Comment by somangshu** [comment]
I cant seem to reproduce this error.

<img width="624" alt="Screenshot 2021-07-23 at 11 00 44 AM" src="https://user-images.githubusercontent.com/11089579/126740907-666efbb5-93a0-448b-bc7e-c2d97ef8a550.png">

Any specific steps here to reproduce? @vivekverma2312 can you check to find the reproducible steps?

**Comment by vivekverma2312** [comment]
@somangshu It's working fine for me also.
<img width="1139" alt="Screenshot 2021-07-26 at 1 29 10 PM" src="https://user-images.githubusercontent.com/83569920/126954112-c748f668-b946-44a8-96c2-9a5f8c1b3bd4.png">

**Comment by somangshu** [comment]
@areyabhishek we are closing this for now. Shall keep an eye for it, In case we are able to reproduce this.
