### ISSUE TITLE
[Bug] Bottom of the editor expands when multi-line code is entered

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6088]
### Steps to reproduce the behaviour:

1. Drag and drop a form widget
2. Open property pane for submit button
3. For on click property enter multi line code
4. Observe that bottom of the editor expands

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser: chrome
- Environment: production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/803c9f7905a64b08a53c468e358543e2-00001.gif)](https://www.loom.com/share/803c9f7905a64b08a53c468e358543e2)

**Comment by somangshu** [comment]
@vivekverma2312 what is meant by "button of the editor expands"? Please you explain a bit more.

**Comment by vivekverma2312** [comment]
This is working fine in #7361
