### ISSUE TITLE
[BUG] Wrong error message during sign up

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#609]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Hit https://app.appsmith.com/user/login
2. Sign up with details - ab@b.com/123123
3. Sign out
4. Now go to the sign up page and again try to sign with ab@b.com/123123

Actual Result: Message is displayed 'There is already an account registered with this username ab@b.com. Please sign in.'
Expected Result: Message should be 'There is already an account registered with this Email  ab@b.com. Please sign in.'

Note: Since there is no mention of username on login/signup screens, it should be handled that way.
<img width="605" alt="Screen Shot 2020-09-20 at 10 50 09 AM" src="https://user-images.githubusercontent.com/49346036/93694975-86185e00-fb2f-11ea-894e-a09133f64d84.png">

**Comment by mohanarpit** [comment]
This can be resolved by changing the error text for the enum `USER_ALREADY_EXISTS_SIGNUP` in the file `AppsmithError.java`
