### ISSUE TITLE
[Feature] Enable a commenting & Notification API inside appsmith

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#6092]
This below description is based on messages from Abhishek Nayak.

Need an API that lets our developer users trigger comments. Like if this button is clicked, then notify the user. 

The basic idea is that we can allow developers to notify users when something happens. It's a simple messaging system that's difficult to implement in internal apps

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_71vd8)

**Comment by areyabhishek** [comment]
Suggesting this as an enhancement to the commenting feature because this extends the feature into something that no other tool does. This API will make this an exciting new shiny feature that we could use to talk about why real-time commenting is special.

**Comment by sumitsum** [comment]
Adding a bit more scope to this feature based on a discussion with a Discord user: Provide notification icon on the right hand corner of any deployed application. Expose an interface / API such that a notification gets pushed to any deployed app using this interface / API. 
```
E.g. on the home page, there's a bell icon at the top that users see when they're logged in.

Wondering if there's a way to access that feature for our appsmith app to send the user notifications (or whether we'd have to build our own).
```

**Comment by codename89** [comment]
Hi please add a notification widget which tracks and displays all the changes made by the users after deployment.
