### ISSUE TITLE
[Bug] Deploy Preview - The Evaluated pane closes when the user moves the cursor towards the property pane

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6093]
## Description
Deploy Preview - https://deploy-preview-5270--appsmith-editor-ce.netlify.app/
It is observed that when any of the evaluated pane is opened and when the user move the cursor towards the property pane the evaluated pane closes

**Expected result:**
Evaluated pane should not close until user click anywhere outside the property pane or when the user clicks on any other field on the property pane

[What happened]
1. Launch appsmith app in the Deploy Preview - https://deploy-preview-5270--appsmith-editor-ce.netlify.app/
2. Drag and drop any widget 
3. Open any of the evaluated pane 
4. Mouse hover towards property pane and observe 

**VideoLink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/25633419c140404bb4ab30d753992a3c-00001.gif)](https://www.loom.com/share/25633419c140404bb4ab30d753992a3c)

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur ]
- Browser [chrome, safari]
- Environment [deploy preview]

**Comment by riodeuno** [comment]
@YogeshJayaseelan @vivekverma2312 I cannot replicate this issue.

**Comment by vivekverma2312** [comment]
@riodeuno It only happens if we expand any of the option in expected pane
https://www.loom.com/share/654264478474418bb41a45c633b19694

**Comment by riodeuno** [comment]
@vivekverma2312 This is the intended functionality. There is a delay of 1 second before the evaluated structure pane closes, earlier the issue was that this used to close even when the pointer was on the edges of the evaluated structure pane, which was preventing users from viewing the details while on the pane. Today, once they leave the pane, it waits for 1 second before closing.

**Comment by somangshu** [comment]
@vivekverma2312 this should probably close, Can we look into this

**Comment by vivekverma2312** [comment]
@riodeuno Is it possible that all the property in Evaluated Pane is maximised by default so that a user can see all the property while editing the field.

**Comment by riodeuno** [comment]
@vivekverma2312 Yes, it is. However, some structures and examples are large, which will push the evaluated value down. This is the reason for making them collapsed by default.

**Comment by bharath31** [comment]
This is no longer an issue in the new property pane
