### ISSUE TITLE
[Bug] Property pane goes into bad state when triggers call functions

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#6095]
## Description

If we choose to show a message on a trigger event for a widget in the non-JS mode, and call an API's run function, the components shown in the property pane automatically switch to that of the run function. The functionality is however retained for the show message components.

### Steps to reproduce the behaviour:

https://user-images.githubusercontent.com/5298848/126761620-055714d2-8743-47a9-a84b-682b38b05d30.mov

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by YogeshJayaseelan** [comment]
@rahulramesha Verified this and it is working as expected
