### ISSUE TITLE
[Bug] Name of Menu button has a space in it

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6098]
1. There's a space in the object name, which is not allowed in Appsmith.
<img width="161" alt="Screen Shot 2021-07-23 at 2 30 25 PM" src="https://user-images.githubusercontent.com/30255708/126760015-78e057e0-b3d0-473b-9ff7-eb331e490a9d.png">

2. Reduce the default width of the menu button to be smaller so that it can fit in tighter spaces and let the default text just be 'Menu' instead of 'Open menu'

3. There's no hover state for the menu button

4. The white colors look a bit weird. We might need color options here

**Comment by Tooluloope** [comment]
@areyabhishek this issue has been solved in this PR https://github.com/appsmithorg/appsmith/pull/5970
