### ISSUE TITLE
[Bug]When the user select the suggested widgets the Bindings Fails for Select, Chart and Text widget

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6103]
## Description When the user select the suggested widgets the Bindings Fails for Select, Chart and Text widget 

[What happened]

https://loom.com/share/0e57b88b831c45ae9a36344414a5f353
https://loom.com/share/9f93de4bba2948ac8663af5fac95f123

### Important Details

- Version: [Cloud ]
- Browser Chrome
- Environment [deploy preview]

**Comment by akash-codemonk** [comment]
@RakshaKShetty I am guessing this should work with say `select * from users limit 10`. 

This seems to be an issue with evaluation when there are large values. 

1) To replicate this you can copy the binding
2) Create a new select widget
3) Paste the binding.
4) It would show that it is in an error state.
