### ISSUE TITLE
[Bug][deploy preview]In generate table the tables are not displayed in the dropdown for the selected datasources 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6108]
## Description

[What happened]In generate table the tables are not displayed in the dropdown for the selected datasources 

### Steps to reproduce the behaviour:

1. Go to 'Datasource page'
2. select snowflake Datasource add all the details
3. click on generate new page button
4. if we see in the screenshot even when there are tables for the snowflake it is not displayed in the table dropdown

![image](https://user-images.githubusercontent.com/45958978/126793607-3ee9c2c4-b4d0-42a7-ab0a-a83275256dcc.png)

### Important Details

- Version: [Cloud]
- OS: [.MacOSX]
- Browser Chrome
- Environment [pdeploy preview]

**Comment by Rishabh-Rathod** [comment]
@RakshaKShetty #5513 only adds the frontend changes for generating the CRUD page and will not contribute to close this issue (#6108).
