### ISSUE TITLE
[Feature] Remove CTAs to launch omnibar from debugger

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6112]
Problem: There are two CTAs in the debugger that launch the omnibar. The likelihood of reaching a correct documentation link is too low. Thus the user is presented with no search results or wrong search results.

We can reintroduce this when we have all the errors logged. Today the omnibar triggers are way to prominent in comparison to how useless they are.

**Comment by Nikhil-Nandagopal** [comment]
Closing since we now have an explicit menu for these errors
