### ISSUE TITLE
[Feature]-[4000]:Debugger improvements

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6114]
1. Allow error messages to be cleared
2. Don't show a notification badge when there are 0 errors
3. Clear the notification count once someone has seen/read the errors

**Comment by rohan-arthur** [comment]
reach 2300

**Comment by rohan-arthur** [comment]
Consider 100% reach because this is a basic improvement in ux that will benefit all users

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | <<number>> |

**Comment by ayushpahwa** [comment]
Consider 100% reach because this is a basic improvement in ux that will benefit all users

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 1.5 |

**Comment by rohan-arthur** [comment]
not planned - we will relook at the debugger in the near future as part of the IDE pod roadmap
