### ISSUE TITLE
[Bug] Menu widget needs to show transparent background

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6117]
The menu widget continues to show white colour even when you choose no background colour. I think it'll be better if the colour is transparent, then the button can fit into the background.
@Tooluloope @jsartisan @somangshu

**Comment by somangshu** [comment]
@wmdev0808 here we will also change the background / text colour property inline to the button widget style customisation changes.
- Box shadow
- Menu styles (Primary, Warning, Danger, Info, Secondary, Custom)
- border radius
- get all style attributes inside style section

We will cover all this with the above fixes
