### ISSUE TITLE
[Feature] Stat box widgets

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6118]
# Objective
Introduce a stat box widget to show numbers at a glance. This is new widget, which is made with the help of old widgets (composite widget)

<img width="1011" alt="Screen Shot 2021-07-25 at 2 40 36 AM" src="https://user-images.githubusercontent.com/30255708/126881409-dbc84557-f2c4-49c9-a1d4-1dcda85e9f2b.png">

# Requirements

| Title | Description | Comment |
| ----- | ----- | ------ | 
| Container | Parent element is the container, Default to 14 rows and 12 columns | - |
| Text | headerText (para 2, #999999), bodyText (Heading 1, Bold, Black), captionText (para2, Theme success color) will be placed one below the other in the extreme left column | - | 
| IconButton / FAB | Default to solid, Success, Up arrow | The icon button will have a change here, When onClick action is not present the hover state and Click pointer should not occur |

> Preview
![Screenshot 2021-08-04 at 5 58 54 PM](https://user-images.githubusercontent.com/11089579/128180758-fc7fbe8c-793d-4d5f-bf9c-3fa106b42291.png)

**Comment by techbhavin** [comment]
@momcilo-appsmith can you please provide  an icon image for the widget panel for this widget
