### ISSUE TITLE
[Bug] Date picker shows an error if there's no default date picked 

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6120]
Date picker should be allowed to not have a default date. This looks like a bug.
<img width="499" alt="Screen Shot 2021-07-25 at 9 55 55 PM" src="https://user-images.githubusercontent.com/30255708/126906225-94ed1b65-19be-4f31-a42b-6fc463f614d4.png">

**Comment by vibhandikyash** [comment]
@YogeshJayaseelan Can you pl. recheck this one. Seems like it's working as expected.
cc: @somangshu

**Comment by areyabhishek** [comment]
I just checked this. It still shows me an error when there's no default date selected. Can you share a screenshot of the datepicker in the selected state?

Here's what it looks like for me without a default date selected.
<img width="844" alt="Screen Shot 2021-07-29 at 8 22 52 PM" src="https://user-images.githubusercontent.com/30255708/127514431-af1d0930-e518-45c3-bcd8-a564cb2aae93.png">

**Comment by somangshu** [comment]
@vibhandikyash can you let us know if you are seeing the error here?

**Comment by vibhandikyash** [comment]
I tried to reproduce the same in the release branch on local env it is not reproducible. on the live env we are facing this issue. 

![image.png](https://images.zenhubusercontent.com/60a239a9e26ae03e618fbc13/f7b33157-f5d0-41c5-a497-6fb6637f6cce)

**Comment by vivekverma2312** [comment]
I am able to repro the issue on prod but it's working fine on release.
Prod:
<img width="1779" alt="Screenshot 2021-08-05 at 4 43 59 PM" src="https://user-images.githubusercontent.com/83569920/128341127-9fb0da54-c22d-4231-a113-b89b1d52da66.png">

Release:
<img width="1783" alt="Screenshot 2021-08-05 at 4 44 54 PM" src="https://user-images.githubusercontent.com/83569920/128341214-d781c770-3b19-4fc7-9ddb-823f8a82ad7a.png">

**Comment by somangshu** [comment]
@vivekverma2312 closing this and tagging QA, lets verify this with the next release
