### ISSUE TITLE
[Bug]MultiSelect Widget Validation

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#6126]
## Description

Using a random key for the Options array rather than the accepted `label` and `value` key doesn't throw any error.

Also, it accepts more than two keys as shown in the second image

<img width="1007" alt="Screenshot 2021-07-26 at 08 45 26" src="https://user-images.githubusercontent.com/31691737/126952441-637f4b97-4677-4654-83fa-dbd83ad99825.png">

<img width="694" alt="Screenshot 2021-07-26 at 08 49 55" src="https://user-images.githubusercontent.com/31691737/126952918-2fa3c6f6-d57c-456d-9fe2-57aa7030ddbb.png">

**Comment by somangshu** [comment]
@Tooluloope @riodeuno is this issue fixed. Can we close this issues?

**Comment by vivekverma2312** [comment]
This issue is already fixed in PR #5228 and merged in release.
