### ISSUE TITLE
[Bug] Cloned widgets also get highlighted when the original widgets get highlighted and vice versa

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#6127]
## Description

When a page with widgets has been cloned, Selecting a widget from the cloned page also highlights the widget from the original page and vice versa.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/498b724a38dc4fafbf13860789670bc4-00001.gif)](https://www.loom.com/share/498b724a38dc4fafbf13860789670bc4)

### Steps to reproduce the behaviour:

1. create a page with a widget.
2. clone the page.
3. select the widget from original page.
4. corresponding widget from cloned page as well the selected widget will get highlighted.

### Important Details

- Version: Cloud / Self-Hosted 
- OS: MacOSX
- Browser: chrome
- Environment: release

**Comment by zhanghuishun** [comment]
Hi, I am new to appsmith and would like to take this issue, I have already built it locally, may I get some information to start?

**Comment by marks0351** [comment]
@zhanghuishun Hi, thanks for volunteering.

The issue arises because widgets in a Page and its Clone(you can check the loom video to clone) have same identifiers. to fix this we need to stop showing widgets that do not belong to the current editing/selected page as selected on the left pane(entity explorer).

**Comment by zhanghuishun** [comment]
Sorry, it’s the first time I came into contact with TypeScript, and it is a bit difficult for me to understand it. May I cancel the arrangement?

**Comment by Nikhil-Nandagopal** [comment]
@zhanghuishun sure no problem! Thanks for giving it a shot :)

**Comment by ramsaptami** [comment]
Widget selected on cloned page is selected even on the original page and vice versa
https://www.loom.com/share/90f31bd6d84a46c8b45054a8652718ab
