### ISSUE TITLE
[BUG]Web Page Testing Reports

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#614]
1. Analyzed https://app.appsmith.com/ on pagelocity. Report:
https://pagelocity.com/analyzer?url=https%3A%2F%2Fapp.appsmith.com%2F

2. Report from webpage test:
https://www.webpagetest.org/result/200920_RN_93e97d597976edc46517739916f4cbdf/

3. Report from GTMetrix
https://gtmetrix.com/reports/app.appsmith.com/atgMeT5f

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 runs on applications page don't seem useful because they are measuring user in logged out state so it's getting redirected to login page
