### ISSUE TITLE
[Bug] Appsmith when POST -ing to AppScript endpoints GAS returns with 405

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#6141]
## Description

While making a POST call to Appscript endpoint 405 is returned

### Steps to reproduce the behavior:

1. Go to API pane
2. Create a POST request to Appscript
3. Error 405 

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by GreenFlux** [comment]
@Nikhil-Nandagopal is this fixed now? There's a similar issue here that's still open. 
https://github.com/appsmithorg/appsmith/issues/25334

**Comment by Nikhil-Nandagopal** [comment]
@GreenFlux we'll pick it up along with that since the issue seems to be the same
