### ISSUE TITLE
[Bug] Tooltip is not showing upon hovering over Scroll content Widget: Form/Tabs.

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#6148]
## Description

Tooltip is not showing upon hovering over Scroll content
**Widget: Form/Tabs.**

### Steps to reproduce the behavior:

1. Go to link http://rc.app.appsmith.com/user/login
2. Login into Appsmith through your user credentials.
3. Go to the widget screen by clicking on the Add icon of widgets  
4. Drag and drop the form/Tabs widget
5. Open property pane of form/Tabs widget
6. Hover over Scroll content
7. Tooltip is not showing for scroll content.

### Important Details

- Version: [Cloud]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [release/frozen]

### Video Link.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/acb6ee8d77274b9fbc2c2217c9b44d08-00001.gif)](https://www.loom.com/share/acb6ee8d77274b9fbc2c2217c9b44d08)
###Screenshot.
https://www.screencast.com/t/IJWxPV8AiD

**Comment by somangshu** [comment]
add helper text for scroll content in form / tabs widget

helper: `Enables scrolling for content inside the widget`

**Comment by Cool-Runningz** [comment]
I am interested in working on this if it is still available. Thank you!

**Comment by areyabhishek** [comment]
I've assigned this to you @Cool-Runningz!

**Comment by Cool-Runningz** [comment]
Thank you @areyabhishek! I will reach back out if I have further questions.

**Comment by Cool-Runningz** [comment]
@areyabhishek Do we want the tooltip to be added for all the widgets that contain the scroll content label? Or just the Form and Tab widgets? I noticed that the tooltip is also not visible for widgets other a lot of other widgets so I wanted to confirm.

**Comment by Nikhil-Nandagopal** [comment]
@Cool-Runningz please do add this for all widgets. That would be great :)

**Comment by Cool-Runningz** [comment]
@Nikhil-Nandagopal Thank you for clarifying! I figured that might be the case so the work for that has been completed in the linked PR above.
