### ISSUE TITLE
[Bug]Selection Widget - Property Pane - “Filterable” functionality is not working properly while using JS button and type false.

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#6149]
## Description

Selection Widget - Property Pane - “Filterable” functionality is not working properly while using JS button and type false.

### Steps to reproduce the behaviour:

1. Go to link http://rc.app.appsmith.com/user/login 
2. Login into Appsmith through your user credentials.
3. Go to the widget screen by clicking on the Add icon of widgets  
4. Drag and drop the Selection  widget
5. Go to the Widget property
6. Enable the Filterable JS
7. Enter the value false and then publish the widget
8. Selection widget still shows the Filterable option. Issue

### Important Details

- Version: [Cloud]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [Release/Frozen]
### video.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/06e1ccf8daa1431baf4b2692a2d2b7bd-00001.gif)](https://www.loom.com/share/06e1ccf8daa1431baf4b2692a2d2b7bd)
### Screenshot.
https://www.screencast.com/t/5agbD3BE

**Comment by Nikhil-Nandagopal** [comment]
@arslanhaiderbuttar please tag the issues with the correct labels

**Comment by Tooluloope** [comment]
@somangshu , I think I've fixed this since

**Comment by Tooluloope** [comment]
@arslanhaiderbuttar could you confirm this issue doesn't exist anymore

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope if you think it works, close it. It will get auto assigned as QA
