### ISSUE TITLE
Onboarding flow | The button on the first screen takes too long to load.

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#6151]
## Description

The button on the first screen after user onboarding flow takes a while to load. 
<img width="644" alt="Screenshot 2021-07-26 at 9 43 03 PM" src="https://user-images.githubusercontent.com/217911/127022796-4ec0c1ef-444f-45b8-8bb4-4c4482b9f9e6.png">

### Steps to reproduce the behaviour:

1. Go to dashboard
2. On the left side navigation, Press "Welcome tour"
3. Click "Let's go" on the new popup of our onboarding flow. 
4. Observe the loading time of the button.

**Comment by Rishabh-Rathod** [comment]
@hiteshjoshi  The reason for this according to the current implementation, a new DB "Super Updates DB" is created for users as soon as this page loads, and only after completion of that, we show the "Start Building" button as after that we route user to datasource showing the same DB "Super Updates DB" which was created.

**Comment by hiteshjoshi** [comment]
In that case, can we plan something like "Loading feedback"? Making sure user is aware that something meaningful is happening. 
@Debsourabh thoughts?
<img src="https://assets.website-files.com/5c7fdbdd4e3feeee8dd96dd2/5ce466e314028525b2c4f1a7_loading-page-delayed-loading-turbotax.gif" />

CC: @areyabhishek

**Comment by areyabhishek** [comment]
This makes sense. It'll tell the user why the delay exists.

**Comment by hiteshjoshi** [comment]
Ok closing this for now. The feedback loadings will be covered in design systems.
