### ISSUE TITLE
[Bug] Tooltip is not showing upon hovering over Filters and download Widget: Table

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#6152]
## Description

Tooltip is not showing upon hovering over Filters and download
**Widget: Table**

### Steps to reproduce the behaviour:

1. Go to link http://rc.app.appsmith.com/user/login
2. Login into Appsmith through your user credentials.
3. Go to the widget screen by clicking on the Add icon of widgets  
4. Drag and drop the table widget
5. Hover on Filters and download
6. Tooltip is not showing for Filters and Download

### Important Details

- Version: [Cloud]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [Release/Frozen]
### video
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8040a28dc01f47d4b5b6d71746fa7842-00001.gif)](https://www.loom.com/share/8040a28dc01f47d4b5b6d71746fa7842)
### Screenshot
https://www.screencast.com/t/XWSsvPYNWjP

**Comment by somangshu** [comment]
design has updated, the row height option does not exist anymore
