### ISSUE TITLE
[Task] Onboarding flow | Wrong gif on welcome tour window. 

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#6153]
## Change the gif on welcome tour.
- Present GIF of "New Query" needs to be updated to match the current Orange buttons.

<img width="291" alt="Screenshot 2021-07-26 at 9 48 54 PM" src="https://user-images.githubusercontent.com/217911/127023549-530cc734-f105-4c43-9eba-84a567932374.png">

**Comment by albinAppsmith** [comment]
<img width="699" alt="Screenshot 2021-07-27 at 11 06 12 AM" src="https://user-images.githubusercontent.com/87797149/127101336-53abe083-7af7-4f49-a106-1216ea6dd802.png">

* "What we build" screen also has the same green color scheme which also should be updated
