### ISSUE TITLE
Onboarding flow | No end button on welcome tour window. 

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#6155]
## Description

The welcome tour window should allow user to end tour at any point. End top is on the top right which makes it really hard for someone to figure out how to end the tour.
<img width="1439" alt="Screenshot 2021-07-26 at 10 10 45 PM" src="https://user-images.githubusercontent.com/217911/127026596-bcde1171-c9da-461b-b39e-ea97704a1754.png">

**Comment by Rishabh-Rathod** [comment]
The PR to make changes was already merged. Hence, closing this issue.
