### ISSUE TITLE
[Bug] Evaluated property pane values goes out of the evaluated property field 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6159]
## Description
Release Frozen - It is observed that the evaluated property pane values goes out of the evaluated value field for few of the widgets

Expected Result:
Evaluated values should be clearly visible within evaluated field 

Issues occurs in the below following widgets following 

1.Button Widget - Button Style JS - Expected Data Type

<img width="1680" alt="Screenshot 2021-07-27 at 8 30 58 AM" src="https://user-images.githubusercontent.com/35128442/127088767-16d96746-a132-40dc-8136-23a882fee7b3.png">

2. Select widget - Options - Expected Data Type

<img width="1680" alt="Screenshot 2021-07-27 at 8 35 03 AM" src="https://user-images.githubusercontent.com/35128442/127089001-f6a85e76-5761-43d7-9ce8-1e39d7fffa4d.png">

3. Chart Widget - Chart Type - Expected Data Type

<img width="1680" alt="Screenshot 2021-07-27 at 1 03 18 PM" src="https://user-images.githubusercontent.com/35128442/127115089-02ae29bd-eb4f-427a-ba0c-dfa736bd0286.png">

4.Radio Widget - Options - Expected Data Type

<img width="1680" alt="Screenshot 2021-07-27 at 1 12 52 PM" src="https://user-images.githubusercontent.com/35128442/127115923-cb7cc8db-9f57-49e4-8961-d86f696fe82f.png">

### Important Details

- Version: [11.3]
- OS: [MacOS Big Sur ]
- Browser [chrome, safari]
- Environment [release Frozen, Production ]

**Comment by somangshu** [comment]
@YogeshJayaseelan is this fixed with the new validation structure changes. Let's close it in that case.

**Comment by rahulramesha** [comment]
@YogeshJayaseelan This seems to be fixed in release, could you please verify

**Comment by YogeshJayaseelan** [comment]
@rahulramesha Verified this in release and the expected data type values are properly displayed.
