### ISSUE TITLE
[Bug]The video is not displayed in the Omni bar for a few of the widgets which is present in the official docs 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6161]
## Description

[What happened] The video is not displayed in the Omni bar for a few of the widgets which is present in the official docs but not in the Omni bar

### Steps to reproduce the behaviour:

The widget list which doesn't display the video when the user searches for the widget in the Omni bar:

Select widget-> not able to search in Omni bar
Filepicker widget->no video
Image widget->no video
Input widget->no video
List widget->no video
Map widget->no video
Modal widget->no video
Radio widget->no video
Rich text editor->no video
Switch widget->no video
tab widget->no video
Video Widget->no video

To set appsmith on docker and Heroku When the user searched for it in Omni bar the video is not displayed in Omni bar but it is present in Docs

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser  chrome
- Environment  release

**Comment by pranavkanade** [comment]
There are two type of youtube we are using for embedding. Will add another regex to match the missed link format.
