### ISSUE TITLE
[Bug] If I have a URL in the text widget, then clicking the URL just takes me to the URL in the same tab

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6163]
## Description: If accidentally I click on the url it takes me to that URL on same tab.

Expected Behaviour: On click we should ask the user to confirm if they’d like to visit the URL and then open the URL in a new tab.

### Important Details

- Version: Cloud 
- OS: e.g.MacOSX
- Browser chrome
- Environment: production

**Comment by somangshu** [comment]
@vivekverma2312 do we really need to get the confirmation from the user for this? Do you see any flaw otherwise
