### ISSUE TITLE
[BUG] You can be logged in and see the sign up page at the same time

### ISSUE THREAD

**Issue by akbansa** [appsmithorg/appsmith#617]
## Description

This is session related issue. I reported earlier for the login page.

### Steps to reproduce the behavior:
1. Login into your appsmith account
2. Open https://app.appsmith.com/user/signup in another tab
3. You can see the sign-up page, not redirected to your logged-in state.

### Important Details
 - Version: Cloud
 - OS: MacOSX
 - Browser: chrome

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit seems like we're not re-directing correctly

**Comment by Nikhil-Nandagopal** [comment]
Also duplicate of #616 so closing this in favour of that being filed 3 minutes earlier 😅
