### ISSUE TITLE
[Bug] User is not able to expand the item 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6178]
Steps to reproduce:
1) Add a list widget
2) Add spacing between the list widget
3) Try to expand the list widget item

Observation:
It is observed that the list widget item does not expand and make it difficult to add a widget into the list item

Expectation:
It is expected that the item inside the widget must gets expanded

Video
https://www.loom.com/share/86d2c4f6aa3849b5b6637609e67e551f

**Comment by somangshu** [comment]
@jsartisan is this a desirable behaviour. Should we fix this?
