### ISSUE TITLE
[BUG] While hovering over the AppSmith tab, it displays the same workflow that was last accessed by the user

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#618]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login
2. Go to Organization settings and on the tab while hovering over it displays 'Organization Settings | AppSmith' or go to application and it displays 'Application | AppSmith'.
3. Logout

Actual Result: It displays 'Organization Settings | AppSmith' or 'Application | AppSmith'' or something else, whichever workflow was last accessed by the user.
Expected Result : It should show 'Login or SignUp | AppSmith'

Attachment : https://drive.google.com/drive/folders/1JR3WzAlJX3dskIrA8smUmwkzjpXc4V2A?usp=sharing

**Comment by areyabhishek** [comment]
Closing this issue because it's been fixed. Thanks @Saket2!
