### ISSUE TITLE
[Bug]The authentication type is missing in the Active tab for the Authenticated API when the authentication type is none

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6180]
## Description

[What happened] When Authenticated API data source is created and the Authentication type is none, Inside active tab-show more section "Authentication Type: " is not displayed

### Steps to reproduce the behaviour:

1. Go to 'Datasource create a new tab
2. Click on Authenticated API
3. Add the URL  and select Authenticate type as None
4. Now click on save and go to the Active tab
5. Click on Show more link
6. Verify the display of the authenticated type
![image](https://user-images.githubusercontent.com/45958978/127111515-c12b7a6f-3604-4d18-b836-a5a31da0c0c2.png)

### Important Details

- Version: [Cloud ]
- OS: [.MacOSX]
- Browser [safari]
- Environment [Release frozen]

**Comment by RakshaKShetty** [comment]
#6017

**Comment by hetunandu** [comment]
Fixed with #6017
