### ISSUE TITLE
[Bug]The header should not be displayed in the Active tab for the Authenticated API when there is no header

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6181]
## Description

[What happened]The header should not be displayed in the Active tab for the Authenticated API when there is no header

### Steps to reproduce the behaviour:

1.Go to 'Datasource create a new tab
2.Click on Authenticated API
3.Add the URL and select Authenticate type as None don't add any header
4.Now click on save and go to the Active tab
5.Click on Show more link
6.Verify the display 
![image](https://user-images.githubusercontent.com/45958978/127114457-ffdd9569-4f2e-4085-9cd7-26242479b1f2.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [e safari]
- Environment [Release frozen]

**Comment by RakshaKShetty** [comment]
#6017

**Comment by BhandarkarPawan** [comment]
Can I work on this?

**Comment by pranavkanade** [comment]
@BhandarkarPawan  sure, go for it!
