### ISSUE TITLE
[Bug] Colour selector must exit after pressing on the Enter or Tab key

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6193]
## Description
Colour selector on widgets to be more keyboard friendly and should exit when user hits **Enter** or **Tab** key. Currently user needs to move cursor to exit the default colour selection panel. In the meanwhile if user users **Tab** to move control then information is overlapped and input fields are blocked

### Steps to reproduce the behaviour:
1. Enter colour name/code into input field
2. Hit **Enter** - colour selction panel should exit but remains on screen
3. Press **Tab** - colour selection panel should exit but causes information text to overlap and input fields being blocked

### Important Details

- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: RC and Production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bec2756012f349b4b3ecf382ffe47052-00001.gif)](https://www.loom.com/share/bec2756012f349b4b3ecf382ffe47052)

**Comment by areyabhishek** [comment]
@ramsaptami Are you a pro user of keyboard shortcuts? Wondering if you can do a thorough scan of everywhere keyboard shortcuts don't work but should work.

We've ignored the keyboard experience, so thanks for bringing it up. 

Could you group all the issues in a single task so that we can work on them?

**Comment by ramsaptami** [comment]
I can look into this. I've come across a few keyboard shortcuts I've made a list already of so I'll continue adding to it.

**Comment by ramsaptami** [comment]
Tab function works but unable to select colour from the colour picker

**Comment by somangshu** [comment]
The tab key implementation is only for moving from the input field and closing the colour picker at the right time. We will need to create another issue for what you have proposed here

**Comment by ramsaptami** [comment]
@somangshu the normal picker where we select colour isn't working is what I meant :) seems to be broken on release

**Comment by somangshu** [comment]
@ramsaptami Can you please share a video to show what is not exactly working?

**Comment by ramsaptami** [comment]
https://www.loom.com/share/e3bc8c2f52744a64bd9ac15d78908664

**Comment by somangshu** [comment]
@ramsaptami please be sure to create a new issue out of this.

**Comment by ramsaptami** [comment]
Done @somangshu. Raised #6922 for this
