### ISSUE TITLE
[Feature] Encrypt Authorisation headers and provide an option for a hardcoded bearer token

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6201]
## Summary

A user thinks it would be a good idea to encrypt and store all authorization headers for added security.
We could also provide an explicit section for hardcoding a bearer token which can be stored and retrieved in an encrypted format

**Comment by sumitsum** [comment]
Update: we have an encoded bearer token based auth option in API datasource now.

**Comment by nidhi-nair** [comment]
Closing this per Sumit's comment above. Please re-open the issue with more information if the currently implemented feature does not meet the expected criteria.
