### ISSUE TITLE
[BUG] Submit button shouldn't be enabled until organization name is typed.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#621]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Issue 1: Submit button shouldn't be enabled until organization name is typed
Issue 2: Able to add organizations with same name again and again

Steps to replicate:
1.Login
2. Create Organization

Expected Result : 
1. Submit button should only be enabled when user enters some text.
2. If an organization name is already chosen, user should be notified about the same.

<img width="1731" alt="Screen Shot 2020-09-20 at 3 49 24 PM" src="https://user-images.githubusercontent.com/49346036/93709085-28007080-fb59-11ea-820d-91bc4bdbf880.png">

**Comment by satbir121** [comment]
We are using `redux-form` library to create forms.
This issue can be resolved by declaring a validator for `TextField` used inside `CreateOrganizationForm.tsx`. This validator will automatically set the state of the form. And that state can be then used to set the disabled state of Submit button.

[Follow this link for an example](https://stackoverflow.com/questions/43768535/redux-form-how-to-disable-submit-button-if-at-least-one-field-is-not-valid)
