### ISSUE TITLE
[Enhancement] Ability to set the y-axis adaptive based on the data in Chart widget

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#6210]
The chart widget today doesn't have any way to make the y-axis adaptive based on the data.
A toggle that makes the y-axis adaptive would solve this.

https://www.fusioncharts.com/dev/chart-guide/chart-configurations/chart-limits#set-y-axis-minimum-value

**Comment by areyabhishek** [comment]
This is how it looks in Google sheets 

![Uploading Screen Shot 2021-07-28 at 3.07.35 PM.png…]()

**Comment by somangshu** [comment]
@areyabhishek image is not visible here
