### ISSUE TITLE
[Feature] Indicate active datasource in the datasources pane

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#6215]
## Summary

When datasources share the same url, it is difficult to make out which datasource I am currently using. We should sort the list to show the active one at the top and Highlight it as well may be.

In the current example, I'm using datasource 5 which is not visibly indicated in any form.

<img width="1285" alt="Screenshot 2021-07-28 at 12 44 05 PM" src="https://user-images.githubusercontent.com/5298848/127280055-5aff7e0e-7a4f-46d3-9c8c-240ad57b115a.png">

**Comment by nidhi-nair** [comment]
Tagged as QA incorrectly, removing the tag till this is fixed.

**Comment by rohan-arthur** [comment]
_As a user, when I am working on a query, I should know which datasource the query is derived from so that I can differentiate between queries using similar URLs_
