### ISSUE TITLE
[Feature] Enable Client Side Timer for all Queries & JS

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#6217]
## Summary

Add a new Timer widget to execute triggers on a certain frequency

## Motivation

Currently, it is not possible to run triggers (call queries, functions, APIs) on a schedule. A Timer widget would be very handy. It will help users build auto-updating, real-time internal tools. On a timer event, we can trigger JS bindings.

## Additional Context

Visual Basic (6 and .Net) had a Timer widget which you can drop on the Canvas/form and then set properties. It was very useful to build timers.

![image](https://user-images.githubusercontent.com/800578/127293334-b5c106bc-8ee0-49b6-a74e-349e0ce82b45.png)

![image](https://user-images.githubusercontent.com/800578/127293437-46385313-0603-4ec3-95b0-d37847f70735.png)

![image](https://user-images.githubusercontent.com/800578/127293486-17753bba-18d2-4dee-991b-5d674eb4b0a6.png)

![image](https://user-images.githubusercontent.com/800578/127293512-4cf76c79-2826-4432-a181-e6d72a70e07e.png)

**Comment by ajinkyakulkarni** [comment]
Related feature https://github.com/appsmithorg/appsmith/issues/3312

**Comment by somangshu** [comment]
We also have #738 and #1950 related to similar functionality. We have disabled `setTimeout` like functions due to security reason. 

The above mentioned issues are not prioritised and needs discussion for the same.

**Comment by Nikhil-Nandagopal** [comment]
If it doesn't have a UI, I don't think this should be a widget. A protected setTimeout seems to be the right way to achieve this.

**Comment by ajinkyakulkarni** [comment]
If it is a widget, we can add multiple timers with different intervals. We can also bind `enabled` property of a timer to some JS condition.  If we don't go with the widget approach, will we be supporting just one timer or come up with a different way to support multiple timers?

**Comment by ajinkyakulkarni** [comment]
If not a widget, should this be a section on the settings page (a section of timers and their properties/binding)?

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni this could simply be writing a JS function in the editor and marking it onPageLoad as
```
export default {
  run: () => {
     setSafeTimeout(() => {
        API1.run();
     }, 1000);
  }
}
```

Then you can do multiple timers, functions, basically whatever the user wants will be possible. But we need to get the JS Editor experience right and enable this safe timeout functionality

**Comment by PaoloConte** [comment]
+1 on this, I'm building dashboards to monitor remote plants, this would be helpful to always show fresh data from the API, the user cannot keep clicking on refresh ;)

**Comment by somangshu** [comment]
@PaoloConte thank for the comment here, This will help us in prioritising the issue

**Comment by hetunandu** [comment]
closing in favour of #3312

**Comment by areyabhishek** [comment]
Reopening this because this issue isn't solved by #3312

**Comment by hetunandu** [comment]
@areyabhishek this issue can be closed once we have all the parts ready. The usage would be to use setInterval in a JS function which is run on page load.

**Comment by cokoghenun** [comment]
How about we make this built-in, in the entity settings page. We already have a checkbox to run queries on page load. We could add one for polling (as a user, I'll expect it to be here)

![Screenshot 2021-11-16 at 12 06 19 PM](https://user-images.githubusercontent.com/17744578/141974410-8b9f631d-431b-4f43-a0ed-753dc48951b7.png)

**Comment by hetunandu** [comment]
> How about we make this built-in, in the entity settings page. We already have a checkbox to run queries on page load. We could add one for polling (as a user, I'll expect it to be here)
> 
> ![Screenshot 2021-11-16 at 12 06 19 PM](https://user-images.githubusercontent.com/17744578/141974410-8b9f631d-431b-4f43-a0ed-753dc48951b7.png)

We thought about this but found it pretty limitting. Incase you want some complex logic to run at a fixed interval, it would not be possible as this feature could only run that single action. Adding it as a function gives it much more flexibility of usage

**Comment by cokoghenun** [comment]
Not sure what you mean by "some complex logic". The only logic here is to poll the API right?

**Comment by hetunandu** [comment]
> Not sure what you mean by "some complex logic". The only logic here is to poll the API right?

you could have some if statements to decide if you want to poll the api. You could want to capture some data from some widgets or other responses and pass that as params to the api you are polling. Many things can be possible

**Comment by cokoghenun** [comment]
Hmm, you're right. My thought initially was, we could have a simple form in the UI for this (because requests I've seen around this are simple get requests), then also add a note or something that if the user wants more control, they could use setInterval/clearInterval

**Comment by areyabhishek** [comment]
Can we do both? Exposing it in the API pane will enable discovery. Discovering this function is difficult unless you try it or read the documentation. While it's easy to discover the simple option in the API pane and we can add a tooltip explaining that they can also use a function.

**Comment by danciaclara** [comment]
A user requested this feature on Discord - Usecase below
`something a bit of a normal timer which i can start, stop/pause, resume and once stoped get the timeElapsed() to get the time series data fetched from the TSDB (influx) via an API call.`

https://discord.com/channels/725602949748752515/760761686549463060/1004025639139037204
