### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DevSnap** [appsmithorg/appsmith#6218]
## Description

When you try to rename a widget, appsmith renames the text of all widgets with the same value.

### Steps to reproduce the behaviour:

1. Create a series of widgets whose text is equal to the name of a widget.
![image](https://user-images.githubusercontent.com/39520353/127296279-a494dcf9-1802-4e50-9d61-1a96fd650ae7.png)
2. Rename the widget name.
![image](https://user-images.githubusercontent.com/39520353/127296479-73376492-5bac-4e7b-b094-5f761b2466f9.png)

### Important Details

- Version: Cloud
- OS: Windows
- Browser: Brave 1.27.108 (Chromium: 92.0.4515.107)
- Environment: production

**Comment by Nikhil-Nandagopal** [comment]
@DevSnap thank you for reporting this issue. We have this tracked here #5657
