### ISSUE TITLE
[BUG] Multiple issues(minor) on Team settings page

### ISSUE THREAD

**Issue by akbansa** [appsmithorg/appsmith#623]
## Description

Here are many issues on the team settings page which can be resolved in one go:
1. When I try to change a role and choose the same role as earlier one. It sends a post request to update details. Since you have all the data in front-end, you can save these requests.
2. No need to show email in name column. Since you can't add/change it.
3. A better way would be to show invite status (`Invited`, `Joined`) if you want to use the space efficiently.

**Comment by Saket2** [comment]
For 2 and 3, there is bug already filed.
2. https://github.com/appsmithorg/appsmith/issues/595
3. https://github.com/appsmithorg/appsmith/issues/622

**Comment by Nikhil-Nandagopal** [comment]
@akbansa Thanks for the feedback, tagging these as improvements!
