### ISSUE TITLE
[Bug]-[348]:Slash command dropdown overflow

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6230]
## Description The slash comment should overflow below the field out of the property pane and should not hide the field inside the property pane.

[What happened]

 The dropdown overlaps on the property pane in the below use cases:

- [ ] Slash commands menu opens up on top when there is no enough space at the bottom.
- [ ] when the code is written beyond the 2nd line the dropdown opens in the top
- [ ] When the input box is very wide the dropdown opens up in the random place

Widgets | Property pane fields where the overlap happens
-- | --
Table widget |  
  | Default Search Text
  | Default Selected Row
  | Actions
  | onRowSelected
  | onPageChange
  | onPageSizeChange
  | onSearchTextChanged
Button |  
  | Visible
  | Google Recaptcha Key
  | Actions
chart |  
  | Series Title
  | Series Data
  | Axis
  | Actions
checkbox |  
  | Visible
  | Disabled
  | Actions
Container |  
  | Background Color
  | Visible
Datepicker |  
  | Required
  | Visible
  | Disabled
  | Min Date
  | Max Date
  | Actions
Divider |  
  | Thickness (px)
FilePicker |  
  | Allowed File Types
  | Required
  | Visible
  | Disable
  | Actions
Iframe |  
  | onMessageReceived
  | Border Opacity (%)
  | Border Width (px)
  | nURLChanged(The dropdown is not displayed correct)
  | onMessageReceived(The dropdown is not displayed correct)
Image |  
  | Max Zoom Level
  | Object Fit
  | Actions
Input |  
  | Regex
  | Error Message
  | Required
  | Visible
  | Disable
  | Reset on submit
  | Actions
List |  
  | Item Spacing (px)
  | Visible
  | Actions
Map |  
  | Visible
  | Actions
menu |  
  | Visible
  | Compact
  | Actions
radio |  
  | Options
  | Default Selected Value
  | Required
  | Visible
  | Disabled
  | Actions
rating |  
  | Tooltips
  | Allow half stars
  | Visible
  | Disabled
  | Actions
Rich text editor |  
  | Default text
  | Required
  | Visible
  | Disabled
  | Actions
select dropdown |  
  | Options
  | Default Option
  | Filterable
  | Required
  | Visible
  | Disabled
  | Actions
switch |  
  | Default Selected
  | Visible
  | Disabled
  | Actions
tab |  
  | Visible
  | Actions
Text |  
  | Text Color
  | Font Style
  | Text Align
Video |  
  | Visible
  | Actions

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser chrome
- Environment [production]

**Comment by areyabhishek** [comment]
@arunvjn Just saw this issue. Are you looking into this?

**Comment by arunvjn** [comment]
@areyabhishek What's mentioned here is the positioning of the slash commands when there is no space at the bottom. 
Today, it works just like autocomplete and opens up on the top when there is no space at the bottom and is pinned to the cursor position. Not sure if there is something to be fixed here.

**Comment by Nikhil-Nandagopal** [comment]
@arunvjn It's cutting half the field. If it has to sho above, can it show complete above the field?

**Comment by areyabhishek** [comment]
It's not easily reproducible, but sometimes the slash command covers the input field.

**Comment by satbir121** [comment]
**Steps To Reproduce**

1. Add a Button Widget
2. Open the `General Section` in Property Pane so that the `Events Section` pushes to bottom.
3. Type `/` in the onClick JS.

Observations:
1. The dropdown overlaps with the `onClick` field. It cuts the onClick field in half. This is not expected. The dropdown should pop up above `onClick` field entirely.
2. Dropdown overlaps with Property Pane. This is expected.

**Reference:**
<img width="1437" alt="Screenshot 2022-08-24 at 1 25 57 PM" src="https://user-images.githubusercontent.com/39981226/186364389-c0eb54b0-667a-47ef-b7d1-b9c737c5a135.png">
