### ISSUE TITLE
[Bug]The slash command dropdown overlaps with the evaluated card when the property pane is overlapping with the entity pane 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6232]
## Description: The slash command dropdown overlaps with the evaluated card when the property pane is overlapping with the entity pane 

[What happened]

### Steps to reproduce the behavior:

1. Drag and drop the widget
2. Drag the property pane and place it on the entity pane
3. Click on the slash command 
4. verify the display of the opened dropdown

![image](https://user-images.githubusercontent.com/45958978/127431735-4acfbec8-a3b5-4140-86e6-db68200e7265.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [chrome
- Environment [production]

**Comment by Nikhil-Nandagopal** [comment]
Solved with docked property pane
