### ISSUE TITLE
[BUG] on iPad Air, Top line (black) isn't proper

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#625]
Browser Details: Safari 
Device Details: iPad Air (iOS 13.3.1)
Note: Tried on cloud.

Steps to replicate:
1. Login 

Actual Result: Observe that top line(black) ends abruptly.

Attachment: https://drive.google.com/drive/folders/1HTBn3g6yM8VkaLC4ZmgQazA_6ykDPjAA?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 closing this because appsmith does not currently support mobile / tablet devices yet 😄
