### ISSUE TITLE
[Bug]The older comments are missing on the canvas 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6266]
## Description

[What happened]The older comments are missing on the canvas but it is displayed in the comment section. if the user clicks on the older comments from the comment section the error is displayed in the console

### Steps to reproduce the behaviour:

![image](https://user-images.githubusercontent.com/45958978/127601190-5deb4585-2b32-45b7-8d89-4d4d35595ca1.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [Firefox]
- Environment [ release]

**Comment by nayan-rafiq** [comment]
@RakshaKShetty would you please test it again? We've deleted the older comments. Please check if it's still there.
