### ISSUE TITLE
[Bug] Default color for divider widget is bad, should be a softer grey

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#6272]
## Description

The default color used on the divider widget is heavy black that doesn't match with the UI, it should a softer grey like #C4C4C4 so the widget can be used without any config.

### Steps to reproduce the behaviour:

Drop divider widget onto the canvas, the default color is #000000

### Reference Images

![Image from iOS](https://user-images.githubusercontent.com/65771350/127621743-ac047baf-342f-4c9e-9eb7-b0fa964516ae.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/65771350/127621749-cb43efef-85d9-48a4-86d7-ee5823544fa8.jpg)

**Comment by somangshu** [comment]
@techbhavin we can use the grey from our theme, also lets check if `#C4C4C4` exists and use theat
