### ISSUE TITLE
[Bug] Multiple header are displayed to user when the header is added from the datasource 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6278]
Steps to reproduce :
1) Add an API
2) Save as data source
3) Add Header in the Datasource
4)Save the data source
5) Create an API from the data source
observe the header section

Observation:
It is observed that the data source header is being displayed to the user twice. 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7e23846f5cd7444bb201abbe10a45392-00001.gif)](https://www.loom.com/share/7e23846f5cd7444bb201abbe10a45392)

**Comment by sumitsum** [comment]
This seems like a UI issue.

**Comment by AmanAgarwal041** [comment]
Should this commit work for this issue [link](https://github.com/appsmithorg/appsmith/commit/cad35c753c0b93fc6dd0c77cdbc65b7a096b3ace) . If this works, will raise a PR for the same.
