### ISSUE TITLE
[BUG] Security Issue : Missing HTTP security headers

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#628]
<img width="1114" alt="Screen Shot 2020-09-20 at 6 20 58 PM" src="https://user-images.githubusercontent.com/49346036/93711712-12e20c80-fb6e-11ea-8fa4-81232955a126.png">

Please find the attached report.
[scan_report.pdf](https://github.com/appsmithorg/appsmith/files/5251661/scan_report.pdf)

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you verify this?

**Comment by Nikhil-Nandagopal** [comment]
Closing since we decided not to restrict these headers as it will restrict embedding appsmith
