### ISSUE TITLE
[Bug] Table column arrangement changes when column name is changed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6283]
## Description
When user renames column within mustache command inside **Table Data**, column arrangement within a table changes and the newly renamed column moves to the end instead. User has to manually move columns back into the original position. Where as when user renames column under **Column** in the **Property Pane**, renamed column remains in the original position.

### Expected Behaviour
Column arrangement needs to remain as the user initially designed, i.e. behaviour of renaming columns through Column and Table Data should be the same.

### Steps to reproduce the behaviour:
**When table is bound to a datasource**
        1. Drag and drop a table to canvas
        2. Bind table to datasource
        3. Edit column names within Table Data mustache code and observe columns move to the end of the table
        
**When table data is from an array**
        1. Drag and drop a table to canvas
        2. Observe column arrangement and array list on mock data
        3. Rename column name from within the Table Data and observe original column being split into two, (A) renamed column 
         (B) original column. Both these columns are moved to the end of the table. Any subsequent column renaming rearranges in 
          it's own pattern.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

https://www.loom.com/share/7b8efe3c5b5c4517a5fb9b30d116d5b3

**Comment by somangshu** [comment]
What is the expectation here @ramsaptami? The table widget is talking all keys as columns from the given object and, If the object is not appropriate should we consider the widget to be at fault?

It also seems related to #4990.

**Comment by ramsaptami** [comment]
Since user is allowed to rename columns from both **Table Data and Column in the Property Pane,** the behaviour is different for both. Renaming through **Column** retains column position in table where as renaming under **Table Data** shifts column.

**Comment by somangshu** [comment]
@ramsaptami Again my point here is that the table data once changed can be considered a different object. Consider an API call where data changes, Will then you not want the table data/view to refresh, While when you change them from the column name you are only mutating the data already available. That is what is happening here.

**Comment by ramsaptami** [comment]
Fair point, it makes sense that it's considered a different object. My point was to do with the column movement but I see what you mean by refreshing the view.

**Comment by somangshu** [comment]
Closing this for now
