### ISSUE TITLE
[Bug] User profile modal does not exit during on-boarding on clicking cursor away from window

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6289]
## Description
User profile modal does not exit on clicking away as it does in the rest of the application during user on-boarding.

### Steps to reproduce the behaviour:
1. Sign-up for Appsmith and you're taken through the on-boarding questionnaire
2. During this, click on user profile to open modal and click away on the canvas. Expected behaviour is for the modal to exit as it's handled in the rest of the application but it remains open.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami unfortunately this too is a quirk of using typeform and will be solved when we move to a native experience. Can't do much about it right now :/
