### ISSUE TITLE
[Feature] Include a prompt to highlight required user input during on-boarding

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6290]
## Summary
When user selects option 'Other' during on-boarding and clicks on Submit, no error or visual prompt is shown to indicate expected input.

## Motivation
Visual prompt/error highlight would help provide visual guide on what's expected to move further along on the on-boarding process rather than having the user pause to take a closer look.

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami this is part of typeform so unfortunately we don't control it today. We'll be moving to a more native approach in the future
