### ISSUE TITLE
[Bug] Filepicker Crashes with Large Files

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6297]
## Description

A user reported that the file picker crashes while uploading files > 10 mb. We triaged this is due to the file getting stored in the data tree.

The solution is to not load files > 5mb into the data tree from the file picker

**Comment by SatishGandham** [comment]
@vivekverma2312 
In this PR we are introducing a new file picker. Changes are internal, it should work like before. Filepickers added before this change should work without any issues.
