### ISSUE TITLE
[BUG] User with Developer access is able to invite others to the organization

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#630]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login with an administrator account (User A)
2. Invite a user with developer access (User B)
3. Login with User B's credentials and now see that User B is able to invite others to the organization.
Note: User B is unable to access the manage users page.

Expected Result: User B should not be able to invite others as developer can only edit and view applications.

<img width="201" alt="Screen Shot 2020-09-21 at 12 04 02 AM" src="https://user-images.githubusercontent.com/49346036/93719081-01b0f400-fb9e-11ea-88fc-8ba27aa637cd.png">

<img width="1792" alt="Administrator Account" src="https://user-images.githubusercontent.com/49346036/93719217-a6cbcc80-fb9e-11ea-9932-ca9b836fd64e.png">
<img width="1781" alt="Developer Account" src="https://user-images.githubusercontent.com/49346036/93719223-aaf7ea00-fb9e-11ea-83cb-92cef017c00b.png">

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 updating the bug to text for developers is wrong. We decided developers would have access to invite users too.
@areyabhishek please provide updated text to reflect difference between admins and developers

**Comment by mohanarpit** [comment]
@all-contributors Please add @areyabhishek for the incredible contribution of their ideas, design and funding.

**Comment by Nikhil-Nandagopal** [comment]
Closing this as developers can also invite other developers and viewers
