### ISSUE TITLE
[BUG] 'Schedule a call' feature doesn't work from the meeting invite

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#631]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Invite a user 
2. User receives an email from Appsmith
3. From the email, click on 'Schedule a call'

Actual Result: It throws an error.
Expected result: It should take the user to a page where a call can be scheduled.

Attachment: https://drive.google.com/drive/folders/1iWg1d2WMGT3nh9BzH_H1wvR5kefXbxBF?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 closing since this was fixed 5 days ago but not deployed
[Fix](https://github.com/appsmithorg/appsmith/commit/cac15f2cacbba579b122c385e4186d9cd231566d)
