### ISSUE TITLE
[Feature] Fusion Maps Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6314]
## Summary

A user wanted the option to be able to use the fusion maps feature of fusion chart

## Requirements
| Title | Desc | Comment |
| ------ | ----- | ----- |
| New widget | Create a new widget for [utilising](https://www.fusioncharts.com/dev/map-guide/setup) [fusion maps](https://www.fusioncharts.com/dev/map-guide/list-of-maps) | - |
| Map chart types | maps/world ;  maps/worldwithantarctica ; maps/europe ; maps/northamerica ; maps/southamerica ; maps/asia ; maps/oceania ; maps/africa | - | 
| Title | Title (label) for the map chart | - |
| Colour gradient base | We will give the colour picker control for selecting the base colour, With that base and the help of tinycolor package used before we will lighten the shade 3 times by 25% to create the final gradient color | - |
| Colour range | This will be fixed internally until custom config is selected | - |
| Data | Data for each required plot in map chart | - |
| Show Label | Show the label on hover or by default can be decided | - |
| onDataPointClick | Action to trigger on click of a data point | - |
| visible | JS convertible Toggle to decide if the chart is visible | - |
| Categorisation of property pane | General config will contain map chart type, Title, Visible, The rest will go under Map chart data | - |

## Out of scope

| Title | Desc | Comment |
| ------ | ----- | ----- |
| Map chart types | Custom | - | 
| On custom map chart selected | As soon as the custom map chart type is selected we take the input from the config object directly as `{type: string, dataSource: object<{chart: object<>, data: array<>, ... }>}, This is similar to the chart widget | - |

## Questions

| Title | Comment | 
| ---- | ------ | 
| Can we hide the scale on the bottom? | | 

## Figma Link for the icon
https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=1868%3A8285

[Implementation Reference](http://jsfiddle.net/fusioncharts/jjLnb9jt/)

**Comment by ravenxone** [comment]
Hi we have internal dashboard which depends heavily on this. Any ideas around tentative timeline?

**Comment by somangshu** [comment]
Hi @ravenxone 👋 , Thanks for commenting here. This helps us prfioritize the task at hand. We do not have any fixed priority for this feature. Let me take a while to define this and get an approx. timeline for release. Ill keep you posted here 🙂

**Comment by somangshu** [comment]
After check this out, I think we should introduce inside the same charts widget under a new configuration custom maps and let the user add the config object similar to how we allow for the custom charts

**Comment by Nikhil-Nandagopal** [comment]
@somangshu why not a separate widget for this? Charts together make sense because one chart can transform to another but maps probably have very different data from charts

**Comment by somangshu** [comment]
@Nikhil-Nandagopal why I said this is because the fusion maps is not per-say a map, Its still data analysis on a map, Which is similar to charts. The second thing is we keep getting requests like #5492 or #4437, My question is how to we address everything else. We already have a map widget, How does this stand different. I felt the logical boundary here is the fusionSDK and hence all related functionalities can be inside the same widget

**Comment by Nikhil-Nandagopal** [comment]
@somangshu is the question on the priority of the requests or whether they should be a single widget?
For priority, I would defer to 
- Effort
- Requests
- Alternatives

For whether it's a single widget I would defer to
- Is the underlying component the same
- Is the data required to render the same

**Comment by somangshu** [comment]
@Nikhil-Nandagopal one more question, What do you think we can call this widget?

**Comment by Nikhil-Nandagopal** [comment]
Map Chart Apparently! 😆 
https://www.google.com/search?q=chart+maps&oq=chart+maps&aqs=chrome..69i57j0i512l2j0i22i30l2j69i60l3.1287j0j4&sourceid=chrome&ie=UTF-8

**Comment by somangshu** [comment]
@momcilo-appsmith need an icon for this widget. Please help

**Comment by momcilo-appsmith** [comment]
You can find it here: https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=1868%3A8285

**Comment by dilippitchika** [comment]
Hi @ravenxone we have added this feature. Could you help us know if you still need this?
