### ISSUE TITLE
[Bug] Input Widget - Currency Type - User is allowed to type decimals on selecting 2 decimal selection when the currency integers are in 6 digits

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6317]
## Description
Release - It is observed that user is allowed to type 3 decimal on selecting 2 decimal selection when the currency integer is 6 in length 

Expected Result:
Selecting 2 decimals user should be allowed to type only 2 decimals 

### Steps to reproduce the behaviour:

1.Launch Appsmith app in the release environment 
2.Drag and Drop input widget 
3.Change the type to currency 
4.Select 2 decimal from decimal dropdown 
5.Choose any country 
6. Type 123456.435 and observe 

Videolink:
https://loom.com/share/e136a7d687ca4f159b95784e05388bdc

### Important Details

- Version: [11.3]
- OS: [e.g.MacOS]
- Browser [Chrome, safari]
- Environment [Release]

**Comment by somangshu** [comment]
It always one additional when changed dynamically. This will happen in edit mode only.

**Comment by vicky-primathon** [comment]
This issue is fixed here https://github.com/appsmithorg/appsmith/pull/5256
