### ISSUE TITLE
[Bug] Button widget: reCaptcha V2 - Does not re submit the api after the first click

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6324]
## Description

In the button widget, When recaptcha is enabled and set up, it is observed that the action does not take place post the first click, In case the api in `onClick` fails the user should be able to trigger this again. 

### Steps to reproduce the behaviour:

1. Set up button reCaptcha 
2. add and action/api call in the onClick event
3. Execute the action
4. Try to execute the action again

It is observed that after the first click the button does not trigger the even on subsequent clicks

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

**Comment by somangshu** [comment]
@vicky-primathon one of our user is facing this issue and needs help, Can you look into this at priority. I have created and application to reproduce the issue. Please check it out [here](https://app.appsmith.com/applications/60c855cb3535574772b645c0/pages/60c855cb3535574772b645c2)

**Comment by somangshu** [comment]
@vivekverma2312 can we test this on release post deployment on priority, Want to cherry pick this for the user.

**Comment by vivekverma2312** [comment]
@somangshu The issue is tested on release and it's working fine.
