### ISSUE TITLE
[Bug]-[3000]:Page must scroll with cursor movement

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6325]
## Summary
When user is editing a data source query and presses cursor to move to the next line, then page must scroll to show the line the cursor is on.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ab5df7ccfba94f7a9670de8178c3cb06-00001.gif)](https://www.loom.com/share/ab5df7ccfba94f7a9670de8178c3cb06)

**Comment by BhandarkarPawan** [comment]
I'd like to work on this. Can it be assigned?

**Comment by ramsaptami** [comment]
@BhandarkarPawan it's all yours. 
Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by Nikhil-Nandagopal** [comment]
This happens in the property pane as well so tagging it as design system

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 6000 |
| Effort (months)  | 1 |

**Comment by ginilpg** [comment]
Issue still persists with query pane and property pane. Need to prioritise this @kocharrahul7

**Comment by eco-monk** [comment]
Notes: 
Bottom tabs have been moved to design system now. Might need changes in design system for this.
For property pane, the content/style tabs on top is the overly that needs to be checked.

**Comment by royalpinto007** [comment]
Hello, can you please assign this issue to me?

**Comment by ramsaptami** [comment]
Hey @royalpinto007 , the fix here requires a minor design change so it would be best if you could connect with the team on this to help guide you through the changes. Our engineer @eco-monk can help you through this.

**Comment by royalpinto007** [comment]
Yes, it would be really great if the file due to which the design problem happens is mentioned. It would help me solve quickly.

**Comment by eco-monk** [comment]
Hey @royalpinto007, Thank you so much for your interest.!
I am afraid, this is not a straight css fix.

Because we generate the query pane though a configuration object. 
We'd need to ensure other pages are not affected when making this change.

Removing tag, I'd suggest you look for other issues tagged `Good first issue`.

**Comment by eco-monk** [comment]
Created a separate issue for property pane. #19293
