### ISSUE TITLE
[BUG] Password reset doesn't work

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#633]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Hit https://app.appsmith.com/
2. Click on Forgot Password
3. Enter Email ID and click on 'Reset'
4. From the received email, click on 'Reset Password'
5. Enter less than (or equal to) 5 characters in 'New Password' field.
6. click on 'Reset' button

Expected Result: 3 possibilities:
1. A message (Please provide a password with a minimum of 6 characters) which is displayed on the login screen, should be present even here.
2. An error message is thrown that minimum 6 characters are needed.
3. 'Reset' Works

Actual Result: None of the three in expected result happens and user is stuck wondering what went wrong.

Attachment: https://drive.google.com/drive/folders/1BxeYZthBTd1Ix-kKEojSMNJSRYcsb89t?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
Seems like a simple validation was missing here, lets just show the minimum characters error message as suggested

**Comment by gagandeepp** [comment]
please assign this to me

**Comment by Nikhil-Nandagopal** [comment]
@gagandeepp I've assigned the issue to you. Feel free to reach out if you have any trouble getting started!

**Comment by gagandeepp** [comment]
@Nikhil-Nandagopal  Unable to install sentry on win 10,please help!

**Comment by Nikhil-Nandagopal** [comment]
@gagandeepp not clear why do you need to install sentry?

**Comment by gagandeepp** [comment]
It is a part of package.json file

**Comment by hetunandu** [comment]
Hey @gagandeepp, were you able to resolve this? Let me know if you need help in solving this hiccup
