### ISSUE TITLE
[Bug]The "setup appsmith locally video"  is not present for docker and heroku  when we search in the omni bar

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6343]
## Description

[What happened]
Setup appsmith locally with Heroku and Docker video is not displayed in the Omni bar which is present in the official docs

### Steps to reproduce the behavior:
![image](https://user-images.githubusercontent.com/45958978/127952014-3f9c3b41-b60e-4f46-b295-4526a68e3af8.png)
![image](https://user-images.githubusercontent.com/45958978/127952046-c0178d26-1283-4554-a2a4-81a9218f7e9e.png)

### Important Details

- Version: [Cloud ]
- Browser chrome
- Environment release

**Comment by Nikhil-Nandagopal** [comment]
video and links are broken @pranavkanade
