### ISSUE TITLE
[Docs] Unable to access part2 of "Creating your First Page"

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#6344]
## Documentation Link 

https://docs.appsmith.com/tutorials/building-a-store-catalog-manager/part-1-creating-a-simple-view/creating-your-first-table#whats-next

## Describe the problem

link part2 points to https://app.gitbook.com/@appsmith/s/appsmith/~/drafts/-MNXsPmxVacsRbqB7S_f/v/v1.3/tutorial/part-2-creating-a-basic-form

## Describe the improvement

Above link is inaccessible. It should point to https://docs.appsmith.com/tutorials/building-a-store-catalog-manager/part-2-using-forms/creating-a-form

**Comment by Nikhil-Nandagopal** [comment]
Fixed it
