### ISSUE TITLE
[Feature] Wizard Form: multi-step form

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#6351]
## Summary
A multi-step form with the following features:
- Configuration for each step, for example
  - Fields and their layout
  - Title / subtitle of the section
- An indicator to indicate the current step
- Conditional flows, based on the user input the next step could be configured
- Optionally there could be an option for sub-steps as well, for example:
  - Step 1
    -  Step 1.a
    -  Step 1.b
  - Step 2
  
 Additionally it could also support linking to a google sheet for responses

## Motivation
Dealing with a lot of fields can be daunting for users. Breaking down into the process into small chunks results in a better user experience.

**Comment by somangshu** [comment]
This is already filled in #2519, can we close this issue?
