### ISSUE TITLE
[Bug]server responded 500 for the crud-page API in automation runs

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#6352]
Steps:

1.Create a DS need for your use case.[postgres in this case]
2.Then while creating a new page, when we tap on Generate New Page we are getting internal server issue.

PFA
<img width="1057" alt="Screenshot 2021-08-03 at 3 23 22 PM" src="https://user-images.githubusercontent.com/67676905/127996642-ef51e21f-3f1b-48ab-80d0-3407fab7de9c.png">

Also logs :

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
 URL: https://dev.appsmith.com/api/v1/pages/crud-page/61090b949f8bc421c86fadc9

**Comment by abhvsn** [comment]
@Rishabh-Rathod I have pushed a fix for this. If everything is working fine on release we can close this issue.

**Comment by abhvsn** [comment]
Closing this as TC is passing on release
