### ISSUE TITLE
[Bug] Button Widget - Evaluated value is 'undefined' for Button style JS

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6358]
## Description
Release frozen - It is observed that evaluated value is 'undefined' for button style JS

Expected Result:
Evaluated value should display the actual evaluated value 

### Steps to reproduce the behaviour:

1. Launch App smith app in the release frozen environment 
2. Drag and Drop button widget 
3. Click on button style JS and observe the evaluated value 

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [Chrome, Safari]
- Environment [release,Release frozen]

1) Button widget - Button style JS
<img width="1680" alt="Screenshot 2021-08-03 at 5 56 13 PM" src="https://user-images.githubusercontent.com/35128442/128016689-1be175c3-ad9c-4854-98cc-6b1cc66c7f15.png">

2) List widget - Zoom JS
<img width="1680" alt="Screenshot 2021-08-04 at 2 14 22 PM" src="https://user-images.githubusercontent.com/35128442/128151281-a0f55f67-df9f-4920-9d10-a11163e71a50.png">

**Comment by somangshu** [comment]
@ajinkyakulkarni we need your help here, This is not related to the widget validation changes and exists from before.

@YogeshJayaseelan can you please attach a screenshot from prod as well?

**Comment by YogeshJayaseelan** [comment]
@somangshu @ajinkyakulkarni Adding screenshot for Prod 

1. button widget - Button style JS
<img width="1680" alt="Screenshot 2021-08-04 at 2 17 47 PM" src="https://user-images.githubusercontent.com/35128442/128151996-8e84621e-c14f-4c59-92dc-43be46aa5b9f.png">

2.List widget - Image - Zoom Js
<img width="1680" alt="Screenshot 2021-08-04 at 2 19 19 PM" src="https://user-images.githubusercontent.com/35128442/128151912-e8320968-c16f-4265-8349-f1c138042125.png">
