### ISSUE TITLE
[Bug] App URL (for sharing) does not update while exporting apps into different organisations

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#6362]
## Description

While importing applications into the organisation, the URL that's used to share isn't updating. 

Loom Recording: https://www.loom.com/share/7040b3d18e1c4e78a93c1ec299012d39

### Steps to reproduce the behaviour:

1. Export an app from the organisation
2. Import to a new organisation
3. Try sharing the app using a URL
4. It still shows the URL of the old app

### Important Details

- Version: Cloud
- OS: MacOSX
- Browser chrome
- Environment: production

**Comment by Nikhil-Nandagopal** [comment]
@abhvsn can we please fix this?

**Comment by abhvsn** [comment]
I'll take this on priority

**Comment by abhvsn** [comment]
@vihar I think you have forgotten to deploy the imported app after you made changes as far as the recording is concerned. You can check the application id from the URL, it's being updated correctly when we share the imported application. The general format that we use for URL is as follows : 
Edit mode : {host_url}/applications/**{applicationId}**/pages/**{pageId}**/edit
View mode : {host_url}/applications/**{applicationId}**/pages/**{pageId}**

**Comment by Nikhil-Nandagopal** [comment]
@abhvsn maybe we can copy the published app too so that it's an exact export?

**Comment by abhvsn** [comment]
Yes, that's already in place. That's why this confusion started. 
After import, we see the edit mode but for share, we have view mode by default where Vihar had different layouts because the original app had those differences in the layout between edit and view mode. 

Closing this as it's a false alarm
