### ISSUE TITLE
[Bug] Redis plugin: handle space in string args

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6363]
## Description
Currently Redis plugin splits the overall string by whitespace and assumes first token to be cmd, and rest to be args. However, this fails in case a string arg is present which has spaces in it. 

Context:
https://discord.com/channels/725602949748752515/760761686549463060/872097304734224414

**Comment by awanishraj** [comment]
Line number 72 in RedisPlugin.java can be improved with this solution: https://stackoverflow.com/questions/3366281/tokenizing-a-string-but-ignoring-delimiters-within-quotes

**Comment by sumitsum** [comment]
@awanishraj thanks a lot for pointing this out. I will take a look at it.
