### ISSUE TITLE
[Bug] Expected Structure Example is not being displayed to user in API Pane

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6364]
Steps to reproduce:
1) Add an POST API 
2) Add  body to the api
and observe

Observation
It is observed that the Expected Structure Example  is not displayed to the user 

Expectation:
The example must be displayed to the user
![Screenshot 2021-08-03 at 7 37 04 PM](https://user-images.githubusercontent.com/71753653/128029668-81aad3f3-ec6c-4273-bfc9-9e0546ef65c0.png)

**Comment by somangshu** [comment]
@riodeuno is this expected?
