### ISSUE TITLE
[Docs] Mention `debugger` statement as part of troubleshooting guide

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6365]
## Describe the problem
```
I found really usefull the debugger statement, for debugging js logic error inside widget actions. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger?retiredLocale=it

Maybe we could mention it, in this section of the readme
https://docs.appsmith.com/troubleshooting-guide/widget-errors
```

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me.

**Comment by hetunandu** [comment]
Hey @mohitsaxenaknoldus assigning this to you. The docs are maintained in a separate repo ["appsmithorg/appsmith-docs"](https://github.com/appsmithorg/appsmith-docs)
Please read our [doc contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before opening the PR.

**Comment by mohitsaxenaknoldus** [comment]
Thanks for that @hetunandu. I've opened a PR for the same, please review: https://github.com/appsmithorg/appsmith-docs/pull/178
