### ISSUE TITLE
[Bug] Modal from other pages does not open on clicking the comment card in the view mode

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#6369]
## Description
Modal from other pages does not open on clicking the comment card

### Steps to reproduce the behaviour:
1. Create a new page (Page 2)
2. Add a modal widget to the page
3. Add a comment to the modal widget
4. Deploy the app
5. Switch to Page 1
6. Click on the comment card
7. The modal does not open

We'd need to click again to open the modal

**Comment by Ranzeb** [comment]
Hi can i work on this feature?

**Comment by mohanarpit** [comment]
Closing this issue as it's not valid any more.
