### ISSUE TITLE
[BUG] Wrong error message while resetting the password

### ISSUE THREAD

**Issue by gogetter22** [appsmithorg/appsmith#637]
Important Details
Version: Cloud
OS: MacOSX
Browser: chrome

Steps 
1 Open https://app.appsmith.com/
2 Click on Forgot Password
3 Enter Email and click on 'Reset'

Expected - error 'Unable to find user with email gogetter22@gmail.com'
Actual - error 'Unable to find user with id gogetter22@gmail.com'

<img width="1791" alt="Screen Shot 2020-09-21 at 1 23 09 AM" src="https://user-images.githubusercontent.com/71608910/93720856-86553f80-fba9-11ea-9bcf-d65de583037d.png">

**Comment by Nikhil-Nandagopal** [comment]
@gogetter22 we use id internally for email / github username so this is technically right, will add this as a UX improvement

**Comment by Jain-Sanchit** [comment]
@Nikhil-Nandagopal Can you please elaborate the issue ? I would like to work on this if i get it.

**Comment by Nikhil-Nandagopal** [comment]
@Jain-Sanchit the response error message says that the id is not found but its actually the email or username. So there error message needs to be updated to say that the email cannot be found or the username cannot be found if its GitHub
