### ISSUE TITLE
[Bug]  Nested API or datasource breaks the widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6370]
Steps to reproduce:
1) Add an API 
2) Run the API 
3) Select list from the widget list
and observe the widget on the canvas

Observation:
It is observed that when the nested API is binded to the widget breaks 

Expectation:
As we are looking into providing good experience to the user we need to dynamically read and understand the API before binding them. 
![Screenshot 2021-08-03 at 10 03 26 PM](https://user-images.githubusercontent.com/71753653/128052678-e64b87c3-9104-4814-9c78-188937beff36.png)

**Comment by akash-codemonk** [comment]
Closing as duplicate of #6268
