### ISSUE TITLE
[Bug] Cyclic dependency error occurs while creating Google sheet Datasource 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6374]
## Description
Release Frozen - It is observed that user is not able to create google sheet datasource - Cyclic dependency error occurs

Expected Result:
Cyclic dependency error should not occur while creating google sheet datasource

### Steps to reproduce the behaviour:

1. Launch Appsmith app in the release frozen environment 
2. Click on datasource 
3. click create new and select - Google sheet 
4. Click on save 
5. Allow access to google account and observe

**Videolink:**
https://www.loom.com/share/2aa696071d8346dc9074815d7e21205e

### Important Details

- Version: [11.3]
- OS: [e.g.MacOS]
- Browser [chrome, safari]
- Environment [release frozen]

**Comment by YogeshJayaseelan** [comment]
@somangshu This happened because of issue #6375

**Comment by somangshu** [comment]
@YogeshJayaseelan The original error occurred because no permissions were assigned while oAuth. Now as mentioned in #6375 it seems to be something connected to the API call itself. Shall check dig more there
