### ISSUE TITLE
[Feature] Custom Authentication only supports the most basic usecase

### ISSUE THREAD

**Issue by BlueWater86** [appsmithorg/appsmith#6384]
## Summary

The custom authentication flow described here: https://docs.appsmith.com/how-to-guides/how-to-implement-custom-authentication-on-appsmith only supports the most basic use case. My organisation uses Azure authentication over MSAL to secure all APIs. I need MSAL integration.

## Motivation

Without [MSAL integration](https://github.com/AzureAD/microsoft-authentication-library-for-js) my organisation cannot progress with implementation of Appsmith.

## Additional Context

We have already completed vertical slice development effort and have implemented this feature request through a new widget. The widget functionality is complete and allows for a JWT to be retrieved from Azure with an event raised on a successful login and subsequent silent token refreshes. The purpose of raising this feature request is so that I can check if this new widget will be accepted as a pull request.

**Comment by BlueWater86** [comment]
If Azure MSAL integration is not acceptable for merge we will continue on our private branch. If it is something you would like integrated, we will complete our development and may need a bit of guidance of which branch you want this merged against.

![image](https://user-images.githubusercontent.com/6543901/128161555-df7d8c10-9b62-498a-95b9-33b656aa92f7.png)

**Comment by Nikhil-Nandagopal** [comment]
Hi @BlueWater86 unfortunately, we wouldn't accept this feature as a pull request because we plan on introducing custom authentication in our enterprise plans.
