### ISSUE TITLE
[Feature] Add export application to top navbar

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6387]
## Summary

Add the option to export application in the top navbar
![Screenshot 2021-08-04 at 4 45 04 PM](https://user-images.githubusercontent.com/11089579/128171767-dce90f2a-d14c-454c-aa36-57be6c8b52df.png)

## Motivation

Its under context that the user might need the option while he is on the application

**Comment by rahulramesha** [comment]
@somangshu this seems to be already implemented and in production by @Rishabh-Rathod, closing this
