### ISSUE TITLE
[Bug] UX : On resizing the Multi select the data does not get truncated appropriately

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6389]
Steps to reproduce:
1) Add a multi-select widget
2) Resize the widget (smaller or larger)
and observe the widget

Observation:
It is observed that the truncation for the option happens from the right which disturbs the truncation

Expectation:
It is expected that the data must be visible to the user 

![Screenshot 2021-08-04 at 5 51 50 PM](https://user-images.githubusercontent.com/71753653/128179967-4c78e6f9-2d47-4903-b4a0-30b3304e8734.png)

**Comment by somangshu** [comment]
We need to give a min width to the multi-select popover

**Comment by Tooluloope** [comment]
@somangshu It actually has a min width,
Couldn't reproduce this
<img width="292" alt="Screenshot 2021-08-04 at 22 24 46" src="https://user-images.githubusercontent.com/31691737/128256964-47103eb5-adde-4efb-9895-bd17f70be8b9.png">
