### ISSUE TITLE
[Bug]The " Lets go" button is not clickable on the onboarding popup

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6393]
## Description

[What happened]The "Let's go" button is not clickable on the Onboarding pop up when the user deletes the default org 

### Steps to reproduce the behavior:

1. Sign in to appsmith 
2. Create a new org
3. Assign the default org to other users 
4. delete the default org
5. Now start the Onboarding by clicking on a welcome tour 
6. The let's go button is not clickable

https://www.loom.com/share/9bd352fa12924d05a2c0cd37f2317341

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [release]

**Comment by sharat87** [comment]
@akash-codemonk, assigning to you since you worked on On boarding right? Let me know if that's not the case :)

**Comment by akash-codemonk** [comment]
@RakshaKShetty Is this still happening? I removed myself from the default org and clicked on `Let's go` it creates an application from the other organisation.

**Comment by akash-codemonk** [comment]
Closing this as this is no longer happening. @RakshaKShetty
