### ISSUE TITLE
[Bug]The select widget fails when a user tries to bind it from the suggested widget section - when the data has duplicate values

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6394]
## Description

[What happened]The select widget fails when a user tries to bind it from the suggested widget section. This happens when data has all nonunique values

### Steps to reproduce the behaviour:

1.Run the mock API 
2.select the select dropdown from the widget suggestion section
3.verify the error displayed in the debugger 
![image](https://user-images.githubusercontent.com/45958978/128289626-3e7fc4d4-1fd7-4ea8-9585-5ad4d31d7394.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [chrome]
- Environment [ release]

**Comment by Nikhil-Nandagopal** [comment]
Generic problem of the suggested widgets
