### ISSUE TITLE
[BUG] While running a query : PluginExecution failed

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#640]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login
2. Go to table tutorial --> edit --> usersTable --> onRowSelected --> Execute a DB query --> Create query --> select
3. Run SELECT * FROM users ; - It succeeds and fetches the correct result
4. Run  SELECT phoneNo FROM users ; --> There is an error:
PluginExecution failed with error ERROR: column "phoneno" does not exist Hint: Perhaps you meant to reference the column "users.phoneNo". Position: 8

Attachement : https://drive.google.com/drive/folders/16zPO1Ud3ZY9KQrSuE8hXNbJ3l3sQT72E?usp=sharing

**Comment by Saket2** [comment]
@areyabhishek , @Nikhil-Nandagopal I understand that we're not supposed to find issues in the Example apps - that's why I'm ignoring UI and functional issues. 

But when we say that we need to find DB connection and data binding issues, are we not supposed to run the SQL part of example apps and find these bugs? Is there another way to target/find these database errors?

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 this would be a valid issue except that here it's failing because for postgres if you need to reference a column name or table name which has a capital letter, you have to wrap it in quotes. So your query should be 
select "phoneNo" from users
