### ISSUE TITLE
[Epic] Appsmith Design system

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#6410]
## Figma
https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=286%3A0

**Comment by albinAppsmith** [comment]
https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=286%3A0

**Comment by hiteshjoshi** [comment]
Closing this and we will take care of rest of the issues separately.
