### ISSUE TITLE
[Bug] Cmd+enter shortcut doesn't work on Google Sheets action

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#6414]
## Description

Cmd+enter shortcut is used to run actions without having to click the Run button. Since Google Sheets is a custom component, my hunch is that it got missed when we were adding the shortcut

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a Google sheets action
2. Press cmd+enter to execute the action. 
3. See that the action doesn't get executed.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by nipun1999** [comment]
@mohanarpit can I work on this issue. I want to take some good first issues to start contributing

**Comment by nipun1999** [comment]
@mohanarpit I have linked this issue with a PR that is fixing this bug. I request you to approve the build on PR
