### ISSUE TITLE
[Feature] Use prismjs for syntax highlighted expected structure example

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#6421]
## Summary

Use PrismJS for syntax highlighted examples.

## Motivation

Using react-json-viewer for expected structure example, adds elements to the example, which are not a part of the actual value which can be used. This creates scenarios where users copying the value as-is would find the value incorrect.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno moving from UI building since the coding pod should own evaluated values

**Comment by Nikhil-Nandagopal** [comment]
We now have a copy button so closing this
