### ISSUE TITLE
[Task] Avoid fetching documentation README till not needed to show in UI and lazy load as per request.

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#6422]
# Description
Currently on the initial load of https://app.appsmith.com/applications/id/page/pageid documentation README files is fetched which aren't shown in UI.

# Solution

- [ ] Don't Load README files till they aren't requested to show. (when a user opens omnibar it can be fetched and cached)
- [ ] Don't Load all files at the same time. Add lazy loading for whatever is requested.

List of file links

- https://raw.githubusercontent.com/appsmithorg/appsmith-docs/v1.2.1/tutorials/building-a-store-catalog-manager/README.md
-  https://raw.githubusercontent.com/appsmithorg/appsmith-docs/v1.2.1/core-concepts/connecting-to-data-sources/README.md
- https://raw.githubusercontent.com/appsmithorg/appsmith-docs/v1.2.1/core-concepts/displaying-data-read/README.md
- https://raw.githubusercontent.com/appsmithorg/appsmith-docs/v1.2.1/core-concepts/writing-code/README.md

**Comment by mohanarpit** [comment]
Can you also please list the endpoints that are being hit on page load which can be optimized away? 

I'm asking because some release notes endpoints are used in analytics flows. Please ensure you have a view of the entire flow before changing its implementation.

**Comment by Rishabh-Rathod** [comment]
> Can you also please list the endpoints that are being hit on page load which can be optimized away?
> 
> I'm asking because some release notes endpoints are used in analytics flows. Please ensure you have a view of the entire flow before changing its implementation.

@mohanarpit  My bad release notes are not fetched on the initial page load. Only documentation readme pages are fetched (for omnibar) which are mentioned above.
