### ISSUE TITLE
[Enhancement][JS Snippet] Create AWS Lambda function script to sync JS Snippets from Mongo Atlas to Algolia

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6433]
We need a Lambda function script to sync updates to JS Snippets collection e.g. if we add a new snippet or change any property of an existing snippet, then the update needs to be automatically synced to Algolia, so that future Snippet searches can show updated snippet to user.
JS Snippets would be stored in a separate collection in Mongo cloud. The script should be triggered for any update to this collection.

**Comment by mohanarpit** [comment]
Can we add some more information to this issue? What data are we syncing between Mongo Atlas & Algolia?

**Comment by sumitsum** [comment]
Updated the description with some context.
