### ISSUE TITLE
[Feature] Text widget: Need more font styles and font sizes for Text widget.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6439]
## Summary
If possible can we take the font size via a numerical input ? 

```
Can we change font size apart from the given options?
Also can we change font styles?
```

**Comment by somangshu** [comment]
@areyabhishek @jsartisan we were just talking about this. I am now thinking with the new sizes decided should we also give a custom option or from the design POV  dosent make sense 
![Screenshot 2021-08-09 at 2 56 20 PM](https://user-images.githubusercontent.com/11089579/128685573-8171b98b-084d-4b20-9e38-cea0759bd199.png)
![Screenshot 2021-08-09 at 2 56 28 PM](https://user-images.githubusercontent.com/11089579/128685579-fe37ce6c-014f-4f02-a49c-41a996e19c62.png)
