### ISSUE TITLE
[Feature] Allow users to set application logo

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#6442]
## Summary
Currently, users can choose a logo for their application. The logo appears in the users dashboard for the application. But it does not appears inside the application. Instead appsmith logo is shown everywhere. Users should be allowed to set their own logo for each application and that logo should be displayed both in edit mode and view mode.

## Motivation
Any organization that uses appsmith as their internal tool - in most cases has own logo. Their internal users e.g. business users expect the organization logo in the topbar. Imagine, a developer of an organization used Appsmith to quickly build some internal tools. The business users liked the tools but they are not comfortable with appsmith logo. So they asked developer to change the logo which can't be done easily today. A different logo for each application will also help to distinguish an application quickly from other applications.

## Additional Context

A user in discord was looking for an option to change the logo.

**Comment by Rishabhkaul** [comment]
With custom logo / branding, can this issue be closed? @hiteshjoshi
