### ISSUE TITLE
[Bug] Table widget, Column order gets reset on page refresh.

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6454]
## Description

The table column order gets reset on page/data refresh. This is only reproducible on production and not release.

### Steps to reproduce the behaviour:

1. Drag and Drop the table widget
2. Change the column order from the property pane
3. Refresh page or data 
4. Observe the column order reset to original order

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

**Comment by somangshu** [comment]
We need to do an RCA here. How does this only appear on Prod. @Tooluloope can you please look into this?

**Comment by DevSnap** [comment]
I have problems if I change the visibility of the entire table dynamically, in that case I lose order, formatting and column visibility. 
If the table visibility stays fixed to true, it doesn't happen.

Version: Cloud
OS: Windows
Browser: chrome
Environment: production

**Comment by somangshu** [comment]
Thanks for reporting this @DevSnap, We are currently looking into this

**Comment by somangshu** [comment]
Another user reported this error [here](https://discord.com/channels/725602949748752515/760761686549463060/874533451771027457)
