### ISSUE TITLE
[Bug] Inputs inside a form are no longer accessible

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6464]
## Description

The inputs inside a form are not accessible using the form data field
{{ Form1.data.Input1 }}

**Comment by somangshu** [comment]
Related Conversation with the user:
> What I actually meant was:
> - When  Input_m1_attribute  field has some data/text/value inside, {{ Form_m1_attributes.data.Input_m1_attribute }} is accessible
> - Only when the  Input_m1_attribute  Is empty, We cannot reference it from the {{From_m1_attributes.data }} object
>Does this cause an error for you with previously made bindings? Can you confirm if the above is true for you?

> Negative. In my case, even when Input_m1_attribute had a value in it, it wasn't accessible by {{ Form_m1_attributes.data.Input_m1_attribute }}
but only by {{ Input_m1_attribute }}
>{{ Form_m1_attributes.data.Input_m1_attribute }} was not being recognized as a valid element itself whether there was value or not.
>And that too suddenly that day. Previously, it was accessible by {{ Form_m1_attributes.data.Input_m1_attribute }}

We are not able to reproduce this issue on our end. We will be keeping our efforts on towards this.

cc: @riodeuno @ashit-rath @vivekverma2312

**Comment by riodeuno** [comment]
@somangshu @Nikhil-Nandagopal @ashit-rath Until we have more information about this issue. We will be reprioritising to a lower level of priority. We will pick this up as soon as we have details.

**Comment by Nikhil-Nandagopal** [comment]
Then lets just close this till then
