### ISSUE TITLE
[Bug] NavigateTo Option shows a # in the property pane

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6466]
## Description

- The navigateTo method randomly adds a # to the Page name which is incorrect

**Comment by ajinkyakulkarni** [comment]
@Nikhil-Nandagopal can you please tell how to reproduce it? 
 
https://www.loom.com/share/0a5cd6f007594d5d9519156c7298b485

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni my mistake, the query params seem to be working. I think it was an incorrect binding.
The # getting added is still happening

**Comment by ajinkyakulkarni** [comment]
@ApekshaBhosale @vnodecg Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6466?planning-poker)

**Comment by vnodecg** [comment]
Closing in favour of #3125
