### ISSUE TITLE
The AppSmith EDITOR is constantly hanging showing browser "Kill or Wait" window

### ISSUE THREAD

**Issue by President** [appsmithorg/appsmith#6470]
The AppSmith EDITOR is constantly hanging showing browser "Kill or Wait" window
How I reproduce this:
1. Created table that displays some query data.
2. Created Textbox
3. In the text box property started creating binding: typed "{{table."  after I typed dot it hangs. Sometimes it may not hang. But when I repeat it later it will may hang
When I reload the page it will be displaying error and will hang again - w/o ability to edit something.

![image](https://user-images.githubusercontent.com/275339/128674979-075db8d0-8c55-4fde-ba23-c90c173e402b.png)

**Comment by areyabhishek** [comment]
@President Apologies! Is this on Appsmith cloud or self-hosted? Do you face this only while typing in the property pane? Is it possible to record a video of this happening?

**Comment by President** [comment]
FYI: 
I have found that it happens when I am using query that returns 4000+ rows and 20 columns.
It seems AppSmith tries to fetch and put all that data right into single text element and it halts whole the Editor.
When I limited the result to just 3 rows (temporary added LIMIT to the query) - it all started working well

**Comment by SatishGandham** [comment]
Hi @President , Thanks for the details.
If you are using it in a table, it exposes the pageSize and pageNo properties. You can use them in your query like this.
Example
`select * from users limit {{ Table1.pageSize }} offset {{ (Table1.pageNo - 1) * Table1.pageSize }}`
Ref: https://docs.appsmith.com/core-concepts/displaying-data-read/display-data-tables#pagination
Let me know if this solves your use case or if you need further help.
