### ISSUE TITLE
[Bug] Google Sheets 'generate page' button by CRUD has a different design to the other sources

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6472]
## Description
'Generate Page' button on Google Sheet data source and is displayed differently on a grey strip background 

### Steps to reproduce the behaviour:
1. Go to generate page by crud and choose a Google Sheet datasource
2. Select spreadsheet, sheet and column and observe the 'generate page' button at the bottom

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: deploy preview

![image](https://user-images.githubusercontent.com/79509062/128675811-cf776512-5175-4a8c-89e4-311ba302cbe9.png)

**Comment by Rishabh-Rathod** [comment]
This should be fixed.
