### ISSUE TITLE
[BUG] Part1- Doc Improvement

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#648]
[AppSmith Doc](https://docs.appsmith.com/quick-start)
### Introduction
Present:- Invest weeks of time building it from scratch and fighting with HTML/CSS
Improvement:- `Investing` weeks of time building it from scratch and fighting with HTML/CSS

### Getting Started
Present:- Appsmith stands for speed and getting started with Appsmith is just as fast.
Improvement:- Appsmith stands for speed and getting started with Appsmith is just as fast `as Usain Bolt`.

Present:- To simplify installation, appsmith comes with an installation script that will download all of the necessary dependencies and help you configure appsmith.
Improvement:- To simplify installation, appsmith comes with an installation script that will download all of the necessary dependencies and `helps you in configuring the appsmith`.

Present:- If you're installing appsmith on Mac, you must have docker desktop installed. Docker is installed automatically by the script on other operating systems.
Improvement:- `For Mac, Docker Desktop is required. For other operating systems, docker will be installed automatically by the script`.

Present:- Check if all containers are running correctly.
Improvement:- Check if all `the` containers are running correctly.

### FAQs
Present:- You may have these questions and we want to answer.
Improvement:- You may have these questions and `we would like to answer them`.

Present:- What type of apps are built on Appsmith?
Improvement:- `What kind of apps can be built on Appssmith`?

Present:- We make building internal tool building easy by giving you building blocks (widgets, APIs, Queries) which you can configure and connect together while the framework does most of the heavy lifting.
Improvement:- `Appsmith makes building internal tool building easy,` by giving you building blocks (widgets, APIs, Queries) which you can configure and connect together while the framework does most of the heavy lifting.

Present:- Appsmith bridges mundane API and UI configurations with powerful code expressions to let you build apps the way you see fit.
Improvement:- Appsmith bridges mundane API and UI configurations with powerful code expressions to let you build `the` apps the way you see them fit.

Present:- Appsmith is open source and can be fully audited and deployed on-premise to ensure none of your data leaves your VPC.
Possible Improvement:- Appsmith is `an` open source `framework` and can be fully audited and deployed on-premise to ensure none of your data leaves your VPC.

Present:- What if I get stuck building an app on Appsmith?
Improvement:- What if I get stuck `while` building an app on Appsmith?

Present:- What can't I do on Appsmith?
Improvement:- `Like with every GOD particle, Appsmith also has its own limitations?`

Present:- It works great for tools internal to your team or organization but you wouldn't get very far trying to build an attractive consumer website. 
Improvement:- It works great for tools`,` internal to your team or organization (didn’t get it after this)but you wouldn't get very far trying to build an attractive consumer website.

**Comment by AninditaBasu** [comment]
@visibleajay @Nikhil-Nandagopal Is this issue already taken? If not, I could maybe take it up for Hacktoberfest?

**Comment by visibleajay** [comment]
@AninditaBasu Thank You for showing interest. This is in open and anybody can take it. Also, [AppSmith](https://app.appsmith.com/) is running a [Bug Bounty](https://github.com/appsmithorg/appsmith/discussions/577) contest.

**Comment by AninditaBasu** [comment]
Thank you @visibleajay . Can you please assign this one to me then? I wont take it up before Oct 1 (and would like to call dibs 🙂 )

**Comment by Hard-Coder05** [comment]
@Nikhil-Nandagopal @mohanarpit I would like to take this issue for hacktoberfest!

**Comment by mohanarpit** [comment]
@Hard-Coder05 Welcome to Appsmith! 🎉 Go for it! 

Make sure you read our [docs contributions guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before starting.

**Comment by Hard-Coder05** [comment]
@mohanarpit If this is considered as a `Hactoberfest` issue then please do add the label
btw I am working on it!

**Comment by Hard-Coder05** [comment]
@Nikhil-Nandagopal @mohanarpit I have raise th PR please review it once and You can close this issue!
