### ISSUE TITLE
[Bug] Table's visible columns are not saved

### ISSUE THREAD

**Issue by President** [appsmithorg/appsmith#6480]
## Description

The table's configuration about what fields are not visible is not saved.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create table
2. Bind it to the query
3. Hide some columns
4. Ensure app was saved
5. Exit the app
6. Reopen the app

Now you see that all fields are visible again

**Comment by Nikhil-Nandagopal** [comment]
@President thank you for reporting this!

**Comment by somangshu** [comment]
Similar issue reported in #6454 where the column order is not saved, This is not reproducible on our release environment. 

@vivekverma2312 @YogeshJayaseelan can you verify this? 
@Tooluloope we need to understand the difference here, Please look into this at priority
