### ISSUE TITLE
[Bug]The File picker button is retained with the "1 file selected " text when the user tries to select the second file

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6492]
## Description

[What happened] The File picker button is retained with the "1 file selected " text when the user tries to select the second file

### Steps to reproduce the behavior:
1.Click on Generate app 
2.Select s3 datasource 
3.Select bucket as "Assets-test.appsmith.com"
4.click on generate app button
5.Now click on Add file button 
6.Select one file 
7.click on the upload
8.now click on add file again 
9.verify the display
![Uploading image.png…]()

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c233efa813404e54b531d5a93e801546-00001.gif)](https://www.loom.com/share/c233efa813404e54b531d5a93e801546)

### Important Details

- Version: [Cloud ]
- OS: [.MacOS]
- Browser [chrome]
- Environment [ deploy preview->6264]

**Comment by somangshu** [comment]
@ramsaptami What happens if you reset the widget onSuccess of the submit actions?

**Comment by RakshaKShetty** [comment]
@somangshu I have added action to reset the widget on Success. so the issue which I am facing now is there is 2 file picker widget in my application. one is inside the Upload file pop up and one is inside the Update file pop-up. So when i add a new file from the upload file pop up the reset happens and the "1 file selected" text won't be displayed, but when i open the update file pop up here i am seeing "1 file selected " text even when i have not updated any of the files.https://www.loom.com/share/632325172ba14eefaed8f02d7053262e

**Comment by somangshu** [comment]
@RakshaKShetty are you seeing this before adding a new file? Also please share the access to this app!

**Comment by RakshaKShetty** [comment]
@somangshu i am seeing this issue after adding a file. yes i am sharing it with you

**Comment by somangshu** [comment]
Looks like some problem with the reference. @SatishGandham can comment better

**Comment by SatishGandham** [comment]
When a file is selected in the filepicker under "Add Files" button, file picker inside the update button is also updated with the same list. Looks like a bug in evaluations.

**Comment by somangshu** [comment]
This is probably related to #6206

**Comment by RakshaKShetty** [comment]
Reopening the issue we are able to repo this in our regression
![image](https://user-images.githubusercontent.com/45958978/151786056-df08f706-2b44-4133-9021-386b842e658b.png)

**Comment by sbalaji1192** [comment]
Related to https://github.com/appsmithorg/appsmith/issues/9603

@Rishabh-Rathod Has provided a fix for #9603, which should solve this issue as well.
@techbhavin We can close your PR associated with this issue.

@Rishabh-Rathod Could you please verify this once on your DP and add this issue ID to your PR?

**Comment by btsgh** [comment]
Tested on Release build and issue is fixed. 
https://www.loom.com/share/359214086b8a40558bba77c639fc53e8
