### ISSUE TITLE
[Bug]When the Page is autogenerated for s3 datasource the default error is displayed in the debugger section for the list widget

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6493]
## Description

[What happened] When the Page is autogenerated for s3 datasource the default error is displayed in the debugger section for the list widget

### Steps to reproduce the behaviour:

1.Click on Generate app
2.Select s3 datasource
3.Select bucket as "Assets-test.appsmith.com"
4.click on generate app button
5.verify the display of default error in the Debbuger section
![image](https://user-images.githubusercontent.com/45958978/128741428-fbeb57e9-b5d5-4c37-ad5e-3a7b95d22825.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [chrome]
- Environment [deploy preview]

**Comment by somangshu** [comment]
Hey Pawan, Please help me understand if this is really related to the list widget. Please comment

**Comment by Aishwarya-U-R** [comment]
Seeing this issue still.

**Comment by somangshu** [comment]
@Aishwarya-U-R please add additional context with your comment

**Comment by Tooluloope** [comment]
I'm unable to reproduce this issue now.

**Comment by Aishwarya-U-R** [comment]
Confirming that not seeing this issue anymore on a S3 datasource.
<img width="872" alt="Screenshot 2022-07-04 at 1 21 08 PM" src="https://user-images.githubusercontent.com/91450662/177107875-2d9a4793-a586-42a8-b36c-d54f92494287.png">
