### ISSUE TITLE
[Bug]The error is displayed in the debugger when the user searches for the file name which is not there in the list 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6494]
## Description

[What happened]The error is displayed in the debugger when the user searches for the file name which is not there in the list
### Steps to reproduce the behaviour:

1.Click on Generate app
2.Select s3 datasource
3.Select bucket as "Assets-test.appsmith.com"
4.click on generate app button
5.Now in the search file prefix input box search for the file name which is not present 
6.verify the display
![image](https://user-images.githubusercontent.com/45958978/128742120-bbe3c0f0-640a-44c4-8dfc-5994e13b3829.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [chrome]
- Environment [deploy preview]

**Comment by somangshu** [comment]
@jsartisan please take a look at this? Can we take this up by the next sprint?

**Comment by somangshu** [comment]
@jsartisan Note:
- The list widget throws an error if the list data has [ ] (empty array)
- The list widget children also throw an error in case the currentItem is referenced

The first error can still be resolved as follows
![Screenshot 2021-08-13 at 12 11 33 PM](https://user-images.githubusercontent.com/11089579/129315663-8a91edb1-f73d-4153-8c8d-cf5bd4a16b77.png)

However, the error in the input field does not resolve:
![Screenshot 2021-08-13 at 12 12 34 PM](https://user-images.githubusercontent.com/11089579/129315749-da88e76a-0349-4d39-b212-375bda2ceb37.png)

**Comment by jsartisan** [comment]
@somangshu I will be discussing this and some other bugs that are there in the sprint backlog with Hetu.

**Comment by Tooluloope** [comment]
I'm unable to reproduce this issue now.
