### ISSUE TITLE
Add analytics datapoint for events related to git-sync

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#6496]
Possible endpoints can be :

1. Git config without the sensitive fields
2. Basic git operations like commit, push, pull etc. with status success/failure and related metadata

Connecting an existing app / importing:
- [x] Connect to git modal: deploy button or bottom bar (FE)
- [x] Generate key CTA (FE)
- [x] Documentation link for the SSH key, via: (FE)
    - [x] Generate key step
    - [x] Connect step
- [x] Copy key (FE)
- [x] Git connection tab CTA (BE)
    - [ ] Was it during connection or updating the local config
    - [ ] Flag: using local or global config during connection
- [ ] Connection errored: (BE)
    - [ ] Invalid repo, reason:
        - [ ] Non empty
        - [ ] Not found
    - [ ] Key not setup
- [x] Import link at the organisation context menu (`/applications` page) (FE)

Commits: push & pull
- [x] Modal trigger: deploy button or bottom bar (FE)
- [x] Commit and push: (BE)
    - [x] Successful
    - [ ] Errored:
        - [ ] Invalid key / read only key
        - [ ] Remote is ahead
- [ ] Pull
    - [x] Trigger: bottom bar or commit tab (after push failed) (FE)
    - [ ] Errored (BE)
        - [ ] due to conflicts
        - [ ] missing/invalid key (rare, in case the key was deleted)
- [x] Documentation link clicks (FE)

Merge:
- [x] Tab opened, via (FE)
    - Bottom bar
    - Tab click
- [ ] Merge status fetched: (by switching branches) (BE)
  - [ ] Conflicts
  - [ ] Success
- [x] Submit CTA (BE)

Disconnect:
- [x] Click on disconnect from connection tab (FE)
- [x] Submit on disconnect modal (BE)
- [x] Edit app name on disconnect modal (FE)

Error modal to show restriction for number of apps that can be connected to private repos:
- [ ] Modal triggered (FE)
- [x] Click on contact sales (FE)
- [x] Click on disconnect (FE)

**Comment by AnaghHegde** [comment]
After the discussion with @vuiets, we have decided that no error states are sent as part of analytics.
