### ISSUE TITLE
[Bug] Multi-select widget documentation is not available on appsmith tutorial 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6500]
Can we please add documentation for multi-select widget as separate widget on tutorial as now multi-select is a different widget.

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Tooluloope** [comment]
@vivekverma2312, Here's the PR, let me know if I didn't catch some properties or properly separate both widgets

 https://github.com/appsmithorg/appsmith-docs/pull/173

**Comment by Tooluloope** [comment]
@vivekverma2312 https://github.com/appsmithorg/appsmith-docs/pull/173 has been merged
