### ISSUE TITLE
[Bug] Set max height of the property pane relative to view port height

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#6501]
## Description

Right now property pane max height is set to static 600px. When the view port is shorter than 600px, there is no way to see the header of the property pane.

### Steps to reproduce the behaviour:

Resize the browser so that the height is less than 700px, and open table or chart property pane. You will not see the header

![Screenshot 2021-08-10 at 12 39 13 PM](https://user-images.githubusercontent.com/441914/128823641-e41b2069-a05c-422c-81b7-2859d271510b.jpg)

**Comment by somangshu** [comment]
We might not want to put more effort here in favour of #6576.

**Comment by somangshu** [comment]
@SatishGandham removing this from good first issues because I think this will be resolved with the docked property pane

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we're docking the property pane
