### ISSUE TITLE
[Bug] File upload on S3 template displays error which does not resolve after successful file upload

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6509]
## Description
Incorrect entry is present during file upload on S3 template which is not resolved even after a successful file upload

### Steps to reproduce the behaviour:
1. Generate page from s3 data source
2. Click on 'Add files' and observe an entry already present in the list widget with an error
3. Upload a file and observe that the error does not resolve

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy Preview

![image](https://user-images.githubusercontent.com/79509062/128853752-8050d6f7-d288-4f1b-97d1-d28a73920287.png)

**Comment by Rishabh-Rathod** [comment]
<img width="1124" alt="Screenshot 2021-08-11 at 1 05 36 PM" src="https://user-images.githubusercontent.com/23132741/128989082-96e707e0-1792-45c1-bf68-881af60d0f27.png">

Also when files are added to `FilePicker` and `listWidget` items = {{FilePicker.files}} 
It shouldn't show "Reference error `currentItem` is not defined".

@jsartisan can you check this.

**Comment by SatishGandham** [comment]
This seems to be due the current implementation of list widget.

**Comment by Tooluloope** [comment]
Currently works without error
<img width="1481" alt="Screenshot 2022-07-03 at 21 46 27" src="https://user-images.githubusercontent.com/31691737/177056786-97042d65-3974-4b12-9273-c578ffe4abb7.png">
