### ISSUE TITLE
[BUG] Inconsistent behavior on the homepage

### ISSUE THREAD

**Issue by gogetter22** [appsmithorg/appsmith#651]
Important Details
Version: Cloud
OS: MacOSX
Browser: Firefox 68.12.0esr (64-bit)

Steps to replicate
1 Login 
2 Click on Share --> 'Invite Users' window opens up
3 Click outside the window and window is closed
4 Click on Create Organization --> Create Organization window opens up
5 Click outside the window and window is not closed

Actual Result - inconsistent behavior across 2 screens on the same page.

Link to the attachment - https://drive.google.com/drive/folders/1SSkt09zb_t1UgAIO2hniL1yBZHTAexDM?usp=sharing

**Comment by satbir121** [comment]
We are using `blueprint` library `Dialog` for showing modal popups. Pass `canOutsideClickClose` as `false` to the `FormDialogComponent` in `pages/Applications/index.tsx` page.

**Comment by satbir121** [comment]
@Nikhil-Nandagopal Should all the forms close on outside click or not close on outside click?

**Comment by Nikhil-Nandagopal** [comment]
@satbir121 all invite modals should close on clicking outside

**Comment by satbir121** [comment]
And what about the `Create Organization` modal?

**Comment by Nikhil-Nandagopal** [comment]
@satbir121 yes same case, any modal that does not absolutely require a users input without which the flow is broken should be dismissable
