### ISSUE TITLE
[Bug] Generated list widget auto focus in not proper on the canvas 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6511]
## Description
Deploy Preview - https://deploy-preview-5389--appsmith-editor-ce.netlify.app/
It is observed that when the suer generates list widget from API the auto focus is not proper on the canvas(it goes to the bottom where user needs to scroll) where table table and chart the focus is proper

**Expected Result:**
Generated list widget on canvas should have proper focus

**Videolink:**
https://loom.com/share/a1dd3cef8eff4ba78c05fc0de3f95a0a

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [deploy preview]

**Comment by vibh1103** [comment]
Hi can i work on this issue ?
