### ISSUE TITLE
[Bug] Automated intercom trigger messages are not working properly.

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#6514]
## Description
To get any automated msg on intercom, user has to trigger intercom on their own at least once.

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [production, release, deploy preview]

**Comment by RakshaKShetty** [comment]
The pop up is displayed when the user is on the home page for more than 3 min 
![image](https://user-images.githubusercontent.com/45958978/129183119-4168767c-042b-4c0d-9b45-4c2f0bc4496b.png)
