### ISSUE TITLE
Resizing widget towards right doesn't work if property pane is visible [Bug]

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#6517]
## Description

Unable to resize the widget towards the right side, if the property pane is visible towards the right side of the widget.
If we click outside the widget so that the property pane is invisible, we can resize.

### Steps to reproduce the behaviour:

1. Insert any widget.
2. Click on it so that the property pane is visible towards the right side of the widget.
3. Try to resize the widget using the control on the right side

### Important Details

- Version: Self-Hosted v1.5.13
- OS: Ubuntu
- Browser: Firefox
- Environment: release

**Comment by Nikhil-Nandagopal** [comment]
Closing this since we're docking the property pane
