### ISSUE TITLE
[Feature]-[500]:The table header controls need to be responsive if there is space available

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6518]
## Summary

The table widget header controls need to be responsive (until there is space available) in case the widget is resized.

## Motivation

Better UX

## Additional Context

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6cd26eb8ccd3481da0ba69615c1314f8-00001.gif)](https://www.loom.com/share/6cd26eb8ccd3481da0ba69615c1314f8)

## Figma link
https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=8%3A7176

**Comment by vibhandikyash** [comment]
https://images.zenhubusercontent.com/275993885/f1d76b61-27af-45aa-b849-234bb61ac218/table_resizing.mov
As per the issue this is already working as expected. Closing this for now. 
cc: @somangshu

**Comment by areyabhishek** [comment]
@vibhandikyash The table still isn't responsive when you have multiple controls. In the video above, I only have the pagination controls but no other controls. 

See video here with other controls: https://www.loom.com/share/cedb83e2caf24429bf84ff8fd702109f
@momcilo-appsmith Could you add the Figma files for this?

**Comment by momcilo-appsmith** [comment]
Link to the responsive version of the table: https://www.figma.com/file/trkiMc12VVpQBqsm7natiU/Table-Changes-Wed-7-Apr-2021?node-id=8%3A7176

**Comment by somangshu** [comment]
I am seeing a concern here, When the header width is reduced the important functionality like search etc are hidden and not accessible to the user, a weird scroll appears but I dont understand how to move it. Is this expected? @momcilo-appsmith @dilippitchika. 

cc @techbhavin

**Comment by dilippitchika** [comment]
Was not aware this was being done, the design is still being discussed on here - https://www.figma.com/file/aJ2Hwz9gH5AK6zaRYtZV8a/Table-widget-update?node-id=846%3A72237

@somangshu can we remove this change from release for now and add this back to needs design?

**Comment by btsgh** [comment]
Tested on Release and here are my observations - 
**Working as per requirement** - (As per the figma doc and dp mentioned in https://github.com/appsmithorg/appsmith/pull/10971), the pagination control moves correctly when table is resized to extra small.

**However, the following are not as per required behaviour:**
 - The controls and do not move smoothly as and when you drag the widget (This was one of the issues documented and explained in a video by Swetha in https://github.com/appsmithorg/appsmith/pull/10971)  
 - Also, when the table widget is sized to a small column width, a scroll bar appears on moving mouse over the table header. But does not seem like it functions. As a user, I should be able to move through and see the various options in the header. (Search / Filter/ Download)  
 -
https://www.loom.com/share/4db4476917b4444cbc677ece044722f5

@somangshu  -  Do you suggest we reopen this issue?

**Comment by somangshu** [comment]
- @btsgh for the first point - I dont think the behaviour is relevant to the app viewer and hence not an important issue to solve. 
- For the second point, I agree to your observation, this is not an Appropriate behaviour. @momcilo-appsmith Need you comments on this. 

Compared to the production environment, this commit leaves some functionality in a not usable state. Hence I agree to @dilippitchika, we will revert this commit. @techbhavin can you kindly take care of that.

**Comment by momcilo-appsmith** [comment]
@somangshu I am linking a new design we are working on currently, I will share it with others in Slack today as well.
https://www.figma.com/file/aJ2Hwz9gH5AK6zaRYtZV8a/Table-widget-update?node-id=846%3A72237

**Comment by momcilo-appsmith** [comment]
Edited the [link](https://www.figma.com/file/aJ2Hwz9gH5AK6zaRYtZV8a/Table-widget-update?node-id=1128%3A77992) in my comment

**Comment by dilippitchika** [comment]
Reach - no. of non desktop users in the last 6 months
Effort - Assuming design, dev and QA effort

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1500 |
| Effort (months)  | 1.5 |
