### ISSUE TITLE
[Bug] Import/export not working correctly, layout gone

### ISSUE THREAD

**Issue by RonaldKools** [appsmithorg/appsmith#6519]
## Description

When importing an application from the cloud to a self hosted Kubernetes version, the import itself succeeds but the layout is broken.
Lots of JS errors in the console:

`main.c32f0f89.chunk.js:1 Widget meta properties not defined:  MULTI_SELECT_WIDGET
getWidgetMetaPropertiesMap @ main.c32f0f89.chunk.js:1
main.c32f0f89.chunk.js:1 Widget type validation is not defined
getWidgetDerivedPropertiesMap @ main.c32f0f89.chunk.js:1
main.c32f0f89.chunk.js:1 Widget default properties not defined MULTI_SELECT_WIDGET
getWidgetDefaultPropertiesMap @ main.c32f0f89.chunk.js:1
main.c32f0f89.chunk.js:1 Widget property pane configs not defined MULTI_SELECT_WIDGET
getWidgetPropertyPaneConfig @ main.c32f0f89.chunk.js:1
evaluation.worker.e6942976.worker.js:2 TypeError: Cannot read property 'defaultProperties' of undefined
    at C.listEntityDependencies (evaluation.worker.e6942976.worker.js:2)
    at evaluation.worker.e6942976.worker.js:2
    at Array.forEach (<anonymous>)
    at C.getPropertyPathReferencesInExistingBindings (evaluation.worker.e6942976.worker.js:2)
    at evaluation.worker.e6942976.worker.js:2
    at Array.forEach (<anonymous>)
    at C.updateDependencyMap (evaluation.worker.e6942976.worker.js:2)
    at C.updateDataTree (evaluation.worker.e6942976.worker.js:2)
    at B (evaluation.worker.e6942976.worker.js:2)
    at evaluation.worker.e6942976.worker.js:2
B @ evaluation.worker.e6942976.worker.js:2
evaluation.worker.e6942976.worker.js:2 Uncaught TypeError: Cannot read property 'derivedProperties' of undefined
    at evaluation.worker.e6942976.worker.js:2
    at Array.reduce (<anonymous>)
    at U (evaluation.worker.e6942976.worker.js:2)
    at B (evaluation.worker.e6942976.worker.js:2)
    at evaluation.worker.e6942976.worker.js:2`

### Steps to reproduce the behaviour:

1. Go to an Appsmith cloud environment and click on the menu of an application 
2. Click on Export to get the JSON
3. Go to an Appsmith kubernetes environment and import the application JSON
4. All succeeds but the layout is destroyed

### Important Details

- Version: cloud and selfhosted on Kubernetes (Appsmith 1.5.13)
- OS: Ubuntu
- Browser Chrome
- Environment production

**Comment by areyabhishek** [comment]
@RonaldKools How is the layout broken? Do you have a before/after screenshot you can share? We'll try to reproduce this and get back to you.

**Comment by RonaldKools** [comment]
Before:
![image](https://user-images.githubusercontent.com/15251435/128954224-63e49210-2c2b-4b03-8bba-fe424ed97110.png)


After:
![image](https://user-images.githubusercontent.com/15251435/128953880-ce296b36-264a-41ac-ab6e-825266db2104.png)

![image](https://user-images.githubusercontent.com/15251435/128953925-c2b676fb-d41b-44e9-bdbe-280e9a548127.png)


Data source is ElasticSearch.

**Comment by abhvsn** [comment]
@RonaldKools if possible can you invite me to your application: abhijeet@appsmith.com on the cloud. If not can we connect regarding this issue as we will need some more details to fix it. Please schedule a call as per your availability https://calendly.com/abhvsn

**Comment by RonaldKools** [comment]
@abhvsn I think I found the issue. The "Multiselect" widget is missing in our Kubernetes version v1.5.13:

![image](https://user-images.githubusercontent.com/15251435/129070991-7bc283b2-62a4-4678-988e-dc6d95c81b62.png)

vs the cloud version:

![image](https://user-images.githubusercontent.com/15251435/129071080-f5ece8a1-8f0d-4af4-946c-bfe29acb2509.png)

**Comment by Nikhil-Nandagopal** [comment]
@RonaldKools great catch! This is a version mismatch issue. We're tagging a new release soon so this will be resolved in a few days. (Sorry for the inconvenience 😓 )

@abhvsn can we add a version check during import?

**Comment by abhvsn** [comment]
@RonaldKools great catch, we are going to add the version check in next release during import as @Nikhil-Nandagopal mentioned.

**Comment by RakshaKShetty** [comment]
This issue will be handled from the UI side the current solution will not work in some scenario
