### ISSUE TITLE
[BUG] Help text is out of the screen for container view.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#652]
## Description
Help text shown on hovering over help button in container box is truncated(out of the screen). 

### Steps to reproduce the behaviour:
1. Add a new Application.
2. Add Container to fully cover the screen.
3. Hover over help text shown in `Container Settings Box`.
4. Text is out of the screen.

[Application Screen](https://drive.google.com/file/d/1RieFxQ3rULUazgSbXot5vIX1mxIk05R5/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by rishavjaiss** [comment]
Hi, can i take this?

**Comment by hetunandu** [comment]
Hey @rishavjaiss! Yes you can take this. Incase you need some help feel free to tag me on this issue and I or someone else from the team will guide you 😃

**Comment by rishavjaiss** [comment]
@hetunandu Hi, I need to know where exactly are the frontend files located in the repo.

**Comment by satbir121** [comment]
@rishavjaiss [here is the file](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/PropertyPane/PropertyHelpLabel.tsx)

**Comment by rishavjaiss** [comment]
@satbir121 ok and how do I clone and start the project on my development environment? npm install and npm start?

**Comment by Nikhil-Nandagopal** [comment]
@rishavjaiss please read our contribution guide. It has all the relevant steps to get started with local development 🙂

**Comment by Nikhil-Nandagopal** [comment]
@rishavjaiss I don't see a PR so I'm unassigning this from you for now. Feel free to claim this once you have time available :)
