### ISSUE TITLE
[Bug] Generate page issue for Google Sheets data source on deploy preview (6301)

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6520]
- [x] #6611
- [x] If there are special characters in the column name then it will be imported has _ in the column name
- [x] When the user selects any one of the rows from the table, that row data is not displayed in the Update row form.

Template Related Issues 
- [ ] #6864
- [x] Trying to enter any value in 'Update row index' is going into a cyclic error
- [x] Table Header Index during data source definition accepts letter 'e' as input
- [x] #6561
- [x] When the default page is created there are some default errors displayed in the debugger section (High importance) 
- [x] Clear data on new row insert form after successful submission

- [x] When the user deletes from the table the deleted value will be displayed until the user manually refresh the page or click on refresh button 

New issues

- [x] #6852
![image](https://user-images.githubusercontent.com/45958978/129700016-ae0bd7de-74c7-4855-b147-975951924f26.png)

- [x] when the user enters the negative number in the "Table Header Index" placeholder the error is overlapped with the column data 
![image](https://user-images.githubusercontent.com/45958978/129699603-f2175410-298e-40eb-9c87-0a4a85dc8af5.png)

- [x] the update form is greyed out when there are some empty rows with few values 
![image](https://user-images.githubusercontent.com/45958978/129699737-06fa8a28-f9cb-45a0-b964-29dc1341c652.png)

**Comment by abhvsn** [comment]
` If there are a special characters in the column name then it will be imported has _ in the column name`
This is how we display the columns with special characters in the table this is not related to the current task.

`When the user selects any on of the row from the table that row data is not displayed in the Update row form`
This is fixed as a part of 6561

**Comment by RakshaKShetty** [comment]
New issues

- [ ] when the user enters the negative number in the "Table Header Index" placeholder the error is overlapped with the column data 
![image](https://user-images.githubusercontent.com/45958978/129699603-f2175410-298e-40eb-9c87-0a4a85dc8af5.png)

- [ ].the update form is greyed out when there are some empty rows with few values 
![image](https://user-images.githubusercontent.com/45958978/129699737-06fa8a28-f9cb-45a0-b964-29dc1341c652.png)

- [ ] When the user enters the input value as "active" and click on update from update form the error is displayed 
![image](https://user-images.githubusercontent.com/45958978/129700016-ae0bd7de-74c7-4855-b147-975951924f26.png)

**Comment by abhvsn** [comment]
I think we have already addressed this issue can we close this @RakshaKShetty
`When the user deletes from the table the deleted value will be displayed until the user manually refresh the page or click on refresh button`

**Comment by ramsaptami** [comment]
@abhvsn tested ok
