### ISSUE TITLE
[Bug]-[100]:Long name of an entity in the entity explorer must be able to display a name on hover

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6524]
Steps to reproduce:
1) Add a JS function
2) Click on the edit icon 
3) Add a long name 
and observe the entity explorer

Observation:
When a long name is added the name of the JS function gets truncated in the entity explorer and the user would not be able to view the entire name 

Expectation:
Since the user is unable to view the entire name of the function, when the user hovers on the name of the function in the entity explorer we can display the name as a tooltip

**Comment by ApekshaBhosale** [comment]
@prapullac can we make this more generic not just for js names. This exists everywhere as of now

**Comment by hordov123** [comment]
@prapullac i would like to work on this issue could you asign it to me?

**Comment by Hanaffi** [comment]
@Rishabh-Rathod Can you assign this to me please?

**Comment by Rishabh-Rathod** [comment]
Sorry for the delay in response. 

@hordov123 Are you still interested to resolve this issue?

If yes i will assign it to you and then you can go ahead with it. 

If not i will go ahead and assign it to @Hanaffi.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 100 |
| Effort (months)  | 0.5 |
