### ISSUE TITLE
[Bug][Deploy Preview] The update fails in s3 generate page when the user tries to update an image for the file which is of a different file type

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6530]
## Description

[What happened] The update fails in s3 generate page when the user tries to update an image for the file which is of a different file type
Neither image nor file name are updated and user cannot change file name during update (feature not allowed)

When user updates a different file type and tries to download, the app crashes and any attempt to open the file fails (second loom video)

### Steps to reproduce the behaviour:
https://www.loom.com/share/07caa849225446f9aed58cc138d3868a
https://www.loom.com/share/2d837a253a0a41d9a01b38c5a0199019

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [chrome]
- Environment [deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty this works perfectly for me. Can you try with 0 files selected by default

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal Didn't get you there, do you mean to try an empty upload?

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami try when there are no files previously selected in the filepicker

**Comment by ramsaptami** [comment]
Saptami Ram is inviting you to a scheduled Zoom meeting.

Topic: [appsmithorg/appsmith] [Bug][Deploy Preview] The update fails in s3
generate page when the user tries to update an image for the file which is
of a different file type (#6530)
Time: Aug 12, 2021 06:30 PM India

Join Zoom Meeting
https://zoom.us/j/94881529861?pwd=ZUUzY1c3Y1RDcDdKTXJqUk9HcE4vZz09

Meeting ID: 948 8152 9861
Passcode: GxaLm6xlOk

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal So if I update an .xlsx with a .png then the thumbnail changes to the image but on download, the file extension and file name remains as .xlsx so the file fails to open. And user is not given an option to change file name during update

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami so that is expected because S3 treats the file name as the identifier to know when to update an existing file and when to add a new file. So the exact name including extension has to remain. I don't think there's a need to replace a file but change it's name, that seems like we should just delete the file and upload a new one.

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal I'm new to S3 so the functionality call is something you'll need to pitch in with. But would a case where user has a **docx** and replaces it with **pdf** so expects to view and download a **pdf** - which can be handled the way you suggested perhaps?
