### ISSUE TITLE
[Bug] Getting Unexpected token { in JSON at position 1 error in console for all the properties of table widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6537]
## Description: When I try to bind table from widget suggestion from query/API screen the error is coming in console

Error: Unexpected token { in JSON at position 1

### Steps to reproduce the behaviour:

1. Go to Datasource
2. Run a query
3. Click on table widget from widget suggestions
4. Observe that now if you make any change in property pane will trow error in console [Like, changing column order, visible, style change]

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6285aac2e93240829c38ca334d42e65d-00001.gif)](https://www.loom.com/share/6285aac2e93240829c38ca334d42e65d)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by AnaghHegde** [comment]
@akash-codemonk Can you please check this ? It doesnt look like it needs to be handled from BE.

**Comment by akash-codemonk** [comment]
While adding the widget a handled error in evaluation is logged to the console. The binding works and there is no crash.
