### ISSUE TITLE
[Enhancement] JS editor : on empty function run the user must be displayed with information 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6539]
Steps to reproduce:
1) Add a Js function
2) Ensure RUN function is displayed to user 
3) Click on RUN 
and observe

Observation:
It is observed that the user will not able to identify if the program ran as we are showing only an empty console

Expectation:
It is expected that an info message can be displayed to user stating the function as ran

**Comment by ApekshaBhosale** [comment]
This is expected if a user is not returning the value we won't be able to show anything. @Nikhil-Nandagopal should we show some message or note?

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale good point. For sync functions this is a nonissue and for async, I think we have a default state to run so this may no longer be needed

**Comment by rohan-arthur** [comment]
@ohansFavour is working on fixing several failing tests
