### ISSUE TITLE
[BUG] Receiving different results on Safari, Firefox with App Link.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#654]
## Description
Created a sample application, deployed it on cloud and opened the provided link on Firefox and Safari.

### Steps to reproduce the behaviour:
1. Create a sample application.
2. Deploy it using deploy button.
3. Copy app link using `View Application` button
4. Open the app link on `Firefox 80.0.1` and `Safari 12.1.2`.

[On Firefox](https://drive.google.com/file/d/14UJEnVbRQufkFN4GLzkYDllnR-ZOQbHq/view?usp=sharing)
[On Safari](https://drive.google.com/file/d/1A-OddDCgl1P18NX2rsVRaUZbZ0qc5rQJ/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by mohanarpit** [comment]
@visibleajay Thanks for opening this issue! 

Can you please give permissions to view the app link on Safari? I'm unable to see the image attached to the issue.

**Comment by visibleajay** [comment]
@mohanarpit Done. 

Kindly let me know if anything is missing.

**Comment by visibleajay** [comment]
App Link wasn't public which threw this error. After making the app-link public, this bug became invalid.
