### ISSUE TITLE
[Feature] Show `Start by adding your first data source` screen for the the newly created application until a widget gets added.

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#6544]
Currently when a user chooses to `Build with Drag & Drop`, we show a an empty canvas with a message "Drag and drop a widget here". Instead of that we should show "Start by adding your first data source" screen. Also providing option to the user to add a widget as well.
![Screenshot 2021-08-11 at 1 41 13 PM](https://user-images.githubusercontent.com/5328605/129139781-8a01e226-8e40-402f-aba7-0fe64f57dfc8.png)

**Comment by marks0351** [comment]
@sbalaji1192 should we just enhance the 'Generate from a Data Table' option coz it actually deals with adding/using data sources. also for users who want to work without data sources this wud be a step more than it usually takes.

**Comment by sbalaji1192** [comment]
@marks0351 Makes sense
Closing this issues as it was created by mistake
