### ISSUE TITLE
[Bug] Property pane action list items are truncated

### ISSUE THREAD

**Issue by susheelgunda** [appsmithorg/appsmith#6548]
Description:

Few  options of "onClick, onTextChanged , onSubmit ..etc" in the drop down of the widget are truncated by default.
This issue might be in other widgets also.

**Actual:**
![image](https://user-images.githubusercontent.com/21009949/129147606-a408143b-a8fe-46a1-8058-0ce521bec92e.png)

**Expected:**
![image](https://user-images.githubusercontent.com/21009949/129148511-4d8482f4-eb38-4031-a19c-be3d8c4eb1e3.png)

**Steps:**

1. - Drag and drop button widget 
2. - Select "onClick" action from the Menu of the button 
3. - Check the list items few of them are truncated

**Details:**

- Version: [Cloud Appsmith v1.5.14-SNAPSHOT ]
- OS: [Win10]
- Browser [chrome]
- Environment [production]

**Comment by SandipPalit** [comment]
I would love to work on this issue. Please assign it to me.

**Comment by Nikhil-Nandagopal** [comment]
@SandipPalit go for it!

**Comment by somangshu** [comment]
@vivekverma2312 can you check if this happening in all the dropdown controls

**Comment by SiddheshShinde-tech** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by aswathkk** [comment]
Closing this since I'm unable to see this issue in production.

**Comment by ramsaptami** [comment]
Reopening this since it's a Windows system specific issue that's still present in production env.
![image](https://user-images.githubusercontent.com/79509062/141826469-3a5d032e-16e0-4c95-b812-fed0ccae6b75.png)
