### ISSUE TITLE
[Bug] Control on Modal should be on button and not the text

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6549]
## Description
When a modal opens up, control is on the text, so user needs to press **Tab** twice to move cursor control to the first button/input field using keyboard functions. Expectation is that cursor control is already on the first button/input box that requires user action. As seen in the video, when user tries to add Google account, the cursor is automatically on the input field

### Steps to reproduce the behaviour:
https://www.loom.com/share/d2e6176129ff4c1bb1949329c1738a37

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

**Comment by somangshu** [comment]
@ramsaptami IMO the example you have compared to has a single purpose where the primary intent of the page is to type an email ID, In our case that might not be true, Keeping input in focus might not be the right thing to do, At least we need a consent from the user, rather something like #4874 makes more sense

**Comment by ramsaptami** [comment]
The example is quite specific, you're right. At the same time #4874 is exactly to what I was trying to explain, for both input as well as buttons (as seen in the _delete_ button action on the recording above). Something like userActionElement.focus() but I was thinking it would be a default function but it makes sense to give user that flexibility to define control position.

**Comment by somangshu** [comment]
Closing in favour of #4874 then. Do re-open if you feel otherwise
