### ISSUE TITLE
[BUG] Duplicate Values in the dropdown.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#655]
## Description
Add dropdown widget to the app screen, update the options to allow to add the duplicate values. Select any duplicate value, both would get selected.

### Steps to reproduce the behaviour:
1. Add dropdown widget to the app screen.
2. update the options to allow to add the duplicate values.
3. Select any duplicate value, both would get selected.

[Duplicate Dropdown Widget](https://drive.google.com/file/d/1S_NMHSrv-UvcJlFwX9C9Cwk3tpd37FyS/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
Let's add a validator for unique options in the dropdown

**Comment by hetunandu** [comment]
**How to solve**

Update the [validator function](https://github.com/appsmithorg/appsmith/blob/6922b9b564fcd4eed24fb44658812b925e5fb1fa/app/client/src/utils/Validators.ts#L349) to also check if all `option.value` are unique. If not, the validator should flag this as invalid.

> Need more guidance while working on a solution for this? Feel free to mention me in a comment on this issue and I'll be happy to help you out 😄

**Comment by Caitlin-Fotheringham** [comment]
Can I pick up this issue?

**Comment by mohanarpit** [comment]
@Caitlin-Fotheringham Welcome to Appsmith! 🎉 

Go for it ! I'm assigned this issue to you. Please try to raise a PR within 2 days. Also, please check our [Contribution Guide](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md) on setting up the project locally.

Feel free to invite your friends to contribute & participate in the [Appsmith Challenge](https://github.com/appsmithorg/appsmith/discussions/863)
