### ISSUE TITLE
[BUG] Filter isEqualTo & notEqualTo aren't working for table filter with id column (integer).

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#656]
### Steps to reproduce the behaviour:
1. Add Table Widget with default values.
2. Apply filter with attribute as `id`, contains, `isEqualTo` & `notEqualTo` is not working.

Expected:- Either the `invalid options` for integer column should be absent or if present than they should filter the table with respect to their usual working.

[Table With Values](https://drive.google.com/file/d/1q9R8FoTs44FvRWOy68c6v-5w9vevVQeW/view?usp=sharing)
[Table with Valid Filter](https://drive.google.com/file/d/1D3U2fSDloOBkg642V7oa3SkzaRGLLol-/view?usp=sharing)
[Table with Invalid Filter](https://drive.google.com/file/d/1IeThCoqnsN_7JCWpSbkYRxV7dM8CI_JJ/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by visibleajay** [comment]
For `orderAmount`, filter `isEqual` and `notEqualTo` are not working.

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon please verify this

**Comment by prapullac** [comment]
Reopening the issue as it is still not functional

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon please fix this
