### ISSUE TITLE
[Feature] Ability to specify the Data Source using javascript

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#6563]
## Summary

It would have been great if there was an option to select the data source associated with the query via javascript.

## Motivation

We have production and development APIs which needs to be authenticated using OAuth2. The only difference between Development and Production APIs is the domain name. One is https://api.example.com/resource and other one is https://api-dev.example.com/resource
If I wanted to make requests to these API resources, I have to create multiple queries for each resource. That could be avoided if it could be managed via javascript.

## Additional Context

![addUser](https://user-images.githubusercontent.com/10436935/129220130-9eaa9090-16ff-4e4d-b285-9423e659c964.png)

I wanted to add users to different environments according to the selection. Each user addition API calls should be made to respective environment domains

**Comment by Nikhil-Nandagopal** [comment]
Hi @Nikhil-Nandagopal 👋 thanks for the feature request. We'll support different environments in our Git Sync Feature. #3199 
This way you can control which branch points to which set of datasources
