### ISSUE TITLE
[Bug]The Minimize icon should be added in response tab so it would be easy  for the user to check the query section and response section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6569]
## Description

[What happened]The minimize icon should be added in the response tab so it would be easy  for the user to check the query section and response section

### Steps to reproduce the behaviour:

1. Go to the datasource section
2.Run the query 
3. Scroll down to the response section
4. verify the display of the response tab

Expected result: the minimize icon should be displayed in the response tab so it would be easy for the user to check the query section and response section
![image](https://user-images.githubusercontent.com/45958978/129300547-a95a4f20-cca8-4dd6-9f9d-39d18c944eaf.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser [ chrome]
- Environment [release]

**Comment by tauantcamargo** [comment]
can i get it? @Pranay105

**Comment by ArslanYM** [comment]
Can I work on this issue?

**Comment by mr-molecule** [comment]
Good day,I am new to this community and possess some experience with Java, but I am not an expert. I am interested in working on this project and would appreciate your guidance on the necessary technologies to learn and any beginner-friendly issues to get started. If you can provide assistance, it would be greatly appreciated and would allow me to make a good start in contributing to this project.

**Comment by REVERB283** [comment]
I've created a MR, can anyone amognst the mainatainers have a look please?

**Comment by REVERB283** [comment]
Is there any update on the MR review, also please can you guys assign it to me?

**Comment by ayushpahwa** [comment]
Closed as solved by [16855](https://github.com/appsmithorg/appsmith/issues/16855)
