### ISSUE TITLE
[Epic] Docked Property Pane

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6576]
## Summary:

We wish to dock the property pane on the right side of the viewport, The docked panes will be resizable, The canvas will scroll underneath them with zoom in/out functionality. Additionally a preview mode will be introduced in the editor.

## Solution:
1. EE and property pane are resizable - to what extent?
2. Allow for canvas scroll underneath the EE and property pane
3. Allow pinning of EE and property pane, which resize the canvas (Not doing this, instead the sub points)
    1. Canvas should rather remain the same size, scroll should be available 
    2. Zoom in / out could solve the problem (keeping the canvas size same)
4. Preview mode will remove all the explorer and only show the canvas 100%, pressing esc will bring the back the preview view 
5. Grab and drag/move the canvas - phase 2
6. The grid size scales to adjust the widget size to remains the same regardless of zooming in or out (W.R.T. canvas size)

## RACI Matrix 

| Attribute | Assignee | 
| ----- | ----- |
| Responsible | @aakashDesign, @jsartisan  | 
| Accountable | @jsartisan  | 
| Consulted | @Nikhil-Nandagopal, @areyabhishek | 
| Informed | @somangshu |

**Comment by Nikhil-Nandagopal** [comment]
@vivekverma2312 thanks for the suggestion! We've heard this many times from our users as well

**Comment by t7c8** [comment]
I'm hopeful this change will come out. It will reduce the friction in editing multiple (or easily obscured) widget properties
