### ISSUE TITLE
[Feature] Dynamo DB: Automatic mapped values

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6581]
A user on discord reports and suggests the following:

BTW - one thing that would make working with dynamodb results much better is if you automatically mapped the values after they are returned. DynamoDB returns this object for each column that has properties "S", "N", "M", etc that depend on the datatype. You then need to edit each column in the table to refer to returnedvalue,.S or returned value.N, It is very annoying. I tried the same thing in retool and they map it for you. The AWS dynamodb API comes with something called the documentclient that does all the mapping for you: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

**Comment by areyabhishek** [comment]
I thought this was already a feature. A good friend had complained about this 6 months ago and ended up using Re tool because of this. @sharat87 @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
Yeah this was supposed to have been fixed. I remember it going out! @sharat87 @sumitsum ?

**Comment by sumitsum** [comment]
Yes, this was fixed earlier. I will ask the user to share their response to see it there is some use case that got missed.

**Comment by sumitsum** [comment]
> Yes, this was fixed earlier. I have asked the user on discord to share their response to see it there is some use case that got missed. https://discord.com/channels/725602949748752515/760761686549463060/875636087152844820

Got response from the user. Looks like some use case is missing. https://discord.com/channels/725602949748752515/760761686549463060/875740785318952960

**Comment by sumitsum** [comment]
I am investigating this issue.
