### ISSUE TITLE
[Bug] Comment and thread deletion doesn't happen in realtime for concurrent users

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#6586]
## Description
Comment and thread deletion doesn't happen in realtime for concurrent users

### Steps to reproduce the behaviour:
1. Create an app and invite another user
2. Open the editor as the other user
3. Add a couple of comments on a new thread
4. Delete a comment: observe the comment doesn't get deleted for the other user
5. Delete a thread: observe the thread doesn't get deleted for the other user

**Comment by nayan-rafiq** [comment]
Backend changes for this is done in this PR: https://github.com/appsmithorg/appsmith/pull/6542
