### ISSUE TITLE
[Bug] iFrame - On url change when page navigation is set the page navigates to the page 2 when ever user navigates to the original page

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6587]
## Description
iFrame - It is observed that when the page navigation is set to page 2 on url change. And whenever the user navigates to original page the page automatically navigates to page 2

Expected result:
User should navigate to page 2 whenever there is a change in the url 

### Steps to reproduce the behaviour:

1. Drag and drop iframe in page 1
2. Create page 2 and copy the page 2 url
3. Navigate to page 1 and click on iframe 
4. Set page navigate - on url changed 
5. Pass the page 2 url in the page navigate field 
6. Modify the source url 
7. observe user will be navigated to page 2
8. Now open page 1 and observe 

**Videolink:**
https://loom.com/share/f6f5af614dff4b4b86947cf7aac03c35

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [release, release frozen]

**Comment by somangshu** [comment]
The Navigate here should happen on a new tab here, Hence the action will not result in a dead loop like this

**Comment by somangshu** [comment]
This will be taken care by the action and not the widget

**Comment by Nikhil-Nandagopal** [comment]
@somangshu actually this is a problem with the iframe. The issue is that the widget is triggering the action even onPageLoad not only when the URL changes.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal that dosent matter I think. I can still use the navigate to action with a condition to create a similar dead loop. According to me the solution here should be navigate to new tab by default. And explicit change to open in the same tab.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu that can always be there especially with JS action, a user can configure a JS action to loop between pages.
Changing the default behavior of navigateTo is not a good solution because most cases, developers expect navigateTo to take their users to another page and not to open another page.
The problem here is that even though the configuration is correct, the behaviour is unexpected

**Comment by somangshu** [comment]
Ok, Though I dont agree to the assumption that the user expects to navigate to another page and not open a new tab. In favour of the above issue we will not let the onURLChanged event fire on page load. Post that the action will function normally.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu I'm only saying this because the default behavior for anchor tags and router navigation is like this
