### ISSUE TITLE
[Enhancement] Comment/Edit view must exit on clicking enabled Comment Mode/Edit Mode icon

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6600]
## Summary
Clicking on Comment Mode icon when comment mode is enabled must close comment pane. Same to be applied to Edit mode as well.

Functionality should be similar to what happens when user clicks on the Help icon.

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami the comment/edit modes are toggles of each other so they do not work like the help icon. A user must be in either of these modes so this isn't valid

**Comment by ramsaptami** [comment]
But we have the page tree in the same position right? So display can be comment mode, edit and page tree and considering there are dedicated buttons wouldn't you say there's a certain expectation from the user to collapse these panes on second click?

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami I didn't quite understand this. The display can be comment mode / edit mode. What is page tree? Is it the entity explorer? It shows in the edit mode. It's not an expand / collapse interaction because the modes are not optional. You must be in edit / comment mode so unselecting edit / comment mode doesn't make sense right?

**Comment by ramsaptami** [comment]
My bad on the jargon there, but yeah I mean the entity explorer. So in this case, correct me if I'm wrong here, the modes are just displays that user can toggle between is that right? (3 display options being entity explorer, edit and comment)

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami yes but there are only 2 options. Edit and Comment. Entity explorer is available in edit mode
