### ISSUE TITLE
[Bug] App name is not appended with '1' when imported the first time

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6602]
## Description
When app is imported and system detects another app of the same name, it appends **#<number>** but this does not happen for the first instance.

### Steps to reproduce the behaviour:
1. Export an app and import it back to the same organization.
2. Observe the name of the app - it's **<name> #<number>**. But for the first duplicate, number one **(1)** is missing
3. For consequent imports, system detects duplicates and numbers it correctly as <name> # 2, # 3 and so on.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: RC

![image](https://user-images.githubusercontent.com/79509062/129357890-0fc3c1cc-cdea-4a05-92c6-0ac1beabbbd7.png)

**Comment by abhvsn** [comment]
Closing this as already resolved
