### ISSUE TITLE
[Bug]-[200]:Control does not move to list widget when it's added from new nav feature

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6604]
## Description
Navigation does not automatically move to the newly added list widget from new nav feature on a long page as is the case with other widgets

### Steps to reproduce the behaviour:
1. Drag and drop widgets on to the canvas so the page is a long one
2. Go to a data source and run a query to populate widget suggestions on new nav.
3. Select list widget from the options and observe the navigation control remain on the top of the page.
4. Repeat # 3 with a table widget and observe navigation control move to the newly added widget

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: RC

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 0.5 |

**Comment by abhishektiwari47** [comment]
Is someone working on this

**Comment by ramsaptami** [comment]
You can pick it up @abhishektiwari47

**Comment by ashishkumar-ldp** [comment]
Hi all,
Just wanted to ask, if the above issue still exists or not. I tried to follow the steps to reproduce but I didn't notice anything off with UI.
Here is loom video of my try: https://www.loom.com/share/7854179b262441d5a551d9e2383fe802?sid=880e0aa9-8a87-4b1b-933a-f6453a58f30a

**Comment by rohan-arthur** [comment]
not reproducible anymore
