### ISSUE TITLE
[Bug] Snowflake - Authentication token has expired. The user must authenticate again.

### ISSUE THREAD

**Issue by DerrickMChan** [appsmithorg/appsmith#6607]
## Description

After leaving the application overnight and coming back to it the next day, the authentication token for the Snowflake connection expired and I cannot find a way to re-authenticate the connection.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a new data source with a connection to Snowflake
2. Use connection in a table
3. Wait until the authentication token expires
4. Refresh the application
4. See error when the table tries to connect to Snowflake to refresh

### Important Details

- Version: Cloud
- Windows
- Chrome
- Production

**Comment by Nikhil-Nandagopal** [comment]
@DerrickMChan Thanks for the bug report! We'll look into this and get back to you

**Comment by DerrickMChan** [comment]
The issue isn't that there is no error message.  An error message does come up, however the query does not automatically refresh the authentication token leading to the error.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair can you confirm whether this will auto refresh the token?

**Comment by DerrickMChan** [comment]
I am still receiving the error as of this morning, please see below.

![image](https://user-images.githubusercontent.com/33213314/129592043-e4922a47-ae59-470f-97f9-93323a2964a7.png)

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal, yes I was able to replicate this error exactly and the fix is to reset the connection to the database when the token expires.

@DerrickMChan thanks for keeping tabs on this issue so diligently! The fix is currently in our release environment and will go into production with the next release. I'll drop a message here when that happens. :)

**Comment by shubham-maurya** [comment]
hi @nidhi-nair, do we know when this is going out? facing the same issue. thanks!

**Comment by somangshu** [comment]
👋  @shubham-maurya, thanks for reaching out. We are tagging the current release this should be done by EOD. Shall keep you posted in case there is a delay.

**Comment by nidhi-nair** [comment]
@DerrickMChan @shubham-maurya this change should be available on your installation now!

**Comment by shubham-maurya** [comment]
Thanks @nidhi-nair ! You guys are fast :)
