### ISSUE TITLE
[Enhancement] Select widget and other popups should be the size of the parent

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6609]
## Summary

The popup for a widget should be the size of the parent until the parent width is above the min width of the popup

**Comment by somangshu** [comment]
We need to find out all use cases for this @vivekverma2312

**Comment by Tooluloope** [comment]
@Nikhil-Nandagopal @somangshu can I get the other Popups apart from Select Wiget.

From Menu Button, is it ideal?
![Screenshot 2021-09-15 at 13 14 39](https://user-images.githubusercontent.com/31691737/133431504-560f75ef-b7c3-4d06-954c-a951b0af0d32.png)

**Comment by somangshu** [comment]
Yes of course, remember the popups by default need to have a min width set and otherwise should always inherite the parent widget width
