### ISSUE TITLE
[BUG] Missing Id value for custom radio button in RadioGroup

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#661]
## Description
On adding custom radio button, the `id` value which is present for default radio button isn't getting added for the custom radio button.

### Steps to reproduce the behaviour:
1. Add Radio Group.
2. Delete the Second radio button option.
3. Add it manually using provided input box.
4. Check JSON schema for the same value.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/MDhPvLG/Input-Box.png" alt="Input-Box" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/mNWcQY6/JSON-Schema.png" alt="JSON-Schema" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by hetunandu** [comment]
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone looking to start contributing to the repo.

The issue arises from the confusion of new options not created with id field in the options. In actuality, the id field is not needed at all, but some old config still has the id field.

You can contribute by just removing the id field in the default options config [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/mockResponses/WidgetConfigResponse.tsx#L158)

> Need more guidance while working on this? Feel free to mention me in a comment on this issue and I'll be happy to help you out 😄

**Comment by Jain-Sanchit** [comment]
@hetunandu  I want to start contributing to this repo and I found it interesting  , there are a lot of things to contribute to . Can i take this up ? Can you assign me .

**Comment by hetunandu** [comment]
Hey @Jain-Sanchit, welcome to Appsmith! Happy to so excited about contributing here 😄

I have assigned this issue to you. Make sure you raise a PR within 2 days. You should also tag your friends in the PR to get a chance to win extra hacktober fest goodies from Appsmith. Read our hacktober fest [discussion](https://github.com/appsmithorg/appsmith/discussions/863) for more details

**Comment by Jain-Sanchit** [comment]
@hetunandu  Sure Sir , I will try to raise a PR within time and will share this with friends.
