### ISSUE TITLE
[Bug] Keeping table filter pane open and dragging and dropping any of the widgets to the canvas the app crashes 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6615]
## Description
Release frozen - It is observed that when the user keeps the table filter open and drags and drops any other widgets to the canvas the app crashes

Expected result:
App should not crash and dragging and dropping any of the widgets to canvas when table filter is open

### Steps to reproduce the behaviour:

1.Launch appsmith on release frozen environment 
2.Drag and drop table widget 
3.Open table filter pane
4. Drag and drop any other widget an observe

**Videolink:**
https://loom.com/share/8596d3c828b44b00b2374d1d9fc2289a

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur ]
- Browser [chrome, safari]
- Environment [release frozen]

**Comment by somangshu** [comment]
@vibhandikyash Please triage this to see if the issue is related to the table widget filter change

**Comment by vibhandikyash** [comment]
@somangshu  Yes, It is related to table widget filter
