### ISSUE TITLE
[Bug]The copy icon is not working in on-boarding tour mission 3 popup

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6617]
## Description

[What happened]The copy icon is not working in on-boarding tour mission 3

### Steps to reproduce the behaviour:

1.Clik on welcome tour from Application page 
2.click on the Start building button
3.On mission 1 pop up click on do it for me 
4.inside the mission 3 pop up click on copy snippet 
5.The user is not able to copy 

https://loom.com/share/d59ba843b66e4894842694d959ec3cac

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [chrome]
- Environment [release frozen]

**Comment by akash-codemonk** [comment]
@RakshaKShetty Is this still happening? Seems to work fine on release and prod.

**Comment by Nikhil-Nandagopal** [comment]
Working for me too @RakshaKShetty can you repro it
