### ISSUE TITLE
[Feature] - Add unit tests for RTS

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#6626]
## Summary

We don't have unit tests for RTS now. Need to add automated tests for RTS.
Our RTS is a tiny project based on socket-io and nodejs.

## Motivation

Automated unit tests and integration tests will make sure the RTS will not fail after new changes.

## Additional Context

Socket-IO has some guide on how to write tests https://socket.io/docs/v4/testing/

**Comment by KechengZhang28** [comment]
Can I work on this?
