### ISSUE TITLE
[Feature] add sidebar widget

### ISSUE THREAD

**Issue by nimbus10** [appsmithorg/appsmith#6642]
Hi, do you  have any plan of adding sidebar widget?

when i manage business platform with appsmith, there are too many pages to manage. i think it will be much more convenient if i can use sidebar widget. unfortunately ,i can only use selectmenu instead.

**Comment by Nikhil-Nandagopal** [comment]
Hi @nimbus10 👋 we do have plans to introduce this. We have a similar request here #2282
