### ISSUE TITLE
[Bug] [Release] Reset button in Form widget is only visible when I hover on the button

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6658]
https://www.loom.com/share/508d856e11b443b7b661edb768ee73f1

Issue is observed only on release environment

**Comment by ohansFavour** [comment]
@vivekverma2312 this has been fixed and merged (https://github.com/appsmithorg/appsmith/pull/6660)

**Comment by vivekverma2312** [comment]
@ohansFavour Tested this on release and working fine.
