### ISSUE TITLE
[Bug] Get Requests don't work with a body field

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6668]
## Description
A user is trying to integrate with the below API but our API assumes body fields are not valid for GET requests
https://api.seatable.io/#65efccf8-1b3e-49a1-aeed-9df75dcadca9
### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by dantosXD** [comment]
Are there any workarounds you can maybe suggest? I would rather not switch database services if I do not have to,

**Comment by Nikhil-Nandagopal** [comment]
@dantosXD we're working on this. We should have a PR soon! Thanks for bringing this up again :)
