### ISSUE TITLE
[BUG] Input Widget - Default text isn't taken into account if placeholder is set.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#667]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, click on 'Create New' in order to create a new application
3. Edit Application
4. From the Form Widgets, pick Input
5. Set Data type as 'text', Default text as 'AA' and Placeholder as 'BB'
6. Change the data type to 'password' and again back to 'text'

Expected Result: When Data type is set to 'Text', default text should be visible.
Actual Result : When Data type is set to 'Text', Placeholder text is visible.https://drive.google.com/drive/folders/1Ye_nwtHOnoD6HS2lM6bnSSsURm7V5VDx?usp=sharing

Attachment : https://drive.google.com/drive/folders/1Ye_nwtHOnoD6HS2lM6bnSSsURm7V5VDx?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 in the video, you are manually deleting the AA from the text and then changing the password so the default was overriden by user input. Doesn't seem valid. Please re-open this if I am missing something here
