### ISSUE TITLE
[Bug]The user cant bind data in the input widget  if the column name are numeric 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6671]
## Description

[What happened]The user cant bind data in the input widget  if the column name are numeric 

### Steps to reproduce the behavior:

1.Generate a page using google sheet
2.Select a sheet that has a numeric value as its column name 
3.now very the display of the autogenerated template
![image](https://user-images.githubusercontent.com/45958978/129841280-867da1ab-d04c-4e3b-8c60-05f5f3df46e9.png)
If the column names are numeric then that value is not displayed in the autosuggest
![image](https://user-images.githubusercontent.com/45958978/129841360-5dfb7452-9ac0-46bc-b24a-bd7eb3c9540d.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [chrome]
- Environment [ deploy preview->6301]

**Comment by somangshu** [comment]
Good Find @RakshaKShetty. The issue is not with the table widget or google sheets plugin. its to do with evaluations. I am guessing this is a limitation. @hetunandu please shed some light on this. Is this a deliberate move? Is this hard to fix?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu I would actually argue that it is with the table widget because 24 is an invalid variable name in JS (cannot start with numbers). So the table needs to sanitize it (maybe add an underscore?)

**Comment by sbalaji1192** [comment]
@techbhavin I had removed the migrations you wrote for this issue, in order to resolve a critical issue where we were resetting the custom column name - https://github.com/appsmithorg/appsmith/pull/10218. so reopening this issue to fix the migration function to rewrite numerical column names for existing application.
CC: @somangshu

**Comment by somangshu** [comment]
We should resolve this quickly, Please gather the information required here @techbhavin and implement this soon
