### ISSUE TITLE
[Bug] Deploy Preview - The columns and the operators are not selectable in the table filter pane

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6673]
## Description
Deploy Preview - https://deploy-preview-6662--appsmith-editor-ce.netlify.app/applications
It is observed that in the table filter pane the columns and operators are not selectable 

**Expected Result:**
User should be able to select columns and operators in the table filter pane

### Steps to reproduce the behaviour:
1. Launch appsmith app in the deploy preview https://deploy-preview-6662--appsmith-editor-ce.netlify.app/applications
2. Drag and drop table widget 
3. open filter pane 
4. Try to select columns and operators in the filter pane and observe

**videolink:**
https://loom.com/share/b9a9f71192c644d5b9ed83a044b883f1

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [deploy preview]

**Comment by somangshu** [comment]
This is a regression caused by the table widget visible property changes in #4819, @Tooluloope your changes should not effect the table widget filter pane columns

**Comment by somangshu** [comment]
@vivekverma2312 please test the table widget visible and disable functionality developed before as well

**Comment by vivekverma2312** [comment]
Removing Hotfix label as this issue is only on release and not on prod.
