### ISSUE TITLE
[Bug] On creating a new JS object before saving the last edited navigates to new JS object

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6679]
Steps to reproduce:
1) Add a JS object1 
2) Add a line into this 
3) Add a  JS object2
and observed

Observation:
It is observed that when the data edited on JS object 1 is not saved before JS object2 is created 

Expectation :
It is expected that the data edited on the JS object must be saved even when a new JS object is created 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/353975740b144ea0a501da981cce8710-00001.gif)](https://www.loom.com/share/353975740b144ea0a501da981cce8710)

**Comment by ApekshaBhosale** [comment]
Implementation is going to change to save body and actions seprately.

**Comment by prapullac** [comment]
Closing the issue as it is working as expected
