### ISSUE TITLE
[BUG] Duplicate value in RadioGroup widget.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#668]
## Description
Duplicate objects are allowed in RadioGroup Widget. No concept of `Primary Key` either.

### Steps to reproduce the behaviour:
1. Add RadioGroup Widget.
2. Duplicate the default value using JSON object and save.
3. Selection of all values are allowed.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/yWtK41Y/Duplicate-Radio-Group-Values.png" alt="Duplicate-Radio-Group-Values" border="0"></a>
<a href="https://ibb.co/HDTXGmz"><img src="https://i.ibb.co/d047kn2/JSON-Schema.png" alt="JSON-Schema" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
Let's add a unique validator for Radio Widget

**Comment by hetunandu** [comment]
Closing in favour of #655 as they share the same validator
