### ISSUE TITLE
[Bug] Color picker on Container widget blocks input for user

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6683]
## Description
Colour picker on container widget blocks input for user if user is trying to enter their own colour code.

### Steps to reproduce the behaviour:
1. Drag and drop container widget on to canvas
2. Click on background colour input box to input you're own colour code - colour picker pops up and blocks input field

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

![image](https://user-images.githubusercontent.com/79509062/129867458-ffc438c0-d961-4d41-8544-3d955fc980f1.png)

**Comment by somangshu** [comment]
Closing this in favour of #4413
