### ISSUE TITLE
[Bug] Deploy Preview - Adding label text 'Enter your Phone number' and tooltip text 'Phone number' and entered phone number is not visible completely 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6685]
## Description
Deploy Preview - https://deploy-preview-5256--appsmith-editor-ce.netlify.app/applications
It is observed that on Adding label text 'Enter your Phone number' and tooltip text 'Phone number' and entered phone number is not visible completely - This is for older inout widgets

Expected Result:
When the label character size is increased either the inout widget should have scroll bar or the input widget size should increase automatically 

### Steps to reproduce the behaviour:

1. Launch Appsmith app in the deploy preview -https://deploy-preview-5256--appsmith-editor-ce.netlify.app/applications
2. Open any existing app which has input widget of type phone number 
3. Enter phone number as input value 
4. Enter label text as 'Please enter phone number'
5. Enter tool tip text as 'Phone number' and observe the phone number value is not visible completely 

**VideoLink:**
https://loom.com/share/a4736e373ef04a7d969c01b56fc9c04c

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [deploy preview]

**Comment by somangshu** [comment]
If there is no space available what is expected @YogeshJayaseelan? Two things:
- Resizing solves this.
- Input cursor on the end of the value makes is visible. 

Otherwise below the min width the widget starts to overflow outside the boundaries. We are still debating internally if we want to change that to scroll inside the container boundary, Which IMO is still not a good solve considering responsiveness

**Comment by krishguptadev** [comment]
Can I work on this? Should I resize it or make the input cursor on the end?

**Comment by ashish921998** [comment]
@somangshu @Pranay105 Can I work on this issue?

**Comment by somangshu** [comment]
@krishguptadev @ashish921998 this issue is more involved and needs to be thought off properly before getting picked up, We are still discussing this internally. 

Kindly look into issues under the hacktoberfest label to find more issues that might interest you. Happy hacking :)

**Comment by somangshu** [comment]
#7215 is related
