### ISSUE TITLE
[Bug] Deploy Preview - The input widget of type phone number is not accurate when placed inside form widget and when moved out of form widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6686]
## Description 
Deploy Preview - https://deploy-preview-5256--appsmith-editor-ce.netlify.app/applications
It is-observed that on Adding label 'enter your phone number' and tooltip text 'Phone Number' and adding valid inputs to phone number field and moving it inside form widget the input widget outline size is not accurate and vice vera when the user expands the input widget size inside form widget and drags the input widget outside the form widget again the size is not accurate

Expected Result:
Inout widget of type phone number widget size should be appropriate when moved in and out of form widget 

### Steps to reproduce the behaviour:

1. Launch Appmsith app in deploy preview - https://deploy-preview-5256--appsmith-editor-ce.netlify.app/applications
2. Drag and drop input widget 
3. Change type to phone
4. Choose country as india and enter valid phone number 
5. Enter label text as 'Enter your phone number' and Tooltip text as 'Phone number'
6. place the above input phone number widget inside form and observe the input widget outline
7. Inside the form - increase the inout widget outline to correct size and move the widget outside form widget and observe 

**videolink:**
https://loom.com/share/fe3220fa07e74f488faab3524e1384f7

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [Chrome, safari]
- Environment [deploy preview]

**Comment by somangshu** [comment]
Closing this as its the default behaviour from bringing default widgets into containers
