### ISSUE TITLE
[BUG] Input Widget : Problem with 'File name with extension' and type

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#669]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, click on 'Create New' in order to create a new application
3. Edit Application
4. From the Form Widgets, pick Input
5. onTextChanged, select 'download'

Actual Result: If 'File name' is put with extension, 'type' is ignored. Type is only taken into consideration when file name is put without extension. When File name is a.txt and type is csv, it becomes contradictory. 

Attachment: https://drive.google.com/drive/folders/1xmmw9wYNUlKyLMuokyUH8j7wQMOLu0zD?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you clarify this? Looks like a bug where there should only be a filename and we should populate the extension

**Comment by Nikhil-Nandagopal** [comment]
Closing since the second parameter is the mime type and is independent of the extension
