### ISSUE TITLE
[Bug] Tab key control does not move to a dropdown value hence user cannot change value using keyboard 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6691]
## Description
When using **Tab** key to move control through the property pane, control does not move inside of a dropdown hence user is unable to make a selection using keys

### Steps to reproduce the behaviour:
1. Drag and drop a text widget on to the canvas
2.  Use **tab** key to move control on the property pane of the widget and observe that control does not move to dropdown property

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

**Comment by somangshu** [comment]
The problem here is that the focus styling is not available on the select widget, If the selection shows up properly our problem is solved

**Comment by somangshu** [comment]
removing this from goodfirst because this is a core control component and we need to be careful here

**Comment by ramsaptami** [comment]
Reopening this since tab control works only limitedly. Using keys on trigger fields does not work as expected
https://www.loom.com/share/3eb4999664354081a140cab8108f2f52

**Comment by aswathkk** [comment]
@ramsaptami That is being tracked on #9920
