### ISSUE TITLE
[Bug] New auth on google sheet is failing, not redirecting to new query page

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6695]
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/42d98ecf143d4160b8acf6f562109cdd-00001.gif)](https://www.loom.com/share/42d98ecf143d4160b8acf6f562109cdd)

- Version: Cloud 
- OS: MacOSX
- Browser chrome
- Environment : production

**Comment by nidhi-nair** [comment]
Cloud services had not been promoted in a while, doing so has fixed this.
