### ISSUE TITLE
[Bug] Unable to see query results in query editor pane

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#6699]
<img width="1536" alt="Screenshot 2021-08-18 at 7 17 27 PM" src="https://user-images.githubusercontent.com/5298848/129911182-887632d8-c1dc-4322-bcef-ad8502461361.png">
<img width="1536" alt="Screenshot 2021-08-18 at 7 21 43 PM" src="https://user-images.githubusercontent.com/5298848/129911208-06495d13-5db8-4db4-a692-e1f5f0c28d32.png">

**Comment by somangshu** [comment]
@vivekverma2312 please verify

**Comment by vivekverma2312** [comment]
Removing Hotfix label as this issue is only on release and not on prod.
