### ISSUE TITLE
[BUG] Dropdown widget: Issues with Required JS

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#670]
Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, click on 'Create New' in order to create a new application
3. Edit Application
4. From the Form Widgets, pick Dropdown widget

Scenario 1 : In Selection Type, choose 'Single Select',  Required JS : disabled
Issue : Once a value is selected, user doesn't have an option to not have any value in the widget. (Even though Required JS is disabled)

Scenario 2: In Selection Type, choose 'Multi Select',  Required JS : Enabled
Issue: User can keep no value in the widget. (Even though Required JS is enabled)

Attachments : https://drive.google.com/drive/folders/1aXYRXU8pvhw09yPqr-eq-ZvFyer3WN8j?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 if no default value is specified, it will have no option selected.
Also required option is only for disabling the form button when the dropdown is in the form
