### ISSUE TITLE
[Bug]Delete functionality is not working under the multi-part section in API

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6711]
## Description

[What happened]unable to delete key-value pair in the multipart body in API Pane 

### Steps to reproduce the behavior:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e2dfd10a50004c7487062c7cfcba28a7-00001.gif)](https://www.loom.com/share/e2dfd10a50004c7487062c7cfcba28a7)

### Important Details

- Version: [Cloud]
- OS: [MacOS]
- Browser [chrome]
- Environment [release]

**Comment by nidhi-nair** [comment]
Duplicate of #6694
