### ISSUE TITLE
[Bug]Clicking on the debug from the evaluated pane should open the error tab and scroll to the particular error when there are multiple errors 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6715]
## Description

[What happened]Clicking on the debug from the evaluated pane should open the error tab and scroll to the particular error when there are multiple errors 

### Steps to reproduce the behaviour:

1. Go to canvas
2. drag and drop the map widget
3. open the property pane
3. make some error
4. now drag and drop the input box
5. open the property pane made some error
6. hover on the error and click on debug button from the evaluated tab 
7. verify the functionality

The user should navigate to the correct error when there are multiple errors in the debbuger

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6f012a45a5324d039a86a03bc83b0e28-00001.gif)](https://www.loom.com/share/6f012a45a5324d039a86a03bc83b0e28)
### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [ chrome]
- Environment [prelease]

**Comment by akash-codemonk** [comment]
@RakshaKShetty I think a better fix would be to show the most recent error at the top. Doing this.
