### ISSUE TITLE
[Bug]Import application fails

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#6718]
Steps:

1. Import application fails.
2. POST call fails 

<img width="1044" alt="Screenshot 2021-08-18 at 11 30 24 PM" src="https://user-images.githubusercontent.com/67676905/130025987-f93da934-1d22-4720-b18a-90ef421c851b.png">
<img width="1278" alt="Screenshot 2021-08-18 at 11 58 37 PM" src="https://user-images.githubusercontent.com/67676905/130026006-f9dbc893-261d-4ced-8ca3-20665049784f.png">

**Comment by pranavkanade** [comment]
This has been fix with - https://github.com/appsmithorg/appsmith/pull/6767
