### ISSUE TITLE
[BUG] Map Widget throws error after redeploying the app with changes.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#672]
[Video In Action](https://drive.google.com/file/d/17qAUiLNxEYgKT9-gAqwACcP3Hiv2HqOh/view)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay the video is not available anymore, can you directly paste a video here or update with the steps so I can verify this?

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay thanks for the updated video, updating the issue

**Comment by prapullac** [comment]
Verified the issue and works as expected
