### ISSUE TITLE
[Bug] Number input field can't be selected on Firefox

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#6723]
## Description

The number in an input field set to Number DataType cannot be selected. _This happens for me on the Appsmith release server, using FireFox_. In Chrome the widget works as expected.

### Steps to reproduce the behaviour:

1. Create a new app
2. Add an input widget to the page
3. Set the DataType to Number
4. Double click on the "0" in the field to select it. It won't be selected
5. Drag across the "0" to select it. It won't be selected

### Important Details

This issue only happens in edit mode, in deployed mode the input works.

- Version: https://release.app.appsmith.com
- OS: Linux Mint 19
- Browser FireFox 89.0.2
- Environment: release (I guess)

**Comment by Nikhil-Nandagopal** [comment]
@zzgvh thank you for the bug report! @vivekverma2312 can you verify this?

**Comment by vivekverma2312** [comment]
@somangshu Able to reproduce on Firefox in edit mode. Working fine in chrome and safari.
