### ISSUE TITLE
[Bug] Download action doesn't work well

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#6730]
## Description

Related https://github.com/appsmithorg/appsmith/issues/3027, https://github.com/appsmithorg/appsmith/issues/3559, https://github.com/appsmithorg/appsmith/issues/4262, https://github.com/appsmithorg/appsmith/issues/4283

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by ajinkyakulkarni** [comment]
@sumitsum @hetunandu Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6730?planning-poker)

**Comment by sumitsum** [comment]
My SP estimate is 8 but max 3 can be voted for planning poker.

**Comment by hetunandu** [comment]
Let's close this one. I have added the other into this milestone since they already are broken apart
