### ISSUE TITLE
[Bug] this.params shows an error in IIFE

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#6732]
### Steps to reproduce the behaviour:

1. Create an API
2. Create a new parameter that has an IIFE which returns a value from `this.params`
`(function() { return this.params.name })()` (also test with arrow function)
3. TypeError: cannot read params of undefined
![image](https://user-images.githubusercontent.com/66776129/148975021-0dc7479d-62fc-4b40-9279-a62cc2f27777.png)

Note: When a param is passed @`Api.run({ name: "abcd" })`, it is successfully passed to the server.

**Comment by ajinkyakulkarni** [comment]
@sumitsum @hetunandu Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6732?planning-poker)

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk why did we revert this fix?

**Comment by eco-monk** [comment]
A user WazirX's apps were broken. cc: @mohanarpit 
Wherever they used normal function as IIFE.

![image](https://user-images.githubusercontent.com/66776129/152489768-1aba31a6-5791-43d5-a7ae-a87aac2cb43b.png)

---

The changes will be brought back with the workaround.
https://github.com/appsmithorg/appsmith/pull/10826

Once merged, using arrow functions / optional chaining will help with this error.

**Comment by eco-monk** [comment]
Todo: need to deprecate normal IIFE function, since we have to do string replacement in out code for this to work

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk what do you mean by deprecate IIFE? That sounds dangerous
