### ISSUE TITLE
[Enhancement] The storeValue seems hacky way to set value

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#6733]
## Description

StoreValue is a very important asset but feels like a lot of our users have build a perspective of storeValue being a hacky way to do data binding. 

Introduce a setState function and document the storeValue better. Also update the documentation.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by ajinkyakulkarni** [comment]
@sumitsum @hetunandu Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6733?planning-poker)

**Comment by sumitsum** [comment]
My sp estimate is 4 .... but only 3 is provided as max.

**Comment by ajinkyakulkarni** [comment]
Another issue related to storeValue https://github.com/appsmithorg/appsmith/issues/6727

**Comment by rohan-arthur** [comment]
@ajinkyakulkarni would you please share more information about this enhancement idea? What is the problem and proposed solution?
