### ISSUE TITLE
[Bug][deploy preview]signposting issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6736]
- [x] When the user takes the welcome tour and click on the last step the "My first application" app gets deployed and the page is displayed empty->**fixed**
- [x] when the user takes onboarding the stand-up app fails only the edit mode works and deploy mode is failed->**fixed**
- [x] when a user tries to connect to the datasource if the user selects the mock data the internal server error is displayed-->**Fixed**
- [x] If the user clicks on the anyone data source and then try to change it without connecting to first one the flow breaks
- [ ] after data sources get added the welcome pop up  is not displayed
- [x] the text should be “Create datasource” instead of  "add datasource
- [x] progress bar component filling should be orange when the user is on canvas->**Fixed**
- [ ] Till the user creates a query “create a query” text should be displayed in the progress bar instead of Add a widget->**this is a requirement once user click on new query button the progress bar changes**
- [ ] After the user run a query there is no pop up so it feels like the flow is broken ->**This is a requirement not an issue** 
- [ ] when the user navigates to the canvas the text “Drag and drop a widget here” should be displayed bit bold 

Changes requested my nikhil:

- [x] When a user clicks add widget, we should open the widget pane too->**Fixed**
- [x] The checklist section can be entirely made clickable instead of only the > arrow->**Fixed**
- [x] Back to canvas should just be Back and follow the same style as the back button everywhere in the app->**Fixed**
- [x] I don't know when but randomly the checklist in the entity explorer becomes orange. I have no idea when this is supposed to happen or what it means.
- [ ] The x to stop the checklist was quite unexpected. I accidentally clicked on it and it just stopped
- [x] When the widget pane is open, the checklist is not seen so there's no feedback when I add a widget
- [ ] Clicking connect data to widgets doesn't really help me do anything. Can we give users some information here like open the omnibar?

- [ ] After dropping a widget the connect data to widgets option is showing, but this should only show if the user has added a query
- [ ] Deploy applications should not be plural
- [ ] The sniping mode is not working for a chart for some reason

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser  chrome
- Environment [ deploy preview]
DP:https://deploy-preview-6599--appsmith-editor-ce.netlify.app/applications

**Comment by RakshaKShetty** [comment]
#4963

**Comment by RakshaKShetty** [comment]
Adding New issue for DP(7089)->

- [ ] ”Here is how appsmith works” page is not displayed when the user login for the first time
- [ ] In the "Add widget text “ The "A" should be Lower case
- [ ] When we add a new page The Add datasource page is not displayed at first instance it displayed Generate page Ui then when the user switches between the pages the Add datasource page is displayed
- [ ]  When a user is asked to "Create a query” in the progress bar the text is displayed as “ Add a query” the text should be consistent
- [ ] In a next Create a Query page “add a widgets” text is displayed as Add Widgets”
- [ ] In Datasources page under generate application section There is bit more space between text Generate Application text
- [ ] Inside the Checklist page "Not sure where to start? Take the welcome tour” Link is not displayed 
- [ ] After successful exploration inside the “ Welcome Appsmith” checklist page the Last step “Deploy application seems to be broken 
- [ ] The test should be "0 of 5 complete” instead of "0 of 5 completed”
- [ ] Inside the checklist page the button name should be “Connect datasource” Instead of "Create a Datasource”
- [ ] In a Add widget window “ the link should be "Alternatively you can also share your application” instead of "Alternatively you can also Deploy your applications.”
- [ ] When user sign-out in between and come back click on widget name under widget in entity explorer the widget pane is not opened
- [ ] If the user click on generate page button the flow looks like broken the progress bar is not displayed

**Comment by sbalaji1192** [comment]
Closing this as fixes have been merged to release as part of https://app.zenhub.com/workspace/o/appsmithorg/appsmith/issues/4057
