### ISSUE TITLE
[Feature] Multiple file uploads are very messy

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#6737]
## Description

Multiple file uploading needs a job queue in frontend and might needs to be separated from single file upload. As it might need to load another JS queue library. Can't see what files were successfully uploaded

### Steps to reproduce the behaviour:

TBD

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by JS-goose** [comment]
Description

Using file picker to upload multiple image files to a Wasabi bucket.

Uploading single file works flawlessly but will not work with multiple files.

File picker: 
![image](https://user-images.githubusercontent.com/30503684/131381160-ef488373-2217-458d-aa88-f7cd89585064.png)

Query with response error:
![image](https://user-images.githubusercontent.com/30503684/131381388-4408b207-4f75-492d-95fc-6ab7efd8b5b8.png)


Important Details

    Version: Self Hosted v1.5.15
    OS: Windows 10 
    Browser Firefox and Chrome
    Environment: production

Apologies if I have not provided enough info.  I'm happy to provide more if need be.

**Comment by Irongade** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BE-Coders-Pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/6737?planning-poker) with ZenHub @ajinkyakulkarni @nidhi-nair @sumitsum
