### ISSUE TITLE
[BUG] 'type' field once selected, no more remains an optional field.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#674]
Attachment: https://drive.google.com/drive/folders/1Fvc0l8Q1x5Y-AcDUdlnz_mr76Kx3QIsN?usp=sharing

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, click on 'Create New' in order to create a new application
3. Edit Application
4. From the Form Widgets, pick button (this is just for an example, this issue is generic to all the widgets)
5. Select Download under onClick
6. Placeholder for 'type' says that it's an optional field

Expected Result : Once selected, user should have an option later on to unselect it since it's an optional field.
Actual Result: Once selected, user can't unselect it. (Even if it's an optional field).

**Comment by daniel-shuy** [comment]
I've created a PR to fix this. Not sure if its the best approach though...

**Comment by prapullac** [comment]
"No Action" as an option is added to every widget action. Hence closing the issue
