### ISSUE TITLE
[Feature] Upload csv/xlsx via Filepicker

### ISSUE THREAD

**Issue by shubham-maurya** [appsmithorg/appsmith#6743]
## Summary

Ability to upload csv/xlsx files via filepicker

## Motivation

Most business reporting / work happens through excel files. Customer facing teams are very used to using Excel as input and output. i would like for my customers to upload and excel, and i parse and provide putput according to the values in the columns. For example, users uploading a list of products and getting a sheet with the recommended price for each item, based on an API

**Comment by Nikhil-Nandagopal** [comment]
@shubham-maurya this should be possible today in the file picker. What is the issue you're facing?

**Comment by shubham-maurya** [comment]
Hi @Nikhil-Nandagopal : yes, my bad - it is possible. The lack of _csv_ as an option in the file type dropdown threw me off.

**Comment by tweinreich** [comment]
Hi @Nikhil-Nandagopal, it would be helpful to be able to provide a custom delimiter. I had an issue with a CSV that had semi colons as a delimiter.

**Comment by Nikhil-Nandagopal** [comment]
@tweinreich for upload any delimiter should work. Could you share an example file and which endpoint was this failing for?
Closing this till we have more information

**Comment by tweinreich** [comment]
@Nikhil-Nandagopal you're right, my mistake, sorry.
