### ISSUE TITLE
Change the data format that is output on form submission from array to map

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#6745]

**Comment by ayushpahwa** [comment]
Closed due to changes from frontend only, reopening to allow for changes from backend side.

**Comment by trishaanand** [comment]
@ayushpahwa : Unsure what the task here is. Could you please re-assign if its still relevant or close if not required. Thanks!

**Comment by nidhi-nair** [comment]
Closing the issue since we're done with structural changes for UQI, might have completed this along the way. @ayushpahwa please reopen and add details to this if you think that is not the case.
