### ISSUE TITLE
[Bug] [Release Frozen] Execution failed with status 5000 error on Google sheet query

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6762]
Observation: Getting error for all existing Google sheet query on Release-frozen

App: http://rc.app.appsmith.com/applications/610cdc95f00abe4fc53d8bed/pages/610cdc95f00abe4fc53d8bef/edit/saas/api/6110c54cd197470eb671316d

<img width="1917" alt="Screenshot 2021-08-20 at 2 22 09 PM" src="https://user-images.githubusercontent.com/83569920/130207937-8c6cdfc3-be86-49db-974f-55f48ff42bc9.png">
<img width="1919" alt="Screenshot 2021-08-20 at 2 17 33 PM" src="https://user-images.githubusercontent.com/83569920/130207956-ef2e49be-220d-4db2-a8aa-cb7706303b96.png">

**Comment by nidhi-nair** [comment]
Closing this as this was an environment related issue
