### ISSUE TITLE
[Feature]: Support Select as a column type in table widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6766]
## Summary

As a dev, I should be able to add the following as column types
- Select

# Success Metrics

| Goal  | Metric |
| ------------- | ------------- |
| Operate on data using input elements | User should be able to perform add/edit action from row by using select elements |

# Requirements

`B:`
| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Column type: `select` | Sets the column type to select | High  | - |
| Computed value | The options to be displayed in the select field; type<Array> |  High | - |
| Default value | The option to be selected by default; type<String> | High | - |
| Inherit attr by data type from the the parent widget | All properties from the parent widget should be inherited under each data type here | high | - |
| Disabled | Should the input remain disabled | high | - |
| onOptionChange | trigger event on change of an option | High | - |

# Developer Handoff Document in Figma:
None required

**Comment by dilippitchika** [comment]
Asked about this in https://community.appsmith.com/t/how-do-i-dynamically-create-menu-items-in-the-menu-button-column-type/517/7

**Comment by ame-appsmith** [comment]
[Another user](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100166538#part_id=initial-part-164629100166538-1436014791) requested this feature.
