### ISSUE TITLE
[Bug] Error "TypeError: CustStatusDropdown.selectedOptionValues.reduce is not a function" raised but there is no problem

### ISSUE THREAD

**Issue by tazmaniax** [appsmithorg/appsmith#6768]
## Description

I'm getting this error "TypeError: CustStatusDropdown.selectedOptionValues.reduce is not a function" from this logic ANY({{"'{"+CustStatusDropdown.selectedOptionValues.reduce((r, v, i) => r + (i>0?', ':'') + v, '')+"}'"}}) and in the preview panel it says it resolves to "undefined" but it is actually working. I'm able to select one or more values in the dependent multi-select widget and it all works correctly, e.g. the correct results are presented. The only problem is the error being raised and the evaluated window not displaying correctly what is actually being sent to the database. This error is raised if the multi-select widget has values or selected or not. Maybe I shouldn't be using Array reduce and there is a better way to convert dropdown selected values to a comma separated list that doesn't give an error?

![CleanShot 2021-08-20 at 10 36 08](https://user-images.githubusercontent.com/1079943/130221328-37086652-3e8a-49ce-9443-f8e6c4730768.png)

![CleanShot 2021-08-20 at 10 32 28](https://user-images.githubusercontent.com/1079943/130221310-78e34bdc-52a9-4c42-a04e-07c7d72486f2.png)

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Open app
4. See error - see screenshots above

### Important Details

- Version: Cloud
- OS: MacOSX
- Browser: Brave (Chromium)
- Environment: Production

**Comment by ohansFavour** [comment]
Hi @tazmaniax, could you please provide me with some more steps and context as I am unable to reproduce this issue. The supposed command appears to be working fine here, upon trial.
