### ISSUE TITLE
[Bug] Binding only works when user click on JS  option for Default Date property on Datepicker widget and then binds 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6773]
## Description: There is no error when user bind the Default Date property on Datepicker without clicking JS option

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4f8097ff37674a34a9634ea7d66bb2df-00001.gif)](https://www.loom.com/share/4f8097ff37674a34a9634ea7d66bb2df)

In Date picker we do not accept JS query without clicking on the JS option

Expected Behaviour: If it’s input field then by default it should accept JS query without having JS option.

**Comment by Nikhil-Nandagopal** [comment]
@vivekverma2312 it's not an input field right? It's actually a date selector field

**Comment by somangshu** [comment]
@vivekverma2312 IIUC the behaviour is correct here, When JS is not enabled the user can see the datepicker popup and otherwise and enter the expression to be evaluated. Closing this for now, Please reopen if required
