### ISSUE TITLE
[Bug] List widget: Probable re-rendering due to eval in child

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6775]
## Description

The list widget started behaving abruptly in a use case of a chart widget as one of the child. Adding necessary details before

https://user-images.githubusercontent.com/11089579/130358602-6100c41d-9a69-461b-9951-44aef98514e3.mov

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

**Comment by SatishGandham** [comment]
This might be taken care when this change goes in #6523

**Comment by somangshu** [comment]
@vivekverma2312 please verify and close this
