### ISSUE TITLE
[Feature] Custom JS lib: Allow users to add private JS libraries.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6777]
## Summary
Some users have JS libraries that are developed and distributed in-house. This feature will allow such users to download and use these libraries with Appsmith. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5nhu4)

**Comment by sharat87** [comment]
How is this different from #2430?

**Comment by sumitsum** [comment]
@sharat87 #2430 is a general issue covering two scenarios - (1) import publicly available JS library (2) import private JS libraries. This particular issue covers case (2). Hence it has been tagged as `advanced` - basically to be solved specifically for EE.

**Comment by billyrudi** [comment]
questo interessa anche a me

**Comment by billyrudi** [comment]
this interest also me

**Comment by Gayathri16401** [comment]
Hi, Actually I want to add xml highlighter feature in my UI. For highlighting XML, I am trying to use Node.js library "hljs = require('highlight.js/lib/common');". But I was not able to import the Node.js libraries in Appsmith . Kindly look into this. Thank you!

**Comment by sumitsum** [comment]
Closing this issue since our current ongoing implementation will also be able to handle this case as a general case.
