### ISSUE TITLE
[BUG] No .env.example in the same directory instead it's in root of the project | Contributing.md issue

### ISSUE THREAD

**Issue by akbansa** [appsmithorg/appsmith#678]
## Description

While setting up front-end, I found that I do not have any `.env.example` in the docker/ directory as per your documentation, see the attached screenshot:

![image](https://user-images.githubusercontent.com/13042781/93898190-90458280-fd10-11ea-9ca0-94b24f52e7df.png)

Instead, it is located in the root folder of the project, please find in the attached screenshot:

![image](https://user-images.githubusercontent.com/13042781/93898509-e9151b00-fd10-11ea-8bd0-9e8f88aea425.png)

**Comment by harishkotra** [comment]
Technically, if you are running the first point, you are still in the project root. So I don't see an issue with this one but I'll leave it to the team to decide.

I would rather look at updating the last command to `cd ../../../`

**Comment by akbansa** [comment]
@harishkotra Your first point is not correct  as running `cd ..` will take you to `app/client` not `root`

But the second is correct. This is a bug in the setup doc.

I reported because I had to spend time finding the file in multiple folders.

**Comment by Saket2** [comment]
I'll be picking it up for Hacktober Fest.

**Comment by mohanarpit** [comment]
@Saket2 Awesome! It's all yours.

**Comment by satbir121** [comment]
@Saket2 Please update [this file](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md)

**Comment by Saket2** [comment]
Raised the pull request https://github.com/appsmithorg/appsmith/pull/907
