### ISSUE TITLE
[Bug] Any error log on widget is not restored once widget deletion is undone

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6782]
## Description
Once user deletes a widget with errors and undoes the delete operation, logs for the error are no longer displayed on the
debugger while widget still displays the error

### Steps to reproduce the behaviour:
1. Add table widget (or any other), type in an incorrect JS code to show an error in the debugger
2. Observe error logs in debugger
3. Delete widget and undo delete
4. Observe the error log clear once widget is restored but widget still shows an error (red state of property pane)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release & Production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5440212afd694782aa674be723657e92-00001.gif)](https://www.loom.com/share/5440212afd694782aa674be723657e92)

**Comment by akash-codemonk** [comment]
@ramsaptami  Could you clarify how you were able to undo, because the error says until the undo toast is present?

**Comment by ramsaptami** [comment]
@akash-codemonk That's right. Technically, if the widget is restored then the errors should be restored too but I guess it's cleared by the delete operation
