### ISSUE TITLE
[Bug] User options display for app after app property change

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6784]
## Summary
- [ ] When user edits app property from home page and clicks back on to the app to exit the property pane of the app, the app does not switch back to show **Edit** and **Launch** options. User has to click outside of the app icon to enable these options though.
- [ ] Property pane of app should exit when user presses the **Esc key** to make it more keyboard friendly for user

## Motivation
When property pane exits on clicking outside of the property pane modal, the expectation for the user is to be able to access normal app operations (Edit, Launch) instead of moving outside of the app icon boundary and then have those options appear.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/78a044b452af4315a2fb3acd22ca0504-00001.gif)](https://www.loom.com/share/78a044b452af4315a2fb3acd22ca0504)

**Comment by ankitakinger** [comment]
Can be closed. Its works as expected today.
