### ISSUE TITLE
[Bug] App sharing invite error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6785]
## Description
- [ ] Pressing **Tab key** must move control from email input to role selection and consequently to the **Invite button** from the dropdown. User must also be able to scroll down options using arrow keys on the dropdown menu selection
- [ ] On pressing **Tab** to move control to role selection from the email address box, an incorrect error is displayed to the user and this error does not get cleared - error must get cleared on successfully sending out an invite

### Steps to reproduce the behaviour:
1. Go to app and click on share
2. Type in an email and press **Tab key** to move control to the next field - expected behaviour is to move control to the dropdown option instead an incorrect error is displayed
3. Choose role and click on **Invite** and observe the error from step 2 still present after successfully sending out an invite.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release & Production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2a2fac9c51ec4995864a4ce77353d1e7-00001.gif)](https://www.loom.com/share/2a2fac9c51ec4995864a4ce77353d1e7)

**Comment by Nikhil-Nandagopal** [comment]
Actually it's supposed to create a tag for that user and allow the user to add another email. Seems to be working for me. Not sure why it's not working here. Also @ramsaptami why is this related to the linting project?

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal this is related to regression testing I'm doing for the current release that's going out

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami is this still happening?

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal this is still on release
![image](https://user-images.githubusercontent.com/79509062/131817493-6cf45bf7-8f24-4ae7-b2c0-e9d44123d403.png)

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi can someone fix this? This seems like a big issue if it blocks inviting other users

**Comment by hiteshjoshi** [comment]
This will be picked this week.
