### ISSUE TITLE
[Bug] Do not mark field as an error if a widget property field is empty

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#6787]
Currently the property pane fields are shown as having an error when it is empty.

Expected: Not show empty fields in an error state.

**Comment by RakshaKShetty** [comment]
@akash-codemonk in the below-mentioned widgets i am seeing an error when the widget property pane is kept empty:
1. file picker has an error in the max file size input box when it is kept empty
2. rating widget has an error in the default rate 
3. chart widget has an error in chart type 
4. In Image widget has an error in object-fit 
5. The rich text editor has an error in the default text 
6. The tab widget has a problem with the default tab

**Comment by akash-codemonk** [comment]
> 5. The rich text editor has an error in the default text
Empty field does not seem to show any error for default text

**Comment by RakshaKShetty** [comment]
In the image widget when the user keeps "Initial location" empty the error is displayed
![Uploading image.png…]()
