### ISSUE TITLE
[BUG] Query Error: PluginExecution failed with error Zero date value prohibited

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#679]
## Description

"Select *" throws an error on a table that has only 25 columns and about 400 rows of data.

**Issue with the datetime columns?** There are two columns out of which one column has 0000-00-00 00:00:00 as value if there are no updates made to the row. 

### Steps to reproduce the behaviour:
1. Connected a MySQL Database
2. Ran a select * from table_name where cond=value;
3. Following error throws up

![image](https://user-images.githubusercontent.com/4999463/93915799-2637d800-fd26-11ea-8fc9-73799adae733.png)

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Google Chrome (v. 85.0.4183.102)

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 can you please verify this?

**Comment by sharat87** [comment]
Hello @harishkotra, we've identified this to be a bug in the way we were connecting to MySQL databases. We didn't expect zero dates in databases, which is probably a lapse. I've raised a PR to fix this. I'll notify you once it's deployed on our cloud.

Thank you for taking the time to report with clear details. Much appreciated.
