### ISSUE TITLE
[Bug] Once JS errors are displayed in the logs, it does not clear even after user deletes incorrect code

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6791]
## Description
JS errors don't clear from the debugger when user removes error causing code. User has to refresh the page to clear errors off the debugger

### Steps to reproduce the behaviour:
1. Add incorrect JS code to a widget and observed errors displayed in the debugger
2. Now delete this code expecting to clear the debugger off the errors too - but the errors stay until page is refreshed

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy Preview (6265 - Linting & Errors)

![image](https://user-images.githubusercontent.com/79509062/130433821-5a0ae63a-74b4-42c4-8bbe-ef019b04d9df.png)

**Comment by hetunandu** [comment]
Can we check this again @ramsaptami

**Comment by ramsaptami** [comment]
works fine on deploy preview now
