### ISSUE TITLE
[BUG] Copy/Pasting table widget isn't persisting the table filter, sorting or searching.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#680]
## Description
Copy/Pasting the table widget in the container isn't persisting the table filter, sorting or searching. Same does persists with delete/undo feature for table widget.

### Steps to reproduce the behaviour:
1. Add a table with default data.
2. Apply any valid filter, sorting, searching to the table data.
3. Copy and paste the table.
4. The generated table would be w/o any filter, sorting or searching.

[Video In Action](https://streamable.com/rqaewp)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay Closing since copy paste is not meant to persist edit mode inputs
