### ISSUE TITLE
[Bug] DatePicker.selectedDate cannot be inserted into DB Postgres

### ISSUE THREAD

**Issue by President** [appsmithorg/appsmith#6802]
## Description

I have a form with integer and two text fields and one datepicker.
And I want to INSERT information to the table in the Postgres from this form.
I created Insert query and attached it to Submit button and 
Inside the query I referenced all the form fields.
Everything is ok except DatePicker.selectedDate  field - it simply does not working

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create form with DatePicker
2. Create INSERT query which is using DatePicker
3. Try to make it working - it is not working

`07:12:11
[QueryInsertLeadInteraction]Execution failed with status 5005
Query preparation failed while inserting value: 2021-08-27T12:23:23.232Z for binding: {{DatePickerInteractionAt.selectedDate}}. Please check the query again. Error: null
{
"requestParams":{
"Query":{
"value":"INSERT INTO interactions (lead_id, interaction_type_id, text, interaction_at) VALUES ($1, $2, $3, $4);"
"substitutedParams":{
}
}
}
}`

P.S. Evaluated value of the query is correct! When I copy/paste it and run it - it works well. So it seems that evaluated value is NOT what really AppSmith is trying to run

Here is evaluated value:
`INSERT INTO interactions (lead_id, interaction_type_id, text, interaction_at)  VALUES ('some-lead-id', 6, 'test text', '2021-08-27T12:23:23.232Z');`

And here is a query:
`INSERT INTO interactions (lead_id, interaction_type_id, text, interaction_at)  VALUES ('{{TableLeads.selectedRow.id}}', {{SelectInteractionType.selectedOptionValue}}, '{{InputInteractionText.text}}', '{{DatePickerInteractionAt.selectedDate}}');`

### Important Details

- Version: Cloud 
- OS: MacOSX
- Browser chrome
- Environment production

**Comment by Nikhil-Nandagopal** [comment]
@President could you try without wrapping your query in quotes?
```
INSERT INTO interactions (lead_id, interaction_type_id, text, interaction_at) VALUES ({{TableLeads.selectedRow.id}}, {{SelectInteractionType.selectedOptionValue}}, {{InputInteractionText.text}}, {{DatePickerInteractionAt.selectedDate}});
```

**Comment by President** [comment]
I didn't mentioned it but I tried both ways - with quotes and w/o quotes. (I just thought after googling other AppSmith examples that with quotes is the more correct way)
W/o quotes is the same error.

However w/o quotes evaluated value is also incorrect - w/o quotes which is incorrect SQL insert.

**Comment by President** [comment]
BTW, if I remove that "interaction_at" datetime field from the INSERT statement or use DEFAULT value for it - i.e. not use DateTimePicker for INSERT then it is working well. 
So the problem seems to be in DateTimePicker binding to he query

**Comment by Nikhil-Nandagopal** [comment]
@President it looks like there were no substituted params. In your UI, does the datepicker have a value selected when you run the query? Also could you add nikhil@appsmith.com to your application? I'd like to see what the issue is

**Comment by President** [comment]
@Nikhil-Nandagopal  - yes, the DatePicker had a value and params were substituted at least " evaluated value" is absolutely correct. It just seems that evaluated value and what is actually executed is different

**Comment by Nikhil-Nandagopal** [comment]
@President could you invite me to your app? I'd love to check it out and see what is going wrong

**Comment by President** [comment]
ok. added you. please look at 'WorkingPage' and QueryInsertLeadInteraction

**Comment by Nikhil-Nandagopal** [comment]
@President I found the issue. Your db column was of type timestamp which needs data in the format YYYY-MM-DD HH:mm:ss. The format of the selected date was ISO string so we had to convert that to the format the DB needed. I used the Datepickers formatted Date option to do this.

**Comment by President** [comment]
Thank you very much, Nikhil-Nandagopal!
I was not able to understand it because I saw that evaluated value was correct. 
Now I slightly better understand AppSmith. It seems when I am using Prepared Statements what I see in "evaluated value" is not what exactly is used. And formats can be slightly different like here.
You helped me a lot!
Best wishes!
