### ISSUE TITLE
[Bug] Entire screen moves down on datasources page when you configure SSL

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6804]
Add a datasource and choose SSL settings
<img width="1440" alt="Screen Shot 2021-08-23 at 10 05 15 PM" src="https://user-images.githubusercontent.com/30255708/130484360-f17f25da-95da-440d-9cbd-3de3602794d3.png">

**Comment by areyabhishek** [comment]
I've assigned it to you @BhandarkarPawan. Please go ahead and fix this. Thank you!

**Comment by tauantcamargo** [comment]
@areyabhishek can i get it?

**Comment by danceAndJive** [comment]
Hi @areyabhishek, can I please be assigned the issue? I'd like to have a crack at it. Thanks!

**Comment by Abhi3685** [comment]
![image](https://github.com/appsmithorg/appsmith/assets/35190737/3f343ef5-0d0f-4842-b99c-301b53ac7499)

This isn't an issue anymore. Please close this.
