### ISSUE TITLE
[Bug]The Application with Input widget breaks as the Valid toggle is not enabled  by default for the  existing application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6809]
## Description

[What happened]The Application with Input widget breaks as the Valid toggle is not enabled by default for the  existing application

### Steps to reproduce the behaviour:

1. Go to canvas
2. Generate a new app for S3 datasource 
3. Now try to search a file name from the input box
4. The error is displayed when the user enters the text

This would be an issue for the previously developed apps because the Valid toggle will be in a disabled state for the existing apps
![image](https://user-images.githubusercontent.com/45958978/130562687-53f45be8-ad18-438c-9e75-61fce732b0b0.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [chrome]
- Environment [ release]

**Comment by somangshu** [comment]
@techbhavin the valid property should always be enabled for new or old widget

**Comment by somangshu** [comment]
@techbhavin Note:
Currently all props are acting independently, i.e. regex, required, valid

1. If valid is true. isValid is true
2. If valid it true and regex does not match, isValid is false
3. if valid is false and regex matches, isValid is false
4. if valid is false and regex does not match matches, isValid is still false
5. If valid is true and required is true, isValid is false when the field is empty
6. if valid is false and required is true, 
7. isValid is false when the field is empty and shows up a different error in the input tooltip when filled

Now looking at these conditions, I feel maybe the functionality is as intended with the following changes,

1. Change the valid prop to an input control like regex
2. the valid field prop should be able to accept undefined apart from boolean
3. Change helper text to > ability to control input validity based on a JS expression.

Once we allow the `undefined ` value we dont really need any migration and it will work for old apps and hence the currently linked PR changes wont be required. I suggest we start from scratch here.
