### ISSUE TITLE
[Bug]-[250]:Back button navigation problems

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6813]
We need to fix how the back button works in our pages. I constantly land at odd places when I use the back button. It’s a minor annoyance that repeats frequently. An example:

- I see a list of datasources in the right hand side bar of the API pane
- I click to edit a datasource so I land up on the datasource page
- I click on the back button and it just takes me to the canvas instead of the API I was editing

**Comment by RakshaKShetty** [comment]
Scenarios tested 
1. In the entity pane on the left side  if there are more data sources with the navigate between then (say eg: if i have API 1 and Database 1 if I go from API 1 to datasource 1 ) then click on Back the user will be navigated to API 1 ->This case works
2. From the API edit pane if the user clicks on Edit datasource and clicks on the Back button from edit page then the userland back on Api Edit pane ->This  case works
3. From the Datasources Active tab click on meat ball icon and click on edit now from the edit page click on back the user navigate to the Active tab ->This case works
4. From the Datasource Create new tab try to create any new datasource connection and click on back from a creation page  the user will land back on create new tab->This case works
5. From the active tab when the user creates a new query/API and now from the Query page when user click on back button the user should be navigated to ACtive tab ->In this case the user is navigated to Create new Tab 
6. From the Query pane from the data source dropdown if the user selects the create new datasource the user is navigated to create a new tab and from there when click on back the user should be navigated to query->In this case the user is navigated to Canvas
7. Select the datasource from the entity pane Now click on New API/query this navigates the user to create a new query or API page from there now click on back the user should come back to the previous page ->This casework for API, not for Query
8. Select the datasource from the entity pane Now click on the edit button now from the query edit pane click on back the user should come back to the previous page ->In this case the user navigates to canvas

**Comment by pranavkanade** [comment]
> Select the datasource(API or Database) from the entity pane Now click on the edit button now from the query edit pane click on back the user should come back to the previous page -> In this case the user navigates to canvas

This is the issue in some cases because, we are using state change for showing different components and not using navigation -> this is impossible to handle from outside
@RakshaKShetty Other than that I've fixed 5, 6 & 7

**Comment by RakshaKShetty** [comment]
we are planning to revert the fix and work on it New changes

**Comment by Aishwarya-U-R** [comment]
There is issue in Back navigation in below scenario also:
> Navigate to 'New Query' of a created data source
> Create/Select/Update/Delete options page is displayed
> Click on any one of it, and navigate inside
> Now click on Back from Query Pane page & expect it to Navigate to Create/Select/Update/Delete options page again
> but User is navigated completed back to the Data sources pages again

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 1|

**Comment by Nikhil-Nandagopal** [comment]
Closing this because the browser back button does this and we reverted this because it became a worse experience. Let's solve navigation once and for all as part of #2602
