### ISSUE TITLE
[Bug] Hand icon must be displayed on row selection of table in Deploy mode

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#6819]
Steps to reproduce 
1) Bind a table to API
2) Add an Input widget
3) Bind the table to Input on Select widget
4) now select the table in View mode
observe the hand icon on selecting 
5) Click on Deploy
and observe a Mouse Arrow in the Deploy mode

Observation:
It is observed that a Mouse Arrow is displayed to a user in the Deploy mode while selecting a row however in View mode we display a hand icon 

Expectation:
It is observed that on selecting a Row inside a table the user must be displayed with hand icon 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f9e0dfc9b77241048a6c996315ae2277-00001.gif)](https://www.loom.com/share/f9e0dfc9b77241048a6c996315ae2277)

**Comment by somangshu** [comment]
@prapullac the hand icon appears in the edit mode because it's hovering over the drag layer, Hence showing the right intent. 
Same goes for the view mode, as the drag is not available the pointer shown is intended. Closing this. Please feel free to re open if required
