### ISSUE TITLE
[Bug] When storeValue is called at the start of an onClick function, the button stops loading

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#6822]
## Description

In a discussion with a user on discord, they are facing an issue with loading not being shown onClick. On checking, it was found that the `storeValue` was there at the start of the onClick function. This is causing the loading to show and stop immediately.

### Steps to reproduce the behavior:

Add steps to reproduce this behaviour, including console/network logs & screenshots

1. Add an API call to the onClick of the button widget
2. Click on the button and the loading shows
3. Now in the onClick JS, add a `storeValue` call at the start of the function/ 
4. Now, click the button and the loading will show for a bit and then disappear.

### Important Details

- Version: Cloud and Self-Hosted
- OS: MacOSX
- Browser chrome
- Environment production

**Comment by J-Ankit2020** [comment]
Assign me this issue

**Comment by hetunandu** [comment]
Thanks for your interest @J-Ankit2020. This is not really a Good first issue. I'll remove the tag. Please find some other issue to contribute and tag me. I'll assign it ASAP

https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest

**Comment by hetunandu** [comment]
Cannot seem to reproduce this anymore. Can you confirm @ayushpahwa 
I tested with 
```
storeValue('epochtime', Date.now());
      Api1.run(() => {
         Api2.run(() => {
            Api3.run();
            });
         });
      }}
```
