### ISSUE TITLE
[BUG] Part2 - Documentation Improvements

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#683]
### Enabling Third Party Services

Current:- Appsmith ships with third party services that improve the app building experience. All third party services are entirely optional
Improvement:- Appsmith ships with third party services that `improves` the app building experience. All third party services are entirely optional`.`

Current:- All third party services are enabled by default in our cloud hosted version
Improvement:- All third party services are enabled by default in our cloud hosted version`.`

Current:- You may need root access to modify the docker.env file
Improvement:- You may need root access to modify the docker.env file`.`

### Building The UI
Current:- Widget names are important when adding logic so name your widgets well!
Improvement:- Widget names are important `while` adding logic`,` so name your widgets well!

Current:- Widget properties can be editing via the property pane which can be toggled next to the delete icon. Widget properties can affect data, style and action to take. 
Improvement:- Widget properties can be edited via the property pane which could be `opened using top-right icon (name)`. Widget properties can affect `the widget data, styling and actions.` 

Current:- Widget properties don't have to be static! Connect a widget property to an API by typing {{ }} inside the property and binding the property using an API name or Widget name. You can learn more about working with widgets and APIs here
Improvement:- Widget properties doesn't have to be static! `To make it dynamic, type {{ }} inside the widget property and bind it to an` API name or Widget name. You can learn more about working with widgets and APIs here

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay would you consider raising a pr for these fixes here
https://github.com/appsmithorg/appsmith-docs

**Comment by Saket2** [comment]
I'll be taking it up for Hacktoberfest. Confirmed with @visibleajay
