### ISSUE TITLE
[Bug] Table's searchText is not working with SELECT queries for Postgres

### ISSUE THREAD

**Issue by President** [appsmithorg/appsmith#6837]
## Description

I want to use Select feature of the Table.
I did what was documented here https://docs.appsmith.com/core-concepts/displaying-data-read/display-data-tables
But it is not working - SQL query seems to incorrectly use searchText property of the table

### Steps to reproduce the behaviour:

1. Create Table
2. Create Select SQL query
3. Bind table to the query
4. Ensure data is displayed correctly in the table
5. Update query with WHERE ilike that is using Table's SearchText property  e.g. I use: "SELECT * FROM leads where full_name ilike '%{{Table1.searchText}}%' limit 10"
6. Go to table, set onSearchTextChanged event to the query
7. Change SearchText field of the table

Nothing is displayed in the table!
and evaluated value of the query is "SELECT * FROM leads where full_name ilike '%$1%' limit 10"
So - it seems  parameter searchText was not substituted in the query

### Important Details

- Version: Cloud
- OS: MacOSX
- Browser chrome
- Environment production

**Comment by President** [comment]
This is in the same app I shared with you - "Page 6" - has just that table and query.

**Comment by Nikhil-Nandagopal** [comment]
@President this has also been resolved. When prepared statements are on, the query must have the % inside the bindings as {{ "%" + Table1.searchText + "%" }}

**Comment by President** [comment]
Update.
ayushpahwa: in the Discord answering another my question suggested to turn off Prepared Statement. I did it and this searchText is also started working!

So - I now think that there is no bug - just  amisunderstanding that Table's SearchText can't work with Prepared Statement. And it would be good to mention this on https://docs.appsmith.com/core-concepts/displaying-data-read/display-data-tables "Server-Side Searching / Filtering" section
(or if it still can somehow work with prepared statements - please clarify)

**Comment by Nikhil-Nandagopal** [comment]
@President it can work with prepared statements as {{ "%" + Table1.searchText + "%" }} or without it as 
'%{{Table1.searchText}}%'
