### ISSUE TITLE
[Bug] [Release]  "cannot read property 'source' of undefined" error on running PostgreSQL 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#6839]
## Description: Record count is displayed but records are not shown in response. Also `cannot read property 'source' of undefined` error is displayed in console.

<img width="1918" alt="Screenshot 2021-08-18 at 6 21 35 PM" src="https://user-images.githubusercontent.com/83569920/130642091-b127c5a9-a76c-43f3-a5c2-ead9edb5e0ac.png">

**Comment by ohansFavour** [comment]
@vivekverma2312 kindly confirm that this issue has been fixed.
