### ISSUE TITLE
[Bug] Dropdown selectedOptionValue cannot be accessed inside List Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6840]
## Description

The selected option value of the dropdown cannot be accessed inside the list widget
1. Drag a List
2. Add a dropdown inside it
3. Drag a Text Widget
4. Bind the text widget to {{List1.items[0].Select1.selectedOptionValue}}

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan @somangshu can we please get this fixed on priority?

**Comment by tomjose92** [comment]
I believe this is the functionality I was looking for. Also would love to see support for other widgets, like table or so to be supported, along with the select button.
My use case is to send an array of objects inside a list object, which will be used by the table or select button to populate.

**Comment by somangshu** [comment]
@tomjose92 got it, Thanks for the additional context here

**Comment by ashit-rath** [comment]
Will be fixed in #16422
