### ISSUE TITLE
[Bug] Empty List shows 1 item

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6841]
## Description

The list widget shows 1 item even when an empty array is passed to it.

### Steps to reproduce the behavior:

1. Drag a list widget
2. add an empty array
3. Hit Deploy
4. See that one list item is present

**Comment by Nikhil-Nandagopal** [comment]
@vivekverma2312 I still see a lot of issues in the list widget. Has this been tested properly? This and #6840

**Comment by prapullac** [comment]
Now on a list widget with empty array deployment, the list displays info message stating "No data to display"
