### ISSUE TITLE
[Feature] Change first day of the week on the date-picker widget

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#6842]
## Summary

We should be able to change the first day of the week on the date picker widget.

## Motivation

As requested by a user on [discord](https://discord.com/channels/725602949748752515/725609493974614076/879784273882800170).

**Comment by Hyperion101010** [comment]
Looks good can i pick this up @ayushpahwa

**Comment by Nikhil-Nandagopal** [comment]
Hi @Hyperion101010 , 👋  the issue is all yours! Do raise a PR within 4 days and read our [Contribution.md](Contribution.md)

**Comment by Nikhil-Nandagopal** [comment]
@OladapoAjala go for it! We can do both, detect the current locale and set that as the default as well as give the user an option

**Comment by OladapoAjala** [comment]
Thanks @somangshu I'd work on this over the weekend and give a feedback soon, been a bit busy lately!
