### ISSUE TITLE
[Bug]The pagination doesn't work for the table widget when the user is in comment mode 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6848]
## Description

[What happened]The pagination doesn't work for the table widget when the user is in comment mode 

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/68b84c8427934ae98513c7794c5e274a-00001.gif)](https://www.loom.com/share/68b84c8427934ae98513c7794c5e274a)
### Important Details

- Version: [Cloud]
- Browser [chrome]
- Environment [Deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty this is expected. The comment mode is a separate mode for dropping comments so general edit / view operations like clicking buttons won't work
