### ISSUE TITLE
[Bug] The List widget gets deselected when an action is clicked inside it

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6850]
## Description

[What happened]When the user clicks on the Update button for the first time the file name is displayed but when we click on it for the second time the file name is not displayed

### Steps to reproduce the behaviour:
https://loom.com/share/002c74a4bcc84594afe6643e39206214

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [ chrome]
- Environment [release]

**Comment by Rishabh-Rathod** [comment]
@RakshaKShetty I am unable to reproduce this issue. Does this happen every time for you?

Seems like a bug in the widget.

**Comment by RakshaKShetty** [comment]
yes @Rishabh-Rathod this happens everytime with me

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan @somangshu please fix this. This will break existing functionality if it goes to master

**Comment by somangshu** [comment]
@jsartisan will be reverting this
