### ISSUE TITLE
[Bug] List goes blank with Menu Widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6851]
## Description

A user reported that the list widget goes blank when the menu widget is added to it

### Steps to reproduce the behaviour:

1. Drag a list widget
2. Add a menu widget to one of the list items
3. Configure one of the menu options
4. Set the onClick to {{ }}
5. The List goes blank

**Comment by somangshu** [comment]
This also happens on setting action to other events like openModal.
