### ISSUE TITLE
[Bug] Widget copy-paste doesn't work inside Tab widget

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#6855]
## Description

Copying & pasting widgets inside the tab widget doesn't seem to work. 

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create a tab widget
2. Add an Input widget inside Tab1
3. Copy-paste the Input widget
4. See that nothing happens. 

Oddly, this seems to work across tabs. If a user tries to copy-paste widgets across 2 tabs, that seems to work.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by marks0351** [comment]
@vivekverma2312 can we validate this?
I am unable to reproduce it.
