### ISSUE TITLE
[Bug] Disabling "Show Tabs" option in tab widget makes the widget look weird

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#6856]
## Description

Disabling the tab headers in the tab widget causes the tab widget to look very weird with borders on the top & bottom. The deployed version looks even worse.

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/79c48dc9b3e24f57873c314d22f4b308-00001.gif)](https://www.loom.com/share/79c48dc9b3e24f57873c314d22f4b308)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
Closing in favour of #4747, Shall prioritise that higher
