### ISSUE TITLE
[Bug] isValid errors on the input widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6857]
## Description

- When the input type is set to number, The isValid for a required field return null / undefined on pageLoad and hence the form buttons by default is enabled for an invalid form. 
- When a field is not required and empty, it should not show an error, given valid and regex properties are also empty
- The input widget shows an error briefly when the value is first changed from empty (this happens only on first keypress in an empty input)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by somangshu** [comment]
@techbhavin lets take this up as well with #6809

**Comment by ramsaptami** [comment]
Still occurs on release
https://www.loom.com/share/ea9848dddfc34c3089421eaeaca461ce

**Comment by somangshu** [comment]
@ramsaptami are you talking about the error that is showing up briefly? 

@techbhavin do you know the cause here?

**Comment by ramsaptami** [comment]
yep, that's right @somangshu

**Comment by techbhavin** [comment]
@somangshu  here current implementation set default error message for validation like email, regex.

and because of that, we are facing this issue.

**Comment by SatishGandham** [comment]
I figured out the first two. Third one not sure.
