### ISSUE TITLE
[Bug] The reset widget action needs a special param to reset children

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6859]
## Description

Triggering resetWidget on a modal does not reset all the fields inside it

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Drag a modal
2. Add an input
3. Enter some text
4. Configure the button to reset the modal
5. The input does not get reset

**Comment by somangshu** [comment]
@Nikhil-Nandagopal the above reproduction step do not lead to the said error, I see that the input widget resets, given that reset children was set to yes
