### ISSUE TITLE
[Bug] API status message overflows in the API pane when the error message is too long

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6862]
We need to wrap the message or shorten the message and only show the whole thing on hover.
<img width="727" alt="Screen Shot 2021-08-25 at 12 14 15 PM" src="https://user-images.githubusercontent.com/30255708/130742355-152a0ddb-394b-4227-ad2c-1c4a41a69532.png">

**Comment by AmanAgarwal041** [comment]
@aakashDesign What should be the design for the hover ?

**Comment by rohan-arthur** [comment]
@Irongade help with reproducing this error, and also to clarify where the error is coming from (service or appsmith server).
