### ISSUE TITLE
[Bug]Clicking on 'debug' crashes the appsmith application

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#6863]
## Description

If API run returns an internal server error, clicking on debug causes a crash

**Comment by akash-codemonk** [comment]
Does this happen on release? This has been fixed in https://github.com/appsmithorg/appsmith/issues/6709

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk can you cherry pick the crash to master?
@trishaanand can you provide an example API to reproduce this?

**Comment by akash-codemonk** [comment]
It has been cherry picked to release frozen currently.
