### ISSUE TITLE
[Bug] JS Editor Cleanup Issues

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#6872]
- [x] The icon size in the entity explorer is not the same as the rest of the icons
- [x] The run button icon is also strangely shaped
- [x] In the action selector, the icon for JS Object and for a function should be different
- [x] The JS Editor needs empty states for when there are no functions defined and when a function is not yet run
- [x] Add export default to the JS object when it is created

**Comment by Nikhil-Nandagopal** [comment]
@ApekshaBhosale New issues
- [ ] The Execute JS Function option should be just below the Execute Query option
- [ ] Changing a function name does not refactor the function and breaks the JSObject when a new function is added with the old functions name
- [ ] + Create New JS Function from action selector only opens the JS Object, it doesn’t create a new function. Let's either achieve this or remove the + option for now
- [ ] The JS static values do not show up in the autocomplete for the best match
- [ ] The JS functions do not show up in autocomplete for the best match 
- [ ] A function that contains 2 API calls and returns a value cannot be run from the JSObject pane and does not show a return value
- [ ] JSObject debugger errors don’t trigger any action clicking on the magic wand
- [ ] In some cases, when typing a random character in the JS, invalid JS is not detected and the JSObject does not show an error
- [ ] ; at the end of the export default is valid but throws an error
- [ ] Immediately creating an object does not parse the values in it
- [ ] If the JSObject is in an unparseable state, we need to show an error that none of the functions and data will work. Highlight red around the Editor and show an error state for the run button (need design here)
- [ ] When the parsing breaks, the run functions revert to older names and behave strangely
- [ ] If there is an error in a JSObject, the evaluated value in a table using the object should have an error “Invalid JS Object” instead now it shows the error inside the JS Object which is confusing to see in the table

**Comment by ApekshaBhosale** [comment]
@nidhi-nair can you please take care of "The refactor is refactoring function names across JSObjects" issue?

**Comment by nidhi-nair** [comment]
Hey can you describe the issue in a bit more detail? What's getting refactored here, the function or collection? @ApekshaBhosale

**Comment by ApekshaBhosale** [comment]
so if object1 and object2  has both run functions and if i change Object1.run => Object1.getData, object2.run is getting renamed as Object2.getData @nidhi-nair

**Comment by nidhi-nair** [comment]
@ApekshaBhosale I can't replicate this, do you think there's some edge case that this applies to?
https://user-images.githubusercontent.com/5298848/133192820-e7f644a5-97cc-434e-9359-b6cdff4d4af2.mov

**Comment by ApekshaBhosale** [comment]
@nidhi-nair i am also not able to reproduce this. we can mark this as resolved.

**Comment by Nikhil-Nandagopal** [comment]
New Issues
- [ ] When accessing an array from another JS Object, it is being executed as a string instead of an array. See Auth Modes in the integration manager page
- [ ] Need to be able to access outer objects in the callback of a run function
- [ ] Autocomplete shows when you type on { and (
- [ ] Autocomplete not opening on tab+space sometimes 
- [ ] Pressing enter at the end of a long line, adds a new line and cursor right below the current line instead of formatting below the closing braces
- [ ] Promise rejection throws a sentry error

**Comment by rohan-arthur** [comment]
@ApekshaBhosale what is pending here?
