### ISSUE TITLE
[Feature]-[90]:Add support for Google Cloud Storage in S3 plugin

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#6877]
Add Google Cloud Storage as one of the service providers in S3 plugin. While configuration Google Cloud Storage datasource, region field should be removed from the form and default bucket should be added. This is because for Google Cloud Storage, region is set to "auto" and the usual listbuckets command used for testing does not work on GS. Hence, a default bucket should be taken as an input in the datasource form to ensure we can check if the configuration is correct.

One should also add a test case `testValidateDatasourceWithMissingRegionWithNonAmazonProvider`.

**Comment by rohan-arthur** [comment]
aws market share: 33%
google cloud market share: 10%

appsmith s3 usage in 6 months: 148
if this represents the 33%, then expected reach is 45

**Comment by nikhil-babar** [comment]
@Nikhil-Nandagopal I would like to work on this issue, plz can you assign me this issue

**Comment by itsparser** [comment]
@trishaanand Are you guys still working on this ticket

**Comment by 62d2** [comment]
@trishaanand are you guys still working on this ticket

**Comment by sak-90** [comment]
@trishaanand I would like to work on this issue. Please assign this to me.

**Comment by abhay-singhal** [comment]
Hey! Can I pick on this issue

**Comment by Nikhil-Nandagopal** [comment]
@abhay-singhal yes you can. Please go ahead

**Comment by abhay-singhal** [comment]
Acknowledged, starting to work on it

**Comment by NilanshBansal** [comment]
@AnnaHariprasad5123 has raised a PR for this issue here https://github.com/appsmithorg/appsmith/pull/33938.
After testing, we have found one blocker (Delete multi files is failing). Rest everything LGTM.
Ref: https://github.com/appsmithorg/appsmith/pull/33938#issuecomment-2157143812

We are currently waiting for this blocker to be resolved only then we can merge this PR in.
cc: @rohan-arthur
