### ISSUE TITLE
[Enhancement] Improve table widget header on toggle

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#6905]
1. The sort icons have very low contrast.
<img width="899" alt="Screenshot 2021-08-26 at 5 30 51 PM" src="https://user-images.githubusercontent.com/88306433/130959283-34bcf4f2-9635-4a4f-9ff3-9d1c3c301d97.png">

2. The ascending arrow touches the bottom border of the header cell.
<img width="847" alt="Screenshot 2021-08-26 at 5 33 29 PM" src="https://user-images.githubusercontent.com/88306433/130959474-9c3c29fc-05e9-4b50-8a5d-519cabef66fa.png">

3.  On cycling through the sort order by clicking the table header, the icon pushes the header text to the right and after the icon goes away after couple of clicks, the text comes back to the original position. Basically the header texts fidgets back and forth on click; the icon should ideally be on the right side rather than the left.

**Comment by PriyanshX1902** [comment]
Hey @somangshu @ashit-rath can i take up as my first issue?

**Comment by somangshu** [comment]
Thanks for showing the intrest! Go Ahead @PriyanshX1902 😄 All yours, assigning this to you

**Comment by kapshar** [comment]
Hey @somangshu  @ashit-rath, I would like to work on this issue can you assign it to me.

**Comment by Cool-Runningz** [comment]
Hello! I am interested in working on this issue if it is still available. Please and thank you!

**Comment by somangshu** [comment]
Hey @Cool-Runningz apologies, but this issues was already assigned. Can you please look under the hacktoberfest label to find other issues you might be interested in

**Comment by somangshu** [comment]
Greetings @Cool-Runningz, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by Cool-Runningz** [comment]
@somangshu Thank you for assigning me this issue. I have read through the Contribution Guidelines and the PR of the work is linked above and ready for review. Thanks!

**Comment by somangshu** [comment]
Thanks @Cool-Runningz, I'll look into it
