### ISSUE TITLE
[Bug] Dropdown Selector Text shrinking

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#6909]
## Description

Shown in the video below
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8f7559dc6a474e5bb9dc63ccc5f332ab-00001.gif)](https://www.loom.com/share/8f7559dc6a474e5bb9dc63ccc5f332ab)

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to New page
2. Click on Generate CRUD page
3. See error

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by RakshaKShetty** [comment]
The issue is fixed 
![image](https://user-images.githubusercontent.com/45958978/131982995-30ddd608-ba78-4b67-8a1e-e09dad8e6c1e.png)
