### ISSUE TITLE
[BUG]Login form not centered

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#691]
## Description
The login form isn't centered when the social login options are disabled
<img width="681" alt="Screen Shot 2020-09-23 at 3 50 40 PM" src="https://user-images.githubusercontent.com/30255708/94000445-cb00f680-fdb4-11ea-83b8-cbe6615dd30b.png">

This is what the login form looks like when social logins are enabled
<img width="646" alt="Screen Shot 2020-10-01 at 5 56 08 PM" src="https://user-images.githubusercontent.com/30255708/94808908-78a48300-040f-11eb-8bb0-76267f7952a2.png">

### Important Details
 - Version: [Self-Hosted vx.x]
 - OS: MacOSX
 - Browser: [Chrome

**Comment by areyabhishek** [comment]
@mohanarpit Couldn't help but assign this to you 🤣

**Comment by riodeuno** [comment]
This seems to be due to the wrapping component which adds padding to the right. This looks fine when we have the divider and  the social login buttons, however, it prevents the children from stretching and filling the parent container.

**Comment by gilga98** [comment]
is this issue still open?
