### ISSUE TITLE
[Bug] Table with correct data shows repeated error messages

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6912]
Reported by a user on Intercom. They are seeing a lot of errors when they load their application. The errors are slowing down the page load, and they prevent the user from interacting with the app.

<img width="154" alt="Screen Shot 2021-08-27 at 1 42 06 AM" src="https://user-images.githubusercontent.com/30255708/131029525-6f377d67-6076-4dd8-b585-7a7a0b0d8977.png">

**Comment by mohanarpit** [comment]
This is resolved. The SQL query being generated was invalid. Fixed it with a little bit of JS.
