### ISSUE TITLE
[Feature] Create a tab dynamically

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#6916]
## Summary

We cannot create a new tab dynamically right now.

## Motivation

Use Case: I have a tab widget, in one of the tabs I add a table called orders. In the order table I add a column of type link. When I click on the link I want to create a new tab adjacent to existing ones. 

## Additional Context

Create new tab adjacent to users and orders when id column is clicked
<img width="869" alt="Screenshot 2021-08-27 at 9 06 55 AM" src="https://user-images.githubusercontent.com/89374972/131068131-3eaee092-72c8-462d-b61b-2ece91817d40.png">

**Comment by dilippitchika** [comment]
Ok, one thing i don't understand is how would someone add content in this tab dynamically? 

Like even if we give the option to create a tab, no one will be able to add content dynamically inside it i believe. 

I am closing this @Nikhil-Nandagopal do let me know if you find a lefit use case
