### ISSUE TITLE
[Bug] Cannot select colour from colour picker (on release)

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6922]
## Description
Colour picker opens up when user clicks on the text part of an object but does not allow colour selection

### Steps to reproduce the behaviour:
1. Go to any widget with a colour field on the property pane and click on the text part of the object. Colour picker appears and can be clicked but changes are not relefected.
![image](https://user-images.githubusercontent.com/79509062/131084280-b35c74d1-a4bb-41dd-b3f5-a0b42babe184.png)

2. Now click on the icon and repeat colour selection process - colour can be selected
![image](https://user-images.githubusercontent.com/79509062/131084402-39076acd-3860-43ed-94d1-05b0691197ed.png)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy preview

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e3bc8c2f52744a64bd9ac15d78908664-00001.gif)](https://www.loom.com/share/e3bc8c2f52744a64bd9ac15d78908664)

**Comment by somangshu** [comment]
closing this in favour of #6978
