### ISSUE TITLE
[Enhancement] Tooltip should be provided for clear logs icon in debugger

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6924]
## Description
Provide a tooltip for 'clear logs' icon in the debugger

![image](https://user-images.githubusercontent.com/79509062/131090322-00aaa06d-ba98-4ee4-9d7c-ecb773880813.png)

**Comment by sbalaji1192** [comment]
@ramsaptami Being done as part of https://github.com/appsmithorg/appsmith/issues/6759
