### ISSUE TITLE
[Bug] Obfuscate data sent to intercom

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#6933]
## Description
There should be an option to disable intercom on self hosted
The email sent to intercom should be hashed

### Important Details

- Version: Self-Hosted v1.5.15

**Comment by rishabhsaxena** [comment]
##Steps to verify:
This should be obfuscated on self hosted instances and not for `app.appsmith.com`

1. From the `/applications` page, open the network tab, and add `intercom` as the search string
![image](https://user-images.githubusercontent.com/1944800/132310359-5c54718d-b751-4843-98a9-0972371acb55.png)

2. Reload the `/applications` page, check for the `/ping` or `/event` requests, user related data such as the `user_data` param, should be obfuscated

**Comment by yatinappsmith** [comment]
I am not sure if this fix is in the master, hence reopening this issue
<img width="455" alt="Screenshot 2021-09-07 at 2 18 36 PM" src="https://user-images.githubusercontent.com/84702014/132316599-5fa322ee-67b8-4eda-bc8e-ffbb98c9de57.png">
<img width="575" alt="Screenshot 2021-09-07 at 2 22 46 PM" src="https://user-images.githubusercontent.com/84702014/132316607-5afce4c7-936f-4f00-bbc9-675004687054.png">

**Comment by Nikhil-Nandagopal** [comment]
This is now fixed
