### ISSUE TITLE
[Bug] Checkbox is not reset on form post

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#6945]
### The issue

One of the views in an app I'm working on has a Checkbox widget. This widget determines how some of the data posted by the form is to be shaped. The checkbox is not reset to its default un-checked state when the form is posted. 

### Description of the form

The form is a bit complex and the issue is probably hidden somewhere in this complexity. The Submit button has two scripts, one for the _onClick_ action and one for the _Reset form on success_.

As the validity of the form depends on the sum of the numbers in the PlantCount fields not exceeding a certain value the _onClick_ handler checks this sum and returns false if the value is too large.

This in turn necessitates a script in the _Reset form on success_ field that returns true/false based on the same numeric check as onClick handler's. The reason for this is that otherwise the whole form is reset even if it isn't posted when the onClick check stops the posting of the form. This is not so nice to the user that now has to enter all values once more.

Video of the bug is to be found  [here](https://user-images.githubusercontent.com/142613/131216356-c0ca6e0e-7d9f-4752-9c49-ce3ac398adc8.mp4)

### Can't replicate with a trivial form

I have tried to create a mock form that displays the same issue, but a "trivial" form with a couple of Selects and a Checkbox works as expected. When the form is posted, and the Submit button's _Reset form on success_ property is true a checked Checkbox reverts to being unchecked as expected.

### Mock app of the whole form with the bug

So I'm taking the the whole form and creating a stand-alone app from it. The form relies on a Google spreadsheet and I'm supplying the link to a copy of that so the app can be set up to work properly. I hope this works, if nothing else, since the Google sheet is accessible to anyone with the link, it should be possible to make a copy of it and make that writable if there is an issue with the one I provide. Google works in mysterious ways, and sometimes I have had to confirm with Google multiple times to get the connection to a sheet working.

The JSON of the app is [here](https://github.com/appsmithorg/appsmith/files/7070627/Checkbox.test.txt). Since Github doesn't allow JSON files you'll have to rename it :wink:

[Link to the google spreadsheet used as backend](https://docs.google.com/spreadsheets/d/1EBuOa-Hg41QiE4stj_thhVz5o791-yNS2v0ySoOi5-8/edit#gid=0)

### Working example and possible connection to a similar issue

Also I have set up the app in an organization on the Appsmith cloud that @Tooluloope shared with me when looking at another bug. He wanted to confirm the issue and then we were interrupted by the weekend so I don't think there's an issue for it yet. However I have a suspicion that the underlying problems might be related, as that bug also has to do with widgets not updating properly when posting to a Google sheet.

### Important Details

- Version: Cloud
- OS: Linux Mint 19
- Browser: FireFox
- production

**Comment by somangshu** [comment]
@zzgvh thanks for reporting this, We are looking into this

**Comment by Tooluloope** [comment]
I think this issue is fixed, wasn't able to reproduce it.
https://www.loom.com/share/b47f176b190e43abb5df1b034db931df

**Comment by zzgvh** [comment]
Clarification on how to trigger the bug using the above app: 
* For the first select, choose JS00-77-001
* For the second select, choose JS00-B-001
* For all three number inputs with their values set to 0, click the up arrow to set the value to 1 and then click the down arrow to set it to 0 again. The reason for this being necessary is issue #8012. When you have done this the submit button should light up.
* Check the checkbox
* Inspect the Reset form on success field of the submit button to make sure that it is `true`
* Submit the form. The checkbox will remain checked.

To repeat the steps above, delete the last two lines (8 and 9) from the all_events tab of the Google sheet.

**Comment by Tooluloope** [comment]
@zzgvh Could you check this video, I believe this issue doesn't exist as of now.
https://www.loom.com/share/4c968b57bd124ac39701f9c644103db5
