### ISSUE TITLE
[Bug] Voice recorder - There is no specific file type to download audio files 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6958]
## Description
Deploy Preview - https://deploy-preview-6702--appsmith-editor-ce.netlify.app/applications/
It is observed that there is not specific file type to download audio files and currently not able to download recorder audio 

Expected Result:
User should be able to download recorder audio file

### Steps to reproduce the behaviour:

1.Launch appsmith app in the deploy preview - https://deploy-preview-6702--appsmith-editor-ce.netlify.app/applications/
2.Drag and drop voice recorder widget 
3.Click on recorder button and start recording audio 
4.On the action - Recoding complete - Click on download option and observe 

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur ]
- Browser [chrome, safari]
- Environment [deploy preview]

<img width="1680" alt="Screenshot 2021-08-25 at 5 59 45 PM" src="https://user-images.githubusercontent.com/35128442/131308024-f4e5c214-a512-405b-bb31-db9cfceeb750.png">

**Comment by somangshu** [comment]
@YogeshJayaseelan why is this assigned to me?

Please assign such bugs from the DP to the author directly

**Comment by sbalaji1192** [comment]
@souma-ghosh Could you evaluate if this is a good first issue?
