### ISSUE TITLE
[Feature]Need to collect data on a api batch loop 

### ISSUE THREAD

**Issue by lyn444** [appsmithorg/appsmith#6966]
## Summary

Provided an array of `UsersID`, we need to do data aggregation on each item by calling some RestAPI that get `UserData`.
Then we need to accumulate all the `Users.contributionCount` and get the final result `TeamContributionCount` which should be bound to an Textbox

Since the Api are async, there is no easy way to do this,
Tried the storeValue on each of the API.run but seems that there is racing issues.

Also tried the recursive continuation but this issue that I reported earlier prevented this way too.
https://github.com/appsmithorg/appsmith/issues/6963

Apparently, there is no way to do this.

Since this is a very common use case for us, could you make a new feature that handles this?

Several suggestions:
* Support await for api.run so we can make use of the results (this would be the best experience)
* or Provide a way to pass variables inside the api.run lambdas so it could be mutated (of course in a thread-safe way if this involves backend)
* Or fix the issue above so at least the recursive continuation workaround could be used. (least preferred)

**Comment by Nikhil-Nandagopal** [comment]
@lyn444 we will support Promise.all soon so you can wait for all functions to complete and aggregate their results
