### ISSUE TITLE
[BUG] Regex for text isn't working in input widget.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#697]
## Description
Used Regex `(/^.{6,}$/)` to throw error on entering less than 6 chars for text input in Input Widget.

Actual:- Throws error for all conditions.
Expected:- Error should be hidden for text with 6 or more chars.

<a href="https://ibb.co/7NSQsbz"><img src="https://i.ibb.co/5x1kb29/Regex-Text-Issue.png" alt="Regex-Text-Issue" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay great catch. For some reason it works without the / at the start and end

**Comment by deepakchethan** [comment]
Hello @hetunandu, I can take this up if it's still open.

**Comment by Nikhil-Nandagopal** [comment]
@deepakchethan I'm assigning this to you. Great to see all your contributions! Keep em coming

**Comment by deepakchethan** [comment]
Thank you @Nikhil-Nandagopal, I went through the code and this seems like the correct behaviour. As we are using `new RegExp("/^.{6,}$/")` which is resulting the regexp of `/\/^.{6,}$\//`. So this is resulting errors. 

According to the hint we are not expecting the regex to being and end with `/`.  We could remove `/` in the beginning and end if the user provides it, would this be the proper fix for this?

**Comment by Nikhil-Nandagopal** [comment]
@deepakchethan after a little digging just removing the / won't work because the Regex contructor takes the flags as a second identifier. I don't have a good solution right now but we need to think of a clean way to convert a string to a Regex

**Comment by deepakchethan** [comment]
We could parse the regex as seen in https://github.com/IonicaBizau/regex-parser.js/blob/master/lib/index.js

**Comment by Nikhil-Nandagopal** [comment]
This looks good! Remember to add a case to handle invalid inputs because while a user is typing, the Regex Will be invalid till it's complete
