### ISSUE TITLE
[Bug]Multiple errors is displayed in the toast bar when the user tries to upload the file in generate page s3. 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6975]
## Description

[What happened]The error is displayed when the user tried to upload the file in generate page s3. 
Inspite of the error displayed the file seems to be uploaded successfully in the list.

### Steps to reproduce the behaviour:

1. Go to the application
2. Select Generate from table data 
3. Select s3 data source
3. Now the CRUD page will be generated
4. Now click on add files
5. click on the select file button add a data
6. now click on the upload button 
7. the error message is displayed as in the screenshot
![image](https://user-images.githubusercontent.com/45958978/131355175-0a1bf359-97fe-4ba9-b1e2-1f7e23d3ce0c.png)

Expected result: the error message should not be displayed

### Important Details

- Version: [Cloud]
- OS: [MacOS]
- Browser [chrome]
- Environment [ release]

**Comment by SatishGandham** [comment]
Problem seems to be in the run call. second parameter, params is not passed to the success call back.

`{{
FilePicker.files.forEach((file, index) => {
	CreateFile.run((response, params)=>   { 
		showAlert('File Uploaded','success'); 
if (params.isLastFile) {
	ListFiles.run(() => {closeModal('Upload_Files_Modal'); resetWidget('FilePickerOld')})	
}
}
	, () => showAlert('File Upload Failed','error')	
	, {fileIndex: index, name: selected_files.items[index].update_files_name.text, isLastFile: index == (FilePicker.files.length - 1), });
	return true;
})
}}`

**Comment by Nikhil-Nandagopal** [comment]
@SatishGandham can you be more specific? Which param is not passed and why is there a problem?

**Comment by SatishGandham** [comment]
@Nikhil-Nandagopal Success callback is looking for a property on the additional parameter passed to run, but that is not passed to success callback.
```
if (params.isLastFile) {
				ListFiles.run(() => {closeModal('Upload_Files_Modal'); resetWidget('FilePickerOld')})	
			}
```

**Comment by Nikhil-Nandagopal** [comment]
@SatishGandham , it is passed here
```
            {
			fileIndex: index, 
			name: selected_files.items[index].update_files_name.text, 
			isLastFile: index == (FilePicker.files.length - 1), 
		}
```

**Comment by SatishGandham** [comment]
@Nikhil-Nandagopal , Yes, third param should be passed to the success and error callbacks, but it is not passed. So the issue.

Other than the error, files are uploaded successfully.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu did the JS contract break?

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @RakshaKShetty this is a blocker and will break prod if it goes out
