### ISSUE TITLE
[Bug] Color Picker doesn't work

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#6978]
## Description

Color picker not working for buttons, icon button, menu button, and container.
Not sure if there are others

### Steps to reproduce the behavior:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/35100b1c91f04a01b9a93ca4dbabaf33-00001.gif)](https://www.loom.com/share/35100b1c91f04a01b9a93ca4dbabaf33)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Browser [e.g. chrome,]
- Environment [release]

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @Tooluloope can we fix this on priority?

**Comment by Tooluloope** [comment]
@somangshu @Nikhil-Nandagopal Just realized it works when the color is Double clicked.
Is that the desired behavior?

**Comment by Tooluloope** [comment]
@somangshu, I think this issue and  https://github.com/appsmithorg/appsmith/issues/6922 are the same

@vibhandikyash removing the onBlur Function seems to fix these issues with the color picker.
https://github.com/appsmithorg/appsmith/pull/6305/files/dfe408560332d5bd175a67291c87e3db5076207d#diff-2f8f820a6f7406c1886138be13bc73fe4578c5137d2e2e1d2951bdacb9b0a4a9

**Comment by vibhandikyash** [comment]
@Tooluloope I tried to reproduce the same on release as well as the prod and it's working as expected. Pl. check the video below.
cc: @somangshu 

https://user-images.githubusercontent.com/17437380/131466939-03df254a-412b-4893-854e-175886bd9d84.mov

**Comment by Tooluloope** [comment]
@vibhandikyash are you using double click or single click?
Double click seems to work on my end

**Comment by vibhandikyash** [comment]
@Tooluloope  Single click. Nowhere we have added double click behavior!

**Comment by somangshu** [comment]
@Tooluloope @Nikhil-Nandagopal this works for me as well on release and prod. 

@ramsaptami please confirm

**Comment by ramsaptami** [comment]
@somangshu It's working fine on prod but doesn't seem to be working on release yet.

**Comment by somangshu** [comment]
Thanks for chiming in guys 😄  With #6536, we will have the colour picker open from the input field gone. This was a fix related to colour picker covering the input when the property pane is small

Furthermore, @ramsaptami suggested that the default colour picker icon/selector should be revamped to better show its clickable.

@Nikhil-Nandagopal does the above sound like a plan of action here?
