### ISSUE TITLE
[BUG] When an app is copied, page name is also appended with 'copy' alongside app name

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#698]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, create an app with app name 'B'
3. Click on edit, and observe that page name is **Page 1**(Which can be seen right under B)
4. Come to the homepage by click on appsmith_ on the top left corner
5. Duplicate app B --> new app with app name 'B Copy' gets created
6, Click on edit for App 'B Copy'

Actual Result: Under app name 'B Copy', page name is written as 'Page 1 Copy'
Expected Result: Under app name 'B Copy', page name should still be 'Page1'

Attachment: https://drive.google.com/drive/folders/1H13ME7V3iE7EXY1M069e-kwgX0L7-YdM?usp=sharing

**Comment by trishaanand** [comment]
Analysis : This issue is happening because we are reusing the Page Clone function inside the Application Clone function. As part of page cloning, a new name is also ascertained and forcibly changed ( a feature required for simple page cloning, but not required for application cloning).

**Comment by daniel-shuy** [comment]
I've created a PR to fix this, it will still append ` Copy` when cloning Pages, but not when cloning Applications
