### ISSUE TITLE
[BUG] Issues with duplicating an app

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#699]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, copy an app multiple times

Issue 1 : As can be seen in the screenshot, when there are multiple apps (say 10) under an organization, there is slight mis-alignment.
Issue 2 : Every time an app is copied, logo changes.
<img width="1780" alt="Screen Shot 2020-09-24 at 12 14 51 AM" src="https://user-images.githubusercontent.com/49346036/94056713-489c2500-fdfc-11ea-8db2-0ab125ccbc7e.png">

**Comment by Nikhil-Nandagopal** [comment]
The logo change can be ignored, the alignment and space issues need to be fixed

**Comment by satbir121** [comment]
@Nikhil-Nandagopal A solution can be to add a max of 3 lines for the app name and then show an ellipsis.

**Comment by draco-malfoy** [comment]
I would like to take this @mohanarpit @Nikhil-Nandagopal, but would need some assistance.
Thank you.

**Comment by satbir121** [comment]
@draco-malfoy Thanks for your interest but this issue has already been fixed. Please check out other issues on the [this link](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22+label%3AFrontend).
