### ISSUE TITLE
[Bug] Changing data source for binding on table widget throws a latent error and does not show error on debugger

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6993]
## Description
When data for a table is changed via sniping mode, page numbers are not restricted (Server side pagination is **on** on table widget) and user is able to navigate beyond limit and error message displayed shows query run failure and clicking on 'Debug' button shows no error in the debugger.

### Steps to reproduce the behaviour:
1. Generate a page using Google Sheets
2. Now create a new query on a different Google Sheets and connect to existing widget from Step 1 through sniping mode 
3. Click on page numbers and observe there's no page limit and no error is displayed until much later. On clicking 'Debug', debugger opens with no error displayed.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f89898f028f5497db847519b9ff47fb8-00001.gif)](https://www.loom.com/share/f89898f028f5497db847519b9ff47fb8)
![image](https://user-images.githubusercontent.com/79509062/131459894-f4ae14ec-8e2e-4eb9-a6fb-72c9a77606ed.png)

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami I think the Table is calling the older SelectQuery onPageChange and since this query is not bound to display on the table, you cannot observe the loading. It is then eventually failing in the background due to a timeout. This seems expected

**Comment by ramsaptami** [comment]
@Nikhil-Nandagopal Since the table is now bound by a new query, should it look at the older binding at all?

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami the table data field is bound to the new query but the onPageChange is still bound to the old query

**Comment by ramsaptami** [comment]
I understand this a specific edge case but I feel there could be a minor change here. Also, since nothing appears in the debugger, we can remove the **Debug button** on the toast messages.
