### ISSUE TITLE
[Bug] Creating an action doesn't switch pages

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#6996]
## Description

In a multi-page application, when an action is created, the editor doesn't switch pages. This causes problems especially when using the "Suggested Widget" feature.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create an Appsmith app with 2 pages
2. Navigate to Page2
3. Click on + Datasources & create a new API on Page1 from the entity explorer
4. Try to bind the results of the API using the "Suggested Widget" feature.
5. Notice that the new widget gets created on Page2 instead of Page1 where the API is present. This leads to invalid data binding.

This is potentially very confusing for a new user who is trying to understand how Appsmith works.

Video Link: [
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5a0ff5e6f1d64128b89d18d00fb4a780-00001.gif)](https://www.loom.com/share/5a0ff5e6f1d64128b89d18d00fb4a780)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena can we merge the fix in?
