### ISSUE TITLE
[Bug] Dragging and dropping input widget throws undefined error on the default field 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7002]
## Description
Release - Input widget - Bu default dragging and dropping input widget to the canvas - undefined error is displayed on the default field 

Expected result:
Error should not be displayed by dragging and dropping input widget 

### Steps to reproduce the behaviour:

1. Launch appmsith app in release environment 
2. drag and drop input widget and observe

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [release, deploy preview]

<img width="1680" alt="Screenshot 2021-08-31 at 2 08 54 PM" src="https://user-images.githubusercontent.com/35128442/131475435-73dd2906-d554-4180-82f3-f28e7089b42f.png">

**Comment by somangshu** [comment]
Default `undefined` value should be acceptable @techbhavin. Also the field is optional so null/undefined both should be acceptable. Please prioritise this higher
