### ISSUE TITLE
[Bug] Field colours are inconsistent and don't change in view or edit more

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7003]
## Description
Field colours are inconsistent on Google Sheets query page , i.e. cannot differentiate mandatory/optional fields and the background colour does not change between edit and view modes

### Steps to reproduce the behaviour:
1. Create a new query for Google Sheets source and observe the variations in field colours on the page and also when you click on each field to edit and when field is in view mode - expectation is to follow designs on figma/other datasources
2. Mandatory fields like row offset and row limit are not marked with an **asterisk symbol** as seen on the **Method field**

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

![image](https://user-images.githubusercontent.com/79509062/131477245-d4389665-fea1-4d53-ac63-b38709232fb8.png)

**Comment by ajinkyakulkarni** [comment]
This will get resolved with #10235

**Comment by nidhi-nair** [comment]
@prapullac adding to your queue since this should already be fixed now.

**Comment by yatinappsmith** [comment]
Missing * is still on release 
![image](https://user-images.githubusercontent.com/84702014/173268214-8d4c16cd-e7f5-495d-ad0b-13ad033ae184.png)

**Comment by nidhi-nair** [comment]
Hey @yatinappsmith! Since this is a fix that is coming in with UQI, could you please test this on the deploy preview instead?
