### ISSUE TITLE
[Enhancement] Add table names/sheet names to data source query page similar to how Generate Page feature displays them

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7005]
## Summary
Currently our Generate Page feature displays table names/buckets for S3 data/sheet names via a dropdown. This feature would be quite useful for the user if it's extended even to the query page.

![image](https://user-images.githubusercontent.com/79509062/131478557-6fbb54f7-d7cb-461a-bd1b-737625b459a9.png)
![image](https://user-images.githubusercontent.com/79509062/131478619-9aa93e7b-cbd6-4d9b-81ad-e223e47a15ba.png)

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal can you please comment on whether scoping Google sheets datasources by sheet is something we want to be doing?

**Comment by nidhi-nair** [comment]
Oh I see, misunderstood that it meant we needed to move this to datasource level. Alright, in that case closing this issue in favour of the entity selector component issue. Plugin migrations will take care of this on a per plugin basis.
