### ISSUE TITLE
[Bug] UI: Visually displeasing multipart form body

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#7006]
## Description

<img width="521" alt="Screenshot 2021-08-31 at 10 03 39" src="https://user-images.githubusercontent.com/46670083/131476998-6f60670f-6dda-4263-95a0-e7511139517a.png">

### Steps to reproduce the behaviour:

1. Go to the new-Api page
2. Change request type to POST
3. Select "body" tab option
4. Select "MULTI-PART" tab option

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [release, deploy preview]

**Comment by areyabhishek** [comment]
@ohansFavour thoughts on how to make this better? @aakashDesign check this out

**Comment by Nikhil-Nandagopal** [comment]
This is solved in our new design system
