### ISSUE TITLE
[Bug] List widget: Does not accept Array<Array>

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7024]
## Description

After the new validation changes the list widget has stopped accepting Array of arrays. One of my apps broke because of this. Now the widget is only accepting Array or Objects. Since the earlier is a common use case, we might have to re evaluate this

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Drag and Drop a list widget
2. Add array or arrays to the list data
3. check the error out 

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [production]

**Comment by tomjose92** [comment]
Commenting here to watch the issue. Eagerly waiting for the fix 🤞

**Comment by tomjose92** [comment]
Is this fix available on https://release.app.appsmith.com or https://app.appsmith.com ?

**Comment by somangshu** [comment]
Hey @tomjose92 this is now available at the release env, As soon as the QA has verified this we will promote it to the prod

**Comment by tomjose92** [comment]
hey @somangshu, I tested the same in release.app.appsmith.com
Still facing the issue. Uploaded the image here.
<img width="1192" alt="Screenshot 2021-09-06 at 5 43 38 PM" src="https://user-images.githubusercontent.com/5265702/132216091-5c6fafc6-16fe-47b9-85f5-8350faa8f6f6.png">

**Comment by jsartisan** [comment]
@tomjose92 how did you add the table inside the list? we disallow that operation

**Comment by jsartisan** [comment]
@tomjose92 the fix is for the list widget and you are doing the binding in table widget in list widget. that won't work.

**Comment by tomjose92** [comment]
@jsartisan, I made the table really small and was able to put the table inside the list [first row], and it was replicated across all list rows.
So your saying I wouldnt be able to add a table or even a select button inside the list?

**Comment by somangshu** [comment]
We dont support the following
```
WidgetTypes.TABLE_WIDGET,
WidgetTypes.LIST_WIDGET,
WidgetTypes.TABS_WIDGET,
WidgetTypes.FORM_WIDGET,
WidgetTypes.CONTAINER_WIDGET,
```

**Comment by vivekverma2312** [comment]
@jsartisan Tested the fix on the release and working fine. Now we are accepting Array of arrays in List widget.
