### ISSUE TITLE
[BUG] Misleading "Connecting to Databases" screenshot

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#703]
## Description

Screenshot on the "Connecting to Databases" (https://docs.appsmith.com/core-concepts/connecting-to-databases) needs to be updated to the new UI (something like the one below)

![image](https://user-images.githubusercontent.com/4999463/94108497-0c4ce100-fe5d-11ea-90e3-543d062b266b.png)

### Why is this needed?

- APIs are now part of Pages.
- Only 3 entities are now part of the navigation instead of 5.

**Comment by SamriddhiMishra** [comment]
@Nikhil-Nandagopal Can I use the same image(above) to replace?

**Comment by SamriddhiMishra** [comment]
@Nikhil-Nandagopal  I have created a PR for this https://github.com/appsmithorg/appsmith-docs/pull/21
Please Review.

**Comment by hetunandu** [comment]
Fixed by [appsmithorg/appsmith-docs#21](https://github.com/appsmithorg/appsmith-docs/pull/21)
