### ISSUE TITLE
[Feature] Camera widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7033]
## Summary

As a dev, I should be able to provide the end user an option to take a picture or record videos through there system camera using browser permissions

## Motivation

I want to be able to use the system camera and process the data further in an API/Query

## Requirements

| Title | Desc | Default | Comment |
| ---- | ----- | ----- | ----- |
| mode | Camera \| Video | Camera | Mode will let the user choose if picture is required or video recording |
| capture photo / video | Option available on the widget in the camera mode. On click we should provide the base64 output | - | - |
| base64 | internal property to fetch the image captured | - | Need to check what format can the video be exported in |
| custom height / width | custom resolution of the exported image is allowed | fallback to package default | - |
| capturing side | widget should have an option to list all devices and let the user choose one of them | first available | - |
| mirrored | show camera preview and get the screenshot mirrored | boolean:false | - |
| permission | request for the necessary permission through the browser. If the user has denied the permission show the message clearly | requesting permission | - |

> Recommended [package](https://www.npmjs.com/package/react-webcam) to be used

## Developer Design Handoff:
https://www.figma.com/file/9E6h3DaPTEZX1uhMye89bi/Camera-Widget?node-id=2%3A263

**Comment by zeroclasses** [comment]
A very useful feature 👍

**Comment by somangshu** [comment]
Hi @zeroclasses 👋  Thanks for the comment, This helps up prioritise the issue. Thanks for you valuable input 😄

**Comment by shwetha-ramesh** [comment]
@wmdev0808 retested this PR based on @prapullac comments. Here are the below findings for the same and some new issues found.

#8785: Fixed

#8788: Still exists. 
https://loom.com/share/7997622dd9cf4bcbbd3aff8250a5854d

#8789: Working fine

#8791: Fixed

#8792 : Still exists. In figma document the widget appears grey when permission is denied, where as in DP the widget appears black
In figma doc
![image](https://user-images.githubusercontent.com/92293815/142856166-8f99a840-667a-4a04-a52f-5ec1c1f666a1.png)
In DP
![image](https://user-images.githubusercontent.com/92293815/142856345-8e316866-9e9a-4169-8382-dab490e14ea3.png)

#8793 : Fixed

#8795: Still exists

#8798 : Still exists.

**_NEW ISSUES_**

1. As per figma document Disabled state must appear grey, in DP it appears black
In figma doc
![image](https://user-images.githubusercontent.com/92293815/142864270-ecf3075a-4857-4235-8d5c-939c1d17cd5b.png)
In DP
![image](https://user-images.githubusercontent.com/92293815/142864302-4621f0a0-3631-4393-ab2f-55d318982a89.png)

2. As per figma doc the tooltip has a black background and then a white text, in DP it has white background and black text.
In figma doc
![image](https://user-images.githubusercontent.com/92293815/142864861-64507757-9edf-484f-a242-32a0f0d53c66.png)
In DP
![image](https://user-images.githubusercontent.com/92293815/142865487-6a4ffe5c-0d65-424a-9d05-77e552f08f2f.png)

3. No setting icon found when user clicks on 'refresh' button as per figma doc
![image](https://user-images.githubusercontent.com/92293815/142865750-703b77a8-664f-44b7-9917-5935f2797cb4.png)

4. Each time user changes from Desktop mode to different mode the transition does not appear smooth.
https://loom.com/share/0690b5f2c4d14e6bb0958820f3366a81

**Moving to In Progress.**
