### ISSUE TITLE
[Bug] Intermittent issues on JS editor 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7035]
1) Intermittent: binding issue (
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ae241d8af6b64743b19fc84773570856-00001.gif)](https://www.loom.com/share/ae241d8af6b64743b19fc84773570856)
2) Intermittent: Suggestions are not displayed inside the JS editor
3) Intermittent:  RUN is not functional (
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5092c0aabe8144e6b457d1ad2c48a383-00001.gif)](https://www.loom.com/share/5092c0aabe8144e6b457d1ad2c48a383)
4) Intermittent: Cyclic dependency and app breaks when the function is added inside a function (
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b7a224b8b260456d9c9ab623eaa7e31d-00001.gif)](https://www.loom.com/share/b7a224b8b260456d9c9ab623eaa7e31d)

**Comment by ApekshaBhosale** [comment]
@prapullac can you give me steps to reproduce the cyclic dependency error here? because I tried it's not happening so looking if any particular case it is happening

**Comment by ApekshaBhosale** [comment]
@prapullac for RUn can you paste what is hello.run()?

**Comment by prapullac** [comment]
@Apeksha 
Cyclic dependency :
https://www.loom.com/share/2fb99041df094ca9a675e086715657f0
I think its because hello inside the function and also the name of the function is so
![Screenshot 2021-09-02 at 1 10 12 PM](https://user-images.githubusercontent.com/71753653/131805048-0df5fcaf-6f9e-4dd7-8b38-61ac49ad9950.png)

**Comment by prapullac** [comment]
We can close the issue as this is not reproducible currently.
