### ISSUE TITLE
[Bug] List widget showing incomprehensible error in view mode

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#7036]
## Description

In the view mode, the list widget shows an error that is not understandable or useful to users.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to the standup app
2. Choose updates for Actions Pod for 30th Aug, 2021
3. See error

<img width="1677" alt="Screenshot 2021-09-01 at 9 51 15 PM" src="https://user-images.githubusercontent.com/458946/131707721-a9aa0576-ba69-4713-974e-10ab6771c23c.png">

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by SatishGandham** [comment]
I'm unable to reproduce this, but this error should not be shown in view mode.

**Comment by Tooluloope** [comment]
I'm unable to reproduce this issue now.
