### ISSUE TITLE
[BUG] Ctrl + V to paste copied widgets doesn't work

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#704]
## Description

Copied a text widget and got the alert that the widget was copied. Tried pasting it with Ctrl + V and nothing happens (screen cast below)

### Steps to reproduce the behaviour:

1. Add any widget in an app
2. Click on the name and copy the widget
3. Paste using Ctrl + V to see that there is no duplication of the widget. 

Screencast: https://recordit.co/Ue7WPNNuPe (After copied alert on top right, Ctrl + V does nothing)

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Google Chrome 85.0.4183.102 (Official Build) (64-bit)

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno can you verify this?

**Comment by riodeuno** [comment]
I can verify that this issue exists. I will create PR with the fix for this issue.

**Comment by prapullac** [comment]
Verified the issue and worked as expected
