### ISSUE TITLE
[Bug] Updating certain columns/fields is updating every other column/field in the row

### ISSUE THREAD

**Issue by vnodecg** [appsmithorg/appsmith#7045]
## Description

Appsmith is writing data to every field/column of a row that is being updated in google sheet, despite the fact that the update query intentionally has certain columns/fields omitted from the update.

More detailed explanation:
https://community.appsmith.com/t/solution-to-write-to-a-google-sheet-that-has-array-formulas/232

### Important Details

- Version: Both cloud and self hosted
- OS: All
- Browser: All
- Environment: production

**Comment by yatinappsmith** [comment]
@vivekverma2312 please review this for release blocker

**Comment by Nikhil-Nandagopal** [comment]
@yatinappsmith @vivekverma2312 this isn't a blocker, it's always existed. It happens when there is a formula in the google sheet which we do not handle right now

**Comment by Nikhil-Nandagopal** [comment]
Closing as we don't support GSheet formulas
