### ISSUE TITLE
[Bug] [Regression] GeneratePage does not work

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#7050]
## Description

Generate Page from datasource does not work

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/31699fa9b4ab4ce4a6866baff099bcc9-00001.gif)](https://www.loom.com/share/31699fa9b4ab4ce4a6866baff099bcc9)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by ApekshaBhosale** [comment]
@nidhi-nair here generate a page from Datasource API response are different hence the problem. Can you please checkout if you need to update the backend with the latest release or something?

**Comment by nidhi-nair** [comment]
@yatinappsmith I'm not able to reproduce this issue. It could be as Apeksha mentions, and that a recent build has resolved the issue. Could you please confirm this?

**Comment by yatinappsmith** [comment]
verified on latest DP
