### ISSUE TITLE
[Bug] JSObject are not present in imported application

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#7051]
## Description

JSObject are not present in imported application

### Steps to reproduce the behaviour:

Create an App.
Create a js object hello World
Export and import and app
Imported application does not have jsobjects

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by nidhi-nair** [comment]
Being picked up in #7008, closing this
