### ISSUE TITLE
[Bug] App crashes while trying to run multiple js functions

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#7054]
## Description

[Bug] App crashes while trying to run multiple js functions
### Steps to reproduce the behaviour:

[Bug] App crashes while trying to run multiple js functions

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3c8a64aed3f24e8e87dec97bc37d7238-00001.gif)](https://www.loom.com/share/3c8a64aed3f24e8e87dec97bc37d7238)
[ParallelapiJSe.json.zip](https://github.com/appsmithorg/appsmith/files/7098004/ParallelapiJSe.json.zip)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by ApekshaBhosale** [comment]
@prapullac can you share what are you trying to do here? or can you share console logs from browser?

**Comment by yatinappsmith** [comment]
verified on latest DP
