### ISSUE TITLE
[Feature] In-app feature to announce major updates contextually

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#7060]
Today users can see updates only on the homepage, but we need to also announce major changes inside the editor itself. This will help our users learn about features like group drag n drop, undo/ redo, etc.

**Comment by kocharrahul7** [comment]
<img width="253" alt="Screenshot 2022-04-15 at 10 37 44 AM" src="https://user-images.githubusercontent.com/20532920/163523408-8eb78244-b53d-4fd6-bd3c-31fc227a7c0f.png">
<img width="376" alt="Screenshot 2022-04-15 at 10 37 14 AM" src="https://user-images.githubusercontent.com/20532920/163523415-1ab40d28-8a5b-42f6-95ee-c35275c5c74f.png">


Done
