### ISSUE TITLE
[Bug]The autocomplete suggestion is getting retained even after selecting the suggested value in the queryeditor

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7066]
## Description

[What happened]The autocomplete suggestion is getting retained even after selecting the suggested value in the query pane

### Steps to reproduce the behaviour:

![image](https://user-images.githubusercontent.com/45958978/131840187-1e3cb510-916d-4f36-9d70-3c4a0cc6d518.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [chrome]
- Environment [release]

**Comment by ohansFavour** [comment]
@RakshaKShetty @ajinkyakulkarni  I am unable to reproduce this. Upon selection, the autocomplete suggestion gets closed. Kindly confirm that this issue no longer applies so it can be closed.
