### ISSUE TITLE
[BUG] Inconsistent Result with dropdown filter.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#707]
## Description
Use example JSON and typed to filter the list. On `H`, it shows only the first option whereas with `Ho` it shows the first 2 option.

 `[
  {
    "label": "Home Town",
    "value": "home_town"
  },
  {
    "label": "Working City",
    "value": "working_city"
  },
  {
    "label": "Destination Wedding",
    "value": "dest"
  }
]`

[Drive Video](https://drive.google.com/file/d/1iQiGjK2aWDqx_MbxZUHdpIxbv2-V7d0q/view?usp=sharing)
### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by daniel-shuy** [comment]
This is because `Fuse.js` is configured to use fuzzy matching, with a [threshold](https://fusejs.io/api/options.html#threshold) of `0.6`. If we want it only filter exact matches we need to configure the `threshold` to `0`.

What should be the correct behavior?

**Comment by Nikhil-Nandagopal** [comment]
@daniel-shuy great catch! If it's the default behaviour of the library let's not change it. We were just confused as to why this was happening. Although this wasn't via code, this really was a great contribution. Thank you! 🎊
