### ISSUE TITLE
[Bug] Multi-select not working properly in newly created applications

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#7079]
## Description

Multi-select using the mouse is not working properly in the newly created application.
I tried to add an input widget and button widget. Then tried to select both using the mouse. It was not working.
But, I was able to select all using Ctrl + A.
It was working properly when I went back to all applications view and re-opened the application.

### Steps to reproduce the behaviour:

1. Create a new application
2. Add an input widget and a button widget
3. Try to select both using the mouse and you will see the button is not getting selected

### Important Details

- Version: Cloud
- OS: Ubuntu
- Browser: Brave (Chrome), Firefox
- Environment: production

**Comment by Nikhil-Nandagopal** [comment]
@aswathkk I'm not able to repro this. Are you able to consistently reproduce this?

**Comment by aswathkk** [comment]
Yes, @nikhil 
This bug only happens if I create a new application.

**Comment by Nikhil-Nandagopal** [comment]
@aswathkk could you share a video please? I can't seem to reproduce this

**Comment by aswathkk** [comment]
![selection-issue](https://user-images.githubusercontent.com/10436935/132097778-e22ac03a-97aa-4787-83ed-16fdc4f8f947.gif)
@Nikhil-Nandagopal Here you could see that multiple widget selection was not working initially. Then I had to reload the application editor to make it work.

**Comment by marks0351** [comment]
@aswathkk  can u check release environment. I believe this has been fixed after the widget grouping extended features.

**Comment by aswathkk** [comment]
@marks0351 Yes. This issue is not there on Release.

**Comment by Nikhil-Nandagopal** [comment]
Awesome closing this
