### ISSUE TITLE
[Bug] Currency Input Overlap Text

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#7083]
## Description
Using CNY currency type overlaps with the text in an input
https://downloads.intercomcdn.com/i/o/384523291/a065f95e40447f9bf224463b/image.png?expires=1630655323&signature=796e0d43405d475daac3c1709bc3f002d5eac0bb2451cf57d692dd7ce4f67321

**Comment by somangshu** [comment]
![Screenshot 2021-09-06 at 7 49 37 PM](https://user-images.githubusercontent.com/11089579/132230940-e2e85efd-fcf6-419e-8e97-e70301faa1b3.png)

**Comment by aswathkk** [comment]
Currently, we are making use of [Blueprintjs input component](https://blueprintjs.com/docs/#core/components/numeric-input).
Their implementation is in such a way that the currency symbol (Left Icon) is of fixed width. If the symbol goes beyond a certain width, it overlaps the input text.
To make it flexible, we need to make use of CSS Flex. But if we are making use of flex, then we also need to modify the input box's properties (like the fucus and error UI state) to make it work like the way it works now. That needs a lot of effort.

The alternative way is to modify the design to look like that of [Bootstrap's input component](https://getbootstrap.com/docs/5.1/forms/input-group/)

![Screenshot 2021-09-15 at 12 49 55 PM](https://user-images.githubusercontent.com/10436935/133388890-6a02df41-2a7f-4390-8960-923694f9ebb6.png)

![Screenshot 2021-09-15 at 12 50 17 PM](https://user-images.githubusercontent.com/10436935/133388958-dfc7cc2d-e1dd-4802-9cc7-1db68c7d24d0.png)

Waiting for @momcilo-appsmith's opinion on this.
