### ISSUE TITLE
[BUG] Inconsistent Modal Behavior.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#709]
## Description
In the editor app, the modal shows a different group of backdrop whereas after deploying it's covering the whole screen.

### Steps to reproduce the behaviour:
1. Add Modal to container which covers the subset of the screen.
2. Link the modal to any container item (in our case Dropdown `onOptionChange`) to open the Modal.
3. Modal would be covering a part of screenshot which is neither the whole screen nor the container view.
4. Deploy and Open the modal using change in dropdown value.
5. The modal would be covering the whole screen.

[Video In Action](https://drive.google.com/file/d/1UwkfW1Ksnkg4gwwd3LCxpd645JQN-gIJ/view?usp=sharing).

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay this is expected because in editor it cannot cover the widgets section whereas in viewer the widget section is not there
