### ISSUE TITLE
[Task] Document how the UI code is laid out 

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#7097]
- How the widgets get their data
- How property pane works
- What are evaluations
- Outline of the sagas
- How a widget is put together.
- Touch on actions

**Comment by pranavkanade** [comment]
@Pranay105 @jnikhila I don't think should go on our docs.

**Comment by danciaclara** [comment]
removing this from the doc team's bucket as this is not related to product documentation. cc: @somangshu

**Comment by somangshu** [comment]
I think we already have a fair amount of doc around this
cc @sbalaji1192 @riodeuno 

@SatishGandham lets connect to find what is still missing, and how can this be managed better.

**Comment by somangshu** [comment]
Closing the issues for now
