### ISSUE TITLE
[BUG] Dropdown onOptionChange is triggering on selecting the same option.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#710]
## Description
Dropdown `onOptionChange` event is getting triggered on selecting the same option.

### Steps to reproduce the behaviour:
1. Add `showMessage()` to dropdown's `onOptionChange`.
2. Select any dropdown option and the message should appear.
3. Select the selected dropdown option again and the message will again appear.

[Video In Action](https://drive.google.com/file/d/18RGp31D5OKN6PMUpkMNqIFE-JbHJfzpX/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by hetunandu** [comment]
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone with basic React JS skills looking to start contributing to the repo.

The bug exists in how we trigger the action from the Dropdown Widget. You can contribute by adding a simple check to see if the new selection is the same the the old one. If it is the same, we should not trigger updates or call the action associated with it. Check this out [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/widgets/DropdownWidget.tsx#L138)

> Need more guidance while working on this? Feel free to mention me in a comment on this issue and I'll be happy to help you out 😄

**Comment by wasabigeek** [comment]
Hi, I'd like to take this!

**Comment by Nikhil-Nandagopal** [comment]
@wasabigeek go for it!
