### ISSUE TITLE
[Bug] JS functions have corresponding objects that are capital cased

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7114]
## Description
Autocomplete shows JS functions as objects that are named with a capital case - example, moment() also shows Moment(), function() also displays Funtion()

![image](https://user-images.githubusercontent.com/79509062/132017081-1acef878-294d-4911-a01e-6c65a3329538.png)

![image](https://user-images.githubusercontent.com/79509062/132017242-0cdd84e1-22de-48fe-a83e-818b42c39c77.png)

![image](https://user-images.githubusercontent.com/79509062/132016835-49aee453-1213-46f9-b450-fc62eca87598.png)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by yatinappsmith** [comment]
@vivekverma2312 please review this for release blocker

**Comment by ohansFavour** [comment]
Constructor classes or functions will not be removed from the hint as they can be used with the new keyword, like "new Function()". However, objects that represent 'interfaces' will be removed.
