### ISSUE TITLE
[Bug] Unable to fetch structure for postgresDB except for public schema

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#7120]
## Description

User on discord had public and testing schema in the DB, but getStructure method returned only public schema tables. 

After looking into the issue it came to light that `pg_catalog.pg_table_is_visible(a.attrelid)` clause in table query is causing the issue because it searches for table in search path and by default public schema is a part of search path but it's not the case with user created schemas. Have a look at **5.7.3. The Schema Search Path**
https://www.postgresql.org/docs/9.1/ddl-schemas.html

### Steps to reproduce the behaviour:

1. Create new PG DB and add test_table for public schema
2. Add sample schema to DB
2. Add sample_table to sample schema
3. Try to fetch the structure from Appsmith
4. Only public schema is fetched with test_table

**Comment by mrjk05** [comment]
Id like this to be solved as this is deal breaker at the moment.

**Comment by sumitsum** [comment]
Re-assigning it to @abhvsn based on our conversation today.
