### ISSUE TITLE
[BUG] Content under an organization opens up at different places in different cases

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#713]
Attachment: https://drive.google.com/drive/folders/19SrxJleDShntTGXaMW8OsTrGozsglprX?usp=sharing

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Create 2 organizations - 1 with short name and 1 with long name.

Issue: Though the positioning of down arrow is same, content (Organization Stettings, Share, members) is positioned at different places in both cases.

**Comment by blenderskool** [comment]
@Nikhil-Nandagopal Can I try working on this?

**Comment by satbir121** [comment]
@blenderskool Sorry this is a duplicate issue. Please take a look at other issues on[ this link](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22)

**Comment by satbir121** [comment]
#603 #735 Duplicate
