### ISSUE TITLE
[Bugs] Comments feedback

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#7131]
## Description
- [x] If I tag someone in my very first comment(even before the bot comments on it), then the other person doesn’t get tagged
- [x] If the name of the other person isn’t set, their email id appears and it’s really long. So the side bar looks weird because email ids are so long
- [x] ~The ‘1 reply’ button in the thread doesn’t look like a button, there’s no hover state for it.~
- [x] I’m able to draw a polygon(for multi-select) even while I’m in chat mode.
- [x] ~If I leave a comment inside a tab in the tab widget, clicking the comment doesn’t open the tab~ #4886 
- [x] ~I can’t leave comments on table filters, debugger, API pane, etc. (will this be worked on?)~
- [x] When I hover on a widget, the name card shows up

**Comment by rishabhsaxena** [comment]
- [ ] The way we load profile images is a bit off. The profile image refreshes every single time I open the comment box or the list of notifications. It’s a tiny detail that’s making the commenting feature look slow.

- [ ] After I hit enter on a comment, the comment box disappears and reappears in place again. It looks like a refresh of the comment box, and the comment pin.

**Comment by ramsaptami** [comment]
- [ ] Tagged comments are not real time. Even logging out and logging back in does not display new comment tags on notifications
