### ISSUE TITLE
[Bug] Resizing a widget breaks DnD in release environment.

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#7138]
## Description

Resizing any widget breaks DnD in release environment.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 this seems like a critical issue. Can you add steps?

**Comment by Nikhil-Nandagopal** [comment]
@yatinappsmith seems like a release blocker

**Comment by marks0351** [comment]
its a release-blocker yes @Nikhil-Nandagopal

**Comment by somangshu** [comment]
@marks0351 please update the description

**Comment by yatinappsmith** [comment]
@vivekverma2312 mark this as a release blocker

**Comment by somangshu** [comment]
@vivekverma2312 isn't this verified? Kindly update

**Comment by vivekverma2312** [comment]
@somangshu The fix is working fine on release. Can we cherry pick this to prod.

**Comment by somangshu** [comment]
I believe this was already present on release and should have gotten promoted. @marks0351 please confirm

**Comment by marks0351** [comment]
@somangshu this is in release branch of CE and EE but not in master branch should i cherry-pick?
