### ISSUE TITLE
[BUG] Too many errors when user tries to access an app which is deleted. And application ID and page ID are being shown.

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#714]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate:
1. Open https://app.appsmith.com/applications in 2 tabs.
2. Now in tab 1, launch the app while on tab 2, be on the homepage.
3. From tab 2, delete the app
4. From tab 1, click on 'edit'

Issue 1: Observe on the right side of the page, whole area is filled with error messages. 1 notification should be enough.
Issue 2 : application ID and page ID should only be printed in logs and nowhere on the UI. 

Attachment: https://drive.google.com/drive/folders/1QKb8B_3hQj0Va5tvmNZkO6OO6CShVgx7?usp=sharing

**Comment by trishaanand** [comment]
Preliminary thoughts : This is happening because all of these API calls are made in parallel from the client and all of these calls return an error that the asset that they are trying to fetch either doesn't exist or the user doesn't have permissions to access this.

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : Assigning this back to you to assign for front-end handling. In case of redirection to the 404 page, all the error toasts should be suppressed and not displayed to the user.
