### ISSUE TITLE
[Enhancement] Differentiate how errors and warnings are highlighted

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7142]
## Summary
Both warnings and errors are highlighted with a red underline which is not very helpful. Warnings usually are displayed different to an error on IDE's

![image](https://user-images.githubusercontent.com/79509062/132185191-e3ef14c1-cb5d-4670-9bcd-70bafd5f52b0.png)

**Comment by vnodecg** [comment]
Everything is changed to errors with the latest PR. This is in favour of hiding unwanted warnings
