### ISSUE TITLE
[Feature] Make user roles available for developers building appsmith applications

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#7148]
## Summary

Make user roles available for developers building applications

## Motivation

The user wishes to make certain fields visible only to users with `Administrator` & `Developer` roles and hide them from `Viewer` role users. This is currently not possible because the roles are stored at Organization level and hence not available in the user object.

**Comment by ggs331** [comment]
It will be really helpful if we can see the permission on user level. Currenntly my wordaround is store permission on database, then create a permission query and make it run on Pageload, then I will see the permissions.

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena @hiteshjoshi can we enable this? should be pretty easy

**Comment by riteshkew** [comment]
Closing this as this was part programmatic access control
