### ISSUE TITLE
[Feature] Show contextual search menu in the debugger

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#7149]
## Summary

https://www.figma.com/file/EdC0j0XwxyC9Flqzxyoxuf/Debugger?node-id=2677%3A3923

Show contextual(based on error type) search menu in the debugger

VALIDATION - Copy / Search Docs / Snippet/ Ask Intercom
PARSE - Copy / Search Google/Snippet
LINT - Copy / Search Google/Snippet
PLUGIN_EXECUTION
&nbsp;&nbsp;DATASOURCE_CONFIGURATION_ERROR - Copy / Search Google / Ask Intercom
&nbsp;&nbsp;PLUGIN_ERROR - Copy / Search Google / Ask Intercom
&nbsp;&nbsp;CONNECTIVITY_ERROR - Copy / Search Docs
&nbsp;&nbsp;ACTION_CONFIGURATION_ERROR - Copy / Search Docs / Ask Intercom

**Comment by ramsaptami** [comment]
Below scenarios currently display all 5 options of the contextual menu (CM) since the errors are not associated with the above mentioned 7 categories of CM. Please add these to the relevant categories so CM can be more appropriately filtered.

- [ ] Create a new API for Google sheets and click Run without entering any values. Response is 500
- [ ] Enter an incorrect sheet name on Google sheets query page. Response is 400
- [ ] Hit Run after entering only URL without resource/queryparam for API. Response is 404

**Comment by akash-codemonk** [comment]
> Below scenarios currently display all 5 options of the contextual menu (CM) since the errors are not associated with the above mentioned 7 categories of CM. Please add these to the relevant categories so CM can be more appropriately filtered.
> 
> * [ ]  Create a new API for Google sheets and click Run without entering any values. Response is 500
> * [ ]  Enter an incorrect sheet name on Google sheets query page. Response is 400
> * [ ]  Hit Run after entering only URL without resource/queryparam for API. Response is 404

@AnaghHegde Currently we are considering these errors on the frontend.

DATASOURCE_CONFIGURATION_ERROR - Copy / Search Google / Ask Intercom
PLUGIN_ERROR - Copy / Search Google / Ask Intercom
CONNECTIVITY_ERROR - Copy / Search Docs
ACTION_CONFIGURATION_ERROR - Copy / Search Docs / Ask Intercom

But for the cases mentioned above by saptami we seem to have some other type.

**Comment by AnaghHegde** [comment]
> Below scenarios currently display all 5 options of the contextual menu (CM) since the errors are not associated with the above mentioned 7 categories of CM. Please add these to the relevant categories so CM can be more appropriately filtered.
> 
> * [ ]  Create a new API for Google sheets and click Run without entering any values. Response is 500
> * [ ]  Enter an incorrect sheet name on Google sheets query page. Response is 400
> * [ ]  Hit Run after entering only URL without resource/queryparam for API. Response is 404

@akash-codemonk @ramsaptami 
1. This needs a change on backend and i will make this change
2. Incorrect urls are part of PLUGIN_ERROR i will check this
3. This does not fall into any of this. I think it was kept like by intentionally, i will check with Nikhil on this.

**Comment by ramsaptami** [comment]
@AnaghHegde @akash-codemonk I'll keep updating the original comment of mine for new scenarios that I come across, so please check for updates there

**Comment by bharath31** [comment]
Seems to be a stale issue. Closing this one out.

**Comment by rohan-arthur** [comment]
not planned - we will relook at the debugger in the near future as part of the IDE pod roadmap
