### ISSUE TITLE
[Bug] Label Text Overflow in Gen CRUD Form

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#7151]
## Description

Text overflows the row when the table's column name is more than 25 characters.

<img width="794" alt="Screenshot 2021-09-06 at 3 32 20 PM" src="https://user-images.githubusercontent.com/23132741/132199832-6162b2d6-07e5-4e17-920a-8f2da003db4a.png">

### Steps to reproduce the behavior:

Add steps to reproduce this behavior, including console/network logs & screenshots

1. Go to an application
2. Click on Add New Page
3. Select Datasource as Example DB 
4. Select Table as public.candidate_feedback
5. See the error in UI similar to the screenshot

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by ramsaptami** [comment]
Still present on release
![image](https://user-images.githubusercontent.com/79509062/132478983-860dc197-ed0d-41a1-a3ae-c1e0bd4349b6.png)

On DP, the table name is overflowing field length if the name is too long
![image](https://user-images.githubusercontent.com/79509062/132479550-20b6bd65-f68b-4ca1-9c72-1f397b9426de.png)
