### ISSUE TITLE
[Bug]The End tour link should not be displayed in the onboarding  for start building page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7152]
## Description

[What happened]The End tour link should not be displayed in the onboarding start building page

### Steps to reproduce the behaviour:

1. Go to the application page
2. click on Welcome tour 
3. The end tour link is displayed in the first instance

![image](https://user-images.githubusercontent.com/45958978/132201979-8950aade-a631-469e-980f-5d70913ba6a2.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [chrome]
- Environment [ release]

**Comment by akash-codemonk** [comment]
I think this is valid to have an end tour option at every step.
