### ISSUE TITLE
[Bug] Error on click action after applying filter in table widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7155]
Error: `Error occurred while evaluating trigger: TypeError: Cannot read property 'step' of undefined`

### Steps to reproduce the behaviour:

1. Drag and drop a table widget
2. Click action on the default data
3. Apply filter [steps + contains +2]
4. Now click on action
5. Observe the error is displayed

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f558d18c76e649d68d3c3099be69a45f-00001.gif)](https://www.loom.com/share/f558d18c76e649d68d3c3099be69a45f)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by yatinappsmith** [comment]
@vivekverma2312 please review as a release blocker

**Comment by vivekverma2312** [comment]
@ashit-rath I am able to repro the issue on release so re-opening the issue.
