### ISSUE TITLE
[BUG] 'Appsmith Editor isn't hidden for user with Read Access

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#716]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Attachment: https://drive.google.com/drive/folders/1DooGep7VcRtOYX5PWInZimDT4nxbuR4Y?usp=sharing

Steps to replicate:
1. From Organization A & Login A (Administrator Access), create an app A
2. From Organization A & Login B (App Viewer Access) --> Click on 'launch'
3.  Message comes
**This page seems to be blank
Please add widgets to this page in the _Appsmith Editor_**  -->  **Appsmith Editor** is clickable and while clicking on it, takes the user to 'Page not found'.

Expected Result: Login B with App Viewer Access shouldn't even be shown an option to click on **Appsmith Editor** in the 1st place.

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : This is a minor front-end bug. When the client fetches the application, the application contains the current user's permission. Only show the message to edit the application if the "userPermissions" array contains permission "manage:applications". In case only "read:applications" permission exists, we should either not display any message at all, or display another message which only states that the page is blank.

**Comment by trishaanand** [comment]
This also would be a good first issue.

**Comment by akshay11298** [comment]
Hi @trishaanand @Nikhil-Nandagopal, if this issue is still open I would like to work on it

**Comment by Nikhil-Nandagopal** [comment]
@akshay11298 go for it!

**Comment by akshay11298** [comment]
Hi @trishaanand @Nikhil-Nandagopal, I have opened pull request #1247 for this.
Screen recording for this is available at https://drive.google.com/file/d/14S8x9aSmPMxNhUPgLBQxDRdol54wrRIL/view?usp=sharing

**Comment by trishaanand** [comment]
@akshay11298 : Could you please resolve the merge conflict? We can take it forward post that. Thanks!

**Comment by akshay11298** [comment]
@trishaanand, I have resolved the merge conflict

**Comment by prapullac** [comment]
Issue is verified and working as expected
