### ISSUE TITLE
Typo on suggestions (tetx should be text) should show a warning

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7164]

**Comment by vnodecg** [comment]
Unfortunately this is not possible to do with jshint. Jshint doesn't check for definitions

**Comment by ramsaptami** [comment]
Didn't we discuss about including a second layer check on our end on this? Is that not possible?

**Comment by vnodecg** [comment]
@ramsaptami  We can't include a second layer to jshint (linter we are using).
