### ISSUE TITLE
[BUG] Share link window doesn't close

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#717]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate:
1. Open https://app.appsmith.com/applications 
2. Launch an application
3. Click on 'Share'  --> A window opens up
4. Click outside the window

Expected Result: Window should close.
Actual Result: Window doesn't close.

Another text issue on the same window:
Text appears as 'Get Shareable link for this for this application '.
Should be 'Get Shareable link for this application.'

Attachment : https://drive.google.com/drive/folders/1pjoFesBkVMuXk6LSAoumvAgaGtwE4McH?usp=sharing

**Comment by avats-dev** [comment]
@Nikhil-Nandagopal Also this one, can you help me out how this can be resolved? Thanks :tada:

**Comment by Nikhil-Nandagopal** [comment]
Hi @avats-dev 👋, thank you for your interest. Please go ahead and pick this up.  @satbir121 can you help Aditya with how to resolve this?

**Comment by satbir121** [comment]
@avats-dev 
The steps here are not complete. Please follow the following steps to reproduce it. Two accounts are needed to reproduce this issue. I am going to reference them as `account1` and `account2`
Steps:
1. Login using `account1`. Create an application `app1`. Invite `account2` as `AppViewer`
2. Login as `account2`and launch `app1`.
3. Click on 'Share' --> A modal popup opens up
4. Click outside the modal.

**Comment by satbir121** [comment]
Solution: Please add `canOutsideClickClose` in the `FormDialogComponent` in the following file.
[link to file](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx#L214)
