### ISSUE TITLE
[Bug] alignment issue in Home page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7175]
Steps to reproduce:
1) Navigate to the homepage
2) Search for non-existing App name

Observation:
The image is not in the center 

Expectation:
It is expected the image displayed should be in the center

![Screenshot 2021-09-06 at 9 13 28 PM](https://user-images.githubusercontent.com/71753653/132241141-96d27a0f-aea3-44e7-a07b-fece1eff11a0.png)

**Comment by Vishnurr2k01** [comment]
> Steps to reproduce:
> 
> 1. Navigate to the homepage
> 2. Search for non-existing App name
> 
> Observation: The image is not in the center
> 
> Expectation: It is expected the image displayed should be in the center
> 
> ![Screenshot 2021-09-06 at 9 13 28 PM](https://user-images.githubusercontent.com/71753653/132241141-96d27a0f-aea3-44e7-a07b-fece1eff11a0.png)

Hi,Can I work on this?

**Comment by ion05** [comment]
@somangshu @prapullac can i work on this as well ?

**Comment by somangshu** [comment]
Hey @ion05, I am not sure if this issue is not yet fixed as we have worked on a lot of things around this. @hiteshjoshi can you kindly confirm and assign this in case its still valid

**Comment by hiteshjoshi** [comment]
Hi @ion05 Sorry for the late revert. Missed this one. Yes, I think you should go ahead.

**Comment by Vishnurr2k01** [comment]
> Update : Apologies for my previous comment. Since @Vishnurr2k01 Asked for this at first. I will wait for sometime forVishnurr to revert.
> 
> > Hi @ion05 Sorry for the late revert. Missed this one. Yes, I think you should go ahead.

Thankyou

**Comment by sbalaji1192** [comment]
Hey @Vishnurr2k01 @ion05 , This issue appears to be fixed along with some of the changes that went in recently.
![Screenshot 2021-10-05 at 3 53 11 PM](https://user-images.githubusercontent.com/5328605/136005752-bb673e71-979b-441d-9b11-12949b69fb75.png)

You can find a different issue that is tagged with [Good First Issue](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22) label to work on.
