### ISSUE TITLE
[Bug] onError action gets called when there is an error in onSuccess action

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#7183]
### Steps to reproduce the behaviour:

1.  Add a button widget
2.  For onClick action execute a valid query.
3.  In onSuccess action add invalid js
4.  In onError action show a modal
5.  On click of the button the onClick query runs succesfully and then there is a notification saying there is an error and then the onError action gets called opening the modal.

This happens on release. 
In production the onError action is not executed when there is an error in the onSuccess action.

https://user-images.githubusercontent.com/67054171/132285027-c6ef2e31-ace7-49e1-9330-55046318b3b7.mov

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [release]

**Comment by Nikhil-Nandagopal** [comment]
Solved with #8988
