### ISSUE TITLE
[BUG] Binding a query directly to a table breaks all further bindings

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#719]
## Description
A user was trying to bind a table to a query without the .data and all their other bindings stopped working.
This occurred because the query has a run function which is injected into the evaluated value and this function caused jsonFn to fail while creating a safe object.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create a query Query1
2. Drag a table Table 1 
3. Bind the table data to {{ Query1 }}
4. Drag another table
5. Bind the default search of Table 2 to {{ Table1.pageNo }}
6. Refresh the page
7. The table stays in a permanently loading state

### Console Logs:
SyntaxError: Unexpected identifier
    at Object.<anonymous> (11.fb929fd1.chunk.js:2)
    at JSON.parse (<anonymous>)
    at Object.exports.parse (11.fb929fd1.chunk.js:2)
    at e.createSafeObject (eval at <anonymous> (eval at r (realms-shim.umd.min.js:1)), <anonymous>:3:35)
    at e.value (main.d20f1a73.chunk.js:1)
    at e.value (main.d20f1a73.chunk.js:1)

### Important Details
 - Version: [Cloud & Self-Hosted]
 - OS: [MacOSX]
 - Browser [Chrome]

**Comment by hetunandu** [comment]
Fixed via #722
