### ISSUE TITLE
[Bug] [Release] Getting error in connection establisher for List widgets

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7190]
Error: 'currentIndex' is defined but never used.

### Steps to reproduce the behaviour:
1. Drag and drop a list widget
2. Bind with the data
3. Observed all the widgets inside have error on connection establisher

<img width="938" alt="Screenshot 2021-09-07 at 1 33 31 PM" src="https://user-images.githubusercontent.com/83569920/132308890-24593bf7-6178-4bfa-be16-c90785ee6854.png">

**Comment by Tooluloope** [comment]
I'm unable to reproduce this issue now.
