### ISSUE TITLE
[Bug] The downloaded file format .html when image url passed in default image field and .Jpeg when the image url is passed in image field

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7191]
## Description
Release/Production - It is observed tat when the image url is passed in default field and when downloaded then the field format is .html and when the url is passed in image field and downloaded the field format is .JPEG

Expected Result:
The downloaded field format should be same when the url is passed via default or image field

### Steps to reproduce the behaviour:

1. Launch appmsith app in release or prod environment 
2. Drag and drop image widget 
3. Pass any image url in default field 
4. Enable the download option and click on download icon and observe the file format
5. Pass the same image url in image field 
6. Enable the download option and click on download icon and observe the file format

Video link:
https://loom.com/share/b6aa244d2d3e4231a65fffd5712472a8

### Important Details

- Version: [11.3]
- OS: [MacOS Big Sur]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
The download of image is applicable only on the image URL. The change required here is to not show the download option when the image URL is null
