### ISSUE TITLE
[Bug] Stat box inside stat box should not be allowed 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7194]
## Description
Release - User is able to place stat box inside stat box

Expected result:
Similar to list widget cannot be placed inside list widget the stat box should not be placed inside stat box

### Steps to reproduce the behaviour:

1. Launch Appmsith app in release environment 
2. Drag and drop stat box widget 
3. Copy the stat box widget and paste it and observe

videolink:
https://loom.com/share/2a2bd079cbd248ab86a123658e1ea10b

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [Chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
Not Placing certain widgets inside the list widget is a technical challenge and hence we dont do it, that is not the case here and hence we should allow any and every operation. We leave it one the developer to take this call. however if we see an error doing this, that will need addressing. 

Closing this
