### ISSUE TITLE
[BUG] App name isn't completely visible when it's long

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#720]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate :
1. From the homepage, create an app named 'gnerwihnireongionihgnerwihnireongionihgnerwihnireongionihgnerwihnireongionihgnerwihnireongionihgnerwihnireongionih1' under an organization

issue: App name with long names isn't completely visible

Attachment - https://drive.google.com/drive/folders/1Z4Xe_Up8As0p1lrmb6K7zpND6YaWN0TT?usp=sharing

**Comment by avats-dev** [comment]
@satbir121 @Saket2 How can this be resolved?

**Comment by satbir121** [comment]
Fixes needed:
1. By default the text only breaks into a new line if there is a space. This can be fixed using `word-break: break-all;`
2. There should max be three lines in the app name. Follow [this link](https://stackoverflow.com/questions/3922739/limit-text-length-to-n-lines-using-css) for details on how to implement that.
3. When the name is in ellipsis, the full name should show up in a tooltip. Use [this component ](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/ads/Tooltip.tsx)for tooltip

The file in question is [this](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Applications/ApplicationCard.tsx#L444).

Please use `styled` library to add styles.

**Comment by avats-dev** [comment]
Ok, getting on this, will let you know soon. Thanks @satbir121 for the help.

**Comment by Nikhil-Nandagopal** [comment]
@avats-dev I don't see a PR in the last 5 days so I'm unassigning you from this. Feel free to claim this once more when you have a chance

**Comment by avats-dev** [comment]
@satbir121 I'm thinking of using `line-clamp` for clamping upto 3 lines. What do you think? Also, I should add css here, https://github.com/appsmithorg/appsmith/blob/92d0fcac8253c4ea6f168ba3a612f4fdd2242c78/app/client/src/pages/Applications/ApplicationCard.tsx#L186-L189, right for the `AppNameWrapper`?

Also, I've never imported and used a component from scratch, so can you help a bit more in implementing `tootltip` or alternatively you can refer some examples for the same, and I can manage. Thanks.

> @Nikhil-Nandagopal I was a bit busy so I couldn't get a chance to focus here, I'm currently working on this one. Thanks.

**Comment by jsartisan** [comment]
@hetunandu I was working on this.

The 2nd and 3rd point by satbir is conflicting with each other. Because if we are doing the 2nd point with CSS, we won't able to tell if the ellipsis is shown or not and show a tooltip accordingly.

So, I am going with this way:
Limit the text up to a certain limit ( say 20 ), trim and add ellipsis if the text is greater than the limit, and show a tooltip.

Works?

**Comment by hetunandu** [comment]
@jsartisan That makes sense. You can trim with js instead to conditionally add the tooltip. How will you handle the lines in this case?

**Comment by jsartisan** [comment]
@hetunandu We can either add ellipsis based on the number of lines ( CSS ) or number of characters ( JS ). If we are going with the JS way, we will have to sacrifice number of lines case.

**Comment by jsartisan** [comment]
I just checked how many characters can come in 3 lines. It's 54. I can add a check on the 54 limit.

**Comment by hetunandu** [comment]
The 54 characters limit is arbitrary and can change based on client zoom, resolution or even future changes in code from our side. I would suggest we use css to add ellipsis and show the tooltip all the time on hover. @Nikhil-Nandagopal does this work out?

**Comment by jsartisan** [comment]
The JSFiddles solution looks good to me. Let me try that.

**Comment by jsartisan** [comment]
@hetunandu That solution is working fine. The only thing I had to change to is check for height instead of width.

**Comment by prapullac** [comment]
The name gets truncated like that of the homepage. Hence closing the issue
