### ISSUE TITLE
[Bug][Release] Extra space is coming at the bottom of the canvas

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7201]
Issue is observed with appsmith email id but not in my personal account id.

<img width="1918" alt="Screenshot 2021-09-07 at 4 29 50 PM" src="https://user-images.githubusercontent.com/83569920/132333925-24df1479-dce5-439a-ad79-331095faac19.png">

**Comment by marks0351** [comment]
@pranavkanade this is observed because of CanvasMultiPointerArena can u pls check it.
