### ISSUE TITLE
[Bug] Tooltip on icons in the icon selector dropdown moves away with the scrolling

### ISSUE THREAD

**Issue by kundansonu** [appsmithorg/appsmith#7208]
## Description

Tooltip on icons in icon selector dropdown moves away with the scrolling, please find attached the screenshot and screen recording.

### Steps to reproduce the behaviour:

1. Add an icon button
2. Click on the icon button 
3. Click on icon selector dropdown
4. Mouse over any of the icons until tooltip appears and then scroll down
5. the tooltip floats out of the icon selector dropdown to the top of the screen

### Important Details

- Version: Cloud
- Browser: chrome, safari
- Environment: production
<img width="1270" alt="tooltip-issue-icon-button" src="https://user-images.githubusercontent.com/5444055/132344835-b319e2db-d226-4e5b-94f1-c71cb4bd2e02.png">

https://user-images.githubusercontent.com/5444055/132344864-f09aaf00-eaee-4605-b916-3e8aff23d508.mov

**Comment by ipankajchaudhary** [comment]
I can fix this issue, assign it to me. please.

**Comment by Nikhil-Nandagopal** [comment]
Hi @ipankajchaudhary, it;s all yours go for it!

**Comment by Rishabhkaul** [comment]
Maybe its time to re-assign or close this? @Nikhil-Nandagopal

**Comment by somangshu** [comment]
Property pane is docked now, This solves the problem
