### ISSUE TITLE
[Bug] Comments mode tooltip does not collapse when tagging users

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7209]
## Description
Tooltip on comment mode does not collapse when tagging users when suggestions pops up above the comment box

### Steps to reproduce the behaviour:
1. Click on the bottom half of the canvas on comment mode and observe the tooltip `type Hello`
2. Use `@` to tag someone and observe the suggestions overlap with the tooltip

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/132345816-368794a4-09d0-4841-a790-ef6bfba64995.png)

**Comment by BhandarkarPawan** [comment]
I can work on this. Can it be assigned to me please?

**Comment by ramsaptami** [comment]
@BhandarkarPawan it's yours. 
Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by ramsaptami** [comment]
Attaching a similar tooltip issue from an unresolved thread

https://github.com/appsmithorg/appsmith/pull/7711#issuecomment-929176117

**Comment by mohanarpit** [comment]
Closing this issue as the feature has been deprecated.
