### ISSUE TITLE
[BUG] Duplicate key error while creating a new app

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#721]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate :

1. From the homepage, create an app named 'Saket' under organization A
2. create an app named 'Saket' under organization A {Repeat 1 basically}

Actual Result: Duplicate Key Error

Attachment: https://drive.google.com/drive/folders/1U3C3RhlgLaDU-SO5hpPSO4lOS0uxGF1s?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 2 apps cannot have the same name on appsmith
