### ISSUE TITLE
[Bug] Cursor shifts position when it inside of a thread

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7212]
## Description
Cursor moves to the start of the line after the first character is typed in a comment thread instead of keeping its continuous position.

### Steps to reproduce the behaviour:
1. Click on Comment mode and start typing a comment by dropping a pin on the canvas
2. Press Enter to enter comment thread and type in anything
3. Observe the cursor shift position after typing the first character where it appears before the first letter, 

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d8db410387d84492a60df39f5b9691c1-00001.gif)](https://www.loom.com/share/d8db410387d84492a60df39f5b9691c1)

**Comment by rishabhsaxena** [comment]
Hey @BhandarkarPawan sure, assigning it to you.
You may refer to the [contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md) for getting started.

**Comment by Rishabhkaul** [comment]
Maybe we can close this @Nikhil-Nandagopal
