### ISSUE TITLE
[Bug]-[1296]:Comment notification for deleted app/page displays resource not

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7213]
## Description
- [ ] When an **app has comments where users are tagged and this app is deleted** then tagged notifications still appears for tagger user. When tagged user clicks on this notification, they are redirected to a 'Resource not found' page with toast messages as seen in the video. 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e8e7f33e40314ef690b2eea1e8e4f593-00001.gif)](https://www.loom.com/share/e8e7f33e40314ef690b2eea1e8e4f593)

- [ ] When a **page with comments where users are tagged is deleted** then the comments remain on the comments pane and users can still access it but clicking on these comments throws an error
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/98dd8faca097482e842502bf0d4ac828-00001.gif)](https://www.loom.com/share/98dd8faca097482e842502bf0d4ac828)

- [ ] When a **home page has comments and a different page is set as home page**, then the comments get transferred to the new home page and users can access it without any errors or issues
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2b284992709e421f8b56e90ff23d51fe-00001.gif)](https://www.loom.com/share/2b284992709e421f8b56e90ff23d51fe)

Expected behaviour is for deleted app/page comments to be deleted from notifications of tagged users as well

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 162 |
| Effort (months)  | 0.25 |

**Comment by vuiets** [comment]
Closing as _Real-Time Commenting_ has been sunset as part of https://github.com/appsmithorg/appsmith/issues/14173.
