### ISSUE TITLE
[Enhancement] All button type widgets have the 'button' in them except Radio Widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7214]
## Summary
To keep with consistency in widget naming, Radio Widget should also have the word 'button' as is with other button type widget names. And it's an actual button.

## Additional Context
![image](https://user-images.githubusercontent.com/79509062/132376585-1f7e63bc-d50c-4a8a-9b4e-469a1c3aac3b.png)

**Comment by somangshu** [comment]
Radio is not a button, and we go ahead with doing something like this we will to rethink for checkbox / switch etc. Closing this for now, If in an internal meeting we call in favour of this, we will reopen it
