### ISSUE TITLE
[Bug] Long label name on input widget does not adjust to resize, only input box does

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7215]
## Description
When an input box with a long name is reduced in size, only the input box size reduces and any input is not visible whereas the widget label retains it's size.

### Steps to reproduce the behaviour:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/32513be9f0a94ab7ace6750d971d6d11-00001.gif)](https://www.loom.com/share/32513be9f0a94ab7ace6750d971d6d11)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by areyabhishek** [comment]
Related issue: https://github.com/appsmithorg/appsmith/issues/7064 
@momcilo-appsmith @somangshu Check out our competitor that we shall not name, they recently introduced a fix for a similar solution. I'm not sure if it's a good solution. It's a lot of options.

<img width="317" alt="Screen Shot 2021-09-07 at 9 52 39 PM" src="https://user-images.githubusercontent.com/30255708/132378803-fb7d222c-d7cd-47b9-bcf9-d613df342b48.png">

**Comment by somangshu** [comment]
Definitely a lot of option, Position and alignment should solve this i feel, Also to implement this we will need dynamic height and widget reflow

**Comment by ramsaptami** [comment]
Fair point @somangshu, that's a rare edge case to be handled by user more than us. Aside from that, our padding for the input box is such that reducing size only retains the padding width so any input is invisible when reduced to the smallest size.

**Comment by momcilo-appsmith** [comment]
@areyabhishek @somangshu  I'd say as well that this is a lot of options.
One more thing that I think we have to consider and I see that they do the same thing as we do: we have a lot of toggles.
Now this might not look like a problem, but they have less height than all the other inputs and therefore are very hard to find when scanning the property pane, I see they are doing the same mistake.
-
What to do instead? Toggle buttons with icons
-
When to use toggles:
* When the toggle is connected to an input
* If we intentionally want to make it harder to find it (not recommended)

**Comment by somangshu** [comment]
We are solving for this in #7064 

cc @wmdev0808 @dilippitchika

**Comment by wmdev0808** [comment]
This issue has been fixed in the PR for #7064 : https://github.com/appsmithorg/appsmith/pull/10600
