### ISSUE TITLE
[Bug] Tooltip should be "resolved thread" on resolved comments

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7221]
## Description
Tooltip currently says **Resolve thread** for comments that are marked **Resolved**. It should read **Resolved thread**

### Steps to reproduce the behaviour:
![image](https://user-images.githubusercontent.com/79509062/132451518-322adab6-4f16-49b2-87fa-893ffee89ee7.png)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by rishabhsaxena** [comment]
Closing this, since this is being tracked on #7153
