### ISSUE TITLE
[Bug]The application page is displayed for split second before landing on the canvas when the new user signs up

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7222]
## Description

[What happened]The application page is displayed for some time before landing on the canvas when the new user signup

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/509b40a502734f7aa2f1461b7af8b53b-00001.gif)](https://www.loom.com/share/509b40a502734f7aa2f1461b7af8b53b)

### Important Details

- Version: [Cloud 
- OS: [MacOS]
- Browser [chrome]
- Environment [ deploy preview]

**Comment by RakshaKShetty** [comment]
#4963

**Comment by sbalaji1192** [comment]
@RakshaKShetty Issue is not relevant anymore due to the fix we provided for - https://github.com/appsmithorg/appsmith/issues/7405. Hence closing

**Comment by RakshaKShetty** [comment]
as we are planning to fix this bug with #7405, we will be testing it along with that fix so removing the QA label
