### ISSUE TITLE
[Bug] Comment notification behavior on Alt key press

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7224]
## Description
Comment notifications loading button does not show loading symbol correctly when scrolled to the bottom and pressing **Alt** key when present at the end of the list makes the notification window behave very oddly.

### Steps to reproduce the behaviour:
1. Click on the bell icon on the home page and scroll to the bottom
2. Observe the loading icon not behave correctly - paused and often interrupted loading icon
3. Press **Alt** and observe the entire notification dropdown go wild
4. Refresh page and go to the end of the notifications and move cursor to the browser area (bookmarks, URL etc) and this behaviour repeats 

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2947b2595f4f43528b8841d1ab82f7fe-00001.gif)](https://www.loom.com/share/2947b2595f4f43528b8841d1ab82f7fe)

**Comment by hiteshjoshi** [comment]
Since we removed commenting. This is no more relevant.
