### ISSUE TITLE
[Bug] Mongo UQI : Issues on DP

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7229]
Below are the identified issues on UQI Mongo.
1) Insert and Delete fetch distinct: Additional field: Query 
2) Changing multiple data sources does not fetch data 
3) Empty Query on aggregate gives us a result that is not true when compared to release Mongo
4) Raw data is not functional: displays an error “Undefined”

**Comment by nidhi-nair** [comment]
@prapullac Could you please retest these on release to check if these are still valid?

**Comment by prapullac** [comment]
@nidhi-nair This is not valid on Release we can close the issue for now
