### ISSUE TITLE
[BUG] 'Unauthorized. Redirecting to login Page' Error notification while hitting https://app.appsmith.com/applications

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#723]
Attachment: https://drive.google.com/drive/folders/1huOOKfZmBm8DekYJUxDEc_K8x367snC2?usp=sharing

Browser Details: Chrome, Firefox, Safari
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Pre-requisite: Make sure that user is not already logged in.
Steps to replicate:
1. Hit https://app.appsmith.com/applications on any browser

Error: Unauthorized. Redirecting to login Page

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 this is expected, we redirect users who are not authenticatedto the login page

**Comment by tnelson-doghouse** [comment]
Agreed; my problem is that it gives this error message, but then doesn't do a redirect.
