### ISSUE TITLE
[Bug][Release] The  z-index of header in editor is wrong.

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#7230]
![18](https://user-images.githubusercontent.com/6636360/132464490-b0b02fac-c2e4-465b-84b0-0e03e678e3b3.gif)

Notice the screen selector icon in the gif.

**Comment by somangshu** [comment]
Does this anyhow belong to the platform?

@marks0351 can you please drop the appropriate solution here. Will pick this up later

**Comment by marks0351** [comment]
we already have a bug for this #7195
cc: @vivekverma2312

**Comment by marks0351** [comment]
closing this in favour of #7195
