### ISSUE TITLE
[Bug] Cursor shifts position while typing in Rich Text Editor Widget

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#7231]
## Description

https://user-images.githubusercontent.com/23132741/132465865-a22c1651-e32d-4156-92ea-578a858d0455.mov

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to https://app.appsmith.com/applications/6131b0ce987e5a1cc9ff72f3/pages/61326208987e5a1cc9ff74f0
2. Click on new Post
3. Try to type inside Rich Text Editor Widget
3. See error

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
@Rishabh-Rathod are you taking about RTE or the input widget, Also there is something specific is your app, I cant see to reproduce this on other apps, EX the standup app

**Comment by Rishabh-Rathod** [comment]
@somangshu this doesn't happen every time it is quite random. I saw it lastest in the above app created by @aswathkk 

Sorry for the confusion I saw the issue in RTE (Rich Text Editor Widget).

**Comment by somangshu** [comment]
@areyabhishek can you please drop your app here, we will debug this and take it forward
