### ISSUE TITLE
[Feature] Thread subscription settings

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#7235]
Notification settings should serve as a way for me to set what kind of notifications and emails do I want to receive when it comes to comments from the app I am currently in.

![image](https://user-images.githubusercontent.com/1944800/132479270-ae262243-8c6e-48c1-ba67-1c0b005f7971.png)

**Comment by pranavkanade** [comment]
@rishabhsaxena do we have designs for this?

**Comment by rishabhsaxena** [comment]
https://www.figma.com/file/XSVhOqRy1W8VS8Cd5nhor9/Collaboration-feature-Tue-20-April-2021?node-id=2%3A3024
@pranavkanade yeah they're here
