### ISSUE TITLE
[Feature] Allow Users to use shareable components e.g. Header and footer

### ISSUE THREAD

**Issue by kundansonu** [appsmithorg/appsmith#7237]
## Summary

Users should be able to mark some components like header, footer, sidebar, etc. as shareable to use it throughout all the pages of their application
## Motivation

Suppose user creates an application with three pages and he/she created header and footer in first of the page, then he/she should be able to make these components shareable and use it across all those three pages they created.

**Comment by Nikhil-Nandagopal** [comment]
@kundansonu thank you for the feature request. We have this feature tracked here #5229 so please do upvote it :)

**Comment by EmanuelFromFlorence** [comment]
Header and bottom bar is very much needed.Here is my vote for that.
