### ISSUE TITLE
[Bug] Need space between import box and button on modal

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7242]
## Description
Need some spacing between the Import button and text upload box during app import.

### Steps to reproduce the behaviour:
1. Go to import app from home page and observe the spacing as seen in the screenshot

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/132484148-84c38a60-135c-40b3-b129-b58ee0841c03.png)

**Comment by pranavkanade** [comment]
This has been fixed with https://github.com/appsmithorg/appsmith/pull/7562
