### ISSUE TITLE
[Enhancement] UX : JS Editor : representation of JS for "on Click" can be improved

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7243]
Steps to reproduce:
1) Add a JS object 
2) Add a Button Widget
3) Click on the property pane
4) navigate to On click option 
5) Select execute JS option 
and observe

Observation:
It is observed that the dropdown can be improved 

Expectation:
It is expected that the icon can be added for a  better look and feel of the dropdown 
![Screenshot 2021-09-08 at 3 04 27 PM](https://user-images.githubusercontent.com/71753653/132488133-cf7a8f7f-0287-47b8-a20f-e324ee7f5be2.png)

**Comment by rohan-arthur** [comment]
Hi Prapulla, now there is an icon shown next to the JS Object name:
![Screenshot 2022-04-22 at 10.42.38.png](https://images.zenhubusercontent.com/6196337f2def7ccca841bb55/1a30845f-cae0-48d2-beca-9fa5ad3b4171)
