### ISSUE TITLE
[BUG] Query Deletion isn't removing the query from associated widget action.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#725]
## Description
Query Deletion neither removes the query from associated widget action nor shows an error message on triggering widget action.

### Steps to reproduce the behaviour:
1. Create a simple action.
2. Trigger it on dropdown selection change, show success/error message on query completion.
3. Remove query.
4. The query is still present in the associated widget action and no error msg is shown on execution of the query.

The video is bit long as the Page selection became unresponsive in between.

[Video in action](https://drive.google.com/file/d/1CxPcqrtMIcfsO4njJQ3RbCfqZe6zVk91/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay we don't delete bindings on deleting a query / widget. Can you raise a separate bug for no error message when incorrect js execution because this seems to be related to that
