### ISSUE TITLE
[Feature] Date Range Picker Widget

### ISSUE THREAD

**Issue by kundansonu** [appsmithorg/appsmith#7252]
## Summary

Date Range Picker widget should be available to shows two month calendars in sequence and lets the user select to select a range of  dates
## Motivation

For some use cases, user might need a widget to select a range of dates, so either a new widget for date range selector or adding functionality to the existing date picker to support range selection.

## Additional Context

<img width="498" alt="Screenshot 2021-09-08 at 5 28 48 PM" src="https://user-images.githubusercontent.com/5444055/132505793-5ba93e82-1833-4f36-8a6a-2c7c08340e96.png">

**Comment by Nikhil-Nandagopal** [comment]
Hi @kundansonu ! Thanks for the feature request. We already have this one captured here #3345 so I'm closing this
