### ISSUE TITLE
[BUG] Unable to execute query on postgres Mock DB table.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#726]
## Description
DB throws error for querying database with `camelCase` naming. From error, it could be inferred that the query converted the table name `camelCase` internally to `camelcase` which is an invalid table.

<a href="https://ibb.co/fXzJvgN"><img src="https://i.ibb.co/0nR5t79/covid-Cases-Issue.png" alt="covid-Cases-Issue" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by visibleajay** [comment]
Similar issue occurred with update query on columnName.

<a href="https://ibb.co/W3TNZYB"><img src="https://i.ibb.co/hMqxbt2/Update-Column-Query.png" alt="Update-Column-Query" border="0"></a>

**Comment by Saket2** [comment]
> Similar issue occurred with update query on columnName.
> 
> [![Update-Column-Query](https://camo.githubusercontent.com/ff1742b442cf11b790fcffb94ceb8cfc9d6fbff4/68747470733a2f2f692e6962622e636f2f684d71786274322f5570646174652d436f6c756d6e2d51756572792e706e67)](https://ibb.co/W3TNZYB)

Explanation here: https://github.com/appsmithorg/appsmith/issues/640#issuecomment-696078648

**Comment by visibleajay** [comment]
This worked with single quote around columnName and tableName.
