### ISSUE TITLE
[Feature] Resizing widget downward is very janky

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7262]
## Summary

This majorly is an issue when the widget is placed at the bottom of the canvas, The resize handle does not autoscroll to increase the size of the widget. The interaction need to be smooth here

**Comment by somangshu** [comment]
@marks0351 we need to understand why is this happening (severity), Can someone else in the team take this up once you have triaged the issue

**Comment by marks0351** [comment]
This is the scroll behaviour even before new DnD. its not a bug but we need to enhance the scrolling behaviour algo on resize.
