### ISSUE TITLE
[Feature] Custom Widget (HTML + JS + binding to data)

### ISSUE THREAD

**Issue by President** [appsmithorg/appsmith#7266]
## Summary

Currently AppSmith is missing some useful widgets (e.g .Calendar, Audio Recorder, etc) and it is not possible to implement in advance all needed widgets - new projects will require new widgets.

The idea is to let developers that are using AppSmith to create and use their own widgets.
Widget should allow to contain any HTML code (including headers, styles) and any JS. 
Ideally if HTML and JS files could be uploaded and re-used but it could be next step. Even of developer just need to insert into one CustomWidget on the page huge pre-created HTML+embedded JS with complex logic (and of course with bindings to the data via "{{ ... }}"), this would allow us to use AppSmith in more complex scenarios.

For example just put all the code from https://github.com/bryanjenningz/record-audio/blob/master/record-server-example/public/index.html would allow us to make audio recorder ourselves.

## Motivation

Decrease dependency on already existing widgets. Allow to use AppSmith in more complex scenarios.

**Comment by areyabhishek** [comment]
Hi! Thanks for opening this. Allowing custom widgets is on our roadmap you'll see this in the next quarter. Calendar widget will also be picked up soon.

Our audio recorder widget is on its way. Could you check out this issue and the linked PR? https://github.com/appsmithorg/appsmith/issues/3912 this should go live next week after we test this internally 

There's a deploy preview link in the PR too for you try it out

**Comment by Nikhil-Nandagopal** [comment]
Hi @President 👋 Thank you for the feature request.
We already have this issue tracked here #2033 so I'm closing this in favor of that.
