### ISSUE TITLE
[Enhancement] Add hover styles to icon button similar to the normal button

### ISSUE THREAD

**Issue by kundansonu** [appsmithorg/appsmith#7274]
## Summary

Icon button should also have the same hover colour like normal button

## Motivation

To maintain consistency between all the buttons the icon button should also have the same hover styles. currently on hover icon button does not change its background color
 
## Screenshot

<img width="154" alt="Screenshot 2021-09-09 at 10 17 18 AM" src="https://user-images.githubusercontent.com/5444055/132624458-7d79d368-1871-4067-9d03-ffe9c84125f0.png">

**Comment by somangshu** [comment]
This is a non-issue, The functionality if to add the hover state only when you have an onClick action so that this widget can be used as an Icon, we have extended this functionality while building the first composite widget i.e. stat box widget. Closing this for now
