### ISSUE TITLE
[Bug] Evaluated property pane overlaps with help page when clicked from Debug dropdown

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7278]
## Description
When **Debug** is clicked from the **Evaluated Value** part of the property pane, then clicking "Trigger Snippet" option opens help page behind it overlapping the 2 pop-ups

### Steps to reproduce the behaviour:
1. Go to a widget and type in a code to show an error
2. Now go to the Debug dropdown on the evaludated part of the PP
3. Click on Trigger Snippet and observe the overlap

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/132628199-27e6dae8-56db-44a6-be0d-c2b610e78454.png)

**Comment by kocharrahul7** [comment]
@ramsaptami I am no longer able to replicate this error, can you please confirm if you are
