### ISSUE TITLE
[Bug] Widget name of Widgets in small container is not visibile properly.

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#7279]
## Description

[What happened]

### Steps to reproduce the behaviour:

<img width="400" alt="bug" src="https://user-images.githubusercontent.com/35134347/132630818-cfa39847-e882-47f7-aa27-7673b50c69c0.png">

widgets in small container will have cropped out widget names which makes it very difficult to open property pane.

I have previously tried fixing this which is very difficult to fix and cater to all use cases.

We can either fix this or should bring in docked property pane asap.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
@marks0351 how will the docked property pane solve this? Will be allow the prop pane to open on the button click again?

**Comment by marks0351** [comment]
@somangshu i believe we are going to allow it back. if not we definitely have to fix this.

**Comment by somangshu** [comment]
Added this to the property pane docking EPIC so that we dont lose track on this

**Comment by somangshu** [comment]
@yaldram can you start triaging this, We need to find the right solution for this, This is a very annoying bug
