### ISSUE TITLE
[BUG] Inconsistent behavior (Dropdown widget) 

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#728]
Attachment: https://drive.google.com/drive/folders/1uABc1FdBUbh9GOGX2DS1QsSPWeDLN3oD?usp=sharing

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, click on 'Create New' in order to create a new application
3. Edit Application
4. From the Form Widgets, pick Dropdown widget

Issue 1: If there are multiple values are selected, only 'Vegan' is visible in the box.
Issue 2: If 'Vegan' is removed, none of the other selected values appear in the box.

**Comment by hetunandu** [comment]
Closing in the favour of #772 as solution would be the same i.e fixing how selected options are showing in a constrained multi select. Adding these cases in the other issue as well.
