### ISSUE TITLE
[Bug] SyntaxError: Unexpected token ';' error on currentItem. on list widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7282]
## Description: I am not getting auto suggestion and also when I type `{{currentItem.}} ` I am getting error.

<img width="701" alt="Screenshot 2021-09-09 at 12 02 17 PM" src="https://user-images.githubusercontent.com/83569920/132635918-d6b933d6-edb5-494b-a057-066c2cb947b4.png">

**Comment by jsartisan** [comment]
@hetunandu 

Binding for children for this issue becomes like this:

```{{List1.listData.map((currentItem, currentIndex) => { return (function(){ return currentItem.; })(); })}}"```

so the error seems valid. should we consider this a valid issue?

**Comment by jsartisan** [comment]
@vivekverma2312 I just checked the autocomplete. seems to be working for me. any steps to reproduce?
