### ISSUE TITLE
[Bug] Debug dropdown on property pane options does not function as intended

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7284]
## Description
Clicking on **Documentation** and **Trigger snippets** sequentially open and close quick help modal instead of navigating to new parts of the modal

### Steps to reproduce the behaviour:
1. Click on Debug present on the evaluated pop-up of a property pane
2. Click on Documentation and observe quick help modal open
3. Now click on Trigger snippets and observe quick help modal close

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/74488014f6d74f5d9a52c94df26ef3ed-00001.gif)](https://www.loom.com/share/74488014f6d74f5d9a52c94df26ef3ed)

**Comment by somangshu** [comment]
@ramsaptami please assigning this to the person who has worked on the debug button on the property pane evaluated value popup. This should be related to the JS snippet development

**Comment by kocharrahul7** [comment]
No longer replicable
