### ISSUE TITLE
[Bug] User history must be restricted to current logged in session only

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7288]
## Description
Page history is not restricted to current logged in user session. A different user logged into the same browser session can use the back button to retrace previous users apps/pages if they are present on the organization. 

### Steps to reproduce the behaviour:
1. Perform various actions on the canvas of different apps so there's enough browser history present to recreate this
2. Share org to a user you're going to be signing in in the next step
3. Log out and now sign in using second user
4. Press back button on the browser and observe you can retrace the previous user's history

PS: recording is on release but reproducible on prod too

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/caaff8d4dd464e359f386a78d61e40a3-00001.gif)](https://www.loom.com/share/caaff8d4dd464e359f386a78d61e40a3)

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami I don't think this is an issue. The browser navigation should be independent of the login or even the site visited.
