### ISSUE TITLE
[BUG] When email ID is long, 'invite' button starts peeking out of the window

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#729]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. click on share and enter long email address

Expected Result: 'Invite button' should stay firm.
Actual Result: 'invite' button starts peeking out of the window

<img width="1791" alt="Screen Shot 2020-09-25 at 1 22 52 AM" src="https://user-images.githubusercontent.com/49346036/94193442-fcb9b080-fecd-11ea-9cf4-eb7adab3f8f1.png">

**Comment by instareasy** [comment]
interested in this issue

**Comment by mohanarpit** [comment]
@instareasy Welcome to the Appsmith community! 😄 

I've assigned this issue to you. Please take a look at our [Contribution](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) guide as you begin.

**Comment by ishaanmehta4** [comment]
I can fix this bug.
Please assign this issue to me.
![example](https://user-images.githubusercontent.com/61118240/95012803-0fb04b80-0659-11eb-9c9f-568b1507073f.jpg)

**Comment by Nikhil-Nandagopal** [comment]
@ishaanmehta4 it's yours!

**Comment by Nikhil-Nandagopal** [comment]
@instareasy I'm unassigning you since you haven't raised a pr in the last 4 days. Please feel free to pick up another one of our many good first issues

**Comment by ishaanmehta4** [comment]
@Nikhil-Nandagopal the PR will be in place by tommorow night.

**Comment by ishaanmehta4** [comment]
@Nikhil-Nandagopal the PR will be in place by tommorow night.

**Comment by ishaanmehta4** [comment]
I have already made a PR #925 to fix this issue with minimal changes in styling.
Please guide me to make changes that are required to get the branch merged (or atleast accepted for the hacktoberfest event).
Thank you

**Comment by Saket2** [comment]
@Nikhil-Nandagopal  UI improvement v/s bug - Shouldn't this be counted as a bug rather than UI improvement as there is this UI breaking in a specific case?
