### ISSUE TITLE
[Bug] [Release] Chart is not coming on Custom cart widget by default

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7292]
### Steps to reproduce the behaviour:

1. Drag and drop a chart widget
2. Change the chart type to custom chart
3. Observe that the chart is not coming

<img width="799" alt="Screenshot 2021-09-09 at 1 34 51 PM" src="https://user-images.githubusercontent.com/83569920/132648004-4f5f80fd-c4e3-4d2a-8db4-b5576b0f08f5.png">

**Comment by somangshu** [comment]
Closing this as not reproducible
