### ISSUE TITLE
[Bug] - [46]: Inconsistent cursor behaviour in comment mode

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#7293]
We have an inconsistency in how the cursor interacts with widgets. Some widgets still work, while most don’t.In the comment mode, I can still interact with the table columns, tabs, but not with other widgets with actions. I think disabling interaction everywhere does make sense but I was hoping we could let users leave comments on the dropdown list for example.

**Comment by vuiets** [comment]
#
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 23 |
| Effort (months)  | 1 |
