### ISSUE TITLE
[Bug] A user can be selected with the same role to an organization

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7296]
## Description

- [ ] When a user is already present in an organization then their current role must be disabled from selection. Currently, we can select the same role and click on Invite and receive a successful message (no additional row is added though)
### Steps to reproduce the behaviour:
1. Go to **Members** under the **Organization** dropdown
2. Click on **Invite users**
3. Add a user for any role and click **Invite** 
4. Repeat step 3 and observe the success message

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9355211f347847309e08d2858aae20f4-00001.gif)](https://www.loom.com/share/9355211f347847309e08d2858aae20f4)

- [ ] Select a different role for the same user and observe the successful message but no change in either role or additional row being added (as was the case before)
### Steps to reproduce the behaviour:
1. Repeat invite but this time choose a different role and observe that additional role is not created

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/670294db7006448a8666437b841750ae-00001.gif)](https://www.loom.com/share/670294db7006448a8666437b841750ae)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release and Prod

**Comment by jasenaquadras** [comment]
I would like to work on this issue.

**Comment by ramsaptami** [comment]
It's yours @jasenaquadras 

Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by shwetha-ramesh** [comment]
@ramsaptami Here is more to the same issue.

https://www.loom.com/share/9355211f347847309e08d2858aae20f4

**Comment by parag477** [comment]
I would like to contribute to this issue.

**Comment by ramsaptami** [comment]
Please go ahead and pick it up @parag477. Let us know if you need any assistance. Good luck!

**Comment by royalpinto007** [comment]
Hello, can you please assign this issue to me?

**Comment by ramsaptami** [comment]
Sure, please go ahead and pick it up!

**Comment by ramsaptami** [comment]
Sure! Please go ahead and pick it up @royalpinto007 !

**Comment by yenniejunvu** [comment]
Does this still need work? I would like to take a look!

**Comment by ramsaptami** [comment]
This issue has been fixed as part of RBAC changes and now throws a validation error hence closing it.
