### ISSUE TITLE
[Enhancement] Add organization search with more options for the user

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7297]
## Summary
Searching for an organization currently only shows the option to create a new app, not options to navigate to the org or show apps under the org. Adding these features would be helpful to the user.

## Additional Context
![image](https://user-images.githubusercontent.com/79509062/132662210-ab77b5fc-4cc8-410d-b089-5bd8f61f4012.png)

**Comment by Nikhil-Nandagopal** [comment]
This should be fixed with the new home page @hiteshjoshi ?

**Comment by Nikhil-Nandagopal** [comment]
We don't need an option to navigate to the org since orgs are upfront filtered. The search works to show the apps under the orgs
