### ISSUE TITLE
[Bug] User display picture does not update after upload

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7299]
## Description
1. Display picture is not updated when user uploads from the file picker (jpg and jpeg work fine)

### Steps to reproduce the behaviour:
1. Go to profile and click **Upload Display Picture**
2. Select an image and upload
3. Observe a shift on the view
4. Refresh page and observe a momentary 'Remove' appear under the profile pic

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/fcd0703f36cc4a3382067067af94e056-00001.gif)](https://www.loom.com/share/fcd0703f36cc4a3382067067af94e056)

### When the Display picture is uploaded successfully, It doesn't reflect in AppHeader. 

(click on the below image to check video)
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/413f9aa61b6545d7918dd2c00e01dc36-00001.gif)](https://www.loom.com/share/413f9aa61b6545d7918dd2c00e01dc36)

**Comment by pranavkanade** [comment]
@ramsaptami could not reproduce this on release, checked both on mac and win10.
https://user-images.githubusercontent.com/13262095/133734404-267350d2-4cf6-4b41-a23e-2ebadeb4d87d.mov

**Comment by pranavkanade** [comment]
could you please verify this again? If you still see the issue, please let me know the format and size of the image

**Comment by ramsaptami** [comment]
it's a PNG of size 2475KB that's not working

**Comment by ashish921998** [comment]
@Pranay105 @ramsaptami I would love to work on this

**Comment by Nikhil-Nandagopal** [comment]
@ashish921998 go for it!

**Comment by ashish921998** [comment]
@Nikhil-Nandagopal @ramsaptami this is not reproduceable, can you please ask someone to link a video on how to reproduce this

**Comment by ramsaptami** [comment]
Hey @ashish921998, so this is a specific edge case where a PNG file of size that's close to the size limit fails.

Other image file types can be successfully uploaded.

**Comment by ankitakinger** [comment]
Fixed already
