### ISSUE TITLE
[BUG] Input widget with type number is allowing default val as `text`.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#730]
## Description
Input Widget with type `number` is allowing default val as `text`.

<a href="https://ibb.co/4mGMSyy"><img src="https://i.ibb.co/znYb2cc/Default-Val-Text-For-Number.png" alt="Default-Val-Text-For-Number" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay this is an interesting issue. I would however say that the type is only to restrict users from entering a value into the input. It is not to restrict data set by the system / editor. Hence closing this

**Comment by visibleajay** [comment]
@Nikhil-Nandagopal Thank You for the clarification. Is editor allowed to pass any invalid value to the widget which is visible in the deployed app?
