### ISSUE TITLE
[Bug]Duplicate query name should be allowed across pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7301]
## Description
All actions (Queries & APIs) should have unique names within a page but can be repeated across different pages in the same application.

Queries and APIs can either be renamed in two ways:
One , from the edit window, where you would click on the current name of the query/API to rename it.
And two, from the entity explorer (the left hand side navigation pane), by clicking on the menu options for that query/API (see video). 

The refactor in the edit window functions correctly for repeated names across pages, but the edit option on the entity explorer errors out for the same value.

The expected behaviour is that the validation for the name refactor from the entity explorer also passes for such scenarios.

### Steps to reproduce the behaviour:

1. Create a new application with page Page1.
2. Create an API in Page1, call it `testAPI`.
3. Create a new page in the same application called Page2.
4. Create another API, this time in Page2.
5. Try to rename this new API to `testAPI` from the entity explorer.
6. See validation error.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4ee46313707046ab944fe420805618b6-00001.gif)](https://www.loom.com/share/4ee46313707046ab944fe420805618b6)

### Important Details

- Version: [Cloud ]
- Browser [chrome]
- Environment [ release]

## Contribution

**Guidelines**
Please read the [Code Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md) to understand the process to get started with solving a Github issue.

**How to fix**
- Currently the logic to find conflict in action names looks for all the action names across all the pages in an application.
- Instead of looking for action names across all the pages, only look for action names within the page. 

**Relevant files and methods**
- [ActionNameEditor.tsx](https://github.com/appsmithorg/appsmith/blob/09eea59330df96c2acbbefa1fcc401ff8026ee12/app/client/src/components/editorComponents/ActionNameEditor.tsx)
  - Please take a look at the `hasActionNameConflict` method for the **correct** implementation. 
- [Name.tsx](https://github.com/appsmithorg/appsmith/blob/b49f5097c6e02ff42ae493416a1a9f141d9ed5eb/app/client/src/pages/Editor/Explorer/Entity/Name.tsx)
  - Please modify the method `hasNameConflict`method. Existing selector (`getExistingActionNames`) used in the file `Name.tsx` is fetching all the action names from all the pages. The selector needs to be changed to only fetch action names from the current page like the `actions` selector in `ActionNameEditor.tsx`.
  - You may refer to this older PR for help: https://github.com/appsmithorg/appsmith/pull/1781 

**Test Cases**
Please write test cases that test the following scenarios:
- Conflicting action name on the same page should give error.
- Same action name on different pages should **not** give any error.
- Please add the test cases in [this](https://github.com/appsmithorg/appsmith/blob/71f4a4b0a979f01dd710c02edeae25c09ace6595/app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Entity_Naming_conflict_spec.js) file.
- You may refer to this older PR for help: https://github.com/appsmithorg/appsmith/pull/1781

**Comment by Rutam21** [comment]
@somangshu I would love to work on this issue as well. Feel free to assign this to me.

**Comment by somangshu** [comment]
@ajinkyakulkarni kindly do the needful ☝️
