### ISSUE TITLE
[Bug]The error message is displayed when user clicks on test button inside the mongo datasource edit page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7302]
## Description

[What happened]Inside the Mock datasource edit page when the user clicks on the test button the error message is displayed

### Steps to reproduce the behaviour:

1.add a mock data source
2.click on the edit icon
3.inside the edit page
4.click on test button

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ccb9d1bacb714b0f98a42516c25aaade-00001.gif)](https://www.loom.com/share/ccb9d1bacb714b0f98a42516c25aaade)

### Important Details

- Version: [Cloud ]
- OS: [e.g.MacOS]
- Browser [echrome]
- Environment elease,

**Comment by arunvjn** [comment]
@RakshaKShetty Can you please describe the expected behavior here ?

**Comment by nidhi-nair** [comment]
Closing as this issue is not reproducible anymore
