### ISSUE TITLE
[Bug] Display pic does not reflect on the header section of the Appsmith homepage

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7305]
## Description
Changed display picture appears on organization but not on the header section of the app

### Steps to reproduce the behaviour:
1. Go to profile and change display picture
2. Go back to home page and observe the DP on organization updated but not on the header

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/132669554-ae187091-37a5-4cbb-994a-4f13957e23b7.png)

**Comment by caspero-62** [comment]
Can I be assigned this please?

**Comment by hiteshjoshi** [comment]
Hi @caspero-62 this is already fixed with the latest updates. 
Can you please look into the tag "Good first issue" and figure out some other issues to work on.

**Comment by nayan-rafiq** [comment]
Thank you @caspero-62 for your interest. Please wait a while, I'm waiting for the work done so far to be merged first. 
In the meantime, you can fork the branch: `fix/update-profile-image-after-upload` and start working on that. 

### Here is a summary of what needs to be done for this issue: 
User has a `photoId` in their state if they've uploaded any photo. The state is stored in `ui.users.currentUser.photoId`. This variable is used to show the profile photo on the right top corner of the navigation bar. 

#### Remove photo
If user goes to edit profile and removes the photo, we need to remove the `photoId` from the `ui.users.currentUser` state also. It should update the profile photo as well on the right top corner.

#### Update photo
If user uploads a new photo, the photoId is returned in the upload API response. On success, we need to set this in `ui.users.currentUser.photoId`.

**Comment by caspero-62** [comment]
Okay I'll do that right away

**Comment by nayan-rafiq** [comment]
@caspero-62 Sorry for being late to reply. You don't need the `fix/update-profile-image-after-upload` branch anymore. You can start working by forking the `release` branch. For more clarification, please check the contribution guides https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md

**Comment by caspero-62** [comment]
Okay then...copy that
