### ISSUE TITLE
[Bug] Binding an object type data to a checkbox is crashing the app

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7306]
## Description
Bind an object type data to a checkbox and observe the app crash

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ed8a9a26d3184d5aba92389f80106f1b-00001.gif)](https://www.loom.com/share/ed8a9a26d3184d5aba92389f80106f1b)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by marks0351** [comment]
@ramsaptami this seems to happen coz of some other reason. I tried with Gsheets and api that returned obj, no crash in release env.
