### ISSUE TITLE
[BUG] onPageChange is not triggering for client side pagination

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#731]
## Description
Alert isn't triggering for tableWidget on `onPageChange` action

[Video In Action](https://drive.google.com/file/d/1DU7e1FwxU56sVuKTCvP1cZV_5Cy-CszT/view?usp=sharing).

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay I've updated this issue description. Thanks for the find!

**Comment by satbir121** [comment]
There is two type of pagination for table widget: Client side and Server side. The pagination is client-side by default. In client side pagination, onPageChange is not getting triggered but it gets triggered for server side pagination.

**Comment by satbir121** [comment]
This might not be a good first issue because the Paginator implementation might need some refactor.

**Comment by prapullac** [comment]
The on page action does not trigger on client side 
Please refer the video for the same 
https://www.loom.com/share/f7669fdf5854483e887fa3e335a2540b

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon please fix this

**Comment by riodeuno** [comment]
@prapullac @Nikhil-Nandagopal This is not reproducible. Please verify.

**Comment by prapullac** [comment]
@riodeuno It is working now as per expectation. Hence we can close the issue
