### ISSUE TITLE
[Enhancement] Input widget: password type icon should change to web standards

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7317]
## Description

The input widget with type password show an icon which is not a standard we should replace this with eye-open in password hidden state & eye-off in password show state (blueprint icons)

![Screenshot 2021-09-09 at 8 16 55 PM](https://user-images.githubusercontent.com/11089579/132708613-8e600744-e126-4f49-a997-01e2c52004b7.png)

## Figma link
https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=428%3A3422

**Comment by SandipPalit** [comment]
I would love to work on this issue, since I already have experience in this domain. Please assign it to me.

**Comment by aditirao7** [comment]
If this isn't already assigned, I would love to work on it.

**Comment by mandvisingh** [comment]
Can i work on this issue?

**Comment by EkaterinaMozheiko** [comment]
I'd like to work on this issue

**Comment by sakshamgurbhele** [comment]
@somangshu I am Interested in working on this, let me know if I can Go ahead.

**Comment by somangshu** [comment]
Greetings @SandipPalit, thanks for showing interest 🎉 , This is all your. Assigning this to you now. Sorry for the delay here, We missed you comment.

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

@mandvisingh @EkaterinaMozheiko @sakshamgurbhele I have to give priority to the person who claimed this first, Please look into other `hacktoberfest` issue, If you find something interesting, please feel free to tag me directly, I shall assign it to you 🙂

**Comment by somangshu** [comment]
@vibhandikyash lets implement this as part of the Input widget design audit
