### ISSUE TITLE
[Feature] Resize the property editor pane

### ISSUE THREAD

**Issue by daemons2000** [appsmithorg/appsmith#7319]
We need this because anything a bit more serious than a Javascript one liner gets wrapped wrapped wrapped so it becomes a mess to edit. Alternatively, a popup JS editor for each field would be nice too.

**Comment by Nikhil-Nandagopal** [comment]
@daemons2000 thank you for the feature request. We have a full fledged JS Editor right now being tested. You can track the issue here #1751

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #4435
