### ISSUE TITLE
[Feature] Spellcheck and autocomplete properties for the input widget

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#7328]
## Summary

HTML's API allows for some neat features which can be enabled or disabled in the input widget.

-  [ ] Spellcheck

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

These should be disabled by default.

De-scoped: 
-  [ ] Autocomplete - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by aliya-rahmani** [comment]
I want to work on this issue.

**Comment by riodeuno** [comment]
@aliya-rahmani Thanks for offering to help out with this issue. It is all yours! Assigning it to you.

Notes on development, specific to the Appsmith platform:
 - The property pane configurations should be changed [here](https://github.com/appsmithorg/appsmith/blob/7665ff3c4f3873fc325d7e4c9002ae3b0594abb1/app/client/src/widgets/InputWidget/widget/index.tsx#L138)
 - We need to add two entries, which would be hidden unless the type is TEXT, as these properties only make sense for the text type. What do you think?
 - By default, these properties would be `false`, this needs to be added in this object [here](https://github.com/appsmithorg/appsmith/blob/7665ff3c4f3873fc325d7e4c9002ae3b0594abb1/app/client/src/widgets/InputWidget/index.ts#L18)

**Comment by somangshu** [comment]
@wmdev0808 that means this can still function inside a form which has a submit button, Similar to the required property in the input widget. 

@riodeuno can you confirm the above, Does it still make sense to implement this

**Comment by wmdev0808** [comment]
@somangshu , Yes, I don't think there will be any method for autocomplete to work in our system
