### ISSUE TITLE
[Bug] Entering phone numbers and Currency numbers and clicking on enter button the phone number and currency numbers disappears

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7331]
## Description
Release Environment - It is observed that the Input widget of PhoneNumber/Currency Type - OnSubmit action - Entering phone number and currency number and clicking on enter button the phone number and the currency number disappears.

Expected Result:
Entered inputs should not disappears on clicking in enter button

### Steps to reproduce the behaviour:

1. Launch Appmsmith app in release environment 
2. Drag and drop input widget 
3. Change type to Phone 
4. Set onSubmit actions - show message 
5. Enter the phone number in widget and click on enter button and observe
6. Repeat the same steps for currency type and observe 

Videolink:
https://loom.com/share/b6ba40a7b4af47f685af4ee15cb13555

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [Release]

**Comment by vicky-primathon** [comment]
@YogeshJayaseelan  same is happening when Input widget type is text. And we follow the same steps as mentioned above. 
cc. @somangshu
