### ISSUE TITLE
[Bug] Modal widget overlaps with the list widget when there is no mouse movement

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7334]
## Description
Release - It is observed that when user places modal widget on top of list widget the modal overlaps with the list widget when there is no move movement and after move movement no overlap happens

Expected result:
Placing modal widget on top of list widget the modal widget should not overlap

### Steps to reproduce the behaviour:

1. Launch Appsmith app in release environment 
2. Drag and drop list widget 
3. Drag and drop modal widget and place it on top of list widget and do dont perform any move movement and observe

videoLink:
https://loom.com/share/e645a38c38b34e1093aeca2d155af8da

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [release]

**Comment by Tooluloope** [comment]
Cant reproduce
