### ISSUE TITLE
[Feature]: Support checkbox as a column type in table widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7338]
## Summary

As a dev, I should be able to add the following as column types

- checkbox

# Requirements

| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Column type: `checkbox` | Sets the column type to checkbox, alter default selected | High  | - |
| default value | The default value for checkbox; Boolean |  High | - |
| Disabled | Should the checkbox remain disabled | high | - |
| onChange | trigger event on change| High | - |
| Alignment | Alignment inside the table cell | Medium | - |

**Comment by somangshu** [comment]
@vibhandikyash does this ☝️ look alright

**Comment by laveena-en** [comment]
LGTM
