### ISSUE TITLE
[BUG] Bug in the Access Rights 

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#734]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login with Account A (User A)
2. Invite User B to User A's personal organization (Developer Access)
3. Now , in User A's personal organization, User B can be seen as a Developer (Expected)
Note: User B receives an email, DO NOT DO ANYTHING from the email
4. Invite User B to User A's personal organization (Administrator Access)
5. Go to User B's email and accept the invite - now login to Appsmith

Bug : In User A's as well User B's account, User B is still shown with Develop access.

In the screenshot, User A is ab@b.com while User B is saketagrawal2501@gmail.com .

<img width="1540" alt="Screen Shot 2020-09-25 at 12 26 13 PM" src="https://user-images.githubusercontent.com/49346036/94236168-65367b00-ff2a-11ea-957b-18948e728e62.png">

**Comment by trishaanand** [comment]
The intended implementation was that Invite would only be used to add a new member to the organization. Here 'Invite' is being used to update the role of the member instead of inviting. This scenario has not been handled so far.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand then that should be clear in the messaging. Also stands to reason that if I can invite anyone with any privilege, I should be able to update their role as well

**Comment by MatthewBerk** [comment]
Would the way to fix this issue be to check if an invite was already sent to the specific user and than invalidate the old one. Or to just update the role of the invited user so regardless of which invite they accept; the newest invite role will be used?

Or do you just want the ability to change an invited user's role without sending another invite?

I am new to this project and found this issue on a 'good first issues' site.

**Comment by Nikhil-Nandagopal** [comment]
@MatthewBerk the simple solution is to just update the role of the invited user. The role is set at the time of invite regardless of whether they accept it or not

**Comment by trishaanand** [comment]
@sims-keshri : I apologize but this is not suitable as a `Good First Issu`e without a deeper understanding of how ACL is implemented on Appsmith size. I will remove the tag for now. Feel free to request for another issue from the list. Thanks!
