### ISSUE TITLE
[Bug] Signing up with Github doesn't extract email ID and breaks reset password too

### ISSUE THREAD

**Issue by kundansonu** [appsmithorg/appsmith#7340]
## Description

When user sign up with GitHub the email ID in the profile is same as the GitHub username.

### Steps to reproduce the behaviour:

1. Sign up using GitHub 
2. Go to profile 
3. Check Email field, the value of email is same as the GitHub username.
4. Reset password functionality will also be broken because of the wrong email id

<img width="724" alt="Screenshot 2021-09-10 at 7 21 21 PM" src="https://user-images.githubusercontent.com/5444055/132864337-211620cf-a89f-458c-b8ee-4aa54e6f51dc.png">
<img width="1063" alt="Screenshot 2021-09-10 at 7 25 31 PM" src="https://user-images.githubusercontent.com/5444055/132864578-94d3c714-bfdd-4ffe-85e7-03c00e07fde2.png">

Reset Password request parameters:
<img width="1063" alt="Screenshot 2021-09-10 at 7 29 54 PM" src="https://user-images.githubusercontent.com/5444055/132865310-a62e4538-01ea-4824-a0fd-a6fe95e99d5b.png">
### Important Details

- Environment: production

**Comment by areyabhishek** [comment]
Thanks for reporting this. GitHub SSO doesn't pass email id to Appsmith so we are unable to send any emails. Because you can reset password using GitHub itself, we didn't think this would be a big problem.

**Comment by riteshkew** [comment]
Closing this as users can reset password through Github and GithubAPIs don't provide email
