### ISSUE TITLE
[Bug] Input Widget unable to drag/move around if positioned in a tabs widget

### ISSUE THREAD

**Issue by RickSoftpaw** [appsmithorg/appsmith#7341]
Hello There

With the latest updates we are unable to move the input witdget wich got placed into a tabs widget.
It will always select the tabs widget if you want to move the input field.

Thanks for a fix.

**Comment by areyabhishek** [comment]
Hi! Thanks for reporting this. We'll find a fix for this.
In meanwhile, could you use CMD+drag or CTRL+drag to move the widgets around? That should work.

**Comment by marks0351** [comment]
@ashit-rath looks like fix for #6723 has induced this bug. can u take a look?
