### ISSUE TITLE
[Bug] Inputs update does not work when there is a binding inside it

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#7344]
## Description

Repro: JS Snippets app

### Steps to reproduce the behaviour:

1. Update a snippet with bindings
2. Switch rows
3. The input does not update anymore

**Comment by Rishabh-Rathod** [comment]
@hetunandu seems similar to #10026, If not please open it again.

**Comment by Nikhil-Nandagopal** [comment]
Not related. This is because there are bindings that are part of the data

**Comment by Rishabh-Rathod** [comment]
Quoting @Nikhil-Nandagopal 
`I'm not able to reproduce it now and since it's not too prevalent a case let's close it`
