### ISSUE TITLE
[Bug] Deleted actions are failing to run

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#7345]
## Description

Repro: Stand up app

### Steps to reproduce the behaviour:
1. Running the main page sometimes shows this error

**Comment by Nikhil-Nandagopal** [comment]
Check JS Snippets app, the find query fails when smart substitution is off

**Comment by sumitsum** [comment]
The issue created by Hetu is different from the comment mentioned by Nikhil. Hence, creating a new issue for the failing `Find` query on Mongo plugin: https://github.com/appsmithorg/appsmith/issues/7399

**Comment by sumitsum** [comment]
The issue seems to be this: API server is returning an action in the on page load list even after it has been deleted.
