### ISSUE TITLE
[Bug] Bindings inside action config are getting replaced

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#7346]
## Description

When there is a binding inside a action field, the server replaces it when executing the action

### Steps to reproduce the behaviour:

1. Create an action and bind it to a input widget
2. Add a binding in the input text box
3. Run the action
4. Request is correctly sent with bindings but response has the bindings replaced

**Comment by Nikhil-Nandagopal** [comment]
Happens with updatequery in js snippets app with smart substitution on

**Comment by subrata71** [comment]
Hey @hetunandu 
Can you please give a concrete example to help reproduce this issue?
