### ISSUE TITLE
[BUG] New UI is distorted due to long organization name

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#735]
Attachment: https://drive.google.com/drive/folders/1JzmFpTXIfmmO89cQRSAR9sA0caJG8kWN?usp=sharing

Steps to replicate:
1. Go to Appsmith homepage
2. Observe Organizations listing on the left hand side of the page

Browser Details: Firefox
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

**Comment by satbir121** [comment]
@Nikhil-Nandagopal One solution can be to add an ellipsis and show a tooltip for organization names. How should we go ahead with this?

**Comment by satbir121** [comment]
@Debsourabh Please suggest what we should do for longer org names.

**Comment by Nikhil-Nandagopal** [comment]
@satbir121 Yes let's ellipsize

**Comment by A-Scratchy** [comment]
Hi, May I request this issue be assigned if it is still free? Happy to contribute :-)

**Comment by satbir121** [comment]
Sure @A-Scratchy Assigning it to you. Please read our [contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md).

Please reach out if you need any help.

**Comment by A-Scratchy** [comment]
Hi @satbir121, I'm struggling to get the dev env up and running for the front end. I keep running into typescript compilation errors such as ( 'xxx' is specified more than once, so this usage will be overwritten.  TS2783). I have followed the client setup guide and tried some other approaches but no luck yet.. any suggestions??

**Comment by satbir121** [comment]
@A-Scratchy Can you try using node version `v10.16.3`?

**Comment by A-Scratchy** [comment]
@satbir121, yes I have nvm set to use 10.16.3. Shall I post on the discord channel?

**Comment by satbir121** [comment]
@A-Scratchy Yes, that would be great!  Please post it on the discord channel. We can help you out in a better way.
