### ISSUE TITLE
[Feature] Font Awesome Support

### ISSUE THREAD

**Issue by tlawrence-TAG** [appsmithorg/appsmith#7350]
## Summary

Font Awesome support!

## Motivation

Lots of capability add... Dynamically set images based on values, etc.

**Comment by Nikhil-Nandagopal** [comment]
@tlawrence-TAG where would you want support for form awesome? Is it in the icon widget?

**Comment by tlawrence-TAG** [comment]
Any place that accepts text. Icon widget, table widget, etc.

**Comment by robertompf** [comment]
No news about this feature? would be.. "awesome"

**Comment by somangshu** [comment]
@robertompf we have not yet prioritised this issue. Can you help us understand you use case?
We are currently working on a design system for widget, this is something that we might plan to abstract. 

cc @ichik @jsartisan @KelvinOm

**Comment by KelvinOm** [comment]
We have added support for https://tablericons.com/. It will be available simultaneously with the release of Anvil #4630.
