### ISSUE TITLE
[Bug] Form widget buttons do not work well when placed inside a container

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7351]
## Description

So basically `formButtons` inside a `container` inside a `form` does not respond well to the required fields. 

### Steps to reproduce the behaviour:

https://user-images.githubusercontent.com/11089579/132937404-945e1cf5-fc22-4a21-b5e8-93b65dbdc383.mov

1. Create a form
2. add an input field to it
3. add a container to the form
4. copy the form buttons to the container
5. set all the visible buttons to required
6. Add value to the input field and see that only buttons outside the container react to the invalid form logic

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- Environment [production]

**Comment by Nikhil-Nandagopal** [comment]
@somangshu Form buttons were meant to only work inside forms. I suggest we close this and kill form buttons / Forms and introduce their logic to buttons / containers

**Comment by dilippitchika** [comment]
@somangshu closing this in favor of #3613 (deprecating form buttons)
