### ISSUE TITLE
JWT token authentication on AppSmith editor GUI

### ISSUE THREAD

**Issue by alexander-potemkin** [appsmithorg/appsmith#7353]
## Summary

JWT authentication will enable AppSmith editor interface to be build-into something bigger.

## Motivation

Currently AppSmith builder / editor gui requires separate authentication, meaning that AppSmith editor can't be integrated as a part of something bigger, not just the appsmith apps

## Additional Context

n8n provide such an ability, it would be very nice to have appsmith there as well

**Comment by Nikhil-Nandagopal** [comment]
@alexander-potemkin thank you for the feature request. Could you tell us a bit more on how you expect this to work?

**Comment by alexander-potemkin** [comment]
@Nikhil-Nandagopal apologies for the delay.
I would like to integrate AppSmith editor into my system and for this to work, I need to avoid using AppSmith build-in authentication. In a way I see, there are two ways to do that:
- OAuth, but it will require my already authenticated user still to see login screen
- by using JWT token: when AppSmith see the user request, it checks if there is a token in the cookie; if not - if it's provided in the HTTP header request and could be verified at the autority endpoint (for example, auth0), so user just get into the system and he never see any login screen and I can manage him/her using my authentication system (like auth0).

I might not be very good explaining things in here, please, let me know if it doesn't make sense or more details required.

**Comment by Nikhil-Nandagopal** [comment]
@alexander-potemkin are you talking about an SSO / SAML integration?

**Comment by alexander-potemkin** [comment]
@Nikhil-Nandagopal , nop about JWT; to simplify things, I would like to get authorized on AppSmith editor GUI using Auth0's https://auth0.com/docs/security/tokens/json-web-tokens

**Comment by mohanarpit** [comment]
@alexander-potemkin If I understand this correctly, all your users are managed in Auth0. You'd like a way for your users to directly authenticate against Auth0 instead of Appsmith's own user management system. This could potentially entail them clicking on "Acme Corp Sign-in" button as well which simply logs them in without any password because they've already authenticated against Auth0 earlier. Am I right about this? 

If yes, this will be available as part of our Open ID SSO integration which will allow you to connect to authentication systems like Auth0, Okta, Keycloak etc. directly from Appsmith by changing a few settings.

**Comment by alexander-potemkin** [comment]
Thank you, @mohanarpit ! When you say 'will be available' - what exactly do you mean by that? And when it will be available? :)

And just in case - that's not exactly what I meant, but, I guess this could also do the trick for now.

**Comment by mohanarpit** [comment]
@alexander-potemkin When I say "available", I mean that the feature will be should be released or usage by the end of Q4, 2021. Just a heads up, this feature will most likely be in a paid version of Appsmith and not in the community version.

**Comment by alexander-potemkin** [comment]
@mohanarpit , yeah, that's what I expected, to be honest :)
So, any chance for an open source JWT authentication then? :)

**Comment by hiteshjoshi** [comment]
Closing this. Will use #2840 for communication.
