### ISSUE TITLE
[Feature]QR Reader/Barcode reader widget

### ISSUE THREAD

**Issue by WSDsuperace** [appsmithorg/appsmith#7354]
## Summary

Add and easy way to scan and decode QR and Barcodes

## Motivation
Now QR codes are more or less everywhere, on tickets, ads and not least on many Covid Certificates and Covid Tracking systems. 
Many Appsmith users and user cases are on mobile hardware where the camera is already available.
## Additional Context

Imagine a Widget similar to [https://blog.minhazav.dev/research/html5-qrcode.html](url) that can return the data to Appsmith. Of course there are many ways to implement this, one way is almost like an Iframe running HTML5/JS.  I have a feeling it would almost be possible to reuse much of the new "smarter" Iframe that I think is under development (access POST/return data in Appsmith). But the HTML5 content must be sourced securely from Appsmith's https or the browser will not allow access to the hardware.

By using an external library maybe the core functionality can be "outsourced" and Appsmith does not have to care about keeping this function updated?

Start/Stop scanning, Camera On/Off, Format settings, Actions on return data

This could potentially be the start of a new series of Widgets. HTML5 based to get access to the hardware such as NFR reading, camera, microphone.....

**Comment by areyabhishek** [comment]
Thanks for your request! We are introducing a camera widget soon. QR or barcode scanner is on the cards as well.

**Comment by Nikhil-Nandagopal** [comment]
@WSDsuperace thank you for your feature request :) We have this issue currently tracked here #4577 I'm closing this so we can better track the issue at a central place and have it prioritized.
