### ISSUE TITLE
[Bug] selctedOptionLabel and selctedOptionValue of dropdown not working in mobile Edge browser.

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#7355]
## Description

selctedOptionLabel and selctedOptionValue giving back undefined in mobile Edge browser but works fine in Chrome.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [Android Mobile]
- Browser [Edge]
- Environment [production, release, deploy preview]

**Comment by parul5sahoo** [comment]
@marks0351 Would like to work on this issue.

**Comment by somangshu** [comment]
@parul5sahoo this issue might be a bit more involved.

@marks0351 do we know what need to be done here?

**Comment by marks0351** [comment]
@somangshu this issue is bit unconventional. we don't know the exact fix for this.
@parul5sahoo if you like to take it up,
 this issue happens only in an Edge browser/ Android mobile. 
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/DropdownWidget/widget/index.tsx#L190
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/DropdownWidget/widget/index.tsx#L191
are the lines evaluated to assign values to selectedOptionLabel and selectedOptionValue respectively.
you can start by investigating why it doesn't work as expected in Edge and then make changes to make it work in all browsers.

Potential Causes of Bug: 
- Check if lodash's findIndex works as expected in Edge Browser.
- Check if Optional chaining operator is supported in Edge Browser.

**Comment by parul5sahoo** [comment]
> @somangshu this issue is bit unconventional. we don't know the exact fix for this. @parul5sahoo if you like to take it up, this issue happens only in an Edge browser/ Android mobile. https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/DropdownWidget/widget/index.tsx#L190 https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/DropdownWidget/widget/index.tsx#L191 are the lines evaluated to assign values to selectedOptionLabel and selectedOptionValue respectively. you can start by investigating why it doesn't work as expected in Edge and then make changes to make it work in all browsers.
> 
> Potential Causes of Bug:
> 
> * Check if lodash's findIndex works as expected in Edge Browser(Mobile Version).
> * Check if Optional chaining operator is supported in Edge Browser(Mobile Version).

@marks0351 okay will try to figure out the problem.

**Comment by laveena-en** [comment]
It's working fine on my Android device with the latest version of Edge (105.0.1343.34).
Hence, closing this issue.
