### ISSUE TITLE
[Bug] Sharing an application publicly must make js collections readable and executable by anonymous users

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#7356]
Public apps that use JS editor will fail to execute for anonymous users currently because the permissions for viewing and executing js collections are not shared appropriately.

**Comment by nidhi-nair** [comment]
@prapullac I didn't quite understand your comment. Are they not able to see JS object related changes in view mode?

**Comment by prapullac** [comment]
@nidhi-nair : Sharing the video below please have look 
https://www.loom.com/share/8dbc2ad175d8454798b1d47b8c7be059
