### ISSUE TITLE
[Bug] Group Option Popup zindex (hides inside the Form Widget container)

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#7358]
## Description

[What happened]
<img width="423" alt="Screenshot 2021-09-10 at 9 40 24 PM" src="https://user-images.githubusercontent.com/23132741/133003381-49abf3c3-363a-4399-81c4-cece562fbe3f.png">

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to New Application and Go to any Empty Page
2. Add a form widget and decrease its size as shown in image.
3. Try to group the buttons

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Sarthakagarwal22** [comment]
I would like to pick up this issue

**Comment by somangshu** [comment]
Greetings @Sarthakagarwal22, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by Sarthakagarwal22** [comment]
<img width="531" alt="Screenshot 2021-10-05 at 9 56 41 AM" src="https://user-images.githubusercontent.com/16587695/135960003-076aab15-7aa5-423a-b386-9903234e2ee1.png">
Does this look like a valid solution

**Comment by somangshu** [comment]
@jsartisan need you to check this out

**Comment by jsartisan** [comment]
@Sarthakagarwal22 the valid solution for this is to use the portal to render the context menu. The reason why this is happening is that the context menu is rendering in the same container.

**Comment by Sarthakagarwal22** [comment]
@jsartisan I would need some help here. I tried using the portal, but I couldn't understand the flow to be honest. A basic approach that I took was, added a css property, which made it work in form. Can we pair up somehow to solve this?

**Comment by jsartisan** [comment]
Yes. Let's have a call tomorrow? Anytime between 10-7.

**Comment by jsartisan** [comment]
@Sarthakagarwal22 Can you come on discord?

**Comment by Sarthakagarwal22** [comment]
Hey @somangshu I am sorry, I dont think, I would be able to give time to this. I thought it was easier, hence I picked it, but looks like its a bigger task.

**Comment by srijit2002** [comment]
@somangshu I like to work on this issue. Can you please list the files, I need to work on.

**Comment by vividh** [comment]
@jsartisan @Rishabh-Rathod I'd like to take this up! Should be fun working with React Portals for once. 😏

**Comment by Rishabh-Rathod** [comment]
Greetings @vividh , thanks for showing interest 🎉 , This is all yours. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate it if you can open a PR within the next 4 days.

**Comment by digant2482** [comment]
Hi, I would like to work on this issue ? @jsartisan just to be clear what do you mean by portal is it the portion shown in image 
<img width="253" alt="Screenshot 2023-10-26 145213" src="https://github.com/appsmithorg/appsmith/assets/73285842/f2feb044-ba36-4be4-bc33-473b6fc97262">

**Comment by somangshu** [comment]
Greetings @digant2482, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate it if you can open a PR within the next 2 days and LMK here.

**Comment by digant2482** [comment]
@jsartisan, hi just wanted to clarify if 
<img width="253" alt="278282336-f2feb044-ba36-4be4-bc33-473b6fc97262" src="https://github.com/appsmithorg/appsmith/assets/73285842/53460d44-f587-442e-b611-b3c4b848dada">
If this is the area, shown in image where we want context menu ?

**Comment by jsartisan** [comment]
@digant2482 No no, sorry. You misunderstood the solution. Currently the context menu is rendering in a container that has overflow hidden. We need to use portal ( https://react.dev/reference/react-dom/createPortal / https://www.radix-ui.com/primitives/docs/utilities/portal ) to make sure the context menu is rendered outside of it with proper position.

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working
