### ISSUE TITLE
[BUG] Inconsistent query execution on pageload.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#737]
## Description
Inconsistent query execution on page load.

I think only the first query for any table (`order` in our case) is getting executed `onPageLoad`
`PostgreSQL -> Mock Database -> orders`
First Query -> `SELECT * FROM orders where id = 9;` -> Getting Executed.
Second Query -> `SELECT * FROM orders where id <= 9 LIMIT 10;` -> Not Getting Executed.

[Video In Action](https://drive.google.com/file/d/1upYwlfFwr8IOp9h200DO7KUfpRARgUPy/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 can you verify this?

**Comment by sharat87** [comment]
Hey @visibleajay, can you confirm if both of the `getUser` as well as `getUsers` are connected to some widget in the editor? If the data from a query is not used anywhere, it won't load it as an optimization measure. If both of these actions are indeed used for a widget in the editor and yet they are not loading on-page-load, that would be a bug. So, could you confirm this please?

**Comment by visibleajay** [comment]
@sharat87 Showing consistent result on `getUser` and `getUsers` when both are connected or disconnected from widget. Thank You for the clarification!.

**Comment by sharat87** [comment]
Thank you for confirming.
