### ISSUE TITLE
[Bug] Debug options on debugger and hover state for CTA

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7380]
## Description
- [ ] User must be able to differentiate errors on Debugger in normal and hover state as seen on the Figma file to inform about CTA options. Currently, both normal and hover state are underlined in normal text (not bold)
![image](https://user-images.githubusercontent.com/79509062/133070071-8daabbf7-40a1-4663-b507-e30560132fba.png)

- [x] The wand next to error code in the Debugger also triggers debugger CTA which is not obvious right now to the user. Include some kind of normal/hover state difference so user would know to click on it.

- [x] Tooltip on wand is "Troubleshoot issue" but is triggered with some lag that can easily be missed if the user is moving quick

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5e5a71a27dbd499399f73d3928630899-00001.gif)](https://www.loom.com/share/5e5a71a27dbd499399f73d3928630899)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by akash-codemonk** [comment]
> ## Description
> * [ ]  User must be able to differentiate errors on Debugger in normal and hover state as seen on the Figma file to inform about CTA options. Currently, both normal and hover state are underlined in normal text (not bold)

This was the behaviour initially. The problem was it was hard to know whether the message was clickable that is why it was underlined by default.
