### ISSUE TITLE
[Bug] Missing error code in debugger for evaluation type error on Input Widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7383]
## Description
Error is missing in debugger for evaluation type error on Input widget

### Steps to reproduce the behaviour:
1. Type in an incorrect JS code on Input widget and observe evaluation error on evaluated objects of PP
2. Go to Debugger and observe missing error present for the Input widget

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/133079168-7cbba694-584d-4cb7-b1ff-0548ce07cc55.png)

**Comment by akash-codemonk** [comment]
No longer able to replicate this. Seems to work as expected now.

**Comment by ramsaptami** [comment]
Seems to be working on release now.
