### ISSUE TITLE
[Bug] Debugger scroll extends to the entire pageand CTA option does not collapse on scroll

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7384]
## Description
- [ ] onClick error message on Debugger, CTA options do not collapse when user scrolls hence CTA options overflows on to the canvas (seen on video)

- [ ] Debugger scroll expands to the entire page when user clicks on an error message to open CTA options (second part of the video)

### Steps to reproduce
1. Go to debugger and click on errors and observe the CTA options pop-up move with scroll on to the canvas
2. Click on an error message (not the first error message) and scroll - observe the scroll expand

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ed12d1ca18834d5e9747e074efdc3843-00001.gif)](https://www.loom.com/share/ed12d1ca18834d5e9747e074efdc3843)

**Comment by BhandarkarPawan** [comment]
I'd like to work on this!

**Comment by tauantcamargo** [comment]
could i investigate it?

**Comment by ramsaptami** [comment]
@tauantcamargo absolutely, please go for it

**Comment by ramsaptami** [comment]
Issue still exists on current prod
