### ISSUE TITLE
[Bug] Error message appears under Logs in Debugger, not Errors

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7390]
## Description
Error is incorrectly present under Logs in the Debugger

### Steps to reproduce the behaviour:
1. Create a query under Postgres database and run an incorrect query
2. Observe the error to be present under **Logs** not **Errors**

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ad2beb4c19824d5792aa75e83f787a61-00001.gif)](https://www.loom.com/share/ad2beb4c19824d5792aa75e83f787a61)

**Comment by ramsaptami** [comment]
This particular scenarios seems to be working. I'll close this for now and reopen when I come across this again since I have seen this before but can't recollect the steps for repro.

**Comment by hiteshjoshi** [comment]
@akash-codemon
This is still happening.  Need to find why

https://user-images.githubusercontent.com/217911/135208575-38230105-7d57-48b0-b243-a08ebfa67c44.mov

**Comment by Nikhil-Nandagopal** [comment]
It happens for new apps till the user gets an error in the widget. Create a new app and immediately try to create a query with an error. @akash-codemonk

**Comment by akash-codemonk** [comment]
@ramsaptami @hiteshjoshi @Nikhil-Nandagopal Tried quite a few ways. Finding it hard to replicate. Tried with a new application as well, new user and new organisation as well. 

https://user-images.githubusercontent.com/67054171/135226844-ee6c9c25-1511-4096-ab2f-a628a7f83fb0.mov

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk found an amazing reason for this. If you press run it works. If you hit cmd + enter, it breaks

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @ajinkyakulkarni @hiteshjoshi this sounds like bad code design somewhere

**Comment by akash-codemonk** [comment]
@Nikhil-Nandagopal Doesn't seem to be the case. Seems to work with shortcut as well. It goes through the same action execution flow.

**Comment by akash-codemonk** [comment]
Ok this issue can be replicated by just renaming entity names. Was listening to an incorrect action type for page switch events.
