### ISSUE TITLE
[Bug] Example DB's overlap when user screen size is reduced

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7391]
## Description
Example DB's under Datasources overlap when screen size is reduced 

### Steps to reproduce the behaviour:
1. Go to Datasources and open up browser console
2. Increase console width and observe example DB's overlap with Databases

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/660984ead8fd41f4acf84f36503e0fe3-00001.gif)](https://www.loom.com/share/660984ead8fd41f4acf84f36503e0fe3)

**Comment by hetunandu** [comment]
The Integrations grid needs to be responsive to different screen sizes.

Look at [NewIntegrationsWrapper](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx#L77) and [MockDatasourceWrapper](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx#L13) to start debugging the problem 

Please read the [contribution guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) before working on this issue

**Comment by JubayerJoy** [comment]
Hi @hetunandu, would love to work on this.

**Comment by ramsaptami** [comment]
It's yours @JubayerJoy. You can pick this up.

Please take note of the info Hetu has mentioned above.

**Comment by JubayerJoy** [comment]
Hi @ramsaptami,
can't reproduce this error. 😕
My Env is the same as yours.

Was this issue fixed?
![video](https://user-images.githubusercontent.com/31549564/135585187-d28f8bae-9749-439a-a78f-af697601ed5b.gif)

**Comment by ramsaptami** [comment]
Hey @JubayerJoy, thanks for reaching out. 

You'll need to have at least one datasource present on your application since we currently list mock DB's on the top for a fresh application. So for our mock datasources to appear at the bottom, please add any datasource and then try to reproducing the case. 

Just tried to reproduce this on my local and here's the screenshot of the overlap issue. Please do let me know if you need more information.
![image](https://user-images.githubusercontent.com/79509062/135586296-d459fecc-3b73-4b67-a58f-256d27b32179.png)

**Comment by JubayerJoy** [comment]
@ramsaptami Thanks for guiding,
Yap, was able to reproduce this. 👍 

![video (1) (1)](https://user-images.githubusercontent.com/31549564/135602954-c8e5ffef-ad7a-486b-9bf6-b92daec76e22.gif)

Will open a PR after solving this.
cheers 🎈
