### ISSUE TITLE
[Bug]z-index issues when user add comments in the container widget

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7396]
## Description

[What happened]Z-index issues when users add comments in the container widget

### Steps to reproduce the behaviour:

1. Go to the application
2. Drag and drop the container widget
3. click on the comment icon 
4. Drop the comment icon in the corner of the container 
5. the icon is displayed as in below screenshot

![image](https://user-images.githubusercontent.com/45958978/133199566-1a9dfb70-7ef7-4dfe-bc12-33f82ef6c25a.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser  chrome
- Environment release

**Comment by pranavkanade** [comment]
https://github.com/appsmithorg/appsmith/issues/5100#issuecomment-920641254
- [ ] Comment pins cut off at the top of the canvas (z-index) issue
