### ISSUE TITLE
[BUG] FilePicker isn't persisting the selected file on delete/undo transition.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#740]
### Steps to reproduce the behaviour:
1. Add File Picker widget to container.
2. `Select File`, upload and close. 
3. Delete FilePicker using FilePicker widget.
4. Undo and the selected file would be removed.

[Video in Action](https://drive.google.com/file/d/1dTonRyuoCsSNax-gKAGz5p59QuiOxkjI/view)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
Closing this. Meta data needn't be persisted across undo / redo
