### ISSUE TITLE
[Bug] [Release] Text on text widget overlaps after copy/paste of widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7400]
### Steps to reproduce the behaviour:
1. Drag and drop text widget
2. Copy paste the widget
3. Now change the text property in the text widget
4. Observe that the new text overlaps the new widget
5. Also after deleting this widget from canvas still shows on the canvas

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/291890fee95a4d33bd41cbcf76dd5167-00001.gif)](https://www.loom.com/share/291890fee95a4d33bd41cbcf76dd5167)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment Release

**Comment by jsartisan** [comment]
@vivekverma2312 I am not able to repro these for the steps mentioned above.
