### ISSUE TITLE
[Bug] Change the error message for duplicate app name in collaborated org

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7401]
## Description
When multiple users are trying to create an app on a common organization, the changes for newly added app is not real time hence there's a conflict on app name causing an error. This error asks user to contact Appsmith support, but a simple page refresh loads the new app. Ideal scenario would be to have newly added app changes to reflect real time, but in the absence, the error message can be changed to inform the user of a page refresh instead of contacting support.

### Steps to reproduce the behaviour:
1. Share organization with multiple users and create an app from User 1
2. Now try to create an app from User 2 simultaneously and observe the error message displayed (as seen in screenshot)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/133215283-d8329785-d814-4ebf-955d-9d6111db6084.png)

**Comment by oliver-pham** [comment]
Can I take on this issue as a first-time contributor this repo?

**Comment by ramsaptami** [comment]
It's yours @oliver-pham 

Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by MJjainam** [comment]
Hi @oliver-pham, is this being worked upon? Or can I pick it up?

**Comment by Catzla** [comment]
Hey @ramsaptami can i take this issue?

**Comment by ramsaptami** [comment]
Hi @Catzla, appreciate you showing interest in resolving this issue 😊

In the interest of keeping things fair, we'd like to give @oliver-pham a chance to fix this since they requested to pick it up.

We have a 4 day timeline to raise a PR for assigned issues. In the event that the PR isn't resolved within that timeframe and if you're available, I'll assign it to you. Hope that's ok!

Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by MJjainam** [comment]
Thanks @ramsaptami 
Is there any exact error message that you have in mind?

**Comment by ramsaptami** [comment]
Something on the lines of another app being present with the same name and that a page refresh to resolve this should be good enough @MJjainam

**Comment by ramsaptami** [comment]
Hey @Nikhil-Nandagopal, we're still throwing an error for duplicate app name without a proper description and resolution. Should we keep this open?
![image](https://user-images.githubusercontent.com/79509062/224302151-7d2bc555-aa23-4fc9-897b-003792ce3b4b.png)

**Comment by ramsaptami** [comment]
Could we add something around **page refresh** to the error message? The new change does not address the problem the right way. When a user is adding a new application and one with the same name exists then they do not have control over renaming the application, hence hinted error message is incorrect.
![image](https://user-images.githubusercontent.com/79509062/236407992-663ca500-9f09-4d6e-9f89-b96cfb9847f1.png)
cc: @abhiappsmith

**Comment by ramsaptami** [comment]
Retry logic appends duplicate app name characters ((1), (2), (3)..) instead of throwing an error in this scenario
