### ISSUE TITLE
[Bug] The recorder.url and recorder.value are 'undefined' in the entity explorer when the widget is Dragged and dropped  

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7404]
## Description
Release/Production Environment - Recorder Widget - It is observed that 'undefined' value is displayed for recorder.value and recorder.url in the entity explorer for recorder widget when the widget is dragged and dropped or after recording is saved and clicking on recording icon again

**Expected result:**
When there is no value empty values can be displayed {} instead of undefined

### Steps to reproduce the behaviour:

1. Launch appsmith app in release environment 
2. Drag and drop recorder widget 
3. Expand the widget in the entity explorer and observe
4. Click on recording icon and save recording 
5. Expand the widget in the entity explorer and observe - Values will be displayed in the recorder.url and recorder.value 
6. Click on recording icon again in saved mode and observe

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur ]
- Browser [chrome, safari]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-14 at 1 07 11 PM" src="https://user-images.githubusercontent.com/35128442/133222001-e10b8c4b-3867-4f8b-a6bd-c4ca65be1398.png">

**Comment by somangshu** [comment]
@YogeshJayaseelan how is this a valid use case, the URL is not an object for that to be default. Also in the init state the URL and value will always be undefined, This should be expected. 

Closing this
