### ISSUE TITLE
[Bug] Adaptive axis toggle is not functioning for charts 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7407]
## Description
Release - Chart Widget - It is observed that enabling adaptive axis on chart doesn't work as expected 

**Expected result:**
Enabling adaptive axis on chart should display more adaptive scale on  x and y axis values 

### Steps to reproduce the behaviour:

1. Launch appmsith app in the release environment 
2. Drag and drop chart widget 
3. Enable Adaptive axis toggle button and observe

**Videolink:**
https://loom.com/share/e65c50a94b504ea8b8cc2c8f59d3a8df

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [release]

**Comment by somangshu** [comment]
Non-Issue
