### ISSUE TITLE
[BUG] Deletion process is cut short if another widget is dragged to the page

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#741]
Attachment: https://drive.google.com/drive/folders/1WTvpeS8Lwd_feuq24tcYsfkDCry4-qLZ?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Edit an app
2. Drag a widget (Say Widget A)
3. Delete Widget A and deletion can be seen on top right corner (There is timer running where in user has a chance to press undo)
4. Drag Widget B while Widget A deletion is in progress

Actual Result: Deletion process of Widget A is abruptly terminated 
Expected Result: Deletion Process should take its own time and not depend on dragging another widget.

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 although this is unexpected, we're not tracking this as a bug since we went ahead with this implementation due to certain tech constraints
