### ISSUE TITLE
[Task] Refactor Generate page form

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#7411]
Goal is to make 
- the least decision on frontend side, 
- code more readable, 
- extensible and less error-prone.

Tasks to do
- [x] Remove Plugin package name mapping constant from frontend
- [ ] Have custom component name sent from backend for a plugin
- [ ] Make GeneratePageForm as a base component that is extended for different plugins

**Comment by Rishabh-Rathod** [comment]
Need to remove this from frontend
```

export const PLUGIN_PACKAGE_NAME = {
  MONGO_DB: "mongo-plugin",
  S3: "amazons3-plugin",
  GOOGLE_SHEETS: "google-sheets-plugin",
  FIRESTORE: "firestore-plugin",
};

export const PluginFormInputFieldMap: Record<
  string,
  { DATASOURCE: string; TABLE: string; COLUMN: string }
> = {
  [PLUGIN_PACKAGE_NAME.MONGO_DB]: {
    DATASOURCE: "MongoDB",
    TABLE: "collection",
    COLUMN: "field",
    FORM_UI: "default" // this can be empty also
  },
  [PLUGIN_PACKAGE_NAME.S3]: {
    DATASOURCE: "S3",
    TABLE: "bucket",
    COLUMN: "keys",
     FORM_UI: "s3_form"
  },
  [PLUGIN_PACKAGE_NAME.GOOGLE_SHEETS]: {
    DATASOURCE: "Google Sheets",
    TABLE: "spreadsheet",
    COLUMN: "keys",
    FORM_UI: "google_sheet_form"
  },
  DEFAULT: {
    DATASOURCE: "SQL Based",
    TABLE: "table",
    COLUMN: "column",
    FORM_UI: "default" // this can be empty also
  },
};

```
@abhvsn you can refer to this for backend data that needs to be sent with the plugin.
I added the `FORM_UI` field which has the name of the form the frontend needs to render.

**Comment by abhvsn** [comment]
@Rishabh-Rathod can we close this if already been taken care of?

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod can we close this if already been taken care of?

The frontend part of it is not yet completed.
