### ISSUE TITLE
[Enhancement] Minimize button on home page help pop-up needs better placement

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7412]
## Summary
Minimize button needs an even padding across (at the bottom) to be more uniform.

![image](https://user-images.githubusercontent.com/79509062/133232670-025f8fbf-f9d5-405b-b3d2-039e815de946.png)

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi @areyabhishek can we get a better design for this popup for the appsmith design system project?

**Comment by Nikhil-Nandagopal** [comment]
This is now removed
