### ISSUE TITLE
[Bug] On share as Public and App-viewer the JS object data is not visible to user

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7413]
Steps to reproduce:
1) Add a JS object 
2) Bind the data to a widget 
3) Deploy the App 
4) Click  and do a Public share 
5) now copy the URL and paste 
and observe

Video :
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c8e664576e9a46fcb4aba57c0aaf5350-00001.gif)](https://www.loom.com/share/c8e664576e9a46fcb4aba57c0aaf5350)

Application URL
https://release.app.appsmith.com/applications/61405701b2c0e74642f8d4cf/pages/61405701b2c0e74642f8d4d1

Observation:
Only Widget is displayed to user and data binded inside is not displayed to the user

Expectation:
The user must be displayed with data

**Comment by mohanarpit** [comment]
Closing this as this is expected behaviour. In a public app we don't know the user. Hence, JS objects are a disabled feature. This is why beta features will not show up in public apps until they are released for GA.

**Comment by Aishwarya-U-R** [comment]
Update:  Now JSObjects is available to all users. Hence it should be visible to public apps as well.
