### ISSUE TITLE
[Bug]All the buttons in the datasource edit pane are transparent & without colour

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7419]
## Description

[What happened]All the buttons in the datasource edit pane are transparent & without colour

### Steps to reproduce the behaviour:
![image](https://user-images.githubusercontent.com/45958978/133241689-2a9945a4-8ea1-4ece-9a37-1305820fb81c.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOSX]
- Browser chrome
- Environment release

**Comment by hetunandu** [comment]
this issue no longer exists

**Comment by hetunandu** [comment]
<img width="1407" alt="Screenshot 2021-09-29 at 3 18 31 PM" src="https://user-images.githubusercontent.com/12022471/135245392-29e3a22a-fa21-465d-8a61-49d43e1391ff.png">
