### ISSUE TITLE
[BUG] Internal server error while processing the request

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#742]
## Description

Ran a "Select * from TABLE_NAME" query only to receive the error. 

While it is not at all advisable to run a "select *" query, the platform should either disable it or show an appropriate error or work as desired. 

Tried the same using adminer on my localhost and the query works.

![image](https://user-images.githubusercontent.com/4999463/94271690-967d6e00-ff5f-11ea-9f8b-1ccb1bb0be64.png)

### Additional Information

**Where is the database hosted?** Amazon RDS
**What is the size of the table?** 300024 rows in the table.

### Important Details

- Version: Cloud
- OS: Windows 10
- Browser: Google Chrome (v. 85.0.4183.102)

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 Can you verify this was a timeout issue? Then we can update the issue to being a timeout message problem

**Comment by sharat87** [comment]
This doesn't look like a timeout issue. The message from a timeout problem looks something like "no terminal signal within 10000ms".

@harishkotra, does the query work if you specify a limit? Like `SELECT * FROM employees LIMIT 10;`?

**Comment by harishkotra** [comment]
@sharat87 This is what is happening now when I try to run the query: https://recordit.co/Max8oDk7tC (Is this a new bug?)

**Comment by harishkotra** [comment]
@sharat87 It works with the LIMIT value.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can we triage this issue and find out why it was happening?

**Comment by mohanarpit** [comment]
In these scenarios, the server typically throws an "Internal Server Error" when it runs out of memory. If a user tries to load a large amount of data in a single query, the server will error out. The limit for now is 10 MB of data.

**Comment by Nikhil-Nandagopal** [comment]
Got it. Then I'm closing this issue because even the client would not be able to handle that much data
