### ISSUE TITLE
[Enhancement] Provide more space below the option to choose welcome tour on Sign Posting page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7422]
## Summary
Equal padding above and below "Not sure where to start? Take the welcome tour" on Sign posting page

![image](https://user-images.githubusercontent.com/79509062/133244333-dc398c15-1bf5-45d0-a10a-6934148c5cc3.png)

**Comment by albinAppsmith** [comment]
@ramsaptami Can you test this in below DP
https://appsmith-git-chore-7422-sign-posting-equal-f1884b-get-appsmith.vercel.app/

**Comment by ramsaptami** [comment]
This looks good @albinAppsmith, we can merge this. A small change on this - can we move the comma before the space in the last step of signposting please?
![image](https://user-images.githubusercontent.com/79509062/163232644-b21db06c-8194-43d7-8e5d-77afb73ba449.png)

**Comment by albinAppsmith** [comment]
@ramsaptami  made that change also
