### ISSUE TITLE
[Bug] [Release] List image flicker after copy/paste of list widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7423]
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/71845aca18f14954ab999657a5596cb4-00001.gif)](https://www.loom.com/share/71845aca18f14954ab999657a5596cb4)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment Release

**Comment by marks0351** [comment]
@vivekverma2312 cannot see this flicker in chrome firefox or safari. need more details. can u share me the particular application.
