### ISSUE TITLE
[Bug][Release] Data in widget gets deleted and Console Error on undo of text widget inside list widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7429]
Error: `Cannot convert undefined or null to object`

### Steps to reproduce the behaviour:

1. Drag and drop a list widget
2. Delete text widget present inside list widget
3. Click on undo
4. Observe the error in console and also observe that the data in text widget gets deleted

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7108b521ef714446bbd4aba58ff9d5fd-00001.gif)](https://www.loom.com/share/7108b521ef714446bbd4aba58ff9d5fd)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment Release

**Comment by aswathkk** [comment]
@vivekverma2312 Unable to reproduce this issue now.

**Comment by Tooluloope** [comment]
Cant reproduce
