### ISSUE TITLE
[BUG] FilePicker widget screen isn't clearing after submitting the form.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#743]
## Description
FilePicker widget screen isn't clearing after submitting the form.

### Steps to reproduce the behaviour:
1. Upload any file using FilePicker.
2. Submit form & the form is getting reset.
3. But the FilePicker `file browse` screen is persisting.

[Video In Action](https://drive.google.com/file/d/1UQDSBenesC9wMxb7ZP5ja6mI2pF6eq5f/view?usp=sharing).

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by dowenrei** [comment]
Hi @visibleajay, can I work on this?

**Comment by Nikhil-Nandagopal** [comment]
@dowenrei go for it!

**Comment by dowenrei** [comment]
Hi Nikhil, so sorry I can't work on this as of now as I can't get Appsmith to run on WSL, I would work on other documentation/backend request. Cheers.

**Comment by Nikhil-Nandagopal** [comment]
@dowenrei, not a problem! Thank you for letting us know 😃

**Comment by aaaaaanthony** [comment]
Is this fixed? I'm still running into it.

https://streamable.com/fmv5kd

**Comment by Nikhil-Nandagopal** [comment]
This does seem to have broken again. @somangshu can we please fix this and the issue with the file picker loading state?

**Comment by Nikhil-Nandagopal** [comment]
We should also have a test case so this never happens again

**Comment by somangshu** [comment]
We are fixing this in #6206, @techbhavin kindly link this as well to the PR
