### ISSUE TITLE
[Enhancement] The data type in the input widget can have separate sub setting options similar to menu items in the menu widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7431]
## Description
Enhancement - Input widget - It is observed that most of the property fields in the input widget are same for most of the input data types and causing few problems.

1.By default the data type is text and when user sets max character to 5 and changes to phone or currency and enters values more than 5 then error message is displayed for number, phone and currency data types that max character is more than default max character 

2. Assume if user chooses phone number type and sets the tool tip message something related to phone number - and on choosing any other data types still the tool tip of phone number will be displayed. 

**Suggestion:**
If we change the design as per the menu items of menu widget we can set unique functionality for each data type

[What happened]

### Steps to reproduce the behaviour:
Scenario 1 : 
1. launch appmsith app in release or production environment 
2. drag and drop input widget 
3. Choose the type as text and set max character to 5
4. Change the default type to number, phone or currency and try to enter character value more than 5 and observe the error message 

Scenario 2 :
1. launch appmsith app in release or production environment 
2. drag and drop input widget 
3. Choose the data type to phone number and try to set tooltip, placeholder or label
4. Change the data type to number or currency field and observe still the tooltip, placeholder and label will be of phone number

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
point 1 is fixed on release, Point 2 seems invalid
