### ISSUE TITLE
[Bug] Suppress "unauthorized. redirecting to login page" toaster, when User visits welcome page.

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#7433]
## Description

![Screenshot 2021-09-14 at 14 57 19](https://user-images.githubusercontent.com/5328605/133252684-f9789bd8-ad98-4126-bb94-1b47e717f1a1.png)

### Steps to reproduce the behaviour:

1. Visit instance root url after installing.
2. observe the error toaster.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by RakshaKShetty** [comment]
![image](https://user-images.githubusercontent.com/45958978/133395289-11f6d380-cc24-4d9d-bce3-8ff1c8c83c5a.png)
