### ISSUE TITLE
(JS-0085) Found some variables redeclared

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#7441]
## Description
In JavaScript, it&#x27;s possible to redeclare the same variable name using `var`. This can lead to confusion as to where the variable is actually declared and initialized. Example - The not-preferred way :

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0085/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0085/occurrences/)

**Comment by bharat-patodi** [comment]
If it is fine, I'd like to take this up

**Comment by samyakjain10** [comment]
Hi, I would like to work on this issue.

**Comment by sbalaji1192** [comment]
Hey @samyakjain10i! I've assigned this issue to you, please make sure to read our [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md) before raising a PR!

**Comment by samyakjain10** [comment]
Hey! I have fixed this issue. Please review!

**Comment by yatinappsmith** [comment]
Verification not required
