### ISSUE TITLE
(JS-0128) Should not have unused variables

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#7442]
## Description
Found variables that are declared but not used anywhere.

## Occurrences
There are 247 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0128/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0128/occurrences/)

**Comment by bharat-patodi** [comment]
If it is fine, I'd like to take this up @mohanarpit

**Comment by mohanarpit** [comment]
It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) to learn more about setting up the code & contributing a fix.

**Comment by dazzlerkumar** [comment]
Hi @mohanarpit, I hope you're good. As I can see it's been 17 days since the issue has been created. Can you assign it to me? or Should I make a PR without being assigned ?

**Comment by bharat-patodi** [comment]
Right here.
I'll be working on the issue this weekend if it's fine with everyone.

**Comment by CCCCCCieL** [comment]
Hi, @mohanarpit may I work this issue?

**Comment by Vishrut19** [comment]
Can I work on this issue?

**Comment by ManojSharma18** [comment]
Hey i am beginner please give me any starting friendly issues.

**Comment by Vishrut19** [comment]
> Hey i am beginner please give me any starting friendly issues.

Hello @ManojSharma18, Always look for Good First Issues to Contribute to - https://github.com/appsmithorg/appsmith/issues#:~:text=we%27ve%20collected%20some%20good%20first%20issues%20for%20you

**Comment by vishalpatil1202** [comment]
Hello @mohanarpit ,
As this issue is still open, can I work on this issue?

**Comment by Abhiarm** [comment]
Can I get assigned this @mohanarpit

**Comment by yash9871** [comment]
hey @mohanarpit  @Vishrut19  can i work on it ?
