### ISSUE TITLE
(JS-0359) Detected the use of require statements except in import statements

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#7443]
## Description
In other words, the use of forms such as `var foo = require(&quot;foo&quot;)` are banned. Instead use `ES6` style imports or `import foo = require(&quot;foo&quot;)` imports. Example - The not-preferred way :

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0359/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0359/occurrences/)

**Comment by bharat-patodi** [comment]
If it is fine, I'd like to take this one up

**Comment by JubayerJoy** [comment]
Hi @mohanarpit, If it's not worked by anyone, I want to work on it.
cheers.

**Comment by nidhi-nair** [comment]
Hey @bharat-patodi! I've assigned this issue to you, please make sure to read our [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md) before raising a PR!

**Comment by bharat-patodi** [comment]
Thanks @nidhi-nair

**Comment by yatinappsmith** [comment]
Verified as part of regression testing
