### ISSUE TITLE
[Feature] Trigger `onRowSelected` each time the row is clicked, even when it's unchanged

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#7449]
## Summary
 Trigger `onRowSelected` each time the row is clicked, even when it's unchanged

If the selected row index isn't updated the `onRowSelected` action is not triggered as a result in case the table has a single row data, it's not possible to trigger it. 

Also there could be instances where it's expected to trigger the action on click and not only when it's updated, for example refetching some data.

## Additional context
Quoting the op from discord:
I would say, a better way to achieve this is to fire onRowSelect when the table data loads and then the row gets selected according to the Default Row. Basically it means we need to fire the event regardless of whether a change is caused by the widget or a user action. Right after the data load the selection is NULL, and when the widget selects the default row (e.g. the 0th one) -- this is a change too. Firing the event on any user's click even without a change in selection is not a good idea

**Comment by Nikhil-Nandagopal** [comment]
I think this is related to #2639 The user doesn't want to run the action every time it's clicked, they want to run it every time it's changed regardless of user input
