### ISSUE TITLE
[BUG] Tab deletion is triggered while adding a tab

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#745]
Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Go to a page and add 3 tabs
2. Copy the 3rd tab and paste - that's create tab 4
3. Go to tab 4 and click on edit --> Add a tab --> Tab is added but there is message on the top right 'Tab 1 deleted' , 'tab 2 deleted'
Issue1 : There is no deletion operation which is triggered by user. 
Attachment: https://drive.google.com/drive/folders/13YyzytMKeUjjBa8MfX_d6JWwM5YI_G4K?usp=sharing

Issue 2: After performing too many operations on tabs, screen freezes. 
Attachment: https://drive.google.com/drive/folders/1ZawYxy4NbVOXpJR3MMvWbW3w1g77DWer?usp=sharing

**Comment by riodeuno** [comment]
We've updated how the tabs widget works.
@vivekverma2312 please verify if this issue still exists.

**Comment by vivekverma2312** [comment]
@riodeuno Verified using the given steps to replicate but could not find the issue, it's working fine.
Not able to access attachments for further details.
