### ISSUE TITLE
[Feature] Option to disable sorting for a table widget column

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#7450]
## Summary
Option to disable sorting for a table widget column

## Additional Context
On sort the selected row state is lost

**Comment by Nikhil-Nandagopal** [comment]
The solution should be to not lose selected row state not to disable sorting right? @rishabhsaxena

**Comment by rishabhsaxena** [comment]
> The solution should be to not lose selected row state not to disable sorting right? @rishabhsaxena
Actually, I wasn't sure if it makes sense to keep the selected index same as the previously selected one after sorting. Or if resetting on sorting is a feature.

**Comment by somangshu** [comment]
#5640 already addressing this. Can we close this?
