### ISSUE TITLE
[Feature] Set `modifiedBy` in application during create, clone, duplicate and import

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#7451]
## Summary

We need to set `modifiedBy` attribute of application to current user when they create, duplicate, clone or import an application.

## Motivation
In order to show last updated by information of an application in user home page, we need this information to be set when an application is created.

## Additional Context
N/A

**Comment by RakshaKShetty** [comment]
This is a backend change we need UI for testing this issue
