### ISSUE TITLE
[Feature] Ability to dock/pin the widget property pane to the right side of the editor

### ISSUE THREAD

**Issue by t7c8** [appsmithorg/appsmith#7453]
## Summary

A 📌  button in the top bar of the widget property pane which, when clicked, "docks" / "pins" it to the right side of the editor. Once the pane has been pinned, clicking on any widget will show its property pane expanded to the full page height and increased to 300-400 pixels in width. I've mocked out part of my idea below:

![Screen Shot 2021-09-14 at 5 55 21 PM](https://user-images.githubusercontent.com/90735788/133354150-c518c539-58e6-4f2c-ac46-1c3ad2557ae5.png)

Unpinning the widget property pane would return to its normal, floating, following and smaller state. 

## Motivation

When I edit properties of one widget after another, I find myself looking and re-looking for the gear icon to click. Then, I have to scroll down in each pane to the field I'm looking for.  Opening and re-opening the widget's property pane gets tiring, especially with widgets that have obscured gear icons. 

## Additional Context

This feature could be tricky depending on the screen resolution. But I'd still take a 90%-of-the-way solution; it would save me a lot of clicking!

**Comment by t7c8** [comment]
I did some more digging and, if I'm not mistaken, it looks like the page editor will [be redesigned in the near future](https://www.figma.com/file/xJOxQNXtoyveW4ZZ3kwrEN/Widget-Discovery?node-id=381%3A414893).

Has Appsmith already considered having docked/pinned panes in a right sidebar?

**Comment by Nikhil-Nandagopal** [comment]
@t7c8 thank you for the feature request. This is currently being worked on and is tracked here #6576 
Stay tuned for a few design updates! @aakashDesign can probably share a few early designs to get your feedback :)

**Comment by t7c8** [comment]
Thanks! I'll be happy to give input on designs
