### ISSUE TITLE
[BUG]When 'Defualt tab' doesn't have the right input - type is shown as 'undefined'. 

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#746]
Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate : In the default tab, type a tab name that doesn't have a matching tab name already. 
Issue 1: Error 'This value does not evaluate to type "undefined". Transform it using JS inside '{{ }}''
Attachment: Attachment: https://drive.google.com/drive/folders/1pkVkNRm7hMc6Dq4Xx_hxVnLIvPf4XNpl?usp=sharing

Issue 2: While deleting a tab (which has type undefined):

<img width="1792" alt="Screen Shot 2020-09-25 at 7 45 49 PM" src="https://user-images.githubusercontent.com/49346036/94278462-7605e180-ff68-11ea-9c9c-7d9c9452227e.png">

**Comment by riodeuno** [comment]
Tabs widget have changed in their functionality since this issue was raised.
@vivekverma2312 please verify if this issue still exists.
@marks0351 Please weigh in on this.

**Comment by vivekverma2312** [comment]
@riodeuno I can repro issue1 -> If Default tab name do not have matching tab then `This value does not evaluate to type "undefined". Transform it using JS inside '{{ }}'`  error is displayed in expected pane.

Not able to repro issue2, it's working fine.

<img width="952" alt="Screenshot 2021-06-07 at 4 45 58 PM" src="https://user-images.githubusercontent.com/83569920/121010925-a2d6ed80-c7b3-11eb-8f8d-1892beb32056.png">

**Comment by riodeuno** [comment]
<img width="1090" alt="Screenshot 2021-08-31 at 12 09 02 PM" src="https://user-images.githubusercontent.com/103687/131454326-26840471-20bb-4af2-9457-9e6d5569d608.png">

@vivekverma2312 This scenario no longer shows "undefined", instead it expects a "Tab Name". 
We will be picking up a more comprehensive validation messages update in this issue: #5840
