### ISSUE TITLE
Datatypes in request payload is being changed

### ISSUE THREAD

**Issue by vasani-arpit** [appsmithorg/appsmith#7462]
## Description

appsmith is changing the datatype of json payload before sending it to server. 

![image](https://user-images.githubusercontent.com/6497827/133378623-4f95485d-43ea-4e6b-a976-0275773970dd.png)

have a look at ```"phone_number": {{phone_number.text}},``` in the above screenshot. evaluated value says it will be sent as string. but when actual operation happens it converts it to numbers. I have also tried ```"phone_number": "{{phone_number.text}}",```. I have also tried ```"phone_number": {{`"${phone_number.text}"`}},```

the API which I am calling is facebook's so I don't have control over their code or server. 

#### My Take on this
It should take textbox as string by default. if a developer/user wants to send a value as Number then he/she can always convert it before sending. 

### Steps to reproduce the behavior:

Add steps to reproduce this behavior, include console / network logs & screenshots

1. take a Input box in canvas
2. take the value of that input box and send to an API in body as JSON
3. Input numbers in input box
4. Send the request and see what is sending to the server

### Expected behavior
Appsmith should send what is being shown in the evaluated value tooltip.

### Actual behavior 
If a string has a digits in it then appsmith is changing that property's value to Number data type.

### Important Details

- Version: Cloud
- OS: Windows
- Browser: chrome
- Environment: production

**Comment by Nikhil-Nandagopal** [comment]
@vasani-arpit great catch here this is indeed strange. @nidhi-nair @trishaanand can you comment here?

**Comment by nidhi-nair** [comment]
Seems like a smart substitution related issue, the values are getting interpretted based on our rules for parsing the data. @trishaanand do we want to disable this for REST APIs?

**Comment by rubabuddin** [comment]
is there a workaround for this issue?

**Comment by vasani-arpit** [comment]
@rubabuddin If the server is in your control then you edit it to accept datatype which appsmith sends. or you can send everything as string using `JSON.stringify()` and do a `JSON.parse()` at the server end. 

you can also try adding " before {{ and after }}. maybe convert your variable to string forcefully using .toString() method.

**Comment by Nikhil-Nandagopal** [comment]
@rubabuddin you can try turning smart substitution off in the query settings

**Comment by ame-appsmith** [comment]
[Another user](https://community.appsmith.com/t/passing-only-numbers-into-a-string-field-actually-sends-a-number-to-the-api-instead-of-a-number-string/1315)  reported this issue.

**Comment by pranavkanade** [comment]
Workaround - https://community.appsmith.com/t/passing-only-numbers-into-a-string-field-actually-sends-a-number-to-the-api-instead-of-a-number-string/1315/4?u=pranav
