### ISSUE TITLE
[Bug] Minor issues with welcome screen

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#7466]
## Description

After installing Appsmith, the welcome screen seen by users needs a few minor improvements

- [x] UI for the dropdown melds with the background white. We should create a distinction. 
- [ ] On pressing tab on the keyboard, the selection doesn't go from password input to the profession dropdown. This is irritating.
- [x] Appsmith logo is not centered in the form. Is this intentional?
- [x] Default query for mock Postgres DB should be changed. It doesn't work.
- [x] Can improve the copy on the welcome screen
- [x] Once the app is deployed for the first time, in the view mode the user can see a notification on the comment icon. On first click, it throws an error. Must be fixed on priority because it's a first impression for the user.
- [ ] This is more of a question: Are all the fields in the welcome page mandatory? Should we reduce the number of mandatory inputs that the user needs to provide?
- [x] The “Get Started” button is un-clickable until the Confetti is completely gone.
- [x] There’s a scrollbar that shows up while the Confetti is playing (probably only when an external mouse is connected, but still).

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by sharat87** [comment]
Video for issues with Confetti:

https://user-images.githubusercontent.com/120119/133407940-5665a80f-add1-4c02-a595-ecfaca9524e0.mov

**Comment by sbalaji1192** [comment]
Have extracted bugs that require quick fixes into #7503 and marked them.

**Comment by sbalaji1192** [comment]
@mohanarpit WRT, `Once the app is deployed for the first time, in the view mode the user can see a notification on the comment icon. On first click, it throws an error. Must be fixed on priority because it's a first impression for the user.`.
We show the unread comments indication for feature discovery purpose. (Not getting any error when i'm clicking the icon, Just asks me to setup live comments.)

**Comment by sbalaji1192** [comment]
Create https://github.com/appsmithorg/appsmith/issues/7509 for `Default query for mock Postgres DB should be changed. It doesn't work.`

**Comment by sbalaji1192** [comment]
created https://github.com/appsmithorg/appsmith/issues/7914 from `On pressing tab on the keyboard, the selection doesn't go from password input to the profession dropdown. This is irritating.`
