### ISSUE TITLE
[Bug] 2 scroll bars are present when user deploys app and going into comment mode toggles between one and two scrolls

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7471]
## Description
2 page scroll bars are present when user deploy app and going into comment mode toggles between one and two scroll bars

### Steps to reproduce the behaviour:
1. Deploy a new app with or without widgets. Observe 2 scrolls on the screen
2. Go to Comment mode and observe the extra scroll vanish and toggle between 1 and 2 scroll when dropping comments on screen

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e45cd7f5915540778f3b460d532243cb-00001.gif)](https://www.loom.com/share/e45cd7f5915540778f3b460d532243cb)

**Comment by J-Ankit2020** [comment]
Assign this to me

**Comment by ramsaptami** [comment]
It's your @J-Ankit2020 

Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by somangshu** [comment]
Greetings @J-Ankit2020, thanks for showing interest 🎉 , Seems like this issues is a but more involved, Please let us know if you need help here!

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by hiteshjoshi** [comment]
@ramsaptami I can no longer reproduce this. Is this still happening?

**Comment by ramsaptami** [comment]
The issue is no longer occurring hence closing this issue.
