### ISSUE TITLE
[Bug] AWS AMI fails to start

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#7473]
When creating an instance via AWS AMI, we get the following error:

```
Generating the configuration files from the templates
/tmp/tmp.h0OE6ncCmP/docker.env.sh: line 9: $5: unbound variable
```

This is because the `docker.env.sh` accepts _five_ arguments, and looks for a `$5` at https://github.com/appsmithorg/appsmith/blob/851abd5a06198f1cf9dfa53f5ca8ddbae260d09f/deploy/template/docker.env.sh#L9, but the AMI's start script passes only _four_ arguments to this script at https://github.com/appsmithorg/appsmith/blob/851abd5a06198f1cf9dfa53f5ca8ddbae260d09f/deploy/aws_ami/first-time-setup.sh#L115. The missing one is the first argument, the `$mongo_database`.

**Comment by nicolasmoreira** [comment]
Same issue here!

**Comment by nicolasmoreira** [comment]
Hey Appsmith team!, do you want to fix this AMI? thanks, cc @sharat87

**Comment by sharat87** [comment]
Hey @nicolasmoreira, the AMI was fixed and approved over the weekend. :tada:

Can you try again now please? If you face any problems, please let us know :)
