### ISSUE TITLE
[Feature] Disable "select all" in multiselect

### ISSUE THREAD

**Issue by birrin-lgtm** [appsmithorg/appsmith#7487]
## Summary

Currently, the multiselect widget allows users to select all options. A toggle in the widget's property editor to enable or disable the "select all" control will help prevent mis-clicks.

## Motivation

In one of my dropdowns, I have over 1300 options. I don't want users to be able to select them all.

**Comment by areyabhishek** [comment]
Thank you for the feature request. Quick question, have you found it easy to misclick the select all option?

**Comment by birrin-lgtm** [comment]
I haven't misclicked yet, but I definitely don't want my users to click it by accident. For reference, the form POSTs to API that will automatically create new entries in a table. I can code a restriction around that in the API (or in appsmith) but I'd just prefer to hide it at the UI level
