### ISSUE TITLE
[BUG] Issues while performing actions on Home Page

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#749]
Attachment : https://drive.google.com/drive/folders/1vFgWznBzwZEXRBxaFXYnUZ1AcBjux_DM?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Issue 1: Go to edit mode --> On the left side, click on Delete against Home Page.
Actual Result : Cannot Delete Home Page.
Expected Result:  No option to delete Homepage.

Issue 2: When there is just 1 page available (Home Page), try clicking on 'Move to Page'
Actual Result : Broken UI.
expected Result: Proper UI.

**Comment by Nikhil-Nandagopal** [comment]
Let's add the text "No Pages" when there are no pages that the user can move the action to

**Comment by A-Scratchy** [comment]
Is this up for grabs?

**Comment by Nikhil-Nandagopal** [comment]
@A-Scratchy yes it is! Go for it

**Comment by prapullac** [comment]
Verified the issue and works as expected
