### ISSUE TITLE
[Bug]-[200]:The CRUD operation is failing in snowflake datasource

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7493]
## Description

[What happened]When there are 2 columns in the table and the user perform the crud operation then the insert, delete and update operations are failing 

### Steps to reproduce the behaviour:

![image](https://user-images.githubusercontent.com/45958978/133553110-a07f6672-9ab6-47f8-b065-0dd8e5caeda9.png)

### Important Details

- Version: [Cloud ]
- OS: [MacOS]
- Browser [ chrome]
- Environment  release

**Comment by abhvsn** [comment]
@RakshaKShetty can we check if this is resolved in release environment?

**Comment by abhvsn** [comment]
@RakshaKShetty can we please check if this has been resolved?

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.5|

**Comment by abhvsn** [comment]
@RakshaKShetty can you please check this once more as we have updated the templates to include the JSON forms

**Comment by abhvsn** [comment]
Closing this as haven't seen any activity recently, please reopen if this is still pending
