### ISSUE TITLE
[BUG] Entity Explorer infinite Re-renders

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#750]
## Description
When deployed App is lying idle, the web app is consistently sharing information to the sentry. 

`1API -> 60KB -> 300ms (approx start to finish per api)`.

If the active tab is app than it shares information quickly but on non-active tab it does shares but a bit slowly.

[Video In Action](https://drive.google.com/file/d/14U_3mMCcCrBL8xhDJqkdWT24kmqgGzHw/view)

[AppSmith App URL](https://app.appsmith.com/applications/5f68ab257f2d33301e7bd48a/pages/5f68ab257f2d33301e7bd48c)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno after debugging it looks like the entity explorer is going into an infinite set of re-renders for this application

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #1143
