### ISSUE TITLE
[Bug] Dependant references inside `[ ]` are not extracted correctly 

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#7508]
## Description

I use IIFEs a lot. And I have seen them misbehave sometimes, I posted #6876 some time ago but the evidence was not hard and fast. I have now found a case where this problem was easy to isolate.

The demo app I'm including mimics the behaviour of getting data from a data source and populating a Select with the IDs of a list of objects as values.

`Select.selectedOptionValue` is then used to get other data from the dataset.

When used like this it looks like the IIFE isn't called when the option changes. However an expression using selectedOptionValue works fine. The IIFE is correct as I can get it to execute _once_ by editing the code to make it be re-evaluated.

This becomes a problem when you have code less trivial than in this example, where you need an IIFE to do more complex stuff.

### Steps to reproduce the behaviour:

Here's a short [demo vid of the bug](https://user-images.githubusercontent.com/142613/133566827-edad961b-8a17-4fdd-b410-694c7dacaba9.mp4).

Install the [IIFE bug demo app](https://github.com/appsmithorg/appsmith/files/7175570/IIFE.bug.demo.txt). (Change the extension to .json!)

Select an item. The lookup value is shown in `SelectedValueExpr` but not in `SelectedValueIIFE`.

Run the app in Edit mode. Select an item. Edit the JS in the Text field of `SelectedValueIIFE` to generate a parse error. Restore the code to its original. The IIFE executes and displays the lookup value. 

### Important Details

- Version: Cloud
- OS: Linux Mint 19
- Browser: FireFox
- Environment: production

**Comment by Nikhil-Nandagopal** [comment]
@zzgvh  Thank you for finding and reporting this. Your feedback and detailed reports are truly incredible and we really appreciate all the effort you put into helping us make appsmith a better product.

**Comment by Nikhil-Nandagopal** [comment]
I can easily reproduce this issue. @hetunandu @ApekshaBhosale @ajinkyakulkarni  can we look into this?

**Comment by Nikhil-Nandagopal** [comment]
Quick steps to repro
Drag an Input
Drag a text widget bind the snippet inside it
`{{{
		A: 1,
		B: 2
	}[Input1.text]
}}
`
Drag another text widget bind the snippet inside it
`{{(function(){
	const map = {
		A: 1,
		B: 2
	};
	return map[Input1.text];
})()}}
`
Change the text in the Input from A -> B
You'll see only one of the Text widgets are updated

**Comment by zzgvh** [comment]
Glad to help! You're such an awesome team, making a kind of product that I really like and enjoy working with. Open source to boot! :rocket:

**Comment by hetunandu** [comment]
Truly detailed and on point bug reproduction. I'll get this fixed ASAP @zzgvh

**Comment by hetunandu** [comment]
@zzgvh on investigation I found that this is not to do with IIFE but they way our dependencies are extracted for a code block. We use a very crude form of string search via regex to find references to other entities and that is breaking in this particular example:
```
(
function getProp() {
	const lookup = { 1: "First item prop", 2: "Second item prop", 3: "Third item prop" };
	
  const prop = lookup[Select.selectedOptionValue];
  return prop;
}
)()
```

Here we are not able to get `Select.selectedOptionValue` as a dependency which is why it is not updating when `Select.selectedOptionValue` updates. 

You could also see this if you just modify the function to something like this or similar
```
(
function getProp() {
	return { 1: "First item prop", 2: "Second item prop", 3: "Third item prop" }[Select.selectedOptionValue];
}
)()
```
and text field will work correctly.

**Comment by hetunandu** [comment]
I think this should be fixed when we implement #2435

**Comment by zzgvh** [comment]
Ok, cool! And good to know there is a workaround for now.

**Comment by hetunandu** [comment]
closing in favour of #2435
