### ISSUE TITLE
[Bug]Default select query in mock postrgres DB `Users` is not working 

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#7509]
## Description

refer -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5009a63e55d447d1aad1b1c377c17584-00001.gif)](https://www.loom.com/share/5009a63e55d447d1aad1b1c377c17584)

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Add an `Users` Postgres mock Db.
2. create a query and choose default select template.
3. run the query and observe the error.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign @arunvjn we should kill this query template and add the snippets CTA prominently here
