### ISSUE TITLE
[Task] Avoid Adding `px` while using theme object values

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#7511]
A small suggestion that might help to avoid mapping line-height or similar values of `theme object` in the future.

## Problem

To consume theme typography for headings and avoid mapping each style i.e., Avoiding this

```
font-weight: ${(props) => props.theme.typography.h1.fontWeight};
font-size: ${(props) => props.theme.typography.h1.fontSize}px;
line-height: ${(props) => props.theme.typography.h1.lineHeight}px;
letter-spacing: ${(props) => props.theme.typography.h1.letterSpacing};
```

and using this instead

```
const Heading = styled.div`
  ${(props) => ({ ...props.theme.typography.h1 })};
`;
```

The issue with this method is that as line-height value can be either number or px and unfortunately it gets converted to number whereas our value in theme object is intended to be pixel values

```
h1: {
      fontSize: 20,
      lineHeight: 27, // this is "27px" and not actually 27
      letterSpacing: -0.204,
      fontWeight: 500,
    },
```

## Solution

Writing theme value in pixels for this kind of property will resolve this issue.

```
h1: {
      fontSize: 20,
      lineHeight: "27px", // <--- this resolves the issue
      letterSpacing: -0.204,
      fontWeight: 500,
    },
```

File to be changed - https://github.com/appsmithorg/appsmith/blob/release/app/client/src/constants/DefaultTheme.tsx

**Comment by Dexters-Hub** [comment]
hey @Rishabh-Rathod can i work on this?

**Comment by Rishabh-Rathod** [comment]
> hey @Rishabh-Rathod can i work on this?

Greetings @Dexters-Hub, thanks for showing interest 🎉 , This is all yours. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate it if you can open a PR within the next 4 days.

**Comment by hunjunChoi** [comment]
Hi @Rishabh-Rathod, it seems the issue has been left open for some time after the initial assignment. May I work on this issue? Thanks.

**Comment by Rishabh-Rathod** [comment]
Sure @hunjunChoi. Go Head.

**Comment by hunjunChoi** [comment]
Unassigned myself due to incompetence

**Comment by tauantcamargo** [comment]
can i get it? @Rishabh-Rathod

**Comment by beheradibas** [comment]
Hey @Rishabh-Rathod , I would like to contribute to this.

I would like to know which properties apart form "lineHeight" needs this change?

Is this required for everything that takes px as default unit ? For example : font-Weight wont require a px but heights will require.

**Comment by Hongkai-Zhai** [comment]
Hey @Rishabh-Rathod can I get this issue?

**Comment by Rishabh-Rathod** [comment]
We are not planning to work on this anymore. Sorry, for the confusion. 

Other good first issues link : https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22
