### ISSUE TITLE
[Bug] Autosuggestion are not working as expected 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7514]
Steps to reproduce:
1) Add a widget
2) Add an API / Query / Js object
3) Bind one of the above
and observe

Observation:
The best match and search are not be displayed appropriately  and suggestions are displayed only on using / cmd

Expectation:
icon must be displayed appropriately and be displayed as the best Match.

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e110e1af0bd84197a100c4dd8585a6d0-00001.gif)](https://www.loom.com/share/e110e1af0bd84197a100c4dd8585a6d0)

![Screenshot 2021-09-16 at 2 14 01 PM](https://user-images.githubusercontent.com/71753653/133581879-a3e37336-cb00-4438-a0df-b930df54f0bb.png)

**Comment by prapullc** [comment]
Closing the issue as this is currently not applicable
