### ISSUE TITLE
[Bug] Clicking on ? icon in property pane doesn't show widget related information 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7515]
## Description
Release - It is observed that for any widgets clicking on ? icon in the property doesn't show the widget related information. whereas in product appropriate information is displayed 

Also, for some of the new widgets are not displayed in the documentation pop up in both release and prod
widgets like - Audio recorder, Checkbox and few more

**Expected result:**
Clicking on ? icon in property pane should display widget related information in the documentation pop up 

### Steps to reproduce the behaviour:

1. Launch Appsmith app in the release environment 
2. Drag and drop any widgets - button/form
3. open property pane and click on ? icon and observe

**Videolink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9c2cbd431a7b4cc1a6db643ec617d5bf-00001.gif)](https://www.loom.com/share/9c2cbd431a7b4cc1a6db643ec617d5bf)

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [release]

**Comment by riodeuno** [comment]
@YogeshJayaseelan This issue does not exist anymore. Please review and reopen if needed.
