### ISSUE TITLE
[Bug]The scrollbar is broken in canvas

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7526]
## Description

[What happened]Table widget on top of the canvas doesn't display with a header as the scroll bar of the canvas is not working

### Steps to reproduce the behaviour:

1. Add a table widget on top of the canvas
2. add few more widgets at the bottom 
3. Now navigate between page 
4. and come back to the same page by clicking on any of the widget names
5. the header of the table is not displayed
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/755490198ebe4d099a47203d3e45e636-00001.gif)](https://www.loom.com/share/755490198ebe4d099a47203d3e45e636)
![image](https://user-images.githubusercontent.com/45958978/133596393-7b2fad20-042d-4594-b9d6-5e735beca26e.png)

### Important Details

- Version: [Cloud 
- OS: MacOSX]
- Browser Firefox,
- Environment release

**Comment by marks0351** [comment]
flashElementsById is the reason. scrollIntoView is forcing it to center to the page moving it out of its scroll top in some cases. @jsartisan  did we change this or it was this way all along?
