### ISSUE TITLE
[BUG]Did not observe any item or terminal signal within 10000ms in 'onErrorResume' (and no fallback has been configured)

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#753]
Run a query:
SELECT A.name AS CustomerName1, B.name AS CustomerName2, A.id
FROM users A, users B
WHERE A.id <> B.id
AND A.gender = B.gender
ORDER BY A.avatar;

Issue : Database becomes extremely slow and finally throws an error.

<img width="1104" alt="Screen Shot 2020-09-26 at 2 06 41 AM" src="https://user-images.githubusercontent.com/49346036/94313888-2ab9f600-ff9d-11ea-9f31-8a3abed05441.png">

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 this seems correct, the timeout for queries is set to 10s. Closing this
