### ISSUE TITLE
[Bug] Table column names and order gets reset sporadically

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#7540]
## Description
A user has been seeing their table columns names and order that is custom gets reset and all the changes need to be added again. This happens when the underlying data / datasource has changed

**Comment by Nikhil-Nandagopal** [comment]
Related to #4984. Can we please fix this on priority? Many users are facing this

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #4984
