### ISSUE TITLE
[Bug] Extra scroll is added to a page when property pane appears on the extreme right and JS object is selected from autocomplete

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7548]
## Description
Extra scroll is added to a page when property pane appears on the extreme right and JS object is selected from autocomplete

### Steps to reproduce the behaviour:
1. Drag and drop a widget on the canvas such that property pane appears on the right most edge
2. Now try to type in a query on a JS field and use autocomplete to select object
3. Observe an extra scroll added onto the page on the right and bottom
4. Trying to scroll this moves the property pane itself

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/098f99bff32342d384cd1c11419cc76f-00001.gif)](https://www.loom.com/share/098f99bff32342d384cd1c11419cc76f)

**Comment by jsartisan** [comment]
Fixed with docked property pane.

**Comment by ramsaptami** [comment]
Reopening it since this hasn't been resolved by docking yet
https://www.loom.com/share/308f0553c66d45c38d6e5c99bdf62baf

**Comment by somangshu** [comment]
@ramsaptami the extra scroll you are seeing is on the property pane itself and not on the canvas, I would argue that this issue is actually resolve, Let us know what is your expectation here or close the issue

**Comment by ramsaptami** [comment]
This is one scenario where I've seen it happen but can replicate it consistently while I'm building an app hence overall this tends to happen more than once when building an app. The aim is to not have that jittery feeling. Our UX would be much better without that slight shift and back that you see in the video

**Comment by rohitagarwal88** [comment]
@ramsaptami : Can you please recheck the issue? I am unable to reproduce it.

**Comment by ramsaptami** [comment]
Closing the issue since property pane is now pinned
