### ISSUE TITLE
[Bug] Audio recorder widget styling property needs to be categorized under Styles not General

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7549]
## Description
Audio recorder widget styling property needs to be categorized under Styles not General as is present on other widgets

![image](https://user-images.githubusercontent.com/79509062/133629318-40e7c74e-2bd6-4182-941c-3100b76ffa13.png)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by ipankajchaudhary** [comment]
Can i work on this?

**Comment by ramsaptami** [comment]
Absolutely @ipankajchaudhary, it's all yours.

Please read the [Contributor's Guideline](https://github.com/appsmithorg/appsmith/blob/0619e3798f3edff10de450a0dc54afde84220352/CONTRIBUTING.md) before starting.

**Comment by ramsaptami** [comment]
Sorry @ipankajchaudhary, this issue is has fix on it's way. 

You could have a look at other issues tagged "[hacktoberfest](https://github.com/appsmithorg/appsmith/labels/hacktoberfest)"
