### ISSUE TITLE
[Task] TextInput Enhancement (components/ads/TextInput.tsx)

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#7553]
- [ ] Currently, the error message is absolute positioned which makes it difficult to align with other components.
> For eg:- A Fixed bottom padding needs to be given so that the error messages could be visible and not overlap with other UI below the text input.

- [ ] When `validator` returns `isValid` as `false`, `onChange` stops working which might not be the use-case every time.
disabling textChange if the value is inValid is not expected behavior.  

- [ ] Avoid Prop drilling `{...props}`.

- [ ] Add comments for each prop to explain its usage and caveats. This should be visible in autocomplete for the component consumers.
> common tasks which should be done for each component -

**Comment by nishihere19** [comment]
Can I work on this issue?

**Comment by Rishabh-Rathod** [comment]
Hey👋🏼 @nishihere19 , thanks for showing interest in this issue.

Unfortunately, this issue is yet in the discussion phase and hence not labeled as a Good First Issue. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22)

Looking forward to seeing your contributions :)
