### ISSUE TITLE
[Bug] Disabled button widget tooltips stay open

### ISSUE THREAD

**Issue by A-Crawley** [appsmithorg/appsmith#7554]
## Description

Tooltips on disabled buttons are not closing after the user has moved their cursor away from a button widget.

### Steps to reproduce the behaviour:

1. Create new page
2. Add button widget
3. Add tooltip
4. Disable button
5. Hover over button
6. Move cursor and tool tip remains

### Important Details

- Version: Cloud
- OS: Windows 10
- Browser: Chromium Edge
- Environment: N\A

**Comment by somangshu** [comment]
The original Issue stated a UX that was probably perceived wrongly. We should do the following
- [ ] The tooltip should be visible on the button upon hover even if the button is disabled. 
- [ ] The tooltip should not be visible if the cursor is not focusing on the button.

@techbhavin keeping this in the product backlog, Will bring it up in the project catchup


cc @Nikhil-Nandagopal @dilippitchika do you guys see any flaws in the above approach, will this be a bad UX for any user that might be looking at this like a feature

ref: this was reported by a [user](https://theappsmith.slack.com/archives/C02BQS5UL11/p1647873093666499)

**Comment by Tooluloope** [comment]
@somangshu I don't think the tooltip should be visible if the button is disabled

**Comment by somangshu** [comment]
Why do you say so, the user might want to show steps to make the button enabled, this is a valid use case @Tooluloope

**Comment by Tooluloope** [comment]
True, I just tried the default HTML behavior and it works as you mentioned
https://codepen.io/Ysaalexis20/pen/MWrbodw

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope great approach to validate the UX!

**Comment by btsgh** [comment]
Tested in Release - As per the above comments from Dev -
1. Tested for tooltip appearing on button disabling. It appears.
2. However, on deploy, though the tooltip appears when button is disabled, when the cursor is not focusing on the button, the tooltip still stays. It does not go away. Check the following video for the behaviour -
3. https://www.loom.com/share/2cbcb422825d46ab8b5fb86da9ac9e4d

**Comment by dilippitchika** [comment]
@wmdev0808 please check this. It's already in release now, could you act on it asap?

**Comment by wmdev0808** [comment]
> @wmdev0808 please check this. It's already in release now, could you act on it asap?

@dilippitchika , I've made the PR for the issue [here](https://github.com/appsmithorg/appsmith/pull/12372)
