### ISSUE TITLE
[Bug] Switch Widget Does not work

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#7563]
## Description

The isSwitchedOnProperty of the SwitchWidget does not work

### Steps to reproduce the behaviour:

1. Drag a switch
2. Drag a text box
3. Bind the text to Switch1.isSwitchedOn
4. Toggle the switch
5. There is no change to the text widget

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@vivekverma2312 @somangshu @yatinappsmith  how did an obvious case like this get missed for this widget? What does regression testing really mean for us today? How are there no automated test cases for obvious cases like these?

**Comment by vivekverma2312** [comment]
@Nikhil-Nandagopal Tested on both prod and release and it's working fine.
https://www.loom.com/share/9716661f5a824e68b48c9164e1176bd2

**Comment by Nikhil-Nandagopal** [comment]
@vivekverma2312 I'm not able to repro now. Let me find the scenario and get back
