### ISSUE TITLE
[Bug] Ctrl+Space and Space key press causes the autocomplete to blink in and out of view

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7564]
## Description
User on discord wrote in about **Ctrl+Space** key press causes the autocomplete to blink in and out of view without staying on screen. This even happens on key press of **Space** or **Shift+Space**.

Currently when user enters object name then the autocomplete opens up but once the autocomplete closes due to any close action (like Ctrl+Space or Esc key press) and then it does not stay open on screen rather blinks in and out of view on **Space** key press.
 
### Steps to reproduce the behaviour:
1. Go to JS object of any widget and type in an query name for example
2. Observe the autocomplete popup after typing 
3. Now press Ctrl+Space and observe the autocomplete window close
4. Any consequent key press of **Space** causes the autocomplete to blink in and out of view

Can we also wait for the user to complete pressing on backspace before displaying the autocomplete again? It's not a great experience when it keeps flashing during backspace.
 
### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3344ccbaaacf4ccfbd34992866af9066-00001.gif)](https://www.loom.com/share/3344ccbaaacf4ccfbd34992866af9066)

**Comment by TomerPacific** [comment]
Hi, I'd like to help out with this issue. Anything I should know before I start?
