### ISSUE TITLE
[Bug] "Cannot convert undefined or null to object" error on placing any widget on List widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7578]
### Steps to reproduce the behaviour:
1. Drag and drop list widget
2. Drag any other widget on List widget
3. Observe `Cannot convert undefined or null to object` error

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b30a0efad2694ce3a079f958ce42a21a-00001.gif)](https://www.loom.com/share/b30a0efad2694ce3a079f958ce42a21a)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by aswathkk** [comment]
@vivekverma2312 I'm unable to reproduce this issue now.
Can you confirm whether this issue still happens?

**Comment by Tooluloope** [comment]
I'm unable to reproduce this issue now.
