### ISSUE TITLE
Read Column from Google Sheets to be Populated in the Dropdown with search

### ISSUE THREAD

**Issue by Biju-Mathew** [appsmithorg/appsmith#7586]
## Summary

The Dropdown needs to read a column from Google Sheets and populate the same data in the Dropdown. A Method to read a column from google sheet when creating a API is not available and needs to be added. Using this way we can populate the dropdown field very easily. 

## Motivation

Since there is a huge data say about 1000 items to be shown in the Dropdown. When creating an array for 1000 items it does not work

## Additional Context

if the dropdown cannot show 1000 items a few can be shown and the rest can be found using a search function which is build in the dropdown

**Comment by Nikhil-Nandagopal** [comment]
Hi Biju, this is related to #7102 which is now fixed and will be available in our next release
