### ISSUE TITLE
[BUG] Default text isn't set for RichTextEditor in incognito.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#759]
## Description
Add RichTextEditor with default text, open the deployed app in `private` mode. The default text would be missing, now refresh the page, it would reappear like `rabbit from hat`.

### Steps to reproduce the behaviour:
1. Add RichTextEditor with default text.
2. Open the  deployed app in `private/incognito browser` mode.
3. The default text would be missing.
4. Refresh and default text will be present.

[Video In Action](https://drive.google.com/file/d/1f5dM1zJZRzv-wG_XJPDu3sfMrMWWK9bI/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by trdillon** [comment]
Is this issue still active? I was not able to replicate it in the current cloud version. I did receive the same CORS errors in private/incognito mode but they didn't prevent the text from being displayed so I'm not sure if they are related to this issue.

**Comment by Nikhil-Nandagopal** [comment]
@trdillon this does seem to be working. I'm closing this, thanks for letting us know :)
