### ISSUE TITLE
[Bug] onSubmit not triggered on Enter key  when dataType is number

### ISSUE THREAD

**Issue by andrewtk** [appsmithorg/appsmith#7593]
## Description
key Enter do not triggered at Input1 field when onChange and onSubmit triggers both exist and Data Type is a number

[What happened]
I want notice that after me store the value onTextChange {{storeValue('text', Input1.text)}}
﻿and rehydrate in the default text as {{appsmith.store.text}}
the onSubmit where I place {{selectQuery.run}} dosn't work. I mean after I put some number at the Input1 and press the Enter key - nothing happens. 
### Steps to reproduce the behaviour:

1.  create onTextChange {{storeValue('storedTrialOwnerId',ownerIdInput.text)}}
2.  Setup the Input1 dataType as a Number
3.  put at Default text {{appsmith.store.storedTrialOwnerId}}
4.   onSubmit place {{selectQuery.run}}
5.  deploy
6.  put number at the <ownerIdInput>
7.  press Enter
8.  nothing happens

 
Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to 'ownerIdInput' place some number
2. Click on 'Enter'
4. See nothing at the table

![image](https://user-images.githubusercontent.com/25726236/133903689-d01d9f9a-977f-49f3-9dc7-621c756a88f3.png)
![image](https://user-images.githubusercontent.com/25726236/133903871-6291efb2-8a30-4d9a-97a2-8d097f675cf8.png)

### Important Details

- Version: [Cloud / Self-Hosted vx.x] self-hosted
- OS: [e.g.MacOSX] Windows 10
- Browser [e.g. chrome, safari] Chrome
- Environment [production, release, deploy preview] production

**Comment by Nikhil-Nandagopal** [comment]
@andrewtk this seems to be working for me. The query is running. It is possible that the query is not receiving the correct data if you are rehydrating the input from the store. Any reason why you're doing this? The query should be able to directly reference the input
