### ISSUE TITLE
[BUG] Default Image is missing when image is specified as dynamic property.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#760]
## Description
Default Image is missing when image is specified as dynamic property.

[Video In Action](https://drive.google.com/file/d/13o1K7FQW2TjoH6vq58eWq71HXQJfE2pY/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by hetunandu** [comment]
**Solution:** Update the logic of the [background image](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/components/designSystems/appsmith/ImageComponent.tsx#L24) to handle for cases where `props.imageUrl` is `undefined`

>Need more guidance while working on a solution for this? Feel free to mention me in a comment on this issue and I'll be happy to help you out 😄

**Comment by visibleajay** [comment]
Hey Hetu, Checked it and found out that `src={this.props.imageUrl}` is null when a dynamic property is provided with no values attached to it as shown in the example.
If we could check and provide any non-zero value when `imageUrl` is empty than it would trigger the img `onError` and `onLoad` method which subsequently would updates the `imageError` var updating the background-image attached to the `StyledImage` Component.

I propose updating `src` with `{this.props?.imageUrl?.length > 0 ? this.props?.imageUrl : "default"}` to make it work in the above case. Would surely like to know your views on this.

**Comment by visibleajay** [comment]
Yes. The suggested one also worked. Please assign it to me.

Am using `@testing-library/react` and `jest` to write unit testcases.
