### ISSUE TITLE
[Bug] Error message is displayed on debugger but error is not present

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7615]
## Description
Error is displayed for linting but error message on debugger does not navigate to errors tab as is generally the case and no error is logged in the debugger.

### Steps to reproduce the behaviour:
1. Go to JS editor and type in any word to cause a lint error
2. Observe a parsing error displayed on the debugger - usual 'Debug' button is missing
3. Navigate to Errors tab and Logs and observe that no errors are logged

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy preview on test.appsmith.com (JS editor)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2c8081449e83406bad71b0257bd035e3-00001.gif)](https://www.loom.com/share/2c8081449e83406bad71b0257bd035e3)

**Comment by hiteshjoshi** [comment]
@akash-codemonk @hetunandu can any of you guys dig in and confirm if this is because of debugger or something else
