### ISSUE TITLE
[FEATURE] Run appsmith on custom port

### ISSUE THREAD

**Issue by deval-gaurav** [appsmithorg/appsmith#762]

**Comment by Nikhil-Nandagopal** [comment]
@deval-gaurav thank you for opening this. We'll try and get this prioritised soon

**Comment by ribab** [comment]
I think the best way to solve this would just be to add documentation on how people can set up their own `docker-compose.yml` file with their customizations

**Comment by Nikhil-Nandagopal** [comment]
@ribab thank you for the suggestion, we're going ahead with adding docs for this in this issue
#1900

**Comment by Nikhil-Nandagopal** [comment]
This has been added to the documentation
