### ISSUE TITLE
[Feature] Change Map Pin Colour on Map Widget

### ISSUE THREAD

**Issue by lahiruelectrily** [appsmithorg/appsmith#7620]
## Summary

Change Map Pin Colour in Map widget.

## Motivation

It is important to distinguish different locations (pins) of the maps with a different colour? Would be be nice to have a property in the Default Makers property.

## Additional Context

This is the about the Map widget.

**Comment by somangshu** [comment]
@lahiruelectrily thanks for the feature request 😄 , We will look into this soon and get it prioritised!

**Comment by lahiruelectrily** [comment]
Thanks

**Comment by somangshu** [comment]
@wmdev0808 Send the SVG over the DM, here is how it looks

<img width="412" alt="Screenshot 2021-10-08 at 11 32 51 AM" src="https://user-images.githubusercontent.com/11089579/136506112-50bd0c33-9deb-45d0-958d-052dfc4e1758.png">

**Comment by Nikhil-Nandagopal** [comment]
Hi @billyrudi 👋 we have a feature request for leaflet open here #5492

**Comment by Akash926988** [comment]
Hi @Nikhil-Nandagopal Is the feature Change Map pin color on Map widget working now?
Really need to incorporate this.

**Comment by somangshu** [comment]
@Akash926988 this is fixed and working now; To know more, checkout our [maps docs](https://docs.appsmith.com/reference/widgets/maps#widget-properties); See the default properties were you place you pins on the map, you can add the prop color to customize your pin
