### ISSUE TITLE
[Bug] Two scrolls are present on app card property

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7622]
## Description
Two scroll bars are present on app card property and only 1 of them scrolls through icon options while the other scroll moves but does not relate to any corresponding choices present on the property dropdown. It also vanishes when cursor is moved away from the card whereas the scroll for icon stays in place.

### Steps to reproduce the behaviour:
1. Go to app card and click on `...`. Scroll and observe the first scroll not perform any action and also disappear when the cursor is moved away.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy preview (7304)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bab4a080e5e0406b819d782d506cbc7e-00001.gif)](https://www.loom.com/share/bab4a080e5e0406b819d782d506cbc7e)

**Comment by albinAppsmith** [comment]
* Icons needs to be changed
* Delete option should be red

https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=79%3A340
