### ISSUE TITLE
[Bug] Not able to place any widget at the last grid (extreme right) inside modal widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7624]
### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Drag and drop a modal widget
2. Now drag another widget inside modal widget
3. Try to place at the extreme right side of the modal
4. Observe that widget can not be placed 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f178ffd2fe2d42bfa00dd981a49680a0-00001.gif)](https://www.loom.com/share/f178ffd2fe2d42bfa00dd981a49680a0)

**Comment by rahulramesha** [comment]
@vivekverma2312 this was fixed yesterday with modal resize, could you please verify

**Comment by rahulramesha** [comment]
Closing this, as it was verified
