### ISSUE TITLE
[Bug] User roles drop down button is not clearly visible on org members page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7626]
## Description
User roles drop down button is not clearly visible. Needs to be enlarged. 

### Steps to reproduce the behaviour:
1. Go to Members option in org settings and add members
2. Observe the dropdown icon is not very clear

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment:Deploy preview (7304)
 
![image](https://user-images.githubusercontent.com/79509062/133981039-2c4a6b60-52de-4083-875a-bdcc85bd34c1.png)

**Comment by albinAppsmith** [comment]
Li, Please take a look at below points

1. Dropdown icon next to developers is not visible
2. Invite user button, icon should be in left
3. Delete Icon replace with Remixicons
4. On hover, prevent changing icon color
