### ISSUE TITLE
[Bug] Refactor of widget name doesn't update in APIs

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#7627]
## Description
Widget name refactor doesn't update values in API pane

### Steps to reproduce the behaviour:
1. Create any widget Text1
2. create API and give key as [{{Text1.text}}](url)
3. Change Text1 to text_box
4. Observe API pane value remains as  [{{Text1.text}}]

https://user-images.githubusercontent.com/7846888/133982923-7f7766dd-39d6-406e-ba10-7a49b0582e0b.mov

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by prapullac** [comment]
on page refresh the name gets updated into the API pane however name does not get dynamically updated.
