### ISSUE TITLE
[Bug] After disabling quick dismiss “on close “ property do not work

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7628]
### Steps to reproduce the behaviour:

1. Drag and drop a Modal widget
2. Open property pane 
3. Disable Quick dismiss
4. Now add any action on "On Close" property
5. Observe that clicking on close icon do not perform on close action

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e1a393d0e0124d3285917dd5301f3ee4-00001.gif)](https://www.loom.com/share/e1a393d0e0124d3285917dd5301f3ee4)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
@vivekverma2312 why is this not verified yet?
