### ISSUE TITLE
[Bug] Deleting an extra row in the  Where clause the entire rows added gets deleted

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7630]
Steps to reproduce:
1) Authorize Google sheet
2) Add an API 
3) Select Fetch rows 
4) Add multiple rows in the Where clause
5) Navigate to the last row and click on Delete
and observe

Observation:
It is observed that all the extra rows gets delete with one click on delete and not a single row 

Expectation:
The respective rows with the delete button clicked must only be deleted 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7ff433e742e64a1e90586873fb47db24-00001.gif)](https://www.loom.com/share/7ff433e742e64a1e90586873fb47db24)

**Comment by prapullac** [comment]
@ayushpahwa : This is observed in Firestore as well

**Comment by ayushpahwa** [comment]
Reopening since this is still persisting
