### ISSUE TITLE
[Bug]Internal server error is displayed when user try to create a app using google sheet

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7634]
## Description

[What happened]When the user selects from the spreadsheet from google_sheet dropdown the error is displayed

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d3d3425877644672bdd381375c663e70-00001.gif)](https://www.loom.com/share/d3d3425877644672bdd381375c663e70)

### Important Details

- Version: [Cloud /]
- OS: MacOS
- Browser  chrome
- Environment release,

**Comment by nidhi-nair** [comment]
Fixed in #7637
