### ISSUE TITLE
[Bug] Selecting saved login credentials from browser causes a white box to appear around credentials

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7636]
## Description
Selecting saved login credentials from browser causes a white box to appear around credentials

### Steps to reproduce the behaviour:
1. Go to sign in page and enter credentials from browser saved details and press enter
2. Observe a white box appear over the email

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy Preview (6304)

![image](https://user-images.githubusercontent.com/79509062/133996935-976ae4c9-35d3-4533-a8e5-15500eb64748.png)

**Comment by albinAppsmith** [comment]
This was added to get rid of the yellowish auto fill color which browsers use by default.

**Comment by albinAppsmith** [comment]
This was fixed
