### ISSUE TITLE
[BUG] Files selected in the Filepicker don't get copied with Page cloning

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#764]
Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate: 
1. Select 'Filepicker' and select a file (Page 1)
2. Clone Page 1  --> Page 1 copy

Actual Result: Selected file in Filepicker isn't present on Filepicker in Page 1 copy

Attachment: https://drive.google.com/drive/folders/1UQZ8-eT50IXsNu6F8nBfCWTVuEqYYnW9?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 copy of any kind won't copy the user inputs to any widget so closing this. 
(Table filters / input / dropdown selection / files picked)
