### ISSUE TITLE
[Bug] Row offset error for existing queries created by generate page feature

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7640]
## Description
Row offset error on existing queries created while using generate page feature

### Steps to reproduce the behaviour:
1. Go to an existing query that was created via generate page feature and click 'Run'
2. Observe row offset error on hitting 'Run'

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/134003973-2a98fdd2-ad9c-46b7-aebb-cba621ccfa15.png)

**Comment by nidhi-nair** [comment]
@ramsaptami could you please share an app that has this reproduction? I'm unable to reproduce this

**Comment by ramsaptami** [comment]
@nidhi-nair think either #7688 or #7815 has fixed this. Can't see this error anymore on my end either.
