### ISSUE TITLE
[Bug] Where Clause data is stored On changing the Query Format--> Query Rows to Query Range

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7644]
Steps to reproduce:
1) Add a query to Google sheet 
2) Select the Query Type as Fetch sheet Rows
3) Select the Query Format--> Query Rows
4) Add required detail 
5) Add a where condition
6) Now change the  Query Format--> Query Range
7) Change the URL 
and click on Run 

Observation :
The where clause is saved the error is displayed to a user 

Expectation :
It is expected that the where clause must be cleared  when the user changes the Query Format as Query Rows have where clause and Query Range does not have Where clause
![Screenshot 2021-09-20 at 7 03 14 PM](https://user-images.githubusercontent.com/71753653/134011242-dc55c186-ae50-4673-b57e-242d4d4d7591.png)

**Comment by trishaanand** [comment]
Closing this since where clause is seen now for both query rows and query range.
