### ISSUE TITLE
[BUG] Special Character is not accepted in the page name but results into empty space (1st character).

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#765]
Attachment - https://drive.google.com/drive/folders/1dK1x9FR-RfkgD0WQoUZhiHINkFoS-A7G?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Go to 'Edit App'
2. Go to page name --> Edit Name
3. Now type a special character or . (full stop) or , (comma)

Expected Result: If it's not accepted, cursor shouldn't move.
Actual Result: Since, characters mentioned in step 3 are not accepted, they result into empty spaces.
Note: Only results into an empty space while typing the 1st character, works fine 2nd character onwards.

**Comment by visibleajay** [comment]
@riodeuno Unable to reproduce it on cloud. @Saket2 Is it still happening?

**Comment by Saket2** [comment]
@riodeuno , @visibleajay  - Replicated it just now.

**Comment by visibleajay** [comment]
@Saket2 Adds a single space when no space is present on pressing of special char. Then works as expected. Thank You for the time.

**Comment by Saket2** [comment]
@visibleajay Edited the bug title and bug description.

**Comment by nuwan94** [comment]
I would like to work on this issue.

**Comment by Nikhil-Nandagopal** [comment]
@nuwan94 go for it! I've assigned you to the issue.

**Comment by prapullac** [comment]
Verified the issue as it is working as expected
