### ISSUE TITLE
[Bug] Table widget doesn't show anything if the value is 0

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#7658]
## Description
If the value of a particular entry in the table widget is 0, it doesn't get visualized.

[What happened]
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f9c4299e3f3b4c609e9aab81cd8b41e1-00001.gif)](https://www.loom.com/share/f9c4299e3f3b4c609e9aab81cd8b41e1)

### Steps to reproduce the behaviour:

1. Drag and drop the Table widget 
2. To the Table data, add a field with value 0
3. Check the resulting table
4. Notice that there is an empty cell

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by zzgvh** [comment]
I found a workaround: In the column control for a field, in the Computed value field add `||"0"` like : `{{currentRow.prune||"0"}}`

**Comment by beheradibas** [comment]
I want to work on this if this issue still persists.

**Comment by ohansFavour** [comment]
Hi @beheradibas , I just confirmed that this issue still exists. Yes, you can go for it!. I will go ahead and assign it to you.
Kindly go through the [contribution guidelines](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md) if you've not done that already. Cheers!

**Comment by sbalaji1192** [comment]
@vibhandikyash @somangshu 
As per my RCA, issue is originating from `renderCell` function on `appsmith/app/client/src/widgets/TableWidget/component/TableUtilities.tsx` file. Specifically from L172. We're checking whether the value exist with an expression that evaluates to false when value is `0`.
