### ISSUE TITLE
[BUG] App crashing while using Date.now().toString() for Chart Widget. 

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#766]
### Steps to reproduce the behaviour:
1. Add a chart widget.
2. Edit the default `x` key, to provide dynamic value. 
3. Provide Date.now().toString by `typing`.
4. See `error`

[Video In Action](https://drive.google.com/file/d/1Yo3pFcrFVPjcWKqL78eUx0UwpWW6kOxw/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
This is now closed :)
