### ISSUE TITLE
[Bug]  By default the Evaluated value is duplicated  for Border radius and Border width 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7661]
## Description
Release - Most of the Widget - It is observed that by default the evaluated value is duplicated when the value is 0 

[What happened]
Evaluated value should not duplicated when the value is 0

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the releas environment 
2. Drag and drop container widget 
3. Open property pane 
4. Click on Border width and border radius and observe

### Important Details

- Version: [11.3]
- OS: [MacOS Big Sur]
- Browser [chrome, safari]
- Environment [release]

<img width="1680" alt="Screenshot 2021-09-21 at 1 50 24 PM" src="https://user-images.githubusercontent.com/35128442/134137610-77f56f40-2089-4829-bb6b-5bf5cf69d556.png">

**Comment by somangshu** [comment]
@jsartisan how is this a good first, Do we know what is the possible fix?

**Comment by SatishGandham** [comment]
This could be due to evaluations, not a good first issue.

**Comment by jsartisan** [comment]
I thought it's a validation issue. So added the good first label to it. my bad.

**Comment by Nikhil-Nandagopal** [comment]
No longer valid
