### ISSUE TITLE
[Bug] Modal titles are not centre aligned

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7664]
## Description
Import application title on Import application pop-up is misaligned

### Steps to reproduce the behaviour:
1. Go to app card and click on `...` and choose "Import Application"
2. Observe the title off to the left from center - should be centered

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/134139514-6a2cd3df-7f0e-4b1d-9945-d4b7952d4feb.png)

**Comment by pranavkanade** [comment]
This can be observed on every modal using `DialogComponent`

**Comment by JubayerJoy** [comment]
Hi @ramsaptami, I would love to work on this.
Cheers.

**Comment by DevrajDC** [comment]
Hi, i would like to work on this issue. Please assign it to me! :)

**Comment by nidhi-nair** [comment]
Please go ahead @JubayerJoy! I've assigned this PR to you, please make sure to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) before starting to work on the issue. 😄

**Comment by hiteshjoshi** [comment]
Hi Folks! This issue is taken care already early today morning by previous assignee.
