### ISSUE TITLE
[Bug] Imported app throws a missing plugin ID error during duplication

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7672]
## Description
Imported application displays a missing plugin ID error during duplication.
Caveat: Bug isn't consistently reproducible. The app attached here in the zip folder does throw this error

### Steps to reproduce the behaviour:
1. Import an application
2. Duplicate the app and observe the missing plugin ID error 

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[Linting Testing (1).zip](https://github.com/appsmithorg/appsmith/files/7202074/Linting.Testing.1.zip)
![image](https://user-images.githubusercontent.com/79509062/134145473-647f95b3-6624-4dd3-8a6b-8d99cd22d625.png)

**Comment by abhvsn** [comment]
Now that we have jsActionCollection as a part of import-export this should be resolved. 
@ramsaptami can you please re-verify this once

**Comment by ramsaptami** [comment]
It's working now @abhvsn

**Comment by abhvsn** [comment]
Closing this, working as expected
