### ISSUE TITLE
[Bug]All the Pages are not displayed in the public mode when the application is deployed with hidden pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7677]
## Description All the Pages are not displayed in the public mode when the application is deployed with hidden pages

[What happened]when an application has a hidden page on the deployment of the application the app is made public. it is observed that on sharing the URL only the hidden page viewed by the user

### Steps to reproduce the behaviour:

1. Add At least 3 pages 
2. Now make any one page as hidden 
3. click on deploy from the hidden page
4. Now make an app public now open the link in a private window
5. Only hidden page is displayed the other pages are not displayed

expected behaviour:
Other than the hidden page all the other page should be Seen in the view mode
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/749c76b474a347aab7067e360424da70-00001.gif)](https://www.loom.com/share/749c76b474a347aab7067e360424da70)

### Important Details

- Version: [Cloud 
- OS: MacOSX]
- Browser  chrome
- Environment  release

**Comment by kocharrahul7** [comment]
Intended behaviour
