### ISSUE TITLE
[BUG] Input Widget : Validation fails when data type is number

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#768]
Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Attachment: https://drive.google.com/drive/folders/1ciSaEWwfG11mrrb-bmv2tcm1yXsHYgs8?usp=sharing

Steps to replicate:
1. Open Input widget
2. Set Error Message to 'Hey'
3. Now, put Email in unexpected format (say 'abc') - Input box turns red and starts showing 'Hey' (Expected)
4. Now, set the data type to Text and enter '123e'
5. Now, set the data type to Number

Actual Result: Like in email case, Input box doesn't turn red and doesn't display 'Hey' (Error Message)

**Comment by hetunandu** [comment]
**Solution:** Update the [isValid binding](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/widgets/InputWidget.tsx#L62) of the input widget to handle data type of number

Note: This is a binding, so the function is actually written in 'quotes'. Make sure syntax is correct since the editor wont lint this.

>Need more guidance while working on a solution for this? Feel free to mention me in a comment on this issue and I'll be happy to help you out 😄

**Comment by MartinTuroci** [comment]
Hi, can I work on this?

**Comment by hetunandu** [comment]
Hey @MartinTuroci welcome to the Appsmith community! 🎉

Assigning this issue to you. Make sure you are able to open a PR within two days.

**Comment by MartinTuroci** [comment]
Thanks @hetunandu. I have problems with setting up the local dev env. I completed all the steps in [docs](https://github.com/MartinTuroci/appsmith/blob/release/contributions/ClientSetup.md), fixed minor TS error that prevented frontend build from building successfully, but it seems like the web client cannot connect to the server. I have run the `start-https.sh`: 
![image](https://user-images.githubusercontent.com/44962077/95016666-af1f0f80-0654-11eb-804c-86ed5d7eabb0.png). My `/etc/hosts`:
![image](https://user-images.githubusercontent.com/44962077/95016737-37051980-0655-11eb-9793-3c7badf4aa54.png)

The error I get:
![image](https://user-images.githubusercontent.com/44962077/95016772-63209a80-0655-11eb-9f45-ccb3ee679c06.png)

Note that I am on Linux `Ubuntu 18.04`.
