### ISSUE TITLE
[Bug] Text widget - Border width evaluated value is undefined by default 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7680]
## Description
Release/Production - It is observed that by default the text widget's border width value is undefined 

Expected Result:
Border width should show the default value instead of undefined 

### Steps to reproduce the behaviour:

1. Launch Appsmith app in the release environment 
2. Drag and drop text widget 
3. Open the property pane 
4. Click on border width and observe 

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [release]

<img width="1680" alt="Screenshot 2021-09-21 at 3 31 36 PM" src="https://user-images.githubusercontent.com/35128442/134152203-cb8cbf44-dd87-4c62-ae39-78afe1442e96.png">

**Comment by somangshu** [comment]
Looks like this is valid, The border width in default state is undefined, What is expected here.

Closing for now
