### ISSUE TITLE
[Bug]-[560]: On special character column name the data does not get fetched 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7687]
Pre condition:
Create a sheet with special characters and follows the steps

Steps to reproduce:
1) Add a Google Datasource
2) Add fetch Query
3) Type: Query row
4) In the Where clause add a special character as column name and value
5) click on RUN 
and observe

Observation:
It is observed that the error is said as "UNDEFINED" which does not give clarity to users on the error 

Expectation:
It is the row from the doc that must be displayed 
![Screenshot 2021-09-21 at 4 13 26 PM](https://user-images.githubusercontent.com/71753653/134661440-06c1eaf3-44c8-4368-8666-12d0ef1dc071.png)

**Comment by rohan-arthur** [comment]
gsheet 6m usage: 1400
assume 20% requirement: 280

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 280 |
| Effort (months)  | 0.25 |

**Comment by ajinkyakulkarni** [comment]
@prapullac verified that this is fixed now.
