### ISSUE TITLE
[BUG] No error on triggering the removed Query from button widget.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#769]
## Description
Triggering the removed query isn't showing any `js` error.

### Steps to reproduce the behaviour:
1. Add a button to trigger a query.
2. Show success, error message on query completion.
3. Click button and see success message.
4. Remove the query and click the button.
5. No query completion information is shown to user.

[Video In Action.](https://drive.google.com/file/d/1b9xIPd9Dnuq04m5FgEMgrIbJkSpGUyVW/view?usp=sharing)

[Source Issue.](https://github.com/appsmithorg/appsmith/issues/725)

### Important Details
 - Version: Cloud
 - OS: MacOS 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay marking this as enhancement because we haven't implemented any error handling for invalid JS yet. There is some technical complexity around it

**Comment by mohanarpit** [comment]
Closing this issue as we show an error when an invalid action is executed.
