### ISSUE TITLE
[Bug] Evaluated value is retained for deleted where condition entry on Google Sheets query

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7690]
## Description
Evaluated value is retained even after row is deleted and a new where clause is being added by user

### Steps to reproduce the behaviour:
1. Go to Google sheets query and enter all details
2. Observe the evaluated value for **Where Condition** fields
3. Now delete the row and observe the evaluated value still present on the new row. This happens to multiple where clauses as well, i.e. if there are 3 column's being filtered then on deleting all 3 rows and adding them back on will still show the retained evaluated value

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2579cc10b0c64934b95ef4686ba431e4-00001.gif)](https://www.loom.com/share/2579cc10b0c64934b95ef4686ba431e4)

**Comment by arunvjn** [comment]
The expectation is for the evaluated value section in the popper, to show values like in the fields above the where clauses.

Start at `NestedComponents` component in `FieldArrayControl.tsx` and work your way downwards to solve this issue.

Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by aliya-rahmani** [comment]
Please assign this to me!

**Comment by ramsaptami** [comment]
Its's all yours @aliya-rahmani.

Please don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue.

**Comment by SiddheshShinde-tech** [comment]
Please assign this issue to me. I would like to work on it !!!

**Comment by ramsaptami** [comment]
I've assigned it to you @SiddheshShinde-tech.

Check out the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before getting started.

**Comment by ramsaptami** [comment]
You can drop in any query and the team will get back as soon as possible

**Comment by Nikhil-Nandagopal** [comment]
Tagging as evaluated value because it's related to the evaluations not being triggered when the query is opened
