### ISSUE TITLE
[Bug] Evaluated value is a number yet an error stating that it's not a number is displayed.

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#7697]
## Description
Evaluated value is a number, yet an error is shown stating that "This value doesn't evaluate to type string or number"

[What happened]

![CpVY8I9](https://user-images.githubusercontent.com/46670083/134186144-fae16189-b89f-4f03-b32c-ce151178c942.png)

### Steps to reproduce the behaviour:

1. Bind Api to input widget
2. access a value of type "number" 
3. See error

### Important Details

- Version: [Cloud ]
- OS: [e.g.MacOSX]
- Environment [release, deploy preview]

**Comment by somangshu** [comment]
@vivekverma2312 please check if this is fixed

**Comment by sbalaji1192** [comment]
RCA - Issues stems from defaultValueValidation function in inputWidget. we are not converting the value to text, when input type is text, before checking validity.
Solution - Handle the case when input type is text and the value is number.
