### ISSUE TITLE
[BUG] Input value is reset while switching between the pages

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#770]
Attachment: https://drive.google.com/drive/folders/1L83s34T6dpYbcRvJaqvUJo79glsINsys?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Have 2 pages - Page 1 and Page 2
2. In Page 1, have an input widget
3. Deploy the app
4. In the input widget of page 1, enter an input value
5. Switch to Page 2 and then switch back to page 1 

Expected Result: Since there is no page reload, input value shouldn't disappear from the input box.
Actual Result: Input value disappears from the Input widget.
Note: Above case is when default value isn't set. If the default value is set, it resets to the default value.

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 there is a page load, data across pages are not persisted today
