### ISSUE TITLE
[Bug] Video Widget - Expected structure example and evaluated value value's overlaps with copy icon 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7701]
## Description
Release - It is observed that the expected example structure and evaluated value value's overlaps with the copy icon 

Expected result:
Expected example structure and evaluated value should not overlap with any icons

### Steps to reproduce the behaviour:

1. Launch Appsmith app in release environment 
2. Drag and drop video widget 
3. Open property pane 
4. Click on url field and expand expand expected structure example and evaluated value and observe

### Important Details

- Version: [11.3]
- OS: [eMacOS Big sur]
- Browser [chrome, safari]
- Environment [release]

<img width="1680" alt="Screenshot 2021-09-21 at 9 53 55 PM" src="https://user-images.githubusercontent.com/35128442/134288652-1946a3af-c45e-402d-8c93-432306df2cbc.png">

**Comment by SatishGandham** [comment]
@YogeshJayaseelan , Can you please test this agin. We are unable to reproduce.
