### ISSUE TITLE
[Bug] Can't delete unused Data Source

### ISSUE THREAD

**Issue by tlawrence-TAG** [appsmithorg/appsmith#7703]
## Description

Trying to delete a data source that is NOT used anywhere by anyone. Toast message says it's used by 7 actions. Can not idenity these actions and do not see the data source in use at all.

- Version: Self-hosted Release v1.5.21

**Comment by Nikhil-Nandagopal** [comment]
Hey @tlawrence-TAG ! We have this issue tracked here #4609
We'll get on this.
