### ISSUE TITLE
[BUG] All the selected values from the dropdown are not visible in the box

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#772]
Attachment : https://drive.google.com/drive/folders/1SIlVTswfLx8QgeF8fNvX5uc2O5Kwlx2u?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. In the dropdown widget, Select 'Multi Select'
2. Have 7-8 values 
3. Now, from the dropdown, select all the values

Expected Result: User should be able to see all the selected values.
Actual Result: User is able to see Only 2-3 values.

**Comment by visibleajay** [comment]
@Saket2 @Nikhil-Nandagopal  This seems to be similar to `https://github.com/appsmithorg/appsmith/issues/728`

**Comment by Saket2** [comment]
That issue talked about 'how more preference' was given to that 1 particular value 'Vegan' and how 'Vegan' removal leads to the removal of all the values.

In this particular case, when we have 7-8 values - we're talking about the box capacity part - where box is unable to contain values beyond a limit (2-3 in this case).

**Comment by hetunandu** [comment]
**Solution**: To show as many options as we can when many options are selected yet also have some indication that more selected options exist (like ellipses work for text).
This is mainly a _CSS_ issue but one needs to know how we block overflowing via our widget positioning and resize containers.

Most changes would happen here
https://github.com/appsmithorg/appsmith/blob/master/app/client/src/components/designSystems/blueprint/DropdownComponent.tsx#L157

Keep in mind that widgets can be resized so when the height of the dropdown increases/decreases, the options should take up appropriate space.

Other resources:
[Flex box](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
[Blueprint Muti select](https://blueprintjs.com/docs/#select/multi-select)

>Need more guidance while working on a solution for this? Feel free to mention me in a comment on this issue and I'll be happy to help you out 😄

**Comment by hetunandu** [comment]
Further cases mentioned in #728 
> Attachment: https://drive.google.com/drive/folders/1uABc1FdBUbh9GOGX2DS1QsSPWeDLN3oD?usp=sharing
> Issue 1: If there are multiple values are selected, only 'Vegan' is visible in the box.
> Issue 2: If 'Vegan' is removed, none of the other selected values appear in the box.

**Comment by pushkar1393** [comment]
Can someone assign this to me? I'd like to try my hand at this.

**Comment by Nikhil-Nandagopal** [comment]
@pushkar1393  go for it! 👍

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal @hetunandu I tried to solve this with CSS but couldn't make it work because of the way blueprint's multiselect works. It's one of the side-effects of the fixed height we are passing to the widget.

Blueprint's multiselect actually take more height as we keep on selecting the options. But that can't be done in our case.

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan we don't want to change the height, instead we want to show as many options as possible and then add a +2 more option

**Comment by jsartisan** [comment]
I don't see any prop being supported by blueprint to accomplish the above requirement. Let me discuss this with hetu.

**Comment by areyabhishek** [comment]
This problem is very acute and old. Can we fix this soon?
<img width="362" alt="Screen Shot 2021-03-19 at 2 42 33 AM" src="https://user-images.githubusercontent.com/30255708/111698436-d5c8af80-885c-11eb-8012-bc0d71f7329c.png">

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan you can try ant design instead

https://user-images.githubusercontent.com/3897254/111737540-cfaaf100-88a5-11eb-917f-8f3f91bc0330.mov

**Comment by areyabhishek** [comment]
How the design is supposed to look: https://user-images.githubusercontent.com/30255708/114886064-dbe28980-9e24-11eb-8277-aee3143035bb.png

**Comment by areyabhishek** [comment]
We had a user comment about this issue in discord.

**Comment by areyabhishek** [comment]
@Tooluloope @somangshu Are we working on this issue?

**Comment by Tooluloope** [comment]
> @Tooluloope @somangshu Are we working on this issue?

Blueprint doesn't Currently support this feature.
We're planning to make multiselect a standalone widget and then use a better library for Multiselect.
