### ISSUE TITLE
[Feature] Access control URL needs more info

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#7728]
1. The Appsmith app URL doesn't explain what permissions are associated with the URL
2. We need to provide more details beside the URL similar to how Google drive does it See below
<img width="619" alt="Screen Shot 2021-09-22 at 3 48 51 PM" src="https://user-images.githubusercontent.com/30255708/134326423-a575e4e2-37f0-4404-a03b-6d999bfbdcfb.png">
.

**Comment by riteshkew** [comment]
Not relevant anymore. Closing it
