### ISSUE TITLE
[BUG] Timer doesn't make sense in the date-picker in 2 specific formats

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#773]
Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Pick date-picker

Actual Result: If date format is selected as YYYY-MM-DD or DD/MM/YYYY, timer is still present on the date-picker. Despite user's selection, it doesn't appear because of the specified time format.
Expected Result: If date format is selected as YYYY-MM-DD or DD/MM/YYYY , timer shouldn't be present.

Attachment: https://drive.google.com/drive/folders/1MtzFJYCu6L8sO8DUE3mBEpKiaMa7Mprv?usp=sharing

**Comment by riodeuno** [comment]
We need a separate datepicker widget which uses and displays only dates.

**Comment by somangshu** [comment]
This issue will be resolved with #3516, And in extensions, the time picker will be a separate widget #3346
