### ISSUE TITLE
[Bug] [Signposting] Application erroring out if an action is bound to a nested widget property

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#7730]
## Description

During signposting, If user binds an action.run to onClick of table column button. application is erroring out with message unable to access indexOf of undefined.

### Steps to reproduce the behaviour:

1. During First time user onboarding flow, Add a table with button column.
2. Bind an action to one of the button.
3. observe application getting errored out.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by sbalaji1192** [comment]
https://www.loom.com/share/27d580cc896d4617a4812f7e4bb722d1

**Comment by ramsaptami** [comment]
verified on release

**Comment by Nikhil-Nandagopal** [comment]
@sbalaji1192 seems like this issue occurred again. Is this in master?

**Comment by sbalaji1192** [comment]
This sentry issue is stale one that  got logged on sep 22nd. We merged the fix to master on 23rd. This has been marked resolved on the sentry already.
