### ISSUE TITLE
[Bug]Delete form widget fails intermittently

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#7737]
Steps:

1. As a part of the form widget spec we see tests related to delete widget failing intermittently.
2. Delete from properties / Delete from the keyboard is failing intermittently, this is after we optimized the test

**Comment by somangshu** [comment]
@NandanAnantharamu what is expected here, Looks like this should be assigned to the owner of the test optimization

**Comment by NandanAnantharamu** [comment]
@somangshu as discussed, this is an intermittent issue, not a cypress issue.

**Comment by somangshu** [comment]
@vivekverma2312 @YogeshJayaseelan can you verify this, if possible we will need some reproducible steps. 

@NandanAnantharamu in case you know how to better debug this, Please let us know, Right now on cypress the only error i see is `CypressError: Timed out retrying`, I suspect something to do with eval here

**Comment by NandanAnantharamu** [comment]
@somangshu CypressError: Timed out retrying, this is seen because after delete the @updateLayout call happens. Since the Delete action hasn't worked the call hasn't happened and the test failed.

**Comment by dilippitchika** [comment]
Is this still happening @NandanAnantharamu?
