### ISSUE TITLE
[Bug] Default JS Snippets “Conditionally Color Table Cells” & “Setting Default states of boolean properties” not changing upon change in snippet text field value.

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#7739]
## Description

Changing the value of Table JS snippet text field does not change the default snippet value for “Conditionally Color Table Cells” & “Setting Default states of boolean properties”

### Steps to reproduce the behaviour:

- Go to link https://release.app.appsmith.com/
- Login into Appsmith through your user credentials.
- Go to the widget screen by clicking on the Add icon of widgets
- Drag and drop the Table widget
- Open the property pane and go to any text field.
- Remove the already existed Default Data and type the “/”
- Menu will be shown
- Select “Conditionally Color Table Cells” or “Setting Default states of boolean properties” Js snippet
- Navigate to the customize tab, Change the values in text field.
- Values in default JS snippet are not changing.

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [Release]

## Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e40987e50b62441383c9ec4387b3a040-00001.gif)](https://www.loom.com/share/e40987e50b62441383c9ec4387b3a040)

## Screenshot:
https://www.screencast.com/t/0p3Xu5w8y
https://www.screencast.com/t/lCxaEAwndC

**Comment by Nikhil-Nandagopal** [comment]
Fixed
