### ISSUE TITLE
[Bug]-[2000]:Query created from property pane, doesn't bind the query to the property it was added from

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#7745]
## Description
- [ ] when user adds a query from the property pane, it doesn't bind the query to the property it was added from
- [x] when user hits add query from the property pane it takes to the new datasources page but it should take to the active datasources when there are datasources already added

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | 0.07 |
