### ISSUE TITLE
[BUG] Table isn't updating with server side pagination.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#775]
## Description
Activated `server side pagination` to provide Realtime information to table. On updating, the `pageNo` is updating but the table data is same as shown on the previous selected pageNo.

### Steps to reproduce the behaviour:
1. Create getKycApp query `select * FROM public."kycApplication" offset {{(Table1.pageNo-1)*10}} fetch next 10 rows only;`.
2. Connect `TableWidget` with getKycApp query.
3. Enable `Server side pagination` and switch to a different `page`.
4. Table data would remain same with respect to initial displayed data irrespective of pageNo.

[Video In Action.](https://drive.google.com/file/d/1Dkzdv8p6b4DLohGVxHRNG7vqXu8Jk-AU/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by harishkotra** [comment]
@visibleajay I checked the video. You have to **set the query to run** in the `onPageChange` along with showAlert() that you already have.

**Comment by visibleajay** [comment]
@harishkotra It's working. I thought, since the displayed table is already binded to the query it would automatically pulled the data on page change. Thank You for the clarification. Closing Now.
