### ISSUE TITLE
[Enhancement] - Inline table edit: Providing an option to enable/disable edit for individual columns

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7756]
## Description
Table Widget - inline Edit - It is observed that if the user has large column data and when Inline Edit is enabled and if the user wants to update the first column user needs to scroll to the first column edit and them again needs to scroll to the end to perform save

Expected Result:
Providing an edit option individually to every column to edit details or with some different approach 

### Steps to reproduce the behaviour:

1. Launch appsmith app in the deploy preview- https://deploy-preview-6990--appsmith-editor-ce.netlify.app/applications
2. Drag and drop table widget 
3. Bind table with large set of columns
4. Enable inline edit toggle 
5. Click on Edit column button in the table and try to edit the first row and observe

**Video Link:**
https://loom.com/share/e2ef16b891024603ac0c8b8d7f9276e8

### Important Details

- Version: [11.3]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [deploy preview]

**Comment by somangshu** [comment]
@vibhandikyash this feedback exist on the PR, we will be developing a solution around this after a discussion, Lets link this to the PR

**Comment by dilippitchika** [comment]
Linked to #4183
