### ISSUE TITLE
[Feature] Improving form widget keyboard accessibility

### ISSUE THREAD

**Issue by ohansFavour** [appsmithorg/appsmith#7757]
## Summary

In a regular HTML form, a user can choose to set different tab indices for different inputs irrespective of their position. This gives users control over how the cursor moves between elements in a form.

## Motivation
Improves keyboard accessibility in forms on Appsmith.

## Additional Context
<img width="180" alt="Screen Shot 2021-09-23 at 11 35 48" src="https://user-images.githubusercontent.com/46670083/134494340-adbffc7d-4a8e-4cff-85a2-23c8d506873f.png">

**Comment by billyrudi** [comment]
this is a must to create user friendly forms!

**Comment by dncpax** [comment]
quality of life improvement. otherwise it feels odd jumping all around the form...

**Comment by dncpax** [comment]
also it's also odd at least for me that tabbing also focus up and down arrows in calendars... but maybe it's just me.

**Comment by billyrudi** [comment]
Hi, there are news on this?

**Comment by dilippitchika** [comment]
Hey we haven't been able to prioritise this yet, one workaround is to arrange the widgets based on the order here.

![Screenshot 2022-03-25 at 3 55 25 PM](https://user-images.githubusercontent.com/19730984/160103365-139c64c0-837c-4bdf-9369-9828069acd8c.png)

**Comment by billyrudi** [comment]
....workaround??  and how i can do it?

**Comment by dilippitchika** [comment]
You can checkout the video below, whichever widget is dropped first keyboard navigation using tabs works in that order. 
https://www.loom.com/share/0941e8747518484db064e58854f2edd9

**Comment by billyrudi** [comment]
but if i have an already made form with many widgets how i can do it? i must delete all?? and if i can change on widget position???
this is not a valid solution!

<img width="2182" alt="Schermata 2022-03-25 alle 12 08 21" src="https://user-images.githubusercontent.com/11408614/160110122-9db6629f-7d69-4c68-8da2-baebc73e6b3c.png">

**Comment by dncpax** [comment]
for a moment I had hope... if only we could reorder widgets in the widgets tree...
@billyrudi is right... this is not a solution.

**Comment by dilippitchika** [comment]
As I said, it's a workaround. Sorry if I put wrong expectations here. This is still something we need to fix.

**Comment by dncpax** [comment]
@dilippitchika hey. I really appreciate how you try to help us! Thanks.

**Comment by dilippitchika** [comment]
Reach: 554 min in 6mos
Impact: High

**Comment by makulais** [comment]
Uhm Wow, can't believe this wasn't part of the original. For the workaround, also be aware that you have to create them in reverse order so that they can come out in correct order?! Found it easier to create them all, using containers inside containers for the copies, then use Ctrl-X and Ctrl-C in reverse order to get them all ordered correctly. Had over 50 input widgets to do this on. Would be nice to have a grid layout also!!

**Comment by makulais** [comment]
An alternative to adding a tab index, or in addition to it, would be the ability to focus on a specific widget using javascript so that when a user completes a widget (onSubmit or onTextChanged), the focus can be placed on the user's next entry automatically.

**Comment by samg666** [comment]
+1
hope to have this feature soon.

**Comment by billyrudi** [comment]
Hi, can ypu prioritize this feature?

**Comment by makulais** [comment]
Use Case:

User has to enter data in each of the fields shown, in order, top to bottom, left to right. Without the ability to control tab functionality, it is extremely slow and difficult to move to the next field in sequential order as it requires mouse actions, then keyboard actions for entry at each field.

![image](https://user-images.githubusercontent.com/34661597/200432346-65e91d04-f707-456e-9536-add6fce43697.png)

**Comment by jdglacier** [comment]
Any update on this?

**Comment by dilippitchika** [comment]
Thanks for all the information, we will prioritise this soon and deliver

**Comment by CptOperations** [comment]
This is a feature I would like to see, will make the input of data faster on report forms.

**Comment by jsartisan** [comment]
@CptOperations @jdglacier @makulais @billyrudi @samg666 @dncpax 
Hey guys, I picked this issue last week and I have a DP ready that I would love to have your feedback on. Here is the DP for it - https://appsmith-git-fix-widget-focus-get-appsmith.vercel.app/

Can you guys try it and let me know if you see any issues with it? 

Note: You will need signup on to the DP ( your app.appsmith.com credentials won't work on it as it points to a different database )

**Comment by jdglacier** [comment]
Hey @jsartisan, I can't seem to sign up on the DP. 
![image](https://user-images.githubusercontent.com/111010738/208900888-608b064f-d083-4bb7-af1d-bd672e010c59.png)

**Comment by dilippitchika** [comment]
Hi @jdglacier google login won't work here, you have to sign up by adding an email and password

**Comment by jdglacier** [comment]
That is the error message I get after entering an email address and password on the signup form. I got an altogether different message when I tried singing up with Google.

**Comment by dilippitchika** [comment]
Oh my apologies, let me create a test account and paste it here.

**Comment by dilippitchika** [comment]
@jdglacier here's a set of credentials you can use to login - widgetfocus@appsmithdemo.com ; widgetfocus@123
Please create a workspace for you to test once you login

**Comment by jdglacier** [comment]
Thanks @dilippitchika, I'm in. 
But it's unclear to me how the next widget is put into focus. Presumably an event needs to be executed onBlur or onSubmit? @jsartisan

**Comment by dilippitchika** [comment]
Hey @jdglacier you can press tab on keyboard and it will go to the next widget.

**Comment by jdglacier** [comment]
Ahh yes I see now, it's position based. That's even better! It seems to work well with all different types of widgets, even with copied and pasted.

**Comment by jsartisan** [comment]
@jdglacier Did it feel natural? Any feedback/suggestions for us?

**Comment by jdglacier** [comment]
@jsartisan It feels very natural, I like it a lot. The only widget that didn't seem to behave like the others was the **Checkbox**, which just gets skipped altogether (**Checkbox Group** is okay).

**Comment by jsartisan** [comment]
That's weird. I just checked the Checkbox widget. It is getting focused for me. Can you share a video if possible?
One thing to note is the focus state for the checkbox is the same as its hover state, you won't see any outline on focus ( like we see in the input widget ). Also, you will need to hit the spacebar to check/uncheck the checkbox when it's focused.

**Comment by jsartisan** [comment]
The focus state for the checkbox is very subtle. That might be making an impression that it is not getting focused.  🤔

**Comment by jdglacier** [comment]
I am not consistently able to replicate it, but you can see in the following video that on the fourth row, the Phone Input and Multitree Select widgets go into focus before the checkbox widget. I do see it go into focus now, just not in the order I would have expected. 
https://user-images.githubusercontent.com/111010738/208935750-1c354ac0-42fd-40b5-92c7-37807416314f.mp4

**Comment by jsartisan** [comment]
Got it. Thanks for the video. Actually, we are calculating the next widget to focus on based on the widget ( widget as a whole ) top position, not the element top position inside the widget. If you notice, in the fourth row, the phone input/multi-select widget and checkbox widget are not of the same height and are also not in the same line (the input/multi-select widget is above than checkbox widget ). Can you try making them of the same height?

**Comment by jdglacier** [comment]
@jsartisan that makes sense! The only problem I have with this is that sometimes widget heights need to be different for them to appear clean and aligned. For example, I would lower the following checkbox's height a bit so it appears on the same level as the phone input widget to its right. 
![image](https://user-images.githubusercontent.com/111010738/208940854-47a1a94f-095e-4d5e-a4cf-c58a2d348692.png)

But that's not a big problem. I can always remove labels from the taller widgets, then add Text widgets above them in lieu. 

Thank you so much for your work on this! This will give forms a much more professional feel.

**Comment by jsartisan** [comment]
Thanks, @jdglacier for the feedback. Really appreciate it.

**Comment by makulais** [comment]
Better than nothing but this solution **does not provide the developer to actually choose the order**. In my case, I have organized inputs based on calculations vertically inside containers, thickness, then weight, then finally density. The tab prioritization routine takes the focus down through the container first then horizontally across to the next container. But the user performs all of the same functions measuring thickness for all lanes first which means that he needs to go horizontally across first then skip to the next row. In order to effectuate this with this solution, I have to remove all of the containers organizing the input fields by lane, which then isn't as intuitive to the end user. 

I would prefer one of the more generalized solutions I have previously described and which is followed in other applications.

**Comment by dilippitchika** [comment]
Hi @makulais my apologies for this, i would say tab index editing as a feature is really complex for a lot of our users. But you are right, we will give the flexibility needed to do that, but it might not be now.

**Comment by dilippitchika** [comment]
In your use-case, you can use a divider widget instead of a container and it would start working for you, our design follows web-standards where we realised any container should get the first priority in tabbing. In this case i see that UI grouping is different and user expectation is different which is why it breaks the pattern.

**Comment by dilippitchika** [comment]
I have created a new issue for this #19935

**Comment by makulais** [comment]
> I have created a new issue for this #19935

Thank you. In my app I also used Icon Buttons to display to the user when a value was out of range, it provided a better highlighting of the specific values than other methods. Bit me with this method of providing tab functionality also though since now they are part of the tab stops. User has to tab twice to get through the input widgets.

**Comment by CWatson-Tactile** [comment]
Any updates on this feature enhancement?

This is quite annoying when using a JSON form. For number inputs, there is no option to disable the step up/down arrows, so tabbing will end up focusing them, causing extra clicks. On a regular number field, you can disable the arrows, which makes navigating much more efficient.

**Comment by Nikhil-Nandagopal** [comment]
@CWatson-Tactile we're working on an improved UI builder that will have accessibility baked in and take care of these issues out of the box

**Comment by awalters141** [comment]
Is this still being worked on?
