### ISSUE TITLE
[Feature] Allow Set timeout in JS

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#776]
## Description
Custom onClick action isn't triggering for button.

### Steps to reproduce the behaviour:
1. Add Button Widget with onClick.
2. `setTimeout(() => showAlert(`Error in loving it`), 10)`
3. Trigger OnClick.

<a href="https://ibb.co/4NWGDMV"><img src="https://i.ibb.co/XJXgdpC/Btn-On-Click.png" alt="Btn-On-Click" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOS 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay we don't support setTimeOut today so converting this into a feature request

**Comment by mohanarpit** [comment]
Related PR that disallows `setTimeout` explicitly: #2076. This is because this is an unsafe function and can potentially bring the application to a stand-still. 

Instead, a user must chain their function calls to be invoked `onSuccess` or `onError` of the previous function execution.

**Comment by aswathkk** [comment]
@mohanarpit We do support `setInterval` now. Similarly, can we support `setTimeout` as well?

**Comment by Nikhil-Nandagopal** [comment]
@aswathkk yeah I agree we should allow this as well

@rohan-arthur @ajinkyakulkarni

**Comment by rohan-arthur** [comment]
@Nikhil-Nandagopal would you please clarify the value of this feature request? What will the user be able to achieve ina business sense (perhaps a use case or two would help)

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur they could use it to show app viewers a message if no action is taken in an app within 60 seconds or as a double confirmation mechanism for destructive actions to give users x seconds to cancel the action before it is fired.

**Comment by aswathkk** [comment]
@rohan-arthur 
A user wanted to call a rate-limited API. They want to make an API call and once it succeeds, they wanted to call another API after a bit of delay. This could only be achieved by using setTimeout.

**Comment by Rishabh-Rathod** [comment]
@rimildeyjsr will be sharing docs on `how to create global actions` and then interested contributors could pick this up.

**Comment by berabhishek** [comment]
I would like to pick this up

**Comment by rimildeyjsr** [comment]
@berabhishek - Hey, thanks for your interest in working on this issue! I have assigned this issue to you, and you can refer to this document to get an overview of how you would work on this issue!

https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/GlobalFunctions.md 

Feel free to ping in case you have any queries!

**Comment by berabhishek** [comment]
Hey can someone review my PR. Note: working on appsmith docs, is it also the job of the dev or wording is chosen by writers?

**Comment by Rishabh-Rathod** [comment]
Hey @berabhishek, We will start reviewing the PR and get back to you soon. 

> working on appsmith docs, is it also the job of the dev, or wording is chosen by writers?

No worries on docs, it will be picked up by the team.

**Comment by AS-Laguna** [comment]
@Rishabh-Rathod is there any update on this? Also a use case from discord user vaidarbhi#9160:

> I have built  an application for mental health awareness for company’s Employees so when the employees log in .. they will be navigated to resources page and after one minute employees will be auto logout and navigated back to log in page. This is my use-case.

**Comment by berabhishek** [comment]
Hey, will update the PR within couple of days
