### ISSUE TITLE
[Bug] Embedding public apps in iFrames don't work

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#7777]
## Description

Apps that are shared publicly are still redirected to the Appsmith login page when the `embed=true` parameter is added to the url for use in iframes. 

### Steps to reproduce the behaviour:

1. Click SHARE and set the app to `Make the application public`
2. Open the link, and the app should bypass the login screen and go straight to the app. 
3. Add `embed=true` to the end of the url and hit enter

You are taken to a login screen, even though the app is set as public. I first noticed this in an iframe and then confirmed the same behaviour when going to the url directly with the embed parameter. 

### Important Details

- Chrome/MacOS

**Comment by Nikhil-Nandagopal** [comment]
@Rishabh-Rathod @sharat87 can we look at what broke this?

**Comment by GreenFlux** [comment]
Unable to reproduce after updating Chrome, rebooting and clearing cache. Will reopen if it occurs again.
