### ISSUE TITLE
[Bug]Git Sync issue - First DP issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7784]
## Arpit feedback

- [x] Empty repo should exclude README, etc.->UI pending
- [x] Default branch name should be picked from repo->fixed
- [x] Can the URL have query params instead of URL params? It Will be easier for users to change branches
- [x] The folder structure should have folder names in small case->fixed
- [x] Create a Datasource is crashing->Fixed
- [x] Switch to the new branch that has been created
- [x] No validation for https git urls
- [x] Create page crashed the app->Fixed
- [x] Clicking on the icons for git should go to the relevant section in the modal
- [x] Debug icon is too small in the bottom bar. Not looking good.
- [x] Switching branches causes the dropdown to flicker
- [x] Creating a new branch should work by pressing the enter button
- [ ] Documentation links will have to be updated.

## Nikhil feedback:

- [x] The option Use default config is disabling the update button
- [x] Create branch doesn't switch the branch
- [x] Hitting commit or merge is always landing on the connect tab instead of the deploy tab
- [x] The pushed branches are not showing in Github->fixed
- [x] Seeing the Black topbar on deploy (no repro)
- [x] A new branch is created on master instead of on the current branch
- [x] Forking / exporting a git connected apps does it for the master branch: add a message on the UI indicating this behaviour
- [x] #8656
- [ ] Default didn’t show and is off by default @abhvsn  ( local config initially being empty will fix this )
- [x] Creating a new app is always prompting to connect to git
- [x] The UI for switching branches needs an update

-----
- [x] Fork Application is not working for git connected repo
- [x] #7966
- [x] Readme.md file HTML syntax is not supported on bitubcket
- [x] check if public repos work without setting up a key
- [x] In the Git repository, the Readme section is displayed as empty
- [x] #8397
- [x] #8395

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by AnaghHegde** [comment]
> Arpit feedback
> 
> * [x]  Empty repo should exclude README, etc.
> * [x]  Default branch name should be picked from repo
> * [x]  No validation for https git urls
> 
> Nikhil feedback:
> * [x]  The pushed branches are not showing in Github
> * [x]  A new branch is created on master instead of on the current branch
> * [x]  Forking / exporting a git connected apps does it for the master branch: add a message on the UI indicating this behaviour
> * [x]  Fork Application is not working for git connected repo

Above ones are completed.
