### ISSUE TITLE
[BUG] When password is wrong, email ID is also cleared from the Login Form

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#779]
Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
Case 1: Enter Correct Email ID and Incorrect password.

Actual Result: Email ID is cleared from the form. 
Expected Result: If Email ID is present in the database, then it shouldn't be cleared from the form.

Case 2: Enter Incorrect Email ID and Incorrect password.

Actual Result: User is notified that there may be incorrect/invalid credentials.
Expected Result: Direct notification that Email ID doesn't exist/registered with Appsmith.

<img width="1789" alt="Screen Shot 2020-09-29 at 12 02 22 AM" src="https://user-images.githubusercontent.com/49346036/94472066-d3f42c80-01e7-11eb-90c2-afebf6eb99a7.png">

**Comment by pc9795** [comment]
IMO the current behaviour is correct. We shouldn't be exposing this information that whether an email is incorrect or a password. The message with invalid credentials is appropriate.

**Comment by mohanarpit** [comment]
Closing this issue because this is expected behaviour.
