### ISSUE TITLE
Helper text of switch control below query editor takes full width.

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#7791]
## Description

Helper text of prepared statement control in query editor takes full width.
<img width="1432" alt="Screenshot 2021-09-24 at 1 15 30 PM" src="https://user-images.githubusercontent.com/89374972/134638039-38dbd721-382d-4acb-94b1-b25471243862.png">

### Important Details
- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by RakshaKShetty** [comment]
reopening the bug facing the same issue again 
![image](https://user-images.githubusercontent.com/45958978/147913737-626fffd5-ff43-40ca-a47f-d187a95636dd.png)

**Comment by rohan-arthur** [comment]
![Screenshot 2024-06-03 at 13 55 34](https://github.com/appsmithorg/appsmith/assets/94514895/25224ca4-6db2-4407-ba90-fce1b2f3590e)
