### ISSUE TITLE
[Bug]The delete button functionality is not working in Generate page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7796]
## Description

[What happened]The delete button functionality is not working in Generate page

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/62ab59f19943479484b69e447d31e795-00001.gif)](https://www.loom.com/share/62ab59f19943479484b69e447d31e795)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser chrome
- Environment release

**Comment by Rishabh-Rathod** [comment]
@RakshaKShetty Is it for only mongo DB or for all templates?

**Comment by RakshaKShetty** [comment]
@Rishabh-Rathod for all the template
