### ISSUE TITLE
[Bug]Select widgets：the drop-down content shows that the text flashes

### ISSUE THREAD

**Issue by dschain** [appsmithorg/appsmith#7797]
## Description

[What happened]
when Generate from Data，get a page。
1.Add a drop-down box to select the input content, the content of the down content comes from mysql；The drop-down box appears in two places：Update Form and Insert Form；
2. The content of the drop-down box in Update Form is displayed normally，but the content of the drop-down box in Insert Form is abnormal。The content in the red box is flashing, and the content of the drop-down box cannot be selected。

![y](https://user-images.githubusercontent.com/44538731/134644359-298a741d-c212-4a17-9ff0-a8dff8e53996.png)
### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by dschain** [comment]
https://user-images.githubusercontent.com/44538731/134648146-e2e3049a-d424-4153-b529-ac87de028f34.mp4

**Comment by dschain** [comment]
Browser：Google Chrome

**Comment by Nikhil-Nandagopal** [comment]
@dschain sorry you faced this issue! We're working on a fix for this
