### ISSUE TITLE
[Bug]The prepared statement is displayed in 2 places

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7798]
## Description

[What happened]The prepared statement is displayed in 2 places under the query pane and also on the setting page

### Steps to reproduce the behaviour:

![image](https://user-images.githubusercontent.com/45958978/134646912-9e29ae11-8816-4aad-8f98-860a1d6d5e9f.png)
![image](https://user-images.githubusercontent.com/45958978/134646942-c1667e8a-e7a0-4016-ad01-807f9bd01340.png)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser chrome
- Environment release

**Comment by mohanarpit** [comment]
This is intentional to help users discover that prepared statements toggle is turned on & that certain queries may not work.
