### ISSUE TITLE
[Bug] Unable to launch duplicated application 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7799]
## Description
Unable to launch a duplicated application that was created during last regression cycle 3 days ago

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/460b790aa7584fa3a1cf949db2624204-00001.gif)](https://www.loom.com/share/460b790aa7584fa3a1cf949db2624204)

**Comment by mohanarpit** [comment]
@ramsaptami Can you please check the browser's network & error console? Do you see any errors there? If yes, can you please paste that as well? Will help triage the issue.

**Comment by ramsaptami** [comment]
![image](https://user-images.githubusercontent.com/79509062/134648515-5f698cb4-30a0-4551-b82b-218db98e17ea.png)
![image](https://user-images.githubusercontent.com/79509062/134648553-805aedc5-c6e2-4208-a4fb-d15afcc9ef8b.png)

**Comment by abhvsn** [comment]
@ramsaptami is this happening for perticular app? If yes can you paste the url of the app.

**Comment by ramsaptami** [comment]
Launching the app shows "unable to find resource" and Page not found message
https://release.app.appsmith.com/applications/6149a31630553a05e0ca91c9/pages/:pageId

Can't open the app to copy the URL. I've added you to the organization and you can try launching/editing the highlighted apps
![image](https://user-images.githubusercontent.com/79509062/134699476-554ae759-7e1a-4c0d-b932-ec1ccfe750dd.png)
