### ISSUE TITLE
[Bug] Empty checkbox is displayed when there is any error in the select widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7800]
## Description
Release/Production - When there is any error in select widget and clicking on the select widget - Empty checkbox is displayed

Expected Result:
Empty tooltip/popup should not be displayed in select widget is there is any error

### Steps to reproduce the behaviour:

1. Launch appmsith in the release environment 
2. Drag and drop select widget 
3. Click on options value and edit value to any incorrect data 
4. Click on select widget and observe

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-24 at 2 27 27 PM" src="https://user-images.githubusercontent.com/35128442/134648677-e8cf8353-20e0-4c99-b8e1-bd50d19dd94e.png">

**Comment by SatishGandham** [comment]
Show no items found message like multiselect. (Proposed solution)

![Screenshot 2021-10-01 at 4 17 11 PM](https://user-images.githubusercontent.com/441914/135607791-d573e6fd-e1e7-432c-848a-c2ae54716674.jpg)

CC: @somangshu

**Comment by ashish921998** [comment]
@somangshu @YogeshJayaseelan @Nikhil-Nandagopal I would love to work on this.

**Comment by Nikhil-Nandagopal** [comment]
@ashish921998 go for t!

**Comment by keyurparalkar** [comment]
@YogeshJayaseelan the mentioned issue is not producible. Neither on Production nor on the release application. Therefore, closing this issue
