### ISSUE TITLE
[Enhancement] Alignment issue with input widget, phone number type

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#7802]
## Summary

The `country-code` (+1) extension seems to be out of vertical alignment

<img width="547" alt="Screenshot 2021-09-15 at 4 43 18 PM" src="https://user-images.githubusercontent.com/88306433/134651038-8c39fafa-77c2-4bc1-926c-5d1e6316b921.png">

**Comment by aswathkk** [comment]
The following is what I see. The vertical alignment looks proper to me.

![Screenshot 2021-09-28 at 8 39 54 PM](https://user-images.githubusercontent.com/10436935/135114882-bd14c123-1b29-4dbf-92b4-66ffd7e2cf8a.png)

**Comment by ashit-rath** [comment]
Seems to have been fixed. Closing this issue
