### ISSUE TITLE
[Bug] Blank page loads when app is forked or imported

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7807]
## Description
Blank page loads when app is forked or imported

### Steps to reproduce the behaviour:
1. Fork an app and observe empty page being loaded
2. Import an app and observe an empty page being loaded

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/1a69a69e653248989e21bad360627530-00001.gif)](https://www.loom.com/share/1a69a69e653248989e21bad360627530)

**Comment by pranavkanade** [comment]
@ramsaptami can we close this?

**Comment by ramsaptami** [comment]
We can close this now. The RTS update seems to have fixed things right now. I'm able to fork/import apps successfully.
