### ISSUE TITLE
[Bug] Image uploaded in file picker which is binded in image widget is not displayed 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7809]
## Description
Release/Production - It is observed that the image which is uploaded in file picker widget and binded in image widget is not displayed

[What happened]
Image uploaded in the filer picker widget and with the following binding {{ Filepicker1.files[0].data }} in image widget should load the uploaded image in the image widget

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1.Launch appmsith app in release or prod environment 
2.Drag and drop file picker widget 
3.Uploaded a image 
4.Drag and Drop image widget 
5. Click on image url field and pass the following value {{ Filepicker1.files[0].data }} and observe

videolink:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/26e9eed907824834973a605b37cc80a3-00001.gif)](https://www.loom.com/share/26e9eed907824834973a605b37cc80a3)

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [Chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
Works fine for me 
![Screenshot 2021-09-30 at 4 49 43 PM](https://user-images.githubusercontent.com/11089579/135446055-0375a08d-63a4-401a-8590-0810c2d76fdc.png)
