### ISSUE TITLE
[BUG] User is asked to perform an action which is not even present on the screen. Text needs to be updated

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#781]
As seen in the screenshot, whenever there is a message 'Unable to reset the password. Please initiate a request via forgot password link to reset your password'.

**Explanation:** For some reason, the password reset failed - Now there is a message displayed (mentioned in the line above) on the screen. But on the same screen **where is the password reset option**?

In this particular case, the password reset failed because there was no 48 hours 'reset password link expiry' check on the reset password link. When user went ahead with password reset, it didn't allow him/her to proceed but at the same time there was no 'forgot password' option on the screen.

<img width="1791" alt="Screen Shot 2020-09-29 at 12 25 32 AM" src="https://user-images.githubusercontent.com/49346036/94473871-6b5a7f00-01ea-11eb-86b6-3596a5c48115.png">

**Comment by Nikhil-Nandagopal** [comment]
A simple solution for this would be to change the error message to
"Unable to reset the password. Please re-initiate the reset process via the login screen"

**Comment by mohanarpit** [comment]
This can be done by modifying the message in the enum class file `AppsmithError.java` in the `appsmith-server` maven module. The enum to be modified is: `INVALID_PASSWORD_RESET`

**Comment by pushkar1393** [comment]
Since this is a text change, does this require a unit test as well? I assume there would already be a test case covering the password reset functionality, so as long as it passes all the existing tests this should be done. Right?

**Comment by Nikhil-Nandagopal** [comment]
@pushkar1393 yes we can forgo a unit test for this. If you're taking up this issue just let us know so we can assign it to you :)

**Comment by akshay11298** [comment]
Hi @Nikhil-Nandagopal , if this issue is still open, kindly assign it to me, I would like to work on it.

**Comment by Nikhil-Nandagopal** [comment]
@akshay11298 it's all yours!

**Comment by akshay11298** [comment]
Hi, I have opened PR #1150 for this issue. Please refer to the attached screenshot of the screen after the update. https://drive.google.com/file/d/1sOtANg-UzBKTL56z4AylCTXBx1LFKSdL/view?usp=sharing

**Comment by akshay11298** [comment]
Hi @mohanarpit I have opened PR 1234 which fixes this issue. 
Below is screenshot of the result- 
![image](https://user-images.githubusercontent.com/26507126/96174055-61ed4880-0f46-11eb-9544-dedc2c66c19e.png)
