### ISSUE TITLE
[Bug] Auto focus does not happen on load for input widget if the input type is number

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7819]
## Description
Release/Production - Auto focus does not happen on load if the input widget type is number

Expected Result:
Input auto focus on load should happen for number type as well

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the release/prod environment
2. Drag and drop input widget 
3. Change the input type to number 
4. Enable auto focus 
5. Refresh the page and observe 

Videolink:
https://loom.com/share/64cfaab4292d4b5bbb3b42d536f5e0d6

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
This does not work for the currency and phone type as well
