### ISSUE TITLE
[Bug] Visible JS on false is not working for columns in Table widget

### ISSUE THREAD

**Issue by arslanhaiderbuttar** [appsmithorg/appsmith#7823]
## Description
Visible JS on false is not working for columns in Table widget

### Steps to reproduce the behaviour:

- Go to link https://release.app.appsmith.com/
- Login into Appsmith through your user credentials.
- Drag and drop table widget 
- Open property pane
- Go to setting of column containing buttons
- Click on Visible JS button
- Type false in the text field of visible
- Column is still visible

### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome, safari]
- Environment [Release]

### Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8dc2179783a74a5aa10086eea7460293-00001.gif)](https://www.loom.com/share/8dc2179783a74a5aa10086eea7460293)

### Screenshot:
https://www.screencast.com/t/y7XlpGXRP

**Comment by somangshu** [comment]
As per the discussion before false is treated as a string here, Putting this inside a `{{}}` binding removes the issue. Closing this for now
