### ISSUE TITLE
[BUG] Able to create multiple organizations with the same name

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#783]
Attachment: https://drive.google.com/drive/folders/1WBCGwFCULq11K0Tj5RsaoqqFvMtz3zQg?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on the cloud.

Issue: Able to create multiple organizations with the same name. 

<img width="344" alt="Screen Shot 2020-09-29 at 1 06 24 AM" src="https://user-images.githubusercontent.com/49346036/94477807-01dd6f00-01f0-11eb-8b4f-89c4bf163cfb.png">

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 I believe org names are not unique in appsmith. @mohanarpit please confirm
