### ISSUE TITLE
[Bug] Deleted page comments are visible, edit mode comments are visible to view mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7830]
## Description
Deleted page comment present on comment pane causes canvas to go in to loading state and refreshing the page shows a resource not found page. 

Another related issue: An edit mode comment is also visible in view mode. This creates a problem because if a comment was added to an unpublished page in edit mode, that should not be visible to view mode as that page is not visible there.

### Steps to reproduce the behaviour:
1. Add a comment on a page and delete the page
2. Go to Comment mode and click on the comment and observe the canvas go in to loading state
3. Refresh the page and observe the resource not found message

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e64347b8d2644724b76d9e49aae019e9-00001.gif)](https://www.loom.com/share/e64347b8d2644724b76d9e49aae019e9)

**Comment by Nikhil-Nandagopal** [comment]
@pranavkanade can you look into this?

**Comment by ramsaptami** [comment]
@nayan-rafiq This issue seems to be fixed. Only have a tiny comment about alignment of text and icon on toast
![image](https://user-images.githubusercontent.com/79509062/140500711-c3de1125-d0ef-41b2-bc29-4de2bfb70a50.png)

**Comment by ramsaptami** [comment]
@nayan-rafiq On the first few tries, there was a comment that displayed "Comment not found" toast. But subsequent tries has brought back the "resource not found" (See videos)

![image](https://user-images.githubusercontent.com/79509062/140503102-303c16cd-1fe5-4b6a-b676-0d91eced015c.png)

https://www.loom.com/share/b8b330f4a8744ac9aa482df6abb87dca

**Comment by ramsaptami** [comment]
Deleted page comment consistently brings up resource not found message hence closing this issue
