### ISSUE TITLE
[Bug] Debug button action only shows contextual menu and does not open the debugger

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7846]
## Description
- [ ] Previously, clicking on the Debug button from the evaluated pane opened up the relevant error on the debugger but now it only pops open the contextual menu. This operation needs to do perform both these actions.

- [ ] Similarly, clicking on an error in the Debugger navigated to the widget but now shows only the contextual menu. This operation needs to perform both these actions.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by akash-codemonk** [comment]
> * Previously, clicking on the Debug button from the evaluated pane opened up the relevant error on the debugger but now it only pops open the contextual menu. This operation needs to do perform both these actions.

This was intentional as there two different events happening a dropdown opens up and then the debugger as well. 

> * Similarly, clicking on an error in the Debugger navigated to the widget but now shows only the contextual menu. This operation needs to perform both these actions.

This seems invalid and this wasn't happening before. This would just navigate the user to another page.

**Comment by ramsaptami** [comment]
@akash-codemonk AKAIR, clicking on Debug would navigate to the widget. There's an example action I've repro'd on an object that has retained the previous action. This issue was raised by Arpit last week regarding concerns of how the debugger is triggered.
https://www.loom.com/share/27e86b06c3224fefb257555cda075ee9

> This seems invalid and this wasn't happening before. This would just navigate the user to another page and the menu would just appear and disappear after navigation.
My bad, the opposite didn't happen before. The documentation pop-up opened up. But would this implementation make sense when there are lots of errors on the debugger but user would have to navigate to the widget?

**Comment by akash-codemonk** [comment]
> > But would this implementation make sense when there are lots of errors on the debugger but user would have to navigate to the widget?

For e.g this wouldn't make sense if we do this on api/query screen debugger. Clicking on an error(of a widget) would show the popup then the user would be navigated away from that screen to a widget. 
The user can navigate to a widget, when the user clicks on the name in the error in the debugger.

**Comment by Nikhil-Nandagopal** [comment]
Closing as this is expected
