### ISSUE TITLE
[Bug] If we hover on table column with large dataset in column then tooltip flickers

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7849]
### Steps to reproduce the behaviour:
1. Drag and drop a table widget
2. Bind the data such that any column has huge data
3. Hover on the data
4. Observe that the tooltip flickers

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/973ad0ac15924ed7844455471fa58d46-00001.gif)](https://www.loom.com/share/973ad0ac15924ed7844455471fa58d46)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_a4mj0)

**Comment by somangshu** [comment]
@SatishGandham what is the right solution, Please point out!

**Comment by aliya-rahmani** [comment]
@vivekverma2312  please assign this to me

**Comment by Nikhil-Nandagopal** [comment]
Hi @aliya-rahmani , 👋  the issue is all yours! Do raise a PR within 4 days and read our [Contribution.md](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md)

**Comment by secure-crypto** [comment]
Hi @Nikhil-Nandagopal , I would like to work on this issue. Can you please assign it to me?

**Comment by utchak160** [comment]
Hey @Nikhil-Nandagopal May I work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@secure-crypto since you asked for it first, I'm assigning it to you

**Comment by Nikhil-Nandagopal** [comment]
@utchak160 please have a look at our other good first issues

**Comment by nikhil-babar** [comment]
@somangshu I would like to work on this issue, plz can you assign me this issue

**Comment by somangshu** [comment]
Greetings @nikhil-babar, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days and let me know here

**Comment by nikhil-babar** [comment]
@somangshu Unfortunately, I am not able to setup the client side of appsmith on my local system.
I have trying to setup it via wsl on windows.
After few seconds of running yarn start it logs following error :

![image](https://user-images.githubusercontent.com/115392530/236626796-c328e694-14bb-466c-a3f6-fafe1e71cb3e.png)

plz can you put some light on this issue

**Comment by jsartisan** [comment]
@nikhil-babar are u on wsl2? or wsl1?
Also, can you check what version of node you are using?

**Comment by nikhil-babar** [comment]
@jsartisan I am using wsl2 and node version: 16.14.0

**Comment by nikhil-babar** [comment]
@jsartisan I have solved that issue, but a new issue has arised:

![image](https://github.com/appsmithorg/appsmith/assets/115392530/8b3ca8d2-3a9d-45a0-adfb-f769648a2683)

how much memory is required to run appsmith client
I have configured wsl upto 4gb ram

**Comment by nikhil-babar** [comment]
@somangshu   This is the detailed image of issue:

![image](https://github.com/appsmithorg/appsmith/assets/115392530/8f21d970-29bc-4116-818c-9124cc9228f3)

**Comment by jsartisan** [comment]
Can you try giving it 8 gb ram? I used to give 8gb ram to wsl2 out of 16gb.

**Comment by nikhil-babar** [comment]
@jsartisan Thankyou for your suggestions, I solved the problem by increasing the swap space of linux distro. It works for few minutes which I guess is enough for solving this issue.
Would approach you if any issue occurs

**Comment by Nikhil-Nandagopal** [comment]
This is now working
