### ISSUE TITLE
[BUG] Rich Text editor Format  changes on deployment

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#785]
Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on the cloud.

Steps to replicate: 
1. Pick 'Rich Text Editor' on page 1 and leave page 2 blank.
2. Deploy

Actual Result:
1. On page 1, in the Rich Text Editor - instead of the text '**This is the initial <b>content</b> of the editor**' , a blank box starts appearing.  (widget Pane)
Attachment: https://drive.google.com/drive/folders/15cOI1LC4sDx1g3c_hrrt3DdZk4sZt3Ok?usp=sharing

2. On the deployed page, also there is change in appearance.
<img width="1790" alt="Screen Shot 2020-09-29 at 10 12 00 AM" src="https://user-images.githubusercontent.com/49346036/94513457-59093100-023c-11eb-9b35-f302e5dfc980.png">

**Comment by visibleajay** [comment]
@Saket2 No. 1 is already raised here `https://github.com/appsmithorg/appsmith/issues/759`.

**Comment by Saket2** [comment]
@visibleajay That's about default text not appearing and this is about an additional blank box appearing on the editor.

**Comment by mohanarpit** [comment]
@all-contributors Please add @Saket2 for their insane contributions to bug reporting and documentation.

**Comment by prapullac** [comment]
Verified the issue and works as expected
