### ISSUE TITLE
[Bug] Appsmith design system improvements on DP (7304)

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7853]
## Description

- [x] #8054
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2076fb10d3fd49dba36336a8dd9189c5-00001.gif)](https://www.loom.com/share/2076fb10d3fd49dba36336a8dd9189c5)

- [x] #8065
![image](https://user-images.githubusercontent.com/79509062/134868297-e13d0022-876a-45c2-ae02-32c1f6881f32.png)

- [x] The arrow for Share button is not the same colour as text and hover mode turns it black on **header**
![image](https://user-images.githubusercontent.com/79509062/135078975-1d2a9091-26fc-4b82-a42a-3946e4dfd60d.png)

- [x] There's no icon while is saving and org members are also not displayed on the **header**. Figma shows -->
![image](https://user-images.githubusercontent.com/79509062/135079461-11700e3c-a7f3-4151-a47c-3483a10cb833.png)

- [x] App options dropdown on **header** has more options on Figma
![image](https://user-images.githubusercontent.com/79509062/135080496-d6f9b1b2-bff1-4101-a75d-f5ce808a0240.png)

- [x] Scroll on **widgets tray** on **entity explorer** on Windows
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bd2808a769b54cb89160d0c2fd3a4498-00001.gif)](https://www.loom.com/share/bd2808a769b54cb89160d0c2fd3a4498)

- [x] #8073

- [ ] Hover mode for Share button is different across the application. Org page, navigation bar view mode & edit mode

- [x] Database name is not sharp cornered
![image](https://user-images.githubusercontent.com/79509062/135114879-e03a2399-f08c-451e-80ea-e81c31a15735.png)

- [x] Alignment of text on **datasources** page
![image](https://user-images.githubusercontent.com/79509062/135115929-729580dc-f313-45a4-a48a-bf77fd3a7f52.png)

- [x] Query name box should have sharp corners
![image](https://user-images.githubusercontent.com/79509062/135116406-5fe43ef2-4ce3-49bc-acd0-9a6f975c933f.png)

- [x] Toggle buttons are off to the side and not centered across application
![image](https://user-images.githubusercontent.com/79509062/135116546-4d4b5eee-6bb2-447c-a3ad-a560eb3881f8.png)

- [x] **Datasource query** setting's tab has input box that's not sharp cornered
![image](https://user-images.githubusercontent.com/79509062/135116791-43be5cac-ef2b-45cb-9934-6b557eefac3f.png)

- [x] There's a gap under the Share button of **header**
![image](https://user-images.githubusercontent.com/79509062/135116943-9d41ef29-5c9c-4212-9b7c-a116c387ad71.png)

- [x] Dropdown icons are inconsistent - need an update about which icon to use
![image](https://user-images.githubusercontent.com/79509062/135117171-21232869-dc05-4fa1-97e7-9554a3045060.png)
![image](https://user-images.githubusercontent.com/79509062/135117213-408d6c61-d0f9-41f7-8ab1-cae87a3a0ab3.png)
![image](https://user-images.githubusercontent.com/79509062/135117507-b7955513-80cc-4c8a-b4ea-92a38689189c.png)

- [x] Change scroll bar on Windows OS on **datasources** page
![image](https://user-images.githubusercontent.com/79509062/135117665-0f3df9e5-201b-42b9-9e64-be0581e572ae.png)

- [x] #8066
       1. Text is truncated at the bottom
       2. Delete should be in red
       3. Copy and move options should be placed next to arrows and aligned with corresponding text
       4. Icons need to be updated
![image](https://user-images.githubusercontent.com/79509062/135118578-c4b4d62d-2b6c-4fbb-bd5d-0f888beabc86.png)

- [x] #8067
![image](https://user-images.githubusercontent.com/79509062/135118933-00fcc949-f87a-46b1-aa3a-56b09714fb22.png)

- [x] No shadow is present on **debugger** and **canvas** boundary

- [x] Entity pane delete option for **widgets** and **datasources** is a maroon shade not red like elsewhere
![image](https://user-images.githubusercontent.com/79509062/135120053-07fda8d8-8947-462e-9a68-06dfe69aa1bf.png)

- [x] Unable to expand datasource from **entity explorer**
![image](https://user-images.githubusercontent.com/79509062/135120360-67456092-81e5-45ee-883a-3f5c4edf35d7.png)

- [x] Icons should be updated. Delete text should be in red on **query page**
![image](https://user-images.githubusercontent.com/79509062/135121192-0202c006-55a6-467d-abfc-2c9ce246060a.png)

- [x] Bin icon needs to be updated for **API datasources**
![image](https://user-images.githubusercontent.com/79509062/135122582-da321bbd-7569-4bb0-a325-0b2ca3ac6a82.png)

- [x] Home page icon is different on **page properties** and on **entity explorer**

- [x] 1. Double line on input box on **firestore** query page
       2. All boxes should be sharp cornered
![image](https://user-images.githubusercontent.com/79509062/135276199-ed7c1f71-1c30-494a-94cc-b3c5d10dc387.png)

- [x] Clicked state of query options is white
![image](https://user-images.githubusercontent.com/79509062/135482832-86894fb2-5722-45ff-bb11-1d7f2835751c.png)

- [x] Hovering over copy button of query on **entity explorer** is removing hover mode. Only clicking on the query copies the query which makes the copy button redundant
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ea65169e04dc4932b33af9aa83c3fa22-00001.gif)](https://www.loom.com/share/ea65169e04dc4932b33af9aa83c3fa22)

- [x] No option to rename JS object from **entity explorer** like how other widgets and datasources can be renamed
![image](https://user-images.githubusercontent.com/79509062/135483998-ef016278-1884-4411-ae71-e2c745cbba82.png)

- [x] Element is still in dark mode on **entity explorer**
![image](https://user-images.githubusercontent.com/79509062/135487764-794f826c-7e3a-4b65-835f-fc3512d31892.png)

- [x] Is the hover on three dots or + on the **entity explorer** meant to be in black?
![image](https://user-images.githubusercontent.com/79509062/135488065-eaaa5ca9-b13e-4d0a-a26f-e4fed45a5534.png)

- [x] Organization creator is displayed as **Owner** on Figma but it's **Administrator** on app. Should it be admin?

- [x] Input box should should have borders on all sides
![image](https://user-images.githubusercontent.com/79509062/135569651-7ed558a0-5d11-46e8-9518-795ab18b20e4.png)

- [x] There's a gap between the input box and icons and the border of the **header**
![image](https://user-images.githubusercontent.com/79509062/135570044-fabfaa13-fd45-4eb4-8208-e6c1dd6142a4.png)

- [x] Center the box the CTA icon
![image](https://user-images.githubusercontent.com/79509062/135570122-1fd4cd82-1da9-4ff9-b151-c9d064d96a35.png)

- [x] There's no hover state for the help icon on he**ader**
![image](https://user-images.githubusercontent.com/79509062/135570883-8751c96e-c683-4c0e-ae26-f6912845b35e.png)

- [x] Needs to be center aligned from top and sides. Do we keep the "**Import Application**" to the left or center?
![image](https://user-images.githubusercontent.com/79509062/135576055-13ec94fd-3959-4d5f-8952-225b33a64175.png)

- [x] Hover over the `?` icon next to **Dependencies** of **entity explorer** and you'll see this tooltip which has a completely different design to the rest of the application
![image](https://user-images.githubusercontent.com/79509062/135576470-39bfef50-d358-4eac-b7c6-2cad4f6d924a.png)

- [x] When present on the **Datasources** page, widgets CTA on entity explorer is not disabled so there's a strange behaviour that occurs on clicking this button
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c44e8b97794b4d8cbbd824db9a1c54c8-00001.gif)](https://www.loom.com/share/c44e8b97794b4d8cbbd824db9a1c54c8)

- [x] Double lines are present on all **datasources** pages
![image](https://user-images.githubusercontent.com/79509062/135589127-c071505b-d0b5-4ca6-bdcd-152a3ecc1970.png)
![image](https://user-images.githubusercontent.com/79509062/135589177-85a13515-cc31-4a1f-87d3-d81d8a812aa8.png)

- [x] Double lines are present on all **query page** input boxes
![image](https://user-images.githubusercontent.com/79509062/135589463-72fdc4ac-27a2-4b56-af44-35762a9a20b8.png)
![image](https://user-images.githubusercontent.com/79509062/135589390-5c862be0-af9b-448e-ae36-c9540a444740.png)

- [x] Text trimmed on search bar of **entity pane**
![image](https://user-images.githubusercontent.com/79509062/135589023-0650dadd-f58d-49fa-afaf-c9f9f10cfa2a.png)

- [x] CTA underline jumps from under the text to the line below for **datasources**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/32209f5a253848d78580a203d3491faf-00001.gif)](https://www.loom.com/share/32209f5a253848d78580a203d3491faf)

- [x] **Debugger** error state
![image](https://user-images.githubusercontent.com/79509062/135589670-175d8a05-6f22-43f7-97c7-71bab65926ac.png)

- [x] **Share button from header** - typo and "shareable" should be in lower case
![image](https://user-images.githubusercontent.com/79509062/135595380-d54f1410-4022-464a-8ea3-1786f6cbce18.png)

- [x] On **org members page**, when members are loading there's a point when the scroll bar blinks in and out and this causes the modal to shrink and expand - can't repro this always but happens when it's loading members for the first time and there are lots of members on the organization (could be a windows exclusive issue because of the scroll)

- [x] App logo for ElasticSearch should be updated

- [x] There are coloured logo's only for databases and API query but nothing else on the entity explorer which makes it look very odd
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/24726c6e201e4172930be71183b44d8e-00001.gif)](https://www.loom.com/share/24726c6e201e4172930be71183b44d8e)

- [x] Text looks hazey, not focused
![image](https://user-images.githubusercontent.com/79509062/135636839-84378445-8b58-44b0-b0ff-6e52bb7d9e72.png)

- [x] Awkward spacing on the members list on **header**
![image](https://user-images.githubusercontent.com/79509062/135660140-2741c5d9-47bb-441c-9e23-7078321596b7.png)

- [x] There's a click icon that appears on visible and home icon on **page properties** but they are not CTA icons

- [ ]  Colour of settings, copy and delete icons are different on **page properties**
![image](https://user-images.githubusercontent.com/79509062/135851799-f3f422c7-6676-48b9-8212-4a3a750ccc7e.png)

- [ ] Share icon is different on new header and needs to be updated on **home page**
![image](https://user-images.githubusercontent.com/79509062/135854388-55564c95-cf54-4973-9d93-1c21f7cf6f85.png)

- [ ] Add top and bottom padding for Deploy, Share and Edit App buttons on **header**
![image](https://user-images.githubusercontent.com/79509062/135875221-609781cc-ec1e-42e8-95e9-1f323fd52c01.png)
![image](https://user-images.githubusercontent.com/79509062/135875235-cf30d104-cb2b-4ff0-8894-bbcd35b9e5c0.png)
![image](https://user-images.githubusercontent.com/79509062/135883596-2e8764a1-10ac-485a-8150-d7fcfbe7692b.png)

- [x] Pressing enter on the API datasource URL field causes control to move to the next line instead of exiting the box

- [x] #8896
![image](https://user-images.githubusercontent.com/79509062/135882235-ae54c715-9ae0-433d-9da0-fadb7b91a27a.png)

- [ ] Organization image on **Org settings** page trims off the boundary when image is loaded
![image](https://user-images.githubusercontent.com/79509062/135899277-b71de990-784c-4282-bbf5-2e9071f52a41.png)

- [ ] The arrow size is very small
![image](https://user-images.githubusercontent.com/79509062/136178708-ebce0e0b-913d-4e69-a244-9ee4a6e8c054.png)

### Potential design changes:
- [x] More padding on the left of the text since it looks shabby right now. Also increase the shadow on the dropdown since it's visually cluttered.
![image](https://user-images.githubusercontent.com/79509062/135081062-56ba352f-9449-4fb3-9cd8-4ec9cf7daf46.png)

 - [x] Scroll bar design on Comment mode for Windows
![image](https://user-images.githubusercontent.com/79509062/135085321-bdef8505-5a28-4650-a71f-4fca40164252.png)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by ramsaptami** [comment]
Reopening this issue since there are pending task that still need to be picked up (only major tasks were picked for immediate fix). Also, reassigning this to prod label since these are now on master.

**Comment by hiteshjoshi** [comment]
https://github.com/appsmithorg/appsmith/issues/7852

**Comment by momcilo-appsmith** [comment]
@albinAppsmith You should consult with @Debsourabh and Emy (will be added to our Github soon) when it comes to Design System of our application in the future.

**Comment by albinAppsmith** [comment]
Closing this ticket and pending tasks are being tracked in [#10186](https://github.com/appsmithorg/appsmith/issues/10186)
