### ISSUE TITLE
[Bug] Clicking `+` widgets does not open widgets tray on entity explorer

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7854]
## Description
Clicking `+` widgets does not open widgets tray on entity explorer

### Steps to reproduce the behaviour:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d7890a74e9464de7b2582ddbcebc44b0-00001.gif)](https://www.loom.com/share/d7890a74e9464de7b2582ddbcebc44b0)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

**Comment by albinAppsmith** [comment]
@ramsaptami This is fixed and deployed in DP

**Comment by ramsaptami** [comment]
Fixed and tested
