### ISSUE TITLE
[BUG] Inconsistent Active Page after deploying application.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#786]
## Description
Active Page isn't a home page when opening the app from `View Application` button shown in confirmation `modal`.

### Steps to reproduce the behaviour:
1. Create a new Page `page2.
2. Deploy app, keeping the `page2` as active in `editor`. Though sometime it happens when `Home` page is active.
3. View Deployed App in `normal` and `incognito` mode using "View Application" button shown in confirmation `modal`.
4. See `inconsistency`

[Video In Action.](https://drive.google.com/file/d/1luBctbEh29Ivr0CxUW_-9f278F_z3TP5/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOS 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay this is expected. On Deploying, we always start from the last seen page and not the home page so that it's obvious to a user what change he just deployed. If you open the app directly from applications page, it will open the home page first
