### ISSUE TITLE
[Bug] Audio widget turns into an Video when any of the video url is passed in the audio widget url field 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7865]
## Description
Audio Video - It is observed that when any of the video url is passed into the audio widget url field the widget turns into video mode

Expected Result:
The audio widget should still remain as an audio format when video url is passed

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the release/Prod environment 
2. Drag and drop audio widget 
3. Pass any of the video url in the audio widget url field and observe

Videolink:
https://loom.com/share/a68c68ba7f6749f5931971b727e5e6d9

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [ chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
As suggested by @aswathkk this will need a new audio widget package, hence this stands on a lower priority.

**Comment by Nikhil-Nandagopal** [comment]
Non issue, we'll wait for user feedback on this one
