### ISSUE TITLE
[Enhancement] To add Disable functionality in the audio widget

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7866]
## Description
Audio Widget - Release/Production - Currently there is no option to disable audio widget

Expected Result:
To add disable toggle functionality in the audio widget

### Steps to reproduce the behaviour:
1. Launch Appmsith app in release or prod environment 
2. Drag and drop audio widget 
3. Open property pane and observe

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-27 at 6 06 19 PM" src="https://user-images.githubusercontent.com/35128442/134909566-63638a2d-336b-4644-bd2e-def8d0f6ecad.png">

**Comment by somangshu** [comment]
There is nothing in our control which need to be disabled here, Video widget show us the same, Closing this for now.
