### ISSUE TITLE
[Bug]Audio option hidden on edit mode

### ISSUE THREAD

**Issue by UXFalcon** [appsmithorg/appsmith#7868]
## Description

**Audio option hidden on edit mode has been going under the main navigation pane** 
the option working fine on View mode though
![Capture](https://user-images.githubusercontent.com/90375262/134911255-21160d47-9f39-47f9-9879-c4b2cd7e3140.PNG)

**Comment by somangshu** [comment]
Found out from [here](https://github.com/cookpete/react-player/issues/1238) that the issue with the underlying package, and is existing for the video player as well. This was never caught because probably user always use the youtube player which resolves the issue because of their own custom implementation. 

![Screenshot 2021-09-27 at 7 18 16 PM](https://user-images.githubusercontent.com/11089579/134921758-b292e5ca-899f-4fe1-91d0-57ee8d4b90c8.png)

☝️  the above example is of the video widget 

To fix this we might want have to revisit the package used. De-prioritising for now.

**Comment by jsartisan** [comment]
@somangshu Assigning this as the good first issue as we can't really do much to fix it but hide that context menu

`controlsList="nofullscreen nodownload noremoteplayback noplaybackrate "`

**Comment by krishguptadev** [comment]
How can I fix this issue?

**Comment by Rutam21** [comment]
@somangshu I would love to work on this ticket. Feel free to assign this to me.

**Comment by somangshu** [comment]
Greetings @Rutam21, thanks for showing interest 🎉 , This is all your. Assigning this to you now. Please let me know if you have any questions.

@krishguptadev please let me know if you are still looking for issues, you can also use the `hacktoberfest` label to filter these issues, Please let me know, Ill make sure to assign them to you.

**Comment by Rutam21** [comment]
@somangshu It would be great if you can point me to the place where the code for the video player stays and let me know the way to test this locally after fixing it.

**Comment by somangshu** [comment]
@Rutam21 all our widgets are compartmentalised and you should be able to find the one you are looking for in there respective folders, this issue is related to the audioPlayer.

**Comment by jsartisan** [comment]
@Rutam21 The file is `src/widgets/AudioWidget/component/index.tsx`
We are using react-player for rendering the component. So you will need to find a way to pass controlsList to the `<ReactPlayer />`.

**Comment by jsartisan** [comment]
Also, check out https://github.com/CookPete/react-player/issues/232#issuecomment-328504894

@Rutam21

**Comment by MitAbhay** [comment]
Can you Assign this issue to me? @somangshu

**Comment by somangshu** [comment]
@MitAbhay this issue is already assigned to another contributor. Kindly check other issues under the label hactoberfest. Feel free to tag me. I'll assign it to you. Happy hacking 😁

**Comment by somangshu** [comment]
@AR10X that'd be great, Assigning this to you now. Do raise the PR in the next 4 days. 🙂

**Comment by somangshu** [comment]
@appsmithorg/qa please verify this with caution, this was merged with failing tests
