### ISSUE TITLE
[Bug] Syntax Error - 'Unexpected token' error is received when Audio widget OnEnd action is set to download 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7869]
## Description
Audio Widget - Release/Production - It is observed that Syntax Error - 'Unexpected token' error is received when Audio widget OnEnd action is set to download and leaving file name with extension and file type empty 

Expected Result:
If the file name and file type is not passed - valid error message can be displayed instead of 'Syntax error - 'Unexpected token' error

### Steps to reproduce the behaviour:

1.Launch Appmsith app in the release/Prod environment 
2.Drag and drop Audio Widget 
3.Open property pane 
4. Set OnEnd action to download and do not pass file name with extension
5. Set the file type as Plan text
6. Change the file type to default option - Select file type(Optional)
7. Click on start button 
8. Wait till play ends and observe

Videolink:
https://loom.com/share/718caf9f1f474efa9a7a58d6906971ea

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by aswathkk** [comment]
@YogeshJayaseelan This seems like a syntax error you made in the `onEnd` field.
You cannot type `download(,,)`.
You can check the [documentation for the download function](https://docs.appsmith.com/framework-reference/download#download) if needed.
