### ISSUE TITLE
[BUG] Image widget : base 64 encoding doesn't work

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#787]
Attachment: https://drive.google.com/drive/folders/1G-Kcr6iXn-P_QnsrXgnAjUiD9AFN8FdK?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on the cloud.

Steps to replicate:
1. Pick Image widget
2. In the image, put a image URL (e.g. https://static.techspot.com/images2/news/bigimage/2018/09/2018-09-04-image-6.png )
Result: Image starts appearing

3. Now convert this image URL to base 64 
Result: Image can't be seen.

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 Closing this because the video shows usage of the base64 of the image URL not the base64 of the image.
