### ISSUE TITLE
[Bug] The OnPlay and OnPause actions message are displayed on clicking on forward or backward on the audio dragger 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7870]
## Description
Audio Widget - Release/Production - It is observed that the OnPlay and OnPause message are also displayed when the user clicks front or back on the audio dragger 

Expected result:
OnPlay message should only display on clicking on play button and OnPause message should display only on clicking pause button 

### Steps to reproduce the behaviour:

1. Launch App smith app in the release/Production environment 
2. Drag and drop audio widget 
3. Set OnPay to show message 
4. Set OnPause to show message 
5. Click on play button and click backward or forward on the audio dragger and observe

Videolink:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/91a3db321fef4b3b9aa239bcf2ab02b7-00001.gif)](https://www.loom.com/share/91a3db321fef4b3b9aa239bcf2ab02b7)

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by Nikhil-Nandagopal** [comment]
Non issue
