### ISSUE TITLE
[Enhancement] Need an option to center align text and icon

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7871]
## Summary
Currently, when an icon is selected for any widget, there are only right and left alignment options. It would be nice to have a center alignment of the icon and text. 

## Motivation
![image](https://user-images.githubusercontent.com/79509062/134921769-bce2b0ac-b134-422b-832a-78ae03ecf16f.png)

**Comment by somangshu** [comment]
duplicate of #7913
