### ISSUE TITLE
[Bug] MultiSelect Default Value return value is not string.

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#7872]
## Description

The expected structure of multi select values are `Array<{ "label": "string", "value": "string" }>` and if we do INT and FLOAT on the value part the widget automatically converts it to string.
The same is not being followed on Default value. For e.g. if I put INT or FLOAT on default value, it doesn't automatically converts to string.

Behaviour of data type across the widget should have same expected results. 

<img width="698" alt="Screenshot 2021-09-27 at 9 02 43 PM" src="https://user-images.githubusercontent.com/217911/134939462-65e27ced-319a-4098-bf3b-99f45e58177e.png">

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
@Tooluloope @SatishGandham this is happening in case of the select widget too. The widget need to accept both string and int value, This failed because of a change in #7698, We need to make sure how to cover the cases here.

**Comment by SatishGandham** [comment]
We are reverting the validation changes and continue to support numbers and boolean values.
