### ISSUE TITLE
[Bug]When user add an extra row and then try to add data in where clause the rows get deleted 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7874]
## Description When user add an extra row and then try to add data in where clause the rows get deleted 

[What happened]when the user add multiple where clause then try to add data the line items deletes automatically

### Steps to reproduce the behaviour:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f3d487567ee64ff4b20e11e0106f2f81-00001.gif)](https://www.loom.com/share/f3d487567ee64ff4b20e11e0106f2f81)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser  chrome
- Environment release

**Comment by nidhi-nair** [comment]
Closing as this has already been resolved.
