### ISSUE TITLE
[Bug]-[22500]:The evaluated value is displayed as undefined in google sheets

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7875]
## Description

[What happened]The evaluated value is displayed as undefined

### Steps to reproduce the behaviour:

![image](https://user-images.githubusercontent.com/45958978/134951098-5c681a15-4e7a-4c40-8b61-d66671e74413.png)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser chrome,
- Environment  release

**Comment by bharath31** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1800 |
| Effort (months)  | <<number>> |

**Comment by bharath31** [comment]
This is not reproducible anymore since the Sheet Name input is now a dropdown with static values
