### ISSUE TITLE
[Bug]Document update for google sheet

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7876]
## Description 
The old image is displayed when the user clicks on the documentation link from the google sheet query pane 

### What happened
When the user clicks on the documentation link from the query pane, the Image in the doc is very old it needs to be updated.

In order to do this, please create a contribution to our documentation repository by following the [Documentation Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)

![image](https://user-images.githubusercontent.com/45958978/134951923-2d9619ba-592f-4c86-a6b9-a12ea70f320e.png)

### Important Details

- Version: Cloud 
- OS: MacOs
- Browser chrome
- Environment release

**Comment by sakshamgurbhele** [comment]
I am interested in this issue, let me know if I can go ahead :)

**Comment by nidhi-nair** [comment]
Please go ahead @sakshamgurbhele, I have assigned this issue to you. Please make sure to read our [Documentation Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before you create a PR for this change! 😄

**Comment by kunals131** [comment]
I want to work on this issue, please let me know if i can.

**Comment by sakshamgurbhele** [comment]
Update: I am working on this, I will make a PR soon.

**Comment by AmiShaaaa** [comment]
I am interested ! Let me know if I can.

**Comment by j1gy45u** [comment]
I'd love to work on this, please let me know if i can!

**Comment by stuck-in-a-conundrum** [comment]
I would like to work on this issue!

**Comment by nidhi-nair** [comment]
Thanks for expressing an interest in the issue folks! This has been solved in https://github.com/appsmithorg/appsmith-docs/pull/233

Please take a look at any of our other unassigned [Good first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) for possible contributions you can make to our repo. 🙂
