### ISSUE TITLE
[Bug]The "Mark all as read" button is not displayed in the notification section on the safari browser

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7877]
## Description

[What happened] "Mark all as read" button is not displayed in the notification section on the safari browser

### Steps to reproduce the behaviour:
![image](https://user-images.githubusercontent.com/45958978/134952850-718c8cc3-f59b-4484-8e87-94551760ddfc.png)

### Important Details

- Version: [Cloud]
- OS: macOS
- Browser chrome
- Environment release

**Comment by eagleera** [comment]
Hi! can I work on this one?

**Comment by RakshaKShetty** [comment]
@pranavkanade and @nayan-rafiq can you help on this

**Comment by pranavkanade** [comment]
@eagleera please go for it

**Comment by eagleera** [comment]
I was trying to generate some notifications but I didn't find a way to do it, do you know some steps I can do to create a notification so I can test?

**Comment by RakshaKShetty** [comment]
Hi @eagleera  this will no longer be valid with our new release as such we're closing this issue :)
