### ISSUE TITLE
[BUG] Table sorting for col id is inconsistent.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#788]
## Description
Table sorting for integer col. id is inconsistent. The sorted value is calculated keeping the id col. as string.

Sample JSON.
`[{"id": 1, "name": "vijay"}, {"id": 2,"name": "ajay"}, {"id": 11, "name": "Rocky"}, {"id": 12, "name": "raman"}, {"id": 3, "name": "ranvijay"}]`

### Steps to reproduce the behaviour:
1. Add Table Widget with Sample `Json` data.
2. Sort id column by clicking over it.
3. See inconsistency.

**Ascending Sorting**
<a href="https://ibb.co/3y1HJBB"><img src="https://i.ibb.co/BVLR1qq/ascending-sorting.png" alt="ascending-sorting" border="0"></a>

**Descending Sorting**
<a href="https://ibb.co/PFzpvPV"><img src="https://i.ibb.co/QpjB3Tx/descending-sorting.png" alt="descending-sorting" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOS 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Saket2** [comment]
<img width="595" alt="Screen Shot 2020-09-29 at 11 37 34 AM" src="https://user-images.githubusercontent.com/49346036/94519492-367d1500-0248-11eb-9fee-1fd37eb4679b.png">

That's probably because Attributes are taken as 'text'.

**Comment by visibleajay** [comment]
@Saket2 Updating `data type` for id col. to `number` removed the sorting issue. Thank You for the clarification!.
