### ISSUE TITLE
[Bug] Unable to open property pane for any of the widgets in canvas when two audio widget is placed nearby and resized

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7881]
## Description
Audio Widget - Release/Production - It is observed that when the two audio widgets are placed nearby and on resizing the widget user is unable to open any of the property pane unless the page is refreshed 

Expected Result:
Placing widgets nearby and resizing user should be able to open property pane

### Steps to reproduce the behaviour:

1. Launch Appmsith app in release or Prod environment 
2. Drag and drop few widgets to the canvas
3. Drag Audo widget
4. Copy audio widget and paste it on the canvas
5. Move the copied audio widget near to the Audio1 Widget
6. Resize the copied audio widget - Refer video and observe

Video link:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/48b46dd944934ce5af934af6bf5412f4-00001.gif)](https://www.loom.com/share/48b46dd944934ce5af934af6bf5412f4)

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by sbalaji1192** [comment]
Audio widget doesn't relay mouse events up the dom tree. - https://jsfiddle.net/aftvoy2q/1/
Issue happens when we try to resize a widget and release mouse over audio widget. since audio widget is not relaying the mouseup event, we're still in resize flow, hence property pane button is not shown.

**Comment by Tooluloope** [comment]
Working Fine.

**Comment by wealthz01** [comment]
Why u on my what’s app
