### ISSUE TITLE
[Bug] Pressing `esc` appends `isCommentMode=false` to the url

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#7887]
## Description

When a user is on editor, pressing `esc` appends `isCommentMode=false` to the url.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to editor.
2. press `esc`.
3. observe that `isCommentMode=false` is added to url.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by areyabhishek** [comment]
Hi! I'm interested in working on this issue. Could you assign this to me?

**Comment by mohanarpit** [comment]
It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

**Comment by eagleera** [comment]
Hi! can I have this assigned to me? I just created the [PR](https://github.com/appsmithorg/appsmith/pull/8135)

**Comment by areyabhishek** [comment]
Done! I'll check the pr tomorrow
