### ISSUE TITLE
[Task] Collaboration experience for the end-user

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#7888]
# Objective
The collaboration feature that we currently have is made for the developers/editors. We want to make the experience pleasant for the end-user as well. This includes onboarding as well as navigation. 

# Current problems
- The mode buttons in the navigation are not in the right place
- The GIFs in the onboarding are low quality

# Requirements
| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Redesign the current collaboration part in the navigation bar (end-user only)  | - | High | - |
| Add new images for the collaboration process (current ones are low quality) | -  | High  | Create a new account and go through this process as a new end-user |
| Close button for the tutorial cards that adhere to design system | -  | High  | - |

# Out of Scope
List the things that are out of cope or might be revisited after the first release.
- Changing the icons
- Redesigning the navigation bar completely
- Redesigning the way that the onboarding works currently.

# Developer Handoff Document in Figma
Link to the developer Handoff Document: 

# RACI matrix

| Label | Value | 
| ------------- | ------------- |
| Responsible |  @UXfalcon |
| Accountable | @momcilo-appsmith  |
| Consulted |  @areyabhishek |
| Informed |  |

**Comment by hiteshjoshi** [comment]
@momcilo-appsmith been a while with this, I think we have changed direction since then? Closing this but feel free reopen and update with new information.
