### ISSUE TITLE
[Enhancement] Action label for "Show Message" should be "Show Alert"

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#7903]
## Summary

on the property pane action, the label says "Show Message" where as the actual function behind it is "showAlert()"

## Motivation

I think this has to be consistent to reduce cognitive load for the user.

## Additional Context
![Screenshot 2021-09-28 at 8 44 17 PM](https://user-images.githubusercontent.com/10436935/135116201-6535a708-b814-4c31-b597-58338416227e.png)

![Screenshot 2021-09-28 at 8 45 03 PM](https://user-images.githubusercontent.com/10436935/135116231-ad6ee109-a5d1-4ced-8682-0a7ce52d973d.png)

**Comment by MartinTuroci** [comment]
Hi, can I take on this issue?

**Comment by aswathkk** [comment]
@MartinTuroci Thanks for showing interest. Unfortunately, we are not yet decided to go with this change.
Please do check other issues which are tagged as [Hacktoberfest](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest). We are happy to assign those to you.

**Comment by aswathkk** [comment]
We are thinking of changing the function `showAlert()` to `showMessage()` since the alert in the browser is having a different UI. The challenge in that would be to write migrations so that the existing applications wouldn't be breaking. We won't be taking that path since a lot of users are using showAlert in their production workflows.

Another approach is to introduce whole new function named `showMessage()` and deprecate the function `showAlert()`. But, this deprecation infrastructure is not in place yet.

So, we will work on this issue only when a generic solution to deprecation and communication of the deprecation are in place.

**Comment by somangshu** [comment]
@MartinTuroci 👋 , this issue is a little more involved and not up for grabs, Can you check issues under the Hacktoberfest to find issue you are interested in, Feel free to tag me so that I can assign them to you

**Comment by rimildeyjsr** [comment]
This is a one line change, will add this to my PR
