### ISSUE TITLE
Hacktoberfest Content Submission

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#7904]
## Hacktoberfest Content Submission
This issue was created to track content submission for Hacktoberfest. Valid content submissions include:
- Templates applications
- Written content i.e blogs, tutorials, how-to guides
- Video content i.e tutorials, how-to guides

### Template Applications
1. [Signup for Appsmith](https://app.appsmith.com/) and build a template application
1. [Ensure that your application is public](https://docs.appsmith.com/core-concepts/access-control#public-apps)
1. [Register for the Appsmith Hacktoberfest event](https://bit.ly/appsmith-hacktoberfest-registeration)
1. Add a comment that links to your application on **this GitHub issue**. Your comment should include the app name and link

### Written Content
1. Create a personal blog post for the article (i.e dev.to or Hashnode)
1. [Register for the Appsmith Hacktoberfest event](https://bit.ly/appsmith-hacktoberfest-registeration)
1. Add a comment that links to your article on **this GitHub issue**. Your comment should include the article name and link

### Video Content
1. Create a video content and upload it to a streaming service (i.e youtube.com)
1. [Register for the Appsmith Hacktoberfest event](https://bit.ly/appsmith-hacktoberfest-registeration)
1. Add a comment that links to your video on **this GitHub issue**. Your comment should include the video name and link

**Comment by Nikhil-Nandagopal** [comment]
@cokoghenun how will users get their PR contribution like this?

**Comment by cokoghenun** [comment]
Oh sorry, we only had in mind receiving Appsmith swag when this was created. @Pranay105 has a better idea so I'll delete this to avoid confusion
