### ISSUE TITLE
[BUG] Text info box in Table Widget is moving out of the screen for large text.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#791]
## Description
Text Info box in `Table Widget` is moving out of the screen for large text.

<a href="https://ibb.co/g6fQ1YS"><img src="https://i.ibb.co/4JXCyk8/Table-Info-box.png" alt="Table-Info-box" border="0"></a>

### Important Details
 - Version: Cloud
 - OS: MacOS 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by Saket2** [comment]
If https://github.com/appsmithorg/appsmith/issues/755 helps.

**Comment by visibleajay** [comment]
@Saket2 In this, the hover text box is going out of the screen if the widget have large input text.

**Comment by Nikhil-Nandagopal** [comment]
Seems related to #792 . Looks like a different effect but the root cause is the same
