### ISSUE TITLE
[Bug]-[4000]:Fix inconsistent copy in Appsmith product

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#7910]
There are areas of the product where we don't follow sentence case.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4000 |
| Effort (months)  | 0.5 |

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
