### ISSUE TITLE
[Feature] Change Administrator & Developer role to Global, and add new Editor role at the Application Level

### ISSUE THREAD

**Issue by developer-uhwi** [appsmithorg/appsmith#7912]
## Summary

One paragraph description of the feature.
**Remove the ability for regular users to create organizations and applications.** 

1. Administrator & Developer roles should be at the global level, giving them the abilities to build apps and create organizations  as usual.
2. Editor & Viewer roles (Editor would be a new role) will have access at the App level. This new Editor role gives the ability for the user to edit the application, this replaces the developer role at the application level. The viewer role remains as is,  as a user who is only able to interact and use the application as intended.
3. Administrative interface to allow the administrator to view all organizations, applications and users.
4. Administrative interface to allow the administrator to change a user global role e.g. Administrator or Developer.
5. Ability to limit or apply storage quota to applications/organizations both for uploaded files and data created.
6. Ability to apply user limits for an organization i.e. the number of users allowed to register/invited in an organization.

## Motivation

Why should this be worked on? What problems or use cases does it solve or
improve?
Most if not all users will be application viewers and NOT creators. Giving the users who do not have any knowledge of building apps, will cause apps to be built which are not being used and possibly lead to a user INADVERTENTLY crashing system because of misuse.

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.
These changes would facilitate better usage in the organization.

**Comment by Nikhil-Nandagopal** [comment]
@developer-uhwi thank you for the feature request! This issue is being tracked as part of #3317 
Just to address your concern, app viewers cannot build apps inside your org and no app that they create should be bale to crash your system
