### ISSUE TITLE
[Feature][Enhancement]Keyboard interactions for dropdown component

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#7914]
## Summary

Currently, the Appsmith design system's dropdown doesn't support keyboard interactions. It should support following ,

- [ ] `Tab` focus.
- [x] `Up` and `down` arrow key interaction to select an option.
- [x] `enter` key interaction to choose a particular option.

## Motivation
This changes will help user to fill out welcome form using just keyboard.

**Comment by kocharrahul7** [comment]
Issue appears to have been fixed here

https://github.com/appsmithorg/appsmith/pull/11420
