### ISSUE TITLE
[BUG] Hover box is blinking for Table Widget for ultra large text

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#792]
## Description
Hover info box starts blinking for table widget for ultra large text.

[Video In Action.](https://drive.google.com/file/d/1IT7NUaph4TK8j3_Nn7FEPvJyiVbJ23Sl/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOS 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by riodeuno** [comment]
A potential fix for this issue is to add an appropriate `position` prop to the `Tooltip` component which renders the full text on hover. [Documentation for the original component](https://blueprintjs.com/docs/#core/components/tooltip)

**Comment by Nibba2018** [comment]
Hi @visibleajay , is this issue still open? I would like to work on this.

**Comment by mohanarpit** [comment]
@Nibba2018 Welcome to Appsmith! 🎉 Go for it! I'd request you to please raise a PR within 2 days.

Also, feel free to participate in [Appsmith's Challenge](https://github.com/appsmithorg/appsmith/discussions/863) during Hacktoberfest. Feel free to tag your friends and invite them to contribute to the project.

**Comment by Nibba2018** [comment]
Thanks @mohanarpit !

**Comment by visibleajay** [comment]
@mohanarpit @Nibba2018 If open, would like to take this up...

**Comment by Nibba2018** [comment]
@visibleajay okay go for it.

**Comment by hetunandu** [comment]
@visibleajay Assigned

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay were you able to get around to this fix?

**Comment by visibleajay** [comment]
@Nikhil-Nandagopal Thank You for the response. Currently occupied with other work. Need time to do it.

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay no problem! I'm unassigning you till you find the time :) Looking forward to future contributions

**Comment by mohanarpit** [comment]
@all-contributors Please add @visibleajay for their invaluable contribution towards bug reporting and documentation.
