### ISSUE TITLE
[Bug] If triggeredRow is getting deleted then the next index in table is getting selected as triggeredRow

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7920]
### Steps to reproduce the behaviour:

1. Create a CRUD UI app
2. drag and drop a text widget
3. Bind the widget with `triggeredRow`
3. Now click on delete action of the table
4. Observe that after the row gets deleted the next index in the table is getting selected

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7c30799a57e64de3a88c13e419f41e4c-00001.gif)](https://www.loom.com/share/7c30799a57e64de3a88c13e419f41e4c)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
The triggered row needs to unset on delete of the row, We might need a primary key defined by the user for this.

**Comment by SatishGandham** [comment]
Fixing #4990 might solve this problem automatically.
