### ISSUE TITLE
[Bug] When options are empty, the dropdown has this small box

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#7921]
## Description
<img width="479" alt="Screenshot 2021-09-29 at 10 26 04 AM" src="https://user-images.githubusercontent.com/103687/135213026-a57437d1-3ae9-4908-a064-8ad0edef89b7.png">
reproduce this behaviour, include console / network logs & screenshots

### Steps to reproduce the behaviour:
Open a select widget when there are no options

### Important Details

- Version: All
- OS: MacOSX
- Browser: Chrome
- Environment: All

**Comment by Bhavin789** [comment]
Hi @riodeuno , I would like to work on this issue. Can you please assign this to me? Thanks!

**Comment by Bhavin789** [comment]
Hello @riodeuno , have added a related PR [here](https://github.com/appsmithorg/appsmith/pull/8357). Thanks!
