### ISSUE TITLE
[Task] Improving status of datasource created

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#7936]
'Datasource Connected' seems to be a constant heading to the datasource view pane. Such a heading does not make sense when the datasource is invalid. 

We should show  datasource state appropriately (connected/ invalid) 

Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Create any DB datasource.
2. Do no fill any fields, just go back to the datasource view pane in the least valid state.
3. create a query with created datasource
4. go to created datasource from entity explorer (left navigation bar)
5. datasource page shows "Datasource Connected"

Ref- #2754

**Comment by vj-codes** [comment]
@ApekshaBhosale I have created a PR #8028
Please have a look, thankss in advance:)
