### ISSUE TITLE
[Bug] user is able to select radio option beyond the selection area

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7937]
## Description
Release - It is observed that user is able to select radio option beyond the selection area - This happens in both edit and deploy mode

Expected Result:
user should be able to select radio option only by clicking on the radio icon

### Steps to reproduce the behaviour:

1. Launch appmsith app in the release environment 
2. Drag and drop radio button 
3. Expand the widget Horizontally 
4. Try to click anywhere on the straight to radio icons

Videolink:
https://loom.com/share/db3769f166f44d47bb973bce53fefaee

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
I think this is acceptable and provides a good UX
