### ISSUE TITLE
[Bug] The vertical scroll bar in the entity explorer is not visible clearly 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7940]
## Description
Release - It is observed that the vertical scroll bar in the entity explorer is not visible clearly because the background colour of entity explorer and the scroll bar colour are same.

Also, there is an horizontal scroll bar in entity explorer which is not required 

Expected Result:
Vertical scroll bar should be visible clearly and the horizontal scroll bar is not required for the entity explorer 

### Steps to reproduce the behaviour:

1.Launch Appmsith app in the release environment 
2.Open any of the app
3.Try to scroll up and down in the entity explorer and observe 

Videolink:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/aa24c131a4f148fb9f1347fd29ade1a7-00001.gif)](https://www.loom.com/share/aa24c131a4f148fb9f1347fd29ade1a7)

### Important Details

- Version: [11.3]
- OS: [MacOS Big Sur]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by Jaideep07** [comment]
Hello, Could @YogeshJayaseelan you pls assign me this issue, I would like to work on this pls.😃

**Comment by sbalaji1192** [comment]
Hey @Jaideep07, Thanks for showing interest in this issue.
It appears that, this issue has been fixed along with few other changes that went in recently.

Please find another [Good first issues](https://github.com/appsmithorg/appsmith/labels/Good%20First%20Issue) to contribute to Appsmith. :)
