### ISSUE TITLE
(JS-0102) Use let instead of var & Prefer var declarations be placed at the top of their scope

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#7941]
## Description
Declare variables at the top of their scope as it improves code readability, performance and also helps in code navigation.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0102/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0102/occurrences/)

**Comment by aanchal-fatwani** [comment]
Hi, I would like to work on this issue. Please assign the same.

**Comment by samyakjain10** [comment]
Hi, I would like to work on this issue.

**Comment by rushalikhilrani** [comment]
hey! I  would love to work on this issue. Please assign it to me

**Comment by Rishabh-Rathod** [comment]
@rushalikhilrani & @aanchal-fatwani 

Hey👋🏼,  thanks for showing interest in this issue.

Unfortunately, this issue is already taken. Do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+label%3Ahacktoberfest)

Looking forward to seeing your contributions :)
