### ISSUE TITLE
[Bug] Alignment of the Multitree-select widget in the entity explorer is improper 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7944]
## Description
Release - It is observed that the alignment of the Multitree-select is improper - The widget is placed little higher when compared to modal and Multi-select widget 

Expected Result:
The alignment of widget should be equal in the entity explorer

### Steps to reproduce the behaviour:

1. Launch Appmsith App in the release environment 
2. Open any of the app and observe the placement of MultiTree Select

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-29 at 6 16 16 PM" src="https://user-images.githubusercontent.com/35128442/135271905-6ce793d9-6f56-4242-a3e5-5ce00aba7b3d.png">

**Comment by Jaideep07** [comment]
I would be glad to work on this could someone (@YogeshJayaseelan , @somangshu , @vivekverma2312 ) pls assign me this issue 😃.

**Comment by somangshu** [comment]
@Jaideep07 this issue needs design change. We are not yet sure here what we need to do.

Can you instead take a look at the `hacktoberfest` label. You will find better and relevant issues. 

Happy hacking 😌

@momcilo-appsmith do we have a solution here?

**Comment by momcilo-appsmith** [comment]
@somangshu we are going to fix this with the new entity explorer
