### ISSUE TITLE
[Bug] Uploading File to S3 not able to upload to root of the s3

### ISSUE THREAD

**Issue by robertoamoreno** [appsmithorg/appsmith#7949]
## Description

When using the upload s3 bucket it always saves files under a folder "/" instead of the root of the bucket.

**Comment by Nikhil-Nandagopal** [comment]
Hello @robertoamoreno 👋 
I'm able to upload files to the root of the bucket. Can you share a screenshot of your query?

**Comment by robertoamoreno** [comment]
https://www.loom.com/share/0befc9e5c7d6450bafe5460f1093d209 @Nikhil-Nandagopal

**Comment by robertoamoreno** [comment]
<img width="848" alt="Screen Shot 2021-09-30 at 8 28 52 AM" src="https://user-images.githubusercontent.com/16195292/135474740-83d49255-f30c-4f94-831c-112cb32584f1.png">

Happens when you use the create page option

**Comment by robertoamoreno** [comment]
It's related when you create page from a database connection under the list query it has extra "/"

**Comment by Nikhil-Nandagopal** [comment]
I see this is to do with the generate page feature. This has been fixed in the next release. Thank you for reporting this!
