### ISSUE TITLE
[BUG] Contact button on the main page takes the user to 'Access Control' documentation

### ISSUE THREAD

**Issue by gogetter22** [appsmithorg/appsmith#795]
Video : https://drive.google.com/drive/folders/1UJ9TRrHLTd0r0Rvh3VixaVKjfiy9e6JZ?usp=sharing

Steps:
1. https://www.appsmith.com/
2. Go to the bottom of the page
3. Click on 'Contact'

Actual Result: Opens up a page where there is information about 'Access Control'
Expected Result: Should open a relevant page where there is relevant information.

Browser: 78.3.0esr (Firefox)

**Comment by rishavjaiss** [comment]
Hi, can I take this up?

**Comment by mohanarpit** [comment]
@rishavjaiss Welcome to Appsmith ! 🎉  Unfortunately, the website is closed source and you can't contribute there. 

You can find a list of other good first issues [here](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22)

Also, feel free to participate in [Appsmith's Challenge](https://github.com/appsmithorg/appsmith/discussions/863) during Hacktoberfest. Feel free to tag your friends and invite them to contribute to the project.

**Comment by hetunandu** [comment]
@mohanarpit this is a website issue which does not open source, thus we cannot have anyone from the community contribute to it. So sorry about this @rishavjaiss. Please go through any other Good First Issues to contribute to Appsmith 🙂

**Comment by areyabhishek** [comment]
I updated the website.

**Comment by mohanarpit** [comment]
@all-contributors Please add @gogetter22  for their invaluable contribution towards bug reporting.
