### ISSUE TITLE
(JS-0008) Duplicate case labels found in switch case

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#7951]
## Description
If a `switch` statement has duplicate test expressions in its `case` clauses, the clause may be repeated or mistyped. It ensures that the offending `case` clause is correct. We support Autofix for this issue. During Autofix, we remove the duplicate switch case (i.e., the second case) as all javascript engines …

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0008/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0008/occurrences/)

**Comment by aayushbisen** [comment]
Is the issue up for grabs? I am interested to fix the issue.

**Comment by Rishabh-Rathod** [comment]
Yes, @aayushbisen, you can go ahead and contribute. 😁

**Comment by aayushbisen** [comment]
Also unrelated to this issue the discord invite link in the CONTRIBUTING.md is expired. 
Kindly check.

**Comment by Rishabh-Rathod** [comment]
Thanks, @aayushbisen for pointing that out. It is fixed now. 😁

**Comment by pooooooooods** [comment]
Seems like the PR that was raised got closed due to inactivity. Is this up for grabs?

**Comment by pooooooooods** [comment]
Oh, I see that the bug got fixed, maybe in some other PR.
