### ISSUE TITLE
[Enhancement] The Show icon in the entity explorer and the enable visible icon in the page properties are not clickable 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7958]
## Description
Release - It is observed that the show icon in the entity explorer and the enable visible icon in the page properties are not clickable 

**Expected Result:**
The show icon in the entity explorer and the enable visible icon in the page properties should be clickable so that user need not to click on three dots in the entity explorer and click on show option and similarly on the page properties user need not to click on setting icon again and enable the visible toggle 

### Steps to reproduce the behaviour:

1.Launch Appsmith app in the release environment 
2.Open any of the app
3.Select any of the page click on the three dots and choose Hide
4.Mouse hover on the page name and try to click on 'Show Icon' and observe 

5.Click on settings icon on the entity explorer 
6.Choose any of the page and click on settings icon in the page properties 
7.Disable the Visible toggle 
8.Click on the 'Enable Visible' icon and observe

Videolink:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d3eb354362144a5e9e4e8509c0b69462-00001.gif)](https://www.loom.com/share/d3eb354362144a5e9e4e8509c0b69462)

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by Nikhil-Nandagopal** [comment]
Closing this as the icons are only indicative and not meant to be clickable since it would interfere with the primary click in the entity explorer
