### ISSUE TITLE
[Enhancement] Add comment lines similar to the one present on ArangoDB on other DB query's

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7969]
## Summary
Currently our dummy data on DB queries contains names of widgets that user's may not have so it displays an error on run. The widget names may get confusing for a new user hence the comment lines explaining the process (like the one present on ArangoDB query) would help a user navigate the application better.

## Additional Content
![image](https://user-images.githubusercontent.com/79509062/135400405-0dd5dcbd-f591-4682-8948-995f35565c85.png)

**Comment by Nikhil-Nandagopal** [comment]
Closing this as we're removing default queries
