### ISSUE TITLE
[Feature]PDF Viewer widget

### ISSUE THREAD

**Issue by RickSoftpaw** [appsmithorg/appsmith#7972]
## Summary

We need an PDF Viewer widget for base64 data

## Motivation

i give the user the possibility to upload attachments via filepicker. It gets stored into mongodb

Now the user usually don't want to download the PDF file. he wants to have a look at it in his browser.

## Additional Context

i tried with an iframe widget (message: no proper URL) Also other widgets cannot work with the base64 pdf data so far.

**Comment by rishabhsaxena** [comment]
Hey @RickSoftpaw realised that we do have a pdf viewer under development, thanks for the point regarding the `IFrame widget`, closing this issue in favour of: https://github.com/appsmithorg/appsmith/issues/3358
