### ISSUE TITLE
[Enhancement] Add confirmation before deleting datasource

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#7976]
description:

we don't have confirmation before deleting the datasource. Once clicked on delete, there is no way to restore it. 
we don't delete datasource if any query is using it but still if the datasource is configured correctly gets deleted, can be very painful for the user.

**Comment by parth-appsmith** [comment]
We dont allow deletion of datasources as long as there are queries/api's connected to that datascource correct?
In that case the scenario when the user is deleting a datascource there is no harm that the application will break, so in this case is it beneficial for us to add another step to the deletion of the datascrouce flow by prompting the user for confirmations?

- There is no way that the actions of deleting a datasource impacts the application in any sense.
- The CTA for delete are clearly defined and the chances of accidental clicks is very minute.

IMO, there is no reason to break the users journey by adding another step of confirmation to the flow of deleting the datasource.
