### ISSUE TITLE
[BUG] No error when no matching letter found in the applications page.

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#798]
## Description

Tried searching for a letter that's not part of the name in the project's list and nothing shows up. I was expecting it to show an error that says "No projects found".

### Steps to reproduce the behavior:

1. Go to Applications
2. Search for a name in the search field
3. See error: https://recordit.co/xHcjqkLYio

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)

**Comment by anuragagarwal561994** [comment]
Hey @Nikhil-Nandagopal I would like to take this up as my first contribution to appsmith.

**Comment by Nikhil-Nandagopal** [comment]
@Debsourabh can you help us with the design for this?

**Comment by Nikhil-Nandagopal** [comment]
@anuragagarwal561994 you can pick this up once we update the designs here

**Comment by Debsourabh** [comment]
Hi @anuragagarwal561994 , I will update the design ASAP and notify you. Thank you for pointing this out.

**Comment by anuragagarwal561994** [comment]
Thanks @Nikhil-Nandagopal

**Comment by Debsourabh** [comment]
https://www.figma.com/file/QzYgZz6y5U9vOyffcyKQ3j/Git-Issue-798?node-id=0%3A1

@anuragagarwal561994 You can use this design. Let us know if you need anything else.

**Comment by akshay11298** [comment]
Hi, if this issue is still open, I would like to work on it

**Comment by anuragagarwal561994** [comment]
Hi @akshay11298 I think you can take this up, I have got pre-occupied with something won't be able to work on it.

**Comment by akshay11298** [comment]
Hi, I have started with this, can someone assign this to me. Also, I had some queries. 
From where can I get the whale error image used above? 
And in that image, I saw a link for "Create application_name". If there are multiple organizations, this link should create the application for which organization?
Thank you

**Comment by mohanarpit** [comment]
@Debsourabh @Nikhil-Nandagopal Looping you into the discussion to answer queries raised by Akshay above.

**Comment by Nikhil-Nandagopal** [comment]
@akshay11298 great questions! We can skip the create app flow.
@Debsourabh can you update the figma file so that the image is exportable

**Comment by akshay11298** [comment]
Hi, I have opened a pull request #1140 for this. 
Screen recording for this is available at https://drive.google.com/file/d/1vlRoEs-Ihdj721MkZAcgeaqZ2HJfIlot/view?usp=sharing

**Comment by prapullac** [comment]
Issue is verified
