### ISSUE TITLE
[Feature] Change references to "self" when widget is being copied

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#7981]
## Summary

When creating a copy of a widget, any references to the original widget in the JS code of the original should be changed to refer to the new name in the copy's code. So when copying `Input1` the JS in the copy should refer to `Input1Copy` wherever `Input1` was used in the original.

## Motivation

As any renaming of a widget also changes all references to it, this seems like a natural extension of that idea. Of course it has to be limited to only the code in the new copy, as it's impossible to determine any other use of the original widget name. But for copying I'd say in almost all cases you want the copy to refer to "itself" rather than the original.

There are numerous times where I have created a widget and set it up just so with code and then created a number of copies. And the JS in all the copies have to be fixed if they had references to "itself".

Another way of doing this is to have a reserved identifier that always referred to the current widget, something like `thisWidget`. But I'm guessing that would be a much bigger change to the underlying code :wink:

**Comment by bharath31** [comment]
@zzgvh thanks for sharing this. Instead of automatically changing references, a more appropriate solution would be to let users track usage and dependencies. #17090 would help with this. 

Closing this issue.
