### ISSUE TITLE
[Enhancement] Minor UI changes on filter pop-up of table filter option

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7984]
## Summary
Using filter option on Table widget causes the text "**Change column datatype to see filter operators**" to move with the width of the filter pop-up. Expectation would be for the text to stay in the original position irrespective of box width.

## Additional Context
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/167d249f2a9342d1aca2b843e2d9f034-00001.gif)](https://www.loom.com/share/167d249f2a9342d1aca2b843e2d9f034)

**Comment by nishihere19** [comment]
Is anyone working on this? If not, can I take this up?

**Comment by Rishabh-Rathod** [comment]
Hey👋🏼  @nishihere19, thanks for showing interest in this issue.

Unfortunately, this issue is not a Good First Issue. Please do check our other Good First issues.

Looking forward to seeing your contributions :)

**Comment by somangshu** [comment]
@ramsaptami @momcilo-appsmith the above behaviours looks right to me, The text is sticking on the right side of the diiv and when the width increases this should be accepted.

Otherwise we should change the position of the text altogether,

**Comment by somangshu** [comment]
@ramsaptami we are of the opinion that there are no changes required here, and this should be closed, Please take up this discussion in the design channel if you feel otherwise or close this issue.

**Comment by riodeuno** [comment]
@ramsaptami @somangshu Let's close this issue, if no further discussion is needed.
