### ISSUE TITLE
[Docs] Single Tree Select Documentation

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#7985]
## Documentation Link 

[Single TreeSelect
](https://github.com/appsmithorg/appsmith/issues/1759)
## Steps

Take a look at [Select Documentation](https://github.com/appsmithorg/appsmith-docs/blob/v1.3/widget-reference/dropdown.md) and [MultiSelect Doc](https://github.com/appsmithorg/appsmith-docs/blob/v1.3/widget-reference/multiselect.md).

Also take a Look at The[ Documentation guideline](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) and [Widget Docs](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/Widgets.md)

## Describe the problem
Doc is missing

## Describe the improvement
Drag a Single TreeSelect Widget to the Canvas and open the Property Pane 
All the Properties of the Single Tree Select Widget should be added to the Docs.
Gifs or Videos would also be welcomed.

**Comment by ArmanChand** [comment]
@nidhi-nair ,
I can work on this Issue

**Comment by Tooluloope** [comment]
Hey @ArmanChand! I've assigned the issue to you. Please make sure to read the guidelines before raising a PR, happy contributing! :)

**Comment by samyakjain10** [comment]
Hey @Tooluloope ! I would like to work on this issue

**Comment by dilippitchika** [comment]
@Pranay105 Please find the link to the documentation for tree select https://www.notion.so/appsmith/TreeSelect-1688874be54140b0921c1905d554407f
