### ISSUE TITLE
[Bug] Unable to use templates  

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#7986]
## Description

[What happened] Unable to use templates apps

### Steps to reproduce the behavior:

Try using templates from
https://www.appsmith.com/templates

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9128efaa044b4379943896da322f50fa-00001.gif)](https://www.loom.com/share/9128efaa044b4379943896da322f50fa)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/77f727fa76954b28a301486a780f59b9-00001.gif)](https://www.loom.com/share/77f727fa76954b28a301486a780f59b9)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@abhvsn how did this break?

**Comment by abhvsn** [comment]
@Nikhil-Nandagopal we put tighter permissions in the last PR which broke this flow.
