### ISSUE TITLE
[Docs] Multi TreeSelect Widget

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#7987]
## Documentation Link 

[Multi Tree Select Widget
](https://github.com/appsmithorg/appsmith/issues/1759)
## Steps

Take a look at [Select Documentation](https://github.com/appsmithorg/appsmith-docs/blob/v1.3/widget-reference/dropdown.md) and [MultiSelect Doc](https://github.com/appsmithorg/appsmith-docs/blob/v1.3/widget-reference/multiselect.md).

Also take a Look at The[ Documentation guideline](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) and [Widget Docs](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/Widgets.md)

## Describe the problem
Doc is missing

## Describe the improvement
Drag a Multi TreeSelect Widget to the Canvas and open the Property Pane 
All the Properties of the Multi Tree Select Widget should be added to the Docs.
Gifs or Videos would also be welcomed.

**Comment by Tooluloope** [comment]
https://github.com/appsmithorg/appsmith/issues/7985 A related issue

**Comment by deepakchethan** [comment]
@Tooluloope I'd like to work on this. Can you please assign this to me?

**Comment by nidhi-nair** [comment]
Hey @deepakchethan ! I've assigned the issue to you. Please make sure to read the guidelines before raising a PR, happy contributing! :)

**Comment by samyakjain10** [comment]
Hey @nidhi-nair ! I would like to work on this issue.

**Comment by dilippitchika** [comment]
@Pranay105  adding the documentation for multi tree select here https://www.notion.so/appsmith/MultiTreeSelect-c324cc380fd94d2286a7e926e5bde7bd
