### ISSUE TITLE
[Bug] Date widget added to hidden form widget causes property pane of Date widget to toggle position and adds an extra strip to the end of the canvas

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7988]
## Description
Date widget's property pane toggles and causes an extra strip to appear at the end of the canvas when it's dragged and dropped onto a hidden form widget on the canvas

### Steps to reproduce the behaviour:
1. Add a form widget on to the canvas or generate a page using a datasource
2. Add a date widget over the form widget and try to edit Default text field on the property pane and observe the property pane shift it's position and cause a strip to appear at the end of the canvas with an extra scroll bar on the page

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/567a1844bafe4dc09b21631135652914-00001.gif)](https://www.loom.com/share/567a1844bafe4dc09b21631135652914)

**Comment by momcilo-appsmith** [comment]
@somangshu Can you resolve this?
