### ISSUE TITLE
[Bug] The name of the Widget is 'TreeSelect' in Widget Pane and 'SingleSelectTree' in the canvas

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7990]
## Description
Release/Production - It is observed that the name of the Widget is 'TreeSelect' in Entity Explorer but when it is dragged to canvas the name of the widget is 'SingleSelectTree' 

Expected Result:
Name of the widget should be same both in Canvas and Widget pane

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the release Environment 
2. Open any of the App
3. Expand widget pane and check for TreeSelect Widget 
4. Drag and drop Tree select tp Canvas and observe the name 

### Important Details

- Version: [11.3]
- OS: [MacOS Big sur]
- Browser [chrome, safari]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-30 at 3 53 04 PM" src="https://user-images.githubusercontent.com/35128442/135438849-f1fc5fff-cb9e-4e0b-9566-0021e330908f.png">

**Comment by SriSatyaT** [comment]
Is there anyone working on this issue?

**Comment by ipankajchaudhary** [comment]
I wanna work on this issue.

**Comment by mohanarpit** [comment]
@SriSatyaT It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com) in order to be eligible for Appsmith swag.

**Comment by mohanarpit** [comment]
@ipankajchaudhary 
Thank you for showing interest in Appsmith. 

Sorry, this issue has already been claimed. I would request you to please look at some of our other [Good First Issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22)

**Comment by SriSatyaT** [comment]
> @SriSatyaT It's all yours! 🎉 
> 
> Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.
> 
> Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com) in order to be eligible for Appsmith swag.

Sure :)

**Comment by bhavy2908** [comment]
i'm intrested

**Comment by SriSatyaT** [comment]
> i'm intrested
> 

Hey thanks for showing intrest. I'll make pr by tomorrow. Hope you grab the other issue.

**Comment by AR10X** [comment]
Pls review this PR #8474
