### ISSUE TITLE
[Bug] The cursor is at the beginning of the TreeSelect widget even after selecting values

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7991]
## Description
Expected Result:
It is observed that the insertion pointer is at the starting point in the tree-select even after selecting the value

Expected Result:
After selecting values the insertion pointer should be at the character ending point

### Steps to reproduce the behaviour:

1.Launch appsmith app in the release environment 
2.Drag and drop TreeSelect Widget 
3.Click onside the treeselect widget 
4.Choose any of the option and observe

Videolink:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bfe3bf7b08b04d9c85165685667603c9-00001.gif)](https://www.loom.com/share/bfe3bf7b08b04d9c85165685667603c9)

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by jindalsachin** [comment]
I would like to work on this

**Comment by mohanarpit** [comment]
@jindalsachin It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com) in order to be eligible for Appsmith swag.

**Comment by jindalsachin** [comment]
Thanks I have registered for the swags and set up the env in IntelliJ . Would you please me point to the specific class/file I should change . I guess the pointer should lchange with listener ?

**Comment by Tooluloope** [comment]
Hi @jindalsachin 
You would need to dig into this [file](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/SingleSelectTreeWidget/component/index.styled.tsx), and Also inspect it on your console to get the class

**Comment by skamp91** [comment]
hey 😊 I want to fix it and work on it, is it still possible ?
