### ISSUE TITLE
[Bug] App header overlaps the Table filter pane when table is placed at top of the canvas 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#7996]
<img width="685" alt="Screenshot 2021-09-30 at 4 31 04 PM" src="https://user-images.githubusercontent.com/83569920/135443563-13bbef87-9ef6-4643-ac91-1099d789b3e6.png">

**Comment by marks0351** [comment]
I think Page Header should still be the highest Z Index. Table popup's boundary limits should always be within the canvas Editor or Viewer is what I assume. We already have functions to move the popup back into the canvas when we move it to extreme of the boundaries. We have to update those functions by setting proper boundary limits which wud start after the header and ends before the footer in terms of Y axis.
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/utils.ts#L39

**Comment by pranavkanade** [comment]
This also observed for deployed apps -
<img width="1344" alt="Screenshot 2022-01-24 at 3 57 03 PM" src="https://user-images.githubusercontent.com/13262095/150768347-1b2c5c4d-61d4-4aa0-9cbe-b9005da2f7c6.png">

**Comment by yaldram** [comment]
One solution to this is to give the Popper element an boundariesElement so that it can preventOverflow. Under src/pages/Editor/Propper.tsx line 133 - 
```javascript
preventOverflow: {
        enabled: true,
        boundariesElement:
          document.getElementById("canvas-0") ||
          document.querySelector('[type="CANVAS_WIDGET"]') ||
          "viewport",
 },
```
- `document.getElementById("canvas-0")` for editing mode.
- `document.querySelector('[type="CANVAS_WIDGET"]')` when in preview mode or deployed the app.

**Comment by marks0351** [comment]
@yaldram we could also just get the boundary parent as a prop and set it to the popper.

**Comment by yaldram** [comment]
@marks0351 done I have added `boundaryParent` prop. I am new to the table widget so we need to check this by changing the position of the filterpane multiple times.

**Comment by yaldram** [comment]
I have pushed the fix branch here please check - fix/7996-table-filter-pane-overflow

**Comment by shwetha-ramesh** [comment]
@yaldram @YogeshJayaseelan re-opening as this does not work on deploy mode on release..

https://loom.com/share/ca1dd026e931437b9cb3131d34fff4c4

**Comment by yaldram** [comment]
@shwetha-ramesh Thanks it is working in production but not on release, I will check this.
