### ISSUE TITLE
[Enhancement] Generate page widgets must be updated according to data type of source

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7997]
## Description
When generate page template is generated with datasource containing a date type column and unique_id is the date column then adding a new record does not register the date field and adding a date widget on the update form does not read the column. Deletion is also not possible.

### Steps to reproduce the behaviour:
1. Go to mySQL datasource and select a table **covidCases** to repro this issue
2. Click on generate page and add a new entry from the modal with a date value of your choice and not the exact format on the table
3. Observe the table entry for date on the new row to be empty
4. Now select the row and observe the update form still hidden
5. Try and delete the entry - which is also not possible

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/394317f4f1c6480da8112649358f1526-00001.gif)](https://www.loom.com/share/394317f4f1c6480da8112649358f1526)

**Comment by abhvsn** [comment]
This will be addressed once we have `JsonFormBuilder` widget which is in pipeline.

**Comment by Nikhil-Nandagopal** [comment]
Solved with JSON Form
