### ISSUE TITLE
[Bug] Appsmith store isn't running in sync within a loop

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#7999]
## Description
```
 if I store value and call API in for loop, it's not sync and 2nd API called before 2nd variable stated
it went like this
Loop 1 :
API with variable A='test'

Loop 2 :
API with variable A='test' (should be 'test2')

The variable is appsmith.store
```
![store-sync](https://user-images.githubusercontent.com/1944800/135444652-5b03777f-45c5-4a24-9778-034550420005.png)

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena what is the use case here? Store value is async in nature

**Comment by rishabhsaxena** [comment]
Got it, I guess we were planning to make it sync. Also the docs say it's a `sync` function:
![image](https://user-images.githubusercontent.com/1944800/135811641-e8a85ec9-7bef-4417-8675-1335c5885e06.png)

**Comment by Nikhil-Nandagopal** [comment]
Thanks updating that!
