### ISSUE TITLE
[Bug] Table widget's filter pop-up does not collapse on opening a modal

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8000]
## Description
Filter pop-up of the table widget does not automatically close when modal widget is opened. 

### Steps to reproduce the behaviour:
1. Drag and drop table and modal widget on to canvas and click on the filter option on the table widget.
2. Now open the modal widget and observe the overlap

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/135444342-c37ee80e-1100-4790-a812-f9098b1b54a4.png)

**Comment by somangshu** [comment]
Here we can reduce the index of the table filter such that it can go behind the modal
