### ISSUE TITLE
[Bug] Modal is showing out of canvas when view mode is changed

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8002]
<img width="888" alt="Screenshot 2021-09-30 at 4 51 55 PM" src="https://user-images.githubusercontent.com/83569920/135446744-c8752cec-c324-4683-8771-66fc6c0073a3.png">

**Comment by somangshu** [comment]
This is not reproducible any more, Closing it for now, @vivekverma2312 please check to see if that is not true.
