### ISSUE TITLE
[Bug] Property pane: long dropdown popup with many entries goes out of the viewport

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8008]
## Description
Release/Production - when there are more number(25-30) of widgets in a page and setting up Onclick actions for any of the widgets it is observed that when the property pane is at the top of the canvas the widget selection pane goes beyond the screen an user is able to select widgets via keyboard and the hidden widgets are not selectable via mouse selection

Expected Result:
If there are more widgets then the during OnClick settings the widgets should not hide and should be easily selectable  

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the release environment 
2. Drag and drop multipe widget (25-30)
3. Open and o the property pane and place the property pane at the top 
4. Set OnClick actions to reset Widget 
5. Choose the widget to reset and try to drag hidden widgets via mouse and observe

**Vdeolink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7b4bb19092d14b1787730591f7321395-00001.gif)](https://www.loom.com/share/7b4bb19092d14b1787730591f7321395)

### Important Details

- Version: [11.3]
- OS: [MacOS Big Sur]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by TD-17** [comment]
Hi! Is anyone working on this issue? If not could you please assign this issue to me?

**Comment by ParnaviKulkarni** [comment]
I can work on this issue if provided with some resources.  Can this issue be assigned to me?

**Comment by OladapoAjala** [comment]
Hello @YogeshJayaseelan I have been able to replicate this bug on my local PC, do you mind if we discuss what files within the project you think the error is coming from?

I am new to contributing to appsmith and this is my first issue.

**Comment by somangshu** [comment]
@OladapoAjala Since this deals will a core component which is used in many places of the app, It might be so that the changes made here will have a cascading effect, we will handle this internally, Can you take a look at other issues under `good first issues` / `hacktoberfest`, Let me know directly if you find something interesting and assign it to you. Happy hacking 🙂

**Comment by somangshu** [comment]
@marks0351 can we fix the popup max-height to avoid this? If you feel the solution here is simple please mark this again as a good first issue!
