### ISSUE TITLE
[Bug] When image url is not passed in both image and default field the rotate icons are still displayed in the widget

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8009]
## Description
Release/Production - It is observed that when the image url is not passed in both the image and default field and enabling rotate toggle - the rotate icons are displayed in the widget

Expected Result:
Rotate icons should not be displayed if no image url is passed in both image and default field 

### Steps to reproduce the behaviour:

1.Launch Appsmith app in the release environment 
2.Drag and drop image widget 
3.Do not pass image url in both the image and default field 
4.Enable the rotate toggle 
5.Mouse hover on the image widget and observe

### Important Details

- Version: [11.3]
- OS: [MacOS. Big]
- Browser [chrome, safari]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-30 at 5 33 12 PM" src="https://user-images.githubusercontent.com/35128442/135452188-15105fd2-f9b8-4d97-8f0c-445b87496881.png">

**Comment by adarshlilha** [comment]
Can I take this up? Thanks
