### ISSUE TITLE
[FEATURE] Airtable Connector

### ISSUE THREAD

**Issue by kunksed** [appsmithorg/appsmith#801]
## Summary

I want to be able to connect to the popular no-code 'database' Airtable and build custom dashboards using Appsmith

## Motivation

- Growing popularity because of no-code nature
- Lots of integrations push data into Airtable
- Already has its own API
- No other tool supports Airtable

**Comment by Nikhil-Nandagopal** [comment]
@kunksed thank you for the feature request! We're looking into adding SAAS integrations soon. We want to be able to add multiple integrations scalably.

**Comment by ajinkyakulkarni** [comment]
We will be developing Airtable integration as part of this epic https://github.com/appsmithorg/appsmith/issues/3270

**Comment by nidhi-nair** [comment]
Closing as this is now available on production.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair can we get some documentation around this?
@vihar can we plan for a tutorial with this integration?
