### ISSUE TITLE
[Bug] Delayed exit of delete modal shows the next table entry before closing

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8010]
## Description
When an S3 bucket entry is deleted, there's a delay between deleting the line and exiting the modal, during which time the next entry is displayed on the delete modal. Raising this as an issue for user experience since it feels unsavory. This is observed even on public app.

### Steps to reproduce the behaviour:
1. Go to a CRUD generated page from S3 datasource
2. Delete an entry and observe the delay after deletion and the next entry being momentarily displayed before the modal closes

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b3b1d25163ca46bca6164a9244f7e41e-00001.gif)](https://www.loom.com/share/b3b1d25163ca46bca6164a9244f7e41e)

**Comment by Nikhil-Nandagopal** [comment]
Fixed in the next release
