### ISSUE TITLE
[Bug] Several problems with Input validation for Number data type

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#8012]
## Description

[This app( change the extension back to .json)](https://github.com/appsmithorg/appsmith/files/7259577/Broken.validation.txt) demonstrates a number of subtly different ways that the validation for Inputs with the Number data type breaks. This may be part of a larger issue around the validation, I have not tested other data types at all. It may also be more or less related to #7899.

### Steps to reproduce the behaviour:

Install the app. Each form has a description of an error. By "jiggle" I mean use the arrows on the input to change the value and then back to its original.

### Important Details

- Version: Cloud
- OS: Linux Mint 19
- Browser FireFox, Chrome
- Environment production

**Comment by zzgvh** [comment]
Adding a video demoing the various error variants.

https://user-images.githubusercontent.com/142613/135573661-c66a8cd0-4caa-400d-af7c-c8477a6377fa.mp4

**Comment by somangshu** [comment]
Comment from the user on [discord](https://discord.com/channels/725602949748752515/760761686549463060/895302466554445904)

> I'm using the Valid field on the Input widget. I'm guessing that it is supposed to be an alternative to the Regex field. If so, it doesn't seem to behave properly on page load. Meaning that the form is treated as valid even if the Input's Valid field returns false. Is this a known issue?

**Comment by sbalaji1192** [comment]
> I found more "fallout" of the issue with "Text.Number". 😢 It's likely you're aware of this already, but I thought a heads up never hurts.
> 
> An input widget set to the Number type and with a Default text of 0 is not included in Form1.data on page load. You have to change its value to include it. This also happens if the Default is changed back to 0 by setting it from a store value.
> 
> I noticed this when a datasource post failed because the value of a form widget wasn't included when it was 0.

opened https://github.com/appsmithorg/appsmith/issues/9117
