### ISSUE TITLE
[Enhancement] : Page properties icon next to page name looks like an attanchment

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8013]
Steps to reproduce:
1) Create multiple new pages
2) Click on the setting option in the entity explorer
3) List of pages are displayed to the user
4) focus on any of the pages
observe the icon next to page name

Observation:
The icon looks more like an attachment icon rather than an icon to launch the page 

Expectation:
It is expected that the icon can be more related to the launch of page.
![Screenshot 2021-09-30 at 5 28 20 PM](https://user-images.githubusercontent.com/71753653/135461338-bf581a43-1e4f-4f36-b13f-9d60eb34a831.png)

**Comment by ArmanChand** [comment]
Hello @Nikhil-Nandagopal ,
I can take this Issue. Please assign it to me

**Comment by somangshu** [comment]
@prapullac I disagree to this, this is the most common representation of a link, Check out this screenshot of quick google search `link icon`
![Screenshot 2021-10-01 at 2 24 22 PM](https://user-images.githubusercontent.com/11089579/135593275-f485703f-5b9c-472f-898b-fade8d1e6cb7.png)

Attachment icon is usually a paperclip. Closing this for now.

@ArmanChand This issue dosent seem valid to me right now, Ill have a discussion around this get back. Meanwhile to find more issue search for the label `good first issue` or `hacktoberfest` to find something relevant to work on. Do tag me, ill assign it to you. Happy hacking

**Comment by somangshu** [comment]
If it makes sense we could probably switch to something like
![Screenshot 2021-10-01 at 2 28 55 PM](https://user-images.githubusercontent.com/11089579/135593843-a98ebe7a-7014-4274-aae5-13b460f0ddac.png)

Please re-open if required

**Comment by prapullac** [comment]
@somangshu  the above icon looks more relevant and we can make changes accordingly.

**Comment by somangshu** [comment]
In that case, @ArmanChand, This is all your 🎉 . Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by Nikhil-Nandagopal** [comment]
The above icon is wrong. It's used to depict that it will open in a new tab.
@momcilo-appsmith could you please help here?

@ArmanChand please don't raise a PR for this just yet :)

**Comment by ArmanChand** [comment]
hello @Nikhil-Nandagopal , 
Waiting for the icon confirmation, once done please inform me, i will start working on it.

**Comment by amanjhurani** [comment]
Hello @somangshu @Nikhil-Nandagopal
It's a kind of webpage a user will be building by clicking on icon. Which will open page in editing mode. I found some icons which matching with the context.

![2](https://user-images.githubusercontent.com/47776459/135659376-92e35d5c-cfe1-45dc-81d7-e89bdaace0c5.png)

![1](https://user-images.githubusercontent.com/47776459/135659392-ed612bbe-25c1-4191-8d22-ab5321132bb2.png)

I would to love to contribute. Please assign it to me, If you liked these icons.

**Comment by ashish921998** [comment]
@Nikhil-Nandagopal I would love to work on this issue.

**Comment by pawankm21** [comment]
I have some suggestions.

[<img src="https://user-images.githubusercontent.com/63885768/135712021-4df74d9c-94af-4bae-a1ba-4ccea09d66aa.png" width="50"/>](image.png)[<img src="https://user-images.githubusercontent.com/63885768/135711958-d3f8487c-5e8a-48d1-8525-d38c438f62a8.png" width="50"/>](image.png)[<img src="https://user-images.githubusercontent.com/63885768/135711960-a3397589-958e-42d1-b501-de121ba7dd37.png" width="50"/>](image.png)[<img src="https://user-images.githubusercontent.com/63885768/135711969-ce376386-9612-4ed8-be88-1cc65d87df5d.png" width="50"/>](image.png)
The first one looks more relevant to me
![image](https://user-images.githubusercontent.com/63885768/135712522-3a924dc7-51aa-4ea1-882f-9db12bdfe082.png)

**Comment by somangshu** [comment]
@momcilo-appsmith Found out that this is actually representing edit page. 

cc @areyabhishek @jsartisan

**Comment by bhavy2908** [comment]
I would like to work on this

**Comment by Aarushi5g** [comment]
Hello, the most relevant icon for preview seems to be this one!

![image](https://user-images.githubusercontent.com/54365212/135766413-d1b676fd-e36f-4a7a-90e8-26b96cab09be.png)

Please let me know what you think and I'll be more than happy to work and complete the issue further!!
Thank you :)

**Comment by ps-19** [comment]
what about this one:

![Uploading icon.png…]()

**Comment by ion05** [comment]
@prapullac can i work on this ?

**Comment by SrinidhiKulkarni28** [comment]
Is this still open? If yes can I work on this?

**Comment by somangshu** [comment]
We have decided to use the icon from our own design system,
![Screenshot 2021-10-06 at 12 23 35 PM](https://user-images.githubusercontent.com/11089579/136154435-f9af0894-013c-47c0-beb3-f260b7b4b5b4.png)

This is already an imported asset in appsmith, Hence you just need to import the ads icon class and refer to the required icon like > ` <Icon name="link" size={IconSize.MEDIUM} />`

**Comment by somangshu** [comment]
This is up for grabs now, Thanks you all for showing interest, However we will have to go by first come first serve basis.

@ArmanChand Greetings, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

I will assign this to the next person, In case I dont see a response from you in the next 3 days.

**Comment by Nikhil-Nandagopal** [comment]
@somyasharma29 @sims-keshri we've already assigned this issue. If it is not resolved in another 2 days, we will make it available again. Please do have a look at our other many good first issues :)

**Comment by somyasharma29** [comment]
Yaa sure and thanks @somangshu

**Comment by somangshu** [comment]
@jsartisan ☝️

**Comment by roshanmelanta** [comment]
Hi @somangshu, I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by somangshu** [comment]
Greetings @roshanmelanta, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

**Comment by rohitagarwal88** [comment]
@vasanth-appsmith : can you help with the icon?

**Comment by somangshu** [comment]
@rohitagarwal88 please check [this](https://github.com/appsmithorg/appsmith/issues/8013#issuecomment-935607026) comment which was the last decided Icon from our DS

**Comment by rohitagarwal88** [comment]
@somangshu I had a discussion with @vasanth-appsmith proposed icon does not convey the desired message, @vasanth-appsmith is working on an alternate approach. He would share it with the team for review.

**Comment by chandanpatra2111** [comment]
hello @somangshu is it still open?
If yes, i can work on it.

**Comment by tauantcamargo** [comment]
@somangshu csan i get it?

**Comment by somangshu** [comment]
Greetings @chandanpatra2111, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

@tauantcamargo Ill go by first come first serve basis, Please look at other Good first issue we have, Ill assign this to you in the next two days in case the PR is not raised

**Comment by somangshu** [comment]
Apologies @chandanpatra2111, After a small discussion internally, we identified this is going to be picked up as a part of a bigger project which is dealing with the page properties overall, I have un-assigned you here. Kindly find other good first issues to work on
