### ISSUE TITLE
[Bug] Fork button missing on some of the applications

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#8016]
## Description

Try using templates from
https://www.appsmith.com/templates

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

goto 
https://www.appsmith.com/templates 
Some of the templates donot have fork button
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/128eb5f4f1a24797b0d6a7db97c87085-00001.gif)](https://www.loom.com/share/128eb5f4f1a24797b0d6a7db97c87085)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by sharat87** [comment]
This seems to be fixed now.
