### ISSUE TITLE
[Bug] Unable to use app on release which is created on master unless redeployed

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#8018]
## Description

[What happened] Migration from master to release seems to fail

### Steps to reproduce the behaviour:

1. Create an app on locally deployed master
2. make app public
3. stop master and start locally deployed release
4. App doesnot work unless redeployed

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/012c68f91f2c4d7b8079013aa3724067-00001.gif)](https://www.loom.com/share/012c68f91f2c4d7b8079013aa3724067)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by yatinappsmith** [comment]
tagging as JSEditor ans app has an jsobject.

**Comment by yatinappsmith** [comment]
After removing the jsobject table data is visible

**Comment by ApekshaBhosale** [comment]
this was problem with public apps. it's solved now!
