### ISSUE TITLE
[Docs] Code of Conduct improvement

### ISSUE THREAD

**Issue by SandipPalit** [appsmithorg/appsmith#8036]
## Documentation Link 

https://github.com/appsmithorg/appsmith/blob/release/CODE_OF_CONDUCT.md

## Describe the problem

The articulation of this documentation needs to be improved.

## Describe the improvement

There are many sections that start with "Examples of" which is not a good way of writing. So, I want to improve those parts. Then I want to correct some more grammatical errors as well.

Please assign this issue to me for the hacktoberfest, so that I can start improving the documentation.

**Comment by riodeuno** [comment]
@SandipPalit Thanks for noticing this issue and offering to help resolve this! This is all yours. Assigning it to you.

**Comment by SandipPalit** [comment]
Thank You @riodeuno 
I am working on this issue and will submit the PR soon.

**Comment by SandipPalit** [comment]
@riodeuno , I have completed the changes and submitted the PR #8083

**Comment by Nikhil-Nandagopal** [comment]
Hi @SandipPalit apologies, I don't think this is a very good PR because our code of conduct is a standard one taken from the contributor covenant. As such I don't think we can accept this PR. Do have a look at our many good first issue!
