### ISSUE TITLE
[Docs] Create an exclusive Hacktoberfest Contribution guide

### ISSUE THREAD

**Issue by SandipPalit** [appsmithorg/appsmith#8037]
## Describe the problem

I faced some difficulty in searching the ways to contribute to your repo which will count towards Hacktoberfest 2021.

## Describe the improvement

I want to create a detailed Hacktoberfest 2021 Contribution guide, which will serve as an all-in-one resource for Hacktoberfest 2021. Please assign this issue to me, so that I can start working on it.

**Comment by mohanarpit** [comment]
Do you believe that our [Contribution Guide](https://github.com/appsmithorg/appsmith/blob/release/CONTRIBUTING.md) is not a good enough resource?

Also, we have a dedicated website [https://hacktoberfest.appsmith.com](https://hacktoberfest.appsmith.com) which lists all our Hacktoberfest resources & swag.

**Comment by SandipPalit** [comment]
I agree that the website is a great resource. If you would like to have some more information on the Contribution Guide, specific to the HacktoberFest, then you can assign it to me, else feel free to close this issue. :)

**Comment by mohanarpit** [comment]
Thanks @SandipPalit. For now, I probably wouldn't clutter the contribution guide with Hacktoberfest specific tasks. That's a generic resource that we wish to maintain for all contributors. 

For now, I'm closing the issue. If you feel that there's a specific improvement that we can make to our contribution guide or the website, please feel free to re-open this issue with specific details on the improvement.
