### ISSUE TITLE
Button widget active, hover and clicked states are not defined on Figma and need design review

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8054]
Creating a separate issue for this since it needs design change

**Comment by momcilo-appsmith** [comment]
Got that. Is this for the buttons on Appsmith or is it for the button widget that the users can drag and drop?

**Comment by ramsaptami** [comment]
Widget that user can grab and drop

**Comment by ramsaptami** [comment]
Can I get permissions to view the document @momcilo-appsmith ?

**Comment by momcilo-appsmith** [comment]
@ramsaptami Just following up here, did this get resolved?

**Comment by ramsaptami** [comment]
Yes, this seems to be resolved now @momcilo-appsmith . Changes have been implemented and present on current release. I have a quick question about the difference between focus and active states though - when do we see this @albinAppsmith

**Comment by ramsaptami** [comment]
Closing this since this has been implemented
