### ISSUE TITLE
[Bug] The Input boxes are displayed multiple times inside the query editor 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8055]
### Steps to reproduce the behaviour:

To repro, this issue follow the below steps
1. create a new app 
2. On page one add a new query for mongo  
3. now create a page 2 there try to add API and the mongo query 
4. Now navigate back to page 1 mongo query 
5. Now we can see the query pane with multiple inputs placeholders
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c9a6b5564a344cca8879c564f2448601-00001.gif)](https://www.loom.com/share/c9a6b5564a344cca8879c564f2448601)

Also happening in below scenario:

1. Export any app with PostgreSQL query fro production
2. Import that app on release
3. Observe that the query is coming twice

<img width="1433" alt="Screenshot 2021-10-01 at 12 41 44 PM" src="https://user-images.githubusercontent.com/83569920/135580947-0d7322f5-b86a-4277-aa04-8fc95453358a.png">

**Comment by RakshaKShetty** [comment]
To repro, this issue in the same application follow the below steps
1. create a new app 
2. On page one add a new query for mongo and Postgre 
3. now create a page 2 there try to add API and the mongo query 
4. Now navigate back to page 1 mongo query 
5. Now we can see the query pane with multiple inputs placeholders
 https://www.loom.com/share/c9a6b5564a344cca8879c564f2448601

**Comment by Nikhil-Nandagopal** [comment]
Not related to import / export. This is a problem with our query editor.

**Comment by Nikhil-Nandagopal** [comment]
@ajinkyakulkarni @ayushpahwa please see!
