### ISSUE TITLE
[Bug]-[10000]:Edit icon consistency across application for design system

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8057]
## Description
Raising this issue to list down different areas where we have **edit** option but there's inconsistency on design/icon. Need some clarity on this.

![image](https://user-images.githubusercontent.com/79509062/135634840-ead01cde-9cbb-4d9e-917e-76359470e52b.png)Icon on **Datasources** page
![image](https://user-images.githubusercontent.com/79509062/135582008-30669484-2e04-4453-ad35-68899a285edb.png)

- [ ] Icon on **API query page** - not present on other datasources
![image](https://user-images.githubusercontent.com/79509062/135584406-52e0d780-d6f4-4026-8275-794faf10312a.png)

- [ ] **Profile dropdown** - icon different from others
![image](https://user-images.githubusercontent.com/79509062/135582879-46984712-a3c5-4326-a002-85342e0f9ae8.png)

- [ ] **Entity pane, query** - no icon
![image](https://user-images.githubusercontent.com/79509062/135583214-33394eaf-21ba-4244-b812-fe7f2c7f9f8a.png)

- [ ] **Entity pane, datasources** - no icon
![image](https://user-images.githubusercontent.com/79509062/135583472-91fab1f5-1f83-4d1a-83d1-4004e666c728.png)

- [ ] **Entity pane, datasources** - no icon
![image](https://user-images.githubusercontent.com/79509062/135583366-2dbd74b6-29de-443b-8f3b-2bb8bfe22e7a.png)

- [ ] **Entity pane, page** - no icon
![image](https://user-images.githubusercontent.com/79509062/135583845-efea2c8a-d97c-4e86-b6c7-4a7bd4a89390.png)

- [ ] **Query name** - icon change?
![image](https://user-images.githubusercontent.com/79509062/135583957-88f8fc2d-e850-43de-a855-fab05f2cf335.png)

- [ ] **Application header** - edit mode icon
![image](https://user-images.githubusercontent.com/79509062/135584009-7a5051cf-a39f-4197-89dc-eaa54b410807.png)

- [ ] **Header**, app name - no icon
![image](https://user-images.githubusercontent.com/79509062/135080068-a3afd9dc-91e7-4c82-b6d7-994140598d09.png)

- [ ] **Home page** - App name edit icon
![image](https://user-images.githubusercontent.com/79509062/135634850-e86bc9b5-c116-431f-b587-cc4ebe4af221.png)

- [ ] **Home page**, app card - icon
![image](https://user-images.githubusercontent.com/79509062/135635134-2c0bf474-4b1a-4fdd-b889-bbc2d664fa04.png)

- [ ] API query
![image](https://user-images.githubusercontent.com/79509062/135640769-97ae5039-21ff-4fa3-9e66-1a7fde80b017.png)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy preview 7304

**Comment by ArmanChand** [comment]
@ramsaptami ,
I can work on this issue

**Comment by ramsaptami** [comment]
Hey @ArmanChand, appreciate your interest in Appsmith. This issue has a pending design need so it's currently on internal review.

Could I suggest picking up issues tagged "hacktoberfest" instead?

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 10000 |
| Effort (months)  | 0.5|

**Comment by rohitagarwal88** [comment]
@vasanth-appsmith : which edit we should use here?

**Comment by rohitagarwal88** [comment]
Closing it. This is fixed in https://github.com/appsmithorg/appsmith/pull/22030

**Comment by ramsaptami** [comment]
API query page has a different icon to the rest of the application
