### ISSUE TITLE
[Bug]-[500]:Delete icon interactions and look for design system

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8058]
## Description
Raising this issue to list down different areas where we have **delete** option but there's inconsistency on design/icon/interaction and needed some clarity.

- [ ] **Deleting a datasource** - no hover state colour, no confirmation, icon change and no colour change on hover
![image](https://user-images.githubusercontent.com/79509062/135581801-dc5319e6-eaf8-482c-abb5-0d23bb3154fb.png)

- [ ] **Query page** - no hover state, no confirmation, icon change and colour change
![image](https://user-images.githubusercontent.com/79509062/135582707-1da7258d-e778-4427-bb8c-66d8d4e2d9a0.png)

- [ ] **Entity pane, query** - no icons, no confirmation, no colour on normal state
![image](https://user-images.githubusercontent.com/79509062/135583175-ee1f535d-f95e-4d89-8520-284c4f8572e1.png)

- [ ] **Entity pane, datasources** - no icons, no confirmation, no colour on normal state
![image](https://user-images.githubusercontent.com/79509062/135583366-2dbd74b6-29de-443b-8f3b-2bb8bfe22e7a.png)

- [ ] **Entity pane, widgets** - no icon, no confirmation, no colour on normal state
![image](https://user-images.githubusercontent.com/79509062/135583588-8d62af11-8734-420b-bb3d-8db6b87d278e.png)

- [ ] **Header, app name** - no icon, no colour on normal state
![image](https://user-images.githubusercontent.com/79509062/135080068-a3afd9dc-91e7-4c82-b6d7-994140598d09.png)

- [ ] **Page properties** - icon change, no colour on normal and hover state
![image](https://user-images.githubusercontent.com/79509062/135595047-55d5af97-6d69-4a73-a331-6516664f069a.png)

- [ ] Center align the bin icon and provide colour in line with design on **org members page**
![image](https://user-images.githubusercontent.com/79509062/135621228-2dbd0de2-c844-4ac0-adf3-224ea65237da.png)

- [ ] App properties on **home page** - different hover and icon to the rest to the app
![image](https://user-images.githubusercontent.com/79509062/135634401-0a5f46d8-ea1a-46db-958c-68ad972b2973.png)

- [ ] **Authenticated API datasouce** - colour, hover state
![image](https://user-images.githubusercontent.com/79509062/135863551-30d69422-d9e6-4d3a-958b-db2ce81d60eb.png)

- [ ] **API datasouce** - hover state, colour on headers and params
![image](https://user-images.githubusercontent.com/79509062/135863769-336f20f6-affb-4fcd-8c3a-642cf204bbfd.png)

- [ ] **Elastic Search datasource** - colour, hover state (same with Redis, mySQL, Redshift, ArangoDB)
![image](https://user-images.githubusercontent.com/79509062/135864643-6137cbe0-5b64-411d-b4bf-d423b4d26dc0.png)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Deploy preview 7304

**Comment by momcilo-appsmith** [comment]
@emysmth @Debsourabh take a look at this

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | 1 |

**Comment by rohitagarwal88** [comment]
@vasanth-appsmith : which delete icon should be used?
