### ISSUE TITLE
[BUG] Field Issues in Organization's General Tab

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#806]
## Description

Tried updating the form with some information:

1. Unable to change the email to empty anymore. 
2. Accepts any random email. 
3. Website field and Workspace filed accept spaces as values
4. Deleting a value doesn't update but shows last stored value (I remove info's in the Website field before starting the screencast)

### Steps to reproduce the behaviour:

Errors Screencast: [https://recordit.co/DyIcHUHKrq](https://recordit.co/DyIcHUHKrq)

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)

**Comment by Nikhil-Nandagopal** [comment]
@devrk96 please add validation for these fields
