### ISSUE TITLE
[BUG] Spaces in Organization Name

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#807]
## Description

Submitted the "Create Organization" form by entering spaces in the "Name" field and the form was successful and created an organization with empty name.

### Steps to reproduce the behaviour:
Screencast: https://recordit.co/GCGUIizMSz

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)

**Comment by vatsalsharma376** [comment]
Can I take up this issue?

**Comment by mohanarpit** [comment]
@vatsalsharma376 Good to see you here & welcome to Appsmith again 😄 

Go for it! Please try to raise a PR within 2 days.

**Comment by AswinCG2002** [comment]
i would love to do this.can u assign me this

**Comment by mohanarpit** [comment]
@AswinCG2002 Welcome to Appsmith! 🎉 

I've assigned the issue to you. Please try to raise a PR within 2 days. 

Also, please check out our [contributing guide](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) before you begin.

**Comment by daniloff200** [comment]
hello :)
looks one, this is not assigned to anybody
I would like to pick this one

**Comment by hetunandu** [comment]
Hey @daniloff200! Welcome to Appsmith! 🎉
Assigning this to you now. Incase you need any help finding a solution, do mention me here and I'll guide you.

Also checkout our [hacktober fest competition](https://github.com/appsmithorg/appsmith/discussions/863) if you are interested in some cool goodies 😄

**Comment by Malvika18** [comment]
hey  i want to contribute

**Comment by satbir121** [comment]
Hello @Malvika18 This issue has been to @daniloff200.

[Here are other good first issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) you can chose from.

**Comment by S-ayanide** [comment]
I have a validation utility for this same use-case which I can use here. Also, it adds a helper text if the user tries to submit an empty field mentioning that 'The field must not be empty'. Can I give it a go? Saw the recent PR didn't have these features.

**Comment by hetunandu** [comment]
@S-ayanide thanks for your suggestions but those features seem to be out of scope for this issue. I welcome you to check out [some of our other issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) since this one is already being worked on.
