### ISSUE TITLE
[appsmith website to be mobile friendly, no need to use desktop mode to use it properly]

### ISSUE THREAD

**Issue by eXfilPr4tik** [appsmithorg/appsmith#8081]
## Summary

If website is opened on mobile phone,then some part of website isn't visible properly and can't be used so make it mobile friendly

## Motivation

Why should this be worked on? What problems or use cases does it solve or
improve?
UserInteractive

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by Nikhil-Nandagopal** [comment]
Hello are you talking about appsmith.com or app.appsmith.com?
appsmith.com is not part of this repository and is going to be mobile friendly soon.
app.appsmith.com has an issue here #4630
