### ISSUE TITLE
Size of images uploaded on Github are too large

### ISSUE THREAD

**Issue by Swatigupta-droid** [appsmithorg/appsmith#8088]
Improve the size of the images to make it look better.

**Comment by rohith1125** [comment]
@Swatigupta-droid Assign me the issue I will fix it

**Comment by Swatigupta-droid** [comment]
@Rishabh-Rathod  ,I have opened a pull request  #8097 for this issue .I have got a reply of getting it merged,
 but haven't yet.

**Comment by mohanarpit** [comment]
Closing this issue for now. If this is still a concern, please re-open the issue along with the PR. Sorry for the delay in getting to this issue.
