### ISSUE TITLE
[BUG] Random "Please check your internet connection" errors

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#809]
## Description

When I went to edit an application, without a set pattern, the error is thrown. Same happens when I go back to the "applications" page. Also noticed that the page doesn't load at all sometimes and sometimes loads with the errors as shown in the screencast below. 

### Steps to reproduce the behavior:

Screencast: [https://recordit.co/TpQJVcewOa](https://recordit.co/TpQJVcewOa)

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac please verify this as well

**Comment by prapullac** [comment]
@Nikhil-Nandagopal Unable to reproduce the issue with the said config

**Comment by Nikhil-Nandagopal** [comment]
@harishkotra are you able to consistently reproduce this?

**Comment by harishkotra** [comment]
@Nikhil-Nandagopal not today. I encountered this twice on the day I reported this. Tried doing the same today but doesn't happen anymore.
