### ISSUE TITLE
[BUG] An unexpected error occurred

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#810]
## Description

Changed the name of the database and navigated to one of the queries I created to find this error. This only happened once and clicking the refresh against the error resolved it immediately. There was also "Please check your internet" popup on the top right which is irrelevant in this case. 

Error: https://recordit.co/hTCpoR6U5X

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)

**Comment by Nikhil-Nandagopal** [comment]
@prapullac please check if this is reproducible

**Comment by prapullac** [comment]
@Nikhil-Nandagopal I am unable to reproduce the issue.This was executed on the environment specified by the user

**Comment by Nikhil-Nandagopal** [comment]
@harishkotra are you able to consistently reproduce this?

**Comment by harishkotra** [comment]
@Nikhil-Nandagopal Not today. Similar to the other issue, this was happening when I was testing it during the time of reporting it. However, this doesn't happen anymore and the platform itself is super fast now unlike my screencast.
