### ISSUE TITLE
[Bug] Website improvements (Webflow design samples)

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8100]
## Description
- [x] Community call banner has a minor typo and extra space
![image](https://user-images.githubusercontent.com/79509062/135661480-61b388de-f6f8-4782-8024-154d95bce17e.png)

- [x] Align headings
![image](https://user-images.githubusercontent.com/79509062/135661699-acb9b288-4172-4255-8e1c-a6d45c341a44.png)

- [x] Elastic Search logo is incorrect - it's the company logo right now

- [x] Reviews from Swiggy/ FreshWorks etc are not there

- [x] Toggle does a little dance before moving to the right
![image](https://user-images.githubusercontent.com/79509062/135661895-ff5b403a-6153-4062-a3db-d8708f0a4d7d.png)

- [x] Roadmap target appears twice
![image](https://user-images.githubusercontent.com/79509062/135663175-24a22489-2817-4f6a-acd3-d3abe81b5acd.png)

- [x] The logo for Elastic search is of the company Elastic, not the product Elastic search
![image](https://user-images.githubusercontent.com/79509062/135664048-82bd97b9-3fa2-412f-b31b-c33d96d88972.png)

- [x] Pricing is different on the **/pricing** and what's present on **/product**

- [x] Description needs an update
![image](https://user-images.githubusercontent.com/79509062/135668197-888ccd51-c8e6-4181-983c-f0c7bd019bd9.png)
![image](https://user-images.githubusercontent.com/79509062/135668701-01d9e576-ec18-43c1-a5c7-9674f3ec50f5.png)
![image](https://user-images.githubusercontent.com/79509062/135668862-78219c70-df59-452e-ba5f-78e2bdd006d1.png)
![image](https://user-images.githubusercontent.com/79509062/135669774-61f7a7fb-0a2a-4063-868b-1578a240cccb.png)
![image](https://user-images.githubusercontent.com/79509062/135670124-39b8bcd3-ef1b-449d-8bd5-01c720a174fe.png)

- [x] Content is the same for all tabs
![image](https://user-images.githubusercontent.com/79509062/135669916-967e01b4-34e5-4ffb-bbb6-3e1ca82ee83f.png)
![image](https://user-images.githubusercontent.com/79509062/135670164-e2393333-8966-482a-acff-07de72baac4a.png)

- [x] Filter on **/blogs** shows a card that does not have a CTA
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/16b6064fe2244faebe0d69baf9736cc5-00001.gif)](https://www.loom.com/share/16b6064fe2244faebe0d69baf9736cc5)

- [x] Links that are not working
Links for github/google signup at the bottom of home page are not working
/product start building link is not working
link for self-hosted not working
link for starter and essential does not work on /pricing
Past events link on /community does not work
Community knowledgebase links (5 of them) don't work
graphQL,cURL, msSQL, firebase link don't work on /integrations
map, menu, radio, rich text, select links on /widgets don't work
case studies link doesn't work on /case-studies
press kit download link doesn't work on /news
read more of press release does not work
git and google sign-up links not working at the end of the page
Link here button on /management does not work
Uses cases links on footer don't work
Terms link on footer doesn't work

**Comment by areyabhishek** [comment]
Thanks @ramsaptami! 
@Rishabhkaul:
1. How does the banner at the top work? Will we manually set it up for every event?
2. Is the roadmap synced to GitHub or do we need to update it manually? We need better text there.

**Comment by Rishabhkaul** [comment]
Thanks @ramsaptami . 

@areyabhishek:
1) Yes  
2) No, we will manually update it here (also, this is not final copy). Vihar is changing it.
