### ISSUE TITLE
[Bug] The undo/redo alert should have width based on the content

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#8102]
Currently, the width of alert that we show in undo/redo feature has a fixed width which looks odd.
<img width="296" alt="screenshot_2021-10-01_at_11 13 03_pm" src="https://user-images.githubusercontent.com/6636360/135701451-efc5f346-897a-4d63-85b9-8053f40eee44.png">

Ideally, the width of the alert should be same as the width of the content instead of a fixed width like the image below:
<img width="639" alt="screen_shot_2021-10-02_at_12 40 50_am" src="https://user-images.githubusercontent.com/6636360/135701478-f3f4d78a-352d-4fa7-b41e-0a897ec16a7c.png">

**Comment by nishihere19** [comment]
Is anyone working on this? If not, can I work on this?

**Comment by somangshu** [comment]
@nishihere19 thanks for showing interest, This issue is not up for grabs, Please search for issues under `hacktoberfest`. Happy hacking :)
