### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by beheradibas** [appsmithorg/appsmith#8105]
## Documentation Link 

https://github.com/appsmithorg/appsmith/blob/master/contributions/ClientSetup.md#running-client-codebase

## Describe the problem

The prerequisites list can be improved.

## Describe the improvement

The setup list has the 2nd item: instructions to install ``mkcert``. After that, a new list has mentioned other steps like cloning the repository and installing yarn. The list item numbers can be changed to make them 3rd and 4th item.

**Comment by prsmahajan** [comment]
I would like to work on this issue.
Can you please assign me if this is not sorted by the assignee?

**Comment by beheradibas** [comment]
Sure, but as I don't see any option to assign it to someone. Maybe because I am not an admin for this repo.
@Nikhil-Nandagopal Please look into the matter.

**Comment by afridihannan** [comment]
Hey Everyone, I am Hannan. I am very beginner to Open  source. I want to contribute on this repo. Can anyone please guide some easy issues and how to proceed!!!
