### ISSUE TITLE
[BUG] clicking on 3 dots (...) results into opening link on Youtube

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#811]
Bug : Hit https://www.appsmith.com/ --> Click on 'See How it works' --> Share --> click on ... (3 dots) 
Actual Result: It takes the user to Youtube.
Expected Result: It should expand and show more options.

<img width="1787" alt="Screen Shot 2020-09-30 at 12 54 18 PM" src="https://user-images.githubusercontent.com/49346036/94655385-1cad0200-031c-11eb-8d93-025342e1897e.png">

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 doesn't seem to be under our control. It's youtube's behaviour
