### ISSUE TITLE
[Docs] Tutorials link in README.md is broken

### ISSUE THREAD

**Issue by roshni-salpekar** [appsmithorg/appsmith#8118]
## Documentation Link 

Link in README - https://github.com/appsmithorg/appsmith/tree/update/readme#tutorials

## Describe the problem

Tutorials link is broken

## Describe the improvement

Link needs fixing

**Comment by TomerPacific** [comment]
Can I help out with this issue?

**Comment by parth1614** [comment]
Greetings there! Can I help with the issue?

**Comment by HammedBabatunde** [comment]
Hello, 
Can I help with this issue?
