### ISSUE TITLE
[Bug] Encoding issue with app export for Mandarin characters

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#8123]
## Description
A user reported on Intercom that Mandarin characters get replaced with ? ? symbols when they tried to import an app from a different instance. It's an encoding issue either during export or import

See screenshot here 
![Screenshot_20211003-101115](https://user-images.githubusercontent.com/30255708/135740408-d528a9b0-db5b-4200-abcb-0755ab9fdbc9.jpg)

**Comment by Nikhil-Nandagopal** [comment]
The user mentioned that this issue is now fixed for them in our latest release
https://app.intercom.com/a/apps/y10e7138/inbox/inbox/search/conversations/164629100012297?q=export&teamAssigneeIdentifier=all&teammateAssigneeIdentifier=all
