### ISSUE TITLE
[Bug] Nested Tabs Selection Issue

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#8127]
## Description

When using nested Tabs, selecting the tab in the children modifies the parent tab.

### Steps to reproduce the behavior:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7c22536983834a548f6ee88499d2e110-00001.gif)](https://www.loom.com/share/7c22536983834a548f6ee88499d2e110)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Nikhil-Nandagopal** [comment]
@somangshu urgent attention here. This can break other people's apps right?

**Comment by Nikhil-Nandagopal** [comment]
@Rishabh-Rathod can you please give the exact steps to reproduce this?

**Comment by Rishabh-Rathod** [comment]
@Nikhil-Nandagopal I am unable to reproduce it now. 

@somangshu this application has the issue this can be used for debugging https://app.appsmith.com/applications/6123c4cf695af65b46d74715/pages/6123c4cf695af65b46d74717

**Comment by vicky-primathon** [comment]
cc @Tooluloope  Default tab property of parent tabs widget was binded to child widget's selected tab. So, whenever user changes tab of nested tabs widget it changes selected tab in parent widget.
