### ISSUE TITLE
[Feature] Add events for javascript code execution

### ISSUE THREAD

**Issue by rmvids** [appsmithorg/appsmith#8128]
## Summary

Add possibility of using events for javascript code execution

## Motivation

Add events in the widget palette, making it possible to run or feed the cache with variables in the events such as the on load of the document or window, for example.

**Comment by Nikhil-Nandagopal** [comment]
@rmvids thanks you for the feature request. This issue will be solved with our JS Editor that will allow execution of javascript on page load #1751. Do let us know if there are any other events missing!
