### ISSUE TITLE
[Feature] Microfrontends for integration

### ISSUE THREAD

**Issue by rmvids** [appsmithorg/appsmith#8129]
## Summary

Microfrontends with token integration.

## Motivation

Add client system integration via token jwt or OAuth. Objective is to be able to elevate or level tool to be a microfrontends portal. In other words, make it possible to use them in production systems as components.

**Comment by Shradha-Verma-12** [comment]
I'd like to take a shot at this issue.

**Comment by Nikhil-Nandagopal** [comment]
@Shradha-Verma-12 this is not a good first issue. Please have a look at our contribution guidelines

**Comment by Nikhil-Nandagopal** [comment]
@rmvids is this to share jwt tokens between oauth providers like auth0 and appsmith?

**Comment by rmvids** [comment]
current solution requires the use of iframe, but I'm suggesting that it works a little more integrated with client systems, so that it's similar to Entando, but not the same. Be able to add widgets on other systems and integrate via oAuth or Jwt via the backend of third-party systems. This would make the widgets could be part of legacy systems and that are in production without the need for rewriting and also not using iframe that I don't see as a good practice...

**Comment by rmvids** [comment]
But if it is not possible to abandon the use of iframe, at least the integration is more transparent for the client, without having public url or even login inside the iframe...
