### ISSUE TITLE
[Docs] Create documentation for video widget.

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#814]
## Summary

Documentation is synced between gitbook and github. Fork [this repo](https://github.com/appsmithorg/appsmith-docs) and create a PR.
Create a file `appsmith-docs/widget-reference/video.md` and add documentation for video widget using the following template. Any screenshot or a gif has to be uploaded inside `appsmith-docs/.gitbook/assets/`.

## Docs Template
```
---
description: >-
  A widget for playing a variety of URLs, including file paths, YouTube, Facebook, Twitch, SoundCloud, Streamable, Vimeo, Wistia, Mixcloud, and DailyMotion.
---

# WidgetName

| Property | Description |
| :--- | :--- |
| **URL** | Property description |
| **AutoPlay** | Property description |
| **Visible** | Property description |

| Action | Description |
| :--- | :--- |
| **onPlay** | onPlay action description |
| **onPause** | onPause action description |
| **onEnd** | OnEnd action description |
```

**Comment by SamriddhiMishra** [comment]
I want to take up this issue.

**Comment by hetunandu** [comment]
That's great @SamriddhiMishra! Assigning it to you 😄

**Comment by SamriddhiMishra** [comment]
I have created a PR for this. https://github.com/appsmithorg/appsmith-docs/pull/17
Please Review!
