### ISSUE TITLE
[Epic] List widget v2

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#8146]
# Objective
Rewrite the list widget and make it more scalable and extendable.

# Success Metrics
List of all metrics you are tracking and the desired goal.
| Goal  | Metric |
| Access derived properties | Should be able to access derived properties of inputs in list |
| Performance  | No unnecessary renders and perf degradation   |

**Comment by Nikhil-Nandagopal** [comment]
Closing since we aren't picking it up yet
