### ISSUE TITLE
[Docs] Documentation Contribution Guidelines

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#815]
## Description

We need to create a guideline for documentation contribution on appsmith. This will make it easier for contributors to help us improve our documentation. For the scope of this task, we'll focus the contributions to 

Updating Documentation Workflow

Widgets 
- Name of widget     
- Description     
- Image of the widget & icon in Sidebar     
- Usage with Queries     
- Properties 

Actions (Show Alert, Download, StoreValue, showModal, closeModal, navigateTo)     
- Name of action     
- Description     
- Parameters     
- Image of it's usage
- Example 

Database Integrations
- Name of the integration
- Link to the official documentation
- Example of Passing Data from widgets
- Example of Displaying Data in widgets

Updating Gifs / Images

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal Has this been completed?
