### ISSUE TITLE
[Bug] When username is a subset of an already existing user then invite user prompt does not appear

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8160]
## Description
When tagged user email address is a subset of an already existing user then "Invite user" prompt is not displayed

### Steps to reproduce the behaviour:
1. In comment mode, try tagging a user with email ID which is a subset of current user, e.g. ramsaptami@appsmith.com (current user) tags saptami@appsmith.com (user to be invited to new organization)
2. Invite user option does not appear and user is unable to add user to organization through comment mode.

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/135845778-4b607f05-c4f2-44c4-937a-9798bfdebb02.png)
![image](https://user-images.githubusercontent.com/79509062/135846023-736dd950-9c0c-430e-9ce6-977edb759604.png)

**Comment by ramsaptami** [comment]
Hey @pranavkanade, the suggestion to add user only pops up right at the end of typing out the entire email. Would it be possible to dynamically check as the user types the email so the Invite user prompt appears a bit earlier rather than at the absolute end?
https://www.loom.com/share/8f382cdca212420fa56c3395e60025db

**Comment by pranavkanade** [comment]
@ramsaptami are you suggesting we should always show the invite new prompt? Showing an invite prompt before user has entered email leads to an error. Try this - go to comments mode, add a comment `@asdf` click on invite user; you'll see the error `please enter a valid email address`.

**Comment by ramsaptami** [comment]
Ah I see, there's a pattern validation. That explains why we need to type out the email entirely before getting that option. I was thinking of a different approach. But this works too 👍
