### ISSUE TITLE
[BUG] Trim leading & following whitespace when editing name of an existing application

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#817]
## Description

When an existing application is edited, it is accepting spaces as the name and saving it while it should throw an error asking the user to enter a name and strip the spaces from the field. Also noticed that the color of the app also changes automatically without changing anything. 

### Steps to reproduce the behavior:

1. Go to "applications"
2. Click on '...'
3. Click on the "edit" icon and enter spaces in the field

Screencast: https://recordit.co/QsxvyTjzom

### Important Details

- Version: Cloud
- OS: Windows 10
- Browser: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by Nikhil-Nandagopal** [comment]
@harishkotra application names can have spaces

**Comment by harishkotra** [comment]
@Nikhil-Nandagopal I agree but space just cannot be the name right? I can add a name as "Organization Name" but not "               ".

**Comment by mohanarpit** [comment]
@harishkotra You're right. We should trim the leading & lagging whitespace in the text and prevent empty names from being set for the application name. I'm re-opening this issue.

**Comment by Nikhil-Nandagopal** [comment]
@harishkotra my bad , this is a valid issue

**Comment by HashTalmiz** [comment]
Hey, Can I take up this issue? I'm not very familiar with the codebase but I can give it a try!

**Comment by Nikhil-Nandagopal** [comment]
@HashTalmiz please have a look at our contribution guide. It will help you get started 😊

**Comment by harishkotra** [comment]
@mohanarpit no above-them for this one?
