### ISSUE TITLE
[Bug]-[8000]:Colour contrast on app cards/user name bubbles for design system

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8171]
## Description
Colour contrast on the app cards/user name bubbles makes it hard to demarcate the boundaries for name bubbles as seen on comment mode (screenshot 1) and home page (screenshot 2)

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/135873817-2d646069-19ea-4a34-9460-6952952abd1f.png)

![image](https://user-images.githubusercontent.com/79509062/135874270-a4ab9721-f4c5-45f7-b4b6-5081d731b553.png)

**Comment by momcilo-appsmith** [comment]
@emysmth Is there a solution for this? I am thinking we should use darker colors for the background, although that will introduce more color into our design system.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 8000 |
| Effort (months)  | 0.5 |

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
