### ISSUE TITLE
[Bug] - Appsmith design system release issues

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#8179]
## Description

- [x] Home page top padding to be reduced
- [x] JS Objects has a double line
- [x] Double line in query page
- [x] Double line debugger and api
- [x]  Widget suggestions drop down icon is still too small
- [x] Dependencies tooltip is still old style
- [x]  Documentation is still not centred vertically in the query
- [ ] Clicking at the end of the page or any entity in the EE does not switch / fold it. Click are needs to be full width
- [x] The selected state of the query is not the same as the selected state of the widget
- [x] App view page sides should not be white
- [x] End tour button in welcome tour flow is greyed out
- [x] Extra padding after modal header

**Comment by Nikhil-Nandagopal** [comment]
One more issue, the selected state of the query is not the same as the selected state of the widget

**Comment by siddhantdixit** [comment]
Can I work on this issue?

**Comment by ramsaptami** [comment]
@albinAppsmith Hover on org member's bubbles on home page causes this strange behaviour
https://www.loom.com/share/8778feaee4f2465b985aeae2d4d6c2c3

**Comment by Nikhil-Nandagopal** [comment]
@siddhantdixit this is not a good first issue. Please have a look at issues with the "Good First Issue" label
