### ISSUE TITLE
[Bug] - Property pane, scrollbar and google sheet where input alignment fixes

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#8190]
## Description

 - [x] Scrollbar appearing on homepage when the members list has more that 20 members
 - [ ] Share popup, while opening the popup loader is coming with scrollbar
 - [x] Selected highlight color is very light
 - [x] Debugger response textbox edges should be sharp
 - [x] Add border to API request URL and remove background
 - [x] Share pop up not getting closed while clicking outside
 - [x] Role popover is hiding dropdown
 - [x] Org members role dropdown arrows should align

**Comment by ramsaptami** [comment]
Debugger success response box is still in rounded corners
![image](https://user-images.githubusercontent.com/79509062/135984920-a114d6b6-450e-43a3-9582-2c51158a2b53.png)

**Comment by ramsaptami** [comment]
Text on welcome page is in grey though its a CTA.
![image](https://user-images.githubusercontent.com/79509062/135987563-5b8aa667-666d-4e5c-9fda-a468a3a81451.png)
