### ISSUE TITLE
[Bug] Tagging Appsmith support on comment mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8193]
## Description
Press **Esc** when the invite pop-up shows up when Appsmith support is tagged and then continuing to comment again. Observe that the invite option does not appear again

### Steps to reproduce the behaviour:
1. Go to **comment mode** and tag Appsmith support. Observe the invite pop-up
2. Now press **Esc**/click outside the box to close the box 
3. Tag support again in a comment and observe no pop-up appear

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Prod

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5d0eac64c7a44d18a99a5c6861cf007e-00001.gif)](https://www.loom.com/share/5d0eac64c7a44d18a99a5c6861cf007e)

**Comment by Rishabhkaul** [comment]
@Nikhil-Nandagopal Guess we can close this, right?
