### ISSUE TITLE
[Bug] Google sheets plugin: Row limit does not parse properly

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8196]
## Description

In case the row limit property in the google sheet plugin has an extra new line the query return an error saying that the row limit is not valid, We should trim such characters from the property value

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Use google sheet get query
2. While defining the row limit add an additional new line
3. Run the query to see the error

Note: We will also need to test this for the rest for the fields.
 
### Important Details

- Version: [Cloud]
- OS: [MacOSX]
- Browser [chrome]
- Environment [production]

**Comment by nidhi-nair** [comment]
This change requires adding basic clean up to the fields that are used in the Google Sheets plugin. Please take a look at the `MethodConfig` class to get started. Although the issue talks about rowLimit, the solve for this is expected to take care of the same validation for rowOffset as well.

This change must be accompanied by a unit test that instantiates the `MethodConfig` class with the failing scenarios and make such scenarios pass with your changes.

**Comment by MitAbhay** [comment]
Assign it to me @somangshu

**Comment by somangshu** [comment]
Greetings @MitAbhay, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by leotom2000** [comment]
Issue Analysis :

This issue is found in 8 scenarios in the same page.

In Fields
(1) Table Heading Row Index
(2) Row Offset
(3) Row Limit
(4) Cell Range

Occurs when 
(1) A space is given after the input value
(2) An enter is given after the input value


Planned fixes in backend :
(1) Addding .trim() to the propertyValue; //around Line 47
(2) Adding propertyValue.replaceAll("[\\n ]", "")  //for the above four cases

File : com.external.config.MethodConfig.java
