### ISSUE TITLE
[Bug] [signposting] Provide option to drop widgets when user is in widget pane

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#8203]
## Description

When a user lands on the new app and clicks the widgets section, the canvas remains with the CTA +datasource which leaves people in a weird state where they can't drag a widget

### Steps to reproduce the behaviour:

While on the first step of signposting flow

1. Use widget Tab at the top to navigate to widget pane
2. Unable to drag and drop widget. UI shows Add datasource screen.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by ramsaptami** [comment]
Clicking on **Widgets** needs to show canvas similar to `+` action 
https://www.loom.com/share/7c56882084114437847f7c62841631ac
