### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by kalpeshT101** [appsmithorg/appsmith#8204]
## Documentation Link 

- The Introduction part in appsmith-docs contains broken markdown making it confusing for readers.

![Screenshot 2021-10-05 at 15-49-51 kalpeshT101 appsmith-docs Mirror of documentation at https docs appsmith com Raise Pull r](https://user-images.githubusercontent.com/36229969/136013749-e4fb838a-7f14-4f93-8d56-329a4043da31.png)

 

## Describe the improvement

- Maybe I can add an anchor markdown with preview image of the youtube link in the readme.md file as shown below:

![Screenshot 2021-10-05 at 16-54-54 Markdown Editor](https://user-images.githubusercontent.com/36229969/136013951-d610ddbf-87c5-4f9b-bf17-af0afb5b5367.png)

**Comment by kalpeshT101** [comment]
Please assign me for the following issue

**Comment by Nikhil-Nandagopal** [comment]
@kalpeshT101 this issue only exists on github. Our docs which are hosted on https://docs.appsmith.com rely on this syntax to render custom components

**Comment by kalpeshT101** [comment]
I see that someone has made the required changes  that I recommended , then why is my PR invalid?

**Comment by Nikhil-Nandagopal** [comment]
@kalpeshT101 I don't see a PR related to this issue can you share the PR?
