### ISSUE TITLE
[Enhancement] Add shadow to welcome tour pop-up's in line with Design System changes

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8208]
## Summary
Design system changes provides a shadow for dropdowns and pop-up. So keeping with this theme, the pop-up's during welcome tour also needs a shadow effect to keep up with current changes

## Additional Context
![image](https://user-images.githubusercontent.com/79509062/136017647-76e2a04e-7278-4592-b602-9d399f4da2a6.png)

**Comment by ashish-patwal** [comment]
hey @ramsaptami i would love to work on this issue if it's available .

**Comment by akash-codemonk** [comment]
@ashish-patwal Please go ahead. The shadows are most likely to be added [to the onboarding helperdiv].(https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/editorComponents/Onboarding/Helper.tsx#L21).

**Comment by ashish-patwal** [comment]
@akash-codemonk are there any specific dimensions to the shadow that needs to be applied to the pop ups

**Comment by akash-codemonk** [comment]
You could pick this up from https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/ads/Menu.tsx#L25
cc: @albinAppsmith

**Comment by ashish-patwal** [comment]
PTAL @akash-codemonk

**Comment by Vishrut19** [comment]
Hey! As I can see that no one is working on this issue. So Can I work on it??

**Comment by akash-codemonk** [comment]
The issue is not longer valid as the UI has been updated. @Vishrut19
