### ISSUE TITLE
[Bug] List Widget shows Unexpected error

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#8221]
## Description

When refreshing the page with a checkbox group within a list widget, the application throws an error.

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Add a list widget
2. Add a checkbox group within the list widget
3. Refresh the page after converting the options control to JS

### Important Details

- Version: [Cloud]
- OS: MacOS
- Browser Chrome
- Environment production

![Screenshot 2021-10-06 at 12 35 56 AM](https://user-images.githubusercontent.com/103687/136086943-06c22252-97c6-489f-a24b-f0940f3a23b9.png)
![Screenshot 2021-10-06 at 12 36 02 AM](https://user-images.githubusercontent.com/103687/136086951-821cac59-9065-4215-90f5-6545050c6b79.png)
![Screenshot 2021-10-06 at 12 36 04 AM](https://user-images.githubusercontent.com/103687/136086956-c7ed6f7c-1925-4815-80a3-824a2b49c7d8.png)

**Comment by MitAbhay** [comment]
Can You assign it to me, @riodeuno

**Comment by riodeuno** [comment]
@MitAbhay Thanks for offering to help out with this issue. We are yet to triage this issue, and are currently working on the assumption that this would need deeper changes in how we develop widgets.

For the time being, I would recommend issues tagged with `hacktoberfest` and `good first issue`.

**Comment by Tooluloope** [comment]
No error occurs.
This has been fixed
https://user-images.githubusercontent.com/31691737/170880680-ca634c1e-40ab-4143-a727-ae9c43c0825f.mov
