### ISSUE TITLE
[Bug] Null check in removeSpecialCharacters in Table Widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#8229]
## Description
```
Cannot read properties of undefined (reading 'split')
    at removeSpecialChars (TableWidget.ts:171)
```

### Steps to reproduce the behaviour:

https://app.appsmith.com/applications/611cf172695af65b46d736c8/pages/611cf172695af65b46d736ca/edit

This error crashed the application

**Comment by Tooluloope** [comment]
https://we.tl/t-lemUdieVFx

Here's the link to the faulty DSL, QA can import this app to test
