### ISSUE TITLE
Widget enhancements

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8233]
## RACI

| | |
| ---- | ----- | 
| Responsible | @Tooluloope, @techbhavin, @wmdev0808, @vibhandikyash  |
| Accountable | @Tooluloope |
| Consulted | @riodeuno, @sbalaji1192, @SatishGandham |
| Informed | @somangshu |

**Comment by leonyangela** [comment]
Hi @somangshu, may I know the details about this task? Thank you

**Comment by somangshu** [comment]
Actionable 16th nov:
- Estimate all issues and push to product backlog @Tooluloope @vibhandikyash @techbhavin 
- plan regular project catchup @Tooluloope
