### ISSUE TITLE
[Bug] The list widget does not reset to the initial page, neither does the selection clears

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8237]
## Description

When we try to reset a list widget on a button click and it is observed that the page number and the item selection does not reset, However the child widgets does reset.

**Comment by somangshu** [comment]
@jsartisan is this intended

**Comment by Rishabh-Rathod** [comment]
A user reported a similar issue on discord. 

https://discord.com/channels/725602949748752515/981075695818141706/981747896816902154
> reset doesn't work on the check box in the list widget too, I've created a demo and invited support@appsmith.com
> https://app.appsmith.com/app/untitled-application-1/page1-629684f1b4c51656bfebc269
> if you make a manual change on the check boxes then try and click select all/unselect all it does not reset to the set value"
