### ISSUE TITLE
[Bug] Mustache is not consistent

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#824]
Theres a difference between

```
{
"range": "Sheet1!A2:E",
"majorDimension": "ROWS",
"values": [{{
[Table1.selectedRow.name](http://table1.selectedrow.name/)}}, {{Table1.selectedRow.duration}}, {{Table1.selectedRow.start}},
'REJECTED',
{{reasonDropdown.selectedOptionValue}} }}]
}
```

and

```
{
"range": "Sheet1!A2:E",
"majorDimension": "ROWS",
"values": {{[
[Table1.selectedRow.name](http://table1.selectedrow.name/), Table1.selectedRow.duration, Table1.selectedRow.start,
'REJECTED',
reasonDropdown.selectedOptionValue]}}
}
```

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you discuss the substitution wrt this issue as well

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu New issue
[{{ Table1.selectedRow }}]
this doesn't evaluate to an array
Why?

**Comment by hetunandu** [comment]
@Nikhil-Nandagopal 
Depends where you are binding this. Text widget will always parse this into a string and table widget will parse it into an Array

**Comment by Nikhil-Nandagopal** [comment]
Binding in the table and it doesn't parse to an array

**Comment by trishaanand** [comment]
As part of Prepared Statement/Smart Substitution we would only be supporting the second scenario where the entire value is being provided from inside the binding instead of using the binding as a templating mechanism.  Closing this as a scenario we wouldnt be handling.
