### ISSUE TITLE
[Bug] All Input fields are highlighed in red when selected

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#8248]
## Description

With the latest release, 1.25, I think there's been a change to how the selected field, i.e. the field you're currently editing, in a widget is highlighted. I don't remember exactly how it was shown before, but now the highlight border box is red, making it look like there's an error, since that is how fields with errors are indicated. There is possibly a small difference in the actual colors, but it's too small to be discernible, at least to me...

This is quite annoying :wink: and thus I am reporting this as a UI bug.

The highlighting as such is thus not the issue, but rather the color. I'd suggest using a dark grey or similar, but it really doesn't matter as long as it doesn't look like the error highlight!

### Steps to reproduce the behaviour:

* Open an app in edit mode.
* Open a widget
* Select a field by clicking it.
* The border box around the field is highligted. In red.

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by kocharrahul7** [comment]
The fields are now black :)
