### ISSUE TITLE
[Docs] Grammatical error in `ClientSetup.md`

### ISSUE THREAD

**Issue by shreemaan-abhishek** [appsmithorg/appsmith#8249]
## Documentation Link 

[This file](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md) has doc. issue.

## Describe the problem

[This](https://github.com/appsmithorg/appsmith/blob/a7d0068256e65589d1f042c0f2357c11c599f4a6/contributions/ClientSetup.md#L89) line has redundant `the`:

> If you cannot set up ***_the_*** the API server on your local system, you can also use Appsmith's staging API server.

## Describe the improvement

We shall remove the extra `the`

**Comment by AR10X** [comment]
Hi, I would like to contribute. 😄

**Comment by shreemaan-abhishek** [comment]
Sure! Totally understandable!
