### ISSUE TITLE
[Bug] Unable to enter space for column names on table widget and using backspace/delete just before space causes the cursor to shift to the end

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8256]
## Description
Unable to enter space for column names on table widget and using backspace/delete just before space causes the cursor to shift to the end

### Steps to reproduce the behaviour:
1. Go to table widget and type in a column name and try pressing space. Observe that space can't be provided between words
2. Now add a space between a word and use backspace/delete/block and then clear the word just before space and observe the cursor shift to the end

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Production

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8750cb2dd370483e86c05b6d0d49a648-00001.gif)](https://www.loom.com/share/8750cb2dd370483e86c05b6d0d49a648)

**Comment by somangshu** [comment]
@Tooluloope I am reassigning this to you, Just to note, We do not want any external entities to touch the code that belongs to table widget, If you see any other such cases please make sure we are mitigate from that

**Comment by Tooluloope** [comment]
@somangshu Should we let the effect of the editing take effect after the input has lost focus or onBlur.

This would let the necessary formatting be done before changing the column name rather than changing/formatting it every time the user types a character

**Comment by somangshu** [comment]
@Tooluloope apart from the performance, what else is the benefit?

**Comment by Tooluloope** [comment]
Basically, the issue with the current behavior is that it formats the input every time the user types, that's why adding space at the back of the column name won't work, but if we format after the user is done typing, then we can remove the excess spaces if any

**Comment by somangshu** [comment]
@Tooluloope recommend working on this internally, Everything related to the core widgets like table

**Comment by Tooluloope** [comment]
Fixed

**Comment by ramsaptami** [comment]
Re-tested and verified this to behave as expected
