### ISSUE TITLE
[Bug] Text Overlaps in the property pane of Button column type 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8274]
## Description
Release/Production - It is observed that on the table widget - Button column type - Text overlaps in the property pane

Expected result:
Text should not overlaps and should be visible clearly 

### Steps to reproduce the behaviour:

1. Launch appmsith app in release environment 
2. Drag and drop table widget 
3. Click on action setting icon and observe

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7b89cd21621c44a8b96232cc1bdad605-00001.gif)](https://www.loom.com/share/7b89cd21621c44a8b96232cc1bdad605)

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release]

**Comment by somangshu** [comment]
Issue resolved
