### ISSUE TITLE
[Task] Automatic Import with Vscode needs improvement

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#8278]
## Problem

1. When using `useEffect`, auto-import does import the `useEffect` from `react` library but doesn't work as expected.

Expected Result:

```
import {useEffect} from 'react'
```
or
```
import React, { useRef, useEffect } from 'react'
```

Actual Result:
```
import useEffect from 'react'
```
or
```
import React, { useRef } from 'react'
import useEffect from 'react'
```

The same happens with most of the libraries.

> This is a configuration issue, plugin which does this particular job needs to be added. (not sure if it is a babel plugin or any other)

**Comment by rajoriaakash** [comment]
Can I try this? I think we might need to add an extension to `package.json`

**Comment by kyteinsky** [comment]
I too don't know much about it. I'll drop this one then.
