### ISSUE TITLE
[Bug] In generate  CRUD page the delete button is displayed in green 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8295]
## Description

[What happened]The delete button color is displayed green when user  generate  CRUD page

### Steps to reproduce the behaviour:

![image](https://user-images.githubusercontent.com/45958978/136366970-9eb0c0eb-082e-43cb-aec4-06f0c17c55bd.png)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser chrome,
- Environment release

**Comment by abhvsn** [comment]
@Hanaffi Sorry to say that we can't assign this to you as this is enhancement in the internal app and only Appsmith team has the access to this. Can you please check other issues?
