### ISSUE TITLE
[Bug]The tooltip is not displayed in entity pane when query name is too long 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8296]
## Description

[What happened]The tooltip is not in the entity pane when the query name is too long  and also the starting text of the name is not displayed

### Steps to reproduce the behaviour:
1. Add a query 
2. Now click on meatball icon in the entity pane
3.  Click on its name
4. Now add the Query name as " insert_data_to_verify" text 
5. Verify the display of text 

the starting text insert is not displayed correctly and even the tooltip is not displayed
![image](https://user-images.githubusercontent.com/45958978/136367978-6a8eafbd-e227-478b-a60e-015484ef2dd7.png)

### Important Details

- Version: [Cloud ]
- OS: MacOS
- Browser chrome
- Environment  release

**Comment by BlakeH2208** [comment]
@somangshu Please assign this to me
