### ISSUE TITLE
[Bug]: isRequired key is missing for some form fields.

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#8303]
- add `isRequired` in API `/api/v1/plugins/{id}/form` in `form.children`

**Comment by nidhi-nair** [comment]
@prapullac could you please help populate this issue with a list of plugin - fields that need this change? We're looking for plugin fields that should be marked with an asterisk but are not.

**Comment by nidhi-nair** [comment]
@rohan-arthur @ajinkyakulkarni I'm unassigning myself from this issue since it needs more info (also adding the tag). Not really sure which fields I need to be doing this for.

**Comment by nidhi-nair** [comment]
Closing till we have more info on this.
