### ISSUE TITLE
[Bug]\n is not showing in rich text editor

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#831]
## Steps
1. drag a rich text editor
2. drag an input
3. make the input multiline
4. enter text in different lines
5. bind the rich text editor to the input
6. the rich text editor displays the data without the new lines

<img width="1211" alt="Screenshot 2020-10-14 at 12 42 53 PM" src="https://user-images.githubusercontent.com/3897254/95955704-e5aa1680-0e1a-11eb-9d8f-add6adc62d9f.png">

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon able to repro this

**Comment by prapullac** [comment]
On deploying the page the data would be in multiple lines in Richtext editor widget. Hence issue is verified

**Comment by prapullac** [comment]
Closing the issue as it is working as expected. Please refer the screenshot for the same 
![Screenshot 2020-11-20 at 6 23 57 PM](https://user-images.githubusercontent.com/71753653/99802434-b2ffe600-2b5d-11eb-8c39-8600f2f9295e.png)
