### ISSUE TITLE
[Bug] Not able to move Multi-select widget and the Multitree-select widget on the canvas by holding the input area

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8311]
### Important Details

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/eddd04a85bb546c5875bd08a9540fda7-00001.gif)](https://www.loom.com/share/eddd04a85bb546c5875bd08a9540fda7)

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by dilippitchika** [comment]
Able to replicate this issue, drag to move works for select type widgets but not multi-select type widgets. Please pick this up after the v2 enhancement.

**Comment by Tooluloope** [comment]
Closing in favour of https://github.com/appsmithorg/appsmith/issues/7259
