### ISSUE TITLE
[Feature] Show warning to user if they navigate out of datasource config page without clicking save

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#8317]
## Summary
Currenlty, Appsmith does auto save everywhere except the datasource config page. Hence, new users get confused and end up not clicking the `save` button leading to failure. Hence, once solution could to be show a warning message to the user if they navigate out of the datasource config page without saving the config. 
Ref: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1633613603108300

**Comment by rohan-arthur** [comment]
will be addressed in #4381

**Comment by sumitsum** [comment]
@rohan-arthur just for clarification - why have we closed this issue ? This issue is very different from #4381 ?

**Comment by rohan-arthur** [comment]
design link: https://www.notion.so/appsmith/Autosave-vs-Manual-save-in-Datasource-fb96a01c3df74a41a4bd0c63398188fe

**Comment by sumitsum** [comment]
@rohan-arthur we don't do auto save in datasource form at the moment.

**Comment by rohan-arthur** [comment]
@sumitsum looks like we do at least in this case: click + to add a new datasource, then click "back". The datasource is saved

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur that is auto create but it doesn't auto save. Clicking create will create the data source but editing a value won't be saved till you hit save

**Comment by rohan-arthur** [comment]
will be addressed in https://github.com/appsmithorg/appsmith/issues/4381
