### ISSUE TITLE
[Bug] Appsmith triggers web firewall rules when Cloudflare is used a proxy

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#8325]
Got this comment from David on [Discord](https://discord.com/channels/725602949748752515/725609493974614076/895739305924886639). 

Appsmith triggers a lot of WebAppFirewall rules in Cloudflare. These are also triggered by Metabase. Currently the WAF rules need to be disabled for Appsmith to be used.

**Comment by bamboowonder** [comment]
I just noticed, that the Action taken on all of these, but simply "Log", not "block".   So the functionality of appsmith would not have been affected.  I also suspect that they weren't considered severe or critical enough to block.
