### ISSUE TITLE
[Bug] Jitters and problems with drag and drop

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#8327]
## Description
Creating this issue to list current problems with the new drag and drop library. I think the issues are scattered so creating a new one to collate them.

1. Issues in dragging/resizing upwards
2. Jitters in container and iframe specifically(reported on Discord)
3. Drag and drop sometimes unresponsive when you try to draw a polygon from outside the canvas area(difficult to consistently reproduce this)

**Comment by marks0351** [comment]
self note:
when dragging a new widget into a container with its parent container scrolled, widget shows up as colliding even when it's not.
relative handle position is not accurate when a new widget is dragged into a container with its parent container scrolled.
