### ISSUE TITLE
[Bug] The Text field for Checkbox group and Radio group is not proper

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8332]
## Description: Key and value text field is not completely used, also certain area in the box is highlighted with different color

<img width="268" alt="Screenshot 2021-10-08 at 12 22 32 PM" src="https://user-images.githubusercontent.com/83569920/136512695-c68b81e6-b4f9-425c-8b9a-fd7bf59ccc2b.png">

**Comment by albinAppsmith** [comment]
@haojin111 there a white space in the end of the textbox

![Screenshot 2021-10-21 at 11 12 21 AM](https://user-images.githubusercontent.com/87797149/138218230-e152aad1-7535-4e24-9aa4-2a0cce1eb41a.png)
