### ISSUE TITLE
[Feature] add an Animate Loading property for all widgets

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#8336]
## Summary
A property to enable or disable the loading animation for a particular widget whenever its data is getting updated. Today the platform does the animation automatically but a user should be able to opt out of it.

## Motivation
In scenarios where the animation does not make sense or if the data is getting polled, the user would want to disable this setting.

## Additional Context
Polling would get enabled with #8158

**Comment by somangshu** [comment]
While we are looking at a platform level cleanup through WDS and Anvil, it was bought to attention that this property should be re-considered and if it really adds value. 

The use case that we are seeing is valid is for polling, what else can we think of here?
If its only about polling is there a better way to think about this, link though some global construct. 

On Stats, I see that people have used / updated this prop in the last 12 months, so we cant ignore its usage and hence thinking from a product POV becomes important. 

<img width="1330" alt="Screenshot 2023-10-20 at 4 45 02 PM" src="https://github.com/appsmithorg/appsmith/assets/11089579/aa9cb3b7-ee7b-454d-98dc-27b32f6ec2d0">

**Comment by Nikhil-Nandagopal** [comment]
@somangshu We'll need to support this because of the real-time use-cases with websockets and some users simply don't like the loading animation.

**Comment by ichik** [comment]
@somangshu @Nikhil-Nandagopal this perhaps requires additional user research, but having it as an app-level/theme prop should satisfy the need, I think.

**Comment by ichik** [comment]
@Nikhil-Nandagopal if the difference of behaviour can be identified on the widget type level, then widgets should implement these different behaviours (as a default, but also in how they react to theme).

**Comment by Nikhil-Nandagopal** [comment]
@ichik It's not a function of the widget type but a function of the use case. If a table widget is receiving live data updates, it should not animate while if it is just refreshing manually, then it needs to. The platform cannot detect when the widget needs live data vs doesn't need live data so the onus is now on the user to set this.
