### ISSUE TITLE
[Task] Generate List of SAAS Integration Issues

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#834]
# Description
We need a large list of good first-time SAAS APIs and the format that they can be configured in

**Comment by nidhi-nair** [comment]
- [x] Airtable
- [ ] Stripe
- [ ] Hubspot
- [ ] Zendesk
- [ ] Sendgrid
- [ ] Salesforce
- [ ] Twilio
- [ ] Slack
- [ ] Jira
- [ ] Github

**Comment by rohan-arthur** [comment]
| Industry | SaaS |
| ------------- | ------------- |
| Spreadsheet Database     | Google Sheets |
| Spreadsheet Database     | Airtable |
| CRM     | Hubspot |
| Support    | Zendesk |
| Communication    | Twilio |
| Sales    | Salesforce |
| Payments    | Stripe |
| Project Management    | Github or Jira |
