### ISSUE TITLE
[Bug] Widget design audit: Table Widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8344]
## Description

This is to make cosmetic changes to the table widget based on the changes after the design audit. Here we are covering:
- Update the selected row color
- Update the checkbox style

## Developer handoff file:
https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=633%3A6639

**Comment by somangshu** [comment]
@eco-monk here are some small UI changes in the table widget, We need to get this done before the end of sprint, Please plan, Let me know if you need any help

**Comment by momcilo-appsmith** [comment]
@eco-monk Here is the hover state for the checkbox that is on added: https://www.figma.com/file/w9CaXHF5iYcrLtiEbAHcFu/Original-Theme-Widgets-Library?node-id=684%3A6471
