### ISSUE TITLE
[Feature] Image Zoom

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#835]
## Summary

Users need a way to zoom into an image displayed by the image widget.

## Motivation

Images are at times used so that manual verification can occur. Some images are of very high resolution and need to be zoomed in order to verify fine details

## Proposed Solution
Add an Enable Zoom Property to the image widget which will transform the mouse to a magnifying glass on hover.
Clicking the image will trigger a zoomed version of the image as a modal which can be further zoomed.
[Example Interaction](https://www.magictoolbox.com/magiczoomplus/examples/#mz-expanded-view-1386050488401)

**Comment by dhawaldj95** [comment]
Just a suggestion, to keep things simple and light can we create a new image widget which will have this zoom functionality and keep the normal one as it is. This would keep it light when we don't want the zoom functionality on an image. Just a thought!

**Comment by Nikhil-Nandagopal** [comment]
@dhawaldj95 that's a good concern! Worry not, we'll have an option in the property pane to turn this feature on/off for the same image widget so that it's not confused with the general functionality. We try to avoid duplication of widgets as much as possible so that new users are able to find the right widget quickly 😃
