### ISSUE TITLE
[Bug] Datepicker default date sets to current date when the binding value is empty

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8363]
## Description

The date picker default date sets to the current date (today) when the given value of binding is empty/null/undefined.

![Screenshot 2021-10-09 at 6 37 04 PM](https://user-images.githubusercontent.com/11089579/136659134-8455cd5b-0049-46f6-9edd-e356346b5821.png)

### Steps to reproduce the behaviour:

1. Add a table selectedRow property binding to the date picker default date
2. The evaluated value of the property is still a date but is expected to be empty / null / undefined 

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by somangshu** [comment]
This might be related to #4058

**Comment by vicky-primathon** [comment]
This might break existing applications where null / empty / undefined is converted to current date. 
cc  @Tooluloope

**Comment by vicky-primathon** [comment]
cc: @riodeuno
