### ISSUE TITLE
[Bug] Appsmith's website page issues

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#8365]
## Description

 1. Social links are broken in Appsmith's home page website blog section.
 
- 1. Open https://www.appsmith.com/blog-categories/announcement
- 2. try to click the social link

2. Clicking on the name of the main blog which currently has the title "All You Need to Know About the Appsmith Hacktoberfest 2021" doesn't open the blog.
 
3. Font size of Heading is big ( Not sure if this is by design)

<img width="1440" alt="Screenshot 2021-10-10 at 1 08 23 AM" src="https://user-images.githubusercontent.com/23132741/136671878-4959bbe4-435f-4ec1-a346-a6622e28d47e.png">

4. CTA "Add to Appsmith" in each blog's end is not actionable.

<img width="807" alt="Screenshot 2021-10-10 at 1 10 43 AM" src="https://user-images.githubusercontent.com/23132741/136671943-fdb72744-95aa-48e9-82c8-e41b89ad91e8.png">

5. CTA "Add to Appsmith" shouldn't be visible for all the blogs. Seems to be valid for a blog with a template or demo example.

6. LineSpacing of Title can be improved `0.01em` will be better currently it is `-0.02em`

<img width="745" alt="Screenshot 2021-10-10 at 1 20 19 AM" src="https://user-images.githubusercontent.com/23132741/136672173-9b581902-8b7e-4b0a-83dd-a9d707906934.png">

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by Rishabh-Rathod** [comment]
Hey👋🏼 @Indrakant-Dana , thanks for showing interest in this issue.

Unfortunately, this issue is not open for external contribution yet. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22)

Looking forward to seeing your contributions :)

**Comment by Rishabhkaul** [comment]
@Rishabh-Rathod Made all the major changes (1,2,4,5). The rest are fine for now I feel.

**Comment by Rishabhkaul** [comment]
@Rishabh-Rathod Made all the major changes (1,2,4,5). The rest are fine for now I feel.
