### ISSUE TITLE
[Bug] Null comparison with type-checking 

### ISSUE THREAD

**Issue by AdeshChoudhar** [appsmithorg/appsmith#8374]
## Description

Mentioned on deepsource.io [link](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0059/occurrences?page=1)

**Comment by AdeshChoudhar** [comment]
@Nikhil-Nandagopal Please review my PR and suggest changes if any.

**Comment by sharat87** [comment]
Hey, I'm not sure this is something that needs _fixing_. Using `==` and `!=` in Javascript is generally not recommended, unless the right hand side is `null`. Null checks in Javascript are best done with `==` and `!=`, not `===` and `!==`.

The expression `x == null` is similar to `typeof x === "undefined" || x === null`. So, unless we know what we are changing and what we are fixing, I don't advise `===` for null-checks.

@riodeuno or @hetunandu, please correct if I got this wrong above.

**Comment by AdeshChoudhar** [comment]
@sharat87 Ok cool. However, the work was already completed and merged without creating an issue beforehand and thus not following contribution guidelines before me. See #8319. I am closing this issue anyways. Thanks.
