### ISSUE TITLE
[Feature] Manage git branches

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#8378]
## Summary

Deploy flow from local to git

- [x] Manage branches
- [x] Create a new branch
- [x] Select existing or switch branches
- [ ] Merge remote to local
- [x] Check if one can switch branches
- [x] Check if one can merge other branch / pull in changes from the remote counterpart 
- [x] Push branch
- [x] Show errors or conflicts message
- [x] List branch should fetch remote as well as local branches
- [x] Delete branches from local if the counterpart is deleted from remote repo
- [x] #8826
- [x] #8648

**Comment by abhvsn** [comment]
>  Merge local branch to remote
We are not going ahead with this feature as this was causing confusion from UX point of view in the merge tab. Closing this for the same reason
