### ISSUE TITLE
[Bug] Issues in Organization Settings screen

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#839]
## Description

Organization settings page takes quite a few seconds to load the existing information and upon updating to a new name, it doesn't get saved.

### Steps to reproduce the behaviour:

Screencast: https://recordit.co/zR294Vz1AV

### Important Details
Version: Cloud
OS: Windows 10
Browser: Microsoft Edge

**Comment by Nikhil-Nandagopal** [comment]
@harishkotra this seems to be specific to your org, can you ping the URL of the org

**Comment by harishkotra** [comment]
@Nikhil-Nandagopal https://app.appsmith.org/org/5f7381eb87a2a2331d40b595/
