### ISSUE TITLE
[Bug]: when use embed=true param cause a blank area at the bottom of the page

### ISSUE THREAD

**Issue by Hexiaopi** [appsmithorg/appsmith#8393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/12226042/136752349-f383bbeb-d9d2-4eb1-a2c8-54f6d248b063.png)

### Steps To Reproduce

```markdown
1、url add param ?embed=true
```

### Environment

Release

### Version

Self-Hosted

**Comment by israrwz** [comment]
+1

This is causing serious usability problem when trying to embed a Appsmith in smaller iframe in an existing website.

**Comment by israrwz** [comment]
the current css is as following:

```
#root>div>div>div>section {
    display: flex;
    flex-direction: row;
    -webkit-box-align: stretch;
    align-items: stretch;
    -webkit-box-pack: start;
    justify-content: flex-start;
    height: calc(100vh - 72px);   /* <-- This needs fixing */
}
```

the **height** deduction should be conditional on the presence of **embed** parameter in the url.

**Comment by techbhavin** [comment]
this issue is covered in the pull request https://github.com/appsmithorg/appsmith/pull/10440.

closed this issue
