### ISSUE TITLE
[Bug] Git Connection & Commit and Push issues

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#8395]
## Connecting to Git

- [x] When the new user login in the signposting flow when the user click on the Deploy button the git Sync pop up is displayed instead of Deploy-->Fixed
- [x] When the URL is wrong the error is not displayed correctly->Fixed
- [x] We need a text that says "Create an empty git repository and paste the remote URL"-->Fixed
- [x] The deploy preview is missing-->fixed
- [x] The update button functionality is not working (The name doesn't get updated when we change the name)->fixed
- [x]  Based on the action performed The pop up should be displayed eg: if it commit and push open the deploy tab if it a merge then open the Merge tab->fixed for deploy
- [x] The Remote URL is editable by users-> it should be until the connection successfull
- [x] When the user is typing the email id in the Email input box the error message should not be displayed -> not fixed
- [x] The deploy key text should say "Paste this deploy key in your repository settings and give it write access. Learn more". This can be slightly more prominent, maybe place it above the deploy key instead of below?-->Not Fixed
- [x] When the user does his first commit and go back to git connection page to change the user details and delete the Email id the error message is not displayed-> not fixed
- [x] When the user clicks on the Update button there is a flickering issue -> not fixed
- [x] When user clicks on deploy the application name disappear and then user should manually reload the page->not fixed

### Others
- [ ] When there is no write access given when a user added a deploy key add a Related toast error for it @AnaghHegde  (when ssh key is added without write access when tried connecting a relevant error should show up)

## Commit and Push
- [x] We need to indicate when a branch has uncommitted changes
- [ ] We need to indicate when a branch has unpush commits @abhvsn ( git status API dependency )

## new issues (13 Oct) 

- [x] When the user clicks on the git repo link the Pop up should open and the link should be closed
- [x] When the user pastes the Wrong URL then paste the right one and click on generate SSH key the button doesn't work
- [x] there is  a slight delay in the performance of the activity when the user add new widgets and click on deploy button under deploy tab it takes some time to enable the Commit and push button [Show loader for git status call @Rishabh-Rathod ]
- [x] In the setting page when the user clicks on git user config the user is not navigated to the tab

**Comment by RakshaKShetty** [comment]
@Rishabh-Rathod following are the new issues 

- [ ] When the user clicks on the git repo link the Pop up should open and the link should be closed
- [ ] When the user pastes the Wrong URL then paste the right one and click on generate SSH key the button doesn't work
- [ ] there is  a slight delay in the performance of the activity
- [ ] In the setting page when the user clicks on git user config the user is not navigated to the tab
