### ISSUE TITLE
[Bug]: JS call fails after JS function name refactor and code addition

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS object call after refactor fails to call when call is triggered through widget binding

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5a7fcba7316b45dfa51461b40f2a541a-00001.gif)](https://www.loom.com/share/5a7fcba7316b45dfa51461b40f2a541a)

### Steps To Reproduce

```markdown
1. Go to JS objects and create an alert message. Bind this to a button widget as an onClick trigger.
2. Run this function from within JS object and via button widget and observe that the alert msg is displayed.
2. Change function name and add an embedded JS Object call
3. Observe the function name refactor change in widget binding but triggering this via widget fails whereas triggering function call from within JS Object works as expected.
```

### Environment

Deploy Preview

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
in response of Refactor call, on click button js action is not refactored
