### ISSUE TITLE
[Bug]: Switch Branch DP issues

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#8397]
## Branches (Switch / Create )
@rishabhsaxena 
- [x] when the user launches the application from the feature branch the master branch application will be launched by default 
- [x] [Critical] when the user adds the new Branch and try to bind the data to the widgets then the user is switched to the master branch immediately and the page is added to the master branch
- [x] When we create a new branch the page will be deleted automatically other than the home page
- [x] The selected branch should be displayed at first by Default(or at least the Master should be displayed at first by default followed by another feature branch in alphabetical order)
- [x] If we delete the branch from the Git hub the branch name is still present in the application(we don't have any delete option internally)
- [x] When the user creates a new branch from Git hub the same branch name is not displayed in our application
- [x] add max-width to the branch button 
- [x] Create branch with "/" in name messing up with route
- [x] There's a big bug where if you're on a feature branch that is not pushed and you add a new page and drag a button and refresh the page, the page is not saved
- [x] The create branch mechanism is still not similar to github which people are used to

### Environment

Deploy Preview

### Version

Cloud

**Comment by hiteshjoshi** [comment]
Issue - When the user creates a new branch from Git hub the same branch name is not displayed in our application 
Moved as a new issue.
