### ISSUE TITLE
[Feature]: Show list of applications sorted by last accessed date of user

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#8398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In the homepage, users can view list of applications. The applications are shown in groups of organizations. List of application under an organization is sorted by it's name. It might be helpful for the user, if they are sorted by the last accessed date of that particular user. For example, If A1, A2, A3 are three applications under an organization. If user 1 opens A1 first and then A2, user1 will see the applications in this order:

- A2
- A1
- A3

If user2 opens A3 first, then A1 and A2 at last, user2 will see them in this order:

- A2
- A1
- A3

### Why should this be worked on?

This will help users to quickly find the apps which they use mostly. An organization may have a large number of apps and as our user management is at organization level, each user will see all of them in their home page. 

In most cases, each user will be heavily engaged with a small number of apps. So if we show each user their mostly used apps first, they'll be able to open them more easily.

**Comment by zzgvh** [comment]
I just came to say, to me this is a very nice idea. When developing, I often create small test apps, and they get left around since you might wanna access them later. So after a while you have a ton of "cruft", and then you have a few "real" apps. 

Having reached this state, having the apps sorted by last access time would be very useful!

Another idea might be to tag the apps, and sort on the tags, but that's probably over complicating things...

**Comment by RakshaKShetty** [comment]
@nayan-rafiq  Have a few queries on the below scenario is it okay The sorting doesn't happen in the below scenario

- [ ] In this Feature if the user edits the application name from the home page and export the app then the application won't be displayed at the top 
- [ ] If the user export the app then sorting doesn't happen
- [ ] When the user Duplicate the application then Both the original and the duplicated app shows first in the sorted order

**Comment by nayan-rafiq** [comment]
@RakshaKShetty exporting an application does not change it so the source app should not affect the sorting. I'm checking other two.

**Comment by nayan-rafiq** [comment]
@RakshaKShetty please reopen this. There was a bug when duplicated application as well as source application - both are sorted. Only new one will be shown first, source application position will be unchanged. 

I'm going to fix this.

**Comment by prgueza** [comment]
@nayan-rafiq imho apps should be ordered by name as this rarely changes and the sorting stays "static". In our experience when a user access multiple applications througout the day the order keeps on changing and it gets harder to find specific applications as these are never found in the same spot. We used to use codes for sorting the applications (1.1, 1.2, 2.1 and so on) and now the applications list view which was very neat became a huge mess. 

This said, i can see the benefits of this sort by last access feature, and i see your point, but i think that ideally each individual user should be able to choose whether to see them ordered by last access or by name.

**Comment by nayan-rafiq** [comment]
Tagging @areyabhishek also here. @prgueza Do you suggest that we should take input from user for the sort order and persist that choice? For example, user will be able to set the sort order and apps will be sorted based on the choice.

**Comment by prgueza** [comment]
@nayan-rafiq Thanks for your quck answer! 

And yeah! The closest example for this that I could find is this sorting picker that github uses for proyects within a repo.

![Screenshot 2022-01-11 at 13 30 07](https://user-images.githubusercontent.com/24815750/148942945-c7786222-3bed-4b09-b517-3d2ff5e65f71.png)

As far as I'm concerned there is no pagination for the applications fetching service so it could be implemented as just a client sorting mechanism. Ideally the selected option *should* be remembered either by keeping track of it in the user's settings or just in the browser local storage. 
 
As for what would the default sorting method be, I'd leave it up to you and the community. For us it makes more sense to have the 'sort by name' as the default option, but I can see how this could not be the most popular opinion.
