### ISSUE TITLE
[Bug] Clicking on organization names does nothing

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#840]
## Description

Upon clicking on the name of the organization, nothing happens except for a few times. Looks like there needs to be a name for the scroll to work. 

Also, adding a smooth scroll may be more user friendly.

### Steps to reproduce the behavior:

Screencast: https://recordit.co/FS56YQfC80

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Microsoft Edge

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #807  different result but the root cause is the same
