### ISSUE TITLE
[Bug]: JS object name inside console log or alert msg is shown as a cyclic dependency error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any function name within double quotes used in either console log or in alert message should not be picked up for validation. Currently, we see a cyclic dependency error on such code lines.

![image](https://user-images.githubusercontent.com/79509062/136773548-b45f62ad-a419-4ae8-af98-5c04adbbb715.png)
![image](https://user-images.githubusercontent.com/79509062/136773646-ec656106-ed3a-4b55-9237-4e3c55593e02.png)

Rest of the function fails to run if we comment out these lines.
![image](https://user-images.githubusercontent.com/79509062/136774677-a346186f-058b-419a-8326-2693d7241328.png)

### Steps To Reproduce

```markdown
1. Go to JS Objects and enter a console log line to print JS Object name and observe the cyclic dependency error on run
2. Use the JS object name in a showAlert() function and observe the same error
3. Comment out this line and run the object - observe that cyclic dependency error is displayed and the rest of the code lines fail to run
```

### Environment

Release

### Version

Cloud

**Comment by hetunandu** [comment]
Fixed with #8617

**Comment by ramsaptami** [comment]
@hetunandu So there's no cyclic dependency error anymore on JS objects. But query names mentioned inside of a console.log on widget properties displays a message for onPage trigger
![image](https://user-images.githubusercontent.com/79509062/140484008-30111eff-5b2c-48b5-a413-dbd318319689.png)

**Comment by ramsaptami** [comment]
This seems to be occurring still
![image](https://user-images.githubusercontent.com/79509062/141826902-1ca4c095-7f6e-4752-a945-e1f8ec4754ee.png)

**Comment by hetunandu** [comment]
@ramsaptami we had to revert the change that fixed this. This will be added back soon. cc @eco-monk
