### ISSUE TITLE
[Bug]: Refactor function name in JS error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When function name is changed and a call to this function from another JS object then refactor throws an error and function call fails

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/1f0f8c745dab41978a655fe7d4a5cb9d-00001.gif)](https://www.loom.com/share/1f0f8c745dab41978a655fe7d4a5cb9d)

### Steps To Reproduce

```markdown
1. Function of JSObj1 is called in JSObj2
2. Change function name of JSObj1
3. Observe the error when your switch to JSObj2
4. Change the name again and observe that the name does not change
```

### Environment

Deploy Preview

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami please verify
