### ISSUE TITLE
[Bug]-[1966]:Connection pools in Mysql plugin lead to runaway connections

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#8419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to invoke a MySQL query in a loop within Appsmith, the R2DBC library for MySQL is not using the existing connection object and ends up creating a new connection for each query. This should not be the case. We should pick a connection from a pre-specified pool of connections and only use those. Else, we might end up bringing down MySQL servers with the error "Too many connections"

### Steps To Reproduce

```markdown
1. Create a MySQL query action
2. Invoke this action using a for-loop on click of a button
3. Monitor the existing number of connections on the MySQL server.
```

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
mysql 6m usage: 983
applying 5% reach of this problem: 50

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.25 |
