### ISSUE TITLE
[Bug] Query error: Please check your internet connection

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#842]
## Description

Running a JOIN query doesn't return any results and throws "Please check your internet connection"

### Steps to reproduce the behavior:

Screencast: https://recordit.co/nWibAO2VlJ

### Important Details
 - Version: Cloud
 - OS: Windows 10
 - Browser: Microsoft Edge

**Comment by ng29** [comment]
Hey @Nikhil-Nandagopal 

Can i work on this? ?

**Comment by Nikhil-Nandagopal** [comment]
@ng29 this is a slightly more invovled issue since we need to find how to reproduce it. I suggest you start with our list of good first issues 😄

**Comment by Nikhil-Nandagopal** [comment]
We now have an option to increase query timeouts
