### ISSUE TITLE
[Bug]: File is corrupted when pushing PNG from image picker through POST via multipart/form-data

### ISSUE THREAD

**Issue by 96imranahmed** [appsmithorg/appsmith#8423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I attempt to create a POST request using `multipart/form-data`, the server receives a corrupted file

**Reproduction below:** 
1. Go to imgbb.com, and create a configuration key for their api (POST request on `https://api.imgbb.com/1/upload?expiration=100&key=XXXXX`)
2. Set `content-type` to `multitype/form-data` and body as per screenshot below (e.g.,`{{FilePicker.files[0]}}`)
3. Set `FilePicker` file type to `binary` (also fails for `base64` and `text`)
4. Try POST the request. Request fails with following error in Appsmith

`{
  "status_code": 400,
  "error": {
    "message": "Can't get target upload source info",
    "code": 310,
    "context": "CHV\\UploadException"
  },
  "status_txt": "Bad Request"
}`

Note: Posting the exact same file with a Postman configuration gives a valid response (see example below):

`{
    "data": {
        "id": "HhgPWDY",
        "title": "245041252-239228178183498-5503923721507175673-n",
        "url_viewer": "https://ibb.co/HhgPWDY",
        "url": "https://i.ibb.co/FH7YSbJ/245041252-239228178183498-5503923721507175673-n.png",
        "display_url": "https://i.ibb.co/FH7YSbJ/245041252-239228178183498-5503923721507175673-n.png",
        "size": 5764,
        "time": "1633956377",
        "expiration": "100",
        "image": {
            "filename": "245041252-239228178183498-5503923721507175673-n.png",
            "name": "245041252-239228178183498-5503923721507175673-n",
            "mime": "image/png",
            "extension": "png",
            "url": "https://i.ibb.co/FH7YSbJ/245041252-239228178183498-5503923721507175673-n.png"
        },
        "thumb": {
            "filename": "245041252-239228178183498-5503923721507175673-n.png",
            "name": "245041252-239228178183498-5503923721507175673-n",
            "mime": "image/png",
            "extension": "png",
            "url": "https://i.ibb.co/HhgPWDY/245041252-239228178183498-5503923721507175673-n.png"
        },
        "delete_url": "https://ibb.co/HhgPWDY/782574610367920e2a46ceefe00322e8"
    },
    "success": true,
    "status": 200
}`

![image](https://user-images.githubusercontent.com/8015435/136808660-9202ed34-e3d4-4472-b166-39ab1670ae13.png)

### Steps To Reproduce

```markdown
See above for detailed reproduction
```

### Environment

Release

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@96imranahmed thank you for reporting this! We'll look into this ASAP
