### ISSUE TITLE
[Bug]: Add support for raw binary data in actions

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#8431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the REST API is unable to post raw binary data to endpoints. We only support base64 encoded data for such operations. Some endpoints mandatorily need binary data though, so our proxy server should handle such data as well.

### Steps To Reproduce

```markdown
Create a REST API and try to use multipart/form-data with raw data
```

### Environment

Production

### Version

Cloud

**Comment by 96imranahmed** [comment]
For those who are stuck with this, you can stand-up a middleman API using `FastAPI` in a few lines of code

```
from fastapi import FastAPI, File, UploadFile
import base64
import requests

app = FastAPI()
ENDPOINT = "XXXXX"
USERNAME = "YYYY"
PASSWORD = "ZZZZ"

@app.post("/upload")
def read_upload(thumbnail: UploadFile = File(...)):
    contents = thumbnail.file.read().decode("utf-8")
    contents = contents[contents.index(",") + len(",") :]
    resp = requests.post(
        ENDPOINT,
        files={
            "thumbnail": (
                thumbnail.filename,
                base64.decodebytes(str.encode(contents)),
                thumbnail.content_type,
            )
        },
        auth=(USERNAME, PASSWORD),
    )
    return resp.json()
```
 
All you need to do now is configure your `FilePicker` to send data as `Base64` and use `{{ImagePicker.files[0]}}` in your POST request (you still POST as File)
