### ISSUE TITLE
[Bug]: Number Input Don't Get Reset On Form Submit

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#8437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using a resettable form, the number input widget doesn't reset. I've added a video here to show this

> It's also noteworthy to mention that force resetting the input widget with the `resetWidget` function still doesn't work

https://user-images.githubusercontent.com/17744578/136925939-44dcc380-1a2d-47d4-a525-6636703aacf2.mp4

### Steps To Reproduce

```markdown
I've illustrated the steps to reproduce this in the attached video
```

### Environment

Production

### Version

Cloud

**Comment by c64bob** [comment]
I can confirm this behaviour. I just encountered the same bug and was looking for an open issue.

**Comment by Nikhil-Nandagopal** [comment]
@cokoghenun @c64bob this seems to be working for me. Can you please share the steps to reproduce this issue?

**Comment by c64bob** [comment]
**Steps to reproduce**

1. Insert a form widget.
2. Insert an input widget and set to data tpye number.
3. Insert a button widget, label it reset, and choose as onClick event to reset form.
4. Type a number into the input widget, and click reset => the number is still visible in the input widget

I'm using v1.6.3 in a Docker container.

**Comment by Nikhil-Nandagopal** [comment]
I think I found the issue. This seems to specifically be an issue after the app is deployed in view mode.
@somangshu @dilippitchika can we please prioritise this?
