### ISSUE TITLE
[Bug]: Git/Debugger bar at bottom is overlapping the widgets and property pane

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Widgets in entity explorer, widgets on canvas and property pane is not visible at the bottom of the screen due to new design of git/debugger.

<img width="1919" alt="Screenshot 2021-10-12 at 2 21 29 PM" src="https://user-images.githubusercontent.com/83569920/136924812-be20fb2c-4415-4a88-8128-19da1d7e4e11.png">

### Steps To Reproduce

```markdown
Drag and drop few widgets on canvas and observe at the bottom of the screen.
```

### Environment

Production

### Version

Cloud

**Comment by Rishabhkaul** [comment]
@vivekverma2312 this can be closed right?
