### ISSUE TITLE
[Bug]-[97]:Inconsistency in the field title of the property pane

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For few of the Widgets the text title is displayed as **colour** in some places and **color** in some places.

Current status:

1.Container widget - Background **colour**, Border **colour**  and Shadow **color**
2.Audio Recorder - Icon **color** , Background **color**
3.Button Widget - Button **color**, Shadow **color**
4.Divider Widget - Divider **color**
5.Form Widget - Background **colour**, Border **colour**  and Shadow **color**
6.Icon Widget - Button **color**, Shadow **color**
7.Iframe Widget - Border **color**
8.List Widget - Background , Item Background - **text colour is not displayed** 
9.Menu Widget - Icon **color**, Text **color**, Background **color** , Menu **color**, Shadow **color**
10.MultiTeeSelect - Label text **color**
12.Rate Widget - Active **color**, Inactive **color**
13.Stat Box Widget - Background **color**
14.Table Widget - Cell Background -**text colour is not displayed for Cell Background**  , Text **color**
15.Text Widget -  Cell Background -**text colour is not displayed for Cell Background** , Text **color** , Border **Colour**
16.TreeSelect - Label text **color**

### Steps To Reproduce

```markdown
1.Launch appsmith app in release or Prod environment 
2.Drag and drop most of the widgets , open property pane and check the field title of colour
```

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@AR10X This is all your. Assigning this to you now. The change will be:
- We follow US english and hence we will use `Color` everywhere, In other words replace `Colour(s)` to  `Color(s)`

**Comment by btsgh** [comment]
FIXED FOR ALL OF THE CASES MENTIONED IN THE BUG EXCEPT THE FOLLOWING CASE:

Table Widget - Cell Background - The text "color" is not displayed for Cell Background in the sub widget properties (Step/Task/Status properties)

**Comment by somangshu** [comment]
@btsgh can you please add a screenshot, Not able to clearly understand this

**Comment by btsgh** [comment]
@somangshu - 
<img width="771" alt="CellBackgroundColor" src="https://user-images.githubusercontent.com/101863839/167562111-58542ee0-6a1f-4650-bc92-c99db971c3d4.png">

**Comment by somangshu** [comment]
@btsgh kindly also point out the change required, Do we need to change the copy? I am not sure

**Comment by btsgh** [comment]
It is just a minor change required .. As per the original bug raised. 
Currently the property text reads as "Cell Background"
It should read as "Cell Background Color"

Refer the bug details point 14.
<img width="791" alt="MainWidgetProperties_Text" src="https://user-images.githubusercontent.com/101863839/167564650-8ac0afc6-32af-4756-b0f5-9aa007051044.png">

**Comment by somangshu** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 97 |
| Effort (months)  | 0.5 |

**Comment by priyanka-mahour** [comment]
@somangshu can I work on this issue?

**Comment by rohitagarwal88** [comment]
@priyanka-mahour : This issue is fixed! Marking it as closed. You can pick up other issues.
