### ISSUE TITLE
[Bug]: Text Widget -The Cell background and Text size field evaluated values are undefined after enabling JS

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by enabling JS on the Cell background colour and the Text Size field on the text widget, the evaluvated value is 'undefined'

https://github.com/appsmithorg/appsmith/issues/8439

### Steps To Reproduce

```markdown
1.Launch appmsith app in release/Prod environment
2.Drag and drop text widget
3.Open property pane 
4.Choose cell background colour an enable JS and click on the cell background colour field and observe the evaluated value 
5.Similarly check for the text size field and observe
```

### Environment

Release

### Version

Cloud

**Comment by keyurparalkar** [comment]
@YogeshJayaseelan, are these the expected value as undefined mentioned in this issue?:

![Screenshot from 2021-12-01 11-45-49](https://user-images.githubusercontent.com/14138515/144182297-6dd7cf18-0d6e-400e-b852-bcf31bc0b555.png)

![Screenshot from 2021-12-01 11-46-04](https://user-images.githubusercontent.com/14138515/144182341-4fe53b2f-39c5-4c1a-9e4d-de4375a6f173.png)
