### ISSUE TITLE
[Bug]:  Datasource Dropdown  is not displayed to user after the enter is cleared 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

API Datasource list is not displayed to the user when the user deletes the entered API once 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/19f02e822aed42a8a88b10fc807cafcd-00001.gif)](https://www.loom.com/share/19f02e822aed42a8a88b10fc807cafcd)

### Steps To Reproduce

```markdown
1) Navigate to API pane 
2) Save the data source
3) Navigate back to the API pane
4) Now delete the API 
5) click on the API field
and observe
```

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@albinAppsmith can we fix the design system here? The enter is not captured in the URL field
