### ISSUE TITLE
[Enhancement]: Autocomplete and linting features must be available under subfields of Action on property pane and under table widget's column settings

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, autocomplete and linting works on all fields of the property pane except for the fields that are expanded when trigger field is using dropdown options (Show Modal, Download, Reset Widget etc). Also, column settings of table widget need this enhancement.

![image](https://user-images.githubusercontent.com/79509062/137079785-9f83da85-8377-41d9-9304-b67d08b5529c.png)

### Steps To Reproduce

```markdown
1. Click on dropdown on trigger fields present under Actions
2. Observe that autocomplete and linting is not currently supported here
```

### Environment

Release

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
@rimildeyjsr could you confirm if this comes under the scope of the new action selector?

**Comment by bharath31** [comment]
@Rishabh-Rathod we will take this up separately after we complete the action selector refactor project.

**Comment by bharath31** [comment]
@ramsaptami autocomplete works on all JS properties when users start typing within `{{ }}`
