### ISSUE TITLE
[Bug]: Table - default row is not deselected (on header checkbox click)

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#8492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When `defaultSelectedRow` is assigned a value. 
It prevents the row from being de-selected., when the header checkbox is clicked.

![Screen Recording 2021-10-13 at 12 10 39](https://user-images.githubusercontent.com/66776129/137081083-7eb02e2a-a3ec-418d-908e-41ee16b365c8.gif)

-----------------------------------------

The row selected by default should be de-selected, when the header checkbox is unchecked.

### Steps To Reproduce

```markdown
- enable `multi row selection` on a table
- assign a value to `defaultSelectedRow`
- uncheck the header checkbox
- The default selected row still remains selected
```

### Environment

Production

### Version

Cloud

**Comment by eco-monk** [comment]
@Ian-Yy, thanks for reaching out and taking time to look at this.!
Unfortunately, this could be a complex issue to start with.

So, I suggest looking at the issues tagged `Good first issue` and `hactoberfest` to see you find anything interesting.!

**Comment by Ian-Yy** [comment]
Hi @eco-monk, I've went through issues tagged with `Good First Issue` and `Hacktoberfest` and all of them are assigned. That's why I'm going through other issues too. Do you mind if I take a day or 2 to look at this and if its really beyond my capability, I will let you know?

**Comment by kaleeaswari** [comment]
Hi, can I get this assigned?

**Comment by Rishabh-Rathod** [comment]
Hey👋🏼  @kaleeaswari, thanks for showing interest in this issue.

Unfortunately, this issue is not open for external contribution yet. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22)

Looking forward to seeing your contributions :)

**Comment by somangshu** [comment]
this is resolved
