### ISSUE TITLE
[Feature]: Parse-platform back-end integration

### ISSUE THREAD

**Issue by slysiou** [appsmithorg/appsmith#8494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Parse-platform is an open-source Back-end as a Service (BaaS): https://parseplatform.org/

Parse provide user authentication and ACL on each record of the database (in a better way than firebase from my point of view).
Parse dashboard is simple to design data structure.
Parse provide a GraphQL api to access data and launch cloud function.

It is already possible to connect Appsmith and Parse-platform. But, more API integration could make it a killer bundle 

### Why should this be worked on?

Low effort to integrate. Parse Platform + Appsmith would provide a killer solution on the market compare to table oriented solution (airtable...) or no code apps developement.

**Comment by Rishabhkaul** [comment]
@slysiou Wondering incase you were ever able to try this, given that the GraphQL integrations was released some time back.

**Comment by slysiou** [comment]
Yes, it works now. But, I am looking to add the parse package to simplify the code.
