### ISSUE TITLE
[Bug]: Filter does not show result when Server Side pagination is enabled

### ISSUE THREAD

**Issue by SG2019** [appsmithorg/appsmith#8505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add a filter on table with multiple pages, the result from the filter only shows up on the page the record is.

I expect the table filter to show all the results irrespective of page number I am on.

### Steps To Reproduce

```markdown
1. Create table with multiple pages
2. Lets say the record 'A' is on page 3
3. Go to page 1
4. Add filter to get the record 'A'
5. No result shows up on page 1 and page 2
6. Navigate to page 3
7. The filter result shows up on page 3
```

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@SG2019 if you disable server-side pagination then you will need to return your entire dataset. This is not recommended if the number of records are larger than 100. You can enable custom server-side filtering using any input / select / date etc widget. This is a document that describes achieving this 
https://docs.appsmith.com/core-concepts/displaying-data-read/display-data-tables#server-side-searching-filtering
