### ISSUE TITLE
[Bug]: While importing the application page sequence does not match with the source application

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#8508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we do import-export the imported application does not have the same page sequence as to exported application. 

### Steps To Reproduce

```markdown
1. Create new application
2. Add pages
3. Export application
4. Import the application and check the page index
```

### Environment

Production

### Version

Cloud

**Comment by hiteshjoshi** [comment]
@abhvsn can we close this?

**Comment by RakshaKShetty** [comment]
reopening the issue we can repro it when app is imported in the new org
