### ISSUE TITLE
[Bug]: Omnibar and debugger shortcuts

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#8511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You cannot trigger the omnibar and debugger when a user is focused on a field. This kills usage of the feature.

### Steps To Reproduce

```markdown
1. Create a table
2. Focus on the table data
3. Hit cmd + k or Cmd +d.
4. The omnibar and debugger don't open
```

### Environment

Production

### Version

Cloud

**Comment by pranavkanade** [comment]
@Nikhil-Nandagopal this is the limitation of the `blueprintjs/core` lib itself. There is newer component available in higher version (`3.39.0`) of this lib which will solve this issue - https://github.com/palantir/blueprint/wiki/3.x-Changelog#blueprintjscore-3390

Although, if we update the lib to `v3.39.0` it'll break `Popover` and `Menu` which we use extensively.
