### ISSUE TITLE
[Docs] Create Documentation for Download function

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#852]
## Describe the problem

We don't have documentation for the internal action that can be used to download data on appsmith. This action can be triggered by a button by setting its onClick property

**Comment by hetunandu** [comment]
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone looking to start contributing to the repo. Make sure you read our [docs contributions guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before starting.

The signature of the function is mentioned [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/utils/autocomplete/EntityDefinitions.ts#L248)

I'm here if you need any help fixing this so feel free to tag me on this thread 😄

**Comment by deepakchethan** [comment]
@hetunandu, I can take this up if this is still up for grabs

**Comment by hetunandu** [comment]
Hey @deepakchethan! Welcome to the Appsmith community 😄 assigning this to you. Do read the docs linked and incase of any doubts let me know. You can ask me for a review once you raise the PR.

**Comment by deepakchethan** [comment]
Thank you @hetunandu, can you please take a look at https://github.com/appsmithorg/appsmith-docs/pull/13.

**Comment by hetunandu** [comment]
Approved and merged! 🎉 Thanks a lot of this @deepakchethan hope to see your contributions on some other issues as well 🙌

**Comment by hetunandu** [comment]
Fixed by [appsmithorg/appsmith-docs#13](https://github.com/appsmithorg/appsmith-docs/pull/13)
