### ISSUE TITLE
[Bug]: New user added to org does not update on the org counter until page is refreshed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a new user is added to an org from home page then member count does not automatically increase until page is refreshed.

![image](https://user-images.githubusercontent.com/79509062/137262421-37a70007-adb4-474a-bb1b-f3b45c2e3ac8.png)

### Steps To Reproduce

```markdown
1. Add users to org and observe the count does not increase until home page is refreshed
```

### Environment

Release

### Version

Cloud

**Comment by sbalaji1192** [comment]
@RodolfoNei This issue is all yours. Please go through our [contributing guidelines](https://github.com/appsmithorg/appsmith/blob/922ab5f008579d7f03e0c2deb7b6b8428d2c09b2/CONTRIBUTING.md). :)

**Comment by ankitakinger** [comment]
This seems to have been fixed and so now works as expected.
