### ISSUE TITLE
[Bug]: Default icon is not displayed by changing the table column type to icon button 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by changing the table column type to icon - default icon is not displayed due to which that particular column looks like empty 

https://loom.com/share/0a351269eaac495cbf01d6206ab21f98

### Steps To Reproduce

```markdown
1.Launch Appmsith app in release/Prod Environment 
2.Drag and drop table widget 
3.Change any of the column type to icon and observe
```

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
Lets make the `add` icon default here. We can take this up with the #8527
