### ISSUE TITLE
[Bug]: JS object missing/deleted needs to be handled for dependency when bound to a widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8535]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior
- When in js object Text1 is referred and later Text1 was created it still throws an error

- When JSObject1.itsFunc() is bound to a widget and this object is deleted, 2 things happen:

  1. Missing/deleted object is not highlighted on widget binding immediately after deletion
  2. After a delayed period (say next day), if JSObject1 is recreated but function name is different and widget binding shows an error for undefined object and not for incorrect function name

### Steps To Reproduce

```markdown
1. Create a JS object and bind this object to a widget and observe the above 2 scenarios
```

### Environment

Release

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
@ramsaptami this is fixed. can you confirm so that we can close this?

**Comment by ramsaptami** [comment]
non-existent function of a JS object bound to a widget is not showing up for lint error which used to happen before
![image](https://user-images.githubusercontent.com/79509062/143391150-b27348b7-e58f-40d2-bd2d-1f0577e462b3.png)

**Comment by ApekshaBhosale** [comment]
can you please mention on which env is this happening? @ramsaptami

**Comment by ramsaptami** [comment]
This is on release

**Comment by ramsaptami** [comment]
Closing this since function name validation is being tracked in #11663 and the actual issue raised has been fixed

**Comment by ramsaptami** [comment]
Updating here on action trigger that persists behaviour even after bound JSObject has been deleted. Page refresh removes this dependency but app saving action does not re-render changes
https://www.loom.com/share/c5b1be5172694b218d2e16f2832e0953

**Comment by ApekshaBhosale** [comment]
same as https://github.com/appsmithorg/appsmith/issues/11663
