### ISSUE TITLE
[Docs] Create documentation for navigateTo function

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#854]
## Describe the problem

We do not have documentation for our navigateTo function today. The function can be triggered by the action selector of a widget such as the onClick of a button.

**Comment by hetunandu** [comment]
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone looking to start contributing to the repo. Make sure you read our [docs contributions guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before starting.

The signature of the function is mentioned [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/utils/autocomplete/EntityDefinitions.ts#L228)

I'm here if you need any help fixing this so feel free to tag me on this thread 😄

**Comment by kichloo** [comment]
@hetunandu I want to work on this issue,

**Comment by mohanarpit** [comment]
@kichloo Welcome to Appsmith! 🎉 

Go for it! Happy hacking!

**Comment by kichloo** [comment]
@mohanarpit This issue seems a bit difficult as I have not worked extensively on it. So, I think it should be unassigned so that it does not stop any other user from contribution,

**Comment by Nikhil-Nandagopal** [comment]
@kichloo I've unassigned you from this. If you'd still like to take this up, I'd be happy to talk to you about it on discord

**Comment by visibleajay** [comment]
@Nikhil-Nandagopal Please assign this to me. Thank You!.

**Comment by visibleajay** [comment]
Added a [PR](https://github.com/appsmithorg/appsmith-docs/pull/23/files) for this issue.

**Comment by hetunandu** [comment]
Fixed by [appsmithorg/appsmith-docs#23](https://github.com/appsmithorg/appsmith-docs/pull/23)
