### ISSUE TITLE
[Bug]: Date Picker widget, Date Format dropdown introduces scrollbar in the body.

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#8545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the property pane, when the `Date Format` property dropdown is opened, it adds a scrollbar to the body rather than the dropdown options area itself.

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/c863368b1b4f4c60b6c52c3e078aeaa9-00001.gif)](https://www.loom.com/share/c863368b1b4f4c60b6c52c3e078aeaa9)

### Environment

Production

### Version

Cloud

**Comment by vivekverma2312** [comment]
Working fine on #7361
