### ISSUE TITLE
[Enhancement]: To have button styling properties for Button column type

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that currently for table button column type - The button styling properties (Border Radius, Box shadow, Shadow Colour, Icon, Icon Alignment) are not available

### Steps To Reproduce

```markdown
1.Launch Appmsith app in release/Prod Environment
2.Drag and drop table widget 
3.Change any of the column type to button
4.Check for the button styling properties
```

### Environment

Release

### Version

Cloud

**Comment by areyabhishek** [comment]
@somangshu @wmdev0808 Can this issue be prioritized? This is a bug because every button type column has styling options except for the button

**Comment by sbalaji1192** [comment]
@jsartisan This issue should be fixed as part of #9146, right?

**Comment by jsartisan** [comment]
Yes

**Comment by somangshu** [comment]
Closing this in favour of #9146
