### ISSUE TITLE
[Docs] create documentation for closeModal Function

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#855]
## Describe the problem

We do not have documentation for our closeModal function today. The function can be triggered by the action selector of a widget such as the onClick of a button

**Comment by hetunandu** [comment]
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone looking to start contributing to the repo. Make sure you read our [docs contributions guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before starting.

The signature of the function is mentioned [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/utils/autocomplete/EntityDefinitions.ts#L240)

I'm here if you need any help fixing this so feel free to tag me on this thread 😄

**Comment by deepakchethan** [comment]
Hello @hetunandu, I worked on this issue as well, please review https://github.com/appsmithorg/appsmith-docs/pull/14

**Comment by mohanarpit** [comment]
@deepakchethan Thanks! For the future, please claim an issue before you start working on it. It ensures that there's no duplicate work happening across the board. If you hadn't commented here, we may have assigned this issue to someone else and close your PR in favour of them.

**Comment by deepakchethan** [comment]
Thank you @mohanarpit

**Comment by hetunandu** [comment]
Approved and merged! 🎉 Thanks @deepakchethan 👯‍♂️
