### ISSUE TITLE
[Feature]: Allow users to suppress error alerts when using custom error callback in run

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#8553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Sometimes, the user wants to show a custom message in errors alerts whenever their API fails. So a way to suppress the default messages is needed.

### Why should this be worked on?

This feature gives users more control over the error messages whenever API/Query fails.

**Comment by Nikhil-Nandagopal** [comment]
We are suppressing all system error messages in view mode #6261
Hence closing this
