### ISSUE TITLE
[Bug]: Helm readme references non existing repo

### ISSUE THREAD

**Issue by erSitzt** [appsmithorg/appsmith#8557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://github.com/appsmithorg/appsmith/tree/release/deploy/helm

### Describe the problem

The url for the helm-repo does not exist.

### Describe the improvement

Correct readme or remove instructions regarding non existent repo

**Comment by Nikhil-Nandagopal** [comment]
Hello we're still working on helm internally. This is not available for everyone yet

**Comment by jalberto** [comment]
Helm support has been announced in the latest blog post, still the repo URL in the docs is invalid

**Comment by sharat87** [comment]
Hey, thanks for sharing your experiences. I am currently working on getting this fixed and be ready to use. Sorry for the trouble.

**Comment by jalberto** [comment]
Probably worth reopening this issue until fixed

**Comment by PatrickHuetter** [comment]
I can confirm that the repo doesn't exist. Hopefully it will work soon :)

**Comment by sharat87** [comment]
This is fixed.
