### ISSUE TITLE
[Bug]: Table widget's mouse over doesn't as expected

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#8560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found that the hover styles on the table were not getting applied throughout the table row. It was just happening with only a column as you see in the following video.

https://user-images.githubusercontent.com/10436935/137500984-7b2f8d7b-07d1-483f-9727-d9870513f941.mov

This was happing only with one table out of the two tables I have in my application.

Here's the application which is having this problem: 
[Table Hover Issue.txt](https://github.com/appsmithorg/appsmith/files/7353953/Table.Hover.Issue.txt)
(Rename this to json and import)

### Steps To Reproduce

```markdown
Change the cell background color of a column to see that mouseover is not working in that column
```

### Environment

Production

### Version

Cloud

**Comment by kaleeaswari** [comment]
Hi, can I get this issue assigned?

**Comment by vivekverma2312** [comment]
@aswathkk I am still able to repro the issue on the application shared by you thus reopening the issue.

**Comment by somangshu** [comment]
@vivekverma2312 can you find the steps to reproduce?

**Comment by techbhavin** [comment]
close this issue for now , can not reproduce

**Comment by aswathkk** [comment]
@techbhavin I'm able to reproduce this in my application.
Check this one: https://app.appsmith.com/applications/61696209770d321d435c371c/pages/61696209770d321d435c371e

**Comment by techbhavin** [comment]
In Observation following point noticed 
 
 when we change the background colors of the cell then mouse hover is not worked as expected the reason is cell background-color is not overridden with row background-color 
 
 
![image](https://user-images.githubusercontent.com/58818598/150084505-5fbbe867-4bee-484f-b1f3-667aed4cba11.png)

cc @somangshu  @aswathkk  @dilippitchika

**Comment by somangshu** [comment]
@techbhavin we should override the hover color with the highest priority. This is a valid bug

**Comment by somangshu** [comment]
this is linked to #4354

**Comment by somangshu** [comment]
@dilippitchika please take a call is this is duplicate 👆 and needs to be closed

**Comment by sbalaji1192** [comment]
related to #11316

**Comment by shwetha-ramesh** [comment]
Duplicate of #11316 which is not fixed yet.
