### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sheetal2001p** [appsmithorg/appsmith#8561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Asynchronous functions in JavaScript behave differently than other functions in two important ways:

- The return value is always a Promise.

- You can use the await operator inside of them.

The primary reason to use asynchronous functions is typically to use the await operator.
There are some functions in some files with no await operator.

### Steps To Reproduce

```markdown
1. Go to app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Comments/AddComments_spec.js
2. In line 14 an async function has no await operator in function call inside it.
3. Go to app/server/scripts/node/acl-migration.js
4. In line 277 an async function has no await operator in its return statement.
```

### Environment

Release

### Version

Cloud

**Comment by sheetal2001p** [comment]
Hey @Rishabh-Rathod  I want to solve this can I?

**Comment by Nikhil-Nandagopal** [comment]
Hi @sheetal2001p 👋 unfortunately this is a very complex solution and we are working on it internally. Please do have a look at our many good first issues to contribute
