### ISSUE TITLE
[Docs] create documentation for show alert function

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#857]
## Describe the problem

The documentation page for the show alert function is missing. The function can be triggered by the action selector of a widget

**Comment by hetunandu** [comment]
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone looking to start contributing to the repo. Make sure you read our [docs contributions guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) before starting.

The signature of the function is mentioned [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/utils/autocomplete/EntityDefinitions.ts#L232)

I'm here if you need any help fixing this so feel free to tag me on this thread 😄

**Comment by StTronn** [comment]
Hey! I would love to start working on this.  Since the docs are on a separate repo for now do I need to clone this repo as well?

**Comment by hetunandu** [comment]
Hey @StTronn! Welcome to the Appsmith community 😄 Great to see you contributing

That is correct, you just need to fork the docs repo for this. No need to clone this repo.

**Comment by StTronn** [comment]
I have made intial pr [here](https://github.com/appsmithorg/appsmith-docs/pull/11). please review and provide feedback.

**Comment by hetunandu** [comment]
Fixed by [appsmithorg/appsmith-docs#11](https://github.com/appsmithorg/appsmith-docs/pull/11)
