### ISSUE TITLE
[Feature]: option to not send an invite email when adding an end-user

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow app admin to choose whether to send the invite email to the user or not

### Why should this be worked on?

_User on discord_
I disabled the admin email, so that end-users, when invited, would not get the autogenerated appsmith email sent to them.  It would be confusing to them. I prefer to draft an email to them that explains how to login in terminology specific to our company.   When inviting, we would like to have the option to not send an invite email when adding an end-user.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu what needs to be done here? Simply not configuring the email would work right?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal We do not have this option in the cloud, And even considering not configuring the SMTP will still generate the error on logs (only my guess). 

We should provide an option somewhere so that the config is completely disabled.
