### ISSUE TITLE
[Bug]: Whitespace in iFrame viewport while embedding the app

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8573]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Using `embed=true` causes iframes to have a large gap at the bottom of the viewport

<img width="524" alt="Screenshot 2021-10-17 at 11 19 17 AM" src="https://user-images.githubusercontent.com/11089579/137613621-17758445-dfe5-439e-a5b0-cc2bc3cad704.png">

### Steps To Reproduce

```markdown
1. Open an online JS environment, repl.it / jsfiddle.net
2. Create an iFrame
3. Add Appsmith embed URL

Its observed that there is a white space b/w the page bottom and iframe bottom.
```

### Environment

Production

### Version

Cloud

**Comment by Tooluloope** [comment]
The iframe issue seems fixed 
https://www.loom.com/share/4519ae7d7c50405cafb33bd2307a3941

**Comment by techbhavin** [comment]
@somangshu  This issue is already Fixed.

no need to fix this issue. can we ask the QA team to test this issue?

**Comment by YogeshJayaseelan** [comment]
@techbhavin @Tooluloope Verified this and there is no whitespace in the iframe viewport 

<img width="1680" alt="Screenshot 2022-01-11 at 2 36 20 PM" src="https://user-images.githubusercontent.com/35128442/148913215-7415466e-f21b-4300-9455-25cdd8ede4d4.png">

**Comment by dilippitchika** [comment]
Reopening issue, please check this - https://app.appsmith.com/applications/61d03b6fa4437918c01f9b92/pages/61e1378eeb0501052b9facfc?embed=true

**Comment by dilippitchika** [comment]
@techbhavin can you check the above comment and the git issue linked?
