### ISSUE TITLE
[Docs] Table widget is missing a gif

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#858]
## Documentation Link 

https://docs.appsmith.com/widget-reference/table

**Comment by kichloo** [comment]
I want to take up this issue

**Comment by mohanarpit** [comment]
@kichloo Since there are other issues already assigned to you. Can we start by closing them before claiming more? Don't worry, there will always be a lot of issues that you can work on.

**Comment by deepakchethan** [comment]
Hello @mohanarpit, @Nikhil-Nandagopal, Can I take this up, if it's up for grabs?

**Comment by kichloo** [comment]
@mohanarpit Ok!

**Comment by kichloo** [comment]
@mohanarpit Can I please take this issue as there is 1 issue I don't know much about which will be unassigned.

**Comment by Jain-Sanchit** [comment]
@mohanarpit  Can i take this issue? or is it done

**Comment by Yashs911** [comment]
Hi, @mohanarpit @Nikhil-Nandagopal I would like to work on this issue.

**Comment by gogetter22** [comment]
I have raised the PR for this issue https://github.com/appsmithorg/appsmith-docs/pull/32

**Comment by kichloo** [comment]
@Nikhil-Nandagopal Kindly assign this issue.

**Comment by gogetter22** [comment]
PR : https://github.com/appsmithorg/appsmith-docs/pull/37

**Comment by Lorem703** [comment]
@Nikhil-Nandagopal Sorry to say but it's literally happened the 2 time. In the previous case also, I, as per the contribution guidelines waited for the issue to get assigned to me while another person comes and makes a PR directly, without even writing a single line regarding assignment and incidentally, it is accepted. This is literally the 2 time now.

**Comment by kichloo** [comment]
@Nikhil-Nandagopal Sorry to say but it's literally happened the 2 time. In the previous case also, I, as per the contribution guidelines waited for the issue to get assigned to me while another person comes and makes a PR directly, without even writing a single line regarding assignment and incidentally, it is accepted. This is literally the 2 time now.

**Comment by Nikhil-Nandagopal** [comment]
@kichloo sorry this happened to you. It was my understanding that you already had other issues you were working on and the claims on this issue were missed by us. As a community, if someone has an issue assigned and a separate pr arises we'll favor the assignee. While if it isn't assigned and a pr arises, we'll favor the pr. 
That being said, we have a lot of open issues so I'd be happy to assign an issue or 2 to you right now if you comment on the ones you can pick up. 🙂
