### ISSUE TITLE
[Feature]-[250]:Copy pages across the applications

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#8582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today in Appsmith we can fork/clone the entire application but we can't copy pages within the applications. 

### Why should this be worked on?

The user was generating a different dashboard and had a master application from which the development was carried out. More often than not user wanted to clone the pages from the master application.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5r64s)

**Comment by anshsrtv** [comment]
We need this. Our use case:
- We have 2 Appsmith apps. One for staging and the other prod.
- We build new appsmith pages in Staging.
- Once the page gets an approval we ship it to the prod app.

**Comment by Nikhil-Nandagopal** [comment]
@anshsrtv there's now a better way to achieve that. You can sync your prod app to a git repo and import it into the staging app with different datasources so that you can just commit and pull from git to sync the changes. You can read about this here
https://docs.appsmith.com/core-concepts/git-sync

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 500 |
| Effort (months)  | 1 |

**Comment by ame-appsmith** [comment]
[Another user](https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100138688#part_id=comment-164629100138688-16836267061) requested this feature.

**Comment by AdithyaSanjay** [comment]
I built a page in one app with all queries and widgets.
But then I had to move it to another app which was like a main app.
It was quite difficult to do so as I had to recreate all the queries and widgets from beginning.
It would be helpful if there was a way to move queries , widgets and pages between apps.

**Comment by Nikhil-Nandagopal** [comment]
You can now solve this by exporting the page as well as using git
