### ISSUE TITLE
[Bug]-[10000]:Alignment issue on share and deploy button

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#8586]

**Comment by albinAppsmith** [comment]
Alignment issues with share, deploy button.

- Share icon is vertically misaligned.
- Deploy text is vertically misaligned.
- The padding beside the end of Deploy is lower than at the start of the word.
- The chevron padding is misaligned.


![Screen Shot 2021-10-12 at 10.21.22 AM.png](https://images.zenhubusercontent.com/60fe9e1e3d0320c6eb5b1f2f/1bccc08f-4605-4a5e-8e8d-95a71a52bc3e)

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 10000 |
| Effort (months)  | 0.5|

**Comment by albinAppsmith** [comment]
Issue seems to be fixed and hence closing the ticket.
![Screenshot 2022-05-04 at 11.56.38 AM.png](https://images.zenhubusercontent.com/60fe9e1e3d0320c6eb5b1f2f/0f234367-dfc7-4745-957c-5d98a9ac7ca6)
