### ISSUE TITLE
[Docs] Input widget is missing a gif

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#859]
## Documentation Link 

https://docs.appsmith.com/widget-reference/input

**Comment by utkarshbajaj** [comment]
Can you assign me this.

**Comment by Nikhil-Nandagopal** [comment]
@utkarshbajaj Thank you for your participation! I've assigned the issue to you. Here's an example of a Gif for a widget.
https://docs.appsmith.com/widget-reference/radio

**Comment by utkarshbajaj** [comment]
@Nikhil-Nandagopal you want only one gif for input widget right?

**Comment by utkarshbajaj** [comment]
I have done it, please have a look.

**Comment by Nikhil-Nandagopal** [comment]
@utkarshbajaj can you link the PR here

**Comment by utkarshbajaj** [comment]
Here: https://github.com/appsmithorg/appsmith-docs/pull/25 
I cannot reference it directly here as the correction is in a different repo (docs repo)

**Comment by utkarshbajaj** [comment]
Hey, I have updated it again!

**Comment by ashawe** [comment]
@Nikhil-Nandagopal I think you should make a label called "assigned" as well as "in review" so that people can easily sort out whether the issue has been assigned and whether the pr has been already made or not.
