### ISSUE TITLE
[Bug]: Input widget of phone number type must read spaces in bound data and accept spaces while entering number

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, phone number type input widget does not read spaces when present in bound data causing an error. Also, one is unable to use spaces in between numbers. This needs to be handled

![image](https://user-images.githubusercontent.com/79509062/137742333-8de7215c-a1e6-4bf7-822f-c56aa50cbb62.png)

### Steps To Reproduce

```markdown
1. Use a datasource that contains phone numbers that are formatted according to local "readbility" style and bind it to an input widget of Phone number type and observe the error
```

### Environment

Production

### Version

Cloud

**Comment by sbalaji1192** [comment]
@vibhandikyash Let's close this issue since we're doing a v2 of input widget with improved formatting for phone numbers. I will factor in the changes that you have done here.
