### ISSUE TITLE
[Bug]: Radio Label and value field accepts duplicate values 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the radio widget label and value field accepts duplicate value

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3d55da2bd51f46d3ba732bf32a1cbc7a-00001.gif)](https://www.loom.com/share/3d55da2bd51f46d3ba732bf32a1cbc7a)

### Steps To Reproduce

```markdown
1.Launch Appmsith app in release Environment 
2.Drag and drop radio widget 
3.Add option value 
4.Try to rename all the label name with the same name and all the value with the same value and observe
```

### Environment

Release

### Version

Cloud

**Comment by YogeshJayaseelan** [comment]
Reopening this issue as this is related to Name and Value Duplication

**Comment by dilippitchika** [comment]
@YogeshJayaseelan can you re-verify this? I cannot see this happening

**Comment by YogeshJayaseelan** [comment]
@dilippitchika Verified this now by passing duplicate key and values appropriate error message 'Values must be unique duplicate values found' error message is displayed
