### ISSUE TITLE
[Docs] Dropdown documentation is missing a gif

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#860]
## Documentation Link 

https://docs.appsmith.com/widget-reference/dropdown

**Comment by visibleajay** [comment]
@Nikhil-Nandagopal Would like to take this up? Also, should the `dropdown gif` needs to cover all options like `{{ Table.selectedRow.gender }}`, `multi-select` & `single-select`.

**Comment by Nikhil-Nandagopal** [comment]
@visibleajay please go ahead. We can 1 gif with a single select and a multi select drop-down side by side. The gif only needs to show you updating the values of the drop-down

**Comment by visibleajay** [comment]
# Dropdown

![](https://drive.google.com/file/d/1hfETpv_Yh1oA9ROb7ynvLkjUzt8AYo29/view?usp=sharing)

**Comment by hetunandu** [comment]
Fixed by [appsmithorg/appsmith-docs#22](https://github.com/appsmithorg/appsmith-docs/pull/22)
