### ISSUE TITLE
[Bug]: If the application name is too big the alignment is broken 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user adds the big application name the alignment is broken 
![image](https://user-images.githubusercontent.com/45958978/137855167-321e010a-6dd2-4467-8289-eec8d21472c4.png)

### Steps To Reproduce

```markdown
Go to the canvas
Rename the application name with some Big name 
Then we can see the Alignment break
```

### Environment

Release

### Version

Cloud

**Comment by pranavkanade** [comment]
@albinAppsmith please fix this with design system changes.
