### ISSUE TITLE
[Docs] Form widget is missing a gif

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#861]
## Documentation Link 

https://docs.appsmith.com/widget-reference/form

**Comment by coastaldemigod** [comment]
@Nikhil-Nandagopal  I can pick this one up

**Comment by Saket2** [comment]
Can I take this up?

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 go for it!

**Comment by veerutekchandani** [comment]
Can you please elaborate the issue ?

**Comment by mohanarpit** [comment]
@veerutekchandani Our documentation (link in description) needs a gif for the form widget.

Also, this issue has already been claimed. Would encourage you to find other [Good First Issues](https://github.com/appsmithorg/appsmith/labels/Good%20First%20Issue).

**Comment by Saket2** [comment]
@Nikhil-Nandagopal  , @mohanarpit  - Raised PR for this : https://github.com/appsmithorg/appsmith-docs/pull/29 . Please review.
