### ISSUE TITLE
[Bug]: Clicking on autocomplete suggestion causes the box/canvas blink

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on autocomplete causes the box/canvas blink

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0a059026c13140c6ace9e00d2b98edf2-00001.gif)](https://www.loom.com/share/0a059026c13140c6ace9e00d2b98edf2)

### Steps To Reproduce

```markdown
1. Click on autocomplete suggestion on JS editor and observe the box blink
2. Click on autocomplete suggestion on widget and observe the canvas blink
```

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment]
Reopening this since this seems to have been partially solved. onClick of suggestion on widgets does not cause the blink anymore but in JS Objects, onClick of autocomplete suggestion does not select the option, only cursor shifts position.
https://www.loom.com/share/2a599cadb12944ec89d3202834b63e64

**Comment by ApekshaBhosale** [comment]
@ramsaptami can we verify and close this please?

**Comment by ramsaptami** [comment]
Tested and verified on release. Closing this
