### ISSUE TITLE
[Docs] Filepicker documentation is missing a gif

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#862]
## Documentation Link 

https://docs.appsmith.com/widget-reference/filepicker

**Comment by kichloo** [comment]
Can I take up this issue?

**Comment by SamriddhiMishra** [comment]
I have created a pr for this https://github.com/appsmithorg/appsmith-docs/pull/16
Please review this.

**Comment by mohanarpit** [comment]
@SamriddhiMishra Thank you for creating the PR. In future, please claim an issue before you start working on it. This ensures that other folks also know that this issue has already been worked on.

**Comment by SamriddhiMishra** [comment]
Sure, @mohanarpit I will keep that in mind. Thanks!
