### ISSUE TITLE
[Bug]: Table column issues

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#8623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**DONE**
1. When I add a custom column, the column gets added at the top of the list and not at the bottom. This is a problem because when I click a button to add something, I expect it’ll be added near the button and not far away. The user won’t even notice this if they have a long list of columns `non reproducible` 
2. If I have a long list of columns(beyond the view port), I can’t move a column from bottom to top because the property pane doesn’t scroll with the card being moved. You can try this out. #4266

**PENDING**
3. Resizing of last column is difficult. It always maintains a fixed size and it can’t ever be thin. This makes it difficult to create symmetrical columns in a table.

### Steps To Reproduce

```markdown
1. Add columns to the table.
```

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@areyabhishek only the point number 3 is a valid issue

**Comment by riodeuno** [comment]
Part of #7393 talks about the last column.

**Comment by momcilo-appsmith** [comment]
@somangshu @riodeuno Do any of these points need design?

**Comment by riodeuno** [comment]
@momcilo-appsmith These seem like UI bugs and don't seem to need design effort.

**Comment by somangshu** [comment]
@riodeuno I feel #7393 is a bit different from point 3. 

Here we wish to resize the last column and not let it take the left out width. The mentioned issue is probably connected to the usability of the resize. @areyabhishek could you please correct me if I am wrong

**Comment by momcilo-appsmith** [comment]
@somangshu Hey why am I assigned to this?

**Comment by somangshu** [comment]
@momcilo-appsmith its for the 3rd point

> Resizing of last column is difficult. It always maintains a fixed size and it can’t ever be thin. This makes it difficult to create symmetrical columns in a table

I feel we need some design help here, Let me know

**Comment by dilippitchika** [comment]
Last col resizing issues, it always goes back to whatever the size was. @areyabhishek can you confirm if this is what you are referring to? 

https://www.loom.com/share/e9ada248d5c04b988a75b0e4bb0e175f

**Comment by dilippitchika** [comment]
Moving this to Product backlog, check the loom above to understand the issue

**Comment by somangshu** [comment]
@dilippitchika what is the solution, I still dont see the clarity here

**Comment by Nikhil-Nandagopal** [comment]
This seems to be working. If there is still a problem lets create a new issue for it
