### ISSUE TITLE
[Bug]: Search filtering for Multiselect

### ISSUE THREAD

**Issue by man1cato** [appsmithorg/appsmith#8624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I type into the MultiSelect widget input field, it does not filter the options like it does in the MultiTreeSelect widget. 
In its settings, there is not a config option for 'Filterable' like there is for the Select widget.

I would expect the MultiSelect widget to have this config option and behave either like the Select widget or like the MultiTreeSelect widget.

### Steps To Reproduce

```markdown
1. Create a MultiSelect widget
2. Check the settings (no 'Filterable' option)
3. Publish and try typing into the input
```

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@man1cato I can see that the list is getting filtered in the multi-select. Can you elaborate on the problem?
