### ISSUE TITLE
[Feature]: Modal widow over modal window

### ISSUE THREAD

**Issue by billyrudi** [appsmithorg/appsmith#8642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi, there is a way to open a modal over a modal, without closing the first opened?

### Why should this be worked on?

in some cases it would be very usefull

**Comment by Nikhil-Nandagopal** [comment]
@billyrudi Could you describe the cases in which you think this feature would be useful?

**Comment by danciaclara** [comment]
Here's a usecase for nested modals. cc: @dilippitchika 

https://discord.com/channels/725602949748752515/1051761935504379974/1051761935504379974
