### ISSUE TITLE
[Bug]: setInterval can be abused with multiple triggers

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#8644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a button with setInterval Action is triggered multiple times multiple events seems to be registered creating multiple triggers

expected behavior: this could be that multiple setInterval events can be not registered under the same ID

### Steps To Reproduce

```markdown
1. go to Editor page and add a button
2. In the Button's Action, select setInterval and set up the action.
3. click on the Button multiple times
4. Observe the event trigerring multiple times with interval shorter than the action's interval
```

### Environment

Production

### Version

Cloud

**Comment by hetunandu** [comment]
A developer can mark the button as disabled incase they see it could be triggered multiple times. 
Once JS editor and onPageLoad functions are out, this can be completely avoided by just marking the function to run in the beginning and not having a manual trigger for it
