### ISSUE TITLE
[Bug]: syntax error with setInterval (action template) 

### ISSUE THREAD

**Issue by locriacyber** [appsmithorg/appsmith#8645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/74560659/138059241-8e951a76-79ee-45ee-8e34-26fe01b33c47.png)

### Steps To Reproduce

```markdown
1. Create a button
2. Create Query1
3. Set the button's onClick action to {{Query1.run()}}
4. Set onSuccess to "Set Interval"
5. Set any delay to any number
6. Set callback function to any function
7. Templating weirdness happen
```

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by hetunandu** [comment]
@ locriacyber
The callback function should always be an anonymous function and can't be an expression. This is indicated by the default text populated in the field today. Closing this as it is not an issue

**Comment by locriacyber** [comment]
@hetunandu What do you mean it's not an issue? It's literally in the list of drop-down options.

@Nikhil-Nandagopal

**Comment by hetunandu** [comment]
@locriacyber What i mean to say is that it needs to be an anonymous function. Inside that function you have any number of query calls / logic you need.

![Screen Recording 2021-11-11 at 5 49 21 PM](https://user-images.githubusercontent.com/12022471/141297227-ce60a053-03b8-4f31-9ff7-7210f7105024.gif)
