### ISSUE TITLE
[Bug]: "Type / to access quick command" text is not displayed for the bottom most input box 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the User clicks on empty input at the bottom of the property pane the text "Type / to access quick command" text is not displayed
![image](https://user-images.githubusercontent.com/45958978/138070247-38780763-c001-416b-b62b-fc244b9efa3d.png)
![image](https://user-images.githubusercontent.com/45958978/138070305-f1851ba0-fff7-4077-9ea4-4b8aa63ad41b.png)

### Steps To Reproduce

```markdown
1. Go to Canvas
2. Drag and drop any one widget
3. Now go to the bottom of the property pane 
4. Click on the input box
5. The text is not displayed
```

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Lets just add additional padding to the bottom of every property pane

**Comment by bharath31** [comment]
No longer reproducible with additional padding on the latest version of every property pane
