### ISSUE TITLE
[Bug]: If the text has slash then default text "type / to access quick command text is not displayed"

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the API when the Value is already auto-filled with the / icon and if the user now click on the input box the "Type / to access quick command text is not displayed
![image](https://user-images.githubusercontent.com/45958978/138071846-ecc3ae29-4fee-43ff-aa7c-716aaa1f9a2c.png)
![image](https://user-images.githubusercontent.com/45958978/138071907-adfafc38-38a0-4ec6-b1bb-80324b4c7fad.png)

### Steps To Reproduce

```markdown
1. Go to API Pane
2. Select Post API
3. Under header tab
4. Click on the First key Now the Text is displayed
5. Now click on the Value section the default text is not displayed
```

### Environment

Release

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
in `app/client/src/components/editorComponents/CodeEditor/BindingPromptHelper.ts` in `showBindingPrompt` it checks for "/" included and we show error. 
change - const lastCharacterOfSlash = inputValue && inputValue.slice(-1);
(!inputValue?.includes("{{") && lastCharacterOfSlash !== "/"))

cc @eco-monk
