### ISSUE TITLE
[Bug]-[2000]:Incorrect lint error for not using a comma separator after a function - shows up as missing semicolon

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When IIFE function is not terminated by a comma then lint error shows up as missing semicolon instead of missing comma and the position is incorrect - this causes a parse error

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4a518506db324936b987e38a5e7335f2-00001.gif)](https://www.loom.com/share/4a518506db324936b987e38a5e7335f2)

### Steps To Reproduce

```markdown
1. Type out a JS function
2. Type out a second one below it without using a comma separator and observe the lint error and position
```

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1000 |
| Effort (months)  | <<number>> |
