### ISSUE TITLE
[Bug]: Parse error remains on screen even after removing error causing code

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a code causes parsing error and this code is removed then the parse error does not clear - this does not happen all the time though but repeating the scenario a couple of times can repro this issue.

It seems to happen when there's a space before `export default` ends and navigating to the canvas and back and then entering an incorrect code does not clear when this code is removed. But also when repeating this copy paste cycle. 

The function when triggered still works though so marking this low priority

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d21b4745697b4c00b93b974be114a4b2-00001.gif)](https://www.loom.com/share/d21b4745697b4c00b93b974be114a4b2)

### Steps To Reproduce

```markdown
1. Leave a space before the last } on JS editor
2. Navigate to the canvas and back
3. Enter code that would cause a parse error
4. Remove error causing code and observe the parse error still present
```

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment]
Another instance of this happening
https://www.loom.com/share/fb10728ecec0473bbb12e929f024e793

**Comment by ApekshaBhosale** [comment]
can you add me to the app? or if any way we can reproduce this? @ramsaptami

**Comment by ramsaptami** [comment]
You've been added to the [org](https://release.app.appsmith.com/applications/6197a8259ed8cc336f0efc71/pages/6197a8259ed8cc336f0efc75/edit). I'll ping you when I come across it again so we can get on a call to debug

**Comment by ramsaptami** [comment]
Works fine on release now hence closing the issue
