### ISSUE TITLE
[Bug]: User needs to click twice on delete icon to delete the last options value 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that for CheckboxGroup and Radio widget user needs to click on delete icon twice to delete the last option value which remains in the options field

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6e323c85b1164963adf4697bab361649-00001.gif)](https://www.loom.com/share/6e323c85b1164963adf4697bab361649)

### Steps To Reproduce

```markdown
1.Launch appmsith app in release/Prod Environment 
2.Drag and drop CheckboxGroup or Radio widget 
3.Open property pane and click on options fields
4.Try to delete options one by one by clicking on the delete icon and observe the delete functionality of the last options to delete
```

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Thanks for bringing this to our attention. Fairly simple issue, add validation to not remove the first two options. Since this is a group type widget, users should at-least have 2 options.
