### ISSUE TITLE
[Bug] currentItem showing error in List widget

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#8677]

**Comment by jauniuseitmantis** [comment]
any updates on this? :)

**Comment by ohansFavour** [comment]
Hi @jauniuseitmantis , this is currently being worked on and will be resolved shortly.

**Comment by ohansFavour** [comment]
Insight on this issue

1.  Currently, widgets present in the List widget have all their properties added to the `logBlacklist`. However, some fields, like the `Button.tooltip `doesn't get added to this list (see an example of the logBlacklist field for a button in a list widget below which doesn't include the tooltip property). 

![Screenshot 2022-02-05 at 19.26.13.png](https://images.zenhubusercontent.com/60f95494e7a0daadf23e22c3/8d88c68d-a386-48e1-953f-19720cdc7250)

The same goes with properties like maxChars and placeholderText of the Input widget (they don't get added to the logBlacklist).


2.  When an entity that was present in the List widget gets dragged out, into the canvas, its `logBlacklist` field doesn't get reset. Hence, errors are not shown in the fields present in the `logBlacklist`.  The List widget's `template` field doesn't get updated too (It still contains the button which had already been dragged out).

Image of List widget's template below. 

![Screenshot 2022-02-05 at 20.17.14.png](https://images.zenhubusercontent.com/60f95494e7a0daadf23e22c3/3dd86c2e-204a-4889-ac92-6b0609deccad)


The video below shows this edge case.

[Edge case](https://www.loom.com/share/5134b326777443bfa11439bf481b8a3c)


CC: @somangshu @riodeuno @jsartisan

**Comment by btsgh** [comment]
Tested in Release for both currentItem and currentIndex in a button added to list widget, after discussion with @ohansFavour and I don't see an error now.
