### ISSUE TITLE
[Bug]: When the name and value are not passed for two of the options no validation message is displayed for duplication

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it is observed that when the user does not pass name and value for two of the radio options then no validation message displayed for the duplication

Expecting a validation message similar to checkbox group widget 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e381e29ee8dd4f2b86880abec2146720-00001.gif)](https://www.loom.com/share/e381e29ee8dd4f2b86880abec2146720)

### Steps To Reproduce

```markdown
1.Launch Appsmith app in release/Prod Environment 
2.Drag and drop Radio widget 
3.Remove the default options name and value for both of the options and observe
4.Similarly try to the CheckboxGroup widget and compare
```

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Related to #8593

**Comment by dilippitchika** [comment]
Fix is to show the error in the debugger for radio widget when the name and value are empty.

**Comment by dilippitchika** [comment]
Not able to replicate @YogeshJayaseelan can you check once?

**Comment by YogeshJayaseelan** [comment]
@dilippitchika Now when the key and value field are empty 'The value at option is invalid' error occurs and looks fine now
