### ISSUE TITLE
[Bug]: 'There was an unexpected error' message is displayed when an unregistered user clicks on Reset Password

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#8683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://loom.com/share/a68f663bd01c409392fc585472a6c7a8

### Steps To Reproduce

```markdown
1. Go to Login page
2. Enter email id which is not registered > Click on 'Forgot Password'
3. Enter the same email id and click on Reset.
```

### Environment

Release

### Version

Cloud

**Comment by shwetha-ramesh** [comment]
Also observed when a user make multiple request for 'Reset password' and then clicks on an old reset password link.
![image](https://user-images.githubusercontent.com/92293815/144198088-18465a6f-7d87-4343-b6c5-1ef0a2293116.png)

**Comment by hiteshjoshi** [comment]
@shwetha-ramesh this looks solved. Closing this. Feel free to reopen if this still exists.
