### ISSUE TITLE
[Bug]: The queries get randomly reorders  in the entity pane when the user rename the new query

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The queries get randomly reorders  in the entity pane when the user rename the new query
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ae39e382c2e5474d8940a9977cb8420e-00001.gif)](https://www.loom.com/share/ae39e382c2e5474d8940a9977cb8420e)

### Steps To Reproduce

```markdown
1. Go to datasource 
2. Add a few queries for anyone datasource 
3. Now change the query name of the recently added query 
4. verify the display
```

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
The entity explorer update now orders the items alphabetically
