### ISSUE TITLE
[Bug]: renaming the widget replaces option "Label" and "Value" out of the  respective array 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user renames the widgets "Multiselect Tree" and "TreeSelect"  it is observed that the Valu and Label of the example move out of the Array item and there exists a jump in the widget

### Steps To Reproduce

```markdown
1) Add a Tree Select
2) Click on the Property Pane 
3) Rename the widget 
and observe the shift
```
![Screenshot 2021-10-21 at 3 51 00 PM](https://user-images.githubusercontent.com/71753653/138259235-bf04b621-1621-474d-962a-34afd1321d58.png)

### Environment

Release

### Version

Self-Hosted

**Comment by somangshu** [comment]
this is resolved with docked property pane
