### ISSUE TITLE
[Bug]: Changes made on the Table does not get reflected on table data in property pane

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user changes the column type and table data the data are not updated to the table data field in the property pane

<img width="1680" alt="Screenshot 2021-10-21 at 5 16 25 PM" src="https://user-images.githubusercontent.com/35128442/138273043-b65bd882-51cc-4097-8d55-536963894f11.png">

### Steps To Reproduce

```markdown
1.Launch Appmsith app in release or Prod Environment 
2.Drag and drop table widget 
3.Change any of column type to image and click on settings icon of that particular column and pass image url in the computed value 
4.Change any of the column to icon and open property pane and check the table data in property pane
```

### Environment

Release

### Version

Cloud

**Comment by Tooluloope** [comment]
@somangshu, I don't think this is an issue, we shouldn't be altering user data inputted in options.
The Data could be coming from an API or something.

Secondly, the user could want to revert back to the initial data.
