### ISSUE TITLE
[Bug]:  Linting errors stays on the "Error Tab" even on rectifying the error

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the linting error stays on the debugger and is displayed to the user even after rectifying the error. 

### Steps To Reproduce

```markdown
1) Navigate to JS editor 
2) write an undefined variable
3) Ensure linting error is displayed to the user 
observe the Error tab under Debugger the error is defined 
4) Now define the variables
and observe the Error tab under Debugger
```

### Environment

Release

### Version

Self-Hosted

**Comment by ApekshaBhosale** [comment]
Duplicate #8663
