### ISSUE TITLE
[Bug]:  Unable to access public apps with out loging in

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#8706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Share the app as public 
logout 
App is not accessible in incognito or after logginout

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8e11776feae44b71ba9a8b23f4520812-00001.gif)](https://www.loom.com/share/8e11776feae44b71ba9a8b23f4520812)

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@albinAppsmith I think this happened with the new design system change. How is there no test case for this???
