### ISSUE TITLE
[Feature] Integrate Google recaptcha on Appsmith.

### ISSUE THREAD

**Issue by anvaynk** [appsmithorg/appsmith#872]
## Summary

It'd be great if you could include Google recaptcha as a plugin on Appsmith and use the token that it generates as an input in the header of an API or in javascript.

## Motivation
The first screen that any kind of web app admin tool generally starts with is authentication. This is done by having a login page. And we use Google recaptcha to check if the person logging in is not a bot. Google recaptcha is a very common DDOS protection mechanism for login functionality. We want to use Appsmith for our internal admin tool but this recaptcha functionality is blocking us from going ahead. 

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by Nikhil-Nandagopal** [comment]
Hi @anvaynk 👋, thank you for the feature request. Are you looking to use re-captcha with appsmith's in-built authentication or do you have your own authentication mechanism?
If you have your own authentication, I'm thinking a good solution Will be to add a re-captcha widget which you can drag and drop inside your application. If it's with appsmith's authentication, we can discuss a solution where re-captcha shows up on the main login page. Let me know what you think!

**Comment by anvaynk** [comment]
We have our own api based authentication mechanism which we want to integrate with Appsmith's UI. I think it'd be great to have recaptcha as a widget so that it can also be added to other pages in the future too (ex: a signup page).

**Comment by Nikhil-Nandagopal** [comment]
@anvaynk after doing a little research, Recaptcha v3 seems like the best way to implement this
https://developers.google.com/recaptcha/docs/versions
In this way, we won't need an additional widget but instead add a re-captcha enabled property to a button. So if that property is enabled, the login call will only be made if the Recaptcha succeeds. 
This library here seems like a good starting point
https://github.com/t49tran/react-google-recaptcha-v3
Does this work? This should be fairly straight forward for us to implement

**Comment by anvaynk** [comment]
Awesome! Yes this should work.

**Comment by Nikhil-Nandagopal** [comment]
@anvaynk we're in the process of shipping this out. We had one clarification. There's a token verification that needs to occur which is what protects an endpoint from bots. We're thinking we'll pass this token back to your login API and your login API is going to verify the token. Is this understanding correct? 
This will also mean that the sitekey which you generate should have app.appsmith.com in the list of domains.

**Comment by Nikhil-Nandagopal** [comment]
@anvaynk just wanted to update you that we have shipped this feature and it is now available in the latest version of appsmith 🎉
