### ISSUE TITLE
[Bug]:  Doc's : On entering an search keyword and clicking on "Enter" key the user is lead Appsmith Introduction page 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user navigates to global search, enters any widget name as a keyword, and clicks on the "Enter" key the user navigated to the Appsmith introduction page rather than to the respective page details the 

### Steps To Reproduce

1) Navigate to Application
2) Click on Global search
3) Add  widget name as keyword 
4) click on "Enter" from the keyboard 
and observe

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
This issue has now been resolved
