### ISSUE TITLE
[Bug]: Kebab menu of the application overlaps on the application when the browser is minimised 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the website is minimized the and user navigates to the home page and tries to open the menu of the application it is observed that the menu overlaps on the application and changes can not be viewed by the user. 

Expectation:
We can open it to the right of the application making the changes visible to the user

### Steps To Reproduce

1) Navigate to home page
2) open the menu of any application 
3) Minimize the browser 
and observe

![Screenshot 2021-10-22 at 10 58 29 AM](https://user-images.githubusercontent.com/71753653/138432981-961f6d58-e55b-499b-bd0e-9a4ba660d3be.png)

### Environment

Release

### Version

Cloud

**Comment by hiteshjoshi** [comment]
This is fixed.
