### ISSUE TITLE
[Enhancement]:  user is unable to edit the email id once entered into email Id field of manage user  

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user navigates to manage user field and tries to share the application with one the user and unknowingly adds a wrong email id. The user must be provided with an option to edit the field details this would help the user avoid retyping the email details.

![Screenshot 2021-10-22 at 5 06 52 PM](https://user-images.githubusercontent.com/71753653/138447545-30b93fa1-5a6c-4544-9376-5a9c918ba83e.png)

 

### Steps To Reproduce

1) Navigate to manage icon 
2) Click on the Share button
3) try to add an email id 
4) and click outside
and observe 

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is not valid. That user with incorrect email has been invited so editing is not an option. The only option is to remove the invited user and re-invite a new user
