### ISSUE TITLE
[Bug]:  Inconsistency in the alignment of the screen when browser is minimized 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the browser of the application is minimized it is observed that the General tab , manage user tab and profile all look different and open in a different manner. opening of pages on smaller screen size needs a consistency through out the application

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f7e7346c949341cf88c5244256d7916f-00001.gif)](https://www.loom.com/share/f7e7346c949341cf88c5244256d7916f)

### Steps To Reproduce

1) Navigate to profile and observe it opens on the complete left of the screen 
2) Navigate to members and observe it opens in the center of the screen 
3) Navigate to the General tab and observe it opens  slightly away from the center

### Environment

Release

### Version

Cloud

**Comment by riteshkew** [comment]
Closing this. No longer reproducible in v1.20
