### ISSUE TITLE
[Bug]: Input Widget's Label Font style JS Edit option doesn't make sense

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#8750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

What's the use of JS Edit option on Input Widget's Label Font style?
Even if it is useful, what value does the user is supposed to enter there?
At least, the proper expected value should be shown.

https://user-images.githubusercontent.com/10436935/138581806-6fe042fd-c9fd-49ef-80c3-8d4126c3f811.mov

### Steps To Reproduce

1. Add an input widget
2. Open property pane and scroll down to see the Label Font Style
3. click on JS Edit. Think about what you should be entering there!

### Environment

Production

### Version

Cloud

**Comment by keyurparalkar** [comment]
@aswathkk yes, there is no information provided on what should be the expected value when JS editor is enabled. 

Proposed solution would can be to display a tooltip with what expected values should be.

**Comment by keyurparalkar** [comment]
Related to #9468

**Comment by sbalaji1192** [comment]
@aswathkk Looks like we don't have the js options on the emphasis property. Could you confirm and close this issue?

**Comment by aswathkk** [comment]
Closing this since we don't have JS option on Emphasis property
