### ISSUE TITLE
Typo found in README.md[Docs] 

### ISSUE THREAD

**Issue by Rony9999** [appsmithorg/appsmith#876]
## Documentation Link 

Add a link to the page which needs improvement (if relevant)

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

A clear and concise description of the improvement.

**Comment by mohanarpit** [comment]
@Rony9999 What typos did you notice in the documentation? Can you please elaborate them in the issue description?

**Comment by mohanarpit** [comment]
@Rony9999 I'm closing this issue as spam for now. Please find better issues on Appsmith's project or contribute to an existing issue.
