### ISSUE TITLE
[Bug]: In JS editor page Run icon doesn't work in debugger section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In JS editor page when the user click on the run icon in the debugger there is no action performed
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9912655c3d5143d7ab0e783401585fb4-00001.gif)](https://www.loom.com/share/9912655c3d5143d7ab0e783401585fb4)

### Steps To Reproduce

1. Go to the application
2. Click on + icon next to js Object
3. In the debbuger section of the js object page 
4.  Click on the Run icon 
5.  The functionality of run icon does work

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
@ramsaptami the uploaded video is truncated, so I cannot see the issue. Would you please upload it again or elaborate further? 
Are you creating a new JS object and trying to run a function inside it upon first creation? If yes, what is the expected behaviour?

**Comment by ramsaptami** [comment]
@rohan-arthur Think the point @RakshaKShetty is trying to make is that the run button that appears in the debugger watch window needs to support run action. This panel is undergoing design change so we'll have to wait and see if the button stays and then pick this up
