### ISSUE TITLE
[Bug]: The Widgets in canvas gets deleted, when user clicks ctrl+z to Undo the changes in Query editor 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user edit query and click on Ctrl + z The latest added widget will be removed/Undo
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6415eac69f574079873403aa815f6e4d-00001.gif)](https://www.loom.com/share/6415eac69f574079873403aa815f6e4d)

### Steps To Reproduce

1. Go to canvas
2. Add a table widget
3. Now go to a datasource
4. Add a new query in Mongo 
5. Add a wrong query now click on control + z from the keyboard
6. Now the table widget will be removed from the canvas

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This should now be solved. @RakshaKShetty
