### ISSUE TITLE
[Bug]: The scroll doesn't work for the date format dropdown inside the date picker widget

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The scroll doesnt work inside the date format inside the date picker. widget
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d766d296a9cf42ba850a1b70ee9b947e-00001.gif)](https://www.loom.com/share/d766d296a9cf42ba850a1b70ee9b947e)

### Steps To Reproduce

1. Go to canvas
2.  drag and drop the date widget
3.  Inside the property pane 
4.  click on the date format dropdown 
5.  try to scroll to check the date format at the bottom of the dropdown 

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Not reproducible after moving the prop pane to right.
