### ISSUE TITLE
[Bug]-[1000]:The query param syntax is wrong for Navigate to property

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user select navigate to action in action property the default query param brackets is not correct

![image](https://user-images.githubusercontent.com/45958978/138692943-3f4162f3-883d-4af5-8e07-1ccd6c76739b.png)

### Steps To Reproduce

1. Go to canvas
2. Drag and drop the table widget
3.  Now got to action property
4. select the navigate to action
5.  Check the brackets displayed in query param 

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 250 |
| Effort (months)  | 0.5|

**Comment by rimildeyjsr** [comment]
This behavior is correct, as without the mustache brackets surrounding the {} it will be treated as a string. Closing this issue!
