### ISSUE TITLE
[Bug]: There is a weird noise that is heard once the widget is placed on the canvas

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user places the widget into the canvas a weird noise is continuously heard to user which make it difficult for user to user the application 

### Steps To Reproduce

1) add the camera widget 
and observe

### Environment

Deploy Preview

### Version

Cloud

**Comment by wmdev0808** [comment]
@prapullac I cannot reproduce the issue
Could you please record the demonstrating video for me?

**Comment by shwetha-ramesh** [comment]
@wmdev0808 Issue still exists.

https://loom.com/share/7997622dd9cf4bcbbd3aff8250a5854d
