### ISSUE TITLE
[Bug]:   on resetting permission the user will not be able to access the camera again

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user drag and drop a camera widget and then denies the permission and resetting or provides the permission the user is unable to recover the widget 
he needs to delete the widget and place it all new 

### Steps To Reproduce

1) place a camera widget
2) ensure at first permission are provided 
3) now block the permission 
4) ensure camera widget turns black
5) Now provide the permission 
and observe

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6619a09d3c5948309bb108d18d905397-00001.gif)](https://www.loom.com/share/6619a09d3c5948309bb108d18d905397)

### Environment

Deploy Preview

### Version

Cloud

**Comment by shwetha-ramesh** [comment]
@prapullac observed with reload the camera re-appears.

**Comment by wmdev0808** [comment]
> @prapullac observed with reload the camera re-appears.

@shwetha-ramesh , What does this mean?

**Comment by shwetha-ramesh** [comment]
> > @prapullac observed with reload the camera re-appears.
> 
> @shwetha-ramesh , What does this mean?

When permission is denied and enabled again, if the browser is refreshed the changes are applied.

**Comment by shwetha-ramesh** [comment]
@wmdev0808 When permission is denied and enabled again, if the browser is refreshed the changes are applied
