### ISSUE TITLE
[Bug]: "Denied permission" must be displayed to user in white  as it is displayed on dark background 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Denied permission"  is displayed to the user in grey which is not displayed prominently to the user.
using colors that are displayed in highlighted manner with white or something 

### Steps To Reproduce

1) drag and drop a camera widget 
2) Deny on the permission 
and observe 

Intermittent : Deny permission is not displayed to the user in some scenario

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by shwetha-ramesh** [comment]
Fixed
![image](https://user-images.githubusercontent.com/92293815/145187963-2d5f732d-b490-4a92-bc15-e97709b40b23.png)
