### ISSUE TITLE
[Bug]: Over lapping on camera icon and capture icon on resizing 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user moves from Desktop mode to mobile mode it is observed that there is Overlapping on the camera icon and capture icon on resizing 
![Screenshot 2021-10-25 at 7 05 45 PM](https://user-images.githubusercontent.com/71753653/138706350-13d732d0-b949-42a8-8e74-aab2d7a09064.png)

### Steps To Reproduce

1) Drag and drop the camera widget 
2) Move from desktop mode to mobile mode 
and observe 

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
Won't fix because it's not built for mobile yet
