### ISSUE TITLE
[Bug]:  Video widget supports only URL and not camera binding 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the camera widget video binding is fetched under the entity explorer it is displayed as "camera1.video" when. tried to bind the same into Video it is not accepted. As video needs URL as binding 

Expectation:
To make it easy to user we can display the exact binding needed for the video widget 

### Steps To Reproduce

1) add a camera widget
2) navigate to entity explorer
3) observe the binding for video 
4) Copy the binding for the video
5) Add a video widget
6) paste the binding to the video 
and observe

### Environment

Deploy Preview

### Version

Cloud

**Comment by shwetha-ramesh** [comment]
Fixed.
