### ISSUE TITLE
[Bug]: Input.isValid shows unexpected behaviour 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#8804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Demo Video 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0a5490d16eb24ce8b7a43bd6594e41ad-00001.gif)](https://www.loom.com/share/0a5490d16eb24ce8b7a43bd6594e41ad)

### Steps To Reproduce

1. Add Input Widget with `Valid` as `{{Input1.text.length > 0}}`
2. Add Text Widget with `Text` as `{{Input1.isValid}}`
3. Type something in input widget and then erase it.
4. See the error

### Environment

Production

### Version

Cloud

**Comment by sbalaji1192** [comment]
RCA - When input element is not required and there is no text, we're simply setting isValid to true. 
Solution - We should validate text with regex and valid property even if isRequired is false.

**Comment by SatishGandham** [comment]
This is expected behaviour.
If an input is empty and it's not required, it is valid.

@sbalaji1192 , we do check the regex and valid property for not required fields if they are not empty.

**Comment by Rishabh-Rathod** [comment]
@SatishGandham Can you help me understand, why do we not check the regex and valid property if they are empty?

**Comment by sbalaji1192** [comment]
Fixed as part of #9119
