### ISSUE TITLE
[Bug]: Text is not centered when checkbox widget has 2 lines of text

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When text of a checkbox overflows on to 2 lines then it's not centered to the checkbox making it look odd

![image](https://user-images.githubusercontent.com/79509062/138835537-ff0cea62-4737-4497-acd8-0ed70c47d622.png)

### Steps To Reproduce

1. Drag and drop a checkbox widget and type in a text such that it overflows to 2 lines and observe

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@Debsourabh suggested this to be a better UI. Please reopen if required
