### ISSUE TITLE
[Bug]-[50]:Scroll is added each time tooltip appears in view mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Both horizontal and vertical scrolls appear when tooltip appears at the bottom of a page. Can be replicated by launching the Standup app.

### Steps To Reproduce

1. Launch Standup app and hover over the **ratings widget** when it's present at the bottom of the page and observe vertical and horizontal scrolls appear when tooltip is displayed

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
The screen-recording reflects this, watch the scroll bar on the right. There is a new one added if the tooltip appears outside the window bounds.

If the tooltip would appear where there is space (the way selects are handled, above the widget when it would not fit below, this would likely solve this issue

https://images.zenhubusercontent.com/275993885/0f00b2f3-9fd6-4f30-8996-5e147acd277d/screen_recording_2022_04_20_at_9_38_17_am.mov

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 50 |
| Effort (months)  | 0.5|

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
