### ISSUE TITLE
[Bug] JS icons missing in property pane

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS icons missing in the property pane
![image](https://user-images.githubusercontent.com/45958978/138867008-d45e7433-5e03-4db7-ae11-1fb04462160e.png)

![image](https://user-images.githubusercontent.com/45958978/138866584-85b099ea-461f-4b8b-9079-c1831cf540c0.png)

### Steps To Reproduce

1. go to canvas
2. drag and drop a widget
3. click on ?= icon next to JS objects
4. add a JS object
5. Now click on the property pane of the widget
6. on the action section select execute a Js function
7. The icon i snot displayed for JS Object

### Environment

Release

### Version

Cloud

**Comment by nishihere19** [comment]
Can I work on this issue?

**Comment by albinAppsmith** [comment]
Sure @nishihere19, Please go ahead.

Please read the [Code Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md) to understand the process to get started with solving a Github issue.

**Comment by arunvjn** [comment]
@RakshaKShetty JS Icons are added in the latest in the actions selection along with the new explorer changes. Can you please retest ?

**Comment by ramsaptami** [comment]
Closing this issue since the icon has been added in the IDE enhancement
