### ISSUE TITLE
[Bug]: The username is not displayed on hover when no of shared users increases for application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#8825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the home page when the user hover on the shared user icon the name is displayed but when there are more users +2 icon is displayed at that time if the user hovers on the Icon the names are not displayed 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4f14f2e3ac2743248b08c5664499607e-00001.gif)](https://www.loom.com/share/4f14f2e3ac2743248b08c5664499607e)

### Steps To Reproduce

1. go to canvas
2. in the home page select the org that has more than no users 
3. now hover on the no icon
4. the names are not displayed 
5. But clicking on it displays the name of users

### Environment

Release

### Version

Cloud

**Comment by hiteshjoshi** [comment]
I think this is fixed. Can’t find this bug anymore. @pranavkanade you can reopen in case this is fixed.
