### ISSUE TITLE
[Feature]: [Enhancement] Option to send test mail from admin settings page.

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#8840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

 There should be a button to test whether email works or not on the admin settings page.
https://www.figma.com/file/lqtUfzJO50RpEhxKttYeOg/Local-Dev-Main?node-id=4232%3A34241

### Why should this be worked on?

 There should be a button to test whether email works or not on the admin settings page.

**Comment by RakshaKShetty** [comment]
The front end is still pending so this cant be tested now, so reopening
