### ISSUE TITLE
[Bug]: UI issue on the debugger for JS editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Debugger overlaps with error and all of the content is not visible on first load of the editor

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3ae8a2c04b99460597550250ed4c3747-00001.gif)](https://www.loom.com/share/3ae8a2c04b99460597550250ed4c3747)

### Steps To Reproduce

1. Launch JS editor and observe the debugger placeholder not being completely visible
2. Cause an error on the code and reduce the size of the debugger and observe the debugger placeholder overlap with the error

### Environment

Deploy Preview

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
@ramsaptami is this happening on API page as well? can you confirm this?

**Comment by ramsaptami** [comment]
@ApekshaBhosale Yep, still happens
