### ISSUE TITLE
[Bug] Deploy install script doesn't work with IPv4 machines anymore

### ISSUE THREAD

**Issue by jack1142** [appsmithorg/appsmith#886]
## Description

Since yesterday (Oct 1, 2020) the A record for api6.ipify.org was removed to make the subdomain only for IPv6 requests. Source: https://www.ipify.org/
From my testing, it looks like `api6.ipify.org` before October 1, 2020, was returning what `api64.ipify.org` returns now. I'll be making a PR to fix this in a few moments.

### Steps to reproduce the behavior:
1. Use the install script on a machine that only has IPv4.
2. See output with no much information that exits early:
```
vm@vm:~$ bash ./install.sh
👋  Thank you for trying out Appsmith! 

🕵  Detecting your OS
vm@vm:~$
```

### Important Details
 - Version: [Cloud / Self-Hosted vx.x] Self-Hosted; no version since this is just install script but revision at the time of issue was: 8b8dcc050a2cfd85d2c5850bd452c45c1bbdda6f
 - OS: [e.g.MacOSX] Ubuntu 20.04
 - Browser [e.g. chrome, safari] N/A

**Comment by Nikhil-Nandagopal** [comment]
@jack1142 thanks for reporting this. I've migrated to the ipv4 version
