### ISSUE TITLE
[Bug]: Default search is not working when server side pagination is enabled table widget

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user generates page from table data and when the server side pagination is enabled - Search is not working as expected 

### Steps To Reproduce

1.Launch Appmsith app in release environment 
2.Open any page and click on generate page from table 
3.Choose option as public.users
4.Choose sub option as Email 
5.Click on generate page 
6.Wait until the page loads 
7.On the table widget click on search field and try to search any valid data and observe

https://loom.com/share/7b14e76e761f40ac9227bf93c89fdda8

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
The problem is not in the search functionality, since the onSearchChanged is bound to a query, the query needs to return the right result, Please check your query
