### ISSUE TITLE
[Bug]: The Page resets to 1 when server side pagination is enabled and search is performed 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user generates page from table data and when the server side pagination is enabled and navigating to page 2 or 3 and on searching the page resets to 1

### Steps To Reproduce

1.Launch Appmsith app in release environment
2.Open any page and click on generate page from table
3.Choose option as public.users
4.Choose sub option as Email
5.Click on generate page
6.Wait until the page loads
7.Navigate to page 2 04 3 
8.Click on search and observe the page resets to page 1

https://loom.com/share/315a665282934e20ac892f2bdf31c2b6

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
This is intended, We are re-setting the page because the query result is different / reloaded
