### ISSUE TITLE
[Bug]-[184000]:Welcome page causes an odd scroll bar toggle while using dropdowns

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Welcome page displays a scroll that causes UI elements to shift (see video below)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/cd1c6c7d55124f0c87048feeace6fb13-00001.gif)](https://www.loom.com/share/cd1c6c7d55124f0c87048feeace6fb13)

### Steps To Reproduce

1. Sign up
2. On the welcome page observe a scroll appear when using the dropdown and moving control away triggers does not stop it 

### Environment

Release

### Version

Cloud

**Comment by shwetha-ramesh** [comment]
https://www.loom.com/share/d17fb0757bd7472288f3219c275157f0

The 'Role' field when entered with any input the screen shakes.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 23000 |
| Effort (months)  | 0.25 |

**Comment by berzerkeer** [comment]
@ramsaptami Hi, I couldn't reproduce this issue. Tried it on different platforms and displays, macbook pro , ultrawide display, windows and mac. 
https://www.loom.com/share/207b271f31474c9f82bb8cbcd6a00585

**Comment by ramsaptami** [comment]
@berzerkeer The scroll issues seem to be fixed. Can we take a look at [this](https://github.com/appsmithorg/appsmith/issues/8876#issuecomment-953560689) comment? The issue is still present
