### ISSUE TITLE
[Bug]: Clicking on JS and when value is false disables the button and menu button in the table widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that When the user disables and enables the menu or button column for the first time and clicking on JS the menu and button column are disabled (But still the JS value is false)

https://loom.com/share/eb4f85264e0049d2bc0c1c7cb0f0edfc

### Steps To Reproduce

1.Launch Appmsith app in release
2.Drag and drop table widget 
3. Change column type to menu or button 
4. Enable the Disable toggle 
5. Again enable the Disable toggle 
6. Click on JS and observe the menu and button column 

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
This issue is not related to the table widget, But the JS convertible option available globally, We have seen these inconsistency and its been tracked elsewhere

**Comment by aswathkk** [comment]
This is not a bug I think. The value `false` is a string.
`false` is a truthy value whereas the value `{{false}}` is falsey.
