### ISSUE TITLE
[Bug]: Import app popup experience improvement

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- [ ] Text can be moved up a bit higher
![image](https://user-images.githubusercontent.com/79509062/139224600-797cdddc-724f-460a-82ee-c93bd97e5f69.png)

- [ ] Tooltip appears at the top right corner when app import is cancelled
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4be7cbd5400741818fc32588048e3db2-00001.gif)](https://www.loom.com/share/4be7cbd5400741818fc32588048e3db2)

### Steps To Reproduce

1. Click on org settings on home page and choose import app to repro the above 2 scenarios

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
This has been changed to a new experience [here](https://github.com/appsmithorg/appsmith/pull/10453), this is the updated screen

@ramsaptami please have a look
 
![Screenshot 2022-04-06 at 3.02.01 PM.png](https://images.zenhubusercontent.com/6194ed835e414ef30494a467/edc6e666-ab53-43e6-ba14-deb2e39a752b)

**Comment by kocharrahul7** [comment]
Closing
