### ISSUE TITLE
[Bug]: Multiple options are in selected state at the same time on the entity explorer

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Multiple options are in selected state in the entity explorer causing much confusion on what's selected and where to navigate next 

![Uploading image.png…]()

### Steps To Reproduce

1. Select an app that has mulitple apps and data sources and observe the entity explorer while navigating between them

### Environment

Release

### Version

Cloud

**Comment by arunvjn** [comment]
@ramsaptami Can you please retest this in the new explorer ? Looks like it is not reproducible there.

**Comment by ramsaptami** [comment]
Closing the issue since it's not reproducible on the new design
