### ISSUE TITLE
[Bug]: Slash command is not functional on JS editor 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user uses a slash command inside JS editor the slash command suggestion is not displayed to user 

![Screenshot 2021-10-28 at 3 23 23 PM](https://user-images.githubusercontent.com/71753653/139233009-0a8359ff-c7ba-4e3e-b27a-3ab412d82714.png)

### Steps To Reproduce

1) Navigate to Js editor
2) Add slash command 
and observe

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Not valid slash commands are not expected in the JS Editor
