### ISSUE TITLE
[Bug]: Page break when a widget is renamed to the word "type" and then renamed to some other word, app crashes.

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#8888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

current: currently the page is broken and in a non restorable state.
expected: dsl property keys should be allowed to be set as widget names.

### Steps To Reproduce

When widget dsl property keys like type, widgetName, topRow, etc are provided as a widget name and then renamed to some other name, the page breaks.

### Environment

Production

### Version

Cloud

**Comment by nidhi-nair** [comment]
This issue needs us to possibly introduce AST on the server side, and have a better sense of the schema that DSLs have to introduce selective rules for refactor. Lowering priority till we can discuss a solution for this issue since this happens for extremely generic names.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair can we do a simple solution like have a blacklist of names that a user cannot rename to?

**Comment by nidhi-nair** [comment]
This has been fixed by #8713
