### ISSUE TITLE
[Bug]: Recaptcha V2 Issue

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#8890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A user complained that the Recaptcha V2 does not work

### Steps To Reproduce

1. Drag a button
2. Configure a Recaptcha Key
3. Configure the key in the button
4. Click the button and there is an error about the recaptcha key

### Environment

Production

### Version

Cloud

**Comment by vicky-primathon** [comment]
Able to access googleRecaptchaKey property of Button once i click on button after adding recaptcha v2 key. 
Found these issues instead:
1. googleRecaptchaKey property is not available in autocomplete for binding
2. Google reCAPTCHA Version dropdown property in button widget is not working properly.
cc @somangshu

**Comment by Nikhil-Nandagopal** [comment]
@vicky-primathon did you try it for v2?

**Comment by vicky-primathon** [comment]
> @vicky-primathon did you try it for v2?

Yes, created a new recaptcha v2 and tested for that.
