### ISSUE TITLE
[Bug]: Fork Apps Broken

### ISSUE THREAD

**Issue by vj-codes** [appsmithorg/appsmith#8894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to follow the instructions mentioned using the application template file, the linked templates take me to the deployed site instead of Github repo link.
As per the instructions, I should see a "fork" button on the top right, but since it's not a GitHub page after clicking, the instructions are invalid.
Update the template links to their respective repos.

### Steps To Reproduce

1. Click on the application of your choice from appsmith_templates.md file
2. See error , no fork button as no GitHub page hyperlinked

### Environment

Release

### Version

Cloud

**Comment by nayan-rafiq** [comment]
I've set `isPublic=true` to the https://app.appsmith.com/applications/5f43bce13697fd5df1c52ce4/pages/5f43c39c3697fd5df1c52d50 and now fork button is displayed for this application.
