### ISSUE TITLE
Create doc on how to configure deploy keys

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#8898]
We will need a doc on how to configure deploy keys (SSH keys) for git-sync feature. Some of the references from popular platforms which hosts the git repos :
https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys
https://docs.gitlab.com/ee/user/project/deploy_keys/#project-deploy-keys
Note : We will need read-write access for the deploy keys in git-sync feature

For most of the cases, companies use Github, Bitbucket, Gitlab to host their repositories so this doc should cover at least these platforms.

**Comment by AnaghHegde** [comment]
Closing this as it is completed.
