### ISSUE TITLE
[Bug]-[150]:Cannot select tables from SQL Server using Quick Page Wizard

### ISSUE THREAD

**Issue by jrvidotti** [appsmithorg/appsmith#8906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to Create a Page using Wizard, I get the error "Couldn't find any table, Please select another datasource".

### Steps To Reproduce

Create a New Page and choose Generate.

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 300 |
| Effort (months)  | 1|

**Comment by kocharrahul7** [comment]
MS Sql server seems to no longer be whitelisted
