### ISSUE TITLE
[Feature]: please add a Scroll Indicator Progress Bar

### ISSUE THREAD

**Issue by VanshajPoonia** [appsmithorg/appsmith#8925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It is basically a bar that indicates that how much the user has scrolled down.

### Why should this be worked on?

Please add such a bar as it looks very cool and tells the user how much he/she has scrolled.

**Comment by areyabhishek** [comment]
@VanshajPoonia thanks for opening the issue. Could you explain where you'd like to see the scrollbar? Is this inside the app, the app editor, container, or table.

**Comment by VanshajPoonia** [comment]
@areyabhishek  I mean to say that on some websites, there is a bar on the top that fills when you scroll the website.
![image](https://user-images.githubusercontent.com/74147463/139529555-7a51bdb8-32f1-4d97-8813-2789fd4dbda7.png)
See this, as the user will scroll down the website, this bar will fill more and more

**Comment by dilippitchika** [comment]
Looks like the progress bar widget now available, closing this
