### ISSUE TITLE
[Feature]: A way to track user behaviour in apps built in Appsmith

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#8926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Use case:

> Is there a way to monitor user behavior in an app ? For example, integrating into something like  https://openreplay.com/
> One current use case for appsmith is as a user prototyping system, so this would be quite cool.

### Why should this be worked on?

A feature like this can enable app developers get insight into where their apps create friction for their users and help them improve in the right direction.

**Comment by Nikhil-Nandagopal** [comment]
This is related to the larger issue of integrating custom js libs so closing this in favor of #2430
