### ISSUE TITLE
[Bug]: Cursor moves to the start of the JS file when window is tabbed from another editor application

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While using JS editor, if an app like Word, notepad, sticky notes etc are switched to and back then the cursor moves to the start of the file.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e3476ecdfb61404a9c4b1bf98a1754cf-00001.gif)](https://www.loom.com/share/e3476ecdfb61404a9c4b1bf98a1754cf)

### Steps To Reproduce

1. Start typing in on JS editor
2. Change to another editor kind of app like Word, Notepad etc...
3. Switch back to Appsmith and observe the cursor shift to the start of the file.

### Environment

Deploy Preview

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
@ramsaptami is this just for js editor or across appsmith?

**Comment by ramsaptami** [comment]
Seems to be only on the editor @ApekshaBhosale

**Comment by rohan-arthur** [comment]
old issue, not reproducible anymore

https://github.com/appsmithorg/appsmith/assets/94514895/9b581db0-040f-49ca-b099-4932ffddadb3
