### ISSUE TITLE
[Bug]: Lint error is displayed outside of page boundary hence truncated

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lint error at the end of the JS editor box is not visible and get truncated as seen in the screenshot

![image](https://user-images.githubusercontent.com/79509062/139650460-eff31023-2ef6-4ce0-815c-26d62c9abc1c.png)

### Steps To Reproduce

1. Type a long line of code on JS editor with errors and observe lint error displayed as seen above

### Environment

Deploy Preview

### Version

Cloud

**Comment by ohansFavour** [comment]
This can be solved by either increasing the padding to the right of the jsObject codeEditor or conditionally using the `selfContain: true` option to render the tooltip inside the editor instance.

**Comment by ramsaptami** [comment]
reopening this since it's still not working on JS editor

**Comment by ramsaptami** [comment]
Works as expected on JS editor
