### ISSUE TITLE
[Epic] Queries Undo/Redo

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#8958]
## Objective

Provide a feature to undo/redo (U/R) actions in the actions/query editor and Datasource editor with up to 200 updates.
In the process of building fast, many unforced errors occur which need to be undone. Enabling faster iteration leads to more usage and a better building experience.

## Solution

We want to treat queries, data sources, and pages as a file and perform undo/redo on the files the way editors do. This means that the history of changes is specific to the file and not across files. The limit of changes will be explored and decided later. Creating/deleting a new file will not come under the scope of the undo/redo operation and as such creating/deleting pages/queries & data sources will not be undoable/redoable.
When a user is in the focus of a field, the undo/redo history will default to the browser behavior and be limited to the field, when it is out of focus of the field, the overall file history will be undoable/redoable.
Undo across git branches will not be allowed. i.e If a user has committed changes and switches to a new git branch, hitting cmd + z will not take the file to the state in the previous git branch.

## RACI
| ------------- | ------------- |
| Responsible   | @arunvjn, @albinAppsmith |
| Accountable   | @hiteshjoshi |
| Consulted     | @Nikhil-Nandagopal, @RoopKrrish9696 |
| Informed      |  @areyabhishek, @mohanarpit   |

**Comment by Nikhil-Nandagopal** [comment]
Today: 
Updated Product Note after a discussion
Next Action Items:
@arunvjn & @albinAppsmith to come back with task breakup and estimates

**Comment by marks0351** [comment]
adding some notes after discussing with a user, he wishes we had a recycle bin for entities(widgets, datasources, apis, queries, etc) that are deleted so that the user can recover them or check what has been deleted and recover only that is needed.

**Comment by Nikhil-Nandagopal** [comment]
@marks0351 can we create a separate issue for that? This epic will deal with undo / redo within a file. While that seems like to undo / redo the operations on top of a file
