### ISSUE TITLE
[Bug]: Next icon of Pagination on table widget get cropped on applying filter

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For default table size the next icon is cropped after applying filter

<img width="668" alt="Screenshot 2021-11-11 at 3 55 31 PM" src="https://user-images.githubusercontent.com/83569920/141282154-8e6761cb-885f-4889-9eb2-687745a10d3e.png">

### Steps To Reproduce

1. Drag and drop a table widget
2. Apply a filter
3. Observe that the next icon for pagination is clipped

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@vivekverma2312 please add a screenshot

**Comment by keyurparalkar** [comment]
@vivekverma2312 closing this issue since this got resolved in the issue: #9312
