### ISSUE TITLE
[Bug]: switching to JS for visible property in column type of table widget always toggle to true

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we switch to JS for visible property of column type and change to false then it do not work

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6e7d3a006f2a4a02825a5a84c6df506e-00001.gif)](https://www.loom.com/share/6e7d3a006f2a4a02825a5a84c6df506e)

### Steps To Reproduce

1. Drag and drop a table widget
2. Open property pane
3. Click on any column
4. For visible property pane change to JS
5. type "false"
6. Observe that the column is still visible

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
The problem here is with the JS switch and the evaluation. This issue is already know and tracked separately as mentioned before
