### ISSUE TITLE
[Bug]: Page properties non-CTA icons have too many cursor icon types

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cursor icons (point, grab and arrow) needs to be defined even for the boundary of icons that don't support a CTA (Visible, home and disabled home page delete icon). See attached video to see how 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/edbae970b4f048c58fbf6785a0b3d2d4-00001.gif)](https://www.loom.com/share/edbae970b4f048c58fbf6785a0b3d2d4)

### Steps To Reproduce

1. Go to Page Properties and hover around the icons present for each page and observe 

### Environment

Release

### Version

Cloud

**Comment by rohitagarwal88** [comment]
Closing as page setting moved to property pane
