### ISSUE TITLE
[Bug]-[100]:Inconsistent action on dropdowns appearing onHover vs onClick of options

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App properties dropdown has sub-menu that appears on hover, whereas query properties `...` (on query page) or widget properties on entity explorer have options with sub-menu where the sub-menu opens up only onClick. This action needs to be made consistent for users

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7f6ec7470a424ec99c9fc4b19dbdd698-00001.gif)](https://www.loom.com/share/7f6ec7470a424ec99c9fc4b19dbdd698)

### Steps To Reproduce

1. Any dropdown present on the app should follow consistency in action for sub-menu's appearing on screen (onHover vs onClick) (app properties, widget properties, query properties)

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 100 |
| Effort (months)  | 0.5|

**Comment by rohitagarwal88** [comment]
ADS 2.0 fixes it.
