### ISSUE TITLE
[Bug]: Unable to play the downloaded audio file 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that user is not able to play the downloaded audio file from the audio widget 

https://loom.com/share/9b90bf9cd2804762a953d2f9975c8f49

### Steps To Reproduce

1.Launch Appmsith app in release/Prod environment 
2.Drag and drop audio widget 
3.OnEnd action set to download 
4.Pass the following option in download setting (Data to download - data, File name with extension - sound.mp3)
5.Wait till the audio ends
6.Open the downloaded file and try to play 

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@YogeshJayaseelan what does `data` denote in the  `Data to download` property. This should work with the right encoding, Kindly re-open the issue if that still doesnt work
