### ISSUE TITLE
[Bug]: Property pane pop up overlaps with debugger pane and shows improper UI 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user places the treeselect widget at the bottom of the canvas and opens property pane and opens the label text size field and when the user scrolls the property pane goes beyond the debugger and shows improper UI

<img width="1680" alt="Screenshot 2021-11-02 at 2 41 24 PM" src="https://user-images.githubusercontent.com/35128442/139821297-82057e75-161b-4bd3-a54c-341618815a84.png">

### Steps To Reproduce

1.Launch Appmsith app in release/Prod environment 
2.Drag and drop treeselect widget at the bottom of the canvas
3.Open property pane and try to change the label size in the property pane
4.Try to scroll and observe

### Environment

Release

### Version

Cloud

**Comment by Tooluloope** [comment]
Fixed

**Comment by Tooluloope** [comment]
Fixed
