### ISSUE TITLE
[Bug]: Dynamically setting default value for a dropdown does not trigger onOptionChange

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#8977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/5298848/139813142-45f980dd-f887-463b-baa9-50454fc5470f.mov

### Steps To Reproduce

1. Create a dynamic binding for default value in dropdown
2. Set an onOptionChange trigger on the dropdown
3. Make a change in the dynamically bound value
4. Notice that the onOptionChange action is not taken

### Environment

Production

### Version

Cloud

**Comment by Tooluloope** [comment]
issue is being tracked here https://github.com/appsmithorg/appsmith/issues/2639
