### ISSUE TITLE
[Bug]-[100]:Clicking outside the box or using Esc key does not close the confirmation modal on API query

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On API query page when confirmation modal pops up, it cannot currently be closed by either clicking outside the box or using the **Esc key**

![image](https://user-images.githubusercontent.com/79509062/139825923-25831daf-a87a-4e55-b0f5-bc70bbac33d5.png)

### Steps To Reproduce

1. Select "Request confirmation before running API" on API query and click Run
2. Try dismissing the pop-up using Esc key or clicking outside the box - does not close

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
The escape key closes the modal, but clicking outside doesn't.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 1 |
