### ISSUE TITLE
[Bug]: Button Style and Button Variant Have same Name.

### ISSUE THREAD

**Issue by techbhavin** [appsmithorg/appsmith#8990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Button Widget Button Style and Variant have the same name.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/58818598/140018870-1fd76489-13ee-4b47-ba9b-30b7d550de91.png)

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
How urgent is this, And what kind of an impact does this make?

**Comment by marks0351** [comment]
@somangshu this is a coding improvement. I would say this should be done before we do theming to avoid readability and maintainability.

**Comment by somangshu** [comment]
Understood, Ill be adding this to the theming project. 

cc @jsartisan

**Comment by jsartisan** [comment]
We won't need `ButtonStyleTypes` now since we rely on background color for any color logic, not on the button style type.
