### ISSUE TITLE
[Bug]: App is publicly accessible even when the toggle is turned off during app share

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#8999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App is still publicly accessible when toggle is turned off during app share. Tried to repro this on a new app and this worked  as expected (see video). Only this [old app of mine](https://app.appsmith.com/applications/615c82c9ea18372f05103a0c/pages/616717781e01bd5e20880d55) shows up publicly.
 (https://app.appsmith.com/applications/615c82c9ea18372f05103a0c/pages/616717781e01bd5e20880d55)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e4989e4e32d14e31b1e8beadb599a26a-00001.gif)](https://www.loom.com/share/e4989e4e32d14e31b1e8beadb599a26a)

### Steps To Reproduce

1. Get publicly available app link from **Share**
2. Disable the _public app_ toggle and the app should display a login page - which usually happens but this month old app still displays all content

### Environment

Production

### Version

Cloud

**Comment by nayan-rafiq** [comment]
I've checked the DB for the application - although it has `isPublic=false` but it has `anonymousUser` with `read` permission in it's policy. That's why it's publicly available.

**Comment by nayan-rafiq** [comment]
I've found the underlying problem and created a PR for that.

**Comment by RakshaKShetty** [comment]
The issue is reproducible with the below app, hence reopening the bug
https://release.app.appsmith.com/applications/613f19670445da6f72168481/pages/613f19670445da6f72168483

**Comment by ramsaptami** [comment]
@nayan-rafiq App can still be accessed
https://www.loom.com/share/78d3829b7b5b491984b7badbc5c626dc

**Comment by nayan-rafiq** [comment]
@RakshaKShetty It should be fixed in release now and will be fixed in production when current release is live.
