### ISSUE TITLE
[Bug]: Overlapping UI in Tabs, Menu Options, Table Columns

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#9004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![](https://cdn.discordapp.com/attachments/760761686549463060/905584705427083265/Screenshot_from_2021-11-03_15-28-54.png)

Text icon overlaps the Tab Name field.

Also are we aware that we could generate dynamic TabName by writing JavaScript inside the tab name field?

### Steps To Reproduce

1. Add a tab widget
2. Give it a huge name like `{{appsmith.store.value_key_big}}`
3. See the issue

### Environment

Production

### Version

Cloud

**Comment by bamboowonder** [comment]
I love that we can use JS *anywhere* in Appsmith.  For this application, a critical feature is being able to dynamically define various parts of the scaffolding on the app.    For our staff, we'll have them setup their day by defining which "projects" they'll be working on.  Aside from defining the tabname, many of the queries will also be customized the the specific projects they choose.   Please do keep this feature to dynamically name tabs.   (and even better to dynamically create and remove tabs)
