### ISSUE TITLE
[Feature]-[12000]:Support MongoDB Serverless by upgrading MongoDB driver

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#9012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As mentioned in the official forums at https://www.mongodb.com/community/forums/t/community-day-trivia-25-which-mongodb-java-driver-version-added-support-for-connection-to-mongodb-atlas-serverless/116142/2, support for MongoDB Atlas Serverless is only available from Java driver version 4.3.

### Why should this be worked on?

MongoDB Serverless is a new product from the MongoDB team and looks like more and more firms are starting to use it. Appsmith's MongoDB plugin currently can't connect to those databases.

**Comment by nidhi-nair** [comment]
Looks like this upgrade is already done and we're able to connect to serverless Mongo without any issues now.
