### ISSUE TITLE
[Bug]: Retain page order or display pages alphabetically when rearranging it on duplicated app

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an app is duplicated and contains hidden pages then duplicated app's pages are shuffled in random logic. Would be great to move hidden pages to the end of the list and alphabetize the remaining **_or_** retain page index positions as original app, Makes it easier for user to navigate/compare on 2 apps if page order is retained.

**Original App**
![image](https://user-images.githubusercontent.com/79509062/140505807-69f45c6c-5089-4201-b1cd-8dcac444d368.png)

**Duplicated App**
![image](https://user-images.githubusercontent.com/79509062/140506587-413b82e0-ff55-4c37-b7d7-9a5c3d659d2f.png)

### Steps To Reproduce

1. Have multiple pages on an app including a few hidden. Observe index positions of pages
2. Duplicate this app and observe the index positions. 

### Environment

Production

### Version

Cloud

**Comment by shwetha-ramesh** [comment]
Also observed pages are shuffled for nonhidden pages and also on fork 
https://loom.com/share/17899a548ce84ce0a6bc0b54c98713e3

**Comment by kocharrahul7** [comment]
Duplication is no longer a feature. With forking apps, the order of pages is retained
