### ISSUE TITLE
[Bug]: Error while setting up SSL

### ISSUE THREAD

**Issue by chitrang89** [appsmithorg/appsmith#9022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Team,

I've been trying to setup SSL on my freshly installed instance on AWS. As described in the documentation, I'm trying to run ```./configure-ssl.sh``` and running into an error as per screenshot below. Any clues?

<img width="784" alt="Screen Shot 2021-11-08 at 1 37 45 PM" src="https://user-images.githubusercontent.com/1250576/140668463-ea66940d-28e9-4512-8174-9811b5dbafee.png">

### Steps To Reproduce

1. Follow steps as laid out here: https://docs.appsmith.com/setup/instance-configuration/custom-domain#aws-ami

### Environment

Production

### Version

Self-Hosted

**Comment by sharat87** [comment]
Hey, thanks for reporting this. This looks to be a documentation error. I'm currently resolving this. You can basically follow the instructions at https://docs.appsmith.com/setup/instance-configuration/custom-domain#docker-k8s instead. As in, please open the `stacks/configuration/docker.env` and set the value of `APPSMITH_CUSTOM_DOMAIN` to your custom domain. Then restart the instance using `docker-compose restart appsmith`. This will auto-provision an SSL certificate for this domain.

Can you try the above and let us know if it resolves the issue please?

**Comment by chitrang89** [comment]
Hi @sharat87,

This seems to have fixed the issue. Appreciate the prompt response :)

**Comment by sharat87** [comment]
Thank you for confirming!
