### ISSUE TITLE
[Feature] Add animation to UI components

### ISSUE THREAD

**Issue by Rahul-160** [appsmithorg/appsmith#903]
## Summary
My idea is to make some animations for better presentation to user. Animations while tapping a button and tabs etc. If we take an example of popular games like PES 2020, you can see that if we are tapping on a button, then the sub options will be seen after a little animation. It can give good effects while using the app. That's all I'm trying to say. Thank you. 

## Motivation
It will be more fun while using app smith.

**Comment by mohanarpit** [comment]
@Rahul-160 Can you please elaborate? What sort of animations are you referring to? Any example that you can link to?

**Comment by satbir121** [comment]
@Rahul-160 Thanks for reaching out and helping us to make Appsmith better! We really appreciate it!

A small feedback: Please rename the issue to `Add animations to UI components`.

**Comment by Rahul-160** [comment]
> @Rahul-160 Can you please elaborate? What sort of animations are you referring to? Any example that you can link to?

Hi, I have elaborated my idea. Please, check it out.

**Comment by Nikhil-Nandagopal** [comment]
@Rahul-160 thank you for the idea. Animations do make sense but they're really hard to get right unless we focus on what needs to be animated. Would love some help there. If you can make a list of the exact interactions where animations could help, it'll help us tackle this better

**Comment by Rahul-160** [comment]
I don't know whether these can happen using code, but it's my idea to your repo.
1. When we searching some thing in search bar. There should have something like in github, when we tried to fork others repo. We can see that animation "brown colour thing forking/Copying".
This is what I'm trying to say. 
Thank you.

**Comment by Nikhil-Nandagopal** [comment]
Closing this as we aren't going in this direction for our new design system
