### ISSUE TITLE
[Bug]: In generate page the searchable column dropdown  alignment is broken 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ingenerate page when the user selects the column name from searchable column dropdown the datatype alignment is broken in quick page wizard 
![Uploading image.png…]()

### Steps To Reproduce

1. go to canvas
2. select generate from data table option
3. select the datasource from the dropdown
4. Now select table from the dropdown
5. Now select the searchable column
6. Now the dropdown alignment is broken because of a extra text displayed

### Environment

Release

### Version

Cloud

**Comment by RakshaKShetty** [comment]
reopening the issue 
![image](https://user-images.githubusercontent.com/45958978/147914825-cf4f5e91-ed27-48bc-bcba-315a2696b285.png)

**Comment by Rishabh-Rathod** [comment]
@jsartisan  Can you check the above issue and also [this issue](https://github.com/appsmithorg/appsmith/issues/9428)?
Both seem to be after the style change of tailwind and were missed.
