### ISSUE TITLE
[Bug]: The error icon is broken in Debugger section

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the error icon is broken in the query debugger section
![Uploading image.png…]()

### Steps To Reproduce

1. Go to the datasource section 
2. Add a query
3. Make some mistakes in Query 
4. Run the query 
5. See the error icon displayed in the response section
6. The icon is broken

### Environment

Release

### Version

Cloud

**Comment by akash-codemonk** [comment]
@RakshaKShetty It is not clear what is broken, could you please attach a screenshot?

**Comment by RakshaKShetty** [comment]
@akash-codemonk attaching the screenshot
![image](https://user-images.githubusercontent.com/45958978/141057151-2b8222f1-30d1-4462-b538-caf487fee6c3.png)

**Comment by akash-codemonk** [comment]
ok I think the height of the pane is too short here, so you don't see the full icon. Do you see the full icon when you increase the height?

**Comment by Irongade** [comment]
@akash-codemonk @RakshaKShetty  This is not a bug, all the user has to do is pull the response Tab viewer up to see the full icon.
