### ISSUE TITLE
[Docs] Change docker section steps number to correct values

### ISSUE THREAD

**Issue by srivickynesh** [appsmithorg/appsmith#904]
## Documentation Link 

https://docs.appsmith.com/quick-start#docker

## Describe the problem

The steps mentioned in docker section shows step number as 1 for all steps mentioned in this section.

## Describe the improvement

Changing the number of the step to 1,2,3 and 4 would be more readable and understandable.

**Comment by JamesT44** [comment]
Could I work on this issue?

**Comment by JamesT44** [comment]
I've added a PR for this. Please let me know if anything needs changing.
