### ISSUE TITLE
[Bug]: User with 'App viewer' rights can see New button to create applications

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When User A creates a new organization with no applications in it and shares that organization with User B with only "app viewer" permission. User B is displayed with _NEW_ button to create application. Upon clicking that an Error is displayed.
![image](https://user-images.githubusercontent.com/92293815/140736734-ddf69301-dc98-47a8-8173-63841a78dd02.png)

**Expected behavior:** User B must not be displayed with "New" button if the user has App Viewer permission

### Steps To Reproduce

1. Login with User A create a new Organization with no applications in it.
2. Share this Organization with User B with _App viewer_ permission only. 
3. Login with User B and verify the organization. 

### Environment

Production

### Version

Cloud

**Comment by Tooluloope** [comment]
@somangshu is this for the App viewers pod?
