### ISSUE TITLE
[Feature]: JSONWidget that will allow crud operations on JSON data.

### ISSUE THREAD

**Issue by siddhant-ti** [appsmithorg/appsmith#9047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This widget displays JSON data, users can expand/collapse any object or array within it.
Users can interact with it by creating new key-value pairs, updating/deleting the existing ones

### Why should this be worked on?

Appsmith doesn't have Nested lists widget yet, so JSON widget will allow interacting with nested data.
Also even if nested lists are created they would take a lot of space on UI, compared to that if user wants CRUD operations on nested data, a small collapsible/expandible JSON widget would be preferable.

**Comment by Nikhil-Nandagopal** [comment]
Hi @siddhant-ti 👋 
We already have this widget tracked here #3360 do leave any additional comments there
