### ISSUE TITLE
[Docs] Two steps points to same step number in google maps section

### ISSUE THREAD

**Issue by srivickynesh** [appsmithorg/appsmith#905]
## Documentation Link 

https://docs.appsmith.com/third-party-services/google-maps

**Comment by mikeattara** [comment]
Hello @Nikhil-Nandagopal and @srivickynesh,

I will like to take this up

**Comment by daniloff200** [comment]
Looks like, PR for this already exist in https://github.com/appsmithorg/appsmith-docs/pull/34

**Comment by Nikhil-Nandagopal** [comment]
@mikeattara this seems to be fixed so I urge you to pick up something else
