### ISSUE TITLE
[Bug]: Issues related to AIRTABLE integration

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### List of Issues

- [x] Clicking on Test does not show any message 
- [x] Error should be in an understandable format
- [x] ~~API Key must be stored in an encrypted format~~ 
- [x] No watermark in the fields to help the user 
- [x] Having space in the table name is not accepted
- [ ] Suggested Widget displays only Text  widget
- [x] Documentation not available
- [ ] Default Command should be populated to bring inconsistence 
- [x] Appropriate error message is not displayed to user On adding record Id wrong in Retrieve Method 
- [x] Bad error when a user does not add a comma when at the end of body line while updating command 
- [x] Bad error handling when inappropriate data is filled into Fields  option (List Records)
- [x] For update the user need to add the entire set of fields rather we can use only the respective field that needs a change "PATCH CMD"
- [x] BaseID watermark can should be changed to "appxxx" from "basexxxx" as most of the base id have this format 
- [x] Duplicate, Import & Export and Fork is broken for Airtable
- [x] When the Update query is executed with wrong input inappropriate error is displayed to a user

### Environment

Deploy Preview

### Version

Cloud

**Comment by nidhi-nair** [comment]
❤️ Thanks for being so prompt with this @prapullac, you're awesome!

**Comment by nidhi-nair** [comment]
The rest of the issues will be fixed after introducing transfofmation modules for each integration. I'm moving this to the product backlog till that point.

cc: @prapullac for change in scope of testing
cc: @rohan-arthur for tracking documentation which needs to still happen and is the only other achievable task on this list right now.

**Comment by felixsuarez0727** [comment]
> - [x] 1. Clicking on Test does not show any message 
> - [ ] 2. Error should be in an understandable format
> - [ ] 3. ~~API Key must be stored in an encrypted format~~ 
> - [x] 4. No watermark in the fields to help the user 
> - [x] 5. Having space in the table name is not accepted
> - [ ] 6. Suggested Widget displays only Text  widget
> - [ ] 7. Documentation not available
> - [ ] 8. Default Command should be populated to bring inconsistence 
> - [ ] 9. Appropriate error message is not displayed to user On adding record Id wrong in Retrieve Method 

**Update:**

1. Not sure what it refers to, but it's marked as completed.
2. Besides @prapullac , @btsgh  also raised her concerns regarding confusing error messages from Integrations. At the moment we will only forward the response from the API, currently there are no plans to make transformations to the responses from SaaS Integrations.
    - Need to check if #15404 refers to the same.
3. Marked as completed.
4. I suppose it's talking about Tooltips. Marked as completed.
5. Marked as completed.
6. Asking @prapullac to clarify this.
7. Already completed: https://docs.appsmith.com/reference/datasources/airtable
8. This will be tracked on #9357.
9. Same as point number 2.

**Comment by prapullac** [comment]
Clarity to point 6 : @felixsuarez0727 
On Airtable we show only text widget for connection however on other DB connection we have Table dropdown widget as well
![Screenshot 2022-08-11 at 10 57 48 AM](https://user-images.githubusercontent.com/71753653/184069859-a21a4c21-b447-4d51-b2d5-ed6d4c01f236.png)

**Comment by felixsuarez0727** [comment]
Thank you for the clarification @prapullac (also thanks for creating #15972).

We will handle the error messaging format issue on #15404.

**Comment by felixsuarez0727** [comment]
Focus on:  Default Command should be populated to bring inconsistence.

**Comment by rohan-arthur** [comment]
not our focus for the foreseeable future, will get around to this at a later time.
