### ISSUE TITLE
[Bug]: List Widget contents are not getting loaded intermittently

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#9066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

List widget is going blank, after updating with the JSON object
Refer the snapshot
<img width="993" alt="Screenshot 2021-11-10 at 11 46 33 AM" src="https://user-images.githubusercontent.com/67676905/141060158-58e45af0-68f1-4ff9-8305-438e3d006581.png">
t

### Steps To Reproduce

Steps:

1. Bind API to a JSON object
2. Add this JSON object to a List widget
3. Check if the List widget is displaying data.

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@YogeshJayaseelan please verify the reproducing steps for this issue

**Comment by ashit-rath** [comment]
Can we have steps for this?
List widget only works on array types and not objects. Can we verify and close this issue?
