### ISSUE TITLE
[Bug]:The Comment and view icon is not displayed for public apps

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The View and comment icon is not displayed for public apps and if the user hover and click on that location the app navigates to sign-in page 
![image](https://user-images.githubusercontent.com/45958978/141065245-8a72b007-e3bc-46b4-872d-478954cde9ee.png)

### Steps To Reproduce

1. go to the application
2. share the application as a public app
3. now logout and enter the public app link
4. Noe the View and Comment icon is not displayed 
5. Hover on the comment section 
6. Click on it 
7. The user is navigated to singing page

### Environment

Production

### Version

Cloud

**Comment by rishabhsaxena** [comment]
This was done as a temp fix, since the experience with the user logged out wasn't working well. The redirect should go back to the public app on clicking the back button. Also should consider if need to make any changes on the onboarding.

**Comment by pranavkanade** [comment]
related - https://github.com/appsmithorg/appsmith/pull/7885

**Comment by pranavkanade** [comment]
This is not a bug. This change was intentional, original ticket - https://github.com/appsmithorg/appsmith/issues/7884
