### ISSUE TITLE
[Feature]: Appsmith Windows based image

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#9076]
### Is there an existing issue for this?

- [X] #9077

### Summary

Currently, the Appsmith docker image is based on Debian, which running this on Windows hosts requires virtualization to be turned on. But this is not the case on many Windows based server environments, where virtualization as well as WSL are disabled.

If there were an Appsmith image based on Windows server images, then running them wouldn't require virtualization to be turned on and so would work in such environments.

### Why should this be worked on?

To support environments where virtualization is turned off on Windows servers.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3hbg5o)

**Comment by lublak** [comment]
Basically, there are two basic images.
Nanoserver and Servercore.
For a smaller server with less overhead the nanoserver is best suited.
