### ISSUE TITLE
[Bug]: onOptionChange when user selects Download 2 files are downloaded at once in Multitreeselect & Treeselect widget

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Two files are getting downloaded when the user changes selection from drop down. This is observed in Multitreeselect & Treeselect widget

https://loom.com/share/17c90b9d98914ea2810cb350a33549e9

**Expected Behavior:** Only one file must get downloaded 

### Steps To Reproduce

1. Drag drop Multitree select widget
2. In property entity > Actions > onOptionChange > Download > Data to download: sample > File name with extension: ext > Type: Html(or any)
3. Go back to multitree select widget drop down > from drop down select a different option.

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@Tooluloope you will have to verify why is this happeing, Keeping it under info pipeline
