### ISSUE TITLE
[Bug]:  Same name can be added to multiple tab in TABS widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The user can add the same name to the tab and we are not evaluating to show an error message this brings in conflict in identifying the Default Tab the 

### Steps To Reproduce

1) Add a Tab widget 
2) Add multiple tab 
3) rename the tab. with same name 
and observe 

![Screenshot 2021-11-10 at 4 00 41 PM](https://user-images.githubusercontent.com/71753653/141097203-61c3bdfa-b482-42c4-af39-ac16be59f00b.png)

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
This is the name and not the `key/id`, Allowing duplicate is a general [practice](https://codesandbox.io/s/pxnuj?file=/demo.js)
