### ISSUE TITLE
[Bug]: If Non public apps URL are opened then the user is not navigated to Login page and a error is displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the apps are not public if we copy-paste the URL The error message is displayed 
![image](https://user-images.githubusercontent.com/45958978/141104801-185acbd3-5a79-4a95-ba8c-5dab02e16165.png)

### Steps To Reproduce

1. Copy the Application Url 
2. go to the incognito window or normal window any other browser
3. paste the application URL
4. The user is not navigated to the Login page and also appsmith server not available error is displayed

### Environment

Release

### Version

Cloud

**Comment by pranavkanade** [comment]
@hiteshjoshi Shall we create a proper screen to indicate that the application is not public / user don't have access to it?

**Comment by trishaanand** [comment]
> @hiteshjoshi Shall we create a proper screen to indicate that the application is not public / user don't have access to it?

@pranavkanade : This is already there. This is a bug that we are seeing Appsmith server unavailable screen. Instead we should be seeing a 404 page.
