### ISSUE TITLE
[Bug]: Negative spacing in item spacing in list widget does not work anymore

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#9084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I pass negative spacing in item spacing of list widget, nothing happens. List widget ignores negative space altogether now.

### Steps To Reproduce

1. Drop a list widget
2. Pass `-5px` in item spacing.
3. Notice there is no change in spacing in list widget.

### Environment

Production

### Version

Cloud

**Comment by Tooluloope** [comment]
Minimum width would be -8px
