### ISSUE TITLE
[Docs]: Update tooltip for Total Records Count property of the table widget

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith#9090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The text on the tooltip of Total Records Count is confusing and does not deliver the meaning of the property.

### Describe the improvement

Replace the tooltip text with the following:

"It stores the total no. of rows in the table. Helps in calculating the no. of pages that further allows to enable or disable the next/previous control in pagination."

**Comment by somangshu** [comment]
@Pranay105 does this require documentation change?

**Comment by Pranay105** [comment]
@somangshu, Yes, it is not mentioned in the documentation. I'll add it.

**Comment by keyurparalkar** [comment]
@Pranay105 PR merged. Please add the documentation changes.
