### ISSUE TITLE
[Feature]: Allow users to insert hour:time:seconds - improved datetimepicker

### ISSUE THREAD

**Issue by codedmind** [appsmithorg/appsmith#9100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Improve the datepicker, isn't possible insert the seconds even if the format datetime have the seconds

### Why should this be worked on?

Maybe having three widgets, datepicker, datetimepicker, timepicker... otherwise maybe improve the actual datepicker so can be possible choose also the seconds
![image](https://user-images.githubusercontent.com/2910047/141160213-35859d0e-8d98-4110-8c47-f917c43ba5c1.png)

**Comment by somangshu** [comment]
This is possible in the current widget implementation, We need to provide an option for the developer to change the precision.
