### ISSUE TITLE
[Bug]: Select Widget highlighted value selection doesn’t reflect in the binding

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#9102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the particular scenario where the select widget's default option is bound with the Table widget's selected row,
noticed this bug of Selection not working when selecting already highlighted value. 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ab12f7171ad14b8dbe637c083a6d0178-00001.gif)](https://www.loom.com/share/ab12f7171ad14b8dbe637c083a6d0178)

### Steps To Reproduce

1. Add Form on canvas and inside that Add Select Widget
2. Add TableWidget and TextWidget on canvas 
3. Select Widget, Set Default option as `{{Table1.selectedRow.step}}` & `options` as 
```
[
  {
    "label": "#1",
    "value": "#1"
  },
 {
    "label": "#2",
    "value": "#2"
  }
]
```
4. Make `Text` of Text Widget as `{{Select1.selectedOptionValue}}`
5. Now Select 3rd Row, then select highlighted option in the Select widget and see the Text widget value.
6. If you don't see an error select 1st or 2nd row of the Table and then select 3rd row again and repeat Step 5.   

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
The problem seems to have resurfaced, Something similar was happening before with the select widget in the form because the getDerivedProperties was intermittently not called. 

@hetunandu @riodeuno do you guys remember the issue, would need the clarity

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @hetunandu @riodeuno we need to fix this with a test case. How does this keep resurfacing?
