### ISSUE TITLE
[Bug]: Error when search with app name and click on New button on homepage

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0cd9b301c6d34112a4e1f3f01f148f3f-00001.gif)](https://www.loom.com/share/0cd9b301c6d34112a4e1f3f01f148f3f)

### Steps To Reproduce

1. On Homepage click on search box
2. Search with any app name
3. Click on new button to create a new application
4. Observe that new app is not created and error is displayed

### Environment

Production

### Version

Cloud

**Comment by pranavkanade** [comment]
<img width="270" alt="Screenshot 2021-11-16 at 11 18 15 AM" src="https://user-images.githubusercontent.com/13262095/141929448-d1990b9d-3418-4604-b91a-97e9102b1cf7.png">

**Comment by pranavkanade** [comment]
Just verified on release and prod, this is no longer an issue.
