### ISSUE TITLE
[Bug]: -1 or a 2d array is shown in selectedRowIndices

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#9109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When in multi-select mode in the Table Widget, the `selectedRowIndices` has `-1` in the array. When selecting rows, the -1 entry still exists.

We need to remove -1 from the list of `selectedRowIndices`

### Steps To Reproduce

1. Add a Table
2. Bind a text widget with `{{Table1.selectedRowIndices}}`
3. See -1 as the value
4. Enable multi-select in the table.
5. The array in the text widget shows `[-1]`

<img width="908" alt="Screenshot 2021-11-11 at 11 48 35 AM" src="https://user-images.githubusercontent.com/103687/141248215-c157e1b1-7b01-462b-969a-31f80a7e15dc.png">

To reproduce the above error, the user needs to enable the enable multi-row select option. Then change the value of the default selected row. Now if the user disables the enable multi-row select and re-enable it then we get a 2d array.

<img width="155" alt="Screenshot 2021-12-07 at 14 54 29" src="https://user-images.githubusercontent.com/31691737/145041834-54600749-8ff6-4300-8bc4-aa6c62ee4183.png">

### Environment

Production

### Version

Cloud

**Comment by ArnavPuri** [comment]
Can I try to solve this issue?

**Comment by somangshu** [comment]
Greetings @ArnavPuri, thanks for showing interest 🎉 , This issue is more involved and will need somebody from the internal team to look into it.

You can take a look at other `good first issues` to find something interesting to work on

**Comment by keyurparalkar** [comment]
Steps to reproduce video:
https://www.loom.com/share/84d4e4b7dff04a4190fbde141bc3fb5e

**Comment by keyurparalkar** [comment]
During the above fix I found out one bug which causes the `selectedRowIndices` to populate with the an array with previous value of `selectedRowIndices`. Thus this leads to a 2d array e.g. [[1]]. To reproduce the above error, the user needs to enable the `enable multi row select` option. Then change the value of `default selected row`. Now if the user disables the `enable multi row select` and re-enable it then we get a 2d array. 3.

Please find below video for reference:

https://user-images.githubusercontent.com/14138515/145007342-9ba656a3-8e08-4736-9ef2-64393434be03.mp4

fix in PR: #9606
