### ISSUE TITLE
[Bug]: request @application intermittetnly doesnot return 

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#9111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Bug]: request application intermittetnly doesnot return 
```
Cypress.Commands.add("LogintoApp", (uname, pword) => {
  cy.window()
    .its("store")
    .invoke("dispatch", { type: "LOGOUT_USER_INIT" });
  cy.wait("@postLogout");

  cy.visit("/user/login");
  cy.get(loginPage.username).should("be.visible");
  cy.get(loginPage.username).type(uname);
  cy.get(loginPage.password).type(pword);
  cy.get(loginPage.submitBtn).click();
  cy.wait("@getUser");
  cy.wait("@applications").should(
    "have.nested.property",
    "response.body.responseMeta.status",
    200,
  );
  initLocalstorage();
});
```
![cypress-screenshot](https://user-images.githubusercontent.com/84702014/141254383-a7ee393a-36f6-412e-8734-ee59d6bddef2.png)

### Steps To Reproduce

This issue is seen while running some cypress tests

### Environment

Release

### Version

Cloud

**Comment by hiteshjoshi** [comment]
Hey, @yatinappsmith, I know it's been a while. Is this still an issue? Closing this but feel free to reopen it.
