### ISSUE TITLE
[Bug]: FilePicker Widget data is not loaded after uploading

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#9116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upload Works fine . But when when the file size is more than 5mb, data field is populated with string `blob:d63fa3b8-a590-4185-b391-af9c95cfb9c6?type=Text`
![image](https://user-images.githubusercontent.com/12005551/141275780-839ad471-6e09-4bc3-9072-ace5bff1d619.png)

### Steps To Reproduce

1. Upload the attached file 1 using FilePicker widget
2. On successful upload try to display the data on a text widget and see the data would be like - `blob:`
3. Repeat 1 & 2 for the file 2 and it works fine. 

### Environment

Production

### Version

Cloud

**Comment by AnaghHegde** [comment]
[generated.txt](https://github.com/appsmithorg/appsmith/files/7519424/generated.txt)
[generated_2.txt](https://github.com/appsmithorg/appsmith/files/7519427/generated_2.txt)

**Comment by SatishGandham** [comment]
Should we bypass this limit for text files? It will be a non breaking change.

**Comment by AnaghHegde** [comment]
But the issue will still be there for non text files right ?

**Comment by SatishGandham** [comment]
> But the issue will still be there for non text files right ?
Only use case for binary files is upload, and that is handled in the actions.

**Comment by Michael-sr** [comment]
Hey! I am having this same problem. My scenario involves using the FilePicker widget with any set of files of any type, but with a size limit of 100 MB.
Any solution coming soon or would I be better off looking for workarounds?

**Comment by SatishGandham** [comment]
@Michael-sr What are you doing with these files? Uploading them somewhere? or reading and processing on client?
If you are uploading, then it should work fine.

**Comment by Michael-sr** [comment]
> @Michael-sr What are you doing with these files? Uploading them somewhere? or reading and processing on client? If you are uploading, then it should work fine.

I am uploading files to the n8n webhook endpoint, but I receive file data that is less than 5MB in size. The rest come with the following data structure: {"data": "blob: ....}.

**Comment by Michael-sr** [comment]
@Nikhil-Nandagopal , thanks for clarifying the situation!

**Comment by somangshu** [comment]
@SatishGandham is this already working, Can we close the issue

**Comment by dilippitchika** [comment]
@somangshu remember the issue we were discussing where base64 uploads of even 2MB were crashing the app when referenced in any other widget? Can this part of the same bug or do we create a new bug?

**Comment by somangshu** [comment]
@dilippitchika Could you mention the issue you are referring to here?

**Comment by dilippitchika** [comment]
Upload a file which is >2MB to the file picker and reference the filepicker.files to a text widget. If the file picker type is set to Base 64, it ends up crashing the whole app.

**Comment by dilippitchika** [comment]
@AnaghHegde we don't allow file size more than 5mb in cloud. We will work on communicating this to appsmith developers in this issue.

**Comment by somangshu** [comment]
@Tooluloope can you find out the problems listed above, take a note and start work on this

**Comment by Tooluloope** [comment]
@somangshu 

- Upload a file which is >2MB to the file picker and reference the filepicker.files to a text widget. If the file picker type is set to Base 64, it ends up crashing the whole app.

Is this the only issue still hanging?

**Comment by somangshu** [comment]
@Tooluloope I think as pointed above we can also check for what data is returned.

**Comment by Tooluloope** [comment]
@dilippitchika https://www.loom.com/share/fa9a4b7a2aa1449c8f43aa56e1bf1dd7
Could you confirm if it crashes

**Comment by Tooluloope** [comment]
The main issue seems fixed.
The other issue is continued here https://github.com/appsmithorg/appsmith/issues/10379
