### ISSUE TITLE
[Bug]: Filter pop-up in table widget does not show drop down for AND/OR condition

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user gives more than 2 filters in table widget the user is not prompted with the drop down to select AND/OR condition for the third filter, but simply displays the second filter condition selected.

https://loom.com/share/cbb60f25ac8448028bd789ce73cd7da3

**Expected Behavior:** The user must be given option to change AND/OR conditions for any number of filters.

### Steps To Reproduce

1. Drop table widget
2. Click on Filter > add certain filter > Observe the third filter drop down options displayed.

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
This is expected, Logically once you start with an operator until you have nesting you cant define what level you are applying the filter on. We will need a big UX change for this, I dont think from the product POV this is required
