### ISSUE TITLE
[Feature]: List All Users in Global Admin Page for Appsmith

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#9132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A list to show all the existing users in global admin page will be very helpful.

### Why should this be worked on?

This will enhance self hosted hosts of appsmith to have a better idea of the global level settings and metrics of their hosted applications.

**Comment by sbalaji1192** [comment]
@marks0351 We have global admin settings page under a feature flag now. Though it doesn't have user details, it lists all the global settings there and you can modify them from UI itself.
