### ISSUE TITLE
[Task]: Improve Typescript support for Sagas

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We are not using typescript efficiently when it comes to Sagas. If we are using it effectively, we could've avoided some run time bugs.
I've come across [typed-redux-saga](https://github.com/agiledigital/typed-redux-saga) project and think this library can help us to improve typescript in the case of Sagas.

**Comment by btsgh** [comment]
As per the feat: upgrade to create react app 5 #14000 - since we have regression tested for CRA 5 changes, this can be closed as verified. Discussed with @aswathkk
