### ISSUE TITLE
[Task]: Git Sync v1 pending tasks 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#9137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Frontend

- [x] #8956
- [x] Pull not yet working
- [x] Push not yet working
- [ ] #6012 

### Backend

- [ ] Default config API changes

@abhvsn mentioned
- [ ] 1. Merge flow issues
- [ ] 2. Delete local branches along with the app in DB if the counterpart from remote is deleted
- [ ] 3. Implement refresh branches functionality which will handle
- [ ] 4. Prune branches (2nd point)
- [ ] 5. Update default branch from remote. Same updates should be done in DB as well so that local repo and DB should be in sync

@AnaghHegde mentioned
- [ ] Show all branches in list branch API
- [ ] Pull flow issues
- [ ] Error handling for all the flows

**Comment by rishabhsaxena** [comment]
Closing this, since we're tracking pending issues/bugs as part of #9209
