### ISSUE TITLE
[Bug]: Icon button is not getting disabled inside Table widget

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Uploading Screenshot 2021-11-12 at 4.03.50 PM.png…]()

### Steps To Reproduce

1. Drag and drop a Table widget
2. For action column change the type to icon button
3. Disable the icon button
4. Observe that the icon button do not get disabled

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
Please verify issues before creating
