### ISSUE TITLE
[Task]: Expose backgroundColor, borderRadius and boxShadow style properties on existing widgets

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#9146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Expose the following style properties on the property pane for appropriate widgets

- [ ] bacground-color
- [ ] box-shadow
- [ ] border-radius

**Comment by cokoghenun** [comment]
@sbalaji1192 Is the filepicker widget included in this change?

**Comment by sbalaji1192** [comment]
@jsartisan Could you answer the question above?

**Comment by jsartisan** [comment]
@cokoghenun @sbalaji1192 Yes. The file picker widget will be also enhanced as well with theming.
