### ISSUE TITLE
[Bug]: Passing multiple params in navigateTo inside Table Widget doesn’t work

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#9148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying the below code in Table widgets column action,
```
{{navigateTo(‘NewPage’, {Name1: currentRow.status, Name2: currentRow.step})}}
```

`{{appsmith.URI.queryParams}}` fails to show all passed params.

### Steps To Reproduce

1. Add a Table widget to the canvas
2. Create a column with type as button
3. Add OnClick action to the button column
```
{{navigateTo(‘NewPage’, {Name1: currentRow.status, Name2: currentRow.step})}}
``` 
4. Create a new page with the name "newPage" & Add a Rich Text Editor with value as `{{appsmith.URI.queryParams}}`
5. Go back to the initial page and click on button whose onClick was defined above
6. See the error

### Environment

Production

### Version

Cloud

**Comment by hetunandu** [comment]
@Rishabh-Rathod Not able to reproduce this. One thing i noticed was that you were using `{{appsmith.URI.queryParams}}` instead of `{{appsmith.URL.queryParams}}` and that could be the reason why you were not able to see the params

**Comment by Rishabh-Rathod** [comment]
Wasn't able to reproduce this issue anymore. Hence closing this.
