### ISSUE TITLE
[Feature]: App level theme control UI

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#9150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As part of the App level theming epic, we need to create a UI where the app developer can change themes, update theme configs.

https://www.figma.com/file/l58dRgau7gCASJSJN3OicH/Application-Theming-Thu-19-Aug-2021?node-id=2%3A1

### Why should this be worked on?

This UI serves as the gateway to App theming.

**Comment by dilippitchika** [comment]
Adding bugs discussed with @jsartisan 

1. Selected item border cuts off for list widget
2. The icon in button widget is little bigger ( it should be 14px )

![image](https://user-images.githubusercontent.com/19730984/147822682-c8d51af2-7e8f-4173-b114-497dcec97eb9.png)
