### ISSUE TITLE
[Bug]: Disable functionality is not working for Icon widget in Table

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Uploading Screenshot 2021-11-15 at 11.07.57 AM.png…]()

### Steps To Reproduce

1. Drag and drop a Table widget
2. Change the action column type to Icon widget
3. Select a icon widget
4. Enable disable property
5. Observe that icon widget do not get disabled

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@vivekverma2312 the image update has failed, Can you also tell me does the button event still trigger, If it does change the priority to high

**Comment by Tooluloope** [comment]
@vivekverma2312 @somangshu 
I cant reproduce this.
