### ISSUE TITLE
[Bug]-[2800]:Mongo Plugin - get structure fails when system.views collection is present

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If `system.xyz` collection is present in database then `getStructure` call fails with the following error: 
```
not authorized on <db name> to execute command { find: "system.views", limit: 1, singleBatch: true...
```

However, user is able to run queries successfully on normal collections. The issues are:
 (1) they are not able to see the list of available collections in the entity explorer 
 (2) generate page fails because `getStructure` call fails. 

The user has summarized the issue as follows: 
```
Summarizing it here...

1. Any DB having views inside it is not able to list the collections in it
2. Queries are working fine if we know the name of the collection that we want to query
3. Collections are getting listed if there are no views in the DB
4. Metabase also connects to DB and lists all the views/collections in it, which is why I brought up the comparison

I think that collection is created when you create views from collections in the DB.
```

Ref: https://discord.com/channels/725602949748752515/909411482754752512/909480363900936264 
Ref: https://jira.mongodb.org/browse/SERVER-27554 

### Steps To Reproduce

1. Create a database on MongoAtlas such that it has a `system.views` or `system.xyz` collection (It seems that `system.views` collection gets created when a view is created in Mongodb - not sure though).
2. Create a datasource on Appsmith to connect to the database in (1). 
3. Create new query on the datasource in (2) and check out the entity explorer section that lists the collections.
4. Click on `generate page` for the datasource. 

### Environment

Production

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6m2oc)

**Comment by mingfang** [comment]
This bug makes the MongoDB plugin completely unusable.
As stated in https://jira.mongodb.org/browse/SERVER-27554
```
...the existence of the system.views collection is an implementation detail. 
A user with the dbAdmin or root roles should prefer to do all of their views-related maintenance using commands like listCollections
```
That MongoDB issue was closed back in 2017!

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 350 |
| Effort (months)  | 0.50 |

**Comment by rbialek** [comment]
Having the same issue on Atlas Mongo: 

`
Query failed with error code 13 and error message 'not authorized on qa to execute command { find: "system.views", filter: {}, limit: 1, singleBatch: true, $db: "qa", $clusterTime: { clusterTime: Timestamp(1652867141, 18), signature: { hash: BinData(0, 544CAB2B61F45C26453EEDC28B31D1813D0742C9), keyId: 7040125179728495651 } }, lsid: { id: UUID("1550ebed-9295-4072-9612-cf78de743466") } }' on server railzqa1-shard-00-02.6vxkm.mongodb.net:27017
`

**Comment by Dylish1** [comment]
Hello!

Sorry is this still in dev?

**Comment by sumitsum** [comment]
@Dylish1 sorry, we havne't been able to address this issue as of yet. Can you please leave a `like` on the issue so that it may help us to prioritize it better ?

**Comment by Dylish1** [comment]
@sumitsum added some and then some :)

**Comment by pranavkanade** [comment]
@sumitsum @vaibh1297 A user faced this issue today, although they don't have the views on the DB. 

https://discord.com/channels/725602949748752515/1055730030988242975/1055730030988242975

**Comment by raushan3737** [comment]
Trying to reproduce the issue.

**Comment by rohan-arthur** [comment]
thank you, for validating this, @raushan3737 ! I will close this issue
