### ISSUE TITLE
[Bug]: Password field accepts more than 42 characters

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a new user Signs up the maximum password count that can be entered is 42 characters. But currently character count of 47 is getting accepted and user is able to sign up successfully. (Refer video)
This happens during 'Reset password' also.

https://loom.com/share/ba08dc3785f6484fb0db8bbebe8d567c

**Expected Behavior:** As prompted to the user a maximum of only 42 characters must be accepted.

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/user/login
2. Sign up > Enter new email id > Enter password with 47 character count and observe

### Environment

Release

### Version

Cloud

**Comment by vuiets** [comment]
A community member reported the same issue on https://github.com/appsmithorg/appsmith/issues/12965 and has requested we take a look at the limit again.

Password generators throw out passwords with as many as 48 characters.
