### ISSUE TITLE
[Bug]:  Debugger extends as the property pane is scrolled

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the widget is added to the bottom of the canvas if the drop-down or color pallet is opened and now scrolled it is observed that the property pane overlaps as we scroll on the white bottom 
![Uploading Screenshot 2021-11-15 at 4.33.02 PM.png…]()

### Steps To Reproduce

1) Add a tree select widget to the bottom of the widget
2) open the Property pane 
3) Scroll and open styling 
4) Scroll to see the different 
and observe

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3ee6adf132e742238d91eee93d7156f1-00001.gif)](https://www.loom.com/share/3ee6adf132e742238d91eee93d7156f1)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
This will be solved with #7361 

cc @jsartisan @vivekverma2312
