### ISSUE TITLE
[Bug]: Data type drop down in Input widget moves throughout the property pane when scrolled

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user clicks on the Data type drop down in property pane of input widget, with the drop down open when the user scrolls through the pane the drop down doesn't collapse. 

https://loom.com/share/8f1cd42dd5b94c0f8247aa1b505b931f

**Expected Behavior:** Drop down must collapse and not move throughout the pane.

### Steps To Reproduce

1. Drag and drop Input widget
2. In property pane click on _Data Type_ drop down > Now scroll through the pane and observe.

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
This is a know issue with the popper component.
