### ISSUE TITLE
[Feature]: Expose current active intervals for clearInterval API

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#9185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be a way to check which intervals are currently active. 

Currently, in the `setInterval` API we need to pass reference ID as a string, and in the `clearInterval` we need to pass the same referenceID which was earlier created to clear the interval. Suppose at start we do not have a referenceID then `clearInterval` throws an error as referenceID does not exists. To avoid this we can check if the referenceID exists or not. But currently we do not have a way to check which are the active intervals. 

### Why should this be worked on?

This will help to handle error when there is no reference ID found.

**Comment by Nikhil-Nandagopal** [comment]
@keyurparalkar the recommended way to do this would be to store the reference IDs using storeValue after the setInterval

**Comment by keyurparalkar** [comment]
@Nikhil-Nandagopal at start there might be no Intervals available, then `clearInterval` throws an error. Attaching a video which might help

https://user-images.githubusercontent.com/14138515/142194829-ec9a9abb-3ca9-48ce-a867-570172f97e35.mp4

:

**Comment by Nikhil-Nandagopal** [comment]
@keyurparalkar in this case shouldn't you be doing a check for whether the store contains a value before trying to clear the interval?

**Comment by keyurparalkar** [comment]
@Nikhil-Nandagopal thanks for the above suggestions, It is working as expected now. Storing and clearing the reference ID on `clearInterval` solved the issue.
