### ISSUE TITLE
[Bug]: The widget count mismatches with the toast message and the canvas while performing undo and redo

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the no of widgets counts mismatches with the toast message and the widgets in the canvas when performing undo and redo operation 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/0ff7648871464defb6790271b2692e5d-00001.gif)](https://www.loom.com/share/0ff7648871464defb6790271b2692e5d)

### Steps To Reproduce

1.Launch Appmsith app in release/Prod Environment 
2.Drag and drop a container widget 
3.Add two widgets inside container and add one outside container 
4.Draw and select all the widgets in the canvas and group them as container 
5. press cmd+z and read the toast message and press cmd+shift+z and read the toast message

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@marks0351 @jsartisan can you clarify the meaning of the message show in context to the situation. I am a little confused

**Comment by Nikhil-Nandagopal** [comment]
Closing since I don't see this message anymore
