### ISSUE TITLE
[Bug]: Visible toggle on page properties animates from off to on when pages are set to visible

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Visible toggle animates from off to on position when settings button is clicked. Ideally, it should be in the on position when the page is set to visible and not toggle when user navigates to page settings.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5a82a3280a1f4fc1a2422f023313fd67-00001.gif)](https://www.loom.com/share/5a82a3280a1f4fc1a2422f023313fd67)

### Steps To Reproduce

1. Go to page properties and click on settings icon and observe the toggle move from off state to on.

### Environment

Release

### Version

Cloud

**Comment by albinAppsmith** [comment]
This is fixed already and merged to release today. Please verify

**Comment by ramsaptami** [comment]
Can you share the PR for this please? I can't see the changes on release yet

**Comment by albinAppsmith** [comment]
https://github.com/appsmithorg/appsmith/pull/9013

**Comment by albinAppsmith** [comment]
Made the fix for this in https://github.com/appsmithorg/appsmith/pull/9675
