### ISSUE TITLE
[Bug]: Delete icon hover color should be red in Data source more actions menu

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/10436935/142174512-7b664879-0497-4517-b612-abb6ae1447b7.mov

### Steps To Reproduce

Create an API data source and click on more actions menu

### Environment

Release

### Version

Self-Hosted

**Comment by somangshu** [comment]
Greetings @stevenTan01, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

**Comment by stevenTan01** [comment]
I have worked on this issue a bit and have come up with this so far. Any feedback on how it looks?

https://user-images.githubusercontent.com/34069744/142740917-ed97d148-464b-4ca1-8440-548dc79ef504.mp4
