### ISSUE TITLE
[Bug]: The outline for the buttons section is not complete in the property pane of button group widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The outline for each and every buttons should be clearly visible and should be complete rectangular outline. 

![Uploading Screenshot 2021-11-17 at 3.38.32 PM.png…]()

### Steps To Reproduce

1. Launch Appsmith app in the release environment 
2. Drag and drop button group widget 
3. open property pane and observe outline of button section for each buttons

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@YogeshJayaseelan please verify issues before creating, That checkbox in the description is for a reason
