### ISSUE TITLE
[Feature]: Add a method to request for the current location of a user

### ISSUE THREAD

**Issue by KirtiChug** [appsmithorg/appsmith#9207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Fetch the current location of the user logged in through custom login
Would need the current location to be passed in maybe headers or requests in the API call.

### Why should this be worked on?

For the fields app, there might be a case where we would need information about where the logged-in user is located while adding the lead for auditing purposes. 
The logged-in user can either be through appsmith login or custom login.

Would need the current location to be passed in maybe headers or requests in the API call.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can we add a function to request the location from a user?

**Comment by hetunandu** [comment]
Yea this is possible @Nikhil-Nandagopal

**Comment by hetunandu** [comment]
@KirtiChug would you be need to watch the current location as it changes or only request it once while making the request?
