### ISSUE TITLE
[Bug]: Database connection does not allow empty password

### ISSUE THREAD

**Issue by jmaister** [appsmithorg/appsmith#9221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I configure a MySQL database with an empty password, the form does not allow me to proceed with the "Test" button.

![image](https://user-images.githubusercontent.com/374021/142215522-7376e6d8-05e0-4745-94a3-e7bab1fc345f.png)

However, I can save and continue.

### Steps To Reproduce

1. Create Datasource
2. Fill database host, port, username
3. Click "Test"

### Environment

Production

### Version

Self-Hosted

**Comment by jmaister** [comment]
![image](https://user-images.githubusercontent.com/374021/142219510-e9e035a2-eea7-4894-8f75-62bddbae5042.png)

It does not allow to run a query either.

**Comment by Nikhil-Nandagopal** [comment]
Related to #7713

**Comment by areyabhishek** [comment]
Thanks for reporting the issue. Making the password field optional makes sense. We've marked this as high and will work on this soon.

**Comment by mojtab23** [comment]
One note: I think that I need to update testcontainers version.  https://stackoverflow.com/a/65244781/3291867

**Comment by mojtab23** [comment]
related to: #10653
