### ISSUE TITLE
[Bug]: Space or newline in action binding causes Action selector not to update properly

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If we add a space after the binding curly braces, then the action selector value is not updated properly.
Refer to the following video:

https://user-images.githubusercontent.com/10436935/142255827-6268bc4f-e53e-463a-ae9b-c2e4dc65a79e.mov

### Steps To Reproduce

1. Add action binding in JS Edit mode ex: `{{showModal('Modal1')}}`
2. See how "Modal1" gets updated once we toggle the JSEdit mode
3. Now, enable JS Edit mode and change the binding to `{{ showModal('Modal1') }}` (Adds space)
4. disable JSEdit mode and see that "Modal1" is not updated into the field.

### Environment

Production

### Version

Cloud

**Comment by aswathkk** [comment]
@somangshu Can I take this as a part of PropertyPane improvements or should this be assigned to someone under the FE Coder's pod?

**Comment by somangshu** [comment]
This is something to do with the parsing, AFAIK we have seen this before. @hetunandu can you point out which POD should take care of this?

**Comment by hetunandu** [comment]
@somangshu This should be Fe Coders.

**Comment by bharath31** [comment]
No longer reproducible. Closing this issue.
