### ISSUE TITLE
[Feature]: Read environment variables from environment with inheritance in docker container

### ISSUE THREAD

**Issue by PatrickHuetter** [appsmithorg/appsmith#9226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I'm using the docker image to deploy appsmith within a Kubernetes cluster. The problem I have is that it doesn't seem to be possible to set the email/smtp settings using environment variables because the docker container will always use the variables from docker.env file within the filesystem.

It would be nice if there would be some inheritance where the OS/shell environment variables that can be injected via dockers default way that take highest priority.

I don't know wether you use spring or spring boot but this is also default behavior in spring boot. You can overwrite every configuration directive by the same name as environment variable.

### Why should this be worked on?

With this it would be more easy to deploy locally via docker and also to use Kubernetes pods without using a ConfigMap.

**Comment by Nikhil-Nandagopal** [comment]
@PatrickHuetter thank you for the feature request this is an interesting idea. We'll evaluate it and try to have it prioritised

**Comment by holyachon** [comment]
This feature is also required to deploy appsmith to AWS ECS.

**Comment by grinono** [comment]
I have the same issue for ECS deployment

**Comment by bradwood** [comment]
> I have the same issue for ECS deployment

same!  looking forward to this too!

**Comment by bradwood** [comment]
Just to add to this, an environment should be read from the _environment_ of the process/container and _NOT_ from a file. Naming a file as `something.env` is completely wrong, as this file is really now a config file which should be something like an `ini`, `toml`, `yaml` or `json` file.

Environment variables should ONLY be read from the _environment_ as the name suggests and they should **override** any setting provided by any kind of config file.

**Comment by pranavkanade** [comment]
<img width="473" alt="Screenshot 2022-01-24 at 4 28 34 PM" src="https://user-images.githubusercontent.com/13262095/150770824-922c5f35-7d76-40f8-8246-b7681307110b.png">

**Comment by marcoacierno** [comment]
Does anyone here have any workaround for this?

**Comment by bradwood** [comment]
You can probably fix this by creating your own docker container FROM this one and then wrapping the ENTRYPOINT with a shell script that takes the environment variables and writes out the config.env before starting the process... You could do this will a template file and the "envsubst" command in Linux (Docker) shell script in 3/4 lines of bash I expect.  But it's pretty hacky.

**Comment by areyabhishek** [comment]
Hi everyone, I have an update on this issue. We are just meeting a fix into release today and expect to have the fix live in production next week. Unfortunately COVID took a toll on our team and we've been recovering the past few weeks.

**Comment by funge** [comment]
Any update on this one? Thanks

**Comment by sharat87** [comment]
Hey, this was fixed as part of https://github.com/appsmithorg/appsmith/pull/10157. Please try it out and let us know if you face any further problems. Thanks!

**Comment by SelaOZ** [comment]
@bradwood Do you have that script by any chance? 

We need this to load different environments for local, stage and prod and it would be very helpful.

**Comment by bradwood** [comment]
sorry. I don't -- I've moved on since this was on my radar and I don't use appsmith

**Comment by Nikhil-Nandagopal** [comment]
@bradwood was this the only reason why you moved on? I'd love to get some of your time top learn about your experience with the platform
https://calendly.com/appsmith-nikhil/30min
