### ISSUE TITLE
[Feature]: Add a keyboard shortcut to open property pane of a selected widget

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#9230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A discord user requested this feature here is their case:
> when a text widget fill completely a container, we cannot open the text widget editor. We must grow the container, open editor and shrink again the container
original msg - https://discord.com/channels/725602949748752515/760761686549463060/910804016592719892

### Why should this be worked on?

Nice to have

**Comment by Nikhil-Nandagopal** [comment]
@pranavkanade will this still be needed once the property pane is docked and can be opened by clicking the widget directly?

**Comment by pranavkanade** [comment]
You're right, that will make this enhancement futile. Closing it.
