### ISSUE TITLE
[Bug]: Value inside the date field is getting corrupted

### ISSUE THREAD

**Issue by parth-appsmith** [appsmithorg/appsmith#9231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am fetching data from the select query on the users database and getting a proper response. The response object contains a date field which shows date in YYYY-MM-DD HH:mm format.

<img width="1792" alt="Screenshot 2021-11-18 at 12 56 25 PM" src="https://user-images.githubusercontent.com/92779003/142383796-2d35273f-3cf7-43bd-9267-ce80e83d282e.png">

When I connect the data from the same query to the table widget, the column dob shows values as **invalid date** . The column input type is also set to plain text.

<img width="1293" alt="Screenshot 2021-11-18 at 12 56 35 PM" src="https://user-images.githubusercontent.com/92779003/142384100-414b4b18-e713-4c80-b72d-8a9f1bab0707.png">

<img width="1792" alt="Screenshot 2021-11-18 at 12 56 39 PM" src="https://user-images.githubusercontent.com/92779003/142384115-b8768ddf-8ab6-444d-903c-bdcdcf644ffe.png">

<img width="1792" alt="Screenshot 2021-11-18 at 2 25 06 PM" src="https://user-images.githubusercontent.com/92779003/142384128-26fc3b94-21bf-40c8-8378-0a1b617068c1.png">

The data seems to be getting corrupted after it's getting stored in the query.data object. This is happening in both release and production environments.

### Steps To Reproduce

1. Run the select query from the users sample db
2. Connect it to the table widget

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@parth-appsmith I'm not able to reproduce this. Can you please share a video?
