### ISSUE TITLE
[Bug]: Input widget evaluation error on using totalRecordCount from Table

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When accessing table count using **totalRecordCount** on an input widget, there's an evaluation error even when input type is set to "Text" or "Number" until the JS is edited (as seen in the video)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5ebf08526fe64a9aa227b558a37d1cf1-00001.gif)](https://www.loom.com/share/5ebf08526fe64a9aa227b558a37d1cf1)

### Steps To Reproduce

1. Drag and drop input widget on the canvas along with a table widget bound to data
2. use `tableName.totalRecordCount` and observe the error displayed
3. Change input type to Number and observe the error persist.
4. Edit the JS code as seen in the video, like removing and reentering mustache braces and the error clears

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
Not reproducible in the updated input widget launched recently. Closing this. 
![Screenshot 2022-02-01 at 3 58 55 PM](https://user-images.githubusercontent.com/19730984/151952402-241a750c-2b9b-44cb-8d3b-f7605e5c1f55.png)
