### ISSUE TITLE
[Enhancement] Add the option to delete an organization from the user's home page

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#924]
## SubTasks

- The backend needs to add an API `DELETE /api/v1/organizations/{id}` that recursively deletes all the applications, pages, actions & datasources for a given organization ID. Once all the sub-entities have been deleted, the API will then delete the organization entity as well.
- The frontend needs to integrate with the API 
- The frontend needs to refresh it's local list of organizations so that this change can be reflected in the UI.

**Comment by pc9795** [comment]
As it is a spring boot project, transactions using `@Transactional` will be enabled by default. 🤔. I think we just need to create a method with delete calls of all the related entities wrapped inside a `@Transcational`.

**Comment by mohanarpit** [comment]
@pc9795 What you are saying is valid for relational databases with the JDBC connector. Since we use Mongo DB, we have to manage the transactions manually. There is a `@Transactional` annotation for MongoDB but unfortunately, I've seen issues with it in the past where the server wouldn't work properly with it. 

Disclaimer: It's been a few months that I tried that annotation. Maybe we should give it another shot with fresh eyes.

**Comment by Debsourabh** [comment]
Designs for the same:

https://www.figma.com/file/iMQ1L57rbz0gGjY8HyHUBW/?node-id=0%3A1

**Comment by sharat87** [comment]
I think we need two separate endpoints for this, one for folks to _leave_ an organization, without affecting anybody else's work and not deleting anything (besides permissions). Another one for actually deleting the organization. Anybody can leave an organization, but only admins can delete an organization.

**Comment by sharat87** [comment]
Created separate issue for leaving an organization: https://github.com/appsmithorg/appsmith/issues/4572.

**Comment by guillerodriguez** [comment]
> ## SubTasks
> * The backend needs to add an API `DELETE /api/v1/organizations/{id}` that recursively deletes all the applications, pages, actions & datasources for a given organization ID. Once all the sub-entities have been deleted, the API will then delete the organization entity as well.
> * The frontend needs to integrate with the API
> * The frontend needs to refresh it's local list of organizations so that this change can be reflected in the UI.

Perhaps you could start with a simple implementation allowing orgs to be deleted only when there are no applications left.
This at least gives users a way to delete the org even if it requires a few more steps (delete apps first).

Example use case: I just created an empty org (just playing around with the UI) which has no apps in it, and now I cannot delete it. That's strange.

**Comment by DevSnap** [comment]
> Perhaps you could start with a simple implementation allowing orgs to be deleted only when there are no applications left.
This at least gives users a way to delete the org even if it requires a few more steps (delete apps first).

This is a great trade-off!
It's a minor feature, but it's annoying not to have it.

**Comment by vincnetas** [comment]
> > ## SubTasks
> > 
> > * The backend needs to add an API `DELETE /api/v1/organizations/{id}` that recursively deletes all the applications, pages, actions & datasources for a given organization ID. Once all the sub-entities have been deleted, the API will then delete the organization entity as well.
> > * The frontend needs to integrate with the API
> > * The frontend needs to refresh it's local list of organizations so that this change can be reflected in the UI.
> 
> Perhaps you could start with a simple implementation allowing orgs to be deleted only when there are no applications left.
> This at least gives users a way to delete the org even if it requires a few more steps (delete apps first).
> 
> Example use case: I just created an empty org (just playing around with the UI) which has no apps in it, and now I cannot delete it. That's strange.

Exactly my case.

**Comment by nayan-rafiq** [comment]
Thanks for your interest @HebertFerrer. I'm assigning this to you. 
If you need any help regarding the implementation, please feel free to tag me here.

**Comment by nayan-rafiq** [comment]
@HebertFerrer do you have any update with this issue?

**Comment by HebertFerrer** [comment]
> @HebertFerrer do you have any update with this issue?

Hi @nayan-rafiq, I don't have any updates sorry, if there's someone interested in taking this issue go ahead, otherwise i'll let you know if I have any updates
