### ISSUE TITLE
[Bug]: Sorting a table with "Server Side Pagination" does not work as expected

### ISSUE THREAD

**Issue by jmaister** [appsmithorg/appsmith#9249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I sort a column on a table that has "Server Side Pagination", it only sorts the rows that are showing on the screen.

Working ok:
![image](https://user-images.githubusercontent.com/374021/142472581-4bf32021-1f66-4159-942a-869c826bf353.png)

Not OK, should show the last rows:
![image](https://user-images.githubusercontent.com/374021/142472647-0db883db-d2c7-48cc-9d63-cb469b6d5901.png)

What I expect is that when I am on page 1 and sort descending, I would see the rows with "Nombre" (name) starting with Z, Y, X, and so on.

### Steps To Reproduce

1. Create a table
2. Create a query

```
select * from drivers
limit {{driverstable.pageSize}} offset {{(driverstable.pageNo - 1) * driverstable.pageSize}}

```
3. Assign the query to the table of point 1 and set "Server Side Pagination"
4. Try sorting the columns ASC, DESC

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@jmaister you need to update your query to order by the sort order from the table. Your query should look like
```
select * from drivers order by {{driverstable.sortOrder.column}} {{driverstable.sortOrder.order}}
limit {{driverstable.pageSize}} offset {{(driverstable.pageNo - 1) * driverstable.pageSize}} {{Table2.sortOrder.order}}```

**Comment by jmaister** [comment]
@Nikhil-Nandagopal thanks for your answer. Adding the `order by` with the table parameters works for the ordering, but not when it is combined with `limit`.

This is the query that I created to make it work. First, the order as a subselect, then the limit.

```
select * from (
    select * from drivers
    order by {{driverstable.sortOrder.column || 'name'}} {{driverstable.sortOrder.order || 'asc'}}
) as tbl
limit {{driverstable.pageSize}} offset {{(driverstable.pageNo - 1) * driverstable.pageSize}}
```

Would it be a more generic way to added this to any query?

Also, I had to add the "|| 'name" and "|| 'asc'" just for when the table order is null. (The default sort column and order is a nice to have feature for data tables)

**Comment by Nikhil-Nandagopal** [comment]
@jmaister that seems odd, the ordering is done at the query level so it should always order and only then apply the limit like a standard SQL query. Could you share the evaluated value of the query and which SQL database are you using? 

Great job with the defaults, they are needed. We have an issue to pick the defaults from the UI itself. But for now this was correct

**Comment by jmaister** [comment]
I don't know what happened when I was testing it. Finally, my query works well and it looks like this:

```
select * from drivers
order by {{driverstable.sortOrder.column || 'name'}} {{driverstable.sortOrder.order || 'asc'}}
limit {{driverstable.pageSize}} offset {{(driverstable.pageNo - 1) * driverstable.pageSize}}
```

I am using MySQL.

This is the generated query: `select * from drivers order by name asc limit 4 offset 0`
