### ISSUE TITLE
[Bug]: Input of "Select" widget height differs from the "Input" widget height

### ISSUE THREAD

**Issue by tmdoit** [appsmithorg/appsmith#9253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The height of "Select" input widget is lower than the "Input" widget.

![Zrzut ekranu 2021-11-19 o 06 58 15](https://user-images.githubusercontent.com/85706044/142574411-a116ae03-f53d-45fe-8b27-dc0770a67181.png)

### Steps To Reproduce

1. Drop "Select" widget on canvas
2. Drop "Input" widget next to "Select" widget
3. Compare the input height of both

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@tmdoit thank you for reporting this! This was a really important detail

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @sbalaji1192 looks like a quickfix we can add?

**Comment by tmdoit** [comment]
Issue can be closed, I see that it is fixed, thanks for your support.
![Zrzut ekranu 2021-11-24 o 10 21 18](https://user-images.githubusercontent.com/85706044/143210360-a2cc43ef-f3f2-4155-88c3-3176d014e56a.png)
