### ISSUE TITLE
[Bug]: For Filepicker widget the close ('x' mark) option appears outside the popup window

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when user clicks on 'Select files' the pop-window which appears has its close option outside the window.
![image](https://user-images.githubusercontent.com/92293815/142610076-7089a7e2-4113-4eea-bc68-773af55d3424.png)

**Expected behavior:** 'x' mark (close option) must appear inside the window.

### Steps To Reproduce

1. Drag & drop Filepicker widget
2. Click on 'Select Files'
3.  Observe the Close option

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
still reproducible, and now there isn't even a `X` icon
![Screenshot 2024-06-25 at 11 46 15](https://github.com/appsmithorg/appsmith/assets/94514895/8d7a792d-7ae6-48db-8d52-a53cb879435c)

**Comment by Jagadeesh-90** [comment]
@Nikhil-Nandagopal @shwetha-ramesh I am picking this issue.

**Comment by daaliachhak17** [comment]
created issue in Jira-https://zemoso.atlassian.net/browse/TNOSB-425

**Comment by Nikhil-Nandagopal** [comment]
@Jagadeesh-90 @daaliachhak17 this is not a valid issue. Please only pick up issues labeled inviting contribution. You can find them here
https://github.com/appsmithorg/appsmith/issues?q=is:open+is:issue+label:%22Inviting+Contribution%22
