### ISSUE TITLE
[Bug]: Tooltip is partially hidden when any widget is placed on the extreme left of the canvas

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When any widget is placed on the extreme left of the canvas and property pane opens on the left side when mouse is hovered over any field tooltips are partially hidden.
![image](https://user-images.githubusercontent.com/92293815/142611937-cd211075-1d1b-4223-adfa-b8c695c1d220.png)

### Steps To Reproduce

1. Drag and drop any widget on extreme left of the canvas (say widget)
2. Open property on the left side
3. Hover over any field and observe tooltip.

### Environment

Production

### Version

Cloud

**Comment by Rishabhkaul** [comment]
@somangshu Do you think this issue could be closed given that property pane has changed?
