### ISSUE TITLE
[Bug]: Code goes into an infinite loop on property pane without an error for uncaught promise exception but throws a parse error with an incorrect error on JS editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Different behaviour observed on JS editor and property pane for the block of code seen below. 

- On property pane, the code within the function `UIBugs` inside of `{{function(){       }}}` on a Button widget goes into an infinite loop without giving any errors. Only browser console shows an error for uncaught promise.
![image](https://user-images.githubusercontent.com/79509062/142668097-d8920e47-b6bd-4cbd-b39e-f5082a2c36f6.png)

- On JS editor, below code gives a parse error with errors as seen in the screenshot below.
![image](https://user-images.githubusercontent.com/79509062/142664137-473796a4-fd3d-44c0-8fa0-6cb431d897a8.png)

### Steps To Reproduce

1. Go to JS editor and type in the above code and observe the errors for line 3
2. Go to property pane of a button widget (or any other trigger field) and execute code. Observe the uncaught exception error on browser console and button widget in an infinite loading loop

### Environment

Deploy Preview

### Version

Cloud

```
export default {
	myVar1: [],
	myVar2: {},
  UIBugs: () => { 
		let arr = [];
		for(let i = 0; i < 14; i++) { 
  		arr.push( appsmith.store["Bug-"+i + ""]);
		}
		const eligibleLabels= ["UI Building",  "Widgets", "Pages", "Property Pane"];
		const eligibleData = arr.filter((point) => eligibleLabels.includes(point.x));
		const chartData = {
			"type": "scrollstackedcolumn2d",
				"dataSource": {
    			"chart": {
        		"xaxisname": "Type",
        		"yaxisname": "No. Issues",
        		"numberprefix": "#",
        		"lineThickness": "3",
        		"flatScrollBars": "1",
        		"scrollheight": "10",
        		"theme": "fusion"
    			},
    		"categories": [
        {
					"category": eligibleLabels.map((label) => { return { label: label } })  
        }
    ],
    "dataset": [
        {
            "seriesname": "No Priority",
            "color": "766d7a",
            "data": eligibleData.map((row) => { return { value: row.noPriY } })
        },
        {
            "seriesname": "Low",
            "color": "eaff00",
            "data": eligibleData.map((row) => { return { value: row.lowY } })
        },
        {
            "seriesname": "High",
            "color": "e86f0c",
            "data": eligibleData.map((row) => { return { value: row.highY } })
        },
        {
            "seriesname": "Critical",
            "color": "db0723",
            "data": eligibleData.map((row) => { return { value: row.critY } })
        }
    ]
}
};
   return chartData;
};()
}
```

**Comment by ramsaptami** [comment]
Removing `;` on line 53, the error changes to unexpected bracket but does not show any lint error anywhere
![image](https://user-images.githubusercontent.com/79509062/142669401-ea47019c-7a0c-4d74-b9dc-afe4cfc2d85f.png)

**Comment by ramsaptami** [comment]
On removing `;` on line 53, the error changes to unexpected bracket but does not show any lint error anywhere
![image](https://user-images.githubusercontent.com/79509062/142669401-ea47019c-7a0c-4d74-b9dc-afe4cfc2d85f.png)

**Comment by rohan-arthur** [comment]
@ajinkyakulkarni this is a strange one, would you please help with the root cause so that we can correctly assess the impact and reach

**Comment by bharath31** [comment]
@satbir121 could we have an RCA on this?

**Comment by ramsaptami** [comment]
Seems fixed, closing the issue
