### ISSUE TITLE
[Bug]: You can start multiple group selections at once

### ISSUE THREAD

**Issue by momcilo-appsmith** [appsmithorg/appsmith#9266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I CMD + Click and drag (to select widgets inside a container) and go outside of the container, then click again to select widgets outside of it, both selections appear.

### Steps To Reproduce

Loom video of how it works:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/aca27c6a6bf94cb890427f18cbbda665-00001.gif)](https://www.loom.com/share/aca27c6a6bf94cb890427f18cbbda665)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@rahulramesha can you check this out?

**Comment by Sripriya93** [comment]
Working fine in release. Verified selecting widgets inside container and outside the container and selecting both
