### ISSUE TITLE
[Bug]: Linting not showing up for self-referenced code on property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Linting pop-up does not show up on Issue Stats page of Appsmith Standup app on the widget and field seen in the screenshot below

![image](https://user-images.githubusercontent.com/79509062/142722431-56d83d9e-4294-4eb6-864b-c5bb64d41a87.png)

### Steps To Reproduce

1. Go to Appsmith Standup app and navigate to Issue Stats page
2. Go to the trigger field of Action_Bugs chart widget and observe lint error highlight but no error being displayed

### Environment

Production

### Version

Cloud

**Comment by hetunandu** [comment]
Fixed with #9773
