### ISSUE TITLE
[Bug]: The button clicks are not working in website template page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Use this template" and "read the tutorial buttons" functionality is not working as expected in the appsmith template page 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/879b1c8d0d074ac88a7aafc606bd23ec-00001.gif)](https://www.loom.com/share/879b1c8d0d074ac88a7aafc606bd23ec)

### Steps To Reproduce

1. go to https://www.appsmith.com/template/expense-manager
2. click on Use this button
3. the click event doesn't work

### Environment

Production

### Version

Cloud

**Comment by GreenFlux** [comment]
This is no longer an issue. The Expense Manager template was removed some time ago, and all the other _Use this template_ links are working correctly. We also no longer have the _Read the tutorial_ button on templates.
