### ISSUE TITLE
[Bug]: JS editor replaces new text with original text on occasions

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are times when after function renaming or as seen in the video attached, when there's an error that occurs during code addition and during processing the exact error isn't displayed. Instead, new text is replaced by the original text. User has to check browser console to look for errors.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ea89b6c7290545339014d1307a1ddead-00001.gif)](https://www.loom.com/share/ea89b6c7290545339014d1307a1ddead)
![image](https://user-images.githubusercontent.com/79509062/142827324-d8fee9d9-c639-44c0-811b-b51828098631.png)
![image](https://user-images.githubusercontent.com/79509062/142827360-2a369ce2-6b54-455c-a4ed-f872f454a270.png)
![image](https://user-images.githubusercontent.com/79509062/142827386-1adeec5f-b539-49ef-955b-30a215defaa1.png)
![image](https://user-images.githubusercontent.com/79509062/142829955-a2550cb5-9296-411f-b36b-c33590811019.png)

### Steps To Reproduce

1. Try function name refactor and when there's an issue saving the application, there are times when this renaming fails and the function name sis reverted to the origin name
2. Follow the steps as seen in the video and observe copy paste failing when function isn't updated. Also, error displayed in not what's displayed on browser console. (Code copied is from Async/await from [this](https://deploy-preview-8988--appsmith-editor-ce.netlify.app/applications/60f00af9e356e02f25b31fc5/pages/6131f04ea74e033781b03f77?isCommentMode=false) link)

### Environment

Deploy Preview

### Version

Cloud

**Comment by ramsaptami** [comment]
Making this critical since promises is now on prod and any delay in saving application causes this issue to occur.

**Comment by rohan-arthur** [comment]
@ramsaptami please check if still reproducible - this might have been resolved in BE Coders cc @nidhi-nair

**Comment by ramsaptami** [comment]
Haven't come across this recently. May have been fixed so I'll close it for now and reopen if it happens again
