### ISSUE TITLE
[Bug]:  The params does not get populated into the fields when added via API field 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the API is been added to the API pane and then we add "?" to the API and add respective add to the same it is observed that the Params details are not inserted 

### Steps To Reproduce

1) Add a API into API field
2) Add an "?" to the api 
3) Insert an Key and value to the API 
and observe 

It is observed that the params are not added into the fields when data is added into from the API field 

### Environment

Release

### Version

Self-Hosted

**Comment by prapullc** [comment]
Issue is resolved hence closing the issue
