### ISSUE TITLE
[Bug]: Incorrect redirect url when fat container is run behind an SSL-terminating reverse-proxy

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#9285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Appsmith is running as a fat container behind a reverse-proxy that does SSL termination, like another NGINX, or Caddy, or AWS ALB, the redirect URLs generated by Appsmith use the `http:` scheme, instead of the `https:` scheme. This causes the redirect URL to be treated as invalid by the OAuth provider.

### Steps To Reproduce

1. Start a new Appsmith instance with the following command:

   ```bash
   docker run -d --name ace -p 8001:80 -p 9001:9001 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ce
   ```

   Appsmith should now be available at <http://localhost:8001>. Go through the welcome tour and then logout.

1. Install Caddy with `brew install caddy` if you are on macOS. Then create a file called `Caddyfile` somewhere on your disk with the following contents:

   ```Caddyfile
   localhost {
   	reverse_proxy :8001
   }
   ```

   Now go to the folder where you created this file in a new Terminal window and run `caddy run`. This command won't finish and that's okay. Let it stay running until the end of this test case.

   Your Appsmith should now also be available at <https://localhost>. Notice the `https:` in that URL. With this URL, we are hitting the Caddy server, which then proxies all requests to port 8001 on where our Appsmith is actually running. But this proxying happens on HTTP, not HTTPS, hence Caddy performs SSL termination here.

1. Follow instructions here: <https://docs.appsmith.com/setup/instance-configuration/google-login> with the domain being `localhost` instead of `app.appsmith.com` in step 4. Save the _client-id_ and _client-secret_ for configuring Google OAuth.

1. Open `stacks/configuration/docker.env` file from where the `docker run ...` command was executed and update the following two fields:

   ```bash
   APPSMITH_OAUTH2_GOOGLE_CLIENT_ID=client-id-from-step-2
   APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET=client-secret-from-step-2
   ```

   Save this file and run `docker restart ace` to restart Appsmith instance. Open <https://localhost> and check that `Login with Google` option is now present.

1.  On <https://localhost>, try logging in with Google OAuth. You should see an error from Google saying `Error 400: redirect_uri_mismatch`. If you do, you are seeing the bug.

### Environment

Production

### Version

Self-Hosted

**Comment by killshotrevival** [comment]
I have installed app smith on self hosted instances using, `helm install appsmith appsmith/appsmith --namespace appsmith --values values.yml --debug` and still facing this issue. Can u please help me to solve that

**Comment by joaomlopes** [comment]
I'm still facing this issue when using Google Oauth

**Comment by bcspragu** [comment]
I'm hitting this as well. I notice the behavior changes depending on the proxy that I use:

- With tinyproxy, the bad redirect domain was `https://appsmith.example.com/login/oauth2/code/google`
- With Caddy, the bad redirect domain was `http://appsmith.example.com/login/oauth2/code/google`

For Caddy, I think the issue is likely "double Caddy", where my Caddy forwards things like `X-Forwarded-Proto`, but the AppSmith-internal Caddy drops them, as [noted in the docs](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults):

> By default, Caddy passes thru incoming headers—including Host—to the backend without modifications, with three exceptions:
> 
> * It sets or augments the X-Forwarded-For header field.
> * It sets the X-Forwarded-Proto header field.
> * It sets the X-Forwarded-Host header field.

I really just want some way to tell AppSmith "Hey, this is my custom domain where you should send the OAuth2 redirect to", but using the `APPSMITH_CUSTOM_DOMAIN` env var, for example, tries to make it get it's own TLS cert and serve HTTPS, which isn't what I want.

**Comment by Yiidiir** [comment]
This issue is still persistant
