### ISSUE TITLE
[Bug]: Nav bar doesn't show up on hidden pages in view mode.

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#9288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

When a page is hidden and when you view it, the nav bar/page tabs isn't shown. There is no way to go to other pages.

### Expected Behaviour
Show the nav bar on hidden pages as well.

### Steps To Reproduce

- Add two pages
- Hide one page
- Goto the hidden page, navbar isn't shown

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@SatishGandham this is expected since this is marked as an internal page outside the navigation hierarchy. It's used for login pages
