### ISSUE TITLE
[Bug]: S3 : Move the deleting icon to the top of the Group Filter

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the Group filter is added to where Clause it is observed that the delete icon is at the bottom of the filter and leads to confusion posing it on the top of the would help us understand better 

### Steps To Reproduce

1) Navigate to S3 query
2) Add a "fetch method"
observe the delete icon

### Environment

Release

### Version

Self-Hosted

**Comment by Irongade** [comment]
This has been fixed via a commit on PR #10411.
