### ISSUE TITLE
[Bug]: Allow removing of files from the FilePicker widget

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#9305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the file picker in a form, if I erroneously select a wrong file for upload, I can't de-select & choose another file from my file system. I have to refresh the entire page causing me to lose all the data that I've already filled out in the form. This is cumbersome to do. 

### Steps To Reproduce

1. Add a FilePicker widget to the canvas
2. Select a file to upload via the file picker.
3. Click on the file picker widget again 
4. You can't deselect a previous file that was selected. Only new files can be added again. 

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you help with a video to reproduce this? It's working for me as seen below

https://user-images.githubusercontent.com/3897254/143193358-e320c740-b7dc-4665-b002-fc223dcd1b33.mov

**Comment by mohanarpit** [comment]
Sorry, unable to reproduce now. Closing this issue till I see it happen again. There is definitely some corner case where the problem is being triggered, but unable to figure out what.
