### ISSUE TITLE
[Bug]: The delete button is broken in generated crud pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Delete button is broken in Crud Pages
![image](https://user-images.githubusercontent.com/45958978/143183748-5d503e91-3e40-461c-bed7-9f6317953867.png)

### Steps To Reproduce

1. go to the Active tab
2. Click on generate the page
3. Select the datasource from the datasource dropdown 
4. select the table
5. select the searchable column
6. click on generate page button
7. once the page is generated 
8. verify the display of the delete button

### Environment

Release

### Version

Cloud

**Comment by Tooluloope** [comment]
Closed with https://github.com/appsmithorg/appsmith/pull/9356
