### ISSUE TITLE
[Bug]: The search filter result alignment  is broken inside the snippets

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The search filter result  alignment  is broken inside the snippets
![image](https://user-images.githubusercontent.com/45958978/143189093-68ff27fd-279f-4ef7-ba53-c6ec5d7f0630.png)

### Steps To Reproduce

1. Go to the Active  Datasource page
2. Click on a new query for mongo database
3. Clik on snippets 
4. Verify the display of misalignment 

### Environment

Release

### Version

Cloud

**Comment by jsartisan** [comment]
@RakshaKShetty I'll fix this one too. this is due to the introduction of tailwind and global style updates.
