### ISSUE TITLE
[Bug]: The Tablet(large) and the Tablet icon looks similar in the canvas size change section

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the same icon is displayed for Tablet(Large) and Tablet option in the canvas size change section
<img width="1680" alt="Screenshot 2021-11-24 at 12 34 10 PM" src="https://user-images.githubusercontent.com/35128442/143191136-187da401-37cc-49c4-ad77-659eb5a977c4.png">

### Steps To Reproduce

1.Launch Appmsith app in release environment 
2.Drag and drop any widget 
3.Click any where on the canvas outside of any widget 
4.On the property doc pane - Canvas size section will be displayed
5.Check the icon of Tablet(Large) and Tablet

### Environment

Release

### Version

Cloud

**Comment by momcilo-appsmith** [comment]
@somangshu I would say we just need to rotate the second one (the large one) for 90 degrees. @emysmth do you agree and can we make this change in the DS?

**Comment by rohitagarwal88** [comment]
@emysmth it's a low-hanging issue but impacts the DX. Can you help with an alternate icon that is part of our DS?

**Comment by somangshu** [comment]
@rohitagarwal88 we can follow Momcilo's suggestions
> rotate the second one (the large one) for 90 degrees

**Comment by Athayde3586** [comment]
This is mine now

**Comment by rohitagarwal88** [comment]
![tablet-line-landscape](https://user-images.githubusercontent.com/890915/175484142-c39a745f-3e42-4679-aacd-4448dfe5f53d.svg)
@rahulramesha : The landscape icon

**Comment by rohitagarwal88** [comment]
@yaldram here is the icon 
https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=4275%3A39215

**Comment by Sripriya93** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/104895602/188139130-fb608a53-c119-4881-9822-89f27380851f.png)
![image](https://user-images.githubusercontent.com/104895602/188139141-198abcf8-c5b7-4021-83f6-b3a91f3b5218.png)
