### ISSUE TITLE
[Bug]: Profile pic error on console when home page is loaded

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Browser console shows errors when display pic of users in not found.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2b646192610b4f7b908cb2daa19a02cc-00001.gif)](https://www.loom.com/share/2b646192610b4f7b908cb2daa19a02cc)

### Steps To Reproduce

1. Go to app.appsmith.com and open up console. Observe 404 errors for display pic API calls.

### Environment

Production

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6zcgc)

**Comment by abhvsn** [comment]
A user on discord also reported this, mentioning here to log the request.
