### ISSUE TITLE
[Bug]: CheckboxGroup widget - When the entire option values are removed the widget disappears when user clicks anywhere on the canvas

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the checkboxgroup widgets entire option value is removed, the widget disappears when the user clicks anywhere on the canvas. Only on mouse hovering on the are where the widget is initially placed then the widget appears

https://loom.com/share/d88d8c3a02b54ab5b96c2b79b91da53f

### Steps To Reproduce

1.Launch appsmith app in release/Prod Environment 
2.Drag and drop checkbox group widget 
3.Remove the value from the option field 
3.click anywhere on the canvas and observe

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment]
This doesn't seem to be a bug. If there's no data, then the widget will be empty. Look at the text widget, iframe widget, image widget, etc. I'll close this issue

**Comment by YogeshJayaseelan** [comment]
@areyabhishek But when the data is removed for MultiSelectTree, MultiSelect, TreeSelect or select widget - Still the widget remains.
