### ISSUE TITLE
[Bug]: 'Invite Users' table appears distorted when character count for Display name is more than 70 characters

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we assign a Display name higher than 70 characters the 'Invite Users' table appear distorted i.e., the columns and their values do not appear aligned

P.S: Noted that in real case users might not assign such long display names, and this can be 1 in 1000 scenarios.

https://loom.com/share/cce6c60933e64432aad1a4112886fc6e

**Expected behavior:** Either there must be a restriction set to number of characters for the display name can have or with any character length display name the table must appear normal 

### Steps To Reproduce

1. Go to homepage https://release.app.appsmith.com/applications
2. Extreme right corner You Account > Edit profile
3. Enter display name with a character count of more than 70
4. Repeat step 2 & 3 for 2 other accounts.
5. Share any existing organization with the other 2 accounts. 
6. Share > Manage users > Invite users. Observe Invite Users table

### Environment

Release

### Version

Cloud

**Comment by yatinappsmith** [comment]
Removing QA label as verified label was added
