### ISSUE TITLE
[Bug]: Connection to establish data is not shown for Button and Audio recorder widget 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the connection to data option is not displayed in the property pane of button and audio recorder widget

**List of Widget that doesn't have data connection option:**
1.Button widget 
2.Audio Recorder
3.FilePicker
4.Iframe

https://loom.com/share/e81efdae59f44f43a76be9c7f40594e8

### Steps To Reproduce

1.Launch Appsmith app in release/Prod Environment 
2.Drag and drop button, audio recorder widget 
3.Open the property pane and observe

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
It's only expected for display widgets
