### ISSUE TITLE
[Bug]: Select query fails on crud when the user switches between the pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Select query fails on crud when the user switches between the pages
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/df79137264b341f2955bdee6542bd2a8-00001.gif)](https://www.loom.com/share/df79137264b341f2955bdee6542bd2a8)

### Steps To Reproduce

1. Generate a crud page
2. Now create a new page and navigate back to the Previously created Generate page
3. The select query fails

### Environment

Release

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
Related to https://github.com/appsmithorg/appsmith/issues/9102

**Comment by ajinkyakulkarni** [comment]
Related https://github.com/appsmithorg/appsmith/issues/9096

**Comment by RakshaKShetty** [comment]
reopening the issue We are facing the same issue in the current release
