### ISSUE TITLE
[Bug]: Breaking UI For Authenticated API Details Page

### ISSUE THREAD

**Issue by megaconfidence** [appsmithorg/appsmith#9338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The UI for authenticated API details page is broken when a header with a really long value is set
This can be fixed with a little CSS or truncating the value. 

Here's a video to describe the current behavior:

https://user-images.githubusercontent.com/17744578/143216746-3e3f9247-b690-4b56-92c2-6dc2e57b3b55.mp4

:

### Steps To Reproduce

1. Create an authenticated API with a header having a really long value
2. Save the API
3. Notice on the API details page, that the UI is broken

### Environment

Production

### Version

Cloud

**Comment by cokoghenun** [comment]
@Nikhil-Nandagopal I'd like to work on this

**Comment by Nikhil-Nandagopal** [comment]
@cokoghenun go for it!

**Comment by skjameela** [comment]
@Nikhil-Nandagopal i would like to work on this issue but when i try to reproduct this im unable to find that ui breaking can you please help me for this

**Comment by Nikhil-Nandagopal** [comment]
@skjameela we'll mark this as closed for now. Please have a look at other issues where we are inviting contribution
