### ISSUE TITLE
[Feature] Add OAuth2 authentication for API integrations

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#934]
## Summary
Users need a way to configure OAuth authentication for their APIs. We can have a section where users can configure the OAuth2 clientId / secret in the API pane. 

## Motivation
Most SAAS integrations require OAuth and most backends support this as well.

## Additional Context
The OAuth token should be fetched, stored, and refreshed by the server using the client-Id/secret. The token should not be fetched on every action execution. The token should be auto refreshed

**Comment by nidhi-nair** [comment]
@mohanarpit Could you help me understand a use case for grant types other than client credentials? I'd assume API integrations would generally be used for processing data without interference. Do we see a scenario where applications will have interactive authentication?

**Comment by mohanarpit** [comment]
We will start with client credentials because that’s the one used for server-server authentication. For the authorization code flow, we will have use cases (in the future), where the developer will connect to their Google sheets/Oauth2 endpoint via an interactive login process.

**Comment by Debsourabh** [comment]
PFA the Figma Link.

Navigate to the Final Page to see the Designs.

https://www.figma.com/file/GZK1AFLLaKHQejRMPUfrc0/oAuth-API?node-id=287%3A1137

**Comment by Debsourabh** [comment]
@nidhi-nair has to get back with the error states. As of now, I have added generic error states. What we need to know is if we can point out which field has the error. If we can point out the field we will need to change the design slightly. Otherwise what we have handles the generic error and success states.
