### ISSUE TITLE
[Bug]: JS editor : the run UI on the response is broken 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The RUN icon present in the Js editor is broken 

### Steps To Reproduce

1) Navigate to JS editor 
2) Add a JS function 
3) observe the Run icon in the response body 

![Screenshot 2021-11-24 at 3 40 16 PM](https://user-images.githubusercontent.com/71753653/143219868-c088bbfb-e4c1-4e3d-bd31-baf1f979dfb7.png)

### Environment

Release

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
@parth-appsmith we are going to change the design itself rigth?

**Comment by ApekshaBhosale** [comment]
task - show response for sync function by default

**Comment by parth-appsmith** [comment]
@ApekshaBhosale yes, as per the new design we have a new illustration in place.
This should get resolved once those changes are implemented.
