### ISSUE TITLE
[Enhancement]: Option to recover an app that's gone into a bad state

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently we don't have a way we to salvage an app that's gone into a bad state. Deletion is the only choice but not the best one for a user. We need a way to debug root cause and/or revert to previous working state.

An example is this [app](https://app.appsmith.com/applications/6193627543aaaf0225a8048a/pages/6193627543aaaf0225a8048e/edit) of mine causes browser crash because it's infinitely running a button widget's onClick code beyond it's defined limit.

https://app.appsmith.com/applications/6193627543aaaf0225a8048a/pages/6193627543aaaf0225a8048e/edit

This was being testing in the middle of a release merge session and is not reproducible since the code used there works as expected elsewhere. The code is something on the lines of:
```
{{(function(){
 let a = "Spongebob"
 for(let i=0;i<5;i++) {
     console.log(a + " \n")
     console.log("square pants")
     console.log("\t !!")
  }
})}}
```
Some background on how it reached there - was testing out escape characters on cloned apps and triggering button widget with incorrect syntax to check for system response and this happened.

### Steps To Reproduce

1. Navigate to this [link](https://app.appsmith.com/applications/6193627543aaaf0225a8048a/pages/6193627543aaaf0225a8048e/edit) and observe the console log. There's no way to kill an infinite loop 

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This will be solved with #2285
