### ISSUE TITLE
[Docs] Steps to whitelist DB IP on AWS

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#935]
## Documentation Link 

https://docs.appsmith.com/core-concepts/connecting-to-databases

## Describe the problem

Today we direct users to whitelist our IP but we don't give them the steps to do so. Doing this on AWS is painful and a page dedicated to this would be helpful!

**Comment by AtieveWadhwa** [comment]
@Nikhil-Nandagopal I'd like to take this up, please assign it to me

**Comment by Nikhil-Nandagopal** [comment]
@AtieveWadhwa go for it!
Just to quickly discuss the doc update, we'd like a page similar to
https://docs.appsmith.com/third-party-services/email/amazon-ses
This page can come inside this folder
https://github.com/appsmithorg/appsmith-docs/tree/v1.2/core-concepts/connecting-to-databases
Don't forget to update the main summary doc. 

Also please read our [contribution guide](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) for documentation

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit the format looks good to me. Can you verify the steps are correct

**Comment by mohanarpit** [comment]
This issue is up for grabs again. Please feel free to pick it up and resolve.

**Comment by ng29** [comment]
> This issue is up for grabs again. Please feel free to pick it up and resolve.

Hey @mohanarpit  Can i work on this?  Would be glad to contribute around AWS 👍

**Comment by ng29** [comment]
> > This issue is up for grabs again. Please feel free to pick it up and resolve.
> 
> Hey @mohanarpit / @Nikhil-Nandagopal Can i work on this? Would be glad to contribute around AWS 👍

I have created a draft PR for the underlying issue, kindly review and merge if no changes are required.

**Comment by Nikhil-Nandagopal** [comment]
@ng29 thanks for your contribution. @mohanarpit can you verify this

**Comment by mohanarpit** [comment]
@ng29 Thank you for this PR! It has been merged 🎉
