### ISSUE TITLE
[Bug]: Prompt is occasionally displayed to user to refresh page after prod has been updated

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App shows a prompt to inform user that Appsmith has been updated and a page refresh is needed. This happens occasionally when a new app is created or when user navigates back to home page and repeats more than once even after actions that involve page refresh has taken place.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ceb221b0e4584e49b180b47cef757b62-00001.gif)](https://www.loom.com/share/ceb221b0e4584e49b180b47cef757b62)

### Steps To Reproduce

1. Create a new app and observe the toast message as seen in the clip above.
2. Go back to home page and observe the same toast appear (at times)

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami does this happen even after you clicked on the refresh option?

**Comment by ramsaptami** [comment]
It doesn't repeat after clicking on refresh, no. Though it appears after a page refresh action like, when the page loads after navigating back to the home page

**Comment by Nikhil-Nandagopal** [comment]
This is expected because app updates can cause crashes unless a hard refresh happens and normal refresh will generally return the cached version of the app so only clicking it will trigger a hard refresh
