### ISSUE TITLE
[Feature]: Add ability to choose a default action for SaaS Integrations created with the Saas Manager App

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#9357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow contributors to choose which action should be populated by default in list of actions for a SaaS integration.

### Why should this be worked on?

This lets users see a populated query editor instead of a blank slate.

**Comment by felixsuarez0727** [comment]
@nidhi-nair, do we have properties that can be controlled from the SaaS App to control this? Will this require BE/FE changes?
