### ISSUE TITLE
[Feature]: Airtable Connexion

### ISSUE THREAD

**Issue by crystalnoir** [appsmithorg/appsmith#9359]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

A database that is very used in the "no code" sphere. Airtable is a good way to have a database with multiple views.

### Why should this be worked on?

Airtable is a reference in cloud databases for no code / low code projects. It's a simple way to have a database with some relationship easily.

**Comment by Nikhil-Nandagopal** [comment]
Hi @crystalnoir 👋 Thank you for the feature request. We have this issue tracked here #801
You can follow it for updates :)
