### ISSUE TITLE
[Bug]: Docked property pane drag to expand is having some glitches

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/10436935/143398139-862fff75-2408-4740-9786-5bd9f860b841.mov

### Steps To Reproduce

Try expanding property pane by dragging. Moving mouse to top or bottom direction also expands the property pane

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@prsidhu can you think of a solution here?

**Comment by prsidhu** [comment]
@somangshu yeah I'll take it up.
