### ISSUE TITLE
[Feature]: Add Ctrl + / shortcut for comments in JS Editor

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#9369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When writing code, using the `Ctrl + /` shortcut is very useful to mark a line as a comment or move it back to code. Request to please add this shortcut handling in Appsmith JS Editor. 

### Why should this be worked on?

Shortcuts make code writing a lot faster & simpler. Hence, adding some well known shortcuts in our editor will make the JS Editor a lot more useful and quicker to work with.

**Comment by Nikhil-Nandagopal** [comment]
FYI this conflicts with the open / close of the entity explorer. @jsartisan we should change the shortcut for that

**Comment by bharath31** [comment]
@ohansFavour I noticed that we tried adding support for this but the [PR](https://github.com/appsmithorg/appsmith/pull/15135) was closed. Does it need more work? If yes, could you share an estimate?

**Comment by ohansFavour** [comment]
Some extra modifications need to be done to this [PR](https://github.com/appsmithorg/appsmith/pull/15135). Check out [these comments](https://github.com/appsmithorg/appsmith/pull/15135#issuecomment-1189948280). This should take about 2 days to complete.

**Comment by bharath31** [comment]
@satbir121 could we prioritize this given some work has already gone into it?
