### ISSUE TITLE
[Bug]: JS Objects Don't Get Copied Over When An App Is Duplicated

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#9372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS objects are not copied over when an application is duplicated. But this issue does not exist when an app is forked or exported

### Steps To Reproduce

1. Create an app
2. Create a JS object file
3. Duplicate the app
4. In the duplicated app, the JS object file does not exist

### Environment

Production

### Version

Cloud

**Comment by practical-programmer** [comment]
I faced the same issue. Workaround is to export, change name and import application json

**Comment by cokoghenun** [comment]
> I faced the same issue. Workaround is to export, change name and import application json

Don't worry about this. It will get fixed ASAP 😉
