### ISSUE TITLE
[Feature]: Custom domain should be configuration from Admin Settings UI

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#9377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The custom domain should be configurable from the Admin settings page with the env variable name `APPSMITH_CUSTOM_DOMAIN`. This needs changes both in the backend to whitelist this env variable for admin settings, and in the client to add the form field for setting the custom domain.

### Why should this be worked on?

Currently settings custom domain has to be done via editing the server's `docker.env` file, which isn't very convenient.

**Comment by sbalaji1192** [comment]
@nayan-rafiq
Pushed FE changes to `feat/custom-domain-settings`.
- Added `Custom Domain` setting under `Advanced` tab.
