### ISSUE TITLE
[Bug]: Debugger shows incorrect message for toast type

### ISSUE THREAD

**Issue by jean-jacket** [appsmithorg/appsmith#9384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The debugger says `Toast type needs to be a one of success, info, warning, danger` but `danger` doesn't work. After some trial it seems `error` works. So the message in the debugger is wrong. 

### Steps To Reproduce

1. Call the `showAlert` function with `danger` as the type. (`showAlert("Error", "danger")`)

(I'm not sure which environment to select. I'm using version `1.6.0`)

### Environment

Release

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@jean-jacket thank you for reporting this! @ohansFavour can we get this quickly resolved?
