### ISSUE TITLE
[Docs] Sort the widgets alphabetically in the widget-reference section

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#939]
## Describe the problem

The widgets need to be listed alphabetically in the summary section of the documentation

**Comment by JoelLau** [comment]
hi @Nikhil-Curefit , will you be working on this issue yourself? If not, can I take this up as part of Hacktoberfest?

**Comment by Nikhil-Nandagopal** [comment]
@JoelLau I'm not! Please take this up!

**Comment by Nikhil-Nandagopal** [comment]
@JoelLau I don't see a PR raised for this issue so I'm unassigning you. Feel free to come back to this when you have the time :)

**Comment by snehal199** [comment]
Can I pick this up @JoelLau ?

**Comment by JoelLau** [comment]
hey sorry, things got a bit crazy at work. please go ahead and re-assign this issue to someone else. thanks for asking @snehal199 !

**Comment by mohanarpit** [comment]
@snehal199 It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, check out the [Appsmith Challenge](https://github.com/appsmithorg/appsmith/discussions/863) where you can win some cool swag by inviting your friends to contribute to this project as well.

**Comment by snehal199** [comment]
Thanks @mohanarpit ! Will start working on the issue right away :smiley:
