### ISSUE TITLE
[Type]-[24000]:Refactor Action Selector component

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#9391]
## Description
Refactor the existing Action Selector component to improve stability
- Easy to add new action functions
- Use AST instead of Regex
- Accept object-based arguments
- Add autocomplete and linting

### SubTasks
- #3027
- #8489
- #9669

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.5 |

**Comment by bharath31** [comment]
Tracking this epic here- https://github.com/appsmithorg/appsmith/issues/16294
