### ISSUE TITLE
[Feature]: User should be able to use readonly GSheet without authentication

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#9398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

User should be able to use readonly GSheet without authentication

### Why should this be worked on?

Currently inorder to use gsheet user has to authenticate via google. If a google sheet is accessbile publicly he/she should be able to use this sheet without authentication.

**Comment by rohan-arthur** [comment]
will be addressed in #18337
