### ISSUE TITLE
[Bug]: Post API Not working

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#9401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A user reported that their post API Fails when the response headers have a \

### Steps To Reproduce

1. Open this app and run the API
https://app.appsmith.com/applications/611babad695af65b46d732f6/pages/611babad695af65b46d732f8/edit/api/61a0b246f6f14050cbd7da9c

### Environment

Production

### Version

Cloud

**Comment by hexaeight** [comment]
As Nikhil pointed out this was a bug in the content type, once the content type was corrected the post api worked fine... Thanks for your support

**Comment by nidhi-nair** [comment]
Thanks for the update @hexaeight! Closing this issue per the above comment.
