### ISSUE TITLE
[Bug]-[17]:Inconsistencies in Font style

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the table widget we have underline option in font style

![Screenshot 2021-11-26 at 3 41 32 PM](https://user-images.githubusercontent.com/10436935/143564376-16b60bb4-cc96-4f39-9a17-0fa6f1f25b9a.png)

In other widgets such as TextWidget and InputWIdget, we don't have underline option

![Screenshot 2021-11-26 at 3 42 31 PM](https://user-images.githubusercontent.com/10436935/143564495-746afd17-f34c-4a4e-bcf5-ef7a6a683063.png)

### Steps To Reproduce

1. In table widget, Select column type as Plain Text and look at font style
2. In other widgets, look at font style

## Fix to do

1. Add the underline option in the `Label styles `> `Emphasis` following widgets
  - Inputs : Input, Currency input, Phone input
  - Selects : Select, multi select, tree select, multi tree select
  - Datepicker
  - Rich text editor
  - Boolean widgets : Switch, checkbox
  - Group widgets : Switch group, Radio group, Checkbox group
  - JSON Form all column types
  - Range Sliders: Range Slider, Number Slider, Range Slider

2. Add the underline option in the Emphasis for the Text widget

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 17 |
| Effort (months)  | 0.5 |

**Comment by sbalaji1192** [comment]
@dilippitchika What should be the expected action here? 
1. Should we remove the `underline` option in Table widget ?, or
2. Should we add the `underline` option in other widgets?

**Comment by jdun28** [comment]
Would it be okay if I worked on this one? I can create a PR both ways so that you can decide which you want to merge in - either underline added to all or underline removed from the table font styles.

**Comment by dilippitchika** [comment]
Missed this, we cannot remove this now from table since it's already being used and there is chance people can write JS to underline something. 

It's better if we only add the underline option in other places.

**Comment by dilippitchika** [comment]
Updated the issue description to reflect the fix

**Comment by aswathkk** [comment]
Hi @jdun28,
Thank you for showing interest in contributing. I've assigned this issue to you.

**Comment by somangshu** [comment]
@ichik what call can we take here? 
If we are removing this prop all together, can we close the issue?

**Comment by ichik** [comment]
@somangshu should be fine. We have plenty of other emphasis tools available for styling.
