### ISSUE TITLE
[Docs] Need a page detailing how to send data across pages

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#941]
## Describe the problem

Appsmith support multi page applications but there is no documentation on how you can send data from one page to another using query params or using the storeValue function

**Comment by prakhargurunani** [comment]
Hey, @Nikhil-Nandagopal Can I work on this ?

**Comment by Nikhil-Nandagopal** [comment]
@prakhargurunani I've assigned the issue to you!
To quickly discuss the solution, I'm thinking  we can add a file under
https://github.com/appsmithorg/appsmith-docs/tree/v1.2/core-concepts/connecting-ui-and-logic
which talks about 2 sections 
- sharing data via query params
- sharing data via local storage

each section must have a gif associated with it demonstrating the method to share the data with the other page.
Hope this makes sense :)

**Comment by prakhargurunani** [comment]
@Nikhil-Nandagopal Can I get some reference about API for passing params....as I am new to the project.

**Comment by Nikhil-Nandagopal** [comment]
@prakhargurunani to pass params as a query parameter, you can trigger the navigateTo function and send query params to the second page. On the second page, you can refer to the query params as {{ appsmith.URL.queryParams.key }}
To use local storage you can use the storeValue function and access the value using {{ appsmith.store.key }}

**Comment by prakhargurunani** [comment]
@Nikhil-Nandagopal I tried a lot...but couldn't successfully retrieve stores query.

**Comment by Nikhil-Nandagopal** [comment]
Hi @prakhargurunani , can you post screenshots of how you were attempting to send/retrieve the data?

**Comment by deepakchethan** [comment]
@Nikhil-Nandagopal, If its open now, I can take this up

**Comment by Nikhil-Nandagopal** [comment]
@deepakchethan go for it!
