### ISSUE TITLE
[Bug]: Keyboard shortcut for copy does not work on code present under Snippets of Omnibar

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Ctrl+A on a snippet in Omnibar window causes all widgets on the canvas to be copied instead of code. So Ctrl+A and Ctrl+C when on Omnibar selects and copies all widgets

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b8e599dbee734e89a060bede237b2c44-00001.gif)](https://www.loom.com/share/b8e599dbee734e89a060bede237b2c44)

### Steps To Reproduce

1. Go to Omnibar --> Snippets
2. Click on the code window and press Ctrl+A. Observe all widgets on the canvas getting selected instead of code.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami cmd + a will only work on inputs. It doesn't generally work on a section of a display text so I don't think this is valid. Do share if you've seen this interaction somewhere else
