### ISSUE TITLE
[Enhancement]: Keyboard shortcut for entity explorer to be supported

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Entity explorer should support renaming via keyboard shortcut

### Why should this be worked on?

Provides easy navigation and supports existing behavior user may expect out of habit.

**Comment by Nikhil-Nandagopal** [comment]
Duplicate of #11134
