### ISSUE TITLE
[Bug]-[200]:Inconsistent keyboard shortcut for Edit mode

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Comment mode is invoked by pressing C Preview mode by P but Edit mode is V. This should be E to maintain consistency

![image](https://user-images.githubusercontent.com/79509062/143618819-b057b84f-7d3d-4823-8e41-171dfdf8661a.png)

### Steps To Reproduce

1. Hover over Edit mode and observe the tooltip suggestion for keyboard shortcut

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment]
I think this is a bug because of the preview mode. Is this on release? 
Also you've open a bunch of issues about keyboard shortcuts, is it possible to create one issue listing down all major keyboard shortcuts we should have? W

**Comment by ramsaptami** [comment]
Hey @areyabhishek , this is on production. Initially it probably made sense to have C and V as shortcuts for comment and edit since they were next to each other on the QWERTY layout but now with the Preview mode, it looks off so this needs to be aligned.

Also, I'd spoken to @somangshu about this a couple of months ago and he'd suggested raising all known issues/enhancements for now and then picking up all keyboard shortcuts as an epic in another quarter. All such issues can be found [here](https://github.com/appsmithorg/appsmith/labels/keyboard%20shortcut)

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 0.5 |

**Comment by kocharrahul7** [comment]
No longer a hotkey
