### ISSUE TITLE
[Bug]: Reset Currency doesn't work 

### ISSUE THREAD

**Issue by inaxium** [appsmithorg/appsmith#9417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currency fields are not reset.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/51343921/143780882-73181349-96aa-4d8e-bfea-c01f25f070f1.png)

![image](https://user-images.githubusercontent.com/51343921/143780890-1f86ae8f-3936-4db9-bbaa-775a1d6246eb.png)

I try also this:

```
export default {
	ada: () => {
		AddRevenueAmount.run(
			() => showAlert('Amount has been committed'), 
			() => showAlert('An error was detected'));
		resetWidget('RevenueForm', true);
	}
}
```

It doesn't work. After more Tests with Currency/Number Fields my feeling is
that there are more Problems.

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by sbalaji1192** [comment]
related to #8506

**Comment by Nikhil-Nandagopal** [comment]
@inaxium it seems to work for me. What is the value of the default text of the input you are setting?
Can you share the exact steps to reproduce this?

**Comment by inaxium** [comment]
The problem was, in fact, that there was no Default Text (Currency) => 0.
You should include it in the doc for numeric fields
a default must be given.

>

**Comment by Nikhil-Nandagopal** [comment]
@inaxium can you try with a new input widget? We used to have this issue in older widgets

**Comment by inaxium** [comment]
How can I achieve this. I use your Docker Image on my Local Notebook.
It should be the newest one. Isn't it?

Am Do., 2. Dez. 2021 um 05:34 Uhr schrieb Nikhil Nandagopal <
***@***.***>:

**Comment by Nikhil-Nandagopal** [comment]
@inaxium if you are running with docker-compose it should auto update. If not, you need to simply run a docker pull command. Post that, deleting and re-adding the input widget should solve this
