### ISSUE TITLE
Limit should be allowed depending upon edit or view mode 

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User wants something like this: 
select * ....
{{ if appsmith.mode == "EDIT") return "LIMIT XX;}} 

Reason: User have a dashboard page with multiple (7 or 8) queries that have hundreds or thousands of records. So edit mode with full query is too slow.

### Steps To Reproduce

https://discord.com/channels/725602949748752515/760761686549463060/913738123010273290

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@vivekverma2312 this is already possible.
