### ISSUE TITLE
[Bug]-[132]:Mouse pointer remains as clickIcon on the select widget dropdown icon when the select widget is disabled

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the select widget is disabled the mouse pointer remains as clickIcon on the select widget dropdown icon

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4be1441d984f42da8ec0707d0dcfdb8e-00001.gif)](https://www.loom.com/share/4be1441d984f42da8ec0707d0dcfdb8e)

### Steps To Reproduce

1.Launch Appmsith app in release/Prod Environment 
2.Drag and drop select widget 
3.Disable the select widget 
4.Mouse hover on the select widget dropdown icon and observe

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Reach from the number of users who have set disabled. 


## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 66 |
| Effort (months)  | 0.25 |

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/appsmithorg/appsmith/assets/94514895/c9aff226-5854-41a3-88af-ef6362bbab30
