### ISSUE TITLE
[Bug]: Declared variable is not read inside promises

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Variable declared inside a function is not read by the `.then` or .`catch` method. Throws an undefined error

### Success case
![image](https://user-images.githubusercontent.com/79509062/143830907-552a932e-e0be-4ff1-8564-280ee0ec8386.png)

### Fail case
![image](https://user-images.githubusercontent.com/79509062/143831852-cb2f7298-8e85-4883-81f5-9bc68ade87e7.png)

### Steps To Reproduce

1. Declare a variable inside a function and use this variable inside a promise. Observe the error

On DP, this query does not run and does not display any error either

### Environment

Release

### Version

Cloud

**Comment by pallavagarwal07** [comment]
@ramsaptami Why was this issue closed? I'm still running into this error.
Did you find a solution or workaround?

**Comment by ramsaptami** [comment]
Sorry about that @pallavagarwal07. I see there's an evaluation error that's regressed. Let me take this up with the team and back to you.
