### ISSUE TITLE
[Bug]: Undo on an idle app does not work

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Try undoing a step on query or canvas on a app that's been left idle for a couple of hours - the functionality is not supported

### Steps To Reproduce

1. Perform any action on canvas/query
2. Test out undo-redo.
3. Now leave the app in idle state for a couple of hours and come back to test out the undo-redo feature. Observe that the functionality is not supported.

### Environment

Deploy Preview

### Version

Cloud

**Comment by hiteshjoshi** [comment]
Closing this for now as we cant replicate.
