### ISSUE TITLE
[Bug]: Error on running CurrentItem and CurrentIndex at same time

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Query on `On click property`
{{
Query1.log(currentItem);
Query1.log(currentIndex)
}}

**Error:** Error occurred while evaluating trigger: ReferenceError: currentItem is not defined.

<img width="1347" alt="Screenshot 2021-11-29 at 6 55 02 PM" src="https://user-images.githubusercontent.com/83569920/143876028-f66bf5fe-a43f-4b63-a9f2-e784c6a8ffca.png">

### Steps To Reproduce

Discord link: https://discordapp.com/channels/725602949748752515/760761686549463060/914857556097241089

### Environment

Production

### Version

Cloud

**Comment by jauniuseitmantis** [comment]
Hi, this seems to be issue not only with button. The same happens with input field if one tries to use currentItem or currentIndex in validation fields (regex, Valid, Error message). I suppose it is also a broader problem with more widgets when they are used in list

**Comment by ohansFavour** [comment]
This should be fixed in [this pr](https://github.com/appsmithorg/appsmith/pull/10338)

**Comment by kamal0808** [comment]
Is this fixed? I am experiencing this issue right now. Here's a public URL to the app. Try clicking on the plus icon.
https://app.appsmith.com/app/my-first-application/page1-62bb875020ae3225cef3448d
