### ISSUE TITLE
[Bug]-[1056]:Console shows error for widget binding when JS code is turned off

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Binding path not found error is displayed when Radio Group widget's options are defined by JS and then this binding is deleted by turning off JS option on the field, then a console error is displayed for binding path.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b42726dd70a2477a8e25a05397af8aa2-00001.gif)](https://www.loom.com/share/b42726dd70a2477a8e25a05397af8aa2)

![image](https://user-images.githubusercontent.com/79509062/143893196-221db404-a99b-43a2-821b-b6b0dc4225e8.png)

### Steps To Reproduce

1. On a radio group widget, insert a JS code for Options field of Property Pane
2. Toggle the JS button so the code is cleared. Now observe the error on browser console as seen in the screenshot

### Environment

Release

### Version

Cloud

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 132 |
| Effort (months)  | 0.25 |

We can relook at the effort for this. Dropping a rough estimate for now.

**Comment by riodeuno** [comment]
@vuiets @ramsaptami This should not be an issue today. #10803 or #12253 should have resolved this. 
I cannot replicate this.

**Comment by ramsaptami** [comment]
Tested this on latest release and this isn't a bug anymore. Hence closing this issue.
