### ISSUE TITLE
[Bug]  [Low]APIs should work without specifying https / http

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#944]
When we integrate a REST API in an Appsmith application, we should be able to hit the endpoint even if there's no http/https appended by the user to the URL. 

By default the Appsmith proxy should initiate requests over `http` for such API invocations.

**Comment by spielers** [comment]
Hey @Nikhil-Nandagopal  you can assign me this.

**Comment by mohanarpit** [comment]
@spielers It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, check out the [Appsmith Challenge](https://github.com/appsmithorg/appsmith/discussions/863) where you can win some cool swag by inviting your friends to contribute to this project as well.

**Comment by mohanarpit** [comment]
For this issue, you'll have to make modifications to the `RestApiPlugin` in the `appsmith-plugins` maven module. Tag me in a comment incase you are stuck or need any clarifications.

**Comment by karmanya007** [comment]
Is this bug being actively worked upon?

**Comment by satbir121** [comment]
@spielers Any updates?

**Comment by spielers** [comment]
Yeah work in progress shortly I'll make a PR

Thanks

**Comment by jrcamelo** [comment]
I am sorry @spielers, finished working on it right when you commented.
@mohanarpit only mentioned RestApiPlugin, but RapidApiPlugin had similar code, so I believe it might also be necessary there.
Are the changes in #1266 acceptable?

**Comment by prapullac** [comment]
Verified the issue and works as expected
