### ISSUE TITLE
[Bug]: Spaces are not allowed on widgets children names (tabs, menus, buttons etc.)

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User cannot use space in tab widget naming. Space can only be included as an afterthought.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9485d1bd690b4c9f99855fffd57fdd45-00001.gif)](https://www.loom.com/share/9485d1bd690b4c9f99855fffd57fdd45)

### Steps To Reproduce

1. Go to tab widget and try to name it First Tab. Since space isn't allowed, type FirstTab and then try to add in a space after typing out the entire name and observe that this is possible.

### Environment

Release

### Version

Cloud

**Comment by jsartisan** [comment]
+1 for this issue. I find not having this very annoying.

cc: @somangshu

**Comment by somangshu** [comment]
This would be a technical challenge, If we have an underlying mapping on the widget name, There might be an issue with predicting what the widget name should be in autocomplete from the user POV. Something similar faced in the table widget v2.

cc @riodeuno @sbalaji1192

**Comment by somangshu** [comment]
also @ramsaptami this issue is not specific to the tabs widget, Its more of a generic challenge across widgets

**Comment by ramsaptami** [comment]
That's true @somangshu . Seen this on table widget too

**Comment by riodeuno** [comment]
It will help if we can compile the parts of the application where we find this issue; solve for all the scenarios at once using the same underlying function.

We have it in the PRD for table widget v2 to handle this correctly for the column names, I believe we can do the same for the tab names -- These are not entity names, nor are paths in the dependency lists, at the moment, so spaces should be easily added.

**Comment by dilippitchika** [comment]
@riodeuno this is something which is quite annoying, if we can also pick it up with table v2 it would help.

@somangshu then as per the above comment, if we decide to go ahead and address it in table v2 can i change the name of the bug and add it in Table widget v2 issues epic?

**Comment by riodeuno** [comment]
It is quite annoying. I am actually suggesting that we pick this up before or in parallel table widget v2. As this is more of a global change that effects multiple aspects of the application and is a low hanging fruit.
