### ISSUE TITLE
[Feature]: Documentation on internal working of Appsmith for Appsmith developers

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#9452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A high level document explaining the internal working of Appsmith and some concepts specific to it.
This should help user predict what could have gone wrong when they have a problem.

Here is a short list of things we should cover, there could be more.

- Evaluations
- Action execution
- Scope of the bindings
- An example of how Api1.data comes to the widget, and example of Input1.value is shown

Examples:

- https://reactjs.org/docs/reconciliation.html

Keep the document as short as possible with links to detailed information.

### Why should this be worked on?

Some support questions could be avoided if users knew how things come together.

**Comment by Rishabhkaul** [comment]
@jnikhila Not sure if marketing is the right team for this. I mean we theoretically could, but possibly best to have some experienced engineer who is familiar with the codebase to do this. Marketing can ofcourse review this. Also just tagging @mohanarpit incase you think this is even relevant.

**Comment by jnikhila** [comment]
@Rishabhkaul - It was assigned so that the DevRel team can create a Tutorial/blog post around that to help users. If needed, we can discuss and finalize. CC: @danciaclara - FYI to take this ahead.
