### ISSUE TITLE
[Bug]: Client does not send back default values when creating a new query out of templates for UQI based plugins.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Isolating the issue mentioned in the 1st pt in #8944 :
```
Currently the template (for commands chosen from db structure pane) is rendered correctly but the default value for command UQI attribute is not picked up by the client. Update: It seems the client is missing other attributes too when sending back the actionConfiguration object to the API server to create a new action.
```

### Steps To Reproduce

1. Send back db structure templates from API server such that the templates do not assign values for those fields that have default values assigned in the UQI editor json form. 
2. Create a query out of one such db template. Check out the `formData` values sent back by the client to create the query. It can be seen that the default values which are rendered on the UI are not sent back in the `formData` to the API server.

### Environment

Production

### Version

Cloud

**Comment by prapullac** [comment]
related to UQI

**Comment by prapullac** [comment]
Verified as a part of UQi and regression
