### ISSUE TITLE
[Bug] Autocomplete doesn't respond to mouse changes

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#946]
## Steps
1. Drag a button onto the screen
2. Open the property pane
3. In the label field open {{ }}
4. The auto-complete will open
5. Pressing down arrow shows a selection on the auto-complete
6. Hovering the mouse does not show the selection

**Comment by ankitpal1029** [comment]
Hey Can i work on this? I am new to open source and hope to learn a lot while i'm working on this

**Comment by ThakurKarthik** [comment]
@hetunandu I want to work on this
