### ISSUE TITLE
[Bug]: Importing specific internal app after forking it fails to launch or edit in release

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Internal app [GitHub Manager](https://app.appsmith.com/applications/60d72903ee9aa1792c5bf168/pages/614d9b9e18a27e5288afa99d) fails to launch or edit after forking it from `app.appsmith.com`, export and then import on release. 

The app opens up edit and launch modes on prod but with a lot of delay.

https://app.appsmith.com/applications/60d72903ee9aa1792c5bf168/pages/614d9b9e18a27e5288afa99d

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/871acfc8397f46e59daf1fcf752d8bab-00001.gif)](https://www.loom.com/share/871acfc8397f46e59daf1fcf752d8bab)
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/80d8806c8de5459bb5a7fe079139d295-00001.gif)](https://www.loom.com/share/80d8806c8de5459bb5a7fe079139d295)

### Steps To Reproduce

1. Fork GitHub Manager app on `app.appsmith.com` and observe the `500: internal server error` as seen in the video and refresh page to see the app displayed in selected personal folder as expected despite error displayed
2. Export this app 
3. Import this app on `release.appsmith.com` 
4. Click on Edit or Launch on app card observe the app behaviour (on release)
5. Repeat step 4 on prod and observe that the app loads

### Environment

Release

### Version

Cloud

**Comment by nidhi-nair** [comment]
Abhijeet's changes have fixed this.
