### ISSUE TITLE
Form data submission of date field not working with postgresql .

### ISSUE THREAD

**Issue by ginjojohny** [appsmithorg/appsmith#9462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Form data submission of date field not working with postgresql  in  YYYY-MM-DD format .  The selected date is not updated in database.

### Steps To Reproduce

Created  a  form with date filed and other input fields .
Inserted form data to postgresql  using insert query.
All form data updated in database except date column.
Tried with both date and timestamp datatypes in postgresql  table .

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny can you share the sql query that you have written that is not working?
Can you also share a screenshot of the evaluated value?

**Comment by ginjojohny** [comment]
Hi,

This is my update query  :

UPDATE customer
SET  client_name = '{{nameInput.text}}',
ppa = '{{PPAInput.text}}',
terminated_client = '{{terminateInput.selectedOptionValue}}',
term_date = {{dateInput.selectedDate}}
WHERE id = {{customer_list.selectedRow.id}};

and also sharing screenshot of date field.


Thank you,
Ginjo Johny

________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny dateInput.selectedDate will be an ISODate format which may be the reason you are seeing an error. If your date picker is in YYYY-MM-DD, you can use {{dateInput.formattedDate}} or you can format the date using moment.js as
{{moment(dateInput.selectedDate).format("YYYY-MM-DD")}}

**Comment by ginjojohny** [comment]
Hi,

Error showing in query as ERROR: column "term_date" is of type date but expression is of type character varying Hint: You will need to rewrite or cast the expression. Position: 109 .

Regards

Ginjo Johny
________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny can you try turning prepared statements off while running this query?

**Comment by ginjojohny** [comment]
Hi,

After removing prepared statement syntax error is showing like this

ERROR: syntax error at or near "," Position: 120

Query  :


UPDATE customer
SET client_id = {{idInput.text}},
client_name = '{{nameInput.text}}',
ppa = '{{PPAInput.text}}',
terminated_client = '{{terminateInput.selectedOptionValue}}',
term_date  =  {{dateInput.formattedDate}},
bench_mark = '{{benchInput.selectedOptionValue}}'
WHERE id = {{customer_list.selectedRow.id}};


Thanks,
Ginjo  Johny


________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny can you try wrapping {{dateInput.formattedDate}} in quotes as '{{dateInput.formattedDate}}'

**Comment by ginjojohny** [comment]
Hi,

I alreday tried with that also  but showing error like this

ERROR: invalid input syntax for type date: "" Position: 118


Thank you
Ginjo Johny
________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny can you please share a screenshot of the evaluated value of the query?

**Comment by ginjojohny** [comment]
Hi

[cid:753698e3-0bff-499f-a026-38db5d4601fe]




Thank You

Ginjo  Johny
________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny I cannot see the image. You need to share it directly on github. The image via email isn't showing for me

**Comment by ginjojohny** [comment]
________________________________

**Comment by ginjojohny** [comment]
Hi,


PFA

Thank You


Ginjo Johny
________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny I'm still unable to see it. Can you directly invite support@appsmith.com to your application?

**Comment by ginjojohny** [comment]
Hi,


This is the evaluated  value

UPDATE customer_details SET client_id = undefined, client_name = 'undefined', ppa = 'undefined', terminated_client = '{{(()=>{const index = _.findIndex(terminateInput.options, { value: terminateInput.defaultValue }); return terminateInput.options[index]?.value; })()}}', term_date  =  '{{ dateInput.value ? moment(dateInput.value).format(dateInput.dateFormat) : "" }}', bench_mark = '{{(()=>{const index = _.findIndex(benchInput.options, { value: benchInput.defaultValue }); return benchInput.options[index]?.value; })()}}', pbm_name = 'undefined', tier_value = undefined, web_portal_use ='undefined', demo_use = 'undefined', pbm_restriction_notes = 'undefined', notes_on_restrictions = 'undefined' WHERE id = undefined;


Thanks
Ginjo Johny
________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny is it possible to get access to your application to debug this? The evaluated value seems incorrect here

**Comment by ginjojohny** [comment]
Hi,

It is not possible  to give access to the application since it is in my local  machine .  If you can support in other ways it will be helpfull

Thanks,
Ginjo Johny

________________________________

**Comment by ginjojohny** [comment]
Hi,



I have sent  you the evaluated value before running the query.


The Evaluated value after running the query is like this :


UPDATE customer_details
SET client_id = $1,
client_name = $2,
ppa = $3,
terminated_client       = $4,
term_date  =  $5,
bench_mark = $6,
pbm_name = $7,
tier_value = $8,
web_portal_use =$9,
demo_use        =       $10,
pbm_restriction_notes = $11,
notes_on_restrictions = $12
WHERE id = $13;




Thanks,
Ginjo Johny

________________________________

**Comment by ginjojohny** [comment]
Hi,


This is the evaluated value after  disbabled the prepared statement.


UPDATE customer_details
SET client_id = 12,
client_name = 'zxv',
ppa = '',
terminated_client       = undefined,
term_date  =  '',
bench_mark = undefined,
pbm_name = '',
tier_value = NaN,
web_portal_use ='',
demo_use        =       '',
pbm_restriction_notes = '',
notes_on_restrictions = ''
WHERE id = 6;



Thanks,
Ginjo Johny
________________________________

**Comment by ginjojohny** [comment]
Hi,


I  am   invited  you to access my application  in cloud instance and the same date issue is there  .

Link is   https://app.appsmith.com/applications/61a9c39ab0a13b21f85249f0/pages/61a9c39ab0a13b21f85249f6


please check it out


Thank you

Gino Johny

________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny this has been solved. The dob was of a timestamp format and needed to be formatted & typecasted

**Comment by ginjojohny** [comment]
Hi,

I  cant  see my app now. showing resource not found error



________________________________

**Comment by Nikhil-Nandagopal** [comment]
@ginjojohny can you check that you are logged in with the correct email id?

**Comment by ginjojohny** [comment]
logged in success .  But I cannot insert the date field . There is no errors while executing the query but value of dob not inserted  to database.

**Comment by ginjojohny** [comment]
In local  I can insert the date with format YYYY-MM-DD  and  datatype as date in postgresql date field .  But  I cannot  update the  form if  date field is null . Also timestamp datatype is not working .

**Comment by Constantine9527** [comment]
hi,@Nikhil-Nandagopal.I have a problem with the widget of DatePicker.

Current Behavior:
Form data submission of date field not working with postgresql in YYYY-MM-DD format . 
App sample in appsmith cloud: https://app.appsmith.com/app/testtablepage/page2-62fdddfe84757e0c05552c65

I have a DatePicker widget and format is YYYY-MM-DD, but when I insert into database, the value of {{DatePicker.formatedDate}} becomes "YYYY-MM-DD +00",  Does "+00" mean time zone? How can I remove it ?
