### ISSUE TITLE
[Feature]: Conditional on page load execution

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user on discord requested this feature. They wanted some way to provide a boolean condition via Javascript which would decide if the action could be executed on page load or not. In this case they wanted the query to execute on page load based on a certain URL parameter being present or not. 
```
Sorry I have not been able to understand the ask completely. Please help me fill the gaps: (1) A db query needs to run on page load based on whether a query param is present or not - ie.. if the query param is absent it should not run ? (2) Another (db ? ) query needs to run always when the 1st query runs ? 

Yes @Sumit this is exactly what i am trying to achieve

```

### Why should this be worked on?

Allows us to create more complex applications.

**Comment by rohan-arthur** [comment]
Can we specify the problem statement more clearly? The proposed solution sounds like surfacing a new event like "OnPageLoad", but what kind of use-cases will be addressed by this?
Happy to speak to the user on discord to understand this better.

**Comment by sumitsum** [comment]
@rohan-arthur this could be related: https://github.com/appsmithorg/appsmith/issues/9556

**Comment by ajinkyakulkarni** [comment]
This could be achieved with #9130 , #9131

**Comment by nidhi-nair** [comment]
I think we've achieved this with JS editor as @ajinkyakulkarni mentioned. Closing the issue for this reason.
