### ISSUE TITLE
[Bug]-[2500]:For function validation type the custom validation function does not work on the page reload on input widget

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#9468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I make us of the custom validation function on `Label Font Style` property of the input widget, and if an error is generated on that property then on page reload the error does not persists. I have observed the similar issue on the button widget's `button variant` property. 

For better understanding of the issue, please find the below attached video for the reference:

https://user-images.githubusercontent.com/14138515/144033889-939375b5-a01a-41f0-9316-a9d8a6c9002f.mp4

### Steps To Reproduce

1. Drag an drop the button widget to the canvas.
2. Enable the JS mode for the `Button Variant` Property.
3. Purposefully generate an error. 
4. Now refresh the page.
5. The error message no longer appears on the widget.

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Applicable to all fields with JS input option. @somangshu is this something we pick up or for FE coders or UI Builders pod?

![Screenshot 2021-12-24 at 11 36 46 AM](https://user-images.githubusercontent.com/19730984/147323139-78ede2de-62f4-4db6-ab32-bbde6e2d54ff.png)

**Comment by somangshu** [comment]
I would say this should go to the FE coders pod because the evaluations missed something on reload, They Might be able to tell us better what happened under the hood

**Comment by ajinkyakulkarni** [comment]
@eco-monk can you do a RCA on this one?

**Comment by rohan-arthur** [comment]
WIDGET_PROPERTY_UPDATE, updatedValue contains "{{"
6m usage: 5000
Applying 50% requirement, 2500
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2500 |
| Effort (months)  | 0.25 |

**Comment by rohan-arthur** [comment]
not reproducible anymore
