### ISSUE TITLE
[Feature]: List widget to have scroll instead of pagination

### ISSUE THREAD

**Issue by jauniuseitmantis** [appsmithorg/appsmith#9474]
### Summary

List widget now has pagination. I wish list widget had possibility to scroll instead

### Why should this be worked on?

It would improve quite a lot of use cases since user experience is much better with list when one can scroll through it instead of clicking on page buttons.

**Comment by Nikhil-Nandagopal** [comment]
Hi @jauniuseitmantis thank you for the feature request. We have this issue tracked here #6293
Do watch the issue for updates!
