### ISSUE TITLE
[Bug]: UI for page properties are not proper

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/06a9a9cbfb33469db7977cf158ce1343-00001.gif)](https://www.loom.com/share/06a9a9cbfb33469db7977cf158ce1343)

The pages on page properties are not in grey shade. The whole page looks white with just text and buttons on it.

### Steps To Reproduce

Open an application and click on setting icon beside page.

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
Mostly fixed after design system updates on the entity explorer
