### ISSUE TITLE
[Bug]: Validation error occurs for the first time when the JS of button variant is enabled for table icon type 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the validation error "This value does not evaluate to type string ( PRIMARY | SECONDARY | TERTIARY )" occurs for the first time when the user enables JS of button variant for table widget icon column type 

https://loom.com/share/ea8e375ba79140d9a58b20d90e61ce7d

### Steps To Reproduce

1.Launch Appmsith app in release environment 
2.Drag and drop table widget 
3.Click on setting icon on any of the column and change it to Icon type
4.Enable the JS of button variant and observe

### Environment

Release

### Version

Cloud

**Comment by aswathkk** [comment]
This is related to #8712

**Comment by dilippitchika** [comment]
@YogeshJayaseelan can you check if this is fixed now? This issue was merged to release based on #8712.

**Comment by YogeshJayaseelan** [comment]
@dilippitchika Verified this and no validation error occurs now

**Comment by dilippitchika** [comment]
@somangshu can we close this? This is marked as done from Yogesh.

**Comment by jsartisan** [comment]
Closing it as it is not happening anymore.
