### ISSUE TITLE
[Feature]: Provide smarter best match suggestions on autocomplete

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#9480]
Sometimes, the autocomplete results are too long and confusing. The list is flooded with system methods and properties that are sometimes not relevant. 

Autocomplete should suggest smarter results based on the context of usage. This includes taking the return type of a property into account.

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you add more details to this issue?

**Comment by hetunandu** [comment]
If we can determine the return value of a JS function, we can use our best match to suggest JS functions on widget properties. For example if we know a JS function returns an array of objects, we can show it in the best match of table data

**Comment by Rishabh-Rathod** [comment]
> If we can determine the return value of a JS function, we can use our best match to suggest JS functions on widget properties. For example if we know a JS function returns an array of objects, we can show it in the best match of table data

There could be a possibility of a function returning different type of data according to condition?  
Just to clarify do we want to show autocomplete best match suggestion according to the last ran data type of JS Function? @hetunandu

**Comment by hetunandu** [comment]
@Rishabh-Rathod, while this is possible, it is a rare case. Mostly the data type would be the same in most cases and that is all we need to predict the best match.

**Comment by bharath31** [comment]
closing this in favour of #17684
