### ISSUE TITLE
[Bug]-[10]:Icon is not displayed in the right alignment when the input type is number or password

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that icon is not displayed when right alignment is selected for input type number or password 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4593d1ac2a874da085bbe829edc8c3d0-00001.gif)](https://www.loom.com/share/4593d1ac2a874da085bbe829edc8c3d0)

### Steps To Reproduce

1.Launch Appmsith app in release/Prod Environment 
2.Drag and drop input widget 
3.Choose type as Number or password 
4.Choose any of the icon 
5.Click on right alignment and observe

### Environment

Production

### Version

Cloud

**Comment by sbalaji1192** [comment]
related to https://github.com/appsmithorg/appsmith/issues/8506

**Comment by dilippitchika** [comment]
Hide the icon alignment option in property pane for password type inputs. By default it should be right aligned and the developer should not be able to change it. 

Reach : Assuming 5% users who configure password also configure icons

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 10 |
| Effort (months)  | 0.5 |

**Comment by somangshu** [comment]
Issue is not reproducible. Closing as its resolved
