### ISSUE TITLE
[Bug]: Organization names allowed to be duplicate

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently more than 1 organization can have the same name

![image](https://user-images.githubusercontent.com/92293815/144193131-d32196af-35d7-4a64-9c8e-06a46dfe7438.png)

**Expected behavior:** Organization names must be unique

### Steps To Reproduce

Login and in home page rename more than 1 organization to the same name

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Orgs can be duplicate
