### ISSUE TITLE
[Bug]: App color changes with every page refresh

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user forks an application from one organization to other, with every page refresh the app color changes in home page 

NOTE: Observed only with this particular application as seen in the video.

https://loom.com/share/5a63f3aa396e4c01a1705829685097b4

**_New issue observed on 15/12/2021_**
**For every new user after the Welcome tour the user is prompted with 'Next mission' & 'Back Home' when clicked on back home user can see 'My first application' the app color changes with every refresh.**

**https://loom.com/share/65f9fb1385b64ceca0a45233a702ff4b**

**Expected behavior: The app color must remain the same as its origin organization.**

### Steps To Reproduce

1. In home page select an application from an organization and Fork it to a different organization
2. Observer the app color changes with every page refresh

### Environment

Production

### Version

Cloud

**Comment by nayan-rafiq** [comment]
@albinAppsmith If I randomly pick a color from available colors and assign that when creating an application - will that solve the problem?

**Comment by nayan-rafiq** [comment]
Old applications which do not have a color set will still change color on page refresh. To fix this, we need an expensive DB migration which I think is not necessary. If user feels it's annoying, they have the option to set a color.
