### ISSUE TITLE
[Bug]: Opening URL of a deleted Google Sheets action shows a faux blank UI

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#9485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening the URL of a Google Sheets query that's already deleted, we expect to see a "not-found" or 404 kinda page. Instead we see a blank query form. This is very misleading.

### Steps To Reproduce

1. Connect to Google Sheets and create a new query to perform some operation on a Google Sheet.
2. Now open the URL for this sheet in a new tab.
3. Delete this action in tab 1.
4. Go to tab 2 and refresh to see the problem.

Video demonstrating the problem:

https://user-images.githubusercontent.com/120119/144195506-7c8df7c9-36bc-44e7-a459-19a241fdd545.mov

### Environment

Production

### Version

Cloud

**Comment by prapullac** [comment]
On refresh a message is displayed stating  "Invalid URL : The page you’re looking for either does not exist, or cannot be found" along with a "GO back" button clicking on this button the user is lead to Datasource page 
Hence closing the issue
