### ISSUE TITLE
[Bug]: Opening Audio widget property pane is not smoother when passing invalid audio url 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by passing any invalid audio url and opening property pane is difficult. It is observed that only by mousing hovering from left or right side of the widget and click on the audio widget name the property pane opens. If the user mouse hovers from top to bottom of the widget and clicking on the widget doest selects the widget.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f994645c5d094e1e95d00d829a397796-00001.gif)](https://www.loom.com/share/f994645c5d094e1e95d00d829a397796)

### Steps To Reproduce

1.Launch appmsith app in release/Prod environment 
2.Drag and drop audio widget 
3.Pass the following invalid url - http://searchgurbani.com/audio/sggs/1.mp3
4.Try to mouse hover on the widget from top to bottom and try to click on the widget and open property pane 
5.Also, try mouse hovering from left and right side of the widget and observe user will be able to select the widget 

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/appsmithorg/appsmith/assets/94514895/bfebe182-16e1-4609-af70-a005b440d074
