### ISSUE TITLE
[Bug] File upload is not putting picker in loading state

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#949]
## Steps to Reproduce
1. Drag a file picker
2. Create an API
3. Bind the onFileSelected to the API
4. Pick a file
5. The File picker does not go into loading state

**Comment by ng29** [comment]
Hey @Nikhil-Nandagopal / @prapullac 
Can i get path of the file so that can start working on this ? ?

Cheers

**Comment by Nikhil-Nandagopal** [comment]
@ng29 I've assigned this to you. @hetunandu will help you with the problematic files

**Comment by ng29** [comment]
> @ng29 I've assigned this to you. @hetunandu will help you with the problematic files

Thanks @Nikhil-Nandagopal , @hetunandu  could you please share the problematic files so that i can start analysis.

**Comment by hetunandu** [comment]
Hey @ng29! The widget file is here

`app/client/src/widgets/FilePickerWidget.tsx`

You should also look at Button widget and see how the loading is implemented as it should be similar for filepicker as well

**Comment by ng29** [comment]
> Hey @ng29! The widget file is here
> 
> `app/client/src/widgets/FilePickerWidget.tsx`
> 
> You should also look at Button widget and see how the loading is implemented as it should be similar for filepicker as well

I have made a draft pr to fix this bug as per my understanding, kindly review and merge if no changes required. 
Cheers
