### ISSUE TITLE
[Bug]-[100]:Global hotkeys list pop-up contains repeating elements making the list look unorganized

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pressing `?` opens up `Global Hotkey` list as a pop-up and this list contains repeating elements that makes the the list unorganized. Some repeating elements need to be renamed since their function is different from what's defined, for e.g. shortcuts for searching snippets, documentation are all described as Omnibar search. Duplicate entry for preview mode etc...

![image](https://user-images.githubusercontent.com/79509062/144205758-54ec007a-f7ef-4b80-91b9-d45202dacc33.png)

![image](https://user-images.githubusercontent.com/79509062/144205673-91157228-7027-440d-9f3c-92955074bd1b.png)

### Steps To Reproduce

1. Go to canvas and press `?` or `Shift+?` to open up Global Hotkey pop-up - observe the list and repeating descriptions of elements

### Environment

Production

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 0.75 |

**Comment by kocharrahul7** [comment]
No longer replicable, This seems to be handled

**Comment by ramsaptami** [comment]
Repetitive actions are still present.

![image](https://user-images.githubusercontent.com/79509062/165353192-2bb31496-2efb-4756-be48-cdb839bf71c9.png)
![image](https://user-images.githubusercontent.com/79509062/165353285-26c828fa-2c56-42f3-b382-c88fe57f7f0f.png)
