### ISSUE TITLE
[Bug]-[24000]:Datasource query needs seamless blending of elements on it's corners

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Datasource query page does not have seamless corners and edges that blend into the next block. They currently appear to be separate entities that are placed next to each other.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b2031fc2a4d240958137d3309c820372-00001.gif)](https://www.loom.com/share/b2031fc2a4d240958137d3309c820372)

### Steps To Reproduce

1. Go to datasource query page and run a query so that all possible elements are present on screen. Zoom into areas where different blocks meet and observe the boundaries not seamlessly blending into the next

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.25 |

**Comment by parth-appsmith** [comment]
@AmanAgarwal041 we have collated all the latest designs for API/Query and JS editor screens in this figma file. 
You can use these are reference. 

https://www.figma.com/file/IfutQTUq3g97j59i3mx6Y4/?node-id=4%3A4
