### ISSUE TITLE
[Feature]: Need a dashboard to monitor the health of everything in the fat container

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Requested by user on Discord. Also seems like a very useful feature in general. 
```
Hello. Does appsmith has any endpoint url to check the service status with status codes etc?
Not the apps status. Appsmith whole service
```

### Why should this be worked on?

Allows users to monitor Appsmith service.

**Comment by sharat87** [comment]
Closing this since we now have supervisor at `/supervisor` for this purpose.
