### ISSUE TITLE
[Bug]: Incorrect Page load execution

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#9501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Query1 depends on Query2, Query2 is not run before Query1 on page load. 

### Steps To Reproduce

 A user reported this issue on intercom
https://app.appsmith.com/applications/619c86ded3208212f819ce08/pages/619c86ded3208212f819ce0f/edit/api/619f3b88f6f14050cbd7d103

### Environment

Production

### Version

Cloud

**Comment by yan-hic** [comment]
I wonder if this should not be reopened to include JS functions e.g. I have a function that process data from 2 APIs, and that function (filtered, merged data) is the source of a Table.
I like to specify that Api1 and Api2 are run first before the function, all at page load.

Currently, these settings are in different places: settings of each Query + setting of JS Objects where one can select the function to run a page load.
Ideally, you have all queries and JS functions (from all JS objects) in one page, and you can set the execution order.

**Comment by Nikhil-Nandagopal** [comment]
@yan-hic the order of execution is automatically handled by the platform. So if your function is reading data from API1 and API2, they will automatically be run on page load before the function.
If you need control over them, you can create a new function and manually run the APIs on page load and simply mark the function to run on Page Load
```
fetchData: async () => {
   API1.run();
   API2.run();
}
```

**Comment by yan-hic** [comment]
@Nikhil-Nandagopal fair enough, I agree this can be done programmatically but it can become complex if one needs to consider all interactions and change dependencies in JS code. I maintain that one place to simply control the order of execution of all Page Load objects is useful, and in line with no-code spirit. 
Just my 2 cents, no need to re-open anything.
