### ISSUE TITLE
[Enhanement]: Support Data URI in Iframe widget

### ISSUE THREAD

**Issue by tejzpr** [appsmithorg/appsmith#9510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I pass a Data URI to the iframe widget as specified in https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs I get a URI validation error
```...```
What I expect is that the Iframe widget should accept the data URL & render the contents of the Data URI for e.g. a Base 64 Encoded image

### Steps To Reproduce

1. Add a Iframe widget
2. Pass a data URI to the URL field

### Environment

Production

### Version

Self-Hosted

**Comment by mohanarpit** [comment]
In this particular case, why not use the image widget to display the base64 encoded data? Can I ask why you wish to use the iFrame widget?

**Comment by Nikhil-Nandagopal** [comment]
@tejzpr agreed on this since the native HTML iframe supports this but as Arpit mentioned, you can use an image widget to achieve this today.

**Comment by tejzpr** [comment]
I was able to display an image using the image widget, but enabling data URI on Iframe would allow display other encoded file types such as a PDF file.

**Comment by dilippitchika** [comment]
@tejzpr we have added a document viewer widget which supports pdfs, word docs etc in base64 encoded formats. You can use that to display pdf files.

Closing this bug for now, for any other data type support in base64 encoding please let us know and we will create an enhancement on our document viewer widget.
