### ISSUE TITLE
[Feature]: Allow inviting users via API

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Requested on Discord:
```
Hello Appsmithians, is there any way to invite users to an organization using APIs?

The use case is that I am making a membership form, so when a new membership form is submitted I want to invite the user to the system.
```

### Why should this be worked on?

Provides a new way of inviting users to an Org.

**Comment by israrwz** [comment]
+1

**Comment by arjunsriva-woven** [comment]
+1

**Comment by 123om123** [comment]
I'd like to work on this issue. Please let me know if I can work on this.

**Comment by vuiets** [comment]
Another request around this today
> Is any way we could add user/ list users for ORGANIZATIONS by API or Query?

**Comment by kostyay** [comment]
+1

**Comment by saivikash1522** [comment]
Hi ,Is this feature available to invite the user to a workspace using API?

**Comment by Nikhil-Nandagopal** [comment]
@saivikash1522 we're tracking this here #24841
