### ISSUE TITLE
[Bug]: Using external MongoDB will still try to connect and configure local MongoDB

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#9513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a fat container is configured with an external MongoDB URI, the entrypoint script should not try to connect and initialize a local MongoDB Replica Set. Instead, it should connect to this external MongoDB, check that it's a replica set already, and if not, do an `rs.initiate()` on it.

User report: https://discord.com/channels/725602949748752515/760761686549463060/915781460810666095

### Steps To Reproduce

Start  fat container with a `docker.env` containing a MongoDB URI pointing to a locally running MongoDB server. The fat container's entrypoint will still try to initialize a separate MongoDB instance and have the server try to connect to this external MongoDB server.

### Environment

Production

### Version

Self-Hosted

**Comment by sum35h** [comment]
@sharat87  I've tested and verified this with appsmith/appsmith-ce:latest. The issue is resolved now.
