### ISSUE TITLE
[Feature]: UQI object level Raw mode and Form mode switcher

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#9529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

UQI feature to allow switching any component from form type to raw type.

### Why should this be worked on?

To allow users to have write complex functionalities in raw mode rather than waiting for appsmith team to implement them.

**Comment by Irongade** [comment]
Closing this issue, since it has already been handled as part of UQI.
