### ISSUE TITLE
[Feature]-[1250]:Rename organizations to workspaces

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#9537]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

We should rename Organizations to Workspaces in the Appsmith product. 

- [ ] UI changes across the board. 
- [ ] Modifications to error messages originating from the server to change the term
- [ ] Documentation changes to reflect this change.
- [ ] Lower priority: Change the API & DB collection name from organizations to workspaces. This is a large breaking change. This is not necessary to do at this juncture, but highly recommended. But it is required to ensure that we don't create additional tech debt for ourselves in the long run. If we do this right now before the Git sync feature launches, it'll ensure that we don't have to deal with the import-export flows. Hence, this is highly recommended before we add more features & users to the Appsmith community.

### Why should this be worked on?

Organizations are a slightly confusing terminology for users. Workspaces are more approachable & also reflect reality better.

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5000 |
| Effort (months)  | 0.5 |

**Comment by jnikhila** [comment]
@trishaanand - Could you please add a doc ticket for this work? I'll add it to the pipeline to pick it up in next sprint for estimation.

**Comment by sidhantgoel** [comment]
Since this change is big, we are planning to do it in three phases.
1. In phase 1 all the BE changes which does not impact FE.
2. In phase 2 remaining BE changes and only necessary changes in FE. (like url and field names in the API calls).
3. In phase 3 remaining FE changes

Pull request for phase 1 #13710
