### ISSUE TITLE
[Bug] Two datasource cant have same names

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#954]
## Steps to reproduce

1. Add a datasource
2. Name the datasource as "Silent" from the datasource page 
3. Add another datasource
4. Name the datasource as "Silent" from the entity explorer page 

and observe

## Observation

It is observed that the name of the datasource gets saved without any error for duplicate

## Expected behaviour

datasource name should be unique and error message must be displayed to user

![Screen_Shot_2020-09-21_at_5 30 20_PM](https://user-images.githubusercontent.com/458946/96956276-52a56680-1515-11eb-8668-ce815c9f2fe5.png)

**Comment by ng29** [comment]
hey @mohanarpit / @prapullac 

Some more info on this will be appreicated, so that i can start this.

**Comment by mohanarpit** [comment]
This is happening because the DB doesn't have a unique index for the name field in the collection. We should add a MongoDB migration in `DatabaseChangelog` class to add a unique index for datasource name & organizationId.

**Comment by mohanarpit** [comment]
@ng29 Would you be interested in taking this up?

**Comment by ng29** [comment]
> @ng29 Would you be interested in taking this up?

Not possible currently @mohanarpit , occupied with other tasks rn

**Comment by trdillon** [comment]
Does this issue still need work? If so I would be glad to take it on, however, the validation seems to be working and I see an index appears to have been created for this.
https://github.com/appsmithorg/appsmith/blob/4f79f1d0852f8d6055ea1a539bfcbec6390ddf52/app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java#L275-L277

**Comment by mohanarpit** [comment]
@trdillon You are right! This has been fixed. Unfortunately, the fix didn't get linked to this issue. Thanks for spotting this.
