### ISSUE TITLE
[Task]: Upgrade react-spring to the latest version

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#9545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

When animations take a long time to finish, they fall into an infinite loop.
This issue seems related
https://github.com/pmndrs/react-spring/issues/770
We are using a version from 2 years ago, didn't see the problem with the latest version of spring.

**Comment by areyabhishek** [comment]
@rahulramesha Quick question about this, will this be fixed?

**Comment by rahulramesha** [comment]
@areyabhishek, yes. We are aiming to push this with the reflow project.
