### ISSUE TITLE
[Docs]: `Setup Appsmith` section does not show up as suggestion on typing in `install` in the search bar

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

when I type in install in the search bar I cannot see the Setup Appsmih section show up in the suggestions:
![Screenshot 2021-12-03 at 12 27 45 PM](https://user-images.githubusercontent.com/1757421/144559560-3f6e0b9d-ff17-4b79-af78-01d918039ee2.png)
 

### Describe the improvement

`Setup Appsmith` section show show up as a suggestion when anyone types in `install` in the search bar.

**Comment by jnikhila** [comment]
Setup Appsmith shows up in the search results - though you have to drill down in search results.
