### ISSUE TITLE
[Feature]: New widget request : Trigger Widget

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Request by user on Discord: 
Provide a new widget called `Trigger Widget`. This widget should be invisible on the application, but would allow the users to define `events` and `actions` ie. the events should trigger the actions linked to the events. The events could be: user clicking on some widget, page refresh / load, change of value in `appsmith.store.xyz` attribute, user email matching some domain, user role matching some string, etc. This will allow more complex workflows to be created on Appsmith.  

```
IF I would do this I would do a new widget TRIGGER WIDGET
that normally is not visible but in my opinion any On change should be possible to fire regardless how the text or setting is changed
If you klick with your mouse on the widget, or if I as programmer "click" for you should be the same thing
we could also use this for cool functions. For example I want to show a picture for a certain time. I trigger the change programmatically and then my JS script takes over. Just by feeding a random number to a variable I will get the action to trigger because very likely the new random number will be different compared to the old text. Event fire and off we go again.....
I guess you get the idea
```

### Why should this be worked on?

Allows more complex workflows to be built on Appsmith.

**Comment by WSDsuperace** [comment]
This widget would not be visible on the application so no end-user would interact directly with it. 
The trigger widget (TW) could have different selectable functions for example:

Run: On trigger run event such as API, Query, JS and the normal range of the already super great options in Appsmith.

**The values in the examples below (true/false) can be any other values also. It's just very simple examples :)**

Monostable toggle: Default value (false) When the trigger condition is met "Do (true) for x time" then "Switch back to (false)".
Usage: Link an image widget's visibility to the value of the trigger and the picture will be visible nnn time and
then hidden again.

Bistable toggle: Default value (false) When the trigger condition is met "Do x (true) " and next time "Do y" (false) and then "x".....
Usage: Link an image widget's visibility to the value of the trigger and a button to the trigger and the picture will change from visible to hidden each time the button is pressed.

Delay: After x time unless triggered the event will fire.
Usage: For example, to control how quickly the onChange event will fire when typing in an Input widget. Link the Input
widget onChange->store.key.x   store.key.x linked to the trigger widget -> and if not triggered again inside the selected time it will fire the selected event. If triggered again a new time delay will start.

Interval:
Fire the selected event every x ms.
Run control using the linked appsmith.store value (true) and it will fire on interval and (false) it is stopped.

Yes, I am aware that all this is possible to write in pure JS but you can look at this as graphical JS snippets. For many users writing code is not something they either _think_ they cannot do or are not able to do. Functional widgets like this would in my mind help less skilled users to reach their goals in an easier way and makes it easy to expand APPs also. 

When doing this way to coding style Appsmith becomes more of a GUI that is controlled by JS logic in the background and
we can choose the most powerful and convenient style depending on the situation.

**Comment by Nikhil-Nandagopal** [comment]
Closing this because it goes against our product philosophy. Widgets by definition are a UI component and this should be achieved via reusable logic snippets
