### ISSUE TITLE
[Feature]: Add CLI option to deploy apps from JSON file

### ISSUE THREAD

**Issue by mwodka** [appsmithorg/appsmith#9559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

From a fresh instance of Appsmith in Docker, can you add a command line option to import apps from JSON?

### Why should this be worked on?

This will allow us to automate app deployment between different environments, using GIT to store the JSON.

**Comment by Nikhil-Nandagopal** [comment]
@mwodka we're working on an option to deploy applications using git here #3199 
I believe this should solve your use case
