### ISSUE TITLE
[Feature]: Include tooltip property for icon button

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#9563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to show a mouse-over tooltip on an icon button, and this property is not available today for the icon button widget.

### Why should this be worked on?

"text" button widget already has this property, which in my opinion is less necessary compared to a tooltip on an icon button. For the sake of consistency, it would be great to have tooltips on both.

**Comment by dilippitchika** [comment]
Makes sense, we should add the property for icon-buttons. Also hover is missing for icon buttons. So whenever, we decide to pick it up we can also add hover.

**Comment by dilippitchika** [comment]
Closing in favor of #13807
