### ISSUE TITLE
[Bug]: [Documentation] incomplete sentence in documentation

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#9564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/framework-reference/navigateto

### Describe the problem

incomplete sentence: “Create a new Page with a valid”
<img width="808" alt="Screenshot 2021-12-04 at 9 35 41 AM" src="https://user-images.githubusercontent.com/94514895/144696417-42f6e26b-5c25-4c20-b152-9d860949fcd3.png">

### Describe the improvement

this was probably a copy-paste error - complete the sentence :)

**Comment by kasarchou** [comment]
Hello @rohan-arthur this is my first time contributing to a project and i would love to fix this issue if it hasn't already been solved.

**Comment by Nikhil-Nandagopal** [comment]
@kasarchou sure go for it!

**Comment by rohan-arthur** [comment]
![Screenshot 2022-02-08 at 10 58 12](https://user-images.githubusercontent.com/94514895/152924036-cacd6578-42c5-4509-bb68-8d8f79328845.png)

still not fixed - reopening
