### ISSUE TITLE
[Bug]: App “forgets” widget names in design time, although the scripts work ok in runtime.

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#9566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am referring to another widget to compute the property of a widget, I can correctly see the widget names in auto-complete, and my script also runs without errors. However, if I then go somewhere else and come back to the script, the referred widget names are highlighted in error (it is a cosmetic issue, as the script actually continues to run despite the errors. See attached video.

Uploading Screen Recording 2021-12-04 at 8.53.14 PM.mov…

### Steps To Reproduce

1. create two input (or any) widgets, W1 and W2
2. go to the property pane of W2, and enter some JS in, say the visible property for it
3. in your script, make sure to refer to W1, e.g., (JS.text =! '0') or something like that
4. notice that you are able write the above condition with auto-complete, and there are no surprises
5. Now navigate away. Maybe open the property pane for W1 and then come back to the property pane for W2.
6. Notice now that "W1" is marked in red as an error. On hover, you see error: "W1 is not defined"

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
Related: #9676

**Comment by ohansFavour** [comment]
Fixed in [9773](https://github.com/appsmithorg/appsmith/pull/9773)
