### ISSUE TITLE
[Bug]-[160]:users cannot escape from binding mode if binding fails

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#9567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I am working with a query, there is a nice flow to directly bind a widget to a query response by clicking the "Connect Widget --> Select Widget" button. 
However, in case the binding fails, it looks like there is no way for the user to abort the operation, other than to click away in the entity explorer

Uploading Screen Recording 2021-12-04 at 9.04.56 PM.mov…

.

### Why should this be worked on?

not super important, but it takes care of one branch of the flow.

**Comment by kocharrahul7** [comment]
Hey @rohan-arthur  I was testing this out, and it seems that you can hit escape to leave binding mode. Do you feel that this solves the issue?

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 40 |
| Effort (months)  | 0.5|
