### ISSUE TITLE
[Feature]: Allow Postgres plugin to connect to AWS `RDS PostgreSQL` instance via `IAM` authentication

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Requested by user on Discord:
 Allow postgres plugin to connect to AWS `RDS PostgreSQL` instance via `IAM` authentication

### Why should this be worked on?

Allows connecting to AWS RDS PostgreSQL.

**Comment by dmelo** [comment]
AWS recommends connecting to RDS using IAM authentication. I believe this would dramatically increase security of AppSmith applications. Today, applications can be exported and, in doing so, the credentials to data sources (including databases) comes with it, plain.

**Comment by rohan-arthur** [comment]
these aws reference for context: 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html

**Comment by Nikhil-Nandagopal** [comment]
One more request for this feature

**Comment by StevenJPx2** [comment]
Please integrate this feature, it would be very useful for us!

**Comment by Nikhil-Nandagopal** [comment]
This is a duplicate of #8377 and we'll pick it up with that
