### ISSUE TITLE
[Feature]: Convert Appsmith application into a chrome extension

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Requested by Discord user:
```
It would be awesome if we can build a chrome extension with Appsmith 
I mean at least for the dashboard of the chrome extension and the popup
Kind of  turning the  web page  into a chrome extension
```

### Why should this be worked on?

Increases usability.

**Comment by bolshoytoster** [comment]
Would 'building for chrome' be available to anyone or just the creator?

I have some experience with chrome extensions so I could probably do this.

**Comment by tiger360** [comment]
> Would 'building for chrome' be available to anyone or just the creator?
> 
> I have some experience with chrome extensions so I could probably do this.

I want a way to build quickly chrome extensions to use for internal uses or to put on the marketplace.
Are you using vite+vuejs to build extension ?

**Comment by bolshoytoster** [comment]
>Are you using vite+vuejs to build extension ?

No, I can do it manually.
