### ISSUE TITLE
[Bug]: Going back to a page caches results from previous run

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#9572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Case 1**: Query which does not run on page load on Page1.

1. I goto page1, trigger the query.  Data is loaded
2. Now I goto page 2
3. Come back to Page1, I have the data without triggering the query.

This is not expected behaviour.

**Case 2**: Query which runs on page load

1. You have to click a button to go to page 2,  the button uses navigate to with params
2. First load is fine
3. When you come back to page 1 and goto page 2 with different params, data matching the first request is shown momentarily

### Steps To Reproduce

1. Create a page to show data from an API on button click.
2. Mark the api to not run on page load
3. Create another page
4. Goto page1->click the button->goto page 2->goto page 1

You will see data from previous API run though the api is not set to run on page load.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@SatishGandham I suggest we not solve this now since it was done on user request as a perceived performance improvement. Maybe this can be a setting in the future or we can tackle this if a user complains?

**Comment by dsakaria16** [comment]
@Nikhil-Nandagopal @SatishGandham . 
I understand the priority. I am just a bit confused as in why other users have not complained. May be the approach I am following is different. If this is going to take time. Can I get to know a workaround wherein I can handle this ? Because I have 14 to 15 pages on my app and navigating between pages is going to be more than often. So if temporarily there is a workaround then please let me know. Thanks

**Comment by Nikhil-Nandagopal** [comment]
@dsakaria16 thanks for reaching out here. I now understand that with navigation params this becomes a big issue because the page is showing the older data for the wrong navigation param. Re-opening this

**Comment by dsakaria16** [comment]
@Nikhil-Nandagopal Thank you .

**Comment by dsakaria16** [comment]
@ajinkyakulkarni @rohan-arthur when do we expect this to get resolved?

**Comment by hetunandu** [comment]
Solution: Clear all action data when switching a page.

**Comment by rohan-arthur** [comment]
@dsakaria16 we will take this up in the next week, will update ETA here when we have more details.
