### ISSUE TITLE
[Bug]: The Get Started button is clickable in the disabled mode 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the new user performs sign up and the Get started button is disabled without selecting the dropdown options. But still the Get Started button is clickable in the disabled mode 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b9eb70750e3d49c79bdf73e9d512d06e-00001.gif)](https://www.loom.com/share/b9eb70750e3d49c79bdf73e9d512d06e)

### Steps To Reproduce

1.Launch appmsith app 
2.Click on Signup 
3.Enter email id and password 
4.mouse hover on the Get Started button and click on it and observe

### Environment

Production

### Version

Cloud

**Comment by sharat87** [comment]
Looks like we have this flow today, so closing.
