### ISSUE TITLE
[Bug]: The default country icon shown in the input widget for type currency and phone number are not selected in the property pane country code  field

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that by default the input widget shows $ icon for currency type and American flag for the phone number type in the widget but the country code field in the property pane shows - No selection by default. 

Expected Result:
Property pane - Country code field also should show the default country as selected option 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3c186e3aba43408f882a8452052f69b0-00001.gif)](https://www.loom.com/share/3c186e3aba43408f882a8452052f69b0)

### Steps To Reproduce

1.Launch the appmsith app in the release
2.Drag and drop input widget 
3.Change the input type to currency and phone number and observe the country code field in the property pane 

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
@sbalaji1192 can you link this to input v2 PR, we can auto-close this.

**Comment by vicky-primathon** [comment]
Setting the default country code will solve this error. We need to add default value of country code in property pane configurations.

**Comment by somangshu** [comment]
closing this as the feature is already covered in the new phone widget
