### ISSUE TITLE
[Feature]: Improve heading sizes

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#9581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Headings (h1, h2, h3) are very small and should be sized bigger, similar to other frameworks

### Why should this be worked on?

Appsmith's headings are sized:
- h1: 24px
- h2: 18px
- h3: 16px

That makes them appear very small on screen, also not very different from each other.

Compared to Bootstrap that has their headings sized:
- h1: 2.5rem/40px
- h2: 2rem/32px
- h3: 1.75rem/28px
- h4: 1.5rem/24px
- h5: 1.25rem/20px
- h6: 1rem/16px

**Visual comparison:**

Appsmith:
![appsmith](https://user-images.githubusercontent.com/5412178/144815148-9abf9830-5792-49d4-b6ed-922bb2d182c4.png)

Bootstrap:
![bootstrap](https://user-images.githubusercontent.com/5412178/144815198-9dce75e4-3be9-42b9-91c9-4739b07406e9.png)

Before the latest update (1.6.1) you could work around this issues by setting the heading to "H1", then in the text field add your own heading-tag. For example: `<h1>My heading</h1>`. And the heading would be more appropriately sized.

That doesn't work anymore because of a newly added Tailwind css class:
`h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
}`

Appsmith should have appropriate heading sizes so that no work around is needed.

**Comment by KelvinOm** [comment]
Not relevant
