### ISSUE TITLE
[Feature]: Newly added tailwind classes disable the possibility to display regular HTML lists in Text-widgets

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#9583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow regular HTML lists in text widget.

### Why should this be worked on?

Before the latest update (1.6.1) you could display a regular HTML list by using a Text-widget and setting the lists html code as the text content, like this:
![list](https://user-images.githubusercontent.com/5412178/144816796-4ead0fd9-1567-4df2-a507-15f2b8712f66.png)

The list would display as expected with indentation and the appropriate markers.

Now after the update a few Tailwind css classes seems to reset the list:
`ol, ul {
  list-style: none;
}

fieldset, ol, ul {
    margin: 0;
    padding: 0;
}`

This is unfortunate since we can no longer display basic HTML lists.

A possible workaround could be to use the Rich text editor widget by setting it to disabled and hiding the toolbar. That's not a good solution though since the Rich text editor isn't using the default font and typography settings and also has i white background.

To solve the issue either the Tailwind classes could be removed or maybe a new HTML list widget could be created.

**Comment by jsartisan** [comment]
@oskarannas Hey I just raised a quick PR to fix this. can you check if this DP of the PR fixes it? - https://deploy-preview-9594--appsmith-editor-ce.netlify.app/

**Comment by oskarannas** [comment]
> 

It seems to be working great. The left padding is missing but that totally fine, not a problem. Big thanks! :)
