### ISSUE TITLE
[Bug]: Password field accepts 'space' as a character 

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently user is able to signup/reset to a password which accepts blank spaces as characters.

![image](https://user-images.githubusercontent.com/92293815/144810066-61d93ddd-55d4-4405-84b6-8dd605372336.png)

Expected behavior: Blank space must not be allowed.

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/
2. Signup > Enter password with blank spaces.

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@shwetha-ramesh spaces are valid password characters. Airtable accepts them as well
