### ISSUE TITLE
[Bug]-[200]:Default functions are retained on the run dropdown even after deleting the JSObject code

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS object does not recognize incorrect structure when code is copy-pasted and hence the default functions `myFun1` and `myFun2` are retained. No error is displayed either on the response or error tab of Debugger and only shows one when the function `myFun1` or `myFun2` are run.

### Steps To Reproduce

1. Go to app at [link](https://release.app.appsmith.com/applications/612332edfe755a38b6e6a9c2/pages/61aa020312c2470ed74e584a/edit/jsObjects/61aa035012c2470ed74e584f) or copy paste a chunk of code that does not follow our JS structure of `export {}...`
2. Observe the default functions retained even after the toast message informing of expected structure
![image](https://user-images.githubusercontent.com/79509062/144824816-3fd79774-daad-4e01-a6d6-0de73dc96acb.png)
3. Run any default function present in debugger and observe the error.

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment]
The above case works as expected for copy-pasted code, but removing default structure `export default {}` retains default functions `myFun1` and `myFun2` in the debugger instead of showing a message as seen in the screenshot below.

https://www.loom.com/share/5eb8a2db83e44a5cbf96592a47f7f579

![image](https://user-images.githubusercontent.com/79509062/150138442-ee11612e-7d7f-487e-8bff-aa70399396d9.png)

**Comment by bharath31** [comment]
Unable to reproduce this issue

**Comment by ramsaptami** [comment]
This issue is reproducible on current release and prod hence reopening it @bharath31
