### ISSUE TITLE
[Bug]: Welcome Tour throws error for new users

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently any new user who signs up and enters homepage and goes through the Welcome tour  faces error in 'Mission 1' of the tour and not able to proceed.  (Refer video)

![image](https://user-images.githubusercontent.com/92293815/144828294-1b271029-91f7-4740-be49-649ed464c3bd.png)

https://loom.com/share/ed69a03878064c79aeb723242b787373

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/
2. Sign up > Give new user details
3. In homepage > Welcome tour

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk can we please get a test for this?

**Comment by akash-codemonk** [comment]
Tests exist and they are failing

**Comment by Nikhil-Nandagopal** [comment]
@akash-codemonk but this is happening on prod as well

**Comment by akash-codemonk** [comment]
the datasource host changed from `fake-api.cvuydmurdlas.us-east-1.rds.amazonaws.com` to `mockdb.internal.appsmith.com` which is why the query is failing to run.

**Comment by mohanarpit** [comment]
@akash-codemonk Can we fix this in the client code base to point to the new subdomain?
