### ISSUE TITLE
[Bug]: User is navigated back to active datasources when deleting GSheets from datasource page

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to Google Sheets datasource with queries from datasource page navigates the user to the top of the Active Datasources page - this behaviour is unique to GSheets.

https://www.loom.com/share/2f2f67a5e1c04eb08e737839229fa64e

### Steps To Reproduce

1. Create a GSheet datasource and dependant queries
2. Try and delete this datasource from it's own page as seen in the video. Other datasources display a message stating there are queries present for this datasource on the same page - but for GSheets, user is navigated to active datasources page.

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
the delete button is not available on the ds edit anymore. Now when I try to delete the datasource from the review page, it works ok:

https://github.com/appsmithorg/appsmith/assets/94514895/623be5d8-7c70-4108-93e3-bf1839a81f22
