### ISSUE TITLE
[Bug]: Selecting autocomplete while using setInterval trigger exits control from input box on pressing enter

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hitting enter to select autocomplete causes control to escape from input box on trigger field when using default structure present for `setInterval`

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e194027363954436a7579979baf7f96d-00001.gif)](https://www.loom.com/share/e194027363954436a7579979baf7f96d)

### Steps To Reproduce

1. Drop any widget with trigger field on to canvas
2. Use setInterval in non-JS mode and try to use any function from autocomplete suggestion and select the autocomplete choice using Enter and observe the focus move away from the box on hittng `Enter`

### Environment

Release

### Version

Cloud

**Comment by bharath31** [comment]
Unable to reproduce this issue
