### ISSUE TITLE
[Bug]: By toggling the switch widget the toggle turns into blue colour

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the user disables the switch widget toggle the turns into blue colour 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8503a1e97ed640a78375739b6f75f047-00001.gif)](https://www.loom.com/share/8503a1e97ed640a78375739b6f75f047)

### Steps To Reproduce

1.Launch appsmith app in release/Prod Environment 
2.Drag and drop switch widget 
3. Disable the switch toggle(Mouse hover on the switch toggle so that the mouse icon will be a pointer and click on the toggle and observe the colour changes to blue)

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Really hard to see, pick this up after everything else is resolved.
