### ISSUE TITLE
[Bug]: The error toast is displayed when user clicks on Git user config tab

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Unexpected error toast is displayed when the user clicks on the Git user config tab in the profile setting page 
![image](https://user-images.githubusercontent.com/45958978/144836744-31314fbe-60df-417e-bad2-5d8f92781bd8.png)

### Steps To Reproduce

1. Sign up as a new user
2. Click on Username
3. Click on the Edit profile menu
4. Click on the Git Config tab 
5. The error toast is displayed

### Environment

Release

### Version

Cloud

**Comment by rishabhsaxena** [comment]
This looks fixed now
