### ISSUE TITLE
[Bug]: The duplicate error message is displayed in the debbuger 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The error message should be displayed only once when the Label and value are not in expected format in the select widget
![image](https://user-images.githubusercontent.com/45958978/144837866-c9b04a62-efee-49d0-affa-b93a6e0eba38.png)
![image](https://user-images.githubusercontent.com/45958978/144839068-bf03574a-383a-4a9f-b9b0-23045908a5ea.png)

### Steps To Reproduce

1. Go to canvas
2. drag and drop the select widget
3. add the mongo query 
4. Now bind it to Select widget 
5. When the data is not in the Label and value format the error is displayed

### Environment

Release

### Version

Cloud

**Comment by Tooluloope** [comment]
@riodeuno, Should we handle this.
The Error messages are actually valid.

**Comment by riodeuno** [comment]
@Tooluloope 

Problem 1: This seems to be a DX issue. I can see why having all of them printed at once can make it difficult to navigate the errors.

Problem 2: There is also the issue of validating so many entries, this can reduce response time (performance)

The solutions we can explore here should deal with both of them separately.

Solution 1: We "load more" errors on demand for similar type of errors.
Solution 2: We bail out from logging errors in the same array after we have identified 10 errors or so. 

We need to discuss further with the team regarding Solution 2. 

However, we should move ahead with Solution 1. This will involve creating a data structure which would be provided by the validations, and understood by the debugger, resulting in a collapsed view, showing only 3-5 errors of the same time. There will also be a "show more" option that when clicked, would load more of the errors.

**Comment by riodeuno** [comment]
Solution 2. is available in release. #10886

**Comment by riodeuno** [comment]
@RakshaKShetty @dilippitchika This shouldn't be an issue anymore, with #10886 merged. Can we revisit and close this issue if we won't be tackling it?
