### ISSUE TITLE
[Task]: Welcome tour datasource hostname should not be hardcoded in FE

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#9605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Currently, the hostname of the data source used by Welcome tour is hardcoded in the FE code. This should be dynamically fetched from the server. This will help us in the future when we update the hostname.

**Comment by sharat87** [comment]
As discussed, let's change the host to `mockdb.internal.appsmith.com` instead.

**Comment by akash-codemonk** [comment]
Closing this as this was for the previous onboarding. The current onboarding imports an application instead.
