### ISSUE TITLE
[Bug]: List widget does not reset the meta data for input widget first list item on data change.

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#9607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Usecase from user:

`I have a list widget. Each item in that widget has an input field. Data for that list is coming from appsmith store. I have a button on page which when clicking changes data in appsmith store which in turn gives updates to list widgets data. The problem is that if I edit input field in list widget and then click button on page to regenerate that list widgets data, I can still see on first item in the list that input field has the same value as I edited before when list widget had another data which is not correct... I would want to reload completely list widget when I change data for it, how could I do that?`

### Steps To Reproduce

1. Add list widget.
2. Add input widget to the list widget
3. Add a button out of the list widget and add an action on that button that will change the list data.
4. Now enter anything in the input of the first input and click on the button.
5. Notice the input still have the same value even on data change.

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Will need to check #15487
