### ISSUE TITLE
[Bug]: Duplicating an application does not duplicates a JS Object

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#9611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I duplicate an Application which have a JS Object, that JSObject is not present in the duplicated application.

### Steps To Reproduce

1. Add a JS object to an application
2. Go to home page and duplicate the application
3. Open the duplicated application
4. Check that JSObject is not there

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
can confirm this happens with "duplicate" action. Might be relevant: "fork" doesn't have this problem.

**Comment by nidhi-nair** [comment]
Closing as duplicate of #9372.
