### ISSUE TITLE
[Bug]: Text widget no longer renders HTML bullets

### ISSUE THREAD

**Issue by jlund** [appsmithorg/appsmith#9612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text widgets in version 1.6.1 don't display HTML formatting for bullets.

As a temporary workaround, you can replace the Text widget with the Rich Text Editor widget and switch on the "Disable" and "Hide toolbar" options.

### Steps To Reproduce

1. Add a text widget to a page.
2. Change the text value to `<ul><li>hello</li></ul>`.
3. Observe that the bullet isn't rendered.

### Environment

Release

### Version

Self-Hosted

**Comment by areyabhishek** [comment]
Hi, this was a bug that crept in because we added Tailwind css recently. Here's the PR that'll be fixing this issue very soon: https://github.com/appsmithorg/appsmith/pull/9594

I'll close this issue because it has already been reported.
