### ISSUE TITLE
[Docs]: Contribution: how to install appsmith on an ubuntu server without docker

### ISSUE THREAD

**Issue by chrismaeda** [appsmithorg/appsmith#9613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I wrote some docs on how to install appsmith on a single linux server without docker or docker-compose.

Feel free to incorporate these.

https://github.com/chrismaeda/appsmith-deploy-single-server-nginx

### Describe the improvement

I wrote some docs on how to install appsmith on a single linux server without docker or docker-compose.

Feel free to incorporate these.

https://github.com/chrismaeda/appsmith-deploy-single-server-nginx

**Comment by sharat87** [comment]
Hey @chrismaeda, thank you for sharing this. Unfortunately, building Appsmith from source for running on a server for production isn't recommended. This will mean the setup needs to updated manually everytime there's a new version of Appsmith. Additionally, every production setup done from source will be slightly different and so supporting and troubleshooting will become further difficult.

However, building from source is and should be encouraged for contributors working with Appsmith's source itself, which is development and not production. Our existing contributing documentation should already serve this purpose. If you feel the contributing docs are not complete are not solving for this, please open a PR to improve this and we'd love to review that!

Thank you again, and sorry for not being able to take this forward. Looking forward to see more contributions from you in the future! 🚀
