### ISSUE TITLE
[Bug]-[660]:Select an icon conditionally for the input widget

### ISSUE THREAD

**Issue by edyou2021** [appsmithorg/appsmith#9614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Provide a way to customize JS, like the icon button of the table widget，it can select a icon conditionally

**Comment by dilippitchika** [comment]
We can add JS on this

**Comment by dilippitchika** [comment]
Assuming 30% of users want to add JS

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 330 |
| Effort (months)  | 0.5 |

**Comment by dilippitchika** [comment]
@sbalaji1192 adding this to table v2 stability. Please ensure it's changed for both v1 and v2. Souma or rishabh can work on this.

**Comment by dilippitchika** [comment]
@dilippitchika to check and close

**Comment by dilippitchika** [comment]
Only needed for input widget and text input, email input and number input in the JSON form. @aswathkk can you check if you have added the JS switch for them in property pane changes?

**Comment by aswathkk** [comment]
@dilippitchika This is not added. I will add this soon
