### ISSUE TITLE
[Feature]-[548]:Provide GitHub's `Blame` like feature on Appsmith

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Sometimes we want to know who made a certain change to the application and when. For e.g. is someone marked some action to be run on page load or if someone changed a line in a JS object, another application developer might be interested in knowing who made that change and when.

### Why should this be worked on?

Helps with collaborative development.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 274 |
| Effort (months)  | 1 |
