### ISSUE TITLE
[Bug]: Chart widget shows invalid data whenever value of y key is not number.

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#9624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The validations of chart widgets say y key in the data can be string or number but whenever there is string in the key, `10` shows up as the value of y key. As a user, I don't expect to see the `10` in y key.a 

### Steps To Reproduce

1. Drop chart widget and enter the following values

![image](https://user-images.githubusercontent.com/6636360/145044680-1bc7b70d-4377-4772-b831-882af1b65b19.png)

### Environment

Production

### Version

Cloud

**Comment by tbatista-fuze** [comment]
following this

**Comment by YogeshJayaseelan** [comment]
@Tooluloope Verified this PR and it is working as expected

**Comment by tbatista-fuze** [comment]
thanks

**Comment by tbatista-fuze** [comment]
still seeing the error being shown 
![image](https://user-images.githubusercontent.com/88663755/149352502-0081977f-c783-43fb-91bc-bc61f3cb1a8b.png)

**Comment by dilippitchika** [comment]
Hi @tbatista-fuze can you help me understand your use case? Are you trying to show X axis with numbers and Y axis with strings?

**Comment by tbatista-fuze** [comment]
yes, sure, I'm doing a count for appearance of strings, for example:
{'wordA': 25, 'wordB': 30, ...}

**Comment by dilippitchika** [comment]
![Screenshot 2022-01-14 at 4 06 46 PM](https://user-images.githubusercontent.com/19730984/149502017-195501f5-561f-4a40-8537-74013af10d11.png)
I guess you are using a column chart, can you use a bar chart instead? You will still need to map x-axis with string and y-axis with number but it will align as you want.

**Comment by tbatista-fuze** [comment]
tried with bar chart and the error persists. However, when I use a constructed JSON it works, but if the JSON is built using code to map it, it brakes

**Comment by dilippitchika** [comment]
Hey @tbatista-fuze I want to debug this with you on a call, if that's ok. Can you block a slot with me if possible?
https://calendly.com/dilip_pitchika/30min?month=2022-01

**Comment by tbatista-fuze** [comment]
Done, see you there :)
