### ISSUE TITLE
[Bug]: helm fails if namespace exists

### ISSUE THREAD

**Issue by yannick** [appsmithorg/appsmith#9625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if i want to deploy appsmith via fluxcd helmrelease it fails unless it can create a new namespace

### Steps To Reproduce

try to deploy the helmrelease into an existing namespace

### Environment

Release

### Version

Self-Hosted

**Comment by sharat87** [comment]
Hey @yannick, thank you for reporting. We are currently working on a fix for this and you should see a solution very soon. I'll keep this open to be closed once that PR is merged in.

**Comment by gokuatkai** [comment]
Hello, I added PR that fixes the issue, but I think you should rather remove the namespace resource from the chart.
helm should be able create it by itself using `--namespace`

**Comment by sharat87** [comment]
Hey @gokuatkai, thank you for mentioning that here. I've merged your PR in. However, I'm going to keep this issue open since what you describe in your comment is indeed the fix we want do. Let's close this after that is also done.

Thank you for your contributions!

**Comment by sharat87** [comment]
Closing this since we don't have a namespace resource anymore in our Helm chart.
