### ISSUE TITLE
[Bug]: Space is not reflected in the text widget.

### ISSUE THREAD

**Issue by hmu332233** [appsmithorg/appsmith#9626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I expected the text widget to show the text I entered with the space.
However, as shown in the picture below, all spaces have disappeared.

If it's an intended function, I'd like to suggest adding a white space setting option.

![image](https://user-images.githubusercontent.com/10302969/145079825-2fa26919-f424-43cf-8855-f1089027f474.png)

![image](https://user-images.githubusercontent.com/10302969/145079854-6e82a0eb-3182-463b-9685-531905909ce4.png)

### Steps To Reproduce

1. Create to Text widget.
2. Enter the text below into Text widget
```
Text
  Text
    Text
      Text
```

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@hmu332233 thank you for reporting this. This is indeed a bug
