### ISSUE TITLE
[Feature]: Use only the carat buttons to collapse children in the Explorer view

### ISSUE THREAD

**Issue by chrispytoes** [appsmithorg/appsmith#9627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This is a minor annoyance that's been bugging me. I don't like how selecting an item in the Explorer view also toggles its children to open/close. I think it makes more sense to have only the carat buttons open/close the items, so that you're not constantly opening or closing things you didn't mean to.

### Why should this be worked on?

This is usually the standard way that tree views are expected to work, so this would improve ease-of-use a little bit.

**Comment by areyabhishek** [comment]
Hi Chrispytoes, this in an annoying thing indeed. This was a bug that crept in a few weeks ago. We've pushed a fix for this already and it should go live tomorrow(for cloud hosted) and Monday(for self-hosted users). https://github.com/appsmithorg/appsmith/pull/8961
