### ISSUE TITLE
[Feature]: Using widgets to create custom React-like components

### ISSUE THREAD

**Issue by chrispytoes** [appsmithorg/appsmith#9628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

First off, I'm aware of issue #2033 for adding fully custom widgets. What I'm proposing is a way to take a widget on the canvas, with all of its settings and children, and save it for instantiating wherever it's needed. Perhaps they could be called "Components", and be added as another page-level (or top-level?) object type.

I think the true power of this feature would come from the ability to pass parameters into each component instance from its settings panel, and reference those parameters within the widgets inside the component using `this.params` or some other method.

Effectively the same concept as React components and props.

### Why should this be worked on?

I don't think I need to explain how useful this would be, do I?

**Comment by Nikhil-Nandagopal** [comment]
@chrispytoes is this similar to creating a reusable widget like this issue describes? #5229

**Comment by chrispytoes** [comment]
@Nikhil-Nandagopal It sounds like it yes, but I think my explanation of it is a little clearer and is more specific as to how it should work.

**Comment by Nikhil-Nandagopal** [comment]
@chrispytoes thanks I'll copy your explanation over to that issue and close this one
