### ISSUE TITLE
[Bug] added theme must be restricted for selected account and not for all the account

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#963]
https://www.notion.so/added-theme-must-be-restricted-for-selected-account-and-not-for-all-the-account-9660829216474d649134ce935694cb38

**Comment by prapullac** [comment]
The theme does not get saved into the profile ie: once the user logout and re login  it is observed that the profile navigates back to default mode.Hence reopening the issue 
Please find the attached video below:
https://www.loom.com/share/f7b14abdef9f47edb23d4a8bff9de423

**Comment by hetunandu** [comment]
@mohanarpit Do we want to save the theme for each user? Will this be a client side save only?

**Comment by Nikhil-Nandagopal** [comment]
Themes are only to be saved locally for now. We're tracking saving this server side here #2702
