### ISSUE TITLE
[Bug]: Column visibility settings is incorrectly altered when column position is changed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Column visibility incorrectly changes when order is changed on the property pane. 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9eba7e1f12584486ab8b56c674d476eb-00001.gif)](https://www.loom.com/share/9eba7e1f12584486ab8b56c674d476eb)

### Steps To Reproduce

1. Mark a few columns of a table widget as hidden and then move their position on the list as seen in the video attached
2. Toggle the visibility buttons and the ones marked hidden become visible and vice versa

### Environment

Release

### Version

Cloud

**Comment by riodeuno** [comment]
Seems like we're using indices instead of column keys to maintaining the visibility property of columns. Or, there is a bug in the computations of the `tableColumns` which results in this issue.

@sbalaji1192 @somangshu This should be fairly simple to triage. Please assign this accordingly.
