### ISSUE TITLE
[Bug]: When the widget is dragged & dropped manually in Welcome tour the widget shows error

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user follows the _Welcome tour_ and does the tour manually by following the instructions of the tour when the table widget is dropped on the canvas it shows error and continues to be present even after the right binding (Refer video)

![image](https://user-images.githubusercontent.com/92293815/145156461-18c74b36-25e3-4c10-a83b-8f9f679eb8e3.png)

![image](https://user-images.githubusercontent.com/92293815/145156494-67193579-72c7-4a7d-82a3-a31eb1b3edb1.png)

### Steps To Reproduce

1. In Homepage click on Welcome tour present at the bottom left
2. Follow instructions > _Let's go_ > _Start Building_ > _New Query_ > _Run_ > _Add Widget_ > Drag & Drop table widget and observe

### Environment

Production

### Version

Cloud

**Comment by RakshaKShetty** [comment]
This bug is not valid as we have changed our welcome tour
