### ISSUE TITLE
[Bug]: When the user uses the 'Suggested widgets' the bindings fails for Select widget in Welcome tour

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user follows the _Welcome tour_ and does the tour manually by following the instructions of the tour when the user selects the _Select_ widget that appears below 'Suggested widgets' on the right, the binding fails and no data is shown. (Refer video)

https://loom.com/share/5948225656234aa5be50984d109cfbed

### Steps To Reproduce

1. In Homepage click on Welcome tour present at the bottom left
2. Follow instructions > Let's go > Start Building > New Query > Run > Under Suggested Widgets click on _Select_ Widget > Observe the widget drop down and bindings >

### Environment

Production

### Version

Cloud

**Comment by vivekverma2312** [comment]
Removing QA label as new welcome tour is available now and this could not be tested.
