### ISSUE TITLE
[Bug]: Divider Widget Doesn't Expand

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#9642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The divider widget is difficult to use and doesn't expand. 
The click target for expanding horizontally is too small. An Illustration is shown in the video bel

https://user-images.githubusercontent.com/17744578/145166666-9b3a6d6c-77ea-4ce0-bb43-262d0b86b72e.mp4

ow

### Steps To Reproduce

1. Drag a divider widget into the canvas
2. Try to expand it horizontally

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
We need to change the default size to 2 rows which is acceptable by the platform such that the resize takes place by default. 

_**Stretch:**_ Further we will look into what needs to change to accept the default at 1 row.
