### ISSUE TITLE
[Bug]: Document viewer icon is not displayed in the entity explorer

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that the document viewer icon is not displayed in the entity explorer when the document viewer is dragged and dropped to the canvas

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2ffa27199f5046c79e240ee0b7af2ddc-00001.gif)](https://www.loom.com/share/2ffa27199f5046c79e240ee0b7af2ddc)

### Steps To Reproduce

1.Launch appmsith app in release/Prod Environment
2.Drag and drop document viewer widget 
3.Check for the icon in the entity explorer under the widget section

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
Seems to be working
