### ISSUE TITLE
[Bug]: JS object does not read values from select widget when options are derived from a binding 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

JS object does not pick up the value from multi-option widgets such as select, checkbox, radio etc when values to those widgets are derived from a binding.

![image](https://user-images.githubusercontent.com/79509062/145172629-7dad2504-f142-4c0f-9612-d4f4bb91f1f9.png)

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/644e1aef17a94460ab1cfd2aca35ec47-00001.gif)](https://www.loom.com/share/644e1aef17a94460ab1cfd2aca35ec47)

### Steps To Reproduce

1. Create a JS object with an array of elements with value and label for select widget
2. Bind this to a select widget on the canvas
3. Use selected `value` or `label `property in another JS object to execute a `console.log` line and observe the value returned

### Environment

Release

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
we had discussion not to make js object variables reactive and partially it will be solved as part of #9979 by @ApekshaBhosale

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/9645?planning-poker) with ZenHub @ApekshaBhosale
