### ISSUE TITLE
[Bug]: Icon widget name overlaps with the audio recorder widget text when they are placed nearby

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#9647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that when the icon widget is placed near by the audio recorder widget the icon name overlaps with the audio recorder widget text in the edit mode. Refer video for details

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/62c3d5361ef34af488f0e80ed15ba5b2-00001.gif)](https://www.loom.com/share/62c3d5361ef34af488f0e80ed15ba5b2)

### Steps To Reproduce

1.Launch appsmith app in release/Prod environment 
2.Drag and drop audio recorder widget 
3.Place the icon widget right side to the audio recorder widget 
4.click on the icon widget so that it displays the icon widget name 
5.Mouse over on the audio recorder widget and observe

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/appsmithorg/appsmith/assets/94514895/6a55995f-98eb-4a97-ae4f-b0173c47a389
