### ISSUE TITLE
[Bug]: Modal widget does not open up when selected from entity explorer

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to navigate to a modal widget by clicking on entity explorer fails to open up the widget. Instead, if another widget, for example select widget, is selected after clicking modal widget then the modal widget first opens up and then canvas navigates to the select widget.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/5689f50dc13a4445a517a2949690a981-00001.gif)](https://www.loom.com/share/5689f50dc13a4445a517a2949690a981)

### Steps To Reproduce

1. Open up any query or JS object
2. Try to navigate to canvas by clicking on a modal widget from the entity explorer. Nothing happens even after multiple clicks
3. Now click on any other widget present on the canvas and observe the modal widget open up before navigating to the selected widget

### Environment

Release

### Version

Cloud

**Comment by kocharrahul7** [comment]
possible duplicate issue :https://github.com/appsmithorg/appsmith/issues/10740 

@ramsaptami can you please confirm that both are the same

**Comment by kocharrahul7** [comment]
possible duplicate issue :https://github.com/appsmithorg/appsmith/issues/10740 

@ramsaptami can you please confirm that both are the same

**Comment by Nikhil-Nandagopal** [comment]
Yes they seem like duplicate issues
