### ISSUE TITLE
[Bug]: Download icon on table widget needs to be changed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Download icon on table widget is an inverted upload button and needs to be changed to an appropriate one.

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/79509062/145208376-dcfe145f-fa68-4e42-b8f5-663b2685de72.png)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@ramsaptami What message is conveyed looking at the icon according to you? I perceived this to be download from cloud.

@momcilo-appsmith need you comments here.

**Comment by momcilo-appsmith** [comment]
@somangshu @ramsaptami Can you try this one and send me how it looks? https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=1140%3A12248

It actually is that icon to upload but rotated so we could change it.

**Comment by somangshu** [comment]
@momcilo-appsmith this looks appropriate. We can take this up now.

@ramsaptami let us know if you think the icon is not appropriate.

**Comment by ramsaptami** [comment]
The new one looks good. It's the download icon most users would be accustomed to.
