### ISSUE TITLE
[Epic]: Templates

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#9661]
### Objective

We want users to make apps faster than before. To do so, we are working on templates, which will allow our developer community to leverage our expertise and knowledge to create some really useful templates.

Users will be able to access our templates, and import them directly into their apps, allowing them to create their first app even faster.

We are looking to create 2 types of templates:

1. complete tools/applications, which are fully featured, and can be used by developers as is.
2. Functionality tools, which are made to highlight specific functionality that our developer community can leverage, and import into their existing apps.

### Success Metrics

| Goal          | Metric         |
| ------------- | -------------- |
| Simplify user experience  | Forks of each of our templates increase over time  |
| Simplify onboarding flow  | Reduced time to create your first complete app        |
| Empower new developers  | Increase in returning users        |
| Empowering user supported/recommended content | Increased user suggestions on our apps  |
| Make sure we are building the right apps  | High user adoption for each of our templates  |

### Requestor

The person responsible for introducing the application/template to us. The person will be responsible for outlining the requirements of the app, and building a dummy app / wireframe. They will be responsible for thinking through the entire process workflow, and ensuring the functionality meets their initial expectations 

### Designer

The designer is responsible for ensuring that the design sparks excitement and joy for the app viewer, ensuring that various templates follow the same design language, and that the app meets the high design standards we impose on ourselves

### App builder

This is the person responsible for the final execution of the template, converting the initial dummy app into a fully functional app.

## Process of creating a template

We would like to have a clearly outlined process of creating a template. This will allow us to maintain quality, as well as monitor the progress of each template. 

1. Initial wireframe/outline is created, as well as a
2. Design is reviewed by a designated designer, giving inputs, either by comments, or by editing the application themselves.
3. The app is updated to match the inputs from the designer
4. The application is then handed over to a developer, who will create database/data source connections, as well as dummy data.
5. The app, once completed will go through a final approval ,with all stakeholders (original requestor, designer, and app builder giving approval).

## Creating visibility / enabling users to find the templates

We will have to make templates available to all users, we should create a landing page. Users will be able to see all available templates, and play around with the created applications without logging into the app. This will allow new users to discover the templates the moment they open the AppSmith website, and understand the rich templates that they will have available to them instantly.

## Sharing of templates

Templates will at the end of the day be applications. Users should be able to create an application from a template both on Appsmith cloud and on their local instance.

## Implementation guideline
The templates will be stored in Appsmith cloud. Each template will have the following information:

- Name of the template
- Minimum supported version of Appsmith
- An application JSON
- Meta data e.g. description, screenshots, create date, updated date, public app link

#### Creating a template

1. An application will be created on Appsmith cloud
2. Make the application as public
3. Export the application as JSON
4. Store the application JSON along with other information to Appsmith CS. If there is an existing version of the template - this will override that. So there'll be a single version available for each template application.

#### Show the templates

1. The FE will call a BE API to get list of templates
2. BE will fetch the templates list from CS. BE will pass the version so that compatible templates are shown only. Alternatively we can return all templates and enable/disable based on version on FE
3. FE will show the templates to user

#### Preview a template

1. User will choose the option to preview the template through a button or link
2. A new tab will be opened with the corresponding public app running on Appsmith cloud

#### Import a template

1. User will choose the option to import a template
2. UI will ask to pick the organization where the application will be imported
3. BE will fetch the application from the CS and import it to the target organization
4. FE will take user to the newly imported application
5. CS will manage a counter to track how many times a template has been imported

#### Phase 1 UX Flow

https://www.figma.com/file/dmDCEc6g2DvccF1QElkdAs/Templates?node-id=2212%3A11165

### Deploy preview

https://appsmith-fijux5k4a-get-appsmith.vercel.app/

### RACI matrix

| ------------- | ------------- |
| Responsible   |  @nayan-rafiq   |
| Accountable   | @akash-codemonk   @kocharrahul7 @RoopKrrish9696  |
| Consulted     | @Nikhil-Nandagopal @areyabhishek |
| Informed      |  @cokoghenun     @Rishabhkaul   @mohanarpit        |

**Comment by kocharrahul7** [comment]
Decisions taken so far:

1. Tags: types of tags:
- data sources
- useage types/functional area (support, marketing, sales)
- Title
- Widget types used in the template
- Departments
- Industry (Technology, Logistics, e-commerce)
- Style/theme
- API provider, etc.

2. Landing pages will be CMS Optimised, we will have all our landing pages follow a standard outline/template, which will allow us to have a highly scalable discovery and landing pages.
3. Created a list of templates being offered by other tools, and using those as priority templates which will be highly SEO optimised, merging the list with the existing templates

Decisions to be takes:

1. How will apps be hosted? will they be in an existing organisation, or will we create a new one which is a combination of the apps in the existing orgs
2. Databases: How will we handle the creation and user permissions. Will users be able to edit apps? When they import apps should we break the database connections so that users can't flood them?
3. What are the Landing page rules that we have to follow: How many images/gifs/paragraphs/tags etc.
4. What is the template design language we would like to follow (template colour scheme, font family/size, etc.)
5. What are the first 5 apps which we will prioritise?
6. Come up with a BRD format which can be leveraged to make the landing pages easily.

**Comment by Nikhil-Nandagopal** [comment]
@kocharrahul7 
I think style / theme should be interchangeable so I think that shouldn't be a tag. Also, what is API provider and why is it different from data source?

**Comment by kocharrahul7** [comment]
These are the points from last weeks discussion:

1. catch-ups rescheduled to Mondays
2. We are working on the first few templates for AppSmith. We are using the process of reskinning the old templates to modernise them.
3. Discussed the template landing page, and settled on a simplistic design, which will bring emphasis to the actual app rather than a GIF or screenshots.

Points to discuss this week:
1. The user flow for discovery of templates
2. The current progress on the templates
3. We are planning a collaboration, and the template we are thinking of creating is a CRM portal, so we should discuss the steps for that, as well as the BRD, and when we can progress to the next steps (creating the template)
4. Discuss the current list, and process, and see where we can improve.

**Comment by kocharrahul7** [comment]
Template discovery: Roop created and shared various options for the Template page for existing user discovery. Of the 3 options mentioned below, we have decided to go with the 3rd option (a tab which will highlight all templates, and allow a user to test and fork the template into their org

Landing pages: Kadao is working on creating a landing page for our templates which is browsing, SEO and CMS friendly. The points to remember are:

we must focus on selling a story rather than just the app. We highlight the type of customer which can use the app, as well as other possible use cases of the same app

We should also try to make it as easy to browse as possible, users should be able to check out a template, and if they like it, look at other similar templates. A user should be able to browse using tags, use case, databases, widgets, etc. And most importantly, a user should be able to navigate from one template to another with ease.

The design should be our own, while we can seek inspiration from existing template browsers, it is essential that we do NOT copy them

We should create 2 options, one which prioritises using the app first, and another which prioritises browsing, perhaps with GIFs, images, and videos, and allow users to open the app in a new tab/window

Templates we will work on this week:

1. Customer Support Dashboard
2. Admin tools (Mongo and postgreSQL)
3. Bulk upload
4. FaunaDB CMS tool (Design review)

**Comment by hiteshjoshi** [comment]
Next actionable items.

- Flow for existing users on app.appsmith.com
- Flow for discovery, ( new users).
- Wireframes based on the flows.

**Comment by RoopKrrish9696** [comment]
**Updated Figma link for templates flow:**

https://www.figma.com/file/dmDCEc6g2DvccF1QElkdAs/Templates?node-id=2212%3A11165

**Comment by RoopKrrish9696** [comment]
**Templates Design QA feedback based on the DP https://appsmith-gozbmkr8a-get-appsmith.vercel.app/ :** cc @kocharrahul7 @akash-codemonk 

Home Page:

1. Tab with Apps & Templates has more padding wrt the active line below it
2. Search should be scrollable in the home page , no need to make the position stick.
3. The font weight of "Apps/templates" is different ( its more ).

Templates Page:

1. Search and "Showing all templates" should be scrollable
2. Padding b/w search and "showing all templates" is high
3. Padding b/w "Showing all templates" and next row is high
4. Padding b/w first row cards and next rows is high
5. In the filters section, the section is not equal height from appsmith logo as it is in the home page
6. In the filters section , the selected item bg can be of more width towards left.
7. The close button in the filter selected item is of less size.
8. Can we have the same font weight used in the home page "organisations" name for all the filter headings in here as well? ( I maybe using different font weight due to old design style, ill try to fix this )
9. Space below the filters section should be more , also the lower section of "whats new, welcome tour" is missing
10. The fork button icon in the card is small and different.
11. Alternative text for fork button on hover is missing.
12. The card titles and paragraphs font weights and sizes are different. Can you once please refer to the handoff?
13. Request a template card in the bottom is missing.
14. When filter is applied, the text "Showing 1 result" has a missing text of " matching X filters".

Template Description page:

1. The font sizes and weights are off in the whole page, please check handoff once, I can help you if you want to do it together.
2. Then height of the iframe should increase
3. The blue border, no of dot lines should be less and width of them should be more

**Comment by RoopKrrish9696** [comment]
**Templates Design QA feedback based on DP https://appsmith-2451ltc62-get-appsmith.vercel.app/templates : cc @kocharrahul7 @Parthvi12 @akash-codemonk** 

1. In the tooltip notification - the arrow is missing
2. The left panel filters have missing left padding in the templates tab
3. Fork button is not in circle in small cards 
4. Close button size can be increased in the filters panel and also in the popup to choose organisation

**Comment by RoopKrrish9696** [comment]
**Final Design Audit bugs : @kocharrahul7 @hiteshjoshi @Parthvi12 @akash-codemonk** 

1. Update all fork icons in the platform to new one
2. Change the fork modal to the new one in the apps tab

**Comment by RoopKrrish9696** [comment]
**Few small design fixes :** @akash-codemonk @kocharrahul7 

1. The padding between back button and title is reduced to 12px
2. The  font-size of subtext in all the sections is reduced to 16px  ( Function , Industry, Datasources )
3. "Showing all 5 templates" font size altered to 20px ( We dont have 18px in the design system, sorry my bad )

**Comment by kocharrahul7** [comment]
Feedback on Mar 28th:

UI changes from feedback to be made:
Add a  view all templates CTA
updating the URL for the “request a template” CTA
updating the animation to make it seem like a new page, rather than navigating around the same page
Changing filters from AND to OR

**Comment by kocharrahul7** [comment]
Catchup on Mar 29th:

- Discussion around Events, the events we must log are:
1. templates being selected
2. filters being applied
- Recently used templates need to be shown for Phase 2, so we need to log templates recently used by a user, and which app is triggering it. For now we will have a user level recently used template, but we will have the option to add an app level filter, so a user can see the most recently used template in this app

- Apps are being uploaded to production
- Final round of visual changes are going to be pushed to Release incorporating comments from 28th today

**Comment by hiteshjoshi** [comment]
Closing this. Will follow up on Templates v2
