### ISSUE TITLE
[Bug]: Button widget throws an e is an undefined error when the user runs the email query 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Button widget throws an e is an undefined error when the user runs the email query 

### Steps To Reproduce

1. go to SMTP Datasource
2. Configure the Port no with 587
3. Now create a new query
4. Add the same email Ids in TO, CC, BCC email input box
5. Bind this query to button widget
5. CLick on button
6. E is undefined error is dsplayed

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
@RakshaKShetty not able to reproduce in release and production, i used mailjet to test with the same 587 port. Closing this for now.
