### ISSUE TITLE
[Bug] Autocomplete doesn't work to access this object inside JSObjects

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#9692]
`this.` currently shows un-necessary autocomplete suggestions.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/66776129/174732947-0de0f502-5a48-44d1-b501-edd9d69b4669.png">

This needs to be changed so it lists variables and functions within the current object only.

Note: 
`this` keyword ideally would work with just functions `function() {}` within an object. Not arrow functions `() => {}`.
It is currently handled by appsmith, so it works with arrow functions too.

**Comment by rohan-arthur** [comment]
_When I use `this.` in the js editor, I should see suggestions for object variables and nothing else_
in Anand's example above, all those suggestions should not be shown, instead autocomplete should only suggest `myVar1` and `myVar2`.
