### ISSUE TITLE
[Bug]: The text seems to be Cropped in the resetting pop up In the admin setting page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The text seems to be Cropped in the resetting pop up In the admin settings page
![Uploading image.png…]()

### Steps To Reproduce

1. go to the admin settings page
2. edit the details 
3. click on the save & reset button
4. When the resetting pop up displayed the text seems to be cropped 

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by sharat87** [comment]
I'm not sure what popup we are talking about here. @RakshaKShetty, is it something that was removed in the time since this issue was opened? If that's the case, can we close this? If not, can you provide a screenshot or provide some more detail please?
