### ISSUE TITLE
[Bug]: missing fields if creating a CRUD page from table (MySQL / MariaDB)

### ISSUE THREAD

**Issue by marcgeldon** [appsmithorg/appsmith#9709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if I create a CRUD page from my MariaDB / MySQL datasource, only the first 4 fields are in the update form.

this happens on appsmith 1.6.1 

Here is my table structure:

`CREATE TABLE articles (
  id int(10) UNSIGNED NOT NULL,
  artno varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  locked tinyint(1) NOT NULL DEFAULT 0,
  artkind tinyint(4) NOT NULL,
  artcategory int(10) UNSIGNED DEFAULT NULL,
  unit_id smallint(5) UNSIGNED NOT NULL,
  expiring tinyint(1) NOT NULL DEFAULT 0,
  description text COLLATE utf8mb4_unicode_ci NOT NULL,
  number_of_packs int(10) UNSIGNED NOT NULL DEFAULT 1,
  receipt_quantity_of_pack decimal(10,2) DEFAULT NULL,
  receipt_quantity_total decimal(10,2) DEFAULT NULL,
  receipt_unit_id int(10) UNSIGNED DEFAULT NULL,
  quantity_final tinyint(1) NOT NULL DEFAULT 0,
  main_vendor_id int(10) UNSIGNED DEFAULT NULL,
  purchasing_price decimal(10,2) DEFAULT NULL,
  recommended_retail_price decimal(10,2) DEFAULT NULL,
  allergens text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  additives text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  additives_allergens_final tinyint(1) NOT NULL DEFAULT 0,
  notes text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  tags text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  _update_from_app tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`

### Steps To Reproduce

Please see my video https://youtu.be/YcDtRV3-f4g

### Environment

Production

### Version

Self-Hosted

**Comment by areyabhishek** [comment]
Hi Marc, this is currently a limitation and not a bug. We'll be introducing an update to this very soon and you'll be able to see all the columns.

**Comment by Nikhil-Nandagopal** [comment]
Solved with the new JSON Form
