### ISSUE TITLE
[Bug] Appsmith logo on login page should not take user to applications page

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#972]
## Steps to reproduce

1. Log out of an application
2. Multiple click on the Appsmith name displayed on the left corner of the application

and observe

## Observation

It is observed that on multiple clicks the user is navigated home page of the previously logged into application 

## Expected behaviour

Clicking on the Appsmith on the login page user should not be lead to home page rather must be inactive

**Comment by OmkarPh** [comment]
Hi @Nikhil-Nandagopal 
I am willing to work on this issue.

**Comment by hetunandu** [comment]
@OmkarPh assigned this to you

**Comment by Rehan6225** [comment]
@Nikhil-Nandagopal excited to work on this issue

**Comment by Rehan6225** [comment]
@Nikhil-Nandagopal can i work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@Rehan6225 Omkar is already working on this. I suggest you have a look at our many open good first issues :) I'd be happy to help you find one if you're having trouble

**Comment by OmkarPh** [comment]
Hi there, I am using WSL currently, 
When I try to do yarn start, it gives error as no such file or directory.

**Comment by mohanarpit** [comment]
@OmkarPh Sorry that you're facing this issue. Can you join our [Discord](https://discord.gg/rBTTVJp) channel? Will be easier to debug this issue and get you started on the codebase.

**Comment by rishabhsaxena** [comment]
this seems to be working, the link on the login page does not point to `/applications`
@Nikhil-Nandagopal is there someone (qa) I should assign this to?

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena you can close this and mark it as QA, it will get auto picked up by @prapullac
