### ISSUE TITLE
[Bug]: Incorrect error when API call is missing query param

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Incorrect 5000 error is displayed on the first run when API call is missing query param. On re-running the query, correct error is displayed to the user

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2bb9d7baae974ad1a0f4b5dcd0add894-00001.gif)](https://www.loom.com/share/2bb9d7baae974ad1a0f4b5dcd0add894)

### Steps To Reproduce

1. Make an API call with missing query param
2. Run the query and observe the right error displayed
3. Now add an incorrect query param and run. Observe the error displayed on the first run - error 5000
4. Re-run step 3 and observe the correct error displayed

### Environment

Release

### Version

Cloud

**Comment by AmanAgarwal041** [comment]
I tried replicating the issue, but seems the issue is already fixed.
Attaching the video : 

https://user-images.githubusercontent.com/7565635/170868481-1f7bdba8-ab07-43d1-8567-261a86931d20.mov

**Comment by ramsaptami** [comment]
Issue seems to be fixed hence closing this bug
