### ISSUE TITLE
[Task]: Create a Wikipedia page for Appsmith.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#9731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Almost all popular OSS projects have their own Wikipedia page. Appsmith should also have one. It will also help us with SEO.

**Comment by vj-codes** [comment]
@cokoghenun heyyo can I work on this?

**Comment by cokoghenun** [comment]
@vj-codes Sure! Go for it!

**Comment by Rishabhkaul** [comment]
Closing this. We will look into this later. The link has more [context](https://blog.hubspot.com/marketing/create-company-wikipedia-page)
