### ISSUE TITLE
[Bug]: New buttons are not center aligned in Vertical orientation for Button group widget

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

New buttons are not center aligned in Vertical orientation for Button group widget

https://loom.com/share/8533393c09de4f489fe99d094099985c

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/
2, Drag & drop Button group widget
3. In property pane change Orientation to 'Vertical'
4. Click on _Add new button_ and observe alignment of new buttons

### Environment

Release

### Version

Cloud

**Comment by techbhavin** [comment]
@shwetha-ramesh  Looks like this issue has been fixed. 

 I can’t create this issue in PROD.  can you please test it again?

cc: @somangshu  @Tooluloope 

https://user-images.githubusercontent.com/58818598/155140954-05e90f58-738f-4599-b607-6333267e0c0f.mov

**Comment by shwetha-ramesh** [comment]
@techbhavin This issue is not reproducible on release nor on prod. 
Closing it.
