### ISSUE TITLE
[Bug]: Hover action possible on disabled menu buttons in Button Group widget

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user disables one of the menu button which has a background color and later hovers over that menu button it is seen that the background color is visible on hover. 

https://loom.com/share/7087adefae6441e89143911aeb127151

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/
2. Drag and drop Button group widget
3. Go to settings of 'More'  button > Go to settings of 'Delete' menu item > Set disabled = true.
4. Now on the widget click on More and hover over Delete. 

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
not reproducible anymore

https://github.com/appsmithorg/appsmith/assets/94514895/add047fd-c0e0-47bd-90b9-1caaf84e21f3
