### ISSUE TITLE
[Bug]: The page order doesn't work as expected in page setting page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The page order doesn't work as expected in page setting page
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/244be42339854e0b9c47a0e616a81f3e-00001.gif)](https://www.loom.com/share/244be42339854e0b9c47a0e616a81f3e)
https://release.app.appsmith.com/applications/61b6f62066fa8b31464b0a33/pages/61b71d095440164c77e9f7f6/edit/pages

### Steps To Reproduce

1. go to page setting page
2. Try to reorder the page name from page setting page
3. The order doesn't work as expected

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty why is this issue marked low? Isn't this core functionality that is broken?

**Comment by RakshaKShetty** [comment]
@Nikhil-Nandagopal This issue i am facing in one of my app so i have kept the  priority as low

**Comment by somangshu** [comment]
Issue is resolved with new UX
