### ISSUE TITLE
[Bug] Redirect to login page after I've reset my password

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#974]

**Comment by akshay11298** [comment]
Hi @Nikhil-Nandagopal, if thia issue is still up for grabs, I'd like to work on it

**Comment by Nikhil-Nandagopal** [comment]
@akshay11298 go for it

**Comment by akshay11298** [comment]
Hi @Nikhil-Nandagopal @prapullac, for this I have updated the success message to "Your password has been reset. Redirecting to the login page" and removed the Login button. And I am redirecting after 1.5 seconds. Is this solution fine or should I do something else?

**Comment by akshay11298** [comment]
Hi, I have opened PR #1324 for this issue.
Screen recording is available at https://drive.google.com/file/d/1PfN8-nDNMbwdl5pibvNdudRJ_KRMwofB/view?usp=sharing

**Comment by Nikhil-Nandagopal** [comment]
Closing as we're now giving a CTA to login after reset
