### ISSUE TITLE
[Bug]: Unable to use optional chaining in query Params

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we use optional chaining syntax inside query params like `{{ this?.params?.val }}` it always becomes `undefined`

### Steps To Reproduce

1. Add a query with parameter
2. Pass some value via params
3. Add optional chaining syntax and see how it evaluates

### Environment

Production

### Version

Cloud

**Comment by hetunandu** [comment]
fixed with #9651
