### ISSUE TITLE
[Feature]: Introduce environment variables to map datasources between branches on Git connected apps

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#9757]

**Comment by AnaghHegde** [comment]
I guess we are not doing this at the movement. @hiteshjoshi We can close this right ?

**Comment by abhvsn** [comment]
We can keep this under product backlog, but don't close this as this is requested a lot of times by community members

**Comment by vuiets** [comment]
@rohan-arthur @parth-appsmith probably already discussed but will you be covering this as part of [#15455 | Multiple Environemnts](https://github.com/appsmithorg/appsmith/issues/15455)?

**Comment by rohan-arthur** [comment]
@vuiets yes, this problem statement is already in scope and we are working out the solution. Please feel free to close this issue

**Comment by vuiets** [comment]
Thanks @rohan-arthur! Was trying to understand if it's in scope. Will leave this open to collect community requests like @abhvsn suggests.

**Comment by trishaanand** [comment]
With multiple environments coming in, this shouldn't be handled as part of GIT. Closing this.
