### ISSUE TITLE
[Feature]: Add option to view response header in API pane

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be an option to view the response header of API requests so that it is easier for Appsmith developers to debug API issues.

### Why should this be worked on?

A user on discord requested this feature. Here's the [link](https://discord.com/channels/725602949748752515/760761686549463060/920272650960523274) to that thread.

User's use case: The Shopify API uses cursor based pagination and provides previous/next links in the response headers. There is currently nowhere to view this data without adding your own widget and binding it to the API's responseMeta.

**Comment by parth-appsmith** [comment]
@Irongade for this we can directly another tab to the response panel of the API pane to have a headers options.
We rename Response Body -> Body and add a header tab next to it on the panel.

Even for the smallest screen resolution of 1366x768 this should work.

![API Pane - Header Tab - 1366](https://user-images.githubusercontent.com/92779003/151340445-d679fb1a-1d6f-447f-bc02-b757b225d750.png)
