### ISSUE TITLE
[Bug]-[10000]:I am able to insert data with null value in a date field to postgres table from Appsmith. But when I retrieve a row in a modal form with a validate and then clear that date field and update to database its showing error

### ISSUE THREAD

**Issue by ginjojohny** [appsmithorg/appsmith#9767]
I am able to insert data with null value in a date field to postgres table from Appsmith. But when I retrieve a row in a modal form with a validate and then clear that date field and update to database its showing error.

![Screenshot (8)](https://user-images.githubusercontent.com/94359116/145940046-3d181604-da76-4173-b076-003e498acb4c.png)

_Originally posted by @ginjojohny in https://github.com/appsmithorg/appsmith/issues/9462#issuecomment-992305620_

**Comment by ginjojohny** [comment]
I tried with case method  in query like this but it also not working
![Screenshot (15)](https://user-images.githubusercontent.com/94359116/146002034-c9f0b839-5276-42da-ac0e-10e66e21cfcc.png)

**Comment by sumitsum** [comment]
Hi @ginjojohny can you please try by turning off the `use prepared statement` toggle and removing the qualifiers like `::timestamp` ?

**Comment by sumitsum** [comment]
@ginjojohny can you please mention what is the input that your are feeding for the timestamp field (`term_date`) when you try to update it ?

**Comment by ginjojohny** [comment]
Hi,

I am trying to update null value to the date field. also I tried by turning off the use prepared statement toggle and removing the qualifiers like ::timestamp.  I need to update date field as null when terminated client value is No.



________________________________

**Comment by sumitsum** [comment]
Hi @ginjojohny can you please tell what is the column type defined in the table for `term_date` field - is it the `DATE` type or the `VARCHAR` type ? Also, please mention your postgres version.

**Comment by ginjojohny** [comment]
Hi,

 The data type of date field is 'DATE' in my table.  And my postgresql version is postgre14.
________________________________

**Comment by rohan-arthur** [comment]
pg 6m usage: 2500
assume 50% requirement: 1250

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1250 |
| Effort (months)  | 0.25 |

**Comment by sumitsum** [comment]
The issue no longer seems to be applicable:
(1) Empty input widget does not return `null` anymore. It returns empty string. 
(2) Adding a JavaScript check in the mustache binding like this seems to address the problem now: `insert into typetestdate values ({{Input2.inputText ? Input2.inputText : null}});`

Thanks @PiyushPushkar02 for the [detailed analysis](https://www.notion.so/appsmith/PostgreSQL-Update-Query-Failure-cee3cd6fa8ed4525b5f7032080bd68f1). cc: @rohan-arthur
