### ISSUE TITLE
[Bug]: This function returns raw data when variable used is from a chained JS object

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a variable defined in a JS object and then bound to a widget which in turn is used in another JS object using this causes raw data to be returned and not actual value

![image](https://user-images.githubusercontent.com/79509062/146130550-590736d3-8848-4414-b9af-fc7ba65f48a7.png)

### Steps To Reproduce

1. Create an array of values for a `select widget` on `JS object` (or any other multi-select widget)
2. Bind this to a `select widget`
3. Assign selected value/label to a global variable in another `JS Object`
4. Use `this` to display/process data and observe raw data being returned inside mustache brackets `{{ }}` instead of actual value

### Environment

Release

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/9779?planning-poker) with ZenHub @ApekshaBhosale
