### ISSUE TITLE
[Bug]: Server detects cyclic dependency incorrectly in some cases 

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#9780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following scenario would trigger incorrect detection in server.

widgetname : widget1.
Text1.text : {{ Api1.data.widget1 }}

This should be something we also make note of for converging parsing rules in client and server.

### Steps To Reproduce

Same as above

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
I don't see a cyclic dependency error when assigning value like above to a widget property anymore. Maybe got fixed with some other issue.
