### ISSUE TITLE
[Bug]: Input widget expansion cause UI discrepancy

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Stretching Input widget to move label to the top causes widget to overlap with another widget if there's less space and highlighted boundary is not aligned to the actual boundary

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/69d295d5e80f48c6a3927bb82e0587eb-00001.gif)](https://www.loom.com/share/69d295d5e80f48c6a3927bb82e0587eb)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@wmdev0808 this is related to #7064 and should be taken up in the current scope

cc @dilippitchika

**Comment by ramsaptami** [comment]
Widgets can still overlap

https://www.loom.com/share/9eb0358e906e4b84a9901607b33b69e6

**Comment by wmdev0808** [comment]
@ramsaptami ,
We've finally decided to allow overflow of the component out of widget bounds, so it's inevitable.
cc: @dilippitchika

**Comment by dilippitchika** [comment]
Please let this be open @wmdev0808, we will close this after we add dynamic height
