### ISSUE TITLE
[Bug]: Changes made to JS object just before toggling a tab undoes the change

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user is toggling between tabs and makes any change immediately before changing tabs, then the change is undone/reverted on it's on before the cursor shifts to the start of the object structure

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/98888f6bf296485aae066adc1f1c6881-00001.gif)](https://www.loom.com/share/98888f6bf296485aae066adc1f1c6881)

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami is this now solved?

**Comment by ramsaptami** [comment]
Unfortunately, AST changes have brought in parsing delay so this issue is very much present and needs prioritization as well, if possible. CC: @satbir121

**Comment by bharath31** [comment]
@ApekshaBhosale could you add an RCA here?

**Comment by ApekshaBhosale** [comment]
@ramsaptami isn't this across Appsmith for all entities? I remember we wanted to make this different issue which includes all entities. can you please check that and update accordingly?

**Comment by ramsaptami** [comment]
I'm unable to reproduce this issue. Are you'll able to see this on your end @bharath31 @ApekshaBhosale

**Comment by bharath31** [comment]
@ramsaptami could you share some browser logs? 

@ApekshaBhosale could this be related to the update issues discussed [here](https://www.notion.so/appsmith/JS-object-functions-update-issues-4ba13b7c47de47e8b1f39f162cbf6df8)?

**Comment by ramsaptami** [comment]
I have see this happen on both release and DPs the past few weeks but have so far been unable to capture logs cause this happens quite unexpectedly and I haven't had devTools open then.
I'll update this thread with logs once I'm able to successfully capture them

**Comment by bharath31** [comment]
this is no longer reproducible
