### ISSUE TITLE
[Bug]: Release does not load without clearing the browser cache

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://release.app.appsmith.com is working only after clearing the browser cache

{"responseMeta":{"status":500,"success":false,"error":{"code":500,"message":"Internal Server Error"}}}

### Steps To Reproduce

Try to load https://release.app.appsmith.com without clearing cache

### Environment

Release

### Version

Cloud

**Comment by nidhi-nair** [comment]
This should be fixed after the migration ran on release, closing this till we have any further issues reported.
