### ISSUE TITLE
[Bug]: Release Notes modal improvements

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#9789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The position of the title, the close button seems wrong. There’s no indication to the user that there’s more text below the scroll.

### Steps To Reproduce

1. Goto home page
2. Click on "What's New"
3. Check the modal

### Environment

Production

### Version

Cloud

**Comment by albinAppsmith** [comment]
Display the first 3 updates then adding a gradient overlay from white to transparent for the rest of content with a read more that will expand the content and increase the vertical scrolling

**Comment by rohan-arthur** [comment]
@albinAppsmith I created a long modal with lot of widgets so that I should see a vertical scroll - I see the scrollbar in the edit mode, but not in view mode. Is this known and shall I create a separate issue for this?

**Comment by albinAppsmith** [comment]
@rohan-arthur  This is related to widget if I understood correctly. So yes please create a separate ticket for this.
