### ISSUE TITLE
[Feature]-[72.47]:Add a way to change font weight in button widget

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#9792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I was trying to replicate this section of the blog ( https://www.appsmith.com/blog/write-more-code-create-reusable-functions-with-our-new-javascript-editor ):

Blog:
![image](https://user-images.githubusercontent.com/6636360/146148800-f4b906ca-86f2-4c52-a23b-4adc92dd4ee0.png)

But couldn't increase the font weight of the button.

Editor:
![image](https://user-images.githubusercontent.com/6636360/146149824-abb3af85-d854-45de-8776-a912e30d2343.png)
So having a font-weight option would be a good option.

### Why should this be worked on?

Sometimes buttons may need a different font-weight other than the default one and currently, there is no option to update it.

**Comment by dilippitchika** [comment]
Discussed with @momcilo-appsmith moving this to icebox, because this is a primary use-case for buttons in websites but not in Internal apps.

**Comment by somangshu** [comment]
Also because the font-weight as a property should be first thought of holistically such that we dont create issues like before with the variants.

**Comment by jsartisan** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 72.47 |
| Effort (months)  | 0.5 |

**Comment by jsartisan** [comment]
Closing as not relevant anymore.
