### ISSUE TITLE
[Feature]: Configure env variables on Kubernetes using values.yml or ConfigMaps 

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#9798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, to bring up a new Appsmith instance with custom Redis/MongoDB/other configs on a Kubernetes cluster with Helm, we have to do a vanilla installation, and then configure these things. There's is no way to configure these at resource provision time.

If these were configurable from Helm's `values.yaml` or a Kubernetes `ConfigMap`, this would be possible and the configuration would be more portable.

### Why should this be worked on?

Having this would allow starting a new cluster without every running an embedded Redis or MongoDB, making it much more convenient.

**Comment by bastianb** [comment]
I think that most of the work is done on the [kubernetes deployment](https://github.com/appsmithorg/appsmith/tree/release/deploy/k8s) thanks to fromEnv and configMap - I am testing it as I wrote.
I believe that the chart should use the same templates as those - and get ride of the all-in-one (appsmith, mongo, redis etc) image that uses supervisord.

**Comment by sharat87** [comment]
Hi @bastianb, thanks for sharing. The all-in-one (or the fat image) is the newer Docker image that was created to make it easier and simpler to get started with running an Appsmith instance. You can read more about the reasoning here: <https://github.com/appsmithorg/appsmith/issues/9592#issuecomment-986711308>.

I think what's needed here is to be able to specify an external MongoDB and external Redis before the provisioning happens, and when this is done, the fat container _doesn't_ run an embedded MongoDB or Redis at all. At that point, it's not very much different from these slim containers, if you'll excuse the wording.

**Comment by bastianb** [comment]
it adds so much complexity and more breaking points, but I agree that it is a good starting point for new comers. Also the image end up with unnecessary packages if one does not use them making it heavier.
Do you plan in the longterm to remove those "slim" images? I am asking in order to know if what I am doing will be deprecated in the future.

**Comment by sharat87** [comment]
They aren't deprecated today, but unfortunately, I can't promise that that'll be the case in the future. We don't have a plan right now on when they will be deprecated, but it's not off the table yet. Sorry for not able to provide a more concrete answer on this.
