### ISSUE TITLE
[Bug]: Table breaks with new data for a user

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#9802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A user's app is broken

### Steps To Reproduce

1. Open the app https://app.appsmith.com/applications/61b9da60c70f2742893b91aa/pages/61b9da60c70f2742893b91ac?isCommentMode=false
2. Toggle the switch between the table data
3. The app does not show data even though the data is valid
4. This works in edit mode

### Environment

Production

### Version

Cloud

**Comment by sbalaji1192** [comment]
@somangshu @Nikhil-Nandagopal @dilippitchika It seems like we have made an assumption in the table widget that the schema of the tabledata will remain the same in view mode. we were not updating a bunch of computed properties in the table widget state (columnOrder, primaryColumns, etc.) in view mode. So I have provided a fix to remove that assumption.

**Comment by somangshu** [comment]
@sbalaji1192 can we merge this now?

**Comment by sbalaji1192** [comment]
@somangshu Working on the cypress test case issue. Can merge by today.

**Comment by sbalaji1192** [comment]
@Aishwarya-U-R I'm seeing some failure on the CI test case I wrote along with the fix. Could you help me resolve this?
My changes are available on `fix/table-computedvalues-view-mode`
