### ISSUE TITLE
[Bug]: AWS AMI has too small root partition size

### ISSUE THREAD

**Issue by gokuatkai** [appsmithorg/appsmith#9809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When launching an instance with the appsmith latest AMI the disk run out of space after few minutes. The default size is 8GB for root.
I expect the AMI default root partition to have a default size which at least allow me to run the application.
After testing, it seems that 10GB should be plenty enough. Some people might want to increase it if they are not using external databases.
This does not count the fact that old versions of the application docker image might not be removed from the docker image store. (I can see that latest AMI holds 3 docker image versions) - but I disabled auto-update, as its by default turn on and not suitable for production usage.

### Steps To Reproduce

1. launch an instance with the AWS AMI
2. logging and run df to check disk usage

### Environment

Production

### Version

Self-Hosted

**Comment by aswathkk** [comment]
Thanks, @gokuatkai for reporting this

We are looking to fix the default AMI settings so that you don’t run into the disk space issue. In the meantime, here’s a video on how to circumvent it by defining a larger disk during startup time itself: https://www.loom.com/share/ea41d08798304295a571b64d818a39a9.
The change is that you need to use the EC2 console instead of the “website” option to launch the AMI. This gives you more control over the settings.

**Comment by gokuatkai** [comment]
thanks, I use terraform to deploy our AWS stacks. So this was not a problem for me to change the size. I was just expecting it to be adequate. The version is as well misleading, it says 1.3.5 on the AMI while in fact it is the latest docker image: v1.6.2 at this day.

**Comment by sharat87** [comment]
Hey @gokuatkai, yes the AMI version is separate from the Appsmith / Docker image version. The AMI will just get the latest Docker image to run, irrespective of what the AMI version is. The AMI version is only incremented when we push fixes to the AMI itself, for things like security updates for the software in the image, or bug fixes in the setup flow etc.

**Comment by EmreKspToken** [comment]
EmreKspToken
