### ISSUE TITLE
[Bug] The hidden column list is not bounded and overflows in height

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#981]
## Steps
1. Drag a table
2. Add many columns to the table data
3. Click on the column visibility option in the table
4. A very large list of columns is displayed

## Expected
The list of columns should have a bounded height and scroll

**Comment by A-Scratchy** [comment]
Happy to do this one if you would like to assign :-)

**Comment by mohanarpit** [comment]
@A-Scratchy Good to hear you got the setup running on your system. This issue is yours for the taking! 🎉
