### ISSUE TITLE
[Feature]-[586]:There should be an option to resize image inside Table widget

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We should be able to set the height and width of the image inside table widget

### Why should this be worked on?

The ability to provide height and width to images inside the table will give the images more visibility.

**Comment by somangshu** [comment]
@aswathkk this can be implemented once we figure out the dynamic height of row in the new table widget

cc @riodeuno

**Comment by momcilo-appsmith** [comment]
@aswathkk Can you provide an example where this would be useful?

**Comment by momcilo-appsmith** [comment]
@aswathkk @dilippitchika @somangshu Can you provide an example where this would be useful?

**Comment by aswathkk** [comment]
<img width="727" alt="Screenshot 2022-04-18 at 12 51 59 PM" src="https://user-images.githubusercontent.com/10436935/163771981-8109226e-dc38-44de-8454-74a361d4df16.png">

@momcilo-appsmith In this table, **it's hard to see the image** properly since it is small. The maximum height possible for an image inside the table is 28px.

**Comment by dilippitchika** [comment]
@momcilo-appsmith this is a good issue to pick up for design, if you have used word-wrapped table which Balaji created with images you can see how this behaves today after updates.

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 220 |
| Effort (months)  | 0.75 |

**Comment by momcilo-appsmith** [comment]
The way I am thinking to go about this is to either:

- Have a set of defined values for the width or
- Have a custom width field

**Comment by somangshu** [comment]
@momcilo-appsmith should this also involve a max-width baed on the table cell dimension?

**Comment by momcilo-appsmith** [comment]
@somangshu At first I thought that it shouldn't because of cell wrap, but then you won't be able to define width if you don't.
I think the answer to your questions is NO.

**Comment by dilippitchika** [comment]
Yeah, i also thought the same that we give default sizes for the images like Small, medium, Large and in the JS option user can define the height of image in px if they wish to. 

The challenges i see are 
- Each image can be of different dimension, so having a fixed set of values may cause some other problems like another column getting wrapped. 
- Defining the default sizes themselves

**Comment by momcilo-appsmith** [comment]
@dilippitchika I think letting them choose from one of the sizes we set is the way to go. Is there a way we can enable people to zoom in the picture?

**Comment by dilippitchika** [comment]
We can i guess, but it has to happen in a popover like scenario. @momcilo-appsmith can you assign someone to research and create a design brief for this problem?

**Comment by andrewdietekoki** [comment]
@dilippitchika

**Comment by andrewdietekoki** [comment]
Design: https://www.figma.com/file/nTMtrnQJUsso2Ud6m8UPqW/Resize-Image-Inside-Table-Widget?node-id=459%3A4159

**Comment by dilippitchika** [comment]
## PRD 
### Story
When adding images in appsmith tables, i want to manage the size of the images so that i can show images better to my users

### Design flow
- When user selects an image col in the table widget, they will now see options for predefined image sizes. 
- One of these would be default, which inherits data from row height set. Meaning when default is selected the image will follow default row height
- Other than that we have options for medium and large which are fixed cell sizes to show images. When any of these are selected, the row wraps to reach these sizes.
- Images can be of multiple sizes, by fixing the height we are allowing for changes in width only to maintain the same aspect ratio

**Comment by andrewdietekoki** [comment]
@dilippitchika 
Updates:
- What will happen when cell wrap is on?
https://www.figma.com/file/nTMtrnQJUsso2Ud6m8UPqW/Resize-Image-Inside-Table-Widget?node-id=475%3A7903
- What will happen when Image Column width is reduced?
https://www.figma.com/file/nTMtrnQJUsso2Ud6m8UPqW/Resize-Image-Inside-Table-Widget?node-id=476%3A8753

**Comment by dilippitchika** [comment]
All items are resolved. Moving this to PRD/Design done phase
