### ISSUE TITLE
[Bug]: Rich Text Editor is blank and cannot be loaded

### ISSUE THREAD

**Issue by edyou2021** [appsmithorg/appsmith#9816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**normal circumstances：**
![image](https://user-images.githubusercontent.com/95668397/146319284-a1a67115-0c8e-41e7-98dd-54dcd9e6f665.png)
**false imagination：**

![image](https://user-images.githubusercontent.com/95668397/146319841-a67b086b-5221-45c0-9bac-7b6f6fef033f.png)

### Steps To Reproduce

Sometimes when you open a page, the rich text edit box is blank

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@edyou2021 can you please share the steps to reproduce the issue?
