### ISSUE TITLE
[Bug]: Unable to filter by empty conditions in Google sheets

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#9824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On trying to apply a where condition on Google sheets to search for an empty value, the plugin responds with an error.

### Steps To Reproduce

Create a `Fetch sheet rows` request with a condition like `"columnName" == [empty_value]`

### Environment

Production

### Version

Cloud

**Comment by rishi-mittal-web** [comment]
Following

**Comment by rohan-arthur** [comment]
played around with this a bit, and found this:

[== ''] does not work
however:
[> ''] works

interestingly, [< ''], [<= ''], etc also don't seem to work.


With the above information, it might be possible to proceed with a hack while we wait for the fix:

Here is my data in google sheet:
<img width="417" alt="Screenshot 2021-12-17 at 2 24 15 PM" src="https://user-images.githubusercontent.com/94514895/146517109-40d90d90-9f90-4f2c-a294-90db7ffae7ad.png">

I want to get all customers who don't have an email address.

1. Create query to get all customers (i.e., no WHERE condition)
2. Create query to get all customers who have email address maintained (i.e, WHERE condition "Email > '')
3. get the differences between query1 and query 2, there are two ways I can think of:
    a. operate on the response objects, compare programmatically in JS where required
    b. write a third query with WHERE condition "Not in {{GetWithEmails.data.map(a => a.ID)}}"

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by leotom2000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BE-Coders-Pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/9824?planning-poker) with ZenHub @nidhi-nair @sumitsum

**Comment by leotom2000** [comment]
Code updates done to resolve the above issue and PR raised with the following resolution
To fetch data from Google Sheet with empty where condition, ie with no entry in Where Conditions, value field

**Features/Scenarios implemented and Tested regarding the values in the condition:**
1. When Value is Empty "" - Pass
2. When Value is Null null - Pass
3. When Value is Space " " - Pass
4. When Two conditions are "" - Pass
5. When Two conditions are null - Pass
6. When one Condition is Null and other empty - Pass
7. When both has value - Pass
8. When both condition are empty - Pass
9. Test for EQ with empty / Null / with_value - Pass
10. Test for 'IN' for with empty / Null - Pass
11. Test for 'NOT_IN' with empty / Null - Pass
12. Test for combination of EQ / IN / NOT_IN - Pass

Note : The UI will sent null, when we do not touch the field (ie Mouse down/Click), at present it is handled in the backend by capturing the nulls.
We may need to fix that in the front end, for which I will create another ticket.
