### ISSUE TITLE
[Bug]: Incorrect focused state while dragging the column sequence in table widget

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#9826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to change the sequence of columns for the table widget then the focus state does not appear for the column which was dragged but instead the column above the dragged one gets focused. 

Below video demonstrates this behaviour:

https://user-images.githubusercontent.com/14138515/146379775-fb01c6d5-0f41-4d7c-8e57-ee62badf6f4e.mp4

The above video will also demonstrates that it appears to happen in both the ways i.e. dragging from top to bottom or bottom to top.

### Steps To Reproduce

1. Drag and drop the table widget on the canvas.
2. Under the columns property of the table widget, try to change the sequence by first clicking the textfield to edit the row label, then drag the clicked row(mouse down state) down.
3. Similarly, try to move a column up in the sequence.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@keyurparalkar please add labels to issues!

**Comment by keyurparalkar** [comment]
> Great catch @keyurparalkar. How did you notice this?

@dilippitchika I was working on another issue: #9188 Over there I noticed this issue.

**Comment by somangshu** [comment]
Good Catch @keyurparalkar, lets take this up with the current errort 👍

**Comment by vicky-primathon** [comment]
The fix for this issue is there in PR https://github.com/appsmithorg/appsmith/pull/10046
