### ISSUE TITLE
[Feature]: Expose Filtered table data in Table widget

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be a way for the users to access the filtered table data and custom made columns.
As of now, there's only one way to read data from table that is via `{{ TableName.tableData }}` which is the data that is coming to Table widget's "Table Data" field.
We need to expose some other fields that have the custom column data and that should change if we filter the table.

### Why should this be worked on?

With this, we will be able to do some operations based on table data.
ex:
Compute the sum of a custom column based on applied filters using
```
{{ myTable.tableData.map(x => x.customColumn).reduce((a, i) => a + i, 0) }}
```

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @aswathkk this works today. Can we please just expose it in the autocomplete as mentioned in #8911
{{data_table.filteredTableData}}
