### ISSUE TITLE
[Bug]: Radiogroup not working for Id->String values

### ISSUE THREAD

**Issue by paulochang** [appsmithorg/appsmith#9834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Default selected value is only pre-selected if the Options values are specified as strings. 
<img width="810" alt="image" src="https://user-images.githubusercontent.com/4237241/146431291-0ab1aade-8bb2-49c7-ab24-619b80a1a46b.png">

Notably, the select widget does allows int to string mapping and behaves as expected, so it can effectively be used as a workaround if string mapping is not possible

<img width="780" alt="image" src="https://user-images.githubusercontent.com/4237241/146433673-fa62edec-f5ac-4537-9f28-15c4034cb197.png">

### Steps To Reproduce

Set the radio group items as a label-value as a string->integer map  as follows:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/4237241/146431181-12675ad4-37c8-4c81-bdff-93be047d8b17.png">

You'll notice that the radio group has no pre-selected item

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
The problem here is very similar to the select widget where the default data is automatically treated at string. 

We should treat the value type as is to resolve the problem. @SatishGandham please correct me if I am wrong.

**Comment by paulochang** [comment]
@somangshu I think this is actually why the select widget always works.. you throw it a string.. or a number or anything... and it always converts it to string so you can always match... unlike the radiogroup which will probably take the value as is.. and sometimes it will be an integer and sometimes a string... so it doesn't match.. even though for most purposes 3="3"

**Comment by somangshu** [comment]
You are right. The default value is always an integer until you use the mushtach barceses. We will keep you posted for the right solution we are going to opt. Thanks for the additional context

**Comment by keyurparalkar** [comment]
To solve this issue, we have decided to go with keeping value present in the default selected value to be evaluated to integer if it's mushtach binding. We will also change the expected type and example in the evaluated value popup.

CC: @somangshu @dilippitchika @Nikhil-Nandagopal

**Comment by somangshu** [comment]
@riodeuno FYI, Here we are changing the checking the dataType from the first object in the options collection and based on that deciding weather on change we should parse the value to return, Is this the right way?

**Comment by riodeuno** [comment]
@somangshu Here, **_if_** the `value` properties can be of different type in different entries, then we may have issues making assumptions based on the first entry. There will be other issues as well, for example, where "1" and 1 can both be valid values. What would an Appsmith developer provide as the `default` in this case? 

So, we might want to validate this as well, for integrity.

In other words, the ideal way in which -- the combination of options and default value -- may work

- [ ] The data type of `value` properties in the options are consistent (enforced via validations)
- [ ] default values are considered to be of the same type as the values. The approach you mentioned works.

**Comment by somangshu** [comment]
@keyurparalkar @sbalaji1192 need inputs from you guys on the above

**Comment by keyurparalkar** [comment]
@somangshu I think we should go with option 2. Were we consider default values to be of the same type as values
What do you think @sbalaji1192 ?

**Comment by sbalaji1192** [comment]
@keyurparalkar @somangshu Let's go with @riodeuno suggestions. We will enforce that all values data type is equal and then we infer the type from the first option to get the default value type.

**Comment by somangshu** [comment]
cc @dilippitchika keeping you in the loop
