### ISSUE TITLE
[Bug] On Deleting an tab user is displayed with an error message

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#984]
https://www.notion.so/On-Deleting-an-tab-user-is-displayed-with-an-error-message-a470e90974f249aca4730092f65c96f7

**Comment by riodeuno** [comment]
@vivekverma2312 Please verify if this issue still exists.

**Comment by vivekverma2312** [comment]
@riodeuno It's working fine now. Not able to repro the issue.
