### ISSUE TITLE
[Bug]: watchPostion() and clearwatch() take long to execute a trigger

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Geolocation API endpoints `watchPostion()` and `clearWatch()` take a long time to run when triggered leaving button (or any other widget that is triggering the action) to remain in loading state for long. More number of times these are triggered and stopped, the longer the processing is each time.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ade361368dac44fd9d80a319f0912c60-00001.gif)](https://www.loom.com/share/ade361368dac44fd9d80a319f0912c60)

### Steps To Reproduce

1. Use button widget to trigger location watch for user
2. Observe the behavior when using `watchPostion()` and `clearPosition()` in tandem 
3. Bind these to a map widget and trigger them again
4. Repeat above steps and observe the duration to execute these actions

`clearWatch()` takes time even on a new app - but once the number of widgets/binding increases then the time taken to execute both these actions increases as well.

### Environment

Release

### Version

Cloud

**Comment by ajinkyakulkarni** [comment]
Hey @ramsaptami , noticed that you are writing a binding inside a binding. Maybe the issue is happening because of that?
![image.png](https://images.zenhubusercontent.com/608fba85753b215e60bd4c31/4f5b6fd3-8cbf-49c8-895e-30f45da4a40c)

**Comment by ramsaptami** [comment]
Unable to repro this even after removing the nested binding hence closing this issue
