### ISSUE TITLE
[Bug]-[600]:Incorrect error handling when location access is turned off and `watchPosition()` is triggered more than once

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Incorrect error handling when location access is turned off and `watchPosition()` is triggered more than once

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2b8eb1cd58434179902cbc21a9b420e4-00001.gif)](https://www.loom.com/share/2b8eb1cd58434179902cbc21a9b420e4)

### Steps To Reproduce

1. Turn off browser location access and trigger `watchPosition()` from Geolocation API - first error is correct
2. Trigger it again and observe an error stating watch position is already running. Enable location access and observe that watch position is not tracking location - it needs to be triggered again in order to read user location details.

### Environment

Release

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
If 25% of users face this error
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 75 |
| Effort (months)  | 0.25 |

**Comment by satbir121** [comment]
@ramsaptami Tested this with:
```

{{appsmith.geolocation.watchPosition((location) => {
	showAlert("abc " + Math.random());
	console.log(location);
	setTimeout( () => {
		console.log("Clearing")
		showModal("Modal1")
		Api1.run({"id": 12})
		appsmith.geolocation.clearWatch()
	}, 10000)
}, (error) => {
	Api1.run({"id": 15})
	showAlert("error " + Math.random());
	showModal("Modal1")
	console.log(error);
},{})}}
```

And 
```
{{appsmith.geolocation.getCurrentPosition(() => {
	Api1.run({id: 15});
	showAlert("abc " + Math.random())
	setTimeout(() => {
		showModal('Modal1')
	})
}, (error) => {
	Api1.run({id: 15});
        console.log("ERROR",error)
	showModal("Modal1")
	showAlert("Error " + Math.random());
})}}
```
