### ISSUE TITLE
[Bug]: Switching between JS and toggle for visible property make the widgets in list widget invisible

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#9853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/da0d8191395f4be9bff614713bbf15c3-00001.gif)](https://www.loom.com/share/da0d8191395f4be9bff614713bbf15c3)

### Steps To Reproduce

1. Drag and drop the List widget
2. Toggle the visible property
3. Click on JS
4. Enter some JS condition and switch between JS and toggle
5. Observe the widgets inside list widget gets invisible

### Environment

Release

### Version

Cloud

**Comment by Tooluloope** [comment]
Cant reproduce this issue
