### ISSUE TITLE
[Bug]: Vertical scroll in embed mode

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#9858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's a scroll that's appearing on pages in embed mode even when there aren't a lot of widgets in the page.
The default page height seems to be fixed and doesn't resize even when the page is empty.

### Steps To Reproduce

1. Add one widget
2. Try to embed it
3. See a scroll appear even when there are no widgets that warrants a scroll

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@YogeshJayaseelan can you please verify this and add a screenshot to the issue

**Comment by YogeshJayaseelan** [comment]
@somangshu Didn't observe any vertical scroll when only one widget is added 

<img width="1680" alt="Screenshot 2022-01-07 at 3 32 37 PM" src="https://user-images.githubusercontent.com/35128442/148527615-d2d620a1-9dfe-44a3-b519-3ebdb8c301fc.png">

**Comment by YogeshJayaseelan** [comment]
@somangshu @marks0351 Tested this in embed mode and vertical scroll is displayed when only one widget is placed - Refer the video below

https://www.loom.com/share/09c8b504e1194f9eab09eaa92fea4e77

**Comment by chandannkumar** [comment]
Tested and saw there is no vertical scroll after fix
https://www.loom.com/share/041d0b1910b84822a665960078424853

**Comment by ioalloc** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Tooluloope** [comment]
Reopening cause of https://github.com/appsmithorg/appsmith/pull/11424

**Comment by somangshu** [comment]
@techbhavin @chandannkumar please take note of this, this cause many user to frown, we need to be extremely careful in these scenarios.

**Comment by rahulramesha** [comment]
Re opening this issue because of the reverting changes in #11674

**Comment by somangshu** [comment]
@jsartisan can you link it to the current PR that fixes this

**Comment by jsartisan** [comment]
Closing as done

**Comment by srichint1** [comment]
I think VSB is still appearing even for a single widget and deployed / preview mode.
Please check attached image and let me know how this can be resolved.
![appsmith_iframe_VSB](https://github.com/user-attachments/assets/29206c76-e574-4da1-9742-9480f5262ca0)
