### ISSUE TITLE
[Bug]: OnPageLoad Query not working when widget/Query name and data binding key name are same

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#9864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For a user application shared on discord 

http://95.217.192.133:82/applications/6193655e2c16ce420ad195cd/pages/6198d7792c16ce420ad19656/edit?id=3

This particular page should logically have `layoutOnLoadActions` but when checked in the page response found layoutOnLoadActions as an empty array.

### Steps To Reproduce

Quoting @mohanarpit 

"There is a known edge case where if any widget is bound to a data field with the same name, the server thinks there is a cyclic dependency. This is because the server doesn’t yet do an AST (which the client has started to do).
Eg: Widget Name: monitor_name
Binding: {{ Api1.data.monitor_name }}
This will cause issues. Not the easiest thing to fix right now without introducing AST parsing of JS bindings on the server."

### Environment

Production

### Version

Self-Hosted

**Comment by Rishabh-Rathod** [comment]
Another user has a similar issue.

Application link - https://apps.gc-silo.com/applications/61aa315446fa5a327584fc17/pages/61bdc308499d7a1a42467fb2/edit

(use support@appsmith.com)

Here also onPageLoadActions for the particular page is sent as an empty array.

**Comment by Rishabh-Rathod** [comment]
Quoting @mohanarpit 

"There is a known edge case where if any widget is bound to a data field with the same name, the server thinks there is a cyclic dependency. This is because the server doesn’t yet do an AST (which the client has started to do).
Eg: Widget Name: monitor_name
Binding: {{ Api1.data.monitor_name }}
This will cause issues. Not the easiest thing to fix right now without introducing AST parsing of JS bindings on the server."

**Comment by Rishabh-Rathod** [comment]
One more user faced this issue, users on page load query were not working because of widget name and JS data binding having the same name.
https://discord.com/channels/725602949748752515/760761686549463060/958134814316318740

**Comment by ame-appsmith** [comment]
Another user reported this issue here: https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100158334#part_id=comment-164629100158334-16277489045
