### ISSUE TITLE
[Bug] On Date Selected should not be called when date is de-selected

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#987]
When a date is de-selected in the Appsmith application, the date widget ends up calling the `onDateSelected` event. This should not be the case. `onDateSelected` should only be fired when a date is selected by the user.

**Comment by spielers** [comment]
Hey @Nikhil-Nandagopal , I would like to work on this please assign me this

**Comment by mohanarpit** [comment]
@spielers It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, check out the [Appsmith Challenge](https://github.com/appsmithorg/appsmith/discussions/863) where you can win some cool swag by inviting your friends to contribute to this project as well.

**Comment by satbir121** [comment]
@spielers Any updates?

**Comment by spielers** [comment]
Yeah  work still is in draft mode . I'll try to complete asap

Thanks

**Comment by Nikhil-Nandagopal** [comment]
@spielers please link the PR to the issue

**Comment by Nikhil-Nandagopal** [comment]
@spielers  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!
