### ISSUE TITLE
[Bug]-[8000]:JSON.parse fails in List Widget, needs escaping special chars like single quotes and \r

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#9872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1187" alt="Screenshot 2021-12-20 at 3 13 28 PM" src="https://user-images.githubusercontent.com/23132741/146746629-a3b7dbff-674a-42f3-a478-d240fd215212.png">

<img width="1182" alt="Screenshot 2021-12-20 at 3 14 25 PM" src="https://user-images.githubusercontent.com/23132741/146746745-bff832a3-a0ea-49f2-b813-2243bc9c0981.png">

```js
originalBinding - "((currentItem) => { navigateTo(currentItem.task, {})})(JSON.parse('{"step":"#1","task":"Drop a t'able","status":"✅","action":"'"}'))"
```

Whenever data has a single quote in it, `JSON.parse`,
root cause 
```js
// In ListWidget/widget/index.tsx line no. 461
  `{{((currentItem) => { ${next}})(JSON.parse('${escapedStringifiedListItem}'))}}`
  
  // here we have single quotes
```

### Solution

1. Either change the way listWidget access its currentItem or 
2. Escape the single quotes and after JSON parsing unescape them.

### Steps To Reproduce

1. Add list widget to canvas and add a button to the item.
2. List widget options = 
```
[
  {
    "step": "#1",
    "task": "Drop a t'able",
    "status": "✅",
    "action": "'"
  },
  {
    "step": "#2",
    "task": "Create a query fetch_users with the Mock DB",
    "status": "--",
    "action": ""
  },
  {
    "step": "#3",
    "task": "Bind the query using => fetch_users.data",
    "status": "--",
    "action": ""
  }
]
```
3. Add onClick of button `{{navigateTo(currentItem.task, {})}}`
4. Click on button and see the issue

### Environment

Production

### Version

Cloud

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_56b2k)

**Comment by Rishabh-Rathod** [comment]
https://github.com/appsmithorg/appsmith/pull/11525 with this PR, we won't have `JSON.parse` inside list widget and hence this issue will be resolved. 
cc: @hetunandu can you confirm this.

**Comment by rohan-arthur** [comment]
incidence of error `missing ) after argument list`, 6m: 1000
of these, ~400 encountered this error after first having placed a list widget on the canvas

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | <<number>> |

**Comment by dilippitchika** [comment]
Removing app viewers pod tags here
