### ISSUE TITLE
[Feature]: Support http-only S3 endpoint (i.e. Minio)

### ISSUE THREAD

**Issue by ondrejmo** [appsmithorg/appsmith#9879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow non-https endpoints for S3 data-source (same as is currently possible with Postgres).

### Why should this be worked on?

If an alternative S3 server such as Minio is be deployed in the same k8s cluster or on the same host, it is possible to access it securely without the need of TLS. Not being able to disable the usage of https in appsmith is an unnecessary complication.

**Comment by Nikhil-Nandagopal** [comment]
@ondrejmo thank you for the feature request!

**Comment by sumitsum** [comment]
This has been implemented and is available no prod and all self hosted instances. It is possible now to specifiy the full endpint along with the protocol ie. http or https when choosing the datasource type as Minio or other.
