### ISSUE TITLE
[Bug]: Migration seems to be broken

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#9885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to create apps while using same mongodb with release fat conaitner prod fat container

### Steps To Reproduce

Steps I followed.
Use latest prod fat container
docker run -d --name appsmith-master -p 80:80 -p 9001:9001 -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ce
Create fresh mongodb instance
docker run -p 127.0.0.1:27017:27017 --name appsmith-mongodb-fresh-temp -e MONGO_INITDB_DATABASE=appsmith -v /Users/yatinchaubal/mongodatadb_fresh_temp:/data/db mongo
In admin settings page change mongoldb uri to mongodb://host.docker.internal:27017/appsmith
Above step would restart app smith
Register and login
App creation is successful.
Stop appsmith instance
Start appsmith release instance. With mongoldb uri pointing to local mongodb://host.docker.internal:27017/appsmith
Login
App creation fails
Recorded video 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ad0b5675891d40e18611c3fb161d32f6-00001.gif)](https://www.loom.com/share/ad0b5675891d40e18611c3fb161d32f6)

### Environment

Release

### Version

Self-Hosted

**Comment by sharat87** [comment]
Hey @yatinappsmith, can you share logs from the Docker container when you saw this error please? I just tried but couldn't reproduce the error. Also, can you confirm if `docker pull appsmith/appsmith-ce` and `docker pull appsmith/appsmith-ce:release` were run before starting the two containers?

**Comment by yatinappsmith** [comment]
I delete both the containers and images before docker run. 
[Bug9885.txt](https://github.com/appsmithorg/appsmith/files/7749674/Bug9885.txt)
Below screenshot was taken at 21Dec2021 [10:23AM.]
<img width="896" alt="Screenshot 2021-12-21 at 10 23 28 AM" src="https://user-images.githubusercontent.com/84702014/146873683-f8a53df6-e56c-4a02-80a4-dcba2718ca26.png">
n

**Comment by yatinappsmith** [comment]
Hi @sharat87 , Added logs in above comment

**Comment by sharat87** [comment]
Thanks for sharing the logs! I see the following error in the logs:

```
java.lang.IllegalStateException: Unable to invoke Cipher due to bad padding
```

This error usually occurs when the wrong salt or password are being used when connecting to an Appsmith database. Are you using any particular dump of a database in your test? I ask because I see you already have a few applications in your organization.

The other way I think this can happen is if the two container you are using, the `appsmith-master` and `appsmith-release`, have different stacks folders. In that case, they would have different `docker.env` files, and so different salt and password. Can you share the `docker run` commands used to bring up these containers initially?

**Comment by yatinappsmith** [comment]
> Thanks for sharing the logs! I see the following error in the logs:
> 
> ```
> java.lang.IllegalStateException: Unable to invoke Cipher due to bad padding
> ```
> 
> This error usually occurs when the wrong salt or password are being used when connecting to an Appsmith database. Are you using any particular dump of a database in your test? I ask because I see you already have a few applications in your organization.
> 
> The other way I think this can happen is if the two container you are using, the `appsmith-master` and `appsmith-release`, have different stacks folders. In that case, they would have different `docker.env` files, and so different salt and password. Can you share the `docker run` commands used to bring up these containers initially?

release and master have different stacks folder
