### ISSUE TITLE
[Bug]: Tab widget needs to follow same style as container widget

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#990]
## Summary
The tab widget should have the same rounded corners that the container widget does

**Comment by imrishabh18** [comment]
@Nikhil-Nandagopal Can I work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@imrishabh18 go for it!

**Comment by satbir121** [comment]
@imrishabh18 Any updates?

**Comment by imrishabh18** [comment]
@satbir121 I will let you know when I complete it. A bit busy with stuff for a few more days.

**Comment by Nikhil-Nandagopal** [comment]
@imrishabh18 since you're currently busy I'm unassigning this issue so that it's still up for grabs. Feel free to come back to any of our many open good first issues 😄

**Comment by ShraddhaGeek** [comment]
Can I work on this issue?

**Comment by Nikhil-Nandagopal** [comment]
@ShraddhaGeek go for it!

**Comment by mohanarpit** [comment]
@ShraddhaGeek Are you still working on this issue? I'm asking because there hasn't been any activity on this issue.

**Comment by Nikhil-Nandagopal** [comment]
@ShraddhaGeek  I don't see a PR for this issue yet so I'm unassigning you from it. I understand something may have come up so feel free to come back to our open issues when you have a chance!

**Comment by sumanthyedoti** [comment]
I like to work on this

**Comment by Nikhil-Nandagopal** [comment]
@sumanthyedoti go for it!
