### ISSUE TITLE
[Bug]: Parse error gets cleared when JS object name is changed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a JS function is in error state and JS object name is changed then the parse error clears but running the previously errored function throws an error.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2a503d504092440c8b68feb763f5276a-00001.gif)](https://www.loom.com/share/2a503d504092440c8b68feb763f5276a)

### Steps To Reproduce

1. Cause a parse error on JS function then rename the object
2. Observe the parse error get cleared
3. Run the function from the watch window and observe error displayed

### Environment

Release

### Version

Cloud

**Comment by ApekshaBhosale** [comment]
@ramsaptami is this still happening?

**Comment by ramsaptami** [comment]
Seems to be fixed @ApekshaBhosale
