### ISSUE TITLE
[Bug]: Git Issues in release

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
- [x] Keep commit input empty by default instead add a placeholder, for the first commit post connection we might want to keep it as `Initial Commit` (@haojin111)
- [x] #10003
- [ ] #10536
- [x] Update message for contact message for intercom: (@haojin111)
  - `Hey there,
Thanks for getting in touch! We understand that you’d like to extend the number of private repos for your <Organisation Name>. Could you tell us how many private repos you’d require and why? We'll get back to you in a short while.` 
- [x] The update button should be similar to COnnect button for the consistence (@haojin111)->Fixed
- [x] The commit change tooltip retains when user click on + icon (@haojin111)->Fixed
- [x] #10517
- [x] The Appsmith server unavailable error is displayed instead of page not found when the user switch between the branch which has missing pages (@haojin111 )->Fixed
- [x] When the user creates a new branch in git in the appsmith application the new remote branch wont be displayed until the new branch is created in local->Fixed
- [x] When the user delete the branch from git and try to sync it the delete branch will still be displayed in the Application @AnaghHegde
- [x] The internal server error is displayed when the user checkout from the remote branch @AnaghHegde
- [x] when the user tries to click on local branch created from the remote branch the appsmith server is unavailable message is displayed @AnaghHegde
- [x] when the user select the local branch created from the remote branch for merging the change the null pointer error is displayed
- [x] The user configuration is not checked by default ->Fixed
- [ ] The user is able to connect 2different application same repo in bit bucket
- [x] The open repo link doesn't work for the bit bucket(in progress by @haojin111), (duplicated by #10216)
- [x] The disconnect flow doesn't work in release->fixed
- [x] #9989
- [x] #10004
  - [ ] ssh url input
  - [ ] ssh key box
  - [ ] conflicts found: (deploy / merge tabs and bottom bar popup)
  - [ ] disconnect popup
  - [ ] repo limit reached modal
  - [ ] error while connecting at the connection tab
  - [ ] push error: pending upstream changes at the deploy tab  
- [x]  When the user tries to add a new branch and clicks multiple times on the branch name the error is displayed and then the user is unable to switch on the new branch created(Disable the click action until we get the response from backend)(@haojin111 )
- [x] The Pull changes button shows infinite loading when there are a merge conflict(@haojin111)
- [ ] When the users are in the same branch the multiple Cursors are displayed
- [ ] The page count is wrong in the deploy tab 
- [ ] When Multiple users tries to merge the changes at the same time the error is displayed in the merge tab
- [x] When the merge is not successful the error message should be displayed(@haojin111 )
- [x] Some time user tries to merge the changes metadat.json error is displayed
- [x] If 2 users create a branch at the same time internal server error is displayed
- [x] Replace the ID with Readable slug  (this should be a part of clean URLs project)
- [x] The new Deploy key should autogenerated when user change the remote URL(@haojin111)
- [x] Invalid URL or page has no data error is displayed on the Canvas
- [x] The wrong error message is displayed when user tries to connect to git without adding a deploy key (@AnaghHegde)
- [x] #10216
- [x] #10217
- [x] #10333
- [x] #10354
- [x] User is unable to delete the imported curl api
- [x] #10537
- [x] The git Icon retains even after deleting the connection(@haojin111 )

The issue which came up after the new changes done

- [x] When the user creates a new branch Until we refresh the browser i won't be able to see the branch(local branch)
- [x] When we create a new remote branch Until we refresh the browser i won't be able to see the branch
- [ ] When we commit and push it take a lot of time  to complete the action (i am comparing it with the previous release) same goes with the merging
- [x] The user should not be allowed to click multiple times on the same Remote branch
- [ ]When user update the page name the count is displayed as “2page updated” instead of 1

### Steps To Reproduce

1. Connect your application to git and check for the above issues

### Environment

Release

### Version

Cloud

**Comment by RakshaKShetty** [comment]
Adding few more new issues 

- [ ] When the user do a curl import the user is not able to rename the API 
- [ ] when the user bind curl imported data into a text widget the then in the deployed version the user is not able to see the Data 
- [ ] the page is not selected by default in this scenario its difficult for user to switch the branches
- [ ] The invalid URllimage is displayed on the canvas
- [ ]

**Comment by abhvsn** [comment]
@RakshaKShetty we are following the above issues under #10637

**Comment by rishabhsaxena** [comment]
- [ ] Hide bottom bar in the preview mode
- [ ] Allow multi line commit messages

**Comment by AnaghHegde** [comment]
Lets close this issue? We can track the issues separately as the feature is in production now ?
