### ISSUE TITLE
[Bug]: [File picker widget] Remove allowed filetype restriction in filepicker widget

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#9907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be no restriction in allowed filetypes in filepicker widget. filetypes like ".csv", ".tsv" should be allowed.

### Why should this be worked on?

We need to allow App developers to have fine control over files types they want to allow in the file picker widget. Some of the App developers would want to allow only `.csv`, but currently, App developers need to allow `text/*` to do that. which would allow other file types as well.

**Comment by somangshu** [comment]
@sbalaji1192 is this really an enhancement, Given that if was working before?

**Comment by sbalaji1192** [comment]
@Nikhil-Nandagopal @somangshu This is not actually a bug in file picker widget. From file picker widget's perspective, we were never allowing CSV files to begin with. 
We had a bug on the validation side, because of that, if you enter a file type that was not allowed, we were not throwing the error. That issue got recently fixed as part of https://github.com/appsmithorg/appsmith/pull/9396/files.
So created this as an enhancement so we can extend the list with more options, not just `csv`.
