### ISSUE TITLE
[Feature]: Add option for "Radio Group" widget to be presented in horizontal position

### ISSUE THREAD

**Issue by tmdoit** [appsmithorg/appsmith#9908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently Radio Group widget is presented only in vertical position. This should works like for Switch Group widget, in responsive manner:
![Zrzut ekranu 2021-12-21 o 10 35 01](https://user-images.githubusercontent.com/85706044/146906852-e67ef5e6-3017-4943-b869-aec5b40c6e32.png)
![Zrzut ekranu 2021-12-21 o 10 35 08](https://user-images.githubusercontent.com/85706044/146906863-d43642ed-2b48-418c-82ee-41e78e3df5f7.png)

### Why should this be worked on?

There are cases where from UX perspective it's required presentation.

**Comment by dilippitchika** [comment]
PRD for this, can be a holistic change we bring about in all the widgets going forward. We will soon be working on the designs.

https://www.notion.so/appsmith/Radio-Switch-and-Checkbox-Group-widgets-Resize-09c64ebdeb76411a99888578a054aaf7

**Comment by yatinappsmith** [comment]
Horizontal Radio group is useful for feedback forms

**Comment by dilippitchika** [comment]
Linked to #10182

**Comment by dilippitchika** [comment]
hey @wmdev0808 i can see that you have added the inline option in radio group in #10600. Can you confirm? If yes, can you please link this issue to the PR?
