### ISSUE TITLE
[Bug]: Password reset message text have special character which needs to be removed from UI

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#9911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot (5)](https://user-images.githubusercontent.com/95341241/146915144-9cecf9d3-62b5-419a-8c69-b35f17211efc.png)

Attaching Screenshot of the message

Issue: Special characters are visible in popup message

### Steps To Reproduce

1. Go to Edit profile
2. Click on Reset Password
3. Check the message appears
4. Message is like: 
          ()=>"A reset password link has been sent to" username

### Environment

Production

### Version

Cloud

**Comment by danieldare** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> ![Screenshot (5)](https://user-images.githubusercontent.com/95341241/146915144-9cecf9d3-62b5-419a-8c69-b35f17211efc.png)
> 
> Attaching Screenshot of the message
> 
> Issue: Special characters are visible in popup message
> 
> ### Steps To Reproduce
> 1. Go to Edit profile
> 2. Click on Reset Password
> 3. Check the message appears
> 4. Message is like:
>    ()=>"A reset password link has been sent to" username
> 
> ### Environment
> Production
> 
> ### Version
> Cloud

The bug has been fixed and merged into the release branch.
