### ISSUE TITLE
[Bug]: columns with type `jsonb` displayed as `[Object object]` in form editor

### ISSUE THREAD

**Issue by sherifnada** [appsmithorg/appsmith#9924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when using the "generate page" option, `jsonb` postgres columns are parsed incorrectly which makes it difficult to edit them: 

![Screen Shot 2021-12-21 at 11 24 32 AM](https://user-images.githubusercontent.com/6246757/146986954-b2784929-e9ac-47c0-9caa-bec282f7d21b.png)

### Steps To Reproduce

1. Connect to a Postres DB one of whose columns has the `jsonb` type (I used the "generate page" option)
2. select a row
3. notice the issue

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@sherifnada thank you for reporting this. This is due to toString() added in the Input. You can remove that and it should work fine! We'll update the CRUD app

**Comment by Nikhil-Nandagopal** [comment]
Should be solved with JSON Form
