### ISSUE TITLE
[Bug]: No vertical scroll option when table has no pagination

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#9927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the table has quite a few rows that expand beyond the height of the widget and there is no pagination, user can not scroll down to bottom rows. The table only shows rows that fit inside the widget height.

### Steps To Reproduce

1. Add a table widget
2. Add a large array as data e.g. 30 rows
3. Disable pagination
4. You'll be able to see the records that fits in viewport only and no way to scroll down

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@nayan-rafiq This is being implemented as part of #2896 
The user can simply mark the table as serverside pagination and it will begin to scroll even if all their data is loaded at once
