### ISSUE TITLE
[Bug]: Tutorial page not found in Documentation

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Few documentations are throwing 'Page not found' when tried to access from Navigation bar.

Pages : Tutorial, Video & Radio
https://loom.com/share/aecd691ae74041b3918b555ba5629623

### Steps To Reproduce

1. In Homepage go to any application
2. In Quick search & Navigation  >  Search Documentation 
3.  Click on _Open Documentation_ for Tutorial and observe
4. Similarly for Video & Radio pages 

### Environment

Production

### Version

Cloud

**Comment by Rishabhkaul** [comment]
This is fixed
