### ISSUE TITLE
[Bug]: Issues on Authenticated API

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1) Query params are not displayed in the active section of DB
2) The number of  Query params are not displayed like that of the header in the API connection
3) On reopening the query params are not saved
4) Header must be displayed in a single line

### Steps To Reproduce

1) Navigate to Authentication API
2) Add Header field and Query Params 
3) Click on Save 
and observe 

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/95bac97522ef48c7b896cf882b601810-00001.gif)](https://www.loom.com/share/95bac97522ef48c7b896cf882b601810)

### Environment

Release

### Version

Cloud

**Comment by sumitsum** [comment]
Re-opening since FE side changes are required.
