### ISSUE TITLE
[Feature]: Upgrade to the latest LTS node version 16.*

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#9933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The LTS version of Node 16 is available. We should upgrade to that for active development & security updates. 

### Why should this be worked on?

Security updates are being shipped with Node 16. We should take advantage of that.

**Comment by sharat87** [comment]
Going by https://endoflife.date/nodejs, NodeJS v14 is EOL ~April2023. We need to upgrade, at least to v16, preferable to v20, progressively.

**Comment by sharat87** [comment]
Finished in https://github.com/appsmithorg/appsmith/pull/21320.

Opened new issue for upgrading to v18 at https://github.com/appsmithorg/appsmith/issues/21897.
