### ISSUE TITLE
[Bug]: After password reset user is able to login 2nd instance in the same browser with any random password character

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#9939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when a user resets the password and logins with new password the user lands to the home page, however in the same browser in a new tab the user can login successfully again by giving any random character as password.

https://loom.com/share/2d22e37c344744a68b6231f11d948eaa

### Steps To Reproduce

1. Go to https://release.app.appsmith.com/user/login
2. Give valid usn & pwd for User1 > In homepage > Edit profile > Reset password
3. Reset password to a new password > Back to Sign in
4. Give usn and new password for User1 > Home page must be seen
5. Now in a new tab go to https://release.app.appsmith.com/user/login
6. Give User1 email id and any _random characters in password field_ and click on login > Observe that homepage is seen for user1

### Environment

Release

### Version

Cloud

**Comment by sharat87** [comment]
Can you see if you can reproduce this if the other tab is in another Incognito window? I think what's happening here is that the random password you are entering isn't checked at all. The point is, you are already logged in in this browser session, so you're just redirected to the applications homepage without checking for your credentials. It's just as if you refreshed the page and tried to access the login or forgot-password links, you'll just be redirected to the applications list page.

I'm closing this now, but if this bug shows up when the other tab is opened in an Incognito session, that's a problem. Please feel free to reopen. Thanks!
