### ISSUE TITLE
[Bug]-[2800]:CRUD happens even with Read-Only access in MYSQL

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#9941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Update, delete functionality are working even if the datasource is authorized only for Read access.

### Steps To Reproduce

1. Create a Datasource of MYSQL with  Read Only Access
2. Try to update or delete using mysql query
3. Observe the table got updated in Read-only access

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
same happens for postgres too
6m usage: 1000+2500 = 3500
applying 20% requirement: 700

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3500 |
| Effort (months)  | 0.5 |

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 3500 |
| Effort (months)  | 0.25 |

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur @ajinkyakulkarni not everyone will need read only mode so I'm lowering the reach

**Comment by sumitsum** [comment]
It seems the issue exists with MySQL but not Postgres. Attaching the usage in Postgres: 

https://user-images.githubusercontent.com/1757421/180231770-bc581357-8a7f-4256-8d4d-e7b7347d45de.mov

**Comment by appsmithguru** [comment]
[Observations and RCA on this issue](https://www.notion.so/appsmith/DDL-DML-in-Read-Only-mode-in-DB-Datasource-038ffb9f48034170a3642e703b19d985)

**Comment by rohan-arthur** [comment]
Easy way to set this up:

1. Create datasource from [our notion page](https://www.notion.so/appsmith/Servers-and-Credentials-665f00d9505745d59db4f3b4eda27c79?pvs=4#02d45a9ecb944962a121e2237ea50c2b), ensure that it is marked `read only`
2. run query to get the total count: `SELECT COUNT(*) FROM a;`
3. run query to add a new row: `INSERT INTO a (PersonID, LastName, attendence, salary, joiningdate, logindateandtime, gross)
VALUES (12, 'new person', true, 100, '2024-01-01', '2024-01-02T08:00:00Z', 2);`
4. repeat the step to run query to get the total count: `SELECT COUNT(*) FROM a;`

You will see that the count is incremented by 1

**Comment by sneha122** [comment]
This looks like a bigger problem where we are taking the read only/read write input from user through datasource config form but we are not using this mode to configure the correct connection. 

As mentioned in this [notion doc](https://www.notion.so/appsmith/DDL-DML-in-Read-Only-mode-in-DB-Datasource-038ffb9f48034170a3642e703b19d985), only postgres and redshift has this functionality implemented, for others (mysql, mssql and mongoDB) it's not there. 

I checked the [r2dbc-mariadb documentation](https://r2dbc.io/spec/1.0.0.RELEASE/spec/html/#connections) to see if we have any way to configure this mode, it looks like we don't

The only immediate solution we have here is to remove this `connection mode` property from datasource form, so there is no confusion on whether we can configure this access or not and it will always connect with all permissions (as it is today)

Moving this to bugs with medium efforts, we can discuss and conclude what approach we want to take

CC: @rohan-arthur @sumitsum

**Comment by Nikhil-Nandagopal** [comment]
@sneha122 in that case it seems like a smaller problem and we should just remove the UI element :)

**Comment by sneha122** [comment]
@Nikhil-Nandagopal Yes that's a good preventive solution for now, till we figure out the connection mode for mysql. Will pick this up in upcoming sprint, Thanks!
