### ISSUE TITLE
[Bug]: Enforcing validation on the row value for widgets

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#9946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that for widgets with row value to be `rows: <FLOAT> * GRID_DENSITY_MIGRATION_V1,` e.g. `rows: 1.1 * GRID_DENSITY_MIGRATION_V1,` causes misalignment with the grid lines present on the canvas. 

This needs to be incorporated to maintain the integrity of the widget configs.

### Steps To Reproduce

Observe the line of code in the file: https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/CheckboxWidget/index.ts#L11

`    rows: 1.1 * GRID_DENSITY_MIGRATION_V1,`

### Environment

Production

### Version

Cloud

**Comment by riodeuno** [comment]
So far there are no dynamically loaded widgets, which means that we have access to all widget configs at build time. To resolve this issue, we can add unit tests as we have done for the property pane configurations.
