### ISSUE TITLE
[Bug]: New onboarding flow improvements DP testing

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- [ ] Evaluated value needs to close when user clicks on `Esc` key
![image](https://user-images.githubusercontent.com/79509062/147076292-3993ecd4-1eba-40a2-87df-8687db6b9b1e.png)

- [x] Orange indicator over Default text field is not center aligned
![image](https://user-images.githubusercontent.com/79509062/147077587-5e4a3742-7b73-4c54-af33-86730ca75452.png)

- [x] Errors for customerInfo query is displayed to user even before the query is displayed on the entity explorer (after completion of running the first query)

- [ ] On-boarding has a time limit, if app is left idle then on-boarding flow exits and regular canvas is displayed when user comes back to the app

- [x]  getCustomers query throws an error when the app freshly loads
![image](https://user-images.githubusercontent.com/79509062/147114781-0e0fbc3d-09cc-4d8f-b31e-82367aa10d4f.png)

- 

### Steps To Reproduce

.

### Environment

Release

### Version

Cloud

**Comment by ramsaptami** [comment]
- [ ] Spinning box needs to center aligned in the space available
![image](https://user-images.githubusercontent.com/79509062/147815275-fd6baeff-0132-4115-8916-a9f7a5ca5546.png)

- [ ] Navigating to canvas by clicking on the table widget centers the widget to viewport causing important information to be accessed only on scroll
https://www.loom.com/share/24412732292e43fb917b622c467efe7b

- [ ] Button widget added in step 6 does not allow user to drop just under image widget but once dropped settles at that spot
https://www.loom.com/share/f7d6c7395c724a31b2e0abbe79fdd5f8

-[ ] Yellow shade of the ratings widget at the last step

**Comment by akash-codemonk** [comment]
@ramsaptami latest dp link https://appsmith-rnzr4kwal-get-appsmith.vercel.app/.

**Comment by ramsaptami** [comment]
- [ ] Highlighted block for binding does not highlight the correct area of the app
https://www.loom.com/share/3db2780ebf374a139bab4a90d55570ba

- [ ] Rolling box is not center aligned to the line
![image](https://user-images.githubusercontent.com/79509062/147821243-05b88dcc-4bc1-4bc6-9b8f-426a094264d5.png)
![image](https://user-images.githubusercontent.com/79509062/147821270-82156184-cc74-4dc6-b9d5-7d2d2418444e.png)

- [ ] Rolling box should be present next the field label as seen in previous steps
![image](https://user-images.githubusercontent.com/79509062/147821435-66dab62a-03ba-4864-950c-7022b60fe5bf.png)
