### ISSUE TITLE
[Bug]: App crashes intermittently in CI

### ISSUE THREAD

**Issue by NandanAnantharamu** [appsmithorg/appsmith#9954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Intermittent application crashes noticed, this will help and reduce false alarms

### Steps To Reproduce

1. App crashes intermittently during test execution in CI.

Attaching the image/video and server logs

<img width="900" alt="Screenshot 2021-12-23 at 10 17 42 AM" src="https://user-images.githubusercontent.com/67676905/147189452-fbb53e01-eedb-47e1-9b46-eb543466da85.png">

https://user-images.githubusercontent.com/67676905/147189691-976feb45-c2a0-47c0-9c8c-9b466d3f418f.mp4

[server-logs-1.zip](https://github.com/appsmithorg/appsmith/files/7766754/server-logs-1.zip)

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
Looks like this is a very cypress thing because the application has not yet loaded and its searching for the element. For not changing the priority.

**Comment by riodeuno** [comment]
@somangshu The application seems to have loaded correctly for the first couple of tests, and it seems that the application crashes in the 3rd test. We need to look at this from a development standpoint and investigate the cause for the crash and fix it.

**Comment by somangshu** [comment]
@jsartisan could you take a look into this?

**Comment by jsartisan** [comment]
Not able to reproduce it on my machine. 😞 Will need some steps to repro it.

cc: @somangshu @yatinappsmith

**Comment by jsartisan** [comment]
Reducing the priority of this issue.
