### ISSUE TITLE
[Bug] Filepicker widget shows an invalid number of files has been uploaded

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#996]
## Steps to reproduce

1. Drag and drop the file picker widget
2. Click on edit prop, give max no files as eg: 2
3. Try to upload >2 files , widget shows 2 files are uploaded
4. Again try to upload > 2 files, 

## Observation

File Picker widget shows 3 files are uploaded

## Expected behaviour
File picker should show the number of files that are being uploaded currently.

**Comment by rishabhsaxena** [comment]
@prapullac couldn't reproduce, could you check this once?

**Comment by prapullac** [comment]
@rishabhsaxena : Unable to reproduce this issue. We can close the issue
