### ISSUE TITLE
[Bug]: Long page names gets truncated abruptly in view mode

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#9969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When page names have more characters it gets truncated abruptly in view mode.

![Screenshot 2021-12-23 at 5 21 22 PM](https://user-images.githubusercontent.com/41686026/147236691-9b3d6d21-13e1-434c-98be-98394f7b344e.png)

### Steps To Reproduce

-

### Environment

Production

### Version

Cloud

**Comment by areyabhishek** [comment]
This is not a bug, but it's a deliberate decision to make the design look good. Did we get a user request? I'd recommend not solving this unless we get a lot of requests.

**Comment by abhvsn** [comment]
Yes we did get a request for this but I can see this might mess up the UI. As you suggested we should wait for more user request and then come up with resolution here.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek @abhvsn I believe the correct solution here should be to ellipsize the name so it's clear that it is being truncated and if you hover you will probably see the full name.

**Comment by dilippitchika** [comment]
Do we have any standards in our design system or developed components on when to show ellipsis? We can just follow that to show it. If not, then can we include this problem in the design system?

**Comment by somangshu** [comment]
@dilippitchika as a general principal from the web, I think any text that is not allowed to overflow and has a no-wrap within a fixed width should have a ellipsis, Otherwise the user will always perceive that there text is not completely visible and its a bug

**Comment by dilippitchika** [comment]
Yup agreed @somangshu, I need help to understand what the **max width** of each tab should be before we show ellipsis.

**Comment by somangshu** [comment]
@dilippitchika max-width right now is `170px` and after that we ellipsize!

**Comment by somangshu** [comment]
Your solution does not work with Preview mode. @vicky-primathon reopening this, Please fix through another PR ASAP

@shwetha-ramesh please keep a note of this scenario for the future.
