### ISSUE TITLE
[Bug] Widget name gets hidden behind other elements

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#997]
https://www.notion.so/Widget-name-gets-hidden-behind-other-elements-e97e10357332460995a6cc750b9c6291

**Comment by jsartisan** [comment]
@Nikhil-Nandagopal Is this still happening? I am not able to reproduce this. 
Can you share the steps if you can reproduce this on your end?

**Comment by Nikhil-Nandagopal** [comment]
@jsartisan doesn't seem to be happening anymore. closing it
