### ISSUE TITLE
Button icon fix center position

### ISSUE THREAD

**Issue by connected201** [appsmithorg/appsmith#9970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i add new buton, and add new icon, text and icon move away in opposite directions

I expect center position to icon and text as in default placement settings
![yCByxO1HdR](https://user-images.githubusercontent.com/20506433/147246687-81bc9979-dfe9-4a32-8714-e5daa0dff87e.gif)

### Steps To Reproduce

Add button
Add icon
Again select placement to center

### Environment

Deploy Preview

### Version

Cloud

**Comment by dilippitchika** [comment]
@jsartisan can you help me understand why this behaves like this? Is it by design?

CC : @momcilo-appsmith

**Comment by somangshu** [comment]
This is a bug @dilippitchika, This is not happening for the older widgets. The alignment by default should be centered as shown on the property pane. 

cc @techbhavin

**Comment by momcilo-appsmith** [comment]
@somangshu agreed. I don't think this needs design input, this is a bug that needs to be fixed.
