### ISSUE TITLE
[Bug]: Table widget fails to pickup/handle utf8 column names from Google sheets

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#9973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The table widget fails to pickup/handle utf8 column names from Google sheets

### Steps To Reproduce

1. Create a sheet with utf8 column names
2. Use the Google sheet integration to display the data on a table widget

### Environment

Release

### Version

Cloud

**Comment by nickanti** [comment]
I believe there is already a ticket on this here:
https://github.com/appsmithorg/appsmith/issues/5445

**Comment by cokoghenun** [comment]
You're right. Closing this
