### ISSUE TITLE
[Bug]: Misalignment of page setting tooltip

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Misalignment of page setting tooltip in page setting page
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/bb291929495c4582ae2ea1e13ae9448f-00001.gif)](https://www.loom.com/share/bb291929495c4582ae2ea1e13ae9448f)

### Steps To Reproduce

1. Go to the page properties pane
2. Add 4 page 
3. Create a copy of a page 
4. Make the old page as invisible
4. now try to transpose the new page with the old page 
5. Verify the display of Pop up

### Environment

Production

### Version

Cloud

**Comment by RakshaKShetty** [comment]
Reopening the issue i am able to repro this issue in the firefox

**Comment by akash-codemonk** [comment]
@RakshaKShetty Please verify again. Have checked on safari and firefox as well. I am guessing you did not have the latest release.
