### ISSUE TITLE
[Bug]: Reloading the page shows the red dot on whats new

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith#9986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I reload the page, the red dot on "Whats new" reappears. It also shows wrong message - "Released 6 days ago" but the modal shows new release was today.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b1c636da067e4fdab9e4267994261b59-00001.gif)](https://www.loom.com/share/b1c636da067e4fdab9e4267994261b59)

### Steps To Reproduce

1. Go to home page
2. Click on release notes Whats new
3. The red dot disappears
4. Reload the page
5. The red dot reappears

### Environment

Production

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
No longer valid
