### ISSUE TITLE
[Bug]: Misalignment of Close and delete icon when user has a long page name

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Misalignment of Close and delete icon when the user has a long page 
![image](https://user-images.githubusercontent.com/45958978/147905584-a3f0d3c3-d43e-45c2-ad78-3817bd48aaaf.png)

### Steps To Reproduce

1. Go to page setting tab
2. Click on gear icon 
3. inside the pop up verify the display of delete and close icon 

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@RakshaKShetty the image upload link is broken
