### ISSUE TITLE
[Bug]-[48000]:The other page name changes by default when users change any one page name

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The other  page name changes by default when users change any one-page name 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/af3e4e7d840e498385bac2ba8459e3d4-00001.gif)](https://www.loom.com/share/af3e4e7d840e498385bac2ba8459e3d4)

### Steps To Reproduce

1. Go to page properties tab
2. Add 10 pages
3. Drag and drop the 10th page to the 3rd place
4. Now change the name of the 3rd page 
5. The name of the 4th page changes automatically

### Environment

Release

### Version

Cloud

**Comment by areyabhishek** [comment]
@RakshaKShetty this is a pretty bad bug. Is this easy to reproduce even with small number of pages? Asking because I can't reproduce this.

**Comment by RakshaKShetty** [comment]
Yes @areyabhishek. I could repro this issue with a small number of pages this is the link to repro the issue https://www.loom.com/share/8faaa59ee264416da5ee7726b355febc

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | 0.25 |
