### ISSUE TITLE
[Feature]: Allow users to turn off auto update & manually update their instance

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#9996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We should allow users to turn off auto-update from the "Admin Settings" page. As a user, I should also be able to click a button on the Settings page & update my Appsmith instance manually. This is in addition to the maintenance window that we already allow users to define in the `docker-compose.yml` file. 

This will allow users a lot more control over their maintenance experience of Appsmith. 

### Why should this be worked on?

While auto updates are great for letting users of Appsmith experience the latest & greatest features without having to go through an update cycle, at times there can be breaking changes within the product. This causes a lot of frustration for our users. 
auto-updates

**Comment by mohanarpit** [comment]
We can leverage Watchtower's [HTTP API](https://containrrr.dev/watchtower/http-api-mode/) to power the "Update Now" button.

**Comment by am-rpa** [comment]
Just wanted to say that this is a pretty important feature. As a business, we run a lot of risk by having an application like this auto update without first testing the update in a staging environment. This is based on the fact that having any kind of business critical workflows/applications in Appsmith that need to have a consistent environment to run in.

**Comment by arjunsriva-woven** [comment]
+1 would like to bump this feature agreeing with am-rpa, and add this is important for us from a security perspective too.

**Comment by fliot** [comment]
+1 auto update have some meaning, but must be disallowed and even hidden-able...

**Comment by Nikhil-Nandagopal** [comment]
This is now off by default so it's unnecessary
